### ISSUE TITLE
Outputs missing on new stack deployment

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#10018]
### What happened?

`pulumi preview` on an empty stack does not present stack outputs for `output<T>` outputs.

If the stack is already deployed, then the `pulumi preview` will present the `output<T>` outputs for new resources and related outputs 

### Steps to reproduce

1. `pulumi new aws-typescript` (behavior also seen with yaml and so may occur for other languages as well)
2. `pulumi preview` - this should present the `bucketName` output but shows no outputs.
3. `pulumi up` - no outputs will be presented during the preview phase, but will be presented upon deployment
4. If you then modify the index.ts to deploy a second bucket and output the second bucket's name and do a `pulumi prevew` it will present the `output<T>` output as expected.

### Expected Behavior

`pulumi preview` on new stacks should not only show me the resources that will be deployed but list the outputs even if the value is not yet known.

### Actual Behavior

`pulumi preview` on new stacks does not show the outputs.

### Versions used

CLI          
Version      3.35.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.9.2
docker  3.2.0
nodejs  unknown

Host     
OS       darwin
Version  12.4
Arch     x86_64

This project is written in nodejs: executable='/Users/mitch/.nvm/versions/node/v18.0.0/bin/node' version='v18.0.0'

Current Stack: dev

TYPE                  URN
pulumi:pulumi:Stack   urn:pulumi:dev::output-test::pulumi:pulumi:Stack::output-test-dev
pulumi:providers:aws  urn:pulumi:dev::output-test::pulumi:providers:aws::default_5_9_2
aws:s3/bucket:Bucket  urn:pulumi:dev::output-test::aws:s3/bucket:Bucket::my-bucket

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/XXXXX
User           XXXXX

Dependencies:
NAME            VERSION
@types/node     14.18.21
@pulumi/aws     5.9.2
@pulumi/awsx    0.40.0
@pulumi/pulumi  3.35.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Wow. I think that every engineer at Pulumi have seen this behavior dozens of times... but never raised an issue? For my sanity, I checked 3.0.0 and it behaves the same way. Our gettings started guides show stdout without outputs. How come nobody complained?

Anyway, it's a great find @MitchellGerdisch and looks like a simple fix in a piece of code that is 3-4 years old: https://github.com/pulumi/pulumi/pull/10031
