### ISSUE TITLE
Pulumi is trying to replace all my resources after upgrading to v3.35.2

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi#10020]
### What happened?

This is quite a weird issue that I've seen twice after upgrading to Pulumi v3.35.2. I have around a dozen Pulumi stacks and after Pulumi v3.35.2 came out I was going through all the stacks and making sure that everything was up to date, using `--target` to update resources in a methodical way.

I'm not sure exactly how, but on two of those stacks, after upgrading the provider resource, Pulumi then tried to replace _all_ the resources in the stack, no longer recognising the auto generated suffixes from previous runs. This means that on a certain Pulumi run, Pulumi wanted to apply changes to 3 resources, but after that was finished he now wanted to apply to 100+ resources, replacing all of them.

I kind of managed to replicate this behaviour by importing a previous version of the stack and this happened everytime I upgraded the provider on that particular stack that was prone to get the issue. The vast majority of my stacks didn't exhibit this bad behaviour and they updated well. By diffing the stack exports I've noticed that a new entry, "sequenceNumber` was added to the resources on the stack. This feels relevant, but I can't prove it.

To fix this issue I reverted the stack to a good state and then grabbed another computer that had the exact same version of the providers installed, but was still running Pulumi v3.35.1. After I updated the stack in full I could then go to Pulumi v3.35.2, and the updates there no longer tried to replace all my resources.

### Steps to reproduce

I was able to reproduce the error _after_ I got the error, I'm not sure how to reproduce it from scratch. All I know is that I had all the providers on their latest versions (for example pulumi-aws and pulumi-azure), then I upgraded to Pulumi v3.35.2 from v3.35.1 and the stack broke after the provider resource got upgraded. This also feels related to Pulumi AWS somehow, which is the vast majority of the resources on my stacks, but I can't prove it.

### Expected Behavior

Pulumi shouldn't try to replace resources.

### Actual Behavior

Pulumi was trying to replace all or almost all of my resources.

### Versions used

CLI
Version         3.35.2
Go Version    go1.17.11
Go Compiler  gc

Host
OS           ubuntu
Version      21.10
Arch          x86_64

Dependencies:
NAME                 VERSION
boto3                1.24.19
dnspython            2.2.1
flake8               4.0.1
pip                  22.1.2
pulumi-aiven         4.5.2
pulumi-aws           5.9.2
pulumi-azure-native  1.66.0
pulumi-azuread       5.25.0
pulumi-opsgenie      1.1.6
pulumi-random        4.8.0
pulumi-tls           4.6.0
setuptools           62.6.0
wheel                0.37.1

### Additional context

I know that this report doesn't give you much to work with, but at least it raises awareness and provides a solution. I was bit by this twice right after the upgrade to v3.35.2, so maybe I'm not the only one.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
> after upgrading the provider resource, Pulumi then tried to replace all the resources in the stack, no longer recognising the auto generated suffixes from previous

Do you have any details on what you mean by this?  Certainly, if your provider resource needs to be replaced, that is the sort of thing that can cause all other resources to believe they need to be replaced.  But the exact details of what would be expected would depend a bit on what specific steps you took to trigger this.

**Comment by Sodki** [comment]
The provider wasn't replaced, just updated. Here I have a snippet of a `pulumi pre --diff` which would have triggered the problem:

```
    ~ pulumi:providers:aws: (update)
        [id=0ffcd62c-c7d9-4033-9dfb-1093afc85cb6]
        [urn=urn:pulumi:<redacted>::lytt::pulumi:providers:aws::ld-eu-west-1]
        assumeRole               : (json) {
            role_arn: "<redacted>"
        }

        region                   : "eu-west-1"
      ~ skipCredentialsValidation: "true" => "false"
        skipGetEc2Platforms      : "true"
        skipMetadataApiCheck     : "true"
        skipRegionValidation     : "true"
      ~ version                  : "5.5.0" => "5.9.2"
```

Allowing this to execute on a machine with Pulumi 3.5.2 would trigger the issue, but not on a machine with Pulumi 3.5.1. I find it baffling as well, but I hit this problem twice, which kind of even makes it worse, since I ran this against a dozen stacks, or so.

**Comment by lukehoban** [comment]
Do you see the same update shown above even in cases where you don't see the replace of other resource?  Or do you only see this update diff in the same cases you see a replace of other resources?

**Comment by Sodki** [comment]
That `pulumi pre` is before the problem is triggered. Unfortunately I don't have one after the problem is triggered and I can't remember if the provider was there or not. But still, there was no code change between there two runs, so the provider should have had no dramatic changes to it.

**Comment by Sodki** [comment]
One thing that I remember is that the update to the provider happened even when I was using `--target` against specific resources and not specifying the provider directly. I'm pretty sure I never targetted the provider itself, since this is something that I never do.

**Comment by lukehoban** [comment]
I wonder if this is related to https://github.com/pulumi/pulumi/commit/7ebba683d905e7cc50ac210e0d7cb6d6c523d184. Cc @Frassle 

Marking p0 at least until we identify the true scope of the issue here.

**Comment by Sodki** [comment]
FYI I have a third stack with the same symptoms. I'm running `pulumi up` with `--target`, v3.5.2 wants to update the provider without being prompted, while v.3.5.1 does not. Seems to be the same thing that was happening before. If you need me to run anything for debugging purposes, let me know.

**Comment by Frassle** [comment]
Looks like https://github.com/pulumi/pulumi/commit/7ebba683d905e7cc50ac210e0d7cb6d6c523d184 triggered this. Targetted updates do have some complexities and looks like we didn't have tests to catch all of them. I'm going to revert that change and publish a patch release and reopen https://github.com/pulumi/pulumi/issues/9869.

**Comment by Frassle** [comment]
3.35.3 has been released.
