### ISSUE TITLE
Allow alternate way to specify entrypoint for node.js runtime

### ISSUE THREAD

**Issue by cfeenstra67** [pulumi/pulumi#10022]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

At the moment, my team has a codebase that is structured as a typescript monorepo we manage with `lerna`. We deploy absolutely everything with Pulumi and love it, however we've run into a slight challenge when it comes to entry points.

Basically the way our project is structured is as follows:
```
- <root>/
  - <supporting files>
  - packages/
    - application1/
      - Pulumi.yaml
      - Pulumi.application1-staging.yaml
      - Pulumi.application1-prod.yaml
      - <application1 source code/supporting files>
    - <other packages>
    - infra/
      - src/
        - index.ts <- the entry point we use for all stacks
        - <other pulumi code files that are imported into `index.ts`>
      - <package.json, tsconfig.json, other supporting files>
```
The idea is that all of the pulumi code is in the `infra` package and totally independent from our application code. Each application has typically two stacks associated with it: a `prod` version and `staging` version. Each of those stacks has at least one configuration option: `stack-type`. In the simplest case, the `Pulumi.application1-prod.yaml` file would look like this:
```yaml
config:
  application1:stack-type: application1
```

Then in our entry point, we have a `switch` that reads this configuration and calls the proper function that actually contains the Pulumi code, something like:
```typescript
import * as pulumi from '@pulumi/pulumi';
import { application1Stack } from './application1';

export = async () => {
  const config = pulumi.Config();
  const stackType = config.require('stack-type');
  switch (stackType) {
    case 'application1':
      return await application1Stack();
    default:
      throw new Error(`Invalid stack type ${stackType}`);
  }
}
```

Overall this works really well, and makes for great code reuse in our Pulumi code. However, in order for this to work, every package that has stack(s) associated with it has to set the following configuration in their `package.json`:
```json
{
  ...
  "main": "../infra/src/index.ts"
  ...
}
```
This is not ideal, since the `main` key means something to JS and TS that has nothing (directly) to do with Pulumi--that defines what the entry point is when _importing_ the package. Since we use Typescript for everything, generally each package has a `build` script that calls `tsc` and compiles the typescript files into JS/declaration files in a `dist/` directory within the package directory.

Ideally, we'd like to be able to set `main` to be `dist/index.js`, as that way when importing things from that package we can simply `import { Something } from '@mypackage/application1'`. However, since the `main` entry point is already being used by Pulumi we have to import things directly from the `dist` directory instead, something like  `import { Something } from '@mypackage/application1/dist`.

This is mostly just a minor annoyance. It also means that in contexts where we're compiling things via webpack, which will happily compile typescript files on the fly rather than having to have a separate `build` command, we can still import via the top-level package name without `dist`, whereas in regular node contexts we always have to include the `dist` part of the path. This leads to some confusion and inconsistency in our codebase. We could _always_ include `dist` in the path, but it still irks the perfectionist in me a bit.

We could also have all our stack configuration files in the `infra` directory, but this requires a lot of directory switching--generally when working on a project I sit in the directory of the package I'm working on, so being able to run `pulumi up` from there directly is a nice experience. Also, when they're in package directories, pulumi is smart enough to only include those stacks when running `pulumi stack select`, so we don't have to scroll through a bunch of stacks or type out the full stack name to select the one we want. It also wouldn't allow us to have project-specific `Pulumi.yaml` files (though this is not really that important--having the correct project name associated with each stack just seems conceptually correct to me, that's the only real difference I can think of).

#### Proposed Solution
So basically the proposal would be that there's some way for us to define a pulumi-specific entry point without using the `main` key. Either having it in `Pulumi.yaml` or under `pulumi` key in `package.json` both seem like they would make some sense, but probably there are many other ways to solve the problem as well.

Anyway, love the product! Hope I didn't overwhelm you with irrelevant details here, I was trying to capture the entire use-case as much as possible. Happy to put together an example repo if my description is not clear. I'm quite a novice when it comes to opening Github Issues, so if I did anything wrong here please let me know.

### Affected area/feature

node.js runtime

**Comment by mikhailshilkov** [comment]
Hi @cfeenstra67, thank you for the detailed description! We love that dedication, definitely not overwhelming!

I think you can do this today. I tried a hello-world TS project sand renamed `index.ts` to `index2.ts`, then changed my `Pulumi.yaml` to

```yaml
name: azure-nextgen-play-ts
runtime: nodejs
main: index2.ts
```

and it just works. Could you give this a try?

**Comment by cfeenstra67** [comment]
@mikhailshilkov amazing! Thanks for pointing that out--that key does appear to be respected. One suggestion might be to update the documentation to reflect this option; I may have missed it, but I've spent lots of time reading the documentation and don't remember coming across that option (or maybe since it's at the top level/applies to any runtime it's just not in the node.js-specific documentation and that tripped me up).

I still can't quite get it to work perfectly for me, though. The problem is that setting the `main` key as you have there changes the current working directory when running Pulumi to the parent directory of `main`. This causes two issues:

- Pulumi doesn't use the correct `tsconfig.json` file, so I end up getting a compilation error due to the default `tsconfig` targeting an older JS version (specifically `Object.fromEntries()` causes the error). I poked around a little bit in the source code and found the `PULUMI_NODEJS_TSCONFIG` environment variable here: https://github.com/pulumi/pulumi/blob/f3e430a1da2b665f29d711b9f1bfd9b9c7f240cc/sdk/nodejs/cmd/pulumi-language-nodejs/main.go , if I set that to `../tsconfig.json` it picks up the correct `tsconfig`. It seems like there should be some way to pass this via the `Pulumi.yaml` file, but I tried the following and it doesn't seem to work:
```typescript
name: application1
main: ../infra/src/index.ts
runtime:
  name: nodejs
  tsconfig: ../tsconfig.json
  # Also tried using the `tsconfigpath` key w/o success as well
```
Is there some way to pass this in the `Pulumi.yaml` file?

- My pulumi code is actually importing code from a shared package in one case, and that shared package loads some templates from the filesystem which are then uploaded to AWS SES in the pulumi code. These are referenced with relative paths, since otherwise the path references break when running code situated in the `./dist` directory vs. running the source code directly w/ `ts-node` or some other method. Since the `main` key causes the current working directory to change, these relative paths also break. I can probably find some workaround for this, but if there's a simple solution it'd be nice to not have to jump through too many hoops. If there's some way to explicitly pass current working directory in `Pulumi.yaml`, that would solve the issue.

Neither of these are a huge deal, I can probably get it to work from here myself in some way or another. Just wanted to check if either had an easy solution. Thanks again!

**Comment by cfeenstra67** [comment]
Just to follow up here: I was able to get this working w/ the given solution for me, so this issue can be considered resolved for me at least. I was able to work around the issues above by making the two following changes:
- moving my `infra` `main` script from `src/index.ts` to `index.ts`, and setting the `main` key (in the _pulumi_ config) for other projects to `../infra/index.ts`. This causes pulumi to use the `infra/tsconfig.json` file for configuration, so I don't get a compilation error.
- making my code that references relative paths just check for the files in multiple places, to handle both the case when we're running source code directly w/ `ts-node` and when it's sitting in the `dist/` directory. This is more robust anyway, as it means that the code can be run from anywhere without the paths failing to resolve.
With these two changes, I'm able to import my packages w/ their top-level names by pointing the `main` key in `package.json` to `dist/index.js` just as I want to.

**Comment by mikhailshilkov** [comment]
Thank you for the follow-up, great to hear it's working for you!

**Comment by kimdhamilton** [comment]
it would be ideal to have this better documented -- this has been tripping me up too

**Comment by nick-verida** [comment]
It's be great to have an example of this somewhere. Decoding the correct project layout isn't obvious.

**Comment by RobbieMcKinstry** [comment]
@samox73 I presume you mean loading tsconfig from a parent directory? That work is being tracked [here](https://github.com/pulumi/pulumi/issues/12780). However, the workaround for now is to use a symlink to the parent directory.

Pulumi already loads `tsconfig` files from the Pulumi "root" directory _i.e._ the directory where Pulumi is executed from.
Does that help?

**Comment by edgehero** [comment]
> Hi @cfeenstra67, thank you for the detailed description! We love that dedication, definitely not overwhelming!
> 
> I think you can do this today. I tried a hello-world TS project sand renamed `index.ts` to `index2.ts`, then changed my `Pulumi.yaml` to
> 
> ```yaml
> name: azure-play-ts
> runtime: nodejs
> main: index2.ts
> ```
> 
> and it just works. Could you give this a try?

@mikhailshilkov also running into this issue, how to fix this? azure forces me to set for the azure functions a main in the package.json. but i want to force pulumi to ignore that main in package.json, setting a main in Pulumi.yaml does not fix this issue because it still uses the main from package.json

**Comment by mikhailshilkov** [comment]
@edgehero Are you using the same package.json both for you Pulumi program and for an Azure Function? Is it because you are using callback functions? Anyway, it would be useful to open a new issue and describe your use case in case the above discussion does not apply to you. Note that we may miss comments on old closed issues...
