### ISSUE TITLE
pulumi stack change-secrets-provider command ignores the --stack flag

### ISSUE THREAD

**Issue by sisrael-dn** [pulumi/pulumi#10045]
### What happened?

Currently, you must select stack before running `pulumi stack change-secrets-provider` command as it is not using the stack name provided to it in the `-s` or `--stack` flag

### Steps to reproduce

- Create some stack
- Unselect your stack (if selected)
- Run `pulumi stack change-secrets-provider <provider> -s <stack_name>`

### Expected Behavior

Pulumi.stack_name.yaml is updated with `secretsprovider`

### Actual Behavior

- If there is some other stack marked as selected : Pulumi.other_stack_name.yaml is updated with `secretsprovider` instead
- If there is no stack selected on interactive mode : Pulumi asks you to choose a stack 
- If there is no stack selected on non-interactive mode : Pulumi 'no stack selected' error

### Versions used

3.35.3

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi @sisrael-dn, thanks a lot for filing the issue and for the repro details. It is indeed a bug in the CLI and we will fix it as soon as possible. Will keep you posted
