### ISSUE TITLE
command dispatch workflows aren't taking PR branches into account

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi#10058]
We have a few workflows that we execute via command dispatch triggered by comments on PRs. e.g. /run-acceptance-tests. Unfortunately these workflows aren't taking the PR branch into account and so end up just running on master.

We should fix up and test that /run-acceptance-tests, /run-integration-tests, /run-docs-gen, and /run-codegen all work correctly on PRs, and for non-pulumi org users.

**Comment by Frassle** [comment]
Tracked down the core reason for this. We chose the ref to checkout with env.PR_COMMIT_SHA, and we do set that env var at the top of the run-integration-tests workflow. But build is a resusable workflow (https://docs.github.com/en/actions/using-workflows/reusing-workflows) and ....
> Any environment variables set in an env context defined at the workflow level in the caller workflow are not propagated to the called workflow. For more information about the env context, see "[Context and expression syntax for GitHub Actions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#env-context)."

**Comment by AaronFriel** [comment]
I think we can trigger the workflow by getting the commitish or ref `refs/pull/$PRNUMBER/merge`. 

I think that might be available as a context variable `${{ github.event.pull_request.??? }}`.

**Comment by Frassle** [comment]
Yup the dispatch workflow already _try_ to sue the context variable, but they use it to set an envvar which doesn't get passed down: https://github.com/pulumi/pulumi/blob/master/.github/workflows/run-build-and-integration-tests.yml#L13

**Comment by AaronFriel** [comment]
Ah - yep. That needs to be passed as an input to the other workflows. 👍 Makes sense.

**Comment by AaronFriel** [comment]
This was marked fixed a little prematurely, but it is now properly fixed: https://github.com/pulumi/pulumi/pull/10749#issuecomment-1254522437
