### ISSUE TITLE
Filename `plugin.proto` is too generic, leading to conflict

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#10066]
### What happened?

I bumped into this error as part of my hackaton work on contract based testing of a provider, using `pact-go` together with the Go pulumi sdk, both registering `plugin.proto`:

```
panic: proto: file "plugin.proto" is already registered
        previously from: "github.com/pact-foundation/pact-go/v2/internal/native"
        currently from:  "github.com/pulumi/pulumi/sdk/v3/proto/go"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

### Steps to reproduce

I have my hackaton work in this branch:

https://github.com/ringods/pulumi-github/tree/pact-testing

The first commit contains the plain setup with which I encountered the problem using the latest tagged version of the pulumi SDK, together with the then released beta version of `pact-go`.

After bumping into the problem, I [reported this](https://github.com/pact-foundation/pact-plugins/issues/4) with the `pact-go` team, they updated their code and released a new beta version on the same day. Later commits on my branch take in this new beta version, which resolves it now between Pulumi and Pact codebases.

### Expected Behavior

Multiple projects should be able to register their protobuf definitions.

### Actual Behavior

Since [protobuf-go v1.26](https://github.com/protocolbuffers/protobuf-go/releases/tag/v1.26.0), such a filename collision generates a panic.

### Additional context

Although both files have different `go_package` directives, as you can see here:

*  https://github.com/pulumi/pulumi/blob/master/sdk/proto/plugin.proto
*  https://github.com/pact-foundation/pact-plugins/blob/f0fdfefef0099518635329a6deab424961690b62/proto/plugin.proto

this doesn't seem to be enough. The filenames need to be unique as well, according this comment on the `protobuf` project:

https://github.com/golang/protobuf/issues/1122#issuecomment-853158260

I strongly suggest to that we also rename our protobuf file to e.g. pulumi-plugin.proto or pulumi/plugin.proto to prevent future filename collisions.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I'm not sure what knock on doing a rename here will have on providers. I'd like to move the proto files to be something like "/proto/pulumi/plugin.proto" and to then build them as "pulumi/plugin.proto" so we get the namespacing.

**Comment by ringods** [comment]
@Frassle I tried renaming the proto file to `pulumi-plugin.proto` locally on my machine during the hackaton and regenerated the SDKs. Besides the Go SDK, the other language SDKs had a lot of renamed files also including the the `pulumi-` prefix, which might have an effect on language specific `import`/`require`/... statements. 

If we are able to rename the proto file without having the generated SDK files having renamed files, there won't be any impact on the SDKs then (IMO).
