### ISSUE TITLE
Pulumi v3.35.3 pulumi import aws:lambda/function:Function produces incorrect code

### ISSUE THREAD

**Issue by c-goosen** [pulumi/pulumi#10067]
### What happened?

Outputs this:
```python
knime_step_1 = aws.lambda_.Function("test",
    architectures=["arm64"],
    environment=aws.lambda..FunctionEnvironmentArgs(
        variables={
            "test": "test",
```            
Instead of :
```python
knime_step_1 = aws.lambda_.Function("test",
    architectures=["arm64"],
    environment=aws.lambda_.FunctionEnvironmentArgs(
        variables={
            "test": "test",
```
aws.lambda..Function vs aws.lambda_.Function for environment

### Steps to reproduce

pulumi version
v3.35.3

pulumi import aws:lambda/function:Function test test-lambda

### Expected Behavior

aws.lambda_.Function

This includes other things like 
aws.lambda..FunctionFileSystemConfigArgs
aws.lambda..FunctionEphemeralStorageArgs

### Actual Behavior

aws.lambda..FunctionEnvironmentArgs

Correct python library references

### Versions used

v3.35.3

### Additional context

Mac OSX M1 Pro

Python 3.10.5

Import existing aws resources

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Is this for TypeScript?

**Comment by Frassle** [comment]
cc @iwahbe as you've made a load of codegen changes recently, you might know what tripped up this.
