### ISSUE TITLE
`pulumi about`/`pulumi plugin install` don't search up the directory tree whereas `pulumi (preview, up, down)` uses node and finds the correct plugings

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#10069]
### What happened?

`pulumi about`/`pulumi plugin install` do not search up the file tree for a package.json when called from a directory with a Pulumi.yaml which is below the package.json, and we repro’d this with a simple test case. This might be a regression, since it’s a fairly common project layout, and no longer follows the “standard” node.js resolution model.

### Steps to reproduce

1. create a new pulumi typescript program
2. move `*.yaml`, `index.ts` to a non-root directory
3. run `pulumi about`

### Expected Behavior

It should resolve all the way up to the folder containing `node_modules` or `.git`

### Actual Behavior

pulumi about
CLI
Version      3.35.3
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/rshade/.nvm/versions/node/v16.15.0/bin/node' version='v16.15.0'

Backend

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's plugins: Could not find either /home/rshade/github/pulumi_projects/aws-eks-ts/programs/eks/yarn.lock or /home/rshade/github/pulumi_projects/aws-eks-ts/programs/eks/package-lock.json

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi there @rshade thanks for filing the issue and for the details about the repro, we really appreciate it 🙏 I was able to see the  error message on my local machine both for a typescript program. The CLI should recursively look up parent directories until it finds a package-lock.json or yarn.lock

**Comment by shubbham1215** [comment]
I would like to contribute and work on this issue. Can you please assign to me?

**Comment by h20220025** [comment]
hi @rshade, This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?
