### ISSUE TITLE
python sdk missing README.md

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#10080]
### What happened?

https://github.com/pulumi/pulumi/blob/1d0f50581f9e5c0233b4e3ae291806cf2cd4620a/sdk/README.md says to check the README.md for python and there is no README.md

### Steps to reproduce

go to https://github.com/pulumi/pulumi/blob/1d0f50581f9e5c0233b4e3ae291806cf2cd4620a/sdk/README.md and click the link to python

### Expected Behavior

README.md exists

### Actual Behavior

doesn't exist

### Versions used

v3.35.3

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by vaibhavkoshti7** [comment]
hello @RobbieMcKinstry . I would like ti work on this issue . Can you assignme this?

**Comment by vaibhavkoshti7** [comment]
Hello @RobbieMcKinstry .I would like to work on this issue. Can you assign me this.

**Comment by RobbieMcKinstry** [comment]
Hi @vaibhavkoshti7 Sure! Thanks for offering to help!

**Comment by opeseyi** [comment]
@RobbieMcKinstry is this issue still open?

**Comment by Frassle** [comment]
> is this issue still open?

It is.

**Comment by vaibhavkoshti7** [comment]
I'm working on this.

**Comment by h20220025** [comment]
hi @vaibhavkoshti7, can you suggest any issue that will be good initiation of my journey towards contribution to FOSS projects.

**Comment by RobbieMcKinstry** [comment]
Hi @h20220025 , thanks for offering to become a FOSS contributor. We keep a [list of issues for first-time contributors](https://github.com/pulumi/pulumi/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue) for this repo. Some of our other repos keep similar lists. For example, the [Pulumi GitHub Action](https://github.com/pulumi/actions/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-issue) and [the Pulumi Docker containers](https://github.com/pulumi/pulumi-docker-containers/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-issue).

Feel free to contact me on the [Pulumi Community Slack](https://slack.pulumi.com/) if you want to contribute and talk through an issue.
