### ISSUE TITLE
Changing provider of an AWS resource deleted the resource

### ISSUE THREAD

**Issue by mohitreddy1996** [pulumi/pulumi#10082]
### What happened?

We attach an Amazon Managed IAM policy using it's ARN to an IAM role. The code snippet looks as follows:

```
function setupAccess(provider) {
    const c = new aws.iam.RolePolicyAttachment(`policy-attach`, {
        policyArn: ARN_TO_POLICY,
        role: inputIamRole,
    }, { provider: provider });
}

const provider = new aws.Provider("aws-provider-iam-attach", {
// region and assumeRole set
}); 

setupAccess(provider);
```

We refactored the code a bit and ended up moving the function `setupAccess` to a different file/module which creates it's own provider (different name, but using the same region and assumeRole configuration as this).

When we update the stack, we see the following logs:

```
 ++ aws:iam:RolePolicyAttachment policy-attach creating replacement [diff: ~provider]

....


 ++ aws:iam:RolePolicyAttachment policy-attach created replacement [diff: ~provider]

....

 +- aws:iam:RolePolicyAttachment policy-attach replacing [diff: ~provider]
 +- aws:iam:RolePolicyAttachment policy-attach replaced [diff: ~provider]

....

 -- aws:iam:RolePolicyAttachment policy-attach deleting original [diff: ~provider

...

 -- aws:iam:RolePolicyAttachment policy-attach deleted original [diff: ~provider]
```

In the summary output of the stack, we see:
```
--  aws:iam:RolePolicyAttachment policy-attach           delete-replacedd
```

In AWS, we no longer see `ARN_TO_POLICY` attached to the `inputIamRole`

### Steps to reproduce

Documented above

### Expected Behavior

Changing the provider should not result in deletion of the original resource

### Actual Behavior

Changing the provider resulted in deletion of the original resource

### Versions used

CLI
Version      3.30.0
Go Version   go1.18.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.6.0
aws         4.38.1
command     0.0.3
confluent   0.2.2
docker      3.1.0
eks         0.39.0
kafka       3.1.2
kubernetes  3.16.0
mysql       3.1.0
nodejs      unknown
postgresql  3.4.0

Host
OS       darwin
Version  12.4
Arch     arm64

This project is written in nodejs (/nix/store/93vxiv2i2bmqs5kw49q1zn7l83nkglpa-nodejs-18.4.0/bin/node v18.4.0)

Backend
*truncated* 

NAME                VERSION
@pulumi/pulumi      3.28.0
netmask             2.0.2
typescript          4.6.2
uuid                8.3.2
@pulumi/eks         0.39.0
@types/node         17.0.21
@pulumi/kubernetes  3.16.0
@pulumi/confluent   0.2.2
@types/uuid         8.3.4
ts-md5              1.2.11
@pulumi/aws         4.38.1
@pulumi/docker      3.1.0
@pulumi/kafka       3.1.2
@pulumi/mysql       3.1.0
@pulumi/postgresql  3.4.0
process             0.11.10
ts-node             10.6.0
@pulumi/command     0.0.3

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @mohitreddy1996, sorry for the confusion. This is a know issue, so I'm going to close as duplicate. You can track progress towards fixing the issue in the original issue: https://github.com/pulumi/pulumi-aws/issues/2009.
