### ISSUE TITLE
Prevent data races from being released

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#10092]
As evidenced by #10081, we have some evidence of a few data races in the Pulumi engine, and we'd like to prevent races.

Unfortunately the race detection flag `-race` dramatically reduces the speed of tests, and implementing this today would negatively impact CI throughput and cycle time.

We could:

- Use the `-race` flag on a subset of tests we think have good coverage.
- Enable the `-race` flag for all tests after completing #10091 
- Use a scheduled GitHub action to run tests comprehensively with `-race`

---

Related issues: #8466, #1605, #11727, #11790

**Comment by Frassle** [comment]
> Use a scheduled GitHub action to run tests comprehensively with -race

I'd like this more generally. I always feel there's three sets of tests you want:
1. Quick PR tests
2. Slower more thorough main branch tests (which https://github.com/pulumi/pulumi/issues/10091 would cover)
3. Very slow, very thorough nightly tests (Not sure when's "night" for us...).

**Comment by RobbieMcKinstry** [comment]
I personally prefer:

> enable the `-race` flag for all tests

Because it's possible (and easy) to introduce races during day-to-day work, I think race detection should be on for all PRs. IMO races are dangerous enough that we should prefer them from landing on `master` at all. In short, the value provided by the `-race` flag on PR outweighs the cost to CI IMHO.

This isn't a hill I'll die on, so if the team disagrees I'm happy to support a different decision.

**Comment by AaronFriel** [comment]
I think I agree with @RobbieMcKinstry for the most part. Fortunately I think there are large classes of tests that won't be impacted by adding `-race` or which we could remove `-race`, and doubly fortunately those are are slowest sets of tests. I still wouldn't want to turn this on by default until we have #10091, but it would allow us to run them on every PR.

1. Integration tests, to a first approximation 100% of their time is waiting for the `pulumi` CLI or copying files in the OS.

   I'd be surprised if adding `-race` impacted this at all.

3. Codegen & docs tests, which again, to a first approximation spend 100% of their time copying bytes in memory or files in the OS, and have _zero_ impact on the average users' workflow.

   We could have a `-race` enabled test that runs a subset of these, but there's no need to run most of these under `-race`. If we have non-deterministic output as a result of a data race, that fails because our codegen tests are snapshot tests, comparing their output to a committed artifact.

**Comment by Frassle** [comment]
If this can be added to the merge on master tests without too much impact, both not taking _too_ long to get through the patch queue, and not taking too much engineering time to maintain the subsets, then I'd be happy with them there. If either of those impacts is large than I'd suggest making these a nightly/daily test set (where you could probably simplify the engineering impact by just say run test on everything, runtime cost doesn't matter so much).

**Comment by abhinav** [comment]
We could mitigate the merge-to-master hit a bit more by making only PRs run with `-race`; merge-to-master can continue to run without. Cases where something passes during a PR but not when merged with another change are possible but should be rare.

As a data point on the periodic job: that's what [Uber's Go monorepo uses](https://www.uber.com/blog/dynamic-data-race-detection-in-go-code/) but it's much much larger.

**Comment by AaronFriel** [comment]
Now that we have bors (#10091) I'd be totally fine with adding `-race` to the merge queue checks.

Checks that only run on PRs are worth little more than what they prevent users from merging: nothing.
