### ISSUE TITLE
Reduce PR blocking and keep trunk green with merge queues

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#10091]
We would like to prevent false results in our testing system and increase CI velocity by moving many of our CI checks to a step _between_ clicking merge PR and the result being placed onto the master branch.

This could occur via the [bors bot](https://bors.tech/) or likely later this year, [GitHub merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue).

**Comment by AaronFriel** [comment]
This is also blocked, as noted in a design meeting, by having a method of producing release notes / a changelog that doesn't require each PR commit to the same file.

**Comment by iwahbe** [comment]
We have this as a separate issue: https://github.com/pulumi/pulumi/issues/9945.
