### ISSUE TITLE
PATH environment variable is reset to "venv\Scripts" in python programs on Windows

### ISSUE THREAD

**Issue by bl-ue** [pulumi/pulumi#10102]
### What happened?

I have a very simple Pulumi python program on Windows, generated with `pulumi new aws-python`. I replaced the contents of `__main__.py` with code to print the `PATH` environment variable. When I run `pulumi up`, the `PATH` is empty except for the `venv\Scripts` directory from my virtual environment.

Since the system's `PATH` variable is not being passed to my code, calls to external executable (e.g. `yarn`) aren't working. This makes the area of the application that calls external programs unuseable on Windows, except for hard-coding the absolute path to the executable in the code.

This doesn't happen on macOS.

### Steps to reproduce

1. On Windows, create a normal Python pulumi program with `pulumi new aws-python`
2. Replace the contents of `__main__.py` with the following:
    ```python
    import os
    
    print(os.environ['PATH'])
    ```
3. Run `pulumi up`

### Expected Behavior

I expect my code to print the same `PATH` value that running `set PATH` in my command prompt (where I run `pulumi up` from) does.

### Actual Behavior

My code's entire `PATH` value was `C:\Users\user\test-win-pulumi-py\venv\Scripts`.

### Versions used

```
CLI
Version      3.35.3
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.10.0
python  unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19043 Build 19043
Arch     x86_64

This project is written in python: executable='C:\Users\user\Desktop\test-win-pulumi-py\venv\Scripts\python.exe' version='3.10.4'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/bl-ue
User           bl-ue
Organizations  bl-ue

Dependencies:
NAME        VERSION
pip         22.0.4
pulumi-aws  5.10.0
setuptools  58.1.0

Pulumi locates its logs in R:\Temp by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

I created the virtual environment using the [`virtualenv`](https://pypi.org/project/virtualenv/) module and the built-in [`venv`](https://docs.python.org/3/library/venv.html) module. Both resulted in the same behavior.

I installed Pulumi on one Windows machine using [the MSI](https://github.com/pulumi/pulumi-winget/releases), and on another machine I used just [the binaries](https://www.pulumi.com/docs/get-started/install/versions/), and both had the same result.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Was a case-sensitive comparison when updating the env var. cli was looking for "PATH" but Windows by default is "Path". Should have this fixed for the next release on Wednesday.
