### ISSUE TITLE
Dotnet program-gen should simplify MyStack.cs into just Program.cs using .NET 6 top-level statements

### ISSUE THREAD

**Issue by Zaid-Ajaj** [pulumi/pulumi#10114]
### What happened?

Today, dotnet program-gen outputs a file called `MyStack.cs` which contains a class called `MyStack` that constructs resources and assigns outputs to properties of the class marked with `[Output]`

In .NET 6, we can greatly simplify this setup and get rid of `MyStack.cs` entirely where we instead generate a single entry point file `Program.cs` that defines stack resources and returns outputs from them. 

This results in
 - Simplified project structure that looks similar to all other languages
 - No longer we need to compute the types of the outputs up front, which today defaults to `Output<string>` for almost everything. 

This issue is also related to `GenerateProject` where the generated project should be targeting `net6.0` and only have `Program.cs` in the project

### Steps to reproduce

Run `pulumi convert --language csharp --out dist` against this YAML program
```yaml
name: YamlTest
runtime: yaml
resources:
  bucket:
    type: aws:s3:Bucket

outputs:
  bucketName: ${bucket.id}
```

### Expected Behavior

Should generate:
```cs
// Program.cs
using System.Collections.Generic;
using Pulumi;
using Aws = Pulumi.Aws;
using Deployment = Pulumi.Deployment;

await Deployment.RunAsync(() => 
{
  var bucket = new Aws.S3.Bucket("bucket")

  return new Dictionary<string, object?>
  {
      ["bucketName"] = bucket.Id
  };
});
```

### Actual Behavior

Generates:
```csharp
// MyStack.cs
using Pulumi;
using Aws = Pulumi.Aws;

class MyStack : Stack
{
    public MyStack()
    {
        var bucket = new Aws.S3.Bucket("bucket", new Aws.S3.BucketArgs
        {
        });
        this.BucketName = bucket.Id;
    }

    [Output("bucketName")]
    public Output<string> BucketName { get; set; }
}
```

### Versions used

Pulumi v3.53.3

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
This is effectively the last thing in https://github.com/pulumi/pulumi/issues/7911 so I suggest we prioritize this with the goal to ship the blog post and close the epic asap. WDYT @Zaid-Ajaj @Frassle?

**Comment by Zaid-Ajaj** [comment]
@mikhailshilkov Sounds good! Working on it right now
