### ISSUE TITLE
Use local provider in examples

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#10116]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In each provider's repository, we have a number of 'examples' which are run via ProgramTest but are also often run manually to test changes to a provider. Currently we have to build the provider's binary and ensure it's available on the $PATH. If it's mis-configured then it falls back to downloading or using a previously installed version which can lead to much confusion.

1. Add a `providers` configuration option in the `Pulumi.yaml` file which includes an option to always run from a local path e.g.

    ```yaml
    providers:
        my-provider:
            localPath: ../../bin/my-provider
    ```

    This should fail with an error if the binary is not found.

2. Integrate into ProgramTest as a pulumi CLI option such as `pulumi link my-provider /absolute/path/bin/my-provider` or an environment variable such as `PULUMI_PROVIDER_PATHS="my-provider:/absolute/path/bin/my-provider"`. This should take precidence over the path in the `Pulumi.yaml` config. This is required to be an absolute path because the examples are copied to a temp directory during the ProgramTest execution.

### Affected area/feature

- Configuration
- Command line/environment variables
- Plugin loading

**Comment by Frassle** [comment]
> Integrate into ProgramTest as a pulumi CLI option such as `pulumi link my-provider /absolute/path/bin/my-provider`

I was thinking about making this sym-link the folder to the plugins directory. Sort of like plugin install but with no copy, maybe it could just be a flag on install instead though.

The envvar could just be added to whatever was read from Pulumi.yaml.
