### ISSUE TITLE
Add tests for "strange" resource/stack/project names

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi#10117]
We've inadvertently broke users a couple of times due to accidentally adding assert validation of tokens to the engine (see https://github.com/pulumi/pulumi/pull/9161 and https://github.com/pulumi/pulumi/issues/9947).

While we have an action item to deprecate or remove these methods (https://github.com/pulumi/pulumi/issues/10052) we should also add tests to ensure that odd names that users are currently using (such as "web:web", "-test") work correctly.

This will be important to ensure that when we do add validation in https://github.com/pulumi/pulumi/issues/8949 we continue to work for current names.

**Comment by h20220025** [comment]
hi @Frassle , This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by Frassle** [comment]
I'd probably look at adding these tests to https://github.com/pulumi/pulumi/blob/master/pkg/engine/lifecycletest/pulumi_test.go 

There's nothing language specific about supporting these names, we just need to check the engine is ok with them.
