### ISSUE TITLE
Pulumi deletes resources if update of a predecessor resource fails

### ISSUE THREAD

**Issue by alecor191** [pulumi/pulumi#10158]
### Summary
I have resource `A` that depends on resource `B`. Both are deployed and Pulumi correctly first creates `B`, then `A`. 

Now I update `B` and run `pulumi up` again. The update of `B` fails, but what's worse, resource `A` gets destroyed by Pulumi.

### Specific example
I'm building a Docker image with Pulumi (resource `B` above) and then deploy it as Azure Container App (resource `A` above). This works fine.

Now I update my app and run `pulumi up` again. This results in Pulumi rebuilding the Docker image. Unfortunately, on my PC I run into [pulumi-docker #326](https://github.com/pulumi/pulumi-docker/issues/326). I.e. the Pulumi Docker build fails.

However, what's worse, is that **Pulumi destroys/deletes the Azure Container App as well.**

This is quite bad, as now the App is gone from Azure, meaning customers can't use the app anymore. And all that, just because a Docker build failed.

Here a short excerpt of the Pulumi console output (see full output below). As you can see, the Docker Image build for `sub-app` failed and as a consequence Pulumi deletes Azure Container Apps for both `sub-app` and `pub-app`.

```text
Updating (playground-westeurope)

View Live: https://app.pulumi.com/...

     Type                                        Name                                               Status         Info
     pulumi:pulumi:Stack                         app-environment-apps-pubsub-playground-westeurope
     ├─ docker:image:Image                       pub-app
     ├─ docker:image:Image                       sub-app                                            **failed**     2 errors
 -   ├─ azure-native:app/v20220301:ContainerApp  pub-app                                            deleted
 -   └─ azure-native:app/v20220301:ContainerApp  sub-app                                            deleted
```

### Steps to reproduce

- Create a Pulumi Docker build
- Create an Azure Container App that uses that Docker image
- Make the Pulumi Docker build fail

### Expected Behavior

When the Docker build step fails, Pulumi stops execution and shows the error. Resources depending on the Docker build should not be modified.

### Actual Behavior

When the Docker build step fails, Pulumi *destroys* resources that depend on the Docker build.

### Versions used

```text
CLI
Version      3.36.0
Go Version   go1.17.12
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.66.0
docker        3.2.0
dotnet        unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22000 Build 22000
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='6.0.302'

Current Stack: playground-westeurope

Found no pending operations associated with playground-westeurope

Backend
Name           pulumi.com
URL            https://app.pulumi.com/...
User           ...
Organizations  ...

Dependencies:
NAME                VERSION
Pulumi              3.35.1
Pulumi.AzureNative  1.66.0
Pulumi.Docker       3.2.0
```

### Additional context

Here the output of `pulumi up -y -f` in the scenario mentioned above:

```text
Updating (playground-westeurope)

View Live: https://app.pulumi.com/...

     Type                                        Name                                               Status         Info
     pulumi:pulumi:Stack                         app-environment-apps-pubsub-playground-westeurope
     ├─ docker:image:Image                       pub-app
     ├─ docker:image:Image                       sub-app                                            **failed**     2 errors
 -   ├─ azure-native:app/v20220301:ContainerApp  pub-app                                            deleted
 -   └─ azure-native:app/v20220301:ContainerApp  sub-app                                            deleted

Diagnostics:
  docker:image:Image (sub-app):
    error: Error saving credentials: rename C:\Users\...\.docker\config.json4032210568 C:\Users\...\.docker\config.json: Access is denied.
    error: Pulumi.ResourceException: ' docker login' failed with exit code 1

       at async Task<string> Pulumi.Docker.Docker.RunCommandThatMustSucceed(string cmd, string[] args, Resource logResource, bool reportFullCommandLine, string stdin, ImmutableDictionary<string, string> env)
       ...


Outputs:
  - pubsub-sample:component-name       : "app-pubsub-sb"
  - pubsub-sample:pub-app-name         : "pub-app"
  - pubsub-sample:pub-url              : "..."
  - pubsub-sample:sub-app-name         : "sub-app"
  - service-bus-topic:connection-string: [secret]
  - service-bus-topic:name             : "app-pubsub-sb-topic"

Resources:
    - 2 deleted
    7 unchanged

Duration: 23s
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Thanks for reporting this issue. Would it be possible to send us a copy of your program so we can replicate the problem?
