### ISSUE TITLE
Go: Expose context.Context from pulumi.Context via getter method

### ISSUE THREAD

**Issue by ghostsquad** [pulumi/pulumi#10162]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Please expose the `context.Context` (via a getter method) of the `pulumi.Context` object so that inline code has a context from which it can use for cancellation information, such as if a user presses `ctrl-c` at the command prompt.

### Affected area/feature

GoLang SDK

**Comment by dixler** [comment]
@AaronFriel is interested in looking into improving our SIGTERM handling.

**Comment by AaronFriel** [comment]
@ghostsquad thanks for reporting this - it looks like we have an un-exported `ctx context.Context` field so it should be safe for us to change this to an exported `context.Context`, which I think is the expected way context wrappers work. Would that work?

I'm tagging in @Frassle here to ask if there's any reason we'd be leery of exposing the internal context, but I expect we'd be fine with it.

**Comment by ghostsquad** [comment]
I would not export the field, as it may not safe to _set_ the context, only to use the current context, similar to that of the http.request object.

https://pkg.go.dev/net/http#Request.Context

**Comment by t0yv0** [comment]
+1 for `func (x pulumi.Context) Context() context.Context`
