### ISSUE TITLE
Encrypted fields are decrypted in Component Resource outputs

### ISSUE THREAD

**Issue by megbetts** [pulumi/pulumi#10172]
### What happened?

Pulumi is automatically decrypting fields that belong to a ComponentResource output. 

I have ComponentResources that create multiple AWS resources within them. Some of these resources return encrypted fields (an RDS instance for example returns a password that is encrypted). If my output is of type RDS (the schema is shown below), the password field is decrypted and is visible in plaintext.

Schema.JSON
```
"db": {
          "$ref": "/aws/v4.0.0/schema.json#/resources/aws:rds%2Finstance:Instance",
  }
```

ComponentResource output:
```
{
        address                              : "fakevalue.fakevalue.fakevalue.rds.amazonaws.com"
        .....
        password                             : foobartext
}
```

Pulumi-AWS output:
```
{
        address                              : "fakevalue.fakevalue.fakevalue.rds.amazonaws.com"
        .....
        password                             : [secret]
}
```

What's interesting here is that this only happens when the encrypted field is wrapped in a resource. If I return an encrypted field as a string output - it stays encrypted.    

### Steps to reproduce

Create a component resource.
Ensure it returns an output that is of the Type of another AWS resource.
Ensure one of the fields of the output resource is encrypted.

### Expected Behavior

The encrypted field stays encrypted

### Actual Behavior

The encrypted field is decrypted when returned by the Component Resource

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hi, thanks for raising this. Could you share the code that you're using to help us reproduce this?

**Comment by megbetts** [comment]
Hello,
What's the best way to send you the code? I can instead give you the easiest way to mock what I did.

If you take the python boilerplate https://github.com/pulumi/pulumi-component-provider-py-boilerplate/blob/main/provider/cmd/pulumi-resource-xyz/xyz_provider/staticpage.py and modify the StaticPage class  with:


```
import pulumi_aws

class StaticPage(pulumi.ComponentResource):
    bucket: s3.Bucket
    website_url: pulumi.Output[str]

    def __init__(self,
                 name: str,
                 args: StaticPageArgs,
                 props: Optional[dict] = None,
                 opts: Optional[ResourceOptions] = None) -> None:

        super().__init__('xyz:index:StaticPage', name, props, opts)

        rds = pulumi_aws.rds.Instance("default",
            allocated_storage=10,
            engine="mysql",
            engine_version="5.7",
            instance_class="db.t3.micro",
            name="mydb",
            parameter_group_name="default.mysql5.7",
            password="foobarbaz",
            skip_final_snapshot=True,
            username="foo")
        
        self.bucket = rds
        self.website_url = "notvalid"

        self.register_outputs({
            'bucket': rds,
            'websiteUrl': bucket.website_endpoint,
        })

```

and then modify the schema.json with

```
"xyz:index:StaticPage": {
            "isComponent": true,
            "inputProperties": {
                "indexContent": {
                    "type": "string",
                    "description": "The HTML content for index.html."
                }
            },
            "requiredInputs": [
                "indexContent"
            ],
            "properties": {
                "bucket": {
                    "$ref": "/aws/v4.0.0/schema.json#/resources/aws:rds%2Finstance:Instance",
                },
                "websiteUrl": {
                    "type": "string",
                    "description": "The website URL."
                }
            },
            "required": [
                "bucket",
                "websiteUrl"
            ]
        }
    },

**Comment by dixler** [comment]
I've managed to reproduce it.

**Comment by megbetts** [comment]
That's great news! Thanks!
