### ISSUE TITLE
Add option to not install dependencies on `pulumi convert`

### ISSUE THREAD

**Issue by aq17** [pulumi/pulumi#10196]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add option to not install dependencies when running `pulumi convert` and to simply generate the converted program

**Comment by dixler** [comment]
@aq17 left some comments on your merged PR.

**Comment by Frassle** [comment]
Also left a comment

**Comment by Frassle** [comment]
Done by https://github.com/pulumi/pulumi/pull/10205
