### ISSUE TITLE
Regression in `pulumi stack ls` latency

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#10219]
### What happened?

`pulumi stack ls -a` takes up to a few minutes in organizations with large stacks

Based on perf traces, it appears that the CLI is doing an api/getStack on every stack which is taking ~200ms per stack.

It looks like it's a recent regression in https://github.com/pulumi/pulumi/pull/10059

### Steps to reproduce

`pulumi stack ls -a`

### Expected Behavior

Executes within a second or so

### Actual Behavior

Takes up to 3-5 minutes based on user reports

### Versions used

CLI 3.36.0, Pulumi Service backend

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@aq17 Let's revert https://github.com/pulumi/pulumi/pull/10059 and see if there are other ways to solve the original ask (even if it's not simple)

**Comment by Frassle** [comment]
We probably need to talk to service team to get this information raised on the right endpoint.

**Comment by dixler** [comment]
> Takes up to 3-5 minutes based on user reports

thanks. can you link the user reports?
