### ISSUE TITLE
Unhide `pulumi gen-completion` in the `pulumi --help` command

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#10215]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi is meant to be easily accessible to its new and more experienced users. As part of this experience, the official documentation [references](https://www.pulumi.com/docs/reference/cli/#command-line-completion) the ability to generate command-line completion scripts. 

However, when running `pulumi --help`, the sub-command `gen-completion` is [not shown](https://github.com/pulumi/pulumi/blob/master/pkg/cmd/pulumi/gen_completion.go#L36). It would be great to expose to all users this sub-command. 

### Affected area/feature

* pulumi CLI

**Comment by dixler** [comment]
hey, @aureq I was talking with @AaronFriel and we're going to merge the PR and open another issue to look into spf13/cobra's built in gen-completion command.
