### ISSUE TITLE
[sdk/go] simplify Go program errors

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#10227]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Consider tidying up redundant information when displaying errors from Go programs.

### Reproduce

- ```pulumi new go```
- Edit main.go:
       
```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		return fmt.Errorf("!")
	})
}
```

- `pulumi preview`

### Current behavior

```
Previewing update (dev)

View Live: https://app.pulumi.com/t0yv0/go-err/dev/previews/33a80085-858c-4439-929c-a59b59e92027

     Type                 Name        Plan       Info
 +   pulumi:pulumi:Stack  go-err-dev  create     1 error; 3 messages
 
Diagnostics:
  pulumi:pulumi:Stack (go-err-dev):
    error: program failed: 1 error occurred:
        * !
    exit status 1
 
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

### Desired behavior

It would be lovely to reduce "1 error; 3 messages" to just "1 error" as in other languages like TypeScript.

The `exit status 1` message is not helpful as it is duplicative with  `error: an unhandled error occurred: program exited with non-zero exit code: 1`. We should remove the duplication.

Copying earlier comment from Pat, we should only retain messaging around `exit code 1` when there is no other error information that's making it obvious that the Go program failed

So in the case of the code above we'd want: 

```
Previewing update (dev)

View Live: https://app.pulumi.com/t0yv0/go-err/dev/previews/33a80085-858c-4439-929c-a59b59e92027

     Type                 Name        Plan       Info
 +   pulumi:pulumi:Stack  go-err-dev  create     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (go-err-dev):
    error: program failed: 1 error occurred:
        * !
```

**Comment by iwahbe** [comment]
I think the desired behavior described in the original post is great! It would be even better if we could leverage common pulumi errors and the [errors.Unwrap](https://pkg.go.dev/errors#Unwrap) function to display error traces for compliant errors.


Given the error 
```go
func doesntWork() (string, error) {
  return "", fmt.Errorf("it didn't work")
}

if s, err := doesntWork(); err != nil {
  return fmt.Errorf("we got an error: %w")
}
```
We could try to infer a message like:
```
Previewing update (dev)

View Live: https://app.pulumi.com/t0yv0/go-err/dev/previews/33a80085-858c-4439-929c-a59b59e92027

     Type                 Name        Plan       Info
 +   pulumi:pulumi:Stack  go-err-dev  create     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (go-err-dev):
    error: program failed: 1 error occurred:
        * we got an error
          * it didn't work
```

**Comment by dixler** [comment]
some extra details around where the `error status 1` is coming from `os.Exit(1)` when doing `go run`
https://stackoverflow.com/questions/26893774/how-to-disable-exit-status-1-when-executing-os-exit1

**Comment by dixler** [comment]
One thing out of scope to consider is go compilation errors

[![asciicast](https://asciinema.org/a/Za5srQd3DeFkMRgu6NHh9rfty.svg)](https://asciinema.org/a/Za5srQd3DeFkMRgu6NHh9rfty)

**Comment by t0yv0** [comment]
@iwahbe you are perhaps suggesting a better pretty-print for Go wrapped errors. I feel like it's on Go to fix/change that no? Alternatively, if there's a Go-community accepted package that has something along the lines of `goerror.PrettyPrint(err error)` we could consider it. Currently Go pretty-prints this kind of error as `we got an error: it didn't work`. I worry if we introduce something Pulumi specific at this level it will just be confusing to users used to what Go does by default.

**Comment by t0yv0** [comment]
@dixler special casing compilation error experience makes sense to me! Please feel free to open another ticket for it and let's do it, it sounds like a very easy quality of life improvement. I think I missed logging it originally simply because I was looking at stats of most commonly experienced errors, and they are dominated by TypeScript stats - but Go is important too, and perhaps used more in contexts where we do not get stats.

**Comment by dixler** [comment]
[internal link](https://pulumi.slack.com/archives/C02VCJEBT2N/p1660163421263049)

**Comment by dixler** [comment]
depends on
- https://github.com/pulumi/pulumi/issues/10350
