### ISSUE TITLE
[sdk/python] remove pulumi callstacks from pulumi program Exception traceback

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#10230]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We currently report long stack traces from Pulumi Python programs. These stack traces contain frames with implementation details that may be helpful for the maintainers to understand what is happening but are not helpful to users, especially first time users.

Please consider removing the extraneous stack frames. This can be done with an escape hatch, perhaps when Troubleshooting (-v=9) with verbose logging as explained in https://www.pulumi.com/docs/support/troubleshooting/#verbose-logging Pulumi could still emit full stack traces.

### Repro

A very common user issue is a missing module - either venv was not setup correctly or pip has not been run. 

- ```pulumi new python```
- Edit __main__.py:

```
import pulumi
import pulumi_oci
```

- ```pulumi preview```

### Current behavior

```
Previewing update (dev)

View Live: https://app.pulumi.com/t0yv0/python-err/dev/previews/5b1762b3-3261-4cca-aa7f-43b76f8a83b8

     Type                 Name            Plan       Info
 +   pulumi:pulumi:Stack  python-err-dev  create     3 errors
 
Diagnostics:
  pulumi:pulumi:Stack (python-err-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/Users/anton/.nix-profile/bin/pulumi-language-python-exec", line 107, in <module>
        loop.run_until_complete(coro)
      File "/nix/store/7q3qsarzyffcm2sjb2yhjgy0d3hzdi7y-python3-3.8.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 49, in run_pulumi_func
        func()
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 126, in <lambda>
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/anton/tmp/48h/python-err/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 149, in __init__
        func()
      File "/Users/anton/.nix-profile/bin/pulumi-language-python-exec", line 106, in <lambda>
        coro = pulumi.runtime.run_in_stack(lambda: runpy.run_path(args.PROGRAM, run_name='__main__'))
      File "/nix/store/7q3qsarzyffcm2sjb2yhjgy0d3hzdi7y-python3-3.8.8/lib/python3.8/runpy.py", line 282, in run_path
        return _run_code(code, mod_globals, init_globals,
      File "/nix/store/7q3qsarzyffcm2sjb2yhjgy0d3hzdi7y-python3-3.8.8/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "./__main__.py", line 2, in <module>
        import pulumi_oci
    ModuleNotFoundError: No module named 'pulumi_oci'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### Desired behavior

Basically remove all frames above __main__.py in the reported traceback. Those do not help the user.

```
View Live: https://app.pulumi.com/t0yv0/python-err/dev/previews/5b1762b3-3261-4cca-aa7f-43b76f8a83b8

     Type                 Name            Plan       Info
 +   pulumi:pulumi:Stack  python-err-dev  create     3 errors
 
Diagnostics:
  pulumi:pulumi:Stack (python-err-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "./__main__.py", line 2, in <module>
        import pulumi_oci
    ModuleNotFoundError: No module named 'pulumi_oci'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### Implementation notes

I've dug a but into Python facilities for stack trace manipulation. It seems that `traceback` module can print traces and can remove frames from these traces. Here is an example program:

```python
import sys
import types
import traceback


class MyError(Exception):
    pass


def foo():
    bar()


def bar():
    baz()


def baz():
    raise MyError()


if __name__ == '__main__':
    try:
        foo()
    except:

        t, e, tb = sys.exc_info()
        traceback.print_exception(t, e, tb)

        print('*'*20 +' TRIMMED ' + '*'*20)

        s = traceback.extract_tb(tb)
        s = traceback.StackSummary.from_list(s[3:])
        print('Traceback (most recent call last):')
        print(''.join(s.format()).rstrip('\n'))
        traceback.print_exception(t, tb=None, value=e)
```

Perhaps this technique could be applicable here, though Pulumi might need to support Python 3.6 still so care is needed when testing on older versions so we do not break those. More Python expertise welcome here.

**Comment by dixler** [comment]
sounds great!

@susanev has an existing issue for this with some feedback notes https://github.com/pulumi/pulumi/issues/9230

opinions on the following improvements:
- If the error occurs in a user's program we can omit the pulumi part of the stack trace.
- If the error occurs in pulumi, we emit the entire stack trace.

concerns:
- it might take longer for users to realize why the idiomatic python pattern below isn't working since they won't even have the full stacktrace to teach them that they're not `__main__`.

```python
if __name__ == '__main__':
    main()
```

**Comment by t0yv0** [comment]
1. That sounds good, if we can tell where the error occurred which might not be easy.

2. What doesn't work about "__name__ == '__main__'"?

**Comment by dixler** [comment]
I guess it's an uncommon case since our default file name for pulumi programs is `__main__.py`

> 2. What doesn't work about "__name__ == '__main__'"? 
> 
> 

https://www.geeksforgeeks.org/what-does-the-if-__name__-__main__-do/
