### ISSUE TITLE
Unable to set secret value that starts with a "-"

### ISSUE THREAD

**Issue by theogravity** [pulumi/pulumi#10241]
### What happened?

Trying to set a secret using the command:

`pulumi config set --secret <name> <value>`

The `value` happens to begin with `-`.

### Steps to reproduce

`pulumi config set --secret <name> "-blah"`

### Expected Behavior

Should store the secret value.

### Actual Behavior

Get the following error:

`unknown shorthand flag: 'E' in (secret value)`

(The E is because the secret starts with `-E`)

### Versions used

```
LI          
Version      3.36.0
Go Version   go1.18.4
Go Compiler  gc

Plugins
NAME        VERSION
aws         4.38.1
aws         4.38.1
kubernetes  3.20.0
kubernetes  3.19.0
nodejs      unknown
tls         4.6.0
tls         4.4.0

Host     
OS       darwin
Version  12.4
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This isn't specific to secrets, but any config value. You need to indicate to the command line parser that there are no more flags and the remaining text should be treated as positional arguments by using `--`. This is a common idiom in cli tools.

`pulumi config set --secret name -- value`

**Comment by dixler** [comment]
> This isn't specific to secrets, but any config value. You need to indicate to the command line parser that there are no more flags and the remaining text should be treated as positional arguments by using `--`. This is a common idiom in cli tools.
> 
> `pulumi config set --secret name -- "-blah"`

TIL what `--` means in help menus
