### ISSUE TITLE
Providers can only have a single set of configuration applied to them

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1026]
Today, our model does not provide a way to have multiple instances of the same provider that are initialized with different configuration (for example, you can not have two aws providers, each targeting a different region).

The workaround today is to just run your Pulumi program multiple times with different sets of configurations (which you could, for example, vary by stack) but it's not 100% satisfying.  What we have is good enough to launch with, however, but we will probably need to do something here over time.

**Comment by lukehoban** [comment]
This is the same as https://github.com/pulumi/pulumi/issues/1221 - so I'll close this out now.
