### ISSUE TITLE
Inaccurate StackReference code generation via `pulumi convert`

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#10260]
Code generation assumes that the `pulumi` package should be interpreted like others, such as `aws`, and imported as `@pulumi/pulumi-pulumi` (nodejs) or via `pulumi_pulumi` (python), and so on.

The schema is also inaccurate for Python at least, as the `name` property in the Python SDK is `stack_name`.

This issue will track successfully generating code for each of our target languages via PCL.

**Comment by Frassle** [comment]
Might be worth syncing with @harribo11 as StackReference tests are one of the tests his looking at adding to the matrix test framework.
