### ISSUE TITLE
Components can not abstract configuration dependencies from your end-users

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1027]
When building a component, you often aggregate resources from a set of providers, which have configuration.  However, as the component author, there's no way for you to control the configuration of these providers, since the top level program owns them.

Previously, we had a solution for a case of this problem where you were distributing a Pulumi program, since that program could have global configuration and that configuration could set values for specific providers.  But we've since removed that and it also did not support the case where you were simply authoring a library to be used by other programs, but wanted to hide configuration details from the end user.

**Comment by lukehoban** [comment]
@ellismg @pgavlin I *think* this is "solved" by first-class providers.  In general, I think the solution here is to not use config and to explicitly parameterize things. Anything else you think we need to track with this issue?

**Comment by pgavlin** [comment]
This is not fully solved, no. This is ameliorated for provider config by FCPs, but library config is still an issue (e.g. configuring `cloud-aws`).

**Comment by pgavlin** [comment]
After further discussion, we believe that @lukehoban's proposed approach above is a solution to this issue.
