### ISSUE TITLE
pulumi CLI always try to access api.pulumi.com

### ISSUE THREAD

**Issue by rophy** [pulumi/pulumi#10282]
### What happened?

Even when trying to login locally, it seems pulumi CLI still try to access api.pulumi.com

### Steps to reproduce

1. Add `127.0.0.1  api.pulumi.com` to `/etc/hosts`

2. Try to login locally:

```bash
$ pulumi login --local --logtostderr --logflow -v=9
Logged in to HOSTNODE as rophy (file://~)
I0729 08:51:48.596523     69645 pulumi.go:259] error fetching latest version information: performing HTTP request: Get "https://api.pulumi.com/api/cli/version": dial tcp 127.0.0.1:443: connect: connection refused

```

### Expected Behavior

pulumi CLI should be able to work in corporate environments without internet access.

### Actual Behavior

Since pulumi always try to access api.pulumi.com, pulumi CLI cannot work in corporate environments without internet access.

### Versions used

v3.36.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rophy** [comment]
Setting env var `PULUMI_SKIP_UPDATE_CHECK` resolves the issue 👍

**Comment by Frassle** [comment]
Maybe the "error fetching latest version information" should also comment that `PULUMI_SKIP_UPDATE_CHECK` is a thing? 
cc @susanev @dixler

**Comment by susanev** [comment]
ha! i almost commented on this, def would love us to address the usability issue here. ill open an issue.
