### ISSUE TITLE
Pulumi 3.37.0+ is throwing `failed to complete update: [409]`

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#10293]
### What happened?

Pulumi 3.37.0 is throwing an error: `error: failed to complete update: [409] Stack 'monitoring-test' is not locked by update id 'eb18fada-43d9-470e-a521-45800a94d5fe' (15gs5q9)` when updating a stack. We believe it is from #10168. Rolling back to 3.36.0 is a current workaround. 

### Steps to reproduce

1. Create a stack with 3.36.0 with http backend
2. upgrade to 3.37.0
3. try to `pulumi up`  the stack. 

### Expected Behavior

Pulumi up should follow thru and create the stack. 

### Actual Behavior

Pulumi up throws a 409

### Versions used

3.37.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
How did none of our testing pick this up?

**Comment by mikhailshilkov** [comment]
@Frassle I believe this issue is with a non-Pulumi backend

**Comment by Frassle** [comment]
Ah understood, cloud be slight difference in behavior there that triggered this.
