### ISSUE TITLE
Delay (or allow delaying) destruction of resources

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi#10290]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Some resources have very deep relationships with other resources and you can't deal with them independently. An example that comes to mind is `aws.rds.Cluster` and `aws.rds.ClusterParameterGroup`. We need the ClusterParameterGroup to be created before the Cluster, which means that any changes that need ClusterParameterGroup to be replaced will break the flow, since Cluster is still using that resource. Fixing this, once it happens, isn't trivial unless you're willing to mess with state files.

If we have a way to delay the deletion of resources to the end of the Pulumi run, then the Cluster would be using the newly created ClusterParameterGroup and so the obsolete ClusterParameterGroup can safely be destroyed.

Perhaps this could be set via a new resourceOption?

**Comment by Frassle** [comment]
Not quite sure I understand the issue here? Pulumi already defaults to creating new resources first and then deleting the old resources at the end of the deployment run. It sounds like this is a specific case of dependencies being wrong maybe?

**Comment by Sodki** [comment]
You're absolutely right, my bad. I got confused because I had a separate issue during the database upgrade that made the whole thing fail, but Pulumi was definitely not to blame.
