### ISSUE TITLE
Potential Codegen regression between v3.33.1 and v3.36.0

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#10308]
When upgrading the pulumi-aws provider to v3.26.1 of the bridge, we effectively changed the version of pulumi from v3.33.1 to v3.36.0. The change also brought in the following PR https://github.com/pulumi/pulumi-terraform-bridge/pull/568 

This regression has caused the pulumi-aws build to go from ~20mins to approx ~80minutes. The publish stage of our binary happens 8 times (different OS / Arch combinations) so this makes it about 300-400 minutes which is causing timeouts

https://github.com/pulumi/pulumi-aws/actions/runs/2761874991

**Comment by iwahbe** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/pull/568 is a version bump. It moves codegen from [v3.34.1 to v3.35.3](https://github.com/pulumi/pulumi/compare/v3.34.1...v3.35.3).
