### ISSUE TITLE
aws-fs-s3-folder example fails to run

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#10306]
### What happened?

TestAccAwsFsS3Folder is failing in the examples repo: https://github.com/pulumi/examples/runs/7628064321?check_suite_focus=true#step:24:1

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
      File name: 'FSharp.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   
      error: an unhandled error occurred: Program exited with non-zero exit code: 134
```

### Steps to reproduce

Reproduced in our CI

### Expected Behavior

Test succeeds

### Actual Behavior

Test fails

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
This looks like a product bug - starting with 3.36.1 we are now referencing FSharp.Core 6.0.5 instead of 4.7.2 in 3.36.0: https://www.nuget.org/packages/Pulumi.FSharp/3.36.1#dependencies-body-tab

It sounds like this changed implicitly when switched to .NET 6 tools in CI? Can we reference 4.7.2 explicitly to fix this?

**Comment by Zaid-Ajaj** [comment]
> It sounds like this changed implicitly when switched to .NET 6 tools in CI?

@mikhailshilkov Yes, unfortunately, the FSharp.Core version is inferred from the current target framework unless explicitly told otherwise. #10311 fixes it
