### ISSUE TITLE
Python explicit provider configuration broken on Linux and Mac

### ISSUE THREAD

**Issue by AlexMikhalev** [pulumi/pulumi#10315]
### What happened?

Trying to follow: 
https://www.pulumi.com/docs/intro/concepts/resources/providers/#explicit-provider-configuration 
on creation provider fails:
```
import pulumi
import pulumi_aws as aws

# Create an AWS provider for the us-east-1 region.
useast1 = aws.Provider("useast1", region="us-east-1")
```
with error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/infrastructure/pulumi_aws_flask/venv/lib/python3.10/site-packages/pulumi_aws/provider.py", line 638, in __init__
    __self__._internal_init(resource_name, *args, **kwargs)
  File "/home/alex/infrastructure/pulumi_aws_flask/venv/lib/python3.10/site-packages/pulumi_aws/provider.py", line 733, in _internal_init
    super(Provider, __self__).__init__(
  File "/home/alex/infrastructure/pulumi_aws_flask/venv/lib/python3.10/site-packages/pulumi/resource.py", line 1164, in __init__
    CustomResource.__init__(
  File "/home/alex/infrastructure/pulumi_aws_flask/venv/lib/python3.10/site-packages/pulumi/resource.py", line 1081, in __init__
    Resource.__init__(self, t, name, True, props, opts, False, dependency)
  File "/home/alex/infrastructure/pulumi_aws_flask/venv/lib/python3.10/site-packages/pulumi/resource.py", line 941, in __init__
    register_resource(
  File "/home/alex/infrastructure/pulumi_aws_flask/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 489, in register_resource
    monitor = settings.get_monitor()
  File "/home/alex/infrastructure/pulumi_aws_flask/venv/lib/python3.10/site-packages/pulumi/runtime/settings.py", line 202, in get_monitor
    require_test_mode_enabled()
  File "/home/alex/infrastructure/pulumi_aws_flask/venv/lib/python3.10/site-packages/pulumi/runtime/settings.py", line 147, in require_test_mode_enabled
    raise RunError(
pulumi.errors.RunError: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
```

### Steps to reproduce

Ensure all pulumi libraries up to date: 
```
pip install -U pulumi_aws 
Requirement already satisfied: pulumi_aws in ./venv/lib/python3.10/site-packages (5.10.0)
Requirement already satisfied: parver>=0.2.1 in ./venv/lib/python3.10/site-packages (from pulumi_aws) (0.3.1)
Requirement already satisfied: pulumi<4.0.0,>=3.0.0 in ./venv/lib/python3.10/site-packages (from pulumi_aws) (3.37.2)
Requirement already satisfied: semver>=2.8.1 in ./venv/lib/python3.10/site-packages (from pulumi_aws) (2.13.0)
Requirement already satisfied: attrs>=19.2 in ./venv/lib/python3.10/site-packages (from parver>=0.2.1->pulumi_aws) (22.1.0)
Requirement already satisfied: arpeggio~=1.7 in ./venv/lib/python3.10/site-packages (from parver>=0.2.1->pulumi_aws) (1.10.2)
Requirement already satisfied: six~=1.13 in ./venv/lib/python3.10/site-packages (from parver>=0.2.1->pulumi_aws) (1.16.0)
Requirement already satisfied: grpcio==1.47 in ./venv/lib/python3.10/site-packages (from pulumi<4.0.0,>=3.0.0->pulumi_aws) (1.47.0)
Requirement already satisfied: pyyaml~=5.3 in ./venv/lib/python3.10/site-packages (from pulumi<4.0.0,>=3.0.0->pulumi_aws) (5.4.1)
Requirement already satisfied: protobuf~=4.21 in ./venv/lib/python3.10/site-packages (from pulumi<4.0.0,>=3.0.0->pulumi_aws) (4.21.4)
Requirement already satisfied: dill~=0.3 in ./venv/lib/python3.10/site-packages (from pulumi<4.0.0,>=3.0.0->pulumi_aws) (0.3.5.1)

```
pulumi version  
v3.37.2
python3 --version   
Python 3.10.4

pip freeze
```
pip freeze               
Arpeggio==1.10.2
attrs==22.1.0
click==7.1.2
dill==0.3.5.1
Flask==1.1.4
grpcio==1.47.0
itsdangerous==1.1.0
Jinja2==2.11.3
MarkupSafe==2.0.1
parver==0.3.1
protobuf==4.21.4
pulumi==3.37.2
pulumi-aws==5.10.0
PyYAML==5.4.1
semver==2.13.0
six==1.16.0
Werkzeug==1.0.1
```

### Expected Behavior

Progress to the next line in the tutorial. 
My aim to setup a default profile for pulumi automation API, which is different to local default ( aws --profile pulumi) so I can progress [Pulumi Over Http example](https://github.com/pulumi/automation-api-examples/tree/fb4ffddd8dd5eade5a7d1454e23123ae432fa3ac/python/pulumi_over_http) 

### Actual Behavior

Crash

### Versions used

pulumi about
CLI          
Version      3.37.2
Go Version   go1.17.12
Go Compiler  gc

Host     
OS       debian
Version  bookworm/sid
Arch     x86_64

Backend        
Name           pulumi.com

### Additional context

My aim to setup a default profile for pulumi automation API, which is different to local default ( aws --profile pulumi) so I can progress [Pulumi Over Http example](https://github.com/pulumi/automation-api-examples/tree/fb4ffddd8dd5eade5a7d1454e23123ae432fa3ac/python/pulumi_over_http) 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AlexMikhalev** [comment]
Probably belongs to pulumi_aws.

**Comment by mikhailshilkov** [comment]
Hi @AlexMikhalev thank you for posting this issue.

> Program run without the Pulumi engine available; re-run using the `pulumi` CLI

It sounds like you are trying to execute your Pulumi program directly without running `pulumi up`?

**Comment by AlexMikhalev** [comment]
Hello Mikhail,
Yes the goal is to create stacks via http requests using Pulumi automation API.

**Comment by mikhailshilkov** [comment]
Still, something isn't right with the setup, since it gives this error. Don't you get the same error if you don't use an explicit provider?

**Comment by AlexMikhalev** [comment]
Nope. I can get the flask http example working by swapping default keys. The purpose of the non-default provider is that my pulumi keys are under --profile pulumi, and the default one is local - for sccache to seaweedfs server.

**Comment by mikhailshilkov** [comment]
Hmm, interesting. Are you adding your explicit provider definition inside `create_pulumi_program` function body [here](https://github.com/pulumi/automation-api-examples/blob/fb4ffddd8dd5eade5a7d1454e23123ae432fa3ac/python/pulumi_over_http/app.py#L23) or at the top of the file [here](https://github.com/pulumi/automation-api-examples/blob/fb4ffddd8dd5eade5a7d1454e23123ae432fa3ac/python/pulumi_over_http/app.py#L5)? Could you maybe share your full file as a gist?

**Comment by AlexMikhalev** [comment]
I narrowed it down to snippet:
```
import pulumi
import pulumi_aws as aws

useast1 = aws.Provider("useast1", region="us-east-1")
```

**Comment by mikhailshilkov** [comment]
Yes, but this snippet has nothing to do with Automation API, so you have to run it from the CLI with `pulumi up`. If you want to run it in Automation API, all your resources (and a Provider is a resource) have to be defined inside a callback to `auto.create_stack` (e.g. in `create_pulumi_program` in the linked example).

**Comment by AlexMikhalev** [comment]
I moved to typescript version of automation API; Typescript have more examples.
