### ISSUE TITLE
`pulumi login` - support using AWS IAM role for s3 bucket authentication

### ISSUE THREAD

**Issue by mlcooper** [pulumi/pulumi#10316]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We are running Pulumi in an AWS Lambda function (python). We're using a [custom Lambda container](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html), and we install the Pulumi CLI in it. Our goal is to have `pulumi login` in our lambda code use the [Lambda execution IAM role](https://docs.aws.amazon.com/lambda/latest/dg/lambda-intro-execution-role.html) assigned to our lambda function to authenticate to the S3 bucket where our Pulumi state file is stored. 

We want to move away from using keys for `pulumi login` to authenticate to the S3 bucket to read/write its state.

To my knowledge, this is not possible today, but please correct me if I am wrong!

Thanks!

### Affected area/feature

Pulumi CLI, specifically `pulumi login`

**Comment by AaronFriel** [comment]
@mlcooper thanks for reporting this! Can you share the full - or a fuller - `pulumi login` command that you're using?

I believe this should work in an IAM context, as we're deferring to the underlying AWS library:

[Logging Into the AWS S3 Backend](https://www.pulumi.com/docs/intro/concepts/state/#logging-into-the-aws-s3-backend)
```shell
pulumi login s3://<bucket-name>
```

But if that doesn't work in a Lambda IAM context, I can tag in one of our AWS experts here to understand if we need to make a change or if there might be an environmental requirement such as the AWS CLI in the container.

**Comment by mlcooper** [comment]
Hi @AaronFriel, thanks for the info. We are going to further test this out with our custom image in a lambda with an appropriate IAM execution role assigned to the lambda. I do now see in your documentation that this _should_ work.  cc: @oscarflexsh
