### ISSUE TITLE
Migrate to gofmt 1.19

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#10327]
`gofmt` 1.19 now reformats comments, whose diffs are caught by linting as failures. These can block PRs while we migrate.

To support a gradual migration, we could:

- [x] Pin lint jobs in CI to Go 1.18.x for a time to enable a migration period, as it accepts 1.18 and 1.19 formatted source code
- [ ] Set a cutoff date (go 1.18 end of life?) to ensure the repo is `gofmt` clean, and remove the version pin
- [ ] Upgrade `golangci-lint` to 1.49.0+ (prefer "latest")

**Comment by RobbieMcKinstry** [comment]
We're not planning to fmt the repo with the 1.19 format in one go, right? 
Do we instead fmt one subdirectory at a time, then mark that subdirectory to use the new 1.19 golang-cli-lint and the old 1.18 golang-cli-lint to ignore fmting that directory? (I don't even know if you can tell golangclilint to ignore lint violation for one directory for one linter only?)

**Comment by AaronFriel** [comment]
@RobbieMcKinstry, @thomas11 has a PR #10389 which should be considered the first draft of this.

I think the simplest approach is to do it in one go, because running multiple golangci-lint versions is a bit tricky and we don't want to overcomplicate our build scripts to handle it.

Fortunately the diff in formatting seems to be exclusively in comments, making it much easier to review.

**Comment by abhinav** [comment]
Is this still outstanding? On latest main, only the following files are out of date:

```
% gofmt -e -l -s $(rg --files -g '*.go' | rg -v compilation_error)
pkg/codegen/dotnet/gen_program_test/batch4/gen_program_test.go
pkg/codegen/dotnet/gen_program_test/batch5/gen_program_test.go
pkg/codegen/python/gen_program_test/batch4/gen_program_test.go
pkg/codegen/python/gen_program_test/batch3/gen_program_test.go
pkg/codegen/testing/test/testdata/aws-s3-folder-pp/go/aws-s3-folder.go
pkg/codegen/testing/test/testdata/aws-eks-pp/go/aws-eks.go
pkg/codegen/testing/test/testdata/aws-fargate-pp/go/aws-fargate.go
pkg/codegen/python/gen_program_test/batch5/gen_program_test.go
pkg/codegen/python/gen_program_test/batch2/gen_program_test.go
pkg/codegen/testing/test/testdata/aws-iam-policy-pp/go/aws-iam-policy.go
pkg/codegen/go/gen_program_test/batch3/gen_program_test.go
pkg/codegen/dotnet/gen_program_test/batch2/gen_program_test.go
pkg/codegen/python/gen_program_test/batch1/gen_program_test.go
pkg/codegen/python/gen_program_test/batch6/gen_program_test.go
pkg/codegen/go/gen_program_test/batch5/gen_program_test.go
pkg/codegen/go/gen_program_test/batch4/gen_program_test.go
pkg/codegen/dotnet/gen_program_test/batch3/gen_program_test.go
pkg/codegen/go/gen_program_test/batch2/gen_program_test.go
pkg/codegen/dotnet/gen_program_test/batch1/gen_program_test.go
pkg/codegen/dotnet/gen_program_test/batch6/gen_program_test.go
pkg/codegen/go/gen_program_test/batch1/gen_program_test.go
pkg/codegen/go/gen_program_test/batch6/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batch5/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batch1/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batch4/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batch2/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batch3/gen_program_test.go
pkg/codegen/nodejs/gen_program_test/batch6/gen_program_test.go
sdk/go/auto/example_test.go
```
