### ISSUE TITLE
AWS Provider hangs on second instantiation using Automation API

### ISSUE THREAD

**Issue by nebbles** [pulumi/pulumi#10325]
### What happened?

We use the Automation API in order to provision our fleet of IoT devices. We constantly have a variable input of devices to provision, so it helps to use this API and pass in a JSON file from which we can loop through and provision necessary certificates etc.

Our general workflow is to use `LocalWorkspace.createOrSelectStack()` when looping through using unique device identifiers. We then pass a program into this stack which includes specifying an AWS Provider which is then used to create AWS resources.

Whilst this used to work, at some point something seems to have broken. When running our script, the first device and stack always works. However when Pulumi gets to the second stack it always gets stuck on creating the AWS Provider we've specified at the beginning of the program:

```
[2022-08-08 20:23:04.369 +0000] INFO (device-manager): create or update infrastructure
[2022-08-08 20:23:04.369 +0000] INFO (device-manager): create or select stack using local workspace
[2022-08-08 20:23:06.178 +0000] INFO (device-manager): bring stack up
[2022-08-08 20:23:08.160 +0000] INFO (device-manager): Updating (33782f5c-e1df-4225-9600-630b503cdce9)
[2022-08-08 20:23:08.597 +0000] INFO (device-manager): View Live: https://app.pulumi.com/mytos/device-communication/33782f5c-e1df-4225-9600-630b503cdce9/updates/3
[2022-08-08 20:23:09.644 +0000] INFO (device-manager):     pulumi:pulumi:Stack device-communication-33782f5c-e1df-4225-9600-630b503cdce9 running
[2022-08-08 20:23:29.406 +0000] INFO (device-manager): @ Updating....
^C
```

(note we tested with an empty program, and the stack created fine even for the second device).

### Steps to reproduce

Whilst I am struggling to reproduce this exactly in a simpler script, I have tried the following (which also fails). This at least shows a simplified model of what our script is doing

```ts
import { LocalWorkspace } from "@pulumi/pulumi/automation";
import * as aws from "@pulumi/aws";
import { Region } from "@pulumi/aws";

const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;

async function stackUp(opt: { stackName: string }) {
    console.log("getting stack", opt.stackName);
    const stack = await LocalWorkspace.createOrSelectStack({
        projectName: "test-project",
        stackName: opt.stackName,
        program: async () => {
            const awsProvider = new aws.Provider("aws-provider", {
                accessKey: AWS_ACCESS_KEY_ID,
                secretKey: AWS_SECRET_ACCESS_KEY,
                region: Region.EUWest2,
            });
        },
    });
    console.log("stack up");
    await stack.up({ onOutput: console.log });
}

async function main() {
    await stackUp({ stackName: "stack-1" });
    await stackUp({ stackName: "stack-2" });
}
main();

```

### Expected Behavior

Would expect a new AWS Provider, as specified, to be instantiated and used for the stack's program.

### Actual Behavior

See above

### Versions used

package.json
```
"@pulumi/aws": "^5.10.0",
"@pulumi/pulumi": "^3.37.2",
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Hey @nebbles thanks for reporting. 

I think you've unfortunately hit an architectural issue. We're going to improve the documentation here and I can suggest a workaround. The underlying issue is here:
- #5449 

In our Go programs, we keep track of global mutable state via a `context` object that's passed to every resource object & constructor. This helps keep concurrent stack or engine events from interfering with each other. In Node.js, we don't have a solution for that yet.

There is a workaround however. I can suggest an alternative implementation that allows the same degree of code sharing. If your project were organized like so:

```
.
├── package-lock.json
├── package.json
├── src
│   ├── index.ts
│   └── stacks
│       └── test-project
│           ├── Pulumi.stack-1.yaml
│           ├── Pulumi.stack-2.yaml
│           ├── Pulumi.stack-3.yaml
│           ├── Pulumi.stack-4.yaml
│           ├── Pulumi.yaml
│           └── index.ts
└── tsconfig.json
```

You could refactor your automation API usage and still share source code & Pulumi snippets between them in the same Node project like in this repo: 

https://github.com/aaronfriel/pulumi-10325

That repo has two commits, the first is set up similar to your first example and exhibits the hang & failure. The second commit is a refactor moving the inline program to a separate folder as a "Pulumi project", but thanks to TypeScript & Node's module resolution, you can share code, interfaces, etc.

In the diff of the second commits, the options & secrets are separated to ensure the latter are encrypted and won't leak into state as unencrypted strings: https://github.com/AaronFriel/pulumi-10325/commit/b95d8094d207a3a9c6ead4bba3778592bc26cc78

**Comment by Frassle** [comment]
Those `stack.up` calls aren't in parallel, one's awaited before starting the other so I don't think this is the same as #5549

**Comment by AaronFriel** [comment]
Hmm, you might be right. I'm going to leave this open and return to it. @nebbles if this workaround works, please do let us know. I think we aim to improve inline program support as part of #5549 which may directly or indirectly fix this, but we don't have an ETA yet.

**Comment by nebbles** [comment]
Thanks @Frassle, that's correct. We await our calls and loop through our devices one after the other in series. It's slow but it used to work, so good enough for us at the time. 

However despite it previously working, it's now broken. Unfortunately I can't narrow down exactly what changed or when but it must've been upstream as we haven't changed how our provisioning script works since we wrote it. 

@AaronFriel I'll take a look into the workaround but it's a bit of a pain to have to refactor the script that used to work just fine (and indeed still works if we only run it for one device).

**Comment by AaronFriel** [comment]
@nebbles Did you identify a version that started failing?

> Whilst this used to work, at some point something seems to have broken.

I must have missed this sentence on my first read, my apologies. I'm going to mark this as a P1, which means we'll track it for inclusion in the next release & I'll take the issue onto my queue as the triage lead.

**Comment by nebbles** [comment]
> @nebbles Did you identify a version that started failing?

@AaronFriel unfortunately not yet. 

I've tried running it on the latest versions (which I updated in the last two days in an attempt to try fix it)
```
"@pulumi/aws": "^5.10.0",
"@pulumi/pulumi": "^3.37.2",
```
and the versions we had in place before were
```
"@pulumi/aws": "^4.4.1",
"@pulumi/pulumi": "^3.2.1",
```
The very confusing bit is that those dependencies, along with the script that provisioned everything hadn't been touched in 15 months. Other dependencies none of this was touched in 15 months.

The other versions being run are
```
ts-node v7.0.1
node v14.17.0
typescript v4.2.4
```

Which I can try updating now to see if it improves anything

> I must have missed this sentence on my first read, my apologies. I'm going to mark this as a P1, which means we'll track it for inclusion in the next release & I'll take the issue onto my queue as the triage lead.

Thank you! 🙏

**Comment by AaronFriel** [comment]
Hey @nebbles I dug into this, and attempted to bisect or discover a failing version of the provider (5.9, 5.10, 5.11 released today), Pulumi Node module, or Pulumi CLI version and was unable to reproduce. 

If you can reproduce it on v3.38.0 of the CLI, or in a Docker image, that would be very helpful to know. 

I've set up everything needed to run it on branch `docker-example` with a shell script to run the Docker CLI against your sample script on the previously mentioned repo: https://github.com/AaronFriel/pulumi-10325/tree/docker-example

I hope this works in the Docker image or with an update, as it would suggest something was borked with the local install or was interfering with the Pulumi CLI.

We'd like to make sure you're unblocked on using the automation API, please let us know if either of those strategies work, or - this would be very surprising - neither and we'll go from there.

**Comment by nebbles** [comment]
Hey @AaronFriel, thanks for getting back to me on this (apologies for the delay).

Whilst unable to work on this week, I'll get back to this as soon as I can to try to create a proper reproduction for this.

**Comment by nebbles** [comment]
Would be helpful to hold this until I"m able to get a bit of time to build a repro - I haven't had a moment to be able to return to it just yet but am definitely planning on it.

**Comment by nebbles** [comment]
As tested in #12942 this is no longer an issue with the latest versions of Pulumi. Crucially I had to ensure nested depedencies of `@pulumi/aws` on `@pulumi/pulumi` weren't still resolved to an old version in the yarn.lock file.
