### ISSUE TITLE
How to call external state for updating in Pulumi

### ISSUE THREAD

**Issue by larsbuch** [pulumi/pulumi#10321]
Background
I work (in Typescript on Azure) with a little more advanced scenario where resources need to have changed based on external setup. It is typically minor changes to resources based on that a new user is added/deleted or a bit more advanced when a company is added/deleted. 

Question (or perhaps feature request)
As that part of the resource setup data is outside of Pulumi I need to import state from the external store into Pulumi so that Pulumi state syncs with that part of the system state.
I try to pick up the data with a async function returning a Promise (which I wrap in the "output" function to have an Output object that Pulumi works with)
Is there a way to force "apply" to run in preview so I there can see the changes before applying them ?
Do I attack the problem the wrong way ?

**Comment by larsbuch** [comment]
Thank you for the fast answer:

What I try to do is this:
"Is this that you want to pull in data from another data source to decided exactly what resources to create in Pulumi."

As now I cannot see the changes in preview as the function is not run making preview unusable when you use that Pulumi is made with a programming language. The resources I load from has been created and variables are there and function runs if there is not updates to the resources that pulumi can see (not my minor resource adjustments or creations). It is not completely a bust as such but just a bit annoying.

**Comment by Frassle** [comment]
> As now I cannot see the changes in preview as the function is not run making preview unusable 

Are these data sources just api calls to something or are you using things like [GetResourceGroup](https://www.pulumi.com/registry/packages/azure-native/api-docs/resources/getresourcegroup/)? If your just making a call to http api or loading a file or something you shouldn't need to use Outputs and Apply at all.

**Comment by larsbuch** [comment]
I get data from a cosmos database Pulumi creates and if it does not exists it seeds the data.

I have not been able to make a stable call to async function. I know that the documentation writes that Pulumi should be able to call async functions

**Comment by Frassle** [comment]
> I get data from a cosmos database Pulumi creates and if it does not exists it seeds the data.

Ah right, so yeh not a lot you can do there. If the database isn't yet created and seeded then there's no way preview can report the data from it. 

I think a common suggestion here would be to see about splitting the stack into two projects, one that makes the database and the other that makes all the infra based on the data within it.

**Comment by larsbuch** [comment]
Tank you for the suggestions

I cannot split the stack as some configuration changes loaded are on some of the resources created earlier. Pulumis state system would just remove it. If I had the option I would not have run with Pulumi as the benefits are limited compared to running directly towards the rest services via the SDKs.

I am just accepting that preview is not working
