### ISSUE TITLE
Allow loglevel to be passed to plugins

### ISSUE THREAD

**Issue by sloncho** [pulumi/pulumi#10322]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It appears that there is no way to enable "debug/trace" log level when using Pulumi Automation - LocalWorkSpace. From CLI it would be `--logflow`.

### Affected area/feature

Automation API

**Comment by AaronFriel** [comment]
Hey @sloncho, thanks for reporting this! It looks like this is a duplicate or extension of another issue we're working on and want to release soon:
- #5855 

I think I'll keep this open though, and track completing both in the same PR, as I think we'd want to enable `--debug`, `--trace`, and `--logflow` arguments for automation API uses.
