### ISSUE TITLE
plugin download ticks backwards and forwards

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#10345]
### What happened?

when running the pulumi example at `example/aws-java-eks-minimal` after removing my `~/.pulumi/plugins` dir.

the plugin progress bar was behaving strangely and would tick back and forth(maybe multiple plugin downloads were clobbering each other)

[![asciicast](https://asciinema.org/a/6Bjur6HdoKZ6wmaNeM5NX2cRM.svg)](https://asciinema.org/a/6Bjur6HdoKZ6wmaNeM5NX2cRM)

the rest of the java error output dedup is tracked in https://github.com/pulumi/pulumi-java/issues/785

### Steps to reproduce

when running the pulumi example at `example/aws-java-eks-minimal` after removing my `~/.pulumi/plugins` dir.

### Expected Behavior

plugin download doesn't tick backwards and forwards.

### Actual Behavior

-

### Versions used

3.38.0-alpha.1660127781+8ee9c611

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lunaris** [comment]
I _think_ this will be fixed thanks to #17019, so closing as fixed.
