### ISSUE TITLE
[sdks/python] Support optional config values in pulumi.Config

### ISSUE THREAD

**Issue by kpitzen** [pulumi/pulumi#10342]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, all of the `config.get_x` methods accept only a string key, and return `Optional[<type>]` where `None` is returned if the config key is not set.  This requires users to add additional logic to provide default values to this configuration depending on the return value of the function.  Instead, it would be ideal if each of these methods could support an optional `default` parameter of their corresponding type to be returned if no config value is set for a given key.

ex:
Instead of:
```python
some_value = config.get("someKey") if config.get("someKey") is not None else my_default
```
we provide an interface that allows for:
```python
some_value = config.get("someKey", my_default)
```

### Affected area/feature

Pulumi Python SDK
This issue also blocks https://github.com/pulumi/pulumi/issues/10268

**Comment by RobbieMcKinstry** [comment]
@kpitzen Forgive me if my Python-foo is out of date, but how would you update the signature to be non-breaking with the current signature?

I was originally picturing the API to look like this:
```python
config.get("someKey", default=my_default)
```

Are you intending to accept the second parameter with `*args`, accepting whatever the first unnamed argument is as the default?

**Comment by kpitzen** [comment]
Obv haven't updated docstrings or anything yet, but you get the idea :)

**Comment by RobbieMcKinstry** [comment]
Ah yes! Okay thank you, that answers my question! SGTM!
