### ISSUE TITLE
Consider explicit `go build` instead of `go run` for running Go programs

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#10350]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Consider removing `go run` style code execution in favor of `go build` followed by running the generated program.

As of pulumi 3.37.2 `pulumi-language-go` has two modes of executing user code, with `go run .` being by far the most common:

- `go run .`
- `./$binary` if .runtime.binary option is set in Pulumi.yaml

The execution happens every time Pulumi interacts with the user program (preview, up, etc), every command ends up calling into this.

The suggestion is to replace `go run .` with two steps, managing a local binary file explicitly:

```go build -o $program```
```./$program```

### Benefits
 
1. Better diagnostics. Currently `go run` hijacks exit codes, see for example https://github.com/golang/go/issues/17813 ; namely it returns exit code 0 for ok, 1 for program error, and 2 for compilation error. If the program exits with a non-0 exit code, instead of returning that code it prints it "exit code 3" for example. Not using `go run` would make it easy for Pulumi to distinguish between compile and runtime errors and print them nicely, and suppress redundant "exit code 3" messages from output (original discussion in https://github.com/pulumi/pulumi/pull/10265).

2. Better execution speed information in the metrics. We would be able to put separate spans and measure compilation/linking vs raw execution time to better identify where slowness is introduced.

3. Unlock path to a Go Build Cache https://github.com/pulumi/pulumi/issues/10473 that would speed up Go programs

### Design

- If PULUMI_GO_USE_RUN=true is set, use default behavior
- If it is not set (by default), use `go build -o $tempFile` to build and `exec $tempFile` to run
- Clean up $tempFile when done
- Note that on Windows the $tempFile must end in `.exe`

### Affected area/feature

Go language support

**Comment by Frassle** [comment]
I can't recall what issue I hit but I'm sure I had another reason for wanting to look at using go build instead of run... Will have to rack my brains, but +1 to this idea anyway

**Comment by dixler** [comment]
one of the concerns with this is when a directory is not readable as we are outputting a new file.

if a company has a policy for securing docker images by disabling write permissions to directories, they may be unable to upgrade `pulumi-language-go` without it breaking.

**Comment by Frassle** [comment]
> if a company has a policy for securing docker images by disabling write permissions to directories, they may be unable to upgrade pulumi-language-go without it breaking.

Isn't tmp always writable, "go run" itself needs to write to a temporary file to work, so I think we can assume that's safe.

**Comment by t0yv0** [comment]
Also there is`~/.pulumi`, which currently manages plugins. Could be something like `~/.pulumi/go-compiler-cache/$(hash-of-current-folder)`

**Comment by Frassle** [comment]
> Could be something like ~/.pulumi/go-compiler-cache/$(hash-of-current-folder)

I had suggested to just use temp (as that's what go run does) but this is also an interesting idea. Might be worth looking into what's need to get build caching from the go compiler?

**Comment by t0yv0** [comment]
The advantage of ~/.pulumi is then we can do `pulumi prune` command to get rid of that. I don't know when we'd know automatically that it is a good time to delete these binaries; these are not really temp files we know when to delete. In the limit, it can leak temp disk space if we never delete nor provide any means to do so.

**Comment by dixler** [comment]
> > if a company has a policy for securing docker images by disabling write permissions to directories, they may be unable to upgrade pulumi-language-go without it breaking.
> 
> 
> 
> Isn't tmp always writable, "go run" itself needs to write to a temporary file to work, so I think we can assume that's safe.

/tmp exists on windows?

**Comment by t0yv0** [comment]
There are cross-platform Go APIs e.g. https://gobyexample.com/temporary-files-and-directories

**Comment by dixler** [comment]
> The advantage of ~/.pulumi is then we can do `pulumi prune` command to get rid of that. I don't know when we'd know automatically that it is a good time to delete these binaries; these are not really temp files we know when to delete. In the limit, it can leak temp disk space if we never delete nor provide any means to do so.
> 
> We wouldn't need anything special from the compiler here just:
> 
> ```
> go build -o ~/.pulumi/go-compiler-cache/$(hash-of-current-folder)/$(name-of-program)
> ~/.pulumi/go-compiler-cache/$(hash-of-current-folder)/$(name-of-program) # execute
> ```

It sounds like we're creating our own build system for Go. I can make tempdirs in `$HOME/.pulumi/go/` for now as I'm more concerned with unblocking and delivering #10227. Maybe we can add caching in later?

**Comment by t0yv0** [comment]
> It sounds like we're creating our own build system for Go.

I don't think that's fair. The concern is disk space leak from retained compiled Go programs (especially on servers running autonomously). There are two approaches:

- write to TEMP, periodically clean up TEMP
- write to a Pulumi-managed place in the file system, add either clean this up as part of Pulumi commands or add a new command to clean it up
   - this could be a new folder like ~/.pulumi/go-compiler-cache
   - this could tie into ~/.pulumi/workspaces or ~/.pulumi/stacks, perhaps with clean up on `pulumi stack destroy`

I guess using write-and-forget to TEMP is the least work and is acceptable if we believe the OS periodically frees up space by deleting files in TEMP. If we take this route, we'd just need to point this out in CHANGELOG, so if users start experiencing issues with disk space leaks we can identify this behavior change as a source.

**Comment by dixler** [comment]
> The advantage of ~/.pulumi is then we can do `pulumi prune` command to get rid of that. I don't know when we'd know automatically that it is a good time to delete these binaries; these are not really temp files we know when to delete. In the limit, it can leak temp disk space if we never delete nor provide any means to do so.
> 
> We wouldn't need anything special from the compiler here just:
> 
> ```
> go build -o ~/.pulumi/go-compiler-cache/$(hash-of-current-folder)/$(name-of-program)
> ~/.pulumi/go-compiler-cache/$(hash-of-current-folder)/$(name-of-program) # execute
> ```

I have an approach that doesn't hash the current folder and instead uses the name of the project as the binary name. This should avoid creating too many binaries as each project has 1 cache entry that gets reused.

```
~/.pulumi/go-compiler-cache/$(name-of-project) # go program binary path
```

**Comment by Frassle** [comment]
> I have an approach that doesn't hash the current folder and instead uses the name of the project as the binary name. This should avoid creating too many binaries as each project has 1 cache entry that gets reused.

I think this is an interesting approach, but I would err on shipping just the simple write the TEMP still for the first pass at this. Once we're happy that "go build" vs "go run" isn't causing any issues, we can start having some smarts like this added as feature flags (PULUMI_GO_CACHE_BUILDS?), that eventually become the default.

**Comment by t0yv0** [comment]
After discussing with @Frassle, scoped this down and moved https://github.com/pulumi/pulumi/issues/10473 out to go as a separate change. @dixler apologies for a lot of back-and-forth on the reqs here.

**Comment by AaronFriel** [comment]
> The risks with caching builds are scoped out now so the only risk is changes in exit code handling.

Do these changes introduce any change, operationally, compared to `go run`? I want to ensure that if we have heavy users of automation API who might be running `pulumi up` on web requests. If they have processes in place to address disk usage from temporary binaries, go module caching, or unknown unknowns, I would prefer we don't surprise their ops teams with a change in behavior and instead roll it out as opt-in at first, then as a replacement. 

Delaying turning on this perf change by a release or two while we get a customer to evaluate has a marginal downside (delaying a perf win), but if it mitigates or helps us validate that there were no unknown unknowns, that makes me feel much more comfortable.
