### ISSUE TITLE
Unable to login to azblob on Azure Government

### ISSUE THREAD

**Issue by mfilipiak-ccg** [pulumi/pulumi#10359]
### What happened?

Attempting to use azblob `pulumi login` on Azure Government. I am not able to find any documentation for doing this, or what needs to be overridden to get the correct auth override URLs to get everything wired correctly.

Is there any documentation to what needs to be done to get this working?

### Steps to reproduce

`pulumi log azblob://{pulumi-container}`

Set the following variables (collected from terraform and other docs)

```
export ARM_CLIENT_ID=
export ARM_CLIENT_SECRET=
export ARM_ENVIRONMENT="usgovernment"
export ARM_SUBSCRIPTION_ID=
export ARM_TENANT_ID=
export ARM_STORAGE_KEY=
export ARM_STORAGE_ACCOUNT="pulumi"
export ARM_AD_ENDPOINT="https://login.microsoftonline.us"

export AZURE_CLIENT_ID=$ARM_CLIENT_ID
export AZURE_CLIENT_SECRET=$ARM_CLIENT_SECRET
export AZURE_ENVIRONMENT=$ARM_ENVIRONMENT
export AZURE_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
export AZURE_TENANT_ID=$ARM_TENANT_ID
export AZURE_STORAGE_KEY=$ARM_STORAGE_KEY
export AZURE_STORAGE_ACCOUNT=$ARM_STORAGE_ACCOUNT
export AZURE_AD_ENDPOINT=$ARM_AD_ENDPOINT
```

### Expected Behavior

Can use a blob storage to store pulumi state on Azure Government.

### Actual Behavior

Receive error:

```
x-ms-client-request-id:66f1fa9e-1ce6-4e90-586b-dd1c2b71f190
x-ms-date:Wed, 10 Aug 2022 03:43:49 GMT
x-ms-version:2020-04-08
/pulumi/pulumi
comp:list
delimiter:
maxresults:1
restype:container
timeout:61'.
   Code: AuthenticationFailed
   GET https://pulumi.blob.core.windows.net/pulumi?comp=list&delimiter=&maxresults=1&restype=container&timeout=61
   Authorization: REDACTED
   User-Agent: [go-cloud/blob/0.1.0 Azure-Storage/0.14 (go1.17.12; linux)]
   X-Ms-Client-Request-Id: [66f1fa9e-1ce6-4e90-586b-dd1c2b71f190]
   X-Ms-Date: [Wed, 10 Aug 2022 03:43:49 GMT]
   X-Ms-Version: [2020-04-08]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
   Content-Length: [766]
   Content-Type: [application/xml]
   Date: [Wed, 10 Aug 2022 03:43:49 GMT]
   Server: [Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthenticationFailed]
   X-Ms-Request-Id: [8232f3ff-901e-0094-436b-ac4adb000000]
```

### Versions used

CLI          
Version      3.37.2
Go Version   go1.17.12
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.67.0
azuread       5.26.1
go            unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='1.19 linux/amd64'

Dependencies:
NAME                                       VERSION
github.com/pulumi/pulumi-azure-native/sdk  v1.67.0
github.com/pulumi/pulumi-azuread/sdk/v5    v5.26.1
github.com/pulumi/pulumi/sdk/v3            v3.34.0
gopkg.in/yaml.v3                           v3.0.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Hey @mfilipiak-ccg, we support the query options that the library we use supports, [`gocloud.dev/blob`](https://pkg.go.dev/gocloud.dev/blob/azureblob?utm_source=godoc#URLOpener):

Could you try adding a query option such as:

```
pulumi log azblob://{pulumi-container}?domain=blob.core.usgovcloudapi.net
```

**Comment by mfilipiak-ccg** [comment]
Apologies, I thought I had replied to this. Thank you @AaronFriel . This solution worked flawlessly. I would have not arrived at this solution without your help.
