### ISSUE TITLE
Sometimes I get prompted for a password twice

### ISSUE THREAD

**Issue by solomonshorser** [pulumi/pulumi#10372]
### What happened?

I get prompted for the password twice when I run `pulumi preview` or `pulumi up`, but `pulumi export` only prompts me once. Why is it this inconsistent?

### Steps to reproduce

1. Execute `pulumi up` or `pulumi preview`.
2. Enter password
3. Enter password again so pulumi can do it's thing.
4. Execute `pulumi export --file someFile.json`
5. Enter password once and observe that `someFile.json` now exists.

### Expected Behavior

1. Execute `pulumi up` or `pulumi preview`.
2. Enter password
3. Pulumi does what I asked it to without a second password prompt.

### Actual Behavior

I got prompted for the password twice.

### Versions used

```
CLI
Version      3.37.2
Go Version   go1.17.12
Go Compiler  gc

Plugins
NAME           VERSION
gcp            5.14.0
google-native  0.18.0
google-native  0.14.0
kubernetes     3.20.2
nodejs         unknown
random         4.2.0

Host
OS       darwin
Version  12.5
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.0.0'
```
*NOTE:* `pulumi about` only prompts for the password once.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
@solomonshorser thanks for reporting this, could you tell me what the prompt is for the password? I think this is either the password for the backend (`pulumi login`) or the passphrase for the stack's configuration, if using the local backend with a passphrase. Can you elaborate?

**Comment by solomonshorser** [comment]
The prompt looks like this:

```
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
```

The backend is a gs bucket, not local.

**Comment by AaronFriel** [comment]
@solomonshorser I'm unable to reproduce locally, using `pulumi login gs://[SOME_BUCKET]`. I set up a simple Pulumi program and then ran:

```log
$ pulumi login gs://[SOME BUCKET]

$ pulumi stack init
stack name: (dev) 
Created stack 'dev'
Enter your passphrase to protect config/secrets: # entered password here
Re-enter your passphrase to confirm: # entered password here

$ pulumi preview
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember): # entered again
Previewing update (dev):
     Type                            Name                Plan       
 +   pulumi:pulumi:Stack             tmp.JquQCjM7Jl-dev  create     
 +   └─ random:index:RandomPassword  my-bucket           create     
 
Outputs:
    bucketName: output<string>

Resources:
    + 2 to create
```

This seems like expected behavior, are you getting **two** prompts for the password on `pulumi preview`?

**Comment by Frassle** [comment]
This is probably on `up` not `preview`. That internally invokes two internal engine deployments and I imagine there might be something there that causes the password stuff to get init'd twice?

**Comment by solomonshorser** [comment]
@AaronFriel I got the two prompts with `up` and `preview`. I got a single password prompt with `import` and `export`.

**Comment by solomonshorser** [comment]
Also, `pulumi state delete` only required one prompt.

**Comment by Frassle** [comment]
> The backend is a gs bucket, not local.

For the record, I don't think backend matter at all here. It's just because the secrets provider is the passphrase one, which you can use with the service backend as well.

**Comment by solomonshorser** [comment]
I _gave_ feedback. My last message was this one (https://github.com/pulumi/pulumi/issues/10372#issuecomment-1215171747), the last message before the bot chipped in.

Either way, I had to destroy/remove the stack that this was happening with, and it doesn't seem to be happening with my new stack - yet.

> It's just because the secrets provider is the passphrase one, which you can use with the service backend as well.

Now this confuses me - how would I use the same provider for a secrets provider as well as a backend? The backend is a gs bucket. How would I use a gs bucket as a secret provider?

**Comment by Frassle** [comment]
> I did give feedback. 

Yes sorry about that, I removed the feedback labels when I saw the bot make that comment. This ticket will stay open now.

> Now this confuses me - how would I use the same provider for a secrets provider as well as a backend?

State backends are separate from secrets providers, so you can have a service backend but an google kms secret provider. My point was that I don't think the fact your using a gs bucket is relevant to why your getting a password prompt twice, we'd _probably_ see the same behavior for other backends,. It should be possible to repro this just using file state, not a bucket.

**Comment by solomonshorser** [comment]
@Frassle Ah, ok.

It hasn't happened since I destroyed and recreated my stack, and I don't know how to reproduce it since I don't know how I got it to do it in the first place.

I guess this can be closed now, but if I figure out how to reliably reproduce this, I'll reopen with the details.
