### ISSUE TITLE
Report progress and estimated completion time in CLI

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1037]
Let's report an accurate percentage complete and estimated time remaining for Pulumi updates.

I think this is doable. Since we start with an initial state with N resources, each with a type T. And will either "noop", update, or destroy each of those N resources; as well as create N' new resources.

Seems like the estimated time would just be the sum of the average update time for each resource based on its type, and just increase/decrease that esitmate as we encounter noop updates or new resources to create.

**Comment by lukehoban** [comment]
This hasn't come up again in last ~2 years.  We might consider things in the future along these lines - but can close this issue out for now.
