### ISSUE TITLE
error: could not deserialize deployment: [503]

### ISSUE THREAD

**Issue by thanhtoan1196** [pulumi/pulumi#10384]
### What happened?

I get this error when I run `pulumi up`
```
error: could not deserialize deployment: [503]
```
Sometimes it's this error
```
error: [503]
```

### Steps to reproduce

I run `pulumi up`

### Expected Behavior

Run `pulumi up` without error

### Actual Behavior

I get this error when I run `pulumi up`
```
error: could not deserialize deployment: [503]
```
Sometimes it's this error
```
error: [503]
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Hi @thanhtoan1196. Which backend are you using?
Can you provide us with some logs from your run? 
How frequently are you encountering this error? 
What version of the CLI are you using? Could you provide a code snippet so we can attempt to reproduce?

**Comment by thanhtoan1196** [comment]
> Which backend are you using?

I use Pulumi Service Backend

> Can you provide us with some logs from your run?

That's all logs

> How frequently are you encountering this error?

Always on that day

> What version of the CLI are you using?

v3.37.2

**Comment by thanhtoan1196** [comment]
I switched from `Pulumi Service Backend` to `Local Filesystem Backend` and no more errors

**Comment by Frassle** [comment]
> How frequently are you encountering this error?
> Always on that day

This is highly suggestive that you had network issues on the day. We've had no reports from the service team of degraded availability from our side.

> I switched from Pulumi Service Backend to Local Filesystem Backend and no more errors

Well yes, that doesn't need a network connection to work.
