### ISSUE TITLE
Support PyYAML 6.0+

### ISSUE THREAD

**Issue by Xboarder56** [pulumi/pulumi#10396]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'm trying to leverage Pulumi as a solution to splunk rule management. However, PySigma requires PyYAML 6.0+ and Pulumi only supports PyYaml 5.3~. I'm sure other packages have this issue and because they both utilize the same venv this causes issues with trying to build the venv. 

### Affected area/feature

Pulumi only support PyYaml 5.3~ and PyYaml is up to 6.0

**Comment by RobbieMcKinstry** [comment]
@Xboarder56  thanks for bringing this to our attention. We'll update PyYAML to 6.0 :)
