### ISSUE TITLE
Allow cross-resource aliases 

### ISSUE THREAD

**Issue by caboog** [pulumi/pulumi#10412]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Could aliasing be made to work across different resources? When migrating providers, such as going from using Pulumi command to Kubernetes, existing resources get destroyed then recreated with the new provider. It would be ideal if we could change the provider, then alias to the old resource to avoid the destroy/recreate process.

**Comment by Frassle** [comment]
> It would be ideal if we could change the provider, then alias to the old resource to avoid the destroy/recreate process.

I think you can? Aliases can refer to an old type, such that the engine considers them the same resource. e.g. https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi/Pulumi.Alias.html#Pulumi_Alias_Type

**Comment by RobbieMcKinstry** [comment]
It sounds like you have a K8s resourced created by a [Pulumi.Command](https://www.pulumi.com/registry/packages/command/api-docs/local/) resource running `kubectl apply -f` (or something similar) locally.

If you want to migrate to a K8s resource gracefully, another option would be to use [`retain-on-delete`](https://www.pulumi.com/docs/intro/concepts/resources/options/retainondelete/) to allow you to delete the `local` command and then use [`pulumi import`](https://www.pulumi.com/docs/guides/adopting/import/) to capture the K8s resource in your state.

**Comment by caboog** [comment]
Thanks @Frassle and @RobbieMcKinstry. Passed along the `retain-on-delete` flag option to the customer. Specifying type didn't work in my (admittedly limited) situation, but that looks promising as well so that got passed along as well.
