### ISSUE TITLE
Unclear how to use `pulumi.runtime.registerStackTransformation`

### ISSUE THREAD

**Issue by alfred-stokespace** [pulumi/pulumi#10428]
### What happened?

I'm trying to follow the guidance of two blog posts, both claiming to explain how to do auto-tagging of resources.
1. https://www.pulumi.com/blog/how-webiny-built-a-serverless-application-framework/#automatic-tagging-of-cloud-infrastructure-resources
2. https://www.pulumi.com/blog/automatically-enforcing-aws-resource-tagging-policies/#applying-tags-enforcement-in-the-saas-console
Both make reference to this function...
 > ```
 > https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/runtime/#registerStackTransformation
 > ```
In addition one talking about Stack Transformations... https://www.pulumi.com/docs/intro/concepts/resources/options/transformations/

However, none is particularly clear how this method is supposed to be called in a successful manner. 

When I use them as I expect it to work (ie. not copy/pasting code into each use of auto tagging) I get 
```
 error: Running program '/REDACTED/project' failed with an unhandled exception:
    Error: The root stack resource was referenced before it was initialized.
        at Object.registerStackTransformation (/REDACTED/pulumi/common/tagsalot/autotag/node_modules/@pulumi/runtime/stack.ts:222:15)
```

### Steps to reproduce

1. Create a "normal" pulumi project, lets say aws-typescript
2. Create a bucket in that project
3. Create another ts package (not a pulumi project) with just this code 
  > ```
  > import * as pulumi from "@pulumi/pulumi";
  > import {isTaggable} from "../taggable";
  > /**
  >  * registerAutoTags registers a global stack transformation that merges a set
  > * of tags with whatever was also explicitly added to the resource definition.
  > */
  > export function registerAutoTags(autoTags: Record<string, string>): void {
  >     pulumi.runtime.registerStackTransformation((args) => {
  >         if (isTaggable(args.type)) {
  >             args.props["tags"] = { ...args.props["tags"], ...autoTags };
  >             return { props: args.props, opts: args.opts };
  >         }
  >         return undefined;
  >     });
  > }
  > ```
4. Satisfy the isTaggable method with example from 2nd blog https://github.com/joeduffy/aws-tags-example/blob/master/autotag-ts/taggable.ts
5. Include the exported function `registerAutoTags` in your Pulumi project `import {registerAutoTags} from "../../common/autotag/AutoTagger";`
6. prepare for the registration
  > ```
  > const autoTagConfig = {
  >    "user:Project": pulumi.getProject(),
  >    "user:Stack": pulumi.getStack(),
  >    "user:CostCenter": "DevOps",
  > } as Record<string, string>
  >
  > registerAutoTags(autoTagConfig)
  > ```
8. try and `pulumi up` your project

### Expected Behavior

A solution without copy-paste of `registerStackTransformation` please.

A single auto-tagging library with the boilerplate `pulumi.runtime.registerStackTransformation` call encapsulated inside and many projects able to import and call that reusable function. 

### Actual Behavior

```
 error: Running program '/REDACTED/project' failed with an unhandled exception:
    Error: The root stack resource was referenced before it was initialized.
        at Object.registerStackTransformation (/REDACTED/pulumi/common/tagsalot/autotag/node_modules/@pulumi/runtime/stack.ts:222:15)
```

### Output of `pulumi about`

```
CLI
Version      3.37.2
Go Version   go1.17.12
Go Compiler  gc

Plugins
NAME    VERSION
aws     4.17.0
docker  3.0.0
nodejs  unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v14.20.0'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/ME
User           ME
Organizations  ME, MYORG

Dependencies:
NAME            VERSION
@pulumi/aws     4.17.0
@pulumi/awsx    0.30.0
@pulumi/pulumi  3.10.3
@types/node     10.17.60

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by alfred-stokespace** [comment]
After looking at how you've implemented this ...
https://github.com/pulumi/pulumi/blob/0d0144bca2aca22e5fccd9484038a5eac596c324/sdk/nodejs/runtime/stack.ts#L221
I can see that there a global you are protecting https://github.com/pulumi/pulumi/blob/0d0144bca2aca22e5fccd9484038a5eac596c324/sdk/nodejs/runtime/stack.ts#L30

Apparently when trying to call into my child package (which has the registerAutoTags) that is detecting that there as more then one of these globals.

I worked around this by changing the registryAutoTags to accept a callback...
```
export function registerAutoTags(autoTags: Record<string, string>, callback: (t: ResourceTransformation) => void ): void {
    callback((args) => {
        if (isTaggable(args.type)) {
            args.props["tags"] = { ...args.props["tags"], ...autoTags };
            return { props: args.props, opts: args.opts };
        }
        return undefined;
    });
}
```
and then in the parent I can do this... 

```
const autoTagConfig = {
    "user:Project": pulumi.getProject(),
    "user:Stack": pulumi.getStack(),
    "user:CostCenter": "DevOps",
} as Record<string, string>
registerAutoTags(autoTagConfig, pulumi.runtime.registerStackTransformation)
```

So each of the pulumi projects where I want to autotag things I need that snippet of code added. Not to bad. 
I guess I'd like some commentary on how you intended us to be using this and is this really the best way to achieve what I'm doing?

**Comment by alfred-stokespace** [comment]
That workaround is not great for at least the following reason...
when I apply this snippet 
```
registerAutoTags({
    "user:Project": pulumi.getProject(),
    "user:Stack": pulumi.getStack(),
    "user:CostCenter": "DevOps",
} as Record<string, string>, pulumi.runtime.registerStackTransformation)
```
I have to do it in each file which has taggable resources... 
I was deeply hoping that I could do it once in the index.ts of the pulumi project and that all resources would get captured... not great at all. Without per-file copy/paste you get nagged about the out-of-policy resources in each file

**Comment by alfred-stokespace** [comment]
Additionally, I'm finding that awsx doesn't respect the registration.

The following example shows no indication of tagging either the vpc or the public/private subnets that derive from the `awsx.ec2.Vpc` creation
```
pulumi.runtime.registerStackTransformation((args) => {
    if (isTaggable(args.type)) {
        args.props["tags"] = {...args.props["tags"], ...{
                "user:Project": pulumi.getProject(),
                "user:Stack": pulumi.getStack(),
                "user:CostCenter": "Test",
            } as Record<string, string>};
        return {props: args.props, opts: args.opts};
    }
    return undefined;
});

// Allocate a new VPC with public and private subnets per AZ:
const vpc = new awsx.ec2.Vpc("services-main", {
    cidrBlock: "172.31.0.0/16",
    numberOfAvailabilityZones: "all",
    subnets: [{type: "public"}, {type: "private"}],
});

```
the policy results look like ...
```
    [advisory]  aws-policy-enforcement v0.0.4  check-required-tags (aws:ec2/subnet:Subnet: services-main-public-2)
    Ensure required tags are present on all taggable resources.
    Taggable resource 'urn:pulumi:prod::service-base::awsx:x:ec2:Vpc$awsx:x:ec2:Subnet$aws:ec2/subnet:Subnet::services-main-public-2' is missing required tag 'user:Stack'
```
when you examine the preview changes you see that anything created with awsx isn't going to get tagged but the child resources created via the non-awsx libarary will get tagged
```
     │  ├─ awsx:x:ec2:Subnet            services-main-public-0
 ~   │  │  └─ aws:ec2:RouteTable        services-main-public-0         update     [diff: ~tags]
```

**Comment by Frassle** [comment]
> Additionally, I'm finding that awsx doesn't respect the registration.

That's a known issue with packaged components: https://github.com/pulumi/pulumi/issues/6948

> Apparently when trying to call into my child package (which has the registerAutoTags) that is detecting that there as more then one of these globals.

That's _very_ odd, the whole point of using a globals declaration here was to tell nodejs that we really do mean to have only one stack variable, regardless of how many times the pulumi module is loaded.

**Comment by alfred-stokespace** [comment]
> Error: The root stack resource was referenced before it was initialized.

@Frassle Thanks for the comment, I think I misspoke and miss-read the code, The error message doesn't say there are two it says that the resource isn't initialized
```
export function registerStackTransformation(t: ResourceTransformation) {
    if (!globalThis.stackResource) {
        throw new Error("The root stack resource was referenced before it was initialized.");
    }
    globalThis.stackResource.__transformations = [...(globalThis.stackResource.__transformations || []), t];
}
```
So my bad there. I was skimming rather then reading carefully.

**Comment by Frassle** [comment]
Yeh you need to call registerStackTransformation after the global state has been initialized, I think as long as "@pulumi/pulumi" is imported first that might happen.

**Comment by alfred-stokespace** [comment]
> Yeh you need to call registerStackTransformation after the global state has been initialized, I think as long as "@pulumi/pulumi" is imported first that might happen.

The code block I have in the opening "Steps to reproduce" show that the parent is doing a `"@pulumi/pulumi"` import and that was the use case I used when I got the error about uninitialized reference. So unfortunately it seems that's not sufficient.

**Comment by Frassle** [comment]
Actually even that _shouldn't_ be needed. We don't import the user program at all until we've setup the global state, so your call to registerStackTransformation should work.

I think your issue is your on an old version of `@pulumi/pulumi`:
```
@pulumi/pulumi  3.10.3
```
I'd update your library and program to 3.38.0 and try again, I think your hitting a bug where stack transforms used to not work due to module rather than global variables.

**Comment by alfred-stokespace** [comment]
Yeah, updating pulumi version did the trick. Thanks. **Both** parent and child needed the update though. 

in child ( _shared typescript module, but not a pulumi project_ ) 

changed
```
callback((args) => {
```
(`callback` was a function returning `pulumi.runtime.registerStackTransformation` ) to 
```
pulumi.runtime.registerStackTransformation((args) => {
```
Dependencies for child project... (npm update && npm audit fix, there were some vulnerabilities)
```
 "dependencies": {
        "@pulumi/aws": "^4.38.1",
        "@pulumi/awsx": "^0.30.0",
        "@pulumi/pulumi": "^3.38.0"
    }
```

in parent (pulumi project)  I did an npm update && npm audit fix (there were some vulnerabilities)
` cat package.json`
...

```
{
    "name": "service-instances",
    "devDependencies": {
        "@types/node": "^10.0.0"
    },
    "dependencies": {
        "@pulumi/aws": "^4.38.1",
        "@pulumi/awsx": "^0.30.0",
        "@pulumi/pulumi": "^3.38.0",
 ...
    }
}

```

**Comment by Frassle** [comment]
> Thanks. Both parent and child needed the update though.

Yup that's expected, they both need to be on recent enough versions of the code that looks at the global var not the module var.

**Comment by alfred-stokespace** [comment]
That also seems to have fixed the issue where sub directories with new resource creations were needing duplicates of the register auto tag call. Now it seems that I only need a single register call at the entry index.js file of the project.  So yes, that clarifies how it's supposed to be used.

**Comment by ghostsquad** [comment]
Is there an example of how to do this autotagging transformation in Golang?
