### ISSUE TITLE
Ampersand in output being converted to \u0026 in state file

### ISSUE THREAD

**Issue by eli88fine** [pulumi/pulumi#10439]
### What happened?

In the console output of the `up`, the output shows up as expected:

`auto-eng-appstream-relay-endpoint-url: "https://appstream2.us-east-1.aws.amazon.com/saml?stack=auto-eng-appstream--appstream--prod-4e3f21b&accountId=111111111111"`

However, when I go to the state file to look at it to grab a bunch of outputs (I'm grabbing them manually from the state file because I need to give them to our SSO IT provider so that they can configure SSO access for this appstream), the ampersand has been converted to escaped unicode (\u0026)...which definitely does **not** work if you try and use it in a URL:
`"auto-eng-appstream-relay-endpoint-url": "https://appstream2.us-east-1.aws.amazon.com/saml?stack=auto-eng-appstream--appstream--prod-4e3f21b\u0026accountId=111111111111"`

I'm using an S3 bucket to store the state, but hopefully that doesn't have anything to do with the issue

### Steps to reproduce

`export("auto-eng-appstream-relay-endpoint-url", "https://appstream2.us-east-1.aws.amazon.com/saml?stack=auto-eng-appstream--appstream--prod-4e3f21b&accountId=111111111111")`

### Expected Behavior

the output in the console matches the output in the state file

### Actual Behavior

the state file converted the ampersand to \u0026

### Output of `pulumi about`

`pulumi about` does not work when using self-hosted Pulumi.

But here's `pulumi plugin ls`

pulumi plugin ls
NAME        KIND      VERSION  SIZE    INSTALLED    LAST USED
aws         resource  5.10.0   391 MB  2 weeks ago  2 weeks ago
aws-native  resource  0.19.0   82 MB   2 weeks ago  2 weeks ago
command     resource  0.4.1    24 MB   2 weeks ago  2 weeks ago

and here's `pip freeze` (I'm using python-flavored pulumi):

Arpeggio==1.10.2
astroid==2.11.7
attrs==21.4.0
boto3==1.24.44
boto3-stubs==1.24.44
botocore==1.27.45
botocore-stubs==1.27.33
cattrs==22.1.0
cfgv==3.3.1
click==8.1.3
colorama==0.4.5
copier==6.1.0
dill==0.3.5.1
distlib==0.3.5
dunamai==1.12.0
exceptiongroup==1.0.0rc8
filelock==3.7.1
grpcio==1.47.0
iam-floyd==0.407.0
identify==2.5.2
importlib-metadata==4.12.0
iniconfig==1.1.1
isort==5.10.1
iteration-utilities==0.11.0
Jinja2==3.1.2
jinja2-ansible-filters==1.3.2
jmespath==1.0.1
jsii==1.63.2
lazy-object-proxy==1.7.1
MarkupSafe==2.1.1
mccabe==0.7.0
mypy==0.971
mypy-boto3-lambda==1.24.40
mypy-boto3-s3==1.24.36.post1
mypy-boto3-sts==1.24.36.post1
mypy-extensions==0.4.3
nodeenv==1.7.0
packaging==21.3
parver==0.3.1
pathspec==0.9.0
pep517==0.12.0
pip-tools==6.6.2
platformdirs==2.5.2
pluggy==1.0.0
plumbum==1.7.2
pre-commit==2.19.0
prompt-toolkit==3.0.30
protobuf==4.21.2
publication==0.0.3
pulumi==3.37.2
pulumi-aws==5.10.0
pulumi-aws-native==0.19.0
pulumi-command==0.4.1
py==1.11.0
pydantic==1.9.1
pyenchant==3.2.2
Pygments==2.12.0
pylint==2.14.5
pyparsing==3.0.9
pytest==7.1.2
pytest-mock==3.8.1
pytest-pylint==0.18.0
pytest-randomly==3.11.0
python-dateutil==2.8.2
PyYAML==5.4.1
pyyaml-include==1.3
questionary==1.10.0
s3transfer==0.6.0
semver==2.13.0
six==1.16.0
stdlib-utils==0.4.8
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.1
typeguard==2.13.3
types-s3transfer==0.6.0.post4
typing_extensions==4.3.0
urllib3==1.26.10
virtualenv==20.15.1
wcwidth==0.2.5
wrapt==1.14.1
zipp==3.8.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> pulumi about does not work when using self-hosted Pulumi.

Really, it should work. What happens?

> the ampersand has been converted to escaped unicode (\u0026)

Looks like this is go's default JSON behavior. We've turned it off in a few places with `SetEscapeHTML(false)` but I guess not when writing stack files, should be an easy fix.

**Comment by Frassle** [comment]
Huh maybe not a quick fix. It seems if using `json.NewEncoder` this is easy to toggle of with aforementioned method. But most of our code uses `json.Marshal` which has _no_ way to disable HTML escaping that I can see.

**Comment by eli88fine** [comment]
`pulumi about` asks me to login.  but I don't have a pulumi.com login
![image](https://user-images.githubusercontent.com/5436635/185489575-a0a151cb-0f86-441e-a986-885da686b117.png)

**Comment by Frassle** [comment]
oh interesting, I'll have a look into that as well then :)

**Comment by eli88fine** [comment]
I guess if I do `pulumi login -l`, then I can do `about` and it shows this

CLI          
Version      3.37.2
Go Version   go1.17.12
Go Compiler  gc

Host     
OS       debian
Version  10.12
Arch     x86_64


...but it doesn't seem like any of that system information should _require_ logging in
