### ISSUE TITLE
reserving issue for change feedback

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#10441]
### What happened?

.

### Steps to reproduce

.

### Expected Behavior

.

### Actual Behavior

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
It's been 5 days since this issue was created. Please fill it up or close it. Thank you!

**Comment by dixler** [comment]
design changed and derisked the PR. closing.
