### ISSUE TITLE
Protected resources prevent detailed diffs from being shown with 'preview' command

### ISSUE THREAD

**Issue by solomonshorser** [pulumi/pulumi#10463]
### What happened?

We had a protected resource that was causing diffs but `preview --diff --refresh` was not showing any details about the resource's differences. When we unprotected the resource (locally, in code: `protect: false`), we were able to see the resource's detailed differences.

### Steps to reproduce

1. Create a protected resource (in our case, it was an SQL Instance https://www.pulumi.com/registry/packages/google-native/api-docs/sqladmin/v1/instance/#instance )
2. Change something in `settings`
3. Run `pulumi preview --refresh --diff`
4. See an error about how a protected resource cannot be replaced - even though we're just trying to get a _preview_ of what might be replaced:
```
error: unable to replace resource "urn:pulumi:stack_name::resource_name::google-native:sqladmin/v1:Instance::cloudSqlInstance" 
as it is currently marked for protection. To unprotect the resource, remove the `protect` flag from the resource in your Pulumi program and run `pulumi up` 
```
5. Turn off resource protection (`protect: false`)
6. Re-run `pulumi preview --refresh --diff` and get a _proper_ diff.

### Expected Behavior

We expected to get a proper diff, even though the resource was protected.

### Actual Behavior

We got an error message.

### Output of `pulumi about`

```
CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc
Plugins
NAME                VERSION
gcp                 6.34.0
gcp                 5.26.0
gcp                 5.26.0
gcp                 5.26.0
google-native       0.23.0
google-native       0.14.0
google-native       0.14.0
google-native       0.14.0
kubernetes          3.20.2
nodejs              unknown
rugal/pulumi-istio  1.0.6
Host     
OS       darwin
Version  12.4
Arch     x86_64
This project is written in nodejs: executable='/usr/local/bin/node' version='v14.16.1'




Dependencies:
NAME                              VERSION
@pulumi/kubernetesx               0.1.6
@pulumi/pulumi                    3.38.0
@types/node                       12.20.55
eslint                            6.8.0
@pulumi/gcp                       6.34.0
@typescript-eslint/eslint-plugin  2.34.0
@typescript-eslint/parser         2.34.0
@pulumi/google-native             0.23.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by ravikumarrao** [comment]
👍

**Comment by t0yv0** [comment]
Thank you for the bug report! It looks like protected flag is indeed not properly integrated with previews.

It's great that your issue provides a good workaround. Note there are also commands like 'pulumi state unprotect <urn>' to remove protect bits from Pulumi state without running a full update or refresh.

**Comment by jcalderin** [comment]
I just hit this issue. Im removing the `default` provider and therefore all my resources want to be replaced. Im trying to figure out how many resources will need a change but Im hitting the error of the preview stopping until I run `pulumi state unprotect` for each of my protected resources (they are buckets, and there are several of them).
