### ISSUE TITLE
`pulumi policy publish` should only bundle up the needed files

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#10488]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Currently `pulumi policy publish` grabs everything in the folder except what's defined in the gitignore. We would like it to only tar up what it needs as there may be extraneous files in that directory. 
### Affected area/feature

Policies As Code

**Comment by ringods** [comment]
One thing which became clear by analysing the code is that we only read the `.gitignore` file from the current working folder. The customer has this in a monorepo, so the `.gitignore` file is located in a (grand)parent folder. 

We should take this into account and read all the `.gitignore` files, starting at the current folder all the way to the root of the repo, which is where the `.git` metadata folder is located.

**Comment by Frassle** [comment]
> We should take this into account and read all the .gitignore files, starting at the current folder all the way to the root of the repo, which is where the .git metadata folder is located.

This sounds reasonable. 

> We would like it to only tar up what it needs as there may be extraneous files in that directory.

I'm not sure how we could do this? I don't think we can tell what files are or are not used by the policy code, someone could have a .txt file that they read as part of policy startup and there's no way for us to know that's used until the code runs.

We could add a new ignore file, or a setting in the project file (PulumiPolicy.yaml), but I think this is going to have to be explicit from the user.

**Comment by justinvp** [comment]
It looks like this was fixed by https://github.com/pulumi/pulumi/pull/10493
