### ISSUE TITLE
Doc Generation - Name Collision occurs when Name of the Module Collides with the Name of a Function or Resource

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#10495]
Output is case sensitive (eg- testModule and TestModule) however this poses a problem for case insensitive file systems.

<img width="292" alt="image (6)" src="https://user-images.githubusercontent.com/25461821/186720501-9f4a6234-4560-495e-9973-874857e34d7f.png">

The consequence of this issue is git continuously thinks there are dirty files on the file system.

**Comment by dixler** [comment]
from my understanding, this is probably a MacOS specific bug, but shouldn't impact our build processes that run on linux runners(with presumably case sensitive filesystems)?

**Comment by phillipedwards** [comment]
I'd tend to agree and while that may not impact linux runners, it does pose problems for OSX users which run docgen on their machines (smoke tests) prior to committing source, for example.

**Comment by dixler** [comment]
We can consider adding a flag `PULUMI_DOCSGEN_CASE_INSENSITIVE_FS` so that we escape capital letters.

**Comment by dixler** [comment]
> That's grim. Why can't we just start prefixing with "module_"/"resource_"/"invoke_" etc? That would solve the name clash issue without needing a feature flag.

Won't this affect the URLs on the docs site?
