### ISSUE TITLE
Rename product to Pulumy

### ISSUE THREAD

**Issue by yjaaidi** [pulumi/pulumi#10505]
## Hello!
Typing `Pulumy` instead of `Pulumi` seems to be a common typo.
What about renaming the product into `Pulumy` and see if `Pulumi` typo is as common. In this case we can revert back to `Pulumi`.

🤪

**Comment by dixler** [comment]
We could also rename pulumi to Terraform 2: electric boogaloo 🤪

Lots of opportunities here

**Comment by dixler** [comment]
after much back and forth with the team and consideration of some alt suggestions, we're probably not going to change the name any time soon. sorry about that 🤪
