### ISSUE TITLE
`pulumi console` no longer opens to the current stack

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#10508]
### What happened?

From Pulumi CLI docs, `pulumi console` is described as follows:

https://www.pulumi.com/docs/reference/cli/pulumi_console/ 
> Opens the current stack in the Pulumi Console

however `pulumi console` now opens to my personal app.pulumi.com org regardless of if a stack is selected or not.

### Steps to reproduce

1. from a directory containing a valid pulumi program, with a selected stack.
2. `pulumi console`
3. see landing page in Pulumi SaaS Service.

### Expected Behavior

I should be redirected to the specific stack eg- https://app.pulumi.com/phillipedwards/my-project/dev

### Actual Behavior

I am redirected to my personal org eg- https://app.pulumi.com/phillipedwards

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
can repro I think it's around here

https://github.com/pulumi/pulumi/blob/6b496b0d185afafbb520a369fa0ebd84c0bcde26/pkg/cmd/pulumi/console.go#L76-L82

**Comment by dixler** [comment]
can repro. taking a look.
