### ISSUE TITLE
Resource option equivalent of `pulumi state delete`

### ISSUE THREAD

**Issue by filip-taxamo** [pulumi/pulumi#10520]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

[pulumi state delete](https://www.pulumi.com/docs/reference/cli/pulumi_state_delete) is awkward to use in a CI/CD setup. It would be nice to say something like:

```diff
+ # TODO: remove after pulumi up
  bucket = aws.s3.Bucket("bucket",
      acl="private",
      tags={
          "Environment": "Dev",
          "Name": "My bucket",
      },
+    opts=pulumi.ResourceOptions(delete=True),
  )
```

and then remove the whole snippet in a subequent PR resulting in the bucket gone from both the Pulumi state and the Pulumi code.

**Comment by Frassle** [comment]
Have you seen [RetainOnDelete](https://www.pulumi.com/docs/intro/concepts/resources/options/retainondelete/)? I think that will do what your asking for.

**Comment by filip-taxamo** [comment]
> Have you seen [RetainOnDelete](https://www.pulumi.com/docs/intro/concepts/resources/options/retainondelete/)? I think that will do what your asking for.

Thanks, I wonder how I missed this, apologies for the noise!

**Comment by filip-taxamo** [comment]
@Frassle actually, this is not an exact equivalent of `pulumi state delete`, as it will fail if the provider for the resource can't be reached (if it's endpoint is not serving anymore for example). But I guess it can't be handled with a resource option, because we can't instantiate the resource at all. 
Do you have any ideas for deleting resources from unreachable providers via code?

**Comment by Frassle** [comment]
> as it will fail if the provider for the resource can't be reached (if it's endpoint is not serving anymore for example)

It should not. RetainOnDelete tells the engine to just do a state delete and does not try to contact the provider to do the delete at all.

**Comment by filip-taxamo** [comment]
> RetainOnDelete tells the engine to just do a state delete and does not try to contact the provider to do the delete at all.

@Frassle hmm, but how can I do `pulumi up` to set RetainOnDelete to false on a resource if its provider is not available?

**Comment by Frassle** [comment]
> hmm, but how can I do pulumi up to set RetainOnDelete to false on a resource if its provider is not reachable?

If you do a no-op update I don't think the engine will try to contact the provider. It will try to diff, see no changes from state and so not call into update or anything. So unless Diff requires access to the provider (which it generally shouldn't) that should allow you to set RetainOnDelete.

**Comment by filip-taxamo** [comment]
> So unless Diff requires access to the provider (which it generally shouldn't) that should allow you to set RetainOnDelete.

Unless the provider is used to look up existing resources. Thanks for the clarifications!
