### ISSUE TITLE
Add ability to see resource creation times to outputs

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#10534]
Different cloud providers create resources with varying amounts of time, some take longer than others.

The default Pulumi output doesn't tell the user how long each resource took, only the total program time. Introducing information about how long a resource took to create would be helpful user feedback.

Personally I'd like to see this opt-in information, rather than the default.

**Comment by dixler** [comment]
I'd like if we could record this data to PULUMI_HOME to try to provide users with estimates.

**Comment by t0yv0** [comment]
Perhaps this is trivial, but I'd love to see a mock-up of the terminal UI so that UX can be iterated on quickly before we start putting the code in. I believe we had some TF UI example somewhere for comparison, that'd be super valuable to have linked here.

**Comment by denniswebb** [comment]
The TF UI is actually really good at this. It adds a line every 10 seconds for each resource it is waiting on and an elapsed time. Then once completed it shows **Completed** with the total elapsed time. If this only works with `--non-interactive` that's fine.

**Comment by dixler** [comment]
I have a prototype if anyone would like to weigh in.

[![asciicast](https://asciinema.org/a/vySOjFlnAIMlJ8RTdPZYjhFDB.svg)](https://asciinema.org/a/vySOjFlnAIMlJ8RTdPZYjhFDB)
