### ISSUE TITLE
Local file resource

### ISSUE THREAD

**Issue by ztmr** [pulumi/pulumi#10532]
I'm porting a Terraform project to Pulumi, that is creating resources on demand and using `local_file` (along with TF templating) to generate a set of files containing some information about the resources created by the stack -- things like deployment diagrams containing IP addresses, Ansible inventories, etc.

I don't see any alternative to `local_file` resource in Pulumi and the Asset resource seems to be read-only. I've tried creating a custom code that would wait for all the dependent outputs (inputs) to be ready and write the file later, but that does not seem to work.
It looks like it might be possible to either use dynamic provider, which is not available for all the languages supported by Pulumi, or by smuggling all required values via the usual output somehow.

The main idea is to have a Pulumi Automation API app, a single binary written in Go, that would spin up an instance of stack on demand, generating these files and possibly running some other commands on these files: rendering and publishing them somewhere, running Ansible, etc.

I think I've seen someone using `hashicorp/local` from Pulumi to do this, but cannot find it anymore.

Is there any good way of doing what I need?

**Comment by Zaid-Ajaj** [comment]
Hi there @ztmr, from what I understand you want to create files based on resources, am I correct? The thing is with Pulumi is that you can use the language OS APIs to create the files you want and then read them into the stack resources as Assets. 

> I've tried creating a custom code that would wait for all the dependent outputs (inputs) to be ready and write the file later, but that does not seem to work.

Can you please elaborate on this with a piece of code? 

Usually this is achieved with a call to `.Apply` i.e.
```
resource.SomeProperty.Apply(func(property) { 
     // create files here based on values from the stack
})
```

**Comment by ztmr** [comment]
@Zaid-Ajaj yes, this is exactly what I am trying, but the apply gives empty string, so only the static pieces get generated. I was thinking perhaps I need to sync the order of how things depend on each other, etc. but whatever I tried is not working.
Is there any way to wait for _all_ resources? Like post-up-hook or something in that fashion?

Let me see if I can come up with a minimal piece of code to reproduce this.

**Comment by ztmr** [comment]
@Zaid-Ajaj that definitely looks handy! I will use this for running the external commands, but generating the local files looks painful using this plugin alone.

I've done a lot of wrestling with apply/all, but it was extremely painful. I'd like to think that if I do apply on a top level custom resource, that depends on its nested resources, all the child resources would be resolved. Parent/dependsOn does not seem to help here much :-(
I've even ended up in situation, where writing the result to file was OK, but assigning it to exported outputs of the entire stack was empty or truncated.

We can close this ticket...
