### ISSUE TITLE
Question: Referencing Stack Outputs from another Project

### ISSUE THREAD

**Issue by ryanpodonnell1** [pulumi/pulumi#10546]
Hello 👋 Looking at adopting pulumi for IaC 

Question:
Is there a way to reference stack outputs from another project using an S3 Backend?

What I am thinking:

We separate projects by s3 prefix when using s3 login backend

```sh
pulumi login s3://<bucketname>/<teamname>/<github_repo>/<project>
```

each stack under that project would be an instantiation of the project so say if we deploy to multiple regions <stack-us-east-1, stack-us-west-2> etc.

Looking at the GO reference [here](https://www.pulumi.com/docs/intro/concepts/stack/) its not clear to me how I would say traverse an s3 bucket key to reference a stack somewhere else

```go
other, err := pulumi.NewStackReference(ctx, "acmecorp/infra/other", nil)
if err != nil {
    return err
}
otherOutput := other.GetOutput(pulumi.String("x"))
```

thinking something like would be useful

```go
other, err := pulumi.NewStackReference(ctx, "s3://<bucketname>/<teamname>/<github_repo>/<some_other_project>/stackName", nil)
if err != nil {
    return err
}
otherOutput := other.GetOutput(pulumi.String("x"))
```

**Comment by Zaid-Ajaj** [comment]
Hi @ryanpodonnell1 I believe your use case is a duplicate of https://github.com/pulumi/pulumi/issues/2814, do you think that is what you want to achieve? if so, feel free to close this as duplicate

**Comment by ryanpodonnell1** [comment]
yes I suppose this might be solved once proper project namespacing is implemented for s3. Closing as dup
