### ISSUE TITLE
Engine (or core providers) should take into account 'stable' bit, and appropriately preserve values during preview

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#1055]
From conversation between @pgavlin @lukehoban and @cyrusnajmabadi.  Right now, understanding and checking of the 'stable' bit for properties is pushed into the language provider.  This is actually unnecessary and hard to use properly.  

During preview, the semantics we want between the engine and the provider are as following:

1. if a resource is unchanged, the engine should return all output properties with their actual unchanged values.
2. if a resource is changes and would need an 'update', then the engine should return original values for all "stable" properties, but undefined/computed for all non-stable properties.
3. If a resource is 'replaced' i'm not sure what is expected.  @lukehoban/@pgavlin to weigh in.

By doing this, all knowledge of stability is removed from the language provider.  All it has to be told is what the current values are (or if they're unknown because we'd actually have to run the update to figure them out).

**Comment by pgavlin** [comment]
@CyrusNajmabadi I thought we did this?

**Comment by lukehoban** [comment]
Looking at the code, this does appear to have been done - we no longer rely on stable in the language runtime - we rely on the engine to decide whether the value is known or not.  

@CyrusNajmabadi If there is anything left to track here - please reopen.
