### ISSUE TITLE
pulumi stack output mangles strings inside objects (chars are escaped)

### ISSUE THREAD

**Issue by awoimbee** [pulumi/pulumi#10561]
### What happened?

A co-worker had issues fetching a string from `pulumi stack output` because pulumi mangles the string.
Pulumi prints '>' as "\u003e".

### Steps to reproduce

```bash
docker run --rm -it --entrypoint bash pulumi/pulumi:3.38.0

mkdir test && cd test
pulumi login -l
export PULUMI_CONFIG_PASSPHRASE=toto
pulumi new typescript -n test -d yolo -s test
printf 'import * as pulumi from "@pulumi/pulumi";const s="><";const o={s: s}; console.log(o); export const es=s; export const eo=o\n' > index.ts
pulumi up --yes && pulumi stack output
```

### Expected Behavior

```
Current stack outputs (2):
    OUTPUT  VALUE
    eo      {"s":"><"}
    es      ><
```

### Actual Behavior

```
Current stack outputs (2):
    OUTPUT  VALUE
    eo      {"s":"\u003e\u003c"}
    es      ><
```
Note: this doesn't seem to be a TypeScript issue as the `console.log` prints `{ s: '><' }`.

### Output of `pulumi about`

I'm using the container, but anyways:
```
root@e170252144d4:/test# pulumi about
CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       debian
Version  11.4
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v16.17.0'

Current Stack: test

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:test::test::pulumi:pulumi:Stack::test-test


Found no pending operations associated with test

Backend
Name           e170252144d4
URL            file://~
User           root
Organizations

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.38.0
@types/node     14.18.26

Pulumi locates its logs in /tmp by default
```

### Additional context

This issue is circumvented by  using `pulumi stack output -j` (json output). The output becomes:
```json
{
  "eo": {
    "s": "><"
  },
  "es": "><"
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Related to https://github.com/pulumi/pulumi/issues/10439. See the comments on that issue about Go's default behavior for html escaping.
