### ISSUE TITLE
make pulumi version check an `info` message rather than a `warning`

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#10578]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
The pulumi version message uses a `warning` rather than an `info` level which I think degrades the significance of a `warning` message and its yellow coloring.

current behavior:
```
warning: A new version of Pulumi is available. To upgrade from version '3.35.3' to '3.39.0', run 
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

desired behavior:
```
info: A new version of Pulumi is available. To upgrade from version '3.35.3' to '3.39.0', run 
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

**Comment by gitsan13** [comment]
Hi I would like to try and implement this feature. Since I am a beginner in this, can you please guide me through the process?

**Comment by RobbieMcKinstry** [comment]
@dixler I think "warning" is the correct message here. Upgrading to a new version could improve security, keep users from reporting old errors, etc. We want the wheel to be as squeaky as possible to ensure our users are on `latest`. :)

**Comment by dixler** [comment]
Hi @gitsan13 thanks for the interest on this issue. I think there's more discussion to be had on the version check message and better conveying our intent when suggesting upgrading so it doesn't seem this enhancement is ready for work yet.

**Comment by ravikumarrao** [comment]
@RobbieMcKinstry pushing an optional patch upgrade info to `stderr` removed the possibility of me failing the pipeline because of actual pulumi errors. Can't always be on the latest version in the middle of dev cycles - because you create regressions too :) 

Maybe we should have permitted versions (semver guidelines) where it gets pushed to `stdout` so it gives us time to verify the new build and upgrade pulumi in our production deployment pipelines.

**Comment by RobbieMcKinstry** [comment]
@ravikumarrao That's a compelling argument in favor of marking the message as `info`. I know @dixler was looking into stderr hygiene, which could be related. You're right; another way to do this would be to write the warning to stdout. But I wonder if the hygiene guidelines have something to say about that.

**Comment by dixler** [comment]
@ravikumarrao you can set the envvar `PULUMI_SKIP_UPDATE_CHECK` to disable the version check.

**Comment by ravikumarrao** [comment]
How would you feel about including this environment variable option in the version check message?

**Comment by dixler** [comment]
@ravikumarrao I've opened https://github.com/pulumi/pulumi/issues/10986 to aggregate feedback. you can :+1:  it.

I imagine that this would be helpful, but it would contradict the point by @RobbieMcKinstry

> @dixler I think "warning" is the correct message here. Upgrading to a new version could improve security, keep users from reporting old errors, etc. We want the wheel to be as squeaky as possible to ensure our users are on `latest`. :)

**Comment by ravikumarrao** [comment]
Having a Squeaky clean air filter isn't always an option when you're driving a car. It's only done during a service effort :)

**Comment by dixler** [comment]
The `info` level just removes the `warning:` so it'll just look like

```
A new version of Pulumi is available. To upgrade from version '3.57.2-dev.0' to '3.57.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

**Comment by dixler** [comment]
We’ve decided to not make any changes to how the upgrade message is emitted currently for reasons listed above, but are still considering mentioning `PULUMI_SKIP_UPDATE_CHECK` in the message, which is tracked by
- https://github.com/pulumi/pulumi/issues/10986
