### ISSUE TITLE
Erroneous PRs to add alpha/beta versions of Pulumi to Homebrew.

### ISSUE THREAD

**Issue by issyl0** [pulumi/pulumi#10612]
### What happened?

Hello. I'm a Homebrew project maintainer, and I noticed that `pulumi-bot` raised a PR for an alpha version of the Pulumi software: https://github.com/Homebrew/homebrew-core/pull/109465. Since the `pulumi-bot` is an automation, there was no human to @-mention on the original PR, hence this issue.

Pre-releases of software are [against our guidelines](https://github.com/Homebrew/brew/blob/6096bc6d71bfb42f285a12414d3aee7fcee1ed75/Library/Homebrew/utils/shared_audits.rb#L35-L45) unless there's a specific, communicated reason for the software to ship a pre-release or otherwise allow it to build for testing purposes.

Previously `pulumi-bot` and your release scripts [have been good at](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+author%3Apulumi-bot+is%3Aclosed) correctly only raising PRs for stable versions, so I was surprised to see this recent behaviour. It has only happened once so far, so it's not a massive problem, but I thought I'd report it before we end up fighting with the bot's schedule of non-stable releases. 😄

Please could you make your release scripts not raise Homebrew bump PRs on alpha or beta releases? Thank you so much! 🙇🏻

### Steps to reproduce

https://github.com/Homebrew/homebrew-core/pull/109465.

Your "on release" Actions appear to have been trying to raise PRs for `alpha` and `beta` releases multiple times over in recent days: https://github.com/pulumi/pulumi/actions?query=workflow%3Ahomebrew+is%3Afailure. Thankfully these were blocked by Homebrew's "bump formula" duplicate PR detection.

### Expected Behavior

For the `pulumi-bot` not to raise PRs on Homebrew/homebrew-core for pre-releases of the Pulumi software, since [pre-releases aren't allowed](https://github.com/Homebrew/homebrew-core/pull/109465/files#annotation_4489054227) in `Homebrew/homebrew-core`.

### Actual Behavior

A PR for a pre-release was raised ([and more were attempted](https://github.com/pulumi/pulumi/actions?query=workflow%3Ahomebrew+is%3Afailure)), causing maintainers to have less time to spend on the many other stable packages for review. 😞

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Hi @issyl0, apologies for the disruption. We are indeed looking at enabling consumption of prerelease builds for Pulumi & associated software. We'll ensure we don't push any prerelease versions to you for now (see #10627).

I found a recent PR adding a software to the allow list (https://github.com/Homebrew/brew/pull/10053) though I didn't see discussion of the rules. What are the reasons permitted for prerelease exceptions, and how can work with Homewbrew to ensure we are able to publish prereleases causing additional work for you and others?

**Comment by issyl0** [comment]
Thanks @AaronFriel, I appreciate it!

The prerelease allowlist is [currently quite short](https://github.com/Homebrew/homebrew-core/blob/master/audit_exceptions/github_prerelease_allowlist.json) and, based on [the history](https://github.com/Homebrew/homebrew-core/commits/master/audit_exceptions/github_prerelease_allowlist.json), the commits have attached PRs with reasons like "this software only ships pre-releases but is otherwise notable enough for inclusion in Homebrew, so let's give it a go", and the idea is that eventually that list is shorter. That reasoning wouldn't apply for Pulumi since you've got such a good prior history of shipping stable releases to all users.

**Comment by AaronFriel** [comment]
Thanks for that background @issyl0. I don't want to take your time on questions that might be answered already in a FAQ or set of guidelines I haven't found yet, so please point me in that direction if it helps.

Is there precedent or a recommended path for say, a "nightly channel" or something like that for homebrew? If there are any examples of the right way, even if not part of homebrew/core, to do this, we'd benefit from following established practices.

**Comment by issyl0** [comment]
> Is there precedent or a recommended path for say, a "nightly channel" or something like that for homebrew? If there are any examples of the right way, even if not part of homebrew/core, to do this, we'd benefit from following established practices.

Sorry for the delay here, I was on vacation. For this, you'll want a [tap](https://docs.brew.sh/Taps). The docs on [creating and maintaining a tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) should explain everything.

Assuming you want it in `pulumi/homebrew-dev` with a name `pulumi`, Pulumi staff who want to use beta versions will install it with `brew install pulumi/dev/pulumi` (since I presume the formula name will be the same as one in homebrew-core). You'll obviously have to have a release script for non-stable versions to that specific tap, but that shouldn't be too hard to add.

This way, the Pulumi that Homebrew/homebrew-core ships to users will be stable, yet employees will have the option of using the edge for bug reports/fixes.

**Comment by AaronFriel** [comment]
I'm closing this for our bug tracking, not to foreclose any more discussion. Thank you so much! :)
