### ISSUE TITLE
We are dropping (many?) API docs due to parsing logic

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#10614]
I was curious why our [AWS VPC docs](https://www.pulumi.com/registry/packages/aws/api-docs/ec2/vpc/) are missing many examples. I assumed that it was because `tf2pulumi` wasn't successfully converting the HCL. To my (pleasant) surprise, that is not true! For example, observe that the generated `schema.json` and SDK comments have them!

https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/ec2/vpc.ts#L10-L63

The root cause for why these go missing seems to be the parsing logic here: https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/examples.go#L46.

A few thoughts

* Are we being too clever?  Why not just parse out every code block we find?

* Can we improve the heuristic by detecting `*ast.Text` and `*ast.Paragraph` segments, and use that?

* More generally, some of those textual elements also add value, so not clear to me why we wouldn't simply preserve the _entire example block_ as it exists, text elements included?

On that last point, we could do a lot worse than just generating the markdown as it exists in the doc comments already:

```markdown
* ## Example Usage
 *
 * Basic usage:
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const main = new aws.ec2.Vpc("main", {
 *     cidrBlock: "10.0.0.0/16",
 * });
 * ```
 *
 * Basic usage with tags:
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const main = new aws.ec2.Vpc("main", {
 *     cidrBlock: "10.0.0.0/16",
 *     instanceTenancy: "default",
 *     tags: {
 *         Name: "main",
 *     },
 * });
 * ```
 *
 * VPC with CIDR from AWS IPAM:
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as aws from "@pulumi/aws";
 *
 * const current = aws.getRegion({});
 * const testVpcIpam = new aws.ec2.VpcIpam("testVpcIpam", {operatingRegions: [{
 *     regionName: current.then(current => current.name),
 * }]});
 * const testVpcIpamPool = new aws.ec2.VpcIpamPool("testVpcIpamPool", {
 *     addressFamily: "ipv4",
 *     ipamScopeId: testVpcIpam.privateDefaultScopeId,
 *     locale: current.then(current => current.name),
 * });
 * const testVpcIpamPoolCidr = new aws.ec2.VpcIpamPoolCidr("testVpcIpamPoolCidr", {
 *     ipamPoolId: testVpcIpamPool.id,
 *     cidr: "172.2.0.0/16",
 * });
 * const testVpc = new aws.ec2.Vpc("testVpc", {
 *     ipv4IpamPoolId: testVpcIpamPool.id,
 *     ipv4NetmaskLength: 28,
 * }, {
 *     dependsOn: [testVpcIpamPoolCidr],
 * });
 * ```
 ```

I don't know the numbers but after spot checking, I would guess we are dropping multiple 100s (maybe >1,000?) examples due to this, including some very important ones like AWS VPCs.

**Comment by RobbieMcKinstry** [comment]
I believe @jkodroff was working on this before he changed teams. Was that work related to this issue, Josh?

**Comment by jkodroff** [comment]
@RobbieMcKinstry No - if it's in the schema and not in the generated docs, it's not in the bridge, which is where I was focusing my efforts for examples conversion.
