### ISSUE TITLE
CLI believes it should upgrade to -alpha- revision

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#10616]
### What happened?

My current Pulumi CLI believe it should be upgraded to an alpha/pre-release version.

```
warning: A new version of Pulumi is available. To upgrade from version '3.38.0' to '3.40.0-alpha.1662150830', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### Steps to reproduce

Install a recent and stable CLI and let it check for the latest version. Then the message above should appear.

This is related to this content https://www.pulumi.com/latest-version

### Expected Behavior

The CLI should upgrade to stable versions only.

### Actual Behavior

The CLI wants me to upgrade to an alpha release.

### Output of `pulumi about`

```
CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Host     
OS       debian
Version  11.4
Arch     x86_64
...
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by praneetloke** [comment]
FYI, I don't see the upgrade notice anymore.

**Comment by aureq** [comment]
@praneetloke It was manually disabled by Paul via https://github.com/pulumi/docs/pull/7983 for now.

**Comment by mikhailshilkov** [comment]
I believe this was caused by https://github.com/pulumi/pulumi/pull/10580 which is now called. We'll be more careful next time.
