### ISSUE TITLE
Support a way to run resource creation after all user code has run

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1062]
With `HttpEndpoint`, we have had to include a `publish` API, because we can't create the new `Deployment` resource until we are sure that all user code has run to create potential routes on the endpoint.

Similarly, for the work on supporting `Bucket`, it turns out that AWS APIs do not allow us to attach multiple `EventNotifications`, we must create one resource with all of the listeners for that bucket.  Which again means we must wait to do this until we know all of the notifications.

In both cases, it would have been much better if we did not need the user to tell us when they are "done".  

Instead, we could in principle allow the library author to indicate that a callback should be called after all user code runs to create a final resource.  This will only work in cases where nothing can/should depend on the final resource creation - but at least in these two cases that seems reasonable and expected.

**Comment by joeduffy** [comment]
Looks like we've got a workaround, and I know we've been using it for a few months now, so closing out. Please reopen if that wasn't adequate.
