### ISSUE TITLE
Support outputs and dependencies in Python runtime

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1063]
The initial Python implementation was optimized for simplicity and getting something that works.  As a result, we implemented everything with synchronous blocking, and none of the same outputs and dependency tracking that we do in the JavaScript runtime.  I believe we can mostly copy what we did in JavaScript, but we will need to fix this, particularly in order to support parallelism.

**Comment by swgillespie** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/2111.
