### ISSUE TITLE
Add support for Zscaler ZPA

### ISSUE THREAD

**Issue by XSchelin** [pulumi/pulumi#10630]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Feature details

Please add support for Zscaler's [ZPA product](https://help.zscaler.com/zpa/about-zpa-api).

Terraform supports it [here](https://registry.terraform.io/providers/zscaler/zpa/); that may be of use.

### Affected area/feature

[Pulumi registry of supported integrations](https://www.pulumi.com/registry/)

**Comment by mikhailshilkov** [comment]
Done in https://github.com/pulumi/registry/pull/4231
