### ISSUE TITLE
When using S3 backend pulumi is looking for backups in the wrong location

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi#10642]
### What happened?

We encountered some error during the state snapshot phase:

```
[diff: ~nodeLabels,resourceName,tags]; error: post-step event returned an error: failed to save snapshot: .pulumi/stacks/prod_azure_northeurope_infra.json: snapshot integrity failure; it was already written, but is invalid (backup available at .pulumi/stacks/prod_azure_northeurope_infra.json.bak): duplicate resource urn:pulumi:prod_azure_northeurope_infra::prj::azure-native:containerservice/v20210501:AgentPool::control1 (not marked for deletion)
    pulumi:pulumi:Stack prod_azure_northeurope_infra running error: update failed
    pulumi:pulumi:Stack prod_azure_northeurope_infra **failed** 1 error
```

The location `.pulumi/stacks/prod_azure_northeurope_infra.json.bak` doesn't exist, all backups are in `.pulumi/backups/prod_azure_northeurope_infra/*.json`

Not sure why this is happening

This caused pulumi to drop the entire state and we ended up creating extra resources and leaking the resources from the failed attempt

### Steps to reproduce

Cause some error during updates to backend

### Expected Behavior

Use the backups folder as intended

### Actual Behavior

Looking for the wrong location

### Output of `pulumi about`

```
CLI
Version      3.26.1
Go Version   go1.17.7
Go Compiler  gc

Host
OS       debian
Version  11.4
Arch     x86_64

Backend
Name     provisioner-96f58db78-m5k7r
URL      s3://bucket-state
User     user
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Does this problem persist on 3.39.3?

**Comment by yarinm** [comment]
@iwahbe I didn't try, is there some change in that version that should help with that?

**Comment by iwahbe** [comment]
There has been some work in the file state backend, but I don't have a specific change in mind. We don't generally back port fixes, so any solution will involve upgrading to 3.40.0 (assuming a fix goes out in the next release). I just wanted conformation that the problem persists on the newest CLI release. It's a minor version bump, so upgrading should be seamless (if not, please let us know).
