### ISSUE TITLE
`pulumi convert -f` doesn't work as expected

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi#10658]
The docs and inline help for `pulumi convert` suggest you can pass a filename with `-f`:

```
The YAML program to convert will default to the manifest in the current working directory.
You may also specify '-f' for the file path or '-d' for the directory path containing the manifests.
```

However when I use this, I get:

```
$ pulumi convert -f "Pulumi.base.yaml" --out "csharp" --language "csharp"

Error: unknown shorthand flag: 'f' in -f
```

Am I using it incorrectly? Or should our docs be updated?

**Comment by iwahbe** [comment]
Hey @cnunciato thanks for pointing this out. We'll get this cleaned up shortly. My first action is to fix the text so it matches how the flags actually work. If you need to use the `-f` or `-d` options, can you file a separate issue?

**Comment by cnunciato** [comment]
@iwahbe Absolutely, will do.
