### ISSUE TITLE
Support assets in Python

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1065]
We don't yet support assets in Python.  Particularly in the absence of [closure serialization](https://github.com/pulumi/pulumi/issues/1064), and even with it, we will need this in order to write even basic programs that use things like lambdas, S3 objects, and so on.

**Comment by swgillespie** [comment]
https://github.com/pulumi/pulumi/pull/1587 fixes this in pulumi/pulumi, we also need
https://github.com/pulumi/pulumi-terraform/issues/190 in order for assets to be passed to providers.
