### ISSUE TITLE
Consider adding a --save-final-state-only flag to speed up large stacks

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#10668]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Consider adding a --save-final-state-only flag to trade safety for speed. This flag would be relevant for situations where:

- the state is very large (many resources, large resources)

- Pulumi CLI crashes or disconnects that might lead to inconsistencies between the state of the cloud and the state checkpoint internally tracked by Pulumi in the statefile (or service) are not a serious concern - either unlikely or easy to recover from

The flag would ask Pulumi to only write the state at the end of a deployment (pulumi up, etc). The default behavior for Pulumi is to write the state immediately after it is making changes. A stack update that creates N resources is currently generating O(N) state writes, and it can slow down large deployments. 

Currently `pulumi up` does this (example using the httpstate backend):

```
POST /api/stacks/t0yv0/ts-many-resources/test1/update -->
       updateResponse.UpdateID=d70490f6-0c8c-43e0-b67a-dfc47af25e51/
PATCH /api/stacks/t0yv0/ts-many-resources/test1/update/d70490f6-0c8c-43e0-b67a-dfc47af25e51/checkpoint
PATCH /api/stacks/t0yv0/ts-many-resources/test1/update/d70490f6-0c8c-43e0-b67a-dfc47af25e51/checkpoint
...
PATCH /api/stacks/t0yv0/ts-many-resources/test1/update/d70490f6-0c8c-43e0-b67a-dfc47af25e51/checkpoint
POST /api/stacks/t0yv0/ts-many-resources/test1/update/d70490f6-0c8c-43e0-b67a-dfc47af25e51/complete
```

The new behavior of `pulumi up --save-final-state-only` would be using only one PATCH at the end:

```
POST /api/stacks/t0yv0/ts-many-resources/test1/update -->
       updateResponse.UpdateID=d70490f6-0c8c-43e0-b67a-dfc47af25e51/
PATCH /api/stacks/t0yv0/ts-many-resources/test1/update/d70490f6-0c8c-43e0-b67a-dfc47af25e51/checkpoint
POST /api/stacks/t0yv0/ts-many-resources/test1/update/d70490f6-0c8c-43e0-b67a-dfc47af25e51/complete
```

The treadeoff is that in case of a catastrophic failure of the `pulumi` process the intermediate state changes it has performed will not be written to the state backend.

The flag would universally apply to the httpstate and filestate backends.

## Alternatives and related tickets

- https://github.com/pulumi/pulumi/issues/3930 will improve the efficiency of httpstate backends and is currently being worked on
- https://github.com/pulumi/pulumi/issues/10068 asking for a similar fixup to the httpstate backend
- https://github.com/pulumi/pulumi/issues/6667 lists scenarios where state is not needed at all

## Naming possibilities

```
--save-final-state-only
--save-final-checkpoint-only
--skip-saving-intermediate-state
--skip-saving-intermediate-checkpoints
```

### Affected area/feature

area/backends

**Comment by jkodroff** [comment]
`--skip-interstitial-checkpoints`?

**Comment by dixler** [comment]
It's so much faster

**Comment by dixler** [comment]
@AaronFriel suggests using an environment variable rather than a CLI flag

I prefer env vars over CLI flags as it works in users' favor and engineering's favor.

users:
- users would have to modify all of their CI scripts to use this feature as a argument rather than have the desired behavior
- environment variables are easier to provide to CI systems and user shell profiles
- removing this flag would be a breaking change to users that use this flag.

engineering:
- we use `cobra` for argument parsing so environment variables are easier to retrieve from subsystems meaning that the diff will be smaller
- we can more easily deprecate this experimental behavior when patch support is done

an env var indicating a vague performance improvement would allow us to quietly remove the env var once our performance goals are reached since the users just want pulumi to be faster and we could hide the implementation details since it'd reduce our flexibility.

i.e. `PULUMI_EXPERIMENTAL_UNSAFE_OPTIMIZE_STACK_MANAGER=1`

**Comment by t0yv0** [comment]
The PR implements `PULUMI_EXPERIMENTAL_SNAPSHOT_MANAGER=1`. I admit the idea this should be env vars better than a flag, but to nitpick the naming one last time, I liked Josh's suggestions that sound more like what the flag is doing for the user rather than how its' implemented.

https://www.pulumi.com/docs/intro/concepts/state/#checkpoints seems to be the official docs that give some vocabulary to what Pulumi does here ("record a checkpoint").

Perhaps:

```
PULUMI_EXPERIMENTAL=1
PULUMI_RECORD_CHECKPOINTS=once 
# or
PULUMI_RECORD_CHECKPOINTS=final-only
```

This opens up adding some more options down the road.

```
PULUMI_RECORD_CHECKPOINTS=every:30s
PULUMI_RECORD_CHECKPOINTS=off # no state saving at all
```

**Comment by iwahbe** [comment]
I like the `skip` based naming options:
```
--skip-saving-intermediate-state
--skip-saving-intermediate-checkpoints
```

We should definitely gate these behind `PULUMI_EXPERIMENTAL`. We might want to add an `unsafe` to the beginning:
```
--unsafe-skip-saving-intermediate-state
--unsafe-skip-saving-intermediate-checkpoints
```

**Comment by dixler** [comment]
Reopening since we would like to better name the environment variable.

**Comment by t0yv0** [comment]
This shipped as an env-var based flag:

```PULUMI_EXPERIMENTAL=true PULUMI_SKIP_CHECKPOINTS=true```.

Looking forward to feedback.
