### ISSUE TITLE
pulumi convert doesn't respect language specific overrides for properties in schema for charp

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi#10671]
### What happened?

Running pulumi convert on a resource with properties with language specific overrides (I have really only tested this with C#)
 seems to not be honored.

e.g. with the following Pulumi.yaml contents (copy the contents to a Pulumi.yaml):
https://github.com/pulumi/pulumi-kubernetes/blob/f93f9b6c75303e3c600b2d1f5f09a78dd6ab9278/provider/pkg/gen/examples/upstream/yaml/deployment.yaml

results in the following:
```
pulumi convert --language csharp --out /tmp/example-dotnet
Installing dependencies...

MSBuild version 17.3.0+92e077650 for .NET
  Determining projects to restore...
  Restored /private/tmp/example-dotnet/yaml-example.csproj (in 872 ms).
/private/tmp/example-dotnet/Program.cs(47,37): error CS0117: 'ContainerPortArgs' does not contain a definition for 'ContainerPort' [/private/tmp/example-dotnet/yaml-example.csproj]

Build FAILED.

/private/tmp/example-dotnet/Program.cs(47,37): error CS0117: 'ContainerPortArgs' does not contain a definition for 'ContainerPort' [/private/tmp/example-dotnet/yaml-example.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.51
error: installing dependencies failed; rerun manually to try again, then run `pulumi up` to perform an initial deployment: `dotnet build` failed to install dependencies: exit status 1
```

In particular the containerport field has the following definition in the schema:
```
"kubernetes:core/v1:ContainerPort": {
            "description": "ContainerPort represents a network port in a single container.",
            "properties": {
                "containerPort": {
                    "type": "integer",
                    "description": "Number of port to expose on the pod's IP address. This must be a valid port number, 0 < x < 65536.",
                    "language": {
                        "csharp": {
                            "name": "ContainerPortValue"
                        }
                    }
                },
...
```

### Steps to reproduce

`pulumi convert --language csharp --out /tmp/example-dotnet` with contents from https://github.com/pulumi/pulumi-kubernetes/blob/f93f9b6c75303e3c600b2d1f5f09a78dd6ab9278/provider/pkg/gen/examples/upstream/yaml/deployment.yaml

### Expected Behavior

Successful conversion to csharp

### Actual Behavior

```
/private/tmp/example-dotnet/Program.cs(47,37): error CS0117: 'ContainerPortArgs' does not contain a definition for 'ContainerPort' [/private/tmp/example-dotnet/yaml-example.csproj]

Build FAILED.
```

### Output of `pulumi about`

```
CLI
Version      3.39.3
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  unknown
yaml        unknown

Host
OS       darwin
Version  11.6.8
Arch     x86_64

This project is written in yaml
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
I've been looking into this one, it looks like another PCL binder issue where only the top-level `Resource.Inputs` are annotated with their schema types but not their nested object items. First I need to get #10958 merged so I can use the utilities there for this fix
