### ISSUE TITLE
Cloudwatch rum appmonitor output for id pushes name not id for assets

### ISSUE THREAD

**Issue by interestinginteger123** [pulumi/pulumi#10690]
Cloudwatch rum appmonitor ouptut ID should contain the unique ID instead it contains the name of the asset.

running the aws cli:

aws rum get-app-monitor --name {APP-NAME}

Has the correct asset value for rum ID

**Comment by dixler** [comment]
Hi, thanks for the issue. Can we have a repro program that deploys the resources that exhibit the behavior that you describe? Thanks.
