### ISSUE TITLE
Moving pulumi resources from one project to another project or stack

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi#10695]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Migrate resources that are created in Pulumi to different stacks.  

Different Use Cases: 
  1. Breaking apart mono repo's into smaller projects/stacks. 
  1. Migrating/Aggregating similar resources such as all service principals into one stack.
  
Current Methods: 
 1.  pulumi stack export -> cherry pick the resources to move -> import the exported into existing the desired project -> delete state from the previous project by urns which are the cherry-picked urns -> refresh stack?
OR
 1. cherry-pick pulumi import resources to another stack(not sure if this works for K8S resources reliably) -> delete state from the previous project by urns -> refresh stack?

**Comment by Eric-Swiftly** [comment]
with a bit of json trickery on a pulumi stack export / import much of this can be done.  However if you are using the default secrets provider the key is tied to the stack so you can't just copy from stack A to stack B.  Also some objects like azuread.ApplicationPassword can't be imported so if stack A created it, you can't then just pulumi import it into stack B.

**Comment by dixler** [comment]
Is this related to
- https://github.com/pulumi/pulumi/issues/3389

**Comment by tusharshahrs** [comment]
Closed since this is a duplicate of [Support moving resources between projects](https://github.com/pulumi/pulumi/issues/3389)
