### ISSUE TITLE
Checksum file is missing in v3.39.4

### ISSUE THREAD

**Issue by suzuki-shunsuke** [pulumi/pulumi#10707]
Thank you for your great project.

I found checksum file is missing in v3.39.4.

https://github.com/pulumi/pulumi/releases/tag/v3.39.4

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/13323303/190083012-6415853e-53fe-47ba-8e41-df130b0916f2.png">

On the other hand, checksum files have been released in v3.39.3.

https://github.com/pulumi/pulumi/releases/tag/v3.39.3

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/13323303/190083183-888f12e5-8d3f-4077-a4c9-08a72cb10964.png">

[pulumi-3.39.3-checksums.txt](https://github.com/pulumi/pulumi/releases/download/v3.39.3/pulumi-3.39.3-checksums.txt)

Could you release the checksum file?

**Comment by AaronFriel** [comment]
Hey @suzuki-shunsuke, thanks for identifying this. We'll get that fixed for the 3.40.0 release.

Interesting project too, at https://aquaproj.github.io/! I'll check it out.
