### ISSUE TITLE
Panic in 3.39.1

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi#10706]
### What happened?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1fa11f8]
goroutine 251619 [running]:
github.com/pulumi/pulumi/sdk/v3/go/pulumi.mergeDependencies({0x0, 0x2, 0xc000500000?}, {0xc00400ee60, 0x2, 0x4bf4fc?})
/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.39.3/go/pulumi/types.go:212 +0x218
github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*OutputState).fulfillValue(0xc000052d90, {0x35fb5a0?, 0xc00500da70?, 0xc00562d6f8?}, 0x1, 0x0, {0xc00400ee60, 0x2, 0x2}, {0x0, ...})
/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.39.3/go/pulumi/types.go:198 +0x39e
github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*OutputState).ApplyTWithContext.func1()
/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.39.3/go/pulumi/types.go:518 +0x61b
created by github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*OutputState).ApplyTWithContext
/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.39.3/go/pulumi/types.go:495 +0x411
```

### Steps to reproduce

Not really sure 

### Expected Behavior

No panics

### Actual Behavior

Panic during stack refresh (I think)

### Output of `pulumi about`

```
CLI
Version      3.39.3
Go Version   go1.19.1
Go Compiler  gc

Host
OS       debian
Version  11.5
Arch     x86_64

Backend
Name           my-pod
URL            s3://bucket
User           pulumi
Organizations

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Thanks for filing this. Could you provide a repro case to better track down what's going wrong?

**Comment by Frassle** [comment]
> /go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.39.3/go/pulumi/types.go:212

That's line is `for _, d := range ours {` which even if `ours` is nil shouldn't trigger a nil-deref (nil slices simply return a zero length and enumerate nothing)

I suspect there were other goroutine stack traces that pointed to the actual issue but haven't been included in this report.

**Comment by yarinm** [comment]
This is actually the full stack I got from the logs and it didn't reproduce since then

**Comment by lukehoban** [comment]
Closing this out, as we don't seem to have a repro or a stack trace.  Please do open a new issue if this reoccurs.
