### ISSUE TITLE
I would like the ability to upgrade a provider for a stack without state surgery

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#10710]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Currently when you upgrade a provider you have to export the stack, change all the provider versions and import the stack. This is not ideal, and I would like to upgrade the provider without hacking the stack. It would be nice to be able to perform an upgrade of the provider and refresh the stack.

**Comment by t0yv0** [comment]
Thanks for reporting this @rshade - this sounds important. For those of us who are a bit less familiar with this part of the product, could you provide some repro steps that currently lead to the situation where Pulumi rejects upgrades and requires hacking the stack as you mention? That would be very helpful.

**Comment by rshade** [comment]
```
I0914 10:00:31.342174   31932 plugins.go:1626] GetPluginPath(resource, confluentcloud, 1.2.0): enabling new plugin behavior
I0914 10:00:31.342190   31932 plugins.go:1728] SelectCompatiblePlugin(..., confluentcloud): beginning
I0914 10:00:31.342202   31932 plugins.go:1761] SelectCompatiblePlugin(..., confluentcloud): skipping plugin confluentcloud-0.1.0: semver mismatch
I0914 10:00:31.342211   31932 plugins.go:1761] SelectCompatiblePlugin(..., confluentcloud): skipping plugin confluentcloud-1.0.0: semver mismatch
I0914 10:00:31.342218   31932 plugins.go:1757] SelectCompatiblePlugin(..., confluentcloud): best plugin confluentcloud-1.2.0: semver match
I0914 10:00:31.342225   31932 plugins.go:1761] SelectCompatiblePlugin(..., confluentcloud): skipping plugin confluentcloud-1.2.1: semver mismatch
I0914 10:00:31.342232   31932 plugins.go:1770] SelectCompatiblePlugin(..., confluentcloud): selecting plugin 'confluentcloud-1.2.0': best match 
I0914 10:00:31.342242   31932 plugins.go:1665] GetPluginPath(resource, confluentcloud, 1.2.0): found in cache at /Users/cjames/.pulumi/plugins/resource-confluentcloud-v1.2.0/pulumi-resource-confluentcloud
I0914 10:00:31.342262   31932 plugin.go:184] Launching plugin 'confluentcloud (resource)' from '/Users/cjames/.pulumi/plugins/resource-confluentcloud-v1.2.0/pulumi-resource-confluentcloud' with args: 127.0.0.1:64697
I0914 10:00:31.369202   31932 provider_plugin.go:1475] Provider[confluentcloud, 0xc000c89980].GetPluginInfo() executing
I0914 10:00:31.369632   31932 provider_plugin.go:495] Provider[confluentcloud, 0xc000c89980].Configure() executing (#vars=1)
I0914 10:00:31.369675   31932 rpc.go:74] Marshaling property for RPC[Provider[confluentcloud, 0xc000c89980].Configure().inputs]: version={1.2.0}
I0914 10:00:31.369698   31932 registry.go:162] loaded provider urn:pulumi:dev.common.us-east-1::confluent-cloud.ecom::pulumi:providers:confluentcloud::default_1_2_0::2313fe71-04b3-4e4c-af83-cebb250a2841
```

**Comment by rshade** [comment]
I want to be able to do the following workflow

1. have an existing project/stack
2. yarn/pip/poetry/etc upgrade my provider
3. pulumi up --providers-only | pulumi refresh --upgrade-providers

**Comment by t0yv0** [comment]
I've tried to reproduce the issue with a program in Go like this:

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws"
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		// ver := "5.11.0"
		// ver := "5.13.0"

		awsProvider, err := aws.NewProvider(ctx, "my-aws", nil)
		if err != nil {
			return err
		}

		bucket, err := s3.NewBucket(ctx, "my-bucket", nil, pulumi.Provider(awsProvider))
		if err != nil {
			return err
		}

		ctx.Export("bucketName", bucket.ID())
		return nil
	})
}

```

The test sequence is changing AWS ref in go.mod, running `go mod tidy`, and running `pulumi up`. It seems that flipping between 5.11.0 and 5.13.0 Pulumi is able to succeed and update my stack up and down.

I've also tried specifying version using pulumi.Version which also seems to work as expected:

```
awsProvider, err := aws.NewProvider(ctx, "my-aws", nil, pulumi.Version(ver))
```

Is there something I am missing that still necessitates `refresh` behavior here? Is perhaps the issue specific to confluentcloud provider, some specific versions, or maybe languages other than Go?

**Comment by t0yv0** [comment]
I've experimented some more here. It sounds full `pulumi up` and `pulumi refresh` work as expected. However if I understand correctly there is something in the user situation that a full `pulumi up` or `pulumi refresh` is not acceptable, perhaps because the program and the stack state have sufficiently out sync.

Current workarounds: 

- as provided by @rshade , stack export -> edit -> stack import

- scoped updates - requiring to know the URN of each provider resource seem to work
     `pulumi up --target urn:pulumi:dev::repro-10710::pulumi:providers:aws::my-aws`
     `pulumi refresh --target urn:pulumi:dev::repro-10710::pulumi:providers:aws::my-aws`

So perhaps we could consider adding a feature that's exactly like `--target` to scope the operations but instead of filtering by URN lists it would specify a filter that selects provider resources only.

**Comment by mikhailshilkov** [comment]
Is this the same request as https://github.com/pulumi/pulumi/issues/9878?

**Comment by Frassle** [comment]
> Is this the same request as https://github.com/pulumi/pulumi/issues/9878?

Yes
