### ISSUE TITLE
Pulumi fails to read Git information on detached HEAD

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1073]
If your current Git repo is in a detached HEAD state, Pulumi fails to update as it fails reading the Git metadata. (Which it gathers for the update.)

`error: gathering environment metadata: reading git repo (getting worktree status): object not found`

Rather than failing we should probably just issue a warning and carry on. The code to tweak is here:
https://github.com/pulumi/pulumi/blob/a23b10a9bf26df7bd737b9884b73e0fbc6558c03/cmd/util.go#L388

```
$ git status
HEAD detached at d4528d4
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Pulumi.yaml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        Pulumi.local-resource-changes.yaml

no changes added to commit (use "git add" and/or "git commit -a")
```

```
$ pulumi update -m "detached HEAD should work, right?"
error: gathering environment metadata: reading git repo (getting worktree status): object not found
```

**Comment by ellismg** [comment]
This appears to no longer be an issue, with `v0.14.3` of `pulumi`.  I validated that the commit is set even when HEAD is detached.
