### ISSUE TITLE
pulumi new project already exists error does not respect the default org

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#10748]
[internal slack convo](https://pulumi.slack.com/archives/C9SGX9QA1/p1663254061919969)

repro steps
- create a project in your individual account with name X
- set your default org to an org that does not have a project with the name X
- use pulumi new
- when it asks for a project name, set it to X
- receive an error saying that project already exists

**Comment by sean1588** [comment]
I ran into this issue recently as well where I intended to create a project in a different org that has the same project name as one in my personal.
