### ISSUE TITLE
Consider splitting deployment-time and run-time APIs apart

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1074]
Today, we frequently provide a single class with both methods designed for use at deployment time, and methods designed for use at runtime.  For example:

```typescript
export interface Topic<T> {
    publish: (item: T) => Promise<void>;
    subscribe(name: string, handler: (item: T) => Promise<void>): void;
}
```

In the above, the `subscribe` API is for use at deployment time, and the `publich` API is for use at runtime.  This is not at all clear from the API, and is not enforced in any deep way.  Calling `subscribe` at runtime will generally fail with a cryptic error, and calling `publish` at deployment time may or may not work depending on the execution environment - but the experience is not great in either case.

We have frequently discussed trying to split APIs like this into two parts - one which is only for deployment time, and another which is only for runtime - with a clear and consistent way to transition from one to the other.

The most promising proposal we have discussed so far looks like:

```typescript
export interface Topic<T> {
    subscribe(name: string, handler: (item: T) => Promise<void>): void;
    ops: TopicOperations<T>;
}

export interface TopicOperations<T> {
    publish(item: T): Promise<void>;
}
```

In this model, we would use `ops` as a conventional name for the property of a deployment time object which has a set of runtime operations available on it.

User code then looks like:

```typescript
let t = new Topic<string>();

t.subscribe("handler", (item) => { 
    console.log(item);
});

cloud.timer.daily("daily", () => {
    // NOTE: Uses `t.ops` instead of `t`
    t.ops.publish();
});
```

The above works because we serialize only the object referred to by `t.ops`, not all of `t` as a result of improvements to closure serialization in M11.  The user could also have stored `let topicOps = t.ops` before the callback and captured `topicOps`, which would also work as expected.

We could then mark Topic with a bit indicating that it should not be legal to closure capture it, which would eagerly prevent `t.subscribe` on the inside.

**Comment by joeduffy** [comment]
@CyrusNajmabadi @lukehoban Given our focus this sprint, it seems unlikely we're going to do anything on this one (and frankly I'm not itching to do anything here until we have more experience and feedback with the current model). Did you keep it in M16 intentionally?

**Comment by lukehoban** [comment]
We've landed in a reasonable place for existing libraries.  We may continue to explore other options as part of new libraries.
