### ISSUE TITLE
release tag `CHANGELOG.md` doesn't contain the `CHANGELOG.md` for that release

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#10752]
### What happened?

https://github.com/pulumi/pulumi/blob/v3.40.0/CHANGELOG.md doesn't contain `v3.40.0`

`master` is fine however. https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md

### Steps to reproduce

...

### Expected Behavior

...

### Actual Behavior

...

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
cc @AaronFriel

**Comment by AaronFriel** [comment]
Won't fix - when the user clicks "Publish Release" that tags the commit and there's no intervening step in which we could edit the CHANGELOG.md with the release notes. It will always be a follow-up PR that adds the release notes published here: https://github.com/pulumi/pulumi/releases
