### ISSUE TITLE
Docs for pulumi.InvokeOptions is missing for NodeJS

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi#10751]
The [node docs for pulumi.pulumi](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#InvokeOptions) do not include docs for `InvokeOptions`, but [the Python docs](https://www.pulumi.com/docs/reference/pkg/python/pulumi/) do.

**Comment by Frassle** [comment]
Looks like both pages have these docs now.
