### ISSUE TITLE
Improved UX for update cancellation, hibernate and timeout with managed stacks

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1077]
If I `ctrl-c` a deployment using the managed stacks model, then attempting to restart the update leads to:

```
$ pulumi update
Updating stack 'stress-tester-testing' in the Pulumi Cloud ☁️
error: calling API: [400] another update is currently in progress
```

We need to provide great CLI experience in these sorts of failure modes, and to make it easy to restart an update in one of these cases.

Scenarios:
1. Ctrl-c a deployment, then start again.
2. Close lid and come back later - should it fail or auto-renew and continue if possible?
3. Deployment in CI cancelled (same as (1) except can't rely on ctrl-c handler).

**Comment by chapmanjacobd** [comment]
If someone else has this issue this will usually get you into a good place but it is still slightly risky:

```sh
pulumi cancel
pulumi stack export | jq '.deployment.pending_operations = []' | pulumi stack import
pulumi up --refresh
```

It might be better to try pulumi destroy and start over.
