### ISSUE TITLE
Can't access AWS region from config (Python)

### ISSUE THREAD

**Issue by nc-kaos** [pulumi/pulumi#10812]
### What happened?

```
aws_config = pulumi.Config("aws")

region = aws_config.get("region")
print(region)
```

Returns None - even though config is set up. Happens for both stacks I have set up, prod and dev.

```
❯ pulumi config get aws:region
us-east-1
❯ pulumi stack select dev
❯ pulumi config get aws:region
us-west-2
```

### Steps to reproduce

As in "what happened".

### Expected Behavior

Configured AWS region to be returned and to be used in code.

### Actual Behavior

Value "None" is being returned.

### Output of `pulumi about`

CLI          
Version      3.40.1
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.14.0
python  unknown

Host     
OS       darwin
Version  12.6
Arch     arm64

This project is written in python: executable='/Users/kaos/Scripts/pulumi/kaos-network-general/venv/bin/python3' version='3.10.6
'

Current Stack: dev

TYPE                                     URN
pulumi:pulumi:Stack                      urn:pulumi:dev::kaos-network-general::pulumi:pulumi:Stack::kaos-network-general-dev
pulumi:providers:aws                     urn:pulumi:dev::kaos-network-general::pulumi:providers:aws::default_5_14_0
pulumi:providers:aws                     urn:pulumi:dev::kaos-network-general::pulumi:providers:aws::us_east1
aws:ec2/eip:Eip                          urn:pulumi:dev::kaos-network-general::aws:ec2/eip:Eip::eip-2
aws:ec2/eip:Eip                          urn:pulumi:dev::kaos-network-general::aws:ec2/eip:Eip::eip-0
aws:ec2/eip:Eip                          urn:pulumi:dev::kaos-network-general::aws:ec2/eip:Eip::eip-1
aws:ec2/vpc:Vpc                          urn:pulumi:dev::kaos-network-general::aws:ec2/vpc:Vpc::main
aws:ec2/internetGateway:InternetGateway  urn:pulumi:dev::kaos-network-general::aws:ec2/internetGateway:InternetGateway::gw

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/kaos
User           kaos
Organizations  kaos

Dependencies:
NAME        VERSION
black       22.8.0
pip         22.2.2
pulumi-aws  5.14.0
setuptools  65.3.0
wheel       0.37.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @nc-kaos 

If you change "print" to be 

pulumi.export("region", region) 

Does it work for you?

Paul

**Comment by nc-kaos** [comment]
Hi, nope, it throws exception:

Exception: Failed to export output. Root resource is not an instance of 'Stack'

**Comment by Frassle** [comment]
> Exception: Failed to export output. Root resource is not an instance of 'Stack'

This is run via "pulumi preview/up" right?

**Comment by stack72** [comment]
Hi @nc-kaos 

This program works fine:

```
"""A Python Pulumi program"""

import pulumi
aws_config = pulumi.Config("aws")

region = aws_config.get("region")
pulumi.export("region", region)
```

without using the export, but using the print, I get the following output:

```
Diagnostics:
  pulumi:pulumi:Stack (test-config-dev):
    us-west-2
```

**Comment by nc-kaos** [comment]
> 

Nope, it was run via python, and I think that was an issue.



> Hi @nc-kaos
> 
> This program works fine:
> 
> ```
> """A Python Pulumi program"""
> 
> import pulumi
> aws_config = pulumi.Config("aws")
> 
> region = aws_config.get("region")
> pulumi.export("region", region)
> ```
> 
> without using the export, but using the print, I get the following output:
> 
> ```
> Diagnostics:
>   pulumi:pulumi:Stack (test-config-dev):
>     us-west-2
> ```

I still receive None and error when running print/export, but resources down the road are interpreting "region" variable correctly. Little weird, but main point is - it works. Thanks for assistance guys.

**Comment by stack72** [comment]
@nc-kaos as you are ok, I will close this out. Let me know if you need to me to reopen it
