### ISSUE TITLE
Homebrew update failure for 3.40.2

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#10860]
The dispatch job failed in the GitHub Action workflow used to create a PR to homebrew/core:  https://github.com/pulumi/pulumi/actions/runs/3132374600/jobs/5084652934

The error is due to `brew` not being present on the PATH.

**Comment by johnkors** [comment]
I guess you're already on it, but all our pulumi builds are now failing with 3.40.2 that worked in v3.40.0.


Run pulumi/actions@v3
Configured range: ^3
Matched version: v3.40.2
Install destination is /home/runner/.pulumi
Successfully deleted pre-existing /home/runner/.pulumi/bin
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/.pulumi -f /home/runner/work/_temp/912ca936-16dd-4831-88b4-c0d0888ff914
Error: code: -2
 stdout: 
 stderr: Command failed with exit code 255: pulumi stack select ohmia/pull69 --non-interactive
error: could not get cloud url: could not load current project: 1 error occurred:
	* #/config: expected string or null, but got object

**Comment by Frassle** [comment]
> * #/config: expected string or null, but got object

That's unrelated to anything to do with brew.
Do you have "config" set in your Pulumi.yaml?

**Comment by johnkors** [comment]
Ah, sorry. I thought this was a 3.40.2 general issues ticket. Sorry. Opened [a sep ticket](https://github.com/pulumi/pulumi/issues/10862).
