### ISSUE TITLE
Homebrew Tap update failure in 3.40.2

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#10861]
The release workflow triggering an update to pulumi/homebrew-tap failed: https://github.com/pulumi/pulumi/actions/runs/3132364032/jobs/5084632708

**Comment by AaronFriel** [comment]
The change in #10868 hasn't quite fixed this.

**Comment by Frassle** [comment]
I think this is fixed now, last release didn't have issues.
