### ISSUE TITLE
Provider acquisition falls back to `get.pulumi.com`

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#10882]
### What happened?

I've not been able to recreate this just yet, but I've had multiple reports of this.

In some circumstances, when setting the `pluginDownloadUrl` in a plugin, occasionally the acquisition fails via a github URL or other URL and falls back to `get.pulumi.com` - example:

```
 error: Could not automatically download and install resource plugin 'pulumi-resource-scaleway'at version v0.0.3, install the plugin using `pulumi plugin install resource scaleway v0.0.3`.
    Underlying error: error downloading plugin scaleway to file: failed to download plugin: scaleway-0.0.3: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-scaleway-v0.0.3-darwin-amd64.tar.gz
```

### Steps to reproduce

It's hard to reproduce, so I'm opening this issue to track failures

### Expected Behavior

It acquires the plugin from github

### Actual Behavior

fails back to get.pulumi.com

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
[GetSource](https://github.com/pulumi/pulumi/blob/master/sdk/go/common/workspace/plugins.go#L751) looks like this would be impossible? If pluginDownloadURL is set then we don't ever hit the get.pulumi.com path.

Is it possible that the downloadURL itself is being unset somehow?

**Comment by ringods** [comment]
@jaxxstorm if it fails, is the user running Pulumi v3.35.3 or up? Worth verifying.

https://www.pulumi.com/docs/guides/pulumi-packages/how-to-author/#support-for-github-releases

**Comment by Frassle** [comment]
Ah I've worked out why this is!
If we hit the code path for automatic plugin fetching (i.e. the standard paths that should have pre-fetched this missed the plugin) we don't have the server URL anymore.

I'll see if there's a way to keep hold of the server URL for longer so these paths can use it, but we should also fix up the reasons that plugins get missed in the pre-fetch. We know some of the ways that can happen, but if we can get more details from customers about how exactly they're hitting this case today it could help.

**Comment by jaxxstorm** [comment]
Another example of this

https://github.com/lbrlabs/pulumi-grafana/issues/17

**Comment by jaxxstorm** [comment]
Whoops I didn't mean to close this!

**Comment by ringods** [comment]
One of our customers bumped into this case. They had a third-party provider in their setup which they removed.

* started from a working situation with the thirdparty provider in place
* they removed the resources from their program *and* removed the SDK package dependency for this provider
* when running `pulumi up`, our engine wants to destroy these resources but it can't find the download url anymore for this provider and falls back to `get.pulumi.com`

Current workaround is a two step approach:

1. remove only the resources from the program. Leave the package dependency in place for now. It is the package install which downloads the plugin binary and make it available to the engine. Now run `pulumi up` for every of the stacks of this program to have the resources destroyed.
1. remove the package dependency from your Pulumi program.

**Comment by aaronkao** [comment]
Getting the same error 

```
pulumi plugin install resource grafana v0.0.5
[resource plugin grafana-0.0.5] installing
error: [resource plugin grafana-0.0.5] downloading from : failed to download plugin: grafana-0.0.5: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-grafana-v0.0.5-linux-amd64.tar.gz
```

**Comment by ringods** [comment]
@aaronkao that will never work. The correct command is:

`pulumi plugin install resource grafana v0.0.5 --server github://api.github.com/lbrlabs`

But that is not the bug.

**Comment by Moon1706** [comment]
@aaronkao 
It doesn't always work as I mentioned here (https://github.com/pulumi/pulumi/issues/11743#issuecomment-1367123761)

**Comment by henriiik** [comment]
You can reproduce this issue with the following steps.

1. have a stack with a provider `$X` using version `$Y`
2. upgrade npm package to version `$Z`
3. remove cached plugins `pulumi plugin rm resource $X`
4. pulumi up
5. crash with error message like this: 

```
error: Could not automatically download and install resource plugin 'pulumi-resource-$X' at version $Z, install the plugin using `pulumi plugin install resource sentry $Z`.
```

Specific provider + versions should not matter but in our case it was the `@pulumiverse/sentry` plugin and the versions v0.0.4 and v0.0.8.

```
```
