### ISSUE TITLE
Change the resource provider using the `aliases` field to refactor

### ISSUE THREAD

**Issue by santunioni** [pulumi/pulumi#10897]
Hello people, imagine the following scenario:

I created a aws/S3 with a simple pulumi project. The project grows and now I have many resources from AWS. I'd like to change the resources provider from the default one.

A valid use case is: Now I want to customize my AWS provider to apply several tags to the resources by default.

I imagined that the `aliases` field would do the trick, but I was wrong. The engine keeps suggesting me to replace the bucket when I explicitly assign the new provider to the bucket resource.

This seems related to #2753, but the solution implemented there was to ignore default providers changes. Can't the engine let the user decide where a provider change should replace the resource or not? 🤔 (something like using the `aliases` field)

Please do not hesitate to tell me if I am missing something.

Thank you all in advance.

**Comment by Frassle** [comment]
I think this _might_ be possible to do with aliases, if you check the stack state there will be a default provider resource (called something like "pulumi::stack::aws::Provider::default") I think if you set the alias for the explicit provider to that URN the engine can see they're the same provider.

**Comment by santunioni** [comment]
@Frassle that's an interesting proposal and I will try later.

Thinking retrospectively, this is kind of intuitive but I couldn't think 🤔.

Thanks a lot! 🙌

**Comment by Frassle** [comment]
If it doesn't work feel free to reopen this issue.
