### ISSUE TITLE
Consider allowing components to be passed CustomResourceOptions and to have control over how to delegate to children

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#10922]
Currently, we have two sets of resource options, `CustomResourceOptions` which can be passed to a custom resource, and `ComponentResourceOptions` which can be passed to a component resource.

`CustomResourceOptions` includes many options that are not currently supported (or at least, never do anything) for components.  For example:
* `deleteBeforeReplace` (components have no semantics for replacement)
* `customTimeouts` (components have no semantics for timeouts)
* `retainOnDelete` (components have no notion of Delete)

We recently added warnings for cases where options were passed to components when these options would have no effect (https://github.com/pulumi/pulumi/pull/9921).  In almost all cases, these warnings called out cases where users were not getting the behaviour they had assumed they would.

However, there are reasons to want to be able to pass some of these options to components, and it's worth considering how to support this.

For example, take `customTimeouts`, and imagine a component that wraps creating a cluster and setting up some supporting services around that cluster.  A timeout may be a very important part of configuring the cluster - which may take a long time to provision, with failure modes leading to very long hangs which need to be timed out.  It is natural for the wrapping component to want to expose an interface to users that accepts `customTimeouts` just like the raw cluster resource would.  Today, this wouldn't work, and would trigger a warning.  It's possible to express these patterns by providing input properties to the resource to pass this information, but this is "different" than the expectations created generally in the Pulumi programming model, and introduces friction for component authors.

There are a couple alternative patterns that would be possible:
1. Allow these options to be passed to components, and make the component author responsible for delegating them down to children.  For example, the wrapper component described above could pass the timeout value down to the child cluster resource, or could even pass 90% of the value to that resource, and 10% to the others, to attempt to ensure that overall component construction fits within a timeout.
2. We could add custom timeout semantics to components, either automatically setting a timeout on all children if it's set on the parent, or setting a cumulative timeout across all child resource constructions. 

Similar things are true for other custom resource options, where allowing them to be passed to components, and assuming that components will manually manage the delegation to children, or that a well-defined semantic for delegation will be established for components.

In practice, it seems that option (1) quite likely will be more flexible and expressive, though it leaves open a door for consumers to expect semantics that the component does not ultimately implement (or implement "correctly").  We should consider how we might allow components to do this delegation for some subset of properties, while still warning if these options are passed to a component which has not defined any semantics for the corresponding option.

**Comment by joeduffy** [comment]
I have to admit, I’m surprised we ended up here. Wasn’t (1) the original design intent from the outset?

**Comment by phillipedwards** [comment]
Another use case is `ignoreChanges`. While not always 1st choice, this resource option can be important at times.

**Comment by lukehoban** [comment]
We've removed the warnings when passing a resource option which is not explicitly understood by the engine for components to a component resource.  This allows component implementations to handle these resource options as they see fit.

We will follow up with docs for each such resource option to indicate to users that there is no Pulumi-defined behaviour for the resource option when applied to a component, but that components can decide how to delegate behaviour to children.  One example of this is in https://github.com/pulumi/pulumi-hugo/pull/2059 - which adds this note to `ignoreChanges`:

> The `ignoreChanges` resource option does not apply to inputs to component resources.  If `ignoreChanges` is passed to a component resource, it is up to that component's implementation to decide what if anything it will do.

**Comment by Frassle** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/11010

We're going with approach 1 as described above. It's something to reconsider especially as a 4.0 action if there's something better we can do here, but for now people can pass and manipulate options as the go down the component chains.
