### ISSUE TITLE
Release notes generated with incorrect PR links 

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#10939]
[Release notes](https://github.com/pulumi/pulumi/releases/tag/v3.40.2) include links like:

[`https://github.com/pulumi/pulumi/pulls/10789`](https://github.com/pulumi/pulumi/pulls/10789), however they should be:
[`https://github.com/pulumi/pulumi/pull/10789`](https://github.com/pulumi/pulumi/pull/10789)

**Comment by myhau** [comment]
I want to catch up with changes in `pulumi/pulumi` and these links make it kinda inconvenient. 

@AaronFriel @Frassle 
Is it ok if I create a PR that fixes these links in the `CHANGELOG.md` file?

**Comment by ericrudder** [comment]
@lukehoban I did (admittedly) one spot check and didn't see this ... is it still a problem in some places?

**Comment by tgummerer** [comment]
It looks like this was fixed in https://github.com/pulumi/go-change/pull/17, but this issue was not closed automatically for some reason.  I'm gonna go ahead and close it out.
