### ISSUE TITLE
Improved recovery for invalid stacks

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1094]
## Issue

If an update is interrupted partway through, it is possible that the service's understanding of your stack's state will have drifted from reality.  The Pulumi CLI and service have no way of reconciling this drift today, and react conservatively by marking the state as "unknown."  The result is the following error message:

> error: stack's resources are in an unknown state due to an interrupted update;
>     please export the stack, repair any inconsistencies, and import the result

## Workaround

To recover from this situation, you will need to do three things:

1. Export your stack's current state checkpoint by running the `pulumi stack export` command.  It is JSON and you probably want to redirect it to a file for easy viewing and editing: `pulumi stack export > stack.json`.  We recommend making a backup of this file for safe-keeping, since what follows requires a bit of manual and error prone editing.
2. Manually verify that the state represents the current state in your cloud and make any necessary edits to the state file (if any -- it is possible none will be needed).  *Be very careful making edits; any incorrect information may worsen the situation, and any deletions are not easy to recover in the current system.*
3. Import your stack's updated state checkpoint, with the newly patched resource information, using the `pulumi stack import` command.  For example, if stored in the `stack.json` file, just run `pulumi stack import < stack.json`.  This will upload your file and automatically clear the unknown status on your stack so that it is usable once again.

----

Notes:

Depending on where we land with https://github.com/pulumi/pulumi/issues/1077, we may or may not need to invest in better recovery for invalid stacks.  An invalid checkpoint occurs when an update interruption happens at an inopportune moment.  There are ways we could possibly recover from this, for instance, if we knew that the local machine had reached a steady state prior to the interruption.  Alternatively, we may just want to make the UX better, by interactively prompting the user for what they want to do next -- including possibly doing an interactive refresh to repair the state of the stack from the source of truth.

**Comment by lukehoban** [comment]
This got better with "pending operations" in the checkpoint - so we provide more context to users - but we can still improve further.

**Comment by pgavlin** [comment]
@lukehoban I have no current plan. I will think on it.

**Comment by leezen** [comment]
Related: https://github.com/pulumi/pulumi/issues/4265

**Comment by lukehoban** [comment]
In practice, the remaining issues here now are tracked in #4265, which is also has a proposed plan of action.  Closing this older issue as a duplicate.
