### ISSUE TITLE
`pulumi refresh` and `pulumi destroy` should accept a `--preview` flag

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#10966]
I swear this existed at some point. This flag would stop after the preview. Particularly useful for refresh.

**Comment by AaronFriel** [comment]
Is this related to @10967?

**Comment by justinvp** [comment]
We discussed this and leaning towards adding `--preview-only` flag to `pulumi refresh` and `pulumi destroy` (and possibly `pulumi up` for consistency).

In the future, we may want to consider adding `pulumi preview refresh` and `pulumi preview destroy` sub commands.
