### ISSUE TITLE
The latest pulumi-cli reports 'bucket azblob://<container-path> is not accessible' when using the Azure Blob Storage backend

### ISSUE THREAD

**Issue by jon-xi** [pulumi/pulumi#10981]
### What happened?

After upgraded to pulumi v3.42.0, the pulumi reports 'bucket azblob://<container-path> is not accessible' when using the Azure Blob Storage backend.

### Steps to reproduce

1. run the installation script: curl -fsSL https://get.pulumi.com | sh
2. run 'pulumi version': make sure the version is 'v3.42.0'
3. export PULUMI_BACKEND_URL=azblob://my-container-name
4. export AZURE_STORAGE_ACCOUNT=my-storage-account
5. export AZURE_STORAGE_KEY=my-storage-account-key
6. run 'pulumi up' or 'pulumi preview'

### Expected Behavior

'pulumi up' or 'pulumi preview' succeeds

### Actual Behavior

 The pulumi reports 'bucket azblob://<container-path> is not accessible'.

### Output of `pulumi about`

2022/10/10 03:08:10 azureblob: constructed service URL: https://<my-storage-account>.blob.core.windows.net
2022/10/10 03:08:10 azureblob.URLOpener: using shared key credentials
error: bucket azblob://<my-storage-account> is not accessible

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
`PULUMI_BACKEND_URL=azblob://` doesn't look like a valid blob url, so I would expect the CLI to error that this is unreachable?

**Comment by jon-xi** [comment]
The content has been cut out, actually it is a valid blob url.

export PULUMI_BACKEND_URL=azblob://my-container-name
export AZURE_STORAGE_ACCOUNT=my-storage-account
export AZURE_STORAGE_KEY=my-storage-account-key

**Comment by Frassle** [comment]
Does that blob already exist? We try to "list" the blob to check access to it, can you call [`az storage blob list`](https://learn.microsoft.com/en-us/cli/azure/storage/blob?view=azure-cli-latest#az-storage-blob-list) on the blob?

**Comment by jon-xi** [comment]
Definitely exists.
For old version of pulumi, say, v3.40.2, there was no issues at all, only when upgraded to v3.41.1 or v3.42.0, the issue occurred.

**Comment by Frassle** [comment]
Ah interesting we updated gocloud in 3.41 (https://github.com/pulumi/pulumi/pull/10900), and looks like there's been a number of changes to azure code in there.

**Comment by AaronFriel** [comment]
@jon-xi Could you try the instructions in the note block for using `az login` to authenticate?

https://www.pulumi.com/docs/intro/concepts/state/#logging-into-the-azure-blob-storage-backend

Copied here:

> As of Pulumi CLI v3.41.1, instead of the environment variables above, Azure CLI authentication may be used by specifying the storage account in the URL like so after using az login:
> 
> ```sh
> pulumi login azblob://<container-path>?storage_account=account_name
> ```

**Comment by AaronFriel** [comment]
@ekini I see you've contributed both to the gocloud.dev backend, to #10900, and to our docs! (Thank you!) Do you have any insight into why this would fail? 

I'm considering this a P0 on our end and may have to revert #10900 if we aren't able to document a workaround or roll out a fix. It looks like

**Comment by jon-xi** [comment]
@AaronFriel

I have tried the instructions you mentioned, it still didn't work, just the behavior is slightly different:

Steps:
1. pulumi version - v3.42.0
2. export PULUMI_BACKEND_URL=azblob://my-container-name?storage_account=my-storage-account-name
3. export AZURE_STORAGE_KEY=my-storage-account-key

Outputs:
2022/10/11 06:06:19 azureblob: constructed service URL: https://my-storage-account.blob.core.windows.net
2022/10/11 06:06:19 azureblob.URLOpener: using shared key credentials
error: bucket azblob://my-container-name?storage_account=my-storage-account is not accessible

This time, it spent much more time to print the error message, it seems to be stuck somewhere. :-(

**Comment by ekini** [comment]
@jon-xi as per your initial comment, this
```
2022/10/10 03:08:10 azureblob: constructed service URL: https://.blob.core.windows.net
```
doesn't look right at all! Could you please confirm the env vars are definitely set, i.e. with `env | grep AZURE_STORAGE`?

Maybe you could try the cli auth? The AZURE_STORAGE_KEY needs to be unset, it's not used with this type of auth. And your user needs to have a ` Storage Blob Data Contributor` role, just having Owner is not enough.

**Comment by ekini** [comment]
Basically, if both `AZURE_STORAGE_ACCOUNT` and `AZURE_STORAGE_KEY` are set, [here](https://github.com/google/go-cloud/blob/master/blob/azureblob/azureblob.go#L324) it decided to go this authentication path, and then goes [here](https://github.com/google/go-cloud/blob/master/blob/azureblob/azureblob.go#L356) which outputs the same log as you get.

I don't see any way you can be left with the storage_account unset in this case.

**Comment by jon-xi** [comment]
@ekini Please take a look of the following screenshots.

![image](https://user-images.githubusercontent.com/2657899/195072477-c29c0174-9541-4279-8513-ba5b4e7a4aef.png)
---
![image](https://user-images.githubusercontent.com/2657899/195072632-554b6878-0d7d-46e2-bf48-5bc03042c25b.png)

**Comment by ekini** [comment]
Thank you @jon-xi ! Everything does look good and should work as expected. Could you please run one more thing just to make a clean experiment?
Hopefully, Docker is installed on the VM. If so, please try this:
```
docker run -ti -e AZURE_STORAGE_ACCOUNT=$AZURE_STORAGE_ACCOUNT -e AZURE_STORAGE_KEY=$AZURE_STORAGE_KEY --rm mcr.microsoft.com/azure-cli az storage blob list -c CONTAINER_NAME
```
to run the command in a clean environment without anything extra that might affect it. This should just output the object list and I just want to know if it works or not.

Is it a VM running on Azure? Just trying to gather more information to hopefully reproduce the problem.

**Comment by jon-xi** [comment]
@ekini I've created a new storage account and tested it, and it worked without errors this time, thank you very much!

But when we run the 'pulumi up' command from Pulumi Automation API, the following messages were printed from the *OnStandardError* delegate, not from the *OnStandardOutput* delegate, why is that?
```
2022/10/11 06:06:19 azureblob: constructed service URL: https://my-storage-account.blob.core.windows.net/
2022/10/11 06:06:19 azureblob.URLOpener: using shared key credentials
```
The screenshots are below:

![image](https://user-images.githubusercontent.com/2657899/195130662-29973e83-3799-43f6-b4af-a55133a8b5ab.png)
---
![image](https://user-images.githubusercontent.com/2657899/195131707-00d701f4-e062-4240-bd68-8df1de16fe3c.png)
---
![image](https://user-images.githubusercontent.com/2657899/195131776-fb621def-310b-453e-a172-043d69326461.png)

**Comment by Frassle** [comment]
Someone noticed that on community slack as well: https://pulumi-community.slack.com/archives/CRVK66N5U/p1665422408374799

It looks like the new version of go-cloud is writing to stdout by default. We need to add some code to reset that on startup.

**Comment by AaronFriel** [comment]
@jon-xi & @ekini thank you for the back and forth on this, it looks like we have a separate issue with stdout logging.

@jon-xi I'm going to delete the images from your screenshot that include portions of the PULUMI_ACCESS_TOKEN and AZURE_STORAGE_KEY secrets and suggest you rotate those. I can't guarantee that no GitHub mirrors have made a copy of those, and I think there's just enough text showing that a user could reconstruct the values.

**Comment by AaronFriel** [comment]
Created an issue for the stdout logging and tracking it! Thanks again @ekini, incredibly helpful. 🙌

**Comment by Andy-d-g** [comment]
Hi, I've the same issue but I'm not sure to understand the solution.

I should use a new storage ?

Thx
