### ISSUE TITLE
Fail Pulumi YAML upgrades on PCL deltas

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#10987]
As part of https://github.com/pulumi/pulumi-yaml/issues/251, the Pulumi YAML repo's PCL output will be decoupled from this repo's. To ensure that updated `pulumi convert` codegen is tested, we must add that verifies the PCL (.pp files) of the version of YAML matches the the PCL in this repo's testdata.

The shipped version of pulumi-yaml is defined by package version in `pkg/go.mod` (see: `scripts/get-language-proviers.sh`).

**Comment by aq17** [comment]
Addressed via https://github.com/pulumi/pulumi-yaml/pull/365
