### ISSUE TITLE
Test flake due to connection reset in setup actions

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#10997]
Test such as [this run](https://github.com/pulumi/pulumi/actions/runs/3229942493/jobs/5288048669) fail in `Set up DotNet 6.0.x`:

> Run actions/setup-dotnet@v2
> Error: read ECONNRESET

This is a tracking issue for us to correlate these errors and make upstream issue(s) as needed.

This problem appears to be localized to the actions/setup-dotnet@v2 action.

* 14 out of 20 of the most recent merge jobs failed.
* Ten failures were in the Set up DotNet 6.0.x job, and this occurred on all 3 platforms (windows, ubuntu, macos).
* One failure was due to a different network issue (pulumictl ETIMEDOUT)
* Three due to an issue with the PR.

Upstream issue: https://github.com/actions/setup-dotnet/issues/333

**Comment by kpitzen** [comment]
https://github.com/pulumi/pulumi/actions/runs/3230628127/jobs/5289317304

**Comment by kpitzen** [comment]
https://github.com/pulumi/pulumi/actions/runs/3231178910/jobs/5290629115

**Comment by kpitzen** [comment]
https://github.com/pulumi/pulumi/actions/runs/3231404553/jobs/5290948152
