### ISSUE TITLE
Provider downloads from a third party fails

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#11013]
### What happened?

When trying to test the download of third-party plugins from GitHub, we get a 403 error.

These commands work fine locally.

### Steps to reproduce

Enable the

```
await ws.installPluginFromServer("scaleway", "v1.2.0", "github://api.github.com/lbrlabs");
```

Test

### Expected Behavior

It downloads the plugin

### Actual Behavior

We get a 403

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This _might_ just have been rate limits? I wonder if we can pull the request body text off for that error to make it a bit more clear.

**Comment by Frassle** [comment]
I think you could quibble over this being a bug or enhancement, I don't think we want to auto-retry all 403's in plugin install but that error message could be a lot better. Rather than just saying 403, github would have given some details in the http response as well but we don't bother looking at that.

**Comment by RobbieMcKinstry** [comment]
Ah, I see what you're getting at re: bug vs feature. I interpreted this issue as specifically a bug in the behavior of the AA function that Lee added in the linked PR. Whoops, I get it now.

**Comment by RobbieMcKinstry** [comment]
@Frassle would you agree that this is a usability consideration we could fix? It feels like the domain of "First 48H"-style usability and error message issues (I know that epic is done with, just trying to draw an analogy).

**Comment by brandonpollack23** [comment]
Is this issue still relevant? I took a look at the code and now we use go's recommended fmt.Errorf and include the formatted error completely in the log.

**Comment by tgummerer** [comment]
Yeah it looks like we're indeed erroring out with a proper error message here now, so we can close this out.
