### ISSUE TITLE
Ctrl-c leaves 0 byte `credentials.json` which pulumi chokes on.

### ISSUE THREAD

**Issue by kmosher** [pulumi/pulumi#11017]
### What happened?

Started an update of the `pulumi/home/infrastructure/build-metrics` stack with stale AWS session creds. Ctrl-C'ed when I realized it was hung in preview trying to do a read that would eventually time out.

Somehow my `~/.pulumi/credentials.json` file got nuked in the process.

All further runs of `pulumi update` and `pulumi login` printed the following:
```
error: could not get cloud url: failed to read Pulumi credentials file. Please re-run `pulumi login` to reset your credentials file: unexpected end of JSON input
```

Checked `credentials.json` and it was 0 bytes in size.

Deleting `credentials.json` un-wedged it and allowed `pulumi login` to work.

### Steps to reproduce

Obviously this might be a fun one to fully repro.

`cat /dev/null > ~/.pulumi/credentials.json` will test pulumi's handling of 0'ed creds files.

### Expected Behavior

Obviously,

1. pulumi should handle Ctrl-C more gracefully in a way that doesn't nuke the creds file.
2. pulumi should recover more gracefully from a borked creds file. `pulumi login` should be enough to fix this state.

### Actual Behavior

pulumi does neither of those things.

### Output of `pulumi about`

```
CLI
Version      3.42.0
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     4.7.0
docker  3.0.0
nodejs  unknown

Host
OS       darwin
Version  12.6
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v18.10.0'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/kmosher
User           kmosher
Organizations  kmosher, pulumi

Dependencies:
NAME                        VERSION
@octokit/plugin-throttling  3.5.0
@pulumi/aws                 4.7.0
@pulumi/awsx                0.30.0
@pulumi/pulumi              3.4.0
@slack/webhook              5.0.3
octokit                     1.1.0
@types/node                 10.17.44
```

### Additional context

This is on macOS 12.6, M1 (arm64), with the default `apfs` filesystem.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Hey Keith, thanks for this report. It sounds like you hit the nail on the head with your "expected behavior" section.

>    pulumi should handle Ctrl-C more gracefully in a way that doesn't nuke the creds file.

Regarding Ctrl-C, we've had a number of bugs opened about race conditions that occur when Ctrl-C is used. The engine uses so many channels and sometimes shares memory between multiple threads, it's quite hard to track down and fix bugs like these. It's a long-term goal to isolate different components of the engine from each other to reduce the tight-coupling between threads.

>    pulumi should recover more gracefully from a borked creds file. pulumi login should be enough to fix this state.

This is much easier to fix. We can insert a call to `fs.stat` during `login` to see how big the `credentials.json` file is, and if it's zero bytes, we can just clear it and proceed. While this won't fix the ultimate problem (why are credentials files getting klobbered in the first place?), it will fix the usability concerns.

**Comment by Frassle** [comment]
Luke pointed out that before https://github.com/pulumi/pulumi/pull/8634 we use to do an write to temporary and then atomic swap to save the credential file, but that PR changed it to try to just use `lockedfile` so we can end up with a cleared but not written file now if pulumi gets killed during that Write (it's not atomic).

**Comment by kmosher** [comment]
> This is much easier to fix. We can insert a call to `fs.stat` during `login` to see how big the `credentials.json` file is, and if it's zero bytes, we can just clear it and proceed. While this won't fix the ultimate problem (why are credentials files getting klobbered in the first place?), it will fix the usability concerns.

Also worth thinking through what `pulumi` should do in other cases where `credentials.json` fails to json parse or is otherwise corrupted. `pulumi login` should probably just clobber that file if it can't understand it. Though maybe there are cases where that wouldn't be desirable?
