### ISSUE TITLE
`pulumi package get-schema docker` calls docker

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#11014]
### What happened?

While attempting to debug an issue with pulumi-docker, `pulumi package get-schema docker` was called. Instead of retrieving the schema from the already downloaded docker provider, it seemingly called the docker CLI.

### Steps to reproduce

Run `pulumi package get-schema docker`

### Expected Behavior

The docker schema is written to stdout.

### Actual Behavior

```
docker: '127.0.0.1:59789' is not a docker command.

See 'docker --help'

error: could not read plugin [docker] stdout: EOF
```
:point_uis written to standard error.

### Output of `pulumi about`

```
CLI          
Version      3.42.0-dev.0
Go Version   go1.19
Go Compiler  gc

Host     
OS       darwin
Version  12.6
Arch     x86_64
```

### Additional context

@Zaid-Ajaj found the bug, I (@iwahbe) confirmed that it was cross-platform and reproducible.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
`os.Stat` looks at PATH, we use that to decided if the string passed to us is a plugin file to invoke directly or a plugin name. "docker" is a file on PATH so we try to invoke it directly.

**Comment by iwahbe** [comment]
> `os.Stat` looks at PATH, we use that to decided if the string passed to us is a plugin file to invoke directly or a plugin name. "docker" is a file on PATH so we try to invoke it directly.

Here is the funny thing. `aws` is also on my path, but `pulumi package get-schema aws` works as expected.

There even both symlinks:
```
$ ls $(which aws) $(which docker)
lrwxr-xr-x 30 iwahbe   12 Oct 20:02 /usr/local/bin/aws -> ../Cellar/awscli/2.8.2/bin/aws*
lrwxr-xr-x 54 root     16 Aug  2021 /usr/local/bin/docker -> /Applications/Docker.app/Contents/Resources/bin/docker*
```

**Comment by iwahbe** [comment]
In `pulumi/pulumi`, where I happened to be while testing, there is a directory called `docker`. There is not a directory called `aws`. That causes the problem. If there is a file, we error as intended.
