### ISSUE TITLE
No logs available for update failures during initialization

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1102]
Consider the following update. The resource provider fails because a required config setting is missing.

```
$ pulumi update
Updating stack 'timer-test' in the Pulumi Cloud ☁️
error: failed to load resource plugin aws: failed to configure pkg 'aws' resource provider: could not validate provider configuration: 1 error(s) occurred:

* "region": required field is not set
```

The update is reported as having failed, but the actual log lines are not reported to the PPC/Hosted-Stack and as a result the logs are empty when rendered on the service.

**Comment by swgillespie** [comment]
Doesn't repro anymore with the various changes we've made in this area.
