### ISSUE TITLE
Provide a secure way to preview prod changes in pull requests

### ISSUE THREAD

**Issue by DominicRoyStang** [pulumi/pulumi#11024]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Some context:

We are using Pulumi with S3 as our backend.

For every pull request, we want our CI/CD pipeline to run `pulumi preview --stack prod --suppress-outputs` to see what changes will be deployed to production.

For us to be able to run this, we would need to expose the `PULUMI_CONFIG_PASSPHRASE` used by the prod stack as well as an access key that can read the `prod.json` backend file in pull request pipelines. This is a security risk because someone could use the information to expose secrets.

If I don't provide the `PULUMI_CONFIG_PASSPHRASE`, `pulumi preview` will ask for it.

As far as I understand, this information (passphrase + read access key for `prod.json`) is all I would need to decrypt the secrets listed in the `prod.json` file.

I believe this would still be a problem if we were to use AWS KMS as our secrets provider. In that scenario, we have to expose AWS credentials that grant access to the key store in pull request pipelines.

I think that at its core, the problem is that resources and their outputs are tightly coupled in the backend stack file. We should be able to restrict access to just resource information without also needing to provide read access to all their outputs. Or at the very least, restrict access to resource information and **non-secret** configs/outputs.

I'm open to any and all workarounds here 👀 

### Affected area/feature

- Pulumi backends

This issue is somewhat related to this one: https://github.com/pulumi/pulumi/issues/2823

**Comment by DominicRoyStang** [comment]
> I'm a tad confused - `pulumi stack output -s <stack_name> --show-secrets` only lists actual defined outputs when I try. `PULUMI_CONFIG_PASSPHRASE` is only set as an environment variable, it is not automatically part of any output.
> 
> CLI Version 3.42.0 in my case.

Huh, you're right @CmdrSharp . I was trying to find the simplest way to illustrate my point, but that example was poor. I've updated the issue description.

Here is the actual issue I was looking into:

In order to grant the ability to `pulumi preview --stack prod` to my pull request pipelines, I need to provide the `PULUMI_CONFIG_PASSPHRASE` for prod and an AWS API key that can read the `prod.json` file in the backend. If I don't provide the config passphrase, pulumi preview will ask for it.

As far as I understand, this information is all someone would need to decrypt the secrets listed in the prod.json file.

---

For a more concrete example, suppose we were to use Pulumi to create an AWS access key.

The backend `prod.json` file would contain an entry like this.

```json
{
    "urn": "urn:pulumi:prod::project::aws:iam/accessKey:AccessKey::access-key",
    "custom": true,
    "id": "ACCESSKEYID",
    "type": "aws:iam/accessKey:AccessKey",
    "inputs": {
        "__defaults": [
            "status"
        ],
        "status": "Active",
        "user": "access-key-user-e95dbba"
    },
    "outputs": {
        "createDate": "2022-10-14T08:20:20Z",
        "id": "ACCESSKEYID",
        "secret": {
            "ghi789": "jkl012",
            "ciphertext": "v1:CypherTextHere="
        },
        "sesSmtpPasswordV4": {
            "abc123": "def456",
            "ciphertext": "v1:CypherTextHere="
        },
        "status": "Active",
        "user": "access-key-user-e95dbba"
    },
    "parent": "urn:pulumi:prod::project::pulumi:pulumi:Stack::project-prod",
    "dependencies": [
        "urn:pulumi:prod::project::aws:iam/user:User::access-key-user"
    ],
    "provider": "urn:pulumi:prod::project::pulumi:providers:aws::default_5_16_2::1234",
    "propertyDependencies": {
        "user": [
            "urn:pulumi:prod::project::aws:iam/user:User::access-key-user"
        ]
    }
}
```

With the `PULUMI_CONFIG_PASSPHRASE` and the information listed, my understanding is that a malicious user would be able to decypher the `secret` value listed in the outputs section of this file.

**Comment by CmdrSharp** [comment]
You are correct that with the config passphrase and the config file containing the salt, the details can be decrypted.

I don't really see a way around this, however. Pulumi needs to be fed the secret _somewhere_ (in a common example, injected as an environment variable stored in GitHub Secrets, or perhaps fetched from Hashicorp Vault or similar).

At some point in time, the secret simply needs to be fetched and fed to Pulumi for it to do its job. If you're running this in a CI/CD-pipeline, it absolutely exposes the _possibility_ for someone else to be malicious. I would try to guard against this with branch rules and by ensuring that pipelines never run without approval (repo settings -> Actions -> General -> Fork pull request workflows from outside collaborators).

Perhaps I am missing something here?

**Comment by DominicRoyStang** [comment]
@CmdrSharp thanks for confirming.

I'm simplifying things a bit here, but essentially, we have the following environment variables

- `AWS_PULUMI_READ_ONLY_ACCESS_KEY` (only has access to read the prod S3 bucket, is exposed in all pipelines)
- `AWS_PULUMI_WRITE_ACCESS_KEY` (can create/update/delete most AWS resources, is **only** exposed in pipelines running on the default branch)
- `PULUMI_CONFIG_PASSPHRASE` (we _want_ this to also **only** be exposed in pipelines running on the default branch)

**Step 1: Pull requests**: on feature branches, we want to have a CI step that runs `pulumi preview --stack prod` using the `AWS_PULUMI_READ_ONLY_ACCESS_KEY`. This allows the code reviewer to quickly see what will change if this branch is merged. Unfortunately, this currently requires that we also grant access to `PULUMI_CONFIG_PASSPHRASE`.

**Step 2: Default branch**: When pull requests get merged to the default branch, another CI pipeline gets run. In this case, it runs `pulumi up --stack prod`  using the `AWS_PULUMI_WRITE_ACCESS_KEY` and  `PULUMI_CONFIG_PASSPHRASE`.

>At some point in time, the secret simply needs to be fetched and fed to Pulumi for it to do its job. If you're running this in a CI/CD-pipeline, it absolutely exposes the possibility for someone else to be malicious.

I agree that Pulumi needs secrets for the steps we are running on the default branch (step 2). I'm looking for a way to only perform a preview on pull requests (step 1) without granting access to production secrets.

>I would try to guard against this with branch rules and by ensuring that pipelines never run without approval (repo settings -> Actions -> General -> Fork pull request workflows from outside collaborators).

- This prevents the pull request reviewers from easily previewing what changes will be applied to the infrastructure if the pull request is merged.
- In my case, we are running on a private repository, but we are in a large company that operates on the _principle of least privilege_. We are pretty protective of production secrets, so not every developer has access to read them. We want some collaborators to be able to create pull requests without (indirectly) granting them access to read production secrets. We still want `pulumi preview --stack prod` (step 1) to be run in CI for their pull requests.

Hopefully this clears up our use case a little bit more, and helps illustrate the need for a way to `pulumi preview` without needing `PULUMI_CONFIG_PASSPHRASE`.

**Comment by RobbieMcKinstry** [comment]
Hi @DominicRoyStang. I've read through the above description, and I hope I can offer something beyond @CmdrSharp 's astute contributions, though I think the Commander is ultimately correct.

Here are the objects in play:

1. Pulumi, a Principal you want to operate with _least privilege_.
2. `AWS_PULUMI_READ_ONLY_ACCESS_KEY`
3. `AWS_PULUMI_WRITE_ACCESS_KEY`
4. `PULUMI_CONFIG_PASSPHRASE`
5. Your S3 bucket, storing the state, which has your state stored. Secrets are encrypted.

The permissions in your system are:
1. `can read secrets`
2. `can read state`
3. `can modify state`

We also have the following conditions which enforce _least privilege_ on the Pulumi principal:

1. When _Pulumi_ is operating on the default branch, we accept that it must have the `modify state` permission.
2. When _Pulumi_ is operating on any other branch, we accept that it must have the `read state` permission and not the `modify state` permission.

We want to determine if (1) `can read secrets` is in the set of least privileges for the Pulumi principal.

----------

To perform a preview, Pulumi needs to determine the diff between the currently running programs and the resources as saved in your statefile. Suppose that a resource in state has a `secret` input. That secret could come from:
1. The `Pulumi.yaml`, in which case it's already encrypted.
2. Another `Output`

If the secret has come directly from `Pulumi.yaml` and into a resource's input, then we have both the encrypted ciphertext in the running Pulumi program, and in the statefile. We could compare the ciphertext and determine whether there is a diff. That's not a problem!

However, the second case isn't as trivial. Suppose a secret is provided to the program via the Config file. You can see [in our docs](https://www.pulumi.com/docs/reference/pkg/python/pulumi/#pulumi.Config.require_secret) that secrets coming from config files are `Output<T>`. That means you can modify the decrypted value with `apply` and return a new secret that can be used as an input. The `Output<T>` typing is rather inconsequential: users may need to be able to transform decrypted secret values before inputting them into other resources. (For example, a user might take a secret password and explode it into five variants to create five SSM secrets using that secret password). 

Additionally, without decrypting secret values, `--refresh` would be unable to compare live resources to resource states. 

Therefore, I'd humbly suggest that `can read secrets` is part of the least privilege set for the Pulumi principal. Without it, not only would a number of Pulumi features not work, but it would restrict the classes of programs that can be expressed in Pulumi.

------------

Following up on the last part of your issue separately:

> We are pretty protective of production secrets, so not every developer has access to read them. We want some collaborators to be able to create pull requests without (indirectly) granting them access to read production secrets.

I presume you're specifically referring to situations where the collaborator needs to run `pulumi preview` locally to evaluate their PR before submitting it? If not: when they submit a PR, and that `preview` is run in the CI environment, they shouldn't be able to see secrets unless they have direct access to the CI/CD machine (in which case, the CI/CD environment is untrusted). Secrets aren't output in plaintext unless running `pulumi preview --show-secrets` is enabled.  

I recommend segmenting your Pulumi project into smaller projects divided by ownership. I'd argue that engineers need to inspect the inputs and outputs of their programs to determine if it's running correctly. If you want a collaborator to self-service by creating PRs for their infrastructure, then it's probably a _least privilege_ for them to be able to inspect the program inputs and outputs.

Suppose that gives them a "large blast radius," so to speak, by giving them access to many resources they can't be trusted to manage. In that case, you can reduce their access by shrinking the number of resources managed by a given stack, giving them access only to the resources they're trusted to manage.

I hope that's helpful! 😺 Please let me know if you have other questions! This made me think really deeply about what Pulumi needs and doesn't need to operate securely.

**Comment by DominicRoyStang** [comment]
Getting back to this issue after a few months. We're currently doing what you suggested: be careful about who gets access to repos.

The only other solution to this I can think of would be to create a service that stores config passphrases and can run `pulumi preview` and return the plan.

Something like this:

1. Commit is pushed
1. CI makes a request to service requesting `pulumi preview --stack prod` to be ran
1. Service selects theappropriate PULUMI_CONFIG_PASSPHRASE for prod stack
1. Service runs `pulumi preview --stack prod`, and returns the output of the command
1. CI outputs the response

There is probably a business opportunity offering this as a service/self-hosted option. I suppose that would be similar to (a subset of) the functionality that [atlantis](https://www.runatlantis.io/) provides for terraform.

Anyhow, I'm going to close this issue because my questions have been answered, and it would probably make more sense to create a separate issue if a feature like that were to be developed.

**Comment by RobbieMcKinstry** [comment]
Thanks for closing the issue. Always happy to chat security :)

Might so plug one of Pulumi's newest features? [Pulumi Deploy](https://www.pulumi.com/blog/pulumi-deployments/) is similar to Atlantis and TF Cloud in that it watches GH repos for commits and executed the code in a hosted environment, similar to your suggestion.
