### ISSUE TITLE
Brew install broken?

### ISSUE THREAD

**Issue by kimdhamilton** [pulumi/pulumi#11041]
### What happened?

To install pulumi on mac, [instructions](https://www.pulumi.com/docs/get-started/install/) say:

> brew install pulumi/tap/pulumi

But that yields a 404

```
==> Downloading https://github.com/pulumi/pulumi/releases/download/v3.43.1/pulum
curl: (22) The requested URL returned error: 404

Error: pulumi: Failed to download resource "pulumi"
Download failed: https://github.com/pulumi/pulumi/releases/download/v3.43.1/pulumi-v3.43.1-darwin-arm64.tar.gz
```

Looking at that github repo, I don't see that path, so the failure makes sense. 

### Steps to reproduce

> brew install pulumi/tap/pulumi

### Expected Behavior

Pulumi installed 🎉

### Actual Behavior

Pulumi not installed + 404 😢

### Output of `pulumi about`

Pulumi not installed, so nothing:
```
$ pulumi about
-bash: pulumi: command not found
```

### Additional context

Pulumi is the best

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kimdhamilton** [comment]
Oops, I noticed `brew install pulumi` works. I'll close it, but maybe this is just a doc rearrange suggestion. Feel free to close after considering possible doc reorder for (what I think is) the more common path

**Comment by AaronFriel** [comment]
@kimdhamilton thank you for reporting this! I've taken steps to fix the URLs in our Tap and we'll be tracking a couple issues to ensure this doesn't happen in the future.
