### ISSUE TITLE
Homebrew Tap should refer to get.pulumi.com blobs or GH releases should be immutable

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#11043]
A PR merge following the release of 3.43.1 updated the GitHub release, invalidating the SHA hashes and modifying the release to be a draft, causing #11041.

If the GitHub Release blobs are immutable (#11042), this can be closed. However if we would prefer users acquire blobs through our CDN, we should update the homebrew the [tap Formula template](https://github.com/pulumi/pulumi/blob/master/.github/scripts/pulumi-tap-template.rb) to use get.pulumi.com URLs.

**Comment by Frassle** [comment]
> However if we would prefer users acquire blobs through our CDN,

I don't think we'd prefer that.

**Comment by AaronFriel** [comment]
We've made the GitHub releases immutable via process changes.
