### ISSUE TITLE
[tf2pulumi codegen] `unknown function` errors

### ISSUE THREAD

**Issue by aq17** [pulumi/pulumi#11068]
Top unknown function errors: 

- [ ] `unknown function 'tolist'`
- [x] `unknown function 'base64encode'`
- [ ] `unknown function 'toset'`
- [ ] `unknown function 'replace'`
- [ ] `unknown function 'jsondecode'`
- [x] `unknown function 'cidrsubnet'`
- [ ] `unknown function 'urlencode'`
- [x] `unknown function 'format'`
- [ ] `unknown function 'filemd5`
- [ ] `unknown function 'yamlencode'`
- [x] `unknown function 'list'`
- [x] `unknown function 'join'`
- [x] `unknown function 'format'; cannot iterate over a value of type union(list(string), none)`
- [x] `unknown function 'flatten'`
- [ ] `unknown function 'sha1'`

**Comment by AlexMapley** [comment]
I think we can add `try` to the list as well, I saw this many across many lines/files:

```shell
Error: unknown function 'try'

  on hello_world.tf line 9:
  (source code not available)
```

**Comment by Frassle** [comment]
`try` is special and might need handling in codegen due to it changing how arguments are evaluated.

**Comment by aq17** [comment]
Closing this in favor of https://github.com/pulumi/pulumi-std/issues/1 due to overlap.
