### ISSUE TITLE
403 HTTP error fetching AWS resource plugin even though it's installed

### ISSUE THREAD

**Issue by iulspop** [pulumi/pulumi#11087]
### What happened?

I started a new Pulumi project in Python today using `pulumi new aws-python` to test the `pulumi import` command on some AWS resources.

Creating the new Pulumi project worked, however when I run `pulumi import AWS::SNS::Topic x-dev-drip-welcome-sns xdevdripwelcomesnsE0E1B83B` I get the error:
```
Previewing import (dev)

View Live: https://app.pulumi.com/iulspop/another-one/dev/previews/cea9f31c-9dbf-412d-b12a-59de485a3121

     Type                 Name             Plan       Info
 +   pulumi:pulumi:Stack  another-one-dev  create     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (another-one-dev):
    error: preview failed: failed to validate provider config: Could not automatically download and install resource plugin 'pulumi-resource-AWS'at version v5.18.0, install the plugin using `pulumi plugin install resource AWS v5.18.0`.
    Underlying error: error downloading plugin AWS to file: failed to download plugin: AWS-5.18.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-AWS-v5.18.0-darwin-arm64.tar.gz
```

However if I run `pulumi plugin install resource AWS v5.18.0` it seems to run successfully and the AWS plugin is listed as installed when I run `pulumi about`.

### Steps to reproduce

I don't know if this bug might be reproduced. Have a M1 MacBook Pro, install Pulumi using the official homebrew tap, start a new project usign`pulumi new`, attempt to import an AWS ressource.

### Expected Behavior

I expect the `pulumi import` command to run succesfully.

### Actual Behavior

The `pulumi import` command fails with this error:
```
Diagnostics:
  pulumi:pulumi:Stack (another-one-dev):
    error: preview failed: failed to validate provider config: Could not automatically download and install resource plugin 'pulumi-resource-AWS'at version v5.18.0, install the plugin using `pulumi plugin install resource AWS v5.18.0`.
    Underlying error: error downloading plugin AWS to file: failed to download plugin: AWS-5.18.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-AWS-v5.18.0-darwin-arm64.tar.gz
```

### Output of `pulumi about`

```
CLI          
Version      3.43.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.18.0
python  unknown

Host     
OS       darwin
Version  12.6
Arch     arm64

This project is written in python: executable='/Library/Frameworks/Python.framework/Versions/3.10/bin/python3' version='3.10.8
'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/iulspop
User           iulspop
Organizations  iulspop

Dependencies:
NAME        VERSION
pip         22.3.0
pulumi-aws  5.18.0
setuptools  65.5.0
wheel       0.37.1
```

### Additional context

I found the troubleshooting [403 error fetching plugin](https://www.pulumi.com/docs/support/troubleshooting/#403-error-fetching-plugin) page and I followed the steps, but they didn't help. In this case, I just started the project so the provider version is already at the latest. In fact, the plugin is listed as installed at the correct version when I run `pulumi about` and version `5.18.0` of the `aws` plugin supports arm64. So I think this must be some other sort of problem.

I tried uninstalling Pulumi, deleting my projects, deleting the `.pulumi` folder and starting again. This time I ran `pulumi up` after I started the template project and it worked in both Python and Typescript. However when I ran `pulumi import` again I got the same error as above.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> pulumi-resource-AWS

That all capitals AWS is very suspicious, it should be lowercase.

**Comment by iulspop** [comment]
I realized my mistake. I was using the resource type listed in AWS CloudFormation `AWS::SNS::Topic` instead of the [Pulumi resource type for SNS topic](https://www.pulumi.com/registry/packages/aws/api-docs/sns/topic/#import) `aws:sns/topic:Topic`. Unrelated to unexpected error, but I also was using the AWS logical id for the resource instead of the physical id.

My initial command:
```
pulumi import AWS::SNS::Topic x-dev-drip-welcome-sns xdevdripwelcomesnsE0E1B83B
```

Corrected command:
```
pulumi import aws:sns/topic:Topic x-dev-drip-welcome-sns arn:aws:sns:us-east-1:298719980197:x-dev-drip-welcome-user-stack-xdevdripwelcomesnsE0E1B83B-T2HA5FclhJIn
```

Now the import preview ran successfully!

**Comment by iulspop** [comment]
The current behavior is explained in the [`pulumi import` CLI commmand reference](https://www.pulumi.com/docs/reference/cli/pulumi_import/#:~:text=If%20a%20resource%20does%20not%20specify%20a%20provider%2C%20it%20will%20be%20imported%20using%20the%20default%20provider%20for%20its%20type.): "If a resource does not specify a provider, it will be imported using the default provider for its type". Since the resource type started with `AWS`, it attempted to download that provider, but failed since it doesn't exist.

I suppose we can close my bug issue, since it's not a bug. But I want to recommend two changes. 

One, I recommend somehow improving the error message. Either check if the type is valid and point me to API reference to find the correct type, or let me know that the provider doesn't exist. The 403 error did not help me understand my mistake.

Second, this is my first time using Pulumi and I was following along the [importing infrastructure](https://www.pulumi.com/docs/guides/adopting/import/) page. Neither it, nor the [`pulumi import` CLI commmand reference](https://www.pulumi.com/docs/reference/cli/pulumi_import/), explained explained the type was a special type you find in the API reference for your provider for that resource. I had to infer that from the examples and it took a while to click. If somehow that detail can be made clearer, than that would improve the documentation.

Should I open another issue on this repo for the first suggestion? I'll post an issue to improve the documentation in the `pulumi-hugo` repo.

**Comment by RobbieMcKinstry** [comment]
Hi @iulspop . Very glad you figured out the issue, and much appreciated for following up!

> Should I open another issue on this repo for the first suggestion?

Yes please, if you don't mind, could you open a new issue on this repo for the suggestion about improving the error message? That will definitely help us better organize it with similar issues about poor error messages :) 

> I'll post an issue to improve the documentation in the pulumi-hugo repo.

✨  Thank you very much! ✨
