### ISSUE TITLE
Allow STDIN to change passphrase 

### ISSUE THREAD

**Issue by mrlnstpn** [pulumi/pulumi#11083]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Can you allow STDIN in changing the pulumi config passphrase?

`tux@pc:~/Platform$ echo "wasdwasd" | pulumi stack change-secrets-provider passphrase --non-interactive
error: passphrase rotation requires an interactive terminal`

`tux@pc:~/Platform$ bash -x rotate.sh
DEFAULT_PASSPHRASE=ILgR6JPuhlqTy1NB6hNvnGAg/XM7p7Eg9nC6adAA0buQYsZMCZmTbc8QuLC8u3Wb
echo ILgR6JPuhlqTy1NB6hNvnGAg/XM7p7Eg9nC6adAA0buQYsZMCZmTbc8QuLC8u3Wb
pulumi stack change-secrets-provider passphrase --non-interactive
error: passphrase rotation requires an interactive terminal`

`tux@pc:~/Platform$ cat rotate.sh
#!/bin/bash
DEFAULT_PASSPHRASE=${PULUMI_CONFIG_PASSPHRASE:-default}
echo $DEFAULT_PASSPHRASE | pulumi stack change-secrets-provider passphrase --non-interactive`

https://github.com/pulumi/pulumi/blob/10dd3d09233fb7cfd9688ef8305add0203002615/pkg/secrets/passphrase/manager.go#L228

**Comment by RobbieMcKinstry** [comment]
Hi @mrlnstpn, thanks for the tip. #11094 looks pretty good, so I suspect we'll have this out with the next release on Wednesday.

**Comment by RobbieMcKinstry** [comment]
🚀 Hurray! Very glad this shipped! :D
