### ISSUE TITLE
CI Failing on "Install Python deps"

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#11088]
Tracking an upstream issue here: https://github.com/pypa/pypi-support/issues/2312

The error logs seem to indicate that files.pythonhosted.org is unreachable. From [a recent job that failed](https://github.com/pulumi/pulumi/actions/runs/3283698078/jobs/5408860463#step:15:30): 

> Run python -m pip install --upgrade pip requests wheel urllib3 chardet
> Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages (22.2.2)
> Collecting pip
>   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2d07c9ed00>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/47/ef/8b5470b5b94b36231ed9c0bde90caa71c0d4322d4a15f009b2b7f4287fe0/pip-22.3-py3-none-any.whl
>   WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2d07cc7a60>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/47/ef/8b5470b5b94b36231ed9c0bde90caa71c0d4322d4a15f009b2b7f4287fe0/pip-22.3-py3-none-any.whl
>   WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2d07af8280>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/47/ef/8b5470b5b94b36231ed9c0bde90caa71c0d4322d4a15f009b2b7f4287fe0/pip-22.3-py3-none-any.whl
>   WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2d07af84[30](https://github.com/pulumi/pulumi/actions/runs/3283698078/jobs/5408860463#step:15:31)>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/47/ef/8b5470b5b94b362[31](https://github.com/pulumi/pulumi/actions/runs/3283698078/jobs/5408860463#step:15:32)ed9c0bde90caa71c0d4[32](https://github.com/pulumi/pulumi/actions/runs/3283698078/jobs/5408860463#step:15:33)2d4a15f009b2b7f4287fe0/pip-22.3-py3-none-any.whl
>   WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2d07af8610>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /packages/47/ef/8b5470b5b94b[36](https://github.com/pulumi/pulumi/actions/runs/3283698078/jobs/5408860463#step:15:37)231ed9c0bde90caa71c0d4322d4a15f009b2b7f4287fe0/pip-22.3-py3-none-any.whl
> ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/47/ef/8b5470b5b94b36231ed9c0bde90caa71c0d4322d4a15f009b2b7f4287fe0/pip-22.3-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f2d07af87f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by AaronFriel** [comment]
Possibly related: https://twitter.com/AS36459/status/1582728252199964672

GitHub is trialing IPv6 support. Are some GitHub Actions jobs running on IPv6 hosts?

**Comment by guineveresaenger** [comment]
Hit this today in https://github.com/pulumi/pulumi-docker/actions/runs/3465176510/jobs/5787674014.

**Comment by justinvp** [comment]
Closing as No Repro. Haven't seen this in a long time.
