### ISSUE TITLE
Using `--tracing file:somelog.log` and a Policy pack enabled causes Python to fail

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#11092]
### What happened?

I have a Pulumi app (Python) and a Policy pack (Python) associated to my project/stack. When I run `pulumi preview --tracing file:pulumi-log.txt`, Python crashes with the output below

```
Previewing update (case-1853)

View Live: https://app.pulumi.com/menfin/zendesk/case-1853/previews/4da5c6d1-1c78-4dd5-9e4a-70e34fb7ccd5

     Type                 Name               Plan     Info
     pulumi:pulumi:Stack  zendesk-case-1853           9 messages
 
Diagnostics:
  pulumi:pulumi:Stack (zendesk-case-1853):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/aureq/.pulumi/policies/menfin/pulumi-analyzer-85a9d4ba-99b7-402d-b88f-f9e4a88a19ca-v0.0.1/venv/lib/python3.9/site-packages/pulumi/policy/__main__.py", line 61, in main
        runpy.run_path(program, run_name="__main__")
      File "/usr/local/lib/python3.9/runpy.py", line 287, in run_path
        code, fname = _get_code_from_file(run_name, path_name)
      File "/usr/local/lib/python3.9/runpy.py", line 252, in _get_code_from_file
        with io.open_code(decoded_path) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/aureq/.pulumi/policies/menfin/pulumi-analyzer-85a9d4ba-99b7-402d-b88f-f9e4a88a19ca-v0.0.1/tcp:/127.0.0.1:32933'
 
error: policy pack "85a9d4ba-99b7-402d-b88f-f9e4a88a19ca" failed to start: could not read plugin [/usr/local/bin/pulumi-analyzer-policy-python] stdout: EOF
```

### Steps to reproduce

1. create a new python based pulumi app (I used the `aws-python` template)
2. create a new policy pack for Python (I use the one provided by `pulumi policy new`)
3. publish your policy pack, create a policy group, add the stack and the pack to the policy group
4. run `pulumi preview --tracing file:pulumi-log.txt`

### Expected Behavior

The policy pack should be evaluated correctly and the tracefile should be saved.

### Actual Behavior

Python crashes

### Output of `pulumi about`

```
CLI          
Version      3.43.1
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     4.38.1
python  unknown

Host     
OS       debian
Version  11.5
Arch     x86_64

This project is written in python: executable='/home/aureq/work/customers/zendesk/1853/venv/bin/python3' version='3.9.14
'

Current Stack: case-1853

Found no resources associated with case-1853

Found no pending operations associated with case-1853

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, demo, pulumi

Dependencies:
NAME           VERSION
pip            22.3.0
pulumi-aws     4.38.1
pulumi-policy  1.5.0
setuptools     65.5.0
wheel          0.37.1
```

### Additional context

This was initially reported by a customer over Zendesk. They noticed the issue through a Gitlab CI/CD pipeline (container image: `pulumi/pulumi`) which I was able to reproduce. Though, I'm able to reproduce the issue in my sandbox (running on k8s) as well.

The problem only occurs when a policy pack is enabled *and* when using `--tracing file:...`

Any affected users shouldn't need `--tracing` and instead should use `--verbose 9 --logtostderr` instead as this is the most likely outcome they'd want.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Hiya Aurel! This ticket is #<span></span>2 on my list to look at tomorrow morning. 👍🏻

**Comment by aureq** [comment]
@RobbieMcKinstry you're amazing ! Thanks a lot.

**Comment by RobbieMcKinstry** [comment]
Agh! Sorry, I didn't get to this while on Ops rotation; I had a different fire to fight :-(
Looking at this now, this line stands out:
```
    FileNotFoundError: [Errno 2] No such file or directory: '/home/aureq/.pulumi/policies/menfin/pulumi-analyzer-85a9d4ba-99b7-402d-b88f-f9e4a88a19ca-v0.0.1/tcp:/127.0.0.1:32933'
```

Notably, the filepath `/home/aureq/.pulumi/policies/menfin/pulumi-analyzer-85a9d4ba-99b7-402d-b88f-f9e4a88a19ca-v0.0.1/tcp:/127.0.0.1:32933` is the concatenation of the tracing URI and an actual filepath. (When the `file` protocol is used with `--tracing`, the engine spins up a Zipkin server on a random port to aggregate traces from child processes, so the port `32933` is the tracing URL as seen by child processes like the Python runtime and the policy pack server.)

I'd bet there's a missing newline character written to STDIN. It looks like the missing newline character means we write the filepath followed by the tracing URI, smashing them together.

**Comment by RobbieMcKinstry** [comment]
The [offending variable](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/policy/__main__.py#L35) is passed in when the CLI arguments are constructed, and used [here](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/policy/__main__.py#L61) as per the stack trace.

**Comment by RobbieMcKinstry** [comment]
I'm not sure where the code is that launches the policy server process, but it might be an easy fix if it's really just a missing newline.

**Comment by ringods** [comment]
The cause of the crash is due to the use of positional arguments in `pulumi-analyzer-policy-python` here:

https://github.com/pulumi/pulumi/blob/576ff5023a450930c4f59e1c481dc11282f8f6bb/sdk/python/dist/pulumi-analyzer-policy-python#L35

and here:

https://github.com/pulumi/pulumi/blob/576ff5023a450930c4f59e1c481dc11282f8f6bb/sdk/python/dist/pulumi-analyzer-policy-python#L51

When not using log or tracing arguments, the arguments passed to the script are of the form:

`127.0.0.1:62496 . -virtualenv=venv`

When using log or tracing arguments, they get prepended by `buildPluginArguments` ([link](https://github.com/pulumi/pulumi/blob/d0638d8c33f28f05479dc74c9ade15cc991bea15/sdk/go/common/resource/plugin/plugin.go#L436)):

`--logtostderr -v=9 --tracing tcp://127.0.0.1:62494 127.0.0.1:62496 . -virtualenv=venv`

I tried updating `buildPluginArguments` so these flags are no longer prepended, but then it fails in reading the resource plugins.
