### ISSUE TITLE
Python Automation API returns CommandError Exception instead of the more specific ConcurrentUpdateError

### ISSUE THREAD

**Issue by drf7** [pulumi/pulumi#11108]
### What happened?

When there is already an update in progress in a stack the exception thrown when trying another update is the generic exception `CommandError` instead of the more specific one `ConcurrentUpdateError`.

This is because the stderr from pulumi is `error: the stack is currently locked by` but the error defined in the pulumi code is `[409] Conflict: Another update is currently in progress.` here: https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/automation/errors.py#L70

So changing the line 70 from:
`conflict_text = "[409] Conflict: Another update is currently in progress."`
To:
`conflict_text = "error: the stack is currently locked by"`
Seems to fix this error for me.

### Steps to reproduce

Execute a pulumi up in a stack that has already an update in progress using the python automation API

### Expected Behavior

`ConcurrentUpdateError` exception is thrown

### Actual Behavior

`CommandError` exception is thrown

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi there @drf7 thanks a lot for reporting this issue and for the suggested fix 🙏 it looks like the conflict error we search for in stderr is not from the local backend so I've addressed this in #11146 such that this text also resolves to `ConcurrentUpdateError` and not the generic `CommandError`

**Comment by drf7** [comment]
Hi @Zaid-Ajaj thanks for fixing it, by local backend you mean anything other than the self-hosted Pulumi Service? So if I were using the self-hosted Pulumi Service I wouldn't have run into this error?

**Comment by Zaid-Ajaj** [comment]
@drf7 The local backend is when you use your local file system to store state. Pulumi supports multiple backends including our own Pulumi Service to store state. Unfortunately, regardless of which backend you use, there is still a change you encounter a concurrent update error. There is an issue https://github.com/pulumi/pulumi/issues/9047 open to help improve the situation

**Comment by drf7** [comment]
@Zaid-Ajaj I encounter this issue using local file system as backend but also using Azure Blob Storage as backend (so it is not only happening in the local file system as backend). But your PR should address both situations so everything is fine, just wanted to clarify that.
