### ISSUE TITLE
StackSettingsConfigValueYamlConverter does not support arrays

### ISSUE THREAD

**Issue by ffMathy** [pulumi/pulumi#11107]
### What happened?

I am trying to create a `LocalWorkspace` and use the settings from another existing `Pulumi.stack.yaml` file into this local workspace.

However, one of the settings has an array value. And when the `LocalWorkspace` then tries to deserialize that value, it fails because the `StackSettingsConfigValueYamlConverter` throws an exception if an array is encountered. It should be gracefully ignored.

### Steps to reproduce

```csharp
var iacWorkspace = await LocalWorkspace.CreateAsync(
    new InlineProgramArgs(
        "some-project-name",
        "some-stack",
        pulumiStack)
    {
        WorkDir = someProjectPath
    },
    cancellationToken);

var settings = await iacWorkspace.GetStackSettingsAsync("some-stack", cancellationToken);
//throws exception
```

With the following stack config:

```yaml
config:
  aws:allowedAccountIds:
  - 1337
```

### Expected Behavior

The array value is skipped during deserialization.

### Actual Behavior

> Unable to deserialize [Pulumi.Automation.StackSettingsConfigValue]. Expecting object if not plain string.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi @ffMathy thanks a lot for filing the issue! I've been able to reproduce the problem and it was indeed far from ideal to throw an exception. I think that gracefully ignoring the value isn't enough as a solution so I've opened #11143 where we will JSON-ify the contents of the complex objects into the value of `StackSettingsConfigValue` so consumers can still access it.
