### ISSUE TITLE
Duplicate outputs not supported

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#11133]
### What happened?

I defined a Pulumi program with two outputs that use the same ID. Only one property has outputs

### Steps to reproduce

import pulumi
from pulumi_aws import s3

bucket = s3.Bucket('my-bucket')
pulumi.export('my-bucket', bucket.id)
pulumi.export('duplicate-output', bucket.id)

### Expected Behavior

I should see two outputs:

`my-bucket`
`duplicate-output`

### Actual Behavior

I only see `my-bucket` populated

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi @jaxxstorm, this definitely looks weird! I've been able to reproduce it in python but not in csharp, go or typescript which means the problem is most-likely in the core python SDK

**Comment by Frassle** [comment]
Yeh see the `massage` function in sdk/python/lib/pulumi/runtime/stack.py it skips values that it's seen before in an attempt to not create cycles, but the way it currently works means it also drops side-by-side duplicate values.

**Comment by mikhailshilkov** [comment]
@kpitzen Can we take it to your Python Improvements epic?
