### ISSUE TITLE
Homebrew tap not working on MacOS Big Sur

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi#11152]
### What happened?

I was trying to be a good citizen and upgrade to the latest pulumi version using brew.

Series of events:

```
$ brew upgrade pulumi
==> Upgrading 1 outdated package:
pulumi/tap/pulumi 3.43.1 -> 3.44.1
==> Downloading https://github.com/pulumi/pulumi/releases/download/v3.44.1/pulum
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################## 100.0%
==> Upgrading pulumi/tap/pulumi
  3.43.1 -> 3.44.1 
Error: Failure while executing; `/usr/local/Cellar/pulumi/3.44.1/bin/pulumi\ gen-completion\ bash` was terminated by uncaught signal ABRT. Here's the output:
```
<NB: the output is empty>
```
brew install pulumi/tap/pulumi
==> Downloading https://github.com/pulumi/pulumi/releases/download/v3.44.1/pulum
Already downloaded: /Users/guin/Library/Caches/Homebrew/downloads/197e14bb9b01638f07be0b7aa9d269b034602c5d301bfe89fe78731edff046e6--pulumi-v3.44.1-darwin-x64.tar.gz
==> Installing pulumi from pulumi/tap
Error: Failure while executing; `/usr/local/Cellar/pulumi/3.44.1/bin/pulumi\ gen-completion\ bash` was terminated by uncaught signal ABRT. Here's the output:
```
<NB: the output is empty>
```
brew install pulumi/tap/pulumi
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and pulumi/tap).

You have 32 outdated formulae and 2 outdated casks installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Downloading https://github.com/pulumi/pulumi/releases/download/v3.44.1/pulum
Already downloaded: /Users/guin/Library/Caches/Homebrew/downloads/197e14bb9b01638f07be0b7aa9d269b034602c5d301bfe89fe78731edff046e6--pulumi-v3.44.1-darwin-x64.tar.gz
==> Installing pulumi from pulumi/tap
Error: Failure while executing; `/usr/local/Cellar/pulumi/3.44.1/bin/pulumi\ gen-completion\ bash` was terminated by uncaught signal ABRT. Here's the output:
```
<NB: the output is still empty>
```
brew outdated
pulumi/tap/pulumi (3.43.1) < 3.44.1
# others elided
```
Trying a general upgrade:
```
brew upgrade
==> Upgrading 32 outdated packages:
# ...
==> Upgrading pulumi/tap/pulumi
  3.43.1 -> 3.44.1 

Error: Failure while executing; `/usr/local/Cellar/pulumi/3.44.1/bin/pulumi\ gen-completion\ bash` was terminated by uncaught signal ABRT. Here's the output:
```
Building pulumi/pulumi from scratch using the `sdk/v3.44.1` tag works:
```
@guin:~🦉 pulumi about
CLI          
Version      3.44.1-dev.0
Go Version   go1.18.7
Go Compiler  gc
```
and running the `gen-completion` script:
```
/Users/guin/go/bin/pulumi gen-completion bash
# bash completion for pulumi                               -*- shell-script -*-

__pulumi_debug()
{
    if [[ -n ${BASH_COMP_DEBUG_FILE:-} ]]; then
        echo "$*" >> "${BASH_COMP_DEBUG_FILE}"
    fi
}
# more lines
```
Downloading the [relevant binary](https://github.com/pulumi/pulumi/releases/download/v3.44.1/pulumi-v3.44.1-darwin-x64.tar.gz) and trying to run `./pulumi` from there like so:
```
@guin:pulumi:owl: ./pulumi
Killed: 9
@guin:pulumi:owl: pwd
/Users/guin/Downloads/pulumi
@guin:pulumi:owl: 
```
results in this:
<img width="252" alt="Screen Shot 2022-10-25 at 3 14 52 PM" src="https://user-images.githubusercontent.com/13116240/197895714-0e699e68-82e6-449c-b006-642395b02ca0.png">

Following the [_incredibly patronizing_ instructions](https://support.apple.com/en-gb/guide/mac-help/mh40616/mac) to circumvent this popup (which is `sudo` impervious), the following output happens:
```
./pulumi
dyld: Symbol not found: _kIOMainPortDefault
  Referenced from: /Users/guin/Downloads/pulumi/./pulumi (which was built for Mac OS X 12.0)
  Expected in: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
 in /Users/guin/Downloads/pulumi/./pulumi
Abort trap: 6
```

### Steps to reproduce

Unclear - seems to be OS dependent. I am on Big Sur 11.6.

### Expected Behavior

Pulumi upgrade.

### Actual Behavior

Homebrew errors with ABRT signal

### Output of `pulumi about`

Only giving system outputs here.

```
Host     
OS       darwin
Version  11.6
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rdonkin** [comment]
I had the same issue yesterday, also on 11.6 Big Sur.  Installing 3.43.1 outside brew worked OK.  I didn't get the pop-up, but everything else was the same.  Clearly Pulumi 3.44.0 only supports macOS 12 Monterey or higher - perhaps triggered but 

This took a while to debug as there was no helpful output

Suggestions

- some output from the brew formula's script hinting at checking the supported version.
- clear mention in the Changelog that certain macOS versions are no longer supported, when this support is removed - I didn't see any references to this
- some warning that a macOS version will not be supported before it happens - perhaps a clear end of support policy statement in the docs

**Comment by Frassle** [comment]
> clear mention in the Changelog that certain macOS versions are no longer supported

Dropping support for this was _not_ intentional. This is a p0 bug that we are looking to rectify immediately.

**Comment by Frassle** [comment]
Downloading the darwin-x64 files from the latest release:
```
otool -l pulumi/pulumi | grep -A 3 min
    minos 12.0
      sdk 12.3
   ntools 1
     tool 3
```

So yup minos is now set to 12.0 not 11.0. That's the same for 3.44.1 and 3.44.0, but 3.43.1 has:
```
    minos 11.0
      sdk 12.1
   ntools 1
     tool 3
```

So something changed between the 15th and the 24th. It's awfully suspect that Ventura (macos-13) released on the 24th.
