### ISSUE TITLE
Escape yaml string characters in `Pulumi new`

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#11161]
### What happened?

The following command throws an error: 
`pulumi new "aws-python" -d ":" -n "x"`

```
error: failed to load Pulumi project located at "Pulumi.yaml": could not unmarshal 'Pulumi.yaml': invalid YAML file: yaml: line 2: mapping values are not allowed in this context
```

### Steps to reproduce

1. `pulumi new "aws-python" -d ":" -n "x"`

### Expected Behavior

It should properly escape the `:` and other yaml chars

### Actual Behavior

It raised the error above. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi @rshade it looks like we need to sanitize or escape the user input around [these lines](https://github.com/pulumi/pulumi/blob/master/pkg/cmd/pulumi/new.go#L269-L278) during `pulumi new` not only for `:` but any YAML character that needs escaping
