### ISSUE TITLE
Add Support for Fly.io

### ISSUE THREAD

**Issue by malkoG** [pulumi/pulumi#11191]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I want to try flyio provider

https://github.com/fly-apps/terraform-provider-fly

### Affected area/feature

Terraform bridge

**Comment by iwahbe** [comment]
Hi @malkoG. Thanks for bringing this up. I don't believe that Fly.io is on our product roadmap, but you could bridge it yourself using [our TF-bridged provider boilerplate](https://github.com/pulumi/pulumi-tf-provider-boilerplate)!

**Comment by dirien** [comment]
Hey @malkoG,

I bridged the provider, as part of the community created providers here: https://github.com/dirien/pulumi-fly

Hope it helps you!
