### ISSUE TITLE
`pulumi destroy --remove` removes the stack, but not the stack config

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi#11198]
### What happened?

I'm assuming this is a bug, but if it's by design, feel free to close. However it does seem inconsistent that when I run this:

```bash
$ pulumi new aws-yaml --yes && pulumi up --yes && pulumi destroy --yes && pulumi stack rm --yes
```

.. the stack file gets deleted:

```
$ ls
Pulumi.yaml
```

.. whereas when I run this:

```bash
$ pulumi new aws-yaml --yes && pulumi up --yes && pulumi destroy --yes --remove
```

.. the stack file's still there:

```
$ ls 
Pulumi.dev.yaml Pulumi.yaml
```

Seems like we should delete `Pulumi.dev.yaml` in the `--remove` case as well. 

Also worth noting after running `--remove`, you can't run `pulumi stack rm` to delete the config file as you normally might (since of course, the stack no longer exists), so you have to `rm` the file manually to get rid of it.

### Steps to reproduce

See above.

### Expected Behavior

The stack file is also deleted.

### Actual Behavior

The stack file still exists after `destroy --remove` completes successfully.

### Output of `pulumi about`

```
CLI
Version      3.45.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME  VERSION
aws   unknown
yaml  unknown

Host
OS       darwin
Version  12.5.1
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
I think it's probably more of an oversight than a design choice. I'll mark it as an enhancement rather than a bug. It should be fairly straightforward to implement.

PR that introduced `pulumi destroy --remove`
https://github.com/pulumi/pulumi/pull/10943

**Comment by heagma** [comment]
I'll work on this. Could you please assign it. @dixler

**Comment by heagma** [comment]
@Frassle Could you review it and see if it's ready to merge  ?
