### ISSUE TITLE
internal client error: Protocol error

### ISSUE THREAD

**Issue by bingtsingw** [pulumi/pulumi#11210]
### What happened?

errors on `pulumi update`

### Steps to reproduce

I created a minimal repo to reproduce this issue: https://github.com/bingtsingw/reproduce-pulumi-protocol-error

### Expected Behavior

checkout to brach `v3.35.2`, install npm packages and run `pulumi update`, this is the worked expected behavior

### Actual Behavior

checkout to `main` or `v3.35.3` brach, install npm packages and run `pulumi update`, this shows the error

```
     Type                 Name                   Plan       Info
 +   pulumi:pulumi:Stack  pulumi-bug-replay-dev  create     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (pulumi-bug-replay-dev):
    error: Running program '/Users/bingtsingw/code/playground/pulumi-bug-replay' failed with an unhandled exception:
    Error: failed to register new resource pulumi-bug-replay-dev [pulumi:pulumi:Stack]: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
        at Object.registerResource (/Users/bingtsingw/code/playground/pulumi-bug-replay/node_modules/.pnpm/@pulumi+pulumi@3.35.3/node_modules/@pulumi/runtime/resource.ts:292:27)
        at new Resource (/Users/bingtsingw/code/playground/pulumi-bug-replay/node_modules/.pnpm/@pulumi+pulumi@3.35.3/node_modules/@pulumi/resource.ts:400:13)
        at new ComponentResource (/Users/bingtsingw/code/playground/pulumi-bug-replay/node_modules/.pnpm/@pulumi+pulumi@3.35.3/node_modules/@pulumi/resource.ts:888:9)
        at new Stack (/Users/bingtsingw/code/playground/pulumi-bug-replay/node_modules/.pnpm/@pulumi+pulumi@3.35.3/node_modules/@pulumi/runtime/stack.ts:67:9)
        at Object.runInPulumiStack (/Users/bingtsingw/code/playground/pulumi-bug-replay/node_modules/.pnpm/@pulumi+pulumi@3.35.3/node_modules/@pulumi/runtime/stack.ts:45:23)
        at Object.run (/Users/bingtsingw/code/playground/pulumi-bug-replay/node_modules/.pnpm/@pulumi+pulumi@3.35.3/node_modules/@pulumi/cmd/run/run.ts:373:20)
        at /Users/bingtsingw/code/playground/pulumi-bug-replay/node_modules/.pnpm/@pulumi+pulumi@3.35.3/node_modules/@pulumi/cmd/run/index.ts:160:57
```

### Additional context

I test a lot of versions, and found that `3.35.2` is the last worked version.
The code compare(https://github.com/pulumi/pulumi/compare/v3.35.2...v3.35.3) shows that version 3.35.3 changes `node/runtime/resource.ts`, and the error message is thrown by this file.

Hope this could provide some clues to solve the problem.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Thanks for filing. It appears your pulumi program is referencing a newer typescript SDK version. I ran the example repository using latest (3.45.0) and didn't run into this bug. We recommend upgrading the CLI to the latest version.

I hope this resolves your issue!

If you're in an environment where you're unable to upgrade your CLI version, you can try downgrading your Pulumi program's SDK version and see if that resolves your issue, but this is sub-optimal.

**Comment by bingtsingw** [comment]
> Thanks for filing. It appears your pulumi program is referencing a newer typescript SDK version. I ran the example repository using latest (3.45.0) and didn't run into this bug. We recommend upgrading the CLI to the latest version.
> 
> I hope this resolves your issue!
> 
> If you're in an environment where you're unable to upgrade your CLI version, you can try downgrading your Pulumi program's SDK version and see if that resolves your issue, but this is sub-optimal.
> 
> edit: I notice that your repository includes `3.45.0` in the package.json, but your output says `3.35.3` was this unintentional?

Thank you for your testing, but your results are different from mine, that is strange
I have three branches in this repo,
The `main` branch with cli version `3.45.0`: not work
The `v3.35.3` branch with cli version `3.35.3`: not work
The `v3.35.2` branch with cli version `3.35.2`: work

**Comment by bingtsingw** [comment]
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/10382462/199373977-4067f2fb-ee3c-4b3a-882a-394cad611aad.png">

**Comment by bingtsingw** [comment]
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/10382462/199374062-0fe50150-df69-477a-bed1-e64de7e4878a.png">

**Comment by iwahbe** [comment]
Thanks for all the information! Unfortunately, we were unable to reproduce the error on your test repo. I noticed that you are using `pnpm`. Do you get the same error using `npm`?
