### ISSUE TITLE
--config-file argument alters the referenced config file adding unintended vars and encryption

### ISSUE THREAD

**Issue by ryanpodonnell1** [pulumi/pulumi#11220]
Hello! 👋 

pulumi version: `v3.45.0`

When I initialize a stack I pass in a referenced `config-file` during the preview/up operations. The intent is to have a shared config file that can be passed into any stack as just an external file (similar to a tfvars.json in terraform).  

When I do this however an `encryptionsalt` is added to the config file forcing me to use `PULUMI_CONFIG_PASSPHRASE` when it should be using the provided kms key during stack creation. This is confusing/incovenient for end users of the repo as it should be transparent with the kms key. 

Steps:

1. Create Stack which creates `Pulumi.dev.yaml`

```sh
pulumi stack init dev
--secrets-provider "awskms:///arn:aws:kms:....." \
--non-interactive 
```

2. contents of `config-sbx.yaml` before `pulumi up`

```yaml
config:
  aws:region: us-west-2
  aws:skipCredentialsValidation: "true"
  aws:useFipsEndpoint: "false"
  infra:use_vpc_config: "false"
```

3. First issue: Run `Pulumi up` even though a KMS secrets provider is set from the init. Confirmed `Pulumi.dev.yaml` file does have the secretsprovider and encryptedkey set.

Pulumi.dev.yaml
```yaml
secretsprovider: awskms:///arn:aws:kms:.......
encryptedkey: AQICAHgo7BVtobVMmFbANKm53VrwtqsxtKeUqM8UXOs+NdOePgH+2VT13j0eizmwrHbam9IkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM45wJ55J1GbR/QDqHAgEQgDv2GBnKsHF0WY+lwW3sOMERKbDaGdgnlwUvNdVf1JyJbzrexmt/rCY50xQuT0PCy2ofCGUYRDcnhaTaHg==
```

```sh
pulumi up -y -s dev  -c "env:tier="dev" --non-interactive --config-file config-sbx.yaml

error: getting secrets manager: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables
```

5. Set `PULUMI_CONFIG_PASSPHRASE` to `""`. `pulumi up` proceeds

  6. Second issue: After successful `pulumi up` an encryption salt is added to the referenced config file as well as the "env:tier" config setting 
  
  contents of `config-sbx.yaml` after:
  
  ```yaml
  encryptionsalt: v1:zr+GvV3nGv8=:v1:zJxDQumFZGUQFeBu:540J59zx1hnfGQvD8luNHbAuSNe/NQ==
  config:
    aws:region: us-west-2
    env:tier: dev
    aws:skipCredentialsValidation: "true"
    aws:useFipsEndpoint: "false"
    infra:use_vpc_config: "false"
  ```

7. interacting with stacks now requires other users entering a passphrase or setting `PULUMI_CONFIG_PASSPHRASE=""`. This is a bit different than using the stacks directly (without --config-file) where a kms secrets provider is configured. The extra step of using the passphrase is not required. I believe this is because `pulumi` adds the salt to the external config file which the dev stack references. 

    Also the adding of `env:tier` to the referenced config file makes this a bit confusing as that variable should only be associated with the stack `Pulumi.dev.yaml` making the shared config file a little less trustworthy. 

10. Ideally `--config-file <file>` should be identical as enumerating the keys individually.

   pulumi up -s dev --config-file <file>.yaml

  ```yaml
  config:
    aws:region: us-west-2
    aws:skipCredentialsValidation: "true"
    aws:useFipsEndpoint: "false"
    infra:use_vpc_config: "false"
  ```

  should be identical to:
  
  ```
  pulumi up -s dev -c "aws:region=us-west-2" -c "aws:skipCredentialsValidation=true" -c "aws:useFipsEndpoint=false" -c infra:use_vpc_config: false"
  ```
  
  the referenced --config-file should be immutable during a Pulumi operation.

**Comment by Frassle** [comment]
I think you've misunderstood what the ``-config-file` option is supposed to be for.
```
--config-file string                    Use the configuration values in the specified file rather than detecting the file name
```
It simply tells pulumi to use the given file for config, rather than working out the file by stack name and loading that.
So `--config-file=config-sbx.yml` is only loading "config-sbx.yml" rather than "Pulumi.dev.yaml" and "config-sbc.yml".

However we've just released the first part of project level configuration which lets you simple set these values in the Pulumi.yaml instead. See the blog post about it at https://www.pulumi.com/blog/project-config-mvp/.
