### ISSUE TITLE
register_resource_outputs error

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#11227]
### What happened?

In the process of bringing up a stack with a component I get the following error:
```
 for k in inputs:
    TypeError: 'NoneType' object is not iterable

    exception calling callback for <Future at 0x10a1380d0 state=finished returned RegisterResourceResponse>
    Traceback (most recent call last):
  ```

### Steps to reproduce

Custom MLC, local reproduction only

### Expected Behavior

It is able to save the stack

### Actual Behavior

It panics on save. 

### Output of `pulumi about`

```
3.43.1
aws            5.18.0
cloudinit      1.3.0
datadog        4.12.0
google-native  0.27.0
kubernetes     3.22.0
python         unknown
random         4.8.2
tls            4.6.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This is the SDK not handling `None` in `register_resource_outputs`, which is typed to not accept None but can be called directly by users, thinking we should be lenient and accept `None` as `{}`.
