### ISSUE TITLE
unable to install the go language plugin manually

### ISSUE THREAD

**Issue by ryanpodonnell1** [pulumi/pulumi#11228]
### What happened?

I am running in an isolated container and need to download/install plugins ahead of time.

I install the aws plugin by running successefully:
`pulumi plugin install resource aws 5.19.0`

I get the error when attempting to run `pulumi preview`

```sh
Previewing update (dev):
 
error: failed to load language plugin go: Could not automatically download and install language plugin 'pulumi-language-go', install the plugin using `pulumi plugin install language go`.
```

I attempt to install the plugin manually to resolve the error:

```sh
error: failed to load language plugin go: Could not automatically download and install language plugin 'pulumi-language-go', install the plugin using `pulumi plugin install language go`.
Underlying error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-go/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```

```
#  pulumi plugin install language go 
error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-go/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
~/.pulumi/plugins # 
```

1. shouldn't pulumi automatically resolve the latest golang plugin release?
2. where can I find the releases for the go plugin?  https://get.pulumi.com/releases/plugins/ just shows access denied

### Steps to reproduce

run :

```
pulumi plugin install language go 
```

### Expected Behavior

go plugin is installed

### Actual Behavior

plugin for go appears not to be found

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
While we call them plugins, the languages aren't _really_ plugins right now. It's on the roadmap to change this.
For the time being you'll need to download a full pulumi release (e.g. https://github.com/pulumi/pulumi/releases/tag/v3.45.0) and grab the "pulumi-language-go" binary from the package in there.
