### ISSUE TITLE
Implement get factory methods for Python

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1123]
We implemented `get` factory methods for resources in JavaScript, to make it possible to fetch state for existing resources by ID, but we did not do the same for Python.  We will want this.

**Comment by swgillespie** [comment]
Moving this out to M21 in the absence of demand.

**Comment by lukehoban** [comment]
We implemented read for Python in https://github.com/pulumi/pulumi/pull/2752, which should unblock rolling out `.get` support to provider SDKs.
