### ISSUE TITLE
Generate sensible Nodejs default dependencies

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#11237]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, every schema has to specify its own set of dependencies for nodejs. If not specified, the following is specified:

```json
    "devDependencies": {
        "typescript": "^4.3.5"
    },
    "peerDependencies": {
        "@pulumi/pulumi": "latest"
    },
```

This is no sufficient to complete the build of the SDK.

1. `@types/node` should be a `devDependency`
2. `@pulumi/pulumi` should be a `dependency` not a `peerDependency` and should target a specific version range based on the minimum SDK features required

The only reason for a provider to override these settings should be to add additional dependencies based on custom overlays (which should be rare). We should also ideally therefore merge the user-specified dependencies with the defaults so that codegen can still controll the version ranges for pulumi and typescript as it starts to use newer features in the future to avoid fragility when adding custom additions.

### Affected area/feature

- nodejs codegen

**Comment by iwahbe** [comment]
I completely agree with (1). I think (2) is more of a gray area. If you do specify `@pulumi/pulumi` as a dep, I don't think we want to give version conflicts.

**Comment by Frassle** [comment]
> custom overlays

Overlays are due to die, so we shouldn't worry about them.

**Comment by danielrbradley** [comment]
Currently, using `peerDependencies`, means that the package will not be installed for the user - they must install it themselves - but it will show a warning if the range doesn't align to the requirements. 

Using `dependencies` will improve the experience by auto-installing pu/pu but also allow us to upgrade pu/pu if we're starting using a new feature from pu/pu. If there's another dependency which requires a different version range of pulumi then that's a valid error which should be surfaced to the user to resolve rather than just printing as a warning. This can  also be overridden by users if desired by using [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/).

A shorterhand version of the range that @Frassle has written is just`"@pulumi/pulumi": "^3.41"`.
