### ISSUE TITLE
Support the type token as an output

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#11240]
Having the type token on an output:

```
certificate.type_token

# returns aws:acm/certificate:Certificate
```

Would be useful in certain situations.

**Comment by iwahbe** [comment]
Could you give a little more context on why this would be useful?

I think of type tokens as implementation details for languages with SDKs, so I'm not super keen on exposing them.

**Comment by Frassle** [comment]
I'm pretty sure @danielrbradley has raised an issue for this before?

**Comment by Frassle** [comment]
Ah might of been Dan last asked for it, but originally raised by Luke: https://github.com/pulumi/pulumi/issues/2754

I think we can close this as a duplicate of that?
