### ISSUE TITLE
<BUG>(NuGet Version badge not working in Readme)

### ISSUE THREAD

**Issue by Arindam200** [pulumi/pulumi#11245]
### What happened?

The `NuGet version badge` in the README file is not working. The previous link is not working correctly that's why the badge is not showing! 

### Steps to reproduce

Replace the broken link with the correct link.

The previous link is not working correctly that's why the badge is not showing! 

### Expected Behavior

![image](https://user-images.githubusercontent.com/109217591/199791660-594447fe-35ae-4f9f-b6f1-4ca2be5ffd6f.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/109217591/199791008-4a0ccf17-8574-4313-ad7b-76f70a6decfe.png)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Thanks for bringing this to our attention. The link is working for me. What browser/os are you using?

**Comment by Arindam200** [comment]
> Thanks for bringing this to our attention. The link is working for me. What browser/os are you using?

Thanks for your kind reply. I'm using Brave browser and the badge isn't working there.what should I do now?

**Comment by Frassle** [comment]
> Brave

I've got someone here using Brave I can ask them to test this and get back if it works for them.

**Comment by Frassle** [comment]
Ok they have Brave browser 1.45.116 and the nuget badge shows up correctly for them. Can you check your browsers developer tools and see if there's anything in the console or network tab that suggests an error?

**Comment by Frassle** [comment]
I'll ask if they can update and test again. Also what OS are you on, windows/Linux/osx?

**Comment by Arindam200** [comment]
> 

I'm in Windows 10 .

**Comment by Arindam200** [comment]
> I'll ask if they can update and test again. Also what OS are you on, windows/Linux/osx?

Thanks . I'm in Windows 10 .

**Comment by Arindam200** [comment]
Hey @Frassle  The Badge is working correctly for me. Should I Close this Issue?


![image](https://user-images.githubusercontent.com/109217591/202192264-9817e4f8-8e21-457c-85b2-56fbbfa3be41.png)

**Comment by iwahbe** [comment]
If it's working for you now, and it seems to be working for everybody else, I think we can close it.

**Comment by Arindam200** [comment]
Thank you for your kind feedback @iwahbe !
