### ISSUE TITLE
CustomResourceOptions.deleteBeforeReplace is not working as expected

### ISSUE THREAD

**Issue by judblackburn** [pulumi/pulumi#11259]
### What happened?

I set `deleteBeforeReplace: true` on a `ClusterCapacityProviders` resource but when running `pulumi up`, Pulumi still tries to create the resource before deleting the old resource on a replacement.

### Steps to reproduce

1. Create a new Pulumi project from the `aws-typescript` template
2. Copy/paste this code in the `index.ts`
    ```ts
    import * as aws from '@pulumi/aws';
    
    const cluster = new aws.ecs.Cluster('playground', {name: 'playground'});
    new aws.ecs.ClusterCapacityProviders(
      'playground',
      {
        clusterName: 'playground',
        capacityProviders: ['FARGATE'],
        defaultCapacityProviderStrategies: [
          {
            base: 1,
            capacityProvider: 'FARGATE',
            weight: 100,
          },
        ],
      },
      {
        dependsOn: cluster,
        deleteBeforeReplace: true,
      }
    );
    ```
3. Run `pulumi up --stack playground`
  1. Pulumi will create the `Cluster` and `ClusterCapacityProviders`
4. Change the `name` parameter of the `ClusterCapacityProviders` from `playground` to `some-other-playground` to cause a replacement
5. Run `pulumi up --stack playground`

Output:
```
Updating (playground):                                                                                                                       
pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:playground::playground::pulumi:pulumi:Stack::playground-playground]                                                        + aws:ecs/clusterCapacityProviders:ClusterCapacityProviders: (create)
        [urn=urn:pulumi:playground::playground::aws:ecs/clusterCapacityProviders:ClusterCapacityProviders::some-other-playground]
        [provider=urn:pulumi:playground::playground::pulumi:providers:aws::default_5_19_0::eafa43b5-43f7-4a0e-8cf3-023963281622]
        capacityProviders                : [
            [0]: "FARGATE"
        ]
        clusterName                      : "playground"
        defaultCapacityProviderStrategies: [
            [0]: {
                base            : 1
                capacityProvider: "FARGATE"
                weight          : 100
            }
        ]                                                                                                                                          
--outputs:--    
        defaultCapacityProviderStrategies: [
            [0]: {
                base            : 1
                capacityProvider: "FARGATE"
                weight          : 100
            }
        ]
        id                               : "playground"                                                                                                
- aws:ecs/clusterCapacityProviders:ClusterCapacityProviders: (delete)
        [id=playground]
        [urn=urn:pulumi:playground::playground::aws:ecs/clusterCapacityProviders:ClusterCapacityProviders::playground]
        [provider=urn:pulumi:playground::playground::pulumi:providers:aws::default_5_19_0::eafa43b5-43f7-4a0e-8cf3-023963281622]
        capacityProviders                : [
            [0]: "FARGATE"
        ]
        clusterName                      : "playground"
        defaultCapacityProviderStrategies: [
            [0]: {
                base            : 1
                capacityProvider: "FARGATE"
                weight          : 100
            }
        ]                                                                                                                                            
--outputs:--  
      - capacityProviders                : [
      -     [0]: "FARGATE"
        ]
      - clusterName                      : "playground"
      - defaultCapacityProviderStrategies: [
      -     [0]: {
              - base            : 1
              - capacityProvider: "FARGATE"
              - weight          : 100
            }
        ]
      - id                               : "playground"                                                                                           
      -  Resources:      
    + 1 created
    - 1 deleted
    2 changes. 2 unchanged

Duration: 25s
```

### Expected Behavior

The existing `ClusterCapacityProviders` named `playground` is deleted, then a new `ClusterCapacityProviders` named `some-other-playground` is created.

### Actual Behavior

Pulumi tries to create the `ClusterCapacityProviders` named `some-other-playground` first which actually fails (even though the console output indicates it succeeded).

Then Pulumi deletes the `ClusterCapacityProviders` named `playground` which leave the `Cluster` without a `ClusterCapacityProviders`.

### Output of `pulumi about`

CLI          
Version      3.46.0
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.19.0
nodejs  unknown

Host     
OS       darwin
Version  12.6
Arch     x86_64

This project is written in nodejs: executable='/Users/jud.blackburn/.asdf/shims/node' version='v16.15.0'

Backend        
Name           mm-blackburnj
URL            s3://rs-pulumi-state-182157423521
User           jud.blackburn
Organizations  

Dependencies:
NAME                VERSION
@pulumi/aws         5.19.0
@pulumi/pulumi      3.46.0
@rs-crossguard/aws  0.1.3
@rs-pulumi/aws      0.23.0
@types/jest         29.2.1
@types/node         18.11.9
gts                 4.0.0
jest                29.2.2
ts-jest             29.0.3
typescript          4.8.4

### Additional context

There are actually 2 problems to solve.

1. Why does the console output show the creation of the `ClusterCapacityProviders` named `some-other-playground` show it succeeded when AWS will prevent it from getting created because it only allows 1 `ClusterCapacityProviders` of a certain type.
2. Why is `deleteBeforeReplace` not being respected.

Thank you for looking into this and I look forward to your response.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> Change the name parameter of the ClusterCapacityProviders from playground to some-other-playground to cause a replacement

Changing the name actually instructs the engine to treat this as a brand new resource. So the engine see this as a brand new resource called "some-other-playground" and a delete of the old resource "playground".

This is because the name is used internally for the engines logical name, and by default for resources physical name. There's some documentation about this at https://www.pulumi.com/docs/intro/concepts/resources/names/.

**Comment by judblackburn** [comment]
@Frassle Thanks for the feedback, I appreciate it.

I agree about the create/delete of the resources and that's expected because, as you said, a name change causes a replacement.

What I didn't expect is the create to come before the delete when I set `deleteBeforeReplace` to `true`.

**Comment by Frassle** [comment]
> I agree about the create/delete of the resources and that's expected because, as you said, a name change causes a replacement.

No that's what's important here. A physical name change causes a replacement, but a logical name change _does not_.
A logical name change is _always_ seen as a new create, it has to be because it's a new logical name and that's what the engine tracks for state. If you want to change the logical name of a resource and not have the engine treat it as a brand new thing you need to use [aliases](https://www.pulumi.com/docs/intro/concepts/resources/options/aliases/). 

ClusterCapacityProviders doesn't actually have a physical name, it being a single item assigned to the cluster itself.

**Comment by judblackburn** [comment]
@Frassle Okay, so what I hear you saying is that a change to logical name means _create_ a new resource NOT _replace_ a resource AND `deleteBeforeReplace` applies only to replacements not creates.  Is that correct?

**Comment by Frassle** [comment]
Correct.

**Comment by Frassle** [comment]
Also I believe your other issue that pulumi said it successfully created the new `ClusterCapacityProviders` is covered by https://github.com/pulumi/pulumi/issues/9925

**Comment by judblackburn** [comment]
@Frassle Yep, that's what we were just discussing.  The idempotency of the AWS API was miss-leading us but it make sense now.  Thanks for the help.  Really appreciate it.

I will close out this issue as it can be referenced from the other open issue.
