### ISSUE TITLE
Switch to Wheel Based Distribution. DEPRECATION: pulumi-kubernetes is being installed using the legacy 'setup.py install' method.

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#11267]
### What happened?

When installing `pulumi-kubernetes` Python module with pip `22.3`, pip complains and displays the following error message.

```
DEPRECATION: pulumi-kubernetes is being installed using the legacy 'setup.py install' method,
because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 
will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' 
option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

### Steps to reproduce

1. `python -m venv venv`
2. `source venv/bin/activate`
3. `pip install -U pip`
4. `pip install pulumi` (no warning)
5. `pip install pulumi-kubernetes` (the above warning is displayed)

### Expected Behavior

The module `pulumi-kubernetes` is installed with no warning displayed.

### Actual Behavior

At the end of the `pulumi-kubernetes` module installation, a warning is displayed.

### Output of `pulumi about`

* `python --version`: Python 3.9.14
* `pip --version`: pip 22.3

### Additional context

This was reported here on our internal [Slack](https://pulumi.slack.com/archives/CUC6W5SMC/p1667345615534719).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Looks like I'm picking this up next in M84. This requires a codegen change to augment `setup.py`, and that change will need to be opt-in. I'll add a feature flag that makes it optional and fork the implementation around the feature flag.

**Comment by RobbieMcKinstry** [comment]
Also requires close collab with Provides and Ecosystem teams.

**Comment by RobbieMcKinstry** [comment]
I'm picking up this issue now.

I'm starting with exploration; I need to familiarize myself with Python codegen and with the background on Wheel-based installs and `pyproject.toml`. Once I have the lay of the land, I'll write up an RFC and circulate it to the Ecosystem and Providers teams for approval. Currently the estimated timeline for that document is end of M84 since I'm on ops rotation next week, but that still might be a generous timeline.

**Comment by jancespivo** [comment]
The issue https://github.com/pulumi/pulumi/issues/4999 might be related.
