### ISSUE TITLE
[BUG] Linux X64 Build Status badge is not showing

### ISSUE THREAD

**Issue by Arindam200** [pulumi/pulumi#11280]
### What happened?

The **Linux X64** Build Status `badge` in the Readme file is not showing.

### Steps to reproduce

 I don't know exactly know how to reproduce this bug.

### Expected Behavior

The badge should be shown! 

### Actual Behavior

![image](https://user-images.githubusercontent.com/109217591/200476016-0110ac7a-c12f-4db4-87a7-99bf5e79f2d9.png)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
This appears not to be as simple as I first suspected. We recently switched to employ merge queues to ensure master is always green. We vet the master build on the `staging` branch before we cherry-pick those commits to the master branch.
This research paper describes our methodology: ["Keeping Master Green At Scale."](https://dl.acm.org/doi/10.1145/3302424.3303970)

**Comment by AaronFriel** [comment]
Hey @Arindam200, as @RobbieMcKinstry mentioned I think the badge doesn't convey anything useful.

[Pulumi's GitHub Releases](https://github.com/pulumi/pulumi/releases) are authoritative, and our CI changes ensure that our latest build must pass all tests.

I think that we ought to remove this section as there's no signal to convey to users here. Badges like this help the team know if they should expect test failures when building off the main branch, and since our changes the answer is no.

**Comment by Arindam200** [comment]
> Hey @Arindam200, as @RobbieMcKinstry mentioned I think the badge doesn't convey anything useful.
> 
> [Pulumi's GitHub Releases](https://github.com/pulumi/pulumi/releases) are authoritative, and our CI changes ensure that our latest builds and commits on `master` must pass all tests.
> 
> I think that we ought to remove this section as there's no signal to convey to users here. Badges like this help the team know if they should expect test failures when building off the main branch, and since our changes the answer is no.


Thank you @AaronFriel  for your kind feedback! You are too kind! 

Should I close this issue?

**Comment by AaronFriel** [comment]
I think @RobbieMcKinstry will when we remove the badge, thanks for offering!

**Comment by Arindam200** [comment]
> I think @RobbieMcKinstry will when we remove the badge, thanks for offering!

Thanks a lot @AaronFriel ! You are very helpful 🙏!
