### ISSUE TITLE
Upgrading sdk form 3.43.1 to 3.46.1 throws eror

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#11316]
### What happened?

Automated testing against upgrading from 3.43.1 -> 3.46.1 thru the following error:
```
[stdout]          stderr: error: Running program '/tmp/binding-directory2497179436' failed with an unhandled exception:
[stdout]          Error: failed to register new resource example--s3-adv-log-bucket [example:aws/s3:S3Bucket]: 2 UNKNOWN: plugins that can construct components must support secrets
[stdout]              at Object.registerResource (/tmp/binding-directory2497179436/node_modules/@pulumi/runtime/resource.ts:293:27)
[stdout]              at new Resource (/tmp/binding-directory2497179436/node_modules/@pulumi/resource.ts:402:13)
[stdout]              at new ComponentResource (/tmp/binding-directory2497179436/node_modules/@pulumi/resource.ts:895:9)
[stdout]              at new S3Bucket (/tmp/binding-directory2497179436/node_modules/@example/aws/s3/S3Bucket.ts:99:9)
[stdout]              at /tmp/binding-directory2497179436/src/index.ts:70:31
[stdout]              at Generator.next (<anonymous>)
[stdout]              at fulfilled (/tmp/binding-directory2497179436/src/index.ts:5:58)
[stdout]              at processTicksAndRejections (node:internal/process/task_queues:96:5)
[stdout]          error: Running program '/tmp/binding-directory2497179436' failed with an unhandled exception:
[stdout]          Error: failed to register new resource example--s3-simple-bucket [example:aws/s3:S3Bucket]: 2 UNKNOWN: plugins that can construct components must support secrets
[stdout]              at Object.registerResource (/tmp/binding-directory2497179436/node_modules/@pulumi/runtime/resource.ts:293:27)
[stdout]              at new Resource (/tmp/binding-directory2497179436/node_modules/@pulumi/resource.ts:402:13)
[stdout]              at new ComponentResource (/tmp/binding-directory2497179436/node_modules/@pulumi/resource.ts:895:9)
[stdout]              at new S3Bucket (/tmp/binding-directory2497179436/node_modules/@example/aws/s3/S3Bucket.ts:99:9)
[stdout]              at /tmp/binding-directory2497179436/src/index.ts:49:26
[stdout]              at Generator.next (<anonymous>)
[stdout]              at fulfilled (/tmp/binding-directory2497179436/src/index.ts:5:58)
[stdout]              at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to reproduce

1. Using the existing test infrastructure upgrade from 3.43.1 to 3.46.1
2. Only raises an issue in typescript, not python or go. 

### Expected Behavior

1. error not to be thrown

### Actual Behavior

1. Error thrown. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
@rshade Could you link us to the automated test that failed? Is the code sample that caused the failure available?

**Comment by justinvp** [comment]
@RobbieMcKinstry, there's a repro in https://github.com/pulumi/pulumi-awsx/issues/948, if that helps. I still haven't figured out what's going on. It appears to happen when passing an explicit `provider` when creating an MLC. Interestingly, if the provider is passed using `providers:` rather than `provider:`, the program works without the error.

**Comment by justinvp** [comment]
This is a regression in the Node.js SDK introduced by #11093.

https://github.com/pulumi/pulumi/blob/beaf07d8be423db318c4b02c8a167e4524f51ac0/sdk/nodejs/runtime/resource.ts#L530-L536

#11093 added the `|| remote` to the `if`, which, in this case, causes the engine to call `Construct` (to create the `Vpc` MLC component) on the specified _aws_ provider, rather than the intended _awsx_ provider.
