### ISSUE TITLE
Parse errors during 'Pulumi up' when using top-level 'config' key in Pulumi.yaml

### ISSUE THREAD

**Issue by activtrak-igueths** [pulumi/pulumi#11326]
Version: 3.46.1
Normal 'Pulumi up':
Diagnostics:
  pulumi:pulumi:Stack (REDACTED):
    Warning: Pulumi.yaml: root-level `configuration` field is deprecated; please use `config` instead.
'Pulumi up' after modifying 'configuration:' to 'config:' in Pulumi.yaml:
errors occurred:
	* #/config/gcp_project: oneOf failed
	* #/config/gcp_project: expected string, but got object
	* #/config/gcp_project: expected integer, but got object
	* #/config/gcp_project: expected boolean, but got object
	* #/config/gcp_project: expected array, but got object
	* #/config/gcp_project: doesn't validate with '/$defs/configTypeDeclaration'
	* #/config/gcp_project/type: doesn't validate with '/$defs/simpleConfigType'
	* #/config/gcp_project/type: value must be one of "string", "integer", "boolean", "array"
	* #/config/name: oneOf failed
	* #/config/name: expected string, but got object
	* #/config/name: expected integer, but got object
	* #/config/name: expected boolean, but got object
	* #/config/name: expected array, but got object
	* #/config/name: doesn't validate with '/$defs/configTypeDeclaration'
	* #/config/name/type: doesn't validate with '/$defs/simpleConfigType'
	* #/config/name/type: value must be one of "string", "integer", "boolean", "array"

**Comment by AaronFriel** [comment]
Hey @activtrak-igueths, thanks for flagging this! Would you mind sharing what your `configuration` or `config` block looks like in the `Pulumi.yaml` file?

We could improve our errors here, but I think the issue might be the last lines of each pair of paths:

```
* #/config/gcp_project/type: value must be one of "string", "integer", "boolean", "array"
* #/config/name/type: value must be one of "string", "integer", "boolean", "array"
```

Could you check and tell me if the config block is using an uppercase `String` or lowercase `string`? Changing it to `type: string` might fix this.

**Comment by activtrak-igueths** [comment]
Hello,
This appears to resolve the issue, I no longer see any errors and am able to do a successful ‘Pulumi up’:
Type                 Name                             Plan     
     pulumi:pulumi:Stack  REDACTED           


Resources:
    3 unchanged
Thanks!

**Comment by AaronFriel** [comment]
Happy to help and we're tracking #11328 to improve the error message!
