### ISSUE TITLE
Pulumi stack select broke after update to v3.46.1

### ISSUE THREAD

**Issue by kerruba-milkman** [pulumi/pulumi#11334]
### What happened?

After updating to version 3.46.1, the `pulumi stack select` command is breaking due to parsing issues with my stack.
The stack name is `shared-dev`, and while all the command related to stack selection were working fine before update - e.g.  `pulumi up`, `pulumi preview`,  `pulumi stack select` - now any command that require selecting the stack is breaking with this error:

```
error: parsing selected stack: stack names may only contain alphanumeric, hyphens, underscores, and periods
```

If instead I pass the stack name as a parameter to the `preview` and `up` commands, they work as expected

### Steps to reproduce

First scenario:

- Create a stack with an hypen in the name, e.g. shared-dev
- Run `pulumi stack select` and select the stack and see the error
- Run `pulumi preview` or `pulumi up`, select the stack and see the error

### Expected Behavior

Valid stack name can be selected interactively 

### Actual Behavior

An error is reported about an issue with the stack name

### Output of `pulumi about`

```
 pulumi about
CLI
Version      3.46.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.13.0
docker  3.4.1
nodejs  unknown
tls     4.6.1

Host
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/lucacherubin/.nvm/versions/node/v14.17.5/bin/node' version='v14.17.5'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/luca_cherubin
User           luca_cherubin
Organizations  luca_cherubin, milkmantechnologies

Dependencies:
NAME                              VERSION
@types/node                       14.18.27
eslint-plugin-import              2.26.0
express                           4.18.1
ts-node                           8.10.2
@typescript-eslint/parser         4.33.0
eslint-config-airbnb-typescript   12.3.1
husky                             4.3.8
@pulumi/aws                       5.13.0
@pulumi/awsx                      0.40.0
@pulumi/pulumi                    3.39.2
@types/express                    4.17.13
@typescript-eslint/eslint-plugin  4.33.0
ts-jest                           26.5.6
typescript                        3.9.10
@pulumi/tls                       4.6.1
@types/prettier                   2.6.0
eslint                            7.32.0
jest                              26.6.3

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> Create a stack with an hypen in the name, e.g. shared-dev
> Run pulumi stack select and select the stack and see the error
> Run pulumi preview or pulumi up, select the stack and see the error

```
fraser@IBASA-PC:~/projects/example$ pulumi stack init shared-dev
Created stack 'shared-dev'
fraser@IBASA-PC:~/projects/example$ pulumi stack select
Please choose a stack, or create a new one: shared-dev
fraser@IBASA-PC:~/projects/example$ pulumi stack
Current stack is shared-dev:
    Owner: Frassle
Current stack resources (0):
    No resources currently in this stack

More information at: https://app.pulumi.com/Frassle/import_test/shared-dev

Use `pulumi stack select` to change stack; `pulumi stack ls` lists known ones
```

Odd, seems fine on my build. Are you sure your only stack is "shared-dev"?

**Comment by alexisatkinson** [comment]
Also see this issue.  Rolling back to 3.46.0 and the issue goes away.

**Comment by Frassle** [comment]
> Are you sure your only stack is "shared-dev"?

I checked this in the service database, it does look like that's the only stack name in use here.

I suspect this has been caused by the update to the [survey library](https://github.com/pulumi/pulumi/commit/61269918c61597f925b99998b47ec72d74778136), where it's probably returning something like "shared-dev\n" or something weirder.

**Comment by aschleck** [comment]
I am experiencing this with a stack named "prod" if I only press enter at the stack selection dialog (the default suggested stack is the one I want so enter should select it.) But if I press down arrow, up arrow, and then enter, then it works fine.

**Comment by brandontoups** [comment]
confirming on 3.46.1 that the behavior aschleck described happens to me as well. if I click up and down arrows (i only have one stack, so it doesn't actually move the arrow anywhere) and then hit enter, it then works

**Comment by mjerdely** [comment]
Do we have an ETA for when this will be released?

**Comment by Frassle** [comment]
> Do we have an ETA for when this will be released?

Tomorrow

**Comment by tonybruess** [comment]
Please release 😃

**Comment by aq17** [comment]
@mjerdely @tonybruess thanks for your patience, the release will actually go out tomorrow morning PDT
