### ISSUE TITLE
Go: AsStringMapOutput() - panic: interface conversion: interface {} 

### ISSUE THREAD

**Issue by Graham-Beer** [pulumi/pulumi#11347]
### What happened?

Trying to convert an export `pulumi.StringMap` through a stack reference in a new Pulumi project.

### Steps to reproduce

ctx.Export("tags", MaximoTags) - The variable `MaximoTags` is of type `pulumi.StringMap`.

Trying to import the value into a new project:

```go
tags := fmt.Sprintf("Graham-Beer/maximo_db/%v", ctx.Stack())

TagRef, err := pulumi.NewStackReference(ctx, tags, nil)
if err != nil {
	return err
}
maximoTags := TagRef.GetOutput(pulumi.String("tags")).AsStringMapOutput()
```

The variable `maximoTags` is used when creating a new EFS:

```go
_, err = efs.NewFileSystem(ctx, "EFS_Maximo", &efs.FileSystemArgs{
        CreationToken:   pulumi.String("ElasticFileSystem-QIgODGs4npZR"),
	Encrypted:       pulumi.Bool(true),
	KmsKeyId:        pulumi.String(kmskey.Id),
	PerformanceMode: pulumi.String("generalPurpose"),
	Tags:            pulumi.StringMapInput(maximoTags),
})
```

### Expected Behavior

I would expect the creation of the EFS share to complete and build the tag values from the stack import.

### Actual Behavior

Get the error:

    panic: interface conversion: interface {} is map[string]interface {}, not map[string]string
    goroutine 74 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.AnyOutput.AsStringMapOutput.func1({0xc855a0?, 0xc0001a1ad0?}) 

### Output of `pulumi about`

```
CLI          
Version      3.46.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME  VERSION
aws   5.18.0
go    unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.19.3 linux/amd64'

Current Stack: test

TYPE                          URN
pulumi:providers:aws          urn:pulumi:test::maximo_efs::pulumi:providers:aws::default
pulumi:pulumi:Stack           urn:pulumi:test::maximo_efs::pulumi:pulumi:Stack::maximo_efs-test
pulumi:providers:pulumi       urn:pulumi:test::maximo_efs::pulumi:providers:pulumi::default
pulumi:pulumi:StackReference  urn:pulumi:test::maximo_efs::pulumi:pulumi:StackReference::Graham-Beer/maximo_db/test


Found no pending operations associated with test

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/Graham-Beer
User           Graham-Beer
Organizations  Graham-Beer

Dependencies:
NAME                                                                   VERSION
git-codecommit.eu-west-1.amazonaws.com/v1/repos/pulumi-library-go.git  0.0.0-20221111145405-79351a5cee5d
github.com/pulumi/pulumi-aws/sdk/v5                                    5.18.0
github.com/pulumi/pulumi/sdk/v3                                        3.44.2

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @Graham-Beer. Thanks for bringing this up. Technically, everything is working as intended. The panic describes the problem: you cannot cast ` map[string]interface{}` to `map[string]string`. Go casts are invariant over underlying types. That being said...

This is a super annoying sharp edge to casting in go. We already have contravariance for array types (casting `[]interface{}` to `[]string` when all elements are strings). Because of your issue, I've opened #11348, which will introduce contravariance over `map`, as well as combinations of `map` and `array` types.
