### ISSUE TITLE
Download Pulumi Cron job fails when installing winget CLI

### ISSUE THREAD

**Issue by Zaid-Ajaj** [pulumi/pulumi#11342]
### What happened?

Installing WinGet CLI is required for us to test that we can install Pulumi from winget. Windows 11 comes with winget preinstalled and on Windows 10 you can install it from the app store. When using `windows-latest` from the github action, we expected that winget CLI is already installed but that is unfortunately not the case. 

To install Winget CLI on the machine of the github workflow we write the following:
```powershell
try { winget --help } catch { Add-AppxPackage -Path https://aka.ms/getwinget }
```
This _works_ when testing with a local Windows machine but doesn't on the github action due to missing dependencies. This issue of missing dependencies is also tracked here: https://github.com/microsoft/winget-cli/issues/1861 where they suggest that they are working on it at the moment

### Steps to reproduce

See the action failing here https://github.com/pulumi/pulumi/actions/runs/3454412189/jobs/5765691040

### Expected Behavior

It should install winget successfully

### Actual Behavior

Winget CLI fails to install

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
winget still doesn't appear to be included by default in GitHub's runner images, but looks like there's a GitHub Action that can be used to install it: https://github.com/marketplace/actions/install-winget
