### ISSUE TITLE
RemoteWorkspaces: Add `skipInstallDependencies` option

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#11357]
`skipInstallDependencies` was recently added to the Deployments API (https://github.com/pulumi/service-requests/issues/126). It should be exposed as an option in Automation API.

**Comment by Frassle** [comment]
We're really gonna need to start investing in something automatic to keep all this in sync, it was bad enough trying to keep automation api in sync with the engine, now we've got to keep it in sync with the service as well.
