### ISSUE TITLE
New resource option `DeletedWith` accepts a URN instead of a Resource

### ISSUE THREAD

**Issue by dorfire** [pulumi/pulumi#11358]
### What happened?

At least in the Go SDK, it's difficult to utilize the new `DeletedWith()` option.
It accept a `URN`, unlike `Parent()` which accepts a `Resource`, so it seems like the only way to use `DeletedWith` is inside an `.ApplyT(...)` block.

### Steps to reproduce

Try to invoke `pulumi.DeletedWith` in the Go SDK.

### Expected Behavior

I would like to be able to invoke `pulumi.DeletedWith` in the Go SDK without `.ApplyT()`.

### Actual Behavior

Seems like one must use `DeletedWith()` inside an `.ApplyT()` block.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
We discussed this internally and decided to go ahead and fix. While changing the signature is technically a breaking change, the feature is currently unusable in Go, so the change would not break anyone, so there's no need to wait for a major version bump.
