### ISSUE TITLE
Python: Can async functions' responses be parts of dependencies?

### ISSUE THREAD

**Issue by antifuchs** [pulumi/pulumi#11361]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In order for a resource in a particular provider to come up, it requires a webhook endpoint to be up, which is handled by a service that's spun up in the same infrastructure code. I thought I could do something similar to the JS API in [this gist](https://gist.github.com/lukehoban/fd0355ed5b82386bd89c0ffe2a3c916a#file-waitforjob-ts-L20-L40), but this doesn't work:

```python
async def wait_for_our_url_ready():
    for _i in range(600):
        async with aiohttp.ClientSession() as session:
            async with session.post(our.webhook_url) as resp:
                if resp.status == 200:
                    return
                await asyncio.sleep(1)
    raise Exception(f"Timed out waiting for {our.webhook_url} to be reachable.")


our_webhook_ready = pulumi.Output.from_input(backend_ingress).apply(
    wait_for_our_url_ready
)

Webhook(
    "webhook",
    name="Backend notifications",
    description="Backend notifications",
    url=our.webhook_url,
    enabled=True,
    depends_on=[our_webhook_ready],
)
```

...because it's not allowed to pass a coroutine to Output.apply. Can I generate a pulumi Resource from the outcome of an async function some other way?

### Affected area/feature

Python bindings.

**Comment by lukehoban** [comment]
@antifuchs I would have expected this example to work as written.  What error are you seeing?  Is it from Python type checker or from Pulumi CLI?

**Comment by lukehoban** [comment]
I tried this out myself - and it works without any errors:

```py
import asyncio
import aiohttp
import pulumi

our_webhook_url = "https://google.com/"

async def wait_for_our_url_ready(_):
    for _i in range(600):
        async with aiohttp.ClientSession() as session:
            async with session.get(our_webhook_url) as resp:
                if resp.status == 200:
                    return
                await asyncio.sleep(1)
    raise Exception(f"Timed out waiting for {our_webhook_url} to be reachable.")


our_webhook_ready = pulumi.Output.from_input(42).apply(
    wait_for_our_url_ready
)

pulumi.export('done', our_webhook_ready)
```

**Comment by antifuchs** [comment]
Hah, I found the problem - my type checker was trying to tell me that this function isn't returning a `pulumi.Resource`, which is required when you put them on `depends_on` lists. Think this works, after all - I just needed to read the type error right. 

Thank you!
