### ISSUE TITLE
Organization part of stack name not parsed correctly in some cases

### ISSUE THREAD

**Issue by samox73** [pulumi/pulumi#11373]
### What happened?

When referencing existing stacks, sometimes the organization part of the stack is not handled correctly:
- When a project with name `test` exists for the current **user**, and a project with stack `organizationId/test` is created, pulumi fails with
  ```
  error: A project with this name already exists
  ```
  Deleting the **user** project and trying again successfully creates the project within the **organization**
- When executing `pulumi up`/`pulumi destroy` in an **organization** project **without** a stack being selected explicitly, pulumi will ask which stack to select. Upon selection, pulumi fails with 
  ```
  error: parsing selected stack: stack names may only contain alphanumeric, hyphens, underscores, and periods
  ```
  Selecting the stack explicitly resolves this issue.

### Steps to reproduce

- ```bash
  ❯ mkdir test-user && cd test-user
  ❯ pulumi new aws-typescript -n "test" -d "test" -s "test"
  Created project 'test'
  
  Created stack 'test'
  
  aws:region: The AWS region to deploy into: (us-east-1)
  Saved config
  
  Installing dependencies...
  
  
  added 164 packages, and audited 165 packages in 16s
  
  50 packages are looking for funding
    run `npm fund` for details
  
  found 0 vulnerabilities
  Finished installing dependencies
  
  Your new project is ready to go! 
  
  To perform an initial deployment, run `pulumi up`
  
  ❯ mkdir test-org && cd test-org
  ❯ pulumi new aws-typescript -n "test" -d "test" -s "powerbot/test"
  error: A project with this name already exists
  ```
- delete the user stack:
  ```bash
  cd ../test-user
  ❯ pulumi stack rm
  This will permanently remove the 'test' stack!
  Please confirm that this is what you'd like to do by typing `test`: test
  Stack 'test' has been removed!
  ```  
- try creating the organization stack again:
  ```bash
  ❯ pulumi new aws-typescript -n "test" -d "test" -s "powerbot/test"
  Created project 'test'
  
  Created stack 'powerbot/test'
  
  aws:region: The AWS region to deploy into: (us-east-1)           
  Saved config
  
  Installing dependencies...
  
  
  added 164 packages, and audited 165 packages in 5s
  
  50 packages are looking for funding
    run `npm fund` for details
  
  found 0 vulnerabilities
  Finished installing dependencies
  
  Your new project is ready to go! 
  
  To perform an initial deployment, run `pulumi up`

  ```
- create another stack in the organization and try `up`ing any stack after unselecting it explicitly:
  ```
  ❯ pulumi stack init powerbot/test2
  Created stack 'powerbot/test2'
  ❯ pulumi stack unselect
  Stack was unselected
  ❯ pulumi up
  Please choose a stack, or create a new one: 
  error: parsing selected stack: stack names may only contain alphanumeric, hyphens, underscores, and periods

  ```

### Expected Behavior

Pulumi should parse the organization part of the stack correctly.

### Actual Behavior

Pulumi mistakes the orgnization part of the stack as being part of the actual stack name.

### Output of `pulumi about`

```
❯ pulumi about
CLI          
Version      3.46.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.20.0
docker  3.6.0
nodejs  unknown

Host     
OS       arch
Version  "rolling"
Arch     x86_64

This project is written in nodejs: executable='/sbin/node' version='v19.1.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/samox73
User           samox73
Organizations  samox73, powerbot

Dependencies:
NAME            VERSION
@pulumi/aws     5.20.0
@pulumi/awsx    0.40.1
@pulumi/pulumi  3.46.1
@types/node     14.18.33

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

I upgraded to version `3.46.0 -> 3.46.1` yesterday, then this started to happen.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pierskarsenbarg** [comment]
Hi this has been fixed and should be released shortly: https://github.com/pulumi/pulumi/pull/11354

**Comment by aq17** [comment]
Thanks @pierskarsenbarg!

**Comment by aq17** [comment]
Closed as duplicate of https://github.com/pulumi/pulumi/issues/11334
