### ISSUE TITLE
Unintended Bucket Replacement when Aliasing Bucket to BucketV2 in Component Resource

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#11397]
### What happened?

When attempting to migrate from aws s3 bucket to aws s3 bucketv2 Pulumi, using aliases, Pulumi wants to replace the s3 bucket.
- Existing component resource contains aws s3 bucket
- Create a new component resource which contains aws s3 bucketv2
- Alias existing aws s3 bucket to the new aws s3 bucketv2 so that the physical aws s3 bucket is retained

### Steps to reproduce

- Existing component resource contains aws s3 bucket
- Create a new component resource which contains aws s3 bucketv2
- Alias existing aws s3 bucket to the new aws s3 bucketv2 so that the physical aws s3 bucket is retained

### Expected Behavior

Bucket should not be replaced

### Actual Behavior

Pulumi wants to replace bucket.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
@phillipedwards can you share your program? I tried

1. creating a component resource
2. creating an s3 bucket as part of the component
3. pulumi up
4. creating a second component resource
5. creating an s3 v2 bucket aliased to the original bucket

Did you delete the 1st component prior but not the bucket prior to 4?

**Comment by phillipedwards** [comment]
@aq17 apologies, I meant to comment that I'll be trying to produce a repro for this one.

**Comment by phillipedwards** [comment]
The below example, which uses vanilla component resources, and aliasing the bucket works as expected, between the two components.
```golang
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ComponentA struct {
	pulumi.ResourceState
}

type ComponentB struct {
	pulumi.ResourceState
}

func NewComponentA(ctx *pulumi.Context, name string, opts ...pulumi.ResourceOption) (*s3.Bucket, error) {
	b, err := s3.NewBucket(ctx, "bucket", nil)
	if err != nil {
		return nil, err
	}

	return b, nil
}

func NewComponentB(ctx *pulumi.Context, name string, opts ...pulumi.ResourceOption) (*s3.BucketV2, error) {
	alias := pulumi.Aliases([]pulumi.Alias{
		{
			Name: pulumi.String("bucket"),
		},
	})

	b, err := s3.NewBucketV2(ctx, "bucket", &s3.BucketV2Args{}, alias)
	if err != nil {
		return nil, err
	}

	return b, nil
}

// deploy componentA
// swap componentA for componentB and re-run pulumi up
// bucket should not be replaced

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		// Create an AWS resource (S3 Bucket)

		bucket, err := NewComponentA(ctx, "my-bucket")
		if err != nil {
			return err
		}

		// Export the name of the bucket
		ctx.Export("bucketName", bucket.ID())
		return nil
	})
}

```

**Comment by aq17** [comment]
Was the user able to share the structure of their component? It seems like it should work irrespective of that though

**Comment by lukehoban** [comment]
Opened https://github.com/pulumi/pulumi/issues/11697 on what I believe is the root cause of the reported issue here.  I am fairly sure there is no issue specific to `BucketV2`.  I believe this can be closed out as a duplicate of https://github.com/pulumi/pulumi/issues/11697.

Note that I think the difference between the issue reported in https://github.com/pulumi/pulumi/issues/11697 and the repro attempted above is that the one here includes this:

```
	alias := pulumi.Aliases([]pulumi.Alias{
		{
			Name: pulumi.String("bucket"),
		},
	})
```

While the one that triggers the problem includes:

```
        aliases := pulumi.Aliases([]pulumi.Alias{
		{
			Type:     pulumi.String("wibble:aws/s3:Bucket"),
		},
	})
```

I believe the issue is most likely going to be specific to `Type` based aliases.
