### ISSUE TITLE
`Stack.createOrSelect`: first select, then create to play well with RO permissions on Pulumi Service

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#11392]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The current implementation for `Stack.createOrSelect` first tries to create the stack and falls back to selecting the stack if the stack already exists. Here is the NodeJS implementation, but as far as I could see, the other language implementations are similar.

https://github.com/pulumi/pulumi/blob/982656f114f7c98e35fe54fccde7fea478ff0d6a/sdk/nodejs/automation/stack.ts#L107-L114

A customer bumps into a problem where most of their users have read-only permissions to an existing stack on our Pulumi Service. Using the current implementation of `createOrSelect` fails for them because the method first tries to create the stack, only selecting the stack as a fallback when the stack already exists.

The customer request is to reverse the implementation to something like this:

```ts
const stack: Promise<Stack> = workspace.selectStack(name).catch((err) => {
    if (err instanceof StackNotFoundError) {
        return workspace.createStack(name);
    }
    throw err;
});

await stack;
```

### Affected area/feature

The change is requested to be compatible with setups where users have read-only permissions on an existing stack. Reversing the implementation within `createOrSelect` will work in such RO situations and will only fail for the fallback case when the stack needs to be created.

**Comment by Frassle** [comment]
We've already flipped this around in the python automation api: https://github.com/pulumi/pulumi/commit/7695311d799f47a3cf13e6019d135eec4bb886bd

It makes sense to just do that in all the apis to keep them in sync.
