### ISSUE TITLE
brew install failing for version 3.47.0

### ISSUE THREAD

**Issue by narenvivek** [pulumi/pulumi#11406]
### What happened?

![image](https://user-images.githubusercontent.com/29542480/202701894-927ec1d9-e5d9-403a-b743-bb7b8e04c33e.png)

### Steps to reproduce

brew install pulumi/tap/pulumi

### Expected Behavior

should have installed correctly

### Actual Behavior

Error: pulumi: Failed to download resource "pulumi"
Download failed: https://github.com/pulumi/pulumi/releases/download/v3.47.0/pulumi-v3.47.0-darwin-arm64.tar.gz

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Hi @narenvivek , apologies for this – please retry now

**Comment by narenvivek** [comment]
that works. thanks
