### ISSUE TITLE
3.47 win amd64 setup missing, 404 link

### ISSUE THREAD

**Issue by dviry** [pulumi/pulumi#11409]
### What happened?

Download link here: https://www.pulumi.com/docs/get-started/install/

Returns a 404 - looking at the releases page: https://github.com/pulumi/pulumi-winget/releases/ - shows the latest is 3.46.1

### Steps to reproduce

see above

### Expected Behavior

correct setup, correct link

### Actual Behavior

404 setup not found

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Hi @dviry , we are working on a fix. `v3.47.1` should be released shortly to remedy this.
