### ISSUE TITLE
Error deserializing optional output resource

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#11416]
The Python SDK throws errors when an optional resource output is missing.

See https://github.com/pulumi/pulumi-awsx/issues/929 for the original issue.
See also https://github.com/pulumi/pulumi-awsx/issues/933 for the same issue with optional output roles.

## Reproduction

In AWSx the `FargateTaskDefinition` can optionally create a log group for you. So has an output property of `pulumi.Output[Optional['pulumi_aws.cloudwatch.LogGroup']]`. See https://github.com/pulumi/pulumi-awsx/blob/master/sdk/python/pulumi_awsx/ecs/fargate_task_definition.py#L487

When we opt to not create a log group:

```python
import pulumi_awsx as awsx

# Create an AWS resource (S3 Bucket)
awsx.ecs.FargateTaskDefinition(
    resource_name="task_def",
    log_group=awsx.awsx.DefaultLogGroupArgs(
        skip=True,
    ),
    container=awsx.ecs.TaskDefinitionContainerDefinitionArgs(
        image="nginx:latest",
        cpu=256,
        memory=512,
        essential=True,
    ),
)
```

The output is set to `undefined` by the component provider.

The SDK fails with:

```
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 192, in <module>
        loop.run_until_complete(coro)
      File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
        return future.result()
      File "/Users/dan/Dev/scratch-py/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 126, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/dan/Dev/scratch-py/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/dan/Dev/scratch-py/venv/lib/python3.10/site-packages/pulumi/runtime/stack.py", line 110, in wait_for_rpcs
        raise exception
      File "/Users/dan/Dev/scratch-py/venv/lib/python3.10/site-packages/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        result = await rpc
      File "/Users/dan/Dev/scratch-py/venv/lib/python3.10/site-packages/pulumi/runtime/resource.py", line 668, in do_register
        rpc.resolve_outputs(
      File "/Users/dan/Dev/scratch-py/venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 1049, in resolve_outputs
        all_properties[translated_key] = translate_output_properties(
      File "/Users/dan/Dev/scratch-py/venv/lib/python3.10/site-packages/pulumi/runtime/rpc.py", line 882, in translate_output_properties
        raise AssertionError(
    AssertionError: Unexpected type; expected a value of type `<class 'pulumi_aws.cloudwatch.log_group.LogGroup'>` but got a value of type `<class 'dict'>` at resource `task_def`, property `log_group`: {'skip': True}
```

The captured RegisterResource request shows the following:

```json
{
    "method": "/pulumirpc.ResourceMonitor/RegisterResource",
    "request": {
      "type": "awsx:ecs:FargateTaskDefinition",
      "name": "task_def",
      "parent": "urn:pulumi:dev::scratch-py::pulumi:pulumi:Stack::scratch-py-dev",
      "object": {
        "container": {
          "cpu": 256,
          "essential": true,
          "image": "nginx:latest",
          "memory": 512
        },
        "logGroup": { "skip": true }
      },
      "propertyDependencies": { "container": {}, "logGroup": {} },
      "version": "1.0.0-beta.11",
      "acceptSecrets": true,
      "supportsPartialValues": true,
      "remote": true,
      "acceptResources": true
    },
    "response": {
      "urn": "urn:pulumi:dev::scratch-py::awsx:ecs:FargateTaskDefinition::task_def",
      "object": {
        "executionRole": {
          "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
          "id": "task_def-execution-a77077c",
          "urn": "urn:pulumi:dev::scratch-py::awsx:ecs:FargateTaskDefinition$aws:iam/role:Role::task_def-execution"
        },
        "loadBalancers": [],
        "taskDefinition": {
          "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
          "id": "task_def-7df87b98",
          "urn": "urn:pulumi:dev::scratch-py::awsx:ecs:FargateTaskDefinition$aws:ecs/taskDefinition:TaskDefinition::task_def"
        },
        "taskRole": {
          "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
          "id": "task_def-task-f771a5f",
          "urn": "urn:pulumi:dev::scratch-py::awsx:ecs:FargateTaskDefinition$aws:iam/role:Role::task_def-task"
        }
      },
      "propertyDependencies": {
        "executionRole": {
          "urns": [
            "urn:pulumi:dev::scratch-py::awsx:ecs:FargateTaskDefinition$aws:iam/role:Role::task_def-execution"
          ]
        },
        "loadBalancers": {},
        "taskDefinition": {
          "urns": [
            "urn:pulumi:dev::scratch-py::awsx:ecs:FargateTaskDefinition$aws:ecs/taskDefinition:TaskDefinition::task_def"
          ]
        },
        "taskRole": {
          "urns": [
            "urn:pulumi:dev::scratch-py::awsx:ecs:FargateTaskDefinition$aws:iam/role:Role::task_def-task"
          ]
        }
      }
    },
    "metadata": { "mode": "server" }
  }
```

It appears the SDK is attempting to deserialize the input value as the output value when the output is not provided. 

Note: this does not happen in the Node.js SDK. I have not tested other SDKs.

**Comment by justinvp** [comment]
> It appears the SDK is attempting to deserialize the input value as the output value when the output is not provided.

The SDKs have this behavior where if the output value isn't present, it'll just set the output value to the input value. Which mostly works for custom resources where there's generally a 1:1 match between inputs/outputs, but obviously does not work well when that's not the case (which is likely to be more often now with components). We likely need to re-think this overall.

https://github.com/pulumi/pulumi/blob/95c3a9b452ec9ca5e53c565fa0820f971fb6322b/sdk/python/lib/pulumi/runtime/rpc.py#L1043-L1055

> Note: this does not happen in the Node.js SDK

The Node.js SDK does do this -- it just doesn't check the types like Python does, so it'll silently set the input value for the output value (even though, the types don't match).

https://github.com/pulumi/pulumi/blob/95c3a9b452ec9ca5e53c565fa0820f971fb6322b/sdk/nodejs/runtime/resource.ts#L743-L756

I suspect the other language SDKs have a similar problem.

**Comment by danielrbradley** [comment]
Initial options I could see here:
- Could we provide a workaround where by we provide some kind of an "empty" value which will stop it defaulting back to the inputs?
- Should we rename all output properties to have different names from inputs - this would be a big breaking change to our existing components, but now might be the moment to do this.
- Do we need a flag in the schema to disable this input copying behaviour which we can opt into for components?

**Comment by justinvp** [comment]
I tried out Go and .NET, and they don't fail during `pulumi up`. (I haven't actually tried inspecting the output value yet; which I suspect will have issues).

Another option would be a more targeted fix for the Python SDK only, where when we're attempting to set the output value as the input value, instead of failing when there's a type mismatch, just don't set the value (and don't fail), which will result in the value being set to None (which is what we want in this case).

https://github.com/pulumi/pulumi/blob/95c3a9b452ec9ca5e53c565fa0820f971fb6322b/sdk/python/lib/pulumi/runtime/rpc.py#L1107-L1112

I think that will at least make `pulumi up` work and make Python work the same as the other languages. And we won't have to do any renames in AWSX, or plumb through new flags in the schema/codegen.

Then we can consider a better improvement later, for all languages, such as having a way to opt-in to disabling this behavior for components.
