### ISSUE TITLE
CodeCov Not Uploading Coverage Reports

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#11419]
https://app.codecov.io/gh/pulumi/pulumi hasn't been updated in quite some time.

[internal discussion](https://pulumi.slack.com/archives/C02VCJEBT2N/p1669047706081659)

**Comment by RobbieMcKinstry** [comment]
@AaronFriel the timeline looks suspiciously Bors related. Around when we started using Bors, CodeCov stopped receiving coverage reports.

**Comment by tgummerer** [comment]
This actually works now.
