### ISSUE TITLE
Resolve outstanding community PRs not merging.

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#11423]
This issue was closed, but there are a lot of outstanding approved PRs that are unable to be merged
- https://github.com/pulumi/pulumi/issues/11360

We need to merge the following approved PRs.

Failed `bors merge` PRs
- [ ] https://github.com/pulumi/pulumi/pull/11331
- [ ] https://github.com/pulumi/pulumi/pull/11383
- [ ] https://github.com/pulumi/pulumi/pull/11307

Documenting the strategy used to get the tests green would also be greatly appreciated in case there are other PRs in a similarly stuck state.

**Comment by tgummerer** [comment]
All of these PRs have been merged, so we can close this out.
