### ISSUE TITLE
`pulumi new` should not depend on all templates being valid

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#11434]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We error when anything [is](https://github.com/pulumi/pulumi/issues/11121) [off](https://github.com/pulumi/pulumi/issues/11433) with our templates, causing `pulumi new` to fail with a deserialization error. We should change how `pulumi new` works to limit the blast area of invalid templates. `pulumi new` should only fail if you attempt to select an invalid template.

**Comment by iwahbe** [comment]
I'm going to assign this to myself to make sure I get around to it. If anyone else is interested, feel free to transfer the assignment.

**Comment by justinvp** [comment]
Make sure `pulumi policy new` has the same improvement.

**Comment by iwahbe** [comment]
@aq17 did the fix end up accounting for `pulumi policy new`?

**Comment by aq17** [comment]
@iwahbe Working on that right now 😅

**Comment by aq17** [comment]
Closed by https://github.com/pulumi/pulumi/pull/11435, https://github.com/pulumi/pulumi/pull/11443
