### ISSUE TITLE
Command "pulumi new --force" fails to launch the project creation sequence on the command line

### ISSUE THREAD

**Issue by svodwood** [pulumi/pulumi#11433]
### What happened?

Updated pulumi to the recent release v3.47.1. Initialized a repository in Github, cloned to a local workstation. Navigated to the folder and attempted to run 'pulumi new --force' to initialize a new Pulumi project. Got an error related to one of the template definitions.

### Steps to reproduce

Run 'pulumi new --force' in a non-empty directory.

### Expected Behavior

Should kick off regular initialization of a new Pulumi project. 

### Actual Behavior

error: could not unmarshal '/Users/username/.pulumi/templates/kubernetes-azure-yaml/Pulumi.yaml': Configuration key 'azure-native:location' is not namespaced by the project and should not define a type

### Output of `pulumi about`

CLI
Version      3.47.1
Go Version   go1.19.3
Go Compiler  gc

Host
OS       darwin
Version  12.6
Arch     arm64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/redacted
User           redacted
Organizations  redacted

Pulumi locates its logs in /var/folders/f_/r89657hx4dvgry2plkbnl4cr0000gn/T/ by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /Users/username). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from /Users/username). If you have not created a project yet, use `pulumi new` to do so: no project file found

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for filing the issue, @svodwood. We're working on fixing the templates that are impacting `pulumi new`.

In the meantime, you can run `pulumi new <templatename> --force`, specifying the template you want, and that should work. The list of available templates are just top-level directories in https://github.com/pulumi/templates, e.g. `aws-typescript`.
