### ISSUE TITLE
`pulumi up --yes` failing with 3.47.2 due to `error: resource violates plan`

### ISSUE THREAD

**Issue by Antman261** [pulumi/pulumi#11444]
### What happened?

All of our deployments have started failing since Nov 23rd, 3:00 UTC with the error `error: resource violates plan`.

We discovered that the failure only occurs in version `3.47.2` when supplying the `--yes` flag. If we run in interactive mode, it passes as usual.

### Steps to reproduce

1. Run `pulumi up --yes` 

### Expected Behavior

Update succeeds with no changes

### Actual Behavior

Update fails with  `error: resource violates plan`

### Output of `pulumi about`

CLI
Version      3.47.2
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME       VERSION
gcp        6.43.0
nodejs     unknown
random     4.8.2
sumologic  0.7.1

Host
OS       darwin
Version  12.4
Arch     arm64

This project is written in nodejs: executable='/Users/anthonyanthony/.nvm/versions/node/v14.17.1/bin/node' version='v14.17.1'

Current Stack: workit/stg

TYPE                                                    URN
pulumi:pulumi:Stack                                     urn:pulumi:stg::skutopia::pulumi:pulumi:Stack::skutopia-stg
pulumi:providers:gcp                                    urn:pulumi:stg::skutopia::pulumi:providers:gcp::default_6_43_0
gcp:pubsub/topic:Topic                                  urn:pulumi:stg::skutopia::gcp:pubsub/topic:Topic::skutopia-stg-skutopia-dlq
gcp:bigquery/dataset:Dataset                            urn:pulumi:stg::skutopia::gcp:bigquery/dataset:Dataset::dataset-skutopia-pubsub-stg
gcp:pubsub/topic:Topic                                  urn:pulumi:stg::skutopia::gcp:pubsub/topic:Topic::skutopia-stg
pulumi:providers:random                                 urn:pulumi:stg::skutopia::pulumi:providers:random::default_4_8_2
random:index/randomString:RandomString                  urn:pulumi:stg::skutopia::random:index/randomString:RandomString::[REDACTED]
random:index/randomString:RandomString                  urn:pulumi:stg::skutopia::random:index/randomString:RandomString::dataingest-password
gcp:pubsub/topic:Topic                                  urn:pulumi:stg::skutopia::gcp:pubsub/topic:Topic::waretopia-stg-skutopia-dlq
gcp:pubsub/subscription:Subscription                    urn:pulumi:stg::skutopia::gcp:pubsub/subscription:Subscription::sub-skutopia-stg-internal-dlq
gcp:bigquery/table:Table                                urn:pulumi:stg::skutopia::gcp:bigquery/table:Table::table-skutopia-messages-stg
gcp:pubsub/subscription:Subscription                    urn:pulumi:stg::skutopia::gcp:pubsub/subscription:Subscription::sub-skutopia-stg-internal
gcp:pubsub/subscription:Subscription                    urn:pulumi:stg::skutopia::gcp:pubsub/subscription:Subscription::sub-skutopia-stg
gcp:pubsub/subscription:Subscription                    urn:pulumi:stg::skutopia::gcp:pubsub/subscription:Subscription::sub-skutopia-stg-dlq
gcp:pubsub/subscription:Subscription                    urn:pulumi:stg::skutopia::gcp:pubsub/subscription:Subscription::sub-skutopia-bigquery-stg
gcp:sql/databaseInstance:DatabaseInstance               urn:pulumi:stg::skutopia::gcp:sql/databaseInstance:DatabaseInstance::ims-database
gcp:dns/recordSet:RecordSet                             urn:pulumi:stg::skutopia::gcp:dns/recordSet:RecordSet::internal-dns
gcp:sql/user:User                                       urn:pulumi:stg::skutopia::gcp:sql/user:User::[REDACTED[
gcp:sql/user:User                                       urn:pulumi:stg::skutopia::gcp:sql/user:User::dataingest-user
gcp:monitoring/alertPolicy:AlertPolicy                  urn:pulumi:stg::skutopia::gcp:monitoring/alertPolicy:AlertPolicy::skutopia-message-delay
gcp:monitoring/alertPolicy:AlertPolicy                  urn:pulumi:stg::skutopia::gcp:monitoring/alertPolicy:AlertPolicy::skutopia-dlq-message-count
gcp:monitoring/alertPolicy:AlertPolicy                  urn:pulumi:stg::skutopia::gcp:monitoring/alertPolicy:AlertPolicy::dlq-message-count
gcp:monitoring/alertPolicy:AlertPolicy                  urn:pulumi:stg::skutopia::gcp:monitoring/alertPolicy:AlertPolicy::waretopia-message-delay
gcp:monitoring/alertPolicy:AlertPolicy                  urn:pulumi:stg::skutopia::gcp:monitoring/alertPolicy:AlertPolicy::under-pressure
gcp:monitoring/alertPolicy:AlertPolicy                  urn:pulumi:stg::skutopia::gcp:monitoring/alertPolicy:AlertPolicy::stressed
gcp:monitoring/alertPolicy:AlertPolicy                  urn:pulumi:stg::skutopia::gcp:monitoring/alertPolicy:AlertPolicy::upcheck
gcp:pubsub/topicIAMMember:TopicIAMMember                urn:pulumi:stg::skutopia::gcp:pubsub/topicIAMMember:TopicIAMMember::grant-pubsub-sa-to-publish
gcp:pubsub/topicIAMMember:TopicIAMMember                urn:pulumi:stg::skutopia::gcp:pubsub/topicIAMMember:TopicIAMMember::grant-skutopia-pubsub-sa-to-publish
gcp:pubsub/subscriptionIAMMember:SubscriptionIAMMember  urn:pulumi:stg::skutopia::gcp:pubsub/subscriptionIAMMember:SubscriptionIAMMember::grant-pubsub-sa-to-ack-message
gcp:bigquery/iamBinding:IamBinding                      urn:pulumi:stg::skutopia::gcp:bigquery/iamBinding:IamBinding::grant-pubsub-sa-to-bigquery
gcp:pubsub/subscriptionIAMMember:SubscriptionIAMMember  urn:pulumi:stg::skutopia::gcp:pubsub/subscriptionIAMMember:SubscriptionIAMMember::grant-skutopia-pubsub-sa-to-ack-message

Found no pending operations associated with workit/stg

Backend
Name           pulumi.com
URL            https://app.pulumi.com/antman-workit
User           antman-workit
Organizations  antman-workit, workit

Dependencies:
NAME               VERSION
@pulumi/gcp        6.43.0
@pulumi/pulumi     3.47.2
@pulumi/random     4.8.2
@pulumi/sumologic  0.7.1
@types/node        14.18.10

Pulumi locates its logs in /var/folders/48/km2bcpn92wg0twbs7dcnyt8h0000gp/T/ by default

### Additional context

I suspect that --yes is incorrectly selecting the new https://www.pulumi.com/docs/intro/concepts/plans/ behaviour, which has some other bug we've ran into.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> I suspect that --yes is incorrectly selecting the new https://www.pulumi.com/docs/intro/concepts/plans/ behaviour, which has some other bug we've ran into.

Almost definitely the case, and not the intention. We'll get a fix out ASAP.

**Comment by justinvp** [comment]
Note that this only happens when passing `--yes`. Running `pulumi up` interactively and selecting yes should work. This has been fixed in v3.48.0.
