### ISSUE TITLE
Installation of Pulumi via Chocolatey fails on Windows

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#11465]
### What happened?

Upgrade of Pulumi fails on Windows using Chocolatey. User reports he currently has v3.38.0 Install of 3.42, 3.45 and 3.48 fails for him.

### Steps to reproduce

Run `choco upgrade pulumi` on Windows.

### Expected Behavior

Upgrade of Pulumi should work using Chocolatey

### Actual Behavior

![image](https://user-images.githubusercontent.com/77923/203861101-8507e237-4ce6-4a92-8b62-9944a6f0b5b3.png)

### Additional context

Reported by a user on the Community Slack.

https://pulumi-community.slack.com/archives/C84L4E3N1/p1669307040018239

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikocot** [comment]
I'll let myself add that both originally and now the terminal was in elevated mode. 

I'm also attaching chocolatey logs.
[choco.log](https://github.com/pulumi/pulumi/files/10091821/choco.log)

**Comment by Frassle** [comment]
This looks like an issue in unzipping Pulumi. From the logs it looks like it's trying to use 'C:\ProgramData\chocolatey\tools\7z.exe', are you sure that executable works.

**Comment by mikocot** [comment]
Thanks, I've seen it's related to decompression, but I kind of assumed it must be a faulty script as it worked before for this and different libs. Now that I checked the binary indeed doesn't work, and it looks like 7zip seems to be a common source of choco problems. Mine might be related to this one: https://github.com/chocolatey/choco/issues/2735

Quite weird, that it stopped working now, but maybe there was a policy change across the company. Dunno.
Anyway, now that I've manually replaced the 7zip filles with correct version it works. You can close the issue.

![image](https://user-images.githubusercontent.com/9884950/204250615-50c6e968-7eac-4dcf-9b19-7c20a7e8289c.png)

**Comment by Frassle** [comment]
Great thanks for confirming.
