### ISSUE TITLE
Component resources shouldn't have id properties

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#11462]
### Problem description

All custom resources have an `id` output field which is not part of the schema but is added by the SDK (and docs).

However, component resources do not have an `id` added by the SDK, but the docs do still add the id field.

E.g. https://www.pulumi.com/registry/packages/awsx/api-docs/ec2/vpc/#id_csharp

### Suggestions for a fix

We should add an exception to the docs generation process to not add `id` fields to component resources.

**Comment by justinvp** [comment]
Here's where this is set:

https://github.com/pulumi/pulumi/blob/449307d4d20f386bcc9df923ebc4ef209d09ff50/pkg/codegen/docs/gen.go#L1561-L1566

The fix: if `r.IsComponent`, then the `id` property should not be added.
