### ISSUE TITLE
Update status displays repeated Type column while downloading

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#11472]
If a plugin download occurs mid-update, all of the update columns seem to draw fine, except that newlines keep getting printed, and the Type column repeated, as the following screenshot demonstrates (this is a preview):

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/3953235/204068075-1be9a93a-c505-4067-8029-4ba022ec7b83.png">

**Comment by lunaris** [comment]
I _think_ this should be fixed by #15821, so closing.
