### ISSUE TITLE
Function serialization broken in NodeJS 19.2

### ISSUE THREAD

**Issue by kpitzen** [pulumi/pulumi#11488]
### What happened?

When opening a new PR unrelated to the Node SDK, tests related to function serialization fail due to a missing internal property `[[Scopes]]`

### Steps to reproduce

Run Node SDK unit tests in CI

### Expected Behavior

If no code changes have been made, no tests should fail.

### Actual Behavior

Tests are failing

### Output of `pulumi about`

Not _terribly_ relevant, but:

CLI          
Version      3.46.2-dev.0
Go Version   go1.19.2
Go Compiler  gc

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/kpitzen
User           kpitzen
Organizations  kpitzen, EpicGames, pulumi

### Additional context

Here is the original failing job:
https://github.com/pulumi/pulumi/actions/runs/3577856744/jobs/6017440059

And a no-op job with _only_ a README change:
https://github.com/pulumi/pulumi/actions/runs/3578273088/jobs/6018337627

The failing branch of code ends here:
https://github.com/pulumi/pulumi/blob/e43e98e5a7abadca7ab04c5f6bf9511b2dcb0478/sdk/nodejs/runtime/closure/v8_v11andHigher.ts#L59

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Well would you look at that, [Node.js 19.2.0 dropped yesterday 2022-11-29](https://nodejs.org/en/download/releases/).

I'm guessing that's changed some internal details, we better make sure we're testing on 19.2 _and_ some older versions for this.

**Comment by Frassle** [comment]
Node 19.2 updated to a newer version of V8, and it looks like V8 has started to remove that "[[Scopes]]" property: https://github.com/v8/v8/commit/735401e1fb317979afe205ff0deaf3d7bf35c835

This stuff hasn't been touched for four years, and I'm not sure what we could do to lookup captured variables without going through [[Scopes]].

Given this is hard blocking everything I'm going to state that we _do not support_ NodeJS 19.2 and higher for the time being. I'll update docs and CI quickly now to get pipelines moving, and then we need to work out if we can fix this.
