### ISSUE TITLE
[sdks/python] Cache virtual environments for integration tests

### ISSUE THREAD

**Issue by kpitzen** [pulumi/pulumi#11485]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, each integration test creates its own virtual environment, installs the released version of the pulumi python sdk and all its associated dependencies AND the local version and all its dependencies.  This can take between 2 to 6 minutes per test depending on how much dependencies differ between the two.  Instead of creating venvs based on the directory they're created in, we should create venvs based on the hashed contents of `requirements.txt` and reuse them on hash collision.

### Affected area/feature

Integration tests

**Comment by justinvp** [comment]
Would this be a new option in [`ProgramTestOptions`](https://github.com/pulumi/pulumi/blob/e43e98e5a7abadca7ab04c5f6bf9511b2dcb0478/pkg/testing/integration/program.go#L147)? Something like `UseSharedVirtualEnv bool`?

**Comment by kpitzen** [comment]
> Would this be a new option in [`ProgramTestOptions`](https://github.com/pulumi/pulumi/blob/e43e98e5a7abadca7ab04c5f6bf9511b2dcb0478/pkg/testing/integration/program.go#L147)? Something like `UseSharedVirtualEnv bool`?

I think that makes sense.  It feels like it ought to default to `true` for now, and we can add exceptions to tests where needed?

**Comment by justinvp** [comment]
> It feels like it ought to default to `true` for now

Maybe... The only thing that gives me pause is that this is used outside this repo, and even by customers. So we have to be thoughtful about some changes and how it'd impact other users.

I guess an alternative would be an envvar to opt-in globally.

**Comment by kpitzen** [comment]
Thinking about this - that makes sense.  Default to `false`, and overlay our new env var to set it to `true` wherever it makes sense to.
