### ISSUE TITLE
Support explicit providers for packaged components

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#11520]
SDKs don't currently support specifying an explicit provider to use when constructing a packaged component (MLC).

This hasn't been too limiting so far as all our first-party component packages aren't currently configurable, but that likely won't always be true, and certainly users may want to offer component packages that are configurable via explicit providers.

This limitation also doesn't work well with the feature to disable default providers. If you configure your stack to enforce that no resource should use a default provider (e.g. `pulumi:disable-default-providers: ["*"]`), and your stack is using packaged components, you'll get an error associated with the packaged component (e.g. `Default provider for 'awsx' disabled. 'awsx:ec2:Vpc' must use an explicit provider.`) that you can't do anything about aside from changing `disable-default-providers` to list the providers (like `"aws"`) rather than the `"*"` catch-all.

## Languages

- [x] Go
- [x] Node.js: Supported as of https://github.com/pulumi/pulumi/pull/13282
- [x] Python: Supported as of https://github.com/pulumi/pulumi/pull/13282
- [ ] https://github.com/pulumi/pulumi-dotnet/issues/179
- [ ] https://github.com/pulumi/pulumi-yaml/issues/505
- [ ] https://github.com/pulumi/pulumi-java/issues/1207

---

Vote on this issue by adding a 👍 reaction.

**Comment by AaronFriel** [comment]
Seems like we ought to handle this in the engine - based on `parent` - to limit the number of resource options that component authors need to handle correctly.

It would be even better if we were able to automatically apply `parent` and `provider[s]` resource options to resources registered during a `Construct` call.

**Comment by Frassle** [comment]
> It would be even better if we were able to automatically apply parent and provider[s] resource options to resources registered during a Construct call.

I'd prefer this. I think we can do this pretty easily by spinning up a new `ResourceMonitor` for the construct call to enforce parent and then get the rest for free by making the engine do propagation for provider/providers.

**Comment by justinvp** [comment]
I'm going to close this as fixed as the customer request was addressed with https://github.com/pulumi/pulumi/pull/13282.

I've opened separate issues to track investigating and fixing (if needed) the remaining SDKs:
- https://github.com/pulumi/pulumi-dotnet/issues/179
- https://github.com/pulumi/pulumi-yaml/issues/505
- https://github.com/pulumi/pulumi-java/issues/1207
