### ISSUE TITLE
Missing Pu service comments/checks in GitHub project, when using the Automation API

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi#11574]
### What happened?

Following scenario:

GitHub repo where our Pulumi GitHub App is connected to it.

## Prerequisite

- In the `.github` folder is a reusable workflow called `pulumi.yaml` which get called by the parent workflow `build.yaml`

### 1. Run

Writing a "classic" Pulumi program and creating PR. Everything work as expected. The Comment from the Pulumi service get add to the PR. Via the App and the github action itself!

![image](https://user-images.githubusercontent.com/38325136/206141030-632093c1-ffeb-41e4-9f0a-6c41a0e3d5c8.png)

https://github.com/dirien/github-pulumi-action/pull/10

### 2. Run via Automation API

Now, I rewrite the "classic" Program to use the automation API. Also the workflow  `pulumi.yaml` gets rewritten: The Pulumi GitHub Action gets removed and a simple `go run .` added. Env Variables for the service gets added too!

No comments
![image](https://user-images.githubusercontent.com/38325136/206141590-7354f46c-acd5-4346-bef6-acb123e772e2.png)

https://github.com/dirien/github-pulumi-action/pull/12

When I check the Pulumi Service, I see the succesful preview:
![image](https://user-images.githubusercontent.com/38325136/206141761-b5ff5f68-d932-4e30-b764-03ddded6ac25.png)

### Steps to reproduce

Here is the demo Repo:

https://github.com/dirien/github-pulumi-action

### Expected Behavior

Comments/checks get posted to the PR

### Actual Behavior

No Comments/checks get posted to the PR

### Output of `pulumi about`

-

### Additional context

We made a first investigation with @blampe and he has saw the demo in action too.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
https://github.com/pulumi/pulumi-service/issues/11402 is related -- we might be able to work around this server-side, but it's worth investigating if something changed on the CLI side.

It might be helpful to compare the metadata for an update that got comments vs. one that didn't:

GitHub action -- comments:

```
ci.build.id         | 3342499889
ci.build.number     | 156
ci.build.type       | pull_request
ci.build.url        | https://github.com/blampe/pulumi-playground/actions/runs/3342499889
ci.pr.headSHA       | 09630c350221b8c97fcdad80096baf8096856122
ci.pr.number        | 36
ci.system           | GitHub Actions
exec.agent          | pulumi/actions@v3
exec.kind           | auto.local
git.author          | Bryce Lampe
git.author.email    | ...
git.committer       | GitHub
git.committer.email | noreply@github.com
git.dirty           | false
git.head            | cbb99b0cbe34ea0196092e4b397f499811cce17f
git.headName        | status-test
updatePlan          | false
vcs.kind            | github.com
vcs.owner           | blampe
vcs.repo            | pulumi-playground
```

versus automation API -- no comments:

```
ci.build.id     | 3577520425
ci.build.number | 23
ci.build.type   | pull_request
ci.build.url    | https://github.com/dirien/github-pulumi-action/actions/runs/3577520425
ci.pr.headSHA   | ca91a0cf8700943b38f723b0c4c09dbff96637a8
ci.pr.number    | 5
ci.system       | GitHub Actions
exec.kind       | auto.inline
updatePlan      | false
```

In the latter case we _probably_ still have enough metadata to post a comment.

But why is the automation API updating sending so much less metadata? They're both using the CLI under the hood, right?

**Comment by omercnet** [comment]
All GitHub internal envs still exist for the shared workflow

**Comment by dirien** [comment]
Hi @omercnet,

this should be fixed by now. Sorry for the later reply. Let me know if you have any further questions.
