### ISSUE TITLE
Use of undeclared err in Go examples

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi#11584]
### What happened?

I just tried to upgrade dependencies in pulumi-azure like so:
```
- 11         github.com/pulumi/pulumi-terraform-bridge/v3 v3.30.0
- 12         github.com/pulumi/pulumi/sdk/v3 v3.40.3-0.20220928152524-977c89fcacd7
+ 11         github.com/pulumi/pulumi-terraform-bridge/v3 v3.34.0
+ 12         github.com/pulumi/pulumi/sdk/v3 v3.48.1-0.20221205185749-86e7d56df231
```

After regenerating the SDKs, I see a bunch of diffs like this one in Go:

```go
  27    //        func main() {
  28    //                pulumi.Run(func(ctx *pulumi.Context) error {
- 29    //                       _, err := backup.GetPolicyFileshare(ctx, &backup.GetPolicyFileshareArgs{
+ 29    //                       _, err = backup.GetPolicyFileshare(ctx, &backup.GetPolicyFileshareArgs{
```

`:=` has been changed to `=` but this is the first occurrence of err so it's undeclared.

There seem to be many instances, although some of those below may be legit if `err` was declared earlier.

```
git diff sdk/go | rg -A 1 '^\-.*_, err :=' | wc -l
     182
```

### Steps to reproduce

I've pushed the branch to pulumi/pulumi-azure/tkappler/upgrade-tf-bridge-3.34.

Steps to repro from `master` in pulumi-azure are

```
cd provider
go get -u -v github.com/pulumi/pulumi-terraform-bridge/v3
go mod tidy
cd ..
make tfgen
make build_go
```

### Expected Behavior

valid Go code in examples

### Actual Behavior

see above

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@aq17, looks like another Go programgen bug. Mind taking a look?

**Comment by thomas11** [comment]
@aq17, I wrote a little script to bisect the p/p version at fault, since 3.40.3 to 3.48 is a pretty large jump. 

```bash
# reset
rm -rf ~/.pulumi/plugins/
git restore .

# upgrade
cd provider
go get -v "github.com/pulumi/pulumi/pkg/v3@v$1"
go get -v "github.com/pulumi/pulumi-terraform-bridge/v3@v$2"
go mod tidy
cd ..

# build
make provider build_go
echo -n "pkg $1, tf-bridge $2: "
git diff sdk/go | rg -A 1 '^\-.*_, err :=' | wc -l
```

However, on my machine I see a surprising result: `pulumi/{pkg,sdk}/v3` version `3.40.3-0.20220928152524-977c89fcacd7` like in master work, but `3.40.3` without the suffix does not.

You can replicate by running the script like this:

```bash
bash test.sh 3.40.3-0.20220928152524-977c89fcacd7 3.30.0
bash test.sh 3.40.3 3.30.0
```

**Comment by aq17** [comment]
@thomas11 could you create a branch with the changed examples? I'm having trouble repro'ing, not sure why I keep getting 
```
no required module provides package github.com/pulumi/pulumi-azure/provider/v5/cmd/pulumi-tfgen-azure; to add it:
        go get github.com/pulumi/pulumi-azure/provider/v5/cmd/pulumi-tfgen-azure
```
even after recursively fetching all dependencies and manually installing that above.

**Comment by thomas11** [comment]
`tkappler/go-err-repro`, thanks!
