### ISSUE TITLE
CLI time elapsed value is negative for a failed resource

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi#11597]
### What happened?

I ran a `pulumi up --refresh --skip-preview` and one of the resources failed the update. The elapsed time is a negative value in this case.

![Screen Shot 2022-12-08 at 11 17 22 AM](https://user-images.githubusercontent.com/9253463/206534077-1f5d9b6f-29cf-42f6-986c-246670fd96f7.png)

### Steps to reproduce

Create a stack with a resource that will fail during a refresh update.

### Expected Behavior

The time elapsed should be a positive number.

### Actual Behavior

The absolute value is correct, but the sign is wrong.

### Output of `pulumi about`

```
CLI
Version      3.48.0
Go Version   go1.19.3
Go Compiler  gc

Host
OS       darwin
Version  12.6.1
Arch     arm64

Dependencies:
NAME                VERSION
...
@pulumi/pulumi      3.48.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Looks related to https://github.com/pulumi/pulumi/issues/11188, which is also about negative timings when `--refresh` is used. I'll close this issue as a dupe.
