### ISSUE TITLE
Implement configuration subset guidance

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#116]
A feature request we've heard from customers is the desire to check, based on a given stack, what AWS regions can be targeted.  (E.g., oops, I used the AWS WAF, so I can only run in us-east-1 and eu-west-1.)  It's not clear how to best generalize this (as it has to do with constraining the configuration parameters to subsets of their normal values), but it sure seems useful; this could also determine that we are even targeting AWS to begin with, versus, say, Azure or Google Cloud.

**Comment by lukehoban** [comment]
We haven't really heard this request again in the last 2 years, and haven't seen upvotes here.  Going to close out - and if a new scenario arises around this we can reopen.
