### ISSUE TITLE
"deletedWith" is ignored

### ISSUE THREAD

**Issue by oskar-martensson** [pulumi/pulumi#11622]
### What happened?

I wanted to deploy a static website in Azure, with a CDN and a custom domain. This needs a DNS record to work, and the DNS record needs the CDN endpoint. The resulting dependencies are like so:
CDN Endpoint -> DNS Record Set -> CDN Custom domain.

This worked for deployment, but not for tear down since Azure needs the DNS Record to be deleted BEFORE the CDN Custom Endpoint.
> Cannot delete custom domain "<my domain>" because it is still directly or indirectly (using \"cdnverify\" prefix) CNAMEd to CDN endpoint "<my cdn endpoint name>.azureedge.net". Please remove the DNS CNAME record and try again.

Therefore I tried setting CDN Custom domain "deletedWith", to be deletedWith the CDN Endpoint. But when running pulumi down, pulumi still tries to delete the CDN Custom domain first.

### Steps to reproduce

Language: Typescript 
Package versions:
- @pulumi/azure-native: 1.88.1
- @pulumi/pulumi: 3.48.0

Pulumi CLI version: v3.49.0

**Gist:**
https://gist.github.com/oskar-martensson/9088ffbc788f15d8ce2351b062da8241

**What I've done:**
Using the example project: https://github.com/pulumi/examples/blob/master/azure-ts-static-website/index.ts
Add an azure-native RecordSet and azure-native CustomDomain.
Use the following dependency chain: CDN Endpoint -> DNS Record Set -> CDN Custom domain.
Set "deletedWith" to the Custom Domain, pointing at the CDN Endpoint.

### Expected Behavior

Pulumi does not attempt to destroy the Custom Domain

### Actual Behavior

Pulumi attempts to delete the Custom Domain

### Output of `pulumi about`

CLI
Version      3.49.0
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.25.0
azure-native  1.88.1
nodejs        unknown

Host
OS       darwin
Version  13.0
Arch     x86_64

This project is written in nodejs: executable='/Users/<xxx>/.nvm/versions/node/v16.14.2/bin/node' version='v16.14.2'

Current Stack: dev

TYPE                                              URN
pulumi:pulumi:Stack                               urn:pulumi:dev::<xxx>::pulumi:pulumi:Stack::<xxx>
pulumi:providers:azure-native                     urn:pulumi:dev::<xxx>::pulumi:providers:azure-native::default_1_88_1
azure-native:resources:ResourceGroup              urn:pulumi:dev::<xxx>::azure-native:resources:ResourceGroup::<xxx>
azure-native:cdn:Profile                          urn:pulumi:dev::<xxx>::azure-native:cdn:Profile::<xxx>
azure-native:storage:StorageAccount               urn:pulumi:dev::<xxx>::azure-native:storage:StorageAccount::<xxx>
azure-native:storage:StorageAccountStaticWebsite  urn:pulumi:dev::<xxx>::azure-native:storage:StorageAccountStaticWebsite::<xxx>
azure-native:storage:Blob                         urn:pulumi:dev::<xxx>::azure-native:storage:Blob::index.html
azure-native:cdn:Endpoint                         urn:pulumi:dev::<xxx>::azure-native:cdn:Endpoint::<xxx>
azure-native:network:RecordSet                    urn:pulumi:dev::<xxx>::azure-native:network:RecordSet::<xxx>
azure-native:cdn:CustomDomain                     urn:pulumi:dev::<xxx>::azure-native:cdn:CustomDomain::<xxx>

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
@oskar-martensson Could you copy the TypeScript program in its entirety, or upload it to a gist for us to include in reproducing the issue?

**Comment by oskar-martensson** [comment]
@AaronFriel Thanks for the quick feedback! I've updated the issue with a gist.

**Comment by justinvp** [comment]
I've found `deletedWith` does not work from both the Node.js and Python SDKs, because it's incorrectly passing the resource itself in the RegisterResource request, rather than the resource's URN:

https://github.com/pulumi/pulumi/blob/cd198333b1b88384568c8327d0fe315a395e4277/sdk/nodejs/runtime/resource.ts#L369

https://github.com/pulumi/pulumi/blob/cd198333b1b88384568c8327d0fe315a395e4277/sdk/python/lib/pulumi/runtime/resource.py#L601

I have a fix and tests in progress.
