### ISSUE TITLE
docs gen producing broken links

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#11620]
the docs gen is producing these broken links
https://www.pulumi.com/registry/packages/gcp/api-docs/compute/instancefromtemplate/[-a-z0-9]*[a-z0-9]
https://www.pulumi.com/registry/packages/gcp/api-docs/compute/instancefrommachineimage/[-a-z0-9]*[a-z0-9]
https://www.pulumi.com/registry/packages/gcp/api-docs/composer/environment/[-a-z0-9]*[a-z0-9]

on these pages
https://www.pulumi.com/registry/packages/gcp/api-docs/compute/instancefromtemplate/
https://www.pulumi.com/registry/packages/gcp/api-docs/compute/instancefrommachineimage/
https://www.pulumi.com/registry/packages/gcp/api-docs/composer/environment/

<img width="733" alt="Screen Shot 2022-12-11 at 6 15 04 PM" src="https://user-images.githubusercontent.com/5489125/206946505-7a22e1db-f460-4f96-9340-126ad8f680f0.png">

the regex expressions prolly need backticks so hugo doesn't think they are links

**Comment by mikhailshilkov** [comment]
I checked the web page source and those links aren't there anymore. Closing as done.
