### ISSUE TITLE
pulumi convert to python doesn't use correct python function for `pulumi.Output.secret`

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#11632]
### What happened?

Converting yaml code with 
```
privateKey:
    Fn::Secret:
      Fn::ReadFile: ${privateKeyPath}
```
to python produces:
```
private_key = pulumi.secret((lambda path: open(path).read())(private_key_path))
```
but it should be `pulumi.Output.secret(....)` 

### Steps to reproduce

1. Run `pulumi convert --language python`  on: https://github.com/pulumi/examples/tree/master/aws-yaml-ansible-wordpress
2. Look at resultant python code - or even try to run it and you'll see that `pulumi.secret` is not valid Python code.

### Expected Behavior

Should produce valid python code - see above.

### Actual Behavior

produces invalid python code - see above.

### Output of `pulumi about`

CLI          
Version      3.49.0
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME     VERSION
aws      unknown
command  unknown
yaml     unknown

Host     
OS       darwin
Version  12.5.1
Arch     x86_64

This project is written in yaml

Backend        
Name           pulumi.com

No dependencies found

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Thanks for finding this, I've made a fix to codegen for this in #11636.
