### ISSUE TITLE
docs gen bug? link in tls api docs 404ing

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#11656]
on this page https://www.pulumi.com/registry/packages/tls/api-docs/privatekey/

there is a link: `is not supported`

which sends you here: https://www.pulumi.com/registry/packages/tls/docs#limitations
and 404s

<img width="913" alt="404" src="https://user-images.githubusercontent.com/5489125/207748613-8ff044c7-4de0-468b-8737-3eafdbfdc0ca.png">

**Comment by susanev** [comment]
i think we should remove links like this, in which we don't have this content in our docs. for what its worth unsure if we want to keep the trimspace link there.

**Comment by adityakode** [comment]
what do you think the link should lead to?

**Comment by mikhailshilkov** [comment]
I don't see this link anymore, so I'll close the issue as done
