### ISSUE TITLE
Providers: Support basic retry functionality for failed provider requests

### ISSUE THREAD

**Issue by kpitzen** [pulumi/pulumi#11654]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, when a request to a provider fails, Pulumi reports the error back up the stack and the entire deployment ceases.  It would be ideal if we could support a basic retry strategy configured at the provider level to add resiliency to our network calls.  Exponential backoff would be ideal, but even a configurable constant delay with configurable retries would be an improvement here.  Once this is configured at the provider level, any calls made by that provider integration would then retry using the configured strategy until either success or exhaustion.

### Affected area/feature

Providers

**Comment by lukehoban** [comment]
This looks to be very similar to #7932 which has additional details and use cases, so closing this one as a duplicate.
