### ISSUE TITLE
Incorrect arg type for Construct method of ComponentResource

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi#11690]
I believe that the ResourceOptions argument should be a variadic slice to accommodate multiple resource options. The current interface only allows a single option.

https://github.com/pulumi/pulumi/blob/v3.50.0/sdk/go/pulumi/provider.go#L34
https://github.com/pulumi/pulumi/blob/v3.50.0/sdk/go/pulumi/provider/provider.go#L30

**Comment by justinvp** [comment]
Multiple resource options from the `ConstructRequest` are being set from a single `ResourceOption`:

https://github.com/pulumi/pulumi/blob/87764984c8308557533ca32d0052254b2e97b9a7/sdk/go/pulumi/provider.go#L109-L121

We could consider changing the signature to be a variadic slice to be consistent with how `ResourceOption` is used elsewhere, but I'm not sure it'd be worth the breaking change as users would have to update the signature when updating to a version that included the change. As such, I'm inclined to close this.

**Comment by lblackstone** [comment]
I didn't realize that the `ResourceOption` could include multiple options, so this change isn't needed after all. The signature is a bit confusing, but not worth a breaking change at this point.
