### ISSUE TITLE
Spurious `error: error reading from server: EOF` in normal error path(s)

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#11706]
If I `pulumi up` before `npm install`ing dependencies in a Pulumi project folder with `runtime: nodejs` I see the following:

```
Diagnostics:
  pulumi:pulumi:Stack (pulumistack-simple-dev):
    error: It looks like the Pulumi SDK has not been installed. Have you run npm install or yarn install?

    error: error reading from server: EOF
```

This includes a spurious `error: error reading from server: EOF` at the end.  I believe that until sometime recently that was not rendered as part of the output in that situation.

**Comment by RobbieMcKinstry** [comment]
I believe you're correct! That's a new error. I'd like to try to repro this; I imagine this is pretty easy to isolate and solve.
