### ISSUE TITLE
Improve typing of resource arguments in Python

### ISSUE THREAD

**Issue by pmuller** [pulumi/pulumi#11732]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Coming from TypeScript, the Python API sometimes feels more verbose.

In TypeScript, we would use a simple object:

```typescript
import { Cluster } from '@pulumi/gcp/container'
new Cluster('foo', {description: 'hello'})
```

Whereas in Python we need an additional import to achieve the same:

```python
from pulumi_gcp.container import Cluster, ClusterArgs
Cluster('foo', ClusterArgs(descriptions='hello'))
```

In TypeScript, we can compose arguments using the spread syntax:

```typescript
const args = {clusterIpv4Cidr: "1.2.3.4"}
new Cluster('foo', {description: 'hello', ...args})
```

It's almost the same when unpacking a dict in Python:
```python
args = {"cluster_ipv4_cidr": "1.2.3.4"}
Cluster('foo', ClusterArgs(description='hello', **args))
```

However, doing the same using the args class requires using the class attributes dictionary, which feels _wrong_, or at least hackish:
```python
args = ClusterArgs(cluster_ipv4_cidr="1.2.3.4")
Cluster('foo', ClusterArgs(description='hello', **args.__dict__))
```

And there is an edge case where the way the `@pulumi.input_type` classes work is misleading the type checker and make it fail to detect a typing issue. For example:
```python
ClusterArgs(**ClusterReleaseChannelArgs(channel="foo").__dict__)
``` 

In TypeScript, we can easily create new types based on existing one, which allow things like:
```typescript
import { NodePool, NodePoolArgs } from "@pulumi/gcp/container";
// Prepare arguments without the mandatory "cluster" argument
type PartialNodePoolArgs = Omit<NodePoolArgs, "cluster">;
const partialArgs: PartialNodePoolArgs = { name: "nodePoolName" };
// Reuse partial args and pass the mandatory "cluster" argument
new NodePool("foo", { ...partialArgs, cluster: "clusterName" });
```

The closer we can do in Python is to get rid of typing for the partial arguments:
```python
from pulumi_gcp.container import NodePool, NodePoolArgs
partial_args = {"name": "nodePoolName"}
NodePool("foo", NodePoolArgs(**partial_args, cluster="clusterName"))
```

Using [TypedDict](https://docs.python.org/3/library/typing.html#typing.TypedDict), the syntax could get easier to work with:
```python
Cluster('foo', {"description": "hello", **partial_args})
```

AFAIK, there is no way to create new TypedDict based on existing ones, like we do with types and utility types in TypeScript.
However I suspect those can be built in Python too (not sure how).

### Affected area/feature

Supporting another notation is possible by adding one more overload.
But that would make maintainance costlier.

**Comment by justinvp** [comment]
See also: https://github.com/pulumi/pulumi/discussions/11500

**Comment by julienp** [comment]
We've shipped TypedDict based input types for AWS and Kubernetes SDKs, with other SDKs following in the coming days and weeks. See also https://github.com/pulumi/pulumi/issues/12689

Read the blog about the changes https://www.pulumi.com/blog/pulumi-loves-python/
