### ISSUE TITLE
[codegen/python] deprecated warning for aws.secretsmanager.get_secret

### ISSUE THREAD

**Issue by fujiapple852** [pulumi/pulumi#11739]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Calling `aws.secretsmanager.get_secret(...)` results in deprecated warnings for attributes of `GetSecretResult` even if these attributes are not accessed:

```
warning: rotation_enabled is deprecated: Use the aws_secretsmanager_secret_rotation data source instead
warning: rotation_lambda_arn is deprecated: Use the aws_secretsmanager_secret_rotation data source instead
warning: rotation_rules is deprecated: Use the aws_secretsmanager_secret_rotation data source instead
``` 

pulumi: 3.18.1
pulumi-aws: 4.29.0

### Steps to reproduce

1. Create a project with:
```python
import pulumi
import pulumi_aws as aws
secret_arn = aws.secretsmanager.get_secret(name="...").arn
```
2. Run `pulumi up`
3. Observe warnings:
```
warning: rotation_enabled is deprecated: Use the aws_secretsmanager_secret_rotation data source instead
warning: rotation_lambda_arn is deprecated: Use the aws_secretsmanager_secret_rotation data source instead
warning: rotation_rules is deprecated: Use the aws_secretsmanager_secret_rotation data source instead
```

**Comment by RobbieMcKinstry** [comment]
@lukehoban can you clarify why this is a Python codegen issue? At first glance, this appears to be an issue the Terraform bridge because it explicitly mentions using a `data source`.

**Comment by RobbieMcKinstry** [comment]
It's worth checking if this message still appears, come to think of it ;D

**Comment by Frassle** [comment]
> can you clarify why this is a Python codegen issue?

It's the python codegen that's adding warning calls for these fields, but it looks like it's warning on _result_ types which the user doesn't have any control over, e.g. see https://github.com/pulumi/pulumi-aws/blob/master/sdk/python/pulumi_aws/secretsmanager/get_secret.py#L47

**Comment by RobbieMcKinstry** [comment]
Ah, thanks! Since this issue is ~18 months old, I'm going to see if I can repro.

**Comment by RobbieMcKinstry** [comment]
Well, those fields are still deprecated in the registry, so it looks like this is still a problem. One solution would be to only show the deprecation _on field access_, which we can do in Python (but wouldn't be true for Go).

Or, we can remove deprecation warnings for Output fields, which doesn't sound as clean to me since it's hiding important information from the user.

**Comment by thundergolfer** [comment]
Is there anything the end user can do to suppress these warnings? We get like six dozen of them each `preview` and `up` operation.

**Comment by cdl-altium** [comment]
Still present 2.5 years after first raised (and more alerts present too):
```
Diagnostics:
  pulumi:pulumi:Stack (<STACK NAME REDACTED>):
    warning: rotation_enabled is deprecated: Use the aws_secretsmanager_secret_rotation data source instead
    warning: rotation_lambda_arn is deprecated: Use the aws_secretsmanager_secret_rotation data source instead
    warning: rotation_rules is deprecated: Use the aws_secretsmanager_secret_rotation data source instead
    warning: rotation_enabled is deprecated: Use the aws_secretsmanager_secret_rotation data source instead
    warning: rotation_lambda_arn is deprecated: Use the aws_secretsmanager_secret_rotation data source instead
    warning: rotation_rules is deprecated: Use the aws_secretsmanager_secret_rotation data source instead
```

I'm not using any of these rotation options. I am only invoking `get_secret()` method.

Do note further that, in current Terraform (4.66.0), some of the features are not even available any more (full deprecated) - see https://registry.terraform.io/providers/hashicorp/aws/3.26.0/docs/resources/secretsmanager_secret#rotation_lambda_arn and then https://registry.terraform.io/providers/hashicorp/aws/latest/docs

**Comment by joeduffy** [comment]
Unless I am mistaken, this patch will address the issue:

```patch
diff --git a/pkg/codegen/python/gen.go b/pkg/codegen/python/gen.go
index 536a64daa..cf82430be 100644
--- a/pkg/codegen/python/gen.go
+++ b/pkg/codegen/python/gen.go
@@ -1505,6 +1505,15 @@ func (mod *modContext) genProperties(w io.Writer, properties []*schema.Property,
 		if prop.Comment != "" {
 			printComment(w, prop.Comment, indent+"        ")
 		}
+
+		// Emit the deprecation message, if present, on *access* to the property, rather than initialization,
+		// to avoid spamming end users with irrelevant deprecation messages.
+		if prop.DeprecationMessage != "" {
+			escaped := strings.ReplaceAll(prop.DeprecationMessage, `"`, `\"`)
+			fmt.Fprintf(w, "%s        warnings.warn(\"\"\"%s\"\"\", DeprecationWarning)\n", indent, escaped)
+			fmt.Fprintf(w, "%s        pulumi.log.warn(\"\"\"%s is deprecated: %s\"\"\")\n\n", indent, pname, escaped)
+		}
+
 		fmt.Fprintf(w, "%s        return pulumi.get(self, %q)\n\n", indent, pname)
 
 		if setters {
@@ -1551,13 +1560,6 @@ func (mod *modContext) genMethods(w io.Writer, res *schema.Resource) {
 			fmt.Fprintf(w, "            if %s and not isinstance(%s, %s):\n", pname, pname, ptype)
 			fmt.Fprintf(w, "                raise TypeError(\"Expected argument '%s' to be a %s\")\n", pname, ptype)
 
-			if prop.DeprecationMessage != "" {
-				escaped := strings.ReplaceAll(prop.DeprecationMessage, `"`, `\"`)
-				fmt.Fprintf(w, "            if %s is not None:\n", pname)
-				fmt.Fprintf(w, "                warnings.warn(\"\"\"%s\"\"\", DeprecationWarning)\n", escaped)
-				fmt.Fprintf(w, "                pulumi.log.warn(\"\"\"%s is deprecated: %s\"\"\")\n\n", pname, escaped)
-			}
-
 			// Now perform the assignment.
 			fmt.Fprintf(w, "            pulumi.set(__self__, \"%[1]s\", %[1]s)\n", pname)
 		}
@@ -1808,9 +1810,9 @@ func (mod *modContext) genFunction(fun *schema.Function) (string, error) {
 			if i > 0 {
 				fmt.Fprintf(w, ",")
 			}
-			// Use the get_dict_value utility instead of calling __ret__.get directly in case the __ret__
-			// object has a get property that masks the underlying dict subclass's get method.
-			fmt.Fprintf(w, "\n        %[1]s=__ret__.%[1]s", PyName(ret.Name))
+			// Use the pulumi.get utility instead of calling __ret__.get directly in case the __ret__
+			// object defines a get property with behavior other than simply returning the property value.
+			fmt.Fprintf(w, "\n        %[1]s=pulumi.get(__ret, '%[1]s')", PyName(ret.Name))
 		}
 		fmt.Fprintf(w, ")\n")
 	}
```

I verified this by manually applying these changes to `venv/lib/python3.10/site-packages/pulumi_aws/secretsmanager/get_secret.py`.

I do not believe this affects other languages as we seem to use the native deprecation mechanisms and/or comments, which do not lead to warnings upon initialization (versus access), nor do they print to the console. I will double check.

**Comment by joeduffy** [comment]
This is amazing, thank you @dixler!!!
