### ISSUE TITLE
Renamed resource URN is impossible to rename back because it is invalid

### ISSUE THREAD

**Issue by melkamar** [pulumi/pulumi#11746]
### What happened?

I changed a child-parent relationship for an existing Kubernetes resource. That caused a problem where pulumi thought that's a whole new resource.

I wanted to rename the resource in the state manually, because as I understand it, the parent-child relation is defined by the resource name:
```bash
pulumi state rename \
    'urn:pulumi:dev::xxx-dev::kubernetes:core/v1:Namespace::amazon_cloudwatchNamespace' \
    'urn:pulumi:dev::xxx-dev::eks:index:Cluster$kubernetes:core/v1:Namespace::amazon_cloudwatchNamespace'
```

This command succeeded, but (I'll blame the [documentation](https://www.pulumi.com/docs/reference/cli/pulumi_state_rename/) here) the new name was not just the second argument. In fact, the second argument got _appended_ to a "hardcoded prefix" `urn:pulumi:dev::xxx-dev::kubernetes:core/v1:Namespace` (which, when looking at it now, makes sense, it's just the docs do not mention that).

So, the new URN of the resource is:
```
urn:pulumi:dev::xxx-dev::kubernetes:core/v1:Namespace::urn:pulumi:dev::xxx-dev::eks:index:Cluster$kubernetes:core/v1:Namespace::amazon_cloudwatchNamespace
```

This is also reported by `pulumi stack --show-urns`.

When I realized my mistake, I wanted to fix this mistake it by renaming the resource back to the original, so I ran
```bash
pulumi state rename \
    'urn:pulumi:dev::xxx-dev::kubernetes:core/v1:Namespace::urn:pulumi:dev::xxx-dev::eks:index:Cluster$kubernetes:core/v1:Namespace::amazon_cloudwatchNamespace' \
    'amazon_cloudwatchNamespace'
```

But now I am getting error from the pulumi CLI:
```
error: The provided input URN is not valid
```

... which is probably true, fair enough, but then I shouldn't have been allowed to do the rename in the first place. And the state clearly internally has this URN because it's printed out to me.

Luckily this is just a stack in development so I can just nuke it, but if there is a way to force-rename a resource with an invalid URN, that would be great.

Edit: `pulumi destroy` seems to not have any problems with the invalid URN (although it renders then resource name as `urn:pulumi:dev`).

### Steps to reproduce

```bash
pulumi state rename <URN> <other-URN>
pulumi stack --show-urns

# This will fail
pulumi state rename <long-long-URN> <valid name>
```

### Expected Behavior

Pulumi should not allow me to rename a resource to an invalid URN

### Actual Behavior

Pulumi let me rename a resource to an invalid URN and now I cannot get it back

### Output of `pulumi about`

```
CLI
Version      3.50.2
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.24.0
awsx        1.0.1
docker      3.6.1
eks         1.0.1
kubernetes  3.23.1
python      unknown

Host
OS       darwin
Version  12.5.1
Arch     x86_64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/melkamar
User           melkamar
Organizations  melkamar

Dependencies:
NAME         VERSION
pip          22.3.1
pulumi-awsx  1.0.1
pulumi-eks   1.0.1
setuptools   65.6.3
wheel        0.38.4
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by gainskills** [comment]
I ran into the same issue today with the latest version: 3.85.0
Figured it out by `pulumi stack export` and edit the export state file then `pulumi stack import`
