### ISSUE TITLE
sdk/go: Support fs.FS

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi#11786]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The [pulumi Go package](https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v3/go/pulumi)
offers three ways of creating an Asset: NewFileAsset, NewRemoteAsset, and NewStringAsset.
NewFileAsset accepts a file path on-disk.

Go 1.16 added a new `io/fs` package that defines a common read-only file-system
abstraction: https://pkg.go.dev/io/fs#FS

This issue is a request to support `fs.FS` for file assets with, possibly,
an API similar to the following.

```go
func NewFSAsset(fsys fs.FS, path string) Asset
```

### Affected area/feature

Go SDK

**Comment by Frassle** [comment]
These do really need to be on the real filesystem. I'm always a little worried about using abstract filesystem interfaces for things that actually only work on the real filesystem (usually because of invoking other processes) and so aren't actually covered by just an interface to describe a filesystem.

**Comment by abhinav** [comment]
@Frassle I didn't realize that they need to be on the file system. That makes sense—if the file path needs to cross process boundaries, then this cannot be an fs.FS. That would only work if we were sending the raw bytes around.

**Comment by abhinav** [comment]
The files need to be on-disk, which isn't guaranteed with fs.FS. Closing as not planned.
