### ISSUE TITLE
pulumi new: Ignore hidden files

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi#11789]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`pulumi new` fails with an error when there are any files in a folder.

```
error: [..] is not empty; rerun in an empty directory, pass the path to an empty directory to --dir, or use --force
```

Doing `git init` after starting a new project is a common workflow.
This means that users will often see this:

```
$ git init
$ pulumi new aws-go
error: [..] is not empty; rerun in an empty directory, pass the path to an empty directory to --dir, or use --force
# Ugh.
$ rm -rf .git
$ pulumi new aws-go
$ git init
```

We should change the CLI to ignore hidden files
when deciding if a directory is empty for this purpose.

### Affected area/feature

CLI

**Comment by Frassle** [comment]
> We should change the CLI to ignore hidden files

Note that most of our templates contain a ".gitignore" which risks splatting over any existing user ".gitignore".

Just special casing that it's ok to have a ".git" seems safe and probably covers the most frequent trip here.

**Comment by justinvp** [comment]
> Just special casing that it's ok to have a ".git" seems safe and probably covers the most frequent trip here.

👍 I was going to say the same thing 😄

**Comment by abhinav** [comment]
I agree that the .gitignore makes this a bit iffy. I think it makes sense to start with ignoring just '.git' and maybe other VCS directories.
