### ISSUE TITLE
Diff display for string values with YAML contents displays empty objects incorrectly

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#11799]
This program:

```go
package main

import (
	p "github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	p.Run(func(ctx *p.Context) error {
		ctx.Export("foo", p.String("foo:\n  bar: {}\n  baz: {}\n"))
		return nil
	})
}
```

Renders this on `pulumi up`:

```
Updating (dev)

View Live: https://app.pulumi.com/lukehoban/goawstest/dev/updates/1

     Type                 Name           Status              
 +   pulumi:pulumi:Stack  goawstest-dev  created (0.00s)     


Outputs:
    foo: (yaml) {
        foo: {
        }
    }


Resources:
    + 1 created

Duration: 2s
```

Note that it fails to render `bar` and `baz`.

If a diff is introduced - like adding a comment to the YAML string - the update diff is also wrong:

```go
package main

import (
	p "github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	p.Run(func(ctx *p.Context) error {
		ctx.Export("foo", p.String("#foo\nfoo:\n  bar: {}\n  baz: {}\n"))
		return nil
	})
}
```

```
Previewing update (dev)

View Live: https://app.pulumi.com/lukehoban/goawstest/dev/previews/1416a1a4-251b-455f-b794-e597e3351975

     Type                 Name           Plan     
     pulumi:pulumi:Stack  goawstest-dev           


Outputs:
  ~ foo: (yaml) {
        foo: {
        }
    }

Resources:
    1 unchanged
```

Note that:
1. `bar` and `baz` are still missing
2. The comment that was introduced is not rendered in the diff
3. Pulumi shows a `~` indicating a diff, but not diff in the object

**Comment by aq17** [comment]
Not rendering `bar` and `baz` is currently expected behavior – we don't print empty values ([shouldPrintPropertyValue](https://github.com/pulumi/pulumi/blob/master/pkg/backend/display/object_diff.go#L236)) , but I think it could make sense to remove that?
cc @dixler

**Comment by dixler** [comment]
@aq17 I did some digging and the behavior of omitting falsey/null/empty values in outputs was introduced in 2017.
https://github.com/pulumi/pulumi/commit/53cf9f8b600a42fa0187ae2de848d4b4a5fd915c

The motivation is the view that outputting empty values will produce a lot of clutter.

Removing it seems reasonable and a quick fix.

**Comment by lukehoban** [comment]
I think the deeper issue might be point (2).  

Fundamentally, it feels like we should never show an empty diff if there is a diff.  So my assumption is that the behaviour should be that if there is a diff being reported:
a. if the YAML based rendering does also indicate a diff, show that
b. if the YAML based rendering doesn't indicate a diff, show the text based diff instead

**Comment by dixler** [comment]
reply race condition. commenting this for future context to link the PRs to this issue.

I've done more digging to address 2 and 3

> 2. The comment that was introduced is not rendered in the diff
> 3. Pulumi shows a ~ indicating a diff, but not diff in the object

https://github.com/pulumi/pulumi/pull/9380 and https://github.com/pulumi/pulumi/pull/9484 introduced changes that render JSON/YAML parsable strings as objects in diffs.

as such, `"foo:\n  bar: {}\n  baz: {}\n"` and `"#foo\nfoo:\n  bar: {}\n  baz: {}\n"` are semantically equivalent.
