### ISSUE TITLE
go.mod: Bump to Go 1.18

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi#11798]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The `{tests,sdk,pkg}/go.mod` files are currently set to 1.17.
We should raise these to 1.18 so that we can use features that are available in 1.18.

To help make the decision:
- Our README states that we require at least Go 1.18
- CI runs against 1.18 or higher
- 1.20 will release in a few weeks, at which point 1.18 will stop receiving patches

**Comment by iwahbe** [comment]
Upgrading `{sdk,pkg}/go.mod` is a breaking change for downstream users with older toolchains. We're working on ensuring that that none of our downstream breaks, then well upgrade. Thanks for bringing this up, we'll take it into consideration.

**Comment by abhinav** [comment]
I completely understand, although I'd like to clarify a minor detail:

Updating the go directive is not a breaking change. It's not a minimum version bound in the standard sense of version directives. It indicates what semantics the code was written to assume. Raising the go directive alone will not break anyone. If we try to use new syntax (generics, or using `any` in place of `interface{}`), which we can do only after raising the directive—that'll break users, and that's when the compiler will tell them that our `go` directive is higher than the version they're using.

We can mitigate these breakages with build flags, and we can verify this by testing with older Go toolchains that we want to support which, worth noting that our CI currently only runs on 1.18 and 1.19.

Although, I suspect some sort of support policy is warranted since we can't indefinitely support old toolchains.
Upstream Go will publish patches only for the current and last minor—so 1.19 and 1.18 right now, and sometime in the next month, only 1.20 and 1.19.

Regardless, I'm on-board with waiting for the plan to prevent those breakages.

**Comment by abhinav** [comment]
Minor update on this: the pkg/ module is already broken on 1.17.
`go test ./...` will refuse to run with the following error:

```
% go test ./...
package github.com/pulumi/pulumi/pkg/v3/backend/filestate
        imports gocloud.dev/blob/azureblob
        imports github.com/Azure/azure-sdk-for-go/sdk/azcore: build constraints exclude all Go files in [...]/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.1.1
package github.com/pulumi/pulumi/pkg/v3/backend/filestate
        imports gocloud.dev/blob/azureblob
        imports github.com/Azure/azure-sdk-for-go/sdk/azcore/policy: build constraints exclude all Go files in [...]/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v1.1.1/policy
package github.com/pulumi/pulumi/pkg/v3/backend/filestate
        imports gocloud.dev/blob/azureblob
        imports github.com/Azure/azure-sdk-for-go/sdk/azidentity: build constraints exclude all Go files in [...]/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azidentity@v1.0.0
package github.com/pulumi/pulumi/pkg/v3/backend/filestate
        imports gocloud.dev/blob/azureblob
        imports github.com/Azure/azure-sdk-for-go/sdk/storage/azblob: build constraints exclude all Go files in [...]/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/storage/azblob@v0.4.1
```

If we run `go test` individually on all packages inside pkg/, 57 out of 82 packages fail on 1.17.

```bash
go list ./... | while read -r PKG; do
        if go test $PKG &>/dev/null; then
                echo $PKG >> good.txt
        else
                echo $PKG >> bad.txt
        fi
done
```

```
% wc -l good.txt bad.txt
      25 good.txt
      57 bad.txt
      82 total
```

Worth noting that the sdk/ package is still green on 1.17.

So if we're concerned about breakage:
- we can leave sdk/'s go directive alone
- raise pkg/
- possibly, add tests to verify sdk/ keeps working with 1.17

**Comment by abhinav** [comment]
Quick update on this:

@pulumi/platform discussed this. Our consensus was:

- Raising the go directive is not directly a breaking change. It doesn't change the version of the compiler you can use—only the code that is compiled dictates that. So if our code begins using `any` or generics (likely following this change), it'll stop compiling with 1.17.
- Even if it was a change that prevented use of older compilers, [our documentation](https://www.pulumi.com/docs/intro/languages/go/) specifically states that we allow using supported Go versions, as defined by the upstream Go support policy, which is current and prior minor versions. With the release of Go 1.20, only Go 1.20 and 1.19 are supported. So pulling support for 1.17 is acceptable.
- pkg/ already does not compile with 1.17.
- Major providers  that we checked manually were already using 1.19.

So, barring any major pushback on this, I'll be landing the #11807 tomorrow.
