### ISSUE TITLE
pulumi up: Move "yes, using Update Plans" to bottom

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi#11800]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

`pulumi up` currently posts this message:

    Do you want to perform this update?
      [experimental] yes, using Update Plans (https://pulumi.com/updateplans)
      yes
      no
      details

Multiple users have reported that the 'yes' (non-experimental) gets lost in the
line noise generated by the experimental entry.
I ran into this during my initial onboarding as well.

To resolve this, we should move the experimental option to the bottom.

    Do you want to perform this update?
      yes
      no
      details
      [experimental] yes, using Update Plans (https://pulumi.com/updateplans)

### Affected area/feature

CLI

**Comment by dixler** [comment]
SGTM
