### ISSUE TITLE
`pulumi new` menu screen wrapping

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#11812]
### What happened?

When I run `pulumi new` the template description may wrap and mess up the display as such:

[![asciicast](https://asciinema.org/a/IOUr2UMx35DXiy37JzqpfKKdV.svg)](https://asciinema.org/a/IOUr2UMx35DXiy37JzqpfKKdV)

### Steps to reproduce

make your terminal less wide.

### Expected Behavior

Be able to see the `Please choose a template` prompt and the filter text.

### Actual Behavior

Can't see it.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
also `pulumi new` hangs a little for me and a progress spinner would be nice.

**Comment by iwahbe** [comment]
I think we need to work on ditching `survey`, and facilitating a better template search experience.

**Comment by AaronFriel** [comment]
I see this as "in progress" without an assignee and a milestone. @dixler is someone on the platform team picking this up?
