### ISSUE TITLE
Add WithValue to pulumi.Context

### ISSUE THREAD

**Issue by bison** [pulumi/pulumi#11825]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The Go SDK for Pulumi has the concept of a `pulumi.Context` that is passed basically everywhere. It wraps a `context.Context` from the Go standard library. I would like to be able to call `WithValue` on a `pulumi.Context` to set extra configuration fields that are available throughout the Pulumi code the same way I might with a `context.Context`.

### Affected area/feature

- Go SDK `pulumi.Context` — [sdk/go/pulumi/context.go](https://github.com/pulumi/pulumi/blob/v3.51.0/sdk/go/pulumi/context.go)

**Comment by RobbieMcKinstry** [comment]
Hi Bison! Thanks for the API suggestion. Is this something you'd be willing to contribute?

**Comment by bison** [comment]
Hi @RobbieMcKinstry, yeah I can do that. I think this is a pretty small change actually.

**Comment by RobbieMcKinstry** [comment]
Awesome! I'll assign this issue to you. Feel free to @ me on the PR whenever you get around to it 👍🏻 Thanks very much!

**Comment by sssash18** [comment]
Hi @RobbieMcKinstry Can I pick up this issue ?

**Comment by bison** [comment]
@sssash18, please do. I ended up not needing this and completely forgot about it.

**Comment by emilhotkowski** [comment]
Hi I added a PR for this small change.  https://github.com/pulumi/pulumi/pull/15147

**Comment by RobbieMcKinstry** [comment]
Hello! I'm no longer a maintainer on the Pulumi Core team, so I'm not able to shepherd this issue any longer. Best of luck, however, and thank you for your generous community contribution!
