### ISSUE TITLE
[go/codegen] Generated Go code does not compile for pulumi-azure, Akamai

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#11837]
### What happened?

The generated Go SDK does not compile. I've not looked too closely as to why; would appreciate the go codegen to fail faster if something is wrong with the schema.

### Steps to reproduce

See:

- https://github.com/pulumi/pulumi-akamai/issues/131 
- https://github.com/pulumi/pulumi-azure/issues/1190 

### Expected Behavior

Generated Go code compiles; or code generation fails.

### Actual Behavior

Generated Go code fails to compile.

### Output of `pulumi about`

v3.51.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Azure may be important - @kpitzen and @justinvp  pinging you in case you think it's worth bumping this up in priority.

**Comment by justinvp** [comment]
Since it'd block Azure, bumping to P1.

**Comment by t0yv0** [comment]
Apologies, this turns out to be a process and/or Makefile issue on the providers side - thanks @abhinav for root-causing in https://github.com/pulumi/pulumi-akamai/issues/131 . I should slow down a bit I feel I should have caught this with some more due diligence.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-azure/pull/1192 example fix
