### ISSUE TITLE
Bors rejecting all PRs

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#11844]
### What happened?

When attempting to merge a PR, bors gives the following message: 
<img width="914" alt="Screenshot 2023-01-12 at 10 22 38 AM" src="https://user-images.githubusercontent.com/22222529/212147891-c3515d14-b571-4b12-87fe-1d157b90eafc.png">

This happens without any indication of test failure and on PRs that pass all tests locally.

### Steps to reproduce

Try to merge a valid PR via `bors`.

### Expected Behavior

PRs with passing tests merge.

### Actual Behavior

PRs with passing tests fail without explanation. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
It looks like bors is functioning now. Will downgrade to a p1 and track for now.

**Comment by justinvp** [comment]
@dixler, can this be closed? AFAIK, bors has been running normally.
