### ISSUE TITLE
Typing "yes" or "n" at the update prompt selects "[experimental] yes, using Update Plans"

### ISSUE THREAD

**Issue by kwohlfahrt** [pulumi/pulumi#11855]
### What happened?

I run a pulumi update, and after the preview, at the prompt `Do you want to perform this update?`, I type `yes[Enter]`. This selects the option `[experimental] yes, using Update Plans (https://pulumi.com/updateplans)`.

For some reason, using update plans fails on my stack, I haven't debugged why.

### Steps to reproduce

Update any stack with `pulumi up -s $STACK_NAME` (I'm not sure if the `-s $STACK_NAME` is necessary). Type `yes` at the prompt.

### Expected Behavior

I expect the option `Yes` to be selected.

### Actual Behavior

The option `[experimental] yes, using Update Plans (https://pulumi.com/updateplans)` is selected instead.

### Output of `pulumi about`

```
CLI          
Version      3.51.1
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.20.0
docker  3.6.0
nodejs  unknown
tls     4.6.1

Host     
OS       darwin
Version  13.1
Arch     arm64

This project is written in nodejs: executable='/Users/kai/.nix-profile/bin/node' version='v18.12.1'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/kwohlfahrt
User           kwohlfahrt
Organizations  kwohlfahrt, CHARM-Tx

Pulumi locates its logs in /var/folders/y5/bn31tpn577ncz9k_8fy16m1w0000gp/T/ by default
```

### Additional context

This occurred in the latest minor release, `3.51.0` was unaffected IIRC. #11802 looks suspicious to me.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kwohlfahrt** [comment]
In fact, typing `n` (but not `no`) causes the option `[experimental] yes, using Update Plans (https://pulumi.com/updateplans)` to be selected as well!

**Comment by Frassle** [comment]
I don't think the prompt actually has ever respected what's typed? It's an up/down selection prompt, we should probably make it block input to make that clear, or start using input to decided the option.

**Comment by kwohlfahrt** [comment]
Huh, I've previously always used the filter-as-you-type mode. If I type some input, it filters the available options to those that contain my input.

Previously, this would cause `y` to filter down to `yes` and the experimental `yes, using Update Plans`, with `yes` selected. And `n`, would cause `no` to be selected. This made it very convenient to use `y[enter]` to apply, and `n[enter]` to reject the update.

**Comment by Frassle** [comment]
Huh so it is! I've somehow never used that before.

The next release should be moving the "yes, using update plans" to the bottom of the list. That will probably fix this.

**Comment by justinvp** [comment]
> given the changes in priority re update plans might be better just removing this option?

Yes, let's remove the option from the prompt. I can open a separate issue to track that. The only open question I have is whether it remains enabled by default in experimental mode.

**Comment by justinvp** [comment]
The prompt was removed from v3.55.0.
