### ISSUE TITLE
Can't login to Pulumi with Azure Blob Storage state backend in devcontainer on Windows

### ISSUE THREAD

**Issue by jooooel** [pulumi/pulumi#11854]
### What happened?

I'm trying to setup a [VS Code devcontainer](https://code.visualstudio.com/docs/devcontainers/containers) for our pulumi development (with Azure Blob Storage as state backend). It works fine when running the devcontainer on Mac OS, but on windows `pulumi login` fails.

The Mac is a Macbook Pro M1 running mac OS Monterey. 

The Windows machine is running Windows 10. It's a corp laptop, so it has a lot of "security" software in place (malware/antivirus scanners, etc). But running the same `pulumi login` command directly in WSL2 works as expected.

### Steps to reproduce

I've created a minimal repro of this, so:

1. Clone this repo on a Windows machine: https://github.com/jooooel/pulumi-login-bug
2. Open the repository in VS Code (remote dev extension required)
3. Open the VS Code command palette (ctrl+shift+p) and choose "Dev Containers: Reopen in container"
4. In a terminal within VS Code, run `pulumi login "azblob://my-storage-container?storage_account=my-storage-account"` (it doesn't matter if the storage account exists, or if you're signed in or not)

### Expected Behavior

That the login command doesn't fail. (In the case of the minimal repro it would fail since there are things missing. But it shouldn't fail with that message)

### Actual Behavior

On Windows, within the devcontainer, the login command fails with:

```
error: problem logging in: unable to check if bucket azblob://my-storage-container?storage_account=my-storage-account is accessible: blob (code=Unknown): DefaultAzureCredential authentication failed
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 403 connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
--------------------------------------------------------------------------------
connecting to 169.254.169.254:80: connecting to 169.254.169.254:80: dial tcp 169.254.169.254:80: connectex: A socket operation was attempted to an unreachable network.
--------------------------------------------------------------------------------
```

### Output of `pulumi about`

```
CLI          
Version      3.51.1
Go Version   go1.19.4
Go Compiler  gc

Host     
OS       debian
Version  11.6
Arch     x86_64

Pulumi locates its logs in /tmp by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /workspaces/pulumi-login-bug). If you have not created a project yet, use `pulumi new` to do so: no project file found
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Sorry for the delay. Thanks for filing this. I'm glad that you have a workaround. I don't have access to a windows machine to repro. 

However, one of my colleagues has the following feedback:

> Think this might need to be kind/question not kind/bug. This is "how do I use dev containers on windows" masquerading as a bug.
I think issue is internet connection sharing (ICS), a Windows feature, is using the same network range that would ordinarily not be used on a personal computer, but would be the metadata server address in AWS, Azure, etc.
> Search for "internet connection sharing 169.254"
> I'd say I'm about 80% confident it's an internet connection sharing interaction. Best to take this issue upstream to the gocloud.dev library tracker

**Comment by jooooel** [comment]
Ok, thanks! I will look into ICS and see if that might be the issue for me. 

I did however realize there's nothing special about the devcontainers (they're just containers as well), so this is a minimal repro that gives the same error:

```
docker run pulumi/pulumi-python:3.52.0 /bin/bash -c "pulumi login 'azblob://my-storage-container?storage_account=my-storage-account'"
```

**Comment by jooooel** [comment]
Yeah, I can't find a workaround for Windows. My networking skills aren't good enough 😅. Any help to get a workaround or solution on Windows would be much appreciated!

**Comment by joelnotified** [comment]
@Frassle, yeah. Looks like it's working for you! Thanks for trying it 👍  So I assume it's something running on our corporate Windows laptops that cause this. 

I did however find a workaround that works on Windows! Adding a route like is mentioned here works fine: https://serverfault.com/a/1060503/311381

```
# Fetch the default gateway IP of container (bridge to host)
$gateway = (Get-NetRoute | Where { $_.DestinationPrefix -eq '0.0.0.0/0' } | Sort-Object RouteMetric | Select NextHop).NextHop
# Fetch the container internal IP interface index
$ifIndex = (Get-NetAdapter -InterfaceDescription "Hyper-V Virtual Ethernet*" | Sort-Object | Select ifIndex).ifIndex
# Create a new route similar to "169.254.169.254  255.255.255.255      172.30.42.1     172.30.42.82   5256"
New-NetRoute -DestinationPrefix 169.254.169.254/32 -InterfaceIndex $ifIndex -NextHop $gateway
```

**Comment by jooooel** [comment]
@Frassle, yeah. Looks like it's working for you! Thanks for trying it 👍  So I assume it's something running on our corporate Windows laptops that cause this. 

I did however find a workaround that works on Windows! Adding a route like is mentioned here works fine: https://serverfault.com/a/1060503/311381

```
# Fetch the default gateway IP of container (bridge to host)
$gateway = (Get-NetRoute | Where { $_.DestinationPrefix -eq '0.0.0.0/0' } | Sort-Object RouteMetric | Select NextHop).NextHop
# Fetch the container internal IP interface index
$ifIndex = (Get-NetAdapter -InterfaceDescription "Hyper-V Virtual Ethernet*" | Sort-Object | Select ifIndex).ifIndex
# Create a new route similar to "169.254.169.254  255.255.255.255      172.30.42.1     172.30.42.82   5256"
New-NetRoute -DestinationPrefix 169.254.169.254/32 -InterfaceIndex $ifIndex -NextHop $gateway
```

**Comment by kellervater** [comment]
@jooooel where did you execute these mentioned statements (within the devcontainer or on windows)? 
I'm currently stuck in an error loop:

Since I put some of my pulumi code in a go module, I wanted to do a `go get example.com/mymodule` which apparently does not work on Windows using ssh from a Yubikey, because since go version 1.17 they don't ask for a password anymore.

So I decided to try the solution of creating a .devcontainer and there I can get my private modules via ssh-yubikey (when setting GOPRIVATE appropriately). BUT... here I am not able to do the `pulumi login <azstorageblobcontainer> (.

It's so frustrating that this super basic functionality doesn't work appropriately. Spent all day to just land at the beginning.

**Comment by kellervater** [comment]
finally... almost at least ;-) 

😄 
2 little tweaks to the workaround of @jooooel .
First, I needed to add `-IncludeHidden` when finding out `ifIndizes`. 
Which leads to the next tweak: In my case I somehow had 2 Hyper-V* Interfaces. 
So I yolo-looped the `NewNetRoute` command over both of them.
The entire thing can be put into a powershell script which I executed on the host:

👨‍💻 
```powershell
$gateway = (Get-NetRoute | Where { $_.DestinationPrefix -eq '0.0.0.0/0' } | Sort-Object RouteMetric | Select NextHop).NextHop
$ifIndizes = (Get-NetAdapter -InterfaceDescription "Hyper-V Virtual Ethernet*" -IncludeHidden | Sort-Object | Select ifIndex).ifIndex
foreach($ifIndex in $ifIndizes) {
  New-NetRoute -DestinationPrefix 169.254.169.254/32 -InterfaceIndex $ifIndex -NextHop $gateway
}
```

😢 
A little downside though...
The `az login` command doesn't work anymore. I guess we interferred somehow with the oauth flow of this command. 

Instead I have to use `az login --use-device-code` within the container or a serviceprincipal.

**Comment by kraiz** [comment]
I got the same error within container on MacOS. It seems to be connected with dns resolving.
Pulumi cli is a go-based binary. Go provides internal and system resolver ([the docs](https://pkg.go.dev/net#hdr-Name_Resolution)). If I force to internal resolver it works as expected:

`GODEBUG=netdns=go pulumi login 'azblob://<container>?storage_account=<account>'`

**Comment by tgummerer** [comment]
I reported this upstream, and got some explanation of what's happening: https://github.com/Azure/azure-sdk-for-go/issues/23058.   Since this behaviour seems intrinsic to how the azure SDK and docker works, unfortunately I don't really see a way forward to get this fixed other than the workaround above, or using an environment credential instead.   Because of that I'm gonna close this issue out.

**Comment by kraiz** [comment]
Hey, my company's proxy responded to IMDS-Requests as well with 503 which made pulumi/AzureSDK retry multiple times resulted in the same problem after like 1 min.

I prevent calls to this IP via iptables (beware, you need to add the NET_ADMIN cap to the devcontainer):
```bash
iptables-legacy -A OUTPUT -d 169.254.169.254 -j REJECT
```

This way the connection it rejected and immediately fallback to `az login`:
```
pulumi stack ls
error: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): DefaultAzureCredential: failed to acquire a token.
Attempted credentials:
        EnvironmentCredential: missing environment variable AZURE_TENANT_ID
        WorkloadIdentityCredential: no client ID specified. Check pod configuration or set ClientID in the options
        ManagedIdentityCredential: Get "http://169.254.169.254/metadata/identity/oauth2/token": dial tcp 169.254.169.254:80: connect: connection refused
        AzureCLICredential: ERROR: Please run 'az login' to setup account.
```

**Comment by kraiz** [comment]
Or assuming that pulumi is doing every other request via HTTPS this works very well (it basically block every HTTP traffic):

```bash
echo 'alias pulumi="http_proxy=disable-pulumis-imds-requests ~/.pulumi/bin/pulumi"' >> /root/.bashrc
```
