### ISSUE TITLE
Support for custom type naming of dynamic provider resource

### ISSUE THREAD

**Issue by Asamsig** [pulumi/pulumi#11856]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When creating a custom provider resource in Node.js, they get a hard-coded type name, [`pulumi-nodejs:dynamic:Resource`](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/dynamic/index.ts#L211), it would be useful to have the possibility to create a more meaningful name.

This feature has already been implemented in Python in this [PR](https://github.com/pulumi/pulumi/pull/7633).

### Proposed solution
Implement an equivalent strategy as was done for Python.

### Affected area/feature

pulumi-nodejs

**Comment by RobbieMcKinstry** [comment]
Thanks for filing this issue Alexander. I'm going to assign to you based on our conversation on Community Slack. Once again, I appreciate your offer to implement! :D
