### ISSUE TITLE
`pulumi config --show-secrets` should use batch-decrypt

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi#11850]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

There is a batch-decrypt endpoint which is more performant for large values of secrets. `pulumi stack --show-secrets` uses this batch endpoint, but `pulumi config --show-secrets` decrypts values in serial. 

Encountered this while working on an issue with @djgrove.

**Comment by blampe** [comment]
This may be a duplicate of https://github.com/pulumi/pulumi/issues/8677

**Comment by RobbieMcKinstry** [comment]
Ah, yeah, I think you're right, it's a duplicate. However, I like your title better!
I'm going to close as a dup, but I'm making #8677 as https://github.com/pulumi/pulumi/labels/good-first-issue so maybe we'll get some takers.
