### ISSUE TITLE
Create a mockable dynamic resource provider implementation for use in tests

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1186]
We have a few different dynamic provider implementations floating around in our integration tests. It would be *awesome* if we could unify those into a single package that can be used in integration tests to mock out resource provider failures. Our negative test coverage is not good because of the difficulty of writing negative tests today in pulumi/pulumi.

**Comment by mikhailshilkov** [comment]
This issue is not user-facing and has been open for 4 years without any activity. I'll go ahead and close it to reduce clutter.
