### ISSUE TITLE
Add optional / backwards compatible generic types to ResourceProvider in nodejs

### ISSUE THREAD

**Issue by Asamsig** [pulumi/pulumi#11875]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Inspired by comments in this [issue](https://github.com/pulumi/pulumi/issues/9086),

The interface [`pulumi.dynamic.ResourceProvider`](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/dynamic/index.ts#L116) uses `any` for parameters and return types, making it difficult to figure out, what is actually given and returned by the methods.

Since TypeScript is structurally typed, changing the type signatures should have no effect on serialized JavaScript.
Adding generic types for Inputs and Ouputs, but defaulting to `any` should not introduce any breaking changes, while making users able to supply types and enjoying type safety.
When bumping to a new major version the defaults could be changed to `unknown` to force users to supply types.

### Affected area/feature

[sdk/nodejs]

**Comment by dixler** [comment]
Hi. I'm going to remove the needs-triage label since your PR has some feedback on it.

Thanks for the suggestion and the PR!
