### ISSUE TITLE
Pulumi is stuck when running on GitHub Actions

### ISSUE THREAD

**Issue by santunioni** [pulumi/pulumi#11889]
### What happened?

A simple `pulumi preview` command is stuck when running on GitHub actions. It is stuck even with no changes in the resources. Other commands such as `pulumi up` are also stuck.

The bug happens intermittently, so it is difficult to reproduce. 

Always works fine when running on my machine (macOS). I tried to run on macOS in github actions but got the same problem.

Perhaps related to https://github.com/pulumi/pulumi/issues/6609

### Steps to reproduce

Create a stack using
- `pulumi 3.51.1`
- s3 as stack backend
- `github plugin github v5.1.0`
- Around ~2k resources. We had ~4k resources before. I was hoping the number of resources would influence the bug, so I deleted a couple that could be deleted.
- Run a simple `pulumi preview` on GitHub actions, running on a `ubuntu-20.04`. You can apply the resources in your machine before running in a way you expect the preview to execute very fast.

Intermittently, the preview would be stuck forever.

### Expected Behavior

The `pulumi preview` should not be stuck. It should run very fast.

### Actual Behavior

The `pulumi preview` is taking forever to run. It lasted 5 hours in a workflow which we didn't configure timeout.

### Output of `pulumi about`

```
CLI          
Version      3.51.1
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
github  5.1.0
nodejs  unknown

Host     
OS       darwin
Version  12.6
Arch     arm64

This project is written in nodejs: executable='/Users/vinicius.vargas/.nvm/versions/node/v16.17.1/bin/node' version='v16.17.1'

Current Stack: loft-br.backstage-resources.gitsyncer

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:loft-br.backstage-resources.gitsyncer::gitsyncer::pulumi:pulumi:Stack::gitsyncer-loft-br.backstage-resources.gitsyncer
pulumi:providers:github                     urn:pulumi:loft-br.backstage-resources.gitsyncer::gitsyncer::pulumi:providers:github::loft-br
github:index/team:Team                      urn:pulumi:loft-br.backstage-resources.gitsyncer::gitsyncer::github:index/team:Team::replaced-name
github:index/membership:Membership          urn:pulumi:loft-br.backstage-resources.gitsyncer::gitsyncer::github:index/membership:Membership::replaced@replaced.com
github:index/teamRepository:TeamRepository  urn:pulumi:loft-br.backstage-resources.gitsyncer::gitsyncer::github:index/teamRepository:TeamRepository::replaced-name
github:index/teamMembership:TeamMembership  urn:pulumi:loft-br.backstage-resources.gitsyncer::gitsyncer::github:index/teamMembership:TeamMembership::replaced-name

-- ATENTION: the number of resources above is way larger (around ~2k). I removed then because of the size limit on github issue body. --

Found no pending operations associated with loft-br.backstage-resources.gitsyncer

Backend        
Name           LOFT-M3786
URL            s3://loft-iac-replaced/.cloudify
User           vinicius.vargas
Organizations  

Pulumi locates its logs in /var/folders/m5/xwz1r9155jg2lcjlwqrh6p540000gq/T/ by default
```

### Additional context

As you can guess from `pulumi about`, we use this stack to automate managing our github membership and team access to repositories. The resources are interpreted from `.yaml` files located at the same repo.

Everything was working fine since 2023/08 until last wednesday (2023/01/11).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hi. Thanks for filing this. I'll take a look.

I notice that you're using a large stack so I'd recommend checking out [this blogpost about PULUMI_SKIP_CHECKPOINTS](https://www.pulumi.com/blog/pulumi-release-notes-80/#skip-checkpoints-experimental-flag) which can improve the speed that large stacks update.

**Comment by santunioni** [comment]
I think I got it solved now. I discovered that nodejs version is the thing that changed since pulumi worked fine for me in github actions.

We were using
```
- uses: actions/setup-node@v3
  with:
    node-version: 16.x
```

Five days ago, when the stack was running fine, the version was being resolved to `16.18.1`. Now it is resolved to `16.19.0`.

I pinned to `16.17.1` because it is the version I use in my notebook. I ran it several times with 100% success. Before pinning I was getting ~10% success. The stack seems to be running fine.

**Comment by santunioni** [comment]
@Frassle, actually I got the same problem in pulumi version `3.38.0`. I bumped to `3.51.1` as an attempt to solve it.

**Comment by santunioni** [comment]
I got strong evidence that node version is the problem. If you confirm it, what do you think of implementing some kind of fail-fast approach when running pulumi with node versions not tested with pulumi?

**Comment by RobbieMcKinstry** [comment]
@santunioni are you exclusively using the GitHub Action? For example, if you unpin Node and run locally, does it work?

**Comment by Frassle** [comment]
> We should call out which versions are supported more clearly on a docs page.

From https://www.pulumi.com/docs/intro/languages/javascript/:

Pulumi supports writing your infrastructure as code in any JavaScript language running on Node.js using any of the [Current, Active and Maintenance LTS versions](https://nodejs.org/en/about/releases/).

**Comment by santunioni** [comment]
@RobbieMcKinstry I just switched my local nodejs version to 16.19.0 and my terminal got stuck on a `pulumi preview`

**Comment by santunioni** [comment]
Perhaps not necessary pulumi, but [github provider](https://www.pulumi.com/registry/packages/github/) is incompatible with nodejs `16.19.0`?

**Comment by santunioni** [comment]
In any case, we can close this issue since the problem is not exactly related to pulumi+github actions.

**Comment by RobbieMcKinstry** [comment]
> > We should call out which versions are supported more clearly on a docs page.
> 
> From https://www.pulumi.com/docs/intro/languages/javascript/:
> 
> Pulumi supports writing your infrastructure as code in any JavaScript language running on Node.js using any of the [Current, Active and Maintenance LTS versions](https://nodejs.org/en/about/releases/).

Yeah, I mean one page for all languages: a quick reference.

**Comment by RobbieMcKinstry** [comment]
> In any case, we can close this issue since the problem is not exactly related to pulumi+github actions and reference it somewhere else talking about versions compatibility

Thanks santunioni. I've went ahead and closed the issue. If you pin down the issue to the GH provider, then [pulumi-github](https://github.com/pulumi/pulumi-github) is the proper issue home. But if the issue is broadly that Pulumi doesn't support Node 16.19 effectively, then we should probably reopen this issue and change the title. 👍🏻

**Comment by santunioni** [comment]
@RobbieMcKinstry I didn't have the same problem when running another stack with nodejs `16.19.0`. Is it sufficient to pin the problem as originated from pulumi-github?

**Comment by RobbieMcKinstry** [comment]
I suppose it's not _technically_ sufficient, since it's possible the bug is at the intersection of `16.19.0` and a set of instructions sent to the Pulumi engine. However, that sounds like a good bet to me.
