### ISSUE TITLE
getEngineVersions: Add support for to pass pulumi.Output<string>

### ISSUE THREAD

**Issue by Arielgordon123** [pulumi/pulumi#11899]
### What happened?

when creating a new GCP project, and then trying to use this project in the `getEngineVersions` function there is an error

`Type 'Output<string>' is not assignable to type 'string | undefined'`

### Steps to reproduce

create a new gcp Project
```js
const myProject = new gcp.organizations.Project("project-1", {

    projectId: "project1"
});
```
then try to use the project as input to `getEngineVersions` function
```js
const engineVersion = gcp.container.getEngineVersions({ project: myProject.number }).then(v => {
    return v.latestMasterVersion;
});
```

### Expected Behavior

I was expected the ability to pass the project as input

### Actual Behavior

```
error TS2322: Type 'Output<string>' is not assignable to type 'string | undefined'.
      Type 'Output<string>' is not assignable to type 'string'.
```

**Comment by Frassle** [comment]
Use `getEngineVersionsOutput` instead. 

https://www.pulumi.com/registry/packages/gcp/api-docs/container/getengineversions/#using
