### ISSUE TITLE
400 Bad request error in azure pipeline with 3.53

### ISSUE THREAD

**Issue by Phil1972** [pulumi/pulumi#11982]
Hi,

Since this morning, we are having issues with v3.53 in our azure pipeline.  I reproduced it as well locally on my machine.

```
error: constructing secrets manager of type "cloud": secrets (code=InvalidArgument): POST https://*******.vault.azure.net/keys/pulumi-secret/decrypt
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadParameter
--------------------------------------------------------------------------------
{
  "error": {
    "code": "BadParameter",
    "message": "The parameter is incorrect.\r\n"
  }
}
--------------------------------------------------------------------------------
```
 Any ideas of what could be wrong?  3.51 works fine.

thanks,

**Comment by Frassle** [comment]
> 3.51 works fine.

Can you try 3.52.1?

This looks like it might be due to https://github.com/pulumi/pulumi/pull/11963.

cc @AaronFriel, we might need to revert that change and do a patch release if 3.52.1 is confirmed good.

**Comment by Phil1972** [comment]
Yes, 3.52.1 works fine

thanks,

**Comment by AaronFriel** [comment]
@Frassle can you take the revert & make the upstream issue with gocloud.dev?

**Comment by thomas11** [comment]
@AaronFriel a user on the community Slack reports the same error after upgrading from 3.52.1 to 3.53.

**Comment by Phil1972** [comment]
Thanks everyone for the quick fix
