### ISSUE TITLE
Write integration tests for Azure secrets

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi#11986]
Context: https://github.com/pulumi/pulumi/issues/11982

We have some integration tests to ensure the aws kms secret store works, we should add some for Azure (and probably GCP and vault as well if that can be setup)

**Comment by Frassle** [comment]
Hey @Phil1972 I'm trying to write up these test to repro what you saw in https://github.com/pulumi/pulumi/issues/11982 but currently not able to trigger that BadParameter error.

Could you let us know what the secret provider url looked like (including any query parameters) and what the key settings were (Key type, size, etc).
My current guess is either some subtle change in the handling of the provider url, or a change in authentication although not clear why that doesn't get triggered until decryption time.

**Comment by Phil1972** [comment]
Hi @Frassle , I am not too sure what you need in terms of parameters.  What I can tell you is that the problem is now gone and I can reproduce it if I revert to the 3.53.0 CLI version.  The secret provider is an azure keyvault/storage account setup as per your instructions

**Comment by Frassle** [comment]
>  I am not too sure what you need in terms of parameters

Parameters is anything in the "azurekeyvault://XXX.vault.azure.net/keys/YYY" beyond the vault name (XXX) and the key name (YYY). E.g. You could be setting something like "?algorithm=RSA-OAEP-256".

> The secret provider is an azure keyvault/storage account setup as per your instructions

Not sure which instructions your referring to there? I didn't think we (Pulumi) had any docs on how to create these keys. The only docs I know are https://www.pulumi.com/docs/intro/concepts/secrets/#azure-key-vault which just describes what the url looks like to use the key.

Key settings should be shown in the azure portal and is things like the Key Type and Key Size.

Also if your setting any AZURE_ env vars such as AZURE_KEYVAULT_AUTH_VIA_CLI or AZURE_AD_RESOURCE.

**Comment by Phil1972** [comment]
ok I understand, here is our login script:

az login
az account set --subscription $subscriptionId
$env:AZURE_STORAGE_ACCOUNT = $storageAccount
$env:AZURE_STORAGE_KEY = (az storage account keys list -g $rg -n $storageAccount --query [0].value -o json) -replace '"', ''
$env:AZURE_KEYVAULT_AUTH_VIA_CLI=$true

; following two probably irrelevant for your test case    
$env:AZDO_ORG_SERVICE_URL='ourDevOpsUrl'
$env:AZDO_PERSONAL_ACCESS_TOKEN=(az account get-access-token --query accessToken) -replace '"', ''

;then login
pulumi login azblob://state

**Comment by Frassle** [comment]
More issues due to a go cloud update: 
https://github.com/pulumi/pulumi/issues/13181
https://github.com/pulumi/pulumi/issues/13183
