### ISSUE TITLE
String Preview Bug

### ISSUE THREAD

**Issue by bbstilson** [pulumi/pulumi#11990]
### What happened?

Bit of an odd one. It appears the rendering of certain strings in the `preview` is outputting errors from the Go layer (just a guess).

### Expected Behavior

Strings should be rendered identically to their data in the preview step.

### Steps to reproduce

I'm using Node/AWS. I am generating a password to use for an AWS secretsmanager secret.

```js
// password.ts

export const password = output(generatePassword());

const PASSWORD_LENGTH: number = 128;
const PASSWORD_CHARS =
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*_-=+";
function generatePassword(): string {
  return Array.from(Array(PASSWORD_LENGTH))
    .map((_) =>
      PASSWORD_CHARS.charAt(Math.floor(Math.random() * PASSWORD_CHARS.length))
    )
    .join("");
}

const secret = new secretsmanager.Secret(name, { name });

const sv = new secretsmanager.SecretVersion(name, {
  secretId: secret.id,
  secretString: password,
});

sv.secretString.apply(console.log);
```

This works as expected! The outputted password is as follows:

```
j$k4Ue$c0@iAxfI_ZPKU1f-PcKki8_$Stw_u2!Aas9O5S1N+1jtD9tlkFIo@+fDiRuA%q^@4WKUw3MdmO@z+hvWUysbISSQRERQ%3y@PkKfDFYHZpA8Mv*-nLHc#WqSF
```

The "bug" is when I go to use it. I have an AWS lambda:

```js
// omitting many required fields to avoid overwhelming the reader
new lambda.Function("name", {
  environment: {
    variables: {
      FOOBAR: password,
    },
  },
});
```
When I `preview` this, I get the following:

```
      ~ environment: {
          ~ variables: {
              ~ FOOBAR: "asdf" => "Lo*eDlru9MtDhQp!a=o_6=ClOLvEw5@nRnWGeqJK048RhY%!(BADWIDTH)%!&(MISSING)Z0%!z(MISSING)bnQ!Jmjr@x2Qap%!H(MISSING)vRr5xOm8%DUsYHbnJFqD4GTusXkZrFmW8hzt-Kym@i-wRWK5Z_iuAxKp5"
            }
        }

```

You'll notice the several `MISSING` and `BADWIDTH` segments.

I've confirmed this does not affect the actual lambda's environment variables, so it seems like it's just related to the preview rendering layer.

Happy to provide any further details. Thanks!

### Output of `pulumi about`

CLI          
Version      3.51.1
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.27.0
awsx    1.0.1
docker  3.6.1
nodejs  unknown

Host     
OS       debian
Version  bookworm/sid
Arch     x86_64

This project is written in nodejs: executable='/home/bbstilson/.nvm/versions/node/v19.4.0/bin/node' version='v19.4.0'

Current Stack: bbstilson/goal_tracker/prod

TYPE                                            URN
pulumi:pulumi:Stack                             urn:pulumi:prod::goal_tracker::pulumi:pulumi:Stack::goal_tracker-prod
pulumi:providers:aws                            urn:pulumi:prod::goal_tracker::pulumi:providers:aws::default_5_27_0
aws:cloudwatch/logGroup:LogGroup                urn:pulumi:prod::goal_tracker::aws:cloudwatch/logGroup:LogGroup::goal_tracker
aws:apigatewayv2/api:Api                        urn:pulumi:prod::goal_tracker::aws:apigatewayv2/api:Api::goal_tracker
aws:apigatewayv2/stage:Stage                    urn:pulumi:prod::goal_tracker::aws:apigatewayv2/stage:Stage::goal_tracker
aws:iam/policy:Policy                           urn:pulumi:prod::goal_tracker::aws:iam/policy:Policy::goal_tracker
aws:iam/role:Role                               urn:pulumi:prod::goal_tracker::aws:iam/role:Role::goal_tracker
aws:secretsmanager/secret:Secret                urn:pulumi:prod::goal_tracker::aws:secretsmanager/secret:Secret::goal_tracker
aws:secretsmanager/secretVersion:SecretVersion  urn:pulumi:prod::goal_tracker::aws:secretsmanager/secretVersion:SecretVersion::goal_tracker
aws:lambda/function:Function                    urn:pulumi:prod::goal_tracker::aws:lambda/function:Function::goal_tracker
aws:apigatewayv2/integration:Integration        urn:pulumi:prod::goal_tracker::aws:apigatewayv2/integration:Integration::goal_tracker
aws:lambda/permission:Permission                urn:pulumi:prod::goal_tracker::aws:lambda/permission:Permission::goal_tracker
aws:apigatewayv2/route:Route                    urn:pulumi:prod::goal_tracker::aws:apigatewayv2/route:Route::goal_tracker-default

Found no pending operations associated with prod

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/bbstilson
User           bbstilson
Organizations  bbstilson

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.51.1
@types/node     14.18.36
@pulumi/aws     5.27.0

Pulumi locates its logs in /tmp by default
warning: A new version of Pulumi is available. To upgrade from version '3.51.1' to '3.52.1', run 
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Yup looks like this isn't escaping user/program input text and trying to treat it as our internal markup directly.
