### ISSUE TITLE
Implement checking progress reporting

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#120]
Now that we sometimes access services over the Internet as part of resource validation (e.g., see pulumi/coconut#115, checking that AMIs exist), the validation step can consume perceptible time.

As a result, we should consider some form of progress reporting.  Even just a single CLI line that says something like `Validating: <resource-x>`, and rewrites itself as it walks through each resource (`<resource-y>`, `<resource-z>`, etc), would at least tell the user what might be taking a long time.  This will also be important if we do analyzers (see pulumi/coconut#119).

In addition to this, we may want to have an "offline" mode.  If you're on an airplane and want to validate that a resource graph is valid, it kind of stinks that you can't do that anymore.

**Comment by pgavlin** [comment]
@joeduffy is this still relevant?

**Comment by joeduffy** [comment]
We have basically done this as part of the Kubernetes providers. Not sure if there's anything else we want to do to make this more first class and/or apply it to other providers. Assigning @swgillespie to decide.
