### ISSUE TITLE
[python] - MLC results in incorrect usage of google-native python package

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#12009]
### What happened?

When building a MLC using https://www.pulumi.com/registry/packages/google-native/api-docs/container/v1/nodepool/#nodepoolautoscaling as an input to a user-defined type, the resulting python sdk incorrectly references the generated type, resulting in a runtime error.

### Expected Behavior

The generated python sdk should reference the above referenced type by:
```
 @property
    @pulumi.getter(name="locationPolicy")
    def location_policy(self) -> Optional['pulumi_google_native.container.v1.NodePoolAutoscalingLocationPolicy']:
        """
        Location policy used when scaling up a nodepool.
        """
        return pulumi.get(self, "location_policy")
```

### Steps to reproduce

Instead, the namespace appears to be truncated, resulting in incorrect usage of the imported package. **see _container below**
```
    @property
    @pulumi.getter(name="locationPolicy")
    def location_policy(self) -> Optional['_container.v1.NodePoolAutoscalingLocationPolicy']:
        """
        Location policy used when scaling up a nodepool.
        """
        return pulumi.get(self, "location_policy")
```

Repro can be referenced:
- generated python sdk :: https://github.com/phillipedwards/pulumi-aws-s3-replicated-bucket/blob/pedwards/gcp-issue/sdk/python/pulumi_aws_s3_replicated_bucket/gcp/gke/outputs.py
- schema.json :: https://github.com/phillipedwards/pulumi-aws-s3-replicated-bucket/blob/3224fb11b53d6b58825d3da1c31b22164f37b945/schema.json#L37-L46

### Output of `pulumi about`

```bash
▶ pulumi about         
CLI          
Version      3.53.0
Go Version   go1.19.5
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/phillipedwards
User           phillipedwards
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Interesting! Thanks for being so thorough Phillip. Your right, this looks like it's originating somewhere between codegen and MLC processing.
