### ISSUE TITLE
Investigate Failing Fuzz Tests Master

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi#12017]
### What happened?

Master has a failing status check. I'm not sure why this is, or if it's a real issue or imagined.

Fuzz tests were executed on master and failed. https://github.com/pulumi/pulumi/actions/runs/4037264022/attempts/1

### Expected Behavior

Master is expected to always be green by construction.

This may be red in an unimportant way.

### Steps to reproduce

Inspect https://github.com/pulumi/pulumi/actions/runs/4037264022/attempts/1 and observe the status check.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Investing red master. 

- The original PR is green. 

- The [commit](https://github.com/pulumi/pulumi/pull/9262/commits) has a green check. (SHA c902b9499f4401b0faf89373394999ff3581b007)

- The [PR's status checks](https://github.com/pulumi/pulumi/pull/9262/checks) are also green.

- My understanding of the process is that Bors merges that PR onto staging and runs the status checks, merging only if the required checks are all green. However, the overall list of checks is red (image below).

<img width="1322" alt="red-workflow" src="https://user-images.githubusercontent.com/4955075/215523862-93f34f89-7e51-4b9b-a117-412786c68c18.png">

- The commit to master that's red was introduced by Bors. (SHA 0c5759f2ce28abd9e9376a6d9397f63d1684d385)

- Judging by the below image, it appears this particular job doesn't fail the workflow. Going to look more closely.

<img width="1353" alt="workflow-graph" src="https://user-images.githubusercontent.com/4955075/215524414-29a94523-a648-459d-b05d-ef519c687490.png">

**Comment by RobbieMcKinstry** [comment]
Aha! We `continue-on-error` if Windows smoke tests fail!

https://github.com/pulumi/pulumi/blob/master/.github/workflows/ci.yml#L314

**Comment by abhinav** [comment]
@RobbieMcKinstry oops we didn't create a ticket for this. I have a fix at #12007.

**Comment by RobbieMcKinstry** [comment]
I have two strong feelings about the testing methodology here.

# Smoke Tests

Smoke tests serve as a low water mark for build acceptance. The name comes from the phrase "where they're smoke, there's fire" -- if a smoke test fails, then everything is likely borked, so the whole build should immediately fail. You should run your lints and smoke tests first so you can fail fast and error the build before executing the unit test suite, which takes more time to execute.

# Fuzz Testing

Despite its reputation in industry, fuzzing (or fuzz testing) has a wide variety of approaches, including formal methods approaches. I'm less familiar with Go's approach, but the general idea is that these tests stochastically try a wide variety of inputs to attempt create a failure. Often, fuzz tests catch errors which aren't seen in practice -- very oddly constructed inputs running against specific functions.

As such, fuzz tests should be separate from smoke tests because they are a very high water mark for build correctness.

# Resolutions

* Let's pull fuzz testing out of the smoke tests
* Let's always fail the build if smoke tests fail.

## Sources

I lean heavily on what I learned taking Bill Laboon's class on quality assurance methodology at university. https://www.amazon.com/Friendly-Introduction-Software-Testing/dp/1523477377

**Comment by RobbieMcKinstry** [comment]
> fuzz-tests-as-unit-tests with fixed inputs, not randomized or fuzzed inputs, is what runs in CI

That still shouldn't run as part of the Smoke suite, since those are hand-crafted inputs for unit tests that were generated by the fuzzer, and are thus a high-water mark for build correctness.

**Comment by abhinav** [comment]
Right. That's with the fixed input—the hand written input. That's basically a vanilla unit test.

**Comment by RobbieMcKinstry** [comment]
Let's see if we can fix that. 👍🏻

**Comment by RobbieMcKinstry** [comment]
Closed by https://github.com/pulumi/pulumi/pull/12007

**Comment by abhinav** [comment]
https://github.com/pulumi/pulumi/pull/12007 has landed; the issue has been resolved

<img width="312" alt="image" src="https://user-images.githubusercontent.com/41730/215560190-9390c52d-7761-4505-8543-d639fb33be9f.png">

**Comment by RobbieMcKinstry** [comment]
🎉🎉🎉🎉
