### ISSUE TITLE
Config secret leaks in environment variable if source is multiline (e.g. a private key file)

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#12016]
### What happened?

Have a two different secrets in a Pulumi.stack.yaml config file. 
One is a simple single value and the other is a private SSH key.
If I run this code:
```
import * as pulumi from "@pulumi/pulumi";
console.log(process.env.PULUMI_CONFIG)
```

I get this output:
```
Diagnostics:
  pulumi:pulumi:Stack (leaky-env-vars-dev):
    {"leaky-env-vars:config:simpleSecret":"[secret]","leaky-env-vars:config:sshKeySecret":"-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXk.....
```

So, the simple secret is treated correctly and not exposed, but the SSH private key is exposed. 
I also confirmed that any multiline secret is treated the same way and exposed.

### Expected Behavior

The secret should not be exposed.

### Steps to reproduce

1. `ssh-keygen -f sshKey`
2. `cat sshKey | pulumi config set sshKeySecret --secret`
3. `pulumi config set simpleSecret mySecretValue --secret`
4. `pulumi preview` with the code provided above.
5. See the sshKey is exposed.

### Output of `pulumi about`

CLI          
Version      3.53.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  12.5.1
Arch     x86_64

Current Stack: xxxxx/leaky-env-vars/dev

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:dev::leaky-env-vars::pulumi:pulumi:Stack::leaky-env-vars-dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/xxxxx

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.53.1
@types/node     16.18.11

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Thanks Mitch! At first blush, this does indeed appear to be an issue. I'll take a look and see why the secret isn't being obscured. In chatting this over with @abhinav, we seem to think the logic that is responsible for obscuring secrets is skipping multiline secrets for whatever reason. That's just a hunch.
