### ISSUE TITLE
Store creation and update timestamps for a resource in the state file

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#12022]
In the state file, we currently have a timestamp that is global for the entire state

```json
"manifest": {
      "time": "2023-01-23T12:38:38.315329-08:00",
..... snip ....
```

It would be super interesting if we could store the last time an individual _resource_ was accessed, whether that be via refresh, update, or something else.

So something like:

```json
{
        "urn": "urn:pulumi:dev::eks-cluster::pulumi:providers:eks::default",
        "custom": true,
        "id": "682ef937-8eca-411d-b9cd-ba0267cb6b04",
        "type": "pulumi:providers:eks",
        "inputs": {
          "version": "0.42.5"
        },
        "timestamp": <insert timestamp here>",
        "outputs": {
          "version": "0.42.5"
        }
      },
     
```

**Comment by RobbieMcKinstry** [comment]
Ooo that's smart Lee! It would be very interesting to see how much infra is completely static. Makes for a nice dashboard card. 🤷🏻‍♂️ 

@caseyyh how much lift would this require in the service? It should be free for the other backends.

**Comment by RobbieMcKinstry** [comment]
Added this to the agenda to discuss during team ideation. Not sure what the lift required would be, but I want to ask my team for their thoughts.

**Comment by caseyyh** [comment]
The service doesn't really peer too closely at the checkpoint file whenever the CLI updates the state file. I imagine we'd want to update the checkpoint model (alongside a major version bump, perhaps?) and on the service end, we'd just need to be able to handle that new model. -- though, this would be an interesting thing to ingest as a part of resource search in our hypothetical future.

I see @blampe is so on top of the GH issue game that he's already seen this --- but Bryce and @djgrove are the ones currently working on Resource Search; tagging them both for their added input if they have any.
