### ISSUE TITLE
Automatically decline in non-interactive environments

### ISSUE THREAD

**Issue by bverhallen** [pulumi/pulumi#12036]
## Hi,

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In a non-interactive environment such as Jenkins, it would be nice to be able to automatically decline a command.
For example a pulumi refresh command now requires user input for declining or accepting. If you don't want to continue, you have to forcefully stop the Jenkins job forcefully and that leaves the pulumi state in a locked status.
There already is a --yes flag to automatically accept for this scenario.
It would be nice if there would be a --no flag that enables you to create a "preview" Jenkins job so you can see what will happen first. Then there could be a second job with the --yes flag to run if everything looks good.

### Affected area/feature

Pulumi cmdline

**Comment by Frassle** [comment]
Maybe we should just change the `--non-interactive` behavior.
Currently that immediately errors out with:
```
$ pulumi refresh --non-interactive
error: --yes or --skip-preview must be passed in to proceed when running in non-interactive mode
```
But what if we allowed these commands to run their preview steps like usual and then just instead of prompting for `Do you want to perform this refresh?` we then exit out with a message like the above?

**Comment by Frassle** [comment]
I think this is exactly the same as https://github.com/pulumi/pulumi/issues/10966, although does give some more ideas for the flag name, and that we should update that non-interactive error message. I'll close this and comment on that ticket.
