### ISSUE TITLE
[cli+ui] Improve how `retainOnDelete` is shown to the user

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#12030]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

(internal [thread](https://pulumi.slack.com/archives/C02970CDD27/p1675189042653359))

When using the resource option [`retainOnDelete`](https://www.pulumi.com/docs/intro/concepts/resources/options/retainondelete/) and if the resource is being removed from the stack state, the resource is shown as being deleted in the preview as well as during the update and the destroy phases. This can easily be anxiety inducing for some users.

To improve the user experience, such `retainOnDelete` resources should be shown differently to the user:

1. The CLI should make it clear that the resource will remain provisioned during preview, update and destroy phases.
2. The Pulumi service should also capture and display such information.

The example below, shows a preview and a destroy for an S3 bucket with `retainOnDelete=true`.

![image](https://user-images.githubusercontent.com/1161681/215873233-2daa4818-d842-4c10-b11b-c76aab4ca79d.png)
 

### Affected area/feature

* cli
* pulumi-service

**Comment by RobbieMcKinstry** [comment]
> This can easily be anxiety inducing for some users.

That statement resonated with me. We should tighten up our language here to make it more clear what is happening.

**Comment by abhinav** [comment]
Proposal for an improvement on this:

For resources marked as retainOnDelete, we add an asterisk or an emoji (maybe 🗃️ as in "archived/it's still around") next to "delete" in the preview above, and at the bottom of the list include a text:

```
    * Will be deleted from Pulumi state but not the cloud provider.
    // or if we use the emoji
    🗃️ Will be deleted from Pulumi state but not the cloud provider.
```

During execution, the asterisk/emoji will be shown next to "deleting" and "deleted" but not the explanation text because the icon is already associated to the message now.

**Comment by dixler** [comment]
Working within the current constraints of the display, maybe we can replace delete with drop when retainOnDelete is used?
```
     Type                              Name                     Plan                                                         
 -   pulumi:pulumi:Stack               aws-ec2-instance-2-dev   delete                                                       
 -   ├─ aws:ec2:RouteTableAssociation  route-table-association  delete                                                       
 -   ├─ aws:ec2:RouteTable             routes                   delete                                                       
 -   ├─ aws:ec2:Instance               instance                 drop                                                       
 -   ├─ aws:ec2:Subnet                 subnet                   delete                                                       
 -   ├─ aws:ec2:InternetGateway        gateway                  delete                                                       
 -   ├─ aws:ec2:SecurityGroup          security-group           delete                                                       
 -   └─ aws:ec2:Vpc                    vpc                      delete  
```

We should also make sure the details reflect whatever change we decide.

**Comment by abhinav** [comment]
I like drop as an alternative to delete.
We'll probably still want to clarify what drop means at the bottom at least for a while.

**Comment by aureq** [comment]
I'd like to propose a few alternatives to `drop`:

* `unlink`
* `detach`
* `untrack`
* `release`
* `unmanage`

**Comment by dixler** [comment]
It looks like we already have a concept of `discard` in the codebase here
https://github.com/pulumi/pulumi/pull/2280

**Comment by dixler** [comment]
I notice that `retainOnDelete` also pertains to `replace` and that experience may be unexpected because retainOnDelete also applies to replaces and there may be unexpected cloud resources floating around their environment running up costs.

For more consistency and clarity, would it make sense to do:
`delete[drop] (0.24s)`
`deleted[drop] (0.24s)`
`replace[drop] (0.24s)`
`replaced[drop] (0.24s)`

I could solve is purely in the CLI display so it wouldn't affect the service.
@susanev @abhinav @Frassle

**Comment by aureq** [comment]
@dixler I think it would be worth adding a message at the end of an update when resources have been dropped to inform the user that some resources are still provisioned in their cloud env. I think the `replace` will trick quite few people not realizing that the previous resource was left behind and a new one was also created.

**Comment by Frassle** [comment]
> I could solve is purely in the CLI display so it wouldn't affect the service.

If we can just do this CLI side for now that seems worthwhile.

> I think it would be worth adding a message at the end of an update when resources have been dropped to inform the user that some resources are still provisioned in their cloud env.

Oh that would be soo nice. Just a list of these things were dropped from state but not actually deleted.

**Comment by dixler** [comment]
How does this look?

[![asciicast](https://asciinema.org/a/28iAIk7CzCpRGXenzpMLAlsuV.svg)](https://asciinema.org/a/28iAIk7CzCpRGXenzpMLAlsuV)
