### ISSUE TITLE
Go 1.20 Upgrade

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi#12040]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This is just a tracking issue for upgrading pu/pu to Go 1.20.
We should link any related tickets here.

The upgrade will help:

- #9224 cc @AaronFriel 

The upgrade is blocked on:

- [x] golangci-lint support with 1.20

Upgrade PR: https://github.com/pulumi/pulumi/pull/12039

**Comment by AaronFriel** [comment]
@abhinav it looks like #12039 to "test with 1.20" marked this issue as fixed. Are we also building on 1.20?

**Comment by abhinav** [comment]
From the cursory digging I did, it appeared that we used the same version set for the builds.
So #12039 should also cover that.

If that's not accurate, we should re-open this.

**Comment by abhinav** [comment]
All existing references to 1.19 were tool-specific (helpful comments, BTW!)

```
% rg -F 1.19 .github
.github/workflows/ci.yml
70:          go-version: '>=1.19.0' # decoupled from version sets, only used by gotestsum

.github/workflows/on-pr-changelog.yml
49:          go-version: '>=1.19.0' # decoupled from version sets, only used by changelog tool

.github/workflows/ci-test-codegen.yml
32:          go-version: '>=1.19.0' # decoupled from version sets, track latest for codegen

.github/workflows/ci-info.yml
66:          go-version: '>=1.19.0' # decoupled from version sets, used by changelog tool

.github/workflows/release-pr.yml
43:          go-version: '>=1.19.0' # decoupled from version sets, only used by changelog tool
```
