### ISSUE TITLE
Broken: Pulumi gen-completion zsh

### ISSUE THREAD

**Issue by ckdarby** [pulumi/pulumi#12059]
### What happened?

When following the docs for gen-completion with zsh the autocomplete doesn't work properly.

### Expected Behavior

Autocompletion working

### Steps to reproduce

```bash
echo $fpath | grep 'completions'
# /home/ckdarby/.oh-my-zsh/completions

pulumi gen-completion zsh >  /home/ckdarby/.oh-my-zsh/completions/pulumi
chmod +x /home/ckdarby/.oh-my-zsh/completions/pulumi

autoload -Uz compinit && compinit -i
exec $SHELL -l
```
```bash

pulumi [tab]

#no auto completion just file system returns
```

### Output of `pulumi about`

CLI          
Version      3.53.1
Go Version   go1.19.5
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by abhinav** [comment]
Hi @ckdarby, thanks for the issue!

Trying it out in a terminal as-is, looks like the completion script generated by the pulumi command works fine:

```
% eval $(pulumi gen-completion zsh)
% pulumi [tab]
# generates auto-completion options
```

I suspect oh-my-zsh is not sourcing the file.
One guess from looking at other oh-my-zsh completion scripts is that it should be named `_pulumi`, not `pulumi`:

```bash
pulumi gen-completion zsh >  ~/.oh-my-zsh/completions/_pulumi
```

Please try that out and let us know if it worked.

**Comment by djsd123** [comment]
Was having the same issue.  The solution from @abhinav worked for me. Much appreciated 🙏

**Comment by dixler** [comment]
I have an issue open to use cobra's built-in gen-completion rather than our custom one.
- https://github.com/pulumi/pulumi/issues/10225
