### ISSUE TITLE
`pulumi state delete <urn>` not able to delete a resource existing in the current state

### ISSUE THREAD

**Issue by ronnylt** [pulumi/pulumi#12119]
### What happened?

```
pulumi state delete 'pulumi:xxx::xxx::network$gcp:organizations/folder:Folder::networking'
 warning: This command will edit your stack's state directly. Confirm? Yes
error: No such resource "pulumi:xxx::xxx::network$gcp:organizations/folder:Folder::networking" exists in the current state
```

The resource exist in the current state, but `state delete` can't find it.

```
pulumi stack -u | grep 'urn:pulumi:xxx::xxx::network$gcp:organizations/project:Project::network'
    │     │  URN: urn:pulumi:xxx::xxx::network$gcp:organizations/project:Project::network
```

### Expected Behavior

The  resource get deleted from the state.

### Steps to reproduce

```
pulumi stack -u 
pulumi sate delete <urn>
```

### Output of `pulumi about`

```
CLI
Version      3.54.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME    VERSION
docker  3.6.1
gcp     6.49.0
nodejs  unknown
random  4.10.0

Host
OS       darwin
Version  13.0
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v16.19.0'
```

### Additional context

```
Dependencies:
NAME            VERSION
@pulumi/docker  3.6.1
@pulumi/gcp     6.49.0
@pulumi/pulumi  3.53.1
@pulumi/random  4.10.0
@types/node     16.18.12

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hey. Sorry you're running into trouble. Can you check if the following command  works?

`pulumi state delete 'urn:pulumi:xxx::xxx::network$gcp:organizations/project:Project::network'`

**Comment by ronnylt** [comment]
Sorry, I pasted the wrong grep command in the initial bug report. 

Anyhow, I imported the state into a local file and removed the resource by hand to make it work. 

Feel free to close the issue, I'll reopen it again if run into troubles with this again.

Thanks

**Comment by dixler** [comment]
No worries. I'm currently working on fixing some `pulumi state delete` bugs. So `@dixler` if you run into it again.

**Comment by hisuwh** [comment]
I'm getting this same problem.

![image](https://github.com/pulumi/pulumi/assets/4470351/8e8cac58-df94-4955-ab4e-b179054ce6ba)

![image](https://github.com/pulumi/pulumi/assets/4470351/c3f3dffe-3fd8-48f7-b31f-8cd0b1383b27)

**Comment by Frassle** [comment]
Looks like you probably hit the same thing as above. That urn has a $ symbol in which your shell is interpreting as a variable ("$azure") and replacing with the empty string before passing to the CLI.
You need to wrap the urn with quotes so the shell doesn't do variable substitution.

**Comment by danktec** [comment]
If anyone is here running into this issue... i needed to wrap my resource URN using single quotes.

```pulumi state delete 'urn:pulumi:ddd::ddd' ```
