### ISSUE TITLE
Official ArchLinux AUR binary

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi#12126]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

As of writing this, https://archlinux.org/packages/community/x86_64/pulumi/ is severely outdated.
We should consider publishing an official `pulumi-bin` package to https://aur.archlinux.org/.
This is something [goreleaser supports natively](https://goreleaser.com/customization/aur/)
so it wouldn't add to our release process significantly.

### Affected area/feature

releases

**Comment by abhinav** [comment]
I'll still follow up on this, but FYI:
we don't use goreleaser to push the binaries, so we can't just use the goreleaser AUR publishing support.
This will need to be done manually.

**Comment by andrewSC** [comment]
@abhinav I've updated `extra/pulumi` to the latest release (i.e. `3.72.2`) just now and plan to add `pulumi-java` and `pulumi-dotnet` in the next week or two to `[extra]`. That being said, I believe we can close this out as having an AUR package that duplicates what's in `[extra]` wouldn't add any value. Let me know if there's any questions or concerns, thanks!

**Comment by abhinav** [comment]
Thanks, @andrewSC. That works!
Yeah, there's no need to have a separate AUR package if Pulumi is already in `[extra]`.

Closing as wontfix.
