### ISSUE TITLE
Repeatedly running a stack with the automation API ignores project/stack config file changes

### ISSUE THREAD

**Issue by squaremo** [pulumi/pulumi#12152]
### What happened?

In https://github.com/pulumi/pulumi-kubernetes-operator/pull/407 I changed the Pulumi Kubernetes operator so that it checked out and ran each stack at a stable path. This change was so that the go build cache didn't treat all the files as new things to compile each time.
This exposed a problem with using the automation API in a long-running process: https://github.com/pulumi/pulumi-kubernetes-operator/issues/411. Essentially: if you rerun a stack, at the same path, the automation API will ignore any changes to Pulumi.&lt;stack&gt;.yaml, because it has cached the result of loading it the first time.

### Expected Behavior

I'd expect it to reload the file if it's changed.

### Steps to reproduce

There's a description of reproducing the problem with the opeartor: https://github.com/pulumi/pulumi-kubernetes-operator/issues/411#issuecomment-1428114730

### Output of `pulumi about`

N/A.

### Additional context

The caching was added in https://github.com/pulumi/pulumi/issues/6564. I am surprised it doesn't upset `pulumi watch` (maybe it does, and no-one has noticed?)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment]
Picking up a conversation from https://github.com/pulumi/pulumi/pull/12038:

> There's probably a sensible design to get the best of both worlds,

I think the original solution, memoising, was appealing because it was transparent to all the invocations of those funcs, so didn't involve chasing down all the possible ways they can be called. To retain that transparency without the problem it causes, what you'd want is memoising with respect to a thread of control -- in other words for the cached return values to be thread local. In go, a `context.Context is as close as it gets, and may already be threaded through much of the relevant code.

**Comment by Frassle** [comment]
Yeh we should just clean this up to not need global state. I'll see if we can start chipping away at this.
