### ISSUE TITLE
Pulumi preview stuck indefinitely

### ISSUE THREAD

**Issue by yz89122** [pulumi/pulumi#12168]
### What happened?

pulumi preview command will just stuck oftenly and randomly, retry can solve. Unknown reason.

```
$ pulumi --stack '***' preview -v 11 --logtostderr 2>log
Previewing update (***):
     Type                 Name                            Plan        
     pulumi:pulumi:Stack  *** running...
```

(The dots of `running...` is still animating.)

### Expected Behavior

Complete preview.

### Steps to reproduce

Just run pulumi preview.

### Output of `pulumi about`

```
pulumi about       
CLI          
Version      3.54.0
Go Version   go1.20
Go Compiler  gc

Host     
OS       darwin
Version  13.1
Arch     x86_64

Backend        
Name           ***
URL            file://~
User           ***
Organizations  

Pulumi locates its logs in /var/folders/pl/n_7kfrtd67n85qq7q_t286k80000gn/T/ by default
```

### Additional context

 - If it's not stuck, it'll complete in about 30 seconds
 - Our stack has about 2 thousands of resources.
 - While stucking, the log will just stop output
 - Didn't see an obvious error in last few lines of log (But I'm not a pulumi expert)
 - We're mainly use TypeScript (`runtime: nodejs`) and `@pulumi/gcp`
 - Retry can solve, this problem will just appear randomly
 - This problem also appear on GitHub Actions

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I'm moving this back to pulumi/pulumi, I've seen enough reports of this to be confident that it's an engine problem not specific to any one provider.

**Comment by yz89122** [comment]
> Hi @yz89122 thanks for taking the time to file the issue! Is it possible that you could share a sample (anonymised) program where the problem occurs during `pulumi preview`? The problem is likely specific the pulumi-gcp provider rather than a general `pulumi preview` problem. I will transfer the issue to that repository

@Zaid-Ajaj 

Sorry, I have no idea how to make a sample program to reproduce this problem in a small program.

I have tried the `-v 3` log option with stuck and successful cases, and what I can see is the last few lines in the stuck case is showing something like

```
I0215 12:09:51.168248   67433 eventsink.go:59] Registering resource: t=***, name=***, custom=false, remote=false
I0215 12:09:51.168369   67433 eventsink.go:59] Registering resource: t=***, name=***, custom=true, remote=false
```

and the successful case has more lines of `"Registering resource"` than the stuck case.

**Comment by Frassle** [comment]
I hit this the other day and it looked like the engine was stuck waiting for events to come from the node program. What ever the issue is here I _highly_ suspect it's in the nodejs sdk, not an engine issue.
In my case it looked like it got stuck after registering the stack resource but before running the users program code. Although @yz89122's case looks like it was partially through running their program before getting stuck.

**Comment by chrisui** [comment]
Just to add context in open (have provided much more detail through support tickets) we are primarily seeing hangs in previews but also occasionally in updates (likely biased because we generally run 10x more previews through ci vs cd). Primarily `pulumi-aws` with nodejs sdk.

Previews seem to hang after reading the first stack resource when they do. Updates are more funky and we've frequently seen 0..N/StackResourceTotal get updated (which does cause some dodgy deployment states but at least on forced cancellation re-run it picks up ok and resolves state).

**Comment by yz89122** [comment]
Thanks for @Frassle's assumption and @chrisui's additional context. I guess the problem is highly related to nodejs SDK. While I'm encountering the problem on my Mac, I can see the node process is consuming entire CPU core. I guess it stuck in a deadloop or something, so I added a few line of code to my program:

```js
(async () => {
  while (true) {
    await fs.appendFile('log', `${(new Date()).getTime()}\n`);
    await delay(1000); // setTimeout and Promise
  }
})();
```

And what I can observe is it written few lines timestamps and stopped writing.

Then I tried to use node.js option `--trace-sigint` to see what function is it running, and send `SIGINT` to the nodejs process. But what I encounter is nothing happened, the process didn't stop and no stack trace printed. I tried option `--trace-sigint` and `SIGINT` will work in normal case, it will print from pulumi's "Diagnostics" section. It just don't work when nodejs is stuck.

**Comment by yz89122** [comment]
Hi @Zaid-Ajaj, I made a TypeScript Pulumi program will probably reproduce this problem.

Init a new TypeScript program.

```ts
// index.ts
import * as pulumi from '@pulumi/pulumi';

class Test extends pulumi.CustomResource {
    constructor(name: string) {
        super('test', name)
    }
}

for (let i = 0; i < 10000; i++) new Test(`${i}`);
```

**Comment by squaremo** [comment]
Possibly pertinent: in https://github.com/pulumi/pulumi-aws/issues/2371, a NodeJS program appears to stall when there's O(1000) BucketObjects being created, and runs OK when not. It's using the service backend.

**Comment by yz89122** [comment]
Updated reproducible sample

Hi @Zaid-Ajaj, I made a sample program that can reproduce this problem [here (https://github.com/yz89122/reproduce-pulumi-issue-12168)](https://github.com/yz89122/reproduce-pulumi-issue-12168).

Note: I CANNOT reproduce either on my M1 MacBook, I can ONLY reproduce this problem on my Intel MacBook and x86 GCE instance.

**Comment by yz89122** [comment]
Hello @Zaid-Ajaj, I have created a sample Pulumi program that could potentially hang indefinitely. You can find the GitHub Actions log illustrating this issue here: https://github.com/yz89122/reproduce-pulumi-issue-12168/actions/runs/4553084335/jobs/8029215202. Unfortunately, I am unable to provide a reliable method for reproducing this issue consistently.

**Comment by yz89122** [comment]
Hi @Zaid-Ajaj and @Frassle, seems like recent version of Pulumi have fixed this problem. I cannot reproduce this problem anymore.

I have no idea what happened. I've check the release page, and I didn't see related release notes in recent releases.

Anyway, thanks for participating this issue. And I guess this issue can be closed.

**Comment by igor-pinchuk** [comment]
I am facing the same issue with python and latest pulumi version... why this issue is closed?

**Comment by Frassle** [comment]
@igor-pinchuk suggest raising a new issue, this is was for nodejs and didn't have a repro so was closed off.

**Comment by sravankumarreddybade** [comment]
Hi @Frassle - Raised https://github.com/pulumi/pulumi/issues/16476 for similar issue in pulumi go

**Comment by Frassle** [comment]
Given we've now got reports for node, go and dotnet I'd suggest just commenting on https://github.com/pulumi/pulumi/issues/16476. It might be this is an engine issue after all.

**Comment by Structed** [comment]
> I use the latest Pulumi and C# (not Nodejs), which also met this issue. (It's hard to share all the projects, but some logs are like the following.)
> 
> ```
> ==> Upgrading pulumi/tap/pulumi
>   3.117.0 -> 3.119.0
> ....
> 
> pulumi preview
> 
> ....
> 
> 
>     0 Error(s)
> 
> 
> Time Elapsed 00:00:01.44
> 
> 'dotnet build -nologo .' completed successfully
> ✨ Previewing update...⠖
> ⠐
> ⠐
> ⠂
> ```
> 
> And the online view:
> 
> <img alt="image" width="1551" src="https://private-user-images.githubusercontent.com/3367820/337617028-8b015b5d-3190-4f09-b4a8-5db96b9b17ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkwNTI3NzgsIm5iZiI6MTczOTA1MjQ3OCwicGF0aCI6Ii8zMzY3ODIwLzMzNzYxNzAyOC04YjAxNWI1ZC0zMTkwLTRmMDktYjRhOC01ZGI5NmI5YjE3Y2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMDhUMjIwNzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE4ZDUxMTVlOGNkYTU0YzY0OGNmNWFlMDQyMTM4ZDRkOGY0NzgxNTRmYjhjNTg2ZWVkNGFhZTZkNmRhNzgyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.v2IjQpClh-_D-dqelpTC2w0GexMnXhllRMZmpB8lNLw">
> I can share more when I get new findings but at least this issue was not completed.
> 
> ## Possible causes
> Pulumi started another process to execute the program, and it will hang forever if the underlying process gets killed.

I am seeing the same with the default C# Azure template. The only thing I changed was the resource group name
