### ISSUE TITLE
Cannot use string as Input type

### ISSUE THREAD

**Issue by maelp** [pulumi/pulumi#12187]
### What happened?

I want to create a Kubernetes nginx-ingress load-balancer, with a static IP that I define,

I do this:

```
web_ingress_ip = pulumi_gcp.compute.Address("web-ingress-ip", address_type="EXTERNAL")

ingress_controller = IngressController(
    "ingress-ctrl",
    controller=ControllerArgs(
        publish_service=ControllerPublishServiceArgs(
            enabled=True,
        ),
        service=ControllerServiceArgs(load_balancer_ips=web_ingress_ip.address),
    ),
)
```

but this results in an error because `web_ingress_ip.address` is a `str` and not an `Input`, not sure why it cannot convert it automatically?

Also, if the property is named `load_balancer_ips`, shouldn't this be a `List[Input[str]]`?

### Expected Behavior

To be able to create the nginx-ingress with the static ip reference

### Steps to reproduce

The code is in the issue

### Output of `pulumi about`

CLI          
Version      3.54.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME                      VERSION
docker                    3.1.0
gcp                       6.46.0
kubernetes                3.23.1
kubernetes-cert-manager   0.0.5
kubernetes-ingress-nginx  0.0.10
python                    unknown

Host     
OS       darwin
Version  13.0.1
Arch     x86_64

This project is written in python: executable='/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/bin/python3' version='3.10.9
'

Current Stack: maelp/infra-arch-pulumi/staging

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:staging::infra-arch-pulumi::pulumi:pulumi:Stack::infra-arch-pulumi-staging
docker:image:Image                          urn:pulumi:staging::infra-arch-pulumi::docker:image:Image::web-app-image
pulumi:providers:gcp                        urn:pulumi:staging::infra-arch-pulumi::pulumi:providers:gcp::gcp
pulumi:providers:gcp                        urn:pulumi:staging::infra-arch-pulumi::pulumi:providers:gcp::default_6_46_0
pulumi:providers:kubernetes                 urn:pulumi:staging::infra-arch-pulumi::pulumi:providers:kubernetes::cluster
gcp:compute/address:Address                 urn:pulumi:staging::infra-arch-pulumi::gcp:compute/address:Address::web-ingress-ip
gcp:artifactregistry/repository:Repository  urn:pulumi:staging::infra-arch-pulumi::gcp:artifactregistry/repository:Repository::gcp-docker-repository
kubernetes:apps/v1:Deployment               urn:pulumi:staging::infra-arch-pulumi::kubernetes:apps/v1:Deployment::web-app-2
kubernetes:apps/v1:Deployment               urn:pulumi:staging::infra-arch-pulumi::kubernetes:apps/v1:Deployment::web-app-1
kubernetes:core/v1:Service                  urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Service::web-app-2-svc
kubernetes:core/v1:Service                  urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Service::web-app-1-svc

Found no pending operations associated with staging

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/maelp
User           maelp
Organizations  maelp

Dependencies:
NAME                             VERSION
pip                              23.0.0
pulumi-docker                    3.1.0
pulumi-gcp                       6.46.0
pulumi-kubernetes-cert-manager   0.0.5
pulumi-kubernetes-ingress-nginx  0.0.10
setuptools                       66.0.0
wheel                            0.38.4

Pulumi locates its logs in /var/folders/6d/tgjjs7m13yngmk287mk9cv9h0000gp/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by maelp** [comment]
Seems to work if I do this though `load_balancer_ips="{}".format(web_ingress_ip.address)`

**Comment by Frassle** [comment]
I think this is the same issue reported at https://github.com/pulumi/pulumi-kubernetes-ingress-nginx/issues/12

I'll close this as a duplicate, and see if I can find which team is responsible for that repo these days to see if they can take another look. It does look like it might just be a typo.
