### ISSUE TITLE
Pulumi up too slow in Golang

### ISSUE THREAD

**Issue by raelix** [pulumi/pulumi#12186]
### What happened?

Currently I'm trying to deploy ~ 200 resources (that will be in a production system ~ 1.5k), I'm using external libraries to know what are the resources to create. Almost all of these (Helm charts) depends each other. 
Unfortunately, it looks to be really slow ~ 35/40 seconds for a preview and I'm using the local backend.

Looking at the logs, the "go build" (_Attempting to build go program_) execution takes approx ~30 seconds. 

I'm opening this issue to keep track of possible solutions to speed up the process. Is there a way to improve it? 

For example using the build=archive option for the imported module

### Expected Behavior

I expected to have a way of improving the execution, even with workaround, especially considering that in a preview/up the go build is called multiple times.

### Steps to reproduce

Just create 2 or 3 Kubernetes provider and 50 Helm charts that depends on them.

These are my required modules:
```
github.com/pulumi/pulumi-kubernetes/sdk/v3 v3.23.1
github.com/pulumi/pulumi/sdk/v3 v3.53.1
github.com/Masterminds/sprig/v3 v3.2.3
github.com/imdario/mergo v0.3.13
github.com/mitchellh/mapstructure v1.5.0
github.com/pkg/errors v0.9.1
github.com/rs/zerolog v1.29.0
gopkg.in/validator.v2 v2.0.1
gopkg.in/yaml.v3 v3.0.1
helm.sh/helm/v3 v3.11.0
```

### Output of `pulumi about`

```
CLI          
Version      3.54.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME        VERSION
go          unknown
kubernetes  3.23.1

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.19 linux/amd64'

Current Stack: production

Found no resources associated with production

Found no pending operations associated with production

Backend        
Name           raelix
URL            file://./vars
User           raelix
Organizations  

Dependencies:
NAME                                        VERSION
github.com/Masterminds/sprig/v3             3.2.3
github.com/imdario/mergo                    0.3.13
github.com/mitchellh/mapstructure           1.5.0
github.com/pkg/errors                       0.9.1
github.com/pulumi/pulumi-kubernetes/sdk/v3  3.23.1
github.com/pulumi/pulumi/sdk/v3             3.53.1
github.com/rs/zerolog                       1.29.0
gopkg.in/validator.v2                       2.0.1
gopkg.in/yaml.v3                            3.0.1
helm.sh/helm/v3                             3.11.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by raelix** [comment]
Looks like the buildTarget helps a lot: https://github.com/pulumi/pulumi-hugo/blob/d84434a04b351497f8531f7c85c2a0dc5dbe7fb6/themes/default/content/docs/reference/pulumi-yaml.md#about-buildtarget
Please let me know if you have further suggestion.

**Comment by Frassle** [comment]
`buildTarget` or `binary` are the solutions to this. `binary` won't run `go build` at all, so it's on you to make sure you're running `pulumi up` against an up to date artifact.
