### ISSUE TITLE
Banning provider version breaks existing stacks deployments

### ISSUE THREAD

**Issue by piotr-bzdyl-vertexinc** [pulumi/pulumi#12185]
### What happened?

Version 4.7.0 of the provider has been "yanked" as per https://github.com/pulumi/pulumi-tls/releases/tag/v4.7.0 description.

This results in existing stack already using that version to fail during previews and updates:
```
error: could not load plugin for tls provider 'urn:pulumi:POPPY-1157::a7s-env::pulumi:providers:tls::default_4_7_0': Could not automatically download and install resource plugin 'pulumi-resource-tls' at version v4.7.0, install the plugin using `pulumi plugin install resource tls v4.7.0`.
Underlying error: error downloading plugin tls to file: failed to download plugin: tls-4.7.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-tls-v4.7.0-darwin-arm64.tar.gz
```

### Expected Behavior

Either the version should not be banned/no longer served from the registry or a nice UX available for the users to easily bump the provider version without need to manually edit stack state (which is error prone).

### Steps to reproduce

Have a stack that already uses pulumi-tls 4.7.0 and try to run pulumi preview.

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I think it's fair to close this as we already have a load of tickets covering this space:
https://github.com/pulumi/pulumi/issues/12177 - is to change the behavior to generally not load or invoke old providers in the first place
https://github.com/pulumi/pulumi/issues/12155 - is to look into how this can be supported better already
https://github.com/pulumi/pulumi/issues/9878 - is to provide a way to force the update of the saved versions in the state
