### ISSUE TITLE
Prototype reserved instance analysis

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#122]
A scenario we've heard from customers is the need to have more intelligence around matching instances to existing reserved instances.  For example, when deploying a new instance, it would be great if we could check to ensure it matches an existing reserved instance (and warn if it doesn't, or possibly even dynamically rewrite the deployment).

**Comment by lukehoban** [comment]
We probably don't need to track a "prototype" issue here.  We may look into something around adding RI (or savings plans) coverage to our PaC feature, but it's also already possible to do this manually on PaC.  Will close this out as a standalone issue in this repo.
