### ISSUE TITLE
Error message for a missing required secret displays wrong command (no `--secret`)

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi#12207]
### What happened?

Give the following code:

```typescript
const config = new pulumi.Config();
const accessToken = config.requireSecret("pulumiAccessToken");
```

If the secret is not defined, we get the following error:

```text
Diagnostics:
  pulumi:pulumi:Stack (workshop-aws-proton-proton-dev):
    error: Missing required configuration variable 'workshop-aws-proton-proton:pulumiAccessToken'
        please set a value using the command `pulumi config set workshop-aws-proton-proton:pulumiAccessToken <value>`
```

### Expected Behavior

The command should be`pulumi config set workshop-aws-proton-proton:pulumiAccessToken <value> --secret`

### Steps to reproduce

(see above program)

### Output of `pulumi about`

```text
CLI          
Version      3.55.0
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.29.1
nodejs  unknown

Host     
OS       darwin
Version  13.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v19.5.0'

Current Stack: jkodrofftest/workshop-aws-proton-proton/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jkodroff
User           jkodroff
Organizations  jkodroff, jkodrofftest, demo, pulumi

Dependencies:
NAME            VERSION
@pulumi/aws     5.29.1
@pulumi/pulumi  3.55.0
@types/node     16.18.12

Pulumi locates its logs in /var/folders/5m/4n1x3f8151s35wc80w06z5k80000gn/T/ by default

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I think this error comes from each SDK, so we'll need to fix it up in all of them.

**Comment by heagma** [comment]
This is only for Python and Nodejs SDK. Go actually uses a different message (run `pulumi config ` to set) for all the require methods, which is more generic. 

I will open the relevant PR.

**Comment by heagma** [comment]
After reviewing the Python and Nodejs SDKs I found that the displayed message is also the same for all the `require ` objects (including secrets) as they are calling the same class wrapping the error message. 

Considering that this looks like a design decision, shall we make the Python and Nodejs message more generic (similar to the one in the Go SDK) like having **"run `pulumi config`  to set**" instead of "**please set a value using the command `pulumi config set <value>`**" to avoid this confusion when requiring secrets instead of other config values? @Frassle .

**Comment by Frassle** [comment]
That sounds reasonable.

**Comment by justinvp** [comment]
> shall we make the Python and Nodejs message more generic (similar to the one in the Go SDK)

I actually kind of like that it shows the exact command to run. I don't think it'd be too difficult to make the secret ones have an error message that includes the `--secret` flag in the suggested command.
