### ISSUE TITLE
bors: Can't merge community PRs

### ISSUE THREAD

**Issue by abhinav** [pulumi/pulumi#12248]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We recently added lint checks as blockers for bors to attempt to merge a PR: https://github.com/pulumi/pulumi/blob/34417a33ce51274e4e531a8d78ce0531fcedcbdf/bors.toml#L11-L14

However, those lint jobs do not run for community PRs.
This makes it impossible to merge community PRs with bors.

We can pick one of the following:

- have lint jobs run on community PRs
- drop the above requirement from bors

Worth noting that this change was made because @dixler found that lint failures were the most common cause for bors merges to fail. So it's preferable if we keep that check.

**Comment by abhinav** [comment]
Update: With #12249, we're unblocked, but this does remove the lint blocker.
There are two possible options now:

- Add the bors lint blocker back, and change community PR GitHub Workflow to run lint for community PRs as well
- Leave it as is, and eat the wasted lint time on bors merges. This is less of a problem now that our CI pipeline won't run tests until lint passes (#12028)

**Comment by abhinav** [comment]
FYI @dixler I had to drop the check from bors.toml because of this.
Do you have thoughts on how we should proceed?

**Comment by tgummerer** [comment]
I just noticed this issue through a different issue search.  We no longer use bors, and we are able to merge community PRs, so I'll go ahead and close this issue out.
