### ISSUE TITLE
Undefined stack exports should serialize as "undefined"

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#1224]
In https://github.com/pulumi/pulumi/issues/1223, I used an undefined property as a stack output:

```
let siteBucket = new aws.s3.Bucket("s3-website-bucket");
exports.bucketName = siteBucket.bucketName; // there is no property 'bucketName' on s3.Bucket!
```

In this case, the stack output is simply ignored: running this program shows no stack exports. Instead, Pulumi should use the string "undefined", so that customers can find their error more easily.

**Comment by lukehoban** [comment]
Though perhaps slightly surprising, this is consistent with the rest of our treatment of `undefined` and I'm not eager to add special cases to our JSON serialization for this unless we have to.  For now, I think we should leave this as is, and see if it becomes a common pain point that really does need further special casing.
