### ISSUE TITLE
calling rm on stack A while inside of stack B deletes B's Pulumi.dev.yaml

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#12246]
_this was reported by a customer, reach out to @susanev if ya need more deets and internal links_

## repro steps
1. create project A/stack A
1. create project B/stack B
1. nav inside of stack A
1. run rm on stack B
1. notice that it deleted `Pulumi.dev.yaml` from stack A

**Comment by susanev** [comment]
cc/ @Frassle

**Comment by Frassle** [comment]
Rephrasing the above a bit I think this is talking about different projects? 

So it's 
* Create a project in folder A, create a stack "dev" for that project, set some config for it to make a "Pulumi.dev.yaml" file
* Create a project in a different folder B, create a stack "dev" for that project, set some config for it to make a "Pulumi.dev.yaml" file
* Navigate to folder "A" and run `stack rm owner/B/dev`. It deletes the stack dev for the B project but then deletes the config file in the current folder which is the A project.

Is that right?

**Comment by susanev** [comment]
@Frassle oh yes sry, this is talking about different projects

in my test run it didn't actually delete anything for B project, but i might have done something wrong
