### ISSUE TITLE
Mark/output variable as not secret

### ISSUE THREAD

**Issue by Pithikos** [pulumi/pulumi#12253]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Allow us to mark an output as not secret explicitly. I couldn't find if this is already available somewhere.

```python
kubeconfig_path = pulumi.Output.all(cluster_kubeconfig, cluster.name).apply(lambda args: update_kubeconfig(*args))
pulumi.export("kubeconfigPath", kubeconfig_path)
```

`kubeconfig_path` shows as `[secret]` while it's clearly not. So it adds unessesary steps just to decrypt multiple variables like it.

I assume this happens since kubeconfig holds a certificate.

**Comment by Frassle** [comment]
Have you seen the [Output.unsecret](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#unsecret) function? I think that's all you need for this.

**Comment by Pithikos** [comment]
Yes that seems to work for now. Thanks
