### ISSUE TITLE
Pulumi python does not have a "apply" method for kubernetes secret

### ISSUE THREAD

**Issue by maelp** [pulumi/pulumi#12250]
### What happened?

I'm creating a Kubernetes secret, then trying to get its name to input as parameter in an nginx ingress, but there is no "apply" method to get the name after the secret creation

### Expected Behavior

I could use something like `secret.metadata.apply(lambda t: t.name)`

### Steps to reproduce

Create a secret and try to export it, it will generate an error

```
client_ca_secret = Secret(
    "client-ca",
    metadata=ObjectMetaArgs(
        namespace="default",
    ),
    data={
        "ca.crt": base64.b64encode(
            open("ca.crt", "rb").read()
        ).decode("ascii")
    },
    opts=pulumi.ResourceOptions(provider=k8s_provider),
)

... later

pulumi.export("secret-name-with-namespace", f"default/{client_ca_secret.metadata.apply(lambda t: t.name)}")
```

this returns something like

```
secret-name-with-namespace: "default/Calling __str__ on an Output[T] is not supported.\n\nTo get the value of an Output[T] as an Output[str] consider:\n1. o.apply(lambda v: f\"prefix{v}suffix\")\n\nSee https://pulumi.io/help/outputs for more details.\nThis function may throw in a future version of Pulumi."
```

### Output of `pulumi about`

CLI          
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME                      VERSION
docker                    3.1.0
gcp                       6.46.0
kubernetes                3.23.1
kubernetes-cert-manager   0.0.5
kubernetes-ingress-nginx  0.0.10
python                    unknown

Host     
OS       darwin
Version  13.0.1
Arch     x86_64

This project is written in python: executable='/Users/primet/work/gouach/code/gouach-backend/infra-arch-pulumi/venv/bin/python3' version='3.10.9
'

Current Stack: maelp/infra-arch-pulumi/staging

TYPE                                                                       URN
pulumi:pulumi:Stack                                                        urn:pulumi:staging::infra-arch-pulumi::pulumi:pulumi:Stack::infra-arch-pulumi-staging
docker:image:Image                                                         urn:pulumi:staging::infra-arch-pulumi::docker:image:Image::web-app-image
pulumi:providers:gcp                                                       urn:pulumi:staging::infra-arch-pulumi::pulumi:providers:gcp::gcp
pulumi:providers:gcp                                                       urn:pulumi:staging::infra-arch-pulumi::pulumi:providers:gcp::default_6_46_0
pulumi:providers:kubernetes                                                urn:pulumi:staging::infra-arch-pulumi::pulumi:providers:kubernetes::cluster
pulumi:providers:kubernetes                                                urn:pulumi:staging::infra-arch-pulumi::pulumi:providers:kubernetes::default_3_23_1
gcp:artifactregistry/repository:Repository                                 urn:pulumi:staging::infra-arch-pulumi::gcp:artifactregistry/repository:Repository::gcp-docker-repository
kubernetes:core/v1:Secret                                                  urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Secret::gouach-server-certificate
kubernetes:core/v1:Secret                                                  urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Secret::client-ca
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:apps/v1:Deployment::web-app-1
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:apps/v1:Deployment::web-app-2
gcp:compute/address:Address                                                urn:pulumi:staging::infra-arch-pulumi::gcp:compute/address:Address::web-ingress-ip
kubernetes:core/v1:Namespace                                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Namespace::cert-manager
kubernetes:core/v1:Namespace                                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Namespace::ingress-nginx
kubernetes:helm.sh/v3:Chart                                                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart::cert-manager
kubernetes:cert-manager.io/v1:ClusterIssuer                                urn:pulumi:staging::infra-arch-pulumi::kubernetes:cert-manager.io/v1:ClusterIssuer::cert-manager-cluster-issuer
kubernetes:helm.sh/v3:Chart                                                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart::ingress-nginx
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Service::web-app-1-svc
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:core/v1:Service::web-app-2-svc
kubernetes:networking.k8s.io/v1:Ingress                                    urn:pulumi:staging::infra-arch-pulumi::kubernetes:networking.k8s.io/v1:Ingress::web-app-ingress-tls-letsencrypt
kubernetes:networking.k8s.io/v1:Ingress                                    urn:pulumi:staging::infra-arch-pulumi::kubernetes:networking.k8s.io/v1:Ingress::web-app-ingress-mtls
kubernetes:core/v1:ServiceAccount                                          urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::cert-manager/cert-manager-cainjector
kubernetes:core/v1:ServiceAccount                                          urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::cert-manager/cert-manager
kubernetes:core/v1:ConfigMap                                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ConfigMap::cert-manager/cert-manager-webhook
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:Service::cert-manager/cert-manager-webhook
kubernetes:core/v1:ServiceAccount                                          urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::cert-manager/cert-manager-startupapicheck
kubernetes:core/v1:ServiceAccount                                          urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::ingress-nginx/ingress-nginx
kubernetes:core/v1:ConfigMap                                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ConfigMap::ingress-nginx/ingress-nginx-controller
kubernetes:core/v1:ServiceAccount                                          urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::cert-manager/cert-manager-webhook
kubernetes:core/v1:ServiceAccount                                          urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::ingress-nginx/ingress-nginx-admission
kubernetes:batch/v1:Job                                                    urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:batch/v1:Job::cert-manager/cert-manager-startupapicheck
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:Service::cert-manager/cert-manager
kubernetes:batch/v1:Job                                                    urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:batch/v1:Job::ingress-nginx/ingress-nginx-admission-patch
kubernetes:batch/v1:Job                                                    urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:batch/v1:Job::ingress-nginx/ingress-nginx-admission-create
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:Service::ingress-nginx/ingress-nginx-controller-admission
kubernetes:core/v1:Service                                                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:Service::ingress-nginx/ingress-nginx-controller
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::certificaterequests.cert-manager.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::orders.acme.cert-manager.io
kubernetes:admissionregistration.k8s.io/v1:MutatingWebhookConfiguration    urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:admissionregistration.k8s.io/v1:MutatingWebhookConfiguration::cert-manager-webhook
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::certificates.cert-manager.io
kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration  urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration::cert-manager-webhook
kubernetes:networking.k8s.io/v1:IngressClass                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:networking.k8s.io/v1:IngressClass::nginx
kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration  urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration::ingress-nginx-admission
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::challenges.acme.cert-manager.io
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::clusterissuers.cert-manager.io
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-cainjector
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-certificates
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-issuers
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-webhook:subjectaccessreviews
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition                urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::issuers.cert-manager.io
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-orders
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-cainjector
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-view
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-challenges
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-certificatesigningrequests
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-issuers
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-ingress-shim
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-clusterissuers
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-edit
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::cert-manager-controller-approve:cert-manager-io
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-clusterissuers
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-certificates
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-orders
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-challenges
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-ingress-shim
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-approve:cert-manager-io
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-controller-certificatesigningrequests
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::cert-manager-webhook:subjectaccessreviews
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::ingress-nginx
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::ingress-nginx
kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRole::ingress-nginx-admission
kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding                 urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding::ingress-nginx-admission
kubernetes:rbac.authorization.k8s.io/v1:Role                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::cert-manager/cert-manager:leaderelection
kubernetes:rbac.authorization.k8s.io/v1:Role                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::cert-manager/cert-manager-webhook:dynamic-serving
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::cert-manager/cert-manager-cainjector:leaderelection
kubernetes:rbac.authorization.k8s.io/v1:Role                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::cert-manager/cert-manager-cainjector:leaderelection
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::cert-manager/cert-manager:leaderelection
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::cert-manager/cert-manager-webhook:dynamic-serving
kubernetes:rbac.authorization.k8s.io/v1:Role                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::cert-manager/cert-manager-startupapicheck:create-cert
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::cert-manager/cert-manager-startupapicheck:create-cert
kubernetes:rbac.authorization.k8s.io/v1:Role                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::ingress-nginx/ingress-nginx
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::ingress-nginx/ingress-nginx
kubernetes:rbac.authorization.k8s.io/v1:Role                               urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::ingress-nginx/ingress-nginx-admission
kubernetes:rbac.authorization.k8s.io/v1:RoleBinding                        urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:rbac.authorization.k8s.io/v1:RoleBinding::ingress-nginx/ingress-nginx-admission
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apps/v1:Deployment::cert-manager/cert-manager-cainjector
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apps/v1:Deployment::cert-manager/cert-manager
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apps/v1:Deployment::cert-manager/cert-manager-webhook
kubernetes:apps/v1:Deployment                                              urn:pulumi:staging::infra-arch-pulumi::kubernetes:helm.sh/v3:Chart$kubernetes:apps/v1:Deployment::ingress-nginx/ingress-nginx-controller

Found no pending operations associated with staging

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/maelp
User           maelp
Organizations  maelp

Dependencies:
NAME                             VERSION
pip                              23.0.0
pulumi-docker                    3.1.0
pulumi-gcp                       6.46.0
pulumi-kubernetes-cert-manager   0.0.5
pulumi-kubernetes-ingress-nginx  0.0.10
setuptools                       66.0.0
wheel                            0.38.4

Pulumi locates its logs in /var/folders/6d/tgjjs7m13yngmk287mk9cv9h0000gp/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
The long text string returned does point to https://www.pulumi.com/docs/intro/concepts/inputs-outputs for more information about this, but the crux of it is `apply` returns another `Output`, and python 'f' strings try to call `__str__` on their arguments, so in the following code:
```f"default/{client_ca_secret.metadata.apply(lambda t: t.name)}```
Your telling python to try and call `__str__` on the Output for `t.name`, which isn't supported.

You want to use output-aware formatting methods like `pulumi.Output.format`:
```
Output.format("default/{0}", client_ca_secret.metadata.apply(lambda t: t.name))
````

**Comment by maelp** [comment]
Thanks :)

**Comment by maelp** [comment]
@Frassle while we're at it, would you know why it's not possible to give a `namespace` to kubernetes ingress `IngressTLSArgs`?

When I create a secret in a given namespace and I do something like 

```
        tls=[
            IngressTLSArgs(
                hosts=[f"web-app-2.{base_hostname}"],
                secret_name=Output.format(
                    "{}.{}",
                    cert_secrets_namespace,
                    server_certificate_secret.metadata.name,
                ),
            ),
        ],
```

I get an error because the secret has a "/" in the name, but it is expected to be RFC 1123 compliant (I also tried "namespace.secret-name" but it doesn't work either)

```
	* the Kubernetes API server reported that "default/web-app-ingress-mtls-6024220f" failed to fully initialize or become live: Ingress.extensions "web-app-ingress-mtls-6024220f" is invalid: spec.tls[0].secretName: Invalid value: "ingress-nginx/server-certificate-secret": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
