### ISSUE TITLE
registerStackTransformations not applying

### ISSUE THREAD

**Issue by smainil** [pulumi/pulumi#12255]
### What happened?

My goal was to be able to execute a transformation on each azure ressource I create in my pulumi project but it doesn't work.

I referenced the dependencies:
@pulumi/azure-native: 1.95.0
@pulumi/pulumi: 3.55.0

As a result: the yarn.lock file referenced the @pulumi/pulumi versions: 3.19.0 (from the azure-native) and 3.55.0

I found an existing issue about registerStackTransformations not registering when having parallel pulumi instance version used

And of course if I force the @pulumi/pulumi to also use the 3.19.0, the registerStackTransformations works really well.

Am I missing some step to be able to have multiple pulumi version and registerStackTransformations working perfectly

### Expected Behavior

I expected that the registerStackTransformations raised on each Ressource defined in my pulumi stack

### Steps to reproduce

defaultTags.ts
```ts
import * as pulumi from '@pulumi/pulumi'

export function registerTags(autoTags: Record<string, string>): void {
    pulumi.runtime.registerStackTransformation((args) => {
        if (isAzureResource(args) && hasTagsProperty(args)) {
            args.props["tags"] = { ...args.props["tags"], ...autoTags };
            return { props: args.props, opts: args.opts };
        }
        return undefined;
    });
}

const isAzureResource = (args: pulumi.ResourceTransformationArgs): boolean => args.type.startsWith("azure")

const hasTagsProperty = (args: pulumi.ResourceTransformationArgs): boolean => 'tags' in args.props
```

index.ts
```ts
import * as resources from '@pulumi/azure-native/resources'
import * as pulumi from '@pulumi/pulumi'

import { registerTags } from './defaultTags'

const stack = pulumi.getStack()
const projectName = pulumi.getProject()
const projectConfig = new pulumi.Config('project')

registerTags({
    "project:name": pulumi.getProject(),
    "project:url": projectConfig.require('url'),
    "pulumi:stack": pulumi.getStack(),
})

const resourceGroupName = `rg-test-register`
const resourceGroup = new resources.ResourceGroup(resourceGroupName, {
    resourceGroupName: resourceGroupName,
})
```

package.json
```json
    "dependencies": {
        "@pulumi/azure-native": "1.95.0",
        "@pulumi/pulumi": "3.55.0"
    },
```

### Output of `pulumi about`

CLI
Version      3.48.0
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.95.0
nodejs        unknown

Host
OS       darwin
Version  13.2
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v17.3.1'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/MAIF
User           MAIF
Organizations  MAIF, freetrialteamproedition

Pulumi locates its logs in /var/folders/20/m73l6kz113gcrttc52fj7hjc82hwfc/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Hi @smainil, thanks for opening an issue and sorry for the trouble! The issue with `registerStackTransformations` when there are multiple copies of `@pulumi/pulumi` should be addressed if all of those copies are 3.35.3 or higher (fixed in https://github.com/pulumi/pulumi/pull/9680).

I just tried creating a new project with Azure Native, and I only got one copy of `@pulumi/pulumi@3.55.0`. If you do end up in a situation where there are multiple copies of `@pulumi/pulumi`, deleting the lock file and `node_modules` and re-running `yarn install` often addresses the issue.
