### ISSUE TITLE
It's not possible to set the path for a config with the Automation API

### ISSUE THREAD

**Issue by raelix** [pulumi/pulumi#12254]
### What happened?

Hello, I'm trying to set the path for a config with the Automation API in Golang.
With the CLI it will be:
```shell
pulumi config set --path 'labels.injection.value' enabled
```
But seems to be not possible with the Automation API in Golang which uses:
```go
(s *Stack) SetConfig(ctx context.Context, key string, val ConfigValue)
```
This because when it runs the command doesn't specify the ```--path``` flag:
```go
	stdout, stderr, errCode, err := l.runPulumiCmdSync(ctx,
		"config", "set", key, secretArg, "--stack", stackName,
		"--non-interactive", "--", val.Value)
```

### Expected Behavior

I expected an output like:
```yaml
encryptionsalt: ....
config:
  automation:labels:
    injection: value
```

### Steps to reproduce

Just run on a stack:
```go
stack.SetConfig(ctx, "labels.injection.value", auto.ConfigValue{Value: value, Secret: false})
```

### Output of `pulumi about`

```shell
CLI          
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Hi @raelix, thanks for opening the issue and sorry for the trouble! This is indeed a gap between what the CLI supports and what's currently exposed from automation API. Until we've closed the gap, some potential workarounds would be to write the config file programmatically or shell out to `pulumi config set --path` from Go.

**Comment by raelix** [comment]
Thanks @justinvp  I just raised a MR to solve it
