### ISSUE TITLE
Too many temporary directories with nodejs SDK

### ISSUE THREAD

**Issue by skdltmxn** [pulumi/pulumi#12263]
### What happened?

I am currently running the operator with two Stacks which are repeatedly synced every minute.

There is no problem with synchronization, but I found out that there are a lot of `pulumi-node-pipes` directories in /tmp after a couple of days I ran the operator.

It seems like each directory is created on every `pulumi update` and never gets removed after sync.  
As of writing this issue, I have over 13000 directories in the operator pod.

```bash
$ ls /tmp/pulumi-node-pipes* | wc -l
$ 13267
```

![image](https://user-images.githubusercontent.com/4114833/219841987-91325ab9-3043-4853-bb57-cebef48a94a5.png)

### Expected Behavior

Any temporary files or directories should be cleaned up after synchronization

### Steps to reproduce

1. Create a stack with `continueResyncOnCommitMatch` set true.
2. Watch `pulumi-node-pipes` folder created in /tmp and never gets deleted.

### Output of `pulumi about`

```
CLI
Version      3.46.0
Go Version   go1.19.2
Go Compiler  gc

Host
OS       debian
Version  11.5
Arch     x86_64

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I actually noticed these files on my machine on Friday, was going to be something to look into after refresh week.
