### ISSUE TITLE
Pulumi stack outputs slurp a JSON file

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#12301]
### What happened?

Pulumi CLI seems to read "../$(dirname).json" file and adopt it into stack outputs. Is this an Easter Egg or documented behavior that happens for some good reason?

### Expected Behavior

This is just surprising. I had accidental file layout that polluted my stack with unexpected stack outputs.

### Steps to reproduce

```
echo '[{"foo": "bar"}]' > foo.json
mkdir foo
cd foo
pulumi new typescript
pulumi preview
```

```
Previewing update (dev)

View Live: https://app.pulumi.com/t0yv0/foo/dev/previews/5e5951c5-649f-469c-91a3-d6c8d79180d0

     Type                 Name     Plan       
 +   pulumi:pulumi:Stack  foo-dev  create     


Outputs:
    0: {
        foo: "bar"
    }

Resources:
    + 1 to create
```

### Output of `pulumi about`

CLI          
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.1
Arch     x86_64
```
This project is written in nodejs: executable='/Users/t0yv0/.nix-profile/bin/node' version='v18.12.1'

Current Stack: t0yv0/foo/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.55.0
@types/node     16.18.13

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Note this seems unique to node

**Comment by Frassle** [comment]
Seems to be this line: https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/cmd/run/run.ts#L376

That's calling `require` with the folder of program (e.g. /home/fraser/projects/foo), and require seems to be picking up the json file.
