### ISSUE TITLE
LICENSE should include year and actual copyright owner

### ISSUE THREAD

**Issue by thndrbrrr** [pulumi/pulumi#12316]
Just a minor oversight – `LICENSE` has not been updated with the actual years and copright owners:

```
   Copyright [yyyy] [name of copyright owner]

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
```

**Comment by Frassle** [comment]
That's not actually intended to be filled in, its an example from the Apache license of how anyone using it should apply it. But this isn't the first time this query has come up, and legally the appendix doesn't need to be maintained in the license file so I'll just remove it to save confusion.

**Comment by thndrbrrr** [comment]
Ooops, my apologies, I didn't notice that it appeared under `APPENDIX: How to apply the Apache License to your work.`
