### ISSUE TITLE
Restore previous scroll behavior

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi#12320]
A recent CLI update appears to have changed the way scrolling works. Now, when there are more resources than can be shown on a given terminal window, we show a little "more" indicator in the lower-right corner:

![image](https://user-images.githubusercontent.com/274700/222258192-405a9253-9f24-4f43-9503-4fe1504c5570.png)

There are a couple of problems with this new behavior, IMO:

* It's really easy to miss that indicator (I missed it myself until someone pointed it out) and even when you do see it, it's not clear how to interact with it.
* Because the view doesn't scroll automatically as new resources are discovered, it can make for an update experience that looks "stuck" -- e.g., when the visible list of resources is all "created", those still "creating" are offscreen, and the mouse doesn't allow you to scroll down like it used to.
* For those used to scrolling in the terminal with a mouse (like me), having to scroll Pulumi output with the arrow keys (when everything else still works with the mouse) is tedious, especially during a long update or one involving dozens or hundreds of resources.

I'm sure these changes were made for good reason, but the experience feels significantly less usable to me now. Previously, I could scroll up and down with the mouse during an update and see all that I needed to see, so since I don't seem to be able to see more now than I could before, it isn't clear (to me at least) how the new behavior is "better" -- but again, I might just be missing it. 

If others agree, though, I'd strongly suggest we consider returning to the previous behavior, and perhaps make the new behavior optional or configurable somehow.

**Comment by dixler** [comment]
I agree with this sentiment. It also seems to get stuck.
