### ISSUE TITLE
[Go] Regression in multi-line string

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#12358]
### What happened?

Observing the diff https://github.com/pulumi/pulumi-akamai/actions/runs/4328374490/jobs/7558039509, we previously generated a JSON string literal as 

```go
pulumi.String(fmt.Sprintf(`  [
	  {
	    "name": "rule1",
	    "type": "erMatchRule",
	    "useRelativeUrl": "none",
	    "statusCode": 301,
	    "redirectURL": "https://www.example.com",
	    "matchURL": "example.com",
	    "useIncomingQueryString": false,
	    "useIncomingSchemeAndHost": false
	  },
	  {
	    "name": "rule2",
	    "type": "erMatchRule",
	    "matches": [
	      {
	        "matchType": "path",
	        "matchValue": "/example/website.html",
	        "matchOperator": "equals",
	        "caseSensitive": false,
	        "negate": false
	      }
	    ],
	    "useRelativeUrl": "copy_scheme_hostname",
	    "statusCode": 301,
	    "redirectURL": "/website.html",
	    "useIncomingQueryString": false,
	    "useIncomingSchemeAndHost": true
	  }

 ]
 `))
```

This isn't 100% optimal, since the call to `fmt.Sprintf` is not necessary, but its very human readable.

After upgrading from tf-bridge v3.40.0 to v3.41.0, the generated string looks like:

```go
pulumi.String("  [\n  {\n    \"name\": \"rule1\",\n    \"type\": \"erMatchRule\",\n    \"useRelativeUrl\": \"none\",\n    \"statusCode\": 301,\n    \"redirectURL\": \"[https://www.example.com\](https://www.example.com/)",\n    \"matchURL\": \"example.com\",\n    \"useIncomingQueryString\": false,\n    \"useIncomingSchemeAndHost\": false\n  },\n  {\n    \"name\": \"rule2\",\n    \"type\": \"erMatchRule\",\n    \"matches\": [\n      {\n        \"matchType\": \"path\",\n        \"matchValue\": \"/example/website.html\",\n        \"matchOperator\": \"equals\",\n        \"caseSensitive\": false,\n        \"negate\": false\n      }\n    ],\n    \"useRelativeUrl\": \"copy_scheme_hostname\",\n    \"statusCode\": 301,\n    \"redirectURL\": \"/website.html\",\n    \"useIncomingQueryString\": false,\n    \"useIncomingSchemeAndHost\": true\n  }\n]\n")`
```

We loose the unnecessary `fmt.Sprintf` (good), and the multi-line string literal (bad). 

### Expected Behavior

Long multi-line strings are rendered as multi-line string literals (using \`), not single line string literals (using `"`).

### Steps to reproduce

Upgrade the codegen version used.

### Output of `pulumi about`

NA

### Additional context

The upgrade bumps the used version of pulumi/pkg from v3.55.0 to v3.56.0. The original issue is https://github.com/pulumi/pulumi-akamai/pull/152.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Taking a look. I haven't yet found where this changed.
