### ISSUE TITLE
NewProvider arguments `args` has wrong type in docs

### ISSUE THREAD

**Issue by squaremo** [pulumi/pulumi#12356]
### Problem description

On https://www.pulumi.com/registry/packages/auth0/api-docs/provider/ for the go snippet, the `args` argument is typed `ProviderArgs`, but the type of that argument is `*ProviderArgs`: https://github.com/pulumi/pulumi-auth0/blob/master/sdk/go/auth0/provider.go.

### Suggestions for a fix

I _suspect_ that is for tfgen-generated projects, on flimsy evidence -- pulumi-mysql (tfgen) has the same problem, and pulumi-eks (not tfgen) does not.

**Comment by justinvp** [comment]
Looks like this has since been addressed, it shows as `*ProviderArgs` in the docs now.

![Image](https://github.com/user-attachments/assets/7892664a-81e6-4111-b073-968be5693edb)
