### ISSUE TITLE
Panic when pressing `Ctrl + C`

### ISSUE THREAD

**Issue by Ravemba** [pulumi/pulumi#12371]
### What happened?

Fatal error

### Expected Behavior

No errors

### Steps to reproduce

Run:
pulumi up
yes 

### Output of `pulumi about`

```
Pulumi Version:   v3.50.1
Go Version:       go1.19.4
Go Compiler:      gc
Architecture:     amd64
Operating System: windows Name      Status
Panic:            send on closed channel
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.19.4/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x20fd300, 0x2a778b0})
        /opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:884 +0x212
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.loadPlugin(0x0?, 0xc0009d8660)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:256 +0xbd
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).Provider(0xc0002b09a0, {0xc0003f4567, 0x5}, 0xc001664140)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:332 +0xb6
github.com/pulumi/pulumi/pkg/v3/resource/deploy/providers.loadProvider({0xc0003f4567?, 0x5?}, 0xc001d9e7b0?, {0x2aabca8?, 0xc0002b09a0?}, {0x2aafee0?, 0xc0009d8570?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/providers/registry.go:107 +0xb7
github.com/pulumi/pulumi/pkg/v3/resource/deploy/providers.NewRegistry({0x2aabca8?, 0xc0002b09a0}, {0xc000e34000, 0xb7, 0xc00251cce0?}, 0x0, {0x2aafee0?, 0xc0009d8570?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/providers/registry.go:149 +0x3f2
github.com/pulumi/pulumi/pkg/v3/resource/deploy.NewDeployment(0xc002aebea0, 0xc003124a80, 0xc0023f4750, 0x0, {0x2a9b0a8?, 0xc001b98180}, {0x3c95760, 0x0, 0x0}, 0x0, ...)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:459 +0x347
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x3c95760, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:189 +0x407
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x3c95760, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/engine/update.go:454 +0x391
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x2a96c50, _}, _, {{0x3c95760, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/engine/update.go:196 +0x670
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc0001adb80, {0xc00004d380, 0x52}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1180 +0x82f
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc0001adb80, {0xc00004d380, 0x52}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1087 +0x43f
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc0001adb80, {0xc00004d380, 0x52}, {0x0, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/apply.go:261 +0x24d
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Update(_, {_, _}, {_, _}, {0xc0001adb80, {0xc00004d380, 0x52}, {0x0, 0x0, ...}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:970 +0xc5
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc0001adb80, {0xc00004d380, 0x52}, {0x0, 0x0, 0x0}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/stack.go:91 +0xba
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Update(_, {_, _}, {0xc0001adb80, {0xc00004d380, 0x52}, {0x0, 0x0, 0x0}, 0xc0004151e8, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:156 +0x88
main.newUpCmd.func1({_, _}, {{{0x3c95760, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:182 +0xf97
main.newUpCmd.func3(0x0?, {0x3c95760, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:496 +0xc65
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc00068ec00?, {0x3c95760, 0x0, 0x0})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc00068ec00, {0x3c95760, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000840f00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Hi @Ravemba. Thanks for opening an issue and sorry for the trouble. Do you get the same error using the latest version of Pulumi?

**Comment by lonegunmanb** [comment]
Hi @justinvp, I just get the following error with v3.59.0 which I believe is the latest version:

We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.59.0
Go Version:       go1.20.2
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            send on closed channel

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.2/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x1f79960, 0x28d27a0})
        /opt/hostedtoolcache/go/1.20.2/x64/src/runtime/panic.go:884 +0x213
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.loadPlugin(0x0?, 0xc00145c6e0)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:268 +0xbd
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).LanguageRuntime(0xc000c92070, {0x0, 0x0}, {0xc0009297c0, 0x20}
, {0xc0009542b0, 0x2}, 0x0)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:393 +0x125
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).EnsurePlugins(0xc000c92070, {0xc00104e780?, 0x6, 0x0?}, 0x3)  
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:449 +0x247
github.com/pulumi/pulumi/pkg/v3/engine.ensurePluginsAreLoaded(0xc0009761e0, 0xc0004f0c90, 0xc000d9ca68?)
        /home/runner/work/pulumi/pulumi/pkg/engine/plugins.go:208 +0x1c6
github.com/pulumi/pulumi/pkg/v3/engine.newUpdateSource({_, _}, {{{0x3b5c368, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, .
..)
        /home/runner/work/pulumi/pulumi/pkg/engine/update.go:392 +0xa5
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(_, _, {{{0x3b5c368, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...) 
        /home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:181 +0x2ea
github.com/pulumi/pulumi/pkg/v3/engine.update(_, _, {{{0x3b5c368, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)        
        /home/runner/work/pulumi/pulumi/pkg/engine/update.go:457 +0x391
github.com/pulumi/pulumi/pkg/v3/engine.Update({0x28f2270, _}, _, {{0x3b5c368, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, ...}, ...)       
        /home/runner/work/pulumi/pulumi/pkg/engine/update.go:198 +0x690
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc000956000, {0xc0009297
c0, 0x20}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1177 +0x8ef
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc000956000, {0xc0009297c0, 0x20},
 ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1093 +0x498
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt({_, _}, {_, _}, {_, _}, {0xc000956000, {0xc0009297c0, 0x20}, {0x0, ...}, ...}
, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/apply.go:116 +0x17a
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc000956000, {0xc0009297c0, 0x20}, {0x0,
 ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/backend/apply.go:229 +0x13e
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Update(_, {_, _}, {_, _}, {0xc000956000, {0xc0009297c0, 0x20}, {0x0, 
0x0, ...}, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:980 +0xc5
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc000956000, {0xc0009297c0, 0x20}, {0x0, 0x0, 0x0}, ...})        
        /home/runner/work/pulumi/pulumi/pkg/backend/stack.go:95 +0xba
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Update(_, {_, _}, {0xc000956000, {0xc0009297c0, 0x20}, {0x0, 0x0, 0x0},
 0xc0005a7890, ...})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:162 +0x88
main.newUpCmd.func1({_, _}, {{{0x3b5c368, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:176 +0x1255
main.newUpCmd.func3(0x0?, {0xc0000cc7e0, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:499 +0xc65
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc00088b200?, {0xc0000cc7e0, 0x0, 0x1})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4c
github.com/spf13/cobra.(*Command).execute(0xc00088b200, {0xc0000cc630, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000005200)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45

**Comment by justinvp** [comment]
@lonegunmanb, can you share your Pulumi program? Or can you reproduce the same issue with one of the basic projects from `pulumi new`?

**Comment by lonegunmanb** [comment]
@justinvp Yes I can. My OS is Windows 10, and my pulumi version is v3.59.0.

The steps to reproduce this issue on my side:

1. git clone https://github.com/lonegunmanb/go-gin-example.git
2. cd to `pulumi` folder
3. `pulumi up --yes`
4. When you see ` +   pulumi:pulumi:Stack  pulumi-go-gin-sample-dev  create.`, press `Ctrl + c`

The panic stack was:

```text
panic: send on closed channel

goroutine 100 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.loadPlugin(0x2ac19a0?, 0xc00178c210)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:268 +0xbd
github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin.(*defaultHost).SignalCancellation(0xc000928000)
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/plugin/host.go:503 +0x65
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute.func1()
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:133 +0xea
created by github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:129 +0x154
```

**Comment by Ravemba** [comment]
@justinvp looks like no

**Comment by dixler** [comment]
This seems similar to https://github.com/pulumi/pulumi/issues/12543

**Comment by AaronFriel** [comment]
I found this and opened https://github.com/pulumi/pulumi/issues/13667, left comments there on a couple things we'd want to do to mitigate panics in the plugin loader.
