### ISSUE TITLE
cluster.kubeconfig.apply does not work with preview

### ISSUE THREAD

**Issue by unludo** [pulumi/pulumi#12372]
### What happened?

With such code:
const cluster = new eks.Cluster(...)

cluster.kubeconfig.apply(async (kubeConfig: string) => {
   // do something
}

when doing `pulumi up`, everything work fine, the cluster is created and the code in the apply section is correctly executed.

But when doing `pulumi preview`, the code in the apply section is not executed, even though the cluster is alive and kubeconfig exists.

### Expected Behavior

the code in apply should be executed during a `pulumi preview`, meaning that the preview should retrieve the kubeconfig.

### Steps to reproduce

indicated in 'what happened' 

### Output of `pulumi about`

CLI          
Version      3.55.0
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME        VERSION
auth0       2.14.0
aws         5.24.0
aws         5.16.2
awsx        1.0.1
datadog     4.12.0
docker      3.6.1
eks         1.0.1
kubernetes  3.23.1
nodejs      unknown
postgresql  3.6.0

Host     
OS       darwin
Version  13.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/.../.nvm/versions/node/v16.13.0/bin/node' version='v16.13.0'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by unludo** [comment]
hi @justinvp,

Thank you for your answer and trying to reproduce. What I have seen is that by doing a `pulumi config refresh` it works. The `pulumi up` was done on another machine. I guess the stack was missing some configuration to run the preview, I don't know which part yet though.

Just another question (don't hesitate to tell me if I should open another issue):

Should the log also appear if the preview is executed before any `pulumi up`, meaning the cluster does not exist yet?

**Comment by justinvp** [comment]
> Should the log also appear if the preview is executed before any `pulumi up`, meaning the cluster does not exist yet?

No, the log would not appear in this case since the value is unknown. When a value is unknown, the apply's callback is not run.
