### ISSUE TITLE
arm2pulumi cannot handle storage account 'tier' 

### ISSUE THREAD

**Issue by shablipapu** [pulumi/pulumi#12395]
### What happened?

Hi,

I'm trying to convert an arm template for an azure storage account to pulumi using arm2pulumi (linux ubuntu 64bit). however, i get the following error

`2023/03/06 15:46:48 Starting render
Error: unknown property 'tier' among [name]

  on program.pp line 311:
 312: 		tier = "Standard"

Error: unknown property 'tier' among [name]

  on program.pp line 311:
 312: 		tier = "Standard"

Error: cannot traverse value of type union(object({name = union(enum(azure-native:storage/v20220901:SkuName(string): cty.StringVal("Standard_LRS"),cty.StringVal("Standard_GRS"),cty.StringVal("Standard_RAGRS"),cty.StringVal("Standard_ZRS"),cty.StringVal("Premium_LRS"),cty.StringVal("Premium_ZRS"),cty.StringVal("Standard_GZRS"),cty.StringVal("Standard_RAGZRS")), output(enum(azure-native:storage/v20220901:SkuName(string): cty.StringVal("Standard_LRS"),cty.StringVal("Standard_GRS"),cty.StringVal("Standard_RAGRS"),cty.StringVal("Standard_ZRS"),cty.StringVal("Premium_LRS"),cty.StringVal("Premium_ZRS"),cty.StringVal("Standard_GZRS"),cty.StringVal("Standard_RAGZRS"))), output(string), output(union(enum(azure-native:storage/v20220901:SkuName(string): cty.StringVal("Standard_LRS"),cty.StringVal("Standard_GRS"),cty.StringVal("Standard_RAGRS"),cty.StringVal("Standard_ZRS"),cty.StringVal("Premium_LRS"),cty.StringVal("Premium_ZRS"),cty.StringVal("Standard_GZRS"),cty.StringVal("Standard_RAGZRS")), string)), string, annotated(0xc03a4709c0))}, annotated(0xc03a470600)), output(object({name = union(enum(azure-native:storage/v20220901:SkuName(string): cty.StringVal("Standard_LRS"),cty.StringVal("Standard_GRS"),cty.StringVal("Standard_RAGRS"),cty.StringVal("Standard_ZRS"),cty.StringVal("Premium_LRS"),cty.StringVal("Premium_ZRS"),cty.StringVal("Standard_GZRS"),cty.StringVal("Standard_RAGZRS")), string)}, annotated(0xc03a470a80))), annotated(0xc03a470b40))

  on program.pp line 311:
 312: 		tier = "Standard"

2023/03/06 15:46:57 IR generation: 385 ms, program gen 9141 ms`

the arm template is as follows:

`{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "storageAccounts_tu2tjvkutjz26sastate_name": {
      "type": "String"
    },
    "virtualNetworks_vnet_tu2tjvkutjz26_externalid": {
      "type": "String"
    }
  },
  "resources": [
    {
      "apiVersion": "2022-09-01",
      "kind": "StorageV2",
      "location": "westeurope",
      "name": "[parameters('storageAccounts_tu2tjvkutjz26sastate_name')]",
      "properties": {
        "accessTier": "Hot",
        "allowBlobPublicAccess": false,
        "encryption": {
          "keySource": "Microsoft.Storage",
          "requireInfrastructureEncryption": true,
          "services": {
            "blob": {
              "enabled": true,
              "keyType": "Account"
            },
            "file": {
              "enabled": true,
              "keyType": "Account"
            }
          }
        },
        "minimumTlsVersion": "TLS1_2",
        "networkAcls": {
          "bypass": "AzureServices",
          "defaultAction": "Deny",
          "ipRules": [
            {
              "action": "Allow",
              "value": "redacted-ip-address"
            }
          ],
          "resourceAccessRules": [],
          "virtualNetworkRules": [
            {
              "action": "Allow",
              "id": "[concat(parameters('virtualNetworks_vnet_tu2tjvkutjz26_externalid'), '/subnets/CoreSubnet')]",
              "state": "Succeeded"
            }
          ]
        },
        "publicNetworkAccess": "Enabled",
        "supportsHttpsTrafficOnly": true
      },
      "sku": {
        "name": "Standard_GRS",
        "tier": "Standard"
      },
      "tags": {
        "Purpose": "xxxx",
        "_0_WTWRegion": "xxxx",
        "_1_BusinessUnit": "xxxx",
        "_2_PointOfContact": "sdwd",
        "_3_BillingCode": "260",
        "_4_ApplicationCode": "NGIT",
        "_5_Environment": "Q",
        "client": "76e3921f-489b-4b7e-9547-xxxx",
        "client_application_id": "tu2tjvkutjz26",
        "env": "Q",
        "organization": "xxxx",
        "saexclude": "UC5",
        "service": "nimbuspoc01",
        "source": "azure",
        "terminationDate": "2023-03-08T08:09:39.8945983Z"
      },
      "type": "Microsoft.Storage/storageAccounts"
    },
    {
      "apiVersion": "2022-09-01",
      "dependsOn": [
        "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_tu2tjvkutjz26sastate_name'))]"
      ],
      "name": "[concat(parameters('storageAccounts_tu2tjvkutjz26sastate_name'), '/default')]",
      "properties": {
        "cors": {
          "corsRules": []
        },
        "deleteRetentionPolicy": {
          "allowPermanentDelete": false,
          "enabled": false
        }
      },
      "sku": {
        "name": "Standard_GRS",
        "tier": "Standard"
      },
      "type": "Microsoft.Storage/storageAccounts/blobServices"
    },
    {
      "apiVersion": "2022-09-01",
      "dependsOn": [
        "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_tu2tjvkutjz26sastate_name'))]"
      ],
      "name": "[concat(parameters('storageAccounts_tu2tjvkutjz26sastate_name'), '/default')]",
      "properties": {
        "cors": {
          "corsRules": []
        },
        "protocolSettings": {
          "smb": {}
        },
        "shareDeleteRetentionPolicy": {
          "days": 7,
          "enabled": true
        }
      },
      "sku": {
        "name": "Standard_GRS",
        "tier": "Standard"
      },
      "type": "Microsoft.Storage/storageAccounts/fileServices"
    },
    {
      "apiVersion": "2022-09-01",
      "dependsOn": [
        "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_tu2tjvkutjz26sastate_name'))]"
      ],
      "name": "[concat(parameters('storageAccounts_tu2tjvkutjz26sastate_name'), '/default')]",
      "properties": {
        "cors": {
          "corsRules": []
        }
      },
      "type": "Microsoft.Storage/storageAccounts/queueServices"
    },
    {
      "apiVersion": "2022-09-01",
      "dependsOn": [
        "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_tu2tjvkutjz26sastate_name'))]"
      ],
      "name": "[concat(parameters('storageAccounts_tu2tjvkutjz26sastate_name'), '/default')]",
      "properties": {
        "cors": {
          "corsRules": []
        }
      },
      "type": "Microsoft.Storage/storageAccounts/tableServices"
    },
    {
      "apiVersion": "2022-09-01",
      "dependsOn": [
        "[resourceId('Microsoft.Storage/storageAccounts/blobServices', parameters('storageAccounts_tu2tjvkutjz26sastate_name'), 'default')]",
        "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_tu2tjvkutjz26sastate_name'))]"
      ],
      "name": "[concat(parameters('storageAccounts_tu2tjvkutjz26sastate_name'), '/default/state')]",
      "properties": {
        "defaultEncryptionScope": "$account-encryption-key",
        "denyEncryptionScopeOverride": false,
        "immutableStorageWithVersioning": {
          "enabled": false
        },
        "publicAccess": "None"
      },
      "type": "Microsoft.Storage/storageAccounts/blobServices/containers"
    }
  ],
  "variables": {}
}
`

### Expected Behavior

the code works without error and creates c# code compatible with storage accounts

### Steps to reproduce

see above

### Output of `pulumi about`

see above

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Hi @shablipapu, thanks for opening the issue and sorry for the trouble. I was going to transfer this to the `arm2pulumi` repo, but see you also already opened https://github.com/pulumi/arm2pulumi/issues/30 there. I'm going to close this one as a duplicate. Someone will get back to you soon there -- we've been a bit behind on looking at incoming reported issues.

**Comment by shablipapu** [comment]
thank you!
