### ISSUE TITLE
Distinguish between provider operation failures and other errors

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#1240]
The former are failure results from whatever cloud backs the provider; the latter are gRPC failures, internal provider errors, etc. Put differently: the former are failures to update/create/etc. actual cloud resources; the latter are failures in the provider infrastructure itself. When encountering the former we can expect to reasonably understand the state of the resource. When encountering the latter we can not.

**Comment by lukehoban** [comment]
Why specifically do we need to do this? How will we ultimately handle these differently?

**Comment by leezen** [comment]
Closing out old issues
