### ISSUE TITLE
Functions without inputs do not have *Output variants

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#12449]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Functions that don't have any input arguments do not have `*Output` variants generated by SDK codegen.

For example, there is no `gcp.organizations.getClientConfigOutput` function: https://github.com/pulumi/pulumi-gcp/blob/master/sdk/nodejs/organizations/getClientConfig.ts

```
export function getClientConfig(opts?: pulumi.InvokeOptions): Promise<GetClientConfigResult>
export interface GetClientConfigResult
```

However, functions that do have input arguments, like `getFolder`, does have an `*Output` variant: https://github.com/pulumi/pulumi-gcp/blob/master/sdk/nodejs/organizations/getFolder.ts

```
export function getFolder(args: GetFolderArgs, opts?: pulumi.InvokeOptions): Promise<GetFolderResult>
export interface GetFolderArgs
export interface GetFolderResult
export function getFolderOutput(args: GetFolderOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetFolderResult>
export interface GetFolderOutputArgs
```

We should consistently emit `*Output` variants for all functions, even if they do not have any input args.

The reason that this is particularly important for `getClientConfig` is that this data source has a sensitive output - and if they could use the `Output` variant, we could automatically wrap that output in a secret - whereas the prompt variant just returns it as a string.

https://github.com/hashicorp/terraform-provider-google-beta/blob/4b17e5713da6bd2982087f686ec1a89b93b08474/google-beta/data_source_google_client_config.go#L31

**Comment by t0yv0** [comment]
@Zaid-Ajaj is this something I can pick up? Got a customer ask here.
