### ISSUE TITLE
Leaking GRPC connections in the Automations API

### ISSUE THREAD

**Issue by tokongs** [pulumi/pulumi#12463]
### What happened?

We have an application using the Automations API which is leaking gorotuines. I suspect that the leak originates [on this line in stack.go](https://github.com/pulumi/pulumi/blob/1b2470db221167ec4e998e226b1c5338e1f26c7b/sdk/go/auto/stack.go#LL1162). As  far as  I can see that `pulumi.Context` is never closed which will leave its GRPC connections open. It may be I am missing context here, but stepping through with a debugger seems to support my hypothesis. Our application never hits `pulumi.(*Context).Close()`

### Expected Behavior

The exepceted behaviour is for the `pulumi.Context` to be closed so that it's GRPC connections are closed. 

### Steps to reproduce

1. Create a `LocalWorkspace` and `InlineStack` with the Automations API.
2. Run `Up` on the stack with the automations API.
3. Repeat, and look at the number of goroutines after each run
4. Altenatively step through with a debugger and see that `Close` is not called on the context

### Output of `pulumi about`

CLI
Version      3.46.1
Go Version   go1.19.3
Go Compiler  gc

Host
OS       arch
Version  22.0.4
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Nice! Thanks very much for doing this investigative work, tokongs! And welcome to the Pulumi Community! (I see this is your first time opening an issue in this repo!) Very glad to have you!

**Comment by RobbieMcKinstry** [comment]
I was able to reproduce a goroutine leak :)

**Comment by RobbieMcKinstry** [comment]
🎉 🎉 🎉  I've confirmed locally that closing the context does indeed fix the leak!
Thanks very much for your sleuthing! I'll open a PR and include the program I used for leak detection.

**Comment by RobbieMcKinstry** [comment]
Thanks for doing most of the work! :D

**Comment by RobbieMcKinstry** [comment]
This fix was included in yesterday's release, so you should not observe a memory leak in in v3.59.0.
