### ISSUE TITLE
Resulting Output from resource method does not track dependencies properly 

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#12471]
### What happened?

When an output is returned via a MLC method, resource dependencies are not properly respected resulting in incorrect behavior, such as resources being destroyed (deleted) in the wrong order.

### Expected Behavior

An output from a MLC method should track dependent resources. The dependent resources should be destroyed prior to their "parent".

### Steps to reproduce

1. Have an MLC which creates a k8s cluster and also includes a method that returns an output of the cluster's kubeconfig
2. Use the kubeconfig to seed a k8sprovider
3. Using the k8sprovider, create arbitrary k8s resources.
4. Destroy the resources after a successful `pulumi up`.

Note, destroy order is incorrect. Pulumi will attempt to destroy the cluster and k8s resources in parallel where there should be a direct dependency.

Cluster -> kubeconfig output from method -> k8s provider -> k8s resources.

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
There are actually two issues here:

1. When rehydrating a component resource, we treat the rehydrated instance as a local component, which means it isn't kept as a dependency during dependency expansion. We should be treating rehydrated components the same way we treat remote components, such that they are kept as a dependency. That way, the implementation of a component resource method that uses outputs of the component will have the dependency on the component passed along through to the result of the method.

2. The result of a resource method should always depend on the resource, just as all resource outputs depend on the resource.

**Comment by justinvp** [comment]
The original customer issue was addressed with https://github.com/pulumi/pulumi/pull/12494. Closing this and tracking the remaining related issues with:
- https://github.com/pulumi/pulumi/issues/13308
- https://github.com/pulumi/pulumi/issues/13309
