### ISSUE TITLE
Pulumi reports bad exit code when using pulumi login in directory whose parent directory does not grant permission

### ISSUE THREAD

**Issue by farvour** [pulumi/pulumi#12481]
### What happened?

Pulumi returns an exit code (255) when running `pulumi login` but the *parent directory of the current working directory doesn't grant read permission*.

```argocd@argo-cd-argocd-repo-server-55d7cdfb97-xtkp7:/tmp/_argocd-repo/52c01366-05dc-4758-9681-a63572526b17/infra$ pulumi login
error: failed to locate Pulumi.yaml project file: open /tmp/_argocd-repo/52c01366-05dc-4758-9681-a63572526b17/infra: permission denied
```

### Expected Behavior

I expected Pulumi to set the login to `--local` to the requested path, regardless of the root directory or basedir of the current working directory (which has permission).

### Steps to reproduce

```
mkdir -p /tmp/parent/child1/child2
cd /tmp/parent/child1/child2
chmod 300 /tmp/parent  # Removes read permission from the parent directory to prevent iterating parent directory.
pulumi login --local
```

### Output of `pulumi about`

```
/tmp/parent/child1/child2
❯ pulumi about
CLI
Version      3.59.0
Go Version   go1.20.2
Go Compiler  gc

Host
OS       darwin
Version  12.6.3
Arch     arm64

Backend
Name           <redacted>
URL            file://~
User           <redacted>
Organizations

Pulumi locates its logs in /var/folders/rk/xr_1cn1d4z9_56pfppyfy0y40000gn/T/ by default
warning: Failed to read project: failed to locate Pulumi.yaml project file: open /tmp/parent: permission denied
warning: Failed to get information about the current stack: failed to locate Pulumi.yaml project file: open /tmp/parent: permission denied

/tmp/parent/child1/child2
❯ pulumi login
error: failed to locate Pulumi.yaml project file: open /tmp/parent: permission denied
```

### Additional context

I feel it is irrelevant for Pulumi to care about trying to iterate the root directory, or any directory for that matter, for the pulumi login operation as it is reported as a warning for pulumi about anyway....

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Hi @farvour. I can see where you're coming from. I'm not completely sure why `pulumi login --local` would need access to `Pulumi.yaml`. I'll dig around in the code to see if there's a reason.

**Comment by RobbieMcKinstry** [comment]
Glad you have a workaround! :D 

Looking at the code, it appears `pulumi login` opens the project purely for technical/architecture reasons. The code path for `pulumi login` creates a new instance of the Filestate backend. The Filestate backend tries to follow RAII, so it requires a `Project` instance as a parameter. It looks like the authors didn't want create a `Filestate` object in an incomplete state, which is a reasonable assumption at the time of writing, but unfortunately, with hindsight, it causes trouble here and presumably elsewhere.

**Comment by RobbieMcKinstry** [comment]
So it sounds like we could implement this fix, but it would require either...

1. a refactor of `filestate.NewBackend()`, allowing a partial creation of the `filestate`. Requires refactoring of virtually every filestate method to guard against partial initialization.
2. use a separate type for `login`

**Comment by Frassle** [comment]
> Sounds complex for either, potentially. This feels very edge-case like, but at the same time, it's a real issue since commands should not fail if the permission of a directory it doesn't have access to doesn't affect the usability of the tool.

Spoke to @RobbieMcKinstry internally, but just to get the message out here as well. This was an inadvertent behavior change while doing some refactoring of how we pass project state around internally. The old code was trying to lookup if there was a contextual project but just ignoring _any_ error that happened. The new code was written to only ignore NoProjectFound errors, so these read permission errors started to cause a failure.

It should be a trivial change to make `login` just ignore any errors during project loading again (although I've pointed out to Robbie that we should at least send the error hit to the debug log rather than completely ignoring it like before).

**Comment by Frassle** [comment]
> However, I'm thinking of scenarios where a user's Pulumi code may be on some shared file-system and the root of that mount doesn't allow read/iterating but just directory (+x mode) and they'd get bit by this as well.

It might make sense for us to actually catch this case of hitting an unreadable parent and translate that error into a ProjectNotFound error as well. Would cover any other cases where we're we want to try and lookup the project but can carry on without one. A bit more of an involved change than just ignoring the error in `login`.
