### ISSUE TITLE
Integrity failure when k8s cluster / provider is replaced

### ISSUE THREAD

**Issue by sebbegg** [pulumi/pulumi#12482]
### What happened?

In our pulumi project we're managing a kubernetes cluster using the azure-native provider, along with some "basic" k8s resources on it.
So the project uses azure-native and the kubernetes provider.

We seem to be unable to properly handle cases where changes the cluster result in a replacement, such as changing the name (though that's not real-world use-case).
Instead it appears that there is some confusion with existing resource and the provider going on, so that we end up with something like this:

![image](https://user-images.githubusercontent.com/6164994/227201111-68530799-84f7-4fc4-a463-e1891cacb354.png)

The state then needs "manual" repairing be deleting all k8s resources e.g. via `pulumi state delete --disable-integrity-checking`.
I assume this is not a kubernetes/azure-native specific issue, so I ended up here...

### Expected Behavior

Ideally, pulumi would delete existing k8s resources (considering them deleted along with the cluster might be an "optimization"), replace the cluster and then re-deploy the k8s resources.

### Steps to reproduce

I managed to reproduce this with the following minimal example below, by:

* run `pulumi up`
* change e.g. the cluster's `resource_name_`
* run `pulumi up` again

```python
"""A Python Pulumi program"""

import base64

import pulumi
import pulumi_kubernetes.core.v1 as k8s_core
from pulumi_azure_native.containerservice import v20220802preview as cs
from pulumi_kubernetes import Provider

cluster = cs.ManagedCluster(
    "cluster",
    resource_name_="mytestcluster2",
    kubernetes_version="1.25.5",
    location="westeurope",
    resource_group_name="xyz",
    dns_prefix="xyz",
    agent_pool_profiles=[
        cs.ManagedClusterAgentPoolProfileArgs(
            count=3,
            enable_auto_scaling=False,
            enable_encryption_at_host=False,
            enable_fips=False,
            enable_node_public_ip=False,
            kubelet_disk_type="OS",
            mode="System",
            name="default",
            os_disk_size_gb=128,
            os_disk_type="Managed",
            os_sku="Ubuntu",
            os_type="Linux",
            type="VirtualMachineScaleSets",
            vm_size="Standard_D2_v2",
        )
    ],
    enable_rbac=True,
    identity=cs.ManagedClusterIdentityArgs(
        type=cs.ResourceIdentityType.SYSTEM_ASSIGNED,
    ),
    disable_local_accounts=False,
    sku=cs.ManagedClusterSKUArgs(
        name=cs.ManagedClusterSKUName.BASIC,
        tier=cs.ManagedClusterSKUTier.FREE,
    ),
    service_principal_profile=cs.ManagedClusterServicePrincipalProfileArgs(
        client_id="msi",
    ),
    network_profile=cs.ContainerServiceNetworkProfileArgs(
        load_balancer_sku=cs.LoadBalancerSku.STANDARD,
        network_plugin=cs.NetworkPlugin.KUBENET,
        network_policy=cs.NetworkPolicy.CALICO,
    ),
    opts=pulumi.ResourceOptions(delete_before_replace=True),
)


def _get_kube_config(cluster: cs.ManagedCluster) -> pulumi.Output:
    def get_cluster_creds(cluster_id: str):
        split = cluster_id.split("/")
        return cs.list_managed_cluster_user_credentials(
            resource_group_name=split[4],
            resource_name=split[-1],
        )

    kube_creds = cluster.id.apply(get_cluster_creds)
    kube_config = kube_creds.kubeconfigs[0].value.apply(
        lambda enc: base64.b64decode(enc).decode()
    )
    return pulumi.Output.secret(kube_config)


k8s_provider = Provider(
    resource_name="k8s-provider",
    kubeconfig=_get_kube_config(cluster),
    cluster=cluster.name,
)

configmap = k8s_core.ConfigMap("my-k8s-resource", opts=pulumi.ResourceOptions(provider=k8s_provider))
```

### Output of `pulumi about`

❯ pulumi about
CLI
Version      3.55.0
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.97.0
kubernetes    3.24.2
python        unknown

Host
OS       darwin
Version  13.2.1
Arch     x86_64

This project is written in python: executable='/Users/me/.pyenv/shims/python3' version='3.10.3
'

Backend
Name           my-desktop
URL            azblob://xyz
User           me
Organizations

Dependencies:
NAME                 VERSION
pip                  23.0.1
pulumi-azure-native  1.97.0
pulumi-kubernetes    3.24.2
setuptools           67.6.0
wheel                0.40.0

Pulumi locates its logs in /var/folders/9r/s7hj72y57dxdjgz8rm0jd9wx734y24/T/ by default
warning: Failed to get information about the current stack: .pulumi/stacks/pulumi-k8s-test.json: snapshot integrity failure; refusing to use it: resource urn:pulumi:pulumi-k8s-test::pulumi-k8s-test::kubernetes:core/v1:ConfigMap::my-k8s-resource refers to unknown provider urn:pulumi:pulumi-k8s-test::pulumi-k8s-test::pulumi:providers:kubernetes::k8s-provider::cf59b3d4-21bd-4c0d-80a9-dd3cc1753fb8

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lunaris** [comment]
Hey @sebbegg. I'm assuming based on the age of this issue without a response that it's been resolved/you were able to unblock yourself? We try to keep a close eye on integrity issues and are always fixing them so hopefully with e.g. the latest CLI you won't be falling foul of one any more? Please feel free to reopen if this is not the case 🙏
