### ISSUE TITLE
Unicode characters in resource property description

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#12508]
### Problem description

There seem to be some unicode characters that are not being rendered correctly in some resource property descriptions.

From https://www.pulumi.com/docs/reference/pkg/azure-nextgen/compute/virtualmachine/#datadisk:

![image](https://user-images.githubusercontent.com/293763/102517097-7b913600-4044-11eb-83bb-95f492e9e78e.png)

**Comment by justinvp** [comment]
<img width="712" alt="Screen Shot 2023-07-26 at 11 47 51 PM" src="https://github.com/pulumi/pulumi/assets/710598/7f12b5d6-28e0-4511-9e2b-fd18e597b61e">

This appears to be fixed.
