### ISSUE TITLE
Unexpected replaces

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1251]
The changes in https://github.com/pulumi/pulumi/pull/1207 will cause anyone using the latest CLI with an old (pre 0.12) @pulumi/aws (or probably all other TF based providers), to see significant spurious diffs and replacements.  Effectively, all the problems seen in https://github.com/pulumi/pulumi/issues/1147.

Not clear what we can/should do about this for 0.12.  @joeduffy @mmdriley

**Comment by lukehoban** [comment]
@pgavlin Can this be closed now?

**Comment by pgavlin** [comment]
Yes.
