### ISSUE TITLE
String literal value with multiple `*` characters not rendering properly

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi#12510]
File: [themes/default/content/registry/packages/google-native/api-docs/cloudkms/v1/keyring/_index.md](https://www.pulumi.com/registry/packages/google-native/api-docs/cloudkms/v1/keyring/)

The [name property](https://www.pulumi.com/registry/packages/google-native/api-docs/cloudkms/v1/keyring/#name_go) includes a string literal that contains several `*` characters. It appears that the markdown renderer is incorrectly interpreting these as formatting directives rather than part of the string literal.

![Screen Shot 2022-03-16 at 7 20 38 AM](https://user-images.githubusercontent.com/9253463/158599053-01a91797-8451-45dc-9ee2-4a83abf4e658.png)

The full value should instead be `projects/*/locations/*/keyRings/*`

**Comment by abhinav** [comment]
<img width="648" alt="image" src="https://github.com/pulumi/pulumi/assets/41730/cfd9be7b-592a-4fa0-93e3-7b49aee43a78">

Looks like this is resolved?
@lblackstone is this good to close?
