### ISSUE TITLE
AccessDenied error from s3 backend after upgrading to v3.59.0

### ISSUE THREAD

**Issue by adam-kiss-sg** [pulumi/pulumi#12534]
### What happened?

After upgrading to v3.59.0, any pulumi command would return the following error:
```
error: write ".pulumi/Pulumi.yaml": blob (key ".pulumi/Pulumi.yaml") (code=Unknown): AccessDenied: Access Denied
        status code: 403, request id: ***, host id: ***
```

### Expected Behavior

The commands to work.

### Steps to reproduce

We use a single s3 bucket for all of our pulumi backend state. We have dev and prod environment (each of our projects has a "dev" and a "prod" stack) sharing this bucket, and use bucket permissions to control writes to the pulumi state:
```
        {
            "Sid": "WriteDev",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::****:root"
            },
            "Action": [
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::pulumi-state/*/.pulumi/*/dev/*",
                "arn:aws:s3:::pulumi-state/*/.pulumi/*/dev.*"
            ]
        },
        {
            "Sid": "WriteProd",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::****:root"
            },
            "Action": [
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::pulumi-state/*/.pulumi/*/prod/*",
                "arn:aws:s3:::pulumi-state/*/.pulumi/*/prod.*"
            ]
        },
```

**After updating to v3.59.0, the following change resulted in an access denied error:**
- https://github.com/pulumi/pulumi/commit/e47c5823c0274769094ac970e8f31108c6a6bd85

### Output of `pulumi about`

CLI          
Version      3.59.0

rest is not relevant (cause is clear)

### Additional context

- Would it be possible to avoid sharing files between stacks? So a user with access to dev environment can not modify anything related to prod environment?
- Could you include something in the changelog about this change?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by abhinav** [comment]
@adam-kiss-sg, FYI, we've agreed upon a change that will help here:
We won't write the metadata file for existing stacks that don't use the new layout.
So if you'd rather not do the manual workaround, the next release will likely resolve this issue for you.

**Comment by adam-kiss-sg** [comment]
@abhinav thank you. Until then, we can stay on v3.58.0 .
