### ISSUE TITLE
Deprecated parameters cause warnings to be shown to the user whether or not the parameter is in use from Python programs

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#12546]
### What happened?

Marking MLC inputs (parameters) as deprecated causes the warnings to be shown to the user whether or not the parameters are actually in use.

### Expected Behavior

Deprecation warnings should only be shown to users when the user is actually utilizing one of the deprecated parameters.

### Steps to reproduce

Mark an optional MLC input (parameter) as deprecated, perform an update without setting the optional, deprecated parameter.

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by RobbieMcKinstry** [comment]
Nice find! Thanks Phil!

**Comment by justinvp** [comment]
@phillipedwards, when getting the warnings, what language is being used?

**Comment by phillipedwards** [comment]
@justinvp Assuming you mean the user program, it was python.

**Comment by justinvp** [comment]
@dixler and I were chatting about this earlier and he was wondering if the parameter is being set to a default value.

Indeed, if the parameter has a default value and hasn't been set, it is set to the default value. Then, if the parameter is deprecated and has been set, a deprecation warning is emitted.

https://github.com/pulumi/pulumi/blob/2f3e1657eb37b6c0980765a4e0055e5655b35c0d/pkg/codegen/python/gen.go#L1321-L1343

The fix would be to check if the value has been set and emit the deprecation warning _before_ setting the default value.

@phillipedwards, do you know if the deprecated parameter has a default value? I'm guessing that's what's going on.

**Comment by phillipedwards** [comment]
I'm not 100% sure but I bet there is a default value. I will confirm.

**Comment by phillipedwards** [comment]
@dixler @justinvp confirmed, the property in question does have a default value, so this makes sense with your thinking.

**Comment by phillipedwards** [comment]
Reopening this issue as it's regressed. Below screenshot is from `pulumi/pulumi@3.75.0` python program
<img width="1040" alt="image" src="https://github.com/pulumi/pulumi/assets/25461821/01e3ac93-8b26-4343-8c09-cbf5b1f90823">

**Comment by aaron-tillekeratne** [comment]
As @Frassle has linked the issue, this is still appearing in CLI version 3.95.
