### ISSUE TITLE
Mocked input to a multi-language component not being passed through to component

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#12553]
### What happened?

I'm using the AWS API Gateway MLC: https://www.pulumi.com/registry/packages/aws-apigateway/

and have the following code: as my Pulumi project:

```typescript
export const api = new apigateway.RestAPI("api", {
    routes: [{
        path: "/",
        localPath: "www"
    }],
    stageName: "test"
});
```

I want to check that the `stageName` input is correct.

In my mocks I've got:

```typescript
case "aws-apigateway:index:RestAPI":
                return {
                    id: "1234",
                    state: args.inputs
                }
```

and then my test looks like this:

```typescript
describe("Infrastructure", function () {
    let infra: typeof import("./index");

    before(async function () {
        // It's important to import the program _after_ the mocks are defined.
        infra = await import("./index");
    })

    describe("apigateway", function() {
        it("must have a stage called test", function(done) {
            infra.api.stage.stageName.apply(s => {
                if(s !== "test") {
                    done(new Error(`Stage name must be set to test. It's currently set to: ${s}`))
                } else {
                    done()
                }
            });
        })
    })
});
```

The test is failing (returning an error) with the error message: `Stage name must be set to test. It's currently set to: undefined`.

### Expected Behavior

I would expect that the test would pass

### Steps to reproduce

GitHub repo: https://github.com/pierskarsenbarg/mlc-unit-tests 

### Output of `pulumi about`

```bash
CLI          
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.2.1
Arch     x86_64

Current Stack: pierskarsenbarg/mlc-unit-tests/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/pierskarsenbarg
User           pierskarsenbarg
Organizations  pierskarsenbarg, karsenbarg, team-ce, demo

Pulumi locates its logs in /var/folders/69/3w1gr05s2pq36wn49bhyknym0000gn/T/ by default

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
The problem is the component takes a top-level `stageName` input, but the output is the result of the component creating an `aws.apigateway.Stage` resource and outputting it as `stage`, and that resource having a `stageName`.

If you want to simulate what the component is doing, you'll have to change your mock to do this:

```typescript
case "aws-apigateway:index:RestAPI":
    return {
        id: "1234",
        state: {
            stage: {
                stageName: args.inputs.stageName,
            }
        },
    }
```

**Comment by pierskarsenbarg** [comment]
I knew it was something like that for outputs. Let me check with the user and then I'll close the ticket

**Comment by RobbieMcKinstry** [comment]
Triaged this as a question because it sounds like we found a fix, but happy to retriage as bug if @pierskarsenbarg comes back from the user with bad news! :)

**Comment by pierskarsenbarg** [comment]
Closing as tested the above and it works. Thanks folks
