### ISSUE TITLE
Could not find parent goal after update

### ISSUE THREAD

**Issue by michal-bajer1** [pulumi/pulumi#12562]
### What happened?

After updating to 3.60.0 my C# azure-native stack stopped working.
It seems the issue is a situation, where I load resource into the stack using `Get `method and then attempt to use this resource as parent to a new resource.

`error: could not find parent goal urn:pulumi:production::ConnectivityHub::azure-native:network:VirtualNetwork::mews-devops-vnet-weu (originally urn:pulumi:production::ConnectivityHub::azure-native:network:VirtualNetwork::mews-de
vops-vnet-weu)
`

### Expected Behavior

Allow the referenced resource to be used as parent.

### Steps to reproduce

Example pseudocode: 
```
var resourceGroup = ResourceGroup.Get("external-resource-group", externalResourceGroupId);
new VirtualNetwork(name, new VirtualNetworkArgs()
        {
            VirtualNetworkName = name,
            AddressSpace = new AddressSpaceArgs
            {
                AddressPrefixes = new []
                {
                    addressPrefix
                }
            },
            Location = location.Id,
            ResourceGroupName = resourceGroup.Name,
        }, new CustomResourceOptions()
        {
            Parent = resourceGroup,
            DependsOn = resourceGroup
        });
```

### Output of `pulumi about`

CLI
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.38.0
azure-native  1.98.1
docker        3.6.1
dotnet        unknown
newrelic      5.8.0

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.202'

Current Stack: mews/Networking/dev.neu

TYPE                                      URN
pulumi:pulumi:Stack                       urn:pulumi:dev.neu::Networking::pulumi:pulumi:Stack::Networking-dev.neu
pulumi:providers:pulumi                   urn:pulumi:dev.neu::Networking::pulumi:providers:pulumi::default
pulumi:pulumi:StackReference              urn:pulumi:dev.neu::Networking::pulumi:pulumi:StackReference::mews/Networking/dev.weu
pulumi:providers:azure-native             urn:pulumi:dev.neu::Networking::pulumi:providers:azure-native::default_1_97_0
azure-native:resources:ResourceGroup      urn:pulumi:dev.neu::Networking::azure-native:resources:ResourceGroup::mews-develop-networking
azure-native:network:VirtualNetwork       urn:pulumi:dev.neu::Networking::azure-native:resources:ResourceGroup$azure-native:network:VirtualNetwork::mews-develop-spoke-neu

Found no pending operations associated with mews/dev.neu

Backend
Name           pulumi.com
URL            https://app.pulumi.com/michal-bajer1
User           michal-bajer1
Organizations  michal-bajer1, mews

Dependencies:
NAME    VERSION
Pulumi  3.54.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jforest** [comment]
I also ran into this.  Was running `3.58.0` and upgraded to `3.60.0` yesterday and started getting a very similar error.

```
Diagnostics:
  kubernetes:core/v1:PersistentVolume (jenkins-pv):
    error: could not find parent goal urn:pulumi:global::REDACTED/Services$REDACTED:k8s/Cluster$aws:ebs/volume:Volume::jenkins-ebs-volume (originally urn:pulumi:global::REDACTED/Services$REDACTED:k8s/Cluster$aws:ebs/volume:Volume::jenkins-ebs-volume)
```

**Comment by dixler** [comment]
Apologies. We recently shipped a feature to delegate parent-child inheritance logic of Resource Options to the engine for the `deletedWith` flag. I've opened a PR reverting the offending PR and it should be merged and released. In the meantime, you can work around this by using the prior CLI version (v3.59.1).
