### ISSUE TITLE
pulumi up target can cause providers in ComponentResources to become unparented

### ISSUE THREAD

**Issue by jon-king-mindbodyonline** [pulumi/pulumi#12621]
### What happened?

([context](https://pulumi.slack.com/archives/CKJ4C845D/p1678135981871219))

Running `pulumi up --target "<existing-urn>" --yes --skip-preview` on an existing stack that has had changes in code that would otherwise (without the `target`) create a new ComponentResource containing a Provider, causes the Provider to be created. This then throws `post-step event returned an error: failed to verify snapshot: child resource <urn:of::provider> refers to missing parent <urn:of::componentresource>`

Trying to then run `pulumi up` doesn't fix it: you get `pre-step event returned an error: failed to verify snapshot`. This leaves the parent-less Provider in the stack, so any further updates are blocked. You have to `stack export`, remove the provider, and `import`

### Expected Behavior

We'd expect that the `target` doesn't create resources that aren't being targeted.

### Steps to reproduce

`pulumi new` -> `aws-typescript`. All the defaults.
`pulumi config set aws:profile myprofile`
`pulumi config set aws:region us-west-2`
`pulumi config set other:profile otherprofile`
`pulumi config set other:region us-west-2`

Create a new file `component.ts` with:
```ts
import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';

export class OtherAccountBucket extends pulumi.ComponentResource {
    public readonly bucket: aws.s3.Bucket;
    constructor(opts: {}, componentOpts?: pulumi.ComponentResourceOptions) { 
        super('test:otheraccount:bucket', 'otheraccountbucket', {}, componentOpts);

        const otherAccount = new pulumi.Config('other');
        const otherAccountProvider = new aws.Provider(
            'other-account-provider',
            {
                profile: otherAccount.get('profile'),
                region: otherAccount.get('region') as pulumi.Input<aws.Region>
            },
            { 
                parent: this
            }
        );

        this.bucket = new aws.s3.Bucket(
            `testbucket`,
            { 
                bucket: `s3-testbucket`,
                acl: 'private'
            },
            {
                parent: this,
                provider: otherAccountProvider
            }
        );
    }
}
```
And modify `index.ts` to:
```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import { OtherAccountBucket } from "./component";

// Create an AWS resource (S3 Bucket)
const bucket = new aws.s3.Bucket("my-bucket");
// const otherBucket = new OtherAccountBucket("other-bucket");

// Export the name of the bucket
export const bucketName = bucket.id;
```

`pulumi up` stands up the first S3 `my-bucket` as intended. Get the bucket urn, uncomment the `otherBucket`, and run:

`pulumi up --target "urn:pulumi:dev::ProviderTest::aws:s3/bucket:Bucket::my-bucket" --yes --skip-preview`

Will generate the error:
```
Diagnostics:
  pulumi:providers:aws (other-account-provider):
    error: post-step event returned an error: failed to verify snapshot: child resource urn:pulumi:dev::ProviderTest::test:otheraccount:bucket$pulumi:providers:aws::other-account-provider refers to missing parent urn:pulumi:dev::ProviderTest::test:otheraccount:bucket::otheraccountbucket

  pulumi:pulumi:Stack (ProviderTest-dev):
    error: resource complete event returned an error: failed to verify snapshot: child resource urn:pulumi:dev::ProviderTest::test:otheraccount:bucket$pulumi:providers:aws::other-account-provider refers to missing parent urn:pulumi:dev::ProviderTest::test:otheraccount:bucket::otheraccountbucket
    error: update failed
```

### Output of `pulumi about`

CLI          
Version      3.61.1
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.35.0
awsx    1.0.2
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  12.6.3
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v19.7.0'

TYPE                  URN
pulumi:pulumi:Stack   urn:pulumi:dev::ProviderTest::pulumi:pulumi:Stack::ProviderTest-dev
pulumi:providers:aws  urn:pulumi:dev::ProviderTest::pulumi:providers:aws::default_5_35_0
aws:s3/bucket:Bucket  urn:pulumi:dev::ProviderTest::aws:s3/bucket:Bucket::my-bucket
pulumi:providers:aws  urn:pulumi:dev::ProviderTest::test:otheraccount:bucket$pulumi:providers:aws::other-account-provider

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME            VERSION
@pulumi/aws     5.35.0
@pulumi/awsx    1.0.2
@pulumi/pulumi  3.61.1
@types/node     16.18.23

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
This sounds pretty gnarly. Thanks for filing this. I'm going to take a look.

**Comment by dixler** [comment]
Thanks to your excellent reproduction notes, I was able to reproduce the issue. :slightly_smiling_face: 

I believe you basically described it with your workaround of unparenting the provider (which you accurately describe difficulty with) in the slack link, but to restate the root cause:

(currently) Pulumi creates providers even if they aren't targeted.

https://github.com/pulumi/pulumi/blame/1cf6a89608ebdb9b6f46b2401fa641e7a33a9dd1/pkg/resource/deploy/step_generator.go#L852

When the update is run with `--target` the provider will be created, but the provider's parent will not be created (because of target) so the provider `parent: this` flag being set.

Here's an even more minimal repro:
```typescript
import * as random from "@pulumi/random";

// Create an AWS resource (S3 Bucket)
const bunny = new random.RandomPet("bunny");

// Comment out the next line to toggle the code.
/*
const badBunny = new random.RandomPet("bad-bunny");
new random.Provider("wew", {}, {
    parent: badBunny,
})
//*/

// Export the name of the bucket
export const bunnyName = bunny.id;
```

Now I just need to think of the cleanest fix to handle this.
