### ISSUE TITLE
Convert Pulumi.Output<string> from aws.ssm.getParameterOutput to Pulumi.Input<number>

### ISSUE THREAD

**Issue by gencube** [pulumi/pulumi#12631]
## Hello!

The need to use AWS SSM Store Parameter returend value to create a k8s.apps.v1.Deployment with spec, replicas in number type.

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
        // need to store Store Parameter with value of replicas.
	const replicas = aws.ssm.getParameterOutput({ name: name }).apply((res) => res.value);
        // returns only Puluimi.Output<string>;

		const deployment = new k8s.apps.v1.Deployment(resourceName, {
			metadata: {
				name: name,
				namespace: namespace,
				labels: labels
			},
			spec: {
				replicas: replicas,  // needs to use Pulumi.Input<number>;
                         }

const replicasNum = aws.ssm.getParameterOutputAsNumber({ name: name }).apply((res) => res.value);

### Affected area/feature

Kubernetes deployment of packages,

**Comment by justinvp** [comment]
Hi @gencube, if you need to convert the string to a number, you can use [`parseInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt) inside the `apply`:

```typescript
const replicas = aws.ssm.getParameterOutput({ name: name }).apply((res) => parseInt(res.value, 10));
```
