### ISSUE TITLE
config values failing to decrypt

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#12632]
### What happened?

In pulumi/pulumi 3.57.0 or greater, there is a case where stack configuration values are failing to decrypt when a value is a secret. View the automation api code `main.go`.

### Expected Behavior

Stack configuration values, secret or not, should never fail to decrypt.

### Steps to reproduce

1. clone https://github.com/phillipedwards/go-auto-stack-decryption
2. ensure all `pulumi/pulumi` versions are 3.57.0 or greater (go.mods and docker-repro.sh)
3. execute `./docker-repro.sh` 

### Output of `pulumi about`

pulumi/pulumi 3.57.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Seems to be due to https://github.com/pulumi/pulumi/commit/e6e7b5e75eb29331e7b49da3420634aace4d29e4. If I revert that commit, then I no longer get the failure.

**Comment by Frassle** [comment]
Turns out this is nothing to do with automation api really. It's just `pulumi config set-all` isn't saving the encryption information correctly on first use.
