### ISSUE TITLE
Aliases that use fields other than URN (like Name, Type, etc.) are not working for child resources in Go

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi#12662]
### What happened?

The PodDisruptionBudget was changed from v1beta1 to v1 as part of support for EKS v1.25, which removes the v1beta1 API.
This is creating issues during an update, because the PDB is aliased by default by Pulumi (https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/go/kubernetes/policy/v1/podDisruptionBudget.go#L41). This lead to a situation where, because of the alias, stacks ended up in a state where it wanted to delete a resource that was already gone and an update thus failing.

- [v1beta1/poddisruptionbudget/](https://www.pulumi.com/registry/packages/kubernetes/api-docs/policy/v1beta1/poddisruptionbudget/)
- [v1/poddisruptionbudget/](https://www.pulumi.com/registry/packages/kubernetes/api-docs/policy/v1/poddisruptionbudget)

### Expected Behavior

pulumi-kubernetes automatically aliases different resource versions. If this worked as expected, the resource would have been updated to v1/PodDisruptionBudget in the state, with no change to the resource on the cluster.

### Steps to reproduce

1. Stand up an eks cluster in python (so that it is a MLC).
2. Create a v1beta1 poddisruptionbudget on eks 1.24
3. upgrade to eks to 1.25 and run `pulumi up`

### Output of `pulumi about`

pending.

### Additional context

1. Kubernetes v1.25 removes the v1beta1/PodDisruptionBudget resource, necessitating an update in the CSI driver component resource

1. pulumi-kubernetes automatically aliases different resource versions, but a MLC bug prevented the alias from working correctly. If this worked as expected, the resource would have been updated to v1/PodDisruptionBudget in the state, with no change to the resource on the cluster. Instead, pulumi wanted to replace the resource.

1. To work around the replacement, the PDB was changed from a statically-named resource to an auto-named resource in code. These resources were also aliased, and the deleteBeforeReplace resource option was set. The alias is incorrect, because these are different resources on the cluster due to the different .metadata.name.

1. Due to the options set in 3., pulumi tries to delete-before-replace the PDB. The delete succeeds, but the replacement seems to be stuck in a retry loop where it keeps creating new auto-named PDBs. I think this is because of the invalid alias in 3.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Some more notes on this:

- The alias is set on a k8s resource inside of a MLC component
- It wasn't working with the default alias set in the k8s provider SDK, so the alias was applied as a workaround
- Using `pulumi/sdk/v3` `v3.61.0` and CLI `v3.60.1`

Here's a snippet:

```go
_, err = policyv1.NewPodDisruptionBudget(ctx, "controller", &policyv1.PodDisruptionBudgetArgs{
    ApiVersion: pulumi.String("policy/v1"),
    Kind:       pulumi.String("PodDisruptionBudget"),
    Metadata: &metav1.ObjectMetaArgs{
        Labels: pulumi.StringMap{
            "app.kubernetes.io/component": pulumi.String("csi-driver"),
            "app.kubernetes.io/instance":  pulumi.String("release-name"),
            "app.kubernetes.io/name":      pulumi.String("aws-ebs-csi-driver"),
        },
        Namespace: pulumi.String("kube-system"),
    },
    Spec: &policyv1.PodDisruptionBudgetSpecArgs{
        MaxUnavailable: pulumi.Any(1),
        Selector: &metav1.LabelSelectorArgs{
            MatchLabels: pulumi.StringMap{
                "app":                        pulumi.String("ebs-csi-controller"),
                "app.kubernetes.io/instance": pulumi.String("release-name"),
                "app.kubernetes.io/name":     pulumi.String("aws-ebs-csi-driver"),
            },
        },
    },
}, pulumi.Aliases([]pulumi.Alias{
    {
        Name: pulumi.String("example"), // <-- This isn't working
    },
}),
  kubernetesProviderOption, // The "provider" option
  childOption, // The "parent" option
)
```

**Comment by justinvp** [comment]
This issue isn't specific to MLCs. I was able to reproduce the issue with a local component in go.

```go
package main

import (
	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := NewMyComponent(ctx, "component")
		return err
	})
}

type MyComponent struct {
	pulumi.ResourceState
}

func NewMyComponent(ctx *pulumi.Context, name string, opts ...pulumi.ResourceOption) (*MyComponent, error) {
	myComponent := &MyComponent{}
	err := ctx.RegisterComponentResource("pkg:index:MyComponent", name, myComponent, opts...)
	if err != nil {
		return nil, err
	}

	randomName := "old"
	randomOpts := []pulumi.ResourceOption{pulumi.Parent(myComponent)}

	// Uncomment these lines after the first update.
	// randomName = "new"
	// randomOpts = append(randomOpts, pulumi.Aliases([]pulumi.Alias{
	// 	{
	// 		Name: pulumi.String("old"),
	// 	},
	// }))

	_, err = random.NewRandomString(ctx, randomName, &random.RandomStringArgs{
		Length: pulumi.Int(16),
	}, randomOpts...)
	if err != nil {
		return nil, err
	}

	return myComponent, nil
}
```

Run an initial `pulumi up` with the above. Then comment out the lines and run `pulumi up` again.

You'll see:

```
$ pulumi up
Previewing update (dev)

     Type                             Name                  Plan
     pulumi:pulumi:Stack              gocomponentalias-dev
     └─ pkg:index:MyComponent         component
 +      ├─ random:index:RandomString  new                   create
 -      └─ random:index:RandomString  old                   delete


Resources:
    + 1 to create
    - 1 to delete
    2 changes. 2 unchanged
```

When there should be no changes.

Alias calculation now happens in the engine and this appears to be a bug in the engine.

The computed alias URN is:

```
urn:pulumi:dev::gocomponentalias::random:index/randomString:RandomString::old
```

But the actual old URN is:

```
urn:pulumi:dev::gocomponentalias::pkg:index:MyComponent$random:index/randomString:RandomString::old
```

The alias URN is missing `pkg:index:MyComponent$`

**Comment by justinvp** [comment]
Doesn't even need to be a component. Any resource with a parent has the problem:

```go
package main

import (
	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		parent, err := random.NewRandomString(ctx, "parent", &random.RandomStringArgs{
			Length: pulumi.Int(16),
		})
		if err != nil {
			return err
		}

		randomName := "old"
		randomOpts := []pulumi.ResourceOption{pulumi.Parent(parent)}

		// Uncomment these lines after the first update.
		// randomName = "new"
		// randomOpts = append(randomOpts, pulumi.Aliases([]pulumi.Alias{
		// 	{
		// 		Name: pulumi.String("old"),
		// 	},
		// }))

		_, err = random.NewRandomString(ctx, randomName, &random.RandomStringArgs{
			Length: pulumi.Int(16),
		}, randomOpts...)
		if err != nil {
			return err
		}

		return nil
	})
}
```

**Comment by justinvp** [comment]
Interestingly, Node.js doesn't repro:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as random from "@pulumi/random";

const parent = new random.RandomString("parent", { length: 10 });

let name = "old";
const opts: pulumi.ResourceOptions = { parent };

// Uncomment these lines after the first update.
// name = "new";
// opts.aliases = [{ name: "old" }];

const child = new random.RandomString(name, { length: 10 }, opts);
```

After uncommenting the lines for the second update, RegisterResource receives the following alias spec for the last resource:

```
Alias:         &pulumirpc.Alias_Spec_{
    Spec: &pulumirpc.Alias_Spec{
        state:         impl.MessageState{},
        sizeCache:     0,
        unknownFields: nil,
        Name:          "old",
        Type:          "",
        Stack:         "",
        Project:       "",
        Parent:        &pulumirpc.Alias_Spec_ParentUrn{ParentUrn:"urn:pulumi:dev::tsaliasbug::random:index/randomString:RandomString::parent"},
    },
},
```

Whereas for an equivalent Go program, it receives:

```
Alias:         &pulumirpc.Alias_Spec_{
    Spec: &pulumirpc.Alias_Spec{
        state:         impl.MessageState{},
        sizeCache:     0,
        unknownFields: nil,
        Name:          "old",
        Type:          "",
        Stack:         "",
        Project:       "",
        Parent:        &pulumirpc.Alias_Spec_NoParent{},
    },
},
```

In the Node.js SDK, if the alias doesn't have a `parent` specified, it fills-in the resource's current parent:

https://github.com/pulumi/pulumi/blob/a207c2d27e4f160bcf933351b02a5d32dd6b9c9c/sdk/nodejs/runtime/resource.ts#L293-L320

Specifically:

https://github.com/pulumi/pulumi/blob/a207c2d27e4f160bcf933351b02a5d32dd6b9c9c/sdk/nodejs/runtime/resource.ts#L312

The Go SDK, on the other hand doesn't do this. If `parent` isn't specified, it doesn't fill it in. The other non-Node.js SDKs may be doing the same thing.

The way the Node.js and engine handles `parent` on the alias doesn't make sense to me. My expectation is that if parent isn't set in the SDK, it shouldn't be set in the alias spec sent to the engine, just like all the other alias fields like `name`, `type`, etc. But given the current behavior of the engine, we may need to make the other SDKs match the behavior of the Node.js SDK.

**Comment by kpitzen** [comment]
> The way the Node.js and engine handles parent on the alias doesn't make sense to me. My expectation is that if parent isn't set in the SDK, it shouldn't be set in the alias spec sent to the engine, just like all the other alias fields like name, type, etc. But given the current behavior of the engine, we may need to make the other SDKs match the behavior of the Node.js SDK.

I think the idea is that children should be aliased alongside their parents as the derived URN will change if the parent type changes, which would cause unexpected resource replacements down the inheritance chain. Allowing for an explicit `parent`-driven alias means that we can re-parent resources without replacing them, so there's slightly different behavior for the two use cases.

**Comment by Frassle** [comment]
The NodeJS SDK looks buggy here. If the alias doesn't set a parent URN then it should be blank. That's why the engine has the block:
```
                if parentURN == "" { 
 			parentURN = goal.Parent 
 		} 
```

**Comment by kpitzen** [comment]
I was just looking at the same thing here. I'm surprised all of the aliasing integration tests are passing given different implementations across language SDKs

**Comment by Frassle** [comment]
Ohhh
The go alias struct is losing information present in the protobuf struct :( 

In the protobuf we can tell the difference between "NoParent" being explicitly set and just both fields being left blank, but in source_eval when we go from protobuf to go struct we throw away the explicit NoParent info and just base it on if ParentUrn is blank.

Sad that none of the alias engine tests checked this.

**Comment by Frassle** [comment]
> Sad that none of the alias engine tests checked this.

Looks like some of the tests that should of been testing aliasSpecs were still written in terms of aliasUrns, so that's why testing missed this. e.g. https://github.com/pulumi/pulumi/blob/master/pkg/engine/lifecycletest/pulumi_test.go#L1562

**Comment by justinvp** [comment]
I don't understand (yet) how https://github.com/pulumi/pulumi/tree/master/tests/integration/aliases/go/retype_parents is passing locally while my similar repro is failing. I see that in `step2` we're not actually changing the types, but when I fix the test to change the types of the resources, it still passes.

**Comment by justinvp** [comment]
OK, I understand what's going on with https://github.com/pulumi/pulumi/tree/master/tests/integration/aliases/go/rename_component_and_child and why it doesn't fail.

In the second step, both the parent and the child are renamed:

https://github.com/pulumi/pulumi/blob/c97ae5fdc11deb6fd82402acd098b41910c28e0b/tests/integration/aliases/go/rename_component_and_child/step2/main.go#L50-L52

https://github.com/pulumi/pulumi/blob/c97ae5fdc11deb6fd82402acd098b41910c28e0b/tests/integration/aliases/go/rename_component_and_child/step2/main.go#L36-L41

Here's the engine's computed aliases for the child:

```
"urn:pulumi:dev::goparentchild::my:module:FooComponent43$my:module:FooResource::otherchild",
"urn:pulumi:dev::goparentchild::my:module:FooComponent43$my:module:FooResource::otherchildrenamed",
```

If we don't rename the parent, here's the computed alias for the child (still works):

```
"urn:pulumi:dev::goparentchild::my:module:FooComponent43$my:module:FooResource::otherchild",
```

Note that the child is including a `Parent` alias, which shouldn't be necessary for these renames:

https://github.com/pulumi/pulumi/blob/c97ae5fdc11deb6fd82402acd098b41910c28e0b/tests/integration/aliases/go/rename_component_and_child/step2/main.go#L38

If we now also remove the child's `Parent` alias, we get the following alias for the child (broken):

```
"urn:pulumi:dev::goparentchild::my:module:FooResource::otherchild",
```

If we start over from scratch, and this time keep the parent rename, but remove the `Parent` alias on the child, we get the following aliases for the child (works):

```
"urn:pulumi:dev::goparentchild::my:module:FooComponent43$my:module:FooResource::otherchild",
"urn:pulumi:dev::goparentchild::my:module:FooComponent43$my:module:FooResource::otherchildrenamed",
"urn:pulumi:dev::goparentchild::my:module:FooResource::otherchild",
```

Two takeaways:
1. If the parent has aliases, the child will have correct aliases due to inheriting the parent's aliases
2. When aliasing a child, you can specify `Parent` to workaround the engine bug
