### ISSUE TITLE
Pulumi FSharp does not respect lambda environment variable settings when deploying lambda function in AWS

### ISSUE THREAD

**Issue by he-shen** [pulumi/pulumi#12673]
let env = ["Key", "Value" |> input] |> inputMap
    args.Environment <- FunctionEnvironmentArgs(Variables = env)

When deploying the lambda function with above setting, no environment variable is added to the deployed function at all.

**Comment by Frassle** [comment]
Is this with aws or aws-native?

**Comment by he-shen** [comment]
This is AWS

**Comment by Frassle** [comment]
Can you run `pulumi preview --diff --show-sames` and reply here with what that shows for the "environment" setting on the function object?

Testing this quickly here my test lambda function _does_ get environment settings applied.

**Comment by he-shen** [comment]
pulumi preview --diff --show-sames gives the following output:

~~~~~~~
      aws:lambda/function:Function: (same)
        [id=dev-edi-function-as2-inbox-handler]
        [urn=urn:pulumi:dev::edi::aws:lambda/function:Function::dev-edi-function-as2-inbox-handler]
        [provider=urn:pulumi:dev::edi::pulumi:providers:aws::default_5_33_0::e9e94cd0-2698-404f-8467-1af4dff10530]
        environment                 : {
        }
        handler                     : "As2InboxHandler::As2InboxHandler.Function::FunctionHandler"
        memorySize                  : 1024
        name                        : "dev-edi-function-as2-inbox-handler"
        packageType                 : "Zip"
        publish                     : false
        reservedConcurrentExecutions: -1
        role                        : "arn:aws:iam::066515142977:role/dev-edi-function-as2-inbox-handler-execution-role"
        runtime                     : "dotnet6"
        s3Bucket                    : "dev-edi-lambda-artifact-066515142977"
        s3Key                       : "As2InboxHandler.zip"
        s3ObjectVersion             : "VlCFGjgnREJ2qb4hNx_JgNYADIe030Yj"
        skipDestroy                 : false
        timeout                     : 30
~~~~~~~~~~

**Comment by he-shen** [comment]
By the way, I found if I change the code from:

let env = ["Key", "Value" |> input] |> inputMap
args.Environment <- FunctionEnvironmentArgs(Variables = env)

TO:

let env = ["Key", "Value" |> input] |> inputMap
args.Environment <- FunctionEnvironmentArgs(Variables = env) **|> input**

Then it will work. If I remove **|> input**, pulumi will actually delete the environment variables from deployment.

It seems that the problem is that the implicit type conversion operator had to be called explicitly to make it working.

However, with or without "|> input" the dotnet build succeeds with no warnings nor errors. I only discovered this by accident, since there is no clue from the dotnet compiler to let me know that the environment variable settings are getting ignored.

**Comment by Frassle** [comment]
That feels like it might be an F# compiler bug, I'll have a look if we can get a repro to send to them.

**Comment by Frassle** [comment]
Ah yeh we've seen this before! https://github.com/dotnet/fsharp/issues/12946

You need to use net7.0, or add calls to the conversion operations explicitly.
