### ISSUE TITLE
Node v10 tracking

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1270]
Node v10 will become Active LTS starting October 2018, so we should probably support it at some point.

Issues I ran into while poking around last night:

1. The version of `grpc-node` we currently use (1.6) is too old to be used with Node v10. I upgraded to `grpc-node` version 1.8 and it compiled.
2. 5 `@pulumi/pulumi` tests fail, in this manner:

```

  1) closure Test getter/setter #1:

      AssertionError [ERR_ASSERTION]: 'exports.handler = __f0;\n\nvar __f1_prototype = {};\nObject.defineProperty(__f1_prototype, "constructor", { configurable: tr... == 'exports.handler = __f0;\n\nvar __f1_prototype = {};\nObject.defineProperty(__f1_prototype, "constructor", { configurable: tr...
      + expected - actual

       function __f2() {
         return (function() {
           with({  }) {

      -return function () {
      +return function /*foo*/() {
                       return this._x;
                   };

           }
       function __f3() {
         return (function() {
           with({  }) {

      -return function (v) {
      +return function /*foo*/(v) {
                       this._x = v;
                   };

           }
```

```
  4) closure Capture all if getter and getter uses this.:

      AssertionError [ERR_ASSERTION]: 'exports.handler = __f0;\n\nvar __o = {};\nObject.defineProperty(__o, "b", { configurable: true, enumerable: true, get: __f1 ... == 'exports.handler = __f0;\n\nvar __o = {};\nObject.defineProperty(__o, "b", { configurable: true, enumerable: true, get: __f1 ...
      + expected - actual

       function __f1() {
         return (function() {
           with({  }) {

      -return function () { return this; };
      +return function /*b*/() { return this; };

           }
         }).apply(undefined, undefined).apply(this, arguments);
       }

      at Object.<anonymous> (bin/tests/runtime/closure.spec.js:3654:24)
      at Generator.next (<anonymous>)
      at fulfilled (bin/tests/runtime/closure.spec.js:5:58)
```

Not sure what these mean. @CyrusNajmabadi any thoughts?

All integration tests pass so there do not appear to be any major regressions or problems with Node v10.

**Comment by CyrusNajmabadi** [comment]
@swgillespie Slightly concerning: https://github.com/v8/v8/blob/master/src/runtime/runtime.h

runtime.h no longer has a definition for FunctionGetScript.  GetFunctionScopeDetails and GetFunctionScopeCount are also gone.  Trying to figure out when this happened, and what we might be able to do about it.

**Comment by CyrusNajmabadi** [comment]
Looks like it was removed in this PR: https://github.com/v8/v8/commit/e404670696b4c49d7f8adcdb075b98acab9967dd#diff-76a3ff46cd3f448a693d106f8e1b7dc4

I have reached out to the author to see if they can help guide us through suitable replacements.

**Comment by lukehoban** [comment]
@CyrusNajmabadi @swgillespie Is this fixed with https://github.com/pulumi/pulumi/pull/1658?

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi/pull/1658
