### ISSUE TITLE
Slightly confusing output for `pulumi plugin rm --all --yes`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#12719]
### What happened?

Deleting all plugins with the `--yes` flag prints this message:

```
𝛌 pulumi plugin rm -ay                    
This will remove 7 plugins from the cache:
    resource cloudflare-5.0.0
    resource gcp-5.0.0
    resource github-4.10.0
    resource kubernetes-3.17.0
    resource random-4.8.2
    resource tls-4.0.0
    resource tls-4.10.0
```

### Expected Behavior

It's not true that `This will remove 7 plugins from the cache`. The plugins have been removed. We should change the message to `7 plugins have been removed from the cache:`.

### Steps to reproduce

Run `pulumi plugin rm --all --yes` (equivalent to `pulumi plugin rm -ay`).

### Output of `pulumi about`

Version is `3.64.1-dev.0`. The rest is not relevant.

### Additional context

I suspect the problem is we intend to run a "Are you sure" dialog before deleting, but the `--yes` flag prevents that. This means the description is not quite right though.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by riteshsonawane1372** [comment]
Kindly check the PR @iwahbe
