### ISSUE TITLE
Consider making it easier to import resources into a Program/Component via `pulumi import`

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#12768]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Today, it is nearly impossible to import existing resources into a component resources without jumping through unreasonable hoops.. You need:
- an empty shell of a component that is pre-existing per https://github.com/pulumi/pulumi/issues/9146
- all type tokens and various combinations of id or name
- iterate over `pulumi import` with parent set or build a bulk import json file

The experience is poor. If a user has already written the code that represents their component, Pulumi should already know the layout of the component resource's graph/tree, so why should users be forced to recreate it by hand?

I'm guessing `pulumi import` does not currently execute the user program in any fashion, but could be wrong. With that said, I'd like to see the following workflow be available, for importing resources into a component resource or any program.

1. Write the Pulumi program (code) to your specifications.
2. Execute `pulumi import componentURN --interactive` or some flag which states this session should be interactive.
3. The user gets prompted to provide the id/name for each resource in the stack without having to deal with type tokens or order of resources; meaning parent/child relationships and dependencies are respected.
4. I have a fully imported program or component.

**Comment by Frassle** [comment]
Internal discussion the agreed approach for this is to run the users program to find all resources that need creating and outputting an import file filed in for those resource with all the names/urns filled in and just needing ID fields to be filled in by the user. They could then run import again with that file once all the IDs have been filled in.
