### ISSUE TITLE
Running project yields failure with no error message

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#12812]
### What happened?

Running the project https://github.com/brandonbloom/pulumi-workspaces-repro/tree/master/packages/cloud

Errors with no message
```
kdixler@kdixler-20xw004aus ..pulumi-workspaces-repro/packages/cloud (git)-[master] % pulumi pre
Previewing update (repro2661)

View in Browser (Ctrl+O): https://app.pulumi.com/dixler/myapp/repro2661/previews/87808a9f-1183-4e04-b921-29701ebd7b32




Resources:

255 kdixler@kdixler-20xw004aus ..pulumi-workspaces-repro/packages/cloud (git)-[master] %   
```

### Expected Behavior

An actionable error message

### Steps to reproduce

Upgrade pulumi to a recent version (to make it relevant).

`yarn install`
`pulumi pre`

### Output of `pulumi about`

recent dev build

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Potentially interesting details:

```
"@pulumi/pulumi@npm:3.65.1":
  resolution: "@pulumi/pulumi@npm:3.65.1"
    "@pulumi/query": ^0.3.0
"@pulumi/query@npm:^0.3.0":
  resolution: "@pulumi/query@npm:0.3.0"
    "@pulumi/pulumi": 3.65.1
```

**Comment by julienp** [comment]
I believe this was fixed in https://github.com/pulumi/pulumi/pull/15426
