### ISSUE TITLE
error: this should already have a plan from when we called register resources

### ISSUE THREAD

**Issue by dan0dbfe** [pulumi/pulumi#12824]
### What happened?

After upgrading to `3.66.0`, I got an error `error: this should already have a plan from when we called register resources` when previewing update through `pulumi up`.

Downgrading to `3.65.1` let me run without errors.

### Expected Behavior

No error

### Steps to reproduce

1. Upgrade to `3.66.0`
2. Run `pulumi up`
3. Get `error: this should already have a plan from when we called register resources` when previewing update
4. Downgrade to `3.65.1`
5. Run `pulumi up` with no errors

### Output of `pulumi about`

CLI          
Version      3.66.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by sewhyte** [comment]
I encountered this error while running a --target-replace on a single URN. I then tried a destroy/up --target on the same URN and it succeeded with no errors.

**Comment by Frassle** [comment]
@dan0dbfe per-chance is this project using [awsx](https://github.com/pulumi/pulumi-awsx)?

**Comment by dan0dbfe** [comment]
Sorry for the incomplete repro steps - I was indeed using a specific `--target`. I am using GCP Classic.

**Comment by Frassle** [comment]
> I was indeed using a specific --target

Ah thanks. We were guessing either you had used --target and not mentioned it or were using awsx, so good to know which of those it was.

This will definitely be due to the changes in target from https://github.com/pulumi/pulumi/pull/12628, I'd suggest we want to try and fix this rather than just reverting as that PR itself fixed another P1 issue.

**Comment by solomonshorser** [comment]
I'm also experiencing this problem. How do I downgrade to 3.65.1 using brew?
