### ISSUE TITLE
How to update pulumi stack

### ISSUE THREAD

**Issue by KhushKia** [pulumi/pulumi#12822]
I have deleted resources mistakenly in azure portal, not sure how to update the pulumi stack about the deleted resources. Once stack knows about deleted resources, i can do a pulumi up to recreate them back. I tried, pulumi refresh in my local..it failed. 

Note: i am using pulumi code in CI\Cd pipeline.

**Comment by justinvp** [comment]
One option is to manually remove the deleted resources from Pulumi's state. Then the next `pulumi up` will recreate them.

There are a couple ways to do that:

1. You could run `pulumi stack --show-urns` to get a listing of the resources in the stack's state, and then use `pulumi state delete "<urn>"` to remove it from the state. See https://www.pulumi.com/docs/intro/concepts/state/#editing-state-manually

2. Another option is to export the state via `pulumi stack export > stack.json`, then modify `stack.json` to delete the resource that was deleted outside of Pulumi, then run `pulumi stack import < stack.json`. See https://www.pulumi.com/docs/intro/concepts/state/#exporting-and-importing-state
