### ISSUE TITLE
Secrets Masking Masks "superset"

### ISSUE THREAD

**Issue by pquerna** [pulumi/pulumi#12853]
### What happened?

[Apache Superset](https://superset.apache.org/) is a tool for visualizing data / business intelligence / dashboarding. 

When outputting an AWS IAM Role with the word `superset` in it, Pulumi is masking this string, eg the CLI shows:
```
 "role/ext-[secret]-iam-role-a-20230509180102262000000001"
```

Where `[secret]` is `superset`.  The Pulumi.com console correctly shows it without the `[secret]` (eg not masked)

### Expected Behavior

Don't mask the word `superset`

### Steps to reproduce

Make a resource with the name `superset`

### Output of `pulumi about`

CLI          
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Host     
OS       debian
Version  11.5
Arch     x86_64

### Additional context

Even if this word matches some list, ideally it would be documented what the CLI tries to Mask.  I couldn't find specific documentation about this behavior, eg its not described on https://www.pulumi.com/docs/reference/cli/  -- so documenting the "rules" of Masking could be helpful.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hi, thanks for filing this. I'm having some difficulty reproducing this. Could you provide a minimal reproduction of your program that triggers this behavior and whether you're using the AWS Classic or AWS Native provider as well as its version? It would help me reproduce this issue on my machine :pray:

**Comment by mikhailshilkov** [comment]
I couldn't reproduce this either. Since we haven't heard back, I'll close the issue as non-actionable.
