### ISSUE TITLE
Use `RunError` less broadly

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1291]
The `pulumi.RunError` error type causes `pulumi` to suppress call stack information in error reporting.  Though useful, this can hide useful call stack details when `RunError`s are returned from APIs which get composed into other abstractions or layers.

We have liberally used `RunError` in places where we were validating user input - but that is likely not providing the best user debugging experience.

**Comment by CyrusNajmabadi** [comment]
Relevant conversation on this topic: https://github.com/pulumi/pulumi/commit/11f1e444f410b5011fe3438a60de4fa7353f2de0#r28768304
