### ISSUE TITLE
Preserve stack outputs when an error occurs

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#12929]
### What happened?

Consider a stack that has been deployed at least once and that has at least one stack output. If that stack is updated and an error occurs (ie, `ResourceError`), the resources are preserved ✅ but all stack outputs are removed ❌.

This is especially problematic since stack outputs are often used as stack references, but also as pat of custom workflows (ie, shell scripts). This can create some knock-off effects downstream that are preventing proper execution.

### Expected Behavior

Like resources, stack outputs should be preserved in case of a stack update failure if the stack had outputs already present.

### Steps to reproduce

1. Create a new Pulumi app
2. Deploy the code below
3. Note the 2 stack outputs (They show in the Pulumi console as well as the stack state, 2 resources are also registered)
4. Uncomment the exception
5. Deploy the updated code
6. An exception occurs, the stack outputs are both gone, the 2 resources are preserved (Pulumi console and state)

```ts
import * as pulumi from "@pulumi/pulumi";
import * as random from "@pulumi/random";

export const top = "top";

new random.RandomPet("😸");

// throw new pulumi.ResourceError("💥", undefined);

new random.RandomPet("🐰");

export const bottom = "bottom";
```

### Output of `pulumi about`

```
CLI          
Version      3.64.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown
random  4.13.0

Host     
OS       debian
Version  11.6
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.16.0'

Current Stack: menfin/aws-ts-self-ref/dev

TYPE                              URN
pulumi:pulumi:Stack               urn:pulumi:dev::aws-ts-self-ref::pulumi:pulumi:Stack::aws-ts-self-ref-dev
pulumi:providers:random           urn:pulumi:dev::aws-ts-self-ref::pulumi:providers:random::default_4_13_0
random:index/randomPet:RandomPet  urn:pulumi:dev::aws-ts-self-ref::random:index/randomPet:RandomPet::🐰
random:index/randomPet:RandomPet  urn:pulumi:dev::aws-ts-self-ref::random:index/randomPet:RandomPet::😸


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo, pulumi

Dependencies:
NAME            VERSION
@pulumi/random  4.13.0
@types/node     16.18.29
@pulumi/pulumi  3.67.0

Pulumi locates its logs in /tmp by default
```

### Additional context

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
This was fixed in https://github.com/pulumi/pulumi/pull/15754 which shipped in v3.112.0.
