### ISSUE TITLE
Preview with `--target` appears to be planning to create non-targetted resources, throws error

### ISSUE THREAD

**Issue by jon-king-mindbodyonline** [pulumi/pulumi#12926]
### What happened?

Running `pulumi up --target "<existing-urn>"` on an existing stack that has had changes in code that would otherwise (without the target) create a new ComponentResource containing a Provider and new Resource. During `preview` and the first stage of `up`, it appears to be planning on creating the new Resource, and throws the error `resource should already have a plan from when we called register resources`

### Expected Behavior

We'd expect that the `target` doesn't try to create resources that aren't being targeted.

### Steps to reproduce

`pulumi new` -> `aws-typescript`. All the defaults.
`pulumi config set aws:profile myprofile`
`pulumi config set aws:region us-west-2`
`pulumi config set other:profile otherprofile`
`pulumi config set other:region us-west-2`

Create a `component.ts` with: 

```ts
import * as pulumi from '@pulumi/pulumi';
import * as aws from '@pulumi/aws';

export class OtherAccountBucket extends pulumi.ComponentResource {
    public readonly bucket: aws.s3.Bucket;
    constructor(opts: {}, componentOpts?: pulumi.ComponentResourceOptions) { 
        super('test:otheraccount:bucket', 'otheraccountbucket', {}, componentOpts);

        const otherAccount = new pulumi.Config('other');
        const otherAccountProvider = new aws.Provider(
            'other-account-provider',
            {
                profile: otherAccount.get('profile'),
                region: otherAccount.get('region') as pulumi.Input<aws.Region>
            },
            { 
                parent: this
            }
        );

        this.bucket = new aws.s3.Bucket(
            `testbucket`,
            { 
                bucket: `s3-testbucket`,
                acl: 'private'
            },
            {
                parent: this,
                provider: otherAccountProvider
            }
        );
    }
}
```

And modify `index.ts` to:
```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import { OtherAccountBucket } from "./component";

// Create an AWS resource (S3 Bucket)
const bucket = new aws.s3.Bucket("my-bucket");
// const otherBucket = new OtherAccountBucket("other-bucket");

// Export the name of the bucket
export const bucketName = bucket.id;
```

`pulumi up` stands up the first S3 `my-bucket` as intended. Get the urn, uncomment `otherBucket`, and run:
`pulumi up --target "urn:pulumi:dev::ProviderTest::aws:s3/bucket:Bucket::my-bucket"`

Will generate the error:
```
Diagnostics:
  test:otheraccount:bucket (otheraccountbucket):
    error: resource should already have a plan from when we called register resources [urn=urn:pulumi:dev::ProviderTest::test:otheraccount:bucket::otheraccountbucket]
```

### Output of `pulumi about`

```CLI          
Version      3.67.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.35.0
awsx    1.0.2
docker  3.6.1
nodejs  unknown
random  4.13.0

Host     
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v19.7.0'

Dependencies:
NAME            VERSION
@pulumi/aws     5.35.0
@pulumi/awsx    1.0.2
@pulumi/pulumi  3.67.0
@pulumi/random  4.13.0
@types/node     16.18.23
```

### Additional context

3.66 fixed a bug with this same setup where the Provider was being created in an unparented state #12621 
This introduced #12824 which appears to have applied to all `--targets`, was fixed in 3.67.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jon-king-mindbodyonline** [comment]
The Provider doesn't appear to be relevant, and I was incorrect - it's the ComponentResource that's trying to be created, not the Resource (S3 in my example) within it. Simpler repro:

`component.ts` with:
```ts
import * as pulumi from '@pulumi/pulumi';
import * as random from "@pulumi/random";

export class BunnyHolder extends pulumi.ComponentResource {
    public readonly pet: random.RandomPet;
    constructor(opts: {}, componentOpts?: pulumi.ComponentResourceOptions) { 
        super('test:components:bunnyholder', 'bunnyholder', {}, componentOpts);
        this.pet = new random.RandomPet("bad-bunny", {}, {
            parent: this
        })
    }
}
```

And `index.ts` as 
```ts
import * as random from "@pulumi/random";
import {BunnyHolder} from "./component";

// Create an AWS resource (S3 Bucket)
const bunny = new random.RandomPet("bunny");

// Comment out the next line to toggle the code.
/*
const badBunny = new BunnyHolder("bad-bunny");

//*/

// Export the name of the bucket
export const bunnyName = bunny.id;
```

Pulumi up, then uncomment and `pulumi up --target "[...]index/randomPet:RandomPet::bunny"`, throws

```
Diagnostics:
  test:components:bunnyholder (bunnyholder):
    error: resource should already have a plan from when we called register resources [urn=urn:pulumi:dev::test::test:components:bunnyholder::bunnyholder]
```

**Comment by dixler** [comment]
Hey. @jon-king-mindbodyonline sorry that you're running into this. Thank you for the repro. Taking a look.

**Comment by dixler** [comment]
@jon-king-mindbodyonline this is a workaround that should allow you to run an update without worrying about plans. 

If you use `--skip-preview`, it will avoid the plan generation in preview causing the update to fail.

let me know if that helps unblock you.
