### ISSUE TITLE
[Node SDK] Decouple DevDependency TypeScript from Library TypeScript

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi#12936]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In conversation with @dixler, I realized we should try to decouple the version of TypeScript we use in development from the version we ship as a library.

**Context:** We write the Node SDK in TypeScript, which we compile to JavaScript and ship as an NPM package. The version of TypeScript we use to compile this package could be any version, without affecting user code. When that package is executed, we load TypeScript as a library, as does TS-Node. This is the runtime version of TypeScript, and this version determines the set of permissible user programs.

In theory, those two versions should be totally separable. We should be able to run `yarn dlx tsc@4.0.0` in dev anywhere we currently run `tsc` without impacting `node_modules` and introducing a version conflict. One impact of this is that we could port our own code to TypeScript 5 completely independently of the work in https://github.com/pulumi/pulumi/issues/12687

### Affected area/feature

Node SDK

**Comment by julienp** [comment]
What's tricky here is that we might accidentally introduce exported types that can't be used in ts3.8.3.
