### ISSUE TITLE
Pulumi GCP w GCP Bucket Statefile Hangs on any operation

### ISSUE THREAD

**Issue by sanderlegit** [pulumi/pulumi#12943]
### What happened?

**Backgound**
I have a Pulumi stack written in Go which manages a GCP environment and provisions some Okta Apps using the gcp-classic and Okta providers. I am using a statefile on a GCP bucket.
The code has worked well for a long time and is used to provision a collection of GCP projects with a selection of services utilizing cloud runs, secrets, bigquery, services accounts and other resources.
Recently after a short hiatus, most operations are failing to complete, forcing me to cancel the run, and provisioning new resources via pulumi up fails constantly.

**Issue**
When running pulumi refresh everything runs normally until the final printout, then pulumi hangs.
When running pulumi up, preview works as usual but once the changes are accepted each resource takes upwards of 1000s to run and rarely actually finish provisioning 'creating...' > 'created'. 
In some cases the resources do finish provisioning, but again after the final expected printout pulumi hangs and fails to update the statefile.
I have run pulumi at max log output and seen that this task is repeated often:
```
I0515 12:23:06.079621   79677 log.go:75] error copying .pulumi/stacks/stateofthings.json.gz to
.pulumi/stacks/stateofthings.json.gz.bak: blob (key ".pulumi/stacks/stateofthings.json.gz -> 
.pulumi/stacks/stateofthings.json.gz.bak") (code=NotFound): googleapi: Error 404: No such object: state-of-deployment/.pulumi/stacks/stateofthings.json.gz, notFound
```
I have tried running with `PULUMI_SKIP_CHECKPOINTS` to avoiding hanging on statefile updates.
Also running from other networks, through VPNs.
The codebase is rather complex and dynamic but has not changed since before the issue appeared and runs without errors.

### Expected Behavior

I expected pulumi to provision new resources as they were added at a similar speed that it has previously.

### Steps to reproduce

Since the stack and codebase are complicated I am unsure how to share the issue specifically. Please advise what information would be helpful to diagnose the problem.

### Output of `pulumi about`

```
CLI
Version      3.66.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME  VERSION
gcp   6.36.0
go    unknown
okta  3.23.0

Host
OS       darwin
Version  12.2.1
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.18.4 darwin/arm64'

Current Stack: stateofthings

TYPE                                                               URN
**892 RESOURCES OMMITTED**


OPP TYPE  URN
creating  urn:pulumi:stateofthings::deploy::gcp:secretmanager/secret:Secret


Backend
Name           enge
URL            gs://state-of-deployment
User           dries
Organizations

Dependencies:
NAME                                  VERSION
cloud.google.com/go/artifactregistry  1.13.0
github.com/go-errors/errors           1.4.2
github.com/pkg/errors                 0.9.1
github.com/pulumi/pulumi-gcp/sdk/v6   6.36.0
github.com/pulumi/pulumi/sdk/v3       3.40.0
google.golang.org/api                 0.119.0
google.golang.org/genproto            0.0.0-20230410155749-daa745c078e1
golang.org/x/oauth2                   0.7.0
github.com/pulumi/pulumi-okta/sdk/v3  3.23.0
```

### Additional context

Apologies if this is the wrong place for something like this since I cannot prove it is directly a bug in Pulumi, and not my implementation.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by abhinav** [comment]
Hey @sanderlegit, thanks for the report.

I believe that that error message is not the root cause. The backend unconditionally calls `backupTarget` on both, the plain text and the .gz versions of the state, and that operation fails and logs in case of the .gz file because those are not written by default:

https://github.com/pulumi/pulumi/blob/5037e3a2d75a538ee115cacc2d7a624c312ed45f/pkg/backend/filestate/state.go#L217-L218
https://github.com/pulumi/pulumi/blob/5037e3a2d75a538ee115cacc2d7a624c312ed45f/pkg/backend/filestate/state.go#L314-L320

It's unclear as of yet whether the issue is with the Pulumi engine or with the GCP provider.
One tool that can help here is setting `PULUMI_DEBUG_GRPC`.

    PULUMI_DEBUG_GRPC=$(pwd)/trace.json pulumi up

This will write a copy of all messages passed between the engine and the various plugins to get an idea of where time is being spent. (Note that the resulting file may contain sensitive information so treat it as secret.)

**Comment by sanderlegit** [comment]
Thanks for the tip, I'll try to get some more specifics from those logs.

I had some runs complete successfully today albeit with >4000s creation times for resources that I have previously seen created in <60s. 

I will try to generate some performance reports and use that flag to identify the bottlenecks / failing requests. 
I do suspect it's simply a performance issue with the GCP provider. 

Maybe worthwhile opening the issue there.

**Comment by justinvp** [comment]
Closing this old issue since we haven't reproduced the issue. Please open a new issue if you're still seeing problems.
