### ISSUE TITLE
`pulumi update` should print stack outputs

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#1296]
As suggested by @lukehoban in https://github.com/pulumi/home/issues/223, it would be useful if `pulumi update` printed out the stack outputs, so that customers don't have to run another command in order to see them.

Also, since stack outputs are a first-class concept, it would be nice to make them more visible.

**Comment by joeduffy** [comment]
Let's also make sure to write a test when we get to this one, to ensure we don't regress in the future, since it's subtle and I can easily imagine us losing this again down the road.

**Comment by CyrusNajmabadi** [comment]
Investigating...
