### ISSUE TITLE
--target breaks stack by deleting default inputs

### ISSUE THREAD

**Issue by neelance** [pulumi/pulumi#12964]
It should be possible to reproduce this bug on any stack with the following command:
```
pulumi preview --show-sames --target='x'
```

With Pulumi v3.67.1 it shows many entries with `[diff: -__defaults]` and some more fields that would be deleted.

Applying this update (with a proper --target) succeeds, but it leaves the stack in a broken state. For example subsequent updates try to set `name` fields to values with new random suffixes, thus wanting to replace a lot of resources.

**Comment by neelance** [comment]
Maybe relevant: We're seeing this with the TypeScript SDK and the GCP provider.

**Comment by neelance** [comment]
The bug got introduced with v3.66.0. The previous version 3.65.1 does not show this behavior.

**Comment by dixler** [comment]
Hey. Thanks for filing this. Taking a look.

**Comment by dixler** [comment]
Hey. I was able to reproduce your issue. Will have a more detailed explanation in a follow up PR to fix it.

**Comment by neelance** [comment]
Thanks!

**Comment by mikhailshilkov** [comment]
@dixler Is there an issue tracking a post-mortem?

**Comment by dixler** [comment]
Opened https://github.com/pulumi/home/issues/2878

**Comment by dixler** [comment]
For future maintainers, this issue explains the root cause of:
- https://github.com/pulumi/pulumi/issues/10020
