### ISSUE TITLE
`pulumi stack ls` inconsistent between backends

### ISSUE THREAD

**Issue by voldemortensen** [pulumi/pulumi#12974]
### What happened?

I'm in the process of moving from Pulumi Cloud to a self-managed s3 backend. While importing stacks into the new backend I ran `pulumi stack ls` to make sure I had imported all the stacks for a given project. The output included all stacks from all projects in the s3 backend.

```
NAME
dev*
dev-db
organization/aws/common
organization/aws/dev
organization/aws/ops
organization/aws/production
organization/infrastructure/dev
organization/infrastructure/production
production
production-db
```

### Expected Behavior

Only the stacks from the current project should be listed. In the above output I was in the `vpc` project and I only expected to see:

```
NAME
dev*
dev-db
production
production-db
```

Additionally, using `pulumi stack ls --project vpc` did not filter the output by project.

### Steps to reproduce

Create multiple stacks in multiple projects using the s3 backend and run `pulumi stack ls`

### Output of `pulumi about`

$ pulumi about
CLI
Version      3.67.1
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     4.38.1
python  unknown

Host
OS       darwin
Version  13.3.1
Arch     arm64

This project is written in python: executable='/opt/homebrew/bin/python3' version='3.11.3'

Current Stack: organization/vpc/dev

Found no pending operations associated with dev

Backend
Name           our-backend-name
URL            s3://our-bucket-name?awssdk=v2&profile=default
User           my-user-name
Organizations

Dependencies:
NAME        VERSION
pip         22.3.1
pulumi-aws  4.38.1
setuptools  66.0.0
wheel       0.38.4

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hi, thanks for filing this. I suspect we'll want to do this eventually, but there is some history to explain why it is this way.

For context, the pulumi self-hosted backend until recently did not have a concept of projects and only saw stacks. Scoping `pulumi stack ls` to projects could potentially break existing users (i.e. scripts) so we'll want to make sure that we're careful when changing this behavior.

**Comment by voldemortensen** [comment]
I'm not sure this is worth closing as the main issue still stands. I definitely appreciate the filter being fixed so quickly though.
