### ISSUE TITLE
ProgramTest ignores provider panic in Configure and hides logs

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#12981]
### What happened?

When working on a P1 in https://github.com/pulumi/pulumi-docker/issues/640 I have shipped a non-fix because the ProgramTest seemingly passes and hides the logs of a panic in the provider that is visible when running `pulumi up` by hand. This is really unfortunate since on the ecosystem team we rely on ProgramTest a lot in qualifying provider releases.

### Expected Behavior

A panic in a provider causes pulumi to exit with non-0 exit flag and ProgramTest to mark the test as failed.

### Steps to reproduce

See https://github.com/pulumi/pulumi-docker/issues/640 and TestSecretsInExplicitProvider

### Output of `pulumi about`

```
running 'dotnet build -nologo .'
  Determining projects to restore...

  All projects are up-to-date for restore.

  docker-640 -> /Users/t0yv0/code/pulumi-docker/examples/test-secrets-in-explicit-provider/csharp/bin/Debug/net6.0/docker-640.dll



Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.01

'dotnet build -nologo .' completed successfully
CLI          
Version      3.67.1-dev.0
Go Version   go1.20.1
Go Compiler  gc

Plugins
NAME    VERSION
docker  4.2.1
dotnet  unknown

Host     
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in dotnet: executable='/Users/t0yv0/.nix-profile/bin/dotnet' version='6.0.403'

Current Stack: t0yv0/docker-640/dev

TYPE                     URN
pulumi:pulumi:Stack      urn:pulumi:dev::docker-640::pulumi:pulumi:Stack::docker-640-dev
pulumi:providers:docker  urn:pulumi:dev::docker-640::pulumi:providers:docker::docker


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi

Dependencies:
NAME           VERSION
Pulumi         3.54.1
Pulumi.Docker  4.2.1

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/ by default

```

### Additional context

I've done a deep dive to try to understand what is going on. The panic definitely originates somewhere in `(dp dockerHybridProvider) Configure`  and can be caught with:

```
	defer func() {
	 	if e := recover(); e != nil {
	 		theerr = fmt.Errorf("CAUGHT PANIC IN COFNIGURE: %v", e)
	 	}
	}()
```

The panic does not cause process termination as something, some code somewhere performs a recover. I've not been able to find this code but quite possibly it is part of gRPC framework where panics in a gRPC method handler are turned into errors already by the framework.

With and without the panic I'm observing that Pulumi CLI acknowledges the error, that is the error gets transmitted over gRPC and processed by the gRPC client.

```
I0519 12:55:50.382279   92660 log.go:75] Provider[docker, 0xc000650b90].Configure() failed: err=CAUGHT PANIC IN COFNIGURE: Error reading level config: '' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[4dabf18193072939515e22adb298388d:1b47061264138c4ac30d75fd1eb44270 value:]'
```

However Pulumi CLI does not stop processing, in fact the control flow is a bit obfuscated by the use of a promise, so possibly the error gets swallowed in the promise:

https://github.com/pulumi/pulumi/blob/46380d4ceac13536232f028c1cd9f574fa75085e/sdk/go/common/resource/plugin/provider_plugin.go#L657-#L657

If Pulumi CLI does not want to stop processing on this error it should at least somehow acknowledge it so that the exit code from the process is not "0" indicating there was a problem.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
I want to point out there's a few workarounds by looking at stderr or engine events heuristically to detect "panic" for example this works:

```go
		// Temporary profilactic check until pulumi/pulumi#12981 is resolved.
		ExtraRuntimeValidation: func(t *testing.T, stack integration.RuntimeValidationStackInfo) {
			for _, e := range stack.Events {
				eventsJSON, err := json.MarshalIndent(e, "", "  ")
				assert.NoError(t, err)
				assert.NotContainsf(t, string(eventsJSON), "panic",
					"Unexpected panic recorded in engine events")
			}
		},

```

**Comment by abhinav** [comment]
@t0yv0 FWIW, at least for the cases in #12982, I verified that the test failed before adding the check.
It's possible for us to test that such a function would cause a test failure too, if that's preferable.

**Comment by t0yv0** [comment]
It sounds like the test cases in #12982 do not quite reproduce the scenario found in pulumi-docker then. I've just tried updating ProgramTest and Pulumi CLI to 3.68.0 and still getting this problem. Detailed repro:

```
# checkout pulumi-docker

$ git rev-parse HEAD 
1b3d7c3e51310b8c13e95517e858877f74d51e85

$ (cd examples && go test -run TestSecretsInExplicitProvider  -tags all -test.v)                                                                                            ~/code/pulumi-docker
=== RUN   TestSecretsInExplicitProvider
=== PAUSE TestSecretsInExplicitProvider
=== CONT  TestSecretsInExplicitProvider
    program.go:1782: sample: /Users/t0yv0/code/pulumi-docker/examples/test-secrets-in-explicit-provider/csharp
    program.go:1787: pulumi: /Users/t0yv0/.nix-profile/bin/pulumi
    command.go:34: **** Invoke '/Users/t0yv0/.nix-profile/bin/dotnet add package Pulumi.Docker -v 4.3.0-alpha.1684388470 -s /Users/t0yv0/.pulumi-dev/nuget --no-restore' in '/var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677'
    command.go:103: Wrote output to /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677/command-output/dotnet-add-package.20230519-155104.0e952.log
    program.go:1929: projdir: /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677
    program.go:1276: Initializing project (dir /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677; stack p-it-antons-mac-csharp-768f96fa)
    command.go:34: **** Invoke '/Users/t0yv0/.nix-profile/bin/pulumi login --cloud-url file:///var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/TestSecretsInExplicitProvider2727568510/001' in '/var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677'
    command.go:103: Wrote output to /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677/command-output/pulumi-login.20230519-155104.e383c.log
    command.go:34: **** Invoke '/Users/t0yv0/.nix-profile/bin/pulumi stack init p-it-antons-mac-csharp-768f96fa' in '/var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677'
    command.go:103: Wrote output to /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677/command-output/pulumi-stack-init.20230519-155105.adbfe.log
    program.go:1373: Performing primary preview and update
    command.go:34: **** Invoke '/Users/t0yv0/.nix-profile/bin/pulumi up --non-interactive --yes --skip-preview --event-log /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-events.json' in '/var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677'
    command.go:103: Wrote output to /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677/command-output/pulumi-update-initial.20230519-155112.b624d.log
    program.go:1345: Destroying stack
    command.go:34: **** Invoke '/Users/t0yv0/.nix-profile/bin/pulumi destroy --non-interactive --yes --skip-preview' in '/var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677'
    command.go:103: Wrote output to /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677/command-output/pulumi-destroy.20230519-155113.a5129.log
    command.go:34: **** Invoke '/Users/t0yv0/.nix-profile/bin/pulumi stack rm --yes' in '/var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677'
    command.go:103: Wrote output to /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-765733677/command-output/pulumi-stack-rm.20230519-155114.6544a.log
--- PASS: TestSecretsInExplicitProvider (10.28s)
PASS
```

However I'd like this test to fail because  e.g. /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/p-it-antons-mac-csharp-768f96fa-events.json conceals a panic.

**Comment by Frassle** [comment]
I don't think this is ProgramTest specific. I'm pretty sure the CLI itself also ignores errors in configure _unless_ the provider is actually used for something.

**Comment by t0yv0** [comment]
Interesting. Is that a feature then like "lazy-evaluate providers wrt errors"? That can make some sense but then the kinds of tests we're writing need to "utilize the provider" in some way to be actionable.

**Comment by t0yv0** [comment]
We've been having a hard look at this again in connection to failing databricks v1.16.0 release, and cannot reproduce as stated.. Sorry for the noise everyone. I think everything works as advertised here:

1. ProgramTest is faithfully looking at Pulumi CLI exit codes and will fail if Pulumi CLI returns non-0

2. In rather a special situation described in https://github.com/pulumi/pulumi/issues/13130, an error in Configure will not cause failure; this may be considered a feature; the workaround is to make sure the tests we write actually use the provider (provision some resources with it). I've basically confirmed that it works like @Frassle comments above.

3.  Panics are not recovered anywhere in our code or in gRPC code. They cause the provider process to fail with non-zero exit code and print the panic on stderr (normal Go behavior). If the panic was done before gRPC server stood up, this makes the engine fail processing with non-zero exit code as expected. If gRPC conversation is already happening, this causes gRPC calls to fail with `err=error reading from server: EOF`, while also printing the panic to stdout which get picked up by logging. Except for the special situation with Configure above, this is enough to stop processing and error out.

Current panic handling behavior is "sufficient" but not ideal. I'll file some nice-to-have improvements:

- https://github.com/pulumi/pulumi/issues/13135
- https://github.com/pulumi/pulumi/issues/13134
