### ISSUE TITLE
TS programgen bug regarding enums

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#12986]
### What happened?

I did a `pulumi import` of a [webhook](https://www.pulumi.com/registry/packages/pulumiservice/api-docs/webhook/) and it produced the following code: 

```typescript
const datalake = new pulumiservice.Webhook("datalake", {
    active: true,
    displayName: [elided],
    format: @pulumi/pulumiservice.WebhookFormat.Slack,
    organizationName: "pulumi",
    payloadUrl: [elided],
    projectName: "datalake",
    stackName: "datawarehouse-production",
}, {
    protect: true,
});
```

It says `@pulumi/pulumiservice.WebhookFormat.Slack` but it should just be `pulumiservice.WebhookFormat.Slack`

### Expected Behavior

Expected `@pulumi/pulumiservice.WebhookFormat.Slack` to be `pulumiservice.WebhookFormat.Slack`

### Steps to reproduce

create a webhook in the pulumi UI and import it using the pulumiservice provider

### Output of `pulumi about`

CLI          
Version      3.62.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME           VERSION
nodejs         unknown
pulumiservice  0.7.1

Host     
OS       darwin
Version  13.0.1
Arch     arm64

This project is written in nodejs: executable='/Users/komal/.nvm/versions/node/v18.12.0/bin/node' version='v18.12.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/komal-pulumi-corp
User           komal-pulumi-corp
Organizations  komal-pulumi-corp, service-provider-test-org, pulumi

Dependencies:
NAME                   VERSION
@pulumi/pulumi         3.62.0
@pulumi/pulumiservice  0.7.1
@types/node            16.18.23

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@Frassle This problem doesn't occur at least for _some_ other providers. Azure Native seems fine here: https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/storageaccount/

```
        bypass: "AzureServices",
        defaultAction: azure_native.storage.DefaultAction.Allow,
        ipRules: [],

```

Any guesses what can be different with the Service provider?

**Comment by Frassle** [comment]
pulumiservice sets the "packageName" language option for NodeJS. Azure-native doesn't. So I suspect it's that. 

"packageName" is only supposed to set the NPM name, not the source code name as well, but I guess wasn't ever tested with enums.

**Comment by mikhailshilkov** [comment]
Interesting! So it sounds lke the usage is correct, but programgen is wrong in this specific case. Thank you!
