### ISSUE TITLE
Regression in Python example generation

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#12998]
### What happened?

Discovered this regression in examples program generation for Python when doing routine pulumi-snowflake updates:

```
        target_failover_group = snowflake.FailoverGroup("targetFailoverGroup", from_replica=snowflake.FailoverGroupFromReplicaArgs(
            organization_name="...",
            source_account_name="...",
-            name=snowflake_failover_group["fg"]["name"],
+           name=%!v(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference),
        ),
        opts=pulumi.ResourceOptions(provider=snowflake["account2"]))
```

The update PR is in https://github.com/pulumi/pulumi-snowflake/pull/250

I've bisected the version of pulumi/pkg:

```
v3.64.0 - good
v3.65.0 - good
v3.66.0 - error
v3.68.0 - error
```

The suspect change is   https://github.com/pulumi/pulumi/pull/12804

And I've confirmed reverting the change https://github.com/pulumi/pulumi/pull/12997 restores previous behavior.

This is not blocking for updating Snowflake provider as pertains to examples generation only.

### Expected Behavior

Working code generated for Python examples or no code generated (examples omitted).

### Steps to reproduce

See linked PR.

### Output of `pulumi about`

The linked PR has go.sum to reproduce.

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
@Zaid-Ajaj do you want to take a look at this? Might be good to try and fix forwards rather than reverting.

**Comment by t0yv0** [comment]
OCI provider confirmed affected also, v0.16.0 was last known working version. Could we possibly filter out these examples. If there's no fix we can try to take some acton on the bridge side to filter out examples with the word PANIC in them; publishing them is not ideal.

**Comment by t0yv0** [comment]
Possibly related similar issue in Go codegen: https://github.com/pulumi/pulumi/issues/13108

**Comment by Zaid-Ajaj** [comment]
I am unable to reproduce from a [latest master](https://github.com/pulumi/pulumi/commit/c85c53a16f79d5db3c5c75aa5670e51167a6f9bd) local build. 

This is how I tried to repro, first I took the example from [official docs](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/failover_group):
<details>
<summary>Snowflake Terraform example</summary>

```tf
resource "snowflake_database" "db" {
  name = "db1"
}

resource "snowflake_failover_group" "source_failover_group" {
  name                      = "FG1"
  object_types              = ["WAREHOUSES", "DATABASES", "INTEGRATIONS", "ROLES"]
  allowed_accounts          = ["<org_name>.<target_account_name1>", "<org_name>.<target_account_name2>"]
  allowed_databases         = [snowflake_database.db.name]
  allowed_integration_types = ["SECURITY INTEGRATIONS"]
  replication_schedule {
    cron {
      expression = "0 0 10-20 * TUE,THU"
      time_zone  = "UTC"
    }

    // replication_schedule could also be specified with interval instead of cron
    // interval = 10
  }
}

provider "snowflake" {
  alias = "account2"
}

resource "snowflake_failover_group" "target_failover_group" {
  provider = snowflake.account2
  name     = "FG1"
  from_replica {
    organization_name   = "..."
    source_account_name = "..."
    name                = snowflake_failover_group.fg.name
  }
}
```

</details>

Converted it to PCL using convert and manual changes into the following:

<details>
<summary>Snowflake example in PCL</summary>

```tf
resource "db" "snowflake:index/database:Database" {
  name = "db1"
}
resource "sourceFailoverGroup" "snowflake:index/failoverGroup:FailoverGroup" {
  name                    = "FG1"
  objectTypes             = ["WAREHOUSES", "DATABASES", "INTEGRATIONS", "ROLES"]
  allowedAccounts         = ["<org_name>.<target_account_name1>", "<org_name>.<target_account_name2>"]
  allowedDatabases        = [db.name]
  allowedIntegrationTypes = ["SECURITY INTEGRATIONS"]
  replicationSchedule = {
    cron = {
      expression = "0 0 10-20 * TUE,THU"
      timeZone   = "UTC"
    }
  }
}
resource "targetFailoverGroup" "snowflake:index/failoverGroup:FailoverGroup" {
  name = "FG1"
  fromReplica = {
    organizationName  = "..."
    sourceAccountName = "..."
    name              = snowflake_failover_group.fg.name
  }
}

```

</details>

Then I ran the following to convert the PCL to python:
```
PULUMI_DEV=1 ~/.pulumi-dev/bin/pulumi convert --from pcl --language python --out python
```
⚠️ Important note ⚠️ 
Note that in my local build, I added `AllowMissingVariables` to the bind options in order not fail the binding when encountering `snowflake_failover_group` since it is not defined 

<details>
<summary>Snowflake example in python</summary>

```python
import pulumi
import pulumi_snowflake as snowflake

db = snowflake.Database("db", name="db1")
source_failover_group = snowflake.FailoverGroup("sourceFailoverGroup",
    name="FG1",
    object_types=[
        "WAREHOUSES",
        "DATABASES",
        "INTEGRATIONS",
        "ROLES",
    ],
    allowed_accounts=[
        "<org_name>.<target_account_name1>",
        "<org_name>.<target_account_name2>",
    ],
    allowed_databases=[db.name],
    allowed_integration_types=["SECURITY INTEGRATIONS"],
    replication_schedule=snowflake.FailoverGroupReplicationScheduleArgs(
        cron=snowflake.FailoverGroupReplicationScheduleCronArgs(
            expression="0 0 10-20 * TUE,THU",
            time_zone="UTC",
        ),
    ))
target_failover_group = snowflake.FailoverGroup("targetFailoverGroup",
    name="FG1",
    from_replica=snowflake.FailoverGroupFromReplicaArgs(
        organization_name="...",
        source_account_name="...",
        name=snowflake_failover_group["fg"]["name"],
    ))

```

</details>

Is possible to see the intermediate PCL code that used to convert to the final python code?
