### ISSUE TITLE
Go SDK Broken since v3.67.0

### ISSUE THREAD

**Issue by MMartyn** [pulumi/pulumi#13000]
### What happened?

We are building a MLC and since v3.67.0 the go sdk generation has broken on external types. We receive messages such as `$ref: failed to parse path '/aws/5.31.0/schema.json'`. Note that we use the pulumi-go-provider and nothing has changed there from when it was working and when it was working. I went through all previous version of pulumi and it was definitely something in the 3.67.0 that caused it to stop working.

### Expected Behavior

Expect that the go sdk would be built successfully.

### Steps to reproduce

Make a simple component using the pulumi-go-provider that has an external type to something like aws. Then try to `make build` and it will fail on building the go one.

### Output of `pulumi about`

CLI          
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Host     
OS       darwin
Version  13.3.1
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
`'/aws/5.31.0/schema.json'` doesn't look like a valid path, it should be `'/aws/v5.31.0/schema.json'`.

This only triggering for Go in v3.67 suggests a problem in the schema serialization. v3.67 started doing Go code generation via a new RPC call rather than in-process and that requires serializing the schema to JSON and reloading it in the code generator process.

**Comment by MMartyn** [comment]
> `'/aws/5.31.0/schema.json'` doesn't look like a valid path, it should be `'/aws/v5.31.0/schema.json'`.
> 
> This only triggering for Go in v3.67 suggests a problem in the schema serialization. v3.67 started doing Go code generation via a new RPC call rather than in-process and that requires serializing the schema to JSON and reloading it in the code generator process.

I traced the GRPC calls from the provider and they are correct. See attached from the trace 
<img width="643" alt="image" src="https://github.com/pulumi/pulumi/assets/1448102/406eda0e-3f68-4534-acf5-843be7d23313">

So it comes out of the provider correct, however when you run get-schema it removes the 'v'. In the various versions of the language hosts you can see that it does this check to add the v back https://github.com/pulumi/pulumi/blob/b6952dc617b859212b0442076ecfcd77d64f1d10/sdk/nodejs/cmd/pulumi-language-nodejs/main.go#L444 & https://github.com/pulumi/pulumi/blob/b6952dc617b859212b0442076ecfcd77d64f1d10/sdk/python/cmd/pulumi-language-python/main.go#L482 & https://github.com/pulumi/pulumi/blob/b6952dc617b859212b0442076ecfcd77d64f1d10/sdk/go/pulumi-language-go/main.go#L310

I believe that the new way of handling this via RPC calls is missing that piece.

**Comment by Frassle** [comment]
Yup looks like a bug in the schema marshaller: https://github.com/pulumi/pulumi/blob/master/pkg/codegen/schema/schema.go#L1345

It's not adding the "v" which is expected.
