### ISSUE TITLE
`--replace` throws error `error: update is marked constrained, but is not constrained to an update or a replace`

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#13001]
### What happened?

A user in community slack messaged that they were running into an error when using `--replace`

> Hi, I'm getting the following error when running pulumi with a --replace:
```
    error: update is marked constrained, but is not constrained to an update or a replace
```

This is likely due to the changes in step_generator.go

[community slack](https://pulumi-community.slack.com/archives/C84L4E3N1/p1684770323349649)

### Expected Behavior

Not run into an error.

### Steps to reproduce

.

### Output of `pulumi about`

v3.68.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Sodki** [comment]
Hi, I'm the user in question.

I get the error when using `--target` and `--replace` together.

If I only use `--replace` I don't get the error, but then the Pulumi runs only targeting those resources, not everything else in the stack, as expected.
