### ISSUE TITLE
Go generated SDKs do not set Version option on resources and invokes

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#13012]
The Version resource option is not passed when calling `RegisterResource` in Go SDKs. This behavior has been noted in the past in these issues:
- https://github.com/pulumi/pulumi/issues/9482
- https://github.com/pulumi/pulumi/issues/12963

And may have contributed to other more difficult to diagnose issues, and I discovered could also impact Azure Native. Though the Go SDK does attempt to perform runtime reflection to determine the package version, the regular expression logic is fallible and an example of this is in the wild in our Azure Native SDK.

## Proposal

Utilize the ongoing work to enable SDK publishing via commands in the Pulumi CLI (internal issue: pulumi/home#2701) to embed a version file prior to publishing. We will couple the version of the CLI used to generate SDKs to the version used to publish them, so that we can make changes to publishing workflows without breaking existing users. New functionality in codegen will be enabled by using `pulumi package gen-sdk` that, when enabled, will correlate to the expected directory structure and contents required to publish via `pulumi package publish-sdk`.

We would modify codegen for the Go SDK to (`gen-sdk`) with a flag to:

1. Add an additional file to the Go package, `sdk-version.txt`, by default to an empty file.
2. Modify the generated `func PkgVersion()` to read this file via `//go:embed` instruction.
3. Add `func DefaultResourceOpts()` and `func DefaultInvokeOpts()` functions to the SDK to return options slices for each.
4. Modify resource and invoke calls to incorporate these defaults.

Simultaneously, we would develop the Go publishing support to utilize this. Go publishing, unlike our other package managers, relies on pushing to Git. So we will implement Go publishing as:

1. Writing to the package's `sdk-version.txt` the version being published.
2. Committing and tagging this change.
3. Pushing the Go module's requisite tag (typically `/sdk/vX.Y.Z`).

## Azure Native issue

This program should return the current version of the Azure Native SDK, but it does not:

```go
package main

import (
	"fmt"

	azure "github.com/pulumi/pulumi-azure-native-sdk"
)

func main() {
	v, err := azure.PkgVersion()
	if err != nil {
		panic(err)
	}
	fmt.Printf(v.String())
}
```

Instead, it prints 1.0.0 - the default version. This results in incorrect behavior when marshaling and unmarshaling provider references (as shown in the next section) and demonstrates the fallibility of the current version resolution method in Go SDKs. Interestingly, this misbehavior **does not** break use of the Azure Native SDK, because that version is not used in resource options calls. Otherwise, this issue would have been discovered much sooner.

## Current plugin resolution

In all of our SDKs except Go, resource and invoke options are used to tell the engine which version of a provider package to use, and therefore which plugin to acquire and use. In Go, we do attempt to discover the version in `pulumiUtilities.go`, as seen below, but this is not used in `RegisterResource()` calls.

```go
// PkgVersion uses reflection to determine the version of the current package.
// If a version cannot be determined, v1 will be assumed. The second return
// value is always nil.
func PkgVersion() (semver.Version, error) {
	type sentinal struct{}
	pkgPath := reflect.TypeOf(sentinal{}).PkgPath()
	re := regexp.MustCompile("^.*/pulumi-example/sdk(/v\\d+)?")
	if match := re.FindStringSubmatch(pkgPath); match != nil {
		vStr := match[1]
		if len(vStr) == 0 { // If the version capture group was empty, default to v1.
			return semver.Version{Major: 1}, nil
		}
		return semver.MustParse(fmt.Sprintf("%s.0.0", vStr[2:])), nil
	}
	return semver.Version{Major: 1}, nil
}
```

And in `init.go` we call `pulumi.RegisterResourceModule` and `pulumi.RegisterResourcePackage`. However, these functions are not how we communicate plugin versions to the engine; they're used for a different purpose involving marshaling and unmarshaling resource references. This was discovered by finding the definitions of `pulumi.RegisterResourceModule` and co, and then looking at where the maps they populate are used.

```go
func init() {
	version, _ := PkgVersion()
	pulumi.RegisterResourceModule(
		"example",
		"",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"example",
		&pkg{version},
	)
}
```

From `pulumi/sdk/go/pulumi/rpc.go`:

```go
# Not used during register resource calls.
var (
	resourcePackages versionedMap
	resourceModules  versionedMap
)

// RegisterResourcePackage register a resource package with the Pulumi runtime.
func RegisterResourcePackage(pkg string, resourcePackage ResourcePackage) {
	if err := resourcePackages.Store(pkg, resourcePackage); err != nil {
		panic(err)
	}
}
```

However, this is not how our other languages send package version information to the engine. Instead, they use the `Version` resource option. You can see this in the resource constructors and default options generated in Python ([ctor](https://github.com/pulumi/pulumi/blob/93ba8d4f8b60896ac6ca0b954095ddb26afb76bf/pkg/codegen/testing/test/testdata/simple-yaml-schema/python/pulumi_example/other_resource.py#L80-L103), [opts](https://github.com/pulumi/pulumi/blob/93ba8d4f8b60896ac6ca0b954095ddb26afb76bf/pkg/codegen/testing/test/testdata/simple-yaml-schema/python/pulumi_example/_utilities.py#L93-L105)), Nodejs ([ctor](https://github.com/pulumi/pulumi/blob/93ba8d4f8b60896ac6ca0b954095ddb26afb76bf/pkg/codegen/testing/test/testdata/simple-yaml-schema/nodejs/otherResource.ts#L33-L44), [opts](https://github.com/pulumi/pulumi/blob/93ba8d4f8b60896ac6ca0b954095ddb26afb76bf/pkg/codegen/testing/test/testdata/simple-yaml-schema/nodejs/utilities.ts#L41-L54)), and Dotnet ([ctor](https://github.com/pulumi/pulumi/blob/93ba8d4f8b60896ac6ca0b954095ddb26afb76bf/pkg/codegen/testing/test/testdata/simple-yaml-schema/dotnet/OtherResource.cs#L31-L42), [opts](https://github.com/pulumi/pulumi/blob/93ba8d4f8b60896ac6ca0b954095ddb26afb76bf/pkg/codegen/testing/test/testdata/simple-yaml-schema/dotnet/Utilities.cs#L58-L74)) sdks. However, in Go, `RegisterResource` lacks any default options:

[Example from the same provider as linked above in Go](https://github.com/pulumi/pulumi/blob/93ba8d4f8b60896ac6ca0b954095ddb26afb76bf/pkg/codegen/testing/test/testdata/simple-yaml-schema/go/example/otherResource.go#L20-L32):
```go
// NewOtherResource registers a new resource with the given unique name, arguments, and options.
func NewOtherResource(ctx *pulumi.Context,
	name string, args *OtherResourceArgs, opts ...pulumi.ResourceOption) (*OtherResource, error) {
	if args == nil {
		args = &OtherResourceArgs{}
	}

	var resource OtherResource
	err := ctx.RegisterRemoteComponentResource("example::OtherResource", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}
```

## How does this work today?

Given all of the above, and the identified issue in Azure Native returning a constant `1.0.0`, one wonders how this even works today. The answer is that the Go language host performs package discovery via `gGetProgramDependencies`. The engine reuses the versions of dependencies discovered here when the `Version` resource option is absent. 

However, this approach is brittle - it depends on `go.mod`, so it may fails for build systems that use separate versioning tooling such as Bazel/Buck/etc. - and shelling out to `go list --json -m ...` on the directory. This function recently had to be changed to handle vendored dependencies and program dir changes to address regressions introduced in #12727, found in #12963, and fixed by #12967.

## Conclusion

By coupling Go codegen and SDK publishing, we can inject accurate versions into the SDK and bring Go in line with our other languages in explicitly constructing resources with package versions.

**Comment by abhinav** [comment]
> 1. Writing to the package's `sdk-version.txt` the version being published.
> 2. Committing and tagging this change.
> 3. Pushing the Go module's requisite tag (typically `/sdk/vX.Y.Z`).

Worth highlighting that this will **not** push the commit that updates sdk-version.txt to main.
The git commit graph for a provider will roughly take the form:

```
main ---o---o---o---o---o---o---...
         \       \           \
          o       o           o
          v1.2.3  v1.2.4      v1.3.0
```

**Comment by AaronFriel** [comment]
Technically `sdk/v1.2.3`, but yes. The plan is not to push to a branch, only a tag.

**Comment by abhinav** [comment]
@pulumi/platform Discussed this in Ideation last week and we agree with this direction.

**Comment by AaronFriel** [comment]
Update on this @abhinav @Frassle - @guineveresaenger and I discovered two things:

1. A potential race in the generated resource constructors from sharing `opts` and mutating it (https://github.com/pulumi/pulumi-docker/blob/master/sdk/go/docker/image.go#L139-L160)
2. An infrequently used code path that does generate a `pkgResourceDefaultOpts` function, but would not be used for first party providers, as they do not set `pluginDownloadURL`. We found a bug in that implementation as well. When a resource constructor is created in a package not at the top level, the function `pkgResourceDefaultOpts` isn't exported and isn't generated with a qualified name.

We'll handle both of these, making this a more robust code path and align it with our other SDK codegen.

**Comment by Frassle** [comment]
Reopened to track adding the publish changes still needed.

**Comment by mikhailshilkov** [comment]
Unassigned Providers for now, since additional changes are needed on the Core side and they are discussing another approach based on plugin JSON files

**Comment by danielrbradley** [comment]
This is now complete for all bridged and native providers as tracked through https://github.com/pulumi/ci-mgmt/issues/915
