### ISSUE TITLE
Output from RandomInteger is in scientific notation

### ISSUE THREAD

**Issue by chris-activewrite** [pulumi/pulumi#13016]
### What happened?

This code:

```python
random_id = random.RandomInteger(
    f"{project_name}-stack-id", min=1000000, max=9999999
).result
pulumi.export("account-random-id", random_id)
```

Results in this output (e.g. from `pulumi stack`):

```text
Outputs:
    account-random-id        : 9.429773e+06
```

### Expected Behavior

The value should be printed as an integer.

No matter how large the `min` and `max` values are, the value should be output in a lossless way,.

### Steps to reproduce

See code above

### Output of `pulumi about`

CLI
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.40.0
awsx        1.0.2
docker      3.6.1
eks         1.0.2
kubernetes  3.27.1
postgresql  3.8.0
python      unknown
random      4.13.0

Host
OS       darwin
Version  12.6.5
Arch     x86_64

This project is written in python: executable='/Users/chrisj/proj/pulumi_aw_aws_demo/venv/bin/python3' version='3.11.3
'

Current Stack: activewrite/env-demo-infra/infra01

TYPE                                      URN
pulumi:providers:aws                      urn:pulumi:infra01::env-demo-infra::pulumi:providers:aws::default
pulumi:pulumi:Stack                       urn:pulumi:infra01::env-demo-infra::pulumi:pulumi:Stack::env-demo-infra-infra01
pulumi:providers:random                   urn:pulumi:infra01::env-demo-infra::pulumi:providers:random::default_4_13_0
pulumi:providers:aws                      urn:pulumi:infra01::env-demo-infra::pulumi:providers:aws::default_5_40_0
random:index/randomInteger:RandomInteger  urn:pulumi:infra01::env-demo-infra::random:index/randomInteger:RandomInteger::env-demo-infra-stack-id
aws:route53/zone:Zone                     urn:pulumi:infra01::env-demo-infra::aws:route53/zone:Zone::env-demo-infra-subdomain-zone
aws:s3/bucket:Bucket                      urn:pulumi:infra01::env-demo-infra::aws:s3/bucket:Bucket::env-demo-infra-infra01-subdomain-bucket

Found no pending operations associated with infra01

Backend
Name           pulumi.com
URL            https://app.pulumi.com/chris-activewrite
User           chris-activewrite
Organizations  chris-activewrite, activewrite

Dependencies:
NAME               VERSION
pip                22.3.1
pulumi-awsx        1.0.2
pulumi-eks         1.0.2
pulumi-postgresql  3.8.0
pulumi-random      4.13.0
setuptools         65.5.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
> Short term maybe we just change the formatting we use to prefer plain notation for non-fractional numbers.

Agreed - let's use this issue to track making this change.
