### ISSUE TITLE
Add an "isDeploying" flag or "onDeploy" event to run code only during the actual deployment and not during preview

### ISSUE THREAD

**Issue by LazaroOnline** [pulumi/pulumi#13023]
We have an scenario where we want to add a call to a function only when pulumi is actually deploying the resources to the cloud during the pulumi up after the user accepts to deploy, and not during a `pulumi preview` nor when a user runs `pulumi up` but then he doesn't accept the deployment.

Some possible implementations of the interface would be:
```js
if (!pulumi.isDeploying) {
  myUserFunction();
}
```
or something like this:

```js
pulumi.onDeploy(() => {
  myUserFunction();
});
```

This feature request is related to this [stackoverflow question](https://stackoverflow.com/questions/76331022/way-in-pulumi-to-run-a-function-only-when-pulumi-up-deploys-resources-and-not-du) where it explains the details of the case we have that would require this feature.

- Vote on this issue by adding a 👍 reaction

**Comment by Frassle** [comment]
Was also [answered on stackoverlow](https://stackoverflow.com/a/76331192/534376) but the isDryRun property tells you this.
