### ISSUE TITLE
When deploying pulumi with targeted resources, if resources not targeted has missing required properties, error is thrown

### ISSUE THREAD

**Issue by zweihan** [pulumi/pulumi#13034]
### What happened?

We are trying to deploy pulumi changes to a part of the stack with `--target` flag. If a new resource, that is not part of the targeted group, has missing required properties, an error is thrown even if we do not intend to create that resource. 
The error thrown:
```
gcp:pubsub/subscription:Subscription resource 'subscription' has a problem: Missing required argument: The argument "topic" is required, but no definition was found.. Examine values at 'Subscription.Topic'.
```

### Expected Behavior

Pulumi should ignore any resource that is not targeted specifically. 

### Steps to reproduce

I have a minimal example [here](https://github.com/zweihan/pulumi-example/tree/master/example2). There are 3 resources in the stack: the stack itself, a topic and a subscription. 

The subscription has an Output, `topic.id`, as a required property. 

On a new stack, if we run command to target the stack resource, `pulumi up --target urn:pulumi:minimal-example-dev::minimal_example::pulumi:pulumi:Stack::minimal_example-minimal-example-dev`,  an error is thrown:
```
gcp:pubsub/subscription:Subscription resource 'subscription' has a problem: Missing required argument: The argument "topic" is required, but no definition was found.. Examine values at 'Subscription.Topic'.
```

### Output of `pulumi about`

CLI          
Version      3.65.1
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.56.0
nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/weihan/.nvm/versions/node/v18.12.1/bin/node' version='v18.12.1'

Backend        
Name           weihan-g14
URL            gs://arbo-pulumi-backend
User           weihan
Organizations  

Dependencies:
NAME            VERSION
@pulumi/gcp     6.56.0
@pulumi/pulumi  3.68.0
@types/node     16.18.33

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I think the next release will fix this because Check will no longer be called for non-targeted resource.

**Comment by lunaris** [comment]
I've just tested this on the latest version (3.143.0) and I think this has been fixed. Additionally, checking the code in `step_generator` it's apparent that we don't call `Check` (which performs property validation) for resources that aren't targeted any more. Marking as closed but please re-open if I'm wrong! 🙏
