### ISSUE TITLE
Asynchronous Mocks for Unit Testing TypeScript Programs

### ISSUE THREAD

**Issue by DSoko2** [pulumi/pulumi#13049]
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi's mocking feature for TypeScript is configured by calling `pulumi.runtime.setMocks(...)`. It only supports synchronous mock implementations. I.e., the functions `call` and `newResource`, which are provided as an object of type `Mocks`, must be synchronous. This prevents using any asynchronous function or APIs to generate or retrieve values to return because they cannot be awaited in a synchronous TS function.

I want to use asynchronous APIs (functions) in my mock implementations. I do not see a way to use Pulumi's mocking for TypeScript that would allow me to do so.

To add support, I could imagine the following solution:

Mocks are currently configured with an object of type `pulumi.runtime.Mocks`:
```
interface Mocks {
    call(args: MockCallArgs): Record<string, any>;
    newResource(args: MockResourceArgs): { id: string | undefined; state: Record<string, any> };
}
```
This could be replaced with the following to enable configuring asynchronous mock implementations:
```
interface CallMock {
	callAsync?: false;
	call(args: MockCallArgs): Record<string, any>;
}
interface AsyncCallMock {
	callAsync: true;
	call(args: MockCallArgs): Promise<Record<string, any>>;
}
interface ResourceMock {
	newResourceAsync?: false;
	newResource(args: MockResourceArgs): { id: string | undefined; state: Record<string, any> };
}
interface AsyncResourceMock {
	newResourceAsync: true;
	newResource(args: MockResourceArgs): Promise<{ id: string | undefined; state: Record<string, any> }>;
}
type Mocks = (CallMock | AsyncCallMock) & (ResourceMock | AsyncResourceMock);
```
This definition would ensure that for both mock types one implementation is provided, sync or async. The `MockMonitor` can use the `callAsync` and `newResourceAsync` flags to identify whether the mock is async. Handling the async functions in the `MockMonitor` should be trivial as all functions handling mocks are already asynchronous. 

### Affected area/feature

Pulumi TypeScript SDK, specifically the runtime mocks module.

**Comment by DSoko2** [comment]
I implemented a sketch of the feature above: DSoko2/pulumi@d642e0e227eb049e9cb49ef11ea7f0b2034109d3

In contrast to my initial post above, this implementation preserves the current `Mocks` interface with statically known properties, which is required to be backwards compatible with code extending that interface.

I would be willing to continue working on this based on your feedback. I'd be happy to see this feature merged and am willing to contribute to make this a PR. Apart from the implementation, I'd require some hint how and where such feature should be tested. If I am seeing it right, there seem to be no explicit tests for mocks; but they are tested implicitly by a number of other tests, which use the feature. Would migrating some of these other tests to the async interface a valid way to go?

**Comment by RobbieMcKinstry** [comment]
Hi @DSoko2! Awesome, thanks for your enthusiasm and engagement! It's always great to encounter an issue where the community member has already put together a solution! 😺 

I see no reason why we wouldn't accept a PR for this feature. It's well-aligned with the goals of the mocking package. From what I can tell, your commit is backward-compatible with the current API, which is a requirement for accepting a PR. So far so good!

Re: testing, rather than replacing existing tests to use the async interface, I expect we'd prefer if you copied an existing test and ported it to the async interface. Perhaps that's what you already had in mind. I think that would be sufficient proof of correctness. 👍🏻 

Looking forward to your PR! Thank you very much for taking initiative to improve the `Mock` interface!

**Comment by DSoko2** [comment]
Thanks a lot for reviewing and merging @Frassle and anyone else involved!
