### ISSUE TITLE
Import issues an odd converter error message, seemingly unrelated to the command

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#13062]
This error message does not seem right to me:

```
$ pulumi import aws:s3/bucket:Bucket some-bucket
error: an inline resource must be specified if no converter or import file is used
```

Shouldn't it instead say something like, `missing required id argument`, and print the `import` command's usage?

**Comment by RobbieMcKinstry** [comment]
Hi Joe,

Yes. That's the same error message you get if you provide any fewer than three arguments to `import`.
i.e.,
1. `pulumi import aws:s3/bucket:Bucket some-bucket`
2. `pulumi import aws:s3/bucket:Bucket`
3. `pulumi import`

We can address each of these three cases separately, with an error message for each. _e.g._

1. "You provided two arguments, but you must provide three. You're missing id"
2. "...you're missing name and id."
3. ...
