### ISSUE TITLE
python automation api does not apply on_output

### ISSUE THREAD

**Issue by jepsenwan** [pulumi/pulumi#13094]
### What happened?

Hi when using the automation api in Celery task, I could not redirect logs from console to log_handler.

```python
    def log_handler(log_entry: str):
        # Log the message to the task log
        message = log_entry.message
        print(message)
        task.log += message + '\n'
        task.save()

    def run_update():

        print('stack_name', stack_name)
        try:
            # Create a stack
            stack = auto.create_or_select_stack(stack_name=stack_name, project_name=project_name, program=program)
            print('stack', stack)

            # Set up the pulumi configuration
            stack.set_config("aws:region", auto.ConfigValue("us-west-2"))

            # Run pulumi up and capture logs using the update callback
            update_summary = stack.up(on_output=log_handler)

        except Exception as ex:
            task.status = (f"An error occurred: {str(ex)}")
            task.save()
        # finally:
        #     # Clean up the stack if it was created
        #     if stack:
        #         stack.destroy(on_output=print)

    run_update()
```

TIA.

 

### Expected Behavior

With the on_output=print, I could see normal logs and resource creation logs. 
```
 +  aws:iam:Role worker-node-role created (8s)
 +  aws:iam:Role eks-role created (8s)
 +  aws:iam:RolePolicyAttachment worker-node-policy-3 creating (0s)
 +  aws:iam:RolePolicyAttachment worker-node-policy-1 creating (0s)
 +  aws:iam:RolePolicyAttachment worker-node-policy-0 creating (0s)
 +  aws:iam:RolePolicyAttachment worker-node-policy-2 creating (0s)
```

Likewise, when it is with on_output=log_handler, it is supposed to write log to the task.log textfield. 

### Steps to reproduce

However, with the on_output=log_handler argument and value in stack.up(), it is failed to write logs to task.log  and even it failed to run the stack.up and not throwing any error. 

Please help figure out if this is normal behaviour.

### Output of `pulumi about`

CLI          
Version      3.69.0
Go Version   go1.20.4
Go Compiler  gc

Host     
OS       darwin
Version  13.2.1
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jepsenwan
User           jepsenwan
Organizations  jepsenwan

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jepsenwan** [comment]
Thanks for figuring it out, 
```
   def log_handler(log_entry):
        # Log the message to the task log
        message = log_entry.message
        print(message)
        task.log += message + '\n'
        task.save()
```
        
        Indeed a string should not have an attribute message,  actually It was like above, and I tried again, but still it had the same behaviour.

Appreciate if you could help check further into it.

Thanks

**Comment by julienp** [comment]
Hey @jepsenwan, I am able to use an on_output handler for stack.up and it works as expected for me. Could you share more details on the error you are seeing?

**Comment by mikhailshilkov** [comment]
@jepsenwan Are you still experiencing this issue, or can we close it now?

**Comment by mikhailshilkov** [comment]
I'll close the issue as stale for now - please let us know if you are still facing any problems
