### ISSUE TITLE
Missing explicit dependency on `@opentelemetry/instrumentation` in Node.js package

### ISSUE THREAD

**Issue by jasperlin451** [pulumi/pulumi#13104]
### What happened?

The package has a dependency on `@opentelemetry/instrumentation` 
 here: https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/cmd/run/tracing.ts#L24. But I assume that this is assuming that one of the other packages will hoist that library up to the root level and make it available since it's not explicitly declared. https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/package.json#L16
 
 However, in a monorepo setup w/ npm workspaces, this hoisting does not happen because another version of `@opentelemtry/instrumentation` exists. As a result pulumi crashes out with `error: Error: Cannot find module '@opentelemetry/instrumentation'`

### Expected Behavior

The `@pulumi/pulumi` package explicitly declares the version of `@opentelemetry/instrumentation` it needs.

### Steps to reproduce

Setup two npm workspaces: one that installs `@pulumi/pulumi` and one that installs a different version of `@opentelemetry/instrumentation` that prevent hoisting.

### Output of `pulumi about`

Not particularly relevant:

```
CLI
Version      3.69.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
awsx    1.0.1
nodejs  unknown

Host
OS       darwin
Version  13.4
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Place1** [comment]
I've also run into this issue. The workaround for now is to tell pnpm to hoist the package using the following `.npmrc` configuration

```
# multiple pulumi packages depend on the @opentelemetry/instrumentation
# package but do not declare a dependency on it within their package.json file.
# this is a bug/mistake within the pulumi packages but it causes runtime errors.
# this configuration tells pnpm to hoist the specific package so that
# it can be resolved from the root node_modules as a workaround.
# https://github.com/pulumi/pulumi/issues/13104
public-hoist-pattern[]=*@opentelemetry/instrumentation*
```

**Comment by dixler** [comment]
Thanks for filing this. Would you be able to put together a minimal repository that reproduces the failing environment? It'd help make sure that the fix addresses the setup that you're reporting it on :pray:

**Comment by jasperlin451** [comment]
https://github.com/jasperlin451/pulumi-hoisting-issue/tree/main

Here's the minimal setup
