### ISSUE TITLE
[codegen/go] Panic in Go Codegen

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#13108]
### What happened?

While reviewing a routine provider upgrade, I saw https://github.com/pulumi/pulumi-hcloud/pull/222/files#r1219396004:
```
// SshKeys: %!v(PANIC=Format method: fatal: A failure has occurred: unlowered splat expression @ #-functions-hcloud:index-getSshKeys:getSshKeys.pp:6,13-35),
```

### Expected Behavior

No visible panics in codegen.

### Steps to reproduce

See PR for details. 

The failing terraform is:
```tf
data "hcloud_ssh_keys" "all_keys" {
}
data "hcloud_ssh_keys" "keys_by_selector" {
  with_selector = "foo=bar"
}
resource "hcloud_server" "main" {
  ssh_keys = data.hcloud_ssh_keys.all_keys.ssh_keys.*.name
}
```

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
@Frassle I see you've been working on codegen recently, can you take a look?

**Comment by Frassle** [comment]
@Zaid-Ajaj said he might have some time to check this today as well. But if not I can look into tomorrow.

**Comment by Zaid-Ajaj** [comment]
@Frassle will have a look tomorrow morning
