### ISSUE TITLE
The use of UseSharedCompilation in .NET Template files

### ISSUE THREAD

**Issue by jaredpar** [pulumi/pulumi#13145]
### What happened?

Looking through the template files for .NET projects noticed they have the following

```csharp
<UseSharedCompilation>false</UseSharedCompilation>
```

Further it's present in most of the .NET based project files in this repository. 

Wanted to understand why this was done. That flag controls whether .NET uses the compiler server in the background vs. shelling out to a command line tool on every build. It's effectively a build optimization. By disabling this server you're effectively slowing down customer builds. This slow down can be quite significant once you get into medium to large sized projects. Easily in the 50-70% slowdown range depending on size and structure. 

Is there a functional reason you made this change? If so I'd like to learn more about it. 

### Expected Behavior

Don't use this flag cause it's just slowing down builds. 

### Steps to reproduce

This can't be empty so I'll just say "look at the code" 😄 

### Output of `pulumi about`

Don't have pulumi installed 😄 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Looks like this was put in years ago (2021) to work around https://github.com/pulumi/pulumi-azure-native/issues/985 & https://github.com/dotnet/roslyn/issues/54775. 

Looks like this limit has been lifted since then (https://github.com/dotnet/roslyn/pull/54992) so we could probably just remove these settings.

**Comment by justinvp** [comment]
Thanks, @jaredpar!

**Comment by jaredpar** [comment]
I completely forgot about that bug. Well know I'm really glad we fixed it 😄 

Thanks for getting this fixed on your side.
