### ISSUE TITLE
Pulumi doesn't build with latest version of azblob

### ISSUE THREAD

**Issue by cookie-mateo** [pulumi/pulumi#13161]
### What happened?

When building a project requiring both Pulumi and `github.com/snowflakedb/gosnowflake` v1.6.19 or above, we see the following error due to Pulumi using `gocloud.dev` v0.27.0

```
external/dev_gocloud/blob/azureblob/azureblob.go:339:66: undefined: azblob.ServiceClient
external/dev_gocloud/blob/azureblob/azureblob.go:342:3: unknown field Telemetry in struct literal of type azblob.ClientOptions
external/dev_gocloud/blob/azureblob/azureblob.go:354:17: undefined: azblob.NewServiceClient
external/dev_gocloud/blob/azureblob/azureblob.go:388:46: undefined: azblob.ServiceClient
external/dev_gocloud/blob/azureblob/azureblob.go:419:17: undefined: azblob.ContainerClient
external/dev_gocloud/blob/azureblob/azureblob.go:426:58: undefined: azblob.ServiceClient
external/dev_gocloud/blob/azureblob/azureblob.go:434:56: undefined: azblob.ServiceClient
external/dev_gocloud/blob/azureblob/azureblob.go:442:56: undefined: azblob.ServiceClient
external/dev_gocloud/blob/azureblob/azureblob.go:534:16: undefined: azblob.BlobDownloadResponse
external/dev_gocloud/blob/azureblob/azureblob.go:847:21: undefined: azblob.BlockBlobClient
external/dev_gocloud/blob/azureblob/azureblob.go:354:17: too many errors
```

### Expected Behavior

I expected my build to complete successfully

### Steps to reproduce

Create a project that includes both Pulumi and  `github.com/snowflakedb/gosnowflake v1.6.19`, attempt to build project. 

### Output of `pulumi about`

CLI
Version      3.62.0
Go Version   go1.20.2
Go Compiler  gc

Host
OS       ubuntu
Version  20.04
Arch     x86_64

Pulumi locates its logs in /tmp by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /home/ubuntu/dev/cookieai-core). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: A new version of Pulumi is available. To upgrade from version '3.62.0' to '3.71.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

### Additional context

Upgrading `github.com/snowflakedb/gosnowflake` to v1.6.19 or above is fairly urgent due to a security vulnerability: https://github.com/advisories/GHSA-fwv2-65wh-2w8c

It looks like upgrading `gocloud.dev` from v0.27.0 to v0.29.0 (latest) would solve the issue, as the latest version of gocloud.dev relies on `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob` v1.0.0, which is the same version relied on by  `github.com/snowflakedb/gosnowflake` v1.6.19. 

The core of the issue is that `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob` introduced breaking changes between v0.4.1 and v1.0.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Are you depending on `github.com/pulumi/pulumi/pkg/v3` instead of `github.com/pulumi/pulumi/sdk/v3`? 
`pkg` isn't really intended to be depended on for most use cases, so you might be ok just depending on sdk instead.

Updating go.cloud sounds reasonable though, hopefully a simple bump.

**Comment by cookie-mateo** [comment]
Pull request created to upgrade gocloud.dev from v1.27.0 to v1.29.0: https://github.com/pulumi/pulumi/pull/13167

**Comment by Frassle** [comment]
We're going to have to reopen this. Updating go.cloud broke numerous azure users.
