### ISSUE TITLE
CLI tries to hit /api/cli/version API 4 times before giving up

### ISSUE THREAD

**Issue by jasonwbarnett** [pulumi/pulumi#13166]
### What happened?

I recently used [mitmproxy][1] only to discover that when running the CLI in an airgapped environment the CLI attempts to reach out to hit https://api.pulumi.com/api/cli/version 4 times, when it can't reach it.

A few things to note:

1. Why is it trying 4 times? Seems excessive.
   1. When this happens in an airgapped environment it causes a significant delay to the CLI returning, ~8 seconds

### Expected Behavior

I would expect the CLI to attempt to reach out to https://api.pulumi.com/api/cli/version only once.

### Steps to reproduce

1. Use iptables (or whatever OS firewall you have) and block requests destined to 80 and 443.
2. Run `pulumi about`

It's also very helpful to use [mitmproxy][1].

### Output of `pulumi about`

```text
CLI
Version      3.71.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.103.0
gitlab        6.0.0
python        unknown

Host
OS       redhat
Version  7.9
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.9.5
'

Backend
Name           my-host
URL            file://~
User           my-user
Organizations

Dependencies:
NAME                 VERSION
pip                  21.1.1
pulumi-azure-native  1.103.0
pulumi-gitlab        6.0.0
setuptools           56.0.0

Pulumi locates its logs in /tmp/my-user by default
warning: Failed to get information about the current stack: No current snapshot
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already). 

[1]: https://mitmproxy.org/

**Comment by abhinav** [comment]
Thanks for the report, @jasonwbarnett.

Yeah, this is not ideal. The [relevant component](https://github.com/pulumi/pulumi/blob/adb18cd1b27d6961a79b3010b01bc598df5d6d43/pkg/backend/httpstate/client/api.go#L159-L168) is configured to make 4 attempts.

We have some partial work on this (#12660) that we're planning on finishing up in the future, which should alleviate this a bit, but the retries are still a bit annoying.
We'll look into fixing that.

We may also look into making this check non-blocking on exit: if the check hasn't reported anything by the time the program exits, we should maybe not wait for it.

While we work on this, we recommend setting PULUMI_SKIP_UPDATE_CHECK as you've discovered.

**Comment by Frassle** [comment]
> Drop retries on the /api/cli/version check
> Don't wait for the check at exit (relevant bits)

I'm not sure about this. Part of me thinks having this be slow enough to be noticeable drives people towards finding and turning on SKIP_UPDATE_CHECK in environments where that makes sense.

**Comment by abhinav** [comment]
#12659 is already out.
Per internal discussion, we'll drop the retries from this call.
