### ISSUE TITLE
Unable to use keyvault as secrets manager in 3.72.0 

### ISSUE THREAD

**Issue by sebbegg** [pulumi/pulumi#13181]
### What happened?

Used pulumi 3.72 in an existing project.
When accessing the stack using an azure keyvault as secrets provider, this fails:

```console
# ./pulumi/pulumi referring to the freshly download 3.72.0 release

venv ❯ ./pulumi/pulumi stack 
error: constructing secrets manager of type "cloud": secrets (code=InvalidArgument): POST https://<some-vault>.vault.azure.net/keys/<some-key>/decrypt
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadParameter
--------------------------------------------------------------------------------
{
  "error": {
    "code": "BadParameter",
    "message": "The parameter is incorrect.\r\n"
  }
}
--------------------------------------------------------------------------------

```
Probably needless to say, that `pulumi up|preview|...` fail with the same error 😉 

We're authenticating via the azure cli, having `AZURE_KEYVAULT_AUTH_VIA_CLI` set.
Rolling back (locally and/or in CI) to 3.71 solves the issue, so this does not seem to be an issue with the keyvault.

### Expected Behavior

Keyvault secrets provider should be initialized without errors.

### Steps to reproduce

Try e.g. `pulumi stack output --show-secrets` with a keyvault secrets provider and pulumi 3.72

### Output of `pulumi about`

venv ❯ ./pulumi/pulumi about
CLI
Version      3.72.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.81.0
databricks    1.11.2
helpers       0.1.0
kubernetes    3.21.2
python        unknown
random        4.7.0
traefik_crds  3.21.2

Host
OS       darwin
Version  13.4
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This looks the same as https://github.com/pulumi/pulumi/issues/11982 which happened last time we tried to update go.cloud from 0.27 to 0.28. We've just updated from 0.27 to 0.29, so this is probably exactly the same issue as last time.

**Comment by Frassle** [comment]
We're going to revert the go.cloud update and get a release out today.
