### ISSUE TITLE
Azure KeyVault Secrets Provider no longer works with v3.72.1+

### ISSUE THREAD

**Issue by matteocalabro-tomtom** [pulumi/pulumi#13201]
### What happened?

After the update, trying to deploy a stack results in the following error:
```
pulumi up -y
error: getting stack configuration: get stack secrets manager: secrets (code=InvalidArgument): keyvault.BaseClient#Decrypt: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="Content of 'value' is not base64url.\r\nProperty 'value' is required.\r\n"
```

Trying to refresh the encryption key returns a similar error:
```
pulumi stack change-secrets-provider azurekeyvault://<something>.vault.azure.net/keys/key-pulumi-secretsprovider-nonprod
Migrating old configuration and state to new secrets provider
error: could not deserialize deployment: constructing secrets manager of type "cloud": secrets (code=InvalidArgument): keyvault.BaseClient#Decrypt: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="Content of 'value' is not base64url.\r\nProperty 'value' is required.\r\n"
```

### Expected Behavior

I'd expect the stack to be deployed/updated correctly.

### Steps to reproduce

- Create a stack using pulumi <3.72.2 and Azure KeyVault as a secrets provider
- pulumi up
- Upgrade pulumi 3.72.2
- pulumi up

### Output of `pulumi about`

```
pulumi about
CLI
Version      3.72.2
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.103.0
azure-native  1.103.0
azure-native  1.103.0
azure-native  1.103.0
azure-native  1.103.0
azure-native  1.103.0
azuread       5.38.0
go            unknown

Host
OS       darwin
Version  13.4
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.20.5 darwin/arm64'

Backend
Name           <redacted>
URL            azblob://<redacted>
User           <redacted>
Organizations

Dependencies:
NAME                                                           VERSION
github.com/pulumi/pulumi-azure-native-sdk/app                  1.103.0
github.com/pulumi/pulumi-azure-native-sdk/containerregistry    1.103.0
github.com/pulumi/pulumi-azure-native-sdk/network              1.103.0
github.com/pulumi/pulumi-azure-native-sdk/operationalinsights  1.103.0
github.com/pulumi/pulumi-azure-native-sdk/resources            1.103.0
github.com/pulumi/pulumi-azuread/sdk/v5                        5.38.0
github.com/pulumi/pulumi/sdk/v3                                3.72.2

Pulumi locates its logs in /var/folders/sx/p446wqzn68g85fb80vtfb4f00000gp/T/ by default
warning: Failed to get information about the current stack: constructing secrets manager of type "cloud": secrets (code=InvalidArgument): keyvault.BaseClient#Decrypt: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="Content of 'value' is not base64url.\r\nProperty 'value' is required.\r\n"
```

### Additional context

Earlier today, I tried upgrading to azure native sdk v2 without success (go cannot find the packages). Could it be there is a dependency conflict?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by matteocalabro-tomtom** [comment]
Also affects 3.72.1, azure keyvault secrets work fine with pulumi 3.72.0.

**Comment by Frassle** [comment]
Does it work for 3.71.0? This may be related to the gocloud.dev updgrade/revert.

**Comment by Frassle** [comment]
Can you confirm if it works for 3.71.0 (not 3.72.0)?

**Comment by Frassle** [comment]
This is almost certainly some inconsistency between the two versions of gocloud.dev we've switched between.
It appears your in the unfortunate position of having created a key on 3.72.0 using the newer version which we had to revert back in 3.72.1. 
I would suggest using 3.72.0 to change the secrets provider to the passphrase provider (`pulumi stack change-secrets-provider passphrase`) and then upgrading to 3.72.2 and changing it back to use the azure secrets provider. 
I'd consider there being very little chance of the CLI working with key generated by 3.72.0 ever again.

**Comment by matteocalabro-tomtom** [comment]
Lucky me! I already did that, thanks for the help. Good to know it's unlikely to happen again 😁

**Comment by rwood-97** [comment]
Hi, I'm working on some code that was created mid-June and am also stuck with this issue. I've tried using v3.72.0 but get this output:

```
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember): 
Enter your new passphrase to protect config/secrets: 
Re-enter your new passphrase to confirm: 
Migrating old configuration and state to new secrets provider
error: could not deserialize deployment: constructing secrets manager of type "cloud": secrets (code=InvalidArgument): POST https://kv-reginald-production.vault.azure.net/keys/pulumi-encryption-key/decrypt
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadParameter
--------------------------------------------------------------------------------
{
  "error": {
    "code": "BadParameter",
    "message": "The parameter is incorrect.\r\n"
  }
}
--------------------------------------------------------------------------------
```

I wonder if potentially `https://kv-reginald-production.vault.azure.net/keys/pulumi-encryption-key/decrypt` is the problem because I made a new version of the key so now it should be looking for `https://kv-reginald-production.vault.azure.net/keys/pulumi-encryption-key/version-number-here/decrypt` but unsure how I can test this and/or fix it.

If I use v.3.92.0 I get:

```
...
Migrating old configuration and state to new secrets provider
error: could not deserialize deployment: constructing secrets manager of type "cloud": secrets (code=InvalidArgument): keyvault.BaseClient#Decrypt: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="The parameter is incorrect.\r\n"
```

Any ideas?

**Comment by RomanDvorsky** [comment]
Hi, 

I did experience the same issue when I tried to run (my pulumi version: v3.136.0):

`pulumi stack init we.uat --secrets-provider="azurekeyvault://{keyvault key uri}"`

and the workaround which help me to solve the issue is this:

`pulumi stack init we.uat --secrets-provider="azurekeyvault://{keyvault key uri}/"`

note the backslash on the end!
