### ISSUE TITLE
Invalid or unknown key when using custom published provider: pulumi-impart

### ISSUE THREAD

**Issue by sbzimpart** [pulumi/pulumi#13205]
### What happened?

There is an issue with out custom published provider: [https://www.pulumi.com/registry/packages/impart/](https://www.pulumi.com/registry/packages/impart/)

Getting the following error when trying to run pulumi preview with some basic program using our provider:
```
    error: pulumi:providers:impart resource 'default_0_1_6_github_/api.github.com/impart-security' has a problem: could not validate provider configuration: Invalid or unknown key. Check `pulumi config get impart:pluginDownloadURL`.
```
It is unclear if something needs to fixed on the provider side or is it some bug.
Provider has been tested locally before publishing to the registry. Note that download provider works correctly. The error occurs when sdk is in use past download phase. 

### Expected Behavior

Execute preview or up without `Invalid or unknown key` error

### Steps to reproduce

- create a new pulumi project (js for this example)
- create spec.yaml file
- set env variable IMPART_TOKEN=1
- set index file to:
```
const pulumi = require("@pulumi/pulumi");
const impart2 = require("@impart-security/pulumi-impart");
const crypto = require("crypto");
const fs = require("fs");

const hashSum = crypto.createHash("sha256");
const specSource = fs.readFileSync(`./spec.yaml`).toString();

const spec = new impart2.Spec("spec", {
  name: "example_spec",
  sourceFile: "spec.yaml",
  //optional to track source files changes
  sourceHash: hashSum.update(specSource).digest("hex"),
});
```
- run `pulumi preview`

### Output of `pulumi about`

CLI          
Version      3.69.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
impart  0.1.6
nodejs  unknown

Host     
OS       debian
Version  11.7
Arch     aarch64

This project is written in nodejs: executable='/usr/local/share/nvm/versions/node/v16.20.0/bin/node' version='v16.20.0'

Current Stack: sbzimpart/pulumi_impart/impart_js

Found no resources associated with impart_js

Found no pending operations associated with impart_js

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/sbzimpart
User           sbzimpart
Organizations  sbzimpart, impart-security

Dependencies:
NAME                            VERSION
@impart-security/pulumi-impart  0.1.6
@pulumi/pulumi                  3.72.2

Pulumi locates its logs in /tmp by default

### Additional context

```

     Type                        Name                                                  Plan   
 +   pulumi:pulumi:Stack         pulumi_impart-impart_js                               create 
     └─ pulumi:providers:impart  default_0_1_6_github_/api.github.com/impart-security         


Diagnostics:
  pulumi:providers:impart (default_0_1_6_github_/api.github.com/impart-security):
    error: pulumi:providers:impart resource 'default_0_1_6_github_/api.github.com/impart-security' has a problem: could not validate provider configuration: Invalid or unknown key. Check `pulumi config get impart:pluginDownloadURL`.
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This was a [bug in the terraform bridge](https://github.com/pulumi/pulumi-terraform-bridge/issues/1169), you need to update `github.com/pulumi/pulumi-terraform-bridge/pf` to  at least v0.11.0.
