### ISSUE TITLE
`pulumi convert` requires providers to be in plugin directory

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#13219]
### What happened?

I am trying to convert an example for an MLC to other supported languages from YAML

I have the plugin binary in my `$PATH`

```
which pulumi-resource-lbrlabs-eks
/Users/lbriggs/src/github/lbrlabs/pulumi-lbrlabs-eks/bin/pulumi-resource-lbrlabs-eks

echo $PATH | awk -F ':' '/1/ {print $1}'
/Users/lbriggs/src/github/lbrlabs/pulumi-lbrlabs-eks/bin
```

When I go to run `pulumi convert` the YAML typescript code for the component provider isn't emitted

### Expected Behavior

I expected all the code to be emitted

### Steps to reproduce

See this example: https://github.com/lbrlabs/pulumi-lbrlabs-eks/tree/main/examples/yaml

Running

```
pulumi convert --language typescript --out ../ts
```

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jaxxstorm** [comment]
Note: if I copy the plugin to `~/.pulumi/plugins` it works great

**Comment by dixler** [comment]
Hey. This seems like a pretty straightforward fix. I'll add it to the bug bash.

**Comment by brandonpollack23** [comment]
Hey I just ran this locally by building the provider and setting path, this looks fixed and there is even a warning emitted about which path it is using to the provider version.
