### ISSUE TITLE
Project-scoped stacks for `local` state backend

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi#13242]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When you use `pulumi login --local` on and then create a stack for project, you end up with a flat file structure in the `stack` folder of the `.pulumi` folder. 

This leads tho the issue, that you can not reuse the stack on a different Pulumi project. That means you have to come up on your own with `namespacing` the stack names: Instead using e.g. `dev` for the  next `blabla_dev` 

It would be from huge benefit, if local state would get the same functionality like for example self managed backends like S3 buckets. https://www.pulumi.com/blog/project-scoped-stacks-in-self-managed-backend/ and have project-scoped stacks in `local` too!

**Comment by Frassle** [comment]
This is _supposed_ to work but I think our checks are getting confused by the other folders installed to ~/.pulumi as part of normal installation.

As a workaround running `pulumi state upgrade` once should fix the issue.

**Comment by dirien** [comment]
@Frassle i run the command `pulumi state upgrade` in the folder after creating the state and I got following output:

```bash
oot@fe46989649d6:/workspace/00-cluster-setup# pulumi state upgrade
This will upgrade the current backend to the latest supported version.
Older versions of Pulumi will not be able to read the new format.
Are you sure you want to proceed?
Please confirm that this is what you'd like to do by typing `yes`: yes
warning: Skipping stack "dev": no project found
Upgraded 0 stack(s) to project mode
```

And nothing changed on the `.pulumi/stack` folder

**Comment by Frassle** [comment]
What's in `~/.pulumi`?

**Comment by dirien** [comment]
@Frassle 

![image](https://github.com/pulumi/pulumi/assets/38325136/57daaecf-1d5b-4b21-a529-17633c3909aa)

**Comment by dirien** [comment]
I use a container, to be sure to have a fresh install of pulumi:

```bash
docker container run --rm -v $(pwd):/workspace --platform linux/x86_64 -ti --entrypoint=bash pulumi/pulumi:3.71.0
```

**Comment by Frassle** [comment]
That meta.yml should set any stacks made next be in project mode.

**Comment by dirien** [comment]
@Frassle got y'a! This looks different now, but the first stack is not in a folder. The second yes. 

![image](https://github.com/pulumi/pulumi/assets/38325136/d43a894a-16cc-4e8b-9892-47275c49a776)

**Comment by Frassle** [comment]
Yeh that's expected given the error you got from `upgrade`. @abhinav put in some fixes to improve that which should be in the next release, and I've just raised https://github.com/pulumi/pulumi/pull/13243 which should fix this defaulting to project mode even for `~/.pulumi`. 

I'd suggest you just manually delete those dev.json files for now and recreate with `pulumi stack init` now the meta.yaml exists.
