### ISSUE TITLE
`pulumi package get-schema ...` broken for non installed packages since v3.72.0

### ISSUE THREAD

**Issue by DSoko2** [pulumi/pulumi#13279]
### What happened?

In v3.72.0 and v3.73.0 retrieving a schema of a package that is not installed yet using `pulumi package get-schema ...` results in a panic (see below). Until v3.71.0 the behavior is that Pulumi tries to download and install the package and prints the schema, which seems to be the correct expected behavior.

```
me@d1d9c51566ed:/home/me# pulumi package get-schema aws@5.41.0
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.72.0
Go Version:       go1.20.5
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x1f7d1c0, 0x38f2110})
        /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:884 +0x213
main.schemaFromSchemaSource({0x7ffe8dd99f9f, 0xa})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/package.go:96 +0x389
main.newExtractSchemaCommand.func1(0x0?, {0xc00036e200?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/package_extract_schema.go:37 +0x35
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunFunc.func1(0x0?, {0xc00036e200?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:96 +0x26
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc0005c8900?, {0xc00036e200, 0x1, 0x1})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4c
github.com/spf13/cobra.(*Command).execute(0xc0005c8900, {0xc00036e1d0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004f00)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45
```

### Expected Behavior

`pulumi package get-schema ...` where ... is a not yet installed package should transparently download the package and print its schema. If the package cannot be found a qualified error should be shown.

### Steps to reproduce

In Pulumi CLI 3.72.0 or 3.73.0 verify that a plugin A with version V is *not* installed yet (e.g., A "aws" and V "5.41.0"). E.g., have a look that A/V is absent in `pulumi plugin ls`.

Then run:
`pulumi package get-schema A@V` 

### Output of `pulumi about`

CLI          
Version      3.72.0
Go Version   go1.20.5
Go Compiler  gc

Host     
OS       debian
Version  12.0
Arch     x86_64

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi @DSoko2 thanks a lot for filing the issue 🙏 I am able to reproduce the error and it is definitely not the intended behaviour. We will fix this as soon as possible!
