### ISSUE TITLE
Add flag to allow as much as possible of a deployment to complete even after a failure

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#13306]
There are situations when you're provisioning a Pulumi program where one resource doesn't provision successfully. There are no downstream dependencies for this resource (ie, no outputs passed to another resource) however as soon as the error is thrown, the program exits.

It would be a nice addition to be able to continue building the resource graph and optimistically create resources, then return the error at the end.

A good example of this is a helm release inside an EKS cluster.

I would imagine this would be a command like flag or env var.

**Comment by rshade** [comment]
I ran into specifically needing the kubeconfig output during a failed pulumi up, so that I could diagnose what was happening in the cluster, I had to pulumi stack export, then search for the cluster name and do it manually.

**Comment by lukehoban** [comment]
This is very similar to https://github.com/pulumi/pulumi/issues/14515, which is being addressed by https://github.com/pulumi/pulumi/pull/15740.

**Comment by justinvp** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/15740
