### ISSUE TITLE
pulumi import throws an error and doesn't generate code when importing a namespace 

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#13339]
### What happened?

This gist contains the instructions and code blocks needed to reproduce this issue:
https://gist.github.com/MitchellGerdisch/2fd73f43cffa7a4c5e1dd207835d52c0 

In a nutshell:
- Launch a k8s cluster using Pulumi (e.g. https://github.com/pulumi/examples/tree/master/aws-ts-eks)
- "manually" (i.e. use kubectl) to deploy the namespace using the manifest
- Launch another stack that instantiates the k8s provider using the kubeconfig from the first stack
- Run `pulumi import` to import the namespace using the k8sprovider from the second stack.

This will import the namespace correctly, but the codegen doesn't happen and this error is presented:
`error: anonymous.pp:14,12-20: undefined variable provider; `

### Expected Behavior

There shouldn't be an error and import code should be generated.

### Steps to reproduce

This gist has instructions and code that can be used to reproduce this:
https://gist.github.com/MitchellGerdisch/2fd73f43cffa7a4c5e1dd207835d52c0 

### Output of `pulumi about`

CLI          
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  3.30.1
nodejs      unknown

Host     
OS       darwin
Version  13.4.1
Arch     x86_64

Current Stack: org/importing/dev

TYPE                          URN
pulumi:pulumi:Stack           urn:pulumi:dev::importing::pulumi:pulumi:Stack::importing-dev
pulumi:providers:pulumi       urn:pulumi:dev::importing::pulumi:providers:pulumi::default
pulumi:pulumi:StackReference  urn:pulumi:dev::importing::pulumi:pulumi:StackReference::MitchGerdisch/aws-ts-eks-hello-world/dev
pulumi:providers:kubernetes   urn:pulumi:dev::importing::pulumi:providers:kubernetes::k8s-provider
kubernetes:core/v1:Namespace  urn:pulumi:dev::importing::kubernetes:core/v1:Namespace::new-test-namespace
kubernetes:core/v1:Namespace  urn:pulumi:dev::importing::kubernetes:core/v1:Namespace::existing-namespace

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME                VERSION
@pulumi/pulumi      3.73.0
@types/node         16.18.37
@pulumi/kubernetes  3.30.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by MitchellGerdisch** [comment]
It may be worth noting that if in the "importing" stack, I instantiate the k8s provider without specifying kubeconfig and instead just use the environment KUBECONFIG approach, I don't think I saw the error.
It only happened when I instantiated the k8s provider with a kubeconfig (retrieved from another stack in this case).

**Comment by kevinresol** [comment]
I can confirm this is happening. Importing is fine, codegen fails.

```
> pulumi about
CLI          
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  12.6
Arch     arm64
```

**Comment by justinvp** [comment]
Some more info: https://github.com/pulumi/pulumi/issues/16759#issuecomment-2244367513
