### ISSUE TITLE
Build from source fails: no required module provides package github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3

### ISSUE THREAD

**Issue by jchook** [pulumi/pulumi#13335]
### What happened?

Building from source on Linux (on both Void and Ubuntu), I have encountered this same error:

```
no required module provides package github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3; to add it:
	go get github.com/pulumi/pulumi/sdk/go/pulumi-language-go/v3
```

### Expected Behavior

Pulumi builds from source without this error.

### Steps to reproduce

This occurs for me on multiple Linux platforms. For example, in a fresh Ubuntu 22.04 VM:

1. `sudo apt-get install git python3 python3-pip`
2. Install go as described [here](https://go.dev/doc/install)
3. Install node 18 (stable), e.g. via [tj/n](https://github.com/tj/n).
4. Install `yarn` via `sudo npm i -g yarn`
5. `git clone https://github.com/pulumi/pulumi && cd pulumi`
6. `make ensure`
7. `make dist`
8. See the error.

### Output of `pulumi about`

N/A

### Additional context

The error occurs for me on v3.72.2, v3.73.0, and master.

The error did not occur on Pulumi v3.44.3.

This appears to be a regression.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Sorry for the trouble @jchook! We recently made `pulumi-language-go` it's own independent go module, and updated most of the Makefile targets to cd into the directory as required by `go install`, but missed the `dist` target. Fixed in https://github.com/pulumi/pulumi/pull/13347

**Comment by jchook** [comment]
Amazing, thank you for the fix! 

I confirmed: this change fixes the error.

It makes me curious -- does your build system not use `make dist`?

**Comment by justinvp** [comment]
> does your build system not use `make dist`?

We use GoReleaser to build the binaries that are released. We've kept the make targets mainly for local development, but I think most folks on the team use `make install` rather than `make dist` for local builds, which is why we missed updating it.
