### ISSUE TITLE
Add support for Azure OpenAI

### ISSUE THREAD

**Issue by bitsmakerde** [pulumi/pulumi#13348]
the new Azure OpenAI API is missing in the current Pulumi solution

Can you please add this?

<img width="1512" alt="image" src="https://github.com/pulumi/pulumi/assets/25720208/63d4eb52-bc18-43d0-9939-86e13a0c7876">

**Comment by lukehoban** [comment]
I believe this can be provisioned and managed via https://www.pulumi.com/registry/packages/azure-native/api-docs/cognitiveservices/deployment/.

**Comment by bitsmakerde** [comment]
@lukehoban  Thank you this works great.

**Comment by SoranaBaciu** [comment]
Hello :)

Could you provide a script snippet please?

( seams like cognitiveservices.Deployment requires an account_name - storage account?, yet when I manually create an openAI service, it is not required)
