### ISSUE TITLE
Pulumi CLI with new command on Windows hangs at prompt for project name

### ISSUE THREAD

**Issue by buchs** [pulumi/pulumi#13353]
### What happened?

I execute `pulumi login --local`.  Then I try `pulumi new <template>` with a variety of templates, like serverless-gcp-python and it prompts me for the project name, but accepts no keyboard input except Control-C. This happens in PowerShell 7 in Windows Terminal.

### Expected Behavior

Creates a new project.

### Steps to reproduce

pulumi login --local
pulumi new serverless-gcp-python  --logtostderr --logflow -v=9

### Output of `pulumi about`

$ pulumi about
CLI
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045
Arch     x86_64

Backend
Name           DESKTOP-HS0KGSQ
URL            file://~
User           AzureAD\KevinBuchs
Organizations

Pulumi locates its logs in C:\Users\KEVINB~1\AppData\Local\Temp by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from C:\Users\KevinBuchs\git\infra). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from C:\Users\KevinBuchs\git\infra). If you have not created a project yet, use `pulumi new` to do so: no project file found

### Additional context

I started on Pulumi version 3.69.0 with the failure. I upgraded to 3.74.0.

Transcript:
$ pulumi login --local
Logged in to DESKTOP-HS0KGSQ as AzureAD\<user> (file://~)
$ pulumi new serverless-gcp-python --logtostderr --logflow -v=9
This command will walk you through creating a new Pulumi project.
Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.
project name: (pulumi-test-project)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
So I gave this a go on my Windows 10 setup in the Windows terminal using powershell and it worked fine.
Does this work if you use a different terminal or shell?

**Comment by buchs** [comment]
Ok. I first tried it in a CMD shell and it worked, Then I went back to PowerShell 7 and it worked. In other words, the problem has stopped happening. I'll let the Pulumi team/processes determine if you want to just close this issue or not.
