### ISSUE TITLE
CLI does not support DeletedWith option in tests

### ISSUE THREAD

**Issue by cbley-da** [pulumi/pulumi#13355]
### What happened?

We have set up mocks for our testing.

After introducing `deletedWith` options for some resources, we get this error:
```
Error: The Pulumi CLI does not support the DeletedWith option. Please update the Pulumi CLI.
```

### Expected Behavior

Tests should work with `deletedWith`.

### Steps to reproduce

Some resources using `deletedWith`:
```
this.pgSvc = new gcp.sql.DatabaseInstance(
      logicalName,
      {
        databaseVersion: 'POSTGRES_14',
       }
    );

    const pgDB = new gcp.sql.Database(
      `db-${logicalName}`,
      {
        instance: this.pgSvc.name,
        name: 'xyz',
      },
      {
        deletedWith: this.pgSvc,
      }
    );
```

Use `setMocks({}` in tests.

### Output of `pulumi about`

```
CLI          
Version      3.72.1
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       nixos
Version  23.05 (Stoat)
Arch     x86_64

This project is written in nodejs: executable='/nix/store/p0f8i04zwf1dd66n2qkazk5x0fbsy7mp-nodejs-18.16.1/bin/node' version='v18.16.1'
```

### Additional context

Similar to the issue here: https://github.com/pulumi/pulumi-dotnet/pull/93

In https://github.com/pulumi/pulumi/blob/50e548a0b31a8ff482a99dbc780a6f7378dc4a54/sdk/nodejs/runtime/mocks.ts#L230

this should be probably changed to exclude `outputValues` just as the comment says, but return true for anything else by default.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I suspect Python and Go probably have the same issue. Should probably just align them all with what we did for dotnet.
