### ISSUE TITLE
  Unable to install resource plugin 'pulumi-resource-Azure' at version v5.44.1

### ISSUE THREAD

**Issue by Praveengitaccount** [pulumi/pulumi#13350]
### What happened?

 pulumi:providers:Azure (Azure):
    error: Could not automatically download and install resource plugin 'pulumi-resource-Azure' at version v5.44.1, install the plugin using `pulumi plugin install resource Azure v5.44.1`: error downloading provider Azure to file: failed to download plugin: Azure-5.44.1: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-Azure-v5.44.1-windows-amd64.tar.gz

### Expected Behavior

Installation of plugin 

### Steps to reproduce

C#  code,

using Pulumi.AzureNative.Resources;

    var opts = new ComponentResourceOptions
    {
        Provider = new ProviderResource("Azure", CloudProvider.Azure, Pulumi.ResourceArgs.Empty)
    };

### Output of `pulumi about`

  └─ pulumi:providers:Azure              Azure                                create

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
So firstly you probably shouldn't be creating a raw `ProviderResource`. Install the azure sdk and use the provider resource type defined in that SDK.

But if for some reason you must use the raw `ProviderResource` then be aware that package names are case-sensitive so it needs to be a lowercase "azure" not "Azure".
