### ISSUE TITLE
[Question] Is there something like pulumi2tf?

### ISSUE THREAD

**Issue by Gerrit-K** [pulumi/pulumi#13439]
This is not an issue, only a question and I'm not even sure if this would be the right place to ask, but maybe someone could help me out. 

I absolutely _love_ Pulumi in comparison to all other alternatives I've come across and tried so far. Unfortunately though at work I'm forced to provision my production resources using TFE with remote execution (so that they can apply automated policies and reject the deployment if my workload violates them). As far as I understand, this means that there's no way of using Pulumi directly for production resources, as execution happens locally in Pulumi. 

Currently the only solution I see is to move away from Pulumi and either use directly Terraform or something in between, like [CDKTF](https://github.com/hashicorp/terraform-cdk) (to generate HCL/JSON for TFE to consume). However, in my opinion neither Terraform itself nor CDKTF are as flexible and developer-friendly as Pulumi, so I was hoping: **is there any way of generating Terraform code (HCL/JSON) from Pulumi code?**

Alternatively, I appreciate any other suggestions or solutions on my particular problem. Maybe I've just missed some crucial pieces of information. Thanks!

**Comment by Frassle** [comment]
Generating hcl (or any constrained markup really) isn't possible in general given a pulumi program, and generating markup from state is extremely low fidelity.
I don't think there's anything we can meaningfully do here.
