### ISSUE TITLE
fatal error on convert

### ISSUE THREAD

**Issue by TimoKramer** [pulumi/pulumi#13440]
Hi there,
I am trying to convert an ECS deployment with tf2pulumi but it fails. Is there something I am doing wrong or is there an easy fix?

```
panic: fatal: A failure has occurred

goroutine 1 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.3.1-0.20200610172153-45a901d3e77c/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Fail(...)
	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.3.1-0.20200610172153-45a901d3e77c/go/common/util/contract/fail.go:25
github.com/pulumi/tf2pulumi/convert.convertTF12(0xc0005d8300, 0xe, 0x10, 0x10000, 0x0, 0x0, 0x1919e40, 0xc0005d0080, 0x0, 0x0, ...)
	/home/runner/work/tf2pulumi/tf2pulumi/convert/tf12.go:155 +0x1e0d
github.com/pulumi/tf2pulumi/convert.Convert(0x10000, 0x0, 0x0, 0x1919e40, 0xc0005d0080, 0x0, 0x0, 0x0, 0x18dd200, 0x2366be0, ...)
	/home/runner/work/tf2pulumi/tf2pulumi/convert/convert.go:107 +0x3d7
main.main.func1(0xc0005e62c0, 0xc000418180, 0x0, 0x4, 0x0, 0x0)
	/home/runner/work/tf2pulumi/tf2pulumi/main.go:52 +0xe6
github.com/spf13/cobra.(*Command).execute(0xc0005e62c0, 0xc0000ce010, 0x4, 0x4, 0xc0005e62c0, 0xc0000ce010)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005e62c0, 0xc00087ff50, 0x1, 0x1)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/home/runner/work/tf2pulumi/tf2pulumi/main.go:117 +0x588
```

Here is the terraform code I want to convert: https://github.com/lispyclouds/helidon-crux-api/tree/main/deploy

Version of tf2pulumi `v0.9.0`

Same error regardless of the target language I pass.

**Comment by Zaid-Ajaj** [comment]
The problem here is that this configuration variable:
```tf
variable "az_count" {
  description = "Number of AZs to cover in a given region"
  default     = "2"
}
```
Is used as a range for resources. When we translate this variable to PCL, it becomes:
```
config "azCount" "string" {
  default     = "2"
  description = "Number of AZs to cover in a given region"
}
```
which is inferred correctly as a `string` but fails on every usage site in resource range expressions where a `string` is not expected. 

Changing the terraform code to 
```tf
variable "az_count" {
  description = "Number of AZs to cover in a given region"
  default  = 2
}
```
Makes the program convert successfully for typescript.

**Comment by lukehoban** [comment]
> Changing the terraform code … makes the program convert successfully for typescript.

Note that while this is useful as a workaround, we will need to ensure that we can convert this correctly, since it is valid HCL. More specifically, we will need to support the same implicit conversions from string to number.

**Comment by Zaid-Ajaj** [comment]
As of Pulumi v3.76.0 the linked program converts to TypeScript without an error due to #13459

**Comment by Zaid-Ajaj** [comment]
As for the implicit conversions, in this case for the range expressions to be parsed as integers from strings, I've opened an #13582 to track that issue. Closing this for the time being as no longer errors during the conversion
