### ISSUE TITLE
Output[T] error message includes invalid URL

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#13461]
### What happened?

I did the bad thing with an output and a string, and got the now infamous error message.

However, the url is incorrect

### Expected Behavior

The url should be correct

### Steps to reproduce

```
Calling __str__ on an Output[T] is not supported.\n\nTo get the value of an Output[T] as an Output[str] consider:\n1. o.apply(lambda v: f\"prefix{v}suffix\")\n\nSee https://pulumi.io/help/outputs for more details.\nThis function may throw in a future version of Pulumi.
```

https://pulumi.io/help/outputs 

404s

### Output of `pulumi about`

not required

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
Looks like perhaps this regressed as part of https://github.com/pulumi/pulumi-hugo/pull/3093.
