### ISSUE TITLE
`pulumi update` against a PPC does not allow you to accept changes.

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1347]
`pulumi update` or `pulumi update --yes`, when run against a PPC simply preview the operation terminate.  The reason is that in this code:

https://github.com/pulumi/pulumi/blob/0c04770f5ee31026d16bc2ec91a9f000dec055eb/pkg/backend/cloud/backend.go#L578-L586

When running via a PPC, updateStack will return a nil ResourceChanges object, and HasChanges on that zero value returns false.

You can work around this by explicitly passing `--no-preview`.

**Comment by pgavlin** [comment]
This is no longer relevant.
