### ISSUE TITLE
Bug or feature that I can accidentally refer to prior configuration values?

### ISSUE THREAD

**Issue by alfred-stokespace** [pulumi/pulumi#13487]
### What happened?

v3.74.0

I accidentally cleared out the configuration value in my Pulimi.dev.yaml file with a particular character `]` and found that on a `up` my config.require code was not only succeeding but also feed the correct value (json string) to code.  

### Expected Behavior

I would expect that if I put a single ']' or '[' in place of previously comited/up'd configurations that it would pass the literal value through to `config.require` and not supply the previous value.

### Steps to reproduce

new project Typescript
```
import {Config} from "@pulumi/pulumi";

const config = new Config();
const sneakyValue = config.require<string>('sneakyValue')
export const myValue = sneakyValue
```
Make sure you add the config value
```
p config set sneakyValue foobarbaz
```
so your Pulumi.dev.yaml looks like ...
```
config:
  aws:region: us-gov-west-1
  pulumtest:sneakyValue: foobarbaz
```

Now do a pulumi up ...
```

     Type                 Name           Status
 +   pulumi:pulumi:Stack  pulumtest-dev  created (0.36s)


Outputs:
    myValue: "foobarbaz"

Resources:
    + 1 created

Duration: 2s
```

Okay now the interesting part, change the yaml config file,... specifically replace `foobarbaz` with either `]` or `[` NOT BOTH!
So like so ...
```
config:
  aws:region: us-gov-west-1
  pulumtest:sneakyValue: [

```
now do another pulumi up and rather then seeing your change as the export you will see the prior value.

```
     Type                 Name           Status
     pulumi:pulumi:Stack  pulumtest-dev


Outputs:
    myValue: "foobarbaz"

Resources:
    1 unchanged

Duration: 1s
```

This gets even more interesting when that value is say a complex JSON string that feeds a loop of creating EC2 instances .... which is how I originally found this issue.  I was stunned that the planner wasn't finding any different between the implications my complex JSON having been replaced with a single character and none of the related resources were being replaced.
So I thought more on it cuz... yea that's odd and added a log statement.
```
pulumi.log.info(sneakyValue)
```
as you ... mmm... wouldn't expect, but do expect now I guess ... is that pulumi log shows the original value
```
Diagnostics:
  pulumi:pulumi:Stack (pulumtest-dev):
    foobarbaz
```
despite the config being in this divergent state.

Feature? or bug?  
Honestly I like the feature, it means that I can refer to configuration state from the past?

Is it pulling config from REST API?  That would be a cool feature if it did. 

### Output of `pulumi about`

```
CLI
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
awsx    1.0.2
docker  3.6.1
nodejs  unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
I was able to repro with the above steps using TypeScript as well as Python.

It looks like this is due to:

https://github.com/pulumi/pulumi/blob/86a240362955ecf64752841d65853194ad8a9a44/pkg/cmd/pulumi/config.go#L1023-L1025

which was introduced with https://github.com/pulumi/pulumi/pull/9918.

When there is an error reading the config, it falls back to using the most recent deployed config.

In this case, the error is: `invalid YAML file: yaml: line 2: did not find expected node content`.

If the file exists but there's an error with the content, I don't think we should be doing this fallback. We should be bubbling up the error to the user, so they can fix the invalid data.

**Comment by Frassle** [comment]
> If the file exists but there's an error with the content, I don't think we should be doing this fallback. We should be bubbling up the error to the user, so they can fix the invalid data.

+1 I've always found this behavior odd. Either files or service should be authoritative about config, and if the service is authoritative then we shouldn't even bother with the files.

**Comment by Frassle** [comment]
`destroy` is an odd beast, I don't think the rules for that necessarily need to match the rules we use elsewhere.
