### ISSUE TITLE
Codegen is dropping `replaceOnChanges` within TS and Go SDKs

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#13492]
### What happened?

When [upgrading](https://github.com/pulumi/pulumi-command/pull/219) [pulumi-command](https://github.com/pulumi/pulumi-command) to the [latest codegen version](https://github.com/pulumi/pulumi/releases/tag/v3.75.0), I observed some unexpected diffs in codegen.

Specifically, I see Go and TS dropping references to `replaceOnChanges`:
- https://github.com/pulumi/pulumi-command/pull/219#discussion_r1263834731
- https://github.com/pulumi/pulumi-command/pull/219/commits/4fc50ccba8cc7417f5d4f0dc2c7237ed8093ed3e

### Expected Behavior

`replaceOnChanges` should not change without a corresponding schema change during an update. Runtime behavior should not change during an update.

### Steps to reproduce

See [upgrade PR](https://github.com/pulumi/pulumi-command/pull/219).

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
The translation from Property to PropertySpec drops this field. Easy fix but yet another point towards we ought to do https://github.com/pulumi/pulumi/issues/13080.

**Comment by iwahbe** [comment]
> The translation from Property to PropertySpec drops this field. Easy fix but yet another point towards we ought to do #13080.

Yup. Luckily we already have a bunch of schemas that exercise (theoretically) every feature of codegen: our test schemas.
