### ISSUE TITLE
Failing to create new project - pip failing to install "pulumi-azure-native"

### ISSUE THREAD

**Issue by vinicius-solon-silva** [pulumi/pulumi#13526]
When I try to create a new pulumi project, pip tries to install the "pulumi-azure-native>=1.0.0,<2.0.0" package, but fails giving this output:

error: could not create 'build\bdist.win-amd64\wheel.\pulumi_azure_native\billing\v20191001preview\list_billing_account_invoice_sections_by_create_subscription_permission.py': No such file or directory
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for pulumi-azure-native
Running setup.py clean for pulumi-azure-native
Failed to build pulumi-azure-native
ERROR: Could not build wheels for pulumi-azure-native, which is required to install pyproject.toml-based projects

**Comment by Frassle** [comment]
This looks like https://github.com/pulumi/pulumi-azure-native/issues/2463
