### ISSUE TITLE
pulumi convert to terraform errors: unknown package 'google'

### ISSUE THREAD

**Issue by geekette86** [pulumi/pulumi#13559]
### What happened?

I write 
```
pulumi convert --from terraform --language typescript --out pulumi   
```
i get this error
```
error: main.pp:0,27-68: unknown package 'google'; unknown package 'google'
warning: main.pp:42,26-63: unknown package 'google'; could not find latest version for provider google: rate limit exceeded: 403 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-google/releases/latest
```

### Expected Behavior

Convert normally the terraform

### Steps to reproduce

just type pulumi convert 

### Output of `pulumi about`

CLI          
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Pulumi locates its logs in /tmp by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from ). If you have not created a project yet, use `pulumi new` to do so: no project file found

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Looks like the same issue as https://github.com/pulumi/pulumi/issues/13552. You hit GitHub rate limits so we couldn't download the provider plugins to do the conversion mapping with.

Try installing the gcp plugin directly `pulumi plugin install resource gcp` and trying the converter again.

**Comment by geekette86** [comment]
same error and i did that before

**Comment by Frassle** [comment]
Understood, but follow along in #13552. We're not running two separate issues for the same error.
