### ISSUE TITLE
--target-dependents is not working

### ISSUE THREAD

**Issue by zweihan** [pulumi/pulumi#13557]
### What happened?

We are trying to selectively deploy resources with `--target` and `--target-dependents` flags when running `pulumi up`

### Expected Behavior

When we use the `--target-dependents` flag when running `pulumi up`, we expect pulumi to only update resources that are dependents of the selected resources with `--target`. This is not the case. 

### Steps to reproduce

Provided a repo to reproduce the issue https://github.com/zweihan/pulumi-example/tree/master/example3

The pulumi stack consists of 3 resources, the stack itself, and 2 topics. The 2 topics do not have any declared parents or `dependsOn`. 
```typescript

const testTopic1 = new gcp.pubsub.Topic("test-topic1", {});

const testTopic2 = new gcp.pubsub.Topic("test-topic2", {});

```

When we run `pulumi up --target urn:pulumi:dev::example3::gcp:pubsub/topic:Topic::test-topic1 --target-dependents`, we can see that the generated update plan also includes `test-topic-2` even though `test-topic-2` is not a dependent of `test-topic-1`. (See screenshot)

![image](https://github.com/pulumi/pulumi/assets/3874318/7bc7ce06-7afe-4501-b96b-4b621c23aa2b)

### Output of `pulumi about`

CLI          
Version      3.76.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.60.0
nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/weihan/.nvm/versions/node/v18.12.1/bin/node' version='v18.12.1'

Backend        
Name           weihan-g14
URL            file://./
User           weihan
Organizations  

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.76.0
@types/node     16.18.38
@pulumi/gcp     6.60.0

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current snapshot

### Additional context

`--target-dependents` used to be working quite well, but stopped working recently. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> --target-dependents used to be working quite well, but stopped working recently.

There was some code changes around targets recently, so that may have accidentally regressed this. Will look into it.

**Comment by Frassle** [comment]
Can repro easily in an engine test. Looking into it.

**Comment by Frassle** [comment]
So it looks like what happens is that the default provider for gcp is created regardless of targets. But that adds the provider to the list of "targeted" resources, and every gcp resource _is_ a dependent of that so then every gcp resource gets created.

I think we can handle this by making --target-dependents not follow default provider dependents.

**Comment by zweihan** [comment]
Thanks for the quick turnaround!
