### ISSUE TITLE
Cloudrunv2 get url not addressed in docs

### ISSUE THREAD

**Issue by yehudamakarov** [pulumi/pulumi#13574]
- in cloudrun v1 there is a pub sub example showing how to use the url of your service (presumably other infrastructure will call it)
- In v2 that example is gone, and there is a new set of reconciliation fields and I don't know where the url is supposed to come from. 

Any help here?

**Comment by Frassle** [comment]
I'm guessing your asking about google cloudrun here? In which case this should probably be addressed to https://github.com/pulumi/pulumi-gcp or https://github.com/pulumi/pulumi-google-native.

**Comment by yehudamakarov** [comment]
thanks, indeed that makes sense. or the documentation (unless they are separated) - see https://github.com/pulumi/pulumi-gcp/issues/1135
