### ISSUE TITLE
Default provider name generation

### ISSUE THREAD

**Issue by eBeyond** [pulumi/pulumi#13578]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
When generating the QName for an custom provider you'll use the version and the repository url from pluginDownloadURL to generate a unique QName:

`urn:pulumi:dev::infra_new::pulumi:providers:someprovider::default_0_0_83_github_/api.github.com/owner/pulumi-someprovider-native`

 This will result in a create-deploy of already existing resources. That might be viable when developing. But when running that in live it could lead to outages. There is also the way to manage it via aliases, but in this case you have to check all of them in the code. Which might be errorprone. As such I'd like to vote for handling the QName independently from the version number. May be it should be up to the developer of the custom resource to decide if there is a redeployment of a resource needed, instead of forcing it (what's currently the default)

 `urn:pulumi:dev::infra_new::pulumi:providers:someprovider::default_github_/api.github.com/owner/pulumi-someprovider-native`

### Affected area/feature
QName-Generation:
(https://github.com/pulumi/pulumi/blob/686bfe2f0443c66ae23ba1c13ebc5eea48ad2679/pkg/resource/deploy/providers/provider.go#L76)

**Comment by Frassle** [comment]
Name generation is done including the version number but this should not trigger a replacement of everything unless the provider says it should in `DiffConfig`.

The provider will be sent the old and new version in the inputs to `DiffConfig`, and it's up the provider to decide if the change of version should trigger a replacement or not. The default behavior is to ignore the version number change and report back no replacement.

**Comment by eBeyond** [comment]
I've implemented the Diff and the Update methods in the provider, but they never get called, when updating the provider. The first run, after the update looks like that:
![image](https://github.com/pulumi/pulumi/assets/380468/38bd71be-1a80-4b84-8d19-4f0899bd99a2)
There have to be a call to Diff on the resource (the first line in the diff shows "Running Diff") but it doesn't:
![image](https://github.com/pulumi/pulumi/assets/380468/70373472-bb66-4dc1-b4b2-997bc12d73c2)
When running up the next time, after changing the Diff it shows the "Running Diff". 
Even if I implement the diff method on the config (InferredConfig) it's not run. 
![image](https://github.com/pulumi/pulumi/assets/380468/c0ff31b3-b3d0-4896-8234-469591c2612c)

**Comment by eBeyond** [comment]
I've found the DiffConfig and implemented it properly. Thanks for the hint to DiffConfig on the provider which has to be replaced by a custom implementation.
