### ISSUE TITLE
Pop!_OS is not supported 

### ISSUE THREAD

**Issue by elizuck** [pulumi/pulumi#13571]
### What happened?

I ran `curl -fsSL https://get.pulumi.com | sh`  and received the output:
```
curl: (60) SSL: no alternative certificate subject name matches target host name 'get.pulumi.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
I then navigated to https://get.pulumi.com/ and received the output:
```
print_unsupported_platform()
{
    >&2 say_red "error: We're sorry, but it looks like Pulumi is not supported on your platform"
    >&2 say_red "       We support 64-bit versions of Linux and macOS and are interested in supporting"
    >&2 say_red "       more platforms.  Please open an issue at https://github.com/pulumi/pulumi and"
    >&2 say_red "       let us know what platform you're using!"
}
```

Linux version details:
```
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
```

### Expected Behavior

I expected Pulumi to be downloaded and installed

### Steps to reproduce

See the "What happened" section

### Output of `pulumi about`

`pulumi: command not found`

### Additional context

The download and install script failed, but manual installation worked

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
> curl: (60) SSL: no alternative certificate subject name matches target host name 'get.pulumi.com'

Strange. The certificate does have `*.pulumi.com`. A+ rating at https://www.ssllabs.com/ssltest/analyze.html?d=get.pulumi.com&latest
