### ISSUE TITLE
Pulumi console showing message Error Cannot read properties of undefined (reading 'hidden')

### ISSUE THREAD

**Issue by fbarrerafalabella** [pulumi/pulumi#13636]
### What happened?

This started today entering to the pulumi console to review my stacks on app.pulumi.com I keep getting the error message
```
Error
Cannot read properties of undefined (reading 'hidden')
```
<img width="394" alt="image" src="https://github.com/pulumi/pulumi/assets/97987681/bd9c2cc6-b259-42ca-8edf-bd8ffc5d87ad">

### Expected Behavior

Not get this message as before

### Steps to reproduce

Enter the pulumi console, wait a few seconds

### Output of `pulumi about`

```
pulumi about
CLI
Version      3.76.1
Go Version   go1.20.6
Go Compiler  gc

Host
OS       darwin
Version  13.4.1
Arch     x86_64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/fbarrerafalabella
User           fbarrerafalabella
Organizations  fbarrerafalabella, LinioIT
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kimberleyamackenzie** [comment]
@fbarrerafalabella Thank you for the report!  We discovered this issue earlier today, and deployed a fix that landed about ~3.5 hours ago.  If you refresh your browser, you should no longer be experiencing this issue - if that doesn't work, you may also want to clear your cache and reload.  I'm going to close this issue as fixed, but please do ping me or re-open if that refresh doesn't work for you.
