### ISSUE TITLE
Move Go SDK generated utils out of `internal` module

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#13632]
https://github.com/pulumi/pulumi/pull/13136 added explicit package versioning to the Go SDK but also re-organised the util functions into a `internal` module. This module name is special in Go and prevents other modules from accessing the code in there.

In Azure Native we have to distribute the Go SDK in multiple smaller modules due to the size limitations of Go packages. When dividing up the modules, they can no longer access the functions from the `internal` module. This is discussed in this upgrade PR: https://github.com/pulumi/pulumi-azure-native/pull/2625

## Proposal

Either:
- Revert moving the utility functions into the internal module.
- Add an option to override the name of the `internal` module so that Azure Native can use something like `utilities` instead.

**Comment by mikhailshilkov** [comment]
@dixler I believe this issue is on the Core’s plate, so we unassigned Providers folks. PTAL, ty!

**Comment by iwahbe** [comment]
I would much prefer option 2, since for most providers we want utilities to be internal.

**Comment by Frassle** [comment]
I'm fine with option two for now. Long term we want less of these language specific options, but I suspect long term we also need to support SDK splits like this properly.

**Comment by shamil** [comment]
This also affect `crd2pulumi`, when upgrading to latest SDK version. I wanted to create PR in the `crd2pulumi` repo to upgrade to Kubernets v4 provider, but the provider (4.1.0) already uses the `sdk` version that has https://github.com/pulumi/pulumi/pull/13136  .
