### ISSUE TITLE
[sdkgen/python] Building wheels with setup.py tries to install dev builds of plugins

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#13709]
When attempting to build a wheel with the following command:

```
python3 setup.py sdist bdist_wheel
```

It fails because `setup.py` contains some [code](https://github.com/pulumi/pulumi/blob/54033de4e64a9815cbf41c6e7b2dd3bf53675b73/pkg/codegen/testing/test/testdata/secrets/python/setup.py#L14-L29) that shells out to `pulumi plugin install`, and it's trying to install a dev build of a plugin that hasn't been published yet.

### Background

The purpose of shelling out to `pulumi plugin install` from `setup.py` is to have the Pulumi plugin installed at the same time that the package is installed. This works currently for source distributions published to PyPi, because `setup.py` will run when the package is installed from a source distribution.

However, when we start publishing wheels (in addition to source distributions), most users will be getting the wheel over the source distribution. Wheels have no mechanism to run arbitrary code when they are installed to be able to shell out to `pulumi plugin install`, which is going to make Python behave the same as all our other languages (except Node.js) w.r.t. plugin installation. Instead of the plugin being installed when the package installed, it'll be relying on the same mechanism the other languages rely on: before running a program, the engine asks the language host for plugins required by the program, and install those before running the program.

### Proposed Fixes

**Option 1**
I think the simplest fix is to make it so that if the flag to generate `pyproject.toml` is set, the SDK generator stops emitting the code that shells out to `pulumi plugin install` from `setup.py`. Then commands like `python3 setup.py sdist bdist_wheel` will succeed at build time. Installing from a source distribution will no longer have the `pulumi plugin install`, but that's the same behavior you'd get if installing the wheel.

**Option 2**
A potentially better solution would be to elide `setup.py` altogether if the flag is set. You'd then be more reliant on the `pyproject.toml` for building the source distribution and wheel, using a command like `python3 -m build` or `python3 --use-pep517 -m pip wheel .`. However, I believe this will require updates to the generated `pyproject.toml` to ensure files like `py.typed` and `pulumi-plugin.json` are included in the generated source distribution and wheel. We may also need to emit a `[build-system]` in the generated `pyproject.toml` per https://packaging.python.org/en/latest/tutorials/packaging-projects/#creating-pyproject-toml.

**Comment by t0yv0** [comment]
We also need something like this to satisfy a customer ask and transition K8S and other provers to pyproject.toml

Currently trying this out: https://github.com/pulumi/pulumi-kubernetes/pull/2531 starting with Option 2.

**Comment by t0yv0** [comment]
I'd like to keep this open until https://github.com/pulumi/pulumi/pull/13812 is integrated which actually makes it possible to build usable wheels. The "tries to install dev builds of plugins" bit is only one of the obstacles to that end.
