### ISSUE TITLE
`config.Require()` unmarshal **not** secret into secret if the string contains secret

### ISSUE THREAD

**Issue by budimanjojo** [pulumi/pulumi#13734]
### What happened?

I have set a secret with a value of "testing": `pulumi config set --path --secret something[0].value testing`
I set another value that is not secret that include "testing" in the value: `pulumi config set something2 just-testing`

Now, if I have code like this in my `main.go`:
```
package main

import {
    "fmt"
    "github.com/pulumi/pulumi/sdk/v3/go/pulumi"
    "github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func main() {
    pulumi.Run(func(ctx *pulumi.Context) error {
        test := config.Require(ctx, "something2")
        fmt.Println(test)
        return nil
    })
}
```
And I run `pulumi up`, the output will be like this:
```
Diagnostics:
  pulumi:pulumi:Stack (test-dev):
    just-[secret]
```

### Expected Behavior

The output shouldn't be `just-[secret]` because it's not a secret. I have also tested with `config.RequireObject()` and the problem is also happening there.

### Steps to reproduce

Explained above.

### Output of `pulumi about`

```
CLI
Version      3.76.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
github  5.3.0
go      unknown

Host
OS       nixos
Version  23.11 (Tapir)
Arch     x86_64

This project is written in go: executable='/etc/profiles/per-user/budiman/bin/go' version='go version go1.20.6 linux/amd64'

Current Stack: budimanjojo/test/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/budimanjojo
User           budimanjojo
Organizations  budimanjojo

Dependencies:
NAME                                    VERSION
github.com/pulumi/pulumi-github/sdk/v5  5.3.0
github.com/pulumi/pulumi/sdk/v3         3.51.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Hi @budimanjojo, this is actually by-design. All secret values will be masked when logged.

```
pulumi config set --path --secret something[0].value testing
```

This is saying that the value `"testing"` is a secret value.

Any time you try to write out the string `"testing"`, the logger will automatically mask it as `[secret]`.

```go
test := config.Require(ctx, "something2")
fmt.Println(test)
```

The value of `test` will be the string `"just-testing"`. It itself is not a secret. But when writing out `"just-testing"`, the `testing` part of that string is masked in the output.

The same would happen if you wrote out:

```go
fmt.Println("testing testing testing")
```

The output would be:

```
Diagnostics:
  pulumi:pulumi:Stack (secs-dev):
    [secret] [secret] [secret]
```

**Comment by budimanjojo** [comment]
Okay if that's by design, maybe have it mentioned in the doc? My concern is that people can now guess my secret based on the output of non secret stuffs although my prod secret string shouldn't be just "testing" but it's worth knowing beforehand.
