### ISSUE TITLE
Python SDK 3.78.1 requirements are out of sync

### ISSUE THREAD

**Issue by AniX** [pulumi/pulumi#13738]
### What happened?

In requirements.txt, Snyk has changed the pinned version of grpcio from 1.56.0 to exactly 1.56.2: see [commit](https://github.com/pulumi/pulumi/commit/8f8f30eeb8f66e08830968b659f81fb5df419e43)

However, it seems that `setup.py` still references the vulnerable version `==1.56.0` (no patch versions allowed), see [here](https://github.com/pulumi/pulumi/blob/46e2753d02d46a1c077930eeccdfe6738f46c0d2/sdk/python/lib/setup.py#L47C12-L47C26)

Pulumi 3.78.1 was released with this conflict, and it looks like the older version in `setup.py` takes precedence in poetry, which is why I can't fix the vulnerability in our dependencies without a version conflict in pulumi.

### Expected Behavior

Both, `setup.py` and `requirements.txt` should have no conflict in the required version of `grpcio`.

### Steps to reproduce

In `pyproject.toml` of my-app

```
grpcio = "^1.56.2"
pulumi = "^3.78.1"
```

Then run `poetry lock`:

```
Updating dependencies
Resolving dependencies... (1.2s)

Because pulumi (3.78.1) depends on grpcio (1.56.0)
 and no versions of pulumi match >3.78.1,<4.0.0, pulumi (>=3.78.1,<4.0.0) requires grpcio (1.56.0).
So, because my-app depends on both grpcio (^1.56.2) and pulumi (^3.78.1), version solving failed.
```

### Output of `pulumi about`

n/a

### Additional context

I'm not sure it's necessary to maintain two dependency lists. At least one of them should allow higher patch versions (typically `setup.py`, e.g. `grpcio~=1.56.0`).

In case your project requirements allow it, you may want to consider using `poetry` with all dependencies just in `pyproject.toml` and not in `setup.py`. IIRC, Snyk bot can also fix dependencies in `pyproject.toml` files and then you don't need to sync anything manually.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hello @AniX thanks a lot for filing the issue and for digging into it ❤️ we really appreciate that 🙏. I've raised #13759 to fix this issue and will be publishing a new version today hopefully. 

Using poetry for our SDK would probably have prevented such issue, we have looked into using poetry for our generated provider SDKs so it is probably a good idea to use it for the main python SDK as well 😄
