### ISSUE TITLE
cloning templates repo: reference not found

### ISSUE THREAD

**Issue by Matrix-Zhang** [pulumi/pulumi#13739]
### What happened?

every time run pulumi new, it returns
```
cloning templates repo: reference not found
```

### Expected Behavior

show templates 

### Steps to reproduce

```
pulumi new
```

### Output of `pulumi about`

```
CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Host     
OS       debian
Version  bullseye/sid
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/Matrix-Zhang
User           Matrix-Zhang
Organizations  Matrix-Zhang
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Same error as in #12277, but that was on Windows.

As a workaround, @Matrix-Zhang, could you try deleting the the `~/.pulumi/templates` directory and re-running `pulumi new`?
