### ISSUE TITLE
Review added at repo-reviews.github.io

### ISSUE THREAD

**Issue by repo-reviews** [pulumi/pulumi#13735]
### Thank you for building **pulumi**!

@repo-reviews created a review titled:

*OSS is good alternative to Terraform*

on [repo-reviews.github.io](https://repo-reviews.github.io) to share their experience using **pulumi**.

[link to review](https://repo-reviews.github.io//reviews/2023-08-18_repo-reviews_pulumi_pulumi)

If you would like to help your super-users share their experiences using your repo, add a [badge](https://github.com/repo-reviews/repo-reviews.github.io#add-badges) to your README.md.

We hope that sharing these experiences helps your users **increase their productivity**.

--
Please be kind,
I’m a human!

**Comment by lukehoban** [comment]
Thanks for the pointer to the review!  We won’t add the badge at this time.
