### ISSUE TITLE
C# generated program calls non-existent Invoke

### ISSUE THREAD

**Issue by erwinkramer** [pulumi/pulumi#13751]
### What happened?

Following the tutorial here for c#: https://www.pulumi.com/registry/packages/azuread/api-docs/getclientconfig/. But `var current = AzureAD.GetClientConfig.Invoke();` will never work, since https://github.com/pulumi/pulumi-azuread/blob/8419bec8e7900246a8f23a676c9f8357a45ae43c/sdk/dotnet/GetClientConfig.cs#L12 only exposes InvokeAsync. 

Also, on https://www.pulumi.com/registry/packages/azuread/api-docs/getclientconfig/, again the c# sample, it specifies : `["objectId"] = current.Apply(getClientConfigResult => getClientConfigResult.ObjectId)`, this also doesn't work because it assumes a non-async result, instead, something like this works fine: `["objectId"] = current.Result.ObjectId`

### Edit: Triage Investigation

In the AzureAD provider there's an invoke called `GetClientConfig` which has no inputs - only an output. In the C# codegen we skip the `genFunctionOutputVersion` (`.Invoke()`):
- https://github.com/pulumi/pulumi/blob/7815e0383d98e18c0810794251de2685f4ac8070/pkg/codegen/dotnet/gen.go#L1544-L1549

This is due to `NeedsOutputVersion` returning false because the inputs are nil. We only generate `.InvokeAsync()`:
- https://github.com/pulumi/pulumi/blob/7815e0383d98e18c0810794251de2685f4ac8070/pkg/codegen/schema/schema.go#L553-L576

It appears that the example generation code does not have the exact same criteria of selecting either `Invoke()` or `InvokeAsync()`. Possible call sites I can see:
- https://github.com/pulumi/pulumi/blob/7815e0383d98e18c0810794251de2685f4ac8070/pkg/codegen/dotnet/gen_program_expressions.go#L458
- https://github.com/pulumi/pulumi/blob/7815e0383d98e18c0810794251de2685f4ac8070/pkg/codegen/dotnet/gen_program_expressions.go#L526-L530

### Expected Behavior

Should work on MY machine 

### Steps to reproduce

Try the tutorial!

### Output of `pulumi about`

CLI
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME     VERSION
azuread  5.40.0
dotnet   unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='8.0.100-preview.7.23376.3'

Current Stack: NO/yolo/dev

TYPE                       URN
pulumi:pulumi:Stack        urn:pulumi:dev::yolo::pulumi:pulumi:Stack::yolo-dev
pulumi:providers:azuread   urn:pulumi:dev::yolo::pulumi:providers:azuread::default_5_40_0
azuread:index/group:Group  urn:pulumi:dev::yolo::azuread:index/group:Group::example

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/NO
User           NO
Organizations  NO

Dependencies:
NAME            VERSION
Pulumi          3.56.0
Pulumi.AzureAD  5.40.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi @erwinkramer I believe this issue is resolved by https://github.com/pulumi/pulumi/pull/13669 which will allow generating invokes for functions without inputs (`GetClientConfig` in this case). It is possible that the current version of the SDK you are using (Pulumi 3.56.0 and Pulumi.AzureAD 5.40.0) do not have this functionality yet. That means they will be added soon in the upcoming update cycles. 

That said, I think we can close this issue. Program-gen does indeed assume output-versioned invokes to be available in the SDK and #13669 will ensure that. 

Thanks again for filing the issue and for the detailed report. If you have any questions, please feel free to ask. We are here to help 😄
