### ISSUE TITLE
Go codegen regression:  input arrays replaced with args arrays

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi#13758]
For instance, expected: `corev1.ContainerArray`, actual: `[]corev1.ContainerArgs`. This is a regression from #7059, part of the ones tracked by #7735.

This causes a number if examples in azure-native to be incorrect:
- pulumi/pulumi-azure-native#2275
- pulumi/pulumi-azure-native#2047
- pulumi/pulumi-azure-native#1619
- pulumi/pulumi-azure-native#1578
- https://github.com/pulumi/pulumi-azure-native/issues/1479

**Comment by thomas11** [comment]
I captured the .pp (`hcl2/model.Body`) of the 2275 case (PrivateEndpoint) from a debug session:

```
resource privateEndpoint "azure-native:network/v20230201:PrivateEndpoint" {
    customNetworkInterfaceName = "testPeNic"
    ipConfigurations = [{
        groupId = "file",
        memberName = "file",
        name = "pestaticconfig",
        privateIPAddress = "192.168.0.6"
    }]
    location = "eastus2euap"
    privateEndpointName = "testPe"
    privateLinkServiceConnections = [{
        groupIds = ["groupIdFromResource"],
        privateLinkServiceId = "/subscriptions/subId/resourceGroups/rg1/providers/Microsoft.Network/privateLinkServices/testPls",
        requestMessage = "Please approve my connection."
    }]
    resourceGroupName = "rg1"
    subnet = {
        id = "/subscriptions/subId/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/myVnet/subnets/mySubnet"
    }
}
```

**Comment by Zaid-Ajaj** [comment]
Closing as fixed, trying out all the examples in the mentioned issues, it seems that it is resolved. Take any of YAML example and convert to it to go to using `pulumi convert --language go` you will that we no longer get the `[]` syntax.
