### ISSUE TITLE
SuppressPluginInstall option for Node and Python

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#13754]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Client request: On our side we would rather have consistent behavior across all client SDKs - no attempts to install plugin when client SDK package installed. Can you add a flag to Language specific section for Python and NodeJS that allow suppress generating logic to install plugin during package install?

Languages:
- Node
- Python

Related: https://github.com/pulumi/pulumi/issues/13709

**Comment by Frassle** [comment]
My opinion is we should just remove these entirely rather than adding an option.
