### ISSUE TITLE
Undo change that started requiring all Pulumi Schemas to include Go-specific `importBasePath`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#13756]
It appears that as of https://github.com/pulumi/pulumi/pull/13136, all Pulumi Schema must include the `importBasePath` option in the `language.go.importBasePath` section.

Without that, the generated Go SDK fails to build with a very esoteric:

```bash
package github.com/pulumi/pulumi-rke/sdk/v3/go/rke
        imports internal: no Go files in /opt/homebrew/Cellar/go/1.20.4/libexec/src/internal
```

This is because without this section, the following codegen change appears:

```patch
diff --git a/sdk/go/rke/init.go b/sdk/go/rke/init.go
index 7219a91..b92febe 100644
--- a/sdk/go/rke/init.go
+++ b/sdk/go/rke/init.go
@@ -7,8 +7,8 @@ import (
 	"fmt"
 
 	"github.com/blang/semver"
-	"github.com/pulumi/pulumi-rke/sdk/v3/go/rke/internal"
 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
+	"internal"
 )
```

This was not required prior to https://github.com/pulumi/pulumi/pull/13136, and adds new burden for every package author.  Ideally we can remove the need for every author to explicitly specify this.

**Comment by justinvp** [comment]
@AaronFriel, @guineveresaenger, @abhinav, @Frassle, any ideas on how to enable the versioning approach in #13136 without this regression?

**Comment by AaronFriel** [comment]
I don't have a suggestion that doesn't entail other compromises, and would instead suggest that we make a missing `importBasePath` a warning for a period of time, with it being required in a future specific version. 

In the mean time, we return to generating a utilities file per directory; this leads to significant code duplication; and to support Azure-Native, the exports will need to be public, polluting the top level namespace and the namespace of every sub-package; even one-resource packages will have several additional symbols. That's precisely what we wanted to avoid, but I think it's required here.

-----

As this is a Go library and not a binary, it precludes using `go.mod` replacements or ldflags. `//go:linkname` also requires full import paths, so no linker shenanigans.

`pulumi-plugin.json` embedding doesn't improve the situation: `//go:embed` cannot embed parent or relative paths, only child paths of the current package, so we would need to create a `pulumi-plugin.json` in **every directory**.

I also think there are several arguments for requiring an `importBasePath`

* Its absence prevents other improvements to Go codegen, as Go lacks relative path imports. No package we generate can reference any other package, contrast this with our other SDKs, where we can import utility methods from relative paths in [node](https://github.com/pulumi/pulumi-aws/blob/9b14ba69d12fd30ad570510b420ee4edfeefe7bb/sdk/nodejs/account/index.ts#L5C1-L5C43), [python](https://github.com/pulumi/pulumi-aws/blob/9b14ba69d12fd30ad570510b420ee4edfeefe7bb/sdk/python/pulumi_aws/acm/certificate.py#L10), [dotnet](https://github.com/pulumi/pulumi-aws/blob/9b14ba69d12fd30ad570510b420ee4edfeefe7bb/sdk/dotnet/Acmpca/Certificate.cs#L108-L115).
* Without an `importBasePath`, two resources in different packages (Pulumi nomenclature: modules) cannot reference the same type: they have to be duplicated types. Likewise, hybrid resource and component provider cannot contain references from one package to another, so a component defined in one package (Pulumi module) cannot have as its inputs or outputs a resource defined in another package.
* Requiring the schema file to contain package names for all languages supported can be used to improve the Registry, lacking an `importBasePath` means we could not, for example, generate automatic links to the package, resources, or args types on pkg.go.dev.

**Comment by blampe** [comment]
We should be able to set a reasonable default for `importBasePath` based on the provider's module, which is known.

The provider binary embeds its module path and can be read by [buildinfo.Read](https://pkg.go.dev/debug/buildinfo#Read) (under the "mod" key). We can emit that as part of the JSON schema with [debug.ReadBuildInfo](https://pkg.go.dev/runtime/debug@go1.22.1#ReadBuildInfo), so gen-sdk has the information available from all sources.

```
❯ go version -m bin/pulumi-resource-xyz
bin/pulumi-resource-xyz: go1.21.5
	path	github.com/pulumi/pulumi-xyz/provider/cmd/pulumi-resource-xyz
	mod	github.com/pulumi/pulumi-xyz/provider	(devel)
    ...
```

Given the provider's module path, `importBasePath` (the SDK's path) can then default to `filepath.Join(providerPath, "../sdk")`. This matches the structure of our existing providers and our templates.
