### ISSUE TITLE
Pulumi stack rename confusion

### ISSUE THREAD

**Issue by interurban** [pulumi/pulumi#13771]
Feedback from Docs Control
https://www.pulumi.com/docs/cli/commands/pulumi_stack_rename/

It is not clear how to rename a project.

My state is:
     Type                                        Name                                                                            Status
     pulumi:pulumi:Stack                         root-prod

and so I figured maybe all I need to do is rename the stack.

The stack name is `prod` but shown as `root-prod` here. Which is confusing.

How do I rename it?

The Notes also don't really clear things up. Specifically the "For now, if you don't want these change

**Comment by interurban** [comment]
I was chatting w/ @jkodroff ; This text is a bit confusing and also doesent reflect the potential use of Alisas; a suggestion:

It could say something like:

NOTE: If you are using the name of the current stack in the name of any resources, renaming the stack necessarily will cause Pulumi to recreate the resource. To rename the stack without recreating affected resources, use an [alias]().

**Comment by dixler** [comment]
Hey, thanks for forwarding this.

> It is not clear how to rename a project.

To my knowledge you can't rename a project without recreating it. If you want to do this, you can edit the `Pulumi.yaml` file and change the `name` field to the desired new project name.

> The stack name is prod but shown as root-prod here. Which is confusing.

`root` is the project name. `prod` is the stack name.

The stack resource is named by taking `${projectName}-${stackName}` hence `root-prod`.

The top-level stack resource is managed by Pulumi and you're not intended to operate on it.

Let me know if there are further questions.
