### ISSUE TITLE
Unexpected error "Call is not yet implemented"

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#13777]
Regression detected updating from 3.75 (July 12th release) to 3.78.1

Looks like the error comes from here:

https://github.com/pulumi/pulumi/blob/baf7dcc180b0240eee15bc14d74f59a4b5a7a665/pkg/resource/provider/component_provider.go#L131

Stack trace starts here: 

https://github.com/pulumi/pulumi/blob/9b39af3a4cf0508dc623b7ac9357beeacaddf90d/sdk/nodejs/runtime/invoke.ts#L301

**Comment by justinvp** [comment]
More details: Customer upgraded the Go SDK for their provider from 3.75 to 3.78.1 (pulumi sdk/pkg).

The provider exposes a method on a resource. Calling the method from a Go or Python program continues to work. Calling the method from Node.js results in an error:

```
         [stdout]  2023-08-24 18:56:43 INFO         <ref *1> Error: call of myprovider:foo/MyResource/myMethod returned an error: Call is not yet implemented 
         [stdout]  2023-08-24 18:56:43 INFO             at Object.callback (/tmp/node_modules/@pulumi/runtime/invoke.ts:301:45) 
         [stdout]  2023-08-24 18:56:43 INFO             at Object.onReceiveStatus (/tmp/node_modules/@grpc/grpc-js/src/client.ts:360:26) 
         [stdout]  2023-08-24 18:56:43 INFO             at Object.onReceiveStatus (/tmp/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34) 
         [stdout]  2023-08-24 18:56:43 INFO             at Object.onReceiveStatus (/tmp/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48) 
         [stdout]  2023-08-24 18:56:43 INFO             at /tmp/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24 
         [stdout]  2023-08-24 18:56:43 INFO             at processTicksAndRejections (node:internal/process/task_queues:77:11) { 
         [stdout]  2023-08-24 18:56:43 INFO           promise: Promise { <rejected> [Circular *1] } 
```

Haven't confirmed the CLI version, but likely recent 3.75/3.76.

**Comment by justinvp** [comment]
This may also be coming from here somehow:

https://github.com/pulumi/pulumi/blob/7a74a929723799d3a09edac773c15fb37b6d6883/sdk/go/common/resource/plugin/provider_unimplemented.go#L94
