### ISSUE TITLE
[critical bug] Pulumi is wiping out unique gcp.projects.IAMBindings in a different (production) stack

### ISSUE THREAD

**Issue by rosskevin** [pulumi/pulumi#13799]
### What happened?

- We are trying to raise two identical sets of stacks, but different names (blue|green).  
- These are targeting the same GOOGLE_CLOUD_PROJECT
- Each resource is uniquely named (pictured below), names consist of stack name and base name
- Each urn for each resource is unique
- up green - all good (at this point)
- up blue - blue's resources are all good, BUT green's accounts now have ALL of their IAM bindings wiped (service accounts remain)
- up green shows no changes (even though ~members) are missing

![stack-conflict-iambinding](https://github.com/pulumi/pulumi/assets/136564/23000419-995d-4ea1-a435-63d69d6a49ba)

### Expected Behavior

One stack has absolutely zero interaction with the uniquely named resources from another stack, whether they target the same GOOGLE_CLOUD_PROJECT or not.

### Steps to reproduce

- `pulumi init stack org/green`
- `pulumi init stack org/blue`
- `pulumi stack select org/green`
- `pulumi up` - observe the green principal and assigned roles at https://console.cloud.google.com/iam-admin/iam
- `pulumi stack select org/blue`
- `pulumi up` - observe the blue principal and assigned roles  in the gcp console, and NOTE that the green ones have disappeared
- Visit https://console.cloud.google.com/iam-admin/serviceaccounts to see that the green serveci accoutns still exist
- `pulumi stack select org/green`
- `pulumi up` - note it sees zero changes, even though the `~members` are now missing

Attached are two files, one to create the `app` identity, and the other that is `Identity.ts` that is the reused library code.

`app.ts`

```ts
import { Identity } from '@alienfast/pulumi-gcp'

import { project } from './gcp'
import { gcpProvider } from './gcpProvider'

export const app = new Identity(
  'app',
  {
    project,
    iamRoles: [
      // for deploying new services/deployments
      'roles/container.developer',
      // for pushing new images to gcr
      'roles/storage.admin',
      //----------------------
      // for preview on infrastructure - need to get current version - no escalated container permissions allowed here
      'roles/container.clusterViewer',
      'roles/container.viewer',
      'roles/viewer',
    ],
  },
  gcpProvider(),
)
```

`Identity.ts`

```ts
import { upperCaseFirstLetter } from '@alienfast/common'
import * as gcp from '@pulumi/gcp'
import { ComponentResource, ComponentResourceOptions, Output } from '@pulumi/pulumi'
import { getStack } from '@pulumi/pulumi/runtime'
import { camelCase, kebabCase } from 'lodash-es'

export interface IdentityArgs {
  readonly iamRoles?: string[]
  readonly project: string
}

/**
 *
 * @see https://cloud.google.com/iam/docs/understanding-roles
 * @see https://cloud.google.com/kubernetes-engine/docs/how-to/iam
 */
export class Identity extends ComponentResource {
  public account!: gcp.serviceaccount.Account
  public key!: gcp.serviceaccount.Key
  public secret!: Output<string>
  public iamBindings: gcp.projects.IAMBinding[] = []

  constructor(nameArg: string, args: IdentityArgs, opts: ComponentResourceOptions) {
    const name = `${nameArg}${upperCaseFirstLetter(getStack() || '')}` // appBlue
    super('af:pulumi:gcp:Identity', name, {}, opts)
    const { iamRoles, project } = args

    console.log('creating service account:', name)
    this.account = new gcp.serviceaccount.Account(
      name,
      {
        project,
        accountId: kebabCase(name),
        displayName: kebabCase(name),
      },
      { parent: this },
    )

    if (iamRoles) {
      for (const role of iamRoles) {
        let bindingName = camelCase(role.replace('roles/', ''))
        bindingName = `${name}${upperCaseFirstLetter(bindingName)}` // appBlueViewer

        console.log('creating role binding:', bindingName, '=>', role)
        this.iamBindings.push(
          new gcp.projects.IAMBinding(
            bindingName,
            {
              project, //required, not inferred
              role,
              members: [this.account.email.apply((email) => `serviceAccount:${email}`)],
            },
            { parent: this, dependsOn: [this.account] },
          ),
        )
      }
    }

    this.key = new gcp.serviceaccount.Key(
      `${name}Key`,
      { serviceAccountId: this.account.name },
      { parent: this },
    )

    this.registerOutputs({
      account: this.account,
      key: this.key,
      iamBindings: this.iamBindings,
      secret: this.secret,
    })
  }
}
```

### Output of `pulumi about`

CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in nodejs: executable='/Users/kross/n/bin/node' version='v18.10.0'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/rosskevin
User           rosskevin
Organizations  rosskevin, alienfast

Pulumi locates its logs in /var/folders/cn/kwy_3rrd5nv3qqs5h2zy8t280000gn/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /Users/kross/projects/archetype/cloud/identity/yarn.lock or /Users/kross/projects/archetype/cloud/identity/package-lock.json
warning: Failed to get information about the current stack: No current stack

### Additional context

This is a *CRITICAL* bug, caused a production outage.  As we tried to raise a totally independently named set of stacks, with the `identity` stack being the first to come up, immediately *PRODUCTION* *SYSTEMS* *WENT* *DOWN*.

Please excuse the bold all caps, but we were shocked and thought we were operating entirely independently and safely from the production set of resources.  I'm not saying it's impossible that this is _my_ bug, it certainly could be user error but I cannot spot it.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rosskevin** [comment]
I'm working on a reproduction repo.

**Comment by jaxxstorm** [comment]
I worked with on this via community slack, I believe this is a side effect of `gcp.project.IAMBinding`

https://www.pulumi.com/registry/packages/gcp/api-docs/projects/iambinding/

> Authoritative for a given role. Updates the IAM policy to grant a role to a list of members. Other roles within the IAM policy for the project are preserved.

**Comment by rosskevin** [comment]
Closing (unless I find this information incorrect).  @jaxxstorm indicated on slack that I am misusing IAMBinding and want IAMMember.

**Comment by rosskevin** [comment]
Since slack messages will disapear in the future:

@jaxxstorm Confirmed user error.  Switching `IAMBinding` (authoritative) to `IAMMember` works.  Thank you for the pointer!

**Comment by rosskevin** [comment]
@jaxxstorm I want to note that `IAMBinding` is used in the GCP crosswalk example, and that's likely where I got it from some years ago.  It is probably best to change it, or minimally put a series warning by it: https://github.com/pulumi/kubernetes-guides/blob/master/gcp/01-identity/util.ts#L24
