### ISSUE TITLE
--target-dependents still not working

### ISSUE THREAD

**Issue by zweihan** [pulumi/pulumi#13818]
### What happened?

I raised the same [issue](https://github.com/pulumi/pulumi/issues/13557) previously. 

There was a fix that was merged and released. However, as of `v3.79.0` it still seems like `--target-dependents` is still not working.

### Expected Behavior

--target-dependents should only update changes which are actually dependents. 

### Steps to reproduce

The repro is in #13557.

### Output of `pulumi about`

```
CLI          
Version      3.79.0
Go Version   go1.21.0
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.60.0
nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/weihan/.nvm/versions/node/v18.12.1/bin/node' version='v18.12.1'

Backend        
Name           weihan-g14
URL            gs://arbo-pulumi-backend
User           weihan
Organizations  

Dependencies:
NAME            VERSION
@pulumi/gcp     6.60.0
@pulumi/pulumi  3.76.0
@types/node     16.18.38
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
We're aware, its being tracked as https://github.com/pulumi/pulumi/issues/13591.
