### ISSUE TITLE
Native Poetry support for Python projects

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#13833]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi Python projects support a `virtualenv` option, the path to a virtual environment to use. If the specified directory does not exist, Pulumi will use Python's built-in [`venv`](https://docs.python.org/3/library/venv.html) module to create a virtual environment and install dependencies into that virtual environment, and run the Pulumi program using the `python` executable in that virtual environment.

There are other popular tools in the Python ecosystem for managing virtual environments, such as Poetry, pyenv, and pipenv. While it is possible to use Poetry with Pulumi today (either without the `virtualenv` option in `Pulumi.yaml` specified, or point it to Poetry's virtual environment directory), it would be ideal if there was a way to specify that Poetry should be used over `venv` for managing and installing a project's dependencies.

This was explored in @kpitzen's hackathon project: https://github.com/pulumi/pulumi/pull/10884, which adds a `toolchain` option for specifying poetry.

Additionally, it would be nice if the solution was applicable to other languages. For example, today, for Node.js, the built-in tool for managing project dependencies is `npm`, but this can be overridden to use `yarn` via `PULUMI_PREFER_YARN` envvar, and https://github.com/pulumi/pulumi/pull/13055 adds a similar envvar for support PNPM.

Ideally, we'd have a much better user experience for this. For example, when running `pulumi new`, it could prompt the user for which package manager tool to use, based on what the language host can support and finds available on `$PATH`. Even nicer if it saved the user's choice as a default value to use for subsequent runs of `pulumi new`.

**Comment by julienp** [comment]
Shipped with https://github.com/pulumi/pulumi/issues/15937
