### ISSUE TITLE
Dynamic Resource Provider hangs if it runs beyond ~180 seconds

### ISSUE THREAD

**Issue by cecil-aw** [pulumi/pulumi#13841]
### What happened?

I've created a custom provider to invoke a lambda (AWS) which runs a process that builds a Lex bot. For now, it does not actually build a bot, but the lambda simply sleeps to simulate time it would take for the process to complete. If I keep the sleep time below 180 seconds, it works fine. If I set the sleep time higher, the dynamic resource status simply states 'updating' and the seconds counter continues to climb. It continues this state until I ctrl-c out of the pulumi up. I've let it run at least 2300 seconds before doing ctrl-c.

### Expected Behavior

The dynamic provider should complete approximately at the amount of time from the lambda sleep, but it does not (if I set the sleep beyond ~180 seconds).

### Steps to reproduce

1. create a simple lambda that sleeps a given amount of time based on the event data passed to it.
2. create a dynamic provider which will invoke this lambda (via create and update functions), passing in a payload which includes the amount of time to sleep. (this could be hardcoded to simply testing)
3. pulumi up and watch the dynamic provider create/update status. It should complete in the amount of time specified by the sleep time set.

### Output of `pulumi about`

CLI
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
python  unknown

Host
OS       darwin
Version  13.5
Arch     arm64

This project is written in python: executable='/Users/cecil.patterson/.python3.10/bin/python3' version='3.10.12
'

Current Stack: archway/pulumi-test/cecil-test-stack

TYPE                                       URN
pulumi:pulumi:Stack                        urn:pulumi:cecil-test-stack::pulumi-test::pulumi:pulumi:Stack::pulumi-test-cecil-test-stack
pulumi:providers:aws                       urn:pulumi:cecil-test-stack::pulumi-test::pulumi:providers:aws::default
pulumi:providers:aws                       urn:pulumi:cecil-test-stack::pulumi-test::pulumi:providers:aws::default_5_42_0
aws:cloudwatch/logGroup:LogGroup           urn:pulumi:cecil-test-stack::pulumi-test::aws:cloudwatch/logGroup:LogGroup::/aws/lambda/pulumi-test-dev-build-lambda
aws:cloudwatch/logGroup:LogGroup           urn:pulumi:cecil-test-stack::pulumi-test::aws:cloudwatch/logGroup:LogGroup::/aws/lambda/pulumi-test-dev-lambda
aws:iam/role:Role                          urn:pulumi:cecil-test-stack::pulumi-test::aws:iam/role:Role::pulumi-test-dev-lambda-role
aws:iam/role:Role                          urn:pulumi:cecil-test-stack::pulumi-test::aws:iam/role:Role::pulumi-test-dev-build-lambda-role
aws:iam/policy:Policy                      urn:pulumi:cecil-test-stack::pulumi-test::aws:iam/policy:Policy::pulumi-test-dev-lambda-policy
aws:iam/policy:Policy                      urn:pulumi:cecil-test-stack::pulumi-test::aws:iam/policy:Policy::pulumi-test-dev-build-lambda-policy
aws:lambda/function:Function               urn:pulumi:cecil-test-stack::pulumi-test::aws:lambda/function:Function::pulumi-test-dev-build-lambda
aws:iam/policyAttachment:PolicyAttachment  urn:pulumi:cecil-test-stack::pulumi-test::aws:iam/policyAttachment:PolicyAttachment::bot-lambda-policy-attach-dev
aws:iam/policyAttachment:PolicyAttachment  urn:pulumi:cecil-test-stack::pulumi-test::aws:iam/policyAttachment:PolicyAttachment::build-lambda-policy-attach-dev
aws:lambda/function:Function               urn:pulumi:cecil-test-stack::pulumi-test::aws:lambda/function:Function::pulumi-test-dev-lambda
pulumi:providers:pulumi-python             urn:pulumi:cecil-test-stack::pulumi-test::pulumi:providers:pulumi-python::default
pulumi-python:dynamic:Resource             urn:pulumi:cecil-test-stack::pulumi-test::pulumi-python:dynamic:Resource::pulumi-test-dev-lex-bot

Found no pending operations associated with cecil-test-stack

Backend
Name           pulumi.com
URL            https://app.pulumi.com/cecil-aw-pulumi
User           cecil-aw-pulumi
Organizations  cecil-aw-pulumi, archway

Dependencies:
NAME        VERSION
boto3       1.28.8
pip         23.2.0
pulumi-aws  5.42.0
setuptools  68.0.0
wheel       0.40.0

### Additional context

I've tried numerous settings on the the lambda/client side such as setting read timeout values, etc. No luck in changing the result.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Will try to reproduce tomorrow.

**Comment by dixler** [comment]
Hey. I was able to reproduce the issue. Might it be perhaps the timeout settings on boto3?

I binary searched the minimum timeout where the hang begins and it was around 60ish seconds.

I found this article about boto3's lambda invoke timeout being around 60 seconds and I think this is the source of your issue. I then moved the sleep setting to 59 seconds and it didn't hang, but at 62 seconds it hangs. I then added the a config option to my client and set the `read_timeout=200` and it resolved the hang. I think the apparent hang may be due to boto3 retry logic.

LMK if this fixes it.

source: https://repost.aws/knowledge-center/lambda-function-retry-timeout-sdk

my repro:

```python
import pulumi
import pulumi_aws as aws
from pulumi import Output
from pulumi.dynamic import Resource
from pulumi.dynamic import ResourceProvider, CreateResult, UpdateResult

from botocore.client import Config
import boto3

class LambdaProvider(ResourceProvider):
    def create(self, props):
        # setting `read_timeout=200` fixed the issue for me.
        config = Config(read_timeout=200, retries={'max_attempts': 0})
        client = boto3.client('lambda', config=config)
        response = client.invoke(
            FunctionName="arn:aws:lambda:us-west-2::function:abcdefg",
            Payload=json.dumps({})
        )
        print(response)
        return CreateResult(id_="this", outs=props)

    def update(self, id, _olds, props):
        return UpdateResult(outs=props)


class LambdaResource(Resource):
    def __init__(
        self,
        name: str,
        opts: pulumi.ResourceOptions = None,
    ):
        super().__init__(LambdaProvider(), name, {}, opts)

LambdaResource("foo")
```

**Comment by cecil-aw** [comment]
Hmm... I played with the read_timeout config quite a bit with no luck. However, I didn't explore retries. I'll setup exactly how you tested and see what my results look like. I'll update asap.

**Comment by cecil-aw** [comment]
Yeah, no luck for me. Same issue. What OS are you running for the Pulumi CLI? I'm using Mac OS. I think I'll try running this from a container in a pipeline . btw, here is my code:
`import boto3
from botocore.client import Config
from botocore.exceptions import ClientError


def invoke_lambda_arn(invoke_lambda_arn, payload=None):
    print(f"Invoke lambda call: {invoke_lambda_arn}")
    client_config = Config(
        read_timeout=600,
        retries={'max_attempts': 0}
    )
    client = boto3.client("lambda", config=client_config)
    try:
        lambda_resp = client.invoke(
            FunctionName=invoke_lambda_arn,
            Payload=payload
        )
    except ClientError as e:
        print(f"Invoke client error: {e}")
        raise
    
    return lambda_resp['Payload'].read().decode('utf-8')
`

**Comment by dixler** [comment]
> What OS are you running for the Pulumi CLI?

linux(debian)

Just a sanity check, if you have the lambda's sleep duration as 180s and the read_timeout=200, does it still hang?

**Comment by cecil-aw** [comment]
Setup:
Lambda function timeout set to 10 minutes (600 secs)
Boto client read timeout set to 6 minutes (360 secs)
Lambda processing (sleep) for 200 seconds.

Updating status continues beyond 200 seconds. When the client read timeout of 360 seconds is reached, the boto client read timeout is tripped and pulumi exits with **updating failed** status. (error: Exception calling application: Read timeout on endpoint URL:)
Still don't know why the process hangs beyond 200 seconds up to the client timeout.

**Comment by cecil-aw** [comment]
I'm going to test this inside a pipeline. I'm getting suspicious of my laptop os config. TBD.

**Comment by cecil-aw** [comment]
Good news. I tested a 240 second delay in the pipeline and it worked as expected. I don't know what's up with my local config. Clsoing.
