### ISSUE TITLE
panic: reflect.Set: value of type pulumi.ID is not assignable to type string

### ISSUE THREAD

**Issue by port8080** [pulumi/pulumi#13857]
### What happened?

I ran `pulumi preview` after upgrading to pulumi-aws v6 and got the following panic

```
Diagnostics:
  pulumi:pulumi:Stack (misc-dev):
    panic: reflect.Set: value of type pulumi.ID is not assignable to type string
    goroutine 68 [running]:
    reflect.Value.assignTo({0x103b158e0?, 0x14000591b80?, 0x1?}, {0x103525afb, 0xb}, 0x103855760, 0x0)
    	/opt/homebrew/Cellar/go/1.20.6/libexec/src/reflect/value.go:3245 +0x208
    reflect.Value.Set({0x103855760?, 0x14000030ad0?, 0x1400019c018?}, {0x103b158e0?, 0x14000591b80?, 0x0?})
    	/opt/homebrew/Cellar/go/1.20.6/libexec/src/reflect/value.go:2236 +0xc8
    github.com/pulumi/pulumi/sdk/v3/go/internal.awaitInputs({0x103d5f878, 0x1400019c018}, {0x103cb3b60?, 0x14000280700?, 0x19?}, {0x103855760, 0x14000030ad0, 0x198})
    	/Users/ajitb/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.80.0/go/internal/types.go:859 +0x16e0
    github.com/pulumi/pulumi/sdk/v3/go/internal.toOutputTWithContext.func3()
    	/Users/ajitb/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.80.0/go/internal/types.go:1036 +0x118
    created by github.com/pulumi/pulumi/sdk/v3/go/internal.toOutputTWithContext
    	/Users/ajitb/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.80.0/go/internal/types.go:1028 +0x358

    error: an unhandled error occurred: program exited with non-zero exit code: 2
```

### Expected Behavior

No panic, this works with aws-sdk v5

### Steps to reproduce

File with ~280 LoC - not sure which is the relevant snippet. Key part is that it works with v5 and not with v6.

### Output of `pulumi about`

CLI
Version      3.79.0
Go Version   go1.21.0
Go Compiler  gc

Plugins
NAME  VERSION
aws   6.0.3
go    unknown

Host
OS       darwin
Version  13.5.1
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.20.6 darwin/arm64'

Current Stack: xetdata/misc/dev

TYPE                                   URN
pulumi:pulumi:Stack                    urn:pulumi:dev::misc::pulumi:pulumi:Stack::misc-dev
pulumi:providers:aws                   urn:pulumi:dev::misc::pulumi:providers:aws::default
aws:amp/workspace:Workspace            urn:pulumi:dev::misc::aws:amp/workspace:Workspace::dev-prometheus-workspace
aws:ses/domainIdentity:DomainIdentity  urn:pulumi:dev::misc::aws:ses/domainIdentity:DomainIdentity::xetsvc.com
aws:ses/domainDkim:DomainDkim          urn:pulumi:dev::misc::aws:ses/domainDkim:DomainDkim::xetsvc.com
aws:ssm/parameter:Parameter            urn:pulumi:dev::misc::aws:ssm/parameter:Parameter::dev-misc-axe-api-key
aws:iam/user:User                      urn:pulumi:dev::misc::aws:iam/user:User::dev-ses-smtp-user
aws:iam/accessKey:AccessKey            urn:pulumi:dev::misc::aws:iam/accessKey:AccessKey::dev-ses-smtp-user
aws:iam/userPolicy:UserPolicy          urn:pulumi:dev::misc::aws:iam/userPolicy:UserPolicy::dev-AmazonSesSendingAccess
aws:ssm/parameter:Parameter            urn:pulumi:dev::misc::aws:ssm/parameter:Parameter::dev-misc-ses-user-name
aws:ssm/parameter:Parameter            urn:pulumi:dev::misc::aws:ssm/parameter:Parameter::dev-misc-ses-access-key

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/port8080
User           port8080
Organizations  port8080, xetdata

Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-aws/sdk/v6  6.0.3
github.com/pulumi/pulumi/sdk/v3      3.80.0
xetdata.com/operations/utils/core    0.0.0

Pulumi locates its logs in /var/folders/m_/snnsxx1d2k94fkfcxy14g03m0000gn/T/ by default

### Additional context

https://github.com/pulumi/pulumi/issues/13575
https://github.com/pulumi/pulumi-aws/issues/2638#issuecomment-1648781925

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I think we're going to need some more information to repro this. I've been trying to trigger this error but as best I can tell the only place `toOutputTWithContext` is called will _always_ set the resolved value to the element type of the input type, see 
 https://github.com/pulumi/pulumi/blob/master/sdk/go/internal/types.go#L1080-L1087.

**Comment by port8080** [comment]
Thanks for looking into this @Frassle!
we will try and update with a smaller self contained repro.

**Comment by port8080** [comment]
I hope the information below helps to get a better repro on your side.

We have triangulated the problem to the following difference
```
        // does not work
	err = ssmutils.CreateSSMParameter(ctx, core.BuildInterProjectConfigKey(ctx, "misc", core.SesUserName), pulumi.StringOutput(accessKey.ID()))
	// works
	// err = ssmutils.CreateSSMParameter(ctx, core.BuildInterProjectConfigKey(ctx, "misc", core.SesUserName), accessKey.ID().ToStringOutput())
```

in a function to set up our Email Service
```
func createEmailService(ctx *pulumi.Context, domain, iamUserName string) error {
	// Set DomainIdentity so SES can send email for entire xetsvc.com domain
	_, err := ses.NewDomainIdentity(ctx, domain, &ses.DomainIdentityArgs{
		Domain: pulumi.String(domain),
	})
	if err != nil {
		return err
	}
	// Domain DKIM settings, since DNS managed by AWS Route 53 already
	// no DNS changes required (done automatically by SES with DomainDkim).
	_, err = ses.NewDomainDkim(ctx, domain, &ses.DomainDkimArgs{
		Domain: pulumi.String(domain),
	})
	if err != nil {
		return err
	}
	// Create the SMTP IAM user account, on which SMTP creds created
	// This is the user account that is allowed to
	smtpUser, err := iam.NewUser(ctx, iamUserName, &iam.UserArgs{
		Name: pulumi.String(iamUserName),
		Tags: pulumi.StringMap{
			"InvokedBy": pulumi.String("SESConsole"),
		},
	})
	if err != nil {
		return err
	}

	// Attach SES sending email policy to smtpUser account
	tmpJSON0, err := json.Marshal(map[string]interface{}{
		"Version": "2012-10-17",
		"Statement": []map[string]interface{}{
			{
				"Action": []string{
					"ses:SendRawEmail",
				},
				"Effect":   "Allow",
				"Resource": "*",
			},
		},
	})
	if err != nil {
		return err
	}
	json0 := string(tmpJSON0)
	_, err = iam.NewUserPolicy(ctx, core.ResourceName(ctx, "AmazonSesSendingAccess"), &iam.UserPolicyArgs{
		User:   smtpUser.Name,
		Policy: pulumi.String(json0),
	})
	if err != nil {
		return err
	}
	accessKey, err := iam.NewAccessKey(ctx, iamUserName, &iam.AccessKeyArgs{
		User: smtpUser.Name,
	})
	if err != nil {
		return err
	}

	// does not work
	err = ssmutils.CreateSSMParameter(ctx, core.BuildInterProjectConfigKey(ctx, "misc", core.SesUserName), pulumi.StringOutput(accessKey.ID()))
	// works
	// err = ssmutils.CreateSSMParameter(ctx, core.BuildInterProjectConfigKey(ctx, "misc", core.SesUserName), accessKey.ID().ToStringOutput())
	if err != nil {
		return err
	}

	err = ssmutils.CreateSSMParameter(ctx, core.BuildInterProjectConfigKey(ctx, "misc", core.SesAccessKey), accessKey.SesSmtpPasswordV4)
	if err != nil {
		return err
	}

	conf := config.New(ctx, "")
	err = ssmutils.CreateSSMParameter(ctx, core.BuildInterProjectConfigKey(ctx, "misc", core.AxeAPIKey), conf.RequireSecret(AxeCode))
	if err != nil {
		return err
	}
	return nil
}
```

**Comment by Frassle** [comment]
`pulumi.StringOutput(accessKey.ID())`

I wouldn't expect that to ever have worked. Go will let you cast between any output types, but then they'll generally panic later on when the untyped inner value tries to cast to the typed value matching the output type casted to.

The new generics API (https://github.com/pulumi/pulumi/discussions/13057) should fix this as then I don't think Go will let you cast an `Output[ID]` to an `Output[string]`. But it will be a while as that's rolled out, and the existing types won't go away because we need to keep them for backwards compat, so you will need to continue being careful about casting those output types.

**Comment by port8080** [comment]
Thanks for th explanation, feel free to close with a 'works as expected!'

**Comment by Frassle** [comment]
Thanks for getting back to us, glad the explanation helped.
