### ISSUE TITLE
Add a mechanism to move resources between projects

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#13874]
If you get to a position whereby you need to refactor some code, or move a resource to a shared infrastructure stack, the process can be quite painful.

Your options generally involve using `import` and copying code from one place to another.,

We likely can't improve the copying code part, but I think we _could_ improve the state management part.

Some off the top of my head ideas:

- Allow us to quickly export the resource id so we can copy code and add the import resource option
- Create a command to quickly export the state reference from one place to another

**Comment by Frassle** [comment]
`pulumi state cp <destination stack> <source urn>` would probably cover the basics. Renaming and reparenting would need some thought though
