### ISSUE TITLE
`pulumi config` errors with: read ".pulumi\meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by VTracyHuang** [pulumi/pulumi#13899]
I want to get the config and I excute command pulumi config
then error occurs:

error: read ".pulumi\\meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): MissingRegion: could not find region configuration

**Comment by Frassle** [comment]
That's an error from the backend that it can't read your statefiles to work out what stack to operate on for config.
Generally that's because you haven't set up the needed auth env vars to work with S3.

**Comment by VTracyHuang** [comment]
How can I locate the problem? Is there any logs? I can't get any information of pulumi

**Comment by Frassle** [comment]
Those are the logs, this error comes from the S3 client we use there isn't anymore information the system can give except that you have missing configuration to use S3.

Suggest looking at https://www.pulumi.com/docs/concepts/state/#aws-s3 and following all the links there about how to setup AWS configuration for Pulumi.

**Comment by surfingdoggo** [comment]
I'm seeing the same issue when I try to run `pulumi login s3://<bucket-name>`. 

Running `pulumi config set aws:region us-east-1` just yells at me to run `pulumi login`.

`$AWS_REGION` is set to us-east-1.

`Pulumi.yaml` is set as:
```
name: message-handler
runtime:
  name: python
description: A minimal AWS Python Pulumi program
config:
  aws-native:region: us-east-1
  aws:region: us-east-1
  pulumi:tags:
    value:
      pulumi:template: aws-python
```
This is being run inside a Docker container, thus the absence of a venv. I'm using temporary credentials from AWS SSO as environment variables.

I'm really stumped as to what could have possibly changed since yesterday. I'll post once I figure this out.

**Comment by surfingdoggo** [comment]
Update: 

This worked:

```
pulumi login 's3://<bucket_name>?region=us-east-1'
```

(It's from the Pulumi login docs)

I'm really not sure what the issue was and it was intermittent, nothing scientific but the environments and variables should have been the same.

**Comment by tgummerer** [comment]
As suggested in https://github.com/pulumi/pulumi/issues/15141, we should probably improve the error message here to make it more easily understandable what's happening.

**Comment by surfingdoggo** [comment]
> As suggested in #15141, we should probably improve the error message here to make it more easily understandable what's happening.

Thanks @tgummerer, I'm new to Pulumi and it's really encouraging that even silly little things like this get attention. It _really_ stands out. Thanks for your help!

**Comment by tgummerer** [comment]
I just realized that we have https://github.com/pulumi/pulumi/issues/13007 open as well, which is the same issue of returning better error messages.  So I'm going to close this issue out, but we're still tracking it.
