### ISSUE TITLE
ts/js project unexpectedly runs main instead of index

### ISSUE THREAD

**Issue by omercnet** [pulumi/pulumi#13916]
### What happened?

during a recent upgrade in pulumi to v3.78.1 pulumi deleted all resources.

the root cause was that even tho there was an index.ts file, pulumi executed the "main" in package.json which does not create resources, resulting in an empty state, causing deletion of all resources

### Expected Behavior

up until now, pulumi would execute the index.ts in the project - this is the expected behavior 
a change to run "main" is a breaking change that should be released as a major version, not a patch

### Steps to reproduce

will work on a repo showing the exact change

### Output of `pulumi about`

```CLI          
Version      3.76.0
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.5.1
Arch     arm64
```

nodejs version is unknown? how do I get its current version?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by omercnet** [comment]
https://github.com/pulumi/pulumi/pull/13273

this is the root cause here

this is a significant change that should drive a major release, not a patch

**Comment by julienp** [comment]
I am sorry about this! The documented behaviour for main is that (https://www.pulumi.com/docs/concepts/projects/project-file/#about-main)
> When it exists in both Pulumi.yaml and package.json, the value in Pulumi.yaml takes precedence.
but as you point out, we broke that in https://github.com/pulumi/pulumi/pull/13273

We fixed this with https://github.com/pulumi/pulumi/pull/16363
