### ISSUE TITLE
Changing region after an update leads to confusing errors

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#1391]
Scenario:

- Deployed webserver example to `us-east-1`
- It created the security group, but not the VM, because I had the wrong AMI listed
- I changed the region to `us-west-2` and redeployed, but AWS gave me a confusing error, because the security group and instance were not in the same region.

Workaround:
- Change region back to `us-west-2`
- Run `destroy`
- Run `update`

It would be nice if Pulumi detected that I changed the region for subsequent updates, and provided a warning that I might see AWS errors, with a link to a doc on how to get back to a good state.

**Comment by lukehoban** [comment]
@pgavlin Assigning to you to track as part of 1st class providers work, which ideally will lead to a better experience here.

**Comment by lukehoban** [comment]
@pgavlin What is the current state here?  Do we have a plan for addressing in current milestone?

**Comment by pgavlin** [comment]
This remains an issue. We will not be able to fix this without extending the provider interface with `{Check,Diff}Config`. This is tracked by #1718, which I do not believe we will do in M19.

**Comment by lukehoban** [comment]
This will be fixed with pulumi/pulumi-terraform#386.  Closing as a dupe.
