### ISSUE TITLE
Pulumi deletes 29 ListenerCertificates, but then doesn't replace them leading to another pulumi up to create them. 

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#13925]
### What happened?

It looks like an error triggered the following deletes:
Resources:
    + 3 created
    ~ 7 updated
    - 31 deleted
    +-2 replaced
    43 changes. 356 unchanged
but the running code should have noticed that the ListenerCertificates were needed. One the subsequent run, without code changes the following modifications took place:
Resources:
    + 29 created
    ~ 2 updated
    31 changes. 337 unchanged
    
this could possibly be related to: #13903

### Expected Behavior

Pulumi replaces the listenercertificates all in the same run if needed. 

### Steps to reproduce

Working on reproduction

### Output of `pulumi about`

Pulumi 3.81.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
This appears to be the same issue as #13903. It's the same pattern of an update failing during an update where a parent is reparented, and then a subsequent update on the prior partial update loses track of the children that should be aliased.
