### ISSUE TITLE
Don't print colors if printing in non-interactive context

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#1395]
Feedback from a beta user:

- "-c auto" doesn't work as I expect - I expect it to be colorless if output is not tty.
- Also if output is not tty I strongly advice not printing  any escape sequences - they are displayed as garbage when you do "| less" or when writing to a logfile  if pulumi is invoked from batch script

**Comment by lukehoban** [comment]
@CyrusNajmabadi @ellismg What's the status of this?  Is there discreet work we can/should still do to help here?

**Comment by CyrusNajmabadi** [comment]
I believe this work is done.  But i need to validate all the OP scenarios are addressed and work properly.
