### ISSUE TITLE
Allow stack references to read in parallel

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#13959]
Currently, stack references read values in serial, which can considerably slow down a deployment if there are many stack references.

Reading all those values in parallel would dramatically speed up some programs

**Comment by justinvp** [comment]
> stack references read values in serial

@jaxxstorm, can you clarify what you mean by the values are read in serial?

**Comment by jaxxstorm** [comment]
@justinvp according to the customer, the values come back one at a time.

I tried to repro this in TypeScript, but having difficulty reproing it. Going to try in Python shortly.

If you have any suggestions on how to profile and verify, please let me know

**Comment by jaxxstorm** [comment]
I believe this was a misunderstanding after syncing with the customer, so closing
