### ISSUE TITLE
Migrating from terraform to pulumi

### ISSUE THREAD

**Issue by arnabsinha4u** [pulumi/pulumi#13978]
### What happened?

Tried to convert a working terraform project to pulumi and faced the issue:

```
pulumi convert --from terraform --language python
Converting from terraform...
warning: : Function not yet implemented; Function flatten not yet implemented
warning: : Provider alias not supported; Provider aliases are not supported, ignoring oci=home-nl-ams
warning: : Provider alias not supported; Provider aliases are not supported, ignoring oci=de-fr
Converting to python...
================================================================================
The Pulumi CLI encountered a code generation error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.83.0
error: main.pp:19,1-30,2: /var/folders/sd/3jp56vfn1kgcjfnx6rlk7csr0000gq/T/pulumi-convert1685076170/modules/networking/main.pp:207,1-245,2: circular reference; , and 2 other diagnostic(s); /var/folders/sd/3jp56vfn1kgcjfnx6rlk7csr0000gq/T/pulumi-convert1685076170/modules/networking/main.pp:207,1-245,2: circular reference; , and 2 other diagnostic(s)
error: could not generate output program
```

### Example

Tried to convert a working terraform project to pulumi using: https://www.pulumi.com/docs/using-pulumi/adopting-pulumi/migrating-to-pulumi/from-terraform/#how-to-use-the-converter

### Output of `pulumi about`

pulumi about
CLI
Version      3.83.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME    VERSION
python  unknown

Host
OS       darwin
Version  13.1
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.9.6
'

Dependencies:
NAME        VERSION
future      0.18.2
macholib    1.15.2
pip         21.2.4
setuptools  58.0.4
six         1.15.0
wheel       0.37.0

Pulumi locates its logs in /var/folders/sd/3jp56vfn1kgcjfnx6rlk7csr0000gq/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
The main issue appears to be the circular reference error, which is allowed in terraform module declarations but not in Pulumi (yet). Addressing this is tracked in #13581.

In the meantime, it may be possible to comment out a portion of your terraform project to break the circular reference, to allow the converter to actually generate some code, and then manually adjust from there.
