### ISSUE TITLE
Pulumi does not handle Azure resources that depends on subnets correctly

### ISSUE THREAD

**Issue by christianeriksson** [pulumi/pulumi#13972]
### What happened?

I have a pulumi stack in Azure with a subnet with private endpoints attached. When renaming the subnet, triggering a replacement of the resource, pulumi does not schdeule a replacement of the private endpoints. As pulumi tries to delete the subnet pulumi crashes with an error:

```
error: Code="InUseSubnetCannotBeDeleted" Message="Subnet temp-private-endpoints is in use by /subscriptions/<SUBSCRIPTION_ID>/resourceGroups/resource-groupd88a400f/providers/Microsoft.Network/networkInterfaces/temp-storage-blob-access-nic-temp/ipConfigurations/privateEndpointIpConfig.8d250950-ccaa-4da6-8d03-407cef3b4735 and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]
```
Even if I trick/force pulumi to replace the endpoint as well and explicitly tell pulumi that the private endpoint depends on the subnet, pulumi fails to schedule deletion of the private endpoint (and underlying resources such as NICs and ip configs) before deleting the subnet, resulting in the same error.

I would have expected Pulumi to first delete all resources attached to the subnet before attempting to delete the subnet, to avoid this Azure error and successfully perform the subnet renaming.

### Example

Start with this setup:
```js
import { network, resources, storage } from "@pulumi/azure-native";

const resourceGroup = new resources.ResourceGroup("resource-group");

const storageAccount = new storage.StorageAccount("storage-account", {
    accountName: "tempacc76523",
    resourceGroupName: resourceGroup.name,
    sku: {
        name: storage.SkuName.Standard_LRS,
    },
    kind: storage.Kind.StorageV2,
});

const vnet = new network.VirtualNetwork("virtual-network", {
    resourceGroupName: resourceGroup.name,
    virtualNetworkName: "temp-virtual-network",
    addressSpace: {
        addressPrefixes: ["10.84.42.0/24"]
    }
});

const privateEndpointsSubnet = new network.Subnet(
    `temp-private-endpoints-subnet`,
    {
        addressPrefix: "10.84.42.0/27",
        resourceGroupName: resourceGroup.name,
        subnetName: "temp-private-endpoints",
        virtualNetworkName: vnet.name,
    }
);

const dataStorageBlobAccessEndpointName = "temp-storage-blob-access";
const dataStorageBlobAccessNicName = `${dataStorageBlobAccessEndpointName}-nic-temp`;
const dataStorageBlobAccessEndpoint = new network.PrivateEndpoint(
    "temp-private-endpoint",
    {
        customNetworkInterfaceName: dataStorageBlobAccessNicName,
        privateEndpointName: dataStorageBlobAccessEndpointName,
        privateLinkServiceConnections: [{
            name: `${dataStorageBlobAccessEndpointName}-service-link`,
            groupIds: ["blob"],
            privateLinkServiceId: storageAccount.id,
        }],
        resourceGroupName: resourceGroup.name,
        subnet: {
            id: privateEndpointsSubnet.id,
        },
    }
);
```
Then change the name of the subnet resource, like this:
```diff
diff --git a/old_index.ts b/index.ts
index 1fc13c1..b29ec3f 100644
--- a/old_index.ts
+++ b/index.ts
@@ -24,7 +24,7 @@ const privateEndpointsSubnet = new network.Subnet(
     {
         addressPrefix: "10.84.42.0/27",
         resourceGroupName: resourceGroup.name,
-        subnetName: "temp-private-endpoints",
+        subnetName: "temp-private-endpoints-change",
         virtualNetworkName: vnet.name,
     }
 );
```
A `pulumi up` will result in:
```
Previewing update (temp.temp):
     Type                                     Name                           Plan        Info
     pulumi:pulumi:Stack                      temp-temp.temp
 +-  ├─ azure-native:network:Subnet           temp-private-endpoints-subnet  replace     [diff: ~subnetName]
 ~   └─ azure-native:network:PrivateEndpoint  temp-private-endpoint          update      [diff: ~subnet]


Resources:
    ~ 1 to update
    +-1 to replace
    2 changes. 4 unchanged

Do you want to perform this update? yes
Updating (temp.temp):
     Type                            Name                           Status                   Info
     pulumi:pulumi:Stack             temp-temp.temp                 **failed**               1 error
 +-  └─ azure-native:network:Subnet  temp-private-endpoints-subnet  **replacing failed**     1 error


Diagnostics:
  pulumi:pulumi:Stack (temp-temp.temp):
    error: update failed

  azure-native:network:Subnet (temp-private-endpoints-subnet):
    error: Code="InUseSubnetCannotBeDeleted" Message="Subnet temp-private-endpoints is in use by /subscriptions/<SUBSCRIPTION_ID>/resourceGroups/resource-groupd88a400f/providers/Microsoft.Network/networkInterfaces/temp-storage-blob-access-nic-temp/ipConfigurations/privateEndpointIpConfig.8d250950-ccaa-4da6-8d03-407cef3b4735 and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]

Resources:
    4 unchanged

Duration: 24s
```
I believe that `pulumi up` should have tried to replace the private endpoint rather than just updating (as one cannot delete a subnet before removing all resources using it).

Adding `dependsOn` to the private endpoint does not make a different, the result is as above.
```js
{
    dependsOn: [privateEndpointsSubnet],
}
```

I can force `pulumi up` to schedule a replacement of the private endpoint by adding:
```js
{
    replaceOnChanges: ["subnet"]
}
``` 
But it will still try to delete the subnet first, resulting in the same error. Further I can try adding `deleteBeforeReplace: true` to the private endpoint but I still get the same result.

### Output of `pulumi about`

```
CLI
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.7.0
nodejs        unknown

Host
OS       arch
Version
Arch     x86_64

This project is written in nodejs: executable='/home/<user>/.nvm/versions/node/v18.13.0/bin/node' version='v18.13.0'

Current Stack: temp.temp

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:temp.temp::temp::pulumi:pulumi:Stack::temp-temp.temp
pulumi:providers:azure-native         urn:pulumi:temp.temp::temp::pulumi:providers:azure-native::default_2_7_0
azure-native:resources:ResourceGroup  urn:pulumi:temp.temp::temp::azure-native:resources:ResourceGroup::resource-group
azure-native:storage:StorageAccount   urn:pulumi:temp.temp::temp::azure-native:storage:StorageAccount::storage-account
azure-native:network:VirtualNetwork   urn:pulumi:temp.temp::temp::azure-native:network:VirtualNetwork::virtual-network
azure-native:network:Subnet           urn:pulumi:temp.temp::temp::azure-native:network:Subnet::temp-private-endpoints-subnet
azure-native:network:PrivateEndpoint  urn:pulumi:temp.temp::temp::azure-native:network:PrivateEndpoint::temp-private-endpoint


Found no pending operations associated with temp.temp

Backend
Name           <machine-name>
URL            azblob://<storage_container>?storage_account=<storage_account>
User           <user>
Organizations

Dependencies:
NAME                  VERSION
@pulumi/azure-native  2.7.0
@pulumi/pulumi        3.83.0
@types/node           16.18.52
ts-node               10.9.1

Pulumi locates its logs in /tmp by default
```

### Additional context

I have observed the same issue with the `web.WebApp` resource in the `azure-native` module if the subnet is attached to the `WebApp` using the `virtualNetworkSubnetId: subnet.id` property.

And as a side note, on a `pulumi destroy` it does seem like pulumi knows to destroy the private endpoint before the subnet, same with the initial creation of the stack.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening this issue with these details, and sorry for the trouble! To summarize, it sounds like the expectation is that the Azure Native provider will track all resources that utilize the given vnet/subnet and replace them automatically when the subnet needs to be replaced. We don't currently do anything like that in the Azure Native provider (or any other providers), and with the current provider model, it doesn't seem possible to derive all the resources that need to be recreated in such a scenario.

One thing we could consider doing is adding a new resource option to Pulumi that would allow you to specify that a resource should be replaced if the specified resource is replaced. I've opened https://github.com/pulumi/pulumi/issues/14072 to track this enhancement, and am closing this in favor of that issue.

**Comment by justinvp** [comment]
In the meantime, one potential way to workaround this is to comment out any resources that are attached to the vnet/subnet when modifying the vnet/subnet, and specify `replaceOnChanges: ["*"]` on the vnet/subnet such that any change to it replaces it. Run `pulumi up` and the vnet/subnet will be replaced and the resources that were commented out will be deleted. Then, subsequently, uncomment the other resources and run another `pulumi up`, which will recreate the resources within the subnet.
