### ISSUE TITLE
Weird error when attempting to create dynamic provider/resource

### ISSUE THREAD

**Issue by jopar219** [pulumi/pulumi#13974]
### What happened?

I'm having trouble creating dynamic providers/resources on a fresh pulumi install. I'm not sure if I'm doing something wrong, since the error I get is not very helpful.

I made a repo with the custom resource code: https://github.com/jopar219/pulumi-example-project/

If I run `pulumi up` inside I get the following error:
```
$ pulumi up
Previewing update (dev):
     Type                               Name                 Plan       Info
 +   pulumi:pulumi:Stack                example-project-dev  create     
     └─ pulumi:providers:pulumi-nodejs  default                         1 error


Diagnostics:
  pulumi:providers:pulumi-nodejs (default):
    error: could not find latest version for provider pulumi-nodejs: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-pulumi-nodejs/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```

Now, I'm not sure if this is a bug or not, but the repo in the error message looks suspicious:
```
github.com/repos/pulumi/pulumi-pulumi-nodejs
```

Since writing dynamic providers/resource is one of the distinguishing features of pulumi, getting an error on my first attempt at creating one is very off-putting.

### Example

# Steps to reproduce
Install from the arch linux package registry as such:
```
$ sudo pacman -Syu pulumi
$ pulumi version
3.81.0
```
Configure pulumi to use the local storage
```
$ pulumi login file://~
```
Clone the repo, and run setup commands
```
$ git clone git@github.com:jopar219/pulumi-example-project.git
$ cd pulumi-example-project
$ npm i
$ pulumi stack init dev
$ export PULUMI_CONFIG_PASSPHRASE=
```
Run `pulumi up`, to get the following message:
```
$ pulumi up
Previewing update (dev):
     Type                               Name                 Plan       Info
 +   pulumi:pulumi:Stack                example-project-dev  create     
     └─ pulumi:providers:pulumi-nodejs  default                         1 error


Diagnostics:
  pulumi:providers:pulumi-nodejs (default):
    error: could not find latest version for provider pulumi-nodejs: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-pulumi-nodejs/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```

### Output of `pulumi about`

CLI          
Version      3.81.0
Go Version   go1.21.0
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       arch
Version  "rolling"
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v20.6.1'

Backend        
Name           archlinux
URL            file://~
User           user
Organizations  

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.83.0
@types/node     16.18.52

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current snapshot

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> Install from the arch linux package registry as such

This is not an officially supported method of installing Pulumi.

The nodejs plugin should be installed side by side with the pulumi executable, you'll have to take this issue up with the maintainers of the arch package. To get going without waiting for a fix, install Pulumi by one of the methods listed at https://www.pulumi.com/docs/install/.

**Comment by jopar219** [comment]
Thanks for the prompt reply!

I installed according to the [instructions](https://www.pulumi.com/docs/install/) and now it works. I'm not sure how to report it to the arch maintainers though, if someone runs into this same issue in the future that might be a good idea.

**Comment by Frassle** [comment]
Looks like they're already aware: https://bugs.archlinux.org/task/72394?project=1&string=pulumi
