### ISSUE TITLE
Azure Backend Blob Storage Auth Failed. 

### ISSUE THREAD

**Issue by wuqunfei** [pulumi/pulumi#13984]
### What happened?

As a developer, we like to use Pulumi with azure backend, like
```
pulumi login azblob://<container-path>
```
But it does not work with all the steps which prepared, Same issue likes https://github.com/pulumi/pulumi/issues/13007 

```
error: problem logging in: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): ===== RESPONSE ERROR (ErrorCode=AuthorizationPermissionMismatch) =====
Description=This request is not authorized to perform this operation using this permission.
RequestId:3fb6f83d-c01e-0067-186e-ea1ec6000000
Time:2023-09-18T20:27:24.9858482Z, Details: (none)
```

### Example

`
#!/bin/sh

ARM_CLIENT_ID=yours
ARM_CLIENT_SECRET=yours
ARM_TENANT_ID=yours
ARM_SUBSCRIPTION_ID=yours

export ARM_CLIENT_ID
export ARM_CLIENT_SECRET
export ARM_TENANT_ID
export ARM_SUBSCRIPTION_ID

az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
az account set --subscription=$ARM_SUBSCRIPTION_ID

RESOURCE_GROUP_NAME=rg-infra-state
RESOURCE_GROUP_REGION="West Europe"

## create resource group
az group create --name $RESOURCE_GROUP_NAME --location $RESOURCE_GROUP_REGION

AZURE_STORAGE_ACCOUNT="infrastate"

## create storage account
az storage account create \
  --name $AZURE_STORAGE_ACCOUNT \
  --resource-group $RESOURCE_GROUP_NAME \
  --location $RESOURCE_GROUP_REGION \
  --sku Standard_RAGRS \
  --kind StorageV2

AZURE_STORAGE_KEY=$(az storage account keys list --account-name $AZURE_STORAGE_ACCOUNT -g $RESOURCE_GROUP_NAME -o tsv --query '[0].value')

export AZURE_STORAGE_ACCOUNT
export AZURE_STORAGE_KEY

## create container
CONTAINER_NAME="statecontainer"

az storage container create \
  --name $CONTAINER_NAME \
  --account-key $AZURE_STORAGE_KEY \
  --account-name $AZURE_STORAGE_ACCOUNT

## Pulumi Login
pulumi login 'azblob://$CONTAINER_NAME?storage_account=$AZURE_STORAGE_ACCOUNT'

`
```
error: problem logging in: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): ===== RESPONSE ERROR (ErrorCode=AuthorizationPermissionMismatch) =====
Description=This request is not authorized to perform this operation using this permission.
RequestId:3fb6f83d-c01e-0067-186e-ea1ec6000000
Time:2023-09-18T20:27:24.9858482Z, Details: (none)
```

### Output of `pulumi about`

`CLI          
Version      3.83.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.8.0
python        unknown

Host     
OS       darwin
Version  13.5.2
Arch     arm64

This project is written in python: executable='/Users/rxhbs7s/opt/anaconda3/bin/python3' version='3.9.13
'

Dependencies:
NAME                 VERSION
pip                  23.2.1
pulumi-azure-native  2.8.0
setuptools           68.2.2
wheel                0.41.2

Pulumi locates its logs in /var/folders/44/_tqghfm11qn6y_74jbfqs3vm0000gq/T/ by default
`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Zaid-Ajaj** [comment]
Hi there @wuqunfei, in our [docs](https://www.pulumi.com/docs/concepts/state/), we mention the following:
 > The Azure account must have the [Storage Blob Data Contributor role](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-contributor) or an equivalent role with permissions to read, write, and delete blobs.

The permission error you are getting could be due to the role assigned to the storage account.

**Comment by wuqunfei** [comment]
thanks, you are right.
