### ISSUE TITLE
AssertionError when attempting to retrieve a GCP provider's `access_token` when not authenticated

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#13985]
Customer report of a possible bug in the core Python SDK language bindings. It manifests in the Pulumi GCP provider when attempting to retrieve the provider's `access_token` when not authenticated to GCP.

```
error: Program failed with an unhandled exception:
Traceback (most recent call last):
  File "/private/tmp/gcp-gke-py/./__main__.py", line 33, in <module>
    gcp_provider_client = get_client_config(opts=InvokeOptions(provider=gcp_provider))
  File "/private/tmp/gcp-gke-py/venv/lib/python3.9/site-packages/pulumi_gcp/organizations/get_client_config.py", line 108, in get_client_config
    access_token=pulumi.get(__ret__, 'access_token'),
  File "/private/tmp/gcp-gke-py/venv/lib/python3.9/site-packages/pulumi/_types.py", line 660, in get
    raise AssertionError(
AssertionError: get can only be used with classes decorated with @input_type or @output_type
```

It's also possible this could be a bug in the Pulumi GCP provider. Perhaps the correct behavior is that the provider return an empty string value rather than `None`.

Either way, the code is falling through [to the assertion error](https://github.com/pulumi/pulumi/blob/e4ea1ec548e7a0d6115d7e4454b78bb0d6f5c36a/sdk/python/lib/pulumi/_types.py#L661) and this probably shouldn't be the case. Ideally, the user would get some form of diagnostic regarding the need to authenticate.

**Comment by justinvp** [comment]
I haven't yet been able to repro.

```python
import pulumi
from pulumi_gcp import Provider
from pulumi_gcp.organizations import get_client_config

gcp_provider = Provider("provider", project="myproject")
gcp_provider_client = get_client_config(opts=pulumi.InvokeOptions(provider=gcp_provider))
```

I’m not authenticated. Running `pulumi up`, I get the following error:

```
Diagnostics:
  pulumi:providers:gcp (provider):
    error: rpc error: code = Unknown desc = 2 errors occurred:
    	* failed to load application credentials.
    To use your default gcloud credentials, run:
    	`gcloud auth application-default login`
    See https://www.pulumi.com/registry/packages/gcp/installation-configuration/ for details.
    Expanded error message: Attempted to load application default credentials since neither `credentials` nor `access_token` was set in the provider block.  No credentials loaded. To use your gcloud credentials, run 'gcloud auth application-default login'.  Original error: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information
```

This is using `pulumi-gcp` `6.65.1` with Python `3.10.6`.

**Comment by justinvp** [comment]
Can repro after running the following:
1. `gcloud auth login --update-adc`
2. `gcloud auth revoke --all`
3. `pulumi up`

**Comment by lukehoban** [comment]
This is caused by this line returning `None`.

https://github.com/pulumi/pulumi-gcp/blob/e0a4310c2ef3ea1f058b280546fc7a8521ed971d/sdk/python/pulumi_gcp/organizations/get_client_config.py#L106

Which in turn is because the invoke is returning `None, None` (no error, but also a None value):

https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/invoke.py#L132

Which is ultimately because monitor.Invoke is returning this:

```
    {'DESCRIPTOR': <google._upb._message.Descriptor object at 0x106022010>, '__module__': 'pulumi.provider_pb2', '__slots__': (), '__doc__': None}
```

Which does not have an expected `"return"` attribute.

This does appear to be an issue in either Python codegen (gracefully handling the possible None from invoke), or in the core SDK (not returning None in the first place).

**Comment by justinvp** [comment]
Running with `PULUMI_DEBUG_GRPC=./debug.json pulumi up`, I see we do actually get a `"return"` value in the response, an empty object:

```json
{
    "method": "/pulumirpc.ResourceMonitor/Invoke",
    "request": {
        "tok": "gcp:organizations/getClientConfig:getClientConfig",
        "args": {},
        "provider": "urn:pulumi:dev::gcppy::pulumi:providers:gcp::provider::04da6b54-80e4-46f7-96ec-b56ff0331ba9",
        "acceptResources": true
    },
    "response": {
        "return": {}
    },
    "metadata": {
        "mode": "server"
    }
}
```

https://github.com/pulumi/pulumi/blob/f82b7358f1fd8e52e303365c1fa630c9bff157b0/sdk/python/lib/pulumi/runtime/invoke.py#L122-L132

In this case, `ret_obj` _is_ an instance of `struct_pb2.Struct`, but it's empty, which causes the `if ret_obj:` path not to be taken, and instead `None, None` is returned.

**Comment by Frassle** [comment]
Should probably be `if ret_obj is not None:`
