### ISSUE TITLE
`whoami` is missing a newline

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#14008]
There is no newline at the end of `pulumi whoami`'s output:

![image](https://github.com/pulumi/pulumi/assets/3953235/f97f0ab1-8c73-4c53-80bc-fc0c77fb2121)

**Comment by Frassle** [comment]
I'd always assumed this had been done on purpose to make it easy to interpolate into shell variables?

**Comment by joeduffy** [comment]
UNIX `whoami` puts a newline at the end, and is commonly used this way?

![image](https://github.com/pulumi/pulumi/assets/3953235/54ff7d5e-53a4-4bbf-be62-5acea62878cd)

**Comment by justinvp** [comment]
Looks like we used to print the newline, but that changed with https://github.com/pulumi/pulumi/issues/14008

**Comment by justinvp** [comment]
Fix: https://github.com/pulumi/pulumi/pull/14025
