### ISSUE TITLE
SSO signin breaks `pulumi login` flow

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#14009]
If I am logged out of the CLI, and run `pulumi login`, then choose to sign in to my org via SSO, it breaks the login flow. In other words, the CLI hangs indefinitely waiting for the login to complete.

![image](https://github.com/pulumi/pulumi/assets/3953235/012355f4-9198-4a73-bd7c-ab091ee106a7)

This is not what I would expect, although I realize the fact that I have 'clicked' presumably somehow lost the context that I was routed through the CLI signin flow.

To repro:
* Log out of CLI (`pulumi logout`)
* Log out of app.pulumi.com in your web browser
* Run `pulumi login` from CLI
* Hit ENTER to pop a browser window
* Click "Sign into SSO" and complete the signin process
* Voila, you land on the dashboard, the CLI is left hanging ...

**Comment by justinvp** [comment]
This likely needs to be fixed in Pulumi Cloud. Investigating.

**Comment by justinvp** [comment]
This is almost certainly a Pulumi Cloud bug. I've added some more information to the upstream bug.
