### ISSUE TITLE
Running `pulumi policy publish` doesn't make use of the user's default org when set

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi#14032]
### What happened?

When running `pulumi policy publish` to publish a policy pack, the CLI defaults to the user's own account, even when the user has set their default org via `pulumi org set-default`.

### Example

* `pulumi org set-default <something>`
* `pulumi policy new aws-typescript`
* `pulumi policy publish` ❌

```
Obtaining policy metadata from policy plugin
Compressing policy pack
Uploading policy pack to Pulumi service
Publishing "aws-dewlkdjwekdjwoj" - version 0.0.1 to "aureq"
error: Publish policy pack failed: [409] This organization does not support Policy as Code.
```

### Output of `pulumi about`

```
CLI          
Version      3.85.0
Go Version   go1.21.1
Go Compiler  gc

Host     
OS       debian
Version  12.1
Arch     x86_64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo, pulumi
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Looks like we're missing a load of calls to GetBackendConfigDefaultOrg in the policy code. Looks like a lot of the help texts will need updating for this as well.

**Comment by aureq** [comment]
@Frassle I've opened an issue for the help texts as well https://github.com/pulumi/pulumi-service/issues/15739
