### ISSUE TITLE
Panic: concurrent map iteration and map write

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#14036]
### What happened?

Customer upgraded from Pulumi CLI 3.83.0 -> 3.85.0 and `pulumi-aws` 6.2.0 -> 6.2.1 (might or might not be related) and during a stack update of one stack, they got `fatal error: concurrent map iteration and map write`.

Full stack trace: [traceback.txt](https://github.com/pulumi/pulumi/files/12713792/traceback.txt)

### Example

N/A

### Output of `pulumi about`

```
CLI          
Version      3.53.1
Go Version   go1.19.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.2.1
kubernetes  4.2.0
python      unknown
random      4.14.0

Host     
OS       darwin
Version  13.6
Arch     arm64

This project is written in python: executable='/Users/q479080/.pyenv/shims/python3' version='3.11.4'

<removed customer info>

Dependencies:
NAME              VERSION
ansible-core      2.15.3
black             23.9.1
commonmark        0.9.1
deploy-aws-infra  0.0.0
flake8            6.1.0
pip               23.1.2
pytest-cov        4.1.0
setuptools        67.8.0
wheel             0.40.0
```

### Additional context

Related: #10060

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
https://github.com/pulumi/pulumi/pull/14049 might be a fix for this. Move the coping to when we create the events, rather than when we try to access them.
