### ISSUE TITLE
Errors on the diff of ecs.TaskDefinition, but applies correctly

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi#14040]
### What happened?

When we have an ecs.TaskDefinition and want to make changes to an environment variable on a container, Pulumi shows a diff that is incorrect, as if another environment variable was about to be changed. If we proceed and apply the change, we see that the change was actually correct.

What's even more strange is that this incorrect diff doesn't manifest always, and it seems to only happen every other Pulumi run, assuming we always apply.

### Example

Consider the following code:

```
pulumi_aws_native.ecs.TaskDefinition(
    "example",
    container_definitions=[{
        "image": "example",
        "name": "example",
        "memory": 128,
        "environment": [
            {
                "name": "a",
                "value": "1",
            },
            {
                "name": "b",
                "value": "2",
            },
        ],
    }],
    opts=pulumi.ResourceOptions(replace_on_changes=["containerDefinitions"],),
)
```

Create the resource above and then change the value of the `b` environment variable to `22`. Run pulumi again and it will show the following diff:

```
      ~ containerDefinitions: [
          ~ [0]: {
                  ~ environment: [
                      ~ [1]: {
                              ~ value: "1" => "22"
                            }
                    ]
                }
        ]
```

The diff is incorrectly showing that the affected variable is `a` instead of `b`. If we proceed with the apply and check the resource later, we see that it correctly changed the environment variable `b`.

Now change the value of the `b` environment variable to `222`. Run pulumi again and it will show the following diff:

```
      ~ containerDefinitions: [
          ~ [0]: {
                  ~ environment: [
                      ~ [1]: {
                              ~ value: "22" => "222"
                            }
                    ]
                }
        ]
```

The diff is now correct. Go ahead and apply the change.

Now change the value of the `b` environment variable to `2222`. Run pulumi again and it will show the following diff:

```
      ~ containerDefinitions: [
          ~ [0]: {
                  ~ environment: [
                      ~ [1]: {
                              ~ value: "1" => "2222"
                            }
                    ]
                }
        ]
```

The diff is once again wrong. You can keep this pattern going, it will always flip between being correct and incorrect if we keep applying the changes.

These results are always consistent. A correct diff will always be correct until applying and an incorrect diff will always be incorrect until applying.

### Output of `pulumi about`

```
CLI          
Version      3.84.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME          VERSION
aws-native    0.77.0
python        unknown

Host     
OS       fedora
Version  38
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.11.5
'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Well this was fun to track down.

When we calculate the diff we compare the old resource outputs to the new resource inputs. Unfortunately it seems the aws provider is reordering the environment array, so the diff gets confused by this.

Initial inputs: `[{name: "a", value: "1"}, {name: "b", value: "2"}]`
Saved outputs: `[{name: "b", value: "2"}, {name: "a", value: "1"}]`

I still think this is a bug in the engine mind you. We're being inconsistent about when we diff against the old inputs (the automatic diff we do when the provider tells us to work it out in the engine), vs the diff we do to restore detailed diffs to diff objects.

**Comment by Sodki** [comment]
This is amazing, thank you @Frassle!
