### ISSUE TITLE
Pulumi fails to recognize and remove VNet dependency

### ISSUE THREAD

**Issue by mikocot** [pulumi/pulumi#14050]
### What happened?

VirtualNetwork parameters can't be modified by the Azure Native Provider if there is any resource using it. We expect that such resource would be first destroyed and then vnet/subnet modified/replaced.

### Example

A Virtual Network is deployed as part of Pulumi stack, using azure native provider.
A Managed Envrionment for Azure Container Apps is bound to a subnet of that network.

When trying to modify parameters (ip range) of that subnet/vnet the deployment fails, as subnet is in use. 
![image (35)](https://github.com/pulumi/pulumi/assets/9884950/d476ba8e-6f61-41ab-8322-c10d622eca01)
![image (34)](https://github.com/pulumi/pulumi/assets/9884950/f7e31533-8898-4e63-9267-87f74b32c577)

### Output of `pulumi about`

> 'dotnet build -nologo .' completed successfully
> CLI
> Version      3.85.0
> Go Version   go1.21.1
> Go Compiler  gc
> 
> Plugins
> NAME          VERSION
> azure-native  2.5.0
> dotnet        unknown
> random        4.13.2
> 
> Host
> OS       Microsoft Windows 10 Enterprise
> Version  10.0.19045 Build 19045
> Arch     x86_64
> 
> This project is written in dotnet: executable='C:\Program Files\dotnet\dotnet.exe' version='7.0.400'

### Additional context

We can't ensure that vnet parameters will never change, currently Pulumi doesn't seem to be able to perform some operation unless the whole stack is destroyed and redeployed, which is much more invasive than just replacing dependent resources.

We can add ReplaceOnChanges and DeleteBeforeReplace = true, but this ends up with similar issue -> used subnet can't be deleted (see second screenshots)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening this issue and sorry for the trouble! To summarize, it sounds like the expectation is that the Azure Native provider will track all resources that utilize the given vnet/subnet and replace them automatically when the subnet needs to be replaced. We don't currently do anything like that in the Azure Native provider (or any other providers), and with the current provider model, it doesn't seem possible to derive all the resources that need to be recreated in such a scenario.

One thing we could consider doing is adding a new resource option to Pulumi that would allow you to specify that a resource should be replaced if the specified resource is replaced. I've opened https://github.com/pulumi/pulumi/issues/14072 to track this enhancement, and am closing this in favor of that issue.

**Comment by justinvp** [comment]
In the meantime, one potential way to workaround this is to comment out any resources that are attached to the subnet when modifying the vnet/subnet, and specify `replaceOnChanges: ["*"]` on the vnet/subnet such that any change to it replaces it. Run `pulumi up` and the vnet/subnet will be replaced and the resources that were commented out will be deleted. Then, subsequently, uncomment the other resources and run another `pulumi up`, which will recreate the resources within the subnet.

**Comment by mikocot** [comment]
thanks, yeah, I believe there should be an option to allow specifying such resources if they can't be tracked by the provider itself. Having to comment things out and redeploy doesn't feel like production-ready solution. That means releasing 2 independent versions, one after each other, a quite terrible process.

In this case the idea to separate stacks even further than we have seems more acceptable, but this unfortunately leads to other issues
