### ISSUE TITLE
Don't emit dots

### ISSUE THREAD

**Issue by ffMathy** [pulumi/pulumi#14069]
It'd be great if we could have a command-line flag for not emitting "dots" while previewing or updating.

When running via NX, my build output looks like this:
<img width="301" alt="image" src="https://github.com/pulumi/pulumi/assets/2824010/d9753785-7cdd-4895-a934-225c0cb315fc">

It adds thousands of lines just containing a dot, creating clutter.

**Comment by blampe** [comment]
+1 I think it would make sense to disable dots automatically if the terminal isn't interactive.

**Comment by ffMathy** [comment]
> ould make sense to disable dots automatically if the terminal isn't interactive.

That's a great idea!

**Comment by Frassle** [comment]
CI terminals don't register as interactive, but we need to emit output to those so CI systems don't think the jobs have stalled.

**Comment by ffMathy** [comment]
@Frassle interesting. What kind of CI systems detect lack of output as stalling? If it's only a handful, can we optimize for those individually?

Alternatively, if behind a flag, it could be opt-in. I wouldn't mind my job in GitHub Actions being marked as stalled, as long as it doesn't actually terminate the build.

A third option could be to emit the dots less often. Perhaps once a minute, or once every 5 minutes?

**Comment by Frassle** [comment]
> What kind of CI systems detect lack of output as stalling?

This is definitely not an area I consider myself well informed in. Originally this was added because of TravisCI, but there's comments in the codebase about Jenkins and we have similar heartbeat messages in scripts that I know we've only ever run on GitHub Actions.

> Alternatively, if behind a flag, it could be opt-in. I wouldn't mind my job in GitHub Actions being marked as stalled, as long as it doesn't actually terminate the build.

If this was a flag it would have to be opt-out. Being seen as a bit spammy with dots is _way_ worse than a CI system thinking a `pulumi up` has stalled and killing it.

> A third option could be to emit the dots less often. Perhaps once a minute, or once every 5 minutes?

That's probably reasonable, I think the current timer is like 20 seconds. But one of the reasons for this ticker is so new users know that stuff is happening.

Maybe an envvar/option to set the time between ticks, with negative values to turn it off?

**Comment by Frassle** [comment]
> If this was a flag it would have to be opt-out. Being seen as a bit spammy with dots is way worse than a CI system thinking a pulumi up has stalled and killing it.

Appears I had too much whisky before writing this sentence. I of course mean it the other way round. Getting killed by a CI system is way worse than being seen as a bit spammy.

**Comment by ffMathy** [comment]
> That's probably reasonable, I think the current timer is like 20 seconds. But one of the reasons for this ticker is so new users know that stuff is happening.
Hmmm, but why not just write something like "Updating - this might take a while" or something.

> Maybe an envvar/option to set the time between ticks, with negative values to turn it off?
That would work too, although less obvious. Most likely not going to get discovered by users. There's a benefit to being part of the `--help` instructions.

**Comment by ffMathy** [comment]
The problem gets amplified when using Pulumi with `nx` and many projects. We have many thousand lines of just dots, making it almost impossible to find a root cause for an issue.

**Comment by dirien** [comment]
@blampe and @Frassle:

after meeting with @ffMathy I fully support a way to disable the "activity indicator"
