### ISSUE TITLE
Typescript StackReference and String[]

### ISSUE THREAD

**Issue by stanislas-draunet-maif** [pulumi/pulumi#14102]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Hi, I'm having trouble with the stackReference of an object with type string[] in typescript. I can easily retrieve the value for an Object with `pulumi.StackReference(`${ORG}/${project}/${stack}`).outputs` or directly from a string with
`const foo = new pulumi.StackReference(`${ORG}/${project}/${stack}`).getOutput('foo')`

but, if I want to retrieve a string[] Array, I have to use .apply() to convert it to a string[] so that I can do a .map().
Moreover, these calls seem to be asynchronous, so I need to include the creation of azure resources in an apply()

Next example is work, but i don't like it

Stack Output from my reference Stack :

```json
Outputs:
  ~ entryList: [
      + [0]: "foo"
      + [1]: "bar"
      + [2]: "foo2"
      + [3]: "bar2"
    ]
```

```typescript
const httpListeners: input.network.ApplicationGatewayHttpListenerArgs[] = []

const stackRef = new pulumi.StackReference(`${ORG}/${project}/${stack}`)
  .getOutput('entryList')
  .apply((o) => <string[]>o)
  .apply((value) => {
        value.map((liste, index) => {
            console.log(liste)
             httpListeners.push({
                ....  // i add config for appgw
            })

        })
  })

stackRef.apply((o) => {
    const agw = new network.ApplicationGateway(`my-apgw`, {
      ....
      httpListeners,
    })
})
```

If I do this (see in the next example), it doesn't work, because typescript doesn't detect the .push() before the appgw is created/updated, so the appgw doesn't update its configuration. This looks like an async operation

```typescript
const httpListeners: input.network.ApplicationGatewayHttpListenerArgs[] = []

const stackRef = new pulumi.StackReference(`${ORG}/${project}/${stack}`)
  .getOutput('entryList')
  .apply((o) => <string[]>o)
  .apply((value) => {
        value.map((liste, index) => {
            console.log(liste)
             httpListeners.push({
                ....  // i add config for appgw
            })

        })
  })

const agw = new network.ApplicationGateway(`my-apgw`, {
  ....
  httpListeners,
})
```

I would like to write

```typescript
const httpListeners: input.network.ApplicationGatewayHttpListenerArgs[] = []

const stackRef = new pulumi.StackReference(`${ORG}/${project}/${stack}`)
  .getOutput('entryList') as string[]


stackRef.map((liste, index) => {
        console.log(liste)
        httpListeners.push({
          ....  // i add config for appgw
        })
})

const agw = new network.ApplicationGateway(`my-apgw`, {
    ....
    httpListeners,
})

```

What do you think ? where i'm wrong ?

**Comment by Zaid-Ajaj** [comment]
Hi @stanislas-draunet-maif, I see what the problem is. We have recently introduced `getOutputDetails` to make this process easier:
```ts
const stackRef = new pulumi.StackReference(`${ORG}/${project}/${stack}`)
const entryListOutput  = await stackRef.getOutputDetails("entryList")
const entryList = entryListOutput.value as string[]
```
You can then use `entryList.map` like you would usually do in TypeScript code. Notice that we `await` the call to `stackRef.getOutputDetails` because it returns a promise. So the entry point of your TypeScript program must be `async` as follows:
```ts
export = async () => {
    const stackRef = new pulumi.StackReference(`${ORG}/${project}/${stack}`)
    const entryListOutput  = await stackRef.getOutputDetails("entryList")
    const entryList = entryListOutput.value as string[]

    // .. the rest of the program
}
```
That said, the reason your code didn't work before is because you using `push` (synchronous) inside `apply` which is asynchronous. If you want to work with `getOutput` you would have to write the following:
```ts
const agw = new network.ApplicationGateway(`my-apgw`, {
  ....
  httpListeners: stackRef..getOutput('entryList')
  .apply((o) => <string[]>o)
  .apply((entryList) => {
        return entryList.map((entry, index) => {
            // create a list of HTTP listeners here
             return {
                // add entry config for app gateway
            }
        })
  }),
})
```

**Comment by stanislas-draunet-maif** [comment]
thanks @Zaid-Ajaj, 

I understand and I have tested this. but await is not accepted with pulumi by default, it tells me this:

![image](https://github.com/pulumi/pulumi/assets/100131854/ff5cbd40-7299-423d-b124-cdc3db1b4f1b)

the vscode message is : `Top-level 'await' expressions are only allowed when the 'module' option is set to 'es2022', 'esnext', 'system', 'node16', or 'nodenext', and the 'target' option is set to 'es2017' or higher.ts(1378)`

Withi pulumi up, i've got this :

![image](https://github.com/pulumi/pulumi/assets/100131854/b9e5b363-c022-48f3-89b4-26758c40d83d)


I checked if my tsconfig.json was correct as in the pulumi template <https://github.com/pulumi/templates/blob/master/azure-typescript/tsconfig.json> , and yes it is

```json
{
    "compilerOptions": {
        "strict": true,
        "outDir": "bin",
        "target": "es2016",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "experimentalDecorators": true,
        "pretty": true,
        "noFallthroughCasesInSwitch": true,
        "noImplicitReturns": true,
        "forceConsistentCasingInFileNames": true
    },
    "files": [
        "index.ts"
    ]
}
```

So, i change module to `es2022 `

But now i have this 
![image](https://github.com/pulumi/pulumi/assets/100131854/a47b6b1d-492c-47a1-a1b5-699710ae7f41)

in the docs I didn't find an explanation of how to configure your project properly with await

Any ideas?

**Comment by stanislas-draunet-maif** [comment]
sorry, i think a understand, i forget this 
```typescript
export = async () => {
    const stackRef = new pulumi.StackReference(`${ORG}/${project}/${stack}`)
    const entryListOutput  = await stackRef.getOutputDetails("entryList")
    const entryList = entryListOutput.value as string[]

    // .. the rest of the program
}
```
