### ISSUE TITLE
Multiple versions of @pulumi/pulumi detected when only one is package-lock.json

### ISSUE THREAD

**Issue by mastoj** [pulumi/pulumi#14128]
### What happened?

Some of my runs in my demo automation project ends with the following error:

> pulumi:pulumi:Stack resource-groups-tomas2  error: Detected multiple versions of '@pulumi/pulumi' in use in an inline automation api program.\n" +
        '    pulumi:pulumi:Stack resource-groups-tomas2 **failed** 1 error\n' +
        '\n' +
        'Diagnostics:\n' +
        '  pulumi:pulumi:Stack (resource-groups-tomas2):\n' +
        "    error: Detected multiple versions of '@pulumi/pulumi' in use in an inline automation api program.\n" +
        "    Use the yarn 'resolutions' field to pin to a single version: https://github.com/pulumi/pulumi/issues/5449.\n" +

I'm running version 3.86.0, and that is the only version of pulumi I can find in my project. 

### Example

The demo project I have is the following one: https://github.com/mastoj/pulumi-automation-demo-v2/tree/bug/multiple-versions. The project doesn't require more than you being logged into pulumi, since I all create are some outputs in this branch.

Not a ton going on in that branch since I'm still bootstrapping the project. Steps that might reproduce (it doesn't happen every time):

1. npm install
2. npm run dev
3. http://localhost:3000
4. Click "Resource groups"
5. Click "new"
6. Repeat 5 and 6 a couple of times

You might also need to try to delete click the delete button of a resource group and then try to create again if you can't reproduce by only creating. 

### Output of `pulumi about`

CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Host     
OS       darwin
Version  13.4.1
Arch     arm64

### Additional context

The error message references this closed issue: https://github.com/pulumi/pulumi/issues/5449

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
I'm able to reproduce this by creating a new resource group, e.g. `test1`, deleting `test1`, and then creating `test1` again.

The reason for the error has something to do with how Next.js is loading `@pulumi/pulumi` modules. Each time `./app/api/resource-groups/route.ts` runs, it ends up running this one or more times:

https://github.com/pulumi/pulumi/blob/58aeed028e35643ca38486ce7b23aa10d7390dd5/sdk/nodejs/runtime/settings.ts#L529-L532

which screws up our SxS detection, and we end up throwing an error.

Now that https://github.com/pulumi/pulumi/issues/5449 has been addressed, I think we can simply remove these checks, as they're no longer needed. Indeed, if I comment out the check in the local copy of `node_modules/@pulumi/pulumi/runtime/settings.js`, everything works correctly (AFAICT) without any SxS errors. I'll go ahead and open a PR that removes these unnecessary checks.

**Comment by justinvp** [comment]
@mastoj, in the meantime, to workaround this, you could temporarily edit your local copy of `node_modules/@pulumi/pulumi/runtime/settings.js`. At the bottom of the file, there is a `runSxSCheck` function. You can comment out or delete the entire content of that function:

```javascript
function runSxSCheck() {
    // const envSxS = process.env[pulumiSxSEnv];
    // process.env[pulumiSxSEnv] = sxsRandomIdentifier;
    // if (!isInline) {
    //     return;
    // }
    // // if we see a different identifier, another version of pulumi has been loaded and we should fail.
    // if (!!envSxS && envSxS !== sxsRandomIdentifier) {
    //     throw new Error("Detected multiple versions of '@pulumi/pulumi' in use in an inline automation api program.\n" +
    //         "Use the yarn 'resolutions' field to pin to a single version: https://github.com/pulumi/pulumi/issues/5449.");
    // }
}
```

**Comment by mastoj** [comment]
@justinvp , awesome. That works for me now, but it would be good if the PR was done before the conference talk. It isn’t ideal to show code where they need to modify the dependency :)
