### ISSUE TITLE
[codegen/python] Azure Native examples sometimes use `...ResponseArgs` for input instead of `...Args`

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi#14145]
### What happened?

For instance:
```py
workspace = azure_native.databricks.Workspace("workspace",
    location="westus",
    managed_resource_group_id="/subscriptions/subid/resourceGroups/myManagedRG",
    parameters=azure_native.databricks.WorkspaceCustomParametersResponseArgs(
                                                                ^^^^^^^^
        prepare_encryption=azure_native.databricks.WorkspaceCustomBooleanParameterArgs(
            value=True,
        ),
    ),
    resource_group_name="rg",
    workspace_name="myWorkspace")
```

Other cases were also reported that look fine now, like [servicebus.Namespace](https://www.pulumi.com/registry/packages/azure-native/api-docs/servicebus/namespace/#namespacecreate). That and the fact that the wrong examples use some correct and some incorrect types, makes me think there's some non-determinism going on. 

This causes downstream issues pulumi/pulumi-azure-native#2084, pulumi/pulumi-azure-native#2083, pulumi/pulumi-azure-native#2575, pulumi/pulumi-azure-native#2608.

Related but not the same: https://github.com/pulumi/pulumi/pull/13703

### Example

  - https://www.pulumi.com/registry/packages/azure-native/api-docs/databricks/workspace/#create-a-workspace-which-is-ready-for-customer-managed-key-cmk-encryption (`WorkspaceCustomParametersResponseArgs`)
  - https://www.pulumi.com/registry/packages/azure-native/api-docs/containerinstance/containergroup/ (`NetworkProfileResponseArgs` and others)
  - https://www.pulumi.com/registry/packages/azure-native/api-docs/containerinstance/containergroup/ (`IpAddressResponseArgs`)

### Output of `pulumi about`

n/a

### Additional context

This is the HCL (.pp) that the Azure Native provider emits for the Databricks example:

```
resource workspace "azure-native:databricks:Workspace" {
	location = "westus"
	managedResourceGroupId = "/subscriptions/subid/resourceGroups/myManagedRG"
	parameters = {
		prepareEncryption = {
			value = true
		}
	}
	resourceGroupName = "rg"
	workspaceName = "myWorkspace"
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Fixed by https://github.com/pulumi/pulumi-azure-native/pull/3135, all linked examples look good now
