### ISSUE TITLE
Python dynamic provider use occasionally causes timeouts after 60+ minutes during refresh

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#14159]
A customer is reporting that they usually see refreshes take 2-3 minutes, but on occasion, they're seeing deployments time out after an hour during refreshes (CI timeout).

Some internal investigation of these updates found that all ~2800 EngineEvents were timestamped within 15 seconds of each other, then suddenly stop. The last engine event is `resourcePreEvent`, and not a `summaryEvent`, and it's for a resource of type `pulumi-python:dynamic:Resource`. Also of note: the resource preview event count does not match the resource outputs event count. There are 1335 resource preview events and 1246 resource outputs events, which matches the 89 Python dynamic resources exactly.

This may be an unhandled bug in the dynamic provider that isn't propagated back, or perhaps a crash, or OOM in the dynamic provider.

This failure mode is similar to an issue with Node.js dynamic providers that was fixed by https://github.com/pulumi/pulumi/pull/6673. There is an open issue to port those improvements to Python: https://github.com/pulumi/pulumi/issues/6675

**Comment by tusharshahrs** [comment]
[Customer Support Issue # 1230](https://github.com/pulumi/customer-support/issues/1230)

**Comment by justinvp** [comment]
https://github.com/pulumi/pulumi/pull/14255 may help as we've seen some oddities with sleep not being interrupted.

**Comment by justinvp** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/14491
