### ISSUE TITLE
pulumi new to work with nonempty dirs

### ISSUE THREAD

**Issue by desteves** [pulumi/pulumi#14158]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

As a developer I don't always follow the linear path of creating a brand new empty directory before getting started with code. I'd like to be able to run `pulumi new` on a directory that has *some* code so as to improve the developer experience. This is similar to how one can run `git init` or `go mod init` in already populated directories.

### Affected area/feature

Pulumi CLI

**Comment by Frassle** [comment]
There's a `--force` flag for this:
```
 -f, --force                     Forces content to be generated even if it would change existing files
```
