### ISSUE TITLE
When creating stack from `pulumi new` stackname has repeated name

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#1417]
Private beta user feedback: 

> Why does my default stack name have hello-aws-javascript twice? (hello-aws-javascript-hello-aws-javascript-dev)

It looks like we're including the project name in the name for `pulumi:pulumi:Stack`.

**Comment by lukehoban** [comment]
We'll look at this along with https://github.com/pulumi/pulumi/issues/2039.

**Comment by ellismg** [comment]
Once we do #2039, we'll change the defaults from `pulumi new` to just propose `dev`  instead of `<stack-name>-dev`.  That should address this issue.

Note that we will continue to name the synthetic static object `<project-name>-<stack-name>`.
