### ISSUE TITLE
Consider not including StringAsset text in checkpoint

### ISSUE THREAD

**Issue by mmdriley** [pulumi/pulumi#1422]
When we create e.g. an `aws:lambda/function:Function`, we only store the hash for the `node_modules` tree, but we store the hash _and_ the text for the `__index.js` asset:

```json
"type": "aws:lambda/function:Function",
"inputs": {
    "code": {
        "assets": {
            "./node_modules/": {
                "4dabf18193072939515e22adb298388d": "0def7320c3a5731c473e5ecbe6d01bc7",
                "hash": "88f293e1444ea49fc7f3e191b57f076ce7de5bab88bcbcd963b66462cd417b3c",
                "path": "./node_modules/"
            },
            "__index.js": {
                "4dabf18193072939515e22adb298388d": "c44067f5952c0a294b673a41bacd8c17",
                "hash": "73d423d439e77916b1fa3c176c2bc26f8591995a52375b5eb8281e1a10bf76e5",
                "text": "<9 kilobytes of text>"
            }
        },
        "hash": "30e85eed0439e12e92fbe9433592be51f5249420b1fb10a451a35dc433baeb97"
    },
    "handler": "__index.handler",
},
```

We only need the hash to know if the resource needs replacement. I guess it's true that we would need the text if we wanted to display a diff, but in this case the diff would be of generated code and is less likely to be useful. Meanwhile this would buy us a nontrivial reduction in checkpoint size (and corresponding transfer times).

**Comment by lukehoban** [comment]
I'm fine calling this "by design" for now.  We do in fact use this text now to present a diff, so changing this would mean removing that feature.  I don't think we have sufficient evidence that that is preferable to the status quo.
