### ISSUE TITLE
Add parameter or new method to allow `pulumi stack ls -a`

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#14226]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
currently, automation api allows for listing all stacks within a project but not all stacks in the scope of a user. Eg- `pulumi stack ls -a`.

### Affected area/feature
add a new method or flag to allow this behavior to be achieved.

**Comment by zbuchheit** [comment]
@justinvp @Frassle I am curious your thoughts as to how/where this might be implemented given the automation api and cli design. I looked at the code base and didn't really see an obvious spot where this would land given it is a more of an org-scoped command.

**Comment by phillipedwards** [comment]
I implemented this for go but (1) tests were still failing and I havent resolved them (2) I hate doing SDK specific things...
https://github.com/pulumi/pulumi/tree/pedwards/aa-list-all-stacks
