### ISSUE TITLE
Flaky test with DLL32 loading issue on Windows

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#14240]
### What happened?

```
=== NAME  TestAccProviderConfig
    command.go:83: Invoke 'C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin\pulumi.exe stack export --file C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az417-3-provider-c-c0c95d023789257115\stack.json' failed: exit status 2
panic: Failed to load user32: A dynamic link library (DLL) initialization routine failed.

goroutine 1 [running]:
syscall.MustLoadDLL(...)
	/opt/hostedtoolcache/go/1.21.1/x64/src/syscall/dll_windows.go:94
github.com/atotto/clipboard.init()
	/home/runner/go/pkg/mod/github.com/atotto/clipboard@v0.1.4/clipboard_windows.go:22 +0x347

    command.go:103: Wrote output to C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az417-3-provider-c-c0c95d02-1541851738\command-output\pulumi-export.20231012-180950.a95cd.log
    program.go:1335: Destroying stack
    command.go:34: **** Invoke 'C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview' in 'C:\Users\RUNNER~1\AppData\Local\Temp\p-it-fv-az417-3-provider-c-c0c95d02-1541851738'
    command.go:83: Invoke 'C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin\pulumi.exe destroy --non-interactive --yes --skip-preview' failed: exit status 2
panic: Failed to load user32: A dynamic link library (DLL) initialization routine failed.
```

Might be a good idea to find out why Pulumi CLI is initializing clipboard. 

### Example

Found during CI runs.

### Output of `pulumi about`

v3.86.0

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
I've seen this before, and mitigated by forking and then getting an upstream patch to `xanzy/ssh-agent`:

https://github.com/pulumi/pulumi/pull/10486

**Comment by t0yv0** [comment]
Unfortunately still experience this issue https://github.com/pulumi/pulumi-terraform-bridge/actions/runs/6551251659/job/17792051156?pr=1446#step:9:5409 ; possibly not yet removed from Pulumi CLI fully.

**Comment by AaronFriel** [comment]
@t0yv0 ah, sorry - to be clear, I pattern matched and this is the same *kind* of error as fixed in #10486. It looks like we would want to patch the upstream `github.com/atotto/clipboard` in the same way.

**Comment by guifran001** [comment]
The reference in pulumi on the clipboard is in this file:
https://github.com/pulumi/pulumi/blob/1a72f09a64c8f806b8dd24c08404366e45fc07d8/sdk/go/common/util/cmdutil/console.go
that is using `github.com/charmbracelet/bubbles/textinput` which depends on `atotto/clipboard`.

I guess `atotto/clipboard` should use `NewLazySystemDLL` instead of `MustLoadDLL`

**Comment by VenelinMartinov** [comment]
Just hit this again: https://github.com/pulumi/pulumi-terraform-bridge/actions/runs/7759249788/job/21162896094

**Comment by VenelinMartinov** [comment]
Another one: https://github.com/pulumi/pulumi-terraform-bridge/actions/runs/8484037216/job/23246252827?pr=1818

**Comment by tgummerer** [comment]
A recent occurrence:

```
=== FAIL: go/auto TestRemoveWithForce (34.37s)
 local_workspace_test.go:222: up failed, err: could not get outputs: exit status 2
        code: 2
        stdout:
        stderr: panic: Failed to load user32: A dynamic link library (DLL) initialization routine failed.

        goroutine 1 [running]:
        syscall.MustLoadDLL(...)
        	/opt/hostedtoolcache/go/1.23.1/x64/src/syscall/dll_windows.go:94
        github.com/atotto/clipboard.init()
        	/home/runner/go/pkg/mod/github.com/atotto/clipboard@v0.1.4/clipboard_windows.go:22 +0x347
```

**Comment by VenelinMartinov** [comment]
Hit this yesterday: https://github.com/pulumi/pulumi-terraform-bridge/actions/runs/11053647383/job/30708522112#step:9:11702

**Comment by VenelinMartinov** [comment]
Hit this again: https://github.com/pulumi/pulumi-terraform-bridge/actions/runs/11130117657/job/30928763739
@tgummerer thank you for taking this on - we are hitting this multiple times a week in the bridge now.

**Comment by tgummerer** [comment]
https://github.com/pulumi/pulumi/pull/17410 should hopefully fix this.  For future reference, [this upstream commit] seems what is necessary: https://github.com/tgummerer/clipboard/commit/d02d263e614e9ce8253944be55e07c8e4112529f#diff-a65430267e4965ff8e93ebe5d7c32fb753dddcc72891a434c8213e947491dc3dR32

**Comment by tgummerer** [comment]
@VenelinMartinov note that for the bridge you might also have to add similar `replace` statements as I did in the above mentioned PR to actually get this fixed (I don't know if they propagate properly downstream 🤔 )

**Comment by VenelinMartinov** [comment]
Replaces do not get propagated to dependancies.

Is the issue happening in the pulumi CLI or in the SDK/ test modules? If it's the second then we will need the same replace in the bridge.

**Comment by tgummerer** [comment]
I think it's mostly a CLI problem, though the library is pulled into the SDK, so I'm guessing it's getting initialized *somewhere*.  Not sure if that would affect the bridge though.  In any case I guess you can see if there's any flakes still with this update and then add the replaces as necessary.

**Comment by VenelinMartinov** [comment]
Yeah, fair, thanks for addressing this!
