### ISSUE TITLE
`pulumi package get-schema` output may contain diagnostics mixed with schema

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#14252]
When using `pulumi package get-schema` to get the JSON representation of a Pulumi Package Schema, as below, the output may contain a spurious line "Downloading provider: ..."

```console
$ pulumi package get-schema aws | tee aws.json
Downloading provider: aws
{
  ...
```

## Root causing

Looking into why this is, we find that it's logged in `workspace.InstallPlugin` to the plugin host. The plugin host uses a plugin context with a default sink, which configures stdout for info messages.

https://github.com/pulumi/pulumi/blob/ca12edfb4ef22d9cd09abcf7e026125da281dc3b/pkg/cmd/pulumi/package.go#L123-L127

For commands like `pulumi package get-schema` which return structured output, we should reserve stdout for intentional writes and send all logging to stderr.

Does this affect other commands such as `pulumi stack export`, or commands with JSON output modes such as `pulumi about`, `pulumi stack output`?

**Comment by justinvp** [comment]
> we should reserve stdout for intentional writes and send all logging to stderr.

Yeah

> Does this affect other commands such as `pulumi stack export`, or commands with JSON output modes such as `pulumi about`, `pulumi stack output`?

It may affect others, but likely not these particular ones.

**Comment by Frassle** [comment]
https://github.com/pulumi/pulumi/pull/14134 fixes this for the "Downloading provider" message which is now routed to stderr.

**Comment by mikhailshilkov** [comment]
@Frassle can we close as fixed?

**Comment by Frassle** [comment]
Yeh I don't know of anywhere we're logging to stdout anymore.
