### ISSUE TITLE
pulumi up --target affects providers on non-targeted resources

### ISSUE THREAD

**Issue by jesse-triplewhale** [pulumi/pulumi#14254]
### What happened?

1. Our pulumi stack has a resource A, for which we are using the default provider.
2. We change resource A so that we are passing it a provider. Run `pulumi up` to use the new provider
3. Remove the custom provider in the code on resource A (for example, someone has an old version of the code), then run `pulumi up --target B` (a different resource)
4. Re-add the custom provider (back to the original branch) - a non-targeted `pulumi up` now tries to recreate resource A because A's provider was changed back in step 3

### Example

branch A:
```
const mongoCluster = new mongodbatlas.Cluster(
  'mongo-cluster',
  { ...params },
  { protect: true}
);

const bucket = new gcp.storage.Bucket(bucketName, {
  location: location,
  name: bucketName,
});
```

branch B: 
```
const mongoCluster = new mongodbatlas.Cluster(
  'mongo-cluster',
  { ...params },
  { protect: true, provider: new mongodbatlas.Provider(...) }
);

const bucket = new gcp.storage.Bucket(bucketName, {
  location: location,
  name: bucketName,
});
```

1. state is as described in branch A

2. branch B
```
# correctly updates the provider
pulumi up
```

3. branch A
```
# incorrectly updates the provider
pulumi up --target urn:...gcp:storage/bucketObject...
```

4. branch B
```
# tries to recreate the resource because of the provider having been changed in step 3
pulumi up
```

### Output of `pulumi about`

```
❯ pulumi about      
CLI          
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME           VERSION
cloudflare     5.12.0
datadog        4.23.0
ec             0.7.0
gcp            6.67.0
google-native  0.31.1
kubernetes     4.4.0
mongodbatlas   3.11.0
nodejs         unknown
postgresql     3.10.0
random         4.14.0
slack          0.4.2

Host     
OS       darwin
Version  13.4
Arch     arm64

This project is written in nodejs: executable='/Users/jessegrodman/.nvm/versions/node/v18.17.1/bin/node' version='v18.17.1'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
It would be useful to say what this fails with? Does it crash, error, does the whole deployment fail or just the mongo resource? At a glance I suspect this _might_ be design of the system, but easier to confirm that if you can let us know exactly how it failed.

**Comment by jesse-triplewhale** [comment]
When I `pulumi up` in step 4 from above, pulumi tries to recreate a resource which was *not* targeted in step 3. pulumi tries to recreate the `mongo-cluster` because of the provider code change. However, before the targeted `pulumi up` in step 3, pulumi would not try to recreate the resource

```
❯ pulumi up
Previewing update ([stack name])

View in Browser (Ctrl+O): [url]

     Type                               Name                          Plan        Info
     pulumi:pulumi:Stack               [stack name]              
 +-  ├─ gcp:storage:BucketObject        api-gateway-config-json       replace     [diff: ~content,detectMd5hash]
...
     └─ mongodbatlas:index:Cluster      mongo-cluster                             1 error


Diagnostics:
  mongodbatlas:index:Cluster (mongo-cluster):
    error: unable to replace resource "[urn...]::mongodbatlas:index/cluster:Cluster::mongo-cluster"
    as it is currently marked for protection. To unprotect the resource, remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`
```

**Comment by Frassle** [comment]
But you have changed the provider in step 2, and you do have protect set so this looks like it should want to do a replace but fail. 
Are you saying that if you skip step 3 in your repro that `pulumi up` doesn't replace the mongo Cluster?

**Comment by Frassle** [comment]
Turns out this is "fixed" by https://github.com/pulumi/pulumi/pull/15716. I've raised https://github.com/pulumi/pulumi/pull/17254 to add a test to ensure this doesn't regress. We'll track fixing this better (making it properly work rather than being an error) in https://github.com/pulumi/pulumi/issues/15732.
