### ISSUE TITLE
Pulumi preview typo untracked resource (retainOnDelete)

### ISSUE THREAD

**Issue by Jimmy89** [pulumi/pulumi#14277]
### What happened?

If my stack replaces a resource with the param `retainOnDelete: true`, pulumi preview informs me about this.
There is a small typo within that information, example: 

```
nfo: This update will leave 1 resource(s) untracked in your environment:
    - aws-native:stepfunctions:StateMachineVersion step-function-stable-version
```

`nfo` should be `Info`.

### Example

See example above: `nfo` -> `Info`

### Output of `pulumi about`

```
NAME                VERSION
@pulumi/aws         6.5.0
@pulumi/aws-native  0.81.0
@pulumi/pulumi      3.89.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
I haven't tried it out yet, but the code to emit this is at:

https://github.com/pulumi/pulumi/blob/226d9b664df8cfb0afc843ac1f2e40df7d0305fa/pkg/backend/apply.go#L135-L152

We do have `info` on line 135. Not sure yet why the `i` in `info` isn't being emitted.

**Comment by Frassle** [comment]
I think the backspace character on line 135 might be the issue. But it's probably needed in other cases.
