### ISSUE TITLE
Duplicate resource URN for pulumi Stack after importing second resource

### ISSUE THREAD

**Issue by jabbrwcky** [pulumi/pulumi#14286]
### What happened?

I started out with a fresh project using the aws-go template. using `pulumi v3.88.1`, `go v1.21.3`.

After importing the first resource (`aws:ssoadmin/permissionSet:PermissionSet                      urn:pulumi:atlas::aws-sso::aws:ssoadmin/permissionSet:PermissionSet::administrators`), pulumi up works as expected.

After importing the second resource (`aws:ssoadmin/managedPolicyAttachment:ManagedPolicyAttachment  urn:pulumi:atlas::aws-sso::aws:ssoadmin/managedPolicyAttachment:ManagedPolicyAttachment::administratorPolicy`)
`pulumi refresh` works, but `pulumi up` fails.

```shell
> pulumi refresh
Previewing refresh (atlas):
     Type                                     Name                 Plan
     pulumi:pulumi:Stack                      aws-sso-atlas
     ├─ aws:ssoadmin:ManagedPolicyAttachment  administratorPolicy
     └─ aws:ssoadmin:PermissionSet            administrators

Resources:
    3 unchanged

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be.
 yes
Refreshing (atlas):
     Type                                     Name                 Status
     pulumi:pulumi:Stack                      aws-sso-atlas
     ├─ aws:ssoadmin:PermissionSet            administrators
     └─ aws:ssoadmin:ManagedPolicyAttachment  administratorPolicy

Resources:
    3 unchanged

Duration: 1s
```

```shell
> pulumi up
Previewing update (atlas):
     Type                 Name           Plan     Info
     pulumi:pulumi:Stack  aws-sso-atlas           1 error

Diagnostics:
  pulumi:pulumi:Stack (aws-sso-atlas):
    error: Duplicate resource URN 'urn:pulumi:atlas::aws-sso::pulumi:pulumi:Stack::aws-sso-atlas'; try giving it a unique name
```

### Example

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v6/go/aws/ssoadmin"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		instances, err := ssoadmin.GetInstances(ctx)
		if err != nil {
			return err
		}

		ctx.Export("instanceArns", pulumi.ToStringArray(instances.Arns))
		ctx.Export("instances", pulumi.ToStringArray(instances.IdentityStoreIds))

		adminPS, err := ssoadmin.NewPermissionSet(ctx, "administrators", &ssoadmin.PermissionSetArgs{
			Description: pulumi.String("Access All Areas"),
			InstanceArn: pulumi.String("arn:aws:sso:::instance/ssoins-..."),
			Name:        pulumi.String("AdministratorAccess"),
		}, pulumi.Protect(true))
		if err != nil {
			return err
		}

		pulumi.Run(func(ctx *pulumi.Context) error {
			_, err := ssoadmin.NewManagedPolicyAttachment(ctx, "administratorPolicy", &ssoadmin.ManagedPolicyAttachmentArgs{
				InstanceArn:      pulumi.String("arn:aws:sso:::instance/ssoins-..."),
				ManagedPolicyArn: pulumi.String("arn:aws:iam::aws:policy/AdministratorAccess"),
				PermissionSetArn: adminPS.Arn,
			}, pulumi.Protect(true))
			if err != nil {
				return err
			}
			return nil
		})

		return nil
	})
}
```

### Output of `pulumi about`

CLI
Version      3.88.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME  VERSION
aws   6.2.1
go    unknown

Host
OS       darwin
Version  14.0
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.21.3 darwin/arm64'

Current Stack: organization/aws-sso/atlas

TYPE                                                          URN
pulumi:pulumi:Stack                                           urn:pulumi:atlas::aws-sso::pulumi:pulumi:Stack::aws-sso-atlas
pulumi:providers:aws                                          urn:pulumi:atlas::aws-sso::pulumi:providers:aws::default
aws:ssoadmin/permissionSet:PermissionSet                      urn:pulumi:atlas::aws-sso::aws:ssoadmin/permissionSet:PermissionSet::administrators
aws:ssoadmin/managedPolicyAttachment:ManagedPolicyAttachment  urn:pulumi:atlas::aws-sso::aws:ssoadmin/managedPolicyAttachment:ManagedPolicyAttachment::administratorPolicy

Found no pending operations associated with atlas

Backend
Name           CARE-MB-0028.local
URL            s3://cc-pulumi
User           jens.hausherr
Organizations
Token type     personal

Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-aws/sdk/v6  6.2.1
github.com/pulumi/pulumi/sdk/v3      3.89.0

Pulumi locates its logs in /var/folders/1_/zc2qtwk53kz8sc6h1d8_d0bc0000gp/T/ by default

### Additional context

`pulumi about` seems to be unable to handle `go.work` files that exist in the directory hierarchy:

```
> pulumi about

...

Pulumi locates its logs in /var/folders/1_/zc2qtwk53kz8sc6h1d8_d0bc0000gp/T/ by default
warning: Failed to get information about the Pulumi program's dependencies: load go.mod: open /.../go.mod
/.../go.mod
/.../go.mod
/.../go.mod
/.../go.mod
/.../go.mod
...
/.../go.mod: file name too long
```

This is only a secondary observation, as the original issue occurs also if no `go.work` file is found in the dir hierarchy.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
You've nested a call to `pulumi.Run` inside a call to `pulumi.Run`. Each run call tries to setup a new stack, this is not supported, we only expect one stack per program. Just remove the second Run call and inline it's code to the call site.

**Comment by Frassle** [comment]
> Ok, still the issue with go.work files in pulumi about remains. I guess this should be a separate issue.

Yeh if you raise an issue for that we can take a look.
