### ISSUE TITLE
Resource changes do not consider changes to component outputs

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#1429]
This is the root cause of the behavior in https://github.com/pulumi/pulumi/issues/1410. If component output changes had been considered in that issue's "no-op" update, the "no-op" update would not have been considered a "no-op".

**Comment by pgavlin** [comment]
This is probably an M16-sized issue.

**Comment by adaniline-traderev** [comment]
Is this issues still open? I have the same issue where a new output is not saved in a stack.

**Comment by lukehoban** [comment]
I'm not clear on what exactly this is tracking now that #1410 was fixed.  I'm going to close this out, but if there is a clear repro of a remaining issue that isn't already tracked elsewhere - we can add that and reopen.
