### ISSUE TITLE
Real controller interface/service

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#143]
At the moment, our deployment orchestration is incredibly naive.  There are known issues around the way state is managed (see #101 and #111), the source of truth is wrong (see #142), the extensibility points aren't there (like logging), and all deployments are driven by a synchronous CLI, and there is no notion of a service or asynchronous deployment.

This work item tracks the significant design and architecture work, and then more modest implementation, to build this right.  It should likely entail (at least) these steps:

* Create a deployment controller interface that can be remoted over a gRPC connection
* Implement this interface for the local, synchronous CLI scenarios
* Implement this interface for the remote, service scenarios (and support asynchronous)
* Add a command to check the status of an asynchronous deployment
* Create a way for the CLI to specify the remote service
* Add a way to configure an environment to use one particular remote service by default

In addition, we should address #142 and we hope #101 and #111 are addressed by these items.

**Comment by hausdorff** [comment]
Let's re-open this to track signaling resource providers that cancellation has occurred, _cf_., https://github.com/pulumi/pulumi/blob/59672597953cefc656719ea81a17644f75a86158/pkg/resource/plugin/context.go#L58

**Comment by hausdorff** [comment]
Oh, sorry, we're tracking this already with #1613. My b.
