### ISSUE TITLE
pulumi commands to config stacks ESC environments imports

### ISSUE THREAD

**Issue by cleverguy25** [pulumi/pulumi#14304]
Allow pulumi CLI to set ESC environment imports.  Syntax is a suggestion only

`pulumi config env` 
Get current  environment imports

`pulumi config env add <env_name>`
Add a new env to the import list

`pulumi config env rm <env_name>`
Remove an environment from the import list

`pulumi config env set-order <env_name> 0`
Change the order of an environment

**Comment by MitchellGerdisch** [comment]
I think there should be a version like 
`pulumi config env add <env1> <env2> <env3>` 
which would just add them in that order.

I also feel like there should be a version like
`pulumi config env set add <env1> <env2> <env3>` that just overwrites the current list in the `environment:` section with the given list in the given order.

**Comment by cleverguy25** [comment]
SImilar issue in the esc repo https://github.com/pulumi/esc/issues/102
