### ISSUE TITLE
Panic occurs when running pulumi preview or pulumi up after upgrading to v3.90.0

### ISSUE THREAD

**Issue by bitofsky** [pulumi/pulumi#14325]
### What happened?

After upgrading to Pulumi v3.90.0, running pulumi preview or pulumi up results in a panic error. Rolling back to v3.89.0 resolves the issue, suggesting this is an update-related bug.

### Example

```
pulumi preview > out.x
panic: fatal: A failure has occurred: unexpected value type <nil>

goroutine 24 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Failf({0x2adf5d7?, 0xc003225ce0?}, {0xc00253d710?, 0x6?, 0x8?})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/contract/fail.go:32 +0xcb
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.object.toDecryptedPropertyValue({{0x0?, 0x0?}, 0xf0?}, {0x32739a0?, 0xc002284b40?})
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/object.go:551 +0x285
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.object.toDecryptedPropertyValue({{0x26304c0?, 0xc003225ce0?}, 0xc8?}, {0x32739a0, 0xc002284b40})
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/object.go:547 +0x486
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.Map.AsDecryptedPropertyMap(0xc00253db60?, {0x32739a0, 0xc002284b40})
        /home/runner/work/pulumi/pulumi/sdk/go/common/resource/config/map.go:87 +0x173
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*evalSource).Iterate(0xc002325020, {0x32884e0?, 0xc0031e5bc0?}, {{0x7fef9ad46978, 0xc00231f840}, 0x7fffffff, 0x0, 0x0, {{0x487e800, 0x0, ...}, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/source_eval.go:123 +0x2af
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute(0xc008c357b8, {0x32884e0?, 0xc0031e5bc0}, {{0x7fef9ad46978, 0xc00231f840}, 0x7fffffff, 0x0, 0x0, {{0x487e800, 0x0, ...}, ...}, ...}, ...)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment_executor.go:167 +0x2b0
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Deployment).Execute(...)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/deployment.go:578
github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run.func1()
        /home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:314 +0x2b0
created by github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run in goroutine 1
        /home/runner/work/pulumi/pulumi/pkg/engine/deployment.go:299 +0x29b
```

### Output of `pulumi about`

CLI          
Version      3.90.0
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/username/.nvm/versions/node/v18.12.0/bin/node' version='v18.12.0'

Current Stack: stack-name

TYPE
pulumi:pulumi:Stack
pulumi:providers:kubernetes
kubernetes:core/v1:Namespace
kubernetes:helm.sh/v3:Chart
kubernetes:storage.k8s.io/v1:StorageClass
kubernetes:cert-manager.io/v1:ClusterIssuer
kubernetes:core/v1:Secret
kubernetes:networking.k8s.io/v1:Ingress

Found no pending operations associated with stack-name

Backend        
Name           ubuntu22
URL            s3://bucket?awssdk=v2
User           username
Organizations  
Token type     personal

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
Thanks for the report!  This seems to be caused by https://github.com/pulumi/pulumi/pull/14273.  I'll work on a fix.

@puco if this is happening to you in an earlier version, that's a separate problem, as the stack trace points to code that was introduced in 3.90.0.  If you can reproduce the error in the earlier version, it would be great if you could open a separate issue with the stacktrace, so we can look into it.

**Comment by puco** [comment]
@tgummerer I have had indeed a different issue in 3.88.0, that one is not present anymore in 3.88.1 nor 3.89.0. (And there is of course no 3.89.1).

**Comment by tgummerer** [comment]
Ah great, that's probably  https://github.com/pulumi/pulumi/issues/14146, which was a very similar issue that was fixed, and that I then re-introduced in a separate change in a slightly different manner.  Thanks for confirming!

**Comment by bitofsky** [comment]
Thank you for the quick resolution on this issue. I've tested it on my end and can confirm that the panic error no longer occurs after upgrading. Your prompt attention to this matter is much appreciated.
