### ISSUE TITLE
"error: expected property name after '.'" while deploying confluentcloud:index:Connector

### ISSUE THREAD

**Issue by sebastianfeduniak** [pulumi/pulumi#14338]
### What happened?

I use confluentcloud:index:Connector to deploy confluent snowflake connector. It worked good until upgrading pulumi to the latest 3.90.1 version. No issues with 3.86.0 version.

With the latest version I get the following error:

```
Diagnostics:
  confluentcloud:index:Connector (***):
    error: expected property name after '.'
```

Verbose mode and diff doesn't provide more information.

### Example

I just deploy https://www.pulumi.com/registry/packages/confluentcloud/api-docs/connector/

with the following properties:

```
    configNonsensitive: {
      name: `***`,
      'connector.class': 'SnowflakeSink',
      'kafka.auth.mode': 'SERVICE_ACCOUNT',
      'kafka.service.account.id': ***,
      'input.data.format': ***,
      'snowflake.database.name': ***,
      'snowflake.role.name': ***,
      'snowflake.schema.name': ***,
      'snowflake.url.name': ***,
      'snowflake.user.name': ***,
      'snowflake.ingestion.method': ***,
      'tasks.max': `***`,
      topics: ***,
    },
    configSensitive: {
      'snowflake.private.key': ***,
      'snowflake.private.key.passphrase': ***,
    },
```

### Output of `pulumi about`

CLI
Version      3.90.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME            VERSION
aws             5.42.0
awsx            1.0.6
command         0.7.1
confluentcloud  1.26.0
datadog         4.12.0
docker          3.6.1
nodejs          unknown
postgresql      3.6.0
random          4.13.2

Host
OS       darwin
Version  12.7
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
Thanks for the report!  This looks the same as https://github.com/pulumi/pulumi/issues/14335, so I'm gonna go ahead and close this out as a duplicate.

**Comment by sebastianfeduniak** [comment]
@tgummerer from the release notes, it should be fixed in the latest version, but still it doesn't work for me with v3.91.1. I get exactly the same error. Can you please shed some light on it?

**Comment by tgummerer** [comment]
It appears the fix wasn't effective in all cases unfortunately, https://github.com/pulumi/pulumi/issues/14439 is reporting the same.  Note especially @Frassle's comment there (https://github.com/pulumi/pulumi/issues/14439#issuecomment-1784830893).  If you would be able to provide some debug logs that would be very helpful!

**Comment by sebastianfeduniak** [comment]
I am not like putting it here but can send in email. Which one should I use?

**Comment by Frassle** [comment]
You can mail me at fraser@pulumi.com

**Comment by sebastianfeduniak** [comment]
@Frassle I just sent it.

**Comment by sebastianfeduniak** [comment]
I can confirm it works in the latest 3.92 version. Thanks!
