### ISSUE TITLE
Should errors returned from DiffConfig be handled differently

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi#14342]
When a plugin provider returns an error from `DiffConfig`, the engine eats the error and then uses fallback logic. Is this intentional? 

For example, the Kubernetes provider tries to load the old/new kubeconfigs to detect a need for replacement due to a substantive change to the cluster.  If the load fails, it returns an error that is silently discarded.

For reference, see the original PR: https://github.com/pulumi/pulumi/pull/2766

`DiffConfig`:
https://github.com/pulumi/pulumi/blob/2b80b07f3e5db09fe615de2cea001848f15b186f/sdk/go/common/resource/plugin/provider_plugin.go#L504-L506

https://github.com/pulumi/pulumi/blob/2b80b07f3e5db09fe615de2cea001848f15b186f/pkg/resource/deploy/step_generator.go#L1617-L1630

Contrast with `Diff`:
https://github.com/pulumi/pulumi/blob/2b80b07f3e5db09fe615de2cea001848f15b186f/sdk/go/common/resource/plugin/provider_plugin.go#L923-L924

**Comment by Frassle** [comment]
Not sure why this is swallowing all errors. This looks like it might just be a typo that didn't get picked up on before.
