### ISSUE TITLE
Create issue templates in preparation for community

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#1438]
When you open things up, there will be hopefully many people filing issues and giving feedback. When they do, it is very helpful (both to them and to the Pulumi staff) to use a GitHub issue template to help people provide relevant information (build, version, steps to reproduce, etc.) A good example of this is the Kubernetes issue templates -- to see it in action, click "new issue" in kubernetes/kubernetes and observe that they have you basically fill out a form.

cc @joeduffy @lukehoban

**Comment by ellismg** [comment]
We discussed doing this internally, but the general feeling was that we don't want to force a bunch of process on folks reporting issues or opening PRs at this time.  When we start to common things we'd like to see in bug reports or PRs, we'll reconsider.
