### ISSUE TITLE
Pulumi down dropping resources from the state on timeout (possibly related to --exclude-protected)

### ISSUE THREAD

**Issue by dieter-aerit** [pulumi/pulumi#14416]
### What happened?

The scenario:
1. I create a stack with quite a few resources. The creation is succesful.
2. I execute a pulumi down command to destroy the stack (excluding some protected resources) .The down operation fails due to a timeout.
3. I do pulumi refresh and it tells me there are only a few resources left in the stack
4. Another pulumi down operation tells me there are only protected resources left

However on inspection of my AWS account, there is a whole bunch of resources left over (not protected ones).
I now have to check all my resources manually and clean them up, which is a major PITA, not to mention a financial liability.
It seems that an error during the pulumi down operation just causes pulumi to assume everything is probably gone and remove it from the state?

I went through my account and found almost half of the resources still there:
* client vpn endpoint
* nat gateway
* vpc
* hosted zone
* records in an existing hosted zone
* log groups
* IPAM pool and related

### Example

![image](https://github.com/pulumi/pulumi/assets/127097460/50b66177-1dbd-429f-aaf6-097f69ef1824)

![image](https://github.com/pulumi/pulumi/assets/127097460/b86f559a-92fd-4c24-8f59-134c70cb0c45)

### Output of `pulumi about`

CLI
Version      3.91.0
Go Version   go1.21.3
Go Compiler  gc

Host
OS       darwin
Version  14.0
Arch     arm64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/dieter-aerit
User           dieter-aerit
Organizations  dieter-aerit
Token type     personal

### Additional context

Note that I was running Pulumi 3.89 when this happened

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
It looks like this may be the same issue tracked in https://github.com/pulumi/pulumi/issues/8164. A comment there notes the same thing happening with —exclude-protected which sounds like the case here.

**Comment by dieter-aerit** [comment]
`bgelens opened this issue on Oct 7, **2021**`

Hmm...

**Comment by rohantandon** [comment]
Linking a comment from #8164 which I think may also be related or at least a consequence of this:

https://github.com/pulumi/pulumi/issues/8164#issuecomment-1786147585

**Comment by t0yv0** [comment]
Subscribing for updates here. @justinvp please let me know if we think AWS provider needs to be fixed here as opposed to the engine or SDKs.
