### ISSUE TITLE
expected property name after '.' after upgrading to pulumi@3.90.0

### ISSUE THREAD

**Issue by dennispan** [pulumi/pulumi#14439]
### What happened?

After upgrading `pulumi` to `3.90.0` and above, we start to see this error:

```
Diagnostics:
  aws:eks:Cluster (service-cluster):
    error: expected property name after '.'
```

We can see this is related with this change: https://github.com/pulumi/pulumi/pull/14257

It could be something to fix on our side with a more restrictive path validation. However, the challenging part is I cannot find an effective way to find where the violation is.

Similar issue was reported in https://github.com/pulumi/pulumi/issues/14335

### Example

```
eks.Cluster(
    name=self._inputs["name"],
    resource_name=self._inputs["name"],
    role_arn=self._iam_role.arn,
    vpc_config=self._vpc_config,
    version=K8sVersion.V1_28,
    opts=ResourceOptions(provider=self._provider),
)
```

With `pulumi@3.89.0`, it works. But with `pulumi@3.90.0` or above, it throws the error. 

However, in the same pulumi project, it only reproduces in `prod` stack, not `dev` stack. Unfortunately we have hundreds of resources in each stack, which makes it hard to locate the error without more information

### Output of `pulumi about`

```
CLI          
Version      3.91.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.6.1
python  unknown

Host     
OS       darwin
Version  14.0
Arch     arm64

This project is written in python: executable='/Library/Frameworks/Python.framework/Versions/3.11/bin/python3' version='3.11.4'

......


Dependencies:
NAME        VERSION
pip         23.3.1
pre-commit  3.5.0
pulumi-aws  6.6.1
ruff        0.1.3
wheel       0.41.2
yamllint    1.32.0

Pulumi locates its logs in /var/folders/d8/t7tynv650qjbvwvgzdf9k_vm0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Is there any chance you could run with debug logs (`-v10 --logtostderr`) and share that with us? Feel free to send us an email with it if you don't want to attach it here.
