### ISSUE TITLE
After 3.90.0 diagnostic for pulumi/dynamic CheckConfig/DiffConfig starts being printed

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#14442]
### What happened?

An existing pulumi app using pulumi/dynamic is updated to pulumi 3.90.0 and it starts printing the following diagnostic:
```
Diagnostics:
  pulumi:pulumi:Stack (standard-cluster-standard-cluster-integration-testing-baseline-ephemeral):
    Traceback (most recent call last):
      File "venv-Linux/lib/python3.8/site-packages/grpc/_server.py", line 552, in _call_behavior
        response_or_iterator = behavior(argument, context)
      File "venv-Linux/lib/python3.8/site-packages/pulumi/dynamic/__main__.py", line 46, in CheckConfig
        raise NotImplementedError(
    NotImplementedError: CheckConfig is not implemented by the dynamic provider
    Traceback (most recent call last):
      File "venv-Linux/lib/python3.8/site-packages/grpc/_server.py", line 552, in _call_behavior
        response_or_iterator = behavior(argument, context)
      File "venv-Linux/lib/python3.8/site-packages/pulumi/dynamic/__main__.py", line 53, in DiffConfig
        raise NotImplementedError(
    NotImplementedError: DiffConfig is not implemented by the dynamic provider
   ```
   It looks to persist to 3.91.1. I will be providing a small repro. 

### Example

```python
"""A Python Pulumi program"""

from pulumi import ResourceOptions
from pulumi.dynamic import (
    Resource,
    ResourceProvider,
    CreateResult,
    DiffResult,
    CheckResult,
    CheckFailure,
)


class EchoOnCreate(Resource):
    class __EchoOnCreateProvider(ResourceProvider):
        def __init__(self) -> None:
            super().__init__()

        def diff(self, _id: str, old, new) -> DiffResult:
            return DiffResult(
                changes=True, replaces=[], stables=[], delete_before_replace=True
            )

        def check(self, old, new):
            return CheckResult(inputs=new, failures=[])

        def create(self, props):
            return CreateResult("1", {**props})

    def __init__(self, name: str, opts: ResourceOptions) -> None:
        super().__init__(EchoOnCreate.__EchoOnCreateProvider(), name, {}, opts=opts)


res = EchoOnCreate("res", opts=ResourceOptions())
```

### Output of `pulumi about`

CLI          
Version      3.86.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.6.0
cloudinit   1.3.0
command     0.8.2
datadog     4.17.1
kubernetes  3.30.2
python      unknown
random      4.13.0
tls         4.10.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
I can reproduce this in a one-off local project. Even a simpler program repos:

```python
from pulumi import ResourceOptions
from pulumi.dynamic import (
    Resource,
    ResourceProvider,
    CreateResult,
)


class EchoOnCreate(Resource):
    class __EchoOnCreateProvider(ResourceProvider):
        def create(self, props):
            return CreateResult("1", {**props})

    def __init__(self, name: str, opts: ResourceOptions):
        super().__init__(EchoOnCreate.__EchoOnCreateProvider(), name, {}, opts=opts)


res = EchoOnCreate("res", opts=ResourceOptions())
```

- repos with `pip install pulumi==3.90.0`
- does not repo with `pip install pulumi==3.89.0`

The odd thing is that https://github.com/pulumi/pulumi/blob/59d2df953ea46f65f95e4cae47fc644e2ff82d22/tests/integration/integration_python_acceptance_test.go#L73 runs successfully for me locally. Both with the existing test, as well as when replacing it with the repro from this issue.

**Comment by justinvp** [comment]
v3.90.0 required grpcio 1.59.2, a recent change to enable support on Python 3.12 (https://github.com/pulumi/pulumi/pull/14259)

If I force my venv back to having grpcio 1.56.2, with pulumi 3.90.0, it works without erroring.

So looks like this is likely related to the grpcio version bump.

**Comment by justinvp** [comment]
Forcing grpcio 1.57.0, it works. Forcing grpcio 1.58.0, I get the error.

**Comment by justinvp** [comment]
It looks like https://github.com/grpc/grpc/pull/33442 is the root cause, in particular the `traceback.print_exc()` call.

**Comment by Frassle** [comment]
It doesn't look like there's anyway to avoid that traceback call? I'd have thought if we at least threw a Grpc specific exception for Status it would just return that without logging, but I can't see a code path for that?

**Comment by justinvp** [comment]
> It doesn't look like there's anyway to avoid that traceback call? I'd have thought if we at least threw a Grpc specific exception for Status it would just return that without logging, but I can't see a code path for that?

Yeah, I was wondering about that, but I also can't see a code path for it.

I'm going to open an upstream issue in https://github.com/grpc/grpc, revert #14259 & extend the dynamic provider test to ensure there are no unexpected diagnostics.

We'll have to wait on the upstream fix to enable Python 3.12 support. Or workaround the upstream bug by swallowing the traceback output to stderr (which I'd prefer not to do).

**Comment by Frassle** [comment]
> revert https://github.com/pulumi/pulumi/pull/14259

From 14259:
> We have historically seen a lot of issues with grpcio releasing bad versions that don't work with Pulumi, which then trigger a cascade of user issues to us when pip starts pulling it in.

That didn't last long to be proven right again.

**Comment by justinvp** [comment]
Upstream issue: https://github.com/grpc/grpc/issues/34853
