### ISSUE TITLE
Windows MSI installers are published unsigned, without a publisher

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#14450]
Users on Windows may see a "Windows protected your PC" message when downloading and running the MSI for Pulumi IaC.

> Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.
> App: pulumi-3.91.1-windows-x64.msi
> Publisher: Unknown publisher

Screenshot which has the above text:
![image](https://github.com/pulumi/pulumi/assets/788800/123d11ba-51e6-45f7-94c8-30982318c364)

**Comment by justinvp** [comment]
This was fixed back in April 2024. The .msi installer is now signed starting with v3.113.2.
