### ISSUE TITLE
Remove misleading updateInProgress output for file backend

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#14457]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Filestate backends currently don't support checking whether there is an update in progress or not. It would be useful for some users to have this support implemented.

For further background see also https://github.com/pulumi/pulumi/issues/10677.

**Comment by Frassle** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/14309
