### ISSUE TITLE
"No change" but with changes(?)

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1447]
Changing the `publiclyAccessible` property of an `aws.rds.ClusterInstance` object didn't produce any change to the Pulumi program. I would have expected it to produce an update of some kind, but this odd behavior is reflected in the output of the CLI, too:

We print "no change" followed by "changes"?!?

```
 *  aws:rds:ClusterInstance databaseInstance no change changes: ~ publiclyAccessible
```

**Comment by CyrusNajmabadi** [comment]
Hrmm.  I don't repro this:

![image](https://user-images.githubusercontent.com/4564579/47744733-4b596400-dc3f-11e8-881a-20917c08d23f.png)

![image](https://user-images.githubusercontent.com/4564579/47744749-58765300-dc3f-11e8-8488-a4d2d4e77b6c.png)

![image](https://user-images.githubusercontent.com/4564579/47744877-9d9a8500-dc3f-11e8-9540-2c2bd81f4e6f.png)

![image](https://user-images.githubusercontent.com/4564579/47744896-a2f7cf80-dc3f-11e8-9755-333d0be0a550.png)

if you repro this again, let me know.  That said, the display shows what the engine gives us.  So if hte engine gives us 'op_same' we should it that way :)
