### ISSUE TITLE
Explicitly passing `--skip-preview` to update still leads to the CLI prompting.

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1448]
If you pass `--skip-preview` to `pulumi update`, it prompts you if you are sure you want to continue without doing a preview.  You can pass `--yes` to the CLI to prevent this prompt from happening, but I think if you explicitly pass `--skip-preview`, we shouldn't immediately ask you if you really want to skip doing a preview.

**Comment by lukehoban** [comment]
Just hit this - quite surprising.

```
$ pulumi update --skip-preview
Do you want to perform this update without a preview?
  yes
> no
```
