### ISSUE TITLE
Error "CloudFront ETag Out Of Sync" when externally modifying CloudFront resource

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#1449]
## Issue

When using AWS CloudFront resources with Pulumi, you can run into errors if you update the CloudFront resource directly through AWS, such as the AWS CLI or console. This is tracked here: [Perform a `Refresh` operation before each `Apply` #57](https://github.com/pulumi/pulumi-terraform/issues/57).

The CLI will show an error such as the following:

```
rpc error: code
  = Unknown desc = deleting urn:pulumi:stack::project::aws:cloudfront/distribution:Distribution::cdn-name:
  PreconditionFailed: The request failed because it didn't meet the preconditions
  in one or more request-header fields.
```

This is because any CloudFront update operation (such as registering a new domain via Route53) rolls forward the [ETag](https://en.wikipedia.org/wiki/HTTP_ETag). Any future management operations must supply the latest ETag, or they will fail. Because Pulumi stores the last ETag in your stack checkpoint file, you must manually update the ETag value if you have managed CloudFront resources outside of Pulumi.

## Workaround

You can update the ETag using `pulumi refresh` operation:

```bash
pulumi refresh
```

This will fetch the current state of your stack's resources from the appropriate cloud providers. In the case of a CloudFront distribution, this will fetch the current ETag from AWS (along with any other properties that may have changed).

**Comment by Jtango18** [comment]
I've automated this as part of my CI/CD process. Hope someone else finds this useful until the underlying issue is resolved.

```bash
# Workaround for Pulumi Issue with modifications to Cloudfront - see: https://github.com/pulumi/pulumi/issues/1449
pulumi stack export > before.json 
qualifiedString=$(cat before.json | jq '.deployment.resources[] | select(.type | contains("aws:cloudfront/distribution:Distribution")) | "URN: \( .urn ) ID: \( .id )"')
distId=$(echo $qualifiedString| cut -d ' ' -f 4 | tr -d \")
echo "Looking up tag for " $distId
etagValue=`perl -nle 'print $& if m{ETag": "\K([A-Z0-9]+)}' <<< $(aws cloudfront get-distribution --id $distId | grep -i etag)`
echo "Found tag: " $etagValue
(cat before.json | jq --arg DISTID "$distId" --arg ETAG "$etagValue" '.deployment.resources = (.deployment.resources | (.[] | select(.id == $DISTID) | .outputs.etag) |= $ETAG)') > updated.json
pulumi stack import < updated.json
rm updated.json
rm before.json
```

**Comment by pgavlin** [comment]
As of 73f4f2c, you can update the ETag using `pulumi refresh` instead of the import/export sequence listed above.

**Comment by lukehoban** [comment]
@pgavlin is there any more work to be done here?  If not, can we close and update the description with current guidance?

**Comment by pgavlin** [comment]
There is not, no. I've updated the description to recommend `pulumi refresh`.

**Comment by ramarao-boddapati-hcl** [comment]
thanks you guys. the pulumi refresh command saved a lot of debugging time. thanks a lot
