### ISSUE TITLE
Encourage us of `TypedDict` + `Unpack` for python kwarg type declarations (PEP 692)

### ISSUE THREAD

**Issue by zschumacher** [pulumi/pulumi#14507]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
It would be amazing if pulumi and its providers would start using/encouraging use of [pep 692](https://peps.python.org/pep-0692/) for typing kwargs.  This gives great editor support and also lets static type checkers ensure you are creating objects correctly.

Example:
```python
from typing import TypedDict, Unpack

class Movie(TypedDict):
    name: str
    year: int

def foo(**kwargs: Unpack[Movie]) -> None:
    assert_type(kwargs, Movie)  # OK!
```

**Comment by zschumacher** [comment]
related to https://github.com/pulumi/pulumi/issues/11732 and https://github.com/pulumi/pulumi/discussions/11500

**Comment by julienp** [comment]
We've shipped TypedDict based input types for AWS and Kubernetes SDKs, with other SDKs following in the coming days and weeks. See also https://github.com/pulumi/pulumi/issues/12689

Read the blog about the changes https://www.pulumi.com/blog/pulumi-loves-python/

**Comment by zschumacher** [comment]
Great stuff!
