### ISSUE TITLE
Add a "continue on error" flag

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#14515]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

At the moment if a resource fails to be deployed we cancel the whole update. While this it's appropriate to fail any dependencies of the failed resource, any other resources could continue to be created/updated and succeed.

I propose either a new argument (`--continue-on-error`) and/or environment variable (`PULUMI_CONTINUE_ON_ERROR`) that will allow this.

I know we have the `--target` argument, but that would mean running multiple updates.

**Comment by Phil1972** [comment]
That would also allow to potentially unblock many issues reported in this issue: https://github.com/pulumi/pulumi/issues/2877
