### ISSUE TITLE
Pulumi new throwing an error

### ISSUE THREAD

**Issue by Rajath-Raghu** [pulumi/pulumi#14551]
### What happened?

Was following the steps mentioned here: https://www.pulumi.com/docs/clouds/aws/get-started/begin/. When I gave pulumi new command and selected "aws-python" program, I got the following error: prepare console: set console mode: the parameter is incorrect.

### Example

![error](https://github.com/pulumi/pulumi/assets/85983817/2bc53fc6-9720-4559-8ca8-2941c351ac6d)

### Output of `pulumi about`

CLI
Version      3.93.0
Go Version   go1.21.3
Go Compiler  gc
Host
OS       Microsoft Windows 8.1 Single Language
Version  6.3.9600 Build 9600
Arch     x86_64
Backend
Name           pulumi.com
URL            https://app.pulumi.com/Dreues
User           Dreues
Organizations  Dreues
Token type     personal
Pulumi locates its logs in C:\Users\RR4C19~1\AppData\Local\Temp by default
warning: Failed to read project: no Pulumi.yaml project file found (searching up
wards from F:\Projects\quickstart). If you have not created a project yet, use `
pulumi new` to do so: no project file found
warning: Failed to get information about the current stack: no Pulumi.yaml proje
ct file found (searching upwards from F:\Projects\quickstart). If you have not c
reated a project yet, use `pulumi new` to do so: no project file found

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
This error message is coming from our upstream dependency, I can see a number of similar error messages on a few CLI tools. They all seem to be related to Windows 8.

Given Microsoft's support for Windows 8.1 has ended on January 10, 2023, I'll close this issue as won't do.
