### ISSUE TITLE
Parse config paths strictly

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi#14573]
We recently changed config paths such that "foo.[0]" was valid, but this ought to be "foo[0]". We should make this strict before users start depending on the buggy behavior.

**Comment by emilhotkowski** [comment]
I'd be glad to help if this is reasonable sized or the scope is clear @Frassle

**Comment by Frassle** [comment]
It's clear what's intended here, pretty much just re-introduce the same fix that https://github.com/pulumi/pulumi/pull/14257 attempted. 

I'm not sure how much the scope on that will actually be, not huge but there are some complexities in that config keys should be strict but property paths everywhere else in the system need to tolerate keys like "foo.[1]" otherwise we'd regress behaviour like we saw with https://github.com/pulumi/pulumi/issues/14439 again.
