### ISSUE TITLE
Support configuring a provider using outputs from other resource creation

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1458]
For example, we may want to provision an AKS/GKE/EKS cluster on Azure/Google/AWS, and then configure `@pulumi/kubernetes` to connect to the cluster using credentials provided as outputs from that resource creation so that kubernetes resources can be created in the cluster.

Today, this does not appear to be possible because the configuration of the Kubernetes provider must be prior to the Pulumi program executing.

I suspect that this would be solved by addressing https://github.com/pulumi/pulumi/issues/1221 using the approach suggested in that issue.

**Comment by pgavlin** [comment]
Fixed with #1695.
