### ISSUE TITLE
Update stack outputs only on successful deployments

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#14621]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

Consider failing a stack reference if the target stack's last update did not successfully complete. 

For example:
- stack a outputs some values
- stack b consumes stack a's outputs
- stack a's last update resulted in a failed run (outputs are now know in an unknown state)
- stack b uses `getOutput` instead of `requireOutput` thus any subsequent update could result in unknown or unintended behavior.

### Affected area/feature

To alleviate against this possibility, allow an opt-in flag to specify that regardless of what stack reference method I use, I am requiring the upstream stack's last update to be successful.

for example
```
const sr = new pulumi.StackReference(
        `${pulumi.getOrganization()}/producer/${pulumi.getStack()}`,
        {
           // better naming, but allows me to fail my program if the upstream (target) stack also failed
            requireUpstreamSuccess: true
        }
    );
```

**Comment by lukehoban** [comment]
I suspect we likely want to address this problem differently. I think if an update fails we should not overwrite its outputs at all. Stack references should behave consistently for all stacks (pulling latest update stack outputs), but updates should be responsible for never corrupting their outputs.

**Comment by Frassle** [comment]
> I think if an update fails we should not overwrite its outputs at all.

Even if we did that it's still pretty risky for downstream stacks. Imagine reading an endpoint address from stack outputs, but the last update replaced the endpoint with a new one and then failed so the stack outputs don't have the new address.

**Comment by phillipedwards** [comment]
While not ideal from a downstream stack's POV, a non-overwritten value at least is not going to cause as update or unintended behavior.

**Comment by AaronFriel** [comment]
> I suspect we likely want to address this problem differently. I think if an update fails we should not overwrite its outputs at all. Stack references should behave consistently for all stacks (pulling latest update stack outputs), but updates should be responsible for never corrupting their outputs.

Echoing this but with an alternative argument: preserving the previous stack outputs on a failed update is consistent with how resource updates apply, and would be consistent with the multi-stack approaches we've delivered (micro-stacks) and experimented with internally.

We encountered the issue of an invalid value (undefined, IIRC) affecting Pulumi AI here:

https://github.com/pulumi/docs/blob/master/infrastructure/index.ts#L54-L55

I propose we retitle this issue to:

"Update stack outputs only on successful deployments"

A flag to opt in to the previous behavior might be useful, e.g., for debugging or advanced scenarios where timeliness and failure of an upstream stack is meaningful.

**Comment by joeduffy** [comment]
I do agree with @Frassle's concern:

> Imagine reading an endpoint address from stack outputs, but the last update replaced the endpoint with a new one and then failed so the stack outputs don't have the new address.

Is it not an option to only replace outputs that have new, fully computed outputs, but to otherwise leave others untouched? If the stack update didn't run to completion, the absence of a new output can't safely be assumed to mean it was deleted.

**Comment by AaronFriel** [comment]
Hm, @joeduffy would you not find it surprising if a downstream service updated to use an upstream service's incomplete - potentially invalid - endpoint?

It depends though, unfortunately, on whether the value that's being provided is from a resource that was replaced (the previous value is valid and points to an existing resource) or updated (the previous value is likely invalid). In either case though, depending on mutable values between stacks seems pretty brittle. 

If an ALB is replaced, for example, I don't know how you don't cause downtime with a downstream service?

**Comment by benesch** [comment]
> I suspect we likely want to address this problem differently. I think if an update fails we should not overwrite its outputs at all. Stack references should behave consistently for all stacks (pulling latest update stack outputs), but updates should be responsible for never corrupting their outputs.

We'd definitely prefer this behavior at @MaterializeInc! @joeduffy's idea...

> Is it not an option to only replace outputs that have new, fully computed outputs, but to otherwise leave others untouched? If the stack update didn't run to completion, the absence of a new output can't safely be assumed to mean it was deleted.

...would also be workable, though it seems somewhat hard to reason about stack outputs where half the values are from the last successful run and half the values are from a run that failed partway through. The rule of "stack outputs are determined entirely by the last successful run" seems easier to reason about.

**Comment by justinvp** [comment]
> The rule of "stack outputs are determined entirely by the last successful run" seems easier to reason about.

After reading all the comments, I think this is my preference.

**Comment by joeduffy** [comment]
I definitely agree this is easier to reason about; it's essentially "transactional".

My only concern is that if resource changes actually happened prior to the failure, the old outputs may in fact be wrong in that they refer to dangling resources.

As a made-up example, say our stack just manages two entirely independent S3 buckets, A and B, and exports their IDs. If we make an update that has to replace both, and A's replacement succeeds (and deletes the old one), but the program fails before B's replacement even begins, then exporting the old IDs will lead to _guaranteed_ incorrect behavior for downstream consumers: A's old ID now points to a resource that no longer exists. Now, it's true that it _may_ still lead to incorrect behavior to use A's new ID in combination with B's old ID, but there are certainly cases where that's the right thing to do.

It would be much nicer if the world was transactional, but it isn't always, and I worry trying to give the appearance that it is here could end up biting us in subtle ways.

No matter what, though, any of these answers seem infinitely better than the current behavior 😄

**Comment by AaronFriel** [comment]
> As a made-up example, say our stack just manages two entirely independent S3 buckets, A and B, and exports their IDs. If we make an update that has to replace both, and A's replacement succeeds (and deletes the old one), but the program fails before B's replacement even begins

My understanding of the engine might be off. Isn't it the case that if A has `deleteBeforeReplace`, the deletion is delayed until the stack succeeds in its entirety? If the program fails then the state file will contain both A<sub>new</sub> and A<sub>old</sub>.

**Comment by joeduffy** [comment]
I don't believe that is true (and certainly it doesn't _need_ to be). Order of operations is determined by dependencies.

**Comment by justinvp** [comment]
The fix for this has merged and will be part of the next CLI release this week. The fix implements the following behavior as noted [here](https://github.com/pulumi/pulumi/issues/14621#issuecomment-1828791907): If the stack did not run successfully to completion, only update stack outputs that were updated and leave any existing stack outputs as-is (i.e. don't delete any outputs).
