### ISSUE TITLE
Support passing an optional project name to `pulumi convert`

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi#14645]
When converting a YAML program to another language, the project name gets reused. It makes sense that this is the default behavior, since if you're converting, you're probably doing so with the intent of continuing to use the program you've converted. But in other cases, for example when converting a program into multiple languages for purposes of testing, it'd be helpful to be able to pass an optional project name to the convert command so the generated program can be executed immediately (and without conflicting with the project/stack that were used to generate it).

**Comment by FonsecaGoncalo** [comment]
Hi @cnunciato 
Can I work on this issue?
