### ISSUE TITLE
Convert from Terraform OCI to Pulumi OCI

### ISSUE THREAD

**Issue by pguerin3** [pulumi/pulumi#14653]
### What happened?

Just doing a conversion of a Terraform file to a Pulumi file (Python)
Using the Oracle cloud.

### Example

1) installedl Terraform in Fedora 38:
sudo dnf install -y dnf-plugins-core
sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
sudo dnf -y install terraform

2) download the Terraform files for the Oracle cloud
cd ~/diagrams
git clone https://github.com/oracle/terraform-provider-oci.git

3) go to a particular project
cd terraform-provider-oci/examples/always_free

4) Init the project
terraform init

5) install Pulumi (Linux)
curl -fsSL https://get.pulumi.com | sh

6) add Pulumi to your PATH
PATH=$PATH:~/.pulumi/bin

7) test
pulumi version

8) do the conversion
pulumi convert --from terraform --language python --out pulumi

### Output of `pulumi about`
```
(diagrams) me@fedora ~/diagrams/terraform-provider-oci/examples/always_free % pulumi convert --from terraform --language python --out pulumi
Converting from terraform...
Downloading provider: terraform
Downloading provider: oci
Downloading provider: tls
warning: /home/me/diagrams/terraform-provider-oci/examples/always_free/main.tf:28,1-15: Failed to evaluate provider config; Could not evaluate expression for oci:region
warning: /home/me/diagrams/terraform-provider-oci/examples/always_free/main.tf:28,1-15: Failed to evaluate provider config; Could not evaluate expression for oci:tenancy_ocid
warning: /home/me/diagrams/terraform-provider-oci/examples/always_free/main.tf:28,1-15: Failed to evaluate provider config; Could not evaluate expression for oci:user_ocid
warning: /home/me/diagrams/terraform-provider-oci/examples/always_free/main.tf:28,1-15: Failed to evaluate provider config; Could not evaluate expression for oci:fingerprint
warning: /home/me/diagrams/terraform-provider-oci/examples/always_free/main.tf:28,1-15: Failed to evaluate provider config; Could not evaluate expression for oci:private_key_path
warning: /home/me/diagrams/terraform-provider-oci/examples/always_free/main.tf:160,19-75: Function not yet implemented; Function lookup not yet implemented
warning: /home/me/diagrams/terraform-provider-oci/examples/always_free/main.tf:188,19-75: Function not yet implemented; Function lookup not yet implemented
Converting to python...
================================================================================
The Pulumi CLI encountered a code generation error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.94.2
error: main.pp:323,39-50: unknown property 'vnic_id' among [displayName id subnetId vlanTag availabilityDomain timeCreated vnicId compartmentId instanceId nicIndex state vlanId createVnicDetails]; 
error: main.pp:323,39-50: cannot traverse value of type union(none, object({availabilityDomain = union(none, string), compartmentId = union(none, string), createVnicDetails = union(list(object({assignIpv6ip = union(bool, none), assignPrivateDnsRecord = union(bool, none), assignPublicIp = union(none, string), definedTags = union(map(dynamic), none), displayName = union(none, string), freeformTags = union(map(dynamic), none), hostnameLabel = union(none, string), ipv6addressIpv6subnetCidrPairDetails = union(list(object({ipv6Address = union(none, string), ipv6SubnetCidr = union(none, string)}, annotated(0xc00138e640))), none), nsgIds = union(list(string), none), privateIp = union(none, string), skipSourceDestCheck = union(bool, none), subnetId = union(none, string), vlanId = union(none, string)}, annotated(0xc00138e440))), none), displayName = union(none, string), id = union(none, string), instanceId = union(none, string), nicIndex = union(int, none), state = union(none, string), subnetId = union(none, string), timeCreated = union(none, string), vlanId = union(none, string), vlanTag = union(int, none), vnicId = union(none, string)}, annotated(0xc00138e380))); 
error: could not generate output program
```
### Additional context

I'm using Fedora 38 and the ZSH shell.

Pulumi version = v3.94.2

Note - I'm also using Python 3.12, with a virtual environment.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Sorry for the trouble, @pguerin3, and thanks for opening an issue. We'll take a look.

**Comment by pguerin3** [comment]
I'm also investigating an issue with examples in oracle/terraform-provider-oci.
So the root cause may not be with Pulumi.....

**Comment by pguerin3** [comment]
Also note that Oracle have a new location for their Terraform provider.
So I added the following to the Terraform configuration to the Always_Free directory.

terraform {
    required_providers {
        oci = {
            source  = "oracle/oci"
            version = ">= 4.0.0"
        }
    }
}

After running the conversion again, I get the same error as before.
Hope this information is useful.

**Comment by pguerin3** [comment]
Got it to work.
The issue was my python virtual environment was not setup correctly.

**Comment by cvasani** [comment]
What the fix you did ? Any word on it ? I am also getting same error.
