### ISSUE TITLE
Go SDK won't build with GOPROXY=direct

### ISSUE THREAD

**Issue by invernizzie** [pulumi/pulumi#14666]
### What happened?

The go SDK uses [sourcegraph/appdash](https://github.com/pulumi/pulumi/blob/5e5357d2595b316758e6dbfddf979b4f1fc075ac/sdk/go.mod#L37), which is an archived project and a `go get` from its direct download link fails with a 404.

The only reason why the SDK builds is that appdash is cached in the [default Go module mirror](https://proxy.golang.org/). The dep should be fixed to fetch from the GitHub repo at https://github.com/sourcegraph/appdash

### Example

GOPROXY=direct go get

### Output of `pulumi about`

This happens since at least v3.51.1

### Additional context

This is related to !10545. Switching to [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-go) would replace an archived dependency with an actively maintained one.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Yup CI picked this up last week. https://github.com/pulumi/pulumi/issues/14646
