### ISSUE TITLE
Add command to generate an import template from a stack

### ISSUE THREAD

**Issue by MMartyn** [pulumi/pulumi#14665]
## Hello!

There currently is the import command that is capable of taking a json file to import (adopt) existing cloud resources into a stack. This is convenient, but building out that json is a manual process. Instead I would like a command to generate a template json file that can be fed into the import command where I would only need to fill in the IDs of the resources I want to import and remove the ones I don't.

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Comment by Frassle** [comment]
Will be fixed by https://github.com/pulumi/pulumi/pull/14548

**Comment by justinvp** [comment]
Closing this as fixed by https://github.com/pulumi/pulumi/pull/14548
