### ISSUE TITLE
Registry Docs Enhancement: Update the "Create Resource" section to generate a complete syntax reference for each language

### ISSUE THREAD

**Issue by toriancrane** [pulumi/pulumi#14675]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Task list

- [x] #15392
- [x] #15393

Request to update the format of the "Create Resource" definition in our registry docs to a more user-friendly, usable format. 

Please take a look at the "Request Syntax" section of the [AWS Boto3 documentation for `create_vpc`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/create_vpc.html) for what I mean by a more user-friendly and "complete" resource definition. The difference is that users can see the exact correct syntax for defining a resource. It is the difference between:

```
tags: Optional[Mapping[str, str]] = None, # from our docs
```

and

```
 # Example from boto3 API docs
 'Tags': [
      {
          'Key': 'string',
          'Value': 'string'
      },
  ]
```

### Affected area/feature

The Pulumi Registry documentation

**Comment by justinvp** [comment]
We should do this for both "constructors" and invokes.

**Comment by justinvp** [comment]
Luke tried this out for YAML: https://github.com/pulumi/pulumi/commit/e1ba64e1b7f3277972f8689f7d02d9e0459c0b66
