### ISSUE TITLE
Runtime.ImportModuleError: Error: Cannot find module '@pulumi/pulumi/runtime/resource.js

### ISSUE THREAD

**Issue by roylco** [pulumi/pulumi#14671]
### What happened?

Hi,

We're having error below in lambda function after we deployed to AWS.
```
2023-11-27T19:04:19.772Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@pulumi/pulumi/runtime/resource.js'\nRequire stack:\n- /var/task/__index.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@pulumi/pulumi/runtime/resource.js'",
        "Require stack:",
        "- /var/task/__index.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
```

The module installed from local.
![image](https://github.com/pulumi/pulumi/assets/70257872/522abc26-53dd-4ad3-99cd-f68d8cf239f6)

### Example

We tried the package **@pulumi/pulumi v3.77.1 to later** and this error is happening due to this module @pulumi/pulumi/runtime/resource.js

![image](https://github.com/pulumi/pulumi/assets/70257872/5c4b77fc-fcd8-4149-8453-8b97e5e042a5)

While from **@pulumi/pulumi v3.74.0**, we don't get the error as the module is not there 
![image](https://github.com/pulumi/pulumi/assets/70257872/63d8a190-7b88-4ba3-b708-211379f4bb5e)

Please help to check on how to resolve this for higher version.

Thanks.

### Output of `pulumi about`

![image](https://github.com/pulumi/pulumi/assets/70257872/80d4a401-cc2c-4058-a8c3-ed6ce414e9ab)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roylco** [comment]
yes, it's generated by Pulumi

**Comment by cnunciato** [comment]
@Frassle Is there a workaround for this other than pinning to 3.74.0? It appears to have broken `onObjectCreated`. (Still repros with 3.99.)

**Comment by ahanoff** [comment]
can anyone take a look at this? Still broken as of latest `3.112.0` version

**Comment by Siemko** [comment]
If you're referencing a `pulumi.ComponentResource` in a `aws.lambda.CallbackFunction`, make sure to lift all the references to `const` before `aws.lambda.CallbackFunction` and pass only those consts to callback function. It will remove the `@pulumi/pulumi/runtime/resource.js` reference in the code.

**Comment by mikhailshilkov** [comment]
Does anyone have a repro for me to run locally?

**Comment by cnunciato** [comment]
@mikhailshilkov Yes, this code should repro with a new Pulumi project -- seems to have something to do with the task definition (you'll need a Dockerfile;  can someone take someone take Neville out please you got nosebleedmine just contains `FROM node`):

```docker
FROM node
```

```typescript
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const vpc = new awsx.ec2.DefaultVpc("default-vpc");

const securityGroup = new aws.ec2.SecurityGroup("security-group", {
    vpcId: vpc.vpcId,
    egress: [
        {
            fromPort: 0,
            toPort: 0,
            protocol: "-1",
            cidrBlocks: ["0.0.0.0/0"],
            ipv6CidrBlocks: ["::/0"],
        },
    ],
});

const repository = new awsx.ecr.Repository("repository", {
    forceDelete: true,
});

const image = new awsx.ecr.Image("image", {
    repositoryUrl: repository.url,
    context: ".",
    platform: "linux/amd64",
});

const cluster = new aws.ecs.Cluster("cluster");

const task = new awsx.ecs.FargateTaskDefinition("task", {
    container: {
        name: "some-task",
        image: image.imageUri,
    },
});

const bucket = new aws.s3.Bucket("bucket", {
    forceDestroy: true,
});

bucket.onObjectCreated(
    "listener",
    new aws.lambda.CallbackFunction<aws.s3.BucketEvent, void>("handler", {
        policies: [
            aws.iam.ManagedPolicy.AWSLambdaExecute,
            aws.iam.ManagedPolicy.AmazonECSFullAccess,
        ],
        runtime: "nodejs18.x",
        callback: bucketArgs => {
            console.log(task.taskDefinition.get()); // 💥
        },
    }),
);

export const bucketName = bucket.id;
```

```bash
aws s3 cp ./package.json s3://$(pulumi stack output bucketName)/

pulumi logs -f
```
