### ISSUE TITLE
--cwd not working

### ISSUE THREAD

**Issue by sukkergris** [pulumi/pulumi#14712]
### What happened?

When not having an organization using --cwd fails.

### Example

[root]:/workspaces/private-job-application-app/IaC/job-application# pulumi up  --stack job-application/dev --cwd /workspaces/private-job-application-app/IaC/job-application
The stack 'job-application/dev' does not exist.

If you would like to create this stack now, please press <ENTER>, otherwise press ^C:  
error: could not create stack: [404] Not Found: Organization 'job-application' not found

### Output of `pulumi about`

[root]:/workspaces/private-job-application-app/IaC/job-application# pulumi up  --stack job-application/dev --cwd /workspaces/private-job-application-app/IaC/job-application
The stack 'job-application/dev' does not exist.

If you would like to create this stack now, please press <ENTER>, otherwise press ^C:  
error: could not create stack: [404] Not Found: Organization 'job-application' not found

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Assuming "job-application" is your project name this is expected, with or without "--cwd" the stack names are either "org/stack" or "org/project/stack".

**Comment by sukkergris** [comment]
In other words - you need an organization in order to use this feature

**Comment by Frassle** [comment]
If using filestate it's always "organization", if using Pulumi cloud its your Pulumi username.

**Comment by sukkergris** [comment]
Great! Thank you 😊👌
