### ISSUE TITLE
Show a progress bar for deployment

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#1471]
Idea 1: show a percentage of resources that have already been created

Idea 2: Look at past deployment data to make guesses about how long it takes to create resources of each type.

Example of a progress bar in Up. Up is OSS and authored in Go: https://github.com/apex/up/blob/master/internal/util/util.go#L78

![image](https://user-images.githubusercontent.com/4260261/41072219-5ce4b8c4-69b1-11e8-9a5f-64703d5166b1.png)

**Comment by lukehoban** [comment]
This hasn't come up again in last ~1.5 years, and we're reasonably happy with overall update progress display at this point.  We may consider something like this in the future - but can close this issue out for now.
