### ISSUE TITLE
Pulumi config cannot retrieve array objects

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1473]
The Toml spec says it supports array types. (https://github.com/toml-lang/toml#user-content-array) However, if `Pulumi.yaml` contains an array `pulumi` fails to parse it.

It might be reasonable to require that `Pulumi.yaml` and its corresponding config values are { string, number, boolean }. However, supporting a richer set of primitives would certainly be useful. e.g. a complex configuration object, or more practically an array of domain aliases.

```
config:
  aws:region: us-west-2
  proj:domainAliases: [ "foo" ]
```

```
error: could not unmarshal map: yaml: unmarshal errors:
  line 6: cannot unmarshal !!seq into string
```

**Comment by AndresPineros** [comment]
Hello, I'm just learning Pulumi and I'd like to understand the purpose of removing the Pulumi.yaml variables.

As I understand, a stack is associated with an environment. But not all Pulumi Components should asociated directly with an environment. If My Pulumi component was "Application X deployment" it would make sense to force a stack, because applications are deployed on a per-environment basis. But generic components like "EC2 Cluster" shouldn't have to be mapped to an environment, it is just a piece of reusable logic that other components can use.

Am I missing something maybe? Is there a standard to use a "default" stack for these stackless Components?

**Comment by lukehoban** [comment]
Components are instantiated within a given stack, and are parameterized via passing arguments to the component class constructor in whatever form the component would like to receive them. 

Pulumi config is a concept that is only associated with a stack, and is the external configuration for that stack. The stack can decide if/how to pass any stack level configuration into components it instantiates.

**Comment by ipeacocks** [comment]
So it there any way to put not only string in `Pulumi.<stack>.yaml`. 
```
config:
  aws:region: us-east-1
  pulumi-infra:private_subnet_cidrs: ["172.255.100.0", "172.255.101.0", "172.255.102.0"]
  pulumi-infra:public_subnet_cidrs: ["172.255.110.0", "172.255.111.0", "172.255.112.0"]
  pulumi-infra:vpc_cidr: "172.255.0.0/16"
```
But for `__main__.py` list/array `["172.255.100.0", "172.255.101.0", "172.255.102.0"]` is still string.  How to deal with it?

**Comment by leezen** [comment]
@ipeacocks Please take a look at https://www.pulumi.com/docs/intro/concepts/config/#structured-configuration. The YAML itself must specify an array (as in the `nums` example)

**Comment by ipeacocks** [comment]
@leezen I am trying next structure:

```
config:
  aws:region: us-east-1
  pulumi-infra:zones_amount: 3
  pulumi-infra:private_subnet_cidrs:
    - 172.255.100.0/24
    - 172.255.101.0/24
    - 172.255.102.0/24
```
But for `__main__.py` it's still `string`:
```
Diagnostics:
  pulumi:pulumi:Stack (pulumi-infra-dev):
    ["172.255.100.0/24","172.255.101.0/24","172.255.102.0/24"]
    <class 'str'>

```

**Comment by leezen** [comment]
Are you using `config.require_object("private_subnet_cidrs")`? https://www.pulumi.com/docs/reference/pkg/python/pulumi/#pulumi.Config.require_object -- this should return back an object and not a `str`

**Comment by ipeacocks** [comment]
Thanks @leezen. Now it's working!
Previously I've used just `config.require("private_subnet_cidrs")` and it produces only `str`.
