### ISSUE TITLE
Add `CustomResource#getInputs`

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#1474]
I propose to add the method `CustomResource#getInputs`, which would return (what I will liberally refer to as) "inputs" passed to the constructor.

Specifically in the context of Kubernetes: suppose we have `new k8s.apps.v1.Deployment(name, {metadata: {...}, spec: {...}})` which creates an instance of a `CustomResource` that represents a Kubernetes `Deployment`. In this case, `getInputs` would return the second argument, which is the JSON specification of the `Deployment` object.

**Motivation:** _Not_ including a way for some `CustomResource` to depend on the _inputs_ of another `CustomResource` will probably create prohibitively long `update` times for Kubernetes apps. This is because many Kubernetes API objects are very decoupled, sharing only small things like labels. The most natural way to declare such a dependency in the current way of doing things is to use `Output<T>#apply`, but this creates an explicit dependency. For for example, if you want a `Service` to have the same name as the `Deployment` it is meant to expose, you'd use `apply` to get the `.metadata.name`, but this creates an explicit dependency, and means that the `Service` must roll out after the `Deployment`, which usually should not be a requirement. In cases where lots of things depend on other things, it is possible to end up with a totally artificial dependency graph, which for many applications I suspect will greatly increase the time it takes to update an application.

**Comment by joeduffy** [comment]
@hausdorff Is this still required, given that you've figured out how to serialize inputs in the way you need?

Also /cc @pgavlin @swgillespie
