### ISSUE TITLE
Pulumi CLI command return exit code 2 when update is available

### ISSUE THREAD

**Issue by pawelprazak** [pulumi/pulumi#14751]
### What happened?

After running on dowgraded version:
```
pulumi plugin ls
echo $?
2
```
unexpected exit code 2 and no output

### Example

```
brew remove pulumi
curl -L -O https://raw.githubusercontent.com/Homebrew/homebrew-core/69b97f26bc78cf68eb30eedd0ca874b6e1914b19/Formula/p/pulumi.rb
brew install pulumi.rb
pulumi plugin ls
echo $?
```
should print `2` at the end

### Output of `pulumi about`

```
pulumi about
CLI
Version      3.94.2
Go Version   go1.21.4
Go Compiler  gc

Host
OS       darwin
Version  14.1.2
Arch     arm64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/pprazak
User           pprazak
Organizations  pprazak, besom
Token type     personal
```

### Additional context

I've found two workarounds to get exit code `0`:
- adding `--logtostderr` argument
- setting `export PULUMI_SKIP_UPDATE_CHECK=true`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@pawelprazak, I haven't been able to repro this. If you do run with `--logtostderr`, e.g. `pulumi plugin ls --logtostderr -v=9` are there any errors in the logs?

**Comment by pawelprazak** [comment]
> @pawelprazak, I haven't been able to repro this. If you do run with `--logtostderr`, e.g. `pulumi plugin ls --logtostderr -v=9` are there any errors in the logs?

There is version update warning, no errors.

**Comment by justinvp** [comment]
@pawelprazak, I still can't repro this so I'm going to close this as no repro. However, if you're still hitting it with a more recent version of the CLI, please re-open and we can dig deeper to understand what's happening. Thank you!

**Comment by pawelprazak** [comment]
Understandable, thank you for looking into this :)
