### ISSUE TITLE
pulumi requires login

### ISSUE THREAD

**Issue by tamusjroyce** [pulumi/pulumi#14757]
### What happened?

Tried to use pulumi, and it requires login

However, `pulumi login --local` works. Could this be in the --help?

pulumi --help | grep local
      --tracing file:                Emit tracing to the specified endpoint. Use the file: scheme to write tracing data to a local file

### Example

`pulumi new` ->

Manage your Pulumi stacks by logging in.
Run `pulumi --help` for alternative login options.
Enter your access token from https://app.pulumi.com/account/tokens
    or hit <ENTER> to log in using your browser

### Output of `pulumi about`

CLI
Version      3.95.0
Go Version   go1.21.4
Go Compiler  gc

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19045 Build 19045
Arch     x86_64

Backend
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations
Token type     personal

Pulumi locates its logs in C:\Users\GalyeJ\AppData\Local\Temp by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from C:\Users\GalyeJ\projects\provisioning\my_first_app). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from C:\Users\GalyeJ\projects\provisioning\my_first_app). If you have not created a project yet, use `pulumi new` to do so: no project file found

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
It is in the help for `pulumi login`.
I don't think we want to specifically call it out in the top level help.
But we can fix the error message to say look at `pulumi login --help` for alternative login options.

**Comment by lethargosapatheia** [comment]
@Frassle But you're making users believe that they cannot use pulumi without having an online account, until someone (like I did) stumbles upon this topic and eventually runs 'pulumi login --local'. There should be a way to able to choose to use it locally when you start with `pulumi new`, which is the actual starting command in most tutorials.

**Comment by shellscape** [comment]
Came here by way of google after running into the same thing. Pretty smarmy tactic.

**Comment by bahdcoder** [comment]
And I'm here too, because they forced me to login and then I realized after 20 minutes of research that it's actually possible to use the open source project without logging in to their cloud. hello 🫠 !

**Comment by facundoq** [comment]
Same here. Not cool Pulumi!
