### ISSUE TITLE
Argument type says Sequence but Tuple is not allowed

### ISSUE THREAD

**Issue by ar-qun** [pulumi/pulumi#14758]
### What happened?

Documentation says that required type is `Sequences` but in reality pulumi complains if I provide a tuple.

### Example

I have confirmed that tuple is a Sequence
```
from collections.abc import Sequence
isinstance(tuple(), Sequence)
```
> True

But
```
gcp.compute.Firewall(
    "security-control-egress-allow-approved",
    network=network.name,
    direction="EGRESS",
    destination_ranges=(
        "0.0.0.0/0"
    ),
    allows=(
        gcp.compute.FirewallAllowArgs(
            protocol="tcp",
            ports=(
                "80",
                "443",
            ),
        ),
    ),
    priority=1000,
)
```
Returns:

>     error: gcp:compute/firewall:Firewall resource 'security-control-egress-allow-approved' has a problem: Attribute must be a list. Examine values at 'security-control-egress-allow-approved.destinationRanges'.

### Output of `pulumi about`

Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):  
Enter your passphrase to unlock config/secrets
CLI          
Version      3.94.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME    VERSION
gcp     7.2.1
python  unknown

Host     
OS       ubuntu
Version  23.04
Arch     x86_64

This project is written in python: executable='/home/me/.cache/pypoetry/virtualenvs/[POETRY_ENV_NAME]/bin/python3' version='3.11.4'

Current Stack: organization/Infrastructure/dev

TYPE                                     URN
pulumi:providers:gcp                     urn:pulumi:dev::Infrastructure::pulumi:providers:gcp::default
pulumi:pulumi:Stack                      urn:pulumi:dev::Infrastructure::pulumi:pulumi:Stack::Infrastructure-dev
pulumi:providers:gcp                     urn:pulumi:dev::Infrastructure::pulumi:providers:gcp::default_7_2_1
gcp:compute/network:Network              urn:pulumi:dev::Infrastructure::gcp:compute/network:Network::default
gcp:compute/subnetwork:Subnetwork        urn:pulumi:dev::Infrastructure::gcp:compute/subnetwork:Subnetwork::default
pulumi:providers:gcp                     urn:pulumi:dev::Infrastructure::pulumi:providers:gcp::default_7_0_0

Found no pending operations associated with dev

Backend        
Name           XXXXXX
URL            file://~
User           me
Organizations  
Token type     personal

Dependencies:
NAME                        VERSION
backcall                    0.2.0
black                       23.11.0
flake8                      6.1.0
ipython                     8.18.1
mypy                        1.7.1
pickleshare                 0.7.5
pip                         23.3.1
pre-commit                  3.5.0
pytest                      7.4.3
wheel                       0.41.2

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
The following is not a `tuple`, it's a `str`, and even though `str` is a `Sequence` it's treated as a `str`:

```python
    destination_ranges=(
        "0.0.0.0/0"
    ),
```

For example:

```python
from collections.abc import Sequence
print(isinstance((
    "0.0.0.0/0"
), Sequence)) # True
print(isinstance((
    "0.0.0.0/0"
), str)) # True
print(isinstance((
    "0.0.0.0/0"
), tuple)) # False
```

You can pass it as a `tuple`, but it needs to actually be a tuple. One way to do that is to have a trailing comma, e.g.:

```python
    destination_ranges=(
        "0.0.0.0/0", # <- trailing comma
    ),
```

```python
print(isinstance((
    "0.0.0.0/0",
), tuple)) # True
```
