### ISSUE TITLE
Golang appdash not found

### ISSUE THREAD

**Issue by linuxluigi** [pulumi/pulumi#14762]
### What happened?

When using github.com/pulumi/pulumi/sdk/v3 v3.95.0 `go mod tidy` fails to download `appdash` with to following error message:

```bash
go: github.com/exivity/pulumiconfig/pkg/pulumiconfig imports
        github.com/pulumi/pulumi/sdk/v3/go/pulumi imports
        github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin imports
        github.com/pulumi/pulumi/sdk/v3/go/common/workspace imports
        github.com/go-git/go-git/v5 imports
        github.com/go-git/go-git/v5/utils/ioutil imports
        github.com/acomagu/bufpipe tested by
        github.com/acomagu/bufpipe.test imports
        github.com/matryer/is: sourcegraph.com/sourcegraph/appdash@v0.0.0-20211028080628-e2786a622600: unrecognized import path "sourcegraph.com/sourcegraph/appdash": reading https://sourcegraph.com/sourcegraph/appdash?go-get=1: 404 Not Found
```

Strange is also, that I now got the same error for `github.com/pulumi/pulumi/sdk/v3 v3.94.2`

As a workaround in `v3.94.2` I added a `replace` statement in my `go.mod` file:

```
module github.com/exivity/pulumiconfig

go 1.21.4

require (
	github.com/go-playground/validator/v10 v10.16.0
	github.com/pulumi/pulumi/sdk/v3 v3.94.2
	github.com/stretchr/testify v1.8.4
)

replace sourcegraph.com/sourcegraph/appdash => github.com/pulumi/appdash v0.0.0-20211028080628-e2786a622600
```

### Example

```bash
echo "" > go.sum
go clean -cache -modcache
go mod tidy
```

### Output of `pulumi about`

❯ pulumi about
CLI          
Version      3.95.0
Go Version   go1.21.4
Go Compiler  gc

Host     
OS       darwin
Version  14.0
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Was fixed by https://github.com/pulumi/pulumi/pull/14726 we just need to tag a release.

**Comment by linuxluigi** [comment]
Awesome, thanks
