### ISSUE TITLE
`pulumi config` should provide a flag to open an environment

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#14770]
Summarizing a conversation internally. We have a few options here.

### Current behavior

The current behavior is that the environment is that `pulumi config` does a `read` and not an `open` on the environment. There is no flag or other mechanism to change that currently.

#### Option 1: Make the environment open by default.

In this case, the environment is opened by default when running either `pulumi config` or `pulumi config get`. 
- Secrets will be elided if the command is `pulumi config` (and revealed if `--show-secrets` is passed). 
- Secrets will be revealed if the command is `pulumi config get`. This is consistent with the existing behavior of this command.

Pros:
- Feels consistent with existing functionality.
- Not introducing any new overhead for users.

Cons:
- Potential RBAC issues (a user may be able to read but not open an environment).
- Potentially unnecessary opens muddling auditing.

#### Option 2: Open the environment if `--show-secrets` is passed as a flag.

In this case, the environment is `read` by default, but `open`ed when the `--show-secrets` flag is passed.
- This means that `pulumi config get` will open by default, consistent with the existing behavior of showing secrets if using this command.

Pros:
- Not introducing any new overhead for users.
- Utilizes existing flags and commands.

Cons:
- Not all dynamic values are secrets. Muddling concepts.

#### Option 3: Introduce a new `--open` flag.

In this case, the environment is `read` by default, but `open`ed when the `--open` flag is passed. The behavior of the various commands, flags and interactions are described below.
- `pulumi config` -> not open, secrets elided
- `pulumi config --show-secrets` -> env not open, stack config secrets shown, environment secrets and dynamic values unresolved
- `pulumi config --open` -> env open, secrets elided
- `pulumi config --open --show-secrets` -> env open, all secrets shown
- `pulumi config get` -> env not open, stack config secrets shown, environment secrets and dynamic values unresolved
- `pulumi config get --open` -> env open, secrets shown

Pros:
- Only opened when expressly needed.

Cons:
- New flag a user needs to learn about and use.
- Potentially confusing if you don't deeply understand the intricacies of the product.
- Not buttery smooth.

### Recommendation

My recommendation is for the environment to open by default when running `pulumi config`. In the case of RBAC issues, we can fall back to the `read` behavior. It provides the smoothest experience for the user without muddling concepts.

**Comment by cleverguy25** [comment]
I feel that Option 2 is best, because down the line if we are generating temporary credentials we will hear from security teams at larger companies.

**Comment by pgavlin** [comment]
IMO the best choice is a combination of (2) and (3): add an `--open` flag that defaults to `false` unless `--show-secrets` is `true`, in which case `--open` also defaults to `true`. I think that will deliver the flexible behavior with reasonable defaults.
