### ISSUE TITLE
`pulumi config env rm` and `pulumi config env add` do not respect `--non-interactive` flag

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#14773]
Just what it says on the tin. When running `pulumi config env rm` or `pulumi config env add` in a `---non-interactive` context, it should show the same error as `pulumi up` like:
```
error: --yes must be passed in to proceed when running in non-interactive mode
```

**Comment by janerikcarlsen** [comment]
+1 to this, any timeline for a fix?

**Comment by julienp** [comment]
This was fixed with https://github.com/pulumi/pulumi/pull/16338, release in 3.120.0
