### ISSUE TITLE
`@pulumi/pulumi` 3.95.0 regressed in combination with `@pulumi/eks`

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#14819]
### What happened?

Customer accidentally picked up `@pulumi/pulumi` 3.95.0 by using `npm install` rather than `npm ci`. [This release](https://github.com/pulumi/pulumi/releases/tag/v3.95.0) contains the following change:

* [feat: enable imports from nodejs provider resources](https://github.com/pulumi/pulumi/pull/14668/files)

Due to that, `@pulumi/eks` resources like `eks:index:VpCni` dropped the `inputs` section from the state file during `pulumi refresh`. Because an empty collection is returned, the existing `inputs` are dropped. If `undefined` would be returned, these `inputs` would be retained.

When running the subsequent `pulumi preview` or `pulumi up`, an addition of the full `kubeconfig` is presented to the user to add the `inputs` section again.

### Example

This flipping behaviour will continue until the case for `result.props === undefined` is handled.

### Output of `pulumi about`

* Pulumi CLI 3.34.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/14803.
