### ISSUE TITLE
Can't create empty text asset

### ISSUE THREAD

**Issue by mmdriley** [pulumi/pulumi#1481]
Calling `NewTextAsset("")` or, in JS, `new pulumi.asset.StringAsset("")`, produces an asset that can't be used. Trying to use it fires this assert:

https://github.com/pulumi/pulumi/blob/9916cd5e6b27a3535a044cf52adcac335fc66660/pkg/resource/asset.go#L286

https://github.com/pulumi/pulumi/blob/9916cd5e6b27a3535a044cf52adcac335fc66660/pkg/resource/asset.go#L266-L268

https://github.com/pulumi/pulumi/blob/9916cd5e6b27a3535a044cf52adcac335fc66660/pkg/resource/asset.go#L84

**Comment by lukehoban** [comment]
Fixed with #1599.
