### ISSUE TITLE
warning: automatic is deprecated: `automatic` is deprecated and will be removed in a future major release. Use `auto` instead.

### ISSUE THREAD

**Issue by aaron-tillekeratne** [pulumi/pulumi#14812]
### What happened?

When using pulumi preview / apply the following warning messages are spat out. 

   warning: automatic is deprecated: `automatic` is deprecated and will be removed in a future major release. Use `auto` instead.

### Example

I believe this might be due to dynamic resources but unsure. 

### Output of `pulumi about`

CLI          
Version      3.95.0
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.67.1
python  unknown

Host     
OS       debian
Version  12.2
Arch     x86_64

This project is written in python: executable='/usr/local/bin/python3' version='3.10.13'

Current Stack: organization/CloudNest/main

<<< REMOVED DUE TO SENSITIVE INFO>>>

Found no pending operations associated with main

Backend        
Name           649ac713e676
URL            gs://cloud-nest-backend
User           vscode
Organizations  
Token type     personal

Dependencies:
NAME          VERSION
autoflake     2.2.1
black         23.11.0
cryptography  41.0.5
ipython       8.17.2
isort         5.12.0
Jinja2        3.1.2
pip           23.0.1
pulumi-gcp    6.67.1
PyGithub      2.1.1
pytest        7.4.3
setuptools    68.2.2
toml          0.10.2
wheel         0.41.3

### Additional context

Nothings failing it's just a set of warnings. 
![image](https://github.com/pulumi/pulumi/assets/140357962/0ca5ebef-ce1d-42f3-967b-561ca1aa61a2)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aaron-tillekeratne** [comment]
Did do a quick google on it, but couldn't find an obvious thread on it.

**Comment by Frassle** [comment]
This looks like it will be due to a property in pulumi-gcp, although I can't find any properties called automatic in a quick github search. Does your program use any other resource providers?

**Comment by aaron-tillekeratne** [comment]
Only the dynamic resource provider for some of my own custom resources. The only place I can think of is the gcp provider's `gcp.secretmanager.SecretManagerReplicationArgs`, but contrary to the warning i'm actually using the `auto` . 
![image](https://github.com/pulumi/pulumi/assets/140357962/a8f6a0ec-f54c-4991-97bb-a0540632a0db)

**Comment by Frassle** [comment]
I think this might be a bug with defaults where even if you don't set the field it still warns about it.
https://github.com/pulumi/pulumi/issues/12546 which was closed but I think all the relevant fixes were reverted out due to other issues they caused.

**Comment by aaron-tillekeratne** [comment]
Righto, if it's not future breaking, happy to close this.
