### ISSUE TITLE
`pulumi new python` add param to specify `venv` path

### ISSUE THREAD

**Issue by copdips** [pulumi/pulumi#14810]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Hi,
I have a question about Python venv,  when running `pulumi new python` in a new project,  the command automatically creates `venv` folder, and installs all the requirements at once. 
Is there anyway to specify a custom `venv` folder instead of the default one ? Say I would like to set it to `.venv`. because in my IDE and shell, I have some hooks bound to `.venv`.
I know how to alter it after running the command, what I need is to alter it before or during the command.
I would be nice if  `pulumi new python`  could add a param to set the venv path.
Thanks

**Comment by aaron-tillekeratne** [comment]
I would extend this to not having any VENV path at all and just use the default PYTHONPATH if not specified.

**Comment by justinvp** [comment]
Thanks for opening the issue for this suggestion! I do think it'd be useful to have per-language prompts like this. I could also imagine prompting for the package manager that you'd like to use (e.g. built-in venv, poetry, etc.).

Related: #13833

**Comment by julienp** [comment]
This is now possible, you can run `pulumi new python --runtime-options virtualenv=.venv --force`. Implemented in https://github.com/pulumi/pulumi/issues/15937
