### ISSUE TITLE
[sdk/nodejs] invokes don't respect the `pluginDownloadURL`

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi#14839]
_A follow-up to https://github.com/pulumi/pulumi/pull/8698._

The NodeJS SDK doesn't propagate the `pluginDownloadURL` option to the `Invoke` RPC.  This may be observed in the RPC log by contrasting the entries for `RegisterResource` and the corresponding `Invoke`.

The problem appears to be that the `runtime.createInvokeRequest` function doesn't set the `pluginDownloadURL` on the `ResourceInvokeRequest` request object.

https://github.com/pulumi/pulumi/blob/061d10b4e2b14a36ab9c8b70c36edc19bf94bb30/sdk/nodejs/runtime/invoke.ts#L203-L217

### Repro
```ts
new k8s.yaml.ConfigGroup("cg-options", {
    resourcePrefix: "cg-options",
    yaml: [`
apiVersion: v1
kind: ConfigMap
metadata:
  name: cg-options-cm-1
`],
},
    {
        providers: [aProvider],
        version: "1.2.3",
        pluginDownloadURL: "https://a.pulumi.test",
    });

```

```json
{
  "method": "/pulumirpc.ResourceMonitor/RegisterResource",
  "request": {
    "type": "kubernetes:yaml:ConfigGroup",
    "name": "cg-options",
    "object": {},
    "version": "1.2.3",
    "pluginDownloadURL": "https://a.pulumi.test",
  }
}
```

```json
{
  "method": "/pulumirpc.ResourceMonitor/Invoke",
  "request": {
    "tok": "kubernetes:yaml:decode",
    "args": {
      "text": "\napiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: cg-options-cm-1\n"
    },
    "provider": "urn:pulumi:p-it-pulumitron-options-689f6992::options-test::pulumi:providers:kubernetes::a::b574c8fd-f513-4422-a215-e2dbe6c91433",
    "version": "1.2.3",
    "acceptResources": true
  },
  "response": {
    "return": {
      "result": [
        {
          "apiVersion": "v1",
          "kind": "ConfigMap",
          "metadata": {
            "name": "cg-options-cm-1"
          }
        }
      ]
    }
  },
  "metadata": {
    "mode": "server"
  }
}

````

More background:
- https://github.com/pulumi/pulumi/pull/2648
- https://github.com/pulumi/pulumi/pull/8544

**Comment by heyzling** [comment]
I got stuck with this issue while building a Terraform-Pulumi bridge provider for NodeJS. I checked if the suggested fix with `ResourceInvokeRequest` would work, and it did!

So the change is basically to add `req.setPlugindownloadurl(opts.pluginDownloadURL || "");`

```ts
const req = new resourceproto.ResourceInvokeRequest();
req.setTok(tok);
req.setArgs(obj);
req.setProvider(provider || "");
req.setVersion(opts.version || "");
req.setAcceptresources(!utils.disableResourceReferences);
req.setPlugindownloadurl(opts.pluginDownloadURL || "");
return req;
```

After this fix, the provider downloads successfully from the custom source, i.e., `PluginDownloadURL`.

**Comment by Frassle** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/16917
