### ISSUE TITLE
docs: fix import of pulumi identity

### ISSUE THREAD

**Issue by lukibahr** [pulumi/pulumi#14845]
File: [themes/default/content/registry/packages/oci/api-docs/Identity/compartment/_index.md](https://www.pulumi.com/registry/packages/oci/api-docs/identity/compartment/)

the import of pulumi identity package provided by the snippets do not work with case sensitive letters. Importing the identity module requires to replace the capital letter with a lowercase "i".

```go
package main

import (
	"github.com/pulumi/pulumi-oci/sdk/go/oci/Identity" # must be replaced with a lowercase i
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
	
```

**Comment by toriancrane** [comment]
Hi @pulumi/engineering team!

Given that this issue is inside of an example, is this an upstream issue?

**Comment by iwahbe** [comment]
> Hi @pulumi/engineering team!
> 
> Given that this issue is inside of an example, is this an upstream issue?

Yep, this looks like a program-gen issue to me.
