### ISSUE TITLE
Support for NO_COLOR?

### ISSUE THREAD

**Issue by pzel** [pulumi/pulumi#1486]
Would it be possible to detect that `NO_COLOR` (http://no-color.org/) is set and not produce colored output in this case? 

I have bad eyes and use high-contrast black-on-white color schemes. Short of always remembering to invoke pulumi with the `-c never` option, there's no way to make the output uniformly legible for people who need high contrast to work.

Attached are screenshots that illustrate
1) running pulumi in my terminal
2) running `pulumi update -c never` and still getting purple output on the screen.

![pulumi-in-white-terminal](https://user-images.githubusercontent.com/344774/41248783-deebf0e0-6d66-11e8-9366-f777f01c42b2.png)
![pulumi-in-white-terminal-color-never](https://user-images.githubusercontent.com/344774/41248784-df04fb9e-6d66-11e8-9f5e-40b78c10c75f.png)

**Comment by tamsky** [comment]
> Short of always remembering to invoke pulumi with the `-c never` option

add to that, some commands don't currently recognize that option.  examples

**Comment by tamsky** [comment]
> Short of always remembering to invoke pulumi with the `-c never` option

most commands don't currently recognize that option.

it's shorter to simply list the commands that *do* support `-c never`:

```
# for cmd in $(pulumi help 2>&1 | awk 'NR==1, /^Available Commands:/ { next; } /^Flags:/ {exit;} {print $1}') ; do pulumi $cmd --help 2>&1 | grep color >/dev/null && echo $cmd ; done
destroy
preview
refresh
update
```

**Comment by CyrusNajmabadi** [comment]
Fixed with: https://github.com/pulumi/pulumi/pull/1594

**Comment by CyrusNajmabadi** [comment]
@pzel Pulumi will not respect hte NO_COLOR env flag if you have it set. Let me know if you see any pesky colors sneaking into the command line!

**Comment by ericrudder** [comment]
I think @cyrusnajmabadi actually means we will "now respect" ... in other
words, you should be good to go!

**Comment by CyrusNajmabadi** [comment]
Indeed.  i always make that typo :)

Fixed with https://github.com/pulumi/pulumi/pull/1594

**Comment by pzel** [comment]
Thank you @CyrusNajmabadi! Works like a charm! I've added a PR so that pulumi takes its rightful place on https://no-color.org :)

**Comment by CyrusNajmabadi** [comment]
Terrific.  Glad we could help out!
