### ISSUE TITLE
Support running Pulumi in lower-tech terminals

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1492]
From one of our beta testers:

> Is there a way to disable the curses-based decision prompt in Pulumi? I usually run a dumb terminal in an Emacs buffer and it doesn't support cursor-addressing.

Which if I understand correctly, means that Pulumi simply won't work in such an environment. Can we detect being in a "dumb terminal" and fallback to a less fancy output scheme? I imagine this would also mean having a low-tech way to render our tree-based progress view too.

**Comment by joeduffy** [comment]
Basically the same as https://github.com/pulumi/pulumi/issues/1851, so closing out in favor of that.

**Comment by pzel** [comment]
For what it's worth, I've solved this for my workstation by always using `--yes` `--non-interactive`, but this is suboptimal, because sometimes it's very nice to have Pulumi tell the user what it's going to do and wait for input.
In the ` emacs/M-x shell` case, I think detecting a dumb terminal and falling back to a basic stdin read-line for the query 'yes / no / details`  would provide the benefit of interactivity to low-tech terminal users.

**Comment by CyrusNajmabadi** [comment]
This is a bit strange.  We do actually try to detect if we're in a TTY or not and we fallback to non-interactive mode if so. We use a go-package to help determine this.  But it sounds like in emacs that isn't working properly.  So emacs somehow feels like a terminal to this package, but doesn't respond well to how we're using the terminal :-/

**Comment by pzel** [comment]
This is what I have in my emacs shell:
```
$ env | grep TERM
TERM=dumb
TERMCAP=
```

**Comment by pzel** [comment]
Yeah, like [this comment](https://stackoverflow.com/questions/47062370/what-does-inside-emacs-do-for-bash#comment81083020_47064310) clarifies, relying on `INSIDE_EMACS` for terminal capabilities is probably the wrong approach. That variable simply means that the given terminal emulator was launched from within emacs, but says nothing about its display capabilities.

For example, it's possible to run `vim` inside a terminal launched with `M-x term` (it supports cursor addressing), but impossible inside `M-x shell` (which is an instance of `comint-mode`, a dumb terminal).

On a practical note, pulumi's interactive features don't work in `M-x term` either, giving this weird error when I press up-arrow:

```

Do you want to perform this update?
  yes
> no
  details
error: confirmation cancelled, not proceeding with the update: Unexpected Escape Sequence: ['\x1b
' 'O']                                                                                          
pulumi$ ```

The animated in-place progress bars do work, though.

**Comment by CyrusNajmabadi** [comment]
This seems unfortunate.  It looks like this issue has been reported with other tools which depend on go's terminal lib: https://github.com/golang/go/issues/26254

But the fix seems to be to literally just look for the TERM variable and disable things if it is `<empty>` or if it is 'dumb': https://golang.org/src/cmd/pprof/readlineui.go.

I suppose we'll just have to do the same, as i can't see any consistent way in the 'go' world to know this sort of thing.
