### ISSUE TITLE
Expressive diagnostics

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#15]
After we have done pulumi/lumi#14, we can go a step further and add "expressive" diagnostics, a la [Clang](http://clang.llvm.org/diagnostics.html).  This helps with usability.

**Comment by pgavlin** [comment]
related: #1712

**Comment by swgillespie** [comment]
I'm assuming we're not interested in expressive diagnostics in the context of a programming language frontend anymore, are we? 😆

**Comment by pgavlin** [comment]
I wouldn't be so sure. IIRC we've kicked around the idea of providing optional source locations to `RegisterResource` et. al. so the CLI/service/etc. could display this information in its errors.
