### ISSUE TITLE
Error please log in to Pulumi Cloud to use Pulumi AI when creating a new project

### ISSUE THREAD

**Issue by matusnovak** [pulumi/pulumi#15003]
### What happened?

I am trying to create a new project with pulumi on the command line with `pulumi new`, but it is asking me to log in to use an AI.

I am using the local filesystem backed login.

I do not wish to use an AI, nor I have explicitly enabled the AI (if such toggle exists). I am simply trying to create a new project on the command line.

### Example

```
$ pulumi login --local
$ pulumi new --language python
error: please log in to Pulumi Cloud to use Pulumi AI
```

### Output of `pulumi about`

```
CLI          
Version      3.99.0
Go Version   go1.21.5
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

Backend        
Name           mnovak-thinkpad
URL            file://~
User           mnovak
Organizations  
Token type     personal

Pulumi locates its logs in /tmp by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /home/mnovak/Documents/pulumi-test). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Failed to get information about the current stack: no Pulumi.yaml project file found (searching upwards from /home/mnovak/Documents/pulumi-test). If you have not created a project yet, use `pulumi new` to do so: no project file found
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@matusnovak, the `--language` flag is only for use when using Pulumi AI to create the project. Try running `pulumi new` without any flags to choose a template. If you just want the basic Python template, you can run `pulumi new python`.

**Comment by justinvp** [comment]
We may want to consider making the `--language` flag work when in "template-mode". For example, `--language python` could act as a filter and only show python templates. If we were to do this, we'd likely have to filter based on the name of the templates rather than the `runtime` project option, because `runtime` isn't specific enough to filter JavaScript vs. TypeScript, or C# vs. F#.

**Comment by matusnovak** [comment]
Oh, right! That makes sense. Thank you very much for your response. I will close this issue if you don't mind.

**Comment by swgillespie** [comment]
Hey @justinvp, I just got hit by this too and this is super confusing for new users, particularly since there's nothing in the CLI gesture that indicates I'm using AI in any way.

**Comment by justinvp** [comment]
Hey @swgillespie! Yeah, let me re-open this issue so we can track addressing the UX issue. Thanks for the ping! Hope all is well.
