### ISSUE TITLE
Tree-view doesn't display well in non-UTF8 codepages

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#1500]
Ends up looking like:

![image](https://user-images.githubusercontent.com/4564579/41306597-7965fcfa-6e2b-11e8-9822-e227372fab32.png)

Not sure if there's a way to force things to use the right characters here.  If there isn't, we can attempt to detect if we're not in a UTF8 codepage and fallback to not having the treeview.

**Comment by ellismg** [comment]
I'm tempted to just saw we close this until we get feedback that this experience isn't great.  My biggest fear here was the behavior on Windows, but the experience actually isn't awful like the above there (the line drawing characters all seem to work).

If we find a substantial amount of usage in places where the table is not rendered, we can figure out how to work around this, but I'd rather just say: "we aren't going to fix this, abset feedback from real users" than to punt int down the milestone path.

**Comment by CyrusNajmabadi** [comment]
That's totally fine with me.  I opened it for awareness.  But absent anyone actually on some non-utf8 system, i don't thin kwe have to do anything here.
