### ISSUE TITLE
Cannot update stack - updateInProgress python

### ISSUE THREAD

**Issue by shaugland** [pulumi/pulumi#15029]
### What happened?

When trying to update the stack and listing stacks with the python sdk, python gives an error saying KeyError: 'updateInProgress'.
It used to work with pulumi 3.75 but now does not work with pulumi 3.97-3.99
Any advice is appreciated

### Example

Diagnostics:
  pulumi:pulumi:Stack (vmtep-catalog.ndev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/home/vsts/work/r1/a/_catalog/pulumi/deploy/./__main__.py", line 28, in <module>
        core_stacks_refs = stack_handler.get_stack_references(f"core.{config.env_name}")
      File "/home/vsts/work/r1/a/_catalog/pulumi/deploy/venv/lib/python3.8/site-packages/pulumi_helpers/stacks/stack_handler.py", line 18, in get_stack_references
        if stack_name in [stack.name for stack in self.list_stacks()]:
      File "/home/vsts/work/r1/a/_catalog/pulumi/deploy/venv/lib/python3.8/site-packages/pulumi_helpers/stacks/stack_handler.py", line 12, in list_stacks
        return [stack for stack in self.current_stack.workspace.list_stacks()]
      File "/home/vsts/work/r1/a/_catalog/pulumi/deploy/venv/lib/python3.8/site-packages/pulumi/automation/_local_workspace.py", line 316, in list_stacks
        update_in_progress=stack_json["updateInProgress"],
    KeyError: 'updateInProgress'

### Output of `pulumi about`

CLI          
Version      3.97.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME           VERSION
gcp            6.30.0
google-native  0.20.0
python         unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.8.10'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
This is caused by https://github.com/pulumi/pulumi/pull/14309.

Assuming you're not using Pulumi Cloud, this `updateInProgress` field was misleading, as it would always have been false.  We updated the python SDK at the same time to ignore this field, but it looks like the python SDK in your venv is still an older version.  Could you try updating that to the latest version, which should resolve this issue.

**Comment by shaugland** [comment]
Unfortunately updating to pulumi v3.99.0 is also throwing that issue. Is there a specific version I should try?

**Comment by Frassle** [comment]
What's the stacktrace show for v3.99?

**Comment by shaugland** [comment]
Ope, looks like we were updating it via pip instead of using the requirements.txt
Updating it through requirements.txt worked
Thanks for the help!
