### ISSUE TITLE
 internal error loading package "file": stat ../pulumi-resource-file: no such file or directory

### ISSUE THREAD

**Issue by JCzz** [pulumi/pulumi#15036]
### What happened?

Trying to use custom provider: https://github.com/pulumi/pulumi-go-provider/blob/main/examples/file/consumer/Pulumi.yaml

### Example

```
git clone https://github.com/pulumi/pulumi-go-provider.git
cd consumer
pulumi login --local
pulumi up
```

pulumi up
```
Enter your passphrase to protect config/secrets:  
Re-enter your passphrase to confirm:  
Previewing update (dev):
     Type                 Name                      Plan       Info
 +   pulumi:pulumi:Stack  consume-random-login-dev  create     3 messages

Diagnostics:
  pulumi:pulumi:Stack (consume-random-login-dev):
    Error: error resolving type of resource managedFile: internal error loading package "file": stat ../pulumi-resource-file: no such file or directory
      on Pulumi.yaml line 11:
      11:     type: file:File

Resources:
    + 1 to create
```

### Output of `pulumi about`

pulumi about                              
```
CLI          
Version      3.99.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME  VERSION
file  unknown
yaml  unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in yaml

Backend        
Name           <me>-MBP.localdomain
URL            file://~
User           <me>
Organizations  
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/ws/r3lmtqdj03d3jn5l3v3t_s3w0000gn/T/ by default
warning: Failed to get information about the current stack: No current snapshot
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
From https://github.com/pulumi/pulumi-go-provider/blob/main/examples/README.md, it looks like there are more steps than running `pulumi up`...

> You can build the provider and then run the `consumer/Pulumi.yaml` example against it with the folling 1-liner:
>
> ```sh
> go build github.com/pulumi/pulumi-go-provider/examples/$(basename $PWD) && pulumi plugin install resource $(basename $PWD) v0.1.0 -f $(basename $PWD) --reinstall && (cd consumer && pulumi up)
> ```

**Comment by JCzz** [comment]
Thanks @justinvp 
Hmm, still the same, but now it creates a file named: file
