### ISSUE TITLE
Failed serializing native fetch in Node  >= 18

### ISSUE THREAD

**Issue by andreujuanc** [pulumi/pulumi#15039]
### What happened?

Using native fetch failed when serializing a lambda.

### Example

```
function handler(){
    return fetch('https://google.com')
}
```

Throws: `Unexpected missing variable in closure environment: fetch`

I fixed it by using `global.fetch`.

### Output of `pulumi about`

CLI          
Version      3.95.0
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
awsx    1.0.2
docker  3.6.1
nodejs  unknown

Host     
OS       debian
Version  10.13
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v16.20.0'

Dependencies:
NAME                      VERSION
@aws-sdk/util-dynamodb    3.258.0
@types/pg-format          1.0.2
@types/pg                 8.6.6
dotenv                    16.0.3
jest                      29.2.2
@lambada/core             1.9.3
@types/node               16.18.11
pg                        8.11.3
undici                    5.16.0
csv-parse                 5.4.0
pg-format                 1.0.4
ts-jest                   29.0.5
ts-node                   10.9.1
typescript                4.9.4
@aws-sdk/client-dynamodb  3.257.0
@pulumi/aws               5.42.0
@pulumi/pulumi            3.52.1
@types/jest               29.2.5
postgres                  3.3.5

### Additional context

Is this the correct behaviour?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by julienp** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/15873
