### ISSUE TITLE
Release 3.100.0 is broken

### ISSUE THREAD

**Issue by andy-nix** [pulumi/pulumi#15043]
### What happened?

Release workflow failed: https://github.com/pulumi/pulumi/actions/runs/7404894608

### Example

There is no docker image for version 3.100.0 (https://hub.docker.com/r/pulumi/pulumi-python/tags?page=1&name=3.100) neither python package in pypi (https://pypi.org/project/pulumi/). However version 3.100.0 is available in npm (https://www.npmjs.com/package/@pulumi/pulumi)

### Output of `pulumi about`

Make no sense

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
This is now fixed.
