### ISSUE TITLE
`pulumi new aws-javascript` fails with "error: read ".pulumi/meta.yaml"

### ISSUE THREAD

**Issue by seanthingee** [pulumi/pulumi#15136]
### What happened?

Trying to create a new project with `pulumi new`. It appears to be attempting to connect to a backend. It is not expected that a backend would need to be connected to at this stage.

### Example

```
❯ mkdir 'pulumietst'
❯ cd pulumietst/
❯ pulumi new aws-javascript
error: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

### Output of `pulumi about`

```
❯ pulumi about
CLI          
Version      3.101.0
Go Version   go1.21.5
Go Compiler  gc

Host     
OS       darwin
Version  14.2.1
Arch     arm64

Pulumi locates its logs in /var/folders/sf/2stxvcjn7jlgxrg3q9h5wnnr0000gp/T/ by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /Users/username/projects/pulumietst). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Could not access the backend: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

### Additional context

```
❯ node -v
v21.2.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> It is not expected that a backend would need to be connected to at this stage.

It is expected. Use the `--generate-only` flag if you just want to generate the project files but not do any stack setup or dependency installation.

**Comment by seanthingee** [comment]
@Frassle Thank you for that. I must be missing something, though. The [create new project page](https://www.pulumi.com/docs/clouds/aws/get-started/create-project/) makes it seem like I shouldn't be receiving this error. If anything, I should receive a prompt for setting up Pulumi Cloud as it states.

**Comment by tgummerer** [comment]
You should definitely not be receiving this error, it seems to be another regression related to the gocloud.dev upgrade (see also https://github.com/pulumi/pulumi/issues/15126), and the patch release we just released should fix this issue.

Just to help me to track down the issue, since this seems to be a slightly different problem than I've seen before, is this the first time running pulumi?  Or did you try to log in to a aws backend at some point before?

**Comment by seanthingee** [comment]
> is this the first time running pulumi? Or did you try to log in to a aws backend at some point before?

I've used pulumi successully once before in a different project last year that used an AWS backend. However, in this case, I am essentially using pulumi for the first time trying to create a new project. My memory is a little fuzzy from last year, but I believe after I create a new project I can configure it with a backend.

Version 3.101.1 yields the same result.

```
❯ pulumi version
v3.101.1

❯ pulumi new
error: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by seanthingee** [comment]
@tgummerer I just tried 3.101.0 on another Mac and it's working as expected, so this issue I'm having may not be related to gocloud.dev upgrade.

**Comment by seanthingee** [comment]
I figured it out. I didn't realize or remember that pulumi stores the backend in a central location: `$HOME/.pulumi/credentials.json`. Therefore I was not actually running pulumi "for the first time" as I thought and, of course, without the credentials it cannot access the backend. Also, the IAM user I was choosing to use didn't actually have access to the backend state bucket like I thought it did.

Changes in [e47c582](https://github.com/pulumi/pulumi/commit/e47c5823c0274769094ac970e8f31108c6a6bd85) led to change the error message. It is more vague now. Running v3.58.0 shows a more specific error message which led me to realize it was attempting to access my bucket specifically.

3.58.0: 
```
warning: A new version of Pulumi is available. To upgrade from version '3.58.0' to '3.101.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
error: unable to check if bucket s3://my-bucket is accessible: blob (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated
```


3.59.0:
```
warning: A new version of Pulumi is available. To upgrade from version '3.59.0' to '3.101.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
error: read ".pulumi/Pulumi.yaml": blob (key ".pulumi/Pulumi.yaml") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by tgummerer** [comment]
@seanthingee awesome, I'm glad you figured that out!  That's also good feedback that this error message got a bit worse, I'll open a separate issue to try and improve that, thank you!

**Comment by cnunciato** [comment]
@tgummerer Is this issue the same as this one? https://github.com/pulumi/pulumi/issues/13899
