### ISSUE TITLE
Display Fully Qualified Type Names in Python Generated Documentation

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#15137]
### What happened?

A user reported consulting the Python language documentation and experienced difficulty in determining the correct input to use. This was attributed to the absence of fully qualified type names, leading to confusion, and causing the user to get stuck on the issue.

### Example

This behavior can be observed in the Kubernetes documentation [here](https://www.pulumi.com/registry/packages/kubernetes/api-docs/core/v1/pod/#metadata_python) when switching between Python and the other languages. Specifically in the example mentioned before, the user didn't know and had trouble finding that their required class was in meta.v1.

### Output of `pulumi about`

N/A

### Additional context

It looks like it possibly could be related to [this](https://github.com/pulumi/pulumi/blob/196727d7f4f36a7a60fdd5c9eb77ba40236b977a/pkg/codegen/docs/templates/utils.tmpl#L9) conditional between `.Name` and `.DisplayName`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by desteves** [comment]
Thanks, @zbuchheit, for bringing this to our attention. I'm adding screenshots to highlight the experience described above.

Here's an example of the Inputs table missing the fully qualified name for `ObjectMetaArgs` in Python:
<img width="666" alt="image" src="https://github.com/pulumi/pulumi/assets/2991841/e350cac1-226d-4545-a0cf-de8dc393e6bc">


Meanwhile, here's an example of the Inputs table showing the fully qualified name as `meta.v1.ObjectMeta` in the Inputs table when selecting Typescript.
<img width="666" alt="image" src="https://github.com/pulumi/pulumi/assets/2991841/fcbecd8e-9745-4d76-b2f5-3c87fb17fdb7">


Thanks for pointing out the potential source of the problem in the `utils.tmpl` file.
