### ISSUE TITLE
improve error message if bucket is not available (filestate backend)

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#15141]
The error message when trying to access a bucket with wrong credentials isn't very descriptive:

```
error: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): MissingRegion: could not find region configuration
```

It would be nice if we could improve that, so users don't get confused what's happening, and can figure out a solution to their problems quicker.  See also https://github.com/pulumi/pulumi/issues/15136#issuecomment-1887519218.

**Comment by emilhotkowski** [comment]
@tgummerer I'd be happy to look into this.

**Comment by tgummerer** [comment]
Awesome, I think this will mostly involve improving the error message (and not re-introducing the `IsAccessible` call, since I don't think we'll want to introduce more network calls where we don't need to.  Happy to review a PR here!

**Comment by cnunciato** [comment]
@tgummerer Is this issue the same as this one? https://github.com/pulumi/pulumi/issues/13899

**Comment by tgummerer** [comment]
Maybe, yeah.  I don't know if there's anything to done in #13899 other than improving the error message, so users can help themselves.  Similarly the idea here is that we should improve the error message for these errors to allow users to more easily help themselves.  

Gonna close this issue out and suggest that there then.
