### ISSUE TITLE
Installing local language plugin on Windows does not append required ".exe"

### ISSUE THREAD

**Issue by andrzejressel** [pulumi/pulumi#15150]
### What happened?

When using `pulumi plugin install language` in Windows executable is copied to .pulumi plugins, but `.exe` is stripped. Due to that error `error: failed to load language plugin testlang: failed to load plugin C:\Users\user\.pulumi\plugins\language-testlang-v1.0.0\pulumi-language-testlang.exe: language plugins must be executable binaries` is shown during pulumi up

### Example

1. Download `https://get.pulumi.com/releases/sdk/pulumi-v3.101.1-windows-x64.zip` and extract pulumi-language-dotnet.
2. Install it using `pulumi plugin install language testlang 1.0 --file .\pulumi-language-dotnet.exe`
3. Create new pulumi project with `runtime: testlang`
4. Run pulumi up

` language plugins must be executable binaries` is shown

5. Add `.exe` to executable in `%userprofile%\.pulumi\plugins\language-testlang-v1.0.0`
6. Run pulumi up

Now language plugin is used

### Output of `pulumi about`

```
CLI          
Version      3.99.0
Go Version   go1.21.5
Go Compiler  gc

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22621 Build 22621
Arch     x86_64

Backend
Name           PC
URL            file://~
User           PC\USER
Organizations
Token type     personal
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Looks like a missing `+".exe"` inside `singleFilePlugin.writeToDir`. Should be a simple fix.
