### ISSUE TITLE
Strange formatting of "loading policy packs..." message

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#15183]
The "loading policy packs..." message is awkwardly offset - should it be left aligned like everything else?

<img width="878" alt="Screenshot 2024-01-18 at 7 31 07 PM" src="https://github.com/pulumi/pulumi/assets/24326455/47bccedb-339f-425d-b82f-5f220e14f933">

This is using CLI v3.102.0

**Comment by tgummerer** [comment]
Indeed, I do think it should be left aligned.  This is not only an issue with the `Loading policy packs...` message, but it's also an issue for subsequent messages from policy pack installations.  #15186 should fix it.
