### ISSUE TITLE
Resources from `Resource.get` trip up snapshot verification

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1521]
Repro program (assuming a bucket named "sean-testbucket" exists):

```javascript
"use strict";
const pulumi = require("@pulumi/pulumi");
const aws = require("@pulumi/aws");

const bucket = aws.s3.Bucket.get("bucket", "sean-testbucket");
const obj = new aws.s3.BucketObject("testobj", {
    bucket: bucket.id,
    content: "text"
});

exports.bucketName = bucket.bucketDomainName;
```

`pulumi update` fails with

```
error: failed to load language plugin nodejs: failed to perform plugin load callback: failed to save snapshot: after mutation of snapshot: resource urn:pulumi:get-dev::get::aws:s3/bucketObject:BucketObject::testobj dependency urn:pulumi:get-dev::get::pulumi:pulumi:Stack$aws:s3/bucket:Bucket::bucket refers to missing resource
```

The problem is that we do not place resources obtained from `Resource.get` in the snapshot. This is a problem for us. Depending on an Output property of a `Resource.get` resource causes us to record the dependency in the snapshot, but since we don't put `Resource.get` resources in the snapshot, snapshot verification fails.

**Comment by swgillespie** [comment]
I'm thinking the fix here is to set a bit on resources indicating whether or not Pulumi is managing them. If we're not managing it, we should not report such a dependency to the engine.

**Comment by joeduffy** [comment]
@swgillespie agree with that approach.

**Comment by joeduffy** [comment]
I ran into another instance of this.  I wanted to try out the new SQS Lambda support, and I did so by looking up an existing SQS queue using `get` rather than provisioning a new one.  Sadly, this did not work, because we end up parenting the subscription to the queue, which also tries to embed it inside of the checkpoint file.  The error I received was

```
error: post-step event returned an error: failed to save snapshot: after mutation of snapshot: resource urn:pulumi:post-sqs-slack-dev::post-sqs-slack::aws-serverless:queue:QueueEventSubscription::my-slack-poster dependency urn:pulumi:post-sqs-slack-dev::post-sqs-slack::pulumi:pulumi:Stack$aws:sqs/queue:Queue::my-queue refers to missing resource
```

**Comment by hausdorff** [comment]
Tagging `kubernetes/inner-dev-loop` because this affects parallelism, which is critical for the upcoming "kube moment"
