### ISSUE TITLE
go/auto TestUpsertStackInlineSourceParallel is flaky

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#15235]
```
=== FAIL: go/auto TestUpsertStackInlineSourceParallel/0 (8.55s)
    local_workspace_test.go:1023: preview failed, err: failed to get preview summary
        code: 0
        stdout: Previewing update (moolumi/testdec70387)
        
        View Live: https://app.pulumi.com/moolumi/testproj/testdec70387/previews/9708973f-09f7-4c62-b533-dc072b0bb454
        
        
            pulumi:pulumi:Stack testproj-testdec70387 running 
            pulumi:pulumi:Stack testproj-testdec70387  
        Resources:
            1 unchanged
        
        
        stderr: 

=== FAIL: go/auto TestUpsertStackInlineSourceParallel (0.00s)
```

Noticed in https://github.com/pulumi/pulumi/actions/runs/7640375721/job/20815758420 (with `--rerun-fails` turned off)

**Comment by tgummerer** [comment]
Another instance https://github.com/pulumi/pulumi/actions/runs/8277964268/job/22649650602 (this one has `--rerun-fails` turned on)

**Comment by tgummerer** [comment]
Also some prior art here: https://github.com/pulumi/pulumi/pull/9467.  I guess that didn't completely fix the flakyness for some reason.

**Comment by tgummerer** [comment]
Another breadcrumb on why this might be a windows only thing is that windows is the only platform where we are using poll instead of inotify for this.  This was introduced in https://github.com/pulumi/pulumi/pull/14659.  I wonder if while fixing one issue that introduced another one.

**Comment by tgummerer** [comment]
Apparently there's still some flakes here: https://github.com/pulumi/pulumi/actions/runs/8456791088/job/23167783667

**Comment by VenelinMartinov** [comment]
We hit this again in the bridge: https://github.com/pulumi/pulumi-terraform-bridge/actions/runs/11932712583/job/33258242529?pr=2641

```
    diff.go:121: failed to preview update: failed to get preview summary
        code: 0
        stdout: Previewing update (test):
          pulumi:pulumi:Stack: (same)
            [urn=urn:pulumi:test::project::pulumi:pulumi:Stack::project-test]
            +-testprovider:index/test:Test: (replace)
                [id=test-id]
                [urn=urn:pulumi:test::project::testprovider:index/test:Test::p]
              ~ id  : "test-id" => output<string>
              - keys: []
        Resources:
            +-1 to replace
            1 unchanged
        
        stderr: 
        
```

Looks like the same problem, we are using latest dev pu/pu version.


Is this a regression? @tgummerer 

Also hit this in GCP a while back: https://github.com/pulumi/pulumi-gcp/issues/1655 we can close that once fixed

**Comment by tgummerer** [comment]
I opened https://github.com/pulumi/pulumi/pull/17825 as a hopeful workaround for this issue.  Longer term we probably want to either fork or replace the `nxadm/tail` library, or replace it completely.  The library seems unmaintained, and there's a couple of PRs around this issue that have been ignored, at least https://github.com/nxadm/tail/pull/71 and https://github.com/nxadm/tail/pull/70.

**Comment by justinvp** [comment]
This looks like a product bug, not just a flaky test.

**Comment by tgummerer** [comment]
@VenelinMartinov are you still seeing the flake with https://github.com/pulumi/pulumi/pull/17825 applied? From https://github.com/pulumi/pulumi-terraform-bridge/issues/2530 it looks like you're seeing a different issue?

**Comment by VenelinMartinov** [comment]
From my discussion with @iwahbe it seemed likely that it has the same underlying issue - the automation API occasionally returns a nil instead of the correct response for configure. We might be wrong here.

We added the same workaround as we did for the `failed to preview update: failed to get preview summary` issue - one resource which uses the provider.
