### ISSUE TITLE
Exception creating new stack to interact with AWS in Python

### ISSUE THREAD

**Issue by KurtOps** [pulumi/pulumi#15249]
### What happened?

Pulumi fails to create a new stack with language Python when I run `pulumi new`. The following error message results:

      clang: warning: argument unused during compilation: '-fno-strict-overflow' [-Wunused-command-line-argument]
      clang: warning: argument unused during compilation: '-stdlib=libc++' [-Wunused-command-line-argument]
      creating None
      creating None/var
      creating None/var/folders
      creating None/var/folders/5z
      creating None/var/folders/5z/qk8j2tl540978qjdxks2rvjc0000gp
      creating None/var/folders/5z/qk8j2tl540978qjdxks2rvjc0000gp/T
      creating None/var/folders/5z/qk8j2tl540978qjdxks2rvjc0000gp/T/tmph841t4ze
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -arch arm64 -arch x86_64 -g -I/Users/<path>/venv/include -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c /var/folders/5z/qk8j2tl540978qjdxks2rvjc0000gp/T/tmph841t4ze/a.c -o None/var/folders/5z/qk8j2tl540978qjdxks2rvjc0000gp/T/tmph841t4ze/a.o
      Traceback (most recent call last):
        File "/Users/<path>/venv/lib/python3.12/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/private/var/folders/5z/qk8j2tl540978qjdxks2rvjc0000gp/T/pip-install-mgu40mt_/grpcio_66d023bba7de4cea93d651198f4fdb41/src/python/grpcio/_spawn_patch.py", line 57, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/Users/<path>/venv/lib/python3.12/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/Users/<path>/venv/lib/python3.12/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/clang' failed with exit code 1

      During handling of the above exception, another exception occurred:...

### Example

After setting up for AWS token, run:

`pulumi new kubernetes-aws-python`

The result is the stack trace above.

### Output of `pulumi about`

CLI
Version      3.102.0
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME    VERSION
python  unknown

Host
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in python: executable='/Library/Frameworks/Python.framework/Versions/3.12/bin/python3' version='3.12.1'

Current Stack: KurtOps/test/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/KurtOps
User           KurtOps
Organizations  KurtOps
Token type     personal

Dependencies:
NAME        VERSION
pip         23.3.2
setuptools  69.0.3
wheel       0.42.0

Pulumi locates its logs in /var/folders/5z/qk8j2tl540978qjdxks2rvjc0000gp/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@KurtOps, thanks for opening the issue and sorry for the trouble. This is https://github.com/pulumi/pulumi/issues/14258 and the fix was released minutes ago with v3.103.0 of the `pulumi` PyPi package! You should be able to run `pulumi new kubernetes-aws-python` in an empty directory and it should work on Python 3.12.
