### ISSUE TITLE
Docs: Fix aws.cognito.UserPoolUICustomization examples for base64 encoding file content

### ISSUE THREAD

**Issue by BrentJohnsonNz** [pulumi/pulumi#15246]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Provided aws.cognito.UserPoolUICustomization example for loading a custom imageFile in Typescript does not work.  The example code 

```
imageFile: Buffer.from(fs.readFileSync("logo.png", 'binary')).toString('base64'),
```

Produces the error:

```
**updating failed**     [diff: ~imageFile]; 1 error
* setting Cognito User Pool UI customization (UserPoolId: ap-southeast-2_*********, ClientId: ALL): InvalidParameterException: The uploaded image must be a valid .jpeg or .png file.
```

I believe this is caused by a misunderstanding of the effect of the 'binary' parameter passed to fs.readFileSync.  Rather than producing a UInt8 Buffer, instead this causes the buffer to contain 'latin1' (UTF16?) content, which encoded to Base64 produces an invalid PNG file.

Correct reading/uploading of the file can be achieved by removing the 'binary' parameter:

```
imageFile: Buffer.from(fs.readFileSync("logo.png")).toString('base64'),
```
or by using the Base64 feature of the readFileSync method:
```
imageFile: fs.readFileSync("logo.png", { encoding: 'base64' }),
```

A search of the documentation files in Github shows this same incorrect readFileSync 'binary' pattern in other locations, perhaps copy/pasted?

### Affected area/feature

[https://www.pulumi.com/registry/packages/aws/api-docs/cognito/userpooluicustomization/](https://www.pulumi.com/registry/packages/aws/api-docs/cognito/userpooluicustomization/)

**Comment by Zaid-Ajaj** [comment]
Hi there @BrentJohnsonNz, our docs are auto generated. They emit the following pattern for when trying to read a file encoded as base64 so this is something we might find in more examples. 
```ts
Buffer.from(fs.readFileSync(<file>, 'binary')).toString('base64')
```
We need to change it into what you suggested
```ts
fs.readFileSync(<file>, { encoding: 'base64' })
```
I've assigned the issue to myself and see to it shortly. Thanks a lot for reporting the issue and for suggesting the fix 🙏
