### ISSUE TITLE
v3.103.0 adds new unlisted Node dependency: "semver"

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#15250]
### What happened?

When I was trying to upgrade pulumi-gcp, I hit this error:

```
$ make build_nodejs

...

yarn run v1.22.21
$ /Users/ianwahbe/go/src/github.com/pulumi/pulumi-gcp/sdk/nodejs/node_modules/.bin/tsc
node_modules/@pulumi/pulumi/automation/cmd.d.ts:1:25 - error TS7016: Could not find a declaration file for module 'semver'. '/Users/ianwahbe/go/src/github.com/pulumi/pulumi-gcp/sdk/nodejs/node_modules/semver/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/semver` if it exists or add a new declaration (.d.ts) file containing `declare module 'semver';`

1 import * as semver from "semver";
                          ~~~~~~~~


Found 1 error in node_modules/@pulumi/pulumi/automation/cmd.d.ts:1

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
gmake: *** [Makefile:56: build_nodejs] Error 2
```

I observed that there was a new pulumi release that effected this area: v3.103.0. 

### Example

NA

### Output of `pulumi about`

NA

### Additional context

https://github.com/pulumi/pulumi/commit/09c36945ac785090d933f00d0e1d830dd6b08a03 changed the effected area, and the change corresponds to the new error. I believe that this introduced the regression.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
We also hit it here: https://github.com/pulumi/pulumi/actions/runs/7649064476/job/20843014365?pr=15248#step:38:2131

```
Error: node_modules/@pulumi/pulumi/automation/cmd.d.ts(1,25): error TS7016: Could not find a declaration file for module 'semver'. '/tmp/TestLanguage3489130828/002/sdks/simple-1.0.0/node_modules/semver/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/semver` if it exists or add a new declaration (.d.ts) file containing `declare module 'semver';`
    language_test.go:135: 
        	Error Trace:	/home/runner/work/pulumi/pulumi/sdk/nodejs/cmd/pulumi-language-nodejs/language_test.go:135
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = sdk packing for simple: npm run build: exit status 2
        	Test:       	TestLanguage/l2-resource-simple
```

This is similar to what happened with https://github.com/pulumi/pulumi/issues/14781 ☹️

**Comment by justinvp** [comment]
https://github.com/pulumi/pulumi/issues/15074 and/or https://github.com/pulumi/pulumi/issues/15075 would have helped catch this before release 😦
