### ISSUE TITLE
Preview does not list all created resources when behind an apply

### ISSUE THREAD

**Issue by megbetts** [pulumi/pulumi#15265]
### What happened?

I create a resource, and then call two functions to deploy additional resources. The functions accept outputs of the first resource as inputs and are called through a pulumi.Output.apply.

Running a preview shows only the first resource being created - it does not show the resources within the functions in the diff - even though the resources are deployed during runtime.

### Example

```
import pulumi
import pulumi_aws


def deploy_access_block(parent_name, rtprops):
    pulumi_aws.s3.BucketPublicAccessBlock("exampleBucketPublicAccessBlock",
                                          bucket=rtprops["bucket_id"],
                                          block_public_acls=True,
                                          block_public_policy=True,
                                          ignore_public_acls=True,
                                          restrict_public_buckets=True)


def deploy_bucket_policy(parent_name, rtprops):
    allow_access_from_another_account_policy_document = pulumi_aws.iam.get_policy_document_output(
        statements=[pulumi_aws.iam.GetPolicyDocumentStatementArgs(
            principals=[pulumi_aws.iam.GetPolicyDocumentStatementPrincipalArgs(
                type="AWS",
                identifiers=["123456789012"],
            )],
            actions=[
                "s3:GetObject",
                "s3:ListBucket",
            ],
            resources=[
                rtprops["bucket_arn"],
                f"{rtprops['bucket_arn']}/*",
            ],
        )])

    allow_access_from_another_account_bucket_policy = pulumi_aws.s3.BucketPolicy(
        "allowAccessFromAnotherAccountBucketPolicy",
        bucket=rtprops['bucket_id'],
        policy=allow_access_from_another_account_policy_document.json)


bucket = pulumi_aws.s3.Bucket(
    "name"
)

pulumi.Output.all(bucket_id=bucket.id).apply(
    lambda rtprops: deploy_access_block(
        "name", rtprops
    )
)

pulumi.Output.all(bucket_arn=bucket.arn, bucket_id=bucket.id).apply(
    lambda rtprops: deploy_bucket_policy(
        "name", rtprops
    )
)
```
Pulumi preview results in: 

<img width="663" alt="image" src="https://github.com/pulumi/pulumi/assets/64611291/4d5d0bbc-4807-4da7-8ece-4e427ce16fef">

pulumi up actually deploys all resources

<img width="843" alt="image" src="https://github.com/pulumi/pulumi/assets/64611291/c8632423-fdee-4560-b0d5-c1ed5d1327b9">

### Output of `pulumi about`

CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Host     
OS       darwin
Version  13.0
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
For example, something like this:

```python
import pulumi
import pulumi_aws

bucket = pulumi_aws.s3.Bucket(
    "name"
)

pulumi_aws.s3.BucketPublicAccessBlock("exampleBucketPublicAccessBlock",
                                          bucket=bucket.id,
                                          block_public_acls=True,
                                          block_public_policy=True,
                                          ignore_public_acls=True,
                                          restrict_public_buckets=True)

allow_access_from_another_account_policy_document = bucket.arn.apply(lambda arn: pulumi_aws.iam.get_policy_document(
    statements=[pulumi_aws.iam.GetPolicyDocumentStatementArgs(
        principals=[pulumi_aws.iam.GetPolicyDocumentStatementPrincipalArgs(
            type="AWS",
            identifiers=["123456789012"],
        )],
        actions=[
            "s3:GetObject",
            "s3:ListBucket",
        ],
        resources=[
            arn,
            f"{arn}/*",
        ],
    )]).json)

allow_access_from_another_account_bucket_policy = pulumi_aws.s3.BucketPolicy(
    "allowAccessFromAnotherAccountBucketPolicy",
    bucket=bucket.id,
    policy=allow_access_from_another_account_policy_document)

```

**Comment by megbetts** [comment]
Thanks @Frassle @justinvp ,

In this example yes, we can pass the outputs in directly but for more complex use cases it's getting pretty messy. We'd like to modularize the code to make it readable / maintainable as well as we sometimes depend on the output value to interpolate it into userdata scripts for example (we're using the Python SDK that doesn't support pulumi interpolate, so we've been using Jinja).
I'll track [Issue 4834](https://github.com/pulumi/pulumi/issues/4834),  is there any chance that will get prioritized anytime soon?

**Comment by justinvp** [comment]
> I'll track [Issue 4834](https://github.com/pulumi/pulumi/issues/4834), is there any chance that will get prioritized anytime soon?

We're not planning to do it this quarter. We may tackle it next quarter or the quarter after, but no firm plans yet.
