### ISSUE TITLE
error: an unhandled error occurred: Program exited with non-zero exit code: -1

### ISSUE THREAD

**Issue by piclemx** [pulumi/pulumi#15320]
### What happened?

When running any operation using the pulumi CLI, we hit sometime this error with no real information of what happens.

### Example

```
$ pulumi login s3://$BUCKEET
Logged in to test as node (s3://***)
$ pulumi stack select $PULUMI_STACK $PULUMI_OPTS --create
$ pulumi up --yes $PULUMI_OPTS $PULUMI_DEPLOY_OPTS
Updating (prod9):
    pulumi:pulumi:Stack test running 
@ updating....
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
    pulumi:pulumi:Stack test running error: an unhandled error occurred: Program exited with non-zero exit code: -1
    pulumi:pulumi:Stack test **failed** 1 error
Diagnostics:
  pulumi:pulumi:Stack (test):
    error: an unhandled error occurred: Program exited with non-zero exit code: -1
Resources:
    1 unchanged
Duration: 20s
```

### Output of `pulumi about`

```
$ echo "Using Pulumi $(pulumi version)"
warning: A new version of Pulumi is available. To upgrade from version '3.75.0' to '3.103.1', visit https://pulumi.com/docs/install/ for manual instructions and release notes.
Using Pulumi v3.75.0
```

### Additional context

It happens sometime with small stack but also with big stack. Most of the time we are seeing that behavior on biggest. Which concerns us is that this happens on a small stack that we never have before. 

It shouldn't happen on both but might be something.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
`Program exited with non-zero exit code: -1`

This is your Pulumi program exiting with an error code. Given no other output pretty hard to guess what's wrong. I'd suggest running with logging `-v10 --logtostderr --logflow` to see if that prints anything to help track it down, and look at adding diagnostic prints to your program itself.

**Comment by piclemx** [comment]
Since the issue is sporadic, adding that kind of level of logging will slow everything and make it hard I guess to follow.

There is no way pulumi can handle it better and put one if the root cause?

**Comment by Frassle** [comment]
> There is no way pulumi can handle it better and put one if the root cause?

Maybe, but again hard to tell until we know what's happening here. It could be your system is running out of memory and the process is just getting OOM killed. The pulumi process doesn't get a signal for that, the program just exits. It might be you've got a crash in your program startup before you've even started running any pulumi specific code. Again that looks the same. Could be a crash in the pulumi SDK itself, again that could look the same.

Although the last one is probably not the case here. Generally when we crash we call panic/throw and that prints a load of crash information to stderr and pulumi does capture stdout and stderr from the program to print them out.

It's pretty odd that nothing printed here, I'll go sanity check there isn't anything about running in non-interactive mode that stops program stderr printing.

**Comment by Frassle** [comment]
> It's pretty odd that nothing printed here, I'll go sanity check there isn't anything about running in non-interactive mode that stops program stderr printing.

Quick check it looks like stderr should always be printing.

**Comment by piclemx** [comment]
I will be adding the logging part as you recommend. See if we can find something.

**Comment by madappa-sharath** [comment]
I'm experiencing the same issue on our CI servers which use 'pulumi/pulumi-nodejs:3.103.1'. I enabled logging and see nothing conspicuous.

The preview completes and it posts to complete api and exists with non-zero code. For me this happens every single time.

```
I0131 17:48:57.258206     203 log.go:81] Pulumi API call response code (https://api.pulumi.com/api/stacks/myorg/my-project/my-stack/update/fa86013c-fe70-413d-8944-1c7cc70d822a/events/batch): 200 OK
I0131 17:48:57.258963     203 log.go:81] Making Pulumi API call: https://api.pulumi.com/api/stacks/myorg/my-project/my-stack/update/fa86013c-fe70-413d-8944-1c7cc70d822a/events/batch
I0131 17:48:57.317461     203 log.go:81] Pulumi API call response code (https://api.pulumi.com/api/stacks/myorg/my-project/my-stack/update/fa86013c-fe70-413d-8944-1c7cc70d822a/events/batch): 200 OK
I0131 17:48:57.317915     203 log.go:81] Making Pulumi API call: https://api.pulumi.com/api/stacks/myorg/my-project/my-stack/update/fa86013c-fe70-413d-8944-1c7cc70d822a/events/batch
I0131 17:48:57.354787     203 log.go:81] Pulumi API call response code (https://api.pulumi.com/api/stacks/myorg/my-project/my-stack/update/fa86013c-fe70-413d-8944-1c7cc70d822a/events/batch): 200 OK
I0131 17:48:57.413721     203 log.go:81] Pulumi API call response code (https://api.pulumi.com/api/stacks/myorg/my-project/my-stack/update/fa86013c-fe70-413d-8944-1c7cc70d822a/events/batch): 200 OK
I0131 17:48:57.532245     203 log.go:81] Pulumi API call response code (https://api.pulumi.com/api/stacks/myorg/my-project/my-stack/update/fa86013c-fe70-413d-8944-1c7cc70d822a/events/batch): 200 OK
I0131 17:48:57.532467     203 log.go:81] Making Pulumi API call: https://api.pulumi.com/api/stacks/myorg/my-project/my-stack/update/fa86013c-fe70-413d-8944-1c7cc70d822a/complete
I0131 17:48:57.680957     203 log.go:81] Pulumi API call response code (https://api.pulumi.com/api/stacks/myorg/my-project/my-stack/update/fa86013c-fe70-413d-8944-1c7cc70d822a/complete): 204 No Content
make: *** [../../common.mk:85: preview] Error 255
```

**Comment by madappa-sharath** [comment]
^ Looking at the whole log file, found this bit

```
I0131 17:48:57.226729     203 log.go:81] eventSink::Infoerr(<{%reset%}>I0131 17:48:57.226668     216 log.go:81] Explicitly ignoring and discarding error: sync /dev/stdout: invalid argument
<{%reset%}>)
I0131 17:48:57.226754     203 log.go:81] eventSink::Infoerr(<{%reset%}>I0131 17:48:57.226712     216 log.go:81] Explicitly ignoring and discarding error: sync /dev/stderr: invalid argument
<{%reset%}>)
    pulumi:pulumi:Stack my-project-my-stack running I0131 17:48:57.226668     216 log.go:81] Explicitly ignoring and discarding error: sync /dev/stdout: invalid argument
    pulumi:pulumi:Stack my-project-my-stack running I0131 17:48:57.226712     216 log.go:81] Explicitly ignoring and discarding error: sync /dev/stderr: invalid argument
I0131 17:48:57.227190     203 log.go:81] langhost[nodejs].Run(pwd=/drone/src/client/ingress,program=.,...,dryrun=true) success: progerr=Program exited with non-zero exit code: -1, bail=false
I0131 17:48:57.227246     203 log.go:81] EvalSourceIterator ended with an error: an unhandled error occurred: Program exited with non-zero exit code: -1
I0131 17:48:57.227270     203 log.go:81] deploymentExecutor.Execute(...): incoming event (nil? true, an unhandled error occurred: Program exited with non-zero exit code: -1)
I0131 17:48:57.227286     203 log.go:81] eventSink::Error(<{%reset%}>an unhandled error occurred: Program exited with non-zero exit code: -1<{%reset%}>)
    pulumi:pulumi:Stack my-project-my-stack running error: an unhandled error occurred: Program exited with non-zero exit code: -1
I0131 17:48:57.227312     203 log.go:81] StepExecutor worker(-1): StepExecutor.waitForCompletion(): waiting for worker threads to exit
```

**Comment by justinvp** [comment]
@piclemx, is your Pulumi program also using Node.js?

**Comment by piclemx** [comment]
> @piclemx, is your Pulumi program also using Node.js?

Yes.

**Comment by madappa-sharath** [comment]
My issue went away. Was due to memory limits being set on the pod running pulumi preview. I removed the memory limits and now previews run successfully. The pod wasn't getting OOMKilled, but somehow pulumi was exiting midway.
