### ISSUE TITLE
"pulumi update" still prompts to continue if preview shows no changes

### ISSUE THREAD

**Issue by mmdriley** [pulumi/pulumi#1532]
Is it safe just to continue in this case?

**Comment by pgavlin** [comment]
If the empty update is unexpected, we may still want to give the user the opportunity to intervene. The only thing that this should affect at the moment is the stack's history, but I can imagine this changing over time (e.g. with hooks on updates).

**Comment by CyrusNajmabadi** [comment]
> Is it safe just to continue in this case?

Is continuing even sensible?  Would it make more sense to just automatically stop instead?   Or, in other words, if continuing *could* have an effect, then showing the user "no changes" seems bad as it implies something very untrue.

**Comment by lukehoban** [comment]
I'm not 100% sure we want to change this.

The preview might show nothing in the following cases, both of which I may still really want to proceed with the update.  Both are maybe "bugs" themselves, but we may want to make sure we've addressed all of that class of issue before we change this.
1. Updates to only stack outputs (pretty common)
2. Pending deletes that don't show in preview (https://github.com/pulumi/pulumi/issues/1596)

/cc @ellismg @pgavlin

**Comment by CyrusNajmabadi** [comment]
Ok.  I'm not changing the front end here until we have a decision on what the right experience should be.

**Comment by lukehoban** [comment]
Closing this out - as I don't think we want to make any change here right now.
