### ISSUE TITLE
API endpoint stops returning stacks after reaching ~500 total

### ISSUE THREAD

**Issue by caboog** [pulumi/pulumi#15332]
### What happened?

Running a curl on `https://api.pulumi.com/api/user/stacks?organization` when an org has a high number of stacks only returns 500. Is this a pagination issue that can be easily resolved to list the full count maybe?

### Example

#!/bin/sh

# REPLACE THESE WITH YOUR VALUES
PULUMI_ACCESS_TOKEN=pul-123
ORG=acme-corp

# Get all stacks
curl \
  -H "Accept: application/vnd.pulumi+8" \
  -H "Content-Type: application/json" \
  -H "Authorization: token ${PULUMI_ACCESS_TOKEN}" \
  "https://api.pulumi.com/api/user/stacks?organization=${ORG}" > GET_stacks.json
cat GET_stacks.json |  jq '.stacks[] | .projectName+"/"+.stackName' -r > stack_names.txt

### Output of `pulumi about`

git:(main) ✗ pulumi about
CLI
Version      3.102.0
Go Version   go1.21.5
Go Compiler  gc

### Additional context

The org reporting this initially has ~8,000 stacks currently.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
Per https://www.pulumi.com/docs/pulumi-cloud/cloud-rest-api/#list-stacks, there is a `continuationToken` "for retrieving the next set of results if results were truncated".  This can be used to page through the results.
