### ISSUE TITLE
Make perf baselines a checkin gate

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#15347]
Today we have offline reports of perf tests. For example, from our #cli-performance-alerts channel:

![image](https://github.com/pulumi/pulumi/assets/3953235/9cdb8184-28b5-4d84-b31f-77e4cbd7fa5a)

Unfortunately, the way this is done
* Is not super visible (only 10 people in that channel)
* Fails to block checkins that would regress beyond our baselines
* Is run in an offline mode meaning correlating failures back to the changes that caused them is very difficult
* In practice, means, it has been an ineffective means of blocking or even getting us to fix perf regressions

Instead of that, we should run the most important tests as checkin gates -- or worst case, actual tests with failure modes on a semi-regular basis, in this repo. Ideally we'd just check in the baselines so they are easy to change and visible to all.

**Comment by justinvp** [comment]
I definitely want such tests in this repo.

Would it also make sense in the provider repos? The last two rounds of `#cli-performance-alerts` were perf regressions in the AWS provider (current one: https://github.com/pulumi/pulumi-aws/issues/3330).

**Comment by joeduffy** [comment]
Agree -- my philosophy is "run them as close to the potential root cause as possible."

**Comment by VenelinMartinov** [comment]
Would we need a way to mock out API calls to make this reliable? We get quite a bit of variance in the current performance tests, so I suspect it'd be very noisy to gate PRs/releases on performance tests.

**Comment by Frassle** [comment]
> Would we need a way to mock out API calls to make this reliable?

Yeh feels like we should be able to make an "artificial" benchmark for the engine at least to check that performance doesn't degrade but with stable Create/Update/Delete times. 

I think this might actually go really well with @PollRobots's work to look at performance and making the engine parallel. If we ran some programs that sent a large number of RegisterResource calls, some in parallel some in serial, that created "fake" resources but with differing (but stable over re-runs) times for their Check/Diff/Create/etc methods that could serve as both a correctness and performance benchmark for the engine itself.

**Comment by VenelinMartinov** [comment]
https://github.com/pulumi/pulumi-aws/issues/3380 I opened an issue in the AWS repo for this since we probably want to start with that - It's our most used provider and it has been a source of performance regressions.
