### ISSUE TITLE
Make cloud provider account number/alias more prominent

### ISSUE THREAD

**Issue by digitalsanctum** [pulumi/pulumi#1534]
I routinely use multiple accounts (AWS) and so far in my limited use of pulumi I'm not seeing any indication of which account each stack belongs to. It would be great to have an indication of which stacks belong to which account. Even better would be the capability to alias accounts. For example AWS account 123 in us-east-1 could have an alias of "personal-aws-us-east-1".

**Comment by lukehoban** [comment]
Closing this out to track in #1181.
