### ISSUE TITLE
`Output.all` aggregates inputs instead of outputs - Python SDK.

### ISSUE THREAD

**Issue by lrnq** [pulumi/pulumi#15353]
### What happened?

I would like to combine multiple outputs and would like to perform an apply over all of them in order to create a new output. From [the docs](https://www.pulumi.com/docs/concepts/inputs-outputs/#all) it seems that this is exactly the use-case for `Output.all`:

> If you have multiple outputs and need to use them together, the all function acts like an apply over many resources, allowing you to use multiple outputs when creating a new output.

Looking at the doc-string for the `all` method in the Python SDK it seems that it aggregates inputs instead of outputs:

https://github.com/pulumi/pulumi/blob/bdebae8bb355c6412ba6d3533c77657392bec47c/sdk/python/lib/pulumi/output.py#L430-L432

The type-hints suggest the same:

https://github.com/pulumi/pulumi/blob/bdebae8bb355c6412ba6d3533c77657392bec47c/sdk/python/lib/pulumi/output.py#L415-L425

### Example

The implementation seems to work as intended, but i'll provide a dummy example anyways using `Output.all`. The issue is more so if you use a type-checker that picks up on this. 

```python
import pulumi
from pulumi_gcp import storage

bucket = storage.Bucket("my-bucket", location="US")
output_str = pulumi.Output.all(url=bucket.url, name=bucket.name).apply(
    lambda args: f"The URL is {args['url']} and the name is {args['name']}"
)
```

### Output of `pulumi about`

```
CLI          
Version      3.104.2
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.54.0
python  unknown
utils   0.1.0

Host     
OS       darwin
Version  14.3
Arch     arm64

This project is written in python: executable='/Users/x/.pyenv/shims/python3' version='3.10.13'

Backend        
Name           macbook-air.lan
URL            file://~
User           x
Organizations  
Token type     personal
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Outputs are Inputs:
```
Input = Union[T, Awaitable[T], "Output[T]"]
```

**Comment by lrnq** [comment]
> Outputs are Inputs:
> 
> ```
> Input = Union[T, Awaitable[T], "Output[T]"]
> ```

Ah... Thank you @Frassle.
