### ISSUE TITLE
`pulumi package gen-sdk ...` is missing a `setup.py` file

### ISSUE THREAD

**Issue by amywhying** [pulumi/pulumi#15358]
### What happened?

1. Ran `pulumi package gen-sdk ${SRC}/${PACKAGE}/schema.json --language python`
2. The sdk folder built does not have `setup.py`

- Running on v3.102.0
- Tried doing this on an older version of v3.78.0 and it worked. 

### Example

1. Run `pulumi package gen-sdk ${SRC}/${PACKAGE}/schema.json --language python`
2. Look into the sdk folder to find `setup.py`

### Output of `pulumi about`

```
CLI          
Version      3.102.0
Go Version   go1.21.5
Go Compiler  gc

Host     
OS       darwin
Version  12.6.3
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
You haven't set the schema option to emit a "pyproject.toml" instead of a "setup.py" file have you?

I'm assuming the rest of the sdk files wrote out to the sdk folder? It's just the "setup.py" that's missing?

**Comment by amywhying** [comment]
I do not recall directly setting the schema option to emit a `pyproject.toml`, but I do have that file instead of `setup.py` after running the command I listed above. 

And yes the rest of the sdk files are in the sdk folder, but only the "setup.py" is missing. 

How is the schema option set and how can I change it?

**Comment by Frassle** [comment]
Threre's a "languages" key at the top of the schema, and in there you can set "python" options one of which is setting pyproject:
```
"langauges": {
  "python": {
    "pyproject": {
      "enabled": true/false
    }
  }
}
```
Set that to false for "setup.py", true for "pyproject.toml".

I can't see anything that would automatically set that to true though, so I'm a bit confused at how this broke for you.

**Comment by amywhying** [comment]
Gotcha, after contacting the project owner and double checking on the file, it was confirmed that there was an update recently to the schema yaml to emit a `pyproject.toml`, which caused this issue. 

Thank you for helping me out on this!

**Comment by Frassle** [comment]
> Thank you for helping me out on this!

No worries, thanks for getting back to us to confirm what happened.
