### ISSUE TITLE
v3.104.2 Local backend - copying lockfile to mounted device failure

### ISSUE THREAD

**Issue by mattfysh** [pulumi/pulumi#15352]
### What happened?

Trying to run a deploy using a local file backend and I received this error, because my `/data` volume is mounted

```
error: blob (key ".pulumi/locks/organization/project/stack/50ca3ab5-242f-412a-9cfc-9abf9d5d11d9.json") (code=Unknown): rename /tmp/50ca3ab5-242f-412a-9cfc-9abf9d5d11d9.json.17aff9636f6f6f63.tmp /data/.pulumi/locks/organization/project/stack/50ca3ab5-242f-412a-9cfc-9abf9d5d11d9.json: invalid cross-device link
```

### Example

pulumi up

### Output of `pulumi about`

**this is the output after downgrading**

CLI          
Version      3.103.0
Go Version   go1.21.5
Go Compiler  gc

Host     
OS       debian
Version  12.4
Arch     aarch64

Backend        
Name           sahara-ed94f00d-86876d5969-mfhkh
URL            file:///data
User           root
Organizations  
Token type     personal

### Additional context

Downgrading to v3.103.0 fixed the issue

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Looks like gocloud changed their behaviour here a while ago and we've only just picked up this change. 
There's a thread about it at https://github.com/google/go-cloud/issues/3314. Looks like the suggested workaround is to add "?no_tmp_dir" to the url to revert back to the old behaviour.

**Comment by Frassle** [comment]
go-cloud team seem convinced that this is a good breaking change and the old behaviour should be explicitly opt'ed into. We could just align with that.

If it's felt that the go-cloud team are wrong on this count we have a couple of options:
1. Just unconditionally add "?no_tmp_dir" to file urls to always opt in to the old behaviour.
2. Add "?no_tmp_dir" by default but have a flag to tell pulumi to not set that.
3. Go see if go-cloud can be changed to not require a filesystem atomic rename for the temp file and instead just do a copy move for cross device links.

Number three could take some significant time so we'd possibly want to do 1 or 2 beforehand as well, possibly reverting them once go-cloud doesn't error on cross device moves by default.

**Comment by tgummerer** [comment]
> Just unconditionally add "?no_tmp_dir" to file urls to always opt in to the old behaviour.

Imo we should do this for now, as this is what the user expects from pulumi, even if the new gocloud.dev behaviour is "more correct" or nicer for users that don't have a mounted device where this breaks.  

I think for the other options, 3) would be nice to implement eventually, but it doesn't feel urgent.

**Comment by nathanchere** [comment]
I get this on a fresh install of pulumi CLI and running `login --local` for the first time.  I would create a new issue but I see a similar one was closed as duplicate of this... though it seems like the scenario described here isn't directly relevant?

**Comment by nathanchere** [comment]
```error: problem logging in: write ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): rename /tmp/meta.yaml..17b19af5dcaac52a.tmp /home/newuser/.pulumi/meta.yaml: invalid cross-device link
```
to be specific

**Comment by nathanchere** [comment]
`pulumi login file:///home/newuser?no_tmp_dir=true` works for now, thanks
