### ISSUE TITLE
Pulumi from package managers

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1536]
Today we have https://get.pulumi.com/install.sh and https://get.pulumi.com/install.ps1 as well as links on https://pulumi.io/install/ to download Pulumi.

It would be ideal if we had support for installing Pulumi via common package managers.  For example, it would be ideal if we had support for the following:

- [x] Homebrew 
- [x] Chocolatey 
- [x] Scoop
- [ ] RPM/DEB packages

For all of these, it's probably simplest to start with our own repositories (e.g. a custom brew tap, seperate nuget feed Chocolatey, APT/RPM sources on get.pulumi.com you can add to your package manager) and then try to work with upstream distros to get it.

For DEB/RPM using something like `fpm` is likely going to be to start with, so we save ourselves from maintaining control and spec files.

Arch is probably also interesting, but I know less about about that packaging technology.  If there are any Arch fans here, please speak up and let us know what works best.

**Comment by loic-sharma** [comment]
I would also recommend adding support for scoop for windows: https://github.com/lukesampson/scoop :)

**Comment by briandrennan** [comment]
@ellismg how does this differ from getting Pulumi SDK in terms of desired experience? Does it supplant the install experience, or is it just an additional install scenario? I'm not sure how much you've followed the [WiX Toolset](https://github.com/wixtoolset) (I assume some exposure with .NET), but install via NuGet is a highly requested feature. On my CI server, I definitely prefer to install dependencies via a package manager. I can also see Pulumi easing the integration test process (provisioning cloud resources, perhaps with crafted data sets, to support integration tests) in the CI pipeline.

**Comment by briandrennan** [comment]
@ellismg my apologies, I wasn't trying to suggest an MSI install. I was suggesting that download via the CI toolchain is a highly requested feature by many WiX Toolset users. I was essentially suggesting that package manager-based install is a highly valued feature in that project, and assume it would be highly valued for Pulumi as well.

**Comment by joeduffy** [comment]
I would like to see us tackle this during M16, since it directly influences (and hopefully significantly improves) the onboarding experience.

**Comment by lukehoban** [comment]
We have decided to prioritize https://github.com/pulumi/pulumi/issues/1686 for now, and to revisit this in again in a couple months.

**Comment by Tirke** [comment]
I went ahead and created a [PR on homebrew-core](https://github.com/Homebrew/homebrew-core/pull/30711) to allow `brew install pulumi`

**Comment by Tirke** [comment]
I believe you can check Homebrew @ellismg 🎉

**Comment by zachgatesak** [comment]
Bumping this for Chocolatey.

**Comment by ljani** [comment]
How about distributing the binaries via `npm` as well? Personally I'd like to run the following commands:

```
git clone https://github.com/ljani/my-pulumi-configs
cd my-pulumi-configs
npm install
npm run my-up-task
# or eg. npm start
```

The `npm install` would install the correct platform binaries (or if that's not possible, then `run` or `postinstall` would download the binaries lazily) to eg. `node_modules/@pulumi/binaries` and create `node_modules/.bin/pulumi` and `node_modules/.bin/pulumi.cmd`, which are callable from `package.json`'s `scripts` section.

This would work very well for not CI servers, but also for teams, because I can assume everyone has and is familiar with `npm`, IDEs support running `npm` scripts, etc.

**Comment by JustinGrote** [comment]
I have submitted a pull request for Pulumi to be included in scoop master bucket.
https://github.com/ScoopInstaller/Main/pull/562

In the meantime you can install with this command:
https://raw.githubusercontent.com/JustinGrote/Main/master/bucket/pulumi.json

FYI @loic-sharma

**Comment by JustinGrote** [comment]
You can check off scoop! I it was merged and approved and it works on my machine with scoop install pulumi.

**Comment by lukehoban** [comment]
Going to close out this meta-issue, as we do now have much of this support.  As new package managers become common needed/desired we can open individual work items to track.
