### ISSUE TITLE
Cloudflare workers

### ISSUE THREAD

**Issue by newtack** [pulumi/pulumi#1538]
Rather than AWS APIG I'd want to use Cloudflare workers for my API entry point, cost being one of the considerations (7x less expensive).

I am sure this is not a common case yet, so I don't expect you to implement this now, but can you point me to how I could do it myself?

**Comment by lukehoban** [comment]
There's probably a few pieces that would be needed.

First - a Pulumi resource provider for managing Cloudflare resources.  That's something we're definitely interested in bringing up.  It could be done either on top of https://github.com/terraform-providers/terraform-provider-cloudflare using https://github.com/pulumi/pulumi-terraform, or as a native Pulumi resource provider (similar to https://github.com/pulumi/pulumi-kubernetes).   This is something we'd love to help with if anyone is interested in partnering on building it up.

That would give you the ability to manage raw resources (including Workers) in Cloudflare.  Next, you would want to create a library to allow you to use a higher-level programming model for connecting Cloudflare workers to API endpoints.  For that, you could take inspiration from https://github.com/pulumi/pulumi-aws-serverless and create a `cloudflare-serverless` package.

These are on our longer term roadmap, but we're also open to helping out if others are interested in making progress on either/both in the near term.

**Comment by ellismg** [comment]
Do note that according to https://github.com/terraform-providers/terraform-provider-cloudflare/issues/50, it looks like the terraform provider does not yet support Cloudflare Workers.  So if you do want to take the tfgen approach (which may be helpful if there’s lots of other Cloudflare things you want) you may first need to add that feature to the provider.

According to the issue it is on their roadmap so you might be able to contribute to the provide and help move the whole ecosystem forward!

**Comment by patryk** [comment]
Hello everyone, just FYI, Terraform provider supports Cloudflare Workers now.

**Comment by casey-robertson** [comment]
Upvote for Cloudflare from tfgen

**Comment by lukehoban** [comment]
The core of this - a CloudFlare provider for Pulumi - is being actively worked on - so moving into the current milestone.

**Comment by jen20** [comment]
The Cloudflare provider should land shortly, and I'll add an example for workers in the next milestone.

**Comment by lukehoban** [comment]
CloudFlare provider is available now, and a Workers example is at https://github.com/pulumi/pulumi-cloudflare/tree/master/examples/worker.

**Comment by MarcoPolo** [comment]
Hi @lukehoban. That link is dead. It looks like the cloudflare worker was changed to another example. Any chance of seeing some updated docs? 

Thanks!

**Comment by kay-is** [comment]
@lukehoban Where are the examples now?

**Comment by zvictor** [comment]
Just check the git history, find the commit roughly at the time he posted, and find the file there: https://github.com/pulumi/pulumi-cloudflare/blob/0da7351608d1a155494ee9c3f42d2f3002b83467/examples/worker/index.ts
