### ISSUE TITLE
Snapshot integrity failure when resource node name with dependency changes outside of --target 

### ISSUE THREAD

**Issue by zweihan** [pulumi/pulumi#15382]
### What happened?

We are using Pulumi to apply changes during deployment. As deployment of services are independent, therefore, we use the flag `--target` to select only resources related to a particular service.

We noticed that if there are resource pulumi node name changes that are not within `--target`, it would result in the following error:
```
error: post-step event returned an error: failed to save snapshot: .pulumi/stacks/dev.json: snapshot integrity failure; it was already written, but is invalid (backup available at .pulumi/stacks/dev.json.bak): resource <RESOURCE_URN_CHILD> dependency <RESOURCE_URN_PARENT> refers to missing resource.
```
This happens when a parent resource's pulumi name changed but is outside the `--target`.

### Example

Supposed we start off with the following set of resources with `pulumi up` already applied and created:
```typescript
const testTopic1 = new gcp.pubsub.Topic("test-topic1", {});

const testTopic2 = new gcp.pubsub.Topic("test-topic2", {});

const testTopic3 = new gcp.pubsub.Topic("test-topic3", {}, { dependsOn: [testTopic1] });
```

There are 3 resources, with `test-topic3` being dependent on `test-topic1`.

Supposed we make the following changes:

1) Change `test-topic1` -> `test-topic1-changed`
```typescript
const testTopic1 = new gcp.pubsub.Topic("test-topic1-changed", {});

```

2) Add a label to `test-topic2`
```typescript
const testTopic2 = new gcp.pubsub.Topic("test-topic2", {
  labels: {
    "env": "dev"
  }
});
```

If we now run `pulumi up`, targeting just `test-topic2`:
```typescript
pulumi up --target <URN_OF_test-topic2>
```
Pulumi would throw the error pasted above. 

### Output of `pulumi about`

```
CLI          
Version      3.103.1
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
gcp     6.60.0
nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/weihan/.nvm/versions/node/v18.12.1/bin/node' version='v18.12.1'

Backend        
Name           weihan-g14
URL            gs://arbo-pulumi-backend
User           weihan
Organizations  
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/gcp     6.60.0
@pulumi/pulumi  3.76.0
@types/node     16.18.38
```

### Additional context

It seems like Pulumi changed the pulumi node name of the dependency of resources outside `--target` causing the state integrity failure.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening the issue with the repro steps, @zweihan. We'll take a look.
