### ISSUE TITLE
Add regression tests with hardcoded keys for AWS and GCP

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#15414]
We should add similar tests as we did for Azure in https://github.com/pulumi/pulumi/pull/15187 for AWS and GCP, to endure new versions are always compatible with the encryption keys we've already written.  These keys need to keep functioning, as users will have similar keys as data on disk.

/xref https://github.com/pulumi/home/issues/3297

**Comment by justinvp** [comment]
We should definitely do this before the next gocloud.dev update.
