### ISSUE TITLE
pulum import into a component throws code gen error: `anonymous.pp:11,10-16: undefined variable parent;`

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#15410]
### What happened?

- Launch a stack that creates resource(s) in a component resource.
- Run `pulumi import ...` with the `--parent` parameter to import the resource into the component resource.

The resource is imported into state and placed under the component resource.

However, codegen fails with the error: `error: anonymous.pp:11,10-16: undefined variable parent; `

### Example

- Using the code below, run `pulumi up`. This will create a stack with a component resource with a bucket inside of it.
- Create another bucket. Using `pulumi new aws-typescript` is an easy way to do this.
- Look at the first stack and get the name and URN for the the `custom:x:S3Bucket` component resource. The name should be `my-bucket` and the URN should be something like `urn:pulumi:dev::typescript::custom:x:S3Bucket::my-bucket`
- Run `pulumi import aws:s3/bucket:Bucket importedbucket OTHERBUCKETID --parent my-bucket=urn:pulumi:dev::typescript::custom:x:S3Bucket::my-bucket`
- You will see the bucket is imported under the component resource, but the codegen fails with the above error.

**NOTE**: Although the pulumi import help page indicates the parent syntax is NAME=URN, you can also just use URN and get the same results: Resource is imported under the component but codegen fails.

Code:
index.ts:
```
import * as s3bucket from "./s3bucket"

// Create an AWS resource (S3 Bucket)
const bucket = new s3bucket.S3Bucket("my-bucket", {});

// Export the name of the bucket
export const bucketName = bucket.bucketId
```

s3bucket.ts:
```
import * as pulumi from "@pulumi/pulumi";
import { Input, Output } from "@pulumi/pulumi"
import * as aws from "@pulumi/aws"

interface S3BucketArgs {
  acl?: Input<string>;
};

export class S3Bucket extends pulumi.ComponentResource {
    public readonly bucketId: Output<string>;
    public readonly bucket: aws.s3.Bucket;

    constructor(name: string, args: S3BucketArgs, opts?: pulumi.ComponentResourceOptions) {
      super("custom:x:S3Bucket", name, args, opts);
        this.bucket = new aws.s3.Bucket(`${name}-comp`, {
          acl: args.acl
        }, {parent: this})

        this.bucketId = this.bucket.id
    }
  }
```

### Output of `pulumi about`

CLI          
Version      3.104.2
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.6.3
Arch     x86_64

This project is written in nodejs:  version='v18.18.2'

Current Stack: dev

TYPE                  URN
pulumi:pulumi:Stack   urn:pulumi:dev::typescript::pulumi:pulumi:Stack::typescript-dev
custom:x:S3Bucket     urn:pulumi:dev::typescript::custom:x:S3Bucket::my-bucket
pulumi:providers:aws  urn:pulumi:dev::typescript::pulumi:providers:aws::default_6_13_0
aws:s3/bucket:Bucket  urn:pulumi:dev::typescript::custom:x:S3Bucket$aws:s3/bucket:Bucket::my-bucket-comp
aws:s3/bucket:Bucket  urn:pulumi:dev::typescript::custom:x:S3Bucket$aws:s3/bucket:Bucket::impcr1
aws:s3/bucket:Bucket  urn:pulumi:dev::typescript::custom:x:S3Bucket$aws:s3/bucket:Bucket::impcr2
aws:s3/bucket:Bucket  urn:pulumi:dev::typescript::custom:x:S3Bucket$aws:s3/bucket:Bucket::impcr3

Found no pending operations associated with dev

Backend        
Name           pulumi.com

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by chrrlesWork** [comment]
Hitting this issue also.

**Comment by bra-fsn** [comment]
Seems to be the same or related: https://github.com/pulumi/pulumi/issues/13339

**Comment by roblframpton** [comment]
I also have this problem.  At first, I missed the "name=urn" syntax for the `--parent` parameter.  But now my import looks like this:

```
pulumi import 'aws:rds/cluster:Cluster' $RESOURCE_NAME $RDS_IDENTIFIER --parent 'database=urn:[blah]:PostgresDatabase::database'
```

And I get the message: `error: anonymous.pp:33,10-18: undefined variable database;`

**Comment by gunzy83** [comment]
In my case, this was preventing a script I was using for multiple imports from continuing to the next step. Adding `--generate-code=false` to the commands is a workaround as I really didn't need the code generation.
