### ISSUE TITLE
sys.stderr.write does not show in Pulumi diagnostics

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1542]
I'm not sure why this is, but `sys.stderr.write` does not show up as a diagnostic in the Pulumi CLI output, but print(..., file=sys.stderr) does.

**Comment by swgillespie** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/2111. The problem was that we needed to explicitly flush stderr before exiting.

**Comment by swgillespie** [comment]
This is still an issue with the 0.16.4 SDK:

```
▶ p pre
Previewing update (pyexamples-dev):

     Type                 Name                       Plan     Info
     pulumi:pulumi:Stack  pyexamples-pyexamples-dev           1 error

Diagnostics:
  pulumi:pulumi:Stack (pyexamples-pyexamples-dev):
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

Permalink: https://app.pulumi.com/swgillespie/pyexamples-dev/previews/e4542332-0ee8-4744-ad19-aacb2e989a6a
error: an error occurred while advancing the preview
```

**Comment by lukehoban** [comment]
@swgillespie Is there anything users can do as a workaround to get additional diagnostics when this happens?

**Comment by swgillespie** [comment]
> Is there anything users can do as a workaround to get additional diagnostics when this happens?

None that I know of, which is a huge pain. We run into this problem whenever we get errors early in startup.

For users reading this, the most common way that you get into this state is that the `pulumi` package isn't installed in your environment. If you open a `python3` shell and run

```
> import pulumi
```

and it fails, that is likely the identical failure that Pulumi is experiencing.
