### ISSUE TITLE
`pulumi new`: When a private template repository is used with credentials those credentials are saved in the project file in clear text

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#15431]
The changes from #15056 causes a significant security leakage when the template used has credentials injected in order to access a private template repository.

This is a documented and suggested approach to accessing private repositories: https://www.pulumi.com/docs/cli/commands/pulumi_new/

```
pulumi new https://DONOTSHOW:WHYISTHISHAPPENING@gitlab.com/hide/me.git --description "use private template" --generate-only --name "based-on-private-template"
```

Pulumi.yaml:
```
name: based-on-private-template
...
description: use private template
config:
  pulumi:tags:
    value:
      pulumi:template: https://DONOTSHOW:WHYISTHISHAPPENING@gitlab.com/hide/me.git
```

We should not save any custom template URL in the project, only templates from the default templates repo or Pulumi AI.

h/t @porterchris

**Comment by AaronFriel** [comment]
I think we should include other template sources as well, as it's helpful in code search & other tools to identify the source. We may just want to remove basic auth and perhaps query strings as well.

**Comment by justinvp** [comment]
Private repos and local file paths may be considered sensitive.
