### ISSUE TITLE
Should be possible to display intermediate states in complex `update`

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#1545]
In providers like Kubernetes, `update`'ing a single resource may actually involve several discrete steps, each of which may fail. In situations where these steps are well-known (_e.g._, deploying a Kubernetes `Service` object), it is possible to greatly simplify the debugging process simply by explaining in which intermediate step the provisioning process failed.

For Pulumi, there are several possibilities for where this information might be exposed:

* In the CLI, it should be possible to display progress on intermediate updates (_e.g._, "x of y containers running in pod", "container failed with status x", "Pod replicated x out of y times", and so on). In the case of Kubernetes, this information is mostly exposed in the API, and it is therefore a matter of plumbing that information in, so that it's rendered correctly in the CLI.
* The engine could stream these intermediate updates to the Pulumi service, thereby allowing it to be rendered in the Pulumi console. Hence, if `pulumi` is run as part of a CI system, it would be possible to recover this information for diagnostic purposes simply by visiting the console.

**Comment by CyrusNajmabadi** [comment]
Indeed.  Technically, we already have support for this through teh UI stack.  Specifically that you can stream messages associated with a resource, and the console will display them.  Now, that said, we might want to improve things here to not just be a dumb stream of info-messages, but instead be a more 'progress' oriented data type that could then be presented in a better fashion (i.e. with a progress-bar, or 'x of y complete' type view).

**Comment by joeduffy** [comment]
If a resource provider logs something, it will auto-magically get parented to the right output stream, right?  If yes, then we could -- as a first cut at this, and as Cyrus suggests -- simply have the Kubernetes provider emit messages of the form `Step N/M: awaiting service creation`, etc, etc.

**Comment by hausdorff** [comment]
Concretely, on the kube provider end, we'd need:

- [ ] To change `Service`, `Deployment`, `Pod`, and `StatefulSet` to be "more aware" of intermediate steps. Most of this information is already in the API, so it's "just" a matter of getting it to the right place.
- [ ] Find a way to get this back to the user, either with log messages or through the UI.

I'm fine writing to log to start, but before we start demoing to people, I would personally like to see something like more like this:

<img width="393" alt="screen shot 2018-06-20 at 3 45 55 pm" src="https://user-images.githubusercontent.com/1409156/41689234-88380852-74a4-11e8-92bb-4e4fef4a6cbc.png">

And then on failure, something like this:

<img width="687" alt="screen shot 2018-06-20 at 2 59 49 pm" src="https://user-images.githubusercontent.com/1409156/41689248-9ce753a2-74a4-11e8-9694-d4a36893c56c.png">

A lot of the information we'd need here is already in the API so this should be pretty doable.

**Comment by CyrusNajmabadi** [comment]
Very cool idea.  Technically, i shoudl totally be possible.  With a resource, we could have a set of 'steps' being performed.  As long as we were notified about these, we could then render this in the CLI in such a manner.

My primary concern would simply be this:  such an approach greatly 'bloats' the amount of space needed for a resource.  Any resource with steps would gets kX bigger.  From a UX perspective, this means any sort of meaty change will now likely be N times longer, and may be harder to grok.  It also may more easily make the output scroll off the top of the screen.  This is problematic in itself because the user cannot see what is going on, and we can only update what is in view.  Technically this problem already exists today.  But the severity of it is mitigated due to us not using only a line-per-resource.

One consideration would be to store hte data, present it succinctly (i.e. "2 or 3 subtasks completed"), and then only show the richer data if there is a failure.  In other words, keep the golden path clean.  But make the failure path much richer.

Thoughts @hausdorff ?

**Comment by hausdorff** [comment]
Just so we all have the same information as we make the decision: only 4-5 resource types in k8s have intermediate steps at all, so the bloat might not be as big as you think.

That said, I actually agree with your overall point and I think it's ok to spit out a concise version and then expand into that checklist thing on failure.

I would like to have a flag that allows you to opt into the "verbose" version, both because I think it's a good demo, and because I just like it.

Does that sound more in line with what you'd like?

**Comment by hausdorff** [comment]
Actually, @CyrusNajmabadi, on second thought, I think it would be better to have a small number of lines (perhaps even just one line for the current operation) displaying what is currently happening, as the resource is being initialized.

A good example of where this is useful is when Pulumi is polling repeatedly because it doesn't have access to some container registry; this could change, but it probably won't, and displaying this to the user is useful, because it gives them the information they need to decide to cancel the rollout and fix the issue themselves.

And on a _muuuuuuch_ less scientific note, which I present less as a strong suggestion but more because I happen to like the look of a (slightly?) busier output screen, and I'm going to shamelessly cherry-pick things to support my hypothesis: there's this trick travel websites do to increase engagement. They find that putting a loading screen before travel results actually causes people to value the results more. This is why even new sites like Hipmunk have a loading bar, even though it takes a very small amount of time to execute the search.

As I said, not a suggestion I expect you to consider extremely carefully, but perhaps worth some brief consideration. :)

**Comment by lukehoban** [comment]
We've added richer status from Kubernetes without yet needing to change the update UX.  I suggest we move this out to a future milestone to reconsider after we've gotten some experience with the current approach.

**Comment by joeduffy** [comment]
@hausdorff The current approach seems to be working quite well, especially with the addition of ephemeral messages -- should we close this out?

**Comment by hausdorff** [comment]
I think we can close this, yes.
