### ISSUE TITLE
AwaitableGetSubnetsResult

### ISSUE THREAD

**Issue by kubegurus** [pulumi/pulumi#15457]
### What happened?

Can't use output of aws.ec2.get_subnet because rather than getting the real info I am stuck on AwaitableGetSubnetsResult 

### Example

`subnet.py`

```
def get_subnets_info(private_subnets):
    subnets_info = []
    for subnet_id in private_subnets:
        subnet_info = aws.ec2.get_subnet(id=subnet_id)
        subnets_info.append(subnet_info)
    
    return subnets_info
 ```
 
`main.py`

```
import pulumi
from   pulumi import ResourceOptions
import pulumi_aws as aws 
from subnets import get_subnets_info

private_subnets = aws.ec2.get_subnets(filters=[{"name": "vpc-id", "values": [vpc_id]}],tags={"SubnetType":"Private"})
subnets_info = get_subnets_info(private_subnets.ids)
print(subnets_info)
```

### Output of `pulumi about`

CLI          
Version      3.105.0
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.18.1
eks         2.2.1
kubernetes  4.7.1
python      unknown

This project is written in python: executable='/opt/homebrew/bin/python3' version='3.11.4'

NAME        VERSION
pip         24.0.0
pulumi_eks  2.2.1
setuptools  69.0.3
wheel       0.42.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@kubegurus, sorry for the trouble. I'm not sure what you mean. You should be able to get the data of each subnet_info, for example, this prints out each arn:

```python
private_subnets = aws.ec2.get_subnets(filters=[{"name": "vpc-id", "values": [vpc_id]}],tags={"SubnetType":"Private"})
subnets_info = get_subnets_info(private_subnets.ids)
# print(subnets_info)
for subnet in subnets_info:
    print(subnet.arn)
```

**Comment by mikhailshilkov** [comment]
@kubegurus Were you able to try the example above?
