### ISSUE TITLE
Support for Hashicorp Nomad

### ISSUE THREAD

**Issue by leowmjw** [pulumi/pulumi#1546]
I'll be interested to participate in a port to target Nomad + its ecosystem (Consul + Nomad + Vault); instead of just having Kubernetes support.  

Do provide some guidance on where / how to get started; that is small enough for a beginner to take a stab at.  Thanks!

**Comment by joeduffy** [comment]
Sounds great!  We'd love to help you get this going.

The easiest thing to do would be to use [our Terraform Bridge](https://github.com/pulumi/pulumi-terraform) to adapt the existing [Terraform Nomad Provider](https://github.com/terraform-providers/terraform-provider-nomad).  The bridge repo's [README](https://github.com/pulumi/pulumi-terraform/blob/master/README.md) has high-level instructions for how this work, and the [Pulumi AWS](https://github.com/pulumi/pulumi-aws) repo is a good blueprint for how this would work (albeit quite a bit more complex than many other providers).  Basically, create a new repo with the two requisite commands (a code-generator and a plugin), make a [`resources.go`](https://github.com/pulumi/pulumi-aws/blob/master/resources.go) that maps the resource types to nice programming language names, and wire up the right build commands.

TBH, I wish our docs here were better, so if you want to help make them easier to follow as you go, that would be much appreciated too!  But no worries if you'd rather focus on the code.  Judging by early interest, I suspect lots of people will want to do this in the weeks to come, that's all 😄

**Comment by ahanoff** [comment]
hi @stack72 , @joeduffy since [nomad is v1 now](https://github.com/hashicorp/nomad/releases/tag/v1.0.0) I would like to implement this provider. May I check with you how do you work with new provider repository? Do you import to pulumi org after implementation is done? Thanks

**Comment by stack72** [comment]
Hi @ahanoff 

Please feel free to get in contact with me - stack72@pulumi.com and we can discuss the new provider

Paul

**Comment by peteking** [comment]
I'm quite interested in this also, any traction so far? If not, I'm happy to help.

**Comment by ahanoff** [comment]
hi @peteking,
no traction yet. 

> https://www.pulumi.com/docs/guides/pulumi-packages/

Previously docs to create new provider were not very clear. I guess with this one should be easier now

**Comment by peteking** [comment]
Ok, yeah docs are much better now. I agree with @joeduffy comment from 3 years ago. Using the Terrafrom Bridge makes sense here given there is adequate Terraform support for Nomad.

https://registry.terraform.io/providers/hashicorp/nomad/latest/docs

To be honest, I've been through K8 in production and back and although it is great, K8 is a Swiss army knife, whereas Nomad is just a good knife; similar to the now kinda dead Docker Swarm.

**Comment by stack72** [comment]
Hi folks

I am delighted to say that thanks to the hard work by one of our community members, we now have a hashicorp nomad provider:

* https://github.com/pulumi/pulumi-nomad
* https://www.pulumi.com/docs/reference/pkg/nomad/
* https://www.npmjs.com/package/@pulumi/nomad
* https://pypi.org/project/pulumi-nomad/
* https://www.nuget.org/packages/Pulumi.Nomad

Please let us know if there are any issues

Paul
