### ISSUE TITLE
`TestMarshalDeployment` fails with an unexpected error

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#15461]
When testing both `TestMarshalDeployment` and `TestDiffStack` in parallel, `TestMarshalDeployment` will fail with an unexpected error.

Note: I have to set `GITHUB_TOKEN`, otherwise I hit rate limits:

```
go test -run "^(TestMarshalDeployment|TestDiffStack)$" github.com/pulumi/pulumi/pkg/v3/backend/httpstate -v
```

```
=== NAME  TestMarshalDeployment
    snapshot_test.go:515:
        	Error Trace:	/Users/user/go/src/github.com/pulumi/pulumi/pkg/backend/httpstate/snapshot_test.go:515
        	            				/Users/user/go/src/github.com/pulumi/pulumi/pkg/backend/httpstate/snapshot_test.go:435
        	            				/Users/user/go/src/github.com/pulumi/pulumi/pkg/backend/httpstate/snapshot_test.go:559
        	Error:      	Received unexpected error:
        	            	open testdata/two-large-checkpoints.json: no such file or directory
        	Test:       	TestMarshalDeployment
```

Somehow the CWD winds up being `/`, resulting in a later test failing when it tries to load test data.

It looks like the cause is something in [#15191](https://github.com/pulumi/pulumi/pull/15191). The commit before ([248d8d1](https://github.com/pulumi/pulumi/commit/248d8d10c6d0870a8812d47e91ae6111c079df82)) passes, and that commit ([bd4e50e](https://github.com/pulumi/pulumi/commit/bd4e50efdd9844a2e9593bb382d3d732db169194)) always fails on local.

It's this right here: [https://github.com/pulumi/pulumi/commit/bd4e50efdd9844a2e9593bb382d3d732db169194#diff-5e0e1bee94fced598b4e117cda5[…]5d13aac4b8eb7abb4f932d4138216R39](https://github.com/pulumi/pulumi/commit/bd4e50efdd9844a2e9593bb382d3d732db169194#diff-5e0e1bee94fced598b4e117cda53e97d3405d13aac4b8eb7abb4f932d4138216R39)

If that's something like the following, it passes:

```go
	cwd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	return cwd
```

**Comment by justinvp** [comment]
It looks like we are hitting this in CI but we retry the test and then it succeeds. For example, https://github.com/pulumi/pulumi/actions/runs/7929950012/job/21651468292#step:38:257

**Comment by tgummerer** [comment]
@Zaid-Ajaj is the change in `GetRoot()` here actually necessary?  Setting it to `/` will make the engine `Chdir` to that directory, and I think the only way to work around that would be to either not do that `Chdir` in the engine (which we should eventually do anyway, but it seems tricky), or making the tests non-parallel.  https://github.com/pulumi/pulumi/pull/15191 doesn't mention why the change was necessary, so I'm wondering if you have additional context here?

**Comment by Frassle** [comment]
GetRoot change is so that the NewProgramINfo function validates it as a valid path.

**Comment by Frassle** [comment]
We should probably just see if we can fix the chdir, it's grim the engine does that and it blocks a lot of other improvments.
