### ISSUE TITLE
Pluggable config/secret storage

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1547]
We have a reasonable default mechanism for config/secret storage today, where we use KMS for encryption, and just tick them in the resulting config YAML file.  Although simple, we will want a lot more flexibility in the future.  For instance, we may want to support secrets stored in Hashicorp Vault, AWS Secrets Manager, and so on.  I assume this will need to be a true point of extensibility.

This goes hand in hand with https://github.com/pulumi/pulumi/issues/397, which is to defer decryption until "as late as possible," which touches the pluggable interface here in the sense that I assume we want all access to secrets managed by, say, Vault, to go through Vault at the time of usage, to integrate properly with its auditing capabilities.  This is a service pulumi.com should also provide, once we have the ability to properly defer this to runtime rather than deployment time.

**Comment by joeduffy** [comment]
We have a design for this work which we'll socialize and pursue as part of our next milestone.

**Comment by joeduffy** [comment]
@pgavlin This is currently marked P1, but based on my understanding of this sprint's focus, we have explicitly evolved our secrets focus to land `Secret<T>` first, along with checkpoint secrets, and will focus on pluggable secrets providers next sprint. Is that right? If yes, can we move this issue (and any others in the same boat)?

**Comment by pgavlin** [comment]
That's correct. I'll move this out.

**Comment by ellismg** [comment]
In the community slack, someone asked about supporting asymmetric encryption, to enable the following user experience:

> Let me restart what I think you are asking.  You'd like it if instead of using a symmetric key managed by the pulumi service when encrypting secrets, instead, you'd like to use a public/private key pair, with the public key stored in `Pulumi.<stack-name>.yaml`  This means that `pulumi config set --secret` could be run by any engineer (it just needs to encrypt a value using the public key, which is right in the file) but operations like `pulumi config get --show-secrets`, `pulumi preview` and `pulumi update` which require you to actually decrypt the secret would require you to provide the private key somehow (i.e. you could imagine a `--private-key-path` argument you'd pass to these commands).

Some rationale from the requestor:

> I think that would be useful to have baked in, as a lower entry cost for users who don't need fully pluggable secret management. I'm in a HIPAA regulated business, so for my use case, we need BYO-secret-management to be able to go live with Pulumi. We're using Google Cloud KMS for that right now in a truly epic hack, but I'd like to use the Pulumi SAAS as soon as we can so that we're not dependent on epic hacks.
