### ISSUE TITLE
Pulumi preview fails with permission errors for any stacks that use ESC environments

### ISSUE THREAD

**Issue by davejhilton** [pulumi/pulumi#15484]
### What happened?

Suddenly, as of today, any attempt to run even a `pulumi preview` on any of our stacks is failing with the following error:

```
error: getting stack configuration: opening environment: [0] 
Diags: You do not have permission to perform this operation.
```

Judging by the error message's mention of "environments", I'm guessing maybe something changed with respect to the permission model for ESC environments? Because we do reference ESC environment(s) in our stack config files.  But this was working as recently as a few days ago, and we haven't changed anything. Did Pulumi change something around how these permissions work?

### Example

Our stack config file looks more or less like this:

```
config:
  key1: value1
environment:
  - dev
```

and our ESC environment looks more or less like this:

```
values:
  aws-region: us-east-1
  global-secret:
    fn::secret:
        ciphertext: ZXN...abc123==

  environmentVariables:
    ESC_ENVIRONMENT_NAME: dev

  pulumiConfig:
    aws:region: "${aws-region}"
    secrets:global: "${secret-abc}"
```

### Output of `pulumi about`

```CLI
Version      3.106.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in nodejs: executable='/Users/daveh/n/bin/node' version='v18.14.2'

Current Stack: {org}/vpc-base/dev

TYPE                                                                       URN
pulumi:pulumi:Stack                                                        urn:pulumi:dev::vpc-base::pulumi:pulumi:Stack::vpc-base-dev
pulumi:providers:pulumi                                                    urn:pulumi:dev::vpc-base::pulumi:providers:pulumi::default
...

Found no pending operations associated with {org}/dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/{user}
User           {user}
Organizations  {user}, {org}
Token type     personal

Pulumi locates its logs in /var/folders/vw/2b3p74gx3s13s0bg7p9lg4kr0000gq/T/ by default
```

### Additional context

We are on the Pulumi "Team Edition" plan.

`pulumi preview` seems to still work if performed by the organization admin user, but it fails for all of the other organization members. But we've used these features for months with all of our users, and have never had permissions issues until now.

This also breaks our Github actions integration, too... since it fails even just trying to run `pulumi preview` for pull requests.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pgavlin** [comment]
@davejhilton we did make a fix to the RBAC checks for imported environments. Are the environments that are failing to open importing other environments?

**Comment by pgavlin** [comment]
Ah, technically the use of the environment in the stack's `environment` stanza is an import, so yes. Can you check the default environment permission for your org?

**Comment by tscully49** [comment]
We are experiencing the same issue

**Comment by pgavlin** [comment]
@tscully49 Can you check the default environment permission for your org?

**Comment by tscully49** [comment]
@pgavlin assuming I am looking in the right place, it looks like the default is read.

**Comment by davejhilton** [comment]
where would I look to find this?

**Comment by pgavlin** [comment]
@davejhilton I missed your note that you are on Team Edition. Team edition doesn't display the default permission though we still track one internally.

For users on Team Edition we believe that we have fixed this issue. Can you try using a stack with an environment now?

**Comment by pgavlin** [comment]
@tscully49 are you also on Team Edition?

**Comment by tscully49** [comment]
@pgavlin we are on enterprise

**Comment by pgavlin** [comment]
> @pgavlin we are on enterprise

Okay--great--I think I see the subscription now. In your case, manually setting the default environment permission to `open` or `write` should fix things. The difference between the two is that `open` permission will allow users to use but not edit environments by default.

**Comment by davejhilton** [comment]
@pgavlin out of curiosity, is the default/internal permission set to `open`, then, for Team Edition?

**Comment by pgavlin** [comment]
> @pgavlin are there docs explaining the difference between those different options?
> 
> Maybe I don’t understand the ins and outs but the fear is a a default read permission would give elevated access to secrets we store in ESC rather than trying to implement least privileged.

`read` or `none` permission is what you want if you are looking for least privilege:

- `none` will give users no access to environments by default
- `read` will allow users to view environment definitions but will not allow users to use the secrets in those environments (so users with `read` permission cannot use `esc env open`/`esc run`/`pulumi up` for stacks with environments)
- `open` will allow users to use secrets from environments but not edit those environments
- `write` will allow users to use secrets from environments and edit those environments

If your org's default environment permission is not `write`, you will need to assign users and environments to teams to grant additional permissions.

Looking for official docs now.

**Comment by pgavlin** [comment]
(edited the above to clarify that users with `read` permission for an environment cannot view secrets at all)

**Comment by tscully49** [comment]
@pgavlin thanks for the insight! Are wildcards supported when we grant open access to specific environments?

**Comment by pgavlin** [comment]
> @pgavlin thanks for the insight! Are wildcards supported when we grant open access to specific environments?

They are not, unfortunately. The default environment permission is the closest thing we have to a wildcard. Each environment must be added to the appropriate team(s) individually.

We're actively planning a more flexible permission model. I'd definitely be interested to hear more about how you'd like to configure things in an ideal world.

**Comment by lukehoban** [comment]
This issue has been fixed for Individual and Team organizations.  For Enterprise and Business Critical organizations which have access to the "teams" feature and the ability to set a default permission for environments, the default has not been changed, but any users seeing this issue can modify it themselves from "Read" (only see the text defining an environment, which includes ciphertext and OIDC configuration, but not plaintext secrets), to either "Open" (decrypt secrets and resolve OIDC credential requests) or "Write" (modify the text defining an environment, plus also open the environment).

We will follow up with further improvements to documentation.
