### ISSUE TITLE
Pulumi Go programs have no natural way of acquiring plugins

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1549]
We rely on package managers to do this on install for other languages, but naturally Go can't rely on this. We should either come up with something here or (at minimum) update templates and documentation to ensure that 1) people know how to download plugins if they are missing and 2) people know to reach for `pulumi plugin install` when using a new provider with Go.

**Comment by swgillespie** [comment]
Go support is out of scope for M21.

**Comment by lukehoban** [comment]
@pgavlin @EvanBoyle Do we have any thoughts on what we'll do here?  This seems to be a fairly deep remaining question mark for Go support.

**Comment by EvanBoyle** [comment]
Let's make sure we update the getting started docs to remove plugin installation once we ship this. AWS example here, but we need to do this for each cloud's getting started guide:

https://github.com/pulumi/docs/pull/2480#discussion_r381648889

**Comment by EvanBoyle** [comment]
closed via https://github.com/pulumi/pulumi/pull/4060
