### ISSUE TITLE
Invalid id: "1:10", Pulumi (Golang) Grafana provisioning deployment bug

### ISSUE THREAD

**Issue by pancudaniel7** [pulumi/pulumi#15494]
### What happened?

Every time I execute `pulumi up`, I encounter an issue where an ID becomes invalid in the state for the Grafana Prometheus data source.

You can check the error in the image below:

<img width="1250" alt="Screenshot 2024-02-22 at 18 55 29" src="https://github.com/pulumi/pulumi/assets/9675142/e56a8578-34ce-407d-8491-c0eca6db7b5e">

### Example

To reproduce the error you can simply run `pulumi up`. Please take in consideration that our Grafana datasource is provisioned using **Pulumi with Golang** like:

<img width="1107" alt="Screenshot 2024-02-22 at 19 01 50" src="https://github.com/pulumi/pulumi/assets/9675142/fdfbd4d3-d054-4a61-a7df-3648fabffe1a">

### Output of `pulumi about`

CLI
Version      3.107.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME       VERSION
auth0      2.23.0
aws        5.41.0
aws        4.38.1
buildkite  2.2.0
github     5.16.0
go         unknown
grafana    0.0.10
random     4.8.2

Host
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.21.5 darwin/arm64'

### Additional context

How we deal with it:

We solve this by exporting the current stack file deleting '1:' from the string '1:10' in the stack file, importing the stack file and running `pulumi up` again.
The main problem here is the time we spend doing that.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Hi @pancudaniel7. Sorry for the trouble. This looks like an issue in the grafana provider, which is maintained by community contributors. It recently moved from the `lbrlabs` org on GitHub to `pulumiverse`: https://github.com/pulumiverse/pulumi-grafana and it sounds like the repo will be unarchived soon. I suggest keeping an eye on that repo and opening an issue there when it's been unarchived. See https://pulumi-community.slack.com/archives/C037PV12W6L/p1709227500753519?thread_ts=1707150007.333119&cid=C037PV12W6L on our community slack for more details.

**Comment by mikhailshilkov** [comment]
https://github.com/pulumiverse/pulumi-grafana/issues is now fully available. Unfortunately, it's not possible to transfer this issue to a repo in another org, so I'll have to close it here. Please open the same issue in the provider if you still experience it. Thank you and sorry for the trouble!
