### ISSUE TITLE
Add retainOnDelete option to s3.BucketObject

### ISSUE THREAD

**Issue by alex-e-leon** [pulumi/pulumi#15509]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I would love to see retainOnDelete extended to s3 bucketObjects. My particular use case is that I have application files (html/js/css etc) that I'm adding to s3 and managing as FileAssets, however I need to keep old files around for a period after new deployments to support users who are still using old versions of the application and haven't upgraded yet.

**Comment by ringods** [comment]
@alex-e-leon `retainOnDelete` is a [resource option](https://www.pulumi.com/docs/concepts/options/retainondelete/) which is available to all Pulumi resources. To activate `retainOnDelete` on a `BucketObject`, the following code snippet should do it:

```ts
let bucketObject = new aws.s3.BucketObject("object", {
      # bucket object arguments here
   }, 
   { 
      retainOnDelete: true
   }
);
```
