### ISSUE TITLE
Add ability to configure emitting large supporting types beyond the 200 limit

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#15507]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently in the doc gen if there are over 200 Nested Types for a resource, only the first 200 are included in the documentation. In some instances it makes docs unusable because many links are broken when they point to one of the types that are excluded. It would be nice for this to be made configurable either to change the amount displayed or to opt out of this functionality altogether.

The relevant code snippet is [here](https://github.com/pulumi/pulumi/blob/26bdac74383c599a7c976d301822883f38ac9b29/pkg/codegen/docs/templates/resource.tmpl#L300-L303).

### Affected area/feature

Doc Gen

**Comment by justinvp** [comment]
We could likely simply remove this limitation. It was originally added in https://github.com/pulumi/pulumi/pull/12070 because of the wafv2 types in AWS. But since then, we fixed the underlying problem with https://github.com/pulumi/pulumi-aws/pull/2589. So we may not have any actual cases where this limit is needed anymore.

**Comment by mikhailshilkov** [comment]
@zbuchheit Can you provide any details about the customer use case? Do they have a very complicated resource with 200+ genuine types, or is it maybe some recursive-like types similar to what we had for WafV2 in AWS? Is there a specific number that would be enough for them?

Removing the limit altogether sounds a bit dangerous in case any provider (1st or 3rd party) goes out of control in wafv2-similar way. We could consider bumping it up, or providing a configuration value.

**Comment by zbuchheit** [comment]
I think making this configurable might be the best option here. If we bumped it up we would need to know how many supporting resources their problematic resource is, and even then if it expands further we would find ourselves in a position to bump it up again once they hit the new ceiling.

**Comment by mikhailshilkov** [comment]
We bumped the limit to 1000 for now. If anyone thinks that's still not enough, we can consider lifting it even higher.
