### ISSUE TITLE
Wording in confirmation of `pulumi refresh` does not describe actual intent

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi#1551]
When running `pulumi refresh` on a stack where drift has occurred (intentionally in this case), the wording is not clear that the resource to be updated is in _checkpoint state_ and not the actual cloud resources:

```shell
❯ pulumi refresh
Previewing refresh of stack 'network'
Previewing changes:

     Type                 Name              Plan          Info
 *   pulumi:pulumi:Stack  vpc-demo-network  no change
 ~   └─ aws:ec2:Vpc       demo-vpc          update

info: 1 change previewed:
    ~ 1 resource to update
      4 resources unchanged

Do you want to perform this refresh?
  yes
> no
  details
```

**Comment by lukehoban** [comment]
Good point - `update` is suggestive that this is the same kind of update that happens when the Pulumi program is going to update the target cloud provider.  I wonder if `refresh` is a better word to use in this context?

**Comment by joeduffy** [comment]
Maybe just a parenthetical after the `Do you want to perform this refresh?`, something along the lines of `    (this operation will not affect live cloud resources, it will just synchronize your state)`.

**Comment by lukehoban** [comment]
FWIW - When re-reviewing this text as part of the recent `refresh` changes Pat made, we could not come up with any "better" names - it felt like we were inventing synonyms of "update" and "delete" that were equally confusing.  And overall, in the context of a "refresh", the existing names felt more "correct".  So I like the idea of keeping the names as-is and using text in the preamble to help clarify this.
