### ISSUE TITLE
Create a package with functions for all Terraform built-ins to ease migration

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi#1552]
It would be useful to have an equivalent of the Terraform `cidrsubnet` function available as a library function for calculating subnet CIDR blocks from a base address.

From the Terraform documentation:

`cidrsubnet(iprange, newbits, netnum)` - Takes an IP address range in CIDR notation (like `10.0.0.0/8`) and extends its prefix to include an additional subnet number.

For example:
- `cidrsubnet("10.0.0.0/8", 8, 2`) returns `10.2.0.0/16`
- `cidrsubnet("2607:f298:6051:516c::/64", 8, 2)` returns `2607:f298:6051:516c:200::/72`

For a list of all Terraform built-ins see: https://www.terraform.io/docs/configuration/interpolation.html#supported-built-in-functions

**Comment by lukehoban** [comment]
It feels like there must be some NPM package that does this - right?  A nice thing about using JS (or any other general purpose language) is that this sort of pure-logic thing generally should already available in the package manager ecosystem.

**Comment by lukehoban** [comment]
And if it's not already, the other nice thing is that anyone can publish a vanilla NPM package with this functionality, and it can then be used from Pulumi (+ any other Node application).

**Comment by joeduffy** [comment]
I'm with James on this one. Frankly, I think we should just have a package with each TF function in one place, to ease migration. @pgavlin I assume we would need that for an HCL converter anyhow.

**Comment by lukehoban** [comment]
Yeah - spent some time looking myself and was surprised that nothing seems to exist.  

I do agree that it likely makes sense to create an npm package `terraform-builtins` that exposes exactly the set of functions at https://www.terraform.io/docs/configuration/interpolation.html#built-in-functions.  As @joeduffy notes - especially useful for migrations.  I'll update the title hear to track that.

FWIW - here was what I came up with for `cidrsubnet` in particular after spending a a few mins on this last night.  I'm sure this can be improved, but perhaps a starting point.

```javascript
var ipaddress = require('ip-address');
var BigInteger = require('jsbn').BigInteger;

// Takes an IP address range in CIDR notation (like 10.0.0.0/8) and extends its prefix to include an additional subnet number.
// For example: 
// * cidrsubnet("10.0.0.0/8", 8, 2) returns 10.2.0.0/16
// * cidrsubnet("2607:f298:6051:516c::/64", 8, 2) returns 2607:f298:6051:516c:200::/72
exports.cidrSubnet = function(iprange, newbits, netnum) {
    var ipv4 = new ipaddress.Address4(iprange);
    var ipv6 = new ipaddress.Address6(iprange);
    if (ipv4.isValid()) {
        var newsubnetMask = ipv4.subnetMask + newbits;
        if (newsubnetMask > 32) {
            throw new Error("Requested " + newbits + " new bits, but only " + (32 - ipv4.subnetMask) + " are available.");
        }
        var addressBI = ipv4.bigInteger();
        var twoBI = new BigInteger('2');
        var netnumBI = new BigInteger(netnum.toString())
        
        var newAddresBI = addressBI.add(twoBI.pow(32 - newsubnetMask).multiply(netnumBI));
        var newAddress = ipaddress.Address4.fromBigInteger(newAddresBI).address;

        return newAddress + "/" + newsubnetMask;
    } else if (ipv6.isValid()) {
        var newsubnetMask = ipv6.subnetMask + newbits;
        if (newsubnetMask > 128) {
            throw new Error("Requested " + newbits + " new bits, but only " + (128 - ipv6.subnetMask) + " are available.");
        }
        var addressBI = ipv6.bigInteger();
        var twoBI = new BigInteger('2');
        var netnumBI = new BigInteger(netnum.toString())
        
        var newAddresBI = addressBI.add(twoBI.pow(128 - newsubnetMask).multiply(netnumBI));
        var newAddress = ipaddress.Address6.fromBigInteger(newAddresBI).correctForm();

        return newAddress + "/" + newsubnetMask;
    } else {
        throw new Error("Invalid IP address range: " + iprange);
    }
};

// Takes an IP address range in CIDR notation and creates an IP address with the given host number.
// If given host number is negative, the count starts from the end of the range.
// For example:
// * cidrhost("10.0.0.0/8", 2) returns 10.0.0.2
// * cidrhost("10.0.0.0/8", -2) returns 10.255.255.254
exports.cidrHost = function(iprange, hostnum) {
    var ipv4 = new ipaddress.Address4(iprange);
    var ipv6 = new ipaddress.Address6(iprange);
    if (ipv4.isValid()) {
        var hostnumBI = new BigInteger(hostnum.toString());
        var addressBI;
        if (hostnum >= 0) {
            var startAddressBI = ipv4.startAddress().bigInteger();
            addressBI = startAddressBI.add(hostnumBI);
        } else { 
            var endAddressBI = ipv4.endAddress().bigInteger();
            addressBI = endAddressBI.add(hostnumBI).add(new BigInteger('1'));
        }
        return ipaddress.Address4.fromBigInteger(addressBI).address;
    } else if (ipv6.isValid()) {
    } else {
        throw new Error("Invalid IP address range: " + iprange);
    }
}
```

**Comment by lukehoban** [comment]
Opened https://github.com/pulumi/pulumi-terraform/issues/267 to track this instead.
