### ISSUE TITLE
Some broken links in `New Language Bring Up` wiki

### ISSUE THREAD

**Issue by mohammadzainabbas** [pulumi/pulumi#15535]
### What happened?

While following the issue https://github.com/pulumi/pulumi/issues/3622 on Rust SDK support, I came across a [question](https://www.pulumi.com/docs/support/faq/#how-can-i-add-support-for-my-favorite-language) from _Pulumi CLI & Pulumi Cloud FAQ_, and I end up on [`New Language Bring Up`](https://github.com/pulumi/pulumi/wiki/New-Language-Bring-up) _wiki_, but the some links are broken in that _wiki_. It would be really nice if someone could fix those broken links.

### Example

Some broken links:

- [ ] https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/cmd/pulumi-language-dotnet/main.go
- [ ] [language.proto](https://github.com/pulumi/pulumi/blob/master/sdk/proto/language.proto)
- [ ] [resource.proto](https://github.com/pulumi/pulumi/blob/master/sdk/proto/resource.proto)
- [ ] https://github.com/pulumi/pulumi-kubernetes/tree/master/cmd/pulumi-gen-kubernetes

among others...

### Output of `pulumi about`

N/A

### Additional context

> [!TIP]
> It would be highly appreciated if someone can make new language SDK support wiki a bit better.

Some links aren't that useful in wiki, for instance: [`Programming Model`](https://www.pulumi.com/docs/intro/concepts/programming-model/) doc redirects to concept page (on [`What is Pulumi?`](https://www.pulumi.com/docs/concepts/)), which isn't helpful in my POV to someone who wants to know about _Programming Model_ in this particular context. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening the issue @mohammadzainabbas and letting us know about the broken links

**Comment by mohammadzainabbas** [comment]
@justinvp I'm happy to help! If there's anything I can do to assist in resolving the issue, please let me know.

**Comment by mikhailshilkov** [comment]
I've fixed all the broken links. There are definitely many ways to make this page more useful - but at least it's not entirely broken anymore.
