### ISSUE TITLE
Punycode deprecation warning in node 21 when using function serialisation.

### ISSUE THREAD

**Issue by julienp** [pulumi/pulumi#15545]
In node 21, importing `punycode` emits a deprecation warning https://nodejs.org/docs/latest/api/deprecations.html#dep0040-nodepunycode-module

Function serialisation [loads this module](https://github.com/pulumi/pulumi/blob/a87b0683cd580282a1f37608ac583a5cf84549a0/sdk/nodejs/runtime/closure/createClosure.ts#L1360) to compare it to modules imported by user code.

Sometimes users have a brittle CI setup and warnings cause failures https://github.com/pulumi/pulumi/issues/15499

**Comment by julienp** [comment]
@justinvp I am not entirely sure what the best course of action is here. Currently we exclude `sys` from the list of builtin modules, but I think this is fine because it was depreciated in node 1.0 (!) and has never been available for function serialisation.

`punycode` is only imported if you use function serialisation, so you don't always run into it like it was the case for the grpc `server.start()` deprecation warning.

I think we can do something like the following in the nodejs bootstrap code to make the warnings more integrated into pulumi

```js
process.removeAllListeners('warning');
process.addListener('warning', warn => pushToPulumiDiagnostics)
```

**Comment by justinvp** [comment]
I'm leaning towards excluding `punycode` like we do with `sys` to avoid the deprecation warning. I don't think it'll break anyone in practice.

https://github.com/pulumi/pulumi/blob/cffdfd1fa4896d7184210b409529ce032877b622/sdk/nodejs/runtime/closure/createClosure.ts#L1421
