### ISSUE TITLE
Test are failing for PRs (`TestCodePathsWorkspace`, `TestCodePathsNested`, etc.)

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#15557]
Tests are failing for PRs:

https://github.com/pulumi/pulumi/actions/runs/8107787381/job/22160117521?pr=15555#step:38:188

```
=== FAIL: integration TestCodePathsWorkspace (96.06s)
...
    error: Error: Got '["../node_modules/is-finite","../node_modules/my-dynamic-provider","../node_modules/my-random","../node_modules/semver","../node_modules/yallist"]' expected '["../node_modules/is-finite","../node_modules/lru-cache","../node_modules/my-dynamic-provider","../node_modules/my-random","../node_modules/semver","../node_modules/yallist"]'
        at /tmp/p-it-fv-az1391--codepaths--f532c118-2414419144/infra/index.ts:45:11
        at Generator.next (<anonymous>)
        at fulfilled (/tmp/p-it-fv-az1391--codepaths--f532c118-2414419144/infra/index.ts:19:58)
```

https://github.com/pulumi/pulumi/actions/runs/8107787381/job/22160117668?pr=15555#step:38:193

```
=== FAIL: integration TestCodePathsNested (41.87s)
...
    error: Error: Got '["../node_modules/semver","../node_modules/yallist"]' expected '["../node_modules/lru-cache","../node_modules/semver","../node_modules/yallist"]'
        at /tmp/p-it-fv-az802-5-codepaths--f71d26fc-2452614488/nested/index.ts:24:15
        at Generator.next (<anonymous>)
        at fulfilled (/tmp/p-it-fv-az802-5-codepaths--f71d26fc-2452614488/nested/index.ts:18:58)
```

There may be others with similar failures.

**Comment by julienp** [comment]
I forgot to provide an update on this ticket yesterday. We skipped the tests to unblock the release.

Tests are being re-enabled in https://github.com/pulumi/pulumi/pull/15573

**Comment by julienp** [comment]
The test cases have `semver` has a dependency, which depends on `lru-cache`.

Depending on how the modules are being installed hosted within node_modules, we can end up with a structure where the version of `lru-cache` that's required is nested inside `semver`. Notably this happened with the release of 3.108.0 and later. Previously the `lru-cache` was a sibling of `semver`. This leads to two different outputs and a brittle test.

```
├── lru-cache@10.2.0
└─┬ semver@7.6.0
  └── lru-cache@6.0.0
```
