### ISSUE TITLE
Support (some) stack operations without a local Pulumi.yaml file

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1556]
With the stack identity model only taking owner and stack name into account, we no longer need a `Pulumi.yaml` file in order to run `pulumi stack select`. The problem this causes is that if you want to `destroy` or `rm` a stack, you need to create a `Pulumi.yaml`, even though it is entirely ignored.

Ideally you could just `pulumi stack select foo` in any directory and then immediately run `pulumi stack destroy`. However, this would open up the possibility for user error where you run `pulumi update` in the wrong directory or something.

So perhaps we just need a `--ignore-missing-pulumi-yaml` flag for `destroy` or `rm`? Or just punt on this entirely? /cc @lukehoban

**Comment by joeduffy** [comment]
The key thing that using the `Pulumi.yaml` gives us is filtering the `pulumi stack ls` list.

Can you not just `pulumi stack rm --stack whatever`?

**Comment by ericrudder** [comment]
or destroy -y could just ignore ... i usually expect if i give the hint to
a CLI to "just do it" .. it should try to "just do it" ... i gave up my
right to be warned.

**Comment by chrsmith** [comment]
@joeduffy No, a `Pulumi.yaml` file is required in what looks like all cases.

$ pulumi stack ls
error: no Pulumi.yaml found; please run this command in a project directory

# There is legitimately no stack named foo.
$ pulumi stack select foo
error: no stack named 'foo' found

# Stack resources-ex exists, and since it does you get an error about Pulumi.yaml.
$ pulumi stack select resources-ex
error: no Pulumi.yaml project file found

# Passing --stack and bypassing the 'stack select' step also fails
$ pulumi destroy --stack resources-ex
error: no Pulumi.yaml project file found (searching upwards from /Users/chris/wasteland)
```

**Comment by joeduffy** [comment]
This just feels like a bug, unsurprising given our history.

`pulumi destroy` and `pulumi stack rm` should not require the `Pulumi.yaml` file, because neither actually runs the program.  So, I believe we should be able to fix these.

`pulumi stack select` probably doesn't make sense to try to make work in this context, since its entire purpose is to select a stack so that subsequent commands automatically use the ambiently selected stack (which we are intentionally overriding using the `--stack` flag).

`pulumi stack ls` has an `--all` (`-a`) flag that will list all stacks, regardless of project file.

**Comment by ellismg** [comment]
> `pulumi destroy` and `pulumi stack rm` should not require the `Pulumi.yaml` file, because neither actually runs the program.

This is true, but for the `pulumi destroy` case we *do* need the provider configuration, which while not in `Pulumi.yaml` is present in `Pulumi.<stack-name>.yaml`, which presumably is missing as well in these cases.  So maybe in this case `pulumi destroy` could offer doing `pulumi config refresh` behind the scenes (fetching the config from the last deployment without persisting it to disk).

**Comment by joeduffy** [comment]
Yeah that seems like a good idea. In fact maybe we should consider doing this for all commands, since in my experience this has been a pain point when working in a team setting. Ymmv, and I realize this reopens old wounds.

**Comment by joeduffy** [comment]
After more pondering, I'm not sure we should go there.

You _can_ `stack rm` without the `Pulumi.yaml` file, right?  This is perhaps the distinction between `destroy` -- which requires program inputs (even if just config) -- and `stack rm`, which does not.

**Comment by ellismg** [comment]
Correct, there’s no technical reason that `stack rm` requires the Pulumi.yaml file.  The fact that the CLI requires it today is just an artifact of how to code evolved from previous iterations where it was required.

**Comment by joeduffy** [comment]
That's what I assumed.  (And in fact, every time I originally commented, I assumed we were only discussing stack removal.)  I say we just fix that then and document the rest.  Just as you can't update a stack without its program and config, it makes sense to me that you can't destroy without the config.  The fact that we have the config refresh command means there's always an explicit workaround.

And @chrsmith, when we discuss "buttons" in the UI, I assume we're not talking about destroy?

**Comment by chrsmith** [comment]
> when we discuss "buttons" in the UI, I assume we're not talking about destroy?

Correct. We cannot touch the user's resources to perform the destroy operation without their cloud provider's (e.g. AWS) credentials.

**Comment by justinvp** [comment]
Sadly need to push this out to focus on the remaining work in the Console.

**Comment by darnmason** [comment]
Could this be reopened to include `pulumi stack output OutputName`?

**Comment by ColeSiegelTR** [comment]
Hi @joeduffy 

I have the same use case as @darnmason , I am looking to output values from a different stack, but I need to select the stack first before running `pulumi stack output OutputName`

Since I am not doing any Pulumi deployment here I don't think I should need the yaml file, I guess I need to make a dummy one as a work-around in the mean time.

**Comment by Frassle** [comment]
I don't think rm, or output do need the yaml file? You just need to fully quailfy the stack name you pass to `--stack`, 
e.g. the following works for me:
```
$ pulumi stack output --stack Frassle/import_test/dev
Current stack outputs (1):
    OUTPUT      VALUE
    bucketName  my-bucket-5b9b82b
```

**Comment by lukehoban** [comment]
@Frassle sounds like we might want to improve the error message in these cases to be more clear that there are two options to fix:
1. Fully qualify the stack name
2. Work within a folder that has a project name inferred from a Pulumi.yaml

**Comment by Frassle** [comment]
```
$ pulumi stack output --stack Frassle/dev
error: If you're using the --stack flag,pass the fully qualified name (org/project/stack): no Pulumi project found in the current working directory. Move to a directory with a Pulumi project or try creating a project first with `pulumi new`.
```

@Zaid-Ajaj just updated that 😄

**Comment by khngn** [comment]
While 
`pulumi cancel --stack full/stack/name` works
`pulumi stack export --stack full/stack/name` works
but then `pulumi refresh --stack full/stack/name` fails with `error: no Pulumi.yaml project file found` just confusing/wrong since the help text show the --stack flag for `refresh`.
Is there a way to run `pulumi refresh` without the `Pulumi.yaml` file?

**Comment by Frassle** [comment]
You can write a minimal pulumi.yaml file with just the runtime filled in (doesn't even need to be a valid runtime, refresh by default won't start it up). 

I'll note though that going forward more and more features will require running the program itself so will need the Pulumi.yaml and the program code to run refresh with.

**Comment by khngn** [comment]
> You can write a minimal pulumi.yaml file with just the runtime filled in (doesn't even need to be a valid runtime, refresh by default won't start it up).
> 
> I'll note though that going forward more and more features will require running the program itself so will need the Pulumi.yaml and the program code to run refresh with.

@Frassle thank you for the info. I use Automation API with inline Pulumi program (with S3 state bucket) and so never have had a Pulumi.yaml. I just wanted to run some actions via the CLI (faster in my Azure pipeline) and so far it's just that the `refresh` causing trouble. Have to generate an artificial Pulumi.yaml just to run a command is just odd.
