### ISSUE TITLE
Examples rendered with not_implemented

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#15589]
### What happened?

There is some code that is generating `not_implemented` into docs and examples.

Possibly this code is involved:
https://github.com/pulumi/pulumi/blob/f831cb942bfad3e7cbee414570786ea363fd370d/pkg/codegen/python/gen_program_expressions.go#L302

This is not a great experience for docs, and perhaps it would be helpful if the generators could be
configured to fail instead of generating this runtime-failing code. In that case example generation
could opt into making these fail, and track the failure reason over time until we can addres the root cause.

### Example

There are https://github.com/search?q=org%3Apulumi%20not_implemented&type=code 195 hits (likely overstating)

Specific instances:

https://github.com/pulumi/pulumi-gcp/blob/master/sdk/python/pulumi_gcp/compute/get_machine_types.py#L116
https://github.com/pulumi/pulumi-azure/blob/7de3999e98e52297a8b4d397e73795adf1186dd2/sdk/python/pulumi_azure/monitoring/scheduled_query_rules_alert.py#L663
https://github.com/pulumi/pulumi-aws/blob/59f3fffe3b86655d0ba639c40e9590c5fadfb923/sdk/python/pulumi_aws/apigateway/domain_name.py#L834

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
@iwahbe thank you for calling attention to this code-generation phenomenon.

**Comment by sean1588** [comment]
Here is a list of resources for aws, gcp, azure, that contain examples affected by this.
```
// pulumi-aws
[
  "aws:apigateway/basePathMapping:BasePathMapping",
  "aws:apigateway/domainName:DomainName",
  "aws:apigatewayv2/deployment:Deployment",
  "aws:autoscaling/tag:Tag",
  "aws:autoscalingplans/scalingPlan:ScalingPlan",
  "aws:cloudfront/function:Function",
  "aws:cognito/identityPoolProviderPrincipalTag:IdentityPoolProviderPrincipalTag",
  "aws:controltower/landingZone:LandingZone",
  "aws:datasync/agent:Agent",
  "aws:ec2/launchTemplate:LaunchTemplate",
  "aws:ec2/vpcIpam:VpcIpam",
  "aws:ecs/service:Service",
  "aws:eks/nodeGroup:NodeGroup",
  "aws:elasticache/cluster:Cluster",
  "aws:identitystore/group:Group",
  "aws:identitystore/groupMembership:GroupMembership",
  "aws:identitystore/user:User",
  "aws:imagebuilder/component:Component",
  "aws:lambda/invocation:Invocation",
  "aws:networkmanager/siteToSiteVpnAttachment:SiteToSiteVpnAttachment",
  "aws:sagemaker/modelPackageGroupPolicy:ModelPackageGroupPolicy",
  "aws:secretsmanager/secretVersion:SecretVersion",
  "aws:ssoadmin/accountAssignment:AccountAssignment",
  "aws:ssoadmin/application:Application",
  "aws:ssoadmin/applicationAccessScope:ApplicationAccessScope",
  "aws:ssoadmin/customerManagedPolicyAttachment:CustomerManagedPolicyAttachment",
  "aws:ssoadmin/instanceAccessControlAttributes:InstanceAccessControlAttributes",
  "aws:ssoadmin/managedPolicyAttachment:ManagedPolicyAttachment",
  "aws:ssoadmin/permissionSet:PermissionSet",
  "aws:ssoadmin/permissionSetInlinePolicy:PermissionSetInlinePolicy",
  "aws:ssoadmin/permissionsBoundaryAttachment:PermissionsBoundaryAttachment",
  "aws:ssoadmin/trustedTokenIssuer:TrustedTokenIssuer",
  "aws:transfer/certificate:Certificate",
  "aws:wafv2/webAclLoggingConfiguration:WebAclLoggingConfiguration"
]

// pulumi-gcp
[
  "gcp:compute/managedSslCertificate:ManagedSslCertificate",
  "gcp:compute/mangedSslCertificate:MangedSslCertificate",
  "gcp:firebase/webApp:WebApp"
]

// pulumi-azure
[
  "azure:automation/runBook:RunBook",
  "azure:core/resourceGroupTemplateDeployment:ResourceGroupTemplateDeployment",
  "azure:hpc/cacheBlobNfsTarget:CacheBlobNfsTarget",
  "azure:monitoring/scheduledQueryRulesAlert:ScheduledQueryRulesAlert",
  "azure:network/networkInterfaceApplicationGatewayBackendAddressPoolAssociation:NetworkInterfaceApplicationGatewayBackendAddressPoolAssociation"
]
```

**Comment by t0yv0** [comment]
https://github.com/hashicorp/terraform-provider-google-beta/blob/master/website/docs/r/firebase_web_app.html.markdown?plain=1#L30 has some HCL example for   "gcp:firebase/webApp:WebApp"

Which results in:
https://github.com/pulumi/pulumi-gcp/blob/master/sdk/python/pulumi_gcp/firebase/web_app.py#L282

**Comment by t0yv0** [comment]
Debugging it a bit on that example.

```
t0yv0@Antons-MacBook-Pro> pulumi convert --from terraform --language pcl --out ./pcl --strict                                                                                                ~/tmp/2024/03/pu-15589
Converting from terraform...
warning: /Users/t0yv0/tmp/2024/03/pu-15589/input.tf:27,30-99: Function not yet implemented; Function lookup not yet implemented
warning: /Users/t0yv0/tmp/2024/03/pu-15589/input.tf:28,30-101: Function not yet implemented; Function lookup not yet implemented
warning: /Users/t0yv0/tmp/2024/03/pu-15589/input.tf:29,30-106: Function not yet implemented; Function lookup not yet implemented
warning: /Users/t0yv0/tmp/2024/03/pu-15589/input.tf:30,30-101: Function not yet implemented; Function lookup not yet implemented
Converting to pcl...
t0yv0@Antons-MacBook-Pro> pulumi convert --from terraform --language pcl --out ./pcl                                                                                                         ~/tmp/2024/03/pu-15589
Converting from terraform...
warning: /Users/t0yv0/tmp/2024/03/pu-15589/input.tf:27,30-99: Function not yet implemented; Function lookup not yet implemented
warning: /Users/t0yv0/tmp/2024/03/pu-15589/input.tf:28,30-101: Function not yet implemented; Function lookup not yet implemented
warning: /Users/t0yv0/tmp/2024/03/pu-15589/input.tf:29,30-106: Function not yet implemented; Function lookup not yet implemented
warning: /Users/t0yv0/tmp/2024/03/pu-15589/input.tf:30,30-101: Function not yet implemented; Function lookup not yet implemented
Converting to pcl...
```

--strict does not help here, but we can turn these warnings into errors in a post-processing step in the bridge. Let me try that and see what it produces.

**Comment by t0yv0** [comment]
Trying this https://github.com/pulumi/pulumi-terraform-bridge/pull/1733 which looks promising on GCP.

**Comment by t0yv0** [comment]
Quick recap:

```
hcl --> pcl --> {py, ts, etc}
```

Looks like hcl->pcl introduces nyi (not yet implemented) nodes and warns about them. 

Curiosity: the second phase of the conversion may generate warnings or errors when translating these nodes to the target language.

https://github.com/pulumi/pulumi/blob/master/pkg/codegen/nodejs/gen_program.go#L1276 seems to prefer Error
https://github.com/pulumi/pulumi/blob/master/pkg/codegen/nodejs/gen_program.go#L1276 seems to prefer Warning

What I am leaning toward is a fix scoped to only the bridge hcl --> pcl phase, that all it does it takes those warnings produced by the terraform converter and promotes them to errors. Having an error drops the example from api docs and schema equally, and generates error messages that can later be subject to Metabase analytics.

There is one downside I could not quite find a good model or originator of these NYI messages so the first version is using a regex to decide if a message is a NYI message or not, which can be a little surprising for future maintainers.

**Comment by justinvp** [comment]
@Frassle, @Zaid-Ajaj, should we provide some option for the converter that @t0yv0 could set to make "not yet implemented" warnings be errors rather than warnings? Maybe even an envvar?

**Comment by t0yv0** [comment]
May consider but landed https://github.com/pulumi/pulumi-terraform-bridge/issues/1732 for now it doesn't seem too bad.

**Comment by justinvp** [comment]
Fixed in the bridge with https://github.com/pulumi/pulumi-terraform-bridge/issues/1732
