### ISSUE TITLE
[sdk/python] Synchronous invokes dependent on providers cause stalls in resource registrations - severly limiting parallelism

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#15591]
Given a program like this:

```py
class Cluster:
    def __init__(name):
        self.eks = new EksCluster(name)
        self.k8s = new k8s.Provider(name, self.eks.kubeconfig)
        self.some_deployment = k8s.yaml.ConfigFile(name, "path/to/k8s/yaml", ResourceOptions(provider=self.k8s))

class Region:
    def __init__(region, vpc_ids):
        self.system_cluster = Cluster("system")
        self.environment_clusters = [Cluster(f"env-{vpc}") for vpc in vpc_ids]

def get_vpc_ids(region_name):
    # elided
    return list_of_vpc_ids

regions = [Region(name, get_vpc_ids(name)) for name in ["us-west-2", "eu-west-1"]]
```

This looks pretty innocuous: for each supported region, create a system EKS cluster and an EKS cluster per vpc. The EKS clusters will take a long time to create, but the creation of each Cluster can happen concurrently. And indeed, given this program, it's reasonable to expect the clusters to be created concurrently, as there is nothing that blocks on the cluster creation.

However, in yaml.ConfigFile, we find the following code:

```py
    invoke_opts = _get_invoke_options(child_opts)
    __ret__ = invoke_yaml_decode(text, invoke_opts)
    resources = _parse_yaml_document(__ret__, child_opts, transformations, resource_prefix)
```

__The problem here is that `invoke_yaml_decode` will block until the provider it uses is available, and in particular, will block the Python thread of your code that is registering resources, causing no more resources to get reported to the Pulumi engine.__ 

In the case of the code above, the provider being used is derived from an EKS cluster, and will not be ready until the EKS cluster is up. This means that the Pulumi program blocks on every EKS cluster it creates, preventing clusters from coming up concurrently.

This leads to a trace like this:
![Screenshot 2024-03-01 at 3 04 04 PM](https://github.com/pulumi/pulumi/assets/223467/7c87307f-4b1a-484f-a316-01b76dadc48e)

Whereas, if the invokes avoided blocking the main program thread, the trace would look like this:
![Screenshot 2024-03-01 at 3 04 08 PM](https://github.com/pulumi/pulumi/assets/223467/c8121217-2c06-41b0-92f6-d050e42d592d)

We will ned to determine a path to solving this for Python users.  The problem doesn't exist for Node (since invokes are async there) or Go/.NET/Java (users can fairly easily move invokes to other threads).  It does exist for YAML, and we likely need to address a similar issue there as well.  

Potential paths to a solution:
1. Provide a lower level `invoke_internal` that doesn't await the promise internally, and can be used to make an invoke call in a more untyped way.  Use this in `yaml.ConfigFile` to unblock at least this scenario.
2. Longer term, consider changing Python invokes to be async by default, or to codegen an async variant of each invoke.
3. We are working on moving `yaml.ConfigFile` to be a Multi-Language Component.  Those run out-of-process anyway, which would indirectly solve this.
4. Something else?

**Comment by justinvp** [comment]
(1) also addresses https://github.com/pulumi/pulumi/issues/15462. I suggest we get (1) merged head of this week's pulumi/pulumi release and update pulumi-kubernetes to use it for `yaml.ConfigFile`, `helm.Chart`, etc. I'll open a PR for the core Python SDK change.
