### ISSUE TITLE
On imports that "do not match the existing resource", log the diff of what did not match

### ISSUE THREAD

**Issue by oeuftete** [pulumi/pulumi#15606]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When doing an import with the Automation API, it can be unclear why it failed:

```
 =  postgresql:index:Role my-user importing (4s) error: inputs to import do not match the existing resource
```

Even turning up to extreme debug log levels doesn't make anything more clear.  (Edit: After combing those logs, I was able to do some attribute-by-attribute manual comparisons and found the culprit (it wasn't [the name](https://www.pulumi.com/docs/concepts/options/import/))... it was not convenient.)

Could the diff that caused the problem simply be logged?  Perhaps at a high log level if it would be troublesome to remove any secrets?

https://github.com/pulumi/pulumi/blob/0f8e922c715cbe338f6b182539b03aa289016a32/pkg/resource/deploy/step.go#L1165-L1174

### Affected area/feature

- Automation API
- Import

**Comment by justinvp** [comment]
Thanks for the suggestion, @oeuftete! Logging the diff sounds reasonable to me.
