### ISSUE TITLE
Jaeger traces outside of Pulumi CLI invocation

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1560]
I'm trying to debug something, and noticing that we emit `pulumi-cli: /pulumirpc.Engine/Log` traces outside of the context of a CLI invocation.

I would expect all of these separate traces to be within the context of a single CLI invocation, i.e. parented under the `<trace-without-root-span>`. 

That "without root span" trace eventually gets named when the command completes, but it isn't especially descriptive. It's just `pulumi-cli: pulumi`. Ideally we could include the command name, e.g. `pulumi-cli: update` or `pulumi-cli: stack-rm`.

![image](https://user-images.githubusercontent.com/4029847/41758375-0932db5a-759d-11e8-9c55-ec3c9e33e2cd.png)

/cc @pgavlin , @swgillespie . Is this by design somehow?

**Comment by joeduffy** [comment]
I think we've moved away from our current approach to tracing.
