### ISSUE TITLE
Conformance tests consistently fail on first try

### ISSUE THREAD

**Issue by tgummerer** [pulumi/pulumi#15603]
The conformance tests for both typescript and python seem to consistently fail on the first try, and then succeed on the retry using `gotestsum`.

Example here: https://github.com/pulumi/pulumi/actions/runs/8164156239/job/22318992080 (for typescript), and here: https://github.com/pulumi/pulumi/actions/runs/8164156239/job/22318992528 (for python).

**Comment by Frassle** [comment]
Can we repro this locally? "node_modules" aren't something we should be snapshotting.

**Comment by tgummerer** [comment]
Yes, I can repro it locally.  It looks like it's failing on validating the generated provider SDK completely.  I'm planning on looking into this today.
