### ISSUE TITLE
YAML: The "pulumi:pulumi:StackReference" resource type is deprecated

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#15635]
### What happened?

I was writing a Pulumi YAML program, and I saw this error message:

```
Diagnostics:
  pulumi:pulumi:StackReference (dw-prod):
    warning: The "pulumi:pulumi:StackReference" resource type is deprecated. Update your SDK or if already up to date raise an issue at https://github.com/pulumi/pulumi/issues.
```

I don't know how to "update my SDK", since I am using Pulumi-yaml and there is no SDK. I 

I am accessing the ref the way our documentation suggests: https://www.pulumi.com/docs/languages-sdks/yaml/yaml-language-reference/#outputs-and-stack-references

### Example

```
resources:
  dw-workflows-loader:
    type: pulumi:pulumi:StackReference
    properties:
      name: pulumi/dwh-workflows-loader-prodbuckets/production
```

### Output of `pulumi about`

```
CLI          
Version      3.107.1-dev.0
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.24.0
pulumi  unknown
yaml    unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in yaml

Current Stack: pulumi/schema-stats/prod

TYPE                      URN
pulumi:pulumi:Stack       urn:pulumi:prod::schema-stats::pulumi:pulumi:Stack::schema-stats-prod
pulumi:providers:aws      urn:pulumi:prod::schema-stats::pulumi:providers:aws::aws
aws:s3/bucketV2:BucketV2  urn:pulumi:prod::schema-stats::aws:s3/bucketV2:BucketV2::schema-stats


Found no pending operations associated with prod

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ian-pulumi-corp
User           ian-pulumi-corp
Organizations  ian-pulumi-corp, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default
```

### Additional context

I feel like any deprecation message should indicate what you should do instead.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Related to https://github.com/pulumi/pulumi/pull/14678 and https://github.com/pulumi/pulumi-yaml/pull/529

https://github.com/pulumi/pulumi-yaml/pull/529 shipped as v1.4.3 (2023-11-29) of YAML which was included with v3.95.0 (2023-12-01) of the CLI.

@iwahbe, I can't repro this using the latest version (v3.111.1). Do you have an older version of the `pulumi-language-yaml` binary? I'm going to go ahead and close this, but feel free to re-open if you're still hitting it.
