### ISSUE TITLE
This whole thing is a bug

### ISSUE THREAD

**Issue by ElGatoLoco** [pulumi/pulumi#15641]
### What happened?

The amount of suffering for anything beyond basic "happy path" use cases is unbelievable. Try funneling more money from marketing to development and fixing shit.

### Example

For fuck sake, if you have two resources, where one depends on each other, and both are marked for deletion, just fucking delete the one that doesn't depended on anything first! I wish I'm actually a decent programer so I could go and fix shit in your project, but I'm not, so I can just complain and go visit a psychiatrist. But still, you raised tens of fucking millions, how about you hire people who actually know some shit about fuck and make shit work?

### Output of `pulumi about`

There is no "about" for this. During the last month I wanted to smash my laptop against the wall multiple times, just because someone thought that using Pulumi is a good idea.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
We haven't heard back and still have no concrete example of how to reproduce the problem, so I'll go ahead and close the issue.

With all due respect @ElGatoLoco, your language here is not appropriate. Please try to stay constructive and respectful and follow our [code of conduct](https://github.com/pulumi/pulumi/blob/master/CODE-OF-CONDUCT.md). We can not tolerate such behavior towards Pulumi employees or community.

**Comment by ElGatoLoco** [comment]
Hey, sorry for the late reply, I've been busy lately. I apologize for the harsh language, it wasn't aimed at any person in particular, but rather to the state of affairs in general. I guess Pulumi isn't the only one, but it definitely is a very good example of what production software shouldn't look like. 

Over the course of the last couple of months I've spent more time battling Pulumi quirks than actually solving real problems - if it was an issue or two, I'd gladly live with it, but it's been dozens. Sure, you're having ambitious goals, but I find it sad to have so many people buy the hype only to get frustrated and migrate away after months of constant struggle.
