### ISSUE TITLE
Stack preview using automation API sometimes fails because of failure to deserialize SummaryEvent

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi#15652]
### What happened?

When executing a preview using the Python automation SDK, sometimes there is a failure while [deserializing the engine events log file](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/automation/_stack.py#L963) that the automation API creates. That ultimately raises the exception with the message [`summary event never found`](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/automation/_stack.py#L444) which makes sense because there was a JSON error. The stack preview itself actually succeeds when I look at the output log that I capture using the `on_output` callback and there are no other errors from the provider I am using.

This issue does not happen consistently and I don't have an efficient way to collect more information as to why the engine event log file fails to deserialize. I have also not been able to figure out a pattern for it just yet. I would like to propose adding some additional debugging around the deserialization code to help with collecting more information.

The unhandled exception is `json.decoder.JSONDecodeError: Expecting ',' delimited: line 1 column 170 (char 169)`.

### Example

Caused by an unhandled exception from https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/automation/_stack.py#L963 which then causes https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/automation/_stack.py#L444 because there is no summary event.

### Output of `pulumi about`

I've only encountered this issue in CI thus far and not in any of my local executions which has made this particularly harder to diagnose and collect more information. The version of the Pulumi Python SDK is `3.107.0`, so it's fairly recent.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Note we've seen I think exactly the same thing in the nodejs Automation API, and I think in the dotnet one as well.

**Comment by tgummerer** [comment]
Here's the issue for NodeJS: https://github.com/pulumi/pulumi/issues/6768

**Comment by tgummerer** [comment]
The issue I've been chasing in https://github.com/pulumi/pulumi/issues/15235 also seems potentially related to this.
