### ISSUE TITLE
Pulumi schema for resource references

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi#15681]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
As a component provider author, I would like to define an output property called `resources` whose type would be an array of resources that were produced by the component. The provider code would assumedly return `ResourceReference` property values.  At the SDK level, I would expect the `resources` property to have a type of `ResourceArray`.

### Workarounds
Use `pulumi.json#/Any`:
```json
            "properties": {
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "pulumi.json#/Any"
                    },
                    "description": "Resources created by the component."
                }
            }
```

**Comment by EronWright** [comment]
This is related to [this](https://pulumi.slack.com/archives/C8R654Y6S/p1710373360946809?thread_ts=1710356943.863009&cid=C8R654Y6S) conversation.

**Comment by lukehoban** [comment]
I expect we would accomplish this by adding one (or three) new built in types to Pulumi schema:
1. `pulumi.json#/Resource`
2. `pulumi.json#/CustomResource`
3. `pulumi.json#/ComponentResource`

And then add support for these in codegen for each language.
