### ISSUE TITLE
Stuck running the Pulumi tour "preview" step

### ISSUE THREAD

**Issue by RobHoman** [pulumi/pulumi#1568]
I'm attempting to run the tour that begins here (https://pulumi.io/tour/basics-programs.html)

Pulumi installed successfully

And I was able to create the aws-go project just fine: `pulumi new aws-go --dir ahoy-pulumi`

But trying to run pulumi preview fails:
```
➜  ~/Programming/scratch/pulumi/ahoy-pulumi pulumi preview
Previewing update of stack 'ahoy-pulumi-dev'
Previewing changes:

     Type    Name    Plan          Info
 *   global  global  no change     1 error

Diagnostics:
  global: global
    error: an unhandled error occurred: problem executing program (could not run language executor): exec: "ahoy-pulumi": executable file not found in $PATH
```

I've been trying to troubleshoot this for a while and I'm lacking on clues. Could this have something to do with my go installation not matching a Pulumi assumption? Is there anyway this error message could be more descriptive to help lead me to the source of the issue?

**Comment by ellismg** [comment]
> Could this have something to do with my go installation not matching a Pulumi assumption?

Possible.  The go language plugin works by taking the name of your project and just trying to run a binary with that name.  This means two things need to have happened:

1. You need to run `go install` to get your program built and installed.
2. You need to ensure that go's bin folder is on your $PATH.

Out of the box, (2) is not true.  So you'll want to ensure you add it to your path (e.g. export `PATH=$(go env GOPATH)/bin:$PATH`)

You should be able to run `which ahoy-pulumi` and see that a program is found.

If you do have `ahoy-pulum`i on your `$PATH` and things still aren't working. We'll have to continue digging. 

> Is there anyway this error message could be more descriptive to help lead me to the source of the issue?

Assuming the above is the issue, we could be a little more pragmatic in the error (maybe with something like "did you `go install` it?"?

I suspect the easiest place to do this would be in https://github.com/pulumi/pulumi/blob/master/sdk/go/pulumi-language-go/main.go#L95, perahps doing an exec.LookPath to ensure `command` is on the path.  If you're interested in contributing, this might be a good place to start.  But if not, that's great too.

Do let me know if the above helped, if not, we'll keep digging.

**Comment by joeduffy** [comment]
I'm going to close under the assumption that this was a PATH issue, but please do reopen if we missed something! I hope you were able to get Pulumi Go up and running after all :smile:
