### ISSUE TITLE
ESC feature does not expose `:` delimitted variables from `pulumiConfig`

### ISSUE THREAD

**Issue by dan-cooke** [pulumi/pulumi#15702]
### What happened?

Following the documentation exactly as written here https://www.pulumi.com/docs/esc/environments/#using-environments-with-pulumi-iac

You would believe that you can expose `:` delimitted variables, as in this example they expose `aws:region` to the pulumi config

However, these variables are no exposed to the runtime

### Example

1. `pulumi env init production`
2. `pulumi env edit production`
3. Paste the following
```yaml
values:
  pulumiConfig:
    api:domain: "test"
    ui:domain: "test"
````
4. Save
5. `pulumi stack init production`
6. `touch Pulumi.production.yaml`
7. Paste the following
```yaml
name: myapp
runtime: nodejs
description: Infrastructure for web application
environment:
  imports:
    - production
```
8. Create a index.ts with the following contents
```.ts
const config = new pulumi.Config('api');

config.require('domain')

```
9. You can also try with `config.require('api:domain')`
8. `pulumi up`

```
 Missing required configuration variable 'api:domain'
```

### Output of `pulumi about`

```
CLI
Version      3.107.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       arch
Version
Arch     x86_64

This project is written in nodejs: executable='/run/user/1000/fnm_multishells/219866_1710498776133/bin/node' version='v20.9.0'

Current Stack: templi/templi-infra/prod

Found no resources associated with prod

Found no pending operations associated with prod

Backend
Name           pulumi.com
URL            https://app.pulumi.com/dan-cooke
User           dan-cooke
Organizations  dan-cooke, templi
Token type     personal

```

### Additional context

It would be nice for organisational purposes to expose these variables,

A structure like this would be very nice

```.yml
dns:
    uiDomain: 'something'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pgavlin** [comment]
I cannot repro this.

One question re: this bit:

> 7. Paste the following
> ```yaml
> name: myapp
> runtime: nodejs
> description: Infrastructure for web application
> environment:
>   imports:
>     - production
> ```

Should I paste this into the `Pulumi.production.yaml` file or the `Pulumi.yaml` file? I've pasted the environment bit into `Pulumi.production.yaml`.

**Comment by dan-cooke** [comment]
Apologies - I swore I closed this with comment

this is a non issue - it comes from a misunderstanding of the syntax on my part

I was confusing : for . Property access
