### ISSUE TITLE
Let stack config override main attribute

### ISSUE THREAD

**Issue by tai-nd** [pulumi/pulumi#15710]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I have issues structuring my Pulumi project just like https://github.com/pulumi/pulumi/issues/8402.
My desired:
```
├── Pulumi.yaml
├── minio
│   ├── minio.ts
│   └── package.json
├── cloudflare
│   ├── cloudflare.ts
│   └── package.json
├── pulumi-stacks
│   ├── Pulumi.cloudflare.yaml
│   └── Pulumi.minio.yaml
├── package.json
```

I believe that my problems would be solved if Pulumi allowed overriding the `main` attribute in stack config (Pulumi.cloudflare.yaml, Pulumi.mino.yaml). This will make structuring Pulumi projects much more flexible and probably improve the situation in https://github.com/pulumi/pulumi/issues/8402 too.

**Comment by Frassle** [comment]
I think we'd normally expect this to be separate projects with their own Pulumi.yaml files rather than using one project and overriding main per stack.
