### ISSUE TITLE
Python resources must set outputs received from engine

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1576]
Currently it does not:

https://github.com/pulumi/pulumi/blob/c2b2f3b117963bbddf869c483a4ee1e8d45475f7/sdk/python/lib/pulumi/resource.py#L76-L79

`tfgen` generated providers accomplish this by manually setting properties in the custom resource's constructor, which probably not what it should be doing (the `Resource` constructor should be doing this).

**Comment by lukehoban** [comment]
Looks like our current approach is that we always override this in CustomResource implementations, which seems fine (and we'll likely have to do the same in other strongly typed languages).  I think we can keep this as is for now in Python.
