### ISSUE TITLE
[auto/go] Installed pulumi command isn't used

### ISSUE THREAD

**Issue by JTarasovic** [pulumi/pulumi#15796]
### What happened?

The automation API for go doesn't use the installed pulumi command.

### Example

1. Make sure `pulumi` does not already exist on `PATH`
2. Clone https://github.com/pulumi/automation-api-examples
3. cd go/cli_installation
4. go run main.go

```
Installing pulumi into /tmp/cli_installation_exmple3856510536
Failed to set up a workspace: failed to select stack: exec: "pulumi": executable file not found in $PATH
code: -2
stdout:
stderr:
```

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Here's a test that fails:

```go
func TestUpsertStackInlineSource(t *testing.T) {
	t.Parallel()

	dir, err := os.MkdirTemp("", "automation-test-")
	require.NoError(t, err)
	defer os.RemoveAll(dir)
	version := semver.Version{Major: 3, Minor: 98, Patch: 0}

	pulumiCommand, err := InstallPulumiCommand(context.Background(), &PulumiCommandOptions{Root: dir, Version: version})
	require.NoError(t, err)

	deployFunc := func(ctx *pulumi.Context) error {
		return nil
	}

	ctx := context.Background()

	projectName := "autoInstall"
	stackName := ptesting.RandomStackName()

	_, err = UpsertStackInlineSource(ctx, stackName, projectName, deployFunc, Pulumi(pulumiCommand))
	assert.NoError(t, err)
}
```

We do attempt to set the `PATH` to the binary that was installed, but that doesn't appear to help with actually finding the `pulumi` binary to run:

https://github.com/pulumi/pulumi/blob/024ff023f182a515b62487836eacca59d1acd8a8/sdk/go/auto/cmd.go#L268-L275

If I apply the following patch, the test succeeds:

```diff
diff --git a/sdk/go/auto/cmd.go b/sdk/go/auto/cmd.go
index a9d807e92..34182fa58 100644
--- a/sdk/go/auto/cmd.go
+++ b/sdk/go/auto/cmd.go
@@ -265,13 +265,9 @@ func (p pulumiCommand) Run(ctx context.Context,
        // all commands should be run in non-interactive mode.
        // this causes commands to fail rather than prompting for input (and thus hanging indefinitely)
        args = withNonInteractiveArg(args)
-       cmd := exec.CommandContext(ctx, "pulumi", args...)
+       cmd := exec.CommandContext(ctx, p.command, args...)
        cmd.Dir = workdir
        env := append(os.Environ(), additionalEnv...)
-       if filepath.IsAbs(p.command) {
-               pulumiBin := filepath.Dir(p.command)
-               env = fixupPath(env, pulumiBin)
-       }
        cmd.Env = env

        var stdout bytes.Buffer
```

**Comment by justinvp** [comment]
@julienp, any reason why we shouldn't do something like my patch above?

**Comment by julienp** [comment]
AFAIK we still need the fixupPath to happen so that plugins are loaded from the same place as the CLI installation we want to use.

We can use `p.command` instead of `"pulumi"` as the command name, but I am confused why that's necessary.

**Comment by Frassle** [comment]
Is `p.command` somehow _not_ an absolute path, and so not hitting the `if filepath.IsAbs(p.command)` part?

**Comment by justinvp** [comment]
> Is `p.command` somehow _not_ an absolute path, and so not hitting the `if filepath.IsAbs(p.command)` part?

In the test above which repros the problem, it does hit the `if filepath.IsAbs(p.command)` path, and it is added to the PATH in cmd.Env, but still fails.

**Comment by Frassle** [comment]
Maybe the command lookup doesn't respect the PATH being set for that command? So we still need the envelope change but also use the full path for exec not "pulumi"

**Comment by julienp** [comment]
> Maybe the command lookup doesn't respect the PATH being set for that command? So we still need the env change but also use the full path for exec not "pulumi"

Oh of course ... the env we set on command is the env for that command, but the current process has a different env (and so a different PATH), and will use its own env/PATH to lookup the command.
