### ISSUE TITLE
Where are the binary releases?

### ISSUE THREAD

**Issue by colemickens** [pulumi/pulumi#1579]
For others, from the "installer" script:

```
VERSION=$(curl --fail --silent -L "https://pulumi.io/latest-version");
TARBALL_URL="https://get.pulumi.com/releases/sdk/pulumi-v${VERSION}-${OS}-x64.tar.gz"
```

So, for me, the current latest release is here: https://get.pulumi.com/releases/sdk/pulumi-v0.14.0-linux-x64.tar.gz

It'd be great if these were:
1. linked from the README
2. linked from the site
3. were included in the GitHub tagged releases

Maybe they are and I missed it?

I think these are going to be far more appetizing to Pulumi's intended audience than an opaque `curl|sh` "installer".

**Comment by ellismg** [comment]
You can find the latest version at https://pulumi.io/install/ (we have the easy install at the top, but you can scroll down to find download links).  We also have previous versions listed at https://pulumi.io/install/changelog.html#all-versions

We’ll keep that list updated as we release new versions.

The feedback to add the most recent version to the README and adding stuff to the tagged releases is great.  I’ll do that.

**Comment by colemickens** [comment]
Gah, I'd even see that page before, but somehow wasn't finding my way back to it. And yet when I go now to pulumi.io, I see there's clearly an "install" button that I can infer would take me to manual download.

My bad, thanks!
