### ISSUE TITLE
General CLI feedback from a new user

### ISSUE THREAD

**Issue by colemickens** [pulumi/pulumi#1580]
Hi. Some quick notes from getting started with Pulumi locally. It's arguably all subjective, feel free to close, just wanted to offer it up.

1. I jumped in with `pulumi stack init`, but that's not right. It gives an opaque error about `Pulumi.yaml` missing. Maybe it could encourage me to run `pulumi new` first, and mention that doing so creates a "project" (since it's not part of the name, and helps establish that a "project" will own "stack"s without me needing to reconsult docs).
2. The `pulumi new` wizard was a bit off-putting and buggy (the interactive template selector was broken in a session [konsole-256color -> bash -> ssh -> bash]). I'd much prefer it just took `--project-name`, `--template-name|--template-uri` to configure the project. Additionally, I'd expected `pulumi new projectName` to work, but instead, it treated `projectName` as the name of a template. Similarly, the wizard prompts for the template first, which seems weird to me.
4. `pulumi new` dropped all of the files in `PWD` rather than in `./{project-name}`. This is counter  intuitive to other tools that handle `new` as meaning a new dir and `init` as implying the `PWD`.
5. `pulumi` should check up front for `npm` if I select the typescript template, maybe even fall back to `yarn`? :)

Also, generally, the command structure is mentally confusing to me. For example,
- `archive` unclear what level its acts on? the project/the stack/etc?
- `config` same question
- `destroy` acts on a stack
- `new` acts on projects
- `login` affects global state
- `update` acts on a stack
- `logs` presumably acts on a stack, or a resource in a stack?

I guess this was maybe intentional to be simpler, but something like this would be easier for me to understand quickly:
- `pulumi project [new|ls|use]` (`|config` ?)
- `pulimi stack [new|ls|use|cancel|preview|update|destroy] that act within hte context of `--project` or the current selected `project`, if there's one
- `pulumi account [login|logout]`
- `pulumi plugin` (I assume the plugins are global to the pulumi install)

This again would've helped me infer that I probably need a `project` to contain my `stack`.

**Comment by hausdorff** [comment]
FWIW I also agree with pretty much all of this. cc @lukehoban @joeduffy

**Comment by joeduffy** [comment]
This is really excellent feedback, @colemickens, thank you.

We should definitely take a step back and do a relook, since we arrived here mostly organically.

As we do take a pass at this, and in the event that we're going to deprecate and move to a new scheme here, I'd also suggest revisiting the verbs themselves.  For example: we use `ls` which feels cleverly UNIXy but inconsistent with all other commands; I've personally never liked `update` because it begs the question of "update _what_" (the CLI itself?) and is a little funny the first time you run it (update ... nothing) -- which is why we support the `up` alias; etc.

**Comment by joeduffy** [comment]
I should also note, my only reluctance about parenting some of these commands to `stack` is simply that `update`, etc. are the most frequently used commands by a factor of, say, 10x.  Requiring an extra word in every CLI invocation feels unfortunate to me.  And yet, I simultaneously agree about the confusion it causes to not do so.  I suppose aliases/completions could help offset this.

**Comment by hausdorff** [comment]
What about a compromise between the two, keeping verbs that everyone understands (_e.g._, `apply` and/or `update`), but moving things like `destroy` -> `stack destroy`?

**Comment by lindydonna** [comment]
>  I suppose aliases/completions could help offset this.

That would be nice--maybe `pulumi update` is just an alias for `pulumi stack update`. I like @hausdorff's suggestion of changing the command to `pulumi stack destroy`, but not aliasing.

**Comment by ellismg** [comment]
https://github.com/pulumi/pulumi/issues/2482 tracks adding aliases for the stack specific stuff.  I'm sure that if we do add them we wouldn't remove any of our top level verbs (since they are often on the inner loop when doing pulumi stuff).
