### ISSUE TITLE
Project gets stripped out of the stack name when `pulumi stack ls --json --all` is ran from inside a project directory

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#15806]
### What happened?

I tried to use the Project name of Catalog, and when I went to go query the stack using `pulumi stack` or `pulumi stack ls --json --all` I noticed that the stack name didn't have the normal Org/Project/Stack format. Instead it was Org/Stack.

### Example

This is what comes back 
```json
  {
    "name": "team-ce/zbuchheit",
    "current": true,
    "url": "https://app.pulumi.com/team-ce/Catalog/zbuchheit"
  }
```
instead of what I would expect which would be 
```json
  {
    "name": "team-ce/Catalog/zbuchheit",
    "current": true,
    "url": "https://app.pulumi.com/team-ce/Catalog/zbuchheit"
  }
```

### Output of `pulumi about`

```
CLI          
Version      3.105.0
Go Version   go1.21.6
Go Compiler  gc

Plugins
NAME  VERSION
go    unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.21.6 darwin/arm64'

Current Stack: team-ce/Catalog/zbuchheit

Found no resources associated with team-ce/zbuchheit

Found no pending operations associated with team-ce/zbuchheit

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/zbuchheit-pulumi-corp
User           zbuchheit-pulumi-corp
Organizations  zbuchheit-pulumi-corp, team-ce, pulumi
Token type     personal
```

### Additional context

This functionally hasn't caused an issue except when querying stacks. Otherwise it appears this isn't causing an issue but I would assume could cause unintended issues later on. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
What issue is it causing? It's pretty much always behaved like this.

https://github.com/pulumi/pulumi/blob/89cd536cb987fa8c7c78efb6b0a60cb897133f70/pkg/cmd/pulumi/stack_ls.go#L221

https://github.com/pulumi/pulumi/blob/89cd536cb987fa8c7c78efb6b0a60cb897133f70/pkg/backend/httpstate/stack.go#L53-L77

For json output, I can see an argument for not eliding certain parts, and always showing the fully qualified name. Though, that could potentially break someone that's somehow depending on it to be the elided format.

**Comment by zbuchheit** [comment]
Updated the title to avoid confusion. After a discussion with @justinvp , closing this issue as it is by design and not functionally causing an issue. I originally opened it out of a precaution when I noticed it with a user.
