### ISSUE TITLE
pulumi.Config('projectName'); Why projectName?

### ISSUE THREAD

**Issue by colemickens** [pulumi/pulumi#1581]
Why does Pulumi need to know the project? Does it not inherently know the Project from the context it's executing in? 

Especially since the configuration values are not defined by the project, but rather by seemingly just existing on the Stack?

If anything, I'd expect to have to input the Stack name. But then, I'm even more confused after skimming through: https://github.com/pulumi/pulumi/issues/1556

**Comment by colemickens** [comment]
Interesting, `pulumi stack ls` doesn't actually seem to be filtering by project. I have a new pulumi project and `pulumi stack ls` still shows me my other stacks. (I've checked that the names in Pulumi.yaml differ.)

**Comment by ellismg** [comment]
> Why does Pulumi need to know the project? Does it not inherently know the Project from the context it's executing in?

The major issue is that there's a split between configuration for your project and the configuration for a library you consume.  For example, in pulumi-cloud, we have a [configuration setting for the cloud you want to target, `cloud:provider`](https://github.com/pulumi/pulumi-cloud/blob/9c81b0be41447c7086e7c428a410df009c4a110f/api/index.ts#L25-L46).

In this case, we want the name of the part of the configuration bag to be invariant across any project that happens to consume it.

However, as you've noticed, for your application itself, `new pulumi.Config(pulumi.getProject())` is exactly what you want. In fact, the above pattern was actually "discovered" by an early customer and surprised all of us.

I think it may be reasonable to say that `new pulumi.Config()` is shorthand for `new pulumi.Config(pulumi.getProject())` and just require folks who are writing reusable components be explicit.  @lukehoban, what do you think about this?  Too much magic?

We have talked about trying to make `pulumi.Config()` just do the right thing for both application and library code, but we've never come to a satisfying position on how to actually detect the correct context robustly.

**Comment by ellismg** [comment]
> (Related to #1556: Interesting, pulumi stack ls doesn't actually seem to be filtering by project. I have a new pulumi project and pulumi stack ls still shows me my other stacks. (I've checked that the names in Pulumi.yaml differ.))

That is surprising and sounds like a bug.  `pulumi stack ls` should, by default, filter to the current project, and only show all of your stacks with `pulumi stack ls --all`.  Locally, I do the the filtering.  I'll open another issue and tag you to try to get more details.

**Comment by colemickens** [comment]
Hm, I typed a bunch but it was mostly me thinking aloud. It seems like some sort of global state, which smells to me (and makes me wonder, can I use `pulumi-cloud` cross-cloud right now? or should that be separate projects? but what if I want to deploy a multi-cloud app with Pulumi?)

In this case, if it's possible for the runtime to know the current project, defaulting `new pulumi.Config()` to the current project would make sense to me.
