### ISSUE TITLE
pulumi stack ls doesn't filter to a project in some cases

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1582]
In #1581, @colemickens notes that there was a case where `pulumi stack ls` does not filter based on the current project.  Which is a bug.  You should explicitly have to pass `--all` to see stacks from other projects.

I couldn't reproduce this with a small project of mine, so there must be something subtle going on here.

@colemickens Is there anything interesting about your setup here?

**Comment by joeduffy** [comment]
Unable to repro this, if we can figure out detailed instructions, let's re-open.
