### ISSUE TITLE
Change plugin download and installation to use engine events for progress

### ISSUE THREAD

**Issue by PollRobots** [pulumi/pulumi#15821]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently the plugin download mechanism reports progress using stdout, this causes a variety of odd behavior and doesn't work well with the ProgressDisplay used for showing other progress.

This was a factor in #15668 and is causal for #14250 

### Affected area/feature

CLI

**Comment by lunaris** [comment]
Fixed in #17019
