### ISSUE TITLE
unknown provider after upgrading Pulumi urn:pulumi:dev::api::pulumi:providers:aws::default_6_25_0

### ISSUE THREAD

**Issue by johnnybenson** [pulumi/pulumi#15831]
### What happened?

Can no longer deploy after upgrading Pulumi

### Example

```sh
➜  api git:(main) ✗ pulumi up
Please choose a stack, or create a new one: enneract/dev
Previewing update (enneract/dev)

error: could not deserialize deployment: snapshot integrity failure; refusing to use it: resource urn:pulumi:dev::api::aws:lb/targetGroup:TargetGroup::api refers to unknown provider urn:pulumi:dev::api::pulumi:providers:aws::default_6_25_0::8fe6bdcd-b46f-48a3-9c66-4878651c3e94
```

### Output of `pulumi about`

```sh
➜  api pulumi about
CLI
Version      3.112.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.28.1
aws-native  0.100.0
awsx        2.6.0
docker      4.5.3
docker      3.6.1
github      6.2.0
nodejs      unknown

Host
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in nodejs: executable='/Users/johnny/.nvm/versions/node/v20.10.0/bin/node' version='v20.10.0'

Backend
Name           pulumi.com
URL            https://app.pulumi.com/ENNERACT_ACCOUNTS
User           ENNERACT_ACCOUNTS
Organizations  ENNERACT_ACCOUNTS, enneract
Token type     personal

Dependencies:
NAME                VERSION
@pulumi/aws         6.28.1
@pulumi/aws-native  0.100.0
@pulumi/awsx        2.6.0
@pulumi/github      6.2.0
@pulumi/pulumi      3.112.0

Pulumi locates its logs in /var/folders/c4/k8tw38mx4h56tscysmh4073w0000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

- Per the docs, I am using the package-wide provider, not defining one explicitly.
https://www.pulumi.com/registry/packages/aws/api-docs/provider

- Downgrading to `@pulumi/aws` to `v6.25.0` does not resolve the issue
 
### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@johnnybenson, can you share what exactly you upgraded and the versions before/after? I assume you upgraded `@pulumi/aws` from v6.25.0 to v6.28.1, and `@pulumi/pulumi` and the Pulumi CLI to v3.112.0 from what version?

**Comment by johnnybenson** [comment]
@justinvp yep, I went from `"@pulumi/aws": "^6.25.0"` to `"@pulumi/aws": "^6.27.0"`.
and `v3.109.0` to `v3.111.1`.

Downgrading doesn't seem to help. I was relying on the package-wide provider so no changes to my code / config outside of upgrading.

Thanks for taking a look, any further insights would be much appreciated.

**Comment by johnnybenson** [comment]
Ended up creating a new stack then rerouted traffic.

Used `pulumi stack rm --force` then manually destroyed the resources in AWS console to clean up this integrity issue. 🙃

Would love feedback on how to avoid this happening again in the future.

**Comment by Frassle** [comment]
> could not deserialize deployment

That looks like the deployment before this one was the one that caused the issue.
Do you know what version of pulumi _wrote_ the deployment before you updated and hit this error?

**Comment by johnnybenson** [comment]
```
 - uses: pulumi/actions@v5
        with:
          command: up
          work-dir: ./stacks/api
...
```

✅ `"@pulumi/aws": "^6.25.0"` + `Pulumi 3.109.0`
![image](https://github.com/pulumi/pulumi/assets/238022/f590cb1b-701e-4f26-acd2-b00f7bbb3a6f)

❌ `"@pulumi/aws": "^6.27.0"` + `Pulumi 3.111.1`
![image](https://github.com/pulumi/pulumi/assets/238022/9e9f9330-dc4c-4aa1-ac18-0250600bd3a5)

----

The Pulumi version in the GitHub action is not explicitly set and updates week over week. The deploys are automated through the action. Occasionally, we manually run `pulumi up` from our local machine—if the version of Pulumi **does not match** the version run in the GitHub action, could that cause some trouble?

Between the successful deploy and the failed one, `@pulumi/aws` was upgraded three times `6.25.0` `6.25.1` `6.27.0`

We've been using Pulumi for about 8 months, this is the first time something like this has happened.

**Comment by johnnybenson** [comment]
Yes

**Comment by Frassle** [comment]
OK thanks I think this was probably an issue with the state 3.109 wrote out, have to look back in code history a bit more see if anything looks suspect.

**Comment by Frassle** [comment]
Just checking is there any chance an update was done on this stack using the `--targets` feature?

**Comment by johnnybenson** [comment]
Yes, the GitHub action looks something like this:

```yml
      - uses: pulumi/actions@v5
        with:
          command: up
          target: |
            urn:pulumi:dev::api::awsx:ecs:FargateService::...
            urn:pulumi:dev::api::awsx:ecs:FargateService::...
            urn:pulumi:dev::api::awsx:ecs:FargateService::...
            urn:pulumi:dev::api::awsx:ecs:FargateService::...
          target-dependents: true
```

**Comment by Frassle** [comment]
I think this specific state corruption was a bug in 3.109 to 3.111.1 and might have been fixed in 3.112.0 (https://github.com/pulumi/pulumi/pull/15716). 

What's odd is that we'd always seen this state corruption manifest as a panic after writing out the bad state, but the user reports we've got for this are now suggesting there's a way to hit the same state corruption but without the expected panic.

Not going to close this off yet, but there's a chance it's not actually a problem anymore.

**Comment by Frassle** [comment]
Ah found it!
Yes this is the same as https://github.com/pulumi/pulumi/pull/15716. But if you still have a resource using the old version of the provider (which awsx could be causing as it sets it's own provider versions) you don't see the panic, you just get the state corruption.
The state corruption issue isn't possible to hit on 3.112 as we recognise the situation earlier and error out.
I do think you're going to have issues doing your next provider upgrade if you always run with --targets because the engine can't currently correctly handle a provider upgrade in a targeted run.
If that's a blocker I'd suggest opening a new issue for us to look into if we can correctly support that use case.

**Comment by johnnybenson** [comment]
That's great. Yes, I do currently run the automated deploys with targets through a Github Action.

The workaround currently, when automated deployment fails, assuming the stack doesn't become corrupted, a manual deploy without targets seems to update provider versions okay and it's possible to resume automated deployments after that.

It does feel like this should _just work_ as far as my expectations as an end-user. Thanks for the deep look at the issue!
