### ISSUE TITLE
Gesture to copy configuration from one stack to another

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1583]
This is a quality of life improvement.

Pulumi makes it very easy to spin up new stacks, which is great.  However, when you create a new stack, you must configure it "from scratch".  The tempting thing to do is to copy an existing `Pulumi.<stack-name>.yaml` file and make the minor edits.  After all, it's just a file right?

Unfortunately, if you are using any encrypted configuration values, things quickly go off the rails.  Since configuration values are encrypted with a per stack key, simply copying the file will not do the right thing.  So, at a minimum, you need to reset all of the secret configuration values, which is a chore.

We should consider a gesture like:

`pulumi config copy [source-stack-name] [destination-stack-name]` which copies all of the configuration values from the source stack to the destination stack.  We could, choose to further augment this with something like a  `--value` flag which would let you specify one or more values to copy.

In the case where we would overwrite values in the destination stack, we could  issue a warning and prompt the user to answer yes or no.

**Comment by kimdhamilton** [comment]
I will use this feature all the time

**Comment by leezen** [comment]
Related: #481
