### ISSUE TITLE
xTransforms does not work to set custom timeouts for awsx.ecs.FargateService

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#15843]
### What happened?

@zbuchheit suggested to try xTransforms and stack transforms for https://github.com/pulumi/pulumi-awsx/issues/1252 but it does not seem to work. It seems to work the same way as the normal transforms in `pulumi preview` that is fails to modify the custom timeout for the underlying resource.

### Example

See ts-lb-with-subnets in pulumi-awsx. Try the xTransforms option instead of the current tranformations option (that does not work). 

Since ECS service is actually a little slow to provision what I've been testing with is

```
PULUMI_DEBUG_GRPC=$PWD/preview.json pulumi preview
```

And trying to look at RegisterResource or Create calls for ecs:Service to see if it get the custom timeout.
Run `pulumi preview`, observe customTimeouts passed to RegisterResource and Create calls in the log. 

### Output of `pulumi about`

```
CLI          
Version      3.111.1
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.28.2
awsx    2.6.0
docker  4.5.3
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  14.4
Arch     x86_64

This project is written in nodejs: executable='/Users/t0yv0/bin/node' version='v18.18.2'

Current Stack: anton-pulumi-corp/ts-lb-with-subnetIds/repro2

Found no resources associated with repro2

Found no pending operations associated with repro2

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/anton-pulumi-corp
User           anton-pulumi-corp
Organizations  anton-pulumi-corp, moolumi, pulumi
Token type     personal

Dependencies:
NAME            VERSION
@types/node     18.19.28
@pulumi/aws     6.28.2
@pulumi/awsx    2.6.0
@pulumi/pulumi  3.112.0

Pulumi locates its logs in /var/folders/gk/cchgxh512m72f_dmkcc3d09h0000gp/T/com.apple.shortcuts.mac-helper// by default

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Yup this is a bug in parent lookup when searching for transforms. The engine wasn't recording component resources as parents.
