### ISSUE TITLE
Example converter adds trailing whitespace

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi#15852]
### What happened?

In our latest pu/pu upgrade, one of the examples started generating trailing whitespace:

https://github.com/pulumi/pulumi-terraform-bridge/pull/1805/files#diff-7d9eadaa17c0d9d669900654bb8303a669fe6880b27407aaa86aa83e5c6baa35

### Example

`cd pkg/tfgen && go test -run TestConvertExamples/aws_lambda_function`

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Looks like it's due to https://github.com/pulumi/pulumi/pull/15773. I see the trailing spaces in the expected output in that PR.
