### ISSUE TITLE
Encountered error when switching from `RegisterStackTransformation` to `XRegisterStackTransform`

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#15881]
### What happened?

When attempting to use `XRegisterStackTransform` on a stack that previously used `RegisterStackTransformation` I encounter the following error

> waiting for RPCs: rpc error: code = Unknown desc = could not parse provider reference: urn:pulumi:zbuchheit::aws-eks-go::pulumi:providers:aws is not a valid URN<{%reset%}>)

### Example

TODO

### Output of `pulumi about`

TODO

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This looks like 'providers' not serialising correctly. I think some parts assume it's a ref and others a urn, should be a case of just making sure they're all consistent.

**Comment by tomachristian** [comment]
I'm still getting this on 3.66.1 on .NET

```
Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="could not parse provider reference: urn:pulumi:local::project::pulumi:providers:kubernetes is not a valid URN")
```

Not actually changing any args, just returning them as they are from the transform. If I return `null`, it works.

**Comment by kmdlcp** [comment]
I also still have this issue
