### ISSUE TITLE
Allow a user to have a "default team" in the same way they can have a "default org"

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#15897]
If I set a default org then I don't have to run `pulumi stack init {orgname}/{stackname}` I can just run `pulumi stack init {stackname}`. 

A default team would allow me to do either `pulumi stack init {stackname}` or `pulumi stack init {orgname}/{stackname}` and it would add the `--team` with whatever I've set as the default team value. In other words, auto-assign a new stack to my team.

**Comment by djgrove** [comment]
Found the dupe ticket I was looking for: #10783
