### ISSUE TITLE
Add `--continue-on-error` for `destroy` to the Automation API

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#15919]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I would like to use the `--continue-on-error` flag for destroy using the automation api as I leverage the automation api for testing. 

### Affected area/feature

Automation API

**Comment by justinvp** [comment]
We're planning to expose the flag in Automation API for both `pulumi destroy --continue-on-error` and `pulumi up --continue-on-error`, once that latter feature is complete.
