### ISSUE TITLE
Resources delete should use old config

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1593]
When config changes, resources which are replaced may need the delete side of the operation to use the old configuration.  To do this safely, we will need to ensure that the configuration used to create a resoruce is maintained in the checkpoint file.  We may do this via 

For example, when changing `aws:region`, most resources will need to be replaced, and the delete operations will need to use the "old" region on the AWS provider to correctly delete the resources.

This will likely be related to https://github.com/pulumi/pulumi/issues/1221.

**Comment by joeduffy** [comment]
I had the same thought about https://github.com/pulumi/pulumi/issues/1221.  I think/hope it may just fall out as a result of doing that work.  Resource configuration will need to be recorded in the checkpoint state, as an identity of sorts (AWS resource x in region a needs to look different from AWS resource y in region b).  Our current global configuration would just work the same way.

Assuming this is true, changing the global region configuration for your program from a  to b would work the same way as if you changed the individually configured package per #1221, meaning we would see "new" resources  in b, and no resources in a, leading to their deletion.

**Comment by ellismg** [comment]
From the archives: https://github.com/pulumi/pulumi/issues/716, where we thought it was a bad idea at the time.

**Comment by lukehoban** [comment]
@pgavlin Assigning to you to track as part of 1st class providers work as that will ideally also address this issue.

**Comment by pgavlin** [comment]
Fixed with #1695.
