### ISSUE TITLE
`--target` leads to "snapshot integrity failure; refusing to use it" error

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi#15959]
### What happened?

I ran `pulumi up --target 'urn:...::aws:ecs/service:Service::ratelimit-' --target-dependents`.

The preview correctly identified the resource as being deleted, but the actual `up` returned an error for unrelated resources:

```
error: could not deserialize deployment: snapshot integrity failure; refusing to use it: resource urn:...::aws:ecs/taskDefinition:TaskDefinition::consoleTaskDefinition’s dependency urn:...::pulumi-service:infrastructure:Service$docker:buildx/image:Index::consoleImage comes after it
```

Subsequent `up`s had the same error.

I was eventually able to get past this with `up --disable-integrity-checking` -- once that succeeded everything worked as normal again.

### Example

Steps:
- 

### Output of `pulumi about`

CLI
Version      3.113.0
Go Version   go1.22.2
Go Compiler  gc

Host
OS       darwin
Version  14.1
Arch     arm64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/bryce-pulumi-corp
User           bryce-pulumi-corp
Organizations  bryce-pulumi-corp, pulumi
Token type     personal

### Additional context

Both resources have `retainOnDelete` set.

The targeted resource was expected to be deleted, because I had replaced it with a different type/provider in my program.

I exported a state file shortly before running the update with `--target`, so it might be possible to repo using that. Ping me and I can send it over.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by 1oglop1** [comment]
I have the same problem, but different resources

```typescript
const users = ['u1', 'u2']
const iamUsers = usersNames.map( u => new aws.iam.User(u, {name: u}))

// note this is not UserPolicy because it has already been attached
new aws.iam.PolicyAttachment(
  "self-management",
  {
    policyArn: selfManagePolicy.arn,
    users: iamUsers.map((u) => u.name),
  },
  {
    provider: awsFrankfurt,
  }
);
```

`pulumi up --target '**u1**' --target-dependents` won't update `self-management` 

```
CLI          
Version      3.112.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME     VERSION
aws      6.31.0
command  0.10.0
nodejs   unknown
```
