### ISSUE TITLE
Error message about non-qualified stack name not quite correct

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi#15967]
### What happened?

```
❯ pulumi stack init dev
error: If you're using the --stack flag, pass the fully qualified name (org/project/stack)
```

I’m not using `--stack`, though. I realize it may be the same thing internally, but it looks wrong.

### Example

see above

### Output of `pulumi about`

❯ pulumi about
CLI          
Version      3.113.1-dev.0
Go Version   go1.22.2
Go Compiler  gc

Host     
OS       darwin
Version  14.4.1
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@thomas11 Were you using a file state backend?

Also, it says "__If__ you're using the --stack flag", so technically it's correct :)

Should we drop the if statement and change it to "Pass the fully qualified name (org/project/stack)"?
