### ISSUE TITLE
Deletions of "pending delete" resources are not shown in preview

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1596]
When a resource deletion fails, it is marked as pending deletion, and future updates will attempt to retry the deletion. However, these deletations of "pending delete" resources are not shown during `pulumi preview`, leading to very surprising output like the following:

```
luke:~/go/src/github.com/pulumi/pulumi-aws/examples/webserver (master *)
$ pulumi update
Previewing update of stack 'twitch'
Previewing changes:

     Type                 Name              Plan          Info
 *   pulumi:pulumi:Stack  webserver-twitch  no change

info: no changes required:
      2 resources unchanged

Do you want to perform this update? yes
Updating stack 'twitch'
Performing changes:

     Type                 Name              Status                  Info
 *   pulumi:pulumi:Stack  webserver-twitch  done
 --  └─ aws:rds:Instance  baseA             **deleting failed**     2 errors

Diagnostics:
  aws:rds:Instance: baseA
    error: Plan apply failed: deleting urn:pulumi:twitch::webserver::aws:rds/instance:Instance::baseA: DB Instance FinalSnapshotIdentifier is required when a final snapshot is required

    error: update failed

---outputs:---
rdsIP: "base-a.cep6renxwgtk.us-west-2.rds.amazonaws.com"

info: no changes required:
      2 resources unchanged

Permalink: https://app.pulumi.com/lukehoban/twitch/updates/8
error: update failed
```

Most likely:
1. We should show pending deletions during preview
2. During both preview and update, we should be explicit about these pending deletions being different than other deletions (not a result of this update, but cleanup from a previous update).

Here's the update prior to the one above which shows how we can get into this state (the create side of a replacement succeeds, but then the delete side of the replacement fails):

```
$ pulumi update
Previewing update of stack 'twitch'
Previewing changes:

     Type                 Name              Plan          Info
 *   pulumi:pulumi:Stack  webserver-twitch  no change
 +-  └─ aws:rds:Instance  baseA             replace       changes: + identifier

info: 1 change previewed:
    +-1 resource to replace
      1 resource unchanged

Do you want to perform this update? yes
Updating stack 'twitch'
Performing changes:

     Type                 Name              Status                   Info
 *   pulumi:pulumi:Stack  webserver-twitch  done
 +-  └─ aws:rds:Instance  baseA             **replacing failed**     changes: + identifier, 2 errors

Diagnostics:
  aws:rds:Instance: baseA
    error: Plan apply failed: deleting urn:pulumi:twitch::webserver::aws:rds/instance:Instance::baseA: DB Instance FinalSnapshotIdentifier is required when a final snapshot is required

    error: update failed

---outputs:---
rdsIP: "base-a.cep6renxwgtk.us-west-2.rds.amazonaws.com"

info: 1 change performed:
    +-1 resource replaced
      1 resource unchanged
Update duration: 3m18.128274838s

Permalink: https://app.pulumi.com/lukehoban/twitch/updates/7
error: update failed
```

**Comment by jnancel** [comment]
Hello Luke,

Knowing that the resource is in pending delete and its replacement has already been created, I think all changes made on the pulumi configuration are applied on the new resources, not the pending ones, resulting in an impossibility of deleting those resources with pulumi.

Why is it that pulumi creates new resources before deleting old ones ? I think it's the opposite in terraform. Does it bring some kind of improvement ?

Thanks

**Comment by swgillespie** [comment]
> Why is it that pulumi creates new resources before deleting old ones ? I think it's the opposite in terraform. Does it bring some kind of improvement ?

The main advantage of this (what we call "create-before-delete", as opposed to the Terraform default you observed, "delete-before-create"), is that the actual "replacement" operation is atomic in the sense that a resource being semantically replaced with another can't be observed by other resources.

That's probably a bit unclear, but more concretely, deleting a resource before its replacement has been created results in a non-zero amount of downtime, whose length is potentially unbounded. An example of how this can go very bad is if your replacement resource is invalid and fails to create. If we deleted the resource being replaced before trying to create the resource doing the replacing, we'd have deleted one of your potentially live resources and you'll be left without the thing that got deleted.
Creating the replacement resource first will at least give you the confidence that your replacement resource is correct and exists before nuking the one you already have.

**Comment by jnancel** [comment]
In the case of a RDS like here, whether you create first or delete first, anyway you'll most probably need to send some schemas to the new DB afterwards. You might also want to have the lowest possible cost, which means deleting first. Create before or to delete before depends a lot on your use case.

Is there any way of choosing the delete-first option in pulumi ?

And again, in this case, how do you then handle the resources that are marked to be deleted when an option you forgot to set prevents them to be deleted other than using the console ?

Thanks

**Comment by lukehoban** [comment]
> Is there any way of choosing the delete-first option in pulumi ?

There is not currently, `deleteBeforeReplace` is only available on specific kinds of resources.  Opened https://github.com/pulumi/pulumi/issues/1620 to track being able to opt in to this.

> In the case of a RDS like here, whether you create first or delete first, anyway you'll most probably need to send some schemas to the new DB afterwards. You might also want to have the lowest possible cost, which means deleting first. Create before or to delete before depends a lot on your use case.

Indeed - it is not true that the "no downtime" point applies to all resources - and certainly replacements of databases are going to be quite disruptive in any case.  

> And again, in this case, how do you then handle the resources that are marked to be deleted when an option you forgot to set prevents them to be deleted other than using the console ?

This part is being tracked with https://github.com/pulumi/pulumi/issues/1597.

**Comment by jnancel** [comment]
For your information, I delete in the console the pulumi pending resources but I kept having this message : 
```
error: Plan apply failed: deleting urn:pulumi:prod::first-pulumi::aws:rds/instance:Instance::base_c: DB Instance FinalSnapshotIdentifier is required when a final snapshot is required
```
I had to `pulumi refresh` for the error to disappear. Is there not a `pulumi refresh` ran just before `preview` or `update` ? If not I think it would be good to add it.

**Comment by swgillespie** [comment]
I'll be addressing parts of this issue in M17 but I'm moving the issue out to M18 to track the complete UX of pending deletes in a preview.
