### ISSUE TITLE
No way to fix resources in "pending delete" status which cannot be deleted without property changes

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1597]
When a resource fails to delete and gets marked as "pending delete", there is no longer any way to modify the properties on the resource.  It can be the case that there is no way to delete the resources without modifying a proeprty on the resource.  This leads to it being impossible to make progress with a stack unless manual edits are made to the checkpoint via `pulumi stack export`/`pulumi stack import`.

See https://github.com/pulumi/pulumi/issues/1596 for an example of this, with `aws.rds.Instance` failing to delete due to:

```
error: Plan apply failed: deleting urn:pulumi:twitch::webserver::aws:rds/instance:Instance::baseA: DB Instance FinalSnapshotIdentifier is required when a final snapshot is required
```

This error cannot be fixed (I believe) without modifying properties on the resource in the checkpoint file.

**Comment by lukehoban** [comment]
Unfortunately, right now, I believe the only option is to `pulumi stack export > stack.json` then manually remove the pending delete resource (and also delete it in the AWS console), then `pulumi stack import < stack.json`.  

/cc @pgavlin @swgillespie Thoughts on any other ways we could improve this in the near term?

**Comment by pgavlin** [comment]
We might be able to hack around this by either a) not including a read resource in its properties' dependencies, or b) keeping track of which resources have are from reads in the engine and filtering them from dependency lists before recording them in the checkpoint. Either way we'd end up needing a new CLI/language runtime release.

**Comment by lukehoban** [comment]
> read resource

Not sure I follow how "read resources" are related to the problem here related to pending deletes?

**Comment by pgavlin** [comment]
Argh, sorry--got my contexts mixed up. I don't have a better suggestion here.
