### ISSUE TITLE
Add plugin type to JSON output of `pulumi about`

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#15992]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

A customer pre-caches resource plugin binaries via a self-hosted Artifactory within their AWS account. They use the info from `pulumi about --json` and use the data from the `plugins` section:

```json
[
  {
    "name": "aws",
    "version": "6.31.0"
  },
  {
    "name": "cloudinit",
    "version": "1.4.1"
  },
  {
    "name": "kubernetes",
    "version": "4.10.0"
  },
  {
    "name": "python",
    "version": null
  },
  {
    "name": "random",
    "version": "4.16.0"
  }
]
```

This lists all plugin types, but the customer is only interested in resource plugins.

Can you add the plugin type to this JSON output, e.g.:

```json
[
  {
    "type": "resource",
    "name": "aws",
    "version": "6.31.0"
  },
  {
    "type": "resource",
    "name": "cloudinit",
    "version": "1.4.1"
  },
  {
    "type": "resource",
    "name": "kubernetes",
    "version": "4.10.0"
  },
  {
    "type": "language",
    "name": "python",
    "version": null
  },
  {
    "type": "resource",
    "name": "random",
    "version": "4.16.0"
  }
]
```

This helps the customer only iterating the resource plugins.

### Affected area/feature

CLI command `pulumi about --json`

**Comment by Frassle** [comment]
Should this really _only_ be in the JSON output? Shouldn't we also show it in the text table output as well to be consistent.

**Comment by ringods** [comment]
While it wasn't in the customer request, I would favor the text table & json output to be consistent indeed.
