### ISSUE TITLE
[CLI][PYTHON] Pulumi CLI 3.113 and python not using `parallel` value

### ISSUE THREAD

**Issue by Morgadoooo** [pulumi/pulumi#15991]
### What happened?

Context:
We are using Pulumi on our Gitlab CI to handle deployment for more than 6 months now. We were previously using 3.112.x without any problem but we updated to 3.113.x and since then the `parallel` configuration doesn't seems to be taken fully into account. 

We defined a parallel at 10 on a xlarge gitlab saas runner and are expecting to have 10 `task` running concurrently
On 3.112.x there is no problem but when we switch to 3.113.x this week we started noticing that instead of 10 task running concurrently we are not only seeing 3/4 tasks running concurrently. 

Switching back to 3.112.x fixes the issue.

### Example

```
import os
from pathlib import Path

import pulumi
import pulumi_docker as docker

for path in Path(os.getcwd()).iterdir():
    docker.Image(
        path.name,
        build=docker.DockerBuildArgs(
            args={'BUILDKIT_INLINE_CACHE': '1', 'DOCKER_BUILDKIT': '1'},
            builder_version='BuilderBuildKit',
            context=str(path),
            dockerfile=path,
            platform='linux/amd64',
        ),
    )

```

### Output of `pulumi about`

CLI
Version      3.113.2
Go Version   go1.22.2
Go Compiler  gc

Plugins
NAME    VERSION
python  unknown

Host
OS       darwin
Version  13.2.1
Arch     arm64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/adrienmorgado
User           adrienmorgado
Organizations  adrienmorgado, skillcorner
Token type     personal

Dependencies:
NAME        VERSION
pip         24.0
setuptools  69.5.1
wheel       0.43.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
Just because of timing (#15994 was also just opened), I'm curious if this also happens in 3.113.0 and 3.113.1 if you had a chance to test that?

cc @dominikzogg  as well who opened #15994.

**Comment by Frassle** [comment]
Can you confirm if it's updating the CLI or updating the Pulumi python library or only both together that causes the reduction in parallelism?

**Comment by tgummerer** [comment]
I managed to bisect it, and it looks like https://github.com/pulumi/pulumi/pull/15895 is causing this.

**Comment by Morgadoooo** [comment]
> Can you confirm if it's updating the CLI or updating the Pulumi python library or only both together that causes the reduction in parallelism?

Changing the Pulumi python library doesn't resolve the issue, seems related to the CLI



> Just because of timing (#15994 was also just opened), I'm curious if this also happens in 3.113.0 and 3.113.1 if you had a chance to test that?
> 
> cc @dominikzogg as well who opened #15994.

We tested it on 3.113.0 and 3.113.2, if i remember correctly (CLI / python sdk) with a combinaison like 
CLI : 3.113.0 SDK: 3.112.x / 3.113.0
CLI : 3.113.2 SDK: 3.112.x / 3.113.2







> Just a note for reproduction. Just using the above script wasn't enough to make this reproduce for me. What had to happen is using the above script, creating the resources, then changing a bunch of them and then on the **update** steps this behaviour would appear.
> 
> Which I guess means that the state lock for and update step must be held longer than we thought? I'm trying to read through the change again and trying to figure out what happens, but no luck so far.

Yeah sorry for the provided example just made it by hand, but it seemed related to updating all the ressources indeed

**Comment by tgummerer** [comment]
> Yeah sorry for the provided example just made it by hand, but it seemed related to updating all the ressources indeed

No worries, the provided example was very helpful to get the reproduction started, thank you for that!
