### ISSUE TITLE
Consider a fallback import mechanism

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#16048]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

Pulumi import mechanism breaks for some TF providers.

Pulumi generates a sequence of Read, Check and Diff calls in an attempt to generate a minimum set of inputs for a resource during import as documented in https://pulumi-developer-docs.readthedocs.io/en/latest/architecture/import.html

However as it turns out some TF providers do not generate Read results that are compatible with Check (not compliant), for example a highly impactful https://github.com/pulumi/pulumi-aws/issues/2318 issue demonstrates that Read may return inputs that trigger a ConflictsWith warnings in Check. 

What could Pulumi do differently here? The suggestion would be to fallback from a precise import algorithm to an approximate one; in the case that Check is failing, instead of proceeding with these failures, take the original inputs returned by Read and continue with them to create a Pulumi program. Warn the user that the program will need manual edits before it can succeed in the next `pulumi up`. The user then is not blocked but able to make progress by editing the program.

This matches TF behavior where import copies the read results into the state and then asks the user to construct a matching program and work through the discrepancies. 

## Alternatives

We are considering some fixes in the bridge or bridged providers for this and similar issues, it might be possible to compensate for at the bridge level such as minimizing inputs until they are ConflictsWith compliant, which would lead to a better user experience in specific cases anyway.

**Comment by justinvp** [comment]
Very interesting idea! We are planning some improvements for import this quarter and this may be worth considering as part of that. cc: @Zaid-Ajaj, @Frassle

**Comment by t0yv0** [comment]
We already use a heuristic to decide if a Read is a refresh Read or Import Read indeed:

https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfbridge/provider.go#L1188

**Comment by t0yv0** [comment]
Will continue in https://github.com/pulumi/pulumi-terraform-bridge/issues/1225
