### ISSUE TITLE
Python `pulumi preview` failure with no error information

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1606]
In https://travis-ci.com/pulumi/examples/builds/78388109 we saw the following failure consistently.  There is no information about what caused the failure - so once we understand the issue we should make sure we report a useful error as well:

```
[ lumi/examples/aws-py-webserver ] Invoke '/home/travis/.pulumi/bin/pulumi preview --non-interactive --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' failed: exit status 255
[ lumi/examples/aws-py-webserver ] Previewing update of stack 'p-it-travis-job-aws-py-web-712f7991'
[ lumi/examples/aws-py-webserver ] Previewing changes:
[ lumi/examples/aws-py-webserver ] 
[ lumi/examples/aws-py-webserver ]  *  global global no change 1 error. error: an unhandled error occurred: Program exited with non-zero exit code: 1
[ lumi/examples/aws-py-webserver ]  *  global global no change 1 error
[ lumi/examples/aws-py-webserver ]  
[ lumi/examples/aws-py-webserver ] Diagnostics:
[ lumi/examples/aws-py-webserver ]   global: global
[ lumi/examples/aws-py-webserver ]     error: an unhandled error occurred: Program exited with non-zero exit code: 1
[ lumi/examples/aws-py-webserver ]  
[ lumi/examples/aws-py-webserver ] error: an error occurred while advancing the preview
[ lumi/examples/aws-py-webserver ] 
```

I cannot repro this locally, and we do not currently have the ability to run debug jobs in Travis for the examples repo where this test runs.

**Comment by swgillespie** [comment]
I've moved most Python and Go work to M18 but I'll keep this in M17 since it looks pretty bad.

**Comment by sstuddard** [comment]
I was just seeing this error. Perhaps it's the same root cause:

- new instance
- install Pulumi on instance
- copied existing Pulumi scripts
- create a new stack and try to `update` or `preview`

Turns out the Pulumi python libraries were not installed. Installation via `pip` was failing because of permissions. As a result I saw the same vague error message in the description.

**Comment by swgillespie** [comment]
Re-opening this, since the above solution is not sufficient if `import pulumi` itself fails.
