### ISSUE TITLE
We should 'Humanize' (or just round) some of our console display

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#1610]
For example, telling me that an update took ```28.1239872398712644918 seconds``` is not helpful.  Having this just say that thsi took ```28 seconds``` is more then reasonable.

**Comment by joeduffy** [comment]
I think this has been done. @CyrusNajmabadi please reopen with more details on where you're seeing this if it's still an issue.

**Comment by CyrusNajmabadi** [comment]
Hasn't been done.  Still see things like: Duration: 9.725929057s

**Comment by joeduffy** [comment]
Ah, great, when I saw "console", I thought you meant our web UI, not the CLI!

Glad to see this fixed.
