### ISSUE TITLE
pulumi prints mangled values in diff of stack outputs with url-encoded characters

### ISSUE THREAD

**Issue by rafalkrupinski** [pulumi/pulumi#16123]
### What happened?

In my production code a URL path containing %2F gets added  a "!(MISSING)" part.
When tried to write a minimal code that reproduces the issue, the string becomes "!(NOVERB)"

### Example

https://gitlab.com/mattesilver/pulumi-percent

### Output of `pulumi about`

pulumi about
CLI          
Version      3.115.0
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host     
OS       debian
Version  12.5
Arch     x86_64

This project is written in nodejs: executable='/home/matte/.nvm/versions/node/v20.12.0/bin/node' version='v20.12.0'

Current Stack: mattesilver/pulumi-percent/dev

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:dev::pulumi-percent::pulumi:pulumi:Stack::pulumi-percent-dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/mattesilver
User           mattesilver
Organizations  mattesilver
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.115.0
@types/node     18.19.31
typescript      5.4.5

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening the issue and sorry for the trouble! I was able to reproduce this behavior, but still need to dig in to understand the root cause. It looks like it has something to do with printing the value from golang using something that's expecting a format string, and go therefore attempting to parse the `%` in the string.

**Comment by rafalkrupinski** [comment]
Yeah, so in my project I was constructing a k8s ConfigMap with URL-encoded strings, and pulumi just showed me this as a change.
I didn't try to go forward with the change, so I don't know if it's just printing exported or changed values, or is it internal data handling. I'll try it later.

**Comment by justinvp** [comment]
I've confirmed that this is a bug in the code that prints the diff. The actual values aren't being changed. It has nothing to do with interpolation in the Node.js SDK. I was able to repro with a simple Python program:

```python
import pulumi

pulumi.export("path2", "%2F")
# pulumi.export("path2", "%2f")
```

Looks like a bug in `printCharacterDiff` in our diff rendering code.

https://github.com/pulumi/pulumi/blob/ff8c44f9f51a3197aca11a7632e7f7a5a431c3de/pkg/backend/display/object_diff.go#L1098

The call to `write` takes a format string, and Go is trying to parse the `%`:

https://github.com/pulumi/pulumi/blob/ff8c44f9f51a3197aca11a7632e7f7a5a431c3de/pkg/backend/display/object_diff.go#L548-L550

Switching the calls to `write` in `printCharacterDiff` to `writeVerbatim` fixes the problem.
