### ISSUE TITLE
Improve target framework support

### ISSUE THREAD

**Issue by InteXX** [pulumi/pulumi#16120]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Is there any discussion of updating the package to support newer targets, preferably .NET Standard 2.0? I'd like to consider using `Pulumi.Cloudflare`, but all of the projects in my solution target .NET 8.

**Comment by Frassle** [comment]
I'm not sure what this is asking for? All SDKs currently target net6.0 the current LTS version, and can be used without issue from net8.0 projects.

**Comment by InteXX** [comment]
Hmm, it seems I've been laboring under the false impression that targeting is strict among versions.

Apparently, that's not the case. I'll have a go of it.
