### ISSUE TITLE
Python: Getting `ValueError: <Future finished result='<redacted>'> is not in deque` errors after upgrading to v3.115.2

### ISSUE THREAD

**Issue by MJLongstreth-tiq** [pulumi/pulumi#16154]
### What happened?

Our stacks have been running without issue.  We are using the Python SDK.  We tried bumping our version from 3.113.3 to 3.115.2.  Our stack still runs, but will throw a bunch of ValueErrors that appear related to https://github.com/pulumi/pulumi/commit/52b58aebbef92c74c9ce89bc3784c7fab8472587.

### Example

```
    ValueError: <Future finished result='example'> is not in deque
    2024-05-08 20:43:58 ERROR default_exception_handler Exception in callback Output.__init__.<locals>.cleanup(<Future finis...<redacted>'>) at /opt/.venv/lib/python3.11/site-packages/pulumi/output.py:107
    handle: <Handle Output.__init__.<locals>.cleanup(<Future finis...<redacted>'>) at /opt/.venv/lib/python3.11/site-packages/pulumi/output.py:107>
    Traceback (most recent call last):
      File "/usr/lib/python3.11/asyncio/events.py", line 84, in _run
        self._context.run(self._callback, *self._args)
      File "/opt/.venv/lib/python3.11/site-packages/pulumi/output.py", line 113, in cleanup
        SETTINGS.outputs.remove(fut)
    ValueError: <Future finished result='<redacted>'> is not in deque
```

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.115.2
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.40.0
resource  harness       0.0.6
resource  newrelic      5.23.1
language  python        unknown

Host     
OS       alpine
Version  3.19.1
Arch     x86_64

This project is written in python: executable='/opt/.venv/bin/python3' version='3.11.9'

....<our stack>...

Backend        
Name           bace63f4638e
URL            azblob://<ourstorageaccount>
User           root
Organizations  
Token type     personal

Dependencies:
NAME                    VERSION
azure-identity          1.16.0
azure-keyvault-secrets  4.8.0
infra                   0.0.1
lbrlabs_pulumi_harness  0.0.6
pip                     24.0
pulumi_azure_native     2.40.0
pulumi_newrelic         5.23.1
setuptools              69.5.1
wheel                   0.43.0
```

### Additional context

Does not appear to be breaking our stack, but the ValueErrors are concerning, so staying on 3.113.3

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening the issue, @MJLongstreth-tiq, and sorry for the trouble! We'll look into it.

**Comment by justinvp** [comment]
@Frassle, my guess is we're removing from the `deque` here:

https://github.com/pulumi/pulumi/blob/bebe5a9b903ecf964629c4041ccb1389955eb530/sdk/python/lib/pulumi/runtime/stack.py#L108

And then the future completes and this runs and raises the error:

https://github.com/pulumi/pulumi/blob/bebe5a9b903ecf964629c4041ccb1389955eb530/sdk/python/lib/pulumi/output.py#L113

Wonder if we should do something like:

```python
            with SETTINGS.lock:
                try:
                    SETTINGS.outputs.remove(fut)
                except ValueError:
                    pass
```

Or check that `fut` is in the `deque` before removing it (though, that could be slower to do).
