### ISSUE TITLE
Missing constructor syntax examples for the Pulumi service provider

### ISSUE THREAD

**Issue by arunkumar611** [pulumi/pulumi#16191]
https://www.pulumi.com/registry/packages/pulumiservice/api-docs/teamstackpermission/

<img width="702" alt="image" src="https://github.com/pulumi/docs/assets/14963978/8e5a0f7e-d9d2-4687-9ce8-e446124cf553">

**Comment by justinvp** [comment]
@Zaid-Ajaj, any idea why some of the languages show "Coming soon!" for constructor syntax examples? TS, Python, Go, C# are "Coming soon", but Java and YAML are filled-in.

**Comment by Zaid-Ajaj** [comment]
The intermediate PCL program generated for `TeamStackPermission` looks like this:
```hcl
resource "teamStackPermissionResource" "pulumiservice:index:TeamStackPermission" {
  organization = "string"
  permission = "read"
  project = "string"
  stack = "string"
  team = "string"
}
```
Where `permission` is a _numeric_ enum defined as follows`{ "read" => 101, "edit" => 102, "admin" => 103 }`. 

Program-gen for C# fails here, generating a PANIC so this specific example is skipped: 
```cs
    // Resource pulumiservice:index:TeamStackPermission
    var teamStackPermissionResource = new PulumiService.TeamStackPermission("teamStackPermissionResource", new()
    {
        Organization = "string",
        Permission = %!v(PANIC=Format method: Unsafe enum conversions from type string not implemented yet:  "read"
 => enum(pulumiservice:index:TeamStackPermissionScope(number): cty.NumberIntVal(101),cty.NumberIntVal(102),cty.NumberIntVal(103))),
        Project = "string",
        Stack = "string",
        Team = "string",
    });
```

TypeScript, Go and Python all fail to a similar error. Fix incoming
