### ISSUE TITLE
why you dont have support for nutanix provider

### ISSUE THREAD

**Issue by AvivMark** [pulumi/pulumi#16214]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Comment by justinvp** [comment]
> why you dont have support for nutanix provider

It just hasn't been requested before. Thanks for the suggestion.

**Comment by AvivMark** [comment]
I will be more than happy to help you נשלח מה-iPhone שלי‫ב-16 במאי 2024, בשעה 22:31, ‏‏Justin Van Patten ***@***.***> כתב/ה:‬﻿

why you dont have support for nutanix provider

It just hasn't been requested before. Thanks for the suggestion.

**Comment by cnemo-cenic** [comment]
FYI I am seeing this, not sure how mature it is https://github.com/pierskarsenbarg/pulumi-nutanix

**Comment by AvivMark** [comment]
I checked the plugin I am using it but it missing features and there is
barely documentation

בתאריך יום ה׳, 23 במאי 2024 ב-19:53 מאת cnemo-cenic <
***@***.***>:

**Comment by mikhailshilkov** [comment]
As mentioned above, this provider is available as a community-driven provider in https://github.com/pierskarsenbarg/pulumi-nutanix

If you miss some feature or experience issues, please open tickets in that repo.

**Comment by pierskarsenbarg** [comment]
@AvivMark not going to reopen this issue, but I’ve brought the provider  inline with the TF provider. The PR for building the site has just been merged so the docs should be there soon
