### ISSUE TITLE
confirmation cancelled, not proceeding with the update: Unexpected Escape Sequence: ['\x1b' 'O']

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1621]
In the VS Code integrated terminal, the `pulumi` up/down prompt no longer works.  Not sure whether this was a change in VS Code or something we changed recently.

```
Do you want to perform this update?
  yes
> no
  details
error: confirmation cancelled, not proceeding with the update: Unexpected Escape Sequence: ['\x1b' 'O']
```

**Comment by ellismg** [comment]
I'm unable to reproduce this on VS Code 1.25.0, on Linux.  But I am sure we have problems here, because there's so many moving pieces.  Can you tell me the following:

1. OS (I assume macOS)
2. VSCode Version
3. The output of `echo $TERM` when you are in the integrated terminal?

**Comment by lukehoban** [comment]
Strange.  This was on insiders build `1.26.0-insider `.  But I can no longer reproduce it myself ( I believe I got updated VS Code this morning).  So most likely it was an issue on their side.  Closing.

**Comment by Frassle** [comment]
I just ran into this, seems my shell had gone into application mode (vs normal mode). Set it back to normal by running "tput rmkx".

**Comment by Frassle** [comment]
And I've tracked down what caused the terminal mode change: https://github.com/Microsoft/dotnet/issues/472
