### ISSUE TITLE
Twistlock scans reporting CVE

### ISSUE THREAD

**Issue by automagic** [pulumi/pulumi#16232]
### What happened?

Twistlock scans of our container images that contain Pulumi CLI started to report following vulnerabilities: GO-2024-2824( https://pkg.go.dev/vuln/GO-2024-2824 ) and GO-2024-2631( https://pkg.go.dev/vuln/GO-2024-2631 ) . We rebuild our base images daily with latest .NET base images and latest Pulumi CLI

### Example

<img width="1350" alt="image" src="https://github.com/pulumi/pulumi/assets/865196/ebd9aa50-dc20-480d-8fa9-5e81b4c9499e">

### Output of `pulumi about`

CLI
Version      3.116.1
Go Version   go1.22.2
Go Compiler  gc

Host
OS       debian
Version  12.5
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
The next release of Pulumi will be built with Go 1.22.3, which will address https://pkg.go.dev/vuln/GO-2024-2824.

Investigating upgrading go-jose.

**Comment by justinvp** [comment]
https://github.com/pulumi/pulumi/pull/16239 upgrades go-jose to a patched version.

**Comment by justinvp** [comment]
This has been addressed with the release of [v3.117.0](https://github.com/pulumi/pulumi/releases/tag/v3.117.0), which is rolling out now.
