### ISSUE TITLE
Parallelize resource deletion

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1625]
Resource deletion is somewhat unique in Pulumi in that we have a complete view of the dependency graph of resources that already exist. When it comes time to delete a resource, we can parallelize execution of `Delete` steps across the dependency DAG of a condemned resource.

Doing so requires us to be intelligent about step dependencies and have a nontrivial task scheduler, so it's a higher-level milestone for parallelism.

**Comment by lukehoban** [comment]
We'll focus on landing create/update parallelism first.

**Comment by swgillespie** [comment]
There are a couple ways that we could approach this problem, depending on how correct we want to be.

We can partition an arbitrary dependency DAG into a series of nodes that we can know are safe to execute in parallel. A straightforward algorithm for this will produce a set of series of nodes (set of antichains) that is the same size as the length of the longest dependency chain in the graph, which is a big improvement over where we are today.

We can also move towards a full-blown DAG scheduling system, where steps have dependencies and get scheduled by the engine executor as soon as the steps they depend on complete. This design is flexible but also more complex. It has the added benefit of allowing us to schedule replacement deletions during the plan.

**Comment by swgillespie** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/1963.
