### ISSUE TITLE
a way for Pulumi to ignore the entrypoint of Package.json ( Node.js)

### ISSUE THREAD

**Issue by edgehero** [pulumi/pulumi#16274]
## Hello!
Currently i got a project based on node.js/typescript. I got the code for azure function and the pulumi infra code to put it on azure in the same project folder.

folder structure:

```
- <root>/
  - <supporting files>
  - package.json
  - apps
    - app1/
      - package.json
      - infra/
          - Pulumi.yaml
          - index.ts # <- pulumi needs to run this file, so use this as entry point
      - src/
          - azure-function.ts
      - dist/
          - compiled-azure-function.js
```

structure apps/app1/package.json
```
{
  ...
  "main": "./dist/compiled-azure-function.js" # <- this is needed for azure functions ( stupid azure quirk ) 
  ...
}
```

## Issue details

When i try to run this with pulumi.
`./dist/compiled-azure-function.js` is taken as entrypoint to pulumi.

even when setting a main entrypoint in Pulumi.yaml, it still uses the main from package.json
```
name: cool-name
main: index.ts
runtime:
  name: nodejs
```
Is there a way to make it use the main from Pulumi.yaml and ignore the package.json main?

**Comment by Frassle** [comment]
I feel like the right answer to this is there should be a package.json in the infra folder. But @julienp might have an idea of how else this could work.

**Comment by danielpatrickdotdev** [comment]
The [docs](https://www.pulumi.com/docs/concepts/projects/project-file/#about-main) say that when determining `main` for nodejs projects

> When it exists in both Pulumi.yaml and package.json, the value in Pulumi.yaml takes precedence.

Are the docs incorrect? I would have expected Pulumi.yaml to take precedence before reading the docs too, but it seems that's not the case.

**Comment by julienp** [comment]
Oh good catch, I think we inadvertently broke this in https://github.com/pulumi/pulumi/commit/cf1189bf2c9a31b7d0ca7aa280661af892029aa4

With [v3.73.0](https://github.com/pulumi/pulumi/releases/tag/v3.73.0) I get the documented behaviour where Pulumi.yaml takes precedence. With [v3.74.0](https://github.com/pulumi/pulumi/releases/tag/v3.74.0), the first change to include the above commit, it always takes the entry point from package.json.

**Comment by Makeshift** [comment]
Just encountered this - I have two stacks with a different `main` specified (this is an example of how to use one of my components cross-stack, so not something I'm deeply interested in following best-practice for):

```
# Pulumi.stack1.yaml
main: src/stack1-output-stack.ts

# Pulumi.stack2.yaml
main: src/stack2-input-stack.ts
```

However, Pulumi ignores these entrypoints and attempts to grab it from `package.json`. It doesn't seem to be possible to do this currently with v3.119.0, as it'll either fail because `main` isn't specified in `package.json`, or be limited to only running one stack if you do specify one.
