### ISSUE TITLE
pendingReplacement

### ISSUE THREAD

**Issue by jesse-triplewhale** [pulumi/pulumi#16288]
### What happened?

❯ pulumi version
v3.117.0

Two questions about when `pendingReplacement` is set to `true`

1. If I have a resource that is `"pendingReplacement": true`, pulumi tries to delete the resource on `pulumi up`. But by definition, the resource does not exist and therefore the delete fails. 
2. `pulumi refresh` does not actually call the resource's `refresh` function when `pendingReplacement` is `true`? Is there a way to change that?

Thank you for your help,
Jesse

### Example

Here is an example of a `pulumi up` with `"pendingReplacement": true` which tries to delete the resource and fails

https://app.pulumi.com/triplewhale/currency-conversion/triple-whale-staging/updates/288

### Output of `pulumi about`

❯ pulumi about  
CLI          
Version      3.117.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  clickhouse     0.0.39
resource  cloudflare     5.28.0
resource  datadog        4.28.0
resource  docker         4.5.3
resource  ec             0.8.0
resource  gcp            7.24.0
resource  google-native  0.32.0
resource  grafana        0.4.2
resource  kafka          3.7.4
resource  kubernetes     4.11.0
resource  mongodbatlas   3.15.0
language  nodejs         unknown
resource  postgresql     3.11.1
resource  rabbitmq       3.3.2
resource  random         4.16.1
resource  slack          0.4.4

Host     
OS       darwin
Version  14.4.1
Arch     arm64

This project is written in nodejs: executable='/Users/jessegrodman/.nvm/versions/node/v18.17.1/bin/node' version='v18.17.1'

Current Stack: triplewhale/currency-conversion/triple-whale-staging

TYPE                                                                URN
--- sanitized ---

Found no pending operations associated with triple-whale-staging

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/triplewhale
User           triplewhale
Organizations  triplewhale
Token type     organization: triplewhale
Token type     cloud-build

Dependencies:
NAME                VERSION
@pulumi/gcp         7.24.0
@pulumi/pulumi      3.117.0
@temporalio/client  1.10.1
@tw/pulumi          0.7.138
@tw/types           0.5.470
@types/node         20.12.11

Pulumi locates its logs in /var/folders/q5/dtfqc20n7f9429fhjpj2kfxh0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for raising this (and for the PR). Thoughts @Frassle and/or @lunaris?

**Comment by Frassle** [comment]
I commented on the PR, we need tests to repro this buggy behavior. 

Also having a closer look at things now, I don't think point 2 is a bug. If a resource is pending replace then we _shouldn't_ call refresh on it, because we know we've already deleted it.
