### ISSUE TITLE
Stack Transformations miss resources defined before them

### ISSUE THREAD

**Issue by michael-aldridge-pozlo** [pulumi/pulumi#16304]
### What happened?

The [docs on stack transformations](https://www.pulumi.com/docs/concepts/options/transformations/#stack-transformations) say that they

> are applied to the root stack resource and as a result inherited by all other resources in the stack.

As such I would expect a stack transformation to be called for all resources in my stack, but it looks like it is only called for resources that come _after_ it in code.

### Example

Consider the following (typescript) example

```typsecript
import * as pulumi from "@pulumi/pulumi";
import * as time from "@pulumiverse/time";

new time.Sleep("before", {createDuration: "60s"});

pulumi.runtime.registerStackTransformation((args) => {
  console.log(args.name);
  return undefined;
});

new time.Sleep("after", {createDuration: "60s"});
```

When we run it, we see the stack transformation is only called on the `after` resource

```
Diagnostics:
  pulumi:pulumi:Stack (XXX):
    after
```

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.117.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/<redacted>/.nvm/versions/node/v18.16.0/bin/node' version='v18.16.0'

Backend        
Name         <redacted>
URL            gs://<redacted>
User           michael
Organizations  
Token type     personal
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This is by design. The registration of stack transforms is imperative, if you want them to apply to everything in the program they need to be registered at the start of the program.

**Comment by tgummerer** [comment]
Even though this is by design, this might indicate that our documentation isn't quite up to the task of explaining this?  I opened https://github.com/pulumi/docs/pull/11942 as a proposal to potentially fix that.
