### ISSUE TITLE
azure-native:servicebus:listNamespaceKeys actually being invoked during runtime

### ISSUE THREAD

**Issue by HilmirWise** [pulumi/pulumi#16312]
### What happened?

I was using python and ran into an issue when running pulumi preview in my pipelines. When calling listNamespaceKeys, instead of mocking it somehow like all the constructors, it actually tries to invoke the function and returns a 404, resource group not found. This is because the resources are not being created.

### Example

To recreate, create a resource group, namespace, namespace rule, and then call the function list_namespace_keys with those parameters. Then run pulumi preview.

### Output of `pulumi about`

CLI          
Version      3.117.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.35.0
resource  azuread       5.47.0
resource  cloudamqp     3.17.1
resource  command       0.9.2
resource  docker        4.5.0
language  python        unknown
resource  random        4.15.0

Host     
OS       ubuntu
Version  24.04
Arch     x86_64

This project is written in python: executable='/home/hilmir/Courier/venv/bin/python3' version='3.12.3'

Backend        
Name           pulumi.com

Dependencies:
NAME                         VERSION
affinda                      4.22.0
azure-servicebus             7.12.2
azure-storage-blob           12.19.1
coverage                     7.5.0
ddtrace                      2.8.2
django-allauth               0.62.1
django-anymail               10.3
django-ca                    1.28.0
django-celery-beat           2.6.0
django-celery-results        2.5.1
django-cors-headers          4.3.1
django-import-export         3.3.8
django-mathfilters           1.0.0
django-ninja                 1.1.0
django-storages              1.14.2
django-structlog             8.0.0
exceptiongroup               1.2.1
factory-boy                  3.3.0
install                      1.3.5
JSON-log-formatter           1.0
keeper-secrets-manager-core  16.6.2
lxml                         5.2.1
MarkupPy                     1.14
mjml-python                  1.3.2
mock                         5.1.0
numpy                        1.26.4
odfpy                        1.4.1
openpyxl                     3.1.2
pdfkit                       1.0.0
pdfmerger                    0.5.0
pillow                       10.3.0
pip                          24.0
psycopg                      3.1.18
psycopg-binary               3.1.18
pulumi_azure_native          2.35.0
pulumi-azuread               5.47.0
pulumi-cloudamqp             3.17.1
pulumi-command               0.9.2
pulumi-docker                4.5.0
pulumi-random                4.15.0
pypdf                        4.2.0
python-jose                  3.3.0
python-stdnum                1.20
python3-openid               3.2.0
ShopifyAPI                   12.5.0
uvicorn                      0.29.0
xlrd                         2.0.1
xlwt                         1.3.0

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Hi @HilmirWise, thanks for opening this and sorry for the trouble!

> To recreate, create a resource group, namespace, namespace rule, and then call the function list_namespace_keys with those parameters. Then run pulumi preview.

Can you share a snippet of the code that demonstrates this?

This sounds like the same/similar problem as https://github.com/pulumi/pulumi/issues/9593. Functions _are_ invoked during preview. If the function needs the resources to be created, one way to workaround this is to call the function inside an `apply` of a resource output property like `id` that won't be available until the resource is created, e.g.:

```python
import pulumi
import pulumi_azure_native as azure_native

resource_group = azure_native.resources.ResourceGroup(...)
namespace = azure_native.servicebus.Namespace(...)
namespace_rule = azure_native.servicebus.NamespaceAuthorizationRule(...)

def get_namespace_keys(resource_group_name, namespace_name, authorization_rule_name, id):
    return azure_native.servicebus.list_namespace_keys(
        resource_group_name=resource_group_name,
        namespace_name=namespace_name,
        authorization_rule_name=authorization_rule_name
    )

keys = pulumi.Output.all(resource_group.name, namespace.name, namespace_rule.name, namespace_rule.id).apply(
    lambda args: get_namespace_keys(*args)
)

primary_key = keys.apply(lambda k: k.primary_key)
```

**Comment by HilmirWise** [comment]
Hi,

Thanks for your response.

I think this should do the trick.

However, I think this behaviour is strange to me. I feel like functions that have Input wrapped parameters and Output wrapped return values should not be called during preview, exactly because of errors like this. Otherwise, the change you guys made to take in Input parameters in listNamespaceKeys (can't find the issue number) is useless since you're forced to use apply either way. I think this should be changed.

Thansk again,
Hilmir
