### ISSUE TITLE
MLC Provider error: cannot construct components if the provider is configured with unknown values

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#16331]
### What happened?

When using a MLC and a provider with an unknown value, because for example the eks cluster is not available, you get the following failure:
` grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "cannot construct components if the provider is configured with unknown values"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-06-05T10:28:03.51563596-05:00", grpc_status:2, grpc_message:"cannot construct components if the provider is configured with unknown values"}"`

### Example

```python
import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx
import pulumi_eks as eks
import pulumi_kubernetes as kubernetes
from pulumi_kubernetes.helm.v4 import Chart, RepositoryOptsArgs

vpc = awsx.ec2.Vpc("my-vpc", number_of_availability_zones=3, nat_gateways=1)

# Create an EKS cluster with the default configuration.
cluster = eks.Cluster(
    "test-cluster",
    vpc_id=vpc.vpc_id,
    private_subnet_ids=vpc.private_subnet_ids,
    public_subnet_ids=vpc.public_subnet_ids,
    node_associate_public_ip_address=False,
    instance_type="c5.large",
    version="1.29",
)

k8s_provider = kubernetes.Provider("k8s_provider", kubeconfig=cluster.kubeconfig)

cert_manager_ns = kubernetes.core.v1.Namespace(
    "cert-manager",
    metadata=kubernetes.meta.v1.ObjectMetaArgs(name="cert-manager"),
    opts=pulumi.ResourceOptions(provider=k8s_provider),
)

v4_cert_chart = Chart(
    "cert-manager",
    chart="oci://registry-1.docker.io/bitnamicharts/cert-manager",
    namespace=cert_manager_ns.metadata["name"],
    opts=pulumi.ResourceOptions(provider=k8s_provider),
)

pulumi.export("kubeconfig", cluster.kubeconfig)
```

### Output of `pulumi about`

```
 pulumi about
CLI
Version      3.118.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.37.1
resource  awsx        2.10.0
resource  docker      4.5.4
resource  eks         2.5.2
resource  kubernetes  4.13.1
language  python      unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python: executable=`pulumi-eks-chart4/venv/bin/python3' version='3.11.9'
``

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
It's currently by-design per https://github.com/pulumi/pulumi/pull/13579.

@Frassle, is there anything we can do to make this scenario work? Helm v4 Chart is an MLC.

**Comment by rshade** [comment]
This seems like a fairly standard scenario, and a preview only bug. `--skip-preview` seems to work fine, maybe if we just render the top level object and throw a warn.

**Comment by Frassle** [comment]
> is there anything we can do to make this scenario work? Helm v4 Chart is an MLC.

I think we could render the component as all unknowns? Just say we're going to create the component resource, but don't register any outputs for it, similar to what we do for custom resources. Obviously none of the inner resources will show up at preview time.

**Comment by EronWright** [comment]
I believe that this issue blocks a major use case for the Kubernetes MLCs, that of provisioning and then using a cluster in a single program. One expects to define a provider based on the cluster's outputs, then apply charts and manifests using that provider.

**Comment by tyler-ball** [comment]
I have the same use case @EronWright mentions - I am creating an Azure AKS cluster and then immediately want to apply a chart on it when creating test deploys of our application stack
