### ISSUE TITLE
Deploying Pulumi stack fails with vague error message.

### ISSUE THREAD

**Issue by jonnysmith1981** [pulumi/pulumi#16360]
### What happened?

I am trying to deploy a Webiny instance following their instructions at https://www.webiny.com/docs/get-started/install-webiny. The first time i tried this the site deployed with no problems. I had to delete the project folder and start from scratch so I ran through the above instructions again. This time the deployment fails with the following error:

```
  pulumi:pulumi:Stack (core-dev):
    error: an unhandled error occurred: [eval]:1
    try {


    SyntaxError: Unexpected end of input
        at new Script (node:vm:94:7)
        at createScript (node:vm:250:10)
        at Object.runInThisContext (node:vm:298:10)
        at node:internal/process/execution:82:21
        at [eval]-wrapper:6:24
        at runScript (node:internal/process/execution:81:62)
        at evalScript (node:internal/process/execution:103:10)
        at node:internal/main/eval_string:30:3

    Node.js v18.19.0
```

I have spoken to Webiny support about this and they are unable to help as it is a Pulumi problem.

I have deleted my global yarn cache, all files relating to Pulumi and trawled through the Registry for "pulumi", before following the instructions again. This has been done 3 times.

### Example

Steps to reprodice can be seen at https://www.webiny.com/docs/get-started/install-webiny. 

Running `yarn webiny deploy` gives the error.

### Output of `pulumi about`

Pulumi is bundled with Webiny so I cannot run `pulumi about`.

Output from `webiny about` shows that it is using Pulumi v2.25.2 and Pulumi-AWS v5.43.0

This is on a Windows 10 computer running Node 18.19.0 and Yarn 3.6.4

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
Thanks for opening the issue.  

> Pulumi v2.25.2

This is a *very* old version of Pulumi, and it's at this time over 3 years out of date, and no longer maintained.  This makes it both very hard to see what this error is about, and to try and track down what might have fixed the issue in the meantime.  Aside from other fixes, this pulumi version also no longer gets any security related updates.

Judging by the output above, it also looks like the program is only half generated for some reason, which looks like a probably `webiny` problem rather than a pulumi problem.

To move forward here I would suggest two things:
- It would be very helpful to see the pulumi program that is being used here. I'm not sure how to find this in `webiny`, but if you don't know maybe their support can help.
- It would be good to encourage `webiny` to upgrade Pulumi to the latest version, as there were many bugfixes that could help if not fix the issue at least diagnose it.

**Comment by jonnysmith1981** [comment]
@tgummerer Many thanks for the quick response. I'll check back in with Webiny support to see if they can answer those two questions.

**Comment by jonnysmith1981** [comment]
Closing this for now as either:
1) Its not a problem with Pulumi
or
2) The version of Pulumi is probably out of support.

**Comment by tarabishy2020** [comment]
I am facing exactly the same error! This was the only similar post I could find.

```bash
pulumi version # v3.120.0
pulumi new azure-typescript
pulumi up #results in the below
```

```
Previewing update (dev):
     Type                 Name      Plan     Info                                                                            
     pulumi:pulumi:Stack  test-dev           1 error                                                                         
Diagnostics:
  pulumi:pulumi:Stack (test-dev):
    error: an unhandled error occurred: [eval]:1
    try {


    SyntaxError: Unexpected end of input
        at makeContextifyScript (node:internal/vm:123:14)
        at node:internal/process/execution:98:22
        at [eval]-wrapper:6:24
        at runScript (node:internal/process/execution:92:62)
        at evalScript (node:internal/process/execution:123:10)
        at node:internal/main/eval_string:51:3

    Node.js v20.11.1
```

`pulumi about` >
```
CLI
Version      3.120.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.45.0
language  nodejs        unknown

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22631 Build 22631
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\Volta\node.exe' version='v20.11.1'

Backend
Name           <*>
URL            azblob://<*>
User           <*>
Organizations
Token type     personal

Dependencies:
NAME                  VERSION
@pulumi/azure-native  2.45.0
@pulumi/pulumi        3.120.0
@types/node           20.11.1
typescript            5.4.5
```

**Comment by DeepakBairagi-Fragmatic** [comment]
@jonnysmith1981  Were you able to find a solution for this?

**Comment by DeepakBairagi-Fragmatic** [comment]
@adrians5j  can you help here, I am also getting this error.

**Comment by swapnilmmane** [comment]
Hi @DeepakBairagi-Fragmatic, we've upgraded Pulumi to v6 with the latest Webiny 5.40 release. Let's continue this discussion on the existing thread in the [Webiny community Slack](https://webiny-community.slack.com/archives/C014Y0HGJ0Y/p1720333629861119). Thanks!
