### ISSUE TITLE
Getting vague error on `pulumi up`

### ISSUE THREAD

**Issue by tarabishy2020** [pulumi/pulumi#16393]
I am facing exactly the same error mentioned in #16360

```
pulumi version # v3.120.0
pulumi new azure-typescript
pulumi up #results in the below
```

```
Previewing update (dev):
     Type                 Name      Plan     Info                                                                            
     pulumi:pulumi:Stack  test-dev           1 error                                                                         
Diagnostics:
  pulumi:pulumi:Stack (test-dev):
    error: an unhandled error occurred: [eval]:1
    try {


    SyntaxError: Unexpected end of input
        at makeContextifyScript (node:internal/vm:123:14)
        at node:internal/process/execution:98:22
        at [eval]-wrapper:6:24
        at runScript (node:internal/process/execution:92:62)
        at evalScript (node:internal/process/execution:123:10)
        at node:internal/main/eval_string:51:3

    Node.js v20.11.1
```

`pulumi about` >
```
CLI
Version      3.120.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.45.0
language  nodejs        unknown

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22631 Build 22631
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\Volta\node.exe' version='v20.11.1'

Backend
Name           <*>
URL            azblob://<*>
User           <*>
Organizations
Token type     personal

Dependencies:
NAME                  VERSION
@pulumi/azure-native  2.45.0
@pulumi/pulumi        3.120.0
@types/node           20.11.1
typescript            5.4.5
```

**Comment by tgummerer** [comment]
This is really odd.  Can you try re-installing the dependencies using `npm ci`?  It almost looks like some dependencies are half installed, which also recently happened in https://github.com/pulumi/pulumi/issues/16377 (but that looked slightly different, so not sure this is the same case again).

**Comment by tarabishy2020** [comment]
That didn't change anything sadly. Also, this error is happening in a project I am working on, and the above steps were to test if it will be the same in a new project or not.
I tried running `pulumi up --logtostderr --logflow -v=10` in both, in the main project no new information appeared, but in the test project i bootstrapped with 
`pulumi new azure-typescript` I am getting the below 2 errors logged

```
Diagnostics:
  pulumi:pulumi:Stack (test-dev):
    error: an unhandled error occurred: [eval]:1
    try {


    SyntaxError: Unexpected end of input
        at makeContextifyScript (node:internal/vm:123:14)
        at node:internal/process/execution:98:22
        at [eval]-wrapper:6:24
        at runScript (node:internal/process/execution:92:62)
        at evalScript (node:internal/process/execution:123:10)
        at node:internal/main/eval_string:51:3

    Node.js v20.11.1

    I0614 17:05:01.803472   14080 main.go:321] one or more errors while discovering plugins: 2 errors occurred:
        * unmarshaling package.json ...\test\node_modules\resolve\test\resolver\false_main\package.json: json: cannot unmarshal bool into Go struct field packageJSON.main of type string
        * unmarshaling package.json ...\test\node_modules\resolve\test\resolver\invalid_main\package.json: json: cannot unmarshal array into Go struct field packageJSON.main of type string
```

**Comment by tgummerer** [comment]
Very odd.  Did this error just start happening in the project you are working on, or did that project never work?  Also did you try this on a different machine?  

Also would you be willing to send us a zip of the project so we can try to reproduce this, since we haven't been able to do so.  And the full logfile you're getting with `-v=10`?  

If you don't want to attach it to the issue you can send it to me privately at v-thomas@pulumi.com.

**Comment by tarabishy2020** [comment]
The main project worked before, but I was having other problems with pulumi-docker provider on my local machine, so tried to run the deployment from an Azure Dev Box, and that's when this error happened. Then tried a fresh project on that same Dev Box and got the same error.
I sent you the log file and the project to your email. 
Thank you for offering to have a look on this🙏

**Comment by NatMarchand** [comment]
Hi there! 
I'm currently running into the same error.
My computer is running on Windows with: 
pulumi v3.123.0
nodejs v20.15.1

In a github action running on ubuntu it works fine.

**Comment by julienp** [comment]
I can reproduce this when I use https://volta.sh to install nodejs. When using the official nodejs installed from https://nodejs.org/en everything works as expected.

From reading the Volta documentation, it puts shim programs on the path and these route somehow to the correct executable. Pulumi is not doing anything particular fancy with how nodejs is executed, so I am not sure what's going wrong here, I still need to investigate this further.

## Workaround

Install the official nodejs from https://nodejs.org/en instead of using node via Volta.

**Comment by julienp** [comment]
In https://github.com/pulumi/pulumi/pull/16160 we made a change that calls `nodejs` with a multiline script. It looks like the Volta shim does not properly handle this. Fix incoming for Pulumi, and I'll open an upstream issue with Volta as well.

**Comment by julienp** [comment]
As @NatMarchand pointed out, this broke in 3.116.0 and is a regression.

**Comment by tarabishy2020** [comment]
I can confirm that I was using Volta when this error occurred.
