### ISSUE TITLE
Pending deletion is problematic

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#1645]
We've seen empirically that pending deletes in the snapshot are buggy and generally problematic.

* https://github.com/pulumi/pulumi/issues/1503 - Duplicated resource leading to assert from `computeDeletes`
* https://github.com/pulumi/pulumi/issues/1597 - No way to fix resources in "pending delete" status which cannot be deleted without property changes
* https://github.com/pulumi/pulumi/issues/1598 - pulumi refresh fails when there are pending deletes
* https://github.com/pulumi/pulumi/issues/1596 - Deletions of "pending delete" resources are not shown in preview

There are a couple fundamental problems with the way that we address pending deletes today:

1. Pending deletes are considered a "delete-replacement" by the engine, which means that from a UI perspective they are rendered as the culmination of a resource replacement. This causes problems in that it is difficult to ascertain via a preview whether or not pending delete deletions are occurring, since they are masked as replacements.
2. Pending deletes are retired at the end of a plan. If a user plan repeatedly creates new pending deletions and does not completely succeed, we will increase the amount of pending deletions without ever having a chance to delete them. This can cause the list of pending deletes to be arbitrarily large.
3. It is empirically possible today to have multiple pending delete resources with the same URN be in the snapshot at a single point in time.

I don't think there's a magic bullet that addresses all of the above issues, but I do think that there are a few concrete things that we can do that will improve the user experience around pending deletes:

1. (Credit to @pgavlin who also thought of this) We should consider retiring all pending deletions at the start of a plan, *before* handling any incoming resource registrations. Doing this before user code is run gives the engine a chance to ensure that there are no pending delete resources in the snapshot before starting a plan. It also ensures that the set of pending delete resources does not expand indefinitely.
2. We should consider some sort of CLI gesture that allows users to remove or edit select resources in the snapshot. There is currently no good solution for #1597 short of editing the snapshot directly, and forcing users to edit the snapshot directly means that we have failed. Terraform has the [`terraform state`](https://www.terraform.io/docs/commands/state/index.html) that gives power users the tools to fix their state file without having to edit the JSON directly.
3. We should reclaim the invariant that there can be at most one resource with a given URN present in the pending delete set. This is only going to become more complicated as we introduce additional resource states (https://github.com/pulumi/pulumi/issues/1626) and invariants allow us to better reason about the behavior of the engine.

**Comment by lukehoban** [comment]
Let's broadly tackle this as part of 0.17.

**Comment by ericrudder** [comment]
i am quite sympathetic to "not everything can get done in m16" ... however
*iff* it's relatively straightforward to try the suggestion in (1) [retire
pending deletions at the start of a plan] ... that would seem to be a nice
thing to do to see if it ameliorates some issues.

**Comment by swgillespie** [comment]
I think that, now that https://github.com/pulumi/pulumi/issues/1503 has been addressed, there aren't any pressing issues that would be remediated by retiring deletes first. We'll also need to think about the UX here - right now pending deletes render pretty poorly (i.e. don't show up at all) in the CLI and I think we'd want to fix that in tandem with retiring deletes first, since otherwise it'll appear that the CLI is unresponsive for a while as things get deleted.

**Comment by ericrudder** [comment]
OK, i will give ... it's precisely because we would "deal with them first"
(including UI) that makes me like the idea ... no mas.

**Comment by swgillespie** [comment]
Sorry, I don't mean to say that it's not good idea anymore - I absolutely agree that retiring deletes first is what we should be doing from a UX and correctness perspective. What I'm not sure about is if I have the time to do all of the UX and engine work to make it happen in M16.
