### ISSUE TITLE
DISABLE_AUTOMATIC_PLUGIN_ACQUISITION does not work for `pulumi convert`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#16469]
### What happened?

@VenelinMartinov noticed a CI failure during `pulumi convert`: GH API limit reached. This is odd, since we run that test with `DISABLE_AUTOMATIC_PLUGIN_ACQUISITION=true`. As far as I understand, with plugin acquisition disabled, we should never reach out to GitHub.

### Example

```console
$ DISABLE_AUTOMATIC_PLUGIN_ACQUISITION=true \
  GITHUB_TOKEN=NOT_A_REAL_TOKEN \
  pulumi convert --from tf --language ts
Converting from terraform...
error: load converter plugin: install "terraform": could not find latest version for provider terraform: 401 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-converter-terraform/releases/latest
```

### Output of `pulumi about`

```
pu about
CLI          
Version      3.121.1-dev.0
Go Version   go1.22.3
Go Compiler  gc

Host     
OS       darwin
Version  14.5
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Getting this quite often lately: https://github.com/pulumi/pulumi-terraform-bridge/actions/runs/9972810153/job/27556840950?pr=2186

**Comment by Frassle** [comment]
`PULUMI_DISABLE_AUTOMATIC_PLUGIN_ACQUISITION`

**Comment by VenelinMartinov** [comment]
Yup, confirmed that was the issue. Thanks @Frassle
