### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)

### ISSUE THREAD

**Issue by m-yavuz** [pulumi/pulumi#16460]
### What happened?

I use Azure DevOps Pipeline to call  `npm install -g @pulumi/pulumi` and  `pulumi up` 
the latest version of pulumi ([3.121.0](https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md#31210-2024-06-22)) has the following issue during the installation:

```
/bin/bash --noprofile --norc /__w/_temp/39416ff9-aaf1-41fe-93ad-170751d9b07b.sh
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
##[error]Bash exited with code '1'.
Finishing: Install Pulumi
```

### Example

`npm install -g @pulumi/pulumi`

### Output of `pulumi about`

TBD

### Additional context

**Agent** : ubuntu-latest
**Node :** 18.x & 20.x 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> the latest version of pulumi ([3.121.0](https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md#31210-2024-06-22)) has the following issue during the installation:

Did it ever work? This looks like your node install isn't correct, you've got a version that wants to dynamically load libc and you don't have that installed.

**Comment by m-yavuz** [comment]
last time pipeline worked correctly a month ago

Node: 16.x 

however, today when i tried to rerun the same pipeline i got this issue :

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@pulumi/pulumi@3.121.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
```

so i tried to upgrade node version to 18 and 20 then i got **`GLIBC_2.28' not found**

**Comment by Frassle** [comment]
Yeh node 16 is well out of support. I'd guess the node 18 and 20 need libc and 16 for some reason didn't. This isn't really an issue with pulumi but with your node setup. I'd guess you're running on linux alpine (it's where we see most glibc issues), which if so installing the compat library might be enough `apk add gcompat`.

**Comment by m-yavuz** [comment]
The pipeline uses Azure DevOps agent ubuntu-22.04 [agent packages details](https://github.com/actions/runner-images/blob/releases/ubuntu22/20240616/images/ubuntu/Ubuntu2204-Readme.md) 

Do you think I need to install **GLIBC** manually to the agent ?

**Comment by Frassle** [comment]
I wouldn't have thought so, especially given that the package lists that node 18 is already installed but that's what the error suggests. I'd suggested you'd get more accurate help from https://github.com/actions/runner-images/issues or azure devops support rather than here. There's nothing specific to pulumi about trying to run node and it failing like this.

**Comment by m-yavuz** [comment]
Right, this doesn't seem to be a Pulumi issue. 
Thank you for your help.
