### ISSUE TITLE
Choose Preferred Package Manager during `pulumi new`

### ISSUE THREAD

**Issue by alayshia** [pulumi/pulumi#16478]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

In development, it would be nice to provide flexibility in picking a preferred package manager. 

I.e. some developers enjoy using `pnpm` versus `npm` because it is faster. 

`pulumi new azure-typescript --package-manager="pnpm"` would be ideal in this scenario.

**Comment by julienp** [comment]
We actually just shipped this in the context of https://github.com/pulumi/pulumi/issues/15937 !

When you create a new typescript/javascript project with the Pulumi CLI v3.12, it asks you for a package manager to use:

<img width="449" alt="Screenshot 2024-06-28 at 12 09 49" src="https://github.com/pulumi/pulumi/assets/387068/aa6b1b9b-4784-4948-98ca-22ff6016edbe">

You can also pass it in via a flag:
```
pulumi new typescript --runtime-options packagemanager=yarn
```

Similarly for new Python projects, you can choose between `pip` and `poetry`.
