### ISSUE TITLE
Pulumi Access tokens stopped working

### ISSUE THREAD

**Issue by edgehero** [pulumi/pulumi#16509]
### What happened?

Pulumi Access tokens stopped working, you can not login with one anymore. and also not create one anymore. what is happening?

### Example

```
export PULUMI_ACCESS_TOKEN=accesstoken
pulumi login 
error: problem logging in: invalid access token
```

### Output of `pulumi about`

CLI                  
Version      3.99.0  
Go Version   go1.21.5
Go Compiler  gc      

Host     
OS       Microsoft Windows 10 Enterprise
Version  10.0.19045 Build 19045
Arch     x86_64

### Additional context

is there a service to check if something of pulumi is offline?

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by bramleffers** [comment]
Just checked it. You'll need to enter alphanumaric charcteres so NO spaces. The error that you get is the following;

```
{
    "code": 400,
    "message": "Bad Request: Token name may only contain alphanumeric, hyphens, or underscores"
}
```

It is not reflected in the GUI this needs to be fixed.

**Comment by Frassle** [comment]
I don't see that 400 error code? Trying this with an extra print for the internal http error I see:

```
PULUMI_ACCESS_TOKEN=" pul-xxxxxx  " pulumi login
Logging in using access token from PULUMI_ACCESS_TOKEN
[401] Unauthorized: No credentials provided or are invalid.
error: problem logging in: invalid access token
```

That's a 401 and no message about the token name?

**Comment by bramleffers** [comment]
@Frassle I'm sorry it is not in the CLI - it's gener ating a access token from the web-interface. 

https://app.pulumi.com/${orgName}/settings/org-tokens

I just tested it again and it maybe it was a hickup because we are enabled to generate tokens again. So this one can be closed.
