### ISSUE TITLE
Improve `pulumi` "landing command" help message

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#1652]
When you enter the `helm` command with no input, you get the following:

```sh
$ helm
The Kubernetes package manager

To begin working with Helm, run the 'helm init' command:

	$ helm init

This will install Tiller to your running Kubernetes cluster.
It will also set up any necessary local configuration.

Common actions from this point include:

- helm search:    search for charts
- helm fetch:     download a chart to your local directory to view
- helm install:   upload the chart to Kubernetes
- helm list:      list releases of charts

Environment:
  $HELM_HOME          set an alternative location for Helm files. By default, these are stored in ~/.helm
  $HELM_HOST          set an alternative Tiller host. The format is host:port
  $HELM_NO_PLUGINS    disable plugins. Set HELM_NO_PLUGINS=1 to disable plugins.
  $TILLER_NAMESPACE   set an alternative Tiller namespace (default "kube-system")
  $KUBECONFIG         set an alternative Kubernetes configuration file (default "~/.kube/config")

Usage:
  helm [command]

Available Commands:
  [...]
```

There are several reasons why this is excellent:

* Reinforces brand immediately (it's "The Kubernetes package manager")
* Clear call to action (run `helm install`)
* Clear follow-up actions (search for charts, download charts, install)

For the comparatively trivial investment of doing this, it's well worth it for us to do it, too.

cc @lukehoban @joeduffy

**Comment by hausdorff** [comment]
I'm tagging this with `kubernetes/inner-dev-loop` because for the Kubernetes moment, I think we should consider this part of the conversion funnel -- _i.e._, we should find a way to clearly communicate what we can do at a high level (_e.g._, program against multiple clouds), and what to do next for those things (_e.g._, `pulumi new` or something to build or install some simple Kubernetes app).

**Comment by joeduffy** [comment]
Love it.

**Comment by joeduffy** [comment]
I'll take this as part of my overall focus of optimizing our onboarding flow.
