### ISSUE TITLE
Request: Allow to granularly disable policy pack rules

### ISSUE THREAD

**Issue by bcheidemann-kmbal** [pulumi/pulumi#16584]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I would like to use the `@pulumi/awsguard` policy pack to validate my Pulumi infrastructure. This works well, except that several rules in the pack are not applicable to certain resources I have configured. Below is by configuration for `AwsGuard`, which has comments explaining why I need to disable certain rules.

```ts
import { AwsGuard } from "@pulumi/awsguard";

new AwsGuard({
  all: "mandatory",
  apiGatewayEndpointType: "disabled", // No options exist in @pulumi/aws-apigateway to configure these settings
  apiGatewayStageCached: "disabled", // Not currently needed for webhook gateway
  apiGatewayMethodCachedAndEncrypted: "disabled", // Not needed currently for webhook gateway
  ec2VolumeInUse: "disabled", // Not needed for bastion host
  encryptedVolumes: "disabled", // Not applicable since bastion host does not have an EBS volume
  acmCertificateExpiration: "disabled", // This fails with a network error
});
```

Unfortunately, the only way I can find to disable rules is globally.

This is not ideal, as most of the rules I have disabled are disabled due to specific exceptions, while the rule should still be generally applicable.

Ideally, it would be possible to disable specific rules for specific resources. There are many ways this could be implemented, but here is a proposal:

```ts
const bastion = new aws.ec2.Instance(
  "bastion-host",
  {
    // --snip--
  },
  {
    policyPackOverrides: {
      "ec2-volume-inuse": "disabled",
      "encrypted-volumes": "disabled"
    },
  },
);
```

**Comment by bcheidemann-kmbal** [comment]
If this feature request is accepted, I'd probably be happy to implement it :)

**Comment by justinvp** [comment]
Thanks for the suggestion! Providing a way to override policies for specific resources is something we should definitely consider.

**Comment by justinvp** [comment]
Was triaging older issues and came across https://github.com/pulumi/pulumi-policy/issues/240 which is basically the same as this issue, so I'm going to close this one as a duplicate. Consider up-voting https://github.com/pulumi/pulumi-policy/issues/240.

**Comment by bcheidemann** [comment]
@justinvp thats fine thanks for the fyi. It looks like this was closed as "not planned" though which may give the wrong impression to people stumbling across this in future
