### ISSUE TITLE
`pulumi about` lists the same plugin multiple times

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#16604]
### What happened?

I ran `pulumi about` in a directory containing a TypeScript Pulumi program as well as a subdirectory with a TypeScript policy pack, and noticed that the same plugins are listed multiple times.

### Example

```
git clone https://github.com/pulumi/examples.git
cd examples/testing-pac-ts
npm install
```

Run `pulumi about` and the list of plugins looks OK:

```
CLI
Version      3.122.0-dev.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.44.0
resource  awsx        2.13.0
resource  docker      4.5.4
resource  docker      3.6.1
resource  eks         2.7.3
resource  kubernetes  4.14.0
language  nodejs      unknown

Host
OS       darwin
Version  14.5
Arch     arm64

This project is written in nodejs: executable='/Users/justin/.nvm/versions/node/v20.9.0/bin/node' version='v20.9.0'
```

Now, install the policy pack's dependencies:

```
cd tests
npm install
cd ..
```

Now run `pulumi about` again and notice plugins are listed twice:

```
CLI
Version      3.122.0-dev.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.44.0
resource  aws         6.44.0
resource  awsx        2.13.0
resource  docker      4.5.4
resource  docker      3.6.1
resource  eks         2.7.3
resource  eks         2.7.3
resource  kubernetes  4.14.0
resource  kubernetes  4.14.0
language  nodejs      unknown

Host
OS       darwin
Version  14.5
Arch     arm64

This project is written in nodejs: executable='/Users/justin/.nvm/versions/node/v20.9.0/bin/node' version='v20.9.0'
```

### Output of `pulumi about`

See above

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by julienp** [comment]
I had a quick look and noticed that pnpm support is missing from the code that looks for dependencies https://github.com/pulumi/pulumi/issues/16613
