### ISSUE TITLE
odata.error AuthorizationPermissionMismatch randomly

### ISSUE THREAD

**Issue by af-vijay** [pulumi/pulumi#16619]
### What happened?

Hi 

I am trying to do pulumi preview and up from the pipeline using the service principle. It works sometimes and it fails sometimes.

The error is prity confusing as well as it does not give any information what is missing.

### Example

pulumi:pulumi:Stack backend.dev running error: RestError: {"odata.error":{"code":"AuthorizationPermissionMismatch","message":{"lang":"en-US","value":"This request is not authorized to perform this operation using this permission.}

### Output of `pulumi about`

CLI
Version      3.119.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.45.0
language  nodejs        unknown
resource  tls           4.10.0

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v18.16.0'

Current Stack: backend.dev

### Additional context

I think service principle has all the permissions as it work sometime.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
This looks similar to https://github.com/pulumi/pulumi/issues/16587.

Does the following comment help? https://github.com/pulumi/pulumi/issues/16587#issuecomment-2223072970

**Comment by af-vijay** [comment]
We had an issue with upsert blobs. It was very hard to identify across 1000 more resources. It would be better if error messages are more clear, to be honest.
