### ISSUE TITLE
TypeScript: Would be useful to have named types for complex args

### ISSUE THREAD

**Issue by brandonbloom** [pulumi/pulumi#1661]
Seems like this might already be tracked somewhere, but I couldn't find an issue. Apologies if I missed something.

The TypeScript declarations are super helpful for discovering what options are available on various resources. However, there are many deeply nested configuration objects that are built almost entirely of `pulumi.Input`, anonymous objects, and primitives. If you make a small error in a nested attribute, `tsc` produces pretty large and obnoxious error messages that are difficult to read. The entire root configuration object gets a squiggly red underline!

I've found that a great way to deal with this problem is to build up larger objects incrementally and assign explicit types to the intermediate values. Although restructuring syntax helps, this is a little more verbose, but well worth it, as it significantly narrows the scope of compiler errors.

Sometimes, you can use fancy TypeScript features like indexed types to get at a useful anonymous type for this purpose. For example:

```typescript
let defaultCacheBehavior: aws.cloudfront.DistributionArgs['defaultCacheBehavior'] = { ...
```

But that's pretty kludgy and sometimes not possible, for example when something is wrapped in `pulumi.Input<...>[]`.

Would be nice if all of these various properties had usefully named types. For this example, I'd love to write:

```typescript
let defaultCacheBehavior: aws.cloudfront.DefaultCacheBehavior = { ...
```

Generally, there are sensible names for these things in the CloudFormation documentation. Again, for example: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html

**Comment by lukehoban** [comment]
Definitely.  This is tracked by https://github.com/pulumi/pulumi-terraform/issues/163, but since you describe the issue really well here I'll go ahead and copy your comment there as well.

**Comment by brandonbloom** [comment]
Thanks.
