### ISSUE TITLE
pulumi login/update uses wrong GCP service account

### ISSUE THREAD

**Issue by cooervo** [pulumi/pulumi#16635]
### What happened?

i have multiple environments and sometimes when running pulumi login I get errors as if it use using service account of different project.

### Example

`gcloud config configurations activate example-stg-mateo`

Then I source GCP credentials with this helper script

`source scripts/set-google-credentials.sh stg`

content of script:

```
FILE_PATH="scripts/dec.sa-${1}-pulumi-keys.json" # I have decrypted and uncomitted keys at this path

# if file does not exists
if [ ! -f $FILE_PATH ]; then
  echo "\n==> ERROR: File ${FILE_PATH} does not exist, should be downloaded from passwords manager"
fi

# set the Google credentials
export GOOGLE_CREDENTIALS=$(cat $FILE_PATH)

echo "\n==> GCP Credentials for env ${1} successfully set! 👍"
```

finally I do `pulumi login gs://example-pulumi-state-stg` and get error:

```                                 
error: problem logging in: error listing stacks: could not list bucket: blob (code=NotFound): googleapi: Error 403: sa-dev-pulumi@example-dev.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist)., forbidden
```

As you can see it uses service account for `dev` not for `stg` which is wrong.

If I do a purely gcloud command to check impersonation is using `stg` account as expected it works it just pulumi commands using `dev` service account:

```
 gcloud storage buckets list --format=json            

WARNING: This command is using service account impersonation. All API calls will be executed as [sa-stg-pulumi@example-stg.iam.gserviceaccount.com].
```

The above command is using `stg` impersonation as expected which is good.

### Output of `pulumi about`

```                                 
pulumi about
CLI          
Version      3.123.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  gcp         7.29.0
resource  kubernetes  4.11.0
language  nodejs      unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in nodejs: executable='/Users/mateo/.nvm/versions/node/v21.6.0/bin/node' version='v21.6.0'

Dependencies:
NAME                VERSION
@pulumi/kubernetes  4.11.0
@pulumi/pulumi      3.122.0
@types/node         18.19.31
typescript          5.4.5
@pulumi/gcp         7.29.0

Pulumi locates its logs in /var/folders/t_/qlx12ywj7n5g1mlszdlf6wd00000gn/T/ by default
warning: Could not access the backend: error listing stacks: could not list bucket: blob (code=NotFound): googleapi: Error 403: sa-dev-pulumi@example-dev.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist)., forbidden
```

Notice pulumi about also uses wrong `dev` service account

**Comment by justinvp** [comment]
Under the covers we use the Go Cloud Development Kit, to provide support for Google Cloud Storage URLs. The [documentation](https://gocloud.dev/howto/blob/#gcs) mentions:

> `blob.OpenBucket` will use Application Default Credentials; if you have authenticated via [`gcloud auth application-default login`](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login), it will use those credentials. See [Application Default Credentials](https://cloud.google.com/docs/authentication/production) to learn about authentication alternatives, including using environment variables.

I suspect when changing `GOOGLE_CREDENTIALS` you'll have to do an explicit `gcloud auth` or other interaction with the `gcloud` CLI to update the current credentials.

**Comment by mikhailshilkov** [comment]
Since we haven't heard back, I'll assume the last comment addresses the problem and will close the issue. Let us know if you still need help.
