### ISSUE TITLE
Upgrade to TypeScript 3.0

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1668]
Now that TypeScript 3.0 is out, let's migrate to it!

https://t.co/CtNIvumwLl

This includes porting our SDK in addition to all of our examples.

**Comment by CyrusNajmabadi** [comment]
My primary concern here is one of compat.  If we move to TS3 and then use something from TS3 that isn't supported on previous versions, that puts on a burden on customers to have to upgrade.  So, my personal preference would be that we upgrade the version of TS we use if/when there's a feature in it we need which warrants it.  

In other words, we are more compatible with more users, the lower the version of TS that we use.  The 2 line itself has huge adoption, and It's unclear to me what we're necessarily buying by moving away from it. 

--

Now, there are 3.0 features that would be nice to have.  For example, having variadic funtions map help clean up this stuff: https://github.com/pulumi/pulumi/blob/15aca4e9d82010dee93cfb103719cf4f89f893a7/sdk/nodejs/resource.ts#L448-L457

However, as above, it would then force our consumers to be on this version as well.  Is this definitely something that we want to take?

**Comment by lukehoban** [comment]
Note that we did already upgrade `@pulumi/pulumi` to TypeScript 3 in https://github.com/pulumi/pulumi/pull/1669.

In practice, I think that is the only repo that actually needs/has a true `dependencies` on TypeScript (all others are `devDependencies`?).

So I think the part that @CyrusNajmabadi is concerned about (and I agree with him) is already done and shipped.  We just haven't updated devDependencies to match in other repos.

**Comment by CyrusNajmabadi** [comment]
Done.  All relevant projects have been fixed up.
