### ISSUE TITLE
Move `pulumi package {get-sdk,get-sdk}` into `pulumi schema`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#16752]
As discussed, we would like to use `pulumi package` for more user facing commands.

We will explicitly position `pulumi package` as "mid-level" (user facing) commands. We will position `pulumi schema` as low-level package author facing commands.

**Comment by Frassle** [comment]
```
		newExtractSchemaCommand(),
		newExtractMappingCommand(),
		newGenSdkCommand(),
		newPackagePublishCmd(),
		newPackagePackCmd(),
```
That's all the current `package` commands.
```
	cmd.AddCommand(newSchemaCheckCommand())
```
And the one current `schema` command.

I'm not sure all the 'package' commands really make sense as 'schema' commands. Annoyingly 'package' is the common description for a lot of these. 

I get that we want to re-purpose 'package' as a high level command, but we need to work out 
A) Exactly what of the current commands stay as high level things. Is publishing and packing high level? Probably not
B) Where they all go. 'schema' is probably ok for most, but extract-mapping is a provider converter thing, not really anything to do with schema.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3371

**Comment by iwahbe** [comment]
Right now, I see as the clear mapping move: `pulumi package get-schema` -> `pulumi schema get`. Other changes are more contentions. I think this needs more though to actually land.

Ideally, we would have a more complete list of sub-commands before we make this change. I don't think this is part of https://github.com/pulumi/home/issues/3371 anymore.
