### ISSUE TITLE
Parameterization passed in `CheckConfig`'s input with normal configuration

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#16757]
### What happened?

When attempting to use a parameterized provider, I saw the bridge error out:

```
Diagnostics:
  pulumi:providers:random (default_0_0_0_dev):
    error: pulumi:providers:random resource 'default_0_0_0_dev' has a problem: `random:name` is not a valid configuration key for the random provider. If the referenced key is not intended for the provider, please choose a different namespace from `random:`.
    error: pulumi:providers:random resource 'default_0_0_0_dev' has a problem: `random:parameterization` is not a valid configuration key for the random provider. If the referenced key is not intended for the provider, please choose a different namespace from `random:`.
```

Looking at the gRPC message passed on `CheckConfig`, this makes sense:

```json
{
    "method": "/pulumirpc.ResourceProvider/CheckConfig",
    "request": {
        "urn": "urn:pulumi:dev::ian-test-python::pulumi:providers:random::default_0_0_0_dev",
        "olds": {},
        "news": {
            "name": "terraform-provider", <-- THIS SHOULD NOT BE IN NEWS
            "parameterization": { <-- THIS SHOULD NOT BE IN NEWS EITHER
                "value": "eyJyZW1vdGUiOnsidXJsIjoicmVnaXN0cnkub3BlbnRvZnUub3JnL2hhc2hpY29ycC9yYW5kb20iLCJ2ZXJzaW9uIjoiMy42LjIifX0=",
                "version": "3.6.2"
            },
            "version": "0.0.0-dev"
        }
    },
    "response": { ... },
    "metadata": { ... }
}
```

Bridged providers error on unknown keys, so this prevents the provider from working as expected. Even if we filtered out unknown keys called `"name"` or `"parameterization"`, this would prevent a provider from passing these keys organically (since the meaning would be ambiguous).

If we need to pass parameterization values to a provider in `CheckConfig`, we should pass them in a new top-level key, not via `"news"`.

### Example

NA

### Output of `pulumi about`

```
CLI          
Version      3.125.0-dev.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  pinecone       0.4.1
resource  pulumi_alz     0.11.1
resource  pulumi_random  3.6.2
language  python         unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in python: executable='/Users/ianwahbe/Projects/pulumi/langs/python/venv/bin/python' version='3.10.11'

Current Stack: pulumi/ian-test-python/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ian-pulumi-corp
User           ian-pulumi-corp
Organizations  ian-pulumi-corp, pulumi
Token type     personal

Dependencies:
NAME             VERSION
deepdiff         6.2.1
pinecone-pulumi  0.4.1
pip              24.1.2
pulumi_alz       0.11.1
pulumi_random    3.6.2
requests         2.28.1
setuptools       70.3.0
wheel            0.43.0

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default
```

### Additional context

CC @Frassle 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Oh this is the same thing that causes "version" and "pluginDownloadURL" to get passed in news. I think we can filter out these keys engine side.

**Comment by iwahbe** [comment]
It would be great to filter these out, both because it will simplify providers but more importantly because this prevents providers from having configuration called `"version"`, `"pluginDownloadURL"`, `"name"` or `"parameterization"`. I'm not comfortable growing the list of secretly forbidden config options, especially for `"name"` which I imagine could come up as a provider config option.

**Comment by Frassle** [comment]
Aye, we should fix this. Doing that in a way that doesn't break state might be tricky but I think we can do something.
