### ISSUE TITLE
Order of pulumi new args could be improved

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1677]
We got feedback about the `pulumi new` command and, after looking at the sequence of steps that led to this feedback, it occurs to me that the ordering of arguments, etc. is a bit off from what one might expect. The user who reported this tried `pulumi new <project-name>` which, to be honest, is a very reasonable assumption (probably more so than assuming `pulumi new <template>`, which is what we do today). In fact, we later added the `--dir` flag, but it's not at all evident, and is probably what most users will want to do anyway (all of our examples are slowly switching to using it).

A better flow would probably be to

* Use `pulumi new <project-name>`, instead of `pulumi new <template>`
* By default, prompt for the template, as we do today
* Support a `--template` flag for selecting the template if you know it in advance
* Behave as though `--dir <project-name>` were passed by default; if you want the current behavior of running in the current working directory -- probably rare -- you can just do `--dir .`

**Comment by joeduffy** [comment]
We agreed to try to get this into this sprint alongside all the new/up goodies already underway.

**Comment by justinvp** [comment]
Presumably we'd allow `-t` as shorthand for `--template` and support passing URL templates via this flag.

Do we want `pulumi up` to be consistent with `pulumi new`, e.g. `pulumi up -t <url>`, or is the "installable cloud app" concept different enough to warrant `pulumi up <url>`?

@joeduffy, @lukehoban, thoughts?

**Comment by joeduffy** [comment]
Personally I think it's ok to diverge here.

Pulumi new: what are you newing? A new project, not a new template.

Pulumi up: what are you upping? A new stack/program.

So the nouns and verbs check out to me, personally.

**Comment by lukehoban** [comment]
Having looked at some concrete examples of this - I'm worried about this change.  In isolation, I like the original suggestion.  But in practice, I think having `new` and `up` accept the URL in different ways is going to be very confusing.

With the current designs (as I understand them) users will think of `pulumi new` and `pulumi up` as being similar.  `new` gets you the code, `up` deploys, but they start from the same source.  In fact, most sources that are designed to be targets of these commands should support both.

So we'll have instructions that suggest either:

```
$ pulumi up https://github.com/pulumi/eks
```

or 

```
$ pulumi new -t https://github.com/pulumi/eks
```

That `-t` is very surprising in this context.

We're also generally moving away from `pulumi new` being just a "template" thing - the EKS example above is not something users will necessarily think of as a "template" - so suggesting to pass `-t/--template` doesn't "feel" quite right.

It may be that this points to deeper questions about the alignment of these commands, but I'm nervous about just doing a point change to the ordering of arguments on `new` without thinking through the full set of experiences here a bit more deeply.

**Comment by lukehoban** [comment]
Given the issues above, I'm going to close this out for now.  We have a design that is consistent in how it accepts URLs across `new` and `up`.  The change to error on non-empty folders will also help ensure that users create a folder or use `--dir` (via useful help text), which should in general avoid the need for the extra part in the template case.
