### ISSUE TITLE
Add Install to Automation API

### ISSUE THREAD

**Issue by julienp** [pulumi/pulumi#16781]
Make `pulumi install` available from the Automation API. This allows deployments to use the install command.

- [x] Go https://github.com/pulumi/pulumi/pull/16782
- [x] Python https://github.com/pulumi/pulumi/pull/17086
- [x] Nodejs https://github.com/pulumi/pulumi/pull/17134
- [ ] .NET tracked by https://github.com/pulumi/pulumi-dotnet/issues/339

Ref https://github.com/pulumi/pulumi-docker-containers/issues/204

Go is required so we can use it in deployments, other languages are not strictly required but should be implemented to maintain feature parity across languages.

**Comment by justinvp** [comment]
Opened https://github.com/pulumi/pulumi-dotnet/issues/339 to track .NET and closing this as complete.
