### ISSUE TITLE
Nesting PropertyValues inside a NewPropertyMapFromMap, silently fails

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi#16889]
### What happened?

A customer reported trying to set a default value for a nested object property in `Check` silently failed because they used a `resource.NewObjectProperty` instance for the value of a subfield instead of a `map[string]any`. They we're surprised when the subfield was simply missing later in a `Diff`. It would have been far more helpful if they had been given an error (or even better if their original code just worked).

### Example

Given a schema like:

```
{
  data: {
    foo: {
      bar: number
    }
  }
}
```

The user tried to apply defaults like this: 
```
if _, ok := newInputs["data"]; !ok {
  newInputs["data"] = resource.NewObjectProperty(resource.NewPropertyMapFromMap(map[string]any{
    "foo": resource.NewObjectProperty(resource.NewPropertyMapFromMap(map[string]any{
      "bar": resource.NewNumberProperty(0),
    }))),
  })))
}
```

but they apparently should have defined them this way(?):
```
if _, ok := newInputs["data"]; !ok {
  newInputs["data"] = resource.NewObjectProperty(resource.NewPropertyMapFromMap(map[string]any{
    "foo": map[string]any{ "bar": 0 },
  })))
}
```

Ideally, the first way should have returned some sort of error.

### Output of `pulumi about`

not relevant

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This has bitten me in the past, I think we should be ok to just make them flow through.
