### ISSUE TITLE
`SecretsProvider` doesn't get set correctly via automation API

### ISSUE THREAD

**Issue by sfc-gh-jlangefeld** [pulumi/pulumi#16890]
### What happened?

We need to `preview` and `up` stacks via the automation API using go.
We also need to set a `SecretsProvider`, which we do via
```go
	opts := []auto.LocalWorkspaceOption{
		auto.SecretsProvider("passphrase"),
		auto.EnvVars(map[string]string{
			"PULUMI_CONFIG_PASSPHRASE": "my-secret-passphrase",
		}),
	}
```

We create the stack via
```go
	stack, err := auto.UpsertStackInlineSource(
		ctx,
		auto.FullyQualifiedStackName("jonny-langefeld", "test-project", "test-stack"),
		"test-project",
		Run,
		opts...,
	)
```

Then below that we run `stack.Preview()` or `stack.Up()` based on conditions.

Now I found out that if if a stack didn't exist (meaning the `upsert` actually created the stack) and the program only calls `stack.Preview()`, then the `SecretsProvider` isn't set correctly, even after a consecutive execution that calls `stack.Up()`. The Pulumi Cloud UI shows `pulumi:secrets_provider: service` in the tags. But it should show `pulumi:secrets_provider: passphrase`.

### Example

I boiled down below code for a minimal reproduction. The program has a const `runUp = false`. Let's consider that our logic to run `stack.Up()` or not.

The rest of the programs just sets the `SecretsProvider` via `auto.LocalWorkspaceOption`, upserts the stack via `auto.UpsertStackInlineSource()` and then always runs a `stack.Preview()` and conditionally a `stack.Up()`. The pulumi `RunFunc` just returns nil so no resources are getting created:

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/pulumi/pulumi/sdk/v3/go/auto"
	"github.com/pulumi/pulumi/sdk/v3/go/auto/optpreview"
	"github.com/pulumi/pulumi/sdk/v3/go/auto/optup"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

const (
	runUp = true
)

func main() {
	ctx := context.Background()

	opts := []auto.LocalWorkspaceOption{
		auto.SecretsProvider("passphrase"),
		auto.EnvVars(map[string]string{
			"PULUMI_CONFIG_PASSPHRASE": "my-secret-passphrase",
		}),
	}

	stack, err := auto.UpsertStackInlineSource(
		ctx,
		auto.FullyQualifiedStackName("jonny-langefeld", "test-project", "test-stack"),
		"test-project",
		func(ctx *pulumi.Context) error { return nil },
		opts...,
	)
	if err != nil {
		log.Fatal("couldn't create stack", err)
	}

	previewStreamer := optpreview.ProgressStreams(os.Stdout)
	_, err = stack.Preview(ctx, previewStreamer)
	if err != nil {
		log.Fatal("couldn't preview stack", err)
	}

	if runUp {
		upStreamer := optup.ProgressStreams(os.Stdout)
		_, err = stack.Up(ctx, upStreamer)
		if err != nil {
			log.Fatal("couldn't update stack", err)
		}
	}
}
```

If I run this code as is via `go run main.go`, at a time when the stack doesn't exists, the stack successfully gets created (due to the upsert), and I get a preview link printed to screen. The `main` function exits and the program returns.

Then, right after, I change the `runUp` constant to `runUp = true` and then run the program again via `go run main.go`. The preview and the up executed successfully, but the tags in the UI show `pulumi:secrets_provider: service`:

![Image](https://github.com/user-attachments/assets/30dc1187-7e33-4cf0-bfa1-c45164a547c4)

Then delete the entire stack (which is possible because there are 0 resources) and run the program again via `go run main.go`, this time with `runUp = true` enabled from the start. This time the stack creates correctly with `pulumi:secrets_provider: passphrase`.

![Image](https://github.com/user-attachments/assets/eeca42ea-189f-4c63-ac39-c04b4d331fe5)

But this is what should have happened in the first place already. There is no reason some automation shouldn't only be able to run `stack.Preview()`.

### Output of `pulumi about`

```
╰─ pulumi about         
CLI          
Version      3.124.0
Go Version   go1.22.5
Go Compiler  gc

Host     
OS       darwin
Version  14.5
Arch     arm64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/jonny-langefeld
User           jonny-langefeld
Organizations  jonny-langefeld, snowflake
Token type     personal
```

### Additional context

I believe this behavior is due to the local workspace that is created in a temp directory. If `stack.Preview()` and `stack.Up()` are executed in one go, as the second example above shows, they are both in the same local temp workdir. But if they are executed in two consecutive runs of the go program, then they have different local temp workdirs per run. And if the first run only executed a `stack.Preview()`, then the `SecretsProvider` isn't persisted in the state yet. However I'd say it's still unexpected behavior.

One workaround I found is to always call `stack.ChangeSecretsProvider(ctx, auto.SecretsProvider("passphrase"), nil)` no matter what. However this is not ideal as it executes `pulumi stack change-secrets-provider`, which always creates an empty update. And we call this code quite often in automation to ensure there are no changes and we would like to keep the update history down to actual infrastructure changes.

I'd be happy to learn that there is another workaround or that I'm using the API wrong. But given the behavior I would still say it's unexpected that the stack is manifested with a false secret provider for ever, if only a `pulumi.Preview()` is run initially via the automation API.

This failure matters to us as we always have our automation do a preview first and if there are changes detected it runs an update. This same behavior frequently happens on new stacks that are created on the fly via the upsert method. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Thanks for the repo. On first guess I'm not sure if this is an Automation API bug or just an issue in the engine, but should be able to work that out pretty quickly from the info you've given here.

**Comment by Frassle** [comment]
> I believe this behavior is due to the local workspace that is created in a temp directory.

Your assessment here seems correct. The secret provider is saved to state if a full update runs but also to the local "Pulumi.<stack>.yaml" config file. For an inline program though that file is just in the temp directory and not persisted between runs, and as `stack init` doesn't write it to state, come the next update the secret provider that was set is lost entirely. So given no info the engine falls back to using the service secret provider by default.

I'll have to talk to the team about this. It's going to probably require support from the service to persist this data somehow given the constraint that Automation API is running things in temporary directories.

**Comment by justinvp** [comment]
Just a quick update: We're working towards a fix that doesn't involve doing the "empty" import update, so that the stack's update history remains clean.
