### ISSUE TITLE
Add a supports feature flag for parameterised providers

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi#16906]
Before we ship param providers publicly we should update the engine to advertise a feature flag that it supports param providers (or more likely that we support package_refs, because that's what the SDKs are actually going to look for).

The SDKs then need updating to look for that feature flag and failing for param sdks if it's not true.

We should also bump the minimum core SDK version specified by parameterised SDKs (probably not _all_ SDKs because that's a very large change with massive downstream effects).

The core SDK change to look for the feature flag and the minimum version change will need doing for each language.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3371

**Comment by Frassle** [comment]
Think this is done for everything but Java now.
