### ISSUE TITLE
Install command fails in clean environment

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi#16920]
### What happened?

Trying to run `pulumi install` on the `random-yaml` example, fails with:
```
resource plugin random installing
warning: Error downloading plugin: unknown version for plugin random
Will retry in 80ms [1/5]
warning: Error downloading plugin: unknown version for plugin random
Will retry in 160ms [2/5]
warning: Error downloading plugin: unknown version for plugin random
Will retry in 320ms [3/5]
warning: Error downloading plugin: unknown version for plugin random
Will retry in 640ms [4/5]
warning: Error downloading plugin: unknown version for plugin random
Will retry in 1.28s [5/5]
error: resource plugin random downloading from : failed to download plugin: random: failed all 5 attempts
```

### Example

1. Check out https://github.com/pulumi/examples/tree/master/random-yaml
2. Set `PULUMI_HOME` to a temporary directory, to ensure that there's no pre-installed plugins.
3. Run `pulumi install`.

For example:
```
cd random-yaml
PULUMI_HOME=./.pulumi pulumi install
```

### Output of `pulumi about`

```
CLI          
Version      3.121.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  random  unknown
language  yaml    unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in yaml

Backend        
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations  
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/d4/bznc6qv135qc7ngyh8ld56lm0000gn/T/ by default
warning: Failed to get information about the current stack: No current stack

```

### Additional context

Note that `pulumi up` works as expected, suggesting that the automatic plugin installation logic is smarter about picking the latest version as opposed to erroring out.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by brandonpollack23** [comment]
I'm taking a look at this now, here are some notes:

* The "install.go" command uses GetPlugins which gets the list (via visitor pattern on yaml) from a grpc call to pulumi-language-yaml
* install doesn't seem to do this directly at the top level so I'm still seeing how it pulls this from the language plugin binary.  Will update shortly

**Comment by brandonpollack23** [comment]
It's a little tangley to handle sharing code at first so I'll split into two commits to get something working first
