### ISSUE TITLE
Improve error reporting experience

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1694]
Here's an error message thats not uncommon to see:

```
$ pulumi up
Performing changes:

     Type    Name    Status        Info
 *   global  global  unchanged     1 info message

Diagnostics:
  global: global
    info: We failed to locate the entry point for your program: /Users/luke/dd/pulumidemos/test123
    Here's what we think went wrong:
      * Your program looks like it has a build script associated with it ('tsc').
    Pulumi does not run build scripts before running your program. Please run 'tsc', 'yarn build', or 'npm run build' and try again.

error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

A few things we should do to improve this:

- [ ] Don't include “there was an error advancing the preview”. That layer of feedback isn't useful. 
- [ ] Don't include “program exited with non-zero exit code”. This is simply not something that happened from the users perspective. 
- [ ] Avoid included `global:global` (and possibly also avoid the extra indentation) for messages that are general and not tied to a resource.
- [ ] It’s unclear why we report both a info and an error diagnostic here. We should be able to report only one. 

Also - this specific error message would not be necessary in the first place if we addressed https://github.com/pulumi/pulumi/issues/958 and avoided the need for an explicit TypeScript build.

**Comment by swgillespie** [comment]
We've made good progress towards improving the above error message but not enough that I feel comfortable closing this issue. I do consider the M17 portion of this issue closed.

**Comment by swgillespie** [comment]
I feel bad punting this repeatedly, but I don't have the bandwidth to tackle this in M21.

**Comment by swgillespie** [comment]
Co-signing this with @CyrusNajmabadi, who has been doing some work in this area.

**Comment by CyrusNajmabadi** [comment]
Yup.  @swgillespie's `Result` work makes this all possible.  I've been making a series of refactorings to help out here with the goal of nailing tihs scenario.  https://github.com/pulumi/pulumi/pull/2554 was a large PR to do this.  But we've decided to break it up into smaller refactorings to make it simpler and easier to go in.  Will get to this this week.
