### ISSUE TITLE
Pulumi v3.128.0 flag 'create' K8S resources without creating them

### ISSUE THREAD

**Issue by btbenjamin** [pulumi/pulumi#16944]
### What happened?

Description:

Since upgrading to Pulumi v3.128.0 (github action), running pulumi up results in the destruction of Kubernetes resources without recreating them, even though they are marked as "create" in the console output.

![Image](https://github.com/user-attachments/assets/ec29dae8-fb15-42fb-91ad-f45475d71ead)

Reinstalling Pulumi v3.127.0 (force install) resolves the issue.

### Example

![Image](https://github.com/user-attachments/assets/ec29dae8-fb15-42fb-91ad-f45475d71ead)

### Output of `pulumi about`

 +  kubernetes:core/v1:ConfigMap ocelot-configMap create 
 +  kubernetes:core/v1:Service document-service create 
 +  kubernetes:apps/v1:Deployment metabase-deployment create 
 +  kubernetes:core/v1:Service email-service create 
 +  kubernetes:apps/v1:Deployment project-deployment create 
 +  kubernetes:apps/v1:Deployment payment-deployment create 
 +  kubernetes:apps/v1:Deployment identity-deployment create 
 +  kubernetes:core/v1:ConfigMap ocelot-configMap create 
 +  kubernetes:apps/v1:Deployment webapp-deployment create 
 +  kubernetes:apps/v1:Deployment ocelot-deployment create 
 +  kubernetes:apps/v1:Deployment metabase-deployment create 
 +  kubernetes:apps/v1:Deployment project-deployment create 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Sorry for the trouble @btbenjamin.

Can you provide more details so we can try to reproduce the behavior you're seeing?

1. What language is your Pulumi program using?
2. Can you provide a list of dependencies your program is using and their versions? i.e. what version of pulumi-kubernetes?
3. Can you share your program or a minimal snippet that we can attempt to use to reproduce?
4. What changes did you make to the program as part of the `pulumi up` operation where you saw this?

**Comment by btbenjamin** [comment]
Hello @justinvp,

Thank you for your interest in.

1. I'm using Typescript language

2.
```
        "@pulumi/pulumi": "3.116.0",
        "@pulumi/openstack" : "3.15.2",
        "@pulumi/kubernetes" : "4.11.0",
        "@pulumi/aws" : "6.35.0"
```

3.
Exemple of deployment creation file 

```
import * as k8s from "@pulumi/kubernetes";
import { PodConfig } from '../../Model/PodConfig';
import { METABASE_ENV } from "../../Constants";

export default function Main(podConfig: PodConfig) {

  const imageName: string = `metabase/metabase`;

  let metabaseSettingObject = .....

  console.log("Benjamin metabaseSettingObject", metabaseSettingObject)

  var deploy = new k8s.apps.v1.Deployment(`${podConfig.apiName}-deployment`, {
    apiVersion: "apps/v1",
    kind: "Deployment",
    metadata: {
      name: `${podConfig.apiName}-deployment`,
      labels: {
        app: `${podConfig.apiName}-deployment`,
      },
    },
    spec: {
      replicas: podConfig.replicat || 1,
      selector: {
        matchLabels: {
          app: `${podConfig.apiName}-deployment`,
        },
      },
      template: {
        metadata: {
          labels: {
            app: `${podConfig.apiName}-deployment`,
          },
        },
        spec: {
          containers: [
            {
              name: `${podConfig.apiName}-container`,
              image: imageName,
              ports: [
                {
                  containerPort: 80,
                },
              ],
              imagePullPolicy: "Always",
              env: metabaseSettingObject
            },
          ],
        },
      },
    },
  });
}
```


4. I haven't changed my program. It's been my CI/CD github action for 6 months. I'm only changing the version of the docker images that I inject into my program.

Thank you for your help

**Comment by btbenjamin** [comment]
@justinvp ,

I updated all my dependency is look better : 

```

        "@pulumi/pulumi": "3.129.0",
        "@pulumi/openstack" : "4.1.1",
        "@pulumi/kubernetes" : "4.16.0",
        "@pulumi/aws" : "6.49.0"
```

**Comment by tgummerer** [comment]
> But is look you have some issue with you pulumi version

This looks like you're installing a newer pulumi version, but not changing your `$PATH` variable to put that first.  The best way to always get the latest pulumi version in GitHub actions is to use the `pulumi/actions`  like follows:

```
- uses: pulumi/actions@v5
  with:
    pulumi-version: latest
```
