### ISSUE TITLE
Enable installing binaries from PRs

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#16960]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

To assist contributors and reviewers in evaluating changes, we should enable installing Pulumi using the binaries built from a pull request. 

For safety, we may want to limit this to contributions from trusted contributors or pull requests built from branches (not forks).

### Affected area/feature

- CI

**Comment by Frassle** [comment]
@tgummerer might know this better, but I think we already build the binaries for every PR and push them to GitHub artefacts. Maybe there's a simple way to pull those back down?

**Comment by AaronFriel** [comment]
I made this issue so I can close it :) 

Yes, PRs already build artifacts, we just don't have a way of installing them via the `get.pulumi.com` script

**Comment by tgummerer** [comment]
@AaronFriel given https://github.com/pulumi/get.pulumi.com/pull/180 is merged I'm assuming this is all done now, and this issue can be closed out?

**Comment by AaronFriel** [comment]
Left open intentionally, will close with a PR that adds a comment describing how to install the CI built release and extending the retention period to 1 week.

**Comment by AaronFriel** [comment]
Closing as complete - technically possible due to get.pulumi.com updates - due to lack of agreement on #17015.

**Comment by Frassle** [comment]
I think as suggested by @tgummerer in https://github.com/pulumi/pulumi/pull/17015/files#r1722817544 we should document this in CONTRIBUTING.md.
