### ISSUE TITLE
pulumi state move fails when providers have the same URN, but different IDs.

### ISSUE THREAD

**Issue by nickroberts** [pulumi/pulumi#16983]
### What happened?

When trying to move resources from one stack to another existing stack, it fails because the provider already exists (the custom provider is of type `pulumi:providers:aws`).

```shell
pulumi state move --source '<source-stack>' --dest '<destination-stack>' '<urn>' 
error: provider '<custom-provider-urn>' already exists in destination stack
```

This was updated in [16737](https://github.com/pulumi/pulumi/pull/16737), however, it is checking the IDs, along with the URNs. If the provider has already been created, the IDs will be different.

[Someone mentioned](https://github.com/pulumi/pulumi/pull/16737#issuecomment-2291104526) maybe we check the inputs instead of the ID. That could possibly work, looking at the provider json for each. It might help that our code is in a monorepo, so versions are the same.

In the meantime, I am testing updating the target stack provider's ID to match the source stack, and it seems to work...however, I'm not sure if there are any other issues if I do that.

### Example

1. Create stack 1 with an aws custom provider, along with a resource, update the stack.
2. Create stack 2 with an aws custom provider, update the stack.
3.  pulumi state move --source 'stack-1' --dest 'stack-2' '<urn>'

You will get the error message:
> `error: provider '<custom-provider-urn>' already exists in destination stack`

### Output of `pulumi about`

```shell
CLI
Version      3.129.0
Go Version   go1.22.6
Go Compiler  gc
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening the issue @nickroberts!

**Comment by SineLung** [comment]
@nickroberts 

> In the meantime, I am testing updating the target stack provider's ID to match the source stack, and it seems to work...however, I'm not sure if there are any other issues if I do that.

How do we update a stack provider's ID to match the source stack provider's ID? Isn't the ID generated randomly?

**Comment by stanvarlamov** [comment]
Seeing the same error after upgrading from version '3.167.0' to '3.169.0'. A similar move worked before the upgrade

Source
```
pulumi:providers:aws     default_6_37_1
          URN: urn:pulumi:qa::qa-my-server::pulumi:providers:aws::default_6_37_1
```
Destination
```
pulumi:providers:aws                   default_6_37_1
          URN: urn:pulumi:dev::qa-my-server-task::pulumi:providers:aws::default_6_37_1
```

Command and error
```
pulumi state move --dest organization/qa-my-server-task/dev urn:pulumi:qa::qa-my-server::aws:ecs/service:Service::qa-my-server-abcd
error: provider urn:pulumi:dev::qa-my-server-task::pulumi:providers:aws::default_6_37_1 already exists in destination stack
```

**Comment by Frassle** [comment]
@stanvarlamov probably that the provider config was different between the two stacks. Error message could probably be more clear about that.

**Comment by stanvarlamov** [comment]
@Frassle I checked the content in JSONs - no apparent to me differences that would cause an error

Source
```
{
                    "urn": "urn:pulumi:qa::qa-my-server::pulumi:providers:aws::default_6_37_1",
                    "custom": true,
                    "id": "b595945a-2cfb-4723-9cf8-82f2ddaeaa6f",
                    "type": "pulumi:providers:aws",
                    "inputs": {
                        "__internal": {},
                        "region": "us-west-2",
                        "skipCredentialsValidation": "false",
                        "skipRegionValidation": "true",
                        "version": "6.37.1"
                    },
                    "outputs": {
                        "region": "us-west-2",
                        "skipCredentialsValidation": "false",
                        "skipRegionValidation": "true",
                        "version": "6.37.1"
                    },
                    "created": "2025-02-21T15:14:04.021619Z",
                    "modified": "2025-02-21T21:52:16.206201Z"
                },
```
Target
```
{
                    "urn": "urn:pulumi:dev::qa-my-server-task::pulumi:providers:aws::default_6_37_1",
                    "custom": true,
                    "id": "a6ea909e-c22c-4d37-af0f-832adf238ec0",
                    "type": "pulumi:providers:aws",
                    "inputs": {
                        "__internal": {},
                        "region": "us-west-2",
                        "version": "6.37.1"
                    },
                    "outputs": {
                        "region": "us-west-2",
                        "version": "6.37.1"
                    },
                    "created": "2025-05-06T19:55:16.500962Z",
                    "modified": "2025-05-06T19:55:16.500962Z"
                },
```

**Comment by Frassle** [comment]
Those inputs are different. The first has skipCredentialsValidation and skipRegionValidation, the later doesn't. That's enough for the engine to say it's not a safe move.

**Comment by stanvarlamov** [comment]
Interesting. Both were created by clicking through the defaults in `pulumi new aws-go`, except the Region was typed in as an override over `us-east-1`, as well as `export PULUMI_CONFIG_PASSPHRASE=''` was likely applied in the terminal before creating the Target but not the Source. It appears that the internal defaulting might have changed in the version used when creating the Target on 2025-05-06 vs. that for the Source back on 2025-02-21. 
What would be the recommended fix to adjust the providers to match close enough for the move to work?

**Comment by stanvarlamov** [comment]
Here's what I've done in the Source stack:
```
export EDITOR=vim
pulumi state edit
```
removed the extra lines from the provider's definition, accepted the edits. The move worked after that.
