### ISSUE TITLE
Pulumi CLI crashes when selecting detail output of pulumi up

### ISSUE THREAD

**Issue by quepcompute** [pulumi/pulumi#17000]
### What happened?

Pulumi CLI crashes when selecting detail output of pulumi up

### Example

envoy = Chart(
    "envoy",
    ChartOpts(
        repo="oci://registry-1.docker.io",
        chart="bitnamicharts/contour",
        namespace=ENVOY_NAMESPACE,
        values={
            "contour":{
                "envoy":{
                    "service":{
                        "type": "LoadBalancer",
                        # "annotations": ""
                    }
                }
            }            

        }, 

      ),

    ),
    opts=ResourceOptions(provider=k8s_provider),
)

### Output of `pulumi about`

Pulumi Version:   v3.94.2
Go Version:       go1.21.4
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/debug/stack.go:24 +0x64
main.panicHandler(0x14003f6beff)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/cmd/pulumi/main.go:35 +0x44
panic({0x105018ee0?, 0x14003490fd8?})
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/panic.go:914 +0x218
gopkg.in/yaml%2ev3.handleErr(0x14003f65900)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:294 +0x80
panic({0x105018ee0?, 0x14003490fd8?})
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/panic.go:914 +0x218
reflect.Value.typeSlow({0x0?, 0x0?, 0x14003fa9000?})
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/reflect/value.go:2634 +0x134
reflect.Value.Type(...)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/reflect/value.go:2629
gopkg.in/yaml%2ev3.(*decoder).unmarshal(0x14000a64700, 0x140036c9d60, {0x0?, 0x0?, 0x1504b0ec8?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.1/decode.go:492 +0x110
gopkg.in/yaml%2ev3.(*Decoder).Decode(0x14003f659a8, {0x0, 0x0})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:131 +0x1d8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).decodeValue.func1()
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:1245 +0x314
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).decodeValue(0x104f34980?, {0x14001338b00, 0x147})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:1258 +0x4c
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPrimitivePropertyValue(0x14003f66128, {{0x104f34980, 0x14002eb92c0}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:830 +0x1e4
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14003f66128, {{0x104f34980, 0x14002eb92c0}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:565 +0x890
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectProperty(0x10536fd80?, {0x1400370c6c0?, 0x1400370c6c0?}, {{0x104f34980?, 0x14002eb92c0?}}, 0x1?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:248 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObject(0x10536fd80?, 0x104585858?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:241 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14003f66518, {{0x10536fd80, 0x14002c82fc0}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:625 +0x634
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectProperty(0x10536fd80?, {0x1400370c6b8?, 0x1400370c6b8?}, {{0x10536fd80?, 0x14002c82fc0?}}, 0x1?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:248 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObject(0x10536fd80?, 0x104585858?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:241 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14003f66908, {{0x10536fd80, 0x14002c82ed0}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:625 +0x634
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectProperty(0x10536fd80?, {0x1400370c620?, 0x1400370c620?}, {{0x10536fd80?, 0x14002c82ed0?}}, 0x1?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:248 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObject(0x10536fd80?, 0x104585858?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:241 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14003f66cf8, {{0x10536fd80, 0x14002c82ea0}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:625 +0x634
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectProperty(0x10536fd80?, {0x1400370c5db?, 0x1400370c5db?}, {{0x10536fd80?, 0x14002c82ea0?}}, 0x1?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:248 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObject(0x10536fd80?, 0x104585858?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:241 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14003f670e8, {{0x10536fd80, 0x14002c82e70}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:625 +0x634
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectProperty(0x10536fd80?, {0x1400370c5b0?, 0x1400370c5b0?}, {{0x10536fd80?, 0x14002c82e70?}}, 0x1?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:248 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObject(0x10536fd80?, 0x104585858?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:241 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14003f674d8, {{0x10536fd80, 0x14002c82e40}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:625 +0x634
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectProperty(0x10536fd80?, {0x1400370c5a0?, 0x1400370c5a0?}, {{0x10536fd80?, 0x14002c82e40?}}, 0x1?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:248 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObject(0x10536fd80?, 0x104585858?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:241 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14003f678c8, {{0x10536fd80, 0x14002c82e10}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:625 +0x634
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectProperty(0x10536fd80?, {0x1400370c588?, 0x1400370c588?}, {{0x10536fd80?, 0x14002c82e10?}}, 0x1?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:248 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObject(0x10536fd80?, 0x104585858?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:241 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14003f67cb8, {{0x10536fd80, 0x14002c82540}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:625 +0x634
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectProperty(0x10536fd80?, {0x14001ccf940?, 0x14001ccf940?}, {{0x10536fd80?, 0x14002c82540?}}, 0x1?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:248 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObject(0x10536fd80?, 0x104585858?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:241 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14003f680a8, {{0x10536fd80, 0x14002c82510}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:625 +0x634
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectProperty(0x10536fd80?, {0x14001ccf930?, 0x14001ccf930?}, {{0x10536fd80?, 0x14002c82510?}}, 0x1?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:248 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObject(0x10536fd80?, 0x104585858?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:241 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14003f68498, {{0x10536fd80, 0x14002c824e0}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:625 +0x634
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectProperty(0x10536fd80?, {0x14001ccf928?, 0x14001ccf928?}, {{0x10536fd80?, 0x14002c824e0?}}, 0x1?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:248 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObject(0x10536fd80?, 0x104585858?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:241 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14001aecde0, {{0x10536fd80, 0x14002c824b0}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:625 +0x634
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14003f68ba8, {{0x104efb480, 0x140038030b0}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:574 +0xb40
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectProperty(0x10536fd80?, {0x14001ccf910?, 0x14001ccf910?}, {{0x104efb480?, 0x140038030b0?}}, 0x1?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:248 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObject(0x10536fd80?, 0x104585858?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:241 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printPropertyValue(0x14003f68d88, {{0x10536fd80, 0x14002c82450}})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:625 +0x634
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObjectProperty(0x10536fd80?, {0x14001ccf88c?, 0x14001ccf88c?}, {{0x10536fd80?, 0x14002c82450?}}, 0x1028932f4?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:248 +0x48
github.com/pulumi/pulumi/pkg/v3/backend/display.(*propertyPrinter).printObject(0x5a?, 0xecf4?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:241 +0xf8
github.com/pulumi/pulumi/pkg/v3/backend/display.PrintObject(0x140000d32b0?, 0x14000468300?, 0x38?, 0x102894ef8?, {0x10458ecf4?, 0x140000d32b0?}, 0x0?, 0x0?, 0x0?)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:230 +0x74
github.com/pulumi/pulumi/pkg/v3/backend/display.getResourcePropertiesDetails({{0x10458ecf4, 0x6}, {0x14000eaefd0, 0xa2}, {0x14001d19100, 0x3b}, 0x0, 0x14001d7a1b0, 0x14001d7a240, {0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/object_diff.go:189 +0xc0
github.com/pulumi/pulumi/pkg/v3/backend/display.renderDiff({_, _}, {{0x10458ecf4, 0x6}, {0x14000eaefd0, 0xa2}, {0x14001d19100, 0x3b}, 0x0, 0x14001d7a1b0, ...}, ...)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/diff.go:400 +0x288
github.com/pulumi/pulumi/pkg/v3/backend/display.renderDiffResourcePreEvent({{{0x10458ecf4, 0x6}, {0x14000eaefd0, 0xa2}, {0x14001d19100, 0x3b}, 0x0, 0x14001d7a1b0, 0x14001d7a240, {0x0, ...}, ...}, ...}, ...)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/diff.go:421 +0x2bc
github.com/pulumi/pulumi/pkg/v3/backend/display.RenderDiffEvent({{0x1045be654?, 0x104f34980?}, {0x1051fd7e0?, 0x14000be0960?}}, 0x105195440?, {{0x10458eefe, 0x6}, 0x0, 0x0, 0x0, ...})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/display/diff.go:122 +0x40c
github.com/pulumi/pulumi/pkg/v3/backend.createDiff({0x14000100900?, 0x14003321e38?}, {0x14001b4c800, 0x3d, 0x102e52f50?}, {{0x10458eefe, 0x6}, 0x0, 0x0, 0x0, ...})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/apply.go:322 +0x14c
github.com/pulumi/pulumi/pkg/v3/backend.confirmBeforeUpdating({_, _}, {_, _}, {_, _, _}, _, {{{0x106a5a380, 0x0, ...}, ...}, ...})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/apply.go:224 +0x4fc
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt({_, _}, {_, _}, {_, _}, {0x14002040160, {0x1400005eea0, 0x46}, {0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/apply.go:161 +0x488
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0x14002040160, {0x1400005eea0, 0x46}, {0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/apply.go:247 +0xbc
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Update(_, {_, _}, {_, _}, {0x14002040160, {0x1400005eea0, 0x46}, {0x0, 0x0, ...}, ...})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/httpstate/backend.go:1027 +0x90
github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0x14002040160, {0x1400005eea0, 0x46}, {0x0, 0x0, 0x0}, ...})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/stack.go:94 +0x88
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Update(_, {_, _}, {0x14002040160, {0x1400005eea0, 0x46}, {0x0, 0x0, 0x0}, 0x1400201c708, ...})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/backend/httpstate/stack.go:171 +0x64
main.newUpCmd.func1({_, _}, {{{0x106a5a380, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x7fffffff, 0x0, ...}, ...}, ...)
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/cmd/pulumi/up.go:182 +0xac8
main.newUpCmd.func3(0x0?, {0x106a5a380, 0x0, 0x0?})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/cmd/pulumi/up.go:513 +0x7cc
main.newUpCmd.RunResultFunc.func4(0x14002120b00?, {0x106a5a380, 0x0, 0x0})
	/private/tmp/pulumi-20231117-4002-1k4ryyk/sdk/go/common/util/cmdutil/exit.go:115 +0x34
github.com/spf13/cobra.(*Command).execute(0x1400050e300, {0x106a5a380, 0x0, 0x0})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x14001ef6000)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/private/tmp/pulumi-20231117-4002-1k4ryyk/pkg/cmd/pulumi/main.go:56 +0x54

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
This looks like the same issue as #14558, which was fixed in v3.96.0 of the Pulumi CLI in December 2023. Closing this as a dupe.

Please upgrade to a more recent version of the CLI. The latest version is v3.129.0.
