### ISSUE TITLE
read-package-tree silently ignores failures, leading to potentially empty node_modules being uploaded

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#1702]
read-package-tree will silently succeed, even if it can't read the package.json file (using hte read-package-json library).  This can happen for any number of reasons (for example, an invalid sem-ver in the file).  We need to check and see if htat happened and give an appropriate error so that we don't seem to succeed.  Otherwise, the user will silently end up with a completely broken lambda.

**Comment by lukehoban** [comment]
@CyrusNajmabadi This was fixed, right?
