### ISSUE TITLE
pulumi stack change-secrets-provider not working when using KMS provider in conjunction with an ARN for the key

### ISSUE THREAD

**Issue by gunniwho** [pulumi/pulumi#17022]
### What happened?

I'm trying to change secrets provider for an existing stack to AWS KMS using the key ARN to specify the key. I get an error when following the documentation and a different error when following the suggested workaround in https://github.com/pulumi/pulumi/issues/5074.

### Example

When running
```
pulumi stack change-secrets-provider "awskms://arn:aws:kms:us-east-1:ACCOUNT_ID:key/KEY_ID"
```
I get the error
```
unable to parse the secrets provider URL: parse ... invalid port ":key" after host
```
and when running (note triple slashes as per https://github.com/pulumi/pulumi/issues/5074)
```
pulumi stack change-secrets-provider "awskms:///arn:aws:kms:us-east-1:ACCOUNT_ID:key/KEY_ID"
```
I get error
```
secrets (code=NotFound): NotFoundException: Invalid arn us-east-1
```

### Output of `pulumi about`

```
CLI
Version      3.121.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.19.0
resource  kubernetes  3.1.2
language  nodejs      unknown

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22631 Build 22631
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v18.16.1'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Which region is your KMS key in? I just tried running `pulumi stack change-secrets-provider` for a key in us-west-2 (with that specified in for the ARN, and it worked without any errors.

```
pulumi stack change-secrets-provider "awskms:///arn:aws:kms:us-west-2:ACCOUNT_ID:key/KEY_ID"
```

If I specify `us-east-1`, I get the `secrets (code=NotFound): NotFoundException: Invalid arn us-east-1` error, because my key isn't in `us-east-1`.

**Comment by gunniwho** [comment]
Apologies, it seems to be working now. Must have been an IAM issue or something...
