### ISSUE TITLE
Support `uv` as package manager for Python projects

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#17031]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The people from Astral built `uv`, a tool replacing `pip` and doing much more. In their own words:

> an end-to-end solution for managing [Python projects](https://docs.astral.sh/uv/guides/projects/), [command-line tools](https://docs.astral.sh/uv/guides/tools/), [single-file scripts](https://docs.astral.sh/uv/guides/scripts/), and even [Python itself](https://docs.astral.sh/uv/guides/install-python/).

Blog article: https://astral.sh/blog/uv-unified-python-packaging
Docs: https://docs.astral.sh/uv/

### Affected area/feature

Python language runtime

**Comment by mkleinbort** [comment]
Yes please!

**Comment by dhillondeep** [comment]
This would be amazing!!

**Comment by oleksandr-holan** [comment]
+

**Comment by phitoduck** [comment]
Fairly new pulumi user here. It caught me off guard that pulumi takes a stance on which package manager you should use. I happened to be using `uv` and `pulumi` kept telling me that the SDK wasn't installed. Pretty confusing for a newcomer. Eventually I learned I needed `pip`.

**Comment by bensi94** [comment]
Not perfect by any means, but I created a script I use as a workaround.

I set my options in  `Pulumi.yaml` as:

```yaml
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: dist/.venv
```

Then instead of for example `uv run pulumi up` I run `./pulumi.sh up`.

The script `pulumi.sh`:

```bash
#!/bin/bash

DIST="dist"

if [ ! -d "DIST" ]; then
    mkdir "$DIST"
fi

function create_virtualenv() {
  rm -rf dist/.venv
  uv run python -m venv dist/.venv
  source dist/.venv/bin/activate
  pip install -r dist/requirements.txt
}

NEW_REQUIREMENTS=$(uv export)

if [ -f "dist/requirements.txt" ]; then
  NEW_REQUIREMENTS_CHECKSUM=$(cksum <<< "$NEW_REQUIREMENTS" | cut -f 1 -d ' ')
  OLD_REQUIREMENTS_CHECKSUM=$(cksum <<< cat dist/requirements.txt | cut -f 1 -d ' ')

  if [ "$NEW_REQUIREMENTS_CHECKSUM" != "$OLD_REQUIREMENTS_CHECKSUM" ]; then
    echo "$NEW_REQUIREMENTS" > dist/requirements.txt
    create_virtualenv
  else
    source dist/.venv/bin/activate
  fi
else
    echo "$NEW_REQUIREMENTS" > dist/requirements.txt
    create_virtualenv
fi

pulumi "$@"
```

Maybe it helps someone 🙏
