### ISSUE TITLE
Panic on ^C path

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1706]
While tracking down another bug, I was trying to cancel a `pulumi destroy` at various points.

```
^Cpanic: send on closed channel

goroutine 249 [running]:
github.com/pulumi/pulumi/cmd.cancellationScopeSource.NewScope.func1(0xc420442040, 0xc4203f8040, 0xc4204ca000, 0xc420680000, 0xc4203f8060)
        /Users/chris/go/src/github.com/pulumi/pulumi/cmd/util.go:472 +0x322
created by github.com/pulumi/pulumi/cmd.cancellationScopeSource.NewScope
        /Users/chris/go/src/github.com/pulumi/pulumi/cmd/util.go:451 +0xf6
```

It looks like we have an apparent data race, as we try to send the "update cancelled" message to the closed `events` channel.
https://github.com/pulumi/pulumi/blob/master/cmd/util.go#L472

**Comment by joeduffy** [comment]
I just hit this too.
