### ISSUE TITLE
Python project using Poetry and a main directory requires superfluous pyproject.toml

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi#17075]
### What happened?

When using Python with Poetry, while having a main directory configured in Pulumi.yaml, `pulumi install` gives an error regarding a missing `pyproject.toml`. The workaround is having two `pyproject.toml` files, one in the project directory, another one in the main directory, but the only use that's used is the project directory one.

### Example

I've created a minimal Pulumi Python project:

**Pulumi.yaml**

```
name: example
runtime:
  name: python
  options:
    toolchain: poetry
main: src
```

**pyproject.toml**

```
[tool.poetry]
package-mode = false
```

**src/**

```
<empty directory>
```

When running `pulumi install` I get an error complaining about a missing file in the main directory:

```
$ pulumi install
Installing dependencies...

error: installing dependencies: could not find pyproject.toml or requirements.txt in /tmp/example/src
```

If I move the `pyproject.toml` file to the main directory, then I get an error complaining about a missing file in the project directory:

```
$ mv pyproject.toml src/
$ pulumi install
Installing dependencies...


Poetry could not find a pyproject.toml file in /tmp/example or its parents
error: installing dependencies: exit status 1
```

If I move the `pyproject.toml` file back to the project directory and create an empty file in the main directory, it works:

```
$ mv src/pyproject.toml .
$ touch src/pyproject.toml
$ pulumi install
Installing dependencies...

Creating virtualenv <redacted> in <redacted>
Updating dependencies
Resolving dependencies...

Writing lock file
Finished installing dependencies
```

The contents of the `pyproject.toml` file in the main directory don't matter, it's always ignored. 

### Output of `pulumi about`

```
CLI
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  python  unknown

Host
OS       ubuntu
Version  24.04
Arch     x86_64

Backend
URL            file://~/pulumi-state-tmp
Organizations
Token type     personal

Dependencies:
NAME  VERSION
pip   24.0

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by julienp** [comment]
Thank you for the detailed description and repro case! It looks like we're always executing `poetry` from the project directory, but we have a check that looks for a `pyproject.toml` in the main directory. That check should probably look in parent folders.

**Comment by Frassle** [comment]
I suspect one of these is looking at the project directory and one the program directory and in most cases those are the same so it hasn't mattered. I think the program directory is the correct place for the file.

**Comment by Sodki** [comment]
Thank you for looking into this.

@frassle Ideally we should be able to have the file in any of those directories, but if it's just the one then I think the project directory is more suitable, since there is a lot of CI tooling that expects those kind of files to be present at the root level of a repository.

**Comment by julienp** [comment]
With https://github.com/pulumi/pulumi/pull/17388 we now start looking in the program directory and search upwards from there.
