### ISSUE TITLE
Pulumi cli hangs on MacOS 14.6.1

### ISSUE THREAD

**Issue by cabbiepete** [pulumi/pulumi#17083]
### What happened?

Similar to https://github.com/pulumi/pulumi/issues/16871 and https://github.com/pulumi/pulumi-aws/issues/4190 

`pulumi about`

```
✗ pulumi about            
CLI          
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.43.0
resource  awsx        2.11.0
resource  cloudflare  5.30.0
resource  docker      4.5.4
resource  docker      3.6.1
language  nodejs      unknown

Host     
OS       darwin
Version  14.6.1
Arch     arm64
```

I think I'm running pulumi arm64 based on 

```
file "$(which pulumi)"
```

returning

```
/opt/homebrew/bin/pulumi: Mach-O 64-bit executable arm64
```

And also that I'm fairly sure we resolved the arm64 issue already a couple months back. any ideas much appreciated

### Example

```
✗ pulumi up        
Previewing update (team)

View in Browser (Ctrl+O): https://app.pulumi.com/myhr/fargate/team/previews/086bf2cc-dc35-447b-b25f-9d7a761030cb

     Type                 Name          Plan        Info
     pulumi:pulumi:Stack  fargate-team  running...  (CodeFragmentMetadata.cpp:48 instruction_extents_for_arm_address)
```

If I wait long enough the summary is

```
SummaryDiffDiagnostic
     Type                 Name          Plan     Info
     pulumi:pulumi:Stack  fargate-team           2 messages
 
Diagnostics:
  pulumi:pulumi:Stack (fargate-team):
    assertion failed [arm_interval().contains(address)]: code fragment does not contain the given arm address
    (CodeFragmentMetadata.cpp:48 instruction_extents_for_arm_address)
 ```

### Output of `pulumi about`

CLI          
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.43.0
resource  awsx        2.11.0
resource  cloudflare  5.30.0
resource  docker      4.5.4
resource  docker      3.6.1
language  nodejs      unknown

Host     
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in nodejs: executable='/Users/cabbiepete/.nvm/versions/node/v20.15.1/bin/node' version='v20.15.1'

Current Stack: myhr/fargate/team-pete

Found no resources associated with team-pete

Found no pending operations associated with team-pete

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/cabbiepete
User           cabbiepete
Organizations  cabbiepete, myhr
Token type     personal

Dependencies:
NAME                VERSION
@pulumi/cloudflare  5.30.0
@pulumi/pulumi      3.122.0
@types/node         20.12.12
typescript          5.4.5
@pulumi/aws         6.43.0
@pulumi/awsx        2.11.0

Pulumi locates its logs in /var/folders/dl/v8h47vxs01xcd0nltj3fk2rr0000gn/T/ by default

### Additional context

```
file "$(which pulumi)"
```

returning

```
/opt/homebrew/bin/pulumi: Mach-O 64-bit executable arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Can you try removing all the pulumi plugins, via `pulumi plugin rm --all`? I'm wondering if any of those were non-arm64 binaries.

You can run `pulumi install` in your project's directory to re-install them, or they'll be installed on-demand on the next `pulumi up`.

**Comment by cabbiepete** [comment]
> Can you try removing all the pulumi plugins, via `pulumi plugin rm --all`? I'm wondering if any of those were non-arm64 binaries.
> 
> You can run `pulumi install` in your project's directory to re-install them, or they'll be installed on-demand on the next `pulumi up`.

Good point I missed this step from the original ticket comment. After removing then reinstalling cli working again. Thanks.

I'll write this up for me and my team but is there a gotcha doc I could contribute to for everyone else?

**Comment by justinvp** [comment]
> is there a gotcha doc I could contribute to for everyone else?

Thanks! Might be worth adding it to https://github.com/pulumi/docs/blob/master/content/docs/support/troubleshooting.md#common-problems

**Comment by cabbiepete** [comment]
I've found I needed to do this per pulumi project which is what tripped me up. I've added a PR with a suggested update to the docs.

**Comment by 7onn** [comment]
My issue was the
```
brew install pulumi/tap/pulumi
```

This command downloaded the crooked binaries for amd64 on my arm macos.

I fixed this by downloading the plain binaries via [arm64 button](https://www.pulumi.com/docs/iac/download-install/)
![Image](https://github.com/user-attachments/assets/be75ecfc-5cbd-4359-9e30-decba13a4894)

**Comment by GabLeRoux** [comment]
I had a similar issue. Root cause was that my `$PATH` had the Intel (`x86_64`) Homebrew path before the ARM one, so it kept installing the `x86_64` version of `pulumi`, and pulumi kept installing `x86_64` versions of its plugins. 🤦 

Updating my `~/.zshrc` to put the ARM Homebrew paths first fixed it:

```bash
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
```

I installed pulumi again and confirmed it was running using arm (including plugins):

```bash
brew install pulumi/tap/pulumi
```

## ✅ Check Homebrew architecture

```bash
BREW_PREFIX="$(brew --prefix)"
file "$BREW_PREFIX/bin/openssl"
```

**Expected output (correct ARM install):**

```
Mach-O 64-bit executable arm64
```

---

## ✅ Check Pulumi CLI architecture

```bash
file "$(which pulumi)"
```

**Expected output:**

```
Mach-O 64-bit executable arm64
```

---

## ✅ Check Pulumi plugin architectures (works in bash + zsh)

```bash
find ~/.pulumi/plugins -type f -name "pulumi-*" ! -name "*.json" ! -name "*.lock" \
  -exec sh -c 'for f do echo "$f: $(file -b "$f")"; done' sh {} +
```

**Expected output example:**

```
/Users/.../pulumi-resource-aws: Mach-O 64-bit executable arm64
/Users/.../pulumi-resource-random: Mach-O 64-bit executable arm64
```

If you see `x86_64`, that plugin is wrong.
