### ISSUE TITLE
snapshot integrity error with Pulumi CLI

### ISSUE THREAD

**Issue by kujenga** [pulumi/pulumi#17111]
### What happened?

I got the below error while trying to run `pulumi refresh --stack=main` and it stated:

> We would appreciate a report: https://github.com/pulumi/pulumi/issues/
> Please provide all of the below text in your report.

### Example

```
Pulumi Version:    v3.130.0
Go Version:        go1.22.6
Go Compiler:       gc
Architecture:      arm64
Operating System:  darwin
Command:           pulumi refresh --stack=main
Error:             resource urn:pulumi:main::plus::gcp:certificatemanager/certificate:Certificate::example-load-balancer-certificate's dependency urn:pulumi:main::plus::gcp:certificatemanager/dnsAuthorization:DnsAuthorization::example-load-balancer-cert-auth-instance refers to missing resource

Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.22.6/x64/src/runtime/debug/stack.go:24 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x104ed6376?, 0x78?}, {0x14001dbed38?, 0x78?, 0x40?})
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:313 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x14002514a20)
        /home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:217 +0xd9c
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getSnapshot(0x0?, {0x1060d18c8, 0x1077d4d80}, {0x1060a9720, 0x1077d4d80}, {0x1060d1de0?, 0x14001dbee50?})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:229 +0x74
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Snapshot(0x14001fd2af0, {0x1060d18c8, 0x1077d4d80}, {0x1060a9720, 0x1077d4d80})
        /home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:151 +0xb0
main.newRefreshCmd.func1(0x14001e3ef08, {0x14001e7e930, 0x0, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/refresh.go:235 +0xcd0
main.newRefreshCmd.runCmdFunc.func2(0x0?, {0x14001e7e930?, 0x0?, 0x0?})
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:31 +0x28
main.newRefreshCmd.runCmdFunc.RunFunc.func5(0x14001e3ef08, {0x14001e7e930, 0x0, 0x1})
        /home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x38
github.com/spf13/cobra.(*Command).execute(0x14001e3ef08, {0x14001e7e910, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x14001e2c008)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        /home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x54
```

### Output of `pulumi about`

CLI          
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  aws            6.37.0
resource  gcp            7.38.0
resource  pulumiservice  0.17.0
language  python         unknown
resource  random         4.15.0
resource  tailscale      0.16.2

Host     
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in python: executable='<snipped>/.venv/bin/python' version='3.11.3'

Backend        
Name           pulumi.com
<snipped>

Dependencies:
NAME        VERSION
<snipped>

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: snapshot integrity failure; refusing to use it: resource urn:pulumi:main::plus::gcp:certificatemanager/certificate:Certificate::example-load-balancer-certificate's dependency urn:pulumi:main::plus::gcp:certificatemanager/dnsAuthorization:DnsAuthorization::example-load-balancer-cert-auth-instance refers to missing resource

### Additional context

The `DnsAuthorization` resource has `delete_before_replace=True` on it, this happened while trying to change them and they are re-created.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kujenga** [comment]
May be related to https://github.com/pulumi/pulumi/issues/17073 and perhaps https://github.com/pulumi/pulumi/issues/17070

I also found https://github.com/pulumi/pulumi/issues/15959 and this command got things working again (that resource already didn't exist):

```
pulumi state delete urn:pulumi:main::plus::gcp:certificatemanager/certificate:Certificate::example-load-balancer-certificate --disable-integrity-checking
```

**Comment by justinvp** [comment]
Thanks for opening the issue, @kujenga.

> The `DnsAuthorization` resource has `delete_before_replace=True` on it, this happened while trying to change them and they are re-created.

Did the snapshot integrity error first happen when running `pulumi refresh --stack=main` or did it occur in a prior operation?

**Comment by lunaris** [comment]
Note: this is technically a duplicate of #16916, since this was the first issue raised with this root cause (and consequently is the only issue bearing a regression label).
