### ISSUE TITLE
Plain resource methods can't return provider objects in nodejs

### ISSUE THREAD

**Issue by corymhall** [pulumi/pulumi#17110]
### What happened?

#13592 adding support for returning plain values from methods and one of the examples is returning a `Provider` that can be used in a subsequent resource.

https://github.com/pulumi/pulumi/blob/69f68e23393d3e0a1c2244ac532288385d9dbbfe/tests/integration/construct_component_configure_provider/nodejs/index.ts#L22-L27

In that example the [implementation is in go](https://github.com/pulumi/pulumi/blob/69f68e23393d3e0a1c2244ac532288385d9dbbfe/tests/integration/construct_component_configure_provider/testcomponent-go/configurer.go#L77-L88) and I am trying to get it to work in nodejs without success.

From what I can tell when you have a method that returns a `Provider` the `pulumi.runtime.call()` method always returns an empty object. If I update the method to return anything else (e.g. another resource or a string) then `pulumi.runtime.call()` returns the correct value.

### Example

I have an repro PR in [pulumi-eks](https://github.com/pulumi/pulumi-eks/pull/1329) which has steps to run to reproduce the issue.

[Generated method in the sdk](https://github.com/pulumi/pulumi-eks/blob/9cefe70ba8e8aa0e3f8d8ee11a4a7279771075cf/sdk/nodejs/cluster.ts#L176-L183)
[resource call method](https://github.com/pulumi/pulumi-eks/blob/9cefe70ba8e8aa0e3f8d8ee11a4a7279771075cf/nodejs/eks/cmd/provider/index.ts#L66-L71)
[nodejs implementation](https://github.com/pulumi/pulumi-eks/blob/9cefe70ba8e8aa0e3f8d8ee11a4a7279771075cf/nodejs/eks/cluster.ts#L2063-L2065)
[application](https://github.com/pulumi/pulumi-eks/blob/9cefe70ba8e8aa0e3f8d8ee11a4a7279771075cf/examples/plain-method-repro/index.ts)

### Output of `pulumi about`

```
CLI          
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.50.1
resource  aws         6.50.1
resource  eks         2.0.0-alpha.0+dev
resource  kubernetes  4.17.1
resource  kubernetes  4.17.1
language  nodejs      unknown

Host     
OS       darwin
Version  14.6.1
Arch     arm64

This project is written in nodejs: executable='/Users/chall/.nvm/versions/node/v20.11.1/bin/node' version='v20.11.1'

Current Stack: corymhall/example-nodegroup/dev2

Found no resources associated with dev2

Found no pending operations associated with dev2

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/corymhall
User           corymhall
Organizations  corymhall
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.130.0
@pulumi/aws     6.50.1
@pulumi/eks     2.7.9
typescript      4.9.5
@types/node     22.5.1

Pulumi locates its logs in /var/folders/3b/6mr1jkqx7r797ff75k27jfjc0000gn/T/ by default
```

### Additional context

We are attempting to [migrate the `pulumi-eks` nodejs implementation to the generated sdk](https://github.com/pulumi/pulumi-eks/issues/603). The non-generated nodejs sdk has a `Cluster` resource which creates a `k8s` provider and then exposes it as a public property which is then used by the user to create more downstream resources. In order to allow users to migrate to the new generated sdk we need a way of exposing this provider.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Looking at it a little bit.

**Comment by t0yv0** [comment]
I think we got this to work somehow. 

This worked:

```typescript
    getK8sProvider(): pulumi.Output<k8s.Provider> {
        return this.core.provider;
    }
```

Trying to add a new field k8sProvided didn't work.

```typescript
    getK8sProvider(): pulumi.Output<k8s.Provider> {
        return this.k8sProvider;
    }
```

I think we might have some issue with hydration / etc or not registering it properly but I couldn't figure it out. 

I think if Cory confirms that `return this.core.provider;` works we're unblocked for now.

**Comment by justinvp** [comment]
Wondering if this is possibly related to #13223 and the use of `yarn link`, but that _should_ be addressed now.

> From what I can tell when you have a method that returns a `Provider` the `pulumi.runtime.call()` method always returns an empty object.

What's the output of the `Call` rpc with `PULUMI_DEBUG_GRPC=logs.jsonl` set?

**Comment by corymhall** [comment]
This is the output of `call`

```json
{
  "method": "/pulumirpc.ResourceProvider/Call",
  "request": {
    "tok": "eks:index:Cluster/getK8sProvider",
    "args": {
      "__self__": {
        "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
        "urn": "urn:pulumi:dev2::example-nodegroup::eks:index:Cluster::example-nodegroup-iam-simple"
      }
    },
    "argDependencies": {
      "__self__": {
        "urns": [
          "urn:pulumi:dev2::example-nodegroup::eks:index:Cluster::example-nodegroup-iam-simple"
        ]
      }
    },
    "project": "example-nodegroup",
    "stack": "dev2",
    "dryRun": true,
    "parallel": 56,
    "monitorEndpoint": "127.0.0.1:62835",
    "acceptsOutputValues": true
  },
  "response": {
    "return": {}
  },
  "metadata": {
    "kind": "resource",
    "mode": "client",
    "name": "eks"
  }
}
```

**Comment by t0yv0** [comment]
I think we're in a better place now, it works, sort of, our latest iteration does the right thing on `pulumi up --skip-preview`. We just need to sort out  unknowns.

Currently getting:

```
Error: Plain resource method "eks:index:Cluster/getK8sProvider" incorrectly returned an unknown value. This is an error in the provider, please report this to the provider developer.
        at Object.<anonymous> (/Users/anton/code/pulumi-eks/sdk/nodejs/utilities.ts:89:19)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/anton/code/pulumi-eks/sdk/nodejs/utilities.ts:7:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This seems reasonable from platform POV as the plain-typed value cannot represent an UNKNOWN provider.

Can we instead return a dummy provider value?

**Comment by t0yv0** [comment]
I need to dig into this. Ideally the provider should be known but the specific kubeconfig output unknown.

**Comment by t0yv0** [comment]
Found the issue. This is rather tricky. We had to add a new field k8sProvider to ClusterInternal in the end, but we kept forgetting to add an entry for it in the call to `super()`. So then rehydrating the state in `Call` didn't "see" this new state although Construct correctly set it up. This was super confusing.


```

        if (opts?.urn) {
            const props = {
                clusterSecurityGroup: undefined,
                core: undefined,
                defaultNodeGroup: undefined,
                eksCluster: undefined,
                eksClusterIngressRule: undefined,
                instanceRoles: undefined,
                kubeconfig: undefined,
                kubeconfigJson: undefined,
                nodeSecurityGroup: undefined,
                k8sProvider: undefined, // MISSING
            };
            super(type, name, props, opts);
            return;
        }
```

The unknown problem we solved separately by avoiding unknown poisoning in construct, should be good to go now.

**Comment by justinvp** [comment]
We could consider doing something to help here. Though, you're typically not dealing with manually maintained `props{}` (it's generally codegened as part of SDKgen) unless you're authoring a dynamic provider resource or manually defining things like in our EKS implementation (which isn’t typical).

I could see a few different things we could consider:
1. Emit a warning when a property comes back from the provider that the SDK doesn’t know about.
2. Same as (1) but error. We’d probably want to have this be opt-in in some way, e.g. opt-in to strictness.
3. We could consider adding the output. It means we’d be creating an output on the fly, after receiving the value from the engine, so there could possibly be a race if you tried to use the output before it was initialized.

I opened https://github.com/pulumi/pulumi/issues/17333 to track the idea.

**Comment by t0yv0** [comment]
@justinvp looks like we just shipped 3.x.x alpha of pulumi-eks that hopefully will be the next major that actually removes the one-of-a-kind architecture for the in-process node SDK, and instead uses SDKGen with Node in a standard fashion. I suspect this issue was found in EKS because of the highly custom way it used to work. So not fixing this is probably a good call if SDKGen guarantees it never happens.
