### ISSUE TITLE
`pulumi.automation._server.LanguageServer.Run` is not able to catch a (derived error of) `BaseException`

### ISSUE THREAD

**Issue by wangshangsam** [pulumi/pulumi#17133]
### What happened?

When I write some tests using [pytest](https://docs.pytest.org/en/stable/), in the event where `pytest.raises(...)` expects an exception but the code wrapped by `pytest.raises(...)` does not raise any exception, pytest would then generate a [Failed](https://github.com/pytest-dev/pytest/blob/4604387ae444a4f3478243f6d12f40b0cc48e121/src/_pytest/outcomes.py#L178) error which is ultimately a (indirect) child class of `BaseException`.

However, the language server [only catches all Exceptions (note: NOT BaseException which is a parent class of Exception) raised in the `self.program`](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/automation/_server.py#L97). In the aforementioned event, the automation runtime then thinks `self.program` is fine even though it's not, which then leads to a deadlock.

### Example

`test_a.py`:
```python
import pytest

from pulumi.automation import create_or_select_stack

class TestA:

  def test_a(self):
    
    def program():
      with pytest.raises(ValueError):
        # Any Pulumi code that works fine.
        a = 1 + 2
    
    stack = create_or_select_stack(..., program=program)
    stack.preview()
```

Command:
```bash
pytest test_a.py  # This command will hang forever.
```

### Output of `pulumi about`

CLI
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Host
OS       ubuntu
Version  22.04
Arch     x86_64

### Additional context

Related question that I asked in `pytest`'s repo: https://github.com/pytest-dev/pytest/discussions/12762

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for the issue @wangshangsam. Indeed it sounds like we likely should be catching `BaseException` rather than `Exception` there.
