### ISSUE TITLE
Expose provider resources in Python

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#1713]
Just what it says on the tin.

**Comment by lukehoban** [comment]
Per #220 which was closed as a dupe of this - we need to make sure that `tfgen` is also updated to emit these instances for each provider.

**Comment by swgillespie** [comment]
Blocked on https://github.com/pulumi/pulumi-terraform/issues/271, which needs to be fixed first. First-class providers are basically useless without a fix to https://github.com/pulumi/pulumi-terraform/issues/271.
