### ISSUE TITLE
Clean up cancellation logic throughout the engine

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#1714]
We take a variety of cancellation approaches in the engine, including:
- `Close` methods
- `Cancel` methods
- `util/cancel` contexts
- `context.Contexl`

We should look through these carefully. I _think_ it's reasonable to expect that we can unify on `util/cancel` for any component that needs to observe two-level cancellation and `context.Context` for everything else, but I'm not certain.

In addition to the varied approaches, it is not clear where the responsibility lies for shutting down various components. We should clarify this as well.

**Comment by lukehoban** [comment]
Removing from a milestone until we decide to tackle this along with some related changes.

**Comment by leezen** [comment]
Closing out old issues
