### ISSUE TITLE
hyphens in python import instructions given by pulumi package add

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi#17149]
### What happened?

from [slack](https://pulumi-community.slack.com/archives/CB81H6DG9/p1725395018150959?thread_ts=1723549488.550369&cid=CB81H6DG9):

>Just discovered the new Any Terraform Provider and immediately tried it for the netapp_ontap provider. Works without any problems. Really great and a game changer for us! :+1::tada:
>Only a small error in the generated comment regarding the hyphen char:
>You can then import the SDK in your Python code with:
>  `import pulumi_netapp-ontap as netapp-ontap`
>So that must be:
`import pulumi_netapp_ontap as netapp_ontap`

We're probably just using the plugin name rather than the python package name for the instructions

### Example

See above

### Output of `pulumi about`

User didn't say, but given the dates, I think they must have been on 3.130.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
@lunaris, want to take a look?
