### ISSUE TITLE
Improve performance of pulumi preview

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1715]
Running `pulumi { preview, update, destroy }` makes a lot of API calls to the Pulumi Service, such as every time a log line is rendered, and for every change that is made to the checkpoint file.

The latency added by each API call update process can add many seconds to the overall update. Most of the time this is masked by the much longer delay in actually modifying cloud resources. But for previews which are persisted in the service, it can increase the duration by a large factor.

This issue tracks improving the performance of `pulumi preview` with regard to the overhead of communicating with the service.

**Comment by joeduffy** [comment]
I just tried a before/after with the [cloud-js-thumbnailer](https://github.com/pulumi/examples/tree/master/cloud-js-thumbnailer):

```
$ time pulumi preview
<the usual output.../>
real	0m14.987s
user	0m2.329s
sys	0m0.972s

$ PULUMI_PERSIST_PREVIEWS=1 time pulumi preview
<the usual output.../>
Permalink: https://app.pulumi.com/pulumi/joe-thumbnailer/previews/e6bb5f0a-4f21-4074-ad96-6f6ff8043a77
real	0m10.62
user	0m2.34
sys	0m0.73
```

The version that persists previews was actually faster! (Given the amount of IO, I realize this is within expected noise ratios, but it clearly didn't go from "10 seconds to 5 minutes.")

Do we have a good example where `PULUMI_PERSIST_PREVIEWS` causes prohibitively poor performance degradation?

Also note that the thumbnailer example includes Docker build output, which I thought was the differentiating factor in good versus poor performance?

As I mentioned today, I dislike holding back features like this behind envvars. It makes the tool harder to use and configure, we'll preemptively spend a lot of time worrying and working around it, and we won't get data about which scenarios it actually causes problems for (if there are indeed any).

**Comment by joeduffy** [comment]
I'm closing out in favor of https://github.com/pulumi/pulumi/issues/1826. As we encounter problems, let's reopen the bug with repros and, ideally, specific proposed actions to take.
