### ISSUE TITLE
Pending deletes show up as replaces

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#1717]
e.g.

```
hela:eip pgavlin$ pulumi destroy
Previewing destroy of stack 'eip-parallel'
Previewing changes:

     Type                      Name              Plan        Info
 -   pulumi:pulumi:Stack       eip-eip-parallel  delete
 +-  ├─ aws:dynamodb:Table     useast1           replace
 -   ├─ aws:ec2:SecurityGroup  default           delete
 -   ├─ aws:dynamodb:Table     uswest2           delete
 -   ├─ pulumi:providers:aws   default           delete
 -   └─ pulumi:providers:aws   useast1           delete

info: 5 changes previewed:
    - 5 resources to delete
```

This is exacerbated by the issue fixed in https://github.com/pulumi/pulumi/pull/1716. Note that fixing that issue may mask this one, as we'll issue a proper delete step for the live resource.

**Comment by swgillespie** [comment]
Linking issues: https://github.com/pulumi/pulumi/issues/1645

**Comment by CyrusNajmabadi** [comment]
Are these being emitted as OpDelete's?  or as OpDeleteReplaced?

**Comment by CyrusNajmabadi** [comment]
Ok, based on what Sean wrote:

> Pending deletes are considered a "delete-replacement" by the engine, which means that from a UI perspective they are rendered as the culmination of a resource replacement. This causes problems in that it is difficult to ascertain via a preview whether or not pending delete deletions are occurring, since they are masked as replacements.

I can see why we'd get teh above display.  Since i know nothing about pending deletes, i'm going to have to discuss this with you guys asap so we can figure out a good story here.

**Comment by joeduffy** [comment]
@CyrusNajmabadi, @swgillespie  is this still a problem, or did the various pending delete work last sprint land us in a good place here?

**Comment by CyrusNajmabadi** [comment]
Have validated that current behavior is now appropriate.
