### ISSUE TITLE
environments interfere with automatic plugin downloads

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#17217]
For root cause information: see https://github.com/pulumi/pulumi/issues/17217#issuecomment-2343134211.

### What happened?

We received a [customer report (internal)](https://pulumi.slack.com/archives/C064J2A20Q3/p1725933828379799) that they needed to run `pulumi plugin install resource terraform-provider` before running `pulumi up`. This shouldn't be necessary, since the engine should know to automatically install [pulumi-terraform-provider](https://github.com/pulumi/pulumi-terraform-provider) as needed. 

Instead of downloading, the customer saw:

```
  pulumi:pulumi:Stack <stack-name> running warning: error downloading provider: plugin asset 'pulumi-resource-terraform-provider-v0.1.0-linux-amd64.tar.gz' not found
```

This is confirmed at minimum in TypeScript, but my guess is that the same problem is present in all languages.

### Example

To reproduce:

1. `mkdir tmp && cd tmp` 
2. Create a new project:
    ```console
    $ pulumi new typescript        
    This command will walk you through creating a new Pulumi project.
    
    Enter a value or leave blank to accept the (default), and press <ENTER>.
    Press ^C at any time to quit.
    
    Project name (tmp):  
    Project description (A minimal TypeScript Pulumi program):  
    Created project 'tmp'
    
    Please enter your desired stack name.
    To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
    Stack name (dev):  
    Created stack 'dev'
    
    The package manager to use for installing dependencies npm
    Installing dependencies...
    
    
    added 294 packages, and audited 295 packages in 9s
    
    43 packages are looking for funding
      run `npm fund` for details
    
    found 0 vulnerabilities
    Finished installing dependencies
    
    Your new project is ready to go! ✨
    
    To perform an initial deployment, run `pulumi up`
    ```
3. `pulumi package add terraform-provider hashicorp/random`
4. `npm add random@file:sdks/random`
5. Write to `index.ts`:
   ```ts
   import * as random from "random";

   new random.Pet("example");
   ```
6. `pulumi install && pulumi up`, creating 2 resources: the stack and the pet.
7. `pulumi plugin rm --all --yes`
8. Remove the `@pulumi/pulumi` from `package.json:dependencies`. `package.json` should look like:
   ```json
       {
        "name": "tmp",
        "main": "index.ts",
        "devDependencies": {
            "@types/node": "^18",
            "typescript": "^5.0.0"
        },
        "dependencies": {
            "random": "file:sdks/random"
        }
    }
    ```
9. Run `pulumi up`:
   ```console
   $ pulumi up
   Previewing update (dev)
   
   View in Browser (Ctrl+O): https://app.pulumi.com/pulumi/ts/dev/previews/7a34591d-26b0-4b40-b24c-44b4ca5ac458
   
   Loading policy packs...
   
        Type                        Name           Plan     Info
        pulumi:pulumi:Stack         ts-dev                  
        └─ pulumi:providers:random  default_3_6_2           1 error
   
   Diagnostics:
     pulumi:providers:random (default_3_6_2):
       error: Could not automatically download and install resource plugin 'pulumi-resource-terraform-provider' at version v0.2.0, install the plugin using `pulumi plugin install    resource terraform-provider v0.2.0`: error downloading provider terraform-provider to file: failed to download plugin: terraform-provider-0.2.0: 403 HTTP error    fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-terraform-provider-v0.2.0-darwin-arm64.tar.gz
   ```

### Output of `pulumi about`

```
CLI          
Version      3.130.0-dev.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME                VERSION
language  nodejs              unknown
resource  terraform-provider  0.2.0
resource  terraform-provider  0.2.0

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v22.1.0'

Current Stack: pulumi/ts/dev

TYPE                     URN
pulumi:pulumi:Stack      urn:pulumi:dev::ts::pulumi:pulumi:Stack::ts-dev
pulumi:providers:random  urn:pulumi:dev::ts::pulumi:providers:random::default_3_6_2
random:index/pet:Pet     urn:pulumi:dev::ts::random:index/pet:Pet::example


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ian-pulumi-corp
User           ian-pulumi-corp
Organizations  ian-pulumi-corp, pulumi
Token type     personal

Dependencies:
NAME         VERSION
random       3.6.2
@types/node  16.18.101

Pulumi locates its logs in /var/folders/fg/_1q36r4j6yx0rwz2fbhjd5y40000gn/T/ by default
```

### Additional context

Just like other providers, parameterized providers should install as they are used. The contents of `package.json` should be fully advisory.

The customer uses `yarn` instead of NPM.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
> [@iwahbe](https://github.com/iwahbe) maybe I missed a step but I'm struggling to repro this. But I did have a thought looking at the error.
> 
> ```
> fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-terraform-provider-v0.2.0-darwin-arm64.tar.gz
> ```
> 
> It doesn't look like the terraform-provider plugin is being mirrored to get.pulumi.com? v0.2.0 looks like a valid version (https://github.com/pulumi/pulumi-terraform-provider/releases/tag/v0.2.0).
> 
> I wonder if the user hit github ratelimits and so we did the auto-fallback to get.pulumi.com but the plugin isn't being pushed there?

If the issue was GH rate limits, then `pulumi plugin install resource terraform-provider` shouldn't work to fix the problem, since that has the same download source.

**Comment by iwahbe** [comment]
Me and @Frassle believe we have root caused this issue. It seems like the issue is caused by a invalid GITHUB_TOKEN injected during `pulumi {up,preview}` by an environment preventing the download.

```yaml
environment:
  - providers.all
```

The token is not injected during `pulumi install`, which is why `pulumi install` worked.

We have 3 potential fixes:

1. ESC should only inject it's env vars into sub-processes of Pulumi, the language host and providers, not into the main process itself. This would fix the issue because the engine could transparently install the publicly available provider, but the program would still witness the injected env vars. (This is my preferred solution, but it is a design decision more then a bug fix)
2. The engine could retry 401 (no permissions) and 403 (timeout) failed downloads when there is a GITHUB_TOKEN set, without the GITHUB_TOKEN set. This could help because some Github tokens have are not able to download public resources, even when no token can.
3. ESC could apply equally to `pulumi install`, making the experience consistent (and allowing esc to be used to access private providers and registries). Ideally, `pulumi` would warn when a download fails and GITHUB_TOKEN was set by ESC to make debugging easier.

**Comment by Frassle** [comment]
Spoke to @pgavlin about the above suggestions and his comment was that option 2 and 3 seem the most reasonable to do.

**Comment by tgummerer** [comment]
> ESC could apply equally to `pulumi install`, making the experience consistent (and allowing esc to be used to access private providers and registries). Ideally, `pulumi` would warn when a download fails and GITHUB_TOKEN was set by ESC to make debugging easier.

I had a look at this, but then realized that environments are tied to stacks, not to project, while `pulumi install` only operates at the project level as far as I can tell, so I don't think this is going to be an option.  

For option 2), fraser already implemented it for 401's, and https://github.com/pulumi/pulumi/pull/17671 is implementing it for 403's.
