### ISSUE TITLE
Issues with Alias definition after `pulumi move`

### ISSUE THREAD

**Issue by colearendt** [pulumi/pulumi#17230]
### What happened?

After `pulumi move`, state has to be modified manually in some cases.

The imported items were of the form `custom:ParentClass$custom:ChildClass`. Afterwards, I needed `custom:NewParentClass$custom:ChildClass`. This created delete/create stuff, and I could not get Aliasing to work properly. I'm not sure if this is that issue in another way, if I was specifying the type alias improperly (type seemed to be `custom:ChildClass`), or if there is something else that is needed for a "parent class." (Alias on parent didn't seem to help either).

### Example

I have a component class with a parent component class `AWSWorklodClusters`. It has a method that creates a child component of another class.

```
class AWSWorkloadClusters(pulumi.ComponentResource):

      def __init__(self, workload: ptd.aws_workload.AWSWorkload, *args, **kwargs):
        super().__init__(
            f"ptd:{self.__class__.__name__}",
            workload.compound_name,
            *args,
            **kwargs,
        )
        _define_things()
    def _define_things():
      ptd.pulumi_resources.team_site.TeamSite(...)

class TeamSite(pulumi.ComponentResource):
     def __init__(
        self,
        workload: ptd.aws_workload.AWSWorkload,
        release: str,
        site_name: str,
        *args,
        **kwargs,
    ):
        super().__init__(
            f"ptd:{self.__class__.__name__}",
            f"{workload.compound_name}-{release}-{site_name}",
            *args,
            **kwargs,
        )
```

When you create this, you get:

- parent: AWSWorkloadClusters == "demo01"
    - child: TeamSite == "demo01-20240909-main"

All well and good! But let's say we want to move _just_ the `TeamSite` to another `pulumi` project

- Create a project that defines the `TeamSite` in code. As a child of a new component `class AWSWorkloadSites(pulumi.Componentclass)` with much the same setup
- Use `pulumi move` to move the `TeamSite` across to the new project (i.e. #17187)
- Now you're good to go! You run `pulumi up` to get a `delete` and `create`, because:
- `ptd:AWSWorkloadClusters$ptd:TeamSite` is different from `ptd:AWSWorkloadSites$ptd:TeamSite`

I tried several `alias` methods to resolve this to no avail:
- `type`
- `parent`
- `name`

Ultimately, "type" is recognized as properly `ptd:TeamSite`, and "parent" could be aliased, but it did not seem that anything addressed the `custom:parentClass$` in the class definition / state.

I resolved the issue by manually changing the URI in all cases / modifying the state directly. But it seemed to me that there is either a bug or another `alias` property is necessary!

Could also be related to #14302

### Output of `pulumi about`

```
CLI
Version      3.130.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  aws         6.34.0
resource  aws-native  0.95.0
resource  command     0.10.0
resource  kubernetes  4.11.0
resource  mailgun     3.5.3
resource  postgresql  3.11.0
language  python      unknown
resource  random      4.16.1

Host
OS       darwin
Version  14.5
Arch     arm64

This project is written in python: executable='/Users/colearendt/.pyenv/shims/python3' version='3.12.1'

Dependencies:
NAME            VERSION
aiohttp         3.9.3
black           24.2.0
editables       0.5
hatch           1.11.0
pip             24.0
internal-package       0.2.0
internal-package-2             0.52.1.dev511+gd4b1d1c3.d20240816
pydevd-pycharm  241.17011.127
pytest          8.2.0
internal-package-3  0.7.4
ruff            0.4.5

Pulumi locates its logs in /var/folders/80/0b6wv3417xl0x60cd800mtwr0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening this separate issue with these additional details, @colearendt!

**Comment by Frassle** [comment]
When you set parent on the alias what did you set it to?

**Comment by tgummerer** [comment]
@colearendt I just tried to reproduce this, and the following works for me:

proj1:

```
import pulumi

class AWSWorkloadClusters(pulumi.ComponentResource):
    def __init__(self, name, *args, **kwargs):
        super().__init__(
            f"ptd:{self.__class__.__name__}",
            name,
            *args,
            **kwargs,
        )
        self._define_things()

    def _define_things(self):
      TeamSite("bla", "v1", "site1", self)

class TeamSite(pulumi.ComponentResource):
     def __init__(
        self,
        name,
        release: str,
        site_name: str,
        p: pulumi.ComponentResource,
    ):
        super().__init__(
            f"ptd:{self.__class__.__name__}",
            f"{name}-{release}-{site_name}",
            None,
            opts=pulumi.ResourceOptions(
                parent=p,
            ),
        )

cluster = AWSWorkloadClusters("my-cluster")
```

After pulumi up-ing this, and moving the resource to `proj2` using `pulumi state move`, I have the following in `proj2`:

```
import pulumi

class AWSWorkloadSites(pulumi.ComponentResource):
    def __init__(self, name, *args, **kwargs):
        super().__init__(
            f"ptd:{self.__class__.__name__}",
            name,
        )
        self._define_things()

    def _define_things(self):
      TeamSite("bla", "v1", "site1", self)


class TeamSite(pulumi.ComponentResource):
     def __init__(
        self,
        name,
        release: str,
        site_name: str,
        p: pulumi.ComponentResource,
    ):
         super().__init__(
            f"ptd:{self.__class__.__name__}",
            f"{name}-{release}-{site_name}",
            None,
            opts=pulumi.ResourceOptions(
                parent=p,
                aliases=[pulumi.Alias(parent="urn:pulumi:dev::proj2::ptd:AWSWorkloadClusters::my-cluster")]
            ),
        )

cluster = AWSWorkloadSites("my-cluster")
```

A `pulumi preview` then only creates the `AWSWorkloadSites` component as expected:

```
$ pulumi preview
Previewing update (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/v-thomas-pulumi-corp/proj2/dev/previews/ca14e3dd-c229-41d4-b92f-64b6d87cb40f

     Type                     Name        Plan       Info
     pulumi:pulumi:Stack      proj2-dev              1 message
 +   └─ ptd:AWSWorkloadSites  my-cluster  create     
```

Am I misunderstanding something here/what are you expecting to see?

**Comment by tgummerer** [comment]
@colearendt since we haven't heard back from you, and I think this works as designed, I'm going to go ahead and close this out.  But please feel free to reopen if we misunderstood something here.
