### ISSUE TITLE
Python codegen is wrong when importing AWS Lambda that has environment variables

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#17294]
### What happened?

Imported a lambda function that has two environment variables defined for it: `MY_LENGTH` and `MY_WIDTH`.
The python generated code looks like this:
```
imported_function = aws.lambda_.Function("imported_function",
    architectures=["x86_64"],
    environment={
        "variables": {
            "m_y__length": "7",
            "m_y__width": "8",
        },
    },
...
```

It's worth noting that if importing it into a typescript stack, the generated code has the correct values for the variable names (i.e. `MY_LENGTH` and `MY_WIDTH`).

### Example

- Launch stack using attached code to create the lambda for importing or otherwise find a lambda that has environment variables defined for it to import.
- initialize a python stack (`pulumi new aws python`)
- import the lambda: `pulumi import aws:lambda/function:Function  imported_function LAMBDA_ID`
- See generated code has bad environment variable declarations.

### Output of `pulumi about`

                                                       
CLI          
Version      3.132.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.52.0
resource  awsx    2.15.0
resource  docker  4.5.5
resource  docker  3.6.1
language  nodejs  unknown

Host     
OS       darwin
Version  13.6.9
Arch     x86_64

This project is written in nodejs: executable='/Users/mitch/.nvm/versions/node/v20.10.0/bin/node' version='v20.10.0'

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.133.0
@types/node     18.19.50
typescript      5.6.2
@pulumi/aws     6.52.0
@pulumi/awsx    2.15.0

### Additional context

As noted above, importing in typescript produces code with the correct environment variable names.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already). 
[sourceproject.zip](https://github.com/user-attachments/files/17048556/sourceproject.zip)

**Comment by Frassle** [comment]
Testing this against codegen it doesn't seem to be something python codegen is doing by default, so going to check if import is doing something odd.

**Comment by Frassle** [comment]
Tracked this down to an issue with the inputTypes option in the language settings of the schema. Should be able to add to the conformance tests and fix because it only happens when inputTypes is set to "classes-and-dicts"

**Comment by Frassle** [comment]
Got a test repro'ing this now at https://github.com/pulumi/pulumi/pull/17302 (dependent on https://github.com/pulumi/pulumi/pull/17315). I _think_ the `generator.typedDictEnabled` is too eager to say types are "typed dicts" just based on them being object types. Plain maps are also object types.

Looks like it might just be a case of seeing if AdditionalProperties is set or not.

**Comment by Frassle** [comment]
Nope, it's the insideTypedDict tracking that looks to be off. That isn't being reset inside maps it seems.
