### ISSUE TITLE
False-positives in our "looks like a config secret" logic

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1732]
Our integration tests in the Service repo found a couple of false positives in our logic to warn if a configuration value looks like a secret.

```
error: config value ''timer app created by "travis" at 2018-08-08 17:33:09.321234916 +0000 UTC m=+30.634475880'' looks like a secret; rerun with --secret to encrypt it, or --plaintext if you meant to store in plaintext
```

A lower priority false positive would be our AWS Access Key. My understanding is the AWS Secret Access Key is the sensitive part of the keypair, the Access Key ID is OK to expose.

Also, looking at the error, we are printing the errant log message with two `'` symbols.

**Comment by ellismg** [comment]
> Also, looking at the error, we are printing the errant log message with two ' symbols.

One comes from the CLI, the other comes from the string itself (the test in this case wrapped its entire message in single quotes, for reasons that are not clear to me)

**Comment by joeduffy** [comment]
We knew this is going to be prone to false positives. What do we want to do?

* Change the error to a warning
* Pass `--plaintext` for each occurrence, which will suppress the error
* Don't do this sort of smart scanning (which will always be prone to false positives, no matter how good it is)

I would like this bug to be actionable if we're going to keep it open, since it's basically by design.

**Comment by lukehoban** [comment]
I suggest that for now, we pass `--plaintext` for each occurence where we or users hit this.  If experience over the next couple weeks suggests we've set this too aggressively, we either change the error to a warning or dial down the detector settings and see if that helps.

**Comment by joeduffy** [comment]
Great point. We copied go vet's thresholds, but we can easily dial them back

**Comment by ellismg** [comment]
This is the new worst false positive:

> error: config value 'Hello, Pulumi Timers!' looks like a secret; rerun with --secret to encrypt it, or --plaintext if you meant to store in plaintext

I am going to pull this into M0.16 and investigate.  I don't think we are doing the right thing if it fires on this string.
