### ISSUE TITLE
No way to debug language servers

### ISSUE THREAD

**Issue by brandonpollack23** [pulumi/pulumi#17335]
Currently we have PULUMI_DEBUG_PROVIDER but no PULUMI_DEBUG_LANGUAGE option.  I just hacked it in locally to fix an issue but we ought to provide that (should't be too difficult, just have to populate the memoized plugin cache with an extant language provider with the given port)

**Comment by tgummerer** [comment]
While we don't have that support, you can probably hack something up using bits of the old debugging instructions (https://github.com/pulumi/docs/blob/83eeb37a259f463fc7aa3df18d25179ae8ec1f4a/content/docs/iac/concepts/debugging/_index.md#debugging-go-programs).

I haven't tried this, but you should be able to create a `pulumi-language-<insert-your-language-here>` that comes first on your path with something like

```
#!/bin/bash
exec dlv --listen=:2345 --headless=true --api-version=2 exec path/to/actual/pulumi-language-<insert-your-language-here>`
```

and then hack the Makefile up to add `-gcflags "all=-N -l"` to the build (not sure if there would be a downside to just generally doing it).

**Comment by justinvp** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/17821

**Comment by justinvp** [comment]
For other language hosts:

- dotnet issue: https://github.com/pulumi/pulumi-dotnet/issues/398
- java issue: https://github.com/pulumi/pulumi-java/issues/1480
- yaml issue: https://github.com/pulumi/pulumi-yaml/issues/694
