### ISSUE TITLE
[python] pulumi v3.134 breaks custom invokes in pulumi-kubernetes

### ISSUE THREAD

**Issue by Zaid-Ajaj** [pulumi/pulumi#17347]
### Description 

_edited to describe the underlying issue_

Recently we merged https://github.com/pulumi/pulumi/pull/17275 and published as of pulumi python sdk v3.134. This changed the behaviour of `invoke_async` to always return `InvokeResult` instead of unwrapping `value` from the `InvokeResult`

This broke the custom pulumi-kubernetes invokes written in python because they expected the response from the invoke to be unwrapped

from [pulumi-kubernetes/yaml/yaml.py](https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/python/pulumi_kubernetes/yaml/yaml.py#L2183-L2185)

```python
async def _invoke_yaml_decode_async(text, invoke_opts):
    inv = await pulumi.runtime.invoke_async('kubernetes:yaml:decode', {'text': text}, invoke_opts)
    return (inv or {}).get('result', [])
```

### Suggested solutions

- ~~Revert https://github.com/pulumi/pulumi/pull/17275 and re-publish~~
- Automatically unwrap `InvokeResult.value` from `invoke_async` when detecting legacy behavior
- ~~Make it such that `InvokeResult` can behave like a dictionary with functions like `get(key, default)` and `items()`, proxying the behaviour to the `.value` field~~
- ~~Fix the issue in pulumi-kubernetes (unwrap the `value` from `InvokeResult` before using it)~~

**Comment by mikhailshilkov** [comment]
The 3.134.0 release has been yanked on PyPI to prevent more users from hitting this issue.
