### ISSUE TITLE
sdk/go/auto: lots of pulumi-resource processes

### ISSUE THREAD

**Issue by jordiprats** [pulumi/pulumi#17361]
### What happened?

I'm using pulumi as a library in a long lived daemon, I can see that it spawns a lot of "pulumi-resource processes, for example, this process has been running for just an hour:

```
$ ps | grep -c pulumi-resource
174
```

### Example

```
~ $ ps
PID   USER     TIME  COMMAND
    1 10015000  0:25 /manager
  920 10015000  0:04 [pulumi-resource]
  921 10015000  0:04 [pulumi-resource]
  925 10015000  0:04 [pulumi-resource]
  926 10015000  0:04 [pulumi-resource]
  929 10015000  0:04 [pulumi-resource]
  930 10015000  0:04 [pulumi-resource]
  962 10015000  0:04 [pulumi-resource]
(...)
```

### Output of `pulumi about`

not relevant here, using as cli:

v3.130.0

With the following imports:

```
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/servicecatalog"
	"github.com/pulumi/pulumi/sdk/v3/go/auto/optdestroy"
	"github.com/pulumi/pulumi/sdk/v3/go/auto/optup"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
I'm not aware of any processes that would be named `pulumi-resource`... Our provider plugin binaries are typically named `pulumi-resource-foo` (e.g. `pulumi-resource-aws`), so if anything, I'd expect them to follow that naming pattern.

Do you have a minimal Go Automation API program that would demonstrate these `pulumi-resource` processes being created?

**Comment by justinvp** [comment]
Looks like we can get a repro from https://github.com/pulumi/pulumi-kubernetes-operator/issues/698
