### ISSUE TITLE
Pulumi import fails if component parent has the same name as the resource

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#17375]
### What happened?

When attempting to import a resource under a component parent with the same name, I get an error ` error: Preview failed: unknown parent '...componentURN' for resource 'resourceURN'`

I would expect the Pulumi engine to be able to understand which resource is the parent and import successfully.

This obviously can be circumvented by renaming the parent or the child's name to something non-conflicting, but that might not always be an easy change for teams

### Example

1. Create component resource and underlying child resource with the same name
1. Delete the resource from state
1. Create a pulumi import file via `pulumi preview --import-file file.json`
1. Fill in the placeholder
1. See unknown parent error

<details>
<summary>Code Repro</summary>

```ts
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

class StorageBucketComponent extends pulumi.ComponentResource {
  public readonly storageBucket: gcp.storage.Bucket;

  constructor(
    name: string,
    args: BucketComponentArgs,
    opts?: pulumi.ComponentResourceOptions
  ) {
    super("test:gcp/zbuchheit:bucket", name, {}, opts);

    this.storageBucket = new gcp.storage.Bucket(
      `${name}`,
      {
        location: args.location,
      },
      { parent: this }
    );

    this.registerOutputs({
      serviceAccount: this.storageBucket,
    });
  }
}

interface BucketComponentArgs {
  location: string;
}

new StorageBucketComponent("zbuchheit-bucket", {
  location: "us",
});

export const bucketName = bucket.storageBucket.name;
export const bucketURN = bucket.storageBucket.urn;

```
</details>

## Helper Command
For convenience, if you run pulumi up with my code repro, you can then use the commands `pulumi up -f && pulumi state delete -y "$(pulumi stack output bucketURN) && pulumi preview --import-file file.json` if you want to get to the scenario where you are ready to attempt the import file.

### Output of `pulumi about`

<details>
<summary>Pulumi About</summary>

```
CLI          
Version      3.134.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  gcp     8.2.0
language  nodejs  3.134.0-dev.0

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in nodejs: executable='/Users/zbuchheit/.nvm/versions/node/v18.17.1/bin/node' version='v18.17.1'

Current Stack: zbuchheit-pulumi-corp/cluster-gcp-ts/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/zbuchheit-pulumi-corp
User           zbuchheit-pulumi-corp
Organizations  zbuchheit-pulumi-corp
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/gcp     8.2.0
@pulumi/pulumi  3.133.0
@types/node     18.19.50
typescript      5.6.2
```
</details>

### Workaround

I was able to workaround the issue by actually editing the parent name to a fake name. For example, if my parent name is `zbuchheit-bucket` I can append a unique suffix such as `-zebra`, complete the import using the import file, then manually edit the state using a global replace to remove the suffix and get the end result I desire.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
What you need to do is set `"logicalName"` for the child resource and set its `"name"` to something different like `inner-zbuchheit-bucket`:

```json
{
    "nameTable": {
        "zbuchheit-bucket": "urn:pulumi:dev::gcpimported::test:gcp/zbuchheit:bucket::zbuchheit-bucket"
    },
    "resources": [
        {
            "type": "gcp:storage/bucket:Bucket",
            "logicalName": "zbuchheit-bucket",
            "name": "inner-zbuchheit-bucket",
            "id": "<the id>",
            "parent": "zbuchheit-bucket",
            "version": "8.3.1"
        }
    ]
}
```

**Comment by zbuchheit** [comment]
Ah, I'll give that a try and close it out once I confirm. Thanks!

**Comment by zbuchheit** [comment]
that did the trick. Thanks! I am not sure that is intuitive to do, so maybe we could improve the docs or the error message to guide the user, but I will open a separate issue for that.
