### ISSUE TITLE
Undefined: pulumi.StringMapMapMapOutput

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi#17415]
The latest version of [pulumi-oci](https://github.com/pulumi/pulumi-oci/issues/599) contains an unsupported nested map type: `go/oci/objectstorage/privateEndpoint.go:24:28: undefined: pulumi.StringMapMapMapOutput`
which makes it currently impossible to build this provider's Go SDK.

**Comment by Frassle** [comment]
Related issue we had about this before: https://github.com/pulumi/pulumi/issues/15478

**Comment by justinvp** [comment]
Fixed by #17417
