### ISSUE TITLE
Inclusion of tests in @pulumi/pulumi npm package can cause unexpected dotnet errors

### ISSUE THREAD

**Issue by smithrobs** [pulumi/pulumi#17471]
### What happened?

`/node_modules/@pulumi/pulumi/tests/automation/data/testproj_dotnet` contains a top-level statement in `Program.cs`.

Having a node app (that installs the package, e.g. a Pulumi program) as a subdirectory to a dotnet app causes the dotnet app to fail its build.

```
dotnet_app
 └ node_app
    └ node_modules
```

Unaware users may find the default error message `dotnet` provides confusing and ambiguous to resolve:

`error CS8802: Only one compilation unit can have top-level statements.`

### Example

Any default config'd dotnet 6+/C# 10+ app using a top-level statement will fail compilation once a node app with `@pulumi/pulumi` installed is placed in a subdirectory of the dotnet app.

### Output of `pulumi about`

N/A

### Additional context

Suggestion: Remove/npmignore tests from the npm package and/or whitelist pkg files via `package.json`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
We should probably add an `.npmignore` file with `test` and `test_with_mocks` in it. We should be careful to also add all relevant entries from `.gitignore` (including parent `.gitignore`?), because that's what NPM currently looks at, but it will stop when `.npmingore` file is defined.

**Comment by julienp** [comment]
> We should be careful to also add all relevant entries from `.gitignore` 

I don't think that's necessary. The way we build the package is to first run `tsc`, which will compile all the files from the `tsconfig.json` `files` property (so this is an explicit include list already). We then add a couple extra files to make it a package via the [Makefile](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/Makefile#L33). This means we all the files in `./bin` were explicitly put there by us, and we don't have to worry about other "random" files.
