### ISSUE TITLE
pulumi helper functions such as `gcp.appengine.get_default_service_account` require a dependency parameter in InvokeOptions

### ISSUE THREAD

**Issue by aaron-tillekeratne** [pulumi/pulumi#17549]
### What happened?

Running the following code will fail due to asynchronous execution. The appengine service account will not exist until the api is enabled and the app is enabled. 

```
app = gcp.appengine.Application(
            resource_name="jahanverse-application",
            project=project_id,
            iap=gcp.appengine.ApplicationIapArgs(
                enabled=True,
                oauth2_client_id=iap_client.client_id,
                oauth2_client_secret=iap_client.secret,
            ),
            location_id=region,
            opts=ResourceOptions(parent=self, depends_on=[app_engine_admin_api]),
        )
default_sa = gcp.appengine.get_default_service_account(project=project_id,opts=pulumi.InvokeOptions())

```

So it would be good if the InvokeOptions had a `dependsOn` parameter too. 

### Example

```
app = gcp.appengine.Application(
            resource_name="jahanverse-application",
            project=project_id,
            iap=gcp.appengine.ApplicationIapArgs(
                enabled=True,
                oauth2_client_id=iap_client.client_id,
                oauth2_client_secret=iap_client.secret,
            ),
            location_id=region,
            opts=ResourceOptions(parent=self, depends_on=[app_engine_admin_api]),
        )
default_sa = gcp.appengine.get_default_service_account(project=project_id,opts=pulumi.InvokeOptions())
```

### Output of `pulumi about`

Backend        
Name           710e3601de50
URL            gs://xxx
User           vscode
Organizations  
Token type     personal

Dependencies:
NAME           VERSION
black          24.4.2
debugpy        1.8.7
GitPython      3.1.41
grpcio-status  1.60.1
ipython        8.26.0
isort          5.13.2
pg8000         1.31.2
pip            24.0
pytest-order   1.2.1
setuptools     69.0.3
weaver         0.7.0
wheel          0.43.0

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by julienp** [comment]
Thanks you for the suggestion! We definitely want to add this and have an existing issue for this here https://github.com/pulumi/pulumi/issues/14243
