### ISSUE TITLE
Snapshot integrity error

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#17616]
### What happened?

Updating (staging)
  
   err?: Error: Command failed with exit code 255: pulumi up --yes --skip-preview --target urn:pulumi:staging::DPPS::XXX:dpps:migration-lambda$aws:lambda/function:Function::postgres-migration-lambda --exec-agent pulumi/actions@v5 --color auto --suppress-progress --exec-kind auto.local --stack XXX/dpps/staging --non-interactive
  error: The Pulumi CLI encountered a snapshot integrity error. This is a bug!

Pulumi Version:    v3.136.1
  Go Version:        go1.23.2
  Go Compiler:       gc
  Architecture:      amd64
  Operating System:  linux
  Command:           pulumi up --yes --skip-preview --target urn:pulumi:staging::DPPS::XXX:dpps:migration-lambda$aws:lambda/function:Function::postgres-migration-lambda --exec-agent pulumi/actions@v5 --color auto --suppress-progress --exec-kind auto.local --stack XXX/dpps/staging --non-interactive
  Error:             could not deserialize deployment: snapshot integrity failure; refusing to use it: resource urn:pulumi:staging::DPPS::aws:s3/bucketPublicAccessBlock:BucketPublicAccessBlock::bucket-public-access-block's dependency urn:pulumi:staging::DPPS::aws:s3/bucket:Bucket::staging-dpps-search-result-export comes after it
  
  Stack Trace:
  
  goroutine 1 [running]:
  runtime/debug.Stack()
  	/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/debug/stack.go:26 +0x5e
  github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x2c38094?, 0x51?}, {0xc002a9d740?, 0x51?, 0x40?})
  	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:611 +0x34
  github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0xc000b47b80)
  	/home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:497 +0x1053
  github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getSnapshot(0x1dcf310?, {0x3345c68, 0x49c1220}, {0x33216e0, 0x49c1220}, {0x33461c0?, 0xc0015b2f40?})
  	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:229 +0xa5
  github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).getTarget(0xc001f4cb90, {0x3345c68, 0x49c1220}, {0x33216e0, 0x49c1220}, {0x33461c0, 0xc0015b2f40}, 0xc001a465d0, {0x7f5a8d8fb4f8, 0x49c1220})
  	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:249 +0x106
  github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).newUpdate(_, {_, _}, {_, _}, {0xc000205a20, {0xc0019a2b40, 0x2f}, {0x0, 0x0, ...}, ...}, ...)
  	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/state.go:196 +0x225
  github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(_, {_, _}, {_, _}, {_, _}, {0xc000205a20, {0xc0019a2b40, 0x2f}, ...}, ...)
  	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1381 +0x113
  github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(_, {_, _}, {_, _}, {_, _}, {0xc000205a20, {0xc0019a2b40, 0x2f}, ...}, ...)
  	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1355 +0x528
  github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute({_, _}, {_, _}, {_, _}, {0xc000205a20, {0xc0019a2b40, 0x2f}, {0x0, ...}, ...}, ...)
  	/home/runner/work/pulumi/pulumi/pkg/backend/apply.go:272 +0x216
  github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Update(_, {_, _}, {_, _}, {0xc000205a20, {0xc0019a2b40, 0x2f}, {0x0, 0x0, ...}, ...})
  	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/backend.go:1108 +0x9d
  github.com/pulumi/pulumi/pkg/v3/backend.UpdateStack({_, _}, {_, _}, {0xc000205a20, {0xc0019a2b40, 0x2f}, {0x0, 0x0, 0x0}, ...})
  	/home/runner/work/pulumi/pulumi/pkg/backend/stack.go:97 +0x9b
  github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Update(_, {_, _}, {0xc000205a20, {0xc0019a2b40, 0x2f}, {0x0, 0x0, 0x0}, 0xc000be3830, ...})
  	/home/runner/work/pulumi/pulumi/pkg/backend/httpstate/stack.go:179 +0x68
  main.newUpCmd.func1({_, _}, {_}, {_, _}, {_, _}, {{{0x49c1220, 0x0, 0x0}, ...}, ...}, ...)
  	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:198 +0xeb6
  main.newUpCmd.func3(0xc0008f0308, {0xc001d3c540, 0x0, 0x0?})
  	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/up.go:574 +0xd09
  main.newUpCmd.runCmdFunc.func4(0x0?, {0xc001d3c540?, 0x0?, 0x0?})
  	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:45 +0x1c
  main.newUpCmd.runCmdFunc.RunFunc.func7(0xc0008f0308, {0xc001d3c540, 0x0, 0xe})
  	/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x3b
  github.com/spf13/cobra.(*Command).execute(0xc0008f0308, {0xc001d3c460, 0xe, 0xe})
  	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
  github.com/spf13/cobra.(*Command).ExecuteC(0xc0019d2308)
  	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
  github.com/spf13/cobra.(*Command).Execute(...)
  	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
  main.main()
  	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x4e
  
  
  Updating (staging)
  
  
      at Object.createCommandError (/home/runner/work/_actions/pulumi/actions/v5/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/errors.js:77:1)
      at /home/runner/work/_actions/pulumi/actions/v5/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:201:1
      at Generator.throw (<anonymous>)
      at rejected (/home/runner/work/_actions/pulumi/actions/v5/webpack:/pulumi-github-action/node_modules/@pulumi/pulumi/automation/cmd.js:19:1)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

### Example

See above.

### Output of `pulumi about`

See above.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
The customer was able to get unblocked by doing a refresh followed by an up. But it would still be good to understand how they got into this state using v3.136.1.

**Comment by lunaris** [comment]
Hi all. I am still looking into what may have caused this issue. The fact that it's a targeted operation means that it might be possible that #17633 fixed it, but I am still investigating using the state files we have retrieved from the customer.

**Comment by lunaris** [comment]
After discussion with the customer, a lack of a reproduction for this, and other work on various snapshot issues, closing this.
