### ISSUE TITLE
Failing function invokes do not abort inline nodejs program in Automation API

### ISSUE THREAD

**Issue by lionello** [pulumi/pulumi#17613]
### Describe what happened

There's something funny about creating an `aws.ecs.TaskDefinition` within an inline Pulumi program: when an exception occurs somewhere within the `containerDefinitions` input, the exception is shown but the program doesn't abort and keeps running forever.

Regular occurrences of `getParameterOutput` (anywhere else) will abort, even just within a `pulumi.Stringify`. It seems to be related to `containerDefinitions` specifically, perhaps because of the normalization that happens internally?

This bug also does not occur in regular Pulumi TS program, but only when run in an inline program through the automation SDK. Therefor, it might be because of the TS automation, but again, it only appears to happen with the `containerDefinitions` field of `aws.ecs.TaskDefinition`.

I've attached the smallest repro I was able to create. Run it with `AWS_PROFILE=your-aws-profile ts-node auto.ts`.

### Sample program

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import { InlineProgramArgs, LocalWorkspace } from "@pulumi/pulumi/automation";

const programArgs: InlineProgramArgs = {
  stackName: "dev",
  projectName: "t",
  program: async () => {
    // getParameterOutput will fail with "couldn't find resource" 
    const value = aws.ssm.getParameterOutput({ name: "bogus", withDecryption: true }).value;
    const containerDefinitions = pulumi.jsonStringify([{ name: "container1", image: "nginx", environment: [{ name: "VAR", value }] }]);
    const taskDef = new aws.ecs.TaskDefinition("task1", {
        containerDefinitions,
        family: "task1",
    });
    return { td: taskDef.arn }; // makes no difference
  },
};

async function main() {
  const stack = await LocalWorkspace.createOrSelectStack(programArgs);
  await stack.setConfig("aws:region", { value: "us-west-2" });
  try {
    await stack.cancel(); // fix previous abort
  } catch (e) {
  }
  await stack.up({ onOutput: console.log, logToStdErr: true, logVerbosity: 10 }); // stderr is swallowed?
}

main().catch((e) => {
  console.error(e.message || e.name);
  process.exitCode = 1;
});
```

### Log output

The "up" options `logToStdErr` and `logVerbosity` don't appear to have any effect in the TS automation API:
```
$ ts-node auto.ts
Updating (dev)


View Live: https://app.pulumi.com/lionello/t/dev/updates/41


    pulumi:pulumi:Stack t-dev  warning: using pulumi-resource-aws from $PATH at /nix/store/8i0is2fkzbbgzcgzqgvhvg6vvgyg30b1-pulumi-3.136.1/bin/pulumi-resource-aws



    pulumi:pulumi:Stack t-dev running warning: using pulumi-resource-aws from $PATH at /nix/store/8i0is2fkzbbgzcgzqgvhvg6vvgyg30b1-pulumi-3.136.1/bin/pulumi-resource-aws

    pulumi:pulumi:Stack t-dev running warning: using pulumi-resource-aws from $PATH at /nix/store/8i0is2fkzbbgzcgzqgvhvg6vvgyg30b1-pulumi-3.136.1/bin/pulumi-resource-aws

@ Updating....

    pulumi:pulumi:Stack t-dev running error: Unhandled exception: Error: invocation of aws:ssm/getParameter:getParameter returned an error: invoking aws:ssm/getParameter:getParameter: 1 error occurred:

@ Updating....
.
.
.
.
.
.
.
.
.
.
.
^C
```

### Affected Resource(s)

`aws.ecs.TaskDefinition`

### Output of `pulumi about`

CLI          
Version      3.136.1
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host     
OS       darwin
Version  15.0.1
Arch     arm64

This project is written in nodejs: executable='/nix/store/hxl1k8qgmrm1vfq5f419iv4wybz9szqq-nodejs-20.17.0/bin/node' version='v20.17.0'

Current Stack: lionello/t/dev

TYPE                  URN
pulumi:pulumi:Stack   urn:pulumi:dev::t::pulumi:pulumi:Stack::t-dev
pulumi:providers:aws  urn:pulumi:dev::t::pulumi:providers:aws::default_6_55_0
aws:iam/role:Role     urn:pulumi:dev::t::aws:iam/role:Role::task1

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/lionello
User           lionello
Organizations  lionello, defang-io
Token type     personal

Dependencies:
NAME                                       VERSION
@types/js-yaml                             4.0.9
js-yaml                                    4.1.0
@aws-sdk/s3-request-presigner              3.631.0
grpc-tools                                 1.12.4
@pulumi/pulumi                             3.136.1
@types/google-protobuf                     3.15.12
@types/mocha                               10.0.7
@types/tar-stream                          3.1.3
@aws-sdk/client-cloudfront                 3.623.0
@aws-sdk/client-elastic-load-balancing-v2  3.623.0
@pulumi/digitalocean                       4.32.0
@pulumi/github                             6.2.3
@pulumi/tls                                5.0.4
oci-registry-client                        0.2.0
@aws-sdk/client-cloudwatch-logs            3.623.0
@aws-sdk/client-s3                         3.623.0
@grpc/grpc-js                              1.10.9
dots-wrapper                               3.11.9
ts-protoc-gen                              0.15.0
@defang-io/pulumi-defang                   0.16.2
@pulumi/archive                            0.2.1
@types/node                                20.14.15
google-protobuf                            3.21.4
ts-node                                    10.9.2
@pulumi/awsx                               2.14.0
prettier                                   2.8.8
@aws-sdk/client-ecs                        3.623.0
@pulumi/aws                                6.55.0
axios                                      1.7.4
mocha                                      10.7.3
tar-stream                                 3.1.7
typescript                                 5.4.5

Pulumi locates its logs in /var/folders/wp/g4m6l2dx3f71wsy8j6l2wwdc0000gn/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tgummerer** [comment]
@lionello did you manage to fix this issue?  I'm curious what you did to fix it?

**Comment by lionello** [comment]
Oops, it got fixed because it was mentioned in a workaround PR in our private repo.
