### ISSUE TITLE
Document relationship between diff and detailed diff in the proto files

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi#17612]
In addition to (or even prior to) https://github.com/pulumi/pulumi/issues/17610, we should add documentation to the gRPC protocol that describes some of the expectations for the response, eg.

- All keys in `Diff` should appear in `DetailedDiff`.
- All keys in `DetailedDiff` should appear in `Diff`.
- `Diff` should not contain duplicates.
- `DetailedDiff` should not contain duplicate keys.

### Duplicate entries in `Diff`

This manifests as the user being shown additional deletions in the detailed diff, more than the actual number of properties that were removed and that are therefore in detailed diff.

Related issue:
- https://github.com/pulumi/pulumi-snowflake/issues/640

### Unaligned keys in `Diff` vs `DetailedDiff`. 

One has property `A` and the other only has property `B`.

Related issue:
- https://github.com/pulumi/pulumi-azure-native/pull/3633

**Comment by thomas11** [comment]
Waiting for pulumi/pulumi#17685 to be merged first.

**Comment by firemanxbr** [comment]
I believe it is possible to complete Milestone 0.112 because issue #17685 was closed and was the last dependency for that milestone. I'm interested in having the Python UV toolchain introduced in that milestone #17031 and #17609
