### ISSUE TITLE
Pulumi state move command fails with snapshot integrity error when moving resources with Cloudflare dependencies between stacks

### ISSUE THREAD

**Issue by tomweston** [pulumi/pulumi#17651]
### What happened?

Attempting to move resources between Pulumi stacks (e.g., `source-service/source-prod-region` to `dest-service/dest-prod-region`) fails due to a snapshot integrity error, specifically when Cloudflare resources are involved. This occurs even when using the `--disable-integrity-checking` flag. Pulumi reports missing dependencies on Cloudflare resources and encounters a bug during the move operation.

**Command executed:**
```bash
pulumi state move --source source-service/source-prod-region --dest dest-service/dest-prod-region 'urn:pulumi:source-prod-region::source-service::deployment:staticHosting::resource-name' --disable-integrity-checking
```

**Error message:**
```
error: The Pulumi CLI encountered a snapshot integrity error. This is a bug!
Error: failed to verify integrity of source snapshot: resource urn:pulumi:source-prod-region::source-service::pulumi:providers:cloudflare::cloudflare's dependency urn:pulumi:dest-prod-region::dest-service::pulumi:pulumi:StackReference::stage refers to missing resource
```

### Stack Trace

```
goroutine 1 [running]:
runtime/debug.Stack()
/opt/hostedtoolcache/go/1.23.1/x64/src/runtime/debug/stack.go:26 +0x64
github.com/pulumi/pulumi/pkg/v3/resource/deploy.SnapshotIntegrityErrorf({0x106855290?, 0x72?}, {0x1400251ec78?, 0x72?, 0x40?})
/home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:331 +0x30
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Snapshot).VerifyIntegrity(0x14000f60120)
/home/runner/work/pulumi/pulumi/pkg/resource/deploy/snapshot.go:217 +0xd9c
main.(*stateMoveCmd).Run(0x14001ff87d0, {0x1076c1e08, 0x108db6760}, {0x1076dd038, 0x1400064aee0}, {0x1076dd038, 0x14001b66a10}, {0x14002071320, 0x1, 0x6}, ...)
/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_move.go:429 +0x23f4
main.newStateMoveCommand.func1(0x0?, {0x14002071320, 0x1, 0x6})
/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/state_move.go:101 +0x2a0
main.newStateMoveCommand.runCmdFunc.func2(0x0?, {0x14002071320?, 0x0?, 0x0?})
/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/errors.go:45 +0x28
main.newStateMoveCommand.runCmdFunc.RunFunc.func5(0x14002062f08, {0x14002071320, 0x1, 0x6})
/home/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:99 +0x38
github.com/spf13/cobra.(*Command).execute(0x14002062f08, {0x140020712c0, 0x6, 0x6})
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0x81c
github.com/spf13/cobra.(*Command).ExecuteC(0x14001da2908)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:55 +0x50
```

### Example

The problem occurs when attempting to move the following resources:
- `urn:pulumi:source-prod-region::source-service::deployment:staticHosting::resource-name`
- `urn:pulumi:source-prod-region::source-service::deployment:staticHosting$cloudProvider:index/record:Record::resource-name`
- Additional resources with dependencies on Cloudflare components...

The resources being moved have dependencies in the source stack, specifically on Cloudflare and AWS resources. This dependency results in an integrity failure, blocking the move operation.

### Output of `pulumi about`

Pulumi Version: v3.133.0  
Go Version: go1.23.1  
Architecture: arm64  
Operating System: darwin  

### Additional context

This issue appears to be associated with component resources that encapsulate AWS and Cloudflare resources within classes or modules, increasing dependency complexity. Moving these components from one stack to another can result in broken dependencies and integrity verification failures, particularly with resources from the Cloudflare provider.

### Contributing

Vote on this issue by adding a 👍 reaction.  
To contribute a fix for this issue, leave a comment (and link to your pull request if you've opened one already).

**Comment by tgummerer** [comment]
I'll take a look at this. Note that `state move` will never allow you to write a corrupt snapshot, hence the `--disable-integrity-checking` functionality not working.  That functionality is also a very bad idea in this case, and should only ever be used if a snapshot is already corrupt, and regular pulumi operations can not succeed.  It's not meant to allow you to corrupt a snapshot (which would then be much harder to clean up.

Since (unless I'm missing something) this isn't a case where we corrupt a users snapshot, but rather just a case where moving resources doesn't work I'm gonna remove the p0 label here.  Still gonna try to take a look at this today.

I have a hunch that the problem here has nothing to do with cloudflare, but rather with the stack reference that isn't treated correctly by `pulumi state move`.

**Comment by tgummerer** [comment]
This was reported to be working fine with a newer version of pulumi, and was likely fixed by https://github.com/pulumi/pulumi/pull/17320.
