### ISSUE TITLE
When calling `workspace.CopyTemplateFiles(..., force, ...)` it throws an error

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi#17653]
### What happened?

A user reported when attempting to call `workspace.CopyTemplateFiles(..., force, ...)` when `force = true` it throws an error. `kdir /tmp/foo-typescript/src: file exists`

I believe the reason we don't see this today is because our templates don't usually have sub-folders

### Example

TODO;

### Output of `pulumi about`

TODO

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
I'm sorry, I closed the issue accidentally. Reopened now.
