### ISSUE TITLE
Getting prompted for config passphrase twice

### ISSUE THREAD

**Issue by serpro69** [pulumi/pulumi#17668]
### What happened?

I have the same problem  as described in #10372, which seems to have started happening randomly in one of my stacks that uses GCS backend.

I have two different stacks, and in one of them I'm now getting double prompts for `up`, `preview` and `destroy`, whereas in the other stack I'm getting only one.

Also the faulty stack only prompts once when I do e.g. export.

```bash
-> pulumi stack export --show-secrets --file stack.json
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your passphrase to unlock config/secrets

-> pulumi up
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your passphrase to unlock config/secrets
Previewing update (test-state):
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):

```

Also note how in both cases it's repeating the output ` Enter your passphrase to unlock config/secrets` multiple times (not sure if this is expected behavior)

I tried to remove local `~/.pulumi` dir entirely (thinking that it my clean some of my local cache or smth like that), which didn't do anything to help with this issue

### Example

n/a

### Output of `pulumi about`

```
pulumi about
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your passphrase to unlock config/secrets
CLI
Version      3.129.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  gcp     8.6.0
language  go      unknown
resource  random  4.16.7
resource  time    0.1.0

Host
OS       debian
Version  bookworm/sid
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.23.1 linux/amd64'

Current Stack: organization/state/test-state

TYPE                                                       URN
...

Found no pending operations associated with ...
Backend
Name           serenity
URL            gs://...
User           sergio
Organizations
Token type     personal

Dependencies:
NAME                                          VERSION
github.com/joho/godotenv                      v1.5.1
github.com/pulumi/pulumi-gcp/sdk/v8           v8.6.0
github.com/pulumi/pulumi-random/sdk/v4        v4.16.7
github.com/pulumi/pulumi/sdk/v3               v3.137.0
github.com/serpro69/pulumi-google-components

Pulumi locates its logs in /tmp by default

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by serpro69** [comment]
UPD in case this helps someone else. Tried a few things locally and seems like resetting the passphrase via `pulumi stack change-secrets-provider passphrase` can be used as a workaround. My problematic stack does not prompt twice anymore ...for now at least.

**Comment by justinvp** [comment]
Glad you got things working! I haven't been able to reproduce this so I'm going to close the issue. If anyone else hits this, please open a new issue. Thank you.
