### ISSUE TITLE
Enable running Node/TypeScript providers from source (implement RunPlugin in Node host)

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#17663]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I want to:
- Implement a provider in Node.js with TypeScript
- Add a `PulumiPlugin.yaml` with `runtime: nodejs` to it
- Point the CLI to the folder with the provider's source code
- Run a program that instantiates resources from that provider

Current result: 

```
could not read plugin [...] stdout: rpc error: code = Unknown desc = not supported
```

This is because `RunPlugin` isn't implemented: 

https://github.com/pulumi/pulumi/blob/85e39e09f66489bc4614b471f0cc76d4cec9f01d/sdk/nodejs/cmd/pulumi-language-nodejs/main.go#L1345-L1349

Expected result:

Node.js host is able to run my Node.js app, starting up the provider process for me. Of course, Node is expected to be installed my the executing machine.

### Affected area/feature

Shimless providers

**Comment by justinvp** [comment]
Ah, I didn't realize we hadn't implemented that for Node.js yet.
