### ISSUE TITLE
Name of imported Go package is wrong

### ISSUE THREAD

**Issue by vincentvdk** [pulumi/pulumi#17745]
File: [themes/default/content/registry/packages/vault/api-docs/rabbitMq/secretbackendrole/_index.md](https://www.pulumi.com/registry/packages/vault/api-docs/rabbitmq/secretbackendrole/)

In the Vault RabbitMQ example the name of the imported package is wrong.
```
"github.com/pulumi/pulumi-vault/sdk/v6/go/vault/rabbitMq"
```

Should be
```
"github.com/pulumi/pulumi-vault/sdk/v6/go/vault/rabbitmq"
```

**Comment by justinvp** [comment]
This is a dupe of https://github.com/pulumi/pulumi/issues/14845
