### ISSUE TITLE
[Epic] DependsOn for Provider Functions

### ISSUE THREAD

**Issue by julienp** [pulumi/pulumi#17747]
## Overview

Add a new DependsOn option for provider functions, which allows specifying additional dependencies that are not captured as part of the function’s inputs.

Original issue: #14243

### References 📔

- [ ] Project View 
- [x] PR/FAQ https://github.com/pulumi/pulumi/discussions/17710
- [x] Design Doc https://docs.google.com/document/d/1YXlu5Ulw_EKMqiQeoBhZYIsxRsRqzv9kU8iFkC721z0/edit?pli=1&tab=t.0#heading=h.31jkxcq1swg5
- [ ] UX Designs 
- [ ] Decision Log

**Comment by justinvp** [comment]
The work for this epic is now complete. YAML support should ship in this week's CLI release.
