### ISSUE TITLE
nodejs langhost can exit without reporting any errors to Pulumi logs

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#1775]
Consider the following output. It looks like everything is just fine, but the update has failed for some reason. Looking at the full `-v=7` logs we can see the problem has to do with the Pulumi program failing for some reason, but no context is being provided to the Pulumi logging infrastructure.

The end result here is a pretty confused user.

```
Updating stack 'analyzer-svc'
Performing changes:

     Type    Name    Status        Info
 *   global  global  unchanged     1 info message

Diagnostics:
  global: global
    info: starting...
    Building container image 'pulum-dc8d99de-container': context=./docker-ffmpeg-thumb
    done

info: no changes required:
      11 resources unchanged

Permalink: https://app.pulumi.com/chrsmith/analyzer-svc/updates/12
error: update failed
```

```
I0814 20:58:18.869694   87084 langruntime_plugin.go:159] langhost[nodejs].RunPlan(pwd=/Users/chris/go/src/github.com/chrsmith/artifactory-demo/analyzer-service,program=.,...,dryrun=false) success: progerr=Program exited with non-zero exit code: 1
I0814 20:58:18.871831   87084 source_eval.go:160] EvalSourceIterator ended with an error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by chrsmith** [comment]
I'm not sure if it helps, but I think I found out what the problem was in my Pulumi app.

The `package.json` had a dependency on the `0.14.0` version of `pulumi-aws` and friends, whereas another dependency required `0.15.0` of pulumi libraries.

e.g.

```
    "dependencies": {
        "@pulumi/aws": "^0.14.0",
        "@pulumi/cloud-aws": "^0.14.0",
        "aws-sdk": "^2.238.1",
        "video-labeler": "latest"  <-- This package's package.json dependeds on @pulumi 0.15.0
    }
```

**Comment by swgillespie** [comment]
I'm tracking the side-by-side issue here: https://github.com/pulumi/pulumi/issues/1785. This issue is for the failure of the engine to report that the langhost exited.
