### ISSUE TITLE
Locked S3 URI is invalid if PULUMI_BACKEND_URL is set

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi#17762]
### What happened?

When the state is locked, pulumi generates a lock file in S3.
Then if the next update comes the error message appears. 
The error message contains S3 URI for a file, but it contains a region argument `?region=eu-central-1` which is an invalid S3 URI and cannot be used with AWS CLI.

### Example

Take the example from the docs `pulumi login 's3://<bucket-name>?region=eu-central-1`

`export PULUMI_BACKEND_URL=s3://mybucket?region=eu-central-1`
Make an operation in the stack, to lock it. (`pulumi up`
Proceed to another update.
`pulumi up`
error: the stack is currently locked by 1 lock(s). Either wait for the other process(es) to end or delete the lock file with `pulumi cancel`.
  `s3://mybucket?region=eu-central-1/.pulumi/locks/organization/project/stack/6f9f3334-e1dc-4bdb-b40b-a72d409598b3.json`: created by <hostname> (pid 97583) at 2024-11-13T05:25:02+01:00`

Then the command
`aws s3 rm 's3://mybucket?region=eu-central-1/.pulumi/locks/organization/project/stack/6f9f3334-e1dc-4bdb-b40b-a72d409598b3.json`
results in error
```
Invalid bucket name "mybucket?region=eu-central-1": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
```

Then the same process again but with valid S3 URI

`export PULUMI_BACKEND_URL=s3://mybucket`
`pulumi up`
error: the stack is currently locked by 1 lock(s). Either wait for the other process(es) to end or delete the lock file with `pulumi cancel`.
  `s3://mybucket/.pulumi/locks/organization/project/stack/6f9f3334-e1dc-4bdb-b40b-a72d409598b3.json`: created by <hostname> (pid 97583) at 2024-11-13T05:25:02+01:00`
Then aws command succeeds
`aws s3 rm 's3://mybucket?region=eu-central-1/.pulumi/locks/organization/project/stack/6f9f3334-e1dc-4bdb-b40b-a72d409598b3.json`

### Output of `pulumi about`

CLI          
Version      3.136.1
Go Version   go1.23.2
Go Compiler  gc

Host     
OS       darwin
Version  15.1
Arch     arm64

Backend        
Name           <hostname>
URL            s3://mybucket?region=eu-central-1

### Additional context

* https://www.pulumi.com/docs/iac/concepts/state-and-backends/

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Yeh the URI's used by pulumi match those supported by gocloud.dev, not the aws CLI. I'm not sure there is a direct mapping over. But you shouldn't need to use aws to rm the file, just run `pulumi cancel` to do it.

**Comment by 1oglop1** [comment]
> Yeh the URI's used by pulumi match those supported by gocloud.dev, not the aws CLI.
This is not issue of AWS CLI, it is the problem of displayed URI, because everything behind `?` is considered a query string, which is wrong the query string with the region should be at the end behind `.json?...` not behind the bucket name.
Somehow the representation is correct internally but incorrect when displayed. So the complaint of AWS CLI is valid. 
PS. I tested extra query string and had no problem `aws s3 rm 's3://mybucket/testfile?region=eu-central-1'`

ref: https://regex101.com/r/n4xlEq/1


> I'm not sure there is a direct mapping over. But you shouldn't need to use aws to rm the file, just run `pulumi cancel` to do it.
Sure that works but I always have to specify the stack which is rather long name in our case, so copy pasting s3 uri to aws cli works faster for me.

**Comment by justinvp** [comment]
I opened #17961 which at least fixes the way the URL is constructed so that it's actually valid. (Though, it's possible the URL may not work with the AWS CLI if it's using query params that it doesn't like).

A more drastic (but perhaps better) change would be to not display the lock file URL at all (though, we could still log it to logs) to encourage folks to use `pulumi cancel` rather than getting into implementation details of manually deleting files.
