### ISSUE TITLE
Show timestamps during non-interactive runs

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1778]
A suggestion from a customer using Pulumi in CI:

In cases where Pulumi does "non-interactive" output, for example and update during CI, it would be nice if there was a way to prefix each line with a timestamp.

**Comment by lukehoban** [comment]
I think it's okay to rely on use of 3rd party tools to wrap timestamp prefixes if really needed.   That is also much more flexible.  Unix philosophy and all :-).  Also haven't really heard this again in last 1.5 years.

**Comment by igal1c0de4n** [comment]
@lukehoban can you provide an example or point to a page which shows how to achieve that?
