### ISSUE TITLE
Reject schemas where resources and functions share the same name

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#17796]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Right now, Pulumi schemas have separate maps for resources and functions, with no prevention of overlap. In practice, only YAML supports functions and resources with the same name. All other languages fail at codegen time when resources and functions have the same name. To clarify the situation, we should make the following change to our schema validation:

1. We should reject schemas where 2 or more resources/functions have the same name.
2. We should case-fold names when searching for duplicates.

This restriction on valid schemas will make authoring tools that work with schemas easier, since we can know that `lowercase(pkg:module:name)` is globally unique within the schemas.

While this is technically a breaking change, no Pulumi language supports this level of naming granularity besides Pulumi YAML, and AFAIK there are no providers written for *only* Pulumi YAML.

### Affected area/feature

Schema binding.

Implementation should be as simple as:

```go
names := len(map[string]schemaPath{}, len(schema.Resources)+len(schema.Functions))
duplicates := map[string]struct{}{}
for r := range schema.Resources {
    v := append(names[r], "resources/"+r)
    names[r]=v
    if len(v) > 1 {
      duplicates[r]=struct{}
    }
}
for f := range schema.Functions {
    v := append(names[f], "functions/"+r)
    names[f]=v
    if len(v) > 1 {
      duplicates[f]=struct{}
    }
}
if len(duplicates) > 0 {
  return displayDuplicates(duplicates)
}
```

**Comment by iwahbe** [comment]
If @pulumi/platform accepts this restriction, I'd be happy to implement it in our schema binding.

**Comment by Frassle** [comment]
Should probably include the `Types` map in that uniqueness search as well.

**Comment by iwahbe** [comment]
> Should probably include the `Types` map in that uniqueness search as well.

We actually can duplicate at the `.Types` level, and we do. One example is `pulumi-cloudflare`:

```console
$ pulumi schema check provider/cmd/pulumi-resource-cloudflare/schema.json
Error: #/resources/cloudflare:index%2FlistItem:ListItem: multiple tokens map to cloudflare:index/listitem:listitem

other paths(s) are #/types/cloudflare:index%2FListItem:ListItem

Error: #/types/cloudflare:index%2FListItem:ListItem: multiple tokens map to cloudflare:index/listitem:listitem

other paths(s) are #/resources/cloudflare:index%2FlistItem:ListItem

error: schema validation failed
```

**Comment by Frassle** [comment]
> We actually can duplicate at the .Types level, and we do. One example is pulumi-cloudflare:

Ah because we always nest them in another namespace.
