### ISSUE TITLE
Arrays vs. HashSets in resource properties

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#178]
Today, we have many resource properties which are modeled as arrays.  For example:

```go
type Environment struct {
	idl.NamedResource
	OptionSettings *[]OptionSetting `lumi:"optionSettings,optional"`
}

type OptionSetting struct {
	Namespace  string `lumi:"namespace"`
	OptionName string `lumi:"optionName"`
	Value      string `lumi:"value"`
}
```

When resolving updates on `OptionSettings`, we currently do this with array semantics, so that for example if you swap two elements in an array, this is reported as an Update operation, with two array indexes having updates.

```typescript
// before
let myenv = new Environment("myenv", {
    optionSettings: [
        {
            namespace: "aws:autoscaling:asg",
            optionName: "MinSize",
            value: "2"
        },
        {
            namespace: "aws:autoscaling:launchconfiguration",
            optionName: "InstanceType",
            value: "t2.nano"
        },
    ]
})

// after
let myenv = new Environment("myenv", {
    optionSettings: [
        {
            namespace: "aws:autoscaling:launchconfiguration",
            optionName: "InstanceType",
            value: "t2.nano"
        },
        {
            namespace: "aws:autoscaling:asg",
            optionName: "MinSize",
            value: "2"
        },
    ]
})
```

Logically though, these `optionSettings` are actually a HashSet, and logically, there was no update between the before and after above.  In the case of `OptionSettings`, the hash key is the pair of `namespace` and `optionName`.

If Lumi continues to treat these as arrays, it will trigger some superfluous updates, and providers have two options: (1) try to interpret the array updates directly or (2) internally map the updates into a HashSet and generate their own logical diff based on that set difference.  

Option 1 may lead to issues when the same logical sub-resources is deleted/added vs. being directly updated, including operational interruption and potentially conflicts on the duplicated subresource identity.

Option 2 is probably the better option.  A one-off example of this is at https://github.com/pulumi/lumi/blob/master/lib/aws/provider/elasticbeanstalk/environment.go#L155-L196, but we likely will want to make a shared (and more robust) implementation of this.

However, that still means Lumi would see superfluous updates which don't end up causing resource changes (but may unintentionally trigger additional updates and/or replacements).  To address this, it might be possible to extend the resource provider API to allow resource providers to report whether a given resource property is logically a hashset, and if so to compute the hash key for an element of an array.

**Comment by pgavlin** [comment]
This is related to provider diffing (see e.g. #1108)

**Comment by lukehoban** [comment]
This is phrased in terms of very old details of the resource model, and much of the details of any possible concerns here are different after implementing provider diffing.  Closing this out - and we can open more actionable issues if needed in the future.
