### ISSUE TITLE
Pkl as supported configuration language

### ISSUE THREAD

**Issue by o-l-a-v** [pulumi/pulumi#17807]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It'd be sweet if Pulumi supported Pkl as configuration language. It's a language by Apple which has a lot of nice features for authoring configuration files.

* <https://pkl-lang.org/>
  * <https://pkl-lang.org/main/current/language-reference/index.html>
* <https://github.com/apple/pkl>
  * <https://github.com/apple/pkl/discussions/7>

It can be transpiled to JSON or YAML, so we can in theory already use it with Pulumi. But native support would be even better.

### Affected area/feature

IaC authoring experience

**Comment by Frassle** [comment]
You could use the yaml runtimes compiler option (https://www.pulumi.com/docs/iac/languages-sdks/yaml/#compiler-support) to make use of pkl today.

I'm not sure there would be much more we could do above that if we handled it in a first class way? But I'll leave this open to track ideas.

**Comment by ericrudder** [comment]
For now, transpiling is the best way to go; you have the best resources out posted, however, https://archive.pulumi.com/t/16597512/has-anyone-had-a-look-on-using-pkl-lang-https-pkl-lang-org-i offers another hint on quality of life improvement (pkl support libs) if you pursue.
