### ISSUE TITLE
Unsecret does not appear to accomplish its name

### ISSUE THREAD

**Issue by alfred-stokespace** [pulumi/pulumi#17844]
### What happened?

I tried to use unsecret https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/functions/unsecret.html with the expectation that the result of unsecreting would be a non-secret string.  

from the doc above
```
unsecret behaves the same as output except the returned output takes the existing output and unwraps the secret.
```

Perhaps I'm misreading what "unwraps" means, but it definitely isn't revealing the value. 

this is causing a problem for us.

We have a real project that happens to have a resource, yes it's a policy and it seems a secret was defined that has overlap with the name of the policy.  Now, likely it is the case that we choose a poor secret in this project, but so what! Don't make me change a secret, which might have substantial impact elsewhere.  If I decide it's okay to reveal a secret I should have that power. 

I'd like to export the name of the policy, so as to refer to it from other stacks (and arn suffers from this too since arn of a policy has the name in it as well) but I can't because it is tainted with the [secret] block and unsecret doesn't solve the problem.

If I say `unsecret` a secret, that is what I expect to happen.  Let me decide whether it's safe to expose that value.

### Example

super simple example...

lets start with the config
```
>$ pulumi config
KEY            VALUE
aws:region     us-REDACTED
pulumi:tags    {"pulumi:template":"aws-typescript"}
fooNameSecret  [secret]
alfreds@DESKTOP:~/work/pulumi-bug

# lets see the value of that secret
>$ pulumi config get fooNameSecret
pulumi-bugs
```
now here's the simple code, that I WOULD expect to produce [secret], and it does! :) 
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import { interpolate } from "@pulumi/pulumi";

const stackName = pulumi.getStack();
const current = aws.getCallerIdentity({});
const accountId = current.then(current => current.accountId);
const awsRegion = new pulumi.Config('aws').get('region');

const parameterPolicy = new aws.iam.Policy(`${stackName}`, {
    name: `${stackName}-pulumi-bugs`,
    policy: interpolate`{
"Statement": [        
    {
        "Action": [
            "ssm:GetParameters",
            "ssm:GetParameter"               
        ],
        "Effect": "Allow",
        "Resource": ["arn:aws-us-gov:ssm:${awsRegion}:${accountId}:parameter/whynot*"]
    }
],
"Version": "2012-10-17"
}`
})

export const policyName = parameterPolicy.name
// yes this is commented out for demonstrating no change!!!
// export const policyName = pulumi.unsecret(parameterPolicy.name)
```
now `up` that
```
Do you want to perform this update? yes
Updating (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/alfreds/pulumi-bugs/dev/updates/3

     Type                 Name             Status               Info
     pulumi:pulumi:Stack  pulumi-bugs-dev                       
 +-  └─ aws:iam:Policy    dev              replaced (0.38s)     [diff: ~name]

Outputs:
  ~ policyName: "[secret]" => "dev-[secret]"

Resources:
    +-1 replaced
    1 unchanged
```

now, uncomment that line `// export const policyName = pulumi.unsecret(parameterPolicy.name)` and comment the one above it

so now your code should be like this...
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import { interpolate } from "@pulumi/pulumi";

const stackName = pulumi.getStack();
const current = aws.getCallerIdentity({});
const accountId = current.then(current => current.accountId);
const awsRegion = new pulumi.Config('aws').get('region');

const parameterPolicy = new aws.iam.Policy(`${stackName}`, {
    name: `${stackName}-pulumi-bugss`,
    policy: interpolate`{
"Statement": [        
    {
        "Action": [
            "ssm:GetParameters",
            "ssm:GetParameter"               
        ],
        "Effect": "Allow",
        "Resource": ["arn:aws-us-gov:ssm:${awsRegion}:${accountId}:parameter/whynot*"]
    }
],
"Version": "2012-10-17"
}`
})

//export const policyName = parameterPolicy.name
export const policyName = pulumi.unsecret(parameterPolicy.name)
```
now do an `up`

```
     Type                 Name             Status     
     pulumi:pulumi:Stack  pulumi-bugs-dev             

Outputs:
    policyName: "dev-[secret]"

Resources:
    2 unchanged

Duration: 4s
```

I expected to see the secret exposed.

### Output of `pulumi about`

```
CLI          
Version      3.136.1
Go Version   go1.23.2
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.60.0
resource  awsx    2.19.0
resource  docker  4.5.7
resource  docker  3.6.1
language  nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/alfreds/.nvm/versions/node/v18.20.1/bin/node' version='v18.20.1'

Current Stack: alfreds/pulumi-bugs/dev

TYPE                   URN
pulumi:pulumi:Stack    urn:pulumi:dev::pulumi-bugs::pulumi:pulumi:Stack::pulumi-bugs-dev
pulumi:providers:aws   urn:pulumi:dev::pulumi-bugs::pulumi:providers:aws::default_6_60_0
aws:iam/policy:Policy  urn:pulumi:dev::pulumi-bugs::aws:iam/policy:Policy::dev


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/alfreds
REDACTED

Dependencies:
NAME            VERSION
typescript      5.7.2
@pulumi/aws     6.60.0
@pulumi/awsx    2.19.0
@pulumi/pulumi  3.141.0
@types/node     18.19.64

Pulumi locates its logs in /tmp by default
```

### Additional context

this is causing a problem for us.

We have a real project that happens to have a resource, yes it's a policy and it seems a secret was defined that has overlap with the name of the policy.
I'd like to export the name of the policy (and arn suffers form this too since arn of policy has the name in it) but I can't because it is tainted with the [secret] block.

Now, likely it is the case that we choose a poor secret, but so what, don't make me change a secret, which might have substantial impact.  
If say `unsret` a secret, that is what I expect to happen.  Let me decide whether it's safe to expose that value.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
This is what's happening: The CLI has an output filter that automatically masks secret config values written out to stdout/stderr or logs during pulumi operations like `pulumi up`, replacing the string with `[secret]`. So anytime such a string is emitted, it's emitted as `[secret]`.

Note that in this case the value itself isn't a secret. Whether you do either of:

```typescript
export const policyName = parameterPolicy.name
export const policyName = pulumi.unsecret(parameterPolicy.name)
```

... the exported value will be stored in Pulumi's state in plaintext.

Again, it's just the output filtering that's making it display as `[secret]`.

> I'd like to export the name of the policy, so as to refer to it from other stacks (and arn suffers from this too since arn of a policy has the name in it as well) but I can't because it is tainted with the [secret] block and unsecret doesn't solve the problem.

I'm curious to know what you're trying to do that isn't working. This should still work regardless of the output filtering. Would love to help!

`pulumi stack output policyName`, for example, should output the value without it being masked, since the exported value itself isn't a secret.

Note that if the value _was_ a secret, e.g. like this:

```typescript
export const policyName = pulumi.secret(parameterPolicy.name)
```

... it would be encrypted in the state, and to see the actual value you'd have to use `pulumi stack output policyName --show-secrets`.

**Comment by alfred-stokespace** [comment]
@justinvp thank you for the explanation.  I assumed that what-i-see-is-what-i-get and didn't even try to use the exported value. What I'm understanding is that, in actual fact the exports are not secrets despite being indicated that way in stdout/stderr.

I'll give that a try. 

I'll close this.  I do still think this is confusing.
