### ISSUE TITLE
Pulumi v3.141.0 breaks using templates on the local filesystem

### ISSUE THREAD

**Issue by RandyHoffman** [pulumi/pulumi#17862]
### What happened?

We create stacks from a Pulumi template directory on the local filesystem using the `pulumi new` cmd.  This capability no longer works in Pulumi v3.141.0 and appears to be related to this [PR](https://github.com/pulumi/pulumi/pull/17824)

If this is intentional, is there a way to create stacks from a local template directory on the local file system?

### Example

This command works in v3.140.0, but not in v3.141.0:
`pulumi new /root/templates/some-project-template'  -g -t -y -f -n 'some-project-name' -d 'Some Project' --dir /tmp/foo`

It now throws this error:
`error: failed to retrieve git folder: failed to clone ref 'refs/heads/main': Get "https:///root/templates.git/info/refs?service=git-upload-pack": http: no Host in request URL`

The templates exist in `/root/templates`
I tried using `file:///root/templates/some-project-template` as the template dir but that issues a template not found error:
`error: template 'file:///root/templates/some-project-template' not found`

### Output of `pulumi about`

# pulumi about
CLI
Version      3.141.0
Go Version   go1.23.3
Go Compiler  gc

Plugins
KIND      NAME       VERSION
resource  aws        6.52.0
language  go         unknown
resource  terraform  5.13.4

Host
OS       ubuntu
Version  24.10
Arch     aarch64

This project is written in go: executable='/usr/bin/go' version='go version go1.23.2 linux/arm64'

Backend
Name           3281d6027c1a
URL            s3://some-pulumi-state-bucket
User           root
Organizations
Token type     personal

Dependencies:
NAME                                       VERSION
github.com/pulumi/pulumi-aws/sdk/v6        v6.52.0
github.com/pulumi/pulumi-terraform/sdk/v5  v5.13.4
github.com/pulumi/pulumi/sdk/v3            v3.130.0
github.com/rs/zerolog                      v1.33.0

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> If this is intentional, is there a way to create stacks from a local template directory on the local file system?

Ah no, not intentional. I think when reviewing I didn't realize these were already working with go-git and the change broke them. We'll revert and rethink.
