### ISSUE TITLE
pulumi CLI assumes it is non-interactive

### ISSUE THREAD

**Issue by shoriminimoe** [pulumi/pulumi#17863]
### What happened?

I am attempting to run `pulumi up` in an interactive shell, but pulumi thinks it is non-interactive and requires additional arguments for non-interactive shells, e.g. `--yes` or `PULUMI_ACCESS_TOKEN`.

### Example

These are the steps I performed:

```console
$ # Install pulumi:
$ sh -c "$(curl -fsSL https://get.pulumi.com)" -- --install-root ~/.local/pulumi
$ export PATH="~/.local/pulumi/bin:$PATH"

$ # Attempt login
$ pulumi login
error: problem logging in: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions

$ PULUMI_ACCESS_TOKEN=*** pulumi login
Logging in using access token from PULUMI_ACCESS_TOKEN
Logged in to pulumi.com as violation1139 (https://app.pulumi.com/violation1139)

$ # Initialize a new project
$ pulumi new python
error: --yes must be passed in to proceed when running in non-interactive mode

$ pulumi new python -y
Created project 'project'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
Created stack 'dev'
...

$ # Create resources
$ pulumi up
error: --yes or --skip-preview must be passed in to proceed when running in non-interactive mode

$ pulumi up -y
Previewing update (dev)

...
```

### Output of `pulumi about`

CLI          
Version      3.141.0
Go Version   go1.23.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  python  unknown

Host     
OS       debian
Version  bookworm/sid
Arch     x86_64

This project is written in python: executable='/home/scaldwell/Scratch/pulumi/venv/bin/python' version='3.10.12'

Current Stack: violation1139/project/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/violation1139
User           violation1139
Organizations  violation1139
Token type     personal

Dependencies:
NAME        VERSION
pip         24.3.1
pulumi      3.141.0
setuptools  75.6.0
wheel       0.45.1

Pulumi locates its logs in /tmp by default

### Additional context

Additional troubleshooting in this Slack thread: https://pulumi-community.slack.com/archives/C01PF3E1B8V/p1732574710281509

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Ah found some answers from the slack thread:
```
Sam Caldwell
  Yesterday at 10:47 PM
Some details: I'm using fish shell with kitty terminal. The TERM variable is xterm-kitty

Sam Caldwell
  Today at 12:58 AM
Hmm... This worked:
$ # Run fish with clean environment
$ env -i fish --no-config
$ pulumi up
Previewing update (dev)
...
There must be some configuration thing happening.
```

I guess fish is doing _something_ odd here to throw off Go's "is terminal" check (https://pkg.go.dev/golang.org/x/term#IsTerminal).

**Comment by shoriminimoe** [comment]
> Ah found some answers from the slack thread:
> 
> ```
> Sam Caldwell
>   Yesterday at 10:47 PM
> Some details: I'm using fish shell with kitty terminal. The TERM variable is xterm-kitty
> 
> Sam Caldwell
>   Today at 12:58 AM
> Hmm... This worked:
> $ # Run fish with clean environment
> $ env -i fish --no-config
> $ pulumi up
> Previewing update (dev)
> ...
> There must be some configuration thing happening.
> ```
> 
> I guess fish is doing _something_ odd here to throw off Go's "is terminal" check (https://pkg.go.dev/golang.org/x/term#IsTerminal).

That's right. I haven't narrowed down the specific setting(s) yet.

Thanks for pointing out `IsTerminal`. Are there any other criteria the CLI tool uses to detect an interactive terminal?

**Comment by Frassle** [comment]
> Are there any other criteria the CLI tool uses to detect an interactive terminal?

https://github.com/pulumi/pulumi/blob/master/sdk/go/common/util/cmdutil/console.go#L51

It checks if TERM=="dumb", IsTerminal and if it thinks it's in a CI system (https://github.com/pulumi/pulumi/blob/master/sdk/go/common/util/ciutil/detect.go#L147). Might be something in your environment is tripping that last check?

**Comment by shoriminimoe** [comment]
Aha! `IsCI` got me. There are quite a few variables it is looking for. My culprit was `JENKINS_URL`.

Conveniently, there is a way to disable CI detection by setting the `PULUMI_DISABLE_CI_DETECTION` environment variable. Thanks for the help @Frassle!
