### ISSUE TITLE
Orphaned locks due to transient Google Cloud Storage errors

### ISSUE THREAD

**Issue by pgcamus** [pulumi/pulumi#17876]
### What happened?

Occasionally GCS will hiccup and fail to delete a file, e.g.

```
2024-11-22 18:11:45.453666+00:00 I up tools/TTTT-tuna stderr: error: there was a problem deleting the lock at gs:/camus-infra-pulumistate/tools/.pulumi/locks/organization/tools/TTTT-tuna/37f829e3-c259-489a-b714-124bc8fcd565.json, manual clean up may be required: blob (key ".pulumi/locks/organization/tools/TTTT-tuna/37f829e3-c259-489a-b714-124bc8fcd565.json") (code=Unknown): googleapi: Error 503: We encountered an internal error. Please try again., backendError
```

Manually removing the lock file resolves the issue.

### Example

This is transient when using the Google Cloud Storage backend.

### Output of `pulumi about`

$ pulumi about
CLI          
Version      3.127.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME           VERSION
resource  command        0.11.1
resource  gcp            8.9.1
resource  grafana        0.5.1
resource  kubernetes     4.17.1
resource  postgresql     3.11.3
language  python         unknown
resource  random         4.16.3
resource  synced-folder  0.11.1

Host     
OS       ubuntu
Version  22.04
Arch     aarch64

This project is written in python: executable='/home/builder/.cache/bazel/_bazel_builder/111d6a28ddfe7cb2f314c9d3cd6a7751/execroot/ritta/bazel-out/aarch64-dbg/bin/infra/pulumi/pulumi.runfiles/python3_10_aarch64-unknown-linux-gnu/bin/python3' version='3.10.9'

Backend        
Name           builderdev.pg.serengeti.localdomain
URL            gs://XXXX/tools
User           builder
Organizations  
Token type     personal

Dependencies:
NAME                         VERSION
absl-py                      2.1.0
dnspython                    2.6.1
gcsfs                        2024.10.0
google-api-python-client     2.121.0
google-cloud-asset           3.26.1
google-cloud-bigquery        3.21.0
google-cloud-bigtable        2.23.1
google-cloud-compute         1.18.0
google-cloud-pubsub          2.21.1
google-cloud-secret-manager  2.20.0
grafanalib                   0.7.1
influxdb                     5.3.2
Jinja2                       3.1.4
kubernetes                   24.2.0
Pint                         0.24.3
pip                          22.3.1
prometheus_client            0.20.0
psycopg2-binary              2.9.10
pulumi_command               0.11.1
pulumi_gcp                   8.9.1
pulumi_kubernetes            4.17.1
pulumi_policy                1.13.0
pulumi_postgresql            3.11.3
pulumi_random                4.16.3
pulumi_synced_folder         0.11.1
pulumiverse_grafana          0.5.1
PySnooper                    1.2.1
PySocks                      1.7.1
python-json-logger           2.0.7
python-socks                 2.5.3
Shapely                      1.8.5.post1
stringcase                   1.2.0

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack

### Additional context

As a rough estimate we see this maybe 1/50k times we run Pulumi operations. This sounds pretty infrequent, but with automation we end up hitting it once a week or so.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
`pulumi cancel` should help fix this at least. We can look at adding some retry logic to the delete code as well.
