### ISSUE TITLE
`pulumi stack select` allows you to select a stack for a different project, leading to confusing behavior

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1787]
Using `pulumi stack select`, you can select any stack you have access to on Pulumi.com, even if it doesn't match the current project.  This can lead to surprising results later.

We saw an instance where someone had closely related projects, each with their own production, staging and testing stacks.  So in their account, there are six stacks:

- app1-production
- app1-staging
- app1-testing
- app2-production
- app2-staging
- app2-testing

Due a typo in how some scripts where invoked as part of their use of Pulumi in CI, they ended up running: `pulumi stack select app1-staging` in the directory for app2.  Pulumi allowed this to happen, but when they then ran `pulumi update` things quickly went off the rails, with an error saying aws:region was not set. This happened because the CLI tried to load `Pulumi.app1-staging.yaml` to read configuration data, but since we were in the app2 directory, this file was not present, meaning we didn't load any configuration data.

I suspect that at a minimum `pulumi stack select` should warn in a case where you end up selecting a stack for a different project. If may make more sense to actually error here, with an optional `--force` flag, for a case where you really wanted to do this (I can't think of a reason you'd want to do this, but I'm sure the moment we wall it off someone will find a good reason to do so).

**Comment by joeduffy** [comment]
I vote for an error.

**Comment by captncraig** [comment]
I also ran into this. Using "dev", "prod" and such for stack names. I have two projects side by side with different stacks. It seems the local storage has no notion of namespacing by project, and it looks like the Backend interface does not either. That kinda constrains how we were trying to do things.

**Comment by ellismg** [comment]
> That kinda constrains how we were trying to do things.

Yeah, this models how we model stacks on pulumi.com.  A stack name needs to be unique across all stacks for a given user (and the local back-end only has a single user).  We've taken to naming stacks `<project-name>-<stack-name>`.

**Comment by ellismg** [comment]
We plan to move the "project" into the stack's identity (for both the local backend and for the Pulumi.com backend), so this should become less of a pain-point as `pulumi stack select` and friends will only be able to see stacks for the current project, by default.  I'll keep this open until #2039 lands.

**Comment by ellismg** [comment]
With the adjustments to the identity model, this is no longer an issue.
