### ISSUE TITLE
Self-managed backend with Scaleway S3 provider

### ISSUE THREAD

**Issue by BrodaUa** [pulumi/pulumi#17886]
### What happened?

I face the same issue as described in [ticket 16242](https://github.com/pulumi/pulumi/issues/16242), unless the provided workaround does not work with Scaleway S3 object storage:

![Image](https://github.com/user-attachments/assets/a5823029-2664-4948-97b1-d3f40a239529)

Even though the `aws s3 ls` works well with the same credentials

### Example

1) install pulumi: `brew install pulumi/tap/pulumi`
2) create API Keys: https://www.scaleway.com/en/docs/identity-and-access-management/iam/api-cli/using-api-key-object-storage/
3) set env varsiables:
```
export PULUMI_BACKEND_URL=https://default-cs-pulumi-backend.s3.fr-par.scw.cloud

export SCW_ACCESS_KEY=<ACCESS_KEY>
export SCW_SECRET_KEY=<SECRET_KEY>
# OR
export AWS_ACCESS_KEY=<ACCESS_KEY>
export AWS_SECRET_KEY=<SECRET_KEY>
# OR BOTH TYPES OF THE ABOVE
```

### Output of `pulumi about`

CLI          
Version      3.142.0
Go Version   go1.23.3
Go Compiler  gc

Host     
OS       darwin
Version  15.1.1
Arch     arm64

Backend        
Name           https://default-cs-pulumi-backend.s3.fr-par.scw.cloud
URL            
User           Unknown
Organizations  
Token type     personal

Pulumi locates its logs in /var/folders/y9/t4pc6gsx32z75lbt7t7_3zl40000gn/T/ by default
warning: Failed to read project: no Pulumi.yaml project file found...
warning: Failed to get information about the current stack: no Pulumi.yaml project file found...

### Additional context

I want to use a self manged S3 bucket as a backend for Pulumi as outlined [here](https://www.pulumi.com/docs/iac/concepts/state-and-backends/#using-a-self-managed-backend)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Try quoting the string in the first command, the default shell used by macos, `zsh` will treat `?` as a glob pattern and it's failing to match a file named `s3://...`, hence the error "zsh: no matches found ..." error.

If the URL is quoted, it should just work!

**Comment by Frassle** [comment]
Thanks for pointing that out @AaronFriel! 

@BrodaUa can you confirm things work after that?

**Comment by BrodaUa** [comment]
Thanks @AaronFriel !
Yes, @Frassle , adding quoting marks resolved the issue.
