### ISSUE TITLE
Export of entire resource only shows ID, URN and packageVersion

### ISSUE THREAD

**Issue by serpro69** [pulumi/pulumi#17884]
### What happened?

I'm trying to export an entire resource instead of a single field, but the output shows only `id`, `urn`, and `packageVersion` fields:

```json
{
  "bucket": {
    "4dabf18193072939515e22adb298388d": "5cf8f73096256a8f31e491e813e4eb8e",
    "id": "my-bucket-15003c9",
    "packageVersion": "",
    "urn": "urn:pulumi:tmp.f9st2wsEsp::tmp.f9st2wsEsp::gcp:storage/bucket:Bucket::my-bucket"
  }
}
```

This happens with all resources I've tried, not just the one in the example.

### Example

```go
package main

import (
	"github.com/pulumi/pulumi-gcp/sdk/v8/go/gcp/storage"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		bucket, err := storage.NewBucket(ctx, "my-bucket", &storage.BucketArgs{
			Location:                 pulumi.String("US"),
			UniformBucketLevelAccess: pulumi.BoolPtr(true),
		})
		if err != nil {
			return err
		}

		ctx.Export("bucket", bucket)
		return nil
	})
}
```

### Output of `pulumi about`

CLI          
Version      3.129.0
Go Version   go1.22.6
Go Compiler  gc

Plugins
KIND      NAME  VERSION
resource  gcp   8.2.0
language  go    unknown

Host     
OS       debian
Version  bookworm/sid
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.23.1 linux/amd64'

Backend        
Name        serenity
URL            gs://...
User           sergio
Organizations  
Token type     personal

Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-gcp/sdk/v8  v8.2.0
github.com/pulumi/pulumi/sdk/v3      v3.130.0

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Thanks for opening the issue, @serpro69. This is being tracked already at https://github.com/pulumi/pulumi/issues/3826, so I'm going to close this as a duplicate.

I also added a [comment here](https://github.com/pulumi/pulumi/issues/3826#issuecomment-2526503671) that shows how you could workaround this today with a helper function that converts a resource into a `pulumi.Map` that can be exported.
