### ISSUE TITLE
Feature Request - Ability to update import IDs on resources where the field is blank

### ISSUE THREAD

**Issue by scottp-dpaw** [pulumi/pulumi#17908]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

My employer is in the process of porting most of their AWS infrastucture provisioning code to Pulumi's Python API. This covers a lot of infrastructure that is already deployed, so in the design of the Pulumi projects we take the following approach:
- Search for an existing resource (using the .get_XXX() APIs), using only the attributes we consider distinct (e.g. a VPC with a certain cidr_block)
- If that call succeeds, pass the ID of that resource to import_ as part of ResourceOptions.
- If it throws an exception, pass None to import_.
- Define the resource with the full list of attributes.

For the majority of AWS resources, this works fine. In the case of a resource created by Pulumi, then second time around being provided an import ID by the program, it can see that the resource ID (usually the ID provided by AWS) is the same and doesn't consider it a change.

Where things get tricky is cases where there isn't an AWS provided ID. The Terraform AWS provider generally makes do with a composite key as the import ID (e.g. ec2.RouteTableAssociation expects a combined "{resource_id}/{route_table_id}"). But for reasons that I don't understand, the Terraform AWS provider will generate a _new_ ID, usually some kind of truncated or hashed version of the original, and store that on the books as the resource's ID. Pulumi seems to recognise this, and will work around it if the provided import ID doesn't match the one on the books: https://github.com/pulumi/pulumi/blob/ad144da8295ce8fdec4bc3fcb9b058ac19e7a375/pkg/resource/deploy/step_generator.go#L632

The issue is this doesn't work for non-AWS-provided-ID resources that were created by Pulumi, then subsequently given a valid import ID. The resources will show up as a spurious "import-replacement" step, which is unlikely to work (e.g. ec2.RouteTableAssociation will try to create "new" associations, then delete the existing associations. This resulted in all the RouteTableAssociations being deleted and Pulumi assuming they still exist).

I'm not sure about the best way to address this, but it would be nice if there was a config switch which would allow Pulumi to auto-override an empty import ID with a provided one.

### Affected area/feature

Pulumi deployment step generator

**Comment by Frassle** [comment]
So just to check I follow this. The scenario is you create a resource with pulumi, e.g. a RouteTableAssociation. You then edit your program to fill in the ImportID for that resource for the thing just created. You then run pulumi again and it gets confused and tries to do an import-replacement.

And what your after is for this to either just work, or to have some way to say "trust this import ID is correct, don't replace it"?

**Comment by scottp-dpaw** [comment]
The idea is that the program will try and check if the resource is there in AWS, and fill in the import parameter if it is. Ideally there doesn't need to be any manual change to the program between runs.

If there is no existing resource in AWS, the import parameter will be None for the first run (which creates the resource), then set to the ID of the resource for subsequent runs.

If there is an existing resource in AWS, the import parameter will be the ID of the resource for the first and subsequent runs.

90% of the time this works; it's just that edge case of resources with a non-AWS-provided ID which causes it to trip up.

**Comment by scottp-dpaw** [comment]
One workaround we considered was to have a manual flag at the start of the program which enables sending import parameters to everything. This mostly works, however you get basically one chance at running it and if anything goes wrong you need to delete the stack.

Another option would be to somehow interrogate the Pulumi stack and don't send the import parameter if the resources exist. It didn't look like this was possible with the API, so we wrote this off as the wrong approach.

**Comment by Frassle** [comment]
OK I follow, thanks for the clarification. I'm going to close this off as a duplicate, I think think this would be well covered by https://github.com/pulumi/pulumi/issues/3388 which is to allow your pulumi program to express the concept of "create this resource if it doesn't already exist, else import it".
