### ISSUE TITLE
`pulumi new` should prompt to run `up` automatically

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#1792]
`pulumi new` already walks through creating a stack and saving required config, and at the end, suggests running `cd <project>` and `pulumi up` to do an initial deployment.

We should consider just running `up` automatically at the end. It'll show the preview and prompt the user whether or not to proceed. (It would not do this when the `--generate-only` flag is specified.)

**Comment by justinvp** [comment]
@pgavlin, @ellismg, @lukehoban, We talked about it briefly, but I don't remember where we landed: What do we do for templates/examples/apps that require an intermediate build step before it can be deployed? In general, the best practice will be for these to be deployable, but there will be cases that require a build step (e.g. go templates).

Some ideas:

- We could add a property that could be specified in `Pulumi.yaml` under `template:` to opt-out of automatic `up`. Or opt-in.

- We could ask the language host if we should proceed with an automatic `up`. For go, the language host could say "no". For nodejs, we could do some analysis to see if there is a build script specified in `package.json` (for old style TypeScript, or other transpile scenarios).

 - I don't love this as it's not a great experience, but we could just proceed with trying the `up` and let it fail (with good error message on next steps). We'll need the good error message anyway as someone might try to run `up` before the build step anyway when doing things manually.

**Comment by ellismg** [comment]
From what I recall, I think we briefly discussed how long term we would use ‘go run’ instead of an explicit build step in the Go language host (that was feeeback independent of this work). Then we sort of felt if we had that, not having support for an explicit build step would be okay.
