### ISSUE TITLE
When asking for new stack name, provide a default name

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#1794]
Anytime we prompt for a new stack name, we should provide a default name.

**Comment by justinvp** [comment]
Would like to have gotten to this, but it's not critical to the experience for M17.

**Comment by joeduffy** [comment]
I was just able to file an issue for this -- would definitely like to align this with the behavior we have for `pulumi new`. My proposal is to use `dev` as the default, and to do something like:

```
$ pulumi new
Enter a stack name ("dev"): 
```

and if you simply hit ENTER, it uses the default name.

**Comment by mikhailshilkov** [comment]
`pulumi new` seems to be doing this already:

```
Created project 'test'

stack name: (dev)
Created stack 'dev'
```

while stack selection dialog's "create a new stack" option doesn't:

```
Please choose a stack, or create a new one: <create a new stack>
Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`):
error: could not create stack: validating stack properties: invalid stack name: a stack name may only contain alphanumeric, hyphens, underscores, or periods
```

`(e.g. 'acmecorp/dev')` is also confusing for me: it feels that `acmecorp/dev` is the default option. "What's `acmecorp`?" "Does `pulumi` think it's my organisation?"

Should we just remove `To create a stack in an organization...` note and copy the behavior of `pulumi new`?
