### ISSUE TITLE
Azure Key Vault secret provider makes 2x calls to decrypt, including an unauthenticated call

### ISSUE THREAD

**Issue by barclayadam** [pulumi/pulumi#17994]
### What happened?

When using the Azure KeyVault secrets provider I'm seeing double calls to decrypt/encrypt secrets. The first call is a 401, followed by a successful 200 response:

![Image](https://github.com/user-attachments/assets/e687d4c4-da0b-4378-ae2f-45446f80606d)

The first call provides no authorisation headers at all, the 2nd provides the correct Bearer token:

![Image](https://github.com/user-attachments/assets/1b57dd88-cd64-4fdf-905b-546ac1494d43)

vs

![Image](https://github.com/user-attachments/assets/5dde0bcc-11e4-4d93-92a1-aa1efdd47591)

### Example

Use the Azure KeyVault secrets provider. Not sure if makes any difference, but we use the Automation API

### Output of `pulumi about`

CLI
Version      3.140.0
Go Version   go1.23.3
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure         4.37.0
resource  azure-native  2.72.0
resource  azuread       5.46.0
resource  cloudflare    5.43.1
resource  docker-build  0.0.7
resource  kubernetes    4.15.0
resource  newrelic      5.10.0
language  nodejs        unknown
resource  random        4.0.0
resource  tls           4.0.0

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22631 Build 22631
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v22.1.0'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I think all of this is managed by [gocloud](https://gocloud.dev/), but we can look into that. Just likely the issue will have to get raised against gocloud eventually.

**Comment by tgummerer** [comment]
I believe this is one layer deeper actually, in the azure SDK.  This is documented here: https://learn.microsoft.com/en-us/azure/key-vault/general/authentication-requests-and-responses#authentication (see the *Note* at the bottom of the linked page).  So I think this is actually correct and expected behaviour.  Are the extra requests causing problems for you?
