### ISSUE TITLE
Support simpler way(s) of passing providers to ComponentResources

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1802]
For CustomResources, we support `{ provider: myProvider }`, but for ComponentResources we require `{ providers: { kubernetes: myProvider } }`.  The latter both feels a bit awkward, but also importantly is just different which is surprising as users generally don't have to think about whether they are using a `CustomResource` or `ComponentResource` - in almost every other way these feel "the same".

We should consider two improvements here:
1. Accept `providers` as an array as well as a map - inferring the kind of the provider from the provider object itself.
2. Accept a `provider:` provider as a shorthand for `providers: [myProvider]` for the (very common) case of only parametrizing by a single provider.

**Comment by lukehoban** [comment]
From #2263 which is related enough that I'm closing as a dupe (even though it's suggesting something that's possibly the opposite - we should make and implement a single decision here).

---

While passing a 'provider' is one of the more common expected patterns for a CustomResource, there is no problem with passing 'providers' (plural), and it even makes sense in a world with arbitrary resource parenting.

We should just allow this work. Note this means a few things fall out:

1. 'providers' should just move into ResourceOptions.
2. We probably want to give either an ordering, or an error if you give both 'provider' and 'providers' (i would prefer an error). If we really needed both, you could just pass 'providers' with 'provider' added to it under the appropriate key.

**Comment by lukehoban** [comment]
Also note that we've had reports of hitting `Explicit providers may not be used with component resources` errors which are related here.  We at least need to improve that error message, but likely as part of doing the work tracked by this issue it will go away entirely.

A user reported the following - which sounds like it shouldn't be triggering this in the first place:

> I have a class extending `pulumi.ComponentResource`, let’s call it `MyComponent`, creating in its `constructor` a `k8s.core.v1.ConfigMap` and a `k8s.helm.v2.Chart` the former getting a direct reference to it in the later `values` args.
Both have their `opts` like `{ parent: this }`, `this` obviously referencing `MyComponent`.
`MyComponent` is called with `opts` like `{ providers: { kubernetes: k8sProvider /* a working k8s.Provider instance */ } }`

**Comment by CyrusNajmabadi** [comment]
Openin since we reverted this PR and didn't take it back in agian.

**Comment by ellismg** [comment]
Did this get re-fixed with https://github.com/pulumi/pulumi/pull/2609, @CyrusNajmabadi?

**Comment by CyrusNajmabadi** [comment]
Yes.  Closed with #2609
