### ISSUE TITLE
Pulumi not picking up tsconfig transpileOnly setting

### ISSUE THREAD

**Issue by ma-ts** [pulumi/pulumi#18047]
Currently, when you want to use alternative typescript compilers (such as SWC) for performance reasons, the attribute `transpileOnly` has to be set to true. Apparently, when Pulumi executes the typescript it overrides the transpileOnly property from the tsconfig.json. 

Can someone elaborate why this piece of code is here? I was looking back in the PR that added it, however I could not find any good rationale:

https://github.com/pulumi/pulumi/blob/fd6853c3f61f96345a11cf96acd2b4eddf58c6b5/sdk/nodejs/cmd/run/run.ts#L258

Teams using typescript should use the `tsconfig.json` to set typescript, instead of through environment variables in Pulumi.

**Comment by justinvp** [comment]
Thanks @ma-ts. Agreed that this should be set through `tsconfig.json`.

When the envvar isn't set to `"true"`, rather than falling back to `"false"`, I'm wondering if we shouldn't set it at all, and if that'd allow whatever is specified in `tsconfig.json` to take precedence. Will have to try it out.

**Comment by julienp** [comment]
I don't think `transpileOnly` is a TypeScript option, it is a ts-node option, there is however a new [`noCheck` option](https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/#the---nocheck-option) in 5.6. See also https://github.com/microsoft/TypeScript/issues/29651

Here's a PR that respects that flag https://github.com/pulumi/pulumi/pull/18067

Note that if you configure `swc` in the tsconfig, ts-node will automatically set `transpileOnly: true`

```
{
  "compilerOptions": {
     ...
  },
  "ts-node": {
    "swc": true
  }
}

```
