### ISSUE TITLE
DependsOn for Provider Functions update breaks existing direct form invocation of DependsOn code

### ISSUE THREAD

**Issue by juangre977** [pulumi/pulumi#18087]
### What happened?

Hi all!

The following updates broke most of our code using **dependsOn**:
https://github.com/pulumi/pulumi/discussions/17710
https://github.com/pulumi/pulumi/pull/17791
with errors of the type
`decoding YAML: DependsOn is not supported for direct form invoke of "kubernetes:yaml:decode", use the output form instead`
depending on the provider function of course. The RFC above provides hints how to solve it but we havent been able to find a satisfying fix. 

For the pulumi-kubernetes/sdk/v3/go/kubernetes/yaml sdk there also appears to be no form of output form invocation so i assume the way to solve this would be using some form of apply/all.

Would appreciate any hints on how to best fix this.

Question: From the RFC i understand that these dependsOn might have no effect at all since the direct invocations are not part of the dependency graph, is that correct?

### Example

We are using the following pattern frequently in code. 
Wasn't able to reproduce the error in a minimal example for now, below is a part of our code producing the first instance of the error:

```go
        // certmanager.go
	func CreateCertManagerCrd(ctx *pulumi.Context, k8sProvider *kubernetes.Provider) (pulumi.Resource, error) {
		m, err := u.GetProjectMetaInfo()
		if err != nil {
			return nil, err
		}
		certManagerVersion := m.Charts["cert-manager"]
		certmancrd, err := yaml.NewConfigFile(ctx, "cert-manager-crd", &yaml.ConfigFileArgs{
			File: "./charts/cert-manager/cert-manager-" + certManagerVersion + "/crd/cert-manager.crds.yaml",
		}, pulumi.Provider(k8sProvider))
		if err != nil {
			return nil, err
		}

		return certmancrd, nil
	}
	
	// cilium.go
	// Fails with
	// decoding YAML: DependsOn is not supported for direct form invoke of "kubernetes:yaml:decode", use the output form instead
	
	k8sComp.certManagerCrd, err = k8s.CreateCertManagerCrd(ctx, k8sProvider)
	if err != nil {
		return nil, err
	}
	_, err = kubeyaml.NewConfigFile(ctx, "cilium-ca-selfsigned-issuer", &kubeyaml.ConfigFileArgs{
		File: "./charts/cilium/ca-selfsigned-issuer.yaml",
	}, pulumi.Provider(k8sProvider), pulumi.DependsOn([]pulumi.Resource{k8sComp.certManagerCrd}))
	if err != nil {
		panic(err)
	}
```

### Output of `pulumi about`

CLI
Version      3.143.0
Go Version   go1.23.4
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.78.0
resource  azure-native  2.78.0
resource  azure-native  2.78.0
resource  azure-native  2.78.0
resource  azure-native  2.78.0
resource  azure-native  2.78.0
resource  azure-native  2.78.0
resource  azure-native  2.78.0
resource  azure-native  2.78.0
resource  azure-native  2.78.0
language  go            3.143.0
resource  kubernetes    3.30.2

Host
OS       ubuntu
Version  22.04
Arch     x86_64

Dependencies:
NAME                                                    VERSION
github.com/apparentlymart/go-cidr                       v1.1.0
github.com/creasty/defaults                             v1.8.0
github.com/go-playground/validator/v10                  v10.23.0
github.com/pkg/errors                                   v0.9.1
github.com/pulumi/pulumi-azure-native-sdk/insights/v2   v2.78.0
github.com/pulumi/pulumi-azure-native-sdk/network/v2    v2.78.0
github.com/pulumi/pulumi-azure-native-sdk/resources/v2  v2.78.0
github.com/pulumi/pulumi-kubernetes/sdk/v3              v3.30.2
github.com/pulumi/pulumi/sdk/v3                         v3.143.0
github.com/stretchr/testify                             v1.10.0
gopkg.in/yaml.v3                                        v3.0.1
k8s.io/apiextensions-apiserver                          v0.32.0
k8s.io/apimachinery                                     v0.32.0
k8s.io/client-go                                        v0.32.0

### Additional context

Thank you!

**Comment by julienp** [comment]
`kubeyaml.NewConfigFile` is a Resource, and takes a `...ResourceOptions` argument, so passing in a `DependsOn(...)` is perfectly valid here. Internally this resource calls itself the (internal) invoke `yamlDecode` and passes through the options from the resource to the invoke.

Previously this worked because the `DependsOn` was basically ignored by the invoke, but with the change to introduce `DependsOn` for output form invokes, we now longer ignore it. We also made it an error when passing `DependsOn` to a direct form invoke. Unfortunately this change is not backwards compatible, and causes the bug here.

I think what we have to do is to ignore the DependsOn in this case, instead of making it an error. This is what we did for Python and Typescript, for example https://github.com/pulumi/pulumi/blob/27cf193189a394a6c1f68583149c90fd4bd512e8/sdk/nodejs/runtime/invoke.ts#L88

**Comment by juangre977** [comment]
Hi Julien!

No worries, thank you for the clarification😄! We will simply refrain from upgrading to that release for now. 
Do you have an idea how you want to tackle it generally? I.e. fix it in the next release by making it behave similarly to python/ts as you described or make it major version upgrade or else?
In any case, thank you for the help. Happy holidays!

**Comment by julienp** [comment]
> Hi Julien!
> 
> No worries, thank you for the clarification😄! We will simply refrain from upgrading to that release for now. Do you have an idea how you want to tackle it generally? I.e. fix it in the next release by making it behave similarly to python/ts as you described or make it major version upgrade or else? In any case, thank you for the help. Happy holidays!

I think we'll match the behaviour of python/ts. I'd argue that this does not need to wait for a major version, since the behaviour we recently introduced was not backwards compatible, and that is definitely a bug!

Happy holidays :)
