### ISSUE TITLE
AWS CloudWatch Log Streams Accumulate

### ISSUE THREAD

**Issue by tvalenta** [pulumi/pulumi#1816]
Within AWS CloudWatch Log Groups, old Log Streams linger until they are pruned through an external process.  While I have not observed this to create any logging failures, I have some Log Groups over four thousand (4,000) empty Log Streams. The command `pulumi logs` appears to run much more slowly on the stacks with excessive log streams, and I hypothesize there to be a correlation.

Strangely, some of my current Log Streams report zero storedBytes, while AWS reports bytes stored on older streams that are outside the retention period. A bug in AWS would not shock me at this point. To at least validate the impact, I'm pruning some of the log groups in our test stack.

**Comment by lukehoban** [comment]
@tvalenta Just to confirm, are you seeing accumulation of many LogStreams or of many LogGroups?  (or both?)

In general, these are both somewhat difficult to manage automatically, as AWS Lambda automatically creates them for you, but does not allow any parameterization of their TTL. There are some things we could try to do in one or more layers of Pulumi to help - but we've found attempts to do that have backfired in the past.

See these for some history:
* https://github.com/pulumi/pulumi-cloud/issues/402
* https://github.com/pulumi/pulumi-cloud/pull/474
* https://github.com/terraform-providers/terraform-provider-aws/issues/454 (similar issue in Terraform AWS provider)

**Comment by tvalenta** [comment]
I have an accumulation of Log Streams, with one particular Log Group being an obscene offender.

**Comment by lukehoban** [comment]
I see. Unfortunately, I believe this is just a fundamental limitation of CloudWatch Logs and Lambda. 

See for example https://forums.aws.amazon.com/thread.jspa?threadID=178855. 

Pulumi has no role in or ability to impact the creation of LogStreams. That is entirely managed by Lambda and CloudWatch Logs. 

Barring AWS making improvements here, you may want to do some periodic cleanup to ensure that Logs cans be queried efficiently.

We should also make sure that the approach `pulumi Logs` takes to performing the CloudWatch Logs queries is as optimal as possible in he face of a large number of log streams - though I suspect this query performance degradation is also a limitation of CloudWatch Logs.

**Comment by tvalenta** [comment]
Seems like there's nothing to be done from the Pulumi side specifically in this area, but I presume there's some areas of improvements around `pulumi logs` as you mentioned.
