### ISSUE TITLE
Make the local backend a little more prominent 

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1818]
The CLI actively pushes folks towards using the service for state management. We do have a local backend, but the only documentation on it is in our FAQ: https://pulumi.io/reference/faq.html#can-i-use-pulumi-without-depending-on-pulumicom

We'd like to make a little easier to discover and use the local state management stuff. To that end, we're going to make a set of targeted improvements:

1. Simplify the gesture to use the local backend to just `pulumi login --local` instead of `pulumi login --cloud-url local://` (the former becomes an alias for the latter).
2. When we prompt for login, add a note explaining that you can `CTRL+C` and run pulumi login `--local` to use the local back-end.
3. When using the local back-end, explicitly show the location of the checkpoint file instead of a link to the service for update history.
4. Fix the cases where we don't prompt to confirm some operations or run previews when using the local backend.

Longer team, we may try to revisit our previous approach of being able to manage local stacks and remote stacks concurrently (e.g. support being logged into multiple back-ends concurrently) but for now we are okay with the bimodal experience of "you're either logged into the local system or pulumi.com"

**Comment by ellismg** [comment]
/cc @hausdorff @lukehoban @joeduffy 

I think this captures the takeaways from our conversation today.

**Comment by lukehoban** [comment]
> I think this captures the takeaways from our conversation today.

:+1:

**Comment by joeduffy** [comment]
@hausdorff Just FYI, since we will want to track this for the upcoming announces.

@ellismg We will need this in PR early next week to make the release, are you on track for that?

**Comment by joeduffy** [comment]
A few comments:

> Simplify the gesture to use the local backend to just pulumi login --local

I have always found this to be confusing. It makes it seem like I actually have a local server that I'm logging into. I wonder if we should just call this "offline mode" and to model it either with a new verb or by simply calling the flag `--offline`, as in `pulumi login --offline` (slightly awkward since you're actually initiating the _absence_ of a login...)

> When we prompt for login, add a note explaining that you can CTRL+C and run pulumi login --local to use the local back-end.

We need to be hyper-sensitive as to the wording of this. Any candidates yet?

> Fix the cases where we don't prompt to confirm some operations or run previews when using the local backend.

I urge you to get a head start on this. It's likely more complex than you think. I know when @CyrusNajmabadi did his progress reporting work, he intentionally didn't wander into this rats nest because the local and cloud backends have diverged so much. And yet, I agree we must do it.

**Comment by joeduffy** [comment]
> I wonder if we should just call this "offline mode"

Here is an alternative approach. Let's say there are two backends:

* HTTP
* Filesystem

Let's further say that we know we'll want the ability to login and use arbitrary HTTP backends, for example with self-hosted on-premises versions of the service. In those cases, I assume we'll say

```
$ pulumi login https://pulumi.acmecorp.com
```

If that's the model, which seems like a very reasonable one, then why don't we just use `file://` for this

```
$ pulumi login file://.
```

This uses the current working directory as your "file database"; if you want your checkpoints to go elsewhere, simply pass a path to another directory containing a `.pulumi` file database

```
$ pulumi login file://path/to/db
```

For now, we will make the restriction that you can only be logged into one place at a time. Per our discussion, that is a fine simplifying assumption. Over time, we likely want to enable multi-logins.

**Comment by ellismg** [comment]
> This uses the current working directory as your "file database"; if you want your checkpoints to go elsewhere, simply pass a path to another directory containing a .pulumi file database


Sure.  This is basically what we have today except that we spell `file://` as `local://` and without any path argument we default to `~/.pulimi` instead.  But If you want make the the scheme change and also drop the cloud-url parameter in favor of just putting the url as an extra argument it works for me.

If you want to run ahead with this Joe, it works for me.  Thanks for the offer.

**Comment by sstuddard** [comment]
Poking my head in the door to offer my feedback as someone evaluating Pulumi.

It's great this is being surfaced. After a couple days experimentation, it appeared that centralized state was the only way. Adopting cloud automation is a big commitment, make evaluation as friction-less as possible.

Given the high cost of adoption, I was left wondering:
 - Do I have to have my org grant Github app approval to play with this? That's high friction.
 - Do I have to depend on your website being up to operate? That gives me the willies.
 - Is it possible I could serve my own state server? How about S3? Are there or will there be options possible?

The managed/centralized state is a *great* value add, but it should be clear and easy to be self-contained.

**Comment by joeduffy** [comment]
Here's one proposal for the login prompt. I'm trying to keep it reasonably concise, but still clear.

Before:

```
$ pulumi login
We need your Pulumi account to identify you.
Enter your access token from https://app.pulumi.com/account
    or hit <ENTER> to log in using your browser            : 
```

After:

```
$ pulumi login
We need your Pulumi account to identify you
    by default, the CLI uses app.pulumi.com;
    to use the CLI without logging in, please press ^D
Enter your access token from https://app.pulumi.com/account
    or hit <ENTER> to log in using your browser            : 
```

If you hit ^D, it will direct you to a page that describes how the state checkpointing works. And you can always run with `pulumi login file://path_to_checkpoint_workspace` explicitly, this is just the default behavior when you are using the default.

**Comment by retr0h** [comment]
Would be nice if @sstuddard's questions were answered.  I'm still wondering the point of the service.  Is this the only way to use pulumi across multiple users?

**Comment by lukehoban** [comment]
> Do I have to have my org grant Github app approval to play with this? That's high friction.

No.  You can sign up for the Pulumi service with a variety of identity providers (including email now).

> Do I have to depend on your website being up to operate? That gives me the willies.

No.  If you use `pulumi login --local` there is no dependence on the Pulumi service.  You will be responsible for managing your checkpoint files and concurrency control.  If you login to the Pulumi service, state will be stored in the Pulumi service backend and will take care of checkpoint state management and concurrency control (and additional management, access control and auditing if needed).

> Is it possible I could serve my own state server? How about S3? Are there or will there be options possible?

Yes - this will be coming soon via the Pull Request at https://github.com/pulumi/pulumi/pull/2455.
