### ISSUE TITLE
Unconditionally enable preview uploads

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1826]
Per the discussion in https://github.com/pulumi/pulumi/issues/1715, I'm not seeing evidence that the performance is prohibitive with uploading preview results. I also want us to live in the world where this is enabled, and see real problems that we will solve over time, as this is key to our overall workflow features. Most of all, this is just going to keep popping up otherwise, and we have other things to focus on.

**Comment by lukehoban** [comment]
This is in progress and will be merge soon - but not blocking M17 milestone.
