### ISSUE TITLE
Finesse UX around auto-update of partial failures

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#1837]
In the following screencast, we see a resource that failed to initialize. When we run `pulumi up` again, without changing that resource, we see that the plan is to `update` the resource again, but the diff is empty. This is probably going to be confusing to some users, and we should think about what the right UX is.

Related to #1836.

[![asciicast](https://asciinema.org/a/198652.png)](https://asciinema.org/a/198652?speed=3)

**Comment by lblackstone** [comment]
Working on cleaning up the awaiters, so this won't be done before M21

**Comment by lukehoban** [comment]
@hausdorff @lblackstone Do we have a plan for what we want to do here (if anything)?

**Comment by lblackstone** [comment]
I don't have a plan for how this could be improved. The update will still show errors, and previous errors are available to refer back to if needed. I'm inclined to close this out if we don't have a concrete plan for improving the UX.

**Comment by leezen** [comment]
Closing out old issues
