### ISSUE TITLE
Spurious diagnostics in Travis - "flag provided but not defined: -tracing"

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1842]
When there are failures in Travis, we see spurious diagnotics being reported along with actual failures

```
[ mi-aws/examples/serverless-raw ] Diagnostics:
[ mi-aws/examples/serverless-raw ]   pulumi:pulumi:Stack: serverless-p-it-travis-job-serverless-0ee6df00
[ mi-aws/examples/serverless-raw ]     info: flag provided but not defined: -tracing
[ mi-aws/examples/serverless-raw ]     Usage of tf-provider-flags:
[ mi-aws/examples/serverless-raw ]       -get-provider-info
[ mi-aws/examples/serverless-raw ]         	dump provider info as JSON to stdout
```

**Comment by metral** [comment]
I've been hitting this a fair amount this week in `pulumi/eks` and it's been making CI jobs harder to work with. Is there any update here @ellismg @lukehoban?

Retrying failed builds usually gets lucky and I can eventually produce a green build, but it's a become quite the nuisance, especially when it occurs in long running tests (e.g. `@pulumi/eks` is 55+ min now per run).

**Comment by lukehoban** [comment]
Looks like the issue here is one or both of:
1. We still have tracing turned on in many tests - like https://github.com/pulumi/examples/blob/master/misc/test/examples_test.go#L41 - even that that tracing endpoint no longer exists (so the data is not going anywhere).
2. When we have tracing turned on, the CLI unconditionally passes `--tracing` to all plugins.
3. The Terraform-based plugins added flag parsing code at some point to handle dumping their schema (for `tf2pulumi` purposes I think?), but this code doesn't handle `--tracing` - hence the error.

We could fix one or all of the above.  I suspect turning off (1) and fixing (3) to not warn would make sense.

**Comment by t0yv0** [comment]
https://github.com/pulumi/pulumi-terraform-bridge/pull/346 I believe addresses the root cause here. What remains is upgrading all terraform-based providers to the new version of pulumi-terraform-bridge.
