### ISSUE TITLE
Exporting entire resources as stack outputs leads to an odd experience

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1858]
From the community slack:

>ed: Surprising behavior: when I return an `aws.ec2.Vpc` object as an export, it turns into its VPC ID as a string. In Terraform or CloudFormation I would expect to get the ID back, but in Pulumi these are all objects that I'm dealing with. At minimum I would have expected it to turn into, say, `{ id: "vpc-xxx" }` - stripping out fields that the exporter doesn't know what to do with.
>
>matt: Just to confirm my understanding, ed, you are talking about when you export a VPC from your top level module (so it shows up as an output of your stack when you run `pulumi stack output`)? (edited)
>
>ed: matt Correct. It results in an export of `{ vpc: "vpc-xxx" }`, which is inconsistent with uses of `vpc` in the code itself. (Having to remember that _this_ `vpc` is a string is weird.)
My natural assumption would be more like `{ vpc: { id: "vpc-xxx" } }`, to match the pattern of accessing the object that I gave Pulumi to deal with.
(I realize this is a breaking change, but I find the cognitive load of having to remember things my typechecker can't to be frustrating.)

This may play into the larger item of having the tool understand `--format json`  and giving well structured json (the output today is line oriented and built around making it easy to glue things together using shell (e.g. `curl $(pulumi stack output url)`)

**Comment by eropple** [comment]
Cool, thanks for filing this.

I think it's pretty natural for something that's a _programming_ tool, like Pulumi, to treat objects as objects and to do useful stuff with them, as opposed to Terraform or CloudFormation where objects are inconvenient ways to block getting at those sweet, sweet strings that you _really_ want, so I'm excited to see what happens here.

**Comment by joeduffy** [comment]
I believe this is an unintentional consequence of the way our marshaling works. We must be marshaling these output properties like we would as input to a resource. I think this happens here

https://github.com/pulumi/pulumi/blob/9cb163f26b056661d6b379750a14ecb2bc2a6c40/sdk/nodejs/runtime/rpc.ts#L247-L255

We did that for perhaps misguided reasons. It allows resources to accept things like `string | SomeResource` as input properties, e.g. where you might want to pass a string-based ARN _or_ an actual reference to a resource object instance (as a "capability" of sorts).

Now, we can probably just fix this by not going down that shared pathway. But it's probably worth pondering briefly whether _that_ behavior is right/desirable/etc. also ...

**Comment by eropple** [comment]
I figured as much when I thought about it, but it's neat to have verification. ;)

The current behavior is certainly defensible. It just seems odd in a programming context to have to manually do something like `vpcId` over `vpc.id`. Like--I'm probably not just going to want the ID. I'm probably going to want the CIDR block any time I want to reference a VPC or a subnet or whatever, I'm probably going to want the AWS instance ID and its private IP address, etc.

**Comment by ellismg** [comment]
> Now, we can probably just fix this by not going down that shared pathway. But it's probably worth pondering briefly whether that behavior is right/desirable/etc. also ...

I wonder, @pgavlin, how would changes here impact that StackReference stuff? Presumably if we made a change such that when a resource is registered as a stack output instead of just doing the normal thing we did the "treat it as an object, and just serialize all properties and then pass that as a map" it would have some impact on importing these outputs.

The other thing that isn't clear to me right now is what would happen in the case where you have nested resources. For example, imagine you are exporting a custom resource that has an output property of another resource.  Does that get expanded recursively or do we just export id's in that case? Or is this a problem we do not face today.

It does seem a little weird that in the checkpoint we would have outputs of the root stack object be treated differently from outputs of other resources.  That makes me nervous because I think it's going to cause things to feel very weird as we try to compose more and more things.

For these sorts of things, I wonder if would instead make sense to have a some function that took a `resource<T>` and "de-resourceifyied" it by copying the object but, eliding the `__` properties that Pulumi adds to a resource.  You could then call that as part of exporting.

FWIW, I wrote the following short program (I'm sure there's something subtly wrong for my poor mans object copy thing, but it does show how you could get the behavior you want today with the existing system):

```typescript
import * as aws from "@pulumi/aws";

const b = new aws.s3.Bucket("my-bucket");
const o = {};

Object.keys(b).filter(x => !x.startsWith("__")).forEach(x => {
    (o as any)[x] = (b as any)[x];
});

export const bucketPulumi = b;
export const bucketPojo = o;
```

When run, `pulumi stack output --json` looks like this:

```
{
  "bucketPojo": {
    "accelerationStatus": "",
    "acl": "private",
    "arn": "arn:aws:s3:::my-bucket-1e9f1d9",
    "bucket": "my-bucket-1e9f1d9",
    "bucketDomainName": "my-bucket-1e9f1d9.s3.amazonaws.com",
    "bucketRegionalDomainName": "my-bucket-1e9f1d9.s3.amazonaws.com",
    "corsRules": [],
    "forceDestroy": false,
    "hostedZoneId": "Z3AQBSTGFYJSTF",
    "id": "my-bucket-1e9f1d9",
    "lifecycleRules": [],
    "loggings": [],
    "region": "us-east-1",
    "requestPayer": "BucketOwner",
    "tags": {},
    "urn": "urn:pulumi:tmp.6Vuuh0L3b4-dev::tmp.6Vuuh0L3b4::aws:s3/bucket:Bucket::my-bucket",
    "versioning": {
      "enabled": false,
      "mfaDelete": false
    }
  },
  "bucketPulumi": "my-bucket-1e9f1d9"
}
```

**Comment by lukehoban** [comment]
This is more important to nail down now that we have `StackReference`, as it will be more common to want to share whole resources across the boundary - and we'll want to have a natural model for how that works.

**Comment by ellismg** [comment]
After talking with @pgavlin we've decided that we'll update our logic for seralizing outputs when registering them to the top level stack object.  The plan is to serialize custom resources as POJO objects (after filtering out the `__pulumi` fields).  We will also ensure that assets and archives do not get the special map key that tells the engine that these objects are "special".

**Comment by ellismg** [comment]
@CyrusNajmabadi Do you think this is something you can handle?  I know that you've been touching the resource serialization code recently, and so I think your both best tasked to fix the issue or point out some deep flaw in our strategy of treating top level exports differently.

**Comment by CyrusNajmabadi** [comment]
It's something i can look at :)
