### ISSUE TITLE
Re-parenting a resource (probably?) shouldn't require destruction

### ISSUE THREAD

**Issue by eropple** [pulumi/pulumi#1877]
Situation: I created a DNS record via Route 53. For organization purposes, I then decided I wanted to make it a child of another resource for the sake of clarity. So I added `{ parent: p }` to my child record.

Pulumi ~has now hung  because it wants to create the new resource before destroying the old resource, which it can't do~ (edit: I was mistaken, it didn't hang, it just took forever for an operation that was still not necessary).

Not the worst thing in the world (do it in two steps!) but annoying. A fully logical (no change in inputs) re-parenting should probably just work.

**Comment by lukehoban** [comment]
This is something we definitely want to improve.  I believe this is the same as https://github.com/pulumi/pulumi/issues/837, which has some background on why this is currently necessary - I'll copy some of your repro case over there and close this one out.
