### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#1879]
One of my stacks got into some sort of corrupted state: whenever I run `pulumi update` if immediately throws

```
panic: send on closed channel

goroutine 30 [running]:
github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).runEngineAction.func1(0xc042578a80, 0xc0425789c0, 0xc04203392
0, 0xc042578ba0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:937 +0x13e
created by github.com/pulumi/pulumi/pkg/backend/cloud.(*cloudBackend).runEngineAction
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/backend/cloud/backend.go:931 +0x44d
```

The stack is called `func` under my account.

**Comment by lukehoban** [comment]
@mikhailshilkov Does this now repro consistently for you on this stack?  Are you able to work on other stacks still without issues?

**Comment by mikhailshilkov** [comment]
@lukehoban yes and yes

**Comment by swgillespie** [comment]
The only way I can imagine that this can happen is if the CLI panics. We close this channel in a `defer` so it's possible that we close the channel due to a panic while another goroutine is still writing events.

I think the fix is simple here - only close the events channel when terminating normally. When panicking we have no guarantees about the state of the system and we can't assume that e.g. channels will be still open.

**Comment by swgillespie** [comment]
@mikhailshilkov I suspect that your `func` stack may still hit a panic, even with the fix to this bug - please open an other issue if that's the case so we can get to the bottom of ut!

**Comment by mikhailshilkov** [comment]
@swgillespie Which bits do I need to wait to try that?

**Comment by swgillespie** [comment]
@mikhailshilkov You only need an updated CLI to try that - I believe that we will be publishing a new build of the Pulumi CLI very very soon, so you shouldn't have to wait long to try that. Until then, though, you can either build the CLI from source (you really only need to `go install github.com/pulumi/pulumi`) or you can download the pre-built binaries here: https://get.pulumi.com/releases/sdk/pulumi-v0.15.1-dev-1536210441-g30fccc07-windows-x64.zip.

(I'm assuming that you're on Windows given the `C:/` paths in your report, but if you need other OSes you can replace `windows` with `linux` or `darwin`.

**Comment by mikhailshilkov** [comment]
No panic with `0.15.2`. Just seems to work now.

**Comment by swgillespie** [comment]
Awesome! 😄
