### ISSUE TITLE
`refresh` swallows initialization errors

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#1881]
In the process of investigating https://github.com/pulumi/pulumi/issues/1790, I discovered that `refresh` has regressed to swallowing initialization errors. This is easy to reproduce:

1. Create a `Pod` with a bad image name.
1. crtl-c after getting a warning about the bad image name.
1. `refresh`, the error disappears.

We'll want to fix this ASAP, before the release later today. cc @pgavlin @swgillespie

**Comment by hausdorff** [comment]
I've also confirmed we are definitely returning the init error from the Kubernetes provider, so this is very probably a bug on the engine side.

**Comment by pgavlin** [comment]
Interesting. We have test coverage for this... any idea why this test isn't failing? https://github.com/pulumi/pulumi/blob/master/pkg/engine/lifecycle_test.go#L1121-L1212

**Comment by hausdorff** [comment]
@pgavlin the failure comes from https://github.com/pulumi/pulumi/commit/0634c1852ad4972872fd66cd966a12825e600557, specifically [this line](https://github.com/pulumi/pulumi/commit/0634c1852ad4972872fd66cd966a12825e600557#diff-674141a8d712fdb099f5fa5e79270d6cR610). I don't think I understand the rationale of this change?
