### ISSUE TITLE
computeCodePath won't find modules in an organization on Windows

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#1888]
Scenario: a serverless function using a handler with a reference to NPM module like `@azure/cosmos`. 

In order to upload the required NPM modules, `computeCodePath` function will be called which would print `Could not include required dependency '@azure/cosmos'`. The zip file won't contain this module.

OS: Windows

**Comment by lukehoban** [comment]
Fixed with #1889.
