### ISSUE TITLE
Need to audit CLI for color-preference conformance

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#1895]
Right now we have many places in the CLI where code just emits outputs with colors, or passes along color.Always (instead of actually passing along the user's preferred color output).  This means that a user with NO_COLOR set or a user that says --color=never will still end up with colored output.  We need to audit the code and have it all go through the core colorization helpers that respect user preferences.

Example issue: https://github.com/pulumi/pulumi/pull/1875/commits/95e917441aa01444792f87447b3171d3c97b150e#diff-d614fe049b3897db1de18e775226437dR77

**Comment by lukehoban** [comment]
Old issue with no more feedback - going to close out for now.
