### ISSUE TITLE
Enable Python analyzers

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#190]
Implementing an analyzer just entails implementing a gRPC interface, so it is entirely language agnostic.  There are some hoops you need to jump through, however, that we could eliminate with a small per-language library.  Particularly given that our goal is to get to "10 lines of Python" for a simple/basic analyzer, we should bite this off before we start writing too many of them.

**Comment by lukehoban** [comment]
This is now tracked in https://github.com/pulumi/pulumi-policy/issues/98.
