### ISSUE TITLE
ExpectRefreshChanges's default value of false changes is probably the wrong call

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#1900]
Basically any end to end test we have at high levels in our stack requires ExpectRefreshChanges to be set to true because some parts of the underlying resources do have diffs when we run `pulumi refresh` during the update lifecycle.

For example in aws-infra's cluster test, I see this:

```
[ ejs/aws-infra/examples/cluster ]  ~  aws:ec2:Eip infratest-net-nat-1 updated changes: ~ associationId,networkInterface,privateIp
```

I've also seen cases where every `aws:lambda:Function` has a property updated during `pulumi refresh`.

As we push 0.15.1-rc1 and friends up the stack, I'm having to explicitly opt all of these tests from refresh, and I'm going to tag them with this issue. I think we should invert the default and only opt in for cases where we know there aren't going to be any changes for the cloud provider.

**Comment by lukehoban** [comment]
We've already pushed this out to all repos, so let's just stick with current default (and thus absorbed the primary pain of the current default).  Let's keep this as is.
