### ISSUE TITLE
Question: Do you have (or planning to have) a unit testing framework?

### ISSUE THREAD

**Issue by pkleanthous** [pulumi/pulumi#1902]
Do you have (or planning to have) a unit testing framework?

**Comment by ellismg** [comment]
We don't presently have a unit testing framework.  For some of our high level cloud APIs we've experimented in the past with providing a local implementation, but we haven't tried to make any of these experiments real yet.

For cases where you want to test application logic (e.g. functions that back serverless APIs for example) It should be possible to use regular javascripting testing frameworks.  If you want to write unit tests where you spin up and down resources against some mock provider or the like, we don't have a great story there.

What sort of tests would you want to write and what would a great solution look like to you?

**Comment by joeduffy** [comment]
Note that we _do_ have our own internal integration test framework which could be used for this sort of thing, but it's quite low level and probably not what you're looking for. E.g., see

* The package itself https://github.com/pulumi/pulumi/tree/master/pkg/testing/integration
* A few example uses of it https://github.com/pulumi/pulumi-aws/blob/master/examples/examples_test.go

**Comment by pkleanthous** [comment]
Hi @ellismg & @joeduffy,

Thanks for your reply.

Ideally, I would like to have a similar eco-system like chef. ChefSpec is a unit testing framework for testing Chef cookbooks. 

Ideally, I would like to have a PulumiSpec framework where I can provide a mock state file (Representing imaginary infrastructure resources) and when I will run the unit tests it will generate a set of actions that Pulumi will execute (if it was running against a real public cloud) also it will give me the ability to check those actions.

**Comment by thefringeninja** [comment]
Something specifically I would like to be able to test: Given a certain stack that deploys to aws, all resources in that stack must have a tag `something` and each `something` tag must all have the same value. I can probably do this now by parsing the state file but I think a test helper would be much nicer here.

**Comment by wyardley** [comment]
I agree, having something similar to `rspec-puppet` etc. is one thing I would really love to see, and one thing I really feel is missing in most of the tools in this space. I'm most familiar with terraform, and I've found that the lack of something like this is a big deficit, especially as you do more complex things.

Of course, doing integration tests with real resources is important too (using a framework along the lines of https://github.com/jacoblearned/kitchen-pulumi is what I've usually done), but being able to quickly validate logic like "I expect this will create N resources of type X with value Y" is pretty important when using code to define resources.

**Comment by lukehoban** [comment]
There are two blogs on what's available here:
* https://www.pulumi.com/blog/unit-testing-infrastructure-in-nodejs-and-mocha/
* https://www.pulumi.com/blog/testing-your-infrastructure-as-code-with-pulumi/

**Comment by lukehoban** [comment]
Closing this out for now - as there are good answers available in the posts above.  We will continue to look at broadening the support for test scenarios.
