### ISSUE TITLE
Add a "power user" `state` command

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1909]
We'd like to minimize the situations in which a user needs to export a checkpoint file, manually patch it, and then re-import it. It's scary and very error prone. That said, we know there are situations that will keep arising where a advanced users will need to do so.

For example, I just double ^C'd and then needed to do the standard `pulumi stack export | pulumi stack import` dance simply to reset the invalid bit in the checkpoint.

@swgillespie had the idea of introducing a "power user" command, which I have taken to calling `pulumi state`. This would provide common operations in CLI form, like `pulumi state set-invalid false`.

It would be nice to put this in place and just add useful helpers over time as we encounter situations. Of course, anytime we do, we should question whether we can fix the problem in a way that won't lead to manual checkpoint editing, but assuming we cannot, `pulumi state` will often be better than the alternative.

A few specific variants of this command that have come up:
- [x] `pulumi state delete <resource>`
- [ ] `pulumi state set-invalid false`
- [x] `pulumi state unprotect <resource>`
- [ ] `pulumi state rename <resource> <newname>`

**Comment by swgillespie** [comment]
Going to close this issue as completed, since we've got the framework in place to add new target checkpoint edits when we find them necessary in the future. Opened https://github.com/pulumi/pulumi/issues/2060 to track `pulumi state rename`
