### ISSUE TITLE
Get lint clean

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#191]
We are running lint rules regularly as part of building and CI validation, however, we had to grandfather a large number of failures of the sort

    exported function Xyz should have comment or be unexported

As we ready our codebase for OSS, we'll want to address these.  Not just to get lint clean, but also because we will begin generating GoDocs and we want all public APIs to have documentation.

**Comment by lukehoban** [comment]
We are lint clean up to our current bar - and do not have current need to raise that bar significantly.
