### ISSUE TITLE
Add ability to export specific versions of a checkpoint

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#1910]
The service retains all historical copies of a stack's checkpoint file. We will eventually expose the concept of versions when we implement a `pulumi history` command (https://github.com/pulumi/pulumi/issues/636). We should also allow users to export specific checkpoint versions also.

**Comment by lukehoban** [comment]
@chrsmith Do we have a user-facing notion of "version" yet that we could/should use here?  (I don't see any notion like that exposed from the work in https://github.com/pulumi/pulumi/pull/2270).  Is this something we are still targeting to get done in M20?

**Comment by chrsmith** [comment]
Quick update here: the APIs necessary in the Pulumi Service have been deployed, so it's just a matter of updating the `pulumi` CLI to add the new verbs to call them.

**Comment by guitarrapc** [comment]
Is there any plan to add `download state` button from Pulumi Web's ACTIVITY view, as Terraform Cloud offers?

![image](https://user-images.githubusercontent.com/3856350/72454497-4fea4800-3804-11ea-8245-753b5c97f564.png)

Most cases I want export previous version's state is "some issue is already happen with state and want to revert back to specific checkpoint". 

So I will use `pulumi history` or go to Pulumi Web's ACTIVITY VIEW to determine which version should I retrieve.

**Comment by lukehoban** [comment]
@guitarrapc yes - this is a very good suggestion - we’ll look into exposing UI for this in the console as well.

**Comment by tedchangtr** [comment]
it would be nice to be able to retrieve versions based on tags.
