### ISSUE TITLE
`pulumi new` feedback

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1920]
A few things that might be nice improvements to the experience below:
* [ ] Color the default values for config differently - or perhaps avoid putting them inside `()`.  Right now they don't stand out as clearly being the default value.
* [ ] "This command will walk you through creating a new Pulumi project" - perhaps this should be expanded now that this command does so much more. Maybe even just change "creating" to "deploying" or "creating and deploying"?
* [ ] Feels like we could have some more vertical whitespace between steps of this process - with more description about what's going on.
* [ ] For "Installing dependencies..." might be nice if we printed "done." when it is done.
* [ ] After "project is ready to go" might be nice to have some vertical whitsepace and a note that we will now do an initial deployment.

![screen shot 2018-09-11 at 12 54 53 pm](https://user-images.githubusercontent.com/223467/45384113-ef207f00-b5c1-11e8-9670-fc49a36f78e1.png)

**Comment by justinvp** [comment]
A couple other items:

 - [ ] Per Luke, we should consider outputting more details on follow-up commands to run when an update fails. Right now, we don't guide users to running `pulumi up` after addressing the update failure.
 - [ ] From #1979, consider going back to just showing the `npm install` output. `npm` doesn't always return an error code when it runs into problems (instead, it prints warning messages).

**Comment by lukehoban** [comment]
This is on the critical path for many/most new users - probably worth taking a pass on improving here in M20.
