### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by franciscocpg** [pulumi/pulumi#1928]
I'd like to suggest an improvement in the README at [Getting Started](https://github.com/pulumi/pulumi#getting-started) section.

It would be to add info about how to install a specific version. Something like:
(...)
1. **Install**:

    To install the latest Pulumi release, run:

    ```bash
    $ curl -fsSL https://get.pulumi.com/ | sh
    ```

   Or to install a specific version, run:
   
    ```bash
    $ curl -fSL https://get.pulumi.com/ | sh -s -- --version x.x.x
    ```
(...)

If you agree it makes sense I can propose a PR for that.

**Comment by lukehoban** [comment]
Given that there are several different approaches that users may want to take to install now (brew, powershell, etc.) - we may actually just want to point to https://pulumi.io/quickstart/install.html here (perhaps a “for more installation options, see ...”), and then make sure to improve the docs linked to there to include this detail on installing a specific version.  

What do you think?

**Comment by franciscocpg** [comment]
hi @lukehoban 

> we may actually just want to point to https://pulumi.io/quickstart/install.html here (perhaps a “for more installation options, see ...”)

You mean something like this?
(...)
1. **Install**:

    To install the latest Pulumi release, run:

    ```bash
    $ curl -fsSL https://get.pulumi.com/ | sh
    ```

   For more installation options, see https://pulumi.io/quickstart/install.html.

(...)


> and then make sure to improve the docs linked to there to include this detail on installing a specific version.

You mean add instructions for downloading specific version to `curl`, `brew` and `powershell` methods? Or just `curl`?

**Comment by lukehoban** [comment]
> For more installation options, see https://pulumi.io/quickstart/install.html.

Yep!

> You mean add instructions for downloading specific version to curl, brew and powershell methods? Or just curl?

Just `curl` is probably fine.
