### ISSUE TITLE
Rethink the TS declarations for Resources and how they specify Inputs/Outputs

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#1929]
@pgavlin Had a very interesting idea which i think it worthwhile to investigate at some point.  The core of the idea is that at the JS/TS sdk layer, we would define very simple structural types to define all 
"lower-case" resource inputs and outputs.  A 'simple structural type' is one that only contains numbers, booleans, strings, and arrays/objects that themselves only contain simple-structural-types.  In other words, they would not contain complex stuff like Promises/Outputs and would just be POJOs.

These types would represent the simple shape for data that would be most natural for people to work with.

With these simple types we would then have three type-operators `ResourceInputs`, `ResourceOutputs` and `Unwrap` (note: we just added the latter with: https://github.com/pulumi/pulumi/pull/1915).  

`ResourceInputs` would be the type operator that took a simple type and made it into the rich 'Input' type we expect today.  In other words, it would transitively give you the similar type, where the types of properties and whatnot would become 'Input<T>'.  So, given a type like:

```{ A: { B: number, C: { D: string[] } } }```  it would give you back:

```{ A: Input<{ B: Input<number>, C: Input<{ D: Input<Input<string>[]> }> }>```

Of course, the newly updated `output` function and `Unwrap' on that would just produce the original simple type from that type.

This would ideally help with how we generate our APIs.  Features would now naturally look like this:

```ts
export interface CertificateArgs {
    readonly domainName: string;
    readonly subjectAlternativeNames?: string[];
    readonly tags?: Tags;
    readonly validationMethod: string;
}

export class Certificate extends pulumi.CustomResource {
    // outputs omitted for brevity.
    constructor(name: string, args: ResourceInputs<CertificateArgs>, opts?: pulumi.CustomResourceOptions)
}
```

`ResourceOutputs` would then be the appropriate type combinator that would take the state type and produce the final resource shape type.  i.e. given:

```{ A: { B: number, C: string }, D: boolean }```  it would give you back:

It would give you back:

```{ A: Output<{ B: number, C: string }>, D: Output<boolean> }```

Note that this is only one level of Outputting deep.  With this, you could then say:

```ts
export interface CertificateArgs {
    readonly domainName: string;
    readonly subjectAlternativeNames?: string[];
    readonly tags?: Tags;
    readonly validationMethod: string;
}

export interface CertifcateState extends CertificateArgs {
    readonly arn?: string;
    readonly domainValidationOptions?: { domainName?: string, resourceRecordName?: string, resourceRecordType?: string, resourceRecordValue?: string[];
    readonly validationEmails?: string[];
}

export class Certificate extends pulumi.CustomResource, implements ResourceOutputs<CertificateState> {
    // no need to write outputs again.  they're indicated by the "implements clause".
    constructor(name: string, args: ResourceInputs<CertificateArgs>, opts?: pulumi.CustomResourceOptions)
}
```

Note: appropriate names would be TBD.  But this would give us the following benefits:

1. Clear relationship between Args/State (based on the assumption that all Args are a subset of State).
2. Args/State are very simple types that are easy to understand and doc.
3. No need to restate resource outputs, as they should be inferrable from the simple type for 'State'.
4. No need to restate resource inputs.  They are inferrable from the simple type for 'Args'.
5. A somewhat magical programming model where it looks like we only take in something like `domainName: string`, but if you happen to pass an `Output<string>` or a `Promise<string>` "things just work (tm)".

Unlike the helper we have for 'output' which helps give you the 'simple structural form', we wouldn't need a helper function for the reverse direction.  That's because all `T`s are already `Input<T>`s to begin with :)  So if you have a simple instance with simple types, it's already a viable `ResourceInput`.

--

Pros are good.  Cons are harder to know without investigation here.  Potential cons are:
1. TS actually gets confused here and we lose typesafety somehow.
2. This ends up being a breaking change for some subtle reason i've missed because TS thinks types are not compatible.
3. Our types are less clear for people who get confused by these wrapper types.
4. Intellisense gets less clear because as you're dotting through things you're seeing these type-combinators potentially showing up.
5. Our codegen layer gets much simpler as we get rid of a bunch of ugly goop around writing out Inputs/Outputs when doing transformations.

Note: none of the above may actually be a problem in practice.  I'm just calling them out for potential things to look for if we do investigate this.

**Comment by CyrusNajmabadi** [comment]
Tagging @lukehoban @joeduffy @pgavlin

**Comment by lukehoban** [comment]
Just to make sure I understand - this doesn't actually change anything for users - right?  It just simplifies code generation somewhat?

**Comment by CyrusNajmabadi** [comment]
It changes things in terms of what they would see whne both looking at our d.ts files (and potentially what they see from intellisense).  It should *not* (AFAICT) actually change the shapes of these types.  My hope though woudl be that the shapes would be more understandable for those looking at our code/docs as they would effectively just have a single source of truth for things instead of getting triplicate state today where you have:

Args-Shape
State-Shape
Resource-Output-Shape

These are all closely related, but subtly different in ways that are important, but which i don't think need such generated complexity pushed right in the face of users. 

Thoughts?

**Comment by CyrusNajmabadi** [comment]
I've looked into this a bit more, and i think this is very promising.  First, this is related to the (Lifted-Outputs proposal)[https://github.com/pulumi/pulumi/pull/2353], but both are independent and can be implemented without the other.

The specific typings we would need are as follows:

```ts
type primitive = Function | string | number | boolean | undefined | null;
type SimpleInput<T> = T | Promise<T> | Output<T>;

type Input<T> =
    T extends boolean ? SimpleInput<boolean> :
    T extends primitive ? SimpleInput<T> :
    T extends Array<infer U> ? SimpleInput<ArrayOfInputs<U>> :
    T extends object ? SimpleInput<InputObject<T>> :
    never;

interface ArrayOfInputs<T> extends Array<Input<T>> { }
type InputObject<T> = {
    [P in keyof T]: Input<T[P]>;
}
```

With this, it's now possible for types to express these shapes *once*, and then allow people to just use the `Input` and `Output` types to express the types that can flow in, and the property types that have flown out.  

Importantly, this removes hte need for the 'Unwrap' type (though we would still keep it around in case it is referenced).  The pojo type is now always the 'unwrapped' type greatly simplifying things.

**Comment by CyrusNajmabadi** [comment]
As an example, here's how things would look in practice:

```ts
export interface CertificateArgs {
    readonly domainName: string;
    readonly subjectAlternativeNames?: string[];
    readonly tags?: Tags;
    readonly validationMethod: string;
}

export class Certificate extends pulumi.CustomResource {
    readonly domainName: Output<string>;
    readonly subjectAlternativeNames?: Output<string[]>;
    readonly tags?: Output<Tags>;
    readonly validationMethod: Output<string>;
    constructor(name: string, args: Input<CertificateArgs>, opts?: pulumi.CustomResourceOptions)
}
```

**Comment by CyrusNajmabadi** [comment]
Tagging @joeduffy @lukehoban @hausdorff @swgillespie .  I would really like to go ahead and try this as an experiment.  I would use feature branches as normal.  I think it would take a few days simply because of what is involved in changing the generators and then trying to flow downstream and iterate on things.

**Comment by CyrusNajmabadi** [comment]
PR to attempt this here: https://github.com/pulumi/pulumi/pull/2464

**Comment by lukehoban** [comment]
What are the downsides to this?  Would be good to enumerate them next to the benefits. 

The one (big) one that comes to mind is docs - the equivalent of https://pulumi.io/reference/pkg/nodejs/@pulumi/aws/acm/#CertificateArgs-certificateBody would not mention that it was an Input. It would be much harder for readers of the docs to understand what types were accepted/produced in various contexts.  I’ll admit this feels like a significant issue.  Thoughts on how to address/mitigate that?

Any other downsides to be aware of?

**Comment by CyrusNajmabadi** [comment]
I've given this some thought and i'm not actually that concerned about doc side of things.  I think it's much clearer TBH to just say "i take a string".  In practice, i do *not* think people will be strictly looking at the values they're passing in and explicitly saying to themselves "but i have an `Output<string>`... how did that go in there?"  Rather, they'll just have some resource, and will be able to pass natural bits of it naturally to other resources.

Some advanced users will def go dive in to figure out what's up, and we'll def need good docs explaining how this works.  But, by and large, i think they'll be ok with this.

**Comment by CyrusNajmabadi** [comment]
What it looks like at the aws level: https://github.com/pulumi/pulumi-aws

**Comment by CyrusNajmabadi** [comment]
I'm going to have to table this again.  I'm just running into too many problems in the TS typings where the language is just fighting me too much :-/

**Comment by CyrusNajmabadi** [comment]
Closing out for now.  Couldn't timebox this effectively and it def ran into challenges.
