### ISSUE TITLE
MySQL 5.7 innodb cluster deployment

### ISSUE THREAD

**Issue by pratibhadeepti** [pulumi/pulumi#1933]
Hi can we use pulumi to deploy MySQL 5.7 Innodb cluster as we can do via ansible if yes then how.

**Comment by lukehoban** [comment]
You can use Pulumi to deploy any VM or container image to any cloud platform.  You can get or produce MySQL 5.7 VM images for most platforms - for example https://aws.amazon.com/marketplace/pp/B01M2YQUML on AWS.  You can find examples of deploying VMs in github.com/pulumi/examples, such as https://github.com/pulumi/examples/tree/master/aws-js-webserver for AWS.

Feel free to follow up in [slack](https://slack.pulumi.io/) if you have further questions.

**Comment by pratibhadeepti** [comment]
If I want to deploy MySQL 5.7 Innodb cluster in openstack how can I do with
pulumi.

**Comment by lukehoban** [comment]
An example of spinning up an OpenStack VM is here: https://github.com/pulumi/pulumi-openstack/blob/master/examples/webserver/index.ts.  You will need to construct the appropriate VM images or provisioning scripts for MySQL 5.7.
