### ISSUE TITLE
warning: context canceled

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1939]
What does `warning: context canceled` mean, and how can we display something more useful instead?

![screen shot 2018-09-14 at 6 15 40 am](https://user-images.githubusercontent.com/223467/45552377-a3e6b600-b7e5-11e8-9317-cca0094959bd.png)

**Comment by swgillespie** [comment]
@lukehoban do you have a repro for this? I'm not sure where `context canceled` came from here.

**Comment by swgillespie** [comment]
I've tried and tried and I can't get this to repro.
