### ISSUE TITLE
Replacement not shown quite right during preview

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1942]
The replacements show as "delete original" in the status, but as "replace" in the summary.

```
     Type                                      Name                      Plan                Info
 *   pulumi:pulumi:Stack                       foobarbaz-foobarbaz-dev   no change
 ~   └─ cloud:http:API                         cakebot                   update              changes: ~ routes
 +      ├─ cloud:function:Function             cakebotf70564dc           create
 +      │  └─ aws:serverless:Function          cakebotf70564dc           create
 +      │     ├─ aws:iam:Role                  cakebotf70564dc           create
 +      │     ├─ aws:iam:RolePolicyAttachment  cakebotf70564dc-fd1a00e5  create
 +      │     ├─ aws:iam:RolePolicyAttachment  cakebotf70564dc-32be53a2  create
 +      │     └─ aws:lambda:Function           cakebotf70564dc           create
 ~      ├─ aws:apigateway:RestApi              cakebot                   update              changes: ~ body
 +-     ├─ aws:apigateway:Deployment           cakebot                   delete original     changes: ~ description,variables
 ~      ├─ aws:apigateway:Stage                cakebot                   update              changes: ~ deployment
 +-     ├─ aws:lambda:Permission               cakebot-90171252          delete original     changes: ~ sourceArn,statementId
 +      └─ aws:lambda:Permission               cakebot-f70564dc          create

info: 12 changes previewed:
    + 7 resources to create
    ~ 3 resources to update
    +-2 resources to replace
      9 resources unchanged
```

**Comment by swgillespie** [comment]
What do we want to print here? `delete original` gets shown because it's the last step in the way that we render three-step replacements now ("creating replacement", "replacing", "deleting original"). Should we revert back to "replaced" once the update/preview is complete? cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
@swgillespie There is a distinction between the 'in progress' and 'done' state for a resource.  So it's likely we're not properly respecting that 'done' state for a replaced resource *during planning*.  In a normal update this would go through "creating, replacing, deleting", and then should transition to "replaced".  During preview this should probably go through "create, replace, delete" then end with "replace".  Or, potentially, during preview we don't have any 'in prrogress' concept and we just show it as "replace".  The 'in progress' stuff is only really relevant when actually performing the update.

Let me know if you need more detials/info.

**Comment by swgillespie** [comment]
@CyrusNajmabadi got it, thanks!
