### ISSUE TITLE
computeCodePaths yields nested npm_modules folders and breaks serverless app

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#1950]
Repro steps:
1. Create a Pulumi app with any serverless package (I was doing Azure).
2. Install an npm package `@azure/serverless`, or directly its dependency `stream_http`.
3. Define a serverless function using the npm module.
4. Run `pulumi update`

Current result: the call to `computeCodePaths` will yield the following:
```
    node_modules\@azure\cosmos
...
    node_modules\stream-http
    node_modules\stream-http\node_modules\readable-stream
    node_modules\stream-http\node_modules\process-nextick-args
    node_modules\stream-http\node_modules\string_decoder
...
```

Note that it found sub-folder `npm_modules` inside that package. They probably shouldn't put it in the first place, but in this case Pulumi should not detect those as separate entries.

Currently, the resulting ZIP file will cotain duplicate entries for all files under sub-`npm_modules`: one from parent package, and one from child package. This e.g. kills the whole Azure Function App because they don't handle this situation gracefully, see https://github.com/Azure/azure-functions-host/issues/3421.

**Comment by CyrusNajmabadi** [comment]
@mikhailshilkov What versions of Pulumi are you on?  I fixed this issue back in: https://github.com/pulumi/pulumi/commit/bee8bb8a78f356c115763bdf0f23d2f83e8c2094

Basically, when we compute these paths we won't add a subpath if we're going to add a parent path.

> They probably shouldn't put it in the first place, 

We include the actual modules that were loaded by node by the app in question.  So, if these modules were actually used by code pulled in by a Lambda/FunctionApp, we need to include them so that the `require("...")` of them in the source code will work.

**Comment by mikhailshilkov** [comment]
Argh, ok. 
I had the issue quite some time ago, it took time to find the root cause. I can see that I used `0.15.0` then.
I updated to `0.15.3` and it seems to be working now.

**Comment by CyrusNajmabadi** [comment]
@mikhailshilkov I'm really sorry you ran into this.  I had to do the same investigation and head-banging to figure out what was breaking in azure as well.  I wish there had been a good way to have made you (and any of hte rest of the community) aware of this so you didn't fall into the same problem.

From your perspective, was there something i could have done that would have helped out here?  I'd be happy to try to change some of my dev practices in the future to help you avoid this sort of thing!

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi/commit/bee8bb8a78f356c115763bdf0f23d2f83e8c2094   Sorry for the pain!

**Comment by mikhailshilkov** [comment]
@CyrusNajmabadi I think it's just bad luck. I haven't even try to look the issue up because I had no idea where it was coming from, just Functions were crashing when I add `cosmos` package. I guess I should have created this github issue, but I wanted to get to the root cause and wasn't sure it was Pulumi's fault, not Azure.

**Comment by CyrusNajmabadi** [comment]
Gotcha!  The next time we run into something like this, i'll try to notify you.  It was such a PITA to figure out, and i'm sorry you had to go through it too!
