### ISSUE TITLE
Timeline for a 'pulumi new kubernetes-go' template?

### ISSUE THREAD

**Issue by omadawn** [pulumi/pulumi#1959]
Looking at Pulumi and excited that there may be some good alternative to managing kubernetes deployments. However I have no familiarity nor interest in JavaScript/TypeScript.

Hopefully there will be templates and examples on the way so that I can start experimenting.

**Comment by lukehoban** [comment]
Thanks @omadawn!

We’re tracking progress on Go support generally in https://github.com/pulumi/pulumi/issues/1614 and in Kubernetes specifically in https://github.com/pulumi/pulumi-kubernetes/issues/70.  Once we’ve addressed the second, we’ll make sure to add the templates as well.

**Comment by lukehoban** [comment]
Closing this out for now since we’ll take care of it with the linked issues.

**Comment by omadawn** [comment]
I'll subscribe to those for updates. Thanks.
