### ISSUE TITLE
Error when using NewFileArchive to create Lambda in Go

### ISSUE THREAD

**Issue by justone** [pulumi/pulumi#1962]
I'm trying to create a lambda with code that is in a local directory.  Here's a snippet:
```
        lambdaFunction, err := lambda.NewFunction(ctx, "slacker", &lambda.FunctionArgs{
            Runtime: "python3.6",
            Code: asset.NewAssetArchive(map[string]interface{}{
                ".": asset.NewFileArchive("./function.zip"),
            }),
            Timeout: 300,
            Handler: "function.lambda_handler",
            Role:    lambdaRole.Name(),
        })
```

When I run `pulumi up`, I get this error message:

```
Diagnostics:
  global: global
    error: expected an asset, but filename is not an asset
```

At @swgillespie's request, I changed line [103 of rpc.go](https://github.com/pulumi/pulumi/blob/abb0c2769baabf6648522ba235d4df73ac32ecaf/sdk/go/pulumi/rpc.go#L103) from:
```
rpcTokenSpecialSigKey: rpcTokenSpecialAssetSig,
```
to:
```
rpcTokenSpecialSigKey: rpcTokenSpecialArchiveSig,
```
and that got past the error message.

However, now I get this message:
```
error: Plan apply failed: creating urn:pulumi:billing-dev::billing::aws:lambda/function:Function::slacker: Error creating Lambda function: InvalidParameterValueException: Uploaded file must be a non-empty zip
```

I've tried both `asset.NewFileArchive("./function")` and `asset.NewFileArchive("./function.zip")`, and the error is the same.

Here's the files on the filesystem:
```
$ tree function
function
└── function.py

0 directories, 1 file
$ unzip -l function.zip
Archive:  function.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     2844  2018-09-20 08:56   function.py
---------                     -------
     2844                     1 file
```

I was able to work around this issue by uploading my code to S3 and using the `S3Bucket` and `S3Key` properties.

Any help would be greatly appreciated.  Thanks.

**Comment by swgillespie** [comment]
We should definitely fix `rpc.go`, that's 100% a bug. There's probably another bug lurking but using `rpcTokenSpecialAssetSig` to serialize an Archive is definitely a bug.

**Comment by swgillespie** [comment]
Go support is out of scope for M21.

**Comment by EvanBoyle** [comment]
We think this may have been fixed. I'll try to create a repro in M31 to verify.

**Comment by lukehoban** [comment]
Confirmed that this works.  There's an example now in the examples repo that does this:

https://github.com/pulumi/examples/blob/1e1720ff87f0cb85dbf12e0840c577953aa35e4a/aws-go-lambda/main.go#L46-L63
