### ISSUE TITLE
pulumi new results in obtuse error

### ISSUE THREAD

**Issue by kennyjwilli** [pulumi/pulumi#1979]
I ran the below command and received the error message below: 
```
pulumi new aws-typescript --dir infrastructure
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the default, and press <ENTER>.
Press ^C at any time to quit.
project name: (infrastructure) ComputeSoftware/infra         
project description: (A minimal AWS TypeScript Pulumi program) Compute Software's AWS infrastructure 
Created project 'ComputeSoftware/infra'.
stack name: (ComputeSoftware/infra-dev) 
Created stack 'ComputeSoftware/infra-dev'.
aws:region: The AWS region to deploy into: (us-east-1) us-west-2
Installing dependencies...
Your new project is configured and ready to go! 
Previewing update of stack 'ComputeSoftware/infra-dev'
     Type    Name    Status        Info
 *   global  global  unchanged     1 info message
 
Diagnostics:
  global: global
    info: error: It looks like the Pulumi SDK has not been installed. Have you run npm install or yarn install?
 
error: failed to load language plugin nodejs: could not read plugin [/home/kenny/.pulumi/bin/pulumi-language-nodejs] stdout: EOF
```

Usually the `pulumi new` command will run `npm install` but it appears `npm install` failed. My best guess is that Pulumi set the `name` in the `package.json` to `ComputeSoftware/infra` and NPM does not like project names that contain a `/`.

**Comment by lukehoban** [comment]
> My best guess is that Pulumi set the name in the package.json to ComputeSoftware/infra and NPM does not like project names that contain a /.

Yes - that looks likely.

> Usually the pulumi new command will run npm install but it appears npm install failed. 

If it failed, we should have reported that and failed the `pulumi new` operation instead of proceeding. We'll look into why that isn't happening here.

**Comment by joeduffy** [comment]
I'm surprised we allow project names with a `/` in them.

I also think we should just go back to showing the `npm install` output. I worried at the time that swallowing the stdout/stderr was going to cause troubles, and it appears to be doing so here. I also think that showing the output as the install happens is actually a desirable thing.

**Comment by lukehoban** [comment]
> I’m surprised we allow project names with a `/` in them. 

Indeed - we’ll need to see if that’s the root cause here - but either way it seems we should constrain these. We’ll likely still need to be careful about potentially illegal NPM packe names.

> I also think we should just go back to showing the npm install output.

I mean - the design was that we would show the output if there was an error - which is exactly the case here. So that makes the case that we have a bug here - not necessarily that that design was wrong.  But happy to just turn it back on by default and err on the side of being too verbose.

**Comment by kennyjwilli** [comment]
It appears the problem is with how NPM handles this. If the project name contains an invalid character, it logs a `npm WARN Invalid name:` message and proceeds to install dependencies as usual. Only the `node_modules` directory is not created and the command exits with status `0` -- no error is thrown.

**Comment by justinvp** [comment]
Thanks for letting us know about this, @kennyjwilli!

I opened https://github.com/pulumi/templates/pull/40 to workaround/sidestep this issue, and opened https://github.com/pulumi/pulumi/issues/1988 to track the more fundamental question around whether we want to allow `/` in project names.

I also added a task to #1920 to track going back to showing the `npm install` output.
