### ISSUE TITLE
Consider not allowing `/` in project names

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#1988]
We currently allow `/` in project names, which has caused issues when we update the project name in `package.json` because NPM doesn't support `/` in project names.

https://github.com/pulumi/pulumi/blob/431f5b345063c6cb1709cac022601631f59077fd/pkg/workspace/project.go#L60

https://github.com/pulumi/pulumi/blob/431f5b345063c6cb1709cac022601631f59077fd/pkg/tokens/names.go#L52-L53

https://github.com/pulumi/pulumi/blob/431f5b345063c6cb1709cac022601631f59077fd/pkg/tokens/names.go#L95-L108

We should re-evaluate what characters we want to allow for project names.

Note: Any changes in the CLI here should also be updated in the service to match, e.g. https://github.com/pulumi/pulumi-service/blob/d0d31ffb9bc5af6bd4f4eb79827461788feb4d24/cmd/console2/src/app/new/new.component.ts#L21-L23

**Comment by joeduffy** [comment]
@justinvp @lukehoban This would be a breaking change. But it feels like the right thing to do. Do we know how many projects would be affected by this change? Any other thoughts?

**Comment by chrsmith** [comment]
+1 to adding this restriction. Another reason to do so is that it would be much more difficult to correctly browse by project name in the service if "/" was a valid character.

Looking at the database, there are 8 stacks that have a slash in the project name. One appears to possibly be a test case of some kind :)

```
MySQL [pulumi]> SELECT DISTINCT value as project_name FROM Tags WHERE name = "pulumi:project" AND value LIKE '%/%';
+-----------------------------------------------------------+
| project_name                                              |
+-----------------------------------------------------------+
| ...
| a:name/with@extra.1-%chars:this`ls`}"?l#] here | or there |
| ...
+-----------------------------------------------------------+
8 rows in set (1.64 sec)
```
