### ISSUE TITLE
Publish an official Docker image with pulumi installed

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#1991]
We've heard of many users building this themselves for local development as well as for deployment automation.  It's worth having an official Docker image which follows best practices for installation and execution environment, makes it easy to login via `PULUMI_ACCESS_TOKEN`, etc.

**Comment by lukehoban** [comment]
We added this to the repo, but we have not published it yet.  Re-opening this to track publishing the image as part of our release process.

**Comment by joeduffy** [comment]
We will also need to reconcile this with the `pulumi/actions` image that we maintain. It is still slightly different due to the addition of tags and cloud-provider SDKs.

**Comment by joeduffy** [comment]
I noticed we haven't been updating `pulumi/pulumi` or `pulumi/actions` with any of our recent releases. @lukehoban @ellismg Can we be sure to begin doing this as part of the release process -- including writing down what that process is -- with the next SDK/CLI release?
