### ISSUE TITLE
"Outputs:" shows up many times

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2010]
Interspersed throughout the service log output, we often now see "Outputs:" showing up multiple times. See below for a screenshot. We changed the CLI logic for how and when these are displayed, so this either broke the behavior, or we had this bug previously and it was just less visible.

![image](https://user-images.githubusercontent.com/3953235/46375032-26290400-c647-11e8-9d42-8103c46124a6.png)

@CyrusNajmabadi I'm assigning to you for now, not because I believe you're at fault (I probably am), but because the way this code was previously actually confused me, and I think you know how it was meant to work...

**Comment by CyrusNajmabadi** [comment]
I have no idea how on earth that could happen :)  This is going to be fun to track down...

**Comment by joeduffy** [comment]
Possibly related to this, I don't see any "Diagnostics:" section at all in the console logs. I do see the error messages printed out, but without the `error:` prefix.

![image](https://user-images.githubusercontent.com/3953235/46429763-1dded080-c6fc-11e8-82c3-93fa382a80a3.png)
