### ISSUE TITLE
Saying `delete` for a read resource during destroy is scary

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2015]
I have a program which does `gcp.container.Cluster.get` to retrieve an existing cluster so that I can deploy new containers into it without having to provide a full `kubeconfig`.

When I go to `destroy` this stack - I see the following:

```
$ pulumi destroy
Previewing destroy of stack 'gke-20181002-dev'
Previewing changes:

     Type                            Name                           Plan       Info
 -   pulumi:pulumi:Stack             gke-20181002-gke-20181002-dev  delete
 -   ├─ kubernetes:core:Pod          nginx                          delete
 -   ├─ pulumi:providers:kubernetes  luke-cluster                   delete
 -   ├─ gcp:container:Cluster        luke-cluster                   delete
 -   └─ gcp:storage:Bucket           my-bucket                      delete

info: 5 changes previewed:
    - 5 resources to delete

Do you want to perform this destroy?
  yes
> no
  details
```

This is scary and a bit misleading.  It implies that we will delete the GKE Cluster.  But we will (I hope!) not actually delete it, just remove it from the checkpoint file.

Feels like we need to explain this more clearly.  In the context of a refresh, it is sensible to use `delete` to mean "remove from checkpoint".  But in the context of an update (or preview of an update), `delete` means something else.  We could consider `remove`, `forget`,etc.?  This is morally the opposite of `read` which shows up at the other end of this operation.

**Comment by pgavlin** [comment]
> We could consider `remove`, `forget`,etc.?

I personally prefer `remove` here. I was going to leave the same feedback on https://github.com/pulumi/pulumi/pull/2024 regarding `state delete`: because `delete` means something pretty specific and destructive in our system at large, I'd rather use `remove` for these sorts of operations.
