### ISSUE TITLE
Add JSON output to pulumi stack ls

### ISSUE THREAD

**Issue by kennyjwilli** [pulumi/pulumi#2018]
We are using Pulumi in automated workflows and would like to have a way to get structured output from `pulumi stack ls`. Currently we need to write a manual parser. I suggest adding the `--json` flag to this command: `pulumi stack ls --json`.

**Comment by lukehoban** [comment]
See also https://github.com/pulumi/pulumi/issues/496 which is the broader topic of supporting `—json` on all commands. But leaving this to track stack ls specifically as that is lower hanging fruit that we may be able to tackle sooner.

**Comment by geekflyer** [comment]
same here. I specifically need json putput for `pulumi stack ls --all` to find all stacks which match a certain name regex and then do some operations on them.
