### ISSUE TITLE
Unable to use vpc.id from aws.ec2.vpc object to find subnetIds.

### ISSUE THREAD

**Issue by IPyandy** [pulumi/pulumi#2022]
Please bear with me here, first attempt at using Pulumi and I may very well be doing something wrong. Also JS/TS, not my strong suit but easy to follow as most examples are in those languages.

I basically took the [aws-ts-eks](https://github.com/pulumi/examples/tree/master/aws-ts-eks) example and started modifying it. Only for the reason of learning how pulumi works and customizing the deployment.

Instead of using the abstracted aws-infra.Network() I am creating a vpc from scratch using the aws.ec2.Vpc methods. This part "seems" to work fine, no linter or compiler errors. I am also creating, for now, three subnets in three AWS availability zones. I will be adding more things such VPN gateways, different route tables. But this is as simple as it gets for now. I understand that if it actually builds, the cluster may not work as there's no nat gateway or internet gateway created yet. I just need to get past this hurdle.

I am having issues inside the eks.Cluster method getting a way to present the subnetIds from the created VPC.

## Code for VPC

```typescript
import * as aws from "@pulumi/aws";
import * as eks from "@pulumi/eks";

// Create a VPC for our cluster.
const vpc = new aws.ec2.Vpc("eks-vpc", {
  cidrBlock: "192.168.16.0/20",
  assignGeneratedIpv6CidrBlock: true,
  enableClassiclink: false,
  enableClassiclinkDnsSupport: false,
  instanceTenancy: "default"
});
```

The above seems to work, then I run and create the three (3) subnets

## Subnets Code

```typescript
const privSubnets = () => {
  const max: number = 3;
  const octetBase = 16;
  const azs = ["us-east-1f", "us-east-1e", "us-east-1d"];
  let subnet: aws.ec2.Subnet;
  const subnets: aws.ec2.Subnet[] = [];

  for (let index = 0; index < max; index++) {
    subnet = new aws.ec2.Subnet(`privSubnets-${index}`, {
      vpcId: vpc.id,
      cidrBlock: `192.168.${octetBase + index}.0/24`,
      mapPublicIpOnLaunch: false,
      assignIpv6AddressOnCreation: true,
      availabilityZone: azs[index]
    });
   subnets.push(subnet);
  }

  return subnets;
};
```

This part while not efficient (maybe) seems to also have no errors.

The issue is next when creating the EKS Cluster itself.

## Code for Cluster

```typescript
const cluster: eks.Cluster = new eks.Cluster("pulumi-eks", {
  vpcId: vpc.id,
  // TRIED ACCESSING THROUGH GETTER
   subnetIds: aws.ec2
     .getSubnetIds({ vpcId: vpc.id }) // vpc.id cannot be used
     .then((subnet: aws.ec2.GetSubnetIdsResult) => subnet.ids),
  // NO WORKIE
  instanceType: "t2.large",
  desiredCapacity: 3,
  minSize: 3,
  maxSize: 6,
  storageClasses: "gp2",
  deployDashboard: true
});
```

For this line `.getSubnetIds({vpcId: vpc.id})` I get this error `Type 'Output<string>' is not assignable to type 'string'.`.

I tried doing it differently by getting the VPC object with getVpc then accessing the subnet ids that way.

```typescript
// TRIED GETTING THE VPC THEN ACCESSING THAT WAY
// BUT USING vpc.id IS NOT VALID APPARENTLY
const subnetIds = aws.ec2
  .getVpc({ id: vpc.id }) // ERROR HERE
  .then((v) => v.id)
  .then((id) => aws.ec2.getSubnetIds({ vpcId: id }))
  .then((subnets) => subnets.ids);

const cluster: eks.Cluster = new eks.Cluster("pulumi-eks", {
  vpcId: vpc.id,
  subnetIds: subnetIds, // Does not work, above part never finishes
  instanceType: "t2.large",
  desiredCapacity: 2,
  minSize: 3,
  maxSize: 6,
  storageClasses: "gp2",
  deployDashboard: true
});
```
Same issue, where `id: vpc.id` is not assignable.

Then where I create the subnets, instead of returning an array of Subnets, it was modified to attempt and return the subnetIds directly for testing.

```typescript
const privSubnetIds = () => {
  const max: number = 3;
  const octetBase = 16;
  const azs = ["us-east-1f", "us-east-1e", "us-east-1d"];
  const subnetIds: string[] = [];

  for (let index = 0; index <= max; index++) {
    const subnet = new aws.ec2.Subnet(`privSubnets-${index}`, {
      vpcId: vpc.id,
      cidrBlock: `192.168.${octetBase + index}.0/24`,
      mapPublicIpOnLaunch: false,
      assignIpv6AddressOnCreation: true,
      availabilityZone: azs[index]
    });
    subnetIds.push(subnet.id); // ERROR HERE
  }

  return subnetIds;
};
```

This line `subnetIds.push(subnet.id)` has the same `.getSubnetIds({vpcId: vpc.id})` I get this error `Type 'Output<string>' is not assignable to type 'string'.`. error.

The funny part is I can use it all day long inside this piece because the input value is `pulumi.Input<string>` and not `string`.

```typescript
const cluster: eks.Cluster = new eks.Cluster("pulumi-eks", {
  vpcId: vpc.id, // THIS IS FINE
```

## THOUGHTS

Maybe the error is because those values don't actually exist yet? I'm coming from terraform where accessing such things would occur at runtime and any planning stages would just say "computed". Is there another way to do what I'm attempting? 

Hopefully, my attempt to explain the error is clear enough to understand.
[index.txt](https://github.com/pulumi/pulumi/files/2446441/index.txt)

**Comment by IPyandy** [comment]
So this version of the code here seems to work, ran and it's finishing up now.. I realized I had more "semantic" errors above but the core issue is still there. Except if `string[]` types changed to `any[]` would compile but fail at preview because values are undefined.

It would still be nice if we can use the `getXYZ` methods and have some kind of "computed" values for those that can't be present until deployment.

Below works and I can now start refactoring and adding functionality.

```typescript
import { ec2 } from "@pulumi/aws";
import * as eks from "@pulumi/eks";

// Create a VPC for our cluster.
const vpc = new ec2.Vpc("eks-vpc", {
  cidrBlock: "192.168.16.0/20",
  assignGeneratedIpv6CidrBlock: true,
  enableClassiclink: false,
  enableClassiclinkDnsSupport: false,
  instanceTenancy: "default",
  tags: {
    Name: "EKS-VPC",
    Env: "Dev"
  }
});

// VPC eports
export const vpcId = vpc.id;
export const vpcCidr = vpc.cidrBlock;

// Create subnets for our VPC (private and public if specified)
function createSubnets() {
  const max: number = 3;
  const octetBase = 16;
  const azs = ["us-east-1b", "us-east-1c", "us-east-1d"];
  const subnets: ec2.Subnet[] = [];

  for (let index = 0; index < max; index++) {
    const subnet = new ec2.Subnet(`privSubnets-${index}`, {
      vpcId: vpcId,
      cidrBlock: `192.168.${octetBase + index}.0/24`,
      mapPublicIpOnLaunch: false,
      availabilityZone: azs[index],
      tags: {
        Name: `eks-privSubnet-${index}`,
        Env: "Dev"
      }
    });
    subnets.push(subnet);
  }

  return subnets;
}

// Subnet exports
export const privSubnets = createSubnets();
export const id1 = privSubnets[0].id; // just testing

function getSubnetIds(subnets: ec2.Subnet[]) {
  const subnetIds: any[] = [];

  subnets.forEach((subnet) => {
    subnetIds.push(subnet.id);
  });

  return subnetIds;
}

export const privSubnetIds = getSubnetIds(privSubnets);

// Create the EKS cluster itseslf, including a "gp2"-backed StorageClass and
// a dpeloyment of the Kubernetes dashboard.
const cluster: eks.Cluster = new eks.Cluster("pulumi-eks", {
  vpcId: vpcId,
  subnetIds: privSubnetIds,
  instanceType: "t2.large",
  desiredCapacity: 3,
  minSize: 3,
  maxSize: 6,
  storageClasses: "gp2",
  deployDashboard: true
});

// Export the cluster's kubeconfisg.
export const kubeconfig: any = cluster.kubeconfig;
```

**Comment by lukehoban** [comment]
Hi @IPyandy - thanks for the detailed notes!

Re: this step:

```typescript
const cluster: eks.Cluster = new eks.Cluster("pulumi-eks", {
  vpcId: vpc.id,
  // TRIED ACCESSING THROUGH GETTER
   subnetIds: aws.ec2
     .getSubnetIds({ vpcId: vpc.id }) // vpc.id cannot be used
     .then((subnet: aws.ec2.GetSubnetIdsResult) => subnet.ids),
  // NO WORKIE
  instanceType: "t2.large",
  desiredCapacity: 3,
  minSize: 3,
  maxSize: 6,
  storageClasses: "gp2",
  deployDashboard: true
});
```

The error you are seeing is because inputs to `.getSubnetIds` cannot be `Output` values from resource creations.  Instead, you can do something like this:

```typescript
const cluster: eks.Cluster = new eks.Cluster("pulumi-eks", {
  vpcId: vpc.id,
   subnetIds: vpc.id.apply(vpcId => aws.ec2
     .getSubnetIds({ vpcId: vpcId }) // vpc.id cannot be used
     .then((subnet: aws.ec2.GetSubnetIdsResult) => subnet.ids)),
  instanceType: "t2.large",
  desiredCapacity: 3,
  minSize: 3,
  maxSize: 6,
  storageClasses: "gp2",
  deployDashboard: true
});
```

Using `.apply` means that the call to `getSubnetIds` will only occur after the VPC has been created and has an id assigned.

An alternate way to write the above is like below - which is a common pattern for this sort of thing:

```typescript
const cluster: eks.Cluster = new eks.Cluster("pulumi-eks", {
  vpcId: vpc.id,
   subnetIds: vpc.id.apply(getSubnetIds),
  instanceType: "t2.large",
  desiredCapacity: 3,
  minSize: 3,
  maxSize: 6,
  storageClasses: "gp2",
  deployDashboard: true
});

async function getSubnetIds(vpcId: string): string[] {
    const res = await aws.ec2.getSubnetIds({vpcId: vpcId});
    return res.ids;
}
```

**Comment by lukehoban** [comment]
I'll close this out for now because I think you have a couple approaches that will work - but feel free to follow up here or in slack with any other questions.

**Comment by IPyandy** [comment]
@lukehoban Thanks for the responses, they help a lot with this and other cases as I expand to add more resources.

Thanks again
