### ISSUE TITLE
Store secrets passed to the provider in encrypted form in the checkpoint

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#2034]
If you have stored provider configuration as a `--secret` in your `Pulumi.<stack-name>.yaml` file, we now store the configuration value (in plain text) in the checkpoint.  This is a change since we did the first class provider work.

We should probably retain the encrypted versions and just decrypt them when we load the checkpoint.

This will probably require some pluming to pass the fact that a value is "secret" across our RPC boundaries.

**Comment by joeduffy** [comment]
We will tackle this coincident with https://github.com/pulumi/pulumi/issues/397, which will let us persist `Secret<T>`s as ciphertext in the checkpoint file, to be decrypted lazily and on-demand upon use.

**Comment by lukehoban** [comment]
The solution we are working on for #397 will address this.  We'll track this as part of #397.
