### ISSUE TITLE
Diagnostics have gone missing from the console

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2038]
From https://github.com/pulumi/pulumi/issues/2010#issuecomment-426737592:

> Possibly related to this, I don't see any "Diagnostics:" section at all in the console logs. I do see the error messages printed out, but without the error: prefix.
>
> ![image](https://user-images.githubusercontent.com/3953235/46429763-1dded080-c6fc-11e8-82c3-93fa382a80a3.png)

I'm almost certain this is my fault, but thanks for looking into it @CyrusNajmabadi.

**Comment by CyrusNajmabadi** [comment]
agreed this is not a good situation.  not a regression however afaict.  And this should fall out as part of: https://github.com/pulumi/pulumi/issues/2038

**Comment by joeduffy** [comment]
@CyrusNajmabadi I think I now know what's been bugging me about this. Although errors are indeed printed in the log, simply not summarized at the end, they are lacking the standard `error:` and `warning:` prefixes. That makes it tough to eyeball and/or grep for what went wrong.

E.g., deployment in the CLI:

![image](https://user-images.githubusercontent.com/3953235/47271490-d8f5cf00-d52e-11e8-8c3a-6035153915bf.png)

Deployment on the web console:

![image](https://user-images.githubusercontent.com/3953235/47271494-e3b06400-d52e-11e8-9a2b-649222e8506e.png)

Is this easy enough to fix? And did this change at some point? I (perhaps mistakenly) recall that we used to see the `error:` prefix in bright red...

**Comment by CyrusNajmabadi** [comment]
> Is this easy enough to fix?

I don't think it would be tough to fix.  That said, i was also under the impression we were going to be reworking the CLI display on the website (i.e. to be richer, and more like the local CLI display where things are grouped/summarized accordingly).  If so, is there a lot of vlaue in investing in this log, if it's not going to be used that much?

**Comment by joeduffy** [comment]
We will be, however, we'll always have the raw log and I think making it greppable and easy to see errors/warnings is a thing we'll want forever -- and would provide practical benefit today, as we are several big rock features landing away from the improved view you mention. So, if it's a <30 minute fix, it's well worth it, IMHO.
