### ISSUE TITLE
Having to prepend org name to stack isn't discoverable

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#2046]
@CyrusNajmabadi [notes](
https://github.com/pulumi/pulumi-service/issues/2172#issuecomment-428708128):

> I'm not sure i like the CLI flow for making a stack where i have to know to prepend the org name before the stack name. It seems like our "pulumi new" flow could prompt for that sort of thing as it's walking through (with the default being to use the user's default stack).

**Comment by lukehoban** [comment]
Closing as a dupe of #2421 which has more details about how we might solve for this.
