### ISSUE TITLE
If a specific property-name is supplied in stack output it is not found

### ISSUE THREAD

**Issue by info4eco** [pulumi/pulumi#2053]
I haven't posted an issue before. But here goes. 

Setup:
Pulumi version v0.15.4

Issue description:
CLI command `pulumi stack output` provides a list of outputs all as expected, including for sake of this example one output called 'foo'
CLI command `pulumi stack output foo` throws an error, `error: current stack does not have output property 'foo'` 

This was working for me previously so that makes it more strange. Not sure if it's relevant but I'm setting the outputs using the python funtion: `pulumi.output('foo', bar)`.

**Comment by lukehoban** [comment]
@swgillespie Any idea how this could happen?

**Comment by swgillespie** [comment]
Nope, but I'll check it out.

**Comment by lukehoban** [comment]
I think this is resolved with the new Python3 support in `0.16.4`.  @info4eco please drop a note if you are still seeing problems here.
