### ISSUE TITLE
gcp default-pool can not be autoscaled via Pulumi

### ISSUE THREAD

**Issue by info4eco** [pulumi/pulumi#2054]
Set up:
GCP
Python
Pulumi v0.15.4 

Description:
I think this is similar to the issues that terraform had:
https://github.com/terraform-providers/terraform-provider-google/issues/473
https://github.com/terraform-providers/terraform-provider-google/issues/844

When I attempt to add autoscaling directly to a cluster Pulumi correctly (?) says `got an unexpected keyword argument 'autoscaling'`
When I try to apply autoscaling to a node-pool with the name 'default-pool' Pulumi also correctly (?) says `default-pool., alreadyExists`

So I think there needs to be another way to autoscale the default pool.

**Comment by geekflyer** [comment]
If you want to create a seperate pool with the name `default-pool` you have to set
`remove_default_node_pool=True`

**Comment by info4eco** [comment]
Ah I wasn't aware of that one. I tested it and it worked well. Thanks very much.

**Comment by Pithikos** [comment]
Does not work anymore as mentioned here: https://github.com/pulumi/pulumi/issues/12257
