### ISSUE TITLE
Multi-region stack support

### ISSUE THREAD

**Issue by davidk01** [pulumi/pulumi#2057]
Hey folks. Long time listener, first time caller. I really like that pulumi is bucking the trend and using a programming language instead of another external DSL for managing cloud resources.

Maybe I'm being a little too ambitious with how I'm trying to use pulumi but I wanted to set up a multi-region stack and couldn't figure out how to do it. More specifically, I was trying to create a multi-region VPC configuration like below

```ts
const regions = ['us-east-1', 'us-east-2', 'us-west-1', 'us-west-2']
regions.forReach((region) => {
  // VPC resource creation for each region
});
```

Unfortunately I couldn't get it to work. It seems like at any given time pulumi can only target one stack and region. Is this correct or is there some documentation I missed that would allow me to do what I want?

**Comment by lukehoban** [comment]
This is actually possible now using `new aws.Provider(...)` to create a new instance of the AWS provider targeting a different region. 

Check out https://github.com/pulumi/pulumi-aws/blob/master/examples/multiple-regions/index.ts for a complete example of multi-region with AWS.

**Comment by davidk01** [comment]
Awesome. Thanks for the pointer.

**Comment by rtorres280** [comment]
is it possible to deploy an api in one region with a lambda proxy integration tied to another region?
