### ISSUE TITLE
Bad error message when plugin is missing for first class provider

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#2067]
If the version we burn into the checkpoint for a provider is not present on the machine and no compatible version is present either, we fail with a horrible error message:

```
error: could not find plugin for provider 'urn:pulumi:my-test-project-dev::my-test-project::pulumi:providers:aws::default'
```

In this case, I hacked the inputs of the aws provider to look like this:

```
                "inputs": {
                    "region": "us-west-2",
                    "version": "0.16.1"
                },
```

Of course, 0.16.1 doesn't exist.

A customer came about this in a different way.  He was using a dev package and then later ran into this error.  He tried removing all his existing plugins and `node_modules` and reinstalling all packages at 0.16.0, but that didn't fix anything, since he had the -dev version burned into his checkpoint.

Explicitly installing that version via `pulumi plugin install resource aws ...` unblocked him, and then the next update correctly sets the provider version to the version corresponding to the `@pulumi/aws` package you have installed.

**Comment by pgavlin** [comment]
I believe that this is fixed as of #2078.
