### ISSUE TITLE
Add a `transform` escape hatch callback to Component options

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2068]
The Kubernetes provider exposes an optional `transform` callback on some components, which allows the set of resources managed by the component to be transformed by the caller before being created.  

This is a generally useful capability, to allow an escape hatch for cases where a component author did not expose a desired capability on some underlying resources it creates, but the caller wants to break the black box abstraction of the component and work around this at least until the component author exposes first class support.

This could be offered as a general feature for all Pulumi components by adding an `transform` callback on ComponentResourceOptions that gets a chance to modify the resource inputs of any resource prior to them being sent to the Pulumi engine.  As we do elsewhere, all parents up the parent chain would be consulted, potentially doing transformations at each layer up the hierarchy.   The caller would need to switch on `type` and potentially `name` to try to find the child resource they care about - which would be brittle when there are changes in the component, but not too much so given this would be intentionally breaking the black box abstraction.  This may require resolving the inputs to ground values (not Outputs) prior to handing them to the callback, so the callback would receive `Unwrap<Args>` instead of  `Args` as a parameter (though it could not be strongly typed in general since the callback would need to handle all child resources).

**Comment by gitfool** [comment]
I keep coming across reasons that this is a must have; the latest being using this to re-parent Kubernetes resources generated by [yaml.ConfigFile](https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/yaml/yaml.ts#L2375). (The existing "text templating" transform doesn't really help here.)

For that use case, and maybe for others, a transform callback that only sees a single object at a time is less than ideal and probably insufficient if you're then dependent on callback ordering for cross object manipulation. I think we also need another top-level transform callback to handle this.

**Comment by lukehoban** [comment]
> I think we also need another top-level "last chance" transform callback to handle this, where the callback is passed all objects.

Unfortunately, with the current execution model Pulumi uses, this is not possible - resources are dispatched to the engine for create/update/replace as they become ready. 

That said, I do expect there are ways we can still address the uses case (though possibly requiring slightly more bookkeeping by users). I’ll keep this scenario in mind as we flesh out the design in #3174.
