### ISSUE TITLE
Weird experience when checkpoint fails validation

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#2076]
Unfortunately, we don't have a great repo here, so I'm just capturing some notes on what a user reported.

The customer ended up in state where his checkpoint was invalid (it contained a reference to a parent resource that didn't exist).  At that point, stuff started behaving super strangely:

When trying to do an update, we got this error:

`
error: failed to load language plugin nodejs: failed to perform plugin load callback: failed to verify snapshot: child resource urn:pulumi:containers-dev::containers::standard:Deploy$kubernetes:apps/v1:StatefulSet$kubernetes:core/v1:Service::eth refers to missing parent urn:pulumi:containers-dev::containers::standard:Deploy$kubernetes:apps/v1:StatefulSet::eth
`

However, when trying to do a `refresh` or a `destroy`, instead we got this error:

`
error: could not find plugin for provider 'urn:pulumi:containers-dev::containers::pulumi:providers:kubernetes::default'
`

The above error looks similar to what we saw in #2067, but in this case, the root cause doesn't appear to the the same.  The version listed as an input the provider was correct.

In this case, the customer manually patched the checkpoint by exporting it, removing the reference to the missing resource and then imported it.  At that point, things worked as expected again.

The fact that the errors here are different makes some amount of sense, since both `destroy` and `refresh` don't actually have to run the language host at all.  Perhaps we are masking the verification error by not doing an errors.Wrap or something?

**Comment by pgavlin** [comment]
I believe that this is fixed as of #2078.
