### ISSUE TITLE
Unable to Run Sharp in AWS Lambda

### ISSUE THREAD

**Issue by WonderPanda** [pulumi/pulumi#2077]
I've been trying for a while now to get a Lambda deployed using Pulumi that packages and uses the Sharp library for serverless image processing. I've followed the [installation instructions from Sharp](http://sharp.pixelplumbing.com/en/stable/install/#aws-lambda) to build the Sharp module for the Lambda environment but no matter what I do I get the following message in CloudWatch Logs when the Lambda tries to run:

```
module initialization error: Error
at Object.Module._extensions..node (module.js:681:18)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:10:15)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
```
[I created a repo that reproduces this issue](https://github.com/WonderPanda/pulumi-aws-sharp) I would love to be able to use this feature with Pulumi so if anything seems out of place or if there's an opportunity to fix something up with a PR please let me know and I can try and tackle it. Just not really sure where to begin at the moment

**Comment by joeduffy** [comment]
@CyrusNajmabadi Do you mind taking a look at this?

**Comment by CyrusNajmabadi** [comment]
Looking now.

**Comment by CyrusNajmabadi** [comment]
Note.  typescript immediately didn't like this code:

```ts
import express from 'express';
import sharp from 'sharp';
```

Due to neither of those packages having default exports.  I updated my version to be:

```ts
import * as express from 'express';
import * as sharp from 'sharp';
```

**Comment by CyrusNajmabadi** [comment]
So i repro this as well.  The line in question it is complaining about is:
`const sharp = require('../build/Release/sharp.node');`

This appears to be a native module which doesn't work well in AWS.  I did find these instructions for sharp+aws.  investigating more: https://github.com/lovell/sharp/blob/master/docs/install.md#aws-lambda

**Comment by WonderPanda** [comment]
Hey @CyrusNajmabadi  thanks a lot for taking a look at this! Are you getting those Typescript errors in  the repo that I linked? My `tsconfig.json` is set up with `esModuleInterop` turned on which is why it should be fine to import them like that. I've used that approach on a number of projects before.

The `package.json` is also already set up with a script called `build-lambda` that uses the docker installation technique mentioned in the sharp AWS Lambda docs.

```
"scripts": {
        "build-lambda": "rm -rf node_modules/sharp && docker run -v $PWD:/var/task lambci/lambda:build-nodejs8.10 npm install"
    },
```
Even when building using the lambda:build image I run into issues :(

**Comment by ellismg** [comment]
I looked into this and I understand what is going on.  There's a poor interaction between how we build the zip file that we upload to lambda and sharp's (correct) use of symlinks for the native libraries that it vendors in as part of it's install process.

@WonderPanda after running your `build-lambda` command, I believe you'll end up with a bunch of files in: `node_modules/sharp/vendor/lib` many of which are symlinks.

```
[matell@matell pulumi-aws-sharp]$ ls -l node_modules/sharp/vendor/lib
...snip...
lrwxrwxrwx. 1 matell matell      21 Oct 19 15:16 libvips-cpp.so -> libvips-cpp.so.42.9.0
lrwxrwxrwx. 1 matell matell      21 Oct 19 15:16 libvips-cpp.so.42 -> libvips-cpp.so.42.9.0
-rwxr-xr-x. 1 matell matell  185632 Sep 19 07:57 libvips-cpp.so.42.9.0
lrwxrwxrwx. 1 matell matell      17 Oct 19 15:16 libvips.so -> libvips.so.42.9.0
lrwxrwxrwx. 1 matell matell      17 Oct 19 15:16 libvips.so.42 -> libvips.so.42.9.0
-rwxr-xr-x. 1 matell matell 2512072 Sep 19 07:57 libvips.so.42.9.0
...snip...
[matell@matell pulumi-aws-sharp]$ 
```

When we actually produce the deployment package, we are not including these symlinks.  I verified this by downloading the code for my copy of the lambda function using the AWS SDK.

```
[matell@matell pulumi-aws-sharp]$ curl -o code.zip $(aws lambda get-function --function-name sharp-test-06463e5 | jq -r .Code.Location)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.1M  100 11.1M    0     0  9383k      0  0:00:01  0:00:01 --:--:-- 9390k
[matell@matell pulumi-aws-sharp]$ unzip -l code.zip | grep '\.so'
  1064376  01-01-1990 00:00   node_modules/sharp/vendor/lib/libcairo.so.2.11512.0
   246576  01-01-1990 00:00   node_modules/sharp/vendor/lib/libcroco-0.6.so.3.0.1
   288432  01-01-1990 00:00   node_modules/sharp/vendor/lib/libexif.so.12.3.3
   198874  01-01-1990 00:00   node_modules/sharp/vendor/lib/libexpat.so.1.6.8
    32032  01-01-1990 00:00   node_modules/sharp/vendor/lib/libffi.so.6.0.4
   315712  01-01-1990 00:00   node_modules/sharp/vendor/lib/libfontconfig.so.1.10.1
   837891  01-01-1990 00:00   node_modules/sharp/vendor/lib/libfreetype.so.6.16.1
   113936  01-01-1990 00:00   node_modules/sharp/vendor/lib/libfribidi.so.0.4.0
   179504  01-01-1990 00:00   node_modules/sharp/vendor/lib/libgdk_pixbuf-2.0.so.0.3612.0
    37736  01-01-1990 00:00   node_modules/sharp/vendor/lib/libgif.so.7.0.0
  1796752  01-01-1990 00:00   node_modules/sharp/vendor/lib/libgio-2.0.so.0.5600.1
  1525608  01-01-1990 00:00   node_modules/sharp/vendor/lib/libglib-2.0.so.0.5600.1
    12608  01-01-1990 00:00   node_modules/sharp/vendor/lib/libgmodule-2.0.so.0.5600.1
   337816  01-01-1990 00:00   node_modules/sharp/vendor/lib/libgobject-2.0.so.0.5600.1
   296760  01-01-1990 00:00   node_modules/sharp/vendor/lib/libgsf-1.so.114.0.44
     5168  01-01-1990 00:00   node_modules/sharp/vendor/lib/libgthread-2.0.so.0.5600.1
    95152  01-01-1990 00:00   node_modules/sharp/vendor/lib/libharfbuzz-subset.so.0.10800.7
   799880  01-01-1990 00:00   node_modules/sharp/vendor/lib/libharfbuzz.so.0.10800.7
   509040  01-01-1990 00:00   node_modules/sharp/vendor/lib/libjpeg.so.8.1.2
   424304  01-01-1990 00:00   node_modules/sharp/vendor/lib/liblcms2.so.2.0.8
   619632  01-01-1990 00:00   node_modules/sharp/vendor/lib/liborc-0.4.so.0.28.0
   302224  01-01-1990 00:00   node_modules/sharp/vendor/lib/libpango-1.0.so.0.4200.3
    57600  01-01-1990 00:00   node_modules/sharp/vendor/lib/libpangocairo-1.0.so.0.4200.3
    90952  01-01-1990 00:00   node_modules/sharp/vendor/lib/libpangoft2-1.0.so.0.4200.3
   779536  01-01-1990 00:00   node_modules/sharp/vendor/lib/libpixman-1.so.0.34.0
   235304  01-01-1990 00:00   node_modules/sharp/vendor/lib/libpng16.so.16.34.0
  3162520  01-01-1990 00:00   node_modules/sharp/vendor/lib/librsvg-2.so.2.43.4
   484776  01-01-1990 00:00   node_modules/sharp/vendor/lib/libtiff.so.5.3.0
   185632  01-01-1990 00:00   node_modules/sharp/vendor/lib/libvips-cpp.so.42.9.0
  2512072  01-01-1990 00:00   node_modules/sharp/vendor/lib/libvips.so.42.9.0
   618848  01-01-1990 00:00   node_modules/sharp/vendor/lib/libwebp.so.7.0.2
    17808  01-01-1990 00:00   node_modules/sharp/vendor/lib/libwebpdemux.so.2.0.4
    46504  01-01-1990 00:00   node_modules/sharp/vendor/lib/libwebpmux.so.3.0.2
   954912  01-01-1990 00:00   node_modules/sharp/vendor/lib/libxml2.so.2.9.8
   110543  01-01-1990 00:00   node_modules/sharp/vendor/lib/libz.so.1.2.11
[matell@matell pulumi-aws-sharp]$ 
```

Because the symlink'd versions don't exist in the deployment package, the loader is unable to resolve the imports from the native module and we fail to load it.

You can work around this issue by taking these symlinks and turning them into real files (you may need to chown this folder first, the docker thing above may have it owned by root or some other user):

```
[matell@matell pulumi-aws-sharp]$ cd node_modules/sharp/vendor/lib
/home/matell/tmp/pulumi-aws-sharp/node_modules/sharp/vendor/lib
[matell@matell lib]$ for f in $(find -type l); do cp --force --remove-destination $(readlink $f) $f; done
```

After doing this, I did a `pulumi update` which took longer because we now upload 3x as much data, but the resulting program worked.

We should be able to do better here, but this will unblock you (even if development will be a little more painful because of the slower turn around time).

**Comment by ellismg** [comment]
BTW, @WonderPanda thank you **so much** for the wonderful test case repository, made it so much easier to investigate this!

**Comment by ellismg** [comment]
This code is problematic:

https://github.com/pulumi/pulumi/blob/2ec066261bebff22d1091ec12eb8bb475cf93737/pkg/resource/asset.go#L794-L797

But I think we need to thing about if we remove this check the downstream impact in our assets system.

**Comment by WonderPanda** [comment]
@ellismg Thank you for helping to diagnose this plus all the detailed information! Really appreciate seeing how you went about diagnosing the problem as well.
I'm definitely happy just to be unblocked and able to start playing around with some ideas for image processing apps deployed through Pulumi
