### ISSUE TITLE
Make sure everything builds on Windows

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#208]
At the moment, we have some issues preventing use of Pulumi on Windows.  I'm sure there are many little issues, however here are the ones I know about:

* We have some newline confusion
* We may not use virtualized path separator in all places, and assume it is `/`
* The gnarliest of all, we use `make` for builds almost everywhere, and assume the existence of several standard GNU tools (`sed`, `bash` built-ins, etc)

We definitely want to enable Windows for our own development purposes, in addition to our customers.

**Comment by chrsmith** [comment]
We are now building/running/testing on Windows for quite some time.
