### ISSUE TITLE
Commit titles are sometimes missing

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2080]
It appears we're still not always getting commit messages.

I don't grok entirely why we can't just fetch the commit message when there's a detached HEAD. There still should be commit metadata. I'd prefer just doing that, if we can, to scraping CI envvars.

**Comment by chrsmith** [comment]
https://github.com/pulumi/pulumi/pull/2069 (which was submitted after we snapped v0.16.0) fixed an issue where if the commit message was prefixed with a `\n` we would consider it as having "" for a title. Perhaps that could be the behavior you are seeing?

With a link to an update on the Pulumi service I could investigate further.

**Comment by chrsmith** [comment]
Without a repro I assume this was just fixed in the linked PR.
