### ISSUE TITLE
Add the GitHub PR repo slug and PR number env tag

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#2081]
The Pulumi Service can provide a link to any pull request associated with the commit that is being deployed, we just need to add the relevant data. (Similar to how if the `origin` remote is a GitHub repo, we add `github.repo`.)

Today we do this automatically for deployments made from repos that have the [Pulumi GitHub App](https://github.com/apps/pulumi) installed. But providing links to pull requests when applicable shouldn't require installing the GitHub app. (And by providing the data from the CLI, we can support linking to other source hosting systems as well.)

Note: We should _not_ take a fix for this in 16.1, and instead start doing this in 16.2.

**Comment by chrsmith** [comment]
Parking this with you @praneetloke , since you own many of the "CI/CD Fundamentals" issues for the current milestone.

**Comment by chrsmith** [comment]
Moving out of M0.23 to just increase focus/have more realistic set of open issues.

**Comment by lukehoban** [comment]
@praneetloke did some work related to this recently.  What is remaining here?

**Comment by praneetloke** [comment]
Yes, I believe this can be closed. The `ci.pr.number` tag was introduced quite a while ago, along with detecting the PR number for a few supported CI systems. As for the repo slug, we have the `vcs.*` properties that have existed for quite a while as well.
