### ISSUE TITLE
Add ability to specify full config file path via CLI / better support for ephemeral environments

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi#2083]
Currently pulumi requires practically for each stack a seperate config file that is named `Pulumi.<stack>.yaml`.

Besides having permanent environments like dev, staging and prod, I'm trying to use pulumi to spin up `0..n` "ephemeral" environments which can be used for a variety of purposes. For example they can be owned by an individual developer to test some code in integration or to run create a preview / integration environment for each pull request on specific repositories.

In order for ephemeral environments to work It'd like to have a generic pulumi config file that can be shared across all those ephemeral environments. I explicitly want to avoid creating and / or committing a new config file for each ephemeral environment / stack.

There's a few ways to achieve this.

1. The obvious one would be to add the ability to pass an explicit path to a config file via the CLI.
In this case I could just run `pulumi up --config-file ./config/Pulumi.ephemeral.yaml -s ephemeral-stack-1` , `pulumi up --config-file ./config/Pulumi.ephemeral.yaml -s ephemeral-stack-2` etc. .

2. Another possibility would be if #2059 is resolved it means I technically don't need a config file at all anymore. I could just the params that are specific to ephemeral stacks in code and I could determine if something is an ephemeral stack by a naming convention of the stack name (i.e. my logic could check if the stack name ends with ephemeral).

Currently there seems to be no way to override the config file location via the CLI.
The only possibility is to override config values is currently via `pulumi up -c myConfigKey=foo` which surprisingly is only available as CLI param for `pulumi up` but not for `pulumi preview` (bug?).

Would love if pulumi gets better support for ephemeral environment creation.

Related issue #1583 is an improvement but also not really what I want, because it'd like avoid creating new config file in the first place.

**Comment by smktpd** [comment]
Why was this ticket closed as completed?
Pulumi currently seems to be opinionated about the locations of the files like Pulumi.yaml and of stack settings files `Pulumi.${stack}.yaml`.
It would be nice to have a CLI option to specify path to stack settings file. Or at very least make Pulumi try to locate it in current work dir and then recursively try parental dirs if it was not found.
