### ISSUE TITLE
Support something more arbitrary than GH in `pulumi new`

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#2086]
This is feedback we get pretty often. Some options:

* Any git/mercurial URL
* Some subset of popular vendors (BitBucket, GL, GH Enterprise, and so on)

**Comment by justinvp** [comment]
Note that the CLI already works with public GitLab and BitBucket repos (and probably other hosted `git` repos):

```bash
pulumi new https://gitlab.com/<user>/<repo>
pulumi new https://bitbucket.org/<user>/<repo>
```

From a branch:

```bash
pulumi new https://gitlab.com/<user>/<repo>/tree/<branch>
pulumi new https://bitbucket.org/<user>/<repo>/tree/<branch>
```

It'd be good to document this.
