### ISSUE TITLE
Add CI vars from other CI systems

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi#2106]
Today the CLI detects CI vars for Travis and GitLab. This info is then used to enrich the experience for users in the web console UI. We should add support for detecting vars in other popular CI/CD systems as well. These are the systems so far that I have found with clear documentation about the environment variables injected into the build pipeline.

- [x] [Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=vsts) - PR #2705.
- [x] [Bitbucket Pipelines](https://confluence.atlassian.com/bitbucket/environment-variables-794502608.html) - PR #2783.
- [x] [Circle CI](https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables)
- [x] [Jenkins](https://wiki.jenkins.io/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-belowJenkinsSetEnvironmentVariables) - PR #3039.
- [ ] TeamCity
- [ ] Atlassian Bamboo
- [ ] Others...

**Comment by praneetloke** [comment]
Environment vars for Azure DevOps and Atlassian's Bitbucket Pipelines were added in M23. I'll bump this to the next milestone to see if we can some more then.

**Comment by praneetloke** [comment]
Moving this out of M26. I just added Jenkins env var detection.

**Comment by stack72** [comment]
Hi @praneetloke 

Is this still required?

P.

**Comment by praneetloke** [comment]
@stack72 I don't think so. I'll close this out.
