### ISSUE TITLE
Finish the GitHub resource provider

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#211]
As part of #134, we will need a GitHub resource provider, so we can subscribe to events.

**Comment by boillodmanuel** [comment]
Hello, the repo is gone? Do you have any update about the github provider?

**Comment by justinvp** [comment]
@stack72, is there anything left to do to make the GitHub provider repo public? I know it had atrophied a bit and you had started getting it back into shape several months ago.
