### ISSUE TITLE
Add Postgres Provider

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi#2141]
Would be awesome if you could add a postgres provider. There's already a terraform provider which does that: https://www.terraform.io/docs/providers/postgresql/index.html .

**Comment by jimmydivvy** [comment]
I prototyped an implementation of this a while ago: https://github.com/jimmydivvy/pulumi-postgres

This was just an experiment to get familiar with Pulumi and I haven't used it in production. But if someone would like to use this as a basis for a properly maintained version it's a starting point.

**Comment by ziahamza** [comment]
An updated version is published here: https://github.com/murcul/pulumi-postgresql
With NPM module published at: https://www.npmjs.com/package/@murcul/pulumi-postgresql

Would be polishing it further and should hit production very soon!

**Comment by pgavlin** [comment]
cc @stack72

**Comment by stack72** [comment]
This provider is already created and released!
