### ISSUE TITLE
Expose metadata tags to CLI/programs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2144]
Particularly with https://github.com/pulumi/pulumi/issues/109, it would be good to expose the ability to tag stacks and permit querying based on those tags. It turns out we already have this capability and use it for project, repo, and CI metadata, but we simply don't expose it. We should, both in the CLI and possibly even programmatically from inside of a Pulumi program.

**Comment by joeduffy** [comment]
This also applies to updates.

This would be very helpful for, say, rolling back to LKG, etc. as part ohttps://github.com/pulumi/pulumi/issues/96.

**Comment by joeduffy** [comment]
@justinvp We just discussed this as one possible approach to taming the "multi-stack" complexity issues, especially for organizing things in the service.

The scenario we discussed was letting a developer tag their stacks with `environment=production | staging | testing`, and then elect to group their stacks by this tag in the service UI, as an alternative view to grouping by project. We could also offer some nice filtering capabilities.

You also brought up some good scenarios around querying tags across stacks and projects.

**Comment by justinvp** [comment]
The most important part of this was adding the CLI commands for managing stack tags, which was done in #2333. There is some remaining work items that we should consider, but I don't think it's P1. Leaving this issue open to track the remaining follow-up but removing P1.

 - [ ] Expose stack tags to Pulumi programs
 - [ ] Persist stack tags in the local backend

**Comment by justinvp** [comment]
I'm going to go ahead and close this as the management side of the feature is complete. As we finalize our direction with config all-up, we can revisit as needed (and revive the PR that exposes the metadata to Pulumi programs as needed).
