### ISSUE TITLE
don't fail `npm install`ing pulumi packages when pulumi CLI is not installed

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi#2155]
Please don't fail npm install'ing pulumi packages when the pulumi CLI is not installed.
Instead just print a warning.

Context: https://pulumi-community.slack.com/archives/C84L4E3N1/p1541223226367000

This is also generally a problem in some other contexts. For example many nodejs programs will have different entry points who don't run or use any pulumi code, i.e. `npm run test`, start the application locally etc.  When putting pulumi packages in the same package.json as the application dependencies it implies everyone (even some team member who doesn't have pulumi deploy permissions, or some simple CI environment which is only supposed to run nodejs tests) has to have pulumi installed to run the app, execute tests etc. even though they never use pulumi themselves.
In order to avoid this we currently always have to create two package.json's - one for the node.js application and one for the pulumi code which deploys it in a subdirectory. While this separation is advisable in most cases, it is over-complexing things for a small stacks which just deploy a lambda function etc.

**Comment by lukehoban** [comment]
These scenarios make sense.  Doing this will mean that the Pulumi packages can install successfully but in practice be unusable, which is a bit of a shame.  But I think @geekflyer is right that there are going to be enough cases where we need to allow this to succeed just to pick up `.d.ts` files or as part of a project which can be run with either Pulumi or some other approach.

**Comment by ellismg** [comment]
This is now complete.  The next released builds of packages for all our providers will not fail to install when `pulumi` is missing on the path, but will display actionable feedback on how to address the issue.
