### ISSUE TITLE
If new fails to update, it doesn't persist stack selection

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2192]
If the update step during `new` fails, it leaves behind the project without a selected stack, so that the next time you run a command, it prompts you to "Please choose a stack, or create a new one."

It seems we should persist the stack selection sooner, right after it has been created, so that this doesn't happen.

**Comment by pgavlin** [comment]
We no longer update, during `new`, correct? Can we close this?

**Comment by justinvp** [comment]
> We no longer update, during `new`, correct? Can we close this?

Right. Closing.
