### ISSUE TITLE
Referencing remote stacks

### ISSUE THREAD

**Issue by jbellmore** [pulumi/pulumi#2208]
Hello!

We currently use Terraform at my organization and being a software engineer I am very excited about Pulumi. We have been waiting for someone to finally use "real" languages with first class support for proper package management, testing, etc. Modularity is what drove us to Terraform to begin with but we are not satisfied with using a declarative DSL without proper conditionals, for each loops and other things you would find in a proper language.

With that said, the one thing we have been very happy with is the ability to reference remote stacks to get values. By doing this, we have been able to break our stacks apart based on lifecycle of the components, while not having to copy and paste string values all over the place. We do this using the terraform remote data sources to refer to an output from a different stack and use them as variables in another stack.

A good example of this is having global infrastructure where the lifecycle is very different from an applications lifecycle. Think of something like subnets being created once per cloud environment where VM's would come up and down inside of that subnet based on events in an application's lifecycle (creation, new version release if doing immutable, etc). So in that instance, we have one code repository that defines the global infrastructure (including subnets) and has outputs which include the id's of the subnets that we created. Then in our app's infrastructure repo we use a remote data source to fetch those values from the remote state of the other repo. This way, there is no need to copy and paste these generated id values around into environment variables or other inputs.

So my question, does Pulumi support something like this or is this on the product roadmap at the moment? I wasn't able to find anything in the docs or in other Github issues about this. I am really hoping you do support it or will in the near future because I would definitely like to switch over if so!

Thank you!

**Comment by lukehoban** [comment]
@jbellmore Great question! In fact, we just landed support for a new feature (`pulumi.StackReference`) to support this in a first class way yesterday, and it will be in the next release of Pulumi! https://github.com/pulumi/pulumi/issues/109

Prior to this, you could certainly already accomplish this separation by standing up different Pulumi stacks for each of the layers of infrastructure, and then manually extract outputs from one layer and feed them in as configuration to other layers.  Many users are doing exactly this today with Pulumi - and it works but requires more manual effort than is ideal.

With https://github.com/pulumi/pulumi/issues/109, you can now do the following:

```typescript
// Lower level stack - deployed to `lukehoban/bucket`
import * as aws from "@pulumi/aws";
let bucket = new aws.s3.Bucket("mybucket");
export let bucketId = bucket.id;
```

```typescript
// Higher level stack - deployed to `lukehoban/app`
import * as aws from "@pulumi/aws";
import * as pulumi from "@pulumi/pulumi";
let remotestack = new pulumi.StackReference("lukehoban/bucket");
let object = new aws.s3.BucketObject("foo", {
    bucket: remotestack.bucketId,
    content: "Hello world",
})
```

**Comment by jbellmore** [comment]
That's amazing news, thanks so much for the quick response!

This looks like exactly what I am looking for :)

**Comment by nguyenxndaidev** [comment]
> With #109, you can now do the following:
> 
> ```ts
> // Lower level stack - deployed to `lukehoban/bucket`
> import * as aws from "@pulumi/aws";
> let bucket = new aws.s3.Bucket("mybucket");
> export let bucketId = bucket.id;
> ```
> 
> ```ts
> // Higher level stack - deployed to `lukehoban/app`
> import * as aws from "@pulumi/aws";
> import * as pulumi from "@pulumi/pulumi";
> let remotestack = new pulumi.StackReference("lukehoban/bucket");
> let object = new aws.s3.BucketObject("foo", {
>     bucket: remotestack.bucketId,
>     content: "Hello world",
> })
> ```

I am testing the official example [aws-ts-stackreference](https://github.com/pulumi/examples/tree/master/aws-ts-stackreference) add these lines to all `Pulumi.yalm`
```
backend:
  url: file://./
```

So each project has its own `.pulumi` directory
![image](https://user-images.githubusercontent.com/24372782/67149007-64bb4c00-f2a6-11e9-8ecc-c1483513aff6.png)

@lukehoban How can I create `StackReference` in this case? What is the name of the `StackReference` I need to provide in the constructor?

**Comment by lukehoban** [comment]
@nguyenxndaidev StackReference currently can only work across stacks all managed by the same backend.  It uses that backend to look up the stacks.  You would need to have all your stacks share a single  backend.  In fact, this is part of why I didn't love the change to support `backend:` in the `Pulumi.yaml` - it is not really aligned with the existing model where backends are more of a global state shared across projects/stacks (and in fact, for a single project, you may well have stacks that live in different backends).  

There are a handful of issues like this related to the local backends currently - https://github.com/pulumi/pulumi/issues/2522 is tracking one of the more fundamental ones.  

You can definitely accomplish what you want here in the Pulumi service backend, and you should be able to accomplish it with a shared local or remoter state backend across all your stacks.

**Comment by nguyenxndaidev** [comment]
@lukehoban Thanks for your reply!

My workaround for this issue is that having a single backend for all inter-dependencies projects. Then I add project name to the stack name to differentiate stacks, ex. `dev` becomes `vpc.dev` for `vpc` project.

**Comment by zhaohc10** [comment]
can we use the same backend(like s3 bucket) but different folders?
