### ISSUE TITLE
Move to pure-JS grpc dependency

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2218]
Pulumi users have hit many installation issues with the native dependencies of `grpc-node` that are part of the `@pulumi/pulumi` package.  

We should explore replacing it with https://github.com/grpc/grpc-node/tree/master/packages/grpc-js which is a pure JavaScript implementation.

**Comment by lukehoban** [comment]
Users hitting issues due to this:
* https://github.com/pulumi/pulumi/issues/2217
* https://github.com/pulumi/pulumi/issues/2157

**Comment by ellismg** [comment]
Note that moving to this will up the minimum node version we require.  The gRPC package has this listed in their engines section: `"node": "^8.11.2 || >=9.4"`

**Comment by lukehoban** [comment]
Do we know if those are true requirements (due to fundamental requirements in those Node versions), or are these just versions that have currently been tested on?

**Comment by joeduffy** [comment]
I also wonder if there's a way we can support downlevel Node.js versions by falling back to the native gRPC. Even if that has to be done manually (but I do also wonder if it's possible to do automated).

**Comment by ellismg** [comment]
Since upstream grpc has solved our issues for Node 11, by publishing binaries, we should be fine until at least Node 12 (according to https://github.com/nodejs/Release#release-schedule that will be released late April).

There's higher impact work we can be doing for now, so I'm moving this out.  Figuring out what to do by M22 should give us enough lead time to do the right thing.  Not that Node 6 official EOLs at the end of April next year.

**Comment by ellismg** [comment]
Node 6 is now EOL, and Node 8 will EOL at the end of this calendar year.  https://www.npmjs.com/package/@grpc/grpc-js recommends Node 10+, but has some support on Node 8.  We might want to look into this, but actually the Node 12 roll-out didn't bite us so bad, even with the native dependency.

**Comment by lukehoban** [comment]
This is done in the `2.0` branch.

**Comment by Dominik-K** [comment]
This also solves `node-pre-gyp` fallbacks to source-compiling `grpc`. Logs like this
```
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.24.2 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error bad download 
```
should be gone (nice for search-engine searches :-) ).
