### ISSUE TITLE
`pulumi new` Git HTTPS x509: certificate signed by unknown authority error

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2233]
A user reported hitting the following:

```bash
$ pulumi new https://github.com/pulumi/templates/python -s lukehoban/python-dev

error: Get https://github.com/pulumi/templates.git/info/refs?service=git-upload-pack: x509: certificate signed by unknown authority
```

**Comment by pgavlin** [comment]
I've tried a few different operating systems and machines without any luck reproducing this. I'm going to close this out for now.

**Comment by joeduffy** [comment]
I believe a customer reported this, so we should definitely try to track down.

Does this repro if you run on a fresh Ubuntu image that you haven't yet run `apt-get install ca-certificates` on?

**Comment by lukehoban** [comment]
The user also noted they were in a corporate environment with a proxy. I strongly suspect there is a real issue here that we’ll need to address.

**Comment by pgavlin** [comment]
> The user also noted they were in a corporate environment with a proxy. I strongly suspect there is a real issue here that we’ll need to address.

This is useful information. I will try with an HTTP/HTTPS proxy.

**Comment by pgavlin** [comment]
I could not reproduce this with either of the suggestions above (Ubutnu 18.04 without `ca-certificates`, Ubuntu 18.04 with HTTP and HTTPS proxies).

**Comment by joeduffy** [comment]
I'm 90% certain I've seen this error when CAs haven't been installed on my machine. Does Ubuntu come with them pre-configured?

**Comment by joeduffy** [comment]
I can try to repro, since I hit this sometime fairly recently. Might have been Debian. No idea if this is what the customer hit but it seems possible.

**Comment by pgavlin** [comment]
> I'm 90% certain I've seen this error when CAs haven't been installed on my machine. Does Ubuntu come with them pre-configured?

It does. I removed `ca-certificates` manually.

**Comment by joeduffy** [comment]
One alternative, possibly plausible, theory:

```
$ pulumi login --local
Logged into 53b2c30f1548 as root (file://~)
$ pulumi new https://github.com/pulumi/templates/python -s python-dev
error: Get https://github.com/pulumi/templates.git/info/refs?service=git-upload-pack: x509: certificate signed by unknown authority
```

**Comment by pgavlin** [comment]
Also possible that `http.sslCAPath` is set in the global git config. Trying this now.

**Comment by swgillespie** [comment]
Is there anything actionable for us here? It sounds like this may have happened because of a misconfigured CA?

**Comment by lukehoban** [comment]
I've pinged the original user who reported this to see if we can get additional details for reproducing.  Given that we've only heard the one report so far though, and have not been able to reproduce ourselves, I'll close this out.  If others hit this and can share a repro please do and we'll reopen to investigate.

**Comment by redbaron** [comment]
In case anyone need to make use of  custom CA certificate, here is how it works for current docker image (with certs being in `/etc/pki/trust/anchors/`, adjust this path as you see fit) :

```
docker run -e https_proxy=$https_proxy -e PULUMI_ACCESS_TOKEN=... --rm -v $(pwd):/code -w /code -v /etc/pki/trust/anchors/:/usr/local/share/ca-certificates --entrypoint= pulumi/pulumi  /bin/sh -c 'update-ca-certificates; exec pulumi new  ...'
```
