### ISSUE TITLE
Vertically resizing window leads to confusing display of update progress

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2241]
After vertically shrinking then growing a window during a `pulumi update` I frequently see rows that are repeated and/or stale.  

Note the large number of duplicated rows below (for `QueueEventSubscription` and `EventSourceMapping` in particular):
![screen shot 2018-11-24 at 8 57 49 am](https://user-images.githubusercontent.com/223467/48970890-23072000-efc7-11e8-8666-708e56fb9524.png)

In contrast, when the update completed, the display ends up correct:

![screen shot 2018-11-24 at 9 00 39 am](https://user-images.githubusercontent.com/223467/48970911-70838d00-efc7-11e8-969a-8e8f18e08773.png)

**Comment by lukehoban** [comment]
@CyrusNajmabadi Do we know how to fix this?

**Comment by CyrusNajmabadi** [comment]
There's something easy we can try that might help.  We currently listen for changes to the width of the terminal and we clear all our display caches and refresh things.  We might as well try to do the same when the height changes as well.  Let me see how that helps things.

**Comment by CyrusNajmabadi** [comment]
Mitigated with #2241.  Note: this is not a full fix to make the experience great for all circumstances.  One thing we're not good with is is when the user manually scrolls while we're updating (at least one windows).

**Comment by CyrusNajmabadi** [comment]
Closing this out as addressing the main issue.  Going to open a couple of additional issues for future milestones.

**Comment by CyrusNajmabadi** [comment]
Sufficiently mitigated with https://github.com/pulumi/pulumi/pull/2990
