### ISSUE TITLE
Update all shortlinks to use statically-generated links in the docs repo

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi#2245]
Once https://github.com/pulumi/docs/pull/682 merges, all existing shortlinks should be moved off of external services such as https://goo.gl/ and generated statically instead.

**Comment by lukehoban** [comment]
@lblackstone Think you can take an initial pass over this?

**Comment by lblackstone** [comment]
I updated all the goo.gl references in our code to point to pulumi.io instead.
