### ISSUE TITLE
Factually incorrect statement: "Build software for any cloud using your favorite language"

### ISSUE THREAD

**Issue by dsaf** [pulumi/pulumi#2255]
C# is not there at the moment - just some funny scripting/front-end languages. I cannot seriously recommend this to my team over YAML/DSLs.

**Comment by dsaf** [comment]
#1526

**Comment by lukehoban** [comment]
This is now listed on the [roadmap](https://github.com/pulumi/pulumi/wiki/Roadmap).  We are investing right now in some work to enable a longer tail of languages in the near future, including of course C# and Java!  I'll close this out as a dupe of https://github.com/pulumi/pulumi/issues/1526.
