### ISSUE TITLE
local testing

### ISSUE THREAD

**Issue by chakch** [pulumi/pulumi#2260]
how can i test AWS infrastructure using pulumi ?

**Comment by ellismg** [comment]
Can you help me understand the sort of tests that you want to write?  Our general strategy has been to follow a model where we actually provision real infrastructure in AWS and then run integration style testing against it (e.g. deploy an actual application and then try to hit exposed endpoints). In some cases we also do testing where we spin up infrastructure and then as questions about the local state file (e.g. how many ALBs were allocated, Is there an S3 bucket and does it have these properties).

We currently use a go library  we developed ourselves to do this, which just drives the execution of the CLI, but we want to make it possible to write this style of testing in the same language that you infrastructure is defined in so it's possible to leverage the entire testing ecosystem of your language.

One question I do have, about the title here, is if you are looking for something where we *don't* spin up AWS resources in your account, in favor of some other strategy.  If that's the case, what would you expect these local tests would do?

**Comment by TLipede** [comment]
@chakch AWS SAM might suit your needs:
https://aws.amazon.com/about-aws/whats-new/2018/04/aws-sam-cli-launches-new-commands/

**Comment by pgavlin** [comment]
It looks like this issue has gone stale, so I'm going to close it for now. Please re-open if the question is still open.
