### ISSUE TITLE
Should likely allow passing 'providers' to a CustomResource

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#2263]
While passing a 'provider' is one of the more common expected patterns for a CustomResource, there is no problem with passing 'providers' (plural), and it even makes sense in a world with arbitrary resource parenting.  

We should just allow this work.  Note this means a few things fall out:

1. 'providers' should just move into ResourceOptions.
2. We probably want to give either an ordering, or an error if you give both 'provider' and 'providers' (i would prefer an error).  If we really needed both, you could just pass 'providers' with 'provider' added to it under the appropriate key.

**Comment by lukehoban** [comment]
This sounds related to (though maybe the opposite of?) https://github.com/pulumi/pulumi/issues/1802. 

Should we add a note on this request to that issue and track in one place?

**Comment by lukehoban** [comment]
Added notes to #1802 and closing this one out.
