### ISSUE TITLE
Support testing Pulumi programs using tests written in the source language

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#2287]
From a discussion on slack, about testing:

>Today, the only test framework we have is the one we use internally which happens to use Go and `go test`, but can run tests against Pulumi applications written in any language.  You can see an example of this here: https://github.com/pulumi/eks/blob/master/nodejs/eks/examples/examples_test.go

>We have plans to move to a model where we can enable any test framework within the language you are using to author your Pulumi applications to be used to author and run test - so jest, mocha, etc for Node.  We expect to enable both tests of deployment, validation and tear down - along with offline validation that components will create the expected child resources with the expected inputs to validate logical correctness of complex components without the need to actually deploy to a cloud provider.

This issue tracks doing the above work to adopt such a model.

**Comment by ellismg** [comment]
Somewhat related is this issue: https://github.com/pulumi/pulumi/issues/2014 where a user wanted to apply policy over what stack could be updated for a project.  If it was easier to drive the deployment life cycle from within the Pulumi program itself, I think it would be possible for policies like the above to be enforced in code.

**Comment by joeduffy** [comment]
@pgavlin @lukehoban Is this in scope for Q3?

**Comment by joeduffy** [comment]
I've referenced this issue from the following blog post: https://www.pulumi.com/blog/unit-testing-infrastructure-in-nodejs-and-mocha/

**Comment by dustinfarris** [comment]
Looking forward to seeing how the "offline validation" shapes up.

> offline validation that components will create the expected child resources 

Could this also be extended to cover resource inputs/dependencies in general, not just those wrapped up in a component?

**Comment by bincyber** [comment]
I had this exact use case which lead me to develop an integrating testing framework for Pulumi programs written in Python: https://github.com/bincyber/pitfall

**Comment by lukehoban** [comment]
@pgavlin has a PR out with an approach to fully mocking the engine interface as a foundational element of unit testing approaches.  See pulumi/pulumi#3738.

**Comment by mikhailshilkov** [comment]
Moving to 0.32 to have enough time to get this right across SDKs

**Comment by pgavlin** [comment]
Pushing this to M33 in favor of finishing off the .NET SDK work--feel free to move back into M32 if that feels better.

**Comment by mikhailshilkov** [comment]
Unit testing is now implemented in all four supported runtimes. Docs are coming soon and tracked in separate issues.
