### ISSUE TITLE
Improve performance of preview/update

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#2303]
There have been some reports that upgrading to v0.16.7 of Pulumi lead to a large performance regression.

```
Resources:
    + 206 to create

pulumi preview  28,03s user 4,33s system 10% cpu 5:22,12 total
```

I would all but guarantee this is related to the new way we emit log data to the service (engine events instead of pre-rendered diff messages).

**Comment by joeduffy** [comment]
Reopening until we add a regression test.
