### ISSUE TITLE
Support lists and maps in config

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2306]
A customer gave us feedback that they'd like to be able to have real lists and maps in their config values. Without this, they have resorted to encoding as comma separated strings or key/value pairs, with custom parsing logic. Particularly given that we serialize these as JSON/YAML, we should consider simply supporting the full set of structures available in that type system.

**Comment by redbaron** [comment]
If it helps prioritise  , please register another [small] customer interest in this feature

**Comment by pgavlin** [comment]
I'd love to better understand the concrete work we're planning for M27. Is this as simple as "support maps and lists in Pulumi.*.yaml"?

**Comment by justinvp** [comment]
> Is this as simple as "support maps and lists in Pulumi.*.yaml"?

Perhaps, but do we want to encourage manual editing of the `Pulumi.*.yaml`? I think we should at least consider the CLI experience here. For example, do we need some special way of indicating list/map values from the CLI or can we make existing ways of doing it (e.g. comma separated string) work? I'll think about it and come up with a proposal we can review in the next day or two.

**Comment by pgavlin** [comment]
Sounds good to me.

**Comment by justinvp** [comment]
For CLI experience, consider how helm supports this: https://github.com/kubernetes/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set

**Comment by gitfool** [comment]
Nice to have CLI support, but if it gets complicated, I'm probably just going to edit the yaml directly, unless there are reasons not to do that?

**Comment by justinvp** [comment]
PR is almost ready to be sent out, but not blocking this milestone.

**Comment by gorilych** [comment]
W/A with implementing `getDict`

Allows to translate keys like `authorizedIPs.andrey: 1.2.3.4`, `authorizedIPs.slava: 5.6.7.8`, ... into dictionary `authorizedIPs: { andrey: '1.2.3.4', slava: '5.6.7.8', ...}`.

```
import * as pulumi from '@pulumi/pulumi';

class Config extends pulumi.Config {
    readonly subkeySep = '.';

    private myFullKey(key: string): string {
        return `${this.name}:${key}`;
    }

    private subkeyToKey(key: string, subkey: string): string {
        return `${key}${this.subkeySep}${subkey}`;
    }

    public getSubkeys(key: string): string[] {
        const prefix = `${this.myFullKey(key)}${this.subkeySep}`;
        const prefixLength = prefix.length;
        const allConfig = pulumi.runtime.allConfig();
        return Object.keys(allConfig)
            .filter(key => key.startsWith(prefix))
            .map(key => key.slice(prefixLength));
    }

    public getDict<K extends string = string>(key: string): { [subkey: string]: K } | undefined {
        const subkeys = this.getSubkeys(key);
        if (subkeys.length == 0) return undefined;
        // convert subkeys to map subkey -> value
        return subkeys.reduce((dict, subkey) => {
            dict[subkey] = this.get<K>(this.subkeyToKey(key, subkey));
            return dict;
        }, {});
    }
}

// Usage example
const config = new Config();

export const authorizedIPs = config.getDict('authorizedIPs');
```

**Comment by Mistic92** [comment]
Are maps supported for yaml? I'm getting error
`* unexpected configuration type 'map[string]interface {}': valid types are string, List<string>, number, List<number>, integer, List<integer>, boolean, List<number>`

for 
```
config:
  cloud_run:resources:
    ingress: "all"
 ```

**Comment by Frassle** [comment]
> Are maps supported for yaml?

They are not currently supported.
