### ISSUE TITLE
Consider hierarchical config

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2307]
In a customer conversation recently, we were asked about plans to support hierarchical config. [TeamCity's approach to this](https://www.jetbrains.com/teamcity/features/configuration.html) was cited as a good example of a model they'd like to see. We did, in fact, used to support project-wide configuration, and may wish to consider bringing it back; I do believe they envisioned even richer support (custom namespacing shared between multiple stacks), but this seems like a simple way to start. It's currently also possible to string together stacks using `StackReference`, although configuration needs to be manually re-exported and propagated between stacks which isn't terribly convenient.

**Comment by nesl247** [comment]
This just bit us for the first time. Previously we didn't like it due to the fact that we had to have everything on a single level, but we just tried to have an array value and realized we couldn't.

I'm curious as to the design decision as to why it's like this.

**Comment by lukehoban** [comment]
The history here is that the Pulumi config system was initially focused on the `pulumi config set <key> <value>` user interface, which naturally biases toward string keys and string values.  Only later did the storage for these get moved into a `Pulumi.stack.yaml` file sitting in the project root, which makes it look like something where a primary user interface should be YAML/JSON (and hence object/arrays).

We honestly have to re-think the config model overall and which direction we want to go - whether to focus more toward `pulumi config set` or more toward a YAML/JSON interface to authoring and managing configuration.

For workarounds, it is common to either:
1. JSON-encode values when stored in config and then use `pulumi.config.getObject(...)` to parse the JSON inside the program.
2. For arrays, just comma-separate the values in input and `.split(",")` to parse them in the program.

**Comment by nesl247** [comment]
Given the fact that we as customers already have to write code and everything to use pulumi, it does make more sense to be config file based. I would leave the CLI for creating secrets.

However, should you choose to keep `config set <key> <value>`, I would recommend the common syntax of `.` separation. Then when saving it:

```
pulumi config set parent.child 1234
```

becomes

```
parent:
	child: 1234
```

Thanks for the insight!

**Comment by lukehoban** [comment]
FWIW - the issue tracked here is actually about hierarchical config in the sense that there could be configuration applied at the organization or project scope which is inherited as defaults into the stack scope.  

I think the feature you are asking about is really more the one tracked in https://github.com/pulumi/pulumi/issues/2306, which has a few more details.  https://github.com/pulumi/pulumi/issues/1052 is also somewhat related.  We'll be tackling this constellation of topics together as part of re-thinking config in the near future.

**Comment by texdc** [comment]
While trivial, consider multiple stacks in the same AWS region.  For each stack, it's necessary to define it for each stack.  [This example](https://github.com/pulumi/examples/blob/master/aws-ts-static-website/Pulumi.yaml) would be the desired implementation.

**Comment by texdc** [comment]
I would also like you to consider variable precedence.  For instance, we'd like to build generic automation that can be configured to taste on the cli at runtime.  So, these cli vars would have the highest precedence, using the selected stack vars as defaults.

```sh
$ pulumi up --vars "foo=bar, zim=zam"
```

**Comment by tedchangtr** [comment]
are there any plans to implement this in the future? we can do this ourselves by writing our function/library, but I would think many people are doing something similar so it might make sense to support this natively?

**Comment by lukehoban** [comment]
@tedchangtr Curious - which form of hierarchy in particular are you looking for?  What would your ideal model be for the scenarios you currently have in mind?

**Comment by tedchangtr** [comment]
@lukehoban We were going to do something similar to what you suggested in a slack message: https://pulumi-community.slack.com/archives/CJ909TL6P/p1575985418099700?thread_ts=1575973362.095100&cid=CJ909TL6P where we have a Pulumi.base.yaml file that can be overridden by stack specific configs like Pulumi.[stack name].yaml and/or the cli. Another option would be use the Pulumi.yaml file to store the shared program configs so we don't need to introduce any additional files.

**Comment by unthought** [comment]
Another vote for this. I ran yesterday into the problem of trying to ignore certain tags that AWS EKS is adding to subnets, and the only way I found is to add this to create stack config files for each stack with the following content:
```yaml
config:
  aws:ignoreTags:
    keyPrefixes:
      - 'kubernetes.io/cluster/'
```

Since we rely mostly on a library shared by all project which encodes/generates defaults based on aws account and stack names, we don't really use stack configuration for anything and this adds quite a bit of noise to every VPC creating stack.

I tried to hack around it with `pulumi.runtime.setConfig` before importing @pulumi/aws (TS), but I think you the default provider is actually not consulting that, even if it's set, or loading it somehow before the AWS import, earlier than I can reach without setting it on the filesystem.

PS: also you will always need this particular setting if you are trying to manage subnet tags with Pulumi, because Pulumi will pick up any untracked tags when writing a change to the subnet tags, and the next run will try to delete the tags since they're not on the resource. Also, `ignoreChanges` doesn't really help you here. I can open another bug for this if desired.

**Comment by NArnott** [comment]
I'd love to put values that are common across all stacks for a project in a central place (instead of copy/paste same value across several stack yaml files).

As an example, the CLI could take a -g (--global) flag so that `pulumi config set -g testvalue 12345` would create a config entry in the Pulumi.yaml file, instead of the currently selected stack's yaml file.

Using the existing Pulumi's config logic, this would still support secrets and have config values display in the Pulumi site's Configuration history as stack-level configurations do.

**Comment by philomory** [comment]
Personally I would love to see even simple hierarchical configuration available, or even something as fully-featured at Hiera from Puppet.

**Comment by hammadzz** [comment]
@justinvp any plans for this or current workarounds? I want to be able to set configs at project level too.

**Comment by farvour** [comment]
I also second the decision regarding a hierarchial configuration design. Something like Hiera would be great, or even Reclass

http://reclass.pantsfullofunix.net/

This is what we were using with Kapitan prior to switching our Kubernetes stuff over to Pulumi, and its abilities to do some really neat "DRY" with includes and such was a very powerful feature. I find myself having to hodge-podge this functionality into the pulumi config by leveraging the ol config.get() or "SOMETHING ELSE" nomenclaTure a lot..

**Comment by dimitor115** [comment]
@lukehoban Is it planned to be implemented?

**Comment by jamesla** [comment]
+1

**Comment by tedchang77** [comment]
Waiting for this as well. Any timelines?

**Comment by delitescere** [comment]
I have an interim workaround using this [script](https://bitbucket.org/delitescere/contact/src/main/bin/init-local-stack) with [these](https://bitbucket.org/delitescere/contact/src/main/config/) templates. It's designed for re-creating stacks that are targeting LocalStack but could be repurposed for project-wide stacks that need to have the same keys but machine-specific values and work along with various `.env` files for interpolation.

**Comment by nwmcsween** [comment]
Please make this pluggable somehow with parsing, merging, etc (yaml, json, whatever) as a plugin implementation detail instead of including it Pulumi.

**Comment by Frassle** [comment]
Hey all. Just an update that we are currently looking into supporting hierarchal config, and have a first version of our plans to share.
This work also ties into [structured config](https://github.com/pulumi/pulumi/issues/1052) as some level of that is required for [pulumi-yaml](https://www.pulumi.com/docs/reference/yaml/#configuration) which is currently having to do it's own thing here.

Just to point out that this plan probably won't solve _everything_ that's been discussed in this issue, but it's just a start we expect to build more features on top afterwards.

# Project config

Pulumi.yaml project files will now have a "config" section which will allow the setting of both values for config keys, and also the declarition of types for project config.
A simple example would be:
```
config:
	aws:region: us-west-2
	vmCount:
		type: integer
		default: 2
	name:
		type: string
		required: true
```

This would set "aws:region" to "us-west-2" for every stack in this project (unless the stack override it in it's own config) and declares two config variables for the project, "vmCount" which would default to 2, and "name" which must be set in each stack config as it's required and has no default.

For those who aren't intrested in types, you could also set the above defaults like so:
```
config:
	aws:region: us-west-2
	vmCount: 2
```
This only works for primitive values, if you want to set an object value it must be nested under a "value" key:
```
config:
	coords:
		value:
			x: 123
			y: 456
```
The above results in an config entry of `["coords"]={"x": 123, "y": 456}` being sent to your program.

We'll be working on a full JSON schema of what is valid for config entries, but the initial version should have support for basic JSON schema-like types.
```
config:
	someBool:
		type: boolean
	someInt:
		type: integer
	someNumber:
		type: number
	someString:
		type: string
	anArray:
		type: array
		items:
			type: string
	aMapOfStringToInt:
		type: object
		additionalProperties:
			type: integer
	anObject:
		type: object	
		properties:
			x: 
				type: integer
			y: 
				type: integer
```
Each type will also have the option of being marked "required" or not, and having a "default" value set.

# Future plans

We've already got some ideas of how to make this system easier to migrate to, and more features to build on top.

Firstly we plan on adding a "pulumi config infer" command. This will look at all your existing stack configs and try and infer what the project config should be. 
For example if every stack sets "aws:region" to "us-west-2" we can set that in the project config instead. If every stack has a string config entry "name", we can declare that as a string type in project config.

Secondly we've got a number of options to add to the config schema. A "merge" option to change how arrays and objects are merged down from project config to stack config when both set the value. An "environment" option to try reading an environment variable to get the config entry if the stack doesn't set it.
More features from JSON schema, such as "description" and validation keywords to allow more constraints to be expressed in the config declaration.

Thirdly given we'll now have type declarations for config we plan on adding a way to take the project config schema and emit a "Config" object in your projects language so you can get type-safe access to config values. No more `config.getNumber("lucky");` instead just `config.lucky`.

Forthly we will add secrets at the project level, this will be fully supported by the Pulumi Service in the same way as stack config (you'll also be able to use any other secret manager).

Finally we'll extend to more hierarchy than just the project. We expect to have a key like `hierarchy` in the project that will define other sources of data to fetch. Very early thinking but something like:
```
hierarchy:
 - type: vault
   host: {org:vault_host}
   token: 
     secure: <encrypted vault token, at project level by project passphrase secrets>
 - type: http
   url: https://coolcats.company/api/config
   authorization:{vault:keys[“coolcats”]}
 - type: file
   path: ../data/data.yaml
```

# Feedback

Please leave feedback, and questions about these plans. The more we hear from users the better we tune things to solve your problems.

**Comment by chris-stetter** [comment]
In the [current version](https://www.pulumi.com/blog/project-config-mvp/) of this feature, is the `required` option (as shown in the previous comment) implemented?

**Comment by Frassle** [comment]
> In the [current version](https://www.pulumi.com/blog/project-config-mvp/) of this feature, is the required option (as shown in the previous comment) implemented?

Kind of. Just don't set a default and it'll be treated as required. What we don't currently have is a way to say something is optional with no default.

**Comment by lukehoban** [comment]
When we closed this issue out, we referred to some future directions for support richer hierarchical configuration in Pulumi.

Today, we released [Pulumi ESC](https://www.pulumi.com/blog/environments-secrets-configurations-management/) which is a solution to this problem which is both much more general than just hierarchical configuration, but also integrates nicely into Pulumi IaC to solve for several of the use cases here.  If you are looking for hierarchical configuration for Pulumi, check out [Pulumi ESC](https://www.pulumi.com/docs/pulumi-cloud/esc/).

**Comment by gnorbsl** [comment]
So you create a half assed config management in your tool and then paywalled the properly implemented one.

**Comment by aniongithub** [comment]
So is there a way to work with Pulumi hierarchical config without subscribing to the Pulumi Cloud? If not, this isn't "richer" It's us being poorer, no? :smile: 

In all seriousness, just looking for a way to use Pulumi as a cloud infrastructure abstraction layer  without having to subscribe to the Pulumi Cloud.
