### ISSUE TITLE
StackReference doesn't update when underlying stack updates

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2310]
From a user report on Slack:

- create an output which was just a string (kubeconfig) in one stack
- consume/use this output value in another stack
- modify the output value in the first stack (as I found a bug in its contents)
- try to `pulumi update` in the second stack that uses output from the first stack but it didn’t find any updates in the output value (was still using the old and incorrect value)

I was able to reproduce the same.

**Comment by pbzdyl** [comment]
I just tested also this scenario:
- I have added a string output in stack 1 and applied it with `pulumi update`. I could see the output added in app.pulumi.com console
- I have added a usage of this output in stack 2 (another key in k8s configmap) and I run `pulumi update` in stack 2 but the preview shows there are no changes to be applied and when I run this update the new key is not added to the configmap

**Comment by pgavlin** [comment]
https://github.com/pulumi/pulumi/issues/2247 tracks the root cause of this issue.

Until that is fixed, we believe that https://github.com/pulumi/pulumi/pull/2332 will do the trick.
