### ISSUE TITLE
support update/refresh/destroy a specific resource

### ISSUE THREAD

**Issue by houqp** [pulumi/pulumi#2317]
Hi,

Is there any plan to support update/refresh a specific resource like terraform's `-target` option?

**Comment by lukehoban** [comment]
It's definitely come up before - but I don't think we have an issue tracking it yet - so thanks for opening one.

Curious if you can provide any additional details on your use case where this is important?  Is your scenario specifically `refresh`?  Or both `refresh` and `update`?

**Comment by houqp** [comment]
I would like to have it for both refresh and update. 

Biggest use-case for me is repairing a broken stack. I have ran into this couple times before where the update command would exit with unresolvable error due to incorrect resource update order. The way I fix it right now is to manually repair the stack with export and import command. This gets harder when I need to automate the fix for external customers.

**Comment by pgavlin** [comment]
Can you elaborate a bit on the problem of incorrect resource update order?

**Comment by lukehoban** [comment]
We also got an ask about destroying a specific resource - so added that to the title.

**Comment by 2-face** [comment]
++

**Comment by igorshapiro** [comment]
Sometimes resource deletion times out, but the resource eventually being deleted even though the state thinks it is not.
It would be very useful to refresh a specific resource.

**Comment by nesl247** [comment]
Right now this would be really useful. We have a stack that has several hundred resources. Running update on it takes a while as it has to check the status of each. (GCP Pub/Sub subscriptions)

**Comment by nesl247** [comment]
All that is missing now is update correct?

**Comment by CyrusNajmabadi** [comment]
Hi all, this has been done.  In the next version of Pulumi, you will be able to use the `-target` option with `pulumi update/refresh/destroy`.  For more details see:

Refresh: https://github.com/pulumi/pulumi/pull/3225
Destroy: https://github.com/pulumi/pulumi/pull/3244
Update: https://github.com/pulumi/pulumi/pull/3251

Thanks!

**Comment by boillodmanuel** [comment]
Hello,

I saw this feature in changelog 1.2.0 (2019-09-26)
> pulumi refresh can now be scoped to refresh a subset of resources by adding a --target urn or -t urn argument. Multiple resources can be specified using -t urn1 -t urn2.

But I can't find it in documentation : https://www.pulumi.com/docs/reference/cli/pulumi_refresh/

Please do not forget to maintain documentation up-to-date, this is so important ;)

**Comment by pgavlin** [comment]
That's surprising: I've verified that the flag exists in the CLI, so the automatic documentation regeneration we do as part of each release should have updated this. Thanks for the report!

**Comment by pgavlin** [comment]
It looks like the documentation for the CLI was unintentionally regenerated using the wrong version after it was updated for 1.2.0 in https://github.com/pulumi/docs/pull/1793.

**Comment by boillodmanuel** [comment]
Your welcome :)

By the way, I just used this feature, and it was not obvious how to get the urn.
I do a `pulumi stack export` to figure it out, but if we can use the name (as shown by `pulumi preview`) would be definitively easier.
