### ISSUE TITLE
Publish/export kubernetes types to allow passing configuration fragments to Kubernetes pulumi resources

### ISSUE THREAD

**Issue by pbzdyl** [pulumi/pulumi#2334]
Currently no types/interfaces are exported from `kubernetes.core.v1` namespace like `ContainerPort`, `EnvVar` etc. Without these types available it's very cumbersome to create `ComponentResource`s that assemble multiple Kubernetes resources but would like to allow customisation of these resources e.g. by passing a list of `ContainerPort`s that should be exposed in a deployment or `EnvVar`s set on the container ports in a pod.

FYI @hausdorff.

**Comment by lukehoban** [comment]
Issue moved to [pulumi/pulumi-kubernetes #336](https://github.com/pulumi/pulumi-kubernetes/issues/336) via [**ZenHub**](https://www.zenhub.com/)
