### ISSUE TITLE
Support StackReference in Python and Go

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2344]
We added `StackReference` for Node.js in https://github.com/pulumi/pulumi/pull/2180, and should add it for Python and Go as well.

As part of this, we should update https://pulumi.io/reference/programming-model.html with details and cross-language code examples.

- [x] Python
- [ ] Go

**Comment by naveensrinivasan** [comment]
yes +1 for Stackreference in `go`. When is it likely to be available.

**Comment by naveensrinivasan** [comment]
Looks like it is available on Feb 21.

**Comment by swgillespie** [comment]
Python support depends on: https://github.com/pulumi/pulumi/issues/1123.

**Comment by lukehoban** [comment]
Python is now supported with #2786.
