### ISSUE TITLE
Setting GOOGLE_CREDENTIALS in Windows 

### ISSUE THREAD

**Issue by ekoome** [pulumi/pulumi#2345]
Can’t seem to find a way to set the contents of gcp credentials on Windows. 

From the documentation, this will off-course not work.

 export GOOGLE_CREDENTIALS=$(cat credentials.json)

Any suggestions?

**Comment by lukehoban** [comment]
I believe this is addressed by @casey-robertson's comment above and docs fix in https://github.com/pulumi/docs/commit/cd118e6d09317cebd82b210c7ba9f1d5ddc0ef69.

There's also  general docs on the environment variables you can use to configure the GCP provider at: https://pulumi.io/quickstart/gcp/index.html#configuration

If things still aren't working after referencing those - please do reopen.
