### ISSUE TITLE
Add graph and DOT generation

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#235]
During pulumi/lumi#90, we radically changed the representation of resource state, in support of running the evaluator and planner in lock-step to observe output property values.  As a result, we lost our ability to generate true graphs and DOT files.  This work item tracks bringing this back.

**Comment by joeduffy** [comment]
This got added back at some point.

**Comment by FrostyLeaf** [comment]
It's pretty hard to read

![image](https://user-images.githubusercontent.com/8349568/147552246-f496d2b2-ba27-4dd0-bdbb-337d8e6548f9.png)

In browser, it looks like this

![image](https://user-images.githubusercontent.com/8349568/147552492-c65d171b-5750-4f4b-809a-a76f22f86227.png)

Anyway to improve?
