### ISSUE TITLE
Add 'concat' and 'interpolate' equivalencies for Python

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#2366]

**Comment by 2-face** [comment]
Any ETA on this feature or workaround i.e. how to ready programatically the value (option with export is no-go since it refers to CLI when we want to ready exported value)?

**Comment by CyrusNajmabadi** [comment]
hey @2-face It shoudl be possible today in python to just use `.apply` on the actual Output value you have to do this work.  It's definitely not as nice as the TypeScript side, but it's a viable workaround until we get to that point.

Thanks!

**Comment by 2-face** [comment]
hi @CyrusNajmabadi I've tried `gcp_instance.network_interfaces.apply(lambda network_interfaces: network_interfaces[0]['accessConfigs']['natIp']`). Yet it returns Output object.

**Comment by CyrusNajmabadi** [comment]
> Yet it returns Output object.

Yes, that's by design.  That's what `pulumi.concat` and `pulumi.interpolate` do as well.  The idea here is to allow one to take in a set of Outputs, combine them in conveinent ways, but still get an Output back at the end.  

This is necessary as `Output` is what keeps track of dependencies, so the final `Output` you get will have a union of all the dependencies of all the `Output` values that flowed in.  :)

**Comment by CyrusNajmabadi** [comment]
@2-face can you explain what you're trying to do (feel free to come to our slack channel at pulumi-community.slack.com to message me directly).  It's a bit unclear to me, and I'd def like to help you work through your issue.  Thanks!

**Comment by lukehoban** [comment]
I can't think of what the "best" analogue of `interpolate` is in Python.

There are generally four string construction techniques that are common in Python (called out at https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting):
* `"hello" + world`
* `f"hello {world}"`
* `"hello %s" % world`
* `Template("hello ${world}").substitute(world=world)`

An `Output.concat("hello", world)` is a natural equivalent to `pulumi.concat` that handles roughly the first case.

f-strings in Python don't have a "tagged" interpreter like template literals in JavaScript, so there does not appear to be any way to do an equivalent of the second case.

My understanding is that there is no way for values passed on the RHS of `%` to change the type generated by the printf-style `%` approach - so I believe that is not possible either.

The `Template` method seems esoteric enough that it is not what we would want to optimize for.

Is `Output.concat("hello", world)` sufficient here?  If not, what else would we do?

**Comment by astronouth7303** [comment]
Ummm.... before f-strings, there was `str.format()`, and you can totally override `string.Formatter` to define your own variations. (I did this in https://github.com/jacebrowning/yorm/blob/7b98899c363c4c1330d4729f6c81f1b69331f895/yorm/utilities.py#L45-L72 )

I suggest having Python's `pulumi.interpolate` be just a version of `str.format` that returns an `Output`, called like `interpolate('{foo}/{bar}', foo=spam.foo, bar=eggs.bar)`

(My other thought was a more magical variant that mimicked f-strings by performing stack inspection to get the locals, but I'm not certain how easy it is to replicate scope stack searching--locals, closures, globals, builtins.)

This could work by:
* `interpolate` runs `Output.all()` on the pargs/kwargs and gives `.apply()` an internal function that does the actual formatting, returning the result of the `.apply()`
* The internal function reconstructs pargs/kwargs from the list and returns the result of `str.format()`

Most of the hard work comes from marshaling pargs/kwargs into and out of a list for the benefit of `Output.all()`.

(Sorry, this was kind of an journey. I initially thought you would need Deep Magic to make `string.Formatter` async, but then I realized that you can just punt the formatting operation until you have the values. In case you still want to take the more magical option, https://github.com/python/cpython/blob/4f9ffc9d1a6a293563deaaaaf4a13331302219b4/Lib/string.py#L151-L282 is what you want.)
