### ISSUE TITLE
Homebrew using a different version of dep to build binary

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi#2371]
The [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/f484290d964992fab738d15a31a23150f99ffbde/Formula/pulumi.rb#L15) is using the latest version of dep (`0.5.0`), while our build tools are [pinned to an older version](https://github.com/pulumi/scripts/blob/8de338ddad50ecdb7d002017934ca61354bd7d8d/ci/install-common-toolchain.sh#L12).

This has the potential to build the binaries with different vendored dependencies. We should choose one of the following options to fix:
1. Update homebrew formula to use the same pinned version
1. Update our build script to use dep `0.5.0` (See https://github.com/pulumi/home/issues/376)
1. Move to go modules instead

**Comment by ellismg** [comment]
We are now on dep 0.5.0
