### ISSUE TITLE
Pūlumi command-line tool indents incorrectly with non-ascii characters.

### ISSUE THREAD

**Issue by jenstroeger** [pulumi/pulumi#2377]
See this screenshot:

![pulumi](https://user-images.githubusercontent.com/12053937/51499676-e9139800-1e16-11e9-9eae-a841407c1afe.jpg)

Doesn’t happen with I rename that bucket object and use strict ascii characters (i.e. `ueber-uns.html`).

**Comment by mikhailshilkov** [comment]
@jenstroeger I tried to reproduce this but formatting seems to work fine for me:

![image](https://user-images.githubusercontent.com/1454008/60270295-6d9ba280-98f0-11e9-810d-14b1ba532b01.png)

I even tried downgrading to version `0.16.11` from January but it works too:

![image](https://user-images.githubusercontent.com/1454008/60270378-9ae85080-98f0-11e9-9879-0dfbc822696c.png)

What kind of shell environment are you running in?

**Comment by jenstroeger** [comment]
That would then be my next guess. I’m on a Mac using urxvtc and bash on XQuartz… maybe that’s an issue (I have problems with unicode on that terminal anyway).

**Comment by chrsmith** [comment]
I suspect everything here is working as intended. We are just writing text to the terminal, and have no just diction on how those characters actually get rendered in your terminal program. I suspect any alignment issues are a matter of the specific client, the fonts its using, etc.
