### ISSUE TITLE
Plugin resource-aws-v0.16.7 stdout: EOF

### ISSUE THREAD

**Issue by Orozco93** [pulumi/pulumi#2387]
Got an issue trying to run `pulumi up`, pulumi is trying to make the preview of the resources and crash with `error: could not read plugin [/Users/julian.orozco/.pulumi/plugins/resource-aws-v0.16.7/pulumi-resource-aws] stdout: EOF`. 

Error:
<img width="793" alt="screen shot 2019-01-23 at 4 58 14 pm" src="https://user-images.githubusercontent.com/24233012/51642837-21f36000-1f30-11e9-99c9-771fbe431bc3.png">

**Comment by Orozco93** [comment]
Find out the error!
This is the workaround!

I start to check all my plugins and saw 3 plugins:
<img width="503" alt="screen shot 2019-01-23 at 5 16 48 pm" src="https://user-images.githubusercontent.com/24233012/51643605-b1017780-1f32-11e9-8f06-816d310c030c.png">

Start deleting every plugin of aws with `pulumi plugin rm KIND RESOURCE VERSION` (`pulumi plugin rm resource aws 0.16.7`).

Reinstall the plugin of aws with `pulumi plugin install KIND RESOURCE VERSION` (`pulumi plugin install resource aws v0.16.7`)

And you are finish 🎉

**Comment by Orozco93** [comment]
Maybe It can be added to a file of common errors or something similar!

**Comment by lukehoban** [comment]
@Orozco93 I'd prefer to fix whatever caused you to get into this state in the first place if possible! :-)

What OS are you on?  For me on OSX, `0.16.2` matches yours at `128 MB` but `0.16.7` is `143 MB` unlike yours which is `93 MB`.  It seems most likely that somehow your download of that plugin was interrupted or failed?  Do you recall what happened when you installed it - did you see any warning or error during a `npm install` 2 hours before you took that screenshot?

**Comment by pgavlin** [comment]
In the absence of more information, I'm not sure there's much we can do here. I'm going to close this out, as we haven't seen any other instances of this. Please re-open as necessary.
