### ISSUE TITLE
resproto.InvokeRequest is not a constructor

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2414]
Two users have noted hitting the following recently when using `latest` of dependencies.  This appears to have just started happening recently - suggesting a `dev` dependency snuck in in a dependency somewhere?

```
Diagnostics:
  pulumi:pulumi:Stack (eks-cluster-eks-cluster-cd-test):
    TypeError: resproto.InvokeRequest is not a constructor
        at Object.<anonymous> (/builds/service-delivery-platform/mustang/sdp-mustang-terraform/pulumi/eks-cluster/node_modules/@pulumi/pulumi/runtime/invoke.js:58:25)
        at Generator.next (<anonymous>)
        at fulfilled (/builds/service-delivery-platform/mustang/sdp-mustang-terraform/pulumi/eks-cluster/node_modules/@pulumi/pulumi/runtime/invoke.js:17:58)
        at <anonymous>
```

Fixing dependencies to the following appears to have fixed it for one user:

```
  "dependencies": {
    "@pulumi/aws": "0.16.7",
    "@pulumi/eks": "0.16.6",
    "@pulumi/kubernetes": "0.19.0",
    "@pulumi/pulumi": "0.16.12"
  }
```

**Comment by swgillespie** [comment]
The most recent change in this area is https://github.com/pulumi/pulumi/pull/2403 - possibly related?

**Comment by ellismg** [comment]
>  The most recent change in this area is #2403 - possibly related?

This is my suspicion as well, however, I believe that we did get coverage on this change with this build: https://travis-ci.com/pulumi/examples/jobs/173976696

```
[matell@matell pulumi]$ git rev-parse HEAD
1d5526d29248d31daf564dcdf776248917aff990
[matell@matell pulumi]$ ./scripts/get-version 
v0.16.13-dev.1548810467+g1d5526d2
[matell@matell pulumi]$ 
```

And we can see from the build logs above:

> [ /examples/aws-ts-ruby-on-rails ] adding resolution for @pulumi/pulumi to version 0.16.13-dev.1548810467

So in theory, we should have gotten a clean run there.  But I agree this is very suspicious.  We saw similar failures to the above in last night's examples run.

**Comment by CyrusNajmabadi** [comment]
Hit this here as well: https://travis-ci.com/pulumi/pulumi-aws/builds/99330797

**Comment by ellismg** [comment]
0.16.14 has been released to NPM and it should address this regression: https://www.npmjs.com/package/@pulumi/pulumi

**Comment by CyrusNajmabadi** [comment]
Thanks!
