### ISSUE TITLE
Avoid emitting new version warning when not actionable

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2426]
Currently we emit a new version warning like below as soon as we have released a new version of the `pulumi` CLI.  However, some package managers (like `brew`) may take 48 hours or more to update after this, and so users of those package managers cannot realistically take action on this warning, and are just stuck with it indefinitely.

We should do one of:
1. Ensure we don't present this warning until all known package managers are updated
2. Don't emit this warning for installs we know were done through a package manager - let that package manager take care of this prompting

Current thought is to prefer (2) at least for `brew`.

**Comment by clstokes** [comment]
On a related note, a `PULUMI_SKIP_UPDATE_CHECK` (or similarly named) environment variable would be helpful for users that don't want to get warned about (like in CI builds) that could maybe do double duty for this too.

**Comment by ellismg** [comment]
Our plan now is to handle this by just not updating the advertised newest version until `brew` has adopted it.  In practice, they appear to be pretty fast.

I opened #2480 to add `PULUMI_SKIP_UPDATE_CHECK` to the product.
