### ISSUE TITLE
ts + node + dynamic provider - necessary variables are sometimes not captured

### ISSUE THREAD

**Issue by johlrich** [pulumi/pulumi#2429]
I noticed that there are sometimes variables that don't seem to be captured.  The smallest example I could create involved two functions and a common object. 

```
var defaultsForThing = {
  config: {
    x: "x",
    y: "y"
  }
}

export function getX() {
  return defaultsForThing.config.x
}

export function getAll() {
  const x = getX()
  return { x, y: defaultsForThing.config.y }
}
```

When the provider uses `getAll`, it will receive an object containing `x` set to x but `y` will be undefined.

```
 Diagnostics:
   pulumi:pulumi:Stack (missing-vars-missingvarsdev):
     result outside provider is:  { x: 'x', y: 'y' }

     result inside provider is:  { x: 'x', y: undefined }
```

Example repro project: https://github.com/johlrich/pulumi-repros/tree/master/missing-vars

**Comment by CyrusNajmabadi** [comment]
Looking now.  Sorry for the delay on this!

**Comment by CyrusNajmabadi** [comment]
Thanks for the great bug report.  This was a nice subtle issue that you found!
