### ISSUE TITLE
Bad error message when serializing classes as stack outputs

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#2448]
> I'm not really sure what we should do in that case. In JavaScript, classes are just objects, so exporting a class is basically equivalent to exporting JSON. Python has a much stronger distinction between dictionaries and class objects - it's not even legal to serialize a class as JSON.

The serialization we do in JS is pretty lossy here - we lose all prototype structure and functions.  Not sure what the closest reasonable equivalent in Python is though.

Certainly at the least we should fail more "nicely" here - indicating explicitly that the value is not serializable as an output.

_Originally posted by @lukehoban in https://github.com/pulumi/pulumi/pull/2447#issuecomment-463385851_

**Comment by ellismg** [comment]
@CyrusNajmabadi this might be something interesting to think about in the context of the cross language work.

**Comment by lukehoban** [comment]
> The serialization we do in JS is pretty lossy here - we lose all prototype structure and functions. Not sure what the closest reasonable equivalent in Python is though.

I suspect running `vars(o)` on the object is reasonable and roughly equivalent to the JSON serialization that JavaScript does.
