### ISSUE TITLE
Inconsistent UI around how we reference a stack-name during updates.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#2463]
Reported by @pbzdyl

![image](https://user-images.githubusercontent.com/4564579/53121104-43804100-3508-11e9-924b-a9eb30e3e98b.png)

We are inconsistent in the UI in terms of how we reference a stack.  In the list of resources, we call the stack 'example-dev'.  This is due to the following code:

https://github.com/pulumi/pulumi/blob/ce26bd871f42b9ff346058aa0760b1a0b30677ef/sdk/nodejs/runtime/stack.ts#L47-L49

However, elsewhere in the UI we simply call things 'dev'. i.e. `Previewing update (dev):`

We should be consistent here.  As the stack name in code is likely not something we could change (without it causing every stack in the world to be updated), we likely would want to just update the UI to say something more like `Previewing update (example-dev):`

**Comment by pbzdyl** [comment]
Thanks @CyrusNajmabadi. I am not sure changing the `dev` to `example-dev` in `Previewing update` will be actually more clear than using just the stack name everywhere. Web console uses just the stack name:

![image](https://user-images.githubusercontent.com/57622/53121528-b31c1d80-3554-11e9-8000-aa5b8c7f269d.png)

So again we have just `dev`. When CLI prompts for the stack (e.g. during select or when its being created) it also used just stack name without project name.

**Comment by CyrusNajmabadi** [comment]
> I am not sure changing the `dev` to `example-dev` in `Previewing update` will be actually more clear than using just the stack name everywhere.

Well, the UI is being accurate.  The name of the *resource* that *represents* the stack *is* named 'example-dev'.  Open question if we really should have named it htat way.  however, until we have a way to seamlessly rename things, we can't really change this due to the deep impact it would have on everyone who did a pulumi-update.  IMO, this is just a little unfortunate wart, but likely not something we could really make a change on now due to how disruptive it would be :-/

**Comment by pbzdyl** [comment]
I guess we could close this issue then :) I just noticed that and mentioned on Slack. If this is an intended behaviour there's no point in keeping this issue open.

**Comment by CyrusNajmabadi** [comment]
Seems reasonable.  I don't personally think it's a huge deal.  And i think we can accept this behavior (and just have this convo be the resolution around it).  Thanks!
