### ISSUE TITLE
k8s.helm.v2.Chart ignored passed namespace

### ISSUE THREAD

**Issue by adaniline-traderev** [pulumi/pulumi#2465]
Helm resource create resources in default namespace, even when a different namespace is passed in the options:
```
const nginx = new k8s.helm.v2.Chart(
    "nginx", 
    {
        repo: "stable",
        chart: "nginx-ingress",
        namespace: 'nginx-ingress'
    }
);
```
The  generated resources are created under default namespace

**Comment by adaniline-traderev** [comment]
The namespace is passed to the templates:
```
namespace: {{ .Release.Namespace }}
```
generates a templates with the correct template, but all the objects are created under default

**Comment by lukehoban** [comment]
I believe this is the same issue tracked in https://github.com/pulumi/pulumi-kubernetes/issues/217.  I’ll close as a dupe but if you think there’s a separate concern happy to reopen.
