### ISSUE TITLE
Memory leak on windows

### ISSUE THREAD

**Issue by giovannicandido** [pulumi/pulumi#2514]
Polumi is consuming all RAM:

![image](https://user-images.githubusercontent.com/915892/53836404-af35c580-3f6e-11e9-983a-f3bd6f62c6f7.png)

OS: Windows 10
Polumi v0.16.16

**Comment by ellismg** [comment]
Can you tell me a little more about what operation you were doing with Pulumi here?  I assume some update that does a bunch of work, but any insights would be great.

**Comment by giovannicandido** [comment]
Sorry, I was in a rush and didn't stop to debug and provide more information.
I'm attaching the project (I removed sensitive information in **Pulumi-dev.yaml**)

This is what I was doing at the time:

1. Docker for windows with kubernetes enabled (should make no difference, but still... ;-)
2. pulumi up 
3. Wait a few minutes.
4. I realize the container was stock on creation because it was waiting for persistent volume to create by the persistent volume claim (and looks like there is no timeout by design on kubertes for this to happen).
5. Notice machine lagging a bit, like a sweat (this is powerful hardware 😄  )
6. Checked the resources usage and get surprised by 13Gi of ram usage, it made me think: Finally, that money got some usage 😆.

This was because I forget about the name of the persistence volume class. Docker-for-windows didn't have the persistence volume class declared (which is host-path).

The code I uploaded was progress over the code at that exact time, so it will create the persistent volume class and use pulumi config to get name (which will be ready to production usage). To reproduce, I think it takes only a config with the wrong name, or to comment the OVH class (which creates the storage class)

To sumirise is problably: persistent volume class -> persistent volume -> persistent volume claim -> pod dependency.

I hope this could be easy reproduced (didn't test).

I almost forgot: You need to add the banzaicloud-stable chart repository: `helm repo add banzaicloud-stable http://kubernetes-charts.banzaicloud.com/branch/master`

Thank you for your time.
Best regards.

**Comment by ellismg** [comment]
Awesome, thanks for the super detailed repo, @giovannicandido!  I'll take a look.

**Comment by mikhailshilkov** [comment]
This issue is very old and I haven't seen any recent reports of it. I'll take the liberty to close it as stale - anyone please feel free to open a new issue with a repro a memory problem if you ever face one.
