### ISSUE TITLE
Improve first-use experience

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#2523]
Friendlier login prompt and catered template selection in `pulumi new`.

**Comment by justinvp** [comment]
This isn't quite ready. Moving to M22 to finish up early this week.

**Comment by lukehoban** [comment]
I'm not sure exactly what this is addressing at this point.  I'll close this out - but we should review `pulumi new` experience all-up and open more concrete issues.

**Comment by justinvp** [comment]
I've opened the concrete issues:

- Improve the login prompt https://github.com/pulumi/pulumi/issues/3095
- pulumi new should show a catered selection of templates https://github.com/pulumi/pulumi/issues/3094
