### ISSUE TITLE
Support 3rd party publishing of resource provider plugins

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2524]
The resource provider model depends on a plugin system, and these plugins are currently loaded from https://get.pulumi.com.  It is only currently possible for 1st party Pulumi packages to publish plugins there, and as a result, if 3rd parties build their own providers, they can use them locally, but must manually distribute plugins which is often prohibitive to production use.

We should do one of:
1. Allow 3rd parties to publish plugins to https://get.pulumi.com
2. Allow packages to provide a custom location where provider binaries are published and to pull from there instead of https://get.pulumi.com

**Comment by ellismg** [comment]
Closing this out.  The majority of the work is now complete and the renaming work is tracked by a separate issue.
