### ISSUE TITLE
RunErrors aren't concisely reported anymore

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2529]
It used to be the case that `RunError`s led to concise error reporting, including omission of the stack trace. The idea here was that these errors want to instruct the user to do something differently -- like run `pulumi config set ...`, and that the extra noise of a stack trace is simply confusing.

It appears this behavior has regressed semi-recently:

![image](https://user-images.githubusercontent.com/3953235/53922928-4b7dcc00-4044-11e9-9bf4-1b2c9cffc3f5.png)

**Comment by lukehoban** [comment]
@CyrusNajmabadi was looking into this last week.  Notably there are two copies of the error, one with suppressed stack and another with the full stack.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi/pull/2547
