### ISSUE TITLE
Resource required manual delete and pulumi refresh to perform update

### ISSUE THREAD

**Issue by RichardWLaub** [pulumi/pulumi#2535]
Two days ago we were deploying updates to GCP DNS record sets which were successful in some environments but not changed in others. In one particular environment, when we updated and code base and ran a `pulumi up` we saw no changes:
```
Resources:
    23 unchanged
```
The only way we could get Pulumi to show changes was to manually delete the incorrect record sets and run a `pulumi refresh`:
```
Resources:
    - 3 deleted
    21 unchanged
```

After this a `pulumi up` successfully deploy the correct record sets.

**Comment by casey-robertson** [comment]
Richard, I believe `pulumi up` after manual deletion of records also didn't report anything to update, correct?

**Comment by RichardWLaub** [comment]
Correct @casey-robertson. A `pulumi refresh` was required after deletion.

**Comment by leezen** [comment]
I'm going to close this for now. Please re-open if you're still seeing this type of behavior.
