### ISSUE TITLE
Begin a library of Pulumi ESLint rules

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#2558]
TypeScript is great, but there are still a few Pulumi-specific gotchas that we are aware of that can trip up Pulumi users in non-obvious ways. We should consider writing some ESLint rules that catch some of these gotchas.

Lint ideas:

* [ ] Warn when a value of type `pulumi.Output<T>` is used in a template literal (https://github.com/pulumi/pulumi-awsx/pull/177)
* [ ] Warn when a value of type `pulumi.Output<T>` is used with the `+` operator with a string
* [ ] Warn when a resource's name derives directly or indirectly from the name of the current stack or project

_Originally posted by @lukehoban in https://github.com/pulumi/pulumi-awsx/pull/177#issuecomment-472681231_

**Comment by armenr** [comment]
Not valuable input, but if it helps to prove any need/fit --> We'd really appreciate this @ my startup.

**Comment by leezen** [comment]
Another good one might be @typescript-eslint/require-await given the likelihood of async functions and potentially leaking a promise

**Comment by cobraz** [comment]
Probably have a rule for catching missing `provider` as well, for those who are into that kind of thing :)

**Comment by aggmoulik** [comment]
Hey, @mikhailshilkov I was wondering does pulumi still looking for the ESLint rules or if the project is dropped. If not, then I would love to work on it.

**Comment by cobraz** [comment]
@aggmoulik That is great! @theneva and I have started on this, and it could end up as a project at [Pulumiverse](https://github.com/pulumiverse). Are you available on Slack, then let me know there if you wanna join up!

I can introduce you to @theneva as well :)

**Comment by aggmoulik** [comment]
Hey @cobraz, I am available on slack but the slack link on pulumi website, is not longer active.

**Comment by kpitzen** [comment]
Hi @cobraz and @aggmoulik!  Not seeing any `eslint` repositories on Pulumiverse, we've created this repo: [eslint-plugin-pulumi](https://github.com/pulumi/eslint-plugin-pulumi).  The plugin is also now available on npm for installation - it's currently in prerelease but feel free to give it a try.  I hope this is helpful!

**Comment by mikhailshilkov** [comment]
@kpitzen Should we close this issue and track any enhancements on the plugin repo?

**Comment by kpitzen** [comment]
Sounds good @mikhailshilkov - I'll close it out now!
