### ISSUE TITLE
errors when updating DeamonSet: "cannot restore slice from map"

### ISSUE THREAD

**Issue by adaniline-traderev** [pulumi/pulumi#2559]
When installing stable/kiam chart, updated chart's values to put additional annotations on the DeamonSet pods, got error when running `pulumi up`:

```
I0314 10:22:16.935800   42599 step_executor.go:310] StepExecutor worker(29): step update on urn:pulumi:test1::kiam::kubernetes:helm.sh/v2:Chart$kubernetes:apps/v1beta2:DaemonSet::kiam-agent retired
I0314 10:22:16.935875   42599 step_executor.go:310] StepExecutor worker(29): step update on urn:pulumi:test1::kiam::kubernetes:helm.sh/v2:Chart$kubernetes:apps/v1beta2:DaemonSet::kiam-agent failed with an error: 1 error occurred:

* cannot restore slice from map
I0314 10:22:16.935903   42599 step_executor.go:310] StepExecutor worker(29): step update on urn:pulumi:test1::kiam::kubernetes:helm.sh/v2:Chart$kubernetes:apps/v1beta2:DaemonSet::kiam-agent failed, signalling cancellation
I0314 10:22:16.935938   42599 plan_executor.go:180] planExecutor.Execute(...): context finished: context canceled
I03
```

**Comment by hausdorff** [comment]
Hmm, actually I think we don't have enough data to understand this bug. @adaniline-traderev did this produce an error at the end of the `pulumi up`? If so please paste that, the logs are not enough context to understand this error.

**Comment by adaniline-traderev** [comment]
Yes, this was result of `pulumi up`. I will try to reproduce it, but it was gone after I destroy the stack and created it again. From the log that pasted in the issue, it looks like this originates from helm component.
I deployed stable/kiam chart, and then updated values to remove some annotation on the pod, ran pulumi up , and this error happened.
