### ISSUE TITLE
Example Analyzers

### ISSUE THREAD

**Issue by gwkunze** [pulumi/pulumi#2562]
I saw the analyzer option in the CLI, but as of yet through my Google-ing I haven't been able to find either documentation on how to implement them or any existing analyzer / example. Is there a list of analyzers or a reference implementation somewhere?

**Comment by d-nishi** [comment]
@gwkunze this was a prototype. We’re hard at work on productizing it now. Can we include you on early access to the WIP implementation -- would love your feedback? If you have any thoughts on what could be useful for you to look at that would be great input as well. 

/cc @hausdorff @lukehoban

**Comment by gwkunze** [comment]
We're still in the process of evaluation Pulumi but I'd definitely be willing to give feedback on the subject. We have something related currently on our CloudFormation stacks which creates a changeset examines the changeset where it has a certain number of whitelisted "safe" operations that get auto-approved while others flag the change for human review.

**Comment by d-nishi** [comment]
That’s fantastic! 

Also would love to know what it would take to get you to cross the eval stage with Pulumi! Are you on our community slack? Would be excellent to get your brain dump on a call!

**Comment by lukehoban** [comment]
This shipped as part of Pulumi’s policy as code offering (CrossGuard). See https://www.pulumi.com/docs/guides/crossguard/.
