### ISSUE TITLE
Allow dot notation in `pulumi stack output`

### ISSUE THREAD

**Issue by rosskevin** [pulumi/pulumi#2566]
As I get more fluent with pulumi, I am creating more `Component`s for reuse. While this is not a barrier for reuse with other stacks, it is a barrier when we need to cross the boundary to other cli tools such as `gcloud`.   Object based component outputs need to be flattened to reuse via cli.

In order to use the `secret` from the following, I have to export the `secret` directly (and name it uniquely), breaking encapsulation, lengthening the external name and in-general making it less-nice to use. 

One such example is:

```ts
export class Identity extends ComponentResource {
  public account!: gcp.serviceAccount.Account
  public key!: gcp.serviceAccount.Key
  public secret!: Output<string>
}

// usage
export const ci = new Identity(...)
```
which wraps our creation/handling of each of our identities.

In order to `gcloud auth activate-service-account --key-file`, I'd like to pull the secret with `pulumi stack output ci.secret`, but instead I'll have to:

```ts
// usage
export const ci = new Identity(...)

export const ciSecret = ci.secret
```

Not a big problem, but does seem like it should be unnecessary.  Adding dot notation to the `pulumi stack output` command would allow programmed outputs to be unique/non-duplicative and object oriented.

**Comment by pgavlin** [comment]
This is an interesting suggestion, especially as we will be exposing such Javascript-style paths in more places in the coming months. For now, I _think_ you could work around this by invoking `pulumi stack output --json` and piping the output through an appropriate `jq` command.

**Comment by rosskevin** [comment]
I've been using jq, and I ended up using more of jq's features, which leads me to consider that this might be unnecessary scope creep for pulumi. I'm ok if this is closed without implementation, up to you.

**Comment by pgavlin** [comment]
Thanks, @rosskevin! I will close this for the time being.
