### ISSUE TITLE
Provide a good error message when users run `node program.ts`/`python program.py`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2580]
Pulumi programs currently cannot be run directly via the underlying runtime (`node` or `python`), and must be instead launched indirectly via `pulumi up` and related commands.  

We should provide a helpful error message for users who try to run directly with `node` or `python`.

Note that this is somewhat related to https://github.com/pulumi/pulumi/issues/2287 which will involve enabling source programs to actually control pulumi deployments - and may actually lead to making `node program.ts` "work" in a meaningful way.  But we will design that experience separately.  For now we should just report a good error message.

**Comment by lukehoban** [comment]
We do provide good errors here in all runtimes now - for example:

```
pulumi.errors.RunError: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
```

**Comment by paul-hammant** [comment]
> We do provide good errors here in all runtimes now - for example: <snip/>

A good example would direct the user to something actionable. Like a) an alternate command. Or to a b) web-page that has and alternate command and a rationale. Without that ppl are directed to use google "re-run using the `pulumi` CLI" which doesn't drive people to (a) or (b)

**Comment by mathieusama** [comment]
I'm my case I got that message (`pulumi.errors.RunError: Program run without the Pulumi engine available; re-run using the 'pulumi' CLI`) for a totally different reason, which was quite confusing.  After a lot of investigation and experimentation, I finally understood that the error was triggered by accessing pulumi config from within a Dynamic Provider (which I understand runs in an isolated context, so probably doesn't have access to config?). So I figured I would fetch the config from outside the provider and pass it into the provider as input. That fixed the issue, however I consider the message to have been more misleading than anything, in my case. IMHO, that use case should be discriminated to provide a more helpful message.

**Comment by boillodmanuel** [comment]
Thanks a lot @mathieusama, I'm in the exact same case than you.

**Comment by MichaelBauerLHIND** [comment]
we have the same problem with the pulumi.Config(). I cant use Quokkajs to debug my index.ts if i use the Config call.

**Comment by allen-munsch** [comment]
I have a discussion and question thread here about general usage and actionable items from this good message.

- https://github.com/pulumi/pulumi/discussions/9405
