### ISSUE TITLE
update hangs up on Cloud.Task creation

### ISSUE THREAD

**Issue by aprooks** [pulumi/pulumi#2597]
`pulumi update` hangs up and goes to an endless loop (at least in web logs)

see https://gist.github.com/aprooks/4c1b5cbd50c54d212756445cba54de07 

```
// task
const dbMigration = new cloud.Task("dbmigration", {
    build: "./Db"
});
```

```
pulumi version
v0.17.2
```

packages
```
{
    "name": "aws-typescript",
    "devDependencies": {
        "@types/node": "latest"
    },
    "dependencies": {
        "@pulumi/aws": "latest",
        "@pulumi/awsx": "^0.17.2",
        "@pulumi/cloud-aws": "^0.17.0",
        "@pulumi/pulumi": "latest"
    }
}
```

**Comment by lukehoban** [comment]
@aprooks I can't see where in the log you link to you are seeing an endless loop (the update appears to end cleanly), and I can't reproduce with my own example doing the same as you have in your code sample above.

Could you share more details?

**Comment by aprooks** [comment]
I've aborted it with ctr-c. With other attempts waited up to 40 minutes and image was never created in ECR. I will try to make a public reproducable script

**Comment by aprooks** [comment]
sorry, seems like I've had seem to have been hit by slow internet, and the fact that docker logs are appended as a snapshot to the main log stream.
