### ISSUE TITLE
Digitial Ocean and/or Linode Provider

### ISSUE THREAD

**Issue by retr0h** [pulumi/pulumi#2598]
Any chance of a Digital Ocean and/or Linode provider in the works?  If not, could you provide details on creating a new provider?  I would love to help, initially with python bindings.

My apologies for submitting an issue against this repo.  There is not a pulumi_digital_ocean repo to submit issues against.

Thanks -
John

**Comment by lukehoban** [comment]
There's been some work on both of these - and thanks for opening an issue to track these!

There's been work on https://github.com/displague/pulumi-linode by @displague, we're working with him on a plan for bringing that over as an official Pulumi provider.

And there are two Digital Ocean providers: https://github.com/jen20/pulumi-digitalocean by @jen20 and https://github.com/jaxxstorm/pulumi-do by @jaxxstorm.  We'll be looking to bring one of these over to be an official Pulumi provider soon too, but you can use either of these yourself already today.

**Comment by retr0h** [comment]
Thanks @lukehoban.  Are there any docs on creating new providers?  I see `pulumi-linode` was mostly generated by tfgen.  Are there any docs on how to create a provider from scratch, since bridging terafaform looks to be the "easier" approach.

**Comment by lukehoban** [comment]
Several of these were generated from https://github.com/pulumi/pulumi-tf-provider-boilerplate which includes pointers on the steps needed to create a Pulumi provider from an existing Terraform provider..

**Comment by clstokes** [comment]
@retr0h these are both now available and published.

https://github.com/pulumi/pulumi-digitalocean
https://github.com/pulumi/pulumi-linode

API docs are published at https://pulumi.io/reference/pkg/.
