### ISSUE TITLE
Expose query primitives on top of stack snapshot

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#2601]
Following on from #2600: once it is possible to retrieve a state snapshot for an arbitrary stack, we can build primitives that make it easy to query resource states.

In the [features/admission-policy](https://github.com/pulumi/pulumi/tree/features/admission-policy) branch, you can see a prototype implementation of this feature. The end goal of this is to expose a `list` method that enumerates all resources of some type from a "data source" (more on this in a second). In particular, we will expose this capability, plus a "data source" for state checkpoints (per #2600). The goal is to allow these query capabilities *across every resource type, across all our SDKs*.  Something like:

```typescript
k8s.apps.v1.Deployment
    .list({ context: pulumi.runtime.getCheckpointListContext() })
    .forEach(d => console.log(d.metadata.name))
```

There are two parts to this:

## "Untyped" core enumeration context

This part exists in pulumi/pulumi, and is made available to all resource providers (_e.g._, Kubernetes, AWS).

The core of the query model depends on a notion of a `ListContext`, which will enumerate resources of some type from a data source (_e.g._, in this case the state checkpoint of a stack). The code will look vaguely like this, with `EnumerablePromise` being a `Promise` that has query operators built onto it.

```typescript
class CheckpointListContextImpl implements query.ListContext {
    public list(args: query.ListArgs): rxjs.Observable<any> {
        return EnumerablePromise
            .from(getStackState(args.stack).then(o => Object.values(o.outputs)))
            .mergeAll() // Flattens EnumerablePromise<T[]> -> EnumerablePromise<T>
            .filter(isType(args.type));
    }
}
```

## Typing layer

This next part part is implemented in the SDKs for individual resource providers (_e.g._, Kubernetes, AWS), and is hence out of scope for the issue as it exists pulumi/pulumi. It will look conceptually like this:

```typescript
export class Deployment extends pulumi.CustomResource {
[...]
    public static list(
        ctx: pulumi.query.ListContext,
        args?: pulumi.query.ListArgs,
    ): rxjs.Observable<outputApi.apps.v1.Deployment> {
        return ctx.list({ ...args, type: "kubernetes:apps/v1:Deployment" });
    }
[...]
}
```

**Comment by hausdorff** [comment]
Following up #2649, which implements a simple `EnumerablePromise` model, it seems now that there is a simpler and more lightweight way to build out the "typing" layer. I talked to @lukehoban offline, and we've agreed to proceed with this direction first, possibly adding the `list`-style typing later. But, we believe that this new proposal is as convenient, and involves things we'd want to do anyway.

The idea is to make use of [user-defined type guards][tg] to provide a well-typed query interface. A resulting query (still using the `EnumerablePromise` model would look something like:

```typescript
const publiclyExposed = await pulumi.runtime
    .listResourceOutputs(k8s.core.v1.Service.isInstance)
    .filter(svc => svc.spec.type === "LoadBalancer");
```

The "trick" here, which is a bit subtle, is that the `svc` parameter of the `filter` call must be the `Service` type, which is not automatically inferred by the compiler.

Using the user-defined type gaurd `Service.isInstance`, we can easily achieve this with code along the following lines:

```typescript
export function listResourceOutputs<U>(typeGuard: (o: any) => o is U): U { ... }
```

Then for each `CustomResource`, we would implement the `isInstance` call such that:

```typescript
export class Service extends pulumi.CustomResource {
[...]
    public static isInstance(o: any): o is Service { ... }
[...]
}
```

[tg]: https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards

**Comment by hausdorff** [comment]
Ok, now that #2667 is about to close #2600, this leaves the following work on this issue:

- [ ] Rebase #2630 on top of the changes in #2667.
- [ ] Plumb the type guards work above through the AWS, Azure, GCP, and Kubernetes providers.
- [ ] Address comments in #2630 (mainly around the implementation of `EnumerablePromise`).
- [ ] Implement similar interfaces in Python and Go.

**Comment by hausdorff** [comment]
Ok, we've made the progress we said we'd make in M23. The only thing we said we _wouldn't_ do is to build out the Python and Go versions of this API -- and we didn't. So I'm going to remove the milestone until we have a concrete plan for those.

**Comment by lukehoban** [comment]
Closing out as we did complete this work - we'll track the follow-ups in other issues.
