### ISSUE TITLE
"could not read plugin [...] stdout: EOF" if `Pulumi.yaml` in parent dir

### ISSUE THREAD

**Issue by Dominik-K** [pulumi/pulumi#2607]
If the file `Pulumi.yaml` is missing, `pulumi up` returns this spurious error message:

> Diagnostics:
  pulumi:pulumi:Stack (pulumi-test-pulumi-test):
    error: It looks like the Pulumi SDK has not been installed. Have you run npm install or yarn install?
>
> error: failed to load language plugin nodejs: could not read plugin [/usr/local/bin/pulumi-language-nodejs] stdout: EOF

Tested with Pulumi version `0.17.4` (via Homebrew).

## How to reproduce
* `mkdir /tmp/pulumi-test && cd /tmp/pulumi-test`
* `pulumi new typescript`
	* just type "Enter" every time
	* On "Previewing initial update ...", choose "no".
* `mv Pulumi.yaml /tmp`
* `pulumi up`

## Related
* #2387 (maybe)

**Comment by ellismg** [comment]
When `pulumi [up | preview | destroy | refresh]` are run, the CLI needs to establish the root of the project.  It does this by looking for a `Pulumi.yaml` file in the CWD, and if that fails, walks upwards.  Once that is found, that directory is used as the current working directory for the update itself (`Pulumi.yaml` may optionally contain a `main:` entry that allows you to point at a different location for where to invoke the language host from).

The general problem here is that by moving the `Pulumi.yaml` file up a level, you've signaled that's the root of your project, but it really isn't.

The behavior you see in this case looks like this:

```
[matell@matell tmp.GGsrxF3jrW]$ pulumi up
Please choose a stack, or create a new one: dev    # (<---NOTE: you have to pick a stack again because we use the location of the Pulumi.yaml file as the key for what stack is active)
Previewing update (dev):
     Type                 Name                Plan     Info
     pulumi:pulumi:Stack  tmp.GGsrxF3jrW-dev           1 message
 
Diagnostics:
  pulumi:pulumi:Stack (tmp.GGsrxF3jrW-dev):
    error: It looks like the Pulumi SDK has not been installed. Have you run npm install or yarn install?
 
error: failed to load language plugin nodejs: could not read plugin [/home/matell/.pulumi/bin/pulumi-language-nodejs] stdout: EOF
```

I believe that the error message could be improved here (in an ideal world we wouldn't show any of the table output until after the language host has started to execute, and we'd instead just print an error message saying we failed to execute your program) but the behavior here today is an outcome of the separation of concerns between the CLI, Engine and Language Hosts.

I'm removing this from Q3 consideration.  The experience is not great, to be sure, but I suspect that few will hit this case in general.

**Comment by Dominik-K** [comment]
@ellismg 
> The experience is not great, to be sure, but I suspect that few will hit this case in general.
You're right. It's not that important. I close this issue and we can reopen it when we see that other experience that strange error message, as well.
