### ISSUE TITLE
Create a pulumi provider to manage pulumi

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi#2617]
I'm working on integration pulumi into slack and need to create a webhook for that.

It would be nice if I could manage the pulumi webhooks in code via pulumi itself.

**Comment by mastoj** [comment]
Is there any progress on this? I was thinking more than just webhooks. Like, creating users and tokens and such :).

**Comment by LouisAmon** [comment]
@stack72 is this even in the roadmap ?

Would be pretty handy for webhooks, tokens, GitHub & Slack integration, SAML, RBAC…

**Comment by RobbieMcKinstry** [comment]
This issue is not currently on the roadmap, but we're doing a lot of work to make provider maintenance less tedious. If we can land provider upgrades more swiftly, we can support a greater number of providers. A `pulumi-native` provider would be a good candidate IMO.

**Comment by lukehoban** [comment]
The Pulumi Service provider was released last year. Among other things, it supports managing Webhooks.

https://www.pulumi.com/registry/packages/pulumiservice/

https://www.pulumi.com/blog/announcing-pulumi-service-provider/

**Comment by RobbieMcKinstry** [comment]
TIL!
