### ISSUE TITLE
Support root level package.json, tsconfig.json, etc.

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi#2619]
It would be great if pulumi would have some better support for monorepos. For our case, we have a single `infrastructure` repo that contains everything. Rather than having a `package.json`, `node_modules`, `tsconfig.json`, etc. in every pulumi project directory, it would be great if `pulumi new` and such would support this out of the box.

**Comment by lukehoban** [comment]
I definitely want to solve for this.  I suspect Node.js will put some limits on what we can do here - and most of this is related to Node.js project structure which Pulumi builds on top of.

But certainly having guidance on what the best options are for sharing these files in large projects is something we need to do.

**Comment by nesl247** [comment]
We actually already share some of it, by removing `package.json`, `tsconfig.json`, `node_modules`, etc. from the project directory.

What we do instead is to import pulumi via:

`import * as pulumi from '@pulumi/pulumi';`

**Comment by ellismg** [comment]
@nesl247 Can you share with me a small outline of what your monorepo looks like (from the filesystem point of view)?  Since you say you don't have a package.json in each module, I am guessing that you are not using something like lerna or yarn workspaces.  What does each individual project folder end up looking like?  Do you just have a bunch of modules with their own `index.ts`'s but they are all in the same package as far as node is concerned?

**Comment by nesl247** [comment]
Hi @ellismg,

Sure, no problem.

```
- /
  - node_modules
  - tsconfig.json
  - package.json
  - yarn.lock
  - applications/
      - application1
          - Pulumi.yaml
          - index.ts
  - networks/
      - vpcs/
          - index.ts
```

Correct, we are not using lerna or yarn workspaces.

**Comment by swgillespie** [comment]
Related: https://github.com/pulumi/pulumi/issues/2608

**Comment by Offtree** [comment]
Running into issues with this while trying to work with a monorepo maintained using [@nrwm/nx](https://github.com/nrwl/nx).

App Structure
```
- /
  - node_modules
  - tsconfig.json
  - package.json
  - yarn.lock
  - apps/
      - api/
          - foo-bar-svc/
              - Pulumi.yaml
              - index.ts
              - tsconfig.json
              - etc... // However there's no package.json in the nested directories.
``` 

Running `pulumi up -C ./apps/api/foo-bar-svc` returns an error when using inline functions for lambdas.

Example:
```
// ./apps/api/foo-bar-svc/index.ts

// Errors
const api = new awsx.apigateway.API("api", {
  routes: [{
    path: "{proxy+}",
    method: "ANY",
    eventHandler: (c, e, a) => {
      console.log("test")
    },
  }],
});
```
Ouput:
```
Previewing update (dev):
     Type                                Name                  Plan       Info
     pulumi:pulumi:Stack                 foo-bar-svc-dev                   1 error
     └─ aws:apigateway:x:API             api                              
 +      ├─ aws:iam:Role                  api3afd83ba           create     
 +      └─ aws:iam:RolePolicyAttachment  api3afd83ba32be53a2-  create     
 
Diagnostics:
  pulumi:pulumi:Stack (foo-bar-svc-dev):
    error: Error: Error reading file '/path/to/app/apps/api/foo-bar-svc/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open '/path/to/app/apps/api/foo-bar-svc/package.json'
        at readFile (/path/to/app/node_modules/@pulumi/pulumi/runtime/closure/codePaths.js:167:19)
        at computeDependenciesDirectlyFromPackageFile (/path/to/app/node_modules/@pulumi/pulumi/runtime/closure/codePaths.js:150:22)
        at /path/to/app/node_modules/@pulumi/pulumi/runtime/closure/codePaths.js:115:36
        at /path/to/app/node_modules/read-package-tree/rpt.js:162:20
 ```

I can work around this by not using inline lambdas for now though, but that means missing out on a lot of the goodness that  pulumi provides over something like terraform, serverless, and others.

**Comment by ringods** [comment]
Related: #4349

**Comment by frosas** [comment]
I had the same issue with JS closures as @Offtree.

According to https://github.com/pulumi/pulumi/blob/9b980c1/sdk/nodejs/runtime/closure/codePaths.ts#L169, package.json is expected to be in the CWD. Same with node_modules.

I guess ideally Pulumi would traverse the parent directories until a package.json is found.

In any case, symlinking those files did the trick:

```bash
$ tree infra
infra
├── Pulumi.prod.yaml
├── Pulumi.yaml
├── index.ts
├── node_modules -> ../node_modules/
└── package.json -> ../package.json
```

**Comment by mdhornet90** [comment]
Chiming in that I'm running into the same issue as the last couple of posters. It's seems Pulumi assumes my infra project would never have its own `src` folder, so trying to use a magic function is broken with the following error:

```
Error reading file '/backend/infrastructure/src/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open '/backend/infrastructure/src/package.json'
```

Are there plans to address this?

**Comment by MichaelHirn** [comment]
@frosas Thanks for your symlink tip. Do you know what pulumi version you are using to get this working?

With `pulumi@v2.21.2` and `ln -s ./package.json ./infra/package.json` I'm getting `Error: ELOOP: too many symbolic links encountered`.

**Comment by achaphiv** [comment]
To anyone else stumbling on this issue, it's possible to use the automation API to accomplish this.

You will lose the ability to use the `pulumi` binary directly (as well as colorized output), but everything can be configured programmatically.

**Comment by nesl247** [comment]
It's been a long time since I opened this up, but I've actually had no problems having root level `package.json`, `tsconfig.json`, etc. This ticket's intention was specifically about `pulumi new` and it not creating these files when they exist at the root level.

**Comment by achaphiv** [comment]
Hmm, I thought the point was to have multiple stacks with a shared `node_modules/` and friends.

So how do you differentiate something like `pulumi up -s dev` from `pulumi up -s prod`?

**Comment by nesl247** [comment]
We actually don't change the infrastructure code per environment, in fact, I highly recommend you don't. Instead, I recommend you make any differences configurable via configuration file.

Our layout is as described in https://github.com/pulumi/pulumi/issues/2619#issuecomment-479618454

**Comment by renehauck** [comment]
I have another workaround: Simply create a fake package.json in the respective subfolder that contains the pulumi files:

```json
{
  "name": "fake",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {},
  "private": true,
  "dependencies": {},
  "devDependencies": {
    "@pulumi/aws": "^4.8.0",
    "@pulumi/awsx": "^0.30.0"
  }
}
```

**Comment by RobbieMcKinstry** [comment]
Related to https://github.com/pulumi/pulumi/pull/11045

**Comment by sarink** [comment]
So if you don't put pulumi's `index.ts` and `tsconfig.json` in the root of you repo, you can't use pulumi? This is kind of absurd

**Comment by RobbieMcKinstry** [comment]
To give an update on this issue, we should be able to close this with https://github.com/pulumi/pulumi/pull/11045 . This PR will look up the directory hierarchy to find `package.json` and use that as the project root. I expect TSConfig to be picked up in addition to `package.json`, though I haven't tested it.

Right now, #11045 is moving very sluggishly, but it's close to finished. I've spent quite a bit of time using different testing approaches, all of which have proven difficult.

**Comment by RobbieMcKinstry** [comment]
https://github.com/pulumi/pulumi/pull/12759 adds support for root-level package.json and node_modules, but not explicitly `tsconfig`.

**Comment by RobbieMcKinstry** [comment]
Took a second look at adding support for TSConfig, and I've decided to open a new issue to track that separately from this issue, primarily because there are different design constraints. https://github.com/pulumi/pulumi/issues/12780 describes the problems unique to `tsconfig.json` and lists a few approaches to adding support for loading it from a parent directory. I expect we will resolve it soon as part of our monorepo support epic.

**Comment by RobbieMcKinstry** [comment]
This issue has been closed by #12759, which adds support for `package.json` files above the Pulumi project root. 

Please see https://github.com/pulumi/pulumi/issues/12780 to information on root-level `tsconfig.json` options. I'd love to get some feedback from the community on our approach! :D

**Comment by justinvp** [comment]
Unfortunately, we found the change results in an error if `main` in `package.json` references a file that doesn't exist. We're temporarily reverting the change and plan to re-introduce it soon.

**Comment by geekflyer** [comment]
hey folks. Any estimate on when a new fix for this issue is coming? We already started relying on the new package.json lookup behaviour introduced in https://github.com/pulumi/pulumi/pull/12759 in our codebase and are currently in a dilemma where we can't upgrade @pulumi/pulumi due to the revert in https://github.com/pulumi/pulumi/pull/12944.

**Comment by justinvp** [comment]
@geekflyer, apologies for the revert and long delay! A new PR is open https://github.com/pulumi/pulumi/pull/13273 which addresses the issue from the previous attempt.
