### ISSUE TITLE
Expose provider functions in a more pleasant fashion

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#2621]
Currently, our provider functions are shaped like so:  `function getSomething(someArgs: Args, ...): Promise<SomeResult>`.  

For example: 

```ts
export function getLogGroup(args: GetLogGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetLogGroupResult> {
    return pulumi.runtime.invoke("aws:cloudwatch/getLogGroup:getLogGroup", {
        "name": args.name,
    }, opts);
}
```

Being async/Promise-returning is actually pretty unpleasant for consumers.  It forces asynchrony where it may not be desired, and it often required either `await`ing (or `then`ing) the promise to get the real data that is in the Result type.

We should explore a few of ways of trying to improve this.

1. we may be able to find a way to do the "proxy lifting" approach we took with Outputs here.  effectively, making it possible to do `getLogGroup(...).arn` which would give you a `Promise<string>` back instead of having to do `getLogGroup(...).then(r => r.arn)`.   This would make things nicer, but carries risk as it's unclear how happy node will be with the mix of Proxies+Promises.

2. We investigate means to make these functions *synchronous*.  Right now, they're only async because we depend on grpc, and that is only async in Nodejs.  However, there are (admittedly hacky) libraries out there that provide a native node component which then allows you to synchronously block on async work.  For example, there https://github.com/abbr/deasync package (whose code is extremely simple) enables blocking on async work by way of natively pumping under the covers until the async work completes.   This would allow us to have a much nicer exposed function model for users, but would open us up to the risk of this maybe not working in a future version of node.  It also brings back a dependency on native code.

**Comment by CyrusNajmabadi** [comment]
Tagging @lukehoban

**Comment by clstokes** [comment]
I frequently have to re-lookup how to handle function results differently than resource outputs. It will be great to get the dev experience of the two as similar as possible. 👍

**Comment by CyrusNajmabadi** [comment]
FYI, the deassync approach works.

**Comment by pgavlin** [comment]
> FYI, the deassync approach works.

This turned out to not work in the long term. `deasync` causes too much instability in the Node runtime by introducing synchronous operation where it is not expected. Provider functions are synchronous in other languages.
