### ISSUE TITLE
Support PULUMI_STACK_NAME env variable.

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#2626]
We should support a `PULUMI_STACK_NAME` environment variable as input to `up`, `preview`, etc. operations allowing users to skip the `pulumi stack select ...` step. This will simplify CI/CD integrations and other automation.

**Comment by ellismg** [comment]
We already have the `-s` option.  Is this not sufficent?

**Comment by clstokes** [comment]
That is indeed sufficient - was unaware of that option. Thanks. Closing.
