### ISSUE TITLE
Emit outputs as environment variable script

### ISSUE THREAD

**Issue by jeshan** [pulumi/pulumi#2632]
Currently, we can export stack outputs as json.
I'm suggesting we can add another option, i.e outputting in a format suitable for a shell script.

Example: I have a stack that outputs
```json
{
  "my_site": "https://mysite.cloudfront.net",
  "cloudfront_id": "E13TUXGZKWDAAA"
}
```

It would be nice if I could export them as:
```
export my_site="https://mysite.cloudfront.net"
export cloudfront_id="E13TUXGZKWDAAA"
```
We would then write this in a shell script:
`$(pulumi stack output --env-vars)`
This will make it really easy to proceed in a script, e.g invalidate a cdn cache after pulumi deploys website assets.

**Comment by zerda** [comment]
I've googled same question, turn out `export CLOUDFRONT_ID=$(pulumi stack output cloudfront_id)` should work.

See documetation https://www.pulumi.com/docs/reference/cli/pulumi_stack_output/

**Comment by martinkearn** [comment]
@zerda ... where do you put that `export` code? Also, do you know how this would look in C#? 

I'm trying to do the same thing; export a connection string as an environment variable so an integration test further down the pipeline can use it (Github actions in my case)

**Comment by justinvp** [comment]
Just curious, is there any prior art of other CLI tools outputting values in this format?

**Comment by abhinav** [comment]
Some tools that I can think of:

- [gimme](https://github.com/travis-ci/gimme): Travis CI's tool to install Go versions. Usage: `eval "$(gimme 1.19)"`
- [starship](https://starship.rs/) and [direnv](https://direnv.net/), although they expect to be put inside your shell configuration, not regular shell scripts
- [jq](https://stedolan.github.io/jq/manual/) supports a `@sh` modifier. That doesn't follow the eval rules. Instead, it expects to be used like `X=$(jq -r '... | @sh')`, which is comparable to our existing `X="$(pulumi stack output foo)"`.
- `go env` prints its output as a shell script by default. It can be `eval`ed if needed.

The `eval` form works well if there are a bunch of variables to write.
As a starting point for the above case, I can see something like the following working:

    eval "$(pulumi stack output --shell --shell-prefix=FOO_)"
    echo "$FOO_my_site". # https://mysite.cloudfront.net
