### ISSUE TITLE
Partial error can cause `up` to get wedged

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#2633]
Currently, when a user runs `pulumi refresh` and one or more resources are unhealthy, this will cause the `refresh` to return an error (_e.g._, "ReplicaSet failed to achieve availability requirements"; "Service targets 0 Pods; _etc_.).

Most of the time, this is fine, but under the following circumstances, it's possible to get wedged. A somewhat contrived, but vaguely realistic scenario:

* Say a `Deployment` is misbehaving somehow, and the user decides to run `kubectl delete` to kill it.
* Hoping to have Pulumi re-created it, they run `pulumi refresh` in an attempt to get Pulumi to acknowledge that it no longer exists.
* `pulumi refresh` will fail, because the `Service` targeting it no longer targets live `Pod`s.

It is possible, but quite unwieldy, to unblock oneself by editing the statefile. Furthermore, there is no particular reason why `refresh` should _fail_ versus:

1. Warning the user that a resource has been observed to be in an unhealthy state.
2. Presenting this as an error during the next `pulumi up`, as we do now.

There is also no particular historical reason why we did it this way. When @pgavlin instigated the "fixing `refresh`" work, the status-rich updates had _just_ landed, and the experience was just starting to become "good." The refresh stuff was sort of tacked onto this, and really only represented our guess about what users would expect.

Finally, because we at Pulumi essentially _never_ use `kubectl` (or Helm) to edit Kubernetes config, this decision was simply never revisited. But this is not the way that every shop works, and it's clearer now that for some places, this is a big deal.

**Comment by hausdorff** [comment]
Oh lol, I had forgotten about this issue: https://github.com/pulumi/pulumi/issues/2352

I do point out something useful, which is that having `refresh` return error code > 0 is useful for scripts when a resource is unhealthy. I suppose that the question is what the default should be.

**Comment by joeduffy** [comment]
I am a *huge* fan of what you say, Alex: (1) warn if resources are unhealthy, but (2) do not block the refresh on them. Provided the next time a deployment occurs, the error surfaces, as you say it will.
