### ISSUE TITLE
Support marking a resource for replacement

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2643]
We should have a CLI command that lets you mark a resource for replacement upon the next deployment. This can be used when, for example, a VM gets wedged and needs to be recreated.

**Comment by melbourne2991** [comment]
Yes! I'm writing some integration tests at the moment and it would be great to be able to blast away DBs/stateful resources. Currently i'm spinning up and tearing down all the infra for each run but it's painfully slow :/

**Comment by lukehoban** [comment]
FWIW - This covers a similar use case to the `pulumi destroy -r <URN>` that was recently proposed and added to https://github.com/pulumi/pulumi/issues/2317.  We likely eventually want both, but the use cases seem to overlap a fair bit.

**Comment by lukehoban** [comment]
We added targetted update/refresh/delete in M27.   This ability to force replacement is the other key tool to allow for CLI driven workflows that work at the level of individual resource (in cases where the program itself cannot be cleanly deployed, or to limit blast radius).

**Comment by lukehoban** [comment]
Note that in the meantime - making a change to the program that triggers the replacement is a workaround here - and is almost always possible in some way that doesn't otherwise seriously impact the resource.  Changing the logical name is another similar option.

**Comment by pgavlin** [comment]
A slightly different approach--consistent with the approach we've taken to targeting--would be to add a flag to `update` that indicates the set of resources to replace. Would that fit the use cases for those of you tracking this issue?
