### ISSUE TITLE
Users with READ permissions sometimes get "not found" errors when they don't have permissions

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2645]
For some operations which require additional permissions beyond what READ users are granted, users can see error messages like:

```
no stack <stackName> found
```

For example, a READ user attempting to `pulumi config get ENV_VAR`.

We should present useful error messages indicating the specific permsisions that are required and missing instead of a "not found" error.

**Comment by chrsmith** [comment]
This has been fixed upstream, and will be deployed in tomorrow's release. The Pulumi API service will still return a 404 to not disclose the existence of a resource in many cases, however if you have _some_ access to a resource, but not specifically the permissions required, you will get a more descriptive 403.

For example, if you have `READ` access to a stack, but need `WRITE` to perform an update, you will now get a 403.
