### ISSUE TITLE
The same resource deployed with different first-class providers should have distinct URNs

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#2647]
In https://github.com/pulumi/pulumi-kubernetes/issues/520, a user pointed out that multiply instantiating the same Helm Chart with the same name on multiple clusters (using first-class providers) doesn't work, because Pulumi allocates them the same URN.

At its core, this is a naming issue: the user intuition is that the same resource deployed to different clusters _should be considered different resources_; implemented with first-class providers, Pulumi does not match this intuition, allocating them the same URN, which causes a collision.

I believe we should match the user intuition here -- if one resource is deployed through different first-class providers (_e.g._, the same Helm Chart is deployed to multiple clusters), then the URNs should be distinct.

For me, the question is what part of the stack is responsible for doing this naming. The two options on the table seem to be:

* **Implement this in the SDKs where appropriate.** Tactically this would mean that (_e.g._) `helm.v2.Chart`, `ConfigFile`, `ConfigGroup` and **all** Kubernetes resource implementations would have to somehow uniquely identify the provider, and put that information inside its own URN. Of course, this would also become a problem for many other providers that you'd expect to allocate resources to -- everything from Helm, to vSphere, to NewRelic.
* **Implement this in the engine.** This would do effectively the same thing (and possibly only affect Kubernetes resources at least until more providers come on board), but handle this transformation on behalf of the SDKs, such that no code changes are required from them.

Of these two options I greatly prefer the second, at least in the long term -- in the short term I think it's fine to make progress with shortcuts. To me, the problem of incorporating enough information into the resource URN to uniquely identify the provider seems challenging, and it's something that I honestly don't trust individual resource providers to do. It's also hard for me to think of a scenario where a first-class provider (even excluding Kubernetes) would _ever_ want URNs to collide in this way. The semantics of having separate resource providers seems to be inextricably linked to _provisioning resources separately_, and to have to re-implement these semantics in every resource type in every resource provider that allows first-class providers seems like a betrayal of the abstraction. It is my belief that this represents the intuition of effectively all of our user base, and _not_ baking this into the model is likely to shoot us again and again as other first-class providers come online.

All of that said, I am sympathetic to the arguments that: (1) we should be careful of the blast radius, and (2) the implications for downstream tooling are non-trivial. Another argument is that we munge URNs already in the `ComponentResource` class, though my opinion is that it would be better to _not_ do this in the SDK. There is some disagreement (per useful discussion with @swgillespie) that the same resource provisioned with different providers should be viewed as "differing in non-trivial ways" but I believe per the issue above we have some evidence that that's not how our users see it.

Thoughts? cc @lukehoban @joeduffy @lblackstone

**Comment by hausdorff** [comment]
It's worth noting that if we intend to complete the resource-aliasing work, it is likely that this (or something like it) would be a good candidate first "real" exercise of those code paths.

**Comment by lukehoban** [comment]
I will note that in general, we’ve been trying to go the other direction with URNs - embedding less information/magic in the construction of the URN and making it simpler and more user-understandable name. In fact, our ideal has been to get to a world where it is just `grandparentname/parentname/childname`  

The goal with that has been to encourage and enable component authors to do the work to (and be in control of) uniquely naming resources. 

It is not exactly clear to me why the provider input should become part of the URN. In principle, it is just one more input to the resource, and just like all the other inputs, should not determine the URN.

Components building children in behalf of a user will always need to ensure they don’t create duplicate names. The effectively required (though unfortunately not enforced) approach to this is to include a user-provided name prefix in front of the name of the child resource.

It seems that in this case, we are trying to avoid needing to take a user-provided name to distinguish things. In general, that is not possible on many/most APIs in Pulumi. For better or worse, it is necessary to have the user provide a name for each instance of a thing that it wants. 

I’ll have to look a bit deeper at the specific case here to see if there’s a deeper issue that makes this hard or unwieldy in this case.

**Comment by pgavlin** [comment]
I don't think that we're going to pursue this, so I'm going to go ahead and close this issue.
