### ISSUE TITLE
Feature request -- scripts written in typescript should be able to get a type-safe interface to pulumi stack output

### ISSUE THREAD

**Issue by breathe** [pulumi/pulumi#2660]
I'd really like to write scripts in typescript that do things with pulumi stack output -- but I don't want to manually invoke `pulumi config --json` and parse that json in a typeless way when I already have a typed version of those exports created during the stack definition process ...

With a simple stack like this:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const size = "t2.micro"; // t2.micro is available in the AWS free tier
const ami = "ami-01ac4e28da63bac3c"; // AMI for Amazon Linux in us-east-1 (Virginia)

const server = new aws.ec2.Instance("example", {
  instanceType: size,
  ami: ami,
});

export const publicIp = server.publicIp;
export const publicHostName = server.publicDns;
```

I'd like to do write code something like this:

someScript.ts
```
import * as pulumi from "@pulumi/pulumi";
import { publicHostName } from "./index";

// throw an error if the stack isn't already deployed and ensure that programmatic access to stack values are available 
pulumi.useDeployedStackWithConfiguration(
  "some-pulumi-config-selection"
);

// do something useful with stack output publicHostName
console.log(publicHostName.get());
```

or maybe like this

```
import * as pulumi from "@pulumi/pulumi";
import { publicHostName } from "./index";

const doUsefulWork = async () => {
   // do something useful with stack output publicHostName
   console.log(publicHostName.get());
}

// throw an error if the stack isn't already deployed and ensure that appropriate programmatic access to stack values is available 
pulumi.useDeployedStackWithConfiguration(
  "some-pulumi-config-selection",
  doUsefulWork
);
```

Is this already a feature in pulumi somehow -- the design looks like something like this should work to me ...

**Comment by breathe** [comment]
Just came across this post https://blog.pulumi.com/testing-your-infrastructure-as-code-with-pulumi

Looks like to do what I want I maybe could mock the PULUMI_NODEJS_STACK, PULUMI_NODEJS_PROJECT, and PULUMI_CONFIG environment variables as inside a test case ... ?

**Comment by gpduck** [comment]
@breathe did you ever get this to work using process.env to set the variables?  I'm trying to write a test that uses pulumi.config and it can't find the variable that I'm setting with process.env

**Comment by leezen** [comment]
You'll want to use StackReferences: https://www.pulumi.com/docs/intro/concepts/organizing-stacks-projects/#inter-stack-dependencies

Please re-open if that doesn't help you get you where you need.
