### ISSUE TITLE
Support paths in ignoreChanges

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2663]
In #2657 we added the ability to ignore change to top-level properties of a resource for the purposes of updates and deletes via the `ignoreChanges` resource option.

We should expand this to also allow specifying nested resources. This will likely require a custom path syntax to allow paths through JSON-like Pulumi resource objects/arrays.

**Comment by pgavlin** [comment]
This should use the path syntax introduced by detailed diffs.

**Comment by pgavlin** [comment]
This is complete.
