### ISSUE TITLE
Implement `pulumi query`

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#2666]
Following up from #2600 and #2601 (which are about to be resolved with #2630), we'll need a standalone way to invoke queries. Discussing with @lukehoban and @ellismg (and per our design meeting) we've decided on the following:

* `pulumi query` will essentially exec a file using the language provider of choice, but with critical engine facilities (notable resource registration, most `Invoke`, _etc_) disabled.
* `pulumi up` will not be allowed to run the query API, particularly as it's not clear what this means when an update is ongoing.

Talking to Matt, and having spent quite a bit of time working with the engine, it seems like the safest path forward is to:

* write a `deploy.Source` for querying, and then change the resource monitor to error out any time `RegisterResource`, `RegisterResourceOutputs`, `ReadResource`, or most uses of `Invoke` are called when in "query mode"
* set up the `Source` evaluation to produce 0 goal states
* _do not_ set up the engine to talk to the service backend in "query mode"

cc @swgillespie

**Comment by ellismg** [comment]
> set up the Source evaluation to produce 0 goal states

We do need to ensure that if we do this, the engine understands that zero goal states being produced does not mean that it should go destroy resources.

**Comment by hausdorff** [comment]
Hmm, shouldn't that be solved incidentally by preventing _any_ resource operations when the engine is in "query mode"?

**Comment by swgillespie** [comment]
> Hmm, shouldn't that be solved incidentally by preventing any resource operations when the engine is in "query mode"?

I don't think so - running an empty program produces zero goal states and zero resource operations, but as Matt points out the engine will try to delete everything because the lack of resource operations implies that there are no resources.

**Comment by swgillespie** [comment]
By "preventing resource operations" do you mean "the engine will try to delete stuff, but something will prevent it from doing so"?

**Comment by hausdorff** [comment]
Yep, that's what I mean.

Ok, after a solid day of work, I think `pulumi query` is starting to limp along. At this point, it basically looks like an exec of a node process with some access to things like stacks, the stack resources, and that sort of thing -- still in the pulumi app's `index.ts`, but that will soon change. We successfully load the language plugins, execute the Pulumi app's `index.ts`, and purposefully fail all resource operations, so we ensure that you can't run an update at the same time as a query. We also purposefully display the output as we normally would, rather than via the "update" CLI UI -- and additionally, this information is NOT sent to the service.

Things that I know for sure are left (_i.e._, might be not exhaustive):

* Don't actually start an update when we run `pulumi query`.
* Take a file on the command line instead of the ambient project.
* Disallow the query capabilities during a `pulumi up`.
* Make the code actually ready to ship (it's not prod-quality).

Particularly because of the last point the code is definitely prototype quality, but for those of us following alone at home, you can see the branch [here](https://github.com/pulumi/pulumi/tree/hausdorff/query-cmd). This isn't anything particularly special, but you can see that the approach is to start with the same code as `up`, and start whittling away at it until it's what we want for `query`.

**Comment by hausdorff** [comment]
I actually just opened as WIP PR to show where it's at but you have been warned: this code is not even close to ready yet, but it's nice to get it out in the open for thoughts.

**Comment by hausdorff** [comment]
Regrouping with @ellismg and @swgillespie, we've agreed on the general approach. In particular:

* `pulumi query` should not be updated as an update (as, _e.g._, `refresh` and `up` are)
* `pulumi query` should instead directly use a simplified version of source eval that simply invokes the language plugin and signals on completion (_i.e._, does not `Iterate`)
* `pulumi query` should not use the engine, but should (eventually) use the provider registry directly. (The language hosts are a separate path provided by the source func/source eval mentioned earlier)

**Comment by hausdorff** [comment]
Alright, here is the work that we know we have ahead:

- [x] Remove dependency on plan and step executor
- [x] Remove dependency on the infrastructure for updates (_i.e._, don't re-use `refresh` or `up` codepaths)
- [x] Write a "naked" language host (_i.e._, one that boots without `source_eval.go` _etc_.)
- [ ] Remove the dependency on the engine.
- [ ] Clean up everything and make it ready for prod.

As you can see, we have 1 major piece of work left, that we know of. If you want to track the progress, you can have a look at the WIP PR above.

**Comment by hausdorff** [comment]
Alright, as you can see in the newly-pushed code in the branch above, we've (mostly) removed the dependency on engine constructs. `query` mode now exists in a "parallel universe" to `up`, with dependencies on critical update infrastructure removed (including step execution, starting updates with the service, and so on). This mitigates most of the risk of the feature, so we're starting to get close, I think.

The code has also been greatly simplified from the prototype. We've mostly removed things that `up` needs but `query` doesn't, so it's also starting to get into tractable reviewable shape.

I believe we will have a PR our very soon.

**Comment by hausdorff** [comment]
Closed with #2667.
