### ISSUE TITLE
Add the ability to create a new pulumi project in a non-empty directory

### ISSUE THREAD

**Issue by aydrian** [pulumi/pulumi#2671]
Currently, if you try to run `pulumi new` in a non-empty directory, you receive the following error:
```
error: /Users/aydrian/Developer/gatsby-site-test is not empty; rerun in an empty directory, pass the path to an empty directory to --dir, or use --force
```
There are some serverless cases were it would be helpful to be able to create a pulumi project in a non-empty directory.
- after generating a static site e.g. [GatsbyJS](https://www.gatsbyjs.org)
- after generating a front end site e.g. [Create React App](https://github.com/facebook/create-react-app)

My work around is to not use `pulumi new` and manually create the `Pulumi.yaml` and `index.js` files and run `pulumi stack init <stack_name>`. This works but it would be nice to have the prompts for creating the yaml file.

**Comment by justinvp** [comment]
Just a note: The `--force` flag can be used with `pulumi new` to force it to work in a non-empty dir.

**Comment by justinvp** [comment]
And for reference, here's some background on why we current error on non-empty directories: https://github.com/pulumi/pulumi/pull/1810 and https://github.com/pulumi/pulumi/issues/1806. It may be worth revisiting now that we've resigned to always encouraging a `mkdir foo && cd foo` before `pulumi new`.

**Comment by lukehoban** [comment]
I think we can close this given that:
1. This is intentional (and reasonably common) to avoid significant confusion that alternatives cause
2. There is a workaround (`--force`)
3. The workaround is called out explicitly in the error message
