### ISSUE TITLE
Pulumi overrides tsconfig.json target

### ISSUE THREAD

**Issue by brandonbloom** [pulumi/pulumi#2673]
AWS Lambda supports new-enough node such that we don't need to transpile-away async/await, but Pulumi seems to force tsc to target "es6" (aka "es2015", I think) via ts-node.

For context: I am trying to debug some subtle issue and it was faster to iterate in the Lambda console, but the inversion of control created by the awaiter machinery is a pain to work with. I knew my tsconfig was set to the appropriate target, so I went spelunking and found where Pulumi is not respecting that.

As a component of a potential fix, change this line:
https://github.com/pulumi/pulumi/blob/70bc0436ed165ec1fbebdda33e033e71e1ae5aa7/sdk/nodejs/cmd/run/run.ts#L157
to target "es2018" and everything seemed to work as expected.

**Comment by lukehoban** [comment]
Interesting - I don't recall exactly why we hard coded this one in.  It would be nice to ensure that the `tsconfig.json` settings could be preferred over the defaults provided by Pulumi.  I seem to recall this was hard to do with `ts-node` though.

**Comment by ellismg** [comment]
At a minimum, for cases where `tsconfig.json` is next to `package.json` (i.e. the CWD we are going to execute in) we could read it and if it sets any fields, don't pass them to `ts-node` (since it will get them by reading the project, I believe).

**Comment by brandonbloom** [comment]
That seems like a good idea. Worth noting that if you're going to read `tsconfig.json`, you should handle the proper directory search, the `extends` key's behavior, its extended JSON-with-comments syntax, etc.

I've used https://github.com/TypeStrong/tsconfig for a quick and dirty tool before and it was OK, but has some weird shortcomings like choking on trailing commas where tsc does not. I think they call it `jsonc`. Might be a good starting point though.

**Comment by haohaolee** [comment]
Any update on this?
It feels a little bit annoying that you see complicated transpiled code when you check out the code uploaded in AWS console, it should be elegant since AWS has supported nodejs 12 runtime for a long time

**Comment by justinvp** [comment]
Fixed by #7068
