### ISSUE TITLE
pulumi stack ls incorrect

### ISSUE THREAD

**Issue by emalamisura-c2m** [pulumi/pulumi#2679]
I have two stacks in my dashboard, and pulumi stack ls only lists one of them.  Even if I add the other one manually, it still only lists one (which is not the current one). 

The one that is listed is a GCP stack.  The one that doesn't show up at all is a Kubernetes stack.

**Comment by chrsmith** [comment]
Hi @emalamisura-c2m , the behavior you are seeing may be by design. But let me explain:

When you run `pulumi stack ls`, it is automatically filtered to only include stacks with the same "Pulumi project" that are in your current directory (or a parent directory). So if the `Pulumi.yaml` is for project `website`, then `pulumi stack ls` will only show stacks for project `website`. (And not, any other stacks, e.g. `emalamisura-c2m/backend/dev`.)

If you run `pulumi stack ls --all` you should see all stacks, which should show you both.

If that doesn't explain the behavior you are seeing, or `pulumi stack ls --all` still only lists one of your stacks, but not both, please let me know. If it was just a matter of this implicit "project filtering", then we should keep this bug around, but to just make that more clear such as calling it out in the output of the command or something.

**Comment by AbhishekTripathi** [comment]
I have a similar situation but in my case `pulumi stack ls` and `pulumi stack ls --all` both return empty. I have logged in using `pulumi login --local`
```
pulumi stack ls --all
NAME  LAST UPDATE  RESOURCE COUNT
```
If I just do `pulumi stack` I get some output as below 
```
 pulumi stack
Current stack is nrdev:
    Managed by xxxx
    Last updated: 2 minutes ago (2019-11-08 22:09:02.3442582 +0100 CET)
    Pulumi version: v1.5.1
Current stack resources (4):
    TYPE                                           NAME
    pulumi:pulumi:Stack                            pulumitest-nrdev
    ├─ azure:core/resourceGroup:ResourceGroup      resourceGroup
    ├─ azure:storage/account:Account               storage
    └─ pulumi:providers:azure                      default_1_3_1

Current stack outputs (1):
    OUTPUT            VALUE
    connectionString  DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxxx;EndpointSuffix=core.windows.net

Use `pulumi stack select` to change stack; `pulumi stack ls` lists known ones
```
Current directory structure is as below
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        02-11-2019    20:20                node_modules
-a----        08-11-2019    21:41             23 .gitignore
-a----        08-11-2019    21:41            636 index.ts
-a----        08-11-2019    21:41            208 package.json
-a----        02-11-2019    20:20          82513 package-lock.json
-a----        08-11-2019    21:41             85 Pulumi.dev.yaml
-a----        08-11-2019    21:42            146 Pulumi.nrdev.yaml
-a----        08-11-2019    21:41             88 Pulumi.yaml
-a----        08-11-2019    21:41            456 tsconfig.json
```

**Comment by chrsmith** [comment]
@AbhishekTripathi that certainly doesn't look right. Would you mind opening a new bug with the output you have here?

If I had to guess, when you are running `pulumi stack`, it is maybe using a different account/credentials than what you are currently logged in as? That might make a difference.

e.g. if you type `PULUMI_ACCESS_TOKEN="pul-xxx pulumi login && pulumi stack ls`, does `nrdev` show up in the list?

Some other pieces of data that would be helpful in diagnosing it:

```
pulumi version

# Print out whoami, which will confirm you're logged into the local backend.
pulumi whoami -v

# The "accounts" you have logged into.
# Be sure not to include any credentials. This is just relevant to understanding
# if the `nrdev` is related to another backend/login.
cat ~/.pulumi/credentials.json | jq '.accounts | keys'
```

**Comment by AbhishekTripathi** [comment]
@chrsmith I didn't quite get the access token part of your comment. I have logged in using `--local` as the backend. I don't have any access token. Please let me know if you need any other detail in the new bug I created.
I have opened a new bug at https://github.com/pulumi/pulumi/issues/3504

**Comment by megakid** [comment]
I am seeing the same.  When I use `pulumi login --local`:

```
PS C:\Projects\aws-typescript\containers> pulumi stack ls
NAME  LAST UPDATE  RESOURCE COUNT
PS C:\Projects\aws-typescript\containers> pulumi stack ls --all
NAME  LAST UPDATE  RESOURCE COUNT
PS C:\Projects\aws-typescript\containers> pulumi stack
Current stack is dev:
    Managed by XXXX-00733
    Last updated: 24 minutes ago (2019-11-15 13:41:58.6661096 +0000 UTC)
    Pulumi version: v1.5.2
Current stack resources (38):
    TYPE                                                                               NAME
    pulumi:pulumi:Stack                                                                container-quickstart-dev
```

**Comment by WoLfulus** [comment]
For those wondering why local stacks doesn't show up. Check your `PULUMI_CONFIG_PASSPHRASE` value, or try selecting a known existing stack anyways (that doesn't show up) with `pulumi stack select <stack_name>`. It will tell you if it's a problem with decryption with `error: decrypting secret value: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase`

**Comment by UnoSD** [comment]
I am experiencing the same issue (local backend and -a doesn't show any stack whereas there is one).

I noticed this happened after I renamed a stack prepending the project name:

my stack was called `production` and appeared with `pulumi stack ls`

then I renamed to `Something/production`, the stack works and still exists, but no results from `pulumi stack ls` or `pulumi stack ls -a`
