### ISSUE TITLE
Add CLI command that shows the current backend

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#2684]
For example, to show which cloud-url is being used, or local directory, or S3 bucket. Perhaps, just extend `pulumi whoami` to output this information?

**Comment by stack72** [comment]
@justinvp / @ellismg do you think this needs to be in JSON or table format or both? Also, do you think The name of the stack should be outputted here as well?

This is a pretty simple addition to the CLI that I can add if you want? It would be my first foray into the pulumi cli

**Comment by ellismg** [comment]
> @justinvp / @ellismg do you think this needs to be in JSON or table format or both? Also, do you think The name of the stack should be outputted here as well?

I think it would be fine to just extend the output to include the URL of the backend.  Not sure that we need JSON or table output format for this just yet (my assumption is that it's a nice thing to have for an end user to situate themselves, not something we'd care about scripting around, since you could always use `pulumi login` to get to a known good state for scripts).  But maybe @justinvp has some additional thoughts on providing more context here.  With respect to showing the current stack name, we already have `pulumi stack` which tells what is the currently selected stack as well as some detailed information

> This is a pretty simple addition to the CLI that I can add if you want?

Sounds great to me, @stack72

**Comment by justinvp** [comment]
> This is a pretty simple addition to the CLI that I can add if you want? It would be my first foray into the pulumi cli

@stack72 Great! We'd love your help! Just need to settle on a design...

> do you think this needs to be in JSON or table format or both?

Personally, I'd start with just outputting something human readable and then follow-up with a JSON flag, if we find there's a need for it. We could do a table format or something simpler.

It's not clear to me yet whether this is a new command or `pulumi whoami`. If `pulumi whoami` do we change its output (is anyone relying on it just returning the current user?) or add a flag to opt-in to providing more detailed info?

> Also, do you think The name of the stack should be outputted here as well?

Your question made me realize that we kind of already have a command for doing this. If you're in a project directory, you can run `pulumi stack` and it will show you information about the current stack, including the URL (as well as custom cloud URL, if one is being used). Perhaps updating `pulumi stack` to show information about other backends would be sufficient to address this request? Though, it does mean the command will only work inside a project directory.

@ellismg, any thoughts?

**Comment by ellismg** [comment]
FWIW, Having `pulumi whoami` print the URL of the currently connected backend (so it works outside a project context) is a great idea.  I would find this especially useful, since sometimes I'll want to check to make sure I'm not connected to my dev-stack before creating some new projects.

**Comment by stack72** [comment]
@ellismg / @justinvp ok I’ll send a PR that extends the current “pulumi stack” output as it feels like it’s a better fit there - I’ll tag you both tomorrow on this and see if you feel it’s ok

**Comment by justinvp** [comment]
@stack72, I replied before seeing @ellismg's initial response. I agree with him that extending `pulumi whoami` to print the URL of the currently connected backend would be useful, so the command can be used outside of existing project directories.

In addition to that, extending `pulumi stack` to output information about other backends would be useful as well!

**Comment by stack72** [comment]
Done for both @justinvp :)
