### ISSUE TITLE
Clarify S3 state backend credentials options

### ISSUE THREAD

**Issue by jeshan** [pulumi/pulumi#2692]
PR #2455 introduced support for storage backend like s3:
`pulumi login s3://...`

The changelog reads:
> Credentials for accessing the bucket operate in the normal manner for each cloud provider.  i.e. for AWS this can come from the environment, or your `.aws/credentials` file, etc.

Can somebody clarify how to specify the AWS CLI profile, i.e the ones available in `~/.aws/config` ?

@Place1

**Comment by Place1** [comment]
I haven’t tested aws but I’m assuming the usual AWS_DEFAULT_PROFILE
environment variable should work.

**Comment by jeshan** [comment]
right! I forgot about that one. note that `AWS_PROFILE` is also accepted.
I struggled with getting started with the s3 storage so I'm documenting the steps here:

Given a stack named `dev` that you want to import into S3:
```bash
pulumi stack -s dev export > stack-export-dev.json
echo "{}" > /tmp/file # the s3 integration expects an existing valid json file
AWS_PROFILE=your-profile aws s3 cp /tmp/file s3://my-private-bucket/.pulumi/stacks/dev.json #must be at this exact path
AWS_PROFILE=your-profile pulumi stack import --file stack-export-dev.json
```
