### ISSUE TITLE
Add a way to get old resource state, or skip resource work on unchanged inputs

### ISSUE THREAD

**Issue by FraserWaters-GR** [pulumi/pulumi#2700]
@joeduffy mentioned the idea https://github.com/pulumi/pulumi-cloud/issues/183#issuecomment-377067029 in relation to not pushing docker builds when not needed. 

We'd also find this useful for other scenarios where we have some work that can be cached as long as the inputs haven't changed, but we don't have anywhere obvious to cache the work.

Being able to get the current state would allow us to write things like:
```typescript
class HeavyWork extends pulumi.ComponentResource {

    public input: pulumi.Output<string>
    public result: pulumi.Output<string>

    constructor(name: string, args : WorkArgs) {
        super("example:heavyWork:HeavyWork", name, {});

        this.input = pulumi.output(args.input);

        this.result = pulumi.all([this.getOldState(), this.input]).apply(
            ([state, input]) => {
                const oldInput = state["input"] as string;
                if (oldInput === input) {
                    return state["result"] as string;
                } else {
                    return this.doHeavyWork(input);
                }
            }            
        )

        this.registerOutputs({
            input: this.input,
            result: this.result
        })
    }
}
```

**Comment by lukehoban** [comment]
One thing to take a look at is “Dynamic Providers”. They provide a way to interact directly at the resource CRUD level, but still authored inside your Javascript program. In particular, this means they do get to see old and new inputs during updates, and have direct access to handle deciding when a diff is present. 

See https://pulumi.io/reference/programming-model.html#dynamicproviders.

**Comment by Frassle** [comment]
I'll have a look at that next week. Looks to be a lot more to write to achieve the result wanted.

Can understand if getOldState doesn't really make sense, I'm not really sure what the state of ComponentResources looks like and saw in another issue that registerOutputs might be going which I guess might change that to not have any state at all.
