### ISSUE TITLE
Support for Hetzner Cloud

### ISSUE THREAD

**Issue by akoenig** [pulumi/pulumi#2707]
I would love to see this unofficial Pulumi Provider ([akoenig/pulumi-hcloud](https://github.com/akoenig/pulumi-hcloud)) for supporting [Hetzner Cloud](https://www.hetzner.com/cloud) integrated into the Pulumi ecosystem 🙂 - As discussed on Slack, it needs some love around the tests, but I use it in a side-project locally and it works 🙂

**Comment by pmaedel** [comment]
I have tried creating my own up to date tf-based pulumi provider, thinking it could not be so difficult, with the provided documentation and boilerplate template. Turns out, it was to difficult for me.
This is currently the 7 most voted for issue and maybe low hanging fruit for you @stack72?

**Comment by stack72** [comment]
Hi @akoenig 

My apologies that this took such a long time to get to but we have finally done the work here to get this taken care of. A lot had changed in the code generator (regarding multiple projects with go.mod files etc) so I wasn't able to port your work directly

Thanks again for raising this

Paul
