### ISSUE TITLE
Support listing stacks that have a given stack tag

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2712]
The CLI does not yet expose a way to discover which stacks have a given tag.

This could be as simple as `pulumi stack ls --tag mytag`, or even including tags in the results from `pulumi stack ls --json` so that a `jq` command could be used to filter down to the stacks that include a given tag.

**Comment by eshamay** [comment]
Please also consider the following:
* multi-tag queries, e.g. "return all stacks that have key1=value1 AND key2=value2"
* a single query that spans all stacks in a project
* output would be a list of stack names

**Comment by eshamay** [comment]
Also, document and expose the Pulumi REST API for stack tag queries for code queries without requiring use of the CLI

**Comment by eshamay** [comment]
* query to get all tags for all stacks, i.e. return a list of stack tags grouped by stack for all stacks in a project.

**Comment by eshamay** [comment]
Another nice-to-have:
query stacks in another project within Pulumi code by providing the reference project's name, and a set of stack tags and values on which to query. Something along the lines of:

```
const referencedStack = new pulumi.StackReference(projectName,
  [
    {tag: "environment", value: "production"},
    {tag: "primary", value: "true"},
    {tag: "region", value: "us-west-2"},
  ]
);```

**Comment by ellismg** [comment]
We didn't get to this in M25, but we do need to think about this and other stack tag related work we'd really like to do to make the feature complete and useful in a bunch of different contexts.
