### ISSUE TITLE
Transient `error: transport is closing`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2713]
We have seen a few reports of users periodically (but not consistently) hitting `error: transport is closing` errors.  

```
@ Updating...........
 +  pulumi:pulumi:Stack myapp-myapp-b-stage-eus2 **creating failed** error: transport is closing
 +  azure:compute:VirtualMachine Studio-B-0-Stage-Eus2-Vm created 
 
Diagnostics:
  pulumi:pulumi:Stack (myapp-myapp-b-stage-eus2):
    error: transport is closing
```

Other notes:
> I’ve seen it 3 times in about 10 days.. our main pipeline is Jenkins running pulumi in a docker container.  I don’t see any other logs/notices other than this.  It fails.. but on all subsequent runs it’s worked.
> I’d say it’s happening about 1 in 20 on pulumi stack updates

**Comment by slikk66** [comment]
Hi, we got another one of these today.  I sent the logs to @lukehoban over slack per his request (some semi-sensitive info in the long log) - we captured the full output around the issue using: `pulumi update --logtostderr -v=7`

**Comment by lukehoban** [comment]
We have unfortunately not been able to root cause any of the occurences of this we've seen so far.  It is likely that the `error: transport is closing` is a symptom not the cause - and that something else is causing the Pulumi program to crash.  If others see this and can reproduce or have verbose logs - we'll try again to investigate.

**Comment by kalicja** [comment]
Hi it has been 2 years, and i found root cause. It is interesting. See if you can reproduce 
1. create kubernetes context with namespace=default, or empty namespace 
2.set up kubernetes:context to this context in pulumi project
3.execute pulumi preview -> it hangs

**Comment by guineveresaenger** [comment]
Possible new instance of this bug: https://github.com/pulumi/pulumi-kubernetes/issues/1970
