### ISSUE TITLE
Improve diagnostic errors for failures in dynamic resource provider

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi#2721]
I have a dynamic resource provider that seems to have actually executed the resource creation against the cloud provider successfully. However, the engine still reported that the `create` function in my implementation of the `pulumi.dynamic.ResourceProvider` interface failed. This is all of the error that I got:

```
+  pulumi-nodejs:dynamic:Resource azure:cdn:Endpoint:CustomDomains:cdnCustomDomain creating

@ Updating.....

+  pulumi-nodejs:dynamic:Resource azure:cdn:Endpoint:CustomDomains:cdnCustomDomain creating error: Plan apply failed: Unexpected struct type.

+  pulumi-nodejs:dynamic:Resource azure:cdn:Endpoint:CustomDomains:cdnCustomDomain **creating failed** error: Plan apply failed: Unexpected struct type.
```

It would be nice to get a little more diagnostic output under failure than that.

**Comment by praneetloke** [comment]
It seems that I may have fixed the above crash by changing the outputs my `create` function was returning.  I was previously returning:

```
{
  id: result.id,
  outs: {
   ...
  }
}
```
I changed it to:
```
{
  id: result.id,
  outs: { ...result, inputs: { ...inputs }}
}
```
After the above change, I ran `pulumi update --logtostderr -v-9 2> err.txt` to try and capture any additional diagnostics of the failure, and I see the following in the log. However, my update doesn't fail with the original error in the issue description anymore.

```
pulumi : I0512 09:35:21.864598   14604 log.go:56] Error closing 'nodejs' language plugin during shutdown; ignoring: 1 
error occurred:
At line:1 char:1
+ pulumi update --logtostderr -v-9 2> err.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (I0512 09:35:21....error occurred::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
	* TerminateProcess: Access is denied.


I0512 09:36:12.126246   14604 log.go:56] Error closing 'nodejs' language plugin during shutdown; ignoring: 1 error 
occurred:
	* TerminateProcess: Access is denied.
```

**Comment by mikhailshilkov** [comment]
Let's track in #3599 which seems to be a more concise summary
