### ISSUE TITLE
k8s.Provider({kubeconfig}) fails when referencing a secret or a stack ref

### ISSUE THREAD

**Issue by jeffijoe** [pulumi/pulumi#2741]
When either a `pulumi.secret` or a `StackReference` prop is made part of the graph that results in a kubeconfig, the below error occurs.

![image](https://user-images.githubusercontent.com/2505474/57931881-d3404c00-78b9-11e9-8467-4d7ecc63c8f0.png)

Example:

```ts
const k8sProvider = new k8s.Provider(name, {
  kubeconfig: pulumi.secret("dont tell anybody")
});
```

```ts
const k8sProvider = new k8s.Provider(name, {
  kubeconfig: new pulumi.StackReference('pancake').getOutput('syrup')
});
```

**Comment by jeffijoe** [comment]
Any known workarounds in the meantime that don't involve glueing 2 pulumi invocations together using a bash script? 😅

**Comment by ellismg** [comment]
Thanks for the report!  https://github.com/pulumi/pulumi/pull/2743 should address this issue.

**Comment by ellismg** [comment]
> Any known workarounds in the meantime that don't involve glueing 2 pulumi invocations together using a bash script? :sweat_smile:

Unfortunately, I don't believe there is a satisfying issue here.

**Comment by jeffijoe** [comment]
Any idea when the fix will be released? 😄

**Comment by ellismg** [comment]
> Any idea when the fix will be released? smile

We'll do a release with the fix shortly after it is code reviewed, so I expect we can get something out later today.  If it's helpful, I am happy to build and share a patched Pulumi with you, so you can see if that unblocks your entire problem.

**Comment by jeffijoe** [comment]
No worries, I’m heading to bed soon anyway, but thanks for fixing it! Spent 6 hours trying to figure this out thinking i was missing something essential, just weird that it apparently works in the reference guide. 🤔
