### ISSUE TITLE
Don't force a single secret output from a stack reference to taint all outputs

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#2744]
When you take a reference to another stack to get its outputs, if /any/ output is considered a secret then the `Output<T>` for the `.outputs` member is treated as a secret.  This means if you call `getOutput("someOutputThatWasNotSecret")` the Output<T> you get back will be marked as a secret, which isn't ideal.

It may be possible for us to make `getOutput` only return a secret output when the output you are fetching was itself a secret, but I believe it will require treating `stackReference` as special in some way.

**Comment by jeffijoe** [comment]
Despite being closed, adding this as a reference as it relates to the core problem https://github.com/pulumi/pulumi/issues/2741

**Comment by ellismg** [comment]
I think we should be able to augment the StackReference type to also include as an output the names of any secret outputs.  Then, inside `getOutput` we can consult this list and remove the secret bit from the output we are going to return in the case where the output you are fetching is not in that list.  We will continue to have to mark the `outputs` property as a secret if any of the individual outputs inside it are secret, however.
