### ISSUE TITLE
Custom resources without utilizing underlying provider

### ISSUE THREAD

**Issue by akoenig** [pulumi/pulumi#2750]
There are sometimes situations in which you want to use a new shiny feature which is not available in the underlying cloud provider (think `gcloud alpha` features).

Would be great to create a custom resource, which fits nicely into the Pulumi create / update / delete lifecycle. Something like:

```typescript
class ShinyFeature extends CustomResource {
  async create() {
    // Spawn `gcloud alpha compute create ...` manually in order to create the resource
  }

  async remove() {
    // Spawn `gcloud alpha compute delete ...` manually in order to remove the resource
  }
}
```

Is this something you're also considering? Would be awesome! 🚀

**Comment by lukehoban** [comment]
This in fact already exists!

See docs here: https://pulumi.io/reference/programming-model.html#dynamicproviders

**Comment by ztmr** [comment]
@lukehoban any plans to support dynamic providers from Go?

**Comment by Frassle** [comment]
> any plans to support dynamic providers from Go?

There are not. The way dynamic providers work (code closure serialization) means it's probably not possible to support them for Go. We have ideas for a new type of dynamic provider that _would_ be doable in Go, but that feature isn't currently on the roadmap.
