### ISSUE TITLE
Improve our package versioning test coverage

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2757]
We recently got bitten by an awful bug whereby, after upgrading the AWS or Azure package, any `pulumi up` would try to recreate all of your resources. Our end users caught this, which is terribly unfortunate. Let's improve our test coverage of package upgrades like this. For instance, have a long lived stack and upgrading it as part of the rollout of a new package would be a fine canary (and is in line with our current goals of improving "upgrade" test coverage).

**Comment by lukehoban** [comment]
I believe we should add a feature to our integration test framework to enable testing a sequence that first deploys with `latest` and then updating with the `yarn link`'d version of the provider, and enforces no replacements.  

We should ensure that we use this in almost all integration tests.  In fact, for all our packages, I believe the current "no-op" step should probably be this upgrade.

This is something @metral has been talking about adding for EKS validation, but I think we should do this in the core integration test framework to ensure it's part of the default test validation that all packages use.

**Comment by ellismg** [comment]
We did not get to this, but it is critical we find time soon to do this, we really need to leverage this as a way to get confidence as part of our release process.

**Comment by stack72** [comment]
Going to close this out - this has helped us successfully find some problems in the Azure package as an example. I am going to close this as a V1 - we have a LOT more work to do in this area. But we need to discuss this and plan this appropriately
