### ISSUE TITLE
Print an update's permalink *before* finishing

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2768]
We don't print an update's permalink until after the update has completed. This is unfortunate, because there are plenty of reasons you might want to look at the service console while an update is proceeding, including seeing some of the more verbose logging available there (versus the interactive CLI display), resource properties, resource graph as it evolves, and, over time, many other goodies.

Instead of always waiting until the end, we should print it at the beginning of an update, possibly in addition to at the very end, for cases where the header scrolls off the screen.

This would also make demos a little nicer since, to kill time while an update occurs, I often go to the update on the service console.

**Comment by stack72** [comment]
Closed via #5222
