### ISSUE TITLE
Add org filter for stack listing

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#2769]
For users in multiple orgs and with lots of stacks `pulumi stack ls -a` can be quite lengthy as it lists _all_ stacks (as expected). This can make the output a bit difficult to parse and also makes it more complex to pipe output to other tools to use for automation. 

`pulumi` should support an `--org` flag (or similar) to filter results to the specified organization.

**Comment by chrsmith** [comment]
Good suggestion. /cc https://github.com/pulumi/pulumi-service/issues/3091, which is an issue tracking some performance improvements we can make for the `stack ls` APIs.

**Comment by lukehoban** [comment]
Also related to https://github.com/pulumi/pulumi/issues/2712.
