### ISSUE TITLE
dynamic.Resource + parent + provider = error

### ISSUE THREAD

**Issue by brandonbloom** [pulumi/pulumi#2776]
I get the following error for a `dynamic.Resource` that has component options `{parent: ...}` set, when the parent has a `{provider: ...}` set for the purposes of assume role:

`error: unrecognized resource type (Check): pulumi-nodejs:dynamic:Resource`

It seems like the Check operation is being executed against the parent's provider (in this case an AWS/Terraform provider specified for assume-role) instead of against the dynamic provider.

Omitting the `parent` option allows me to workaround this issue.

**Comment by lukehoban** [comment]
@brandonbloom Do you happen to have a repro of this?  There's a lot going on in the described scenario - and I fear that I'll have trouble reproducing accurately.

**Comment by brandonbloom** [comment]
I didn't produce a minimal repo, but I think it should be possible to do some relatively easily. I have a workaround, so this isn't pressing.

However, if I were to attempt a minimal repro, here's what I'd do:

1) Instantiate a first-class AWS provider for "assume role"
2) Create a ComponentResource, passing it a providers map with that aws provider in it.
3) Create a Dynamic resource & provider.
4) In the constructor of the ComponentResource, instantiate the dynamic resource, passing the `{parent: this}` options.
5) Note that running step 4 fails
6) Remove `{parent: this}` options, note that running works (but, of course, the component hierarchy is wrong)

**Comment by solidDoWant** [comment]
To anybody else looking for the workaround (not language specific) you can create a new ResourceOptions without the provider set, i.e. in Python `ResourceOptions(parent=self)` instead of `ResourceOptions(parent=self, provider=<some provider object>)`

**Comment by mmmmmarco** [comment]
If you are using the Pulumi Azure C# client, make sure to use the Provider from the correct library. So if you are trying to create a resource with Pulumi.AzureNative, don't accidentally use a Provider from Pulumi.AzureNextGen for example. Otherwise you will get the error unrecognized resource type (Check)

**Comment by lukehoban** [comment]
Closing this out as it is an old issue, we don't have a concrete repro, and the suggested workaround above is the "correct" way to do this.
