### ISSUE TITLE
Support additional secrets providers

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2780]
We recently added support for a configurable `secrets-provider` on a stack.  This secrets=-provider manages the encryption of secret data in config and the state file.  We currently support two options - `default` (encryption handled by pulumi.com) and `passphrase` (encryption managed by PBKDF2  derived from a user provided passphrase).

We would like to expand this to support additional `secrets-providers` for integration with existing encryption solutions - including:
- [ ] AWS KMS
- [ ] Azure KeyVault
- [ ] Google Cloud KMS

In each case, the secrets provider should allow configuration of provider credentials and a key id to use for making encrypt/decrypt calls using the secrets provider.

**Comment by gordonbondon** [comment]
Go CDK has support for cloud secrets https://github.com/google/go-cloud/blob/a68836e8e108ad55d26e8e2d21579028090c8aa5/internal/website/content/howto/secrets/open-keeper.md so maybe it can be used for this purpose, same as for bucket backends.

**Comment by ellismg** [comment]
We (unfortunately) did not get to this yet.  The idea of using Go CDK is interesting, it looks like it could be worthwhile.  When prototyping this for AWS, I had been using their GenerateDataKey method, which allows you to generate a key that you can use for AES-256-GCM, which ties in nicely with how the local secrets manager works today.

I think we will want to follow a similar strategy if we use the Go CDK.  We should generate a key locally, then encrypt it using the cloud secret manager and store the resulting ciphertext in `Pulumi.<stack-name>.yaml`, similar to what we do for the local passphrase today.  We'll also need to store whatever context information we need to re-create the secrets provider (In a Go CDK world, I think this is just the string we'd pass to construct the Keeper).

**Comment by omerlh** [comment]
Where can I find information about the `secret-provider` API? I'm wondering if I can leverage tools like [Kamus](https://kamus.soluto.io) for this. The main advantage of using Kamus is that it let everyone encrypt, saving the hard challenge of managing permissions.

**Comment by ellismg** [comment]
Fixed with https://github.com/pulumi/pulumi/pull/2994
