### ISSUE TITLE
Tests hang reading an output property

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2785]
The test below hangs. At first I expected this was due to https://github.com/pulumi/pulumi/pull/2638#issuecomment-483809925 which causes tests to hang if any output that is not also an input is `.apply`'d.  But in this case, the property being read is a property that was provided as an input.

```typescript
    describe("constructor", function() {
        let testBucket = new aws.s3.Bucket("test");
        let bucketPolicy = new aws.s3.BucketPolicy("test", {
            bucket: testBucket.id,
            policy: ""
        });
        it("should attach to the given bucket", function(done) {
            bucketPolicy.bucket.apply(bucketId => {
                // hangs and doesn't run this code
                if (bucketId == "test") {
                    done();
                } else {
                    done(new Error(`wrong bucket id ${bucketId}`))
                }
            })
        });
```

**Comment by dustinfarris** [comment]
I'm noticing that this happens for any outputs that are not already given by an input.

e.g. this passes (urn):

```ts
describe("bucket", function() {
    let bucket = new aws.s3.Bucket("test");
    it("should have an urn", function(done) {
        bucket.urn.apply(urn => {
            done();
        });
    });
});
```

this hangs (arn):

```ts
describe("bucket", function() {
    let bucket = new aws.s3.Bucket("test");
    it("should have an arn", function(done) {
        bucket.arn.apply(arn => {
            // hangs and doesn't run this code
            done();
        });
    });
});
```

**Comment by lukehoban** [comment]
> I'm noticing that this happens for any outputs that are not already given by an input.

This is a known behaviour of the current unit testing implementation, as discussed in https://github.com/pulumi/pulumi/pull/2638#issuecomment-483809925.  We should look into how to improve that.

What I'm really surprised at is that your original repro was `bucketPolicy.bucket.apply` on a `bucketPolicy` resource which had provided a value for `bucket` as an input.  I would have expected that case to work.

**Comment by dustinfarris** [comment]
Maybe because `testBucket.id` is itself an Output?

**Comment by lukehoban** [comment]
> Maybe because testBucket.id is itself an Output?

Yep - that explains it.  We’ll use this issue to track any improvements we can make to avoid hanging when outputs are `.apply`d in tests.

**Comment by lukehoban** [comment]
For folks who hit this - there is an alternative unit testing approach available that runs inside real `preview` and `apply` operations - which is documented at https://www.pulumi.com/blog/unit-testing-infrastructure-in-nodejs-and-mocha/.

**Comment by lukehoban** [comment]
Closing this out as part of the planned deprecation of PULUMI_TEST_MODE in https://github.com/pulumi/pulumi/issues/3045.
