### ISSUE TITLE
GOOGLE_CREDENTIALS doesn't get used during pulumi login to a gs://bucket

### ISSUE THREAD

**Issue by Place1** [pulumi/pulumi#2790]
Hi all, i'm using the new cloud bucket storage state backend on google cloud `gs://my-bucket`.

I think that pulumi (or go cloud) is not reading the `GOOGLE_CREDENTIALS` environment variable for authentication. Here's a sample output

```bash
$ export GOOGLE_CREDENTIALS="$(cat ~/service-account-credentials.json)"
$ pulumi login gs://my-bucket
error: problem logging in: unable to open bucket gs://my-bucket: open bucket gs://my-bucket: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

As a work around to this issue, i'm doing the following:

```bash
$ export GOOGLE_CREDENTIALS="..." # the variable is actually from a Gitlab CI Secret
$ echo "$GOOGLE_CREDENTIALS" > /creds.json
$ export GOOGLE_APPLICATION_CREDENTIALS="/creds.json"
$ pulumi login gs://my-bucket
```

**Comment by ellismg** [comment]
I believe that it is the underlying `go-cloud` that is not doing this.  https://gocloud.dev/howto/blob/open-bucket/#gcs.

**Comment by lukehoban** [comment]
cc also @vangent

**Comment by vangent** [comment]
Go CDK follows the GCP guidelines [here](https://cloud.google.com/docs/authentication/production), which recommend storing the credentials in a file and setting the path to that file in `GOOGLE_APPLICATION_CREDENTIALS`, as described in your workaround.

Where did you find `GOOGLE_CREDENTIALS` documented as a way to pass credentials to GCP APIs?

**Comment by Place1** [comment]
@vangent I've been using `GOOGLE_CREDENTIALS` as documented here: https://pulumi.io/quickstart/gcp/

**Comment by vangent** [comment]
Got it. That looks like a Pulumi-specific configuration.

The default Go CDK `URLOpener` follows the GCP guidelines as described above; you can create and register your own `URLOpener`s as described here:
https://gocloud.dev/concepts/urls/#muxes

to get more control.
