### ISSUE TITLE
Google Cloud state backend fails to print a signed url after pulumi up finishes

### ISSUE THREAD

**Issue by Place1** [pulumi/pulumi#2791]
When running `pulumi up` using a `pulumi login gs://my-bucket` the update completes successfully and the remote state is correctly saved in the bucket, but the command terminates with an error code because pulumi fails to fetch a signed url to the state bucket.

Here's a sample output of the error
```bash
Resources:
    ~ 1 updated
    127 unchanged

Duration: 1m47s
error: Could not get signed url for stack location: blob (code=Unknown): to use SignedURL, you must call OpenBucket with a valid Options.GoogleAccessID and exactly one of Options.PrivateKey or Options.SignBytes
```

The problem is here: https://github.com/pulumi/pulumi/blob/master/pkg/backend/filestate/bucket.go#L46-L47

Because the call to [blob.OpenBucket](https://github.com/pulumi/pulumi/blob/master/pkg/backend/filestate/backend.go#L102-L103) doesn't provide a [blob.Options](https://godoc.org/gocloud.dev/blob/gcsblob#Options) the call to `SignedURL` fails.

I think a change is required to reuse the current GCP credentials when generating this signed URL, that seems like a reasonable solution to me.

edit:

after reading a bit more, it seems like the GCS [URLOpener](https://godoc.org/gocloud.dev/blob/gcsblob#URLOpener) from go-cloud supports settings the required values as a query param, meaning that `pulumi login gs://my-bucket?access_id=...&private_key_path=...` should work. Is this the expected UX for pulumi with GCS?

**Comment by Place1** [comment]
@CyrusNajmabadi hey, would you mind checking out the above PR?

**Comment by CyrusNajmabadi** [comment]
Sure!

**Comment by theomessin** [comment]
Any update on this?

**Comment by rawkode** [comment]
Yep. This is broken :(

**Comment by daralthus** [comment]
@lukehoban Would it make sense to just disable printing the signed url (or make it a cli option to do that) in the meantime?

There is already an `opts.ShowLink` flag used around to disable this for `file://` backends.

Happy to make a PR if that helps.

**Comment by lukehoban** [comment]
@daralthus yes - that would be an improvement - though would also love to fix the underlying issue. PRs for either welcome!

**Comment by Place1** [comment]
@lukehoban i've already made a PR that fixes the underlying problem but it's been ignored. i'm happy to get it up-to-date again if someone will accept it: #2906

the PR notes how it fixes the problem.

**Comment by daralthus** [comment]
@lukehoban Had a look at @Place1's PR and I agree it's the way to go!

**Comment by pawelprazak** [comment]
Still a problem in 2021...

**Comment by justinvp** [comment]
@pawelprazak, would you mind opening a new issue with more information about the problem you're still seeing?
