### ISSUE TITLE
Fault in plugins on `pulumi update --refresh` and `pulumi refresh`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2799]
We recently started auto-downloading plugins when needed during `pulumi update`, but it appears we do not yet for `pulumi refresh` (and possibly for other commands).  This appears to prevent `pulumi update --refresh` from correctly acquiring plugins that might be needed for the old versions of resources in the checkpoint (possibly different than what the `npm install` acquired for the new version of the source code).

**Comment by ellismg** [comment]
I would have expected that this was fixed by https://github.com/pulumi/pulumi/pull/2773 (which has not yet been released, but the code changes should be present in HEAD).  Is there still a gap here, @lukehoban?

**Comment by lukehoban** [comment]
Ahh - great - I thought I had seen a recent change related to this.  That most likely addresses this.  I opened based on a report from @AaronFriel, so he may be able to verify that #2773 addresses this fully for him once it is available in a release.
