### ISSUE TITLE
Using S3 backend with multiple projects is unpleasant

### ISSUE THREAD

**Issue by eropple** [pulumi/pulumi#2814]
Current situation: I've got a number of...I keep wanting to call them _stacks_, but in Pulumi that word means something (though [the documentation](https://pulumi.io/reference/organizing-stacks-projects/) also confusingly overloads the term!), so let's call them _projects_...encompassing different bits of functionality. While I want to use the Pulumi SaaS, I need to prove that we can do our thing by using the S3 backend first.

Right now, the experience of doing so feels pretty bad. And while I'm gung-ho about Pulumi, I feel queasy about maybe having it too early here because while the actual resource/state management seems to be very mature I don't know if I can adequately manage this stuff _and_ provide a quality, DRY developer experience without writing a bunch of should-be-superfluous wrapper scripts around Pulumi itself.

## Current options ##
- I can tell my developers that they need to switch stacks to something like `dev.build.my-service` (or something equally long and gross), and that their configs will be stored in `Pulumi.dev.build.my-service.yaml` (barf). Then I can pass similarly grody `pulumi.StackReference` names in our code. The IAM policies necessary to effectively control access to these states are also going to be kinda gross.
- I can use separate `pulumi login`s for separate services, but `pulumi login` is stateful at a user level (this strikes me as no bueno, FWIW, but is probably a separate issue) and the S3 backend can't talk to a different `pulumi login`/"backend" (another term that seems aggressively overloaded) so `my-service` couldn't talk to `core-infra` even if it wanted to.

## Desired Outcomes ##
- We have a `name` field in `Pulumi.yaml`. I would like the contents of that field to be namespaced into the `.pulumi/stacks` directory. For example, for `my-service`, I want `dev` to be at `.pulumi/stacks/my-service/dev.json`.
- I would like this name to be part of the name used for `pulumi.StackReference`s. I should be able to go something like

```ts
// while working in project `my-service`, stack `dev` - `my-service/dev`
const env = config.get("env") || pulumi.getStack().split("/").last();
const core = new pulumi.StackReference(`core-infra/${env}`); // `core-infra/dev`
```

...and just have it work. (I recognize that this potentially collides with the organization stuff in the SaaS product, but I can't come up with a better way to do this that respects that `.pulumi` really wants to think of itself as a file system.

Thanks, folks. Appreciate your hard work.

**Comment by ellismg** [comment]
From a naming point of view, we refer to the `name` property in the `Pulumi.yaml` file as the "project name".  You can get at it by calling `pulumi.getProject()`.  I believe that doing https://github.com/pulumi/pulumi/issues/2522, this will address the issue, because we would store stuff in a per project folder under the `.pulumi` folder in the s3 bucket.

I do not believe that we would change the return value of `pulumi.getStack()` to include the project name (we don't do this today in the SaaS offering, and I would want to keep alignment there), so I think you'd write:

```typescript
const env = config.get("env") || pulumi.getStack();
const core = new pulumi.StackReference(`core-infra/${env}`); // `core-infra/dev`
```

**Comment by eropple** [comment]
That works for me, so long as I have a way to fully qualify things!

Would, then, `core-infra/dev` refer for its config to a `Pulumi.dev.yaml` file in the `core-infra` project directory? (Similarly, would `pulumi stack switch dev` do the Right Thing?)

**Comment by gordonbondon** [comment]
I think #2813 should solve problem with `pulumi login` being user level vs project level.

**Comment by ellismg** [comment]
> I think #2813 should solve the problem with pulumi login being user level vs project level.

Yeah, I think that fits in with our overall model much better than something per project.

**Comment by ellismg** [comment]
> Would, then, core-infra/dev refer for its config to a Pulumi.dev.yaml file in the core-infra project directory? (Similarly, would pulumi stack switch dev do the Right Thing?)

Sorry, I don't fully understand the question here.  Let's imagine you have two projects:

`core-infa`
`great-app`

This means you'd have two different Pulumi programs, each with their own `Pulumi.yaml` files, in separate directories.  Each project would have one or more stacks, each with their own `Pulumi.<stack-name>.yaml` file.

In the code in the `great-app` project, you should be able to do the following:

```typescript
const env = config.get("env") || pulumi.getStack();
const core = new pulumi.StackReference(`core-infra/${env}`); // `core-infra/dev`
```

And have that read stack outputs from the stack named by whatever `env` is, in the `core-infra` project.

When you run `pulumi config` or `pulumi stack select`, the project is inferred from whatever the closest `Pulumi.yaml` file is.  So if you were in the `core-infra` folder, `pulum config -s dev` would refer to the config for the `core-infra` `dev` stack, where as the same command when run from the `great-app` folder would pick up config for the `dev` stack in for `great-app`.

Hopefully that answers your question?  If not, can you try to ask it in a different way?

**Comment by kurlzor** [comment]
I'm using the s3 backend and `pulumi stack select` returns every stack of every project. The stack names aren't namespaced by project so it's impossible to have a project `A` with a `staging` stack and a project B also with a `staging` stack.

**Comment by gorilych** [comment]
same thing with gcs backend. It makes sense to use project in paths in s3/gcs buckets and this will allow use project name in a reference.

**Comment by eordano** [comment]
> We're using the s3 backend and `pulumi stack select` returns every stack of every project. The stack names aren't namespaced by project so it's impossible to have a project `A` with a `staging` stack and a project B also with a `staging` stack. It forces us to include the project name in the stack name, like `A-staging` and `B-staging`.

We also run into this "problem". More of a nuance, but makes the "project-stack" naming strange (we end up with funny-looking "staging:something-staging" names for all our stacks).

**Comment by renannprado** [comment]
I'm having the same issue as @kurlzor.

@kurlzor how are you dealing with the limitation? in my case we're not using (yet) stack references, but due to this naming problem, we end up having one s3 bucket per pulumi program.

**Comment by sfoulston** [comment]
We've just encountered this issue as well.

We have multiple programs (`core-infra`, `api`, `frontend`, etc), and it would be incredibly helpful to use `StackReference` in the `api` program to reference the shared network components (VPC, subnets, etc) created by `core-infra`. But because of the issues with shared backends mentioned in this issue, like @renannprado we've had to use a separate S3 bucket for each program. This means we have to manually get resources using hardcoded IDs (which might change if the `core-infra` resources change), so all the dependent programs are messier and more fragile.

It would seem to make complete sense to namespace Pulumi state using the project name as well as the stack, so I really hope this is on the near-term roadmap! 🤞

**Comment by peay** [comment]
I am also having this issue. Perhaps that's a bit naive, but would this require much more than just updating [`GetStack`](https://github.com/pulumi/pulumi/blob/master/pkg/backend/filestate/backend.go#L319) for the `filestore` backend to use the project and stack name, instead of just `stackName`?

```diff
 func (b *localBackend) GetStack(ctx context.Context, stackRef backend.StackReference) (backend.Stack, error) {
 	stackName := stackRef.Name() 
+	stackProject := stackProject.Name() 
-	snapshot, path, err := b.getStack(stackName)
+	snapshot, path, err := b.getStack(stackProject, stackName)
         ...
 }
```

Perhaps behind a feature flag for backward compatibility.

Are there other considerations that I am missing, or would this be a viable plan?

**Comment by imod** [comment]
@samox73 not sure anymore, but I think I did try this too and it did not work when referring to an output of a different cluster

**Comment by samox73** [comment]
@imod Correct. Afaik, when working with differing backend types (S3 & `app.pulumi.com`) it is currently not possible to reference one stack from the other backend type, though that would make migrating much easier.

**Comment by Thammachart** [comment]
I think this [release](https://github.com/pulumi/pulumi/releases/tag/v3.61.0) would be good enough to fix this issue, wouldn't it? 
![image](https://user-images.githubusercontent.com/1731496/231055989-6ed91878-5fc8-4984-96e6-c47b2c365ca4.png)

**Comment by abhinav** [comment]
Indeed! Thanks for bumping, this @Thammachart.

Folks, as of 3.61.0, we support project-scoped stacks in the self-managed backend.
See also the announcement blog post: https://www.pulumi.com/blog/project-scoped-stacks-in-self-managed-backend/

Closing issue as fixed. Thanks!
