### ISSUE TITLE
Style read diffs in previews/updates differently

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#2817]
The way we style read diffs in previews and updates is, to me at least, a bit confusing. (Empirically, in demos it has been for end users too.) At a glance, they make it look like we are unconditionally creating new resources (which, in the case of -- say -- a VPC, can be rather frightening/jarring).

For example, consider this program (a variant of our ECS Fargate getting started):

```typescript
import * as awsx from "@pulumi/awsx";

// Create a load balancer on port 80 and spin up two instances of Nginx.
const lb = new awsx.elasticloadbalancingv2.ApplicationListener("nginx", { port: 80 });
const nginx = new awsx.ecs.FargateService("nginx", {
    taskDefinitionArgs: {
        containers: {
            nginx: {
                image: "nginx",
                memory: 128,
                portMappings: [ lb ],
            },
        },
    },
    desiredCount: 5,
});

// Export the load balancer's address so that it's easy to access.
export const url = lb.endpoint.hostname;
```

Because we don't specify the VPC explicitly, this component will read the default one from our account. On the first `pulumi up`, this is shown in green, which makes it look like a `create` at a glance. The summary also states nothing about them, only the `create`s, furthering confusion:

![image](https://user-images.githubusercontent.com/3953235/59316299-97a76080-8c72-11e9-948f-4eb31e616e7a.png)

I can see an argument for showing these. They are, in fact, "new reads" in my update. I have a slight preference for colorizing them differently (like maybe not colorizing them at all and using the default terminal color so they stand out less), although I think we could probably safely hide them by default.

Notice that it's made worse by the fact that the VPC component responsible for reading _is_ a `create`, so it really does look like we're creating a new VPC here, even though we aren't.

Things get worse during subsequent updates, however, and I'm pretty sure this part is just flat out a bug with how we're doing and showing diffs for `read` resources from one update to the next.

If I make no edits, a `pulumi up` preview says:

![image](https://user-images.githubusercontent.com/3953235/59316416-4055c000-8c73-11e9-9e86-d7b863139242.png)

As far as I can tell, the resources read didn't change in any way, but their appearance -- again, in green -- tricks me into thinking they are going to be created. If I select `details`,  I'm shown a considerable number of properties, looking like something changed...but I don't think it did?

![image](https://user-images.githubusercontent.com/3953235/59316443-6e3b0480-8c73-11e9-8257-0efbd1df1208.png)

Here's where it gets even more confusing. If I actually _do_ edit my program -- let's say change `desiredCount` from `5` to `3`, my diff gets cluttered up with similar stuff:

![image](https://user-images.githubusercontent.com/3953235/59316470-9165b400-8c73-11e9-8313-9e73b5f576e2.png)

The details contains the read properties along with the changed ones:

![image](https://user-images.githubusercontent.com/3953235/59316479-9dea0c80-8c73-11e9-9f4c-4ea5ad3a8c7c.png)

I was only expecting to see `desiredCount: 5 => 3` here.

**Comment by lukehoban** [comment]
As noted in #2821, we should also look at the intersection of `read` resources and `refresh` here.  There appear to be some display and general "churn" issues there that are particularly awkward.

**Comment by pgavlin** [comment]
I believe that this is done for `read` in the context of the progress display, but I think that the diff display still shows these steps.

**Comment by CyrusNajmabadi** [comment]
> I believe that this is done for read in the context of the progress display, but I think that the diff display still shows these steps.

I'm personally ok landing there.  The main display doesn't show anything misleading.  BUt if someone looks at the full diff, they'll be told about the reads.  That seems acceptable.  Anyone opposed to having us just close this out?

**Comment by nesl247** [comment]
This is something that has always been confusing to me, and seeing this issue, I'll put my two cents here. I would think that any stack references would not show up in the details. My suggestion would be to have a verbosity level for the diff output if it does benefit people.
