### ISSUE TITLE
Support secrets in Go SDK

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#2820]
We added support for marking values as secret inside the Go and Python SDKs, but we have not done the work in the Go SDK to do the same.

- [ ] Support marking an `pulumi.Output` as secret and flow information across the RPC boundary
- [ ] Add pulumi.secret and related helpers
- [ ] Support `AdditonalSecretOutputs`

**Comment by EvanBoyle** [comment]
Make sure to update stack output integration tests to validate behavior https://github.com/pulumi/pulumi/blob/7b3ec744f467f0ecea7d3ab8cfc0df6e39dbd9f1/tests/integration/stack_reference/nodejs/step2/index.ts#L21

**Comment by justinvp** [comment]
Will this include adding `Secret` variants on https://github.com/pulumi/pulumi/blob/master/sdk/go/pulumi/config/config.go?

**Comment by EvanBoyle** [comment]
Yes this will include get/try/requireSecret variants

**Comment by elsesiy** [comment]
I'm wondering whether this change will also support the following use case:
1. Generate ssh key pair if there's non in the config already
2. Store key pair in the state encrypted using the stack encryption
3. Upon next run retrieve the config secret, hence don't generate a new key pair

I tried implementing this but it doesn't seem to be very straight-forward at this point. I could always make a detour using the filesystem and `os.Stat` to check whether there's an existing key pair but that's not my preferred choice.

Using the `config.New` notion, I'm not able to actually write values to it even though that would be needed in this case. The only other thing I can image would be somehow referencing the stack output from the same stack to decide whether to conduct a certain action or not.

Thoughts?

**Comment by EvanBoyle** [comment]
Have you taken a look at our documentation for secrets and config? https://www.pulumi.com/docs/intro/concepts/config/#secrets

Secrets are encrypted and stored in the pulumi.<stack>.yaml file. As far as I'm aware there isn't a runtime api equivalent for the CLI `pulumi config set --secret` so you'd need to shell out to update the stack's config during a run. 

I believe that the other option that you mention of self-referencing a stack export would work as well. Secret stack exports would be stored encrypted in the stacks state file.

**Comment by elsesiy** [comment]
@EvanBoyle Yes I did and it mentions the following:
```
The programming model offers a Config object with various getters and setters for retrieving values.
```
This is in fact not true then but why is there no runtime API?
Sure shelling out would work too but I was looking for a pulumi native way of dealing with this if possible :)

**Comment by EvanBoyle** [comment]
Definitely agree with you here. 

Have you looked into using the TLS provider? https://www.pulumi.com/docs/intro/cloud-providers/tls/

You'd need to make sure you use `additionalSecretOutputs` to ensure that the results are properly wrapped in secrets.

**Comment by elsesiy** [comment]
Thanks for being so responsive, very helpful!
Doesn't seem to fit my SSH key pair use case, am I mistaken?
For `additionalSecretOutputs` I need to wait for #3938.

**Comment by EvanBoyle** [comment]
Yes you do need to wait for #3938 

That provider is a wrapper over https://www.terraform.io/docs/providers/tls/r/private_key.html

You should be able to use it to create an ssh key pair: https://stackoverflow.com/questions/49743220/how-do-i-create-an-ssh-key-in-terraform/49792833

**Comment by elsesiy** [comment]
I'll look into it, thanks!

**Comment by elsesiy** [comment]
@EvanBoyle I'm able to use `additionalSecretOutputs` for all resources but custom `ComponentResource`s. Specifiying the resource option on the individual resource within the custom resource or when instantiating the custom resource both doesn't work. Any idea how to get this to work?

Example:
```
test.go

package test

type Test struct {
	pulumi.ResourceState

	Password *random.RandomPassword
}

type Args struct {
	Length pulumi.StringInput
}

func New(ctx *pulumi.Context, name string, args *Args, opts ...pulumi.ResourceOption) (*Test, error) {
	t := &Test{}
	err := ctx.RegisterComponentResource("test-pw", name, t, opts...)

	randomPassword := random.RandomPasswordArgs{
		Length:  pulumi.Int(args.Length),
		Special: pulumi.Bool(true),
	}
	
	# specifying the resource option here still prints it in plain text
	t.Password, err = random.NewRandomPassword(ctx, "test", &randomPassword)
	if err != nil { return nil, err }

	return t, nil
}


main.go

package main

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		# specifying the resource option here still prints it in plain text
		test, err := test.New(ctx, "abc" &test.Args{
			Length: pulumi.String(5),
		})
	})
}
```

What am I doing wrong?

**Comment by lukehoban** [comment]
@elsesiy Here's what I did - and it worked - not sure exactly what you had tried that hadn't worked?

```go
// test.go
package test

import (
	"github.com/pulumi/pulumi-random/sdk/go/random"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

type Test struct {
	pulumi.ResourceState

	Password *random.RandomPassword
}

type Args struct {
	Length pulumi.IntInput
}

func New(ctx *pulumi.Context, name string, args *Args, opts ...pulumi.ResourceOption) (*Test, error) {
	t := &Test{}
	err := ctx.RegisterComponentResource("test-pw", name, t, opts...)

	randomPassword := random.RandomPasswordArgs{
		Length:  args.Length,
		Special: pulumi.Bool(true),
	}

	t.Password, err = random.NewRandomPassword(ctx, "test", &randomPassword, pulumi.AdditionalSecretOutputs([]string{"result"}))
	if err != nil {
		return nil, err
	}

	return t, nil
}
```

```go
// main.go
package main

import (
	"github.com/lukehoban/goapp2/test"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		test, err := test.New(ctx, "abc", &test.Args{
			Length: pulumi.Int(5),
		})
		if err != nil {
			return err
		}
		ctx.Export("password", test.Password.Result)
		return nil
	})
}
```

```toml
// Gopkg.toml
[[constraint]]
  version = "v1.11.1"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  version = "v1.5.0"
  name = "github.com/pulumi/pulumi-random"

[prune]
  go-tests = true
  unused-packages = true
```

Resulting stack output (note that the generated password is encrypted in the state file in both places it appears - as an output of RandomPassword and as a stack export):

```json
{
    "version": 3,
    "deployment": {
        "manifest": {
            "time": "2020-02-28T11:46:39.389415-08:00",
            "magic": "536e9da7300013be2eb488e82ca78e9e93182d32bc2a3811616f7751b29ebfd3",
            "version": "v1.11.0"
        },
        "secrets_providers": {
            "type": "service",
            "state": {
                "url": "https://api.pulumi.com",
                "owner": "lukehoban",
                "project": "goapp2",
                "stack": "luke-dev"
            }
        },
        "resources": [
            {
                "urn": "urn:pulumi:luke-dev::goapp2::pulumi:pulumi:Stack::goapp2-luke-dev",
                "custom": false,
                "type": "pulumi:pulumi:Stack",
                "outputs": {
                    "password": {
                        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                        "ciphertext": "AAABAMD6S3+w9nM8Th7d6tzQl+PL8WMu1A8EDgsXqYDLT8GEfJM9cIDLfZo="
                    }
                }
            },
            {
                "urn": "urn:pulumi:luke-dev::goapp2::test-pw::abc",
                "custom": false,
                "type": "test-pw",
                "parent": "urn:pulumi:luke-dev::goapp2::pulumi:pulumi:Stack::goapp2-luke-dev"
            },
            {
                "urn": "urn:pulumi:luke-dev::goapp2::pulumi:providers:random::default",
                "custom": true,
                "id": "f866d170-b057-4331-9df2-a70271784625",
                "type": "pulumi:providers:random"
            },
            {
                "urn": "urn:pulumi:luke-dev::goapp2::random:index/randomPassword:RandomPassword::test",
                "custom": true,
                "id": "none",
                "type": "random:index/randomPassword:RandomPassword",
                "inputs": {
                    "__defaults": [
                        "lower",
                        "minLower",
                        "minNumeric",
                        "minSpecial",
                        "minUpper",
                        "number",
                        "upper"
                    ],
                    "length": 5,
                    "lower": true,
                    "minLower": 0,
                    "minNumeric": 0,
                    "minSpecial": 0,
                    "minUpper": 0,
                    "number": true,
                    "special": true,
                    "upper": true
                },
                "outputs": {
                    "id": "none",
                    "length": 5,
                    "lower": true,
                    "minLower": 0,
                    "minNumeric": 0,
                    "minSpecial": 0,
                    "minUpper": 0,
                    "number": true,
                    "result": {
                        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                        "ciphertext": "AAABACUjW4WmUZCU/4AHfFXlWbgcl6aPSCpMjHpX/zLCnsd8k7hIQXXKhx8="
                    },
                    "special": true,
                    "upper": true
                },
                "parent": "urn:pulumi:luke-dev::goapp2::pulumi:pulumi:Stack::goapp2-luke-dev",
                "provider": "urn:pulumi:luke-dev::goapp2::pulumi:providers:random::default::f866d170-b057-4331-9df2-a70271784625",
                "propertyDependencies": {
                    "length": [],
                    "special": []
                },
                "additionalSecretOutputs": [
                    "result"
                ]
            }
        ]
    }
}
```
