### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2835]
A few specific things:
- [ ] Specific versions of dependencies (presumably kept up-to-date with https://github.com/pulumi/scripts/blob/master/ci/install-common-toolchain.sh)
- [ ] Clarity that sources must be in `$GO_HOME`

**Comment by pgavlin** [comment]
Closing this as a dupe of https://github.com/pulumi/pulumi/issues/1559
