### ISSUE TITLE
'ee_perf' test needs to be reenabled.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#2856]

**Comment by ellismg** [comment]
Chris, we've seen this test be a bit flaky over the course of the past few days where it exceeds the deadline by a huge amount:

```
integration_test.go:52: Test step "pulumi-update-initial" took longer than expected. 34.10 vs. max 8.00s
```

Do you have a sense for what could be causing the large variability here?  I am guessing that your changes you are making to how engine events are sent will have an impact here, is there a way we can get tighter bounds here?   I know we don't call `t.Parallel()` here, but I don't know if that is something specific to any work spawned inside the test method or if it actually means (This method itself does not run concurrently with the other TestXXX methods in the `integration_test.go` file)

**Comment by chrsmith** [comment]
Yikes. I've been looking at this perf issue for a while, and there are _a lot_ of variables to consider. But the good news is that I'm already working on cleaning up a PR and testing a fix for this. So I suspect we'll be able to reenable this test (doing even more work within less time, no less) soon.

**Comment by lukehoban** [comment]
Can we somehow capture a perf trace on one of these tests that takes 10x the expected time so we can understand what subsystem is actually to blame?  I’d love to have some real data here.

**Comment by chrsmith** [comment]
Fixed in #2858 . Please let me know if you see that test fail in the future, as it should have more than enough "wiggle room".

**Comment by leezen** [comment]
Not sure we actually need to do anything more here unless I'm missing something, so closing.

**Comment by chrsmith** [comment]
Nope, all is well. For posterity the test in question is `TestEngineEventPerf`:
https://github.com/pulumi/pulumi/blob/2585b86aa4252b1ea430dbfd2324c47ea57763b1/tests/integration/integration_nodejs_test.go#L35-L55
