### ISSUE TITLE
Consider using panicwrap for better error reporting

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#286]
The [panicwrap project](https://github.com/mitchellh/panicwrap) is a nifty way to improve diagnostics.  It forks the process under a watch that will catch panics and report them before crashing.  It's a little mind-bending at first but seems handy, especially for crashes "in the wild" (in the running service and/or in the hands of users).

This work item tracks looking into using this for all standalone executables.

**Comment by joeduffy** [comment]
I'm not sure we want to do precisely what this issue says, but I _think_ we still have problems with error reporting if the `pulumi` process itself panics.

We could just accomplish what this work item was after with some global `panic` handers on all of our Goroutines. Basically, anywhere we today say `go ...`, we would need to say something like `cmdutil.Gowithhandler(func () { ... })`.

Reassigning to @swgillespie in case he has ideas on how, when, and what to do here.

**Comment by lukehoban** [comment]
I'll close this out - as we look at improving our error reporting going forward - this is one of many technical solutions we may consider.
