### ISSUE TITLE
Backport the "Policy violations" error view from service

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi#2872]
The web UI has started to render policy violations as a dedicated stream, rather than re-using the "error" view as the CLI does. We should fix this.

**Comment by ekrengel** [comment]
Not sure if we need a new issue for this, but I noticed that when a mandatory Policy fails we do not print the console URL to the update/preview.

**Comment by chrsmith** [comment]
Merged a change to improve this in the Pulumi Service first. I'll back port the changes into the CLI once we support multiple violations in the same update. (Since for now we fail as soon as we see the first policy violation, so there isn't much value in improving the UI to support better reporting for multiple errors.)

**Comment by chrsmith** [comment]
Made some progress on this, but given the amount of refactoring required in the `pkg/backend/display` package, I'll need to split it out over several PRs. Moving to next milestone.

**Comment by ekrengel** [comment]
Some other things I've noticed that are bit problematic:

The CLI doesnt tell me what PP the violation is from.
```
Diagnostics:
  aws:s3:Bucket (my-bucket):
    advisory: [s3-no-public-read] Prohibits setting the publicRead or publicReadWrite permission on AWS S3 buckets.
    You cannot set public-read or public-read-write on an S3 bucket. Read more about ACLs here: https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html
```

The service appears to group PP violations, maybe based on the PP name (actual name). Which means that if I `aws-pack` locally and enforced by the service. The violations are grouped together. The non-local PP was actually v9 so my guess is were using some sort of map here incorrectly.

```
  Policy Pack aws-typescript (v1)
    [advisory] s3-no-public-read(my-bucket)
    Prohibits setting the publicRead or publicReadWrite permission on AWS S3 buckets.
    You cannot set public-read or public-read-write on an S3 bucket. Read more about ACLs here: https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html
 
    [mandatory] s3-no-public-read(my-bucket)
    Prohibits setting the publicRead or publicReadWrite permission on AWS S3 buckets.
    You cannot set public-read or public-read-write on an S3 bucket. Read more about ACLs here: https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html
```
