### ISSUE TITLE
Expose latest update status via cli

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#2876]
There should be a way to get the latest update status via the cli - either through `pulumi stack` or maybe a new `pulumi stack status`. If the most recent update failed, I might want to take a different action so need a way to check this programmaticallyl via the CLI before continuing. Currently this is only exposed via the service.

**Comment by ellismg** [comment]
We do have `pulumi history` today on the CLI which gives you a view of your deployment history (I'll fully admit that the output is not great today, but it does dump JSON which is helpful) so you could do the following:

`pulumi history --json | jq .[0].result`

To get the status of the most recent update.

**Comment by clstokes** [comment]
I didn't even know `pulumi history` existed! This gives me what I need (and was being asked for by a another user) - going to close this.
