### ISSUE TITLE
Consider exposing a Docker image without the pulumi entrypoint

### ISSUE THREAD

**Issue by Charliekenney23** [pulumi/pulumi#2891]
I like using immutable containers throughout my build stage. It would be really nice if I could roll my own docker image based on the pulumi docker image, install the aws plugin, install some dependencies and then run `pulumi up`.

If we end up moving to alpine for instance to decrease image size (I'm interested in taking this work if it's not currently in progress), we could expose the following images:
- `pulumi/pulumi-alpine` -> based on `python-alpine:3.7`, bundled with pulumi binary.
- `pulumi/pulumi` -> based on `pulumi/pulumi-alpine`, with `pulumi` set as entrypoint.

In the future we could have something like `pulumi/pulumi:nodeX`, `pulumi/pulumi:pythonX` and `pulumi/pulumi:golangX` to bundle the basic toolchain with the binary.

**Comment by ekrengel** [comment]
Along with this it would be great if we could improve the experience from Dockerhub. I noticed this page is scarce. At a minimum we should add:

1. link to github repo
1. link to the dockerfile used to make the image
1. a description

**Comment by lukehoban** [comment]
> Along with this it would be great if we could improve the experience from Dockerhub. 

This part is done.
