### ISSUE TITLE
Unable to cancel a preview with ^C

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#2895]
Perhaps I am going crazy, but I cannot seem to cancel a preview by hitting `^C`. Perhaps the logic to intercept, and gracefully terminate the update only applies to `pulumi up`? The only way to get out of this is to send `SIGQUIT` (`^|`)

**Comment by pgavlin** [comment]
We were unable to repro this after multiple attempts, so I'm closing this out for now. We can reopen if necessary.
