### ISSUE TITLE
Support pathlib.Path in FileAsset

### ISSUE THREAD

**Issue by astronouth7303** [pulumi/pulumi#2896]
`pulumi.FileAsset` currently only supports strings, not `pathlib.Path` or anything else bearing `__fspath__()`.

**Comment by ellismg** [comment]
Thanks for opening this!  If you're interested, we'd be happy to accept a PR.

**Comment by campbellr** [comment]
@ellismg any issue with me picking this up?

**Comment by lukehoban** [comment]
@campbellr Absolutely!  

In case you hadn't already found it - the relevant source code is at https://github.com/pulumi/pulumi/blob/31cb92d7b80a08a1527760cbbe2c3c6c1fa57900/sdk/python/lib/pulumi/asset.py#L35-L43

And there are some tests at https://github.com/pulumi/pulumi/blob/31cb92d7b80a08a1527760cbbe2c3c6c1fa57900/sdk/python/lib/test/langhost/asset/__main__.py#L25-L27
