### ISSUE TITLE
Support similar flow to terraform saved plan

### ISSUE THREAD

**Issue by omerlh** [pulumi/pulumi#2899]
Terraform allowed to save the plan generated by the plan command to a file, and then pass this file to the apply command. This ensures that the plan executed is the same plan that was reviewed from the plan command. Is this is something that pulumi can support in the future using `preview` and `up`?

**Comment by lukehoban** [comment]
This is generally being tracked in https://github.com/pulumi/pulumi/issues/2318. As noted there, the exact plan/apply feature may not be possible with the current Pulumi model, but a similar feature likely is, and is something we would like to support. 

I’ll close this one out for now. Feel free to add notes on that issue as well.

**Comment by omerlh** [comment]
Thanks!
