### ISSUE TITLE
Python Quality of Life improvements

### ISSUE THREAD

**Issue by astronouth7303** [pulumi/pulumi#2901]
As per Slack, here's a repost of some of my really general utility work. This is more like a discussion than a specific issue.

In my first few days, I've found some really rough edges in Pulumi.

I will discuss my solutions to these problems in additional comments.

## Python Async

The first and biggest problem has to do with the nature of async in Python vs JS/TS, and how that effects the usability of some functions. Python is a synchronous language first with async/event loops as an add on; the global/module-level context is synchronous requiring special calls to get to an async context.

Lets discuss `pulumi_aws.route53.get_zone()` specifically. This is a pretty necessary function if you're doing anything with route53 records. It is defined as a coroutine (`async def`) that returns a python-native awaitable, not a pulumi `Output`. With what is currently define (that I know of), there is no method of chaining (analogous to `Output.apply()`) or otherwise using it from the global synchronous context. Pulumi will happily accept it in place of a true `Output`, but that's it.

In general, there is no clarity or explanation of how users are expected to use async in Pulumi. (In contrast to other async projects, such as Django Channels/ASGI which makes it very clear how to do things in synchronous and asynchronous ways and how to bridge between them.)

## Component Resources

The second issue is more concrete and specific: Defining `ComponentResources` is full of boilerplate, and the documented boilerplate produces a resource with a significantly different interface from the standard ones:
* Some arguments have different names: `__opts__`/`opts`, `__name__`/`name`
* The registered outputs aren't available on the resulting object, making it significantly less usable.

**Comment by astronouth7303** [comment]
## Python Async

Largely, the way I'm dealing with this is defining a `FauxOutput` and `@outputish` to wrap coroutines in objects that match the `Output` interface, making them meaningfully usable from the global synchronous context. (There is also an `@and_then` for simpler, more direct coroutine chaining, but I consider this unnecessary with `FauxOutput`.)

https://github.com/dingbots/castle/blob/9d5765fb4356c5caccb787b436665e7bfd607cf2/utils.py#L121-L209

**Comment by astronouth7303** [comment]
## Component Resources.

Ok, this is pretty easy. I just define an `@component` that takes some arguments (like the full namespace name) and turns a callable into a full class. This dramatically reduces the boilerplate necessary, makes it easier to be more inline with other resources, and in general makes defining components simpler and more robust.

https://github.com/dingbots/castle/blob/9d5765fb4356c5caccb787b436665e7bfd607cf2/utils.py#L88-L118

**Comment by astronouth7303** [comment]
The only downside about these is that they're both based on fairly advanced understandings of their respective areas.

By my own "magic barometer", the level of advanced magic here is acceptable for what they're accomplishing. However, if they are going to be incorporated into the project and Pulumi Inc is going to be maintaining them, you may have your own barometer based on your talent.

**Comment by astronouth7303** [comment]
Ok, new one: tasks.

Turns out, pulumi is generally really good about dealing with tasks. But (asycnio's fault, but makes development hard)

* Defining them isn't super great
* Tasks fail silently with the only indication that they failed that stuff does't get done, or pulumi just flat fails

**Comment by astronouth7303** [comment]
(And yes, I'd be happy to submit a PR for the actual changes, assuming that Pulumi wants them. I just figured a discussion about them first might be in order.

**Comment by lukehoban** [comment]
@astronouth7303 Thanks for the deep investigations here.  I have not yet had a chance to go deep here - but either myself or @ellismg  or @CyrusNajmabadi will take a deeper look shortly.  We would definitely be interested in PRs to improve things in this area if there are clear steps you already know should be taken here.

**Comment by astronouth7303** [comment]
This is basically me saying "Look, I'm writing a bunch of utilities to make pulumi/python more usable while y'all do that deep magic stuff mentioned elsewhere, and I'd like to publish it for others to use."

I guess, my question is: Would you rather build it as a 3rd party package on pypi or contribute it directly to pulumi?

(Also, I'm still actively developing some of the code as I start doing more complex things and building up other things; see the full repo. The links above are permalinks to the version at the time.)

**Comment by lukehoban** [comment]
> Would you rather build it as a 3rd party package on pypi or contribute it directly to pulumi?

Would definitely love these in `pulumi/pulumi`!

A key thing I would love to understand is structurally what the right way to address these issues is, and at what layer to best tackle them.

For example, you note the issues stemming from `pulumi_aws.route53.get_zone()`.  One of the things we have considered is making these functions (functions that wrap `invoke` RPC calls) synchronous.  There is fundamentally no reason they are not synchronous in Python.  If we were to do that, would we be addressing the whole issue here?  What is not clear is whether there are also fundamental issues related to the use of futures underneath `Output`.  I have not seen any clear examples of deep problems on that side of things - but would be very interested in talking through them if there are additional examples of concrete issues related to resources and `Output` (vs `get_xyz` methods and explicit use of Futures).

**Comment by astronouth7303** [comment]
None of them are super deep problems; that's what "quality of life" means--"Yeah, you've got the right idea, but it's kind of a pain to use"

Making `get_zone()` either syncronous or something that implements the `Output` interface would both fix that problem--a bare coroutine just doesn't do that much in Python, and to do something useful you either need to bubble it up (that is, use it from other coroutines) or wrap it up (what my `FauxOutput` does).

As I dig and think about it more, one of the biggest problems is making `ComponentResources` behave more like pulumi-defined `Resources` and smoothing over rough edges in implementation. This includes:
* Supporting sync and async initialization
* Making outputs available on the object immediately, usable for further composition, as outputs, etc
* Dealing with inputs and unifying if they're immediate or delayed values. (eg, sometimes its hard-coded and sometimes it's an `Output` and dealing with both cases in the Component's code is just annoying and messy)
* Even just making the construction signatures more similar

Together, these changes make components much easier and more consistent to use.

**Comment by CyrusNajmabadi** [comment]
Hey @astronouth7303 could you clarify this bit:

> Making outputs available on the object immediately, usable for further composition, as outputs, etc

I'm not sure i understand that one.  Thanks!

**Comment by astronouth7303** [comment]
First of all, the standard boilerplate doesn't make outputs available on the object at all:

```python
class MyResource(pulumi.ComponentResource):
    def __init__(self, name, opts = None):
        super().__init__('pkg:MyResource', name, None, opts)
        bucket = s3.Bucket(f"{name}-bucket", opts=pulumi.ResourceOptions(parent=self))
        self.register_outputs({
            'bucketDnsName': bucket.bucketDomainName
        })

component = MyResource("component", ResourceOptions(providers={
    "aws": useast1,
    "kubernetes": myk8s,
}))

pulumi.export("dnsName", component.dnsName)  # This will blow up
```

(Looking through the JS examples, this itself might be a bug?)

Additionally, if the set up body is async (using the latest version of my `@component`):
```python
@component()
async def MyResource(name, __opts__):
        bucket = s3.Bucket(f"{name}-bucket", opts=pulumi.ResourceOptions(parent=self))
        return {
            'bucketDnsName': bucket.bucketDomainName
        }


component = MyResource()

pulumi.export("dnsName", component.dnsName)  # This will blow up
```

The outputs won't be registered until after the coroutine completes, when there needs to be an `Output` at `.bucketDnsName`.

```python
@component(outputs=['bucketDnsName'])
async def MyResource(name, __opts__):
        bucket = s3.Bucket(f"{name}-bucket", opts=pulumi.ResourceOptions(parent=self))
        return {
            'bucketDnsName': bucket.bucketDomainName
        }


component = MyResource()

pulumi.export("dnsName", component.dnsName)  # This will now work
```

Now, given the issues I mentioned above about normalizing data passed into and returned from components, a future version of `@component()` may not be so flexible about the function its decorating.

**Comment by joeduffy** [comment]
> Making get_zone() either syncronous or something that implements the Output interface would both fix that problem--a bare coroutine just doesn't do that much in Python, and to do something useful you either need to bubble it up (that is, use it from other coroutines) or wrap it up (what my FauxOutput does).

I see two decisions here:

1. Do we offer async, sync, or both variants of resource functions?
2. If async, are those of type `Output[T]`? At the moment, they are `Awaitable[T]`.

For 1, there is no question IMHO that we should offer synchronous variants. I wonder if this should even be the default -- although just offering `*_sync` variants would at least be compatible. Even if we provide synchronous versions, it would still be reasonable to offer asynchronous variants too, for the same reason you might want to do async I/O for long-running activities.

For 2, we have the same decision to make for Node.js and it has caused us similar trouble there.

**Comment by astronouth7303** [comment]
It seems like you'd want an `Output`-like for consistency? Like, it doesn't imply any dependency information but can be used in all the same ways as a true `Output`. (Remember that `Output` serves two purposes: (1) To track dependency information of what resources provide information to other resources, and (2) to provide usability features around promises/futures/deferreds/etc. The primary problem of `get_zone()` etc is that while 1 doesn't apply you still need 2.)

As for sync/async, I'm not sure what value having both would bring? Like, this feels like an area you should figure out what best practices are and just do that. It doesn't seem like having both enables different use cases, just different styles of the same thing.

**Comment by CyrusNajmabadi** [comment]
> First of all, the standard boilerplate doesn't make outputs available on the object at all:

This is effectively expected.  For a component, you control what you want on it (it's basically a normal class).  So if you want to expose any outputs, you can do so.

```py
self.register_outputs
```

For pulumi, the reason to call `register_outputs` is to effectively say "this component has completed running.  It's basically a way for us to know that your constructor has done all the work it needs to do.  At that point any UI we have will switch from the `creating...` stage to the `created stage`. 

There's only one type that really need to pass any values to `register_outputs` and that's the root Stack type.  This is how *it* effectively exposes stack outputs to the rest of the world (and it's what you see printed after a `pulumi up` completes.  We don't use this for any other components (or, if we do, it's old code that needs to be updated) :)

**Comment by astronouth7303** [comment]
@CyrusNajmabadi you seem to have completely missed the point. My complaint is that outputs are not assigned as attributes on the resource, meaning registered or not, nothing can access them and you can't use them in composition, chaining, or just exporting. So there's aspects of the boilerplate that are not documented. (And needing to both save outputs on attributes and give them to `.register_outputs()` feels extremely redundant.)

If `.register_outputs()` doesn't actually need outputs given to it, the boilerplate should be updated.

**Comment by astronouth7303** [comment]
(Oh, and the phrase "boilerplate should be updated" epitomizes why boilerplate is not great and should be refactored into utilities/macros/libraries/etc)

**Comment by CyrusNajmabadi** [comment]
> First of all, the standard boilerplate doesn't make outputs available on the object at all:

This is effectively expected.  For a component, you control what you want on it (it's basically a normal class).  So if you want to expose any outputs, you can do so.

```py
self.register_outputs
```

For pulumi, the reason to call `register_outputs` is to effectively say "this component has completed running.  It's basically a way for us to know that your constructor has done all the work it needs to do.  At that point any UI we have will switch from the `creating...` stage to the `created stage`. 

There's only one type that really need to pass any values to `register_outputs` and that's the root Stack type.  This is how *it* effectively exposes stack outputs to the rest of the world (and it's what you see printed after a `pulumi up` completes.  We don't use this for any other components (or, if we do, it's old code that needs to be updated) :)

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi you seem to have completely missed the point. My complaint is that outputs are not assigned as attributes on the resource, meaning registered or not, nothing can access them and you can't use them in composition, chaining, or just exporting

I did get that :)

My overall point was that the expected usage pattern for *components* is for the author to be in control over what is assigned or not.  So, in your case, it wouldn't be:

```py
bucket = s3.Bucket(f"{name}-bucket", opts=pulumi.ResourceOptions(parent=self))
```

but rather

```py
self.bucket = s3.Bucket(f"{name}-bucket", opts=pulumi.ResourceOptions(parent=self))
```

Note that this is in line with how we treat things in JavaScript/TypeScript.

>  (And needing to both save outputs on attributes and give them to .register_outputs() feels extremely redundant.)

Sorry if i wasn't clear.  You don't need to give them to `.register_outputs`.  The only type in the system that really does this is the Stack type.  The argument basically exists just for that type alone.  As i mentioned, in our TS/JS sdks no other components pass along these outputs.  They only call `.register_outputs` solely to let the ui know "the component has finished being created".

**Comment by CyrusNajmabadi** [comment]
> As for sync/async, I'm not sure what value having both would bring? Like, this feels like an area you should figure out what best practices are and just do that. It doesn't seem like having both enables different use cases, just different styles of the same thing.

There's a few reason to have both:

Having async is good for apps that may end up creating a lot of expensive cloud resources.  Being async means that these can effectively be created in parallel, which can improve overall running time for a complex app.  However, the downside is the extra burden this places on the consumer of the library.  They now have to move to the more complex async/await coding pattern, which may not be desirable in many cases (especially for simpler apps.

'Sync' is nice for the reverse reason.  It's easy to code against and doesn't require any sort of complex coding to deal with.  However, it does mean you block until the full call happens (which could be expensive/unbounded esp. as it may involve the network).  For many this might be fine.

**Comment by lukehoban** [comment]
Honestly I can't really think of a reason why we would need async version of these in Python if we had offered sync vresions.  These `.getXYZ` calls don't do super-long-running work, they just do lookups.  Doing this kind of thing in async code in Python is pretty unusual, except for high-performance web servers or the like - which is a very different use case.  

The worst thing that would happen that I can tell if we dropped the async versions of these is we may lose a tiny amount of concurrency opportunity.  Is that worth having two versions of all of these APIs?

**Comment by astronouth7303** [comment]
> Sorry if i wasn't clear. You don't need to give them to .register_outputs. The only type in the system that really does this is the Stack type. The argument basically exists just for that type alone. As i mentioned, in our TS/JS sdks no other components pass along these outputs. They only call .register_outputs solely to let the ui know "the component has finished being created".

And hence my point: Your documented boilerplate is wrong, and having copy/paste boilerplate this complex leads to these kinds of problems. (The "standard boilerplate" example I gave above came from the [programming model](https://www.pulumi.com/docs/reference/programming-model/#components) documentation.)

> The worst thing that would happen that I can tell if we dropped the async versions of these is we may lose a tiny amount of concurrency opportunity. Is that worth having two versions of all of these APIs?

As far as I can tell (from my limited perspective) there is limited value, and you should just pick one and go with it. And if you go with async, the returned object should implement an interface similar to `Output` because of the usability that interface provides for using future-likes in a synchronous context.

**Comment by CyrusNajmabadi** [comment]
> (The "standard boilerplate" example I gave above came from the programming model documentation.)

Thanks for letting me know.  I'll file a doc bug to get that fixed up :)

**Comment by CyrusNajmabadi** [comment]
> Honestly I can't really think of a reason why we would need async version of these in Python if we had offered sync vresions. These .getXYZ calls don't do super-long-running work, they just do lookups. Doing this kind of thing in async code in Python is pretty unusual, except for high-performance web servers or the like - which is a very different use case.

That's a good point.  Should we then just do the same for TS/JS?  We're only async because of GRPC.  But we can just hide that and be fully sync so people don't have to deal with the async complexity.

**Comment by lukehoban** [comment]
https://github.com/pulumi/pulumi/pull/3019 is merged now, which enables us to make `.getXYZ` calls synchronous.  We still need to push out the code generation changes into providers before closing this out.

**Comment by astronouth7303** [comment]
I would argue that defining Component Resources should still get a pass: Dealing with immediate vs async Inputs, correctly producing Outputs, probably a few other things.

**Comment by lukehoban** [comment]
Fair enough - this issue was indeed tracking many different topics.    I believe the most severe of these was the many issues around asynchronous `getXYZ` methods, and that's the one we've specifically focused on addressing immediately - though the others are all great topics for further discussion.

**Comment by lukehoban** [comment]
https://github.com/pulumi/pulumi-terraform/pull/447 is also now merged, so once provider packages pick this up the synchronous `getXYZ` will be avaiable.

**Comment by pgavlin** [comment]
I'm going to close this out; we can file distinct issues for follow-up as necessary.
