### ISSUE TITLE
Possible to write provider's in typescript?

### ISSUE THREAD

**Issue by breathe** [pulumi/pulumi#2903]
Is it possible to write pulumi provider's in typescript?  I'd love to use pulumi to manage resource state in arbitrary small/random third party services -- would be amazing if I could write provider's in language with which I'm familiar to be able to do this ...

Is it possible?

**Comment by lukehoban** [comment]
It is indeed possible!  See https://pulumi.io/reference/programming-model/#dynamicproviders.
