### ISSUE TITLE
Fatal error when encrypting a secret using a file

### ISSUE THREAD

**Issue by lee-baines** [pulumi/pulumi#2907]
I'm guessing the encrypted string is too long as it is 3285 chars long.  The file I'm encrypting is a GCP service account:

***serviceaccount body removed for security purposes***

Here is the resulting error:

The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v0.17.21
Go Version:       go1.12.6
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            regexp: Compile("\n\\$\x00\x02>8\xd9X\xa8\xb8\\(\xc4Fv\xa3g\x8cd\xa0\\)\x9f\xd0F\\[V9\xe2\xe3\x1a\x95r\xda\xf6\x99\xa9C\x82\xb3\x12\xce\x12\x00`\x90\x00\xee\xdc\x1ds\xf9\\.\xd1\U000195247\xcc\x14\x86'k\xc3\xe0\"\xef˂\x00I\x9f'@\xe91\t\\*\\*g;\n\x18&\xcfBY\x1e@\x03Z\xd9o\xe0\x94\xf2\xcd\xefm7iF\xbe\xd8\xccBNוk\xf4\xd5ʝ\xc3C\xed\x0f\xa5\xf42HJ\xb1̟\xec\\.\xc6\xf2\xb7\x93\xe6d\x1caM~녨2\xdc`\"\xb9\xaa\xbf ø\x02\xb13\xc09\x9f\xe2:V\u007f<syc\x1ehz\xe5\x15\xf7\x9e\x01k\xa4\\*\xdd_\xa8I\\)\x81\xb7\xd6dV\xae\xc8Yi\\(x\xe7\xebM\x831\xc03\xb8o/a\x1d\xdfE5\xdfp62\x9ev\xc0!\xa7\xf7\x98\\[\x06<\\.G\xb1\xb3\x1d!\x16ꎌ\xb7\xfaQ\"\x1b\\}\nJ>\x8d\\[ϔ\x0f\\$\xef\xbdsO\xe1\xddػO\xab\x98ML\xf6U\xbf-EӸ'\xbf\x15\x11\x02\x0fٲ\xfb\x03p\x97\x11\xff\xf4\xd3A\x0f\t\x1b\xca\xc0\a\xd8bo\x00W\xcc3\xb0B\xd5\\$\xb17x\xaf\xf6\x9b\xb6\x87\\.\x86t\xbb3\x90\xefugy\xfe:z\x91f\xa9nU\xe8\"\\?\xd8#h\xc7Ά\xeb\x98p\xd7寎c\xb1c\xf7\xe6g\x88\xe8\xd1O\x1eէ\xf3\xcd\\|H\xc2\xfa\x1a\xe2\x15ѥ\xf4\x1f\f\xc9!aU\xe9\x9b1\xad\x92\x9b\xc0g\x85\xc6\xd4~ֳ\xa6<\xc1\xbf:\xd5\x1f\x1c\xba\x06\xbc\x94Kg\xeaAm9\xcb\xf13\x03\xf8\xf4\xe5\xba=f\xcbָ\x8a\xc0\x05\xa2\xb3\x0e\xec\xe2\x9e\\*\x83\xc8\xe6\x19\x87D\x9c\xe0\\]\xdf\x13\xe0\xb9\xfdsi\\^\x96\xdc\x15\xf9\xeb\xbf\xe1\xb4\x19\x85T\xba\x13\u007fm\x8c4\x9a\xa2\x11ѻ\x10\xfb\xb4\xa0\xaa\xeb\xbe\xdcKw\\[l\xce\\.-\xf6\xf4\xb9\\}N\x17\x9af\xbasY\\}A\x83\\{e\xaf\xa9\xf8\xee\x15\xe5\x04V&8\x16\xb9 \x87\xa0\xbd\x19\x13\v\xa5\xfd\xe7\xfc\xab\\[u\x82\xc4zKޖ8\xf0b\x03d\xaeU\x13\xa2I\xf3-\xd5\xe1\x92gh\x15bA\u00a0\xa5\xee\xa7D\\\\%\x9e\xa0\xafYD\xf8g\xf3Aѥ\xbb\x88\x91\xa9\x19\\.\xc3\xc6B\xf7\xcdf\x12\\)\\*\rv\xa8\x85\x96\xb3C\xdft\xa0\x9cEVh\x19z\x1chK\xfc\xd7h\x91u\x11\r\xae\xd7x\xc1\xbe\xac\xfd\x98\x0e\x95\x8cp\xc2f\xef~\x11\xbc\x81\x93\xb0\xbe\x1d\x19J\xf24\\)\\*PS\xb1!\"n8g\xeb\xde\\$\x8d\r2\xcea\x96\xd0MhRR\x94\x0f\xc2\u007f\xafM!\xf8Oa䰞S,\x11\xf2ɐ\xd3=\xce1\xec\\)\xef\xf8\nm\xc3И\\}o\\+zI\x00\xbd'z\xc7\xd3m\xcc\xea\x16\xba\xe7G\xadO\x837\x89\\{\xab\xbc\xaa\u007f\xb7\x16\xca\x01#\xbb!\x89\x84J\xd6X\\]\x02f\x18\xa1\xbfƷsE Z\vC\xcf`\x1b-\xa8\xc3r0:F\\]\xf3\x1a\x9e\x94\xddَ\xd7`x\x18\xa70\xfcIi\x94\xad\x87d\xe3\x8c\fÇ\xa01\x12\x92\xdf\xd9\xe4\x86D\xdbQ\x9f_\x1cZ\x8ey\x15`\xdaL,\x9c\x8e\xfc\xfa\x1dR\xb9o~\x1eM\x95\x13\"\\(\x1a'\x0fP!v\xa0\r\x1b\xbe\x1aݵ\\$ac\\(\\^\\[ND\x1c7\x1a\xad\xd6>:\x93\xdeD\xb2f\x84N\xa7\x15\x9e\xfe<\xcb\x13s\xaf\xa6dtp\x162aް\\^7j\x14\x95\v\xe32\x8ec\xf4\x1fn\xb1\xbb\xeaD0mc&\xba\aȐ\x85U\x10\\]\ndx\x14\x87bv\xaev@\xcdڸ\xb4\xbb\x04,\x95\x1a\x1a\\\\Zږ1#\x0fͦ߮\x90\x94\x14\xf9%\xe2\xa1\xd7\xf5\xc8\xe3S\x05\\?\xe9\xcb\xc9Ф\xfcQӫ\x9d\x01p\x83\xdcA\"\x81\xba\xa4\r6>\xc2o\xff\x8a\\|\xcb\x05'\xd4\x1d\x05\xb6p\xff5>=\\]R\\)\xff\x02ܷ4\x1c\xae\x9b\x12\xea>_y\x97\xa6\xa3g\\|\x81\xec\xfbnc\xb2H\x84\xa8\xc3N\xce\xde/\xcai\x94\xa0\x8d\xa180Z\xc7T\x15\xd6\x01ş\x84٨A\x81\x92\x97\xa9\x1a\xf4\x95\x9c!&3\xda\\?X\xdd0\xaa\xbb̎\x82\x9aS\xb7\xa0\xac\xf4\xc4\x02\xa1p\x89\xe9b\xb8K\x98&\\)\x16\x83\xfa&\xa8\xb9\x11\xc6\x06A\r\xc8U0\x8b\xc6~\xa0\xd88LXi\x1f\\}4m\x14\xa6\xff\x95\xe5\x04\\(,ݹ\x9d\aV\x16\x89\xdf\x11\f\xbc\n\xa3\t\x80\xb4\\+\xa9\x92\xec\xef\xc1 i\x95\x170\xe82`k\xbfJ4\x9f-\xa4\xb4>\xc1\xdb~\xb1\x1cF\xac\x82\xb3V\xce\xee\x04\u0088\xaf\xc0\xc3l\x8d\xf6܍0\xe2\xab\xf7\xb1\xec˛xTy\t<\xe1\x15\xb3\x94\xa3\xfd\xd7t3\x85D\xf5\xa9\xcd\xf1ZL\xb4\xbde>\\)\xb3\x1b\xe6\xa02\xc1\xf0\x88\xbf\xf1l\x04`\\$\xd7\\^\t\x1eJ\xfe\x11F\x1c\xf2\xe4\\|\xb1ВL\xe2\x97!\xb5\xf9\x9c\t\x06\xef\xfd\x1e\x96%C\\[\xc7G\x16\x14\v\\?\xfbkiP\xa4#Th\xc3\xc4\x15-\x8e0n\x0f\x9d\xf7\a\x13\x1d\xd5p\xb8\\\\P\xe59\xd3\ue13e\xb5R:\xfeU\x8e#z5\x9c\xfb\x87\xbb0\u007f\xde\x10\xf2C\x04\x0e\u2e68l\xad\xc4n\x97\\\\#\\}\u007f\xb9ڪf\xab\xf6\xa5v\x8e\xd3\xe9\x84\xc3\x14G\xc7t&\xd1\\(\xb0ju\x90\xdfb-\x91\x88\xa0r\xb7\x8c3\x80&\x02N\x18\xc5\xc3\xd3\x16\x8e\x92\xa4\xe3L\xa4<\x14\ue431\x81G\xf2wh\x0f\x19A<jDK\xf1\xf4\\\\\x8dd\\*\x84\xfe\\.s\x0f;o\\)Μ~\r\tbu\x18\x95/I\x16ā\xcdC\x83L\x15\x1a\x12&\x8aZir\xdb\xd8\xf7\xc7\x117S\xa2\xb7\xddL-\xe3~\xac\xa8,\\(\v&\x15f\xcah\"\xa3\xd0\x18\xdb\\\\@\xa7\xdf\xfe\xc5\xf5\xbc\\)Z\\(\x93\v\x9eZ\xd4\x12\xb2\x0e\x8bn\x81u㗅7F\xa0\xa9\x9a\xea\\^\xfe\xf6<\\+\x16\xb1@\x16\xe6\x02L\x04\xa6\x8cz\xe2wE\x9c\xdaX\x88g\xd8\xc8\xc9r\xc0\xe7\x8f\x12\xda1p\x8fs-\xa5\xf0s\x14\\{\xb5\x0eQ\xc1\x12A\\^\xb0\x92\xa9~=R\x8f\xa1\xb9v\x82\xa0\x14 \x86Kbi\xdf\xf1\x8f\xfe\\]\x10>̤\xb1\x036\\^CI\x00\x15\n6\xb9_\xd20\xa7\xd7b\xfd&,\xbb\xebN\xb1YHx\xe98\x8eB\x92\xa7d\x8c\xaa\xd3`h\x9b\\[\xcdjo/\xb8K\x9d\x863\xfbڪV\xb9\xba\xc2\xe2\vxTމ\\]bE\xd1ӭ\x13\x8cq\xa6e\t\xe4\bR3\xe2\xfe\x1b\xc0\x85\xb8\\}\x1a\x17C\xa0F\\}\n\\[\xfb\xa6\xfe\xea\xfe\xce\r\x83\x1b\x01D\a\xbc\x0e\xfeg\x19\xe1荀\xb8Jm\xf6\x15\x98\r\nA-Y\x85\xf2\xb9\xa6t2i\xda\\}\xc8'\x1e\b\xd4ˆ\xbf\xf6\xe3\xa67WF\\\\vFu\x14\xb5\"ʤiz\xa5\xc9V\\.\x10A\xb4\xe0B\xea\xb6Vy\xd3-\x99\x9d~!o\xeasт\xa6\xf0&F\xd5\xd8\x1e\x83\\[ڝ\x1dG\xc4\xe2\xf8\xc3\x01\x13\xbe\x05\xa3\x1e\x06\xc0;G\x0f\\+\x11\x1c\\$\xf7#\xb7\xa3\xea\xef6\xa8T\x0eϸ/\xe4_Cٳ\x1cz\x9e\xf0-\x0f\x88\x97\x87\r\x0e\xb9\x9d\x04\\}\xd67\x10\x13\\{lSI\xe0,cP\xa7v\xf1-\xe9\x1b\xf6\u007fIVF\x88\"5\\*\x1d\xe8\xb0XQqV#,tb\xbd\x90\x04E\xfa\\?7\xbb\x05i\xe7\xc7\\]o2W\xb5\xe1\xfd\x13ľ\\(\xeaB\xc0\x9a\xf9\x1b\xa2\x115V\x18\xa0\xfb6\xa9\x04\xec\U0009b310:\x84\xf1\xce\xc8h\x1bL\x9c\xd0\x1c\xc3\xe5\xe5\xe3\x98\xf8\x1f\xbb\x15\x14T\\[Rz\xbc\x13\x96\x8b4\xec\x82\xe5Ս\xf2\x8eh<`e\x84\xc8\xf5\x9b\xc8f\x93/\x05Q\xc8\xf1e\xac\x84\x9a\xaasv%\xa3\xa2\x85\xafU4h\xceQE\x83x\xd1\"\xea\x984\\$\xf6p-\x04\xc2\x19\x1f\x86\x12\xa5\xeat,\x87\xe4\x1c\x9f\xe1\xdd\xf4\xbf\x9aUbQu\xef\xf7\x1bPī\x9e\x92 ÚܤY\xce\v\U000f9811\xc6Y\n\xc5\xc2C\xa1\xda7\x15͐\x9c-\x8c\x81Z/\x1d\xca_Z_\x86\r\x88\xdct\xfdy\x92\xcd\x00\xa8KW\\(\xb9\x057L\x81\\[\x95\xe9\x1aVL\x0fi\xb9ْ\"\x83s\xe9_\xcbY\xd1\xe7#\xe5\xcc\bSZ\x1a\xba\x95\xa6\xa42\b\xa07C\xbd\xc2Lɉچwn\x1b\xe7\xaa\\}\x9dn\\$E\xac\x16:\x1a\x80\xddx\x99`\xac\x12Y\xcc\x14\xa7\x11\xf3\xd5!\xb6I\fڎ\xb0\xad\xf7\xb4\xc0L\x85G\xf4\xf5\xb3\r'6\xb7\xaf\xcbX4Z\x15\x8ff\x84\x15\xd6\\{N\xfd\\}\x12\xb1\xb5m\xef\x02\xaf#\xd3a\x14L\x9a\xfa\xcdA\xc9\\{y<ڌ\x80\xd6\x1d\xc3\x1a\x8f\xdcM\x89N\xe1\xf6m\xdc@\\?\xe8s2&H\xf6\xb6\x1cnW\\*\\?\xa5\xf1\xff\xbf0\xb8w h\x05Nھ\xf1t\x97\x1e\r\tq\x16/\x1f\xe5\f\x8e\x1cU\x99U8\xee\xf6\xa5\a\xe4S\xd7v\xe6\x06\x98c\xb6\x06\x90\\^\xb9\x19k\xb1\r\xba\xb6\xcd\xf9'G\n\v\xec\\?\xe1\x04Q\x12\xeeAd\xc8\xd9\x0eZ\\^\\}\aT\x98H=\x9a̤\\)\\)t\xe9\xa9PJj\xe0\\}\x0e\xb2\x87MP\xfd5\x17\x96o\\)P\xa8\x83\xc9\xe1\xf7\xdc\\{\x8eԈ\xcb=잆qX:f\xd7\x02\x12\xa2݂d\x19\\\\\"dq\xbb\xbe\xdd\x11\xf4\x00s\xf9f\\)\x9e\xd2\x1c\xbeV~\x9cΧ\\)N\xb8\xa9Ju\xbeE\x05k\x89\x19a;Vݍ\\$\x16C\xbf\u008dʹ\xe0g\\+\xefWHcȫ\xba\xbd\x01\x85\x8f\x81s\xd6"): error parsing regexp: invalid UTF-8: `�X��\(�Fv�g�d�\)��F\[V9���r����C���`���s�\.�𙔤7��'k��"�˂I�'@�1        \*\*g;
&�BY@Z�o�����m7iF���BNוk��ʝ�C���2HJ�̟�\.���daM~녨2�`"��� ø�3�9��:V<sychz���k�\*�_�I\)���dV��Yi\(x��M�1�3�o/a�E5�p62�v�!���\[<\.G��!ꎌ��Q"}
J>�\[ϔ\$�sO��ػO��ML�U�-EӸ'�ٲ�p����A     ��boW�3�B�\$�7x�����\.�t�3��ugy�:z�f�nU�"\?�#h�Ά�p�寎c�c��g���Oէ��\|H���ѥ�
                                                                                                                  �!aU�1����g���~ֳ�<��:����Kg�Am9��3���=f�ָ������\*����D��\]���si\^������T�m�4��ѻ������Kw\[l�\.-���\}N�f�sY\}A�\{e�����V&8� ���
2�a��MhRR���M!�Oa䰞S,�ɐ�=�1�\)��n8g��\$��-��ghbA ��D\\%���YD�g�Aѥ����\.��B��f\)\*
m�И\}o\+zI�'z��m����G�O�7�\{�����#�!��J�X\]f��ƷsE Z
                                                   C�`�r0:F\]����َ�`x�0�Ii���d�
ݵ\$ac\(\^\[ND7��>:��D�f�N���<�s��dtp2aް\^7j�                                   Ç�1����D�Q�_Z�y`�L,����R�o~M�"\('P!v�
                                           �2�c�n���D0mc&�Ȑ�U\]
�U0��~��8LXi\}4m����\(,ݹ�V��_y���g\|���nc�H���N��/�i����80Z�T�ş�٨A�������!&3�\?X�0��̎��S������p��b�K�&\)��&���A
                            �
�       ��\+����� i�0�2`k�J4�-��>��~�F���V�����l��܍0����˛xTy    <������t3�D����ZL��e>\)�2�����l`\$�\^   J�F��\|�ВL�!��� ���%C\[�G
                                                                                                                                 \?�kiP�#Th��-�0n���p�\\P�9��R:�U�#z5����0��C⹨l��n�\\#\}�ڪf���v����G�t&�\(�ju��b-���r��3�&N������bu�/Iā�C�L&�Zir����7S���L-�~��,\(~
                                         &f�h"���\\@������\)Z\(�
                                                                �Z���n�u㗅7F����\^��<\+�@�L��z�wE��X�g���r���1p�s-��s\{�Q�A\^���~=R���v�� �Kbi���\]>̤�6\^CI
6�_�0��b�&,��N�YHx�8�B��d���`h�\[�jo/�K��3�ڪV����
                                                 xTމ\]bE�ӭ�q�e  R3����\}C�F\}
�[������
 ��g�荀�Jm��
��\}�7\{lSI�,cP�v�-�IVF�"5\*�XQqV#,tb��E�\?7�i��\]o2W���ľ\(�B���5V��6��򛌐:����h��������T\[Rz���4��Ս�h<`e�����f�/Q��e����sv%����U4h�QE�x�"�4\$�p-����t,��������UbQu���� ÚܤY�
                                                                                                                                                                          󹠑�Y
��t�y���KW\(�7L�\[��VLi�ْ"�s�_�Y��#�SZ�����7C��Lɉچwn\}�n\$E�:��x�`�Y����!�I
'6���X4Zq/��\{N�\}��m��#�aL���A�\{y<ڌ�����M�N��m�@\?�s2&H��nW\*\?����0�w hNھ�t��L�G���
����'G     �U�U8����S�v��c��\^�k�

�\?�Q�Ad��Z\^\}T�H=�̤\)\)t�PJj�\}��MP�5�o\)P������\{�Ԉ�=잆qX:f��݂d\\"dq����s�f\)���V~�Χ\)N��Ju�Ek�a;Vݍ\$C�ʹ�g\+�WHcȫ�����s�`

goroutine 1 [running]:
runtime/debug.Stack(0xc000486e38, 0x1d071e0, 0xc0015e6330)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
        /private/tmp/pulumi-20190627-53585-11t2ox7/src/github.com/pulumi/pulumi/main.go:30 +0x6e
panic(0x1d071e0, 0xc0015e6330)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:522 +0x1b5
regexp.MustCompile(0xc00054e000, 0x9f6, 0x9f6)
        /usr/local/Cellar/go/1.12.6/libexec/src/regexp/regexp.go:272 +0x159
github.com/pulumi/pulumi/pkg/util/logging.CreateFilter(0xc0015e6310, 0x1, 0x1, 0x1f54f24, 0x8, 0xc0015e6310, 0x0)
        /private/tmp/pulumi-20190627-53585-11t2ox7/src/github.com/pulumi/pulumi/pkg/util/logging/log.go:134 +0xf0
github.com/pulumi/pulumi/pkg/engine.makeEventEmitter(0xc0004aca20, 0x21d37e0, 0xc000b26bd0, 0x6, 0x0, 0x0)
        /private/tmp/pulumi-20190627-53585-11t2ox7/src/github.com/pulumi/pulumi/pkg/engine/events.go:187 +0x349
github.com/pulumi/pulumi/pkg/engine.Update(0x21d37e0, 0xc000b26bd0, 0xc000d772c0, 0x2c8d7e0, 0x0, 0x0, 0x7fffffff, 0x0, 0x0, 0x0, ...)
        /private/tmp/pulumi-20190627-53585-11t2ox7/src/github.com/pulumi/pulumi/pkg/engine/update.go:84 +0x221
github.com/pulumi/pulumi/pkg/backend/filestate.(*localBackend).apply(0xc00028bce0, 0x21dcae0, 0xc0000ee000, 0x1f54306, 0x7, 0x21f2f00, 0xc00155ced0, 0xc000938980, 0xc000741e50, 0x3f, ...)
        /private/tmp/pulumi-20190627-53585-11t2ox7/src/github.com/pulumi/pulumi/pkg/backend/filestate/backend.go:454 +0x127c
github.com/pulumi/pulumi/pkg/backend/filestate.(*localBackend).Preview(0xc00028bce0, 0x21dcae0, 0xc0000ee000, 0x21caba0, 0xc0001d3780, 0xc000938980, 0xc000741e50, 0x3f, 0xc0008e76c0, 0x2c8d7e0, ...)
        /private/tmp/pulumi-20190627-53585-11t2ox7/src/github.com/pulumi/pulumi/pkg/backend/filestate/backend.go:349 +0x192
github.com/pulumi/pulumi/pkg/backend.PreviewStack(0x21dcae0, 0xc0000ee000, 0x21f2f00, 0xc00128d890, 0xc000938980, 0xc000741e50, 0x3f, 0xc0008e76c0, 0x2c8d7e0, 0x0, ...)
        /private/tmp/pulumi-20190627-53585-11t2ox7/src/github.com/pulumi/pulumi/pkg/backend/stack.go:81 +0xeb
github.com/pulumi/pulumi/pkg/backend/filestate.(*localStack).Preview(0xc00128d890, 0x21dcae0, 0xc0000ee000, 0xc000938980, 0xc000741e50, 0x3f, 0xc0008e76c0, 0x2c8d7e0, 0x0, 0x0, ...)
        /private/tmp/pulumi-20190627-53585-11t2ox7/src/github.com/pulumi/pulumi/pkg/backend/filestate/stack.go:72 +0x86
github.com/pulumi/pulumi/cmd.newPreviewCmd.func1(0xc0001c6f00, 0x2c8d7e0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/pulumi-20190627-53585-11t2ox7/src/github.com/pulumi/pulumi/cmd/preview.go:111 +0x820
github.com/pulumi/pulumi/pkg/util/cmdutil.RunResultFunc.func1(0xc0001c6f00, 0x2c8d7e0, 0x0, 0x0)
        /private/tmp/pulumi-20190627-53585-11t2ox7/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:111 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc0001c6f00, 0x2c8d7e0, 0x0, 0x0, 0xc0001c6f00, 0x2c8d7e0)
        /private/tmp/pulumi-20190627-53585-11t2ox7/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c6500, 0x1facf38, 0x0, 0x0)
        /private/tmp/pulumi-20190627-53585-11t2ox7/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /private/tmp/pulumi-20190627-53585-11t2ox7/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
        /private/tmp/pulumi-20190627-53585-11t2ox7/src/github.com/pulumi/pulumi/main.go:49 +0x4c

**Comment by lukehoban** [comment]
We have code that tries to mask out any occurrences of the secret in logging output, and it looks like that code is failing to build a regexp to search for this string.

**Comment by lee-baines** [comment]
I've removed the service account body from the message as it had be scanned and raised as security breach by Google.

**Comment by mikhailshilkov** [comment]
The simplest repro for this bug:

```
pulumi config set v ab$'\xa7' --secret
pulumi up --skip-preview
```
causes
```
Panic:            regexp: Compile("ab\xa7"): error parsing regexp: invalid UTF-8: `�`
```

My understanding is the reg-ex can't support non-UTF8 symbols, so the workaround is to skip such a secret and do not include it into a regex. I will open a PR for this, let me know if you see better options.
