### ISSUE TITLE
pulumi_aws.route53.get_zone() doesn't forward exception

### ISSUE THREAD

**Issue by astronouth7303** [pulumi/pulumi#2908]
I think this is a runtime problem I just found in `pulumi_aws`?

I have this code:

```python
async def find_zone(domain):
    zonename = domain
    while '.' in zonename:
        try:
            zone = await pulumi_aws.route53.get_zone(name=zonename)
        except Exception:
            _, zonename = zonename.split('.', 1)
        else:
            return zone
    else:
        raise ZoneNotFoundError(f"Unable to find zone for domain {domain}")
```

However, the exception seems to never be forwarded to the code and instead just gets printed and aborts, with this backtrace:

```
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/astraluma/.local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
        return future.result()
      File "$VENV_SITE/pulumi/runtime/stack.py", line 38, in run_in_stack
        await RPC_MANAGER.unhandled_exeception()
      File "$VENV_SITE/pulumi/runtime/rpc_manager.py", line 68, in rpc_wrapper
        result = await rpc_function(*args, **kwargs)
      File "$VENV_SITE/pulumi/runtime/invoke.py", line 74, in do_invoke
        resp = await asyncio.get_event_loop().run_in_executor(None, do_invoke)
      File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "$VENV_SITE/pulumi/runtime/invoke.py", line 72, in do_invoke
        raise Exception(details)
    Exception: invocation of aws:route53/getZone:getZone returned an error: invoking aws:route53/getZone:getZone: no matching Route53Zone found
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

Given that I attempt to handle it above, I would guess that there's a manual Future in there that you're not forwarding exceptions to?

**Comment by ellismg** [comment]
@pgavlin Do you know if this is still a problem since we have now done https://github.com/pulumi/pulumi/pull/3019?  I suspect the fact that we now run this synchronously will have some impact here.

**Comment by pgavlin** [comment]
This should no longer be an issue, but I'll see if I can repro.

**Comment by CyrusNajmabadi** [comment]
Switching over to pat as i imagine this will likely be quite easy to validate.

**Comment by pgavlin** [comment]
I _think_ that this will still happen. I've been able to repro the original behavior, but I need to check again once a new version of `pulumi_aws` is released. In the meantime I'll see if I can verify with some hand-crafted code.

**Comment by pgavlin** [comment]
I've verified that this does not happen when using an up-to-date version of `pulumi_aws` with an up-to-date version of `pulumi`.
