### ISSUE TITLE
Expected outputs are not produced when using an async main function in Node

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi#2910]
I would expect the following program to produce an output name `bucketArn` with the value from the resource, however it produces no outputs.

```typescript
import * as aws from "@pulumi/aws";
import {ComponentResource, ComponentResourceOptions, Output} from "@pulumi/pulumi";

class TestComponent extends ComponentResource {
    private bucket: aws.s3.Bucket;

    public bucketArn(): Output<string> {
        return this.bucket.arn;
    }

    constructor(name: string, args: {}, opts?: ComponentResourceOptions) {
        super("TestComponent", name, {}, opts);

        this.bucket = new aws.s3.Bucket(`${name}-bucket`, {}, {
            parent: this,
        });
    }
}

async function main() {
    const component = new TestComponent("test", {});

    return {
        bucketArn: component.bucketArn(),
    }
}

module.exports = main();
```

**Comment by jen20** [comment]
Current versions:

`pulumi` CLI: v0.17.21
`node`: v8.14.0

**Comment by clstokes** [comment]
Occurs with these versions too if helpful:
- pulumi `v0.17.21`
- node `v12.5.0`

**Comment by lukehoban** [comment]
A simple workaround is:

```
export const bucketArn = main().then(m => m.bucketArn);
```

It is mostly unintentional that this does not work as written - if your module export is itself a Promise or Output, we should be able to handle that (just like we handle if it is an object with Promise or Output-valued properties).

**Comment by CyrusNajmabadi** [comment]
Fix available.

**Comment by CyrusNajmabadi** [comment]
> Is there a way to export multiple stack outputs?

Absolutely!  Just do this:

```ts
const mainResult = main();
export const bucketArn = mainResult then(m => m.bucketArn);
export const whatever = mainResult.then(m => yadda yadda);
export const whatever2 = 1 + 2 + floop;
```

basically, all your top-level exports become 'stack outputs'.  You can have those be outputs, promises, expressions, whatever. :)

**Comment by tigran-gruv** [comment]
> ```ts
> export const bucketArn = mainResult then(m => m.bucketArn);
> export const whatever = mainResult.then(m => yadda yadda);
> ```

^^^ Is it a guaranteed behavior to export promise and get the resolved value at the end?

**Comment by lukehoban** [comment]
>  Is it a guaranteed behavior to export promise and get the resolved value at the end?

Yes - the Pulumi JavaScript SDK will load your entrypoint module, then resolve all Inputs (Outputs or Promises) that were set on the modules exports. This is required and guaranteed behavior.

**Comment by fuadsaud** [comment]
I was bitten by this issue today and, as far as I understand, [the docs](https://www.pulumi.com/docs/languages-sdks/javascript/#entrypoint) seem to indicate that exporting an async function would work. Am I missing something?
