### ISSUE TITLE
Introduce compatible pattern to allow 'parents' to be more explicitly passed.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#2917]
Forgetting to pass parents today is extremely easy given both the optional nature of our 'opts' param, and the optional nature of the 'parents' property within it.  We've had dozens of issues about forgetting this, and it gets missed in CRs all the time even with experienced team members.

I propose the following non-breaking approach to this that we could adopt in the future to help alleviate this problems for component authors.

The basic idea is to just add an overload like so to 100% of our resources:

```ts
export class Bucket extends pulumi.CustomResource {
    constructor(parent: Resource, name: string, args?: BucketArgs, opts?: pulumi.CustomResourceOptions);
    constructor(name: string, args?: BucketArgs, opts?: pulumi.CustomResourceOptions);
```

Note that we'd keep the existing constructor around, and our base resource types would do dynamic introspection of the parameters to determine which overload was being called.  

We would also provide a switch/config/something option to effectively state that it as an error to use the legacy form.  This is similar to how TypeScript introduced things like the `--strict` flag to help catch issues, but only for those who wanted to opt into that.

This would have the virtue of:

1. being non-breaking.  All existing constructors would be around and would work fine.
2. making it ideally *much* easier to notice when things are bad.  Instead of having 'parents' be an optional property of an optional parameter, it would be something we could look for *right up front* when making a resource.  This would hopefully be much easier to spot during a CR.
3. We can enable our own switch locally to state that it's always an error to not pass a parent as the first ar.  This allows us to hit the pain immediately in our own libraries/tests, without being a pain for customers.  Customers could opt-into this if they wanted though.

**Comment by CyrusNajmabadi** [comment]
Note: from talking to @lukehoban we see this as a long term (i.e. 2.0) sort of thing.  But i'm just writing it down so it doesn't get lost.

**Comment by mikhailshilkov** [comment]
As this hasn't picked up any steam in 2.5 years, is somewhat node-specific, and the parent issue got closed, I'll go ahead and close it as won't do.
