### ISSUE TITLE
Allow `pulumi stack export` to get an unencrypted statefile

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2918]
Currently, if there are encrypted values in a checkpoint, it is not possible to get a serialized form of the checkpoint with decrypted values.  This can be important for importing into a new stack - whether in a different backend or even in a different org or project or stack in the pulumi.com backend.

We should consider adding ` —show-secrets` or similar to `pulumi stack export`.

**Comment by pgavlin** [comment]
Note that the exported statefile should retain information about which values are secret s.t. those values can be re-encrypted upon import.
