### ISSUE TITLE
`getXYZ()` methods fail in unit test mode

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#2921]
All calls to `getXYZ` methods (which use `invoke` in the underlying Pulumi resource provider to make calls to the target cloud provider) currently fail in `PULUMI_TEST_MODE`.

This is because test mode runs without a resource monitor, and thus has no ability to make calls to the engine and thus also no ability to make calls to a cloud resource provider.

For example - testing code that contains something like this:

```
const result: GetParameterResult = await getParameter(...)
```

Leads to this:

```
TypeError: Cannot read property 'invoke' of undefined
      at debuggable_1.debuggablePromise.Promise (/path/to/my/project/node_modules/@pulumi/pulumi/runtime/invoke.js:63:114)
```

Addressing this and https://github.com/pulumi/pulumi/issues/2785 will likely involve a fundamentally different approach to `PULUMI_TEST_MODE` unit test execution.

**Comment by lukehoban** [comment]
Even before solving for the fundamental limitation here, we'll likely want to improve the error message here.

**Comment by dustinfarris** [comment]
Is there a workaround for this?  Setting `PULUMI_ENABLE_LEGACY_DIFF` to true when testing doesn't seem to help.  I realize that the diffing change is not directly what's causing this issue.  Are there any other "legacy" flags we can set to get this working until things stabilize?

For now, we've had to peg @pulumi/pulumi@0.17.22 and @pulumi/aws@0.18.22.

**Comment by dustinfarris** [comment]
I believe this is the same as #2838 but without being wrapped in `UnhandledPromiseRejectionWarning` — probably due to synchronous features introduced in https://github.com/pulumi/pulumi-terraform/pull/422

**Comment by lukehoban** [comment]
Indeed - I'll close this out as a dupe of #2838.
