### ISSUE TITLE
Define configuration lifecycle

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#293]
Right now we simply let providers read configuration whenever they want.  This is unlike the work we just did in the bridge, where configuration is performed at very specific and well-defined point in the program's execution.  It's possible we want to do the same thing here, at least as a convention.  This will slightly change behavior because today if configuration is mutated during a program's execution, the provider will pick it up on demand (which means, in principle, we can do things like alter the target region partway through a single program's execution.

**Comment by pgavlin** [comment]
This is effectively moot as of first-class providers.
