### ISSUE TITLE
Proper OS packaging

### ISSUE THREAD

**Issue by eropple** [pulumi/pulumi#2935]
`curl | sh` is a rough thing to sell security people on and tarballs don't integrate with package repos. Any thoughts/roadmap items for .deb/.rpm distributions?

**Comment by eropple** [comment]
Barring that, a nice option might be (as I mentioned offhandedly in #2934) a plugin for [asdf](https://github.com/asdf-vm/asdf). The Terraform plugin has made life a lot easier on that side of the fence.

**Comment by lukehoban** [comment]
This is being tracked in https://github.com/pulumi/pulumi/issues/1536.  I'm going to close this out as a dupe - but let me know if you think there's something else we should track on this thats orthogonal to that issue.
