### ISSUE TITLE
S3 backend: passing arguments to the client?

### ISSUE THREAD

**Issue by eropple** [pulumi/pulumi#2937]
This might be a feature request or it might be a doc request!

As per https://pulumi-community.slack.com/archives/C84L4E3N1/p1563216396381800 I'm trying to pass `x-amz-acl: bucket-owner-full-control` to the underlying S3 backend client for my state store. The reason for this is that we have multiple accounts that need to read states, but when a state is created by someone other than the bucket owner its permissions aren't set correctly. (If you Google for _s3 bucket owner object owner_, you will find many confused people about this!)

Can this be done now? If so, how? And is there doc for it? ;)

**Comment by eropple** [comment]
Another example: our VPN in AWS has a role attached to it. Pulumi's S3 backend preferentially attempts to use its metadata endpoint to get instance profile creds even when I set `AWS_PROFILE`; I should be able to say "no, use the profile value".

**Comment by eropple** [comment]
This is progressively more painful. Having to disconnect from my VPN because I can't seem to tell the S3 client (whether it's talking to my state store, to our existing TF remote state, etc.) "no, use `AWS_PROFILE`" is making it so I have to disconnect from our VPN to run Pulumi. :(

**Comment by lukehoban** [comment]
I *believe* that neither `AWS_PROFILE` nor customer headers for `x-amz-acl: bucket-owner-full-control` are currently configurable on the S3 backend.  Definitely open to PRs here.

**Comment by eropple** [comment]
I am emphatically not a Go programmer, but I can maybe take a look next week.

Also to clarify, `AWS_PROFILE` does work--what doesn't work is the correct AWS certificate chain. Other AWS tools do as expected and use `AWS_PROFILE` before checking instance metadata; this might be a bug in the underlying library.

**Comment by eropple** [comment]
FWIW, for anyone else who've run into a similar problem - we're attempting to solve it probably-the-more-correct-way by dropping `169.254.169.254` at our VPN.

**Comment by lukehoban** [comment]
Opened a more general issue on this topic - https://github.com/pulumi/pulumi/issues/4665.  I'll close this one out as dupe as the solution will need to be a general mechanism.
