### ISSUE TITLE
Version inconsistencies lead to errors

### ISSUE THREAD

**Issue by arnediekmann** [pulumi/pulumi#2938]
When trying to use a project with `CustomResource` objects with the current CLI (`v0.17.22`) I  encountered the following error:

```
TypeError: opts.parent.__aliases is not iterable
        at new Resource ([...]/node_modules/@pulumi/pulumi/resource.js:117:51)
        at new CustomResource ([...]/node_modules/@pulumi/pulumi/resource.js:270:9)
        at new Resource ([...]/node_modules/@pulumi/pulumi/dynamic/index.js:40:9)
        at new DatabaseUser ([...]/src/database/database-user.ts:7:9)
        at [...]/src/database/gcp/gcp-database-cluster.ts:64:13
```
The instance of `GCPDatabaseCluster` (which has no aliases) is the parent of a `DatabaseUser` (again without aliases). Since aliases are a fairly new feature (#2774) @lukehoban and I both suspected version inconsistencies to be the cause.

I could work around the problem by deleting all `node_modules` directories and running `yarn` again. Fixing the version inconsistencies in the `package.json` files and running `yarn` alone did not suffice, however.

Is it maybe possible to somehow ensure that new features are backwards compatible? Another improvement on that front could be warnings that address version inconsistencies.

**Comment by lukehoban** [comment]
>  I could work around the problem by deleting all node_modules directories and running yarn again. Fixing the version inconsistencies in the package.json files and running yarn alone did not suffice, however.

Yes - this aligns with my experience with `yarn` not being particularly aggressive on aligning version numbers during updates, but being good at aligning them on fresh installs.

> Is it maybe possible to somehow ensure that new features are backwards compatible? Another improvement on that front could be warnings that address version inconsistencies.

Yes - that is certainly the goal, and this case is just a bug.
