### ISSUE TITLE
Rename CLI environment variables for 1.0

### ISSUE THREAD

**Issue by bermudezmt** [pulumi/pulumi#2944]
We honor a few environment variables related to the CLI such as PULUMI_API and PULUMI_ACCESS_TOKEN. We may need to rename these variables before we launch 1.0.

**Comment by lukehoban** [comment]
> We may need to rename these variables before we launch 1.0.

Curious - why do you think we would need to rename these?

**Comment by bermudezmt** [comment]
Hey @lukehoban - this came out of my discussion with Justin, Christian, and Chris. @chrsmith suggested filing an issue to review the CLI-specific environment variables before we update the docs (apparently some of these might be mentioned in the reference pages). I'm not 100% up to speed on this yet -- just filed the issue before I forget.

**Comment by chrsmith** [comment]
Thanks @bermudezmt . For a little more context @lukehoban , it isn't that we _should_ rename these CLI environment variables. More that, in addition to confirming we are documenting them, we want to make a 👍/👎 decision on if those are the names we want to use ~forever.

`PULUMI_ACCESS_TOKEN` is fine, but perhaps `PULUMI_BACKEND_URI` or `PULUMI_STATEPROVIDER` would be more appropriate than `PULUMI_API`? I have opinions and wanted to raise the issue in case others feel the same way.

**Comment by stack72** [comment]
@chrsmith is this something we still need to act upon or can this be closed out now that we are way later in the process?

**Comment by chrsmith** [comment]
Nope, nothing to do here. While maybe in an alternate universe we ended up with different env var names, what we have today are fine.
