### ISSUE TITLE
change or customize plugin install location

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi#2966]
When using nodejs, pulumi plugins are automatically installed upon `npm install`.
However the plugins are not installed alongside the node_modules directory but in the global user home under `~/.pulumi/plugins`. This is kinda surprising for nodejs users which are used to have all their deps self-contained under node_modules. I suspect the same applies to advanced python users which expects all their deps to be contained in a workspace local virtualenv.
 
While this behavior is normally not a big deal on a local machine, it caused me multiple times some headache in CI environments. Particularly there are some CI systems, e.g. codefresh, which pass the working directory / volume from container to container (sometimes called "container chains") and other CI systems which have explicit caching support for certain working directories.
The fact that pulumi installs plugin outside the working directory, in a "somewhat" not fully stable location (i.e. the absolute path depends on OS and username of the container in which the install command was executed) oft led to situations in CI where the pulumi node_modules were present, but the plugins not and failed the pipeline with an error similar to this:
```
error: could not load plugin for kubernetes provider 'urn:pulumi:api-events-staging::api-events::pulumi:providers:kubernetes::api-cluster
-dev-a': no resource plugin 'kubernetes' found in the workspace or on your $PATH     
```

If this occurs, there is not even a way to "install the missing plugins", other than by nuking the entire node_modules directory and download all dependencies (not only pulumi plugins) from scratch.

Therefore I'd like to request a change in this behaviour, especially something that considers the needs of CI environments.

A few ideas I had:
1. Add an environment variable override like `PULUMI_PLUGIN_LOCATION` which can be used to override the default plugin (install and search) location.
2. Install pulumi plugins into node_modules instead of home directory. This could be optionally controlled via an environment variables as well.
3. Automatic lazy fetching of plugins by language SDKs, if a plugin is not present at runtime.

**Comment by lukehoban** [comment]
Another Codefresh user reported hitting the same issue.

It does feel like an env var to control where the `.pulumi` folder lives is likely the most direct thing here.  There are other things beyond even plugins that are stored in `~/.pulumi` currently that will probably cause other forms of confusion if they are not maintained across `pulumi` executions.  

Note that we do now try to automatically fetch plugins if needed during `update` on relatively recent CLI releases.  I'm not sure whether the issues reported here still repro with those latest CLIs, or whether we now can correctly pull these in again on demand.

**Comment by fernandocarletti** [comment]
I'm getting the same issue here. For now, we added a workaround, removing the `node_modules/` folder and running `yarn install` again in the same container the preview runs. Adds some more time to the build though.

**Comment by fernandocarletti** [comment]
This is odd. Is this unassign expected? I did not do it O.o

**Comment by nesl247** [comment]
@lukehoban See https://pulumi-community.slack.com/archives/C84L4E3N1/p1570105675260600 for an issue with the automatic fetching of plugins.

**Comment by boillodmanuel** [comment]
Controlling where `.pulumi` folder lives is usefull also for using CI/CD caching (which often forbid to cache ~/.pulumi but allow current directory)

**Comment by boillodmanuel** [comment]
Hello, 
It's awesome to have tackle this so quickly! 👍 

But I don't see any documentation update. Do not forget to maintain documentation up-to-date 💪

**Comment by pgavlin** [comment]
Opened https://github.com/pulumi/docs/issues/1838 to track updating the docs.

**Comment by XBeg9** [comment]
Any ideas on how to move pulumi `bin` into PULUMI_HOME? I am talking specifically about this script https://get.pulumi.com/, that installs pulumi bin into $HOME user directory, which means we can't cache it :( on CircleCI using `ramdisk`. @mikhailshilkov @pgavlin

**Comment by leezen** [comment]
@jaxxstorm who was looking at https://github.com/pulumi/get.pulumi.com/pull/75
