### ISSUE TITLE
Migrating to Pulumi v0.17.23 and newer

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#2971]
As of Pulumi v0.17.23, the detection of differences between the actual and desired state of a resource is left entirely up to that resource's provider. While in general this provides many improvements--in particular, Pulumi is better able to detect and respond to changes made out-of-band, and is able to import resources for management by Pulumi--it does expose Pulumi programs to bugs in providers that may detect changes even when none are present. The most common cause of this issue is improper or unexpected normalization of values.

As of this writing, there are several known provider issues that are exposed by Pulumi v0.17.23:
1. https://github.com/pulumi/pulumi-kubernetes/issues/644
2. https://github.com/pulumi/pulumi-aws/issues/667
3. https://github.com/pulumi/pulumi-aws/issues/668
4. https://github.com/pulumi/pulumi-gcp/issues/184
5. https://github.com/terraform-providers/terraform-provider-aws/issues/665

Workarounds for (2), (3), and (4) are described in the issues. (1) and (5) require bugfixes in the respective providers. In these cases, the `PULUMI_ENABLE_LEGACY_DIFF` environment variable can be set to `1` in order to use the legacy diffing approach until fixes are available.

**Comment by jen20** [comment]
https://github.com/terraform-providers/terraform-provider-aws/issues/158 is another example of this - though it manifests only with a misconfiguration in code.

**Comment by mikhailshilkov** [comment]
It sounds like this one can be closed. Feel free to reopen if it still has any value.
