### ISSUE TITLE
Windows Terminal: preview duplicates rows

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#2999]
[Windows Terminal](https://github.com/microsoft/terminal) Preview 0.2.1831.0.

Note the top three rows are duplicated on both screens below.

PowerShell:
![image](https://user-images.githubusercontent.com/1454008/62078489-6a7c3500-b255-11e9-92b8-4463c30a29de.png)

Cmd:
![image](https://user-images.githubusercontent.com/1454008/62078564-8f70a800-b255-11e9-8667-65a80d84506d.png)

**Comment by lukehoban** [comment]
Did this just start happening?

@cyrusnajmabadi is this a regression from https://github.com/pulumi/pulumi/pull/2990

**Comment by mikhailshilkov** [comment]
I've just installed Windows Terminal (Preview).

Standard PowerShell/cmd works fine.

**Comment by CyrusNajmabadi** [comment]
@mikhailshilkov does this happen when you manually scroll up/down in the window?  or does it happen every time you do an update?

**Comment by mikhailshilkov** [comment]
It happens every time without me doing anything tricky

**Comment by CyrusNajmabadi** [comment]
Fantastic.  I wonder if this is an issue with the underlying library we use for painting to the terminal.  Given that this is the new preview terminal for windows, i'm going to treat this as low priority for now.  We'll see how much usage we see of this in the future and if we get more reports.

**Comment by CyrusNajmabadi** [comment]
There's a new build of the windows terminal: https://devblogs.microsoft.com/commandline/windows-terminal-preview-v0-3-release/

Can you let me know if you still see this behavior with it?  Thanks!

**Comment by mikhailshilkov** [comment]
It looks good so far! I'll close the issue until I see the problem again.
