### ISSUE TITLE
Update testing framework to include package upgrades

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#3026]
One of the things we really need to introduce to catch some regressions earlier is testing that after upgrading a package, we don't get any spurious diffs. The updated flow would be as follows:

* yarn install
* yarn link <each opts.Depencies>
* (+) yarn run build
* pulumi init
* (*) pulumi login
* pulumi stack init integrationtesting
* pulumi config set <each opts.Config>
* pulumi config set --secret <each opts.Secrets>
* pulumi preview
* pulumi up
* pulumi stack export --file stack.json
* pulumi stack import --file stack.json
* pulumi preview (expected to be empty)
* pulumi up (expected to be empty)
* yarn install (to be dev)
* pulumi preview  - we need to understand if this will be expected to be empty or not
* pulumi up  - we need to understand if this will be expected to be empty or not
* pulumi destroy --yes
* pulumi stack rm --yes integrationtesting

**Comment by lukehoban** [comment]
This is the same as https://github.com/pulumi/pulumi/issues/2757#issuecomment-494804228 I believe?

**Comment by stack72** [comment]
You are correct - closing in favour of #2757
