### ISSUE TITLE
Make integration testing command line tool

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#303]
Currently integration tests for Lumi packages compile against `pkg/integrationtesting`.  However, this requires that otherwise LumiJS-only packages must have a working Go environment including vendorring of transitive dependencies to be able to run tests. 

The integration testing could instead be a command-line utility distributed with the Lumi package releases.

**Comment by pgavlin** [comment]
@lukehoban do we still want to do this? It seems like in general this requires adding support for running arbitrary code in some language to do post-test-step verification?

**Comment by lukehoban** [comment]
Nope - let's close this - as you note - the addition of `ExtraRuntimeValidation`, which has been very valuable for testing, has made this less attractive.
