### ISSUE TITLE
Pulumi up silently installs a plugin with no visible progress

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#3033]
I cloned one of the examples and ran `pulumi up` on it. I also happened to be on a slow internet connection.

```
$ pulumi up
Please choose a stack, or create a new one: <create a new stack>
Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`): dev
Created stack 'dev'
Previewing update (dev):
Moving plugin... done.
```

`Previewing update (dev):` was showing for quite a long time without any visible progress. Based on `Moving plugin... done.` label (that we added recently) I can tell that this time was (partially?) spent on downloading a provider plugin.

Shall we show the download progress here the same way we show it during `install`?

**Comment by lukehoban** [comment]
> Shall we show the download progress here the same way we show it during install?

Yes - we should give some indication about this plugin installation.  Perhaps more subtle - but some indication is important given this can take a long time on slow connections.
