### ISSUE TITLE
Hitting "down" while reading API token during `pulumi login` leads to error.

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#3035]
As part of reading API tokens, we flip the terminal into no echo mode.  When we are in that state, keyboard motion characters like DOWN will be sent as ANSI escape codes and we'll include them in the value we read.  We should not be doing this.

As an example:

```
[matell@matell pulumi]$ pulumi login --cloud-url https://api.pulumi-test.io/
Manage your Pulumi stacks by logging in.
Run `pulumi login --help` for alternative login options.
Enter your access token from https://app.pulumi.com/account/tokens
    or hit <ENTER> to log in using your browser                   :
error: problem logging in: getting user info from https://api.pulumi.com: performing HTTP request: Get https://api.pulumi.com/api/user: net/http: invalid header field value "token \x1b[B\x1b[B\x1b[B\x1b[B\x1b[B\x1b[B" for key Authorization       
```

**Comment by CyrusNajmabadi** [comment]
> We should not be doing this.

What should we be doing instead? :)

**Comment by ellismg** [comment]
> What should we be doing instead? :)

Not 100% sure.  It's possible that we should just be stripping all ASNI escape sequences from the string we "read"?

**Comment by reilly3000** [comment]
I'm having a similar issue, except I'm getting a rouge newline for some reason.

echo $PULUMI_ACCESS_TOKEN
mytokenhere
pulumi login
Logging in using access token from PULUMI_ACCESS_TOKEN
error: problem logging in: getting user info from https://api.pulumi.com: performing HTTP request: Get https://api.pulumi.com/api/user: net/http: invalid header field value "token mytokenhere\n" 
for key Authorization

**Comment by CyrusNajmabadi** [comment]
I'm actually really curious if we need to solve this.  I tried a couple of different unix commands (like `sudo`) and hit arrow keys (like `down`) when typing in this sort of data.  The commands ended up failing.  So it feels like most systems just suck this in as part of the string they're reading.  It feels fine to me that we do the same.

**Comment by CyrusNajmabadi** [comment]
@lukehoban for check here.  i don't feel like this needs to be fixed.  And i certainly don't think it's a priority for 0.27.  i think in general there isn't an expectation from users that hitting arrow keys will have no impact when typing in secret info.
