### ISSUE TITLE
Deprecate PULUMI_TEST_MODE

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3045]
We are going to leverage the techniques demonstrated in https://www.pulumi.com/blog/unit-testing-infrastructure-in-nodejs-and-mocha/ instead.

**Comment by ericrudder** [comment]
Can we annotate the "old" (4.19) blog entry with a link/note to the new one
as well, since it will still come up in searches?

**Comment by dustinfarris** [comment]
Will the new method support unit testing libraries that are not necessarily part of a pulumi program?

**Comment by joeduffy** [comment]
Thanks for the questions Dustin. I know this is an important scenario for your team so I want to make sure whatever we do here will work for you. I also think the way you're testing is a close approximation for what I've heard other end users doing, so your feedback is super valuable.

> Will the new method support unit testing libraries that are not necessarily part of a pulumi program?

Any libraries that don't depend on Pulumi runtime functions -- like allocating resources and reading their resolved output properties -- can still be safely tested using existing mechanisms.

The main change here is that `PULUMI_TEST_MODE` tries to execute in a "half runtime" state, where there is no CLI or engine to communicate with, which is what leads to hangs. We have found that this is quite error prone and confusing. Basically, 50% of the time, your test isn't going to actually succeed at doing what you want it to do.

With the new approach, there is a full CLI and engine available, so everything works just as it would during typical Pulumi evaluation.

> The new method feels close to integration testing to me — which is great — but does it come at the cost of unit testing?

Unit testing is still possible. The idea is to run the unit tests during `pulumi preview`. Do you think that will work for your use cases?

> Also, will there be support for utilities like mocha watch that reruns unit tests as you write them?

This is one of the major losses, I think. The existing `mocha` CLI can't be used. You can, however, use the built-in programmatic capabilities of Mocha, which [covers a lot of ground](https://github.com/mochajs/mocha/wiki/Using-Mocha-programmatically). It appears "watch" is one that wouldn't be possible -- unless @lukehoban sees something here that I'm missing.

https://github.com/pulumi/pulumi/issues/2287 will explore capabilities such as this.

**Comment by dustinfarris** [comment]
Thanks for the reply, Joe.

We see the benefits of unit testing during preview and post-update when the entire shape of resources is known.  We are excited to play with this new feature which should be prioritized soon.

As I haven't had a chance to play with it myself yet, can you give me a sense of how long it will take to run a modest test suite on an average-size program?  The unit tests we have now serve as a fast spot check on our wiring, and I believe there is value in that.  We use a combination of pulumi's test mode and sinonjs to stub out resources and check that known inputs and dependencies are being configured properly.

As a very basic example, we might assert that a myBucket resource is in fact a Bucket:

```typescript
describe("my bucket", function() {
    it("is a Bucket", function() {
        assert.ok(infra.myBucket instanceof aws.s3.Bucket);
    });
});
```

This test executes in less that 1 ms, and using mocha watch, we are able to add to this spec and get near-real-time feedback on what's missing or broken.

I'm guessing that the removal of `PULUMI_TEST_MODE` means that any attempt to import a pulumi-dependent module will crash outside of the pulumi runtime.  I feel like there is a lot of room for improvement with the current framework we've been using.  The tests we have require a fair amount of boilerplate and "cleverness" to work with pulumi, but they are fast.

**Comment by lukehoban** [comment]
We're tracking the work to design for a more integrated testing solution in https://github.com/pulumi/pulumi/issues/2287, and don't plan to actively deprecate anything here independent of that, so will close this out.

**Comment by iwahbe** [comment]
That `PULUMI_TEST_MODE` still exists can cause confusion. We should depreciate it and remove any mention of it from the docs.
