### ISSUE TITLE
Python runtime can peg CPU at 100% when using data sources

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi#3051]
Using the AWS provider from the `stack72/v2.23.0` branch of `pulumi_aws`, the following code pegs the CPU at 100% (in the Python interpreter):

```python
import pulumi

from pulumi_aws import get_availability_zones

zones = pulumi.Output.from_input(get_availability_zones())
zone_names = zones.apply(lambda zs: zs.names)

pulumi.export('name0', zone_names.apply(lambda x: x[0]))
```

Of note is that the branch of the AWS provider in question was the first to pull in the asynchronous to synchronous changes.

**Comment by stack72** [comment]
FWIW, master branch will do the same
