### ISSUE TITLE
Unable to rename a stack's project

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#3052]
The "project name" is the `project` field found in `Pulumi.yaml`, and makes up part of a stack's identity. For example, if the `Pulumi.yaml` has `project: frontend` and another has `project: backend`, then I can have two stacks with the name `dev` since the project differs.

`chrsmith/frontend/dev`
`chrsmith/backend/dev`

I can rename one of those, e.g. to `dev-renamed` by running `pulumi stack rename`. However, I don't have a way to rename the _project_ used for a stack.

If I edit the `Pulumi.yaml` and try to run `pulumi up`, I am greeted with a prompt to create a new stack. (Since no stacks with the new project name exist.)

```
$ pulumi up --skip-preview
Please choose a stack, or create a new one:
> <create a new stack>
```

It seems like we should update `pulumi stack rename` to support this use-case, even if it is a little wonky. For example, you need to run `pulumi stack rename --new-project=foo`, which will edit the `Pulumi.yaml` file and also need to rename all of the other stacks with that same project name?

**Comment by followben** [comment]
This is an old issue, but for anyone else who stumbles on it, projects can be renamed via the `stack rename` [command](https://www.pulumi.com/docs/reference/cli/pulumi_stack_rename/):

> You can also rename the stack’s project by passing a fully-qualified stack name as well. For example: ‘robot-co/new-project-name/production’. However in order to update the stack again, you would also need to update the name field of Pulumi.yaml, so the project names match.

**Comment by samox73** [comment]
@neovasili it works for me. Mind that you need to use your username/org as a prefix:

```bash
❯ pulumi version
v3.43.1
❯ pulumi new aws-typescript -n "test" -d "test" -s "dev" -y
❯ pulumi stack rename USERNAME/new-test/dev
Renamed dev to USERNAME/new-test/dev
```

**Comment by neovasili** [comment]
Thanks for checking @samox73 😄 

mmm, I'm using S3 backend for state, might be that the reason? I mean, there is no username in my use case. If that's the case, what I should be putting there? I think that should be clarified in the docs.

**Comment by samox73** [comment]
@neovasili Sorry, I've never used the S3 backend. But judging from #2522 this issue has been present for a while 😢

**Comment by jcalderin** [comment]
I have had the same problem, and the workaround doesn't work if your backend is S3. Sadly, I had to modify manually the state what is the last thing I wanted to do.

Can we re-open the issue?

**Comment by mikhailshilkov** [comment]
@jcalderin There is no first-class notion of projects in our S3 backend, so I don't think this issue quite applies. It should probably be tracked as a part of https://github.com/pulumi/pulumi/issues/2522
