### ISSUE TITLE
aws.ecs.Cluster does not support Container Insights

### ISSUE THREAD

**Issue by random-ua** [pulumi/pulumi#3062]
It's impossible to enable Container Insights when creating new ECS Cluster instance

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-container-insights.html

Also new clusters created with {CloudWatch monitoring: Default Monitoring} despite Container Insights enabled by default (with `aws ecs put-account-setting-default --name containerInsights --value enabled`)

**Comment by lukehoban** [comment]
This is being tracked in the upstream provider here: https://github.com/terraform-providers/terraform-provider-aws/issues/9294.  This will be available in Pulumi as soon as it's available in that upstream provider.

**Comment by NickReisenauer** [comment]
Now that this is supported upstream, is it available in Pulumi?
