### ISSUE TITLE
pulumi.Output<Resource> leaves it with just pulumi.OutputInstance<Resource> with no properties

### ISSUE THREAD

**Issue by redbaron** [pulumi/pulumi#3096]
StackReference.getOutput() returns `pulumi.Output<any>` , which I'd like to refine to a more restricted type to have more typesafe goodness.

lets say output is produced as:
```ts
let proj = new gcp.organizations.Project(...);

{
[name]: { project: proj }
}
```

then when I use it , I'd like to do:

```
const bootstrap = new pulumi.StackReference("stackname")
.requireOutput("var") as pulumi.Output<{ [name: string]: {project: gcp.organizations.Projects}>

const project : gcp.organizations.Projects = bootstrap["x"].project; //this fails
```

which makes TS compiler bark at me because result of such `as` casting is a mere `pulumi.OutputInstance<T>`  , with former `pulumi.Lifted<T>` part being completely lost.

I think it is because of https://github.com/pulumi/pulumi/blob/8fd05fcd9fbd1480c01726b4fc7fcf158e611f99/sdk/nodejs/output.ts#L685 where it does not descend into object field if `T extends Resource`.

Not insisting on fixing `pulumi.Output<T>`, but having typed outputs from other stacks is something worth having IMHO.

In the meantime workaround for me is following unergonomic acrobatics:

```
const bootstrap = new pulumi.StackReference("stackname")
.requireOutput("var") as pulumi.Output<{ [name: string]: {project: pulumi.Unwrap<Pick<gcp.organizations.Projects,'id'|'number'>>}>
```

**Comment by lukehoban** [comment]
A core thing here is that Resources are not fully roundtripped through `StackReference` - they are JSON serialized and so the values you retriev when you reference the outputs will not be true `Resource` instances but instead JSON objects.

As a result, most of the places you mentioned `gcp.organizations.Projects` above just won't work as you are hoping they will. 

Instead, you should export the `id` of the resource and call `.get` on that in the other stack.

I *think* that the rest of the experience here might be downstream of that core problem.

**Comment by redbaron** [comment]
> As a result, most of the places you mentioned gcp.organizations.Projects above just won't work as you are hoping they will.

I realised that it is just a JSON , all I want is define types of it's keys. If https://github.com/pulumi/pulumi/blob/8fd05fcd9fbd1480c01726b4fc7fcf158e611f99/sdk/nodejs/output.ts#L692 was exported I'd do:

```
{ project: pulumi.LiftedObject<gcp.organizations.Projects, pulumi.NonFunctionPropertyNames<gcp.organizations.Projects>>}
```

as a workaround, but it is still not very ergonomic

**Comment by lukehoban** [comment]
I'm not sure there is any simple way to JSON-ify the type of a Pulumi-codegen'd `Resource` (or even in general of any TypeScript type).

I think the "right" thing here will be to provide a way to rehydrate Resource references from a `StackReference` to a stack output that is a `Resource`.  

But the simpler thing for now is to just export the `id` and `.get` it.

**Comment by redbaron** [comment]
> I'm not sure there is any simple way to JSON-ify the type of a Pulumi-codegen'd Resource (or even in general of any TypeScript type).

Really simple way of doing it would be to codegen and  plain old type too for every resource.

**Comment by CyrusNajmabadi** [comment]
> Really simple way of doing it would be to codegen and plain old type too for every resource.

I personally don't think that would be very desirable.  There would be "yet another" way of thinking about a Resource.  Right now one has to consider the shape of all its inputs, which is similar, but not equivalent to the shape of all its Outputs.  There would now be a new type similar to the POJO for that resource to have to know and think about.  Instead, just having the id and being able to actually hydrate back to the true Resource on the other end is valuable.  It also means proper resource tracking, instead of potentially losing that in the conversion and passing along of the pojo-ized data.

**Comment by redbaron** [comment]
Having 'id' is not universal solutions either, in multi-project setup, where pulumi's service account is restricted to bare minum like in our case there might be no permissions to do said fetch at all. 

In addition to that, conceptually it might be a bit less safe as get by id gives back current state of the object in cloud, while it should be the same as what referred stack produced, that is not necessary the case and I'd prefer to based my action on pulumi state of the world and let cloud fail my calls if there is a critical mismatch, rather than succeeding without knowing that upper stack is stale

**Comment by redbaron** [comment]
As for the type generation , that was just a suggestion how it can be achieved, having Lifted<POJO<T extends Resource>> which works is fine too, but I couldn't figure how to write one

**Comment by mikhailshilkov** [comment]
This issue is a bit stale and isn't obviously actionable. I'll go ahead and close it - feel free to open a new issue with a refined suggestion.
