### ISSUE TITLE
Don't push to upgrade to pre-release versions

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3102]
It feels odd to me that we suggest people upgrade from stable to unstable versions. E.g.

> warning: A new version of Pulumi is available. To upgrade from version '0.17.24' to '1.0.0-beta.2', run

I propose we only suggest upgrading to the latest stable version. If people want to adopt and give us feedback on a release candidate, great, but that possibility should be communicated through other means (Slack, blog posts, etc).

**Comment by lukehoban** [comment]
This was very point in time around the 1.0 betas - no need to track now.  We will have a related but in practice totally different set of discussions for 1.0 -> 2.0.
