### ISSUE TITLE
Lifted property lookups on `Output<undefined>` don't throw?

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3111]
Is it intentional that these print `undefined` instead of throwing?

```ts
const x = pulumi.output(<{a: number}><any>undefined).a;
x.apply(x => console.log(x));
```

```ts
const x = pulumi.output([{a: 1}])[99].a;
x.apply(x => console.log(x));
```

The fact that these "succeed" and produce `Output<undefined>` is different than normal JavaScript behaviour where `undefined.a` would throw.

This partially leads to confusion like in https://github.com/pulumi/pulumi/issues/3063.

**Comment by lukehoban** [comment]
This appears to be done very on-purpose - but I cannot reason about why this is "right":

https://github.com/pulumi/pulumi/blob/b72e411c37234c0f25533bc3b8a18c795b4221c1/sdk/nodejs/output.ts#L303-L312

**Comment by lukehoban** [comment]
It looks like my [original prototype](https://github.com/pulumi/pulumi/commit/5f8b6f7c0e096cd65e0c2be69607bc3f5075720f#diff-60a0d91ede7b9f2ccd5436be151b9057R476-R478) of this did not have that special case - it just had:

```
return obj.apply(ob => (<any>ob)[prop]);
```

**Comment by CyrusNajmabadi** [comment]
i thnk it would be fine to just have that logic.  I think the concern i had at the time was that this could mean we'd null-ref in preview.  But since we're going through the standard `.apply` codepath, i think we should be insulated from that.

**Comment by CyrusNajmabadi** [comment]
In terms of hte "why", i think in my head i was treating this vaguely similarly to 'nullable' in that i lifted operations on a null value to just keep returning null.  It was also nice in case there was code that effectively wanted to do a `?.blah` type lookup.  But i can def see why this woudl not be desirable and that we should just keep standard property semantics here.  

@lukehoban I'm fine with making this change.  Note that it will be a "breaking" behavioral change.  Are you ok with that?

**Comment by CyrusNajmabadi** [comment]
We decided this is 'by design' as per: https://github.com/pulumi/pulumi/pull/3210#issuecomment-555845992

**Comment by CyrusNajmabadi** [comment]
Note: docs where updated here: https://www.pulumi.com/docs/intro/concepts/programming-model/#optional-chaining-off-of-an-output
