### ISSUE TITLE
Python Integration Tests

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#3114]
Since we have added more python tests to our providers, we have started getting the following error after the first python test creates the virtual env

```
OSError: [Errno 17] File exists: '/home/travis/.local/share/virtualenvs'
```

This is because, by default, pip creates a virtualenv that is at a shared location.

We need to be able to create a virtualenv per test to ensure that tests don't interfere with each other. This is causing a lot of our provider builds to fail

**Comment by lukehoban** [comment]
This was in theory fixed in https://github.com/pypa/pipenv/issues/3257. 

@stack72 Can you share more details?  Full stack trace, how frequently this occurs, etc?

**Comment by stack72** [comment]
This occurs on every build now that we have multiple python tests in - we are starting to see it only because I increased the python test coverage in each project recently

**Comment by lukehoban** [comment]
Hmm - we have ~10 Python tests running in parallel in pulumi/pulumi - and I don't think we've ever hit this there.  What's different about the cases you have added recently?

https://github.com/pulumi/pulumi/blob/b72e411c37234c0f25533bc3b8a18c795b4221c1/tests/integration/integration_test.go

**Comment by ellismg** [comment]
This should now be fixed by https://github.com/pulumi/scripts/commit/6e8696e457bd60ee472e60a8ae70765abae166e7
