### ISSUE TITLE
Add test coverage of (old CLI, new pkgs) and (new CLI, old pkgs)

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3137]
We should add at least `examples` test coverage for the combination of ("old CLI" + "new pkgs") and ("new pkgs" + "old CLI"), where "old" means "1.0.0" for the nearterm, and "new" means "dev builds".

**Comment by lukehoban** [comment]
From https://github.com/pulumi/pulumi/issues/3127, we should make sure to include tests which use `StackReference`.

**Comment by stack72** [comment]
I think this looks like @ellismg is picking it up in https://github.com/pulumi/examples/pull/374

**Comment by lukehoban** [comment]
Fixed with pulumi/examples#374.
