### ISSUE TITLE
Figure out why ES7 is silently permitted in our code

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3148]
We explicitly set our Node.js SDK target to ES6 in our project:

https://github.com/pulumi/pulumi/blob/a687f815751a627d2fe605ab9b8da8de2bf25b0f/sdk/nodejs/tsconfig.json#L4

And yet, somehow, we are allowing the use of ES7-only functions, like [Array.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes):

https://github.com/pulumi/pulumi/blob/a687f815751a627d2fe605ab9b8da8de2bf25b0f/sdk/nodejs/stackReference.ts#L152

This isn't the first time this has happened. Each time it does, I am unable to compile locally on my dev machine. It's a mystery why apparently nobody else on the team has this same problem, and/or why CI is happily accepting this:

```
stackReference.ts:152:18 - error TS2339: Property 'includes' does not exist on type 'string[]'.

152     return names.includes(await nameOutput.promise());
                     ~~~~~~~~
```

Sure enough, if I change the target to `es7`, the problem goes away. But I don't think we want to be targeting newer runtimes -- or, if we do, we should explicitly discuss and decide.

**Comment by CyrusNajmabadi** [comment]
Have opened https://github.com/microsoft/TypeScript/issues/33355 to get insight here.

**Comment by CyrusNajmabadi** [comment]
From ryancavanaugh

> node.d.ts has (correctly) a /// <reference lib="es2016" /> directive (or equivalent), because the version of node it represents includes all the ES2016 APIs and needs to reference some of the types therein.

So, realistically, since we are targeting node, we are targeting a minimum of es2016.  We should just upgrade everything to htat so we can use these features and not be in the weird state where the compiler occasionally gets unhappy

**Comment by ellismg** [comment]
FWIW - I do suspect that our strategy of using `"@types/node": "latest"` in our package.json is also buying us a no favors.  I suspect this means we are seeing types and method for the latest version of node, but our "minimum node version" is "8.10.X", and so we should be doing something like `"@types/node": "^8.0.0"` ?

**Comment by CyrusNajmabadi** [comment]
Yes, that's a reasonable thing to do as well.  I will update.
