### ISSUE TITLE
Create a release for every new version

### ISSUE THREAD

**Issue by ncsibra** [pulumi/pulumi#3167]
Based on this slack thread: [https://pulumi-community.slack.com/archives/C84L4E3N1/p1567144445103700](https://pulumi-community.slack.com/archives/C84L4E3N1/p1567144445103700)
Please create a new github release (not just tag) for every new version in every pulumi repo so we can more easily follow the changes, watch them etc.
You can do this as part of the publishing process, github has a release api.

**Comment by pgavlin** [comment]
cc @ellismg

**Comment by sudoforge** [comment]
Below is the initial transcript from #4050:

**@sudoforge** [(original comment)](https://github.com/pulumi/pulumi/issues/4050#issue-578846710):

> I maintain system packages for pulumi (and more) for Arch Linux users, and typically rely on email notifications to know that any given package has a new release. It would be great if Pulumi created GitHub releases (or had an email list that was notified on releases) so that users like myself can be notified of upstream releases.

**@lukehoban** [(original comment)](https://github.com/pulumi/pulumi/issues/4050#issuecomment-597311979):

> See also #3167.
> 
> Although we don't publish full releases with binaries, we do have Releases listed at https://github.com/pulumi/pulumi/releases, and they are available in RSS via https://github.com/pulumi/pulumi/releases.atom.

**Comment by sudoforge** [comment]
> Although we don't publish full releases with binaries, we do have Releases listed at https://github.com/pulumi/pulumi/releases

This would seem to indicate a slight misunderstanding of that tab. GitHub simply displays each tag under the "Releases" tab of that page; this is **not** a GitHub Release, which has to be created independent of the tag (either through the web interface or the API). Creating a GitHub release does not necessitate adding binaries; although this would be beneficial for users who want to download the compiled binary for each release, it is a separate feature of GitHub Releases.

 > they are available in RSS via https://github.com/pulumi/pulumi/releases.atom

Yes, I am aware that I could write a custom service to watch the RSS feed for this project and notify myself / automate tasks on each new entry in the feed. That is not desirable for several reasons, namely that each user wishing to do this would need to create such a service; and reinventing the wheel when GitHub has a feature for handling this type of notification feed is not desirable.

I would be more than happy to help add a Workflow step for creating a release if the powers that be are okay with that.

**Comment by lukehoban** [comment]
> This would seem to indicate a slight misunderstanding of that tab. GitHub simply displays each tag under the "Releases" tab of that page; this is not a GitHub Release, which has to be created independent of the tag (either through the web interface or the API).

Yep - definitely understood and agreed on the desired state to be in - I was just pointing out what is available today.

> I would be more than happy to help add a Workflow step for creating a release if the powers that be are okay with that.

Great!  Ccing @stack72 who may have thoughts on where best to integrate this.  I suspect we'll want to do it as part of the `publish_packages` step in the Makefile (or a separate step that runs after that).

**Comment by sudoforge** [comment]
Thanks @stack72!

**Comment by stack72** [comment]
I will get this rolled out to the provider repos ASAP!
