### ISSUE TITLE
Errant behavior when multiple routes map to same static resource

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#317]
Consider the following: Two API routes get mapped to the same static file.

```
api.routeStatic("GET", "/index.html",               "file.html",                "text/html");
api.routeStatic("GET", "/index2.html",             "file.html",                "text/html");
```

Upon the second deploy, e.g. if you remove the "/index2.html", Lumi gets confused and dies. (Either the S3 Object gets deleted removing the "/index2.html" route and "/index.html" 's route processing gets confused, or vice versa.

```
error: rpc error: code = Unknown desc = Error preparing aws:s3/object:Object old property state: open XXXX: no such file or directory
```

**Comment by joeduffy** [comment]
This is pretty old, so closing out. If we can easily repro, let's reopen with a full program.
