### ISSUE TITLE
Strange behavior during child resource changes

### ISSUE THREAD

**Issue by NinoFloris** [pulumi/pulumi#3172]
Strange behavior during child resource changes

`parent` behavior when a child changes a property (here `minPortsPerVm`) should result in a `replace` action yet it results in a `create` and `delete` (of more than is being created as well).

<img width="485" alt="Screenshot 2019-09-03 at 19 43 36" src="https://user-images.githubusercontent.com/4218809/64202399-54cfe000-ce91-11e9-8f7b-d822b798a2eb.png">

At this point it's not a true `replace` so it also doesn't respect `deleteBeforeReplace` set on the child anymore (this will throw api errors as gcp allows only one NAT setup `ALL_SUBNETWORKS_ALL_IP_RANGES`).

Succesful diff must look like this
<img width="624" alt="Screenshot 2019-09-03 at 19 45 13" src="https://user-images.githubusercontent.com/4218809/64202610-d9226300-ce91-11e9-91e3-04e92eeecd16.png">

First raised on slack: https://pulumi-community.slack.com/archives/C84L4E3N1/p1567532795201800

Repro: 
```ts
import * as gcp from "@pulumi/gcp";

const computeEngine = new gcp.projects.Service("compute-engine-api", {
    disableDependentServices: true,
    service: "compute.googleapis.com"
});

const primaryNetworkName = "test"

export const primaryNetwork = new gcp.compute.Network(
    primaryNetworkName,
    { autoCreateSubnetworks: true },
    { dependsOn: computeEngine }
);

const router = new gcp.compute.Router(
    `${gcp.config.region}-router`,
    {
        network: primaryNetwork.name
    })

new gcp.compute.RouterNat(
    `${gcp.config.region}-nat`,
    {
        natIpAllocateOption: "AUTO_ONLY",
        router: router.name,
        minPortsPerVm: 128,
        logConfig: {
            enable: true,
            filter: "ALL"
        },
        sourceSubnetworkIpRangesToNat: "ALL_SUBNETWORKS_ALL_IP_RANGES"
    }, {
    parent: router,
    /* Each region can only have one 'all_subnetworks' NAT */
    deleteBeforeReplace: true
})
```

Steps:
1. Deploy.
2. Change a property on `RouterNat`, try to deploy again, this will fail because create is done before delete.
3. Destroy stack.
4. Remove `parent` from `RouterNat`, deploy.
5. Change a property on `RouterNat`, deploy again, now it's flagged as a `replace` and it will succeed.

**Comment by pgavlin** [comment]
@NinoFloris I can't reproduce this issue: when I deploy the code above, then change `minPortsPerVm` from `128` to `64`, I see the expected replacement:

```
hela:gh3172 pgavlin$ pulumi pre
Previewing update (dev):

     Type                         Name             Plan        Info
     pulumi:pulumi:Stack          gh3172-dev
     └─ gcp:compute:Router        us-west1-router
 +-     └─ gcp:compute:RouterNat  us-west1-nat     replace     [diff: ~minPortsPerVm]

Resources:
    +-1 to replace
    4 unchanged
```

What versions of the Pulumi CLI and packages are you using?

**Comment by NinoFloris** [comment]
v1.0.0-rc.1 of packages  and cli

**Comment by pgavlin** [comment]
FWIW, it appears from your first screen shot that `europe-west4-router` was originally a child of `gcp-infra-dev`. If that changed at the same time as the change to `minPortsPerVm`, you would see the behavior you described originally: the parent of a resource is a part of that resource's identity, so changing its parent will cause the CLI to see the creation of a new resource and the deletion of the original.

**Comment by pgavlin** [comment]
Indeed, if I take the actions I described--deploy the stack with the `Router` parented to the `Network`, then remove that parent-child relationship and re-deploy--I see the behavior originally described:

```
hela:gh3172 pgavlin$ pulumi up
Previewing update (dev):

     Type                            Name             Plan
     pulumi:pulumi:Stack             gh3172-dev
 +   ├─ gcp:compute:Router           us-west1-router  create
 +   │  └─ gcp:compute:RouterNat     us-west1-nat     create
     └─ gcp:compute:Network          test
 -      └─ gcp:compute:Router        us-west1-router  delete
 -         └─ gcp:compute:RouterNat  us-west1-nat     delete

Resources:
    + 2 to create
    - 2 to delete
    4 changes. 3 unchanged

Do you want to perform this update? no
confirmation declined, not proceeding with the update
```

This is expected behavior due to the change in resource identities. The best documentation I can find for this is [here](https://www.pulumi.com/docs/intro/concepts/programming-model/#urns); we should consider clarifying this.

**Comment by NinoFloris** [comment]
Thanks for the quick replies!

Right, yes I just looked at my last commits and I see I indeed removed another parent as well.
