### ISSUE TITLE
Provider builds failing due to a transitive dependency on an unreachable repo

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#3173]
This is essentially https://github.com/hashicorp/terraform/issues/22664. We have seen this in at least these repos:
- [x] https://github.com/pulumi-aws
- [x] https://github.com/pulumi-gcp
- [x] https://github.com/pulumi-azure
- [x] https://github.com/pulumi-azuread
- [x] https://github.com/pulumi-awsx

It is likely that this affects anything that is downstream of https://github.com/pulumi-terraform.

**Comment by stack72** [comment]
https://github.com/pulumi/pulumi-azuread/pull/24
https://github.com/pulumi/pulumi-azure/pull/350
https://github.com/pulumi/pulumi-gcp/pull/210
https://github.com/pulumi/pulumi-aws/pull/731

**Comment by stack72** [comment]
All are passing now except pulumi-awsx which has a legit issue

**Comment by pgavlin** [comment]
Let's leave this open until we're sure all repos are clean. I'll remove the P1 label now that the core providers are fixed.

**Comment by pgavlin** [comment]
@stack72 can you add the other repos you've fixed/opened PRs for to this list?

**Comment by stack72** [comment]
https://github.com/pulumi/pulumi-datadog/pull/21
https://github.com/pulumi/pulumi-docker/pull/101
https://github.com/pulumi/pulumi-gitlab/pull/14
https://github.com/pulumi/pulumi-linode/pull/24
https://github.com/pulumi/pulumi-cloudflare/pull/34
https://github.com/pulumi/pulumi-tls/pull/8
https://github.com/pulumi/pulumi-dnsimple/pull/11
https://github.com/pulumi/pulumi-f5bigip/pull/28
https://github.com/pulumi/pulumi-postgresql/pull/15
https://github.com/pulumi/pulumi-mysql/pull/21
https://github.com/pulumi/pulumi-openstack/pull/57
https://github.com/pulumi/pulumi-vsphere/pull/40
https://github.com/pulumi/pulumi-digitalocean/pull/32
https://github.com/pulumi/pulumi-packet/pull/32
https://github.com/pulumi/pulumi-newrelic/pull/23
https://github.com/pulumi/pulumi-random/pull/46

**Comment by stack72** [comment]
https://github.com/pulumi/pulumi-cloud/pull/745

**Comment by stack72** [comment]
All repos are now clear of this issue as far as I can tell
