### ISSUE TITLE
very slow `pulumi up`, possibly due to slow snapshot-related operations

### ISSUE THREAD

**Issue by redbaron** [pulumi/pulumi#3178]
our organization stacks are taking unbearable amount of time to run even on a simple no change `pulumi up`.  Stack with 165 resources takes ~11 minutes to complete with no changes made and no refresh option used.

`--logtostderr -v1` option generates ~15M log file with a steady stream of events with no obvious gaps, except for a single entry:

```
I0903 11:06:28.070124    1901 snapshot.go:473] Marked old state snapshot as done: urn:pulumi:gke01-london::gcp-gke::nakhoda:CertManager$kubernetes:core/v1:Namespace$kubernetes:yaml:ConfigFile::cert-manager-role-binding
```

each `Marked old state snapshot as done` seems to be taking 2.3-2.5 seconds and there is one such record for ever resource, so just that step alone is 6.3 minutes.  I am yet to find where rest of time is spent, but that is  a start.

**Comment by lukehoban** [comment]
We investigated the logs from both @redbaron's CLI and the Pulumi Service backend. 

It appears this is related to the CLI client making 13 calls to `POST /encrypt` per 1 call to `PATCH /checkpoint` for this stack update.  These calls to  `/encrypt` are related to  encrypting values in the checkpoint file (see for example https://www.pulumi.com/blog/managing-secrets-with-pulumi/).

The `encrypt` calls are processed serially, and are not cached locally.

Combined with the round-trip latency of @redbaron's connection, this leads to each checkpoint write being ~10s apart.  In particular, we are seeing each `encrypt` call spend <20ms processing at api.pulumi.com, but the calls are spread out each occurring 500ms-1s apart, presumably due to round trip latency (and some client processing).

There are a few key things we should look into improving here:
1. Cache encrypt results locally so we do not have to reencyrpt the same values repeatedly.
2. Allow users to optionally turn off checkpoint encryption
3. Allow changing secrets providers for an existing stack (this would have provided a workaround)

**Comment by redbaron** [comment]
@lukehoban , is it possible to attach it from a different angle and see why resources get touched in a stack at all? When plan come back with no changes, why there is any activity to checkpoint? Current explanation implies that `pulumi up` run time is linear with number of resources in a stack, not with a  number of changes in a plan, which looks strange.

**Comment by mikhailshilkov** [comment]
@lukehoban  How about

4. Make the backend globally distributed with low read/write latencies for people around the world? I've heard Pulumi makes it easier ;-)

**Comment by redbaron** [comment]
it's gone worse, same stack, 3 more resources (167 in total), all latest versions, no-op pulumi up, : **31 minutes and keeps going.**

It reaches the point where Pulumi stops helps helping to manage infrastructure and be more of a obstacle. 

we consider switching to a local stack backend, but then having a subscription for pulumi.com gets us zero value, other than showing a support for  this otherwise great product.

**Comment by lukehoban** [comment]
> s it possible to attack it from a different angle and see why resources get touched in a stack at all? 

Yes - I am very interested in why you are seeing 165 checkpoint writes given you say you are making no changes. 

Can you share the CLI output from the preview or update?

**Comment by lukehoban** [comment]
Note that we’re also looking into a fix which should address (1) above - which I believe is the core of the issue here at https://github.com/pulumi/pulumi/pull/3183.

**Comment by redbaron** [comment]
@lukehoban , debug.log I've sent over email *is* CLI output:

```
</dev/null pulumi up --diff --stack ${PULUMI_STACK} --logtostderr -v=9 &>/debug.log
```

**Comment by redbaron** [comment]
@lukehoban ,

> Yes - I am very interested in why you are seeing 165 checkpoint writes given you say you are making no changes.

how can I help debugging this issue?

**Comment by redbaron** [comment]
I just ran same build in a Googles Cloud Build , it ran build in a VM with public IP address in Michigan , so it must be slashing latencies significantly, but build continues to timeout.

**Comment by redbaron** [comment]
another unscientific datapoint: if plan has updated resources, it completes in 10 minutes, if plan is clean it doesn't finish even in one hour.

**Comment by redbaron** [comment]
we are still affected by it :(  given that very same `pulumi up` can take drastically different times to complete  it also might be a data race in one of your Go components. I'd be happy to run debug versions with race detector enabled if you have them.

Plugins we use in this stack:

- @pulumi/pulumi
- @pulumi/gcp
- @pulumi/kubernetes
- @pulumi/cloudflare

**Comment by pgavlin** [comment]
Hopefully the changes in https://github.com/pulumi/pulumi/pull/3238 will help us track this down. I'll ping this thread once a dev build with those changes has been published (should be later today). We can then try collecting some traces for analysis.

**Comment by pgavlin** [comment]
Okay, build `1.2.0-alpha.1568668603` has support for emitting tracing data to a file. You can either build from source (just build at `HEAD` in `master`), or install this version like so: `curl -sSL https://get.pulumi.com | sh -s -- --version 1.2.0-alpha.1568668603`. Once installation has finished, you can collect a local execution trace by passing a `file:` URL to `--tracing`:

```bash
$ pulumi up --tracing=file:./up.trace
```

You can then email us the trace and we may be able to glean some more information.

**Comment by NinoFloris** [comment]
We're in the same boat (less resources) running a trace as we speak.

**Comment by NinoFloris** [comment]
@pgavlin sent you the trace in a slack DM :)

**Comment by lukehoban** [comment]
@pgavlin and I just looked at @NinoFloris's trace.  It is a 5m trace with 24s preview and a 4m5s update. 
 
A few observations:
1. It appears that 3m12s of the overall 4m5s of the update are related to encrypt calls - very similar to https://github.com/pulumi/pulumi/issues/3178#issuecomment-528108790.  This seems to be the main issue.
2. There appear to be 57 resources changing during this update -so there is indeed churn here - though it should not result in this long of an update.
3. There is a ReadResource for a stack reference which takes 16s during the update phase - that feels like much too long.
4. Lots of Check and Diff RPCs calls which are (a) taking >100ms which seems like a lot and (b) are all serialized.  Both during preview and during update.  These add up to ~20s overall - most of the preview time, and a nontrivial chunk for the update.
5. Each PATCH checkpoint is taking ~300ms - which is quite a lot.  This adds up to ~20s even by itself.

**Comment by lukehoban** [comment]
@redbaron Any chance you would be able to collect the same trace as noted in https://github.com/pulumi/pulumi/issues/3178#issuecomment-531999313 and share with us so we can correlate the data from your update with the above.  It seems clear that (1) is an issue in both cases, but we want to make sure there aren't any additional issues that are surfaced from looking at your case.

**Comment by NinoFloris** [comment]
@lukehoban great analysis! Nice work. 

>There appear to be 57 resources changing

There were actually only 4 leaf resources that actually change according to preview

**Comment by lukehoban** [comment]
> There were actually only 4 leaf resources that actually change according to preview

Can you share what the preview and/or update output looked like? (redacted as needed)

**Comment by redbaron** [comment]
Yes, I meant to do it today, but could fine time to do this experiment, I ll provide traces tomorrow

-------- Original Message --------

**Comment by redbaron** [comment]
@lukehoban , I collected traces and it runs for a less than a minute. I also checked with latest pulumi 1.1.0 and it again runs for less than a minute.

So it is clearly something on our side which changed.  We recently caught a bug where resources were  unintentionally reparented and I think that is what might was causing problems. In short , we were updating same `opts` object in multiple constructors, every time setting new parent. I can imagine it might be throwing off some logic in your engine so it start to go in loops.


Roughly it looked like this:

```
class CompA extends pulumi.ComponentResource {
 constructor(... , opts: pulumi.ResourceOptions) {
    super(..., opts);
    opts["parent"] = this;   // <<< asking for trouble
    const k8sOpts = { ...opts, ...{ provider: provider } };
    const ns = new k8s.core.v1.Namespace(..., k8sOpts);
    k8sOpts["parent"] =  ns;   // <<<< first reparenting ,and I think it also might make `ns` to be parent of self inside engine
    new k8s.core.v1,....(... , k8sOpts) // note: same k8sOpts object passed to many k8s resources
    new ComponentB(.... , k8sOpts) //  pass further down
    new k8s.core.v1,....(... , k8sOpts) // continue to create k8s objects with tainted k8sOpts
 }
}

class CompA extends pulumi.ComponentResource {
  constructor(..., opts: pulumi.ResourceOptions) {
        super(..., opts);
        opts["parent"] = this;   // all registered objects are changing parent again?
        new ...Resource(..., opts)
  }

}
```

unfortunately I it also means I have no reproducer for you anymore as it would require either rolling back to old version of stack (not an option) or crating completely new stack, but depends on some unshareable singleton so it is not that easy :(

**Comment by lukehoban** [comment]
The most significant contributing factor in the three cases we've gotten traces for was fixed in https://github.com/pulumi/pulumi/pull/3183, which will be released this week.

I'm going to close this out - and have opened https://github.com/pulumi/pulumi/issues/3257 to track the remaining issues.

If others see performance issues - please share traces on #3257 so we can confirm whether there are any additional concerns.
