### ISSUE TITLE
Document Engine API boundary

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#318]
https://github.com/pulumi/pulumi-fabric/pull/315 introduced the Engine which allows the deployment service to host parts of Lumi.  Presently, all of the exports on the engine are undocumented, and we should fix that.

The API surface was "designed" by just extracting all the existing lumi commands, so as part of this we should a clean up pass over the boundary to try to improve it.

**Comment by lukehoban** [comment]
We do document some of this boundary for the layman at https://www.pulumi.com/docs/intro/concepts/how-pulumi-works/.  As far as the internal boundary - I think we have what we need for now, and will formalize internal APIs more as needed for new user scenarios.
