### ISSUE TITLE
`pulumi new --yes` doesn't use all defaults

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#3193]
Given the `--help` output on `pulumi new --help` I expect `pulumi new ... --yes` to use the default values for all project setup, but it fails on the project name. When I `pulumi new ...` (without `--yes`) it prompts me for the project name, but accepts the default of the current working directory name by hitting `<enter>` on the prompt. `pulumi new ... --yes` should do this too for the project name.

```
11:14:46 [eks-output-issue] $ pulumi new aws-typescript --yes
Created project ''

error: failed to load Pulumi project located at "/Users/clstokes/cc/eks-output-issue/Pulumi.yaml": project is missing a 'name' attribute
11:14:50 [eks-output-issue] $
```

**Comment by snowsky** [comment]
I don't run into the issue with v1.1.0.

**Comment by clstokes** [comment]
@snowsky You're right! I just tried with `v1.1.0` and it works as expected. Closing this.

**Comment by snowsky** [comment]
It may be related with the other ticket #3078. I tried with an existing project and got the exact error message "Created project ''".
