### ISSUE TITLE
ebs availabilityZone should be optional

### ISSUE THREAD

**Issue by cowwoc** [pulumi/pulumi#3211]
`aws.ec2.InstanceArgs` has an optional `availabilityZone` but `aws.ebs.VolumeArgs` has a mandatory `availabilityZone`. I am expecting the latter to be optional as well.

**Comment by rawkode** [comment]
You should use your created instance and fetch it's availabilityZone.

There's no "default"

AWS picks one at random.

By not specifying one in your EBS volume, you'd end up with them in different zones

**Comment by cowwoc** [comment]
I wanted to change the default size of the instance disk so I didn't expect to create the disk after the server. But digging into this further, I don't need to create a `aws.ebs.Volume` at all. The following worked for me:

```
const server = new aws.ec2.Instance("sparrow-vm", {
	keyName: "someName",
	instanceType: someType,
	securityGroups: [securityGroup.name],
	ami: someAmi,
	ebsBlockDevices:
		[
			{
				deleteOnTermination: true,
				deviceName: "/dev/xvda",
				volumeSize: 16,
				volumeType: "gp2"
			}
		]
});
```

Meaning, I just had to customize `ebsBlockDevices` on instance initialization.
