### ISSUE TITLE
brew version not updated to 1.1.0

### ISSUE THREAD

**Issue by lemaral** [pulumi/pulumi#3221]
pulumi up 
warning: A new version of Pulumi is available. To upgrade from version '1.0.0' to '1.1.0', run
   $ brew upgrade pulumi
brew upgrade pulumi
Error: pulumi 1.0.0_1 already installed
Confusing...

**Comment by nesl247** [comment]
I think this can be closed as it is available now.

**Comment by lemaral** [comment]
Indeed it is thanks
