### ISSUE TITLE
catch future checkpoint errors at `pulumi stack import` time

### ISSUE THREAD

**Issue by redbaron** [pulumi/pulumi#3222]
we imported  manually edited stack without errors, then run `pulumi plan`. neither showed any errors, but at update time we've got:

```
    [urn=urn:pulumi:gke01-london::gcp-gke::pulumi:pulumi:Stack::gcp-gke-gke01-london]
error: post-step event returned an error: failed to verify snapshot: child resource urn:pulumi:gke01-london::gcp-gke::nakhoda:IngressController$kubernetes:core/v1:Namespace$kubernetes:yaml:ConfigFile::ingress-churn-public-ingress refers to missing parent urn:pulumi:gke01-london::gcp-gke::nakhoda:IngressController$kubernetes:core/v1:Namespaceingress-churn-public
```

it would be really nice if import have caught it

**Comment by pgavlin** [comment]
Thanks for the report. I do think that this is a good idea--if we really need the ability to import invalid checkpoints (stranger things have happened)--we can add a flag that allows that.
