### ISSUE TITLE
Latest version number should come from brew

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3230]
Anytime I run a Pulumi command, I get this warning right now:

```
$ pulumi ...
warning: A new version of Pulumi is available. To upgrade from version '1.0.0' to '1.1.0', run
   $ brew upgrade pulumi
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

Yet running the command as suggested just issues an error:

```
Error: pulumi 64 already installed
```

I assume this is because the latest version hasn't been merged into Brew yet: https://github.com/pulumi/pulumi/issues/3221.

This is quite annoying as an end user. Is there any reason we can't take the latest version from Brew itself for purposes of checking if you're on the latest?

**Comment by lukehoban** [comment]
Yes - we either need to pull this version from brew, or else hold off on pushing to a new minimum version until we are sure brew (and any other package managers we support in the future) have the latest.
