### ISSUE TITLE
Example on setting / getting / passing non-primitive type to config?

### ISSUE THREAD

**Issue by zanhsieh** [pulumi/pulumi#3232]
Hi,

Just wonder if I could pass nested type into config. If so, what is the cli syntax and how should I call them from the code.

What I intend to do is:

```
$ pulumi config set mydict1 {"dict1": "val1"}
```

And we should see in Pulumi.dev.yaml similar to this:
```
# Pulumi.dev.yaml; pseudo-code, not working 
config:
  aws:region: us-east-2
  test-pulumi:mydict1:
    dict1: val1
```

And get it should like this:
```
$ pulumi get mydict1
{"dict1": "val1"}
```

Is this even possible? How to call it in the code?

**Comment by lukehoban** [comment]
This is being tracked in https://github.com/pulumi/pulumi/issues/2306. 

The workaround for now is to JSON encode the config values and then use `.getObject` to deserialize inside your Pulumi program.
