### ISSUE TITLE
unable to use inquirerjs in pulumi program

### ISSUE THREAD

**Issue by Place1** [pulumi/pulumi#3233]
Sorry for the lack of details but i'm not familiar enough with pulumi's internals for this issue.

Today I thought it'd be fun to write a pulumi program that prompts the user for it's own configuration using [InquirerJS](https://github.com/SBoudrias/Inquirer.js/)

Here's what my program looks like:

```typescript
import * as k8s from '@pulumi/kubernetes';
import * as inquirer from 'inquirer';

async function main() {
  const response = await inquirer.prompt({
    name: 'name',
    type: 'input',
    default: 'default-name',
  });

  new k8s.core.v1.Namespace('namespace', {
    metadata: {
      name: response.name,
    }
  });
}

main();
```

When the program runs I get the following output:

```bash
➜  kubernetes git:(master) ✗ pulumi up                            
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE to remember): 
Previewing update (test):

     Type                 Name             Plan       Info
 +   pulumi:pulumi:Stack  kubernetes-test  create     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (kubernetes-test):
    error: an unhandled error occurred: Program exited with non-zero exit code: -1
```

If I run the same program with ts-node (but the pulumi related code commented out) the prompt works as expected.

Is this a bug or just not a supported use-case. I was hoping to make use of this so that others on my team could more easily create development/testing environments.

**Comment by leezen** [comment]
I think there's probably some ways to get stdin to work with a Pulumi program, but in general, I would not recommend trying to do so. The CLI is already running in an environment where a lot of the i/o is being managed in various ways and trying to inject more into that environment seems awkward. If the goal is to get user input into the program while running the program, it probably makes more sense to simply await on some kind of remote network call, e.g. query an API endpoint for user input. Or, even run that API on the client itself, have the user provide the inputs via a web browser, and read those over the network socket within the Pulumi program.
