### ISSUE TITLE
Problem with export ressource with prefix (python problem)

### ISSUE THREAD

**Issue by ut0mt8** [pulumi/pulumi#3234]
Dumb question but what I wanted is something really simple, just prefixing the name of a ressource with 'http://'. 

I've tried  :
```
pulumi.export('nglb_http_endpoint', 'http://'+elb.dns_name')
```
with elb an ElasticLoadBalancer ressource.

But I have an type error that I cannot concat string with Output.
TypeError: can only concatenate str (not "Output") to str

I cannot find the way to convert elb.dns_name to str. str() is not working btw.
How to do this ?

**Comment by pgavlin** [comment]
You can do this with `Output.apply`:

```python
pulumi.export('nglb_http_endpoint', elb.dns_name.apply(lambda dns_name: 'http://'+dns_name))
```

**Comment by ut0mt8** [comment]
Thanks you.
