### ISSUE TITLE
Python `TypeError: unsupported operand type(s) for +: 'dict_values' and 'list'` when using ResourceOptions.providers

### ISSUE THREAD

**Issue by jeffmace** [pulumi/pulumi#3235]
I get an `TypeError: unsupported operand type(s) for +: 'dict_values' and 'list'` error when attempting to merge two instances of the class and one of them uses `ResourceOptions.providers`.

This happens because https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/resource.py#L427 returns a `dict_values` object and not a `list`. The issue can be fixed by replacing that line with `options.providers = list(options.providers.values())`. I am using the `pulumi/pulumi:v1.1.0` Docker image that runs Python 3.7.4.

This code will fail with the error.
```
import pulumi

pulumi.ResourceOptions.merge(
    pulumi.ResourceOptions(providers={}),
    pulumi.ResourceOptions(),
)
```

**Comment by pgavlin** [comment]
Thanks for the report!
