### ISSUE TITLE
CLI Performance Issues

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3257]
Collecting several of the issues we've observed in CLI performance traces that are not yet addressed, and which we should look into individually:

Issues from trace from @NinoFloris in https://github.com/pulumi/pulumi/issues/3178#issuecomment-532375183:
- [ ] There appear to be 57 resources changing during this update -so there is indeed churn here - though it should not result in this long of an update.  Edit: @NinoFloris later pointed out that his CLI showed only 6 proposed changes in preview and 2 in update (the second failing).
- [ ] There is a ReadResource for a stack reference which takes 16s during the update phase - that feels like much too long.
- [ ] Lots of Check and Diff RPCs calls which are (a) taking >100ms which seems like a lot and (b) are all serialized. Both during preview and during update. These add up to ~20s overall - most of the preview time, and a nontrivial chunk for the update.
- [ ] Each PATCH checkpoint is taking ~300ms - which is quite a lot. This adds up to ~20s even by itself.
- [ ] For each patch checkpoint, we are uploading ~60k, and there appears to be ~100ms of server-side processing time on average (though this includes trying to read the request body, which may include waiting on the client to send the full payload), and ~200ms of other (presumably client and network) time.

**Comment by lukehoban** [comment]
For others seeing CLI performance issues - please collect a trace as in the steps below and share it here or in DM on the Pulumi Community Slack:

-----

Build 1.2.0-alpha.1568668603 has support for emitting tracing data to a file. You can either build from source (just build at HEAD in master), or install this version like so: `curl -sSL https://get.pulumi.com | sh -s -- --version 1.2.0-alpha.1568668603`. Once installation has finished, you can collect a local execution trace by passing a file: URL to --tracing:

```
$ pulumi up --tracing=file:./up.trace
```

You can then email us the trace and we may be able to glean some more information.

**Comment by lukehoban** [comment]
>  Lots of Check and Diff RPCs calls which are (a) taking >100ms which seems like a lot and (b) are all serialized. Both during preview and during update. These add up to ~20s overall - most of the preview time, and a nontrivial chunk for the update.

We got another trace that showed an even more extreme version of this.  It had 106 resources (almost all Kubernetes?).  The traces shows serially calling `Diff` and then `Check` on each of these resources.  Each call takes 2-5s (significantly worse than expected).  There are no actual updates being done at all here.  Just the work to check and diff is taking up ~10m of wall clock time.

**Comment by lukehoban** [comment]
> Lots of Check and Diff RPCs calls which .... are all serialized. 

Opened https://github.com/pulumi/pulumi/issues/3302 to track this specifically.

**Comment by lukehoban** [comment]
> Each [Kubernetes Check/Diff] call takes 2-5s (significantly worse than expected).

https://github.com/pulumi/pulumi-kubernetes/issues/827 is tracking this one.

**Comment by pgavlin** [comment]
We have done quite a bit of work on this in recent weeks:
- https://github.com/pulumi/pulumi/pull/3332
- https://github.com/pulumi/pulumi/pull/3340 
- https://github.com/pulumi/pulumi/pull/3336
- https://github.com/pulumi/pulumi/pull/3331

A fix for https://github.com/pulumi/pulumi/issues/3302 is also in review.

**Comment by brandonkal** [comment]
I'm seeing extreme delays finishing a `pulumi destroy`. Here you can see a 30+ second delay after the last kubernetes object is deleted.

1. Operations are sequential for the most part when they could be parallel.
2. Pulumi usually hangs after the last operation which is annoying.

[Pulumi-slow-destroy-trace.zip](https://github.com/pulumi/pulumi/files/4015049/Pulumi-slow-destroy-trace.zip)
I've also attached the program file for reference on what it is (a single helm chart). The `pulumi up` graph is skewed because this won't actually deploy completely (helm hook annotations are ignored).

**Comment by lukehoban** [comment]
Cristoph shared a trace offline - it shows serialized calls to `patchCheckpoint` each taking 30s on the critical path leading to a 30m+ deployment.

<img width="608" alt="trace" src="https://user-images.githubusercontent.com/223467/73212381-fb4ba480-4102-11ea-8c39-65606fc77c0b.PNG">

**Comment by pgavlin** [comment]
@lukehoban any idea how much data is being sent there?

**Comment by julienvincent** [comment]
I am seeing similar extreme performance delays for stack applies, primarily for kubernetes-heavy stacks.

Recently after adding a few more resources to the stack I started getting program crashes similar to what is being reported in #3279 

Here is my trace from when the execution crashes:

[up.trace.zip](https://github.com/pulumi/pulumi/files/4128466/up.trace.zip)

Here is a trace after setting `NODE_OPTIONS=--max_old_space_size=6144`

[up.trace.zip](https://github.com/pulumi/pulumi/files/4128467/up.trace.zip)

**Comment by lukehoban** [comment]
@julienvincent Thanks for the details.  My guess is what you are seeing is related to the issue being tracked in https://github.com/pulumi/pulumi-kubernetes/issues/963.

**Comment by julienvincent** [comment]
@lukehoban Thanks!

**Comment by lukehoban** [comment]
We've released three major performance fixes recently - which I believe address all of the various things reported on this thread so far:

* https://github.com/pulumi/pulumi/pull/3851
* https://github.com/pulumi/pulumi-kubernetes/pull/974
* https://github.com/pulumi/pulumi/pull/3860

Given that - I'm going to close this one out for now.  If folks see any performance issues after upgrading to latest versions - please do open new issues with details so we can track any future performance investments.
