### ISSUE TITLE
get_zone() failing to raise error?

### ISSUE THREAD

**Issue by astronouth7303** [pulumi/pulumi#3262]
ok, this is weird.

I'm getting the log:

```
  pulumi:pulumi:Stack (cardboard-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/astraluma/.local/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
        return future.result()
      File "/home/astraluma/.virtualenvs/gobuildit/cardboard/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 72, in run_in_stack
        raise RPC_MANAGER.unhandled_exception.with_traceback(RPC_MANAGER.exception_traceback)
      File "/home/astraluma/.virtualenvs/gobuildit/cardboard/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc_function(*args, **kwargs)
      File "/home/astraluma/.virtualenvs/gobuildit/cardboard/lib/python3.7/site-packages/pulumi/runtime/invoke.py", line 157, in do_invoke
        resp = await asyncio.get_event_loop().run_in_executor(None, do_invoke)
      File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/astraluma/.virtualenvs/gobuildit/cardboard/lib/python3.7/site-packages/pulumi/runtime/invoke.py", line 155, in do_invoke
        raise Exception(details)
    Exception: invocation of aws:route53/getZone:getZone returned an error: invoking aws:route53/getZone:getZone: no matching Route53Zone found
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

This sounds a lot like #2908 except it's working.

The only place I call `get_zone` is https://github.com/dingbots/putils/blob/master/putils/aws.py#L115-L130 and `print()` additions show it to be working correctly and returning stuff. (ie, exception stuff is working

I'm actually not sure what's calling it with the unknown name?

This particular issue is being particularly resistant to reduction and reproducing--starting from a fresh project fails to reproduce it, and reducing it has me down to a single import that only defines things.

I guess I'll update this if I can reduce this.

**Comment by astronouth7303** [comment]
Like, I copy/pasted `__main__.py` into a new pulumi project (using the same virtual environment) and it works:

```python
import pulumi
from putils import find_zone

config = pulumi.Config('cardboard')
basedomain = config.require("domain")

zone = find_zone(basedomain)
print(zone.id)


api_domain = f'api.{basedomain}'


pulumi.export('zone', zone.id)
pulumi.export('webhook_url',  f"https://{api_domain}/postreceive")
```

The only thing I know that's different between the projects is:
* The name
* Some additional secrets in the config
* Files that are currently unused (because `__main__.py` is stripped down)

Oh, and the zone ID gets printed. A value is returned, and it's functional, and the `print()` above executes.

But pulumi overall fails and dumps the stack above.

**Comment by leezen** [comment]
Are you still running into this issue?

**Comment by astronouth7303** [comment]
I haven't touched this code in a while.
