### ISSUE TITLE
Auto-detect the language/runtime

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#329]
At the moment, we require developers to specify the runtime environment their code should be run in explicitly, using a `runtime` attribute in the `Pulumi.yaml` (or `.json`) file:

    name: mypackage
    description: A cool package.
    runtime: nodejs

Eventually, I presume we will also support specifying a runtime version, e.g. `nodejs@6.10.2`.

This adds to the "hello world" boilerplate, however, and is easy enough to infer.  For instance, if there's a `package.json`, we can assume the runtime is `nodejs@latest`.

At the moment, the fabric is 100% agnostic to the language runtimes, but it feels like something we should support, especially if we're getting into the build business anyway.  Heck, we might even support a `Detect` function on the `LanguageRuntime` API, so that the fabric remains agnostic.

**Comment by lukehoban** [comment]
There's rather limited need for this in practice today - and it is not something we've seen asks for.  Possibly the only really practical benefit of this would be if it allowed getting rid of the concept of `Pulumi.yaml` file entirely - though there are likely bigger reasons that is difficult (identifying project root, identifying current project name).  Closing this out as a standalone request.

**Comment by lukehoban** [comment]
I opened https://github.com/pulumi/pulumi/issues/3745 to track the idea of not requiring `Pulumi.yaml`.
