### ISSUE TITLE
Make providers more "contribution friendly" adding a central hub

### ISSUE THREAD

**Issue by fernandocarletti** [pulumi/pulumi#3297]
Hello!

I've been wondering how the contribution for providers could be more friendly. Today the option for non-official providers get a bit shady, where you should point to a custom place (#2789), which is not very practical, since it does not work the same way as the official plugins, being downloaded automatically when installing the dependencies.

A good solution for this could be a central hub to publish the providers, something like NPM where it can integrate with the Github repository and any user could publish their own providers. This could be the source for the plugins installation for the Pulumi CLI, making plugins searchable and simplifying the version management. https://providers.pulumi.io sounds cool :)

WDYT?

**Comment by ryan4yin** [comment]
just like terraform's `https://registry.terraform.io`

**Comment by infin8x** [comment]
Today, we've announced Pulumi Registry, the central place for all Pulumi Packages (Providers & Components): https://www.pulumi.com/registry. Check it out and let us know what you think!

There's also more to come in the coming months, including easier authoring of Pulumi Packages and a self-service way to publish to Pulumi Registry.
