### ISSUE TITLE
pulumi preview shows differences when nothing has changed

### ISSUE THREAD

**Issue by kdreibel** [pulumi/pulumi#3301]
I was doing some refactoring in our `infrastructure` stack, and was using `pulumi preview` to ensure that the changes I make wouldn't change anything (yet).  However, I was getting a lot of changes showing up.  Eventually, I went back to `master` to make sure I had backed everything out, but `pulumi preview` was still showing that things would change.  This goes against my understanding of how `pulumi` should work, so I asked for support in https://pulumi-community.slack.com/archives/C84L4E3N1/p1570135724281600 , where I was eventually advised to file this issue.

Initially I was using `v1.2.0`, but I downgraded to `v0.17.27` as my colleague advised me that the `infrastructure` was brought up using that version.  But I still had the same problem.

Our package.json dependencies are:
```
        "@pulumi/gcp": "^0.16.2",
        "@pulumi/kubernetes": "^0.18.0",
        "@pulumi/pulumi": "^0.16.7",
        "@pulumi/random": "^0.2.0"
```

Here's the preview output:

```
   Type                 Name                           Plan     Info
     pulumi:pulumi:Stack  infrastructure-infrastructure             Version 1.3.0-alpha.1570119193 referenced at node_modules/@pulumi/random/node_modules/@pulumi/pulumi/package.json

     Type                             Name                           Plan        Info
     pulumi:pulumi:Stack              infrastructure-infrastructure              3 messages
 +-  ├─ pulumi:pulumi:StackReference  getmargin/identity/identity    replace
 +-  ├─ gcp:container:Cluster         kube                           replace     [diff: -__defaults,enableBinaryAuthorization,enableIntranodeVisibility,enableTpu~masterAuth,name,nodeConfig]
 +-  ├─ pulumi:providers:kubernetes   kube                           replace     [diff: ~kubeconfig]
 +-  ├─ kubernetes:apps:Deployment    honeycomb                      replace     [diff: ~provider]
 +-  ├─ kubernetes:apps:Deployment    redis-replica                  replace     [diff: ~provider]
 +-  └─ kubernetes:apps:Deployment    redis-primary                  replace     [diff: ~provider]

Diagnostics:
  pulumi:pulumi:Stack (infrastructure-infrastructure):
    Found incompatible versions of @pulumi/pulumi.  Differing major or minor versions are not supported.
      Version 0.16.19 referenced at node_modules/@pulumi/pulumi/package.json
      Version 1.3.0-alpha.1570119193 referenced at node_modules/@pulumi/random/node_modules/@pulumi/pulumi/package.json

Resources:
    +-6 to replace
    29 unchanged
```

I tried a `pulumi up` and just looked at the details.  Here are some highlights:

```
  +-kubernetes:apps/v1beta1:Deployment: (replace)
        [id=default/redis-primary]
        [urn=urn:pulumi:infrastructure::infrastructure::kubernetes:apps/v1beta1:Deployment::redis-primary]
        [provider: urn:pulumi:infrastructure::infrastructure::pulumi:providers:kubernetes::kube::7ee13444-c7df-4201-9b52-b8812522593a => urn:pulumi:infrastructure::infrastructure::pulumi:providers:kubernetes::kube::output<string>]
        apiVersion: "apps/v1beta1"
        kind      : "Deployment"
        metadata  : {
            name: "redis-primary"
        }
```

In the details, the line that's highlighted (as a difference) is 
```
[provider: urn:...::7ee13444-c7df-4201-9b52-b8812522593a => urn:...::output<string>]
```
And that `output<string>` at the end looks odd.  There is also a very long `kubeconfig` value that is being changed to `output<string>`, elsewhere in the details.  Lastly, from details, are these changes WRT `enableBinaryAuthorization` which are odd because again I haven't changed anything.

```
    ++gcp:container/cluster:Cluster: (create-replacement)
        [id=kube-108876a]
        [urn=urn:pulumi:infrastructure::infrastructure::gcp:container/cluster:Cluster::kube]
      - enableBinaryAuthorization: false
      - enableIntranodeVisibility: false
      - enableTpu                : false
      ~ name                     : "kube-108876a" => "kube-cf9e2fe"
    +-gcp:container/cluster:Cluster: (replace)
        [id=kube-108876a]
        [urn=urn:pulumi:infrastructure::infrastructure::gcp:container/cluster:Cluster::kube]
      - enableBinaryAuthorization: false
      - enableIntranodeVisibility: false
      - enableTpu                : false
      ~ name                     : "kube-108876a" => "kube-cf9e2fe"
```

**Comment by pgavlin** [comment]
@kdreibel are you using `yarn` or `npm` to install packages?

**Comment by kdreibel** [comment]
`npm`

**Comment by lblackstone** [comment]
The k8s provider will force a replacement of resources if certain fields in the kubeconfig change. In this case, it looks like the kubeconfig is a computed value (pulumi.Output), which means we can’t tell during preview what’s going to change in the kubeconfig.

We take the conservative choice to preview a replace of resources using that provider anytime the kubeconfig is a computed value since we can't tell for sure if the underlying cluster has changed until the value has been computed. (See https://github.com/pulumi/pulumi-kubernetes/pull/577 for details)

This only applies to the preview, and won’t actually replace the resources if the cluster hasn't changed. For example, a version upgrade of the k8s cluster will show a replace on preview, but won't actually replace the resources when the update is applied. In general, previews are conservative about what will happen when computed values are present.

**Comment by pgavlin** [comment]
@lblackstone is correct w.r.t. the replacement behavior. It's surprising, though, that you're seeing any changes at all after attempting to roll back to the original Pulumi version. Can you share the contents of your package-lock.json?

**Comment by kdreibel** [comment]
Added a .txt extension so github would allow upload

[package-lock.json.txt](https://github.com/pulumi/pulumi/files/3709763/package-lock.json.txt)

**Comment by pgavlin** [comment]
> Initially I was using v1.2.0, but I downgraded to v0.17.27 as my colleague advised me that the infrastructure was brought up using that version. But I still had the same problem.

Are you referring to Pulumi CLI versions here, or `@pulumi/pulumi` versions? Your `package-lock.json` indicates that you're using v0.16.19 of `@pulumi/pulumi`. Is that expected?

**Comment by kdreibel** [comment]
> Are you referring to Pulumi CLI versions here, or `@pulumi/pulumi` versions?
I'm just talking about the Pulumi CLI version

**Comment by oliverholliday** [comment]
I had a similar thing today.

The rather worrying preview included deleting a ton of important resources:
```
Resources:
    ~ 2 to update
    - 78 to delete
    +-15 to replace
    95 changes. 8 unchanged
```

I didn't have any need for this stack anymore so I proceeded anyway resulting in this: 

```
Resources:
    ~ 2 updated
    101 unchanged

Duration: 5m49s
```

Package version changes were:
```
-                "@pulumi/kubernetes": "1.1.0",
-                "@pulumi/pulumi": "1.2.0",
-                "@pulumi/random": "1.0.0"
+                "@pulumi/kubernetes": "1.2.2",
+                "@pulumi/pulumi": "1.3.1",
+                "@pulumi/random": "1.1.0"
```

Full output attached as a text file (I've redacted some keys and UUIDs).

[bug.txt](https://github.com/pulumi/pulumi/files/3734781/bug.txt)

**Comment by nesl247** [comment]
@oliverholliday I believe your issue is related to https://github.com/pulumi/pulumi/issues/3190.

**Comment by kdreibel** [comment]
@pgavlin @lblackstone wondering if there is any movement on this issue, or if we're to interpret the earlier comments to mean "working as expected"?  We're just looking for a path forward here.  Is there a different way we should be doing the `kubeconfig` in order to get a proper preview?  The consequences of a `pulumi up` blowing away the existing infra are too high for us to risk not doing a `pulumi preview` first, or not being able to rely on it.

**Comment by joeduffy** [comment]
@pgavlin I assume this will be resolved with #3327? Should this be duped?

**Comment by kdreibel** [comment]
> @pgavlin I assume this will be resolved with #3327? Should this be duped?

This will *probably* be resolved with #3327.  However, if it were up to me, I'd like to keep this open, so that I can confirm that #3327 really fixes this issue, once it is merged.

**Comment by kdreibel** [comment]
So I am trying to move forward by creating a user role that has readonly permissions, and then doing `pulumi preview` / `pulumi up` with them.  That way, I can selectively grant create permission on certain things, and make sure that resources can't be deleted.  The result of this is test suggests that pulumi *would* destroy the existing cluster, or at least it looks like it's trying.  Please advise.

```
Do you want to perform this update? yes
Updating (getmargin/infrastructure):
     Type                 Name                           Status     Info
     pulumi:pulumi:Stack  infrastructure-infrastructure               Version 1.6.0-alpha.1573150599 referenced at node_modules/@pulumi/random/node_modules/@pulumi/pulumi/package.json

     Type                      Name                           Status                   Info
     pulumi:pulumi:Stack       infrastructure-infrastructure  **failed**               1 error; 4 messages
 +-  └─ gcp:container:Cluster  kube                           **replacing failed**     [diff: -__defaults,enableBinaryAuthorization,enableIntranodeVisibility,enableTpu~masterAuth,name,nodeConfig]; 1 error

Diagnostics:
  gcp:container:Cluster (kube):
    error: Plan apply failed: node_version and min_master_version must be set to equivalent values on create

  pulumi:pulumi:Stack (infrastructure-infrastructure):
    Found incompatible versions of @pulumi/pulumi. Differing major or minor versions are not supported.
      Version 0.16.19 referenced at node_modules/@pulumi/pulumi/package.json
      Version 1.6.0-alpha.1573150599 referenced at node_modules/@pulumi/random/node_modules/@pulumi/pulumi/package.json
    D1108 00:28:44.286302700    2192 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used

    error: update failed

Outputs:
  - devStorageBucketName : "dev-storage-816b6f9"
  - dnsZoneName          : "getmargin-f0a3ad5"
  - dnsZones             : [
  -     [0]: {
          - fqdn: "getmargin.co."
          - name: "getmargin-f0a3ad5"
        }
  -     [1]: {
          - fqdn: "compound.co."
          - name: "compoundco-34b3a2f"
        }
    ]
  - kubeconfig           : [... HIDDEN ...]
  - prodStorageBucketName: "prod-storage-58b17e6"
```

**Comment by lblackstone** [comment]
@kdreibel I can't tell exactly what you changed in your code, but it appears that you may be changing fields that would force a cluster replacement. I'd guess that could be then `name` and/or `nodeConfig`.

The operation is failing because the master/worker versions don't match, probably because something is still using a default value.

**Comment by kdreibel** [comment]
What I'm saying is that this is what I'm getting when nothing has changed in the code.

**Comment by kdreibel** [comment]
Ok I now have a second case where this is occurring.  I added a GCP bucket using `pulumi`, and protected it.  Now, on a second run, it's trying to delete and recreate the bucket (bad), though it won't because it's protected (good).  See `--diff` output here:

```    +-gcp:storage/bucket:Bucket: (replace) 🔒
        [id=bookkeeping-befeb37]
        [urn=urn:pulumi:infrastructure::infrastructure::gcp:storage/bucket:Bucket::bookkeeping]
        forceDestroy: false
        location    : "us"
      ~ name        : "bookkeeping-befeb37" => "bookkeeping-6a75cc0"
        project     : "compound-production"
        storageClass: "multi_regional"
    + gcp:storage/bucketACL:BucketACL: (create)
        [urn=urn:pulumi:infrastructure::infrastructure::gcp:storage/bucketACL:BucketACL::bookkeeping-acl]
        bucket       : output<string>
        predefinedAcl: "private"
```

The Kubernetes cluster that would be destroyed is also in there:
```
      ~ name                     : "kube-108876a" => "kube-2992f0a"
```

**Comment by kdreibel** [comment]
I see this behavior if I do a `pulumi preview` immediately after a `pulumi up`

**Comment by joeduffy** [comment]
I apologize for the delay in replying here.

The fix for https://github.com/pulumi/pulumi/issues/3190 was merged in Pull Request https://github.com/pulumi/pulumi/pull/3327 last week, which will be released later this week. We are working to see whether that addresses the problems above. @lblackstone @pgavlin please do report back here after you've figured out whether it does / does not.

My worry is that this won't actually fix *everything* for you. The title of this bug is probably incorrect now that we understand the broader scope of the challenges you're hitting. The last couple examples were, in fact, **not** specific to previews. My understanding is that you're seeing _replacements when your source program hasn't even changed_, which is a very different problem.

Historically, the only time I remember seeing something like this is when upgrading from very old pre-1.0 CLIs that used our old diffing scheme. Is that possibly what's happening here?

If so, it may be that we'll need to re-import the affected resources, to get the state fixed up to the new representation, and then you'll be good to go. Let's confirm that's what's actually happening and then, if so, @pgavlin should be able to advise on the best path forward.

**Comment by pgavlin** [comment]
@kdreibel we just released Pulumi 1.6.0 yesterday. Can you try updating to the latest version of the CLI and `@pulumi/pulumi` and see if this fixes your issue?

**Comment by kdreibel** [comment]
Pluses: the diff was not as large as before.  It's promising.
Minuses: it still tried to delete a bucket it should not have.  The preview did not say it was going to delete it.  It only failed because the user I ran with doesn't have permission to delete buckets.

```
bash-5.0# pulumi up
Previewing update (getmargin/infrastructure):

     Type                           Name                           Plan       Info
     pulumi:pulumi:Stack            infrastructure-infrastructure             1 message
 ~   ├─ gcp:storage:Bucket          bookkeeping                    update     [diff: ~storageClass]
 ~   ├─ gcp:storage:Bucket          dev-bookkeeping                update     [diff: ~storageClass]
 +   ├─ gcp:storage:BucketACL       bookkeeping-acl                create
 +   ├─ gcp:storage:BucketACL       dev-bookkeeping-acl            create
     ├─ gcp:container:Cluster       kube                                      [diff: +enableShieldedNodes~__defaults,protect,provider]; 1 warning
     ├─ kubernetes:apps:Deployment  redis-primary                             1 warning
     ├─ kubernetes:apps:Deployment  redis-replica                             1 warning
     └─ kubernetes:apps:Deployment  honeycomb                                 1 warning

Diagnostics:
  pulumi:pulumi:Stack (infrastructure-infrastructure):
    [REDACTED]     983 env_linux.cc:71]            Warning: insecure environment read function 'getenv' used

  gcp:container:Cluster (kube):
    warning: urn:pulumi:infrastructure::infrastructure::gcp:container/cluster:Cluster::kube verification warning: "zone": [DEPRECATED] Use location instead

  kubernetes:apps:Deployment (redis-replica):
    warning: apps/v1beta1/Deployment is not supported by Kubernetes 1.16+ clusters. Use apps/v1/Deployment instead.

  kubernetes:apps:Deployment (honeycomb):
    warning: apps/v1beta1/Deployment is not supported by Kubernetes 1.16+ clusters. Use apps/v1/Deployment instead.

  kubernetes:apps:Deployment (redis-primary):
    warning: apps/v1beta1/Deployment is not supported by Kubernetes 1.16+ clusters. Use apps/v1/Deployment instead.

Outputs:
  + bookkeepingBucketName: "bookkeeping-[REDACTED]"
  - devStorageBucketName : "dev-storage-[REDACTED]"

Resources:
    + 2 to create
    ~ 2 to update
    - 1 to delete
    5 changes. 34 unchanged

Do you want to perform this update? yes
Updating (getmargin/infrastructure):

     Type                   Name                           Status                  Info
     pulumi:pulumi:Stack    infrastructure-infrastructure  **failed**              1 error; 1 message
 -   └─ gcp:storage:Bucket  bookkeeping                    **deleting failed**     1 error

Diagnostics:
  gcp:storage:Bucket (bookkeeping):
    error: deleting urn:pulumi:infrastructure::infrastructure::gcp:storage/bucket:Bucket::bookkeeping: googleapi: Error 403: viewonly@compound-production.iam.gserviceaccount.com does not have storage.buckets.delete access to project [REDACTED]., forbidden

  pulumi:pulumi:Stack (infrastructure-infrastructure):
    Error deleting bucket bookkeeping-befeb37: googleapi: Error 403: viewonly@compound-production.iam.gserviceaccount.com does not have storage.buckets.delete access to project [REDACTED]., forbidden

    error: update failed
```

**Comment by pgavlin** [comment]
What does the detailed diff look like? It's strange that the summary lists a resource to delete, but none of the resources in the tree are marked for deletion.

**Comment by kdreibel** [comment]
Now on `pulumi` version v1.6.1 .  The preview *starts* as saying `delete`, but then it thinks for a moment, and then changes it to `update`.  I can get you a screen recording if this would help.

Here's the detailed diff as returned from `pulumi up` + `details` (with UUIDs replaced with Xs)

```
- gcp:storage/bucket:Bucket: (delete)
    [id=bookkeeping-befeb37]
    [urn=urn:pulumi:infrastructure::infrastructure::gcp:storage/bucket:Bucket::bookkeeping]
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:infrastructure::infrastructure::pulumi:pulumi:Stack::infrastructure-infrastructure]
    > pulumi:pulumi:StackReference: (read)
        [id=getmargin/identity/identity]
        [urn=urn:pulumi:infrastructure::infrastructure::pulumi:pulumi:StackReference::getmargin/identity/identity]
        name: "getmargin/identity/identity"
    ~ gcp:storage/bucket:Bucket: (update) 🔒
        [id=dev-bookkeeping-3aca61a]
        [urn=urn:pulumi:infrastructure::infrastructure::gcp:storage/bucket:Bucket::dev-bookkeeping]
        [provider: urn:pulumi:infrastructure::infrastructure::pulumi:providers:gcp::default::XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX => urn:pulumi:infrastructure::infrastructure::pulumi:providers:gcp::default_1_6_0::output<string>]
      ~ storageClass: "MULTI_REGIONAL" => "multi_regional"
    ~ gcp:storage/bucket:Bucket: (update) 🔒
        [id=bookkeeping-750bab1]
        [urn=urn:pulumi:infrastructure::infrastructure::gcp:storage/bucket:Bucket::bookkeeping]
        [provider: urn:pulumi:infrastructure::infrastructure::pulumi:providers:gcp::default::XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX => urn:pulumi:infrastructure::infrastructure::pulumi:providers:gcp::default_1_6_0::output<string>]
      ~ storageClass: "MULTI_REGIONAL" => "multi_regional"
    + gcp:storage/bucketACL:BucketACL: (create)
        [urn=urn:pulumi:infrastructure::infrastructure::gcp:storage/bucketACL:BucketACL::dev-bookkeeping-acl]
        [provider=urn:pulumi:infrastructure::infrastructure::pulumi:providers:gcp::default_1_6_0::XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX]
        bucket       : "dev-bookkeeping-3aca61a"
        predefinedAcl: "private"
    + gcp:storage/bucketACL:BucketACL: (create)
        [urn=urn:pulumi:infrastructure::infrastructure::gcp:storage/bucketACL:BucketACL::bookkeeping-acl]
        [provider=urn:pulumi:infrastructure::infrastructure::pulumi:providers:gcp::default_1_6_0::XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX]
        bucket       : "bookkeeping-750bab1"
        predefinedAcl: "private"
      gcp:container/cluster:Cluster: (same) 🔒
        [id=kube-108876a]
        [urn=urn:pulumi:infrastructure::infrastructure::gcp:container/cluster:Cluster::kube]
        [provider: urn:pulumi:infrastructure::infrastructure::pulumi:providers:gcp::default::XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX => urn:pulumi:infrastructure::infrastructure::pulumi:providers:gcp::default_1_6_0::output<string>]
      + enableShieldedNodes      : false
    --outputs:--
  + bookkeepingBucketName: "bookkeeping-750bab1"
  - devStorageBucketName : "dev-storage-816b6f9"
```

**Comment by tberman** [comment]
@joeduffy any update here? This prevents us from running pulumi properly inside one of our most important stacks and causes a lot of headache any time we attempt to use it.

**Comment by tberman** [comment]
> Historically, the only time I remember seeing something like this is when upgrading from very old pre-1.0 CLIs that used our old diffing scheme. Is that possibly what's happening here?
> 
> If so, it may be that we'll need to re-import the affected resources, to get the state fixed up to the new representation, and then you'll be good to go. Let's confirm that's what's actually happening and then, if so, @pgavlin should be able to advise on the best path forward.

This is definitely possible, this is an old stack.

**Comment by leezen** [comment]
We synced up offline and to summarize, there were two issues:

1. There was an actual delete of a bucket. This was an incomplete operation from a previous update that never finished. At the same time, there was an actual create as there were ACLs specified in the Pulumi program that never made their way to the new bucket.
2. The cluster looked like it was getting replaced due to missing the `container.clusters.getCredentials` permission. Once this permission was granted and a stack refresh occurred, the replace action went away. (For reference: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/gcp/container/#Cluster-masterAuth)

Separately, for others who might see similar outputs and want to debug, it's useful to set those resources to protected (https://www.pulumi.com/docs/intro/concepts/programming-model/#protect), which ensures that the resource will not be deleted.

I believe we're all set and I'm closing the issue, but feel free to open back up if you have other questions/comments.
