### ISSUE TITLE
Make resource functions blocking

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#331]
At the moment, we serialize closures asynchronously.  This permits us to capture references to resources whose properties may not have settled yet.  Sadly, it suffers from two problems:

* Value captures now happen at indeterminate points in time.
* It is possible to create cycles, which themselves create hangs.

As an example, the Pulumi Framework's crawler example contains this code:

```typescript
import * as pulumi from "@pulumi/pulumi";

let countDown = new pulumi.Topic<number>("countDown");

countDown.subscribe("watcher", async (num) => {
    console.log(num);
    if (num > 0) {
        await countDown.publish(num - 1);
    }
});

pulumi.timer.interval("heartbeat", {minutes: 5}, async () => {
    await countDown.publish(25);
});
```

Subtly, the lambda passed to `countDown.subscribe` closes over `countDown` itself, and that object internally stores a reference to the `aws.lambda.Function` that results from serializing the closure.  On its face, this should not be possible!  The ordering strictly happens as: 1) create the topic, 2) create the function, 3) subscribe.  But the use of promises allows us to fast forward in time such that the capture actually depends on the function having been created!

Yikes.

After landing the current Pulumi Fabric overhaul, I'm going to go back and overhaul the overhaul.  Most likely, we will do something like this:

1) Hide all waits and resolutions in C++ code so that we can block safely while still processing incoming RPC requests from the host resource monitor (containing property resolutions).
2) Turn `Resource` into a JavaScript `Proxy`, so we can hook access to properties, and transparently block by calling into the C++ code.  This will eliminate `Computed<T>`, `mapValue`, and vastly simplify consumer code.  I dare say, it will be gorgeous.

So, good news, we see a path to something awesome.  Bad news, it's more work.

**Comment by lukehoban** [comment]
We've decided not to do this.  Current async variants compose well into `Output`, especially once we address https://github.com/pulumi/pulumi-terraform/issues/204.
