### ISSUE TITLE
Minimize usages of deasync library in pulumi

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#3318]
Followup to https://github.com/pulumi/pulumi/issues/3299 with the conclusions of our discussions:

Here are the steps we will take to mitigate/resolve the deasync issue people are hitting.  There are two critical issues, both affecting OSX users:

1. A crash that occurs intermittently on all versions of node and all versions of OSX: https://github.com/pulumi/pulumi/issues/3260
2. A hang that seems to occur only with Catalina and Node12: https://github.com/pulumi/pulumi/issues/3309

To attempt to mitigate/resolve both issues, we will:

- [ ] detect when calls are going through the deasync codepath on Catalina+Node12 and we will issue an explicit console warning (likely linking to this issue, or another useful page).  @lukehoban to take this on initially.
- [ ] update our `@pulumi/pulumi` API so that all code that takes a `Provider` resource now takes a `Provider | ProviderRef` (where `ProviderRef` is effectively a realized string).  
- [ ] add an `async Provider.getRef(): Promise<ProviderRef>` method to enable people to get at the `ProviderRef` for a `Provider`
- [ ] update the `@pulumi/pulumi` `invoke` function to stay synchronous, but now call through a new synchronous-RPC codepath between the language and the engine (outlined in https://github.com/pulumi/pulumi/commit/1138b9e4df9def7ea3de92b73dbe3cc0bac35a7d). We will always call through this for invokes.
- [ ] first  call `deasync Provider.getRef()` in the case where we need to perform an `invoke`, but we only have a `Provider` and not a `ProviderRef`.  We may also choose to warn here, suggesting that people pass along a `ProviderRef` instead.
- [ ] optionally consider a change where we allow pulumi code to export a top-level async function.  This will make life less painful if users need to switch to getting a provider ref and have to async'ify their code. PR for this here: https://github.com/pulumi/pulumi/pull/3321

Benefits of this change:

1. It is non-breaking.  all existing code that ran successfully before should continue to run successfully.
2. Some percentage of users hitting the hang/crash on OSX will no longer hit this.  Specifically, users that are not using a provider will have no issue.
3. Some percentage of users will still hit the hang/crash.  However, they can be notified about the issue and pointed at docs explaining what they should do instead to work around things.  The workaround will be do add an explicit `await provider.getRef()` and pass that value in instead.  Note: this may be unpleasant as it may mean virally making code async.

**Comment by lukehoban** [comment]
@CyrusNajmabadi I think this was closed via https://github.com/pulumi/pulumi/pull/3325?
