### ISSUE TITLE
Kubernetes Secret 'metadata.name' output is a secret even though it is in clear in the console

### ISSUE THREAD

**Issue by mleclercq** [pulumi/pulumi#3333]
Given the following example:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as random from "@pulumi/random";
import * as k8s from "@pulumi/kubernetes";

const password = new random.RandomPassword("password", {
  length: 20
}, { additionalSecretOutputs: ['result'] })
const mySecret = new k8s.core.v1.Secret("my-secret", {
  metadata: {
    namespace: 'default'
  },
  stringData: {
    password: password.result
  }
})

export const secretName = mySecret.metadata.name
```

Running `pulumi up` gives:

```
Updating (dev):

     Type                            Name            Status      
 +   pulumi:pulumi:Stack             tmp-pulumi-dev  created     
 +   ├─ random:index:RandomPassword  password        created     
 +   └─ kubernetes:core:Secret       my-secret       created     
 
Outputs:
    secretName: "[secret]"

Resources:
    + 3 created

Duration: 6s
```

Note that the `secretName` output is marked as a secret, event though the `mySecret.metadata.name` should not be considered a secret and actually shows in plain text in the pulumi console.

Expected behavior:
The `secretName` output should not be a secret.

Side note: it is quite surprising that we have to add `{ additionalSecretOutputs: ['result'] }` to a `RandomPassword` to make its result a secret. One would expect a `RandomPassword` to be considered a secret by default since this is the only difference between a `RandomPassword` and a `RandomString` in terraform.

**Comment by pgavlin** [comment]
Thanks for the report. Aside from not being displayed on the terminal, are there other issues that are caused by `secretName` being marked secret?

> Side note: it is quite surprising that we have to add { additionalSecretOutputs: ['result'] } to a RandomPassword to make its result a secret. One would expect a RandomPassword to be considered a secret by default since this is the only difference between a RandomPassword and a RandomString in terraform.

We have a workitem tracking this: https://github.com/pulumi/pulumi-terraform-bridge/issues/10

> Expected behavior:
The secretName output should not be a secret.

This is a side-effect of the way we handle the serialization of secret data between the Pulumi CLI and the k8s resource provider, the latter of which does not understand secrets natively. I thought we had an issue tracking our efforts to improve this, but I can't find one offhand, so I'll keep this issue for tracking.

**Comment by mleclercq** [comment]
> Thanks for the report. Aside from not being displayed on the terminal, are there other issues that are caused by secretName being marked secret?
The issue is that the "secretness" of `mySecret.metadata.name` is propagated where it is used. For instance I have a deployment that references in an `env` and as a result the whole container spec shows as a secret which reduce the ability to see change details before applying them.

I can try to provide a minimal example if that helps.

**Comment by mikhailshilkov** [comment]
I realize this is an old issue, but since then we've implemented a change to mark k8s secrets as Pulumi secrets automatically: https://github.com/pulumi/pulumi-kubernetes/pull/1577

I will go ahead and resolve this as by design.
