### ISSUE TITLE
pulumi-typescript, issues with multiple versions installed

### ISSUE THREAD

**Issue by spion** [pulumi/pulumi#3338]
I've spent the best part of Friday trying to debug why my deployment doesn't preview at all. I would get errors where an eks ServiceRole would be created but when wrapped `pulumi.output` it would become undefined, i.e.

`pulumi.output(role).apply(role => use role.arn here)`

results with a `TypeError: Cannot read property 'arn' of undefined`

The cause of this was that some of the pulumi submodules were depending on a different version of the core `@pulumi/pulumi` package that defines the Output<T> erm, "monad", and these versions were not compatible among eachother.

Clearing up yarn.lock and installing freshly from scratch fixed this, however I was hoping if there was a way to detect whether there are multiple `@pulumi/pulumi` modules in use and at least show a warning.

This happens easier than you thought it might. Yarn is very liberal about fetching the latest version of every dependency but conservative about modifying `yarn.lock` for already installed dependencies and their dependencies. For example:

* As first step you install `@pulumi/awsx` which pulls e.g. `@pulumi/aws@1.5.0` and `@pulumi/pulumi@1.3.0`
* A new semver minor version of  `@pulumi/pulumi`  is published i.e. `1.4.0`
* You add `@pulumi/eks` with `yarn add`
* Yarn prefers to always pick the latest possible version so it picks `@pulumi/pulumi@1.4.0` as a submodule in `@pulumi/eks` node_modules dir. But it doesn't touch the 1.3.0 version depended on by `@pulumi/awsx` since its locked in yarn.lock. Therefore it has to nest 1.4.0 under eks.
* Both modules use `@pulumi/aws`, however since that module hasn't had an update and its still at `1.5.0`, its installed only once at the toplevel, resulting with it using `@pulumi/pulumi@1.3.0`
* This means that Output<T>'s produced by `1.3.0` from `@pulumi/aws` are consumed by Output<T>'s generated by core pulumi `1.4.0` used by `@pulumi/eks`. If the Output<T>'s aren't designed to be cross-version compatible, this will result with problems.

**Comment by spion** [comment]
Seems like #1017 is a related issue

**Comment by pgavlin** [comment]
> This means that Output's produced by 1.3.0 from @pulumi/aws are consumed by Output's generated by core pulumi 1.4.0 used by @pulumi/eks. If the Output's aren't designed to be cross-version compatible, this will result with problems.

In general, `Output` is intended to be both forwards- and backwards-compatible. The behavior you were seeing might have been due to problems with `Output` that were introduced with `@pulumi/pulumi` v1.3.0 and [fixed with `@pulumi/pulumi` v1.3.1](https://github.com/pulumi/pulumi/pull/3324). These problems caused `apply` callbacks to be run on data that was only partially known.

I am going to close this for now under the assumption that this problem is 1.3.0-specific. If it crops up again, please go ahead and reopen this issue.

**Comment by spion** [comment]
Correct the actual versions in question were 1.3.0 and 1.3.1.

Good to know that Output is meant to be compatible. Thanks!
