### ISSUE TITLE
Hacktoberfest 2019 - Pulumi 

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3345]
To celebrate [Hacktoberfest](https://hacktoberfest.digitalocean.com/), we want to encourage anyone interested in contributing to the Pulumi open source projects to jump in and submit a PR, review a PR or add repros and/or additional insights to existing open issues.  

Any and all contributions are warmly welcomed! :tada:

If you are looking for suggestions for first issues to contribute on - the list of ["Help Wanted" issues](https://github.com/issues?utf8=✓&q=org%3Apulumi+label%3A"help+wanted"+) is a good place to start.  These issues are things that folks new to contributing to the Pulumi project can likely pick up and work on.  If you are interested in contributing to one of these and are just looking for pointers on where to get started - leave a note on the issue and someone from the Pulumi project will help out.

Contributions to the Pulumi documentation are also very welcome, and can be a great place to get started contributing to the project.  Check out the [open issues in the docs site](https://github.com/pulumi/docs/issues) for some ideas - or just click "edit this page" on any page at https://www.pulumi.com/docs/ to contribute an improvement.

Members of the Pulumi project will be happy to engage on any issues, PRs or questions.   You can jump in directly on GitHub, or join us in the #contribute channel on the [Pulumi Community Slack](https://slack.pulumi.com/).

Links:
- "Help Wanted" issues: https://github.com/issues?utf8=✓&q=org%3Apulumi+label%3A"help+wanted"+
- Documentation issues: https://github.com/pulumi/docs/issues
- Contributing channel in the Pulumi Community Slack: https://pulumi-community.slack.com/messages/CB81H6DG9

**Comment by pgavlin** [comment]
Hacktoberfest has concluded :D
