### ISSUE TITLE
pulumi login to az backend asks for token

### ISSUE THREAD

**Issue by davidobrien1985** [pulumi/pulumi#3349]
```
pulumi version  
v1.3.1
```
OS: Ubuntu 19.10

```
pulumi login -c az://pulumistate
Manage your Pulumi stacks by logging in.
Run `pulumi login --help` for alternative login options.
Enter your access token:
```

This should not happen, right? 
I'd expect this to just use my environment's azure variables to go to Azure storage.

**Comment by mikhailshilkov** [comment]
@davidobrien1985 I believe the correct command is `pulumi login azblob://my-pulumi-state-bucket `

**Comment by davidobrien1985** [comment]
Not according to the documentation. Plus, that also ends up with the same message.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mikhailshilkov** [comment]
Okay, the docs are wrong then. Try this:

```
PS > pulumi logout 
PS > $env:AZURE_STORAGE_ACCOUNT="testsa"
PS > pulumi login azblob://state
Logged into DESKTOP as DESKTOP\user (azblob://state)
```

**Comment by davidobrien1985** [comment]
Yeah, it's correct here:
https://www.pulumi.com/docs/reference/cli/pulumi_login/

Wrong here: https://www.pulumi.com/docs/intro/concepts/state/#azure-blob-storage

Thanks @mikhailshilkov

**Comment by justinvp** [comment]
PR to fix the docs: https://github.com/pulumi/docs/pull/1854

**Comment by davidobrien1985** [comment]
@justinvp :D thanks, I was already working on that and would've pushed after getting my tea.

**Comment by justinvp** [comment]
@davidobrien1985, ah, sorry! Thanks for letting us know about the issue!

**Comment by joeduffy** [comment]
@justinvp Should we be issuing an error for any unrecognized protocols (like `az://`)?

**Comment by justinvp** [comment]
> Should we be issuing an error for any unrecognized protocols (like `az://`)?

Good idea. And in the case of `az://` it'd be worth mentioning `azblob://` (or just allowing `az://`).

Opened #3382
