### ISSUE TITLE
Breakdown of perf cost in building/testing this repo.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#3355]
WIP.  still collecting this info

Insignificant times dropped.

1. Travis install step (2.5 minutes). https://github.com/pulumi/pulumi/blob/d72872c49a5310160444833fff62895366f78b7e/.travis.yml#L24-L25

3. Installing go deps: 141s

3. Travis make step (25m total)
    1. Nodejs sdk
        1. ensure: 50s
        2. ts build: 20s
        3. go build: 60s
        4. go lint: 21s
        4. test: 72s
    2. Python sdk
        1. ensure: 40s
        2. tests: 40.789s
    3. sdk
        1. build 60s
        2. lint 60s
    4. publish tgz: 60s
    1. github.com/pulumi/pulumi/cmd tests: 100s
    2. github.com/pulumi/pulumi/pkg/engine tests: 50s
    3. github.com/pulumi/pulumi/examples tests: 315s
    4. github.com/pulumi/pulumi/tests tests: 315s.

**Comment by stack72** [comment]
Closing this out as this has now moved to GitHub Actions
