### ISSUE TITLE
"Algorithm is required" when initializing stack with Azure Key Vault encryption provider

### ISSUE THREAD

**Issue by devblackops** [pulumi/pulumi#3359]
Initializing a new stack using Azure Key Vault as the encryption provider results in an error:
```
pulumi stack init my-stack --secrets-provider="azurekeyvault://<my-key-vault>.vault.azure.net/keys/<my-key>"

error: open keeper azurekeyvault://<my-key-vault>.vault.azure.net/keys/<my-key>: algorithm is required
```

The [docs](https://www.pulumi.com/docs/intro/concepts/config/#azure-key-vault) make no mention of how to provide the algorithm.

**Comment by davidobrien1985** [comment]
@devblackops I think the documentation is wrong here.
`pulumi new --secrets-provider="azurekeyvault://<vault>.vault.azure.net/keys/<key>?algorithm=RSA-OAEP-4096"`
if algorithm RSA4096 was used.

This worked for me.

**Comment by davidobrien1985** [comment]
Actually, it also failed, but with a different error:

```
Sorry, could not create stack 'azkv': secrets (code=Unknown): azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://pulumienc.vault.azure.net.vault.azure.net/keys/keys/pulumiencryption/encrypt?api-version=7.0: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Get http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F: dial tcp 169.254.169.254:80: connect: no route to host'
```

and yes, I ran `az login` before this.

**Comment by devblackops** [comment]
Yep. I see the same error. `169.254.169.254` is the Azure Instance Metadata service which is would be used to acquire a token for a managed identity.

https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token

That API endpoint is only valid from within an Azure VM / container. That obviously won't work when when running pulumi locally or if already authenticated via `az cli` or using environment variables.

**Comment by davidobrien1985** [comment]
Yep, I assume there's some spaghetti in the code. I'll take a look later on.

**Comment by devblackops** [comment]
The docs state that the URL should be something like `azurekeyvault://acmecorpvault.vault.azure.net/keys/payroll` but the code is adding  `vault.azure.net` and `keys` by itself.

It ends up trying to hit `https://acmecorpvault.vault.azure.net.vault.azure.net/keys/keys/payroll/encrypt?api-version=7.0`

I guess what it expects it to be is `azurekeyvault://acmecorpvault/payroll`.

To get around `169.254.169.254` I'm now running this test in Cloud Shell but I run into another auth error.

```
error: secrets (code=PermissionDenied): keyvault.BaseClient#Encrypt: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="Unauthorized" Message="AKV10022: Invalid audience. Expected https://vault.azure.net, found: https://management.core.windows.net/."
```

**Comment by mikhailshilkov** [comment]
@devblackops Try setting the `AZURE_AD_RESOURCE` env variable to `https://vault.azure.net`.

The CLI authentication, URL schema, and the default audience were all fixed in a newer version of the `go-cloud` library. I'll open a PR to update.
