### ISSUE TITLE
Pulumi is stuck in "running mode" with aws.<<Method Here>>

### ISSUE THREAD

**Issue by abdsahin** [pulumi/pulumi#3363]
Hi Everyone,

I use Terraform a lot but wanted to try out Pulumi. I have a problem with getting the default region value. According to the document, I do the following

``` javascript
var pulumi = require("@pulumi/pulumi");
var aws = require("@pulumi/aws");

var config = new pulumi.Config();
console.log("starting");
var currentRegion = aws.getRegion()
console.log(currentRegion);
console.log("passed");
```

When I run `pulumi up`, the screen stays like that
```
Previewing update (<<My Stack Name Here>>):

     Type                 Name                      Plan        Info
     pulumi:pulumi:Stack  <<My Project Name Here>>  running.    starting
```

It stays like that for hours(if I let probably). When I remove the line `aws.getRegion()`, then it works(of course I need to give the region to my resources in another way).

Anything that I am doing wrong? I am using 
pulumi version v1.3.1 
macbook : 
- System Version: macOS 10.14.6 (18G103)
- Kernel Version: Darwin 18.7.0

**Comment by lukehoban** [comment]
This is due to https://github.com/pulumi/pulumi/issues/3309. If you move to Node <= 12.10.0 (or Node 10) things should work. 

That issue was closed yesterday, and the fixes should be fully rolled out today.
