### ISSUE TITLE
`up --target` warns about other resources during preview but `up` fails

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#3369]
When using `up --target ...` to target a resource that has dependencies, the `preview` output warns about other resources being created, but then when the `up` executes Pulumi exits with an error about the dependencies and won't continue.

`destroy --target ...` works as expected.

Pulumi `v1.3.1`

#### Steps to Reproduce `up` behavior

Note: this targets the Subnet, to see the VPC created as well.

1. With the code below execute `pulumi up -t 'urn:pulumi:dev::demo-aws-ts-webserver::aws:ec2/subnet:Subnet::main'` and proceed with the `up`.

#### Steps to Reproduce `destroy` behavior

Note: this targets the VPC, to see the Subnet destroyed as well.

1. `pulumi up -y`
1. `pulumi destroy -t 'urn:pulumi:dev::demo-aws-ts-webserver::aws:ec2/vpc:Vpc::main'`

#### Code
```
import * as aws from "@pulumi/aws";

const vpc = new aws.ec2.Vpc("main", {
    cidrBlock: "10.0.0.0/16"
});

const subnet = new aws.ec2.Subnet("main", {
    vpcId: vpc.id,
    cidrBlock: "10.0.0.0/24",
});
```

#### `up -t ...` Output
```
% pulumi up -t 'urn:pulumi:dev::demo-aws-ts-webserver::aws:ec2/subnet:Subnet::main'
Previewing update (dev):

     Type                     Name                       Plan       Info
 +   pulumi:pulumi:Stack      demo-aws-ts-webserver-dev  create     1 warning
     ├─ pulumi:providers:aws  default_1_7_0                         1 warning
 +   ├─ aws:ec2:Vpc           main                       create     1 warning
 +   └─ aws:ec2:Subnet        main                       create

Diagnostics:
  aws:ec2:Vpc (main):
    warning: Resource 'urn:pulumi:dev::demo-aws-ts-webserver::aws:ec2/vpc:Vpc::main' is being created but was not specified in -target list.

  pulumi:pulumi:Stack (demo-aws-ts-webserver-dev):
    warning: Resource 'urn:pulumi:dev::demo-aws-ts-webserver::pulumi:pulumi:Stack::demo-aws-ts-webserver-dev' is being created but was not specified in -target list.

  pulumi:providers:aws (default_1_7_0):
    warning: Resource 'urn:pulumi:dev::demo-aws-ts-webserver::pulumi:providers:aws::default_1_7_0' is being created but was not specified in -target list.

Resources:
    + 3 to create

Do you want to perform this update? yes
Updating (dev):

     Type                 Name                       Status         Info
     pulumi:pulumi:Stack  demo-aws-ts-webserver-dev  **failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (demo-aws-ts-webserver-dev):
    error: Resource 'urn:pulumi:dev::demo-aws-ts-webserver::pulumi:pulumi:Stack::demo-aws-ts-webserver-dev' is being created but was not specified in -target list.

Permalink: https://app.pulumi.com/clstokes/demo-aws-ts-webserver/dev/updates/290
%
```

#### `destroy -t ...` Output
```
% pulumi destroy -t 'urn:pulumi:dev::demo-aws-ts-webserver::aws:ec2/vpc:Vpc::main'
Previewing destroy (dev):

     Type                 Name                       Plan
     pulumi:pulumi:Stack  demo-aws-ts-webserver-dev
 -   ├─ aws:ec2:Subnet    main                       delete
 -   └─ aws:ec2:Vpc       main                       delete

Resources:
    - 2 to delete

Do you want to perform this destroy? yes
Destroying (dev):

     Type                 Name                       Status
     pulumi:pulumi:Stack  demo-aws-ts-webserver-dev
 -   ├─ aws:ec2:Subnet    main                       deleted
 -   └─ aws:ec2:Vpc       main                       deleted

Resources:
    - 2 deleted

Duration: 4s

Permalink: https://app.pulumi.com/clstokes/demo-aws-ts-webserver/dev/updates/292
%
```

**Comment by clstokes** [comment]
Additionally, the output is inconsistent from `up -t ...` and `destroy -t ...`.

As shown in the output above `up -t ...` prints a warning for each resource that will also be updated and `destroy -t ...` does not. The warning messages should be omitted from `up -t ...` IMO.

**Comment by CyrusNajmabadi** [comment]
> Note: this targets the VPC, to see the Subnet destroyed as well.

Note: this is expected, and is how we doc'ed the feature (albeit not necessarily super clearly)when we released it: 

> - `pulumi destroy` can now be scoped to delete a single resource (and its dependents)

That said, I agree we should likely warn if it will end up deleting resources you didn't ask to delete.

**Comment by CyrusNajmabadi** [comment]
Note: the 'up' behavior is behaving as we originally designed it (though i think we could be better here).  Specifically, we wanted to not error immediately if we encounter a downstream update to a resource that was not specified.  That way you would hear about all of them and not have to keep rerunning to hear about a new unspecified resource each time. 

--

That said, the inconsistency and lack of clarity here isn't great.  I think we should do the following:

1. When running an update, we should report all the resources that would need to update that you didn't specify in your --target list.  And then we should fail the preview after all of them have been reported.

2. When running a destroy we should do the same.  Report all the resources to destroy that weren't mentioned and force hte user to specify them.

This should then be consistent between the two and follow the principle of "you must always specify all the items that are going to chnage if you use --target".

Thoughts @pgavlin @lukehoban ?

**Comment by clstokes** [comment]
> 1. When running an update, we should report all the resources that would need to update that you didn't specify in your --target list.  And then we should fail the preview after all of them have been reported.

@CyrusNajmabadi, I think the behavior users want is for Pulumi to report all the resources that would need to be updated/destroyed and then proceed (or allow the user to proceed), not fail.

A targeted operation is a "power user" type operation and I expect users generally know what they're doing when they need to use `-t`. Forcing the user to specify every dependent resource to use `-t` isn't a good user-experience in my opinion.

**Comment by CyrusNajmabadi** [comment]
> Forcing the user to specify every dependent resource to use -t isn't a good user-experience in my opinion.

I'm not sure i agree with this.  I think it's important for this sort of power case to have to be explicit about what you're doing.  similar to how some tools require you to confirm you're doing what you want by explicitly retyping the name of things.

I can completley imagine someone not certain waht they're doing going and using `--target` and having things get much worse because we extended the set and they didn't understand the implications.

Here's what i propose:

1. `--target` must be specified by the user for any resources we are going to touch (including resources that are touched because of specific --target passed in).  
2. we report all resources that you didn't specify and then error out of the command afterwards.
3. the error says "either specify all targets, or pass -f to force the operation".
4. if you pass -f we *warn* about resources you didn't mention, but we go ahead and do all the updates anyways.

Benefits of this approach:

1. consistency between update/refresh/delete wrt `--target`s.
2. default safe behavior.  if you specify targets and we would need to touch something outside of that set, our default behavior is to be conservative and not proceed.
3. available consistent escape hatch for customers.  Customers can always get through this by specifying all the `--target`s manually.
4. easy, but dangerous, opt-in flag for the user with `-f`.  This allows a power user to just barrel on through with less pain, but forces them to be cognizant of what they are doing.

Thoughts @clstokes @lukehoban @pgavlin ?

**Comment by clstokes** [comment]
The `-f` flag seems like a great option to support both desires - the default safe behavior and the power user use case. :+1:
