### ISSUE TITLE
During `pulumi up` the stack file is read again after preview which can take in account new modifications

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi#3371]
When using pulumi, I often do `pulumi up`, then waiting for preview to be finished, I continue to update the script. When preview is finished, I confirm `update` and pulumi take in account my last modifications (which I don't want).

I agree that is not the standard flow, but during testing, it can be surprising.

Feel free to close this issue if it's too minor for you.

**Comment by clstokes** [comment]
@lukehoban do we want to close this in favor of https://github.com/pulumi/pulumi/issues/2318 or do we consider this different enough?

**Comment by pgavlin** [comment]
I think we can close this, yes.
