### ISSUE TITLE
.NET support - work items

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#3384]
Here's a list of work items for us to complete both for the immediate present, and to get .net support up to production quality.  This is mostly copied from https://github.com/pulumi/pulumi/wiki/New-Language-Bringup. 

Pri0:

- [x] Create a Pulumi SDK that is feature-parity with the @pulumi/pulumi SDK in https://github.com/pulumi/pulumi/tree/master/sdk.
    1. Assigned to @CyrusNajmabadi.  
    2. Delivery date: 10/23
    3. PR: https://github.com/pulumi/pulumi/pull/3399
- [x] Create a language host
    1. Assigned to @CyrusNajmabadi.  
    2. Delivery date: 10/23
    3. PR: https://github.com/pulumi/pulumi/pull/3399
- [x] Update CI to build/test SDK
    1. Assigned to @CyrusNajmabadi.  
    2. Delivery date: 10/24
    3. PR: https://github.com/pulumi/pulumi/pull/3399
- [x] Add tfgen support
    1. Assigned to @pgavlin 
    2. Delivery date: 10/28
    3.  PR: https://github.com/pulumi/pulumi-terraform-bridge/pull/56
- [x] Azure SDK generated for .NET
    1. Assigned to @pgavlin 
    2. Delivery date: 10/29
    3. PR: https://github.com/pulumi/pulumi-azure/pull/398
- [x] Package publishing automation for the language's package manager
    1. Assigned to @CyrusNajmabadi 
    2. Delivery date: 10/29
    3. PR: https://github.com/pulumi/pulumi/pull/3416
- [x] Add support to integration test harness
    1. Assigned to @mikhailshilkov 
    2. Delivery date: 10/25
- [x] Port integration tests at https://github.com/pulumi/pulumi/tree/master/tests/integration
    1. Assigned to @mikhailshilkov 
    2. Delivery date: 10/30
    3. Critical work is done here.
- [x] Enable publishing for all providers
    1. Assigned to @stack72 
    2. Delivery date: 10/31

Pri1:
- [ ] 10 Examples in https://github.com/pulumi/examples
    1. Assigned to @mikhailshilkov / @lukehoban 
    2. Delivery date: 10/31
    3. PR: https://github.com/pulumi/examples/pull/445
       3.1.  1/2 AWS
       3.2.  Update to point at real packages
- [x] Templates
    1. Assigned to @mikhailshilkov
    2. At least for Azure (10/30)
    3. PR: https://github.com/pulumi/templates/pull/69
      3.1 template for AWS/GCP
- [x] New Project wizard (https://github.com/pulumi/pulumi-service/issues/4308)
    1. Assigned to @justinvp
    2. Delivery date: 11/6
    3. PR: https://github.com/pulumi/pulumi-service/pull/4311
- [x] Azure AD provider, Random provider, AWS, GCP (bonus points for "everything")
   1. Assigned to @pgavlin 
   2. Delivery date: 10/31
- [x] Language Docs
   1. Language page (yes - 10/30) (https://github.com/pulumi/home/issues/592) (@spara)
   1. Lang-chooser on programming model page (yes - 10/30) (@CyrusNajmabadi )
   1. Getting Started (yes - 10/31) (@CyrusNajmabadi) 
   1. Reference docs (no)
   1. Lang chooser support for .NET/C# (yes - 10/31) (@justinvp)
- [x] 1.4.1 release
   1. Assigned to @pgavlin 
   2. Delivery date: 11/1
- [ ] Preview Launch
   1. Blog (Pulumi blog - 11/5)
   2. Video (Luke - 11/5)
   3. Blog (.NET blog -  TBD)
   4. Channel9 (.NET team -  TBD)

Pri2:
- [ ] Add Kubernetes codegen support (https://github.com/pulumi/pulumi-kubernetes/issues/863)
    1. Assigned to ??
    2. Delivery date: TBD
- [ ] Add support for the new language to tf2pulumi 
    1. Assigned to ??
    2. Delivery date: TBD
- [ ] Dynamic Providers
- [ ] StackReference

**Comment by CyrusNajmabadi** [comment]
@lukehoban  for our meeting tomorrow.

**Comment by stack72** [comment]
@CyrusNajmabadi ALL providers have PRs open now to add DotNet support and all builds are green.

**Comment by justinvp** [comment]
BTW, I added lang chooser support for .NET to https://github.com/pulumi/docs/pull/1914 yesterday.

**Comment by lukehoban** [comment]
Closing out - we'll track remaining work in https://github.com/pulumi/pulumi/issues/3470.
