### ISSUE TITLE
pulumi up using Python fails in Windows

### ISSUE THREAD

**Issue by VikingExplorer** [pulumi/pulumi#3398]
I'm going through the "getting started" guide. I selected AWS.  When I type "up", I get an error:

PS C:\Users\g> cd .\pulumi-qs\                                                                                     
PS C:\Users\g\pulumi-qs> pulumi up                                                                                 
Previewing update (dev):                                                                                               
     Type                 Name          Plan     Info                                                                       pulumi:pulumi:Stack  pfmProto-dev           1 error                                                                
on 3.6 or greater?                                                                                                    
Diagnostics:
  pulumi:pulumi:Stack (pfmProto-dev):
    error: Failed to locate 'python3' on your PATH. Have you installed Python 3.6 or greater?

PS C:\Users\g> python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32

PS C:\Users\g> python3
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 01:31:54) [MSC v.1916 64 bit (AMD64)]

**Comment by VikingExplorer** [comment]
![Capture](https://user-images.githubusercontent.com/15109208/67518267-6bfda380-f672-11e9-85de-42b2dad20a19.PNG)

**Comment by lukehoban** [comment]
I just tried this myself, and indeed when I installed Python3 on Windows, I did not get any `python3` binary installed by default.  So it does sounds like Pulumi needs to fall back to `python` binary if `python3` cannot be found.

You should be able to workaround this by copying `python.exe` to `python3.exe` in the `AppData\Local\Programs\Python\Python38` folder.

I am still a little confused about your comment above that `python3` does resolve on your path.  But I do also note that it reports Python 3.7.5, so it seems to be picking up something different than what you have in your environment.  Is it possible you have some other scripts that have put something on your path locally?

Either way - key action for Pulumi should be to ensure we can work in case there is no explicit `python3` binary installed.

**Comment by VikingExplorer** [comment]
Error:
PS C:\Users\gunna\pulumi-qs> pulumi up                                                                                 Previewing update (dev):                                                                                               
     Type                 Name          Plan     Info                                                                       pulumi:pulumi:Stack  pfmProto-dev           1 error; 6 messages                                                    
ode: 1txt from inside the virtualenv.ule>                                                                             
Diagnostics:
  pulumi:pulumi:Stack (pfmProto-dev):
    Traceback (most recent call last):
      File "C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin\pulumi-language-python-exec", line 14, in <module>           import pulumi
    ModuleNotFoundError: No module named 'pulumi'
    It looks like the Pulumi SDK has not been installed. Have you run pip install?
    If you are running in a virtualenv, you must run pip install -r requirements.txt from inside the virtualenv.       

I followed the "Getting Started" guide carefully.

I need to try this again.  Is there a clear procedure for Windows?

**Comment by VikingExplorer** [comment]
I'm going through it carefully. The instructions are vague on the platform. For example, Homebrew was previously mentioned w/o regard to other platforms.  

@lukehoban what is the Windows PS equivalent to the instructions at https://www.pulumi.com/docs/get-started/aws/review-project/ ?

**Comment by VikingExplorer** [comment]
Here is what I've done so far: https://www.evernote.com/l/ACyp0cmXpSBLQb4zj9wnSg-YF0nXdbecaBc/

**Comment by VikingExplorer** [comment]
Was anyone able to reproduce this problem?

**Comment by lukehoban** [comment]
I am going to keep this issue to track the initial issue that was reported - which I believe is fundamentally the one from my comment above:

> Either way - key action for Pulumi should be to ensure we can work in case there is no explicit `python3` binary installed.

We will need to fall back to `python` - since the former is not available in a standard Windows install.

@VikingExplorer I don't quite follow the other issues you've noted on this thread.   We've opened https://github.com/pulumi/docs/issues/1921 to track improving the getting started docs for Windows - if you could add notes there with any more details on which steps still fail for you - that would be very helpful.

**Comment by stgaup** [comment]
I have the same problem on my machine. I have added python to the path, and still getting the same error:

Previewing update (dev):

     Type                 Name              Plan     Info
     pulumi:pulumi:Stack  PulumiPython-dev           1 error

Diagnostics:
  pulumi:pulumi:Stack (PulumiPython-dev):
    error: Failed to locate 'python3' on your PATH. Have you installed Python 3.6 or greater?

I have installed Python 3.7 in this directory:
C:\Users\svegau\AppData\Local\Programs\Python\Python37

Typing "python" or "python3" in the console does nothing. However typing "py" seems to work. I also tried the workaround copying the python.exe file til python3.exe.

**Comment by scheung38** [comment]
Yes I am also seeing the same pulumi up: error: Failed to locate python3 on your PATH.

This is just after using python 3.7 to create the virtualenv? Is this fixed as I cannot do pulumi up...

**Comment by lukehoban** [comment]
This more or less completely blocks Windows+Python usage of Pulumi (without an ugly workaround described in https://github.com/pulumi/pulumi/issues/3398#issuecomment-546138407) - so adding P1 and pulling forward.

**Comment by pascostefan** [comment]
C'mon guys, this isn't fixed, is it?

**Comment by dstine** [comment]
Thanks for the fix, @lukehoban.

Just confirming for any readers that the workaround noted above (copy `python.exe` to `python3.exe`) also works within a virtual environment (`[VENV]/Scripts`). You are not required to modify the "core" system installation of Python 3.

My environment:
* Windows 7
* Python 3.6.8
* Git Bash for Windows 2.12.2.2
