### ISSUE TITLE
failed to compute asset hash: asset path '...' is a directory; try using an archive

### ISSUE THREAD

**Issue by igorshapiro** [pulumi/pulumi#3405]
Trying to create a lambda for handling S3 object creation:

```ts
transcriptionJobs.bucket.onObjectCreated('publish', async ev => {
  const s3Client = new aws.sdk.S3()
  const kinesisCliet = new aws.sdk.Kinesis()
  for (const { s3: { bucket, object } } of ev.Records || []) {
    console.log({ bucket, object })
  }
})
```
and getting an error:

```
    Error: failed to register new resource publish [aws:lambda/function:Function]: 2 UNKNOWN: failed to compute asset hash: asset path 'node_modules/@lemonade/infra-common' is a directory; try using an archive
```

**Comment by CyrusNajmabadi** [comment]
@igorshapiro do you know what `@lemonade` is?

**Comment by BrunoRoque06** [comment]
Is `@lemonade/infra-common` a local package? I get this when the lambda uses a library that is "symlinked" under `node_modules` (like `yarn link ...` or `lerna add ...` do).

**Comment by jen20** [comment]
I believe this is a dupe of #2980, and the issue is constructing hashes through symbolic links.

**Comment by lukehoban** [comment]
Closing as dupe of https://github.com/pulumi/pulumi/issues/2980.
