### ISSUE TITLE
.NET build output break table layout in terminal

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#3413]
The ephemeral log messages from `dotnet build` sometimes look funky in the CLI output in Windows Terminal. They wrap over the next line and then somehow break the table:

![image](https://user-images.githubusercontent.com/1454008/67718350-e0687780-f9cf-11e9-9b5d-50eed2788d24.png)

I'm on Windows Terminal latest, but @lukehoban mentioned he saw glitches on Mac too.

**Comment by justinvp** [comment]
Dupe of #3374? cc: @pgavlin

**Comment by pgavlin** [comment]
I believe so, yes.
