### ISSUE TITLE
Add backend URL to the stack config

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi#3415]
Switching between backends has become a common thing now, and as such I forget which backend URL I used to init a stack. I end up running `pulumi login ...` and `pulumi logout` until I find the correct backend I used originally. Instead, it would be nice to know which backend was used when a stack was initialized and have this information in the stack config file (Pulumi.<stack_name>.yaml).

**Comment by clstokes** [comment]
Related to https://github.com/pulumi/pulumi/issues/2996.

**Comment by lukehoban** [comment]
> Related to #2996.

Ahh - indeed - that issue looks like it's currently more or less tracking the exact same thing - though the title doesn't quite match what it's now tracking.  I'll close this one as a dupe and re-title that one.
