### ISSUE TITLE
`pulumi up` in non-interactive terminal auto-approves changes

### ISSUE THREAD

**Issue by theneva** [pulumi/pulumi#3435]
Hi! :wave:

I'm testing out Pulumi by importing an existing GCP infrastructure, and hit some unexpected-to-me behaviour.

When running `pulumi up` (which we use to check things instead of `pulumi preview` because of the `details` option), there's a nice prompt with `no` as the default selection.

If Pulumi detects that it is in a non-interactive terminal, it auto-approves changes. This is explicit behaviour: https://github.com/pulumi/pulumi/blob/6900ff5bc5167e44fe8f3333f74b08c2d2354196/cmd/up.go#L330-L334

This was unexpected to me for several reasons:

First, the presence of a `--yes` flag indicates to me that the default is to reject any changes by default.

Second, this behaviour differs from other tools that prompt for confirmation before performing an action, such as `apt-get` (whose default selection is to approve changes, but still hangs if not passed `-y`).

Edit: This behaviour also does not match Terraform, which (like `apt-get`) tries to prompt anyway when its output is piped.

Finally, the terminal is detected as non-interactive if the output from `pulumi up` is piped to another program. In my case, I tried running `pulumi up` with a high verbosity and piping the output to `less` with `pulumi up -v 5 | less`. That killed our development cluster because the input didn't match what we tried to import :smile:

I think it makes sense to hang and/or default to rejecting any potentially destructive changes if the terminal is not interactive, and instead print a helpful message pointing to the `--yes` flag.

**Comment by pgavlin** [comment]
This is certainly worth some consideration. @CyrusNajmabadi @justinvp @lukehoban what do y'all think?

**Comment by theneva** [comment]
This is on the verge of being a dealbreaker for us :confused: an update would be great!

**Comment by SimenB** [comment]
Pulumi v2 seems like a great opportunity the change this, fwiw

**Comment by chrsmith** [comment]
Thanks for the report @theneva , all of the reasons you mention seem pretty convincing that the current behavior isn't quite right. And while it's a little more convenient for, say, using Pulumi in CI/CD to default to `--yes`, failing to properly work on the `pulumi up -v 5 | less` scenario is "not great".

So unless someone else can find a reason why it's important we keep this current behavior, I'd totally be onboard with making the breaking change in the v2.0 timeframe. ("soonish") We'd just need to be careful about rolling this out / messaging it, as it would break existing CI/CD pipelines that are dependent on the current default-to-`--yes` behavior.

**Comment by CyrusNajmabadi** [comment]
> This is certainly worth some consideration. @CyrusNajmabadi @justinvp @lukehoban what do y'all think?

I would have no problem with this.  Even though this was an explicit intentional decision at the time, the negatives outweigh the positives for me.  Requiring an explicit `--yes` on the command-line is non-onerous and would certainly be greatly appreciated by anyone who has ever run into this sort of thing.

**Comment by CyrusNajmabadi** [comment]
Working on a fix now.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi/pull/3793
