### ISSUE TITLE
.NET provider plugins not installed automatically

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#3438]
`pulumi new gcp-csharp` + `pulumi up` won't install the alpha provider plugin automatically. I have to run e.g. `pulumi plugin install resource gcp v1.5.0-alpha.1572481793+gc085ce6` manually (`up` gives a hint).
I haven't found a way to do so on NuGet restore yet to do what we do with `npm install`. Maybe `up` command should just install the plugin instead of suggesting doing so manually.

**Comment by mikhailshilkov** [comment]
`pulumi up` doesn't install all required resource plugins automatically. It only installs resource plugins that are used in the current snapshot - see `gatherPluginsFromSnapshot`
Also, we don't auto-install language plugins, despite `engine.installPlugins` saying so.

**Comment by lukehoban** [comment]
The intended design is that the package install step should take care of this (`NPM install`, etc.). Do we know if Nuget offers any way to script this into the restore set?

**Comment by mikhailshilkov** [comment]
I'm reading a no here:

> By design packages cannot participate during/before restore with their own custom build targets. 
> The reason for that is when restore runs those targets are imported into the project yet.

> You can do a lot in a package build targets file by hooking to the some of the prebuild targets (rather than restore), but it's not a good practice to download things in those targets as that can degrade the performance.
