### ISSUE TITLE
brew throws error on some MacOS versions

### ISSUE THREAD

**Issue by prasannapad** [pulumi/pulumi#3439]
To install setup pulumi build, I ran:

`brew install node pipenv python@3 typescript yarn go golangci/tap/golangci-lint`

but kept getting the error: Error: /usr/local is not writable.

To fix this, re-install brew as suggested here:

https://github.com/Homebrew/brew/issues/3285#issuecomment-334976806

Maybe worth mentioning in CONTRIBUTING.md

**Comment by lukehoban** [comment]
This sounds like it’s a bug in brew itself - right?  (And possibly that some old version of brew doesn’t work well on newer macOS?).

I don’t see anything obvious we would change in Pulumi here?

**Comment by prasannapad** [comment]
That's correct, it's likely a bug in brew, nothing needed in Pulumi itself.

**Comment by justinvp** [comment]
Closing since this is a brew issue and nothing to fix in Pulumi itself.
