### ISSUE TITLE
make fails with "Subprocess launched with function call as argument or cmd arguments (gosec)" error

### ISSUE THREAD

**Issue by prasannapad** [pulumi/pulumi#3440]
running `make` fails with the following error.. 

 "Subprocess launched with function call as argument or cmd arguments (gosec)" error

LINT:
golangci-lint run
cmd/pulumi-language-nodejs/main.go:488: G**204: Subprocess launched with function call as argument or cmd arguments (gosec)**
		cmd := exec.Command(host.nodeBin, args...)
make[1]: *** [lint] Error 1
make: *** [sdk/nodejs_all] Error 2

**Comment by pgavlin** [comment]
Which version of `golangci-lint` do you have installed?

**Comment by prasannapad** [comment]
`1.20.1`

**Comment by prasannapad** [comment]
Thanks @pgavlin this fixed the issue, I am able to move past this  ( but running into another issue which I will log).
