### ISSUE TITLE
.NET SDK sample folder is missing

### ISSUE THREAD

**Issue by SeanFeldman** [pulumi/pulumi#3442]
https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/README.md is referring to `sdk/dotnet/examples` directory, but it's missing.

**Comment by mikhailshilkov** [comment]
Yes, they are being moved to https://github.com/pulumi/examples, see https://github.com/pulumi/examples/pull/445
I'll update the README when the PR is merged.

**Comment by mikhailshilkov** [comment]
Fixed in-place
