### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by yoeldovidcohen** [pulumi/pulumi#3467]
Pulumi Version:   v1.4.1
Go Version:       go1.12.9
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            fatal: An assertion has failed: type was empty

goroutine 1 [running]:
runtime/debug.Stack(0xc0002a2c08, 0x13f2700, 0xc000efab30)
        /home/travis/.gimme/versions/go1.12.9.linux.amd64/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
        /home/travis/gopath/src/github.com/pulumi/pulumi/main.go:30 +0x6e
panic(0x13f2700, 0xc000efab30)
        /home/travis/.gimme/versions/go1.12.9.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assertf(0x0, 0x16cd80d, 0xe, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:33 +0x198
github.com/pulumi/pulumi/pkg/resource.NewState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000ef70b0, 0xc000ef70e0, 0x0, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/resource_state.go:54 +0x58
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeResource(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:400 +0x296
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeOperation(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:407 +0x83
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeDeploymentV3(0x14abdbd7, 0xed55634ef, 0x0, 0xc00024c340, 0x40, 0xc000230c68, 0x6, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:232 +0x59f
github.com/pulumi/pulumi/pkg/resource/stack.DeserializeUntypedDeployment(0xc00022c1e0, 0x199f1a0, 0x29b33a0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/stack/deployment.go:169 +0x186
github.com/pulumi/pulumi/cmd.newStackImportCmd.func1(0xc000117900, 0x29b3938, 0x0, 0x0, 0x11, 0x11)
        /home/travis/gopath/src/github.com/pulumi/pulumi/cmd/stack_import.go:78 +0x232
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc000117900, 0x29b3938, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:96 +0x51
github.com/pulumi/pulumi/pkg/util/cmdutil.RunResultFunc.func1(0xc000117900, 0x29b3938, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:112 +0x6b
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).execute(0xc000117900, 0x29b3938, 0x0, 0x0, 0xc000117900, 0x29b3938)
        /home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000dd680, 0x17482a8, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/pulumi/pulumi/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/vendor/github.com/spf13/cobra/command.go:800
main.main()
        /home/travis/gopath/src/github.com/pulumi/pulumi/main.go:49 +0x4c

**Comment by pgavlin** [comment]
Thanks for the report!

It looks like something in the state file you were attempting to import is corrupt. If you can email me a copy of the state file, I can take a look and see what might be amiss.

**Comment by mikhailshilkov** [comment]
There is no repro in this issue and it has been inactive for 2+ years. I'll go ahead and close it.
