### ISSUE TITLE
Duplicated text and rendering which breaks single line display with new .NET project

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3469]
On first `pulumi up` after `pulumi new azure-csharp` I see some awkward rendering during the update, with the display ending up with the duplication and multi-line rendering below.  This was on Windows.

FWIW - first time this process takes quite awhile - and there is not clear status on the screen during the period of time that is "slow".  After slow operations complete I temporarily see things like "Restoring took 20s" - but I don't see anything indicating that I am waiting on restore.  Then the plugin download information gets displayed out of place with the rest of the rendering.

<img width="590" alt="rendering" src="https://user-images.githubusercontent.com/223467/68429712-7a17ed80-0163-11ea-8c7a-27081948fb21.PNG">

**Comment by clstokes** [comment]
Seems related to https://github.com/pulumi/pulumi/issues/3374 ?

**Comment by joeduffy** [comment]
Fwiw, I am seeing effectively the same symptoms described in #3374, in 1.5.1. Are we sure that was fixed? E.g. this is on a Mac:

![image](https://user-images.githubusercontent.com/3953235/68490513-f52de200-01fd-11ea-8bf5-c43deb2b25d8.png)

**Comment by lukehoban** [comment]
I do not believe the issues reported in #3374 are the same as the issue everyone is seeing here. I believe there is a bug unique to dotnet that this issue is tracking.

**Comment by lukehoban** [comment]
Investigating this - it appears to repro if there are any calls to `engineClient.Log` from the language host.  Even logging an empty string triggers this.  The `dotnet` language host is the only one that current logs.

**Comment by pgavlin** [comment]
Is this still an issue?

**Comment by lukehoban** [comment]
> Is this still an issue?

Yes.

**Comment by lukehoban** [comment]
> Investigating this - it appears to repro if there are any calls to engineClient.Log from the language host. Even logging an empty string triggers this. The dotnet language host is the only one that current logs.

I've noticed this over the last few days even outside of using .NET when adding temporary diagnostic logging code to a language implementation.

**Comment by lukehoban** [comment]
Here's another example of this when we print a warning about incompatible versions of a resource provider:

```
Previewing update (dev):
     Type                 Name     Plan     Info
     pulumi:pulumi:Stack  564-dev           warning: resource plugin aws is expected to have version >=1.18.0, but has 1.18.0-alpha.157

     Type                 Name       Plan       Info
     pulumi:pulumi:Stack  564-dev               2 warnings
 ~   └─ aws:s3:Bucket     my-bucket  update     [diff: ~tags]
```

**Comment by joeduffy** [comment]
This still seems to be an issue, and happens with every .NET project I've created. Marking as part of the 2.0 release since this should be part of making sure .NET is ready for prime time.

E.g.

![image](https://user-images.githubusercontent.com/3953235/73125142-50978280-3f58-11ea-98fd-5f99ec7080fa.png)
