### ISSUE TITLE
Go: add helpers for defining `ComponentResource`s

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#3488]
Currently, the Go SDK only defines the interface for a `ComponentResource`; the implementation is left entirely up to the user. We should add simple helpers for defining these resources.

**Comment by lukehoban** [comment]
This does not appear to be part of https://github.com/pulumi/pulumi/pull/3506 currently - not precisely sure what this is tracking or whether it is critical.  @pgavlin could you add more details?
