### ISSUE TITLE
Go: support `transformations`

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#3490]
Support this API in the Go SDK.

**Comment by ekrengel** [comment]
Sorry for the back and forth on this one! Wanted to make sure it was something that could be done in M32 before assigning it to @tasiah

**Comment by tasiah** [comment]
I'm not very familiar with Go transformations. Just to make sure I'm working on the right thing, is this the API you're referring to: https://godoc.org/golang.org/x/text/transform? A super simple example of what we would want to do with this API would also be hugely appreciated.

**Comment by ekrengel** [comment]
I believe this is a Pulumi concept not a go concept. You should set up some time with @EvanBoyle  or @pgavlin to explain more!

**Comment by tasiah** [comment]
I'm glad I asked then! For reference: https://www.pulumi.com/docs/intro/concepts/programming-model/#transformations. There's examples for how other languages use it too, so that helps a lot. I'll reach out again when I inevitably need more help, thanks!

**Comment by EvanBoyle** [comment]
@tasiah Here's a reference PR for transformations in python: https://github.com/pulumi/pulumi/pull/3319

**Comment by lukehoban** [comment]
> Here's a reference PR for transformations in python: #3319

In case it helps - the actual "logic" of this feature is just the 20 lines here: 

https://github.com/pulumi/pulumi/pull/3319/files#diff-e40a55916cf826f23928c81468e845cdR613-R634

The rest of that PR is the data structures needed to enable that (and lots of test coverage).
