### ISSUE TITLE
Go: reimplement `Output` more robustly, consider changing its interface

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#3492]
- Outputs will currently panic or hang if they are resolved or rejected more than once, depending on whether or not their value has ever been awaited.
- The value of an output is publicly available, unlike in other SDKs
- Output should _probably_ be an `interface`, perhaps with an internal-only implementation
- Apply callbacks could be more ergonomic, e.g. through the use of reflection to allow strongly-typed, dynamically-checked arguments

**Comment by lukehoban** [comment]
Part of https://github.com/pulumi/pulumi/pull/3506?
