### ISSUE TITLE
Can't ^C a .NET program

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3500]
Is there something wrong with the ^C implementation for .NET Core?

```
$ pulumi preview
Previewing update (dev):
     Type                 Name         Plan     Info
     pulumi:pulumi:Stack  dotplay-dev           Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core

System Messages
  ^C received; cancelling. If you would like to terminate immediately, press ^C again.
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
  ^C received; terminating
```

**Comment by CyrusNajmabadi** [comment]
@pgavlin how is cancellation supposed to work?  is it through the context instance we receive?  If so, is there a general way to cancel 3rd party apps we've spawned?  Should we just kick them off on a goroutine and then just wait on either the goroutine/ctx signaling completion?

**Comment by EvanBoyle** [comment]
Closing as this no longer repros on pulumi v3.7.1
