### ISSUE TITLE
 panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [pulumi/pulumi#3508]
I am getting "panic: interface conversion: interface {} is nil, not map[string]interface {}" error while doing pulumi up, If i retry to deploy and works fine

Trying to deploy Azure app services (linux containers), using azure devops plugin. deployment agent 2016 windows server

here is the log link
https://github.com/rajeshmuraleedharan/testing/blob/master/transpor-is-closing.txt

**Comment by EvanBoyle** [comment]
@rajeshmuraleedharan can you share your code?

**Comment by rajeshmuraleedharan** [comment]
I can but is there any way to securely share the code ?

**Comment by rajeshmuraleedharan** [comment]
@EvanBoyle 
I have created a private git hub repo and invited you as collaborator. Please check

**Comment by rajeshmuraleedharan** [comment]
@EvanBoyle 
Also uploaded a azure devops release log zip file, where you can see multiple attempts for DEV & QA regions (first two attempt failed, third one worked)

![image](https://user-images.githubusercontent.com/16232384/68887942-91188b80-06df-11ea-87aa-686b4fb9e62e.png)

![image](https://user-images.githubusercontent.com/16232384/68887821-4dbe1d00-06df-11ea-9dab-e5f34d6fe3d7.png)

**Comment by rajeshmuraleedharan** [comment]
@EvanBoyle please let me know if you need more details

**Comment by pgavlin** [comment]
This sounds like the same issue as https://github.com/pulumi/pulumi-azure/issues/383.

**Comment by mikhailshilkov** [comment]
I think this issue was solved long time ago, so I'll go ahead and close it
