### ISSUE TITLE
Dotnet: adopt consistent approach for running programs across compiled languages

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#3509]
For the go SDK we look for an executable with the same name as the program before running it via 'go run' on behalf of the user. The behavior is as follows:

1. Look for an executable:
a. in `$CWD`
b. in `$GOPATH/bin`
c. somewhere on the `$PATH`
2. Fallback to executing via `go run`

We should adopt similar behavior in dotnet for consistency amongst our compiled languages.

See https://github.com/pulumi/pulumi/pull/3503 for go implementation.

**Comment by lukehoban** [comment]
@mikhailshilkov @CyrusNajmabadi @pgavlin Curious your thoughts on this?  This approach feels like it's somewhat less natural in .NET, but I can see it still working there, and I don't have any specifically better suggestions.  This may also be related to whether we switch from a "run an exe" to "load a plugin" style approach for .NET.

**Comment by mikhailshilkov** [comment]
This would potentially address
> Enable running pulumi up on precompiled binaries in case people want to split the compilation from execution

from #3470 

We could do this *in addition* to the current method. And yes, we should fit this into the stories of "load a plugin" and "run a script" (csx, fsx, Ps).

**Comment by mikhailshilkov** [comment]
It feels like this issue is important for CI/CD scenarios when people want to separate the build step from the run step.

**Comment by mikhailshilkov** [comment]
We need to implement the option from #4338 in .NET
