### ISSUE TITLE
Skip dep install on `pulumi new` (prefer yarn)

### ISSUE THREAD

**Issue by brandonkal** [pulumi/pulumi#3520]
I prefer yarn with pnp for managing dependencies for TS/JS. Having the option to skip the auto-install of JS dependencies or use yarn would be nice.

When I ran `pulumi new` @types/node@8` was installed and I would prefer the option to change that to version 12 before the installation of dependencies occurs.

**Comment by lukehoban** [comment]
There is the following flag to `pulumi new` that allows skipping this step so you can customize dependency installation. 

I’m not sure we would change the default here as a key goal of `pulumi new` is to be a simple way to get a fully initialized project. 

Any other options that would have helped you here?

From https://www.pulumi.com/docs/reference/cli/pulumi_new/: 

> -g, --generate-only             Generate the project only; do not create a stack, save config, or install dependencies

**Comment by brandonkal** [comment]
Thank you for the tip. I looked through the flags before opening so I'm surprised I missed `-g`!

I'm not asking for the default to be changed. Though on that note, I would enjoy having `pulumi new` use yarn when it is in the PATH (with an environment variable option for those who wish to make the preference explicit).

**Comment by pgavlin** [comment]
> I would enjoy having pulumi new use yarn when it is in the PATH (with an environment variable option for those who wish to make the preference explicit).

This is an interesting suggestion. I think that should be a relatively small change. @justinvp ?

**Comment by justinvp** [comment]
Yep, this has been requested before and we are fixing as part of https://github.com/pulumi/pulumi-policy/issues/102. PR here: https://github.com/pulumi/pulumi/pull/3556
