### ISSUE TITLE
[QUESTION] Any Python lambda Aurora examples?

### ISSUE THREAD

**Issue by scheung38** [pulumi/pulumi#3521]
Showing how to query, launch and shutdown etc?

Thanks

**Comment by lukehoban** [comment]
@scheung38 could you share any more details on what you are looking for (or what you have tried so far)?  Or join https://slack.pulumi.com/ to discuss?

**Comment by scheung38** [comment]
Only seen your Typescript example but would like to see Python implementation

**Comment by lukehoban** [comment]
Is there a specific TypeScript example you’d like to see in Python?

**Comment by scheung38** [comment]
Just how to setup AWS Lamdba Aurora RDS with Python and basic CRUD.
