### ISSUE TITLE
Pulumi up with Azure Storage SAS token returns SignedURL error

### ISSUE THREAD

**Issue by ndonze** [pulumi/pulumi#3537]
Repro steps:

1. Create a new Pulumi project. For example:

```
> mkdir ReproAzureSasTokenSignedUrlError
> cd ReproAzureSasTokenSignedUrlError
> pulumi new -g azure-typescript
> npm i

Set a location on the storage account in index.ts
```

2. Set up a blob container in Azure Storage for Pulumi stack state
2a. Create an Azure Storage account
2b. Within your Azure Storage account, create a blob container with private access
2c. Within your blob container, add a new Access policy (Stored access policies) with:
--- All Permissions selected
--- An Expiry time well in the future
2d. Within your Azure Storage account, navigate to Storage Explorer (preview) > BLOB CONTAINERS
2e. Right-click on [your blob container]
2f. Get Shared Access Signature
2g. Select your Access policy
2h. Create
2i. Copy the query string value in full (including the leading question mark)

3. Log into Pulumi with stack state in Azure Storage
3a. Set env var AZURE_STORAGE_ACCOUNT to your Azure Storage account name
3b. Set env var AZURE_STORAGE_SAS_TOKEN to the query string copied when generating your Shared Access Signature
3c. `pulumi login azblob://[your blob container name]`

4. Initialize stack and provision
4a. `pulumi stack init repro`
4b. `pulumi up`

Expected: Provisioning completes and updates stack state in Azure Storage without error

Actual: Provisioning completes and stack state appears to be updated, but the following error is returned:

> error: Could not get signed url for stack location: blob (code=Unknown): to use SignedURL, you must call OpenBucket with a non-nil Options.Credential

**Comment by WillooWisp** [comment]
Same thing with preview:

warning: Could not get signed url for stack location: blob (key ".pulumi/stacks/mytestdev.json") (code=Unknown): azureblob: to use SignedURL, you must call OpenBucket with a non-nil Options.Credential

**Comment by stack72** [comment]
Linked to #4029

**Comment by stack72** [comment]
Hi @WillooWisp / @ndonze 

I just updated the linked issue to say we will be suppressing permalinks (by default) on non-SaaS backends so this error will no longer be surfaced

I am going to be starting work on that now so it will ship in Pulumi v2.21.0

Paul
