### ISSUE TITLE
Permits to don't fail when stack reference does not exist

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi#3540]
I'm trying to do a blue green deployment of a resource, and for this use case, I need to know if the current stack has already been deployed and if true, to get a previous output.

Here is a pseudo code:

project `blue-green-deploy`, stack `dev`:
```ts
const thisStack = new pulumi.StackReference(`account/blue-green-deploy/${env}`)
let color
if (thisStack) {
  const previousColor = thisStack.getOutputSync("color")
  color = (previousColor && previousColor === 'blue') ? 'green' : 'blue'
} else {
  color = 'blue'
}

Unfortunately, if the stack has never been deployed, the stack reference fails during runtime and I can not recover from it / catch it.

**Comment by leezen** [comment]
I can see why you might want to catch an exception for not being able to instantiate the StackReference, but I also don't think this is how you actually want to go about what you're trying to do. Can you please explain why you need to get a previous output as part of doing your deployment? I'd like to better understand your use-case.

**Comment by boillodmanuel** [comment]
Hello,

My use case is :
- create a VM (azure)
   - with a new disk if this is the first deployment
   - reusing the previous disk for next deployments

My idea was to save the disk id in the pulumi stack outputs and retrieve it dynamically afterwards.
But I encounter several issues (as far as I remember):
- the stack reference fails if the stack has not been deployed (my workaround was to use a config flag for that)
- when deployment fails (totally or partially), outputs could be unavailable (AFAIR) or updated with a new disk id (but I wish to keep the original / last successfully deployed disk id)

So, I will certainly move to another strategy to do that.

**Comment by boillodmanuel** [comment]
Feel free to close this issue if you want

**Comment by leezen** [comment]
I think I might be missing something. What you're describing should just happen automatically without having to use stack references to the stack itself. For example, if you have a VM ("my-vm") and a volume ("my-vol") attached to it, which are created as part of the first deployment. And your second deployment has a new VM ("new-vm") but still uses "my-vol" -- pulumi shouldn't attempt to create a new volume. Is this different from what you're describing or not happening for you?

**Comment by boillodmanuel** [comment]
Indeed, I omit some parts to simplify ;)

After first deployment, I have :
- `vm1` attached to `disk1`

I (Azure) can't create a second `vm2` attached to the same disk while the first `vm1` exists.
So, the idea was to create a new `vm2` attached to a new `disk2` which is copied from `disk1`

In the pulumi project, only the `vm2` and `disk2` resources are present because previous resources should be deleted at the end of deployment.

In order to create `disk2` from `disk1`, I need the `disk1.id` which isn't present in the projet anymore. It's while I tried to output the id to reuse it later.

I hope it's clearer now 🙂

**Comment by leezen** [comment]
I think one option could be to use dynamic provisioners for this. I'm not as familiar with Azure, but assuming the process would be similar to AWS, you could have the dynamic provisioner unmount the disk upon instance deletion and re-attach it as part of instance creation with a provisioner depending on the instance resource. Here's the documentation for using dynamic provisioners: https://www.pulumi.com/docs/intro/concepts/programming-model/#providers

**Comment by boillodmanuel** [comment]
Thanks for pointing dynamic provider out. It's very interesting. 
I'll close this issue as I don't need that feature anymore.
