### ISSUE TITLE
Please hide output when an exception occurs...

### ISSUE THREAD

**Issue by elucidsoft** [pulumi/pulumi#3545]
Can you please hide the output and status on an exception and just show the exception? 

1. If your output is large it hides the exception and you might think it succeeded. This has happened to me multiple times where I checked in broken code after running preview because my output pushed the exception so far up the console window I didn't see it.

2. It shows incorrect plan status anyways, so why even show it?  
3. It's not useful information in most cases.

**Comment by pgavlin** [comment]
> If your output is large it hides the exception and you might think it succeeded. This has happened to me multiple times where I checked in broken code after running preview because my output pushed the exception so far up the console window I didn't see it.

When you refer to output, are you referring to your Pulumi program's stdout (e.g. console.log messages)?

> It shows incorrect plan status anyways, so why even show it?

Can you elaborate on this? In what way is the plan status incorrect?

**Comment by elucidsoft** [comment]
Plan status shows delete when it throws an exception which is incorrect.

Yes, I am referring to sdout.

**Comment by lukehoban** [comment]
@elucidsoft Any chance you could share output or screenshot. I don't quite follow what you are describing here.
