### ISSUE TITLE
Version of gRDP dependency of @pulumi/pulumi does not compile with Node 13

### ISSUE THREAD

**Issue by masm** [pulumi/pulumi#3551]
I am using Node 13. When installing grpc@1.21.1, a dependency of @pulumi/pulumi, the compilation fails. The latest version of grpc is 1.24.2, and that works. Is it possible to update the dependency, please?

**Comment by lukehoban** [comment]
I believe `@pulumi/pulumi` version `1.6.0`, released yesterday, now depends on `grpc` version `1.24.2`.  See https://github.com/pulumi/pulumi/pull/3512 and https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md#160-2019-11-20.
