### ISSUE TITLE
Feature Request: AppService Environments (ASE) Support

### ISSUE THREAD

**Issue by moattarwork** [pulumi/pulumi#3553]
Pulumi does not have any support for creating App Service Environment and assign that to a separate vNet with isolated security group and routing. 

Currently, it seems there is some possibility to do that using ARM templates but we are testing this with our edge cases. It would be good to have a separate implementation of that.

Terraform team is implementing that but it's not ready yet. Here is the link for conversation: https://github.com/terraform-providers/terraform-provider-azurerm/issues/438

**Comment by pgavlin** [comment]
Generally we pick up support for new resources as soon as they've been added to the upstream TF provider. For features that aren't yet implemented but are available via the cloud provider's SDK, you can workaround the lack of the resource via a dynamic provider: https://www.pulumi.com/docs/intro/concepts/programming-model/#dynamicproviders

In this case, you could use the ARM SDK inside a dynamic provider to create the resources you describe.

**Comment by pgavlin** [comment]
In the meantime, we will track adding this feature using the upstream TF issue.
