### ISSUE TITLE
[QUESTION] Autocompletion Typescript lacking in VS Code?

### ISSUE THREAD

**Issue by scheung38** [pulumi/pulumi#3555]
After importing, say:

import * as random from "pulumi/random";

const dbpassword = new random.

and CTRL-SPACE I expect to see for example RandomString

Don't see it as well as many others like:

const vpc = new awsx.

Also dont see .ec2

**Comment by pgavlin** [comment]
@lukehoban any ideas here?

**Comment by lukehoban** [comment]
You have to `npm install @pulumi/random` to get the package.  

You then have to have an `import * as random from "@pulumi/random"`.

Then you should get completion list on `random.`.

Pulumi doesn't do anything particularly unique here - you can just follow standard VS Code and NPM tooling guides to get set up.
