### ISSUE TITLE
Does OutPut supports resource reference across multi aws accounts ?

### ISSUE THREAD

**Issue by Kiddinglife** [pulumi/pulumi#3566]
I am following aws best practise of "multi accounts" with the help of AWS Control Tower and AWS Organations. I am just wondering if there is a convient way in pumuli to help for across accounts resource reference?
i.e. 
account A has a s3 bucket with name xxxx
account B has a lambda that needs to reference xxx as environment variable.
Is there sdk api for this ?

**Comment by pgavlin** [comment]
If these resources are in separate stacks, you can configure the AWS provider for each stack to use the appropriate account: https://www.pulumi.com/docs/get-started/aws/configure/.

If these resources are in the same stack, you can use explicit instances of `aws.Provider` to achieve this: https://www.pulumi.com/docs/intro/concepts/programming-model/#providers https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/#Provider

**Comment by pgavlin** [comment]
If these resources are in separate stacks, you can configure the AWS provider for each stack to use the appropriate account: https://www.pulumi.com/docs/get-started/aws/configure/.

If these resources are in the same stack, you can use explicit instances of `aws.Provider` to achieve this: https://www.pulumi.com/docs/intro/concepts/programming-model/#providers
