### ISSUE TITLE
[QUESTION] pulumi config set aws: profile <profilename>

### ISSUE THREAD

**Issue by scheung38** [pulumi/pulumi#3567]
pulumi config set aws: profile <profilename> 

Where do I get this profilename from AWS?

**Comment by lukehoban** [comment]
See https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html.

**Comment by scheung38** [comment]
So if generated credential file:

[saml] 
AWS-Access-key

Then it is
Pulumi config set aws:profile saml

**Comment by lukehoban** [comment]
> `pulumi config set aws:profile saml` 

Yep - that’s right.

**Comment by glitchwizard** [comment]
@lukehoban is there a way to do this in typescript? I saw that it said you can use environmental variables, so that's the only way other than the cli command `pulumi config set aws:profile <profile name>` ?

**Comment by lukehoban** [comment]
@glitchwizard If you need to programmtically construct a provider - you can use `new aws.Provider("aws", { profile: "profilename" })`.  See https://www.pulumi.com/docs/reference/pkg/aws/provider/.
