### ISSUE TITLE
[QUESTION] Win 10 pulumi new fails

### ISSUE THREAD

**Issue by scheung38** [pulumi/pulumi#3568]
Corporate environment Win 10 PyCharm terminal
> pulumi whoami

returns current user

> pulumi new aws-python

error: authorization failed?

**Comment by pgavlin** [comment]
Can you provide mode details? A screenshot of your terminal or copy/pasting the exact output would be helpful.

**Comment by scheung38** [comment]
Error: authorization fails

**Comment by lukehoban** [comment]
From @scheung38 offline discussion:

> Hi Luke, https://github.com/pulumi/templates endpoint is readable / accessible but cannot clone but able to download as zip

**Comment by emiliza** [comment]
Closing out stale issue - the templates repo is accessible and I'm able to download as zip. 

fwiw original error of "authorization failed" sounds like an auth error with Github API
