### ISSUE TITLE
generate Pulumi scripts from ARM templates?

### ISSUE THREAD

**Issue by danvanderboom** [pulumi/pulumi#3577]
Is there a way to generate a Pulumi script (for each language) from an ARM template? To sort of reverse engineer existing resources. 

If not, does Pulumi expose a data structure representing the list of types to be constructed and the properties to set or override defaults for? Something to build code generators from...

**Comment by pgavlin** [comment]
> Is there a way to generate a Pulumi script (for each language) from an ARM template? To sort of reverse engineer existing resources.

Not at the current time.

> If not, does Pulumi expose a data structure representing the list of types to be constructed and the properties to set or override defaults for? Something to build code generators from...

The best references we have are the [Terraform](https://github.com/pulumi/pulumi-terraform-bridge/tree/master/pkg/tfgen) and [Kubernetes](https://github.com/pulumi/pulumi-kubernetes/tree/master/pkg/gen) code generators. I'm also happy to answer any questions you have.

**Comment by stack72** [comment]
This is now available via https://www.pulumi.com/arm2pulumi/ :)
