### ISSUE TITLE
Warn if both index.js and index.ts exist

### ISSUE THREAD

**Issue by brandonkal** [pulumi/pulumi#3582]
When debugging tsc, a index.js file was created. This caused confusing behavior when  the two eventually diverged.

I would suggest a helpful warning if pulumi detects both a index.js and a index.ts file.

**Comment by pgavlin** [comment]
> This caused confusing behavior when the two eventually diverged.

What sort of behavior did you see?

**Comment by brandonkal** [comment]
Pulumi started using index.js instead of index.ts
It may be a good idea to have pulumi record if it is first deployed with index.ts so that it will not run the js file if it later appears.
