### ISSUE TITLE
Parents deleted by refresh corrupt Pulumi state file

### ISSUE THREAD

**Issue by brandonkal** [pulumi/pulumi#3583]
When state integrity goes sour, `pulumi stack rm` should continue to function.

Steps to reproduce:
1. Deploy k8s deployment and service
2. manually delete deployment
3. `pulumi refresh`. This should not be allowed as it breaks the stack. A warning is shown that the service is now unhealthy (does not target pod)
4. `pulumi destroy` or `pulumi stack rm`
```
error: .pulumi/stacks/dev.json: snapshot integrity failure; refusing to use it: child resource urn:pulumi:dev::gitkit::kubernetes:apps/v1:Deployment$kubernetes:core/v1:Service::gitea refers to missing parent urn:pulumi:dev::gitkit::kubernetes:apps/v1:Deployment::gitea
```

**Comment by pgavlin** [comment]
Thanks for the repro steps!

> `pulumi refresh`. This should not be allowed as it breaks the stack. A warning is shown that the service is now unhealthy (does not target pod)

This is interesting--did you deploy this stack from a Pulumi program you wrote manually, or is this from an example/`kx`/etc.?

**Comment by brandonkal** [comment]
This was a program I wrote manually. Just a Gitea pod behind a service with pvc and ingress.

**Comment by jkinkead** [comment]
I ran into this as well. It seems like a failure in the child-parent model; children should be robust to parents being taken away, and in particular not corrupt the Pulumi state.

**Comment by lukehoban** [comment]
I was working with a user to debug and issue - and they ran into this when doing `refresh` on a stack that had a Helm chart whose parent was a Namespace.  The Namespace got removed from the checkpoint by the refresh, but the Helm chart was left there (because it is a component resource). This led to the same corruption mentioned by others here.

**Comment by aszenz** [comment]
Faced the same issue after doing `pulumi refresh`, one sns topic was removed directly from aws ui, I refreshed now pulumi complains about missing parent `sns topic` for child resource `topic event subscription`.
I'm just wondering if destroying everything and recreating would work?

**Comment by WoLfulus** [comment]
This just happened to me after a refresh, Now I'm not sure how to proceed.

**Comment by vyrwu** [comment]
> I was working with a user to debug an issue - and they ran into this when doing `refresh` on a stack that had a Helm chart whose parent was a Namespace. The Namespace got removed from the checkpoint by the refresh, but the Helm chart was left there (because it is a component resource). This led to the same corruption mentioned by others here.

Had the simillar issue. The updates to my stack were getting stuck with error messages referring to a missing parent resource, like:
```
aws:iam:RolePolicyAttachment (grafana-euw1-test):
    error: pre-step event returned an error: failed to verify snapshot: child resource urn:pulumi:test::iac-services::kubernetes:core/v1:Namespace$kubernetes:yaml:ConfigGroup::externaldnspublic-euw1-test refers to missing parent urn:pulumi:test::iac-services::kubernetes:core/v1:Namespace::cluster-services-namespace-euw1-test
```

My workaround was to run:
```bash
$ pulumi stack export --file stack.json
```

Then replacing the missing resource URN with the URN of the stack as a parent in the `stack.json` file. After modifying the file:
```bash
$ pulumi stack import --file stack.json
$ pulumi refresh
```

After doing that, I could successfully destroy&rebuild my stack.

**Comment by mrjackdavis** [comment]
Hey, I've run into this on multiple occasions, especially in relation to SNS topics and subscriptions. They return `status code: 404` errors.

I would expect `refresh` to detect if an item, or one of it's parents is deleted.

My current, onerous, workaround is to remove these items from state. But it's frustrating especially if there's a lot.

Are there any better workarounds?

**Comment by ffMathy** [comment]
I have this problem as well, when creating inspector resource groups that are empty, but act as a parent to other resources.

When running `pulumi refresh`, it just marks all those parents as deleted (most likely because they are not present?), which then causes the corruption.

This is quite critical. We'd like to run refresh in our CI/CD to avoid drifting, but not when it corrupts the state.

Any ETA on this @lukehoban @pgavlin?

**Comment by ffMathy** [comment]
@iwahbe while this does indeed fix the corruption, it still causes resource groups to be created by Pulumi, to disappear during refresh. They are then re-created again during `pulumi up`, but that creates a lot of noise in the diff generated.

**Comment by ffMathy** [comment]
More specifically, by "resource groups", I mean my `aws:inspector:ResourceGroup`.
