### ISSUE TITLE
Use feature-detection to determine how getOutputSync should behave

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#3584]
`getOutputSync` should only call into `pulumi:pulumi:readStackOutputs` if our CLI supports this functionality.  Otherwise it should fallback to the old codepath where we use deasync (showing a warning if we're doing that).

**Comment by pgavlin** [comment]
So this should already be implemented: https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/stackReference.ts#L132-L198

**Comment by CyrusNajmabadi** [comment]
Closing out.
