### ISSUE TITLE
Improve policy packs experience at the command line

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3589]
Right now we have `pulumi policy apply`, but no way of temporarily disabling said pack using the CLI. For that, we need to go to the service. Related, I did find the terminology a little inconsistent here -- my mental model is that I upload packs, that those packs are versioned, and that I can enable/disable any pack for my organization. Is my mental model incorrect?

Assuming it's correct, I would like to propose we have four commands:

* `pulumi policy publish`: does what it does today, publishes a new version of a pack.
* `pulumi policy rm`: physically removes that pack entirely, and all version history (but not auditing records that tell me as an end user what packs have been run -- those should be preserved).
* `pulumi policy enable`: enables an already-published pack at a given version number.
* `pulumi policy disable`: disables an already-enabled pack.

Eventually, I would imagine that perhaps `enable` and `disable` are what we would use to selectively enable/disable individual rules as well for a given pack.

**Comment by ekrengel** [comment]
I will evaluate what is the set of commands we want to support and then work on implementing this.. also considering `ls` and other possible commands

**Comment by ekrengel** [comment]
To expand on Joe's initial thoughts:

- `pulumi policy publish [org]`: does what it does today, publishes a new version of a pack.

- `pulumi policy rm POLICY-PACK-NAME [--version]`: physically removes that pack entirely, and all version history (but not auditing records that tell me as an end user what packs have been run -- those should be preserved). NOTE: That this will fail if its applied anywhere. Optional specify the version you want to remove.

- `pulumi policy enable POLICY-PACK-NAME [--version] [--policy-group]`: enables an already-published pack at a given version number. If version is not specified, uses the latest. If Policy group is not specified, use the default.

- `pulumi policy disable POLICY-PACK-NAME[--policy-group]`: disables an already-enabled pack. If Policy group is not specified, use the default.

- `pulumi policy ls`: list all policy packs published to the organization & their latests version

@justinvp What do you think? are there already CLI commands that only work w the service (besides Policy ones)?

**Comment by justinvp** [comment]
@ekrengel, what is the difference between enabling/disabling and applying/unapplying? Does `enable` replace `apply`?

**Comment by ekrengel** [comment]
@justinvp `enable` would replace `apply`. We could also go with `apply` and `unapply` ... either way i think we should try to get the terminology solidified and make sure to be consistent through docs / the console

**Comment by ekrengel** [comment]
I was also think we should have something for listing the policy groups..

**Comment by justinvp** [comment]
> `enable` would replace `apply`

👍

> Any thoughts on which one it should be?

I prefer `enable` as it's more intuitive (to me). When I was first learning about PaC, I had to read the docs to know what `apply` meant.

Should we make `pulumi policy publish` implicitly enable the policy pack on the default policy group? Or have an array flag to specify which policy groups it should be enabled for? (If no policy groups are specified, the default is used automatically?)

> I was also think we should have something for listing the policy groups.. although not sure what that command would look like.

Sounds good to me. Maybe `pulumi policy group ls`? Then there could also be commands for adding/removing policy groups (e.g. `pulumi policy group add` and `pulumi policy group remove`)

**Comment by ekrengel** [comment]
* I think we can add a flag to also apply to `pulumi policy publish` -- although i think i'll probably want to think a bit more about how this will work (which policy group to apply to, should we take a list, etc.) that i will punt this for now

* If we use `pulumi policy group ls` then should we also use `pulumi policy pack ls`? 

* In terms of adding `pulumi policy group add` -- potentially? It seems strange to me to add this to the CLI since you cannot add stacks via the CLI... maybe in the future but for starters, I think we should start w the other commands and then maybe add a set of "policy group" specific commands down the line.

**Comment by ekrengel** [comment]
@justinvp So to summarize:

- `pulumi policy publish [org]`: does what it does today, publishes a new version of a pack.

- `pulumi policy rm [org/]POLICY-PACK-NAME [--version]`: physically removes that pack entirely, and all version history (but not auditing records that tell me as an end user what packs have been run -- those should be preserved). NOTE: That this will fail if its applied anywhere. Optional specify the version you want to remove.

- `pulumi policy enable [org/]POLICY-PACK-NAME [--version] [--policy-group]`: enables an already-published pack at a given version number. If version is not specified, uses the latest. If Policy group is not specified, use the default.

- `pulumi policy disable [org/]POLICY-PACK-NAME[--policy-group]`: disables an already-enabled pack. If Policy group is not specified, use the default.

- `pulumi policy pack ls [org]`: list all policy packs published to the organization & their latests version

- `pulumi policy group ls [org]`: list all policy groups in the organization

**Comment by ekrengel** [comment]
Made a lot of progress here. Still have the following left:
- `pulumi policy pack ls [org]`: list all policy packs published to the organization & their latests version
- `pulumi policy group ls [org]`: list all policy groups in the organization
- `pulumi policy rm [org/]POLICY-PACK-NAME`: not specifying a version deletes all --> need to wait for service release to add this functionality.

I am working on the ls functionality today, but will push this out as it will probably be sometime before this is merged.

**Comment by ekrengel** [comment]
The last PR for this has been merged!
