### ISSUE TITLE
Pulumi Preview Hanging Indefinitely on `sts:GetCallerIdentity:

### ISSUE THREAD

**Issue by miking-the-viking** [pulumi/pulumi#3604]
I've recently run into an issue on a particular stack on a particular project. When I attempt to `preview` or `up` the preview hangs on `running...` at the Stack resource level. It never shows any of the resources in the Stack. The project is exclusively being deployed to AWS. If I run `refresh` it _does_ show all the resources and indicates that there's updates it needs to perform to match the state.

Using verbose debugging it seems to just hang indefinitely (hours before I manually cancelled it) on `debug: Trying to get account information via sts:GetCallerIdentity`.

The crazy thing is: I have other projects/stacks on this device using the _same_ pulumi access token, and AWS profile that can deploy no problem. This issue only started happening for me when I switched to a new laptop. Another developer on my team has no issue deploying this stack using the same credentials on his machines.

Some other info: all the Pulumi projects are built with TS.

```
PULUMI
v1.6.1

AWS CLI
aws-cli/1.16.290 Python/3.7.5 Darwin/19.0.0 botocore/1.13.26

OS X
Catalina 10.15.1 (19B88)

Docker
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by pgavlin** [comment]
Which version of `@pulumi/pulumi` and `@pulumi/pulumi-aws` are you using for this project?

**Comment by miking-the-viking** [comment]
The following versions are currently being used from Pulumi:

```
        "@pulumi/aws": "^1.0.0",
        "@pulumi/awsx": "^0.18.10",
        "@pulumi/docker": "^0.17.4",
        "@pulumi/pulumi": "^1.0.0",
```

**Comment by lukehoban** [comment]
This appears to be the same issue as https://github.com/pulumi/pulumi-aws/issues/814, which was reported around the same time.

**Comment by lukehoban** [comment]
I have a repro of this,  and indeed it is the same issue as https://github.com/pulumi/pulumi-aws/issues/814.  I'll close this one out as a dupe.
