### ISSUE TITLE
preview and up hang indefinitely when looping over results of a lookup function

### ISSUE THREAD

**Issue by bincyber** [pulumi/pulumi#3605]
##### ISSUE TYPE
- Bug Report

##### PULUMI VERSION
This issue was observed with Pulumi 1.4.0 and 1.6.1 and pulumi_aws v1.12.0.

##### SUMMARY
This is a basic example that demonstrates this issue:

```python
import pulumi_aws as aws
import pulumi

# provision a new VPC and Internet Gateway
vpc = aws.ec2.Vpc(
    resource_name="vpc",
    cidr_block="10.10.0.0/16"
)

ig = aws.ec2.InternetGateway(
    resource_name="internet-gateway",
    vpc_id=vpc.id,
)

# retrieve the IDs of the VPC's route tables
# at this stage, this will return only the main route table since no other route tables exist
route_tables = vpc.id.apply(lambda i: aws.ec2.get_route_tables(vpc_id=i))

# set the Internet Gateway as the default route
for i in route_tables.ids:
    aws.ec2.Route(
        resource_name=f"{i}-default-gateway",
        route_table_id=i,
        destination_cidr_block="0.0.0.0/0",
        gateway_id=ig.id
    )
```
Both `pulumi preview` and `pulumi up` hang because the VPC does not exist, so it doesn't have route tables to return to be looped over. Even if the for loop is commented out and the VPC is provisioned, and then the for loop is uncommented, it will still hang indefinitely until manually cancelled with Ctrl+C.

Is this approach incorrect or is there a workaround?

**Comment by pgavlin** [comment]
This approach will not work: the result of the `apply` is not iterable. You could create the routes inside an `apply`, which should work.

All that said, it is surprising that the program is hanging... We shouldn't even run the `apply` if the VPC doesn't yet exist. Can you enable verbose logging (run with `-v=9 --logtostderr` and redirect stderr to a file) and email me the output?

**Comment by bincyber** [comment]
Thanks for looking into this issue @pgavlin .

Can you provide an example of how resources are created inside an `apply`? I've tried the following ways:

1. 
```python
route_tables = vpc.id.apply(lambda i: aws.ec2.get_route_tables(vpc_id=i))

route_tables.ids.apply(lambda rtb_id: aws.ec2.Route(
        resource_name=f"{rtb_id}-default-gateway",
        route_table_id=rtb_id,
        destination_cidr_block="0.0.0.0/0",
        gateway_id=ig.id
    )
)
```

2.
```python
def provision_default_routes(vpc_id):
    for i in aws.ec2.get_route_tables(vpc_id=i).ids:
        aws.ec2.Route(
            resource_name=f"{i}-default-gateway",
            route_table_id=i,
            destination_cidr_block="0.0.0.0/0",
            gateway_id=ig.id
        )

vpc.id.apply(provision_default_routes)
```
3.
```python
def provision_default_routes(args):
    vpc_id = args[0]
    ig_id = args[1]

    for i in aws.ec2.get_route_tables(vpc_id=vpc_id).ids:
        aws.ec2.Route(
            resource_name=f"{i}-default-gateway",
            route_table_id=i,
            destination_cidr_block="0.0.0.0/0",
            gateway_id=ig_id
        )


pulumi.Output.all(vpc.id, ig.id).apply(provision_default_routes)
```

None of these approaches worked for me.

The documentation for `apply` mentions that the function is not allowed to make resources: https://www.pulumi.com/docs/reference/pkg/python/pulumi/#pulumi.Output.apply. Is this still true?

I have emailed you the log output.
