### ISSUE TITLE
Picking Typescript version

### ISSUE THREAD

**Issue by from-nibly** [pulumi/pulumi#3606]
Version 3.7 of typescript is out with new features. I get compile errors when using them for instance the null coalesce `??`. It looks like it is trying to compile with the wrong version of typescript. I have version `3.7.2` explicitly set in my package.json. Looks like pulumi is using `=3.6.3`. I simply ran 
```bash
rm -rf node_modules/@pulumi/pulumi/node_modules/ts-node && rm -rf node_modules/@pulumi/pulumi/node_modules/typescript
```
This resolved the issue, but this isn't a real solution. I can't run that every time I run npm install.

Shouldn't typescript and ts-node be a dev dependency for pulumi and not a production dependency?

Apologies if this has been asked before, but it has been really difficult to figure out how to control the typescript version with pulumi.

**Comment by pgavlin** [comment]
@CyrusNajmabadi @lukehoban what's the recommended approach here?

**Comment by CyrusNajmabadi** [comment]
> Shouldn't typescript and ts-node be a dev dependency for pulumi and not a production dependency?

TypeScript needs to be a production dependency for us because we use it as part of our 'closure serialization' infrastructure.

I'm not sure if we can both reference TyepScript as a prod-dependency for closure-serialization while also allowing *another* version of the language to be used for compiling us.

--

That said, we should likely just update our stack to move to TS 3.7

**Comment by from-nibly** [comment]
What about making it an optional dependency that is actually required at runtime. That way the user can define which version should be used. You can even set a version range that is supported. And the pulumi new command can just add the dependency to the root project package.json for you.

**Comment by from-nibly** [comment]
I guess peerDependencies might be more appropriate?

https://npm.github.io/using-pkgs-docs/package-json/types/peerdependencies.html

https://medium.com/angular-in-depth/npm-peer-dependencies-f843f3ac4e7f

**Comment by justinvp** [comment]
We should definitely move to 3.7.x soon, but in the meantime, what about [disabling](https://www.pulumi.com/docs/intro/languages/javascript/#disabling-built-in-typescript-support) the built-in TypeScript support and just running `tsc` manually to compile the Pulumi program to JavaScript?

**Comment by from-nibly** [comment]
I mean long term upgrading typescript isn't really a solution. I would have to wait for pulumi to catch up every time typescript came out with a new feature, and pulumi would have to rush to upgrade every time.

As a workaround I can add a step to my deployment by either

- Removing pulumi's versions of typescript and ts-node
- Compile the typescript on my own.

Removing the dependencies is actually easier than adding typescript compilation to my build pipeline. It either has to be manual or I have to build `pulumi up` into some sort of pipeline where it recompiles every time I run it.

Is setting up peerDependencies or optionalDependencies not something you want to do?

**Comment by CyrusNajmabadi** [comment]
> Is setting up peerDependencies or optionalDependencies not something you want to do?

**Comment by CyrusNajmabadi** [comment]
> Compile the typescript on my own.

Note: this is a very normal way to do things.   I still personally just compile my TS and then just run pulumi on my generated JS files.

**Comment by CyrusNajmabadi** [comment]
fixed with https://github.com/pulumi/pulumi/pull/3627

**Comment by aecorredor** [comment]
Bumping this again. I'm using TypeScript version `4.9.3` and I'm getting `A 'const' assertions can only be applied to references to enum members, or string, number, boolean, array, or object` when trying to do something like 

```ts
const myVar= `${otherVar}-suffix` as const
```

That's a valid `as const` assertion in TS `4.9.x`, but pulumi throws that TS error when running the deployment step. My thought was that Pulumi is using an older version where that assertion is still not valid.

Is there any workaround?

**Comment by lcswillems** [comment]
It seems Pulumi is currently using the version 3.8.3 of TypeScript. That's super old...

**Comment by justinvp** [comment]
@aecorredor, for a workaround see https://github.com/pulumi/pulumi/issues/12117#issuecomment-1423437407
