### ISSUE TITLE
Should add all supported CI/CD systems to the Github App page

### ISSUE THREAD

**Issue by AgrimPrasad** [pulumi/pulumi#3610]
https://www.pulumi.com/docs/guides/continuous-delivery/github-app/ only lists the following:

1. AWS Code Services
2. Azure DevOps
3. CircleCI
4. GitHub Actions
5. GitLab CI
6. Travis

However, I see support for more CI/CD systems here which should all be listed (unless there's some integration missing?): https://www.pulumi.com/docs/guides/continuous-delivery/

**Comment by chrsmith** [comment]
Thank you for the report @AgrimPrasad , I'll get that cleaned up!

**Comment by chrsmith** [comment]
Fixed in https://github.com/pulumi/docs/pull/2203

**Comment by AgrimPrasad** [comment]
Thanks, had a minor comment on https://github.com/pulumi/docs/pull/2203

Otherwise looks good.
