### ISSUE TITLE
First-class Stack component for .NET

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#3619]
(moved from #3470, related https://github.com/pulumi/pulumi/pull/3399#discussion_r338799707)

Consider unifying API of ComponentResource vs Stack. They are almost the same thing: a collection of resources with outputs, but one is a class with output properties while the other is a function returning a dictionary.

We could publicly expose the existing `Stack` class with a new default constructor. An end program would derive from that class to define its resources in its constructors. The outputs would be defined with properties of type `Output<T>`.

Here is an example program:

``` cs
class MyStack : Stack
{
    public Output<string> StorageConnectionString { get; }

    public MyStack()
    {
        var resourceGroup = new ResourceGroup("functions-rg");

        var storageAccount = new Account("sa", new AccountArgs
        {
            ResourceGroupName = resourceGroup.Name,
            AccountReplicationType = "LRS",
            AccountTier = "Standard",
        });

        this.StorageConnectionString = storageAccount.PrimaryConnectionString;
    }
}

class Program
{
    static Task<int> Main() => Deployment.RunAsync<MyStack>();
}
```

Here are some benefits to this approach:

1. Implementation of `Main()` is a straightforward one-liner without callbacks.
2. `Stack` ~ the top-level `ComponentResource`.
3. Feels more C#-idiomatic (?)
4. Immediately introduces the concept of "stack" to the user. When they see a stack row in the CLI, they can map this to their component.

Downsides:

1. Multiple ways to do the same thing may be confusing.
2. Since constructors can't be async, there's no clear story when control flow must depend on async calls (e.g. invokes). However, we need to address this for component resources regardless of stacks, and then use the same approach for stacks.

**Comment by CyrusNajmabadi** [comment]
First, i really like the idea of going down this route and feeling more .net'y

Main problem i have here is that the work is expected to be done in the constructor of Stack, which is not `async`.  This will make async work more painful.  

I'd like an approach that allows for things like exposing a `.Run` method or something like that to provide a place for async work to happen. 

Second, it feels like if we go this route, we should just go the route of using attributes/reflection and have this type discovered for people without them having to write 'main' at all.

**Comment by mikhailshilkov** [comment]
> Main problem i have here is that the work is expected to be done in the constructor of Stack, which is not async. This will make async work more painful.

I agree. Do we have the same problem for component resources?

> Second, it feels like if we go this route, we should just go the route of using attributes/reflection and have this type discovered for people without them having to write 'main' at all.

We could... However, we could take these two things independently, or step by step.

**Comment by CyrusNajmabadi** [comment]
> I agree. Do we have the same problem for component resources?

yes.  note that there's a PR we're suggesting for this: https://github.com/pulumi/pulumi/pull/3648

If that goes through, we'll likely be ok as we can employ the same strategy there.

**Comment by mikhailshilkov** [comment]
I updated the sample PR and the top comment with `InitializeAsync` method that enabled async control flows.

**Comment by hansmbakker** [comment]
> I updated the sample PR and the top comment with InitializeAsync method that enabled async control flows.

@mikhailshilkov what is the current recommendation for `InvokeAsync` calls which is e.g. needed for `await Pulumi.AzureAD.GetClientConfig.InvokeAsync();`?

I cannot find what happened to `InitializeAsync` from your comment?

**Comment by Zaid-Ajaj** [comment]
@hansmbakker Since `net6.0` it is a lot easier to use top-level program statements and so the recommended way today is to use `RunAsync`:

```cs
using Pulumi;

return await Deployment.RunAsync(async() =>
{
    var clientConfig = await Pulumi.AzureAD.GetClientConfig.InvokeAsync();
});
```
the `InitializeAsync` method that @mikhailshilkov was referring to is async method _you_ add to your `Stack` class and synchronously call it inside the constructor of the `Stack` class (since constructors are not async) to populate the outputs. 

This is of course very cumbersome whereas with `RunAsync` you simply mark the callback as `async` and `await` any async function like you would usually do

**Comment by hansmbakker** [comment]
thank you @Zaid-Ajaj!

That approach works - is there any documentation on how best to structure this approach using an async callback or `Task`, especially when your codebase grows (I guess in the past you would `ComponentResources`, but there is the same issue with the constructor)

**Comment by Zaid-Ajaj** [comment]
> how best to structure this approach [...]

@hansmbakker You can simply use function composition to define resources and call them in the callback function of the entry `RunAsync`.

```cs
using Pulumi;

return await Deployment.RunAsync(async() =>
{
    var clientConfig = await ClientObjectId();
});

async Task<string> ClientObjectId() 
{
    var clientConfig = await Pulumi.AzureAD.GetClientConfig.InvokeAsync();
    return clientConfig.ObjectId;
}
```
where you can put the function `ClientObjectId` in a different file and have create resources or call other invokes. Hope this helps

**Comment by hansmbakker** [comment]
@Zaid-Ajaj Ok, I understand, so it will be composed of `Task`s rather than `class`es. Thank you!
