### ISSUE TITLE
Provide a way to get all stacks from `stack ls`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3620]
We recently made a change to improve the performance of `stack ls` - but as part of that also changed the correctness of `stack ls -a` to not report all stacks if there are more than 300. A warning is issued when there are more - but it does not indicate what users can do to actually get all stacks. 

We should:
1. Provide a way to actually get all stacks
2. Possibly make that the default again for `stack ls -a`
3. If we do continue to limit by default, include enough information in warning for users to actually get all stacks (or limit query by project If necessary). 

Cross ref [slack discussion](https://pulumi-community.slack.com/archives/C84L4E3N1/p1575851212127100?thread_ts=1575805569.114600&channel=C84L4E3N1&message_ts=1575851212.127100). 

Other notes:

> I would recommend adding the 300 Max to the documentation so users will not rely on it (as we did) with their automation tools.
> if i use a tag filter with the CLI will it still hide results? Cause i still see the warning. Where as if i use the project  filter i don't

**Comment by jasminen** [comment]
@lukehoban Thanks for addressing this issue! 

I did some tests and indeed filtering by tag will hide some results even if result set size is < 300 . My guess is that all stacks are returned and then filtered by tag - which hits the Max 300 limit.
