### ISSUE TITLE
upgrading to npm package @pulumi/azure@1.7.0 causes an error

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi#3621]
Hi,

Today, I updated to last @pulumi/azure version, the 1.7.0.
The @pulumi/pulumi version (1.6.1) was already up-to-date.
Since that, I got this error:
``` 
azure:network:Subnet (snet-forge-jenkins-agents-sandbox):
    error: azure:network/subnet:Subnet resource 'snet-forge-jenkins-agents-sandbox' has a problem: "enforce_private_link_endpoint_network_policies": conflicts with enforce_private_link_service_network_policies
```
I have totally no idea of what it means, because this policy doesn't exist in azure (I guess).

Downgrading to @pulumi/azure version 1.6.0 fix it.

Best regards

**Comment by pgavlin** [comment]
@mikhailshilkov, can you take a look at this?

**Comment by mikhailshilkov** [comment]
I got it reproduced. Apparently, we handle this in somewhat upexpected way:

```
"enforce_private_link_endpoint_network_policies": {
	Type:          schema.TypeBool,
	Optional:      true,
	ConflictsWith: []string{"enforce_private_link_service_network_policies"},
	Default:       false,
},

"enforce_private_link_service_network_policies": {
	Type:          schema.TypeBool,
	Optional:      true,
	ConflictsWith: []string{"enforce_private_link_endpoint_network_policies"},
	Default:       false,
},
```

Any combination of `undefined`/`true`/`false` causes an error for me.

To be continued...

**Comment by mikhailshilkov** [comment]
@boillodmanuel A workaround to keep using 1.7.0 is to set the following on your subnet resources:

```
  enforcePrivateLinkEndpointNetworkPolicies: false,
```

A proper fix will require a new release of the Azure provider.
