### ISSUE TITLE
[QUESTION] error 401: Authenticate user against Active Directory?

### ISSUE THREAD

**Issue by scheung38** [pulumi/pulumi#3634]
Win 10, using existing examples from /templates/aws-py-resources

(.env) pulumi up

error: [401] 

Cannot connect
The Proxy received an invalid response

Authenticate user against Active Directory?

My AWS configuration is active and I am able to deploy via normal Terraform route

Does this mean I am denied access from corporate firewall?

**Comment by leezen** [comment]
This looks like a client error on your end as you said, so closing.
