### ISSUE TITLE
Default value for optional config values in pulumi python

### ISSUE THREAD

**Issue by Panaetius** [pulumi/pulumi#3637]
Currently, the pulumi python `Config` object has methods for getting optional values, such as `.get()`, `.get_bool()` etc. Those methods return a value or `None` if no value was found`.

It'd be a great addition if it'd be possible to pass a default value for those methods, to make code more readable. Especially in the case of `get_bool` and a default value of `True`

Currently (example where the default value is `True`):
```
enabled = config.get_bool('enabled')

if enabled or enabled is None:
    ...
```

Proposed:
```
if config.get_bool('enabled', True):
    ...
```

In many cases, a default value can be handled by doing something like

```
name = config.get('name') or 'default_name'
```

but there are many things in python that are falsy that could erroneously lead to a default value to be supplied even if a value was supplied ( like setting 'name' to '' in the above example).

This could potentially also print that a default value was used as a warning, if necessary.

It's a pretty small change but would improve quality of life and readability of the code and potentially prevent bugs from happening.

**Comment by justinvp** [comment]
Fixed by #10344
