### ISSUE TITLE
Provide a way for components to mark that they are asynchronously-constructed

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#3646]
Relevant internal slack link: https://pulumi.slack.com/archives/G9Y1SA4TF/p1576097108018500

As part of https://github.com/pulumi/pulumi/issues/3528 we need to introduce the concept of an asynchronously constructed component (specifically a VPC).  This is currently problematic because:

1. user may create a VPC (which is suppsoed to created subnets/gateways/etc.)
2. users 'dependsOn' this Vpc in some other resource.

Today, we determine the set of dependent custom resources based on the point in time the resource was depended-on.  However, if VPC now constructs itself asynchronously, that point-in-time could very likely be empty or incomplete.  

We propose that a component can tell pulumi.ComponentResource that it constructs itself asynchronously.  IN that case, if someone depends-on that component, it will have to wait until the async-construction is done (signalled by calling .registerOutputs).  For components that are not-async, then they will be considered done at the end of the constructor and will see no change in behavior.

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi/pull/3676

**Comment by boillodmanuel** [comment]
Hello @CyrusNajmabadi,

I'm looking for this feature in official doc and didn't found anything. Is this documented anywhere (other than in PR)
