### ISSUE TITLE
Reusing / Abstracting Pulumi Projects

### ISSUE THREAD

**Issue by zombor** [pulumi/pulumi#3647]
Hi, I'm interested in using pulumi for deploying applications to kubernetes, basically like the example (https://github.com/pulumi/examples/blob/master/kubernetes-ts-exposed-deployment/index.ts). However, I want to deploy an *arbitrary* application using a common pulumi program where the user of the deployed app can configure different things about their deployment. Things like dns name, databases, docker image name, etc. I have some conceptual struggles in how to implement this for many different projects/users, though.

I'd like users to be able to do something like `pulumi new` to make their `Pulumi.yaml` and then do as little work as possible to import/use the pulumi program that I wrote. This is fairly easy with Go, as the go language provider will look for a binary in `$PATH` with the same name as the project name. From what I can tell this is the only language provider that does this and since there's no Go k8s support yet, I'm using typescript.

Are there any common patterns I can take advantage of that I'm not thinking of?

**Comment by brandonkal** [comment]
This is how I would approach things:
1. Don't try to share a project per say. Instead, share the code as a normal module. In JavaScript, that means via an npm server. The user's index.ts file can be as simple as:
```
import  'your-module'
```
2. Write a simple interactive shell script that: (1) ensures pulumi is installed, (2) ensures any other dependencies (i.e. helm and helm repos, etc) are installed, (3) prompts for and writes config.
3. If it is something that is reusable on its own, define a pulumi.CustomResource which takes parameters and creates child objects.
4. Understand that projects don't hold config. Stacks do.

**Comment by ringods** [comment]
@leezen This is indeed a good question and should be looked into a bit further. In regular NodeJS, one can run scripts without a local Node project setup via `npx` or [`ynpx`](https://www.npmjs.com/package/ynpx) (the yarn equivalent). 

If we could bundle a reusable infrastructure component including the Pulumi project file, I envision a user would not need to have a local Node project setup (`package.json`, dependencies, ...). Login on the backend, create the stack and off we are.

**Comment by brandonkal** [comment]
@leezen In that case, I'd highly recommend using Deno. I have an issue about Deno runtime support in Pulumi.

**Comment by brandonkal** [comment]
Oops. Meant to ping @ringods

**Comment by ringods** [comment]
@brandonkal you mean this?

https://deno.land/

I don't understand why this would need another runtime all of a sudden. Can you elaborate on your thinking?

**Comment by brandonkal** [comment]
Yes. You can see my other issue on Deno support. A Deno runtime is required as currently there is only a Node runtime.

**Comment by mikhailshilkov** [comment]
I feel like with introduction of Go support for k8s, binary option for all compiled languages, automation API and multi-language packages, this issue must have an answer in that space of new possibilities. I'm not _exactly_ sure what the proposed solution was here, but given lack of activity for 2+ years I'll take the liberty to close the issue.
