### ISSUE TITLE
Importing resources and provider only options

### ISSUE THREAD

**Issue by cristi-** [pulumi/pulumi#3661]
Hi,

I'm trying to move a s3 bucket between two stacks. Based on the docs, I copied the code that creates the s3 bucket and added the extra `{"import": ID}` option. There seems to be a problem with options provided at the creation time, in this case `bucketPrefix`.

How to reproduce:

Create a s3 bucket in a stack:
```
new aws.s3.Bucket("test", { bucketPrefix: "test" })
```

Import the bucket in a new stack:
```
new aws.s3.Bucket("test", { bucketPrefix: "test" }, {
    import: "test20191214172206098400000001"
})
```

The error is: 
```
 =   └─ aws:s3:Bucket     test              import     [diff: +bucketPrefix]; 1 warning

Diagnostics:
  aws:s3:Bucket (test):
    warning: inputs to import do not match the existing resource; importing this resource will fail
```

Adding ` ignoreChanges: ["bucketPrefix"]` allows the import to continue, but the resource will be recreated.

Thanks!

**Comment by leezen** [comment]
A lot has changed in the import functionality since the time this issue was filed. I believe the `pulumi import` command should address this given it provides the necessary inputs via read.
