### ISSUE TITLE
Slow pulumi preview with invoke

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi#3665]
While working on https://github.com/pulumi/pulumi-kubernetes/pull/908, I found that `pulumi preview` is taking a very long time (~3 mins) on the Istio integration test. 

I'm not sure what's causing the slowness, but I am passing very large YAML files (15k+ LoC) through the invoke, and returning similarly large data structures to the SDK in case that's relevant.

I've attached relevant debug output from running this command:
`pulumi preview --profiling=profile --tracing="file:./preview.trace" --logtostderr -v=9 2> out.txt`

[debug_output.zip](https://github.com/pulumi/pulumi/files/3969111/debug_output.zip)

/cc @pgavlin @lukehoban

**Comment by lukehoban** [comment]
We saw another trace from another user that had similar symptoms.  There is a >9min gap between a ReadResource (for a stackreference) and the next RegisterResource, where nothing except three RenewLease operations occurs.  

That trace has a similar characteristic that a very large (~100k) payload is being returned from the ReadResource.  But the operation appears to complete in 100ms or so - and there is no clear work being down for the following 9 minutes.

Here's a snippet of the trace - although it's hard to tell from this - the time between the start of the first operation shown and the end of the last is ~9mins:
<img width="972" alt="Screen Shot 2019-12-26 at 4 21 26 PM" src="https://user-images.githubusercontent.com/223467/71494430-1a050580-27fc-11ea-9c1c-324f0d7f3fdc.png">

**Comment by shaunhellar** [comment]
@lukehoban We confirmed it was indeed from having a stack reference read an exceptionally large output. After fixing the export in the upstream dependency our `pulumi preview/up` execution times went from ~15 minutes back down to <1 min.

**Comment by pgavlin** [comment]
Removing the P1 label for now as we do have a workaround. @lukehoban I wonder if this was fixed with the `Output<>` changes--can you try your repro?

**Comment by lukehoban** [comment]
I don’t have any repro myself - but I’m 99% sure this was fixed by the output changes - so closing out for now. If anyone still sees sever slowness related to invokes or stack references though, please do open a new issue.
