### ISSUE TITLE
Please make Pulumi dotnet sdk Deployment.Instance setter public

### ISSUE THREAD

**Issue by lonegunmanb** [pulumi/pulumi#3672]
Hi Pulumi,

Words cannot express how excited i was when I found you guy has supported dotnet sdk! GREAT JOB!

I've been waiting so long for a tdd style IaC solution until I found pulumi. I cannot wait to try pulumi dotnet sdk so I can use xunit to drive my IaC code without actually run them. What I want is write some unit test code to assert what my resources should look like, let it fail, then implement the requirement by fix the test, and these tests should be finished in seconds. However, I found an Exception "Trying to acquire Deployment.Instance before 'Run' was called." raised, because Deployment.Instance is null when I run my xunit test. I found Deployment.Instance is an interface type so I tried implementing a dummy IDepoyment and set to Deployment.Instance, hope it can be a walkaround. Unfortunately, Deployment.Instance's setter is internal, so I cannot inject my dummy easily. Could you please make it public? Or could you give me some advice on how to do TDD on pulumi development? Many Thanks!

**Comment by lonegunmanb** [comment]
After inject my dummy IDeployment via reflection, I found test still failed because in Resource's constructor the code try converting Deployment.Instance to IDeploymentInternal which is an internal interface so I cannot implement it.
Any advice would be appreciated, and again, THANK YOU FOR YOUR GREAT JOB!

**Comment by mikhailshilkov** [comment]
@lonegunmanb Thank you for the kind words!

I have a pending issue to figure out the testing story in https://github.com/pulumi/pulumi/issues/3633

Do you have an example of the tests that you are trying to write, so that we could work together to make them possible?

**Comment by lonegunmanb** [comment]
Thank you for your reply! Let's say we have a dummy deployment implementation already, and this dummy deployment (or actual deployment as well) will store every resource we new into a generic typed collection named "ResourceRepo", and we can access resources by Resource<T> where T : Resource method.  The code below cannot be compiled for now, but I think if we can combine linq, generic IQueryable, Terraform Sentinel like policy base check, and speed of unit test which can finish hundreds thousands of checks in seconds, it'll be a game changer.
`public class NetworkTest
    {
        public NetworkTest()
        {
            
        }

        public const string TenancyId = "TenancyId";
        public static readonly string[] allowed_zones = new []
        {
            "us-east-1a",
            "us-east-1b",
            "us-east-1c",
            "us-east-1d",
            "us-east-1e",
            "us-east-1f",
        };

        [Fact]
        public void NetworkValidationTest()
        {
            var network = new Infra.Network();
            Infra.ResourceRepo.Resource<Pulumi.Aws.Ec2.Vpc>().ToList().ForEach(Valid);
            Assert.True(Infra.ResourceRepo.Resource<Pulumi.Aws.Ec2.Subnet>().All(subnet=>Valid(subnet)));

            var privateSubnetWithInternetGateway = from privateSubnet in Infra.ResourceRepo.Resource<Subnet>()
                where IsPrivate(privateSubnet)
                join association in Infra.ResourceRepo.Resource<RouteTableAssociation>() on privateSubnet.Id equals
                    association.SubnetId
                join internetGateway in Infra.ResourceRepo.Resource<InternetGateway>() on association.GatewayId equals
                    internetGateway.Id
                select privateSubnet;
            Assert.False(privateSubnetWithInternetGateway.Any());
        }

        private static bool IsPrivate(Subnet subnet)
        {
            return subnet.Tags["private"] == "true";
        }

        private static void Valid(Vpc vpc)
        {
            Assert.True(vpc.EnableDnsHostnames, "vpc should enable DnsHostNames");
            Assert.True(vpc.Tags.ContainsKey(TenancyId) && !string.IsNullOrEmpty(vpc.Tags[TenancyId]), "vpc should has TenancyId tag");
        }

        private static Valid(Subnet subnet)
        {
            return InAllowedZone(subnet) && ConnectedToVpc(subnet);
        }

        private static bool ConnectedToVpc(Subnet subnet)
        {
            return Infra.ResourceRepo.Resource<Vpc>().Select(vpc=>vpc.Id).Contains(subnet.VpcId);
        }

        private static void InAllowedZone(Subnet subnet)
        {
            return allowed_zones.Contains(subnet.AvailabilityZone);
        }
    }`

We can write two kinds of tests, the unit tests don't need runtime information, we can run unit tests without using real deployment or invoking cloud api to query datasource; and we run integration tests like we run terraform plan, which will query datasource.

Furthermore, maybe we can find a way to define state drift policy, we can constrain which resources cannot been updated, or deleted during apply new code on current state.

**Comment by mikhailshilkov** [comment]
@lonegunmanb I would appreciate your feedback https://github.com/pulumi/pulumi/pull/3696 and whether it would solve your needs

**Comment by lonegunmanb** [comment]
I think we're almost there with a mock TStack. What I want is write test code in [https://www.pulumi.com/docs/guides/crossguard/](Pulumi CrossGuard) way and in linq style code. I'll study your pr to see what I can do with a mock stack. Thanks a lot!

**Comment by lonegunmanb** [comment]
yes, your TestResult is exactly what I want! I'll try to finish my unit test trial after your pr's been merged into release. Great job, thanks!
