### ISSUE TITLE
Support also `--target-childs` for `pulumi destroy`

### ISSUE THREAD

**Issue by Dominik-K** [pulumi/pulumi#3684]
We're using the `parent` option more & more. As such, targeted deletion of the parent currently lacks easiness as implicitly [targeting childs is not supported](https://github.com/pulumi/pulumi/pull/3244#issue-318531739), yet.

**Comment by pgavlin** [comment]
I believe that @komalali implemented this with https://github.com/pulumi/pulumi/pull/7605.
