### ISSUE TITLE
Possible to manage existence of user accounts in azure active directory? 

### ISSUE THREAD

**Issue by breathe** [pulumi/pulumi#3689]
Would love to be able to define the set of users which should exist in an azure active directory instance via pulumi -- is this possible somehow?

**Comment by stack72** [comment]
Hi @breathe 

Yes this is possible. You can use the https://github.com/pulumi/pulumi-azuread package to do this

https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azuread/#User

Paul
