### ISSUE TITLE
Trouble importing aws.elasticbeanstalk.ConfigurationTemplate

### ISSUE THREAD

**Issue by jandom** [pulumi/pulumi#3695]
Hi there guys, 

Really love what you're doing here! Used pulumi to overhaul our infrastructure over the last few weeks. I've had to import/adopt a large number of resources, so this is not my first rodeo but seeing some unexpected behavior with this resource type. 

First of all, if I don't import but just create, everything works

```typescript
const template = new aws.elasticbeanstalk.ConfigurationTemplate(
  "template", {
    application: "symfony73",
    solutionStackName: "64bit Amazon Linux 2018.03 v2.9.1 running PHP 7.3",
  },
  {
    // import: "testing",
});
```

When I uncomment and import, I see a strange error

```
Diagnostics:
  aws:elasticbeanstalk:ConfigurationTemplate (template):
    error: Preview failed: refreshing urn:pulumi:testing::backend::aws:elasticbeanstalk/configurationTemplate:ConfigurationTemplate::template: InvalidParameter: 1 validation error(s) found.
    - minimum field size of 1, DescribeConfigurationSettingsInput.ApplicationName.
 
  pulumi:pulumi:Stack (backend-testing):
    error: preview failed
```

But the ApplicationName passed in Args was valid for creation. 

The imported config exists, so it's not that my identifier was wrong etc
```
$ aws elasticbeanstalk describe-applications | grep "ConfigurationTemplates" -A4
            "ConfigurationTemplates": [
                "production", 
                "testing", 
                "staging"
            ], 

```

**Comment by stack72** [comment]
Hi @jandom 

Unfortunately, beanstalk configuration templates are not supported for import or as data sources at this time

This is because the underlying [Terraform Provider](https://github.com/terraform-providers/terraform-provider-aws) doesn't support this as of now. 

This would need to be supported in the upstream provider before this can be supported in Pulumi :(

Sorry about this

Paul

**Comment by jandom** [comment]
Hi @stack72 

Yeah, you're absolutely right – just had a look at the sources myself. Thank you for answering my question, I think this is resolved now!
