### ISSUE TITLE
[QUESTION] problem getting started with basic AWS-TypeScript: 

### ISSUE THREAD

**Issue by scheung38** [pulumi/pulumi#3698]
Mac OS: Catalina
Node.js:  v10.16.0

Already have ~/.aws/credential

[default]
aws_access_key_id =  <Access_Key_ID>
aws_secret_access_key = <MySecret_Access_Key>  
region = eu-west-2

pulumi new aws-typescript

pulumi up            
Previewing update (dev):

     Type                 Name                       Plan     Info
     pulumi:pulumi:Stack  aws-typescript-tilson-dev            
     └─ aws:s3:Bucket     my-bucket                           1 error
 
Diagnostics:
  aws:s3:Bucket (my-bucket):
    error: could not validate provider configuration: 1 error occurred:
    	* : invalid or unknown key: default

Previously I was able to login to AWS using Terraform and deploy? Why Pulumi tells me this error?  But after these were created, these IDs were deleted from AWS as advised, but if deleted then what's stored in .aws/credentials are no longer valid?

**Comment by lukehoban** [comment]
What does `pulumi config` show?  From the error it sounds like perhaps you have set `aws:default` to something - but that is not a valid provider configuration input for the `AWS` provider.

**Comment by stack72** [comment]
I am going to close this out - it's unanswered since December 2019 

If this is still a problem please do let us know and we can reopen it

Paul

**Comment by CanRau** [comment]
Good to know, didn't realize I couldn't use a provider namespace for additional custom config that felt like it belonged more in there but now that I think about it I get it 😅
