### ISSUE TITLE
Add Pulumi to MacPorts

### ISSUE THREAD

**Issue by bgdnlp** [pulumi/pulumi#3699]
Have you considered creating a Pulumi port for MacPorts?

The manual installation works fine, it doesn't get much easier than that. I'm talking about download -> untar, not even the shell pipe. And Pulumi will warn about new versions being available. It would just be nice-to-have for those of us that use MacPorts instead of Homebrew.

**Comment by leezen** [comment]
Closing as we do have a Pulumi port now https://ports.macports.org/port/pulumi/ and include this as an option in our installation guide.
