### ISSUE TITLE
Modelling multiple resource states in a stack and easily switching between them

### ISSUE THREAD

**Issue by damianh** [pulumi/pulumi#3703]
I'll try to explain what I mean with a use case and you can tell me if I am completely wrong or not :)

- I have a service that has it's own stack
- The service has three different modes - lets say `online`, `testing` and `offline`.
- In offline mode, the lambdas are throttled by setting max concurrency of zero, the ALB is configured to return `503` for all requests and the database is put to single user mode.
- In testing mode the database is in standard mode, the lambdas have the max concurrency set to non-zero but the ALB still returns `503`.
- In online mode, the ALBs now forward traffic.

In my mind, I would like to be able to model these modes in pulumi and select which mode to apply when doing a `pulumi up`. The best I can come up with at the moment is to do something like this where I use a config value...

```
pulumi config set mode offline
pulumi up -y
... run migrations etc
pulumi config set mode testing
pulumi up -y
... run an acceptance test
pulumi config set mode online
pulumi up -y
```

(In the above I am missing saving the config change to version control so if it fails for any reason it's not optimal.)

... that I uses as a switch:

```csharp
var mode = config.Require("mode");

switch (accessKey)
{
    case "offline":
        GoOffline();
    case "online":
        GoOnline();
    //etc...
}
```

Instead of patching the config I _think_ prefer to be able to do `pulumi up --mode=offline`.

Extrapolating this I can envisage more complicated modes such as canary deployments, blue-green etc. I understand that this is moving much more into the orchestration space.

Penny for your thoughts on this. Cheers.

**Comment by lukehoban** [comment]
I might be misunderstanding the full scenario - but to first approximation each of these “modes” should be a “stack”.  

As discussed in https://www.pulumi.com/docs/intro/concepts/organizing-stacks-projects/, the general Pulumi model is that a project is a single codebase, and a stack is an instance of that codebase with its own config and isolated resources under management.  In your case, I would expect you to have 3 stacks for this project, each with the `mode` config variable set differently. Each stacks config could be source controlled, and you can switch between stacks or `pulumi up -s mystack`. 

I think the difference in your mode is you are trying to do all three steps in one stack. I’m not sure how that could work, as the desired states of these three are different, so you can’t (easily) describe them desired state for all three at once. 

Note that if you want to promote changes through your three environments, you can definitely do that by updating each environment in sequence (either manually or via CI). It is also common to adding stacks to certain branches in source control and have CI drive updates to the corresponding stack when new code is pushed to a branch, so you could drive this promotion via CI.

**Comment by damianh** [comment]
The Automation API allows me to do what want here so I'm going to close this issue. Cheers.
