### ISSUE TITLE
Product wise billing

### ISSUE THREAD

**Issue by nsisodiya** [pulumi/pulumi#3709]
In our old AWS account, we have hosted multiple products. I tried my best but failed to generate product-wise billing. for example - If the total bill of AWS is $5000 USD then I want to see something like this
Product 1 = $3000
Product 2 = $1500
Product 3 = $500

May you guide us for creating something like this using tags etc.
I am sure, this will be much easy with Pulumi.

**Comment by leezen** [comment]
You can certainly tag your resources using Pulumi (usually by specifying the `tags` attribute in the resource) and then use AWS's [cost allocation tags](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html) to see where your costs are coming from.
