### ISSUE TITLE
Feature Request: add a retry Resource Option

### ISSUE THREAD

**Issue by bincyber** [pulumi/pulumi#3715]
##### ISSUE TYPE
- Feature Request

##### SUMMARY

Add a [resource option](https://www.pulumi.com/docs/intro/concepts/programming-model/#resourceoptions) to automatically retry provisioning a resource:

```python
account_id = aws.get_caller_identity().account_id

iam_role = aws.iam.Role(
    resource_name="vpc-admin",
    description='IAM Role for VPC Administration',
    path='/',
    force_detach_policies=True,
    assume_role_policy={
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "AllowAccountAssumeRole",
            "Action": "sts:AssumeRole",
            "Principal": {
                "AWS": f"arn:aws:iam::{account_id}:root"
            },
            "Effect": "Allow"
        }]
    }
)

iam_role_policy_attachment = aws.iam.RolePolicyAttachment(
    resource_name="vpc-admin-policy-attachment",
    role=iam_role.id,
    policy_arn="arn:aws:iam::aws:policy/AmazonVPCFullAccess"
)

iam_role_provider = aws.Provider(
    resource_name='vpc-admin-provider',
    assume_role={
        "role_arn": iam_role.arn,
        "session_name": "VpcAdmin"
    },
    opts=pulumi.ResourceOptions(
        depends_on=[
            iam_role_policy_attachment
        ]
    )
)

aws.ec2.Vpc(
    resource_name="test-vpc",
    cidr_block="10.100.0.0/16",
    enable_dns_hostnames=True,
    enable_dns_support=True,
    tags={
        "Name": "test-vpc",
        "CreatedBy": "vpc-admin-provider"
    },
    opts=pulumi.ResourceOptions(
        parent=iam_role_provider,
        provider=iam_role_provider,
        retries={
            "max_attempts": 10,
            "delay": 5
        }
    )
)
```

The above example would attempt to provision the AWS VPC up to 10 times with a delay of 5 seconds between each try.

Without the retry, the above example would fail because IAM is eventually consistent. It's possible to work around this (see https://github.com/pulumi/pulumi-aws/issues/673), however it would be easier on the user if Pulumi could retry provisioning the resource.

**Comment by mastoj** [comment]
Why was this closed? I'm interested in the exact same thing.

**Comment by onedr0p** [comment]
I am noticing on Digital Ocean that creating a LB often times returns a 500 error. I am not sure what is causing it but having a retry option in the `CustomResourceOptions` would be great. Maybe we need to open a new issue since the OP here decided it is not needed for his usecase.

**Comment by tksrc** [comment]
I am also interested in this. Can we please re-open and track?

**Comment by gordonbondon** [comment]
I was also interested in this, so open a new issue here https://github.com/pulumi/pulumi/issues/7932

**Comment by palladius** [comment]
Also interested.

**Comment by esciullo** [comment]
Interested

**Comment by mickdelaney** [comment]
Interested
