### ISSUE TITLE
`pulumi preview --diff --json` doesn't display diff 

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi#3717]
This has been discussed here https://pulumi-community.slack.com/archives/C84L4E3N1/p1575398932450500

Short summary:
I want to get a json diff when importing an existing resource.
Running `pulumi preview --diff` gives me a non-json diff in a pulumi proprietary format. When I run `pulumi preview --diff --json` I get no diff at all which appears like a bug.

**Comment by htthao** [comment]
I am also running into this problem. Do you have any update on it?

**Comment by pgavlin** [comment]
@geekflyer when you refer to a JSON diff, are you referring to a particular format (e.g. [JSON patch](https://tools.ietf.org/html/rfc6902))?

**Comment by mikhailshilkov** [comment]
`pulumi preview --diff --json` seems to work now, it gives me JSON of this format:

```
{
    "config": ...,
    "steps": [
      ...
    ],
    "diagnostics": ...,
    "duration": ...,
    "changeSummary": ...
}
```

Unfortunately, the link to the slack thread doesn't work anymore.

I'll go ahead and close the bug as resolved, feel free to file a new issue to track improvements to this command vs. its current state.
