### ISSUE TITLE
Add DotNet support to the pulumi/actions GitHub action docker container

### ISSUE THREAD

**Issue by tndata** [pulumi/pulumi#3723]
when I try to build my C# pulumi project in Github using GitHub actions, I get this error

Diagnostics:
  pulumi:pulumi:Stack (PulumiAppServiceContainer-githubaction):
    error: could not find `dotnet` on the $PATH: exec: "dotnet": executable file not found in $PATH

I am using this image - uses: docker://pulumi/actions

**Comment by lukehoban** [comment]
This was fixed recently in https://github.com/pulumi/pulumi/pull/3616, but I believe we have not yet published the updated images which include that fix. That is tracked in https://github.com/pulumi/pulumi/issues/3701.

**Comment by lukehoban** [comment]
I’ll actually close this out as the work is done and the remaining release task is already tracked in #3701.
