### ISSUE TITLE
Feature: Update go-cloud library to enable Azure filestate backend to specify different Azure Storage Domain

### ISSUE THREAD

**Issue by Strife96** [pulumi/pulumi#3724]
Currently, Pulumi's cloud filestate backends use the go-cloud library's default blob driver to handle blob storage connection, reads/writes, etc. Recently, the go-cloud library's default Azure blob driver gained the ability to specify an Azure domain (i.e. "blob.core.windows.net", "blob.core.usgovcloudapi.net", etc.) using an environment variable. This enables users to access blob accounts in any Azure domain (Government, German, China, custom, etc.) instead of being restricted to the public Azure domain. 

Unfortunately, Pulumi uses its own fork of go-cloud that does not yet implement this feature. It would be nice to be able to store Pulumi stack states in blob storage backends from any Azure Cloud domain, instead of being forced to use a public Azure storage account. 

The Pulumi Azure filestate backend could add this feature with little effort if the pulumi/go-cloud fork is updated to a more recent commit that includes this change (earliest being https://github.com/google/go-cloud/commit/055da8b4f13288de2a3a2bc8ffc4e82e2b90dd0a).

**Comment by glennmusa** [comment]
@Strife96 I had success configuring a backend in Azure Government cloud by specifying the `AZURE_STORAGE_DOMAIN` environment variable.

```bash
export AZURE_STORAGE_ACCOUNT={your storage account name}
export AZURE_STORAGE_DOMAIN=blob.core.usgovcloud.api.net
export AZURE_STORAGE_KEY={your storage account key}
pulumi login azblob://{your state container}
```

From the fork here: https://github.com/pulumi/go-cloud/blob/4551da96f976dca635364e09225d86bd3c21ffbe/blob/azureblob/azureblob.go#L239-L242

```go
// StorageDomain is an Azure Cloud Environment domain name to target
// (i.e. blob.core.windows.net, blob.core.govcloudapi.net, blob.core.chinacloudapi.cn).
// It is read from the AZURE_STORAGE_DOMAIN environment variable.
type StorageDomain string
```

**Comment by stack72** [comment]
I am going to close this out - we recently migrated to a newer version of go-cloud https://github.com/pulumi/pulumi/pull/5138 and away from the pulumi fork
