### ISSUE TITLE
Issue with 1.8.1 pulumi/actions docker image

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3727]
From https://pulumi-community.slack.com/archives/CDE799L1M/p1578505547064500: 

> I believe the Pulumi Actions v1.8.1/latest tag in docker (released ~25min ago) is broken for Python.  Using it with github actions results in a No module named pulumi error, but using the v1.7.1 tagged actions container works just fine.  Unrelated question: where's the right place to bring up issues with actions/ci in general?  Opening up an issue in the pulumi/pulumi repo didn't seem quite right...

**Comment by pgavlin** [comment]
This should now be fixed.

**Comment by chrsmith** [comment]
Thanks Pat!
