### ISSUE TITLE
Considering dropping support for Node 8

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3736]
Pulumi officially support "Node.js version 8 and later" (https://www.pulumi.com/docs/intro/languages/javascript/).  However, Node 8 was EOL as of 12/31/2019.  And we are seeing some dependencies starting to drop support, and in some cases actively block usage on Node <10.

We should consider if/when to officially change support Node version to 10 and later.

As part of this, we should move our min-version testing to Node 10 instead of Node 8.

**Comment by leezen** [comment]
Marking as P1 to have this before pushing out a beta release of 2.0

**Comment by lukehoban** [comment]
I believe we should decouple this from `2.0` and just continue to say that Pulum is supported on Maintenance, Current and Active LTS versions of Node.  We should drop Node 8 from our CI testing across the board, and add Node 13 now, and Node 14 in April when it is released.

**Comment by leezen** [comment]
Created a separate issue in the docs repo to update the text. I'll leave this open to track removing Node 8 from CI and add Node 13.

**Comment by leezen** [comment]
Since we're decoupling from 2.0, I'm going to punt this back into the backlog.
