### ISSUE TITLE
Move template tests to templates repo

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3744]
We currently test all our templates in this repo's CI.  These tests are somewhat slow, are the only place we directly depend on external cloud providers, and generally catch a class of issues that aren't related to `pulumi/pulumi` itself.

We should look into moving these tests to run nightly in `pulumi/templates` instead - which is a closer match for their coverage.

**Comment by stack72** [comment]
I can move these easily enough as I have the credentials for them
