### ISSUE TITLE
[.NET] Vault Provider ProviderAuthLoginsArgs Parameters error "auth_login.0.parameters: should be a map"

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi#3746]
Hello,

I am trying to create a vault provider using the ProviderAuthLoginsArgs so I can authenticate using AppRole. I have added the parameters as an InputMap but each time i run up it gives me the error "auth_login.0.parameters: should be a map". I was unable to find good vault examples that were using a custom provider like this and since dotnet is so new I am not sure if I am just configuring it incorrectly or if this is a bug.

```cs
var vaultProvider = new Provider("vault",
  new Pulumi.Vault.ProviderArgs
  {
    Address = config.Require("vaultEndpoint"),
    AuthLogins = new InputList<ProviderAuthLoginsArgs>
    {
      new ProviderAuthLoginsArgs
      {
        Path = $"auth/approle/role/{config.Require("vaultAppRoleName")}/login",
        Parameters = new InputMap<string>
        {
          {"role_id", config.Require("vaultAppRoleId")},
          {"secret_id", config.RequireSecret("vaultAppRoleSecretId")}
        },
      }
    }
  });
```
cli verson: v1.8.1

dotnet nuget versions:
pulumi: 1.9.0-preview-multilang.1578185806
pulumi.vault: 1.7.0-preview-alpha.1578306348

**Comment by mikhailshilkov** [comment]
I reproduced the same error with .NET, while TS version works fine.

It looks like our serialization doesn't work properly and sends this map as a string. Here is a value from the log for .NET:

```
(inputs=map[address:{bla} authLogins:{[ { "path": "auth/approle/role/bla2/login",
"parameters": "{ \"4dabf18193072939515e22adb298388d\": \"1b47061264138c4ac30d75fd1eb44270\", \"value\": { \"role_id\": \"bla3\", \"secret_id\": \"bla4\" } }" } ]}
maxLeaseTtlSeconds:{20} maxRetries:{2}])
```
while TS has
```
(inputs=map[address:{bla} authLogins:{&{{[{"path":"auth/approle/role/bla2/login",
"parameters":{"role_id":"bla3","secret_id":"bla4"}}]}}}
maxLeaseTtlSeconds:{20} maxRetries:{2}])
```
@CyrusNajmabadi could you check?

**Comment by CyrusNajmabadi** [comment]
Notes as i go along.

TS does this:
```ts
inputs["authLogins"] = pulumi.output(args ? args.authLogins : undefined).apply(JSON.stringify);
```

This takes `authLogins` (Which is `pulumi.Input<pulumi.Input<inputs.ProviderAuthLogin>[]>;`) and should json stringify it.  

in .net we have: 

```
        [Input("authLogins", json: true)]
        private InputList<Inputs.ProviderAuthLoginsArgs>? _authLogins;
```

the `json: true` is supposed to get us to do the same.  investigating.

**Comment by mikhailshilkov** [comment]
The fix has been merged to `pulumi-vault` today (https://github.com/pulumi/pulumi-vault/pull/25/files#diff-9d140050d61d8a86799b4f72e8cccc0eR148) and will be included into the next release
