### ISSUE TITLE
pulumi command hangs when non existing dir passed as param for `--cwd`

### ISSUE THREAD

**Issue by matkarasiewicz** [pulumi/pulumi#3754]
Calling pulumi command hangs when directory passed as a value to `--cwd` param doesn't exist.

Example:
`pulumi --cwd non-existing-dir version`

Tested on :
v1.8.1 MacOs/Linux/Windows

Expected behavior:
Error notification that passed dir doesn't exist.

**Comment by stack72** [comment]
Hi @matkarasiewicz 

I am sorry it took so long to get back to you on this issue. It looks like this has been fixed up 

I am using the latest Pulumi

```
▶ pulumi --cwd /tmp/nothing up
error: chdir /tmp/nothing: no such file or directory
```

Paul
