### ISSUE TITLE
Update Policy gestures to support configuration

### ISSUE THREAD

**Issue by ekrengel** [pulumi/pulumi#3756]
Related to: https://github.com/pulumi/pulumi-policy/issues/91

We will be improving the UI experience to support configuration. The CLI now allows you to enable/disable Policy Packs, so the CLI will also need to be able to support configuring them.

**Comment by justinvp** [comment]
> The CLI now allows you to enable/disable Policy Packs, so the CLI will also need to be able to support configuring them.

@ekrengel, @sean1588, what changes are we planning to make to the commands?

**Comment by ekrengel** [comment]
I think we just have one additional need which is that enabling a PP should check if config is required & support passing in config / checking that its valid. Checking its valid is not a hard requirement thought bc the svc does this.
