### ISSUE TITLE
Add test coverage for all supported Secrets Providers

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3761]
We support `awskms`, `azurekeyvault`, `gcpkms` and `hashivault` secrets providers today.  We should ensure all of these have robust test coverage.

**Comment by jaxxstorm** [comment]
The first order of business here was to verify all these secrets providers worked as expected, which I've done - will add the set up examples either to the docs or pulumi/examples depending on where we think it's best.

Secondly, it's time to add test coverage. Some unit tests would be a good start, will start looking at what we need to do there.

**Comment by lukehoban** [comment]
> will add the set up examples either to the docs or pulumi/examples depending on where we think it's best

As a first step, let’s add to examples repo. 

We could then look at adding to or expanding https://www.pulumi.com/docs/intro/concepts/config/#available-encryption-providers.

**Comment by stack72** [comment]
Moving this to 0.34, this isn't urgent and a lot of the initial work has been completed - it just needs examples now :)

**Comment by jaxxstorm** [comment]
I've added these in the associated PR, but currently they will be skipped. I've opened an associated issue privately to discuss how we manage and provision these dependencies.

**Comment by jaxxstorm** [comment]
Blog post is out, and all the examples are done. Closing this!
