### ISSUE TITLE
Python: follow up on type issues

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#3767]
There were a few type issues discovered as a part of enabling mypy in #3710 and #3758. 

1. Follow up on the encoding of `Unknown` and `None` WRT `Output`: https://github.com/pulumi/pulumi/pull/3758#discussion_r367570819
2. Label `T` in Output as covariant: https://github.com/pulumi/pulumi/pull/3758#discussion_r367579715. If I try enabling this, mypy complains about covariant parameters in `.apply`. This needs some further investigation.

**Comment by lukehoban** [comment]
> If I try enabling this, mypy complains about covariant parameters in .apply.

Curious - which lines of code triggered these errors?

**Comment by EvanBoyle** [comment]
Another one to look into: https://github.com/pulumi/pulumi/pull/3758/files/9008ac25d834e04a643a1d96b45d6122183af1be#r368084010

**Comment by lukehoban** [comment]
We've made many improvements to these types - and remaining improvements are not "critical" and easy to make incrementally.
