### ISSUE TITLE
Unhandled exceptions and inconsistency in requireOutputSync

### ISSUE THREAD

**Issue by robertvanhoesel** [pulumi/pulumi#3780]
I experience inconsistent behavior when calling StackReference.requireOutputSync() in preview/up, centered around the following bit:

https://github.com/pulumi/pulumi/blob/c9d3a504b175a39020310d79d85a5adfbde781f0/sdk/nodejs/stackReference.ts#L141-L159

Results vary between:
- Unhandled exception because secretNames is undefined ( .includes() on line 150)
- Occasionally the neat but incorrect error that output does not exist.
- The expected result (program continues but warns about usage of requireOutputSync).

It seems there is some race condition calling requireOutputSync before all properties are resolved (outputs, secretNames, supported).
 
I am aware of the fact that requireOutputSync is problematic and to be deprecated, but looking at our current setup (not passing a promise to StackReference, using sdk+cli 1.8.1, node v12.10.0) it should not cause any problems already. This inconsistent behavior occurs on all recent versions of Pulumi (at least 1.5-1.8.1)

**Comment by robertvanhoesel** [comment]
Is there anything I can do to fix or help you fix this unhandled exception? It's coming up 3 out of 4 times and blocks us from using Pulumi in CI and turns development more into gambling hoping for no exceptions.

**Comment by CyrusNajmabadi** [comment]
@robertvanhoesel can you use requireOutput instead of requireOutputSync?

**Comment by CyrusNajmabadi** [comment]
@lukehoban Pulumi 2.0 adds the following APIs:

```ts
public async getOutputValue(name: string): Promise<any>;
public async requireOutputValue(name: string): Promise<any>;
```

https://github.com/pulumi/pulumi/blob/feature-2.0/sdk/nodejs/stackReference.ts#L104

There should be no problem with backporting these helpers to the Pulumi 1.x line.  Do you have any issues with that?  I'll create a PR asap to help out here.

**Comment by robertvanhoesel** [comment]
@CyrusNajmabadi thanks for looking into this!

We considered and tried switching to requireOutput, however in most cases we are not passing them as resources to Pulumi code that can work with Output<T> but rather as strings used to generate new resource names i.e.:

```ts
const dbName = infra.requireOutput('dbPrimaryDatabaseName') as Output<string>,
const user = new pg.Role(`${dbName}-client-user`, {
  name: `${dbName}-client`,
  password: pwd.result,
  login: true,
}, { provider: providers.db });
```

New resources only accept strings as as the name parameter, not an Output<string>. Suggested workarounds by the cli such as o.apply() and interpolate`` both result in a new Output<string>. Casting `String(Output<string>)` is also not allowed. 

I've just retried implementing requireOutput to work in our scenario but without luck. 

Any guidance on how to simply use the output as strings for names? The below just works fine (* aside from the inconsistent behavior).

```ts
const dbName = infra.requireOutputSync('dbPrimaryDatabaseName') as String
```

---

With Pulumi 2.0's async requireOutputValue, we would need to wrap all our resource creation inside async as well, is this a typical pattern for 2.0?

**Comment by CyrusNajmabadi** [comment]
> we would need to wrap all our resource creation inside async as well, is this a typical pattern for 2.0?

Unfortunately yes.  This work is fundamentally asynchronous (and actually needs to talk to different processes and whatnot).  We tried making it synchronous, but it put us in a very bad state as the library we were using to accomplish this was actually very hacky and led to some extremely bad issues (i.e. crashes, instability, corruption, etc.).  It's a problem i caused, and i've been spending at least a month digging us out of it :(

**Comment by robertvanhoesel** [comment]
@CyrusNajmabadi thanks & understood. We appreciate the work you and the team put in! 

In the meantime, any suggested approach on how to use Output<string> as part of a resource name?

**Comment by lukehoban** [comment]
> In the meantime, any suggested approach on how to use Output as part of a resource name?

Today, there is no way to do this.   The resource name must be known immediately to be sure that resource identity lines up.  

Note that in your example above, you can keep `name: ...` as is - you just need to change `new pg.Role(<name>)`.  The latter is just the logical resource name within this stack - and so shouldn't *need* to be dependent on any output.

I'm going to close this issue out since I don't believe there is anything we expect to concretely change here in the near term - we fundamentally had to make some changes here to be compatible with Node.js.  If there are second-order things that we should consider adjusting as a result - do feel free to open a new issue.
