### ISSUE TITLE
Final revamp of .NET package names and namespaces

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#3786]
.NET naming convention [says](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) that acronyms should be PascalCase.

However, the brands should keep capitalization ([link](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces)):

> If your brand employs nontraditional casing, you should follow the casing defined by your brand, even if it deviates from normal namespace casing.

The suggestion is to revise the following providers:
- `VSphere` -> `vSphere`
- `MySql` -> `MySQL`
- `PostgreSql` -> `PostgreSQL`
- `CloudAmqp` -> `CloudAMQP`

Special attention goes to AWS and GCP. Are they "brand employing nontraditional casing" or just acronyms?
- Amazon uses "AWS" in NuGet, but others use mostly "Aws" https://www.nuget.org/packages?q=aws
- Google uses "Gcp" https://www.nuget.org/packages?q=gcp
- It's a close call, but we should probably go for `Pulumi.AWS` and `Pulumi.GCP`, which is the most impactful change here (provider, templates, examples, breaking change).

**Comment by lukehoban** [comment]
I don’t have a strong sense of how strongly this brand rule is followed - but I will admit that it introduces a really ambiguous element into our naming that I’m sure we’ll get “wrong” a lot - especially in long tail providers. And which is a breaking change to fix. 

It feels like a simple and predictable pattern that we can confidently apply is desirable here - even if it is ever so slightly off from official guidelines. 

But if others think this is something we have to do to have “good” .NET names, I don’t feel too strongly.

**Comment by mikhailshilkov** [comment]
I don't feel religious about this either. FWIW, it looks like there's a lot of inconsistency in naming the same things in different packages.

Whatever we choose, the chance of errors for any new provider will stay relatively high, so we'll need to carefully review every new one anyways. We should probably document naming in "creating a new provider" guide if/when we have one.

**Comment by mikhailshilkov** [comment]
The decision is to keep the naming as-is and keep living with the maximally unambiguous naming strategy.
