### ISSUE TITLE
Pulumi fails to find Python on windows

### ISSUE THREAD

**Issue by pixelicous** [pulumi/pulumi#3787]
I cannot get pulumi 1.8.1 to work on windows 10 from command line.
Both pulumi and python installed from choco
No other application has an issue with python

Following the beginners guide i run: pulumi up
and get:
error: Failed to locate 'python3' on your PATH. Have you installed Python 3.6 or greater?

The funny thing is, i created the virtualenv and installed prerequisites without any issue
i can also run "which python" and see its running in my virtualenv

I have verified and i have python installed and its in the path, as i can write python from anywhere and get to python (Python 3.8.1)

Found similar issue at #3398, seem

p.s- you are missing correct instructions on your website for windows on how to activate a python virtual environment.

**Comment by lukehoban** [comment]
The fix for #3398 (and also this issue) is in master - but will be released this week as part of 1.9.0. 

The fix for the docs related to windows and virtual environments is in progress in https://github.com/pulumi/docs/pull/2184 - feel free to leave feedback on those changes.

**Comment by pixelicous** [comment]
@lukehoban thx, so i guess ill start checking pulumi sometime in the futue and not now

Thanks!

**Comment by dstine** [comment]
@pixelicous 
Just FYI, I am successfully using the work-around from #3398 with Pulumi 1.8.1: copying `python.exe` to `python3.exe`

**Comment by lukehoban** [comment]
@pixelicous we expect to have a release out today that includes this fix. And as @dstine notes, it is possible to work around in the meantime!
