### ISSUE TITLE
`pulumi update` with `--target` and unapplied non-target resource breaks everything 💥

### ISSUE THREAD

**Issue by theneva** [pulumi/pulumi#3790]
Hi! :wave:

I'm not 100 % sure if this is an issue with Pulumi or with the GCP Provider, but the stack trace points to the Pulumi code.

## Background

I have a TypeScript Pulumi project that uses GCP.

My resource file (`index.ts`) has a bunch of resources. One resource (a GCP service account) is a work in progress, and has never been applied. It looks like this (`provider` is just a non-default GCP provider):

```ts
const grafanaPublicImageServiceAccount = new gcp.serviceAccount.Account(
  'grafana_public_image_service_account',
  {
    accountId: `grafana-public-images-${environment}`,
    displayName: 'Grafana public image service account',
  },
  { provider }
);
```

I upgraded the GCP provider, which changed some default values on the `container_cluster` resource type. I wanted to apply those new defaults to my cluster, but not apply the work-in-progress service account.

To achieve this, I scoped the `update`: `$ pulumi up --target urn:pulumi:$STACK::$PROJECT::gcp:container/cluster:Cluster::$CLUSTER_NAME`

As expected, this only updated my container cluster in GCP, and committed the new state to the state file.

## The problem

Unexpectedly, it also committed the work-in-progress service account to the state file without an `id` field. It wasn't actually created in GCP, so at least there's that.

In this state (with a service account without an `id` in the state file), Pulumi crashes completely when reading the state file. Specifically, it fails this assertion:

https://github.com/pulumi/pulumi/blob/0d0641278cadb995301de8678be1a021abda0f28/pkg/resource/plugin/provider_plugin.go#L669

Here's the stack trace:

```
$ pulumi refresh
Previewing refresh ($STACK):

panic: fatal: An assertion has failed

goroutine 176 [running]:
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
	/private/tmp/pulumi-20200123-81804-1k7sk6i/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assert(...)
	/private/tmp/pulumi-20200123-81804-1k7sk6i/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/resource/plugin.(*provider).Read(0xc0010fd7a0, 0xc000b48300, 0x5f, 0x0, 0x0, 0xc00124c630, 0xc00124c660, 0x0, 0x7fffffff, 0x100, ...)
	/private/tmp/pulumi-20200123-81804-1k7sk6i/src/github.com/pulumi/pulumi/pkg/resource/plugin/provider_plugin.go:669 +0xfcb
github.com/pulumi/pulumi/pkg/resource/deploy.(*RefreshStep).Apply(0xc00078efa0, 0x1, 0x52ec902, 0x23, 0xc001503e18, 0x3)
	/private/tmp/pulumi-20200123-81804-1k7sk6i/src/github.com/pulumi/pulumi/pkg/resource/deploy/step.go:726 +0x140
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).executeStep(0xc000b89000, 0x8, 0x55dc1a0, 0xc00078efa0, 0x0, 0x0)
	/private/tmp/pulumi-20200123-81804-1k7sk6i/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:271 +0x217
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).executeChain(0xc000b89000, 0x8, 0xc00095e2a0, 0x1, 0x1)
	/private/tmp/pulumi-20200123-81804-1k7sk6i/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:221 +0xe6
github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).worker.func1(0xc000b89000, 0x8, 0xc00095e2a0, 0x1, 0x1, 0xc0013d9800)
	/private/tmp/pulumi-20200123-81804-1k7sk6i/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:371 +0xea
created by github.com/pulumi/pulumi/pkg/resource/deploy.(*stepExecutor).worker
	/private/tmp/pulumi-20200123-81804-1k7sk6i/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:368 +0x2fa
```

I was able to run scoped refreshes (e.g., `$ pulumi refresh --target urn:pulumi:$STACK::$PROJECT::gcp:container/cluster:Cluster::$CLUSTER_NAME`) with no issues – but whenever I did something to make Pulumi read the entire state file, it failed immediately.

## Workaround

I worked around the issue by manually deleting the offending service account entry from the `resources` array in the state file. `$ pulumi state delete $OFFENDING_RESOURCE_URN` worked fine :smile:

## Reproduction

After applying the workaround, I did the same thing again to verify that I understood the problem.

1. Have a project with existing resources
2. Add a (valid) resource that has not been applied
3. Run a scoped update on any other resource (it does not need to have changes): `$ pulumi update --target $SOME_RESOURCE`
4. Try doing something that forces Pulumi to read the state file: `$ pulumi refresh`

**Comment by pgavlin** [comment]
Thanks for the report! @CyrusNajmabadi can you take a quick look?

**Comment by CyrusNajmabadi** [comment]
That seems very bad.  This is the case where we go through the 'skipped create' path.  i.e. we mark that a user wanted to make the item, but we don't explicitly error unless the created item is referenced by something that we're actually going through with.  

There must be a mistake where we're not properly filtering out this 'skipped create'.

**Comment by theneva** [comment]
Thank you very much for fixing this so quickly!

**Comment by CyrusNajmabadi** [comment]
Definitely!
