### ISSUE TITLE
Support turning secret into non-secret

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3795]
There are (rare) occasions when it is important to opt-in to turning a secret into a non-secret.  This is dangerous (as it risks leaking the secret) - but we should allow users to make the explicit choice to do so if they want.

They can already technically accomplish this - so it's not changing the trust boundaries to provide an API for it.  And the API should have all the appropriate warning signs attached (perhaps even `unsafe` in the name if warranted).

A workaround for now is:

```ts
        (<any>password).isSecret = Promise.resolve(false);
```

This should be added to all language SDKs.

**Comment by stack72** [comment]
The work involved here is the add the following style api to all the languages we have available

`const v = pulumi.unsecret(output)`

**Comment by stack72** [comment]
@lukehoban should we also take care of #2886 at the same time?

**Comment by stack72** [comment]
Closed as being tracked in #5653
