### ISSUE TITLE
Testing with Jest breaks on closure serialization

### ISSUE THREAD

**Issue by dustinfarris** [pulumi/pulumi#3799]
Running unit tests with Jest breaks if a test references an output from a resource that utilizes closure serialization, e.g. lambda callbacks or dynamic resources.

Minimal repo to reproduce:

https://github.com/dustinfarris/pulumi-jest-bug

Install dependencies and run `npx jest` to see the error:

```
Error calling "Runtime.evaluate(global.__inflightFunctions.id0)": Uncaught
```

This is coming from [runtime/closure/v8_v11andHigher#getRuntimeIdForFunctionAsync](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/runtime/closure/v8_v11andHigher.ts#L140).

After digging a little, it seems that `__inflightFunctions` did not exist at the time this was called.  Here's some console.log output from my locally built pulumi:

```js
exceptionDetails: {
        exceptionId: 2,
        text: 'Uncaught',
        lineNumber: 0,
        columnNumber: 27,
        scriptId: '2434',
        exception: {
          type: 'object',
          subtype: 'error',
          className: 'TypeError',
          description: "TypeError: Cannot read property 'id1' of undefined\n" +
            '    at <anonymous>:1:28\n' +
            '    at Session.post (inspector.js:110:28)\n' +
            '    at internal/util.js:278:30\n' +
            '    at new Promise (<anonymous>)\n' +
            '    at Session.post (internal/util.js:277:12)\n' +
            '    at /opt/pulumi/node_modules/@pulumi/pulumi/runtime/closure/v8_v11andHigher.js:121:40\n' +
            '    at Generator.next (<anonymous>)\n' +
            '    at fulfilled (/opt/pulumi/node_modules/@pulumi/pulumi/runtime/closure/v8_v11andHigher.js:18:58)\n' +
            '    at processTicksAndRejections (internal/process/task_queues.js:93:5)',
          objectId: '{"injectedScriptId":1,"id":4}'
        }
```

I believe this may be related to how Jest isolates individual test suites (files) in their own vm, but I'm not too familiar with how vms work in node.

cc @lukehoban

**Comment by DSoko2** [comment]
I investigated a bit on this probem:
At the core, `v8_v11andHigher#getRuntimeIdForFunctionAsync` relies on `global` being the same instance within the inspector session. This is usually the case as there is only one `global` in the entire process. However, jest (and others, too) use the nodejs vm API to create separate contexts, which basically each have their own non-shared `global`. The problem faced here is that the inspector session works on another `global` instance than `v8_v11andHigher#getRuntimeIdForFunctionAsync` which causes that the corresponding function is not found. This can be solved by providing the `Runtime.evaluate` the right `contextId` argument. However, that's the tricky one here, I assume...

So far the only way I found/see to find execution context ids is using the inspectors [Runtime.executionContextCreated](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-executionContextCreated) event. Using it I managed to implement a hacky patch that tries currently existing contexts until it found the right one. Obviously, this is not a nice solution, which most probably is not generally reliable. I think about trying to deliberately create an dedicated context with initially observed and then known context id for this inspector stuff, and making its `global` accessible to invocation of `v8_v11andHigher#getRuntimeIdForFunctionAsync` from other contexts. If this works, it could be a generally applicable solution to this problem.

It would be good to know whether there is a better/easier way to get execution context ids than observing them through the inspector's [Runtime.executionContextCreated](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-executionContextCreated) event. Unfortunately, I could not find such thing on Google nor in the docs. @CyrusNajmabadi do you perhaps know an alternative feature for that? You seem to have better knowledge with these APIs...
