### ISSUE TITLE
Creating a Dynamic Provider causes 'non-numeric port' error on Windows

### ISSUE THREAD

**Issue by cloudspeak** [pulumi/pulumi#3807]
Hi,

I am learning how to write a Dynamic Provider using the [example in the documentation](https://www.pulumi.com/docs/intro/concepts/programming-model/#dynamicproviders).  My Pulumi program looks like this:

```python
import pulumi
from pulumi.dynamic import ResourceProvider, CreateResult
from pulumi import ResourceOptions
from pulumi.dynamic import Resource
from typing import Any, Optional

class MyProvider(ResourceProvider):
    def create(self, inputs):
        return CreateResult(id_="foo", outs={})

class MyResource(Resource):
    def __init__(self, name: str, props: Any, opts: Optional[ResourceOptions] = None):
        super().__init__(MyProvider(), name, props, opts)

myRes = MyResource("TestNewResource", {})
```

However, when I run `pulumi up` I get the following error message:

```
Diagnostics:
  pulumi:providers:pulumi-python (default):
'): strconv.Atoi: parsing "65196\r": invalid syntaxs\MyWindowsUsername\.pulumi\bin\pulumi-resource-pulumi-python.cmd] wrote a non-numeric port to stdout ('65196
```

The error message is slightly garbled but I think the problem is the `\r` which is present after the port number.  Since I am on Windows 10, something is probably outputting Windows line breaks.  Indeed, just above the [line which I presume generates this error](https://github.com/pulumi/pulumi/blob/10a960ea4b7728a21fe0b0a6aa9768994a538e92/pkg/resource/plugin/plugin.go#L171), a comment states "`Parse the output line (minus the '\n')`". I then tried the same code on a Linux VM and I do **not** encounter the same error.

This issue occurs on Pulumi 1.8.1 and 1.9.0.  I am using Python 3.8.  Note a [similar, older issue](https://github.com/pulumi/pulumi-policy/issues/170) appeared in pulumi-policy, but the cause seems to be unrelated.

Am I doing anything wrong, or can anyone suggest a workaround for this?  It is going to be a huge blocker for my project if I cannot create Dynamic Providers on Windows.

Many thanks.

**Comment by lukehoban** [comment]
Thanks for the detailed report - it does look like there is an issue here with Python + Dynamic Providers + Windows. We will look into it.
