### ISSUE TITLE
Need a way to avoid conflicts between two Pulumi stacks

### ISSUE THREAD

**Issue by mmdriley** [pulumi/pulumi#381]
Sometimes a property other than a resource's name needs to be unique within some scope (e.g. an AWS region). These are the sorts of things we'd use `xyz-${AWS::StackName}` for in CloudFormation.

One motivating example is the `Family` field of an ECS task definition. This needs to be unique within a region, but should _not_ change when the TaskDefinition is recreated since AWS provides its own versioning scheme with revision numbers. See the [CloudFormation docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-family) for more on how this works.

One solution might be to create a cheap intermediate resource (e.g. an S3 bucket, or a fake resource designed entirely for this purpose), rely on its unique naming, then borrow part of that name. It might be useful, though, to know the property value _before_ the stack is created -- consider the case of EC2 keypairs that need to be created before the Pulumi program is deployed.

We can also punt this back to users with config, but this seems like a common enough problem to merit a platform solution.

**Comment by joeduffy** [comment]
We now have the `@pulumi/random` package. I believe that's sufficient to avoid these issues.

/cc @pgavlin so he can correct me if I'm wrong.
