### ISSUE TITLE
Unconditional diff for program without changes

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3810]
I have a program that unconditionally shows a diff when there are no changes made.

The offending part of the program is:

```csharp
// Create an IAM role that can be used by our service's task.
var taskExecRole = new Iam.Role("task-exec-role", new Iam.RoleArgs {
    AssumeRolePolicy = @"{
    ""Statement"": [{
        ""Sid"": """",
        ""Effect"": ""Allow"",
        ""Principal"": {
            ""Service"": ""ecs-tasks.amazonaws.com""
        },
        ""Action"": ""sts:AssumeRole""
    }]
}",
});
```

The policy shows up as a diff, apparently due to some normalization of the JSON?

```
~ assumeRolePolicy:
"{\"Version\":\"2008-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ecs-tasks.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
=>
"{\n    \"Statement\": [{\n        \"Sid\": \"\",\n        \"Effect\": \"Allow\",\n        \"Principal\": {\n            \"Service\": \"ecs-tasks.amazonaws.com\"\n        },\n        \"Action\": \"sts:AssumeRole\"\n    }]\n}"
```

**Comment by stack72** [comment]
Im pretty sure this is because you are missing Version in the policy and AWS is normalising it

**Comment by joeduffy** [comment]
That sounds likely to be it -- but shouldn't we be insulated from this, since we store and diff the normalized values? Or is the provider not doing full normalization for the value used for diffing?

**Comment by joeduffy** [comment]
By the way, confirmed that adding the version makes this go away.

Feel free to close out if this is by-design -- I just assumed we'd want to ensure we never get into this state, but if it's due to behavior in the provider, at the very least I suppose it's a bug in the provider and not in the engine itself.

**Comment by stack72** [comment]
Yeah this is 100% a but in the provider. Basically the provider on the Read is getting the normalised value and storing that and causing our perpetual diff. Technically this is an actually an invalid Policy but aws allows it because people are sloppy :/ not sure if this means we should close this out - but I 100% would expect the same behaviour in TS or Go

**Comment by joeduffy** [comment]
Yeah, I copied that from somewhere, hence the missing version. I'll close this out then -- please open something on the AWS provider if you think this warrants further investigation. I've never heard anybody mention this previously and folks are writing IAM policies left and right, so I assume it's not worth chasing down.
