### ISSUE TITLE
Ensure all integration tests run on Windows

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#3811]
As a follow up to #3656, there are a number of integration tests that currently fail on Windows:

* [ ] TestConfigCaptureNodeJS
* [ ] TestStackReferenceNodeJS
* [ ] TestStackReferencePython
* [ ] TestStackReferenceDotnet
* [ ] TestStackReferenceSecretsNodejs
* [ ] TestStackReferenceSecretsDotnet
* [ ] TestDynamicPython
* [ ] TestPartialValuesPython
* [ ] TestStackBadParenting
* [ ] TestLargeResourceNode

We need to ensure these are not skipped on each test run

Related: #3656

**Comment by mikhailshilkov** [comment]
This task has been open for two years and I'm pretty sure the todo list is out of date. I'll close it, we should improve our CI setup independently of this list.
