### ISSUE TITLE
Support closure serialization in the Go SDK

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#3820]

**Comment by lukehoban** [comment]
Honest question - is this possible?  What are our best thoughts on how we could approach it?   (Note that it is not supported in Python or .NET currently).

**Comment by EvanBoyle** [comment]
I haven't started to think about it. Just making sure the list here (https://github.com/pulumi/pulumi/issues/1614) is captured in issues. It's already stimulating discussion it seems!

**Comment by pgavlin** [comment]
I really don't think that this is possible. The only way in which I think we _might_ be able to do this is by compiling to WASM and then adding whatever support we'd need to execute Go on WASM. While the latter isn't super complicated (see e.g. https://pkg.go.dev/github.com/pgavlin/warp@v0.0.0-20210421003616-2bac1014889b/go_wasm_exec), Go on WASM isn't really feature-complete.

**Comment by pgavlin** [comment]
I'm going to close this for now.

**Comment by t0yv0** [comment]
I'm thankful this is closed; even if possible that's possibly very "interesting" to maintain. Scala/Spark, Scala/Python and .NET MBrace rely on closure serialization among others. When I worked with Scala/Spark it caused very painful debugging.

Now, Spark really emphasizes closure serialization so I searched the net how people do it in Go.

https://github.com/apache/beam/blob/master/sdks/go/examples/cookbook/filter/filter.go#L55

```go
	// Rows filtered to remove all but a single month
	filtered := beam.ParDo(s, &filterMonthFn{Month: m}, rows)

	// Then, use the global mean as a side input, to further filter the weather data.
	// By using a side input to pass in the filtering criteria, we can use a value
	// that is computed earlier in pipeline execution. We'll only output readings with
	// temperatures below this mean.
	return beam.ParDo(s, filterBelowMeanFn, filtered, beam.SideInput{Input: globalMeanTemp})
}

type filterMonthFn struct {
	Month int `json:"month"`
}

func (f *filterMonthFn) ProcessElement(row WeatherDataRow, emit func(WeatherDataRow)) {
	if row.Month == f.Month {
		emit(row)
	}
}
```

So, the user is asked to manually annotate the closure state as a struct and take care that it serializes.
