### ISSUE TITLE
1.9.1 Release

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#3821]
- [x] language SDKs and CLI
- [x] homebrew (https://github.com/Homebrew/homebrew-core/pull/49459)
- [x] dockerhub
- [x] docs and marked as latest-version (https://github.com/pulumi/docs/pull/2313)
- [x] Chocolatey

**Comment by pgavlin** [comment]
@stack72 any ideas re: this Chocolatey issue? https://ci.appveyor.com/project/Pulumi/pulumi-chocolatey

**Comment by stack72** [comment]
@pgavlin the previous maintainer hadn't switched off the autoupdate of the Pulumi package - this has been rectified. Chocolatey does have the 1.9.1 package though :)
