### ISSUE TITLE
Go SDK testing approach (user facing)

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#3824]
See dotnet issue: https://github.com/pulumi/pulumi/issues/3633
Mocks PR: https://github.com/pulumi/pulumi/pull/3738

**Comment by EvanBoyle** [comment]
This was added as a part of #3506 

We still need documentation, blogs, etc.

**Comment by lukehoban** [comment]
> This was added as a part of #3506 
> We still need documentation, blogs, etc.

Should we close this out then and use https://github.com/pulumi/docs/issues/992 to track?   cc @mikhailshilkov

**Comment by lukehoban** [comment]
Closing this out.  We need to document mocking and unit testing support in *all* languages - and that is part of  https://github.com/pulumi/docs/issues/992.
