### ISSUE TITLE
Different config path and source path

### ISSUE THREAD

**Issue by jjangga0214** [pulumi/pulumi#3827]
Hi, let's say I have a directory structure like this.

```
mydir
├── Pulumi.productoin.yaml
├── Pulumi.staging.yaml
├── Pulumi.yaml
├── src
│   ├── cluster.ts
│   ├── config.ts
│   └── index.ts
└── tsconfig.json
```

So, source files(e.g. index.ts) and config files like Pulumi.yaml does not reside in the same directory.
In this situation, how can I `pulumi up`?

**Comment by pgavlin** [comment]
You should be able to add the following to your `Pulumi.yaml`:

```
main: src/
```
