### ISSUE TITLE
Move Input and Output attributes to Pulumi namespace

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#3833]
(.NET SDK) `InputAttribute` and `OutputAttribute` are currently in `Pulumi.Serialization` namespace, and they seem to be the user-facing core things not in `Pulumi`. As we use those attributes for component resources and stacks, they should be in `Pulumi`.

That's a breaking change but it seems worth it.

@CyrusNajmabadi opinion?

**Comment by CyrusNajmabadi** [comment]
Yes.  This seems worth it.  Previously it wasn't expected that users would ever need this.  But that's not the case anymore with Stacks.

**Comment by mikhailshilkov** [comment]
Opened #3910 to track the removal of the obsolete attributes
