### ISSUE TITLE
Imported Azure ResourceGroup trying to be deleted on destroy

### ISSUE THREAD

**Issue by michaeldtaylor** [pulumi/pulumi#3842]
In the organisation I am currently working for have a rather strange policy with regards to Azure ResourceGroups, meaning this is not something I can create myself (lots of teams share the same subscription).  I can however create and manage anything under a specific ResourceGroup.

I thought that using ImportId's might be the way to do it:

````csharp
var resourceGroup = new ResourceGroup("my_rg",
    new ResourceGroupArgs
    {
        Name = "my_rg"
    },
    new CustomResourceOptions
    {
        ImportId = "/subscriptions/guid/resourceGroups/my_rg"
    });
````

And this works fine when using:
````
pulumi up
````
However, when using:
````
pulumi destroy
````
It is trying to delete the imported ResourceGroup, which a) It can't because I don't have permission, and b) It shouldn't because it was not created by Pulumi, merely imported. Not only does it try to delete the ResourceGroup, it sits there forever retrying to do that, so destroy becomes useless for me.
````
Previewing destroy (dev):

     Type                         Name            Plan
 -   pulumi:pulumi:Stack          quickstart-dev  delete
 -   ├─ azure:storage:Account     my_storage      delete
 -   └─ azure:core:ResourceGroup  my_rg           delete          <---- Wrong
````
I tried "Protect" = true, but this just stopped destory altogether.

Is there any way around this? Effectively, I want Pulumi to manage everything under the ResourceGroup, but leave the ResourceGroup alone.

**Comment by stack72** [comment]
Hi @michaeldtaylor 

So, unfortunately, when you bring a resource into Pulumi management (via import or otherwise), it then follows the Pulumi crud cycles. Therefore, when you try and destroy the resources in the application, it will try and destroy the resource group. I think the only way around this for you would be to use the `azure.core.getResources` resource where you would pass in a resource group. That would return a list of the IDs and the types (e.g. Network, compute etc) of the resources housed within the resource group and then you could manage those resources rather than the resource group itself

Does this make things any easier for you?

Paul

**Comment by michaeldtaylor** [comment]
I'll give it a go thanks. My hands are tied, so if I can't get it to work I can't use Pulumi to manage the rest of the environment, unless I never use destroy.

**Comment by stack72** [comment]
I totally understand @michaeldtaylor - sometimes there are environmental restrictions around these types of things. Please let me know if you have any issues with this getResources code path and we can see what we can do

Paul

**Comment by stack72** [comment]
Hi @michaeldtaylor 

Is there anything else you need with this?

Paul

**Comment by michaeldtaylor** [comment]
Hi @stack72,

I'm good for now thanks. I'll let you know how I get on.

Michael

**Comment by lukehoban** [comment]
Closing out for now - but happy to address any remaining issues here if you'd like to reopen.

**Comment by amaier-ypog** [comment]
I solved that by protecting the imported resource group and then destroying the stack but excluding the protected resource:

```
$ pulumi stack -u # get the urn of the ResourceGroup to protect
$ pulumi state protect <urn>
$ pulumi destroy --exclude-protected
```

**Comment by asmaier** [comment]
I solved that by protecting the imported resource group and then destroying the stack but excluding the protected resource:

```
$ pulumi stack -u # get the urn of the ResourceGroup to protect
$ pulumi state protect <urn>
$ pulumi destroy --exclude-protected
```

**Comment by Frassle** [comment]
[retain on delete](https://www.pulumi.com/docs/iac/concepts/options/retainondelete/) would probably also be a good option for this scenario.
