### ISSUE TITLE
Can't iterate over Output[List] (Python)

### ISSUE THREAD

**Issue by solidDoWant** [pulumi/pulumi#3849]
When I attempt to iterate over an Output[List] object such as below:

`
import pulumi
import pulumi_cloudflare
import pulumi_aws.globalaccelerator
from typing import List, Optional

class Args:
    def __init__(self, ips: List[str]):
        self.ips: List[str] = ips

class ExampleComponent(pulumi.ComponentResource):
    def __init__(self, name: str, args: Args, opts: Optional[pulumi.ResourceOptions] = None):
        for ip in args.ips:
            print(ip)

ga: pulumi_aws.globalaccelerator.Accelerator = pulumi_aws.globalaccelerator.Accelerator(
    "global_accelerator",
    enabled = True,
    ip_address_type = "IPV4",
    name = "pulumi-issue-global_accelerator"
)

example: ExampleComponent = ExampleComponent(
    "example",
    Args(ga.ip_sets[0]["ip_addresses"])
)
`

Instead of printing the output, the following is printed instead:
`Previewing update (dev):

    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E619F0D0>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E617E9D0>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E6168A60>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E619B640>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61791C0>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E6187700>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E6187F40>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61A34C0>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61A3730>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61A39A0>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61A3C10>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61A3E80>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61AF130>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61AF3A0>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61AF610>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61AF880>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61AFAF0>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61AFD60>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61AFFD0>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61B1280>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61B14F0>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61B1760>
    pulumi:pulumi:Stack pulumi-test6-dev  <pulumi.output.Output object at 0x00000202E61B19D0>
...
`

(For context there should only be two outputs)

Output.Apply and All both return Output objects, so they don't help. 

What do I need to do to iterate over a returned Output[List]?

**Comment by pgavlin** [comment]
> What do I need to do to iterate over a returned Output[List]?

You can't iterate over an `Output[List]` by design, as the actual value of the output may not be known at the time you attempt to iterate. You need to access the resolved value of the output via an `Apply` and iterate over it inside your callback.

**Comment by pgavlin** [comment]
(`Output` values are essentially futures that extra information such as resource dependencies, secretness, etc)

**Comment by solidDoWant** [comment]
If that's the case how do I create additional resources based off of an output value? I'm aware and fine with the fact that they wouldn't show up at preview time. Output.apply says that:

> 'func' is not allowed to make resources.

Is there a way to extract it to a non-output values from apply?

**Comment by pgavlin** [comment]
> Output.apply says that:
>
> > 'func' is not allowed to make resources.
> 
> Is there a way to extract it to a non-output values from apply?

This is a guideline, but not a hard rule. The most significant risk is that if you create a resource inside an apply and return one of its outputs, the result may not have proper dependency information, which can cause issues during `pulumi destroy`. Besides that, the resources may not show up at preview time if the inputs to the apply are unknown (as you've pointed out).

**Comment by lukehoban** [comment]
> Output.apply says that:
>> 'func' is not allowed to make resources.

Note that we should definitely fix this doc comment to be more accurate about the implications of creating resources inside an `apply` callback.

**Comment by solidDoWant** [comment]
Thanks @pgavlin, that solves my problem.
