### ISSUE TITLE
[NodeJS] Significant performance issues with `pulumi.output` and `pulumi.all` 

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3850]
We have seen that when large objects are passed as inputs to `pulumi.output` and/or `pulumi.all`, they can cause very large amounts of memory allocations and garbage collection due to recursively visiting the input object(s) and allocating a lot of (most often unnecessary) intermediate results.  

We believe this is the root cause of a number of OOM issues we have seen reported by Pulumi Node.js users - including:
- https://github.com/pulumi/pulumi/issues/3279
- https://github.com/pulumi/pulumi-kubernetes/issues/963
- https://github.com/pulumi/pulumi-eks/issues/312

**Comment by pgavlin** [comment]
I believe https://github.com/pulumi/pulumi/pull/3851 will fix this issue.

**Comment by lukehoban** [comment]
Fixed with #3851.
