### ISSUE TITLE
Clean up CustomResourceOptions vs ComponentResourceOptions in .NET SDK

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#3857]
- Make `ResourceOptions` class abstract
- `CustomResource` should expect `CustomResourceOptions`
- `ComponentResource` should expect `ComponentResourceOptions`
- Fix the docs that would mention `new ResourceOptions` instead of a derived class

**Comment by joeduffy** [comment]
Note that I cleaned up a few obvious `new ResourceOptions` instances in the docs [here](https://github.com/pulumi/docs/pull/2338), however I can't claim to have gotten them all.
