### ISSUE TITLE
Add primitive helper methods to the Go SDK

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#3861]
There are a few repetitive motions with the Go SDK especially with converting prompt arrays and maps into pulumi equivalents. 

Joe also ran into a similar issue with `StringArrayInput` that required a helper when working on an [ECS example](https://github.com/pulumi/examples/pull/540):

```go
func toPulumiStringArray(a []string) pulumi.StringArrayInput {
	var res []pulumi.StringInput
	for _, s := range a {
		res = append(res, pulumi.String(s))
	}
	return pulumi.StringArray(res)
}
```

We should add some helpers to make this a little more ergonomic.

**Comment by EvanBoyle** [comment]
From @joeduffy :
https://github.com/pulumi/pulumi/issues/4080
It's likely I'm completely misunderstanding how these types are meant to be used, and/or overlooking some conversion functions in our SDK. However, I've found that some conversions between output types are relatively common and yet I don't see any easy way to accomplish them.

Here are a few examples:

* `[]string` => `pulumi.StringArray`
* `map[string]string` => `pulumi.Map`
* `[]pulumi.IDOutput` => `pulumi.IDOutputArray`
* `[]pulumi.IDOutput` => `pulumi.StringOutputArray`
* `[]pulumi.StringOutput` => `pulumi.StringOutputArray`

For many of the output-related ones, I've encountered them when accumulating values throughout a program, and then later needing to supply them as inputs to a resource constructor. For instance, we often want to pass an array of IDs where the receiving type just calls them strings.

Another area I ran into this is `pulumi.Export`. It unfortunately expects an `Output` as the value (I wonder, should it just take an `interface{}`?) -- which means we need to convert the values.

Here are the conversion helpers I've written to convert things:

```go
package main

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func goStringArrayToPulumiStringArray(ss []string) pulumi.StringArray {
	var elems []pulumi.StringInput
	for _, s := range ss {
		elems = append(elems, pulumi.String(s))
	}
	return pulumi.StringArray(elems)
}

func goMapToPulumiMap(m map[string]string) pulumi.Map {
	ret := make(pulumi.Map)
	for k, v := range m {
		ret[k] = pulumi.String(v)
	}
	return ret
}

func idOutputArrayToIDArrayOutput(as []pulumi.IDOutput) pulumi.IDArrayOutput {
	var outputs []interface{}
	for _, a := range as {
		outputs = append(outputs, a)
	}
	return pulumi.All(outputs...).ApplyIDArray(func(vs []interface{}) []pulumi.ID {
		var results []pulumi.ID
		for _, v := range vs {
			results = append(results, v.(pulumi.ID))
		}
		return results
	})
}

func idOutputArrayToStringOutputArray(as []pulumi.IDOutput) pulumi.StringArrayOutput {
	var outputs []interface{}
	for _, a := range as {
		outputs = append(outputs, a)
	}
	return pulumi.All(outputs...).ApplyStringArray(func(vs []interface{}) []string {
		var results []string
		for _, v := range vs {
			results = append(results, string(v.(pulumi.ID)))
		}
		return results
	})
}

func stringOutputArrayToStringArrayOutput(as []pulumi.StringOutput) pulumi.StringArrayOutput {
	var outputs []interface{}
	for _, a := range as {
		outputs = append(outputs, a)
	}
	return pulumi.All(outputs...).ApplyStringArray(func(vs []interface{}) []string {
		var results []string
		for _, v := range vs {
			results = append(results, v.(string))
		}
		return results
	})
}
```

**Comment by sudhanshuraheja** [comment]
@EvanBoyle any Input type can get the base or output variable, so instead of trying to work with strings, I find it easier to create the right array type like so `pulumi.StringArray{pulumi.String("some-name")},`

**Comment by holywend** [comment]
thanks
