### ISSUE TITLE
Provide option to suppress upgrade notifications

### ISSUE THREAD

**Issue by deplorable** [pulumi/pulumi#3864]
Hi folks,

Have been trying to integrate Pulumi into some shell scripts and noticed pulumi keeps displaying a notification to upgrade to the latest version (1.9.1), when using commands like "pulumi stack select STACKNAME" and other commands. 

Is there any way to suppress upgrade notifications like this, with a CLI option like --suppress-upgrade-notifications or similar?

Am currently using a self-managed backend stored locally on my filesystem.

Thanks!

**Comment by deplorable** [comment]
Silly me.
pulumi stack select STACKNAME 2> /dev/null
does what I need -- but would still be nice to have a suppression switch for such things. ^_^

**Comment by lukehoban** [comment]
There is also the `PULUMI_SKIP_UPDATE_CHECK` env var which can be set to skip this - see https://www.pulumi.com/docs/reference/cli/environment-variables/.
