### ISSUE TITLE
Question: Programmatically access the current stack's declared resources

### ISSUE THREAD

**Issue by ilmax** [pulumi/pulumi#3867]
I've just started playing around with pulumi so please be indulgent with me if this sounds silly :) but I'm not able to find a way to iterate over the resources declared in the current stack, I think it will be useful for example (I'm thinking about the C# Azure SDK) to run through all resources to apply a specific tag or to add a lock if the current stack is Production and so on.

Is there any way to iterate over all declared resources in the current stack?

**Comment by lukehoban** [comment]
There is `pulumi.runtime.registerStackTransformation` in Node.js and Python which plays a similar role - it lets you provide a callback which can transform the inputs to any resource that gets constructed as part of the stack.  You could use it to add tags, to keep track of what resources are registered, or anything similar.

It appears it is not yet available in the .NET SDK, but will be as part of .NET GA.

Does that meet your need here?

**Comment by ilmax** [comment]
I think that would do the job for my use case, thanks!
