### ISSUE TITLE
Add aliases to the go code generator

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#3884]
The schema allows a provider to specify aliases for a resource. The code generator needs to emit those aliases into the generated code as default resource options.

**Comment by lukehoban** [comment]
This is probably most impactful for Kubernetes - where we use aliases to establish compatibility across Kubernetes API versions.  cc @lblackstone  and https://github.com/pulumi/pulumi-kubernetes/issues/70.
