### ISSUE TITLE
Getting resourcegroup not found while creating mangement locks on azure

### ISSUE THREAD

**Issue by dokuboyejo** [pulumi/pulumi#3891]
Been getting this now all of a sudden consistently, even though the resource group(s) mentioned exist with resources

`error: locks.ManagementLocksClient#CreateOrUpdateByScope: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'XXXRG' could not be found."
<br/>
    error: locks.ManagementLocksClient#CreateOrUpdateByScope: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'xxxrg01' could not be found."`

**Comment by mikhailshilkov** [comment]
Can you reproduce it with a clean stack? If so, could you post the repro code here?

**Comment by dokuboyejo** [comment]
@mikhailshilkov  that's a little tricky has this is an existing resource group hosting sql managed instance. The strange thing is that out of 3 resource groups marked for locking, one of them worked correctly while the other two failed.

**Comment by dokuboyejo** [comment]
@mikhailshilkov the issue is similar to https://github.com/MicrosoftDocs/azure-docs/issues/17847

**Comment by mikhailshilkov** [comment]
@dokuboyejo As you can imagine, this is even more tricky for me without seeing any of the code and having a way to reproduce the error. "Resource group not found" is quite a generic error and can be a symptom of many different things.

**Comment by dokuboyejo** [comment]
@mikhailshilkov see the code snippet below
`# lock resource group 2
rg02_lock = management.Lock(
    config_rg02['lock']['name'],
    name=config_rg02['lock']['name'],
    lock_level="CanNotDelete",
    notes=f"Resource Group {config_rg02['name']} is locked for delete",
    scope=rg02.id
)`

**Comment by dokuboyejo** [comment]
issue resolved.
it was something to do with the subscription mismatch
