### ISSUE TITLE
`pulumi logs` panic

### ISSUE THREAD

**Issue by JoseAlban** [pulumi/pulumi#3903]
Pulumi Version:   v1.9.1
Go Version:       go1.13.6
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: An assertion has failed

goroutine 1 [running]:
runtime/debug.Stack(0xc000ad94c8, 0x4fdfa00, 0xc000af2840)
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
	/private/tmp/pulumi-20200128-77277-6j7tta/src/github.com/pulumi/pulumi/main.go:30 +0x6e
panic(0x4fdfa00, 0xc000af2840)
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/panic.go:679 +0x1b2
github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
	/private/tmp/pulumi-20200128-77277-6j7tta/src/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:23
github.com/pulumi/pulumi/pkg/util/contract.Assert(...)
	/private/tmp/pulumi-20200128-77277-6j7tta/src/github.com/pulumi/pulumi/pkg/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/backend/filestate.GetLogsForTarget(0xc000aecbd0, 0xc000aa3580, 0x0, 0x0, 0x6fc08f8, 0x6138028, 0xc000aecbd0, 0x0, 0x0)
	/private/tmp/pulumi-20200128-77277-6j7tta/src/github.com/pulumi/pulumi/pkg/backend/filestate/backend.go:629 +0x28a
github.com/pulumi/pulumi/pkg/backend/filestate.(*localBackend).GetLogs(0xc0001c2dc0, 0x55c26c0, 0xc0000440c0, 0x55dfc80, 0xc000a85f80, 0xc000aec630, 0x6fc08f8, 0x6138028, 0xc000aa3580, 0x0, ...)
	/private/tmp/pulumi-20200128-77277-6j7tta/src/github.com/pulumi/pulumi/pkg/backend/filestate/backend.go:623 +0xf3
github.com/pulumi/pulumi/pkg/backend.GetStackLogs(0x55c26c0, 0xc0000440c0, 0x55dfc80, 0xc000a85f80, 0xc000aec630, 0x6fc08f8, 0x6138028, 0xc000aa3580, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200128-77277-6j7tta/src/github.com/pulumi/pulumi/pkg/backend/stack.go:109 +0xdf
github.com/pulumi/pulumi/pkg/backend/filestate.(*localStack).GetLogs(0xc000a85f80, 0x55c26c0, 0xc0000440c0, 0xc000aec630, 0x6fc08f8, 0x6138028, 0xc000aa3580, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200128-77277-6j7tta/src/github.com/pulumi/pulumi/pkg/backend/filestate/stack.go:89 +0xa6
github.com/pulumi/pulumi/cmd.newLogsCmd.func1(0xc000402500, 0x6138028, 0x0, 0x0, 0x11, 0x11)
	/private/tmp/pulumi-20200128-77277-6j7tta/src/github.com/pulumi/pulumi/cmd/logs.go:94 +0x434
github.com/pulumi/pulumi/pkg/util/cmdutil.RunFunc.func1(0xc000402500, 0x6138028, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/pulumi-20200128-77277-6j7tta/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:96 +0x51
github.com/pulumi/pulumi/pkg/util/cmdutil.RunResultFunc.func1(0xc000402500, 0x6138028, 0x0, 0x0)
	/private/tmp/pulumi-20200128-77277-6j7tta/src/github.com/pulumi/pulumi/pkg/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000402500, 0x6138028, 0x0, 0x0, 0xc000402500, 0x6138028)
	/private/tmp/pulumi-20200128-77277-6j7tta/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000124000, 0x0, 0x0, 0x52bfe5d)
	/private/tmp/pulumi-20200128-77277-6j7tta/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/pulumi-20200128-77277-6j7tta/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
	/private/tmp/pulumi-20200128-77277-6j7tta/src/github.com/pulumi/pulumi/main.go:49 +0x63

**Comment by leezen** [comment]
Could you please provide details on what you were trying to do i your pulumi program? Also, does this bug reproduce in the latest version of pulumi?

**Comment by lukehoban** [comment]
@JoseAlban Is it possible this happened when you ran `pulumi logs` on a stack that had never been deployed?

**Comment by stack72** [comment]
I believe this was closed via #5503. Let's close this out and if we find the error again, we can come back to it and re-look at it
