### ISSUE TITLE
Pulumi plugin install $AWS_PLUGIN requires project file - does it have to?

### ISSUE THREAD

**Issue by SwitchedToGitlab** [pulumi/pulumi#3904]
Very minor "issue", more of a request really, or "does it *have* to do that though?" kind of thing...

- Issue: `Pulumi.yaml` is required for a user to install the Pulumi AWS plugin, which makes it harder to build project-ambiguous Docker container images. I can see other potential issues, but this one is mine :)

```
STEP 9: RUN pulumi plugin install $AWS_PLUGIN_VERSION
error: no Pulumi.yaml project file found (searching upwards from /app). If you have not created a project yet, use `pulumi new` to do so
```

- Proposed solution: Don't check for a project file before installing the AWS plugin. 

Is the project file really necessary for this operation? I actually don't see anything about a provider in the file, so I wouldn't think that there would be a dependency there. 

Not a big deal, but it would make life easier and honestly from a functional standpoint. I also think it makes more logical sense this way, but I haven't looked at the code behind this so take that with the appropriate number of grains of salt.

For anyone looking to get around this, you can use a "dummy" `Pulumi.yaml` file then use `pulumi login file://tmp` to login and store the state file locally, which will be discarded when the build is completed. The following appears to work:

*Dockerfile:*
```
FROM pulumi/pulumi:latest as aws
ENV AWS_PLUGIN_VERSION=1.18.0
ENV PROJ_DUMMY_FILE="make/pulumi/Pulumi.yaml"
COPY $PROJ_DUMMY_FILE .
RUN pulumi login file:///tmp
RUN pulumi plugin install $AWS_PLUGIN_VERSION
```
*Pulumi.yaml:* 
```
name: TEST
runtime: python
description: A dummy project file so that we can install Pulumi's AWS plugin
```

Thanks for considering it!

**Comment by stack72** [comment]
Hi @SwitchedToGitlab 

I am going to close this out - this is not the case anymore - we are able to pulumi plugin install at any path on our machines now

```
ls -la
total 0
drwxr-xr-x   2 stack72  staff    64 10 Oct 20:56 .
drwxr-xr-x  84 stack72  staff  2688 10 Oct 20:56 ..

~/code/plugin-install-without-project-file
pulumi plugin install resource aws 3.2.1
[resource plugin aws-3.2.1] installing
Downloading plugin: 69.02 MiB / 69.02 MiB [=========================] 100.00% 8s
Moving plugin... done.

~/code/plugin-install-without-project-file
ls -la
total 0
drwxr-xr-x   2 stack72  staff    64 10 Oct 20:56 .
drwxr-xr-x  84 stack72  staff  2688 10 Oct 20:56 ..
```
