### ISSUE TITLE
Official bridge to GitHub Terraform Provider

### ISSUE THREAD

**Issue by Igorbek** [pulumi/pulumi#3907]
It would be great to have an official provider for GitHub. Terraform has it: https://github.com/terraform-providers/terraform-provider-github

Also, there's a project based on pulumi terraform boilerplate: https://github.com/ibrasho/pulumi-github but it seems to be not maintained at all, and moreover the packages don't work.
There's a blog post about using github https://www.pulumi.com/blog/managing-github-webhooks-with-pulumi/ which demonstrate using dynamic provider for that it appears to be buggy.

I think considering the importance of webhooks-lambda integration, it would be very beneficial to have the official bridge maintained by Pulumi.

**Comment by stack72** [comment]
This has been released to all of your favourite package managers:

* https://pypi.org/project/pulumi-github/
* https://www.nuget.org/packages/Pulumi.GitHub
* https://www.npmjs.com/package/@pulumi/github

**Comment by Igorbek** [comment]
That's awesome, thank you!
