### ISSUE TITLE
Structured Config Secrets behaviour

### ISSUE THREAD

**Issue by robertvanhoesel** [pulumi/pulumi#3911]
A few weeks back I added some structured secrets to our project as described below, this worked wonderfully and all is fine. When I ran Pulumi again today I got several warnings including that the secrets where missing (in an unhandled exception). After re-adding the secrets again like I did a few weeks back, it still didn't work. When I rewrote the implementation to not used structure config with secrets, but instead regular config values things where fine. 

Reading the docs, and seeing that it did work a few weeks back I wonder if I misunderstood something or wether this is a bug.

### Original implementation
Set structured secrets:
`pulumi config set --path --secret MyNamespace:MyKey.some.secretkey '...secret...'`

Resulting config
```yaml
config:
  MyNamespace:MyKey:
    some:
      secretkey:
        secure: ABCDEF1234567890==
```

In code
```ts
let myNamespaceConfig = new Config('MyNamespace:MyKey')
const myKeySecret = myNamespaceConfig.requireSecret

const x = {
  someSecret: myKeySecret('some.secretkey'),
  // ... etc for more secrets and config vars
}

```
Running 2 weeks back (Jan 23) this worked fine. Running this today I get the following unhandled exception:

```
failed with an unhandled exception:
    TypeError: Cannot read property 'require' of undefined
        at requireSecret (.../@pulumi/pulumi/config.js:219:32)
```

After re-adding the secrets in the same way I added them, this still doesn't work.

This occurs in Pulumi SDK & CLI 1.8.1 and 1.10.1 (latest) on OS X using Node 12.10.1

Noteworthy: In the Pulumi Dashboard I don't see these configuration values deployment, it's also missing on the original deployment on Jan 23rd. 

Running `pulumi config refresh' results in a config file without the secrets.

### Rewritten implementation
Set non-structured secrets:
`pulumi config set Namespace:MyKey.some.secretkey '...secret...' --secret`

Resulting config
```yaml
config:
  Namespace:MyKey.some.secretkey:
     secure: ABCDEF1234567890==
```

In code
```ts
let myNamespaceConfig = new Config('MyNamespace')
const myKeySecret = (k: string) => myNamespaceConfig.requireSecret('MyKey.' + k)

const x = {
  someSecret: myKeySecret('some.secretkey'),
  // ... etc for more secrets and config vars
}
```

In this instance in the Pulumi Dashboard, I actually see the secrets being stored in the deployment.

## Questions
1. (How) would structured secrets show up in the Pulumi dashboard?
2. Is this expected behavior or a bug?
3. Why can't I access the namespace key like I originally did?
```js
Config('MyApp:Namespace');
config.requireSecret('some.secretKey')
```
This throws: 
```
error: Missing required configuration variable 'MyApp:Namespace:some.secretKey' 
please set a value using the command 'pulumi config set 
MyApp:Namespace:some.secretKey <value>' 
```
Running the suggested command ironically fails (also, shouldn't it instruct you to actually set is as a secret? #3812)

Thanks!

**Comment by lukehoban** [comment]
@robertvanhoesel Thanks for the very detailed report and repro!  

I think there may be at least two, possibly three, separate issues here related to secrets in nested config.  @justinvp - could you take a look and break down into separate tracking issues if there are in fact multiple independent issues here?

**Comment by justinvp** [comment]
Thanks for the report, @robertvanhoesel!

> Running 2 weeks back (Jan 23) this worked fine.

Hmm, I wouldn’t expect the following code to have ever worked correctly with  `pulumi config set --path --secret MyNamespace:MyKey.some.secretkey '...secret...'`...

```typescript
let myNamespaceConfig = new Config('MyNamespace:MyKey')
const myKeySecret = myNamespaceConfig.requireSecret

const x = {
  someSecret: myKeySecret('some.secretkey'),
  // ... etc for more secrets and config vars
}
```

The first issue is with `new Config('MyNamespace:MyKey')`. The `Config` constructor accepts a namespace, not a namespace & key.

Second, when using nested config structures, they must be accessed as an object via [`getObject`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#Config-getObject)/[`requireObject`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#Config-requireObject) or  [`getSecretObject`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#Config-getSecretObject)/[`requireSecretObject`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#Config-requireSecretObject).

So if you had run the following command:

```bash
pulumi config set --path --secret MyNamespace:MyKey.some.secretkey '...secret...'
```

You’d need to access it like:

```typescript
const config = new Config("MyNamespace");
const myKey = config.requireObject<{ some: { secretkey: string; } }>("MyKey");
const someSecret = myKey.some.secretkey;
```

If you wanted the “secretness” to be maintained inside the Pulumi program, you’d need to treat the whole object as a secret like:

```typescript
const config = new Config("MyNamespace");
const myKey = config.requireSecretObject<{ some: { secretkey: string; } }>("MyKey");
const someSecret = myKey.apply(k => k.some.secretkey);
```

Nested structures that contain secrets are displayed as a secret for the whole nested structure in the Pulumi dashboard. In this case, it'd look like:

<img width="615" alt="Screen Shot 2020-02-12 at 4 52 02 AM" src="https://user-images.githubusercontent.com/710598/74336693-a3907880-4d53-11ea-995c-9682060d8b8b.png">

**Comment by robertvanhoesel** [comment]
Thanks @justinvp for the explanation, that makes a lot more sense! 

I rewrote this piece to the suggested approach and it works perfect.

**Comment by justinvp** [comment]
Sure thing! Glad things are working for you now!

I've also opened a PR to improve our docs around this, to hopefully make it more clear for others in the future: https://github.com/pulumi/docs/pull/2434

**Comment by dokuboyejo** [comment]
How is this achieved in python...getting a similar error
