### ISSUE TITLE
Pulumi and local development with Kubernetes

### ISSUE THREAD

**Issue by vorotech** [pulumi/pulumi#3926]
Hello and thank you for a great product!

I'd like to share the feedback on how do we do the local development and which role is taken by Pulumi. And ask you a few questions about whether we are doing it right or other conceptual ways to achieve the same things are designed.

The target environment is a Kubernetes cluster running in Docker Desktop (Windows/Mac) for developers and GKE cluster in Google Cloud in staging/production.
The Kubernetes cluster deployment is done by Pulumi only for staging/production, and it is managed as a separate stack, so any other services targeting the k8s has the clusterRef in their config.

```yaml
# Pulumi.staging.yaml
config:
  gcp:project: my-project
  kubernetes:clusterStack: my-org/my-cluster/staging
```
Take a look at the dev config we utilize to target the local k8s cluster instead:

```yaml
# Pulumi.dev.yaml
config:
  docker:skipPush: "true"
  kubernetes:isLocal: "true"
  kubernetes:context: docker-desktop
```
As you can see there few custom config variables that we need in order to change the behaviour of the following Pulumi script.

```ts
// Get k8s provider ref
const k8sConfig = new pulumi.Config('kubernetes');
let provider;
if (k8sConfig.getBoolean('isLocal')) {
  provider = new k8s.Provider('k8s', { context: k8sConfig.require('context') });
} else {
  const clusterStack = new pulumi.StackReference(k8sConfig.require('clusterStack'));
  provider = new k8s.Provider("k8s", { kubeconfig: clusterStack.getOutput("kubeConfig") });
}
```

Another statement is applied to the Docker image build process; because we want to avoid pushing it to remote GCR:

```ts
const skipPush = new pulumi.Config('docker').getBoolean('skipPush');
const image = new docker.Image(appName, {
  imageName: skipPush ? imageName : `${registryHostName}/${gcp.config.project}/${imageName}`,
  build: {
    context: '..'  // Build Dockerfile 
  },
  skipPush: skipPush
})
```

And the last, but not the least to use this image properly while creating the Pod we also should consider either it local or remote (`image.imageName` is the unique hash which was not pushed to local Docker):

```ts
// Defined a Pod
const pb = new kx.PodBuilder({
  containers: [
    {
      name: appName,
      image: skipPush ? imageName : image.imageName, // local vs remote image
      imagePullPolicy: 'IfNotPresent', // <-- important for local
      ports: { http: 80 },
    }
  ]
});
```

Another concern we have is when targeting local environment in this way, the ability to use remote persistence at the Pulumi service makes not much sense since it is valid only per single machine.

Looking forward to hearing the thoughts of community and Pulumi dev team.

**Comment by EvanBoyle** [comment]
@vorotech and anyone else interested in this issue:

I'm actually working on a project in this space and would be interested to show you a demo and collect some feedback and understand how you're using pulumi today. If you're interested, feel free to schedule a time that works for you: https://calendly.com/evan-148/30min
