### ISSUE TITLE
Missing required configuration variable even when config is set

### ISSUE THREAD

**Issue by dokuboyejo** [pulumi/pulumi#3927]
I am using pulumi sdk 1.10.1 with pulumi-azure   1.13.0
Config value was set in jenkins ci like so
```
pulumi config set --secret appservices:suser "vusr"
```

In code, when trying to retrieve secret it fails
```
sluser = config.require_secret("suser")
```

```
pulumi:pulumi:Stack <project>-<stack> running error: Missing required configuration variable '<project>:suser'
```

**Comment by dokuboyejo** [comment]
Issue resolved...needed to add --config-file to point to the config path

**Comment by ManivelRamu** [comment]
> Issue resolved...needed to add --config-file to point to the config path

How to do that

**Comment by Frassle** [comment]
It's an option on `pulumi config`
> --config-file string   Use the configuration values in the specified file rather than detecting the file name

**Comment by alter** [comment]
Doesn't work for me (

**Comment by Frassle** [comment]
I think you need to put `--config-file` just after `pulumi` and before `config` in the command, e.g. 
`pulumi --config-file some_config.yaml config set appservices:suser "vusr"`
