### ISSUE TITLE
Run dep ensure as part of Go tests in integration framework

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#3939]
When we are running our Go integration tests, none of our code actually installs the code that is required to actually install the go dependencies

We need to make `dep ensure` run as part of the prepareGoProject

This means there is now a dependency on dep as part of our setup - this needs to be added to our common tool chain

**Comment by lukehoban** [comment]
Note that we'll most likely have to run `pulumi plugin install` manually as well for now.

**Comment by stack72** [comment]
@lukehoban do we need the plugins if we have the sdks installed?

**Comment by lukehoban** [comment]
Yes - as of now we don't automatically acquire plugins as part of SDK installation.  We hope to enable this in the (near) future with https://github.com/pulumi/pulumi/issues/1549.

**Comment by lukehoban** [comment]
We've decided to hold off on this to see if we can land Go modules support first.  Dep doesn't support "npm link"-style dependencies, which are critical for correctness of our testing framework - so there is more work needed if we do intend to keep `dep` much longer.

If we land do modules support by 3/13, we will close this out and move ahead with Go modules-based testing.  If not, we should move ahead with this and put in the work to ensure we have solid test support until we can get to Go modules.
