### ISSUE TITLE
Error with `pulumi logs -f` in Go Pulumi app

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#3947]
`pulumi logs -f` fails with the error `no AWS region found` for each resource in my Pulumi application when my Pulumi application is a **_Go_** application. I've reproduced this across two distinct (but similar) Go Pulumi applications.

Pulumi version is `v1.10.1`.

#### Steps to reproduce

1. `pulumi up` on the [aws-go-lambda](https://github.com/pulumi/examples/tree/master/aws-go-lambda) example 
1. `pulumi logs -f` - observe error

#### Output

```
aws-go-lambda % pulumi up -y --skip-preview
Updating (dev):

     Type                    Name               Status
 +   pulumi:pulumi:Stack     go-lambda-dev      created
 +   ├─ aws:iam:Role         task-exec-role     created
 +   ├─ aws:iam:RolePolicy   lambda-log-policy  created
 +   └─ aws:lambda:Function  basicLambda        created

Outputs:
    lambda: "arn:aws:lambda:us-west-2:052848974346:function:basicLambda-cf098f0"

Resources:
    + 4 created

Duration: 38s

Permalink: https://app.pulumi.com/clstokes/go-lambda/dev/updates/2
aws-go-lambda % pulumi logs -f
Collecting logs for stack dev since 2020-02-20T10:56:46.000-08:00.

error: failed to get logs: 3 errors occurred:
	* no AWS region found
	* no AWS region found
	* no AWS region found

```

**Comment by clstokes** [comment]
If needed, checkpoint file is here - https://gist.github.com/clstokes/700426f4bbbe88f5c04450e7a5b41d3b.

**Comment by gunar** [comment]
I've solved this problem with this command line:

```sh
pulumi config set aws:region $AWS_DEFAULT_REGION
```

**Comment by gunar** [comment]
Aaand I'm back because I just had the same problem today and I just found my own answer above :) Which means I still find it confusing that pulumi accepts `AWS_DEFAULT_REGION` in some places but not in other. Anyway, this is fine.
