### ISSUE TITLE
`no go files listed` error in linux

### ISSUE THREAD

**Issue by spara** [pulumi/pulumi#3955]
**pulumi version:** v1.10.1

**plugins:**
NAME    KIND      VERSION  SIZE    INSTALLED  LAST USED
aws     resource  1.22.0   218 MB  n/a        5 hours ago
docker  resource  0.17.4   44 MB   n/a        5 hours ago

**OS:** ubuntu 18.04.3

**Go version:** go version go1.10.4 linux/amd64

**dep:**
 version     : v0.5.4
 build date  : 2019-07-01
 git hash    : 1f7c19e
 go version  : go1.12.6
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false

**To reproduce:**

```bash
$ pulumi new aws-go
$ dep ensure
$ pulumi up
```
v1.10.1
sophiaparafina@ubuntu:~/go/src/qs$ pulumi up -v 10 --logtostderr
I0220 14:43:10.370640   17962 backend.go:414] found username for access token
I0220 14:43:10.371001   17962 api.go:193] Making Pulumi API call: https://api.pulumi.com/api/stacks/spara/qs/dev
I0220 14:43:10.800064   17962 api.go:209] Pulumi API call response code (https://api.pulumi.com/api/stacks/spara/qs/dev): 200 OK
I0220 14:43:10.801309   17962 backend.go:414] found username for access token
Previewing update (dev):
I0220 14:43:10.801670   17962 api.go:193] Making Pulumi API call: https://api.pulumi.com/api/stacks/spara/qs/dev/update
I0220 14:43:11.000670   17962 api.go:209] Pulumi API call response code (https://api.pulumi.com/api/stacks/spara/qs/dev/update): 200 OK
I0220 14:43:11.001375   17962 ignore.go:44] Explicitly ignoring and discarding error: no git repository found from /home/sophiaparafina/go/src/qs/Pulumi.yaml
I0220 14:43:11.002114   17962 api.go:193] Making Pulumi API call: https://api.pulumi.com/api/stacks/spara/qs/dev/update/bf72f302-8c05-4209-ab7c-ae0c2e574f43
I0220 14:43:11.189693   17962 api.go:209] Pulumi API call response code (https://api.pulumi.com/api/stacks/spara/qs/dev/update/bf72f302-8c05-4209-ab7c-ae0c2e574f43): 200 OK
I0220 14:43:11.189962   17962 backend.go:414] found username for access token
I0220 14:43:11.189784   17962 backend.go:886] Stack dev being updated to version 1
I0220 14:43:11.190209   17962 api.go:193] Making Pulumi API call: https://api.pulumi.com/api/stacks/spara/qs/dev/update/bf72f302-8c05-4209-ab7c-ae0c2e574f43/renew_lease
I0220 14:43:11.368193   17962 api.go:209] Pulumi API call response code (https://api.pulumi.com/api/stacks/spara/qs/dev/update/bf72f302-8c05-4209-ab7c-ae0c2e574f43/renew_lease): 200 OK
I0220 14:43:11.368352   17962 api.go:193] Making Pulumi API call: https://api.pulumi.com/api/stacks/spara/qs/dev/export
I0220 14:43:11.441030   17962 api.go:209] Pulumi API call response code (https://api.pulumi.com/api/stacks/spara/qs/dev/export): 200 OK
I0220 14:43:11.441567   17962 plugins.go:76] gatherPluginsFromProgram(): gathering plugins from language host
I0220 14:43:11.441668   17962 plugins.go:427] GetPluginPath(language, go, <nil>): found on $PATH /home/sophiaparafina/.pulumi/bin/pulumi-language-go
I0220 14:43:11.441684   17962 plugin.go:82] Launching plugin 'go' from '/home/sophiaparafina/.pulumi/bin/pulumi-language-go' with args: 127.0.0.1:41109
I0220 14:43:11.450206   17962 langruntime_plugin.go:170] langhost[go].GetPluginInfo() executing
I0220 14:43:11.450736   17962 langruntime_plugin.go:83] langhost[go].GetRequiredPlugins(proj=qs,pwd=/home/sophiaparafina/go/src/qs,program=.) executing
I0220 14:43:11.451107   17962 langruntime_plugin.go:125] langhost[go].GetRequiredPlugins(proj=qs,pwd=/home/sophiaparafina/go/src/qs,program=.) success: #versions=0
I0220 14:43:11.451205   17962 plugins.go:83] gatherPluginsFromProgram(): plugin go <nil> () is required by language host
I0220 14:43:11.451301   17962 plugins.go:95] gatherPluginsFromSnapshot(): gathering plugins from snapshot
I0220 14:43:11.451390   17962 plugins.go:127] ensurePluginsAreInstalled(): beginning
I0220 14:43:11.451577   17962 plugins.go:427] GetPluginPath(language, go, <nil>): found on $PATH /home/sophiaparafina/.pulumi/bin/pulumi-language-go
I0220 14:43:11.451666   17962 plugins.go:132] ensurePluginsAreInstalled(): plugin go <nil> already installed
I0220 14:43:11.451754   17962 plugins.go:147] ensurePluginsAreInstalled(): completed
I0220 14:43:11.451844   17962 plugins.go:215] computeDefaultProviderPlugins(): language host reported empty set of provider plugins, using all plugins
I0220 14:43:11.458061   17962 plugins.go:234] computeDefaultProviderPlugins(): considering go
I0220 14:43:11.458214   17962 plugins.go:237] computeDefaultProviderPlugins(): skipping go, not a resource provider
I0220 14:43:11.458769   17962 plugins.go:271] computeDefaultProviderPlugins(): summary of default plugins:
I0220 14:43:11.460261   17962 step_generator.go:811] stepGenerator.GeneratePendingDeletes(): scanning previous snapshot for pending deletes
I0220 14:43:11.465604   17962 plan_executor.go:391] planExecutor.retirePendingDeletes(...): no pending deletions
I0220 14:43:11.465724   17962 plan_executor.go:215] planExecutor.Execute(...): waiting for incoming events
I0220 14:43:11.465421   17962 langruntime_plugin.go:136] langhost[go].Run(pwd=/home/sophiaparafina/go/src/qs,program=.,#args=0,proj=qs,stack=dev,#config=1,dryrun=true) executing
I0220 14:43:11.466073   17962 step_executor.go:321] StepExecutor worker(-2): worker coming online
I0220 14:43:11.466179   17962 step_executor.go:321] StepExecutor worker(-2): worker waiting for incoming chains
I0220 14:43:11.483536   17962 eventsink.go:79] eventSink::Infoerr(<{%reset%}>go run: no go files listed
<{%reset%}>)
     Type                 Name    Plan     Info
     pulumi:pulumi:Stack  qs-dev           go run: no go files listed
I0220 14:43:11.488600   17962 langruntime_plugin.go:163] langhost[go].RunPlan(pwd=/home/sophiaparafina/go/src/qs,program=.,...,dryrun=true) success: progerr=program exited with non-zero exit code: 1
I0220 14:43:11.489819   17962 source_eval.go:167] EvalSourceIterator ended with an error: an unhandled error occurred: program exited with non-zero exit code: 1
I0220 14:43:11.489937   17962 plan_executor.go:219] planExecutor.Execute(...): incoming event (nil? true, &{0xc000d3d820})
I0220 14:43:11.490029   17962 eventsink.go:87] eventSink::Error(<{%reset%}>an unhandled error occurred: program exited with non-zero exit code: 1<{%reset%}>)
I0220 14:43:11.490107   17962 step_executor.go:321] StepExecutor worker(-1): StepExecutor.waitForCompletion(): waiting for worker threads to exit
I0220 14:43:11.490174   17962 step_executor.go:321] StepExecutor worker(-2): worker exiting due to cancellation
I0220 14:43:11.490239   17962 step_executor.go:321] StepExecutor worker(-1): StepExecutor.waitForCompletion(): worker threads all exited
I0220 14:43:11.490305   17962 plan_executor.go:254] planExecutor.Execute(...): step executor has completed
I0220 14:43:11.490383   17962 plan_executor.go:131] planExecutor.Execute(...): exiting provider canceller
I0220 14:43:11.490464   17962 ignore.go:44] Explicitly ignoring and discarding error: rpc error: code = Canceled desc = grpc: the client connection is closing
I0220 14:43:11.491992   17962 api.go:193] Making Pulumi API call: https://api.pulumi.com/api/stacks/spara/qs/dev/     pulumi:pulumi:Stack  qs-dev           1 error; 1 message
Diagnostics:
  pulumi:pulumi:Stack (qs-dev):
    go run: no go files listed
    error: an unhandled error occurred: program exited with non-zero exit code: 1
I0220 14:43:11.681841   17962 api.go:209] Pulumi API call response code (https://api.pulumi.com/api/stacks/spara/qs/dev/update/bf72f302-8c05-4209-ab7c-ae0c2e574f43/events/batch): 200 OK
I0220 14:43:11.682070   17962 api.go:193] Making Pulumi API call: https://api.pulumi.com/api/stacks/spara/qs/dev/update/bf72f302-8c05-4209-ab7c-ae0c2e574f43/complete
I0220 14:43:11.861247   17962 api.go:209] Pulumi API call response code (https://api.pulumi.com/api/stacks/spara/qs/dev/update/bf72f302-8c05-4209-ab7c-ae0c2e574f43/complete): 204 No Content

**expected outcome:**

pulumi displays resource graph and asks to deploy

**Comment by stack72** [comment]
Closing this out - this will be tested continuously as part of the templates testing
