### ISSUE TITLE
How to pull an image from a private registry using C#?

### ISSUE THREAD

**Issue by sfmskywalker** [pulumi/pulumi#3956]
Scenario:

* My Pulumi project creates an AKS cluster + Azure Container Registry resource.
* It then builds a Docker image from a DockerFile and pushes it to the private ACR.
* It creates a k8s Deployment with a Pod template referencing the image.

When doing `pulumi up` however, the process hangs at the step when creating the deployment and the pod. The pod is created, but when inspecting its status, I see the following:

```
Type     Reason     Age                From                                        Message
  ----     ------     ----               ----                                        -------
  Normal   Scheduled  98s                default-scheduler                           Successfully assigned default/identity-uz6yngrk-56f4bf4b87-pht6h to aks-agentpool-29795503-vmss000000
  Normal   Pulling    52s (x3 over 95s)  kubelet, aks-agentpool-29795503-vmss000000  Pulling image "devyaregistry.azurecr.io/identity:94ee6762824d9594251d92e35c1b699703f2df2f03bac7d86f1733a4de1c6f43"
  Warning  Failed     52s (x3 over 95s)  kubelet, aks-agentpool-29795503-vmss000000  Failed to pull image "devyaregistry.azurecr.io/identity:94ee6762824d9594251d92e35c1b699703f2df2f03bac7d86f1733a4de1c6f43": rpc error: code = Unknown desc = Error response from daemon: Get https://devyaregistry.azurecr.io/v2/identity/manifests/94ee6762824d9594251d92e35c1b699703f2df2f03bac7d86f1733a4de1c6f43: unauthorized: authentication required
  Warning  Failed     52s (x3 over 95s)  kubelet, aks-agentpool-29795503-vmss000000  Error: ErrImagePull
  Normal   BackOff    12s (x6 over 94s)  kubelet, aks-agentpool-29795503-vmss000000  Back-off pulling image "devyaregistry.azurecr.io/identity:94ee6762824d9594251d92e35c1b699703f2df2f03bac7d86f1733a4de1c6f43"   Warning  Failed     12s (x6 over 94s)  kubelet, aks-agentpool-29795503-vmss000000  Error: ImagePullBackOff
```

Which I guess makes sense: the Deployment isn't referencing any Docker pull secrets.

After searching the web, I came across this SO post with the exact same issue:

https://stackoverflow.com/questions/59882357/pulumi-how-to-pull-a-docker-image-from-a-private-registry

One of the answers explains that one must first create a Secret and reference that secret from the Pod template.

This all makes sense. However, I don't seem to be able to find an API that helps me create such a Secret. I can of course do so manually using `kubectl` as described in the [Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/), but I want to do it programmtically. The Kubernetes docs do describe in detail what the `regcred` secret looks like (e.g. `{"auths":{"your.private.registry.example.com":{"username":"janedoe","password":"xxxxxxxxxxx","email":"jdoe@example.com","auth":"c3R...zE2"}}}`), so I could probably create it programmatically. But I'm hoping there's an easier way that I somehow missed.

Any pointer would be much appreciated!

**Comment by sfmskywalker** [comment]
I also considered using the `Docker.DotNet` package and its `DockerClient` API to generate the secret. However, it seems like the `Output<T>` type doesn't have the convenient `RequireValueAsync` method like the `StackReference` type does. Otherwise I could leverage DockerClient and pass the necessary details (server URL, admin username + password for basic auth).

**Comment by mikhailshilkov** [comment]
Have a look at [this example](https://github.com/pulumi/examples/blob/master/azure-ts-aks-keda/keda.ts#L129) -- it's TypeScript, but sounds like what you are asking for?

**Comment by sfmskywalker** [comment]
That indeed looks like exactly what I need. Will try it out tomorrow. Thanks!

**Comment by sfmskywalker** [comment]
I tried it out and it worked a charm! Here's my C# version that creates an Azure Container registry and then a k8s secret that can be used to pull images from said registry:

```csharp
// Create container registry.
var registryName = $"my-registry";
var registry = new Registry(registryName, new RegistryArgs
{
    Name = registryName,
    ResourceGroupName = resourceGroupName,
    Sku = "Basic",
    AdminEnabled = true
});

// Create a k8s secret for use when pulling images from the container registry.
var dockerCfg = Output.All<string>(registry.LoginServer, registry.AdminUsername, registry.AdminPassword).Apply(values =>
{
    var r = new Dictionary<string, object>();
    var server = values[0];
    var username = values[1];
    var password = values[2];
    r[server] = new
    {
        email = "notneeded@acme.com",
        username,
        password
    };

    return r;
});

// Serialize & base64 encode the secret data. 
var dockerCfgString = dockerCfg.Apply(x => Convert.ToBase64String(Encoding.UTF8.GetBytes(System.Text.Json.JsonSerializer.Serialize(x))));

// Create the secret.
var dockerPullSecret = new Pulumi.Kubernetes.Core.V1.Secret("registry-secret", new SecretArgs
{
    Data =
    {
        { ".dockercfg", dockerCfgString }
    },
    Type = "kubernetes.io/dockercfg",
    Metadata = new ObjectMetaArgs
    {
        Name = $"registry-secret"
    }
}, new CustomResourceOptions
{
    Provider = provider // a k8s provider created earlier, not shown here in this code snippet.
});
```

I then exported the secret name like so:

```csharp
return new Dictionary<string, object?>
{
    ["container-registry:secret-name"] = dockerPullSecret.Metadata.Apply(x => x.Name)
```

Then from my other Pulumi project, I can simply reference the exported secret name as a Docker pull secret:

```csharp
var infra = new StackReference($"sfmskywalker/infra");
var dockerPullSecretName = infra.RequireOutput($"container-registry:secret-name").Apply(x => (string) x);

var deployment = new Pulumi.Kubernetes.Apps.V1.Deployment(serviceName, new DeploymentArgs
    {
        Spec = new DeploymentSpecArgs
        {
            Selector = new LabelSelectorArgs
            {
                MatchLabels = new InputMap<string>
                {
                    { "app", $"app-{serviceName}" },
                },
            },
            Replicas = 1,
            Template = new PodTemplateSpecArgs
            {
                Metadata = new ObjectMetaArgs
                {
                    Labels = new InputMap<string>
                    {
                        { "app", $"app-{serviceName}" },
                    },
                    Name = serviceName
                },
                Spec = new PodSpecArgs
                {
                    Containers = new List<ContainerArgs>
                    {
                        new ContainerArgs
                        {
                            Name = serviceName,
                            Image = image.ImageName,,
                            
                        }
                    },
                    // Specify docker pull secret name:
                    ImagePullSecrets = new LocalObjectReferenceArgs
                    {
                        Name = registrySecretName
                    }
                }
            }
        }
    }, new CustomResourceOptions
    {
        Provider = k8sProvider
    });
```

**Comment by mikhailshilkov** [comment]
If you feel it's useful, we always accept donations in terms of PRs to the examples repo

**Comment by sfmskywalker** [comment]
That’s a great idea. I think this is mighty useful and will work on a PR.

**Comment by sfmskywalker** [comment]
Here you go: https://github.com/pulumi/examples/pull/574. Do let me know if there's anything you would like see changed.
