### ISSUE TITLE
Add backend argument to pulumi cli

### ISSUE THREAD

**Issue by remorses** [pulumi/pulumi#3966]
I want to use the pulumi cli in a server, where a request can trigger a deploy, I will keep the pulumi state in different folders in a s3 bucket based on request

The problem is that the state backend (the s3 bucket path) is configured globally with `pulumi login` but I need to specify the bucket for every command invocation because requests can be concurrent

It would be cool to add a `--backend` argument to specify the bucket and overwrite the `pulumi login` bucket

**Comment by remorses** [comment]
I will place everything on the same project

**Comment by lukehoban** [comment]
Just a note that this is very related to what’s tracked in https://github.com/pulumi/pulumi/issues/3747, and we definitely plan to improve support for this - effectively moving the backend to be tracked as part of the stack.
