### ISSUE TITLE
Read doesn't seem to honor additionalSecretOutputs

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi#3976]
I tried setting the `additionalSecretOutputs` option on a `get` method, but it does not seem to be marking the selected output as secret.

To reproduce, run the following on a Kubernetes cluster:
```
kubectl create namespace foo
```

Then, run the following program:
```ts
import * as k8s from "@pulumi/kubernetes";

const ns = k8s.core.v1.Namespace.get("foo", "foo", {additionalSecretOutputs: ["metadata"]})
export const metadata = ns.metadata;
```

The exported variable is not marked secret/encrypted.
```
metadata: {
        creationTimestamp: "2020-02-25T20:14:59Z"
        name             : "foo"
        resourceVersion  : "651896"
        selfLink         : "/api/v1/namespaces/foo"
        uid              : "22e99401-a5ae-451d-8626-cdab547b5530"
    }
```
---

This works as expected for resource creation:
```
const ns = new k8s.core.v1.Namespace("foo", {metadata: {name: "foo"}}, {additionalSecretOutputs: ["metadata"]})
export const metadata = ns.metadata;
```
```
metadata: "[secret]"
```

**Comment by EvanBoyle** [comment]
Not familiar with the typescript impl, but I implemented this in the go SDK. One thing that stands out is that in `registerResource` we set `additionalSecretOutputs` on the request, but I don't see this value getting set for `readResource`. Am I missing something there? 

https://github.com/pulumi/pulumi/blob/9abcca345a6c024087b35152b0d6fca92baef191/sdk/nodejs/runtime/resource.ts#L179-L195

https://github.com/pulumi/pulumi/blob/9abcca345a6c024087b35152b0d6fca92baef191/sdk/nodejs/runtime/resource.ts#L111-L119

**Comment by lblackstone** [comment]
Good catch @EvanBoyle -- I confirmed this fix and opened a PR.
