### ISSUE TITLE
No module named 'google.protobuf.pyext._message'

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#3981]
It looks like https://github.com/pulumi/pulumi/pull/3895 may have introduced a regression in `1.11.0` for some Python use cases.  

A user reports seeing this:
![01782FF1-D292-460A-9ACD-4455C2591AE1](https://user-images.githubusercontent.com/223467/75379501-57345500-588a-11ea-8ffc-2d11f076b064.png)

With this:

![image (11)](https://user-images.githubusercontent.com/223467/75379504-57cceb80-588a-11ea-8c37-0d69491168a0.png)

**Comment by lblackstone** [comment]
I was able to reproduce the error on a Windows VM, but not on Mac.

**Comment by lblackstone** [comment]
It appears that https://github.com/pulumi/pulumi-kubernetes/issues/984 does not affect Windows, so I should be able to conditionally include this import only on other OS's.

Confirmed that things were working as expected with `pulumi-kubernetes==1.5.4` (which uses `pulumi==1.10.0`)

**Comment by henninge** [comment]
Seeing this again on MacOS 10.15.7, pulumi installed via brew.

```
$ pulumi version
v2.12.1
$ venv/bin/pip3 freeze
Arpeggio==1.10.1
attrs==20.2.0
dill==0.3.3
grpcio==1.33.2
parver==0.3.1
protobuf==3.13.0
pulumi==2.12.1
pulumi-aws==3.11.0
semver==2.13.0
six==1.15.0
$ venv/bin/python --version
Python 3.9.0
```

It looks like it is a bug in protobuf, though, because there is actually no defintion for `SetAllowOversizeProtos` in the lib. A bit unfortunate as it breaks the quickstart guide.

**Comment by huydinhle** [comment]
I got the exact same issue today. Can't run pulumi anymore, any idea on how to workaround?

**Comment by henninge** [comment]
I commented out lines 42-44 in `venv/lib/python3.9/site-packages/pulumi/runtime/invoke.py`

**Comment by huydinhle** [comment]
it works @henninge . Thank you !!!

**Comment by lukehoban** [comment]
@henninge @huydinhle It sounds like this might be related to Python 3.9 - support for which is being tracked in https://github.com/pulumi/pulumi/issues/5662.
