### ISSUE TITLE
Don't mark policy and watch commands as experimental

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#3985]
We decided to stop guarding `policy` and `watch` commands using the experimental flag (see [here](https://github.com/pulumi/pulumi/blob/8a0987c892e86706bd3affb6eb934aa084a85c09/cmd/pulumi.go#L200)). Instead, we should show them and just clearly mark them in the UI as "experimental."

For example:

```
Available Commands:
  cancel         Cancel a stack's currently running update, if any
  config         Manage configuration
  destroy        Destroy an existing stack and its resources
...
  policy         (preview) Manage resource policies
...
  watch          (preview) Continuously update the resources in a stack
...
```

The rationale here is to drive usage and solicit more feedback, rather than hiding them.

I assume we still want to keep `query` as an experimental command.

**Comment by justinvp** [comment]
I plan to take care of this for PaC this milestone: https://github.com/pulumi/pulumi-policy/issues/196

**Comment by joeduffy** [comment]
Ah great, feel free to dupe. Didn't think to look in that repo as this is a CLI thing, not the pulumi-policy package. Can you do it for `watch` while you're there?

**Comment by justinvp** [comment]
I'll keep this issue and dupe the other. I'll take care of `watch` as well.
