### ISSUE TITLE
[CLI] Configure to use organization by default

### ISSUE THREAD

**Issue by SpainTrain** [pulumi/pulumi#3989]
## Problem

Currently, running a command like `pulumi new` creates the project and stack in one's personal Pulumi account.  All of my projects and stacks are in our Pulumi organization, so this creates some overhead moving stacks into the organization manually.

**EDIT**

```
pulumi new -s <org>/<stackname>
```

is possible, and solves the problem.  However, this does still require remembering to add the flag every time, even if every project/stack is always made in the same org (and my memory isn't amazing :grin:).

## Feature Suggestion

~~Provide a CLI command and/or flag and/or environment variable which sets the organization/account to be used by commands.~~

**EDIT**

Provide an environment variable and/or wizard option to set default org.

## Related Issues

- https://github.com/pulumi/pulumi/issues/3539 (Requests a superset of what this issue is requesting)
- https://github.com/pulumi/pulumi/issues/1421 (Provides guidance on how to get around part of this limitation)

## Other Background

Based on Slack thread: https://pulumi-community.slack.com/archives/C84L4E3N1/p1582825218176200?thread_ts=1582824975.176100&cid=C84L4E3N1

**Comment by justinvp** [comment]
It is possible to do this today with:

```bash
pulumi new -s <org>/<stackname>
```

**Comment by kevink** [comment]
Would it make any sense to put the target org and stackname in the pulumi.yml like the way we can config the default aws region?

**Comment by ringods** [comment]
I raised #3747 a while back regarding working against multiple backends. Maybe add this ticket to the `Related Issues` in the description of this issue.

**Comment by clstokes** [comment]
Related to https://github.com/pulumi/pulumi/issues/4826
