### ISSUE TITLE
Resources summary is omitted if Pulumi app produces console output

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#3993]
#### Problem 

If my Pulumi application produces console output (e.g. `console.log()`), the `Resources` summary doesn't get output as well.

#### Suggestion

Always print the `Resources` summary.

#### Steps to reproduce

1. `preview` the code below
1. uncomment the `console.log` line
1. `preview` again - observe `Resources` is missing.

#### Code to reproduce

```ts
import * as aws from "@pulumi/aws";

const vpc = new aws.ec2.Vpc("main",{
    cidrBlock: "10.0.0.0/16",
});

// console.log("adsf") <- uncomment this line
```

#### Output

```
aws-ts-webserver % pulumi preview
Previewing update (demo):
     Type                 Name                        Plan       
 +   pulumi:pulumi:Stack  demo-aws-ts-webserver-demo  create     
 +   └─ aws:ec2:Vpc       main                        create     
 
Resources:
    + 2 to create

Permalink: https://app.pulumi.com/clstokes/demo-aws-ts-webserver/demo/previews/d67021e3-eaa6-4adf-a169-c925d36cd9fe
aws-ts-webserver % banner adding console.log        

############################################################################
#
# adding console.log
#
############################################################################

aws-ts-webserver % pulumi preview                    
Previewing update (demo):
     Type                 Name                        Plan       Info
 +   pulumi:pulumi:Stack  demo-aws-ts-webserver-demo  create     1 message
 +   └─ aws:ec2:Vpc       main                        create     
 
Diagnostics:
  pulumi:pulumi:Stack (demo-aws-ts-webserver-demo):
    adsf
 

Permalink: https://app.pulumi.com/clstokes/demo-aws-ts-webserver/demo/previews/3eb7953b-ff07-43fb-a231-5e44c754a555
```

**Comment by joeduffy** [comment]
Wow, I've noticed this strange behavior while demoing, and it seemed vaguely inconsistent to me, but I never realized it was console logging that was the difference... Good find! 🕵

**Comment by clstokes** [comment]
This occurs when any diagnostics information is printed from the application, including [incompatible versions](https://github.com/pulumi/pulumi/issues/4234) and policy violations.

**Comment by clstokes** [comment]
accidentally closed

**Comment by mikhailshilkov** [comment]
Still repro's with 3.33.2

**Comment by justinvp** [comment]
This no longer repos with recent versions of the CLI. I believe it was fixed by https://github.com/pulumi/pulumi/pull/13264
