### ISSUE TITLE
config.Get silently converts object to string

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#3997]
#### Problem

If I mistakenly use `config.Get()` to get a configuration value that's actually a list, the value is returned as a string without a warning or error to the user.

~~TypeScript handles this better by throwing an error, but the error message could likely be improved to mention the type issue. See https://gist.github.com/clstokes/e90c0ebf77a89663f934726f3209e09e for code and output.~~

#### Suggestion

Throw an error when an obviously wrong type is retrieved via config.

#### Steps to reproduce

1. `pulumi stack init gh-issue`
1. Set config values

    ```
    pulumi config set --path 'regions[0]' us-west-2
    pulumi config set --path 'regions[0]' us-east-1
    ```

1. `preview` - observe no error and unexpected type conversion

#### Code to reproduce

```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"github.com/pulumi/pulumi/sdk/go/pulumi/config"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		config := config.New(ctx, "")

		var regionsAsList []string
		config.GetObject("regions", &regionsAsList)

		fmt.Printf("regionsAsList - %v\n", regionsAsList)

		regionsAsString := config.Get("regions")
		fmt.Printf("regionsAsString - %v\n", regionsAsString)

		fmt.Printf("eof\n")

		return nil
	})
}
```

#### Output

```
pulumi-go-readobject % pulumi preview
Previewing update (dev):
     Type                 Name                      Plan     Info
     pulumi:pulumi:Stack  pulumi-go-readobject-dev           3 messages
 
Diagnostics:
  pulumi:pulumi:Stack (pulumi-go-readobject-dev):
    regionsAsList - [asdf zxvc]
    regionsAsString - ["asdf","zxvc"]
    eof
 

Permalink: https://app.pulumi.com/clstokes/pulumi-go-readobject/dev/previews/f3d552ee-76d3-49dc-9388-22eb29766b62
pulumi-go-readobject % 
```

**Comment by lukehoban** [comment]
> TypeScript handles this better by throwing an error

I don’t think that’s true. All languages should behave the same way here - and that behavior is, at least until a significant overhaul of and breaking change to, config - by design. 

The error you are seeing in the linked TS example seems to be about missing required config entirely. Note that the error is coming from the `requireObject` not the `require`.

**Comment by clstokes** [comment]
You're right, the config was missing. 🤦‍♂ 

Closing this as "by design".
