### ISSUE TITLE
Expected diff to not require deletion or replacement during Update

### ISSUE THREAD

**Issue by logicbomb421** [pulumi/pulumi#3998]
I am attempting to import a GKE cluster. Importing the cluster and node pools succeeds, however, when I remove the import IDs and rerun `up`, the following error is thrown:

```
Diagnostics:
  pulumi:pulumi:Stack (kubernetes-delete-me):
    panic: fatal: An assertion has failed: Expected diff to not require deletion or replacement during Update of urn:pulumi:delete-me::kubernetes::gcp:container/cluster:Cluster::kubernetes|delete-me|test-cluster-1|us-central1-c
    goroutine 54 [running]:
    github.com/pulumi/pulumi/pkg/util/contract.failfast(...)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.9.1/pkg/util/contract/failfast.go:23
    github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc000492400, 0x3537dda, 0x48, 0xc0006bb718, 0x1, 0x1)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.9.1/pkg/util/contract/assert.go:33 +0x197
    github.com/pulumi/pulumi-terraform-bridge/pkg/tfbridge.(*Provider).Update(0xc000542780, 0x398e6c0, 0xc0009be9f0, 0xc00093db90, 0xc000542780, 0x3041a01, 0xc00098d5c0)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi-terraform-bridge@v1.6.5/pkg/tfbridge/provider.go:805 +0x81d
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler.func1(0x398e6c0, 0xc0009be9f0, 0x33e6fa0, 0xc00093db90, 0x33e5e20, 0x4a2ca18, 0x398e6c0, 0xc0009be9f0)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.9.1/sdk/proto/go/provider.pb.go:1651 +0x86
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x398e6c0, 0xc00098be90, 0x33e6fa0, 0xc00093db90, 0xc00099d9c0, 0xc00099d9e0, 0x0, 0x0, 0x39576a0, 0xc000220c50)
    	/home/travis/gopath/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20171105060200-01f8541d5372/go/otgrpc/server.go:61 +0x36e
    github.com/pulumi/pulumi/sdk/proto/go._ResourceProvider_Update_Handler(0x3449340, 0xc000542780, 0x398e6c0, 0xc00098be90, 0xc0000925a0, 0xc0002f3920, 0x398e6c0, 0xc00098be90, 0xc0007bc000, 0x1b6c)
    	/home/travis/gopath/pkg/mod/github.com/pulumi/pulumi@v1.9.1/sdk/proto/go/provider.pb.go:1653 +0x14b
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000542600, 0x39c7120, 0xc0004d8a80, 0xc0007b4400, 0xc000660120, 0x49fc220, 0x0, 0x0, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1024 +0x4f4
    google.golang.org/grpc.(*Server).handleStream(0xc000542600, 0x39c7120, 0xc0004d8a80, 0xc0007b4400, 0x0)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1313 +0xd97
    google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000728030, 0xc000542600, 0x39c7120, 0xc0004d8a80, 0xc0007b4400)
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:722 +0xbb
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:720 +0xa1

    error: update failed

  gcp:container:Cluster (kubernetes|delete-me|test-cluster-1|us-central1-c):
    error: transport is closing
```

Oddly this is something I have done before without issue. I even force removed the stack and re-imported, as well as trying a state refresh. Both were unsuccessful.

Please let me know if more information is needed.

---

#### Version Info
- pulumi: `1.11.1` (`@pulumi/pulumi` is identical)
- pulumi gcp plugin: `2.7.0` (`@pulumi/gcp` is identical)
- node: `10.14.2`

**Comment by leezen** [comment]
Was there a diff details provided as well when you ran this? If so, could you please provide it?

**Comment by logicbomb421** [comment]
@leezen there was indeed:

```
Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:delete-me::kubernetes::pulumi:pulumi:Stack::kubernetes-delete-me]
    ~ gcp:container/cluster:Cluster: (update)
        [id=projects/bv-k8s-development/locations/us-central1-c/clusters/test-cluster-1]
        [urn=urn:pulumi:delete-me::kubernetes::gcp:container/cluster:Cluster::kubernetes|delete-me|test-cluster-1|us-central1-c]
        [provider=urn:pulumi:delete-me::kubernetes::pulumi:providers:gcp::default_2_7_0::be655922-b2b4-4641-8c9e-4dca5cb5e706]
      + minMasterVersion     : "1.14.10-gke.17"
      + removeDefaultNodePool: false
```

The actual program provides these args based on whether or not we're importing the resource (I ran into issues when not setting these to `undefined` during imports):
```ts
// this is the interface for `config` below
interface ClusterConfig {
  importFrom?: string;
  nodePools: NodePoolConfig[];
  locations: string[];
  clusterArgs: gcp.container.ClusterArgs;
};
// ---
minMasterVersion: config.importFrom ? undefined : config.clusterArgs.minMasterVersion,
removeDefaultNodePool: config.importFrom ? undefined : config.clusterArgs.removeDefaultNodePool,
```
I have previously imported several clusters successfully in this way. I was testing something in isolation before performing the import on our production cluster, and this issue popped up.

**Comment by logicbomb421** [comment]
More info: Just created a second test cluster, imported it into a new Pulumi stack, and then attempted `up` again after removing the import IDs and got the same issue.

**Comment by leezen** [comment]
Interesting. This would suggest that somehow as part of import, we're not pulling in those two values. As a temporary workaround, you could try doing a `pulumi refresh --target <urn>` for the imported cluster resource. Then, your statefile will now include those two missing attributes. Hopefully that lets you make forward progress. I'll keep this issue open as a bug.

**Comment by logicbomb421** [comment]
@leezen thank you for the suggestion, however it does not appear to have gotten me past this issue.

I ran the following:
```
pulumi refresh --target 'urn:pulumi:test-cluster-2::kubernetes::gcp:container/cluster:Cluster::kubernetes|test-cluster-2|test-cluster-2|us-central1-c'
```

which resulted in:
```
Previewing refresh (betterview/test-cluster-2):
     Type                      Name                                                    Plan
     pulumi:pulumi:Stack       kubernetes-test-cluster-2
     └─ gcp:container:Cluster  kubernetes|test-cluster-2|test-cluster-2|us-central1-c

Resources:
    1 unchanged

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be. details

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be. yes
Refreshing (betterview/test-cluster-2):
     Type                      Name                                                    Status
     pulumi:pulumi:Stack       kubernetes-test-cluster-2
     └─ gcp:container:Cluster  kubernetes|test-cluster-2|test-cluster-2|us-central1-c

Resources:
    1 unchanged

Duration: 1s
```

Then once complete, I re-ran `pulumi up` with the same error message.

I also tried the same steps inside a docker container running `pulumi/pulumi:latest` in order to rule out something local to my machine, however the same issue persisted.

**Comment by logicbomb421** [comment]
More info: Just had a colleague check out my branch and reinitialize everything from scratch on his laptop (all versions are the same) and he is also receiving this error.

**Comment by leezen** [comment]
Ah... I just realized I read the diff in the wrong direction. Those are new values it's trying to apply to the cluster (not the other way around). Does it crash if you do a targeted up for just the cluster?

**Comment by logicbomb421** [comment]
Unfortunately it does still crash when targeting just the cluster:

```
pulumi up --target='urn:pulumi:test-cluster-2::kubernetes::gcp:container/cluster:Cluster::kubernetes|test-cluster-2|test-cluster-2|us-central1-c'
```
The above produces the same diff:
```
Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:test-cluster-2::kubernetes::pulumi:pulumi:Stack::kubernetes-test-cluster-2]
    ~ gcp:container/cluster:Cluster: (update)
        [id=projects/bv-k8s-development/locations/us-central1-c/clusters/test-cluster-2]
        [urn=urn:pulumi:test-cluster-2::kubernetes::gcp:container/cluster:Cluster::kubernetes|test-cluster-2|test-cluster-2|us-central1-c]
        [provider=urn:pulumi:test-cluster-2::kubernetes::pulumi:providers:gcp::default_2_7_0::b0c811e9-3a52-404e-b592-d6c98ee2393d]
      + minMasterVersion     : "1.14.10-gke.17"
      + removeDefaultNodePool: false
```

**Comment by leezen** [comment]
As an update, still looking into this.

Some notes -- I was able to reproduce this by:

1. Creating a GKE cluster in GCP with all default settings.
1. Importing that cluster via:
```
let importedCluster = new gcp.container.Cluster("import", {
    name: "cluster-for-import"
}. { import: "us-central1/cluster-for-import" });

let importPool = new gcp.container.NodePool("default", {
    name: "default-pool",
    cluster: importedCluster.name,
    location: "us-central1"
}, { import: "us-central1/cluster-for-import/default-pool" });
```
1. I'm not able to reproduce removing just the imports and having `pulumi up` fail. 
1. However, changing the cluster, e.g. adding `nodeVersion` arg to the cluster config in the above program and attempt `pulumi up` will fail as described.

**Comment by leezen** [comment]
It turns out that on import, we import both `clusterIpv4Cidr` and `ipAllocationPolicy` but the provider only expects one of these properties. There's a bug where the underlying diff doesn't show the fact that  `ipAllocationPolicy` is going to be changed (due to the conflict), which results in the desire to replace the resource. We're still digging into the bug, but as an immediate workaround, you can do the following:

1. Export the statefile: `pulumi stack export > stack.json`
1. Edit `stack.json` to remove the `ipAllocationPolicy` block from the statefile.
1. Import the modified statefil: `pulumi stack import < stack.json`
1. Run `pulumi up` to effect your changes.

I was able to get the above to work after having a broken stack in the way you described above. Hopefully this works for you as well.

**Comment by leezen** [comment]
@logicbomb421 Please re-open if the above workaround doesn't help. I have separate tracking issues for the actual bug encountered.
