### ISSUE TITLE
Request of adding TencentCloud to cloud providers list

### ISSUE THREAD

**Issue by likexian** [pulumi/pulumi#4000]
Hello, would Pulumi add TencentCloud to the cloud providers list?

TencentCloud website: https://intl.cloud.tencent.com/
Terraform plugin: https://github.com/terraform-providers/terraform-provider-tencentcloud

Any other informations I am glad to make addition.

**Comment by likexian** [comment]
Hello @leezen 
Is that any thing I can do to help this process?

**Comment by leezen** [comment]
If you'd like to try creating a provider, you can take a look at https://github.com/pulumi/pulumi-tf-provider-boilerplate

**Comment by likexian** [comment]
> If you'd like to try creating a provider, you can take a look at https://github.com/pulumi/pulumi-tf-provider-boilerplate

Thanks.
After creating the new provider, could it be add to the offical provider list?

**Comment by Kagashino** [comment]
> If you'd like to try creating a provider, you can take a look at https://github.com/pulumi/pulumi-tf-provider-boilerplate

Hi, I'm the contributor of Terraform TencentCloud Provider.  
We have noticed this issue. As the current tencentcloud stack team, we are intent to support Pulumi TencentCloud Provider, and we're trying to build the example provider by using specific sdkv2 version here https://github.com/tencentcloudstack/pulumi-tencentcloud. 
What we're wondering is whether the pulumi official was intent to add TencentCloud to Package list, or the progress is blocked for the reason of Terraform TencentCloud Provider? If not, is the sdks published by the official or ourselves (as the third party)?
If there is anything we can do please let us know. Thank you.

**Comment by jaxxstorm** [comment]
@Kagashino there aren't any plans to add an official provider. You can bridge the provider yourself and add it to the registry. Happy to help with this.

**Comment by Kagashino** [comment]
> @Kagashino there aren't any plans to add an official provider. You can bridge the provider yourself and add it to the registry. Happy to help with this.

Thanks for your reply, we will take our own step to handle it.
