### ISSUE TITLE
Pulumi hangs when given bogus --cwd argument

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#4002]
Passing the `--cwd` argument to a relative folder that does not exist appears to just hang. (At least on v1.11.1 on macOS.)

```
$ pulumi --cwd ./totally-bogus stack ls
```

**Comment by nesl247** [comment]
Looking into this a bit, it's got to do with Pulumi's custom `PersistentPreRun`. Any error from there does not seem to be raised and it hangs.
