### ISSUE TITLE
Creating an Azure C# project with the name "Pulumi" causes a Cycle Error

### ISSUE THREAD

**Issue by andreasnauta** [pulumi/pulumi#4013]
Steps to reproduce: 

1. Type `pulumi new`
2. Select `azure-csharp`
3. Type `Pulumi` as the project name.
4. Select default values.

Then you get  "error NU1108: Cycle detected."

![Pulumi](https://user-images.githubusercontent.com/8932820/75776292-02924d80-5d54-11ea-927c-8773e21fe99c.jpg)

**Comment by mikhailshilkov** [comment]
Thanks for reporting this. We should probably prevent people from using project names `Pulumi` and `Pulumi.<Something>`.
