### ISSUE TITLE
Investigate import bug where conflicting attributes are imported

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#4019]
It turns out that on import, we import both `clusterIpv4Cidr` and `ipAllocationPolicy` but the provider only expects one of these properties. There's a bug where the underlying diff doesn't show the fact that  `ipAllocationPolicy` is going to be changed (due to the conflict), which results in the desire to replace the resource. We're still digging into the bug, but as an immediate workaround, you can do the following:

1. Export the statefile: `pulumi stack export > stack.json`
1. Edit `stack.json` to remove the `ipAllocationPolicy` block from the statefile.
1. Import the modified statefil: `pulumi stack import < stack.json`
1. Run `pulumi up` to effect your changes.

I was able to get the above to work after having a broken stack in the way you described above. Hopefully this works for you as well.

_Originally posted by @leezen in https://github.com/pulumi/pulumi/issues/3998#issuecomment-594973056_

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in #8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
