### ISSUE TITLE
Users report seeing odd error messages about "Method handler getSchema for /pulumirpc.ResourceProvider/GetSchema expected but not provided"

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#4028]
Example: https://travis-ci.com/pulumi/examples/jobs/294066108#L3613

**Comment by justinvp** [comment]
Pretty sure this happens when the method is missing from dynamic providers.

**Comment by phewitt** [comment]
also seeing this message. ```pulumi:pulumi:Stack (infrastructure-stage):
    Method handler getSchema for /pulumirpc.ResourceProvider/GetSchema expected but not provided
 
    Method handler getSchema for /pulumirpc.ResourceProvider/GetSchema expected but not provided
 
    error: update failed
 
Resources:
    399 unchanged
```
the error is from something else. but the message is new for me.

**Comment by baoduy** [comment]
I'm also receiving this message today `Method handler getSchema for /pulumirpc.ResourceProvider/GetSchema expected but not provided`
