### ISSUE TITLE
skip signed url creation

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi#4029]
This request may be somewhat specific to using GCS as state backend.

Currently when running any pulumi command locally with normal user / gcloud credentials, every operation starts and ends with this message:
```
warning: Pulumi will not be able to print a statefile permalink using these credentials. Neither a GoogleAccessID or PrivateKey are available. Try using a GCP Service Account.
```

This is an inherent limitation in GCS due to GCP only being able to create signed urls using a service account, but not using personal credentials.
However using a service account locally would violate a bunch of best practices / security practices and also would is rather inconvenient setup for a team.
In other words while this warning is informative, there's imo no reasonable way to fix this from a users perspective / it's not very actionable.

On the other hand to get this warning over and over again is annoying and noisy.
Most of my team members actually first think this is an error.

**Therefore i'd like to request the option to skip signed url creation altogether or be able to suppress this warning**.

This could be for example an argument like `pulumi up --skip-signed-url` or environment variable like `PULUMI_BACKEND_DISABLE_SIGNED_URL=1`.
Another, perhaps preferable alternative variant would be to introduce an option to specify the link type / format. In case of GCS I could imagine these 2 variants:
1. `signedURL` (the default)
2. `objectURI` , e.g.: `gs://my-state-bucket/.pulumi/stacks/prod.json`
3. `off`

A user than may invoke the CLI with `pulumi up --state-link-format objectURI` and would get `gs://my-state-bucket/.pulumi/stacks/prod.json` instead.

Hope this could be considered as it would solve some of the UX issues when using blob storage as backend. Thanks!

**Comment by HagaiBarel** [comment]
I second this. Being hitting this recently and it's really annoying / confusing

**Comment by stack72** [comment]
Hi @geekflyer / @HagaiBarel 

I am sorry for the lack of response on this - a while back there was a new cmd flag added

```
pulumi up --suppress-permalink
```

This will suppress the output that is causing the issue here. This is supported on up / refresh / destroy / preview and import

I hope this helps

Paul

**Comment by HagaiBarel** [comment]
Hi Paul,

Thanks for the reply. Yes, using `--suppress-permalink` does suppresses the output of the permalink which resolves one of errors, however the above warning also happens at the start of the operation not only at the end. It's also printed with other actions, e.g. `pulumi whoami`, `pulumi stack ls` etc.

**Comment by stack72** [comment]
Hey @geekflyer / @HagaiBarel 

So I wanted to update you both on what we decided here. Yesterday, we made the decision to suppress permalinks (and therefore the warning above) when any non-SaaS backend is being used. There is going to be a way to opt-in for permalinks but a permalink for a non-SaaS backend is actually the same as running `pulumi stack export`. I am not 100% sure who will miss this feature but the fact that you get that warning above on all Pulumi commands isn't a great experience

I am going to be starting to work on this today so it will ship soon! I apologise for the delay here

Paul

**Comment by HagaiBarel** [comment]
Thanks @stack72 for the update, looking forward to it

**Comment by stack72** [comment]
Just going to drop this here to show the progress. As you can see, we no longer show Permalinks by default when we are in a non-SaaS backend but we can opt-in if they require it

[![asciicast](https://asciinema.org/a/bOK710jYHrZHuFIltwluZeeEV.svg)](https://asciinema.org/a/bOK710jYHrZHuFIltwluZeeEV)

**Comment by infin8x** [comment]
@stack72 looks like you fixed this? Can I close the issue?

**Comment by stack72** [comment]
@infin8x waiting on a final review of the PR so I can close it out :/ sorry!
