### ISSUE TITLE
RunAsync should have a Task<void> overload

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#4036]
If I have a `RunAsync` lambda whose body doesn't return a dictionary, but does need to do asynchronous work and as such needs to be `RunAsync(async () => ...)`, this seems to bind to the ultra-generic `RunAsync(Action)` overload. This means the returned `Task` is simply ignored ([per this line here](https://github.com/pulumi/pulumi/blob/81b6afa3c7af28b6398f3d17228d38ce181fe898/sdk/dotnet/Pulumi/Deployment/Deployment_Run.cs#L18)). This is a major footgun: we won't actually wait for the tasks generated by that lambda to quiesce. This seems common enough to warrant a more specific overload, `RunAsync(Task<void>)`, which does await the task.

At least I _think_ that's what's happening in this example, which exits at the first `await`, before getting around to creating that `Ec2.Instance` resource:

```
using System.Collections.Generic;
using System.Threading.Tasks;

using Pulumi;
using CloudFormation = Pulumi.Aws.CloudFormation;
using Ec2 = Pulumi.Aws.Ec2;

class Program
{
    static Task<int> Main()
    {
        return Deployment.RunAsync(async () =>
        {
            var network = await CloudFormation.Invokes.GetStack(new CloudFormation.GetStackArgs
            {
                Name = "my-network-stack",
            });

            var subnetId = network.Outputs["SubnetId"];

            var web = new Ec2.Instance("web", new Ec2.InstanceArgs
            {
                Ami = "ami-0adc0e3ef2558cb1f",
                InstanceType = "t3.micro",
                SubnetId = (string)subnetId,
            });
        });
    }
}
```

**Comment by mikhailshilkov** [comment]
Our current guidance if to use `Deployment.RunAsync<MyStack>()` API where `MyStack` is a class derived from `Stack` (similar to `ComponentResource`). I'll change all templates and examples to that (hopefully, next week).

**Comment by joeduffy** [comment]
IMHO still seems like, if we're going to keep the alternative APIs around, we should have this overload to prevent people from making this mistake in the future.

Are we keeping both, or deprecating the old style in favor of the stack-oriented APIs?

**Comment by mikhailshilkov** [comment]
I'm reluctant to deprecate the old style in such short notice: we haven't even converted the templates and examples to the new style yet (in progress right now).
I'll take this change to M33.
