### ISSUE TITLE
Impossible to use pulumi inside others existings programs

### ISSUE THREAD

**Issue by mtparet** [pulumi/pulumi#4037]
Hello,

I'm trying to build a Kubernetes controller to manage aws (and others) resources using python with https://github.com/zalando-incubator/kopf but I cannot succeed to run Pulumi sdk inside it because it requires to be run with the Pulumi cli.

I think it will be a real game changer to be able to use Pulumi sdk where we want instead of just using the pulumi cli which really limits the usage of pulumi features.

Do you know if there are any workarounds (I tried test mode, but it does not make real calls) or if this is planned or in experimental state somewhere ? 

For now I have to look to alternatives like https://github.com/rancher/terraform-controller but it too sad because being able to combine kopf and pulumi could be really much better.

**Comment by mikhailshilkov** [comment]
This is tracked #3901

**Comment by mtparet** [comment]
Thanks @mikhailshilkov, I will follow this issue.

**Comment by mtparet** [comment]
And if I can help (or test alpha versions), let me know.

**Comment by EvanBoyle** [comment]
Closing in favor of https://github.com/pulumi/pulumi/issues/3901

Please add any additional detail about your requirements there.
