### ISSUE TITLE
Add linter/linting-infrastructure to help prevent pitfalls when writing an pulumi-app

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#404]
Right now coding against pulumi and pulumi-cloud is effectively coding against a slightly different dialect of JS/TS.  For example, due to how our deployment model works, capturing of top level state in functions has very different semantics vs how local execution would normally work.    Because of this, it can be very easy for a developer to get tripped up and to code up something that would work locally, but will not work in the pulumi cloud.   Indeed, during https://github.com/pulumi/pulumi-cloud/pull/79 I made several 'noob' mistakes that I didn't know were a problem.

To address this, I propose investing in tslint plugins that can look for common mistakes and guide the user on how they can do things properly.  Our documentation can then recommend usage of that linter when doing local (and even deploy/push) development.  This system can then be a generalized place where we can add more functionality/hints/warnings/errors as we move forward and discover other issues users may need to be concerned with.

**Comment by lukehoban** [comment]
This hasn't been an area we've seen a lot of feedback/need in the last 2 years, so closing out for now.  Can reopen based on user feedback/needs as appropriate.

**Comment by orcutt989** [comment]
+1

**Comment by thalesog** [comment]
+1
