### ISSUE TITLE
Pulumi has problems with umlauts in build logs

### ISSUE THREAD

**Issue by peterwurzinger** [pulumi/pulumi#4044]
Running the Pulumi 1.12.0 CLI on Windows 10 with dotnet-sdk and Azure plugin.
That said, executing `pulumi up` in a directory containing the provisioning application brought up an error:
``` cmd
error: failed to discover plugin requirements: Problem executing 'dotnet build -nologo .': rpc error: code = Internal desc = grpc: error while marshaling: proto: field "pulumirpc.LogRequest.Message" contains invalid UTF-8
```

The CLI terminates at a build step of the provisioning application printing out the following log message:
`Wiederherstellung in "25,28 ms" f�r "<path>\azure-deploy.csproj" abgeschlossen.`

This conforms to the german log output of `dotnet restore` (which is a subtask of `dotnet build`). The wrong encoded character is the character "ü". When running a build manually (in the same shell session) by executing `dotnet restore` the character gets displayed correctly.

So luckily there is a workaround by switching the codepage to UTF-8 (`chcp 65001`). Executing `pulumi up` after that seems to do the trick.

**Comment by peterwurzinger** [comment]
Just being curious if this issue is being accepted or not, since it was added, and then removed from a milestone @leezen

**Comment by leezen** [comment]
@peterwurzinger It's something we're digging into. We don't use the milestones to indicate if something is 'accepted' -- just as an internal tracking mechanism. In this case, I used it to make sure it showed up in our triage discussion.

**Comment by leezen** [comment]
Related: https://github.com/pulumi/pulumi/issues/4342
