### ISSUE TITLE
Create GitHub releases in addition to the release tags, so users who are watching releases are notified

### ISSUE THREAD

**Issue by sudoforge** [pulumi/pulumi#4050]
I maintain system packages for `pulumi` (and more) for Arch Linux users, and typically rely on email notifications to know that any given package has a new release. It would be great if Pulumi created GitHub releases (or had an email list that was notified on releases) so that users like myself can be notified of upstream releases.

**Comment by lukehoban** [comment]
See also https://github.com/pulumi/pulumi/issues/3167.

Although we don't publish full releases with binaries, we do have Releases listed at https://github.com/pulumi/pulumi/releases, and they are available in RSS via https://github.com/pulumi/pulumi/releases.atom.

**Comment by sudoforge** [comment]
I'll close this and continue the discussion in #3167.
