### ISSUE TITLE
Can't log-out of a local state folder if it's been deleted

### ISSUE THREAD

**Issue by oliverholliday** [pulumi/pulumi#4054]
If you do `pulumi login file://my_folder` and then delete that folder, it's impossible to use any of the CLI commands to clear it. 

```
c:\> pulumi logout
error: unable to open bucket file://deleted_folder
```

I had to manually edit `%USERPROFILE%/.pulumi/credentials.json` to clear the `"current": "file://deleted_folder"` setting to get anywhere.

Thanks

**Comment by stack72** [comment]
Closed via manual merge of #4218
