### ISSUE TITLE
Values for "files" or "include" in tsconfig appear to be ignored

### ISSUE THREAD

**Issue by austinbutler** [pulumi/pulumi#4062]
The documentation on [disabling built-in TS support](https://www.pulumi.com/docs/intro/languages/javascript/#disabling-built-in-typescript-support) seems to indicate that only `target`, `module`, `moduleResolution`, and `sourceMap` are hardcoded and cannot be overridden when using the built-in TS support, but it seems that in addition changes to `files`, `include`, and `exclude` have no effect.

The default `tsconfig.json` when using the TS template with `pulumi new` has `"files": ["index.js"]`. If I remove that, change it to a file that doesn't exist, or replace it with `includes`, it seems to have zero effects on running `pulumi preview`. If I rename my `index.ts` to `whatever.ts` I get `We failed to locate the entry point for your program`, even if I update the tsconfig to `"files": ["whatever.ts"]`.

So I think either the documentation is incomplete, or there's a bug with the `pulumi` cli. It would be nice to be able to make changes to `files`, `includes`, etc. and still have the built-in TS support enabled.

**Comment by leezen** [comment]
You should be able to change `files` to 'whatever.js' but you'll also need to change the main entry point to `whatever.ts` in your `package.json` -- this is hinted at within the `TypeScript` section in https://www.pulumi.com/docs/intro/languages/javascript/#getting-started so we can definitely improve the documentation here.

For reference: https://github.com/pulumi/pulumi/blob/0f4e5a6a0b3bb065c7ce0ee520ea40e6c4d18cff/sdk/nodejs/cmd/pulumi-language-nodejs/main.go#L562-L568

**Comment by pjoe** [comment]
Pulling my hair over this :S

Trying to add a type definition file for an untyped npm module using:

```
    "include": [
        "extra-typings/*.d.ts"
    ]
```

This works when I do a normal `tsc`, but fails with pulumi because `include` is not picked up somehow.

**Comment by leezen** [comment]
We use `ts-node` and... https://www.npmjs.com/package/ts-node#help-my-types-are-missing

**Comment by pjoe** [comment]
@leezen Thank you, that works.

I did end up submitting a PR with the type definitions to the upstream project [dns-zonefile](https://github.com/elgs/dns-zonefile/pull/37), so hoping the will be included soon.
