### ISSUE TITLE
Decide if we want to loosen the major version side-by-side restriction for pulumi SDK

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#4079]

**Comment by lukehoban** [comment]
We added a block in the code to prevent mixing `@pulumi/pulumi` SDKs across major versions in case we wanted to make breaking changes to the SDK API surface area that would lead to these being incompatible (and to provide a useful error even in older CLIs).

However, we have in practice not made any API-level breaking changes, and we do expect programs that use libraries targeting both `1.x` and `2.x` to be fine.

As a result, I believe we should loosen these checks to not trigger until `3.x`, again giving ourselves the change to decide on larger breaking changes in the next major release if desired.

Thoughts @pgavlin @leezen @stack72 ?

**Comment by leezen** [comment]
@lukehoban That seems reasonable to me.
