### ISSUE TITLE
Plugin Local Install CLI that isn't a Tarball

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi#4084]
Right now the plugin install command allows for a tarball. When developing a provider/plugin it creates the binary but does not compress it. It would be useful to have the install command allow to install a plugin binary itself to make installing and testing local plugins easier.

**Comment by stack72** [comment]
Hi @mitchellmaler 

My apologies for the time taken to get back to you here. Currently, Pulumi will load providers from PATH as well. This is my local development workflow.

Do you think this will allow your testing purpose here?

Paul

**Comment by stack72** [comment]
I am going to go ahead and close this out - if you think that we need make changes here then please do let me know

Paul
