### ISSUE TITLE
Resource docs generator must use camelCase name for nested properties in Python

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi#4095]
See this [comment](https://github.com/pulumi/docs/pull/2641#discussion_r393293399) for more info.

**Comment by justinvp** [comment]
I was looking at the schema generator, see:

https://github.com/pulumi/pulumi-terraform-bridge/blob/4364f9abde790234690ae593344c192ee0a62570/pkg/tfgen/generate_schema.go#L140-L144

and

https://github.com/pulumi/pulumi-terraform-bridge/blob/4364f9abde790234690ae593344c192ee0a62570/pkg/tfgen/generate_schema.go#L324-L331

So I think in the doc generator, you can look at `language` for the property and look for `mapCase` for `python`. And also for `csharp` look for a csharp-specific `name`.

**Comment by praneetloke** [comment]
@justinvp I believe you are correct, in that if we just check for `MapCase` and use the PascalCase for nested types when it is true for Python, we should be good. [Here's](https://github.com/pulumi/pulumi/blob/cfcfad2f3c8c4bb7f34130f68e2c842dda3dc7e6/pkg/codegen/python/gen.go#L831) where the Python SDK code generator currently builds a map of such properties that need to use PascalCase rather than snake_case.

**Comment by praneetloke** [comment]
So it turned out that it wasn't just a matter of checking for the `MapCase` property in the `propertyInfo` of a `schema.Property`. In fact, in the schema JSON `mapCase` is always false. If were to rely on this property, we would actually always generate property names in a single case.

Instead, the Python code generator actually builds a map of the casings and checks if a certain nested property needs to use a snake_case or a camelCase. These case maps also seem to be package-wide rather than module-specific. In clarifying this with Pat, it seems this is the way to fix this. This also correctly matches the casing used in the generated Python SDK code.
