### ISSUE TITLE
Ever-changing `pulumiManifest.go`

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#4118]
When used in a provider, the latest master generates `pulumiManifest.go` files. The files have a version in them, so the files change on every generation and cause build failures.

**Comment by lukehoban** [comment]
We have decided to just have individual providers add all `pulumiManifest.go` files to their `.gitignore`.  This will be part of the process of adopting the latest Go code-generator, and so we can close this issue out.
