### ISSUE TITLE
Require explicit opt-in to use pre-built binaries for Go language host

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#4123]
We added support for automatically `go run`ing Pulumi Go programs recently. For backward compatibility though, we treated the presence of a binary in the local folder or on the PATH as being preferred.

This means that if you ever (accidentally) build your project, then you no longer pick up any changes you make unless you explicitly build.

This is unintuitive and has caught several users off guard over the last couple weeks.  

We should instead default to `go run` always, and require a `Pulumi.yaml` configuration setting to explicitly opt-in to using a binary instead.

**Comment by stack72** [comment]
@lukehoban I have a small question about this work. The work for this to do this needs to happen in `sdk/go/pulumi-language-go/main.go`. I *think* the main job here is to somehow be able to pass a configuration value from the Pulumi.yaml file to that language host - this will need to be via `GetRequiredPluginsRequest` Proto - is this your understanding?
