### ISSUE TITLE
Python schema code-gen incorrectly projecting `oneOf` (unions)

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#4125]
On `aws.elasticbeanstalk.Application` we have:

```
                "application": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "string",
                            "$ref": "#/types/aws:elasticbeanstalk/application:Application"
                        }
                    ],
                    "description": "Name of the Beanstalk Application the version is associated with.\n"
                },
```

This is leading to this in Python:

```
:param pulumi.Input[dict] application: Name of the Beanstalk Application the version is associated with.
```

However, this is not a `dict`, it should be a `Union[str, dict]`.

**Comment by clstokes** [comment]
This is more widespread than just this one property. The `bucket` property on `aws.elasticbeanstalk.Application` also has the issue - https://www.pulumi.com/docs/reference/pkg/aws/elasticbeanstalk/applicationversion/#create-a-applicationversion-resource.

**Comment by justinvp** [comment]
[Currently](https://github.com/pulumi/pulumi-aws/blob/c100b256bc60df799f2bcc6e81dce0db8aadc98b/sdk/python/pulumi_aws/elasticbeanstalk/application_version.py#L18-L19) these are typed as `str`:

```python
                 application: Optional[pulumi.Input[str]] = None,
                 bucket: Optional[pulumi.Input[str]] = None,
```

**Comment by mikhailshilkov** [comment]
Interestingly, this does seem to work in azure-native, where for the definition

```
"kind": {
    "oneOf": [
        {
            "type": "string"
        },
        {
            "$ref": "#/types/azure-native:storage:Kind"
        }
    ],
    "description": "Required. Indicates the type of storage account."
},
```

Python codegen [generates](https://github.com/pulumi/pulumi-azure-native/blob/eac64ded91075c91eb7708d39b34e69d4bac77ef/sdk/python/pulumi_azure_native/storage/storage_account.py#L19):

```
kind: pulumi.Input[Union[str, 'Kind']],
```

Not sure if that's that extra `"type": "string",` that confuses the AWS provider?

```
"application": {
    "type": "string",
    "oneOf": [
        {
            "type": "string"
        },
        {
            "type": "string",
            "$ref": "#/types/aws:elasticbeanstalk/application:Application"
        }
    ],
    "description": "Name of the Beanstalk Application the version is associated with.\n",
    "willReplaceOnChanges": true
},
```

**Comment by lukehoban** [comment]
This appears fixed for all examples I can find of this in the AWS SDK.
