### ISSUE TITLE
Rancher2 (.NET) Modify NodeTemplate Value shows will be deleted but is updated 

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi#4138]
I have a Rancher2 NodeTemplate that I am creating in .NET. I created it then made a modification to the NodeTemplateVsphereConfigArgs which results in the preview shows it will be delete. Once I allow it to continue after the prompt results in a update. This NodeTemplate is in a ComponentResource.

```
$ pulumi up
Previewing update (asc-dev-k8s-c02):
     Type                            Name                                             Plan
     pulumi:pulumi:Stack             k8s-asc-dev-k8s-c02
 -   └─ rancher2:index:NodeTemplate  masterNodePool:asc-dev-k8s-c02_master_node_pool  delete

Resources:
    - 1 to delete
    9 unchanged

Do you want to perform this update? yes
Updating (asc-dev-k8s-c02):
     Type                            Name                                             Status      Info
     pulumi:pulumi:Stack             k8s-asc-dev-k8s-c02
 ~   └─ rancher2:index:NodeTemplate  masterNodePool:asc-dev-k8s-c02_master_node_pool  updated     [diff: ~vsphereConfig]

Resources:
    ~ 1 updated
    9 unchanged

Duration: 12s
```

**Comment by mikhailshilkov** [comment]
@mitchellmaler sorry for the slow response, are you still hitting this? would it be possible to share some code?

**Comment by stack72** [comment]
Hi @mitchellmaler 

I believe this will be taken care of by https://github.com/pulumi/pulumi-rancher2/blob/master/CHANGELOG.md#250-2020-10-26 as we changed how previews work in this provider release

I am going to close this out and if this is not the case, then please let me know

Paul
