### ISSUE TITLE
Slow Go builds and (especially) `go run`s

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#4140]
With a 20 line Pulumi Go program using `pulumi-kubernetes`, I see builds when a single character has changed taking ~10s:

```
$ time go build
real    0m10.073s
user    0m11.840s
sys     0m2.656s
```

When users run `pulumi up`, we by default use `go run`, and we use it a total of 4 times (preview and update, and for each of those GetRequiredPlugins and Run).  These `go run` executions aren't cached (even when nothing has changed), so we pay the very significant build cost 4x as much as we would need to. 

To address the second issue, we might want to skip using `go run` and instead `go build` or `go install` automatically?  (There are definitely subtleties to this).

**Comment by EvanBoyle** [comment]
We have updated the plugin acquisition code so that it doesn't invoke the program. That should cut the time for a pulumi up in half.

**Comment by EvanBoyle** [comment]
Closing this out for now. The core issue remaining is the size of our Go SDKs. Not much we can do in the near terms to address this.

**Comment by alienvspredator** [comment]
Go build is still slow and takes up 12Gb of RAM
<img width="1680" alt="Снимок экрана 2020-09-14 в 09 14 42" src="https://user-images.githubusercontent.com/39991717/93055396-8918d780-f673-11ea-84ec-3ae1a78f4e88.png">
