### ISSUE TITLE
Programmatically set config values for stacks and stack references

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi#4142]
In the open office hours today, a user who's working through how to split up their stacks wanted the ability to programmatically set pulumi config for the stack itself, but primarily for other stacks also to propagate parameters from parent -> child stacks.

**Comment by mikhailshilkov** [comment]
Reading this now, I'm not quite sure what this issue tracks... You can set the stack configs with `pulumi config` (or automation API) and why would you need to set config for stack references? There's nothing such a config would affect?

Since this issue is 2 years old, I'll go ahead and close it - but please comment with clarification if this scenario is still needed. Thank you!

**Comment by danielbraun89** [comment]
I don't understand the decision to close this issue. setting config programmatically enables to to conditionally change the config based on your own program logic. It is nothing like using `pulumi config` cli command.

**Comment by Frassle** [comment]
> setting config programmatically enables to to conditionally change the config based on your own program logic

The whole point of config is that it's set before your program logic, if you have internal logic that changes you should just be using normal variables not re-changing config.

**Comment by danielbraun89** [comment]
> > setting config programmatically enables to to conditionally change the config based on your own program logic
> 
> The whole point of config is that it's set before your program logic, if you have internal logic that changes you should just be using normal variables not re-changing config.

While I agree with this statement, the problems start when you have a disagreement about what should be a configuration and what more appropriate as a variable. Currently this decision is being made once per introduction of a feature by someone in Pulumi and I personally see the benefit in letting the user to override this decision

**Comment by danielbraun89** [comment]
> > setting config programmatically enables to to conditionally change the config based on your own program logic
> 
> The whole point of config is that it's set before your program logic, if you have internal logic that changes you should just be using normal variables not re-changing config.

While I agree with your statement, the problems start when you have a disagreement about what should be a configuration and what more appropriate as a variable. Currently this decision is being made once per introduction of a feature by someone in Pulumi and I personally see the benefit in letting the user to override this decision

**Comment by Frassle** [comment]
> Currently this decision is being made once per introduction of a feature by someone in Pulumi and I personally see the benefit in letting the user to override this decision

Can you give an example of this? I can't think of anything that we say _has_ to be config and can't be set in the program except for default provider config, and we have a ticket open about that (https://github.com/pulumi/pulumi/issues/2059) but it's quite possible to workaround by using explicit providers in the mean time.

**Comment by danielbraun89** [comment]
> > Currently this decision is being made once per introduction of a feature by someone in Pulumi and I personally see the benefit in letting the user to override this decision
> 
> Can you give an example of this? I can't think of anything that we say _has_ to be config and can't be set in the program except for default provider config, and we have a ticket open about that (#2059) but it's quite possible to workaround by using explicit providers in the mean time.

I was indeed thinking about default provider disabling config.  I wanted to force disable default providers in order to prevent mistakes by other team members with unaligned config file

**Comment by Frassle** [comment]
> I wanted to force disable default providers (in code form) in order to prevent mistakes by other team members with unaligned config file

Yup we have https://github.com/pulumi/pulumi/issues/9864 tracking exactly that, probably end up being the same solution for that and #2059.

> btw the configuration documentation also a bit misleading

Ah yes that is a bit misleading, I'll get that fixed up.

**Comment by shadiramadan** [comment]
Hmm I ran into an annoying GCP resource that doesn't let me specify the project but it does pick up the project via the config.  Unfortunately I create the project in pulumi so that doesn't work!  Guess I'll use a local command for now.
