### ISSUE TITLE
Please don't overwrite your artifacts :)

### ISSUE THREAD

**Issue by sudoforge** [pulumi/pulumi#4146]
I maintain a package that downloads tarballs of releases from `https://get.pulumi.com`. I noticed a [checksum change][0] for the `1.3.0` archive within the past two days.

This is an anti-pattern within the packaging world; once you release a versioned artifact, you shouldn't really change it. One way to release an update would have been to repackage it as `1.3.0-1`.

[0]: https://github.com/sudoforge/pkgbuilds/commit/08f0ac72822301a168c00afb6bc15b9c904b7bcf

**Comment by stack72** [comment]
Hi @sudoforge 

We have put new safeguards in place for this - we are using goreleaser to manage our binaries

Sorry it took me a while to get back to closing this issue out

Paul
