### ISSUE TITLE
A way to manage errors in code

### ISSUE THREAD

**Issue by remorses** [pulumi/pulumi#4148]
Now when you execute `pulumi up` and there are errors deploying you get the errors messages printed on the screen.

It would be cool to handle errors in code similar to how you can handle resource outputs with `apply`.

**Comment by leezen** [comment]
Could you please describe this a bit more? Are you looking for something like this? https://www.pulumi.com/docs/intro/concepts/programming-model/#logging -- things logged via `pulumi.log` are included in the Pulumi web console.

**Comment by remorses** [comment]
I would like to manage errors in the code itself, like `apply` but for errors

Every resource could have an `onError` method and call this method when the resource cannot be created and pass the error as argument
The error would be simply the json object returned from the api used under the hood

```ts
const helloService = new gcp.SomeResource()
helloService.someProperty.apply(status => {
    // manage output
})
helloService.onError(error => {
    // manage error
})
```

Currently there is no way to manage errors in the code, you can only see the error messages in the logs
It would be super useful to manage errors in the code, especially in a remote environment: 
you could send a message to slack when you cannot create a resource, 
easier debugging of why a resource cannot be created (because you can see the error object itself),

**Comment by leezen** [comment]
Got it -- thanks for explaining the use case!
