### ISSUE TITLE
.NET API: is `Deployment` confusing enough to be renamed?

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#4154]
Our entry point in .NET programs currently looks like this ([link](https://github.com/pulumi/templates/blob/master/csharp/Program.cs#L6)):

```csharp
static Task<int> Main() => Deployment.RunAsync<MyStack>();
```

I think the name `Deployment.Run` may be unfortunate in two ways:

1. The program itself does not deploy anything. When people get started with Pulumi, they often misinterpret the meaning of a program as if it was self-contained and are surprised to learn that the CLI is the required counterpart. IMO, `Deployment.Run` adds to this confusion from the get-go.

2. It seems likely that we will pursue the implementation of Runtime API (#3901) in the foreseeable future. @joeduffy made a prototype of it where he used `stack.deploy` as the verb for a self-contained action in the node SDK. What are we going to call it in .NET if `Deployment.Run` is already taken?

While we are close to GA, we are still not there, so we still have a chance to deprecate `Deployment.RunAsync` and come up with the new blessed name. Unfortunately, .NET is currently the only SDK that has to have this name at all, so we don't have a name to borrow.

`Stack.BuildAsync`?

Ideas are welcome!

**Comment by lukehoban** [comment]
Honestly - I think we can keep this name.  

> The program itself does not deploy anything. 

That's not really true - the program *does* deploy things, but it does so by calling gRPC endpoints that are only correctly set up if you launch the program via the Pulumi CLI.  I think this point about who launches the process is mostly unrelated to what the API should be called inside the code.  

> @joeduffy made a prototype of it where he used stack.deploy as the verb for a self-contained action in the node SDK. What are we going to call it in .NET if Deployment.Run is already taken?

That was just a pretty early sketch, and I'm not sure we know enough yet about what that API is going to look like to try to redesign our core APIs.  But at the very least, I could imagine using our existing .NET `Stack` and giving it instance methods, or having other methods on the runtime API (equivalent of `pulumijs` in @joeduffy's example) have allow for this.

**Comment by joeduffy** [comment]
I do agree that it's worth thinking through the names we _would_ choose. My choice of `stack.deploy` certainly wasn't very thoughtful and I'll admit that as I was tinkering with the code, it felt wrong. Something more like `stack.declareResources` is probably more technically accurate, even if verbose.

**Comment by mikhailshilkov** [comment]
We are going forward with the current API, so I'll close this issue.
