### ISSUE TITLE
grpc: received message larger than max

### ISSUE THREAD

**Issue by nrf110** [pulumi/pulumi#4155]
I'm getting the following error when trying to pass the string contents of a large file (webpack bundles) into a resource input.: `Error: failed to register new resource static_css_2-dc0caae3-chunk-css-map [cloudflare:index/workersKv:WorkersKv]: 8 RESOURCE_EXHAUSTED: grpc: received message larger than max (4595819 vs. 4194304)`

This is the code I'm using to reproduce the issue:
```typescript
pulumi.output(args.contentDir).apply((contentDir) => {
            glob.sync(`${contentDir}/**`)
            .filter((file) => fs.statSync(file).isFile())
            .map((file) => {
                const key = path.relative(contentDir, file);
                const kvName = key
                    .toLowerCase()
                    .replace(/\//g, '_')
                    .replace(/\.|\s/g, '-');
                return new cf.WorkersKv(kvName, {
                    namespaceId: namespace.id,
                    key,
                    value: fs.readFileSync(file, { encoding: 'utf8' }),
                }, { parent: this });
            });
        });
```

**Comment by danielrbradley** [comment]
Had a similar issue when uploading blobs to azure using the `StringAsset` class, but not when using a `FileAsset`.

```
grpc: received message larger than max (6900224 vs. 4194304)
```

Also interesting was that the failure caused some state corruption where it then assumed it had created the blobs and then got stuck trying to delete them which resulted in "not found" errors.
