### ISSUE TITLE
Go mod ends up with "ambiguous import" for the pulumi sdk

### ISSUE THREAD

**Issue by krilor** [pulumi/pulumi#4166]
I'm trying to follow the guide outlined in https://www.pulumi.com/docs/intro/languages/go/ , but I end up with the following "ambiguous import" error when I try to build.

```
/go/pkg/mod/github.com/pulumi/pulumi-aws@v1.27.0/sdk/go/aws/s3/accessPoint.go:11:2: ambiguous import: found package github.com/pulumi/pulumi/sdk/go/pulumi in multiple modules:
	github.com/pulumi/pulumi v1.12.2-0.20200313044354-8111d33438b9 (/go/pkg/mod/github.com/pulumi/pulumi@v1.12.2-0.20200313044354-8111d33438b9/sdk/go/pulumi)
	github.com/pulumi/pulumi/sdk v0.0.0-20200324171821-8ce10e1dfe54 (/go/pkg/mod/github.com/pulumi/pulumi/sdk@v0.0.0-20200324171821-8ce10e1dfe54/go/pulumi)
```
I've isolated this behaviour in a golang 1.14 buster container.
`docker run -it golang:1.14.1-buster bash`

I then run these commands one after the other
```bash
curl -fsSL https://get.pulumi.com | sh
export PATH=$PATH:/root/.pulumi/bin

mkdir /myproject && cd /myproject
pulumi login --local
pulumi new aws-go

go mod init github.com/krilor/myproject
go build -o myproject
```

Full output:

```
$ docker run -it golang:1.14.1-buster bash
root@28263dd3f8d5:/go# curl -fsSL https://get.pulumi.com | sh
=== Installing Pulumi v1.13.0 ===
+ Downloading https://get.pulumi.com/releases/sdk/pulumi-v1.13.0-linux-x64.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 55.1M  100 55.1M    0     0  7130k      0  0:00:07  0:00:07 --:--:-- 9399k
+ Extracting to /root/.pulumi/bin

=== Pulumi is now installed! 🍹 ===
+ Please add /root/.pulumi/bin to your $PATH
+ Get started with Pulumi: https://www.pulumi.com/docs/quickstart
root@28263dd3f8d5:/go# export PATH=$PATH:/root/.pulumi/bin
root@28263dd3f8d5:/go# 
root@28263dd3f8d5:/go# mkdir /myproject && cd /myproject
root@28263dd3f8d5:/myproject# pulumi login --local
Logged into 28263dd3f8d5 as root (file://~)
root@28263dd3f8d5:/myproject# pulumi new aws-go
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name: (myproject) 
go build -o myproject' is not a valid project name. A project name may only contain alphanumeric, hyphens, underscores, and periods.
project name: (myproject) 
project description: (A minimal AWS Go Pulumi program) 
Created project 'myproject'

stack name: (dev) 
Enter your passphrase to protect config/secrets: 
Re-enter your passphrase to confirm: 
Created stack 'dev'

Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE to remember): 
aws:region: The AWS region to deploy into: (us-east-1) 
Saved config

Your new project is ready to go! 

To perform an initial deployment, run 'dep ensure', then, run 'pulumi up'

root@28263dd3f8d5:/myproject# ls -1
Gopkg.toml
Pulumi.dev.yaml
Pulumi.yaml
main.go
root@28263dd3f8d5:/myproject# go mod init github.com/krilor/myproject
go: creating new go.mod: module github.com/krilor/myproject
root@28263dd3f8d5:/myproject# go build -o myproject
go: finding module for package github.com/pulumi/pulumi/sdk/go/pulumi
go: finding module for package github.com/pulumi/pulumi-aws/sdk/go/aws/s3
go: downloading github.com/pulumi/pulumi-aws v1.27.0
go: downloading github.com/pulumi/pulumi v1.13.0
go: downloading github.com/pulumi/pulumi/sdk v0.0.0-20200324171821-8ce10e1dfe54
go: found github.com/pulumi/pulumi-aws/sdk/go/aws/s3 in github.com/pulumi/pulumi-aws v1.27.0
go: found github.com/pulumi/pulumi/sdk/go/pulumi in github.com/pulumi/pulumi/sdk v0.0.0-20200324171821-8ce10e1dfe54
go: downloading github.com/pulumi/pulumi v1.12.2-0.20200313044354-8111d33438b9
go: downloading github.com/pkg/errors v0.9.1
/go/pkg/mod/github.com/pulumi/pulumi-aws@v1.27.0/sdk/go/aws/s3/accessPoint.go:11:2: ambiguous import: found package github.com/pulumi/pulumi/sdk/go/pulumi in multiple modules:
	github.com/pulumi/pulumi v1.12.2-0.20200313044354-8111d33438b9 (/go/pkg/mod/github.com/pulumi/pulumi@v1.12.2-0.20200313044354-8111d33438b9/sdk/go/pulumi)
	github.com/pulumi/pulumi/sdk v0.0.0-20200324171821-8ce10e1dfe54 (/go/pkg/mod/github.com/pulumi/pulumi/sdk@v0.0.0-20200324171821-8ce10e1dfe54/go/pulumi)
root@28263dd3f8d5:/myproject#
```
I've been able to figure out a "workaround" by getting a specific pulumi version  
before the build. This was based on the answer on this prometheus issue: https://github.com/prometheus/prometheus/issues/5590

I used `go get github.com/pulumi/pulumi@v1.13.0`

I'm posting this here in case anyone faces the same issue and maybe it should make it ways to the docs.

**Comment by EvanBoyle** [comment]
Upgrading to go modules across all of our SDKs is an active work in progress. The work to upgrade pulumi/pulumi is done. But the changes for the aws provider and others are in flight. Until that point using dep as you see in examples is the safe way to go.

I expect go modules should be ready to consume in a week or two.

**Comment by krilor** [comment]
Thanks for the fast reply. I have it working (by getting specific version as mentioned), so I'm all good for now. I didn't have dep installed and the doc I linked actually mentioned mod, so thought it worthwhile to file an issue in case anyone else was facing the same.

I'll leave this open until the go mod upgrade is finalized and I'll circle back and retest then.

**Comment by EvanBoyle** [comment]
@krilor The work to update to go modules across our major cloud providers is complete. 

You can see the updated go examples for each cloud here: github.com/pulumi/pulumi/examples

You can also try out the updated templates:

```
$ pulumi new go
$ pulumi new aws-go
$pulumi new azure-go
$ pulumi new aws-go
```

We've also updated our getting started documentation: https://www.pulumi.com/docs/get-started/

Please feel free to reopen this issue if you have any trouble getting a project with go modules up and running.

**Comment by krilor** [comment]
Sweet! Looking good.

One minor thing I notice is that since you are shipping go.mod file with the examples, running `go mod init` actually fails with _"go mod init: go.mod already exists"_

This doc page should probably be updated as well: 
https://www.pulumi.com/docs/intro/languages/go/

Specifically this section:

> Use your favorite Go dependency manager (such as Go’s built-in modules system, by running go mod init in your project’s directory).

Another thing I saw was that `pulumi new go` reads _go 1.13_ in go.mod, even tho I'm running 1.14. I have no idea what the significance of that is, just noticed.

Thanks for the great work you are doing to bring Pulumi to Go.
