### ISSUE TITLE
Expose ephemeral logging in Python SDK

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#4169]
In the Node.js SDK, we expose the engine's ephemeral logging capabilities, as a simple boolean for the various logging API calls. In Python, we do not.

This capability can be useful, for instance, if your program does some lengthy operation (like building Docker images, provisioning VMs, etc) where you want to log some progress as you go, but don't want to clutter up the final diagnostics.

**Comment by lukehoban** [comment]
Related (but different): https://github.com/pulumi/pulumi/issues/4009
