### ISSUE TITLE
Repository name in pulumi portal contains / when repository cloned via https

### ISSUE THREAD

**Issue by ahanoff** [pulumi/pulumi#4170]
Repository displayed with / when git repo clone was done via https protocl, and without if done via ssh

<img width="163" alt="image" src="https://user-images.githubusercontent.com/2371703/77508656-2a358b00-6ea6-11ea-96ab-9f7ed7d56761.png">

**Comment by leezen** [comment]
I'm having trouble following as the screenshot you attached doesn't have a lot of context. Are you referring to the value of the stack tags shown in the Pulumi console for `vcs:repo`? Or is this happening somewhere else?

**Comment by ahanoff** [comment]
@leezen it happens in https://app.pulumi.com/ (Pulumi Console). Let me create test repo and provide better screenshot
