### ISSUE TITLE
How can I convert resources' properties array to output?

### ISSUE THREAD

**Issue by lonegunmanb** [pulumi/pulumi#4171]
Dear Pulumi:

I've tried new pulumi dotnet sdk, but I've got a problem: how can I convert a resource array's ids to an output array?
```csharp
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using Pulumi;
using Pulumi.AliCloud.Vpc;

class MyStack : Stack
{
    private readonly string[] az = new[]
    {
        "cn-shanghai-a",
        "cn-shanghai-b",
    };
    public MyStack()
    {
        var vpc = new Pulumi.AliCloud.Vpc.Network("tets_vpc", new NetworkArgs
        {
            Name = "test_vpc",
            CidrBlock = "10.0.0.0/16"
        });

        var subnets = az.Select(((az, index) => new Subnet($"switch{index}", new SubnetArgs
        {
            VpcId = vpc.Id,
            AvailabilityZone = az,
            CidrBlock = $"10.0.{index}.0/24",
            Name = $"switch{index}"
        }))).ToArray();

        var subnetIds = new List<string>();

        subnets.Select(s => s.Id.Apply(new Func<string, string>(delegate(string id)
        {
            subnetIds.Add(id);
            return id;
        }))).ToArray();


        SubnetIds = Output.Create(subnetIds.ToImmutableArray());
    }

    [Output]
    public Output<ImmutableArray<string>> SubnetIds { get; set; }
    
}
```

As you can see, I want export all subnet ids, but I don't know how to convert an Output<string>[] to an Output<ImmutableArray<string>>. It's very weird to use Apply and a delegate to collect string value inside Output<string>.

**Comment by mikhailshilkov** [comment]
Hi @lonegunmanb 

The key to this puzzle is the method called `Output.All`:

``` csharp
SubnetIds = Output.All(subnets.Select(s => (Input<string>)s.Id).ToImmutableArray());
```

I opened https://github.com/pulumi/pulumi/issues/4182 to avoid the ugly conversion in `Select`.

**Comment by lonegunmanb** [comment]
> Hi @lonegunmanb
> 
> The key to this puzzle is the method called `Output.All`:
> 
> ```cs
> SubnetIds = Output.All(subnets.Select(s => (Input<string>)s.Id).ToImmutableArray());
> ```
> 
> I opened #4182 to avoid the ugly conversion in `Select`.

Many thanks @mikhailshilkov ! I see pulumi's input and output design is based on reactive programming, GREAT JOB!

Yeah, maybe avoiding explicit conversion will improve programming experience dramaticlly, can't wait anymore 😄 

By the way, maybe I'll choose pulumi dotnet sdk in my test environment soon, because of unit test capability, MANY THANKS!
