### ISSUE TITLE
AWS resource already exits

### ISSUE THREAD

**Issue by rob3000** [pulumi/pulumi#4172]
Hi, 

So i have the following scenario and wanted some guidance on how best to handle it. For a stack we ran `pulumi destroy -s {stackName}` which deleted all the resources in AWS. One of the resources was a secretsManager which when deleted its only a soft delete and you have 30 days to reactivate that secret. When we try to run a `pulumi up -r` we get the error:
```
aws:secretsmanager:Secret (myAwesomeName):
    error: error creating Secrets Manager Secret: InvalidRequestException: You can't create this secret because a secret with this name is already scheduled for deletion.
```

So we login to AWS and reactivate the secret and re run `pulumi up -r` but we encounter the following:
```
aws:secretsmanager:Secret (myAwesomeName):
    error: error creating Secrets Manager Secret: ResourceExistsException: The operation failed because the secret myAwesomeName already exists.
```

Whats the best way to get around this error without having to rename the secretManager?

**Comment by leezen** [comment]
Are you able to use `import`? https://www.pulumi.com/docs/intro/concepts/programming-model/#import

From the stack's point of view, the secret is an existing resource and should now be adopted into the stack.
