### ISSUE TITLE
Secret Output Names of StackReferences are shown as different.

### ISSUE THREAD

**Issue by jeduden** [pulumi/pulumi#4176]
I have a Stack Reference 
```
const infraStack = new pulumi.StackReference(`infra-${env}`);
```

to a stack that exports secrets something like this:
```
exports.Secret1 = config.requireSecret('Secret1')
exports.Secret2 = config.requireSecret('Secret2')
exports.Secret3 = config.requireSecret('Secret3')
```

if i run `pulumi up` on the stack containing the reference i see often changes like this:
```
~ secretOutputNames: [
          ~ [0]: "Secret1" => "Secret2"
          ~ [1]: "Secret2" => "Secret1"
            [2]: "Secret3"
        ]
```

Eventhough the secret contents did not change. Also both stacks didn't change.
I can do a `pulumi refresh` multiple times and it keeps displaying this change in my project.

**Comment by leezen** [comment]
How are you constructing `secretOutputNames`? It doesn't look like anything is changing except for the order of those values in the array. I'm wondering if there's something non-deterministic in how that array is constructed?

**Comment by jeduden** [comment]
i am not constructing explicitly. pulumi is constructing this array somehow: see https://github.com/pulumi/pulumi/blob/35bc41c5d3a763c89451927358ded79a16718360/sdk/nodejs/stackReference.ts#L38

**Comment by leezen** [comment]
Thanks for that. I'll add this to the backlog to make this deterministic so that these spurious diffs don't show up.

**Comment by jaxxstorm** [comment]
Moving this out, got backlogged behind 2.0 work.
