### ISSUE TITLE
Resource docs generator bug with double-quotes in markdown

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi#4177]
Double-quotes in the markdown of a property comment should not be encoded. See https://github.com/pulumi/docs/pull/2641#issuecomment-600321461.

**Comment by praneetloke** [comment]
For an example pf the bug, see `volumeType` in https://www.pulumi.com/docs/reference/pkg/aws/ec2/instance/#instanceebsblockdevice.

**Comment by tasiah** [comment]
Fixed [accidentally](https://pulumi.slack.com/archives/CBUP505U7/p1585165244004600?thread_ts=1585165175.004500&cid=CBUP505U7) with [this commit](https://github.com/pulumi/pulumi/commit/bdefc557af755f90a700c295f6f5ccbba102ecd8).
