### ISSUE TITLE
Do not require PULUMI_TEST_MODE in node unit tests

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#4187]
Here is a command that works for me when I'm running mock-based unit tests in Node.js:

```bash
$ PULUMI_TEST_MODE=true  \
  PULUMI_NODEJS_STACK="my-ws" \
  PULUMI_NODEJS_PROJECT="dev" \
  mocha -r ts-node/register ec2tests.ts
```

Removing any env variable causes errors from the engine.

However, all other runtimes (python, go, .NET) run just fine without these variables.

We should automatically pick up the test mode when mocks are provided in Node.js code.

**Comment by lukehoban** [comment]
I just tried this - and cannot repro the issue.

I ran the following in https://github.com/pulumi/examples/blob/31056c3480cc445e5d4d3a8a0a86977adce2bc5e/testing-unit-ts/:

```
$ ./node_modules/.bin/mocha -r ts-node/register ec2tests.ts


  Infrastructure
    #server
      ✓ must have a name tag
      ✓ must not use userData (use an AMI instead)
    #group
      ✓ must not open port 22 (SSH) to the Internet


  3 passing (8ms)
```

**Comment by mikhailshilkov** [comment]
@lukehoban Cleaned everything up and tried again - and it works indeed. Closing and updating the example.
