### ISSUE TITLE
Update tagging and release process to support multi-module repos

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#4213]
For every release going forward, we need to publish a tag for each go.mod path. For pulumi/pulumi it would look like:

```
sdk/v1.13.1
pkg/v1.13.1
tests/v1.13.1
```

We should document this going forward and fix the most recent provider and pulumi/pulumi releases if possbile. 

Here's a ticket with more detail about consul's troubles with releasing a multi-module repo that may be of help: https://github.com/golang/go/issues/33033

**Comment by stack72** [comment]
So I’m not sure what this actually means in essence - how can I tag individual folders?

**Comment by EvanBoyle** [comment]
Does that work? `git tag -a sdk/v1.13.1`

**Comment by lukehoban** [comment]
This sounds like it could be nontrivially disruptive. We treat tags as true versions. We’ll need to be careful here. This is also generally “unfortunate”. Are there any alternatives?

**Comment by EvanBoyle** [comment]
The go modules documentation for repos with sub modules recommends prefixed tags like `sdk/v1.13.1`:

https://github.com/golang/go/wiki/Modules#publishing-a-release

**Comment by EvanBoyle** [comment]
Just tested this locally. It should work fine:

``` 
Evans-MBP:pulumi evanboyle$ git tag -a "sdk/1.13.1"
Evans-MBP:pulumi evanboyle$ git tag -a "sdk/1.13.2"
Evans-MBP:pulumi evanboyle$ git tag -l
sdk/1.13.1
sdk/1.13.2
v0.1
v0.10.0
v0.10.0-rc1
v0.10.0-rc2
v0.10.0-rc3
v0.10.0-rc4
v0.10.0-rc5
v0.10.0-rc6
v0.11.0
```

**Comment by EvanBoyle** [comment]
Important to note if you create a tag `t1` you cannot create another tag that has t1 as a prefix before a `/`.

for instance:

```
$ git tag -a "sdk" # this is fine
$ git tag -a "sdk/v1" # boom failure due to a directory already existing  at `.git/sdk`

**Comment by EvanBoyle** [comment]
@lukehoban no alternatives if you want to be able to properly `go get github.com/pulumi/pulumi/sdk@v1.x.x`

**Comment by EvanBoyle** [comment]
@stack72 @lukehoban Tomorrow morning I'd like to push the new tags to pulumi/pulumi on the same commit we tagged at v1.13.1 

Any objections?

**Comment by lukehoban** [comment]
This will make our release process fundamentally heavier (pushing three tags instead of one) in every single repo, and very easy to get wrong. 

How are we going to make this maintainable?  I wonder if we can have the release job triggered by the normal version tag actually push tags for the derived ones so that this is automatic?

Are we sure we won’t trigger additional releases with the new tags?  I think we currently trigger a release on any tag - may need to scope that to `v\d.*` or something?

**Comment by EvanBoyle** [comment]
Here's a PR that ignores releases for tags other than `^v\d`.

https://github.com/pulumi/pulumi/pull/4219

Let's do this release process manually once to work out the kinks and we can automate it afterward.

**Comment by EvanBoyle** [comment]
PR for pulumi-aws: 

https://github.com/pulumi/pulumi-aws/pull/914

**Comment by EvanBoyle** [comment]
I manually published tags for pulumi/pulumi `pkg/v1.13.1` `sdk/1.13.1`:

```sh
git checkout f43a9522cb824e6c11fe51b5da82a44b54b3acc4
git tag sdk/v1.13.1
git push origin sdk/v1.13.1

git checkout f43a9522cb824e6c11fe51b5da82a44b54b3acc4
git tag pkg/v1.13.1
git push origin pkg/v1.13.1
```

Also did the same for pulumi-aws `sdk/v1.28.0`:

```
git checkout b399e2d36394582be9403feb5c63b086c782432a
git tag sdk/v1.28.0
git push origin sdk/v1.28.0
```

**Comment by EvanBoyle** [comment]
Pushed a commit to update travis.yml for pulumi-azure into this PR:

https://github.com/pulumi/pulumi-azure/pull/500

**Comment by EvanBoyle** [comment]
GCP: https://github.com/pulumi/pulumi-gcp/pull/309

**Comment by EvanBoyle** [comment]
get-version scripts need to be updated too: https://github.com/pulumi/pulumi/issues/4227

**Comment by EvanBoyle** [comment]
@stack72 now that you've gone through the release process a few times, is this something that you think requires some additional tooling and automation, or are you happy with the current process?

**Comment by stack72** [comment]
I am going to close this out - we have successfully managed this for a lot of the providers and the core app. We can build tooling around this as we go when 2.0 is out the door
