### ISSUE TITLE
pulumi 1.13.1 mac osx build is broken

### ISSUE THREAD

**Issue by chenrui333** [pulumi/pulumi#4222]
relates to https://github.com/Homebrew/homebrew-core/pull/52237
mojave build log, https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/60008/version=mojave/console

**Comment by EvanBoyle** [comment]
Hi @chenrui333 I've updated the formula in this PR and it's now building cleanly: https://github.com/Homebrew/homebrew-core/pull/52308

**Comment by stack72** [comment]
Closed in homebrew and the build is passing

@chenrui333 please can you close Homebrew/homebrew-core#52237 when the new PR is closed :)
