### ISSUE TITLE
pulumi preview : in case of an error, it's not possible to read the full error ?

### ISSUE THREAD

**Issue by StefH** [pulumi/pulumi#4225]
In powershell:
![image](https://user-images.githubusercontent.com/249938/77852652-1197de80-71e0-11ea-86ca-2165bf865a7d.png)

**Comment by Rookian** [comment]
Seems related to https://github.com/pulumi/pulumi/issues/4188

**Comment by leezen** [comment]
If it's hanging like #4188, let's track this there as well. It'd be great if you have a program you're willing to share for repro.

**Comment by Rookian** [comment]
@leezen  I got this error (console is hanging) again, because I forget to disable resource providers.
