### ISSUE TITLE
get-version scripts now returning invalid versions with new tags

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#4227]
./scripts/get-version is now returning `sdk/v1.13.1` which fails semver.parseTolerant. These scripts need to be updated across all of our repos to ignore anything before the `/` in a tag.

**Comment by EvanBoyle** [comment]
https://travis-ci.com/github/pulumi/pulumi-aws/builds/156375379

**Comment by stack72** [comment]
This is going to become a P1 as we need to release a 2.0.0 beta tomorrow or Tuesday
