### ISSUE TITLE
Disable auto-naming globally

### ISSUE THREAD

**Issue by simhams** [pulumi/pulumi#4231]
Pulumi.Azure - 
We have very strict rules around naming conventions and cannot have auto-naming.
Is there anyway we can disable auto-naming globally, instead of doing it for each resource?

**Comment by mikhailshilkov** [comment]
Thanks @simhams 
Let's track this in #1518

**Comment by mikhailshilkov** [comment]
Thanks @simhams 
Let's track this in #1518
