### ISSUE TITLE
How do I retrieve project and stack meta information in C#?

### ISSUE THREAD

**Issue by Rookian** [pulumi/pulumi#4238]
I would like to get the stack name within my stack C# code.

How do I retrieve project and stack meta information in C#?

**Comment by justinvp** [comment]
Hi, @Rookian 👋 

> I would like to get the stack name within my stack C# code.

```csharp
Deployment.Instance.StackName
```

> How do I retrieve project and stack meta information in C#?

What meta information are you looking to retrieve?

**Comment by Rookian** [comment]
> Hi, @Rookian 👋
> 
> > I would like to get the stack name within my stack C# code.
> 
> ```cs
> Deployment.Instance.StackName
> ```
> 
> > How do I retrieve project and stack meta information in C#?
> 
> What meta information are you looking to retrieve?

Ok got it. Sry, but I could not find it in the documentation. I looked after `Deployment.Instance.StackName` just now and could find it
 under: https://www.pulumi.com/docs/intro/concepts/programming-model/

`Pulumi.Deployment.Instance.ProjectName` and `Pulumi.Deployment.Instance.StackName` is all what I need so far. 

Thank you!
