### ISSUE TITLE
Provide pulumi as a .NET Core tool

### ISSUE THREAD

**Issue by Rookian** [pulumi/pulumi#4239]
In the community it is a best practice to be able to use different versions in different repositories. Right now, I have to install chocolately and install pulumi globally on my machine.

Please adapt the new .NET Core tool ecosystem and provide a .NET Core tool nuget package for pulumi. 

https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool

**Comment by mikhailshilkov** [comment]
Thank you for your suggestion! I think we want to keep the tooling experience universal across all languages and runtimes that Pulumi supports and won't fragment the tool ecosystem. I'll close this isssue as won't do.
