### ISSUE TITLE
Freeze resource objects post-construction

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#424]
Resource objects aren't meant to be mutated post-construction.

If you do so, we don't guarantee that properties will see the newly updated values, and in fact due to asynchrony, it's unclear what the state would even be.  We mark properties `readonly` in most places to signify this, but that's purely a TypeScript thing and is optional.

We should consider freezing -- in the [`Object.freeze` sense](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) -- to enforce this dynamically.

**Comment by CyrusNajmabadi** [comment]
I'm closing out simply as this doesn't seem to actually be an issue that has ever been a problem.
