### ISSUE TITLE
Should Deployment.Instance return Deployment rather than IDeployment?

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#4241]
Currently, `Deployment.Instance` returns `IDeployment`:

https://github.com/pulumi/pulumi/blob/7efca23beb6557b9e7777fb9143df9cf41388c91/sdk/dotnet/Pulumi/Deployment/Deployment.cs#L42

https://github.com/pulumi/pulumi/blob/7efca23beb6557b9e7777fb9143df9cf41388c91/sdk/dotnet/Pulumi/Deployment/IDeployment.cs#L7-L42

What if we want to add more information in the future, such as the _qualified_ stack name that includes the org (https://github.com/pulumi/pulumi/issues/2800)?

Changing the interface would be a breaking change, so how and where would we expose it?

Should `Deployment.Instance` instead return `Deployment` so that we can add members in the future?

**Comment by mikhailshilkov** [comment]
@justinvp Yeah good point. We could provide a default implementation for new members, but that's a meh...

Cyrus was okay with the current setup, but I don't quite like `Deployment.Instance` at all. For Stack-based API we could simply put those properties on the base class, so people could do `this.StackName` instead of `Deployment.Instance.StackName`. The callback API would need to get an extra `context` parameter, I suppose. This is also a potential step to multi-threaded API (needed e.g. for tests). Thoughts?

**Comment by justinvp** [comment]
> I don't quite like `Deployment.Instance` at all.

I don't have a strong opinion. But if we do keep it, I think we should change it to not return the interface.

> For Stack-based API we could simply put those properties on the base class, so people could do `this.StackName` instead of `Deployment.Instance.StackName`.

Any concern about adding members to `Stack` that would potentially conflict with what a user would want to use to specify stack outputs?

> This is also a potential step to multi-threaded API (needed e.g. for tests).

Oh? What do you mean?

**Comment by mikhailshilkov** [comment]
> Any concern about adding members to Stack that would potentially conflict with what a user would want to use to specify stack outputs?

Users can specify an explicit name if needed:

```cs
[Output("StackName")]
public Output<string> MyStackName { get; set; }
```

> Oh? What do you mean?

One can't run multiple deployments at the same time. While it's not a problem for real deployments, it is a problem for mocked unit tests. They have to run sequentially right now (see [this code](https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi/Deployment/Deployment_Run.cs#L111)).
