### ISSUE TITLE
Permit dependsOn on Outputs (.NET)

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi#4254]
Currently you cannot provide a output resource for depends on.
https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi/Resources/ResourceOptions.cs#L27
This looks to be done for javascript https://github.com/pulumi/pulumi/pull/2198

**Comment by mikhailshilkov** [comment]
@mitchellmaler This is possible today:

```csharp
var rg = new ResourceGroup("rg");
var outputRg = Output.Create((Resource)rg);

var account = new Account("sa", new AccountArgs(), new CustomResourceOptions
{
    DependsOn = { outputRg }
});
```

It could be an `Input<Resource>` too. One caviat is that I had to cast to `Resource` so that the types would match. Is that maybe what got you blocked?

**Comment by mikhailshilkov** [comment]
@mitchellmaler I'm going to close this one, please report back if it still doesn't work for you
