### ISSUE TITLE
Updating Azure vnet with tag when subnet is used fails

### ISSUE THREAD

**Issue by davidobrien1985** [pulumi/pulumi#4260]
Creating a vnet with subnets as standalone resources causes an issue with subsequent updates to the vnet.

```python
from pulumi import ResourceOptions, Config, Output, get_stack
from pulumi_azure import core, network, storage, operationalinsights, monitoring
from pulumi.resource import CustomTimeouts

config = Config()
rg_name = config.require('rgname')
ssvc_vnet_space = config.require('ssvc-vnet')
stack_name = get_stack()
azure_subscription = core.get_subscription()

default_tags={
  "environment": stack_name
}

resource_group = core.ResourceGroup('rg', 
  name=rg_name + "-" + stack_name,
  tags=default_tags
)

# networking resources
vnet = network.VirtualNetwork('ssvc-vnet',
  resource_group_name=resource_group.name,
  name="ssvc-vnet-{0}".format(stack_name),
  address_spaces=[ssvc_vnet_space],
  tags=default_tags
)

subnet_config = [('AzureBastionSubnet', '10.1.1.0/27'), ('GatewaySubnet', '10.1.1.32/27'), ('AzureFirewallSubnet', '10.1.1.64/26')]

for subnet in subnet_config:
  subnet_resource = network.Subnet(subnet[0],
    resource_group_name=resource_group.name,
    name=subnet[0],
    address_prefix=subnet[1],
    virtual_network_name=vnet.name
  )

  if subnet[0] == "GatewaySubnet":
    vpn_gw_pip = network.PublicIp("vpn-gw-pip",
      name="vpn-gw-pip",
      resource_group_name=resource_group.name,
      allocation_method="Dynamic",
      tags=default_tags
    )

    vpn_gw = network.VirtualNetworkGateway("vpn-gw",
      name="vpn-gw",
      resource_group_name=resource_group.name,
      sku="VpnGw2",
      type="Vpn",
      vpn_type="RouteBased",
      ip_configurations=[{
          "name": "vpn-gw-ipconf",
          "subnet_id": subnet_resource.id,
          "publicIpAddressId": vpn_gw_pip.id
      }],
      tags=default_tags,
      opts=ResourceOptions(custom_timeouts=CustomTimeouts(create='45m', update='45m', delete='45m'))
    )
```

This creates successfully. 

Next step:
Add a new tag to `default_tags` and `pulumi up`. This will fail with 

```
~   └─ azure:network:VirtualNetwork  ssvc-vnet               **updating failed**     [diff: ~tags]; 1 error
Diagnostics:
  azure:network:VirtualNetwork (ssvc-vnet):
    error: 1 error occurred:
        * updating urn:pulumi:prod::azure-foundations::azure:network/virtualNetwork:VirtualNetwork::ssvc-vnet: Error Creating/Updating Virtual Network "ssvc-vnet-prod" (Resource Group "sharedservices-prod"): network.VirtualNetworksClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet GatewaySubnet is in use by /subscriptions/<subId>/resourceGroups/sharedservices-prod/providers/Microsoft.Network/virtualNetworkGateways/vpn-gw/ipConfigurations/vpn-gw-ipconf and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]
```

The `PUT` seems to be sending an empty list of subnets to the vnet resource.
Tested in terraform and there it works. Terraform correctly sees the subnet resources as children of the vnet.

```
pulumi==1.13.0
pulumi-azure==2.2.0
```

**Comment by davidobrien1985** [comment]
This is starting to get quite blocking as the nested subnet resource seems to be super limited now compared to the standalone resource which allows for private endpoints etc.

**Comment by jamesianberry** [comment]
I have reproduced this using code in https://github.com/pulumi/examples/pull/611/files
Changes:
 
    Type                         Name                          Operation
>   pulumi:pulumi:StackReference jamesianberry/azure-py-vdc/dr read
~   azure:core:ResourceGroup     prod-vdc-rg-                  updated
~   azure:network:PublicIp       hub-er-gw-pip-                updated
~   azure:network:PublicIp       hub-fw-pip-                   updated
~   azure:network:PublicIp       hub-vpn-gw-pip-               updated
 
Diagnostics:
 
jamesianberry/azure-py-vdc/prod (pulumi:pulumi:Stack)
error: update failed
 
hub-vn- (vdc:network:Hub$azure:network/virtualNetwork:VirtualNetwork)
error: 1 error occurred:
	* updating urn:pulumi:prod::azure-py-vdc::vdc:network:Hub$azure:network/virtualNetwork:VirtualNetwork::hub-vn-: Error Creating/Updating Virtual Network "hub-vn-b007c91b" (Resource Group "prod-vdc-rg-6ecb23ab"): network.VirtualNetworksClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet AzureFirewallSubnet is in use by /subscriptions/e2442e38-cf1a-47bb-9110-7e022052f875/resourceGroups/prod-vdc-rg-6ecb23ab/providers/Microsoft.Network/azureFirewalls/hub-fw-15cb83fd/azureFirewallIpConfigurations/hub-fw-ipconf and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]

 
Resources:
    ~ updated 4
    2 unchanged
 
Duration: 20s

**Comment by mikhailshilkov** [comment]
I was indeed able to reproduce this error:
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/1454008/79232683-1effca80-7e68-11ea-8073-e8f7337a4b9a.png">

A workaround is to run `pulumi refresh` after any subnet changes (and confirm with `yes`):
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/1454008/79232785-40f94d00-7e68-11ea-9ac4-edbfa73d2df5.png">

Refresh updates the `subnet` property of the VNet resource and it won't try to delete the VNets anymore.

Now `pulumi up` will succeed:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/1454008/79232872-5cfcee80-7e68-11ea-9f75-e2f753014d7b.png">

Terraform "works" because they do a refresh automatically. I am not yet sure how to fix this reliably, but I hope this unblocks everyone.

**Comment by jamesianberry** [comment]
I rebuilt my infrastructure, refreshed it and then added a tag - success (even gateways):
Updating (dr):
     Type                                       Name             Status      Info
     pulumi:pulumi:Stack                        azure-py-vdc-dr
 ~   ├─ azure:core:ResourceGroup                dr-vdc-rg-       updated     [diff: ~tags]
     ├─ vdc:network:Hub                         hub
 ~   │  ├─ azure:network:VirtualNetwork         hub-vn-          updated     [diff: ~tags]
 ~   │  ├─ azure:network:PublicIp               hub-vpn-gw-pip-  updated     [diff: ~tags]
 ~   │  ├─ azure:network:PublicIp               hub-er-gw-pip-   updated     [diff: ~tags]
 ~   │  ├─ azure:network:PublicIp               hub-fw-pip-      updated     [diff: ~tags]
 ~   │  ├─ azure:network:VirtualNetworkGateway  hub-vpn-gw-      updated     [diff: ~tags]
 ~   │  ├─ azure:network:VirtualNetworkGateway  hub-er-gw-       updated     [diff: ~tags]
 ~   │  ├─ azure:network:Firewall               hub-fw-          updated     [diff: ~tags]
 ~   │  ├─ azure:network:RouteTable             hub-gw-rt-       updated     [diff: ~tags]
 ~   │  ├─ azure:network:RouteTable             hub-dmz-rt-      updated     [diff: ~tags]
 ~   │  └─ azure:network:RouteTable             hub-sn-rt-       updated     [diff: ~tags]
     └─ vdc:network:Spoke                       spoke
 ~      ├─ azure:network:VirtualNetwork         spoke-vn-        updated     [diff: ~tags]
 ~      └─ azure:network:RouteTable             spoke-sn-rt-     updated     [diff: ~tags]

**Comment by davidobrien1985** [comment]
So should it be pulumi's advice to always run a refresh?
If terraform does it, why not pulumi? Seeing that this might be a safer approach overall?

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by mikhailshilkov** [comment]
@davidobrien1985 I think we don't do this due to the performance penalty which is lost in 95% of the cases. See https://github.com/pulumi/pulumi/issues/2247 that tracks this.
You can choose to opt-in for refresh for every update with a CLI flag if that's your preference.

**Comment by davidobrien1985** [comment]
Before I close this issue, is this solution Pulumi's official solution to this problem? 
> You must run `refresh` if you are using the standalone `subnet` resource
This seems to be the recommended resource going forward as this also is the only way to add subnet private link etc.

**Comment by mikhailshilkov** [comment]
@davidobrien1985 Yes, this is my understanding, given how the TF provider is currently implemented.

**Comment by davidobrien1985** [comment]
Thanks @mikhailshilkov :)
