### ISSUE TITLE
Consider using strongly typed arg objects for empty .NET args

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#4303]
If I create a new resource without arguments, for instance:

```
var bucket = new Bucket("my-bucket");
```

Then we internally use a singleton `ResourceArgs+EmptyResourceArgs` instance as the argument object rather than a strongly typed argument object specific to that resource.

This makes generic transformations difficult to write.

For example, I wanted to write a transformation that automatically applies tags for well-known taggable types. I had assumed the transformations would receive dictionaries, but instead they receive fully typed argument objects. As a result, I need to resort to reflection to interact with them generically:

```
    public MyStack() : base(
            new StackOptions {
                ResourceTransformations = {
                    RegisterAutoTags(new Dictionary<string, string> {
                        { "User:Project", Deployment.Instance.ProjectName },
                        { "User:Stack", Deployment.Instance.StackName },
                        { "User:Cost Center", config.Require("costCenter") },
                    }),
                },
            }
        )
    {
...

    static ResourceTransformation RegisterAutoTags(Dictionary<string, string> autoTags) {
        return args => {
            if (IsTaggable(args.Resource.GetResourceType())) {
                var tagp = args.Args.GetType().GetProperty("Tags");
                var tags = (InputMap<object>)tagp.GetValue(args.Args, null) ?? new InputMap<object>();
                foreach (var tag in autoTags) {
                    tags[tag.Key] = tag.Value;
                }
                tagp.SetValue(args.Args, tags, null);
                return new ResourceTransformationResult(args.Args, args.Options);
            }
            return null;
        };
    }
```

Unfortunately, because the `ResourceArgs+EmptyResourceArgs` type does not define a `Tags` property, and because I believe I need to return a strongly typed object from the transformation, it would seem the only solution is to special-case every unique argument type? Notably, if we just passed an empty instance of `BucketArgs` here, the above approach would have worked fine.

**Comment by mikhailshilkov** [comment]
Done in 2.0
