### ISSUE TITLE
Request for adding Auth0 provider to Pulumi provider

### ISSUE THREAD

**Issue by AliBazzi** [pulumi/pulumi#4306]
Hi,

what is the process of requesting wrapping of existing provider, we are interested in having [Auth0 terraform provider](https://www.terraform.io/docs/providers/auth0/index.html) ported to Pulumi.

Please do let me know how the process of adding new providers works. 

Thank you.

**Comment by leezen** [comment]
Please take a look at https://github.com/pulumi/pulumi-tf-provider-boilerplate

**Comment by stack72** [comment]
Hi @AliBazzi 

I just wanted to check back to this item - there is a provider in progress for this. If you continue to track this issue, you will see the status soon

Paul

**Comment by stack72** [comment]
This provider has been released:

* https://www.npmjs.com/package/@pulumi/auth0
* https://pypi.org/project/pulumi-auth0/
* https://www.nuget.org/packages/Pulumi.Auth0

Docs will be available here - https://www.pulumi.com/docs/reference/pkg/auth0/ (when the [PR](https://github.com/pulumi/docs/pull/3350) is merged)

**Comment by AliBazzi** [comment]
Thanks for the effort here, much appreciated !
