### ISSUE TITLE
Cisco&VMware support

### ISSUE THREAD

**Issue by cvad2or** [pulumi/pulumi#4310]
Hello, 
Pulumi supports Infrastructure of Vmware and Cisco natively? If not can we import these providers from Terraform and modify them to support new resource?

Thanks,

**Comment by leezen** [comment]
Yes, you can import those providers from Terraform. Please see https://github.com/pulumi/pulumi-tf-provider-boilerplate as a starting point for doing so.

**Comment by leezen** [comment]
I should also point out if you mean vSphere support, that's already available via https://github.com/pulumi/pulumi-vsphere

**Comment by stack72** [comment]
Hi @cvad2or 

I am going to close this out - as @leezen rightly points out, we have a library that helps to scaffold these providers

Please let us know if you have any other questions

Paul
