### ISSUE TITLE
unrecognized plugin kind: aws

### ISSUE THREAD

**Issue by omerlh** [pulumi/pulumi#4319]
Following #4305 - plugin install failed with the following error:

```
pulumi plugin install aws
```

When running `pulumi plugin ls` I can see this plugin. What am I missing? I'm running those commands on our CI server using pulumi/pulumi:v1.14.0  docker image.

**Comment by stack72** [comment]
Hi @omerlh

Can you tell me if the Pulumi bin folder is added to PATH?

Paul

**Comment by omerlh** [comment]
Yes: 
```
docker run -it --entrypoint=/bin/bash pulumi/pulumi:v1.14.0 
root@ca1408b6807d:/# echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.pulumi/bin
```

**Comment by pgavlin** [comment]
@omerlh I think you may need to run

```
pulumi plugin install resource aws 1.30.0
```

Note the addition of the plugin kind (`resource`) and version.

**Comment by stack72** [comment]
Hi @omerlh 

Did the suggestion from @pgavlin work for you?

Paul

**Comment by omerlh** [comment]
Yes, thank you. sorry for the late response!
