### ISSUE TITLE
Program codegen: Go

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#4330]
- [ ] Resource variables
	- [ ] Basic instantiations
	- [ ] Ranged instantiations
		- [ ] Eventually-typed ranges (i.e. ranges that are promises or outputs)
	- [ ] Resource options
- [ ] Config variables
	- [ ] Typed config
	- [ ] Required config
	- [ ] Optional config
- [ ] Local variables
- [ ] Output variables
- [ ] Component declarations
- [ ] Component variables
- [ ] Expressions
	- [ ] Anonymous function expressions
	- [ ] Binary operator expressions
	- [ ] Conditional expressions
	- [ ] For expressions
	- [ ] Function call expressions
		- [ ] Apply intrinsic
		- [ ] Interpolate intrinsic (where necessary)
		- [ ] `entries`
		- [ ] `fileArchive`, `fileAsset`
		- [ ] `invoke`
		- [ ] `mimeType`
		- [ ] `range`
		- [ ] `readDir`
		- [ ] `toJSON`
		- [ ] etc.
	- [ ] Index expressions
	- [ ] Literal value expressions
		- [ ] Multi-line string literals
	- [ ] Object construction expressions
	- [ ] Relative traversal expressions
	- [ ] Scope traversal expressions
	- [ ] Splat expressions
	- [ ] Template expressions
	- [ ] Template join expressions
	- [ ] Tuple construction expressions
	- [ ] Unary operator expressions
- [ ] Applies
	- [ ] Proxied apply lowering
	- [ ] Interpolate lowering
- [ ] Trivia
	- [ ] Comments
	- [ ] Whitespace

**Comment by EvanBoyle** [comment]
Some sub-issues to track some of the more concrete outstanding work:

https://github.com/pulumi/pulumi/issues/4760
https://github.com/pulumi/pulumi/issues/4761
https://github.com/pulumi/pulumi/issues/4762
https://github.com/pulumi/pulumi/issues/4763
https://github.com/pulumi/pulumi/issues/4764
https://github.com/pulumi/pulumi/issues/4767
https://github.com/pulumi/pulumi/issues/4768
https://github.com/pulumi/pulumi/issues/4769
https://github.com/pulumi/pulumi/issues/4770
https://github.com/pulumi/pulumi/issues/4771
