### ISSUE TITLE
When importing a `ClusterRoleBinding` pulumi says there are input diffs

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi#4333]
I was trying to import a `ClusterRoleBinding` it was saying there were diffs from the code. Nothing showed different when running `preview --diff`, and when running `up --diff` it showed the `roleRef` and `subjects` being different.

The other part to this is that pulumi should not care if there is a difference between inputs and the code. What I would expect to happen is to run the `imports` and then ask again for the `up`. The reason I say this is because `import` should really be a separate task from `up` IMO.

https://pulumi-community.slack.com/archives/C84L4E3N1/p1586361564483100 for the conversation related to this issue.

**Comment by lukehoban** [comment]
> I was trying to import a ClusterRoleBinding it was saying there were diffs from the code. Nothing showed different when running preview --diff, and when running up --diff it showed the roleRef and subjects being different.

It will be useful to get a repro of this - I'm not immediately clear what would lead to that specific experience.

> The reason I say this is because import should really be a separate task from up IMO.

We are adding a `pulumi import` command in https://github.com/pulumi/pulumi/issues/1635 (and https://github.com/pulumi/pulumi/pull/4765), which I expect will match the flow you are looking for here more closely.

**Comment by nesl247** [comment]
Unfortunately I don't recall what I was doing at the time, I just created the issue quickly so it wouldn't get lost.

**Comment by mikhailshilkov** [comment]
We've introduced the `import` command since this issue was created and it's not clear what it's currently tracking. I'll go ahead and close it for now, let me know if there's a follow-up to be done here
