### ISSUE TITLE
Azure Authentication Issue. "Error building account: Error getting authenticated object ID: Error parsing json result from the Azure CLI: Error retrieving running Azure CLI: Unable to encode the output with cp1252 encoding. Unsupported characters are discarded."

### ISSUE THREAD

**Issue by sbugalski** [pulumi/pulumi#4342]
Hello,

Found issue with pulumi version v1.14.0 when going first time through Quick Start guide for Azure-Python
[out.txt](https://github.com/pulumi/pulumi/files/4453732/out.txt)

Steps to reproduce:
* choco install pulumi
* refreshenv
* mkdir quickstart ; cd quickstart
* pulumi config
* pulumi new azure-python
* py -3 -m venv venv
* .\venv\Scripts\Activate.ps1
* pip3 install -r .\requirements.txt
* python -m pip install --upgrade pip
* pulumi up

Azure CLI Version:
```
azure-cli                          2.3.1

command-modules-nspkg              2.0.3
core                               2.3.1
nspkg                              3.0.4
telemetry                          1.0.4

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\sb\.azure\cliextensions'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
```
[out.txt](https://github.com/pulumi/pulumi/files/4453736/out.txt)
[out.txt](https://github.com/pulumi/pulumi/files/4453737/out.txt)

**Comment by leezen** [comment]
Thanks for reporting this. I assume it works if you change your codepage to UTF-8?

**Comment by sbugalski** [comment]
@leezen 
```
PS C:\Users\sb\git\src\quickstart> chcp                                                                                 Active code page: 437
PS C:\Users\sb\git\src\quickstart> chcp 65001                                                                           Active code page: 65001
PS C:\Users\sb\git\src\quickstart> pulumi up                                                                            Previewing update (dev):
     Type                         Name            Plan       Info                                                        +   pulumi:pulumi:Stack          quickstart-dev  create                                                                     └─ azure:core:ResourceGroup  resource_group             1 error                                                    
Diagnostics:
  azure:core:ResourceGroup (resource_group):
    error: Error building account: Error getting authenticated object ID: Error parsing json result from the Azure CLI: Error retrieving running Azure CLI: Unable to encode the output with cp1252 encoding. Unsupported characters are discarded.
```

**Comment by komalali** [comment]
Hmm it's interesting that your codepage wasn't set to cp1252 originally (your output shows 437). There are a few instances of this error popping up in relation to the azure cli itself. 

From your logs it looks like you are using the azure CLI login, could you try using the [Service Principal Authentication](https://www.pulumi.com/docs/intro/cloud-providers/azure/setup/#service-principal-authentication) instead and let us know if you still run into the same issue?

**Comment by Rookian** [comment]
If we change the OS language from German to English, pulumi works as expected.

**Comment by sbugalski** [comment]
> Hmm it's interesting that your codepage wasn't set to cp1252 originally (your output shows 437). There are a few instances of this error popping up in relation to the azure cli itself.
> 
> From your logs it looks like you are using the azure CLI login, could you try using the [Service Principal Authentication](https://www.pulumi.com/docs/intro/cloud-providers/azure/setup/#service-principal-authentication) instead and let us know if you still run into the same issue?

Unfortunately it does not work either (SPN with owner role at subscription level).
[out2.txt](https://github.com/pulumi/pulumi/files/4497463/out2.txt)


> If we change the OS language from German to English, pulumi works as expected.
```
Get-WinSystemLocale                                                           
LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)
```

**Comment by TechWatching** [comment]
I have the same exact problem on my laptop (French language on OS). The workaround (chcp 65001) did not work for me either. Is there another workaround (apart from changing OS language ?) ? This is a quite blocking issue.
