### ISSUE TITLE
Python and TS inconsistency around code implementation

### ISSUE THREAD

**Issue by davidobrien1985** [pulumi/pulumi#4343]
Not sure if there's a proper way to explain what I mean, so here are two images.
The description of properties in Python is below the property, where in TS it's above. When going from one to another (i.e. different customer) it causes confusion. @mikhailshilkov even thinks this might be a bug?!

Python:
![image](https://user-images.githubusercontent.com/8554521/78873872-de323b00-7a8e-11ea-88dd-8900e9d8ed74.png)

TS:
![image](https://user-images.githubusercontent.com/8554521/78873811-c8bd1100-7a8e-11ea-8cb0-9a1087ee8eca.png)

**Comment by mikhailshilkov** [comment]
I think that's actually as intended. See

https://realpython.com/documenting-python-code/#class-docstrings
http://epydoc.sourceforge.net/manual-docstring.html#variable-docstrings

**Comment by davidobrien1985** [comment]
well then, must be a difference in the languages. I'll close this now.
