### ISSUE TITLE
Pulumi CLI crashes when unprotecting an empty stack

### ISSUE THREAD

**Issue by gpduck** [pulumi/pulumi#4405]
I'm writing a script to run some automated end-to-end testing and wanted it to be able to run on a completely local stack to avoid any locking or other conflicts if multiple people try to run tests at the same time.

# Repro Steps (Windows 10, PowerShell)

$env:PULUMI_CONFIG_PASSPHRASE = "mypassphrase"
pulumi login file://$pwd
pulumi stack select sandbox --create
pulumi state unprotect --all --yes --non-interactive

# Crash report

Pulumi Version:   v1.14.1
Go Version:       go1.13.10
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack(0xc00024b910, 0x1600e80, 0x2821090)
        C:/hostedtoolcache/windows/go/1.13.10/x64/src/runtime/debug/stack.go:24 +0xa4
main.panicHandler()
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x75
panic(0x1600e80, 0x2821090)
        C:/hostedtoolcache/windows/go/1.13.10/x64/src/runtime/panic.go:679 +0x1c0
main.unprotectAllResources.func1(0x185a73a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state_unprotect.go:74 +0x29
main.runTotalStateEdit(0x0, 0x0, 0x18a2a00, 0x18efd60, 0x28659a0, 0x0)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state.go:164 +0x25b
main.unprotectAllResources(0x0, 0x0, 0xc0001c8d00, 0xe, 0xe)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state_unprotect.go:73 +0x55
main.newStateUnprotectCommand.func1(0xc0002b8580, 0xc000512510, 0x0, 0x3, 0x0, 0x0)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state_unprotect.go:51 +0xeb
github.com/pulumi/pulumi/sdk/go/common/util/cmdutil.RunResultFunc.func1(0xc0002b8580, 0xc000512510, 0x0, 0x3)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x72
github.com/spf13/cobra.(*Command).execute(0xc0002b8580, 0xc000512360, 0x3, 0x3, 0xc0002b8580, 0xc000512360)
        d:/a/pulumi/pulumi/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000bc840, 0x0, 0x0, 0xc00024bf20)
        d:/a/pulumi/pulumi/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x31e
github.com/spf13/cobra.(*Command).Execute(...)
        d:/a/pulumi/pulumi/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
main.main()
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x6a

**Comment by clstokes** [comment]
I'm able to reproduce this on macOS too as an extra data point. I do not get this with the `app.pulumi.com` backend, so it seems specific to the local file backend.

macOS steps
```
pulumi login file://$PWD
pulumi stack select $(uuidgen) --create
pulumi state unprotect --all --yes --non-interactive
```

Full output
```
pulumi-gh-4405-2 % pulumi login file://$PWD
Logged into Camerons-MacBook-Pro.local as clstokes (file:///Users/clstokes/cc/scratch/pulumi-gh-4405-2)
pulumi-gh-4405-2 % pulumi stack select $(uuidgen) --create
Created stack '77F4FFE2-00C6-463F-BCC5-C2D450095240'
pulumi-gh-4405-2 % pulumi state unprotect --all --yes --non-interactive
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v1.14.1
Go Version:       go1.14.2
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack(0xc00071d878, 0x511a280, 0x62ccd80)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
	/private/tmp/pulumi-20200414-41085-1xrbvrm/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x6e
panic(0x511a280, 0x62ccd80)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
main.unprotectAllResources.func1(0x5353273, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/pulumi-20200414-41085-1xrbvrm/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state_unprotect.go:74 +0x22
main.runTotalStateEdit(0x0, 0x0, 0x5399100, 0x53e5e58, 0x631a900, 0x0)
	/private/tmp/pulumi-20200414-41085-1xrbvrm/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state.go:164 +0x254
main.unprotectAllResources(0x0, 0x0, 0xc0001c1100, 0xe, 0xe)
	/private/tmp/pulumi-20200414-41085-1xrbvrm/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state_unprotect.go:73 +0x4e
main.newStateUnprotectCommand.func1(0xc0006be840, 0xc0004f4180, 0x0, 0x3, 0x0, 0x0)
	/private/tmp/pulumi-20200414-41085-1xrbvrm/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state_unprotect.go:51 +0xe4
github.com/pulumi/pulumi/sdk/go/common/util/cmdutil.RunResultFunc.func1(0xc0006be840, 0xc0004f4180, 0x0, 0x3)
	/private/tmp/pulumi-20200414-41085-1xrbvrm/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc0006be840, 0xc0004f4090, 0x3, 0x3, 0xc0006be840, 0xc0004f4090)
	/private/tmp/pulumi-20200414-41085-1xrbvrm/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000256dc0, 0x15, 0x0, 0x0)
	/private/tmp/pulumi-20200414-41085-1xrbvrm/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/pulumi-20200414-41085-1xrbvrm/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
main.main()
	/private/tmp/pulumi-20200414-41085-1xrbvrm/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x4d
	/private/tmp/pulumi-20200414-41085-1xrbvrm/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x4d

pulumi-gh-4405-2 % 
```

**Comment by stack72** [comment]
Hi @gpduck 

Thanks for finding this issue - I just opened a PR that protects against the panic:

```
$ pulumi state unprotect --all --yes --non-interactive
error: no resources found to unprotect
```
