### ISSUE TITLE
Consider bumping checkpoint version post 2.0

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#4409]
Follow up from https://github.com/pulumi/pulumi/pull/4403#discussion_r409026252

We decided to defer bumping the statefile version, holding off until post-2.0-launch, so we can get more mileage on the changes.

Changes:
- https://github.com/pulumi/pulumi/commit/b29cf9c7502e3a464857039f6072c7edf2d7c886
- https://github.com/pulumi/pulumi-service/commit/a62cc9f01d840342f6d7a774c16fabb6e9283712
- https://github.com/pulumi/pulumi/commit/770c8071a420f2e56c7d5681fea57f1684eb7c31

**Comment by stack72** [comment]
@leezen maybe we need to consider this for Pulumi 3.0
