### ISSUE TITLE
Try to delete diag.Document

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#441]
See comments on #428 

> Random comment, I wonder if we should :boom: all the `diag.Document` stuff.
  
> I'm sure there are lingering references to it, but I don't think any of it is essential. Similar with the entire errors package. Do we already have a work item to delete the latter, and replace it with normal errors? If yes, maybe we can take care of both at the same time.

Probably makes sense to do a pass over the entire pulumi/pulumi repository and just get rid of stuff we aren't using anymore.

**Comment by swgillespie** [comment]
We've ripped out just about as much as we can from `pkg/tokens`, so I'm closing this.
