### ISSUE TITLE
Missing Python module typing annotations?

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#4416]
`mypy` doesn't seem to like something about the way our modules are structured:

![image](https://user-images.githubusercontent.com/3953235/79475118-20420c00-7fbc-11ea-9a48-7de0cb5b79fa.png)

This happens if I try dotting off the imported module directly, as in `import pulumi_aws as aws` and then declaring a resource as `aws.ec2.Vpc(...)`. The style of using `from pulumi_aws import ec2` works fine, however. It's very possible this is something about my configuration but given that it works for one form but not the other, my guess is that maybe we're missing a typing annotation somewhere?

**Comment by smcoll** [comment]
Same trouble- mypy is not comprehending the modules when imported this way:

```python
# __main__.py
import pulumi_aws
import pulumi_aws as aws

pulumi_aws.ec2.get_vpc(default='true')
aws.ec2.get_vpc(default='true')
```

```bash
$ mypy __main__.py
tmp.py:5: error: Module has no attribute "ec2"
tmp.py:6: error: Module has no attribute "ec2"
```

What i find interesting, though, is that as soon as i import the `ec2` module this way, anywhere in that file, the errors disappear:

```python
from pulumi_aws import ec2
```

```bash
$ mypy __main__.py
Success: no issues found in 1 source file
```

i haven't dug into it, but my guess is this is related to how `pulumi_aws/__init__.py` uses `importlib.import_module`.

**Comment by smcoll** [comment]
You know what, this was a problem in pulumi_aws 2.x but seems to be working in 3.x.

**Comment by justinvp** [comment]
This was when we adopted the changes from https://github.com/pulumi/pulumi/pull/4948 in the AWS provider.
