### ISSUE TITLE
Create a CI target to test pkg/codegen downstream dependencies

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#4421]
pkg/codegen has a bunch of downstream dependencies including `pulumi-terraform-bridge`, all of the providers, and docs. We don't have a way to trigger and E2E test from pulumi to verify new codegen changes. This probably isn't something we want to run on every build, given that CI currently takes ~40 minutes in pulumi/pulumi. Having something that we can run ad-hoc to bring more confidence to codegen specific changes would be helpful here.

**Comment by pgavlin** [comment]
Fixed with #4567.
