### ISSUE TITLE
Update homebrew, chocolatey for 2.0

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#4423]

**Comment by stack72** [comment]
Homebrew is merged - waiting on latest-version to update before triggering chocolatey

**Comment by stack72** [comment]
Chocolatey is now released as per https://ci.appveyor.com/project/Pulumi/pulumi-chocolatey/builds/32316830

**Comment by stack72** [comment]
https://chocolatey.org/packages/pulumi/2.0.0
