### ISSUE TITLE
pulumi plugin install doesn't support verbose logging

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#4427]
When trying to help someone with slow plugin downloads I tried to get verbose logging from `pulumi plugin install -v5 ...`, but get the error `An error occurred: unknown shorthand flag: 'v' in -v5`.

#### Suggestions for fix

Provide some helpful information from verbose logs such as:
- The URL that's being used for download
- The installation destination - e.g. `/Users/user1/.pulumi/plugins/...`
- The full request and response headers (maybe at a higher log level?)

#### Actual Output

```
Desktop % pulumi plugin install resource aws v0.16.2-dev -v5
Error: unknown shorthand flag: 'v' in -v5
Usage:
  pulumi plugin install [KIND NAME VERSION] [flags]

Flags:
      --exact           Force installation of an exact version match (usually >= is accepted)
  -f, --file string     Install a plugin from a tarball file, instead of downloading it
  -h, --help            help for install
      --reinstall       Reinstall a plugin even if it already exists
      --server string   A URL to download plugins from

Global Flags:
      --color string                 Colorize output. Choices are: always, never, raw, auto (default "auto")
  -C, --cwd string                   Run pulumi as if it had been started in another directory
      --disable-integrity-checking   Disable integrity checking of checkpoint files
  -e, --emoji                        Enable emojis in the output (default true)
      --logflow                      Flow log settings to child processes (like plugins)
      --logtostderr                  Log to stderr instead of to files
      --non-interactive              Disable interactive mode for all commands
      --profiling string             Emit CPU and memory profiles and an execution trace to '[filename].[pid].{cpu,mem,trace}', respectively
      --tracing file:                Emit tracing to the specified endpoint. Use the file: scheme to write tracing data to a local file
  -v, --verbose int                  Enable verbose logging (e.g., v=3); anything >3 is very verbose

An error occurred: unknown shorthand flag: 'v' in -v5
```

**Comment by mdaniel** [comment]
The long one appears to be a weirder message, although closer to the underlying root cause:
```console
$ pulumi --verbose=9 plugin install
Error: invalid argument "9" for "--verbose" flag: strconv.ParseBool: parsing "9": invalid syntax
$ pulumi version
v2.3.0
```

**Comment by clstokes** [comment]
Related to #5535.

**Comment by stack72** [comment]
```
▶ pulumi plugin install resource azure-nextgen v0.2.1 --verbose=true
[resource plugin azure-nextgen-0.2.1] installing
[resource plugin azure-nextgen-0.2.1] downloading from
Downloading plugin: 0 B / 17.82 MiB [----------------------------------]   0.00%[resource plugin azure-nextgen-0.2.1] installing tarball ...
Downloading plugin: 17.82 MiB / 17.82 MiB [=========================] 100.00% 9s
Moving plugin... done.
```

This is as verbose as the logs get here!

**Comment by clstokes** [comment]
@stack72 it would be great to get more detail in those error logs... e.g. the URL being download from, the location being downloaded _to_, and the location being moved to. If that deserves its own issue, let me know.

**Comment by stack72** [comment]
Yeah I think that is what we can do here - should be quite straight forward

I don't think we will be able to support the more detailed logs eg v=9 though

**Comment by clstokes** [comment]
Can we make it consistent with the actual `-v` flag like other commands and what shows in the help output? `--verbose=true` is "non standard" in my opinion?

**Comment by stack72** [comment]
So we can do it but there isn't enough happening here that can give us many log levels - I mean what do you expect v=5 to do? Or v=9?

If you can give me an idea of what you want at each level then I can implement it

**Comment by clstokes** [comment]
The log levels are opaque to the user anyway in my opinion, and given the messages being printed, I think a low level would be appropriate - e.g. `-v=2`?

**Comment by stack72** [comment]
Sounds good - I'll see what I can do here
