### ISSUE TITLE
Enable a plain build in addition to linting for each of the provider SDKs

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#4428]

**Comment by stack72** [comment]
This feels overkill if the linting tool does this already?

**Comment by leezen** [comment]
This was one of the outcomes of the post-mortem discussion on how we got into a state where we missed a type in the SDK. This would have to taken in the full context of overhauling the build. One thought was this could help de-couple linting from the build process:
- When linting is turned off for whatever reason, there's still protection due to the build
- We can run linting as a separate step in the build process

**Comment by pgavlin** [comment]
Is this still relevant? Sounds like the desire is to run the build with the linter disabled, and run the linter in a separate leg?

**Comment by stack72** [comment]
This can be closed out - I have an action item elsewhere
