### ISSUE TITLE
Be able to grant policies to roles based on the relationship between two resources

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#4429]
This would require some semantic level of understanding around what the possible actions against a resource are and how to model the policy for another resource to interact with it.

Of particular interest is the ability to grant permissions to a handler (e.g. Lambda function) to read/write from a resource along the line of:

```
this.table.grantReadWriteData(this.handler);
```

**Comment by mikhailshilkov** [comment]
I think I'm missing some context around this issue - but it doesn't feel like a core Pulumi issue - rather a provider or another package. Given its inactivity for two years, I'll go ahead and close it.
