### ISSUE TITLE
Stack command or option to just print the stacks name

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi#4444]
Currently there is no command or option to have the stack name printed out to the console. You have to run the `stack` command which prints out a bunch of information along with the name or you can run `stack ls` and grep for the selected one. 

Would be great to have a stack command like `stack current`, or `stack name`, or`stack ls --name` that just prints the current name.

**Comment by stack72** [comment]
I sorted of experimented today with “Pulumi stack —show-name”

Does this work for you?

**Comment by mitchellmaler** [comment]
Sure that works! Lines up with the other --show- flags.

**Comment by stack72** [comment]
Ok I’ll open the PR in the morning and tag you in it for reference
