### ISSUE TITLE
Unable to create Azure Storage Account with static website enabled: Error: static_website.0: invalid or unknown key: error404_document

### ISSUE THREAD

**Issue by jdudleyie** [pulumi/pulumi#4448]
When creating a `azure.storage.Account` (using TypeScript) and including staticWebsite -> error404Document property, I get the below error.

    azure:storage:Account rtsmarttagsprod  error: azure:storage/account:Account resource 'rtsmarttagsprod' has a problem:     static_website.0: invalid or unknown key: error404_document
        pulumi:pulumi:Stack rt-smart-tags-app-prod  
        azure:storage:Account rtsmarttagsprod  1 error
     
    Diagnostics:
      azure:storage:Account (rtsmarttagsprod):
        error: azure:storage/account:Account resource 'rtsmarttagsprod' has a problem: static_website.0: invalid or unknown key:     error404_document
     
    ##[error]Pulumi command exited with code '255' while trying to run 'up '.

From the terraform docs it looks like this should be named `error_404_document` - but Pulumi is trying to use the name `error404_document` so this might be why it is failing?

https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#error_404_document

I have tried as a workaround using the key `error_404_document` instead and casting the sub object type as `any` but this did not seem to work. 

Would there be a workaround to this? I suppose I could potentially use an Azure ARM template instead but I would prefer not to.

Typescript code block:

    return new azure.storage.Account(name, {
        location: locationNorthEurope,
        resourceGroupName: resourceGroupName,
        accountTier: 'Standard',
        accountReplicationType: 'LRS',
        accessTier: 'Hot',
        accountKind: 'StorageV2',
        enableHttpsTrafficOnly: true,
        staticWebsite: {
            indexDocument: 'index.html',
            error404Document: 'index.html',
        },
    });

**Comment by stack72** [comment]
Hi @jdudleyie 

My apologies for the issue here - this is something that has been reported and is being tracked https://github.com/pulumi/pulumi-azure/issues/512

I am going to close this issue out now that there is a reference between them and we can track it in one place

Thanks for reporting it

Paul

**Comment by gertjvr** [comment]
Hit the exact same issue today.
