### ISSUE TITLE
The core engine needs more testing

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#445]
There are a number of core scenarios that aren’t covered by the tests in this repository, which means that we can frequently miss bugs that affect workflows that are tested by other repositories. We should take advantage of the test/dynamic resource provider to add tests for these scenarios.

Here is a short list of scenarios we should cover:
- replacement operations
- CRUD operations that fail
- invalid inputs to Pulumi
- use of multiple stacks/configs/etc

**Comment by pgavlin** [comment]
We've made some pretty good progress here!
- The dynamic provider is now widely used in integration tests
- An additional testing framework has been brought online to enable very precise control of initial conditions and failure injection
- Work is ongoing to port this framework to use the Go language provider to make it even easier to write tests

**Comment by joeduffy** [comment]
@pgavlin @swgillespie Are there specific actions we want to take here? If yes, can we file work items for them, and close out this uber issue? Or at least turn it into a checklist above so we can track completion?

Alternatively, we can make this a recurring chore we revisit every sprint?

**Comment by pgavlin** [comment]
Nothing specific. Let's close this out.

**Comment by pgavlin** [comment]
Closing this out in favor of individual work items.
