### ISSUE TITLE
Add env var to skip interactive steps in CLI commands

### ISSUE THREAD

**Issue by migueloller** [pulumi/pulumi#4459]
Following a conversation with @lukehoban on Slack, I'm suggesting a feature is added to the CLI that allows for skipping interactive steps—during CI, for example.

In Pulumi v1 the desired behavior was there but it was implicit. For example, running `pulumi up` in CI would behave as running `pulumi up --non-interactive --yes`. In Pulumi v2, this implicit behavior was removed, and for good reasons. Updates are potentially destructive and implicitly doing this is thus potentially dangerous.

That being said, sometimes it might be desirable to avoid interactive steps, and while this is configurable per command (i.e., `--non-interactive` and `--yes`), having a global way to do this would be a great QoL improvement.

My suggestion is to add support for an env var that explicitly turns on the behavior from v1. Here are some suggested variable names:
- `PULUMI_NON_INTERACTIVE`
- `PULUMI_ALWAYS_YES`

I might also be worth thinking if the behavior should provide additional functionality instead of just implementing v1's behavior as is. For example, maybe the new behavior also skips previews? This might be out of scope, though.

**Comment by leezen** [comment]
Related https://github.com/pulumi/pulumi/issues/4457 and https://github.com/pulumi/pulumi/issues/4458
