### ISSUE TITLE
Pulumi hangs when creating a Cognito User Pool in LocalStack

### ISSUE THREAD

**Issue by jdtommy** [pulumi/pulumi#4493]
This may be more of a feature request. 

When creating a Cognito User Pool on local stack, Pulumi will just hang and then time out after an hour. It would be great if Pulumi had better integration with LocalStack

**Comment by leezen** [comment]
Could you please provide more details about the nature of the hang? Pulumi in general should never hang and has timeouts built in if the provider doesn't respond, so I'm curious if you could please provide verbose logs per https://www.pulumi.com/docs/troubleshooting/#verbose-logging

**Comment by jdtommy** [comment]
Thanks for the direction on logging. It appears there is a bug in LocalStack. Pulumi is able to create the User-Pool ok, but it then tries to set the pools MFA config and fails and tries 25 times with a step back so it takes a long time. 
```
DEBUG: Validate Response cognito-idp/SetUserPoolMfaConfig failed, attempt 10/25, error SerializationError: failed to unmarshal response error
status code: 500
```

I tried to use the aws cli to set-user-pool-mfa-config and get the same error. I even tried to get-user-pool-mfa-config and it returns the error.  I will create a bug in LocalStack.

**Comment by mklueh** [comment]
@jdtommy do you have any resource on how to even use Localstack with Pulumi?

**Comment by whummer** [comment]
@mklueh @jdtommy FYI, we have now created a thin wrapper script `pulumilocal` which should simplify the deployment to LocalStack: https://github.com/localstack/pulumi-local Looking forward to getting your feedback - thanks!

**Comment by mikhailshilkov** [comment]
Closing based on the suggestion to use https://github.com/localstack/pulumi-local
