### ISSUE TITLE
Containers don't contain `go` binaries

### ISSUE THREAD

**Issue by sam-myers** [pulumi/pulumi#4495]
I encountered the following issue when using GitHub Actions with the Go SDK.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/5410234/80268549-80f5d680-8697-11ea-8709-bccefd530836.png">

The GitHub Actions container uses [`pulumi/actions`](https://github.com/pulumi/pulumi/blob/master/dist/actions/Dockerfile) and is based on [`pulumi/pulumi`](https://github.com/pulumi/pulumi/blob/master/dist/pulumi/Dockerfile). Neither of those containers install Go.

I believe that this is unexpected behavior; the CI container should be able to handle all supported Pulumi SDKs. It makes sense to me that the base `pulumi/pulumi` container would be the sensible place for the installation to take place.

**Comment by stack72** [comment]
Hi @sam-myers 

This was fixed and released in v2.2.0 (13th May) of Pulumi - please do let us know if there are any issues 

Thanks

Paul
