### ISSUE TITLE
Pulumi not seeing configuration variables

### ISSUE THREAD

**Issue by recursivefunk** [pulumi/pulumi#4496]
I'm trying to use a configuration variable which is defined, but I'm getting an error message saying it is not defined and the instructions I'm given to resolve doesn't seem to work.

(truncated) output of `pulumi config`
```
KEY                 VALUE
aws:region          us-east-1
```

In the code
```javascript
const region = config.require('aws:region');
```

After `pulumi up`
```
Previewing update (dev):
     Type                 Name            Plan     Info
     pulumi:pulumi:Stack  say-l8r-js-dev           1 error
 
Diagnostics:
  pulumi:pulumi:Stack (say-l8r-js-dev):
    error: Missing required configuration variable 'say-l8r-js:aws:region'
        please set a value using the command `pulumi config set say-l8r-js:aws:region <value>`
```

Note the last line says `please set a value using the command pulumi config set say-l8r-js:aws:region <value>`

When I do that, I get
```
error: invalid configuration key: could not parse say-l8r-js:aws:region as a configuration key (configuration keys should be of the form `<namespace>:<name>`)
```

But as we see above, my configuration key *is* in the specified format. Hopefully, I'm missing something. Any ideas?

---
Pulumi v2 (was also happening with v1.x - I thought perhaps an upgrade would fix it)
Node v10.16.0

**Comment by leezen** [comment]
When you create the `Config` object, you can specify a namespace. If you don't specify a namespace, then it's assumed the namespace is the project name (`say-l8r-js`). You could either create a config object for the `aws` namespace and read the value from there, e.g. `const config = new pulumi.Config("aws"); region = config.require("region")` or you could have the config key simply be `region` and change your code to be `config.require("region")` with a corresponding `pulumi config set say-l8r-js:region us-east-1`

**Comment by slavafomin** [comment]
Hello!

Just wanted to share my negative experience.

Right now, Pulumi is handling config variables in absolutely counter-intuitive and cumbersome manner. I've spent an hour today, trying to figure out why my existing variables can't be read from the config.

What if I want to access my variables by using they fully-qualified name without the need to create a separate `Config` object for each namespace? Why is it making such trivial thing so hard?

I wish this could be simplified.

**Comment by diktamxx** [comment]
Terrible!
