### ISSUE TITLE
pulumi up error with NodePort

### ISSUE THREAD

**Issue by nik786** [pulumi/pulumi#4498]
pulumi version
v2.0.0

python --version
Python 3.6.9

I have met following error when I have defined NodePort instead of LoadBalancer as ServiceType in __main__.py

"""
Creating a Kubernetes Deployment
"""
import pulumi
from pulumi_kubernetes.apps.v1 import Deployment
from pulumi_kubernetes.core.v1 import Service

# Minikube does not implement services of type `LoadBalancer`; require the user to specify if we're
# running on minikube, and if so, create only services of type ClusterIP.
config = pulumi.Config()
is_minikube = config.require_bool("isMinikube")

app_name = "nginx"
app_labels = { "app": app_name }

deployment = Deployment(
    app_name,
    spec={
        "selector": { "match_labels": app_labels },
        "replicas": 1,
        "template": {
            "metadata": { "labels": app_labels },
            "spec": { "containers": [{ "name": app_name, "image": "nginx" }] }
        }
    })

# Allocate an IP to the Deployment.
frontend = Service(
    app_name,
    metadata={
        "labels": deployment.spec["template"]["metadata"]["labels"],
    },
    spec={
        "type": "ClusterIP" if is_minikube else "NodePort",
        "ports": [{ "port": 80, "target_port": 80, "protocol": "TCP" }],
        "selector": app_labels,
    })

result = None
if is_minikube:
    result = frontend.spec.apply(lambda v: v["cluster_ip"] if "cluster_ip" in v else None)
else:
    ingress = frontend.status.apply(lambda v: v["nodeport"]["ingress"][0] if "nodeport" in v else None)
    if ingress is not None:
        result = ingress.apply(lambda v: v["ip"] if "ip" in v else v["hostname"])

pulumi.export("ip", result)

error:

(venv) root@anode:/opt/play/pulumi/quickstart# pulumi up
Previewing update (dev):
     Type                           Name            Plan       
 +   pulumi:pulumi:Stack            quickstart-dev  create     
 +   ├─ kubernetes:apps:Deployment  nginx           create     
 +   └─ kubernetes:core:Service     nginx           create     
 
Resources:
    + 3 to create

Do you want to perform this update? yes
Updating (dev):
     Type                           Name            Status                  Info
 +   pulumi:pulumi:Stack            quickstart-dev  **creating failed**     3 errors
 +   ├─ kubernetes:apps:Deployment  nginx           created                 
 +   └─ kubernetes:core:Service     nginx           created                 
 
Diagnostics:
  pulumi:pulumi:Stack (quickstart-dev):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/root/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
        return future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/opt/play/pulumi/quickstart/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 81, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/opt/play/pulumi/quickstart/venv/lib/python3.6/site-packages/pulumi/runtime/stack.py", line 50, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/opt/play/pulumi/quickstart/venv/lib/python3.6/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 182, in _step
        result = coro.throw(exc)
      File "/opt/play/pulumi/quickstart/venv/lib/python3.6/site-packages/pulumi/runtime/resource.py", line 440, in do_register_resource_outputs
        serialized_props = await rpc.serialize_properties(outputs, {})
      File "/opt/play/pulumi/quickstart/venv/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 68, in serialize_properties
        result = await serialize_property(v, deps, input_transformer)
      File "/opt/play/pulumi/quickstart/venv/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 173, in serialize_property
        value = await serialize_property(output.future(), deps, input_transformer)
      File "/opt/play/pulumi/quickstart/venv/lib/python3.6/site-packages/pulumi/runtime/rpc.py", line 159, in serialize_property
        future_return = await asyncio.ensure_future(awaitable)
      File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
        future.result()
      File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/opt/play/pulumi/quickstart/venv/lib/python3.6/site-packages/pulumi/output.py", line 114, in get_value
        val = await self._future
      File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/opt/play/pulumi/quickstart/venv/lib/python3.6/site-packages/pulumi/output.py", line 155, in run
        value = await self._future
      File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
        result = coro.send(None)
      File "/opt/play/pulumi/quickstart/venv/lib/python3.6/site-packages/pulumi/output.py", line 176, in run
        transformed: Input[U] = func(value)
      File "./__main__.py", line 51, in <lambda>
        result = ingress.apply(lambda v: v["ip"] if "ip" in v else v["hostname"])
    TypeError: argument of type 'NoneType' is not iterable
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
 
Resources:
    + 3 created

Duration: 26s

Permalink: https://app.pulumi.com/nik/quickstart/dev/updates/3

can anyone help??

**Comment by nik786** [comment]
But deployment and service get creates in k8s inspite of having this weird error

**Comment by leezen** [comment]
By the time the code has errored, the resources have been created, so that's expected behavior.

Checking for `ingress is not None` won't actually do what you want (which is why you're running into this error) because `ingress` is an `Output` in your code (because it's the result of an `apply`). You can move this non-check within the lambda itself to avoid this.

**Comment by nik786** [comment]
Hi @leezen 
Honestly saying I'm not able to understand this particular part

result = None
if is_minikube:
    result = frontend.spec.apply(lambda v: v["cluster_ip"] if "cluster_ip" in v else None)
else:
    ingress = frontend.status.apply(lambda v: v["nodeport"]["ingress"][0] if "nodeport" in v else None)
    if ingress is not None:
        result = ingress.apply(lambda v: v["ip"] if "ip" in v else v["hostname"])

pulumi.export("ip", result)

You said "You can move this None check within the lambda itself to avoid this."
Can you help me to edit this part to bypass the error??

**Comment by leezen** [comment]
Something along the lines of:

```
def get_result(val):
    ingress = v["nodeport"]["ingress"][0] if "nodeport" in v else None
    if ingress is not None:
        return v["ip" if "ip in v else v["hostname"]
    return None

ingress = frontend.status.apply(lambda v: get_result)
```

Where the None check moves inside the lambda.

**Comment by nik786** [comment]
Hi @leezen 
I have edited like this

#result = None
if is_minikube:
    result = v["cluster_ip"] if "cluster_ip" in v else None
else:
    ingress = v["nodeport"]["ingress"][0] if "nodeport" in v else None
    if ingress is not None:
        return v["ip" if "ip in v else v["hostname"]
    return None

ingress = frontend.status.apply(lambda v:  result)
#pulumi.export("ip", result)

**Comment by nik786** [comment]
This one is latest

result = None
if is_minikube:
    result = v["cluster_ip"] if "cluster_ip" in v else None
else:
    ingress = v["nodeport"]["ingress"][0] if "nodeport" in v else None
    if ingress is not None:
        return v["ip" if "ip"in v else v["hostname"]
    return None

ing = frontend.status.apply(lambda v: ingress)


#pulumi.export("ip", result)

**Comment by nik786** [comment]
It worked with this config

result = None
if is_minikube:
    result = frontend.spec.apply(lambda v: v["cluster_ip"] if "cluster_ip" in v else None)
else:
    ingress = frontend.status.apply(lambda v: v["nodeport"]["ingress"][0] if "nodeport" in v else None)
#    if ingress is not None:
#        result = ingress.apply(lambda v: v["ip"] if "ip" in v else v["hostname"])

pulumi.export("ip", result)
