### ISSUE TITLE
Support for delete before create

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#450]
We always use "create before delete" today.  This works well for resources that don't hold any "precious" external handles.  But especially for low level infrastructure, resoures will often hold on to  handles that must be unique.

For example:
1. A NAT Gateway holds an Elastic IP, and cannot be re-created (in a different subnet for example) using the same Elastic IP until the old NAT Gateway is deleted.
2. A subnet holds onto a section of the CIDR block for it's VPC.  It cannot be changed (from private to public for example) without first deleting the old subnet and then creating the new one.

Now, both of these will become highly destructive operations as a result of needing to delete before create.  But that is a fundamental part of what is required to be able to use these infrastructure components.

**Comment by Dominik-K** [comment]
[Documentation for `deleteBeforeReplace` in "Programming Model"](https://www.pulumi.com/docs/intro/concepts/programming-model/#deletebeforereplace) (in case someone comes here from search-engine).
