### ISSUE TITLE
GCS failed with rateLimitExceeded during pulumi up, destroying the state

### ISSUE THREAD

**Issue by farcaller** [pulumi/pulumi#4500]
A bit of a sad situation. Running pulumi 2.0.0. The `pulumi up` failed with:

> error: post-step event returned an error: failed to save snapshot: An IO error occurred during the current operation: blob (key ".pulumi/stacks/example.prod.json") (code=Unknown): googleapi: Error 429: The rate of change requests to the object pulumi-state/.pulumi/stacks/example.prod.json exceeds the rate limit. Please reduce the rate of create, update, and delete requests., rateLimitExceeded

This happened during a k8s helm turnup.

I think pulumi just keeps polling the state or something until eventually google explodes. That's no good.

What makes it worse is that `pulumi-state/.pulumi/stacks/example.prod.json` is now gone, so effectively I lost all the state. I think that's a suboptimal behavior there. Pulumi should try its best to preserve the state. At the very worst I expected the write to fail, leaving the old blob intact.

**Comment by lukehoban** [comment]
This is being tracked in https://github.com/pulumi/pulumi/issues/4258.
