### ISSUE TITLE
Pulumi re-evaluates the js code between previewing and applying

### ISSUE THREAD

**Issue by farcaller** [pulumi/pulumi#4501]
Coming from terraform, the expectation is whatever you preview is what you're going to apply. With pulumi (2.0.0) it's not the case.

If you run `pulumi up`, check the preview, then modify something in your configuration, the updated configuration will get applied.

**Comment by lukehoban** [comment]
This is in part related to a fundamental difference in how Pulumi works. But we are looking into providing a way to constrain updates to what was approved in a preview to provide the same confidence that all changes have been previewed and approved. See https://github.com/pulumi/pulumi/issues/2318.
