### ISSUE TITLE
pulumi thinks i am in non-interactive mode all the time

### ISSUE THREAD

**Issue by dustinfarris** [pulumi/pulumi#4503]
Getting this in my local terminal (iTerm, Fish shell):

```
> pulumi up
error: --yes must be passed in to proceed when running in non-interactive mode
```

**Comment by jaxxstorm** [comment]
Can you output the value of `env`, redacting any potentially secret information? Thanks!

**Comment by dustinfarris** [comment]
It looks like this started happening when I upgraded from fish 3.1.0 to [3.1.1](https://github.com/fish-shell/fish-shell/releases/tag/3.1.1).

### env

```
COLORFGBG=15;0
COLORTERM=truecolor
COMMAND_MODE=unix2003
CPPFLAGS=-I/usr/local/opt/openssl@1.1/include
DJANGO_ENV=local
EDITOR=nvim
ERL_AFLAGS=-kernel shell_history enabled
GIT_EDITOR=nvim
GPG_TTY=/dev/ttys001
HOME=/Users/dustin
ITERM_PROFILE=Dustin
ITERM_SESSION_ID=w0t0p0:A2C663F0-B746-433E-99C8-2ADEC3AC1705
LANG=en_US.UTF-8
LC_TERMINAL=iTerm2
LC_TERMINAL_VERSION=3.3.9
LDFLAGS=-L/usr/local/opt/openssl@1.1/lib
LOGNAME=dustin
LaunchInstanceID=00C2F6EA-3BED-4BFD-8EF2-AC469911037E
NVM_BIN=/Users/dustin/.nvm/versions/node/v12.13.1/bin
NVM_CD_FLAGS=
NVM_DIR=/Users/dustin/.nvm
NVM_HAS_RUN=1
PATH=/Users/dustin/.pyenv/libexec:/Users/dustin/.pyenv/plugins/python-build/bin:/Users/dustin/.pyenv/plugins/pyenv-virtualenv/bin:/Users/dustin/.pyenv/plugins/pyenv-update/bin:/Users/dustin/.pyenv/plugins/pyenv-installer/bin:/Users/dustin/.pyenv/plugins/pyenv-doctor/bin:/Users/dustin/.nvm/versions/node/v12.13.1/bin:/Users/dustin/.pyenv/libexec:/Users/dustin/.pyenv/plugins/python-build/bin:/Users/dustin/.pyenv/plugins/pyenv-virtualenv/bin:/Users/dustin/.pyenv/plugins/pyenv-update/bin:/Users/dustin/.pyenv/plugins/pyenv-installer/bin:/Users/dustin/.pyenv/plugins/pyenv-doctor/bin:/Users/dustin/.pyenv/shims:/Users/dustin/.pyenv/bin:/Users/dustin/go/bin:/usr/local/opt/openssl/bin:./node_modules/.bin:/usr/local/opt/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PKG_CONFIG_PATH=/usr/local/opt/openssl@1.1/lib/pkgconfig
PWD=/Users/dustin/src/pulumi-ucboitlake
PYENV_ROOT=/Users/dustin/.pyenv
PYENV_SHELL=fish
PYENV_VIRTUALENV_DISABLE_PROMPT=1
SECURITYSESSIONID=186a6
SHELL=/usr/local/bin/fish
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.25mOneYu4n/Listeners
SSL_CERT_FILE=/usr/local/etc/openssl@1.1/cert.pem
TERM=xterm-256color
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.3.9
TERM_SESSION_ID=w0t0p0:A2C663F0-B746-433E-99C8-2ADEC3AC1705
TMPDIR=/var/folders/6c/gnqxmq_90kv6nl08m_xphw9m0000gn/T/
USER=dustin
VISUAL=nvim
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
__CF_USER_TEXT_ENCODING=0x0:0:0
nvm_prefix=/Users/dustin/.nvm
```

**Comment by dustinfarris** [comment]
This might be related https://github.com/fish-shell/fish-shell/issues/6955 — I'll be tracking that issue.  Hopefully it is resolved soon and I'll test against pulumi to see if this is also resolved.

**Comment by clstokes** [comment]
@dustinfarris I saw your comment on that issue - just to confirm, did downgrading back to fish-shell 3.1.0 resolve this?

**Comment by dustinfarris** [comment]
Yes, this was a regression in fish 3.1.1.  Fish 3.1.2 was released today and should fix it—I'll test that out tomorrow.  Sorry for the false alarm—pulumi cli happened to be the first program where I experienced the error cause I'm living in the pulumi lately! ;-)

**Comment by sachinm24** [comment]
I am running into this on mac with bash as shell

**Comment by leezen** [comment]
Could you dump your env vars as Dustin did? That would be helpful in determining if there's anything that might be causing that.

**Comment by sachinm24** [comment]
> Could you dump your env vars as Dustin did? That would be helpful in determining if there's anything that might be causing that.

```bash
SHELL=/usr/local/bin/bash
ITERM_PROFILE=Default
COLORTERM=truecolor
XPC_FLAGS=0x0
TERM_PROGRAM_VERSION=3.3.9
TMUX=/private/tmp/tmux-501/default,65004,0
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.AEU0xnFEER/Listeners
TERM_SESSION_ID=w0t0p0:A26580C1-F858-4C64-B4CF-F4C097462638
PWD=***
LOGNAME=***
ITERM_SESSION_ID=w0t0p0:A26580C1-F858-4C64-B4CF-F4C097462638
HOME=***
LANG=en_US.UTF-8
JENKINS_TOKEN=
VIRTUAL_ENV=***
JENKINS_URL=***
TMPDIR=/var/folders/8c/vspvhfc90mngvy01w0pknh4w0000gn/T/
LC_TERMINAL=iTerm2
TERM=screen
USER=***
TMUX_PANE=%1
COLORFGBG=0;15
KMS=***
LC_TERMINAL_VERSION=3.3.9
SHLVL=2
BANNER_ENV=****
XPC_SERVICE_NAME=0
KUBECONFIG=****
PS1=(venv) \h:\W \u\$
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.WT7NjRKrIn/Render
PATH=***
OLDPWD=***
GOPATH=***
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
TERM_PROGRAM=iTerm.app
_=/usr/bin/env

```

**Comment by leezen** [comment]
Thanks. `JENKINS_URL` is one of the env vars that Pulumi CLI uses to detect CI environments. Could you please try unsetting that?

**Comment by sachinm24** [comment]
> Thanks. `JENKINS_URL` is one of the env vars that Pulumi CLI uses to detect CI environments. Could you please try unsetting that?

Cool that did it. Can we add this to a troubleshooting guide?

**Comment by boillodmanuel** [comment]
In looked in source code to find the cause:
- Interactive mode detection: https://github.com/pulumi/pulumi/blob/v2.10.1/sdk/go/common/util/cmdutil/console.go#L48
   - If CI is detected, terminal is defined as non-interactive
- CI detection: https://github.com/pulumi/pulumi/blob/v2.10.1/sdk/go/common/util/ciutil/detect.go#L138
   - Disable CI detection with `PULUMI_DISABLE_CI_DETECTION=true`

So using `PULUMI_DISABLE_CI_DETECTION=true pulumi up` can help to diagnostic if an env variable related to CI cause pulumi to run in non-interactive mode
