### ISSUE TITLE
Investigate Python tooling support (IDE doc strings, type checking, etc.)

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#4510]
The outcome of this issue should be a proposal document outlining alternatives considered, the recommendation, and a discussion (async or sync) with consensus from the team on moving forward.

Use either the "Interested Parties" or "Pulumi RFC" template (available via Google Docs "New from Template")

**Comment by lukehoban** [comment]
Related: https://github.com/pulumi/pulumi/issues/3765.

**Comment by leezen** [comment]
Closing as we've reviewed the document and will move on to implementation
