### ISSUE TITLE
Azure Devops Provider

### ISSUE THREAD

**Issue by gertjvr** [pulumi/pulumi#4511]
Is anybody working on a provider to automate azure devops 

- creating projects, 
- repositories, 
- pipelines

cc @stack72

**Comment by tmeckel** [comment]
https://github.com/tmeckel/pulumi-azuredevops
https://github.com/tmeckel/pulumi-azuredevops-samples

**Comment by gertjvr** [comment]
@tmeckel looking at the code, am I right to assume its using microsoft/terraform-provider-azuredevops?

**Comment by tmeckel** [comment]
Yes sure it does. Why implementing a native Pulumi provider when there's a maintained Terrform provider from Microsoft. Is there an issue with going that way?

**Comment by gertjvr** [comment]
@tmeckel  Umm the maintained provider from Microsoft you speak of hasn't been released yet and has some interesting issue. 

- What you call maintained I call still in development.  
https://github.com/microsoft/terraform-provider-azuredevops/issues/166

- Can't use a secret in the variables groups, otherwise, it will always recreate the variable group
https://github.com/microsoft/terraform-provider-azuredevops/issues/170

I wouldn't release this provider unless it is made clear to the users that the engine which it is built on might change without notice.

**Comment by gertjvr** [comment]
Can see its nearly ready once this https://github.com/microsoft/terraform-provider-azuredevops/issues/241 is released, think you would be good to go.

**Comment by stack72** [comment]
Hi all

delighted to be able to say that this provider has now been released:

https://pypi.org/project/pulumi-azuredevops/
https://www.nuget.org/packages/Pulumi.AzureDevOps
https://www.npmjs.com/package/@pulumi/azuredevops

This is based on the newly published terraform provider and is thanks to the work of @tmeckel 

The PR for the docs is in flight right now and will be merged soon
