### ISSUE TITLE
Python - numbers get typed as floats, but should be integers

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#4514]
In Python, some resource arguments that are integers (ports, counts, etc) are typed as float when they should be integers. 

Examples:
- `port` at https://www.pulumi.com/docs/reference/pkg/aws/elasticache/replicationgroup/#inputs
- `max_size`, `min_size `, `default_cooldown `, `desired_capacity `, etc. at https://www.pulumi.com/docs/reference/pkg/aws/autoscaling/group/#properties
- `priority` at https://www.pulumi.com/docs/reference/pkg/gcp/compute/firewall/
- `partitions`, `replication_factor` at https://www.pulumi.com/docs/reference/pkg/kafka/topic/#inputs

**Comment by justinvp** [comment]
I'm actually not sure why we haven't typed these as `int`.
https://github.com/pulumi/pulumi/blob/2585b86aa4252b1ea430dbfd2324c47ea57763b1/pkg/codegen/python/gen.go#L1546-L1547

.NET codegen types them as `int`:

https://github.com/pulumi/pulumi/blob/2585b86aa4252b1ea430dbfd2324c47ea57763b1/pkg/codegen/dotnet/gen.go#L287-L290

I don't see any reason why we couldn't do the same for Python. Would need to confirm it doesn't cause any problems roundtripping through serialization/deserialization.

**Comment by justinvp** [comment]
It's worth considering this now as we're refining the type annotations.
