### ISSUE TITLE
NodeJS/TypeScript programmatic exports

### ISSUE THREAD

**Issue by mrsimonemms** [pulumi/pulumi#4528]
In both Python and Golang, the exports are programmatic - eg, in Python, you call `pulumi.export('public_ip', server.public_ip)`.

For `<reasons>`, I could do with doing a similar sort of thing in TypeScript - is there any way of getting TS to create outputs with a pulumi method rather than the `export const public_ip = server.public_up`?

**Comment by leezen** [comment]
There's no way directly that I know of. Depending on what you're trying to do, an alternative to using the `export` syntax is to have a top-level function return the outputs as in the second example shown on: https://www.pulumi.com/docs/intro/languages/javascript/#entrypoint

```
export = async () => {
    // create resources
    return { out: myResource.output };
}
```

So, you could imagine writing something along the lines of:
```
export = async () => {
    exports = {};
    const myExport = <T>(key: string, val: pulumi.Output<T>) => {
        exports[key] = val;
    }

    myExport("hello", pulumi.output("test"));

    function foo() {
        myExport("bar", pulumi.output({
            "key": "value"
        }));
    }

    foo();

    // create resources
    return exports;
}
```

**Comment by JElgar** [comment]
Is it possible to add this to the roadmap? I'm happy to have a look at adding this. The reason being this work around is possible but for some use cases not ideal. My example is I am creating a shared component which creates a container app and a managed certificate in azure. It has a bit of a weird circular dependency so we have to know if the certificate has already been created already or not (and use that to create the definition of the container app). This is managed by creating an output with the certificate id (if its created). Ideally the custom component could create an output in the constructor so the consumer of that component doesn't have to care.
