### ISSUE TITLE
Need Pulumi Pagerduty provider

### ISSUE THREAD

**Issue by vijay-balakrishnan** [pulumi/pulumi#4540]
Pagerduty provider is missing in Pulumi provider. Nice to have pagerduty api, so we can create all those integration in via Pulumi.

opening an Issue as per @clstokes.

**Comment by bharbron** [comment]
FYI, we (GrubHub SREs) have created a pulumi_pagerduty provider using the [pulumi-tf-provider-boilerplate](https://github.com/pulumi/pulumi-tf-provider-boilerplate). We can push it up to a `pulumi/pulumi_pagerduty` repo if Pulumi creates it.

**Comment by leezen** [comment]
@bharbron That's great! Any chance you're in the Community Slack so we can more easily coordinate (or let us know if you have a preferred way to communicate directly with you)

**Comment by bharbron** [comment]
I am not currently in the community slack, but I'll go ahead and join it.

**Comment by stack72** [comment]
@bharbron when you join DM me on there and we can work out creating you a repo

**Comment by stack72** [comment]
Hi @bharbron 

Just pinging back on this - if you want to mail me - stack72@pulumi.com and we can take care of this :)

Paul

**Comment by stack72** [comment]
Thanks to all of the hard work put in by @bharbron, I have just published this provider as a 1.0.0 :)

https://www.npmjs.com/package/@pulumi/pagerduty
https://pypi.org/project/pulumi-pagerduty/
https://www.nuget.org/packages/Pulumi.Pagerduty
