### ISSUE TITLE
UnitTesting a Blob throws "Unsupported value when converting to protobuf: Pulumi.FileAsset"

### ISSUE THREAD

**Issue by StefH** [pulumi/pulumi#4558]
**Stack**
``` c#
private class BlobStack : Stack
{
    public BlobStack()
    {
        var blobArgs = new BlobArgs
        {
            AccessTier = BlobAccessTiers.Hot,
            Name = "test",
            Source = new FileAsset(Path.Combine(FilesFolder, "TextFile1.txt")),
            StorageAccountName = "sa",
            StorageContainerName = "sa",
            Type = BlobTypes.Block
        };

        var blobOptions = new CustomResourceOptions
        {
            Parent = this
        };

        _ = new Blob("test", blobArgs, blobOptions);
    }
}
```

Where
``` c#
private static string FilesFolder => Path.Combine(Directory.GetParent(Directory.GetCurrentDirectory()).FullName, "netcoreapp3.1", "files");
```
And the "TextFile1.txt" does exists.

**Unit test:**
``` c#
[Fact]
public async Task Blob()
{
    // Arrange and Act
    var resources = await Testing.RunAsync<BlobStack>();

    // Assert
    resources.Length.Should().Be(2);
    var blob = resources.OfType<Blob>().FirstOrDefault();

    Assert.NotNull(blob);
    blob.GetResourceName().Should().Be("test");
}
```

**Throws:**

> Pulumi.RunException : Running program 'C:\Users\xxx\.nuget\packages\microsoft.testplatform.testhost\16.5.0\build\netcoreapp2.1\x64\testhost.dll' failed with an unhandled exception:
> System.InvalidOperationException: Unsupported value when converting to protobuf: Pulumi.FileAsset
>    at Pulumi.Serialization.Serializer.CreateValue(Object value)
>    at Pulumi.Serialization.Serializer.CreateStruct(ImmutableDictionary`2 serializedDictionary)
>    at Pulumi.Testing.MockMonitor.SerializeAsync(Object o)
>    at Pulumi.Testing.MockMonitor.RegisterResourceAsync(Resource resource, RegisterResourceRequest request)
>    at Pulumi.Deployment.RegisterResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options)
>    at Pulumi.Deployment.ReadOrRegisterResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options)
>    at Pulumi.Deployment.CompleteResourceAsync(Resource resource, ResourceArgs args, ResourceOptions options, ImmutableDictionary`2 completionSources)
>    at Pulumi.Deployment.Runner.WhileRunningAsync()
>    at Pulumi.Deployment.TestAsync[TStack](IMocks mocks, TestOptions options)
>    at Pulumi.Azure.Extensions.Tests.Storage.BlobCollectionTests.Blob() in C:\Users\StefHeyenrath\Documents\GitHub\Pulumi.Azure.Extensions\tests\Pulumi.Azure.Extensions.Tests\Storage\BlobCollectionTests.cs:line 92
> --- End of stack trace from previous location where exception was thrown ---

**Comment by StefH** [comment]
I did update the Testing.cs example code with 2 parts:

**NewResourceAsync** : do not just pass the inputs, but use a Convert method to skip invalid values
``` c#
mocks.Setup(m => m.NewResourceAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<ImmutableDictionary<string, object>>(), It.IsAny<string>(), It.IsAny<string>()))
                .ReturnsAsync((string type, string name, ImmutableDictionary<string, object> inputs, string? provider, string? id) => (id ?? Guid.NewGuid().ToString(), Convert(inputs)));
```
**Convert** method looks like:
``` c#
private static ImmutableDictionary<string, object> Convert(ImmutableDictionary<string, object> dictionary)
{
    var builder = ImmutableDictionary.CreateBuilder<string, object>();
    foreach (var entry in dictionary)
    {
        // https://github.com/pulumi/pulumi/issues/4558
        switch (entry.Value)
        {
            case int _:
            case double _:
            case bool _:
            case string s:
            case ImmutableArray<object> _:
            case ImmutableDictionary<string, object> _:
                builder.Add(entry.Key, entry.Value);
                break;
        }
    }

    return builder.ToImmutable();
}
```

Full solution can be found at
https://github.com/StefH/Pulumi.Azure.Extensions/blob/master/tests/Pulumi.Azure.Extensions.Tests

**Comment by mikhailshilkov** [comment]
FWIW, I mention this problem and a workaround in this blog post: https://www.pulumi.com/blog/unit-testing-cloud-deployments-with-dotnet/#website-files

**Comment by StefH** [comment]
Thanks for the blog with information and the work-arounds.

I'll close this issue, however all these workarounds make it very hard and complex to quickly start writing simple unit-tests.
