### ISSUE TITLE
Confluent Cloud Provider

### ISSUE THREAD

**Issue by rafaribe** [pulumi/pulumi#4562]
Does Pulumi support Confluent Cloud as a provider or is there some way to create the Confluent Cloud resources like Kafka Clusters, API credentials, and environments with Pulumi? 
I've found only this [terraform one](https://github.com/Mongey/terraform-provider-confluentcloud) written by a fellow dev.

**Comment by leezen** [comment]
There's no provider for it yet, but you could create one using the instructions from https://github.com/pulumi/pulumi-tf-provider-boilerplate

If you go down that route, we'd be happy to work with you on turning it into a community provider.

**Comment by rafaribe** [comment]
Since the original source code is not mine, I would prefer doing it [natively](https://github.com/pulumi/pulumi-provider-boilerplate).

**Comment by rafaribe** [comment]
Are there some good examples where I can base my code on?

**Comment by mastoj** [comment]
@rafaribe, did you create some provider for confluent? I would really love to see that happen.

**Comment by rafaribe** [comment]
Not yet, I've managed to deploy the stuff using some scripts, but maybe I'll do a second attempt with the terraform bridge. I couldn't find any good examples to build a pulumi provider natively so I went another way @mastoj

**Comment by mastoj** [comment]
@stack72 is there a roadmap or anything that visualize the providers you intend to do. 

I totally understand if you don’t have this on a roadmap, but would be nice to know if you do.

**Comment by stack72** [comment]
Hi folks

Just circling back on this:

* https://github.com/pulumi/pulumi-confluent
* https://www.pulumi.com/docs/reference/pkg/confluent/
* https://npmjs.com/package/@pulumi/confluent
* https://pypi.org/project/pulumi-confluent/
* https://www.nuget.org/packages/Pulumi.Confluent
