### ISSUE TITLE
`--yes` shouldn't be required for commands that won't have any `yes/no` prompts

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#4569]
Using `--skip-preview` is an alternative to using `--yes`.  It should be allowed to pass that without needing to also pass `--yes` as there will be no `yes/no` prompt.

```
➜  foo pulumi up --skip-preview --non-interactive
error: --yes must be passed in to proceed when running in non-interactive mode
```

**Comment by joeduffy** [comment]
Just hit this myself -- agree this seems unnecessary!
