### ISSUE TITLE
Pulumi.yaml must be capitalized

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#457]
I would assume that the Pulumi tooling would do a case-insensitive search for pulumi.yaml. But as it turns out, the file name must exactly be `Pulumi.yaml` with a capital 'P'. Is there a specific reason why this is fixed?

I'm happy to fix this low-priority issue. I just wanted to make sure there wasn't some specific reason for this behavior beforehand. It looks like we just need to update `IsProject` and friends in [pkg/workspace/paths.go](https://github.com/pulumi/pulumi/blob/master/pkg/workspace/paths.go).

**Comment by lukehoban** [comment]
This hasn't come up again in the last 2 years - I think its "just the way it is".

**Comment by komalali** [comment]
It only took 2.5 more years but it finally came up!

(@lukehoban) Seems reasonable to do either of these if anyone want to pick it up:
* support lowercase
* Recognize lowercase and warn/error

**Comment by dixler** [comment]
My 2 cents, but I think having a standard case sensitive file is reasonable and makes file lookup simpler.

**Comment by lukehoban** [comment]
It's been another 2 years, and ultimately agree that being case senstive remains a reasonable answer here.  Will close out (again 😄) as by design.

**Comment by jkodroff** [comment]
Note that this restriction also applies to stack config files. On MacOS, either is fine: `pulumi.dev.yaml` works as well as `Pulumi.dev.yaml`. In Pulumi Deployments, the case-sensitivity matters: `pulumi.dev.yaml` will not get picked up, due to the case-sensitivity of the underlying filesystem.

**Comment by crazybolillo** [comment]
Not everyone uses Linux and this is just personal opinion but the capital letter stands out like a sore thumb, feels like I am sinning against UNIX. Seems like a PR was never made, I can get one out if agreed with.
