### ISSUE TITLE
Issue on pulumi up command when console shows incorrectly interpreted character.

### ISSUE THREAD

**Issue by Samuel-Dufour** [pulumi/pulumi#4580]
Using Pulumi version 2.1.0 on Windows 10 installed in French, when I execute `pulumi up`, I get an error related to restore command output.
The output contains a badly encoded character (`Identification des projets � restaurer...` instead of `Identification des projets à restaurer...`) and I get the following error : 
```
error: failed to discover plugin requirements: Problem executing 'dotnet build -nologo .': rpc error: code = Internal desc = grpc: error while marshaling: proto: field "pulumirpc.LogRequest.Message" contains invalid UTF-8
```
Here are the related logs when executing `pulumi up --logtostderr -v=9 2> out.txt` :

``` 
I0506 23:35:25.628773   25160 eventsink.go:70] eventSink::Info(<{%reset%}>  Identification des projets à restaurer...
<{%reset%}>)

I0506 23:35:25.628773   25160 langruntime_plugin.go:92] langhost[dotnet].GetRequiredPlugins(proj=testPulumi,pwd=C:\Users\Samuel\Projects\testPulumi,program=.) failed: err=Problem 
executing 'dotnet build -nologo .': rpc error: code = Internal desc = grpc: error while marshaling: proto: field "pulumirpc.LogRequest.Message" contains invalid UTF-8

I0506 23:35:26.147300   25160 sink.go:154] defaultSink::Error([38;5;1merror: [0m[0mfailed to discover plugin requirements: Problem executing 'dotnet build -nologo .': rpc error: code 
= Internal desc = grpc: error while marshaling: proto: field "pulumirpc.LogRequest.Message" contains invalid UTF-8
```

I was able to execute `pulumi up` by switching windows language to english to avoid accentuated characters in command logs.

It seems to be related to [this issue](https://github.com/pulumi/pulumi/issues/4044).

Hope it helps !

**Comment by leezen** [comment]
It does indeed seem related to the issue you linked. I'll keep this open for now until we track down what's going on in case this is somehow different.
