### ISSUE TITLE
Program codegen: add type annotations to object constructor expressions

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#4587]
My biggest struggle with C# program codegen is lack of schema type information while producing object initializers. Here is an illustrative example.

A PP snippet:

```hcl
resource bucket "aws:s3:Bucket" {
	loggings = [{
		targetBucket = logs.bucket,
	}]
	tags = {
		Name = "mybucket"
	}
}
```

should translate to C#:

```cs
var bucket = new Aws.S3.Bucket("bucket", new Aws.S3.BucketArgs
{
    Loggings = 
    {
        new Aws.S3.Inputs.BucketLoggingArgs  // <-- 1
        {
            TargetBucket = logs.BucketName, // <-- 2
        },
    },    
    Tags = // <-- 3
    {
        { "Name", "mybucket" }
    }        
});
```

Notice three places where we need the corresponding schema type to make decisions:

1. Input type name for `Loggings` property (or rather element type in this case).
2. `BucketName` is an overridden property name in C# because `Bucket` is not allowed.
3. `Tags` is a dictionary. In PP it looks exactly like any other object constructor expression, so we need type metadata to make this decision.

My understanding is that we need to extend `ObjectConsExpression` and/or `TupleConsExpression` with a schema type annotation, similar to what we did for `FunctionCallExpression`.

I can't seem to find a simple way to do so. @pgavlin would you be able to give that a try?

**Comment by pgavlin** [comment]
> similar to what we did for FunctionCallExpression.

What are you referring to here?

**Comment by mikhailshilkov** [comment]
It has `Signature` with `StaticFunctionSignature` having schema type information, if I remember correctly from looking in the debugger

**Comment by pgavlin** [comment]
Okay. What you're seeing is probably the schema information that is attached to the `*model.ObjectType`s that are present in the `Signature`. That is independent of the signature itself. There are similar annotations in the types used for resource inputs and outputs.

**Comment by pgavlin** [comment]
This need is met by #4594.
