### ISSUE TITLE
Generated apply is wrong in Node/EKS program codegen example

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#4588]
Node.js program gen generates a wrong line [here](https://github.com/pulumi/pulumi/blob/8fded5f29f961b978802ea30ee817967d1f0f0cc/pkg/codegen/internal/test/testdata/aws-eks.pp.ts#L53).

```ts
const subnetIds = pulumi.all([vpcSubnet, __item.id]).apply(([vpcSubnet, id]) => vpcSubnet.map(__item => id));
```
should actually be
```ts
const subnetIds = vpcSubnet.then(vpcSubnet => vpcSubnet.map(vpcSubnet => vpcSubnet.id));
```

**Comment by pgavlin** [comment]
Fixed by #4589.
