### ISSUE TITLE
S3 Bucket(s) in broken state

### ISSUE THREAD

**Issue by gdhagger** [pulumi/pulumi#4592]
Today I started receiving the error:
`preparing urn:pulumi:dev::pulumi-test::aws:s3/bucket:Bucket::web-assets-bucket's old property state: expected string or JSON map; got <nil>`

This initially happened on a large existing project, but I am able to quickly replicate the issue by attempting to import one of the problem buckets in a fresh AWS+Typescript project slightly modified from the template.

Full contents of my simple project index.ts:
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

// Create an AWS resource (S3 Bucket)
// const bucket = new aws.s3.Bucket("my-bucket");

// const bucket = aws.s3.Bucket.get('web-assets-bucket','irisvr-dev-web-assets')

const bucket = new aws.s3.Bucket('web-assets-bucket', {
  bucket: 'irisvr-dev-web-assets'
}, {
  import:'irisvr-dev-web-assets'
})

// Export the name of the bucket
export const bucketName = bucket.id;
```

I can successfully 'get' the bucket by commenting that section and commenting the 'new', but importing immediately throws the error at the top of this issue.

Attached is the output of `TF_LOG=TRACE pulumi up --logtostderr -v=9 2> out.txt`
[out.txt](https://github.com/pulumi/pulumi/files/4596551/out.txt)

**Comment by leezen** [comment]
What are the versions of the pulumi CLI (`pulumi version`) and SDK (`@pulumi/pulumi` in your `package.json`) you're using?

**Comment by gdhagger** [comment]
`2.1.0`

**Comment by gdhagger** [comment]
Also discovered that I can reproduce this failure attempting to import some other buckets in our AWS account that were never managed by Pulumi, but not all.

Some buckets import just fine - but there's no setting I can see via the S3 console that appears to be different, permissions wise or anything else.

**Comment by danfhernandez** [comment]
Can you share your `package.json`?  I tried to reproduce with 2 pulumi projects below but didn't run into any issues. 

Create bucket: 
``` typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

// Create an AWS resource (S3 Bucket)
// const bucket = new aws.s3.Bucket("my-bucket");

// const bucket = aws.s3.Bucket.get('web-assets-bucket','irisvr-dev-web-assets')

const bucket = new aws.s3.Bucket('web-assets-bucket', {
  bucket: 'pulumi-dev-web-assets'
})

// Export the name of the bucket
export const bucketName = bucket.id;
```

Import bucket: 
``` typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

// Create an AWS resource (S3 Bucket)
// const bucket = new aws.s3.Bucket("my-bucket");

// const bucket = aws.s3.Bucket.get('web-assets-bucket','irisvr-dev-web-assets')

const bucket = new aws.s3.Bucket('web-assets-bucket', {
  bucket: 'pulumi-dev-web-assets'
}, {
  import:'pulumi-dev-web-assets'
})

// Export the name of the bucket
export const bucketName = bucket.id;
```

`package.json`: 
``` json
{
    "name": "s3-zendesk-import-2",
    "devDependencies": {
        "@types/node": "^10.0.0"
    },
    "dependencies": {
        "@pulumi/pulumi": "^2.0.0",
        "@pulumi/aws": "^2.0.0",
        "@pulumi/awsx": "^0.18.10"
    }
}
```

**Comment by jaxxstorm** [comment]
There's an interesting error in the logs

```
I0507 21:24:34.888965   26879 eventsink.go:59] [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?>
I0507 21:24:34.888976   26879 eventsink.go:62] eventSink::Debug(<{%reset%}>[aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?><{%reset%}>)
I0507 21:24:34.889084   26879 eventsink.go:59] <Error><Code>NoSuchTagSet</Code><Message>The TagSet does not exist</Message><BucketName>irisvr-dev-web-assets</BucketName><RequestId>829855315F0285F8</RequestId><HostId>tfif0hvhQApvEPMIdC0ZKJO0UIbqQ8OzlncD/VGCVqHqC1kPqG1gjWs4K7QJ8zGim6+ZOL+aJac=</HostId></Error>
```

Did the problem buckets have their tags removed?

**Comment by gdhagger** [comment]
package.json is
```
{
    "name": "pulumi-test",
    "devDependencies": {
        "@types/node": "^10.0.0"
    },
    "dependencies": {
        "@pulumi/pulumi": "^2.0.0",
        "@pulumi/aws": "^2.0.0",
        "@pulumi/awsx": "^0.18.10"
    }
}
```

`npm list | grep pulumi` output:
```
pulumi-test@ /home/graham/Projects/irisvr/pulumi-test
├─┬ @pulumi/aws@2.3.0
│ ├── @pulumi/pulumi@2.1.0 deduped
├─┬ @pulumi/awsx@0.18.14
│ ├─┬ @pulumi/aws@1.31.0
│ │ ├── @pulumi/pulumi@1.14.1 deduped
│ ├─┬ @pulumi/docker@0.17.4
│ │ ├─┬ @pulumi/pulumi@1.14.1
│ │ │ ├── @pulumi/query@0.3.0 deduped
│ ├─┬ @pulumi/pulumi@1.14.1
│ │ ├── @pulumi/query@0.3.0 deduped
├─┬ @pulumi/pulumi@2.1.0
│ ├── @pulumi/query@0.3.0
```

**Comment by gdhagger** [comment]
As mentioned before, if I play around with different buckets, some work, others don't.  And most bizarrely of all, the one I included in my initial sample (`irisvr-dev-web-assets`) now works fine, but it's twin from another environment (`irisvr-sbx-web-assets`) still does not.

Re: tags - none of these buckets have ever had tags.

I believe they were originally created in another stack with Pulumi, and I've successfully moved a bunch of items between stacks/projects before without issue.  It's actually quite possible these were created via Terraform and imported into an earlier Pulumi project.

**Comment by gdhagger** [comment]
Problem seems to be something to do with `@pulumi/aws` `2.3.0`

If I modify my `package.json` to:
```
{
    "name": "pulumi-test",
    "devDependencies": {
        "@types/node": "^10.0.0"
    },
    "dependencies": {
        "@pulumi/pulumi": "^2.0.0",
        "@pulumi/aws": "2.2.0",
        "@pulumi/awsx": "^0.18.10"
    }
}
```
then wipe out my `node_modules` dir and run `npm i`
everything works fine:
```
Previewing update (dev):
     Type                 Name               Plan        Info
     pulumi:pulumi:Stack  pulumi-test-dev
 +-  └─ aws:s3:Bucket     web-assets-bucket  replace     1 warning

Diagnostics:
  aws:s3:Bucket (web-assets-bucket):
    warning: inputs to import do not match the existing resource; importing this resource will fail


Do you want to perform this update?  [Use arrows to move, enter to select, type to filter]
  yes
> no
  details
```

If I bump the version to `2.3.0`, and again wipe my `node_modules` and reinstall:

```{
    "name": "pulumi-test",
    "devDependencies": {
        "@types/node": "^10.0.0"
    },
    "dependencies": {
        "@pulumi/pulumi": "^2.0.0",
        "@pulumi/aws": "2.3.0",
        "@pulumi/awsx": "^0.18.10"
    }
}
```

```
Previewing update (dev):
     Type                 Name               Plan       Info
     pulumi:pulumi:Stack  pulumi-test-dev               1 error
 =>  └─ aws:s3:Bucket     web-assets-bucket  import     1 error

Diagnostics:
  pulumi:pulumi:Stack (pulumi-test-dev):
    error: preview failed

  aws:s3:Bucket (web-assets-bucket):
    error: Preview failed: preparing urn:pulumi:dev::pulumi-test::aws:s3/bucket:Bucket::web-assets-bucket's old property state: expected string or JSON map; got <nil>```


Unfortunately simply downgrading my real project and wiping/reinstalling the node_modules doesn't seem to be enough to fix things with one of my environments.  Fortunately that's my sandbox env and I can blow chunks of it away temporarily if I need to.

**Comment by gdhagger** [comment]
Fixed my sandbox!!!

I had to remove any pre-existing state for the buckets and any of their dependencies (ie, cloudfront distribution, and the DNS records pointing to those) and set those deps up to also be re-imported.

I think I'd already done a bunch of that in my dev environment hence I'd fallen into that fix when testing the downgrade.

With that done and `@pulumi/aws` downgraded to `2.1.0` I was able to re-import all the broken bits and get my stack back in working order.

Not closing this issue as the problem with `2.3.0` still exists

**Comment by leezen** [comment]
@justinvp Could this be related to what we serialize to the statefile for imports?

**Comment by justinvp** [comment]
@leezen, Possibly. I am not sure.

**Comment by rarous** [comment]
Hi, I got into the same situation. I created new stack and used CustomResource for static website infrastructure we use on many other stack, but here it started to fail. Workaround with pinned v2.1 works fine.

**Comment by gdhagger** [comment]
For the record I've been fine with v2.2 as well - I think I initially downgraded to v2.1 because that's what I'd been using just before breakage.

**Comment by leezen** [comment]
@rarous What do you mean by used `CustomResource`? Are you importing a bucket similar to the original issue?

**Comment by rarous** [comment]
@leezen sorry, I forget to link [the resource](https://github.com/topmonks/topmonks-webs/blob/master/.scripts/pulumi-resources/website.ts). It is not importing, it is creating from scratch, but next update in CI failed with the same error.

**Comment by robpark** [comment]
FWIW I'm seeing the same issue updating just an S3 bucket with a website option set. 

Python:
```
Arpeggio==1.9.2
attrs==19.3.0
dill==0.3.1.1
grpcio==1.28.1
parver==0.3.0
protobuf==3.11.3
pulumi==2.1.0
pulumi-aws==2.3.0
semver==2.10.0
six==1.14.0
```

**Comment by stack72** [comment]
Fixing this issue in https://github.com/pulumi/pulumi-terraform-bridge/pull/191

**Comment by stack72** [comment]
Pending release of pulumi-aws to fix this!
