### ISSUE TITLE
Docker image pulumi/actions doesn't have golang installed

### ISSUE THREAD

**Issue by MacTynow** [pulumi/pulumi#4599]
[The documentation](https://www.pulumi.com/docs/guides/continuous-delivery/github-actions/#demos-and-examples) and [the docker hub page](https://hub.docker.com/r/pulumi/actions) mention that you can use the `pulumi/actions` image with any language. However, when using golang, you'd run into the following:

```
error: failed to discover plugin requirements: couldn't find go binary: unable to find program: go
```

Indeed, golang isn't installed in this image (unlike python or nodejs).

I see two solutions to this problem:
1. Add golang to the image
2. Have one image per language (which would make each image smaller and faster to pull)

Let me know your thoughts and I'd be glad to write a PR for any chosen solution.

**Comment by jaxxstorm** [comment]
I've opened #4612 to get this installed for now which will close this issue. We have #4599 open at the moment for creating smaller, language-focused builds for our docker images which I think is an important step.
