### ISSUE TITLE
Lifecycle Hooks for Resources (and Provisioners)

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#4600]
#99
#1691

**Comment by CanRau** [comment]
Yes please 🙏
I'd love to add DNS records to an external domain, that would be fantastic 🎉

**Comment by lukehoban** [comment]
We've closed out #99 as part of releasing the Pulumi [Command](https://www.pulumi.com/registry/packages/command/) package.  

We've kept #1691 open to track some deeper language level hooks in the resource lifecycle.

I'll close this meta issue out for now, and the remaining work will be tracked in #1691.
