### ISSUE TITLE
Indicate required properties when creating resource objects in IDE

### ISSUE THREAD

**Issue by ardalon** [pulumi/pulumi#4601]
Version: Pulumi for C#

While it can be inferred which are required [singleton] properties for a given resource by looking at the Pulumi SDK class definitions for which properties are nullable and which are not.  It would increase productivity and be more elegant to decorate required attributes using language constructs.  This will then be picked up by the Visual Studio IDE and Errors will be displayed without need for compiling or running pulumi up, which will eliminate countless inner loop cycles.

Also: collection property types are not nullable and so trial and error/re-reading docs is needed, which slows productivity.

**Comment by lukehoban** [comment]
I believe this is the same as https://github.com/pulumi/pulumi/issues/3808. Does that look like the same issue?  If so, please do upvote that one and we can close this out.

**Comment by ardalon** [comment]
Yes it appears to be the same.  Sorry about that!
