### ISSUE TITLE
RewriteConversions and RewriteApplies don't work together

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#4610]
In my .NET programgen, I'm processing expressions with both rewriting conversions and applies:

```go
expr = hcl2.RewriteConversions(expr, typ)
expr, _ = hcl2.RewriteApplies(expr, nameInfo(0), true)
```

However, applies within a conversion isn't resolved. I get

```cs
var vpc = ...; // Output<GetVpcResult>
var subnets = Aws.Ec2.GetSubnetIds.InvokeAsync(new Aws.Ec2.GetSubnetIdsArgs
{
    VpcId = vpc.Apply(vpc => vpc.Id), // <-- this isn't converted
});
```

instead of

```cs
var vpc = ...; // Output<GetVpcResult>
var subnets = vpc.Apply(vpc => Aws.Ec2.GetSubnetIds.InvokeAsync(new Aws.Ec2.GetSubnetIdsArgs
{
    VpcId = vpc.Id,
}));
```

cc @pgavlin

**Comment by pgavlin** [comment]
Can you try flipping the phase ordering? i.e. run `RewriteConversions` after `RewriteApplies`?

**Comment by mikhailshilkov** [comment]
I did, and then the converts stopped working... I felt like this order makes more sense?

**Comment by pgavlin** [comment]
> I did, and then the converts stopped working... I felt like this order makes more sense?

Can you elaborate? What does the IR look like in each case?

**Comment by pgavlin** [comment]
As a general rule, IR is preferable to output code when debugging. Dumping the IR is as simple as `log.Printf("%v", expr)`.

**Comment by pgavlin** [comment]
Ah, and it looks like the actual problem is in the "lifted apply" transformation, not the apply rewriter itself. It looks like the apply rewriter is doing the right thing (applies are being inserted), but the apply -> property access lowering phase is missing potential lifted accesses b/c the conversions are tripping up its pattern matching. Is that right?

**Comment by mikhailshilkov** [comment]
Convert, then Apply
```
invoke("aws:ec2:getSubnetIds", __convert( {
	vpcId = __apply(vpc, eval(vpc, vpc.id))}))
```

Apply, then Convert
```
__convert(__apply(__convert(vpc),eval(vpc,  invoke("aws:ec2:getSubnetIds", {
	vpcId = vpc.id})
```

**Comment by pgavlin** [comment]
> Ah, and it looks like the actual problem is in the "lifted apply" transformation, not the apply rewriter itself. It looks like the apply rewriter is doing the right thing (applies are being inserted), but the apply -> property access lowering phase is missing potential lifted accesses b/c the conversions are tripping up its pattern matching. Is that right?

^^ Disregard this. I think I missed that `vpc` is itself an `Output<string>`.

**Comment by pgavlin** [comment]
Regarding the conversions getting tripped up by the applies: this is my mistake, and what I get for avoiding `model.VisitExpression`. The conversion rewriter is not properly descending into all child expressions. I'll send a fix shortly.

**Comment by mikhailshilkov** [comment]
Sorry for the possible confusion, but `vpc` is `Output<GetVpcResult>`, so apply gets its `id` and that's fine

**Comment by pgavlin** [comment]
https://github.com/pulumi/pulumi/pull/4614

**Comment by pgavlin** [comment]
This is now fixed.
