### ISSUE TITLE
GitHub App not updating PR status/check

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#4613]
We've had multiple users in our Community Slack report that the Pulumi GitHub App is not updating the status/check on pull requests with the results of the `pulumi preview`. I've not been able to reproduce this, so opening this issue on their behalf.

For clarity:
![image](https://user-images.githubusercontent.com/293763/81731528-e857a880-9443-11ea-8632-b5d80b801e21.png)

See https://pulumi-community.slack.com/archives/C84L4E3N1/p1585163434020800 for more context.

**Comment by praneetloke** [comment]
@danfhernandez @clstokes this should now be resolved with Pulumi CLI version 2.5.0. I'll close this out if one of you could also try it out?

**Comment by Incisive** [comment]
Works great on my end, thanks for addressing this !

**Comment by praneetloke** [comment]
Awesome! Thanks for the checking, @Incisive.
