### ISSUE TITLE
[Go SDK] Add serialization support for untyped fields

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi#4629]
Add support for an untyped map field that looks something like this:

```go
type CustomResource struct {
    OtherFields pulumi.MapOutput `pulumi:""`
}
```

**Comment by lblackstone** [comment]
@pgavlin Will you have a chance to work on this this morning, or need me to look into it? Aiming to cut k8s provider release tomorrow with this change.

**Comment by pgavlin** [comment]
Working on this now
