### ISSUE TITLE
Passing config value as stdin doesn't show create new stack prompt

### ISSUE THREAD

**Issue by matkarasiewicz** [pulumi/pulumi#4637]
```
$pulumi config set --stack newstack --path newstack:key value

The stack 'newstack ' does not exist.

If you would like to create this stack now, please press <ENTER>, otherwise press ^C:
```
```
$echo "value" | pulumi config set --stack newstack --path newstack:key 

error: no stack named 'newstack ' found
```
Expected:
`pulumi config set` command with passed value in stdin should show create new stack prompt

**Comment by leezen** [comment]
This is by design in that piping values in to `pulumi` assumes you're in a non-interactive shell. You could change this to `pulumi stack select newstack --create` followed by the config set.
