### ISSUE TITLE
Unable to use Azure Key Vault Secret Provider in China

### ISSUE THREAD

**Issue by carterwilliamson** [pulumi/pulumi#4642]
When initializing a stack with
```bash
pulumi up --secrets-provider https://<keyvault_name>.vault.azure.cn/keys/<keyname>
```

I got the following error

`error: invalid keyID "https://<keyvault_name>.vault.azure.cn/keys/<keyname>"; must match ^(https://.+\.vault\.azure\.net/)keys/(.+)$ []`

(This was a useful error message. Was very clear.)
This seems like a valid secrets provider if we can change the regex to include `.cn`.

**Comment by jaxxstorm** [comment]
I've moved this to the pulumi repo because it's actually used inside the pulumi CLI

**Comment by carterwilliamson** [comment]
I posted this in slack, but it couldn't hurt to x-post here
We put together and tested a regex for this
`^(https://.+\\.vault\\.(?:azure\\.net|azure\\.cn|usgovcloudapi\\.net)/)keys/(.+)$`

**Comment by jaxxstorm** [comment]
Thanks @carterwilliamson - I've also added the Azure Germany region, I'm putting an alpha build together now!

**Comment by jaxxstorm** [comment]
@carterwilliamson I've built a patched version of pulumi using the changes you suggested, can you give it a try? You can install it using:

```
curl -fsSL https://get.pulumi.com/ | bash -s -- --version "2.3.0-alpha.1589491786"
```

Which will install to `$HOME/.pulumi/bin/pulumi`

If this fixes your issue, I'll get this released for you!

**Comment by carterwilliamson** [comment]
@jaxxstorm Looks like the authentication backend might not be getting set correctly.

I've set the following:
```
AZURE_CLIENT_ID
AZURE_CLIENT_ID
AZURE_CLIENT_ID
```

error: secrets (code=InvalidArgument): azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://idca-public.vault.azure.cn/keys/pulumisharedkey//encrypt?api-version=7.0: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://vault.azure.net was not found in the tenant named ***. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 95fe8910-4076-4fc8-beaa-397aeb489100\r\nCorrelation ID: b79875d9-b4dd-4c01-bb6e-5511ba5c214c\r\nTimestamp: 2020-05-15 18:28:25Z","error_codes":[500011],"timestamp":"2020-05-15 18:28:25Z","trace_id":"95fe8910-4076-4fc8-beaa-397aeb489100","correlation_id":"b79875d9-b4dd-4c01-bb6e-5511ba5c214c","error_uri":"https://login.chinacloudapi.cn/error?code=500011"}

**Comment by carterwilliamson** [comment]
I browsed the source code. Looks like additionally I need to set `AZURE_AD_RESOURCE`. I'm going to try this and see if that works.

**Comment by carterwilliamson** [comment]
Setting `AZURE_AD_RESOURCE=https://vault.azure.cn` fixed that error and it works as expected. Thanks @jaxxstorm !!

**Comment by jaxxstorm** [comment]
Awesome, thanks @carterwilliamson I'll get this into our next release!

**Comment by carterwilliamson** [comment]
@jaxxstorm something new popped up during testing. Any ideas?
China Key Vault was working and then just kind of... stopped.
`error: constructing secrets manager of type "cloud": secrets (code=PermissionDenied): keyvault.BaseClient#Decrypt: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="Unauthorized" Message="Error validating token: IDX10500"`
