### ISSUE TITLE
Install dependencies automatically for new Python projects

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#4645]
Consider making it easier to get started using Python with Pulumi by automatically creating a virtual environment and installing dependencies as part of `pulumi new` (like we do with other languages), and automatically using the virtual environment when running `pulumi up`.

Basically avoid the need to show 3 separate commands that must be copy/pasted/run before running `pulumi up`.

Here's one way this could work:

[![asciicast](https://asciinema.org/a/SaTwxisZ684t61t6Zbg4GSftp.svg)](https://asciinema.org/a/SaTwxisZ684t61t6Zbg4GSftp)

1. When creating a *new* Python project with `pulumi new`, we run `python -m venv venv` on your behalf (using the same lookup logic we use to invoke `python` today, including using `PULUMI_PYTHON_CMD` if set or looking for both  `python3` and  `python`).

2. We then update `Pulumi.yaml` to tell it to use the virtual environment:

    ```yaml
    runtime:
      name: python
      options:
        virtualenv: venv
    ```

    `virtualenv` is a new runtime option for Python. It is the path to a virtual environment for Pulumi to use. If set, we will effectively “activate” this virtual environment before invoking Python commands from Pulumi, by setting the appropriate environment variables, such that any `exec.Command` runs of `python` or `pip` from Pulumi will use the virtual environment.

3. We then install dependencies by running `pip install -r requirements.txt` (which will use the `pip` from the virtual environment), just like how we automatically install dependencies for other languages.

4. We no longer need to output commands that must be copy/pasted/run before running `pulumi up`. We simply indicate the project is ready to go and you can run `pulumi up` to deploy your project.  Since the `Pulumi.yaml` has `virtualenv` set, we run the Python program using the virtual environment when `pulumi up` is run.

If you don’t want Pulumi to automatically use the virtual environment, e.g. you want to use your own approach to virtual environments (like using Pipenv; or installing dependencies globally on the system), then simply remove the `virtualenv` option that was added to `Pulumi.yaml` (and optionally delete the `venv` directory), and then use whatever approach you want before running `pulumi` just like before. 

## Additional things to think about:

- `cdk8s init python` appears to be doing something similar (looks like it uses [Pipenv](https://pipenv.pypa.io)).

- If this only works with `pulumi new`, how can we make it easy to use for existing projects that don't already have the virtual environment created (e.g. clone git repo and trying to get started with an example).

**Comment by skela** [comment]
is there any way to rename the requirements.txt file? an option to set the name of the file in Pulumi.yaml or some such?

I tend to prefer to name the file Pipfile...
