### ISSUE TITLE
`pulumi stack export --show-secrets` does not prompt for passphrase 

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#4648]
All other commands that need the passphrase prompt the user for it.  While this isn't blocking (I can use the env var), it is inconsistent.

```
➜  stackmigration pulumi stack export --show-secrets > stack.json
error: could not deserialize deployment: decrypting secret value: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase
```

**Comment by lukehoban** [comment]
Same is true when importing a stack file with plaintext secrets (i.e. generated from the command above):

```
➜  stackmigration pulumi stack import < stackimport.json 
error: could not deserialize deployment: encrypting secret value: failed to encrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase
```

**Comment by stack72** [comment]
Sorry for missing this @lukehoban - I’ll pick it up and fix it

**Comment by lukehoban** [comment]
After re-reviewing this - it appears that this is just caused by being in non-interactive mode due to the `> stack.json`, and so is expected and consistent with other places we do the same.  The should work fine with `--file` instead.  Given that - closing this as by-design.
