### ISSUE TITLE
No resource plugin 'digitalocean' found in the workspace or on your $PATH

### ISSUE THREAD

**Issue by sudhanshuraheja** [pulumi/pulumi#4651]
I'm on pulumi version v2.2.1 and am using Go and DigitalOcean for the project.

The instructions for setting up a new project on [DigitalOcean](https://www.pulumi.com/docs/intro/cloud-providers/digitalocean/setup/) were not as clear as the ones on AWS (which suggests using `pulumi new aws-go`), so I started the project with `pulumi new go`.

On trying to getup a droplet I'm getting the following error

```txt  pulumi:providers:digitalocean (default):
    error: no resource plugin 'digitalocean' found in the workspace or on your $PATH
```

I tried `pulumi plugin` on the command list, and it had help available about how to install a plugin.
```txt Available Commands:
  install     Install one or more plugins
  ls          List plugins
  rm          Remove one or more plugins from the download cache
```

However, trying to install `pulumi plugin install resource digitalocean` throws the error `error: missing plugin version argument`

So, I tried to find the available version online, and the closest thing that I could find was [this page]( https://www.pulumi.com/docs/get-started/install/versions/), however `pulumi plugin install resource digitalocean 2.2.1` did not work.

I brute forced by trying different versions starting from 1.0.0. and reached 2.4.1. (I am assuming this is the highest version because 2.5.0 and 2.4.2 did not work).

Could you confirm if this is the right version number to use, and if not what would be the right one to use?

Summarising version numbers
Pulumi: v2.2.1
Go: go version go1.14.2 darwin/amd64
OS: MacOS Catalina (10.15.4)
Provider: DigitalOcean

**Comment by leezen** [comment]
Sorry for the confusion. If you declare a dependency on pulumi-digitalocean in your `go.mod` the plugin should be acquired automatically as part of program execution. https://github.com/pulumi/pulumi-digitalocean/releases details the set of available releases, so yes, 2.4.1 is correct.
