### ISSUE TITLE
[Community] Adopt Github Discussions for threaded Q/A

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#4654]
While a lot of people seem to like Slack, I think it's usefullness is highly overrated. 

When I post questions, I want to first analyse what I experienced and then post it with more context than just a one-liner. Preparing that message in Slack's message editor is very cumbersome. Also, finding previous questions on Slack is very hard, also with the limited Slack subscription which is used for the Community Slack.

Can you (Pulumi) adopt something else for better threaded style Questions and Answers? Github is in the process of rolling out its Discussions feature. Discussions use the same editor as Github Issues which means you can refer to issues, PRs and code snippets as one is used to on Github. Questions start as `Unanswered` but can be marked as `Answered`. And each discussion thread as a steady URL to link back to.

IMO, It would provide for a much better async handling and followup of questions.

To give you an idea, you can see the [Concourse](https://concourse-ci.org) project using this feature on their main repo: https://github.com/concourse/concourse/discussions

**Comment by nesl247** [comment]
I'd love to see GitHub Discussions as well. Slack is great, but as more people are using pulumi, it's become nearly useless for me.

**Comment by mattstratton** [comment]
Closing this issue since we have the good news that GH Discussions has been enabled! 

https://github.com/pulumi/pulumi/discussions
