### ISSUE TITLE
Publish Github Action in the GH Actions Marketplace

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#4660]
Hereby the request to package & publish as a true Github Action. This entails:

* Moving the [current code](https://github.com/pulumi/pulumi/tree/master/dist/actions) to a separate Git repository per [Github's advice](https://help.github.com/en/actions/building-actions/about-actions#choosing-a-location-for-your-action)
* Publishing the action following [the documentation](https://help.github.com/en/actions/building-actions/publishing-actions-in-github-marketplace).

The advantage is that the action can now be discovered in [the Marketplace](https://github.com/marketplace?type=actions&query=pulumi). Other Pulumi users published actions as a workaround, e.g. #4289 

Another benefit is that the action can be properly used with [`act`](https://github.com/nektos/act), a tool to test Github Workflows locally. Currently, the `uses: docker://pulumi/actions` notation is [not supported](https://github.com/nektos/act/issues/212).

**Comment by cobraz** [comment]
I can help with this, @leezen

**Comment by cobraz** [comment]
I can help with this, @leezen

**Comment by stack72** [comment]
This has been done! It's now available here - https://github.com/marketplace/actions/pulumi-cli-action
