### ISSUE TITLE
Add hint on how to circumvent refusal to delete protected resources.

### ISSUE THREAD

**Issue by gsuess** [pulumi/pulumi#4662]
It's how to know how to deal with the error message:

> refusing to delete protected resource

As printed here:

https://github.com/pulumi/pulumi/blob/7f27618e2d579cc7e0da82bc43c9808fc138c999/pkg/resource/deploy/step.go#L331

To circumvent this issue one needs to unprotected it with:

```
pulumi state unprotect <urn>
```

It would be great if the information how to unprotect the resource was included in the error message, because the command to unprotect it is not easy to find on the documentation, `pulumi --help` or even Google.

**Comment by valer-cara** [comment]
In the meantime you can responsibly edit the state file directly, setting `protect: false` where needed. :eyes:
