### ISSUE TITLE
GetSecret/RequireSecret APIs are (unnecessarily) weakly typed

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#4664]
The current `Get*Secret` APIs for config all return `Output` even though they are guaranteed to know what type of output they will generate.  They should be able to be made more strongly typed - making them easier to use - and without any source breaking change (for any code which previously run correctly).

**Comment by joeduffy** [comment]
Note, since I just struggled with this for a bit, the workaround is to cast the return values:

```go
s := config.GetSecret(ctx, "foo").(pulumi.StringOutput)
b := config.GetBool(ctx, "bar").(pulumi.BoolOutput)
// and so on ...
```

Clearly would be good to fix this so they return the strongly typed values directly.
