### ISSUE TITLE
Serializing 3rd party Javascript / Apollo Server on GCP

### ISSUE THREAD

**Issue by jonsherrard** [pulumi/pulumi#4666]
Hello all!

First of all, thank you for Pulumi! It's great!

Second of all, I apologise for the naivety you're about to encounter in this issue... I really am way out of my depth here.

I'm trying to run the basic "hello world" example of https://github.com/apollographql/apollo-server/tree/master/packages/apollo-server-cloud-functions.

This package is a wrapper around the popular `apollo-server` graphql API builder/server... thing.

The nub of this package, is a method called `createHandler` which will return a handler for the GCP-Fn to use.

As follows:

```js
// Construct a schema, using GraphQL schema language
const typeDefs = gql`
  type Query {
    hello: String
  }
`;

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    hello: () => "Hello world!",
  },
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
  playground: true,
  introspection: true,
});

const serverHandler = server.createHandler();


// Create GCP Fn
const graphApi = new gcp.cloudfunctions.HttpCallbackFunction(
  "graphApi",
  serverHandler
);

const graphInvoker = new gcp.cloudfunctions.FunctionIamMember("invoker", {
  project: graphApi.function.project,
  region: graphApi.function.region,
  cloudFunction: graphApi.function.name,
  role: "roles/cloudfunctions.invoker",
  member: "allUsers",
});

export const url = graphApi.httpsTriggerUrl;
```

Now this all looks good, until I run `pulumi up`, and at some point, `pulumi` will serialize my javascript (a pretty large amount presumably? including all the deps?), ready to upload to GCP.

At this point I get the error:

```sh
Diagnostics:
  pulumi:pulumi:Stack (grapql-api-gcp-fn):
    (node:83431) ExperimentalWarning: queueMicrotask() is experimental.
    (node:83431) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
 
    error: Error serializing function '<anonymous>': index.ts(24,82)
    
    function '<anonymous>': index.ts(24,82): captured
      'graphApiHandler', a function defined at
        function '<anonymous>': ApolloServer.js(60,15): which could not be serialized because
          arrow function captured 'this'. Assign 'this' to another name outside function and capture that.
    
    Function code:
      (req, res) => {
                  if (req.path && !['', '/', '/graphql'].includes(req.path)) {
                      res.status(404).end();
                      return;
                  }
```

Now there are a lot of references to`this` in this file: https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-cloud-functions/src/ApolloServer.ts

I've forked `apollo-server-cloud-functions` and tried to Assign/alias `this` to another name. But I cannot get things to work. 

I *think* this is an issue for `apollo-server-cloud-functions` to fix, but I'm just very lost as to where to look.

Any pointers very welcome. Apologies for the very poorly explained and understood issue!

All the best,

Jon x

**Comment by leezen** [comment]
I was able to get this to work by sticking the relevant graphql code into a callback factory:
```
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";
import { ApolloServer, gql } from "apollo-server-cloud-functions";

const factory = () => {
    // Construct a schema, using GraphQL schema language
    const typeDefs = gql`
        type Query {
            hello: String
        }
    `;

    // Provide resolver functions for your schema fields
    const resolvers = {
        Query: {
            hello: () => "Hello world!",
        },
    };

    const server = new ApolloServer({
        typeDefs,
        resolvers,
        playground: true,
        introspection: true,
    });
    return server.createHandler();
};

// Create GCP Fn
const graphApi = new gcp.cloudfunctions.HttpCallbackFunction(
    "graphApi",
    {
        callbackFactory: factory
    }
);

const graphInvoker = new gcp.cloudfunctions.FunctionIamMember("invoker", {
    cloudFunction: graphApi.function.name,
    role: "roles/cloudfunctions.invoker",
    member: "allUsers",
});

export const url = graphApi.httpsTriggerUrl;
```

**Comment by leezen** [comment]
The thing to note here is that by doing this, you're scoping a lot of the apollo-server stuff to within the context of the function itself. This is also what you want because this way the Apollo server is initialized as part of executing the function (rather than executing your Pulumi program).

**Comment by jonsherrard** [comment]
Lee! I am not worthy!

Thank you so much! I had this amorphous unseeing wander in this general area wrapping all sorts of things in IIFEs, and I even looked at the code for `callbackFactory`... alas. I am not quite there yet with the old' JS 😓  

A thousand thank yous!

Have a great day!

Jon

**Comment by leezen** [comment]
Glad to help and that you're hopefully unblocked. Don't hesitate to reach out for help on Community Slack!

**Comment by camjackson** [comment]
Thanks for the tips so far @leezen. Unfortunately I'm still facing this problem even with the factory approach. My code looks like:

```ts
// lambda.ts:
import { ApolloServer } from 'apollo-server-lambda';
import { typeDefs, resolvers } from './graphql';

export function createHandler() {
  return new ApolloServer({ typeDefs, resolvers }).createHandler();
}

// infra.ts:
import * as awsx from '@pulumi/awsx';
import { createHandler } from './lambda';

const endpoint = new awsx.apigateway.API('my-api', {
  routes: [
    {
      path: '/',
      method: 'ANY' as any,
      eventHandler: createHandler() as any,
    },
  ],
});

export const url = endpoint.url;
```

The error is:
```
    '(event, context, callback) => { if ( ...': ApolloServer.js(29,11): captured
      'asyncHandler', a function defined at
        function '<anonymous>': ApolloServer.js(87,32): which could not be serialized because
          arrow function captured 'this'. Assign 'this' to another name outside function and capture that.

    Function code:
      (event, context) => __awaiter(this, void 0, void 0, function* () {
                  const eventHeaders = new apollo_server_env_1.Headers(event.headers);
                  const requestCorsHeaders = new apollo_server_env_1.Headers(corsHeaders);
                  if (cors && cors.origin) {
                      const requestOrigin = eventHeaders.get('origin');
      ...
```

**Comment by camjackson** [comment]
Ahh never mind, I realised that I missed the important bit about passing my factory function as a factory, rather than just calling it myself!!! I needed this:

```ts
const eventHandler = new aws.lambda.CallbackFunction(
  'my-callback',
  {
    callbackFactory: createHandler as any, // Note: don't call the function here, just pass it!
  },
);
```

And then the API route looks like:
```ts
{
  path: '/',
  method: 'ANY',
  eventHandler,
}
```

**Comment by camjackson** [comment]
While I did get the function deployed successfully, I'm now hitting the same error as #6229 😢
