### ISSUE TITLE
Please consider adding dotnet sdk's Pulumi.Testing to nuget

### ISSUE THREAD

**Issue by lonegunmanb** [pulumi/pulumi#4672]
Hi Pulumi!

I'm exciting to write an article about exploring how to exercise tdd for IaC code with Pulumi dotnet sdk, and I've found that Pulumi dotnet sdk has a very powerful testing library: Pulumi.Testing. But I can't find this package in nuget so I have to link Pulumi and Pulumi.Testing project. Could you please consider adding Pulumi.Testing library to nuget? Many thanks!

**Comment by mikhailshilkov** [comment]
Hi @lonegunmanb 
`Pulumi.Testing` is a namespace inside the main `Pulumi` NuGet package, so no extra libraries are needed. You can find a fully runnable example at https://github.com/pulumi/examples/tree/master/testing-unit-cs

**Comment by lonegunmanb** [comment]
> Hi @lonegunmanb
> `Pulumi.Testing` is a namespace inside the main `Pulumi` NuGet package, so no extra libraries are needed. You can find a fully runnable example at https://github.com/pulumi/examples/tree/master/testing-unit-cs

I see, thanks @mikhailshilkov .
May I have a request for you? It seems that you've write a static class named Testing with RunAsync and GetValueAsync methods. These two methods are required in every cs pulumi project's unit tests so could we consider add this Testing class to Pulumi core library so we won't need to copy and paste these code everywhere?

Again, thanks for your sdk! I'm writing an article about TDD for IaC multi-cloud project in Chinese, introducing pulumi to China.

**Comment by lonegunmanb** [comment]
Dear @mikhailshilkov,
I've tried unit test and I've encountered a NullReferenceException, after digging into source code decompiled by Jetbrains Rider, I found the problem is in MockMonitor's RegisterResourceAsync method:

```csharp
public async Task<RegisterResourceResponse> RegisterResourceAsync(
      Resource resource,
      RegisterResourceRequest request)
    {
      // ISSUE: reference to a compiler-generated field
      int num1 = this.\u003C\u003E1__state;
      string id;
      object state;
      RegisterResourceResponse result1;
      try
      {
        if (request.Type == "pulumi:pulumi:Stack")
        {
          result1 = new RegisterResourceResponse()
          {
            Urn = MockMonitor.NewUrn(request.Parent, request.Type, request.Name)
          };
        }
```

Your latest code has fixed that problem by init Object for root Stack resource:
```csharp
public async Task<RegisterResourceResponse> RegisterResourceAsync(Resource resource, RegisterResourceRequest request)
        {
            lock (this.Resources)
            {
                this.Resources.Add(resource);
            }

            if (request.Type == Stack._rootPulumiStackTypeName)
            {
                return new RegisterResourceResponse
                {
                    Urn = NewUrn(request.Parent, request.Type, request.Name),
                    Object = new Struct(),
                };
            }
```

So I guess next release will fix this problem, am I right?

Cannot wait anymore to reveal the power of mighty TDD with Pulumi!!!

**Comment by lonegunmanb** [comment]
Btw, is there anyway to setup Config in unit test? I'm using Config to read input variables, it'll be really helpful to enable setup Config in unit test to simulate user input. Many thanks!

**Comment by mikhailshilkov** [comment]
Yes, the NRE bug will be fixed in the next version, I think you can pin to 2.1.1 where it used to work too.
The config in unit tests in tracked in https://github.com/pulumi/pulumi/issues/4472 and there is a workaround described there.

**Comment by lonegunmanb** [comment]
> Yes, the NRE bug will be fixed in the next version, I think you can pin to 2.1.1 where it used to work too.
> The config in unit tests in tracked in https://github.com/pulumi/pulumi/issues/4472 and there is a workaround described there.

Many thanks!

**Comment by mikhailshilkov** [comment]
There were a few tactical questions in this issue and it has been open for 2 years without further activity. It's not clear what it could track for the future, so I'll go ahead and close it.
