### ISSUE TITLE
Fatal error on update command

### ISSUE THREAD

**Issue by JabbarFagan** [pulumi/pulumi#4674]
I received a fatal error when executing 'pulumi update' to bootstrap a Linux VM on Azure:

(azure) (base) ➜  LFS205 pulumi update
\Previewing update (dev):
     Type                                                    Name                   Plan
 +   pulumi:pulumi:Stack                                     LFS205-dev             create
 +   ├─ azure:core:ResourceGroup                             resourceGroup-lfs205   create
 +   ├─ azure:network:VirtualNetwork                         vnet-lfs205            create
 +   ├─ azure:network:NetworkSecurityGroup                   NSG-lfs205             create
 +   ├─ azure:network:Subnet                                 subnet-lfs205          create
 +   ├─ azure:network:SubnetNetworkSecurityGroupAssociation  SubnetNSGassoc-lfs205  create
 +   ├─ azure:network:NetworkInterface                       interface-lfs205       create
 +   └─ azure:compute:LinuxVirtualMachine                    VM-lfs205-0            create

Resources:
    + 8 to create

### Do you want to perform this update? \  [Use arrows to move, enter to select, type to filter]
================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v2.2.1
Go Version:       go1.13.10
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: index out of range [-1]

goroutine 1 [running]:
runtime/debug.Stack(0xc0017342e8, 0x52fe560, 0xc000f50000)
	/Users/travis/.gimme/versions/go1.13.10.darwin.amd64/src/runtime/debug/stack.go:24 +0x9d
main.panicHandler()
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x6e
panic(0x52fe560, 0xc000f50000)
	/Users/travis/.gimme/versions/go1.13.10.darwin.amd64/src/runtime/panic.go:679 +0x1b2
gopkg.in/AlecAivazis/survey%2ev1.(*Select).OnChange(0xc0000ba5b0, 0x0, 0x0, 0x0, 0x0, 0x10, 0x63df300, 0x0, 0x0, 0x0, ...)
	/Users/travis/gopath/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/select.go:154 +0x6d5
gopkg.in/AlecAivazis/survey%2ev1.(*Select).Prompt(0xc0000ba5b0, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/select.go:234 +0x3cf
gopkg.in/AlecAivazis/survey%2ev1.Ask(0xc001734948, 0x1, 0x1, 0x50ace40, 0xc0011700c0, 0x0, 0x0, 0x0, 0x539dea0, 0x50e2301)
	/Users/travis/gopath/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/survey.go:148 +0x187
gopkg.in/AlecAivazis/survey%2ev1.AskOne(0x57a1fe0, 0xc0000ba5b0, 0x50ace40, 0xc0011700c0, 0x0, 0x0, 0x0, 0x0, 0x42, 0x0)
	/Users/travis/gopath/pkg/mod/gopkg.in/!alec!aivazis/survey.v1@v1.8.8/survey.go:94 +0xcd
github.com/pulumi/pulumi/pkg/v2/backend.confirmBeforeUpdating(0x53f4ee7, 0x6, 0x57ca880, 0xc0007f9300, 0xc000091800, 0x11, 0x20, 0x63df300, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/apply.go:168 +0x439
github.com/pulumi/pulumi/pkg/v2/backend.PreviewThenPrompt(0x57ab560, 0xc0000d2008, 0x53f4ee7, 0x6, 0x57ca880, 0xc0007f9300, 0xc0007f9380, 0xc00080de90, 0x23, 0xc000f55de0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/apply.go:127 +0x25a
github.com/pulumi/pulumi/pkg/v2/backend.PreviewThenPromptThenExecute(0x57ab560, 0xc0000d2008, 0x53f4ee7, 0x6, 0x57ca880, 0xc0007f9300, 0xc0007f9380, 0xc00080de90, 0x23, 0xc000f55de0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/apply.go:199 +0x1ac
github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudBackend).Update(0xc0004baed0, 0x57ab560, 0xc0000d2008, 0x57ca880, 0xc0007f9300, 0xc0007f9380, 0xc00080de90, 0x23, 0xc000f55de0, 0x63df300, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/backend.go:812 +0xe6
github.com/pulumi/pulumi/pkg/v2/backend.UpdateStack(0x57ab560, 0xc0000d2008, 0x57ca880, 0xc0007f9300, 0xc0007f9380, 0xc00080de90, 0x23, 0xc000f55de0, 0x63df300, 0x0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/stack.go:82 +0xc4
github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudStack).Update(0xc0007f9300, 0x57ab560, 0xc0000d2008, 0xc0007f9380, 0xc00080de90, 0x23, 0xc000f55de0, 0x63df300, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/httpstate/stack.go:148 +0x96
main.newUpCmd.func1(0x63df300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, 0x63df300, 0x0, ...)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/up.go:133 +0xb0e
main.newUpCmd.func3(0xc0001f5340, 0x63df300, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/up.go:372 +0x4e1
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc0001f5340, 0x63df300, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc0001f5340, 0x63df300, 0x0, 0x0, 0xc0001f5340, 0x63df300)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001f4dc0, 0x0, 0x0, 0xc0002b7f20)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/travis/gopath/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/travis/gopath/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x63

(azure) (base) ➜  LFS205

**Comment by JabbarFagan** [comment]
I ran 'pulumi up' 3 hours later w/o making any changes and... it worked. My VM was deployed without errors or warnings.

**Comment by JabbarFagan** [comment]
Fatal error occurred at around 11:45 EST today.  Success (next attempt) occurred at around 14:45.

**Comment by stack72** [comment]
Hi @JabbarFagan 

I apologise for taking so long to get back to you on this issue! We actually shipped a fix for this in Pulumi v2.5.0 and didn't realise it would have been linked to this fix

I am sorry for the late response, we will ensure we get better in this area

Paul
