### ISSUE TITLE
C# RequireObject and GetObject are not working

### ISSUE THREAD

**Issue by efleming18** [pulumi/pulumi#4684]
I am trying to follow [this example](https://www.pulumi.com/docs/intro/concepts/config/#structured-configuration) to retrieve a list of objects from a config file to use in the Stack code. If I copy/paste this exact example from this doc in to my project, `RequireObject` and `GetObject` both return null.

Additionally, I tried to create my own object to deserialize the values in to, but this also did not work.

Is there any know issues on this not working, or any example that can be provided of it working?

**Comment by leezen** [comment]
I am not able to reproduce this. I copied and pasted the example and received back:

```
Diagnostics:
  pulumi:pulumi:Stack (scratch-pulumi-dotnet-dev):
    Active: True
```

as expected.

Could you please check your `Pulumi.<stack>.yaml` to see how the config values are set there?

**Comment by efleming18** [comment]
I promise when I tried this yesterday, I was not able to get it to work. Now, it seems to be working! I will close this issue. Thank you.
