### ISSUE TITLE
[Ubuntu] pulumi CLI results in error: lstat /home/user/.gvfs: permission denied for zshrc

### ISSUE THREAD

**Issue by aymanapatel** [pulumi/pulumi#4696]
I am trying to run Pulumi in Ubuntu using `.zshrc`
I am able to install Pulumi CLI. But when I am running `pulumi up`, it takes me to Pulumi login page, which after succesful log results in `lstat /home/user/.gvfs: permission denied` error.

`pulumi version` :  v2.2.1

**Comment by leezen** [comment]
Does the CLI have permission to write to whatever it's trying to write to? That path isn't pulumi specific, but I'm guessing it's trying to write to within your home directory and doesn't have permission to do so for whatever reason?

**Comment by davsm** [comment]
I get the following error. I am using bash from WSL Ubuntu

error: lstat /mnt/c/hiberfil.sys: permission denied

pulumi version v2.6.1
