### ISSUE TITLE
Start linting all TypeScript code with ESLint

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#4698]
[TSLint](https://github.com/palantir/tslint) that we currently use in several places is deprecated in favor of ESLint.

I suggest using ESLint consistently:
- [x] Replace TSLint with ESLint in pulumi/pulumi (https://github.com/pulumi/pulumi/pull/7719)
- [ ] Replace TSLint with ESLint in pulumi/examples
- [ ] Introduce ESLint in all provider repositories starting with providers with any hand-written mixins

**Comment by stack72** [comment]
Kinda tracked here - https://github.com/pulumi/examples/issues/520

**Comment by horacehylee** [comment]
Hi, may I volunteer to help with this issue?

**Comment by mikhailshilkov** [comment]
@horacehylee Definitely! Thank you!

**Comment by horacehylee** [comment]
@mikhailshilkov I have raised a PR for migrating to ESlint, could you please take a look?
