### ISSUE TITLE
DscConfiguration Error

### ISSUE THREAD

**Issue by maverick126** [pulumi/pulumi#4700]
I am trying to run the following DscConfiguration

```
dsc_configuration = azure.automation.DscConfiguration(
    "IISDscConfig",
    resource_group_name=resource_group_name,
    automation_account_name=auto_account_name,
    location=location,
    content_embedded="""
Configuration IISDscConfig {
    Import-DscResource -ModuleName 'xPSDesiredStateConfiguration'
    Import-DscResource -ModuleName 'xWebAdministration'

    Node localhost {
        WindowsFeature IIS
        {
            Ensure = 'Present'
            Name = 'Web-Server'
        }
    }
}
"""
)
```

Getting the error:

```
> Diagnostics:
  pulumi:pulumi:Stack (pulumi_automation-dev):
    error: update failed

  azure:automation:DscConfiguration (IISDscConfig):
    error: automation.DscConfigurationClient#CreateOrUpdate: Failure responding
to request: 
StatusCode=400 -- Original Error: autorest/azure: Service returned an error. 
Status=400 Code="BadRequest" 
Message="The configuration name in the script must match the configuration name.
```

The script and configuration name are both with the name IISDscConfig

**Comment by leezen** [comment]
There's an additional `name` parameter that this resource takes: `DscConfiguration(resource_name, opts=None, automation_account_name=None, content_embedded=None, description=None, location=None, log_verbose=None, name=None, resource_group_name=None, tags=None, __props__=None)`

Without explicitly passing it in, you're using the [autonaming](https://www.pulumi.com/docs/intro/concepts/programming-model/#autonaming) in Pulumi. Can you please try explicitly setting the name and seeing if that works?

**Comment by stack72** [comment]
Hi @maverick126 

We've not heard back on this issue in a long time. I'm going to close it out for now but if you still have problems then please do let us know and we can reopen this

Paul
