### ISSUE TITLE
Conditionally IgnoreChanges

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi#4715]
Sometimes I set a min number of nodes in a node pool that I want Pulumi to initially create. Outside Pulumi I have processes that can increase the amount of the node pool so I do not want to decrease it. Then if for some reason it goes below that initial amount aka min amount I would like Pulumi to increase it again. I am sure there are many other use cases for this such as Pod replicas in Kubernetes.

**Comment by leezen** [comment]
How do you envision this working? Would it be a callback for `ignoreChanges`? So you could write something like: `new Resource(..., { ignoreChangesCallback: cb });` where cb returns the set of arguments you may or may not want to ignore?

**Comment by mitchellmaler** [comment]
Yea something like that. It would need to be on a per property basis. So other properties can change where this one or others you can run a callback or anonymous function to check the state of the resource and returrn a bool if that field should be changed or not.

**Comment by lukehoban** [comment]
> It would need to be on a per property basis. So other properties can change where this one or others you can run a callback or anonymous function to check the state of the resource and returrn a bool if that field should be changed or not.

It seems you should be able to express that today by conditionally setting the elements of an array somewhere centrally and then passing that into resources. I can’t come up with a case where a callback would let you express something new. 

From an ergonomics perspective though, you may want to centralize the process of determine what properties on what resources to ignore. That should be possible with `transformations` and in particular a global stack transformation, depending on the use case. 

If those don’t sound like they would work for your case, would be great to see a sketch of what you are trying to do.

**Comment by mikhailshilkov** [comment]
Since the issue has been open for 2 years without comments or upvotes, and there is a workaround suggested, I will go ahead and close it. Feel free to open a new issue that would show a scenario that is not possible today.
