### ISSUE TITLE
could not validate provider configuration: 2 errors occurred:

### ISSUE THREAD

**Issue by superjose** [pulumi/pulumi#4718]
Hi 😊. I've been enjoying Pulumi so far. I've loved how easy it's been just to follow the configuration, and I managed to get my stuff up and running with little trouble. 

Now, I've quite a roadblock. I was trying to create a SSM Parameter's store in my Pulumi config: 

```javascript

const config = new pulumi.Config();
const auth0ClientSecret = config.requireSecret("auth0-client_secret");
const auth0ClientId = config.requireSecret("auth0-client_id");

const auth0ClientSecretSSM = new aws.ssm.Parameter(
  "auth0-client_secret",
  {
    name: "auth0_client_secret_" + env,
    type: "SecureString",
    value: auth0ClientSecret,
  }
);

const auth0ClientIdSecretSSM = new aws.ssm.Parameter("auth0-client_id", {
  type: "SecureString",
  value: auth0ClientId,
});
```

I tried doing this. I set up the secrets to the config accordingly:

`pulumi config set --secret auth0-client_secret thesecret`
`pulumi config set --secret auth0-client_id theId`

After that, and running `pulumi up`, I got hit with:

```yaml
Diagnostics:
  aws:iam:Policy (schon-SQS-send-messages-dev):
    error: could not validate provider configuration: 2 errors occurred:
        * : invalid or unknown key: auth0_client_id
        * : invalid or unknown key: auth0_client_secret
```

And I haven't been able to get rid of that error ever since! I've been hitting my head for over 40 minutes by turning off/on pieces of code, and the only thing that it seems to work is if I start in blank state, in which Pulumi asks to delete all of my resources (something, of course, that I don't want to do). 

I've tried:
-  `pulumi config rm auth0_client_secret`
-  `pulumi config rm auth0-client_secret`

I went into the `User:/.pulumi` folder in my Windows machine to see where could it be lying. No answer. 

It seems that the problem lies in how Pulumi tends to see the hyphen `-` . 

Is there a way to reset Pulumi's config? I even tried looking at the Yaml files and re-creating the keys and deleting them again to no avail. I can't seem to find anything online either. 

Just this:
https://www.pulumi.com/docs/intro/concepts/config/#changing-the-secrets-provider-for-a-stack

Any ideas? 

Thank you!!

**Comment by superjose** [comment]
Oh oh. I'm so screwed right now. I tried deleting the entire production stack, which I did (as the app isn't completely live yet...). But the problem persisted! 

Seriously, where does Pulumi hide all that information?! Is it on the server? I think it does store it on the server... Is there a way to delete this?

![image](https://user-images.githubusercontent.com/8230270/83169310-da12b900-a0e0-11ea-8569-c3a9f5e9936f.png)

**Comment by superjose** [comment]
If it helps, I'm using Windows 10 May 2020 update. Running Pulumi 2.3.0 and the AWS 2.6.2 plugin

**Comment by lukehoban** [comment]
Ahh - I *think* the problem might be that your project is named `aws`.  That is - your `Pulumi.yaml` contains `name: aws`.  

That appears to be causing the config for your project to be interpreted and used as config for the `aws` provider.  For example - treated the same as if you set `aws:region` as a config variable.  

This is something we will want to fix or warn on in the Pulumi config system.

To workaround this - you would likely need to change the project name to something that does not conflict.  You can use `pulumi stack rename` to help with this (as the state file will need to be adjusted as well as updating `Pulumi.yaml`).  https://www.pulumi.com/docs/reference/cli/pulumi_stack_rename/

**Comment by superjose** [comment]
OMG!!! That solved the issue!!! Thank you so much Luke!!!!

Thaaaaaank youuuuuuuuuuuuu!!!!

**Comment by superjose** [comment]
Again 😊! Thank you so much. Sorry for the rant. I got a little bit overwhelmed back there. I need to drill in my head to avoid using names that are similar to prevent this type of issues. 

I apologize for writing it like that. Anyways, Kudos for the support team for the great and prompt support.

**Comment by lukehoban** [comment]
No worries - thanks for reporting this!  I've opened https://github.com/pulumi/pulumi/issues/4720 to track the core issue here.  I'll close this one out as a dupe.  Glad to hear you've been able to work around this in the meantime.
