### ISSUE TITLE
Bad experience when project name conflicts with a provider (e.g. `aws`)

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#4720]
If the name of a project is the same as one of the providers being used, any config set on the project is interpreted as config for the provider - and will lead to errors.  This effectively makes it impossible to use config.

We will need to find a way to either warn on this - or avoid this problem altogether by making un-namespaced config truly "different" (always tied to project) than namespaced config.

From https://github.com/pulumi/pulumi/issues/4718:

> I tried doing this. I set up the secrets to the config accordingly:
> 
> ```
> pulumi config set --secret auth0-client_secret thesecret
> pulumi config set --secret auth0-client_id theId
> ```
> 
> After that, and running pulumi up, I got hit with:
> 
> ```
> Diagnostics:
>   aws:iam:Policy (schon-SQS-send-messages-dev):
>     error: could not validate provider configuration: 2 errors occurred:
>         * : invalid or unknown key: auth0_client_id
>         * : invalid or unknown key: auth0_client_secret
> ```

**Comment by nesl247** [comment]
This is the same issue as #3546 internally I think. The route to getting there is different.

**Comment by lukehoban** [comment]
> This is a duplicate of #3546

Ahh - yes - you are absolutely right.  Closing this one out to track there instead.
