### ISSUE TITLE
Fish autocompletions not automatically installed with homebrew

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi#4721]
The fish shell autocompletions should be auto installed when installing with homebrew.

**Comment by stack72** [comment]
@nesl247 this has now been released to the homebrew formula - https://github.com/Homebrew/homebrew-core/blob/master/Formula/pulumi.rb

**Comment by nesl247** [comment]
Those don't actually work. They are never loaded. I'll comment there.

**Comment by jaxxstorm** [comment]
@nesl247 thanks for the pointer, I'm not super familiar with the fish shell personally. I see a fix has been opened for this, so I'll wait for that to be merged. Thanks for your patience.
