### ISSUE TITLE
Best practice CI setup for infrastructure + service deployment

### ISSUE THREAD

**Issue by mklueh** [pulumi/pulumi#4728]
Hi there,

let´s say a project consists of the following parts:

Core Infrastructure
- API Gateway
- Cognito
- SQS
- S3
- EKS

Service Infrastructure
- Services
- Lambdas

What I would do now is to set up a CI pipeline that first builds my services and secondly does the infrastructure and service deployment. 
However, my gut feeling tells me that I should separate the core infrastructure from my service deployment. I want to prevent that anything goes wrong with the core like shutting down Cognito/S3 and deleting any user data with it, so nothing that goes wrong with the services should lead to a rollback of the underlying infrastructure.

_Is using one stack for both layers bad?_

However, separating those into two pulumi stacks would cause not having the credentials of the core infrastructure that I need to provide to the services in the second stack and I´d probably configure those manually in Gitlab / GitHub.

_Should the deployment be always fully automated or are manual steps "okay"?_

What is your prefered way to setup your CI pipeline?

**Comment by danfhernandez** [comment]
> Is using one stack for both layers bad?

Having a single project / stack for all resources, include core infrastructure, is a great place to start, especially if there are true dependencies between the resources.  

That said, as complexity increases it can certainly make sense to consider breaking out your application into multiple projects / stacks. It sounds like you may be at that juncture but there are some gotchas to keep in mind. See: https://www.pulumi.com/docs/intro/concepts/organizing-stacks-projects/. 

> separating those into two pulumi stacks would cause not having the credentials of the core infrastructure that I need to provide to the services in the second stack

You can actually use a combination of [stack outputs](https://www.pulumi.com/docs/intro/concepts/programming-model/#stack-outputs) and [stack references ](https://www.pulumi.com/docs/intro/concepts/programming-model/#stack-references) to pass along necessary information for other stacks. 

Note, when breaking out your application into multiple stacks, you need to make sure to do so carefully. A common place you can stub your toe is making breaking changes in a stack, like your core infra stack, without cascading the changes down to stacks that depend on it, your services stack in this scenario. 

> Should the deployment be always fully automated or are manual steps "okay"?

This is really up to you! That said, I think with the use of stack outputs / references above, this won't be a concern. 

> What is your preferred way to setup your CI pipeline?

In your CI setup, Its generally a good practice to setup stack dependent project pipelines to depend on the pipeline of the project it's dependent on. This is to ensure upstream changes make it down stream stacks. 

This increased complexity can be a reason some will decide against breaking out their stack.

**Comment by mklueh** [comment]
Hi @danfhernandez ,

thanks for your extensive answer, it really helps me alot.

I wouldn´t call my project that complex, so I´m not sure if splitting the stack is worth the hassle then and I´ll stick with a single stack.
