### ISSUE TITLE
Pulumi can't access VPN URLs

### ISSUE THREAD

**Issue by igstan** [pulumi/pulumi#4739]
I'm running macOS and experimenting with the GitLab provider, trying to set up a group in a private GitLab instance that sits behind a VPN. The TypeScript code is simple:

```ts
import * as gitlab from "@pulumi/gitlab";
const gitlabGroup = new gitlab.Group('my-group);
```

I've also properly set up my `gitlab:token` and `gitlab:base_url` config values. However, when I issue a `pulumi preview` command I get (example.com is the redacted part of my internal host):

```
error: Get "https://gitlab.example.com/api/v4/user": dial tcp: lookup gitlab.example.com on 8.8.8.8:53: no such host
```

After some research it seems this is an issue with the HTTP client library in Go itself. The [Terraform project has a similar open issue](https://github.com/hashicorp/terraform/issues/3536), which further links to the main [Go issue](https://github.com/golang/go/issues/12524).

On the other hand, it seems that the Go problem has been fixed in https://github.com/golang/go/commit/f6b42a53e5ac1f1c3f3b1c9ed2407e68e0b637a0, but my poor knowledge of Go prevents me from understanding whether that fix requires an explicit compile-time flag or not.

**Comment by leezen** [comment]
Thanks for linking the relevant issues and spending some time digging into it. Reading through the issue, it looks there a number of options we could take and should investigate.

**Comment by leezen** [comment]
It should be noted that this will apply to all the binaries that might make DNS queries, including provider binaries.

**Comment by flubbes** [comment]
Hey. I got the same problem. 

## My findings
* It occurs when using a VPN which is (correctly) configured to NOT catch all DNS requests.

## Possible workaround

### macOS
1. Find your network adapter `sudo networksetup -listnetworkserviceorder`
2. Find dns server for VPN `scutil --dns`
3. `sudo networksetup -setdnsservers "${Your network adapter}" ${vpn dns ip}`

### Other OS

Set your primary DNS server temporarily to "VPN DNS only" 

---

**Don't forget to revert this setting after you are done. E.g. `sudo networksetup -setdnsservers "USB 10/100/1000 LAN" 1.1.1.1`**

## Links

Probably related: https://github.com/hashicorp/terraform/issues/3536

**Comment by justinvp** [comment]
I believe this is now fixed. We're building both the CLI and pulumi-gitlab with Go 1.20+ which addresses this issue for macOS.
