### ISSUE TITLE
Allow customizing CLI colors

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#474]
I use a light theme for my terminal, so it would be nice if I could use custom colors.

**Comment by joeduffy** [comment]
Note that this has gotten much better thanks to work @CyrusNajmabadi has done, but custom CLI color schemes would probably be a "nice to have" someday.

**Comment by lukehoban** [comment]
We haven't actually heard this request again in the last 2+ years, so I'm going to close this one out.  We have done a fair bit of incremental improvement generally - which may be why this doesn't come up more often.
