### ISSUE TITLE
[Go Program Gen] convert unused variables to `_`

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#4771]
Go is unique among our supported languages in erroring on unused variables. We need a pre-generation lowering step that traverses all nodes and collects the roots of all scope traversals. When we generate a variable or generate a node, we should check this list of roots first to know if we have a variable that's used later on. 

For example: https://github.com/pulumi/pulumi/pull/4749/files#diff-ae83e82bc7feedf66a792c8a49a12105R149

**Comment by lblackstone** [comment]
I think you've already finished this work, but note that you could also run the generated code through [goimports](https://github.com/golang/tools/blob/master/imports/forward.go) to automatically remove unused imports. 

Similar to this:
https://github.com/pulumi/pulumi/blob/fa69a31c97347d1bced2ad5a6de2f2b30a723af4/pkg/codegen/go/gen.go#L1266-L1270
