### ISSUE TITLE
Could not create stack 'dev'

### ISSUE THREAD

**Issue by Brotosterone** [pulumi/pulumi#4788]
Taking a crack at Pulumi for the first time. Using the s3 as my backend for states. I have the bucket set up in AWS. I have my creds configured in .aws file.  Any ideas?

**1. login:**
`pulumi login s3://pulumi-state-bucket`
**2. run:** 
`pulumi new aws-csharp`
**3. Enter info**  
`project name: (test)
project description: (A minimal AWS C# Pulumi program)
Created project 'test'
stack name: (dev)
Enter your passphrase to protect config/secrets:
Re-enter your passphrase to confirm:`

**Then get the following error**
`Sorry, could not create stack 'dev': could not create stack: An IO error occurred while writing the new snapshot file: blob (key ".pulumi/stacks/dev.json") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors`

**Comment by Brotosterone** [comment]
Looks to be a simialar issue here https://github.com/pulumi/pulumi/issues/2714. However I don't have a .pulumi/stacks that exists

**Comment by leezen** [comment]
This reads like the credentials are misconfigured -- could you please verify that you're able to run `aws sts get-caller-identity` for example?

**Comment by Brotosterone** [comment]
Yep, that runs fine.

**Comment by leezen** [comment]
Could you please run with verbose logging and provide the logs in this issue? 
https://www.pulumi.com/docs/troubleshooting/#verbose-logging

**Comment by Brotosterone** [comment]
Apologies for the delay:
Here is the log :
I0611 16:23:23.366331   24852 ignore.go:44] Explicitly ignoring and discarding error: no git repository found from C:\projectname\Pulumi.yaml
I0611 16:23:23.506883   24852 ignore.go:44] Explicitly ignoring and discarding error: copying .pulumi\stacks\dev.json to .pulumi\stacks\dev.json.bak: blob (key ".pulumi/stacks/dev.json -> .pulumi/stacks/dev.json.bak") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
I0611 16:23:23.824929   24852 state.go:207] Error while writing snapshot to: .pulumi\stacks\dev.json (attempt=0, error=blob (key ".pulumi/stacks/dev.json") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors)
I0611 16:23:25.173509   24852 state.go:207] Error while writing snapshot to: .pulumi\stacks\dev.json (attempt=1, error=blob (key ".pulumi/stacks/dev.json") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors)
I0611 16:23:26.786487   24852 state.go:207] Error while writing snapshot to: .pulumi\stacks\dev.json (attempt=2, error=blob (key ".pulumi/stacks/dev.json") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors)
I0611 16:23:28.640052   24852 state.go:207] Error while writing snapshot to: .pulumi\stacks\dev.json (attempt=3, error=blob (key ".pulumi/stacks/dev.json") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors)
I0611 16:23:30.863292   24852 state.go:207] Error while writing snapshot to: .pulumi\stacks\dev.json (attempt=4, error=blob (key ".pulumi/stacks/dev.json") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors)
I0611 16:23:33.483740   24852 state.go:207] Error while writing snapshot to: .pulumi\stacks\dev.json (attempt=5, error=blob (key ".pulumi/stacks/dev.json") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors)
I0611 16:23:36.613409   24852 state.go:207] Error while writing snapshot to: .pulumi\stacks\dev.json (attempt=6, error=blob (key ".pulumi/stacks/dev.json") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors)
I0611 16:23:40.322110   24852 state.go:207] Error while writing snapshot to: .pulumi\stacks\dev.json (attempt=7, error=blob (key ".pulumi/stacks/dev.json") (code=Unknown): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors)

**Comment by leezen** [comment]
Thanks -- that unfortunately doesn't shed much light. One other thing I can think of is that `aws-sdk-go` doesn't actually handle SSO credentials correctly. You don't happen to be using those? Or potentially require something in `.aws/config`? The AWS Go SDK has slightly different behavior from that of the other AWS SDKs, so I'm wondering if some configuration difference might exist that's letting the AWS CLI succeed, but the code here fail. See also https://docs.aws.amazon.com/sdk-for-go/api/aws/session/

**Comment by itmustbejj** [comment]
@leezen Can you expand upon the aws-sdk-go difference for SSO? I'm getting this error while trying to use the awscli v2 with SSO. Is there an existing issue against this?

**Comment by leezen** [comment]
aws-sdk-go doesn't handle using credentials obtained via the CLI with `aws sso`: https://github.com/aws/aws-sdk-go/issues/3186

**Comment by leezen** [comment]
Closing this out in favor of https://github.com/pulumi/pulumi/issues/5072

**Comment by HarryCaveMan** [comment]
I am experiencing this issue not with SSO but with the use of `AWS_PROFILE` environment variable in conjunction with a SAML profile in `.aws/credentials`. As stated, the login succeeds, but the `new` command fails in exactly the same way. This is not just an issie with `aws sso`
