### ISSUE TITLE
Python codegen: Use classes when generating Python programs

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#4792]
When generating Python programs (e.g. tf2pulumi), the emitted programs should use the new class-based approach for nested inputs/outputs, rather than dictionaries.

Part of https://github.com/pulumi/pulumi/issues/3771.

**Comment by justinvp** [comment]
Here are some existing examples and how they should look after these changes:

## Using versioning

https://www.pulumi.com/docs/reference/pkg/aws/s3/bucket/#using-versioning

### Old

```python
import pulumi
import pulumi_aws as aws

bucket = aws.s3.Bucket("bucket",
    acl="private",
    versioning={
        "enabled": True,
    })
```

### New

```python
import pulumi
import pulumi_aws as aws

bucket = aws.s3.Bucket("bucket",
    acl="private",
    versioning=aws.s3.BucketVersioningArgs(
        enabled=True
    ))
```

## Enable Logging

https://www.pulumi.com/docs/reference/pkg/aws/s3/bucket/#enable-logging

### Old

```python
import pulumi
import pulumi_aws as aws

log_bucket = aws.s3.Bucket("logBucket", acl="log-delivery-write")
bucket = aws.s3.Bucket("bucket",
    acl="private",
    loggings=[{
        "targetBucket": log_bucket.id,
        "targetPrefix": "log/",
    }])
```

### New

```python
import pulumi
import pulumi_aws as aws

log_bucket = aws.s3.Bucket("logBucket", acl="log-delivery-write")
bucket = aws.s3.Bucket("bucket",
    acl="private",
    loggings=[aws.s3.BucketLoggingArgs(
        target_bucket=log_bucket.id,
        target_prefix="log/",
    )])
```

The main things to keep in mind:
- `*schema.ObjectType` should no longer be treated as dictionaries.
- For inputs, the name of the ObjectType has an `Args` suffix and is currently in the same module as the the resource/function (e.g. both the `Bucket` resource and the `BucketLoggingArgs` input type are in `pulumi_aws.s3`).
- For outputs, the name of the ObjectType doesn't have a special prefix/suffix and these currently get outputted in the outputs submodule (e.g. the `Bucket` resource is in `pulumi_aws.s3` and the `BucketLogging` output type is in `pulumi_aws.s3.outputs`). *I'm not sure if this detail will ever show up in generated programs, since typically these are just "dotting" into the outputs of a resource (e.g. `my_bucket.loggings[0].target_prefix`).
- The names of the input arguments and output fields of input/output types are always snake_case.
- The new generated example code should look more like the C# generated examples, so the codegen code for C# may be a useful reference.

**Comment by komalali** [comment]
@justinvp does this also apply to function calls?

For example: https://www.pulumi.com/docs/reference/pkg/aws/getami/

### Old

```python
import pulumi
import pulumi_aws as aws

example = aws.get_ami(executable_users=["self"],
    filters=[
        {
            "name": "name",
            "values": ["myami-*"],
        },
        {
            "name": "root-device-type",
            "values": ["ebs"],
        },
        {
            "name": "virtualization-type",
            "values": ["hvm"],
        },
    ],
    most_recent=True,
    name_regex="^myami-\\d{3}",
    owners=["self"])
```

### New

```python
import pulumi
import pulumi_aws as aws

example = aws.get_ami(executable_users=["self"],
    filters=[
		aws.GetAmiFilterArgs(
			name="name",
            values=["myami-*"],
        ),
		aws.GetAmiFilterArgs(
			name="root-device-type",
            values=["ebs"],
        ),
		aws.GetAmiFilterArgs(
			name="virtualization-type",
            values=["hvm"],
		),
    ],
    most_recent=True,
    name_regex="^myami-\\d{3}",
    owners=["self"])
```

**Comment by justinvp** [comment]
> does this also apply to function calls?

@komalali Yep!
