### ISSUE TITLE
`pulumi stack ls` with filestate backend silently skips stacks which use different passphrases 

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#4798]
We've had a couple reports that running `pulumi stack ls` will list some, but not all, of the stacks visible to a user.  It appears this can happen when some of the stacks share a passphrase, but others do not.  

Turning on verbose logs in such cases shows:

```
I0521 13:18:52.537300   56993 backend.go:732] error reading stack: mstr-fs-8423bc3a598d-35 (decrypting secret value: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase) skipping
```

We should:
1. Surface the error instead of silently leaving the stacks out of the list.
1. Ideally not require the passphrase to have a stack be listed in `pulumi stack ls`

**Comment by jonathan-willis** [comment]
The simple way to reproduce this would be to create a stack. Then delete the salt in the Pulumi.stack.yaml file.

**Comment by Gerrit-K** [comment]
I've just noticed this for an `azblob` backend. I've simply `unset PULUMI_CONFIG_PASSPHRASE` and then ran `pulumi stack ls`. The result showed less stacks than before I unset the passphrase. In particular, it now _only_ showed stacks that had _no_ resources deployed (i.e. those who were destroyed, but not removed).

**Comment by jamie-owen** [comment]
I've been experiencing this too, I've narrowed it down to `pulumi stack ls` attempting to deserialize the latest deployment for each stack and failing on resources that make use of a configuration secret, this happens when `PULUMI_CONFIG_PASSPHRASE` is either not set at all or set to the passphrase of another stack.
