### ISSUE TITLE
Why aren't Go secret returns strongly typed?

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#4799]
All of the [`pulumi/pulumi/sdk/go/pulumi/config` secret functions](https://godoc.org/github.com/pulumi/pulumi/sdk/go/pulumi/config) return plain old `Output`s. Is there a reason they don't return `StringOutput`, `BoolOutput`, etc, as appropriate? The weak typing makes them slightly painful to work with.

**Comment by lukehoban** [comment]
Dupe of https://github.com/pulumi/pulumi/issues/4664.
