### ISSUE TITLE
Node.js - Propagate DynamicProvider changes to already provisioned resources

### ISSUE THREAD

**Issue by asmith60** [pulumi/pulumi#4805]
I have a resource that is provisioned via a DynamicProvider. I want to change the DynamicProvider class and have that change propagate to the resource that already exists in my pulumi stack.

As of right now it appears any resource I create via a DynamicProvider is "stuck" with whatever the provider definition was at the time of creation.

For example if I change the `update` method in the DynamicProvider class to print "foo" to the console on every update, then the next time I trigger an update on my resource (that already exists in my stack) I expect "foo" to be printed to the console.

Is this workflow supported? 
Do I need to do something special to make my resource realize that the underlying provider has changed?

**Comment by leezen** [comment]
Yes, the underlying provider should change. You should see a diff that looks like:

```
 ~   └─ pulumi-nodejs:dynamic:Resource  hello                 updated     [diff: ~__provider,value]
```

Which indicates that the provider itself for the resource is also changing.

If you have a repro where this doesn't work, it'd be great if you could please post it.

**Comment by asmith60** [comment]
I believe I have narrowed the issue down to changes being ignored only in the `delete` method of a DynamicProvider.

Example repro tested on pulumi 2.4.0:

1. Initial bootstrap of project/stack - everything works as expected - [Link to commit](https://github.com/asmith60/pulumi-issue-4805/tree/3db0ab711e31b986a09c497987fddf3bad83c5e9)
```bash
pulumi up
Previewing update (pulumi-issue-4805.dev):
     Type                               Name                                     Plan       
     pulumi:pulumi:Stack                pulumi-issue-4805-pulumi-issue-4805.dev             
 +   └─ pulumi-nodejs:dynamic:Resource  Foo:my-resource                          create     
 
Resources:
    + 1 to create
    1 unchanged

Do you want to perform this update? yes
Updating (pulumi-issue-4805.dev):
     Type                               Name                                     Status      
     pulumi:pulumi:Stack                pulumi-issue-4805-pulumi-issue-4805.dev              
 +   └─ pulumi-nodejs:dynamic:Resource  Foo:my-resource                          created     
 
Resources:
    + 1 created
    1 unchanged
```

2. Changed the update method - also works as expected (note the added console output and "diff: ~__provider") - [Link to commit](https://github.com/asmith60/pulumi-issue-4805/tree/8ad086a26267853d1216f0ff4ba87db502ae88f8)
```bash
pulumi up
Previewing update (pulumi-issue-4805.dev):
     Type                               Name                                     Plan       Info
     pulumi:pulumi:Stack                pulumi-issue-4805-pulumi-issue-4805.dev             
 ~   └─ pulumi-nodejs:dynamic:Resource  Foo:my-resource-0                        update     [diff: ~__provider,baz]
 
Resources:
    ~ 1 to update
    1 unchanged

Do you want to perform this update? yes
Updating (pulumi-issue-4805.dev):
     Type                               Name                                     Status      Info
     pulumi:pulumi:Stack                pulumi-issue-4805-pulumi-issue-4805.dev              1 message
 ~   └─ pulumi-nodejs:dynamic:Resource  Foo:my-resource-0                        updated     [diff: ~__provider,baz]
 
Diagnostics:
  pulumi:pulumi:Stack (pulumi-issue-4805-pulumi-issue-4805.dev):
    PROVIDER UPDATED
 
Resources:
    ~ 1 updated
    1 unchanged
```

3. Changed the delete method - **does not** work as expected, no console output or "diff: ~__provider" - [Link to commit](https://github.com/asmith60/pulumi-issue-4805/tree/e8fcfe61ebd1364d94cd2390c776179553999d9c)
```bash
pulumi up
Previewing update (pulumi-issue-4805.dev):
     Type                               Name                                     Plan       
     pulumi:pulumi:Stack                pulumi-issue-4805-pulumi-issue-4805.dev             
 -   └─ pulumi-nodejs:dynamic:Resource  Foo:my-resource-0                        delete     
 
Resources:
    - 1 to delete
    1 unchanged

Do you want to perform this update? yes
Updating (pulumi-issue-4805.dev):
     Type                               Name                                     Status      
     pulumi:pulumi:Stack                pulumi-issue-4805-pulumi-issue-4805.dev              
 -   └─ pulumi-nodejs:dynamic:Resource  Foo:my-resource-0                        deleted     
 
Resources:
    - 1 deleted
    1 unchanged
```

**Comment by leezen** [comment]
This makes sense in that the delete will use what's in the state to delete the provider. This is because it's totally possible to remove all the dynamic provider source along with the resource itself and want to delete the resource, so there the serialized code is what gets executed. But, as you point out, the serialized code isn't updated. It should work though if you first update the delete method on the provider (while keeping the resource), then deleting the resource should use the updated provider source code.

**Comment by asmith60** [comment]
I believe I understand what you are saying. I went through these steps:

1. Update the delete method on the provider while keeping the existing resource
2. Run `pulumi up` (the output says everything is "unchanged", no "diff: ~__provider")
3. Comment out the resource
4  Run `pulumi up` again

The resource gets deleted, but I still don't see the changes (a log to the console in this example)

Shouldn't the plan for the resource have been "update" in step 2 (as opposed to "unchanged) because I changed the underlying provider?

**Comment by leezen** [comment]
Yes, I would've expected that in step 2 as well. I just tried this against a toy example and my resource did diff correctly after updating the delete function. I couldn't actually access your commit links, so I'm curious if there's something more going on in your configuration vs. my minimal attempt to repro.

**Comment by asmith60** [comment]
Sorry about that. I changed the repo to public access (I guess the default is private now).

Thanks for your help on this. Please let me know if you see anything wrong with my configuration

**Comment by asmith60** [comment]
@leezen do you have your minimal attempt at a repro available to look at? I would like to compare your configuration against mine if possible

**Comment by leezen** [comment]
It was something along these lines:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as crypto from "crypto";

const randomprovider: pulumi.dynamic.ResourceProvider = {
    async create(inputs) {
        return { id: crypto.randomBytes(16).toString('hex'), outs: {
            value: inputs.value
        }};
    },
    async update(id, olds, news) {
        console.log("Update");
        return {
            outs: {
                value: news.value
            }
        }
    },
    async delete(id) {
        console.log("Hello");
        console.log("More");
    },
}

class Random extends pulumi.dynamic.Resource {
    constructor(name: string, value: string, opts?: pulumi.CustomResourceOptions) {
        super(randomprovider, name, {
            value,
        }, opts);
    }
}

const test = new Random("hello", "test-value2");
```

And I was updating the code w/in my `delete` between steps as we discussed above
