### ISSUE TITLE
How to deal with secret updates correctly?

### ISSUE THREAD

**Issue by mklueh** [pulumi/pulumi#4806]
For local development purposes I´m creating a PostgreSQL database with Pulumi with randomly created credentials, then I´m storing them as a secret which I then use for my application.

```
  createPostgres(): Secret {
     const password = new RandomPassword("password", {
            length: 16,
            overrideSpecial: "_%@",
            special: true,
        });


        const user = new RandomPassword("user", {
            length: 16,
            overrideSpecial: "_%@",
            special: false,
        });

        const deployment = new Deployment(appName, {
            spec: {
                replicas: 1,
                selector: {matchLabels: appLabels},
                template: {
                    metadata: {labels: appLabels},
                    spec: {
                        containers: [{
                            name: appName,
                            image: "postgres:12.3-alpine",
                            ports: [{containerPort: 5432}],
                            volumeMounts: [
                                {
                                    mountPath: "/var/lib/postgresql/data",
                                    name: "data-volume"
                                }
                            ],
                            env: [
                                {
                                    name: "POSTGRES_USER",
                                    value: user.result
                                },
                                {
                                    name: "POSTGRES_PASSWORD",
                                    value: password.result
                                },
                                {
                                    name: "POSTGRES_DB",
                                    value: "postgres"
                                }
                            ]
                        }],
                        volumes: [{
                            name: "data-volume",
                            emptyDir: {
                                medium: "Memory",
                            }
                        }]
                    }
                }
            }
        });

        const postgresUrl = PostgresDatabase.createUrl("localhost", user, password, 5432, "postgres");

        return new Secret("postgres-secret", {
            stringData: {
                postgresUrl: postgresUrl,
                postgresUser: user.result,
                postgresDatabase: "postgres",
                postgresPassword: password.result
            }
        });

    }

    private static createUrl(host: string, username: RandomPassword, password: RandomPassword, port: number, database: String) {
        return "postgres://" + username.result + ":" + password.result + "." + host + ":" + port + "/" + database;
    }
```

As my url schema was wrong, I´ve corrected that and ran **pulumi up** again. It then refreshed the secret and the application, but not the database so the connection between both was broken afterwards.

As a solution I´ve first created the secret and the credentials from it for my Postgres Deployment as well as for my Application Deployment, however when having both in Kubernetes, I need the Postgres name from the reference to build my database url, which is why I can´t define the Secret before the Deployment.

Is there a better aproach?

**Comment by leezen** [comment]
I'm a bit confused why changing the URL scheme would break the database? I don't see any type of dependency of the database on the URL scheme.

My understanding of your dependency graph looks like this:

```
username <-
secret <- deployment (db) <- secret <- deployment (application)
```

And ultimately you have some application that consumes that secret. I'm a bit confused where the circularity exists or what prevents the above from happening?

**Comment by mklueh** [comment]
@leezen It doesn´t really break the database, but as the database resource is not connected to the Kubernetes Secret it won´t get noticed about the changed credentials and therefore would have still the old credentials, meanwhile the application has been upgraded with the newer ones.
So the connection cannot be established anymore.

In the example I´ve given there is no circularity, but as stated above it is flawed when it comes to updates of the secret.


> `username <- secret <- deployment (db) <- secret <- deployment (application)`
> And ultimately you have some application that consumes that secret. I'm a bit confused where the circularity exists or what prevents the above from happening?

I assumed that I´d need the instance of the database in order to get the right domain name that I then write into a secret and pass it to the application. If I´d create the secret before the database deployment I could not do that, which is where my thought about the circularity came from.

**Comment by leezen** [comment]
> as the database resource is not connected to the Kubernetes Secret it won't get noticed about the changed credentials and therefore would have still the old credentials, meanwhile the application has been upgraded with the newer ones.

Sorry, I don't quite follow here. In your example above, the kubernetes secret depends on `password.result` and the database also depends on that as well. So any update to `password` should result in updates to both the secret and the database deployment.

**Comment by lukehoban** [comment]
The explanation from @leezen above matches my own interpretation here.

Note that in Kubernetes, changes to a deployment do not force all existing pods to get redeployed, they only impact new pods. So you *might* want to use `replaceOnChanges` to force the deployment to be recreated if the spec or spec.template changes. This would allow you to accomplish what you want, in spite of default Deployment behaviour in Kubernetes.
