### ISSUE TITLE
Provide way to change the secrets provider for an existing stack.

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#481]
From @ellismg 

> Regarding changing passwords, we don’t have that but it’s a good idea.  Can you file a 0.9 bug? 
> For now, you’ll need to blow all your existing secrets away and manually remove the 
> EncryptionSalt property from the .yaml file and re add everything.

Obviously there is an easy workaround, but a nice fit-and-finish issue.

**Comment by joeduffy** [comment]
Assigning to @swgillespie as part of thinking through enterprise and pluggable encryption scenarios.

**Comment by joeduffy** [comment]
We have a design for key rotation and re-keying, which will unblock this work for M20 or M21.

**Comment by ellismg** [comment]
This now tracks a slightly larger work item, allowing the ability to change the secrets provider for an existing stack.  This means not only being able to change a property on the provider itself (i.e. the passphrase) but the type of provider itself (the service managed provider to passphrase or KMS or another provider)

**Comment by lukehoban** [comment]
This is likely dependent on https://github.com/pulumi/pulumi/issues/2918.  Once that is supported, this will be fairly easy to implement (as a shorthand for exporting the stack with unencrypted secrets, reencrypting them (and config), and importing the new stack (plus serializing the new config).
