### ISSUE TITLE
Github Actions: With GCP:  Configure Docker

### ISSUE THREAD

**Issue by jonsherrard** [pulumi/pulumi#4811]
Hi there,

I've run into an error where Docker is not authenticated to push to the GDP container registry:

In the Github Action entrypoint script, service accounts are enabled using `gcloud` CLI, but there is another step required to authenticate docker (required for pushing images), to the gcr.io

https://github.com/pulumi/pulumi/blob/master/dist/actions/entrypoint.sh#L88

Should https://cloud.google.com/sdk/gcloud/reference/auth/configure-docker the `configure docker` command also be run at this line?

**Comment by stack72** [comment]
Hi @jonsherrard 

Thanks for the report here - let me look into this and get back to you asap!

Paul

**Comment by stack72** [comment]
You were indeed correct @jonsherrard 

PR has been opened to fix this - added the --quiet attribute on the auth to ensure it doesn't flood the logs. We do this on our internal repos for that specific command

**Comment by jonsherrard** [comment]
Thank you very much @stack72 - I'll keep an eye on the PR
