### ISSUE TITLE
How to handle name when creating multiple dependent instances

### ISSUE THREAD

**Issue by farzadmf** [pulumi/pulumi#4819]
Hi,

I'm trying to create multiple Azure App Service Plans and Certificates.

To create the plans:
```typescript
const plans = [
  { location: 'eastus', size: 'S1', tier: 'Standard' },
  { location: 'westus', size: 'S1', tier: 'Standard' },
]
const appPlans: azure.appservice.Plan[] = [];
plans.forEach(plan => {
  appPlans.push(
    new azure.appservice.Plan(`plan-${plan.location)}`, {
      name: `plan-${plan.location}`,
      // ...
    }),
  );
});
```

Then, I was doing this to create the certificates:
```typescript
const planCerts: azure.appservice.Certificate[] = [];
appPlans.forEach(plan => {
  plan.name.apply(planName => {
    planCerts.push(
      new azure.appservice.Certificate(`cert-${plan.location}`, {
        name: `cert-${plan.location}`,
        // ...
      }),
    );
  });
});
```

But, I've also noticed this in the documentation, which I feel is telling me that this is not the proper way to do it:
![image](https://user-images.githubusercontent.com/5768792/84558231-43a8df00-acff-11ea-967c-9320e0abc0a0.png)
For that reason, I was wondering how I should do this. I can easily use `Output<T>` in my creation args (second argument to the `Certificate` constructor), but I also want the `name`s (first argument to the constructor) to correlate to each other. Is there any way to do that? Or am I totally in the wrong direction and I don't know what I'm doing??

**Comment by leezen** [comment]
As you found, it's not recommended to create resources within `apply`. You could refactor this to simply do:

```typescript
plans.forEach(plan => {
  new azure.appservice.Plan(`plan-${plan.location)}`, {
      name: `plan-${plan.location}`,
      // ...
  }),
  new azure.appservice.Certificate(`cert-${plan.location}`, {
      name: `cert-${plan.location}`,
      // ...
  }),
});
```

If you wanted to have two separate iterations for whatever reason, you shouldn't need to do this via apply because `Output` can be an `Input`:

```typescript
const planCerts: azure.appservice.Certificate[] = [];
appPlans.forEach((p, i) => {
    planCerts.push(
      new azure.appservice.Certificate(`cert-${i}`, {
        name: pulumi.interpolate`${cert}-p.name`,
        // ...
      }),
    );
});
```

Note that in the above, you won't be able to use the output within the resource name since we're not within an apply.

**Comment by farzadmf** [comment]
Thank you @leezen for your answer, so let's say I wanted to name my resources with something other than a "counter" (for example, `location`), is there any way to do that?

Also, I think I didn't choose the right example, but for example, when creating Azure App Service and App Service Slot, the slot needs the app service to be there beforehand, so they should be done in two separate loops (I think)

Because the issue with using a "counter" is that let's say initially I have 3 plans and my `cert`s will be named `cert-0`, `cert-1`, and `cert-2`, then if I remove the middle one, ideally only `cert-1` should be deleted, but if we're relying on the count of plans, then what would happen is that `cert-2` will be destroyed and re-created as `cert-1`

Any thoughts on that?

**Comment by leezen** [comment]
You can certainly use `location` -- that's the beauty of Pulumi, you're free to use the language in the way you want. I was only pointing out you couldn't use the `Output` from the resource. You can still of course use `location` from the structure you're passing in.

**Comment by farzadmf** [comment]
That's the thing actually. If I'm not mistaken, we have two `name`s we use when creating resources:
- The first argument we pass to the constructor of resources is the `name` that `pulumi` uses (I think to create the `urn` of the resource)
- The `name` field we pass to the creation args (e.g., in the case of Typescript and a Certificate, the `CertificateArgs` interface), which determines the name given to the resource in the cloud

I'm trying to find a way to somehow parameterize the *first* argument (the `name` used by `pulumi`). The reason I want to do that is the use case I explained above (if `pulumi` uses `cert-<number>`, then when we remove `cert-1`, it causes the `urn` to change and a resource being destroyed and replaced)

And please know that I LOVE `pulumi`, and all these questions are to better understand best practices etc. when using it

**Comment by leezen** [comment]
You can parameterize the first argument -- just not with outputs. So this works:

```typescript
const plans = [
  { location: 'eastus', size: 'S1', tier: 'Standard' },
  { location: 'westus', size: 'S1', tier: 'Standard' },
];

const appPlans: azure.appservice.Plan[] = [];
plans.forEach(plan => {
  appPlans.push(
    new azure.appservice.Plan(`plan-${plan.location)}`, {
      name: `plan-${plan.location}`,
      // ...
    }),
  );
});

const planCerts: azure.appservice.Certificate[] = [];
plans.forEach(plan => {
    planCerts.push(
      new azure.appservice.Certificate(`cert-${plan.location}`, {
        name: `cert-${plan.location}`,
        // ...
      }),
    );
  });
```

If you really need the output to be part of the resource name itself, then you'll have to create the resource within an `apply` (and live with the consequences of `preview` being potentially wrong).
