### ISSUE TITLE
Why is AdditionalSecretOutputs a List and not IEnumerable?

### ISSUE THREAD

**Issue by mastoj** [pulumi/pulumi#4820]
Having the property as a `List` seems a little bit to restrictive in my opinion and also a little bit less smooth to work with from F#. If it was IEnumerable it would be easier to assign an F# list to the property, now I need an extra conversion step.

**Comment by mikhailshilkov** [comment]
I think the main driver here is having concise C# code. Having a list enables simpler code like

```cs
new CustomResourceOptions
{
    AdditionalSecretOutputs = { "MyOutput1", "MyOutput2" }
}
```

which one can't do with enumerables. FWIW, I believe this is consistent with other list-like values in our API.

**Comment by stack72** [comment]
@lukehoban / @mikhailshilkov is this something we want to look into or do we believe the current API is correct?

**Comment by lukehoban** [comment]
The current API consistently uses this approach quite broadly.  It would be a meaningful breaking change to change this now, and not immediately clear it's worth it here.  I think we can continue to track the broader set of issues that make the Pulumi .NET API non-idiomatic/awkward to use in F# as part of https://github.com/pulumi/pulumi/issues/3644.  I'll close this one for now.
