### ISSUE TITLE
Add capability for `pulumi stack init` to copy current stack config for new stack

### ISSUE THREAD

**Issue by danfhernandez** [pulumi/pulumi#4823]
Goal is to improve the experience when creating additional stacks with config values, especially ones that are required. This could come either as a flag or default behavior. 

Current stack is `dev`. Contents of `Pulumi.dev.yaml`: 
``` 
config:
  aws:region: us-east-1
```

**Default version**
Run `pulumi stack init staging`. `Pulumi.staging.yaml` is generated and contains: 
``` 
config:
  aws:region: us-east-1
```

**Using option version**
Run `pulumi stack init staging --copy-config`. `Pulumi.staging.yaml` is generated and contains: 
``` 
config:
  aws:region: us-east-1
```

Another option that could improve the experience here is to copy over values defined in `config` from the `Pulumi.yaml` to any new stacks config file. 

Example `Pulumi.yaml`:
```
name: my-project
runtime: nodejs
description: A minimal AWS TypeScript Pulumi program
config: 
  aws:region: us-east-1 
```

Generates a config file with the following when a new stack is created: 
``` 
config:
  aws:region: us-east-1
```

It could be useful to implement both since they do slightly different things.

**Comment by lukehoban** [comment]
Very related to (or maybe just an requirement of?) https://github.com/pulumi/pulumi/issues/1583.

**Comment by danfhernandez** [comment]
Yeah it's very related to that and has the same goal in mind: 

> When creating a new stack it should be easier to have some config populated such that the `pulumi up` right after `pulumi stack init` is less likely to fail if there's required config.

The secret nuance is an important wrinkle to consider.  I think it would be reasonable for an initial implementation to only copy over non-secret values. The same would be the case if the `Pulumi.yaml` path was taken -  only non-secret values can be stored there.
