### ISSUE TITLE
Consider implementing `GetRequiredPlugins` for Python

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#4848]
As of #2560, the engine will attempt to install any missing plugins during `pulumi up` by scanning the snapshot and asking the language host for required plugins. This is a best effort as not all language hosts implement `GetRequiredPlugins`, in particular Python:

https://github.com/pulumi/pulumi/blob/2d61852e4f5577f2b42e87d9ce2dcfc85da452b6/sdk/python/cmd/pulumi-language-python/main.go#L144-L149

Some folks are still experiencing errors due to missing plugins when Python dependencies are installed before Pulumi is installed (e.g. in CI scenarios like https://github.com/pulumi/pulumi-azure/issues/601).

The missing plugin errors wouldn't happen for Python programs if `GetRequiredPlugins` was implemented. I don't see any particular reason why we couldn't implement it for Python.

The way it's implemented for .NET is by running `dotnet list package --include-transitive` and parsing the output.

For Python, we could do something similar. If we assume that pip is being used (seems like a reasonable assumption) we could run `python -m pip list` and parse the output:

```sh
$ venv/bin/pip list
Package    Version
---------- -------
Arpeggio   1.9.2  
attrs      19.3.0 
dill       0.3.2  
grpcio     1.29.0 
parver     0.3.0  
pip        19.2.3 
protobuf   3.12.2 
pulumi     2.4.0  
pulumi-aws 2.9.1  
semver     2.10.2 
setuptools 41.2.0 
six        1.15.0
```

Maybe we'd only support it when the `virtualenv` runtime option is set in `Pulumi.yaml`, as then we'd have stronger idea that `pip` is being used? But that may limit its usefulness as it will be some time before `virtualenv` is adopted broadly.

**Comment by CortalUX** [comment]
Yeah I'm not using the virtualenv option - mainly because as mentioned, I'm using cloud hosted VMs which are 'clean' on setup, then destroyed after. Although - I do use virtual environments on my local machine, and I would use the virtualenv option if it was required for this to work :)

**Comment by justinvp** [comment]
`python -m pip list --format json` outputs JSON
