### ISSUE TITLE
Multi-targeting support

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi#4869]
Should multi-targeting be implemented so that Pulumi can also run on .NET Standard 2.0 and 2.1 instead of just the current target framework (.NET Core 3.1)?

**Comment by mikhailshilkov** [comment]
We discussed this in #3579 and decided to go with .NET Core 3.1. See the discussion there.

Is there a specific reason why you want to see it on Standard?

**Comment by MisinformedDNA** [comment]
I don't need Standard, I was just surprised that it wasn't included. 

Anyway, thanks for the link. I couldn't find that discussion.
