### ISSUE TITLE
.NET and NodeJS reference URLs that don't exist

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi#4870]
I noticed that .NET and NodeJS reference URLs in the comments that don't exist. Both use this URL which results in a 404: github.com/pulumi/pulumi/pkg/v2/resource/stack.RootPulumiStackTypeName

See #4844

**Comment by leezen** [comment]
@stack72 Should this point at github.com/pulumi/pulumi/sdk/v2/go/common/resource/stack instead?
