### ISSUE TITLE
Pulumi GitHub Action: Add test for Python projects that use venv

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#4871]
As of Pulumi v2.4.0, when you create a new Pulumi Python program with `pulumi new`, the CLI creates a lightweight virtual environment in a `venv` directory, runs `venv\bin\pip install -r requirements.txt` to install dependencies in the virtual environment, and sets the `virtualenv: venv` option in `Pulumi.yaml` which tells the CLI to use that virtual environment when subsequent commands (like `pulumi up`) are run.

If you've committed the project as it was generated and want to use it with the Pulumi GitHub Action, you'll end up running into `error: "/github/workspace/venv" doesn't appear to be a virtual environment`.

This is because the generated project includes a `.gitignore` file that excludes the `venv/` dir from Git, so by default the `venv` dir that is generated locally won't be included in any Git commits.

To workaround, you need to remove the `virtualenv` option from `Pulumi.yaml` so that the `pulumi` CLI doesn't attempt to use it.

We should consider making it so this _just works_.

The GHA already installs Python dependencies globally:

https://github.com/pulumi/pulumi/blob/a53dfe69b7c9d56cb7217a69f784ceadd1ed65b2/dist/actions/entrypoint.sh#L117-L120

We could augment this by checking to see if the `virtualenv` option is set in `Pulumi.yaml` and if so, create the virtual environment (if it doesn't exist) and install dependencies into it automatically. Or, alternatively, just strip the `virtualenv` option from `Pulumi.yaml` if the `venv` dir doesn't exist.

**Comment by GaboFDC** [comment]
Is this being worked on? Seems realatively stragin forward so I could make a PR with it if you guys want some extra hands on this

**Comment by justinvp** [comment]
@GaboFDC, we haven't started this yet and would love a PR! 😃

**Comment by justinvp** [comment]
Remaining task is to add a `python_venv` test [here](https://github.com/pulumi/pulumi/tree/f36431106443fc431076b43df68b03538eae0855/tests/containers) and then wiring it up [here](https://github.com/pulumi/pulumi/blob/f36431106443fc431076b43df68b03538eae0855/tests/containers/containers_test.go#L112-L114)
