### ISSUE TITLE
Consider supporting SSH URLs with `pulumi new`

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#4872]
`pulumi new` currently allows specifying URLs to repos like `https://github.com/pulumi/templates`. We should consider supporting SSH URLs like `git@github.com:pulumi/templates.git` (or SSH URLs to GH enterprise) so SSH can be used for authentication.

**Comment by RobbieMcKinstry** [comment]
👋🏻 @dixler When you get a chance, do you think you could provide a TODO list of what's left to get this issue across the finish line? I know in ideation we discussed adding a flag, etc. to use system git in the context of ADO, eventually being able to extend this to ssh URLs more broadly.
