### ISSUE TITLE
sporadic reports of plugin acquisition failing

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#4877]
Over the past week or so, we've seen sporadic reports of plugin acquisition not working as expected on `pulumi up`

https://pulumi-community.slack.com/archives/C84L4E3N1/p1592841319264100
https://github.com/pulumi/pulumi-azure/issues/605

Interestingly, only the azure plugin has been reported to be affected at this time.

This issue is to track instances of this to make sure we're aggregating what's happening

**Comment by jaxxstorm** [comment]
another instance here: https://github.com/pulumi/pulumi-azure/issues/601

**Comment by justinvp** [comment]
I don't think https://github.com/pulumi/pulumi-azure/issues/601 and https://github.com/pulumi/pulumi-azure/issues/605 are related.

In https://github.com/pulumi/pulumi-azure/issues/601, my last comment outlines what I'm pretty sure is going on (confirmed the behavior on my machine). We are just waiting to hear back from the user to confirm installing Pulumi first before installing the Python dependencies did indeed address the issue.

**Comment by jaxxstorm** [comment]
The related issues for this have been closed, so closing this one out
