### ISSUE TITLE
error: could not get cloud url: unmarshalling credentials file: unexpected end of JSON input

### ISSUE THREAD

**Issue by a5a5a9** [pulumi/pulumi#4920]
TEST/pulumi$ pulumi new 
error: could not get cloud url: unmarshalling credentials file: unexpected end of JSON input

**Comment by leezen** [comment]
It'd be great if you could provide more details. What backend are you attempting to use and how is it configured?

**Comment by lukehoban** [comment]
I believe this is a dupe of https://github.com/pulumi/pulumi/issues/3877?

**Comment by a5a5a9** [comment]
I've tried
pulumi new 
pulumi new aws-python
pulumi new kubernetes-python
pulumi login --local

**Comment by lukehoban** [comment]
@a5a5a9 All the occurences of this error mentioned in #3877 have been related to running multiple `pulumi` command concurrently on the same machine - is it possible you are doing that?  Also - could you look at your `~/.pulumi/credentials.json` and see if it looks malformed in any way?

**Comment by a5a5a9** [comment]
credentials.json was empty. I deleted ~/.pulumi and reinstalled it and it works now . thank you
