### ISSUE TITLE
_submodules causes IntelliSense to be confused

### ISSUE THREAD

**Issue by sindre-nistad** [pulumi/pulumi#4931]
Hi,
In version 3.11.0, I am unable to get IntelliSense (autocomplete in IntelliJ's PyCharm)  from the `plum_azure` module.
This worked fine in version 3.9.2.

The problem seem related to how `plum_azure/__init__.py` is generated; the module names are listed in `_submodules`, but changing its name to `__all__`, the IntelliSense works as expected.

In Python, `__all__` is a [special variable](https://docs.python.org/3/tutorial/modules.html#importing-from-a-package) in `__init__.py` files.

Is it possible to rename `_submodules` to `__all__` again?

**Comment by sindre-nistad** [comment]
> Can you tell me how you're importing pulumi_azure here? Is it with `import pulumi_azure as azure`?

Yes

**Comment by komalali** [comment]
I dug into this a little further and looked at some popular open-source python packages like django and pandas to see if and how they are using the __all__ keyword. From what I could find, there isn't consistent use of __all__. Additionally, the problem isn't so much that we aren't using __all__ here, it's that IntelliJ/PyCharm doesn't parse the `importlib.import_module()` function correctly, so even though the submodules are correctly imported into the namespace (can be checked by `dir(pulumi_azure)`), they don't show up in autocomplete.

I have a fix locally, will push it up.

**Comment by sindre-nistad** [comment]
Thanks,
Is this something JetBrain's PyCharm team should be made aware of?

**Comment by komalali** [comment]
@sindre-nistad It looks like an issue already exists: https://youtrack.jetbrains.com/issue/PY-38552
