### ISSUE TITLE
Expose locking primitive

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#4939]
We have locking over updates built into the pulumi service, but sometimes operations need to be grouped into an uninterrupted unit of execution. Consider [recovering from an interrupted update](https://www.pulumi.com/docs/troubleshooting/#interrupted-update-recovery) that leaves the stack in `pending operation` state. To fix you'd run the following series of commands:

```sh
pulumi cancel
pulumi stack export
pulumi stack import
pulumi refresh
```
Ideally you want full control during this procedure and don't want another operator making conflicting changes. Consider a `pulumi stack lock` command to wrap this execution:

```sh
pulumi stack lock --expire=3m
pulumi cancel
pulumi stack export
pulumi stack import
pulumi refresh 
pulumi stack unlock
```

**Comment by damianh** [comment]
Related: https://github.com/pulumi/pulumi/issues/3600

**Comment by lukehoban** [comment]
Closing this out as a duplicate of #3600.  Moved the concrete suggestion for CLI commands into that issue.
