### ISSUE TITLE
Cannot deploy a public Google Cloud Function

### ISSUE THREAD

**Issue by littlepea** [pulumi/pulumi#4946]
I'm following the python example but it's doing the same thing pretty much in terms of `FunctionIamMember` https://github.com/pulumi/examples/blob/master/gcp-py-functions/__main__.py

It looks like setting `member="allUsers"` is not enough anymore to make a function truly public, now the only way I can do it is by deploying once with `gcloud` CLI and adding `--allow-unauthenticated` flag. It seems to be a separate flag now (since the end of 2019) and it's not related to `member`.

So my workflow now is to:

1. Create a function with Pulumi (can't make it public, getting 403 errors)
2. Deploy once with `gcloud` CLI and `--allow-unauthenticated` flag to make it truly public
3. Continue deploying changes with Pulumi

This is madness...

It looks like Terraform and Serverless framework both have [the same issue](https://forum.serverless.com/t/setting-iam-policies-for-google-http-functions-since-all-new-gcloud-http-functions-after-nov-1-2019-will-default-private/8686) as Pulumi.

More context in a [Slack thread](https://pulumi-community.slack.com/archives/C84L4E3N1/p1593408953003000).

**Comment by leezen** [comment]
I'm not actually able to reproduce this. Setting `allUsers` is enough from what I can tell? I recently did a MIW episode using GCP functions: https://github.com/pulumi/pulumitv/tree/master/modern-infrastructure-wednesday/2020-05-27 and I am able to curl the endpoint from that project after deploying it.

Similarly, I just deployed the example and was able to receive back a response (I didn't bother configuring the API keys, but the function responds):
```
❯ curl https://us-central1-pulumi-development.cloudfunctions.net/eta_demo_function-39ef674                                                gcp-py-functions 20:19:55
[ENABLE TWILIO TO SEND A TEXT]:
Hey! I'm leaving now, I'll be at 'Space Needle, Seattle, WA' to pick you up in about [ENABLE GOOGLE MAPS TO DETERMINE TRAVEL TIME].%
```

Could you share how you're deploying the function? How are you attempting to query the function?

**Comment by littlepea** [comment]
@leezen I've figured it out, looks like the problem was that my service account used with Pulumi didn't have `Cloud Functions Admin` role in IAM so it couldn't properly create the invoker. 

The weird thing is that Pulumi didn't show any errors about this until today for me, it was creating the function and invoker but I was getting 403 and redeploying a function with `gcloud` CLI would solve the problem...
But today Pulumi started failing to create the invoker specifically so this is how I've found by trial and error that adding that IAM role solves the problem...
