### ISSUE TITLE
Pulumi destroy with invalid state file proceeds but without deleting resources

### ISSUE THREAD

**Issue by oliverholliday** [pulumi/pulumi#4955]
I manually edited the state to remove pending_operations but left a trailing comma, making the JSON invalid.

When I ran `pulumi destroy --yes --non-interactive` on our CI server the result was that pulumi removed all resources from the state file but didn't actually delete any resources.

`pulumi preview` against the same invalid state file produced an error:

```
error: failed to load checkpoint: invalid character ',' looking for beginning of value
```

I believe `pulumi destroy` doesn't have the same verification step and instead just proceeds without erroring - as if there are no resources in the file - and ends up with a blank state and no resources destroyed.

**Comment by tgummerer** [comment]
Not sure when exactly this was fixed, but testing this locally, destroy now behaves correctly, and aborts:


```
$ pulumi destroy --yes --non-interactive                        
Previewing destroy (dev2):
error: failed to load checkpoint: place 1: invalid character ']' looking for beginning of value
```
