### ISSUE TITLE
[codegen/[python] config module should start with an underscore

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#4961]
This module is only used internally and therefore should be marked as a private module.

Related: https://github.com/pulumi/pulumi/pull/4959

**Comment by lukehoban** [comment]
> This module is only used internally

This particular module is somewhat commonly used by user code to get the values of package configuration from within the program.  I think we most likely don't want to hide this one (and that it would be a non-trivial breaking change if we did).

**Comment by komalali** [comment]
I think I got confused by the fact that we explicitly don't import it into the top-level package for providers. What is the reason for that?

https://github.com/pulumi/pulumi/blob/master/pkg/codegen/python/gen.go#L310-L312
