### ISSUE TITLE
Enable SourceLink and embed PDB symbols for all NuGet packages

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi#4962]
[SourceLink](https://github.com/dotnet/sourcelink) is essential and would make it easy to step _into_ Pulumi C# source supplied as NuGet packages.

Happy to submit a PR if someone can point me to how / where these packages are created at build-time.

**Comment by gitfool** [comment]
Looks like you just need to drop an appropriate `Directory.Build.props` into the top level [sdk/dotnet](https://github.com/pulumi/pulumi/tree/master/sdk/dotnet) directory; e.g.:
```xml
<Project>
  <PropertyGroup>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
  </ItemGroup>
</Project>
```

**Comment by mikhailshilkov** [comment]
We could also add this to the `csproj` / `fsproj` files, we only have two projects in `pulumi/pulumi`. I guess we also need to do this for every provider?

**Comment by gitfool** [comment]
Yes to both.

**Comment by mikhailshilkov** [comment]
Great! Extending the provider's csproj is easy: it's defined [here](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/dotnet/templates.go#L111)
