### ISSUE TITLE
Add a Visual Studio Code dev container to encapsulate the development environment

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi#4963]
I don't want to pollute my development environment in order to [hack on Pulumi](https://github.com/pulumi/pulumi/blob/master/CONTRIBUTING.md#hacking-on-pulumi).

Fortuntately, Visual Studio Code [dev containers](https://github.com/microsoft/vscode-dev-containers) are a great solution. Please add one to this repo! 😁 

(I should be able to make code changes and run a build from inside this dev container.)

**Comment by gitfool** [comment]
I got this to work with the following files:

`.devcontainer/devcontainer.json`:
```json
{
    "name": "Pulumi",

    "dockerFile": "Dockerfile",
    "context": "..",

    "runArgs": [
        "-e", "PULUMI_ACCESS_TOKEN"
    ]
}
```
`.devcontainer/Dockerfile`:
```dockerfile
FROM pulumi/pulumi

RUN ln -s /usr/local/go/bin/go /usr/local/bin/go

RUN version=0.0.24 \
    && curl -fsSLO https://github.com/pulumi/pulumictl/releases/download/v$version/pulumictl-v$version-linux-amd64.tar.gz \
    && tar -xzf pulumictl-v$version-linux-amd64.tar.gz --directory /usr/local/bin --no-same-owner pulumictl \
    && rm -f pulumictl-v$version-linux-amd64.tar.gz \
    && pulumictl version
```
Notes:
* Using [pulumi/pulumi](https://github.com/pulumi/pulumi/blob/master/docker/pulumi/Dockerfile) base image for required tools
* `go` binary is not in path (`ENV` `PATH` override does not seem to work); add via symbolic link into `/usr/local/bin`
* [`pulumictl`](https://github.com/pulumi/pulumictl) binary is not in base image but needed for builds

**Comment by gitfool** [comment]
@komalali so the above seems to work for `make ensure && make` so is it worth submitting a PR so others can discover it?

**Comment by komalali** [comment]
Yes definitely, that would be awesome! Thanks for working through this @gitfool 🎉

**Comment by spara** [comment]
You can also use the [pulumi Dockerfile](https://github.com/pulumi/pulumi/blob/master/docker/pulumi/Dockerfile) as in this [example](https://www.pulumi.com/blog/vscode-devcontainers/) instead of building from the pulumi image, or alternatively do this instead of building the pulumictl from source:

```
# Install the Pulumi SDK, including the CLI and language runtimes.
RUN if [ "$PULUMI_VERSION" = "latest" ]; then \
    curl -fsSL https://get.pulumi.com/ | bash; \
  else \
    curl -fsSL https://get.pulumi.com/ | bash -s -- --version $(echo $PULUMI_VERSION | cut -c 2-); \
  fi && \
  mv ~/.pulumi/bin/* /usr/bin
```

**Comment by komalali** [comment]
@spara this PR basically codifies your example and is built off the pulumi Dockerfile as a base image. super helpful to not have to go through all the steps manually!
