### ISSUE TITLE
Add a CLI option to wait for the debugger in the language specific child process

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi#4964]
I'd like to tighten the dev inner loop for C#/.NET development and this could no doubt be applied to other languages/frameworks.

In particular, add a CLI option, e.g. `--debug-break`, that will help synchronize attaching the language-specific debugger to the child process spawned by `pulumi up`.

For example, [Cake](https://github.com/cake-build/cake) supports debugging a C# build script with a `--debug` option:
* [DebugCommand.Execute](https://github.com/cake-build/cake/blob/36489449227160c778101658b09dce37f3cbd5cb/src/Cake/Commands/DebugCommand.cs#L42-L48)
* [CakeDebugger.WaitForAttach](https://github.com/cake-build/cake/blob/36489449227160c778101658b09dce37f3cbd5cb/src/Cake/Diagnostics/CakeDebugger.cs#L21-L27)

In order for this to interact with Visual Studio Code, Pulumi should produce output that can be used to detect the transition to when the child process has spawned and is waiting for the debugger to be attached. Ideally this output includes the child process pid.

**Comment by lukehoban** [comment]
This is effectively what we are planning on doing for https://github.com/pulumi/pulumi/issues/1372. The goal is for that to cover this scenario - so if there’s anything that should be added on that issue - please do add a note there. I’ll close this one out to consolidate feedback there.

**Comment by gitfool** [comment]
Doh!
