### ISSUE TITLE
Pulumi alpha NuGet packages do not work with `pulumi plugin install resource`

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi#4965]
Using the following `csproj` file I can reference the latest Pulumi alpha NuGet packages:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pulumi" Version="*-*" />
    <PackageReference Include="Pulumi.Aws" Version="*-*" />
  </ItemGroup>
</Project>
```
(Note: [floating _prerelease_ versions](https://github.com/NuGet/Home/wiki/Support-pre-release-packages-with-floating-versions) has been supported since NuGet 5.6 and Visual Studio 16.6.)

This builds fine but fails during `pulumi up`:
```
pulumi:providers:aws default_2_12_0_alpha_1593596255_36552968  error: no resource plugin 'aws-v2.12.0-alpha.1593596255+36552968' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v2.12.0-alpha.1593596255+36552968`
```
This looks like it's because the NuGet package was published to nuget.org with a semver _excluding_ version metadata ([2.12.0-alpha.1593596255](https://www.nuget.org/packages/Pulumi.Aws/2.12.0-alpha.1593596255)), despite using the full semver internally, which is fine (and what we do too), but the call to `pulumi plugin install resource` is using the full semver _including_ metadata, so they just needs to agree on what "external" version to use.

![image](https://user-images.githubusercontent.com/750121/86426639-44e88d00-bd3c-11ea-9530-4ef918eecc0b.png)

**Comment by leezen** [comment]
It appears this affects not just .NET, but also Node. We should make sure this works correctly for all package managers.

**Comment by stack72** [comment]
Hi @gitfool 

I just rolled out a chance that all *future* dev builds will now have the correct verision for downloading the plugin

Paul
