### ISSUE TITLE
Allow `pulumi state delete` to proceed even in case of snapshot integrity failure

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#4984]
### Problem

A user's state file can occasionally get into a bad _state_ (e.g. https://github.com/pulumi/pulumi/issues/3583) and must be fixed either with `pulumi state delete ...` or through manual changes. Unfortunately, some bad states prevent `pulumi state delete ...` from functioning (such as the error below and linked issue) and the user must resort to manual editing the state file which is error-prone. 

#### Example snapshot integrity failure error

```
% pulumi state delete 'urn:pulumi:dev::p-parent-delete-test-::aws:s3/bucket:Bucket$aws:s3/bucket:Bucket::child'
error: .pulumi/stacks/dev.json: snapshot integrity failure; refusing to use it: child resource urn:pulumi:dev::p-parent-delete-test-::aws:s3/bucket:Bucket$aws:s3/bucket:Bucket::child refers to missing parent urn:pulumi:dev::p-parent-delete-test-::aws:s3/bucket:Bucket::parent
```

### Suggestions for a fix

Allow `pulumi state delete ...` to still proceed when a user's state is in a "snapshot integrity failure" _state_ as this is safer than the user manually editing the state file. 

**Update:** As @joeduffy pointed out this is available via `--disable-integrity-checking`, but we should make this an interactive prompt rather than a flag so that the user knows this is an option.

Understandably, this might not be feasible in all cases (invalid JSON), but some cases like this should still be allowed.

**Comment by joeduffy** [comment]
Does [`--disable-integrity-checking`](https://www.pulumi.com/docs/reference/cli/#options) work around this?

**Comment by clstokes** [comment]
> Does [`--disable-integrity-checking`](https://www.pulumi.com/docs/reference/cli/#options) work around this?

Only if you know that option exists! 🤦 

Thanks! That indeed allows the `pulumi state delete` command to proceed and fix the state. Closing this.

**Comment by clstokes** [comment]
_Actually_, I'm going to reopen this. That option is indeed available via `pulumi state delete --help` but I feel the user experience could be better here.

We prompt the user interactively before proceeding with the `pulumi state delete`. We should also make the disable-integrity-checking functionality interactive so that it's more discoverable for the end user.

**Comment by joeduffy** [comment]
Agree, might also be nice for integrity errors to mention the flag.

**Comment by clstokes** [comment]
> Agree, might also be nice for integrity errors to mention the flag.

Yep, that would work too.

**Comment by johnnybenson** [comment]
Integrity errors do not mention the flag today and it would have saved me a few days before finding it mentioned here.

```
  pulumi:providers:aws (default_6_28_2):
    error: pre-step event returned an error: failed to verify snapshot: resource urn:pulumi:dev::api::aws:lb/targetGroup:TargetGroup::api refers to unknown provider urn:pulumi:dev::api::pulumi:providers:aws::default_6_25_0::8fe6bdcd-b46f-48a3-9c66-4878651c3e94
```

**Comment by daaain** [comment]
I also lost a few hours figuring out how to dig myself out of a hole of my own making with errors like: 

```
error: getting snapshot: snapshot integrity failure; refusing to use it: resource urn:pulumi:staging::...::gcp:cloudrun/service:Service::...'s dependency urn:pulumi:staging::...::gcp:pubsub/topic:Topic::document-uploaded-topic comes after it
```

```
error: snapshot integrity failure; refusing to use it: resource urn:pulumi:staging::...::gcp:cloudrun/service:Service::... dependency urn:pulumi:staging::....::gcp:pubsub/topic:Topic::document-uploaded-topic refers to missing resource
```

Searching for these error message came up with a few different topics in pulumi-community (see [1](https://archive.pulumi.com/c/typescript), [2](https://archive.pulumi.com/c/general/223), [3](https://archive.pulumi.com/c/general/583)) that all suggested versions of having to delete and import state and / or some manual editing of the state file which I was reluctant to do as I had the feeling I could mess things up even more.

So I'd like to join in asking if these integrity errors could please come with a documentation URL that gives a bit of context what is wrong and then suggests the use of the `--disable-integrity-checking` flag which in the end helped me to fix the issues I had by allowing me to destroy and recreating the affected resources. Without that flag I was completely blocked with most commands just returning the error, including refresh.
