### ISSUE TITLE
Confusing transitive resource updates when dependencies have changes

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#4992]
If a resource is updated it can cause confusing and invalid updates in the preview for downstream resources that depend on any of its outputs. As a concrete example, if I provision an AWS KMS Key and an RDS Cluster that uses the KMS Key ID and then update tags on the KMS Key, Pulumi will indicate the RDS Cluster will be replaced, but this doesn't actually happen.

Note: This is a general issue, not specific to AWS KMS or RDS.

#### Suggestions for a fix

Only indicate changes to downstream resources that will actually occur.

#### Code to reproduce

```ts
import * as aws from "@pulumi/aws";

const kmsKey = new aws.kms.Key("main", {
    tags: {
        /**
         * Change any of these tags and the RDS Cluster will be marked as `replace`, but won't actually happen.
         */
        // k1: "v1",
        k2: "v2",
        // k3: "v3",
    }
});

const defaultCluster = new aws.rds.Cluster("default", {

    storageEncrypted: true,
    kmsKeyId: kmsKey.arn,

    availabilityZones: [
        "us-west-2a",
        "us-west-2b",
        "us-west-2c",
    ],
    backupRetentionPeriod: 5,
    clusterIdentifier: "aurora-cluster-demo",
    databaseName: "mydb",
    engine: "aurora-mysql",
    engineVersion: "5.7.mysql_aurora.2.03.2",
    masterPassword: "o209dsjvnlasdkfjasldf;.oad",
    masterUsername: "foo",
    preferredBackupWindow: "07:00-09:00",
    skipFinalSnapshot: true,
}, {
    protect: false,
    // ignoreChanges: ["kmsKeyId"],
});
```

#### Steps to reproduce

1. `pulumi stack init`
1. `pulumi config set aws:region us-west-2`
1. `up` the code above
1. change tags on the `aws.kms.Key` resource
1. `up` again and observe the `replace` operation on the `aws:rds:Cluster` resource in the output

```
p-rds-kms-diff % pulumi up
Previewing update (cameorn):
     Type                 Name                    Plan        Info
     pulumi:pulumi:Stack  p-rds-kms-diff-cameorn              
 ~   ├─ aws:kms:Key       main                    update      [diff: ~tags]
 +-  └─ aws:rds:Cluster   default                 replace     [diff: ~kmsKeyId]
 
Resources:
    ~ 1 to update
    +-1 to replace
    2 changes. 1 unchanged

Do you want to perform this update? yes
Updating (cameorn):
     Type                 Name                    Status      Info
     pulumi:pulumi:Stack  p-rds-kms-diff-cameorn              
 ~   └─ aws:kms:Key       main                    updated     [diff: ~tags]
 
Resources:
    ~ 1 updated
    2 unchanged

Duration: 4s

Permalink: https://app.pulumi.com/clstokes/p-rds-kms-diff/cameorn/updates/2
```

#### Workaround

A workaround for this is to use [`ignoreChanges`](https://www.pulumi.com/docs/intro/concepts/programming-model/#ignorechanges) on the downstream resource to ignore changes to the `kmsKeyId` in this case. Also, can use [`protect: true`](https://www.pulumi.com/docs/intro/concepts/programming-model/#protect) to protect against potential resource deletions as a safety mechanism.

**Comment by joeduffy** [comment]
This came up just recently with a key customer (and seems like we've had this longstanding problem for quite some time). I appreciate we need to be conservative, but don't we know for sure that readonly (purely-computed) properties will never change during an update? This is AFAIK the same thing we do with resource IDs (and I would guess the above won't repro if you use `kmsKey.id` rather than `kmsKey.arn` as the input to the cluster's `kmsKeyId` property). In this case, ARN is a computed property. Or are there computed properties that are expected to change? (That would be surprising and seem to go counter to the declarative goal state approach at the heart of our system but is that the reason we haven't fixed?)

**Comment by leezen** [comment]
Some thoughts from @pgavlin:

> I think we can do something relatively straightforward at the cost of some hopefully rare but potentially surprising behavior. In essence, we should be able to allow a resource provider to indicate that certain property paths are known to be stable, and that the engine should retain any old values for those properties when returning values from RegisterResource. This could cause surprising behavior if the values of those properties do in fact change when the update is applied. I believe that problem is solvable with preview constraints, but implementing those constraints feels like a much larger task.

> For TF-derived plugins, we can adopt the TF rule: any property that does not appear in the TF diff is assumed to be stable. This will cover essentially anything that is not k8s. For k8s, we could take advantage of server-side dry-run. Server-side dry-run allows the k8s provider to hand the k8s API server the configuration for a resource and receive as much of the goal state as is knowable in return. We already use this capability in the provider; we could take further advantage by treating any properties in the result of the dry-run that have not changed with respect to the current state as stable properties.

**Comment by leezen** [comment]
Given the nature of this work, we'll want to start with a design doc for what we'll actually do and how this will actually work

**Comment by leezen** [comment]
Re-opening to track the provider updates that need to happen to have #5443 take effect.

**Comment by stack72** [comment]
Hi all

I am delighted to say that this work has been completed and has been rolled out to the CLI in v2.12.1 and all of the providers as the latest release

Please let us know if there are any issues!

Paul
