### ISSUE TITLE
slack.pulumi.com no longer working

### ISSUE THREAD

**Issue by JesterOrNot** [pulumi/pulumi#4993]
How does one join the Pulumi Slack community When clicking join I get

![image](https://user-images.githubusercontent.com/50386709/87204520-af647480-c2ca-11ea-9e4d-885407daf15c.png)

Is the slack only for the official team? Or is this an enterprise/paid feature? Or is it something on my end?

Sorry if this is the wrong place to post this. I didn't know where else to put it.

**Comment by lukehoban** [comment]
Thanks @JesterOrNot.  This should now be fixed.  Could you try again and let us know if you are still seeing any issues?

**Comment by JesterOrNot** [comment]
Works!

**Comment by introom** [comment]
![image](https://user-images.githubusercontent.com/669045/107150734-3e895600-699a-11eb-9e8f-075970fb5263.png)
No longer working again.

**Comment by susanev** [comment]
@introom did someone invite you recently? or were you first trying to join today?

**Comment by lukehoban** [comment]
The Slack invite code was updated.

**Comment by bchex** [comment]
Looks like it needs to be updated again...

<img width="1773" alt="image" src="https://user-images.githubusercontent.com/103138374/165628981-5a2860c4-430e-43b1-b4e4-287c82a388b9.png">

**Comment by susanev** [comment]
hi @bchex we will get this updated soon, for now you can use this link
https://join.slack.com/t/pulumi-community/shared_invite/zt-1825lc88k-KjgW6nh7qQd5sikIZgPTAA

**Comment by susanev** [comment]
okay all fixed now! thx for the report!!

**Comment by sloncho** [comment]
Not working as of today :(

**Comment by cnunciato** [comment]
@sloncho In case you happened to click the link quoted above (`https://join.slack.com/.../...gPTAA`), that link is definitely expired. You should be able to sign up at https://slack.pulumi.com without issue now -- but please do post back here if that isn't the case!

**Comment by sloncho** [comment]
Thanks

**Comment by scav** [comment]
Link appears to have expired again.

**Comment by cnunciato** [comment]
@scav Just updated. If you're trying to join, try https://slack.pulumi.com again, and thanks for the report!
