### ISSUE TITLE
Remove the _custom_resource_type global from the python sdk. 

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#5000]
We override [this global](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/known_types.py#L35-L36) in our [tests](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/test/test_next_serialize.py#L50-L54). 

Rework the test to not require this global override.

**Comment by mikhailshilkov** [comment]
It looks like this has been fixed in #5041
