### ISSUE TITLE
Preview/Up Slowness

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi#5001]
I have a large stack that always seems to take a long time to process up or even just a preview. I have tried targeting just two resources and I still get the slowness. From the CLI I see if process all the items which show the CRUD operations but it seems to hang/wait for a long time before finishing processing.

The stack I am working on is "mitchell.maler/k8s-cluster-projects/asc-stg-k8s-c01".
Pulumi Version: v2.6.1
Using Pulumi Cloud for stack state.

@lukehoban I have talked to you on slack about this and thought it would be best to document this in an issue for better visibility.

## Example 1
Here I ran an up that targets two URNs which are to be created which took around 8m
```
$ pulumi up \
  --target "urn:pulumi:..." \
  --target "urn:pulumi:..." \
  --skip-preview --tracing=file:./up.trace
Updating (stack_name):
     Type                          Name                   Status      
     pulumi:pulumi:Stack           name                                                           
 +   ├─ kubernetes:core:Secret     secret-name            created     
 +   └─ kubernetes:core:ConfigMap  config-name            created     
Resources:
    + 2 created
    1697 unchanged
Duration: 7m58s
```

## Example 2
I also have ran a preview on the whole stack with `--logtostderr -v=9`. I seem hundreds (maybe thousands) of the evensink.go then a long hang before the langruntime_plugin.go:163 which results in about a 7 min wait. This is most likely my issue and this was only a preview.

```
I0709 20:53:46.756266   23872 eventsink.go:59] Registering resource monitor end: t=vault:kubernetes/authBackendRole:AuthBackendRole, name=omitted, custom=True
I0709 20:53:46.756293   23872 eventsink.go:62] eventSink::Debug(<{%reset%}>Registering resource monitor end: t=vault:kubernetes/authBackendRole:AuthBackendRole, name=omitted, custom=True<{%reset%}>)
....................
I0709 21:00:34.799332   23872 langruntime_plugin.go:163] langhost[dotnet].RunPlan(pwd=/Users/mitch.maler/omitted.csproj,...,dryrun=true) success: progerr=
I0709 21:00:34.801075   23872 plan_executor.go:219] planExecutor.Execute(...): incoming event (nil? true, <nil>)
Resources:
    + 61 to create
    ~ 1 to update
    62 changes. 1698 unchanged
________________________________________________________
Executed in  692.09 secs   fish           external 
   usr time  1236.14 secs  176.61 millis  1235.96 secs 
   sys time  102.84 secs   22.25 millis  102.81 secs 
```

I sent @lukehoban trace files for both of these in slack but he said they are pretty large so might not be easy to explore.

Please let me know if there is anything else I can post here or DM someone. I am still pulling apart and poking around my stack to see if it is anything on my side.

**Comment by lukehoban** [comment]
This is unfortunately hard to diagnose without access to your environment.  

From the Pulumi side, I see a typical update that takes ~9min.  It completes all of it's state file updates within the first 2min, and then doesn't communicate to the backend at all for just over 7 minutes, except to renew a lease token for the update every 2.5 minutes.  That suggests that something is happening on the client that is "hanging" for a long time after all the resource operations are done.

It sounds like you see this same 7min "hang" even in previews?

Is it possible you have code yourself that would be waiting - perhaps an `.apply` call that runs some code that could need to wait for a long time?  Also - do you know what the memory and CPU utilization of the `pulumi-*` processes look like during the update?

Is there anything at all in your code that works with the outputs of resources your stack manages?  Do you have stack outputs - and if so - anything really large?
