### ISSUE TITLE
Pulumi tags in YAML stacks

### ISSUE THREAD

**Issue by albertocorrales** [pulumi/pulumi#5004]
I'm working with pulumi tags, and as far as I know, we need to use Pulumi command on the console to create, update or remove tags: https://www.pulumi.com/docs/reference/cli/pulumi_stack_tag/

However, it would be great if we could manage our tags in our stack YAML file. For example, something like this in Pulumi.dev.yaml stack:
```
config:
  aws:region: eu-west-1
  domain:param1: value1
  domain:param2: value2
tags:
  tag-key-1: tag-value-1
  tag-key-2: tag-value-2
```

That way to handle tags would be great to maintain them in our source code repository and have better visibility of the tags we are using per each stack.

**Comment by catmeme** [comment]
Operationally managing tags in a declarative configuration is much easier / less manual than using the pulumi cli or web console.

My organization would love to take advantage of pulumi tags, but without this feature, it's hard for us to commit.

**Comment by sam-utila** [comment]
Cool, I wanted this too.
I see that is already in - but site documentation does not reflect this great feature
