### ISSUE TITLE
Pulumi New to support Private template repo

### ISSUE THREAD

**Issue by chr15murray** [pulumi/pulumi#5007]
I've been trying to use a private repo as the basis for a pulumi templates. Then calling it using:
`pulumi new https://github.com/<redacted>/pulumi-templates/azure-typescript`

This results in `error: authentication required`

I can't see any way to parse authentication options so tried using basic auth and a PAC token but this also didn't work. Presumably this is because you can only retrieve files (not browse). 
`pulumi new https://$GHPAC@raw.githubusercontent.com/<redacted>/pulumi-templates/master/azure-typescript`

I asked in the community slack and was directed here to raise as an issue. Original question here: 
https://pulumi-community.slack.com/archives/C84L4E3N1/p1594724059405800

The ideal situation would allow the use of existing authentication and/or to prompt the user for credentials. Ideally this could be once on the machine for repeat use.

An alternative would be support for `pulumi repo add` with the same credential support.

Thanks

Chris

**Comment by lukehoban** [comment]
Related to https://github.com/pulumi/pulumi/issues/4872.

**Comment by chr15murray** [comment]
As a workaround. It's possible to clone the private repo separately and then use a local file path reference instead. 

`pulumi new ~/git/pulumi-templates/azure-typescript`

**Comment by Graham-Beer** [comment]
Trying to perform a pulumi new with a AWS CodeCommit repository. Passing AWS IAM git credentials to the https header returns a `error: authentication required`. Able to perform a git clone without any issues.

**Comment by williamsbdev** [comment]
@lukehoban, @leezen, @justinvp - I'd like to take a stab at adding the functionality for private repo support. However, prior to starting I'd like to get some guidance on what the team would like to see as far as how this should be implemented (to make the most effective use of everyone's time).

I'm curious if the Pulumi team has a preference on one or both of the following issues being implemented as a part of the support for private repo functionality.
- #3444
- #4872

My initial thoughts are that we could leverage a new/existing file in the `PULUMI_HOME` directory to track the template repositories and also the credentials for fetching these private repositories via either `ssh` or `https`.

I've found these [examples](https://github.com/go-git/go-git/tree/master/_examples/clone/auth) for how to authenticate with `go-git`. I used these to successfully pull down a private template repository by building the Pulumi CLI with my local credentials hard coded just to prove it out.

The reading of the file for credentials _should_ be isolated to this [file](https://github.com/pulumi/pulumi/blob/master/sdk/go/common/util/gitutil/git.go).

My other questions are (not mutually exclusive):
- Should we add another command to configure template repositories (think `helm repo`)?
- Should we add flags to the `pulumi new` command to support private template repos?
- Should we store a file with the credentials to be reused?

I'm excited to start working on this feature once I get a little guidance from the Pulumi team as to what they'd like to support long-term.

**Comment by hansarh** [comment]
Any news on this?

**Comment by blampe** [comment]
@chr15murray if you've configured an SSH key with GitHub you should be able to use the alternative address for the repo:

```
pulumi new git@github.com:<redacted>/pulumi-templates/azure-typescript
```

**Comment by lukehoban** [comment]
Per @blampe's note in https://github.com/pulumi/pulumi/issues/5007#issuecomment-1686806782 above, this is now fixed and private templates can be used with `pulumi new` via either SSH keys or token auth. 🚀
