### ISSUE TITLE
fatal: A precondition has failed for snap

### ISSUE THREAD

**Issue by JesusGoVar** [pulumi/pulumi#5016]
Pulumi Version:   v2.6.1
Go Version:       go1.14.3
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            fatal: A precondition has failed for snap

goroutine 1 [running]:
runtime/debug.Stack(0xc0000d54d8, 0x14d1020, 0xc0001cd0b0)
        C:/go/src/runtime/debug/stack.go:24 +0xa4
main.panicHandler()
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x75
panic(0x14d1020, 0xc0001cd0b0)
        C:/go/src/runtime/panic.go:969 +0x174
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Require(0x0, 0x17c6271, 0x4)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/require.go:26 +0x143
github.com/pulumi/pulumi/pkg/v2/resource/edit.LocateResource(0x0, 0xc00003a0e0, 0xa, 0x14bf1e0, 0xc0004522d0, 0x181)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/resource/edit/operations.go:84 +0x51
main.locateStackResource(0x17c7e3d, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00003a0e0, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state.go:59 +0x64
main.runStateEdit.func1(0x17c7e3d, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state.go:118 +0x88
main.runTotalStateEdit(0x0, 0x0, 0xc0000d5b01, 0xc0000d5ba0, 0x13ad268, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state.go:164 +0x25b
main.runStateEdit(0x0, 0x0, 0xc000181701, 0xc00003a0e0, 0xa, 0xc0000d5c88, 0xc00018e290, 0xc000195f10)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state.go:117 +0x90
main.newStateDeleteCommand.func1(0xc000350580, 0xc000193b00, 0x1, 0x1, 0x0, 0x0)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/state_delete.go:58 +0xc7
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc000350580, 0xc000193b00, 0x1, 0x1)
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x72
github.com/spf13/cobra.(*Command).execute(0xc000350580, 0xc000193a70, 0x1, 0x1, 0xc000350580, 0xc000193a70)
        C:/Users/appveyor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2a4
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001ca840, 0x15, 0x0, 0x0)
        C:/Users/appveyor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/appveyor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        C:/Users/appveyor/go/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x54

**Comment by stack72** [comment]
Hi @JesusGoVar 

apologies this has taken so long to get back to - please can you tell me what you were doing when this happened?

I am trying to look into it

Paul

**Comment by stack72** [comment]
Hi @JesusGoVar 

I am checking back in on this again - please can you let us know what backend you were using when this happened?

Thanks

Paul
