### ISSUE TITLE
Output in Python allows infinite iteration

### ISSUE THREAD

**Issue by rohfle** [pulumi/pulumi#5028]
**Summary**

Iterating through acm.Certificate.domain_validation_options results in an infinite loop that creates a memory leak that eats all available memory.

**System**
- Ubuntu 19.04
- Python 3.7.4
- Terraform 0.12.25 (probably not relevant)
- Pulumi 2.6.1

**Example code**

```python
"""An AWS Python Pulumi program"""

import pulumi
from pulumi_aws import ec2, acm, lb, route53

# Configuration
config = pulumi.Config()
MANAGED_DOMAINS = config.require_object('managed_domains')
EXTRA_DOMAINS = config.require_object('extra_domains')
ALL_DOMAINS = EXTRA_DOMAINS + MANAGED_DOMAINS

# Create new zones
zones = {}
for domain in MANAGED_DOMAINS:
  zone = route53.Zone(domain, name=domain)
  zones[domain] = zone

# Create ACM generated certificate
cert = acm.Certificate("cert",
    domain_name=ALL_DOMAINS[0],
    tags={
        "Environment": "test",
    },
    validation_method="DNS",
    subject_alternative_names=ALL_DOMAINS[1:]
)

# Add the validation DNS records to each managed domain
cert_records = []
for record_to_add in cert.domain_validation_options:
  if record_to_add.name not in MANAGED_DOMAINS:
    continue
  record = route53.Record(f"acm-verify-{record_to_add.name}",
      name=record_to_add.resourceRecordName,
      ttl=60,
      type=record_to_add.resourceRecordType,
      records=[record_to_add.resourceRecordValue],
      zone_id=zones[record_to_add.name])
  cert_records += [record]

# Wait for verification of ACM cert
cert_validation = acm.CertificateValidation(
  "cert-validation",
  certificate_arn=cert.arn
)

```

**Debugging**

Theres probably a better way to do this, but for me to debug the out of memory issue, I moved `venv/bin/python3` to `venv/bin/python3.orig` and put the following at `venv/bin/python3`:

```bash
#!/bin/bash

ARGS=( "$@" )

echo "Env" > args_used
env >> args_used
echo "Run" >> args_used
echo "python3.orig -m pdb ${ARGS[@]}" >> args_used
sleep 3600
```

Then:
- run `pulumi preview -d -v 9 --logtostderr`
- switch to second terminal, `cat args_used`
- copy and export `PULUMI_CONFIG` (using single quotes to keep formatting)
- copy and paste the `python3.orig -m pdb ...` command to get a pdb shell 
  - note you can also use `gdb -ex r --args python3.orig ...` or other tools at this point
- set a breakpoint for the line `for record_to_add in cert.domain_validation_options` (line 34 for me):
```
b <path/to/__main__.py:34>
```
- run using command `r` in pdb
- code will break
- interact with code using `interact`
- try the following code in the interpreter:
```python
for foo in cert.domain_validation_options:
    print("Infinite loop")
```
- watch your memory usage grow with top

**Possibly related issues**
Looks like there is a redesign of `aws_acm_certificate` occurring in terraform, one feature of which is that `domain_validation_options` will be calculated during plan.
- https://github.com/terraform-providers/terraform-provider-aws/issues/13053
- https://github.com/terraform-providers/terraform-provider-aws/pull/14199

**Comment by leezen** [comment]
This actually looks more like a bug in `Output` than anything. I believe if you run the loop within the apply, the code above should work, e.g.

```
def iterate_records(validation_options):
  for record_to_add in validation_options:
    ...
cert.domain_validation_options.apply(lambda o: iterate_records(o))
```

**Comment by leezen** [comment]
Assuming the above helps with your issue, I'm going to rename this issue to be the fact that iterating over an output doesn't return any type of error and seems to allow arbitrary iteration.

More minimal repro:
```
import pulumi

o = pulumi.Output.from_input("hello")
count = 0

for f in o:
    print(f"Hello {count}")
    count += 1
```

**Comment by rohfle** [comment]
Thanks - you are right. Switching the code to run in an .apply() stopped the memory leak from occurring.

The docs for .apply() method - https://www.pulumi.com/docs/intro/concepts/programming-model/#apply

**Comment by rohfle** [comment]
[This](https://github.com/pulumi/pulumi/blob/f36431106443fc431076b43df68b03538eae0855/sdk/python/lib/pulumi/output.py#L224) function is being called even though the Output is a list
```python
    def __getitem__(self, key: Any) -> 'Output[Any]':
        """
        Syntax sugar for looking up attributes dynamically off of outputs.
        :param Any key: Key for the attribute dictionary.
        :return: An Output of this Output's underlying value, keyed with the given key as if it were a dictionary.
        :rtype: Output[Any]
        """
        return self.apply(lambda v: UNKNOWN if isinstance(v, Unknown) else cast(Any, v)[key], True)
```

and key is 0,1,2,3,4,5,6... etc

**Comment by rohfle** [comment]
So this has the same issue
```
class Foo:
    def __getitem__(self, key):
        return "baa %s" % key

foo = Foo()
for thing in foo:
    print(thing)
```

From python [docs](https://docs.python.org/3/reference/datamodel.html#object.__getitem__)

> object.__getitem__(self, key)¶
> 
> Called to implement evaluation of self[key]. For sequence types, the accepted keys should be integers and slice objects. [...]; if of a value outside the set of indexes for the sequence (after any special interpretation of negative values), IndexError should be raised. [...]
> 
> **Note
> for loops expect that an IndexError will be raised for illegal indexes to allow proper detection of the end of the sequence.**

**Comment by lukehoban** [comment]
> __getitem__

Yes - that is the core issue - `Output` objects delegate all accesses to an `apply`.  

We will likely want to implement `__iter__` on `Output` or explicitly exclude it from the forwarding in `__getitem__`/`__getattr` since it can never be correctly "lifted" onto the value in the Output (since it must produce a prompt iteration to be useful in Python).

**Comment by GaboFDC** [comment]
This also makes the example on https://www.pulumi.com/docs/reference/pkg/aws/acm/certificate/#referencing-domain-validation-options-with-for-each-based-resources really convoluted and not really functional.
