### ISSUE TITLE
add --show-urns option to pulumi up and pulumi preview

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi#5029]
The `--show-urns` is already available on `pulumi stack`.
But when you want to create a new (target) resource with `pulumi up --target URN`, you don't have the URN yet, and there is no way to get it easily (as far as i know)

**Comment by lukehoban** [comment]
How/where would you expect it to be display in `pulumi up` and `pulumi preview`?  Note that it is displayed as part of detailed diff - either in `details` or in `--diff`.  Though it will only show URNs for the subset of resources that it actually reports a change on - so may not be as useful as `pulumi stack --show-urns`.

Curious where you would like to have seen this surfaced to make this easier?

**Comment by boillodmanuel** [comment]
Hi Luke,

I was not aware that `pulumi preview --diff` was showing the URNs. It's what I was looking for 👍
This way, I can get all the URNs, for existing resources in `pulumi stack --show-urns` and for new resources in `pulumi preview --diff`. 
It will be even better if I can export all URNs in a single operation 😎

In my usecase, an issue in the azure terraform provider causes a resource to be replaced each time (which didn't work moreover). So, I have to select pulumi targets manually until this issue is fixed.

Thanks for your quick answer. You can close this issue if you want.

**Comment by stack72** [comment]
Hi all

Going to close this out as this seems to answer the question

Please let me know if this isn't the case

Paul
