### ISSUE TITLE
Update CLI integration tests to match error codes, not text

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#503]
Currently we validate error conditions with specific text. Instead we should compare against pre-defined error messages. Or possibly pre-defined exit codes.

e.g. 

```
// package cmd
const ErrNoRepository = "no repository"

// package testing
// Confirm errOutput contains the error message `ErrNoRepository`.
t.Contains(t, errOutput, cmd.ErrNoRepository)
```

Related but slightly different than https://github.com/pulumi/pulumi/issues/496. Adding to M0.9 so people are happy.

**Comment by joeduffy** [comment]
We've lived with this so far, and can fix it as we go if appropriate.
