### ISSUE TITLE
Support using `Output` values from `StackReference`s as resource names

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi#5035]
We commonly enough export arrays of resources that we need to loop over in other projects, and need to make use of the export resource names as part of the resources names in the other project.

For example, Project A may export a group of GKE clusters, and in Project B, we need to create resources for each of those clusters. We do this via looping the array. Today we have to use a random identifier, generally an incremented integer as the resource name because the `StackReference` has everything as `Output` and the the resource names all require pure `string`s.

While it would be nice to support using Resource1 as part of Resource2's name in the same project, I understand that may be even more difficult, so I'm just asking for support for this with existing resources, AKA, `StackReference`s.

**Comment by leezen** [comment]
Thanks for logging this -- the idea makes sense -- as does the desire to have any `Output` be able to take part in naming a resource.

In the meantime, if your outputs are non-secret, are you able to use `getOutputValue`/`requireOutputValue` for this as those return `Promise` which you can await to use as a prompt value for the resource name?

**Comment by thrixton** [comment]
Plus one for this, I have a similar issue where I have a consolidated StackConfig class where I grab multiple `StackReference`s and expose properties for each.

Changing to an async entrypoint and using an async init strategy works well, thanks @leezen .

```typescript
import { StackConfig } from "../0010-Common/Config/StackConfig";

// Async entry point
export = async () => {
//Export interface for strong(ish) typing
  const out: Partial<{
    componentName: any;
    imageTag: any;
    imageUri: any;
    imageName: any;
    ipServiceTarget: any;
  }> = {};

  const conf = await new StackConfig(pulumi.getStack()).init(true);

//.... snip

return out;
}
```

In the `StackConfig.init` method I async setup the instance backing the getter

```typescript
public async init(initK8sClusterConfig?: boolean): Promise<StackConfig> {
    await this.setupCommonConfig();

    if (initK8sClusterConfig) {
      await this.setupK8sClusterConfig();
    }

    return this;
  }
```

It's somewhat unwieldy, especially declaring the export interface, but it works well.

**Comment by tenwit** [comment]
Another aspect of this is for outputs that don't yet exist in the StackReference. Currently, if in @nesl247's use case, project B is accidentally run before project A, then the StackReference outputs don't exist. This fails asynchronously, which means that it's not possible to handle it in the Pulumi app (or at least, not easy, I haven't found a way.. maybe the Promise returned from requireOutputValue is properly rejected?). So it's not possible to (for example) deploy the parts of a project B that are not dependent on project A.
Perhaps a version of a StackReference that assumes that all outputs are present before the app starts would solve this problem? It then becomes the app developer's responsibility to know when to use StackReference and when to use SynchronouslyAccessibleStackReference.

**Comment by pgpx** [comment]
Could StackReference values just be non-Output values (same as config values)?  That would greatly simplify their use.

**Comment by Frassle** [comment]
> Could StackReference values just be non-Output values (same as config values)?

They can be. The `StackReference` type has `getOutput` and `getOutputValue` methods, the later returns a promise not an output, but it will throw if the value is a secret.

**Comment by pgpx** [comment]
> They can be. The StackReference type has getOutput and [getOutputValue](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#StackReference-getOutputValue) methods, the later returns a promise not an output, but it will throw if the value is a secret.

Thanks, though I'm using the Go SDK and that doesn't seem to have those methods yet.

**Comment by abhinav** [comment]
Hey folks, we recently added new methods to all SDKs to help with this. See [Stack reference output details](https://www.pulumi.com/blog/stack-reference-output-details/). Please let us know if that solves your problem.

Thanks!

**Comment by abhinav** [comment]
We've also added a [section to the stack reference docs](https://www.pulumi.com/docs/intro/concepts/stack/#reading-outputs-from-stack-references) documenting both getOutput and getOutputDetails, and when you might use one versus the other.

Closing issue as resolved.
