### ISSUE TITLE
Option to specify extra properties requiring replacement

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#5037]
A user wants to change the property `foo` of a resource from `bar` to `buzz`.

```ts
const r = new SomeResource("name", {
  foo: "bar"
});
```

Consider a case when such change can't be applied in-place (requires a new resource to be created). However, the provider doesn't happen to know about this requirement and the operation fails at runtime while trying to update the resource.

The SDK could provide an extra option `requireReplacement` to work around the issue:

```ts
const r = new SomeResource("name", {
  foo: "buzz"
}, { requireReplacement: ["foo"] });
```

**Comment by lukehoban** [comment]
Tracked in #6753.
