### ISSUE TITLE
Generate package registrations for SDKs.

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#5043]
https://github.com/pulumi/pulumi/pull/5041 introduces resource references. In order to rehydrate a resource reference during deserialization, each language SDK must be able to resolve the resource type in the URN to a constructor. We do this at package scope, which requires that each package register itself with the SDK during initialization. We need to update the code generators to ensure that this happens at package load time.

I'm not 100% sure how to achieve this with .NET, but for Node, Python, and Go, this should be straightforward.

Part of #2430.

**Comment by stack72** [comment]
This is now in place for DotNet / Python and NodeJS
