### ISSUE TITLE
Allow types in a package schema to refer to resources.

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#5045]
Just what it says on the tin. This allows resources to flow into and out of other resources and functions.

Part of #2430.

**Comment by pgavlin** [comment]
This also involves updating the code generators to generate appropriate references to the appropriate resource type. This should be as simple as extending the `Ref` support to allow paths of the form `#/resources/pkg:module:resource`.

**Comment by pgavlin** [comment]
Note that functions should not be able to reference resource types (either directly or transitively), as functions do not return `Output`s. The only exception will be for resource methods, where a resource type may be present in the `__self__` position.

**Comment by lblackstone** [comment]
> Note that functions should not be able to reference resource types

Do I need to enforce that during binding? It doesn't look like the current logic includes enough information to determine if this is the case, so I'd need to refactor a bit to pass that info along.

**Comment by pgavlin** [comment]
> Do I need to enforce that during binding? It doesn't look like the current logic includes enough information to determine if this is the case, so I'd need to refactor a bit to pass that info along.

Yes, this should be enforced when importing a schema.

**Comment by lblackstone** [comment]
Opened #5385 to track the function validity restrictions since it looks like this would require a fair bit of additional work, and isn't in the critical path for an initial implementation.
