### ISSUE TITLE
Allow azure resources to access sql server instead of providing a lot of ip addresses

### ISSUE THREAD

**Issue by ysmoradi** [pulumi/pulumi#5048]
I've followings:

```cs
appService.OutboundIpAddresses.Apply(ips =>
{
    foreach (string ip in ips.Split(','))
    {
        new FirewallRule($"app-service-{ip}", new FirewallRuleArgs
        {
            EndIpAddress = ip,
            ResourceGroupName = resourceGroup.Name,
            ServerName = sqlServer.Name,
            StartIpAddress = ip
        });
    }

    return (string?)null;
});
```

But I need following:

![image](https://user-images.githubusercontent.com/5352980/88453628-f41d0d80-ce7d-11ea-9bd2-6d811e990c58.png)

Thanks in advance

**Comment by leezen** [comment]
I believe you should be able to set start and end to `0.0.0.0` per https://docs.microsoft.com/en-us/rest/api/sql/firewallrules/createorupdate

**Comment by ysmoradi** [comment]
@leezen Interesting.
But by 
> Use value '0.0.0.0' to represent all Azure-internal IP addresses.

Does it mean other azure customers can see my sql database?
