### ISSUE TITLE
[Automation API] Handle nesting

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#5058]
There is nothing preventing a user from running a nested `stack.Up()` (one stack uses automation API to create another stack). This seems like a feature that will be highly comparable, so we should support it in a first-class way. 

One idea of thinking is the provide a `stack.ParentOp()` function that would perform the same operation as the containing stack. So if you update the outer stack, the inner stack also gets update. Then when you destroy the outer stack, the inner also gets destroyed without having to change any code.

**Comment by EvanBoyle** [comment]
Update: given that we don't run user code on destroy or refresh, there is no natural way to support this without building something provider like. For now, trying to use nested stacks will throw an error.

**Comment by infin8x** [comment]
Closing this based on @EvanBoyle's comment ☝🏻
