### ISSUE TITLE
Make changelogs better

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi#5063]
There are a few issues I find with the way changelogs are currently handled.

1. Releases are not used in GitHub. This should be where the changelogs are posted, as well as `CHANGELOG.md`, so that it's really easy to see what is going on in a new release.

2. The changelogs (regardless of where posted) should be more than the PR titles and a link to the PR. Most of the PRs do not actually show how to make use of the changes. This makes it difficult to make use of new functionality, as well as understand changes.

**Comment by leezen** [comment]
Starting with the latest release, we're trialing a process to review the changelog entries prior to release. As part of M52, I'll also take a look updating our process to publish the changes as part of the GitHub release.

**Comment by leezen** [comment]
Closing this out as we're now using `CHANGELOG_PENDING` and including release notes as part of releases in GitHub.

**Comment by nesl247** [comment]
Thanks for changing that @leezen.
