### ISSUE TITLE
F# lacks ability to set StackOptions and outputs

### ISSUE THREAD

**Issue by UnoSD** [pulumi/pulumi#5067]
The F# helpers `Pulumi.FSharp` do not have support for specifying `StackOptions`.

I tried changing then to code to a C#-style, using a class-style type inheriting from `Stack` and passing the `StackOptions` to the base constructor. That works, but I was forced to make all my outputs into properties of the type.

Following the C# example I then created a constructor that sets those properties, but I realised that partial object initialisation is not supported, therefore I can't set the stack outputs if I set `StackOptions` and vice-versa.

I will now try using a let binding to see if that works, but would be much appreciated if this was more F#-friendly and supported the options without imitating the C# structure.

Thank you

This causes a runtime exception: `System.InvalidOperationException: The initialization of an object or value resulted in an object or value being accessed recursively before it was fully initialized`

```fsharp
module UnoCash.Pulumi.Test

open Pulumi.FSharp
open System
open Pulumi

type bclList<'a> =
    System.Collections.Generic.List<'a>

let transform (opt : ResourceTransformationArgs) =
    //if onLocalMachine then
    opt.Options.IgnoreChanges <- bclList(["source"])
    
    ResourceTransformationResult(opt.Args, opt.Options) |> Nullable

type MyStack() as this =
    inherit Stack(
        StackOptions(
            ResourceTransformations =
                bclList([
                    ResourceTransformation(transform)
                ])))
        
    let infra (this : MyStack) =
        this.Hostname <- Output.Create("Example")
    do
        infra (this)
    
    member val Hostname = Output.Create("") with get, set

[<EntryPoint>]
let main _ =  
  Deployment.RunAsync<MyStack>()
            .GetAwaiter()
            .GetResult()
```

**Update**
OK, using mutable let bindings and changing the properties to use those as backing fields works, but it is ugly and boilerplate-y as hell.

**Comment by mikhailshilkov** [comment]
You should be able to use [this C# overload](https://github.com/pulumi/pulumi/blob/6ff94a18cf7b61cf4096cc6f8d716e42d0ad3416/sdk/dotnet/Pulumi/Deployment/Deployment_Run.cs#L74). We may want to expose it in the F# wrapper indeed.

**Comment by UnoSD** [comment]
thank you, @mikhailshilkov, the poor IntelliSense experience for F# struck again :), I didn't notice it was there.

Shall I leave this issue open? I still think Pulumi would benefit from a more idiomatic F# way of altering the stack options.

**Comment by mikhailshilkov** [comment]
yes, definitely. a PR is welcome :)
I'm also curious if you think we should expose `StackOptions` as-is or do something F#-y different.

**Comment by UnoSD** [comment]
> yes, definitely. a PR is welcome :)

that seems fair :), I'll try and get something together when I have a moment

> I'm also curious if you think we should expose StackOptions as-is or do something F#-y different.

I'll give you some feedback when I have a go at the PR; you have seen my work with the CE so, probably, you know how I feel about pushing every bit of boilerplate away :)

**Comment by UnoSD** [comment]
https://github.com/pulumi/pulumi/pull/5077

**Comment by emiliza** [comment]
Closing, this is fixed by https://github.com/pulumi/pulumi/pull/6376
