### ISSUE TITLE
Secret provider does not work with awskms + ARN

### ISSUE THREAD

**Issue by pkyosx** [pulumi/pulumi#5074]
According to [pulumi official doc](https://www.pulumi.com/docs/intro/concepts/config/) we can use the following command to choose our awskms.

`pulumi stack init my-stack --secrets-provider="awskms://arn:aws:kms:us-east-1:111122223333:key/1234abcd-12ab-34bc-56ef-1234567890ab?region=us-east-1"`

However, I got the following error message in response.

error: open secrets.Keeper: parse "awskms://arn:aws:kms:us-east-1:111122223333:key/1234abcd-12ab-34bc-56ef-1234567890ab?region=us-east-1": invalid port ":key" after host

It seems to be a [fixed issue by go-cloud](https://github.com/google/go-cloud/issues/2808) in Jun 6. 

Currently, our gocloud.dev module seems to be a May version(v0.19.1-0.20200517170643-46480dc2c3dd). Needs to evaluate if it can be updated to a newer version to support ARN in awskms secret provider. The online doc might also needs update to use empty host as example.

**Comment by andreujuanc** [comment]
Hi @leezen 
Is this going to be released soon, right? 
Thanks!

**Comment by stack72** [comment]
Hi @andreujuanc 

This was released quite a while ago already

Is this not working for you?

Paul

**Comment by andreujuanc** [comment]
Hi @stack72 
It failed with the same error as OP.
I'm running 2.15.6
Had to use the "short" keyid version.

**Comment by stack72** [comment]
Hi @andreujuanc 

Please can you tell me if you are doing something like this

"awskms://"

Or

"awskms:///"

Notice the triple /

**Comment by andreujuanc** [comment]
@stack72 
I just ran this in another project and it did not work:

```bash
pulumi stack init staging \
    --secrets-provider="awskms://arn:aws:kms:eu-west-1:ACCOUNT:key/ID"
```

Pulumi version: `v2.15.6`
package.json:
```json
"@pulumi/aws": "^3.20.0",
"@pulumi/awsx": "^0.22.0",
"@pulumi/pulumi": "^2.15.6"
```

**Comment by stack72** [comment]
Ok can you use /// before the arn

I am sure that's what is needed

**Comment by andreujuanc** [comment]
Will try, but:
https://www.pulumi.com/docs/intro/concepts/config/#aws-key-management-service-kms
![image](https://user-images.githubusercontent.com/360052/102285234-28c95880-3f36-11eb-8663-30d911eedadc.png)

**Comment by leezen** [comment]
@andreujuanc Thanks for pointing out the documentation issue. I've opened a PR (https://github.com/pulumi/docs/pull/4800) to fix that as the triple-slash is what the underlying API expects.

**Comment by andreujuanc** [comment]
Brilliant, it works.
Cool we found the docs issue for others to see.
Thanks a lot @stack72 @leezen
