### ISSUE TITLE
Can not create AWS Lambda function

### ISSUE THREAD

**Issue by WoHinDu** [pulumi/pulumi#5078]
I want to create a AWS Lambda function with Pulumi in Python. The code I use is the following:

```python
lambda_policy = iam.get_policy_document(statements=[{
    'actions': ['sts:AssumeRole'],
    'principals': [{
        "identifiers": ["lambda.amazonaws.com"],
        "type": "Service",
    }]
}])

lambda_role = iam.Role('lambda-role', assume_role_policy=lambda_policy.json)

lambda_function = lambda_.Function(
    'lambda_function',
    runtime='python3.7',
    role=lambda_role.id,
    handler='main.main',
    code=pulumi.FileArchive('main.py.zip'))
```

Unfortunately, I'm not able to do so. The code always generates an exception without an error message.

> aws:lambda:Function (lambda_function):
>     error: Error creating Lambda function: ValidationException:
>         status code: 400, request id: 8e2da49d-54d4-4a89-83e3-cecc77d6b156

Any idea what's going on? Is there a mistake on my side?

**Comment by leezen** [comment]
It's hard to say since the error is fairly generic, but it doesn't look like the policy you're giving the role would have the necessary permissions to execute a Lambda function? At a minimum, it should be able to write to CWLogs, e.g. include the managed `AWSLambdaBasicExecutionRole`

**Comment by WoHinDu** [comment]
Thanks for the quick reply!
I also tried to attach the BasicExecutionRole like this:

```python
iam.RolePolicyAttachment(
    'lambda-basic-execution',
    policy_arn='arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
    role=lambda_role.id)
```

The error remains the same.

**Comment by leezen** [comment]
One other thought: you want the `role` within your function constructor to be `lambda_role.arn` (the `id` will return the name).

**Comment by WoHinDu** [comment]
Thank you! 
That was the problem. Changing the `id` to `arn` solved the issue. 

I guess I'm not the first person who had such a problem. I would suggest to:

- update the documentation. It does not mention explicitly that the arn is required
- add a meaningful error message

**Comment by leezen** [comment]
Thanks for the suggestions and glad to hear you got the problem resolved!

**Comment by ffMathy** [comment]
I am having the same error. Not seeing any details as to why the `ValidationException` would happen. @leezen any plans to improve the error logging when an error 400 happens from AWS, so we can see the root cause? The response body would help a lot.

**Comment by user1689** [comment]
Same issue, but solved it by retry again and again without change anything
