### ISSUE TITLE
Panic when attempting to perform a `get` using an undefined StackOutput

### ISSUE THREAD

**Issue by benmccann** [pulumi/pulumi#5082]
I'm not really sure from this error what's wrong as there are no details. I'm happy to give any amount of access to my project that would be useful in debugging this

The error:

>panic: fatal: An assertion has failed
>
>goroutine 289 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/home/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assert(...)
	/home/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/sdk/v2/go/common/resource/plugin.(*provider).Read(0xc000bbcb40, 0xc00121e900, 0x5b, 0x0, 0x0, 0x0, 0xc001225410, 0xc32a4d, 0x4, 0x0, ...)
	/home/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/resource/plugin/provider_plugin.go:724 +0x1011
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*ReadStep).Apply(0xc001225470, 0x1, 0x1797f63, 0x23, 0xc0011a3e38, 0x3)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step.go:623 +0xfd
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).executeStep(0xc0010ec700, 0x7, 0x1b3a660, 0xc001225470, 0xc000be8fc0, 0xc000f9c778)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:271 +0x217
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).executeChain(0xc0010ec700, 0x7, 0xc00120ba10, 0x1, 0x1)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:221 +0xe6
github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).worker.func1(0xc0010ec700, 0x7, 0xc00120ba10, 0x1, 0x1, 0xc00121e960)
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:371 +0xc4
created by github.com/pulumi/pulumi/pkg/v2/resource/deploy.(*stepExecutor).worker
	/home/travis/gopath/src/github.com/pulumi/pulumi/pkg/resource/deploy/step_executor.go:368 +0x2e3

Code in `infra` project:
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";


const vpc = new awsx.ec2.Vpc("myproj", {});


const cluster = new awsx.ecs.Cluster("myproj", { vpc });
const securityGroupIds = cluster.securityGroups.map(g => g.id);


const dbSubnets = new aws.rds.SubnetGroup("dbsubnets", {
	subnetIds: vpc.privateSubnetIds,
});
const dbConfig = new pulumi.Config("database");
const db = new aws.rds.Instance("postgresdb", {
	engine: "postgres",

	instanceClass: "db.t2.micro",
	allocatedStorage: 20,

	dbSubnetGroupName: dbSubnets.id,
	vpcSecurityGroupIds: securityGroupIds,

	name: dbConfig.require("database"),
	username: dbConfig.require("username"),
	password: dbConfig.requireSecret("password")
});


const loadBalancer = new awsx.lb.ApplicationLoadBalancer(
    "app-load-balancer", { external: true, securityGroups: cluster.securityGroups, vpc });
// TODO: https, ssl certs, listen on 443, etc.
const listener = loadBalancer.createListener('web', { port: 80, external: true });


export const vpcId = vpc.id;
export const vpcPrivateSubnetIds = vpc.privateSubnetIds;
export const vpcPublicSubnetIds = vpc.publicSubnetIds;
export const dbEndpoint = db.endpoint;
export const albId = loadBalancer.loadBalancer.id;
export const albListenerId = listener.listener.id;
```

Code in app server project:
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";


const infra = new pulumi.StackReference("user/infra/prod");


// Load Balancer
const loadBalancerId = infra.getOutput("loadBalancerId");
const underlyingAwsLoadBal = aws.alb.LoadBalancer.get('underlyingAwsAppLoadBal', loadBalancerId);
const appLoadBal = new awsx.lb.ApplicationLoadBalancer('applicationLoadBalancer', {loadBalancer: underlyingAwsLoadBal});

// I plan to later create a service and have the load balancer route to it, but the project is crashing with just this code
```

`pulumi up` completed successfully on the `infra` project, but I get the error above when running `pulumi up` in the app server project.

**Comment by leezen** [comment]
One possibility is that in the implementation, it's expecting a `securityGroups` argument as well, which it's trying to look up when constructing `appLoadBal`:

`this.securityGroups = x.ec2.getSecurityGroups(this.vpc, name, args.securityGroups, { parent: this }) || [];`

I'm guessing it's that read that's failing?

**Comment by benmccann** [comment]
I don't think that's it. I commented out the last line and it's still failing. It seems the line that fails is:
```
const underlyingAwsLoadBal = aws.alb.LoadBalancer.get('underlyingAwsAppLoadBal', loadBalancerId);
```

**Comment by benmccann** [comment]
Is it because [`getOutput` returns `Output<any>`](https://github.com/pulumi/pulumi/blob/66bd3f4aa8f9a90d3de667828dda4bed6e115f6b/sdk/nodejs/stackReference.ts#L64) and [`LoadBalancer.get` takes a `pulumi.Input<pulumi.ID>`](https://github.com/pulumi/pulumi-aws/blob/130436cc6d3d7f7292cd63069fcb1d9fa029ca1e/sdk/nodejs/lb/loadBalancer.ts#L84)? Though if that's the case then I'm not really sure what the expected way is to accomplish what I'm trying to do.

**Comment by benmccann** [comment]
I figured it out. I renamed a variable in one project and not the other. `infra.getOutput("loadBalancerId")` should have been `infra.getOutput("albId")`. I'm going to leave this bug open though because I think the real issue here is Pulumi's error handling. I would have expected a usable error message, but what was printed just looks like gibberish to me

**Comment by leezen** [comment]
Thanks for the update. Agreed with the hard to debug error message.

**Comment by leezen** [comment]
Tracking in https://github.com/pulumi/pulumi/issues/5888
