### ISSUE TITLE
Creation of failover group for SQL servers elastic pool.

### ISSUE THREAD

**Issue by mcBIG** [pulumi/pulumi#5099]
Hi, i'm trying to create environment with database failover group.
We are creating databases within elastic pool.

To be able add database to failover group, accoding to [azure documentation](https://docs.microsoft.com/en-us/azure/azure-sql/database/failover-group-add-elastic-pool-tutorial?tabs=azure-portal)  i need to create elastic pool with identical name within secondary database, but this is not posible to do with pulumi. I'm getting this error. `  error: Duplicate resource URN 'urn:pulumi:dev::test::azure:core/resourceGroup:ResourceGroup$azure:sql/sqlServer:SqlServer$azure:mssql/elasticPool:ElasticPool::elpl'; try giving it a unique name `

You can replicate it with this script.
```javascript
import * as azure from "@pulumi/azure";


const resourceGroup = new azure.core.ResourceGroup("dbfailover", { location: "WestEurope" });

const primary = new azure.sql.SqlServer(
  "primary",
  {
    resourceGroupName: resourceGroup.name,
    version: "12.0",
    administratorLogin: "sqladmin",
    administratorLoginPassword: `s0mes3cr3t*`,
  },
  {
    parent: resourceGroup,
  }
);

const primaryElasticPool = new azure.mssql.ElasticPool(
    "elpl",
    {
        resourceGroupName: resourceGroup.name,
        serverName: primary.name,
        sku: {
            name: "BasicPool",
            tier: "Basic",
            capacity: 50,
        },
        perDatabaseSettings: {
            maxCapacity: 5,
            minCapacity: 0,
        },
        maxSizeGb: 4.8828125
    },
    { parent: primary }
);

const secondary = new azure.sql.SqlServer(
  "secondary",
  {
    resourceGroupName: resourceGroup.name,
    location: "northeurope",
    version: "12.0",
    administratorLogin: "sqladmin",
    administratorLoginPassword: `s0mes3cr3t*`,
  },
  {
    parent: resourceGroup,
  }
);

const secondaryElasticPool = new azure.mssql.ElasticPool(
    "elpl",
    {
        resourceGroupName: resourceGroup.name,
        serverName: secondary.name,
        location: "northeurope",
        sku: {
            name: "BasicPool",
            tier: "Basic",
            capacity: 50,
        },
        perDatabaseSettings: {
            maxCapacity: 5,
            minCapacity: 0,
        },
        maxSizeGb: 4.8828125
    },
    { parent: secondary }
);

const db1 = new azure.sql.Database(
  "db1",
  {
    resourceGroupName: primary.resourceGroupName,
    serverName: primary.name,
    elasticPoolName: primaryElasticPool.name
  },
  {
    parent: resourceGroup,
  }
);

const exampleFailoverGroup = new azure.sql.FailoverGroup(
  "tstfoggroup",
  {
    resourceGroupName: primary.resourceGroupName,
    serverName: primary.name,
    databases: [db1.id],
    partnerServers: [
      {
        id: secondary.id,
      },
    ],
    readWriteEndpointFailoverPolicy: {
      mode: "Manual",
    },
  }
);
```

**Comment by lukehoban** [comment]
>  `error: Duplicate resource URN 'urn:pulumi:dev::test::azure:core/resourceGroup:ResourceGroup$azure:sql/sqlServer:SqlServer$azure:mssql/elasticPool:ElasticPool::elpl'; try giving it a unique name`

You just need to give the second resource a different logical name.  In particular, change the second `elpl` to `elpl-secondary`.  More details on names at https://www.pulumi.com/docs/intro/concepts/programming-model/#names.

**Comment by mcBIG** [comment]
I get the problem with same name of resources. Problem is that i need to somehow force pulumi to use same name for both elastic pools.

If i create failover group with DB in elastic pool and on the secondare sql server is missing the elastic pool, i get this error. 
```
error: Error issuing create/update request for SQL Failover Group "tstfoggroup796f0a56" (Resource Group "r333-dbfailover5f8977b7", Server "primary21b6cba5"): sql.FailoverGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="FailoverGroupUnableToPerformGroupOperationOnDatabases" Message="The operation cannot be performed due to multiple errors." Details=[{"code":"40857","message":"Elastic pool not found for server: 'secondary6434b8cb', elastic pool name: 'elpl-prim8904e793'."}]
```

So my question is, is there any way how to create resources with same name or is it a limitation?

**Comment by mcBIG** [comment]
So the answer is [Controlled Naming](https://www.pulumi.com/blog/infrastructure-as-code-resource-naming/#controlled-naming).
Sorry, next time i'll spend more time with google.
