### ISSUE TITLE
[codegen] k8s resource tokens

### ISSUE THREAD

**Issue by sashu-shankar** [pulumi/pulumi#5101]
resource tokens aren’t being normalized correctly for k8s resources when generating from PCL

- [x] python - https://github.com/pulumi/pulumi/issues/5106
- [x] dotnet
- [x] go - https://github.com/pulumi/pulumi/issues/5108
- [x] node

**Comment by sashu-shankar** [comment]
PCL header: resource foo "kubernetes:core/v1:Namespace"

Incorrect Header for Golang: 
<img width="671" alt="Screen Shot 2020-08-04 at 2 56 42 PM" src="https://user-images.githubusercontent.com/67289341/89362093-d459c680-d681-11ea-8413-e41cb9a9d3d8.png">

**Comment by EvanBoyle** [comment]
Current C# program gen:
https://github.com/pulumi/kube2pulumi/blob/master/testdata/Namespace.cs#L8
Would expect something like:
https://github.com/pulumi/examples/blob/master/kubernetes-cs-guestbook/simple/Guestbook.cs#L27

**Comment by EvanBoyle** [comment]
PR with tests to fix has been merged. @lblackstone has helpfully annotated the tests with corrections: https://github.com/pulumi/pulumi/pull/5105

**Comment by EvanBoyle** [comment]
Note that there are a few outstanding bugs with yaml2pcl that @lblackstone discovered. The issues in #5105 are the result of valid PCL and still need to be fixed.

https://github.com/pulumi/kube2pulumi/issues/4
https://github.com/pulumi/kube2pulumi/issues/5
https://github.com/pulumi/kube2pulumi/issues/6

**Comment by EvanBoyle** [comment]
Thanks y'all! 🥳
