### ISSUE TITLE
[codegen/go] Reference types in external packages

### ISSUE THREAD

**Issue by albert-zhong** [pulumi/pulumi#5103]
Could we implement the ability to reference types from external packages when using the Go codegen? For example, if I create some `ObjectTypeSpec` with the follow `Properties` field:

```go
<...>.Properties["metadata"] = pschema.PropertySpec{
     TypeSpec: pschema.TypeSpec{
         Ref: "#/types/kubernetes:meta/v1:ObjectMeta",
     },
}
```

This properly generates a `metadata?: k8s.types.input.meta.v1.ObjectMeta` field in the NodeJS codegen. However the Go codegen can't process this. It fails a check on line 153 in `codegen/go/gen.go`:

```go
// If the package containing the type's token already has a resource with the
// same name, add a `Type` suffix.
modPkg, ok := pkg.packages[mod]
contract.Assert(ok)
```

@lblackstone told me this could possibly be done via the `Language` field in the schema. I've been trying this approach today and I haven't gotten it to work yet, so I'll again some more tommorow.

**Comment by lblackstone** [comment]
@albert-zhong Is this still needed?

**Comment by albert-zhong** [comment]
> @albert-zhong Is this still needed?

Yes. It's possible to get this to work by creating a fake `kubernetes:meta/v1:ObjectMeta` type, and manually setting its import to be the external package, but an automatic way to handle this would be nice.

**Comment by mikhailshilkov** [comment]
I'm going to assume this has been fixed since the issue was opened. We have packages like AWSX and EKS that do such references and they seem to be working well.
