### ISSUE TITLE
Broken upgrade to 2.8.0 for passphrase secrets provider

### ISSUE THREAD

**Issue by thrixton** [pulumi/pulumi#5104]
Per the title.

```
error: failed to decrypt encrypted configuration value '...': illegal base64 data at input byte 2
This can occur when a secret is copied from one stack to another. Encryption of secrets is done per-stack and
it is not possible to share an encrypted configuration value across stacks.
```

This works fine when running 2.7.1, upgrade to 2.8.0 and it immediately breaks.

There are all sorts of issues with the new options for copying stack config, changing providers as well. More to come.

**Comment by thrixton** [comment]
This is working with a default secrets provider

**Comment by stack72** [comment]
Hi @thrixton 

Apologies this has caused an error for you - I am working on fixing up this issue for the default secrets provider right now

Can you elaborate a little more on the following?

> There are all sorts of issues with the new options for copying stack config, changing providers as well. More to come.

Thanks

Paul

**Comment by thrixton** [comment]
Thanks for looking into this so quickly, and the great work @stack72 and team :)

Regarding other issues mentioned.

All these are with the 2.8.0 release.  

1. `pulumi stack change-secrets-provider passphrase` (on a `default` provider stack) 
  This does nothing, no `encryptionsalt` value is added

2. `pulumi stack init dev2 --copy-config-from dev --secrets-provider passphrase`
2.1 `pulumi config set test test --secret`
At this point, the `encryptionsalt` is removed from the config file, I'm not 100% sure what state it is in as it's part of a larger set of stacks sorry :(
> NOTE: `dev` stack is `passphrase` protected

Quite possibly this has already been fixed in vNext with the changes from #5110.

**Comment by stack72** [comment]
Hey @thrixton 

V2.8.1 is already on its way to being released

I've verified that we don't lose the encryption salt from the config files now and that we can change away from passphrase secret providers

The main question I have from you is, how badly has this affected your stack coding files and are they recoverable from source control? (I'm really hoping that the side effects are not terrible)

**Comment by thrixton** [comment]
Hi @stack72 , 

All is recoverable from SC yes, thanks.

The bigger issue maybe is that 2.8.0 / latest is picked up by any CI/CD extensions (Azure Devops specifically), and there doesn't appear to be a way to "pin" (correct me if i'm wrong here) to a known good version without manual install and configuration.

So I had to migrate back to the default secrets provider by rm'ing the stacks and recreating them, ok in this instance as I'm just working on getting CI/CD setup and don't have any non-disposable deployed stacks ATM.

Thanks for everything.

**Comment by stack72** [comment]
@thrixton 

:/ You would need to pin in the package.json file (or the appropriate package manager for your language runtime)

v2.8.1 is just finishing deploying - if you want to test this out on some experimental stacks to see if this solves your bug then I'd be hugely grateful. It won't be available on homebrew until they merge the PR though - https://github.com/Homebrew/homebrew-core/pull/59213

but you can install via curl - `curl -sSL https://get.pulumi.com | sh`

**Comment by thrixton** [comment]
Re pinning it in package.json, yes, but is the pipelines task independent of that?

![image](https://user-images.githubusercontent.com/4625987/89474316-9dda9380-d7c8-11ea-9a09-522b7a7e0a07.png)

E.g. when I use the pipeline task, it downloads the latest.

Re testing,

How can I get the binary for windows?

**Comment by stack72** [comment]
Try this guide

https://www.pulumi.com/docs/get-started/install/#installation-script

**Comment by thrixton** [comment]
Confirmed 2.8.1 original and the 2 additional issues 👍
