### ISSUE TITLE
pulumi watch panic: fatal: An assertion has failed

### ISSUE THREAD

**Issue by jonathan-willis** [pulumi/pulumi#5112]
The cli panics when running `pulumi watch` on a new stack that has not been `pulumi up`ed before.

Reproduce:
- `pulumi stack init`
- `pulumi watch`

If it is by design that `pulumi watch` should not create a new stack automatically but only update existing stacks, then a nicer message would be helpful.

This is with v2.8.0 pulumi cli version.

**Comment by stack72** [comment]
Hi @jonathan-willis 

Apologies this happened - just to ask a few questions here:

1. Is this something you tried before and just started happening?

2. What backend are you using (to help recreate) - is it the SaaS and therefore using the default secrets provider?

3. What did you want the watch command to do for you?

Thanks

Paul

**Comment by jonathan-willis** [comment]
Hi @stack72 

1. I had never tried the `pulumi watch` command before but have done similar things using inotify tooling.
2. I was using S3 as a backend and I had no secrets so I guess that was the default secrets provider.
3. I suppose ideally it would create the stack if it didn't exist or update it if it did exist. Or at the very least present a message telling me what I did wrong and the best way to proceed.

**Comment by stack72** [comment]
Hi @jonathan-willis 

So I just tried the following steps:

* pulumi new typescript -y
* pulumi stack init dev2
* pulumi watch

I don't get a panic

Can you give me some output of the panic to try and help here?

Thanks

Paul

**Comment by stack72** [comment]
Ping @jonathan-willis :)

**Comment by jonathan-willis** [comment]
`goroutine 37 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assert(...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v2/backend/filestate.GetLogsForTarget(0xc00050c2a0, 0xc000111340, 0x0, 0x0, 0x7f0bd50d11c8, 0x2937318, 0xc00050c2a0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/filestate/backend.go:631 +0x28a
github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).GetLogs(0xc0000981e0, 0x1b27820, 0xc000044138, 0x1b40ca0, 0xc00045f9b0, 0xc00058e420, 0x7f0bd50d11c8, 0x2937318, 0xc000111340, 0x0, ...)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/filestate/backend.go:625 +0xf3
github.com/pulumi/pulumi/pkg/v2/backend.Watch.func1(0x1b4b240, 0xc0000981e0, 0x1b27820, 0xc000044138, 0x1b40ca0, 0xc00045f9b0, 0xc0005de580, 0xc000111340)
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/watch.go:47 +0x231
created by github.com/pulumi/pulumi/pkg/v2/backend.Watch
        /home/travis/gopath/src/github.com/pulumi/pulumi/pkg/backend/watch.go:44 +0x16c
`
My instructions above to reproduce weren't quite right:
`
pulumi 
`

**Comment by stack72** [comment]
perfect - looks like you are using the local filestate backend - that's what I was missing?

**Comment by jonathan-willis** [comment]
I was actually originally using the s3 cloud backend but I switched to the file backend in order to reproduce it and get the panic msg for you and not affect my current work.
