### ISSUE TITLE
`history` command should be a sub-command under `stack`

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5134]
1. `pulumi history` should be `pulumi stack history` to be consistent with other stack-specific commands.
1. The help text for `pulumi history` should be updated. It currently says `Update history for a stack`, but has no _update_ capabilities.

```
clstokes % pulumi history --help
Update history for a stack

This command lists data about previous updates for a stack.

Usage:
  pulumi history [flags]
...
```

**Comment by stack72** [comment]
This test should probably be "History of stack updates" ?

**Comment by clstokes** [comment]
Looks like we're inconsistent between "Display ...", "Show ...", and "Print ...", but I think a more _action_ statement like "Display history for a stack" would be best.

**Comment by stack72** [comment]
Moving the command would be a breaking change - we should actually duplicate the command under the stack command and then we would add a deprecated to the existing use case.

We would then need to remove this from v3.0.0
