### ISSUE TITLE
Python: Consider supporting `<Resource>Args` classes for creating resources

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5146]
Python resources are created by passing inputs directly to a resource's `__init__` method, e.g.:

```python
bucket = aws.s3.Bucket("bucket",
    acl="private",
    tags={
        "Environment": "Dev",
        "Name": "My bucket",
    })
```

This approach is different from other Pulumi languages, which have a separate type (e.g. `BucketArgs`) to pass the inputs to the resource's constructor.

A customer asked if we'd consider supporting `<Resource>Args` for Python. The primary reason is to have an object "bag" that can be used to hold/manipulate/validate/pass-around inputs _before_ creating the resource. It'd also provide consistency with all the other Pulumi languages.

We could add optional support for this in a compatible way via an `__init__` [overload](https://docs.python.org/3/library/typing.html#typing.overload):

```python
class Bucket(CustomResource):
    @overload
    def __init__(__self__, args: Optional[BucketArgs] = None, opts: Optional[pulumi.ResourceOptions] = None)
        ...
    @overload
    def __init__(__self__,
                 resource_name,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 acceleration_status: Optional[pulumi.Input[str]] = None,
                 acl: Optional[pulumi.Input[str]] = None,
                 ...)
```

And usage:

```python
args = aws.s3.BucketArgs(
    acl="private",
    tags={
        "Environment": "Dev",
        "Name": "My bucket",
    })
bucket = aws.s3.Bucket("bucket", args)
```

**Comment by KentShikama** [comment]
Python doesn't support having multiple `__init__` functions in a class. If you provide multiple, CPython will just ignore the earlier ones. You could support a `fromArgs` factory like follows:

```
@classmethod
def fromArgs(cls, resource_name, args, opts):
    return cls(resource_name, opts, args.foo, args.bar, ...)

def __init__(__self__, resource_name, ...
```

Usage:

```
args = aws.s3.BucketArgs(
    acl="private",
    tags={
        "Environment": "Dev",
        "Name": "My bucket",
    })
bucket = aws.s3.Bucket.fromArgs("bucket", args)
```

**Comment by justinvp** [comment]
> Python doesn't support having multiple `__init__` functions in a class. If you provide multiple, CPython will just ignore the earlier ones.

Yep, the last one is the one that will be used at runtime, any earlier ones marked as `@overload` are for the benefit of type checkers / IDEs. From https://docs.python.org/3/library/typing.html#typing.overload:

> The `@overload` decorator allows describing functions and methods that support multiple different combinations of argument types. A series of `@overload`-decorated definitions must be followed by exactly one non-`@overload`-decorated definition (for the same function/method). The `@overload`-decorated definitions are for the benefit of the type checker only, since they will be overwritten by the non-`@overload`-decorated definition, while the latter is used at runtime but should be ignored by a type checker.

---

> You could support a `fromArgs` factory like follows:

Thanks for the suggestion! The factory may be a cleaner way of exposing this (though, less consistent with other Pulumi languages).

**Comment by KentShikama** [comment]
> any earlier ones marked as @overload are for the benefit of type checkers / IDEs

Ah ok. I hadn't considered mocking an overload as I thought it wouldn't be worth the cruft that it would add to the internals. I tried implementing it for a DigitalOcean `Domain` class I use, and it adds less explicit complexity than I expected but still more than what a `fromArgs` would involve. Basically, it would involve implementing a subset of multiple dispatch. The complexity could probably be moved to a class decorator.

```
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Dict, List, Mapping, Optional, Tuple, Union, overload
from dataclasses import dataclass
from . import _utilities, _tables

__all__ = ['Domain', 'DomainArgs']

@dataclass
class DomainArgs:
    ip_address: Optional[pulumi.Input[str]]
    name: Optional[pulumi.Input[str]]


class Domain(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                resource_name,
                args: Optional[DomainArgs] = None,
                opts: Optional[pulumi.ResourceOptions] = None):
        ...

    @overload
    def __init__(__self__,
                resource_name,
                opts: Optional[pulumi.ResourceOptions] = None,
                ip_address: Optional[pulumi.Input[str]] = None,
                name: Optional[pulumi.Input[str]] = None,
                __props__=None,
                __name__=None,
                __opts__=None):
        ...

    def __init__(__self__, resource_name, *args, **kwargs):
        def _get_input_args(args, args_name):
            if len(args) >= 1:
                input_args = args[0]
                return input_args, args[1:]
            else:
                input_args = kwargs.get(args_name)
                return input_args, args
        input_args, args_tail = _get_input_args(args, "args")
        opts_args, args_tail = _get_input_args(args_tail, "opts")
        is_input_args = isinstance(input_args, DomainArgs)
        is_opts_args = isinstance(opts_args, pulumi.ResourceOptions)
        if not args_tail and (is_input_args or is_opts_args):
            __self__._internal_init__(resource_name, opts_args, input_args.ip_address, input_args.name)
        else:
            __self__._internal_init__(resource_name, *args, **kwargs)

    def _internal_init__(__self__,
                         resource_name,
                         opts: Optional[pulumi.ResourceOptions] = None,
                         ip_address: Optional[pulumi.Input[str]] = None,
                         name: Optional[pulumi.Input[str]] = None,
                         __props__=None,
                         __name__=None,
                         __opts__=None):
    # The rest of the class is the same
```

Usage

```
    domain_args = do.DomainArgs(name=domain_name, ip_address="<REDACTED>")
    domain = do.Domain(
        "do-domain",
        domain_args)
```

**Comment by KentShikama** [comment]
See https://github.com/KentShikama/pulumi/commit/cb81a568bf1e9523d34f54ef4420c36da46ff3a3 for corresponding generator code.

**Comment by justinvp** [comment]
The codegen change has been merged. Now we'll need to adopt the change in the providers.

**Comment by stack72** [comment]
We need to roll this out to:

- [ ] pulumi-kubernetes
- [ ] pulumi-azure-native
- [ ] pulumi-aws
- [ ] pulumi-azure
- [ ] pulumi-azuread
- [ ] pulumi-gcp
- [ ] pulumi-random
- [ ] pulumi-vsphere
- [ ] pulumi-openstack
- [ ] pulumi-f5bigip
- [ ] pulumi-equinix-metal
- [ ] pulumi-cloudflare
- [ ] pulumi-newrelic
- [ ] pulumi-linode
- [ ] pulumi-digitalocean
- [ ] pulumi-mysql
- [ ] pulumi-postgresql
- [ ] pulumi-gitlab
- [ ] pulumi-datadog
- [ ] pulumi-dnsimple
- [ ] pulumi-tls
- [ ] pulumi-vault
- [ ] pulumi-kafka
- [ ] pulumi-consul
- [ ] pulumi-okta
- [ ] pulumi-signalfx
- [ ] pulumi-aiven
- [ ] pulumi-fastly
- [ ] pulumi-docker
- [ ] pulumi-rabbitmq
- [ ] pulumi-cloudamqp
- [ ] pulumi-spotinst
- [ ] pulumi-alicloud
- [ ] pulumi-rancher2
- [ ] pulumi-mailgun
- [ ] pulumi-keycloak
- [ ] pulumi-kong
- [ ] pulumi-github
- [ ] pulumi-mongodbatlas
- [ ] pulumi-auth0
- [ ] pulumi-pagerduty
- [ ] pulumi-azuredevops
- [ ] pulumi-ns1
- [ ] pulumi-hcloud
- [ ] pulumi-civo
- [ ] pulumi-wavefront
- [ ] pulumi-akamai
- [ ] pulumi-splunk
- [ ] pulumi-venafi
- [ ] pulumi-cloudinit
- [ ] pulumi-opsgenie

**Comment by stack72** [comment]
All TF based providers have been rolled with this new code :)
