### ISSUE TITLE
StackReference to stack with a secret config set throws: "failed to decrypt: incorrect passphrase"

### ISSUE THREAD

**Issue by jshearer** [pulumi/pulumi#5151]
**EDIT:** An hour later and some digging, what I discovered is that even if you have _no_ secret outputs, Pulumi will sometimes identify certain resource outputs that should be secret, and will serialize them as encrypted. This causes problems when deserializing via StackReference _if you use different passphrases between projects_. 

---

I am using the Google cloud storage state backend. I have three projects, with their corresponding stacks: `core.live`, `hydra.live`, and `metadata.master`. In the metadata project, I have 

```typescript
import * as pulumi from "@pulumi/pulumi";

const core_output = new pulumi.StackReference("core.live");
export const gcpRepoName = core_output.requireOutput("repoName");
export const zoneName = core_output.requireOutput("runZoneName");

const hydra_output = new pulumi.StackReference("hydra.live");
export const hydraPrivateUrl = hydra_output.requireOutput("hydraPrivateUrl");
```

When I ran this before adding the StackReference to `hydra.live`, things worked. `repoName`, `runZoneName`, etc. were read properly from the `core_output` stack ref. Now, when adding the `hydra_output` stack ref, `pulumi up`, `pulumi preview` both fail:

```
pulumi preview -v=8
warning: Pulumi will not be able to print a statefile permalink using these credentials. Neither a GoogleAccessID or PrivateKey are available. Try using a GCP Service Account.
Previewing update (metadata.master):
     Type                             Name                      Plan     Info
     pulumi:pulumi:Stack              metadata-metadata.master           1 error
     └─ pulumi:pulumi:StackReference  hydra.live                         1 error
 
Diagnostics:
  pulumi:pulumi:Stack (metadata-metadata.master):
    error: preview failed
 
  pulumi:pulumi:StackReference (hydra.live):
    error: Preview failed: decrypting secret value: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase
```

This happens even when I remove the call to `.requireOutput`, purely having 
```typescript
const hydra_output = new pulumi.StackReference("hydra.live");
```

causes the failure.

I recently upgraded from `2.7` to `2.8.2`, and added the `hydra_output` stack ref after the upgrade so I'm not sure if this would have worked with `2.7` or not. I found [this](https://github.com/pulumi/pulumi/issues/2744) issue which seems kind of related, but in this case _none_ of the outputs of `hydra.live` are secrets...

I looked into the stack state file in gcs, and the outputs are clearly there in plaintext as I would expect:
```json

            "resources": [
                {
                    "urn": "urn:pulumi:hydra.live::hydra::pulumi:pulumi:Stack::hydra-hydra.live",
                    "custom": false,
                    "type": "pulumi:pulumi:Stack",
                    "outputs": {
                        "hydraPrivateUrl": "...",
                        "hydraPublicUrl": "..."
                    }
                },
                {
                    "urn": "urn:pulumi:hydra.live::hydra::pulumi:providers:pulumi::default",
                    "custom": true,
                    "id": "10a03ca2-474c-41c5-958f-11fe6f85f0a4",
                    "type": "pulumi:providers:pulumi"
                }
```

**Comment by leezen** [comment]
This is a limitation of the way stack references work in that they expect the same secrets provider. Making this configurable is tracked in https://github.com/pulumi/pulumi/issues/4665
