### ISSUE TITLE
Inconsistency in required environment variables when interacting with hashivault

### ISSUE THREAD

**Issue by elsesiy** [pulumi/pulumi#5152]
Using the `pulumi-vault` provider the following environment variables are used:
```
VAULT_ADDR
VAULT_TOKEN
```

Using the `hashivault` secrets engine, the env vars differ for no apparent reason:
```
VAULT_SERVER_URL
VAULT_SERVER_TOKEN
```

An example workflow usually looks as follows, e.g. with Okta:
1. `export VAULT_ADDR=https://myvault:8200`
2. `export VAULT_TOKEN=$(vault login -token-only -method=okta username=jdoe)`
3. `vault xyz action`

Due to the current implementation the workflow becomes a bit more tedious:
1. `export VAULT_ADDR=https://myvault:8200`
2. `export VAULT_TOKEN=$(vault login -token-only -method=okta username=jdoe)`
3. `export VAULT_SERVER_URL=$VAULT_ADDR`
4. `export VAULT_SERVER_TOKEN=$VAULT_TOKEN`
5. `pulumi preview`

I understand that the implementations for the secrets provider and the vault api differ a bit and the difference comes from underlying SDK [here](https://gocloud.dev/howto/secrets/#vault).

Is it possible that the secrets the implementation for the secrets provider can account for both environment variable naming conventions?

Thanks!

**Comment by stack72** [comment]
Closed via #7204
