### ISSUE TITLE
Make it possible to use custom S3 endpoint url for cloud-backend

### ISSUE THREAD

**Issue by bjornbugge** [pulumi/pulumi#5155]
We have all our infrastructure on DigitalOcean, including various S3 spaces.  I'm investigating Pulumi to see how we can benefit from it and I wanted to initially store our state in one of our own S3 spaces.  However, as far as I can see it's not possible to use a non-AWS S3 service at the moment:

If I create a space `mySpace` in region `ams3` and do a `pulumi login s3://mySpace.ams3.digitaloceanspaces.com` then Pulumi attempts to connect to https://s3.ams3.amazonaws.com/mySpace.ams3.digitaloceanspaces.com/.pulumi/stacks/dev.json  The region string and AWS credentials are picked up from my `~/.aws/credentials` file, however, I can't seem to find a way to change the default endpoint to something else. 
It would be very useful if it was possible to change this, for example via an environment variable like `AWS_ENDPOINT=ams3.digitaloceanspaces.com`.

**Comment by lukehoban** [comment]
This is largely what is being tracked in https://github.com/pulumi/pulumi/issues/3592. Would you mind adding relevant details of the specific Digital Ocean scenario here to that issue so we can track together?
