### ISSUE TITLE
Support `--preview` for `pulumi destroy` when targeting Pulumi.com 

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#516]
Today there's no support in Pulumi.com for doing a preview of a destroy operation. In the local case, we do support this, so we should add support here.

**Comment by chrsmith** [comment]
In an odd reversal, the Pulumi Service can support this previews of refreshes, imports, and destroys. However, the CLI no longer supports them. I'll log a bug in the `pulumi/pulumi` repo to consider adding `--preview` back. As it would be nice to _just_ run the preview and see the results for refreshes and destroys.
