### ISSUE TITLE
Remote state in S3

### ISSUE THREAD

**Issue by mmdriley** [pulumi/pulumi#517]
For our various "durable" stacks -- production, staging, testing -- we're storing checkpoint files in S3 and writing shell scripts to shuttle them back and forth. These shell scripts are necessary for where we are right now, but they don't accrue much value to customers or to the product.

At some point we're probably going to move these stacks to PPCs, which will deal with state management and concurrency for us. Paying customers will likewise use PPCs. That solution won't work for open-source/fire-and-forget users, though, and it raises some bootstrapping/circularity questions for us around bringing up new service and PPC instances.

This issue tracks adding state management on S3 as a first-class concept in Pulumi. In the limit, this could end up looking like the [Terraform S3 backend](https://www.terraform.io/docs/backends/types/s3.html).

At the very least, I'm sure @chrsmith would be happy to see the bulk of this logic written in Go rather than in bash.

**Comment by ksiadz** [comment]
Do you plan to implement this? I am in the middle of choice for new project. Would like to switch from terraform and it's template language, but not being able to manage state on my own is kind of deal breaker.

**Comment by joeduffy** [comment]
Short answer, yes, absolutely.

There is a dupe issue at https://github.com/pulumi/pulumi/issues/1966 that is still open and which we've been using to track this.

Note that you can manage your own state files already using the "local backend" (`pulumi login --local`); more info is available at https://pulumi.io/reference/state.html#to-the-filesystem-backend.

We have been working on a roadmap and will be sure that this makes it into that, so everybody knows when we plan to tackle it. In the meantime, community contributions are *very* welcome.
