### ISSUE TITLE
Python docgen: Use PyNameLegacy when emitting property name of nested types

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5175]
https://github.com/pulumi/pulumi/pull/4918 updated `PyName` to properly handle acronyms, and introduced `PyNameLegacy` to maintain the previous behavior for the names emitted in the mapping tables.

We need to update the docgen to use `PyNameLegacy` when output Python docs for nested types.

Note: This is just a point-in-time issue. Once all the providers have been updated to have `UsesIOClasses`, we should emit the correct name returned by `PyName` for the nested types.

**Comment by mikhailshilkov** [comment]
I believe this is now irrelevant, see https://github.com/pulumi/pulumi/pull/9870 that removes `PyNameLegacy`
