### ISSUE TITLE
generatePythonPropertyCaseMaps slows down doc generation

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#5184]
For a new large-ish provider API reference docs generation takes ~25 minutes. Apparently, if I remove [this line](https://github.com/pulumi/pulumi/blob/f8d929d197b3cc5b4a8dbac5bf207587e93fcb2c/pkg/codegen/docs/gen.go#L1781) with Python casing mapping, the time drops to 1 minute.

**Comment by stack72** [comment]
FWIW, I am greater than 2 hours now to regenerate the GCP provider...

**Comment by mikhailshilkov** [comment]
@pgavlin Do you remember why we call `pkg.ImportLanguages` for every property in https://github.com/pulumi/pulumi/blob/f8d929d197b3cc5b4a8dbac5bf207587e93fcb2c/pkg/codegen/python/doc.go#L135 ?

Isn't this single import enough https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/gen.go#L1757 ?

**Comment by mikhailshilkov** [comment]
Yes, that's the problem:
![image](https://user-images.githubusercontent.com/1454008/90526145-53fe8f80-e170-11ea-89a8-edc697112ca0.png)

**Comment by pgavlin** [comment]
> @pgavlin Do you remember why we call `pkg.ImportLanguages` for every property in https://github.com/pulumi/pulumi/blob/f8d929d197b3cc5b4a8dbac5bf207587e93fcb2c/pkg/codegen/python/doc.go#L135 ?
> 
> Isn't this single import enough https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/gen.go#L1757 ?

The code that's in there is the equivalent of the original code prior to the `ImportLanguages` API. Because the first function you're referencing is exported, I didn't want to make a behavioral change at that time. I think it's fine to do so now.

Do we know why this slowed down so much recently? Or has this been slow since that port?

**Comment by mikhailshilkov** [comment]
> Do we know why this slowed down so much recently? Or has this been slow since that port?

I don't know. @stack72 do you remember a moment when generation started being slow, if there was one?
