### ISSUE TITLE
Bug: deletion of ACM Certificate gets stuck when used with an ApiGateway DomainName and Route53 CNAME Record

### ISSUE THREAD

**Issue by mikerochip** [pulumi/pulumi#5186]
Title says it all.

## Expected Behavior

If I provision an ACM certificate pointing to domain foo.com, add a Route53 CNAME record for foo.com, then change the certificate to point to bar.com, pulumi up should be able to handle that just fine.

## Current Behavior

pulumi up hangs indefinitely when trying to delete the ACM certificate for the old domain. If you go to the AWS console and try to delete the certificate, you get an error message saying that it's still being used in a Route53 record.

## Steps to Reproduce

1. Create an ACM certificate for DomainName "foo.com"
1. Attach it to an API Gateway DomainName
1. Create a Route53 CNAME record for that domain
1. pulumi up, everything works
1. Back in your code, change the DomainName to "bar.com"
1. pulumi up
--> pulumi CLI hangs when trying to delete the ACM certificate

## Context (Environment)

I used Pulumi to provision an ACM cert and validation, R53 zone and cname record, and APIG DomainName for one of my hosted zones. I then wanted to change the zone and ran into this bug.

Here's the part of my project where I made this discovery:

https://github.com/mikerochip/waker-upper/blob/master/WakerUpper.Infra/DomainResources.cs

Specifically, I changed the domainZoneId in the config, but effectively that meant changing the domain name.

**Comment by leezen** [comment]
If you make the API Gateway domain name depend on the validation, does this go away? I suspect what might be happening is that the program isn't waiting for the validation of the new cert, which means the old cert is still the one attached and being used.

**Comment by mikerochip** [comment]
I like the thinking, but I don't think that's the problem. I think the problem is the fact that there are implicit dependencies on the AWS side and Pulumi (or maybe it's TF) isn't aware of that.

The DomainName is already dependent on the validation, unless I'm using Pulumi improperly:

```C#
            Stack.DomainCertificateArn = validation.CertificateArn;
```

```C#
            DomainName domainName = new DomainName("DomainName", new DomainNameArgs
            {
                Domain = Stack.DomainName!,
                RegionalCertificateArn = Stack.DomainCertificateArn!,
                EndpointConfiguration = new DomainNameEndpointConfigurationArgs
                {
                    Types = "REGIONAL",
                },
                SecurityPolicy = "TLS_1_2",
            });
```

**Comment by mikerochip** [comment]
The problem seems like it's Pulumi not being aware that it can't destroy the cert without first destroying the R53 records, again because of the implicit dependency of the R53 records on the cert. Is this a case where I can add an explicit DependsOn for the R53 record on the cert?

**Comment by leezen** [comment]
Yes, earlier when I mentioned having the dependency, I meant using a `DependsOn`

As you note, the dependency on the _cert_ is there, but not on the cert _validation_:
`CertificateValidation validation = new CertificateValidation(...`

I would expect to see a `DependsOn` with `validation` as a resource since you need the cert validated before you want to attach it to the APIGW.

**Comment by mikerochip** [comment]
No, it's dependent on the validation. I really don't think that's the problem and I fear we're getting off topic a bit.

Here are the lines showing it's dependent on the validation:

```
Stack.DomainCertificateArn = validation.CertificateArn;
RegionalCertificateArn = Stack.DomainCertificateArn!,
```

Might want to take a second look at this file: https://github.com/mikerochip/waker-upper/blob/master/WakerUpper.Infra/DomainResources.cs

**Comment by mikerochip** [comment]
My understanding of Pulumi is that having an output connected to an input like this will create the dependency, but maybe that's not how Pulumi works?

**Comment by leezen** [comment]
Sorry! I missed that while looking through the file. Thanks for pointing that out. Having an output connected to an input does create the dependency as you said. Sounds like we'll need to dig a little deeper here to figure out what's going on. Appreciate your patience.

**Comment by mikerochip** [comment]
Hey, no worries, I really appreciate the quick help and responses. FWIW, this fixed the problem for me:

https://github.com/mikerochip/waker-upper/commit/34860c2c56f30476d24bb16876204b9e87679d7a

I tried changing my domain a couple times with that fix, and pulumi up ran both times just fine.

I went ahead and clarified the title and description to highlight the fact that the problematic part is the fact that the CNAME record has an implicit dependency on the cert due to the fact that the CNAME record is pointing to the same domain name as the cert.

So, I'm now sort of uncertain if this is a bug or pulumi just needs a good sample of how to properly handle domain name provisioning because having to add the DependsOn for the CNAME record on the certificate is really not obvious.

**Comment by leezen** [comment]
Thanks for the follow-up. This isn't really a pulumi bug since the dependency graph cannot know about this dependency except to do what you've done by using `DependsOn` (which is exactly what it's for). I think I missed this on my end because I didn't actually realize AWS modeled the dependency between ACM and Route 53.
