### ISSUE TITLE
[python] pulumi.export exports only one resource

### ISSUE THREAD

**Issue by SebastianGogoasa** [pulumi/pulumi#5215]
In the example below I am trying to create three individual S3 buckets and I'd like to get the output of these buckets but for some reason I can only get one, in this case the last one. If I use a `break` then I get the first one, this is expected.

#### Version
```
Pulumi: v2.9.0
Python: 3.8.5
```

#### Code
```
import pulumi
from pulumi_aws import s3

# General variables
resource_region                 = "eu-west-2"

# Variables
a_bucket_prefix                 = "my-bucket-prefix"
a_bucket_name                   = "something"
bucket_environments             = ["production", "staging", "development"]

# Loop through each environment
for each_bucket_environment in bucket_environments:

    # Generating bucket names based on variables and environment
    bucket_name = a_bucket_prefix + "-" + a_bucket_name + "-" + each_bucket_environment

    # Creating the S3 buckets
    bucket_name = s3.Bucket(

        bucket_name,
        acl                     = "private",
        region                  = resource_region,
        force_destroy           = False,

    )

    # Export the name of each S3 bucket
    pulumi.export('bucket_name', bucket_name.id)
```

## Expected Behavior

I would expect that all three resources to be exported like:
```
❯ pulumi stack output

Current stack outputs (3):
    OUTPUT       VALUE
    bucket_name: "my-bucket-prefix-something-production-xxxxxxx"
    bucket_name: "my-bucket-prefix-something-staging-yyyyyyy"
    bucket_name: "my-bucket-prefix-something-development-e420f7a"
```

## Current Behavior

Currently only one resource gets exported, the last resource:
```
❯ pulumi stack output

Current stack outputs (1):
    OUTPUT       VALUE
    bucket_name: "my-bucket-prefix-something-development-e420f7a"
```

## Steps to Reproduce

Code above.

**Comment by leezen** [comment]
The behavior you've described is 'by design.' Different stack outputs should have different names. The name is the key used for stack references and for distinguishing the outputs. I would suggest prepending/appending something to the key to make it unique within the loop.

**Comment by AkhterAli** [comment]
I don't quite find this answer acceptable.  OP is clearly creating three different each with its respective name in a single stack.  Outputting only a single bucket would also imply that the stack backend only manages the single s3 bucket created rather than the three.  This would also mean that any modification applied after the bucket creation within a loop would not apply to any other bucket apart from the very last one.

**Comment by leezen** [comment]
@AkhterAli The name is a unique key, so this is what I meant in terms of "by design." In terms of looping through multiple things for output, one could either construct an output that joins those things together as the value for a single key or vary the key itself, e.g. `bucket_name_{i}`
