### ISSUE TITLE
Add structured output to Stack.Up

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#5218]
Right now `Stack.Up` returns limited output (stdout, stderr, Outputs, Summary). This is mainly due to the fact that `pulumi up` doesn't support a `--json` flag. We should add a `--json` flag to pulumi up, and then consume this from the Automation API. 

Ideally, we should be able to consume this output in both sync and streaming contexts.

**Comment by lukehoban** [comment]
Shared one approach we could take to this in #5754 which builds on the `--event-log` flag that already exists on the CLI.

**Comment by EvanBoyle** [comment]
I had imagined streaming JSON events incrementally as many of the `go` tools do. Good find, `--event-log` offers a code path to follow and get things started.

**Comment by komalali** [comment]
Closing command-based issues for language-based issues 
* #6441 
* #6442 
* #6443 
* #6444
