### ISSUE TITLE
Add structured output to Stack.Destory

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#5219]
Right now `Stack.Destroy` returns limited output (stdout, stderr, Summary). This is mainly due to the fact that `pulumi destroy` doesn't support a `--json` flag. We should add a `--json` flag to pulumi destroy, and then consume this from the Automation API.

**Comment by komalali** [comment]
Closing command-based issues for language-based issues 
* #6441 
* #6442 
* #6443 
* #6444
