### ISSUE TITLE
Add structured output to Stack.Refresh

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#5220]
Right now `Stack.Refresh` returns limited output (stdout, stderr, Summary). This is mainly due to the fact that `pulumi refresh` doesn't support a `--json` flag. We should add a `--json` flag to pulumi refresh, and then consume this from the Automation API.

**Comment by komalali** [comment]
Closing command-based issues for language-based issues 
* #6441 
* #6442 
* #6443 
* #6444
