### ISSUE TITLE
Pulumi Should retain comments in Stack Config

### ISSUE THREAD

**Issue by JasonWhall** [pulumi/pulumi#5235]
When running Pulumi commands like `pulumi up` or `pulumi preview`  when using Azure KeyVault as it's Secrets Provider for the selected stac, comments in the relevant config file are removed. It would be useful to retain these comments as config files could be edited by hand and checked into source control with these comments to provide information to other users about the reasoning for the config value. When not using the `--secrets-provider` flag. Running `pulumi` commands retain comments in the config as expected.

Example stack config file `pulumi.<stack>.yaml`:
```
# Top level comment
secretsprovider: REDACTED
encryptedkey: REDACTED
config:
  # Another Comment
  MyProject:GroupIds: 
  - 11111111-1111-1111-1111-111111111111 # Group one
  - 11111111-1111-1111-1111-111111111112 # Group 2
```

## Expected Behavior

Comments should be retained in the config file as these could contain useful information that refers to config values

## Current Behavior

All comments are removed from config

## Steps to Reproduce

1. Create a new project `pulumi new csharp`
2. Initialise the stack with Azure KeyVault as the secrets provider
```
pulumi stack init dev --secrets-provider=azurekeyvault://<Vault Name>.vault.azure.net/keys/<Key Name>
```
3. Open the `pulumi.dev.yaml` file and add a comment
4. Run `pulumi up` and comments will be removed

**Comment by lukehoban** [comment]
@JasonWhall Can you confirm which version of the `pulumi` CLI you were using with `pulumi version`?

**Comment by JasonWhall** [comment]
@lukehoban - Apologies I've just re-tested this and the issue only occurs when using the stack has a  `--secrets-provider`. I've reproduced this using Azure KeyVault as the secrets provider but may affect when using other providers as well. 

I'm using latest Pulumi CLI `v2.9.0` 

I've also updated the steps to reproduce to reflect this.

**Comment by lukehoban** [comment]
@stack72 is this something we can return back to pre-`2.8.0` behavior without a larger change to YAML serialization?

**Comment by alastairs** [comment]
Any update on this one? I've used comments in the stack files to annotate the Azure subscription IDs with their names, and was disappointed to find that all lost as soon as I ran a `pulumi preview`.

**Comment by farvour** [comment]
Hmm, we use the `hashivault` secrets provider and have this problem as well.

**Comment by austinbutler** [comment]
Still an issue with 3.4.0. Pulumi also likes to reformat the file even when there are no changes, which is annoying if you have a prettier pre-commit hook.

**Comment by Frassle** [comment]
Was suggested today to see about bringing https://github.com/pulumi/pulumi/pull/6489 up to date and giving that another try which would fix this issue.
