### ISSUE TITLE
bootstrapping Pulumi on an arm64 system (64-bit Raspberry Pi OS / Ubuntu arm64)

### ISSUE THREAD

**Issue by vielmetti** [pulumi/pulumi#5244]
Pulumi for 64-bit Raspberry Pi OS / 64-bit arm64 Ubuntu

## Expected Behavior
Run the bootstrapper on a 64-bit Linux system running arm64:

```
curl -fsSL https://get.pulumi.com | sh
```

## Current Behavior
```
error: We're sorry, but it looks like Pulumi is not supported on your platform
       We support 64-bit versions of Linux and macOS and are interested in supporting
       more platforms.  Please open an issue at https://github.com/pulumi/pulumi and
       let us know what platform you're using!

We're sorry, but it looks like something might have gone wrong during installation.
If you need help, please join us on https://slack.pulumi.com/
emv@pi:~ $ 
```

## Steps to Reproduce

1. Run an arm64 system
2. Bootstrap with the suggested bootstrap script
3. Error message as above

## Context (Environment)

I'm trying to provision Packet hardware from my Pi 4 in my 
home lab, so that I can experiment with such things as @rawkode has
done at https://twitter.com/rawkode/status/1288546946488111106 and
https://gitlab.com/rawkode/packet-examples/-/tree/master/pulumi-saltstack .
But first I wanted to get the CLI running.

I think it should all build without incident from source.

**Comment by vielmetti** [comment]
`I think it should all build from incident from source` - well, perhaps not so fast.

I had to install `dotnet`, following this gist from @richlander https://gist.github.com/richlander/467813274cea8abc624553ee72b28213

With that installed, I then get this error:

```
/home/emv/.nuget/packages/grpc.tools/2.24.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Google.Protobuf.Tools cannot determine host OS and CPU. [/home/emv/src/github.com/pulumi/pulumi/sdk/dotnet/Pulumi/Pulumi.csproj]
/home/emv/.nuget/packages/grpc.tools/2.24.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : Use environment variables PROTOBUF_TOOLS_OS={linux|macosx|windows} and PROTOBUF_TOOLS_CPU={x86|x64} to try the closest match to your system. [/home/emv/src/github.com/pulumi/pulumi/sdk/dotnet/Pulumi/Pulumi.csproj]
/home/emv/.nuget/packages/grpc.tools/2.24.0/build/_protobuf/Google.Protobuf.Tools.targets(84,5): error : You may also set PROTOBUF_PROTOC to specify full path to the host-provided compiler (v3.5+ is required). [/home/emv/src/github.com/pulumi/pulumi/sdk/dotnet/Pulumi/Pulumi.csproj]
```

Installing protoc on Ubuntu 18.04 arm64 with `apt-get install protobuf-compiler` yields the 3.0.0 version of protoc, but v3.5+ is required.

**Comment by vielmetti** [comment]
There's a prebuilt protoc at https://github.com/protocolbuffers/protobuf/releases/tag/v3.13.0 ; installed it, then these errors:

```
/home/emv/.nuget/packages/grpc.tools/2.24.0/tools/linux_/grpc_csharp_plugin : error : program not found or is not executable [/home/emv/src/github.com/pulumi/pulumi/sdk/dotnet/Pulumi/Pulumi.csproj]
  Please specify a program using absolute path or make sure the program is available in your PATH system variable
--grpc_out : error : protoc-gen-grpc: Plugin failed with status code 1. [/home/emv/src/github.com/pulumi/pulumi/sdk/dotnet/Pulumi/Pulumi.csproj]

Build FAILED.

/home/emv/.nuget/packages/grpc.tools/2.24.0/tools/linux_/grpc_csharp_plugin : error : program not found or is not executable [/home/emv/src/github.com/pulumi/pulumi/sdk/dotnet/Pulumi/Pulumi.csproj]
--grpc_out : error : protoc-gen-grpc: Plugin failed with status code 1. [/home/emv/src/github.com/pulumi/pulumi/sdk/dotnet/Pulumi/Pulumi.csproj]
```

When I look at grpc.tools I see no arm64 support

```
emv@q-01:~/.nuget/packages/grpc.tools/2.24.0/tools$ ls
linux_x64  linux_x86  macosx_x64  macosx_x86  windows_x64  windows_x86
```

**Comment by vielmetti** [comment]
Looks like we're not the first one down this particular path for nuget, https://github.com/grpc/grpc/issues/22263

**Comment by stack72** [comment]
Hi @vielmetti 

We do publish arm64 linux builds now - have you tried pulumi on this?

Paul

**Comment by richlander** [comment]
Ouch. That's no longer the best way to install .NET on Arm64. The latest builds are at https://dotnet.microsoft.com/download

**Comment by mikhailshilkov** [comment]
I believe this has been solved with arm64 builds quite a while ago. I'll close the issue as done - if anybody has troubles with arm64, please open a new issue.
