### ISSUE TITLE
Python type hints in providers use List[T] for arguments, not Sequence[T]

### ISSUE THREAD

**Issue by csssuf** [pulumi/pulumi#5278]
The generated Python type hints for providers use `typing.List[T]` to represent lists of items in constructors/arguments, rather than `typing.Sequence[T]`. In particular, this is a problem when `T` is an Input, since `typing.List` is invariant over T, and Input is just a union under the hood. This means that many calls which should pass typechecking do not.

## Expected Behavior
Running `mypy` against Pulumi programs which pass lists of inputs into Pulumi providers passes (given that those inputs are the correct type, of course.)

## Current Behavior
mypy reports that the lists are of the incorrect type.

## Steps to Reproduce
Here's a simple Python program which reproduces the behavior:
```python
from typing import List, Sequence

import pulumi


def accepts_list(lst: List[pulumi.Input[str]]):
    pass


def accepts_sequence(lst: Sequence[pulumi.Input[str]]):
    pass


lst = ["string1", "string2"]
accepts_list(lst)
accepts_sequence(lst)
```

Running mypy against this produces the following:
```
list_test.py:15: error: Argument 1 to "accepts_list" has incompatible type "List[str]"; expected "List[Union[str, Awaitable[str], Output[str]]]"
list_test.py:15: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
list_test.py:15: note: Consider using "Sequence" instead, which is covariant
Found 1 error in 1 file (checked 1 source file)
```

## Context (Environment)
We have Pulumi programs which we have already been typechecking via mypy without type hints in the provider libraries. Now that the provider libraries have these incorrect type hints, mypy flags many new type errors in our Pulumi programs. This can be worked around by explicitly annotating the lists are `List[pulumi.Input[...]]`, but this is quite tedious, especially for types with deeper nesting (via a real example from our pulumi_kubernetes codebase): 
```python
role_arg_rules = [rbac_rule_to_pulumi_arg(rule) for rule in rules]  # type: List[pulumi.Input[pulumi.InputType[PolicyRuleArgs]]]
```

**Comment by justinvp** [comment]
Thanks for the suggestion, @csssuf! Makes sense, we should definitely move to `Sequence`. We use `Mapping` rather than `Dict` for similar reasons.

**Comment by justinvp** [comment]
The changes for this have been merged and will roll out as the providers are released.

**Comment by csssuf** [comment]
Thanks for the quick fix!
