### ISSUE TITLE
ResourceTransformation not working with custom resource

### ISSUE THREAD

**Issue by thrixton** [pulumi/pulumi#5284]
Per [this](https://www.pulumi.com/blog/automatically-enforcing-aws-resource-tagging-policies/) article, I have a transformation to auto add tags to resources.  
When I define custom resources (`pulumi.ComponentResource`), the transformation is not called with that resource or the contained resources of my custom resource.  
Logging out the resources, all are shown except for my custom one.  
```ts
    pulumi.log.info(`tag - arg:${args.name}, type: ${args.type}`);
```

Using a `ResourceValidationPolicy` policy, it does get called for my custom resource and the contained resources.

## Expected Behavior
The transformation is called for the custom resource and any child resources.

## Current Behavior
It is not being called.

## Context (Environment)

| Component | Version | 
| -- | -- |
| pulumi |  v2.9.2 | 
|  @pulumi/policy | ^1.2.0 |

**Comment by leezen** [comment]
Could you please provide your source code for how you register your stack transformation and instantiate your component resource?

**Comment by thrixton** [comment]
Well that's annoying, creating a minimal repro project works perfectly.
Apologies 🤔
