### ISSUE TITLE
Retrieve AWS region as a config

### ISSUE THREAD

**Issue by gunar** [pulumi/pulumi#5292]
When creating Cloudflare DNS Records for Domain Validation (SES), we need to interpolate the region in order to compose the DNS Record Name.

Desired change:
```diff
   priority: 10,
   zoneId: CLOUDFLARE_ZONE_ID,
   // https://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-mx-record.html
-  value: `inbound-smtp.${config.require('myCustomConfigForAwsRegion')}.amazonaws.com`,
+  value: `inbound-smtp.${config.require('aws:region')}.amazonaws.com`,
   ttl: 600
 });
```

That is, I'd like to be able to use the "native" config variable `aws:config` as opposed to having to set up a duplicated, custom one.

**Comment by jamesholmes-linktree** [comment]
const awsConfig = new pulumi.Config("aws")
awsConfig.require("region")

**Comment by gunar** [comment]
Thank you @jamesholmes-linktree, this works.
