### ISSUE TITLE
Failure to serialize a native built-in function

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#5294]
The below program fails when it attempts to serialize the native built-in function, `isNaN`. This seems wrong, though, I thought we had logic to skip serializing builtins since we don't actually need to serialize them (they're available in the global context).

## Expected Behavior

Pulumi should skip serializing `isNaN` and successfully run the program. (I don't know if whether removing `isNaN` from the equation simply leads to another bit of native code, and hence another failure, however...)

## Current Behavior

The program fails with an error message:

```
   error: Error serializing '(ev, ctx, cb) => { let body; ...': api.js(210,21)

    '(ev, ctx, cb) => { let body; ...': api.js(210,21): captured
      variable 'handlers' which indirectly referenced
        function 'app': express.js(38,20): which referenced
          function 'setMaxListeners': which captured
            'NumberIsNaN', a function defined at
              function 'isNaN': which could not be serialized because
                it was a native code function.

    Function code:
      function isNaN() { [native code] }
```

## Steps to Reproduce

Run `pulumi up` on this program:

```javascript
const cloud = require("@pulumi/cloud-aws");
const express = require("express");
const app = express();

app.get("/", (req, res) => {
    res.send("Hello, World!");
});

const endpoint = new cloud.API("app");

endpoint.get("/{proxy+}", app);

exports.endpoint = endpoint.publish().url;
```

## Context (Environment)

The following is a workaround for now that uses a native API Gateway endpoint if users don't need all of Express.js:

```javascript
const cloud = require("@pulumi/cloud-aws");
const endpoint = new cloud.API("app");

endpoint.get("/", (req, res) => {    res.send("Hello, World!");});
exports.endpoint = endpoint.publish().url;
```

**Comment by madmod** [comment]
I have also hit into this bug. Unfortunately I'm not able to apply the workaround because I have some custom middleware which depends on express.

**Comment by parimalyeole1** [comment]
Facing same issue.
If we try to use any other node module which use native code then while doing pulumi up serilize step is throwing error

**Comment by bishwenduk029** [comment]
I also faced a similar issue. Normally bundlers would introduce these native function calls , but are not getting serialised
```
'(ev, ctx, cb) => { let body; ...': captured
      variable 'handlers' which indirectly referenced
        'async (req, res) => { const result = ...': which referenced
          'async (pagesContext, req, cache) =>  ...': which referenced
            'async (normalizedPathname, pagesCont ...': which referenced
              function 'getPage': which referenced
                '(module2) => { if (module2 && module ...': which referenced
                  '(target, module2, desc) => { if (mod ...': which captured
                    '__getOwnPropNames', a function defined at
                      function 'getOwnPropertyNames': which could not be serialized because
                        it was a native code function.
```  

Any tips on which part of the code in the sdk to look up. I can give it a try to fix the same. Getting some clues can help get a quick jumpstart on the issue.

**Comment by antonkatz** [comment]
Facing this as well
```
 '(req, res) => handler(req, res)': transaction.js(42,19): captured
      'handler', a function defined at
        '(req, res) => { // handle request ha ...': index.js(199,11): which captured
          variable 'middleware' which indirectly referenced
            function 'urlencodedParser': urlencoded.js(79,35): which referenced
              function 'parse': urlencoded.js(73,17): which referenced
                function 'queryparse': urlencoded.js(258,29): which referenced
                  function 'parse': node:querystring(318,14): which captured
                    'ObjectCreate', a function defined at
                      function 'create': which could not be serialized because
                        it was a native code function.
```

**Comment by baoduy** [comment]
Me too I got the same issues please share if any workaround.

**Comment by antonkatz** [comment]
Use the Archive package method -- don't remember the details -- it takes a
folder and uploads everything in that folder as an archive to the cloud
function

**Comment by nithinpeter** [comment]
Facing the same issue as well. Is there a workaround?

**Comment by roblframpton** [comment]
This also fails for the promise versions of `fs`.  For example, this is fine:

```
import { readdirSync } from "fs";
const files = readdirSync(".");
```

But this fails to serialize:

```
import { readdir } from "fs/promises";
const files = await readdir(".");
```

**Comment by ryanfabela** [comment]
Having this issue with just about any library I use, zod, yup, joi, validator.js, etc etc. Any updates or fixes? Or am I doing something wrong?

**Comment by sladkoff** [comment]
I had this problem when importing a zod schema from a file with this syntax:

```ts
import {z} from "zod";

export const Schema = z.object({
    user_id: z.string(),
    start_time: z.string().datetime(),
    end_time: z.string().datetime().optional(),
    notes: z.string().optional()
})

export type Schema = z.infer<typeof TimeEntrySchema>
```

I could finally fix this by wrapping the Schema in a function 🤷‍♂️

```ts
import {z} from "zod";

export const getSchema = () => {
    return z.object({
        user_id: z.string(),
        start_time: z.string().datetime(),
        end_time: z.string().datetime().optional(),
        notes: z.string().optional()
    })
}

export type Schema = z.infer<ReturnType<typeof getSchema>>
```

**Comment by jakobo** [comment]
Adding additional context. This also shows up in Dynamic Resources because they share a serializer. Included my logs here: https://gist.github.com/jakobo/bda66c77da6f9bfd4c0cdd50392f9ce4

In my case, I'm using node 16 w/ esm, so there's a lot more built-in functions to bump into.

**Comment by mattfysh** [comment]
I'm also using zod and have run into this issue. Unfortunately I can't wrap the zod schema in a function as I'm importing it from a shared project in a monorepo. I tried `import { MySchema } from '@shared/zod'` and then `const getSchema () => MySchema` but it still ran into the serialization error

I'm also using the automation API, and running my program with `tsx`... so I imagine I'm in the edge case of the edge case

**Comment by mmmoli** [comment]
> Adding additional context. This also shows up in Dynamic Resources because they share a serializer. Included my logs here: https://gist.github.com/jakobo/bda66c77da6f9bfd4c0cdd50392f9ce4
> 
> In my case, I'm using node 16 w/ esm, so there's a lot more built-in functions to bump into.
> 
> [Slack thread for reference](https://app.slack.com/client/T85C88L30/C01PF3E1B8V/thread/C01PF3E1B8V-1682117823.869169)

Same here. Where'd you get to @jakobo? Any workaround with Dynamic Resources?

**Comment by jakobo** [comment]
@mmmoli the answer kind of sucks. We removed all external libraries and just use native fetch. got, axios, etc all create the serialization error.

If you have straightforward api calls, purrl by the pulumiverse team is a good alternative on the dynamic resource side: https://github.com/pulumiverse/pulumi-purrl

**Comment by mmmoli** [comment]
Fair. 

I just finished tearing out `axios` before I read your msg. 

> https://github.com/pulumiverse/pulumi-purrl

Looks spot-on. Thanks for the tip.

**Comment by dhilgarth** [comment]
I actually was able to solve it by manually implementing the solution from the documentation.

My original code:
```
import * as fs from 'fs';

getConfig() {
    return fs.readFileSync(...);
}

class LocalAwsCredentialsFileProvider implements dynamic.DynamicProvider {
    async check(olds: DynamicProviderInputs, news: DynamicProviderInputs) {
        // ...
        const config = getConfig();
        // ...
    }
}
```

The solution:
```
class ConfigReader {
    fs = require("fs");
    getConfig() {
        return this.fs.readFileSync(...);
    }
}

class LocalAwsCredentialsFileProvider implements dynamic.DynamicProvider {
    reader = new ConfigReader();
    async check(olds: DynamicProviderInputs, news: DynamicProviderInputs) {
        // ...
        const config = this.reader.getConfig();
        // ...
    }
}
```

**Comment by CMCDragonkai** [comment]
We are seeing:

```
error: Error: Error serializing 'async event=>{const ecs=await import ...': imageUpdateLambda.ts(1,640)
    
    'async event=>{const ecs=await import ...': imageUpdateLambda.ts(1,640): captured
      variable 'ecr' which indirectly referenced
        function 'BatchGetImageCommand': index.js(3857,28): which referenced
          function 'CommandRef': index.js(292,17): which captured
            variable 'closure' which indirectly referenced
              'async (output, context) => { if (out ...': index.js(1330,53): which referenced
                'async (output, context) => { const p ...': index.js(1343,58): which referenced
                  '(output, data) => { const findKey =  ...': index.js(3792,51): which referenced
                    '(target, value) => __defProp(target, ...': index.js(6,13): which captured
                      '__defProp', a function defined at
                        function 'defineProperty': which could not be serialized because
                          it was a native code function.
    
    Function code:
      function defineProperty() { [native code] }
    
        at throwSerializationError (/home/amy/git/Polykey-Infrastructure/node_modules/@pulumi/runtime/closure/createClosure.ts:701:11)
        at /home/amy/git/Polykey-Infrastructure/node_modules/@pulumi/runtime/closure/createClosure.ts:422:13
        at Generator.next (<anonymous>)
        at /home/amy/git/Polykey-Infrastructure/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:21:71
        at new Promise (<anonymous>)
        at __awaiter (/home/amy/git/Polykey-Infrastructure/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:17:12)
        at serializeWorkerAsync (/home/amy/git/Polykey-Infrastructure/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:210:20)
        at /home/amy/git/Polykey-Infrastructure/node_modules/@pulumi/runtime/closure/createClosure.ts:379:26
        at Generator.next (<anonymous>)
        at fulfilled (/home/amy/git/Polykey-Infrastructure/node_modules/@pulumi/pulumi/runtime/closure/createClosure.js:18:58)
```

But only if we are using ESM mode in our package.json. We were hoping to be using ES modules instead of CJS.

What's with this:

```
    Function code:
      function defineProperty() { [native code] }
```

? How exactly is this supposed to be worked around?

**Comment by CMCDragonkai** [comment]
How does Pulumi even ignore native code?

**Comment by mbaroody** [comment]
> I have also hit into this bug. Unfortunately I'm not able to apply the workaround because I have some custom middleware which depends on express.

has anyone found a workaround for express specifically?

**Comment by CMCDragonkai** [comment]
Apparently we should just do dynamic imports in the function itself.

**Comment by Zemnmez** [comment]
I'm getting the same issue just trying to call the aws-sdk from a dynamic provider, which I thought was the intended use-case...

```
  ● pulumi › smoke

    Error serializing '() => provider'

    '() => provider': captured
      variable 'provider' which indirectly referenced
        function 'create': which referenced
          function 'AssociatePhoneNumberContactFlowCommand': which referenced
            function 'CommandRef': which captured
              variable 'closure' which indirectly referenced
                'async (output, context) => { if (out ...': which referenced
                  'async (output, context) => { const p ...': which referenced
                    '(output, data) => { const findKey =  ...': which referenced
                      '(target, value) => __defProp(target, ...': which captured
                        '__defProp', a function defined at
                          function 'defineProperty': which could not be serialized because
                            it was a native code function.
```

I'll try refactoring to dynamic require calls. I also saw a comment about ESmodules -- I'm using those right now, does function serialization not support them?

**Comment by jakobo** [comment]
> I'll try refactoring to dynamic require calls. I also saw a comment about ESmodules -- I'm using those right now, does function serialization not support them?

In our experience ESM support was spotty, which is why our pure REST calls moved to purrl calls. A lot of our external stuff that wasn't a straightforward REST request moved to `@pulimi/command` with the following setup. This let us use full TypeScript code and not worry about serialization part.

* **PROs** Can run any TypeScript, ESM, library combination you want. If you can `npm run` it, you can Pulumi run it
* **CONs** Does _not_ serialize. The code used to execute is tied to your repo, not your state. This may matter to you, it may not, it'll depend on how you run your infra

```ts
import process from "node:process";
import * as url from "node:url";
import { local } from "@pulumi/command";
import * as pulumi from "@pulumi/pulumi";

const __filename = url.fileURLToPath(import.meta.url);

if (process.env.PULUMI_RUN === "create") {
  // RUN code

  // output on stdout
  process.stdout.write(toState(result, env));
  process.exit(0);
}

if (process.env.PULUMI_RUN === "update") {
  throw new Error("Update is not implemented for pulumi command.local");
}

if (process.env.PULUMI_RUN === "delete") {
  // DELETE code

  process.stdout.write(PULUMI_COMMAND_STDOUT ?? "{}");
  process.exit(0);
}

if (process.env.PULUMI_RUN === "read") {
  // Read flow
  throw new Error("Read is not implemented for pulumi command.local");
}

// define your resource (in this case, it's a realm dataAPI key as a componentresource,
// containing an instance of local.Command. It will use create/delete and allow for
// overwriting. You can add safeguards on create to make it idempotent and update a
// resource until local.Command supports read/update commands
// it's pure TypeScript, using "tsx"
export class MongoRealmDataAPIKey extends pulumi.ComponentResource {
  // inputs (copy from args)
  // outputs (also define these)

  constructor(
    name: string,
    args: any,
    options?: pulumi.ComponentResourceOptions
  ) {
    super(
      "ns:mongo:realm:dataAPI:key",
      name,
      {
        //
        ...args,
        id: undefined /* out */,
        apiKey: undefined /* out */,
      },
      options
    );

    // kept this as an example of exporting the environment for
    // local.Command
    const env: Record<string, string | pulumi.Input<string>> = pulumi
      .all([acquireToken(), args.projectId, args.applicationId, args.name])
      .apply(([token, projectId, appId, n]) => ({
        MONGO_TOKEN: token,
        MONGO_PROJECT_ID: projectId,
        MONGO_APP_ID: appId,
        MONGO_NAME: n,
      }));

    // uses an ENV value to trigger the "flow" to use
    const app = new local.Command(
      `${name}-cmd`,
      {
        create: `PULUMI_RUN=create pnpm exec tsx ${__filename}`,
        delete: `PULUMI_RUN=delete pnpm exec tsx ${__filename}`,
        environment: env,
      },
      { parent: this }
    );

    const response = app.stdout.apply(
      (s) => JSON.parse(s) as State<MongoAPIResponse>
    );

    // inputs => this.* as pulumi.output
    // outputs => this.* as pulumi.output
  }
}
```

**Comment by mikhailshilkov** [comment]
Another example is when trying to use `lodash.get` which uses `Array.isArray` under the hood inside a pulumi CallbackFunction handler:

```
error: Error serializing function 'processEvent': routing.ts(27,34)
    
    function 'processEvent': routing.ts(27,34): captured
      variable 'auditRoutingConfig' which indirectly referenced
        function 'SlackNotifier': slackNotifier.ts(4,15): which referenced
          function 'handle': slackNotifier.ts(11,16): which referenced
            function 'get': get.js(28,12): which referenced
              function 'baseGet': _baseGet.js(12,16): which referenced
                function 'castPath': _castPath.js(14,17): which referenced
                  function 'isArray': which could not be serialized because
                    it was a native code function.
    
    Function code:
      function isArray() { [native code] }
```

**Comment by julienp** [comment]
I can reproduce this error with a test case like this (where func is the function to be serialised):

```js
const isArray = Array.isArray;

export const func = async () => {
    console.log(isArray([]));
}
```

The problem is that we try to serialise the isArray function that's part of func's closure.

Moving isArray into the function works because we don't attempt to capture isArray by value.
```js
export const func = async () => {
    const isArray = Array.isArray;
    console.log(isArray([]));
}
```

Maybe a solution is to not capture this type of function by value but instead by reference (we could emit the literal expression `Array.isArray` here for the value), but I am not sure yet how to accomplish that in a scalable way that works for all possible such references.

**Comment by julienp** [comment]
We have solved many of the issues reported in this thread, notably we support more [native node modules](https://github.com/pulumi/pulumi/pull/15873), [recognise aliases to properties of builtin objects](https://github.com/pulumi/pulumi/pull/15873) (this is a large source of the "native function" issues) and handle [simple cases of Function.bind](https://github.com/pulumi/pulumi/pull/15887).

No doubt there are more cases where function serialisation can still fail, notably when trying to serialise something that relies on some internal node properties. See https://github.com/pulumi/pulumi/issues/15904 for a dedicated issue for track this problem.

When the issue stems from code that's coming from a package in node_modules, in general a good strategy to get function serialisation working is to require or dynamic import the module in the function. This prevents us from capturing the used parts of the module as a values, which is what often causes issues.
