### ISSUE TITLE
Provide documentation on how to mock PulumiMock.call method

### ISSUE THREAD

**Issue by edmondo1984** [pulumi/pulumi#5295]
I am struggling to test a composite component, where the output of some commands is used to execute the following commands. This is a very trivial pulumi.runtime.Mocks implementation, 

```
import pulumi
from unittest import mock
from typing import Callable
from pulumi_gcp.organizations import GetOrganizationResult


class PulumiMocks(pulumi.runtime.Mocks):
    call_mock = mock.MagicMock()

    def __init__(self):
        self.call_mock.side_effect = self.call_mocked

    def new_resource(self, type_, name, inputs, provider, id_):
        return [name + "_id", inputs]

    def call(self, token, args, provider):
        return self.call_mock(token, args, provider)

    def call_mocked(self, token, args, provider):
        import pdb

        if token == "gcp:organizations/getOrganization:getOrganization":
            return self.mock_get_organization(args)
        pdb.set_trace()
        return {}

    def mock_get_organization(self, args):
        return GetOrganizationResult(
            create_time=None,
            directory_customer_id=None,
            domain=None,
            id=None,
            lifecycle_state=None,
            name=None,
            org_id=None,
            organization=None,
        )

```

Running test fails with the following error:

```
================================================================================================= short test summary info =================================================================================================
FAILED tests/projects/test_ephemeral_project.py::test_ephemeral_project - AttributeError: 'GetOrganizationResult' object has no attribute 'items'
```

**Comment by mikhailshilkov** [comment]
@edmondo1984 apologies for the slow response.

Your mock should return a dictionary instead of the result class. Here is an example that I have for `get_ami` in AWS:

```py
    def call(self, token, args, provider):
        if token == "aws:index/getAmi:getAmi":
            return {
                "architecture": "x86_64",
                "id": "ami-0eb1f3cdeeb8eed2a",
            }
        return {}
```

I will look into extending examples and docs.

**Comment by mikhailshilkov** [comment]
@edmondo1984 I added examples in https://github.com/pulumi/examples/pull/807

**Comment by edmondo1984** [comment]
@mikhailshilkov after that change 

`args = (), kwargs = {}

    def wrapper(*args, **kwargs):
        from .. import Output  # pylint: disable=import-outside-toplevel
>       _sync_await(run_pulumi_func(lambda: _sync_await(Output.from_input(fn(*args, **kwargs)).future())))

../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/runtime/mocks.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/runtime/sync_await.py:62: in _sync_await
    return loop.run_until_complete(fut)
../../../../.pyenv/versions/3.7.3/lib/python3.7/asyncio/base_events.py:584: in run_until_complete
    return future.result()
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/runtime/stack.py:51: in run_pulumi_func
    await RPC_MANAGER.rpcs.pop()
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py:67: in rpc_wrapper
    result = await rpc
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:88: in is_value_known
    return await is_known and not contains_unknowns(await future)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/runtime/resource.py:320: in do_register
    resolver = await prepare_resource(res, ty, custom, props, opts)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/runtime/resource.py:86: in prepare_resource
    serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/runtime/rpc.py:71: in serialize_properties
    result = await serialize_property(v, deps, input_transformer)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/runtime/rpc.py:176: in serialize_property
    value = await serialize_property(output.future(), deps, input_transformer)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/runtime/rpc.py:162: in serialize_property
    future_return = await asyncio.ensure_future(awaitable)
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:113: in get_value
    val = await self._future
../../../../Library/Caches/pypoetry/virtualenvs/pulumi-utils-X5zl2to4-py3.7/lib/python3.7/site-packages/pulumi/output.py:175: in run
    transformed: Input[U] = func(value)
pulumi_utils/projects/ephemeral_project.py:76: in <lambda>
    lambda k: base64.b64decode(k).decode("utf-8")
../../../../.pyenv/versions/3.7.3/lib/python3.7/base64.py:80: in b64decode
    s = _bytes_from_decode_data(s)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

s = None

    def _bytes_from_decode_data(s):
        if isinstance(s, str):
            try:
                return s.encode('ascii')
            except UnicodeEncodeError:
                raise ValueError('string argument should contain only ASCII characters')
        if isinstance(s, bytes_types):
            return s
        try:
            return memoryview(s).tobytes()
        except TypeError:
            raise TypeError("argument should be a bytes-like object or ASCII "
>                           "string, not %r" % s.__class__.__name__) from None
E           TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

../../../../.pyenv/versions/3.7.3/lib/python3.7/base64.py:46: TypeError`

**Comment by mikhailshilkov** [comment]
Sounds like something is set to None but expected to be a Base64 string?

**Comment by edmondo1984** [comment]
I only swapped the following method:

```
def mock_get_organization(self, args):
        return GetOrganizationResult(
            create_time=None,
            directory_customer_id=None,
            domain=None,
            id=None,
            lifecycle_state=None,
            name=None,
            org_id="my-org-id",
            organization=None,
        )

```

with
 
```
def mock_get_organization(self, args):
   return {
            "org_id": "my-org-id"
        }
```

**Comment by edmondo1984** [comment]
@mikhailshilkov this behaviour is weird because the https://github.com/pulumi/pulumi-gcp/blob/master/sdk/python/pulumi_gcp/organizations/get_organization.py

shows that all fields are optional

```
	import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union
from .. import _utilities, _tables

__all__ = [
    'GetOrganizationResult',
    'AwaitableGetOrganizationResult',
    'get_organization',
]

@pulumi.output_type
class GetOrganizationResult:
    """
    A collection of values returned by getOrganization.
    """
    def __init__(__self__, create_time=None, directory_customer_id=None, domain=None, id=None, lifecycle_state=None, name=None, org_id=None, organization=None):
        if create_time and not isinstance(create_time, str):
            raise TypeError("Expected argument 'create_time' to be a str")
        pulumi.set(__self__, "create_time", create_time)
```

**Comment by mikhailshilkov** [comment]
I'm struggling to grasp where `base64.b64decode(k).decode` comes from. Do you know? Or do you have a repro project that I could clone and run?

**Comment by edmondo1984** [comment]
So this is my custom component using pulumi_gcp to create ephemeral projects

```
import base64

import pulumi_gcp
from pulumi import ComponentResource, Output, ResourceOptions
from pulumi_gcp import organizations, projects, pubsub, serviceaccount, storage


class ProjectArgs:
    def __init__(
        self, project_name: str, root_project_name: str, organization_name: str
    ):
        self.project_name = project_name
        self.root_project_name = root_project_name
        self.organization_name = organization_name


class Project(ComponentResource):

    ephemeral_project_provider: pulumi_gcp.Provider

    new_project_id: Output[str]

    number: Output[str]

    project_owner_service_account: pulumi_gcp.serviceaccount.Account

    def __init__(self, name: str, args: ProjectArgs, opts: ResourceOptions = None):

        super().__init__("myorg:modules:Project", name, {}, opts)

        root_project = organizations.Project.get(
            f"{name}-root-project", id=args.root_project_name
        )
        organization = organizations.get_organization(
            organization=args.organization_name
        )

        # Create an ephemeral project
        ephemeral_project = organizations.Project(
            f"{name}-new-project",
            name=args.project_name,
            project_id=args.project_name,
            billing_account=root_project.billing_account,
            org_id=organization.org_id,
        )

        self.project_owner_service_account = serviceaccount.Account(
            resource_name=f"{args.project_name}-project-owner-service-account",
            account_id="projectowner",
            project=ephemeral_project.project_id,
        )

        project_owner_service_account_key = serviceaccount.Key(
            resource_name=f"{args.project_name}-project-owner-service-account-key",
            service_account_id=self.project_owner_service_account.name,
        )

        project_owner_serviceaccount_iam_membership = projects.IAMMember(
            resource_name=f"{args.project_name}-project-owner-service-account-iam-member",
            project=ephemeral_project.project_id,
            role="roles/owner",
            member=self.project_owner_service_account.email.apply(
                lambda service_account_email: f"serviceAccount:{service_account_email}"
            ),
        )

        resourceManagerService = projects.Service(
            f"{args.project_name}-enable-resorce-management",
            project=ephemeral_project.project_id,
            service="cloudresourcemanager.googleapis.com",
        )

        self.ephemeral_project_provider = pulumi_gcp.Provider(
            resource_name="ephemeral-project-provider",
            credentials=project_owner_service_account_key.private_key.apply(
                lambda k: base64.b64decode(k).decode("utf-8")
            ),
            opts=ResourceOptions(
                depends_on=[
                    resourceManagerService,
                    project_owner_serviceaccount_iam_membership,
                ],
            ),
        )

        self.number = ephemeral_project.number
        self.new_project_id = ephemeral_project.project_id
        self.register_outputs(
            {
                "new_project_id": ephemeral_project.project_id,
                "number": ephemeral_project.number,
            }
        )


```


```
import pulumi

from pulumi import Output, Input
from tests.pulumi_mocks import PulumiMocks


def call_side_effect(token: str, args: dict, provider: str):
    return {}


pulumi.runtime.set_mocks(PulumiMocks())

# noqa: E402
from pulumi_utils.projects.ephemeral_project import Project, ProjectArgs


@pulumi.runtime.test
def test_ephemeral_project():
    project_name = "my-project-name"
    root_project_name = "root-project-name"
    organization_name = "root-organization-name"
    args = ProjectArgs(project_name, root_project_name, organization_name)
    project = Project("name", args)

    def test_properties(args):
        new_project_id = args[0]
        assert new_project_id == project_name

    Output.all(project.new_project_id).apply(test_properties)
```

**Comment by leezen** [comment]
Re: #5597, I didn't quite understand what you were asking there. Are you looking for additional clarification on the exception you had above or why the set_trace gets run given you would've expected the assert to raise an exception or something else? Apologies in advance if I'm not totally following.

**Comment by edmondo1984** [comment]
According to the previous messages one should just return a dict and not
the type itself in the mocks. I followed the advice in the previous comment
and the test is still failing with a serialisation issue occurring inside
pulumi framework

Il giorno mer 21 ott 2020 alle 07:40 Lee Zen <notifications@github.com> ha
scritto:

**Comment by leezen** [comment]
Looking at the code above, this looks like a legitimate test failure. From what I can see in the mocks you have setup, you never mock out the `privateKey` of `project_owner_service_account_key` so it's going to be `None` and hence why the decode fails.

**Comment by edmondo1984** [comment]
How did you find out @leezen ? Very helpful ! If I could troubleshoot it by myself I can go much faster

**Comment by edmondo1984** [comment]
Super helpful. Where exactly in the stack trace you could see it? I didn’t
find it myself

Il giorno ven 30 ott 2020 alle 18:56 Lee Zen <notifications@github.com> ha
scritto:

**Comment by leezen** [comment]
The very end of your trace has:

```
../../../../.pyenv/versions/3.7.3/lib/python3.7/base64.py:80: in b64decode
    s = _bytes_from_decode_data(s)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

s = None

    def _bytes_from_decode_data(s):
        if isinstance(s, str):
            try:
                return s.encode('ascii')
            except UnicodeEncodeError:
                raise ValueError('string argument should contain only ASCII characters')
        if isinstance(s, bytes_types):
            return s
        try:
            return memoryview(s).tobytes()
        except TypeError:
            raise TypeError("argument should be a bytes-like object or ASCII "
>                           "string, not %r" % s.__class__.__name__) from None
E           TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

../../../../.pyenv/versions/3.7.3/lib/python3.7/base64.py:46: TypeError
```

And the only place that's called is in your callback where `s` is the value of the private key.
