### ISSUE TITLE
[Automation API] Python Implementation

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#5299]
The current plan is to pick the work back up on November 16th with the goal of delivering it (along with [C#](https://github.com/pulumi/pulumi/issues/5596)) by the end of the year. We've scoped the effort and it looks like the following:

- [x] Create `Workspace` Interface [TypeScript reference](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/workspace.ts). Note there are some places where the [Go interface](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/workspace.go) is more complete (cancel, export, import). Ideally, we should shoot for the same level of completeness as the Go impl. 
- [x] Implement `RunPulumiCmd` [TypeScript reference](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/cmd.ts)
- [x] `LocalWorkspace` Implementation [TypeScript reference](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/localWorkspace.ts)
- [x] `Stack` implementation supporting local programs [TypeScript reference](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/stack.ts)
- [x] Implement idiomatic structured error handling [TypeScript reference](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/errors.ts)
- [x] Add `InlineProgram` support. This involves creating a Python implementation of the gRPC LanguageServer. TypeScript references: [LanguageServer](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/server.ts), [Preview consumption](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/stack.ts#L228-L250), and [Up consumption](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/stack.ts#L147-L169)
- [ ] Port over a few examples from https://github.com/pulumi/automation-api-examples

There are also many tests that should be replicated. These should make the implementation and acceptance criteria fairly straight forward:

https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/tests/automation/localWorkspace.spec.ts
https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/local_workspace_test.go
https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/errors_test.go

We have started a branch, but there is only the first commit that sets up the package and has the beginnings of the `Workspace` interface definition: https://github.com/pulumi/pulumi/compare/auto/python

This is actually a great opportunity for contributors to get involved and accelerate the process. The work is well-scoped and there are reference implementations. The work listed above is in order of operation. We're highly motivated to make sure this work lands soon, so this is a unique opportunity to contribute. We could offer support to anyone in the community who's interested in participating in the following forms:

1. Give you the context that you need. We'll do a kickoff via Zoom where we do an architecture overview, analyze key components of the system, and talk about what the implementation in Python  will look like. 
2. Access to the engineering team via slack.
3. Regular time with me debugging and talking through problems on Zoom. 
4. Prompt code reviews
5. T-shirts and swag

If anyone is interested in contributing please reach out in a comment, DM me on community slack, or email me at "first at pulumi dot com".

**Comment by komalali** [comment]
I'm in it for the t-shirts and swag

**Comment by komalali** [comment]
I created new issues for Remote Program and recovery workflow and updated the description on this ticket to exclude those. I'll be making separate PRs so tracking them separately.

**Comment by EvanBoyle** [comment]
Wow, a ton of progress! Not sure if we have an issue tracking but it would be great to see the content in the examples repo ported and in action: https://github.com/pulumi/automation-api-examples

**Comment by infin8x** [comment]
#### Status week of February 8, 2021: 🟢 

- This has fully shipped now that the blog post is live!
