### ISSUE TITLE
Support passing passphrase via a file

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5305]
Pulumi should allow `PULUMI_CONFIG_PASSPHRASE_FILE` to be set in a mutually exclusive manner with `PULUMI_CONFIG_PASSPHRASE`, and if it’s set, read the passphrase from the path contained in the variable. There are bunch of CI systems which expose secrets in the filesystem but don’t mask secret values in logs, so it would be nice to avoid a stray `set -xtrace` logging the passphrase when the variable is set.

**Comment by stack72** [comment]
@clstokes do you think the file needs to have the plain text secret in it only or needs to have a different structure?

**Comment by clstokes** [comment]
> @clstokes do you think the file needs to have the plain text secret in it only or needs to have a different structure?

plaintext is sufficient IMO.

**Comment by stack72** [comment]
ok so we can do this that it will just read the contents of the file
