### ISSUE TITLE
t.Logf functions saturate GitHub Actions Output

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#5326]
We use `t.Logf` to output information about what Pulumi is doing.

`t.Logf` outputs to stderr, which means we get these errors which can be misleading

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1622940/92846264-bf690500-f39c-11ea-92cf-b60c71afc7e8.png">

We have a few options here:

1. Remove the `t.Logf` calls (seems overkill)
2. Wrap the `t.LogF` calls in a wrapper that detects if we're in CI and suppresses them if we are
3. Replace them with something else?

**Comment by komalali** [comment]
Saw this in the [docs](https://golang.org/pkg/testing/#T.Logf):
> For tests, the text will be printed only if the test fails or the -test.v flag is set.

Do we set that flag? Can we just not set the flag?

**Comment by viveklak** [comment]
Yeah I have typically unset `-v`in CI test runs which takes care of this.

**Comment by jaxxstorm** [comment]
We don't, which is admittedly confusing.

**Comment by mikhailshilkov** [comment]
I feel like this hasn't been a problem recently. Since we haven't done anything in two years, I assume we won't touch it until the issue surfaces itself again in some other capacity. As a cleanup, I'll go ahead and close the issue for now.
