### ISSUE TITLE
Pulumi config param value is not set correctly if value has $ in it

### ISSUE THREAD

**Issue by sivaprasadreddy** [pulumi/pulumi#5328]
While there is no $ symbol in the value it is working fine.

```
pulumi config set param1 "ab123cd@xyz"
pulumi config get param1 => "ab123cd@xyz"
```

But if there is a $ symbol it is not working as expected.
```
pulumi config set param1 "ab$123cd@xyz"
pulumi config get param1 => "abcd@xyz"
```

However, we can workaround this issue by escaping $ with \$ as follows:

```
pulumi config set param1 "ab\$123cd@xyz"
pulumi config get param1 => "ab$123cd@xyz"
```

Is it expected or a bug?

**Comment by sivaprasadreddy** [comment]
Looks like Shell is replacing the "$123" as blank before sending it to Pulumi.
When we use single quotes it's working as expected:

```
pulumi config set param1 'ab$123cd@xyz'
pulumi config get param1 => ab$123cd@xyz
```

**Comment by stack72** [comment]
ah ok - so it's happening before it hits the pulumi engine - great news - thanks for letting me know

I can close this out as it's not a Pulumi specific bug

**Comment by sivaprasadreddy** [comment]
Yes, it seems it's not pulumi bug. But it is so common issue people may encounter, adding a note in Pulumi Config and Secrets management page would greatly help people.
