### ISSUE TITLE
Support "soft deletes" for resources

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#533]
At the moment, when you ask to destroy something, we happily oblige.  And then it's gone, forever.  We should consider whether we want some guardrails here.

In the past, we've considered requiring a `--force` to actually delete precious/persistent resources, for example.  And this may be a fine start, especially as it would require us to figure out a model for marking precious/persistent resources.  But it's probably insufficient.

Another approach is to have a "trashcan" (a.k.a., graveyard, a.k.a. quarantine, etc).  The idea is that destroyed resources (or perhaps just those precious/persistent resources) would get moved to this area, rather than destroying them entirely, for safe-keeping.  We would make it easy to restore from this area -- perhaps simply by creating a resource with the same URN in some future deployment -- in addition to giving you a way to "empty" the trashcan (at which point they are gone entirely).

Related to this, we'll also eventually need a way to do backups and restorations.  I think these are sufficiently distinct as to track them separately, but there's no question they are intimately related to one another.  See https://github.com/pulumi/pulumi-cloud/issues/43.

By the way, I thought we already had an issue tracking this, but I couldn't find it.  Please feel free to close as a dupe and link if I missed something.

**Comment by lukehoban** [comment]
Given where we are today - it's not clear this proposal still makes sense in the form it's phrased - I'll close this out for now.
