### ISSUE TITLE
Allow some output values to evaluated during preview

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi#5335]
Is there a way to specify that an output is fast, without any external dependencies, and without any side effects to resources, such that it should be evaluated during preview so its value can flow throughout and thereby avoid a cascade of unknown values?

An example use case is where I've got some helpers to create AWS IAM roles which I've switched from using c# string interpolation tricks to using `Pulumi.Aws.Iam.GetPolicyDocument`:
```c#
public static Role CreateRoleForService(string name, string service) =>
    new Role(name, new RoleArgs { AssumeRolePolicy = AssumeRoleForService(service) });

private static Output<string> AssumeRoleForService(string service) =>
    Output.Create(GetPolicyDocument.InvokeAsync(
        new GetPolicyDocumentArgs
        {
            Statements =
            {
                new GetPolicyDocumentStatementArgs
                {
                    Effect = "Allow",
                    Principals =
                    {
                        new GetPolicyDocumentStatementPrincipalArgs
                        {
                            Type = "Service",
                            Identifiers = { service }
                        }
                    },
                    Actions = { "sts:AssumeRole" }
                }
            }
        })).Apply(policy => policy.Json);
```
I don't know exactly what happens behind the scenes here, so I could be missing something important, but _intuitively_ this should be "fast, without any external dependencies, and without any side effects to resources".

I have a vague understanding from comments I've seen here and there that the Pulumi API is generated using the Terraform API, but that is only used for the "schema" of the API and not the actual engine implementation, which makes sense but also leaves me in the dark and with more questions:

* If `Pulumi.Aws.Iam.GetPolicyDocument` maps to Terraform [iam_policy_document](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document), which is a data source, does it make sense to treat it differently w.r.t. output value evaluation during preview, and should this be a more general property of "data sources"?
* Is there documentation somewhere that goes into the gory details of how this mapping is done?
  * ... this would help answer other questions I have like why is the `Statement` `Sid` being passed as an empty string despite being declared as optional in the Terraform argument reference and a nullable string property (`string?`) in the c# object model; I would expect not specifying this to _omit_ the value, so is this a bug?

**Comment by leezen** [comment]
Could you please provide your preview diff output? I would expect this work

**Comment by gitfool** [comment]
I rebuilt my stack and in the process confirmed that this does actually work as expected:
```
+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:alpha::aws::pulumi:pulumi:Stack::aws-alpha]
    + aws:iam/role:Role: (create)
        [urn=urn:pulumi:alpha::aws::aws:iam/role:Role::alpha-eks-node-role]
        [provider=urn:pulumi:alpha::aws::pulumi:providers:aws::default_3_4_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        assumeRolePolicy   : "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"ec2.amazonaws.com\"\n      }\n    }\n  ]\n}"
        forceDetachPolicies: false
        maxSessionDuration : 3600
        name               : "alpha-eks-node-role-939104e"
        path               : "/"
    + aws:iam/role:Role: (create)
        [urn=urn:pulumi:alpha::aws::aws:iam/role:Role::alpha-eks-cluster-role]
        [provider=urn:pulumi:alpha::aws::pulumi:providers:aws::default_3_4_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        assumeRolePolicy   : "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"sts:AssumeRole\",\n      \"Principal\": {\n        \"Service\": \"eks.amazonaws.com\"\n      }\n    }\n  ]\n}"
        forceDetachPolicies: false
        maxSessionDuration : 3600
        name               : "alpha-eks-cluster-role-88eaed2"
        path               : "/"
```
I must have been confused while looking at another output. 😕 

Nothing to see here, moving on, the other question still stands... why is the `Statement` `Sid` being passed as an empty string despite my not specifying its value and it being declared as optional?

**Comment by leezen** [comment]
Sorry it took me a while to come back to this thread. `Sid` is being passed as an empty string is a byproduct of how the underlying upstream Terraform provider works when it marshalls to JSON.
