### ISSUE TITLE
Error in resolving stack reference is hidden by error message about active promises

### ISSUE THREAD

**Issue by jakubneubauer** [pulumi/pulumi#5349]
When running in interactive mode (with preview), I get error that stack reference cannot be resolved. Probably pulumi cannot connect to azure blob storage, the error looks like this:
pulumi:pulumi:StackReference 14 UNAVAILABLE: Connection dropped

but what I want to report in this issue is, that when I run pulumi with --skip-preview -y , then I got this error:

```
The Pulumi runtime detected that 2388 promises were still active
at the time that the process exited. There are a few ways that this can occur:
  * Not using `await` or `.then` on a Promise returned from a Pulumi API
  * Introducing a cyclic dependency between two Pulumi Resources
  * A bug in the Pulumi Runtime
Leaving promises active is probably not what you want. If you are unsure about
why you are seeing this message, re-run your program with the `PULUMI_DEBUG_PROMISE_LEAKS`
environment variable. The Pulumi runtime will then print out additional
debug information about the leaked promises.
```
So it looks like the original error causes some promises not being resolved, because program exited too early. But the original error cause is not displayed, it is covered with the promises problem. So I cannot detect, where is the REAL problem.

**Comment by leezen** [comment]
Could you please share your code?

**Comment by jakubneubauer** [comment]
Hi, I cannot share code, it is too complex - we builded the whole library on top of pulumi and our scripts deploy hunderds of resources

**Comment by leezen** [comment]
Thanks for the clarification. If you run with verbose logging, you shouldn't miss any errors/messages that might show up. https://www.pulumi.com/docs/troubleshooting/#verbose-logging

The leaky promises detection shouldn't obscure any exception bubbling or error handling.
