### ISSUE TITLE
fetching pulumi/pulumi-dotnet or pulumi/pulumi-dotnet:latest will return 2.4.0

### ISSUE THREAD

**Issue by AliBazzi** [pulumi/pulumi#5351]
Hi,

i'm curious about `latest` tag assignment for `pulumi/pulumi-dotnet` image, can I know why it's stuck on 2.4.0, is it intentional, and you consider pulumi 2.4.0 stable while the later not yet ? or is it by mistake ?

I would like to fetch `pulumi/pulumi-dotnet:latest` and get the latest pulumi cli version along that image.

Thanks.

**Comment by stack72** [comment]
@jaxxstorm thoughts on this?

**Comment by AliBazzi** [comment]
I saw that other images of other programming languages have the same issue, the `latest` tag is still stuck on `2.4.0`
