### ISSUE TITLE
RFE: Support Poetry for a Python Project with a pyproject.toml

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi#5352]
## Expected Behavior
When creating a python project have it build a pyproject.toml and not a requirements and venv directory. 

## Current Behavior
Currently it creates a venv and requirements.txt file which we always remove and create a pyproject.toml

**Comment by josh-gree** [comment]
Having to use pip for managing dependencies is very annoying! Are there any plans to allow for this or guidance around doing so as things stand currently?

**Comment by justinvp** [comment]
> Are there any plans to allow for this or guidance around doing so as things stand currently?

@josh-gree, You can use Poetry or other tools like Pipenv instead of pip today. Some guidance on this is described here: https://www.pulumi.com/docs/intro/languages/python/#virtual-environments

**Comment by josh-gree** [comment]
Thanks @justinvp - tried this still get module resolution issues... :-( - I may well be doing something silly though!

**Comment by justinvp** [comment]
@josh-gree, what does your `Pulumi.yaml` look like?

**Comment by josh-gree** [comment]
@justinvp - repro here -> https://github.com/josh-gree/pulumi-repro

**Comment by josh-gree** [comment]
@justinvp Any idea?

**Comment by oatnog** [comment]
I see similar issues.

**Comment by kpitzen** [comment]
@josh-gree @oatnog 
I believe the issue here is not specifying your own project as a package within `pyproject.toml`:
![image](https://user-images.githubusercontent.com/4128006/177044604-270a1c6d-ec10-42fb-abf0-015af9ea13df.png)

**Comment by mikhailshilkov** [comment]
Thank you for the repro @kpitzen! Since Poetry is working, I'll close the issue as done - let us know if anyone still has trouble with it.
