### ISSUE TITLE
Test "interactive" parts of the UI

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi#537]
Some of the `pulumi` CLI commands read user input interactively.  In these cases, we have gestures like passing command line arguments or setting environment variables for a non interactive story, which we use in CI for our testing.

We should try to write some tests that actually simulate user input as well, so we could catch cases like what we saw in #534 where the commands worked as expected, except on Windows where the interactive version failed because of line endings.

**Comment by lukehoban** [comment]
This has not really come up again in the last 2 years, and I believe we do have some test coverage generally for this.  Will close for now, and we can reopen if new need arises.
