### ISSUE TITLE
TestInlineConcurrentUpdateError is flaky

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#5378]
This test occasionally fails in certain situations:

https://github.com/pulumi/pulumi/runs/1119353021?check_suite_focus=true#step:15:1918

I'm going to disable this for the time being

**Comment by jaxxstorm** [comment]
See https://github.com/pulumi/pulumi/issues/5312 for related issue

**Comment by jaxxstorm** [comment]
cc @EvanBoyle

**Comment by EvanBoyle** [comment]
@jaxxstorm did you pull this change into your branch? I think that should've made it substantially more reliable.
