### ISSUE TITLE
Check operation is very expensive for `lambda.Function` object

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#538]
A `pulumi preview` invokes `Check` on each resources created by the program.  Almost all of these take <1ms.  However, for each `aws.lambda.Function` object, we see these `Check` calls taking ~700ms, with ~300ms of no provider action prior to this.

The following trace is from a `pulumi preview` prior to any deployment of the `pulumi/pulumi-cloud/examples/containers` test.

<img width="1445" alt="screen shot 2017-11-07 at 8 56 10 pm" src="https://user-images.githubusercontent.com/223467/32532291-216ad282-c3fe-11e7-9b4e-294344b52bf9.png">

And this is from a segment of that e2e trace.

<img width="1235" alt="screen shot 2017-11-07 at 9 01 49 pm" src="https://user-images.githubusercontent.com/223467/32532419-f1145fa8-c3fe-11e7-956f-c779abd7a3df.png">

This shows lots of short `Check` calls with two very long `Check` calls associated with two `Function` objects.

In this example, just the Function checks alone account for over 1/3 of the total `pulumi preview` wall-clock time (>3.5s of 10.5s).  The AWS provider `Configure` (2.5s), Docker build (2s) and AWS `getAmi` (1.4s) are the other major chunks of the long pole.

I expect this is related to preparing the `Archive` associated with these lambdas for purposes of checking and validating the property bag.

**Comment by joeduffy** [comment]
It doesn't seem like this is a pressing issue any longer. If it is, let's reopen with more recent data.
