### ISSUE TITLE
Support functions referencing resource types

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi#5385]
Edit: We should be able to support this. See discussion below.

~Functions should not be able to reference resource types (either directly or transitively), as functions do not return `Output`s. The only exception will be for resource methods, where a resource type may be present in the `__self__` position.~

_Originally posted by @pgavlin in https://github.com/pulumi/pulumi/issues/5045#issuecomment-692337109_

**Comment by lblackstone** [comment]
Notes from offline conversation with @pgavlin:

```
You should be able to mark each object type with a hasResourceRef bit, then check during binding that a function does not reference any resource types or any object types that have that bit set

This will require a change to object type binding s.t. object types are bound via DFS (edited) 

(currently we bind types in two passes: one for declaration and another for actual binding)

Then when binding an object type, you can set the hasResourceRef bit if any field is a resource ref or another object type with the bit set

(or an array type with resource-type elements, etc. etc.)
```

**Comment by justinvp** [comment]
I need to look into the details more and summarize here, but this could be problematic for EKS as many of the functions/methods refer to resource types.

**Comment by justinvp** [comment]
My proposal is in https://github.com/pulumi/pulumi-eks/issues/452. Basically, there are four functions that I'm proposing we refactor as components that can be schematized. The rest, I think we can punt.

**Comment by pgavlin** [comment]
> functions do not return `Output`s. 

My original intuition disregarded the fact that we can simply change the codegen s.t. functions that accept resources as inputs do return `Output`s. The generated function can do an `apply` that then calls the raw invoke.

**Comment by pgavlin** [comment]
That approach should obviate the refactorings proposed in https://github.com/pulumi/pulumi-eks/issues/452.

**Comment by justinvp** [comment]
So, if there is a resource type as an argument to the function, it should be emitted as an `Input<TheResource>`, and the return type of the function will be an `Output`? What about any other arguments to the function? If we have one argument that's going to be an `Input` should we make all of them inputs?

**Comment by pgavlin** [comment]
> So, if there is a resource type as an argument to the function, it should be emitted as an Input<TheResource>, and the return type of the function will be an Output? 

That's right.

> What about any other arguments to the function? If we have one argument that's going to be an Input should we make all of them inputs?

Yes, I think that seems reasonable.

**Comment by infin8x** [comment]
#7072
