### ISSUE TITLE
Issue when creating AWS Cloudwatch subscription with granting CloudWatch Logs permissions to invoke lambda.

### ISSUE THREAD

**Issue by Erwinvandervalk** [pulumi/pulumi#5389]
We're trying to create an AWS CloudWatch log subscription to forward logs to a lambda for processing. The code we used to have is no longer working and giving us the following error message: 

```
Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function.
```
We narrowed the issue down to the cloudwatch loggroup no longer having the ":*" in the ARN. In previous versions, this was the case but no longer. 

We can see the difference in this picture (lambda permissions)
![image](https://user-images.githubusercontent.com/6771385/93309309-a8466f00-f803-11ea-973b-aeddb4a4237b.png)
- The top permission was created with a previous version of pulumi aws ("@pulumi/aws": "1.18.0",)
- the bottom permission was created with the current version of pulumi aws ("@pulumi/aws": "3.2.1")

As you can see, the ":*" is no longer there, causing the issue. A workaround is to manually add this ":*" but it was unexpected behavior and took us quite some time to narrow down. 

## Expected Behavior

The log subscription should be created. 

## Current Behavior

We get the following error message. 
```
Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function.
```

## Steps to Reproduce
Here's (some of) the code I used 
``` TypeScript

// logforwarder is a lambda..
// settings.provider contains the provider

 const logGroup = new aws.cloudwatch.LogGroup(`${prefix}service-log-group`, {
        name: `/aws/lambda/example`,
    }, { provider: settings.provider });

    const persmission = new aws.lambda.Permission(`${prefix}service-cloudwatch`, {
        function: logForwarder.name,
        action: "lambda:InvokeFunction",
        principal: "logs.eu-central-1.amazonaws.com",
        sourceArn: logGroup.arn, // This is where the issue is. 
    }, { provider:  settings.provider });


    new aws.cloudwatch.LogSubscriptionFilter(prefix + "service-filter", {

        destinationArn: logForwarder.arn,
        logGroup: logGroup,
    }, {
        provider: settings.provider,
        dependsOn: persmission
    });

```

## Workaround

``` Typescript
                const invokePermission = new aws.lambda.Permission(
                    args.name + "-cloudwatch",
                    {
                    {
                        function: functionName,
                        statementId: this.name,
                        action: "lambda:InvokeFunction",
                        principal: "logs.eu-central-1.amazonaws.com",
                        sourceArn: logGroup.arn.apply(s => s.endsWith(":*")? s : s + ":*") // pulumi api changed and all new resources created haven't ":*" at the end
                    },
                    },
                    { provider }
                );
                );
```

## Context (Environment)

This issue caused us not to be able to forward our logs to our logging platform when creating new lambda.

**Comment by stack72** [comment]
Hi @Erwinvandervalk 

So I need to apologise here but this is actually part of the upgrade to v3.0.0 AWS provider - we get the "new" behaviour based on the changes to the upstream Terraform provider that we based pulumi-aws on

`resource/aws_cloudwatch_log_group: Automatically trim :* suffix from arn attribute (#14214)`

was their entry in the CHANGELOG in v3.0.0 which we linked to

I'm sorry this wasn't more clear that this was happening...

Paul

**Comment by Erwinvandervalk** [comment]
It was a bit of an insidious change, because when we did the upgrade, nothing broke (as nothing else was changed or re-evaluated). It was only when we tried to add a new loggroup that this started to occur, which was weeks later. So, the link between the upgrade of the aws provider and the permission issue wasn't obvious. 

Some thoughts:
Perhaps the aws.lambda.Permission could check if the ARN has a :* at the end and raise a warning if it doesn't? 

And / Or the documentation could now say that you manually have to add it.

**Comment by Erwinvandervalk** [comment]
Since we have a solution for us now (the workaround described above). Feel free to close this issue.

**Comment by stack72** [comment]
thanks @Erwinvandervalk

**Comment by mococa** [comment]
this just took me an entire night, man
