### ISSUE TITLE
Enumerate Output<List<T>> ?

### ISSUE THREAD

**Issue by ardacetinkaya** [pulumi/pulumi#5392]
I am digging Pulumi for Azure with C# to get know and understand Pulumi. But I have some confusing within Output<T> type.
I am trying to get outbound IP addresses of App Service and over that list I want to create a firewall rule for SQL.

Because of Output<T> model, I can not enumerate on lists.
Is there any way to do these in easy way? 
I just want to enumerate on output and use its values as input for some other resource.

```csharp
        var ipList = apiAppService.PossibleOutboundIpAddresses.Apply(ips=>ips.Split(',').ToList());

        foreach (var item in ipList)
        {
            var firewallRule = new SQL.FirewallRule(......);
        }
```

**Comment by stack72** [comment]
Hi @ardacetinkaya 

Apologies you are having this issue - without knowing exactly what you are trying to do, I can point you in the direction of our our output documentation that may help you here - https://www.pulumi.com/docs/intro/concepts/programming-model/#outputs

If you can give a sample reproduction then we may be able to give you a bit more targeted help

Thanks

Paul

**Comment by ardacetinkaya** [comment]
Thanks for quick reply @stack72 

I checked the documentation but the examples are not enough or ready for .NET, C# development stack
```
// Helpers for accessing properties are not yet available in .NET.
```

In fact, my issue is a simple use case, I am getting App Service's outbound IP addresses as _1.1.1.1,2.2.2,3.3.3.3,...._ as Output<string>   I am converting to Ouput<List<string>> but I am not able to enumerate on this new List<>. I need to enumerate on list and use the values for to create another resource. 
Any code example with C# would really help me to clear about these.

It would be nice to have a better documentation in .NET,C# dev. stack for some basic use cases

**Comment by joaocpribeiro** [comment]
I have the same issue but I am using typescript. I can get the outbound IP addresses in a variable of type pulumi.Output<string[]>.
I would like to iterate through the values on the array to create one firewall rule for each. 

I tried to create the firewall rules within an `apply` method ([see here](https://www.pulumi.com/docs/intro/concepts/inputs-outputs/#apply)), but they don't get recognize. 

@ardacetinkaya Did you find any acceptable solution for your case?

**Comment by joaocpribeiro** [comment]
@stack72 Could you eventually help out here? I am managing azure resources using azure-native package. 
My "app" is a web.WebApp. The following code is working:
```
let firstIpAddress = app.outboundIpAddresses.apply(v => v.split(','))[0];
const firewallRule = new azure_native.sql.FirewallRule("firewallRuleForWebApp", {
  endIpAddress: firstIpAddress,
  firewallRuleName: "WebApp",
  resourceGroupName: resourceGroup.name,
  serverName: sqlServer.name,
  startIpAddress: firstIpAddress,
});
```
But I want to do this for all outboundIpAddresses, and I don't know how many they are.

I first tried the following:
```
let outboundIpAddressesArray = app.outboundIpAddresses.apply(v => v.split(','));
outboundIpAddressesArray.forEach((value, index) => {
  const firewallRule = new azure_native.sql.FirewallRule(`firewallRuleForWebApp${index}`, {
    endIpAddress: value,
    firewallRuleName: `WebApp${index}`,
    resourceGroupName: resourceGroup.name,
    serverName: sqlServer.name,
    startIpAddress: value,
  });
});
```
But `Property 'forEach' does not exist on type 'Output<string[]>'.`.
I also tried:
```
let outboundIpAddressesArray = app.outboundIpAddresses.apply(v => v.split(','));
let index = 0;
while (true) {
  pulumi.log.info(`Index: ${index}`);
  let value = outboundIpAddressesArray[index];
  value.apply(x => pulumi.log.info(x));
  if (value.apply(x => x === undefined))
  {
    pulumi.log.info(`BREAK!`);
    break;
  }
  
  const firewallRule = new azure_native.sql.FirewallRule(`firewallRuleForWebApp${index}`, {
    endIpAddress: value,
    firewallRuleName: `WebApp${index}`,
    resourceGroupName: resourceGroup.name,
    serverName: sqlServer.name,
    startIpAddress: value,
  });
  index++;
}
```
But `if (value.apply(x => x === undefined))` is always false.

How can I add a firewall rule per outbound ip address?

**Comment by Frassle** [comment]
> But `if (value.apply(x => x === undefined))` is always false.

Huh that's surprising, I would have though an output object would always be [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy).

Anyway your main issue is your apply is at the wrong level you want something like:
```
app.outboundIpAddresses.apply(v => {
  let outboundIpAddressesArray =  v.split(',');
  let index = 0;
  while (true) {
    let value = outboundIpAddressesArray[index];
    if (value === undefined)
    {
      break;
    }
  
    const firewallRule = new azure_native.sql.FirewallRule(`firewallRuleForWebApp${index}`, {
      endIpAddress: value,
      firewallRuleName: `WebApp${index}`,
      resourceGroupName: resourceGroup.name,
      serverName: sqlServer.name,
      startIpAddress: value,
    });
    index++;
  }
});
```

**Comment by joaocpribeiro** [comment]
@Frassle My mistake. It is always true, that's why no firewall rule is created.
And it seems the same happens for `value === undefined`. Value is never `undefined`. `Output<string>` is not `undefined` even if its value is `undefined`.

**Comment by Frassle** [comment]
> Value is never undefined. Output<string> is not undefined even if its value is undefined. Therefore the while-loop never ends.

Correct. Output is like a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) it's a container for a value, not the value itself. Try something like I suggested above where you apply once and then loop inside the apply. It's not perfect (previews don't understand it) but it should create everything fine during `up`. See https://github.com/pulumi/pulumi/issues/5736 for an issue about this.

**Comment by joaocpribeiro** [comment]
Sorry, at the first glance I did not identify the change on the first line of code, I thought the only changed was `if (value === undefined)`. Now I saw the whole difference and yeah, it seems to be working properly. Thanks a lot!

**Comment by pipech** [comment]
@mikhailshilkov 

I am a bit confuse.
Can we make resources with `Output.apply` ?
Because base on documentation not suppose to, right?

```
/**
 * Instance side of the [Output<T>] type.  Exposes the deployment-time and run-time mechanisms
 * for working with the underlying value of an [Output<T>].
 */
export interface OutputInstance<T> {
    /**
     * Transforms the data of the output with the provided func.  The result remains a
     * Output so that dependent resources can be properly tracked.
     *
     * 'func' is not allowed to make resources. <<<<<<<
```

https://github.com/pulumi/pulumi/blob/f6fc0997927bf6b49cf7cffda9ae692bb5c42a7c/sdk/nodejs/output.ts#L808

**Comment by mikhailshilkov** [comment]
> Can we make resources with Output.apply ?

You can, but you should try to avoid this if possible. The problem is that your previews won't see resources created inside an apply, so they won't be accurate. In this specific case though, it may not be possible to avoid this.

> Can we just use .then, something like this?

Even if you could, this won't solve the problem. The promise will get resolved at the same time when an output is resolved.
