### ISSUE TITLE
[Automation API] Secrets provider is not respected during refresh operation 

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi#5397]
Hey,

I'm using a project with _local backend_ with s3 as the state store. I was trying to configure the secrets provider backend with:

```
project := workspace.Project{
		Name:    tokens.PackageName(projectName),
		Runtime: workspace.NewProjectRuntimeInfo("go", nil),
	}
	sp := auto.SecretsProvider(cfg.SecretProvider)
	w, err := auto.NewLocalWorkspace(ctx, auto.Program(deployFunc), auto.Project(project), sp)
	if err != nil {
		return nil, errorlib.Wrapf(err, "failed to create workspace")
	}
```

`auto.UpsertStack(ctx, stackName, w)` is successful

When I was trying to use stack.Refresh() I was getting this error:
`stdout: \n, stderr: error: getting secrets manager: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables\n\n: failed to refresh stack: exit status 255`

Seems like the secrets provider isn't respected at all.

Note that I had to fix another issue to get to this point, `auto.SelectStack` didn't pass `--secret-provider` as an argument, so i patched locally the pulumi SDK to get passed that. Sadly that fix wasn't enough and the error above is still present.

**Comment by EvanBoyle** [comment]
SelectStack missing here: https://github.com/pulumi/pulumi/blob/0e3666cc3687f9aa643957739b5fc81c2cdd9ed1/sdk/go/x/auto/local_workspace.go#L339

We'll reproduce this and get a fix out. Thanks for reporting.

**Comment by EvanBoyle** [comment]
After a little digging it seems that the issue is with secrets providers in the form `awskms///`. Note the three slashes.

Selecting a stack does not require specifying a secrets provider as this is encoded in the state file at creation time.
