### ISSUE TITLE
Fail to create iam user policy Unexpected type; expected 'dict' got '<class 'str'>' 

### ISSUE THREAD

**Issue by dannielshalev** [pulumi/pulumi#5398]
## Issue summary: 
I'm using pulumi to provision AWS account with a few resources under the new account
I encounter an issue when I create an IAM user policy for the newly created user
as followed: 
pulumi up/ preview fail when passing a dictionary aws.iam.UserPolicy policy variable it fails with the following error:
```
Diagnostics:
  pulumi:pulumi:Stack (shared-services-production-core-production):
    error: Program failed with an unhandled exception:
    error: Traceback (most recent call last):
      File "/home/danniels/.pulumi/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/home/danniels/dev/pulumi-infra/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/home/danniels/dev/pulumi-infra/venv/lib/python3.8/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await RPC_MANAGER.rpcs.pop()
      File "/home/danniels/dev/pulumi-infra/venv/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/home/danniels/dev/pulumi-infra/venv/lib/python3.8/site-packages/pulumi/runtime/resource.py", line 426, in do_register
        await rpc.resolve_outputs(res, resolver.serialized_props, resp.object, resolvers)
      File "/home/danniels/dev/pulumi-infra/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 502, in resolve_outputs
        translated_value = translate_output_properties(value, res.translate_output_property, types.get(key))
      File "/home/danniels/dev/pulumi-infra/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 436, in translate_output_properties
        raise AssertionError(f"Unexpected type; expected 'dict' got '{typ}'")
    AssertionError: Unexpected type; expected 'dict' got '<class 'str'>'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

```

```python
       self.policy = aws.iam.UserPolicy(
            f"{self.account_name}-{self.automation_user}-policy",
            policy=load_config(self.default_policies),
            user=self.user.name,
            name=f"{self.account_name}-{self.automation_user}-policy",
            opts=ResourceOptions(provider=self.provider, parent=self.provider)
        )
```

## Expected Behavior
When creating and passing a valid json to policy variable is expected to pass without error.
as it in the class UserPolicy documentation: 
```python
    policy: pulumi.Output[str]
    """
    The policy document. This is a JSON formatted string.
    """
    """
    :param pulumi.Input[str] name: The name of the policy. If omitted, this provider will assign a random, unique name.
    """
```

## Current Behavior
pulumi up/ preview fail when passing a dictionary aws.iam.UserPolicy policy variable it fails with the following error:
        raise AssertionError(f"Unexpected type; expected 'dict' got '{typ}'")
    AssertionError: Unexpected type; expected 'dict' got '<class 'str'>'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1

to work around this problem do casting to string to the policy: 

```python
            policy=str(load_config(self.default_policies)['automation_user_policy']),
```
this workaround only works post aws account creation, after the account during the `pulumi up` it fails once more with flowing error:
```
  aws:iam:Policy (account-name-policy):
    error: aws:iam/policy:Policy resource 'account-name-policy' has a problem: "policy" contains an invalid JSON: invalid character '\'' looking for beginning of object key string
 ```

when I revert the casting to string in order for it to work and all the resources are successfully provisioned 

my policy is valid, this issue doesn't reproduce when the aws account is created. 

this causing a significant obstacle to create a CI&CD process using pulumi...

## Steps to Reproduce
 
prerequisite:
the blow steps should be in a pulumi project and stack that creates an AWS account and a new user in this new account

1. create a valid json policy 
2. use the following function to load this policy.json:
```python
def load_config(data):
    with open(data, 'r') as y:
        config_data = yaml.load(y, Loader=yaml.SafeLoader)
    return config_data
```
data is the path to the policy.json
3. create an I a user 
4. create an I a user policy using the load_config:
```python
            policy=load_config(self.default_policies)
```

**Comment by MitchellGerdisch** [comment]
The userpolicy resource policy input is expected to be a string (of json) as per https://www.pulumi.com/docs/reference/pkg/aws/iam/userpolicy/#inputs 

From my testing using some sample yaml, it looks like the load_config() function (specifically the yaml.load()) returns a json object and not a string (of json).
Applying json.dumps() to the output does stringify the yaml and may solve the problem.

Also, if you haven't already, maybe trying some in-line JSON (as a string) to see that it basically works without the load_config() function may help track down the root cause.

**Comment by Max1boy** [comment]
using `policy=json.dumps(load_config(self.default_policies)['automation_user_policy']),`
seems to have solved our issue, Thanks!

**Comment by MitchellGerdisch** [comment]
Great to hear!
Thanks for confirming that it worked.
