### ISSUE TITLE
Can't delete stack

### ISSUE THREAD

**Issue by GaboFDC** [pulumi/pulumi#5416]
I'm using s3 backend and kms secrets provider.

I create a new project:

`pulumi new --secrets-provider="awskms://1123-123?region=us-east-1"`

it finishes fine, all fine:

```
 ~/GIT/core-infra/new2  $ ll
total 0
-rwxrwxrwx 1 wsl-unix-user wsl-unix-user   12 Sep 18 14:35 .gitignore
-rwxrwxrwx 1 wsl-unix-user wsl-unix-user  375 Sep 18 14:35 Pulumi.core-infra.qa11.yaml
-rwxrwxrwx 1 wsl-unix-user wsl-unix-user  122 Sep 18 14:36 Pulumi.yaml
-rwxrwxrwx 1 wsl-unix-user wsl-unix-user  219 Sep 18 14:35 __main__.py
-rwxrwxrwx 1 wsl-unix-user wsl-unix-user   46 Sep 18 14:35 requirements.txt
drwxrwxrwx 1 wsl-unix-user wsl-unix-user 4.0K Sep 18 14:35 venv
 ~/GIT/core-infra/new2  $ cat Pulumi.core-infra.qa11.yaml
secretsprovider: awskms://1123-123?region=us-east-1
encryptedkey: some-super-secret==
config:
  aws:region: us-east-1
 ~/GIT/core-infra/new2  $
```

If try to remove it immediately

## Expected Behavior

Should remove the stack properly

## Current Behavior

```
 ~/GIT/core-infra/new2  $ pulumi -v 4 stack rm core-infra.qa11
This will permanently remove the 'core-infra.qa11' stack!
Please confirm that this is what you'd like to do by typing ("core-infra.qa11"): core-infra.qa11
Stack 'core-infra.qa11' has been removed!
warning: A new version of Pulumi is available. To upgrade from version '2.9.2' to '2.10.1', run
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
 ~/GIT/core-infra/new2  $ pulumi stack ls
NAME             LAST UPDATE  RESOURCE COUNT
core-infra.qa    n/a          n/a
core-infra.qa1   n/a          n/a
core-infra.qa11  n/a          n/a
core-infra.qa2   n/a          n/a
github.singular  3 days ago   572
warning: A new version of Pulumi is available. To upgrade from version '2.9.2' to '2.10.1', run
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
 ~/GIT/core-infra/new2  $ ll
total 0
-rwxrwxrwx 1 wsl-unix-user wsl-unix-user   12 Sep 18 14:35 .gitignore
-rwxrwxrwx 1 wsl-unix-user wsl-unix-user  122 Sep 18 14:36 Pulumi.yaml
-rwxrwxrwx 1 wsl-unix-user wsl-unix-user  219 Sep 18 14:35 __main__.py
-rwxrwxrwx 1 wsl-unix-user wsl-unix-user   46 Sep 18 14:35 requirements.txt
drwxrwxrwx 1 wsl-unix-user wsl-unix-user 4.0K Sep 18 14:35 venv
 ~/GIT/core-infra/new2  $
```

it removes the local stack file, but the actual stack in the bakend is not removed. Have tryied multiple times, and happens every time. Thats why so many stacks in the ls.

## Steps to Reproduce

1. Login to s3 backend.
2. create project and stack
3. try to remove stack

## Context (Environment)

I plan to manage multiple projects on the same backend, thats why there is also an extra stack.

I also tested on the latest version and is same result.

Also tested with no secrets provider, same result.

Also triend doing `pulumi up` then destroy and then removing the stack, but same result.

**Comment by theneva** [comment]
Pretty sure I have the same problem on Pulumi v2.14.0:

![stack-rm](https://user-images.githubusercontent.com/1404650/100391979-6de42400-3035-11eb-9006-87fd889594bb.gif)

This is pretty annoying. I'll work around it by deleteing the stack file from the storage backend (GCS in my case), but it's Not Great that Pulumi claims to have successfully removed the stack when it clearly hasn't :smile:

**Comment by emiliza** [comment]
I can't repro this on v.3.7.0 using a GCS backend. This may have been resolved a while back - feel free to comment with repro versions if this is still a problem.

**Comment by gvialetto** [comment]
I confirm I can repro this, same steps as above, in `v3.10.3`. 
Creating a stack on S3 backend and then immediately deleting it leaves the stack files in the storage backend (but deletes the local stack file). `pulumi stack ls` still reports the stack as present.

**Comment by Frassle** [comment]
Just tested with v3.26.0 using AWS S3. Can't repro, the stack files seems correctly deleted although a ".bak" file is left behind but that's intended and doesn't show up on `stack ls`.

If people hit this issues again can you please include logs from running pulumi with `--logtostderr -v9`.
