### ISSUE TITLE
[Automation API] UpResult.GetPermalink() not working

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi#5422]
It always returns and error `failed to get permalink for update` even though it is printed to the stdout.
I'm using the new progressStreams feature but even without using the problem persists.

Example code:
```
                  result, err2 := s.Up(ctx, optup.ProgressStreams(writer))
		if err2 != nil {
			return errorlib.Wrapf(err2, "failed to update stack")
		}
		link, err := result.GetPermalink()
```

**Comment by metral** [comment]
Are you still encountering this issue @yarinm? If so, are you using the Pulumi Service for state management, or an alternative / local backend instead?

This code path is currently intended for the Service, but would return errors if using a local backend.

**Comment by infin8x** [comment]
Closing this for now. As @metral noted, this is only expected to work against the Pulumi Service.
