### ISSUE TITLE
`pulumi up` tree view broken when exceeding console height

### ISSUE THREAD

**Issue by stohrendorf** [pulumi/pulumi#5441]
The `pulumi up` tree view of the resources breaks when its height exceeds the console height (see screenshot).

## Expected Behavior
Tree view is not broken.

## Current Behavior
![image](https://user-images.githubusercontent.com/7853507/93862275-11295d80-fcc2-11ea-8734-9a7ce4ea44d5.png)

## Steps to Reproduce
Add more resources than the height of the console can handle.

## Context (Environment)
N/A

(Quick idea how to "fix" this - if possible: collapse child nodes if needed and limit vertical size of children in case of a flat list/degenerated tree and only show the full tree after planning is done.)

**Comment by stohrendorf** [comment]
FYI, this also affects `pulumi preview` so that it outputs wrong information. In certain cases it can output a valid looking tree that's not actually representing the actual resource tree. Both are ways to review the changes to be done, and as they can produce wrong outputs, possibly leading to a faulty stack update because of misinformation, I would consider this a bug.

**Comment by SharpEdgeMarshall** [comment]
On big projects this is quite annoying, there is some workaround in the meantime?

**Comment by Frassle** [comment]
I do wonder if it's worth investigating the use of something like [tview](https://github.com/rivo/tview) for UI support.

**Comment by lukehoban** [comment]
This was fixed in https://github.com/pulumi/pulumi/pull/11200.
