### ISSUE TITLE
Question: What is a unique provider ID in Azure? 

### ISSUE THREAD

**Issue by Tikarei** [pulumi/pulumi#5445]
Hello. I'm new to Azure and Pulumi so bare with me if the answer is obvious. I'm trying to [get an existing resource group](https://www.pulumi.com/docs/reference/pkg/azure/core/resourcegroup/#look-up) so that I can create a new VM under that group. The documentation says I need to pass a 2nd argument that is a **unique provider ID of the resource to lookup**. 

What is that ID? I can't find any references of that ID on the Azure Portal when looking at my VM details.

**Comment by lukehoban** [comment]
If you look at an existing resource of the same type - you can see it’s `id` property either by logging in code - or running `pulumi stack —show-ids `. 

For Azure, IDs are almost always the ARM resource path - like `/subscriptions/0282681f-7a9e-424b-80b2-96babd57a8a1/resourceGroups/tfvmex-resources`. 

https://github.com/pulumi/docs/issues/3773 Is tracking adding examples of import of formats to the documentation for all resources.

**Comment by Tikarei** [comment]
Thanks, working now!
