### ISSUE TITLE
Support tracing in the JavaScript langhost implementation

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#545]
With #521 we have added support for OpenTracing through the engine, providers and language hosts.  However, we do not yet generate any traces from the JavaScript side of the langhost RPC boundary.  In practice, this doesn't obscure too much, but we may be able to get additional insight by instrumenting the langhost with key spans - such as resource creation.

**Comment by joeduffy** [comment]
I think we've decided to move away from Jaeger tracing overall, so closing out. Please reopen if this is still something we will do.
