### ISSUE TITLE
`change-secrets-provider` is unable to change from one passphrase to another passphrase

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5452]
#### Problem

If I try to use `change-secrets-provider` to change the passphrase my stack is currently using, I get prompted for my current passphrase several times, but I'm never prompted for a _new_ passphrase and then the command exits.

```
% pulumi stack change-secrets-provider passphrase
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
%
```

#### Suggestions for a fix

Prompt for a new passphrase.

Also, why do I get prompted for the current passphrase so many times? Could this be improved too?

**Comment by stack72** [comment]
So this is when you are trying to rotate the passphrase used - so staying within the passphrase provider right?

**Comment by clstokes** [comment]
Yes, staying within the passphrase provider, but trying to change the passphrase that is used.
