### ISSUE TITLE
Node SDK 2.10.2 leaks promises

### ISSUE THREAD

**Issue by andrew-property-xyz** [pulumi/pulumi#5457]
Very similar to issue #2470, I am attempting to test a very similar program:
```
const aws = require('@pulumi/aws')

const initService = () => {
  const uploadBucket = new aws.s3.Bucket('data-feed-upload')

  uploadBucket.onObjectCreated('feedUploadHandler', async (e) => {})

  return {
    uploadBucket: uploadBucket
  }
}

module.exports = {
  initService
}
```

When testing with mocha, the test itself passes but I get this message (see below) and the process exits with 1 - which would fail any CI/CD pipeline I might have in place.
```
The Pulumi runtime detected that 120 promises were still active
at the time that the process exited. There are a few ways that this can occur:
  * Not using `await` or `.then` on a Promise returned from a Pulumi API
  * Introducing a cyclic dependency between two Pulumi Resources
  * A bug in the Pulumi Runtime

Leaving promises active is probably not what you want. If you are unsure about
why you are seeing this message, re-run your program with the `PULUMI_DEBUG_PROMISE_LEAKS`
environment variable. The Pulumi runtime will then print out additional
debug information about the leaked promises.
```

It is the uploadBucket.onObjectCreated statement that causes this. If I comment this line out, there is no issue.

I am using Node 10.16.1, @pulumi/aws 3.4.0 and @pulumi/pulumi 2.10.2.

## Expected Behaviour

If there are active promises when the process exits, then, yes, it is good to be made aware of them but the documentation and stack trace (from using the `PULUMI_DEBUG_PROMISE_LEAKS` environment variable) provide little assistance in understanding what is going on and how to resolve this issue.

So, in summary, I'm not sure what the expected behaviour should be here. Is this bad code that will genuinely leak promises? If so, how do I address them? If the code is fine and shouldn't leak promises, is it an issue with the Pulumi Runtime in test mode?

## Current Behaviour

As described above. Unable to resolve the reported issue and cannot test. This problem does not seem to arise when the program is actually run (with a real lambda function) using `pulumi up`, only when trying to test.

This feels to me like a bug in the Pulumi Runtime or a very simple thing that I am not doing right but which isn't covered in the documentation.

## Steps to Reproduce

As above.

## Context (Environment)

I'm just trying to perform simple tests to validate that the various resources are created, etc. but even though the tests themselves pass, it seems the presence of the active promises results in a non-zero exit code.

**Comment by leezen** [comment]
It'd be helpful if you could please provide your test code and setup.

**Comment by andrew-property-xyz** [comment]
Please clone: https://github.com/property-xyz/pulumi-test

**Comment by andrew-property-xyz** [comment]
@leezen I have modified the test to use the all/apply pattern to evaluate bucket name. This passes but I still get the complaint about 157 active promises and the process exiting with code 1 when I run tests using `npm test`.

**Comment by leezen** [comment]
I took a look at the source you provided -- thanks. This looks like a possible bug in the runtime w.r.t. unit testing in that everything that 'leaks' appear to be the underlying resources of the component resource that gets constructed for the `onObjectCreated` handler.

**Comment by andrew-property-xyz** [comment]
Ok, thanks for looking at this so promptly.

**Comment by andrew-property-xyz** [comment]
Hi. Is there any movement on this? At the moment, I am having to exclude test files that include any pulumi dependencies (even if there are no tests) because `npm test` just fails due to hundreds of leaked promises.

**Comment by EvanBoyle** [comment]
Closing this out as the repo with the repo seems to have been deleted. If this issue is persisting in the latest pulumi 3.X, please open a new issue with a repro.
