### ISSUE TITLE
AWS-Typescript Getting Started can't load AWS credentials 

### ISSUE THREAD

**Issue by DylanSp** [pulumi/pulumi#5458]
I'm working through the Getting Started docs for aws-typescript. I have valid AWS credentials under a profile named "dev" in ~/.aws/credentials; I've confirmed that these work with the AWS CLI. However, with aws:profile set to "dev", running `pulumi up` gives a Terraform error about failing to find valid credentials.

## Expected Behavior
`pulumi up` successfully displays a preview of the expected update.

## Current Behavior
```
Diagnostics:
  aws:s3:Bucket (my-bucket):
    error: 1 error occurred:
        * error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
    
    Please see https://registry.terraform.io/providers/hashicorp/aws
    for more information about providing credentials.

    Error: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

## Steps to Reproduce
1. `pulumi new aws-typescript`
2. `pulumi config set aws:profile dev` (with a valid AWS profile named `dev`)
3. `pulumi up`

**Comment by DylanSp** [comment]
Looks like this is an underlying Terraform issue; I ran into the same phenomenon when using Terraform directly, documented on [this issue](https://github.com/terraform-providers/terraform-provider-aws/issues/15361). Closing this issue, since it's not Pulumi-related.

**Comment by donovanmuller** [comment]
I faced the same issue. I found that setting the profile via `pulumi config set aws:profile xxx` resulted in the error above, in my case, when using `assumeRole`:

```typescript
const provider = new aws.Provider("privileged", {
    assumeRole: {
        roleArn: "xxx",
        sessionName: "PulumiSession",
        externalId: "PulumiApplication",
    },
    region: aws.config.requireRegion(),
});
```

I had to set set `export AWS_PROFILE="xxx"` explicitly for the above to work. Not sure if this is a different issue though. Adding for posterity.

**Comment by aecorredor** [comment]
@donovanmuller I can confirm that solved it for me.
