### ISSUE TITLE
[Feature request] ARM64-based CLI package and Docker Image

### ISSUE THREAD

**Issue by runlevel5** [pulumi/pulumi#5466]
AWS EC2 offers ARM-based instance type which is very economical for running CI/CD. I would like to ask if your team could offer the ARM64-based binary package and Docker image.

Many thanks

**Comment by lukehoban** [comment]
This is also being tracked in https://github.com/pulumi/pulumi/issues/4868.  Will close this one out to consolidate there - but please do upvote it @runlevel5!
