### ISSUE TITLE
Changing secrets provider breaks `pulumi stack history --show-secrets --json

### ISSUE THREAD

**Issue by elsesiy** [pulumi/pulumi#5470]
## Update after some debugging
The underlying issue here is with changing secrets providers. `pulumi history --json --show-secrets` grabs all previous updates from the service for this stack, including all config. `--show-secrets` will decrypt the config using the most recent decrypter. Secrets encrypted using previous providers will fail to decrypt with the new secrets provider. Changing secrets providers should probably re-encrypt all config from previous updates. 

The immediate action item here is to fix the history command to add a placeholder for config values that it can't decrypt. More broadly, we need to sort this question out:

__Should changing secrets provider re-encrypt the full deployment history?__ What about deployment checkpoints in the service? Currently, the way this works is by doing a `stack export` and a `stack import` for the last deployment.

There are a few aspects to think through here:

1. Does changing the secrets provider require the old secrets material? Presumably, one motivation for changing secrets providers could be the loss of a particular material. Today we do require the material if the existing stack has any encrypted values. 
2. The current workflow kind of breaks "rollback". Older versions don't get rewritten with the new config value. How should exporting/importing an old version of the stack with a different encryption provider work if we don't re-encrypt history?
3. Re-encrypting history might involve re-encrypting checkpoints. There could be thousands of these, and the process to re-encrypt would need to be driven by the service. We'd need to think through how this works for OSS backends. 
4. It's not clear what the ownership philosophy is with respect to stacks and secrets providers? If you change a secrets provider, you could make the argument that all previously encrypted values should be inaccessible by design.

Practically I think a decent solution that balances investment, complexity shared between SaaS and OSS backends, and leaves customers the option for a rollback workflow could look like this:

1. Add the ability to re-encrypt N previous deployments as a part of the secrets provider migration command (default to either N=1 or N=5). 
2. Do this re-encryption via the CLI, ignore any checkpoints in the service. This balances investment and drift across the service and OSS backends.
3. Model this as a roll forward for the previous N deployments (export --version=N, re-encrypt, import --version=M). For example, deployments 1, 2, and 3 get re-encrypted and imported as deployments 4, 5, and 6 respectively. 
 
## Original report
I just deployed a stack update using the Automation API.
Even though the update succeeded, I got a panic at the end as fetching the stack history seems to have failed.

## Expected Behavior
I expect the stack history to be successfully fetched and hence the update to succeed.

## Current Behavior
panic

```
~ update outputs
Resources:
    + 1 created
    ~ 2 updated
    3 changes. 63 unchanged
Duration: 1h20m20s
==> Couldn't update stack: code: 1
Pulumi Version:   v2.10.2
Go Version:       go1.15.2
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: cipher: message authentication failed
goroutine 1 [running]:
runtime/debug.Stack(0xc001307668, 0x51abf60, 0xc0015f63e0)
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/debug/stack.go:24 +0x9f
main.panicHandler()
	/private/tmp/pulumi-20200921-51897-11yu5ss/pkg/cmd/pulumi/main.go:29 +0x73
panic(0x51abf60, 0xc0015f63e0)
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/panic.go:969 +0x175
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/private/tmp/pulumi-20200921-51897-11yu5ss/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.AssertNoError(0x57262a0, 0xc00011c590)
	/private/tmp/pulumi-20200921-51897-11yu5ss/sdk/go/common/util/contract/assert.go:40 +0xe5
main.displayUpdatesJSON(0xc00155e000, 0xc5, 0x117, 0x57279e0, 0xc0015ccc00, 0x0, 0xc5)
	/private/tmp/pulumi-20200921-51897-11yu5ss/pkg/cmd/pulumi/stack_history.go:112 +0x165
main.newHistoryCmd.func1(0xc000712dc0, 0xc0002f1740, 0x0, 0x3, 0xe, 0xe)
	/private/tmp/pulumi-20200921-51897-11yu5ss/pkg/cmd/pulumi/history.go:65 +0x228
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunFunc.func1(0xc000712dc0, 0xc0002f1740, 0x0, 0x3, 0x0, 0x0)
	/private/tmp/pulumi-20200921-51897-11yu5ss/sdk/go/common/util/cmdutil/exit.go:96 +0x51
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc000712dc0, 0xc0002f1740, 0x0, 0x3)
	/private/tmp/pulumi-20200921-51897-11yu5ss/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000712dc0, 0xc0002f16b0, 0x3, 0x3, 0xc000712dc0, 0xc0002f16b0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000160000, 0x15, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/private/tmp/pulumi-20200921-51897-11yu5ss/pkg/cmd/pulumi/main.go:48 +0x4d
: failed to get stack history: exit status 1
```

## Steps to Reproduce
There's nothing to provide here, the snippet that ultimately failed is this
```
stdoutStreamer := optup.ProgressStreams(os.Stdout)
_, err = stack.Up(ctx, stdoutStreamer)
if err != nil {
    fmt.Printf("==> Couldn't update stack: %s", err.Error())
}
```

**Comment by EvanBoyle** [comment]
Sorry this slipped through the cracks. Is this a consistent failure? The stack trace indicates that the failure might be related to secrets provider configuration. Are you using a non-default secrets provider? Do you have a full repro?

**Comment by elsesiy** [comment]
We're using the HashiCorp Transit secrets engine which is a "default" secrets provider from Pulumi perspective I believe. I don't have much more than that unfortunately, let me know if you want to take a look at it via screen share or something

**Comment by lukehoban** [comment]
Am I right that deploying this stack directly (not via Automation API) works as expected?  But doing it inside Automation API leads to the panic?

**Comment by lukehoban** [comment]
Also - does running `pulumi stack history` manually for this stack also lead to the same panic?

**Comment by elsesiy** [comment]
@lukehoban Running `pulumi stack history` directly works just fine, no panic. I never used this command before but it seems like the Automation API is running this after updating a stack

**Comment by EvanBoyle** [comment]
Can you try `pulumi stack history --json` this runs a slightly different code path. And is this a consistently reproducible error?

**Comment by sfc-gh-jelsesiy** [comment]
@EvanBoyle That works too, no panic

**Comment by EvanBoyle** [comment]
Is your `workDir` set to the same path as your `pulumi.yaml` and `pulumi.stack.yaml` for that project? It would be helpful to have more detail about how your project is laid out, what the pulumi.yaml and pulumi.stack.yaml contents look like, and how you are setting up your local workspace with automation API. 

Happy to do this over screen share if you want to set up time thurs/friday.

**Comment by sfc-gh-jelsesiy** [comment]
```
.
├── README.md
├── common
│   ├── Pulumi.stack.yaml
│   ├── Pulumi.yaml
│   ├── README.md
│   ├── go.mod
│   ├── go.sum
│   ├── main.go
│   └── vendor
├── go.mod
├── go.sum
├── main.go ## Automation API
└── platform
    ├── Jenkinsfile
    ├── Makefile
    ├── Pulumi.stack.yaml
    ├── Pulumi.yaml
    ├── README.md
    ├── go.mod
    ├── go.sum
    ├── kubernetes
    ├── main.go
    ├── network
    ├── postgres
    ├── util
    └── vendor
```

The Automation API piece basically does the following:
1. Finds all stacks in `common`
2. For each stack
```
dir := "common" # just for illustrative purposes, actually part of the iteration piece
stack, err := auto.SelectStackLocalSource(ctx, auto.FullyQualifiedStackName(..), dir)

stack.Preview(ctx)
...
# see issue description
stack.Up(ctx, stdoutStreamer)
```

**Comment by EvanBoyle** [comment]
@elsesiy The underlying panic/error has been fixed, and the history command will no longer fail. @stack72 made the change here that marks values we can't decrypt rather than choking: https://github.com/pulumi/pulumi/pull/5701

We released a patch version with this fix. Let us know when you have the chance to update and give it a try: https://www.pulumi.com/docs/get-started/install/versions/

**Comment by elsesiy** [comment]
@EvanBoyle Using the exact same example we went over, I'm now getting a new error during preview:
```
Failed to preview stack: unable to unmarshal preview result: invalid character 'r' looking for beginning of value

exit status 1
```

**Comment by EvanBoyle** [comment]
@elsesiy The command that runs is closer to `pulumi preview --json`. The command "succeeding" according to error code, but it seems that the resulting output can't be unmarshalled:

https://github.com/pulumi/pulumi/blob/0e3666cc3687f9aa643957739b5fc81c2cdd9ed1/sdk/go/x/auto/stack.go#L258

I have a PR up that provides better diagnostics in the error message:

https://github.com/pulumi/pulumi/pull/5715

You can either pull down and build against that branch, or set a breakpoint at the line I linked at look at the value of `stdout`. Either of those should give us a better idea of why we can't handle the preview result.

**Comment by elsesiy** [comment]
@EvanBoyle It works using the latest SDK `2.13.2`, seems to be related to https://github.com/pulumi/pulumi/pull/5709 as we do have a quite a few custom resources. With the latest version there's also no more panic due to the history issue we observed, hence closing this ticket! Thank you so much 🥇

**Comment by EvanBoyle** [comment]
Glad to hear @elsesiy!

I opened https://github.com/pulumi/pulumi/issues/5717 to follow up on the issue with the change secrets provider workflow.
