### ISSUE TITLE
How to share a config between projects

### ISSUE THREAD

**Issue by sam-cogan** [pulumi/pulumi#5473]
I'm using Pulumi to deploy a AKS cluster, and to minimise blast area I've split this into 3 projects, prerequisites, AKS and applications. I'm aware how I can pass values between projects using stack references, however I've got a number of config values which are used by all 3 projects. As far as I can tell the only way to work with these is to either specify them 3 times in the stack file for each project, or pass them as outputs from one project to another. There are quite a few config settings, which don't change so it seems a waste of time to create outputs and pass them between each project. Is there a better way to achieve this?

I tried using a config file that sat above the projects and referencing that using the --config-file path, ~~however that resulted in the second project trying to delete the resources created in the first one, so looks like it caused them to use the same state file.~~ it seems that if I specify the --stack property alongside this it does work, but is this best practice?

**Comment by leezen** [comment]
There's nothing inherently wrong in what you've described. I suspect your config could potentially diverge at some point and you'll want a flavor of https://github.com/pulumi/pulumi/issues/2307 that's not specific to project-stack hierarchy, but something that sits common to a set of projects. I'll add this issue to the overall tracking epic in https://github.com/pulumi/pulumi/issues/4604

**Comment by sam-cogan** [comment]
Thanks @leezen I agree, having a hierarchical configuration that can merge configs from different levels would be very useful for these sort of scenarios.

**Comment by rhyek** [comment]
hi. this was closed by the author, but not resolved, i believe. is the pulumi team still considering org-level configs as a proper feature? i'm currently doing as @sam-cogan mentioned and having one project output configs for other projects to consume via stack references, but would love something more ergonomic.

**Comment by Frassle** [comment]
> is the pulumi team still considering org-level configs as a proper feature?

Yes we should have some news on this shortly.
