### ISSUE TITLE
pulumi stack output --show-secrets incorrectly displays special characters

### ISSUE THREAD

**Issue by ghost** [pulumi/pulumi#5474]
I'm using @pulumi/random to generate password for my rds instance. The value I got was something like `pass&word`.  When I use command `pulumi stack output --show-secrets` it displayed the value `pass\u0026word`

## Expected Behavior

Show correct secret value in correct encoding, i.e. `pass&word`

## Current Behavior

Shows incorrect secret value , i.e. `pass\u0026word`

## Steps to Reproduce

1.  clone https://github.com/akhanqi/secrets-pulumi-bug
2. run `pulumi up`
3. run `pulumi stack output --show-secret`
4. check that output has \u003c or other unicode characters

> OUTPUT    VALUE
    password  {"id":"none","length":30,"lower":true,"minLower":0,"minNumeric":0,"minSpecial":30,"minUpper":0,"number":true,"result":"_}}%-++{:_(-[%\u003c\u003e?-\u003c{})\u003e=+\u0026-#]$","special":true,"upper":true,"urn":"urn:pulumi:dev::pulumi-secrets-bug::random:index/randomPassword:RandomPassword::password"}

**Comment by jccr** [comment]
I rely on `pulumi stack output --show-secrets --json` as part of my CI workflow, and I've recently hit this issue when wrapping a value with an `&` character with `pulumi.secret()`

This became a showstopper for me. I think I can try to workaround this in my CI script to unescape the value, but this is inconvenient.

@stack72 any word on the secret handling improvement work?
