### ISSUE TITLE
Cannot find module '@pulumi/pulumi/runtime/index.js

### ISSUE THREAD

**Issue by xdmtk** [pulumi/pulumi#5478]
Hi all, 

I've just began using Pulumi as of today so forgive me if I'm missing something really obvious, but I'm running into some really strange errors when invoking my Lambda function after Pulumi has deployed it to AWS. 

## Expected Behavior
Going off the example code seen in https://www.pulumi.com/docs/tutorials/aws/rest-api/ , I've got the standard 3 imports 
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";
```

And an endpoint from 
```
const endpoint = new awsx.apigateway.API("exampleLambda", {
    routes: [
        {
            path: "/",
            method: "POST",
            eventHandler: new aws.lambda.CallbackFunction("exampleHandler", {
                memorySize: 256,
                callback: handler,
            }),
        }
    ]
});
```

My handler function requires some secrets I've stored with `pulumi config set --secret`, so I bring up a new `Config()` instance like so
```
const getSecrets = () => {
    const config = new pulumi.Config();
    return config.requireSecret('exampleSecret');
}
```

After calling `getSecrets()` it should return the secret I stored. 

## Current Behavior

Instead, however I get an error regarding the imports. 

```
2020-09-29T20:40:14.800Z	b003717c-d6d5-48fe-b7a4-8fb8d7f18d01	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Cannot find module '@pulumi/pulumi/runtime/index.js'\nRequire stack:\n- /var/task/__index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/__index.js",
        "/var/runtime/UserFunction.js",
        "/var/runtime/index.js"
    ],
    "stack": [
        "Error: Cannot find module '@pulumi/pulumi/runtime/index.js'",
        "Require stack:",
        "- /var/task/__index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:841:27)",
        "    at Module.require (internal/modules/cjs/loader.js:1025:19)",
        "    at require (internal/modules/cjs/helpers.js:72:18)",
        "    at /var/task/__index.js:150:23",
        "    at __f3.__f4 (/var/task/__index.js:185:6)",
        "    at __f3.<anonymous> (/var/task/__index.js:367:24)",
        "    at __f3.__f18 (/var/task/__index.js:375:34)",
        "    at __f3.<anonymous> (/var/task/__index.js:383:32)",
        "    at __f3.__f20 (/var/task/__index.js:387:34)"
    ]
}
```

I even decided to skip using the `Config()` class figuring I would just fetch the secret from a key file on an S3 bucket

```
import * as aws from "@pulumi/aws";
const getKeyFileFromS3 = async () => 
    const keyFile = await aws.s3.getBucketObject({
        bucket: 'credentials',
        key: 'creds.json'
    });
}
```

But even this results in a similar error
```
2020-09-29T21:50:01.862Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@pulumi/aws/s3/index.js'\nRequire stack:\n- /var/task/__index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@pulumi/aws/s3/index.js'"
...
...
```

So as of right now, the only import I am actually able to use is the `import * as awsx from "@pulumi/awsx";` import, that sets up the APIGateway endpoint. 

## Steps to Reproduce

1. Setup `pulumi new` AWS Typescript project and use typescript variant of https://www.pulumi.com/docs/tutorials/aws/rest-api/ 
2. Either: Store secrets and attempt to retrieve them using `Config.requireSecret()` | Retrieve file from S3 using `aws.s3.getBucketObject()`
3. `pulumi up` and execute Lambda. 
4. Observe logs with `Runtime.ImportModuleError` error

## Context (Environment)

Again, this seems almost too basic to be fixable and I'm hoping there isn't some environment or AWS issue on our end that is causing this, but I'm not sure where to start looking. The only issue that seems to be even closely related I could find was https://github.com/pulumi/examples/issues/514 , and it doesn't do much in the way of help here.

I'm trying to accomplish a very basic task here, and that is store keyfile credentials with `pulumi config` and retrieve them securely when running my Lambda. Please let me know if you all need any more information. I'll try and provide as much as I can.

Thanks!

**Comment by tusharshahrs** [comment]
Hi @xdmtk,
  Here is one way to do the following.  You can set the secret as the following for the config:
`pulumi config set --secret exampleSecret "ABCDEFGHIJKLMNOPQRSTUVWXYZ"`

Then when you do `pulumi config`:
```
KEY            VALUE
exampleSecret  [secret]
aws:region     us-east-2
```

In your index.js file replace this:
```
const getSecrets = () => {
    const config = new pulumi.Config();
    return config.requireSecret('exampleSecret');
}
```
with the following:

```
// create a local config variable
const config = new pulumi.Config()
// get secret from local config
getSecrets = config.requireSecret("exampleSecret");
```

At the very end of the file you can add this:
`exports.mygetSecrets = getSecrets;`

Then run: `pulumi up -y` and after it completes run:
` pulumi stack output`

```
Current stack outputs (2):
    OUTPUT        VALUE
    mygetSecrets  [secret]
    url           https://2ozd4e00jf.execute-api.us-east-2.amazonaws.com/stage/
```

**Comment by tusharshahrs** [comment]
@xdmtk,
Looks like you are missing the node modules.  You can do the following in the directory you are running this from:
`npm install`

**Comment by xdmtk** [comment]
Hi @tusharshahrs 
Per your first comment, the problem isn't actually Pulumi passing up secrets in the stack, but its that they cannot actually be accessed from the `Config` class because the `Config` class fails to initialize due to missing files in the module.

As you can see here, the modules are indeed installed locally. 
![image](https://user-images.githubusercontent.com/36802059/94855242-0d44bc00-03e3-11eb-87e2-2d7ba62ed162.png)


The issue is that after running `pulumi up`, the modules don't seem to get uploaded to AWS, as when firing the function from the endpoint returned after `pulumi up` is when I get the missing modules error. 

I can't actually inspect the file package that gets uploaded either since its too large for the AWS console to show me in the inline editor.

**Comment by tusharshahrs** [comment]
Can you try this:
  `pulumi up --logtostderr -v9 --debug`
and send us the output via email since it will be big.  support@pulumi.com

**Comment by xdmtk** [comment]
Done. Thank you!

**Comment by xdmtk** [comment]
@tusharshahrs FYI - I am experiencing similar import frustrations when using a Python project too. Not sure if related, but when trying to add additional dependencies in my projects `virtualenv`, they also are unable to be found when executing on the cloud.

**Comment by xdmtk** [comment]
For anyone who might be wondering:

It's not entirely clear from the Pulumi documentation that the `pulumi` modules cannot actually be used in a Lambda execution context. While I've realized now that the Pulumi `config` secrets should be injected as environment variables for a Lambda function in the 'Infra-As-Code' portion of the project, I initially thought I could utilize the Pulumi module inside the Lambda callback to get `config` secrets on the fly and in the cloud. If I could suggest anything, it might be to make this issue clear in the documentation surrounding AWS Lambda Functions and Pulumi.

**Comment by yomofo2s** [comment]
I am trying to provision an instance on vsphere using typescript- vsphere
@xdmtk After i injected my pulumi config secret in to the environment variables. Then i could not validate my provider configuration for my vsphere, i noticed that it has changed my pulumi.yaml config.
`config:
  vsphere:password:
    secure: rvuc/euYmCoHdDWPESJZ2Q=
  vsphere:server: servername
  vsphere:user: username
`
This is the error that i receive
`    error: could not validate provider configuration: 1 error occurred:
        * Invalid or unknown key`

Any help would be greartly appreciated.

**Comment by lakindu2002** [comment]
Anyone found a fix? I'm getting the same error right now.
