### ISSUE TITLE
GitHub Action can sometimes fail to install plugins

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#5479]
Reported by several users from the community.

While using the GitHub Actions Docker image, sometimes the plugin acquisition will fail:

```
  pulumi:providers:aws (default_3_2_1):                                                                                                                                                                         
    error: no resource plugin 'aws-v3.2.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v3.2.1`
```

A community user managed to track down a little bit more information:

> FYI i fixed this issue, still not 100% sure but its something to do with the stack not being deployed at all yet and running it in the docker container which means that the 'state' (output of pulumi stack export doesn't have an aws provider linked to it.) This appears to be required for the docker image to download the provider plugin
deploying from my local machine through pulumi fixed the issue in the docker container as the state had been 'created'

**Comment by RobbieMcKinstry** [comment]
Hey Lee, I think this issue is now stale enough to close. As you know, the GitHub Action no longer uses Docker, and has since been rewritten in pure TypeScript. If we find further evidence of failed plugin downloads, we can open an issue in https://github.com/pulumi/actions
