### ISSUE TITLE
Pulumi v2.11.1 Release 

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#5491]
https://github.com/pulumi/pulumi/issues/5482 was a bust, so here's the fix

- [x] language SDKs and CLI
- [x] homebrew
- [x] dockerhub
- [x] slim docker images
- [x] docs and marked as latest-version https://github.com/pulumi/docs/pull/4326/files
- [x] Chocolatey

**Comment by jaxxstorm** [comment]
Build is here: https://travis-ci.com/github/pulumi/pulumi/jobs/393385251

Linux is finished

**Comment by leezen** [comment]
Darwin build finished and published, but the Homebrew step failed. Will run that manually.

**Comment by leezen** [comment]
Homebrew: https://github.com/Homebrew/homebrew-core/pull/61798

**Comment by AaronFriel** [comment]
@jaxxstorm @leezen thank you!
