### ISSUE TITLE
Error running CrossGuard policies in pulumi/pulumi-nodejs Docker image

### ISSUE THREAD

**Issue by lukemundy-vgw** [pulumi/pulumi#5500]
having problems using the pulumi/pulumi-nodejs docker image to deploy my template, seems to be an issue installing whatever plugin is required to run CrossGuard policies.

here's the command i'm running:

```
docker run -v $(pwd):/pulumi/projects -e PULUMI_ACCESS_TOKEN -it pulumi/pulumi-nodejs:latest /bin/bash -c "npm ci && pulumi preview"
```

and here's the output from the pulumi up command

```
Logging in using access token from PULUMI_ACCESS_TOKEN
Previewing update (my-stack):
Installing policy pack vgw-sec-policies 3.0.2...
[resource plugin aws-2.13.1] installing
Finished installing policy pack


error: could not start policy pack "vgw-sec-policies" because the built-in analyzer plugin that runs policy plugins is missing. This might occur when the plugin directory is not on your $PATH, or when the installed version of the Pulumi SDK does not support resource policies
```

any ideas what I can do to resolve this?

discussion thread of the issue in community slack: https://pulumi-community.slack.com/archives/C84L4E3N1/p1601551989160900

@jaxxstorm

**Comment by leezen** [comment]
I believe https://github.com/pulumi/pulumi/pull/5495 should address this. I believe the latest tag had this change -- do you mind giving it a try and letting us know if that works?

**Comment by lukemundy-vgw** [comment]
it appears to work now, however the pulumi command is now outputting a huge amount of what looks like stream debugging information during the operation, which also seems to cause it to take much longer than usual. the command completes successfully though.

I ran a `pulumi preview` in the new image (sha hash `43953e33b56`) and got over 100k lines of stuff similar to the following:

```
    send: reset nghttp2_active_outbound_item
    send: aob->item = 0x55bae5be9b28
    stream: adjusting kept idle streams num_idle_streams=0, max=100
    send: next frame: payloadlen=8, type=7, flags=0x00, stream_id=0
    send: start transmitting frame type=7, length=17
    stream: adjusting kept idle streams num_idle_streams=0, max=100
    send: end transmission of a frame
```
has a debug build of the pulumi cli been used or something?

**Comment by leezen** [comment]
As a workaround, the `2.11.2` tag does not exhibit this behavior.

**Comment by leezen** [comment]
@jaxxstorm I suspect this has something to do w/ the ubi image. I see the same behavior in `2.11.2-ubi` but not `2.11.2` (which is debian)

**Comment by lukehoban** [comment]
This was fixed some time ago.
