### ISSUE TITLE
Structured configuration not supported in Automation API

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi#5506]
## Expected Behavior

I need a programmatic counterpart of structured configuraiton.

## Current Behavior

I can only set a single value (`SetConfig`) or all values at once `SetAllConfig`), but structured config doesn't seem to be supported at the moment

## Context (Environment)

* https://www.pulumi.com/docs/intro/concepts/config/#structured-configuration
* https://github.com/pulumi/pulumi/blob/3be1ea9592b305df8aeb83c3810aee9bb8adeb7a/sdk/go/x/auto/local_workspace.go#L166-L184

## Support

- [x] [Go](https://github.com/pulumi/pulumi/pull/12265)
- [x] https://github.com/pulumi/pulumi/pull/13052
- [x] https://github.com/pulumi/pulumi/pull/14305
- [x] https://github.com/pulumi/pulumi-dotnet/pull/191

**Comment by EvanBoyle** [comment]
As a workaround, is it possible to read the entire top-level config entry, change the appropriate property, and then write it back?

**Comment by ringods** [comment]
@EvanBoyle I don't understand what you hint here.

There is no config yet in my case: I developped my stack with structured config and now using the automation api rolling out customer specific versions of that stack. This means I have a Git workspace, upserting the stack after configuring it.

**Comment by EvanBoyle** [comment]
So you want to set a leaf value: 

```
SetConfig("a.b.c.d", "foo");
```

This is equivalent to:

```
val = {
b: {
c: {
d: "foo"
}
}
}

SetConfig("a", toJSON(val))
```

**Comment by alexeyzimarev** [comment]
If the config object has one of the leaf as a secret, I would assume it won't work.

**Comment by alexeyzimarev** [comment]
Oh, I see, the whole object is set as secret if one value is a secret value.

**Comment by tmccombs** [comment]
> So you want to set a leaf value:
> 
> SetConfig("a.b.c.d", "foo");
> 
> This is equivalent to:
> 
> val = {
> b: {
> c: {
> d: "foo"
> }
> }
> }
> 
> SetConfig("a", toJSON(val))
> 

It doesn't look like that works.   With the equivalent (I think) code:
``` 
await stack.setConfig("a", {
      value: JSON.stringify({
        b: {
          c: {
            d: "foo",
          },
        },
      }),
    });

```
I get config that looks like:

```  
  my-stack:a: '{"b":{"c":{"d":"foo"}}}'
```

**Comment by JaveriaK** [comment]
Just want to chime in that updating leaf values through setConfig doesn’t work.

code:

```golang
	pItem, err := stack.GetConfig(ctx, Params.ListKey)
	if err != nil {
		return MajorError, fmt.Errorf(“[Error]: Parameter %v does not exist in stack”, Params.ListKey)
	}
	var arr []map[string]interface{}
	_ = json.Unmarshal([]byte(pItem.Value), &arr)
	for _, elements := range arr {
		if elements[“apiVersion”] != Params.Value {
			elements[“apiVersion”] = Params.Value
		}
	}
	outList, _ := json.Marshal(&arr)
	err = stack.SetConfig(ctx, Params.ListKey, auto.ConfigValue{
		Value:  string(outList),
		Secret: false,
	})
	if err != nil {
		return MajorError, fmt.Errorf(“[Error]: Error Updating Stack %v”, err)
	}
```

generated change in stack file:
```yaml
-  kubernetes:platform_pools:
-  - apiVersion: 1.19.11
-    name: platform1
-    resourceName: platform-pool
-    vmSize: Standard_D16s_v3
+  kubernetes:platform_pools: ‘[{“apiVersion”:“1.21.4",“name”:“platform1",“resourceName”:“platform-pool”,“vmSize”:“Standard_D16s_v3"}]’
```

Neither does trying to get leaf elements work: `stack.GetConfig(ctx, kubernetes:platform_pools[0].apiVersion)`

**Comment by radirobi** [comment]
Dear @EvanBoyle,

could you tell me how to achieve the following structured config by using Pulumi GO sdk:
`config:
  azure-native:location: WestUS
  myNamepace:myStorage:
    name: myStorageName
    size: 50`

**Comment by shreecodes** [comment]
As a workaround to this issue, we're thinking about writing our own helper function that invokes the CLI with `pulumi config set --path ... --non-interactive` with an optional `--secret`. The automation SDK is a wrapper around the CLI, after all.

This approach might be a little fragile if/when the CLI changes in the future... but are there any other reasons to avoid this approach?

**Comment by Aylr** [comment]
Is there any update on if/when the Automation API might support structured configuration? Has anyone else here found a decent workaround?

**Comment by mDemianchuk** [comment]
+1, any update on the `--path` support?

**Comment by coopbri** [comment]
> Is there any update on if/when the Automation API might support structured configuration? Has anyone else here found a decent workaround?

Hey @Aylr, I'm not sure if you've tried this already but processing structured config as a JSON string works for me.

E.g. for an array/list:

```ts
await stack.setConfig("test:array", {
  value: JSON.stringify(["value1", "value2"]),
});

console.log(await stack.getConfig("test:array"));
// output: { value: '["value1","value2"]', secret: false }, works properly in program
```

**Comment by iamcaleberic** [comment]
Has anyone figured any workaround to pass lists with the automation API in golang? it's quite limiting at the moment.

```
# Pulumi.yaml
nodePool:
  description: Node pool for cluster
  type: array
  items: 
  - name:nodeCount:preemptible:machineType
```


```
# Pulumi.stack-name.yaml
nodePools:
  - name: primary
    nodeCount: 1
    preemptible: true
    machineType: "e2-medium"
```

The suggested workaround with top level config key does not really work as described.

**Comment by justinvp** [comment]
Added Node.js and .NET support in https://github.com/pulumi/pulumi/pull/14305 and https://github.com/pulumi/pulumi-dotnet/pull/191

**Comment by EronWright** [comment]
A quick comment on a remaining gap:  `stack.GetAllConfig()` doesn't fully support structured config because it doesn't accept a path or return object values.  A possible workaround is to use `stack.StackSettings()`?

**Comment by sfc-gh-jlangefeld** [comment]
+1 to @EronWright's question. It is a bit confusing that the `stack` object can't set objects as config, but a `*workspace.ProjectStack` object retrieved via `stack.Workspace().StackSettings(ctx, "stack")` can via `a.Config.Set(key, value, true)`.

**Comment by yambottle** [comment]
```
proj_infra_stack.set_config(
        "proj-infra:gh-usernames",
        auto.ConfigValue(value=os.getenv("GH_USERNAMES").split(",")),
    )
# Gives me: TypeError: expected str, bytes or os.PathLike object, not list
```

**Comment by farvour** [comment]
> ```
> proj_infra_stack.set_config(
>         "proj-infra:gh-usernames",
>         auto.ConfigValue(value=os.getenv("GH_USERNAMES").split(",")),
>     )
> # Gives me: TypeError: expected str, bytes or os.PathLike object, not list
> ```

Yeah I ran into this oddity .. since the automation API just passes the set config the same way the CLI expects, you have to use the path-spec and iterate your list and set each element individually.

Like:
```
s3_buckets = cast(dict[str, Any], dig(self.env_config, "s3_buckets"))
logger.info("Creating S3 buckets", project=project, buckets=list(s3_buckets.keys()))
  for i, s3_bucket in enumerate(s3_buckets.keys(), 0):
  stack.set_config(f"buckets[{i}]", ConfigValue(s3_bucket), path=True)
```

**Comment by yambottle** [comment]
> > ```
> > proj_infra_stack.set_config(
> >         "proj-infra:gh-usernames",
> >         auto.ConfigValue(value=os.getenv("GH_USERNAMES").split(",")),
> >     )
> > # Gives me: TypeError: expected str, bytes or os.PathLike object, not list
> > ```
> 
> Yeah I ran into this oddity .. since the automation API just passes the set config the same way the CLI expects, you have to use the path-spec and iterate your list and set each element individually.
> 
> Like:
> 
> ```
> s3_buckets = cast(dict[str, Any], dig(self.env_config, "s3_buckets"))
> logger.info("Creating S3 buckets", project=project, buckets=list(s3_buckets.keys()))
>   for i, s3_bucket in enumerate(s3_buckets.keys(), 0):
>   stack.set_config(f"buckets[{i}]", ConfigValue(s3_bucket), path=True)
> ```
> 
> This process is horribly slow when you have a lot of values, too, since it has to invoke pulumi n-number of times to do so. It may be faster with `set_all_config()` but either way, the path-spec nuance is annoying.

I ended up with setting configs with json string and then instead of `config.require_object`, use `config.require + json.loads`, inspired by [require_object](https://www.pulumi.com/docs/reference/pkg/python/pulumi/#pulumi.Config.require_object) doc:
```
proj_infra_stack.set_config(
        "proj-infra:gh-usernames",
        auto.ConfigValue(value=os.getenv("GH_USERNAMES")),
    )
# then later
gh_usernames = json.loads(config.require("gh-usernames"))
```

**Comment by EronWright** [comment]
A new related feature: https://github.com/pulumi/pulumi/pull/19427
