### ISSUE TITLE
Stack files do not specify what organization they belong to - leading to ambiguity

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#5510]
If I am a member of two orgs (say `acme` and `emca`) and create a `dev` stack of the `s3-sample` project in both organizations, I will end up with the same `Pulumi.dev.yaml` file being used for both stacks inside the project folder.  This makes it impossible to make changes to one stack without impacting the other.  

Worse, even if I am only a member of one organization - but I collaborate on a project codebase with others who are part of other organizations - one of us may check in a `Pulumi.dev.yaml` that is intended for the `acme` org, and the other will see it and expect it to be for the `ecma` org.  Because best practice is to check these files in, this will be common in any case where a single project codebase is used across organizations.

**Comment by clstokes** [comment]
Closing because duplicate of #5511.
