### ISSUE TITLE
Python: Adding mapping type parameter does not work

### ISSUE THREAD

**Issue by mszewczyk-ipwt** [pulumi/pulumi#5516]
I work in Python 3.8.5 and when I try to add Mapping type object to a resource the Pulumi update or preview is stuck endlessly on log `debug: looking for resolver using translated name...`. The particular bug I found is related to the resource and property in this link -> https://www.pulumi.com/docs/reference/pkg/gcp/cloudfunctions/function/#environment_variables_python . 

In my code I have something like this:
```
import pulumi
import pulumi_gcp

some_function = pulumi_gcp.cloudfunctions.Function(
  f'{environment_name}_function',
  runtime='python37',
  entrypoint='call_function',
  source_archive_bucket=function_bucket.name,
  source_archive_object=function_object.name,
  project=gcp_project,
  region=region,
  trigger_http=True,
  environment_variables=dict(
    something='interesting'
  )
)
```
And with this declaration I'm not even able to finish generating preview. Pulumi is only showing this part of output:
```
Previewing update (dev):
     Type                            Name                                    Plan        Info
     pulumi:pulumi:Stack             customproject-dev                                   1 error; 1853 debugs
 ~   ├─ gcp:projects:IAMCustomRole   dev-role                                update      [diff: ~permissions]
 +-  ├─ gcp:projects:IAMMember       dev-member                              replace     [diff: ~role]
 ~   └─ gcp:cloudfunctions:Function  dev_function                            update      [diff: -labels~environmentVariables]

Diagnostics:
  pulumi:pulumi:Stack (customproject-dev):
    error: preview canceled
```
Pulumi is stuck on the debug message `debug: looking for resolver using translated name ip_address` (which is irrelevant to the object I'm changing). I am forced to SIGINT the process and then the error `error: preview canceled` appears. There is no other error when I'm trying to find within logs.
When I remove the `environment_variables` property, then the preview is generated properly and I don't have to SIGINT the process:
```
Previewing update (dev):
     Type                            Name                                    Plan        Info
     pulumi:pulumi:Stack             customproject-dev                                      
 ~   ├─ gcp:projects:IAMCustomRole   dev-role                                update      [diff: ~permissions]
 +-  ├─ gcp:projects:IAMMember       dev-member                              replace     [diff: ~role]
 ~   └─ gcp:cloudfunctions:Function  dev_function                            update      [diff: -labels]
 
Resources:
    ~ 2 to update
    +-1 to replace
    3 changes. 33 unchanged
```
This also happens when I'm trying to declare [labels](https://www.pulumi.com/docs/reference/pkg/gcp/cloudfunctions/function/#labels_python) parameter which is also the same type of `Mapping[str, any]`. I tried also using different types of variables like lists or even declaring the dictionary using `{}` and nothing worked.

## Expected Behavior
`pulumi preview` and also `pulumi up` should work and show what is wrong with the parameter.

## Current Behavior
`pulumi preview` and also `pulumi up` is stuck on irrelevant debug message and nothing is moving on.

## Steps to Reproduce
1. Create a code for pulumi in python 3
2. Declare a resource with parameter that has type of `Mapping[str, any]`
3. Attempt to update the resource

## Context (Environment)
What I want to achieve right now is to deploy to GCP a Cloud Function that has to have environment variables declared, but with this bug I'm forced to declare it manually using Gcloud console.

**Comment by leezen** [comment]
Could you please confirm which version of `pulumi-gcp` and `pulumi` you are you using? I'm having trouble reproducing this w/ the following:

```
py_function = cloudfunctions.Function(
    "python-func",
    source_archive_bucket=bucket.name,
    runtime="python37",
    source_archive_object=py_bucket_object.name,
    entry_point="handler",
    trigger_http="true",
    available_memory_mb=128,
    environment_variables=dict(test='this')
)
```

Altering the dictionary, I'm still able to successfully preview and update.

**Comment by mszewczyk-ipwt** [comment]
Thanks @leezen for the hint, I purged my workspace, so probably there was an issue with having old version of dependencies in virtual env. right now it is working.
