### ISSUE TITLE
Is there a way to tell pulumi that resources which are in pending_operations has been created

### ISSUE THREAD

**Issue by boillodmanuel** [pulumi/pulumi#5517]
In some cases, `pulumi up` fails during an update.
If there are `pending_operations` in the state, the [documentation](https://www.pulumi.com/docs/troubleshooting/#interrupted-update-recovery) said that we should remove the cloud resourced manually and do a refresh in order to start again a the `pulumi up`.

## Expected Behavior

In some case, the cloud resource is well created, and I want to tell to pulumi that resources in `pending_operations` are well created. I tried to manually move the resources to the `resources` list and reimport the state but this didn't work.

In my case, the resource creation is an Azure Virtual Network Gateway, and the creation lasts ~20/30min
Is there another solution?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by leezen** [comment]
When you say you tried to reimport the state, are you using the `import` flag for the resource in code? The way I would expect this to work is:

1. Remove the resource from pending operations
2. Lookup the name of the resource in the cloud provider
3. Update your code such that it reads:
    ```
    const foo = new Resource(..., { import: 'import-id' })
    ```
    for the failed resource
    (see also https://www.pulumi.com/docs/intro/concepts/programming-model/#import)

**Comment by boillodmanuel** [comment]
No, I didn't import the resource from its id in code.
What I did is :
- exporting the state
- editing the state
  - I moved all resources that was in the `deployment.pending_operations` array (actually the content of the `resource` value for each item) to the `deployment.resources` array.
- importing the state
- run `pulumi refresh` => got a go error 

Example of state with pending_operations:


```json
{
    "version": 3,
    "deployment": {
        "resources": [],
        "pending_operations": [
            {
                "resource": {
                    "urn": "urn:pulumi:sandbox::network-hub::azure:network/subnet:Subnet::snet-hub",
                    "custom": true,
                    "type": "azure:network/subnet:Subnet",
                    "inputs": {
                        "__defaults": [
                            "enforcePrivateLinkEndpointNetworkPolicies",
                            "enforcePrivateLinkServiceNetworkPolicies"
                        ],
                        "addressPrefixes": [
                            "172.24.239.32/27"
                        ],
                        "enforcePrivateLinkEndpointNetworkPolicies": false,
                        "enforcePrivateLinkServiceNetworkPolicies": false,
                        "name": "snet-hub",
                        "resourceGroupName": "rg-hub",
                        "virtualNetworkName": "vnet-hub"
                    },
                    "parent": "urn:pulumi:sandbox::network-hub::pulumi:pulumi:Stack::network-hub",
                    "propertyDependencies": {
                        "addressPrefixes": null,
                        "name": null,
                        "resourceGroupName": [
                            "urn:pulumi:sandbox::network-hub::azure:core/resourceGroup:ResourceGroup::rg-hub"
                        ],
                        "virtualNetworkName": [
                            "urn:pulumi:sandbox::network-hub::azure:network/virtualNetwork:VirtualNetwork::vnet-hub"
                        ]
                    }
                },
                "type": "creating"
            }
        ]
    }
}
```

Result after having moved the pending_operations into resources:

```json
{
    "version": 3,
    "deployment": {
        "resources": [
            {
                "urn": "urn:pulumi:sandbox::network-hub::azure:network/subnet:Subnet::snet-hub",
                "custom": true,
                "type": "azure:network/subnet:Subnet",
                "inputs": {
                    "__defaults": [
                        "enforcePrivateLinkEndpointNetworkPolicies",
                        "enforcePrivateLinkServiceNetworkPolicies"
                    ],
                    "addressPrefixes": [
                        "172.24.239.32/27"
                    ],
                    "enforcePrivateLinkEndpointNetworkPolicies": false,
                    "enforcePrivateLinkServiceNetworkPolicies": false,
                    "name": "snet-hub",
                    "resourceGroupName": "rg-hub",
                    "virtualNetworkName": "vnet-hub"
                },
                "parent": "urn:pulumi:sandbox::network-hub::pulumi:pulumi:Stack::network-hub",
                "propertyDependencies": {
                    "addressPrefixes": null,
                    "name": null,
                    "resourceGroupName": [
                        "urn:pulumi:sandbox::network-hub::azure:core/resourceGroup:ResourceGroup::rg-hub"
                    ],
                    "virtualNetworkName": [
                        "urn:pulumi:sandbox::network-hub::azure:network/virtualNetwork:VirtualNetwork::vnet-hub"
                    ]
                }
            }
        ]
    }
}

```

**Comment by leezen** [comment]
I see. I think the easiest way to fix up the state is the method I suggested. Do you mind giving that a try?

**Comment by boillodmanuel** [comment]
I already fixed my stack by deleting the cloud resources, but if there was
somehow a way to just flag pending operation as done, following by a
refresh if needed, it could simplify the resolution.

Best regards

**Comment by leezen** [comment]
Thanks for the feedback. Having an easier way to mark pending operations as complete is tracked in https://github.com/pulumi/pulumi/issues/4265

**Comment by boillodmanuel** [comment]
I just figured out that `id` property was missing. I guess I just have to add it and reimport the stack, like this (I will give it a try next time):

```json
{
    "version": 3,
    "deployment": {
        "resources": [
            {
                "urn": "urn:pulumi:sandbox::network-hub::azure:network/subnet:Subnet::snet-hub",
                "custom": true,
                "id": "ADD ID HERE",
                "type": "azure:network/subnet:Subnet",
...
            }
        ]
    }
}
```

I know that importing in code would works but it's not easy when `pulumi up` is done only in CI/CD pipeline.

For what it worths, we could have commands like this:
```bash
pulumi state pending-operations
# => List pendings operations with their urns

pulumi state fix-pending-operations --target "URN" --import-id "REAL ID"
# => Fix one pending operation
```
