### ISSUE TITLE
Allow `pulumi up` without building .NET project

### ISSUE THREAD

**Issue by koliyo** [pulumi/pulumi#5529]
I have a .NET Pulumi stack that can read dynamic configuration from external files / environment.

I would really like to be able to run `pulumi up` without rebuilding the project every time. Please add an optional flag for this, should be very simple to just skip the build stage?

**Comment by mikhailshilkov** [comment]
You can do this today with the `binary` project option, see https://www.pulumi.com/docs/intro/concepts/project/
