### ISSUE TITLE
CLI verbose flag is broken

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi#5535]
When trying to install plugins, the verbose flag is not being recognized.

## Expected Behavior
Additional logs are output.

## Current Behavior
> An error occurred: unknown shorthand flag: 'v' in -v

## Steps to Reproduce

1. Run `pulumi plugin install resource azure v3.20 -v 3`

## Context (Environment)

I was trying to see if there were any logs that could help with https://github.com/pulumi/pulumi/issues/2695

## Workaround

From [Slack](https://pulumi-community.slack.com/archives/C84L4E3N1/p1602189896364200): `pulumi --verbose=true plugin install resource azure v3.20`

**Comment by stack72** [comment]
Hey @MisinformedDNA 

Apologies that this tripped you up :/ This was reported by @clstokes a while back so I am going link the issues and close this out as a dupe

I hope we can get this fixed up soon for you

https://github.com/pulumi/pulumi/issues/4427

Paul
