### ISSUE TITLE
npm sub-dependecies not always included in lambda function closure bundle

### ISSUE THREAD

**Issue by JeromeMutgeert** [pulumi/pulumi#5555]
We are managing 32 lambda functions on AWS in a single pulumi project in typescript.
Since I included axios 0.19.2 as dependecy in package.json I am encountering inconsistent pulumi closure bundles accross updates.

## Current Behavior

Axios 0.19.2 has a sub-dependecy follow-redirects 1.5.10. This sub-depenedecy appears to not be included in the first 3 lambda function code bundles from the update order when running pulumi up, as can be seen in the stack export json.

The consequences are that when running pulumi up -y several times without changing any code, there keeps showing diff in the previews. The actual non-dry updates even seem to be inconsistent with their preceding previews: 

I've encountered a preview where the follow-redirects package was added to one arbitrary lambda and removed from another, and when I chose 'yes', in the end nothing had happened.

## Expected Behavior

The follow-redirects package should always be included with all lambda functions, and a pulumi up dry run should be consistent with the actual update.

## Context (Environment)

I have alredy found a fix by including follow-redirects 1.5.10 as a direct dependecy.

I am running on an Intel core i7-7700HQ @ 2.8GHz x8 with 15,6 GiB memory on Ubuntu 18.04, with nodejs v12.18.4 and pulumi engine v2.11.2, and the following pulumi npm packages:
        "@pulumi/aws": "3.2.0",
        "@pulumi/awsx": "0.21.0",
        "@pulumi/pulumi": "2.9.0",

## Steps to Reproduce

I do not wish to share our entire code base. It seems that direct dependecies are included, but that sub-dependecy inclusion might be dependant on some missing await somewhere. I hope the summary provides enough clarity of what might be going on. If you can indeed find a spot to insert an await that might fix this, that would be great news. If not, I can see if I can provide some more info.

**Comment by leezen** [comment]
Some additional information would be helpful here. In particular, how do you import axios into your program? Is it imported within the function closure or outside of it? If outside, have you tried importing it within the function closure itself?

**Comment by JeromeMutgeert** [comment]
In fact, Axios is only used by a one of the 32 lambda functions, and this method is declared in a separate file and Axios is imported only there. I guess this means that it is indeed not imported in the function closure of the lambda functions that do not use it.

Note that I already found a fix for my problem. I think moving the import statement, if it would work too, would be a comparable fix as putting follow-redirects as a direct dependency. Should I test it? 

I even think for my case Axios and follow-redirects could as well be left out of the bundles of the 31 other lambdas, simply because it's not imported within the closures. That would also fix it. Wouldn't that be always desirable?

**Comment by leezen** [comment]
Yes, I believe it should be the case that if you move the import, that could work. It really depends on the overall structure of your imports and where they take place. Generally speaking, if you don't need the import as part of your program itself and it's only needed at function runtime, then importing it like the following is preferred:

```typescript
...
const fn = new aws.lambda.CallbackFunction("fn", {
    callback: async () => {
        const axios = (await import("axios")).default;
        ...
    }
});
...
```

**Comment by mikhailshilkov** [comment]
The last reply makes sense to me and the issue has been quiet for 1.4 years, so I'll take the liberty to close it as by-design. Let me know if you'd like to provide additional context and keep it open.
