### ISSUE TITLE
watch mode panics with a policy pack in place

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5561]
#### Problem

If I run `pulumi watch` with a policy pack enabled for my Pulumi organization, the Pulumi CLI will panic and exit.

Pulumi CLI version: `v2.11.2`

#### Error

```
% pulumi watch
Watching (demo/dev):
21:25:35.732[                    ] Updating...
21:25:46.818[demo-aws-ts-webserve] create pulumi:pulumi:Stack
21:25:58.740[demo-aws-ts-webserve] done create pulumi:pulumi:Stack
panic: fatal: A failure has occurred: unknown event type 'policy-violation'

goroutine 47 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /private/tmp/pulumi-20201002-82311-wm0lqs/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Failf(0x54c5f42, 0x17, 0xc0004c1680, 0x1, 0x1)
        /private/tmp/pulumi-20201002-82311-wm0lqs/sdk/go/common/util/contract/fail.go:30 +0x18d
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowWatchEvents(0x54ad686, 0x8, 0x54ab33e, 0x6, 0xc000181200, 0xc000181260, 0x54aa54c, 0x6, 0x10100000000, 0x3, ...)
        /private/tmp/pulumi-20201002-82311-wm0lqs/pkg/backend/display/watch.go:81 +0x1d2
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowEvents(0x54ad686, 0x8, 0x54ab33e, 0x6, 0xc00030c3cc, 0x3, 0xc00003fa00, 0x15, 0xc000181200, 0xc000181260, ...)
        /private/tmp/pulumi-20201002-82311-wm0lqs/pkg/backend/display/display.go:60 +0x2d5
created by github.com/pulumi/pulumi/pkg/v2/backend/httpstate.(*cloudUpdate).RecordAndDisplayEvents
        /private/tmp/pulumi-20201002-82311-wm0lqs/pkg/backend/httpstate/state.go:205 +0x21a
```

#### Steps to reproduce

1. [publish and enable a policy pack for your organization](https://www.pulumi.com/docs/get-started/crossguard/enforcing-a-policy-pack/)
1. run `pulumi watch` on a project and stack in the same org as your enabled policy pack

**Comment by clstokes** [comment]
The panic also causes the stack to be left in a "conflict" state on subsequent run.

e.g.

```
% pulumi destroy -y --skip-preview 
Destroying (demo/dev)

error: [409] Conflict: Another update is currently in progress.
To learn more about possible reasons and resolution, visit https://www.pulumi.com/docs/troubleshooting/#conflict
```

**Comment by stack72** [comment]
@clstokes lets talk about what you would expect the behaviour to be here

**Comment by clstokes** [comment]
Not meant as a flippant response... I would expect it to not panic and to successfully run the policy pack(s). If there's more that you need, let me know.

**Comment by stack72** [comment]
Sorry @clstokes i should have been more clear here - what I mean is, how do you expect the watch functionality to work with policies in general - not around this specific panic

Would you expect to see the policy warnings / violations appear as part of the output or should we just fix the panic and work that part out later?

**Comment by clstokes** [comment]
Let's fix the panic for now so that watch is usable. A simple "policy packs passed" or "policy packs failed" message in the watch output is fine for now in my opinion.
