### ISSUE TITLE
Normalize cloud URL during `login`

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5564]
#### Problem

It's possible for users to get in an awkward "state" where the cloud URL they use during `pulumi login` does not exactly match the secret provider backend configured for their state - e.g. `https://api.pulumi.com/` vs `https://api.pulumi.com` (no trailing slash). This results in a confusing error message during pulumi commands.

#### Error output

```
% pulumi pre
Previewing update (dev)

View Live: https://app.pulumi.com/clstokes/p-secrets-url-slash/dev/previews/53ece0ee-6508-4041-9f28-f956c516eff5

error: could not deserialize deployment: constructing secrets manager of type "service": could not find access token for https://api.pulumi.com, have you logged in?
```

#### Steps to reproduce

1. `rm ~/.pulumi/credentials.json`
1. `pulumi login`
    1. will result in `https://api.pulumi.com` being stored in `~/.pulumi/credentials.json` and the stack state after the `up -y` below
1. `mkdir p-secrets-url-slash && cd p-secrets-url-slash`
1. `pulumi new typescript -y`
1. `pulumi config set --secret mySecret asdf`
1. `pulumi up -y`
1. `pulumi logout`
1. `pulumi login https://api.pulumi.com/` (with trailing slash)
    1. will result in `https://api.pulumi.com/` being stored in `~/.pulumi/credentials.json` and cause the error in the next step
1. `pulumi preview` - observe error

#### Suggestions for a fix 

Normalize the cloud URL during `pulumi login` to match the canonical form expected in the stack state, which _seems_ to be no trailing slash.

**Comment by chrsmith** [comment]
Traveling down the road of URL canonicalization can only lead to madness... but obviously we shouldn't fail for mundane things like if the URL ends with a slash or not. Good catch!
