### ISSUE TITLE
Improve coverage of plugin to gRPC bridges

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#5574]
This does reinforce an irritating hole in our test coverage: while we have great coverage of the high-level plugin interfaces, we have worse coverage of the plugin -> gRPC bridges. We should think about how we can improve this coverage (e.g. by adding support for previews to the dynamic provider, perhaps as a config option).

_Originally posted by @pgavlin in https://github.com/pulumi/pulumi/pull/5562#issuecomment-707944076_

**Comment by mikhailshilkov** [comment]
My feeling is that this issue doesn't carry enough value two years in its existence. We do need to improve our test coverage but we'll track it elsewhere.
