### ISSUE TITLE
[Automation API] Unintuitive behavior with relative paths (FileAsset, closure serialization) and inline programs

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#5578]
Automation API inline programs create a temporary working directory (unless directly specified) to store pulumi.yaml and to invoke the CLI. This breaks any relative path references the user may define in their inline program:

```ts
const pulumiProgram = () async => {
// at runtime this actually resolves to $AUTOMATION_API_TEMP/build
const relative = "./build"
}
```

We have a few options:

1. Change Automation API to use `.` as the current working dir. This preserves relative paths, but has the downside of leaking files like `pulumi.yaml` and `pulumi.stack.yaml` which the user might not care about or might find confusing to see generated out of nowhere. 
2. Document this behavior and leave it as is. encourage users to only use absolute paths with inline programs. 
3. Do some sort of deeper fix where we specify the temp directory to be used only for settings (yaml files), and use `.` as the CWD for program execution.

**Comment by EvanBoyle** [comment]
Note that this likely breaks closure serialization as `node_modules` won't be in the expected location.

**Comment by EvanBoyle** [comment]
To be clear the current work around it to set an explicit workdir when creating the stack or workspace:

```ts
const args = {
stack: "",
project: "",
program ()=> {},
workDir: ".", // set work dir to current directory
}
```

**Comment by barclayadam** [comment]
To add to this the breakage goes further, as dynamic resources cannot be used without the workaround as dynamic module cannot be found:

`Error: Cannot find module '@pulumi/pulumi/cmd/dynamic-provider'` as well `could not read plugin [C:\Users\barcl\.pulumi\bin\pulumi-resource-pulumi-nodejs.cmd] stdout: EOF.`

Forcing the current workDir makes this work, but can cause further problems due to the files that end up on disk. I think related to #5679 the files on disk can cause issues if you have multiple inline programs with same named stacks but different projects / configs / programs (I've not tracked down exactly the issue).

**Comment by EvanBoyle** [comment]
@barclayadam thanks for reporting. I need some time to think through a resolution here.

**Comment by roderik** [comment]
I had the same issue using the eks package in the automation API.
However, now it writes yaml files in the root of my application, introducing another concurrency issue.

**Comment by EvanBoyle** [comment]
@roderik not ideal, but as a possible workaround in the meantime (I have not tried this): you may be able to allocate a temp directory to use as your working dir, and symlink your node_modules folder into it. That way you don't pollute a common directory with `pulumi.stack.yaml` files that could potentially collide.

**Comment by lukehoban** [comment]
> Do some sort of deeper fix where we specify the temp directory to be used only for settings (yaml files), and use . as the CWD for program execution.

Can we use the `main:` setting in the generated `Pulumi.yaml` to point back to the real working directory?

From https://www.pulumi.com/docs/intro/concepts/project/: 
> main: (optional) an override for the main program’s location. By default, the program’s working directory is assumed to be the location of Pulumi.yaml. To choose a different location, use the main property. For example, if your Pulumi program is in a subdirectory infra/, use main: infra/.

**Comment by EvanBoyle** [comment]
I prototyped a fix for this here: https://github.com/pulumi/pulumi/pull/6247

Still needs work, but my testing shows that the approach suggested by @lukehoban should work.

**Comment by EvanBoyle** [comment]
Reopening as I still need to make changes in the SDKs

**Comment by EvanBoyle** [comment]
https://github.com/pulumi/pulumi/pull/6743 Sets this main to os.CWD (or equivalent) for inline programs by default which will resolve issues in the common case. 

You can now control this behavior yourself by setting `main` in ProjectSettings.
