### ISSUE TITLE
GitHub Actions entrypoint script doesn't invoke pulumi on `rerequested` action

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#5583]
Duplicated issue from https://github.com/pulumi/actions/issues/20, by @samscott89:

> If pulumi actions runs on a [re-run check](https://developer.github.com/v3/activity/events/types/#checkrunevent), then it doesn't get picked up as needing preview:
> 
> >      PR event (null) contains no changes and does not warrant a Pulumi Preview
> 
> From https://github.com/pulumi/pulumi/blob/master/dist/actions/entrypoint.sh#L28

The issue is old enough that some of the docs and scripts have changed, but it appears to still be an issue. ~~It should just be a matter of adding another state to this allow list.~~

Here are the docs for the `pull_request` webhook event:
https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#pull_request

... but if I understand correctly, the problem is that we aren't hooking into the `check_suite`'s `rerequested` action.
https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#check_suite

**Comment by stack72** [comment]
I am going to close this issue out - the plans are to support a native GHA in q1 2021 so we will get support for that by default
