### ISSUE TITLE
Passing the same ResourceOptions instance to resources can result in failures related to the provider version

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5584]
Passing the same `ResourceOptions` instance to multiple resources can lead to failures related to the provider version.

Consider this Python program:

```python
from dataclasses import dataclass

from pulumi import ComponentResource, ResourceOptions
from pulumi_tls import PrivateKey
from pulumi_random import RandomPassword


@dataclass
class ThingsFromMultipleProvidersArgs:
    pass


class ThingsFromMultipleProviders(ComponentResource):
    def __init__(self, resource_name: str, args: ThingsFromMultipleProvidersArgs, opts: ResourceOptions = None):
        super().__init__("repro:ThingsFromMultipleProviders", resource_name, None, opts)

        child_opts = ResourceOptions.merge(opts, ResourceOptions(parent=self))

        self.tls_resource = PrivateKey(f"{resource_name}-tls-resource",
                                       algorithm="RSA",
                                       rsa_bits=2048,
                                       opts=child_opts)

        self.random_resource = RandomPassword(f"{resource_name}-random-resource",
                                              length=10,
                                              opts=child_opts)

        self.register_outputs({})


ThingsFromMultipleProviders("repro", ThingsFromMultipleProvidersArgs())
```

```
pulumi>=2.0.0,<3.0.0
pulumi-tls>=2.3.0,<3.0.0
pulumi-random>=2.3.1,<3.0.0
```

When `child_opts` is first passed to `pulumi_tls.PrivateKey`’s constructor, `child_opts.version` is set to `"2.3.0"`, the version of the installed `pulumi_tls` package.

https://github.com/pulumi/pulumi-tls/blob/af3a123633ce0d7239ebb3713275ae6b254ebb66/sdk/python/pulumi_tls/private_key.py#L46-L47

```python
if opts.version is None:
    opts.version = _utilities.get_version()
```

When that same `child_opts` instance is passed to `pulumi_random.RandomPassword`’s constructor, the version is already set to `"2.3.0"`, so that’s the value that’s used. Which is likely not the correct version for the `pulumi_random` package. If that version of the plugin is not installed, it results in a failure during `up`.

The TypeScript variants of these resources do a similar thing, so the same behavior likely happens there as well. (Need to check the behavior of the other languages).

One way we could consider addressing this would be to update our code generators to make the constructors of these resources make a copy of the passed-in opts before modifying it.

Until then, a workaround would be to do the copying manually before passing the opts to the resource. For example:

```python
import copy;

...

child_opts = ResourceOptions.merge(opts, ResourceOptions(parent=self))

self.tls_resource = PrivateKey(f"{resource_name}-tls-resource",
                                algorithm="RSA",
                                rsa_bits=2048,
                                opts=copy.copy(child_opts))

self.random_resource = RandomPassword(f"{resource_name}-random-resource",
                                        length=10,
                                        opts=copy.copy(child_opts))
```

**Comment by mikhailshilkov** [comment]
This is similar to https://github.com/pulumi/pulumi/issues/9548 that was fixed in https://github.com/pulumi/pulumi/pull/9802 and https://github.com/pulumi/pulumi/pull/9856
