### ISSUE TITLE
Pulumi should have a way to generate config from template without using new

### ISSUE THREAD

**Issue by Sytten** [pulumi/pulumi#5589]
It is very common for public projects to not commit their stack configuration. Because of the limitations of #5588 or other limitation, the creator might not want its users to download the project using new, but instead use `git`. The leaves the problem that there is currently no way to generate the config for a stack using the template as you would do with the `new` command.

## Expected Behavior

I should be able to do something like `pulumi config init` and it would ask me all the values from the template just like it does for the `pulumi new` command.

## Current Behavior

I have to write either an example config or put a bunch of `pulumi config set` in the README.

**Comment by justinvp** [comment]
Looks like a duplicate of https://github.com/pulumi/pulumi/issues/1793

**Comment by Sytten** [comment]
Agreed, closing
