### ISSUE TITLE
403 Error while creating Azure Storage Account

### ISSUE THREAD

**Issue by remojansen** [pulumi/pulumi#5609]
## Expected Behavior
The storage account should be created with no errors

## Current Behavior
```
Do you want to perform this update? yes
Updating (prod)

View Live: https://app.pulumi.com/remojansen/learning-ts-web-ui/prod/updates/2

     Type                      Name                     Status                  Info
     pulumi:pulumi:Stack       xxxxxx               **failed**              1 error
 ~   └─ azure:storage:Account  xxxxxx               **updating failed**     [diff: +allowBlobPublicAccess,minTlsVersion~__defaults,provider]; 1 erro

Diagnostics:
  pulumi:pulumi:Stack (xxxxxxxxxxxx):
    error: update failed

  azure:storage:Account (xxxxxxxxx):
    error: 1 error occurred:
        * updating urn:pulumi:prod::learning-ts-web-ui::azure:storage/account:Account::learningts: 
        Error reading queue properties for AzureRM Storage Account "xxxxxxxxx": queues.Client#GetServiceProperties: 
        Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. 
        Status=403 Code="AuthenticationFailed" Message="Server failed to authenticate the request. 
        Make sure the value of Authorization header is formed correctly including the signature.
        RequestId:37663721-c003-0015-31ef-a7b186000000\nTime:2020-10-21T21:16:13.3117447Z"
```

## Steps to Reproduce
```ts
const appName = "xxxxxxxxx";

const resourceGroup = new azure.core.ResourceGroup(appName, {
    location: azure.Locations.NorthEurope,
});

const storageAccount = new azure.storage.Account(appName, {
    resourceGroupName: resourceGroup.name,
    accountReplicationType: "LRS",
    accountTier: "Standard",
    accountKind: "StorageV2",
    staticWebsite: {
      indexDocument: "index.html",
    },
});
```

## Context (Environment)
I'm using:

```json
"devDependencies": {
    "@azure/arm-cdn": "5.0.0",
    "@pulumi/azure": "3.26.0",
    "@pulumi/pulumi": "2.12.0"
}
```

**Comment by remojansen** [comment]
Since this Pulumi package is based on the azurerm Terraform Provider. I think this could be related https://github.com/terraform-providers/terraform-provider-azurerm/issues/3997#issuecomment-523854160 ?

**Comment by leezen** [comment]
Can you please describe how you're authenticating and how your provider is configured?

**Comment by remojansen** [comment]
How can I find the provider details? I think I'm using the default. I have used az-login command.

**Comment by leezen** [comment]
Thanks. That's helpful. Just to confirm then, you're using `az login` and aren't setting up any additional parameters in such as in https://www.pulumi.com/docs/intro/cloud-providers/azure/setup/ correct?

**Comment by leezen** [comment]
The 403 makes me suspect a permissions issue on your end? I wasn't able to reproduce this via having credentials with `az login` and running the code provided. Any chance you've tried to create a storage account via the `az` command line and have that work?

**Comment by remojansen** [comment]
I have been using WLS 2.0 with Ubuntu I thought that maybe that could be the problem. So I switched to the window Powershell and it is now working.
