### ISSUE TITLE
Don't couple big changes in pulumi with breaking changes from upstream providers

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi#5627]
Please do not couple big changes from pulumi with big changes in providers. For example, GCP and Vault both have BC breaks in the same version that adds support for the provider preview functionality.

Unless there is a really good reason for this needing to be done, this now requires us to significantly test out our infrastructure code in order to have previews that are reliable.

**Comment by stack72** [comment]
Hi @nesl247 

My apologies here - this one was something we had a bit of a chicken and egg style scenario on. 

Let's start with GCP, we had code from upstream that was in master waiting for a release. These code changes were breaking changes to a number of datasource in their output parameters to be lists. We could have released v4.0.0 and then v4.1.0 for the preview functionality - and we should ensure that happens in future

With regards to Vault, the Vault provider was on an older version of the codegen. The upgrade of the codegen changed the package names (something that we didn't release in GCP as a major version but something we tried to do better with here). That upgraded codegen brought us in line with the new preview functionality BUT as this changed package names, we thought it best to major bump

For what it's worth, we did try to take on feedback from before about introducing major changes without major version bumps but it seems our process isn't quite smooth enough here.

There's definitely a case for us to learn again to make this even smoother

Paul

**Comment by nesl247** [comment]
Hey @stack72,

For GCP, I would have actually expected something completely different. Instead of a 4.0.0 and 4.1.0, I would have released 4.0 as you have, but created a branch from the last 3.0 release, and pulled in the preview change there. This allows everyone to get the benefits of the preview functionality without having to upgrade to a major release. This is something that `Symfony` does really well (it's a PHP framework).

Regarding the vault, that makes sense and unfortunately it's mostly just bad timing (us wanting the preview functionality coupled with you guys changing the codegen package names). Hopefully package names will not change again in the future, because this was an unfortunate change that I think a lot of people didn't see the benefit on, but I know it caused a lot of misc. issues for both you and your customers over the last several months. I see that here there really was no better option other than having the BC breaks and the preview functionality, given the circumstances.

I would definitely say that the handling of major version bumps has improved, but there is still room for improvement. Between the solution I mentioned with regards to the GCP versioning, to also just avoiding BC breaks unless they are truly really beneficial in some way.

I would imagine there are many users of pulumi that are small teams who are responsible for large amounts of infrastructure code. It's quite difficult to go back and test everything and make sure nothing breaks. Even with tests, there is still a lot of possibilities for breakages due to the simple fact of what pulumi is. Having multiple BC breaks a year (3.0 of GCP just came out this year for example) is not really sustainable IMO. Eventually people will start ending up on really old versions because it's just too hard to keep up.

Anyways, thanks for the explanations and I look forward to see how this is improved in the future.

**Comment by stack72** [comment]
Thanks for that feedback @nesl247 

It's definitely something we will make sure to keep in-mind. The package naming changes are done - we have made all the codegen changes there to fixup bugs

I like your idea about branching from the last 3.x release for GCP - I will make sure we do that in the future

My apologies again here - I actually tried to make sure we didn't break any code unnecessarily but didn't get it quite right

Thanks for letting us know - this is important to get right for our users

Paul
