### ISSUE TITLE
[AWS] 2.12.x introduced breaking changes for aws.route53.Record / aws.acm.Certificate

### ISSUE THREAD

**Issue by njbmartin** [pulumi/pulumi#5634]
Using the latest version of Pulumi (2.12.1), generating a certificate and creating a certificate validation domain for it results in an error.

```
error: aws:route53/record:Record resource 'xxx.xxx-validation' has a problem: Required attribute is not set
```

Version 2.12.x is a minor bump, so this shouldn't break on upgrading from 2.10.x or 2.11.x

## Expected Behavior

Working on versions below 2.12.0 (tested in 2.10.x and 2.11.x)

## Current Behavior

A _Required_ attribute is not set, but it doesn't say which one... creating a DNS record with hard coded values works, so it must be something to do with the Promise resolution.

## Steps to Reproduce

1. Clone https://github.com/pulumi/examples/tree/master/aws-ts-static-website
2. Make sure you are using the latest Pulumi CLI 2.12.2
3. Configure a new stack with an existing DNS zone, a subdomain that doesn't exist, and no existing certificate.
4. Pulumi up and watch it error
5. downgrade Pulumi to 2.11.2 or lower
6. Try pulumi up again (works)

## Context (Environment)

I'm actually trying to configure a REST API with AWS Lambda, and routing up a custom domain. Using that example to understand how to configure certificates and the domain.

**Comment by viveklak** [comment]
Tracking this in #5633. Closing dupe.
