### ISSUE TITLE
KeyNotFoundException thrown from Pulumi.Deployment.Runner

### ISSUE THREAD

**Issue by KjWhal** [pulumi/pulumi#5638]
I'm on Pulumi.Azure 3.22, my stack is nothing fancy, a sql server db and app service

System.Collections.Generic.KeyNotFoundException: The given key 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[System.Threading.Tasks.VoidTaskResult,Pulumi.Deployment+<CompleteResourceAsync>d__61]' was not present in the dictionary.
       at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
       at Pulumi.Deployment.Runner.<>c__DisplayClass7_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Pulumi.Deployment.Runner.WhileRunningAsync()

**Comment by viveklak** [comment]
Could you provide a bit more information please? Code sample, versions of Pulumi components, logs and steps to reproduce would be helpful.
