### ISSUE TITLE
Bug in merge method for `ResourceOptions`

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5639]
Given a `ComponentResource` that creates an `AWS` resource and a `Kubernetes` resource.

Given also that the `ComponentResource` is passed a `ResourceOptions` with a keyed `providers` property set for e.g. just `Kubernetes`.

If that `ResourceOptions` object is merged with another `ResourceOptions` object using the `merge` function the `keyed` providers property is collapsed into an unkeyed `provider` (singular) property.

Because this new `provider` property is no longer keyed to just `Kubernetes` the provider would also be used for the AWS resource.

This will result in a fatal error, since the AWS resource does not understand a `Kubernetes` provider.

This directly seems to be done on purpose as can be seen here:

https://github.com/pulumi/pulumi/blob/3d2e31289aba2065853d06024a3da9adfc013202/sdk/python/lib/pulumi/resource.py#L522

**Comment by iwahbe** [comment]
The merge essentially creates this program:
```python
import pulumi
from pulumi_aws import s3
from pulumi_kubernetes import Provider

# Create an AWS resource (S3 Bucket)
bucket = s3.Bucket('my-bucket', opts=pulumi.ResourceOptions(
    provider=Provider("test")
))
```
I'm not sure there is a way around this without changing already existing behavior. I'm concerned that a user might have `ResourceOptions(providers={"Kubernetes": Provider("name")}).merge(None)` and then access the `provider` field. I'm going to look into filtering which provider keys we send so the above program becomes valid (and the provider is ignored).
