### ISSUE TITLE
Improve error message if pulumi update tries to delete already-deleted resource

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#564]
Coworker accidentally deleted my resource as part of cleanup. I tested `pulumi update`, and the error message was descriptive but verbose:

```
error PU2003: Plan apply failed: rpc error: code = Unknown desc = Error applying urn:pulumi:testing::url-shortener::aws:lambda/function:Function::urlshortener2b682017 update: Error modifying Lambda Function Code urlshortener2b682017-0e16ef4cee9fe011: ResourceNotFoundException: Function not found: arn:aws:lambda:us-east-1:153052954103:function:urlshortener2b682017-0e16ef4cee9fe011
	status code: 404, request id: dabbdf34-c988-11e7-bee7-cb12bdabb0f9
Step #13 failed [modify]: this failure was catastrophic and the provider cannot guarantee recovery
info: no changes required:
      12 resources unchanged
A catastrophic error occurred; resources states may be unknown
error: rpc error: code = Unknown desc = Error applying urn:pulumi:testing::url-shortener::aws:lambda/function:Function::urlshortener2b682017 update: Error modifying Lambda Function Code urlshortener2b682017-0e16ef4cee9fe011: ResourceNotFoundException: Function not found: arn:aws:lambda:us-east-1:153052954103:function:urlshortener2b682017-0e16ef4cee9fe011
	status code: 404, request id: dabbdf34-c988-11e7-bee7-cb12bdabb0f9
```

Suggestions: 
- Make it clear what resource 404'd. For example:
```Resource not found: arn:aws:lambda:us-east-1:153052954103:function:urlshortener2b682017-0e16ef4cee9fe011. This can happen if <explanatory text>. For more information, see https://docs.pulumi.com/help-page```

- Remove unnecessary information, such as request ID (unless it's valuable). 
- Clean up error: `rpc error: code = Unknown desc = Error applying urn:pulumi:testing::url-shortener::aws:lambda/function:Function::urlshortener2b682017`. Certainly it's useful to know the stack, but the function name was something that was generated. Can we map it to a line number in the code?

**Comment by pgavlin** [comment]
> Clean up error: rpc error: code = Unknown desc = Error applying urn:pulumi:testing::url-shortener::aws:lambda/function:Function::urlshortener2b682017. Certainly it's useful to know the stack, but the function name was something that was generated. Can we map it to a line number in the code?

This is really the only immediately actionable issue, as the error message itself is produced by AWS.

**Comment by lukehoban** [comment]
We now show this:

```
Diagnostics:
  aws:s3:Bucket (my-bucket):
    error: 1 error occurred:
    	* updating urn:pulumi:dev::564::aws:s3/bucket:Bucket::my-bucket: "my-bucket-f82a885": error getting S3 bucket tags: NoSuchBucket: The specified bucket does not exist
    	status code: 404, request id: 6265C8D3ABB3FA6A, host id: gbJb6j1jMZpb+d5Yp7vhQ0/VPktklS3SoBMT3hpbsbTR8cop56lCD6Rw7GWXH6foonl62n1blhQ=
```

This is the AWS error message - and we can't/won't try to rewrite that. 

> Can we map it to a line number in the code?

We do provide reasonable back-pointer to the resource in question in the current diagnostic, but a line number might be helpful. I'll open a specific issue to track that and close this one.
