### ISSUE TITLE
Pulumi use incorrect plugin version

### ISSUE THREAD

**Issue by to4kin** [pulumi/pulumi#5641]
Hello, I'm using Pulumi version 2.12.0 with Golang.
Also, I have the following plugins installed:

![image](https://user-images.githubusercontent.com/4819027/97456933-56d4e800-194a-11eb-8954-d6591a981bc4.png)

Today I've tried to install some applications to the eks cluster from yaml file:

`metricsServer, err := yaml.NewConfigFile(
			ctx,
			"Metrics Server",
			&yaml.ConfigFileArgs{
				File: "configs/metrics-server-v0.3.7.yaml",
			},
			pulumi.DependsOn([]pulumi.Resource{workerNodeGroup}),
		)`

Imports:
`import (
	"github.com/pulumi/pulumi-kubernetes/sdk/v2/go/kubernetes/yaml"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)`

go.mod
`require (
	github.com/pulumi/pulumi-aws/sdk/v3 v3.8.0
	github.com/pulumi/pulumi-kubernetes/sdk/v2 v2.6.3
	github.com/pulumi/pulumi/sdk/v2 v2.12.0=
)`

## Expected Behavior

I expected that a new application will be installed

## Current Behavior

![image](https://user-images.githubusercontent.com/4819027/97457522-e4183c80-194a-11eb-8d37-81a181fa7da5.png)

## Context (Environment)
Why Pulumi use the version 2.6.1? Why not the 2.6.3 from the plugins? How I can set the correct version?

**Comment by viveklak** [comment]
Did you have 2.6.1 installed before and then removed it? Running the `pulumi plugin install resource kubernetes v2.6.1` command should get past this issue.

**Comment by to4kin** [comment]
Yes, this will fix the issue. But why pulumi trying to use version 2.6.1? Is it store information about versions in the stack? How to update version in the stack?

**Comment by KatoStoelen** [comment]
The same thing happens with dotnet and Azure.

Pulumi CLI v2.14.0
Runtime `dotnet` (binary entry point)
Pulumi.Azure v3.31.1

```console
>pulumi preview --diff
Previewing update ([stack-name]):
[resource plugin azure-3.30.1] installing

...

error: no resource plugin 'azure-v3.31.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource azure v3.31.1`
```

The output above is from the Azure Pipeline task. Locally it does not install any plugins (same error, though).

As you can see, the CLI installs `azure-3.30.1` and complains that `azure-v3.31.1` is not installed.

Would be nice if you don't have to run `pulumi plugin install ...` as there would then be multiple places to specify the version and more room for errors.

**Comment by grosren** [comment]
### Context (Environment)

	github.com/pulumi/pulumi-azure/sdk/v3 v3.41.0
	github.com/pulumi/pulumi-azuredevops v1.0.0
	github.com/pulumi/pulumi-kubernetes/sdk/v2 v2.7.5
	github.com/pulumi/pulumi/sdk/v2 v2.16.2

### Current Behavior 
I am facing the same issues since several versions of Pulumi and Plugins on all my projects and stacks. 

#### Case 1
In my stack file I have the following resource
`
            {
                "urn": "urn:pulumi:xxx::xxx::pulumi:providers:kubernetes::default_2_6_1",
                "custom": true,
                "id": "283a0a0c-296c-4650-a736-03230cbeae24",
                "type": "pulumi:providers:kubernetes",
                "inputs": {
                    "version": "2.6.1"
                },
                "outputs": {
                    "version": "2.6.1"
                }
            }
`

The provider is not used, but somehow it triggers to download the old plugin version:

	Previewing update (xxx/xxx)
	View Live: ....

	[resource plugin kubernetes-2.6.1] installing

#### Case 2
If I delete that provider (not used anywhere) I get following error:

	Previewing update (xxx/xxx)
	View Live: ...

	[resource plugin azure-3.32.0] installing 
	....
  
	pulumi:pulumi:Stack: (same) [urn=urn:xxx]
	pulumi:pulumi:StackReference: (read)
	 [id=xxx]
	 [urn=urn:pulumi:xxx]
	name: "xxx"
	error: no resource plugin 'kubernetes-v2.6.1' found in the workspace or on your $PATH, install the plugin using `pulumi 	plugin install resource kubernetes v2.6.1`
	Resources:
    	3 unchanged

Its unclear to me, why specific versions are need to deploy or preview a stack --> **No documentation available**

**Comment by viveklak** [comment]
Closing in favor of https://github.com/pulumi/pulumi/issues/5641

**Comment by Rus1an31** [comment]
> The same thing happens with dotnet and Azure.
> 
> Pulumi CLI v2.14.0 Runtime `dotnet` (binary entry point) Pulumi.Azure v3.31.1
> 
> ```
> >pulumi preview --diff
> Previewing update ([stack-name]):
> [resource plugin azure-3.30.1] installing
> 
> ...
> 
> error: no resource plugin 'azure-v3.31.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource azure v3.31.1`
> ```
> 
> The output above is from the Azure Pipeline task. Locally it does not install any plugins (same error, though).
> 
> As you can see, the CLI installs `azure-3.30.1` and complains that `azure-v3.31.1` is not installed.
> 
> Would be nice if you don't have to run `pulumi plugin install ...` as there would then be multiple places to specify the version and more room for error.
> 
> --edit--
> 
> Even though I run `pulumi plugin install resource azure v3.31.1` before `pulumi preview`, `pulumi preview` still installs azure-3.**30**.1. However, since v3.**31**.1 also exists, no error occurs.

I have the same issue. Can you tell please how did you solve it?

**Comment by LucasBrazi06** [comment]
Same problem here, new fix has been provided in plugin 'kubernetes' V3.21.1 but it still uses the V3.20.2 when doing 'pulumi up'!!!
pulumi/pulumi-kubernetes#2249

**Comment by jamest-pin** [comment]
Similar thing happening to me. I have not specified a plugin version anywhere, but it for some reason is stuck to using the old version which is out of date. If no explicit version is specified, pulumi ought to use the latest available...
```
% pulumi plugin ls
NAME            KIND      VERSION  SIZE    INSTALLED      LAST USED
aws             resource  6.0.2    513 MB  1 month ago    1 month ago
aws             resource  5.16.2   419 MB  7 minutes ago  7 minutes ago
aws-apigateway  resource  1.0.1    92 MB   3 weeks ago    3 weeks ago
str             resource  1.0.0    24 MB   1 week ago     1 week ago
time            resource  0.0.16   38 MB   4 days ago     4 days ago
```

**Comment by Frassle** [comment]
> If no explicit version is specified, pulumi ought to use the latest available...

If it's downloading a specific old version its because an explicit version _is_ present. You'll probably find you had a code change that triggered a resource delete, the current behavior of the engine is to use the version of the provider that created the resource to delete the resource.

**Comment by jamest-pin** [comment]
Thanks @Frassle I was using aws crosswalk, so perhaps it was using some underlying resource and somehow specified an old version? Anyway, turns out deleting my whole stack and all the plugins then bringing it up again, then it used the newer version.

**Comment by Frassle** [comment]
> I was using aws crosswalk, so perhaps it was using some underlying resource and somehow specified an old version?

Yeh that sounds likely, crosswalk will have it's own version of aws that it uses.
