### ISSUE TITLE
depends_on only works with a Resource/CustomResource and not Output[CustomResource]

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi#5642]
## Expected Behavior
Trying to use the get_resource method of a Helm3 Chart to extract a created resource for a depends_on. 

## Current Behavior
When I use that extracted Output[CustomResource] it receive the error `Exception: 'depends_on' was passed a value that was not a Resource.` Most likely the check on depends_on needs to be fixed/extended to work with Output[Resource/CustoResource] types. 

## Steps to Reproduce
```
cert_manager_deployment = cert_manager_chart.get_resource(group_version_kind="apps/v1/Deployment",
                                                          name="cert-manager",
                                                          namespace="cert-manager")
```
Use that as a depends_on resource.

https://github.com/pulumi/pulumi/blame/5cef84f0366f264baf51c322d1d22b6124fdf236/sdk/python/lib/pulumi/resource.py#L450-L454

**Comment by justinvp** [comment]
Yep.

https://github.com/pulumi/pulumi/blob/5cef84f0366f264baf51c322d1d22b6124fdf236/sdk/python/lib/pulumi/resource.py#L303

Needs to change from `List['Resource']` => `Input[List[Input['Resource']]]` along with the underlying implementation.

**Comment by justinvp** [comment]
Addressing this involves implementing a similar change as https://github.com/pulumi/pulumi/pull/2198 for Python.

**Comment by lblackstone** [comment]
The same issue is present in the Go SDK.

**Comment by mitchellmaler** [comment]
@lblackstone What can be done to start the conversation on making this change. Since the Kubernetes helm ready depends on this change for the other SDKs and is a highly requested item.

**Comment by lblackstone** [comment]
> @lblackstone What can be done to start the conversation on making this change. Since the Kubernetes helm ready depends on this change for the other SDKs and is a highly requested item.

Sorry for the delay on this. The team is hard at work on some other priorities at the moment, but this is next in the queue for me. I'm hoping to start driving this again later this month. This feature turned out to need some additional work in the core Pulumi SDKs, so it's a bit more involved than we thought initially.

**Comment by eljoth** [comment]
@lblackstone any updates on this ?

**Comment by lblackstone** [comment]
> @lblackstone any updates on this ? Would like to have a look at the go implementation for [pulumi/pulumi-kubernetes#861](https://github.com/pulumi/pulumi-kubernetes/issues/861).

No, we haven't had a chance to make the core Pulumi changes yet, but it's on the backlog. I believe the change will apply to all supported languages, so there isn't really anything to be done for Go specifically at this time.

**Comment by benesch** [comment]
In case anyone else is impatient, here's how I hacked around this in the Python SDK. This is to solve a slightly different issue—making a EKS node group dependent on an EKS cluster—but I imagine the approach generalizes:

```python
# Workaround for https://github.com/pulumi/pulumi/issues/5642.
class ClusterDependency:
    def __init__(self, cluster):
        self.cluster = cluster

    @property
    def urn(self):
        return self.cluster.eks_cluster.apply(lambda r: r.urn)

    @property
    def __class__(self):
        # Bypass https://github.com/pulumi/pulumi/blob/b7d403204/sdk/python/lib/pulumi/resource.py#L460-L462.
        return pulumi.Resource

cluster = eks.Cluster(
    "eks-cluster",
    # ...
)

aws.eks.NodeGroup(
    "eks-node-group"
    # ...
    opts=ResourceOptions(
        parent=cluster, depends_on=[ClusterDependency(cluster)],
    ),
)
```

**Comment by t0yv0** [comment]
Bots closing prematurely, only the Python fix is in, Go is pending.
