### ISSUE TITLE
Add boolean values to Go SDK

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#5647]
Currently, if you want to define a boolean value, you need to do:

```go
pulumi.BoolPtr(true)
pulumi.BoolPtr(false)
```

It seems like a pretty easy quality of life addition to add boolean types, like 
```
pulumi.True
pulumi.False
```

**Comment by stack72** [comment]
@jaxxstorm so pulumi.True / False should relate to pulumi.BoolPtr and not pulumi.Bool?
