### ISSUE TITLE
stack select and secrets-provider

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi#5650]
Hi,
I would like to setup an Azure DevOps Pipeline to pulumi preview/update using Azure KeyVault for the key.

If I do, from scratch:
```
pulumi login azblob://stae
pulumi stack select --create dev --secrets-provider "azurekeyvault://keyvault.vault.azure.net/keys/pulumi"
pulumi up --yes
```
It works as expected the first time, if I rerun it again it complains because no password is given.

I think that the problem is related to "--secrets-provider" option. Seems that this option is skipped if "--create" does not take effect.

As workaround for now I am doing:
```
pulumi login azblob://stae
pulumi stack select --create dev --secrets-provider "azurekeyvault://${KEYVAULT}.vault.azure.net/keys/${PULUMI_KEY}"
pulumi stack change-secrets-provider "azurekeyvault://${KEYVAULT}.vault.azure.net/keys/${PULUMI_KEY}"
pulumi up --yes
```
in order to force pulumi to always use Azure KeyVault.

Am I using it wrong?

Thanks

**Comment by yellowhat** [comment]
Are there any update on this?

Thanks

**Comment by stack72** [comment]
Hi @yellowhat 

My apologies for taking so long in responding here. Can you tell me if Pulumi.<stackname>.yaml is part of your source control?

That file will have information in it that allows Pulumi to be able to reconstruct the secrets provider

Paul

**Comment by yellowhat** [comment]
@stack72, Sorry for the late reply.
The `Pulumi.yaml` that I use is:
```
name: dev
runtime: python
description: description
```

Is there something missing?

Thanks

**Comment by stack72** [comment]
Hey @yellowhat 

Do you have another yaml file? Something like Pulumi.dev.yaml?

If so have you git ignored this type of file or is CI the first place you are creating the stack?

Paul

**Comment by stack72** [comment]
Hey @yellowhat yeah that's got it for me - this is what I suspected

Basically the details of the secrets provider is saved to Pulumi.<stackname>.yaml

Therefore as this file isn't in source control, Pulumi can't find the details to use the secrets provider

When you use change-secrets-provider, it's rewriting the yaml file and thus why it works then

We need to investigate the usecase of using a secrets provider without storing the stack yaml file

Paul

**Comment by yellowhat** [comment]
Ok thanks.

**Comment by yellowhat** [comment]
Hi, are there any update on this?

**Comment by mikhailshilkov** [comment]
This issue has been stale for a year so I'll take the liberty to close it as by-design, as explained by Paul. Feel free to open a new issue with a feature request to improve secrets provider configuration and outline your ideas. Thank you!
