### ISSUE TITLE
Give users the ability to throw errors for "Calling [toString] on an [Output<T>] is not supported"

### ISSUE THREAD

**Issue by hcharley** [pulumi/pulumi#5665]
https://pulumi-community.slack.com/archives/CJ909TL6P/p1604120367076300

**Comment by clstokes** [comment]
Sharing a screenshot of the conversation from Community Slack for when this rolls past the 10,000 message limit.

![image](https://user-images.githubusercontent.com/293763/97915183-e6d9af80-1d05-11eb-9c18-3fc41cc5728c.png)

**Comment by mikhailshilkov** [comment]
Dupe of #4261
