### ISSUE TITLE
Go panic using Automation API in nodejs

### ISSUE THREAD

**Issue by barclayadam** [pulumi/pulumi#5679]
I am encountering a Go panic when executing an inline program using Automation API:

````
Pulumi Version:   v2.12.1
Go Version:       go1.15.3
Go Compiler:      gc
Architecture:     amd64
Operating System: windows
Panic:            fatal: [400] Message authentication failed

goroutine 1 [running]:
runtime/debug.Stack(0xc000535650, 0x225bf20, 0xc000bfe8e0)
        C:/hostedtoolcache/windows/go/1.15.3/x64/src/runtime/debug/stack.go:24 +0xa5
main.panicHandler()
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x75
panic(0x225bf20, 0xc000bfe8e0)
        C:/hostedtoolcache/windows/go/1.15.3/x64/src/runtime/panic.go:969 +0x1c7
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.AssertNoError(0x28d3c00, 0xc000976d00)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/sdk/go/common/util/contract/assert.go:40 +0xe8
main.displayUpdatesJSON(0xc000996840, 0x5, 0x8, 0x28d3b60, 0xc000bf9350, 0x0, 0x5)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/stack_history.go:112 +0x174
main.newHistoryCmd.func1(0xc00095e580, 0xc000944cf0, 0x0, 0x3, 0xe, 0xe)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/history.go:65 +0x248
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunFunc.func1(0xc00095e580, 0xc000944cf0, 0x0, 0x3, 0x0, 0x0)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:96 +0x58
github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1(0xc00095e580, 0xc000944cf0, 0x0, 0x3)
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x72
github.com/spf13/cobra.(*Command).execute(0xc00095e580, 0xc000944cc0, 0x3, 0x3, 0xc00095e580, 0xc000944cc0)
        D:/a/pulumi/pulumi/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc00042adc0, 0x15, 0x0, 0x0)
        D:/a/pulumi/pulumi/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        D:/a/pulumi/pulumi/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x54
````

## Steps to Reproduce
I'm not entirely sure what is causing this, trying to track down the case here. I have a relatively large script that is failing late on, even after doing what appears to be the same action dozens of times before. I thought it was an issue with the same project with multiple stack names & programs, but if I run the application with just the single stack that fails it fails on its own.

I've changed the inline program definition to do basically nothing, in particular, it does not touch any resources. The problem still happens.

I've removed a call to `setAllConfig`, same problem.

If I change nothing but the name of the stack or project, it works.

I deleted the stack from backend (Pulumi app) and that allowed it to work on the next attempt

I'm at a loss for what triggered this TBH but wanted to document the error.

**Comment by barclayadam** [comment]
I have done further work and now another stack has this same problem. I do not know what causes this, but I'm not in a state where another stack is broken but I do not want to remove the state from Pulumi backend because resources have been deployed. This is completely blocking

**Comment by stack72** [comment]
Hi @barclayadam 

Sorry you are hitting this - please can you tell me what backend you are using for Pulumi - is it an S3 bucket or something or just the Pulumi SaaS?

Paul

**Comment by barclayadam** [comment]
@stack72, Sorry, thought I had put that. I'm using the Pulumi SaaS backend

**Comment by barclayadam** [comment]
Another point of interest... This actually seems to happen _after_ the update has succeeded/finished as shown in the Pulumi web app

**Comment by stack72** [comment]
So the issue here seems to be around getting the history of the stack but I can't see how that is causing a panic...

**Comment by barclayadam** [comment]
As mentioned in the original issue this would happen on a basically empty stack too, so my assumption is this would be happening in the "clean up" part of the execution, whether that is getting history or not (as I know the actual program starting with a simple console log line).

I understand the Automation API is new/beta but there definitely feels to be some pretty rough edges, unfortunately. Probably unrelated but I've had a stack or 2 get "stuck" doing nothing. Some resources are created, but then nothing. I can restart the stack and it creates a few more, but it does not do the whole thing.

**Comment by stack72** [comment]
Hi @barclayadam 

I have 1 more question - by any chance are you on a windows laptop and using a VPN?

P.

**Comment by EvanBoyle** [comment]
Looks like another instance of https://github.com/pulumi/pulumi/issues/5470

Can you share any additional details about your setup? Are you using a non-default secrets provider?

**Comment by barclayadam** [comment]
Hi @stack72. I'm on a windows PC but no VPN and a pretty rock-solid internet connection. 

@EvanBoyle I'm not using a non-default secrets provider, but I _am_ managing the config myself. I load the config from a single project / stack (the config project) and then distribute the ConfigMap to each application stack.

It is not consistent how to get into this state though. I have only a single stack that got "stuck" like this at the moment, although this is the 2nd one from the ones I have been executing

**Comment by EvanBoyle** [comment]
Do you have the config for the stack that got stuck?

**Comment by barclayadam** [comment]
I do, but when experimenting it appeared that if I replaced the call to `setAllConfig` with an empty object it made no difference

**Comment by EvanBoyle** [comment]
Are you using secrets or refreshing config as a part of this? Does your stack have secret outputs?

**Comment by barclayadam** [comment]
The exact same config is used across all stacks (I've removed the sensitive parts)

````yaml
config:
  cloudflare:accountId: -
  cloudflare:apiToken:
    secure: -
  cloudflare:apiUserServiceKey:
    secure: -
  cloudflare:email: cloudflare.uat.automation@-.com
  postmark:accountToken:
    secure: -
  common-config:acrSku: Standard
  common-config:activeDirectoryAdminPassword:
    secure: -
  common-config:activeDirectoryAdminUsername: dba@-.com
  common-config:aksNodePoolOsDiskType: Managed
  common-config:appConfigSku: standard
  common-config:askNodePoolVmSize: Standard_B2Ms
  common-config:checkRegions: WEU
  common-config:cloudflareEmailZoneId: -
  common-config:cloudflareEndpointsZoneId: -
  common-config:cloudflareSolverApiToken:
    secure: -
  common-config:cloudflareSolverEmail: cloudflare.uat.automation@-.com
  common-config:cloudflareSslMode: strict
  common-config:elasticApmCloudId: -
  common-config:elasticApmSecretToken:
    secure: -
  common-config:elasticApmUrl: https://...
  common-config:elasticCloudAuth:
    secure: -
  common-config:filebeatDeleteAge: 3d
  common-config:k8sVersion: 1.17.13
  common-config:letsEncryptDirectory: https://acme-v02.api.letsencrypt.org/directory
  common-config:letsencryptEmail: info@-.com
  common-config:metricbeatDeleteAge: 2d
  common-config:monitorIntervalInSeconds: "60"
  common-config:nodeCount: "2"
  common-config:postgresGeoRedundantBackEnabled: "false"
  common-config:postgresSku: B_Gen5_1
  common-config:postgresStorageMb: "5120"
````

**Comment by barclayadam** [comment]
By "refreshing config" do you mean using the `stack.refreshConfig` call? If so, no. I select the config stack ` LocalWorkspace.createOrSelectStack(...)`, call `stack.setAllConfig(...)` and then `stack.up`. The config object passed to `stack.setAllConfig` is one loaded from a different stack through `stack.getAllConfig`

**Comment by barclayadam** [comment]
Many of my stacks have secret outputs, that does not determine whether this panic happens though

**Comment by EvanBoyle** [comment]
The `history` command that is executing at the end of `stack.Up()` retrieves all previous update results and all config values associated with each of those updates. It would seem that one of those config values is failing to decrypt. So the failure here is independent of the current config you use for the update. It has to do with some bad config in the history that the command can't handle. 

Now to figure out what that config is, and why we can't handle it. Would you mind sharing the code that reads and sets config?

**Comment by barclayadam** [comment]
Ok, I think I may know what could be going on:

 - Load the common configuration from a separate stack (this uses a "traditional" Pulumi application using Automation API)
 - Modify the prefix of the config keys and push to a new stack. This stack uses workdir: ".". `stack.up`
 - Create a new project with different name but SAME stack name (i.e. both are "uat") and do the same. If you do NOT delete the Pulumi.yaml and Pulumi.[stack].yaml the config keys are merged. This second one gets itself in to a bad state

Note that I have NOT tried the above in a simple test case, just speculation on what I've noticed when trying to debug.

What do I mean by merged configs? If the "common" config has:

```yaml
config:
   common-config:myConfigValue: 1
````

and you create 2x stacks with same name in different projects you end up with:

````yaml
config:
    project-1:myConfigValue: 1
    project-2:myConfigValue: 1
````

If those are actually secrets you will have one that has a different encryption key and therefore could not be decoded.

I automate the deletion of these files before running any stacks now as I noticed this duplication of config keys, but did not immediately link it back to the panic. I just did not like the untidiness :)

For completeness config loading and stack executions looks something like:

````typescript

const stack = LocalWorkspace.selectStack({
    stackName: config.environment,
    workDir: path.join('.', 'config'),
});

const commonConfig = stack.getAllConfig();

async runProject(project: string) {
	const stack = await LocalWorkspace.createOrSelectStack({
        projectName: project,
        stackName: 'same-stack-name',
        program: () => {
            return {};
        },
    }, {
        workDir: process.cwd(),
    });

    await stack.setAllConfig(Object.entries(commonConfig).reduce((curr, [key, value]) => {
            curr[key.replace('common-config', project)] = value;

            return curr;
        }, {} as ConfigMap));

    await stack.up();    
}

await runProject('project1');
await runProject('project2');
````

**Comment by barclayadam** [comment]
Out of curiosity, why is the history being loaded and the associated config values in the up command? 

In general, I'm finding that Pulumi is pretty slow because of the excessive chattiness to the SaaS backend, and have definitely noticed that the backend shows an operation has completed but the local program is still waiting on `stack.up` to finish (I raised another bug @ #5453 regarding it)

**Comment by EvanBoyle** [comment]
Ah, good find! Yes having a config value that had been encrypted by another stack in a pre-existing pulumi.stack.yaml would definitely cause this class of error. 

The history command is called to fetch a JSON summary of the update operation. Unfortunately the history command loads all previous updates (and config), while we only really need the last one. This will be optimized in the future. When we add better structured output for `up()`, we will likely be able to remove this call.

**Comment by EvanBoyle** [comment]
We've updated the history command so that it marks unencryptable values rather than failing: https://github.com/pulumi/pulumi/pull/5701

This is available in the most recent CLI release. Going to close this issue out for now, but feel free to reopen if you hit more problems!
