### ISSUE TITLE
Add support for adding tags to stacks through automation api

### ISSUE THREAD

**Issue by danfhernandez** [pulumi/pulumi#5681]
When using automation api to bring up stacks it would be useful to tag them as so for tracking and debugging purposes.

**Comment by jbaileyashe** [comment]
I am transition bash code to using the automation api, and this feature would be really nice to have. Until its available, I have to use both the Automation API and bash code together 😢

**Comment by alexeyzimarev** [comment]
I think it would be also quite useful to be able to set tags from within the stack code itself.

**Comment by komalali** [comment]
In lieu of an automation api solution, it is currently possible to set stack tags using the [REST API](https://www.pulumi.com/docs/reference/service-rest-api/#set-stack-tag).

**Comment by eliaskickbush** [comment]
At my current job we're making great progress in our automations using this API, and this feature would be really useful to standardize certain tags for infrastructure. Would there be any interest from the community in further development for this feature/ is this still open? I could make a case to develop this further.

**Comment by Eric-Swiftly** [comment]
> In lieu of an automation api solution, it is currently possible to set stack tags using the [REST API](https://www.pulumi.com/docs/reference/service-rest-api/#set-stack-tag). No more using bash to set tags!

You can then wrap that REST API in a Dynamic Provider and end up with something [like this ](https://github.com/Eric-Swiftly/PulumiCodeSamples/blob/main/pulumi_api_provider.py)

**Comment by RobbieMcKinstry** [comment]
This sounds like a good first issue for automation API. I'm not scheduled to work on this soon, but if my schedule opens up, I'd be interested.

**Comment by RobbieMcKinstry** [comment]
@mrod-io has offered to submit a PR to address this issue. ❤️

**Comment by RobbieMcKinstry** [comment]
[This issue](https://github.com/pulumi/pulumi/issues/11936) tracks the remaining work of supporting Go, Python, and Dotnet with the same feature.

**Comment by matanbaruch** [comment]
For anyone looking at this merge.

You have the following methods on Stack: getTag, listTags, removeTag and setTag
https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/automation/#Stack
