### ISSUE TITLE
Plugin installation can fail silently during `pulumi new` on Windows

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi#5685]
When running `pulumi new azure-csharp`, the azure plugin seems to download fine, but it actually didn't.

## Expected Behavior
When pulumi cannot install a plugin, an error (or warning) message is displayed.

## Current Behavior
It says "Your new project is ready to go!"

## Steps to Reproduce
1. Run `pulumi new azure-csharp` (I'm using Powershell Core on Windows)

## Context (Environment)
I thought the plugin had installed because it was successful.

## Console output:

> C:\repos\ArmVSPulumi\function-app-consumption\PulumiPortLocal3 [master +7 ~1 -1 !]> pulumi new
> Please choose a template: azure-csharp                A minimal Azure C# Pulumi program
> This command will walk you through creating a new Pulumi project.
> 
> Enter a value or leave blank to accept the (default), and press <ENTER>.
> Press ^C at any time to quit.
> 
> project name: (PulumiPortLocal3)
> project description: (A minimal Azure C# Pulumi program)
> Created project 'PulumiPortLocal3'
> 
> stack name: (dev)
> Created stack 'dev'
> Enter your passphrase to protect config/secrets:
> Re-enter your passphrase to confirm:
> 
> Enter your passphrase to unlock config/secrets
>     (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
> azure:location: The Azure location to use: (WestUS)
> Saved config
> 
> Installing dependencies...
> 
> running 'dotnet build -nologo .'
>   Determining projects to restore...
> 
>   Restored C:\repos\ArmVSPulumi\function-app-consumption\PulumiPortLocal3\PulumiPortLocal3.csproj (in 5.38 sec).
> 
>   You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
> 
>   PulumiPortLocal3 -> C:\repos\ArmVSPulumi\function-app-consumption\PulumiPortLocal3\bin\Debug\netcoreapp3.1\PulumiPortLocal3.dll
> 
> 
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:11.04
> 
> 'dotnet build -nologo .' completed successfully
> [resource plugin azure-3.29.0] installing
> Downloading plugin: 56.96 MiB / 56.96 MiB [========================] 100.00% 11s
> Moving plugin...Finished installing dependencies
> 
> Your new project is ready to go!
> 
> To perform an initial deployment, run 'pulumi up'
> 
> warning: A new version of Pulumi is available. To upgrade from version '2.12.0' to '2.12.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
> C:\repos\ArmVSPulumi\function-app-consumption\PulumiPortLocal3 [master +8 ~1 -1 !]> ls C:\Users\50587\.pulumi\plugins\
> 
> 
>     Directory: C:\Users\50587\.pulumi\plugins
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> d----           10/7/2020 11:26 AM                resource-azure-nextgen-v0.2.1
> d----           10/7/2020 11:26 AM                resource-azure-nextgen-v0.2.1.tmp901394687 - Copy
> d----            8/3/2020 11:24 AM                resource-azure-v3.14.0
> d----           8/11/2020 11:31 AM                resource-azure-v3.15.0
> d----           10/8/2020 10:57 AM                resource-azure-v3.22.0
> d----           10/8/2020 10:58 AM                resource-azure-v3.22.0.tmp214190647 - Copy
> d----           9/28/2020  4:40 PM                resource-azure-v3.23.0
>

**Comment by stack72** [comment]
Hi @MisinformedDNA 

If you can, can you run the same pulumi plugin install command in your terminal with verbosity:

e.g. 

`pulumi plugin install resource azure-nextgen v0.2.1 -v=9 --logtostderr`

and see what it tells you

**Comment by MisinformedDNA** [comment]
> C:\PulumiPortLocal3> pulumi plugin install resource azure v3.29 -v=9 --logtostderr
> I1104 14:07:01.435559   19964 sink.go:146] defaultSink::Infoerr([resource plugin azure-3.29.0] installing)
> [resource plugin azure-3.29.0] installing
> I1104 14:07:01.451127   19964 plugins.go:591] SelectCompatiblePlugin(..., azure): beginning
> I1104 14:07:01.451127   19964 plugins.go:624] SelectCompatiblePlugin(..., azure): skipping plugin azure-3.14.0: semver mismatch
> I1104 14:07:01.451127   19964 plugins.go:624] SelectCompatiblePlugin(..., azure): skipping plugin azure-3.15.0: semver mismatch
> I1104 14:07:01.452086   19964 plugins.go:624] SelectCompatiblePlugin(..., azure): skipping plugin azure-3.22.0: semver mismatch
> I1104 14:07:01.452086   19964 plugins.go:624] SelectCompatiblePlugin(..., azure): skipping plugin azure-3.23.0: semver mismatch
> I1104 14:07:01.452086   19964 plugins.go:630] SelectCompatiblePlugin(..., azure): failed to find match
> I1104 14:07:01.452086   19964 plugins.go:201] azure downloading from https://get.pulumi.com/releases/plugins
> I1104 14:07:01.453088   19964 plugins.go:208] full plugin download url: https://get.pulumi.com/releases/plugins/pulumi-resource-azure-v3.29.0-windows-amd64.tar.gz
> I1104 14:07:01.454091   19964 plugins.go:218] plugin install request headers: map[User-Agent:[pulumi-cli/1 (; windows)]]
> I1104 14:07:02.468150   19964 plugins.go:225] plugin install response headers: map[Accept-Ranges:[bytes] Age:[438416] Content-Disposition:[attachment; filename=pulumi-resource-azure-v3.29.0-windows-amd64.tar.gz] Content-Length:[59728053] Content-Type:[application/x-gzip] Date:[Fri, 30 Oct 2020 18:20:07 GMT] Etag:["009e5b651cf4a4a1e3ac375a6d2f49b0-12"] Last-Modified:[Fri, 30 Oct 2020 17:28:00 GMT] Server:[AmazonS3] Via:[1.1 60df84b4b5ee2196fc780b830eafdc5d.cloudfront.net (CloudFront)] X-Amz-Cf-Id:[ZhoopuQ0ecTeqBrDWKjGxNP80_t8R8AsbdF4UnmW0PnMoHUJ-O-90g==] X-Amz-Cf-Pop:[MSP50-C1] X-Cache:[Hit from cloudfront]]
> Downloading plugin: 0 B / 56.96 MiB [----------------------------------]   0.00%I1104 14:07:02.471189   19964 plugin_install.go:135] [resource plugin azure-3.29.0] installing tarball ...
> Downloading plugin: 56.96 MiB / 56.96 MiB [========================] 100.00% 13s
> Moving plugin...I1104 14:07:16.135982   19964 plugins.go:304] moving plugin from "C:\\Users\\50587\\.pulumi\\plugins\\resource-azure-v3.29.0.tmp369584755" to "C:\\Users\\50587\\.pulumi\\plugins\\resource-azure-v3.29.0"
> I1104 14:07:17.393237   19964 sink.go:162] defaultSink::Warning(warning: A new version of Pulumi is available. To upgrade from version '2.12.0' to '2.12.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.)
> warning: A new version of Pulumi is available. To upgrade from version '2.12.0' to '2.12.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
> I1104 14:07:17.397216   19964 sink.go:154] defaultSink::Error(error: installing [resource plugin azure-3.29.0] from : moving plugin: rename C:\Users\50587\.pulumi\plugins\resource-azure-v3.29.0.tmp369584755 C:\Users\50587\.pulumi\plugins\resource-azure-v3.29.0: Access is denied.
> main.newPluginInstallCmd.func1
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/plugin_install.go:137
> github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunFunc.func1
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:96
> github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112
> github.com/spf13/cobra.(*Command).execute
>         D:/a/pulumi/pulumi/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846
> github.com/spf13/cobra.(*Command).ExecuteC
>         D:/a/pulumi/pulumi/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
> github.com/spf13/cobra.(*Command).Execute
>         D:/a/pulumi/pulumi/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
> main.main
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48
> runtime.main
>         C:/hostedtoolcache/windows/go/1.15.2/x64/src/runtime/proc.go:204
> runtime.goexit
>         C:/hostedtoolcache/windows/go/1.15.2/x64/src/runtime/asm_amd64.s:1374
> )
> error: installing [resource plugin azure-3.29.0] from : moving plugin: rename C:\Users\50587\.pulumi\plugins\resource-azure-v3.29.0.tmp369584755 C:\Users\50587\.pulumi\plugins\resource-azure-v3.29.0: Access is denied.
> main.newPluginInstallCmd.func1
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/plugin_install.go:137
> github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunFunc.func1
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:96
> github.com/pulumi/pulumi/sdk/v2/go/common/util/cmdutil.RunResultFunc.func1
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112
> github.com/spf13/cobra.(*Command).execute
>         D:/a/pulumi/pulumi/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846
> github.com/spf13/cobra.(*Command).ExecuteC
>         D:/a/pulumi/pulumi/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
> github.com/spf13/cobra.(*Command).Execute
>         D:/a/pulumi/pulumi/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
> main.main
>         D:/a/pulumi/pulumi/src/github.com/pulumi/pulumi/pkg/cmd/pulumi/main.go:48
> runtime.main
>         C:/hostedtoolcache/windows/go/1.15.2/x64/src/runtime/proc.go:204
> runtime.goexit
>         C:/hostedtoolcache/windows/go/1.15.2/x64/src/runtime/asm_amd64.s:1374
>

Related to https://github.com/pulumi/pulumi/issues/2695

**Comment by stack72** [comment]
Looks like this is still the same as #2695 

We will continue tracking the work in there and I can close this out as a dupe

**Comment by MisinformedDNA** [comment]
It isn't a dupe. #2695 is about fixing the error. This issue is about not failing silently in the context of `pulumi new` regardless of where the error may be coming from.

This issue can be fixed even if #2695 is not.

**Comment by leezen** [comment]
@MisinformedDNA thanks for clarifying. I've re-opened and updated the title to reflect the suggestion.
