### ISSUE TITLE
Installation in Powershell on Linux does not set the path

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi#5691]
When I install Pulumi within Powershell on Linux (specifically, I'm in a GitHub Codespace), the path does not get set. Well, almost. If enter the bash shell, then the pulumi folder is set in the path.

## Expected Behavior
Path gets set for all shells

## Current Behavior
Path is not set for Powershell 

## Steps to Reproduce

1. Create a GitHub Codespace and switch shell to Powershell
2. Run `curl -fsSL https://get.pulumi.com | sh`
3. Run `pwsh` to enter a new shell
4. Run `$env:PATH` (Pulumi is not on the path)

## Workaround
(continuing from repro steps)
5. Run `bash` to enter a new shell
6. Run `echo $PATH` (Pulumi is on the path)
7. Run `pwsh`
8. Run `$env:PATH` (Pulumi is still on the path)

## Context (Environment)
GitHub Codespaces
Powershell

This was frustrating as it's not obvious that switching shells would help. (I thought a path was a path.)

**Comment by lukehoban** [comment]
I think this may be the same issue tracked in https://github.com/pulumi/get.pulumi.com/issues/79.
