### ISSUE TITLE
Confusing and concerning error message about plugin shutdown

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5698]
#### Problem

With verbose logging turned on the last error messages printed indicate that an error occurred, but the `up` is actually successful. This seems benign but is confusing when troubleshooting error messages as it seems indicates an error, but doesn't seem to cause any actual problems.

This happens with pulumi version v2.12.1 across Python and NodeJS (and likely other languages too).

#### Error

Nodejs
```
I1106 08:02:12.478682   69216 ignore.go:44] Explicitly ignoring and discarding error: rpc error: code = Canceled desc = grpc: the client connection is closing
I1106 08:02:12.479112   69216 host.go:417] Error closing 'nodejs' language plugin during shutdown; ignoring: 1 error occurred:
```

Python
```
I1106 08:00:57.184500   66865 ignore.go:44] Explicitly ignoring and discarding error: rpc error: code = Canceled desc = grpc: the client connection is closing
I1106 08:00:57.205778   66865 host.go:417] Error closing 'python' language plugin during shutdown; ignoring: 1 error occurred:
```

#### Steps to reproduce

1. `pulumi new python -y`
1. `pulumi up -y --skip-preview -v5 --logtostderr`
    1. Observe error.

**Comment by tgummerer** [comment]
I can't find the PR fixing this right now, but we made some changes improving the shutdown flow, and there's no longer an error about shutting down the language plugin.
