### ISSUE TITLE
Detect if users accidentally add an AWS secret in plaintext

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#570]
Per comment here: https://github.com/pulumi/pulumi/pull/563#issuecomment-344471076

> Note that it may be interesting eventually to run something like this: https://github.com/awslabs/git-secrets.  The idea would be we could reject attempts to add a secret-like value

    error: the plaintext config value looks like a secret;
           pass --force to add it anyway, or --secret to encrypt

**Comment by joeduffy** [comment]
I'm bumping this one slightly, for a related, but different reason: warning every time someone does a plaintext configuration -- as we do today -- is, in hindsight, probably a bad idea.

`warning: saved config key 'x' value 'y' as plaintext; re-run with --secret to encrypt the value instead. Use --plaintext to avoid this warning`

First, you get desensitized to it.  Second, it looks like you did something wrong when you probably didn't.  Third, it gives the same impressions during demos, many of which entail configuration.  Etc.

I'd rather eliminate this warning altogether in favor of something like the above.
