### ISSUE TITLE
[codegen/dotnet] Special cases for .NET enum values

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#5706]
I gave the .NET enum generation a run on NextGen. Overall, looks great.

However, it exposed two special cases that don't compile as-is:

1. If an enum value is `Equals`, that conflicts with the `Equals()` method.

```cs
public static Operator Equals { get; } = new Operator("Equals");
public static Operator NotEquals { get; } = new Operator("NotEquals");
public static Operator Contains { get; } = new Operator("Contains");
public static Operator DoesNotContain { get; } = new Operator("DoesNotContain");
...
[EditorBrowsable(EditorBrowsableState.Never)]
public override bool Equals(object? obj) => obj is Operator other && Equals(other);
public bool Equals(Operator other) => string.Equals(_value, other._value, StringComparison.Ordinal);
```

Suggestion: rename `Equals` to `EqualsValue`?

2. Number values aren't handled properly because C# identifiers can't start with a number:

```cs
public static AlertSeverity _ { get; } = new AlertSeverity("0");
```

Suggestion: rename to `Value0`?

**Comment by justinvp** [comment]
> 1. If an enum value is `Equals`, that conflicts with the `Equals()` method.

Is this true? The `Equals` value is static so it's not conflicting with the instance `Equals` methods, it's hiding the static `object.Equals` method, which is a warning. But this is intentional. Nobody will be using `Operator.Equals()` for the `Object.Equals()` functionality. We can avoid the warning by using the `new` keyword to indicate hiding is intentional, e.g.:

```c#
public static new Operator Equals { get; } = new Operator("Equals");
```

This can be handled in the codegen. If we're going to emit a value named `Equals` we should emit the `new` keyword.

**Comment by justinvp** [comment]
> 2. Number values aren't handled properly because C# identifiers can't start with a number:

Is this an actual example from Azure? If so, how does the Azure SDK project the values?

**Comment by mikhailshilkov** [comment]
> Is this true?

Compilation error:

```
  Enums.cs(97, 30): [CS0102] The type 'Operator' already contains a definition for 'Equals'
```

Full example:

```cs
[EnumType]
    public readonly struct Operator : IEquatable<Operator>
    {
        private readonly string _value;

        private Operator(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static Operator Equals { get; } = new Operator("Equals");
        public static Operator NotEquals { get; } = new Operator("NotEquals");
        public static Operator Contains { get; } = new Operator("Contains");
        public static Operator DoesNotContain { get; } = new Operator("DoesNotContain");

        public static bool operator ==(Operator left, Operator right) => left.Equals(right);
        public static bool operator !=(Operator left, Operator right) => !left.Equals(right);

        public static explicit operator string(Operator value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is Operator other && Equals(other);
        public bool Equals(Operator other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
```

**Comment by mikhailshilkov** [comment]
> how does the Azure SDK project the values?

Great question! Answer is `Zero`, `One`, etc: https://github.com/Azure/azure-sdk-for-net/blob/ea67572f05212f0b9bdb9eda858379cbd40deae5/sdk/insights/Azure.ResourceManager.Insights/src/Generated/Models/AlertSeverity.cs#L32

**Comment by komalali** [comment]
> The answer is Zero, One,

I believe that's probably coming from https://github.com/Azure/autorest.common/blob/7d8821d7d6c555adaffc685954e34ea1fe1c83b1/src/CodeNamer.cs#L22-L63

**Comment by justinvp** [comment]
>   Enums.cs(97, 30): [CS0102] The type 'Operator' already contains a definition for 'Equals'

Ah, because of the instance `Equals` we added. Well, I guess our only option then is to rename the enum value. And looks like the Azure SDK uses `EqualsValue` as you suggest. https://github.com/Azure/azure-sdk-for-net/blob/ea67572f05212f0b9bdb9eda858379cbd40deae5/sdk/insights/Azure.ResourceManager.Insights/src/Generated/Models/Operator.cs#L34
