### ISSUE TITLE
Improve "error: no resource plugin '<plugin>' found" error messages

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5725]
Consider an error message you get when running `pulumi up` and a plugin isn't installed (and isn't automatically acquired):

```
pulumi:providers:aws (default):     error: no resource plugin 'aws' found in the workspace or on your $PATH
```

At a minimum, we should show the command you need to run _in_ this error message:

```
pulumi plugin install resource aws v0.15.0
```

Or potentially just automatically install the plugin instead of returning an error

**Comment by justinvp** [comment]
Related: https://github.com/pulumi/pulumi/issues/5619

**Comment by abrahampcmb** [comment]
"just automatically install the plugin instead of returning an error"
ditto

**Comment by aterreno** [comment]
this is still happening, especially on GitHub actions, no resolution yet? no workarounds?

**Comment by RobbieMcKinstry** [comment]
Nothing just yet I'm afraid, but we're always happy to take community contributions! I'd be available to mentor a contribution for this PR.

**Comment by Frassle** [comment]
I thought me and @Zaid-Ajaj had fixed this? Plugins try to install automatically if the engine hits a request for a plugin it doesn't yet have.

**Comment by RobbieMcKinstry** [comment]
@aterreno Would you be able to provide a small project that reproduces the error? 🙏🏻

**Comment by aterreno** [comment]
Hi sorry I am not anymore working on that project / company so I don't have
the codebase to reproduce

**Comment by RobbieMcKinstry** [comment]
I've recently observed that yes, we do automatically install resource plugins if they're missing.
