### ISSUE TITLE
Breaking changes to consider for Pulumi 3.0

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#5731]
#### Confirmed for 3.0

- [x] https://github.com/pulumi/pulumi/issues/6168
- [x] https://github.com/pulumi/pulumi/issues/6592
- [x] https://github.com/pulumi/pulumi/issues/5257
- [x] https://github.com/pulumi/pulumi/issues/3151

#### Under discussion for 3.0

- [ ] https://github.com/pulumi/pulumi-terraform-bridge/issues/315

#### Deferred

- https://github.com/pulumi/pulumi/issues/2484
- https://github.com/pulumi/pulumi/issues/5941

**Comment by joeduffy** [comment]
I was hoping we would have tackled https://github.com/pulumi/pulumi-terraform-bridge/issues/10 by now. If we're not doing so because it's a breaking change (my vote is still to take it since it's security related), we should absolutely consider that as part of the 3.0 milestone.

**Comment by lukehoban** [comment]
> I was hoping we would have tackled pulumi/pulumi-terraform-bridge#10 by now

It is still currently planned to deliver in the next few weeks as a non-breaking change ahead of 3.0. If we discover we cannot keep the breaking change nature of this constrained enough to feel comfortable shipping it now (or require shipping it under a flag), we will definitely do it no later than 3.0.

**Comment by leezen** [comment]
Closing out this tracking issue from 3.0.
