### ISSUE TITLE
Faulty error message for KeyNotFoundException - refers to the wrong stack

### ISSUE THREAD

**Issue by mastoj** [pulumi/pulumi#5733]
When you require an output that doesn't exist in a stack you'll get a key not found exception. That exception will always print the stack name of the "running" stack and not the stack that you are requiring the output from.

https://github.com/pulumi/pulumi/blob/42d1a606a47ee66c478954fc505690ab1a2ad085/sdk/dotnet/Pulumi/Resources/StackReference.cs#L79

**Comment by mikhailshilkov** [comment]
Yeah, it should be `v.Item1` instead of `name` there. Fancy a PR?

**Comment by mastoj** [comment]
@mikhailshilkov can look at it later today. So that is also wrong, I was actually referring to the stack name which is also wrong.

**Comment by mikhailshilkov** [comment]
Oh, wow, indeed, both are wrong!
