### ISSUE TITLE
Help for login command give you the wrong domain for pulumi backend login

### ISSUE THREAD

**Issue by it-ops-liron** [pulumi/pulumi#5734]
When doing
`pulumi login --help`
In one of the outputs there is this line:
`pulumi login https://api.pulumi.acmecorp.com`

This is a mistake (old domain?)

## Expected Behavior
Expected to get: `pulumi login https://api.pulumi.com`

## Steps to Reproduce
`pulumi login --help`

## Version: 2.13.2

**Comment by stack72** [comment]
Hi @it-ops-liron 

This relates the comment above it:

```
If you prefer to log in to a self-hosted Pulumi service backend, specify a URL. For example, run

    $ pulumi login https://api.pulumi.acmecorp.com
```
 
For those users that have a self hosted Enterprise version of Pulumi. You don't need to specify a url, `pulumi login` will "find" the correct SaaS url

I hope this helps?

Paul

**Comment by it-ops-liron** [comment]
> Hi @it-ops-liron
> 
> This relates the comment above it:
> 
> ```
> If you prefer to log in to a self-hosted Pulumi service backend, specify a URL. For example, run
> 
>     $ pulumi login https://api.pulumi.acmecorp.com
> ```
> 
> For those users that have a self hosted Enterprise version of Pulumi. You don't need to specify a url, `pulumi login` will "find" the correct SaaS url
> 
> I hope this helps?
> 
> Paul

That is correct I have not read the note. - Closing

However using local and moving back to pulumi was the step I tried and I didn't understand . :) 
Sorry for the noise.

**Comment by stack72** [comment]
No need to apologise - it's no noise at all - I just needed to confirm why we have that line there 👍 

Hope it's all working for you now!
