### ISSUE TITLE
How to create a collection of resources from an Output<T[]>

### ISSUE THREAD

**Issue by simon0191** [pulumi/pulumi#5736]
It would be nice to have a way to create a collection of resources from an `Output<T[]>`. 

The only way I've found so far to do this is to use an `apply` but the problem is that it's not recommended to create resources inside an `apply` because it can lead to dependencies not being tracked correctly, as well as missing some dependencies during preview.

To give you some context, I wanted to create an SSL certificate with AWS ACM, validate it, and then assigning it to a load balancer.

As `new aws.acm.Certificate(...)` returns a `Certificate` object with `domainValidationOptions` of type `pulumi.Output<outputs.acm.CertificateDomainValidationOption[]>`, when I want to create the DNS record to validate the certificate I need to iterate through the array of `CertificateDomainValidationOptions` but they are wrapped inside a promise/output. The only way I found to iterate over this array was with the apply function, and then, in order to create the DNS records, I couldn't think of another way rather than creating them inside the apply.

Here's the relevant piece of code:

```
const cert = new aws.acm.Certificate("web_salonomi_com_cert", {
  domainName: "web.salonomi.com",
  tags: {
    source: "cloudflare",
  },
  validationMethod: "DNS",
});

const validationRecords = createCloudFlareValidationRecords(cert.domainValidationOptions, cloudflareZoneId)

function createCloudFlareValidationRecords(dvosOutput: Output<DomainValidationOption[]>, cloudflareZoneId: string): Output<cloudflare.Record[]> {

  return dvosOutput.apply((dvos) => {

    return dvos.map((dvo, idx) => {
      const recordName = `web_salonomi_com_cert_validation_record_${idx}`

      return new cloudflare.Record(recordName, {
        // WORKAROUND! use dvosOutput to force it as a dependency of the record
        // WORKAROUND! if it's dry run, set a  string, if not, cloudflare provider will fail
        //             because it validates that `name` and `type` are truthy
        // https://github.com/pulumi/pulumi-cloudflare/blob/0157ec1675be3244146327c7dd821c239d47e189/sdk/nodejs/record.ts#L151
        type: dvosOutput.apply((_) => runtime.isDryRun() ? "CNAME" : dvo.resourceRecordType),
        name: dvosOutput.apply((_) => runtime.isDryRun() ? "x" : dvo.resourceRecordName),
        value: dvo.resourceRecordValue,
        zoneId: cloudflareZoneId,
      })
    })
  })
}
```

Some questions:

1. Is there a better way to do this?
2. I guess one problem is the unkown size of the array, so, What do you think about changing the type of `Certificate.domainValidationOptions` to an array with fixed size? Something like `pulumi.Output<ArrayOfSize2<outputs.acm.CertificateDomainValidationOption>>`, so that all the outputs are available during preview and there's no need to unwrap the array with `apply`

**Comment by leezen** [comment]
In the case where you don't know the final output array size, I agree this can be tricky. However, in this particular case, I think you do know the size of the array: it's the number of domains (including SANs), so you can iterate on that as a prompt value. So you could do something along the lines of the below where `num` is the number of domains for that certificate:

```
for (let idx = 0; idx < num; i++) {
    const recordName = `web_salonomi_com_cert_validation_record_${idx}`
    return new cloudflare.Record(recordName, {
        type: cert.domainValidationOptions[idx].resourceRecordType,
        name: cert.domainValidationOptions[idx].resourceRecordName,
        value: cert.domainValidationOptions[idx].resourceRecordValue,
        zoneId: cloudflareZoneId,
      })
}
```

and this way avoid creating the resources within an apply.

**Comment by Frassle** [comment]
This looks similar to the firewall case @mikhailshilkov pointed out to me in https://github.com/pulumi/pulumi/issues/5464 as an example of a Pulumi program that wasn't quite expressible using applicatives, but also isn't quite right using the apply semantics. See https://github.com/pulumi/pulumi/issues/5464#issuecomment-700587178 for an idea that might be able to handle it.

**Comment by lukehoban** [comment]
BTW - I believe this use case is related to the feature proposal discussed in https://github.com/pulumi/pulumi/issues/4834#issuecomment-644827733.

**Comment by Sytten** [comment]
This is still an issue, anything new since 2020?

**Comment by cdierkens** [comment]
I'm also interested. Trying to use GCP CloudfunctionsV2 but the trigger URI is buried in the Cloud Run service and not returned on the Cloudfunction output.

**Comment by C0DK** [comment]
I have a similar case where the output of a build command creates a bunch of files, and these files have to be uploaded to a bucket. this is not apparently possible.

**Comment by Frassle** [comment]
> this is not apparently possible.

It's possible, you just create the bucket objects inside an apply. It's just not ideal because preview can't see those resources.

Also pretty sure this is asking for exactly the same as https://github.com/pulumi/pulumi/issues/4834 so I'm going to close this one as a duplicate.
