### ISSUE TITLE
[codegen/*] Array env variables may not be parsed correctly in providers

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#5743]
Azure NextGen's first-class provider has a config parameter `AuxiliaryTenantIds` of type "array of strings". It reads its value from an environment variable `ARM_AUXILIARY_TENANT_IDS`.

However, none of SDKs seem to be parsing a string into an array: [.NET](https://github.com/pulumi/pulumi-azure-nextgen/blob/20a695af0d020b34b0f1c336e1b69702755174cc/sdk/dotnet/Provider.cs#L120), [Node](https://github.com/pulumi/pulumi-azure-nextgen/blob/20a695af0d020b34b0f1c336e1b69702755174cc/sdk/nodejs/provider.ts#L36), [Python](https://github.com/pulumi/pulumi-azure-nextgen/blob/master/sdk/python/pulumi_azure_nextgen/provider.py#L68), [Go](https://github.com/pulumi/pulumi-azure-nextgen/blob/master/sdk/go/azure/provider.go#L24). Also, Go code fails to compile (see https://github.com/pulumi/pulumi-azure-nextgen/issues/126).

Terraform [splits](https://github.com/terraform-providers/terraform-provider-azurerm/blob/f639dcebe48a9003f9556c72de08bed2771953ae/azurerm/internal/provider/provider.go#L216) that env variable by `;`. Does that sound good for the default behavior?

**Comment by lblackstone** [comment]
It looks like we [currently don't document](https://www.pulumi.com/docs/reference/pkg/azure-native/provider/#auxiliarytenantids_nodejs) the expected format for this input.
![Screen Shot 2021-03-02 at 3 37 06 PM](https://user-images.githubusercontent.com/9253463/109724670-26f25700-7b6d-11eb-968a-929113948c3d.png) 
The classic Azure provider supports this as an [undocumented feature](https://github.com/terraform-providers/terraform-provider-azurerm/issues/4378#issuecomment-534688224), but it's not schematized.
 
> Terraform splits that env variable by `;`. Does that sound good for the default behavior?

Generally, I'd expect a list to be comma-delimited, so I'm not sure that makes sense as a global default. For the azure-native provider case, I'm going to drop support for the `ARM_AUXILIARY_TENANT_IDS` env var, which makes this issue a moot point for now.

If we do choose to support list inputs for env vars, I could imagine users trying to set them in a variety of ways, so we'd probably want more robust parsing:
```
LIST="a,b"
LIST="[a,b]"
LIST="a;b"
LIST="a b"
LIST="[a;b]"
```

**Comment by leezen** [comment]
Closed with https://github.com/pulumi/pulumi-azure-native/pull/624
