### ISSUE TITLE
`pulumi preview --json` shows plugin installation output

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#5747]
A JSON preview still displays plugin acquisition output. This breaks the ability to parse the JSON output as you have a bunch of unstructured text at the beginning of the output. The `--json` flag should disable all other calls to stdout. To repro: 

`pulumi plugin rm --all && pulumi preview --json`

**Comment by EvanBoyle** [comment]
To workaround this for Automation API, you can use  `workspace.InstallPlugin` to install plugins ahead of time:

- go: https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v2/go/x/auto#example-LocalWorkspace.InstallPlugin
- node: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/x/automation/#LocalWorkspace-installPlugin

**Comment by joeduffy** [comment]
I should note that it's also just bad stdout/stderr hygiene to be emitting things like plugin download status to stdout.

**Comment by lukehoban** [comment]
I believe there are two options here:
1. Render plugin installation status only to debug logs (`logging.V(preparePluginVerboseLog).Infof`)
2. Render plugin installation status to diag sink (`sink.Infof`)

With either option - we likely have to change the style of the rendering - as it's not clear we can use the ProgressBar approach in either of those approaches.

I'm not entirely clear on what the user experience would be for (2).  It will in part depend on what event stream renderer is being applied - and I suspect it would be fairly natural in all existing renderers (not shown at all for `pulumi preview --json`, and shown as an ephemeral status on the stack resource for the default update status table rendering).  I am not sure though whether common cases of plugin installation happen too early for this rendering to work well. I expect we'll need to try this out and see what works well from a user experience perspective.

(1) is simpler, but hides a potential source of significantly delays.  Users could frequently (but semi-randomly) sit waiting for 2-10s with no indication of progress.  I'm inclined to try to do (2) if possible.

**Comment by EvanBoyle** [comment]
It might be a helpful reminder that the only reason I raised this issue is because it breaks parsing `pulumi preview --json` which came up from the Automation API Go SDK. Given that we are planning on removing this from the Automation API via https://github.com/pulumi/pulumi/issues/6308, the priority of fixing this might be lower for the time being. Still good to tackle if it is straightforward.

**Comment by komalali** [comment]
Yup yup, aware that this is not necessarily top of the list for priority since we're planning to do #6308  - just wanted to get an idea of the work required so I have a better understanding for the next iteration planning. 

Thanks for the notes @lukehoban that's very helpful!

**Comment by komalali** [comment]
Some additional info relevant to this issue. The problem here goes beyond just the `--json` usage, plugin download should not print to stdout regardless. From @lukehoban's suggestions, `(2) Render plugin installation status to diag sink (sink.Infof)` would still result in this information being printed to stdout as part of the `Diagnostics` similar to what we see for `go build` output. https://github.com/pulumi/pulumi/issues/6546

The experience is particularly deteriorated when using the `--non-interactive` flag, because the diag sink prints incrementally in that case, and then again as part of the `Diagnostics` block at the end.

**Comment by lcsmontiel** [comment]
i am experiencing the same issue.

Download plugin outputs should'nt be in pulumi preview --json output because this impact in JSON parsing.

version v2.22.0 here

**Comment by joeduffy** [comment]
Just hit this and took a look. I think two very targeted edits gets this output back into stderr where it belongs:

```diff
diff --git a/pkg/engine/plugins.go b/pkg/engine/plugins.go
index 880dd64da..e9f380748 100644
--- a/pkg/engine/plugins.go
+++ b/pkg/engine/plugins.go
@@ -16,6 +16,7 @@ package engine
 
 import (
 	"fmt"
+	"os"
 	"sort"
 
 	"github.com/blang/semver"
@@ -176,7 +177,7 @@ func installPlugin(plugin workspace.PluginInfo) error {
 		return err
 	}
 
-	fmt.Printf("[%s plugin %s-%s] installing\n", plugin.Kind, plugin.Name, plugin.Version)
+	fmt.Fprintf(os.Stderr, "[%s plugin %s-%s] installing\n", plugin.Kind, plugin.Name, plugin.Version)
 	stream = workspace.ReadCloserProgressBar(stream, size, "Downloading plugin", cmdutil.GetGlobalColorization())
 
 	logging.V(preparePluginVerboseLog).Infof(
diff --git a/sdk/go/common/workspace/plugins.go b/sdk/go/common/workspace/plugins.go
index 9d40f349b..8d58dcc6c 100644
--- a/sdk/go/common/workspace/plugins.go
+++ b/sdk/go/common/workspace/plugins.go
@@ -761,6 +761,7 @@ func ReadCloserProgressBar(
 
 	// If we know the length of the download, show a progress bar.
 	bar := pb.New(int(size))
+	bar.Output = os.Stderr
 	bar.Prefix(colorization.Colorize(colors.SpecUnimportant + message + ":"))
 	bar.Postfix(colorization.Colorize(colors.Reset))
 	bar.SetMaxWidth(80)
```

**Comment by joeduffy** [comment]
Closed by https://github.com/pulumi/pulumi/commit/7101046709155ae6bec839f36203d5b3c05c42f2.
