### ISSUE TITLE
"project is missing a 'name' attribute" error 

### ISSUE THREAD

**Issue by prasannapad** [pulumi/pulumi#5765]
### Problem description

First time quickstart experience failed with --"name" attribute error -- though the instructions say "simply press ENTER to accept the (default)."

- I saw a product documentation issue on the following URL: https://www.pulumi.com/docs/get-started/azure/create-project/

Repro steps:
c:\repos\pulumi\quickstart>pulumi new azure-typescript
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name:
project description: (A minimal Azure TypeScript Pulumi program)
Created project ''

error: failed to load Pulumi project located at "c:\\repos\\pulumi\\quickstart\\Pulumi.yaml": project is missing a 'name' attribute

### Suggestions for a fix

Pulumi could auto-generate a default name or modify the instructions to require a project name.

**Comment by justinvp** [comment]
I believe this was recently fixed by https://github.com/pulumi/pulumi/pull/5504
