### ISSUE TITLE
cli unexpectedly traverses up directory tree

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5768]
If I run `pulumi` from a directory that does not contain a Pulumi project, `pulumi` traverses up the directory tree until it finds a directory with a Pulumi project. I don't think this is what users would expect a cli tool to do and caused confusion for me personally.

#### Version

pulumi cli - `v2.13.0`

#### Steps to reproduce

```shell
mkdir my-proj
cd my-proj
pulumi new typescript -y 
mkdir my-proj-subdir
cd my-proj-subdir

pulumi pre      # preview runs successfully from empty directory
```

#### Current behavior

`pulumi` commands run successfully.

#### Expected behavior

`pulumi` should fail with the usual "no valid project" error.

**Comment by lukehoban** [comment]
This is indeed intentional, and is fairly common for tools like Pulumi that have a file marking the root of the project (git, typescript, etc). It’s documented in the second sentence of the Pulumi projects page: https://www.pulumi.com/docs/intro/concepts/project/.
