### ISSUE TITLE
[Automation API] Provide mechanism to `cancel` a running deployment

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#5779]
#### Ask

The Automation API should support the equivalent to `pulumi cancel` to cancel a running deployment.

#### Use case

A user should be able to handle `CTRL+C` on their Automation program as gracefully as possible by canceling currently running deployments.

**Comment by charlex** [comment]
I don't see a way to call this programmatically on the Stack object either. I'd like to call a function, just as as I would call `await stack.up()` or `await stack.destroy()` to `await stack.cancel()`

**Comment by komalali** [comment]
This looks like a duplicate of https://github.com/pulumi/pulumi/issues/5531 so I'm closing it out in favor of the other issue.

Feel free to reopen if there's a distinction I'm missing.
