### ISSUE TITLE
Kubenetes Secret physical name cannot be set

### ISSUE THREAD

**Issue by hammadzz** [pulumi/pulumi#5790]
## Expected Behavior

Setting physical name for k8s.core.v1.Secret resource should be possible.

## Current Behavior

Creating k8s.core.v1.Secret resource results in forceful autonaming.

See docs on [k8s.core.v1.Secret](https://www.pulumi.com/docs/reference/pkg/kubernetes/core/v1/secret/)

## Steps to Reproduce

1. See resource docs, missing name property in args

**Comment by benjick** [comment]
Check out `metadata`: https://www.pulumi.com/docs/reference/pkg/kubernetes/core/v1/secret/#objectmeta
