### ISSUE TITLE
Expose the Pulumi.yaml "name" to Pulumi programs

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#580]
Today, Pulumi programs get access to `pulumi.getStack()` and `pulumi.getProject()` - but the name I tend to want most often is the `name` from the `Pulumi.yaml` file.

For example, in standard usage - the names might be the following:

- Pulumi.yaml name: `todo`
- stack name: `production`
- project: `pulumi-cloud` (actually I might be wrong about that - I really have no idea what this one is)

The latter two don't really provide any meaningful identity associated with the program - and in particular - the `stack` name is effectively a qualifier on the first name.

Is there any reason we can't provide the program name as well?

**Comment by palladius** [comment]
excuse me, how do you expose the project name it via CLI?

Something like:
```
cat Pulumi.yaml  | egrep '^name:' | awk '{print $2}'
```

In other words, I'd like the project name to be exposed by CLI too.
