### ISSUE TITLE
[codegen/go] Register package/module resources

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5801]
Go side of https://github.com/pulumi/pulumi/pull/5806

The generated code will need to call [`RegisterResourcePackage`/`RegisterResourceModule`](https://github.com/pulumi/pulumi/blob/260620430c4c8a41a8d7adfbd66f68ba6fd1e168/sdk/go/pulumi/rpc.go#L682-L718) in Go package `init` functions.

Looks like we'll also need to tweak the signatures of `RegisterResourcePackage`, `RegisterResourceModule`, and the interfaces to match similar tweaks we've made to [Python](https://github.com/pulumi/pulumi/pull/5805) and [Node.js](https://github.com/pulumi/pulumi/pull/5837).

**Comment by lblackstone** [comment]
I started stubbing out what the generated files should look like and ran into a couple more questions:

1. Do we need to pass `ctx` to the construct methods?
2. Is there an equivalent method for the `getVersion` methods used in other SDKs?

Here's the gist: https://gist.github.com/lblackstone/8ab76fc0c4f5cdeeecd398e2330053db

**Comment by justinvp** [comment]
> 1. Do we need to pass `ctx` to the construct methods?

I'm not sure. I initially thought, "yes," to be able to use it to call but I'm not seeing how to get a `ctx` inside `rpc.go` where these functions would be called when unmarshaling a resource reference. @pgavlin?

> 2\. Is there an equivalent method for the `getVersion` methods used in other SDKs?

Hmm, doesn't look like it. Not sure how we want to handle this for Go. @pgavlin, any ideas?

**Comment by pgavlin** [comment]
> I'm not sure. I initially thought, "yes," to be able to use it to call but I'm not seeing how to get a ctx inside rpc.go where these functions would be called when unmarshaling a resource reference. @pgavlin?

We do need to flow the context, yes, as we need to be able to make a call into the engine to get the resource's state. We'll have to plumb the current context through the deserializer.

> Hmm, doesn't look like it. Not sure how we want to handle this for Go. @pgavlin, any ideas?

Not offhand. We definitely need something like this, though, as Go modules do allow a single program to use two versions of a provider. I have no clue how to implement this properly, though: the scripts we use to determine the version will produce incorrect results if the code for the current version is not committed. Other languages get around this by updating the version prior to publishing the package and then fetching it dynamically at runtime, but for Go, the code _is_ the package. AFAICT, this means that we need to stamp the package version into the Go code at codegen time, which we can't do b/c we don't _know_ the version at codegen time. It's kind of a mess.

**Comment by lblackstone** [comment]
> We do need to flow the context, yes, as we need to be able to make a call into the engine to get the resource's state. We'll have to plumb the current context through the deserializer.

@pgavlin I took a crack at this in #6089

**Comment by pgavlin** [comment]
An idea regarding `getVersion`: for now, we could support no more than a single version of a particular package at a given time. We could add the ability to support multiple side-by-side versions in future releases.
