### ISSUE TITLE
Required attribute is not set error when following documentation to create custom API Gateway domain

### ISSUE THREAD

**Issue by esp1** [pulumi/pulumi#5813]
I'm encountering an error when trying to follow the "Configuring AWS API Gateway Custom Domains and SSL using Route53 and ACM" instructions here: https://www.pulumi.com/docs/guides/crosswalk/aws/api-gateway/#configuring-aws-api-gateway-custom-domains-and-ssl-using-route53-and-acm. When I execute `pulumi up` on the example configuration it fails with a `Required attribute is not set` error on the `sslCertValidationRecord` resource, which is configured in the documentation as:
```
const sslCertValidationRecord = new aws.route53.Record("sslCertValidationRecord", {
    zoneId: webDnsZone.id,
    name: sslCert.domainValidationOptions[0].resourceRecordName,
    type: sslCert.domainValidationOptions[0].resourceRecordType,
    records: [ sslCert.domainValidationOptions[0].resourceRecordValue ],
    ttl: 10 * 60 /* 10 minutes */,
});
```

Note: This looks like similar to https://github.com/pulumi/pulumi/issues/5634 which was closed, but I am encountering this issue with the latest pulumi version `v2.14.0`. I do not know if this a new issue or a regression.

## Expected Behavior

Resources should be provisioned without errors

## Current Behavior

Provisioning fails with the following error:
```
Diagnostics:
  aws:route53:Record (sslCertValidationRecord):
    error: aws:route53/record:Record resource 'sslCertValidationRecord' has a problem: Required attribute is not set
    error: aws:route53/record:Record resource 'sslCertValidationRecord' has a problem: Required attribute is not set
```

## Steps to Reproduce

1. Follow instructions and use the example configuration for [Configuring AWS API Gateway Custom Domains and SSL using Route53 and ACM](https://www.pulumi.com/docs/guides/crosswalk/aws/api-gateway/#configuring-aws-api-gateway-custom-domains-and-ssl-using-route53-and-acm)
2. Run `pulumi up`

## Context (Environment)

Pulumi version v2.14.0
Mac OS Catalina version 10.15.7

**Comment by LeslieOA** [comment]
@esp1 I'm [experiencing the same thing](https://github.com/pulumi/pulumi/issues/5633#issuecomment-731673124).

@leezen [has a solution](https://github.com/pulumi/pulumi/issues/5633#issuecomment-719088070) that may work for you, so it'd be good to know your mileage:

> It seems this is somehow related to the recently released preview functionality. We'll continue to investigate. In the meantime, as mentioned above, downgrading is one path forward. Alternatively, you can also set the environment variable `PULUMI_DISABLE_PROVIDER_PREVIEW=1` (or `true`) with pulumi CLI `2.12.x` and should be able to proceed.

**Comment by esp1** [comment]
@LeslieOA thanks for the tip - I tried `PULUMI_DISABLE_PROVIDER_PREVIEW=1 pulumi up` and it didn't show the `Required attribute is not set` error, but it hung when attempting to create the `aws:acm:CertificateValidation` until finally failing with the below error about an hour later:

```
     Type                              Name                     Status                  Info
     pulumi:pulumi:Stack               dsl-infra-dev            **failed**              1 error
 +   ├─ pulumi:providers:aws           usEast1                  created                 
 +   ├─ aws:acm:Certificate            sslCert                  created                 
 +   ├─ aws:route53:Record             sslCertValidationRecord  created                 
 +   └─ aws:acm:CertificateValidation  sslCertValidationIssued  **creating failed**     1 error
 
Diagnostics:
  pulumi:pulumi:Stack (dsl-infra-dev):
    error: update failed
 
  aws:acm:CertificateValidation (sslCertValidationIssued):
    error: 1 error occurred:
        * Error describing created certificate: Expected certificate to be issued but was in state PENDING_VALIDATION
```

**Comment by LeslieOA** [comment]
@esp1 Our mileage is the same it seems. 
Had this issue all of yesterday (multiple attempts).

I'm attempting to achieve this manually until there's a fix on the horizon, but I'll report back my progress irrespective.

**Comment by leezen** [comment]
```
 * Error describing created certificate: Expected certificate to be issued but was in state PENDING_VALIDATION
```

The above message suggests that the validation didn't actually succeed correctly. Have you verified that the records are queryable publicly via DNS?

**Comment by esp1** [comment]
Ah you're right @leezen - thanks for pointing that out. I'm having some issues with my domain registration that I'm pretty sure are the reason for that last PENDING_VALIDATION error. It's going to take me a while to sort that out but I'll update here once I clear that hurdle.

**Comment by leezen** [comment]
Closing for now as I believe the original issue should no longer be a problem. Please re-open if that's not the case.
