### ISSUE TITLE
(Azure) Pulumi up fails when subscription names are the same on Different Topics

### ISSUE THREAD

**Issue by shahabganji** [pulumi/pulumi#5814]
I am provisioning a service bus on my application, and I have multiple Topics with obviously different names configured, each topic has its own subscriptions. In the Azure portal, one could define subscriptions with the same name on different topics but when I 
tried to do the provisioning the same scenario via pulumi I got the following error: 

```bash
Diagnostics:
  azure:servicebus:Subscription (sbs-sample):
    error: Duplicate resource URN 'urn:pulumi:dev::PulumiProvisioningSampleServiceBus::azure:servicebus/subscription:Subscription::sbs-sample'; try giving it a unique name
```

## Expected Behavior

When you define subscriptions on Azure Portal, it is possible that two **different** topics have **subscriptions** which their names look the same; while they are on different topics, there should not be any problem. I expect pulumi provisioning to do the same.

## Current Behavior
It throws an exception indicating that the subscription name is not unique. It seems that pulumi does not take the topic name into account.

![image](https://user-images.githubusercontent.com/4405518/99953899-3c8ffd80-2d82-11eb-9cc3-096ca2b41d1a.png)

When you create a subscription via the Azure CLI or portal, it looks like the following:

![image](https://user-images.githubusercontent.com/4405518/99959195-d9569900-2d8a-11eb-9e6a-eef10e91e6c0.png)

## Steps to Reproduce

[Here](https://github.com/shahabganji/PulumiProvisioningSampleServiceBus) you could find a sample project that helps to reproduces the steps.

## Context (Environment)
> How has this issue affected you? What are you trying to accomplish? 

I have two separate topics each of which bound for a special sort of events, I want each application to be able to subscribe to these topics by the application name as the subscription name.

**Comment by mikhailshilkov** [comment]
You should give different logical names to your resources. The physical subscription name can still be the same

```cs
var sampleSubscriptionOnFirstTopic =
                new Pulumi.Azure.ServiceBus.Subscription("sbs-sample-1",
                    new Pulumi.Azure.ServiceBus.SubscriptionArgs
                    {
                        Name = "sbs-sample",
                        ResourceGroupName = SampleResourceGroupName,
                        NamespaceName = ServiceBusNamespaceName,
                        TopicName = FirstTopicName,
                        MaxDeliveryCount = 5,
                    });

            var sampleSubscriptionOnSecondTopic =
                new Pulumi.Azure.ServiceBus.Subscription("sbs-sample-2",
                    new Pulumi.Azure.ServiceBus.SubscriptionArgs
                    {
                        Name = "sbs-sample",
                        ResourceGroupName = SampleResourceGroupName,
                        NamespaceName = ServiceBusNamespaceName,
                        TopicName = SecondTopicName,
                        MaxDeliveryCount = 5,
                    });
```

**Comment by shahabganji** [comment]
@mikhailshilkov Thanks for the clarification 👍🏼
