### ISSUE TITLE
[codegen/python] Panic when referencing some external types

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5819]
The following properties cause the Python codegen to panic with:

```
panic: interface conversion: interface {} is json.RawMessage, not python.PropertyInfo
github.com/pulumi/pulumi/pkg/v2/codegen/python.recordProperty(0xc000d8c8c0, 0xc0016fc2a0, 0xc0016fc2d0, 0xc000548f58)
github.com/pulumi/pulumi/pkg/v2@v2.14.1-0.20201121160205-9a707c4e03b6/codegen/python/gen.go:1446 +0x3d
```

## eks:index:ManagedNodeGroup

```go
"launchTemplate": {
	TypeSpec:    schema.TypeSpec{Ref: awsRef("#/types/aws:eks%2FNodeGroupLaunchTemplate:NodeGroupLaunchTemplate")},
	Description: "Launch Template settings.",
},
"remoteAccess": {
	TypeSpec:    schema.TypeSpec{Ref: awsRef("#/types/aws:eks%2FNodeGroupRemoteAccess:NodeGroupRemoteAccess")},
	Description: "Remote access settings.",
},
"scalingConfig": {
	TypeSpec: schema.TypeSpec{Ref: awsRef("#/types/aws:eks%2FNodeGroupScalingConfig:NodeGroupScalingConfig")},
	Description: "Scaling settings.\n\n" +
		"Default scaling amounts of the node group autoscaling group are:\n" +
		"  - desiredSize: 2\n" +
		"  - minSize: 1\n" +
		"  - maxSize: 2",
},
```

## eks:index:CoreData

```go
"encryptionConfig": {
	TypeSpec: schema.TypeSpec{Ref: awsRef("#/types/aws:eks%2FClusterEncryptionConfig:ClusterEncryptionConfig")},
},
```

This line is panicing:

https://github.com/pulumi/pulumi/blob/505d53421ed12ae0e00d3e489eb9686b619eda7a/pkg/codegen/python/gen.go#L1446

The value is `json.RawMessage` rather than `python.PropertyInfo`.

I wonder if the following isn't called for externally referenced schemas?

https://github.com/pulumi/pulumi/blob/505d53421ed12ae0e00d3e489eb9686b619eda7a/pkg/codegen/python/importer.go#L57-L64

**Comment by pgavlin** [comment]
@justinvp that seems correct. Do you want to look into this further?

**Comment by justinvp** [comment]
@viveklak, were you able to address this as part of https://github.com/pulumi/pulumi/pull/5826? I know you were running into it there because you needed the `GoPackageInfo`.

**Comment by justinvp** [comment]
I have a fix for this available -- just needs minor cleanup and I'll open the PR.
