### ISSUE TITLE
Cluster import is not successful: Computed attribute cannot be set message

### ISSUE THREAD

**Issue by MatiasNMont** [pulumi/pulumi#5828]
When you want to import a cluster with the `pulumi import aws:eks/cluster:Cluster <name> <id> ` command, the following message appears: 

```
aws:eks:Cluster (mserv-test-eks):
    error: aws:eks/cluster:Cluster resource 'resource' has a problem: Computed attribute cannot be set
    error: aws:eks/cluster:Cluster resource 'resource' has a problem: Computed attribute cannot be set
    error: Preview failed: one or more inputs failed to validate
```

The cluster exists on AWS. When I start a stack with pulumi and try to import the cluster the above error does not let me continue the import.

## Expected Behavior
Cluster should be imported to stack 

## Current Behavior
the error described above appears and the task fails

**Comment by colearendt** [comment]
I believe I may be seeing the exact same problem when creating a fresh EKS cluster on AWS. I have narrowed it down to the `resource_name` parameter. Without it, I get:
```
    TypeError: __init__() missing 1 required positional argument: 'resource_name'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

But with it:
```
Diagnostics:
  aws:eks:Cluster (training-eks-cluster):
    error: aws:eks/cluster:Cluster resource 'training-eks-cluster' has a problem: Computed attribute cannot be set
```

**Comment by miranda98** [comment]
I'm getting the same error for `role_arn`
Without `role_arn` I get:
```
TypeError: Missing required property 'role_arn'
```
But with it I get:
```
error: aws:eks/cluster:Cluster resource 'develop-develop-test-eks-cluster-eks' has a problem: Computed attribute cannot be set
```

**Comment by colearendt** [comment]
I had to remove `vpc_id`. https://github.com/pulumi/pulumi-aws/issues/1278 Hope it helps!

**Comment by oliveratprimer** [comment]
Getting the same error when trying to import an EKS cluster
