### ISSUE TITLE
When importing errors, the text saying to copy and paste the code is still shown

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#5833]
Pulumi v2.14.0
If an import fails, we still show the text explaining that the user should copy and paste the generated code into the application. It also shows the text explaining that the resources are protected.

## Expected Behavior

There is no code to copy and paste so it doesn't need to show either paragraph.

## Current Behavior

The error message is shown and then the two messages from [here](https://github.com/pulumi/pulumi/blob/b0580ab998b1647b4c624b31cc0f73254f8eca08/pkg/cmd/pulumi/import.go#L477-L486) are shown.

## Steps to Reproduce

1. Run `pulumi import aws:s3/bucket:Bucket bucket bucket-name` (or another name if you happen to have access to that bucket)

**Comment by stack72** [comment]
@pierskarsenbarg the fix for this has been merged to master and is awaiting release

**Comment by stack72** [comment]
Closed via https://github.com/pulumi/pulumi/pull/5825
