### ISSUE TITLE
Turn on support for feature "resourceReferences"

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5838]
We need to enable this by default:

https://github.com/pulumi/pulumi/blob/06da84a752600e0ee998f6d1ac800c241d4dcddc/pkg/resource/deploy/source_eval.go#L533-L534

But before we do that we need to ensure the following:

- We need to make sure that we can use downlevel language SDKs with resource references enabled
- As well as downlevel providers
- We also need to ensure that the newer SDKs work with downlevel CLIs

**Comment by lblackstone** [comment]
PR reverted in #5850 

This change will require further testing.

**Comment by lblackstone** [comment]
Tested by setting the experimental flag in the examples repo and verifying that the nightly cron job passed: https://github.com/pulumi/examples/runs/1522860936?check_suite_focus=true#step:22:492

Re-enabling this change in #5905
