### ISSUE TITLE
stacks created with azure/compute and azure/network are not unit testable in go

### ISSUE THREAD

**Issue by thomas-b-jackson** [pulumi/pulumi#5844]
I got the [unit tests in go example working](https://github.com/pulumi/examples/tree/74db62a03d013c2854d2cf933c074ea0a3bbf69d/testing-unit-go)

I then tried to create a comparable test using azure/network and azure/compute.

The tests are failing. 

Root cause appears to be that calls to compute.NewLinuxVirtualMachine, etc work in test mode, but the output state of all the attributes set in main.go are nil (e.g. AdminUserName, Location, etc)

## Expected Behavior

Test passes the assertion: `assert.Equal(t, "azure-vm-dev", computerName)`

## Current Behavior

Test fails the assertion: `assert.Equal(t, "azure-vm-dev", computerName)`

computerName is empty, as are ALL other attributes

## Steps to Reproduce
1. setup main.go and main_test.go per context
1. in a debugger session, run:
   `go test`
1. set a breakpoint in main_test.go at line 28
1. expand infra variable per:
   `infra->server->Name->Output State->value
1. note that value is nil
1. note that value of ALL output states is nil

## Context (Environment)

go version go1.14.2 linux/amd64

Visual Studio Code: Version: 1.51.1 

main.go as:
```
package main

import (
	"github.com/pulumi/pulumi-azure/sdk/v3/go/azure/compute"
	"github.com/pulumi/pulumi-azure/sdk/v3/go/azure/network"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type infrastructure struct {
	server *compute.LinuxVirtualMachine
}

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		_, err := createInfrastructure(ctx)

		return err
	})
}
func createInfrastructure(ctx *pulumi.Context) (*infrastructure, error) {

	_, err := network.NewVirtualNetwork(ctx, "exampleVirtualNetwork", &network.VirtualNetworkArgs{
		AddressSpaces: pulumi.StringArray{
			pulumi.String("10.0.0.0/16"),
		},
		Location:          pulumi.String("westus2"),
		ResourceGroupName: pulumi.String("npeccpdevwu2RgGolduck"),
	})
	if err != nil {
		return nil, err
	}

	subnetNetwork, err := network.LookupSubnet(ctx, &network.LookupSubnetArgs{
		Name:               "clusternodes",
		ResourceGroupName:  "npeccpdevwu2RgGolduck",
		VirtualNetworkName: "npeccpdevwu2RgGolduckVPC",
	})
	if err != nil {
		return nil, err
	}
	exampleNetworkInterface, err := network.NewNetworkInterface(ctx, "exampleNetworkInterface", &network.NetworkInterfaceArgs{
		Location:          pulumi.String("westus2"),
		ResourceGroupName: pulumi.String("npeccpdevwu2RgGolduck"),
		IpConfigurations: network.NetworkInterfaceIpConfigurationArray{
			&network.NetworkInterfaceIpConfigurationArgs{
				Name:                       pulumi.String("internal"),
				SubnetId:                   pulumi.String(subnetNetwork.Id),
				PrivateIpAddressAllocation: pulumi.String("Dynamic"),
			},
		},
	})
	if err != nil {
		return nil, err
	}
	linuxMachine, err := compute.NewLinuxVirtualMachine(ctx, "exampleLinuxVirtualMachine", &compute.LinuxVirtualMachineArgs{
		ResourceGroupName:             pulumi.String("npeccpdevwu2RgGolduck"),
		Location:                      pulumi.String("westus2"),
		Size:                          pulumi.String("Standard_F2"),
		AdminUsername:                 pulumi.String("adminuser"),
		DisablePasswordAuthentication: pulumi.Bool(false),
		AdminPassword:                 pulumi.String("x8NL6w86jeBt"),
		NetworkInterfaceIds: pulumi.StringArray{
			exampleNetworkInterface.ID(),
		},
		OsDisk: &compute.LinuxVirtualMachineOsDiskArgs{
			Caching:            pulumi.String("ReadWrite"),
			StorageAccountType: pulumi.String("Standard_LRS"),
		},
		SourceImageReference: &compute.LinuxVirtualMachineSourceImageReferenceArgs{
			Publisher: pulumi.String("Canonical"),
			Offer:     pulumi.String("UbuntuServer"),
			Sku:       pulumi.String("16.04-LTS"),
			Version:   pulumi.String("latest"),
		},
	})
	if err != nil {
		return nil, err
	}

	return &infrastructure{
		server: linuxMachine,
	}, nil
}
```

main_test.go as:
```
package main

import (
	"fmt"
	"sync"
	"testing"

	"github.com/pulumi/pulumi/sdk/v2/go/common/resource"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
	"github.com/stretchr/testify/assert"
)

type mocks int

func (mocks) NewResource(typeToken, name string, inputs resource.PropertyMap, provider, id string) (string, resource.PropertyMap, error) {
	return name + "_id", inputs, nil
}

func (mocks) Call(token string, args resource.PropertyMap, provider string) (resource.PropertyMap, error) {
	return args, nil
}

func TestInfrastructure(t *testing.T) {
	err := pulumi.RunErr(func(ctx *pulumi.Context) error {
		infra, err := createInfrastructure(ctx)
		assert.NoError(t, err)

		var wg sync.WaitGroup
		wg.Add(1)

		//  Instances must be named correctly
		pulumi.All(infra.server.Name).ApplyT(func(all []interface{}) error {
			computerName := all[0].(string)

			fmt.Printf("name: %s", computerName)
			assert.Equal(t, "azure-vm-dev", computerName)
			wg.Done()
			return nil
		})

		wg.Wait()
		return nil
	}, pulumi.WithMocks("project", "stack", mocks(0)))
	assert.NoError(t, err)
}

```

Don't think I can recommend/use pulumi if unit testing isn't supported in azure.

**Comment by leezen** [comment]
Perhaps I'm missing something, but isn't this a problem with the mock you've setup? Your mock returns `return name + "_id", inputs, nil` so it's simply returning the inputs as the outputs. However, none of your inputs include `Name` so `Name` is going to be `nil`. So you'll need to either pass that as an input upon resource creation or have the mock include this property as an output.

**Comment by thomas-b-jackson** [comment]
hey @leezen , i tried to express this in my "Steps to Reproduce", but all of the values are empty, including the value is set (e.g. ResourceGroupName, Location, etc)

**Comment by leezen** [comment]
This is because at that point in the code, not all outputs are necessarily resolved. This why in the test code, the checks are done within the `Apply`

A couple things to try to see what I mean:
1. If you add `inputs["name"] = resource.NewStringProperty("azure-vm-dev")` within `NewResource` you'll see that your test passes. Obviously, you'll need to adjust this function to properly decide how to mock the various resources that you need to mock.
2. If you set a breakpoint after `wg.Wait()` in your test, you'll see that the `known` property on your output flips from `false` to `true` and that the output has a value (since at this point, `wg.Done()` was invoked within the `Apply`).
