### ISSUE TITLE
Feature request: open the Pulumi Console with a single command

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi#5854]
Today, the `pulumi stack ls` command shows the corresponding Pulumi Console for each stack in a project. The links are clickable too. It would be nice to be able to launch the Pulumi Console in the browser by simply running `pulumi stack console` for the currently selected stack, as well as support the `-s` flag for passing a stack name. I tried searching for an existing issue but couldn't find one. Please feel free to close this as a dupe if one already exists.

**Comment by stack72** [comment]
This is covered by:

```
▶ pulumi console --help
Opens the current stack in the Pulumi Console

Usage:
  pulumi console [flags]
```

It doesn't support adding `-s` so we can mark this as an enhancement
