### ISSUE TITLE
Octopus Deploy Step Template Azure Account Integration

### ISSUE THREAD

**Issue by thorpgeek** [pulumi/pulumi#5858]
When I tried using the Octopus Deploy step template, an following the steps provided, the step does not work.

## Expected Behavior
Create a variable Azure, and the value is an Azure Account, add a step to the project fill out all required inputs. Create a release and deploy a release, create or amend pulumi stack.

## Current Behavior
Create a variable Azure, and the value is an Azure Account, add a step to the project fill out all required inputs. Create a release and deploy a release, errors out saying no ClientID or SubscriptionID has been set.

## Context (Environment)
Octopus Deploy

## Work Around
Create a copy of the step template and edit the Powershell script and change the values to this

Azure.ClientID
to
Azure.Client

Azure.SubscriptionID
to
Azure.SubscriptionNumber

Following the documentation provided by Octopus Deploy
https://octopus.com/docs/projects/variables/azure-account-variables

**Comment by praneetloke** [comment]
Hi @thorpgeek! Thank you for reporting the issue. It seems that the property names were updated at some point after the step templates were released. I have opened a [PR](https://github.com/OctopusDeploy/Library/pull/1050) to update the step templates in the library.

**Comment by praneetloke** [comment]
The PR has been merged. The new version of the templates should now be available in the library. @thorpgeek you should be able to update the version you've installed now.
