### ISSUE TITLE
Strange error messages when performing `pulumi up` or `pulumi destroy`

### ISSUE THREAD

**Issue by iamNoah1** [pulumi/pulumi#5859]
When I run `pulumi up` or `pulumi destroy` only from time to time I get the following error message: 

`assertion failed [*ret_index + 2 == num_insts]: RET should be second last instruction in translation
(StateRecovery.cpp:304 check_cfg)`

The strange thing about it is that the CLI tab is not responsive anymore after that. ctrl + c does not work. 
## Expected Behavior

There should be an error message that is a little bit more clear about what went wrong. At least the CLI should not get unresponsive. 

## Current Behavior

see description

## Steps to Reproduce

Really hard to say because the issue only appears from time to time. Randomly. 

## Context (Environment)
Probably the most important context information that I am working on a new apple M1 ARM machine. I could imagine that the problem has something to do with that fact.

**Comment by lukehoban** [comment]
> Probably the most important context information that I am working on a new apple M1 ARM machine. I could imagine that the problem has something to do with that fact.

Yes - this does appear to be a Rosetta 2 translation issue.  This error is not coming from Pulumi - it appears to be coming from the binary translation process itself.

I only see one other occurrence of this on the web currently - but under similar conditions with running an darwin/amd64 binary on an M1. https://github.com/prysmaticlabs/prysm/issues/7950. 

We'll need to try to reproduce this on an M1 machine to investigate further and mitigate.

Direct support for arm64 in `pulumi` is tracked in https://github.com/pulumi/pulumi/issues/4868.

**Comment by lukehoban** [comment]
As a somewhat random guess - any chance you can try using `GODEBUG=asyncpreemptoff=1 pulumi up` and see if you still see this issue?

**Comment by iamNoah1** [comment]
@lukehoban thanks for the fast reply. Seems to work, but as I described the problem only showed up from time to time. So I will keep an eye on it and give feedback accordingly.

**Comment by zosmac** [comment]
Found this track searching on StateRecovery.cpp:304 check_cfg. 
https://github.com/golang/go/issues/42700

I am getting this same behavior with a Go program I am writing, running on the new M1. Same intermittent behavior as reported here; my program may run for hours or days, or may crash much sooner. A kill -6 on the process produces a stack trace which is always the same except for the first goroutine. All the others appear to be waiting on one thing or another. Appears to go into a hard CPU loop based on Activity Manager (cpu ~ 100%) Memory also appears to start leaking. Lots of detail in a Spindump initiated from Activity Manager, but I do not know how to interpret it.

**Comment by mikhailshilkov** [comment]
With https://github.com/pulumi/pulumi/issues/4868 implemented, I'll go ahead and close this issue hoping that Rosetta translation isn't applicable anymore

**Comment by nchanged** [comment]
Still an issue, appears randomly:
Pulumi version : **v3.29.0**

```
 assertion failed [inst.has_value()]: failed to decode instruction: 0x0
    (StateRecovery.cpp:355 determine_state_recovery_action_forward_branches)
```

**Comment by DanHulton** [comment]
Still happening, randomly with no pattern I can detect.  Re-running the command sometimes fixes it, sometimes it takes multiple runs before it works again.

Pulumi version: v3.33.2
MacOS version: 12.4

```
assertion failed [inst.has_value()]: failed to decode instruction: 0x0
    (StateRecovery.cpp:355 determine_state_recovery_action_forward_branches)

  pulumi:providers:aws (default_5_6_0):
    error: could not read plugin [/Users/danhulton/.pulumi/plugins/resource-aws-v5.6.0/pulumi-resource-aws] stdout: EOF
```

**Comment by craig-pyrra** [comment]
Just chiming in that this happens constantly for me, seemingly more frequently lately. I'd guess about 2/3s of `pulumi up` attempts fail with this kind of error. Here's the output of `pulumi about`, in case that helps.

```
CLI
Version      3.42.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.10.0
docker      3.2.0
eks         0.41.2
kubernetes  3.20.0
nodejs      unknown
random      4.8.0

Host
OS       darwin
Version  12.5
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v18.4.0'

--- project data elided ---

Dependencies:
NAME                            VERSION
@pulumi/aws                     5.10.0
@pulumi/awsx                    0.40.0
@pulumi/eks                     0.41.2
@pulumi/pulumi                  3.36.0
@pulumi/random                  4.8.0
@twingate-labs/pulumi-twingate  0.0.22
@types/node                     14.18.22

Pulumi locates its logs in /var/folders/l1/n8m8xn9d62945txsq3n82kpc0000gn/T/ by default
```

**Comment by lhaskins** [comment]
This is still happening. `pulumi about` returns: (removing stack specific details)
```
CLI          
Version      3.81.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.11.0
aws-tags    0.4.1
command     0.8.2
local-exec  0.3.1
python      unknown
random      4.2.0
utils-py    0.5.6

Host     
OS       darwin
Version  12.3
Arch     x86_64

This project is written in python: executable='/usr/local/bin/python3' version='3.11.5
'

TYPE                                                 URN
pulumi:providers:aws                                 urn:pulumi:<STACK_INFO>::pulumi:providers:aws::default
pulumi:providers:aws                                 urn:pulumi:<STACK_INFO>::pulumi:providers:aws::default_5_11_0
pulumi:providers:random                              urn:pulumi:<STACK_INFO>::pulumi:providers:random::default_4_2_0
pulumi:providers:local-exec                          urn:pulumi:<STACK_INFO>::pulumi:providers:local-exec::default_0_3_1

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/<USER>
User           <USER>

Dependencies:
NAME               VERSION
pip                23.2.1
pulumi-local-exec  0.3.1
pulumi-utils-py    0.5.6
setuptools         56.0.0
```

The error happens in 2 forms:
```
Diagnostics:
  aws:rds:SubnetGroup (ameff-db-prod):
    error: error reading from server: EOF

  pulumi:pulumi:Stack (ameff-db-prod):
    assertion failed [inst.has_value()]: failed to decode instruction: 0x0
    (StateRecovery.cpp:355 determine_state_recovery_action_forward_branches)
```
and

```
Diagnostics:
  pulumi:providers:aws (default_5_11_0):
    error: could not read plugin [/path/to/.pulumi/plugins/resource-aws-v5.11.0/pulumi-resource-aws] stdout: EOF

  pulumi:pulumi:Stack (<STACK_NAME>):
    assertion failed [inst.has_value()]: failed to decode instruction: 0x0
    (StateRecovery.cpp:355 determine_state_recovery_action_forward_branches)
```

**Comment by craig-pyrra** [comment]
@lhaskins are you using the [ARM-native](https://github.com/pulumi/pulumi/issues/4868) version of Pulumi? If not, I recommend switching to it. Otherwise, the thing that worked for me under Rosetta was `GODEBUG=asyncpreemptoff=1 pulumi [...]` as mentioned [here](https://github.com/pulumi/pulumi/issues/5859#issuecomment-738526234)

Type `arch` in your terminal. If it says `i386` then you're using Rosetta.

**Comment by lhaskins** [comment]
@craig-pyrra You are correct! pulumi did think that my os was x86_64, but `arch` returns `arm64`. 

I ended up reinstalling homebrew and pulumi (and all of my other corresponding packages) and this fixed it. Thanks! I'm looking forward to not seeing these errors any longer 😄

**Comment by justinvp** [comment]
I'm closing this as fixed. We've been producing ARM native versions of the CLI and plugins for a while now. If you're running into Rosetta bugs on ARM macs, please use an ARM build of the CLI.
