### ISSUE TITLE
Bump dotnet Grpc dependency to 2.34.0

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi#5861]
There are some important fixes for dotnet/c# in [v1.34.0](https://github.com/grpc/grpc/releases/tag/v1.34.0) (NuGet [2.34.0](https://www.nuget.org/packages/Grpc.Core/2.34.0)), in particular for dotnet 5 and single file executables:
> C#
> * Fix C# native library loading in .NET 5 single-file apps (backport to v1.34.x). (#24853)
> * Make RIDs for the native dependencies in Grpc.Core arch specific. (#24766)
> * Improve PlatformApis check for detecting Unity. (#24714)
> * Fix to not require libc-dev on .NET 5 or later. (#24485)
> * C#: Make Grpc.Core nuget slimmer by moving mobile support to Grpc.Core.Xamarin package. (#24380)
> * C#: Stop supporting 32bit runtime for linux and macos . (#24378)
> * Modernize C# HelloworldXamarin example. (#24425)

**Comment by mikhailshilkov** [comment]
That's great to know! A PR would be welcome ;) (I believe it's just two lines in csproj)

**Comment by gitfool** [comment]
Incoming!

**Comment by gitfool** [comment]
@mikhailshilkov it would also be good to bump `Pulumi.Protobuf` to `Google.Protobuf` [v3.14.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.14.0).

**Comment by mikhailshilkov** [comment]
> be good

I think they can move independently. Are there exciting fixes in Protobuf too?

**Comment by gitfool** [comment]
Nothing exciting like the fix we're waiting for, but always good to keep up to date and there may be other beneficial side effects:
> C#
> * Annotate ByteString.CopyFrom(ReadOnlySpan) as SecuritySafeCritical (#7701)
> * Fix C# optional field reflection when there are regular fields too (#7705)
> * Fix parsing negative Int32Value that crosses segment boundary (#8035)
