### ISSUE TITLE
Missing property/attribute on preview

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#5864]
Users are reporting problems with missing attributes/properties such as https://github.com/pulumi/pulumi-aws/issues/1222 and https://github.com/pulumi/pulumi-aws/issues/1188. In particular, we thought we had fixed the issue that was primarily tracking this in https://github.com/pulumi/pulumi-azure/issues/192.

Given how this affects all providers, let's track this issue in `pulumi/pulumi`. Copied from the last comment in pulumi-azure#192 that describes the situation along with the workaround.

As an update on this issue:
- We closed this issue thinking https://github.com/pulumi/pulumi/issues/4992 addressed this issue. However, it only addresses the case for updates where the resource already exists (as pointed out above).
- The previously documented workaround (to use `apply(s => s || "default")`) should continue to work in the create case. In the case of updates, pulumi/pulumi#4992 should address the spurious diffs previously seen. If you're still seeing spurious diffs on preview, please post in this issue.
- Alternatively, you can disable provider preview by setting `PULUMI_DISABLE_PROVIDER_PREVIEW=true`
- We're investigating ways to improve the behavior for creates such that we can flow unknown values through.

_Originally posted by @leezen in https://github.com/pulumi/pulumi-azure/issues/192#issuecomment-730830636_

**Comment by leezen** [comment]
Also https://github.com/pulumi/pulumi-aws/issues/1239

**Comment by mikhailshilkov** [comment]
Also https://github.com/pulumi/pulumi-azure-nextgen/issues/115

**Comment by pgavlin** [comment]
Oddly enough, this appears to have been fixed and then regressed. With whatever version of the Azure provider was on my path when I looked at this today, the original issue does not repro, but with the current version of the provider, it does:

```
azure ❯ pulumi pre
Previewing update (dev):
     Type                             Name                  Plan       Info
 +   pulumi:pulumi:Stack              pulumi-azure-192-dev  create     1 warning
 +   ├─ azure:core:ResourceGroup      resourceGroup         create     
 +   ├─ azure:storage:Account         storage               create     
 +   ├─ azure:appservice:Plan         plan                  create     
 +   ├─ azure:appservice:FunctionApp  function              create     1 warning
 +   ├─ azure:keyvault:KeyVault       keyvault              create     
 +   └─ azure:keyvault:AccessPolicy   app                   create     
 
Diagnostics:
  azure:appservice:FunctionApp (function):
    warning: urn:pulumi:dev::pulumi-azure-192::azure:appservice/functionApp:FunctionApp::function verification warning: "storage_connection_string": [DEPRECATED] Deprecated in favor of `storage_account_name` and `storage_account_access_key`
 
  pulumi:pulumi:Stack (pulumi-azure-192-dev):
    warning: resource plugin azure is expected to have version >=3.33.2, but has 3.25.0-alpha.1602181969+93df8f93.dirty; the wrong version may be on your path, or this may be a bug in the plugin
 
azure ❯ rm `which pulumi-resource-azure`
azure ❯ pulumi pre                      
Previewing update (dev):
     Type                             Name                  Plan       Info
 +   pulumi:pulumi:Stack              pulumi-azure-192-dev  create     
 +   ├─ azure:core:ResourceGroup      resourceGroup         create     
 +   ├─ azure:storage:Account         storage               create     
 +   ├─ azure:appservice:Plan         plan                  create     
 +   ├─ azure:appservice:FunctionApp  function              create     1 warning
 +   ├─ azure:keyvault:KeyVault       keyvault              create     
     └─ azure:keyvault:AccessPolicy   app                              2 errors
 
Diagnostics:
  azure:appservice:FunctionApp (function):
    warning: urn:pulumi:dev::pulumi-azure-192::azure:appservice/functionApp:FunctionApp::function verification warning: "storage_connection_string": [DEPRECATED] Deprecated in favour of `storage_account_name` and `storage_account_access_key`
 
  azure:keyvault:AccessPolicy (app):
    error: azure:keyvault/accessPolicy:AccessPolicy resource 'app' has a problem: Missing required property 'tenantId'
    error: azure:keyvault/accessPolicy:AccessPolicy resource 'app' has a problem: Missing required property 'objectId'
 
azure ❯ 
```

Looking into this now.

**Comment by mikhailshilkov** [comment]
Yeah, this seems like a regression. I took a project that I last deployed in April, updated to all `latest`, and tried to deploy from scratch - to see a similar error at preview. The error is resolved if I create resources in portions. I'm quite sure the same code worked fine in April.

**Comment by mikhailshilkov** [comment]
My error is actually pretty bad and can be easily reproduced: run a `pulumi preview` on https://github.com/pulumi/examples/tree/master/aws-ts-apigateway

>      Type                                Name                          Plan       Info
> +   pulumi:pulumi:Stack                 aws-ts-apigateway-dev         create     
> +   ├─ aws:apigateway:x:API             hello-world                   create     
> +   │  ├─ aws:iam:Role                  hello-world4fcc7b60           create     
> +   │  ├─ aws:iam:RolePolicyAttachment  hello-world4fcc7b60-32be53a2  create     
> +   │  ├─ aws:lambda:Function           hello-world4fcc7b60           create     
> +   │  ├─ aws:apigateway:RestApi        hello-world                   create     
> +   │  └─ aws:apigateway:Deployment     hello-world                   create     
> +   ├─ aws:dynamodb:Table               counterTable                  create     
>     └─ aws:lambda:Permission            hello-world-86405973                     1 error
> 
>Diagnostics:
>  aws:lambda:Permission (hello-world-86405973):
>    error: aws:lambda/permission:Permission resource 'hello-world-86405973' has a problem: "function_name" doesn't >comply with restrictions ("^(arn:[\\w-]+:lambda:)?([a-z]{2}-(?:[a-z]+-){1,2}\\d{1}:)?(\\d{12}:)?(function:)?([a-zA-Z0-9-_]+)>(:(\\$LATEST|[a-zA-Z0-9-_]+))?$"): "urn:pulumi:dev::aws-ts-
>apigateway::aws:apigateway:x:API$aws:lambda/function:Function::hello-world4fcc7b60"

**Comment by lukehoban** [comment]
> error: aws:lambda/permission:Permission resource

Yes! I was just hitting this yesterday on a four line Pulumi program - and was trying to figure out how this could be broken to open a new issue.

```ts
import * as aws from "@pulumi/aws";
const bucket = new aws.s3.Bucket("mybucket");
bucket.onObjectCreated("foofunction", async (ev, ctx) => {
    console.log(JSON.stringify(ev));
});
```

**Comment by lukehoban** [comment]
For that program above - the error happens regardless of `@pulumi/aws` version, but only happens for `@pulumi/pulumi` >= `2.13.0` (published on 11/4/2020).

**Comment by lukehoban** [comment]
The last four messages appear to be related to a different (and newer) issue - tracking that in https://github.com/pulumi/pulumi/issues/5933.

**Comment by leezen** [comment]
Tracking the rollout to all providers here:

- [x] pulumi-aws
- [x] pulumi-azure
- [ ] pulumi-azuread
- [x] pulumi-gcp
- [x] pulumi-random
- [ ] pulumi-vsphere
- [ ] pulumi-openstack
- [ ] pulumi-f5bigip
- [ ] pulumi-packet
- [ ] pulumi-cloudflare
- [ ] pulumi-newrelic
- [ ] pulumi-linode
- [ ] pulumi-digitalocean
- [ ] pulumi-mysql
- [ ] pulumi-postgresql
- [ ] pulumi-gitlab
- [ ] pulumi-datadog
- [ ] pulumi-dnsimple
- [x] pulumi-tls
- [ ] pulumi-vault
- [ ] pulumi-kafka
- [ ] pulumi-consul
- [ ] pulumi-okta
- [ ] pulumi-signalfx
- [ ] pulumi-aiven
- [ ] pulumi-fastly
- [ ] pulumi-docker
- [ ] pulumi-rabbitmq
- [ ] pulumi-cloudamqp
- [ ] pulumi-spotinst
- [ ] pulumi-alicloud
- [ ] pulumi-rancher2
- [ ] pulumi-mailgun
- [ ] pulumi-keycloak
- [ ] pulumi-kong
- [ ] pulumi-github
- [ ] pulumi-mongodbatlas
- [ ] pulumi-auth0
- [ ] pulumi-pagerduty
- [ ] pulumi-azuredevops
- [ ] pulumi-ns1
- [ ] pulumi-hcloud
- [ ] pulumi-civo
- [ ] pulumi-wavefront
- [ ] pulumi-akamai
