### ISSUE TITLE
pulumi up --target wildcard urn support

### ISSUE THREAD

**Issue by xdays** [pulumi/pulumi#5870]
## Expected Behavior

Can pulumi support `pulumi up -t urn:pulumi:prod::beluga::beluga:aws:VPC::*`?

**Comment by shousper** [comment]
I would actually _love_ any level of more sophisticated query syntax for the `--target` flag 👍🏻

A `--target-children` flag would cover a bunch of my use cases (probably because of how I'm grouping resources) but globbing could be a little more useful.

**Comment by ppawiggers** [comment]
I'd also like to see this functionality. Targeting on URN works for a single resource, but not for a groups of resources (its children for example). Coming from Terraform this is a huge downside.

**Comment by RXminuS** [comment]
Same here, we have interdependencies between several stage class resources and so they are in the same stack. But we want to only be able to update one version of them even though a code change would be replicated across all of them

**Comment by shousper** [comment]
FWIW, the "workaround" we've been using is to keep projects small.

Each piece of software or infrastructure is deployed in isolation so multiple people can work on different units of our stack. Infrastructure is still all in a monorepo, while applications standalone.

We haven't ported our whole codebase to this model, but it works well for the things that are split up. Particularly when you just need to do something quick like allocate a deployment more resources, increase replicas, or add more nodes to an ASG. No need to wait 30 minutes for 100's of resources to validate.

**Comment by Sodki** [comment]
@iwahbe  Thank you for working, on this, but it seems that the wildcard doesn't glob `:`, which makes it's usage very limiting. Take this URN, for example:

```
urn:pulumi:dev::lytt::aws:docdb/cluster:Cluster::xyz
```
The following works:

```
$ pulumi up -t *:*:*::*::*:*cluster:*::*
```

But take any of the `:` from there and it doesn't work any more:

```
$ pulumi up -t *:*::*::*:*cluster:*::*
There were no resources matching the wildcards provided.
Wildcards can only be used to target resources that already exist.
$ pulumi up -t *cluster*
There were no resources matching the wildcards provided.
Wildcards can only be used to target resources that already exist.
```

Any thoughts on this?

**Comment by Frassle** [comment]
> but it seems that the wildcard doesn't glob `:`

Use a double wildcard **.
* will break at colons, ** will include them.

**Comment by shousper** [comment]
I've just run into this little snag with the `v3.24.1` CLI:

```
  aws:acm:CertificateValidation (cdn):
    error: Resource 'urn:pulumi:production::dabble-accounts::aws:acm/certificate:Certificate$aws:acm/certificateValidation:CertificateValidation::cdn' depends on 'urn:pulumi:production::dabble-accounts::aws:acm/certificate:Certificate::cdn' which was was not specified in --target list.
```

When trying to update like this:

```
pulumi --stack production up --target 'urn:pulumi:production::dabble-accounts::aws:acm/certificate:**' --target-dependents
```

Even though the `CertificateValidation` is a child of the `Certificate` (visible in the URN). I also tried `--target '**:acm/certificate:**' --target-dependents`, but no luck.

Is this intended?

**Comment by iwahbe** [comment]
@shousper did `urn:pulumi:production::dabble-accounts::aws:acm/certificate:Certificate::cdn` exist before you ran pulumi up. Currently wildcards only support resources that already exist. If it did exist, then I don't understand why `**:acm/certificate:**` didn't expand into `urn:pulumi:production::dabble-accounts::aws:acm/certificate:Certificate::cdn`. 

`--target-dependents` doesn't really enter into this. It adds all dependents of targeted resources to the target list. If the targeted resource depends on another resource, the update will still fail.

**Comment by shousper** [comment]
@iwahbe Ahh okay, yeah they're new resources. I didn't think of that, thanks!

**Comment by Sodki** [comment]
> Currently wildcards only support resources that already exist.

@iwahbe Out of curiosity, is this something you plan to implement in the future, being able to apply wildcards on new resources?

**Comment by iwahbe** [comment]
We are definitely open to implementing wildcard support for resources not yet created, but it's not on any roadmap I'm aware of. I'll create an issue to keep track.

**Comment by iwahbe** [comment]
https://github.com/pulumi/pulumi/issues/8956
