### ISSUE TITLE
Pulumi runs in JenkinsCI cannot report preview checks to gitbub PR

### ISSUE THREAD

**Issue by aylei** [pulumi/pulumi#5890]
## Expected Behavior

See `pulumi preview` results in github PR via pulumi github app.

## Current Behavior

No results are reported

## Steps to Reproduce

1. Run `pulumi preview` in JenkinsCI, which is sourced from a github PR
2. Check PR comments and PR checks

## Context (Environment)

This blocks us adopting pulumi in our IaC workflow, I suspect the issue is caused by the pulumi cli did not detects the `PR Number` from jenkins environments

**Comment by praneetloke** [comment]
@aylei thank you for taking the time to submit the issue. Looking at Jenkins' latest [docs](https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#using-environment-variables), I can say that we are already reading the environment info for [Jenkins](https://github.com/pulumi/pulumi/blob/master/sdk/go/common/util/ciutil/jenkins.go#L26) builds that is available out-of-box.

However, we do support a sort of [escape hatch](https://github.com/pulumi/pulumi/blob/master/sdk/go/common/util/ciutil/generic.go#L30) that lets you set the environment info yourself, if you have access to it. Specifically, for the GitHub App PR commenting feature, the important bit is the PR's HEAD SHA. Without the SHA in the Jenkins build environment, the Pulumi Service wouldn't be able to create the comment. Using the escape hatch, you could set this variable (as well as the other info) yourself as environment variables, _before_ the Pulumi step in your pipeline, using [`PULUMI_CI_PULL_REQUEST_SHA`](https://github.com/pulumi/pulumi/blob/master/sdk/go/common/util/ciutil/generic.go#L40). It's possible that with the use of the [GitHub plugin for Jenkins](https://github.com/jenkinsci/pipeline-github-plugin) you might get access to the variables you will need to set for Pulumi.

Read more about about the fallback for CI detection: https://www.pulumi.com/docs/guides/continuous-delivery/other/.

**Comment by praneetloke** [comment]
@aylei let me know if you have more questions based on my previous comment.

**Comment by mikhailshilkov** [comment]
I feel like the question has been answered and we haven't heard back, nor anybody else engaged in 1.5 years. I'll go ahead and close the issue.
