### ISSUE TITLE
pulumi logs don't show up

### ISSUE THREAD

**Issue by dnltinney** [pulumi/pulumi#5892]
I was trying out the [aws-ts-s3-lambda-copyzip example](https://github.com/pulumi/examples/tree/master/aws-ts-s3-lambda-copyzip#deploying-the-app) and wanted to see the logs when an object is uploaded to the s3 bucket, but logs don't show.

## Expected Behavior
logs are shown e.g.
```
$ pulumi logs -f
Collecting logs for stack dev since 2019-03-10T10:09:56.000-07:00...
2019-03-10T11:10:48.617-07:00[zipTpsReports] Zipping
    tpsreports-96458ef/tps001.txt into tpszips-edfde11/tps001.txt.zip
```

## Current Behavior
no logs are shown e.g.
```
Collecting logs for stack dev since 2020-12-08T14:47:44.000+01:00.

```

## Steps to Reproduce
copy code from [aws-ts-s3-lambda-copyzip example](https://github.com/pulumi/examples/tree/master/aws-ts-s3-lambda-copyzip#deploying-the-app) and follow steps

```
npm install
pulumi stack init
pulumi config set aws:region eu-central-1
pulumi up

pulumi logs -f   # start follow logs in seperate window

aws s3 cp ./myTpsReport001.txt s3://$(pulumi stack output tpsReportsBucket)
```

## Context (Environment)
```
$ sw_vers
ProductName:    macOS
ProductVersion: 11.0.1
BuildVersion:   20B50


$ pulumi version
v2.15.3

$ npm version
{
  npm: '7.0.14',
  node: '15.3.0',
  v8: '8.6.395.17-node.22',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.16.1',
  modules: '88',
  nghttp2: '1.41.0',
  napi: '7',
  llhttp: '2.1.3',
  openssl: '1.1.1g',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
```

**Comment by clstokes** [comment]
@dnltinney I believe you're hitting https://github.com/pulumi/pulumi/issues/1926 and this usually happens when you're not providing the necessary AWS credentials to `pulumi logs`. How are you setting your AWS access keys?

**Comment by dnltinney** [comment]
@clstokes setting credentials via `export AWS_PROFILE=PROFILE`
