### ISSUE TITLE
Error deleting Target Group: ResourceInUse: Target group is currently in use by a listener or a rule

### ISSUE THREAD

**Issue by Aeolun** [pulumi/pulumi#5900]
```
aws:alb:TargetGroup (stack-tg2):
    error: deleting urn:pulumi:dev::stack::aws:alb/targetGroup:TargetGroup::stack-tg2: 1 error occurred:
    	* Error deleting Target Group: ResourceInUse: Target group 'arn:aws:elasticloadbalancing:*:*:targetgroup/stack-tg2/fdcc6be49a381f35' is currently in use by a listener or a rule
    	status code: 400, request id: 15e6ebc6-8993-48cb-a041-2bbfc2702d39
```

## Expected Behavior
When I modify port definitions on a target group, first the listener should be removed, then the target group should be modified, and the listener re-added.

## Current Behavior
When I modify the port definitions on a target group, pulumi tries to replace the target group with a new one, but this doesn't work because there is still a listener that makes use of the target group.

## Steps to Reproduce
1. Create ALB with targetgroup/listener (to anywhere)
2. Modify the target group to cause it to be replaced.
3. Failure

## Context (Environment)
It's not the end of the world, but fairly annoying to have to manually delete the listeners, refresh the stack, then re-run update to make sure that the target groups can be replaced without issues.

**Comment by leezen** [comment]
By default, pulumi attempts to create before delete on replace. You can modify this behavior by specifying `deleteBeforeReplace` (https://www.pulumi.com/docs/intro/concepts/programming-model/#deletebeforereplace)

**Comment by ffMathy** [comment]
I am having the same issue. @leezen setting `DeleteBeforeReplace` to true does not work.

**Comment by ffMathy** [comment]
@Aeolun did you ever resolve the issue?

**Comment by Aeolun** [comment]
@ffMathy Not with Pulumi as I recall (just manually). But I haven’t needed to modify the ports again either. It may be fixed in a new version, or it may not.

**Comment by ffMathy** [comment]
Alright. Then I think someone (@leezen) should reopen?

**Comment by emiliza** [comment]
@ffMathy does https://github.com/pulumi/pulumi/issues/2625 address your issue?

**Comment by pgavlin** [comment]
> I am having the same issue. @leezen setting DeleteBeforeReplace to true does not work.

Just to clarify--is the `DeleteBeforeReplace` setting not respected at all (i.e. `pulumi` still attempts to create a new target group prior to deleting the original), or is it respected but does not solve the issue?

@Aeolun would it be possible for you to share a code snippet that demonstrates how the ALB, target group, and listeners are declared?

**Comment by ffMathy** [comment]
It is respected for me, but doesn't help. I can't share code because it's under NDA.

**Comment by ffMathy** [comment]
To be honest though, I think it happens always.

**Comment by Aeolun** [comment]
@pgavlin I'll see if I can pull out a representative example. Sorry, didn't see this comment before.

**Comment by richmeij** [comment]
@pgavlin Can confirm that this still occurs. But I'm pretty new to Pulumi, so it might have to do with my setup.

I have a targetgroup with 3 instances attached to it. The ALB only has 1 listener on port 80.

Here's my code for the ALB: 
```ts
export const albSg = new aws.ec2.SecurityGroup("dev-alb-sg", {
  vpcId: vpc.id,
  ingress: [
    {
      fromPort: 80,
      toPort: 80,
      protocol: aws.ec2.ProtocolType.TCP,
      cidrBlocks: ["0.0.0.0/0"],
    },
  ],
  egress: [
    {
      fromPort: 0,
      toPort: 0,
      protocol: aws.ec2.ProtocolType.All,
      cidrBlocks: ["0.0.0.0/0"],
    },
  ],
  tags: {
    Name: "dev-alb-sg",
  },
});

export const alb = new aws.alb.LoadBalancer("dev-alb", {
  loadBalancerType: aws.alb.LoadBalancerType.Application,
  internal: false,
  subnets: subnets.then((subnets) => subnets.map((subnet) => subnet.id)),
  securityGroups: [albSg.id],
  name: "dev-alb",
});

export const albTg = new aws.alb.TargetGroup("dev-alb-tg", {
  name: "dev-alb-tg",
  vpcId: vpc.id,
  targetType: "instance",
  protocol: "HTTP",
  port: 80,
});

export const albListener = new aws.alb.Listener("dev-http-listener", {
  loadBalancerArn: alb.arn,
  port: 80,
  protocol: "HTTP",
  defaultActions: [
    {
      type: "forward",
      targetGroupArn: albTg.arn,
    },
  ],
});
```

When I change the name of my targetgroup, the output is:
```
     Type                              Name               Plan        Info
     pulumi:pulumi:Stack               dev
 +-  ├─ aws:alb:TargetGroupAttachment  alb-tg-instance-1  replace     [diff: ~targetGroupArn]
 +-  ├─ aws:alb:TargetGroupAttachment  alb-tg-instance-0  replace     [diff: ~targetGroupArn]
 +-  ├─ aws:alb:TargetGroupAttachment  alb-tg-instance-2  replace     [diff: ~targetGroupArn]
 +-  ├─ aws:alb:TargetGroup            dev-alb-tg         replace     [diff: ~name]
 ~   └─ aws:alb:Listener               dev-http-listener  update      [diff: ~defaultActions]

Resources:
    ~ 1 to update
    +-4 to replace
    5 changes. 13 unchanged

Do you want to perform this update? yes
Updating (dev)

View Live: xxx

     Type                              Name               Status                   Info
     pulumi:pulumi:Stack               dev   **failed**               1 error
 +-  ├─ aws:alb:TargetGroupAttachment  alb-tg-instance-1  replaced
 +-  ├─ aws:alb:TargetGroupAttachment  alb-tg-instance-0  replaced
 +-  ├─ aws:alb:TargetGroupAttachment  alb-tg-instance-2  replaced
 +-  └─ aws:alb:TargetGroup            dev-alb-tg         **replacing failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (dev):
    error: update failed

  aws:alb:TargetGroup (dev-alb-tg):
    error: deleting urn:pulumi:dev::projetcname::aws:alb/targetGroup:TargetGroup::dev-alb-tg: 1 error occurred:
        * error deleting Target Group: ResourceInUse: Target group 'arn:aws:elasticloadbalancing:eu-central-1:0000:targetgroup/dev-alb-tg-1e2a297/a0154c3075c17b7c' is currently in use by a listener or a rule
        status code: 400, request id: bbc2d4b6-e653-4695-bb9f-7b2a1b82d0f5
```

**Comment by richmeij** [comment]
@leezen @emiliza Maybe this issue should be reopened?

**Comment by richmeij** [comment]
@leezen @emiliza Can any of you comment on this? Were there any changes in the meantime that may help to resolve this issue?

**Comment by mikhailshilkov** [comment]
@richmeij Playing this in my head, it sounds like a correct sequence would be

1. Delete Listener
2. Delete TargetGroup
3. Create TargetGroup
4. Create Listener

I guess what is missing is that Listener is an update not a replacement. Could you try adding [replaceOnChanges](https://www.pulumi.com/docs/intro/concepts/resources/options/replaceonchanges/) to your Listener options to make it a replacement when `targetGroupArn` changes?

By the way, your code doesn't have `TargetGroupAttachment` resources.

>  the targetgroup attachments are now gone in AWS, but Pulumi doesnt think so.

Does `pulumi refresh` help?

**Comment by richmeij** [comment]
Hi @mikhailshilkov, thanks for replying.

> @richmeij Playing this in my head, it sounds like a correct sequence would be
> 
> 1. Delete Listener
> 2. Delete TargetGroup
> 3. Create TargetGroup
> 4. Create Listener

Sounds correct to me.

> I guess what is missing is that Listener is an update not a replacement. Could you try adding [replaceOnChanges](https://www.pulumi.com/docs/intro/concepts/resources/options/replaceonchanges/) to your Listener options to make it a replacement when `targetGroupArn` changes?

Thanks for the tip, I will give this a go.

> By the way, your code doesn't have `TargetGroupAttachment` resources.
> 
> > the targetgroup attachments are now gone in AWS, but Pulumi doesnt think so.
> 
> Does `pulumi refresh` help?

Yeah sorry, the code posted hier was just the alb/tg part. There is an ec2 part where instances are created and added to the targetgroup. You can verify their existance in the pulumi output. The point was that Pulumi now thinks they are "replaced", but when I look in AWS no instances are attached to the (not replaced) targetgroup. The consequence is that my instances are no longer reachable through the ALB.

**Comment by richmeij** [comment]
@mikhailshilkov Adding `{ replaceOnChanges: ["targetGroupArn"] }` seemed to work for me. Thanks! 🙏

**Comment by Aeolun** [comment]
@mikhailshilkov Adding `replaceOnChanges` does not work for me. The problem is that Pulumi tries to delete the TargetGroup before deleting the Listener.

**Comment by Romany-Saad** [comment]
The only solution I could find was to create a different TargetGroup each time.

get a random name for your target group, and make sure its length is 32 chars or less.
```ts
const random = ''.padEnd(10, Math.floor(Math.random() * 1000000).toString()) // or whatever way
const targetGroupName = `some-name-${random}-target-group`
```
then
```ts
const targetGroup = new lb.TargetGroup(
  targetGroupName,
  {
    name: targetGroupName,
    ...
  },
  {
    // exclude the name from calculating the changes
    // this avoids creating a resource on each run, but only if other property that name has changed.
    ignoreChanges: ['name'],
    ...
  }
)
```

this way pulumi will create a new component each time you change anything other than the name with different name, then pass that to the listener rule (which depends on a new resource and has to wait for it to be ready then refer to it).

This is just a workaround to not stop your automation tools, but not an ideal solution because I found that the old TargetGroup will not be cleaned automatically by Pulumi for some reason, which you will need clean manually whenever you like.

**Comment by deepakkt** [comment]
In addition to the above, I added a dependsOn constraint on the listener rule

```golang
		}, pulumi.DependsOn([]pulumi.Resource{targetGrp}),
			pulumi.ReplaceOnChanges([]string{"targetGroupArn"}),
			pulumi.DeleteBeforeReplace(true))
```

the target group is still being deleted ahead of the listener rule despite forcing the dependency.

**Comment by arjun810** [comment]
Is there a reliable workaround here yet?

**Comment by jaxxstorm** [comment]
For those that come across this issue.

It's really important to note that if you add a resource property, like a `dependsOn` or a `deleteBeforeReplace`, you _need_ to run a successful `up` operation before you make changes to the resources that trigger a replacement.

Let's take this example code, which has a hard coded name in the targetGroup and listener:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const vpc = new awsx.ec2.Vpc("example");

const sg = new aws.ec2.SecurityGroup("example", {
  ingress: [
    {
      protocol: "tcp",
      fromPort: 80,
      toPort: 80,
    },
  ],
  vpcId: vpc.vpcId,
});

const alb = new aws.alb.LoadBalancer("example", {
  name: "example-repro",
  loadBalancerType: aws.alb.LoadBalancerType.Application,
  internal: false,
  subnets: vpc.publicSubnetIds,
  securityGroups: [sg.id],
});

const targetGroup = new aws.alb.TargetGroup("example", {
  name: "example-repro",
  vpcId: vpc.vpcId,
  targetType: "instance",
  protocol: "HTTP",
  port: 443,
});

const albListener = new aws.alb.Listener("example", {
  loadBalancerArn: alb.arn,
  port: 80,
  protocol: "HTTP",
  defaultActions: [
    {
      type: "forward",
      targetGroupArn: targetGroup.arn,
    },
  ],
});
```

Now, as has been pointed out earlier in this issue, if you modify the `port` property of the listener or targetGroup, you'll trigger a resource conflict.

What most people do at this stage is find this issue, then add the resource property _after_ that have _also_ changed the port, like so:

```typescript
  const targetGroup = new aws.alb.TargetGroup("example", {
  name: "example-repro",
  vpcId: vpc.vpcId,
  targetType: "instance",
  protocol: "HTTP",
  port: 443, // port has changed
}, {
    deleteBeforeReplace: true, // I've also added this resource property
});
```

This *will not work*. The reason for this is that Pulumi is now trying to add a resource option, while _also_ still replacing the resource.

The correct thing to do is:

modify the resource options without actually modify the resource and run a successful `pulumi up`:

```typescript
const targetGroup = new aws.alb.TargetGroup("example", {
  name: "example-repro",
  vpcId: vpc.vpcId,
  targetType: "instance",
  protocol: "HTTP",
  port: 80,
}, {
    deleteBeforeReplace: true, // adding this
});
```

*Now* I can change the port in the next operation.

```typescript
const targetGroup = new aws.alb.TargetGroup("example", {
  name: "example-repro",
  vpcId: vpc.vpcId,
  targetType: "instance",
  protocol: "HTTP",
  port: 443,
}, {
    deleteBeforeReplace: true, // adding this
});
```

This requirement applies to _all_ resource properties, including `replaceOnChanges` and anything else needed to get this particular resource working correctly.

**Comment by cobrastarfunkel** [comment]
[jaxxstorm](https://github.com/jaxxstorm) response worked for me (Also using replaceOnChanges) until I made changes to the target groups and target group attachments as well as the listeners all at the same time

Now Pulumi intends to remove the Listeners but apparently only after the target groups which of course fails because they're in use by the Listeners

So we can't reliably make changes to ELBs?

**Comment by Aeolun** [comment]
I think what we need here is some `blocksChangesIn` property that allow us to specify the `aws.alb.TargetGroup` in the listener, which will then make Pulumi first delete any resources that block changes in another one, then re-create them afterwards.

`dependsOn` is doing the exact opposite, but we need the reverse.

**Comment by flostadler** [comment]
Hey folks, sorry you're running into this issue!

You're right @Aeolun, it would be great if we had a way to specify those kind of replacement dependencies! We're tracking support for this here: https://github.com/pulumi/pulumi/issues/14072. 

One possible workaround right now is setting a `namePrefix` instead of a fixed `name` for the target group. That way pulumi can create a replacement for the target group before updating the listener and then ultimately deleting the old target group. This way you can also change the listener and the target group at the same time.

<details>
  <summary>Example</summary>

  ```ts
  import * as pulumi from "@pulumi/pulumi";
  import * as aws from "@pulumi/aws";
  import * as awsx from "@pulumi/awsx";

  const vpc = new awsx.ec2.Vpc("example");

  const sg = new aws.ec2.SecurityGroup("example", {
    ingress: [
      {
        protocol: "tcp",
        fromPort: 80,
        toPort: 80,
      },
    ],
    vpcId: vpc.vpcId,
  });

  const alb = new aws.alb.LoadBalancer("example", {
    name: "example-repro",
    loadBalancerType: aws.alb.LoadBalancerType.Application,
    internal: false,
    subnets: vpc.publicSubnetIds,
    securityGroups: [sg.id],
  });

  const targetGroup = new aws.alb.TargetGroup("example", {
    namePrefix: "repro-",
    vpcId: vpc.vpcId,
    targetType: "instance",
    protocol: "HTTP",
    port: 443,
  });

  const albListener = new aws.alb.Listener("example", {
    loadBalancerArn: alb.arn,
    port: 80,
    protocol: "HTTP",
    defaultActions: [
      {
        type: "forward",
        targetGroupArn: targetGroup.arn,
      },
    ],
  });
  ```
</details>
