### ISSUE TITLE
Validation error when importing Azure AppServicePlan using pulumi import command

### ISSUE THREAD

**Issue by OlegKarasik** [pulumi/pulumi#5901]
Unable to import Azure App Service Plan (with cloud login) using the following command:

```
pulumi import azure:appservice/plan:Plan <name> /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<resourceGroup>/providers/Microsoft.Web/serverFarms/<name>
```

## Expected Behavior
Azure App Service Plan is imported.

## Current Behavior
The call returns an error:

```
error: Preview failed: importing /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<resourceGroup>/providers/Microsoft.Web/serverFarms/<name>: Error parsing Resource ID "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<resourceGroup>/providers/Microsoft.Web/serverFarms/<name>": ID was missing the `serverfarms` element
```

If we replace `serverFarms` id segment with `serverfarms`, then everything works as expected.

## Steps to Reproduce
1. Execute command `pulumi import azure:appservice/plan:Plan <name> /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<resourceGroup>/providers/Microsoft.Web/serverFarms/<name>`

## Context (Environment)
1. Pulumi CLI v 2.15.4
2. Cloud login.

**Comment by leezen** [comment]
I'm a bit confused by the expectation here. The import path for the resource really is `serverfarms` and the documentation shows as such: https://www.pulumi.com/docs/reference/pkg/azure/appservice/plan/#import

**Comment by OlegKarasik** [comment]
Hi @leezen,

You are absolutely correct that pulumi documentation addresses app service plan as `serverfarms`. However, Azure addresses app service plan as `serverFarms`. 

You can verify it by looking at URL:
`https://portal.azure.com/#@<tenant>/resource/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<resourceGroup>/providers/Microsoft.Web/serverFarms/<name>`

or `Resource ID` on properties tab:
`/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<resourceGroup>/providers/Microsoft.Web/serverFarms/<name>`

I raised the issue because as a user I expect to be able to copy-paste resource identifier from Azure without a need to parse and reconstruct it manually using pulumi documentation. 

If such workflow isn't expected then there is no issue and you can close it :)

**Comment by leezen** [comment]
@OlegKarasik Thanks for clarifying. I think this is a case where Microsoft is a bit inconsistent in how it is naming things. While the URL may use `serverFarms`, the provider follows the ARM API where it is all lowercase. (See also https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2020-09-01/AppServicePlans.json in their official spec and the [relevant documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/serverfarms)). I'm not actually sure where the camelcase version comes from, but you may want to file an issue against the https://github.com/Azure/azure-rest-api-specs repo to try to see if there's any way to rectify the inconsistency.

**Comment by OlegKarasik** [comment]
Thank you. 

I have created an [issue](https://github.com/Azure/azure-rest-api-specs/issues/12072) as you have proposed.
