### ISSUE TITLE
Validation error when importing Azure Resource Group using pulumi import

### ISSUE THREAD

**Issue by OlegKarasik** [pulumi/pulumi#5902]
Executing of `pulumi import azure:core/resourceGroup:ResourceGroup <name> /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<name>` command returns an error.

## Expected Behavior
The command imports resource group.

## Current Behavior
The command fails with the following error:

```
error: preview failed

azure:core:ResourceGroup (practice7):
  error: azure:core/resourceGroup:ResourceGroup resource '<name>' has a problem: Missing required property 'location'. Either set it explicitly or configure it with 'pulumi config set azure:location <value>'.      
  error: Preview failed: one or more inputs failed to validate
```

It is important to note that setting `pulumi config set azure:location <value>` doesn't affect current command behavior.

## Steps to Reproduce
1. Execute `pulumi import azure:core/resourceGroup:ResourceGroup <name> /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/<name>`

## Context (Environment)
Pulumi CLI 2.15.4
Cloud Login

**Comment by leezen** [comment]
I'm not able to reproduce this. After ensuring I have run `pulumi config set azure:location <value>` (WestUS in my case), the import preview succeeds (as does the actual import).

**Comment by OlegKarasik** [comment]
Hi @leezen,

I am not sure what did change but today I am unable to reproduce the issue too (I didn't change anything. I just repeated the command which was previously failing).

I am closing this.
