### ISSUE TITLE
python 3.9 and pulumi have some issues with protobuf

### ISSUE THREAD

**Issue by MattBlack85** [pulumi/pulumi#5904]
Today my OS bumped python to 3.9, I changed my Pipfile, reinstalled the dependencies and I can't run pulumi anymore, I got the following error:
```
ImportError while loading conftest '/home/matt/data/repos/cyclope/tests/conftest.py'.
tests/conftest.py:4: in <module>
    import pulumi
../../../.local/share/virtualenvs/cyclope-mw2Vtk-i/lib/python3.9/site-packages/pulumi/__init__.py:24: in <module>
    from .asset import (
../../../.local/share/virtualenvs/cyclope-mw2Vtk-i/lib/python3.9/site-packages/pulumi/asset.py:21: in <module>
    from .runtime import known_types
../../../.local/share/virtualenvs/cyclope-mw2Vtk-i/lib/python3.9/site-packages/pulumi/runtime/__init__.py:44: in <module>
    from .invoke import (
../../../.local/share/virtualenvs/cyclope-mw2Vtk-i/lib/python3.9/site-packages/pulumi/runtime/invoke.py:40: in <module>
    from google.protobuf.pyext._message import SetAllowOversizeProtos  # pylint: disable-msg=E0611
E   ModuleNotFoundError: No module named 'google.protobuf.pyext._message'
```
The actual packages versions:
 - pulumi==2.6.0
 - pulumi-aws==2.13.1
 - grpcio==1.34.0
 - protobuf==3.14.0

The exact same set of dependencies work against python 3.8

## Expected Behavior
Running any pulumi command (or importing pulumi in the code) shouldn't lead to any error

## Current Behavior
A missing module is causing pulumi to crash

## Steps to Reproduce
1. run pulumi up
2. import pulumi in any module

## Context (Environment)
After re-installing the deps I went straight with a `pulumi up` and I wasn't able to run any update, running the test suite causes the same problem the first time we import pulumi

**Comment by lukehoban** [comment]
This looks like the same issue that was tracked in https://github.com/pulumi/pulumi/issues/3981 and then fixed as part of adding Python 3.9 support in https://github.com/pulumi/pulumi/issues/5662. 

I expect you need to update your `pulumi` and possibly `pulumi-aws` versions to a newer version since support for Python 3.9 was added.

**Comment by MattBlack85** [comment]
we have some big issues with unit testing and mocks and that's why we are still locked to such an ancient version, something changed after 2.6.0 and we are slowly refactoring them. Thanks for letting me know @lukehoban

**Comment by lukehoban** [comment]
Got it - that makes sense.  I expect you'll need to stick with Python 3.8 until you've been able to adopt Pulumi >= 2.13.0, as Python 3.9 broke some gRPC functionality that we had to pick up a fix for.
