### ISSUE TITLE
Remove hardcoded knowledge of serialized-functions from plan.go diffing code.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi#592]
As part of https://github.com/pulumi/pulumi/pull/591 we hardcode in some knowledge of what serialized functions look like, so we can adjust the text for a better diffing experience.

It would be better if this was not in this part of the codebase.  instead, ideally, the resource could specify what the 'massaged text' was that it wanted the plan code to work with.

**Comment by lukehoban** [comment]
Closing this out - we'll fix this if/when it causes problems in the future.

**Comment by joeduffy** [comment]
Don't we still have this hard coded knowledge in the core Go engine?

**Comment by lukehoban** [comment]
This has been open for more than 2 years and we haven't heard any feedback on it.  Closing it until we get feedback.
