### ISSUE TITLE
Consider a --preview-code option for `import`

### ISSUE THREAD

**Issue by haacked** [pulumi/pulumi#5934]
I'd like to use existing resources I have in Azure as a template for creating new resources in Pulumi. Right now, what I do is:

1. `import {resource}`
2. Perform the import.
3. Copy the outputted source code into my Pulumi program, but change the details I want to change.
4. `pulumi state delete {resource}`

The reason I do this is that the preview for import doesn't show the source code that will be generated. Let me know if there's already a better approach to what I'm trying to do.

The main reason I'm trying this is I've created a bunch of resources in Azure manually. I don't yet have a mental model of how to recreate those resources in Pulumi.

**Comment by mikhailshilkov** [comment]
This is very close to #8836 so we'll use that issue to track this improvement
