### ISSUE TITLE
Preview fails when resource refs are enabled

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#5939]
From https://github.com/pulumi/pulumi/issues/5933:

Previews fail in very incorrect ways with CLI `2.15.5`.

```ts
import * as aws from "@pulumi/aws";
const bucket = new aws.s3.Bucket("mybucket");
bucket.onObjectCreated("foofunction", async (ev, ctx) => {
    console.log(JSON.stringify(ev));
});
```

```
$ pulumi preview
...
Diagnostics:
  aws:lambda:Permission (foofunction):
    error: aws:lambda/permission:Permission resource 'foofunction' has a problem: "function_name" doesn't comply with restrictions ("^(arn:[\\w-]+:lambda:)?([a-z]{2}-(?:[a-z]+-){1,2}\\d{1}:)?(\\d{12}:)?(function:)?([a-zA-Z0-9-_]+)(:(\\$LATEST|[a-zA-Z0-9-_]+))?$"): "urn:pulumi:dev::promisecapture::aws:s3/bucket:Bucket$aws:s3:BucketEventSubscription$aws:lambda/function:Function::foofunction"
```

This happens when resource refs are enabled.

**Comment by justinvp** [comment]
The problem is how we marshal resource references when we're not keeping resources:

https://github.com/pulumi/pulumi/blob/cae129c7fa73df2c88115aae71071c7e040e9802/sdk/go/common/resource/plugin/rpc.go#L166-L174

If we see the ID is an empty string, we return the URN, which isn't taking into account that the ID may be unknown.

If the ID is unknown (`ref.HasID == true && ref.ID == ""`) we should return the ID as an unknown string, instead of returning the URN.

**Comment by leezen** [comment]
I'm not sure that this is actually fixed. With pulumi 2.17.0 and enabling via `PULUMI_ENABLE_RESOURCE_REFERENCES=1` I still see the same error.
