### ISSUE TITLE
Support resource references via a feature flag

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#5942]
Enable the feature based on the `PULUMI_EXPERIMENTAL_RESOURCE_REFERENCES` flag

Related: https://github.com/pulumi/pulumi/pull/5905 and https://github.com/pulumi/pulumi/pull/5932

**Comment by lblackstone** [comment]
#5960 added the `PULUMI_ENABLE_RESOURCE_REFERENCES` flag, which accomplishes the same goal. Closing this out now
