### ISSUE TITLE
Document scenarios and create test coverage for resource references

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#5943]
Resource references introduces a number of changes that affects the engine's behavior. We need to document what the various scenarios are that it affects and add test coverage for those scenarios.

**Comment by pgavlin** [comment]
Here's an initial cut:

## Resource Scenarios

1. Custom resources with known IDs
2. Custom resources with unknown IDs
3. Component resources

Tests for all of these can be easily written. We should ensure that each SDK and the CLI
covers marshalling and unmarshaling a resource reference that fits each scenario.

## Marshaling Boundaries

1. SDK <-> CLI
2. CLI <-> Statefile
3. CLI <-> Resource Providers
4. Statefile <-> Pulumi Console

- SDK <-> CLI and CLI <-> Resource Providers are runtime compatibility boundaries
	- Downlevel SDK/Resource Provider <-> Current CLI
	- Downlevel CLI with current SDK/Resource Provider
	- Support for resource references must be negotiated
	- It is the responsibility of the entity that does support resource references to
      declare its support and to respect the absence of support in other entities
		- For example, a CLI that does support resource references must serialize them as
          URNs (for references to component resources) or IDs (for references to custom
          resources) when communicating with an SDK or resource provider that does not
          support resource references.
	- We should be able to emulate these scenarios in unit tests (i.e. in `pkg/engine/lifecycletest/pulumi_tests`)
		- We can emulate a downlevel CLI by selectively disabling support for resource
          references in the resource monitor
		- We can emulate a downlevel SDK by selectively disabling support for resource
		  references in the test harness
		- We can emulate a downlevel resource provider by selectively disabling support
		  for resource references in the test harness
	- We may also be able to emulate these scenarios in integration tests, though doing so
      in a way that persists once the feature is enabled by default involves configuration
      knobs (e.g. envvars) that selectively disable support for resource refs in *only* the
      SDK or *only* the engine. We may not want those knobs long-term.
	- We may be also able to emulate these scenarios in SDK unit tests. If we cannot, we
	  should strongly consider enabling this emulation s.t. we can validate the behavior
	  in a more fine-grained fashion.
	- The examples test passes do construct the SDK <-> CLI scenarios, but will cease to
	  do so once both the latest release and the dev build support resource references
- CLI <-> Statefile and Statefile <-> Pulumi Console are static compatibility boundaries
	- Downlevel CLI <-> current statefile
	- Downlevel Console <-> current statefile
	- We have a mechanism to indicate the version of a statefile, which implies the set of
	  features that may be present within the statefile
	- We have not discussed whether or not to bump the version for resource refs
	- Bumping the version would allow the CLI and console to fail more gracefully when
	  presented with a statefile that contains resource references.
