### ISSUE TITLE
OCI: Oracle Cloud Infrastructure

### ISSUE THREAD

**Issue by julianobarbosa** [pulumi/pulumi#5948]
Is there any plan to support [Oracle Cloud Infrastructure](https://www.oracle.com) ?

**Comment by stack72** [comment]
From the linked issue:

"This tool lacks support for the officially GOATed IaaS provider: Oracle Cloud Infrastructure. Oracle cloud is twice as cheap and twice as performant as AWS for most workloads; in some cases, like bandwidth heavy products, the difference is 10x. This is the only defining factor for kubernetes cloud installations; the entire point of container orchestration systems is to abstract the other details, and oracle has full support for all the important Kubernetes primitives. There are issues with plugin support, but those are inconsiderable compared to the cost savings, provided you are actually good at systems administration and are not afraid of mildly inconvenient technical problems.

Only brainwashed technology professionals constantly grasping for the newest most hip toys, spooked instantly by the brand name (that being their only way to evaluate different products), even consider using the outmoded alternatives. By not supporting this god-tier offering Pulumi is probably inducing losses of up to a million+ a year simply by encouraging startups to begin elsewhere."

**Comment by deosha** [comment]
@leezen Let me know if you are open to contributions on this issue?

**Comment by stack72** [comment]
Hi @deosha 

We are definitely open to contributions in this area - we have https://github.com/pulumi/pulumi-tf-provider-boilerplate that can be used to scaffold the related Terraform provider as well

Let me know if you are interested in this and we can put you in the right direction to get started

Paul

**Comment by pellizzetti** [comment]
Hey @deosha @stack72! 👋🏻

If no one is actively working on this, I would like to give it a try.

@stack72 The boilerplate seems pretty straightforward to me, still, I have some questions:

- Do you guys have some checklist/guidelines/action plan that one should follow when creating a provider?
- When mapping the resources in the Terraform provider to Pulumi, should I map all in one go or just the ones I plan to use and the community can chime in with the rest over time?

**Comment by dirien** [comment]
hi @stack72  and @pellizzetti,

i created a oci-provider and i would like to get some feedback. 

--> https://github.com/dirien/pulumi-oci

**Comment by dirien** [comment]
@stack72, should i create a separate Issue for this, or is there a way i transfer the repo to the Pulumi Repository?

**Comment by colemickens** [comment]
Is there maybe more information coming soon here or...?

**Comment by dirien** [comment]
AFAIK, @stack72 needs to fit the code into the toolchain of Pulumi. Maybe he has an update?

**Comment by EladGabay** [comment]
@stack72 Hey, any update? :)

**Comment by EladGabay** [comment]
https://github.com/EladGabay/pulumi-oci
An updated version of @dirien s repo.

**Comment by dirien** [comment]
> https://github.com/EladGabay/pulumi-oci An updated version of @dirien s repo.

Love it! GG!

**Comment by EladGabay** [comment]
I moved it to "pulumi-oci" org, also added a new release.
https://github.com/pulumi-oci/pulumi-oci
Hope it will be adopted soon by official pulumi.

**Comment by dirien** [comment]
Great! I dont knw what happend with the other repo?! :( @stack72?

**Comment by pasmon** [comment]
The pulumi-oci or pulumi_oci package doesn't seem to be available in PyPI?

**Comment by scratchmex** [comment]
@stack72 @EladGabay bumping this as the repo seems updated. How is the process of adding this to the supported providers?

**Comment by kaizendae** [comment]
Are there any news regarding adding official support for oracle cloud infrastructure ?

**Comment by stack72** [comment]
Hi folks,

We are currently working on this

Paul

**Comment by stack72** [comment]
Hi folks

Happy to say that I can close this out:

https://github.com/pulumi/pulumi-oci
https://www.nuget.org/packages/Pulumi.Oci
https://pypi.org/project/pulumi-oci/
https://www.npmjs.com/package/@pulumi/oci

Please raise any issues in that repository :)

Paul

**Comment by dirien** [comment]
Great @stack72! I will give it a spin!

**Comment by stack72** [comment]
Thanks @dirien !! Get in contact if there are issues :)
