### ISSUE TITLE
TypeError: pulumi.runtime.registerResourceModule is not a function

### ISSUE THREAD

**Issue by aaronhayes** [pulumi/pulumi#5955]
I've just updated to version `2.15.6` from `2.15.0` of pulumi and started seeing this issue when previewing deployments.

`TypeError: pulumi.runtime.registerResourceModule is not a function`

Full Output:

```
    error: Running program '/infra' failed with an unhandled exception:
    TypeError: pulumi.runtime.registerResourceModule is not a function
        at Object.<anonymous> (/infra/node_modules/@pulumi/index.ts:49:16)
        at Module._compile (node:internal/modules/cjs/loader:1102:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
        at Module.load (node:internal/modules/cjs/loader:967:32)
        at Function.Module._load (node:internal/modules/cjs/loader:807:14)
        at Module.require (node:internal/modules/cjs/loader:991:19)
        at require (node:internal/modules/cjs/helpers:92:18)
        at Object.<anonymous> (/infra/config/postgresql.ts:3:1)
        at Module._compile (node:internal/modules/cjs/loader:1102:14)
        at Module.m._compile (//infra/node_modules/ts-node/src/index.ts:439:23)
```

## Expected Behavior

Preview / Up commands work prroperly. 

## Current Behavior

Error during previews 

`TypeError: pulumi.runtime.registerResourceModule is not a function`

## Steps to Reproduce

1. 
2.
3.
4.

## Context (Environment)

MAC OS - Big Sur.

Pulumi 2.15.6

**Comment by estyrke** [comment]
I also have this after upgrading the npm package yesterday. I thought it was the major upgrade of @pulumi/aws from 2.11.0 to 3.20.0, but I also had an upgrade of @pulumi/pulumi from 2.5.0 to 2.15.6. The error seems to be triggered by an import of @pulumi/random (which is at 2.4.4, up from 2.1.3 - will try backing down again).

**Comment by leezen** [comment]
@pgavlin @justinvp Looking at the codegen changes made to the modules in https://github.com/pulumi/pulumi/pull/5839, I think for NodeJS specifically, we need to bump the version of `@pulumi/pulumi` in `package.json` across all providers for this change to be safe. I'm actually not sure how the cases above are happening as 2.15.6 has the resource registration bits in it.

@estyrke @aaronhayes one possibility to check is if there are packages that are bringing in older versions of `@pulumi/pulumi` somehow?

**Comment by estyrke** [comment]
@leezen Yes, it seems like @pulumi/random brings in @pulumi/pulumi@2.5.0 (in both versions I have tried).

Furthermore, downgrading @pulumi/random back to 2.1.3 seems to solve the issue for me, but I'm not really sure what yarn does under the hood, so it still might be something else I guess.

**Comment by leezen** [comment]
@estyrke I would not expect it to bring in `2.5.0` as `package.json` in `@pulumi/random` has:

```
"dependencies": {
        "@pulumi/pulumi": "^2.0.0"
    },
```

So it should transitively attempt to bring in the latest version. You may want to check out your `package.json` or package lock file to see if there's something that's forcing you to bring in an older version.

**Comment by justinvp** [comment]
> Looking at the codegen changes made to the modules in #5839, I think for NodeJS specifically, we need to bump the version of `@pulumi/pulumi` in `package.json` across all providers for this change to be safe.

@leezen, yes, we did this for both Node.js _and_ Python's `setup.py` before releasing the Kubernetes and AWS updates that included the resource package/module registration calls.

- https://github.com/pulumi/pulumi-kubernetes/commit/e363b8572632977a6628f0ea5289328ecd2106ff
- https://github.com/pulumi/pulumi-aws/commit/dc8d336caa9186ced9520f4546c42ba956bd195e

We'll want to do this for the other providers as well as they are updated to include the registration calls. Looks like we missed it for `@pulumi/random`. cc: @stack72, @jaxxstorm

**Comment by justinvp** [comment]
@estyrke, in the meantime, as Lee mentioned, `@pulumi/random` should still pull in the latest version of `@pulumi/pulumi`, but may not be doing that depending on your existing `node_modules` cache or package lock file. You may need to delete your package lock file and `node_modules` and rerun `npm install` (or `yarn install`).

**Comment by aaronhayes** [comment]
This seems to be fixed in the latest version. Should we close this issue?

**Comment by leezen** [comment]
Yup -- was just waiting on someone to confirm in case there was something else going on. Thanks for confirming!

**Comment by victor-cui-discovery** [comment]
I'm getting this error with pulumi version **2.17.2**

**Comment by justinvp** [comment]
@victor-cui-discovery, what package versions are you using (see your package lock file)? It's likely you need to upgrade the version of `@pulumi/pulumi`.

**Comment by victor-cui-discovery** [comment]
My `yarn.lock` file has version  **2.17.2** declared.
```
"@pulumi/pulumi@~2.17.2":
  version "2.17.2"
  resolved "https://registry.yarnpkg.com/@pulumi/pulumi/-/pulumi-2.17.2.tgz#055e3981f599618cdc20a4c3960d023ab95fcfd0"
  integrity sha512-D7vW....
....
```
I also see some other versions of pulumi like `2.15.0` declared in the lockfile but my `package.json` declares version **2.17.2** as a `devDependency`. I'm on version **2.2.0** of @pulumi/random which brings in the pulumi version below in its dependencies.

```
 dependencies:
    "@pulumi/pulumi" "^2.0.0
```

**Comment by justinvp** [comment]
Hmm, `registerResourceModule` should be present in `2.15.0`+. It's possible you have a package in `node_modules` that's pulling its own nested dependency on an older `@pulumi/pulumi`. I've seen this sometimes with `node_modules` and end up deleting the `node_modules` directory and reinstalling the packages.

> "@pulumi/pulumi" "^2.0.0

This should match the latest of 2.x.

**Comment by victor-cui-discovery** [comment]
I've tried deleting the `node_modules` directory with `rm -r node_modules/`,`rm -r ~/.pulumi/plugins/`, and `yarn cache clean` then running `yarn` but still running into this. I've ctrl-f for `@pulumi/pulumi` and everything is on `^2.0.0` or a specific `2.15.0`+ version.

**Comment by justinvp** [comment]
If you delete your `yarn.lock` (you may want to back it up in case you want to go back to these specific deps) and `rm -r node_modules/`, and then run `yarn install`, do you still hit the issue?

**Comment by victor-cui-discovery** [comment]
Yes deleting my `yarn.lock` and recreating it resolved the "pulumi.runtime.registerResourceModule is not a function" error

**Comment by XBeg9** [comment]
having the same issue, `azure-nextgen` has ^2.0.0, but tried to make a mandatory resolution to 2.20.0 and it doesn't help at all, even with `rm -r ~/.pulumi/plugins/`

**Comment by justinvp** [comment]
@XBeg9, this is unrelated to `~/.pulumi/plugins/`. It can happen when something is pulling in an older `@pulumi/pulumi` Node.js package. The easiest way to fix the issue is to delete `node_modules` and the lock file (either `package-lock.json` or `yarn.lock`) and reinstall the Node dependencies (`npm install` or `yarn install`).

**Comment by XBeg9** [comment]
@justinvp yep, I know, I've verified that some dependencies requested old version of `@pulumi/pulumi` package. Deleting \*.lock files is a bad practice, I suggest using [resolution field](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)

**Comment by boillodmanuel** [comment]
I got this issue with npm package `@pulumi/pulumi` `3.2.1`. And upgrading to `3.5.1` fixed it
