### ISSUE TITLE
panic when attempting to use pulumi from terminal with 0 width

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#5957]
Upon `pulumi up` (for any new project), and receive the following stack trace:

```
panic: fatal: An assertion has failed: action must be non empty

goroutine 54 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assertf(0x0, 0x1cdded5, 0x18, 0x0, 0x0, 0x0)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:33 +0x1a5
github.com/pulumi/pulumi/pkg/v2/backend/display.makeActionProgress(0x2b16a20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:60 +0xe5
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).refreshColumns(0xc0016e2480, 0x2b16a20, 0x1, 0xc0016c4370, 0x5, 0x5, 0xc0010bd5f0, 0x5, 0x5)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:431 +0x10e
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).refreshAllRowsIfInTerminal(0xc0016e2480)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:649 +0x373
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).processNormalEvent(0xc0016e2480, 0x1cc7688, 0xc, 0x1b168c0, 0xc0013a9c20)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:1128 +0x376
github.com/pulumi/pulumi/pkg/v2/backend/display.(*ProgressDisplay).processEvents(0xc0016e2480, 0xc00154a460, 0xc00007d260)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:1196 +0x145
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowProgressEvents.func1(0xc0016e2480, 0xc00154a460, 0xc00007d260, 0xc00007d440)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:336 +0x3f
created by github.com/pulumi/pulumi/pkg/v2/backend/display.ShowProgressEvents
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/progress.go:335 +0x4fd
```

**Comment by leezen** [comment]
Looks related to https://github.com/pulumi/pulumi/issues/5643

**Comment by lukehoban** [comment]
See also https://github.com/pulumi/pulumi/issues/5643 and https://github.com/pulumi/pulumi/issues/4904 which are the same failure. We fixed a related issue in https://github.com/pulumi/pulumi/pull/3936.

**Comment by leezen** [comment]
Playing a bit with the terminal and looking at where this is failing, it seems to have something to do w/ the way we compute columns based on colorization. If I run

`NO_COLOR=true pulumi up` then things work as expected.

**Comment by leezen** [comment]
And now I can't repro it after resizing my terminal... it works with colors now.

**Comment by leezen** [comment]
After a bunch of resizing, restarting, exiting, etc. I think the following is a reliable repro:
1. From CloudShell, run `exit` on the command line
2. It should prompt:
    ```
    Lost your connection to the environment.
    Press any key to reconnect and continue using AWS CloudShell
    ```
1. Press any key (it should display `Preparing your terminal...`)
1. Run `pulumi up` and you should see the previewing section followed by the panic.

Once you resize the terminal, all is fine again. It appears that for whatever reason, we detect the terminal width and height as 0:

```
[cloudshell-user@ip-10-0-22-68 term-test]$ go run main.go
0
0
true
```

where main.go is simply testing ```currentTerminalWidth, currentTerminalHeight, err := terminal.GetSize(int(os.Stdout.Fd()))```

this appears to be a bug with CloudShell itself since once I resize the window, then the correct values come back. This does mean that we do not error properly when detecting a 0 width window, however (there's no logic in the code that checks for this from what I can tell).
