### ISSUE TITLE
Terraform issue in build pipeline 

### ISSUE THREAD

**Issue by manojmasinete** [pulumi/pulumi#5974]
The plan phase is getting paused with the below lines :

"The secret key (password) of a service principal in the owner role for the subscription. variable needs to be pulled from Azure Devops Key Vault and passed in at build time. DO NOT INCLUDE IN AND FILES!!"

**Comment by leezen** [comment]
I'm having trouble understanding what's going on here exactly. Did you mean to open this issue here? The title states "Terraform"?

**Comment by manojmasinete** [comment]
@leezen Yes this issue is regarding the Terraform pipeline. The output window was paused with the above liens so need help for why it's happening.

**Comment by leezen** [comment]
@manojmasinete I'm still having trouble following what's going on. Could you please provide more context along with reproduction steps?

**Comment by manojmasinete** [comment]
Hello @leezen  I'm getting an error as following:

Error: Error building AzureRM Client: obtain subscription(***) from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1: Subscription '***' not found. Check the spelling and casing and try again.

**Comment by leezen** [comment]
The error messages are helpful, but can you also please provide more information about what you're doing? What did you run to get that error? What does your environment look like? What versions of the CLI/SDKs are you using?

**Comment by manojmasinete** [comment]
Just one query:

Do the service principal need the contributor role on the top subscription?

**Comment by leezen** [comment]
@manojmasinete I'm still not following. Could you please provide the details I asked for in my previous comment?

**Comment by stack72** [comment]
I am going to close this out - there isn't any reproducible information to help us find the error here

I am more than happy to reopen it if you can provide us some form of reproduction

Paul
