### ISSUE TITLE
hyphens in resource state mismatch go code from pulumi import

### ISSUE THREAD

**Issue by dustin-decker** [pulumi/pulumi#5985]
When importing a resource with hyphens in the given pulumi resource name, the go code generated uses underscores in the name. The name in the code mismatches the state, and so pulumi attempts to create a new resource.

## Expected Behavior
The hyphens should not be replaced with underscores, and Pulumi should recognize as being imported and not attempt to create a new one.

## Current Behavior
Pulumi attempts to create a new resource since the name in code mismatches the name in the state.

## Steps to Reproduce

1. Use a go stack
2. Import resource, using hyphens in name `pulumi import gcp:organizations/policy:Policy uniform-bucket-access 111111111111/constraints/storage.uniformBucketLevelAccess`
3. Observe stack resource has hyphens in the name with `pulumi stack export`
4. Observe generated go code has hyphens replaced with underscores
5. Observe a new resource being created when running `pulumi up`

**Comment by dustin-decker** [comment]
My guess is go's codegen is mutating this string with [makeValidIdentifier](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/go/utilities.go#L58).

**Comment by EvanBoyle** [comment]
@dustin-decker 

I just tried something similar with pulumi 3.8.0. I imported an S3 bucket with a hyphenated name:

```
$ pulumi import aws:s3/bucket:Bucket mybucket abc-defg-hyphenname
```

And it generated a valid program that I can refresh without diff

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := s3.NewBucket(ctx, "mybucket", &s3.BucketArgs{
			Acl:          pulumi.String("private"),
			Bucket:       pulumi.String(" abc-defg-hyphenname"),
			ForceDestroy: pulumi.Bool(false),
		}, pulumi.Protect(true))
		if err != nil {
			return err
		}
		return nil
	})
}
```

I'm going to close this out for now. If you have an updated repro with code, please feel free to reopen or open another issue.
