### ISSUE TITLE
Improve automatic handling of secrets in Pulumi

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#5986]
Specifically, we want to implement https://github.com/pulumi/pulumi-terraform-bridge/issues/10. Part of doing that requires first doing https://github.com/pulumi/pulumi/issues/5653 since there needs to be an ergonomic way to have an "easy out" (as stated in #10). Finally, there are some rough edges around displaying secrets such as https://github.com/pulumi/pulumi/issues/5474

We should also decide if we want to do something like https://github.com/pulumi/pulumi/issues/5640 or close it as something we don't want to do.

**Comment by infin8x** [comment]
Closing this in favor of tracking the more specific issues (#5640 and #5474) on the team backlog
