### ISSUE TITLE
Stack corrupted by "dependency refers to missing resource"

### ISSUE THREAD

**Issue by MarkusKramer** [pulumi/pulumi#5988]
I'm trying to create a API gateway resource like this

```
function apiGateway(mainLambda: aws.lambda.Function, env: Environment) {
    return new awsx.apigateway.API(`${env.resourceNamePrefix}backend`, {
        routes: [{
            path: "{proxy+}",
            method: "POST",
            eventHandler: mainLambda
        }, {
            path: "{proxy+}",
            method: "OPTIONS",
            eventHandler: mainLambda
        }],
    });
}
```

This previously worked. Now on `pulumi up` I'm getting
```
  aws:apigateway:x:API (...-dev1-backend):
    error: post-step event returned an error: failed to save snapshot: .pulumi/stacks/dev1.json: snapshot integrity failure; it was already written, but is invalid (backup available at .pulumi/stacks/dev1.json.bak): resource urn:pulumi:dev1::...::aws:apigateway:x:API::...-dev1-backend dependency  refers to missing resource
```

The most annoying thing is that all subsequent actions on the stack are now failing with `error: .pulumi/stacks/dev1.json: snapshot integrity failure; refusing to use it: resource urn:pulumi:dev1::...::aws:apigateway:x:API$aws:apigateway/restApi:RestApi::...-dev1-backend dependency  refers to missing resource`

Pulumi version: v2.15.6

**Comment by leezen** [comment]
Can you please try performing a `pulumi stack export` and seeing if it contains the missing resource URN? If not, perhaps compare against the backup state file to see if somehow something was accidentally deleted?

**Comment by MarkusKramer** [comment]
I believe the root cause of my issue was #5577. It seems my stack had referenced a zip archive that didn't exist.
Luckily this happened on a dev environment.

**Comment by mikhailshilkov** [comment]
Indeed, I got the same error today because of #5577
