### ISSUE TITLE
contains_unknowns fails if val contains a "values" key

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#6000]
The `contains_unknowns` function fails if the input `val` contains a `"values"` key.

https://github.com/pulumi/pulumi/blob/7e3d69a53ad34134f57d9bb3ad62d4e5d95f5723/sdk/python/lib/pulumi/runtime/rpc.py#L562-L575

Changing the return statement to the code below _seems_ to fix this:

```py
return impl(val.values(), stack)
```

**Comment by komalali** [comment]
I can't seem to repro this, are there any more details on what the failure looks like or a case where it fails?
