### ISSUE TITLE
Error: compile: version "go1.14" does not match go tool version "go1.15.1"

### ISSUE THREAD

**Issue by andrepinto** [pulumi/pulumi#6002]
When run pulumi up 

## Expected Behavior
# runtime/internal/sys
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # internal/race
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # math/bits
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # runtime/internal/atomic
    flag provided but not defined: -p
    usage: asm [options] file.s ...
    Flags:
      -D value
        	predefined symbol with optional simple value -D=identifier=value; can be set multiple times
      -I value
        	include directory; can be set multiple times
      -S	print assembly and machine code
      -V	print version and exit
      -debug
        	dump instructions as they are parsed
      -dynlink
        	support references to Go symbols defined in other shared libraries
      -e	no limit on number of errors reported
      -gensymabis
        	write symbol ABI information to output file, don't assemble
      -newobj
        	use new object file format
      -o string
        	output file; default foo.o for /a/b/c/foo.s as first argument
      -shared
        	generate code that can be linked into a shared library
      -trimpath string
        	remove prefix from recorded source file paths
    # internal/cpu
    flag provided but not defined: -p
    usage: asm [options] file.s ...
    Flags:
      -D value
        	predefined symbol with optional simple value -D=identifier=value; can be set multiple times
      -I value
        	include directory; can be set multiple times
      -S	print assembly and machine code
      -V	print version and exit
      -debug
        	dump instructions as they are parsed
      -dynlink
        	support references to Go symbols defined in other shared libraries
      -e	no limit on number of errors reported
      -gensymabis
        	write symbol ABI information to output file, don't assemble
      -newobj
        	use new object file format
      -o string
        	output file; default foo.o for /a/b/c/foo.s as first argument
      -shared
        	generate code that can be linked into a shared library
      -trimpath string
        	remove prefix from recorded source file paths
    # sync/atomic
    flag provided but not defined: -p
    usage: asm [options] file.s ...
    Flags:
      -D value
        	predefined symbol with optional simple value -D=identifier=value; can be set multiple times
      -I value
        	include directory; can be set multiple times
      -S	print assembly and machine code
      -V	print version and exit
      -debug
        	dump instructions as they are parsed
      -dynlink
        	support references to Go symbols defined in other shared libraries
      -e	no limit on number of errors reported
      -gensymabis
        	write symbol ABI information to output file, don't assemble
      -newobj
        	use new object file format
      -o string
        	output file; default foo.o for /a/b/c/foo.s as first argument
      -shared
        	generate code that can be linked into a shared library
      -trimpath string
        	remove prefix from recorded source file paths
    # unicode
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # unicode/utf8
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # unicode/utf16
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # encoding
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # crypto/subtle
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # crypto/internal/subtle
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # container/list
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # internal/nettrace
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # vendor/golang.org/x/crypto/cryptobyte/asn1
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # vendor/golang.org/x/crypto/internal/subtle
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # image/color
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # golang.org/x/crypto/internal/subtle
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # github.com/uber/jaeger-client-go/internal/baggage
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # github.com/uber/jaeger-client-go/internal/reporterstats
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # github.com/pulumi/pulumi/sdk/v2/go/common/version
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # github.com/uber/jaeger-client-go/internal/throttler
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # google.golang.org/grpc/internal/grpclog
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # google.golang.org/grpc/serviceconfig
    compile: version "go1.14" does not match go tool version "go1.15.1"
    # runtime/cgo
    flag provided but not defined: -p
    usage: asm [options] file.s ...
    Flags:
      -D value
        	predefined symbol with optional simple value -D=identifier=value; can be set multiple times
      -I value
        	include directory; can be set multiple times
      -S	print assembly and machine code
      -V	print version and exit
      -debug
        	dump instructions as they are parsed
      -dynlink
        	support references to Go symbols defined in other shared libraries
      -e	no limit on number of errors reported
      -gensymabis
        	write symbol ABI information to output file, don't assemble
      -newobj
        	use new object file format
      -o string
        	output file; default foo.o for /a/b/c/foo.s as first argument
      -shared
        	generate code that can be linked into a shared library
      -trimpath string
        	remove prefix from recorded source file paths

    error: an unhandled error occurred: program exited with non-zero exit code: 2

## Steps to Reproduce
pulumi up

## Context (Environment)
language: Golang 
my go version: 1.15.1
pulumi version: v2.16.0

Update go.mod to

go 1.15

require (
        github.com/pulumi/pulumi-kubernetes/sdk/v2 v2.7.5
        github.com/pulumi/pulumi/sdk/v2 v2.10.2-0.20200917182150-ab70dd3d645d
)

but with default go.mod  the error occurs in the same way

**Comment by leezen** [comment]
This looks like it could be a potential mismatch between the version of go you're running and where it's picking up the underlying libraries? Have you checked that your `GOROOT` and `GOPATH` are correct?

**Comment by wnz27** [comment]
this is command `go build` use default go version is go1.14 , 
this cli tool can add a go path param or other method to use specific go version to 
use `go build` compile code
example:
```shell
export GOROOT=go/specific/version
go/specific/version/bin/go build
```

**Comment by leezen** [comment]
Thanks for making those steps explicit. Since we haven't heard back from the original poster in quite some time, I'm going to close this issue out.
