### ISSUE TITLE
fetching userinfo failing in pulumi-nodejs:2.16.2 image

### ISSUE THREAD

**Issue by tummalah** [pulumi/pulumi#6012]
trying docker run on the image failing when fetching userinfo. Testing the same access token on local Pulumi CLI works fine.  

command failing :
docker run --rm -ti -e PULUMI_ACCESS_TOKEN=<<myaccesstoken>> -v ${pwd}:/pulumi/projects pulumi/pulumi-nodejs:2.16.2 /bin/bash -c "pulumi  preview -s dev"

Error:
Logging in using access token from PULUMI_ACCESS_TOKEN
error: getting user info from https://api.pulumi.com: performing HTTP request: Get "https://api.pulumi.com/api/user": x509: certificate signed by unknown authority

**Comment by lukehoban** [comment]
I just tried this myself and did not see this error.

Are you running in an environment where you need a custom CA installed?  If so - does this comment help? https://github.com/pulumi/pulumi/issues/2233#issuecomment-518305242

**Comment by tummalah** [comment]
> I just tried this myself and did not see this error.
> 
> Are you running in an environment where you need a custom CA installed? If so - does this comment help? [#2233 (comment)](https://github.com/pulumi/pulumi/issues/2233#issuecomment-518305242)

@lukehoban  thanks for the quick response :) . I am using Docker desktop on windows 10. Is there anyway we can mount the CA store of windows to docker ? I installed the root CA into windows trusted store and restarted the Docker Daemon but no luck. I will try the same in my personal laptop instead of my companies' and see how it goes.

**Comment by lukehoban** [comment]
> Is there anyway we can mount the CA store of windows to docker ?

Honestly not sure on this unfortunately.

**Comment by tummalah** [comment]
@lukehoban  Happy to inform that this issue is fixed. Running Dind with custom CA has fixed the issue.
