### ISSUE TITLE
Pulumi config set returns an error when passing a value starting with `-`

### ISSUE THREAD

**Issue by codylandry** [pulumi/pulumi#6015]
When attempting to store a secret ssh key starting with a `-` in config, I get the following error:
```
An error occurred: bad flag syntax: -----BEGIN OPENSSH PRIVATE KEY-----...
```

This is the command I ran:
```
pulumi config set --secret git.id_rsa "$(cat id_rsa)"
```

When searching for a solution to this, a common answer is to use a command line parameter with `=` like this:
```
pulumi config set --secret git.id_rsa --value="$(cat id_rsa)"
```

Unfortunately, this isn't included in the command options and are instead positional arguments.  I'd suggest that `--value` be added to accommodate these situations.

## Expected Behavior
I expect to have a way to pass any string value to a config.

## Current Behavior
I get the above error.

## Steps to Reproduce
Run the following where file `id_rsa` begins with a `-`
```
pulumi config set --secret git.id_rsa "$(cat id_rsa)"
```

## Context (Environment)
Macbook pro bash 3.2

Also, I feel like there might be some quote escaping combination that can be used, but I couldn't come up with one.  Each attempt I made either caused the error or caused quotes to end up in the stored config value.

**Comment by codylandry** [comment]
😓 Please ignore this.  `|` works just fine.

**Comment by HectorArchilogic** [comment]
Hi @codylandry May I ask how did you solved it?

**Comment by codylandry** [comment]
@HectorArchilogic, if memory serves, I believe I piped in the value instead of using `--value`.  Something like this:

`cat id_rsa | pulumi config set --secret git.id_rsa`

**Comment by rensvis** [comment]
I found using -- before the value also works:
`pulumi config set --secret secretKey -- '-----BEGIN PRIVATE KEY-----\nsome-private-key\n-----END PRIVATE KEY-----'`
