### ISSUE TITLE
Support pipenv on the pulumi/actions container

### ISSUE THREAD

**Issue by GaboFDC** [pulumi/pulumi#6018]
Right now pulumi is highly coupled with the standard requirements.txt file for python dependencies.
But there may be cases in which this file is not used, like when using pipenv.

For these cases you need to maintain both the Pipfile and the requirements.txt

We could change the https://github.com/pulumi/pulumi/blob/master/docker/actions/entrypoint.sh file, to also check if there is a Pipfile.lock file and use pipenv to install the dependencies.

I was going to open the PR straight away, but wanted to get the feedback opinion from maintainers first.

This also could be a first step to make pulumi less coupled with venv and pip, and allow to use other methods like pipfile. i.e, when creating a new python project, allow the user to use pipenv, instead of installing the .venv straight away.

**Comment by stack72** [comment]
Hi @GaboFDC 

Just to give a heads up that this action will undergo a major rewrite in q1 2021 to remove this large docker container and move to a native GitHub action

We won't be carrying out any major work on this action until that happens BUT we would happily accept a PR that adds this functionality that you need

I hope this gives you a little insight

Thanks

Paul

**Comment by GaboFDC** [comment]
Thanks for the quick reply @stack72 
Just to be sure, is this been tracked on any issue? Also can you specify what do you mean by a native GitHub action?
This isn't really major work, is just a few extra checks, and install some extra dependencies (pipenv) so this could also be done in the native action, right?

**Comment by stack72** [comment]
Hey @GaboFDC 

So a native GitHub action means that it will no longer be an all in one docker container - all the setup eg Python install / pipenv setup will need to be handled outside of the the Pulumi action

The action itself will only handle the Pulumi commands, it will no longer handle the setup

I am writing up a design document right now that will be published as a new issue this week - that will show some of the new sample action setups that we suggest as part of the migration

Paul

**Comment by GaboFDC** [comment]
Nice, now is much more clear, so yeah, for now if the pr is good enough it will suffice, later when the action only handles running pulumi cli, then we can setup the workflow to install dependencies and everything else normally.

**Comment by GaboFDC** [comment]
Could you give a look to https://github.com/pulumi/pulumi/pull/6019

**Comment by stack72** [comment]
Closed via https://github.com/pulumi/actions/commit/ba58c77ae0471c1f154bd36645e61d9657222565

**Comment by parkedwards** [comment]
@stack72 
Quick question on your `pipenv` update 

If the action is being invoked in a monorepo project (via CI/CD), where there are multiple pulumi projects in subdirectories (which we point the action to via `work-dir`), but the root level contains the Pipfile.lock -- am I correct in understanding that the action will not invoke `pipenv run`?

**Comment by drubf** [comment]
> @stack72 Quick question on your `pipenv` update
> 
> If the action is being invoked in a monorepo project (via CI/CD), where there are multiple pulumi projects in subdirectories (which we point the action to via `work-dir`), but the root level contains the Pipfile.lock -- am I correct in understanding that the action will not invoke `pipenv run`?

Hi @parkedwards,

Next time try skipping the pipenv, like this:
```
    - name: Pip install Pipfile.lock
      shell: bash
      run: |
        pipenv requirements > requirements.txt
        pip install -r requirements.txt
```
