### ISSUE TITLE
Automation API has no option to `rm` a stack

### ISSUE THREAD

**Issue by roderik** [pulumi/pulumi#6020]
## Expected Behavior

As it is possible to create dynamic stacks, it should be possible to remove these stacks completely

**Comment by komalali** [comment]
@roderik This functionality does exist. I'm not sure which language you are using so I've listed both references below.

Source code:
* [[Go reference]](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/local_workspace.go#L351-L358)
* [[TS reference]](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/x/automation/localWorkspace.ts#L333-L340)

Usage:
* [[Go reference]](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/local_workspace_test.go#L735)
* [[TS reference]](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/tests/automation/localWorkspace.spec.ts#L156)

**Comment by roderik** [comment]
I totally overlooked this, my bad
