### ISSUE TITLE
Why use ComponentResources?

### ISSUE THREAD

**Issue by vyrwu** [pulumi/pulumi#6021]
This is a generic question about the idiomatic way of structuring Pulumi scripts in a scalable way.
 
I find myself wondering about the advantages of structuring Pulumi scripts around Component Resources, as opposed to native language abstraction tools, like functions. 

Based on the Pulumi Programming Model doc, using components seems to be a " highly recommended" way of structuring Pulumi programs. However, I've managed to spend the last few months building Pulumi exclusively using TS language features. Example in TypeScript:

```js
// Why would I do:
class TopSecret extends pulumi.ComponentResource {
    constructor(name, namespace, opts): {
        super('iac:TopSecret', name, opts)
        // More implementation details here
        new k8s.core.v1.Secret(
            name,
            {
                metadata: {
                    namespace,
                },
                stringData: {
                    'password.txt': 'somePassword',
                },
            },
            {
                dependsOn: this,
            }
        )
    this.registerOutputs({})
    }
}

// If I can do:
const buildTopSecret = (name, namespace, opts) => {
    // More implementation details here
    new k8s.core.v1.Secret(
        name,
        {
            metadata: {
                namespace,
            },
            stringData: {
                'password.txt': 'somePassword',
            },
        },
        opts
    )
}
```

Due to the strong push of authors of Pulumi to use Components, and seeing how the community is increasingly leaning towards this approach, I am considering doing some refactoring to be more "idiomatic" about my Pulumi scripts. What will I gain from that? Are there any tangible benefits to using ComponentsResources? 

Thanks in advance

**Comment by leezen** [comment]
There's nothing technically "wrong" with using functions the way you're using them. One of the advantages of Pulumi is you're able to take advantage of existing abstraction mechanisms in languages to suit your needs (such as using functions to encapsulate logic). You could even use classes without ComponentResource to abstract away the fact that a component might be multiple resources.

That being said, there are a number of reasons to consider using ComponentResources. Two of them are mentioned in https://www.pulumi.com/docs/intro/concepts/programming-model/#components -- ComponentResources can have their own outputs, so this extends the abstraction model of a resource. For example, if I'm creating a `S3ReplicatedBucket` resource, I could expose outputs off the component resource itself (e.g. `S3ReplicatedBucket.sourceRegion` and `S3ReplicatedBucket.destinationRegion`) as conveniences to users of the component resource. These outputs are tracked as part of the state in the engine. There's no easy way to replicate this with other encapsulation methods. The other, inheriting resource providers, provides a convenience for users of your abstraction.

There are a couple other reasons to use ComponentResources not mentioned directly in that section. One is that you can pass a transformation to a `ComponentResource` (https://www.pulumi.com/docs/intro/concepts/programming-model/#transformations). As a result, if a user of your component wanted to modify a child resource in some way, they could pass a transformation without having to completely break apart the abstraction. Additionally, you can take advantage of the various `ResourceOptions` one typically expects to provide to a resource (https://github.com/pulumi/pulumi/blob/58c07c52c8d4db037c284b66d432d96db6081ca9/sdk/nodejs/resource.ts#L503) and have those work as expected.

Another reason is that we're building support for cross-language sharing of component resources https://github.com/pulumi/pulumi/issues/2430. Taking advantage of the functionality to write once and use across all languages requires authoring a component against the ComponentResource interface.

**Comment by vyrwu** [comment]
@leezen thx for an exhaustive answer!

I've noticed that Pulumi has somewhat of an easier time figuring out the dependencies and parent-child relationships when using Component Resources. Is due to the way it's handled internally?

BTW Pulumi also prints Component structures in the resource tree very neatly, making for potentially more readable previews IMHO.

**Comment by leezen** [comment]
For parent-child relationships, it's still just using the underlying `parent` option to a resource, so it's not necessarily "better" from that perspective.
