### ISSUE TITLE
Importing from file shows error if resources have same name but different types.

### ISSUE THREAD

**Issue by rchamorro** [pulumi/pulumi#6032]
When importing resources using a file with the command `pulumi import -f resources.json` and C# as target language.

It works importing the same resources without the file.

Example imported file:

```json
{
  "resources": [      
    {
      "type": "azure-nextgen:resources/v20200601:ResourceGroup",
      "name": "resource-name",
      "id": "/subscriptions/subscription-id/resourceGroups/resource-group-name"
    },    
    {
      "type": "azure-nextgen:web/v20200601:AppServicePlan",
      "name": "resource-name",
      "id": "/subscriptions/subscription-id/resourceGroups/resource-group-name/providers/Microsoft.Web/serverfarms/app-service-plan-name"
    }
  ]
}
```

## Expected Behavior

Do not show error importing resources from file when they have same names but different types, and show the code that should be included in the Pulumi Stack.

## Current Behavior

Pulumi imports the resource but shows and error and does not show the code required to handle the resource.

This is the output:

```
     Type                                                Name           Status
 +   pulumi:pulumi:Stack                                 stack-name     created
 =   ├─ azure-nextgen:web/v20200601:AppServicePlan       resource-name  imported
 =   └─ azure-nextgen:resources/v20200601:ResourceGroup  resource-name  imported

Resources:
    + 1 created
    = 2 imported
    3 changes

Duration: 7s

error: internal error: Error: "internal-apis" already declared

  on anonymous.pp line 0:
   1: resource internal-apis "azure-nextgen:resources/v20200601:ResourceGroup" {
   2:     location = "westeurope"
   3:     resourceGroupName = "resource-name"
   4: options {
   5: protect =true
   7: }
   9: }

"resource-name" already declared
```

## Steps to Reproduce

1. Create a file with two resources two import with different types and same name 
2. pulumi import -f resources.json

## Context (Environment)

- Windows 10
- C# Target language
- No other resources in the stack

**Comment by HagaiBarel** [comment]
Hitting this as well using `go` as the target language, `pulumi v2.16.2`

**Comment by mikhailshilkov** [comment]
Is this not "by design"? Name is translated to variable names in the target programming language - is it not a reasonable requirement to keep them unique? Does the requirement to have them unique block any scenario?

**Comment by EvanBoyle** [comment]
This is by design. There cannot be two resources within the same lexical scope in a program.

**Comment by clstokes** [comment]
I believe this should be re-opened. 

While it's true that variable names cannot be re-used within the same lexical scope in a program, it is common to re-use the same **_logical_** resource name and that is allowed by Pulumi and should be supported by `pulumi import --file ...`. [Here is an example](https://github.com/pulumi/examples/blob/master/gcp-py-instance-nginx/__main__.py#L10) from our own examples repo of this. 

This also causes friction for users that are wanting to do a large import by generating the input file from another source (such as a terraform state file) where resource names are re-used.

**Comment by lukehoban** [comment]
Just an additional note - this happens because the `name` provided in the import specification is used for two purposes:
1. The logical resource name
2. The language-level variable name bound to the resource

While the name in (1) doesn't need to be unique (for resources of different types), (2) does need to be unique because all these variables will be code-generated to live in the same scope.

We are considering potentially removing the error here, which would then lead to generating code which will error when pasted into your program, but can be easily fixed up as needed.  

Alternatively, we might allow specifying a `languageName` separately, where that language name *would* still need to be globally unique across the import operation.

**Comment by denniswebb** [comment]
Can we get a flag that disables the language generation? We don't need that part. It's useful for somebody learning Pulumi and IaC, but not for all of us.
