### ISSUE TITLE
Slow performance for stack.setAllConfig

### ISSUE THREAD

**Issue by roderik** [pulumi/pulumi#6042]
I'm experiencing 50s delays for the following call to pulumi via the automation API. I moved from individual config sets which were slow to this one to try and make it quicker, but no netto difference.

```
  console.log(new Date());
  await stack.setAllConfig({
    'cloudflare:accountId': { value: 'xxx' },
    'cloudflare:apiKey': { value: 'xxx', secret: true },
    'cloudflare:email': { value: 'xxx@xxx.xx' },
    chartmuseumPassword: { value: 'xxx', secret: true },
    chartmuseumUsername: { value: 'xxx' },
    ghcrPullSecretPassword: {
      value: 'xxx',
      secret: true,
    },
    ghcrPullSecretUsername: { value: 'xxx@xxxx.xxx' },
    'gcp:project': { value: process.env.GOOGLECLOUD_PROJECT_ID! },
    'gcp:zone': { value: 'europe-west1-b' },
    'gcp:credentials': {
      value: JSON.stringify({
        type: 'service_account',
        project_id: process.env.GOOGLECLOUD_PROJECT_ID,
        private_key_id: process.env.GOOGLECLOUD_PRIVATE_KEY_ID,
        private_key: process.env.GOOGLECLOUD_PRIVATE_KEY!.replace(/\\n/g, '\n'),
        client_email: process.env.GOOGLECLOUD_CLIENT_EMAIL,
        client_id: process.env.GOOGLECLOUD_CLIENT_ID,
        auth_uri: 'https://accounts.google.com/o/oauth2/auth',
        token_uri: 'https://oauth2.googleapis.com/token',
        auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs',
        client_x509_cert_url: process.env.GOOGLECLOUD_CLIENT_X509_CERT_URL,
      }),
      secret: true,
    },
    'azure:environment': { value: 'public' },
    'azure:location': { value: 'westeurope' },
    'azure:clientId': { value: process.env.AZURE_APPLICATION_ID! },
    'azure:clientSecret': { value: process.env.AZURE_CLIENT_SECRET!, secret: true },
    'azure:subscriptionId': { value: process.env.AZURE_SUBSCRIPTION_ID! },
    'azure:tenantId': { value: process.env.AZURE_TENANT! },
    'aws:region': { value: 'eu-west-3' },
    'aws:accessKey': { value: process.env.AWS_ACCESS_KEY_ID! },
    'aws:secretKey': { value: process.env.AWS_SECRET_ACCESS_KEY!, secret: true },
  });
  console.log(new Date());
```

```
2021-01-03T15:06:05.985Z
2021-01-03T15:06:55.158Z
```

## Expected Behavior

Maybe a few seconds as it does an API call?

## Current Behavior

Not sure what is so slow here (maybe the secret encryption?)

## Context (Environment)

It is unfortunate as it is often as long or longer than the actual change and it is incurred at every run.

**Comment by lukehoban** [comment]
I believe this was fixed recently with https://github.com/pulumi/pulumi/pull/6022.  That fix should be be in a release this week.

**Comment by komalali** [comment]
Unfortunately, the change in #6022 had to be reverted. [[Details]](https://github.com/pulumi/pulumi/pull/6022#issuecomment-754209542)

Hopefully, we can address #6050 in the near future.

**Comment by roderik** [comment]
I'm now blindly setting it each time, would it make sense to fetch it first, compare it, and only set it on changes? Or is that not going to make it faster?

**Comment by komalali** [comment]
Yeah, the issue here is that `setAllConfig` just loops through each config key and runs `setConfig` serially, so the more config keys you set the longer it will take. It would help if you only set it on changes or ideally you only set the specific keys that have changed.

That being said, I'm hoping to address this in the next few weeks so that `setAllConfig` writes all changes in parallel which should speed up execution considerably.

**Comment by joeduffy** [comment]
I am wondering, why does it take 50s to set less than 20 config variables, even if it means shelling out to the CLI once each time?  Fully understand that this is going to be O(N) and that this isn't great, however, setting 20 in the shell is just 6s:

```bash
$ time for i in {0..20}; do pulumi config set x y; done

real	0m6.380s
user	0m2.627s
sys	0m0.576s

**Comment by komalali** [comment]
Each `setConfig` first selects the specified stack `pulumi stack select [name]` and then runs `pulumi config set`. Each time it runs each of those, we shell out to a child process, run the command, wait for it to complete, parse the output, move on to the next. So 20 config vars means 40 calls to the CLI. 

In python, I have a test for bulk config ops (set 10, delete 10 config vars). It takes ~40s and almost all of that time is spent waiting for processes.
<img width="2057" alt="Screen Shot 2021-01-05 at 3 05 26 PM" src="https://user-images.githubusercontent.com/24326455/103709491-7f3f1b00-4f67-11eb-930f-f029d3d45d34.png">

I'll replicate it for node.

**Comment by komalali** [comment]
Ran it through the profiler again after bringing in the changes from https://github.com/pulumi/pulumi/pull/6373 and almost a 10x improvement from 40 seconds to <5 seconds. But even better, we go from O(N) time to O(1) which should make set-all and rm-all much more pleasant to use.

<img width="1424" alt="Screen Shot 2021-02-18 at 8 19 33 PM" src="https://user-images.githubusercontent.com/24326455/108457106-b96a3080-7226-11eb-8f95-2727ebe6ebc0.png">
