### ISSUE TITLE
Pulumi keep wanting to replace Firestore Index after creation

### ISSUE THREAD

**Issue by huydinhle** [pulumi/pulumi#6043]
## Summary and Steps to Reproduce
I created a simple firestore index using pulumi. Here is the code
```
foo = gcp.firestore.Index("foo",
    collection="bar",
    fields=[
        gcp.firestore.IndexFieldArgs(
            field_path="field1",
            order="ASCENDING",
        ),
        gcp.firestore.IndexFieldArgs(
            field_path="field2",
            order="ASCENDING",
        ),
        gcp.firestore.IndexFieldArgs(
            field_path="field3",
            order="ASCENDING",
        ),
    ])
```
Then I did a `pulumi preview -r --diff`
## Expected Behavior

The preview diff should show no changes at all.
## Current Behavior

The preview told me to delete a fieldPath called __name__ which I did not created
```
      ~ fields: [
            [0]: <null>
            [1]: <null>
            [2]: <null>
          - [3]: {
                  - fieldPath  : "__name__"
                  - order      : "ASCENDING"
                }
        ]
Resources:
    +-1 to replace
```

## Context (Environment)

1. This issue created misleading information about the state of our infrastructure

### Notes
```
❯ pulumi version
v2.16.2
```

**Comment by leezen** [comment]
This is actually the expected behavior. If last field entry should be `__name__`. If you omit this entry, it will be added automatically with the same direction as that of the last field defined. Since you didn't add it, it's added automatically, but now there's a resulting diff.
