### ISSUE TITLE
[Automation API] Support parallel execution of python inline programs

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#6052]
The Pulumi python runtime implementation uses quite a bit of global state: 
* [SETTINGS](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/settings.py#L94)
* [ROOT](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/settings.py#L189)
* [CONFIG](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/runtime/config.py#L24)

We'll need to refactor all usage of global state out of the python SDK to allow Automation API to execute concurrent programs on different stacks that use the inline/hosted execution model.

Related: https://github.com/pulumi/pulumi/issues/5449

**Comment by AaronFriel** [comment]
Per discussion with @Frassle, we may want to implement this using Python [contextvars](https://docs.python.org/3/library/contextvars.html) for async-local state. This should allow two Pulumi programs in Python to run concurrently.

**Comment by kpitzen** [comment]
Removed the fixed tag until #10472 is merged
