### ISSUE TITLE
Unit tests fail to load configuration from PULUMI_CONFIG when it contains a list

### ISSUE THREAD

**Issue by ashevtsov-wawa** [pulumi/pulumi#6058]
When configuration contains a list and `PULUMI_CONFIG` environment variable is used to pass configuration data at the start of unit tests, the tests fail with `Configuration 'X' value 'Y' is not a valid JSON object`.
`pulumi (up|preview|update)` run fine.

## Expected Behavior
Any configuration data that gets parsed fine by `pulumi (up|preview|update)` should load fine when running unit tests.

## Current Behavior
Unit tests fail with `Configuration 'X' value 'Y' is not a valid JSON object` error.

## Steps to Reproduce
Simple project to reproduce the issue: https://github.com/ashevtsov-wawa/getobject-test
In short
Config file
```yaml
config:
  aws:region: us-east-1
  test:roles:
    - foo
    - bar
```

`index.ts`
```typescript
import * as pulumi from "@pulumi/pulumi";

const config = new pulumi.Config();

export const roles = config.getObject<string[]>('roles') || [];
```

`index.spec.ts`
```typescript
const pulumiConfig = require('js-yaml').safeLoad(require('fs').readFileSync(process.env.PULUMI_TEST_CONFIG_FILE, 'utf8'));

process.env.PULUMI_TEST_MODE = "true";
process.env.PULUMI_NODEJS_STACK = "unit";
process.env.PULUMI_NODEJS_PROJECT = "test"
process.env.PULUMI_CONFIG = JSON.stringify(pulumiConfig.config);

import {expect} from 'chai';
import {roles} from '../index';

describe("index", function () {
    it(`bar role should be defined`, function (done) {
        expect(roles).to.contain('bar');
    });

    it(`foo role should be defined`, function (done) {
        expect(roles).to.contain('foo');
    });
});
```

Test command: `cross-env PULUMI_TEST_CONFIG_FILE=tests/Pulumi.test.yaml mocha -r ts-node/register --reporter spec tests/**/*.ts`

## Context (Environment)
Unable to run unit tests after converting comma-separated values (`foo,bar`) into YAML list for readability.

**Comment by komalali** [comment]
Hey @ashevtsov-wawa I made a [pull-request](https://github.com/ashevtsov-wawa/getobject-test/pull/1/files) to your repro example with a recommended testing strategy using nodejs and automation API. [Here's](https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/tests/automation/localWorkspace.spec.ts) how we test automation-api itself, there might be some other helpful tidbits in there.

**Comment by ashevtsov-wawa** [comment]
@komalali That really helps. Thank you!
I checked Pulumi v1 (which we are still using) and it doesn't have `x/automation` submodule. Can this or a similar approach be used in v1? I know, my example is for v2, just curious whether it possible to work around this issue in v1.

**Comment by komalali** [comment]
Unfortunately, the `automation` submodule is a relatively new development (nodejs was only just released a few months ago). 
For the config-parsing use-case though, if you write you `index.spec.ts` file as follows it should do the trick:

```typescript
const pulumiConfig = require('js-yaml').safeLoad(require('fs').readFileSync(process.env.PULUMI_TEST_CONFIG_FILE, 'utf8'));

process.env.PULUMI_TEST_MODE = "true";
process.env.PULUMI_NODEJS_STACK = "unit";
process.env.PULUMI_NODEJS_PROJECT = "test"
process.env.PULUMI_CONFIG = JSON.stringify(pulumiConfig.config);

import {expect} from 'chai';
import * as pulumi from '@pulumi/pulumi';

describe("index", function () {
    it(`reads config correctly`, function () {
        const config = pulumi.runtime.allConfig();
        const roles = config['test:roles'];
        expect(roles).to.contain('bar');
        expect(roles).to.contain('foo');
    });
});
```

**Comment by komalali** [comment]
I'm going to close out this ticket as I believe I answered your question but I do highly recommend upgrading to v2+ as automation-api will make testing much easier.
