### ISSUE TITLE
NodeJS runtime settings should always be written to and read from (JiT) env vars

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#6059]
Automation API and multi-language components introduced a new lifecycle for SDK runtime settings, mainly runtime options (monitor address, engine address) are not guaranteed to be set in advance of the `@pulumi/pulumi/runtime` module being loaded. 

Automation API spins up its own language server and populates settings based on the gRPC run request it receives. It currently (erroneously) sets these runtime settings via a module level variable: https://github.com/pulumi/pulumi/blob/39297cb9ddb4e2499db72dc64175b6352e9ab7a8/sdk/nodejs/x/automation/server.ts#L87

NodeJS module resolution can sometimes result in two copies of a package being loaded. For instance a simple program:

```
import * as pulumi from "@pulumi/pulumi"; // gets it's own module scoped runtime settings (options)
import * as gcp from "@pulumi/gcp" // gets separate module scoped pulumi/pulumi runtime settings (options)
```

Can result in two instances of the `@pulumi/pulumi/runtime` module and separate copies of runtime settings that are not synced. A call in the provider library ([for example](https://github.com/pulumi/pulumi-gcp/blob/f5b3eb92bd51e3b95c2ee30f8b031ce7a5506125/sdk/nodejs/container/getEngineVersions.ts#L48)) will then be made with uninitialized runtime settings, and fail with the error: 

```
Unhandled exception: Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
```

This error case only occurs if the `@pulumi/pulumi/runtime` module resolves to have multiple copies of the package. This can be manually worked around in the meantime via `package.lock.json` surgery to force `@pulumi/pulumi` to resolve to a single version. 

To fix this we need to do the following:
1. Ensure that `resetOptions` and anything else that manipulates runtime options does so via environment variables: https://github.com/pulumi/pulumi/blob/05a922b431fd88ad10a709e1e264e3eba61a8994/sdk/nodejs/runtime/settings.ts#L62
2. Ensure that runtime options are always run from environment variables instead of the module level cache. Code like this can read stale values due to the new lifecycle: https://github.com/pulumi/pulumi/blob/05a922b431fd88ad10a709e1e264e3eba61a8994/sdk/nodejs/runtime/settings.ts#L226
3. Roll out the new version of the @pulumi/pulumi with this fix to providers https://github.com/pulumi/home/issues/1191
4. Out of an abundance of caution, force providers to share the same `@pulumi/pulumi` dependency via specifying it as a `peerDependency` to prevent errors of this category in the future.  https://github.com/pulumi/home/issues/1191

Those first two above should address the issue in question for both automation api and multi-lang components.

**Comment by EvanBoyle** [comment]
The issue to roll out providers + use force a peer dependency on pulumi/pulumi https://github.com/pulumi/home/issues/1191

**Comment by roderik** [comment]
I can confirm this works! Using yarn resolutions in the package.json is an easy way to do the package.locl tinkering you mention.
