### ISSUE TITLE
Pulumi Refresh failure on azure-nextgen resources due to API version specified.

### ISSUE THREAD

**Issue by mp3911** [pulumi/pulumi#6071]
pulumi refresh fails for the the `azure-nextgen:web/latest:WebAppSwiftVirtualNetworkConnection` & `azure-nextgen:web/latest:WebApp` resource types due to an incorrect API version.

## Expected Behavior
pulumi refresh should be able to interact with Azure to pull down the latest configuration & the azure-nextgen plugin should use available versions of the Azure APIs.

## Current Behavior
On `pulumi refresh` I get the following error for both the `azure-nextgen:web/latest:WebAppSwiftVirtualNetworkConnection` & `azure-nextgen:web/latest:WebApp`

`azure-nextgen:web/latest:WebAppSwiftVirtualNetworkConnection (AdminPortal-westeurope-SUBNET-INTEGRATION):
    error: Preview failed: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'westeurope' and API version '2020-09-01' for type 'sites/networkConfig'. The supported api-versions are '2020-06-01, 2019-08-01, 2018-11-01, 2018-02-01, 2016-08-01, 2016-03-01, 2015-08-01, 2015-07-01, 2015-06-01, 2015-05-01, 2015-04-01, 2015-02-01, 2018-12-01-alpha'. The supported locations are 'southcentralus, msftwestus, msfteastus, msfteastasia, msftnortheurope, eastus2stage, centralusstage, southafricanorth, eastasia, japaneast, westus, australiaeast, brazilsouth, southeastasia, centralus, japanwest, centralindia, uksouth, canadaeast, koreacentral, francecentral, northeurope, westus2, eastus, westindia, eastus2, australiacentral, germanywestcentral, norwayeast, uaenorth, switzerlandnorth, northcentralus, ukwest, australiasoutheast, koreasouth, canadacentral, westeurope, southindia, westcentralus, eastasiastage, northcentralusstage'."`

## Steps to Reproduce
1. Using Pulumi (C#) with packages Pulumi.Azure Version: 3.41.1 and "Pulumi.AzureNextGen" Version="0.4.0"
2. Create an Azure web app with swift vnet connection
3. Perform a pulumi refresh

## Context (Environment)
Trying to manage an Azure App Service using the Azure-NextGen package in the West Europe location. This doesn't prevent performing a pulumi up but we will have to downgrade the Azure-NextGen package to allow the refresh functionality.

**Comment by mikhailshilkov** [comment]
Yes. Microsoft published the specs before they released the API itself (which they claimed they wouldn't do). A fix on our side is tracked in https://github.com/pulumi/pulumi-azure-nextgen/issues/191

**Comment by avdv** [comment]
Hi.

I also get a simliar error:
```
 error: Preview failed: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'westeurope' and API version '2019-07-24-preview' for type 'servers'. The supported api-versions are '2014-01-01, 2014-04-01, 2014-04-01-preview, 2015-05-01-preview, 2017-03-01-preview, 2017-10-01-preview, 2018-06-01-preview, 2019-06-01-preview, 2020-02-02-preview, 2020-08-01-preview, 2020-11-01-preview, 2021-02-01-preview'. The supported locations are 'australiacentral, australiaeast, australiasoutheast, brazilsouth, canadacentral, canadaeast, centralindia, centralus, eastasia, eastus, eastus2, francecentral, germanywestcentral, japaneast, japanwest, jioindiawest, koreacentral, koreasouth, northcentralus, northeurope, norwayeast, southafricanorth, southcentralus, southindia, southeastasia, switzerlandnorth, uaenorth, uksouth, ukwest, westcentralus, westeurope, westindia, westus, westus2, westus3'."
```
I am using pulumi 3.3.1 and az-cli 2.23.0.

The code which fails is:
```cs
var sqlServer = SqlServer.Get("sqlserv", "/subscriptions/<id>/resourceGroups/<res-group>/providers/Microsoft.Sql/servers/sqlserv");
```
Looking at the api versions, the mentioned 2019-07-24-preview one is not available.

TIA for any advice!

**Comment by mikhailshilkov** [comment]
@avdv Why are you using the `2019-07-24-preview` version? I think our default version is `2020-11-01-preview` and it is in your list above. Did you import that namespace explicitly?

**Comment by mikhailshilkov** [comment]
The original issue was fixed so I'll go ahead and fix this issue. If you see a similar error, please report in https://github.com/pulumi/pulumi-azure-native/issues
