### ISSUE TITLE
ApplyString fails when applier return type is StringOutput

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#6073]
ApplyString (and all similar functions) fails when the return type of the applier is a StringOutput, even though it could succeed.  It incorrectly decides to return an `AnyOutput`, and then fails to convert that to a `StringOutput`.  At the very least, a better error saying this is not allowed should be presented instead of defaulting to `AnyOutput` and having that panic as a conversion.  But I see no reason we can't correctly support this as well.

```go
x := pulumi.String("hello").ToStringOutput().ApplyString(func(x string) pulumi.StringOutput {
    return pulumi.String(x).ToStringOutput()
})
```

```
    panic: interface conversion: pulumi.Output is pulumi.AnyOutput, not pulumi.StringOutput
    goroutine 1 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*OutputState).ApplyString(...)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/types_builtins.go:1015
    main.main.func1(0xc0001aa500, 0x247dfb4, 0x13)
        /Users/lukehoban/dd/pulumidemos/goexamplecam/main.go:19 +0xb26
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.RunWithContext(0xc0001aa500, 0x24ae2e0, 0xc0000381ef, 0xc)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/run.go:101 +0x1fb
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.RunErr(0x24ae2e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/run.go:82 +0x239
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.Run(0x24ae2e0, 0x0, 0x0, 0x0)
        /Users/lukehoban/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.9.2/go/pulumi/run.go:39 +0x59
    main.main()
        /Users/lukehoban/dd/pulumidemos/goexamplecam/main.go:14 +0x3e
    exit status 2
```

**Comment by lukehoban** [comment]
There's a proposed fix for this in https://github.com/pulumi/pulumi/commit/4354540168a4d97ac84f30801131a2f3523bf2d0.  It allows `ApplyT` to behave correctly, but raises an issue (noted in the tests), that dependencies are not being collected correctly when the return type of the applier is an Output.  This technically is already a problem for `Apply`, which will succeed, but with the wrong dependencies, for a similar case.  But it's not clear we should expose `ApplyT` to this as well before addressing the underlying issue with correctly combining dependencies (and secretness and potentially other data in the Output).

**Comment by lukehoban** [comment]
A workaround for this in the meantime - the following will work:

```go
		var s pulumi.StringOutput = pulumi.String("hello").ToStringOutput()

		// Apply that returns a `StringOutput`
		x := s.ApplyT(func(v string) pulumi.StringOutput {
			return pulumi.String(v).ToStringOutput()
		})

		// To workaround #6073, convert from `interface{}` to `string`
		x1 := x.ApplyT(func(v interface{}) string {
			return v.(string)
		})
```

**Comment by AaronFriel** [comment]
@lukehoban I think #9513 resolved this, and I think it's correct but something feels wrong about merging the dependencies in the loop in `await`. I think it means that if an output is returned by multiple ApplyT appliers, each usage will accumulate additional dependencies.

A "right" solution might be to call ApplyT(WithContext) _within_ the await loop to create a new output that depends on the inner-awaited output, and yield the outer with the additional deps?

Let's re-open if you think this needs refinement.
