### ISSUE TITLE
Dotnet pulumi unit tests crashes with "the key 'urn' is not present in the dictionary"

### ISSUE THREAD

**Issue by nicro950** [pulumi/pulumi#6080]
Pulumi Dotnet unit tests crashes with "The given key 'urn' was not present in the dictionary." after updating to version pulumi 2.15.5 and later.

It looks like the crash was introduced with this code line: https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi/Testing/MockMonitor.cs#L36

This line will also result in the urn is not present in the dictionary https://github.com/pulumi/pulumi/blob/master/sdk/dotnet/Pulumi/Deployment/Deployment_Invoke.cs#L39 

A solution to this problem would be to move the urn retrieval into the if check, since it looks like the urn is only used when the token type is "pulumi:pulumi:getResource".

This error was discovered while using the pulumi azure library with the following code in a test scenario
```csharp
var clientConfig = Output.Create(GetClientConfig.InvokeAsync());
```
```csharp
await Deployment.TestAsync<Stack>(new Mock());
```

## Expected Behavior
No crashing

## Current Behavior
Crashing

## Steps to Reproduce
1. create a dotnet pulumi project for azure
2. create unit tests which creates a stack which uses "Output.Create(GetClientConfig.InvokeAsync())"
3. The test should crash

## Context (Environment)

We are trying to test our common infrastructure code, and pulumi broke almost all of our unit tests with this change. We can not upgrade to a newer version of pulumi before this is resolved.

**Comment by mikhailshilkov** [comment]
Thank you for the report and sorry for the trouble! You suggested change makes sense, do you want to open a PR?

**Comment by nicro950** [comment]
I can open a pr. Is it required to add any change log or similar things?

**Comment by nicro950** [comment]
I have now created a PR: https://github.com/pulumi/pulumi/pull/6081
