### ISSUE TITLE
Python 3.6 support broken under 2.17.1

### ISSUE THREAD

**Issue by csssuf** [pulumi/pulumi#6108]
With the release of #5979, Pulumi no longer runs under Python 3.6. Specifically, [this `__futures__` import](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/x/automation/stack.py#L15) is only available on 3.7+. After a quick look, it looks like that file already uses quoted annotations for forward references [(e.g. here)](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/x/automation/stack.py#L155), so there should be no changes necessary beyond removing the `__futures__` import.

Assuming this is unintended, I'd be happy to cut a PR to fix it.

## Expected Behavior
Per [the docs](https://www.pulumi.com/docs/reference/pkg/python/pulumi/#pulumi-python-sdk%C2%B6), Pulumi should support Python 3.6.

## Current Behavior
It does not.

## Steps to Reproduce
```jforcier@C02XR3YXJG5M ~/repos/pulumi/sdk/python/lib
(pulumi-36) > $ pip freeze | grep pulumi
pulumi==2.17.1
jforcier@C02XR3YXJG5M ~/repos/pulumi/sdk/python/lib
(pulumi-36) > $ python
Python 3.6.6 (default, Feb 27 2020, 11:00:07)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.20.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pulumi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jforcier/repos/pulumi/sdk/python/lib/pulumi/__init__.py", line 99, in <module>
    from . import runtime, dynamic, policy, x
  File "/Users/jforcier/repos/pulumi/sdk/python/lib/pulumi/x/__init__.py", line 15, in <module>
    from . import automation
  File "/Users/jforcier/repos/pulumi/sdk/python/lib/pulumi/x/automation/__init__.py", line 30, in <module>
    from .local_workspace import (
  File "/Users/jforcier/repos/pulumi/sdk/python/lib/pulumi/x/automation/local_workspace.py", line 26, in <module>
    from .stack import _DATETIME_FORMAT, Stack
  File "/Users/jforcier/repos/pulumi/sdk/python/lib/pulumi/x/automation/stack.py", line 15
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
>>>
```

## Context (Environment)
We run most of our Pulumi code under Python 3.6, and hit this this morning.

**Comment by komalali** [comment]
Hi @csssuf this was definitely unintended, fix incoming.

**Comment by csssuf** [comment]
Thanks for the quick fix!

**Comment by komalali** [comment]
@csssuf No problem, thanks for reporting it! We just started the release for v2.17.2 that will include this patch.
