### ISSUE TITLE
Test our full language runtime version matrix

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#6110]
Our test coverage should at least nightly include validation against all major supported language runtime versions - or at least lowest supported and highest supported.
- [ ] Python 3.7+ (currently 3.7❌, 3.8❌, 3.9✅ and 3.10❌)
- [ ] Node.js Current, Active and Maintenance versions (currently Node.js 20❌,19❌,18❌, 16❌, 14✅)
- [ ] .NET 3.1+ (currently 3.1✅, 6.0❌)
- [ ] Go 1.18+ (currently 1.18❌, 1.19❌)
- [ ] Java 11+ (currently 11✅, 17❌,19❌, 20❌, 21❌)

**Comment by stack72** [comment]
The work required here includes the ability to decouple our builds from our tests - when we currently set a language, we immediately use that same language version for testing - we need to be able to build a binary and SDK and then use that on systems with the other language runtimes involved

**Comment by t0yv0** [comment]
.NET 5 & 6  requested here also

**Comment by lukehoban** [comment]
Updated to include Node.js 20, 19 and 18, and Go 1.18.  For Node.js in particular, we are now only testing a "Maintenance" version.

**Comment by kpitzen** [comment]
Do we expect to continue supporting Python 3.6.x? It was EOL Dec 2021

**Comment by Frassle** [comment]
No. We need to update the table above, and the language pages as well.
I think we'll take a similar stance for all the languages as our nodejs stance (any of the Current, Active and Maintenance LTS versions).
Under that we would for example stop supporting python 3.6, dotnet 5.0, and in December also dotnet 3.1.

**Comment by Frassle** [comment]
I've updated the table at the top to reflect our currently supported versions (as declared on the language pages, e.g. https://www.pulumi.com/docs/intro/languages/python/).
Some of these will change again soon. E.g. dotnet 7.0 is being released in November and dotnet3.1 will no longer be supported in December.

**Comment by Frassle** [comment]
Note that Java 18 is technically currently supported but falls out of support _this_ month so probably isn't worth testing.

**Comment by mikhailshilkov** [comment]
> cartesian product 

Could you please help me why we need a product here? Can't we run separate jobs for each version of each runtime, so that  the result is a sum of all versions, not a product?

**Comment by justinvp** [comment]
I haven't thought this through fully, but I wonder how difficult it'd be to separate out the MLC and automation API tests that cross language boundaries, and use a "version sets" approach for just those tests, but do "sum of all versions" for everything else. Perhaps that'll be too complicated?

**Comment by AaronFriel** [comment]
A "sum of versions" approach for a select set of tests would require discipline in marking which tests depend on which language runtimes and maintaining a system to keep that in sync or generate it as part of computing the job matrix. I'd need to think about how we could do that.

As you can see, even just testing two version sets produces a significant number of test jobs: https://github.com/pulumi/pulumi/runs/8260715397?check_suite_focus=true

That's naively running every test twice on each platform, for lack of a method to do exactly that sort of teasing out of different versions.

Perhaps to split the difference, we do sum of versions testing on the templates & examples repositories instead? Those code samples are already by language(s) and provider(s) by directory. Cross-language tests would just use version sets there?

**Comment by mikhailshilkov** [comment]
I feel like it would be a great start if we just had a "sum of versions" approach and use default versions for all "other" languages that isn't standard. E.g. when you test with .NET 5 (non-standard), you test it against standard versions of all other languages, and so on. Maybe this won't catch some very exotic MLC bugs but I don't feel bad about this at the moment. I feel like we'd get 99% of what we want from this matrix testing.

**Comment by AaronFriel** [comment]
If we're willing to set aside the time to do the refactor, that's doable. Do we feel like this will catch more than just testing minimum-supported, current, latest?

**Comment by Frassle** [comment]
+1 for just testing the sum of versions
We should test that MCLs works for each runtime but there's no need to test nodejs program at each version * a golang component at each version. If each nodejs runtime can send the correct request to the engine, and each golang version can correctly reply to the request from the engine we don't then need to test their product.
