### ISSUE TITLE
Preview hangs when using aws-sdk in a dynamic resource

### ISSUE THREAD

**Issue by josh-pritchard** [pulumi/pulumi#6115]
As soon as I include any function from the aws sdk I think that pulumi is importing it to the __provider function and the preview just hangs. It sat over 40 minutes before I cancelled it. This is a test stack so there is nothing else there other than 1 security group and one network interface for testing. I have debug logs on and its hanging right at the point where it registers resources. If I just comment the function out that step runs in 4 seconds. I have created a number of dynamic resources so I don't think I am doing anything wrong. Here is the code from the very beginning of my resource I did not get very far I was just making sure I could read the Network Interface information. I am doing this because the behavior of the default resource to attach Network Interfaces does not fit our desired flow. This is a major concern for me if I can't interact with AWS through the sdk at all in custom resources there are so many potential use cases. I can spend some time debugging pulumi I am okay with go but I would need to be pointed in the right direction.

```ts
import * as pulumi from '@pulumi/pulumi';
import { v4 as uuidv4 } from 'uuid';
import * as _ from 'lodash';
import * as aws_sdk from 'aws-sdk';
let ec2 = new aws_sdk.EC2();
export interface AttachSecurityGroupsArgs {
  /**
   * Security Groups to attach to network interfaces
   */
  securityGroupIds: pulumi.Input<string>[];
  /**
   * Network Interface Id to attache security groups to
   */
  networkInterfaceId?: pulumi.Input<string>;
}
interface State {
  securityGroupIds: pulumi.Unwrap<string>[];
  networkInterfaceId: pulumi.Unwrap<string>;
}
export class AttachSecurityGroups extends pulumi.dynamic.Resource {
  public readonly securityGroupIds!: pulumi.Input<string>[];
  public readonly networkInterfaceId!: pulumi.Input<string>;
  constructor(
    name: string,
    attachSecurityGroupsArgs: AttachSecurityGroupsArgs,
    opts?: pulumi.CustomResourceOptions
  ) {
    const provider: pulumi.dynamic.ResourceProvider = {
      diff: async (id: pulumi.ID, olds: State, news: State) => {
        let changes = true;
        let replacementProperties: string[] = ['securityGroupIds'];
        return {
          changes: changes,
          replaces: replacementProperties.length > 0 ? replacementProperties : undefined,
          deleteBeforeReplace: true,
        };
      },
      create: async (inputs: State) => {
        let networkInterface = await describeNetworkInterface(inputs.networkInterfaceId);
        console.log(networkInterface);
        return { id: uuidv4(), outs: inputs };
      },
      update: async (id: pulumi.ID, inputs: State, olds: State) => {
        return { id: uuidv4(), outs: inputs };
      },
      delete: async (id: pulumi.ID, props: State) => {
        return;
      },
      read: async (id: pulumi.ID, props: State) => {
        return { id: uuidv4(), props: props };
      },
    };
    super(provider, name, attachSecurityGroupsArgs, opts);
  }
}
let describeNetworkInterface = (
  networkInterfaceId: string
): Promise<aws_sdk.EC2.DescribeNetworkInterfacesResult> => {
  return new Promise((resolve, reject) => {
    var params = {
      NetworkInterfaceIds: [networkInterfaceId],
    };
    console.log(params);
    ec2.describeNetworkInterfaces(params, (err, data) => {
      if (err) {
        reject(err);
      } else {
        resolve(data);
      }
    });
  });
};
```

**Comment by leezen** [comment]
I suspect this has to do with importing `aws-sdk` which is a fairly large library to serialize. Dynamic providers (and their dependencies) are serialized as part of your state. If you swap to only importing the parts of the AWS SDK that you need, e.g. `import S3 from 'aws-sdk/clients/ec2';` does that help you proceed?

**Comment by josh-pritchard** [comment]
This did not solve the issue the preview seems so still hang indefinitely.

**Comment by leezen** [comment]
After playing with this a little bit, it looks like a closure serialization issue. I was able to get this to work by moving the creation of the EC2 client within the provider and using `uuid@7.x` due to the deep import issue mentioned in https://github.com/uuidjs/uuid/issues/444.

e.g.
```
let describeNetworkInterface = (
  networkInterfaceId: string
): Promise<aws_sdk.EC2.DescribeNetworkInterfacesResult> => {
    let ec2 = new aws_sdk.EC2();
    return ec2.describeNetworkInterfaces({
      NetworkInterfaceIds: [networkInterfaceId]
  }).promise();
};
```

**Comment by josh-pritchard** [comment]
Thanks @leezen I will give this a try
