### ISSUE TITLE
Implement recreate_on_update option to always recreate a resource and not to update

### ISSUE THREAD

**Issue by Tahvok** [pulumi/pulumi#6130]
I have a special use case.
I need a `recreate_on_update` option (name as an example).
This are my special requirements:
1. This option will make sure that the resource is **always** recreated instead of being updated (when possible).
2. However, I also need to make sure that the resource is deleted first before the new one is created.

This is a follow up to a conversation I had with @clstokes 

Consider the following use case:
I'm using a cloud instance that accepts cloud init configuration as an instance metadata. (See [container optimized os](https://cloud.google.com/container-optimized-os/docs/how-to/create-configure-instance#using_cloud-init_with_the_cloud_config_format) as example).

The cloud init in such case runs only when the instance is created for the first time.

I also need to make sure that only 1 instance is running at any given time.

If I want to update this metadata, right now pulumi will simply update the instance, and therefore the cloud init script will not run.

One approach would be to always create a new resource, by changing the resource name - but then the new resource is always created first before the old one is deleted (as the `delete_before_replace` option works only on the same resource), therefore there could be 2 instances running at any given time - which does not fulfill requirement 2.

Therefore an option to disable "updates" on a resource - and to always recreate it would help a lot.
Please consider adding it.

**Comment by leezen** [comment]
While the option you're asking for doesn't exist yet, in case you weren't aware of it, there's a CLI option `--target-replace` on `update` you could use as a potential workaround

**Comment by Raggey** [comment]
Just adding to this, I have a similar issue with AWS + S3 objects, pulumi wont detect if the underlying s3 object has changed, only if its been added/removed. A `recreate_on_update` flag would work nicely.

**Comment by lukehoban** [comment]
This issue is also being tracked in #6753.
