### ISSUE TITLE
Pulumi import fails for certain AWS CodeBuild projects

### ISSUE THREAD

**Issue by jeffreyjam** [pulumi/pulumi#6131]
Hi all, I created several AWS CodeBuild projects through the console which are valid and work properly. However, the 'pulumi import' command fails on them, saying the inputs failed to validate. Specifically the error message is:
```
error: aws:codebuild/project:Project resource 'codebuild-test-project' has a problem: expected artifacts.0.namespace_type to be one of [NONE BUILD_ID], got 
error: aws:codebuild/project:Project resource 'codebuild-test-project' has a problem: expected artifacts.0.packaging to be one of [NONE ZIP], got 
error: aws:codebuild/project:Project resource 'codebuild-test-project' has a problem: invalid value for environment.0.certificate (must end in .pem or .zip)
error: Preview failed: one or more inputs failed to validate
```
The problem fields were ones that I didn't specify and also aren't required. It looks like the import command doesn't properly handle missing values for those inputs.

I'm using the most recent version of the Pulumi CLI, v2.17.2.

**Comment by lukehoban** [comment]
Possibly related to https://github.com/pulumi/pulumi/issues/6131.

**Comment by AluBhorta** [comment]
I'm getting a similar error trying to import CodeBuild projects.

Below is the message I received:

```
Diagnostics:
  pulumi:pulumi:Stack (auto-wp-pulumi-ts-dev):
    error: preview failed
 
  aws:codebuild:Project (auto-wp-codebuild-project):
    error: aws:codebuild/project:Project resource 'auto-wp-codebuild-project' has a problem: expected artifacts.0.namespace_type to be one of [NONE BUILD_ID], got . Examine values at 'Project.Artifacts.NamespaceType'.
    error: aws:codebuild/project:Project resource 'auto-wp-codebuild-project' has a problem: invalid value for environment.0.certificate (must end in .pem or .zip). Examine values at 'Project.Environment.Certificate'.
    error: Preview failed: one or more inputs failed to validate
```

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in #8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
