### ISSUE TITLE
Engine throws with panic error when using Tags as below

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi#6135]
Creating this issue here as suggested from original issue, https://github.com/pulumi/pulumi-azure-nextgen/issues/216.

Adding this to Pulumi.AzureNextGen.Web.V20200601.Inputs.WebAppArgs for a Pulumi.AzureNextGen.Web.V20200601.WebApp, where the appServicePlanName variable is a simple string.

```
Tags = new InputMap<string>
{
    { $"hidden-related:/subscriptions/<subscriptionId>/resourceGroups/{resourceGroup.Name}/providers/Microsoft.Web/serverfarms/{appServicePlanName}", "empty" }
}
```

Error during preview when web app resource and app service plan resource have been imported already.

```
panic: fatal: An assertion has failed

goroutine 25 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assert(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v2/backend/display.translateDetailedDiff(0x1cbd6a4, 0x6, 0xc0012ac720, 0x5c, 0xc0019d7680, 0x22, 0xc001554a20, 0xc001554ab0, 0xc001554b40, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/detailedDiff.go:145 +0x237
github.com/pulumi/pulumi/pkg/v2/backend/display.renderDiff(0x1fd16c0, 0xc001509620, 0x1cbd6a4, 0x6, 0xc0012ac720, 0x5c, 0xc0019d7680, 0x22, 0xc001554a20, 0xc001554ab0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:322 +0x145
github.com/pulumi/pulumi/pkg/v2/backend/display.renderDiffResourcePreEvent(0x1cbd6a4, 0x6, 0xc0012ac720, 0x5c, 0xc0019d7680, 0x22, 0xc001554a20, 0xc001554ab0, 0xc001554b40, 0x0, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:351 +0x298
github.com/pulumi/pulumi/pkg/v2/backend/display.RenderDiffEvent(0x1cbf1ba, 0x7, 0x1cc772f, 0xc, 0x1b169a0, 0xc0012e4640, 0xc0018bbc18, 0x1cbc10e, 0x6, 0x100010000000000, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:122 +0x718
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowDiffEvents(0xc0014ca480, 0x11, 0x1cbf1ba, 0x7, 0xc00007eb40, 0xc00007ec00, 0x1cbc10e, 0x6, 0x100010000000000, 0x1, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/diff.go:85 +0x499
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowEvents(0xc0014ca480, 0x11, 0x1cbf1ba, 0x7, 0x7ffd794fcd3f, 0xc, 0xc000cc8e88, 0x8, 0xc00007eb40, 0xc00007ec00, ...)
        /Users/runner/work/pulumi/pulumi/pkg/backend/display/display.go:53 +0x178
created by github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).apply
        /Users/runner/work/pulumi/pulumi/pkg/backend/filestate/backend.go:487 +0x308
```

**Comment by mikhailshilkov** [comment]
Hi @WillooWisp
I'm trying to repro this locally but I haven't succeeded yet. I'm on pulumi 2.17.1 and Azure NextGen 0.4.0.

Here is my full stack as-is:

```cs
using Pulumi;
using Pulumi.AzureNextGen.Resources.Latest;
using Pulumi.AzureNextGen.Web.V20200601;
using Pulumi.AzureNextGen.Web.V20200601.Inputs;
using Pulumi.Random;

class MyStack : Stack
{
    public MyStack()
    {
        var randomString = new RandomString("random", new RandomStringArgs
        {
            Length = 12,
            Special = false,
            Upper = false,
        });

        var resourceGroup = new ResourceGroup("resourceGroup", new ResourceGroupArgs
        {
            ResourceGroupName = Output.Format($"cs-appservice-docker-{randomString.Result}"),
            Location = "WestUS"
        });

        var plan = new AppServicePlan("linux-apps", new AppServicePlanArgs
        {
            ResourceGroupName = resourceGroup.Name,
            Name = Output.Format($"linux-apps-{randomString.Result}"),
            Location = resourceGroup.Location,
            Kind = "Linux",
            Reserved = true,
            Sku = new SkuDescriptionArgs
            {
                Name = "B1",
                Tier = "Basic"
            }
        });
        
        var imageInDockerHub = "microsoft/azure-appservices-go-quickstart";
        
        var helloApp = new WebApp("hello-app", new WebAppArgs
        {
            ResourceGroupName = resourceGroup.Name,
            Location = plan.Location,
            Name = Output.Format($"hello-app-{randomString.Result}"),
            ServerFarmId = plan.Id,
            SiteConfig = new SiteConfigArgs
            {
                AppSettings = new[] 
                { 
                    new NameValuePairArgs
                    {
                        Name = "WEBSITES_ENABLE_APP_SERVICE_STORAGE",
                        Value = "false"
                    }
                },
                AlwaysOn = true,
                LinuxFxVersion = $"DOCKER|{imageInDockerHub}"
            },
            HttpsOnly = true,
            Tags =
            {
                { "hidden-related:/subscriptions/12345678-7a9e-424b-80b2-96babd57a8a2/resourceGroups/fake/providers/Microsoft.Web/serverfarms/fake", "empty" }
            }
        });
    }
}
```

The preview and update work just fine. Could you give it a try and/or spot the difference?

**Comment by WillooWisp** [comment]
Will do that!

**Comment by WillooWisp** [comment]
Okay, I have now managed to reproduce it quite easily with an app insights component resource instead of the web app resource, but same error I believe. It is important that the state has been imported first, otherwise the preview will not fail.

```
pulumi import -f $resources.json -s $stack --cwd $project --protect=false --diff --suppress-permalink

{
    "resources": [
        {
            "type": "azure-nextgen:resources/latest:ResourceGroup",
            "name": "rg-Dev123122",
            "id": "/subscriptions/<subscriptionId>/resourceGroups/Dev123122"
        },
        {
            "type": "azure-nextgen:insights/latest:Component",
            "name": "ai-Dev123122-AppInsights",
            "id": "/subscriptions/<subscriptionId>/resourceGroups/Dev123122/providers/microsoft.insights/components/Dev123122-AppInsights"
        }
    ]
}
```

```
var resourceGroup = new ResourceGroup($"rg-{resourceGroupName}",
  new ResourceGroupArgs
  {
      ResourceGroupName = resourceGroupName,
      Location = location,
  },
  new CustomResourceOptions
  {
      Protect = true
  }
);

var componentArgs = new ComponentArgs
{
    ApplicationType = "web",
    Kind = "web",
    Location = resourceGroup.Location,
    IngestionMode = IngestionMode.ApplicationInsights,
    ResourceGroupName = resourceGroup.Name,
    ResourceName = applicationInsightsName,
    RetentionInDays = 30,
    Tags =
    {
        { $"hidden-link:/subscriptions/{Environment.SubscriptionId}/resourceGroups/{resourceGroup.Name}/providers/Microsoft.Web/sites/{webAppName}", "Resource" }
    }
};

var component = new Component($"ai-{applicationInsightsName}", componentArgs,
    new CustomResourceOptions
    {
    }
);
```

**Comment by mikhailshilkov** [comment]
I can't import your resources because I don't have access to them. If there's nothing secret in there, could you send me the result of `pulumi stack export` at the point when the preview would fail? You can send it to mikhail@pulumi.com if you want to keep it private.

**Comment by WillooWisp** [comment]
`{
    "version": 3,
    "deployment": {
        "manifest": {
            "time": "2021-01-21T07:39:43.3848891Z",
            "magic": "bab0330a73211f1759bdaefaf31cc71832ed959388abc2a64cb88829949346a6",
            "version": "v2.18.0"
        },
        "secrets_providers": {
            "type": "passphrase",
            "state": {
                "salt": "v1:XMvDwNfFw1k=:v1:36NM8kLhf5wK1bAm:FHTJNL8nHTh/g52Bi5B12W3l9n3l1w=="
            }
        },
        "resources": [
            {
                "urn": "urn:pulumi:devstack::platform::pulumi:pulumi:Stack::platform-devstack",
                "custom": false,
                "type": "pulumi:pulumi:Stack"
            },
            {
                "urn": "urn:pulumi:devstack::platform::pulumi:providers:azure-nextgen::default_0_4_0",
                "custom": true,
                "id": "f6363fa0-7840-48e8-8660-d2fd01c5ab85",
                "type": "pulumi:providers:azure-nextgen",
                "inputs": {
                    "version": "0.4.0"
                },
                "outputs": {
                    "version": "0.4.0"
                }
            },
            {
                "urn": "urn:pulumi:devstack::platform::azure-nextgen:resources/latest:ResourceGroup::rg-devstack",
                "custom": true,
                "id": "/subscriptions/39c6a521-77eb-48fd-973d-bfbf7e482e46/resourceGroups/devstack",
                "type": "azure-nextgen:resources/latest:ResourceGroup",
                "inputs": {
                    "location": "northeurope",
                    "resourceGroupName": "devstack"
                },
                "outputs": {
                    "__inputs": {
                        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                        "ciphertext": "v1:s0umyL7YbKlXUdTP:Gri5jBqzf6N8vehtLC+RsAvgaeJ1jOz1zP2RktarJjrYcf+57MfzOauXQL5XaZ5fPr9ICRvz0QqcZNZGLzt6/dxSo4agKe7pKyImNZI="
                    },
                    "id": "/subscriptions/39c6a521-77eb-48fd-973d-bfbf7e482e46/resourceGroups/devstack",
                    "location": "northeurope",
                    "name": "devstack",
                    "properties": {
                        "provisioningState": "Succeeded"
                    },
                    "tags": {},
                    "type": "Microsoft.Resources/resourceGroups"
                },
                "parent": "urn:pulumi:devstack::platform::pulumi:pulumi:Stack::platform-devstack",
                "provider": "urn:pulumi:devstack::platform::pulumi:providers:azure-nextgen::default_0_4_0::f6363fa0-7840-48e8-8660-d2fd01c5ab85"
            },
            {
                "urn": "urn:pulumi:devstack::platform::azure-nextgen:insights/latest:Component::ai-devstack-AppInsights",
                "custom": true,
                "id": "/subscriptions/39c6a521-77eb-48fd-973d-bfbf7e482e46/resourceGroups/devstack/providers/microsoft.insights/components/devstack-AppInsights",
                "type": "azure-nextgen:insights/latest:Component",
                "inputs": {
                    "applicationType": "web",
                    "ingestionMode": "ApplicationInsights",
                    "kind": "web",
                    "location": "northeurope",
                    "resourceGroupName": "devstack",
                    "resourceName": "devstack-AppInsights",
                    "retentionInDays": 30,
                    "tags": {
                        "hidden-link:/subscriptions/39c6a521-77eb-48fd-973d-bfbf7e482e46/resourceGroups/devstack/providers/Microsoft.Web/sites/devstack": "Resource"
                    }
                },
                "outputs": {
                    "__inputs": {
                        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                        "ciphertext": "v1:2t+1RmvZ8DxpRGOV:uL2dQ9yr119OT1CjW2GlLxtL9e0JLvMT6dced/OhQjYbFzdb/y6/tm8lzHDv9Z8R9RZlnhTFEFzgaP9tlj6OkR1b6+LV9gnN8CZHQBuQRfmQVFASqP5Pub8IFVRK4XJpCAmmIMIQUrJSXK6wix3KuN3wWDiaDGDpPY3+7wTnXkKLRrm/UkFvIz+3wPpfv+nq5KIH76O6fzaxNC/z9Yt61eYkO/JwhUHmU3PCVg8DXBG4oMz2393mDjh8YJSEhvUnZUGbAmA4bAULgxlGYF+LIuNOYjC2qGMFz9qwiT5kJ2ZZOG5Phlj4o5rjaFAB1vcYLxOnpZxfWUO/uK1+0627w+m6qHin7RMc1WY0SZDr4a2KpFDPakyFJjJ53IKVs0NQUHJPrlhc9m6GRAd3QKr+4H4grpMd5CPlPyAA7xzpydn85GrngV17KmCJduhsTZ9G3GjxXtYf6oe6vmPK/EgQrGB39MfLUomi0KoZgJAx90jGiID+"
                    },
                    "appId": "9cce0f3f-5dd6-4a31-b053-5f13d663f4fb",
                    "applicationId": "devstack-AppInsights",
                    "applicationType": "web",
                    "connectionString": "InstrumentationKey=45e1abc2-4866-4d36-9474-77cd0c9eb4c2;IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/",
                    "creationDate": "2019-10-08T14:13:09.5672818+00:00",
                    "id": "/subscriptions/39c6a521-77eb-48fd-973d-bfbf7e482e46/resourceGroups/devstack/providers/microsoft.insights/components/devstack-AppInsights",
                    "ingestionMode": "ApplicationInsights",
                    "instrumentationKey": "45e1abc2-4866-4d36-9474-77cd0c9eb4c2",
                    "kind": "web",
                    "location": "northeurope",
                    "name": "devstack-AppInsights",
                    "provisioningState": "Succeeded",
                    "retentionInDays": 30,
                    "tags": {
                        "hidden-link:/subscriptions/39c6a521-77eb-48fd-973d-bfbf7e482e46/resourceGroups/devstack/providers/Microsoft.Web/sites/devstack": "Resource"
                    },
                    "tenantId": "39c6a521-77eb-48fd-973d-bfbf7e482e46",
                    "type": "microsoft.insights/components"
                },
                "parent": "urn:pulumi:devstack::platform::pulumi:pulumi:Stack::platform-devstack",
                "provider": "urn:pulumi:devstack::platform::pulumi:providers:azure-nextgen::default_0_4_0::f6363fa0-7840-48e8-8660-d2fd01c5ab85"
            }
        ]
    }
}`

**Comment by mikhailshilkov** [comment]
Okay, I reproduced the problem now, thank you.

The culprit is your usage of an output (`resourceGroup.Name`) inside string formatting:

```cs
$"hidden-link:/subscriptions/{System.Environment.GetEnvironmentVariable("ARM_SUBSCRIPTION_ID")}/resourceGroups/{resourceGroup.Name}/providers/Microsoft.Web/sites/{webAppName}"
```

The actual value becomes 

```
tags.hidden-link:/subscriptions//resourceGroups/Pulumi.Output`1[System.String]/providers/Microsoft.Web/sites/dev
```

We fail to parse that funky resource group "name" `Pulumi.Output`1[System.String]`.

To work around the issue, please change the string not to use outputs:

```cs
$"hidden-link:/subscriptions/{System.Environment.GetEnvironmentVariable("ARM_SUBSCRIPTION_ID")}/resourceGroups/rg-{resourceGroupName}/providers/Microsoft.Web/sites/{webAppName}"
```

or produce the whole `Tags` value inside a `resourceGroup.Name.Apply(name => ... /* create tags here */`).

Of course, we still need to fix the panic, but I believe it shouldn't block you.

**Comment by WillooWisp** [comment]
Ahh, of course, I guess the error fooled me into thinking it was something else. Thanks!
