### ISSUE TITLE
[Automation API] [go] Typed Stack Outputs

### ISSUE THREAD

**Issue by Pondidum** [pulumi/pulumi#6152]
I'd love to be able to strong type my stack outputs. Currently, I can get an `auto.OutputMap`, but this loses type information.

Current implementation:
```go
outputs, err := stack.Outputs(ctx)
if err != nil {
	return err
}
```

I'd like to be able to pass a custom object for the `json.Unmarshal` call:
```go
type MyStackOutputs struct {
	SecurityGroups []string
}

var outputs MyStackOutputs
if err := stack.Outputs(ctx, &outputs); err != nil {
	return err
}
```

**Comment by mikhailshilkov** [comment]
Dupe of #5689
