### ISSUE TITLE
[sdk/go] Consider safer Elem/Index/MapIndex functions instead of allowing these to panic

### ISSUE THREAD

**Issue by jzaron** [pulumi/pulumi#6154]
I need to extract an AWS EKS cluster security group ID to provide security group information for a launch template. Tried to do it like this:

```
eksCluster := eks.NewCluster(...)
securityGroup := eksCluster.VpcConfig.ClusterSecurityGroupId().Elem()
launchTemplateArgs := ec2.LaunchTemplateArgs{
    (...),
    NetworkInterfaces: ec2.LaunchTemplateNetworkInterfaceArray{
        ec2.LaunchTemplateNetworkInterfaceArgs{
	    DeviceIndex: pulumi.IntPtr(0),
	    SecurityGroups: pulumi.StringArray{
                eksCluster.VpcConfig.ToClusterVpcConfigOutput().ClusterSecurityGroupId().Elem(),
	    },
	},
    },
}
launchTemplate, err := ec2.NewLaunchTemplate(ctx, (...), &launchTemplateArgs)
```
When I run `pulumi up` it ends up with:

```
Diagnostics:
  pulumi:pulumi:Stack (create-cluster-jakubz-test):
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbb7925]
    goroutine 203 [running]:
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.StringPtrOutput.Elem.func1(0x0, 0x0, 0x0)
        /home/jzaron/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.17.2/go/pulumi/types_builtins.go:6623 +0x5
    reflect.Value.call(0xa25b620, 0xc11f8b0, 0x13, 0xc04dd80, 0x4, 0xc000252cd8, 0x1, 0x1, 0x10, 0xc0004dd370, ...)
        /usr/lib/go-1.14/src/reflect/value.go:460 +0x8ab
    reflect.Value.Call(0xa25b620, 0xc11f8b0, 0x13, 0xc000252cd8, 0x1, 0x1, 0xa3be1a0, 0xc0004dd370, 0xc0008d0bd8)
        /usr/lib/go-1.14/src/reflect/value.go:321 +0xb4
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.makeContextful.func1(0xc000252cc0, 0x2, 0x2, 0xc000252cc0, 0x3, 0xc0004aa9f0)
        /home/jzaron/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.17.2/go/pulumi/types.go:286 +0x7c
    reflect.callReflect(0xc000145650, 0xc0008d0bd8, 0xc0008d0bc0)
        /usr/lib/go-1.14/src/reflect/value.go:549 +0x322
    reflect.makeFuncStub(0xc32c7c0, 0xc000052098, 0x0, 0x0, 0x0, 0xa16fec0, 0x0, 0xc000252c90, 0xc0008d0e30, 0x4b33fb, ...)
        /usr/lib/go-1.14/src/reflect/asm_amd64.s:20 +0x42
    reflect.Value.call(0xc00040e660, 0xc000145650, 0x13, 0xc04dd80, 0x4, 0xc0008d0f60, 0x2, 0x2, 0xa475160, 0xa16fec0, ...)
        /usr/lib/go-1.14/src/reflect/value.go:460 +0x8ab
    reflect.Value.Call(0xc00040e660, 0xc000145650, 0x13, 0xc000123f60, 0x2, 0x2, 0xc000676040, 0x1, 0x1)
        /usr/lib/go-1.14/src/reflect/value.go:321 +0xb4
    github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*OutputState).ApplyTWithContext.func1(0xc000192e00, 0xc32c7c0, 0xc000052098, 0xc3ad040, 0xc000192e70, 0xc00040e660, 0xc000145650, 0x13)
        /home/jzaron/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.17.2/go/pulumi/types.go:410 +0x28b
    created by github.com/pulumi/pulumi/sdk/v2/go/pulumi.(*OutputState).ApplyTWithContext
        /home/jzaron/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.17.2/go/pulumi/types.go:398 +0x1e0
    exit status 2

    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

The problem seems to be that the Elem() function causes too early pointer dereference. I can't just use value returned by `ClusterSecurityGroupId()` because it returns `StringPtrOutput` . This is incompatible with the type I need to create a launch template, as `LaunchTemplateArgs -> NetworkInterfaces -> SecurityGroups` is of `StringArray` type, so with `StringPtrOutput` code won't compile at all.

The problem pops out if the cluster does not exist at the time of running `pulumi up`. If the cluster already exists, all works fine, but it's worth nothing.

I tried to find some help on Pulumi Slack, but after some discussion was told to report a bug.

## Expected Behavior
`pulumi up` causes normal execution with no runtiime error, first it creates AWS EKS cluster, then creates launch template using cluster security group ID.

## Current Behavior
`pulumi up` ends up with runtime error.

## Steps to Reproduce
Take Pulumi Golang SDK. Try to create an EKS cluster, and then to create a launch template with interface binded to cluster's default security group. Code stub is above (if needed, I can provide full code, just don't want to make this post too heavy).

## Context (Environment)
I need to extract an AWS EKS cluster security group ID to provide security group information for a launch template. I use a custom AMI for worker nodes, so AWS forces me to define a launch template.

**Comment by EvanBoyle** [comment]
What happens if you manually author the apply rathen than calling `elem`?

```go
eksCluster.VpcConfig.ToClusterVpcConfigOutput().ClusterSecurityGroupId().ApplyString(func(v string*) string {
result := ""
if v != nil {
result = &v
}
return result
}
```

**Comment by jzaron** [comment]
Thanks for the hint :) Works with:

```
eksCluster.VpcConfig.ClusterSecurityGroupId().ApplyString(func(v *string) string {
    result := ""
    if v != nil {
        result = *v
    }
    return result
}
```

But shouldn't the `Elem()` method check for null?

**Comment by lukehoban** [comment]
Retitled the issue.  Two things we could consider here:
1. Change to `Elem`/`Index` to return zero values instead of panicing on invalid operation (nil pointer dereference or out of bounds array index).
2. New safer (and more flexible) variants like `ElemOr`/`IndexOr`/`MapIndexOr` which take an additional argument to use as the default value to return in case the elem/index operation is not valid.

We should likely make both changes.  (1) is a behaviour change, but only in that it allows programs that previously panic'd to succeed - so cannot be breaking.

**Comment by lukehoban** [comment]
> We should likely make both changes.

On second thought - (1) is the only critical change to make.  #6338 makes that change.

The other variants like `ElemOr` are already fairly easy to write manually with `ApplyT`, and there are several version of `ElemOr` that could make sense - so no need to generate all of these by default - users can just use `ApplyT` if they need more flexibility than the default `Elem`/`Index`.

* `func (o BoolPtrOutput) ElemOr(defaultVal bool) BoolOutput`
* `func (o BoolPtrOutput) ElemOr(defaultFunc func () bool) BoolOutput`
* `func (o BoolPtrOutput) ElemOr(defaultVal BoolInput) BoolOutput`
* `func (o BoolPtrOutput) ElemOr(defaultFunc func () BoolInput) BoolOutput`
