### ISSUE TITLE
name_prefix broken?

### ISSUE THREAD

**Issue by rtoma** [pulumi/pulumi#6155]
The resource parameter `name_prefix` seem broken. I noticed this with aws.LogGroup. Haven't tested with other resources.

Actually this parameter is pretty pointless, since Pulumi does auto naming by default. Maybe just remove this parameter?

This is the code I use:

```
import pulumi_aws as aws

aws.cloudwatch.LogGroup('lg', name_prefix='pulumi-nameprefix-test')
```

This issue may be related to https://github.com/pulumi/pulumi-terraform/issues/210 where it was mentioned but also marked as resolved. Regression?

## Expected Behavior

Pulumi creates the log group with a name starting with the specified prefix. Just like auto naming when name_prefix is omitted.

## Current Behavior

Fails with:

```
error: aws:cloudwatch/logGroup:LogGroup resource 'lg' has a problem: ConflictsWith: "name": conflicts with name_prefix
```

Even though I have not specified the name parameter. Only resource_name and name_prefix.

## Steps to Reproduce

1. Use included snippet above
2. Pulumi up ftw
3.
4.

**Comment by lukehoban** [comment]
In https://github.com/pulumi/pulumi-aws/issues/143#issuecomment-423695936, it was claimed that this should not longer happen.  cc @pgavlin.

**Comment by tlinhart** [comment]
I've just encountered the exact same issue as described above.

**Comment by dferretti** [comment]
Same here, using the dotnet SDK for Pulumi 3.1.0, Pulumi.Aws 4.1.0. The Autoscaling.Group resource is breaking similarly for me using NamePrefix.

**Comment by dgivens** [comment]
Just a +1 with aws.autoscaling.Group in typescript SDK, Pulumi 3.4.0, AWS 4.7.0.

**Comment by iwahbe** [comment]
I just tested this with `aws: 4.27.1` and `pulumi 3.17.0`. It seems to just work. 
```python
import pulumi_aws as aws
import pulumi
lg = aws.cloudwatch.LogGroup('lg', name_prefix='pulumi-nameprefix-test')
pulumi.export('name', lg.name)
```
```
Updating (dev)

View Live: https://app.pulumi.com/iwahbe/6155-repro/dev/updates/3

     Type                        Name            Status      
 +   pulumi:pulumi:Stack         6155-repro-dev  created     
 +   └─ aws:cloudwatch:LogGroup  lg              created     
 
Outputs:
    name: "pulumi-nameprefix-test20211110191147084700000001"

Resources:
    + 2 created

Duration: 5s
```
If this is still a problem for you, please reopen the issue.
