### ISSUE TITLE
Add pagination options to `pulumi stack history` 

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#6168]
#### Context

`pulumi stack history` currently returns the full history for a stack. This can be a lengthy response for a very active stack that has been around for a longtime. It can also be useful to just get the details of the _most recent_ deployment without having to parse through a large response.

#### Proposal

Add `--page` and `--page-size` arguments to `pulumi stack history` for the state backends that support it. 

With those, `--page 1 --page-size 1` would allow a user to get just the most recent deployment details.

**Comment by EvanBoyle** [comment]
@cnunciato @clstokes I just added a `--limit` flag via #6257 that solves for half of this. `--limit 1` lets you grab the most recent entry. 

`--limit N` translates to `--page-size N --page 1`

It would definitely offer greater flexibility to do as you suggest and instead expose both `--page-size` and `--page`. We have another 10 days until the next CLI release so there is time to amend the functionality here, but after that, it becomes a bit harder. I'd be happy to make the change if we think it's necessary.

**Comment by cnunciato** [comment]
It’d be great to support both options, yeah. These are the options we support across all paginated APIs in the Service.

**Comment by komalali** [comment]
@EvanBoyle are you gonna take this?

**Comment by EvanBoyle** [comment]
Done https://github.com/pulumi/pulumi/pull/6292
