### ISSUE TITLE
pulumi/pulumi-dotnet:latest is not deterministic

### ISSUE THREAD

**Issue by AliBazzi** [pulumi/pulumi#6185]
## Expected Behavior
when I pull pulumi/pulumi-dotnet:latest image, I have to get .net distribution consistently 

## Current Behavior

After each release of the image and tagging it with `latest` on your end, I get .net 5 or .net 3.1, depends on the latest tagger win.

Sometimes `ubi` distribution tag the latest, which cause .net sdk version to be .net 5

And sometimes `debian` tag the latest, which cause .net sdk version to be .net core 3.1

## Steps to Reproduce

```
docker container run -it pulumi/pulumi-dotnet:2.18.0-ubi /bin/bash
[root@a992fd8d19f6 projects]# dotnet --list-sdks
5.0.102 [/usr/lib64/dotnet/sdk]
```

```
docker container run -it pulumi/pulumi-dotnet:2.18.0-debian /bin/bash
root@f2876a3efd1c:/pulumi/projects# dotnet --list-sdks
3.1.405 [/usr/share/dotnet/sdk]
```

## Context (Environment)
this behaviour prevents me from adopting `latest` tag, since it's not deterministic for me to set the project target as expected

I'm not sure also why `ubi` and `debian` images have different .net sdks version

**Comment by AliBazzi** [comment]
if I target multiple runtimes with the .net Pulumi project like:

```
<TargetFrameworks>netcoreapp3.1;net5.0</TargetFrameworks>
```

I'm getting the following error using `pulumi/pulumi-dotnet` container:

```

Diagnostics:
--
  pulumi:pulumi:Stack (xxx):
  Unable to run your project
  Your project targets multiple frameworks. Specify which framework to run using '--framework'.
   
  error: an unhandled error occurred: Program exited with non-zero exit code: 1


```

**Comment by AliBazzi** [comment]
Also, worth mentioning a suggestion to have `ubi-latest` and `debian-latest` as tags, because when this bug is fixed, it's not clear what is the intended behaviour of `latest` tag. 

Is debian or ubi your default option for the Pulumi sdk container ?

**Comment by stack72** [comment]
Hi @AliBazzi 

So my apologies that this happened - this was 2 specific bugs in our docker container build:

1. We created a pulumi/pulumi-dotnet:latest container (based on debain)
2. We then created the ubi and debian containers and then tagged those as latest as well - which wasn't correct
That has now been corrected!

The ubi container didn't scope the dotnet-sdk to 3.1 so that was why you saw 5.x 
That has also now been corrected

So the containers are as follows:

```
▶ docker container run -it pulumi/pulumi-dotnet:2.20.0-ubi /bin/bash
[root@269e393fc870 projects]# dotnet --list-sdks
3.1.111 [/usr/lib64/dotnet/sdk]
```

```
▶ docker container run -it pulumi/pulumi-dotnet:2.20.0-debian /bin/bash
root@13c7444c3ec6:/pulumi/projects# dotnet --list-sdks
3.1.405 [/usr/share/dotnet/sdk]
```

```
▶ docker container run -it pulumi/pulumi-dotnet:latest /bin/bash
root@f9c054becbff:/pulumi/projects# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@f9c054becbff:/pulumi/projects# dotnet --list-sdks
3.1.405 [/usr/share/dotnet/sdk]
```

deleted and re-pulled `pulumi/pulumi-dotnet:latest` to ensure it's a deterministic build

```
▶ docker container run -it pulumi/pulumi-dotnet:latest /bin/bash
root@4724266d3268:/pulumi/projects# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

I believe we are in better shape here now - I apologise again, thank you for bringing this to our attention

Paul

**Comment by AliBazzi** [comment]
Thanks Paul,

It's fixed on my side after testing.
