### ISSUE TITLE
Lambda nodejs local import

### ISSUE THREAD

**Issue by Fanda36** [pulumi/pulumi#6186]
Hi,

when I use local library in Lambda nodejs, then I can't deploy stack (it started infinite loop). If I remove import of my local file `import {getMetadata} from "../lib/s3";` then everything works fine. But I'd like to to use my local `*.ts` libraries.

```js
// Copyright 2016-2019, Pulumi Corporation.  All rights reserved.
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

////////////////////////////////////////////////////////////////
// local s3.ts file
import {getMetadata} from "../lib/s3";
////////////////////////////////////////////////////////////////


const cluster = awsx.ecs.Cluster.getDefault();

const bucket = new aws.s3.Bucket();


// A task which runs a containerized FFMPEG job to extract a thumbnail image.
const myTask = new awsx.ecs.FargateTaskDefinition("myTask", {
    container: {
        image: awsx.ecs.Image.fromPath("myTask", "./docker"),
    },
});


export const bucketName = bucket.id;

bucket.onObjectCreated("onNewFile", new aws.lambda.CallbackFunction<aws.s3.BucketEvent, void>("onNewFile", {
    // Specify appropriate policies so that this AWS lambda can run EC2 tasks.
    policies: [
        (...)
    ],
    callback: async bucketArgs => {

        if (!bucketArgs.Records) {
            return;
        }

        for (const record of bucketArgs.Records) {
            const sourceFileKey = record.s3.object.key;

////////////////////////////////////////////////////////////////////////////////////////////////
// I'd like to use my local libraries in Lambda
////////////////////////////////////////////////////////////////////////////////////////////////
            const metadata = await getMetadata(bucketName.get(), sourceFileKey);
            console.log("metadata:", metadata);

            await myTask.run({
                cluster,
                overrides: {
                    containerOverrides: [{
                        name: "container",
                        environment: [
                            {name: "S3_BUCKET", value: bucketName.get()}
                           (...)
                        ],
                    }],
                },
            });

            console.log(`Running convert task.`);
        }
    },
}), {filterPrefix: "uploads/"});

```

## Expected Behavior
Stack will be published

## Current Behavior
Infinite stack init (the image is after 30 minutes). If I remove the import of my local `s3.ts` file, then stack is deployed without any problems.

![image](https://user-images.githubusercontent.com/3972954/105639286-99d62700-5e77-11eb-8497-a38a5d64c663.png)

## Steps to Reproduce
See my code example in the top.

## Context (Environment)
I'd like to use local `*.ts` files in Lambda function.

**Comment by mikhailshilkov** [comment]
Importing external functions should be possible - with some gotcha's as described in https://www.pulumi.com/docs/tutorials/aws/serializing-functions/

Is it possible to share the source code behind `getMetadata` and the rest of `../lib/s3`? Ideally, it would be an isolated repro program.

**Comment by Fanda36** [comment]
You can try this. https://github.com/Fanda36/test I hope it is working example. :) (I did big clean up)

**Comment by Fanda36** [comment]
There is maybe too many js code to optimize so it just take really long time.

**Comment by mikhailshilkov** [comment]
@Fanda36 You can get to the AWS SDK using the Pulumi package with `aws.sdk.S3...` where `aws` comes from `import * as aws from "@pulumi/aws";`. It's been a while since I tried but I believe this will save you from serializing the whole AWS SDK (which is huge).

**Comment by mikhailshilkov** [comment]
Here is a relevant example: https://github.com/pulumi/examples/blob/e942d6130cd402d48db56889581ce2db1879803f/aws-ts-scheduled-function/index.ts

**Comment by Fanda36** [comment]
Thank you. It looks good. I am migrating from Serverless to to Pulumi. I use my source codes from Serverless but now I know how to use AWS SDK in Pulumi.
