### ISSUE TITLE
add Yandex Cloud Pulumi Resource Provider

### ISSUE THREAD

**Issue by rgeraskin** [pulumi/pulumi#6187]
Hello. Please add Yandex Cloud Pulumi Resource Provider

Terraform Resource Provider links: 
https://registry.terraform.io/providers/yandex-cloud/yandex/latest/docs
https://github.com/yandex-cloud/terraform-provider-yandex

**Comment by artemkoru** [comment]
Hi, we also need it too. Please add it!

Thanks!

**Comment by aladmit** [comment]
@rgeraskin Have you tried to convert terraform provider to pulumi provider with bridge? Is it hard to support?

https://github.com/pulumi/pulumi-terraform-bridge#adapting-a-new-terraform-provider

**Comment by rgeraskin** [comment]
@aladmit no, I didn't try

**Comment by aladmit** [comment]
Good news everyone! We have a provider for Yandex.Cloud now https://github.com/aladmit/pulumi-yandex

**Comment by stack72** [comment]
Hi @aladmit 

Would you be interested in making this an "official" Pulumi provider?

Paul

**Comment by rauanmayemir** [comment]
@stack72 We've been monkey patching the tf-bridge-gen here: https://github.com/buhta/pulumi-yandex.
We took `resources.go` from @aladmit's repo and cleaned it up a bit, fixing typos and also including new endpoints from the latest tf provider.

It works great, but some aspects that need improving:
1. Release pipeline and branching for new versions of the provider
2. Currently everything is under a single package, it might be better to split everything up by modules (single module works great for us, though)

**Comment by aladmit** [comment]
Hi @stack72 Yeah, that sounds interesting. What do we need to do to make it "official"?

Hi @rauanmayemir Glad my work helped you somehow 🎉 I hope we would maintain new the "official" provider together. What did you patch in tf-bidge-gen?

**Comment by rauanmayemir** [comment]
@aladmit Minor typos, like ServiceCccount or StorageObjet.

**Comment by stack72** [comment]
Hi @aladmit can you drop me a mail on stack72 @ pulumi.com and we can work it out?

Paul

**Comment by aladmit** [comment]
@stack72 Yeah, sure. I've dropped you an email.

**Comment by stack72** [comment]
Hi friends,

I am happy to say that, thanks to @aladmit and @rauanmayemir, we now have an official Pulumi Yandex Provider

I just published v0.1.0 of the provider. Links are as follows:

* https://www.npmjs.com/package/@pulumi/yandex
* https://pypi.org/project/pulumi-yandex/
* https://www.nuget.org/packages/Pulumi.Yandex
* https://pkg.go.dev/github.com/pulumi/pulumi-yandex/sdk@v0.1.0/go/yandex
