### ISSUE TITLE
[Python] Avoid using the translation tables when using the data class types

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#6199]
In https://github.com/pulumi/pulumi/issues/3771 we implemented used Python's dataclass support to provide a richer type experience. However, when using these data class types, inputs/outputs are still pushed through `translate_output_property` and `translate_input_property` for camelcase/snakecase translation. As an alternative to making a completely breaking change (as suggested in https://github.com/pulumi/pulumi/issues/3151), we could at least try to detect if the type is a raw `dict` or a data class. If it's the latter, then don't bother using the translation tables for any nested values since the assumption is at this point, the user knows what she is doing in terms of the actual keys/values.

**Comment by justinvp** [comment]
The snake_casing issues from https://github.com/pulumi/pulumi/issues/3151 have been addressed in the 3.0-based provider Python SDKs (with https://github.com/pulumi/pulumi/pull/6695 and https://github.com/pulumi/pulumi/pull/6696).

Preview releases that include the fix are now available for the following providers:

- pulumi-kubernetes 3.0.0-beta.2
- pulumi-azure 4.0.0-beta.2
- pulumi-gcp 5.0.0-beta.2
- pulumi-azure-native 1.0.0-beta.2
- pulumi-random 4.0.0-beta.2
- pulumi-azuread 4.0.0-beta.2
- pulumi-aws 4.0.0-beta.2
