### ISSUE TITLE
Add flag or command to print provider and package versions

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#6217]
#### Problem

It can be helpful in troubleshooting to know the _full_ list of provider and package versions that are in use for a particular stack. Currently this can be gathered from `pulumi stack export` and the runtime-specific package manager (e.g. `npm ls`), but this should be easier for the end user, especially the versions already in their state file.

#### Suggestions for a fix

Add a `--all` flag to `pulumi version` or a separate `pulumi stack version` command to print this information (or both?) if the user is in a project directory and should support `-s stack` flag if not.

e.g.

```
 $ pulumi version --all -s my-org/my-proj/my-stack
v2.18.2

Current stack is dev.

Current stack providers (4):
    TYPE                                     NAME
    pulumi:pulumi:Stack                      p-ts-bucket-dev
    ├─ pulumi:providers:cloudflare           default_0_0_1
    └─ pulumi:providers:aws                  default_3_25_1

Providers from package manager:
<output from `npm ls`, `pip3 list`, etc>
```

**Comment by emiliza** [comment]
Marking as resolved, this is possible now by using `pulumi about`
