### ISSUE TITLE
Cant find go binary when GOPATH has multiple folders

### ISSUE THREAD

**Issue by pintonunes** [pulumi/pulumi#6223]
According to https://golang.org/cmd/go/#hdr-GOPATH_environment_variable, GOPATH can be a list of folders like the PATH environment variable.

In the code seems that you're not taking that into account.
https://github.com/pulumi/pulumi/blob/d3187d630f9555d7fae2c76ce33caa18b6de00b4/sdk/go/common/util/executable/executable.go#L35-L38

Quick test:
![image](https://user-images.githubusercontent.com/37883272/106299589-3ec47b80-624d-11eb-9349-21042477d4b1.png)

**Comment by ynden** [comment]
Hi, can you assign it to me please?
Thanks!

**Comment by leezen** [comment]
@ynden Sure -- I assume you intend to take a stab at this?

**Comment by ynden** [comment]
Yes, I would like to give it a shot.

**Comment by leezen** [comment]
Great! Thank you!

**Comment by stack72** [comment]
Closed via #6506
