### ISSUE TITLE
Warn on update when using any NPM modules from global cache (service scenario)

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#623]
`pulumi update` will work locally whether or not an NPM package is in the `node_modules` folder, as NPM will happy load them from a global cache.

However, when using the hosted service, the update will fail since the required packages are not found in the upload archive.

We should detect and warn in these situations, as the update will fail. (The fix is to run `npm` or `yarn` install for the packages that are picked up from the cache.)

**Comment by ellismg** [comment]
Given that all deployments happen locally now, this is no longer interesting.
