### ISSUE TITLE
`pulumi history` should have the option to only retrieve last entry

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#6252]
`pulumi history --n=1` or equivalent

**Comment by stack72** [comment]
@EvanBoyle there is a related issue here - https://github.com/pulumi/pulumi/issues/2412

Does this sound the correct idea?

**Comment by EvanBoyle** [comment]
@stack72 related, but this is a very specific improvement needed for #6253 so I'd like to keep it open.
