### ISSUE TITLE
Cannot re-register module aws:accessanalyzer/analyzer@3.27 

### ISSUE THREAD

**Issue by MatiasNMont** [pulumi/pulumi#6258]
When I run pulumi preview command I receive the follow message 
`Error: Cannot re-register module aws:accessanalyzer/analyzer/analayzer@3.27. Previous registration was [Object Object], new registration was [Object Object]
            at register (~/myproject/node_module/@pulumi/pulumi/runtime/rpc.js:549:23)
            at Object.registerResourceModule (~/myproject/node_module/@pulumi/pulumi/runtime/rpc.js:613:5)
            at Object.<anonymous> ~/myproject/node_modules/node_modules/@pulumi/accesanalyzer/index.ts:24:15)
           at Module._compile(internal/modules/cjs/loader.js:999:30)`

## Expected Behavior
Pulumi previous shuold be succesful

## Current Behavior
Error  Cannot re-register module aws:accessanalyzer/analyzer@3.27

**Comment by leezen** [comment]
Could you please provide the program you're executing along with your `package.json` and `package-lock.json` or `yarn.lock`?

**Comment by justinvp** [comment]
We may need to change the registration implementation to be tolerant of re-registrations at the same version.

**Comment by MatiasNMont** [comment]
sorry for the delay, I  created  a [custom component resource A](https://pulumi.awsworkshop.io/30_modern_iac_ts/45_componens/10_create_component.html) and I'm using this resource from other component (component B ). Component A has the next dependencies in the package.json:
  `"@pulumi/aws": "^3.3.0",
        "@types/chai": "^4.2.12",
        "@types/mocha": "^8.0.3",
        "@types/sinon-chai": "^3.2.5",
        "@typescript-eslint/parser": "^4.3.0",`

Componet that it using A has the next dependencies: 
`"@pulumi/aws": "^3.0.0",
        "@pulumi/pulumi": "^2.0.0",
        "@customRepo/componentA"
        "ts-node": "^9.0.0",`
