### ISSUE TITLE
runtime stalls when using pulumi with Rosetta2 emulation on Apple M1

### ISSUE THREAD

**Issue by kherings** [pulumi/pulumi#6261]
when creating a stack in an Rosetta2 environment
```pulumi stack init local```

the execution randomly faults with 

```assertion failed [abi_info.kind == AbiKind::TranslatedCode]: emulated forward to an arm pc that isn't in translated code. arm_pc=0x1078984d8 abi_kind=6 emulation_interval=[0x107904ce4,0x107904cf8) instruction_interval=[0x107904cd0, 0x107904cf8) x86_rip=0x4054477 (ThreadContextRegisterState.cpp:677 move_to_instruction_boundary)```

It is an Rosetta2 issue - but if you could somehow check if there is a way to 'avoid' the instructions that trigger the fault it would be great. 

## Expected Behavior
Not to crash 

## Current Behavior
random crashes

## Steps to Reproduce
1. setup environment as explained in here - https://github.com/pulumi/pulumi/issues/4868#issuecomment-765266392
2. keep on using the environment until randomly the error occurs

## Context (Environment)
Potentially connected  issue  can be found here: https://github.com/golang/go/issues/42700

**Comment by stack72** [comment]
Hi @kherings 

Sorry we didn't get back to you sooner on this - we have just completed the work that allow the latest Pulumi CLI (and plugin binaries) to be installed on apple arm machines. I believe this will now work under rosetta 2 as we needed to upgrade our version of Go to support this

Please let me know if there are any issues

Paul

**Comment by stack72** [comment]
I haven't heard back about this and it's been 6 days since we released our arm based tooling

Please let me know if there's an issue

Paul
