### ISSUE TITLE
IgnoreChanges sets properties to null when used on a property with a secret value

### ISSUE THREAD

**Issue by UnoSD** [pulumi/pulumi#6272]
Example of the `IgnoreChanges` usage here:
https://github.com/UnoSD/TvShowRss/blob/66ade7fc736a169d302dcceb3622edd519c4b08b/Infrastructure/Program.cs#L482

When setting a connection string as secret here:
https://github.com/UnoSD/TvShowRss/blob/66ade7fc736a169d302dcceb3622edd519c4b08b/Infrastructure/Program.cs#L528

The connection string gets used to generate a SAS token then a URL, therefore the URL infers the "secrecy".

That URL gets assigned to a property of a resource, when running `pulumi up`, the REST API gets invoked without the URL `value`; making the whole property ignored (IgnoreChanges = appSettings[0]), calls the REST API with a `null`.

All that results in an InternalServerError, that could give other issues/different results with other non-Azure providers, so I believe the issue belongs to the generic Pulumi repo.

API call body when ignoring appSetting[0].value:

```json
"appSettings": [
	{
	  "name": "WEBSITE_RUN_FROM_PACKAGE"
	},
	{
	  "name": "OtherSetting",
	  "value": "value"
	}
]
```

API call body when ignoring the whole appSetting[0]:

```json
"appSettings": [
	null,
	{
	  "name": "OtherSetting",
	  "value": "value"
	}
]
```

## Expected Behavior
Changes to the value/the property should be ignored and should not produce an invalid API request.

## Current Behavior
When IgnoreChanges is enabled, the whole property gets picked up for update and an invalid value is sent to the provider

## Steps to Reproduce
1. Create a property of a resource as set its value to a secret output
2. pulumi up
3. Set IgnoreChanges on that property
4. pulumi up

Making the value non-secret fixes the issue, but the SAS token should remain encrypted in the backend

Thank you

**Comment by williamsbdev** [comment]
I'm also experiencing this issue with another provider/resource. I'm currently managing K8s Deployments and I want to do the image update with `kubectl` to perform a faster deploy. Thus I want to add the following so Pulumi will not see this as a diff:

```
ignoreChanges: ['spec.template.spec.containers[0].image'],
```

However, when I do so, about half of the Deployments show this for the update:

```
~ kubernetes:apps/v1:Deployment: (update)
        [id=<deploymentNamespace>/<deploymentId>]
        [urn=urn:pulumi:<stackName>::<projectName>::kubernetes:apps/v1:Deployment::<deploymentName>]
        [provider=urn:pulumi:<stackName>::<projectName>::pulumi:providers:kubernetes::k8sProvider::<guid>]
      ~ spec: {
          ~ template: {
              ~ spec: {
                  ~ containers: [
                      ~ [0]: {
                              - image: <null>
                            }
                    ]
                }
            }
        }
```

When I look in the state file, I see something like this:

```
"containers": {
    "123abc": "456def",
    "ciphertext": "v1:asdfasdf"
}
```

There are some secret environment variables being provided from a Pulumi config secret but it doesn't just encrypt that one leaf node, it's encrypting the whole `containers` array. When I specify to ignore the `image` property, it then seems to remove the property and thus results in an error.

I'm not sure how proceed from here.

**Comment by hamenu** [comment]
The exact same issue with Container Apps:

```
{
    "template": {
        "containers": [{
            "image": "<some-image-from-acr>",
            "env": [{
                "name": "NON_SECRET",
                "value": "123"
            },
            {
                "name": "SECRET",
                "value": "<SOME_PULUMI_SECRET>" // <------------- culprit
            }]
        }]
    }
}
```

We use Azure CLI to update the `image` property during deployment, and ignore it in the template:

```
ignoreChanges = { "template.containers[0].image" }
```

However, as mentioned above, the entire `containers` object turns into a secret and the `ignoreChanges` doesn't work.

The other problem is that if we change the value of `NON_SECRET` from `123` to `456`, Pulumi shows the change like this

```
~ containers: [
    ~ [0]: {
        ~ env: [
            ~ [0]: {
                ~ value: [secret] => [secret]
            }
        ]
    }
]
```

The workaround we have at the moment is getting the current `image` using Azure CLI _before_ `pulumi up` and pass that into the template as a Stack Config.

**Comment by caioaao** [comment]
Still happening on pulumi v3.73 and v3.68

**Comment by MitchellGerdisch** [comment]
What's worth noting is that when a subvalue in the `template` property is set as secret, it taints the whole `template` property as a secret. So even though the subvalue being changed is not a secret, it appears as a secret and it seems like `ignoreChanges` ignores secret values.

FWIW, here's code with test sequences in the comments for reproducing this issue.
```
import * as pulumi from "@pulumi/pulumi"
import * as azure from "@pulumi/azure-native";

/* TEST SEQUENCE:
    SUNNY DAY - Ignored property is NOT wrapped as a secret and things work as expected:
        SUNNY-STEP-1:
            Comment out the `ignoreChanges()` line. 
            Comment out the config.requireSecret() line and uncomment the line that sets envValue to a specific value.
            Run `pulumi up -r -y` 
            Whatever pulumi wants to do or not do regarding creating or updating resources is fine and expected at this step.
        SUNNY-STEP-2:
            UNcomment the `ignoreChanges()` line. 
            Run `pulumi up -y`
            There should be no change, but now things are baselined with ignoreChanges set.
        SUNNY-STEP-3:
            OUTSIDE of this stack, modify the image for the container app. 
                See the stack output for some help to import the container app into another throw-away stack you can use to easily modify the image.
                You can use "mcr.microsoft.com/azuredocs/aci-helloworld" for a different image
            Run `pulumi up -r` and you should see no update changes.

    RAINY DAY - Ignored property is wrapped as a secret and is subsequently not ignored when updated.
        RAINY-STEP-0:
            Uncomment the config.requireSecret() line and comment out the line that sets envValue to an specific value.
            Comment out the `ignoreChanges()` line. This is to get everything launched and set up as expected for the next sequence of steps.
            And it taints the template property as sensitive (i.e. secret) given the use of the secret envValue config.
            Run `pulumi up -r -y` and let pulumi do what it needs to do.
        RAINY-STEP-2:
            Uncomment the `ignoreChanges()` line. 
            Run `pulumi up -y`
            There should be no change, but now things are baselined with ignoreChanges set.
        RAINY-STEP-3:
            Modify the image for the container app OUTSIDE of this stack. 
                See the stack output below for some help to create another throw-away stack you can use to easily modify the image.
                You can use "mcr.microsoft.com/azuredocs/aci-helloworld" for a different image 
            Run `pulumi up -r` 
            Look at details and see that the ignoreChanges setting is being ignored and a change to the image is being registered.

*/

const resourceGroup = new azure.resources.ResourceGroup("my-resource-group");

const env = new azure.app.ManagedEnvironment("myenv", {
    resourceGroupName: resourceGroup.name,
});

// const envValue = '3'

const config = new pulumi.Config()
// doesn't matter what the value is set to in config.
// it is simply to taint the template property as sensitive data
const envValue = config.requireSecret("envValue") 


const app = new azure.app.ContainerApp("myapp", {
    resourceGroupName: resourceGroup.name,
    managedEnvironmentId: env.id,
    configuration: {
        ingress: {
            external: true,
            targetPort: 80,
        },
    },
    template: {
        containers: [{
            name: "hello-world",
            image: "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest",
            env: [
                {
                    name: "WEBSITE_HTTPLOGGING_RETENTION_DAYS",
                    value: '3'
                },
                {
                    name: "FakeThing",
                    value: envValue
                }
            ],
            resources: {
                cpu: 0.5,
                memory: "1.0Gi",
            },
        }],
    },
}, {
    ignoreChanges: ["template.containers[0].image"],
});

// Used for testing to create another stack that you can use to tinker with the setting outside of this stack.
// Once imported into that throw-away stack, modify the code in the outside stack to use: image: "mcr.microsoft.com/azuredocs/aci-helloworld"
// Then you can run `pulumi up --skip-preview -r` on the throw-away stack to get the image changed outside this stack
export const importAppContainerCmd = pulumi.interpolate`pulumi import azure-native:app:ContainerApp importedContainerApp ${app.id}`
```

**Comment by Frassle** [comment]
Can repro this in an engine test. It's due to some overly strict type checks when traversing property paths in `PropertyPath.Reset`, basically we see an indexer "[0]" and go "well to apply this property value should be an array" but it's not an array, it's a secret with an array inside it.
