### ISSUE TITLE
pulumi destroy with --target errors and leaves stack in unworkeable state

### ISSUE THREAD

**Issue by thrixton** [pulumi/pulumi#6283]
Targeting a resource (with dependent resources) for destroy errors and leaves the stack in an unworkeable state
## Example
Given the resource tree below
Deployment ==> Service
Service ==> Ingress

If I do a `pulumi destroy -t (urn of Deployment)`, we get the error below
```
error: post-step event returned an error: failed to verify snapshot: resource urn:pulumi:<snip>-ingress dependency urn:pulumi:<snip>worker refers to missing resource
```
When I do a `pulumi stack export --file stack.json` and look at the resulting file, I can see that there is a resource (my ingress) which still refers to my destroyed resource.
E.g. From the example above, Ingress still exists in the stack and refers to Deployment in the `dependencies` and `propertyDependencies.spec` elements.

I then remove the lines from my `stack.json` and do a `pulumi stack import --file stack.json` and it then works as per expected.

## Expected Behavior
Either dependent resources are destroyed (Service and Ingress)  
or
Dependent resources are left in place in a pending state and references are cleaned up in the stack

## Context (Environment)
"@pulumi/pulumi": "^2.20.0"
"@pulumi/kubernetes": "^2.8.0"

> NOTE: This may be an issue with the kubernetes provider rather than pulumi as it's not strictly necessary to remove dependent resources as their requirements may be satisfied at a future point.

**Comment by alex-hunt-materialize** [comment]
This also happens when passing `--target-dependents` during the destroy.

The expected behavior should probably be:

1. For `pulumi destroy --target $SOME_URN`, it should abort immediately if any dependents exist.
2. For `pulumi destroy --target $SOME_URN --target-dependents`, it should destroy the dependents first, followed by the target resource, and it should never corrupt the stack.

**Comment by alex-hunt-materialize** [comment]
Additionally, it seems to remove items from the state which still exist in reality. It crashed with:
```
error: post-step event returned an error: failed to verify snapshot: resource urn:pulumi:alexhunt::mzcloud::kubernetes:batch/v1beta1:CronJob::frontegg-sync-job dependency urn:pulumi:alexhunt::mzcloud::kubernetes:core/v1:Secret::mzcloud-alexhunt refers to missing resource
```
and the RDS instance which both of those depend on is gone from the state. The RDS instance itself still exists in AWS.

**Comment by alex-hunt-materialize** [comment]
This may also be related to https://github.com/pulumi/pulumi/issues/3878

**Comment by t0yv0** [comment]
This should be fixed with https://github.com/pulumi/pulumi/pull/8360 - please reopen if there are still issues. Thank you!
