### ISSUE TITLE
Not prompted for passphrase after first `up` when using local backend

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#6286]
## Expected Behavior

Pulumi should prompt users for their passphrase if `PULUMI_CONFIG_PASSPHRASE` and `PULUMI_CONFIG_PASSPHRASE_FILE` are not set when using any state backend.

## Current Behavior

If I initialize and `up` a stack when using the `--local` state backend, I'm not prompted for the passphrase after the first `up` and receive an error:

```
(venv) p-py-config-passphrase % pulumi up -y -f                   
error: decrypting secret value: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase
```

### Important Notes

- this behavior does not occur if I don't export a secret from the Pulumi app.
- this behavior does not occur if I use the Pulumi Console backend.
- setting `PULUMI_CONFIG_PASSPHRASE_FILE` does not resolve this

## Steps to Reproduce

1. `pulumi login --local`
1. `export PULUMI_CONFIG_PASSPHRASE=1234567890`
1. `pulumi new python -y`
2. `pulumi stack init pphrase-2`
4. `pulumi config set --secret foo bar`
3. `echo 'import pulumi\nfoo = pulumi.config.Config().require_secret("foo")\npulumi.export("foo", foo)' > __main__.py`
4. `pulumi up -y -f`
5. `unset PULUMI_CONFIG_PASSPHRASE`
4. `pulumi up -y -f`
    - observe error `error: decrypting secret value: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase`
1. `export PULUMI_CONFIG_PASSPHRASE=1234567890`
4. `pulumi up -y -f`
    - observe: completes successfully
5. `echo $PULUMI_CONFIG_PASSPHRASE > ./my-password.txt`
5. `export PULUMI_CONFIG_PASSPHRASE_FILE=./my-password.txt`
5. `unset PULUMI_CONFIG_PASSPHRASE`
4. `pulumi up -y -f`
    - observe: still fails even though `PULUMI_CONFIG_PASSPHRASE_FILE` is set

## Full output

```
(venv) p-py-config-passphrase % export PULUMI_CONFIG_PASSPHRASE=1234567890
(venv) p-py-config-passphrase % pulumi stack init pphrase-2
Created stack 'pphrase-2'
(venv) p-py-config-passphrase % pulumi config set --secret foo bar
(venv) p-py-config-passphrase % pulumi up -y -f
Updating (pphrase-2):
     Type                 Name                              Status      
 +   pulumi:pulumi:Stack  p-py-config-passphrase-pphrase-2  created     
 
Outputs:
    foo: "[secret]"

Resources:
    + 1 created

Duration: 1s

Permalink: file:///Users/clstokes/.pulumi/stacks/pphrase-2.json
(venv) p-py-config-passphrase % unset PULUMI_CONFIG_PASSPHRASE   
(venv) p-py-config-passphrase % pulumi up -y -f                   
error: decrypting secret value: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase
(venv) p-py-config-passphrase % export PULUMI_CONFIG_PASSPHRASE=1234567890
(venv) p-py-config-passphrase % pulumi up -y -f
Updating (pphrase-2):
     Type                 Name                              Status     
     pulumi:pulumi:Stack  p-py-config-passphrase-pphrase-2             
 
Outputs:
    foo: "[secret]"

Resources:
    1 unchanged

Duration: 1s

Permalink: file:///Users/clstokes/.pulumi/stacks/pphrase-2.json
(venv) p-py-config-passphrase % echo $PULUMI_CONFIG_PASSPHRASE > ./my-password.txt
(venv) p-py-config-passphrase % export PULUMI_CONFIG_PASSPHRASE_FILE=./my-password.txt
(venv) p-py-config-passphrase % unset PULUMI_CONFIG_PASSPHRASE
(venv) p-py-config-passphrase % pulumi up -y -f                                       
error: decrypting secret value: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase
```

## Context (Environment)

```
(venv) p-py-config-passphrase % pulumi version
v2.19.0
(venv) p-py-config-passphrase % pip list
Package    Version
---------- -------
dill       0.3.3
grpcio     1.35.0
pip        20.2.3
protobuf   3.14.0
pulumi     2.20.0
PyYAML     5.4.1
semver     2.13.0
setuptools 49.2.1
six        1.15.0
```

**Comment by AndreLachanceMoovAI** [comment]
+1.

Created a new stack, first up works fine,.

However, the stack then vanishes from `pulumi stack ls` and any subsequent attempt to use the stack returns an error.

```
>pulumi stack select dev
error: decrypting secret value: failed to decrypt: incorrect passphrase, please set PULUMI_CONFIG_PASSPHRASE to the correct passphrase
```

Small thing to note, I am not exporting or using any secrets/config.

**Comment by AndreLachanceMoovAI** [comment]
Small update, 

I managed to fix the issue on my side by downgrading the pulumi plugin for azure from v.3.51 to v.3.17.0.
