### ISSUE TITLE
Pulumi resources mutate the `opts` parameter.

### ISSUE THREAD

**Issue by timmyers** [pulumi/pulumi#6293]
Pulumi resources generated from terraform providers mutate their `opts` parameter which can result in very odd behavior from the perspective of the caller.  This is pervasive through all `tfgen` generated packages.

One place this exists, which breaks the example below, is here: https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/iam/role.ts#L194.

To be clear, this is breaking a common lint rule: https://eslint.org/docs/rules/no-param-reassign

## Expected Behavior
`opts` parameter is not mutated when instantiating a resource.

## Current Behavior
`opts` parameter, particularly `opts.version` is mutated when instantiating a resource.

## Steps to Reproduce
https://gist.github.com/timmyers/240f5234f6cbd4666ba185a1f7ecfc03

## Context (Environment)
Creating resources from multiple different default providers is broken easily by the mutation of `opts` in a single `ComponentResource`.

**Comment by abatilo** [comment]
This actually seems pretty major.

I guess for now, you can just make sure to create a new `defaultOpts` for each provider? That's just a work around. This should definitely be fixed ASAP.

**Comment by pgavlin** [comment]
Thanks for bringing this up! This is definitely not intended behavior 😬

**Comment by timmyers** [comment]
@lukehoban I am not sure why but the fix for this did not fix this issue everywhere.

For example: `https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/apiextensions/customResource.ts`
