### ISSUE TITLE
[Breaking] Add pagination defaults to `pulumi stack history`

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#6294]
https://github.com/pulumi/pulumi/pull/6292 exposed pagination options but didn't change the default behavior of retrieving every stack update ever performed.

For older stacks with many updates, this request can take quite a long time and produces a lot output. We should limit the default number of entries (@cnunciato suggests the github default of 100) to an output size that is friendlier on the user and on our backends 😄

**Comment by leezen** [comment]
Addressed by https://github.com/pulumi/pulumi/pull/6841
