### ISSUE TITLE
How I can make a computed value?

### ISSUE THREAD

**Issue by XBeg9** [pulumi/pulumi#6303]
https://github.com/pulumi/pulumi/blob/f6ec691544770813e16ca8fd41dafee6aa7c7690/sdk/go/common/resource/properties.go#L79

Is there a way to create a computed value from TS? In the use case, I don't know the value on `preview` mode, it will be computed only when some resources from the stack will be deployed to the server.

```
// Computed represents the absence of a property value, because it will be computed at some point in the future.  It
// contains a property value which represents the underlying expected type of the eventual property value.
```

Thanks

**Comment by XBeg9** [comment]
Trying an empty promise like this
```js
pulumi.runtime.isDryRun()
    ? new Promise(() => {}) : new Promise(async (resolve, reject) => ....)
```

gives me a promise leak error:
```
The Pulumi runtime detected that 50 promises were still active
    at the time that the process exited. There are a few ways that this can occur:
      * Not using `await` or `.then` on a Promise returned from a Pulumi API
      * Introducing a cyclic dependency between two Pulumi Resources
      * A bug in the Pulumi Runtime
    Leaving promises active is probably not what you want. If you are unsure about
    why you are seeing this message, re-run your program with the `PULUMI_DEBUG_PROMISE_LEAKS`
    environment variable. The Pulumi runtime will then print out additional
    debug information about the leaked promises.```

btw, I was able to use the empty promise approach for some time and randomly started getting this leakage and ended up getting it on every preview. :(

**Comment by pgavlin** [comment]
@XBeg9 I _think_ that this code should work:

```typescript
pulumi.runtime.isDryRun()
    ? Promise.resolve(pulumi.unknown) : new Promise(async (resolve, reject) => ....)
```

**Comment by XBeg9** [comment]
probably you meant `pulumi.runtime.unknownValue`,  but now it responds with
```bash
Diagnostics:
  kubernetes:core/v1:Secret (root-secret):
    error: Preview failed: resource 'ku-ns/04da6b54-80e4-46f7-96ec-b56ff0331ba9' does not exist
```

code
```js
pulumi.runtime.isDryRun()
    ? Promise.resolve(pulumi.runtime.unknownValue) // if dry run, don't resolve anything (preview mode)
    : new Promise(async (resolve, reject) => {
```

**Comment by pgavlin** [comment]
> probably you meant pulumi.runtime.unknownValue, but now it responds with

No, I did mean `pulumi.unknown`--is it not exported?

**Comment by XBeg9** [comment]
@pgavlin not, it's not exported :( should it be inside `@pulumi/pulumi` packages, right?

**Comment by XBeg9** [comment]
hm, took it from here: https://github.com/pulumi/pulumi/blob/cedab0003bda3b4cbb767d1a8875a620c34ba9da/tests/integration/partial_values/nodejs/index.ts#L7

```js
Promise.resolve(pulumi.output({ __pulumiUnknown: true }))
```

It works!

Thanks @pgavlin

**Comment by pgavlin** [comment]
> @pgavlin not, it's not exported :( should it be inside @pulumi/pulumi package, right?

It should, yes.

> hm, took it from here:

Glad that this works, at least. I'll file a followup issue to make sure that `pulumi.unknown` is exported.
