### ISSUE TITLE
[Automation API] Support incremental updates in preview

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#6306]
Currently, it's not possible to write incremental updates to an `io.Writer`

The issue can be seen [here](https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/stack.go#L255).

In the `Up` function, you can provide a progress stream: https://github.com/pulumi/pulumi/blob/master/sdk/go/x/auto/stack.go#L317

**Comment by EvanBoyle** [comment]
closing in favor of https://github.com/pulumi/pulumi/issues/6308 which has more detail
