### ISSUE TITLE
Write proposal regarding inputs for components

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#6309]
Components often need to conditionally create child resources based on input arguments. But multi-lang components currently project all inputs as `Input` (each will be `Output`) meaning there's really no good way to do this since we don't recommend creating resources inside an `apply`.

This issue tracks writing down a proposal with various options.

- Provide some way to allow resource creation inside `apply`.
- `pulumi.If` and `pulumi.For` primitives. https://github.com/pulumi/pulumi/issues/4834
- Allow prompt values for component inputs (requires schema, codegen, and docgen changes).
- Workaround in the marshaling layer? (If it's a prompt value, return it to `Construct` as the prompt value, rather than as an `Output`.)

Related:
https://github.com/pulumi/pulumi-eks/issues/490

**Comment by jaxxstorm** [comment]
A concrete example of this:

I want to create some Kubernetes resources in a multi language component. Most Kubernetes distributions come with an already created `kube-system` namespace which users might want to use to install those resources, where _others_ might want to create their own namespace.

I can't currently give users this option. Ideally i'd be able to let them do this:

```
const foo = new lb.Awslbcontroller("foo", {
    createNamespace: true,
    namespace: "foo",
})
```

**Comment by leezen** [comment]
During a recent planning discussion, we decided the reasonable path forward here is the third option mentioned:

> Allow prompt values for component inputs (requires schema, codegen, and docgen changes).

This improves authorability at the expense of increasing some of the complexity on the consumer side, but not by much as current `ComponentResource` consumers already need to think about prompt values.

**Comment by lukehoban** [comment]
> the reasonable path forward here is the third option

Is there an issue tracking implementing that?

**Comment by justinvp** [comment]
> Is there an issue tracking implementing that?

I've opened https://github.com/pulumi/pulumi/issues/6425
