### ISSUE TITLE
StackReference - items deleted when upgrading the cluster nodes

### ISSUE THREAD

**Issue by DStoyanoff** [pulumi/pulumi#6311]
Hello guys,
Thank you for your work with Pulumi.

I have experienced an issue today. I will first describe my setup.

I have one project for general, infra-related resources. This is where I've put the k8s cluster creation scripts. 
I also have multiple app-related projects that sit in a different repository and reference the infra project using StackReference. So far, everything worked as expected with this setup.

Today I had to change the tier of the cluster nodes to a bigger one. I have executed that in the infra repository, and as expected, the cluster was recreated with the new nodes. However, all deployments, services and other resources that sit in the downstream stacks got deleted. Is there a better way of handling such scenarios that I have missed or is it a general limitation of the stack reference functionality?

**Comment by pgavlin** [comment]
@DStoyanoff Pulumi does not offer builtin coordination of updates to dependent stacks (in your case, the app stacks that reference the infra stack). If you are using the Team or Enterprise editions of the Pulumi SaaS backend, you can use web hooks to achieve something similar by starting updates of dependent stacks each time the infra stack is changed: https://www.pulumi.com/docs/intro/console/extensions/webhooks/. If you're using a different backend (or the free edition of the Pulumi SaaS), you can use the automation API to similar effect: https://www.pulumi.com/blog/automation-api/.

We do hope to make this simpler in the future, though we don't have any concrete proposals at the moment.

**Comment by lukehoban** [comment]
@DStoyanoff I believe https://github.com/pulumi/pulumi/issues/2309 tracks what you are looking for here.  Please do weigh in there.
