### ISSUE TITLE
Create `config set-all` and `config rm-all` commands.

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#6329]
### Problem

Currently, automation API has O(N) time complexity dependent on the number of config keys for the `setAllConfig` and `removeAllConfig` functions because they loop through each key and run `setConfig` and `removeConfig` respectively. Under the hood, `setConfig` and `removeConfig` use the CLI commands `pulumi config set` and `pulumi config rm` respectively.

To improve this, we should introduce the ability to set and remove multiple config keys via a single command.

### Proposal

We introduce `pulumi config set-all` and `pulumi config rm-all` commands. The semantics of the commands are described below.

#### `pulumi config set-all`

**Usage**
```shell
$ pulumi config set-all --secret key1=value1 --plaintext key2=value2 --plaintext key3=value3
$ pulumi config set-all --path --secret key.prop=value1 --plaintext key1[0]=value2 --plaintext key3=value3
```

The existing `pulumi config set` command supports the `--path`, `--secret` and `--plaintext` flags, and we do some interactive checking (if a value is not provided we prompt for it, we check if the value looks like a secret and prompt the user to re-enter with `--secret`, etc.).

For the `set-all` command, I propose that we eliminate the interactive workflow and require that each key/value pair **must** have either a `--secret` or `--plaintext` flag preceding it. We will keep the `--path` flag as a boolean flag to indicate that **all** keys in that command should be parsed as paths rather than raw strings.

#### `pulumi config rm-all`

**Usage** 
```shell
$ pulumi config rm-all key1 key2 key3.foo "key4[1]" key5 key6
$ pulumi config rm-all --path key1 key2 key3.foo "key4[1]" key5 key6
```

As with the existing `pulumi config rm` command, the `--path` will be supported as a boolean flag. The flag applies to all keys in that command, indicating that they should be parsed as paths rather than raw strings.

### Related issues

* #6042

**Comment by lukehoban** [comment]
>  I also propose that we drop the --path flag

Is there any reason that `key1` in `key1=val1` couldn't just be allowed to be a full "path" (instead of just a top level key)?  That might allow supporting paths within the default model already proposed here.  I don't recall precisely why we had to add `--path` in the first place vs. just extending the format of supported keys in the normal `pulumi config` commands - and whether that same reason constrains this decision as well?

**Comment by komalali** [comment]
>Is there any reason that key1 in key1=val1 couldn't just be allowed to be a full "path" (instead of just a top level key)?

That's a good question. I had assumed there was a reason for `--path` being the way it is which is also why I wasn't proposing that `key1` be a full path. But perhaps it is not so. I'll look into it.

**Comment by justinvp** [comment]
> I don't recall precisely why we had to add `--path` in the first place vs. just extending the format of supported keys in the normal `pulumi config` commands - and whether that same reason constrains this decision as well?

The reason was around compatibility as keys can contain path characters (e.g. `pulumi config set foo.bar baz` or `pulumi config set [hello] world`), so `--path` was used to opt-in to the "path" syntax. It is unfortunate that it complicates the model a bit.

I could imagine coming up with a way to make `set-all`/`rm-all` work with the "path" syntax on by default, and have some way of escaping so you can still handle top-level keys that include special characters like `.`, `[`, `]`, etc. And if we were to do this, we could consider turning that on by default for the other config commands as a 3.0 behavior change, obviating the need for `--path` in these commands. Not sure how much value this really adds, other than simplifying the command line story for config.

**Comment by komalali** [comment]
I found the [original PR](https://github.com/pulumi/pulumi/pull/3342) where this was first added. Thanks @justinvp for the very detailed PR description!

It appears [we support periods in config keys](https://github.com/pulumi/pulumi/pull/3342#pullrequest-328358018-permalink:~:text=If%20you%20want%20to%20include%20a%20period%20in%20the%20name%20of%20a%20property%2C%20it%20can%20be%20specified%20as%3A), and we would need `--path` to support that specific use.

There doesn't appear to be anything else that would necessitate the `--path` flag. So perhaps we could move forward with what I have proposed with the caveat that this wouldn't work with keys with "path" characters.

**Comment by komalali** [comment]
Hah! Justin beat me to it.

**Comment by komalali** [comment]
>have some way of escaping so you can still handle top-level keys that include special characters like ., [, ], etc.

Perhaps wrapping it in quote marks could be the way of escaping?

**Comment by komalali** [comment]
What if we keep `--path` as a boolean flag (only used once per command) for both `rm-all` and `set-all` indicating that **every** key listed in that `set-all` or `rm-all` should be checked as a path rather than a raw string?

In that case, you would use `--path` if even one of the listed keys is a path but not if a key includes a "path character". The only situation in which this would not work is when you have both path keys **and** a top-level key including path characters - the chances of which seem low and it seems reasonable enough that you could run two separate commands if you did happen to fall into that bucket.

**Comment by justinvp** [comment]
> What if we keep `--path` as a boolean flag (only used once per command) for both `rm-all` and `set-all` indicating that **every** key listed in that `set-all` or `rm-all` should be checked as a path rather than a raw string?

This sounds fine to me. It's consistent with what we did for `pulumi up --config outer.inner=value --config-path`.

https://github.com/pulumi/pulumi/blob/0fe4978a7a009d93d6b9bcdfce318712e8c15fbe/pkg/cmd/pulumi/up.go#L397-L399

**Comment by komalali** [comment]
I'll update the original description of this issue to reflect the conversation in the comments.
