### ISSUE TITLE
[sdk/go] Add AnyOuput type assertion methods?

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#6356]
The `AnyOutput` type represents an `Output` whose value is an `interface{}`.  

It is an important type because `Apply` returns an `AnyOutput`.  But it is unfortunately rather hard to use - as you can't pass it to anything directly.  Instead, you have to do `anyout.ApplyInt(func (v interface{}) int { return v.(int) }).  

In practice, that makes `.Apply` close to unusable - because you ~always must follow an `.Apply` with a `.ApplyT`.  So it's basically always preferable to just use `ApplyT` directly.

We could try to make `AnyOutput` more usable by offering type assertion methods on it - like `anyoutout.AsInt()` via :

```go
func (o AnyOutput) AsInt() IntOutput {
  return o.ApplyInt(func (v interface{}) int {
    return v.(int)
  })
}
```

This method can of course panic because it is a type assertion.  But it would make `AnyOutput` and `Apply` more reasonable to work with.  It would only require N new methods total (not N^2, as these are only needed on `AnyOutput`).

**Comment by lukehoban** [comment]
No longer needed after the decision to remove `Apply` in the 3.0 branch.

**Comment by lukehoban** [comment]
There are still many places where `AnyOutput` shows up - so we likely still need to address this.  Reopening to track.

**Comment by Trojan295** [comment]
I've got a case, where one stack exports an StringArrayOutput. In an other stack I want to reference and use this value. As there is no `GetStringArrayOutput` on the `StackReference` I have to use the following code:
```go
publicSubnets := vpcStack.GetOutput(pulumi.String("publicSubnetIDs")).ApplyT(func(x interface{}) []string {
	y := x.([]interface{})

	r := make([]string, 0)
	for _, item := range y {
		r = append(r, item.(string))
	}
	return r
}).(pulumi.StringArrayOutput)
```

It would be useful to have an option to cast the AnyOutput to StringArrayOutput.
