### ISSUE TITLE
Add a `pulumi history` command

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#636]
We don't have any way to see the update history from the CLI.  We should add a `pulumi history` command to see this information.  We may also want to consider the ability to inspect details or diffs between updates, detailed resource state for particular updates, and so on.

**Comment by chrsmith** [comment]
This would definitely be nice to have, but it doesn't fit in M0.17, at least for me.

**Comment by joeduffy** [comment]
I would be fine implementing this command just for `httpstate` backends to begin with. Ideally this command goes hand in hand with https://github.com/pulumi/pulumi/issues/1910, so that you can not only see the deployment history, but fetch the checkpoint state from an arbitrary version in the past.

**Comment by joeduffy** [comment]
We made good progress on reviving the old implementation and discussing the new design. I expect we'll be able to land this during M20.

**Comment by joeduffy** [comment]
This is done as part of https://github.com/pulumi/pulumi/commit/bf300038d4b2602b5e932dbce80562fd435d3aa6. Thank you @diana-slaba!
