### ISSUE TITLE
Azure DevOps repositories not supported for Pulumi project templates

### ISSUE THREAD

**Issue by muellermatthias** [pulumi/pulumi#6360]
## Expected behavior

It should be possible to host Pulumi project templates in Azure DevOps repositories.
## Current behavior

Pulumi new command will fail:
"error: repository not found"
## Steps to reproduce

1. Create an Azure DevOps repo
2. Copy git https clone link
3. Run `pulumi new <URL>` (add username and PAT if repo is private)

Running `git clone <URL>` works fine.

After looking into the Pulumi source code I found this:
https://github.com/pulumi/pulumi/blob/ae91a277df04bd3a93d79cf1bf52002ec77a7f51/sdk/go/common/util/gitutil/git.go#L343-L365
The code tries to append ".git" to the path if it's missing. That works for Gitlab and GitHub, but not for Azure DevOps.
The Azure DevOps URLs usually look like this:
dev.azure.com/{organization}/{project}/_git/{repository}
Pulumi will try to add ".git" to the project name which results in the following URL:
dev.azure.com/{organization}/{project}.git/_git/{repository}

That would explain the error message.

**Comment by muellermatthias** [comment]
After fixing the URL parsing, I get a different error:
"error: unexpected client error: unexpected requesting "https://{user}:{pat}@dev.azure.com/{ort}/{project}/_git/pulumi{repo}/git-upload-pack" status code: 400"

This error has already been reported in the go-git library on GitHub: https://github.com/go-git/go-git/issues/64.

**Comment by leezen** [comment]
Thanks for digging into this more. I'll mark this issue as awaiting an upstream dependency for now.

**Comment by zbuchheit** [comment]
are there any updates on this? I saw on the go-git issue thread that some people had to migrate to git2go to get it to work.

**Comment by t0yv0** [comment]
Noting  https://github.com/go-git/go-git/issues/64 related here courtesy of @squaremo 

Quote:

```
The only reliable fix is to use git2go, which is Go bindings for the C library libgit2.
```

Discussion notes.

We need to look into these options:

- git2go
- using platform `git` via os.Exec in this fallback case

Both have some costs, linking C libs can cause issues, and detecting platform git CI can fail or require additional steps in contexts such as Docker containers. We may need to look at Pulumi docker containers.

**Comment by squaremo** [comment]
> I saw on the go-git issue thread that some people had to migrate to git2go to get it to work.

Flux, which initially used go-git exclusively, ran into a very similar problem. In its controllers, we ended up using git2go and linking with libgit2: the result is https://github.com/fluxcd/golang-with-libgit2, a container base image with libgit2 and its dependencies already built. This is used to build static binaries, e.g., https://github.com/fluxcd/image-automation-controller/blob/main/Dockerfile. In theory it could be used to build a distributable binary, too, though this hasn't been done for Flux's CLI tool yet.

The problem with that approach here will be that _any_ binary built with Pulumi's go libraries (the automation API) would need to link with libgit2, either requiring it to be installed at the point of use, or using extra machinery like the build image Flux uses. That's quite a cost to put on users of the automation API.

With that in mind, I would recommend giving people the option to exec `git` for cloning, in the automation API and in the Pulumi CLI. Controlling it with an environment variable would mean no need to update code, just bump the library version and rebuild.

**Comment by RobbieMcKinstry** [comment]
@squaremo It's unclear to me why we need the environment variable to enable the feature.
Right now we don't support AZ DevOps repos at all. If we change the code to detect AZ DevOps repo URIs, and invoke system git when we do, we're strictly adding functionality. Can that approach not be the default? I'm unsure why a user would need to opt-in. Thanks!

**Comment by squaremo** [comment]
> It's unclear to me why we need the environment variable to enable the feature.

People might want to use this with git providers or hosts other than Azure DevOps. For example, go-git also had problems with AWS CodeCommit, and it's unclear whether that's been resolved.

**Comment by dixler** [comment]
It seems that the problems are
1. go-git cannot clone from azure devops
2. converting a URL to the clone url, git ref, and path to the template

## converting a URL to the clone url, git ref, and path to the template

I propose that we add 3 flags to `pulumi new` to specify
- repo url(can include https auth fields)
- git ref to use(if specified: checks out the specified ref)
- template path(default: repository root)

This would make it generic to other git repository providers and avoid the ambiguity that we have when interpreting a string.

## go-git cannot clone from azure devops

when a user is using the new flags, opt them into a v2 implementation that uses the system installed git. This would avoid breaking existing users that don't expect this system dependency.

This change would also implement
- https://github.com/pulumi/pulumi/issues/4872

**Comment by t0yv0** [comment]
@dixler could you elaborate why the two things have to be mixed? Can they be solved separately and be functionally independent? For example why would the style of specifying Git references decide which Git client to use? That sounds like a very unfortunate coupling.

On the #4872 proposal, a proliferation of flags may not be the most user friendly. Consider how other OSS packages solve this problem. For example, npm uses the following encoding of Git coordinates in an URL (see <protocol>://[<user>[:<password>]@]<hostname>[:<port>][:][/]<path>[#<commit-ish> | #semver:<semver>]):

```
<protocol>://[<user>[:<password>]@]<hostname>[:<port>][:][/]<path>[#<commit-ish> | #semver:<semver>]

where <protocol> is one of git, git+ssh, git+http, git+https, or git+file.
```

This seems expressive enough to encode template path, Git protocol, and various creds in one URL, though I'm not sure of backward compatibility constraints off the bat without digging in.

**Comment by dixler** [comment]
---

> @dixler could you elaborate why the two things have to be mixed? Can they be solved separately and be functionally independent? For example why would the style of specifying Git references decide which Git client to use? That sounds like a very unfortunate coupling.

Rewriting the entire `pulumi new` command to support Azure DevOps repositories seems like a large and risky change.

This approach leaves legacy behavior intact to avoid breaking existing CI jobs/scripts that may depend on the old behavior such as not needing `git` installed on the PATH.

If a user is trying to pull down a template from a git repository, it doesn't seem like much of an ask to ask them to have git installed. It seems like a fair assumption that `pulumi new` is oriented around development work. If they're adamant about not having git installed, they can use the legacy implementation that uses strings.

Tying the solutions together would allow us to handle 2 longstanding issues in 1 PR. Otherwise, the other issue probably won't get prioritized unless it's taken care of by coincidence.

---

> On the #4872 proposal, a proliferation of flags may not be the most user friendly. Consider how other OSS packages solve this problem. For example, npm uses the following encoding of Git coordinates in an URL (see https://docs.npmjs.com/cli/v8/commands/npm-install):
> 
> ```
> <protocol>://[<user>[:<password>]@]<hostname>[:<port>][:][/]<path>[#<commit-ish> | #semver:<semver>]
> 
> where <protocol> is one of git, git+ssh, git+http, git+https, or git+file.
> ```
> 
> This seems expressive enough to encode template path, Git protocol, and various creds in one URL, though I'm not sure of backward compatibility constraints off the bat without digging in.

I've implemented things like this and I regret reinventing named parameters
- they're much less readable than having named arguments especially in scripts.
- users have to learn how to use our proprietary URI schema
- we have to write/maintain a parser for this.
- it's very hard to add new parameters to a URI specification since we would have to make sure it's not ambiguous to the parser

We already have spf13/cobra to parse arguments for us.
