### ISSUE TITLE
Enable building the .NET SDK with .NET 5+

### ISSUE THREAD

**Issue by jankeromnes** [pulumi/pulumi#6364]
Hi there! 👋

I'm trying to build a fully-automated dev setup for Pulumi using [Gitpod](https://www.gitpod.io), and I initially tried using the default .NET Core image, `gitpod/workspace-dotnet`.

However, this image comes with .NET Core 5.0, which I believe Pulumi doesn't support yet, because when I run `make` I get the following error:

```
TEST FAST:
# include the version prefix/suffix to avoid generating a separate nupkg file
dotnet test /p:VersionPrefix=2.21.0 /p:VersionSuffix=alpha.1613579752+gd4eb09cf9
  Determining projects to restore...
  All projects are up-to-date for restore.
  Pulumi -> /workspace/pulumi/sdk/dotnet/Pulumi/bin/Debug/netcoreapp3.1/Pulumi.dll
  Pulumi.Tests -> /workspace/pulumi/sdk/dotnet/Pulumi.Tests/bin/Debug/netcoreapp3.1/Pulumi.Tests.dll
Test run for /workspace/pulumi/sdk/dotnet/Pulumi.Tests/bin/Debug/netcoreapp3.1/Pulumi.Tests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.8.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.1 at [/home/gitpod/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.20.04-x64
. Please check the diagnostic logs for more information.

Test Run Aborted.
make[1]: *** [Makefile:53: dotnet_test] Error 1
make[1]: Leaving directory '/workspace/pulumi/sdk/dotnet'
```

Would it be possible to allow building with .NET Core 5.0?

(I don't know much about .NET, but have successfully upgraded small projects from 3.1 to 5.0 without problems by just updating a version string.)

## Affected feature

`make`

**Comment by mikhailshilkov** [comment]
.NET 5 is supported, you just need to configure your `csproj` accordingly. See the full example here: https://github.com/pulumi/examples/tree/master/azure-nextgen-cs-net5-aks-webapp

**Comment by mikhailshilkov** [comment]
I haven't tried building it from source code with .NET 5. Do you know what needs to change to make it work for you?

**Comment by jankeromnes** [comment]
Thanks for the quick response!

I've found a workaround for now (installing .NET 3.1 in my base image instead of .NET 5) but I guess building Pulumi from source with .NET 5 could be attempted by adjusting the tests (i.e. whichever test in `TEST FAST` fails when seeing .NET `5.0.1` because it seems to expect `3.1.0` instead).

I'm happy to look more deeply into making the build pass with .NET 5 if that's helpful.

**Comment by jankeromnes** [comment]
Sure! I'll give it a try tomorrow then.

(Meanwhile, my attempts with .NET 3.1 currently have `make` failing due to various `tslint` errors in `pulumi/sdk/nodejs/`, e.g. `ERROR: /workspace/pulumi/sdk/nodejs/runtime/config.ts:45:26 - Missing semicolon` -- but I feel that's more of a topic for the `#contribute` channel in the [Pulumi Community Slack](https://slack.pulumi.com/).)

**Comment by mikhailshilkov** [comment]
Pulumi now defaults to .NET 6, so I expect I can close this issue now. Learn more here: https://www.pulumi.com/blog/pulumi-targets-dotnet-6/
