### ISSUE TITLE
[sdk/nodejs] Config values (e.g. `aws.config.region`) aren't available inside `construct`

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#6366]
For example, trying to use `aws.config.region` from a component created in `construct` isn't picking up config values.

Also calls to [this](https://github.com/pulumi/pulumi-awsx/blob/b515c09c32196286380dc08b362c53272b63d6a3/nodejs/awsx/utils.ts#L137) return `undefined`.

We are setting up config before calling the user's `construct`, so need to investigate why `aws.config.region` isn't available:

https://github.com/pulumi/pulumi/blob/a6b6437b493bde032eda9f7a3acb704f42625d6c/sdk/nodejs/provider/server.ts#L268-L275

**Comment by EvanBoyle** [comment]
Is it related to this issue where the imports that trigger config are evaluated before the server is running?

https://github.com/pulumi/pulumi/issues/5582

**Comment by justinvp** [comment]
> Is it related to this issue where the imports that trigger config are evaluated before the server is running?

Yes, I believe so. Closing as dupe of #5582
