### ISSUE TITLE
Pulumi logs should work with multiple accounts and regions

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi#6371]
We're using Pulumi to build a stack with resources on multiple accounts and regions. We define multiple AWS providers and then each resource gets assigned to one of those providers. Authentication is done by connecting to a certain role in a certain account and then assuming other roles on the other accounts, which is done when we define the providers. Pulumi logs seems to try and use the main credentials to connect to the multiple resources, which would never work since we're creating the resources on other accounts and without assuming the correct role it will never work.

## Affected feature

Pulumi logs should take into account the defined providers and use the credentials and roles set on those providers to connect to CloudWatch and retrieve the logs. I believe this would also solve the problem of having resources on multiple regions as well.

**Comment by lukehoban** [comment]
This is the same issue as tracked in https://github.com/pulumi/pulumi/issues/1828. Closing out as a duplicate.
