### ISSUE TITLE
[sdk/dotnet] Concurrency issue in WhileRunningAsync HandleCompletion

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#6377]
We received the following error in one of our [test runs](https://github.com/pulumi/pulumi-azure-nextgen-provider/pull/522/checks?check_run_id=1921033867#step:19:183) which means our task awaiting logic isn't entirely thread-safe. It doesn't happen often but that's how concurrency issues manifest... We should fix this.

```
Diagnostics:
pulumi:pulumi:Stack (cs-simple-p-it-fv-az59-79-cs-simple-c27e31cf):
   error: Running program '/tmp/p-it-fv-az59-79-cs-simple-c27e31cf-036146210/bin/Debug/netcoreapp3.1/cs-simple.dll' failed with an unhandled exception:
  System.Collections.Generic.KeyNotFoundException: The given key 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[System.Threading.Tasks.VoidTaskResult,Pulumi.Deployment+<RegisterResourceOutputsAsync>d__74]' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
     at Pulumi.Deployment.Runner.<>c__DisplayClass9_0.<<WhileRunningAsync>g__HandleCompletion|0>d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
  at Pulumi.Deployment.Runner.WhileRunningAsync()
```

**Comment by Badabum** [comment]
Just got the same error

**Comment by orionstudt** [comment]
could change the task dictionary to a `ConcurrentDictionary`

**Comment by andrewdmoreno** [comment]
@mikhailshilkov apologize if you're not the right person to answer this but I think I am running into same issue. Seems like it was resolved, but my question is if there a specific version of a package that we need to be using that has this fixed?

**Comment by t0yv0** [comment]
Could you open a new issue @andrewdmoreno with your dependency versions? Much appreciated.
