### ISSUE TITLE
Output.all() unhandled exception

### ISSUE THREAD

**Issue by gdeber** [pulumi/pulumi#6380]
When using pulumi==2.21.0 in python there's an exception during pulumi up:

>     error: Program failed with an unhandled exception:
> 
>     error: Traceback (most recent call last):
>       File "/home/debe/bin/pulumi-latest/pulumi-language-python-exec", line 85, in <module>
>         loop.run_until_complete(coro)
>       File "/home/debe/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
>         return future.result()
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 83, in run_in_stack
>         await run_pulumi_func(lambda: Stack(func))
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
>         await RPC_MANAGER.rpcs.pop()
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
>         result = await rpc
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       [Previous line repeated 5 more times]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
>         result = await rpc
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       [Previous line repeated 5 more times]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
>         result = await rpc
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       [Previous line repeated 5 more times]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
>         result = await rpc
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       [Previous line repeated 5 more times]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
>         result = await rpc
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       [Previous line repeated 5 more times]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
>         result = await rpc
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 91, in is_value_known
>         return await is_known and not contains_unknowns(await future)
>       [Previous line repeated 5 more times]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 358, in do_register
>         resolver = await prepare_resource(res, ty, custom, props, opts)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 86, in prepare_resource
>         serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 78, in serialize_properties
>         result = await serialize_property(v, deps, input_transformer)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 199, in serialize_property
>         value = await serialize_property(output.future(), deps, input_transformer)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 185, in serialize_property
>         future_return = await asyncio.ensure_future(awaitable)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 358, in do_register
>         resolver = await prepare_resource(res, ty, custom, props, opts)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 86, in prepare_resource
>         serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 78, in serialize_properties
>         result = await serialize_property(v, deps, input_transformer)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 199, in serialize_property
>         value = await serialize_property(output.future(), deps, input_transformer)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 185, in serialize_property
>         future_return = await asyncio.ensure_future(awaitable)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 358, in do_register
>         resolver = await prepare_resource(res, ty, custom, props, opts)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 86, in prepare_resource
>         serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 78, in serialize_properties
>         result = await serialize_property(v, deps, input_transformer)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 199, in serialize_property
>         value = await serialize_property(output.future(), deps, input_transformer)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 185, in serialize_property
>         future_return = await asyncio.ensure_future(awaitable)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 358, in do_register
>         resolver = await prepare_resource(res, ty, custom, props, opts)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 86, in prepare_resource
>         serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 78, in serialize_properties
>         result = await serialize_property(v, deps, input_transformer)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 199, in serialize_property
>         value = await serialize_property(output.future(), deps, input_transformer)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 185, in serialize_property
>         future_return = await asyncio.ensure_future(awaitable)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 358, in do_register
>         resolver = await prepare_resource(res, ty, custom, props, opts)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 86, in prepare_resource
>         serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 78, in serialize_properties
>         result = await serialize_property(v, deps, input_transformer)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 199, in serialize_property
>         value = await serialize_property(output.future(), deps, input_transformer)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 185, in serialize_property
>         future_return = await asyncio.ensure_future(awaitable)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 358, in do_register
>         resolver = await prepare_resource(res, ty, custom, props, opts)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/resource.py", line 86, in prepare_resource
>         serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, res.translate_input_property)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 78, in serialize_properties
>         result = await serialize_property(v, deps, input_transformer)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 199, in serialize_property
>         value = await serialize_property(output.future(), deps, input_transformer)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/runtime/rpc.py", line 185, in serialize_property
>         future_return = await asyncio.ensure_future(awaitable)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 116, in get_value
>         val = await self._future
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 116, in get_value
>         val = await self._future
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 116, in get_value
>         val = await self._future
>       [Previous line repeated 4 more times]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 157, in run
>         value = await self._future
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 382, in gather_futures
>         return await asyncio.gather(*value_futures_list)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 116, in get_value
>         val = await self._future
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 178, in run
>         transformed: Input[U] = func(value)
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 266, in from_input
>         dict_items = [[k, Output.from_input(v)] for k, v in val.items()]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 266, in <listcomp>
>         dict_items = [[k, Output.from_input(v)] for k, v in val.items()]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 272, in from_input
>         list_items: List[Union[Any, Awaitable[Any], Output[Any]]] = [Output.from_input(v) for v in val]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 272, in <listcomp>
>         list_items: List[Union[Any, Awaitable[Any], Output[Any]]] = [Output.from_input(v) for v in val]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 266, in from_input
>         dict_items = [[k, Output.from_input(v)] for k, v in val.items()]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 266, in <listcomp>
>         dict_items = [[k, Output.from_input(v)] for k, v in val.items()]
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 274, in from_input
>         output: Output[T] = cast(Output[T], Output.all(*list(list_items))) # type: ignore
>       File "/home/debe/.pyenv/versions/3.7.2/envs/Pulumi-latest/lib/python3.7/site-packages/pulumi/output.py", line 388, in all
>         raise ValueError("Output.all() was supplied no inputs")
>     ValueError: Output.all() was supplied no inputs
>     error: an unhandled error occurred: Program exited with non-zero exit code: 1

Same exception didn't occours when using pulumi==2.20

## Context (Environment)
In my code I didn't make use of Output.All. I only refer to another stack:

> network_interfaces=[{
>                                           "accessConfig": [{}],
>                                           "network": parentStack.get_output('vpc_id'),
>                                           "subnetwork": parentStack.get_output('subnet_id'),
>                                       }],
> 

## Affected feature
pulumi cli v2.21.0
python libs:
pulumi            2.21.0
pulumi-aws        3.12.2
pulumi-gcp        4.8.0

> 

>

**Comment by csssuf** [comment]
This is also causing issues with `ConfigGroup` in pulumi-kubernetes, due to this line: https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/python/pulumi_kubernetes/yaml.py#L165

**Comment by komalali** [comment]
@csssuf Thanks for reporting that, no need to file another issue - fix incoming.

**Comment by komalali** [comment]
Alright folks, [v2.21.1](https://pypi.org/project/pulumi/2.21.1/) is out and includes the fix to this bug.
