### ISSUE TITLE
StackReference can't be read from twice - registered twice (read and read)

### ISSUE THREAD

**Issue by jeffrichie** [pulumi/pulumi#6409]
When pulling in a StackReference in two different files in same project, error is thrown on `preview`:

## Expected behavior
Let me pull in a StackReference however many times I want.

## Current behavior
Error:
```
  pulumi:pulumi:StackReference (vpc/development):
    error: resource 'urn:pulumi:dev::two-stack-references::pulumi:pulumi:StackReference::vpc/development' registered twice (read and read)
```

## Steps to reproduce

`index.ts`:

```
import { createTestOne } from './infra/test';
import { createTestTwo } from './infra/test2';

createTestOne();
createTestTwo();
```

`./infra/test.ts`:

```
import * as pulumi from '@pulumi/pulumi';
import { StackReference } from '@pulumi/pulumi';

export function createTestOne(): StackReference {
  const test1 = new pulumi.StackReference(
    'vpc/development'
  );

  return test1;
}
```

`./infra/test2.ts`:

```
import * as pulumi from '@pulumi/pulumi';
import { StackReference } from '@pulumi/pulumi';

export function createTestTwo(): StackReference {
  const test2 = new pulumi.StackReference(
    'vpc/development'
  );

  return test2;
}
```

## Context (Environment)
This makes me have to create a StackReference in `index.ts` and pass it around to functions. This becomes messy.

```
two-stack-references % pulumi version
v2.21.1
```

**Comment by jeffrichie** [comment]
After talking with folks on the Pulumi Slack, this may not be a true bug. Defining the StackReference once and importing it when needed seems like the correct pattern. It would still be nice to have this option though. 👯 

Feel free to close.

**Comment by pquerna** [comment]
Exporting a single instance of this might make more sense in Typescript, but isn't a very common pattern in Go - and this same issue can happen there

**Comment by pquerna** [comment]
been using this as a work-around in go:

```
package xpulumi

import (
	"sync"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var refCache sync.Map

type refKey struct {
	ctx     *pulumi.Context
	refName string
}

func GetStackReference(ctx *pulumi.Context, refName string) (*pulumi.StackReference, error) {
	key := refKey{ctx, refName}
	refx, ok := refCache.Load(key)
	if ok {
		return refx.(*pulumi.StackReference), nil
	}

	ref, err := pulumi.NewStackReference(ctx, refName, nil)
	if err != nil {
		return nil, err
	}
	refCache.Store(key, ref)
	return ref, nil
}

```

**Comment by lukehoban** [comment]
This is also being tracked in https://github.com/pulumi/pulumi/issues/7018 now, so I'll close this one out and port the Go workaround noted above to that issue.
