### ISSUE TITLE
Error when importing a GCP Cloud Run domain mapping

### ISSUE THREAD

**Issue by optel-perchri1** [pulumi/pulumi#6432]
When trying to import a GCP Cloud Run domain mapping, pulumi returns 4 errors : 
```Diagnostics:
  gcp:cloudrun:DomainMapping (domain-mapping):
    error: gcp:cloudrun/domainMapping:DomainMapping resource 'domain-mapping' has a problem: Computed attribute cannot be set
    error: gcp:cloudrun/domainMapping:DomainMapping resource 'domain-mapping' has a problem: Computed attribute cannot be set
    error: gcp:cloudrun/domainMapping:DomainMapping resource 'domain-mapping' has a problem: Computed attribute cannot be set
    error: gcp:cloudrun/domainMapping:DomainMapping resource 'domain-mapping' has a problem: Computed attribute cannot be set
```
I tried the three formats documented in Pulumi's docstring:

1. `pulumi import gcp:cloudrun/domainMapping:DomainMapping default locations/{{location}}/namespaces/{{project}}/domainmappings/{{name}}`
2. `pulumi import gcp:cloudrun/domainMapping:DomainMapping default {{location}}/{{project}}/{{name}}`
3. `pulumi import gcp:cloudrun/domainMapping:DomainMapping default {{location}}/{{name}}`

With the third format, without a project part, I receive the error project: `required field is not set.`

The two first formats seem happy with the `id` string passed, i.e. not complaining about a missing field, but return the 4 errors mentioned above. Yet I could import 10 other GCP resource types successfully; this is the only one that gives me trouble.

These errors are similar to other reported errors (https://pulumi-community.slack.com/archives/C84L4E3N1/p1608570994454500 / https://github.com/pulumi/pulumi/issues/5828, https://github.com/pulumi/pulumi-terraform-bridge/issues/74), where the workaround solution was to remove an argument, but this was in the context Pulumi code, not a resource import.

## Expected behavior

The domain mapping should import like other resource types.

## Current behavior

See the error reported above.

## Steps to reproduce

1.`pulumi import gcp:cloudrun/domainMapping:DomainMapping domain-mapping {{location}}/{{project}}/{{name}}`

## Context (Environment)

Using pulumi 2.21.1 and 2.21.2 on Ubuntu 20.04.

## Affected feature

pulumi import

**Comment by optel-perchri1** [comment]
I previously submitted this problem in Pulumi Community Slack channel : https://app.slack.com/client/T85C88L30/C84L4E3N1

**Comment by lukehoban** [comment]
Opened https://github.com/pulumi/pulumi/issues/7160 to track the root issue.  Closing this one out to track there and collect additional data.
