### ISSUE TITLE
Elastic Cloud provider

### ISSUE THREAD

**Issue by ffMathy** [pulumi/pulumi#6438]
I would love a provider for the official Elasticsearch host, Elastic Cloud (elastic.co).

**Comment by Dmitry-Danchenko** [comment]
Hi, now I am working on elasticsearch provider using pulumi terraform boilerplate:
https://github.com/Dmitry-Danchenko/pulumi-elasticsearch
But I do not have enough time to support all functionality.
If you want to help - welcome!

**Comment by stack72** [comment]
We now have this provider available in our registry https://www.pulumi.com/registry/packages/ec/
