### ISSUE TITLE
Automation api Go SDK debug log propagation from provider fails

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi#6451]
Debug logging options are available for Go Automation API: https://pkg.go.dev/github.com/pulumi/pulumi/sdk/v2@v2.21.2/go/x/auto/optup#Option
Setting `FlowToPlugin` should result in all relevant logs from the plugin/provider to be pulled.
However, at the moment setting these options results in this diagnostic message and no debug logs:
```
Diagnostics:
  pulumi:pulumi:Stack (...):
    flag provided but not defined: -v
    Usage of tf-provider-flags:
      -get-provider-info
                dump provider info as JSON to stdout
      -version
```
Using LogToStdErr gets around this but that is not feasible for all stacks.

**Comment by yarinm** [comment]
Is there a way to solve this soon? I have a serious issue I can't debug without it.

**Comment by EvanBoyle** [comment]
Closing this as it is a subset of work tracked in https://github.com/pulumi/pulumi/issues/7402
