### ISSUE TITLE
Automation API C# Updates for GA

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#6459]
I can refresh that #5761 did everything except:

- `RemoteProgram` support
- Stack `import/export/cancel` support
- Concurrency (#6139)

Also during #5761 we talked about re-naming the following methods:

1. `GetConfig` -> `GetConfigValue`
2. `GetAllConfig` -> `GetConfig`
3. `SetConfig` -> `SetConfigValue`
4. `SetAllConfig` -> `SetConfig`

And those changes haven't been reflected in the other SDKs yet.

_Originally posted by @orionstudt in https://github.com/pulumi/pulumi/issues/5596#issuecomment-789742923_

**Comment by leezen** [comment]
Based on discussion 3/16, we think the only things that need to happen are:
* Stack import/export/cancel support
* Concurrency (#6139)

**Comment by komalali** [comment]
@leezen about renaming the methods, what we discussed during the meeting today is actually the opposite of the current state. All of the values listed first (i.e. GetConfig) are what is used in the other SDKs (nodejs/python/go), the ones listed second `GetConfigValue` is what is used only in dotnet. So if we want to bring them into alignment there is still work to do here for dotnet.

**Comment by orionstudt** [comment]
I'm sorry if I made that confusing. I meant for what was before the arrow to be what it is currently, and after the arrow to be what was agreed it should be changed too

**Comment by leezen** [comment]
@komalali Thanks for clarifying. In which case, I'll update the comment above to indicate we should bring that in as well.

**Comment by t0yv0** [comment]
This is done.
