### ISSUE TITLE
Automatic virtual environment creation uses wrong path and fails

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#6471]
If I `pulumi new python -y`, virtual environment creation works fine. 

If I `pulumi up` and do not already have a virtual environment, pulumi attempts to create a virtual environment uses the wrong path and fails. In this scenario, `pulumi` appears to create a `venv` directory using the full absolute path but from the relative path - e.g `/Users/clstokes/cc/scratch/p-python-venv/p-python1/Users/clstokes/cc/scratch/p-python-venv/p-python1/venv` when running from `/Users/clstokes/cc/scratch/p-python-venv/p-python1/`.

## Expected behavior

`pulumi up` should create a `venv` within my current project directory - e.g. `/Users/clstokes/cc/scratch/p-python-venv/p-python1/venv`.

## Current behavior

`pulumi up` creates a `venv` using the full absolute path, but within my current directory - e.g. `/Users/clstokes/cc/scratch/p-python-venv/p-python1/Users/clstokes/cc/scratch/p-python-venv/p-python1/venv` when running from `/Users/clstokes/cc/scratch/p-python-venv/p-python1/`

### Error output

```
p-python1 % pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/clstokes/p-python1/dev/previews/e952a0b6-b101-41b9-a82b-a9a1dcca0ce2

     Type                 Name           Plan
     pulumi:pulumi:Stack  p-python1-dev

error: failed to discover plugin requirements: The 'virtualenv' option in Pulumi.yaml is set to "venv", but "/Users/clstokes/cc/scratch/p-python-venv/p-python1/venv" doesn't exist; run the following commands to create the virtual environment and install dependencies into it:

    1. python3 -m venv /Users/clstokes/cc/scratch/p-python-venv/p-python1/venv
    2. /Users/clstokes/cc/scratch/p-python-venv/p-python1/venv/bin/python -m pip install --upgrade pip setuptools wheel
    3. /Users/clstokes/cc/scratch/p-python-venv/p-python1/venv/bin/python -m pip install -r requirements.txt


For more information see: https://www.pulumi.com/docs/intro/languages/python/#virtual-environments
```

## Steps to reproduce

1. mkdir dir1 && cd dir1
2. `pulumi new python -y`
3. `rm -rf venv`
4. `pulumi up`
    - *observe error*

## Context (Environment)

```
p-python1 % python3 --version
Python 3.9.1
p-python1 % pulumi version
v2.21.2
```

**Comment by t0yv0** [comment]
I was able to reproduce.
