### ISSUE TITLE
Topic Subscription creation suddenly timing out

### ISSUE THREAD

**Issue by doctorshiban** [pulumi/pulumi#6472]
In the week or so, the same pulumi plan that has worked prior started timing out, due to the topic subscription step timing out. We're targeting Localstack. This appears very similar to a previous issue we ran into: https://github.com/pulumi/pulumi/issues/6333

## Expected behavior
```Pulumi up``` executes as expected, creating the topic subscription

## Current behavior
The topic subscription creation is timing out (animation is sped up purposefully)

![2021-03-04_21-26-31](https://user-images.githubusercontent.com/69910109/110071331-b1cf7f00-7d30-11eb-8f64-bbec8cf75db4.gif)

Here's the specific error message screenshot:
![image](https://user-images.githubusercontent.com/69910109/110071398-cd3a8a00-7d30-11eb-89a9-01a707b37f3b.png)

## Steps to reproduce
Created a repo with a minimal repro:
https://github.com/doctorshiban/pulumi-topic-example

## Context (Environment)
Development is currently blocked because we rely on Localstack across the team

**Comment by doctorshiban** [comment]
@leezen has anything changed similar to the other issue that may have caused this to start happening?

**Comment by leezen** [comment]
@doctorshiban No, no other defaults have changed w.r.t. provider configuration for the AWS provider. It would be helpful if you're able to indicate at which version of the plugin this stops working for you? Did you update the version and this stopped working?

**Comment by doctorshiban** [comment]
I'm using:
![Snag_83165f5](https://user-images.githubusercontent.com/69910109/111052138-62164500-840d-11eb-9f9c-36b3aff949b4.png)

The repo I posted here has a minimal repor: https://github.com/doctorshiban/pulumi-topic-example
Does this work as expected on your end?

**Comment by leezen** [comment]
I had no issues running the example in your repo against AWS itself, so I suspect this has something to do with localstack? One option I could imagine is passing in a transformation to try increasing the `confirmationTimeoutInMinutes` on the underlying `TopicSubscription` resource.

**Comment by doctorshiban** [comment]
I wound up transitioning to Docker-based lambdas which don't have related limitations. Closing this one out
