### ISSUE TITLE
Cannot mix azure-classic and azure-native SDKs and use one set of Azure credentials in the config

### ISSUE THREAD

**Issue by agileramblings** [pulumi/pulumi#6475]
I've recently added CosmosDB provisioning to our pulumi app. I've used the new azure-native SDK (in beside the existing azure SDK for other resources) and when I run the pulumi app locally, everything works because I had executed `az login`. When I run the app via our AzureDevOps build agent, I get this error:

```
2021-03-04T17:23:48.8597836Z   azure-native:documentdb/v20210301preview:DatabaseAccount (releasesplatform-cosmosdb):
2021-03-04T17:23:48.8598404Z     error: building auth config: obtain subscription() from Azure CLI: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1
```

This app/pipeline worked prior to the cosmosdb additions.
I've re-run another one of our pipelines that executes a `pulumi app` and it continues to work.
Doing an `az logout` and `pulumi up` causes the error to appear on my local machine as well.
I have this in my `pulumi config` which is what the pipelines do for authentication with Azure

![image](https://user-images.githubusercontent.com/9729653/110129455-364bed00-7d85-11eb-99c1-abf1ad554c07.png)

Duplicating all of the `azure-native:...` configuration with `azure:...` configuration values resolves this problem.

## Expected behavior
A better error message, or the various providers to "search" for azure client credentials

## Current behavior
Azure DevOps pipeline seems unable to authenticate with Azure using the current `pulumi config` values.

## Steps to reproduce

1. `pulumi new azure-typescript` (pulumi CLI v2.22.0)
2. ensure that `az logout` has been executed
3. setup `pulumi config` with azure authentication values (e.g. `azure-native:clientId`)
4. `npm install @pulumi/azure`
5. Create a resource group using the azure-classic library
6. Create a resource group using the azure-native library
7. `pulumi up`

```
import * as pulumi from "@pulumi/pulumi";
import * as resources from "@pulumi/azure-native/resources";
import * as azure from "@pulumi/azure";

const env = pulumi.getStack();
const config  = new pulumi.Config("azure-native");
const location = config.get("location");

const rgClassic = new azure.core.ResourceGroup(`rg-test-${env}`, {
    name: `rg-test-${env}`,
    location: location
});

const rgNative = new resources.ResourceGroup( `rg-test-native-${env}`, {
    location: location
});
```
![image](https://user-images.githubusercontent.com/9729653/110137213-d3128880-7d8d-11eb-8bfd-b8a53904f066.png)

## Context (Environment)
Pipeline failed to execute pulumi app

## Affected feature
pulumi CLI using azure credentials from `pulumi config`

**Comment by mikhailshilkov** [comment]
This is tracked in https://github.com/pulumi/pulumi-azure-native/issues/592

**Comment by agileramblings** [comment]
Thanks, @mikhailshilkov. You can close this as a duplicate then.
