### ISSUE TITLE
[Automation API] Consider adding OnOutput-callback to preview

### ISSUE THREAD

**Issue by vipentti** [pulumi/pulumi#6483]
Currently the dotnet Automation API allows providing a callback `Action<string>? OnOutput` to Up-, Refresh- and DestroyOptions.
Is there a reason no such option is available for PreviewOptions?

From what I checked, this also applies to the python and nodejs automation APIs.

**Comment by komalali** [comment]
👋 Hello! This work was just completed as part of https://github.com/pulumi/pulumi/pull/6436 and will be included in the next minor version release!

**Comment by komalali** [comment]
@vipentti I believe this was an oversight, there is no reason that this option couldn't be added to `PreviewOptions`. In fact, [python](https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/x/automation/_stack.py#L306) already includes it, it was just added to [Go](https://github.com/pulumi/pulumi/pull/6436/files#diff-723d66b142ee2a694577f698d088f893418af8c2395da7c27c277ae29fa4edf5R83-R87) and thanks to this issue I just realized it's missing from Nodejs but will be added shortly.
