### ISSUE TITLE
Valid error outputs confusing message

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi#6494]
When an error occurs in Automation API (.NET), there is much more error output that running a stack from the API. None of it is helpful.

## Expected behavior
Should output (almost) the same messaging for the CLI and Automation API

## Current behavior

I get the following errors in the output window

1. Pulumi.LogException: Error occurred during logging 
    - As a developer, I never expect to see a logging exception
2. Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="failed to connect to all addresses"
    - This makes it seem like a gRPC issue. But also, is there a race condition that allows call to be made to the host after the host is disposed?
3. System.OperationCanceledException: The operation was canceled.
    - Unless I cancelled it, I don't expect to see this exception

## Steps to reproduce

Run in VS:

```csharp
static async Task Main(string[] args)
{
    var program = PulumiFn.Create(() =>
    {
        var rg = new Pulumi.AzureNative.Resources.ResourceGroup("resourceGroup", new Pulumi.AzureNative.Resources.ResourceGroupArgs { ResourceGroupName = "some-resource-group-name", Location = "" });
    });

    var projectName = "sampleProject";
    var stackName = "dev";

    var stackArgs = new InlineProgramArgs(projectName, stackName, program);
    var stack = await LocalWorkspace.CreateOrSelectStackAsync(stackArgs);

    Console.WriteLine("successfully initialized stack");

    Console.WriteLine("updating stack...");
    var result = await stack.UpAsync(new UpOptions { OnOutput = Console.WriteLine });

    if (result.Summary.ResourceChanges != null)
    {
        Console.WriteLine("update summary:");
        foreach (var change in result.Summary.ResourceChanges)
            Console.WriteLine($"    {change.Key}: {change.Value}");
    }
}
```

## Context (Environment)

Visual Studio 2019 16.8
Pulumi CLI 2.22.0
Pulumi.Automation 2.22.0-preview

NOTE: The repro provides a clear error, but in my original code, there was not (and I still haven't solved that one). Consequently, I wasted a lot of time trying to figure out was wrong with gRPC or what was cancelling the operation. 

It's also complicating testing:

![image](https://user-images.githubusercontent.com/1784452/110660823-911c8480-8189-11eb-85dc-2f895aee3bf3.png)

## Affected feature

area/automation-api

**Comment by EvanBoyle** [comment]
@MisinformedDNA can you provide the full text of the error (with the latest pulumi 3.x preferably) as well as a summary of what the expected error would look like?
