### ISSUE TITLE
[provider] Add Exoscale as Cloud provider

### ISSUE THREAD

**Issue by matthiasbaldi** [pulumi/pulumi#6514]
## Affected feature

I saw that you already have some cloud provider integrations i.e. from [Hetzner](https://www.pulumi.com/docs/intro/cloud-providers/hcloud/).
Would it be possible that you also integrate some others cloud providers for i.e. [Exoscale](https://www.exoscale.com)?
They have a new well documented API https://openapi-v2.exoscale.com/ which could be used.

Thank you.

**Comment by lukehoban** [comment]
If anyone is interested in contributing here - please take a look at the Pulumi Package authoring documentation at https://www.pulumi.com/docs/guides/pulumi-packages/#process-of-authoring-a-pulumi-package.  If there is an existing Terraform provider, it can be bridged to work with Pulumi.  If there is not, and you would like to build a provider directly against the OpenAPI specification, you can build a Native provider.  Boilerplate and instructions for both paths are documented on that page.

**Comment by matthiasbaldi** [comment]
Currently I have not so much time to implement something. If others want to: [Exoscale Terraform](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs)

**Comment by dirien** [comment]
Hi @matthiasbaldi,

Sorry to resuracte this issue, but: 

I created the provider (https://github.com/dirien/pulumi-exoscale) and will ask @ringods to accept it in the Pulumiverse GitHub organisation (I built it with Pulumiverse in mind)

**Comment by matthiasbaldi** [comment]
That looks amazing 👍👍👍
I will test it as soon I have the possibility to load the Windows binary (currently no infra to build it that fast) for the plugin and give some feedback here!

**Comment by dirien** [comment]
@matthiasbaldi Started to transfer it to Pulumiverse orga (thx @ringods), so hopefully we will have the binary build there to use! So no need for you to build it, if you can wait!

**Comment by ringods** [comment]
@matthiasbaldi all the work has been done by @dirien to get the initial packages published:

- JS/TS: https://www.npmjs.com/package/@pulumiverse/exoscale
- Python: https://pypi.org/project/pulumiverse-exoscale/
- .NET: https://www.nuget.org/packages/Pulumiverse.Exoscale
- Go: https://github.com/pulumiverse/pulumi-exoscale/tree/main/sdk/go/exoscale

Listing in the registry is pending approval of this PR by one of my Pulumi colleagues: https://github.com/pulumi/registry/pull/1553

**Comment by dirien** [comment]
Hi @SebastienPittet, maybe you are interessted in this news too!

**Comment by matthiasbaldi** [comment]
Thanks a lot 👌🥳 @dirien & @ringods.  Short test looks amazing 👍
Found something for the nodepools, but will create an issue in the correct repo.
