### ISSUE TITLE
Removind inline route from RouteTable does not remove the routes

### ISSUE THREAD

**Issue by GaboFDC** [pulumi/pulumi#6532]
## Expected behavior
When adding in-line routes to a route table, if those in-line routes are deleted, the routes should be deleted from the route table.

## Current behavior

If you remove the routes argument from the RouteTable resource, the routes it contains should be removed as well.

## Steps to reproduce

1. Create a Routetable:

```py
import pulumi
import pulumi_aws as aws

route_table = aws.ec2.RouteTable("routeTable",
    vpc_id=aws_vpc["default"]["id"],
    routes=[
        aws.ec2.RouteTableRouteArgs(
            cidr_block="10.0.1.0/24",
            gateway_id=aws_internet_gateway["main"]["id"],
        ),
        aws.ec2.RouteTableRouteArgs(
            ipv6_cidr_block="::/0",
            egress_only_gateway_id=aws_egress_only_internet_gateway["foo"]["id"],
        ),
    ],
    tags={
        "Name": "main",
    })
```

2. Run pulumi up and wait for all to be created
3. Remove or comment the line with the routes argument.

```

import pulumi
import pulumi_aws as aws

route_table = aws.ec2.RouteTable("routeTable",
    vpc_id=aws_vpc["default"]["id"],
    tags={
        "Name": "main",
    })
```

3. run pulumi up, and no change will be shown.
4. To the routes to be actually deleted, you need to pass the arg with an empty array.

**Comment by viveklak** [comment]
Probably a manifestation of https://github.com/hashicorp/terraform-provider-aws/issues/199? Could you try with replacing the routes with an empty list instead?

**Comment by GaboFDC** [comment]
Yes i tested that at the time.
> 4. To the routes to be actually deleted, you need to pass the arg with an empty array.
Bit if is from the terraform provider, we can follow along the fix there. thanks.

**Comment by emiliza** [comment]
@GaboFDC This has been fixed upstream, and pulled in to our pulumi-aws provider. Can you try upgrading pulumi-aws to v3.36.0+? 

Please re-open if this is still an issue. Thanks!
