### ISSUE TITLE
Turn on `PULUMI_SELF_MANAGED_STATE_LOCKING=1` by default

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#6536]
In https://github.com/pulumi/pulumi/pull/2697 we added support for self-managed backend state locking behind the  `PULUMI_SELF_MANAGED_STATE_LOCKING=1` flag to ensure that we can get some real-world validation of this before making it the default, given it's potential impact on performance and correctness when using a local or cloud backend.  

Once we have sufficient real-world experience, we should flip this to be on by default.

**Comment by piclemx** [comment]
Any idea when this will be activate?

**Comment by mpatters72** [comment]
Any expected date for this?  Would be nice to not have to this set.
