### ISSUE TITLE
https://app.pulumi.com returns 404 

### ISSUE THREAD

**Issue by alex-berger** [pulumi/pulumi#6538]
The Pulumi UI (https://app.pulumi.com/) is a bit shaky today. Navigating to a project site results in 404.

## Expected behavior

I can navigate to the a project's page and do not get an 404 error.

## Current behavior

Navigating to a project site results in 404.

## Steps to reproduce

![pulumi](https://user-images.githubusercontent.com/1087375/111296759-236ecd80-864d-11eb-840e-e352166eb604.gif)

## Context

- We use GitLab as authentication provider.

<img width="1859" alt="image" src="https://user-images.githubusercontent.com/1087375/111306130-1c00f180-8658-11eb-8908-f184436619ca.png">

**Comment by jkisk** [comment]
Thank you for bringing this to our attention @alex-berger, the fix will be live a bit later today.
