### ISSUE TITLE
Add `--exclude-protected` flag to `pulumi destroy`

### ISSUE THREAD

**Issue by headconnect** [pulumi/pulumi#6539]
It's generally easy to tear-down and rebuild resources if none of them have to be protected, however with certain resource types, they might be more cumbersome and you want to ensure you don't delete them as part of the process (such as Azure KeyVault).

Working with larger amounts of resources makes it hard to tear-down and rebuild resources when one is protected, since you have to manually paste a huge list of target URNs to the `pulumi destroy` command. It would be better if I could simply say `pulumi destroy --exclude-protected` so that all unprotected resources get destroyed.

It could be implemented in such a way that it either 1) detects and prevents deletion of resources the protected resource is dependent on or 2) it would require you to manually protect those resources as well in order to successfully perform the deletion.  In my case, out of 27 resources in a given stack, I only protect the KeyVault (and the ResourceGroup, since the KeyVault slightly depends on it). 

## Affected feature

Pulumi CLI - destroy command.

**Comment by bartsmykla** [comment]
I just faced this problem, where we are generating ssh keys and saving them in GCP's Secret Manager if they are not already present. I would like to protect this secrets if they are created by pulumi during the destroy command.

I could try and help with contribution of this feature if there is somebody willing to mentor me about the process and answer my questions during the road

**Comment by debajyoti-thetaonelab** [comment]
We are creating AWS ECS Cluster & FargateService in a existing VPC(imported into pulumi), we want to delete the ECS Cluster but not the VPC as other resources not managed by pulumi also run there.

**Comment by 107ef363-c60f-46fb-a8bc-da8c5f4f6938** [comment]
Agreed, this feature would be great. I did not see this issue and suggested the same thing yesterday. I think the simplest thing to do would be to have an option like `--keep` or `--exclude` and pass the URI as an argument (essentially an inversion of `--target`).
