### ISSUE TITLE
Cannot import AWS volume

### ISSUE THREAD

**Issue by BenElgar** [pulumi/pulumi#6541]
`pulumi import` does not appear to work to import AWS volumes. Note that this EC2 volume was originally created using Pulumi.

## Expected behavior

The volume should be appropriately imported into the Pulumi state with `pulumi import`.

## Current behavior

The `pulumi import` raises an error as follows:

```
❯ pulumi import -f import.json
Previewing import (deref/playground)

View Live: https://app.pulumi.com/deref/playground/playground/previews/cff1b9ab-4658-41e6-a825-d12e153d137d

     Type                 Name                   Plan       Info
     pulumi:pulumi:Stack  playground-playground             1 error
 =   └─ aws:ebs:Volume    vol-0764febc948d2201c  import     3 errors

Diagnostics:
  aws:ebs:Volume (vol-0764febc948d2201c):
    error: aws:ebs/volume:Volume resource 'vol-0764febc948d2201c' has a problem: AtLeastOne: "snapshot_id": one of `size,snapshot_id` must be specified
    error: aws:ebs/volume:Volume resource 'vol-0764febc948d2201c' has a problem: AtLeastOne: "size": one of `size,snapshot_id` must be specified
    error: Preview failed: one or more inputs failed to validate

  pulumi:pulumi:Stack (playground-playground):
    error: preview failed
```
`import.json`:
```json
{
  "nameTable": {
    "aws-us-west-2": "urn:pulumi:playground::playground::pulumi:providers:aws::provider-us-west-2"
  },
  "resources": [
    {
      "id": "vol-0764febc948d2201c",
      "name": "vol-0764febc948d2201c",
      "provider": "aws-us-west-2",
      "type": "aws:ebs/volume:Volume"
    }
  ]
}
```

```
❯ aws ec2 describe-volumes --volume-ids vol-0764febc948d2201c
{
    "Volumes": [
        {
            "Attachments": [
                {
                    "AttachTime": "2021-03-10T15:17:33+00:00",
                    "Device": "/dev/xvda",
                    "InstanceId": "i-0f382f83d254d5ba4",
                    "State": "attached",
                    "VolumeId": "vol-0764febc948d2201c",
                    "DeleteOnTermination": true
                }
            ],
            "AvailabilityZone": "us-west-2d",
            "CreateTime": "2021-03-10T15:17:33.789000+00:00",
            "Encrypted": false,
            "Size": 8,
            "SnapshotId": "snap-0be809745585ffdf2",
            "State": "in-use",
            "VolumeId": "vol-0764febc948d2201c",
            "Iops": 100,
            "VolumeType": "gp2",
            "MultiAttachEnabled": false
        }
    ]
}
```

## Steps to reproduce

1. Create an EC2 volume. In this case the volume was created implicitly by creating an EC2 instance with the following command:
```javascript
    new aws.ec2.Instance(
      name,
      {
        ami: 'ami-0f9eefbab78499455', // Amazon Linux 2 HVM on ARM, 64-bit w/ SSD volume support.
        instanceType: 't4g.micro',
        userData: "<omitted>",
        vpcSecurityGroupIds: ["<omitted>"],
        subnetId: bastionSubnetId,
      }
    );
```
2. Attempt to import the created volume into a different Pulumi stack using `pulumi import` with an import file similar to the one above

## Context (Environment)

We're trying to create tools to allow people to generate Pulumi import files for arbitrary infrastructure. Dogfooding this on our own infrastructure, which is itself mostly managed via Pulumi, we run into issues. The specific case of handling resources that are already managed by Pulumi is not particularly important for us but it uncovers an issue with importing volumes more widely.

## Affected feature

`pulumi import`

**Comment by viveklak** [comment]
@BenElgar given you are trying to import a volume through the json file, you need to include a size field for the volume since that is required to be able to create it in the first place through the aws SDK. In the case of the creation process you mentioned, EC2 internally maps the ami ID for the instance to a volume size/snapshot. It doesn't seem reasonable to expect Pulumi to discover this implicit link during imports.

**Comment by BenElgar** [comment]
Thanks @viveklak! That makes sense. Is there a mechanism to provide such necessary information via the JSON file? Or is an AWS volume of this description essentially not possible to import with `pulumi import`?

**Comment by viveklak** [comment]
If you specify the size in the json, I expect it to work.

**Comment by viveklak** [comment]
That said, we do have a problem in that Pulumi is only populating required fields when trying to import the resource through the CLI and missing some of the additional constraints (such as exactly one) . I cut https://github.com/pulumi/pulumi/issues/6547 for tracking that.

You should still be able to import with the json file with the additional property or through the code (https://www.pulumi.com/docs/guides/adopting/import/#pulumi-import-resource-operation) if the required fields are specified.

**Comment by BenElgar** [comment]
I'm sure that providing the missing fields in code would work but my hope was to have `pulumi import` generate the necessary code.

I've tried providing both `size` and `snapshot_id` in the JSON file, individually and together, in every combination of case and type that I could imagine without any success, e.g.

```json
{
  "id": "vol-0764febc948d2201c",
  "name": "vol-0764febc948d2201c",
  "provider": "aws-us-west-2",
  "type": "aws:ebs/volume:Volume",
  "size": 8
}
```

From a brief inspection of the implementation of `pulumi import` it would appear that there isn't support for providing any additional parameters to a resource: https://github.com/pulumi/pulumi/blob/1731053b1839c608efcdefa4687d9d17632e1632/pkg/cmd/pulumi/import.go#L98-L105

Assuming I'm correct, my expectation would be that `pulumi import` returned a clearer error indicating that that resource type wasn't supported for importing in such a manner. Though obviously it would be even better if those additional properties could be supplied.
