### ISSUE TITLE
Secrets filtering is over-aggressive

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi#6548]
In https://github.com/pulumi/pulumi/blob/f6ec691544770813e16ca8fd41dafee6aa7c7690/pkg/engine/events.go#L225 we add a filter for secret values from logging. However, this filtering is over-aggressive as it removes all partial matches and even cases where the output itself happens to coincide as a secret value (e.g. I might have a secret output `foo` and I happen to `console.log("foo")` which will cause the filtering to replace with `[secret]`). This behavior is confusing for the end user since it's not clear why things are being marked as `[secret]`.

**Comment by EvanBoyle** [comment]
@leezen do you have any ideas for action here? If this were to be exact match only, what characters should be included on either side (whitespace, ':', etc)? 

There is some code in the filter that prevents filtering secrets less than length 3: https://github.com/pulumi/pulumi/blob/80f1989600a307d3dee40dcd59504e3d9c43dad4/sdk/go/common/util/logging/log.go#L126

Overall, seems like erring on the side of conservative is the right move here.

**Comment by leezen** [comment]
@EvanBoyle I originally filed this issue as a community member observed this behavior and was surprised by it. I agree that erring on the conservative side is 'correct' here and notably, this is the behavior systems like GHA exhibit as well. I'll close this for now as `by-design` given the lack of engagement with the issue.
