### ISSUE TITLE
Set stack tags in a config file

### ISSUE THREAD

**Issue by runlevel5** [pulumi/pulumi#6552]
Pulumi stack tags are being set via `pulumi stack tag set` CLI which is totally fine if users don't have a large amount of stacks. However to set tag for a large amount of stacks, the job would be more error-prone and time-consuming. So I've been thinking why don't pulumi allow users to set tags within the `Pulumi.yaml` (for global config) and `Pulumi.<stackName>yaml` (for stack config). I am unsure what the interface would be, but I think something like:

```
# Pulumi.yaml
tags:
  - tag1
  - tag2
  - tag3
```

```
# Pulumi.<stackName>yaml
pulumi:
  tags:
    - tag4
```

**Comment by runlevel5** [comment]
FYI @shadeven

**Comment by stack72** [comment]
Hey @runlevel5 

Thanks for opening this - I am going to close it as a dupe of #5004 and allow this to be tracked from that issue (as we can track how long the issue is open for)

Please add a reaction or a comment in that issue to ensure we can see how many people would want this

Thanks

Paul
