### ISSUE TITLE
stack import: handle empty string in dependency gracefully

### ISSUE THREAD

**Issue by woeps** [pulumi/pulumi#6553]
If a stack file is being imported with some dependency as an empty string, the import shouldn't fail but gracefully disregard that empty string dependency. Currently there is a not so obvious error message in place, but this could be more user friendly.

## Affected feature

CLI command `pulumi import`

When a stack's state got inconsistent:
```
error: the current deployment has 1 resource(s) with pending operation
```
I deleted the resource (having the pending operation) manually and removed pending operation from exported stack.
Then `pulumi import` yielded the following error message:
```
error: 2 errors occurred:
    1) state file contains errors: resource urn:project:stack::api::aws:cognito/userPool:UserPool::UserPool dependency  refers to missing resource
    2) importing this file could be dangerous; rerun with --force to proceed anyway
```
The mentioned resource had a dependency of `[ "" ]` (array with a single element of an empty string which tripped up the import. I don't know how this empty string ended up there exactly. (I haven't touched that part of the stack export.)
Would be nice to have an error handling in place which just disregards empty strings.

**Comment by EvanBoyle** [comment]
@woeps do you have a repro with minimal code and steps to get into this state? 

Did you specify the empty dependency (`[""]`)? If so this is by design.
