### ISSUE TITLE
Failing to install inside Docker container on Apple M1 Silicon 

### ISSUE THREAD

**Issue by holmok** [pulumi/pulumi#6555]
## Expected behavior
I should be able to build a docker container that installs the Pulumi tools inside of it.

## Current behavior
I have a `node:15.10-slim` docker image I am trying to build that installs Pulumi tools. When I run the install curl I get this message:

```
#10 1.143 error: We're sorry, but it looks like Pulumi is not supported on your platform                       
#10 1.143        We support 64-bit versions of Linux and macOS and are interested in supporting                
#10 1.143        more platforms.  Please open an issue at https://github.com/pulumi/pulumi and
#10 1.143        let us know what platform you're using!
#10 1.143 
#10 1.143 We're sorry, but it looks like something might have gone wrong during installation.
#10 1.143 If you need help, please join us on https://slack.pulumi.com/
```

## Steps to reproduce

1. Create a docker file as follows:
```
FROM node:15.10-slim

# UPDATE IMAGE INSTALL SYSTEM SOFTWARE
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install curl -y

# SETUP PULUMI
RUN curl -fsSL https://get.pulumi.com/ | bash
RUN export PATH=$PATH:$HOME/.pulumi/bin
```
2.  run ` docker build -t my-container .`

## Context (Environment)

This is running on a Mac Mini M1 with 16GB RAM.  Docker version: Docker version 20.10.1, build 831ebeae96

**Comment by stack72** [comment]
Hi @holmok 

My apologies about this - there is a pending release in a few hours that will fix this up! I will circle back when v2.23.0 has been released with the new capabilities

Paul

**Comment by holmok** [comment]
Thanks for the quick follow-up!

**Comment by stack72** [comment]
Hi @holmok 

I believe you will be good now in this area! Please note, only the latest binaries and CLI releases have an arm64 build so to take advantage, you will need to be on the latest of each

Please let me know if there are any issues and I will be able to help fix them up

Paul

**Comment by stack72** [comment]
I've not heard back on this issue and it's been 6 days since we have released our arm based binaries

Please let me know if there are any other issues

Paul
