### ISSUE TITLE
Homebrew install of Pulumi doesn't show the version

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#6565]
```
▶ which pulumi
/usr/local/bin/pulumi
```

```
▶ pulumi version

warning: A new version of Pulumi is available. To upgrade from version '0.0.0' to '2.22.0', run
   $ brew upgrade pulumi
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

Suspected that ldflag isn't working as expected during the build

**Comment by stack72** [comment]
The bump of the homebrew package is as follows - https://github.com/Homebrew/homebrew-core/commit/02acd866e2b4ec1018896e10591777abe23dde91

**Comment by stack72** [comment]
The issue here is that homebrew installs run "make brew" to install Pulumi. Since the 3.0.0 release machinery changes, Pulumi now uses "pulumictl" to determine the version of the software - this isn't available as part of the homebrew setup on a customer machine so therefore the version passed to the ldflag is empty and thus an empty response from pulumi verison command

**Comment by leshibily** [comment]
is this fixed?

**Comment by stack72** [comment]
Hi @leshibily 

I am preparing the release right now

**Comment by leshibily** [comment]
Hi @stack72 

Thanks for working hard to get the right away
