### ISSUE TITLE
Migration of nextgen to native fails if custom components are used as parents

### ISSUE THREAD

**Issue by imod** [pulumi/pulumi#6570]
## Expected behavior
Migration of `nextgen` provider to `native` provider should not cause delete/create of existing resources on azure.

## Current behavior
When doing the migration, all resources which have a custom component as a parent, will be recreated.

## Steps to reproduce

I created a small dummy project which shows the problem: https://github.com/imod/azure-nextgen-migration

## Context (Environment)
Before migration:

    "@pulumi/azure-nextgen": "^0.4.0"
    "@pulumi/pulumi": "^2.17.2"

After migration:

    "@pulumi/azure-native": "^0.7.1"
    "@pulumi/pulumi": "^2.22.0"

**Comment by mikhailshilkov** [comment]
Moved to `pulumi/pulumi` as I think this error isn't specific to the native Azure provider

**Comment by EvanBoyle** [comment]
@komalali any intuition on whether or not this would've been fixed by https://github.com/pulumi/pulumi/pull/7605?

**Comment by komalali** [comment]
@EvanBoyle I don't *think* so. I'm really not sure what's going on here but the issue I fixed was specific to usage of `--target` not including children.

**Comment by justinvp** [comment]
I'm going to close this as fixed. There were some old bugs related to aliases within components that have long since been addressed.
