### ISSUE TITLE
pulumi up is using my kubeconfig, but isn't respecting namespace

### ISSUE THREAD

**Issue by zdog234** [pulumi/pulumi#6588]
When I run `pulumi up`, it's connecting to my cluster (so I know it's seeing + using my kubeconfig file). However, I'm getting a permission error because it's trying to do stuff in the "default" namespace, which I don't have access to, even though my namespace is configured as `personalid` in my kubeconfig file.

## Expected behavior

I would expect `pulumi up` to create a deployment in my `personalid` namespace

## Current behavior

`pulumi up` attempts to create a deployment in the `default` namespace

## Steps to reproduce

1. Configure a kubeconfig file with credentials that have access to the `foobar` namespace in a cluster, but not the `default` namespace
2. Run `pulumi up` in one of the example kubernetes projects

## Context (Environment)

I'd like to be able to use `pulumi up` in my personal k8s namespace without messing around with custom providers

## Affected feature

`pulumi up`

Thanks :)
I was going to write some custom `pyinvoke` scripts, but the "pulumi vs custom" section of your docs convinced me to try getting pulumi working -- just because I'm able to understand my custom k8s build scripts doesn't mean someone else will be able to maintain them (which is especially important for the use case I'm currently working on)

**Comment by viveklak** [comment]
Are you setting the namespace for the resources in your code? The provider relies on the default behavior of kubernetes clients in this case which defaults to `default` namespace when omitted.
