### ISSUE TITLE
Improve CONTRIBUTING.md documentation

### ISSUE THREAD

**Issue by catmeme** [pulumi/pulumi#6602]
To work on [pulumi/pulumi-awsx](https://github.com/pulumi/pulumi-awsx) I’ve resorted to reverse engineering the process from the [Makefile](https://github.com/pulumi/pulumi-awsx/blob/master/Makefile), as the [README.md](https://github.com/pulumi/pulumi-awsx/blob/master/README.md) and [CONTRIBUTING.md](https://github.com/pulumi/pulumi-awsx/blob/master/CONTRIBUTING.md) didn't provide enough information for me to onboard myself.

I found that `yarn` and [pulumictl](https://github.com/pulumi/pulumictl) are required, then I can run `make build_nodejs` as long as I have `tsc` in my `PATH` , then I’m able to run `make test`.

The [pulumi/pulumi-awsx/CONTRIBUTING.md](https://github.com/pulumi/pulumi-awsx/blob/master/CONTRIBUTING.md) seems inaccurate, unless I’m missing a step.  `make test_all` does not exist in the `Makefile` and the main [pulumi/pulumi/CONTRIBUTING.md](https://github.com/pulumi/pulumi/blob/master/CONTRIBUTING.md) is not very relevant to developing for this nodejs package.

Additional instructions on how to test changes to libraries in your own Pulumi projects would be nice.

**Comment by guineveresaenger** [comment]
Hi @catmeme! 

We've recently https://github.com/pulumi/pulumi/pull/8894 to better reflect the current state of the world. We added a section on how to reach maintainers and the community, as well as updated the Make build system information.

Additionally, we are consolidating all Pulumi ecosystem repository contribution guides to refer to the central pulumi/pulumi one, with [repository-specific additions](https://github.com/pulumi/pulumi-aws/pull/1803). These are living documents, so we hope you will continue to assist us in improving them.
