### ISSUE TITLE
Permissions error when running `pulumi new <path_to_repo_folder>

### ISSUE THREAD

**Issue by lifeofzero** [pulumi/pulumi#6608]
I am trying to maintain a configuration repo that will have specific project settings for my three stacks (dev, stage, prod).  
From this configuration repo I would like to use it as a base to seed new repos/services.  I get two failures with 'permission denied'

- We need to create a new repo that maps to a service
- developer creates a new folder locally for their service
- inside this folder they create a folder 'infrastructure/dev'
- from this dir they run pulumi new <path_to_local_git_pulumi_config_repo>
- this runs but errors out with  
## Expected behavior

I would think that I could run` pulumi new <path_to_github_config_repo> `and it would populate the folder with the pulumi base yaml and python from the config repo that I have.  Then I can modify the __main__.py with my new code and deploy into the given stack (dev, stage, or prod) using `pulumi up`

## Current behavior

I get the following error during `pulumi new`
reated stack 'dev'
Creating virtual environment...
Finished creating virtual environment
Updating pip, setuptools, and wheel in virtual environment...
error: updating pip, setuptools, and wheel via '/Users/tyler/projects/propel-api/infrastructure/dev/venv/bin/python -m pip install --upgrade pip setuptools wheel': fork/exec /Users/tyler/projects/propel-api/infrastructure/dev/venv/bin/python: permission denied

From this directory I can run `pip install -r requirements.txt` and it does work, but if I then run `pulumi up` I get the following error.
error: failed to discover plugin requirements: fork/exec /Users/tyler/projects/propel-api/infrastructure/dev/venv/bin/python: permission denied

## Steps to reproduce

1. create a new repo on git for the new service
2. git clone locally
3. cd to repo folder
4. git branch
5. pulumi new <path_to_local_git_pulumi_config_repo>
6. Get the above permissions denied error
7. pip install -r requirements.txt
8. pulumi up
9. Get the above failed to discover plugin requirements

## Context (Environment)

I am trying to create a developer workflow that has a baseline set of pulumi configurations for each of the stacks that we will operate from.  This configuration will be managed in a git repo and will only have dev, stage, prod configurations for pulumi and right now GCP

**Comment by lifeofzero** [comment]
Figured it out, the 'venv' from the config project was getting copied across to the new project I was creating.  Once I removed the 'venv' from the config directory (it was not checked into git, but hung around from when I originally created it) everything was seeded correctly and installed correctly.  Not sure if there's a check pulumi wants to do if a repo path is passed into 'new' and it contains a venv folder.

**Comment by t0yv0** [comment]
Looks like it's possible to reproduce:

```
#!/bin/sh

mkdir template
pushd template
pulumi new --yes aws-python --name "template-6608-1"
popd

mkdir user-project
pushd user-project
pulumi new --yes ../template --name "user-project-6608-1"
popd
```
