### ISSUE TITLE
[python, go, dotnet] Make custom available to Mocks::newResource

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#6617]
In https://github.com/pulumi/pulumi/pull/6551 we added support for a `custom` argument to `newResource` mocks for Node.js.  We need to do this in the other languages as well.

Per discussion on that PR, we will likely address this with a breaking change to accept a property bag instead of discreet arguments, to ensure we do not have to make further breaking changes here in the future.

**Comment by stack72** [comment]
Closed via #6672
