### ISSUE TITLE
Pulumi removes state during "pulumi up"

### ISSUE THREAD

**Issue by nowak-ninja** [pulumi/pulumi#6618]
Hey Pulumi Team,

I have observed that during `pulumi up` the tool removes state file from the backend (in our case it's Alicloud OSS [S3 API]) and if You cancel command execution by pressing CTRL+C or another way, You are left without state at the end.

## Expected behavior

State not removed instantly but replaced at the end of the process.

## Current behavior

State file removed right after `pulumi up`

## Steps to reproduce

1. prepare IaaC code
2. run `pulumi up`
3. observe state file dissapearance

## Affected feature
Stack update/deletion.

**Comment by EvanBoyle** [comment]
@nowak-ninja do you have a repro for this? I tried `ctrl+c` a few times on an update and did not have my state deleted.
