### ISSUE TITLE
Better error handling when deploying from an M1 (arm) machine

### ISSUE THREAD

**Issue by atlipall** [pulumi/pulumi#6626]
When trying to deploy using an Apple M1 machine to a stack with a version of the kubernetes plugin prior to 2.8.3 it fails to download the plugin with 403 error and no useful error message.

## Expected behavior
An error message stating that the version of the plugin is not compatible with ARM/M1 and with suggestions on how to fix it.

## Current behavior
`pulumi up` errors with the following message:
`error: could not load plugin for kubernetes provider 'urn:pulumi:xxx-xxx-xxx::xxx-xxx::pulumi:providers:kubernetes::default_2_6_1': no resource plugin 'kubernetes-v2.6.1' found in the workspace or on your $PATH, install the plugin using 'pulumi plugin install resource kubernetes v2.6.1'`

Running the suggested plugin install command results in:
`[resource plugin kubernetes-2.6.1] installing
error: [resource plugin kubernetes-2.6.1] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-kubernetes-v2.6.1-darwin-arm64.tar.gz`

Even though version 2.8.3 is set in requirements.txt and already installed

## Steps to reproduce

1. Setup an existing pulumi project, with an older version of the kubernetes plugin, on an Apple M1
2. Update requirements.txt with `pulumi-kubernetes==2.8.3` (if a python project)
3. Run `pulumi up`

## Context (Environment)
Trying to deploy an existing stack using a fresh development machine (Macbook Pro M1)

**Comment by leezen** [comment]
I'll leave this issue open to track the better error handling as suggested. But, separate from that, we'll actually need to resolve https://github.com/pulumi/pulumi-kubernetes/issues/1487 (or at least bump the version so that there's an ARM version of the plugin available).

**Comment by justinvp** [comment]
https://github.com/pulumi/pulumi-kubernetes/issues/1487 has been fixed. We've been publishing ARM versions for quite a while now. At this point, it's not worth improving the error message for when very old ARM versions are not available.
