### ISSUE TITLE
Seemlessly swtich between backends

### ISSUE THREAD

**Issue by gerrywastaken** [pulumi/pulumi#6629]
# The problem

When I'm just testing something I want to be able to use a local backend as it's much faster for testing changes quickly (fiber still isn't quicker than the connection to my SSD). However I still want to use Pulumi's backend when I know the change I actually want to make.

Switching to a local backend seems quite simple:
```
pulumi login --local
```
However switching back is more involved:

```
> pulumi logout; pulumi login

Manage your Pulumi stacks by logging in.
Run `pulumi login --help` for alternative login options.
Enter your access token from https://app.pulumi.com/account/tokens
    or hit <ENTER> to log in using your browser                   : 
```
1. open browser with link
2. login to pulumi.com
3. create a new token
4. paste it into the terminal.

(I already previously entered token, so I'm not sure why it is needed again)

There apparently isn't a: `pulumi login --standard`

I've created a work around:
```
function pulumi_login_local
  cp ~/.pulumi/credentials.json.local ~/.pulumi/credentials.json
  pulumi stack select standard_dev
end

function pulumi_login_standard
  cp ~/.pulumi/credentials.json.pulumi ~/.pulumi/credentials.json
  pulumi stack select local_dev
end
```
But this is just a hack and is likely to break the next time Pulumi updates the credentials file.

## Affected feature

However, really I'm not looking to change accounts at all, what would be better would be something like `git`s concept of remotes:

In the same way as I can:
`git push office`
or
`git push nasbox`

I'd like to
`pulumi up standard`
or
`pulumi up local`

Each would likely have to have their own namespaced stack, much like I did in my work around: e.g. `{remote_name}_{stack_name}`. This seems to be different to what was asked in https://github.com/pulumi/pulumi/issues/6029, however this may be a solution to both issues.

**Comment by komalali** [comment]
You can use an alternate backend for specific commands by using the `PULUMI_BACKEND_URL` [environment variable](https://www.pulumi.com/docs/intro/concepts/state/#f31294c1-d481-42f0-9778-ff5412e26656:~:text=PULUMI_BACKEND_URL). Would that serve your purpose?

**Comment by gerrywastaken** [comment]
@komalali Thank you for the response. However I created the issue because PULUMI_BACKEND doesn't appear to work in this way. I wish it did.

```
> pulumi stack ls
NAME  LAST UPDATE     RESOURCE COUNT  URL
dev*  15 minutes ago  3               https://app.pulumi.com/Caulfield/backend_test/dev
> pulumi login --local
Logged in to local as gerry (file://~)
> pulumi stack ls
NAME  LAST UPDATE  RESOURCE COUNT
> PULUMI_BACKEND=https://app.pulumi.com/Caulfield pulumi up
Please choose a stack, or create a new one:  [Use arrows to move, enter to select, type to filter]
> <create a new stack>
```
