### ISSUE TITLE
Automation: overwriting existing Pulumi.yaml

### ISSUE THREAD

**Issue by headconnect** [pulumi/pulumi#6632]
When running an automation script with the name of the project specified, as well as workdir specified as `"."`, automation overwrites the existing `Pulumi.yaml` file instead of reading its contents.

This also means that it will not find the selected stack as, in my case, the Pulumi.yaml contains the "config" parameter to indicate that my stacks are stored in the `stacks/` folder. Therefore it creates a new stack in `"."` and complains that it cannot read config.requireObject("---") parameters.

## Expected behavior

I would expect that automation attempts to read the existing `Pulumi.yaml` file before overwriting it, and thus using the correct stack.

## Current behavior

Currently automation will overwrite an existing `Pulumi.yaml` with just `name:` and `runtime:` fields, where name is a required parameter set to LocalWorkspace.selectStack().

Workaround is to manually read the `Pulumi.yaml` and pass its contents to the `projectSettings` key of the second parameter to LocalWorkspace.selectStack(). This will still overwrite `Pulumi.yaml` but it will be overwritten with the same contents (just slightly different formating). 

## Steps to reproduce

Example of reproduction here:
https://github.com/headconnect/pulumi-bug-reproducer/tree/issue/automation-6632-overwriting-pulumi-yaml

## Context (Environment)

This occurs with both tsc & ts-node execution on windows 10. 

This makes it scary to use automation on any form of important resource stacks, as the behavior might be unpredictable.

**Comment by EvanBoyle** [comment]
Yes, this looks like a bug. The implementation checks for the presence of a projectSettings object. It should also check if a workdir containing a project is specified. Probably it should work as:

1. Use project settings if specified
1. If workdir is specified, try to call `getProjectSettings`
2. Finally, create the default project if this is an inline program.
