### ISSUE TITLE
Calculate build version once and reuse it

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#6634]
A potential hole was found in our builds due to https://github.com/pulumi/docs/issues/5507

Wr effectively found that when we tag a release, if an existing build is running, the publish step of that release will pull all the tags from the repository and then use those tags to calculate the version

therefore, we could be running tests of the master build as part of an "alpha" release and if we pushed a release tag (e.g. v2.21.2), the master build could use that v2.21.2 tag and then publish an artifact of that name. That would have a specific checksum. When the release build kicked in, it would recreate a new version of that binary and publish that + those checksums to S3 as well as GitHub. That could put us in a situation where we are serving incorrect binaries

**It looks like this only happened once - v2.23.1**

We should change the build process to calculate the release versions (for each language + Go binaries) at the start of the process and then re-use those versions throughout the build process

**Comment by t0yv0** [comment]
This contributes to checksum check failures, happened a half-dozen times now. The issue description is perfect. We ended up using a similar approach in pulumi-java fwiw https://github.com/pulumi/pulumi-java/blob/main/.github/workflows/pr.yml#L88 - calculate versions once and share via artifacts. It guards against the race.
