### ISSUE TITLE
Add `--code-only` feature to `pulumi import`, getting code without updating stack/state

### ISSUE THREAD

**Issue by glitchwizard** [pulumi/pulumi#6653]
Currently we can use `pulumi import`, and doing so updates the state of the stack imported. It would be great to have the something like `pulumi import --code-only` where it only gets the code and does not update the state of the stack. 

Currently the only way we know how to do this is run `pulumi import` and then delete the most recent updated stack state. 

## Affected feature

`pulumi import` would be affected, giving it an option to exclude updating the state of the stack upon import. This would allow us to get the code for the part, somewhat like a template, and then use it elsewhere, without having to worry about the state of our stack potentially changing.

**Comment by mikhailshilkov** [comment]
This is very close to https://github.com/pulumi/pulumi/issues/8836 so we'll use that issue to track this improvement
