### ISSUE TITLE
PR Contribution Guide Outdated

### ISSUE THREAD

**Issue by DSoko2** [pulumi/pulumi#6660]
It would be nice if the following could be addressd in the [PR Contribution Guide](https://github.com/pulumi/pulumi/blob/master/CONTRIBUTING.md#submitting-a-pull-request) as these questions are unclear to me (and most probably to other future collaborators, too):

1. What is the quality gate and how can it be tested? Currently only `make travis_pull_request` is mentioned, which is definitely outdated information.
2. What information to provide in the PR description?
3. How and when will the maintainers react to PRs? This transparency allows to avoid frustration at the contributor and avoids unnecessary polling. Also, a hint when and how it is appropriate to remind the maintainers would be nice.

**Comment by stack72** [comment]
Hi @DSoko2 

I apologise here - you are 100% correct that this guide is out of date and I will ensure we add more information here

This was recently brought up by someone else so it's definitely something I will get acted upon and get more information available

You can feel free to ping me directly if you have immediate questions and we will be able to work together on getting you unblocked here

Paul

**Comment by guineveresaenger** [comment]
Hi @DSoko2,
we've recently [updated our contributor docs](https://github.com/pulumi/pulumi/pull/8894) to better reflect the current state of the world. We added a section on how to reach maintainers and the community, as well as updated the Make build system information.
Additionally, we are consolidating all Pulumi ecosystem repository contribution guides to refer to the central pulumi/pulumi one, with repository-specific additions. These are living documents, so we hope you will continue to assist us in improving them.
