### ISSUE TITLE
Python dynamic resources can't set extra outputs

### ISSUE THREAD

**Issue by chrisglass** [pulumi/pulumi#6678]
When writing a python dynamic provider, setting outputs on the "outs" parameter of the CreateResult instance returned by the create() method does not make those new fields available as an Output for the created Resource.

## Expected behavior
Entries added to "outs" are available on the resource as extra outputs

## Current behavior
Entries added to "outs" are not available on the resource as extra outputs

## Steps to reproduce
Here is a minimal example demonstrating the issue:

```python
class CustomProvider(ResourceProvider):
    def create(self, props):
        name = props["name"]
        unique_suffix = binascii.b2a_hex(os.urandom(4)).decode("utf-8")
        # This random bit is just some random data we'd like to expose as an output.
        # This could be a field returned by a remote API instead, or whatever.
        random_bit = binascii.b2a_hex(os.urandom(16)).decode("utf-8")

        resource_id = name + "-" + unique_suffix

        state = {
            "name": name,
            "random_bit": random,  # Here we add a new output to the resource
        }

        return CreateResult(resource_id, outs=state)


class Custom(Resource):
    def __init__(self, name, parameter, opts=None):
        props = {"name": name, "parameter": parameter}
        super().__init__(CustomProvider(), name, props, opts)


random1 = Custom("name1", "a parameter") # For now, no problem
random2 = Custom("name2", random1.random_bit) # This doesn't work. I expected to have a dependency between resources

```

## Context (Environment)
This prevents me from returning outputs that are not known in advance - for example, my production code wraps calls to the AWS service catalog (that is not supported in the official library). The servicecatalog objects also have "outputs" that I'd like to make available through the Resource, but I can't tell what they are in advance. 

## Affected feature

Not sure.

**Comment by chrisglass** [comment]
It might be a limitation of the two-phase pass on the code (one creating essentially Futures and the second pass realizing them).

How should I expose e.g. servicecatalog outputs to the rest of pulumi, if that is the case?

**Comment by mikhailshilkov** [comment]
I believe you should declare those outputs explicitly as shown in https://github.com/pulumi/examples/blob/master/aws-py-dynamicresource/mysql_dynamic_provider.py#L89

**Comment by chrisglass** [comment]
Ah I see. So this is a bit awkward, but workable.

In case somebody is facing the same problem in the future an stumbles upon this post, here's the above example fixed (really, it's creating a single static output that happens to be a further dict):

```python
class CustomProvider(ResourceProvider):
    def create(self, props):
        name = props["name"]
        unique_suffix = binascii.b2a_hex(os.urandom(4)).decode("utf-8")
        # This random bit is just some random data we'd like to expose as an output.
        # This could be a field returned by a remote API instead, or whatever.
        random_bit = binascii.b2a_hex(os.urandom(16)).decode("utf-8")

        resource_id = name + "-" + unique_suffix

        state = {
            "name": name,
            "extra_outputs": {'random_bits': random},  # Here we add a new output as an entry in the bag of extra stuff
        }

        return CreateResult(resource_id, outs=state)


class Custom(Resource):
    def __init__(self, name, parameter, opts=None):
        props = {"name": name, "parameter": parameter, "extra_outputs": None} # Note how it's defining the extra_outputs here.
        super().__init__(CustomProvider(), name, props, opts)


random1 = Custom("name1", "a parameter")
random2 = Custom("name2", random1.extra_outputs)

```
