### ISSUE TITLE
`pulumi import` in the cli not working with certain Dynamo DB tables

### ISSUE THREAD

**Issue by glitchwizard** [pulumi/pulumi#6690]
Trying to import a dynamo DB using `pulumi import` can sometime result in the following error: `All attributes must be indexed. Unused attributes: ["<name of attribute>"]`

We can import a table with no secondary indexes and no sort key, but on one table we get the error on the secondary index key, and on the other we get the error on the sort key. 

## Expected behavior

It should import the table and provide the code to recreate it in Typescript/NodeJS

## Current behavior

Running the command `pulumi import aws:dynamodb/table:Table <pulumi resource name> <aws resource name>` gives us an error stating 

```
aws:dynamodb:Table (foo):
    error: Preview failed: diffing urn:pulumi:local::foobar::aws:dynamodb/table:Table::foo: 1 error occurred:
    	* All attributes must be indexed. Unused attributes: ["bar"] 
```

## Steps to reproduce

1. Create a dynamodb table with a secondary index, or a sort key, and populate it with some data
2. run `pulumi import` on that table

## Context (Environment)

We're working on moving our CloudFormation IAC fully to Pulumi

## Affected feature
`pulumi import` in the cli

**Comment by cesmunoz** [comment]
Is there an update with this? I'm facing the same situation. I have tables with partition key and sort key and I cannot import them into pulumi

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in #8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
