### ISSUE TITLE
Automation API - not possible to set structured configuration?

### ISSUE THREAD

**Issue by damianh** [pulumi/pulumi#6700]
I'm trying to set some structured config (`--path` when done via cli) via the automation API and it doesn't seem to work whatever format I attempt. My use case is running some pulumi infra against dynamodb local as part of an integration test.

If my config were yaml, this is what it would look like:

```yaml
config:
  aws:accessKey: not
  aws:endpoints:
    - dynamodb: http://localhost:8000
  aws:region: us-east-1
  aws:secretKey: used
  aws:skipCredentialsValidation: true
  aws:skipRequestingAccountId: true
```

My code:

```csharp
    await RunAsync("pulumi", "login --local --non-interactive"); // (is there a better approach than this?)
    var workspaceOptions = new LocalWorkspaceOptions
    {
        Program = PulumiFn.Create<DefaultStack>(),
        ProjectSettings = new ProjectSettings("dynamodb-tests", ProjectRuntimeName.Dotnet),
        EnvironmentVariables = new Dictionary<string, string>
        {
            { "PULUMI_CONFIG_PASSPHRASE", "secret" }
        }
    };
    var workspace = await LocalWorkspace.CreateAsync(workspaceOptions);
    await workspace.InstallPluginAsync("aws", "v3.35.0");
    var workspaceStack = await WorkspaceStack.CreateOrSelectAsync("testing", _workspace);

    await _workspaceStack.SetConfigAsync(new Dictionary<string, ConfigValue>
    {
        {"aws:region", new ConfigValue("eu-west-1")},
        {"aws:accessKey", new ConfigValue("not")},
        {"aws:secretKey", new ConfigValue("used")},
        {"aws:skipCredentialsValidation", new ConfigValue("true") },
        {"aws:skipRequestingAccountId", new ConfigValue("true") },
        {"aws:endpoints[0][\"dynamodb\"]" , new ConfigValue("http://localhost:8000")} // <-- Cant get this to work
    });
```

There error I always get is :

```
Diagnostics:
  aws:dynamodb:Table (table):
    error: could not validate provider configuration: 1 error occurred:
    	* Invalid or unknown key
```

So... how do I set a service endpoint url via automation API? cheers

Related docs: https://www.pulumi.com/docs/intro/concepts/config/#structured-configuration
Related slack thread: https://pulumi-community.slack.com/archives/CRH5ENVDX/p1617474199168800

(not sure whether this is a bug or an enhancement request tbh)

**Comment by vipentti** [comment]
I think this is related to https://github.com/pulumi/pulumi/issues/6352

**Comment by komalali** [comment]
You can set this via automation api with:

**Comment by komalali** [comment]
Also, instead of `await RunAsync("pulumi", "login --local --non-interactive");` you could pass in the env var [PULUMI_BACKEND_URL](https://www.pulumi.com/docs/intro/concepts/state/#831920a2-b77a-4cbd-a5b2-13ff163cae1e:~:text=PULUMI_BACKEND_URL) to your workspace, i.e. 

```csharp
EnvironmentVariables = new Dictionary<string, string>
        {
            { "PULUMI_CONFIG_PASSPHRASE", "secret" },
			{ "PULUMI_BACKEND_URL": "file://~" }
        }
```

**Comment by damianh** [comment]
@komalali Thanks for the rapid response. I can confirm your suggestions work, cheers.
