### ISSUE TITLE
Interactive configuration setting does not accept large values

### ISSUE THREAD

**Issue by Slaiyer** [pulumi/pulumi#6702]
Setting configuration values larger than 1024 characters does not work in the interactive mode.

This limitation becomes especially troublesome when a secret needs to be introduced into the stack, as one of the following must be now used as a workaround:
1. `pulumi config set --secret $KEY "$LONG_SECRET_FROM_CLI"`
2. `pulumi config set --secret $KEY "$(</tmp/long-secret-from-file)"`

Both require the input of secrets in plaintext, and are less than ideal as such.

## Expected behavior
1. `pulumi config set` value should not be limited to 1024 characters in the interactive mode.
2. `pulumi config set` should expose a flag `-f`/`--file` to read input from.

## Current behavior
1. Terminal bell when attempting to provide a value of length > 1024 characters in the interactive mode.
2. No `-f`/`--file` flag available for `pulumi config set`.

## Steps to reproduce
1. Invoke `pulumi config set $KEY`.
2. Enter string longer than 1024 characters at the `value: ` prompt.

## Context (Environment)
Trying to incorporate a secret which has a plaintext length larger than 1024 characters into a stack's configuration.

## Affected feature

`pulumi config set`

**Comment by t0yv0** [comment]
To expand on the workaround, it is not necessarily less secure, as one can use a password manager to extra the password, for example the `pass` manager:

```
pulumi version
# v2.23.1
pass generate temp_secret 4096
pulumi config set --secret sky $(pass temp_secret)
diff <(pulumi config get skey) <(pass temp_secret)
```

I believe similar can be achieved with `op` 1Password CLI.

I then also wonder how useful is the suggested `-f` option, is it intended to just read plain-text secrets or the intention is to have Pulumi support some form of decryption?

**Comment by leezen** [comment]
Also worth noting that `pulumi config set` can also read from `stdin`, e.g.:

`cat foo | pulumi config set publicKey`

Does this satisfy your use case to read from a file?

**Comment by Slaiyer** [comment]
> I then also wonder how useful is the suggested `-f` option, is it intended to just read plain-text secrets or the intention is to have Pulumi support some form of decryption?

Ah... that was just a suggestion to enable file reads if we were going to have to do that anyway.
@leezen i completely missed the stdin option! That essentially takes care of the issue.

However, I still find the interactive value setting's limit of 1024 characters an unexpected limitation - any specific reason for that?
Please feel free to close this issue in light of these workarounds.

**Comment by leezen** [comment]
There's no particular reason beyond that's the default when allocating a buffer for reading stdin in the library. I'll close this issue as 1024 seems 'reasonable' enough for interactive use and other use cases can pipe.
