### ISSUE TITLE
Project-wide variables (not stack specific)

### ISSUE THREAD

**Issue by ppawiggers** [pulumi/pulumi#6719]
In the YAML configuration file for a stack you can define variables:

```yaml
config:
  foo:bar: myvar
```

This works fine, however I have some project wide variables that are independent of the activated stack (I use the same Pulumi code for multiple projects, and a stack per environment). Adding the `config` as above to `Pulumi.yaml` does not work:

```bash
error: could not get cloud url: could not load current project: yaml: unmarshal errors:
  line 5: cannot unmarshal !!map into string
```

Of course I can load it manually in the code like:

```python
with open("project-vars.yaml") as f:
  data = yaml.load(f.read())
```

But imho it's better to do it like with stacks.

**Comment by lukehoban** [comment]
This is effectively the feature tracked in https://github.com/pulumi/pulumi/issues/2307.

**Comment by ppawiggers** [comment]
Thanks @lukehoban , that seems to be it. I have to work in my issue search skills.
