### ISSUE TITLE
Ability to get logged messages count in Python

### ISSUE THREAD

**Issue by mgzenitech** [pulumi/pulumi#6722]
Maybe it's already possible but I was unable to find anything in the docs. Basically I need to know if there were any logged errors:

```python
from pulumi import log

log.error("whatever")

print(f"{log.???} logged messages")
```

or atleast some sort of function that returns if there were any errors logged like `log.has_errors()`

**Comment by mgzenitech** [comment]
also I'd like to know some way for sort of soft stop in pullumi if there are any errors logged. Maybe there's such a thing already implemented via exported function or something like that?

META:
```
if there are any errors logged:
    soft stop pulumi without any exception (basically stop pulumi from asking for changes apply)
```

**Comment by EvanBoyle** [comment]
This isn't a supported feature. I would suggest wrapping the pulumi logger with your own utility to add this functionality.

**Comment by mgzenitech** [comment]
NodeJS counterpart has **hasErrors** method:
[https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/log/#hasErrors](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/log/#hasErrors)

Isn't this same thing as I have requested in Python?

**Comment by leezen** [comment]
@mgzenitech You're correct that this is exposed in the NodeJS runtime. Arguably, this function should be marked `internal` as it's used by other parts of the runtime to determine how to surface error messages vs. something we want to support in general as part of a logging library.
