### ISSUE TITLE
Multiple `testproj` module names detected

### ISSUE THREAD

**Issue by Volatus** [pulumi/pulumi#6775]
VS Code with the Go extension reports issues regarding `testproj` module being found more than once.
## Expected behavior

There should be no errors.
## Current behavior

The Gopls language server has some issues with the go modules within the Pulumi repository. Supposedly it's due to a module being found twice within the workspace.
## Steps to reproduce

1. Fork & Clone Pulumi
2. Make sure you have Go extension installed in VS Code
3. Make sure all dependencies are present and run `make ensure` (For me it's present even before the make command)

![image](https://user-images.githubusercontent.com/46189206/114785647-a8045700-9d85-11eb-9c6f-9d6c8e7b758d.png)

## Context (Environment)

There have been no changes made to the code but this errors shows up with the repository from upstream.

**Comment by leezen** [comment]
@Selonophile These conflicts show up as multiple tests end up using the same module name, but this shouldn't affect anything in the actual build of the repo itself.

Not sure if others are bothered by this. Happy to take a PR to make these test project names unique.

**Comment by Selonophile** [comment]
@leezen Just opened the [PR](https://github.com/pulumi/pulumi/pull/6800) for this.
