### ISSUE TITLE
[docgen] Regression in args types

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#6797]
Regression introduced by #6686

When regenerating resource docs using the latest commit in `master`, I'm seeing diffs on args types. Previously, we were emitting unwrapped types (by design, as to not clutter the table of args), but now they're being emitted wrapped as `Input`.

<img width="873" alt="Screen Shot 2021-04-16 at 1 10 40 PM" src="https://user-images.githubusercontent.com/710598/115094491-9e3c3a00-9ed2-11eb-92c7-ceb89f62f46f.png">

**Comment by viveklak** [comment]
This also affects doc gen for the google-native provider.
