### ISSUE TITLE
Need way to detect if update would change any resources

### ISSUE THREAD

**Issue by chrsmith** [pulumi/pulumi#681]
Perhaps this is a specific instance of https://github.com/pulumi/pulumi/issues/496, but as part of "canary" jobs we need to test that a `pulumi update` does not modify any existing resources. (e.g. updating the PPC doesn't rename/delete any Dyanmo tables or S3 buckets.

Unfortunately I don't know if we can use preview, since we can only get an accurate picture of resource changes by doing the actual update. Right?

**Comment by joeduffy** [comment]
@chrsmith we now have the `--expect-no-changes` flag for `pulumi preview` and `pulumi up`. I think that suffices for this issue, unless I'm misunderstanding. Please reopen with more details If I am.
