### ISSUE TITLE
Is Pulumi 3.0 ready yet?

### ISSUE THREAD

**Issue by austinbutler** [pulumi/pulumi#6814]
Looking at the available data it's a bit conflicting.

1. `pulumi version` recommends `2.25.2`
2. "[Upgrading to Pulumi 3.0](https://www.pulumi.com/docs/get-started/install/migrating-3.0/)" doc says "Pulumi 3.0 is currently in rc"
3. "[Available Versions](https://www.pulumi.com/docs/get-started/install/versions/)" doc says "The current stable version of Pulumi is 2.25.2"
4. This repo's latest release is `v3.0.0`
5. `yarn outdated` shows `3.0.0` for `@pulumi/pulumi`

**Comment by infin8x** [comment]
[Pulumi 3.0 is out!](https://www.pulumi.com/blog/pulumi-3-0/). Hope to see you at [PulumiUP in an hour](https://www.pulumi.com/pulumi-up/), where we'll be sharing all the news!
