### ISSUE TITLE
[cli] Panic printing detailed diffs in a specific scenario

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi#6816]
I got the following panic when I tried to run a `preview` with a `--diff` and also when I chose **Details** from the confirmation prompt in an `up`.

```
goroutine 50 [running]:
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.failfast(...)
	/workspace/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v2/go/common/util/contract.Assert(...)
	/workspace/sdk/go/common/util/contract/assert.go:26
github.com/pulumi/pulumi/pkg/v2/engine.printPropertyValue
	/workspace/pkg/engine/diff.go:511 +0x1485
github.com/pulumi/pulumi/pkg/v2/engine.PrintObject
	/workspace/pkg/engine/diff.go:230 +0x248
github.com/pulumi/pulumi/pkg/v2/engine.printPropertyValue
	/workspace/pkg/engine/diff.go:517 +0x135d
github.com/pulumi/pulumi/pkg/v2/engine.PrintObject
	/workspace/pkg/engine/diff.go:230 +0x248
github.com/pulumi/pulumi/pkg/v2/engine.GetResourcePropertiesDetails
	/workspace/pkg/engine/diff.go:190 +0x3d3
github.com/pulumi/pulumi/pkg/v2/backend/display.renderDiff
	/workspace/pkg/backend/display/diff.go:330 +0x575
github.com/pulumi/pulumi/pkg/v2/backend/display.renderDiffResourcePreEvent
	/workspace/pkg/backend/display/diff.go:351 +0x298
github.com/pulumi/pulumi/pkg/v2/backend/display.RenderDiffEvent
	/workspace/pkg/backend/display/diff.go:122 +0x718
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowDiffEvents
	/workspace/pkg/backend/display/diff.go:85 +0x499
github.com/pulumi/pulumi/pkg/v2/backend/display.ShowEvents
	/workspace/pkg/backend/display/display.go:53 +0x178
created by github.com/pulumi/pulumi/pkg/v2/backend/filestate.(*localBackend).apply
	/workspace/pkg/backend/filestate/backend.go:566 +0x308
```

## Expected behavior
CLI doesn't panic whilst printing a detailed diff.

## Current behavior
CLI panics when it encounters a property that is not an object and therefore, fails the [assertion](https://github.com/pulumi/pulumi/blob/master/pkg/engine/diff.go#L511).

## Steps to reproduce

Although I was able to reproduce this consistently in an existing stack, unfortunately, I have not been able to reproduce this in a fresh stack mostly because my existing stack is quite large and it was difficult to hone in on a specific piece of code triggering the panic.

However, I found that my existing stack was being tripped up by a property that was a resource reference and not a simple object value (i.e. `PropertyMap`) I also found that the same resource was referenced as an input in a lot of places and any of those places could have triggered the panic. I have a [branch](https://github.com/pulumi/pulumi/compare/praneetloke/resource-reference-panic?expand=1) that adds a new check to `printPropertyValue` that evaluates if a property to be printed is a resource reference. With that I was able to see the detailed diff without issues (I had a log line in `printPropertyValue` that confirmed the type of the property in my local.) Sadly, even with this finding I was unable to reproduce this behavior in a new stack.

## Context (Environment)

* S3 backend
* Latest CLI
* pulumi Python SDK 2.21.1
* pulumi-kubernetes 2.8.1

**Note**: As mentioned in the previous section, I have not been able to reproduce this in a fresh stack with the above versions. I am suspecting that the problem lies in how the `diff` operation works as it prints out properties of a resource.

## Affected feature

Using the `--diff` flag or choosing the **Details** option from the confirmation prompt during an `up`.

**Comment by lukehoban** [comment]
It appears this is the same issue as #6934, and was fixed with https://github.com/pulumi/pulumi/pull/6962.
