### ISSUE TITLE
[sdk/python] - AssertionError: Unexpected type. Expected 'dict' got '<class 'str'>' for Policy

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi#6818]
Before 3.0.0 I could pass in a dict as an `aws.BucketPolicy.policy`. Now the same code fails with: `AssertionError: Unexpected type. Expected 'dict' got '<class 'str'>'`

## Expected behavior

The code should succeed as it did before

## Current behavior

It fails with an assertion error

## Steps to reproduce

The following code reproduces the issue if you try to run `pulumi up`

```python
import pulumi
from pulumi_aws import s3

bucket = s3.Bucket("my-bucket")

policy = s3.BucketPolicy("my-policy", bucket=bucket.id, policy={
    "Version": "2012-10-17",
    "Statement": {
        "Effect": "Allow",
        "Principal": "*",
        "Action": ["s3:GetObject"],
        # Policy refers to bucket explicitly
        "Resource": [pulumi.Output.concat("arn:aws:s3:::", bucket.id, "/*")]
    }
})
```

**Comment by komalali** [comment]
The reason this fails is because `policy` is technically typed as `str`. We previously did some "magic" behind the scenes to transform the dict to a json string, but we have since tightened up the type checker. 

However, you can still pass in the policy as a string as below:

```python
import pulumi
from pulumi_aws import s3

bucket = s3.Bucket("my-bucket")

policy = s3.BucketPolicy("bucket-policy", bucket=bucket.id, policy=bucket.id.apply(lambda id: json.dumps({
        "Version": "2012-10-17",
        "Statement": {
            "Effect": "Allow",
            "Principal": "*",
            "Action": ["s3:GetObject"],
            # Policy refers to bucket explicitly
            "Resource": [f"arn:aws:s3:::{id}/*"]
        },
    })))
```

**Comment by cbcmg** [comment]
Another example of getting this exception: 

```
k8s.Provider('k8s-provider', kubeconfig=cluster.kubeconfig)
```

will throw the exception listed above.

```
k8s.Provider('k8s-provider', kubeconfig=cluster.kubeconfig.apply(lambda i: str(i)))
```

will succeed. There is no indication anywhere in the pulumi console output of the root cause of the exception.

**Comment by justinvp** [comment]
@cbcmg, what is the type of `cluster` and its `kubeconfig`?

**Comment by t0yv0** [comment]
I can repro the S3 example. With some debug stmts:

```
    error: Traceback (most recent call last):
      File "/Users/anton/.nix-profile/bin/pulumi-language-python-exec", line 85, in <module>
        loop.run_until_complete(coro)
      File "/nix/store/cp9nlaz4a24n8sp9f738ngdnrd19s4rp-python3-3.8.5/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
        return future.result()
      File "/Users/anton/pulumi/sdk/python/lib/pulumi/runtime/stack.py", line 110, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/Users/anton/pulumi/sdk/python/lib/pulumi/runtime/stack.py", line 45, in run_pulumi_func
        await wait_for_rpcs()
      File "/Users/anton/pulumi/sdk/python/lib/pulumi/runtime/stack.py", line 94, in wait_for_rpcs
        raise exception
      File "/Users/anton/pulumi/sdk/python/lib/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/anton/pulumi/sdk/python/lib/pulumi/output.py", line 91, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/anton/pulumi/sdk/python/lib/pulumi/output.py", line 91, in is_value_known
        return await is_known and not contains_unknowns(await future)
      File "/Users/anton/pulumi/sdk/python/lib/pulumi/output.py", line 91, in is_value_known
        return await is_known and not contains_unknowns(await future)
      [Previous line repeated 1 more time]
      File "/Users/anton/pulumi/sdk/python/lib/pulumi/runtime/resource.py", line 438, in do_register
        resolver = await prepare_resource(res, ty, custom, remote, props, opts, typ)
      File "/Users/anton/pulumi/sdk/python/lib/pulumi/runtime/resource.py", line 100, in prepare_resource
        serialized_props = await rpc.serialize_properties(props, property_dependencies_resources, translate, typ)
      File "/Users/anton/pulumi/sdk/python/lib/pulumi/runtime/rpc.py", line 121, in serialize_properties
        result = await serialize_property(v, deps, input_transformer, get_type(k))
      File "/Users/anton/pulumi/sdk/python/lib/pulumi/runtime/rpc.py", line 307, in serialize_property
        raise AssertionError(f"Unexpected type. Expected 'dict' got '{typ}'\n" + m)
    AssertionError: Unexpected type. Expected 'dict' got '<class 'str'>'
    serialize_property(value={'Version': '2012-10-17', 'Statement': {'Effect': 'Allow', 'Principal': '*', 'Action': ['s3:GetObject'], 'Resource': [<pulumi.output.Output object at 0x10f188ca0>]}}, deps=[], input_transformer=None, typ=<class 'str'>
     type(value) = <class 'dict'>
```

**Comment by t0yv0** [comment]
Mini repro:

```
import pulumi.runtime.rpc as rpc
import pulumi_aws.s3.bucket_policy as bucket_policy


async def main():
    await rpc.serialize_properties(
        inputs={
            'bucket': None,
            'policy': {
                'Version': '2012-10-17',
                'Statement': {
                    'Effect': 'Allow',
                    'Principal': '*',
                    'Action': ['s3:GetObject'],
                    'Resource': []
                }
            }
        },
        property_deps={'bucket': []},
        input_transformer=None,
        typ=bucket_policy.BucketPolicyArgs)

import asyncio
asyncio.run(main())
```

**Comment by lukehoban** [comment]
> @cbcmg, what is the type of cluster and its kubeconfig?

@justinvp I assume this is an `eks.Cluster`s `kubeconfig` output, which is an `Output[Any]` and returns an Kubeconfig object instead of a string.  This is also likely related to https://github.com/pulumi/pulumi-kubernetes/issues/1032.  I'm unclear on what changed specifically in 3.0 for Python here - but I think the underlying issue is that the Kubernetes `Provider` should accept either an object or a string - as suggested in that issue.

**Comment by justinvp** [comment]
> I'm unclear on what changed specifically in 3.0 for Python here

The thing that changed in 3.0 was that we now raise an error when an input value is a dict, but the type annotation doesn't match. Since we have some cases that historically have worked when passing a dict value despite the type annotation not saying it accepts a dict, I'm going to stop raising the error. I have a fix that I'm preparing now.

**Comment by t0yv0** [comment]
Sounds like you're taking this to a fix Justin based on historical usage preference so that sounds good, I'm just curious for the future.

**Comment by justinvp** [comment]
@t0yv0, we do need to fix the type annotations -- that's the "right" long-term fix. Specifically for `BucketPolicy` this is tracked by https://github.com/pulumi/pulumi-terraform-bridge/issues/339. And it looks like there's a similar issue tracking updating the type annotation for `kubeconfig` with https://github.com/pulumi/pulumi-kubernetes/issues/1032.

But since there are probably more cases like this (where they type annotation doesn't match the reality of acceptable values), I think it's best to also remove the assertion that was introduced in 3.0, so at least we go back to the behavior we had previously (not raising an error in the SDK and passing the value through to the resource provider).
