### ISSUE TITLE
Deno support for Pulumi

### ISSUE THREAD

**Issue by headconnect** [pulumi/pulumi#6820]
It would be great to be able to use Deno as an alternative to Node for typsecript execution.  

Essentially - recreating #3838 as I -DO- use pulumi and would love to be able to take advantage of certain benefits of deno, particularly when running automation.

**Comment by leezen** [comment]
@headconnect Thanks for bringing this back up. We like to track issues from the beginning, so I'll go ahead and re-open #3838.

**Comment by infin8x** [comment]
Duplicate of #3838
