### ISSUE TITLE
Move runCommandThatMustSucceed helper into main package

### ISSUE THREAD

**Issue by JakeGinnivan** [pulumi/pulumi#6839]
Often we need to trigger a build or some other command during our `up` process, ensuring the command output can be logged and errors are surfaced properly would be handy. Otherwise some guidance around running a cli command during your preview or up step would be handy.

There is some built in functionality in the docker library, specifically at https://github.com/pulumi/pulumi-docker/blob/c69d6acb9af5dc76454c22e4a62607e427ede62b/sdk/nodejs/docker.ts#L575

I am using the node SDK

## Affected feature

Docker builds

**Comment by komalali** [comment]
@JakeGinnivan what is `runCommandThatMustSucceed`? Where in the code are you referring to? What language are you using?

It's possible you might want to use [Automation API](https://github.com/pulumi/automation-api-examples) if you want to run other code with your Pulumi code.

**Comment by JakeGinnivan** [comment]
Hey @komalali, I have updated my original issue with more info. I certainly missed the useful information out of the issue 😂

**Comment by lukehoban** [comment]
I think what we really want to do here is ultimately create a multi-language Pulumi package to support running and managing lifetime of local operating system processes. This is ultimately related to (or possibly the same as) https://github.com/pulumi/pulumi/issues/99. 

I'm not sure the specific code in runCommandThatMustSucceed is the right thing to expose directly - it is rather built-for-purpose for the needs of that specific library. But the goal of running processes inside Pulumi programs in a standard way definitely make sense.

**Comment by JakeGinnivan** [comment]
Have closed as I agree #99 is the way to go, for the moment I have just copied the runCommandThatMustSucceed function into my projects which does the job for now.
