### ISSUE TITLE
GCP k8s Cluster with enable_autopilot refuses to be created because of conflict with enable_binary_authorization

### ISSUE THREAD

**Issue by Zubnix** [pulumi/pulumi#6842]
Simply create a k8s cluster with autopilot enabled.

## Expected behavior
It should just work.

## Current behavior
Gives error:
ConflictsWith: "enable_binary_authorization": conflicts with enable_autopilot. Examine values at 'Cluster.EnableBinaryAuthorization'.

Explicitly enabling or disabling the 'EnableBinaryAuthorization' option does not fix it.

## Steps to reproduce
Create a stack with a single GKE cluster resource

**Comment by Zubnix** [comment]
related: https://github.com/pulumi/pulumi-gcp/issues/560

**Comment by komalali** [comment]
Closing as duplicate of https://github.com/pulumi/pulumi-gcp/issues/560
