### ISSUE TITLE
Consider making Output[T] covariant in python mypy

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#6843]
Original user issue reported as follows:

```
# mypy .
helper_k8s.py:193: error: Argument "string_data" to "Secret" has incompatible type "Output[Mapping[str, str]]"; expected "Union[Mapping[str, Union[str, Awaitable[str], Output[str]]], Awaitable[Mapping[str, Union[str, Awaitable[str], Output[str]]]], Output[Mapping[str, Union[str, Awaitable[str], Output[str]]]], None]"
Found 1 error in 1 file (checked 7 source files)                                                                                                                                                              
~4m-23.0s
```

The user expects `Output[Mapping[str, str]]` to be a subtype of `Output[S]` since `Mapping[str, str]` is a subtype of `S`, with `S = Mapping[str, Union[str, Awaitable[str], Output[str]]]`. That is to say, the user expects the `Output` to be covariant. The workaround is to apply an identity lambda, so `x.apply(lambda v: v)` instead of `x`. Playground listing below:

```python
from pulumi import Output
from typing import Mapping, Union, Awaitable, Generic, TypeVar


S = Mapping[str, Union[str, Awaitable[str], Output[str]]]


def f1(x: Mapping[str, str]) -> S:
    return x


# def f2(x: Output[Mapping[str, str]]) -> Output[S]:
#     return x
#
# error: Incompatible return value type (got "Output[Mapping[str, str]]", expected "Output[Mapping[str, Union[str, Awaitable[str], Output[str]]]]")
# note: Perhaps you need a type annotation for "x"? Suggestion: "Output[Mapping[str, Union[str, Awaitable[str], Output[str]]]]"


def f3(x: Output[Mapping[str, str]]) -> Output[S]:
    return x.apply(lambda v: v)


T1 = TypeVar('T1')
T2 = TypeVar('T2', contravariant=True)
T3 = TypeVar('T3', covariant=True)


class InvariantBox(Generic[T1]):
    pass


class ContravariantBox(Generic[T2]):
    pass


class CovariantBox(Generic[T3]):
    pass


# def f4(x: InvariantBox[Mapping[str, str]]) -> InvariantBox[S]:
#     return x
#
# error --^


# def f5(x: ContravariantBox[Mapping[str, str]]) -> ContravariantBox[S]:
#     return x
#
# error --^


def f6(x: CovariantBox[Mapping[str, str]]) -> CovariantBox[S]:
    return x
``` 

## Affected feature

Usability of k8s libs.

## Discussion

There might be far-reaching implications of marking Output as a covariant, so it might not be feasible, or else not a good idea.

## References

- https://github.com/pulumi/pulumi/issues/3767
- https://github.com/pulumi/pulumi/pull/3758#discussion_r367579715

**Comment by Slaiyer** [comment]
Just curious, why does the identity lambda satisfy the type checker?

**Comment by t0yv0** [comment]
It would seem that to typecheck the following term:

```
x.apply(lambda v: v)
```

It may be inferring the type `Mapping[str,str] -> S` for the lambda, which it can do since it believes `Mapping[str,str]` to be a subtype of `S` already. In this case the `x.apply(f)` term may be judged to be `Output[S]` without needing the covariance. I think one of the special cases of `apply` type is:

```
Output[T] -> (T -> T2) -> Output[T2]
```

Which does not use sub typing constraints.

Above I'm using the notation `A -> B` for `Callable[[A], B]`.

**Comment by orionstudt** [comment]
If it is decided that it is OK to make this change, I'd like to see the same in the dotnet SDK. And also, if this is OK, is there any reason to not also do `Input<T>`?
