### ISSUE TITLE
Why is the word "dirty" appended in the version of Pulumi? (2.25.2+dirty)

### ISSUE THREAD

**Issue by doitadrian** [pulumi/pulumi#6847]
For some reason, installing my project's NPM packages works, but when I look into `node_modules/@pulumi/pulumi/package.json`, I can see the following version set in the`version` property: `2.25.2+dirty`.

![image](https://user-images.githubusercontent.com/5121148/115744272-b6103400-a392-11eb-8010-8bf9a3589c72.png)

## Expected behavior
Shouldn't this be just `2.25.2`?

## Current behavior
The version has the word `dirty` appended, so `2.25.2+dirty`.

## Steps to reproduce

1. Installed my project's packages using `yarn`.
2. Tried to deploy cloud infra, but when looking at the package version, I can see the `dirty` word appended to the package version.

## Context (Environment)
This is really a question... can anybody explain why would this `+dirty` word be appended to the package version? And how is this controlled? Or is this a Pulumi thing at all? And if so, should I be concerned?

## Affected feature
N/A

---
Sorry if I missed any information, please let me know if so.

**Comment by stack72** [comment]
Hi @doitadrian 

My apologies for this - when we build our binaries and packages, (in our current build), we have been calculating the version at *EVERY* stage of the build. This means that changes in the filesystem during our build (e.g. binary creation, or go tools installed) could potentially be picked up as a local filesystem modification and thus be marked as "+dirty". This is an internal version check only via https://github.com/pulumi/pulumictl/blob/master/pkg/gitversion/gitversion.go#L307 - we are going to change how the build happens to ensure this will not happen again.

I hope this answers your question and I hope it helps alleviate the strange behaviour here.

If you think it would help, I can always create a new 2.25.x release to make sure that our users are happy

Paul

**Comment by doitadrian** [comment]
Thanks for the fast response @stack72 :)

Well, at this point, the only thing I wanted to ensure was that this detail doesn't represent some kind of a broken state of Pulumi CLI or a bug. I mean, it looks like everything still works fine, but just wanted to double-check.

So, as far as I'm concerned, releasing a regular `2.25.x` is not a must, but still, if you want to have piece of mind, than be my guest ;)

Thanks again for the assistance @stack72, feel free to close this issue if you think that's appropriate.

**Comment by stack72** [comment]
yeah everything works absolutely fine! I will talk to the team and see if we want to cut a new release to make sure that everyone is happy :)

Paul
