### ISSUE TITLE
Config yaml file is reformatted during preview using the AKV secrets provider

### ISSUE THREAD

**Issue by WillooWisp** [pulumi/pulumi#6848]
I experience this issue with Pulumi 3.0 and Azure Key Vault as secrets provider. Whenever I make a preview the yaml file is reformatted by Pulumi.

**Comment by komalali** [comment]
@lblackstone is this expected after the roundtripping yaml work?

**Comment by lblackstone** [comment]
The changes that will fix this were reverted and are still [in progress](https://github.com/pulumi/pulumi/pull/6489). I'm going to close this as a duplicate of #423
