### ISSUE TITLE
Inputs not available as implicit Outputs on subclassed resources in Pulumi 3.0

### ISSUE THREAD

**Issue by christophermaier** [pulumi/pulumi#6850]
Subclassed Resources appear to behave differently between Pulumi 2.x and 3.x. In particular, input properties on subclassed resources are not available as implicit output properties.

## Expected behavior
Input properties should be accessible as output properties on subclassed resources, as they are on the native Pulumi resources.

## Current behavior
Input values do not resolve to a usable value, causing failures in the creation of resources that depend on them. They do not show up as stack outputs, either.

## Steps to reproduce
I've created a reproduction at https://github.com/christophermaier/pulumi-3.0-subclass-bug, with further background information.

## Context (Environment)
I have several subclassed resources in my Pulumi code for restriction/specialization purposes (e.g., ensure all DynamoDB tables generated from a subclass have the same billing mode, etc.). While I could model this as a simple function call (as opposed to object creation), it is also useful to attach helper methods to the subclassed objects to make it easier to perform additional operations, like granting permissions to the resource from other resources (as with AWS Role Policies, for instance).

Such code worked without issue with Pulumi 2.x, but fails with 3.x, preventing us from upgrading (at least without rewriting our infrastructure code)

**Comment by justinvp** [comment]
Another example:

```python
class NetworkLoadBalancer(aws.lb.LoadBalancer):
    network_interface: Output[aws.ec2.AwaitableGetNetworkInterfaceResult]
    # TODO: Network ACL.
    def __init__(self, name: str, public_subnet_id: Input[str], opts: ResourceOptions = None):
        super(NetworkLoadBalancer, self).__init__(
            name,
            opts=opts,
            internal=False,
            load_balancer_type='network',
            subnets=[public_subnet_id]
        )
        self.network_interface = self.id.apply(lambda id: get_elb_network_interface(id, opts))
        self.record_alias = aws.route53.RecordAliasArgs(
            evaluate_target_health=False,
            name=self.dns_name,
            zone_id=self.zone_id
        )
```

Results in:

```
    error: aws:route53/record:Record resource 'PlatformBackendAlias' has a problem: Missing required argument: The argument "alias.0.name" is required, but no definition was found.. Examine values at 'Record.Aliases'.
```

Same problem with `zone_id`.

**Comment by justinvp** [comment]
I still need to confirm, but I believe this is a regression introduced by https://github.com/pulumi/pulumi/pull/6695. We now use the class's type and name metadata to do camelCase <=> snake_case translations, but we only look at metadata associated with the class itself and not from any base classes. We need to fix this for resources to look for base class metadata as well.
