### ISSUE TITLE
Why does code generated from “pulumi import” lack a lot of details?

### ISSUE THREAD

**Issue by lyenliang** [pulumi/pulumi#6856]
I want to use pulumi to import one of my existing resources on AWS.

So I ran `pulumi import aws:elasticache/cluster:Cluster my-redis my-redis` command and got the following details in the output:

```
= aws:elasticache/cluster:Cluster: (import) 🔒
    [id=my-redis]
    [urn=urn:pulumi:prod::my_aws_infra::aws:elasticache/cluster:Cluster::my-redis]
    [provider=urn:pulumi:prod::my_aws_infra::pulumi:providers:aws::default_4_0_0::5bcb13d1-6ocf-qb30-bf12-6c7a1683a072]
    availabilityZone      : "ap-northeast-1c"
    azMode                : "single-az"
    clusterId             : "my-redis"
    engine                : "redis"
    engineVersion         : "4.0.10"
    maintenanceWindow     : "sat:20:00-sat:21:00"
    nodeType              : "cache.t3.small"
    notificationTopicArn  : "arn:aws:sns:ap-northeast-1:123456789123:redis_sns_topic"
    numCacheNodes         : 1
    parameterGroupName    : "default.redis4.0"
    port                  : 6379
    securityGroupIds      : [
        [0]: "sg-b6d1b86al301zd054"
        [1]: "sg-5yfa3a33"
    ]
    snapshotRetentionLimit: 0
    snapshotWindow        : "16:30-17:30"
    subnetGroupName       : "default"
    tags                  : {
    }
```

The code I get from `pulumi import ...` becomes

```
my_redis = aws.elasticache.Cluster("my-redis",
    cluster_id="my-redis",
    notification_topic_arn="arn:aws:sns:ap-northeast-1:123456789123:redis_sns_topic",
    opts=pulumi.ResourceOptions(protect=True))
``` 

Why does the generated code lack a lot of information (`availabilityZone`, `azMode`, `engine`, etc)?

The code works correctly when I run `pulumi up`.

How does pulumi know all the configurations of the redis resource?

Are the configurations stored in the backend of pulumi?

Because the code works correctly, I'm not sure if this is really a bug.

## Expected behavior
I expect that the code should contain other attributes of the redis service.
```
my_redis = aws.elasticache.Cluster("my-redis",
    availability_zone="ap-northeast-1a",
    az_mode="single-az",
    engine="redis",
    engine_version="4.0.10",
    maintenance_window="sat:21:00-sat:22:00",
    ...
    cluster_id="my-redis",
    notification_topic_arn="arn:aws:sns:ap-northeast-1:123456789123:redis_sns_topic",
    opts=pulumi.ResourceOptions(protect=True))
```

## Current behavior

The real code I got is 

```
my_redis = aws.elasticache.Cluster("my-redis",
    cluster_id="my-redis",
    notification_topic_arn="arn:aws:sns:ap-northeast-1:123456789123:redis_sns_topic",
    opts=pulumi.ResourceOptions(protect=True))
``` 

## Steps to reproduce

1. Create an ElastiCache redis on an AWS account.
2. Run `pulumi new aws-python`  to setup a basic aws python template.
3. Run `pulumi import aws:elasticache/cluster:Cluster my-redis my-redis` to import the redis resource into pulumi.

## Context (Environment)

I want to import my ElastiCache redis resource on AWS into pulumi.
The version of my pulumi is `v3.0.0`.
My python version is `3.8.2`.

**Comment by komalali** [comment]
Hi @lyenliang,

This is the expected behavior. For the purposes of importing the resource to be managed by Pulumi, the necessary inputs are specified in the code generated. You are of course welcome to include the additional details in your code, but Pulumi has generated what is necessary to import the resource.

To see all of the inputs/outputs of your resources, you can take a look at your state file (`pulumi stack export`).

**Comment by lyenliang** [comment]
Hi, @komalali

Thanks for you reply. 

Is there any option I can enable so that pulumi can generate a code with all the details?

I want this feature because I will create a new redis in another AWS region.

I will use `pulumi stack select <new_stack>` to switch to a new stack, modify some of the details of the redis service, and then run `pulumi up` to create a new redis another AWS region.

**Comment by komalali** [comment]
@lyenliang unfortunately there's no way to currently generate all of the inputs during import. Instead, you could get the inputs from the stack state `pulumi stack export > stack.json` and then update your code to mirror the state which you could then use to create other stacks.

**Comment by lyenliang** [comment]
I got it. Thank you @komalali.
