### ISSUE TITLE
Bump Grpc NuGet packages to 2.37.0

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi#6870]
There are more important fixes for dotnet/c# in [v1.37.0](https://github.com/grpc/grpc/releases/tag/v1.37.0) (NuGet [2.37.0](https://www.nuget.org/packages/Grpc.Core/2.37.0)) (since [v1.34.0](https://github.com/grpc/grpc/releases/tag/v1.34.0)):
> C#
> * [C#] Add buildTransitive directory to NuGet package. (#25385)
> * Reduce Grpc.Core nuget size by generating separate .so with/without debug symbols for grpc_csharp_ext. (#25729)
> * make Grpc C# work on aarch64 linux. (#25717)
> * Add support for additional protoc arguments in Grpc.Tools. (#25374)
> * C#: Use explicit native extension loading whenever possible. (#25490)

> * [Backport] [C#] Use explicit native extension loading whenever possible. (#25506)

> * fix nuget package signing on Linux (do not use PublicSign=true on non-windows). (#24980)
> * Remove C# as a supported language for xDS features. (#24982)
> * Fix C# native library loading in .NET 5 single-file apps. (#24744)

**Comment by gitfool** [comment]
@mikhailshilkov similar to #5861.

**Comment by mikhailshilkov** [comment]
Sounds good. Are you opening a PR?
