### ISSUE TITLE
Automation API: No example for a custom Workspace in TypeScript.

### ISSUE THREAD

**Issue by brandonbloom** [pulumi/pulumi#6874]
There is no example for implementing a custom Workspace in TypeScript.

**I'm not sure if it's is actually possible to implement a useful custom Workspace...**

The docs suggest that this should be possible. From [https://www.pulumi.com/docs/guides/automation-api/concepts-terminology/](https://www.pulumi.com/docs/guides/automation-api/concepts-terminology/):

> Custom Workspace implementations can be used to store Project and Stack settings as well as Config in a different format, such as an in-memory data structure, a shared persistent SQL database, or cloud object storage. Regardless of the backing Workspace implementation, the Pulumi SaaS Console will still be able to display configuration applied to updates as it does with the local version of the Workspace today.

The guide at https://www.pulumi.com/docs/guides/automation-api/ should have an example of a custom workspace.

I've attempted to implement a custom workspace without any examples and I'm not entirely sure that it is actually possible due to the way the `LocalWorkspace` and `Stack` classes are currently implemented.

**Comment by brandonbloom** [comment]
Here's my attempt to create a dynamic workspace:
https://gist.github.com/brandonbloom/a60f179d69073fb76b53f183697ea08a

This works for `refresh` and `destroy`, but `up` has all sorts of problems with unhandled rejections, etc.

**Comment by orionstudt** [comment]
I opened an issue about this [in the documentation repo.](https://github.com/pulumi/docs/issues/5875)

**Comment by komalali** [comment]
@brandonbloom @orionstudt As discussed elsewhere, we don't expect custom implementations for Workspace to be created externally without deep knowledge of Pulumi internals. I'll follow up by clarifying the documentation.
