### ISSUE TITLE
Certain resources not running through registerStackTransformation

### ISSUE THREAD

**Issue by sharpn** [pulumi/pulumi#6878]
When trying to migrate from terraform to pulumi using a custom `registerStackTransformation` some providers do not seem to run the new code to append the import.

Using 
```ts
  pulumi.runtime.registerStackTransformation(({ type, name, props, opts }) => {
    return {
      props,
      opts: pulumi.mergeOptions(opts, {
        import: lookupId(type, name),
      }),
    };
  });
```
as per the example

At the moment i have found the following:
- @pulumi/kubernetes
- @pulumi/random

I figured as this is over multiple packages it was worth specifying it here.

## Expected behavior
All resources should be run against the transformer

## Current behavior
A selection of resources do not run against the transformer

## Steps to reproduce
1. Create a random string resource
2. Create a new `import.ts` as explained in the docs
3. Try and import a random string resource from terraform

## Context (Environment)
Trying to convert my terraform infrastructure as code to pulumi, currently block import of 90% of our resources as they are inside a kubernetes cluster

**Comment by EvanBoyle** [comment]
@sharpn can you provide a full code sample and some more specific steps (ie exact resources imported in a particular order)? I am having a hard time understanding the current/expected behavior described:

> A selection of resources do not run against the transformer
