### ISSUE TITLE
Implement error functions to access error message struct values

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#6900]
The errors returned from many automation API actions have some struct values which might be useful:

https://github.com/pulumi/pulumi/blob/master/sdk/go/auto/errors.go#L24-L29

This can be seen when you return the error on some operations:

```
error getting stack: code: 255
, stdout:
, stderr: error: no stack named 'mostly-relative-dodo' found

: failed to select stack: exit status 255%
```

It's difficult to handle these values, so it might be useful to implement these. It would be great if we could access these vaues directly so we can unwrap them ourselves

**Comment by mikhailshilkov** [comment]
I think this is covered by #6212 and #6137
