### ISSUE TITLE
Automation API `stack.preview()` causes TypeError

### ISSUE THREAD

**Issue by alexhwoods** [pulumi/pulumi#6911]
When I run `stack.preview()` in the automation API it causes a `TypeError: once is not a function`.
## Expected behavior

It shouldn't cause a type error.

## Current behavior

It does cause a type error.

## Steps to reproduce

1. I have a stack, called `sub-a`. It looks like this.
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as random from '@pulumi/random';

new random.RandomString('monkey', { length: 15 });
```
2. I then reference that in an automation stack.
```typescript
import * as pulumi from "@pulumi/pulumi"
import { LocalWorkspace } from "@pulumi/pulumi/automation"

async function main() {
  const stack = await LocalWorkspace.createOrSelectStack({
    stackName: 'dev',
    workDir: `${__dirname}/sub-a`
  })

  await stack.preview()
}

main()

```
3. I run `pulumi up --yes` from the top level stack, and that causes
```typescript
error: Running program '/Users/alexwoods/experiments/super-pulumi' failed with an unhandled exception:
    TypeError: once is not a function
```

Here's the repo I'm messing around in
https://github.com/alexhwoods/super-pulumi

## Context (Environment)

I'm just experimenting with the automation API.

**Comment by alexhwoods** [comment]
op, not done writing this, sorry bout that

**Comment by EvanBoyle** [comment]
Are you trying to run the Automation API program (super-pulumi) with the CLI? If so, this is not a supported way to use automation api. You should compile your typescript and execute the resulting JS via node. You should be able to add an npm script along the lines of `tsc && node index.js`. 

See this example for more details:

https://github.com/pulumi/automation-api-examples/blob/main/nodejs/inlineProgram-ts/package.json#L15

There are multiple examples of using automation api with compiled typescript, ts-node, and plain javascript: https://github.com/pulumi/automation-api-examples/tree/main/nodejs

**Comment by alexhwoods** [comment]
Hey @EvanBoyle and @tusharshahrs, thanks for being responsive!

I updated the `super-pulumi` repo, I'm doing `npm run execute`, which is doing `./node_modules/ts-node/dist/bin.js index.ts`, like in the examples

**Comment by alexhwoods** [comment]
(I do agree with you about warning `pulumi up` for automation API use cases though. That wasn't obvious when I first started these examples)

**Comment by alexhwoods** [comment]
I will try compiling and then running like you mentioned as well

**Comment by alexhwoods** [comment]
But just to be clear with the `npm run execute` (which just runs ts-node) does not work. And I believe it should, right?

**Comment by EvanBoyle** [comment]
@alexhwoods I cloned the repo and ran it and was not able to repro the error:

```
$ yarn install
$ yarn run exec
yarn run v1.22.10
warning package.json: No license field
$ ./node_modules/ts-node/dist/bin.js index.ts
✨  Done in 4.82s.
```

Can you provide more information about your environment? What version of node are you running, do you have a global tsc install, and what OS are you using?

**Comment by alexhwoods** [comment]
Interesting 🤔 

Yeah of course. I'm on a Mac. `v3.1.0` of the Pulumi CLI. The other details should be in the repo 🤔 .

Maybe some sort of caching issue or something. I did run `pulumi up` at some point, maybe something lingers?

I'll try freshly cloning it somewhere else and seeing what happens

**Comment by alexhwoods** [comment]
Same error when I clone and run from scratch (used Yarn this time)
```
$ git clone https://github.com/alexhwoods/super-pulumi.git
Cloning into 'super-pulumi'...
remote: Enumerating objects: 91, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 91 (delta 50), reused 87 (delta 46), pack-reused 0
Receiving objects: 100% (91/91), 27.82 KiB | 459.00 KiB/s, done.
Resolving deltas: 100% (50/50), done.
c162461  $ cd super-pulumi
super-pulumi : master ✔ : $ yarn
yarn install v1.22.10
warning package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning super-pulumi: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
warning The target of linked package "@pulumi/localfile" is missing. Removing link.
warning The target of linked package "kombucha-provider" is missing. Removing link.
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 11.85s.
super-pulumi : master ✘ :✭ $ yarn run exec
yarn run v1.22.10
warning package.json: No license field
error Command "exec" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
super-pulumi : master ✘ :✭ $ yarn run execute
yarn run v1.22.10
warning package.json: No license field
$ ./node_modules/ts-node/dist/bin.js index.ts
(node:60859) ExperimentalWarning: The fs.promises API is experimental
(node:60859) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time
TypeError: once is not a function
    at TailFile.quit (/Users/alexwoods/experiments/c162461/super-pulumi/node_modules/@logdna/tail-file/lib/tail-file.js:277:13)
    at /Users/alexwoods/experiments/c162461/super-pulumi/node_modules/@pulumi/pulumi/automation/stack.js:635:20
    at Generator.next (<anonymous>)
    at /Users/alexwoods/experiments/c162461/super-pulumi/node_modules/@pulumi/pulumi/automation/stack.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/alexwoods/experiments/c162461/super-pulumi/node_modules/@pulumi/pulumi/automation/stack.js:17:12)
    at cleanUp (/Users/alexwoods/experiments/c162461/super-pulumi/node_modules/@pulumi/pulumi/automation/stack.js:633:36)
    at Stack.<anonymous> (/Users/alexwoods/experiments/c162461/super-pulumi/node_modules/@pulumi/pulumi/automation/stack.js:328:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/alexwoods/experiments/c162461/super-pulumi/node_modules/@pulumi/pulumi/automation/stack.js:18:58)
✨  Done in 7.88s.
```

**Comment by alexhwoods** [comment]
Ah, i see you had more questions, one sec

**Comment by alexhwoods** [comment]
I will try running this in a container

**Comment by alexhwoods** [comment]
You are correct, it's my environment! (Thanks for helping me work through that.)

I did
```bash
docker run -it --entrypoint=/bin/bash debian -i
```

Then run the script
```bash
apt update && apt upgrade --yes
apt install curl git --yes

# Node
curl -sL https://deb.nodesource.com/setup_12.x | bash -
apt install nodejs --yes

# NPM
curl -O https://npmjs.org/install.sh | bash -

# Pulumi
curl -fsSL https://get.pulumi.com | sh
export PATH="/root/.pulumi/bin:$PATH"

# Set PULUMI_ACCESS_TOKEN
export PULUMI_ACCESS_TOKEN=<your-pulumi-access-token>
```

Then

```bash
git clone https://github.com/alexhwoods/super-pulumi.git
cd super-pulumi

# NPM Install in root, sub-a and sub-b
npm i && cd sub-a; npm i && cd ../sub-b; npm i && cd ..

npm run execute
```

Not sure what it is in my environment (I'll start with Node and TypeScript), but thank you for the help!

**Comment by alexhwoods** [comment]
(Think it was the Node version)

**Comment by infin8x** [comment]
Thanks for the follow-up @alexhwoods!
