### ISSUE TITLE
`pulumi up --logflow` causes node multi-lang component provider to hang

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#6912]
Repro:

1. create a component from typescript boilerplate
2. `pulumi up --logflow` and observe no progress (I think this interferes with the provider printing out the port)

**Comment by t0yv0** [comment]
Cannot reproduce on 

```
pulumi version
v3.5.1
```

**Comment by EvanBoyle** [comment]
Just gave this a try, as I was surprised this didn't repro given nothing has changed in the boilerplate. Turns out my original repro description was wrong. Specifically it is the combination of two CLI flags:

```console
$ pulumi up --skip-preview --logflow --logtostderr
```

Reproduces for me after cloning the boilerplate repro, building the provider, and running the program with the latest pulumi nodejs sdk.

**Comment by EvanBoyle** [comment]
Somehow the logflow flag is getting picked up as the engine address which causes log messages to hang. The runtime options when specifying both flags end up as: 

```
    {
      project: 'simple',
      stack: 'abc',
      dryRun: false,
      queryMode: false,
      parallel: 2147483647,
      monitorAddr: '127.0.0.1:52743',
      engineAddr: '--logtostderr',
      syncDir: undefined,
      cacheDynamicProviders: true,
      testModeEnabled: false,
      legacyApply: false
    }
```

Will prep a fix

**Comment by t0yv0** [comment]
Unfortunately having to reopen due to the fix causing https://github.com/pulumi/pulumi/issues/7642 - going to revert that fix.
