### ISSUE TITLE
Enable deterministic builds for dotnet packages

### ISSUE THREAD

**Issue by gitfool** [pulumi/pulumi#6916]
NuGet packages for dotnet have source link enabled but not [deterministic builds](https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/#deterministic-builds).

**Comment by mikhailshilkov** [comment]
What's the practical effect of this?

**Comment by gitfool** [comment]
Like it says in the link above, the source paths will be "normalized" so be the same regardless of the build server working directory, and [NuGetPackageExplorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) will show a green tick:

![image](https://user-images.githubusercontent.com/750121/116512731-9346c800-a91c-11eb-9f22-037919fd91a0.png)

Otherwise, the developer debugging experience will be the same.

**Comment by gitfool** [comment]
FTR, this is what the NuGet package looks like post merge:

![image](https://user-images.githubusercontent.com/750121/116799132-68da5200-ab4a-11eb-9104-b8aadede1994.png)
