### ISSUE TITLE
Improve how we handle/surface errors in multi-language components

### ISSUE THREAD

**Issue by infin8x** [pulumi/pulumi#6933]
From `@t0yv0`: 

> I would like us to pay attention to how failures present themselves to the user. (1) "type" error having either the component's SDK or implementation generate a value that does not match the declared schema; how do we attribute the fault and present this error nicely, or how do we make sure this never happens; (2) general unhandled error inside the implementation; how do we label the error with the component at fault and preserve the original lang stack trace. Just a little bit of attention here would go a long way. In our current code, the default behavior in these cases is not great.

**Comment by EronWright** [comment]
A great enhancement along these lines would be to be able to return validation errors from the `Construct` RPC, as one can do with the `Call` RPC.

**Comment by t0yv0** [comment]
I would add https://github.com/pulumi/pulumi-eks/issues/1220 here as a great example of a practical highly upvoted user issue. Note pulumi-eks provider is trying to do "vanilla" validation of its inputs of eks.Cluster, however when it decides that the inputs are invalid and tries to communicate to the user that they need to change the program, the user is instead presented with a gRPC traceback.

**Comment by Frassle** [comment]
@lunaris has done some initial investigation into this area, we definitely want to improve the grpc errors so that they look "clean" to users, rather than containing irrelevant grpc details.

**Comment by justinvp** [comment]
We now improved how errors are reported from packaged components.

Fixed by:
- https://github.com/pulumi/pulumi/pull/17306
- https://github.com/pulumi/pulumi/pull/17325
- https://github.com/pulumi/pulumi/pull/17429
- https://github.com/pulumi/pulumi/pull/17464

Follow-up issue tracking adding the same treatment to `Call`: https://github.com/pulumi/pulumi/issues/17553
