### ISSUE TITLE
Provide naming guidance/recommendations for SDK packages

### ISSUE THREAD

**Issue by infin8x** [pulumi/pulumi#6954]
Since Pulumi Packages will sometimes be used directly from language package registries (npmjs, NuGet Gallery, PyPI), we should help package authors land in the pit of success when naming their Pulumi Package (and the resultant SDK packages created by the `pulumi package publish` command (#6928)).

## Goals of package naming

- The Pulumi namespace (`@pulumi` on npm) or pulumi-bot account (NuGet, PyPI) should own “common” names where possible, so that it’s easy for users to fall in the pit of success if they install packages directly from the CLI without searching the registry. e.g. `@pulumi/eks`, Pulumi.Eks, or pulumi-eks should all point to the official 1st-party Pulumi Package for EKS, if possible. 
- We should try to differentiate Pulumi-owned packages from community-contributed packages, so it's easier for users of both types of packages to know where to go for support, where to look for docs, etc.

## Proposal

- All 1st-party Pulumi Packages are owned by a Pulumi-owned account (we already have this today - `pulumi-bot`)
- All 1st-party Pulumi Packages start with `@pulumi/` (on npm), `Pulumi.` (on NuGet), and `pulumi-` (on PyPI)
  - For npm, we guarantee this because we own the `@pulumi/` namespace
  - For NuGet.org, we can guarantee this using [namespace reservation](https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation), if we don't already
  - PyPI doesn't seem to have a solution, per [this thread](https://discuss.python.org/t/namespace-support-in-pypi/1609/42)
  - For Go, this is solved automatically as long as all official Pulumi packages come from the `pulumi` GitHub organization
- For 3rd-party Pulumi Packages, we should recommend (and the tooling should generate) names of this format:
  - npm: `@your-namespace/pulumi-[package-name]`
  - NuGet: `[your-namespace].Pulumi.[package-name]`
  - PyPI: `[your-namespace]-pulumi-[package-name]`
  - Go modules: n/a, this is determined by the URL from which the module is served; we recommend repo names of `[username/organization]/pulumi-[package-name]`
- If a package name has multiple words, separate those words with hyphens e.g. "pulumi-aws-quickstart-redshift"

## Other notes:
- Reference internal slack thread: https://pulumi.slack.com/archives/C01AP60KH5F/p1633149434021800
- Proposal for plugin naming

**Comment by infin8x** [comment]
### Notes from the review 5/13

- We have some funny logic for the implementation of `GetRequiredPlugins` - let's make sure to look into it.

**Comment by EvanBoyle** [comment]
One related but slightly tangential item is the set of validations that various package managers enforce. For instance I tried to publish a multi-lang package `localProcess`. I didn't have any errors from codegen, schema, or even using the locally linked package until I tried to publish to NPM and it failed. 

I can also imagine situations where folks from python try to give snake case names to packages like `local_process`. My understanding is that our codegen takes care of snake casing and translating into appropriate language specific names, but we should document (or ideally validate) what that is.

**Comment by infin8x** [comment]
### Notes from the review 7/20

Discuss the proposal above, particularly around the name of the repo, the Pulumi Package (including any directory names, the type token, etc.), and the plugin. Some specific questions: do we support and/or recommend dashes? Capital letters?

**Comment by iwahbe** [comment]
>Go modules: n/a, this is determined by the URL from which the module is served; we recommend repo names of [username/organization]/pulumi-[package-name]

I'm interpreting the path as `forge-url/[username|orginization/pulumi-[package-name]`. As an example: `github.com/iwahbe/pulumi-my-package`.

**Comment by ringods** [comment]
Coming late to the party, this is what we standardized on for Pulumiverse:

https://github.com/pulumiverse/infra/blob/main/README.md#package-registries
