### ISSUE TITLE
Plain inputs typed as a type in the schema should not be typed as a plain type in the generated SDKs

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#6957]
It used to be possible to have a plain input `foo` typed as a type `xyz:index:Foo` (or as an array or map of `xyz:index:Foo`) where the generated code would type the plain property `foo` as an unwrapped `T` rather than `Input<T>`.

However, after #6686 and #6811, the codegen now emits a plain type for `xyz:index:Foo` and types the plain property `foo` as the plain type. So there's no way to accept a plain property as a type that itself has properties that are not plain.

**Comment by justinvp** [comment]
To address this, we'll revert back to the old behavior, where `foo` will be typed as `FooArgs` rather than a plain `Foo` type. `FooArgs`'s properties will be wrapped as `Input<T>`, unless designated as `plain` in which case the type won't be wrapped as `Input<T>` but will be just `T`.

**Comment by justinvp** [comment]
@pgavlin, I began looking at this, but I think it'll be much faster if you take it.

**Comment by justinvp** [comment]
Concrete example from a customer:

> I want a property generated on an args class for a resource which is:
> 
> ```
> storageClasses: { [k: string]: StorageClassArgs }
> ```
> 
> Where all of the properties on `StorageClassArgs` are `Input<T>` rather than prompt.

**Comment by infin8x** [comment]
Fixed by #7059 

Follow-on work tracked in #7359
