### ISSUE TITLE
C# example has incorrect property name

### ISSUE THREAD

**Issue by hognevevle** [pulumi/pulumi#6965]
File: [themes/default/content/docs/reference/pkg/aws/iam/policy.md](https://www.pulumi.com/docs/reference/pkg/aws/iam/policy/)

The C# example assigns a serialized JSON object to a property of `PolicyArgs` named `Policy`. However, this property doesn't exist in the C# SDK. I believe the correct replacement would be `PolicyDocument`.

**Comment by mikhailshilkov** [comment]
Dupe of #10042
