### ISSUE TITLE
Error: Minimum version requirement failed. The minimum CLI version requirement is 3.2.0-alpha, your current CLI version is 3.1.0. Please update the Pulumi CLI.

### ISSUE THREAD

**Issue by hcharley** [pulumi/pulumi#6972]
## Expected behavior

Expecting to see a brew pulumi version of 3.2.0

## Steps to reproduce

1. Upgrade pulumi to package.json at 3.2.0
2. Attempt to run `brew upgrade pulumi`
3. Note that there is no version to upgrade to
4.

## Context (Environment)

Running Pulumi Automation API.

**Comment by stack72** [comment]
Hi @hcharley 

There's a PR open right now for homebrew - https://github.com/Homebrew/homebrew-core/pull/76707

We are waiting on them to merge it

Sorry for this

Paul

**Comment by hcharley** [comment]
All good. Thanks for the update. It looks like it was merged. Will try this out tomorrow.

**Comment by stack72** [comment]
Hi @hcharley 

I've just verified that the release is now available and working on homebrew 

```
==> Upgrading 1 outdated package:
pulumi 3.1.0 -> 3.2.0
==> Upgrading pulumi 3.1.0 -> 3.2.0
==> Downloading https://ghcr.io/v2/homebrew/core/pulumi/manifests/3.2.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pulumi/blobs/sha256:7b751841c9cac1af45b8e2a9b79b62f4229f8b388738d1ad6b177448ac220e86
==> Downloading from https://pkg-containers-az.githubusercontent.com/ghcr1/blobs/sha256:7b751841c9cac1af45b8e2a9b79b62f4229f8b388738d1ad6b177448a
######################################################################## 100.0%
==> Pouring pulumi--3.2.0.catalina.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/pulumi/3.2.0: 18 files, 134MB
```

I am going to close this out - please let me know if you have any other issues here

Paul
