### ISSUE TITLE
Strange errors when using blank stack passphrase

### ISSUE THREAD

**Issue by Oliver-Sellwood** [pulumi/pulumi#6974]
Using Pulumi with a blank stack passphrase in GCP results in strange errors.

I am not 100% certain this is just for GCP. Another project I have worked on with `"@pulumi/pulumi": "^2.24.1"` in AWS does not have this issue.

## Expected behavior
Blank passphrase works the same as a non blank passphrase

## Current behavior
Running an initial `pulumi up` works as expected but any further interactions with the stack result in the folllowing error

```
error: constructing secrets manager of type "passphrase": unable to find either `PULUMI_CONFIG_PASSPHRASE` or `PULUMI_CONFIG_PASSPHRASE_FILE` when trying to access the Passphrase Secrets Provider; please ensure one of these environment variables is set to allow the operation to continue
```

## Steps to reproduce

1. echo 'export PULUMI_CONFIG_PASSPHRASE=""' >> ~/.bashrc
2. pulumi up
3. pulumi stack output kubeconfig

## Workaround
Set a stack password
```
echo 'export PULUMI_CONFIG_PASSPHRASE=secret' >> ~/.bashrc
```

## Context (Environment)

package.json
```
{
    "name": "project",
    "devDependencies": {
        "@types/node": "^10.0.0"
    },
    "dependencies": {
        "@pulumi/gcp": "^5.2.0",
        "@pulumi/kubernetes": "^3.1.1",
        "@pulumi/pulumi": "^3.2.0"
    }
}

```

index.ts
```
import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";
import * as gcp from "@pulumi/gcp";

const name = "helloworld";

// Create a GKE cluster
const engineVersion = gcp.container.getEngineVersions().then(v => v.latestMasterVersion);
const cluster = new gcp.container.Cluster(name, {
    initialNodeCount: 2,
    minMasterVersion: engineVersion,
    nodeVersion: engineVersion,
    nodeConfig: {
        machineType: "n1-standard-1",
        oauthScopes: [
            "https://www.googleapis.com/auth/compute",
            "https://www.googleapis.com/auth/devstorage.read_only",
            "https://www.googleapis.com/auth/logging.write",
            "https://www.googleapis.com/auth/monitoring"
        ],
    },
});

// Export the Cluster name
export const clusterName = cluster.name;

// Manufacture a GKE-style kubeconfig. Note that this is slightly "different"
// because of the way GKE requires gcloud to be in the picture for cluster
// authentication (rather than using the client cert/key directly).
export const kubeconfig = pulumi.
    all([ cluster.name, cluster.endpoint, cluster.masterAuth ]).
    apply(([ name, endpoint, masterAuth ]) => {
        const context = `${gcp.config.project}_${gcp.config.zone}_${name}`;
        return `apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ${masterAuth.clusterCaCertificate}
    server: https://${endpoint}
  name: ${context}
contexts:
- context:
    cluster: ${context}
    user: ${context}
  name: ${context}
current-context: ${context}
kind: Config
preferences: {}
users:
- name: ${context}
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
`;
    });

// Create a Kubernetes provider instance that uses our cluster from above.
const clusterProvider = new k8s.Provider(name, {
    kubeconfig: kubeconfig,
});

```

**Comment by hakoerber** [comment]
This is related to #6893.

Specifically [this if expression](https://github.com/pulumi/pulumi/blob/a1a2ce91269ad8231b1ef3cfa38ee3e1ed6434ea/pkg/secrets/passphrase/manager.go#L180):

```go
if phrase == "" {
	return nil, errors.New("unable to find either `PULUMI_CONFIG_PASSPHRASE` nor " +
		"`PULUMI_CONFIG_PASSPHRASE_FILE` when trying to access the Passphrase Secrets Manager; please ensure one " +
		"of these environment variables is set to allow the operation to continue")
}
```

I think we do not properly differentiate between an *unset* env variable and an *empty* one.

Not sure how to proceed here. If wanted, I could work on a fix that allows empty env variables again.

**Comment by mikhailshilkov** [comment]
@stack72 Do you know what our intent is here: do we want to support empty passphrases?

**Comment by stack72** [comment]
Hi @hakoerber  / @Oliver-Sellwood 

I am sorry this caused an issue for you - this was certainly not intended. AThe reasoning behind the change is that when a user had unset either of the 2 environment variables but the stack was protected by a passphrase, then we were trying to decrypt the stack using an empty passphrase by default which was throwing an encryption error. It was not expected to break or change any other use cases. I have just spent some time on this as follows:

```
pulumi up -y -f
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Updating (pphrase-2)

error: could not deserialize deployment: constructing secrets manager of type "passphrase": unable to find either `PULUMI_CONFIG_PASSPHRASE` or `PULUMI_CONFIG_PASSPHRASE_FILE` when trying to access the Passphrase Secrets Provider; please ensure one of these environment variables is set to allow the operation to continue
```

is what the user will currently get when using an empty passphrase due to the new logic we introduced in v3.2.0. 

I have just made the following fix to allow this to work as expected:

```
▶ PULUMI_CONFIG_PASSPHRASE="" pulumi up -y -f
Updating (pphrase-2)

     Type                 Name                             Status
     pulumi:pulumi:Stack  test-empty-passphrase-pphrase-2

Outputs:
  + foo: "[secret]"

Resources:
    1 unchanged

Duration: 1s
```

Notice I am using an empty environment variable that we now check exists rather than just the contents of the environment variable. This is a happy medium that will allow both sets of use cases to work as expected

I am going to plan on getting this through our CI system today and a patch created for this functionality

Again, I am very sorry that you have been hit by this error. This was a complete misunderstanding that people would be using blank passphrases :/

Paul
