### ISSUE TITLE
Cannot export empty PULUMI_CONFIG_PASSPHRASE

### ISSUE THREAD

**Issue by PlusMinus0** [pulumi/pulumi#6977]
It seems to be impossible now, to use an empty passphrase. This is a possible regression with 3.2.0 because it is still working with 3.1.0.
## Expected behavior
To unlock the stack with an empty passphrase, in pulumi 3.1, this worked

```$ PULUMI_CONFIG_PASSPHRASE="" pulumi up```

## Current behavior
Since 3.2 this does not work, downgrading makes it work again.

```
$ PULUMI_CONFIG_PASSPHRASE="" pulumi up
error: constructing secrets manager of type "passphrase": unable to find either `PULUMI_CONFIG_PASSPHRASE` or `PULUMI_CONFIG_PASSPHRASE_FILE` when trying to access the Passphrase Secrets Provider; please ensure one of these environment variables is set to allow the operation to continue
```

**Comment by stack72** [comment]
Hi @PlusMinus0 

I just merged a Pull Request that fixes this and we will be cutting v3.2.1 in order to fix this functionality

https://github.com/pulumi/pulumi/pull/6976

Sorry this happened here

Paul
