### ISSUE TITLE
[sdk/python] Deployment hangs when output value's type doesn't match type annotation

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#6981]
When resolving outputs, if there is a type mismatch between the output value and the expected type from the type annotation, the deployment appears to hang, and canceling yields an unhelpful error message, e.g. something like:

```
  File "/Users/user/temp/proj/venv/lib/python3.8/site-packages/pulumi/runtime/rpc.py", line 634, in translate_output_properties
    raise AssertionError(f"Unexpected type; expected 'dict' got '{typ}'")
AssertionError: Unexpected type; expected 'dict' got 'typing.Sequence[pulumi_kubernetes.core.v1.outputs.Container]'
```

This can happen if inputs aren't typed correct (when the inputs are propagated as outputs) during preview, or when there is a bug in the provider itself (e.g. dynamic providers).

We should ensure such error messages bubble up and fail the deployment rather than hanging.

We should also thread through the property path and include it in the error message, and consider also including the output value.

Note that this issue has been around for a while since when we introduced typed input/output classes for nested data.

**Comment by t0yv0** [comment]
@pgavlin @justinvp thanks for taking this over!

It sounds like I did start on this in PR 7049

**Comment by t0yv0** [comment]
Sorry btw this got carried over and fell off my radar. I put in in "IN Review" column and forgot about this. So what the PR does:

- it has the change to make the hang into a normal error

- it is lacking a checked-in automated test case

- the nature of the error is not changing (it's kind of as unhelpful as before, but surfaces better than a hang)

**Comment by t0yv0** [comment]
@pgavlin do you want to take over or you want me to finish the PR by adding the test case? This is assuming changing the error itself is out of scope.
