### ISSUE TITLE
Example from `BranchPolicyBuildValidation` documentation generates a Type mismatch error

### ISSUE THREAD

**Issue by jahsome** [pulumi/pulumi#6986]
I can’t figure out how I’m to coerce an `Output<string>` into a number, (I presume I'm missing some apply trickery?) and the example from docs appears to be broken.

The example provided [here](https://www.pulumi.com/docs/reference/pkg/azuredevops/branchpolicybuildvalidation) results in an error.

I believe the issue to be with the example:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as azuredevops from "@pulumi/azuredevops";

const project = new azuredevops.Project("project", {});
const git = new azuredevops.Git("git", {
    // ...
});
const buildDefinition = new azuredevops.BuildDefinition("buildDefinition", {
   // ...
});
const branchPolicyBuildValidation = new azuredevops.BranchPolicyBuildValidation("branchPolicyBuildValidation", {
    projectId: project.id,
    enabled: true,
    blocking: true,
    settings: {
        displayName: "Don't break the build!",
        buildDefinitionId: buildDefinition.id,                        // 👈 HERE
        validDuration: 720,
        filenamePatterns: [
            "/WebApp/*",
            "!/WebApp/Tests/*",
            "*.cs",
        ],
        // ...
    },
});
```
The issue is the `BuildDefinition.id` is an `Output<string>` whereas `buildDefinitionId` requires an `Input<number>`.

## Expected behavior

The documentation should include a working example.

## Current behavior

The documentation example results in the following error:

```
(property) BranchPolicyBuildValidationSettings.buildDefinitionId: pulumi.Input<number>
The ID of the build to monitor for the policy.

Type 'Output<string>' is not assignable to type 'Input<number>'.
  Type 'Output<string>' is not assignable to type 'OutputInstance<number>'.
    Types of property 'apply' are incompatible.
      Type '{ <U>(func: (t: string) => Promise<U>): Output<U>; <U>(func: (t: string) => OutputInstance<U>): Output<U>; <U>(func: (t: string) => U): Output<...>; }' is not assignable to type '{ <U>(func: (t: number) => Promise<U>): Output<U>; <U>(func: (t: number) => OutputInstance<U>): Output<U>; <U>(func: (t: number) => U): Output<...>; }'.
        Types of parameters 'func' and 'func' are incompatible.
          Types of parameters 't' and 't' are incompatible.
            Type 'string' is not assignable to type 'number'.ts(2322)
```

## Steps to reproduce

1. `pulumi new typescript`
2. install `@pulumi/azuredevops`
3. paste [example from documentation](https://www.pulumi.com/docs/reference/pkg/azuredevops/branchpolicybuildvalidation/#example-usage)
4. `pulumi up`

## Context (Environment)
I am attempting to follow the documentation examples.

## Affected feature
`unknown`

**Comment by jahsome** [comment]
> Hi @jahsome! You should be able to do
> 
> ```ts
> buildDefinition.id.apply(v => Number(v))
> // or
> buildDefinition.id.apply(v => parseInt(v)) // or parseFloat(v)?
> ```

 Thank you for your wisdom! 🤜🤛

**Comment by mikhailshilkov** [comment]
I believe the question has been answered, so I'll go ahead and close the issue
