### ISSUE TITLE
How do you write a Pulumi provider that makes a REST API request in pytyon?

### ISSUE THREAD

**Issue by dennislloydjr** [pulumi/pulumi#6988]
How do you write a Pulumi provider that makes a REST API request in pytyon?

## Expected behavior
I expect that I can write a new ResourceProvider that implements the create method. Within the create method, I should be able to call an arbitrary REST API using the requests library to create a resource.

## Current behavior
I receive the message:
```
Diagnostics:
  pulumi:pulumi:Stack (data-services-account-dev):
    C:\Python39\lib\site-packages\grpc\_server.py:448: RuntimeWarning: coroutine 'invoke.<locals>.do_rpc' was never awaited
      return None, False
    RuntimeWarning: Enable tracemalloc to get the object allocation traceback

    error: update failed

  pulumi-python:dynamic:Resource (dev-slack-bot):
    error: Exception calling application: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.

Resources:
    1 unchanged
```

## Steps to reproduce
from pulumi import ComponentResource, export, Input, Output
from pulumi.dynamic import Resource, ResourceProvider, CreateResult
from typing import Optional

import requests
from requests.auth import HTTPBasicAuth

class FivetranUserArgs(object):
  given_name: Input[str]
  family_name: Input[str]
  email: Input[str]
  phone: Optional[Input[str]]
  picture: Optional[Input[str]]
  role: Input[str]
  def __init__(self, given_name, family_name, email, phone=None, picture=None, role="ReadOnly"):
    self.given_name = given_name
    self.family_name = family_name
    self.email = email
    self.phone = phone
    self.picture = picture
    self.role = role

class FivetranUserProvider(ResourceProvider):
  def _auth(self):
    return HTTPBasicAuth("my-key", "my-secret")

  def create(self, props):
    payload = {
      "given_name": props["given_name"],
      "family_name": props["family_name"],
      "email": props["email"],
      "phone": props["phone"] if "phone" in props else None,
      "picture": props["picture"] if "picture" in props else None,
      "role": props["role"]
    }

    url = "https://api.fivetran.com/v1/users"
    response = requests.post(url=url,auth=self._auth(),json=payload).json()

    return CreateResult(response["data"]["id"], {**props, **response.raw_data})

class FivetranUser(Resource):
  given_name: Output[str]
  family_name: Output[str]
  email: Output[str]
  phone: Output[str]
  picture: Output[str]
  role: Output[str]

  def __init__(self, name, args: FivetranUserArgs, opts = None):
    full_args = {'name': None, 'given_name':None, 'family_name':None, 'email':None, 'phone':None, 'picture':None, 'role':None, **vars(args)}
    super().__init__(FivetranUserProvider(), name, full_args, opts)

## Context (Environment)
I'm trying to automate configuring Fivetran, a data integration provider. I'd like to be able to create resources such as users, connections and groups.

I'm running:
Pulumi 3.1.0
Python 3.9.2
Powershell 7.1.3
Windows 10 Pro

**Comment by lblackstone** [comment]
@komalali Do you know what's going wrong here?

**Comment by komalali** [comment]
Hey! I followed up with @dennislloydjr on slack. I couldn't use the exact code defined here as I don't have the correct credential, and I couldn't replicate the issue with my own attempt. I gave them a starting point that makes a request in the create method, described below.

```python
import requests
import binascii
import os
import pulumi
from pulumi.dynamic import Resource, ResourceProvider, CreateResult


class StatusArgs(object):
    url: str
    def __init__(self, url: str) -> None:
        self.url = url


class StatusResourceProvider(ResourceProvider):
    def create(self, args):
        response = requests.get(url=args["url"])
        random = binascii.b2a_hex(os.urandom(16)).decode("utf-8")
        return CreateResult(f"status-{random}", {"code": response.status_code})


class Status(Resource):
    url: pulumi.Input[str]
    code: pulumi.Output[str]
    def __init__(self, name, args, opts=None):
        args = {**args, "code": ""}
        super().__init__(StatusResourceProvider(), name, args, opts)


r = Status("foo", vars(StatusArgs(url="https://www.google.com")))
pulumi.export("r_status", r.code)
pulumi.export("r_url", r.url)
```

I'm going to close out this issue as I believe that answers the question.
