### ISSUE TITLE
"The Pulumi CLI encountered a fatal error. This is a bug!" while trying `pulumi import`

### ISSUE THREAD

**Issue by patrickmburrell** [pulumi/pulumi#6990]
OS: macOS Catalina, v10.15.7
computer: MacBook Pro (Retina, 15-inch, Late 2013)

I ran the following command:
`pulumi import aws:ec2/instance/Instance "[resource name here]" [id-here]`

I wasn't sure about the type token to use, and I couldn't find any documentation for it, so I just guessed at `aws:ec2/instance/Instance`. I got the following response:

================================================================================
The Pulumi CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/pulumi/issues/
Please provide all of the below text in your report.
================================================================================
Pulumi Version:   v3.2.1
Go Version:       go1.16.3
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            fatal: An assertion has failed: Module member token 'aws:ec2/instance/Instance' missing module member delimiter

goroutine 1 [running]:
runtime/debug.Stack(0xc0018bf240, 0x55d05e0, 0xc0005f2bc0)
        /usr/local/Cellar/go/1.16.3/libexec/src/runtime/debug/stack.go:24 +0x9f
main.panicHandler()
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/cmd/pulumi/main.go:29 +0x76
panic(0x55d05e0, 0xc0005f2bc0)
        /usr/local/Cellar/go/1.16.3/libexec/src/runtime/panic.go:965 +0x1b9
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /private/tmp/pulumi-20210506-41645-1px53ac/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x7ffeefbff500, 0x5993e0d, 0x38, 0xc0018bf490, 0x1, 0x1)
        /private/tmp/pulumi-20210506-41645-1px53ac/sdk/go/common/util/contract/assert.go:33 +0x1a5
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.ModuleMember.Module(0x7ffeefbff5ce, 0x19, 0xc000691410, 0x0)
        /private/tmp/pulumi-20210506-41645-1px53ac/sdk/go/common/tokens/tokens.go:192 +0xd2
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.ModuleMember.Package(0x7ffeefbff5ce, 0x19, 0x5c5d148, 0x1)
        /private/tmp/pulumi-20210506-41645-1px53ac/sdk/go/common/tokens/tokens.go:187 +0x35
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.Type.Package(0x7ffeefbff5ce, 0x19, 0x36, 0x5932cad)
        /private/tmp/pulumi-20210506-41645-1px53ac/sdk/go/common/tokens/tokens.go:227 +0x70
github.com/pulumi/pulumi/pkg/v3/engine.newDeployment(0xc000a72dc0, 0xc001384720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/engine/deployment.go:177 +0x470
github.com/pulumi/pulumi/pkg/v3/engine.update(0xc000a72dc0, 0xc001384720, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, 0x0, ...)
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/engine/update.go:439 +0x4e7
github.com/pulumi/pulumi/pkg/v3/engine.Import(0x5cba9e8, 0xc000a03e60, 0xc000a72dc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffffff, ...)
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/engine/import.go:43 +0x56e
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).runEngineAction(0xc000a62270, 0x5cc6fc8, 0xc000196008, 0x594839b, 0xf, 0x5cb1c68, 0xc0009ba0c0, 0xc0000a2c80, 0xc00020b040, 0x36, ...)
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/backend/httpstate/backend.go:1043 +0xce5
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).apply(0xc000a62270, 0x5cc6fc8, 0xc000196008, 0x594839b, 0xf, 0x5ce34f0, 0xc0008bc780, 0xc0000a2c80, 0xc00020b040, 0x36, ...)
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/backend/httpstate/backend.go:949 +0x2ba
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPrompt(0x5cc6fc8, 0xc000196008, 0x594839b, 0xf, 0x5ce34f0, 0xc0008bc780, 0xc0000a2c80, 0xc00020b040, 0x36, 0xc00019bda0, ...)
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/backend/apply.go:115 +0x133
github.com/pulumi/pulumi/pkg/v3/backend.PreviewThenPromptThenExecute(0x5cc6fc8, 0xc000196008, 0x594839b, 0xf, 0x5ce34f0, 0xc0008bc780, 0xc0000a2c80, 0xc00020b040, 0x36, 0xc00019bda0, ...)
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/backend/apply.go:200 +0x1a8
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudBackend).Import(0xc000a62270, 0x5cc6fc8, 0xc000196008, 0x5ce34f0, 0xc0008bc780, 0xc0000a2c80, 0xc00020b040, 0x36, 0xc00019bda0, 0x1, ...)
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/backend/httpstate/backend.go:842 +0x109
github.com/pulumi/pulumi/pkg/v3/backend.ImportStack(0x5cc6fc8, 0xc000196008, 0x5ce34f0, 0xc0008bc780, 0xc0000a2c80, 0xc00020b040, 0x36, 0x0, 0x0, 0x0, ...)
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/backend/stack.go:91 +0xe5
github.com/pulumi/pulumi/pkg/v3/backend/httpstate.(*cloudStack).Import(0xc0008bc780, 0x5cc6fc8, 0xc000196008, 0xc0000a2c80, 0xc00020b040, 0x36, 0x0, 0x0, 0x0, 0xc000507848, ...)
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/backend/httpstate/stack.go:153 +0xc8
main.newImportCmd.func1(0xc000995b80, 0xc000992d80, 0x3, 0x3, 0x0, 0x0)
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/cmd/pulumi/import.go:462 +0xd05
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc000995b80, 0xc000992d80, 0x3, 0x3)
        /private/tmp/pulumi-20210506-41645-1px53ac/sdk/go/common/util/cmdutil/exit.go:112 +0x6b
github.com/spf13/cobra.(*Command).execute(0xc000995b80, 0xc000992d50, 0x3, 0x3, 0xc000995b80, 0xc000992d50)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c0840, 0xc00006e740, 0x406fc68, 0xc000000180)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /private/tmp/pulumi-20210506-41645-1px53ac/pkg/cmd/pulumi/main.go:48 +0x4d

**Comment by stack72** [comment]
Hi @patrickmburrell 

I'm sorry you ran into this error - we should definitely fix this up so that it doesn't happen

I can point you at https://www.pulumi.com/docs/reference/pkg/aws/ec2/instance/#import which will have an import example with the correct type token

But we should fix this up to make this a better error

Paul

**Comment by patrickmburrell** [comment]
Hi Paul,

Thanks for the quick response, and also for the `import` reference. I did end up finding that same page about 10 minutes after I posted.

I'm really enjoying Pulumi so far. "Great job!" to all the minds who've contributed to this.

Patrick
