### ISSUE TITLE
Colored output with automation

### ISSUE THREAD

**Issue by tmccombs** [pulumi/pulumi#6997]
## Affected feature

When using the automation API, when calling `preview` or `up`, it would be nice if there was a configuration option to specify that you want ANSI color codes in the output, for use in custom CLI use cases.

**Comment by adrianord** [comment]
I'm also interested in this being a feature of the automation api. I see that there are options that get passed to the pulumi subprocess here https://github.com/pulumi/pulumi/blob/ccd00c3731811e99bd737680e4da9ac3502bf3fe/sdk/nodejs/automation/stack.ts#L155-L187

It would be nice to either have an option for color always here, or have a way to pass additional arguments to the subprocess ourselves.
