### ISSUE TITLE
unable to find either `PULUMI_CONFIG_PASSPHRASE`

### ISSUE THREAD

**Issue by reidlai** [pulumi/pulumi#7001]
After upgrade to pulumi cli to v3.2.1, I keep on to receive unable to find either `PULUMI_CONFIG_PASSPHRASE` randomly when I run pulumi up.  Should I fall back old version and wait until fix?

**Comment by stack72** [comment]
Hi @reidlai 

If you are using a stack with a blank passphrase then you need to set PULUMI_CONFIG_PASSPHRASE="" to your environment where Pulumi is being run

We added a check to the Pulumi passphrase secrets manager that you have intentionally set an empty passphrase on your stack

I hope this helps

Paul

**Comment by stack72** [comment]
Hi @reidlai 

I am going to close this out as we have not heard back from you - please let me know if you still get the issue after the suggestion above and I can reopen it

Thanks

Paul
