### ISSUE TITLE
Automation API uses application appsettings.json and errors on port binding

### ISSUE THREAD

**Issue by sam-cogan** [pulumi/pulumi#7020]
It seems that if you have a dotnet web app using Kestrel, and you set the port in appsettings.json then the Pulumi automation API also tries to use the same port when it launches it's Kestrel instance, which then fails because the port is already in use by the main web app.

## Expected behavior

The automation API should ignore the appsettings.json file and use a non-conflicting port

## Current behavior

Automation api crashes due to port conflict

## Steps to reproduce

1. Create a dotnet web app using Kestrel
2. Create a appsettings.json defining the port for the kestral app
3. Use the Pulumi automation api in the application code
4. Launch and see failure on refresh/preview/up

## Context (Environment)

Trying to utilise the automation API inside a web API running on Kestrel

## Affected feature

Automation API

**Comment by lblackstone** [comment]
I don't think Pulumi is explicitly reading the `appsetting.json` file, so maybe that's automatically picked up by the .NET runtime.

@justinvp Do you know?

**Comment by komalali** [comment]
@orionstudt might have the relevant context here from the conversation in slack.

**Comment by orionstudt** [comment]
@lblackstone @komalali Hi everyone, sorry. I think it is either our call to `.CreateDefaultBuilder()` or `.ConfigureWebHostDefaults(...)` that is configuring Kestrel to check for the presence of `appsettings.json`.

Couple that with when you publish an ASPNET API that has a dependency on `Pulumi.Automation`, meaning the `appsettings.json` will be in the same directory as the Automation API binary, than I believe that is why it is getting picked up.

**Comment by orionstudt** [comment]
Also I think whatever resolution is made for this, could also resolve #6780 

Since currently the work around for #6780 is to use `appsettings.json` to disable logging.
