### ISSUE TITLE
CLI Parameter: on destroy, skip protected resources

### ISSUE THREAD

**Issue by lenardchristopher** [pulumi/pulumi#7033]
## Affected feature

The pulumi CLI should add a parameter to ignore protected resources. 

Context example: in azure I have stacks that create resources in a shared resource group across all the stacks. I do not want to destroy that resource group on every stack destroy.

`pulumi destroy --skip-protected-resources`

There was also a comment in you slack workspaces from someone else looking for the same thing.
https://pulumi-community.slack.com/archives/C84L4E3N1/p1615712172308500

**Comment by mikhailshilkov** [comment]
There's now a separate option for this behavior: [RetainOnDelete](https://www.pulumi.com/docs/intro/concepts/resources/options/retainondelete/). Given this option exists, I don't think we want a separate CLI flag, so I'll close this issue.
