### ISSUE TITLE
Structured config with inline automation

### ISSUE THREAD

**Issue by tmccombs** [pulumi/pulumi#7044]
## Affected feature

the `setConfig` and `setAllConfig` functions in the automation API don't have any way to  set structured config, such as `aws:assumeRole.roleArn`.   Basically, there needs to be a way to have the `pulumi config` command run with the `--path` option. I think this could be done by adding an optional boolean parameter to these functions that would result in passing the `--path` option. Or maybe another property on `ConfigValue`, although in that case, I'm not sure if it would work with `setAllConfig` if some have path=true and others don't.

**Comment by EvanBoyle** [comment]
Closing as a duplicate of https://github.com/pulumi/pulumi/issues/5506

**Comment by tmccombs** [comment]
ah man, I looked for that and couldn't find it.  weird that that didn't show up when I searched for "structured config automation"....
