### ISSUE TITLE
Pulumi Import does not gracefully handle ':' character in AWS tags

### ISSUE THREAD

**Issue by shreecodes** [pulumi/pulumi#7046]
A common practice for AWS tags is to use a colon `:` separator in the tag labels as a means of applying namespaces to tags.  For example, the label for a tag might be `mycompany:myorg:myservice:mytag`. Running `pulumi import` in the CLI for AWS resources that have `:` in their tags displays an error instead of printing out the generated code for the imported resource.

## Expected behavior
Usually, the CLI would output the code necessary to define the resource.

## Current behavior
 The resource imports successfully, but there is a nasty error at the end of the output where the code would normally be:

```
error: internal error: Error: Missing attribute separator

  on anonymous.pp line 5:
   5:     tags ={
   6: mycompany:mytag = "mytagvalue"}

Expected a newline or comma to mark the beginning of the next attribute.
```

## Steps to reproduce

1. Create a resource in AWS, outside of Pulumi, that has a tag with `:` separators in the label: `mycompany:myname`. S3 Bucket may be easiest.
2. In a pulumi project, use the CLI to import the resource.

## Context (Environment)
macOS 11.3.1
pulumi cli v3.1.0

This isn't a major issue, but it does make it tedious to get infra imported into Pulumi.

**Comment by jspiewak** [comment]
See pulumi/pulumi-aws#1368

**Comment by pratikgajjar** [comment]
I am facing this issue, Why it mentions that it's issue with golang project but cli provided by all official doc using GoLang so even if my project is in TypeScript It's not helping. 

I mean this should create problem for anyone regardless of their pulumi project language because cli is in golang.

Let me know If I misunderstood anything.

**Comment by shreecodes** [comment]
You're right @pratikgajjar  - when I first wrote up the issue I didn't realize it affected other languages as well. I updated the issue accordingly.
