### ISSUE TITLE
Link to Pulumi Dockerfile on Dockerhub is broken

### ISSUE THREAD

**Issue by spara** [pulumi/pulumi#7056]
## Expected behavior
go to: https://hub.docker.com/r/pulumi/pulumi
click on link: https://github.com/pulumi/pulumi/blob/master/dist/pulumi/Dockerfile

should display [Dockerfile](https://github.com/pulumi/pulumi/blob/master/docker/pulumi/Dockerfile)

## Current behavior
click on link: https://github.com/pulumi/pulumi/blob/master/dist/pulumi/Dockerfile

displays 404

## Steps to reproduce

1. go to: https://hub.docker.com/r/pulumi/pulumi
2. click on link: https://github.com/pulumi/pulumi/blob/master/dist/pulumi/Dockerfile

**Comment by stack72** [comment]
nice catch @spara - I just updated the link
