### ISSUE TITLE
Support methods for multi-language components

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#7072]
Components often have methods that provide additional functionality associated with an instance of a component. We will add a new capability in the schema and Provider interface to support resource methods.

## Design

Resource methods will be implemented by adding a new field, `methods`, to `schema.ResourceSpec`. This field will map from method names to functions. Functions will be identified using a JSON path, which must refer to a function in the containing schema. If a method map refers to a function that does not exist or refers to an entity that is not a function, `schema.ImportSpec` will return an error. By convention, method names should be in `camelCase`, and functions that implement methods should use a token of the form `pkgName:path/to/module:ResourceName/methodName`. A function that implements a resource method for a resource type T must have an input field with the name `__self__` of the resource type T. The implementation of a resource method should depend only on properties of a resource type that are present in the schema, as the value of the `__self__` parameter will be a resource reference that can only be resolved to its serializable state.

### Code Generation

A resource method definition in a Pulumi schema should generate an appropriately-scoped method or function in each SDK. For all of our currently-supported languages, this should be a member function on the appropriate resource type.

### `Call` Provider gRPC

While methods could be implemented with the existing `Invoke` method with some additional arguments, instead we will add a new `Call` gRPC method specifically for methods. `Call` will take similar arguments as `Invoke` and additionally accept the monitor address and component resource options, to be able to create child resources of a component inside Call.

### SDKs

We will provide helpers in each SDK to make it easier to implement `Call` for methods, similar to what we’ve done for `Construct`, adapting the raw gRPC values into the Pulumi SDK model in each language.

## Primary Work Items for 7/8

- [x] #7141
- [x] #7363
- [x] #7379
- [x] #7364
- [x] #7377
- [x] #7378
- [x] #7437
- [x] #7438

## M59

- [x] #7555
- [x] #7488
- [ ] #7582
- [ ] #7606

**Comment by lukehoban** [comment]
> Resource methods will be implemented by adding a new field, methods, to schema.ResourceSpec. This field will map from method names to functions.

We likely want to support module- level functions as well as methods. We support module-level functions as invokes today, but will need to allow them to opt-in to being `Call`s instead I assume?

**Comment by t0yv0** [comment]
> additional functionality associated with an instance of a component

What is meant by an instance of a component? Does the method implementation operate on read-only fields from a serialized representation of the object implementing the component, or does it operate on an actual object that has continuous identity in the provider process address space and can therefore mutate fields?

**Comment by t0yv0** [comment]
More broadly, can implementations of these methods do anything or is it restricted somewhat? Reading the above, they can:

- create child resources
- mutate the state of the component instance (or not?)

Can they also create arbitrary resources for example or is this restricted? Thanks.

**Comment by justinvp** [comment]
> What is meant by an instance of a component? Does the method implementation operate on read-only fields from a serialized representation of the object implementing the component, or does it operate on an actual object that has continuous identity in the provider process address space and can therefore mutate fields?

Currently, it's the former. Inside the provider implementation, the `__self__` argument is a resource reference, which will be unmarshaled as a new instance of the component, with its state from the engine (the state that was specified via `RegisterResourceOutputs`).

One annoying aspect of this is that it requires the component to be registered so that a new instance can be instantiated when `__self__` is unmarshaled, and the implementation of the component in the provider has to handle a the `ResourceOption.Urn` option being specified.

And another problematic aspect of this is that currently the rehydrated component instance will be missing the `providers` map, so if you want to create resources from a method, and use the same providers as the component, you'll currently manually have to ensure any of those providers are saved in the state, so they are available from the method.

To address these issues, we're considering making it so that when a resource reference is unmarshaled, if there's an existing instance available in the same provider process address space for a urn/id, just return the existing instance, which is what the "Provide a way to make `__self__` resource options available for implicit use by children from methods" follow-up task is about.

> More broadly, can implementations of these methods do anything or is it restricted somewhat?

You can create arbitrary new resources (and specify the component as the parent of those new resources), but you can't mutate the state of the component.

**Comment by t0yv0** [comment]
Thanks for explaining! Naively this seems workable, viz the client code does `new`, which allocates state in the engine and a URN, the URN gets passed to provider as part of Call, and by the time provider is executing Call it should indeed find the state in the engine by URN lookup. There seems to be now ay to do Call before new, so sequencing here works.

Obligatory plug here for RPC systems out there that have the distributed object capability and reference passing like https://capnproto.org/rpc.html#distributed-objects (for much much later).

**Comment by justinvp** [comment]
Closing this issue out as the core support is available (.NET PRs to be merged soon). There are some remaining follow-ups that we'll track separately as their own items:

- https://github.com/pulumi/pulumi/issues/7648
- https://github.com/pulumi/pulumi/issues/7649
- https://github.com/pulumi/pulumi/issues/7650
- https://github.com/pulumi/pulumi/issues/7651
