### ISSUE TITLE
cli commands can be slow on Windows

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#7091]
This is still light on actionable data, but we've had numerous users report the `pulumi` cli is slow on Windows machines. This has been observed for even simple commands such as `pulumi stack`, `pulumi stack select`, etc.

Will update this with more details as we get them.

**Comment by EvanBoyle** [comment]
@clstokes any idea if this is persisting or if there is any more data? Wondering if there is overlap with some of the things we've observed that are more generic perf issues such as https://github.com/pulumi/pulumi/issues/6445

**Comment by clstokes** [comment]
@EvanBoyle I’m going to close this (thanks for the prompt). The hypothesis in this instance was that this was occurring on a corporate workstation that was highly “hardened” and restricted and therefore the performance issues were likely caused by antivirus agents or similar that were causing the issue.
