### ISSUE TITLE
[programgen/go] Discriminated union creation code doesn't compile

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi#7101]
Since https://github.com/pulumi/pulumi/pull/6430 we support discriminated unions. However, Go programgen code instantiating discriminated types fails to compile. Specifically, the code doesn't use the `...Args` input variants for the underlying types. See https://www.pulumi.com/docs/reference/pkg/azure-native/documentdb/databaseaccount/#cosmosdbdatabaseaccountcreatemax for an eample.

## Expected behavior
programgen generates valid code

## Current behavior
```
BackupPolicy: documentdb.PeriodicModeBackupPolicy{
	PeriodicModeProperties: documentdb.PeriodicModeProperties{
		BackupIntervalInMinutes:        240,
		BackupRetentionIntervalInHours: 8,
	},
	Type: "Periodic",
},
```
when in fact it should be:
```
BackupPolicy: &documentdb.PeriodicModeBackupPolicyArgs{
	PeriodicModeProperties: &documentdb.PeriodicModePropertiesArgs{
		BackupIntervalInMinutes:        pulumi.Int(240),
		BackupRetentionIntervalInHours: pulumi.Int(8),
	},
	Type: pulumi.String("Periodic"),
},
```

**Comment by iwahbe** [comment]
@viveklak I'm struggling with coming up with the desired output here. The type [`PeriodicModeProperties`](https://github.com/pulumi/pulumi-azure-native/blob/3267fabfbe318c3fba9ce493ad1e75f77e39297b/sdk/go/azure/documentdb/pulumiTypes.go#L8237-L8242) exists, but I couldn't find `PeriodicModePropertiesArgs`. Are you sure that type should exist? If so, that might be the first bug to address.

**Comment by justinvp** [comment]
This no longer appears to be an issue. The current example from the docs works as expected:

```go
BackupPolicy: &documentdb.ContinuousModeBackupPolicyArgs{
	ContinuousModeProperties: &documentdb.ContinuousModePropertiesArgs{
		Tier: pulumi.String(documentdb.ContinuousTierContinuous30Days),
	},
	Type: pulumi.String("Continuous"),
},
```
