### ISSUE TITLE
nodejs/typescript sdk doesn't process Map type field in resource args

### ISSUE THREAD

**Issue by Dmitry-Danchenko** [pulumi/pulumi#7106]
nodejs/typescript sdk doesn't process Map type field in resource args.

I'm trying to create Kafka topic using typescript SDK:

<code>
import * as kafka from "@pulumi/kafka";

new kafka.Topic("test-topic", {
    name : "test-topic",
    partitions: 4,
    replicationFactor: 1,
    config: new Map<string, any>([["retention.ms", "1200000"]])
  });
 
</code>

## Expected behavior

It should create topic with config: {"retention.ms", "1200000"}

```bash
pulumi up --diff
Previewing update (dev):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::kafka_migrate::pulumi:pulumi:Stack::kafka_migrate-dev]
    + kafka:index/topic:Topic: (create)
        [urn=urn:pulumi:dev::kafka_migrate::kafka:index/topic:Topic::test-topic]
        [provider=urn:pulumi:dev::kafka_migrate::pulumi:providers:kafka::kafka-dmp::c8998bd0-719a-46ef-8c9b-6d983fbadfbd]
        config           : {
            retention.ms: "1200000"
        }
        name             : "test-topic"
        partitions       : 4
        replicationFactor: 1
Resources:
    + 1 to create
    2 unchanged
```

## Current behavior

It creates Topic with an empty config:

```bash
pulumi up --diff
Previewing update (dev):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::kafka_migrate::pulumi:pulumi:Stack::kafka_migrate-dev]
    + kafka:index/topic:Topic: (create)
        [urn=urn:pulumi:dev::kafka_migrate::kafka:index/topic:Topic::test-topic]
        [provider=urn:pulumi:dev::kafka_migrate::pulumi:providers:kafka::kafka-dmp::c8998bd0-719a-46ef-8c9b-6d983fbadfbd]
        config           : {
        }
        name             : "test-topic"
        partitions       : 4
        replicationFactor: 1
Resources:
    + 1 to create
    2 unchanged
```

## Steps to reproduce

https://github.com/Dmitry-Danchenko/pulumi-kafka-bug-example

## Context (Environment)

I can't correctly create/manage Kafka Topics.

## Affected feature

Kafka plugin isn't working properly:
https://www.pulumi.com/docs/intro/cloud-providers/kafka/

**Comment by justinvp** [comment]
@Dmitry-Danchenko, the `Topic` resource's `config` arg isn't typed as a `Map` it's an object:

https://github.com/pulumi/pulumi-kafka/blob/4244bf0f97353d5fbed6a314ec94ceebf93641fc/sdk/nodejs/topic.ts#L145

```typescript
readonly config?: pulumi.Input<{[key: string]: any}>;
```

Does the following work?

```typescript
import * as kafka from "@pulumi/kafka";

new kafka.Topic("test-topic", {
    name : "test-topic",
    partitions: 4,
    replicationFactor: 1,
    config: {"retention.ms": "1200000"},
  });

```

**Comment by Dmitry-Danchenko** [comment]
Yeap! It woks! A lot of thanks!
