### ISSUE TITLE
automation_api failure of second consecutive run

### ISSUE THREAD

**Issue by segevgal87** [pulumi/pulumi#7125]
We're using the `automation_api` on node.js to create resources on AWS and K8s.
We have two classes that perform the textbook Pulumi flow. Each one independently is working fine, but the second is always failing when running them one after the other.

## Current behavior
Running two consecutive `pulumi` programs one after the other is not working properly. Doesn't matter which one is the first, the second one is always failing with a `grpc` related error:
```
Exception has occurred: Error: 14 UNAVAILABLE: No connection established
  at Object.callErrorFromStatus (.../node_modules/@grpc/grpc-js/src/call.ts:81:24)
```
To be clear - two pulumi programs on the same node.js run.

## Steps to reproduce

1. Create two node.js inline programs, as provided in the docs
2. Run them one after the other as follows:
```
datalakeResults = await datalakePulumiCreate.up()
k8sResults = await k8sPulumiCreate.up()
```
where inside each `up()` function there's the flow of stack select etc.

## Context (Environment)
- There are two different stacks for each one.
- There is no paralleling, one is done, and only then the other starts
- Running the same function twice causes the same error
- Inline functions
- The behavior is consistent.
- Pulumi version: 3.3.0

## Affected feature
`area/automation-api`

**Comment by lukehoban** [comment]
This looks like it's the same issue being investigated in https://github.com/pulumi/pulumi/issues/6457.

If you have code for a repro, could you share it on #6457?
