### ISSUE TITLE
warning: Configuration 'newrelic:apiKey' value is a secret; use `getSecret` instead of `get`

### ISSUE THREAD

**Issue by austinbutler** [pulumi/pulumi#7126]
Following the upgrade to Pulumi 3.3.0, I get this warning:

```
warning: Configuration 'newrelic:apiKey' value is a secret; use `getSecret` instead of `get`
```

I never directly refer to `apiKey` config, so I assume it's due to how this resource gets the secret internally. 

## Expected behavior

This resource provider should access via `getSecret` instead of `get` and no warning should be emitted.

## Current behavior

Warning is emitted.

## Steps to reproduce

Just use this resource in Pulumi and run `pulumi up`.

## Context (Environment)

Just using it.

**Comment by justinvp** [comment]
We're going to temporarily disable this new warning in a patch release. #7127 tracks re-enabling the warning without this issue.
