### ISSUE TITLE
Stop pulumi without exception

### ISSUE THREAD

**Issue by mgzenitech** [pulumi/pulumi#7154]
Guys, is there a way to stop pulumi without raising an exception in Python?

I may be completely off but this is where I currently am:
```python
pulumi.dynamic.dynamic.asyncio.current_task().cancel()
```

I've even tried stopping the event loop:
```python
pulumi.dynamic.dynamic.asyncio.get_running_loop().stop()
```

But all of my attempts failed to cleanly stop pulumi from progressing.

**Comment by lukehoban** [comment]
> is there a way to stop pulumi without raising an exception in Python?

In general, you need to allow the process to exit cleanly.  It is not safe to just kill the event loops that Pulumi manages, as the Pulumi Python language host also uses the process lifecycle to manage state of the deployment.

**Comment by mgzenitech** [comment]
@lukehoban so how do I stop it cleanly without triggering the YES/NO/DETAILS interactive input?
