### ISSUE TITLE
Provider gRPC client logging causes failures.

### ISSUE THREAD

**Issue by liamawhite** [pulumi/pulumi#7156]
I'm trying to write my own provider using the boilerplate template but I think there is a breaking bug. From what I can tell the provider is expected to output to stdout the port it is listening on, but what appears to happen is that grpc logging beats it to it.

When I run Pulumi up I get:

```
pulumi:providers:tsb (tsb):
    error: tsb (resource) plugin [/Users/liamwhite/go/bin/pulumi-resource-tsb] wrote a non-numeric port to stdout ('2021-05-27T13:44:04.073942Z	info	[core]parsed scheme: ""'): strconv.Atoi: parsing "2021-05-27T13:44:04.073942Z\tinfo\t[core]parsed scheme: \"\"": invalid syntax
```

I can fix this by manually configuring the grpc logger to either info log to stderr (or discard).

```
// NewHostClient dials the target address, connects over gRPC, and returns a client interface.
func NewHostClient(addr string) (*HostClient, error) {
	grpclog.SetLoggerV2(grpclog.NewLoggerV2(os.Stderr, os.Stderr, os.Stderr)) // <-----------
	conn, err := grpc.Dial(
		addr,
		grpc.WithInsecure(),
		grpc.WithUnaryInterceptor(rpcutil.OpenTracingClientInterceptor()),
		rpcutil.GrpcChannelOptions(),
	)
...
```

The only problem with sending to stderr is that it shows up in diagnostics so it may be preferable to `io.Discard` instead.

**Comment by lukehoban** [comment]
>  From what I can tell the provider is expected to output to stdout the port it is listening on, but what appears to happen is that grpc logging beats it to it.

Yes - a requirement for a Pulumi plugin is that the first output to `stdout` is the port to use to connect to its gRPC server.  That is part of the contract of what it means to be a Pulumi Plugin.  You will need to ensure that you don't log anything to `stdout` ahead of that.

**Comment by liamawhite** [comment]
@lukehoban I wasn't logging anything this just happened importing the standard boilerplate [Main function](https://github.com/pulumi/pulumi/blob/master/pkg/resource/provider/main.go#L36) @3.3.1.

**Comment by lukehoban** [comment]
>  I wasn't logging anything this just happened using the standard boilerplate that imports the Main function @3.3.1.

I just tried out cloning https://github.com/pulumi/pulumi-provider-boilerplate, updating `go.mod` to use `github.com/pulumi/pulumi/pkg/v3 v3.3.1`, building the provider, and then running an example using the provider, and I am not seeing this issue.  Do you have repro steps for what additional changes you are making that might potentially impact this?

**Comment by liamawhite** [comment]
I did some more investigating and after deleting my go mod cache and re-downloading everything it appears to not be an issue. I have no idea what was causing it.

**Comment by liamawhite** [comment]
I noticed this hadn't actually gone away (we just hadn't rebuilt it recently). Having rebuilt without the logging changed I mentioned it still occurs. I have opened up a PR to solve the issue.
