### ISSUE TITLE
StackReference-ed outputs are declared as secrets

### ISSUE THREAD

**Issue by itay** [pulumi/pulumi#7157]
I’m seeing some odd behavior of values being declared a secret even though they shouldn’t be, specifically with stack reference values.

For example, in one stack I have:

```
		bucket, err := s3.NewBucket(ctx, fmt.Sprintf("my-bucket-%s", region), nil)
		if err != nil {
			return err
		}
		ctx.Export("bucket", bucket.ID())
```

And then in another stack:

```
infraStack, err := pulumi.NewStackReference(ctx, "...", nil)
infraBucket := infraStack.GetStringOutput(pulumi.String("bucket"))
auditLogLocation := pulumi.Sprintf("s3://%s/audit-logs", infraBucket)
```

`auditLogLocation` is now a secret (i.e. if I export it, it shows up as a secret), and I have to explicitly do `pulumi.Unsecret(…).(pulumi.StringOutput)` on it.

This happens for any value that comes from the other stack. This is with Pulumi 3.3.0.

## Expected behavior
See above - If I "import" an output from another stack that is not a secret, it should not import as a secret.

## Current behavior
See above.

## Steps to reproduce

See above.

## Context (Environment)

Pulumi 3.3.0 - I can work around this by explicitly doing `pulumi.Unsecret`.

**Comment by lukehoban** [comment]
I ran exactly what's in the repro, but did not see the results of getting a secret value in the consuming stack.  It's also very surprising that that would be possible.  Are you sure your full use case doesn't have some secret value being combined into the results in some way?  Can you share a complete repro?

Definitely happy to re-open if you have additional details!

Stack 1:
```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		region := "ap-southeast-2"
		bucket, err := s3.NewBucket(ctx, fmt.Sprintf("my-bucket-%s", region), nil)
		if err != nil {
			return err
		}
		ctx.Export("bucket", bucket.ID())
		return nil
	})
}
```

```
$ pulumi stack output
Current stack outputs (1):
    OUTPUT  VALUE
    bucket  my-bucket-ap-southeast-2-c5512aa
```

Stack 2:
```go
package main

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		infraStack, err := pulumi.NewStackReference(ctx, "lukehoban/tgosource/dev", nil)
		if err != nil {
			return err
		}
		infraBucket := infraStack.GetStringOutput(pulumi.String("bucket"))
		auditLogLocation := pulumi.Sprintf("s3://%s/audit-logs", infraBucket)
		ctx.Export("auditLogLocation", auditLogLocation)
		return nil
	})
}
```

```
$ pulumi stack output
Current stack outputs (1):
    OUTPUT            VALUE
    auditLogLocation  s3://my-bucket-ap-southeast-2-c5512aa/audit-logs
```

**Comment by itay** [comment]
@lukehoban thanks - I haven't had time to do a clean repro, just what I have in my environment. I am guessing I am doing something wrong, but haven't yet figured out what it is :)
