### ISSUE TITLE
Import leads to fields that cannot be set or are required but missing

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#7160]
We have seen several cases where `pulumi import` leads to either `this field cannot be set` or `Missing required property` errors - for example:
- https://github.com/pulumi/pulumi/issues/6432
- https://github.com/pulumi/pulumi-pagerduty/issues/52
- https://github.com/pulumi/pulumi-azuredevops/issues/56
- https://github.com/pulumi/pulumi-gcp/issues/591
- https://github.com/pulumi/pulumi/issues/7884
- https://github.com/pulumi/pulumi/issues/7978
- https://github.com/pulumi/pulumi/issues/8326
- https://github.com/pulumi/pulumi/issues/8335

This is most likely a deeper issue with `pulumi import` that we will need to address.

**Comment by cperreault** [comment]
Regarding #6432 (I am the author of it under a different professional account), I finally found out that it happened when the environment variable GOOGLE_CREDENTIALS is set. I was containing the private key of a GCP service account. When it is not set, I could do `pulumi refresh` without the App Engine Admin API error!

**Comment by joeduffy** [comment]
@lukehoban @pgavlin Is https://github.com/pulumi/pulumi-aws/issues/1605 and instance of this too?

**Comment by lukehoban** [comment]
> Is pulumi/pulumi-aws#1605 and instance of this too?

Yes - most likely.

**Comment by 0x1991babe** [comment]
One naive fix here allowed me to successfully import my resource: https://github.com/pulumi/pulumi-aws/issues/1605#issuecomment-910833221. Not sure if this is a generalizable / viable approach for other resources, but appears to be sufficient for my use case.

**Comment by 0x1991babe** [comment]
In case anyone needs a temp workaround, here's my hacky patch. No idea if this will work for other resources, but allowed me to successfully import the two I needed:

````patch
diff --git a/pkg/resource/deploy/step.go b/pkg/resource/deploy/step.go
index 927ee3d53..9d9d8eedf 100644
--- a/pkg/resource/deploy/step.go
+++ b/pkg/resource/deploy/step.go
@@ -931,11 +931,11 @@ func (s *ImportStep) Apply(preview bool) (resource.Status, StepCompleteFunc, err
                if !ok {
                        return resource.StatusOK, nil, errors.Errorf("unknown resource type '%v'", s.new.Type)
                }
+
+               props := cleanReadInputs(s.old.Inputs)
                for _, p := range r.InputProperties {
-                       if p.IsRequired() {
-                               k := resource.PropertyKey(p.Name)
-                               s.new.Inputs[k] = s.old.Inputs[k]
-                       }
+                       k := resource.PropertyKey(p.Name)
+                       s.new.Inputs[k] = props[k]
                }
        } else {
                // Set inputs back to their old values (if any) for any "ignored" properties
@@ -1170,3 +1170,28 @@ func getProvider(s Step) (plugin.Provider, error) {
        }
        return provider, nil
 }
+
+func cleanReadInputs(properties resource.PropertyMap) resource.PropertyMap {
+       cleaned := make(resource.PropertyMap)
+       skips := make(map[string]interface{})
+       skips["vpcId"] = nil
+
+       for k, v := range properties {
+               if _, ok := skips[string(k)]; ok {
+                       if ok {
+                               continue
+                       }
+               }
+
+               if !v.IsEmpty() {
+                       cleaned[k] = v
+                       continue
+               }
+
+               if v.IsObject() {
+                       cleaned[k] = resource.NewObjectProperty(cleanReadInputs(v.ObjectValue()))
+               }
+       }
+
+       return cleaned
+}
diff --git a/sdk/go/common/resource/properties.go b/sdk/go/common/resource/properties.go
index 337870f6b..3e068b96c 100644
--- a/sdk/go/common/resource/properties.go
+++ b/sdk/go/common/resource/properties.go
@@ -541,6 +541,17 @@ func (v PropertyValue) TypeString() string {
        return ""
 }

+func (v PropertyValue) IsEmpty() bool {
+       if v.IsNull() {
+               return true
+       } else if v.IsString() {
+               return v.V == ""
+       } else if v.IsArray() {
+               return len(v.V.([]PropertyValue)) == 0
+       }
+       return false
+}
+
 // Mappable returns a mapper-compatible value, suitable for deserialization into structures.
 func (v PropertyValue) Mappable() interface{} {
        return v.MapRepl(nil, nil)
```
Basically, we strip empty values from the inputs, and use a hard coded list of properties to skip to avoid computed properties. It seems like the computed properties should be available since they're clearly marked on the tf provider, but good enough for me for now!

**Comment by ffMathy** [comment]
What is the status on these? Experiencing this with AWS EC2 Key Pair import.

**Comment by joeduffy** [comment]
Thanks so much for the insights and patch, @tychedelia. I'll circulate internally and see if we can bump this.

**Comment by shibumi** [comment]
Hi,
I am encountering the same issue with hetzner server resources:

error: hcloud:index/server:Server resource 'myserver' has a problem: Missing required argument: The argument "image" is required, but no definition was found.. Examine values at 'Server.Image'.

Would be nice if pulumi could provide a command line flag to just set these values to nil.

**Comment by adrianord** [comment]
Having a similar issue with trying to import virtual machines using the vSphere providers
```
error: Preview failed: diffing urn:pulumi:infra::pulumi-vsphere::vsphere:index/virtualMachine:VirtualMachine::inflipam01: network_interface parameter is required when not deploying from ovf template
```

**Comment by hjorth** [comment]
Any progress on this? I am experiencing this when importing a gcp cloud sql instance - that was actually created using pulumi, but maybe never made it to the state..

**Comment by jasminen** [comment]
Another reported import issue - importing AWS EC2 instances fails:
https://github.com/pulumi/pulumi-aws/issues/1605

Is there any plan to resolve this?
This makes pulumi adoption to existing organizations nearly impossible.

**Comment by Frassle** [comment]
> Is there any plan to resolve this?

Yes! We have two changes in the works right now to improve this.

Firstly we're seeing if we can improve the results of `Read` calls from our bridged terraform providers (https://github.com/pulumi/pulumi-terraform-bridge/pull/453). Currently terraform returns a lot of missing properties as zero values instead of missing and we need to work around that for clean imports.

Secondly we're changing the way `pulumi import` works (https://github.com/pulumi/pulumi/pull/8922) so that it will nearly always result in being able to codegen _something_ which you can then pull into your pulumi program.

We'll continue to try out importing various resources and taking community comments after these have landed to keep improving the import experience, but we expect the above two changes to have significant impact on making imports better.

**Comment by marcindulak** [comment]
I'm not sure if my case is the same issue, but https://github.com/pulumi/pulumi/pull/8846 seems to provide a workaround

```
pulumi version
# v3.24.1

pulumi plugin install resource azure 4.39.0
pulumi plugin ls
# NAME          KIND      VERSION  SIZE    INSTALLED  LAST USED
# azure         resource  4.39.0   274 MB  n/a        12 minutes ago
# azure-native  resource  1.56.0   44 MB   n/a        14 minutes ago
```

```
pulumi import azure:core/resourceGroup:ResourceGroup klkl-187172 /subscriptions/xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/klkl-187172
...
Diagnostics:
  azure:core:ResourceGroup (klkl-187172):
    error: azure:core/resourceGroup:ResourceGroup resource 'klkl--187172' has a problem: Missing required argument: The argument "location" is required, but no definition was found.. Examine values at 'ResourceGroup.Location'.
    error: Preview failed: one or more inputs failed to validate

Import failed, try specifying the set of properties to import with.
This can be done by passing the property names with the --properties flag.
```

However, appending `--properties location` results in a successful import. The caveat is that the resource is managed by the classic https://github.com/pulumi/pulumi-azure and not native provider https://github.com/pulumi/pulumi-azure-native.

**Comment by ahummel25** [comment]
@marcindulak Having the same issue. the `--properties location` worked great, but like you said, the resource is managed by the classic `pulumi azure` and not native. Did you find any solution for this?

**Comment by lukehoban** [comment]
> like you said, the resource is managed by the classic pulumi azure and not native

If you import into the type `azure:core/resourceGroup:ResourceGroup`, that will use the `azure` provider, which is the Azure Classic provider.  You can use `azure-native:resources:ResourceGroup` to import into the `azure-native` provider.
