### ISSUE TITLE
Magic Functions do not work without package.json in the same folder

### ISSUE THREAD

**Issue by rtkelly13** [pulumi/pulumi#7168]
I have a monorepo with multiple pulumi projects under several levels of folders so for example.

- /lambda/cron-job-1
- /lambda/cron-job-2
- /packages.json

When creating a project similar to 
https://www.pulumi.com/blog/scheduling-serverless/
in the ` /lambda/cron-job-1` folder that has a Magic Lambda function. The code is slightly different because I've tweaked it so I could pass the role explicitly to the lambda but is effectively the same.

## Expected behavior
pulumi preview works as expected and deploys lambda as expected which happens when a valid package.json is co-located

## Current behavior
When I run pulumi preview I get this error. I've removed the specific parts of the stack trace to my app. But can provide the whole thing if necessary. From what I can see  
```
Error: Error reading file  'C:/lambda/cron-job-1/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open 'C:/lambda/cron-job-1/package.json'

unhandled rejection: CONTEXT(876): resource:stack-name[aws:lambda/function:Function]
    STACK_TRACE:
    Error
```

Here is a full stack trace from the reproduction above
```
     Type                                          Name                 Plan       Info
     pulumi:pulumi:Stack                           pulumi-test-dev                 1 error
 +   └─ aws:cloudwatch:EventRuleEventSubscription  emptyTrash           create
 +      ├─ aws:cloudwatch:EventRule                emptyTrash           create
 +      ├─ aws:iam:Role                            emptyTrash           create
 +      ├─ aws:iam:RolePolicyAttachment            emptyTrash-b5aeb6b6  create
 +      ├─ aws:iam:RolePolicyAttachment            emptyTrash-4aaabb8e  create
 +      ├─ aws:iam:RolePolicyAttachment            emptyTrash-e1a3786d  create
 +      ├─ aws:iam:RolePolicyAttachment            emptyTrash-74d12784  create
 +      ├─ aws:iam:RolePolicyAttachment            emptyTrash-a1de8170  create
 +      ├─ aws:iam:RolePolicyAttachment            emptyTrash-019020e7  create
 +      ├─ aws:iam:RolePolicyAttachment            emptyTrash-7cd09230  create
 +      ├─ aws:iam:RolePolicyAttachment            emptyTrash-6c156834  create
 +      └─ aws:iam:RolePolicyAttachment            emptyTrash-1b4caae3  create

Diagnostics:
  pulumi:pulumi:Stack (pulumi-test-dev):
    error: Error: Error reading file 'C:/git/pulumi-test/project/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open 'C:/git/pulumi-test/project/package.json'
        at readFile (C:\git\pulumi-test\node_modules\@pulumi\pulumi\runtime\closure\codePaths.js:167:19)
        at computeDependenciesDirectlyFromPackageFile (C:\git\pulumi-test\node_modules\@pulumi\pulumi\runtime\closure\codePaths.js:150:22)
        at C:\git\pulumi-test\node_modules\@pulumi\pulumi\runtime\closure\codePaths.js:115:36
        at C:\git\pulumi-test\node_modules\read-package-tree\rpt.js:162:20

```

## Steps to reproduce

1. create a new pulumi project
2. create a subfolder called project and copy the following files (index.ts, pulumi.yml, pulumi.dev.yml, tsconfig.json)
3. copy over the sample code from the blog post here https://www.pulumi.com/blog/scheduling-serverless/
4. try to run pulumi up and receive the above error. (If you remove the lambda code and just create the bucket this works successfully)

## Context (Environment)
I have to include a local package.json file inside the subfolder whereas I would prefer it to be in the root folder. I think this issue has come up before I started using pulumi around how pulumi resolves the packages originally. But hasn't been thought about in the context of this? I've had a look through and can't seem to find the exact issue that fixed this originally

**Comment by lukehoban** [comment]
Yes - this is a scenario that would be great to add support for.  That will likely be something we need to enable in the core closure serialization logic in https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/runtime/closure/codePaths.ts.

**Comment by dpmccabe** [comment]
I've gotten this to work just by symlinking `package.json` and `node_modules` from wherever I'm running the pulumi command to their locations up the directory tree.

**Comment by RobbieMcKinstry** [comment]
I expect we'll be able to resolve this issue when https://github.com/pulumi/pulumi/pull/12759 lands.
