### ISSUE TITLE
How can I cast an Output<string> to a string?

### ISSUE THREAD

**Issue by jamesla** [pulumi/pulumi#7179]
When attempting the following example:

```ts
const privateKey = new pulumi.tls.PrivateKey(cfg.requireSecret('mySecret').apply((key) => key), { algorithm: 'RSA' }
```

and get the following compiler error `Argument of type 'Output<string>' is not assignable to parameter of type 'string'`

What I have tried:

1.  lifting as per docs (same error)
```ts
const privateKey = new pulumi.tls.PrivateKey(cfg.requireSecret('mySecret'), { algorithm: 'RSA' }
```

2. Wrapping in callback (works but not useful as privateKey variable gets descoped)
```ts
cfg.requireSecret('mySecret').apply((key) => {
  const privateKey = new pulumi.tls.PrivateKey(key, { algorithm: 'RSA' }
});
```

3. Using the getter (unable to run pulumi up)
```ts
const privateKey = new pulumi.tls.PrivateKey(cfg.requireSecret('mySecret').get(), { algorithm: 'RSA' }
```

**Comment by jaxxstorm** [comment]
Hey @jamesla - it looks to me like you're trying to use an `Output<string>` as a resource name - that's not actually possible.

The resource name _must_ be known at runtime, it can't be resolved asynchronously, otherwise, the resource can't be registered in the engine.

Can you explain a little bit more about what you're trying to do?

**Comment by jaxxstorm** [comment]
Got this resolved in community slack,

**Comment by jamesla** [comment]
> Hey @jamesla - it looks to me like you're trying to use an `Output<string>` as a resource name - that's not actually possible.
> 
> The resource name _must_ be known at runtime, it can't be resolved asynchronously, otherwise, the resource can't be registered in the engine.
> 
> Can you explain a little bit more about what you're trying to do?

Yes sorry I didn't read the docs properly and was trying to instantiate a `PrivateKey` with a real private key that I had generated with openssl when all of that was handled for me. My bad and thanks for the help @jaxxstorm !
