### ISSUE TITLE
nodejs multi-language components are 200+MB

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#7182]
Each nodejs component has it's own `node_modules` with some heavy dependencies such as`@pulumi/pulumi` and `grpc`. This leads to 200+MB plugins at a minimum. Install a dozen components on your system and you are at multiple GB in the plugin cache. Add to this fact that we may want to include a node runtime embedded in the plugin at some point and this starts getting out of hand.

We should investigate ways to slim this down. Some options that may be worth considering:

1. Manual audit of dependencies
2. Creating single js file distributions (no node_modules) via something like ncc https://github.com/vercel/ncc
3. provide a pre-installed pseudo-plugin "pulumi-plugin runner" that has a node runtime, common large dependencies (pulumi, grpc, provider SDKs maybe?). that could be referenced from real plugins via package.json `pulumi-plugin-runner: "../pulumi-plugin-runner`. Our plugin installation process could manage this dependency and even have multiple versions installed (one per pulumi runtime version?).

**Comment by EvanBoyle** [comment]
Just tried a very basic `ncc` invocation:

```console
ncc build index.ts -o single
```

and the result is a 22MB javascript file. 90% reduction!

**Comment by EvanBoyle** [comment]
@joeduffy suggested a common node modules solution with the following layout:

```
a/
    package.json
b/
    package.json
c/
    package.json
node_modules/
```

Then running `npm i a/ b/ c/` from the root.

**Comment by EvanBoyle** [comment]
Got an `ncc` based plugin working on one of my projects, but it required some changes to pulumi/pulumi to exclude the typescript dependency. 

- old size: `230 MB`
- new size: `16 MB`

`ncc` does not seem to be advanced enough to exclude certain submodules from being compiled (`@pulumi/pulumi/runtime/closure' for instance), so I had to make a local build of pulumi with all of that deleted. We could probably use a fancier webpack configuration to achieve the same thing, but I think it would be nice to keep our users (and ourselves) out of the business of webpack if possible so I opened https://github.com/pulumi/pulumi/issues/7184

**Comment by EvanBoyle** [comment]
https://github.com/pulumi/pulumi/pull/7188 makes them 150MB

**Comment by komalali** [comment]
So I spent a very long time fighting with [pkg](https://www.npmjs.com/package/pkg) and just wasn’t getting anywhere (we do things in pulumi/pulumi that pkg isn't straightforwardly compatible with) so eventually abandoned it and decided to try [nexe](https://www.npmjs.com/package/nexe) instead.  And it worked pretty much right out of the box, but not quite the space savings we were seeing with pkg.

Still, using a combination of [ncc](https://github.com/vercel/ncc) and nexe, I was able to create a single-file binary for `astro-containerapp` clocking in at 116MB. This includes the nodejs dependency itself, as well as typescript.

Compare that to the 297MB and bajillions of files that this provider was at the start of the day, and that’s a **61%** size decrease with the bonus that we’ve removed all external dependencies.

**Comment by EvanBoyle** [comment]
Going to close this out with a workaround listed at the end. https://github.com/pulumi/pulumi/issues/7184 tracks removing the runtime typescript dependency from pulumi/pulumi. In the meantime as long as you aren't using closure serialization (magic functions, dynamic providers) you should be able to do the following:

1. Use `ncc` to build a single JS file that includes all dependencies, manually excluding typescript: `ncc build index.ts -o single -e typescript`
2. Replace `require("typescript")` with `{}` as described here https://github.com/vercel/ncc/issues/642#issuecomment-771401679

That gets a basic component down to ~20MB of javascript. The boilerplate repo that bundles nodejs and includes typescript will be ~115MB as @komalali describes above.
