### ISSUE TITLE
Pulumi 3 fails compilation on NodeJS/TS project

### ISSUE THREAD

**Issue by pluppens** [pulumi/pulumi#7191]
Apologies for the non-descriptive title - I'm not familiar enough with the internals to understand exactly where it goes wrong.

I have installed:
- pulumi v3.3.1
- NPM 6.14.10
- NodeJS v12.20.1

Running Linux 5.9.16-1-MANJARO.

My `package.json` file (and updated `package-lock.json`):
```
{
    "name": "<snip>",
    "devDependencies": {
        "@types/node": "^12.20.14"
    },
    "dependencies": {
        "@aws-sdk/types": "^3.15.0",
        "@hubspot/api-client": "^3.4.1",
        "@pulumi/aws": "^4.6.0",
        "@pulumi/awsx": "^0.30.0",
        "@pulumi/cloud": "^0.30.1",
        "@pulumi/cloud-aws": "^0.30.1",
        "@pulumi/pulumi": "^3.3.1"
    }
}
```
This is a continuation of some TS projects that were started on Pulumi V2, but to my knowledge, the migration was done following the upgrade guide, so I'm presuming this is correct. I couldn't easily switch back to V2 to see if this is a breaking change, but since I didn't see anything reported yet, I'm going to assume it's purely on my side (perhaps an outdated dependency on NodeJS?).

```
pulumi:pulumi:Stack (<snip>):
    error: SyntaxError: eval at <anonymous> (<project-path>/node_modules/@pulumi/pulumi/runtime/closure/v8_v10andLower.js:82:27):1:7 Expected an operand but found %
    return %FunctionGetScriptSourcePosition(func);
           ^
        at new Function (native)
        at Object.<anonymous> (<project-path>/node_modules/@pulumi/pulumi/runtime/closure/v8_v10andLower.js:82:27)
        at Module._compile (internal/modules/cjs/loader.js:999:30)
        at Object..js (internal/modules/cjs/loader.js:1027:10)
        at Module.load (internal/modules/cjs/loader.js:863:32)
        at Function.Module._load (internal/modules/cjs/loader.js:708:14)
        at Module.require (internal/modules/cjs/loader.js:887:19)
        at require (internal/modules/cjs/helpers.js:74:18)
        at Object.<anonymous> (<project-path>/node_modules/@pulumi/pulumi/runtime/closure/v8.js:26:24)
        at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**Comment by stack72** [comment]
Hi @pluppens 

Please can you give us a sample of code (minus any confidential information / secrets etc) so that we can try and recreate this

thanks

Paul

**Comment by pluppens** [comment]
I would, but the matter seems more complex than that - even fully clearing my `index.ts` file (meaning entirely blank) causes the issue when I type `pulumi up`. Perhaps something is cached, but this doesn't seem to be related to the actual project code?

**Comment by pluppens** [comment]
Ok, I'm not entirely sure what caused the issue - likely a very outdated dependency, listed above. The problem was that the `node`, `npx` and `npm` programs were symlinked by SDKMAN's Java installation, which for some reason has these programs in the `/bin` folder. I'm honestly not sure how they got there - but correcting the path results in the following:
- NPM 7.12.1
- NodeJS v16.1.0

After that, the evaluation passes fine. Apologies for wasting everyone's time with this. I had a suspicion, but due to the lack of visibility into the evaluation process it was hard to figure out where the problem originated.

**Comment by stack72** [comment]
Hey @pluppens nothing to apologise for at all! Glad it's working better for you now

Paul
