### ISSUE TITLE
Can't run `pulumi preview` from docker container

### ISSUE THREAD

**Issue by paymog** [pulumi/pulumi#7237]
When running `pulumi preview` in a docker container the command hangs for a while and then eventually errors out with `go build github.com/pulumi/pulumi-gcp/sdk/v5/go/gcp/compute: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed`

## Steps to reproduce
[Here's a link](https://app.pulumi.com/gadic/server/prod/previews/e6f467d3-cc5d-45d8-9cf0-490cfcae4cd6) to a `pulumi preview`. Unfortunately I haven't figured out a minimal reproduction.

Here's the pulumi version and the plugin versions:
```
root@246593fd6370:~# pulumi version
v3.4.0
root@246593fd6370:~# pulumi plugin ls
NAME        KIND      VERSION  SIZE    INSTALLED  LAST USED
gcp         resource  5.2.0    104 MB  n/a        38 minutes ago
kubernetes  resource  3.1.1    78 MB   n/a        38 minutes ago

TOTAL plugin cache size: 182 MB
```

Expected: I expect `pulumi preview` to successfully execute
Actual: `pulumi preview` hangs then fails

**Comment by paymog** [comment]
Let me try increasing the number of cores available to the docker vm on my macbook

**Comment by paymog** [comment]
Looks like increasing the resources available to the VM fixed it! Now I'm getting errors about not being able to authenticate with GCP which should be much easier to fix.

**Comment by paymog** [comment]
Though, is there a way to ask pulumi not to kill the compilation process early? I'd like to avoid giving docker all of the CPUs on my mackbook.

**Comment by lukehoban** [comment]
Thanks for the details. 

It does look like this is the `go build` causing resource exhaustion. You can do the Go build yourself, and then have Pulumi run an existing binary.  

What CPU and memory were you running with, and what build time did you see in that environment?

Also - what size is your compiled Go binary?

**Comment by paymog** [comment]
Good idea, I'll try running `go build` on the `main.go` for my infra before running pulumi.

I was running with 3 CPU and 2 gigs of memory. The signal kill happened after ~5 minutes (using intuition, I didn't time it). 

```
root@90d14ee59004:/gadic# time PULUMI_ACCESS_TOKEN=<token> pulumi preview
Logging in using access token from PULUMI_ACCESS_TOKEN
Please choose a stack, or create a new one: prod
Previewing update (prod)

View Live: https://app.pulumi.com/gadic/server/prod/previews/0432346f-4158-48f0-b5fc-e3adb2435976

[resource plugin kubernetes-3.1.1] installing
Downloading plugin: 977.10 KiB / 29.02 MiB [>----------------------]   3.29% 23s[resource plugin gcp-5.2.0] installing
Downloading plugin: 29.02 MiB / 29.02 MiB [========================] 100.00% 17s
Downloading plugin: 35.10 MiB / 35.10 MiB [========================] 100.00% 23s
     Type                           Name             Plan     Info
     pulumi:pulumi:Stack            server-prod
     └─ gcp:serviceAccount:Account  worker-cloudsql           1 error

Diagnostics:
  gcp:serviceAccount:Account (worker-cloudsql):
    error: 1 error occurred:
        * Attempted to load application default credentials since neither `credentials` nor `access_token` was set in the provider block.  No credentials loaded. To use your gcloud credentials, run 'gcloud auth application-default login'.  Original error: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.



real    3m47.962s
user    6m13.597s
sys     2m16.364s
```

How do I find the size of the compiled binary? I looked in both `$GOPATH/bin` and `WORKDIR` in the dockerfile after running the above command and didn't find a binary.

Interestingly, it _feels_ like the compilation process went much faster today than it did yesterday. Not sure why, maybe I had other processes running yesterday which ate up resources in the docker vm.

**Comment by EvanBoyle** [comment]
@paymog pulumi uses `go run main.go` style invocation by default when you run preview or up, go run does the compilation but does not produce a binary on disk. I think Luke was suggesting that you `go build` a binary and copy that into your container definition. See the `runtime.options.binary` configuration option for `Pulumi.yaml`: https://www.pulumi.com/docs/reference/pulumi-yaml/

I'm going to go ahead close this issue out as it seems that you are unblocked.
