### ISSUE TITLE
Include custom server URLs for plugins in stack state

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#7242]
When determining required plugins for an existing stack, we look at providers in the stack's state.

https://github.com/pulumi/pulumi/blob/f0bfc94ef35b2d1b961e65bbbba21495a7be6619/pkg/engine/plugins.go#L97-L127

However, we currently have no way to tell whether such providers are from a plugin from a custom server URL, so we attempt to download all these plugins from the Pulumi URL.

We'll need to include the custom URL in the state to address this. One way of doing that is making it an optional input and a (required?) output, then plumb it through the plugin loader. So if a server is specified in the inputs, we would pass that to the loader. And the loader would always return the server it used to download the plugin. With this approach, we'd have to stamp the URL in the generated SDKs.

One challenge: If it's stamped as an input to a provider, this wouldn't handle the common case of default providers, since they aren't instantiated by the SDK. Which means, we may need to embed the custom server URL in every resource request like we do for the version.

**Comment by justinvp** [comment]
While the description above describes the "correct" implementation, a simpler approach in the meantime would be to use a heuristic: When combining the plugins from `gatherPluginsFromProgram` and `gatherPluginsFromSnapshot`, if a plugin name from the snapshot is present in the set of plugins from the program, and the plugin from the program has a custom server URL, we could just use the same custom server URL for the plugin determined from the snapshot. This would likely work the majority of the time, unless the version from the snapshot was hosted elsewhere.

**Comment by iwahbe** [comment]
I'm concerned the heuristic solution won't work for `pulumi destroy`. Because destroy doesn't run the program, it doesn't call `gatherPluginsFromProgram`. You could manually destroy (by removing all resources from your program and running `pulumi up`) and I think it would still work.
