### ISSUE TITLE
Provide a credential-free way of using pulumi with Azure Blob storage as a custom pulumi backend

### ISSUE THREAD

**Issue by Rookian** [pulumi/pulumi#7251]
Right now, we have the following options to authenticate against Azure Blob Storage, when using it as a custom pulumi backend:
- `AZURE_STORAGE_KEY `
- `AZURE_STORAGE_SAS_TOKEN`

Both are credentials that need to be stored/handled securely. 
You can implement this securely by adding Azure Key Vault and store the secret in it. 
Another option is to retrieve one of the secrets by using e.g. Azure CLI/Azure SDK and don't even store it in AKV.

In my opinion all this could be much easier. 
You could provide Azure Cli authentication for BlobStorage (`AZURE_STORAGE_AUTH_VIA_CLI`)
You already provide a similar option for AKV to use AzureCli as an authentication method (`AZURE_KEYVAULT_AUTH_VIA_CLI`).

Pros:
- Consistent way of using a secret provider (AKV) and custom pulumi backend (Azure Storage)
- Easy comprehensible and less code which is more beginner friendly
- Providing out of the box best practices when it comes to authentication against Azure Services
- Better developer experience by just using Pulumi and your language of choice instead of adding addtional tools/libraries inside or outside of pulumi like Azure SDK or Azure Cli. Azure Cli imo should only be used once for authentication. So imo you create a by far better developer experience when you try to avoid media breaks (using different tools/platforms than pulumi). You already went into the right direction with "pulumi automation".

I hope that make sense and does help.

**Comment by infin8x** [comment]
Thanks for this suggestion! We use `google/gocloud` to interface with Azure Blob Storage (among others) and would need to either add or have support added for BlobStorage auth via AzureCli, similar to this issue (https://github.com/google/go-cloud/issues/2462) that added KeyVault support via AzureCli.  We've filed https://github.com/google/go-cloud/issues/3012 to track that request.

**Comment by ekini** [comment]
I created [a PR](https://github.com/google/go-cloud/pull/3072) to add the functionality as above but it's not going to be accepted. The maintainers positions is to implement it is to DIY with URLOpeners in the actual software. Should I move the code from the above mentioned PR to Pulumi?
Does it make sense?

Just want to add that `AZURE_STORAGE_AUTH_VIA_CLI` solely isn't really useful as it will take the default Azure subscription. With `subscription_id` query parameter it's possible to set the subscription id.  (yes, of course it's possible to set that subscription id with an env var but if we go this way the current `AZURE_STORAGE_KEY` approach already works).

**Comment by Rookian** [comment]
@infin8x and @ekini any news from your site?

**Comment by lukehoban** [comment]
This was just fixed in go-cloud, so we may now be able to pull that fix in. 

https://github.com/google/go-cloud/issues/3012#issuecomment-1211289743

**Comment by ekini** [comment]
There's even more in it - go-cloud now also supports setting storage account in the URL to fully define the backend in it, not requiring any env vars. Just need to wait for the next release.
