### ISSUE TITLE
Should `pulumi config refresh` bring down `secretsprovider` from config?

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#7282]
Today `pulumi config refresh` gets the last deployed config from the backend and stores it locally.  This doesn't however bring down the `secretsprovider` section of the config file, which specificies how data in the config is encrypted.  That information is available in the deployed state file, and we could/should return that back to the client to to store into the local config.

**Comment by jancespivo** [comment]
Hi, in my opinion it should return `secretsprovider` back (also with `encryptedkey`).
After `pulumi config refresh` I expect `pulumi config --show-secrets` works. But now I get an error: `error: could not decrypt configuration value: cipher: message authentication failed`.

**Comment by mattfysh** [comment]
This would be very handy, currently using the automation API in local mode for a test environment and need to use this workaround:

```ts
const { deployment } = await stack.exportStack()
const encryptionSalt = deployment.secrets_providers.state.salt
await stack.workspace.saveStackSettings(name, { encryptionSalt })
```
