### ISSUE TITLE
`pulumi up` fails when run in kubernetes cluster

### ISSUE THREAD

**Issue by paymog** [pulumi/pulumi#7283]
I have a pulumi stack which manages a GCP project. I can successfully run `pulumi up` for this stack from my laptop. I'm now trying to add some automation to run `pulumi up` from a docker image running as a pod in a kubernetes cluster (which is itself managed by the stack). However, when I attempt to update the stack from a pod running in the kubernetes cluster I get the following error: `configured Kubernetes cluster is unreachable: unable to load schema information from the API server: the server has asked for the client to provide credentials`. I've added a `gcp:credentials` config to my stack. Without this config I've found the even `pulumi preview` fails authentication. My expectation (which might be naive) is that `gcp:credentials` should be enough to pass all authentication required assuming that the kubernetes cluster lives within the GCP project which generated those credentials.

Why is `pulumi up` failing when it's running from within the kubernetes cluster it's trying to update? Similarly, why does `pulumi preview` succeed in the exact same environment?

## Steps to reproduce
I don't have a minimal reproduction but here's a link to an execution of `pulumi up` which failed: https://app.pulumi.com/gadic/server/prod/updates/158

Expected: I expect `pulumi up` to work when `gcp:credentials` is provided in the stack config 
Actual: `pulumi up` fails when run from within a pod running in a k8s cluster, even though `gcp:credentials` is provided as a config in the stack

**Comment by roderik** [comment]
If you set the GOOGLE_CREDENTIALS env var on the pod it works for us

**Comment by paymog** [comment]
I had to do the following

```
$ pulumi config get gcp:credentials > /auth.txt
$ gcloud auth activate-service-account --key-file /auth.txt
$ pulumi up --skip-preview
```

Setting GOOGLE_CREDENTIALS didn't help unfortunately though it's confusing that I had to go through this extra auth flow.

**Comment by leezen** [comment]
@paymog It'd be great if you're able to provide more repro/debug details as I would expect what you've described to work. 

`configured Kubernetes cluster is unreachable: unable to load schema information from the API server: the server has asked for the client to provide credentials` suggests that the part that's failing isn't necessarily talking to Google but to your Kubernetes cluster instead?

**Comment by paymog** [comment]
Sure @leezen! What details would you like? I'll try to provide a high level outline below, happy to add more as you see fit.

1. create pulumi stack which creates a kubernetes cluster in GCP
2. add `gcp:credentials` to said pulumi stack
3. in the stack, define a kubernetes deployment called `worker`
4.  ensure that the `worker` image has `pulumi` as a binary and all relevant code from the github repo (source code, pulumi infra code, etc)
4. add an endpoint to this worker object which, when called creates a kubernetes pod with the same image as the `worker` pods
5. bring up the stack
6. call the above endpoint on the worker
5. in this newly created k8s pod, run `pulumi preview` and see that it works (it seems to use `gcp:credentials`)
6. next run `pulumi up --skip-preview` and see the error mentioned in the original post

**Comment by leezen** [comment]
@paymog The error mentioned in the original post appears to be related to talking to the Kubernetes cluster and not to GCP from what I can tell. Does the Pulumi program you're trying to execute use the kubernetes provider in some way and is it configured?

**Comment by paymog** [comment]
Ah yes I am, I'm submitting `pulumi.Provider(input.k8sProvider)`, where `input.k8sProvider` is of type `*provider.Providers`, to all the calls which create a new kubernetes resources. Here's an example `appsv1.NewDeployment(ctx, "name", &appsv1.DeploymentArgs{}, pulumi.Provider(input.k8sProvider))` - is that the source of the troubles?

**Comment by leezen** [comment]
Do you mind providing the code for where `input.k8sProvider` comes from? Or, ideally, as much of your source program that you're able to share.

**Comment by leezen** [comment]
I don't see the source for `generateKubeconfig`, but given the error above we've been discussing, have you validated that the generated kubeconfig works?

**Comment by paymog** [comment]
Here's the source for `generateKubeconfig`:

```
func generateKubeconfig(clusterEndpoint pulumi.StringOutput, clusterName pulumi.StringOutput,
	clusterMasterAuth container.ClusterMasterAuthOutput) pulumi.StringOutput {
	context := pulumi.Sprintf("demo_%s", clusterName)

	return pulumi.Sprintf(`apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: %s
    server: https://%s
  name: %s
contexts:
- context:
    cluster: %s
    user: %s
  name: %s
current-context: %s
kind: Config
preferences: {}
users:
- name: %s
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp`,
		clusterMasterAuth.ClusterCaCertificate().Elem(),
		clusterEndpoint, context, context, context, context, context, context)
}
```

I haven't specifically validated that it works - I assumed it's valid since `pulumi up` works on my laptop. 

This code was taken from one of the examples: https://github.com/pulumi/examples/blob/master/gcp-go-gke/main.go

**Comment by leezen** [comment]
I think that's probably worth validating then on the environment where this isn't working, especially since you're saying this works on your laptop. For example, does the pod this runs from have the `gcloud` binary?

**Comment by paymog** [comment]
Yup, the pod this runs from has the `gcloud` binary. I'll give that kubeconfig validation a shot tomorrow.

**Comment by lblackstone** [comment]
This looks to me like a configuration issue, and since the issue hasn't been updated in a long time, I'll close this out now. Please open a new issue if you're still having problems.
