### ISSUE TITLE
Provider for Snowflake

### ISSUE THREAD

**Issue by LouisAmon** [pulumi/pulumi#7302]
Would be epic to have a native provider for Snowflake

Here's the SDK in Go:
https://github.com/snowflakedb/gosnowflake

Most of the resources in Snowflake are managed via SQL code which is executed via the SDK.

There are a lot of bridges between Snowflake, AWS, Google Cloud & Azure so a native provider would help a lot in a multi-cloud setup !

**Comment by stack72** [comment]
Hi @LouisAmon 

We are working on something in this area! Stay tuned :D

**Comment by LouisAmon** [comment]
https://www.pulumi.com/docs/reference/pkg/snowflake/

Well done guys !
