### ISSUE TITLE
Incorrect type annotation in Python dynamic provider leads to hang

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#7313]
Deploying https://github.com/pulumi/examples/blob/master/aws-py-ec2-provisioners/ leads to a hang.

Verbose logging shows that the following errors are reported before the hang:

```
  File "/Users/lukehoban/go/src/github.com/pulumi/examples/aws-py-ec2-provisioners/venv/lib/python3.9/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
    result = await rpc
  File "/Users/lukehoban/go/src/github.com/pulumi/examples/aws-py-ec2-provisioners/venv/lib/python3.9/site-packages/pulumi/runtime/resource.py", line 542, in do_register
    rpc.resolve_outputs(res, resolver.serialized_props, resp.object, deps, resolvers, transform_using_type_metadata)
  File "/Users/lukehoban/go/src/github.com/pulumi/examples/aws-py-ec2-provisioners/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 697, in resolve_outputs
    translated_value = translate_output_properties(value, translate_to_pass, types.get(key),
  File "/Users/lukehoban/go/src/github.com/pulumi/examples/aws-py-ec2-provisioners/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 643, in translate_output_properties
    element_type = _get_list_element_type(typ)
  File "/Users/lukehoban/go/src/github.com/pulumi/examples/aws-py-ec2-provisioners/venv/lib/python3.9/site-packages/pulumi/runtime/rpc.py", line 79, in _get_list_element_type
    raise AssertionError(f"Unexpected type. Expected 'list' got '{typ}'")
AssertionError: Unexpected type. Expected 'list' got '<class 'list'>'
```

These errors are triggered by the following line - in particular the fact that it is `pulumi.Output[list]` instead of `pulumi.Output[List[Dict[str, str]]]`.  Changing to the latter fixes this, but that should not be necessary - "incorrect" type annotations should not lead to a failure and certainly not to a hang.

https://github.com/pulumi/examples/blob/master/aws-py-ec2-provisioners/provisioners.py#L160:L160

This also appears to be a regression, as this same program worked when originally added.

Finally - this program does not appear to be being run in the `examples` test suite.  The morally equivalent TypeScript example is being run, so we should have all the required machinery there to put this under test.

**Comment by justinvp** [comment]
With https://github.com/pulumi/pulumi/pull/7049 I suspect this would no longer result in a hang, but will likely still error, which still needs to be fixed.

**Comment by t0yv0** [comment]
I'm doing little obvious things:

0. reproduced the issue, which is now an Exception (not hang), but an obscure stack trace
1. https://github.com/pulumi/pulumi/pull/7681 makes the example work
2. [ ] TODO I will add a PR to examples to make it run in the tests

Now, I'm not sure that this statement is not obviously true in general for our codebase:

> "incorrect" type annotations should not lead to a failure and certainly not to a hang.

The ideal would be to just not use them, but we use the type annotations non trivially. Perhaps we could audit the code and make an effort to separate type analysis so it obviously never leads to failures and the product can bail out of not understanding type annotations.

That'd be a larger effort beyond a single ticket - how far do we want to go? Should I file something along these lines or we just continue fixing the issues as bugs arise.
