### ISSUE TITLE
Output as component input leads to unknown value

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#7318]
When providing an `output` into a multi-language component, the value is treated as unknown or undefined and leads to unexpected behavior.

Per @justinvp, these lines appear to be the culprit:

https://github.com/pulumi/pulumi/blob/258fb00bc2ecbd489af6d694a2204468cc7ca729/sdk/go/pulumi/provider.go#L238

https://github.com/pulumi/pulumi/blob/258fb00bc2ecbd489af6d694a2204468cc7ca729/sdk/go/pulumi/provider.go#L188

(Apologies for brevity of issue, lots of detail in a private slack conversation.)

**Comment by justinvp** [comment]
Note that this was based on the original TypeScript implementation, so we should audit the provider code for all the languages.

https://github.com/pulumi/pulumi/blob/258fb00bc2ecbd489af6d694a2204468cc7ca729/sdk/nodejs/provider/server.ts#L311-L312
