### ISSUE TITLE
NodeJS Automation API - detect side by side @pulumi/pulumi and fail early

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#7333]
Addresses the underlying issue behind one of the reports in https://github.com/pulumi/pulumi/issues/6998

When two copies of pulumi/pulumi are loaded in an automation api inline program, there can be problems with global state and the outstanding work queue. We should try to detect this scenario and fail fast.

**Comment by hzshlomi** [comment]
Hi Evan, I saw the patch is storing a random value in the environment and my question is - do you intent to also prohibit same version parallel runs? asking because a previously working program just stopped running throwing the `Detected multiple versions of '@pulumi/pulumi' in use in an inline automation api program` error message.

**Comment by EvanBoyle** [comment]
@hzshlomi parallel same version runs of inline programs are not supported for nodejs at the moment: https://github.com/pulumi/pulumi/issues/5449

There is some global state in the nodejs sdk, and parallel executions can cause strange and undefined behavior leading to  inconsistent and hard to diagnose errors.

**Comment by hzshlomi** [comment]
Thanks for the reply and the pointer. There is yet another usage scenario that is prohibited by this implementation - the case where you want to wrap up common functions in a helper library. the pulumi sdk would be `require`d more than once and complain, is that correct?

**Comment by EvanBoyle** [comment]
> the case where you want to wrap up common functions in a helper library
I believe you should still be able to use the `resolutions` field of `package.json` to force usage of a single pulumi/pulumi. Alternatively, if this is a helper library you are in control of, you can either declare pulumi as a peer dependency, or curry in the pulumi modules (pass the instance of pulumi as a parameter to your helper library/functions). 

If you have an example/minimal repro happy to help get you unblocked here.

**Comment by hzshlomi** [comment]
Thanks again :) i think i will just go ahead and export pulumi/pulumi for the helper lib user to require.. i guess it will do for now
