### ISSUE TITLE
pulumi up cmd unable to find file outside of pulumi folder

### ISSUE THREAD

**Issue by Maritcode** [pulumi/pulumi#7336]
Trying to use a public key in a secret folder outside of pulumi folder ("/../secret/id_rsa.pub"). pulumi up cmd gives errors.
However, if using a public key inside of pulumi folder ("/../pulumi/id_rsa.pub"), pulumi up cmd works fine.
public key file is already on chmod 777.

## Steps to reproduce
index.ts file
```ts
import * as pulumi from "@pulumi/pulumi";
import * as linode from "@pulumi/linode";
const fs = require("fs");
const path = require("path");
let pubKey: string = fs.readFileSync(path.join(__dirname, "/../secret/id_rsa.pub")).toString();

const masterInstance = new linode.Instance("nanode-master", {
  group: "masters",
  type: "g6-nanode-1",
  region: "ap-south",
  image: "linode/alpine3.13",
  authorizedKeys: [pubKey],
  rootPass: "rootPass123!",
  tags: ["master node"],
});
```

## Expected:
Expect it to proceed to create instance. Same result if "/../secret/id_rsa.pub" is change to "/../pulumi/id_rsa.pub" and do 'pulumi up'.

## Actual:
> error: Running program '/pulumi' failed with an unhandled exception:
    Error: ENOENT: no such file or directory, open '/secret/id_rsa.pub'
        at Object.openSync (fs.js:462:3)
        at Object.readFileSync (fs.js:364:35)
        at Object.<anonymous> (/pulumi/index.ts:5:25)
        at Module._compile (internal/modules/cjs/loader.js:999:30)
        at Module.m._compile (/pulumi/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
        at Object.require.extensions.<computed> [as .ts] (/pulumi/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:863:32)
        at Function.Module._load (internal/modules/cjs/loader.js:708:14)
        at Module.require (internal/modules/cjs/loader.js:887:19)

**Comment by leezen** [comment]
@Maritcode I don't think this is a Pulumi issue so much as how NodeJS works? I don't see anything in your stack trace or error suggesting there's an issue with Pulumi itself. Could you please provide what your directory structure looks like and how you're invoking `pulumi`?

**Comment by Maritcode** [comment]
|-pulumi
|--|--.pulumi
|--|--node_modules
|--|--.gitignore
|--|--id_rsa.pub
|--|--index.ts
|--|--package.json
|--|--Pulumi.dev.yaml
|--|--Pulumi.yaml
|--|--tsconfig.json
|--|--yarn.lock
|
|-secret
|--|--id_rsa.pub

both files are exactly the same and same permission.
reading from pulumi folder and 'pulumi up' works. create instance.

reading from secret folder and 'pulumi up' errors.

**Comment by leezen** [comment]
I'm not able to reproduce this behavior with running `pulumi`. It'd be great if you try to reproduce this w/o pulumi, e.g. create a file like `test.ts`:

```typescript
const fs = require("fs");
const path = require("path");
let pubKey: string = fs.readFileSync(path.join(__dirname, "/../secret/id_rsa.pub")).toString();
console.log(pubKey);
```

and then run `$(yarn bin)/ts-node test.ts` to see if that works or still results in the same error.

**Comment by Maritcode** [comment]
Is only during 'pulumi up' that is not able to find the file. 
console.log or other data handling function works perfectly in nodeJS environment, express or etc. whether is reading from within pulumi folder or outside pulumi folder.

To replicate the exact same error, there are a few prerequisite steps of set up required.
1. Shell Env required: 
a) PULUMI_BACKEND_URL="file://"
b) PULUMI_PREFER_YARN=true
2. pulumi login --local
3. pulumi new linode-typescript -n linode-pulumi -d linode-typescript -s dev --force
a) prompts for linode access token and paste in ( requires linode account and linode instance access token )
4. create the same index.ts
```ts
import * as pulumi from "@pulumi/pulumi";
import * as linode from "@pulumi/linode";
const fs = require("fs");
const path = require("path");
let pubKey: string = fs.readFileSync(path.join(__dirname, "/../secret/id_rsa.pub")).toString();

const masterInstance = new linode.Instance("nanode-master", {
group: "masters",
type: "g6-nanode-1",
region: "ap-south",
image: "linode/alpine3.13",
authorizedKeys: [pubKey],
rootPass: "rootPass123!",
tags: ["master node"],
});
```
5. pulumi up

If you don't have linode, let me know where to find you so I can drop you a temporary linode access token.

**Comment by Maritcode** [comment]
Reinstalled pulumi and it works now.
