### ISSUE TITLE
Distinguish complete (`created`) from in-progress (`creating) tasks

### ISSUE THREAD

**Issue by mikemaccana** [pulumi/pulumi#7337]
When looking at pulumi console output it's often difficult to see what's in progress (green `creating`) vs what's finished (green `created`), particularly when there's a lot resources been created:

![image](https://user-images.githubusercontent.com/172594/122542131-4204ac00-d022-11eb-8f72-19e94c7763c2.png)

I'd make `creating...` in blue. This would make it really obvious to see  what's outstanding.

**Comment by marsblkm** [comment]
Hi @mikemaccana mind if I take this one?

**Comment by marsblkm** [comment]
Hi I am new to this so sorry I might have tagged the wrong person....

Here is what I have found out:

The colour of each `StepOp` is defined in https://github.com/pulumi/pulumi/blob/master/pkg/resource/deploy/step.go#L1059 like this:
```
func (op StepOp) Color() string {
	switch op {
	case OpSame:
		return colors.SpecUnimportant
	case OpCreate, OpImport:
		return colors.SpecCreate
	case OpDelete:
		return colors.SpecDelete
	case OpUpdate:
		return colors.SpecUpdate
	case OpReplace:
		return colors.SpecReplace
	case OpCreateReplacement:
		return colors.SpecCreateReplacement
	case OpDeleteReplaced:
		return colors.SpecDeleteReplaced
	case OpRead:
		return colors.SpecRead
	case OpReadReplacement, OpImportReplacement:
		return colors.SpecReplace
	case OpRefresh:
		return colors.SpecUpdate
	case OpReadDiscard, OpDiscardReplaced:
		return colors.SpecDelete
	default:
		contract.Failf("Unrecognized resource step op: '%v'", op)
		return ""
	}
}
```
This means no matter the progress of `OpCreate` is in progress(`creating`), preview(`create`), done(`created` or `creating failed`), it is always going to be green. (see here: https://github.com/pulumi/pulumi/blob/master/pkg/backend/display/progress.go)

It looks kinda tricky to change the colour of same ops based on its progress/status without breaking the exisiting patter. Thoughts?
