### ISSUE TITLE
Generated enums in Go are not "Inputty"

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi#7351]
Given the following schema definition for an input property

```
                "volumeType": {
                    "$ref": "#/types/x:index:EbsVolumeType",
                    "type": "string"
                },
```

And the following (shortened) definition of the referenced type:

```
        "x:index:EbsVolumeType": {
            "type": "string",
            "enum": [
                {
                    "name": "gp2",
                    "value": "gp2"
                },
                {
                    "name": "io1",
                    "value": "io1"
                },
            ]
        },
```

The Go code generator generates the following entry in to the input-typed arguments structure for the resource with the input property:

```
	VolumeType EbsVolumeType `pulumi:"volumeType"`
```

However, `EbsVolumeType` is a type alias for `pulumi.String`, which is not an `Input`.

Consequently, `Output` types cannot be supplied here, which is unexpected.

**Comment by pgavlin** [comment]
There are a couple of levels to the fix here.

1. We need to generate an `Input` interface type for each enum
2. We need to change [the code that generates the input type name for an enum type](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/go/gen.go#L259-L261) to reference the input interface

For (1), the [code that generates enum type definitions](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/go/gen.go#L781-L818) probably just needs to call [`genInputInterface`](https://github.com/pulumi/pulumi/blob/634e97cd55d8ad0347924b535f3f0daf6517a6c1/pkg/codegen/go/gen.go#L633-L640).

**Comment by komalali** [comment]
Hmm, it seems like we are not generating output types for enums currently. This is all we generate: https://github.com/pulumi/pulumi/blob/73a66f48ead301bacf1d7d2833c016cf803b57c1/pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/pulumiEnums.go#L40-L67

We do appear to generate both input interfaces and output types/methods for [arrays](https://github.com/pulumi/pulumi/blob/73a66f48ead301bacf1d7d2833c016cf803b57c1/pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/pulumiEnums.go#L99-L142) and [maps](https://github.com/pulumi/pulumi/blob/73a66f48ead301bacf1d7d2833c016cf803b57c1/pkg/codegen/internal/test/testdata/simple-enum-schema/go/plant/tree/v1/pulumiEnums.go#L172-L215) though
