### ISSUE TITLE
Fix Go SDK to be compatible with changes in #7059

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#7359]
With the changes in #7059, any attempt to use the new features causes a panic.

```
panic: fatal: An assertion has failed: map[]: cannot assign map[string]providerconstruct.TestObjInput to map[string]providerconstruct.TestObj
    goroutine 13 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x18b7e00, 0x1a05ac9, 0x1a, 0xc0004a8fc0, 0x3, 0x3)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/common/util/contract/assert.go:33 +0x1a5
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputAndDetermineSecret(0x18b7e80, 0x0, 0x1b0aba0, 0x18b7e20, 0x1, 0x1, 0x0, 0x181cc53, 0xe, 0x0, ...)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/pulumi/rpc.go:288 +0x514
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInput(0x18b7e80, 0x0, 0x1b0aba0, 0x18b7e20, 0x181cc01, 0xe, 0x0, 0x0, 0x1b0aba0, 0x18b7e20, ...)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/pulumi/rpc.go:170 +0x73
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputs.func1(0x181cc6b, 0xe, 0x18b7e80, 0x0, 0x1b0aba0, 0x18b7e20, 0x195, 0x0)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/pulumi/rpc.go:77 +0x9f
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.marshalInputs(0x1aea900, 0xc0001280f0, 0x22, 0xc0003b2390, 0xc0006041e0, 0x1, 0xc00019c0f0, 0x47, 0x0)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/pulumi/rpc.go:140 +0x605
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).prepareResourceInputs(0xc00039c140, 0x1aea900, 0xc0001280f0, 0x1a0dcda, 0x22, 0xc0006041e0, 0xc000136190, 0x1, 0x0, 0x0, ...)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/pulumi/context.go:949 +0x277
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).registerResource.func1(0xc000136190, 0xc00039c140, 0x1aea900, 0xc0001280f0, 0x1a0dcda, 0x22, 0xc0006041e0, 0x1, 0x19f53d8, 0x5, ...)
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/pulumi/context.go:577 +0x1d7
    created by github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).registerResource
    	/Users/Luke/Code/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.4.0/go/pulumi/context.go:564 +0x5a5
    exit status 2
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

This patch fixes the panic:

```patch
diff --git a/sdk/go/pulumi/provider.go b/sdk/go/pulumi/provider.go
index 684732d02..a650d281f 100644
--- a/sdk/go/pulumi/provider.go
+++ b/sdk/go/pulumi/provider.go
@@ -21,11 +21,11 @@ import (
 	"strings"
 
 	"github.com/pkg/errors"
+	"google.golang.org/grpc"
+
 	"github.com/pulumi/pulumi/sdk/v3/go/common/resource"
 	"github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin"
-
 	pulumirpc "github.com/pulumi/pulumi/sdk/v3/proto/go"
-	"google.golang.org/grpc"
 )
 
 type constructFunc func(ctx *Context, typ, name string, inputs map[string]interface{},
@@ -60,6 +60,7 @@ func construct(ctx context.Context, req *pulumirpc.ConstructRequest, engineConn
 		return nil, errors.Wrap(err, "unmarshaling inputs")
 	}
 	inputs := make(map[string]interface{}, len(deserializedInputs))
+
 	for key, value := range deserializedInputs {
 		k := string(key)
 		var deps []Resource
@@ -216,27 +217,66 @@ func constructInputsCopyTo(ctx *Context, inputs map[string]interface{}, args int
 				continue
 			}
 
-			if field.Type.Implements(outputType) || field.Type.Implements(inputType) {
+			handleField := func(typ reflect.Type, value resource.PropertyValue, deps []Resource) (reflect.Value, error) {
 				resultType := anyOutputType
-				if field.Type.Implements(outputType) {
-					resultType = field.Type
-				} else if field.Type.Implements(inputType) {
-					toOutputMethodName := "To" + strings.TrimSuffix(field.Type.Name(), "Input") + "Output"
-					if toOutputMethod, found := field.Type.MethodByName(toOutputMethodName); found {
+				if typ.Implements(outputType) {
+					resultType = typ
+				} else if typ.Implements(inputType) {
+					toOutputMethodName := "To" + strings.TrimSuffix(typ.Name(), "Input") + "Output"
+					if toOutputMethod, found := typ.MethodByName(toOutputMethodName); found {
 						mt := toOutputMethod.Type
 						if mt.NumIn() == 0 && mt.NumOut() == 1 && mt.Out(0).Implements(outputType) {
 							resultType = mt.Out(0)
 						}
 					}
 				}
-				output := ctx.newOutput(resultType, ci.deps...)
+				output := ctx.newOutput(resultType, deps...)
 				dest := reflect.New(output.ElementType()).Elem()
-				secret, err := unmarshalOutput(ctx, ci.value, dest)
+				secret, err := unmarshalOutput(ctx, value, dest)
+				if err != nil {
+					return reflect.Value{}, err
+				}
+				output.getState().resolve(dest.Interface(), !value.ContainsUnknowns(), secret, deps)
+				return reflect.ValueOf(output), nil
+			}
+
+			if field.Type.Implements(outputType) || field.Type.Implements(inputType) {
+				val, err := handleField(field.Type, ci.value, ci.deps)
 				if err != nil {
 					return err
 				}
-				output.getState().resolve(dest.Interface(), true /*known*/, secret, nil)
-				fieldV.Set(reflect.ValueOf(output))
+				fieldV.Set(val)
+				continue
+			}
+
+			if field.Type.Kind() == reflect.Slice && (field.Type.Elem().Implements(outputType) || field.Type.Elem().Implements(inputType)) {
+				elemType := field.Type.Elem()
+				length := len(ci.value.ArrayValue())
+				dest := reflect.MakeSlice(field.Type, length, length)
+				for i := 0; i < length; i++ {
+					val, err := handleField(elemType, ci.value.ArrayValue()[i], ci.deps)
+					if err != nil {
+						return err
+					}
+					dest.Index(i).Set(val)
+				}
+				fieldV.Set(dest)
+				continue
+			}
+
+			if field.Type.Kind() == reflect.Map && (field.Type.Elem().Implements(outputType) || field.Type.Elem().Implements(inputType)) {
+				elemType := field.Type.Elem()
+				length := len(ci.value.ObjectValue())
+				dest := reflect.MakeMapWithSize(field.Type, length)
+				for k, v := range ci.value.ObjectValue() {
+					key := reflect.ValueOf(string(k))
+					val, err := handleField(elemType, v, ci.deps)
+					if err != nil {
+						return err
+					}
+					dest.SetMapIndex(key, val)
+				}
+				fieldV.Set(dest)
 				continue
 			}
```

**Comment by infin8x** [comment]
We should fix this in all languages, if needed

**Comment by pgavlin** [comment]
> We should fix this in all languages, if needed

I do think that we'll need similar fixes in all languages. I'm pretty certain that the above patch is incomplete, as well, as it doesn't descend into types beyond the top level.

**Comment by pgavlin** [comment]
Porting the preliminary fix for this issue to Node + Python is proving troublesome due to the lack of type information during the deserialization process. This prevents the deserializer from understanding exactly which values should be prompt and which should be `Output`s. I see a few different approaches we could take here:

1. Insist that each multi-language component make schema information available, and use pull type information from the schema. This has the benefit of building upon some pieces that already exist, but does imply some new work--especially for Node--to consume schema information during deserialization.
2. Emit additional code in the SDKs s.t. argument types provide their own deserializers. Although this would work, we would be generating a large amount of new code, and further complicating the SDK code generators. It would also be more difficult to fix any bugs that arise.
3. Expand the definition of the [Output](https://github.com/pulumi/pulumi/blob/master/sdk/go/common/resource/properties.go#L83-L88) property type to include dependencies as well as the resolved value, and serialize outputs as such. This has the benefit of removing the need for the various maps that track input property dependencies, keeps deserialization logic centralized, and touches a well- (and recently-) trod path. The lattermost point is also its most significant downside, however: this approach does require touching the core RPC types, which means that we must be very careful to avoid unintentional breaks.

My preference is for option (3), as it is a relatively straightforward extension of the existing RPC type system that can easily be scoped to multi-language components by only enabling output marshaling when `remote` is set to `true` in a `RegisterResourceRequest`. In addition, we can lean on our existing mechanisms for version negotiation if necessary to ensure that we don't accidentally break existing multi-language components.

@lukehoban @infin8x @emiliza @justinvp @jen20 thoughts?

**Comment by justinvp** [comment]
Option 3 is my preference as well.

**Comment by pgavlin** [comment]
Sounds like we have a little more breathing room on this than we thought. @infin8x @emiliza should we move this to 0.59?

**Comment by emiliza** [comment]
Since this is just for component authors we can punt on the Node+Python preliminary port fixes for M59+

We can remove the `p1` label here since that's resolved by that prelim fix. But we should keep this in the current iteration to start scoping out what the more complete fix would be and carry over to M59

**Comment by pgavlin** [comment]
Here's the way I'd like to break this work down. Anything that is demarcated with a
letter is parallelizable with respect to its peers.

1. Prerequisites
	a. Add a monitor feature for output values. This feature will be disabled by default,
	   and should be toggleable via an envvar for testing purposes.
	b. Expand the definition of `resource.Output` in the Go SDK to additional information
	   about the output, i.e. dependencies and secretness
2. RPC Support
	a. Add support in the core Go RPC code for marshaling and unmarshaling output values
		- Output values should be marshaled as special objects ala archives, assets, and
		  resource refs
		- Output values should be unmarshaled as `resource.Output` values
	b. Add support in the language SDKs for marshaling and unmarshaling output values
		- The SDKs must not produce output values unless the monitor feature is enabled
			- We can probably scope this even further and only produce output values when
			  marshaling the inputs to a multi-language component
			- If we chose not to do so, then the engine will need to replace output values
			  with their resolved value when marshaling for a consumer that does not itself
			  support output values. We have prior art for this with resource refs
		- Output values should be marshaled as the same special object produced and
		  consumed by the engine
		- Output values should be unmarshaled into the language SDK's representation of
		  a Pulumi Output
3. Enable end-to-end tests using the envvar added in step (1)
	a. Examples tests
	b. Multi-lang-specific tests
4. Assuming end-to-end tests are clean, remove the envvar (or change its polarity) and
   enable output values by default

I do not think that this is a tremendous amount of work. (1) is trivial, (2) should take at
most 2 weeks assuming 1 engineer, (3) can take a variable amount of time depending on the
tests we choose to run + whether or not we encounter failures, and (4) is trivial.

**Comment by emiliza** [comment]
Closing this out as the original request for addressing the panic and implementing the patch (which has been merged by https://github.com/pulumi/pulumi/pull/7369)

Tracking remaining work of the full-fix in: https://github.com/pulumi/pulumi/issues/7434
