### ISSUE TITLE
Flaky TestBrokenDynamicProvider

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#7361]
https://github.com/pulumi/pulumi/runs/2898508112

panic: TestBrokenDynamicProvider: test timed out after 600 seconds, suspect pulumi hanging

Note: failure only on Mac OS runner, perhaps something network-related blowing the timeout?

If this happens again please +1 the issue.

**Comment by emiliza** [comment]
+1 just happened again 😞 

https://github.com/pulumi/pulumi/runs/3549833224?check_suite_focus=true
