### ISSUE TITLE
Generating complete code when running `pulumi import `?

### ISSUE THREAD

**Issue by lyenliang** [pulumi/pulumi#7366]
When importing an AWS resource using pulumi, the code currently generated does not contain all the details of the resource. 

For example, when I run `pulumi import aws:elasticache/cluster:Cluster my-redis my-redis`, the python code I get is 

```
my_redis = aws.elasticache.Cluster("my-redis",
    cluster_id="my-redis",
    notification_topic_arn="arn:aws:sns:ap-northeast-1:123456789123:redis_sns_topic",
    opts=pulumi.ResourceOptions(protect=True))
```

It does not contain `availabilityZone`, `azMode`, `engine`, ... etc.

Do you guys think that adding a new option for `pulumi import` so that it can generate a code that contains all the details is a good idea?

The new option might be `pulumi import --complete-code ...`.

I like this feature because I want to create a new redis in another AWS region.

The steps I'm going to use for migrating the redis to another AWS regions are as the following:
1. Run `pulumi import --complete-code ...` in AWS region A to get the the code that contains all the details of redis.
2. Modify some of the details of the redis service so that it can run in AWS region B.
3. Run `use pulumi stack select <new_stack>` to switch to a new stack. This stack is created for region B.
4. Run `pulumi up` to create the redis service in region B.

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in #8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
