### ISSUE TITLE
When stack outputs are `undefined`, they act as though there was no stack output at all

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#7376]
Feedback from a user in email:

> If you export an output value that ends up being undefined/None/etc, then that export will simply be omitted.

For example, this program in TypeScript:

```ts
export const a = undefined;
export const b = null;
export const c = "";
export const d = 0;
```

Results in this update (note that *only* `d` shows up as an output here):

```
Updating (dev)

View Live: https://app.pulumi.com/lukehoban/undefinedexport/dev/updates/1

     Type                 Name                 Status
 +   pulumi:pulumi:Stack  undefinedexport-dev  created

Outputs:
    d: 0

Resources:
    + 1 created

Duration: 2s
```

And this list of stack outputs (note that `b`, `c`, and `d` show up here, but *not* `a`):

```
Current stack outputs (3):
    OUTPUT  VALUE
    b       null
    c
    d       0
```

The biggest issue is that `a` doesn't show up in this last output at all.  The issue with the `pulumi up` display is more superficial, but also should be addressed.

**Comment by filip-taxamo** [comment]
I got bitten by this badly today when it got combined with https://github.com/opsgenie/terraform-provider-opsgenie/issues/227 - an output of the apiKey property of an imported Opsgenie API integration was disappearing on me, because it was nil.

**Comment by iwahbe** [comment]
**CC** @lukehoban @emiliza 
The "superficial" issue (`b`, `c`) is by design: https://github.com/pulumi/pulumi/blob/f8a98b2a86472773051507a829b18b653fe18673/pkg/engine/diff.go#L437-L458
I would be happy to change this if we decide the additional clutter is worth the lessoned confusion.

**Comment by lukehoban** [comment]
> The undefined issue (a) is also by design:

Ideally I believe we should change the design here based on feedback we've heard from users.  This has caused significant confusion for users who run into this (normally because something ends up being undefined, and they try and export it to test it, but then the output is just missing).  

That said, I'm slightly nervous about the code block you linked being the root of this.  That code is used for *all* object serialization from the language SDK into the engine.  I am not at all certain what the implications of passing `undefined` values along that RPC interface are - and we'd need to make changes there carefully given the potential blast radius of changes at that layer.

An alternative would be to have the code in https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/runtime/stack.ts#L96:L96 turn `undefined` into `null`, which does survive through the RPC.  This is somewhat justified by the fact that we are already rewriting "normal" JS values into a special format for purposes of stack exports.  

That said, I'm not entirely sure why `null` is treated differently here, and whether `null` values behave properly here in general.  But I suspect they do.

There's also the question of what happens here in other languages.  From a quick test, I believe Python `None` also disappears, and it is less clear there what other sentinel we would use to end up with a language-agnostic "null" in the Pulumi engine.   I haven't yet looked at Go and .NET, but I suspect there are subtle differences here for each of them as well.

I feel like we likely do eventually have to rationalize this across languages and address the usability gap that has tripped up many users, but I'm also not sure there's a "simple" fix we can make consistently across languages.

Definitely interested in @justinvp and @pgavlin input on this as well.

> The "superficial" issue (b, c) is by design:

This one again seems to be related to logic that is used much more generally, and I'm not sure we should make a change here right now.  We should likely revisit overall diff rendering at some point, as there are quite a few issues tracking feedback on diff generally, and this is part of that class of feedback.

I think it's fine to use this issue to track the just the issue with (a) not showing up.

**Comment by justinvp** [comment]
I think it'd be worth looking into "keeping" top-level `undefined` stack outputs by coercing them to `null` (and similar for `None` values in Python, `nil` in Go, and `null` in .NET) to improve this usability issue. It is a bit unfortunate that stack outputs behave differently than other resource outputs, but this is already the case today with the way we serialize certain stack output values specially. If we were to do this, out of an abundance of caution, we'd probably want to do it in a major release like 4.0 due to the behavior change and possibly even have a envvar to opt-in to the old behavior.

**Comment by Sodki** [comment]
Hi, I also wanted to point out another behaviour related to this. I'm using Python, so the language below will reflect this.

If we export a dictionary that contains a None value, then that value does show up in the outputs as `null`. If we then import that Output into a different stack, then the element with the `null` value is gone from the dictionary.

**Comment by abhinav** [comment]
Discussed this with the team in Ideation today.
The consensus was as follows:

Coercing `undefined` to `null` or an empty string is a significant unexpected change in semantics and we should not do that.
Further, `undefined` itself is not a valid value in the wire protocol; it's also [not a valid JSON value](https://stackoverflow.com/a/14946821), which the protocol aims to emulate.

```javascript
JSON.stringify({a: undefined})
// '{}'
```

_However_, we agree that this can be a pain point for users running into this.
We think we can have the Javascript SDK log a message when producing outputs and an undefined value is being left behind.

Would that be sufficient for the case you ran into, @jkodroff?

**Comment by iwahbe** [comment]
> Discussed this with the team in Ideation today. The consensus was as follows:
> 
> Coercing `undefined` to `null` or an empty string is a significant unexpected change in semantics and we should not do that. Further, `undefined` itself is not a valid value in the wire protocol; it's also [not a valid JSON value](https://stackoverflow.com/a/14946821), which the protocol aims to emulate.
> 
> ```js
> JSON.stringify({a: undefined})
> // '{}'
> ```
> 
> _However_, we agree that this can be a pain point for users running into this. We think we can have the Javascript SDK log a message when producing outputs and an undefined value is being left behind.
> 
> Would that be sufficient for the case you ran into, @jkodroff?

We could also send the special value `{ "specialKey": "specialUndefinedValue" }` the same way we do for secrets. Both the engine and the language runtime need to be aware of this, but it would allow `[undefined]` to show up just like `[secret]`.

**Comment by Frassle** [comment]
> We could also send the special value 

I don't want to add a new special type to the wire protocol to handle one oddity of JavaScript. I think the conclusion given by @abhinav should stand.

**Comment by jkodroff** [comment]
Forgot to respond to this. @abhinav @Frassle: Yes, a warning would be sufficient. As a user, just give me some clear indication of why my output isn't present, e.g.

> Output `foo` is undefined and will not appear in stack outputs.

**Comment by jkodroff** [comment]
Thanks for fixing this!
