### ISSUE TITLE
`pulumi stack ls` returns nothing and does not prompt for passphrase

### ISSUE THREAD

**Issue by shousper** [pulumi/pulumi#7381]
When you have a stack using a passphrase for encryption, running `pulumi stack ls` does not return any stacks, nor prompt for the passphrase. However, setting the passphrase via `PULUMI_CONFIG_PASSPHRASE` resolves it.

If it cannot get the stack list without the passphrase, it should prompt for it?

## Steps to reproduce

I'm not 100% certain if relevant, but our stacks are stored in S3.

1. Create a new stack with a passphrase (can be empty AFAIK)
2. `pulumi up` to persist state.
3. In another folder, or on another machine, checkout or copy the same stack code.
4. `pulumi stack ls`.

Expected: Prompt for passphrase.
Actual: No stacks returned.

**Comment by lukehoban** [comment]
This is the same issue as tracked in https://github.com/pulumi/pulumi/issues/4798 - so closing out to continue tracking there.
