### ISSUE TITLE
Pulumi input_type decorator default property value

### ISSUE THREAD

**Issue by cyrano5614** [pulumi/pulumi#7385]
## problem
Using pulumi decorator for input_type and setting property default value doesn't seem like its getting respected.

## Steps to reproduce minimal
```
import pulumi

@pulumi.input_type
class Test:
    a: pulumi.Input[str] = pulumi.property("a", default="foo")
    b: pulumi.Input[str] = pulumi.property("b", default="bar")

ham = Test()

print(ham.a)
# actual: "a"
# expected "foo"

print(ham.b)
# actual: "b"
# expected "bar"

```

Expected: default value of "foo", and "bar" for a, and b respectively
Actual: property name is set as default instead of default value

Maybe I am not understanding the use of pulumi.input_type correctly?  Thank you for your help and time.

**Comment by lukehoban** [comment]
@cyrano5614 What's your scenario for wanting to use these in your own objects?  Today, the `pulumi.input_type` and `pulumi.property` mechanisms are an implementation tool used inside Pulumi libraries by some of the serialization/deserialization machinery we have.  They aren't really intended to be used in other contexts outside of Pulumi code generation.  If you have more details on the use case, please do reopen with more details.

**Comment by SharpEdgeMarshall** [comment]
Actually I'm having this issue too, I'm creating a ComponentResource that should receive nested args and I was following the `@pulumi.input_type` approach as indicated in source code comments:

file: pulumi/_types.py
```
Here's how the `NestedArgs` input class can be declared:
#
#   @pulumi.input_type
#   class NestedArgs:
#       first_arg: pulumi.Input[str] = pulumi.property("firstArg")
#       second_arg: Optional[pulumi.Input[float]] = pulumi.property("secondArg", default=None)
#
```

**Comment by SharpEdgeMarshall** [comment]
@lukehoban this looks like a bug, if you use the short version with only `@pulumi.input_type` you get the error that @cyrano5614 described, if you use the verbose approach the behaviour is correct

**Comment by SharpEdgeMarshall** [comment]
This works:
```
@pulumi.input_type
class ClusterArgs:

    def __init__(__self__, *,
                 k8s_version: Optional[pulumi.Input[str]] = "1.21"):
        pulumi.set(__self__, "k8s_version", k8s_version)

    @property
    @pulumi.getter(name="k8s_version")
    def k8s_version(self) -> pulumi.Input[str]:
        return pulumi.get(self, "k8s_version")

    @k8s_version.setter
    def k8s_version(self, value: pulumi.Input[str]):
        pulumi.set(self, "k8s_version", value)
```

This not:
```
@pulumi.input_type
class ClusterArgs:
    k8s_version: Optional[pulumi.Input[str]] = pulumi.property("k8s_version", default="1.21")
```

**Comment by justinvp** [comment]
This is a legitimate issue. `pulumi.property` can be used as a convenience when defining an input class by hand to avoid having to write all the boilerplate that our generated SDK emits. Since it isn't used by our codegen, it hasn't been exercised very much, and indeed there is a bug with the default value handling. I'll open a PR with a fix.
