### ISSUE TITLE
Uniform authoring for SDK codegen tests

### ISSUE THREAD

**Issue by emiliza** [pulumi/pulumi#7405]
Currently: 
We hand author a schema  then compare the outputs (diff tests)

Things to consider:
- Look at how we’re doing comparison testing - decide on just one
- Scenarios to try: Re-baseline, failures, specific test
- Create set of utility functions and docs
- Start using existing utility functions
- Run all tests against all test schemas

**Comment by pgavlin** [comment]
This was fixed with https://github.com/pulumi/pulumi/pull/7433
