### ISSUE TITLE
[codegen] Go program Codegen issues when upgrading to pkg/v3.6.0

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi#7414]
The upgrade of pulumi-azuread to use pkg/v3.6.0 codegen has introduced some breaking changes to the go sdk:

```
- // _, err := azuread.LookupUser(ctx, &azuread.LookupUserArgs{
+ // _, err := azuread.LookupUser(ctx, &GetUserArgs{
```

https://github.com/pulumi/pulumi-azuread/pull/173/files#diff-47b50246e3a6181a6d86935973a3588781be2dc150a7527bebda445a4163c62dR42

This is currently blocking the upgrade to the new version of the bridge which is blocking codegen tests in the pulumi/pulumi repo

**Comment by emiliza** [comment]
Continuing from slack - assigning this to @komalali - @pgavlin please update if you have guidance on where this should be fixed, thanks!

**Comment by pgavlin** [comment]
> The upgrade of pulumi-azuread to use pkg/v3.6.0 codegen has introduced some breaking changes to the go sdk:

The snippet above is not a breaking change to the SDK. It is a change to the program code generator, and should not block upgrades. Are there other changes that are breaking?

**Comment by komalali** [comment]
My naive gut feeling is that something is going awry with [useLookupInvokeForm](https://github.com/pulumi/pulumi/blob/7b1d6ec1accce89a7aaf642aae883e4a2e579d13/pkg/codegen/go/gen_program.go#L666-L693)

**Comment by justinvp** [comment]
This appears to be long since fixed. The [latest](https://github.com/pulumi/pulumi-azuread/blob/b7104c6838a6d2692f1659f6d991c8f37499b6d6/sdk/go/azuread/getUser.go#L38) code looks like:

```
_, err := azuread.LookupUser(ctx, &azuread.LookupUserArgs{
```
