### ISSUE TITLE
Stack rename causes subsequent updates to try and recreate resources

### ISSUE THREAD

**Issue by sbogacz** [pulumi/pulumi#7421]
I ran into something I think would be somewhat unexpected when using pulumi stack rename today. The description says
 
 >Note: Because renaming a stack will change the value of getStack() inside a Pulumi program, if this name is used as part of a resource’s name, the next pulumi up will want to delete the old resource and create a new copy.

However, I've observed that `pulumi up` wants to destroy the stack and resources following a rename, regardless of `getStack()` being used to name the resources. Using a simple Go AWS program this can be reproduced:

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := s3.NewBucket(ctx, "bucket", &s3.BucketArgs{
			Acl: pulumi.String("private"),
			Tags: pulumi.StringMap{
				"Environment": pulumi.String("Dev"),
				"Name":        pulumi.String("My bucket"),
			},
		})
		if err != nil {
			return err
		}
		return nil
	})
}
```

`getStack()` is never used in the resource name, yet following a rename, the plan wants to delete and recreate the bucket and stack:

![image](https://user-images.githubusercontent.com/10064258/124202129-faa50380-da96-11eb-8660-879c665785c8.png)

I would expect `stack rename` followed by `pulumi up` to expect no changes, as long as `getStack()` wasn't used when naming resources.

EDIT: This seems to be backend specific, as the local backend does not present this same issue.

**Comment by lukehoban** [comment]
This definitely looks like a bug - the intended behaviour of `pulumi stack rename` is precisely to ensure that that stack name in URNs gets updated correctly.

> EDIT: This seems to be backend specific, as the local backend does not present this same issue.

That is surprising, but a good hint at where the issue might be here.

**Comment by sbogacz** [comment]
We were able to confirm that it was indeed a backend specific issue, and it was in our custom backend. Closing the issue.
