### ISSUE TITLE
pulumi.DependsOn should allow dependencies on Output

### ISSUE THREAD

**Issue by irl-segfault** [pulumi/pulumi#7429]
Hi all.

Go currently does not support dynamic providers, which means I cannot implement custom resources.  I have a use case which is described by the following pseudo-code:

```
resource1 := pkg.NewResource(...)

output2 := resource1.output1.ApplyT(func(s) bool { 
    // make API calls to external service
    return true
  })
resource2 := pkg.NewResource(..., pulumi.DependsOn(output2))
                                                                                                          ^ arg requires pulumi.Resource
```

In this case, I need to make API calls to some external service, and I want those calls to be a pre-requisite of creating any subsequent resources.  In order to do this, I can return a `BoolOutput` from the `ApplyT` call, but I have no way of injecting this `Output` into the dependency graph.

If Go had support for dynamic providers, it's possible I could wrap this in a custom resource.

In general, I feel like Pulumi users should be able to express dependencies on any awaitable value or asynchronous task, instead of only resources managed by Pulumi.  To me, this is a killer feature of Pulumi vs. something like Terraform.

**Comment by lukehoban** [comment]
This is tracked in #2545 and https://github.com/pulumi/pulumi/issues/3972.  Will close this out to continue tracking there.  Feel free to add additional notes on use cases there if not already covered in that issue.
