### ISSUE TITLE
Unable to preview basic EKS crosswalk stack

### ISSUE THREAD

**Issue by nickmanks** [pulumi/pulumi#7456]
Trying to follow the basic steps from https://www.pulumi.com/docs/guides/crosswalk/aws/eks/ to get started with an EKS cluster using crosswalk:

```ts
const provider = new aws.Provider("privileged", {
  assumeRole: {
    roleArn: roleToAssumeARN,
    sessionName: "FarBarSession",
    externalId: "FooBar",
  },
  region: aws.config.requireRegion(),
});

// Create an EKS cluster with the default configuration.
const cluster = new eks.Cluster(
  `gateway-${process.env.NODE_ENV}-cluster`,
  {
    providerCredentialOpts: {
      roleArn: roleToAssumeARN,
    },
  },
  { provider },
);

// Export the cluster's kubeconfig.
export const kubeconfig = cluster.kubeconfig;
```

1. Write code snippet above / follow EKS crosswalk instructions
2. Run `pulumi preview`

Expected: Stack to be created
Actual: `error: no resource plugin 'eks' found in the workspace or on your $PATH`

<img width="896" alt="Screen Shot 2021-07-08 at 10 38 29 pm" src="https://user-images.githubusercontent.com/13515460/124923286-a1f8dc00-e03d-11eb-9d6c-94f96e659141.png">

Tried to run:
```bash
pulumi plugin install resource eks 4.11.0
```

But got the error:
```
error: [resource plugin eks-4.11.0] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-eks-v4.11.0-darwin-amd64.tar.gz
```

**NOTE** This was after running `brew upgrade pulumi` and using following npm packages:

```
   "@pulumi/aws": "^4.11.0",
    "@pulumi/awsx": "^0.30.0",
    "@pulumi/eks": "^0.31.0",
    "@pulumi/pulumi": "^3.6.0",
```

Thanks in advance 🙏

**Comment by stack72** [comment]
Hi @nickmanks 

My apologies it wasn't clear what the command to run here. As you can see from your package.json, the version of eks is 0.31.0, therefore running the command:

```
pulumi plugin install resource eks 4.11.0
```

will unblock you here

I will leave this open so we actually track the bug here but this will at least let you get going

Paul

**Comment by nickmanks** [comment]
I think you mean:

```bash
pulumi plugin install resource eks 0.31.0
```

But yes this did work! thank you 🙏
