### ISSUE TITLE
Is it possible to check in code if CLI was invoked with up/destroy/preview ?

### ISSUE THREAD

**Issue by logileifs** [pulumi/pulumi#7465]
I have this script where I am creating a kubernetes cluster in digitalocean, I want to use the same script to create a local kind cluster when I run `pulumi up` with the stack `local`. That works fine but I also want to be able to destroy said cluster when I run `pulumi destroy` with the stack `local`.

So I am wondering if there is a way to check in the script if it has been invoked with `destroy` `up` or `preview` ?
Code example:
```
import subprocess
import pulumi

import pulumi_digitalocean as do
from pulumi_kubernetes import Provider
from pulumi_kubernetes.core import v1 as core
from pulumi_kubernetes.apps.v1 import Deployment
from pulumi_kubernetes.apps.v1 import DeploymentSpecArgs
from pulumi_kubernetes.meta.v1 import LabelSelectorArgs, ObjectMetaArgs

config = pulumi.Config()
stack = pulumi.get_stack()
print(f'stack: {stack}')
dry_run = pulumi.runtime.is_dry_run()
print(f'dry_run: {dry_run}')


def create_local_cluster():
	command = config.require('cluster_creation_command')
	p = subprocess.run(command.split(), check=True, capture_output=True)
	print(p.stderr.decode())


def create_cloud_cluster():
	cluster_cfg = config.require_object('cluster')
	cluster = do.KubernetesCluster(
		cluster_cfg['name'],
		name=cluster_cfg['name'],
		region=config.require('region'),
		version=cluster_cfg['version'],
		node_pool=do.KubernetesClusterNodePoolArgs(
			name=cluster_cfg['base_node_pool']['name'],
			size=cluster_cfg['base_node_pool']['size'],
			node_count=cluster_cfg['base_node_pool']['node_count']
		)
	)
	return cluster


def create_local_env():
	create_local_cluster()


def create_cloud_env():
	cluster = create_cloud_cluster()
	kube_config = cluster.kube_configs[0].raw_config.apply(lambda x: x)

	pulumi.export('cluster', cluster)
	pulumi.export('kube_config', kube_config)


if stack == 'local':
	if not dry_run:
		print('create local env')
		create_local_env()
	elif 'destroy':      # how can I get here ????
		destroy_local_env()
	else:
		print('local dry_run - doing nothing')
else:
	create_cloud_env()

```

**Comment by lukehoban** [comment]
The best solution to this is going to be [dynamic providers](https://www.pulumi.com/docs/intro/concepts/resources/#dynamicproviders), which would allow you to create your own resource provider inline in Python that handles the create, update, delete and diff operations specifically for the local Kind cluster.  This is the way you can plug into the resource lifecycle and define the behaviour for each operation yourself.

Note that your Pulumi program does't actually run at all during a `pulumi destroy`, so there is no way today to check for whether the program is being run in a destroy - as it isn't!  This is part of why dynamic providers actually need to be serialized and stored in the state file so they can be invoked even when the program isn't available. 

It *is* possible to check whether you are in a preview or not with `pulumi.runtime.is_dry_run()` - as both previews and updates run the program.

**Comment by logileifs** [comment]
Ahh okay I see. I will have a better look at the documentation for the dynamic providers.
Do you have any plans to add some providers to manage resources locally (like kind for example) ?
