### ISSUE TITLE
pulumi 3.6.1 doesn't show diffs

### ISSUE THREAD

**Issue by pbzdyl** [pulumi/pulumi#7486]
I use Pulumi dynamic provider and before 3.6.1 (I was using 3.6.0) `pulumi up` was showing diffs like the following:

```
$ pulumi up
Previewing update (dev):
     Type                               Name                                          Plan       Info
     pulumi:pulumi:Stack                my-dev
 ~   └─ pulumi-nodejs:dynamic:Resource  myorg:users:User:Admin    update     [diff: ~firstName]

Resources:
    ~ 1 to update
    1 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::XXX::pulumi:pulumi:Stack::my-dev]
    ~ pulumi-nodejs:dynamic:Resource: (update)
        [id=myorg:users:User:Admin]
        [urn=urn:pulumi:dev::XXX::pulumi-nodejs:dynamic:Resource::myorg:users:User:Admin]
      ~ user                   : {
          ~ firstName      : "John" => "Joe"
        }
```

However, after upgrading to 3.6.1, the detailed preview doesn't show the diff but the whole existing resource data

This issue has been also raised on Slack: https://pulumi-community.slack.com/archives/C84L4E3N1/p1625741083479000

**Comment by emiliza** [comment]
Sounds like a possible regression from the recent `replaceOnChanges`.  @lblackstone perhaps the new `sg.applyReplaceOnChanges`  is modifying the diff where it wasn’t before?
https://github.com/pulumi/pulumi/commit/eb32039013277d8bce69fe284e93fbdbfcab9964#diff-23931859ebe7b762c1c12b464bc738bc5a4d59a8b549ddf9784065ffbfee7fdbR529-R533 - can you please take a look?

**Comment by lblackstone** [comment]
I confirmed the regression is related to eb32039. Looking into it now.

**Comment by lblackstone** [comment]
@pgavlin @lukehoban Any idea why this would be happening? I added logging around the statement that Emiliza linked, and it doesn't appear that the diff is changing.

```
I0712 16:53:45.530163   51478 step_generator.go:529] Old diff for 'urn:pulumi:py-dynamic::aws-py-dynamicresource::pulumi-python:dynamic:Resource::mysql_votes_table' (details=map[] replaceKeys=[database_name] changeKeys=[])
I0712 16:53:45.530177   51478 step_generator.go:536] New diff for 'urn:pulumi:py-dynamic::aws-py-dynamicresource::pulumi-python:dynamic:Resource::mysql_votes_table' (details=map[] replaceKeys=[database_name] changeKeys=[])
```

**Comment by pgavlin** [comment]
What do you see if you dump the engine events (`PULUMI_DEBUG_COMMANDS=true pulumi pre --event-log some-file`)?

**Comment by ederst** [comment]
Works again:
```
      ~ config      : {
          ~ validate_args      : {
              ~ skip: true => false
            }
        }
```

Thanks!
