### ISSUE TITLE
Add pulumi.Getenv() function to Go SDK

### ISSUE THREAD

**Issue by johannesdrescher** [pulumi/pulumi#7490]
Using an environment variable as an input in Go requires wrapping `os.Getenv()` in `pulumi.String()`. My guess is that `pulumi.String(os.Getenv("FOO"))` appears very frequently in a lot of organizations' code.

This could be simplified by adding a single function to the Go SDK: `pulumi.Getenv()`. This would be similar to the `pulumi.Printf`, `pulumi.Fprintf` and `pulumi.Sprintf()` but much simpler to implement.

**Comment by lukehoban** [comment]
We've generally resisted adding `Output` wrappers of the long tail of functions that return strings in the core Go SDKs, as its a *very* long tail.  The `pulumi.Sprintf` and related functions are somewhat of an exception, as they actually aren't just wrapping the output string in an `Output`, they allow a simple way to compose incoming `Output` values into another `Output`, in the most common case of combining string values together.  This is the single most common use of `.Apply`, and thus the syntactic sugar felt like it paid for itself.  It's also replaces something rather cumbersome like `pulumi.All(in1, in2).ApplyT(func(args []interface{}) string { return fmt.Sprintf("%s: %s", args...) }).(pulumi.StringOutput)` with just `pulumi.Sprintf("%s: %s", in1, in2)`.  

In cases where it's just a matter of using `pulumi.String` (as you would have to even for a string literal), I think we will continue to hold the line of not adding new functions, and encouraging the slightly more explicit pattern that can be used consistently.

**Comment by johannesdrescher** [comment]
@lukehoban I agree that you should not add a huge number of output wrappers. But are you sure `os.Getenv` does not warrant another exception? Anyone could write a library to do this themselves but you end up having to tightly couple it with every infrastructure project that uses it. It just seems much more obvious to have a tiny function like in the Pulumi Go SDK for everyone to use.
