### ISSUE TITLE
Programgen extremely slow in Azure Native when upgrading to 3.6.0

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#7503]
Azure Native generates doc examples from JSON examples in Azure API spec. It's been always fairly slow (~7 minutes on my laptop) but upgrading the pkg dependency to 3.6.0 and above makes it super slow (I believe @komalali reported 4 hours, I didn't wait for completion).

I did a binary search and found #7059 to be the source of this slow-down. It's still slow in current master version (c3f5177). 

Right now, this is blocking an update of Azure Native (I'll try to figure out if I can exclude some slow examples as a temporary workaround).

**Comment by mikhailshilkov** [comment]
It looks like there's a single problematic resource `azure-native:costmanagement:Report`. I excluded it and generation got back to 7-ish minutes, so the workaround is fine for now.

**Comment by pgavlin** [comment]
> It looks like there's a single problematic resource azure-native:costmanagement:Report. I excluded it and generation got back to 7-ish minutes, so the workaround is fine for now.

Do you have CPU profiles that I might be able to dig in to?

**Comment by mikhailshilkov** [comment]
> Do you have CPU profiles that I might be able to dig in to?

No, I didn't produce them. I'm not even sure the operation completes in a reasonable time to get the profile. FWIW, the repro is `make generate_docs` in azure-native.

**Comment by pgavlin** [comment]
This is fixed. Here are the changes:
- https://github.com/pulumi/pulumi/pull/7548
- https://github.com/pulumi/pulumi/pull/7547
- https://github.com/pulumi/pulumi/pull/7546
- https://github.com/pulumi/pulumi/pull/7545
