### ISSUE TITLE
 error: Error: ' docker build ./app -t 12fda807-container' failed with exit code 1

### ISSUE THREAD

**Issue by harshack** [pulumi/pulumi#7528]
Trying to create Simple ECS Fargate service for express app using PULUMI. 
Locally using my Mac laptop i am able to spin up the infrastructure.. 
But when i switch the same code to CI/CD - Concourse it fails with  error: Error: ' docker build ./app -t 12fda807-container' failed with exit code 1

## Steps to reproduce
1.In CI/CD  Use below image for an task step

---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pulumi/pulumi
    tag: "latest" 

2. Try running below example code from https://www.pulumi.com/docs/guides/crosswalk/aws/ecr/

import * as awsx from "@pulumi/awsx";

// Create a repository, as before.
const repo = new awsx.ecr.Repository("my-repo");

// Build an image from the "./app" directory (relative to our project and containing Dockerfile),
// and publish it to our ECR repository provisioned above.
export const image = repo.buildAndPushImage("./app");

Expected:  docker build ./app -t <<RANDOM>>-container should pass
Actual:  docker build ./app -t <<RANDOM>>-container  is failing.

More Error:

 error: Error: ' docker build ./app -t 12fda807-container' failed with exit code 1
    
        at /tmp/build/23bf5af8/source-repo/infra/node_modules/@pulumi/docker.ts:592:15
        at Generator.next (<anonymous>)
        at fulfilled (/tmp/build/23bf5af8/source-repo/infra/node_modules/@pulumi/docker/docker.js:18:58)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
    error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by lukehoban** [comment]
> Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

It sounds like you don't have Docker installed?  To do a Docker build, you need a local Docker daemon running that can do the builds.
