### ISSUE TITLE
Typescript - Specific Class Cannot be Imported from Module Outside Index.ts

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#7543]
As a developer building component resources, I want to be able to import specific classes from an external module, instead of the whole module, so that I limit my imported resources. This behavior is supported in the index.ts (root of pulumi project), however, a compiler error is produced when this is located in an file other than index.ts.

## Steps to reproduce

1.  pulumi new aws-typescript
2. create new ts file called some-component.ts
3. in some-component.ts import Bucket from "@pulumi/aws/s3"
4. import the some-component into index.ts
5. pulumi up
6. boom goes the dynamite!

[git repo for completeness](https://github.com/phillipedwards/pulumi-ts-import-error)

#### component-resource
![image](https://user-images.githubusercontent.com/25461821/125871065-b3ce6342-7ad3-4a26-a29e-0b07f176a0d5.png)

#### index.ts
![image](https://user-images.githubusercontent.com/25461821/125871093-48eb1485-affa-4023-9704-69e7aa916f6a.png)

Expected:  New S3 bucket resource is created
Actual:  Compiler error is produced.  

![Screen Shot 2021-07-15 at 4 25 37 PM](https://user-images.githubusercontent.com/25461821/125870230-3fa60749-e06f-42a8-90e7-289e4a558521.png)

**Comment by justinvp** [comment]
I tried this out and couldn't reproduce the issue. It must be long since fixed.
