### ISSUE TITLE
Many net-new C# classes generated when updating to 3.7

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#7550]
See [here](https://github.com/pulumi/pulumi-azure-native/pull/986/commits/e1532ab56aaa4833890447c47c280653f195afd3) for an example of azure-native update. Those new classes are likely unused so it feels like a waste adding them on top of the already huge SDK with all the overhead that it brings.

**Comment by mikhailshilkov** [comment]
The change is apparently less significant that I deducted, thank you @pgavlin for following up

**Comment by pgavlin** [comment]
Going to go ahead and close this. The impact of the change was less than a half of a percent; the added code was in the Go SDK as a result of the recent changes around enums.
