### ISSUE TITLE
replaceOnChanges option treats "" as a wildcard

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi#7556]
Related to https://github.com/pulumi/pulumi/pull/7226

The `replaceOnChanges` resource option currently treats `""` the same as the wildcard `"*"`, which might lead to unexpected replacements. I think it would make more sense to ignore the empty string.

## Steps to reproduce

Run the following program.
```typescript
import * as k8s from "@pulumi/kubernetes";

const appLabels = { app: "nginx" };
const deployment = new k8s.apps.v1.Deployment("nginx", {
    spec: {
        selector: { matchLabels: appLabels },
        replicas: 1,
        template: {
            metadata: { labels: appLabels },
            spec: {
                containers: [{ name: "nginx", image: "nginx:1.14"}],
            },
        },
    }
}, {replaceOnChanges: [""]});
```

Update `.spec.replicas` to a new value:
```typescript
import * as k8s from "@pulumi/kubernetes";

const appLabels = { app: "nginx" };
const deployment = new k8s.apps.v1.Deployment("nginx", {
    spec: {
        selector: { matchLabels: appLabels },
        replicas: 3,
        template: {
            metadata: { labels: appLabels },
            spec: {
                containers: [{ name: "nginx", image: "nginx:1.14"}],
            },
        },
    }
}, {replaceOnChanges: [""]});
```

Expected: 
The resource should be updated.
![Screen Shot 2021-07-16 at 11 33 04 AM](https://user-images.githubusercontent.com/9253463/125986869-eee11051-ff5e-4bca-81a3-be55b09399d6.png)

Actual: 
The resource is replaced.
![Screen Shot 2021-07-16 at 11 33 31 AM](https://user-images.githubusercontent.com/9253463/125986916-b7a03f64-25fd-4fe2-91b9-d7c8c7d06d1f.png)

**Comment by lblackstone** [comment]
@lukehoban What do you think?

**Comment by lukehoban** [comment]
This is technically intentional, and I think is reasonable and expected based on the description/specification in https://www.pulumi.com/docs/intro/concepts/resources/#replaceonchanges.

What would you expect `{replaceOnChanges: [""]}` to mean other than this?

**Comment by lblackstone** [comment]
> What would you expect `{replaceOnChanges: [""]}` to mean other than this?

I'd expect it to be a no-op. I'd guess that this case would be more likely to be unintentional with a default value or similar. I just stumbled across it when I unintentionally deleted the string contents rather than the array contents on an update.

**Comment by lukehoban** [comment]
> I'd expect it to be a no-op.

It would be a little weird to me to allow this but have it be a noop.  It seems if anything we could make it an error - though I'm not 100% sure that is better.

FWIW - this is the same as the fact that `"foo"` means "the foo property or any of its children".  `""` means "the root resource or any of its children".

**Comment by lblackstone** [comment]
> `""` means "the root resource or any of its children".

Ok, that makes sense to me. I'll close this out for now, and we can reevaluate if it becomes a problem later.
