### ISSUE TITLE
Incorrect dependency handling of topic subscriptions when using ASG with lambda

### ISSUE THREAD

**Issue by maddalab** [pulumi/pulumi#7564]
I've code in the [repository](https://github.com/maddalab/pgar/) that does the following

* Subscribes to instance terminating events from an ASG
* Events are published to a SNS topic
* Lambda function listens to SNS topic to perform housekeeping and *completing* lifecycle action

During development I regularly performed `pulumi destroy`. The lambda topic subscription is deleted early on prior to ASG is deleted. When this happens events in SNS topic are not delivered to the lambda and lifecycle action is not completed. Due to the lifecycle action not being completed ASG is not drained and cannot be deleted, `pulumi destroy` will eventually fail with a time out.

I've one of two options, having specified a `CONTINUE` default for lifecycle events, I just wait for a timeout and continue to occur. Or lend a helping hand by terminating instances from the console.

Performing ec2 terminating instance house keeping requires an additional manual step. Admittedly this is only an issue during development and once the stack is stood up there will not be a reason to destroy the stack.

## Steps to reproduce

[Code](https://github.com/maddalab/pgar/blob/main/index.ts) is available to reproduce, it has a few more elements but is short enough and consistently reproduces the behavior.

Expected: 
[Lifecycle hook subscriptions](https://github.com/maddalab/pgar/blob/main/index.ts#L136) should be treated as a dependency.

Actual: 
Race conditions requiring manual intervention

**Comment by emiliza** [comment]
Haven't tried pulling your repro (will try tomorrow), but have you tried using [dependsOn](https://www.pulumi.com/docs/intro/concepts/resources/#dependson) @maddalab ? Curious if that solves this for you.

**Comment by lukehoban** [comment]
@maddalab  As @emiliza suggested, you can use `dependsOn` to address this.  I believe this patch will fix the problem in your example:

```diff
diff --git a/index.ts b/index.ts
index fa1f8aa..92a7910 100644
--- a/index.ts
+++ b/index.ts
@@ -115,29 +115,6 @@ const launchTemplate = new aws.ec2.LaunchTemplate("ci-cd-runner-template", {
 // create a sns topic to receive ASG lifecycle events
 const asgEventsTopic = new aws.sns.Topic("asg-events-topic");
 
-// create an ASG for ec2 instances running github runners, terminating events
-// are posted to a SNS with topic asg-events-topic. ASG is manually configured
-// for now TODO: Determine CW even criteria to scale.
-const runnerAsg = new aws.autoscaling.Group("ci-cd-runner-asg", {
-    desiredCapacity: 2,
-    maxSize: 2,
-    minSize: 1,
-    healthCheckGracePeriod: 300,
-    healthCheckType: "EC2",
-    launchTemplate: {
-        id: launchTemplate.id,
-        version: `$Latest`,
-    },
-    vpcZoneIdentifiers: vpc.privateSubnetIds,
-    initialLifecycleHooks: [{
-        name: "asg-events-hook",
-        defaultResult: "CONTINUE",
-        lifecycleTransition: "autoscaling:EC2_INSTANCE_TERMINATING",
-        notificationTargetArn: asgEventsTopic.arn,
-        roleArn: lifecycleRole.arn
-    }]
-});
-
 // lambda function than listens to ASG events and ensures EC2 instance
 // cleanly unregister themselves in github before terminating
 const cb = new aws.lambda.CallbackFunction("ci-cd-scale-in-callback", {
@@ -182,7 +159,30 @@ const cb = new aws.lambda.CallbackFunction("ci-cd-scale-in-callback", {
     }
 });
 
-asgEventsTopic.onEvent("ci-cd-scale-in", cb);
+const subscription = asgEventsTopic.onEvent("ci-cd-scale-in", cb);
+
+// create an ASG for ec2 instances running github runners, terminating events
+// are posted to a SNS with topic asg-events-topic. ASG is manually configured
+// for now TODO: Determine CW even criteria to scale.
+const runnerAsg = new aws.autoscaling.Group("ci-cd-runner-asg", {
+    desiredCapacity: 2,
+    maxSize: 2,
+    minSize: 1,
+    healthCheckGracePeriod: 300,
+    healthCheckType: "EC2",
+    launchTemplate: {
+        id: launchTemplate.id,
+        version: `$Latest`,
+    },
+    vpcZoneIdentifiers: vpc.privateSubnetIds,
+    initialLifecycleHooks: [{
+        name: "asg-events-hook",
+        defaultResult: "CONTINUE",
+        lifecycleTransition: "autoscaling:EC2_INSTANCE_TERMINATING",
+        notificationTargetArn: asgEventsTopic.arn,
+        roleArn: lifecycleRole.arn
+    }]
+}, { dependsOn: subscription });
 
 function createRole(rolePrefix: string, servicePrincipal: string, policies: [string, string][]) {
``` 

As originally written, your ASG depends on the topic, but not on the topic subscription.  The change above ensures that it depends on both.

**Comment by maddalab** [comment]
kk ty both.
