### ISSUE TITLE
Pulumi is using an archived provider for GitHub

### ISSUE THREAD

**Issue by BNBlake** [pulumi/pulumi#7570]
Looks like Pulumi is using an archived provider for GitHub. The updated one is here: [https://github.com/integrations/terraform-provider-github](https://github.com/integrations/terraform-provider-github)

**Comment by stack72** [comment]
Hi @BNBlake 

No, we are actually using the integrations one - I have a replace in the go.mod that points to a fork of the correct repo

We can't point directly at the integrations repo as they still have a module name of github.com/terraform-providers - https://github.com/integrations/terraform-provider-github/blob/main/go.mod#L1

Without this changing, we can't point to a repo with a different module name

Paul
