### ISSUE TITLE
Artifactory Provider

### ISSUE THREAD

**Issue by fitzoh** [pulumi/pulumi#7594]
There is an existing [Artifactory Terraform provider](https://registry.terraform.io/providers/jfrog/artifactory/latest), but there doesn't appear to be a Pulumi Provider.

There's already some [marketing material](https://www.pulumi.com/resources/sharing-and-reusing-infrastructure/) about using Pulumi with Artifactory, it would be nice if there was an out of the box way to manage Artifactory with Pulumi as well.

(area/providers)

**Comment by stack72** [comment]
We do have an artifactory provider now https://www.pulumi.com/registry/packages/artifactory/
