### ISSUE TITLE
Prompt for passphrase on pulumi up

### ISSUE THREAD

**Issue by logileifs** [pulumi/pulumi#7599]
When I do `pulumi login --local` and set an empty passphrase I always get this error:
```
error: constructing secrets manager of type "passphrase": unable to find either `PULUMI_CONFIG_PASSPHRASE` or `PULUMI_CONFIG_PASSPHRASE_FILE` when trying to access the Passphrase Secrets Provider; please ensure one of these environment variables is set to allow the operation to continue
```
when running `pulumi up`. I think it would be a much nicer user experience to be prompted for the passphrase instead of just having an error thrown in my face. 

I know I could avoid this by setting the `PULUMI_CONFIG_PASSPHRASE` variable but I sometimes switch between pulumi projects in the same terminal and don't want to rely on something in my env for pulumi to work.

**Comment by lukehoban** [comment]
> When I do pulumi login --local and set an empty passphrase I always get this error:

@logileifs What exactly were the steps you took that led to that error message?  Perhaps, what exactly do you mean by "set an empty passphrase"?

When I try this myself, I cannot get that error - I see this:

```
➜  other pulumi up
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
Previewing update (other-dev):
     Type                 Name             Plan
 +   pulumi:pulumi:Stack  other-other-dev  create

Resources:
    + 1 to create
```

**Comment by lukehoban** [comment]
@robwruck thanks for the repro steps - I was able to reproduce the problem with these steps, and this is indeed a bug we should address.

**Comment by justinvp** [comment]
Looks like this has been fixed as it no longer repros.
