### ISSUE TITLE
License Placeholders

### ISSUE THREAD

**Issue by johannesdrescher** [pulumi/pulumi#7602]
Just noticed that the `LICENSE` file only contains the placeholders for `[year]` and `[name of copyright owner]` and not the real deal. For all I know this could be intentional, I'm not a lawyer. I wanted to bring it to your attention anyway in case it is not.

https://github.com/pulumi/pulumi/blob/81f87b0c6ac5a2b52268b46599affdf79d9e6db7/LICENSE#L190

**Comment by stack72** [comment]
Hi @johannesdrescher 

Thank you for pointing this out / this is something I will get rectified across all affected repos starting tomorrow!

Paul

**Comment by stack72** [comment]
Hi @johannesdrescher 

After further research - this is actually only part of the license text to tell people how to apply the license to each file

So there is no work to do here

Sorry for my confusing response above

Paul

**Comment by johannesdrescher** [comment]
Hi @stack72, 

Apologies, I should have read the context before opening the issue. Hope this didn't take up much of your time.

Johannes

**Comment by stack72** [comment]
Not at all - when it comes to licensing it's always best to make sure everything is covered :) thanks so much for being diligent here and checking with us
