### ISSUE TITLE
Allow the CLI to query current update "status"

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#762]
Now that we support cloud deployments in the CLI, it would be nice to be able to query the current update status (in addition to [update history](https://github.com/pulumi/pulumi/issues/636)).

More than that, however, we should let a user reconnect to an existing deployment.  This would allow users to view the status of an ongoing update (e.g., maybe kicked off in Travis), or resume their own deployment in the event something happened (machine crash, accidental ^C, network outage, ...). 

For example, perhaps a `pulumi status --tail` or `--watch-latest` or somesuch.

**Comment by ellismg** [comment]
The ability to remotely monitor an update is now provided by the service itself (on app.pulumi,com) and that seems good enough to close this.  Given our current deployment model where the deployment happens on your local machine, attaching to and following an existing deployment doesn't seem like it is high enough value to go after.
