### ISSUE TITLE
Support parallel construct requests for nodejs multi-lang components

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#7629]
For stability and due to global state issues in the nodejs runtime, we serialized MLC construct requests in https://github.com/pulumi/pulumi/pull/6452

This has some obvious downsides like not creating cloud resources in parallel if you are instantiating multiple instances of the same component in a program. 

Will require some of the same set of work as https://github.com/pulumi/pulumi/issues/5449 to remove global state from the nodejs runtime.

**Comment by mikhailshilkov** [comment]
Yes, I think this is still an issue and is indeed causing serialized deployments in awsx: https://github.com/pulumi/pulumi/blob/6cfa4afcaf1d8ff12dfce91b36d5abd30a9aaa11/sdk/nodejs/provider/server.ts#L275-L280

**Comment by denis-tierno-lc** [comment]
Just for visibility's sake, this is a deal breaker for my deployment. My app spawns 15 services, and they are kinda slow, so it takes almost one hour for a deployment to complete.

**Comment by justinvp** [comment]
I suspect this should be a relatively easy to fix. We already made the changes in the Node.js SDK to avoid the global state issue for Automation API, we just hadn’t gone back to change the provider code to no longer serialize `Construct` and `Call` calls.

**Comment by mikhailshilkov** [comment]
@justinvp Great! Is it just a matter of removing the serialization? What is the testing that we would need to add?

**Comment by t0yv0** [comment]
Another iteration planning, still very interested in this for AWS, could possibly even take it on with some quick guidance. CC @mjeffryes
