### ISSUE TITLE
`gcp.cloudrun.GetServiceResult.statuses`: Why is this an array?

### ISSUE THREAD

**Issue by cakoose** [pulumi/pulumi#7634]
1. I want to get the URL for my Cloud Run service.
2. Using `gcp.cloudrun.getService(...)`, I get a `gcp.cloudrun.GetServiceResult`.
3. That object has a `statuses` field, which is an `Array<GetServiceStatus>`, each with a `url` field.

I'm wondering why this is not just a single `status`.
- The GCP RPC API's [`GetService`](https://cloud.google.com/run/docs/reference/rpc/google.cloud.run.v1#google.cloud.run.v1.Services.GetService-table) call returns a [`Service`](https://cloud.google.com/run/docs/reference/rpc/google.cloud.run.v1#google.cloud.run.v1.Service) object, which has a single `status`.
- The Terraform equivalent also has a single status: [docs](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#attributes-reference).

Am I missing something?

My current workaround is to just assert that `statuses.length === 1` and then use `statuses[0]`.

**Comment by stack72** [comment]
Hi @cakoose 

Sorry that this is causing issues here - we codegen against the google-beta schema and it has status as a List with no MaxItems so as part as we are concerned, it may have more than 1 status returned...

https://github.com/hashicorp/terraform-provider-google-beta/blob/master/google-beta/resource_cloud_run_service.go#L680

We can add a MaxItems 1 but this could be a breaking change

Paul

**Comment by cakoose** [comment]
Ah, got it.  Even if this can't be fixed quickly, what's the right way to get the ball moving on this?  Submit a `MaxItems=1` patch to the terraform-provider-google-beta and terraform-provider-google repos?

(I actually vaguely remember this issue now.  When writing a Terraform plugin a few years ago, I was annoyed to find that only lists can have nested fields!  Makes it really easy to forget to set `MaxItems=1`, I guess...)

**Comment by cakoose** [comment]
Also, looks like `status` is defined correctly in the Pulumi "Google Native" plugin: [docs](https://www.pulumi.com/docs/reference/pkg/google-native/run/v1/service/#inputs).  Looking forward to that coming out of preview!

(Since I have a workaround, I'll probably stick with the old plugin for now.)

**Comment by cakoose** [comment]
I opened an issue on the Terraform plugin's bug tracker about setting `MaxItems: 1`: https://github.com/hashicorp/terraform-provider-google/issues/9771

**Comment by cakoose** [comment]
@stack72: It appears that Terraform does not allow setting `MaxItems` on `Computed: true` attributes: [v2 upgrade guide](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#stronger-validation-for-helper-schema-schema-computed-fields)

Apparently the previous Terraform GCP plugin used to have `MaxItems: 1` on the `status` field ([link](https://github.com/hashicorp/terraform-provider-google-beta/blame/858167e3bf28e4f2fd111d8cb8b17521ef2156f7/google-beta/resource_cloud_run_service.go#L250)), but they removed it.

Since Terraform is untyped, this doesn't really affect them that much.  With Pulumi and TypeScript though, the problem is more apparent.  Is there any way to specify overrides for the Pulumi codegen?

**Comment by yehudamakarov** [comment]
happy i found this, i'm trying to assert a cloud run service only has 1 URL and can't figure out how to do that using the `go` package
