### ISSUE TITLE
AWS Cloudfront Distribution: Support Trusted key groups argument

### ISSUE THREAD

**Issue by patrick1011** [pulumi/pulumi#7636]
AWS CloudFront now supports the ability to create public keys and a Trust Key Group which can be used as a signer for CloudFront signed URLs and cookies. Historically you had to use a key pair that was created by the root account user.

The current AWS Pulumi provider appears to support the creation of a CloudFront Public Keys and Key Groups, but (as far as I can see) does not support using that Trusted Key Group in the arguments to a distribution.

Terraform recently added this feature (https://github.com/hashicorp/terraform-provider-aws/pull/18644).

**Comment by stack72** [comment]
Hi @patrick1011 

This has actually been available since pulumi-aws v4.0.0 release - are you not seeing this in there? I can see it in `DistributionOrderedCacheBehavior` as `trustedKeyGroups` - it's a []string

Please let me know if you can't see the same here

Paul

**Comment by patrick1011** [comment]
Hey @stack72 ,

Whoops - somehow missed this in `DistributionOrderedCacheBehavior`.

Thanks for your time.

Patrick

**Comment by stack72** [comment]
> Hey @stack72 ,
> 
> Whoops - somehow missed this in `DistributionOrderedCacheBehavior`.
> 
> Thanks for your time.
> 
> Patrick

Good news! thanks for getting back to me so fast!
