### ISSUE TITLE
"error: could not deserialize deployment"

### ISSUE THREAD

**Issue by brainoutsource** [pulumi/pulumi#7658]
I've been using pulumi stack for my AWS infra deployment for a few months, but today `pulumi up` just hangs for 10 minutes and then fails with the following error:

```
error: could not deserialize deployment: decrypting secret value: performing HTTP request: Post "https://api.pulumi.com/api/stacks/MY_USER/MY_PROJECT/MY_STACK/decrypt": stream error: stream ID 29; PROTOCOL_ERROR
```

I'm running Pulumi version 3.8.0.

Is there any workaround for this?

Thank you!

**Comment by brainoutsource** [comment]
This error was persistent for a couple of hours, and then it just disappeared.

**Comment by emiliza** [comment]
@brainoutsource thanks for reporting!  Looks like our service was having issues at this time - apologies for that inconvenience, we'll be investigating to prevent this from occurring again

**Comment by emiliza** [comment]
Closing this out since this is resolved now. Thanks again for reporting this issue! :)
