### ISSUE TITLE
Test provider inputs for Check, Diff, etc.

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#766]
As a follow-up for the changes in #761, we should add better tests for expected inputs, etc. in the various provider functions. This turns out to be surprisingly tricky, as it really ought to use the actual provider interface and managing state with the dynamic provider is not always straightforward for various reasons.

**Comment by pgavlin** [comment]
This is _finally_ doable in a realistic fashion now that we've improved the testability of the engine.

**Comment by mikhailshilkov** [comment]
I'm slowly going through older issues... This one isn't user-facing and has been open for 4 years without any action - so I'll go ahead and close it thinking it has no real value anymore.
