### ISSUE TITLE
Properties are typed Any disabling type checking

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#7679]
Typechecking with MyPy is disabled for properties. This leads to runtime issues and panics such as https://github.com/pulumi/pulumi/issues/7132

## Steps to reproduce

```
from pulumi_aws import secretsmanager

secret = secretsmanager.Secret(resource_name='secret_name')
reveal_type(secret)
reveal_type(secret.arn)
```

Run `mypy .`

Expected: secret.arn typed as Output[str].

Actual:

```
__main__.py:4: note: Revealed type is 'pulumi_aws.secretsmanager.secret.Secret'
__main__.py:5: note: Revealed type is 'Any'
```

**Comment by t0yv0** [comment]
I've moved it from pulumi-aws and let's consider prioritizing this. Just was discussing this with a user in #python community slack.

**Comment by wimax-grapl** [comment]
For what it's worth, PEP612's ParamSpec makes type-annotating these decorators way easier. Mypy supports it as of 0.930

**Comment by arusahni** [comment]
This also impacts `pulumi_aws.s3.BucketV2`:

```python
bucket = aws.s3.BucketV2("bucket-name")
reveal_type(bucket.arn):  # Type of "bucket.arn" is "Any"
```

**Comment by julienp** [comment]
This was fixed in https://github.com/pulumi/pulumi/pull/15865

Running the bucket or secrets manager examples I get 
```
Revealed type is "pulumi.output.Output[builtins.str]
```
