### ISSUE TITLE
Update resource getter methods support Input<>.

### ISSUE THREAD

**Issue by brion-fuller** [pulumi/pulumi#7680]
In my use case, when creating an azure container registry there are credentials that are automatically generated for you.  In order to obtain these credentials for other parts of deployment, I current need to do something like this.
```
const registryCredentials = pulumi
  .all([containerRegistry.name, resourceGroupName])
  .apply(([registryName, resourceGroupName]) =>
    getRegistryCredentials({
      registryName,
      resourceGroupName,
    })
  );
```

This seems like this could be avoid and cleaner to accept Input<> types and end up being.
```
const registryCredentials = 
    getRegistryCredentials({
      registryName: containerRegistry.name,
      resourceGroupName,
    });
```

## Affected feature

Codegen for nodeJs.

**Comment by filip-zyzniewski** [comment]
This discussion seems related: https://pulumi-community.slack.com/archives/CJ909TL6P/p1627568493243600

**Comment by lukehoban** [comment]
This is being tracked in https://github.com/pulumi/pulumi/issues/5758 and is something we are working on designing/solving currently.
