### ISSUE TITLE
Unable to import GCP Compute Instance or change providers

### ISSUE THREAD

**Issue by rynslmns** [pulumi/pulumi#7697]
We were trying to update our Providers to use the default providers. In doing so, we ran into a number of issues. The two main issues were:

1. We seemed to run into a bug when trying to import a GCP instance
2. We ran into difficulties trying to change providers, specifically when using Helm.

## Steps to reproduce
- To avoid destroy/recreate, we attempted to use aliases for gcp provider. This did not work as the preview showed that the resources would be replaced.
- Manually deleting the resource from the pulumi state and reimporting that resource using pulumi import failed as the gcp compute instance resource failed to import.
- We found exporting the state, and updating the URNs for the provider would work around the failed import issue, however, the URN for a new provider is not known for a new provider we want to introduce for an upgrade.
- Could not figure out the URN for a new default provider without first using that provider.
 - Import of gcp.compute.Instance failed
    - Import failed due to error; partial error
 ```
problem: ConflictsWith: "boot_disk.0.disk_encryption_key_raw": conflicts with boot_disk.0.Kms_key_self_link.
      Examine values at 'Instance.BootDisk.DiskEncryptionKeyRaw'.
      
```

- There was another conflict error with nicType expecting value of GVNIC, VIRTIO_NET
- Default values for the boot disk encryption and the network type
- Unable find nicType in gcp instance preventing us from entering a matching value

**Comment by leezen** [comment]
> To avoid destroy/recreate, we attempted to use aliases for gcp provider. This did not work as the preview showed that the resources would be replaced.

This should be fixed as of https://github.com/pulumi/pulumi/pull/7166

> Manually deleting the resource from the pulumi state and reimporting that resource using pulumi import failed as the gcp compute instance resource failed to import.

I assume this is the error you later show below in your description. Was this done via resource option (https://www.pulumi.com/docs/guides/adopting/import/#pulumi-import-resource-operation) or the CLI?

> Unable find nicType in gcp instance preventing us from entering a matching value


Do you mean finding the set of enumerable values for this was an issue? Just want to make sure I understand what went wrong from your perspective.

**Comment by mikhailshilkov** [comment]
There seem to be several issues in one here, but I'll treat it as a purely import issue for clarity.

Import functionality has been significantly refactored in #8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
