### ISSUE TITLE
Diff in the CLI different from diff in the Pulumi Service

### ISSUE THREAD

**Issue by filip-taxamo** [pulumi/pulumi#7709]
Our CI/CD setup has run `pulumi preview --diff`

## Steps to reproduce

1. run `pulumi preview --diff`.
2. compare the output in CLI to the diff in the web UI
3. raise eyebrows

Expected: 

Diff in the CLI matches the diff in the web UI

Actual:

CLI output:

(View Live: https://app.pulumi.com/taxamo/infrastructure-common-production/production/previews/d4972798-f398-44f1-a7c1-3b1af3d99520)

![image](https://user-images.githubusercontent.com/84842146/128321469-66ad55f3-1491-4670-af61-50328e1f68c9.png)

Web UI:

![image](https://user-images.githubusercontent.com/84842146/128321967-b870556a-b629-46d1-ba39-484d36fba09b.png)

Observe the lack of `+ policy     : "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"secretsmanager:GetSecretValue\",\n      \"Resource\": \"*\",\n      \"Principal\": {\n        \"AWS\": \"arn:aws:iam:[...]\"\n      }\n    }\n  ]\n}"`

in the web UI.

**Comment by filip-zyzniewski** [comment]
Also happened with a subsequent preview on the same code: https://app.pulumi.com/taxamo/infrastructure-common-production/production/previews/476af854-5ff2-482a-bba3-1adca6013d05

**Comment by filip-taxamo** [comment]
Also happened with a subsequent preview on the same code: https://app.pulumi.com/taxamo/infrastructure-common-production/production/previews/476af854-5ff2-482a-bba3-1adca6013d05

And with the actual update: https://app.pulumi.com/taxamo/infrastructure-common-production/production/updates/20 .

**Comment by justinvp** [comment]
The code that rendered the diff in Pulumi Cloud used to be quite different from the CLI. That's since been addressed. I believe this is now fixed in Pulumi Cloud.
