### ISSUE TITLE
go program generation is non-deterministic

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#7713]
For me ~one in 10 test runs fail due to some non-determinism in the go codegen. I think this is due to unstable iteration of union and other types/maps. I would not be surprised if this impacts other languages as well.

**Comment by emiliza** [comment]
@EvanBoyle can you provide links to some of the failures?

**Comment by EvanBoyle** [comment]
Ok a simple script to compute failures:

```bash
total_runs=100
fails=0
succeeds=0

for (( c=0; c<=$total_runs; c++ ))
do
  go test github.com/pulumi/pulumi/pkg/v3/codegen/go -run TestGenerateProgram -count=1 && succeeds=$((succeeds+1)) || fails=$((fails+1))
done

success_rate=$succeeds/$total_runs
echo "Success rate: $success_rate"
```

Results for 100 runs: `Success rate: 93/100`

It looks like all of the failures are related to https://github.com/pulumi/pulumi/blob/master/pkg/codegen/internal/test/testdata/azure-native.pp which is currently disabled in master

I am seeing these issues working on https://github.com/pulumi/pulumi/pull/7711 which re-enables that test. So I suppose this blocks https://github.com/pulumi/pulumi/pull/7711 from moving forward but is not "technically" a CI flake and might not deserve the p1 label. To be clear, 7711 does not introduce this issue, it just highlights it be enabling a test.

**Comment by EvanBoyle** [comment]
Ran the command for each of `go` `dotnet` `nodejs` and `python` on master and confirmed 100/100 success rate for program generation. Going to remove the P1 label.

**Comment by justinvp** [comment]
I can't repro any non-determinism. I tried running the script above and there were no failures.
