### ISSUE TITLE
Create stack with same name per project

### ISSUE THREAD

**Issue by Rugal** [pulumi/pulumi#7728]
![image](https://user-images.githubusercontent.com/1812023/128763966-c663cf41-967b-4b20-af3e-15bbd350e114.png)

From official document I can see project is a big thing and stack is specific to environment, so let's say if I have project `A`, it can have multiple enviroments like `dev`, `qa`, `prod` etc.,
And I have multiple projects now, each can have `dev` and `qa` itself, so I want to create stack with the same name under different project(they have their own `Pulumi.yml` file respectively)

When I try to do so, I get 

```
stack name: (dev)
Sorry, could not create stack 'dev': stack 'dev' already exists
```

## Steps to reproduce

1. create project `test1`, with stack name `dev`
    ![image](https://user-images.githubusercontent.com/1812023/128764252-0fed3556-f4d2-4fe4-8897-ce827c62181f.png)

2. ls all available stacks
    ![image](https://user-images.githubusercontent.com/1812023/128764415-238660b7-2bb4-4d3e-ab16-7ad0c22e8f52.png)

3. create another project `test2`
    You can see this time, the stack creation is failed as `dev` is already used
    ![image](https://user-images.githubusercontent.com/1812023/128764467-741269a8-13e0-44cd-bc8f-ac1a250c89d7.png)

Expected:  To create stack with same name, in different project
Actual: The stack name seems to be globally unique

**Comment by emiliza** [comment]
Thanks for reporting!  Was able to repro this on a local and GCS backend.

You could work around this issue by switching where each project's state is stored, eg: instead of generic `gs://foo` (which appears to be reading as global) have subdirs of `gs://foo/test1` and `gs://foo/test2` and `pulumi login gs://` to each of those as you work between projects.  Not ideal, but should work.

**Comment by Rugal** [comment]
Hi @emiliza ,

After some discussion in Slack, we found that only `Pulumi Service` supports this feature, and other backends do not.
The only way to work it through it to set the BACKEND url like what you mentioned above. But doing so would lost the ability to use `StackReference`.

This is understandable but should be documented clearly in official website.

**Comment by Rugal** [comment]
The only thing I would like to point out is that, this feature is only available in `pulumi service`, and this should have been documented clearly, in case others misunderstand it going forward.

issue closed.

**Comment by silasdavis** [comment]
Why is this closed? It makes very little sense to have non-pulumi backends to have different namespacing rules with project.

That is stack names should only need to be unique within projects, like with the hosted service.

**Comment by Frassle** [comment]
This is a duplicate of https://github.com/pulumi/pulumi/issues/2522
