### ISSUE TITLE
Consider exporting the `runPulumiCmdSync` method

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#7743]
In some situations, there are command line flags that aren't available on [this](https://github.com/pulumi/pulumi/blob/013036064f8a49fca6842179a40e005da06a806a/sdk/go/auto/local_workspace.go#L529) method.

If there is lag between automation API features and and the CLI options, it could be useful to export the method so downstream automation API users have the flexibility to implement themselves

**Comment by EvanBoyle** [comment]
Going to close this out, the solution here is to expose the underlying flag as a part of the API and not to make internals of automation api (which could change) public
