### ISSUE TITLE
Add `RetainOnDelete` resource option

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#7747]
There are many cases where it is useful or necessary to allow a resource managed by Pulumi to be kept around when the Pulumi resource managing it is deleted (including when the stack it is part of is destroyed).  For example:
1. A database or persistent storage that is created by Pulumi, but which should be intentionally retained when the Pulumi stack that created it is destroyed, allowing for manual processes to deprovision, backup and/or migrate the backing data
2. Resources imported into a Pulumi program but still "owned" by some external system, which should not be destroyed as part of the Pulumi stack lifecycle
3. Resources that have been removed from a backing cloud provider, but where the resource provider does not cleanly treat this as a deletion, where the user wants to indicate they are okay with removing the resource without requiring that the resource provider's destroy operation is run

One way to support this would be a `retainOnDelete: true` resource option, which when set to true causes the resource provider `Destroy` operation to not be executed, instead just implicitly succeeding whenever a destroy on the resource is needed (including during a replace).

**Comment by t0yv0** [comment]
Copying slack comment from @Frassle 

```

I've updated https://github.com/pulumi/pulumi/pull/8746, there's one question on there of if we want to take this further by spliting the behaviour flag into "onDeleteBehaviour" and "onReplaceBehaviour" or if we handle both via one enumeration. The current and possible set looks like:

+-----------+------------+-----------+
| Behaviour | On replace | On delete |
+-----------+------------+-----------+
| Delete    | Delete     | Delete    |
+-----------+------------+-----------+
| ?         | Block      | Delete    |
+-----------+------------+-----------+
| ?         | Drop       | Delete    |
+-----------+------------+-----------+
| Protect   | Delete     | Block     |
+-----------+------------+-----------+
| ?         | Block      | Block     |
+-----------+------------+-----------+
| ?         | Drop       | Block     |
+-----------+------------+-----------+
| ?         | Delete     | Drop      |
+-----------+------------+-----------+
| ?         | Block      | Drop      |
+-----------+------------+-----------+
| Drop      | Drop       | Drop      |
+-----------+------------+-----------+

Some of those look like they might be useful, like (Block, Block) = ProtectReplacements. Others seem a bit odd like (Delete, Drop) but maybe people would have a use for them?
```

**Comment by t0yv0** [comment]
Does `Block` aka 'DeleteBehavior=Protect' overlap with https://www.pulumi.com/docs/intro/concepts/resources/options/protect/ or is it somehow different?

Do we have specific use cases in mind where the user wants replace-driven deletions and delete-driven deletions to have a different strategy? Running quite a bit ahead here of what's being asked for in the ticket, so I am wondering if we know examples where this would be super useful.

**Comment by t0yv0** [comment]
I'm wary that generalizing over what's being asked for here may be premature, as we just need a convenient way to solve this particular problem, but this got me thinking so I'm going to log it here. Perhaps what's asked can be thought of as a provider transformation overriding how the provider interprets the delete effect, for a specific resource, e.g. wrapper over: 

```
    // Delete tears down an existing resource with the given ID.  If it fails, the resource is assumed to still exist.
    rpc Delete(DeleteRequest) returns (google.protobuf.Empty) {}
```

If Pulumi power users could add custom options into the ResourceOption bag and could transform provider implementations, these together give sufficient power to do RetainOnDelete or protect/throw an exception (though perhaps not the convenience of an official option).

I'm curious now how deep the provider resource option goes (https://www.pulumi.com/docs/intro/concepts/resources/providers/), can I already wrap an AWS provider in some custom code re-interpreting Delete requests.

**Comment by Frassle** [comment]
> Does Block aka 'DeleteBehavior=Protect' overlap with https://www.pulumi.com/docs/intro/concepts/resources/options/protect/ or is it somehow different?

It's intended as a replacement for protect. Working on this it looked like we could end up with a proliferation of flags that would conflict with each other, or just move all delete behavior to be tracked by one setting.

> I'm wary that generalizing over what's being asked for here may be premature, as we just need a convenient way to solve this particular problem

The most specific way to solve this problem is to add another bool flag "retainOnDelete" and if that's true when we delete something it's a no-op delete. One fun thing is to keep in mind that for a "Delete" we only have an old state but for a "Replace" there's the old state and new state to consider. "protect" for example lets you unprotect with the new goal state and cause the old one to be deleted via a replace (even though the resource state being deleted had protect=true).

Trying to reason about this with two bool flags is `old.Protect * new.Protect * old.Retain * new.Retain + old.Protect * old.Retain (2*2*2*2+2*2 = 20)` states, with the one behavior setting it's `old.Behaviour * new.Behaviour + old.Behaviour (3*3+3 = 12)` states.

If we add another mode in the same way this becomes 72 and 20 states. 

> Do we have specific use cases in mind where the user wants replace-driven deletions and delete-driven deletions to have a different strategy? 

Yes. You might want to allow replacements but not allow complete deletions. Currently you have to do a little dance where you unset the protect bit before running up. Once you have that you start wondering if those replacements should be deletes or drops, and then you have all the fun of above when new and old disagree. 

> provider transformation overriding

Given how we have to handle destroy and all the pain that dynamic providers has brought I'm really not keen on adding more magic like that.

**Comment by lukehoban** [comment]
> I'm wary that generalizing over what's being asked for here may be premature, as we just need a convenient way to solve this particular problem

I share this feeling as well, especially since we have existing precedence around options here, and some of the generalizations would lead to some awkward overlap with existing options.  The "simple" intents that users might have seem to also end up with more esoteric forms of expression under this generalized proposal - effectively the API seems to be more generic, but somewhat less clear.

> We'd like to warn the user that a resource has been dropped but not deleted. It's pretty easy to do this on the one up that drops the resource (we can just print a diag message from the delete handler) but we thought it might be better to be more explicit and keep track of "dropped" resources in a separate part of the state file. We could then warn on every up that a resource isn't being tracked by pulumi until the user explicitly okays this with something like pulum stack disregard <id>

I'm not sure we want to do all of this.  In particular, I don't think we should warn in any case after a user has explicitly opted-in to this.  In the scenarios where this is really needed, it's totally intentional and not a warning for this to do what the user asked for.  It's also not something we would want to require any manual intervention - the point of having the flag is to make this easy to describe correctly in automation.  I don't even think we should store this in the state file - that could quickly become a lot of not useful data.  It's largely the same as the ids of deleted resources, which we don't keep around.  In this case, the user similarly has clearly indicated they don't want to keep these around.

**Comment by Frassle** [comment]
Lets stick with bool flags for now then. I've reworked https://github.com/pulumi/pulumi/pull/8746 to just have a "RetainOnDelete" bool option. If that's true on a resource state we don't call the provider Delete, there's no diagnostic message about this.

**Comment by Frassle** [comment]
> One remaining question on your PR is that it seems to persist the RetainOnDelete in the statefile.

I inferred Luke's comments to be about persisting that we did the drop in the state file. The flag itself has to go in the state file as that's the only data source we have when doing Deletes/Destroys.
