### ISSUE TITLE
Pulumi Python issues on Nix OS

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#7754]
Receiving reports of ImportError when using Pulumi python on NixOS:

```
ImportError: /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libc.so.6: version `GLIBC_2.33' not foun│
d (required by /nix/store/lg104nh0szci8slz5z6494m457jm5y3p-gcc-10.3.0-lib/lib/libstdc++.so.6)  
```

For example https://github.com/NixOS/nixpkgs/pull/131979#issuecomment-897486600

## Steps to reproduce

TBD.

**Comment by t0yv0** [comment]
First some good news. Basic python-gcp template works with pulumi up on Nix OS:

```
# VirtualBox appliance https://nixos.org/download.html#nixos-virtualbox
$ nixos-version
21.05.2438.927ce1afc1d (Okapi)

$ nix-channel --add https://nixos.org/channels/nixos-unstable
$ nix-channel --update
$ nix-env -i pulumi
$ pulumi version
3.9.0
$ nix-env -i python3-3.9.6
$ nix-env -i google-cloud-sdk
# configure Google cloud per https://www.pulumi.com/docs/intro/cloud-providers/gcp/setup/
$ mkdir myproj
$ cd myproj
$ pulumi new gcp-python
$ pulumi up --yes
```

**Comment by t0yv0** [comment]
However under the same Nix OS setup, using `pulumi` package from a venv fails:

```
$ mkdir simple-py
$ cd simple-py
$ python -m venv venv
$ source venv/bin/activate
$ python -m pip install pulumi
$ python -c 'import pulumi'
# ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory

```

**Comment by t0yv0** [comment]
The issue is really with grpcio:

```
$ mkdir simple-grpcio
$ cd simple-grpcio
$ python -m venv venv
$ source venv/bin/activate
$ python -m pip install grpcio
$ python -c 'import grpc'

[demo@nixos:~/simple-grpcio]$ python -c 'import grpc'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/demo/simple-grpcio/venv/lib/python3.9/site-packages/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
(venv) 
```

**Comment by t0yv0** [comment]
It appears that it is easy to install system-wide `grpcio` packages on Nix OS and those work; however when using `virtualenv` isolation inside the venvs the import error persists. The simplest workaround is getting the right LD_LIBRARY_PATH. For example, we can describe a shell in `shell.nix`:

```
# shell.nix
{ pkgs ? import <nixpkgs> {} }:

pkgs.mkShell {
  name = "pulumi-compatible-python-env";
  buildInputs = [];
  src = null;
  shellHook = ''
    export LD_LIBRARY_PATH=${pkgs.lib.makeLibraryPath [pkgs.stdenv.cc.cc]}
  '';
}
```

And then activate it:

```
$ nix-shell shell.nix
[nix-shell:~]$ env | grep LD_LIB
LD_LIBRARY_PATH=/nix/store/dzaadhn5y56da24635icafv1nrawxm4n-gcc-10.3.0-lib/lib
shellHook=export LD_LIBRARY_PATH=/nix/store/dzaadhn5y56da24635icafv1nrawxm4n-gcc-10.3.0-lib/lib
```

Then we can import gprc and pulumi from within a venv:

```
./venv/bin/python -c 'import pulumi'
```

**Comment by t0yv0** [comment]
Notes: the reason `pulumi` itself magically works, but manual python venvs don't, is probably because of https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/admin/pulumi/default.nix#L21 LD_LIBRARY_PATH modification built into the Pulumi derivation on nixpkgs.

**Comment by aureq** [comment]
> 
> 
> It appears that it is easy to install system-wide `grpcio` packages on Nix OS and those work; however when using `virtualenv` isolation inside the venvs the import error persists. The simplest workaround is getting the right LD_LIBRARY_PATH. For example, we can describe a shell in `shell.nix`:
> 
> ```
> # shell.nix
> { pkgs ? import <nixpkgs> {} }:
> 
> pkgs.mkShell {
>   name = "pulumi-compatible-python-env";
>   buildInputs = [];
>   src = null;
>   shellHook = ''
>     export LD_LIBRARY_PATH=${pkgs.lib.makeLibraryPath [pkgs.stdenv.cc.cc]}
>   '';
> }
> ```
> 
> And then activate it:
> 
> ```
> $ nix-shell shell.nix
> [nix-shell:~]$ env | grep LD_LIB
> LD_LIBRARY_PATH=/nix/store/dzaadhn5y56da24635icafv1nrawxm4n-gcc-10.3.0-lib/lib
> shellHook=export LD_LIBRARY_PATH=/nix/store/dzaadhn5y56da24635icafv1nrawxm4n-gcc-10.3.0-lib/lib
> ```
> 
> Then we can import gprc and pulumi from within a venv:
> 
> ```
> ./venv/bin/python -c 'import pulumi'
> ```

@t0yv0 I think you have the temporary fix in the form of injecting `LD_LIBRARY_PATH` into nix-shell. Depending on other pulled python libraries, the path may require further expansion onto other needed libraries.

**Comment by junkangli** [comment]
I have also encountered the error reported in https://github.com/pulumi/pulumi/issues/7754#issue-969353939. And this is actually different from the one in https://github.com/pulumi/pulumi/issues/7754#issuecomment-897904087. I tried the workaround fix suggested above, but still face the original issue.

One thing I observed from @t0yv0 trail of posts is that his approach to running Pulumi Python program is to activate a `nix-shell` and run from within a `venv`. I am thinking that `nix-shell` would have already provided the isolated virtual environment to run Pulumi Python, so it does not make sense to run it in `venv`, which will now be on top of `nix-shell`.

**Comment by t0yv0** [comment]
That's true I have not been able to reproduce the original issue yet.

About venvs: that is true, it should be possible to manage python packages with Nix (instead of venv). Note that default configurations for Pulumi templates create v-envs anyway, though I believe this can be opted out of in editing Pulumi.yaml and removing venv-related options. 

Let me dig some more and try to get to the actual issue you all are having.

**Comment by t0yv0** [comment]
A few more findings. Opting out of venv in Pulumi works, mostly, except there is a problem. In projects that control the python environment with Nix (such as with poetry2nix) and opt out of Pulumi venv support, the LD_LIBRARY_PATH env var setting in `pulumi` wrapper introduces issues. It breaks Python `grpc` library, even when it is installed and working via a Nix package. 

I have made a little branch that makes the LD_LIBRARY_PATH customization optional:

https://github.com/t0yv0/nixpkgs/tree/t0yv0/pulumi-make-ld-library-path-editing-optional

Here is a nix expr that builds `pulumi` while opting out of the LD_LIBRARY_PATH edit:

```
{}:

let

  # This may eventually become just <nixpkgs> if the patch gets merged.
  patchedNixPkgs = builtins.fetchTarball {
    name = "nixpkgs-with-preserveLdLibraryPath-pulumi-option";
    url = https://github.com/t0yv0/nixpkgs/archive/3e3c0d466e438a24b009295a64df55bf6775accc.tar.gz;
    sha256 = "0b8brv2f8fl4myd5q814mn8qv4yk2pvda30fcpqnkfqhiw4h69ph";
  };
  pkgs = (import patchedNixPkgs) {};

in pkgs.pulumi-bin.override { preserveLdLibraryPath = true; }
```

One could also do this to not only override pulumi-bin, but override anything in nixpkgs that depends on pulumi-bin (though I do not think there is anything):

```
{}:

let

  # This may eventually become just <nixpkgs> if the patch gets merged.
  patchedNixPkgs = builtins.fetchTarball {
    name = "nixpkgs-with-preserveLdLibraryPath-pulumi-option";
    url = https://github.com/t0yv0/nixpkgs/archive/3e3c0d466e438a24b009295a64df55bf6775accc.tar.gz;
    sha256 = "0b8brv2f8fl4myd5q814mn8qv4yk2pvda30fcpqnkfqhiw4h69ph";
  };

  # Now configure `pulumi-bin` to avoid setting LD_LIBRARY_PATH.
  pkgs = import patchedNixPkgs {
    config = {
      packageOverrides = pkgs: {
        pulumi-bin = pkgs.pulumi-bin.override { preserveLdLibraryPath = true; };
      };
    };
  };

in pkgs.pulumi-bin
```

If this is of interest I can submit a PR to nixpkgs.

**Comment by mudrii** [comment]
@t0yv0 This could be great if this can be implemented in main for pulumi-bin

**Comment by t0yv0** [comment]
https://github.com/NixOS/nixpkgs/pull/136304
