### ISSUE TITLE
How to delete an existing instance.

### ISSUE THREAD

**Issue by Rick6652** [pulumi/pulumi#7759]
## Get an instance on AWS
```python
import pulumi
import pulumi_aws as aws

ex_instance = aws.ec2.get_instance(instance_id="i-0ba***********a76")
```
## How to delete an existing instance？
How to use pulumi to delete an instance on AWS, what should I do?

**Comment by nesl247** [comment]
You can't delete an instance in that way. Pulumi is a stateful manager of cloud resources. If you want to delete an existing instance, it would have had to have been created or imported into pulumi, which you could then do a `pulumi destroy` with.

**Comment by joeduffy** [comment]
@nesl247 is correct. @Rick6652 please check out https://www.pulumi.com/docs/guides/adopting/import/ if you want to see how to go about first importing existing cloud resource state, so that you can bring it under the control of Pulumi.
