### ISSUE TITLE
Stack corrupted by missing zip file

### ISSUE THREAD

**Issue by MarkusKramer** [pulumi/pulumi#7765]
I once again ran into the issue that a missing ZIP file corrupted my stack
I'm using a resource like this:
```
    const functionVersion = new Function(`backend`, {
        name: `backend`,
        runtime: aws.lambda.CustomRuntime,
        code: new pulumi.asset.FileArchive("../../backend.zip"),
        handler: "not.used.in.provided.runtimei",
        role: role.arn,
        memorySize: 512,
....
    });
```

I've described the same bug before in #5988 and https://github.com/pulumi/pulumi/issues/5577#issuecomment-734386482
This time the issue was cause by relocating my pulumi code to a different directory - without adjusting above relative path to it. The next `pulumi up` failed and from this point on I was getting
```
error: .pulumi/stacks/dev-markus.json: snapshot integrity failure; refusing to use it: resource urn:pulumi:dev-markus::proj::aws:apigatewayv2/api:Api::backend dependency  refers to missing resource
```
(my AWS API gateway is referencing above lambda).

This time however manually fixing the empty string reference (as mentioned here https://github.com/pulumi/pulumi/issues/5988#issuecomment-756035901) did not fix the problem. After this fix I was getting
```
error: .pulumi/stacks/dev-markus.json: snapshot integrity failure; refusing to use it: resource urn:pulumi:dev-markus::proj::aws:apigatewayv2/api:Api::backend's dependency urn:pulumi:dev-markus::proj::aws:lambda/function:Function::backend comes after it
```

I'm on Pulumi v3.10.1.

**Comment by pgavlin** [comment]
@MarkusKramer could you share statefiles prior to an update with a missing zip file and after an update with a missing zipfile? If so, please email them to me directly.

**Comment by MarkusKramer** [comment]
I've emailed you the state files.

**Comment by pgavlin** [comment]
Just a quick update--I have the state files and this is on my radar. Thanks for sharing those, @MarkusKramer !

**Comment by pgavlin** [comment]
Finally looping back on this.

- After looking at the state files, I believe that moving the `Function` before the `Api` in the list of resources will repair the statefile
- I've tried a number of repros, and in every case I'm unable to replicate this situation, as the missing archive consistently fails the update without leaving the stack in a corrupted state. These failures all look something like:

```
Previewing update (dev)

     Type                 Name        Plan     Info
     pulumi:pulumi:Stack  gh7765-dev           1 error
 
Diagnostics:
  pulumi:pulumi:Stack (gh7765-dev):
    error: Running program 'gh7765' failed with an unhandled exception:
    Error: failed to register new resource first [pulumi-nodejs:dynamic:Resource]: 2 UNKNOWN: failed to compute archive hash for "code": open bar.zip: no such file or directory
        at Object.registerResource (gh7765/node_modules/@pulumi/pulumi/runtime/resource.js:219:27)
        at new Resource (gh7765/node_modules/@pulumi/pulumi/resource.js:217:24)
        at new CustomResource (gh7765/node_modules/@pulumi/pulumi/resource.js:309:9)
        at new Resource (gh7765/node_modules/@pulumi/pulumi/dynamic/index.js:56:9)
        at new Resource (gh7765/index.ts:16:9)
        at Object.<anonymous> (gh7765/index.ts:22:15)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Module.m._compile (gh7765/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        at Object.require.extensions.<computed> [as .ts] (gh7765/node_modules/ts-node/src/index.ts:442:12)
```

I'm really perplexed by how the state file ended up corrupted. Still digging in there.

**Comment by MarkusKramer** [comment]
Thanks for looking into it. I appreciate your support.

I believe we have never seen the error `UNKNOWN: failed to compute archive hash for "code": open bar.zip: no such file or directory` in case of a missing ZIP file with our setup. In code the Function is declared before the Api.

**Comment by lunaris** [comment]
Hi @MarkusKramer -- we've fixed a lot of snapshot integrity issues since this was raised and I'm wondering if this is something that's still affecting you/something you've seen with a recent version of Pulumi?

**Comment by MarkusKramer** [comment]
I'm not using this mechanism anymore, so I can't say. It's probably safe to close this issue.












---- On Thu, 05 Sep 2024 17:20:32 +0200 Will Jones ***@***.***> wrote ---





Hi https://github.com/MarkusKramer -- we've fixed a lot of snapshot integrity issues since this was raised and I'm wondering if this is something that's still affecting you/something you've seen with a recent version of Pulumi?

**Comment by lunaris** [comment]
No worries -- thanks for getting back to me 🙏
