### ISSUE TITLE
Failing referencing a type on azure-native schema.json

### ISSUE THREAD

**Issue by sergioalen** [pulumi/pulumi#7775]
Hello,

I'm attempting to reference a `azure-native:web:WebApp` resource on a custom component provider using the following as a template: https://github.com/pulumi/pulumi-component-provider-ts-boilerplate/blob/be03a0b1d374b72fa7aed5016315182ebf919079/schema.json with this resource ref: `"$ref": "/azure-native/v1.22.0/schema.json#/resources/azure-native:web:WebApp",`

but so far I have not been successful as every time I execute the `make generate` command I get `failed to bind properties: error binding type for property "app": failed to parse path: /azure-native/v1.22.0/schema.jsonrm -rf sdk/dotnet`

My schema.json looks as follows:
```
{
    "name": "appService",
    "resources": {
        "test:azure:WebApp": {
            "isComponent": true,
            "inputProperties": {
                "name": {
                    "type": "string",
                    "description": "Name of the app"
                }
            },
            "requiredInputs": [
                "name"
            ],
            "properties": {
                "app": {
                    "$ref": "/azure-native/v1.22.0/schema.json#/resources/azure-native:web:WebApp",
                    "description": "The app resource."
                },
                "webAppUrl": {
                    "type": "string",
                    "description": "The app URL."
                }
            },
            "required": [
                "app",
                "webAppUrl"
            ]
        }
    },
    "language": {
        "csharp": {
            "packageReferences": {
                "Pulumi": "3.*",
                "Pulumi.AzureNative": "1.*"
            }
        },
        "nodejs": {
            "dependencies": {
                "@pulumi/pulumi": "^3.0.0",
                "@pulumi/azure-native": "^1.0.0"
            },
            "devDependencies": {
                "@types/node": "^10.0.0",
                "typescript": "^3.7.0"
            }
        },
        "python": {
            "requires": {
                "pulumi": ">=3.0.0,<4.0.0",
                "pulumi_azure_native": ">=1.0.0"
            }
        }
    }
}
```

Referencing the other `azure` and `aws` provider resources work fine.

Any help would be appreciated, thanks!

**Comment by justinvp** [comment]
Looks like a problem with the following regex not being able to handle the `-` in `azure-native`:

https://github.com/pulumi/pulumi/blob/d196fc0279f3af97ed7ab7b4f417762caf3ef903/pkg/codegen/schema/schema.go#L1544
