### ISSUE TITLE
Multiple concurrent calls of automation API fail

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi#7782]
Hi,
we are using automation for changing stacks for different projects. Now when we try to update 10 stacks at the same time, some updates fail (6 stacks are updated properly) with:
```
Exception calling application: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "failed to connect to all addresses"
    debug_error_string = "{"created":"@1629267918.913166429","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3008,"referenced_errors":[{"created":"@1629267918.912664014","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
    >
```
Then when we run the rest of updates, they are updated properly. Is there some limit?

**Comment by emiliza** [comment]
How are you running Automation API, is this via inline or local program? And which language?

**Comment by jancespivo** [comment]
It runs via inline program written in Python. And to be even more complicated it is custom dynamic provider. We are using dynamic provider + automation API quite sucessfully, but sometimes we hit some weird issues like this one :)

**Comment by EvanBoyle** [comment]
@jancespivo concurrent execution of inline programs in currently not supported for python or nodejs. See https://github.com/pulumi/pulumi/issues/6052 for more details.

Your options to work around this are:

1. Use a local program and continue with parallelism as is
2. Run each parallel operation as a separate process

Closing this as a dupe of the issue linked above. Feel free to comment on https://github.com/pulumi/pulumi/issues/6052 with more details or give it a +1.
