### ISSUE TITLE
Pulumi cannot "pickle" dynamic provider

### ISSUE THREAD

**Issue by ederst** [pulumi/pulumi#7795]
After updating the python library to 3.10.2/3 I get the following error when running Pulumi:

```
     # ...
      File "/workspace/project/.venv/lib/python3.9/site-packages/pulumi/dynamic/dynamic.py", line 269, in __init__
        props[PROVIDER_KEY] = serialize_provider(provider)
      File "/workspace/project/.venv/lib/python3.9/site-packages/pulumi/dynamic/dynamic.py", line 233, in serialize_provider
      # ...
      File "/workspace/project/.venv/lib/python3.9/site-packages/dill/_dill.py", line 1410, in save_type
        StockPickler.save_global(pickler, obj, name=name)
      File "/userdir/.pyenv/versions/3.9.4/lib/python3.9/pickle.py", line 1070, in save_global
        raise PicklingError(
    _pickle.PicklingError: Can't pickle <class '__main__.ClusterProvider'>: it's not found as __main__.ClusterProvider
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

The class `ClusterProvider` is a dynamic provider located in a separate module (`providers.kops`) and is not directly used/imported in the `__main__.py`. I tried to work around this issue by doing so (putting `from providers.kops import ClusterProvider` int the `__main__.py`), but this raises another error:

```
      File "/userdir/.pyenv/versions/3.9.4/lib/python3.9/pickle.py", line 997, in _batch_setitems
        save(v)
      File "/userdir/.pyenv/versions/3.9.4/lib/python3.9/pickle.py", line 578, in save
        rv = reduce(self.proto)
    TypeError: cannot pickle '_abc._abc_data' object
```

The issue was probably introduced with https://github.com/pulumi/pulumi/pull/7755.

## Steps to reproduce
TBH, I do not know what exactly is going on and so I cannot say: "do this" to reproduce, but I can try to explain our project structure in a simplified way:

```
components/kops/
  - cluster.py
       # class KubernetesCluster(pulumi.ComponentResource) -> instantiates the Cluster resource which uses the ClusterProvider
providers/kops/
  - base.py
       # class BaseProvider(dynamic.ResourceProvider, metaclass=ABCMeta): -> basic CRUD implementation for kops stuff
       # class BaseResourceProvider(BaseProvider, metaclass=ABCMeta): -> extends CRUD for kops (yaml) manifest handling
  - cluster.py
       # class ClusterProvider(BaseResourceProvider): -> handles stuff for the cluster manifest
__main__.py
  # instantiates the KubernetesCluster component
```

When calling `pulumi up/preview` I am getting the error(s) above.

Expected: Pulumi doing it's thing
Actual: Pulumi being in a pickle

I can provide further information if needed and try to do an example project where this is happening as well, for now I am just rolling back to 3.10.1 where everything worked fine so far.

**Comment by ederst** [comment]
I have provided an example project which reproduces the issue: https://github.com/ederst/pulumi-in-a-pickle (already commented out the abstract class stuff, which cannot be pickled as well)

What seems to fix it, is to remove all the `super().__init__()` calls, like so: https://github.com/ederst/pulumi-in-a-pickle/pull/1

Hope this helps somehow.

**Comment by lukehoban** [comment]
Thanks @ederst for the repro and details.  This definitely does look like it was introduced with https://github.com/pulumi/pulumi/pull/7755, and suggests that there is a deeper issue in `dill`'s handling of non-main module resolution that the workaround there cannot handle correctly.  We'll look into what can be done to address this, or whether we need to roll back 7755 until this can be properly supported in `dill`.
