### ISSUE TITLE
Consider a declarative model and implementation for dependency information

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#7797]
Consider refactoring resource dependency computation to make the intended model more obvious and explainable in terms of the source program. 

The SDK would record base facts (graph edges) pertinent to reconstructing the dependency graph. For example:

```go

type resourceType int

const (
	ComponentResource resourceType = iota
	CustomResource
)

type newResourceDepInfo struct {
	urn               urn   // uniquely identifies the resource
	epoch             int   // >= 0, increments to track resource declaration order in the user program
	parent            *urn  // optional, declared by user code in resourceOptions
	dependsOn         []urn // explicit dependencies declared by user code in dependsOn
	inputDependencies []urn // implicit dependencies from Inputs passed to resource constructor
	resourceType      resourceType
}   
```

The "children at the time of construction" notion is modeled via the incrementing `epoch`. Make the SDK (not the engine) responsible for computing epoch and thus ordering resource constructions as close to source code order as possible. Expect the majority of Pulumi programs to register resources in a deterministic order (no resources from apply and no non-apply parallelism). For other programs we can provide some helper tooling to detect and deal with the situation, perhaps pinning the order. 

Illustration of epoch utility:

```python
a = R()               # a.epoch=0
b = R(dependsOn=[a])  # b.epoch=1, trans_deps(b) == [a]    because c.epoch > b.epoch
c = R(parent=a)       # c.epoch=2
d = R(dependsOn=[a])  # d.epoch=3, trans_deps(d) == [a, c] because c.epoch < d.epoch
```

When downstream code such as the engine receive `newResourceDepInfo` info data it can arrange it into sets `[]newResourceDepInfo` and verify that the sets are dense (consecutive `0..n` ranges of epoch), or wait until the sets are full, freeing up the transport protocols from the obligation to transmit these messages in a specified order, and providing a measure of determinism in case of out-of-order delivery.

Transitive dependency computations can then be modeled as pure functions of dense `newResourceDepInfo` sets, and tested out as needed. Since the sets are relatively small we may not need to persist or network-serialize transitive inferred deps, just the base facts.

**Comment by t0yv0** [comment]
Inspired by https://github.com/pulumi/pulumi/pull/7791/files

**Comment by t0yv0** [comment]
This does not quite cut it in case of components that return from the constructor before completing adding all the children (Helm Charts)?  Example to articulate:

```python

class R(Component):
    def __init__(self):
        self.ready = future()

        def later():
           R1(parent=self)
           # R1 is a "by-design" child as the author of R envisioned.
           self.ready.done()

        fork(later)


r = R()
C(parent=r)  # C is "out-of-band" child, the author of R has not envisoned, but the user of R adds it

# There may be a race on whether C is or is not a child of R "at the time of R.ready".
```

**Comment by t0yv0** [comment]
Idea: perhaps a deterministic model can be built by making a distinction between "by-design" and "out-of-band" children. That is, when determining the meaning for `x.depends_on(y)`, we take the union of all "by-design" children of `y` with the subset of "out-of-band" children of y at the epoch less than `x.epoch`.

**Comment by pgavlin** [comment]
> Expect the majority of Pulumi programs to register resources in a deterministic order (no resources from apply and no non-apply parallelism).

I don't think that this is a realistic expectation, to be frank. It is not uncommon for programs to effectively fork and join in their dependencies, which creates graphs that do not have a total order (only a partial order). For example, a program may create an AWS VPC, add subnets to the VPC that are not dependent on one another, and then feed the subnet IDs into e.g. a load balancer, EC2 instance, etc.

**Comment by t0yv0** [comment]
Do these programs fork and join lexically or do they fork and join in their dynamic execution? The following program you mention has a diamond desired dependency graph but it still has linearizable source declaration order.  If SDK can capture source declaration order, this information can be useful to take into account as it's very intuitive in terms of the source program.

```
vpc = VPC()
subnet1 = Subnet(vpc=vpc)
subnet2 = Subnet(vpc=vpc)
subnets = [subnet1, subnet2]
EC2Instance(subnets=subnets)
```

A program with unrecoverable lexical order is possible but is it common?

```
vpc = VPC()
subnets = []
fork(lambda: add_subnet())
fork(lambda: add_subnet())
EC2Instance(subnets=subnets)
```

**Comment by t0yv0** [comment]
I'm searching for something to pin this program basically:

```
a = R()               
b = R(dependsOn=[a])  
c = R(parent=a)
d = R(dependsOn=[a])
```

It seems that without specifying what "children at the time of .." means, this program can resolve `b` dependencies to include `c` or not include `c`. Are we saying this bit of non-determinism is desirable or else not problematic?

**Comment by t0yv0** [comment]
Retracting as outdated, awaiting new design doc on deps.
