### ISSUE TITLE
`pulumi new` for Go projects doesn't fully prepare the project's dependencies

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#7807]
Running `pulumi new azure-go` initializes the new Go project and installs dependencies:

```
This command will walk you through creating a new Pulumi project.

Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.

project name: (azurego) 
project description: (A minimal Azure Native Go Pulumi program) 
Created project 'azurego'

Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
stack name: (dev) 
Created stack 'dev'

azure-native:location: The Azure location to use: (WestUS) 
Saved config

Installing dependencies...

Finished installing dependencies

Your new project is ready to go! ✨

To perform an initial deployment, run 'pulumi up'
```

Subsequently running `pulumi up` yields the following errors:

```
Diagnostics:
  pulumi:pulumi:Stack (azurego-dev):
    main.go:4:2: missing go.sum entry for module providing package github.com/pulumi/pulumi-azure-native/sdk/go/azure/resources (imported by azurego); to add:
    	go get azurego
    main.go:5:2: missing go.sum entry for module providing package github.com/pulumi/pulumi-azure-native/sdk/go/azure/storage (imported by azurego); to add:
    	go get azurego
    main.go:6:2: missing go.sum entry for module providing package github.com/pulumi/pulumi/sdk/v3/go/pulumi (imported by azurego); to add:
    	go get azurego
 
    error: an unhandled error occurred: program exited with non-zero exit code: 1
```

Forcing you to run `go get $PROJECT` before `pulumi up` will work.

This isn't the intention. The "Installing dependencies..." step should take care of initializing the project so that `pulumi up` will work without requiring any other commands to be run first.

For Go projects, dependencies are initialized by `pulumi new` using `go mod download`. That used to be sufficient, but it looks like that's no longer the case with more recent versions of Go.

I think we can address this issue by changing `pulumi new` to use `go mod tidy` instead of `go mod download`.

**Comment by t0yv0** [comment]
Reading https://golang.org/ref/mod#go-mod-tidy we may need to tread carefully here, as `go mod tidy` literally edits `go.mod`, which might upset some users, "why is Pulumi editing my go.mod?" we might need to call this out in release notes.

**Comment by t0yv0** [comment]
By the way, was this detected by https://github.com/pulumi/templates/actions CI - it looks like it wasn't, is that because it only manifests with go toolchain upgrade and we have not upgraded that CI yet?

**Comment by justinvp** [comment]
> Reading https://golang.org/ref/mod#go-mod-tidy we may need to tread carefully here, as `go mod tidy` literally edits `go.mod`, which might upset some users, "why is Pulumi editing my go.mod?" we might need to call this out in release notes.

I was thinking about that too. I don't think we care much about it for our templates, but it is possible for someone to specify their own template URL, which could indeed change the `go.mod`. I can update the CHANGELOG to make this more clear. I'm not sure what the alternative would be if we didn't want to use `go mod tidy` -- I suppose we could run `go get <project>`, but it's not guaranteed that someone has specified the project in `go.mod` like we do in our templates.

> By the way, was this detected by https://github.com/pulumi/templates/actions CI - it looks like it wasn't, is that because it only manifests with go toolchain upgrade and we have not upgraded that CI yet?

We're currently running Go 1.15.x in the templates repo. I tried changing this to 1.16.x in https://github.com/pulumi/templates/pull/205 to see if the tests would fail, but they didn't. The reason the tests pass is because they use our [`integration.ProgramTest`](https://github.com/pulumi/templates/blob/d75cd731b95bf6ae37f47106313d6abad45a58af/tests/template_test.go#L133) which, as you know, runs `go mod tidy` as part of preparing the Go project:

https://github.com/pulumi/pulumi/blob/da2bd2ab043f2588b3a136846da1b97505326f25/pkg/testing/integration/program.go#L1948-L1952

To properly test this, we'd need to provide a new option for `ProgramTest` to opt-out of preparing the test project directory.

**Comment by t0yv0** [comment]
I found the following in release notes: https://go.dev/blog/go116-module-changes

```
In Go 1.16, module-aware commands report an error after discovering a problem in go.mod or go.sum instead of attempting to fix the problem automatically. In most cases, the error message recommends a command to fix the problem.

$ go build
example.go:3:8: no required module provides package golang.org/x/net/html; to add it:
    go get golang.org/x/net/html
$ go get golang.org/x/net/html
$ go build
As before, the go command may use the vendor directory if it’s present (see Vendoring for details). Commands like go get and go mod tidy still modify go.mod and go.sum, since their main purpose is to manage dependencies.
```

It sounds like as of 1.16 `go mod download` will shy away from editing `go.mod` and `go.sum`. 

I'd like to retract my objection, as you point out this pertains to expanding templates, whether ours or user-defined templates, in which case `go mod tidy` sounds very appropriate - let `pulumi new` fixup `go.mod` and `go.sum`, this is fine.. This is not part of `pulumi up` and would not be affecting a stack that is in prod and tries to be conservative, just new templates. Let's take your fix.
