### ISSUE TITLE
Protected ComponentResource does not prevent deletion of child resources

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#782]
My naive expectation was that setting `protect` to `true` on a `ComponentResource` would prevent the deletion of the component and all it's children.

However, we process the deletions of the children prior to the deletion of the component, so we gladly delete them before we discover and report that we cannot delete the componet, at which point we stop (after deleting all the contents of the component).

It may be that this is by design, though it is suprising.

It is of course still possible to explicitly pass the `protect` value down into child resources to ensure they are also protected.

**Comment by lukehoban** [comment]
Suggested approach to fixing this: #1736.

**Comment by swgillespie** [comment]
Closing this in favor of https://github.com/pulumi/pulumi/issues/1736, which fixes this for Node. Keeping https://github.com/pulumi/pulumi/issues/1736 open to track landing this in Python and Go.
