### ISSUE TITLE
Cannot Retrieve Array Value from Configuration When Configuration is Set in PULUMI_CONFIG Environment Variable

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#7827]
## Array value cannot be retrieved from Pulumi Configuration when configuration values are set to `PULUMI_CONFIG` environment variable.

Reproduction of issue located at: https://github.com/phillipedwards/py-test

## Steps to Reproduce Issue
1. Clone this repo
2. python(3) -m pip install -r requirements.txt
3. pulumi preview
4. python(3) -m unittest

## Expected
Steps 3 and 4 (`pulumi preview` and `python3 -m unittest`) should successfully execute and write configuration values to CLI.

## Actual
Step 3 `pulumi preview` successfully writes configuration values to CLI.  
Step 4 `python3 -m unittest` fails due to an error which reads, `pulumi.config.ConfigTypeError: Configuration 'alb:subnet-ids-json' value '['subnet-123']' is not a valid 'JSON object'`

Screenshot:
![image](https://user-images.githubusercontent.com/25461821/130529275-11b675a1-6357-446e-be81-bab252d83bc2.png)

**Comment by phillipedwards** [comment]
After doing a little digging and thinking, I think the issue stems from how the Pulumi config is loaded from the PULUMI_CONFIG environment variable. Specifically, the `json.loads()` function is called twice when a program invokes `confiig.require_object()`. Once to load the configuration from the environment variable and again to retrieve the specific key from the configuration.

**Comment by justinvp** [comment]
I haven't tried the repro yet, but from looking it over, I'd expect it to work if `alb:subnet-ids-json: ['subnet-123']` was a JSON string, e.g. `alb:subnet-ids-json: '["subnet-123"]'`

**Comment by EvanBoyle** [comment]
Agree. Seems like the issue here is not with pulumi, but with either the config values that are stored or the robustness of your mocks that parse the YAML:

https://github.com/phillipedwards/py-test/blob/master/test_config.py#L14-L17

I'm going to close this issue out. Here is an issue that tracks adding a more fully supported config mocking feature to our unit testing support. There are some more examples of doing similar mocking via `PULUMI_CONFIG` in that issue: 

https://github.com/pulumi/pulumi/issues/4472

**Comment by phillipedwards** [comment]
@justinvp That's what I thought originally, however, it makes no difference. Single quotes or double quotes, escaping the JSON....it all results in the same error.

**Comment by justinvp** [comment]
@phillipedwards, with these changes, I don't see any errors:

```diff
$ git diff
diff --git a/Pulumi.dev.yaml b/Pulumi.dev.yaml
index 56f299b..e59ff84 100644
--- a/Pulumi.dev.yaml
+++ b/Pulumi.dev.yaml
@@ -1,7 +1,6 @@
 config:
   alb:environment: prod
-  alb:subnet-ids:
-    - subnet-123
-  alb:subnet-ids-json: ['subnet-123']
+  alb:subnet-ids: '["subnet-123"]'
+  alb:subnet-ids-json: '["subnet-123"]'
   aws:region: us-east-1
```

As @EvanBoyle mentions, an alternative to modifying the values in `Pulumi.dev.yaml` is changing how `Pulumi.dev.yaml` is parsed, such that the individual values for `alb:subnet-ids` and `alb:subnet-ids-json` that are used in `PULUMI_CONFIG` are JSON strings.

**Comment by justinvp** [comment]
Here's one way of parsing `Pulumi.dev.yaml` in a way that allows it to work as expected.

```diff
$ git diff
diff --git a/test_config.py b/test_config.py
index b32f88d..eb57ac6 100644
--- a/test_config.py
+++ b/test_config.py
@@ -14,7 +14,10 @@ class MyMocks(pulumi.runtime.Mocks):
 def set_config():
     with open("./Pulumi.dev.yaml", "r") as file:
         data = yaml.full_load(file)
-        os.environ["PULUMI_CONFIG"] = json.dumps(data["config"])
+        config = data["config"]
+        for key in config:
+            config[key] = json.dumps(config[key])
+        os.environ["PULUMI_CONFIG"] = json.dumps(config)
```

**Comment by phillipedwards** [comment]
@justinvp  Ahhh yeah you're right. I thought I tested with that format, but guess not. Big miss on my part. Anyway, appreciate the look and the help from you and @EvanBoyle .
