### ISSUE TITLE
Add codegen feature flags to help providers opt out of features to reduce generated code size

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#7835]
This a fairly tactical idea stemming from Go package size issues that broke pulumi-azure-native: https://github.com/pulumi/pulumi-azure-native/issues/1092

The providers team is contemplating a revert in the short term, to use codegen before pulumi/pulumi#7383, however we do need to be able to ship codegen upgrades through azure-native. If we could quickly put flags in place that allow opting out of some of extra code generation introduced by 7383, this would provide some optionality to move forward smoothly and buy our teams time to figure out real fixes for the underlying issues.

**Comment by t0yv0** [comment]
Update on this issue. 

Thanks to great effort by @komalali  and the providers team the provers have included #7383 and are up-to-date, but pulumi-azure-native is getting close to the file size limit one more time.

@mikhailshilkov requested to look into introducing flags for $fn_Output feature that currently does present an upgrade difficulty (for pulumi-azure-native)?

**Comment by mikhailshilkov** [comment]
> requested to look into introducing flags for $fn_Output feature that currently does present an upgrade difficulty (for pulumi-azure-native)?

This is needed for Go specifically. Other SDKs should be fine AFAIK.

**Comment by t0yv0** [comment]
Added a fix targeting fn_Output specifically. Agreed in discussion that we'll use feature-specific flags.
