### ISSUE TITLE
Nodejs codegen produces incorrect import syntax for azure-native

### ISSUE THREAD

**Issue by sergioalen** [pulumi/pulumi#7858]
When implementing the SDK generator for custom component providers, the nodejs codegen produces the following syntax for the azure native package:

```
import * as pulumiAzure-native from "@pulumi/azure-native";
```

As you can see the `pulumiAzure-native` contains a hyphen which is syntactically incorrect.

## Steps to reproduce

1. Create a custom component resource that uses the `@pulumi/azure-native` pkg
2. Run the `make generate` which ultimately executes `nodejsgen` against the `schema.json` to generate the SDKs
3. Check the output SDK for nodejs with incorrect import sysntax

Expected: possible correct syntax would be `import * as pulumiAzureNative from "@pulumi/azure-native";`
Actual: `import * as pulumiAzure-native from "@pulumi/azure-native";`

dotnet, go and python SDK generators seem to output in the correct format.

**Comment by emiliza** [comment]
@sergioalen What version of Pulumi are you using?

**Comment by sergioalen** [comment]
> @sergioalen What version of Pulumi are you using?

Apologies for the late reply, version info:
```
    "dependencies": {
        "@pulumi/azure-native": "^1.23.0",
        "@pulumi/pulumi": "^3.9.1"
    },
```
