### ISSUE TITLE
Pulumi v3.10.1+ hangs forever when previewing

### ISSUE THREAD

**Issue by benesch** [pulumi/pulumi#7862]
`pulumi preview` in v3.10.1+ hangs forever if you use a `pulumi_eks.Cluster` as the parent of another resource. Here's the smallest demonstration I could come up with:

```py
cluster = eks.Cluster(
    "example",
    vpc_id="doesntmatter",
    skip_default_node_group=True,
)

aws.eks.NodeGroup(
    "example",
    cluster_name="example",
    instance_types=["t3.micro"],
    node_role_arn=cluster.instance_roles[0].arn,
    subnet_ids=["doesntmatter"],
    scaling_config=aws.eks.NodeGroupScalingConfigArgs(
        desired_size=1,
        max_size=1,
        min_size=1,
    ),
    opts=pulumi.ResourceOptions(
        # Comment out the following line to make preview work.
        parent=cluster,
    ),
)
```

I've put together a Git repository that packages this reproducer up at https://github.com/benesch/pulumi-bug-eks. Instructions are in the README there.

I'm almost positive that https://github.com/pulumi/pulumi/commit/ecb98b66fd45c1cd5958bfd912eee8b8ce51a09d is the culprit, based on the fact that it is the _only_ commit in v3.10.1 that touches the Python SDK. From a quick skim, I wouldn't be surprised if there's additional trickiness that needs to happen when a remote resource is used as the parent of a local resource.

Not setting the cluster as the parent of the node group is a perfectly fine workaround for us for now. Just lost a fair amount of hair tracking this one down. :D 

cc @pgavlin

**Comment by lukehoban** [comment]
@pgavlin is this caused by https://github.com/pulumi/pulumi/pull/7732?

**Comment by EvanBoyle** [comment]
Repro'd this (consistently) and confirmed that https://github.com/pulumi/pulumi/issues/7862 seems to be the issue. Same program succeeds on 3.10.0. 

The changeset in question includes tests for component resources via a mocked `register_resource` impl, however there are no e2e/integration tests covering remote components. That would probably be a good place to start the investigation and determine if this is a specific combination of resources/dependencies causing this or just a coverage hole. cc @t0yv0

**Comment by t0yv0** [comment]
> Repro'd this (consistently) and confirmed that #7862 seems to be the issue. Same program succeeds on 3.10.0.

Did you mean #7732? 

Will start digging in shortly.

**Comment by EvanBoyle** [comment]
Ah yes, that is what I meant.

**Comment by t0yv0** [comment]
Simplified program:

```python
cluster = eks.Cluster(...)
aws.eks.NodeGroup(..., 
    node_role_arn=cluster.instance_roles[0].arn,
    opts=pulumi.ResourceOptions(parent=cluster),
)
```

Reason of hang: dependency expansion is not circle-aware and waits for NodeGroup urn preventing it from progressing to RegisterResource:

```
_add_dependency descending into child=NodeGroup of parent=Cluster
_add_dependency begins waiting on res.urn with res.NodeGroup
   why:
     prepare_resource res=NodeGroup, property_dependencies_resources key=nodeRoleArn
```

Now this is very reminiscent of the cycle hunt in https://github.com/pulumi/pulumi/pull/7859 for the engine implementation of dep expansion for deletes in https://github.com/pulumi/pulumi/pull/7852

I can put a test in and some simple some cycle detection into Python SDK that may help with this problem.

However I have been wondering if this logic could be completely handled by the engine instead of putting it in SDKs? I sense that we could have a ResourceMonitorWrapper that expands/reorders RegisterResource sequence as needed to expand deps. That'd be a win compared to implementing it N times in all language SDKs. However there probably is still the problem that parent-child relation is constructed and reported to the engine incrementally and the SDK is currently having a better view of it, that is if we moved the dep expansion into the engine it wouldn't see parent-child declarations fast enough to do as accurate job as the SDK of it.

@pgavlin does this sound right? So I should proceed with in-Python fix? If you have a draft doc for the dependency project this issue would be good to reference in there. Thanks.

**Comment by pgavlin** [comment]
> So I should proceed with in-Python fix? If you have a draft doc for the dependency project this issue would be good to reference in there. Thanks.

Yes, you should proceed with the in-Python fix. The behavior of the Python implementation is supposed to match the behavior of the Node implementation in this respect. We may need a similar fix for Go.

**Comment by pgavlin** [comment]
@t0yv0 can you check to see if this same program fails in Node? I don't see anything in the Node SDK that would prevent this from hanging either...

**Comment by t0yv0** [comment]
Yeah certainly I can check across SDKs.

**Comment by EvanBoyle** [comment]
When I repro'd the issue I also tried it in node and the preview succeeds:

```ts
import * as pulumi from "@pulumi/pulumi";
import * as eks from "@pulumi/eks";
import * as aws from "@pulumi/aws"


const cluster = new eks.Cluster("examples",
{
    vpcId: "doesntmatter",
    skipDefaultNodeGroup: true,
});

const ng = new aws.eks.NodeGroup("example", {
    clusterName: "example",
    instanceTypes: ["t3.micro"],
    nodeRoleArn: cluster.instanceRoles[0].arn,
    subnetIds: ["doesntmatter"],
    scalingConfig: {
        desiredSize: 1,
        maxSize: 1,
        minSize: 1,
    }
}, { parent: cluster})

```

Note that EKS does not use remote components, but it seems like that is not related to the root cause.

**Comment by pgavlin** [comment]
The fact that there is a remote component involved might be relevant. In the case of NodeJS, the property deps will not include the EKS cluster—instead, they will include the instance role whose ARN is referenced. Although this should also be the case for remote components, I’m wondering if we have a bug there that isn’t omitting the cluster from the list of dependencies in the instanceRolea output. Could we try the NodeJS repro using EKS as a remote component?

**Comment by t0yv0** [comment]
I'm now running Evan's node translation and about to debug into it to understand why it passes. 

> Could we try the NodeJS repro using EKS as a remote component?

What do you mean here? `eks.Cluster` is always a remote component because it declares itself as such. I'm a bit confused.

**Comment by pgavlin** [comment]
In NodeJS, `eks.Cluster` should be a local component unless we changed something recently. It is remote for all other languages.

**Comment by t0yv0** [comment]
Oh... that's interesting. Okay let me debug then to see what else I can find.

In Python..  `node_role_arn` property dependencies included eks.Cluster, though it's not obvious to me why, looking at the code definition for eks.Cluster in Python. Is there a rule that remote component outputs always depend on remote component itself, or some such..

**Comment by t0yv0** [comment]
Go version hangs similarly to the Python version. https://github.com/pulumi/pulumi/issues/7890

**Comment by t0yv0** [comment]
C# version hangs similarly also https://github.com/pulumi/pulumi/issues/7900
