### ISSUE TITLE
Azure Devops Provider: Branch policy conflict doesn't make any sense

### ISSUE THREAD

**Issue by francardoso93** [pulumi/pulumi#7898]
Not sure if I should report this here or at [Microsoft Terraform Provider Azure Devops](https://github.com/microsoft/terraform-provider-azuredevops/issues). 

I have a Go Lang code managing several Azure Devops resources, but I'm getting a conflict error of the property  `OnPushResetApprovedVotes` with `OnPushResetAllVotes` when tryinng to use the method `NewBranchPolicyMinReviewers(....)` as described at [API Reference doc](https://www.pulumi.com/docs/reference/pkg/azuredevops/branchpolicyminreviewers/) . It doesn't matter the values I set for these properties, conflict all the time.

## Steps to reproduce

1.  Use NewBranchPolicyMinReviewers() method as described at [API Reference doc](https://www.pulumi.com/docs/reference/pkg/azuredevops/branchpolicyminreviewers/). That's my code:
``` Go
func handleMinReviewersPolicy(ctx *pulumi.Context, projectId pulumi.IDOutput, repoConventionedNamed string, repository *azuredevops.Git) error {
	_, err := azuredevops.NewBranchPolicyMinReviewers(ctx, repoConventionedNamed + "branch-policy-min-reviewers", &azuredevops.BranchPolicyMinReviewersArgs{
		ProjectId: projectId,
		Enabled:   pulumi.Bool(true),
		Blocking:  pulumi.Bool(true),
		Settings: &azuredevops.BranchPolicyMinReviewersSettingsArgs{
			ReviewerCount:                     pulumi.Int(1),
			SubmitterCanVote:                  pulumi.Bool(false),
			LastPusherCannotApprove:           pulumi.Bool(true),
			AllowCompletionWithRejectsOrWaits: pulumi.Bool(false),
			OnPushResetApprovedVotes:          pulumi.Bool(true),
			OnLastIterationRequireVote:        pulumi.Bool(false),
			Scopes: azuredevops.BranchPolicyMinReviewersSettingsScopeArray{
				&azuredevops.BranchPolicyMinReviewersSettingsScopeArgs{
					RepositoryId:  repository.ID(),
					RepositoryRef: repository.DefaultBranch,
					MatchType:     pulumi.String("Exact"),
				},				
				&azuredevops.BranchPolicyMinReviewersSettingsScopeArgs{
					RepositoryId:  nil,
					RepositoryRef: pulumi.String("refs/heads/releases"),
					MatchType:     pulumi.String("Prefix"),
				},
			},
		},
	})
	if err != nil {
		return err
	}
	return nil
}

```

2. Pulumi Up (You will find the error now)
3. Also try to change values of OnPushResetApprovedVotes and OnPushResetAllVotes (All possible combinations -> true/true, false/false, true/false, false, true).
4. When you run **all of these combinations** you will find the **same error every time**

Expected: 
Pulumi CLI asks if you want to apply all changes to real infraestructure

Actual: 
``` 
Diagnostics:
  azuredevops:index:BranchPolicyMinReviewers (techfin-riskbranch-policy-min-reviewers):
    error: azuredevops:index/branchPolicyMinReviewers:BranchPolicyMinReviewers resource 'techfin-riskbranch-policy-min-reviewers' has a problem: "settings.0.on_push_reset_approved_votes": conflicts with settings.0.on_push_reset_all_votes
    error: azuredevops:index/branchPolicyMinReviewers:BranchPolicyMinReviewers resource 'techfin-riskbranch-policy-min-reviewers' has a problem: "settings.0.on_push_reset_all_votes": conflicts with settings.0.on_push_reset_approved_votes
```

**Comment by emiliza** [comment]
Sorry about that experience @francardoso93. 

We have this issue tracked in https://github.com/pulumi/pulumi-azuredevops/issues/38 .
