### ISSUE TITLE
Pulumi destroy --keep option

### ISSUE THREAD

**Issue by 107ef363-c60f-46fb-a8bc-da8c5f4f6938** [pulumi/pulumi#7901]
When destroying part of a stack it is often much easier to specify what you'd like to keep than what you'd like to target. This is especially true for stacks with a large number of resources. 

For instance you might want to keep a GCP project when rebuilding a stack because deleted projects (projects pending permanent deletion) still count towards your project quota for a while. In those situations using the target option is tedious and involves a lot of copy and pasting.

The solution is adding an option to `pulumi destroy` that does the opposite of what `--target` does. Using `--keep` or `-k` for short seems like an obvious choice.

**Comment by emiliza** [comment]
Great suggestion! This feature request is being tracked in https://github.com/pulumi/pulumi/issues/6539

Please track and upvote that issue 😄
