### ISSUE TITLE
Output apply / creation is run during preview and fails if base resource does not exist

### ISSUE THREAD

**Issue by dspasojevic** [pulumi/pulumi#7903]
I'm trying to derive a new `Output` by calling `apply` on an existing `Output`. The example here is to retrieve the URL of a queue (which is no longer necessary since the queue resource now has the url), but the same pattern was used to derive the value of an SSM parameter using the name of the resource, etc.

The documentation seems to suggest that `apply` is run *after* resource creation and not during preview. This doesn't seem to be the case.

## Steps to reproduce

1. Create a new `aws-typescript` project.
2. Change code to below:
```typescipt
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

// Create an AWS resource (SQS Queue)
const queueResource = new aws.sqs.Queue("somequeue")

// Create a new Output that is derived from an Output from the created resource

const queue = queueResource.name.apply((name) => 
    aws.sqs.getQueue({name})
);

// This also fails
// const queue = pulumi.output(aws.sqs.getQueue({name: "somequeue"}));

// Export the id 
export const queueId = queueResource.id;

// Export the url
export const queueUrl = queue.url;
```
3. Run preview `tsc && pulumi preview -d`

Expected: 
Expect `queueUrl` to be undefined during preview, but defined after resource creation.
Actual:
Fails because `aws.sqs.getQueue` is run during preview / before the resource is created.

**Comment by emiliza** [comment]
This is a similar issue to https://github.com/pulumi/pulumi/issues/7030

Which we've deemed not a bug:

In general, an apply will run if the value is known. I think the wording in the documentation could be improved, but the intent of the text "For example, it won’t run during a preview, when resource output values may be unknown" should emphasize the "may be unknown" part.

**Comment by dspasojevic** [comment]
Thanks @emiliza. I see that the suggested workaround there is to test what stage is being run or rely on an output that is not not until the resource is created.

This:
```typescript
const queue = pulumi
  .all([queueResource.id, queueResource.name])
  .apply(([_, name]) =>
    aws.sqs.getQueue(
      {
        name,
      },
      {
        async: true,
      }
    )
  );
```

Does indeed work.

Is that still the suggested approach to this?
