### ISSUE TITLE
Combination of main and python runtime with virtualenv option in Pulumi.yaml doesn't work

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi#7907]
Pulumi.yaml:

```yaml
name: myproject
main: src/
runtime:
  name: python
  options:
    virtualenv: .venv
```

```bash
pulumi up
```

Expected: Packages are installed to .venv in the project directory, pulumi up works.
Actual: Packages are installed to .venv in the project directory, however pulumi up fails with:
```
Diagnostics:
  pulumi:pulumi:Stack (myproject-teststack):
    The 'virtualenv' option in Pulumi.yaml is set to "/home/xyz/projects/project_directory/src/.venv", but "/home/xyz/projects/project_directory/src/.venv" doesn't exist.
    Run the following commands to create the virtual environment and install dependencies into it:
        1. python3 -m venv /home/xyz/projects/project_directory/src/.venv
        2. /home/xyz/projects/project_directory/src/.venv/bin/python -m pip install --upgrade pip setuptools wheel
        3. /home/xyz/projects/project_directory/src/.venv/bin/python -m pip install -r /home/xyz/projects/project_directory/src/requirements.txt
    For more information see: https://www.pulumi.com/docs/intro/languages/python/#virtual-environments
```

I think packages should be installed to .venv in the project directory and not to src/.venv because there might be problems with module names. I can imagine `virtualenv: pulumi` that could shadow pulumi package. If I want to force it, it is possible to do it with `virtualenv: src/pulumi` (and take a risk). So the only problem is that pulumi tries to find the virtualenv directory in the main directory and not in the project one.

**Comment by emiliza** [comment]
This issue is being tracked in https://github.com/pulumi/pulumi/issues/7061
