### ISSUE TITLE
.NET 6 support

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#7911]
.NET 6 will ship in November 2021. It's going to be the next LTS version.

- [x] #8153 
- [x] https://github.com/pulumi/pulumi/issues/8476
- [x] https://github.com/pulumi/pulumi/issues/8447
- [x] https://github.com/pulumi/templates/issues/269
- [x] https://github.com/pulumi/protobuf/pull/1
- [x] https://github.com/pulumi/templates/issues/292
- [x] https://github.com/pulumi/pulumi-docker-containers/issues/85
- [x] Consider switching our docs to default to .NET 6
- [x] https://github.com/pulumi/pulumi/issues/10114
- [x] https://github.com/pulumi/pulumi-hugo/issues/1724

**Comment by t0yv0** [comment]
Possibly blocked on grpc update.

**Comment by mikhailshilkov** [comment]
All the improvements related to .NET 6 that we planned in this epic are now shipped! .NET 6 is the default .NET version in Pulumi now, and we also rely on some more modern C# features. Read more in our blog [Improved Pulumi experience with .NET 6](https://www.pulumi.com/blog/pulumi-targets-dotnet-6/).
