### ISSUE TITLE
Could pulumi config set cause race condition ?

### ISSUE THREAD

**Issue by yadsamit-disc** [pulumi/pulumi#7920]
Hi Team,

**Background:**
Our deployment pipeline is as follows: `git push by tag --> circleCi --> pulumi --> ECS fargate`

**Problem:**
Today we don't have a way to mark release/deployment version in our logs. In order to do so, I am trying to inject the git release version to circleCi and eventually to our monitoring platform agent (datadog here) through pulumi.

**Approach:**
I have found a way to do set the release version in the datadog agent. I am using the below command
`pulumi config set releaseVersion <<parameters.tag>>` in one of our circleCI config commands.

_Steps in the circleCi command:_
1. `pulumi login to s3 bucket`
2. `pulumi config set releaseVersion <<parameters.tag>> in the relevant stack`
3. `pulumi up`
4. `pulumi logout`

**Concerns:**
Would updating the stack config while deploying cause any issue - specially any race condition?

Thanks for your help.

Best
Amit

**Comment by emiliza** [comment]
The way you've outlined your steps should be fine. Let me know if you're encountering any issues!
