### ISSUE TITLE
Route53 Zone ARN missing in TS

### ISSUE THREAD

**Issue by hognevevle** [pulumi/pulumi#7923]
![CleanShot 2021-09-08 at 15 23 31](https://user-images.githubusercontent.com/2721188/132517569-fbb5ae0b-ea59-42a6-8497-3f22c7a960d7.png)

As far as I can see in the docs, the `arn` field should be available. Also, when doing the same operation in C#, there is indeed an `Arn` field available, so it seems like a TS-issue.

**Comment by stack72** [comment]
Hi @hognevevle 

Please can you tell me what version of pulumi-aws you are using? I can see that the parameter is indeed available in the latest version

https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/route53/getZone.ts#L90

Paul

**Comment by hognevevle** [comment]
Hi Paul,

Sorry for not ensuring I was on the latest version. I was on `4.15.0`. After upgrading the `4.19.0`, everything works as expected.

Thank you!
