### ISSUE TITLE
pulumi-onelogin

### ISSUE THREAD

**Issue by excavador** [pulumi/pulumi#7935]
New provider: pulumi-onelogin

Hello! 
I need pulumi-onelogin provider, like you have already for okta (pulumi-okta).

I have created initial version using terraform-bridge: https://github.com/excavador/pulumi-onelogin
Is it possible to move this repository to pulumi organizations and give me access to this repository?

Eventually I will extend repository and create all other required things (like release management, etcetera), like you have for pulumi-okta

**Comment by stack72** [comment]
Hi @excavador 

Can you email me on stack72 @pulumi.com and we can discuss this?

thanks

Paul

**Comment by excavador** [comment]
@stack72 I wrote from ot@project-plato.com

**Comment by excavador** [comment]
@stack72 thank you, Paul!
