### ISSUE TITLE
ReplaceOnChanges: Found recursive object warnings when upgrading Azure-Native to 3.12.0

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#7940]
Upgrading Azure-Native to codegen v3.12.0 causes a very large number of warnings:

```
warning: Failed to genereate full `ReplaceOnChanges`: Found recursive object "virtualNetworkTaps"
warning: Failed to genereate full `ReplaceOnChanges`: Found recursive object "applicationGatewayBackendAddressPools"
warning: Failed to genereate full `ReplaceOnChanges`: Found recursive object "backendIPConfigurations"
warning: Failed to genereate full `ReplaceOnChanges`: Found recursive object "loadBalancerInboundNatRules"
warning: Failed to genereate full `ReplaceOnChanges`: Found recursive object "publicIPAddress"
warning: Failed to genereate full `ReplaceOnChanges`: Found recursive object "subnet"
warning: Failed to genereate full `ReplaceOnChanges`: Found recursive object "linkedPublicIPAddress"
warning: Failed to genereate full `ReplaceOnChanges`: Found recursive object "servicePublicIPAddress"
warning: Failed to genereate full `ReplaceOnChanges`: Found recursive object "subnet"
```

This totally screws the output of code generation...

Recursive objects are expected and are indeed used heavily in azure-native. We should adjust codegen accordingly.

**Comment by justinvp** [comment]
@iwahbe, this looks like a regression introduced by the recent `ReplaceOnChanges` codegen feature.

**Comment by iwahbe** [comment]
So my first take is that
1. This is a bug, in that warnings are emitted that shouldn't be. 
2. Under the current design, these warnings should be emitted if any object in the chain has `replaceOnChanges: true`. This is per our discussion on recursive objects: https://github.com/pulumi/pulumi/pull/7874#issuecomment-910499720. If recursive objects are common, are we comfortable with this design?
