### ISSUE TITLE
Import RouteTableAssociation error

### ISSUE THREAD

**Issue by fdelfranco** [pulumi/pulumi#7978]
Hi! im having a issue trying to import an existing Route Table Association from aws.

Im using the next command: 

```
pulumi import aws:ec2/routeTableAssociation:RouteTableAssociation assoc subnet-0a40fcb0a44bba71d/rtb-0940e4e4d9f6ef096
```

Getting this output:

```
Previewing import (prod):
     Type                              Name      Plan       Info
     pulumi:pulumi:Stack               ami-prod             1 error
 =   └─ aws:ec2:RouteTableAssociation  assoc     import     3 errors
 
Diagnostics:
  pulumi:pulumi:Stack (ami-prod):
    error: preview failed
 
  aws:ec2:RouteTableAssociation (assoc):
    error: aws:ec2/routeTableAssociation:RouteTableAssociation resource 'assoc' has a problem: ExactlyOne: "gateway_id": one of `gateway_id,subnet_id` must be specified. Examine values at 'RouteTableAssociation.GatewayId'.
    error: aws:ec2/routeTableAssociation:RouteTableAssociation resource 'assoc' has a problem: ExactlyOne: "subnet_id": one of `gateway_id,subnet_id` must be specified. Examine values at 'RouteTableAssociation.SubnetId'.
    error: Preview failed: one or more inputs failed to validate
```

can anyone give some help? idont know if something wrong or is a bug.

Thanks!

**Comment by fdelfranco** [comment]
having same problems when importing a route:

$ pulumi import aws:ec2/route:Route my_route rtb-0832b42c94eba5578_10.61.3.0/24
Previewing import (artifacs):
     Type                 Name               Plan       Info
     pulumi:pulumi:Stack  artifacs-artifacs             1 error
 =   └─ aws:ec2:Route     my_route           import     11 errors
 
Diagnostics:
  pulumi:pulumi:Stack (artifacs-artifacs):
    error: preview failed
 
  aws:ec2:Route (my_route):
    error: aws:ec2/route:Route resource 'my_route' has a problem: ExactlyOne: "carrier_gateway_id": one of `carrier_gateway_id,egress_only_gateway_id,gateway_id,instance_id,local_gateway_id,nat_gateway_id,network_interface_id,transit_gateway_id,vpc_endpoint_id,vpc_peering_connection_id` must be specified. Examine values at 'Route.CarrierGatewayId'.
    error: aws:ec2/route:Route resource 'my_route' has a problem: ExactlyOne: "egress_only_gateway_id": one of `carrier_gateway_id,egress_only_gateway_id,gateway_id,instance_id,local_gateway_id,nat_gateway_id,network_interface_id,transit_gateway_id,vpc_endpoint_id,vpc_peering_connection_id` must be specified. Examine values at 'Route.EgressOnlyGatewayId'.
    error: aws:ec2/route:Route resource 'my_route' has a problem: ExactlyOne: "nat_gateway_id": one of `carrier_gateway_id,egress_only_gateway_id,gateway_id,instance_id,local_gateway_id,nat_gateway_id,network_interface_id,transit_gateway_id,vpc_endpoint_id,vpc_peering_connection_id` must be specified. Examine values at 'Route.NatGatewayId'.
    error: aws:ec2/route:Route resource 'my_route' has a problem: ExactlyOne: "transit_gateway_id": one of `carrier_gateway_id,egress_only_gateway_id,gateway_id,instance_id,local_gateway_id,nat_gateway_id,network_interface_id,transit_gateway_id,vpc_endpoint_id,vpc_peering_connection_id` must be specified. Examine values at 'Route.TransitGatewayId'.
    error: aws:ec2/route:Route resource 'my_route' has a problem: ExactlyOne: "vpc_endpoint_id": one of `carrier_gateway_id,egress_only_gateway_id,gateway_id,instance_id,local_gateway_id,nat_gateway_id,network_interface_id,transit_gateway_id,vpc_endpoint_id,vpc_peering_connection_id` must be specified. Examine values at 'Route.VpcEndpointId'.
    error: aws:ec2/route:Route resource 'my_route' has a problem: ExactlyOne: "instance_id": one of `carrier_gateway_id,egress_only_gateway_id,gateway_id,instance_id,local_gateway_id,nat_gateway_id,network_interface_id,transit_gateway_id,vpc_endpoint_id,vpc_peering_connection_id` must be specified. Examine values at 'Route.InstanceId'.
    error: aws:ec2/route:Route resource 'my_route' has a problem: ExactlyOne: "network_interface_id": one of `carrier_gateway_id,egress_only_gateway_id,gateway_id,instance_id,local_gateway_id,nat_gateway_id,network_interface_id,transit_gateway_id,vpc_endpoint_id,vpc_peering_connection_id` must be specified. Examine values at 'Route.NetworkInterfaceId'.
    error: aws:ec2/route:Route resource 'my_route' has a problem: ExactlyOne: "gateway_id": one of `carrier_gateway_id,egress_only_gateway_id,gateway_id,instance_id,local_gateway_id,nat_gateway_id,network_interface_id,transit_gateway_id,vpc_endpoint_id,vpc_peering_connection_id` must be specified. Examine values at 'Route.GatewayId'.
    error: aws:ec2/route:Route resource 'my_route' has a problem: ExactlyOne: "local_gateway_id": one of `carrier_gateway_id,egress_only_gateway_id,gateway_id,instance_id,local_gateway_id,nat_gateway_id,network_interface_id,transit_gateway_id,vpc_endpoint_id,vpc_peering_connection_id` must be specified. Examine values at 'Route.LocalGatewayId'.
    error: aws:ec2/route:Route resource 'my_route' has a problem: ExactlyOne: "vpc_peering_connection_id": one of `carrier_gateway_id,egress_only_gateway_id,gateway_id,instance_id,local_gateway_id,nat_gateway_id,network_interface_id,transit_gateway_id,vpc_endpoint_id,vpc_peering_connection_id` must be specified. Examine values at 'Route.VpcPeeringConnectionId'.
    error: Preview failed: one or more inputs failed to validate

**Comment by emiliza** [comment]
Hi @fdelfranco - Apologies for the inconvenience.  We have an open issue tracking these import failures, see: https://github.com/pulumi/pulumi/issues/7160 - also contains a possible workaround identified in that thread
