### ISSUE TITLE
`Go` expects arg fields that don't exist

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#7983]
## Steps to reproduce

1. Go to `sdk_driver.go` and remove `replace-on-change`'s `SkipCompileCheck` set. 
2. Run `go test ./...` from `pkg/codegen`. 

Expected: The pulumi code generator should produce valid code. This code should type check. 
Actual: 
I got this error for `Go`:

```
❯ go get
# github.com/pulumi/test/internal
./cat.go:30:9: args.Name undefined (type *CatArgs has no field or method Name)
./cat.go:31:7: args.Name undefined (type *CatArgs has no field or method Name)
```

## On closing
- [ ] Reenable this test in `sdk_driver.go`.

**Comment by justinvp** [comment]
This was fixed by #9052
