### ISSUE TITLE
aws lambda, ResourceConflictException: The operation cannot be performed at this time

### ISSUE THREAD

**Issue by snolangps** [pulumi/pulumi#7990]
I'm trying to deploy a stack to aws (which worked fine until Thursday September 16th 2021), and recently just noticed that I'm seeing `ResourceConflictException: The operation cannot be performed at this time. An update is in progress`.

But when I look up the status of the lambda(s) in question, i see:
`aws lambda get-function --function-name someLambda --query 'Configuration.[State, StateReason, StateReasonCode, LastUpdateStatus]'
[
    "Active",
    null,
    null,
    "Successful"
]`

So I'm so very confused on whether this is pulumi or aws...?

Dependencies being used:
"aws-sdk": "^2.575.0"
"@pulumi/aws": "0.18.27",
"@pulumi/awsx": "0.18.14",
"@pulumi/pulumi": "1.8.0"

## Steps to reproduce

1. Just try to deploy with lambdas...

Expected: 
I'm expecting to see resources update.

Actual: 
I'm getting errors that SOME lambdas have an "update in progress"

**Comment by emiliza** [comment]
@snolangps Looks like you may be experiencing this: https://forums.aws.amazon.com/thread.jspa?messageID=995846#995846

AWS is now rolling out Lambda states: https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions/ - looks like the recommendation now is to check for the lambda state to return successful before continuing

Hope this helps!
PS: Please upgrade your Pulumi versions when you get a chance 😄

**Comment by snolangps** [comment]
@emiliza thx for the response, so is this something to use pulumi to check for the state first, or from somewhere else? Is there new documentation on how to deploy aws lambdas about this now?

**Comment by snolangps** [comment]
@emiliza I updated versions and it seems to be working now. Not sure if that was it, or if aws fixed whatever was wrong, but this seems to be working now, thx.

**Comment by isenberk** [comment]
HI this error occur to me again it is about https://aws.amazon.com/blogs/compute/coming-soon-expansion-of-aws-lambda-states-to-all-functions. Does Pulumi plan to create update to support this ?
