### ISSUE TITLE
Design for stacks exporting APIs

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#8]
At the moment, we have placeholders for stacks being able to export structured APIs.  This will enable stronger typechecking, including proper substitutability that our unique approach to componentization enables.  The problem is, we don't yet have any idea of what form this takes.

At a top-level, we must pick a metadata format.  Candidates here include OpenAPI/Swagger, RAML, and Protobufs/gRPC.  One option is to pick something that is "provider"-like and pluggable.

I have to admit, I have a preference for OpenAPI/Swagger for "internet-facing" services, and Protobufs/gRPC for inward-facing microservices APIs.

After that, we need to figure out what runtime manifestation occurs on the wire.  For instance, it's possible we would leverage OpenAPI/Swagger as the metadata format, but turn around and use gRPC and HTTP/2 on the wire.

Moreover, when installing a stack locally, we may want to auto-generate some client side proxy wrappers for interacting with the service, to add strong typing.  This becomes more important as we consider doing the DSL.

This work item will likely spawn many more as we make progress on these topics.

**Comment by pgavlin** [comment]
@joeduffy I'm not 100% sure what the idea is here--can we close this one out?

**Comment by joeduffy** [comment]
This doesn't really apply to our new model -- closing out.
