### ISSUE TITLE
Pulumi uses defalut aws creds profile even when aws:profile is configured

### ISSUE THREAD

**Issue by orcutt989** [pulumi/pulumi#8015]
I noticed that Pulumi was trying to use my default aws credentials profile even though I had aws:profile configured to a different profile for the stack.  The new profile was based on a different base profile AND when I rename the default profile it seems to get upset about not being able to find credentials despite aws:profile being configured.

Happened in Pulumi 3.7.1 and 3.12.0

**Comment by orcutt989** [comment]
My node packages are way out of date. Updating per pulumi support.

 ``` @types/node     ^10.0.0  →  ^16.9.6
 @pulumi/awsx    ^0.24.0  →  ^0.31.0
 @pulumi/eks     ^0.23.0  →  ^0.33.0
 @pulumi/pulumi   ^2.0.0  →  ^3.12.0
 dotenv           ^8.2.0  →  ^10.0.0
 yaml            ^1.10.0  →  ^1.10.2```

**Comment by tusharshahrs** [comment]
This issue has been resolved.

**Comment by emiliza** [comment]
Just in case other folks may be running into this, general resolution involved:
- update package.json & pulumi version
- add providerCredentialOps: https://www.pulumi.com/docs/reference/pkg/eks/cluster/#providercredentialopts_nodejs
- create new vpc/subnets

**Comment by orcutt989** [comment]
Thanks! Yes the problem was not using providerCredentialOpts.
