### ISSUE TITLE
Revisit config key naming and API design

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#802]
At the moment, there are a few oddities with respect to config key naming and API design.

First, we use `:config` whenever we allocate a config bag, and then require that it get specified at the CLI when interacting with config values.  For example, in code:

```typescript
import * as pulumi from "pulumi";
let config = new pulumi.Config("mypackage:config");
// ...
let something = config.require("something");
```

And:

```bash
$ pulumi config set mypackage:config:bar x
$ pulumi config set aws:config:foo y
# and so on...
```

The `:config` part adds no value and, indeed, it's just weird that you need to remember it.  Also, the fact that `mypackage` isn't auto-discovered is also annoying.

It would be actually pretty neat if you could just do something like this instead:

```typescript
import * as pulumi from "pulumi";
let something = pulumi.config.require("something");
```

And then:

```bash
$ pulumi config set mypackage:bar x
$ pulumi config set aws:foo y
```

The most challenging part of this is getting the dynamic package name discovery working.  This needs to resolve to the package whose code is calling the config system.  But if we can make this work, I think the usability would be considerably better than what we have today.

**Comment by joeduffy** [comment]
We did part of this, removing the superfluous `config` part. @ellismg Do you envision us ever taking the next step and removing the need for the colon `:`? If not, let's close this out for now.

**Comment by lukehoban** [comment]
> Do you envision us ever taking the next step and removing the need for the colon :? If not, let's close this out for now.

I think we can close this out at this point. We may more broadly rethink config, but don't need to track this specifically at this point.
