### ISSUE TITLE
`package embed is not in GOROOT` error on templates test

### ISSUE THREAD

**Issue by emiliza** [pulumi/pulumi#8030]
See: https://github.com/pulumi/templates/runs/3680449329?check_suite_focus=true

```Error:     ../../pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.13.0/go/common/apitype/core.go:32:2: package embed is not in GOROOT (/opt/hostedtoolcache/go/1.15.15/x64/src/embed)```

Introduced in https://github.com/pulumi/pulumi/pull/8002/

**Comment by stack72** [comment]
I am pretty confident this will be close via https://github.com/pulumi/templates/pull/215

**Comment by stack72** [comment]
Upgrading to Go 1.16.x fixed the issue
