### ISSUE TITLE
Project configuration (`Pulumi.yaml`) option to refresh before every `preview`/`update`/`destroy`

### ISSUE THREAD

**Issue by infin8x** [pulumi/pulumi#8058]
Following up on a suggestion in https://github.com/pulumi/pulumi/issues/2247#issuecomment-925366911, let's introduce a new config option that will cause the engine to run a refresh before every `preview`/`update`/`destroy` operation. This should be logically equivalent to the user remembering to always add `--refresh` to those operations.

Suggested option name/type: `alwaysRefresh` (boolean)

**Comment by stack72** [comment]
Hi @infin8x 

So I need a little clarification on the work here - should the `Pulumi.yaml` option be used over the cli args? I.e. the user has specifically set this value for the entire project

Paul

**Comment by jre21** [comment]
Generally in this situation, command-line flags should take precedence over the config file.  That way a user can set a default behavior but still override it for a specific execution.  The most common approach I've seen in other projects is:

- `pulumi update --refresh`: perform a refresh before updating
- `pulumi update --no-refresh`: update without performing a refresh
- `pulumi update`: use the behavior defined in the configuration file (or the global default if the config doesn't specify a behavior)

Another common pattern to keep in mind for if you do decide to change the default behavior in 4.0: many projects will issue a depreciation notice for a few releases prior to changing a default.  This notice would typically be printed during program execution, state what behavior is changing, and direct users who wish to retain the current behavior to set it explicitly set it in their config file (usually with a note that doing so will silence the deprecation warning).  The notice should _not_ be displayed to users who already have explicit configuration.  Git took this approach, for example, prior to changing the default setting for `push.default` in their 2.0 release.

**Comment by infin8x** [comment]
@stack72 good question. I agree with @jre21's suggestion - CLI flags take precedence over the config file.

Thanks @jre21 for the broader suggestion on deprecation workflow.
