### ISSUE TITLE
Python puts raise statements in lambdas. 

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#8062]
This was discovered compiling our program generator tests. We assume that `raise Execption(body)` is a expression, but it is not. Because python `lambda`s only accommodate expressions, this fails with a syntax error. Note that `lambda x: return x` is also invalid. 

We might consider opting out of `lambda`s in favor of full functions. 

To reproduce, run 
1. `cd pkg/codegen && python3 -m py_compile internal/test/testdata/aws-s3-folder-pp/aws-s3-folder.py`

Expected: Print nothing (valid python)
Actual:
```sh
  File "internal/test/testdata/aws-s3-folder-pp/aws-s3-folder.py", line 18
    content_type=(lambda: raise Exception("FunctionCallExpression: mimeType (aws-s3-folder.pp:19,16-37)"))()))
                          ^
SyntaxError: invalid syntax
```

**Comment by justinvp** [comment]
Looks like this issue is no longer present. I'll open a PR to unskip.
