### ISSUE TITLE
Go program codegen: handle providers incorrectly

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#8076]
This was found compiling our program codegen tests. Our providers don't live in their own namespace. Instead they share the top level namespace of `aws`.  We incorrectly import `"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/providers"` instead of `"github.com/pulumi/pulumi-aws/sdk/v4/go/aws"`. 
## Steps to reproduce

1. `cd pkg/codegen/internal/test/testdata/aws-resource-options-pp`
2. `go build`

Expected: A clean compile
Actual: 
```
aws-resource-options.go:4:2: no required module provides package github.com/pulumi/pulumi-aws/sdk/v4/go/aws/providers; to add it:
	go get github.com/pulumi/pulumi-aws/sdk/v4/go/aws/providers
```

**Comment by lukehoban** [comment]
See also related https://github.com/pulumi/pulumi/issues/6510.
