### ISSUE TITLE
Panic when ec2.LookupAmiOutput finds no matching results

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#8107]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

`ec2.LookupAmiOutput` panics when the user-specified filters result in no AMIs being found. 

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/ec2"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		res := ec2.LookupAmiOutput(ctx, ec2.LookupAmiOutputArgs{
			Filters: ec2.GetAmiFilterArray{
				ec2.GetAmiFilterArgs{
					Name: pulumi.String("name"),
					// use "Cloud9AmazonLinux2-*" to get a valid result
					Values: pulumi.StringArray{pulumi.String("Cloud9AmazonLinux3-*")},
				},
			},
			MostRecent: pulumi.Bool(true),
			Owners:     pulumi.StringArray{pulumi.String("amazon")},
		})

		ctx.Export("arn", res.Arn())
		return nil
	})
}
```

### Steps to reproduce

Expected: recoverable error or empty result
Actual: panic

Filing it here rather than in pulumi/pulumi-aws as this might be an issue with handling errors in the newly introduced $fnOutput helper feature, the older plain version of the invoke LookupAmi is better behaved here.

**Comment by dixler** [comment]
I was able to repro this error on `github.com/pulumi/pulumi-aws/sdk/v4/go/aws/ec2`

This appears fixed on the latest v5 of the aws provider. (github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ec2)
[![asciicast](https://asciinema.org/a/sEAPTfbLbSPh8iQEsPUPMTygG.svg)](https://asciinema.org/a/sEAPTfbLbSPh8iQEsPUPMTygG)
