### ISSUE TITLE
can't find ami

### ISSUE THREAD

**Issue by guan-ai** [pulumi/pulumi#8120]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

This is my first attempt with pulumi. I have the AWS_ACCESS_KEY_ID and the AWS_SECRET_ACCESS_KEY in the environment variable. And I'm following [this tutorial](https://www.learnaws.org/2021/06/19/pulumi-python-ec2/) and [this tutorial](https://www.pulumi.com/docs/reference/pkg/aws/getami/). 

I found that simple AMI query could not return the correct resource. It always says "Your query returned no results" when I have the AMI with the correct name on AWS. 

### Steps to reproduce

1. `ami = aws.ec2.get_ami(owners=["self"],
    filters=[
        aws.ec2.GetAmiFilterArgs(
            name="name",
            values=["my-ami-namei"],
        ),
    ],
    most_recent=True,
    executable_users=["self"]
    )`
2.`pulumi up` or `pulumi preview`

Expected: It should return the correct AMI resource. 
Actual: `Exception: invoke of aws:ec2/getAmi:getAmi failed: invocation of aws:ec2/getAmi:getAmi returned an error: invoking aws:ec2/getAmi:getAmi: 1 error occurred:
    	* Your query returned no results. Please change your search criteria and try again.
`
Am I missing something?

**Comment by ecda909** [comment]
Did you ever figure this out? I'm facing the same issue...
