### ISSUE TITLE
aws.lambda.CallbackFunction() policy doesn't get attached

### ISSUE THREAD

**Issue by shinebayar-g** [pulumi/pulumi#8126]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce

1. Create new `aws.lambda.CallbackFunction()` with `policies` property set.

Expected: 
Policy gets attached properly.

Actual: 
Policy didn't get attached.

When we define new lambda function with `aws.lambda.CallbackFunction()` class it takes `policies` property. Its description is:

```
A list of IAM policy ARNs to attach to the Function. Will be used if [role] is not provide. If neither [role] nor [policies] is provided, a default policy of [iam.AWSLambda_FullAccess] will be used instead.
```

So I assume supplying `policies` should work. On pulumi up it creates new `aws:iam:Role` , `aws:iam:RolePolicyAttachment` resources automatically. But this new Role doesn't get policy attached. It just creates empty Role.

**Comment by stack72** [comment]
Hi @shinebayar-g 

I'm sorry this has happened, please can you give me a snippet of code that allows me to test that your scenario is fixed when I look into this?

Paul

**Comment by shinebayar-g** [comment]
Sure, I'm testing this on latest SDK versions, if confirmed I'll paste example code.

**Comment by shinebayar-g** [comment]
Hmm. I mixed up the Stacks my bad. This is invalid bug report. Sorry. 🏳️

**Comment by stack72** [comment]
No worries @shinebayar-g - thanks for confirming for us!
