### ISSUE TITLE
Simple gesture for destroying/removing old stacks

### ISSUE THREAD

**Issue by mmdriley** [pulumi/pulumi#814]
I'm trying to clean up after a Travis test that created a Pulumi stack in the testing environment and then [exited before deleting the stack](https://travis-ci.com/pulumi/pulumi-service/jobs/106449891#L1285-L1292).

I have to piece together the ambient local state (owner, repo) from the test config and CLI and then get those values right in my local CLI (including setting up a directory with a `Pulumi.yaml`!) so I can delete that stack.

Instead, I should be able to `pulumi login` with the appropriate access key and API endpoint, list _all_ stacks this user has access to, recognize the one I want to delete, and delete it. This should work from an empty directory.

**Comment by ellismg** [comment]
With the first class provider changes, we should no longer need to do `pulumi config refresh -f`, which I think gets us to a place where we can make `pulumi destroy -s <stack-name> --force` just work without having to write a dummy Pulumi.yaml file or call `pulumi config refresh` since all the configuration relevant to the providers is now stored in the checkpoint.

**Comment by joeduffy** [comment]
I believe this is done. @ellismg @justinvp @chrsmith please correct me if wrong, and reopen.

**Comment by hubert-da** [comment]
Just for reference, this trick doesn't work if your config has secrets. The `destroy -f` command fails on:
```
error: failed to decrypt encrypted configuration value 'canton:artifactory-password': cipher: message authentication failed
This can occur when a secret is copied from one stack to another. Encryption of secrets is done per-stack and
it is not possible to share an encrypted configuration value across stacks.

You can re-encrypt your configuration by running 'pulumi config set canton:artifactory-password [value] --secret' with your
new stack selected.

refusing to proceed
```
