### ISSUE TITLE
Launch Darkly Provider Pulumi

### ISSUE THREAD

**Issue by thorpgeek** [pulumi/pulumi#8143]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Would love to be able to use Pulumi with Launch Darkly, There seems to be a Terraform provider https://github.com/launchdarkly/terraform-provider-launchdarkly

**Comment by mitchellmaler** [comment]
@stack72 Do you know if this can be added?

**Comment by juniorb2ss** [comment]
It would be great to have this adapter! :)

**Comment by ddaniel-dt** [comment]
This would be awesome to have!

**Comment by jaxxstorm** [comment]
Hey folks! The Launch Darkly provider is here!

https://github.com/lbrlabs/pulumi-launchdarkly

I'll add it to the registry in a few days once it's been battle tested

**Comment by stack72** [comment]
Delighted to be able to close this out! Thank you @jaxxstorm :)
