### ISSUE TITLE
[auto/go] Secret annotation in automation API is inconsistent with CLI behavior 

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi#8170]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
For object type outputs containing deeply nested secrets, the way automation api annotates secrets doesn't match the CLI. Take the following example:
```
import * as pulumi from "@pulumi/pulumi";


export const foo = {
    secret: pulumi.secret("this is a secret"),
    notSecret: "not a secret"
}
```
The CLI results in the following:
```
Outputs:
    foo: {
        notSecret: "not a secret"
        secret   : "[secret]"
    }
```

While automation api annotates `foo` as not-secret. This can result in clients of automation api leak secrets inadvertently - see https://github.com/pulumi/pulumi-kubernetes-operator/issues/204

One thought is that the CLI should treat the entire `foo` object as secret or automation api should support nested output values and correctly annotate nested values.

Another option is to allow clients perform the translation on their end instead by providing access to the raw outputs. i.e. provide an alternative to https://github.com/pulumi/pulumi/blob/master/sdk/go/auto/local_workspace.go#L465 which looks something as the following:
```
func (l *LocalWorkspace) StackOutputsRaw(ctx context.Context, stackName string, showSecrets bool) (map[string]interface{}, error) {
	// standard outputs
	outStdout, outStderr, code, err := l.runPulumiCmdSync(ctx, "stack", "output", "--json", /*--show-secrets if showSecrets is true */ "--stack", stackName)
	if err != nil {
		return nil, newAutoError(errors.Wrap(err, "could not get outputs"), outStdout, outStderr, code)
	}

	var outputs map[string]interface{}

	if err = json.Unmarshal([]byte(outStdout), &outputs); err != nil {
		return nil, errors.Wrapf(err, "error unmarshalling outputs: %s", secretStderr)
	}

        return outputs, nil
}
```

Note that this might affect more than just the go automation API. 

### Steps to reproduce

1. Run above program on the CLI and through go automation API to invoke the StackOutputs on the stack.

Expected: Consistent behavior across CLI and automation API
Actual: mislabeled secret information resulting in https://github.com/pulumi/pulumi-kubernetes-operator/issues/204

**Comment by EvanBoyle** [comment]
Here is a workaround we could easily implement at the SDK level:

https://github.com/pulumi/pulumi/blob/2e5fedff544f21d3aafdd15d1f4326f9afa8241b/sdk/go/auto/local_workspace.go#L492-L497

We could change the secretness check to something along the lines of:

```go
raw := string(json.Marshal(outputs[k]))
isSecret := strings.Contains(raw, secretSentinel)
```

However we would now have a subtle difference in behavior between automation API and CLI. @komalali, thoughts? 

I will say that the CLI behavior is surprising. If that top level `foo` export was an output instead of a JS object, it would be marked as secret...

**Comment by lblackstone** [comment]
A couple questions to make sure we're on the same page here:

1. Does this workaround need to be implemented in each SDK, or just in the spot that @EvanBoyle noted?
2. We're hoping to land this change today in support of https://github.com/pulumi/pulumi-kubernetes-operator/issues/204. Should I take this issue, or does someone on platform/core want to take it?
