### ISSUE TITLE
Make ts-node a peer dependency

### ISSUE THREAD

**Issue by dmattia** [pulumi/pulumi#8177]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

the nodejs sdk specifies ts-node and typescript versions in its dependencies: https://github.com/pulumi/pulumi/blob/a92a005d6897506d3ea40307dfd37788c51a4dcf/sdk/nodejs/package.json#L24-L25

I've been hitting issues using `"ts-node": "=8.10.2"` in my own project where I frequently see errors when I run `pulumi up` like:

<img width="1273" alt="Screen Shot 2021-10-08 at 11 12 31 AM" src="https://user-images.githubusercontent.com/8922077/136596102-14e457b7-14d5-4b74-864f-975cd46133c9.png">

I can work around this by using yarn resolutions, like:

```json
"resolutions": {
    "ts-node": "=8.10.2"
  },
```

but this affects ts-node in my entire yarn workspace, which is not what I want.

By making ts-node a peer dependency (still with a minimum version specified), it would be easier to bring my own version I want to use.

### Affected area/feature

Pulumi nodejs sdk

**Comment by komalali** [comment]
Hi! This is an interesting idea. FWIW, there is context on why we have avoided updating ts-node thus far and are pinned to this version: https://github.com/pulumi/pulumi/issues/4876

**Comment by dmattia** [comment]
A message from the Slack has another workaround idea (https://pulumi-community.slack.com/archives/C84L4E3N1/p1633725538463200): 

```text
we have similar issues very often - compiling typescript works, ts-node throws weird errors. We tweaked our tsconfig to match ts-node requirements closer, but we still get them.
We are now investigating disabling ts-node entirely and running @pulumi/pulumi on compiled code. Oddly, a service fails without an error, though it deploys with TS enable and with the CLI …
Btw, we’re using ts-node 10.* - had fewer issues than with 8.*
```

I can try running on already built typescript code, but that is still unideal.

**Comment by dixler** [comment]
@dmattia thanks again for the PR. We're trying to think about ways to introduce the changes described in #10122 without breaking people's projects if we want to do this before 4.0.

cc @RobbieMcKinstry  @t0yv0

**Comment by julienp** [comment]
Done in https://github.com/pulumi/pulumi/pull/15622
