### ISSUE TITLE
Do not generate Go inputty types for output-only schema types

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#8194]
A lot of schema types in some providers (azure-native, google-native) are output-put, i.e. they are used to define the structure of resource outputs but never resource inputs. For example, in `azure-native` those types will have a `Response` suffix.

Our current Go codegen would generate a full set for types for those schema types, including inputty types. In order to reduce the size of Go SDKs, particularly in azure-native, it would make sense to avoid generating those unneeded types.

**Comment by emiliza** [comment]
Closing, fixed by https://github.com/pulumi/pulumi/pull/7943
