### ISSUE TITLE
ReplaceOnChanges - strconv.ParseInt

### ISSUE THREAD

**Issue by markgould** [pulumi/pulumi#8197]
I'm trying to use ReplaceOnChanges for an AKS cluster to replace when the availabilityZones change. I'm doing this right now:
```
                ReplaceOnChanges =
                {
                    "agentPoolProfiles[*].availabilityZones"
                }
```

I get the error:
error: invalid array index: strconv.ParseInt: parsing "*": invalid syntax

Shouldn't I be able to use the * syntax in an array? I'm having to do this as a workaround currently:

```
  ReplaceOnChanges =
                {
                    "agentPoolProfiles[0].availabilityZones",
                    "agentPoolProfiles[1].availabilityZones"
                }
```

**Comment by iwahbe** [comment]
I suspect this will work:
```
                ReplaceOnChanges =
                {
                    "agentPoolProfiles["*"].availabilityZones"
                }
```

I'm not 100% sure though.

We might want to consider accepting [*] for the future. @justinvp what do you thing?
