### ISSUE TITLE
unittesting python Pulumi

### ISSUE THREAD

**Issue by nab-gha** [pulumi/pulumi#8217]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Trying to run unit tests for python project

### Steps to reproduce

See https://github.com/paulcarlton-ww/pulumi-python-examples

```
git clone https://github.com/paulcarlton-ww/pulumi-python-examples
cd pulumi-python-examples/example1
virtualenv venv
source venv/bin/activate
export PULUMI_PYTHON_PROJECT=example-one
export PULUMI_PYTHON_STACK=example-one
export PULUMI_CONFIG=$(yq eval Pulumi.${PULUMI_PYTHON_STACK}.yaml --output-format=json | jq -c '.config')
pytest
```
Expected: Unittest to run
Actual: failed to process stack yaml.

```
ERROR test_server.py - pulumi.config.ConfigMissingError: Missing required configuration variable 'project:application'
```

Yet the same yaml file works when doing `pulumi up`

**Comment by emiliza** [comment]
Hi @paulcarlton-ww - sorry about the inconvenience! We have this as an enhancement being tracking in https://github.com/pulumi/pulumi/issues/4472

This thread provides a workaround  https://github.com/pulumi/pulumi/issues/4472#issuecomment-618053293 that should get you unblocked.
