### ISSUE TITLE
Improve CLI debugging in automation api

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#8231]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

At the moment, it's sometimes difficult to debug the error messages from the CLI when using automation API.

Example is here: https://pulumi-community.slack.com/archives/C019YSXN04B/p1631922087059900

Is it possible to add a `debug` config option to the `stack.up()` method or similar?

### Affected area/feature

Automation API

**Comment by roderik** [comment]
Some context on why we need it:

We use a queuing system in node that does pulumi up via the automation api. We use separate processes to do this due the concurrency limitations but they do process pulumi up on different stacks sequentially. We notice that when we use a stackreference to an output that is not there (a kubeconfig for a cluster we do not run in staging), that the pulumi up errors out like you would expect. But, if this happens, the next runs fails with "One or more errors occured" with no errors in the console, the pulumi output, or anywhere. As soon as our queue timeout is reached, we get an error that it closed a job that was left running. After this, the jobs process correctly again.

We need this debugging capability to figure out what pulumi thinks this "One or more errors" is, so we can file correct tickets about this. For now, we try catch the pulumi up, and on error force an exit(1) so the process is restarted fully on the next job.

**Comment by EvanBoyle** [comment]
Is this a dupe of https://github.com/pulumi/pulumi/issues/5855?

**Comment by komalali** [comment]
Have you tried using the `onEvent` callback to look at the `DiagnosticEvent`s for more details?

**Comment by roderik** [comment]
> Have you tried using the `onEvent` callback to look at the `DiagnosticEvent`s for more details?

We are logging with `onOutput`, does `onEvent` expose more info?

**Comment by pierskarsenbarg** [comment]
Closing as duplicate
