### ISSUE TITLE
[Automation] Add API to import resources into state (`pulumi import`). 

### ISSUE THREAD

**Issue by tmccombs** [pulumi/pulumi#8237]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'd like to have support for importing resources in the automation API. I've got something that sort of works by registering a StackTransformation that adds `import` to the resource options. However, it 's a little bit clunky, and the import has to be done at the same time as an update, and the current state has to exactly match the configuration, which complicates some things as we transition to using Pulumi. What I'd like is an API that takes the urn or equivalent, and the import id, and imports it into the state without generating the pulumi code, or checking that it matches the current configuration.

### Affected area/feature

Automation API

**Comment by tmccombs** [comment]
If you are referring to " I've got something that sort of works by registering a StackTransformation that adds import to the resource options." I meant that my program using the automation API was injecting a `StackTransformation` before it runs the rest of the inline program, not a branch of pulumi.

**Comment by Ares3266** [comment]
@tmccombs yeah I'd be intrigued to see how you've managed that in your program. The implementation I've got is a lot more dysfunctional than that.

**Comment by tmccombs** [comment]
basically I have a funciton like this:

```
export async function registerImportTransformation(imports: Imports): Promise<void> {
    registerStackTransformation((args: ResourceTransformationArgs) => {
        const fullName = args.type + '$' + args.name;
        let id = imports[fullName];
        if (!id) {
            return undefined;
        }
        return {
            opts: mergeOptions(args.opts, {
                import: id,
            }),
            props: args.props,
        };
    });
}

````

And my inline program looks like:

```

() => {
   if (onStart) {
     await onStart();
   }
   return await realProgram();
}
```

And if the preview or up command is importing something, then it loads the imports from JSON and calls

```
onStart = registerImportTransformation.bind(undefined, imports);
```
before running preview/up on the stack.

**Comment by yarinm** [comment]
Any update about this? We also have a use case for that

**Comment by Zaid-Ajaj** [comment]
The following PRs implement the import functionality via the automation API

[[nodejs/autmation] Implement Stack.import() to specify and import resources into a stack #16615](https://github.com/pulumi/pulumi/pull/16615)
[[dotnet/automation] Implement Stack.ImportAsync() for batch importing resources into a stack pulumi/pulumi-dotnet#296](https://github.com/pulumi/pulumi-dotnet/pull/296)
[[python/automation] Implement Stack.import_resources() for batch importing resources into a stack #16668](https://github.com/pulumi/pulumi/pull/16668)
[[go/automation] Implement Stack.ImportResources() for batch importing resources into a stack via the automation API #16721](https://github.com/pulumi/pulumi/pull/16721)

Closing as resolved ✅
