### ISSUE TITLE
Outputs remain in stack after corresponding resource has been deleted

### ISSUE THREAD

**Issue by christophermaier** [pulumi/pulumi#8273]
- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I have written a function that creates a resource and exports a value from that resource. I call this function several times in the course of a Pulumi program, creating the desired resources and generating the desired outputs. After some refactoring, however, I determined that these resources weren't needed in the current project, so I removed the function and all the call sites.

When I ran `pulumi up`, it deleted all the resources, as expected, and the diff output also indicated that all the corresponding stack outputs were also deleted. However, running `pulumi stack` showed one of the outputs remained, even though its corresponding resource was deleted. Repeated calls to `pulumi up` showed a diff output suggesting that the remaining output was deleted, but `pulumi stack` showed that it still remained.

A bit of experimentation with adding these resources back and deleting them again suggests that it wasn't any particular resource that was triggering it, but I always had one output left behind. Since my stack had no other outputs aside from these I'm describing, there may be some kind of edge condition I was triggering at the transition from 1 to 0 outputs, but that's pure speculation on my part.

I ultimately ended up fixing the problem by running `pulumi stack export`, editing the resulting JSON, and then running `pulumi stack import`.

I unfortunately cannot provide a reproduction case, but I was using the following software:
- Pulumi CLI 3.12.0
- Pulumi Python SDK 3.13.2
- Pulumi Hashicorp Vault Provider 4.5.0; the resources in question were instances of [pulumi_vault.identity.Entity](https://www.pulumi.com/registry/packages/vault/api-docs/identity/entity/)

**Comment by Gambitran** [comment]
Same exact behavior for me as well if it's the last output available.

Resolved the same way OP mentioned.

1. `pulumi stack export --file export.json`
2. Edit export.json
3. `pulumi stack import --file export.json`
4. `pulumi up`
5. Output removed from console
