### ISSUE TITLE
Imported Resource Names are Changed to Snake Case for Go Programs

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#8295]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

As a developer, I want to import existing resources into a new Pulumi Go program so I can put these existing resources under Pulumi's control. The problem is the generated Go program changes all resource names to `snake_case` which causes Pulumi to delete and recreate resources, if those existing resources are not snaked cased and include separators like hyphens.

### Steps to reproduce

1. Create/Find resources which has a hyphen. Eg- `my-test-vpc-asdf`.
2. Create a new Pulumi Go program - `mkdir import-issue && cd import-issue && pulumi new aws-go`
3. Create JSON file which contains the resources to import. Call it resources.json or whatever you want. (see below)
4. Run `pulumi import --file resources.json`
5. Replace your `index.ts` contents with the generated code.
6. Unprotect the imported resource.
7. Run `pulumi preview` and view CLI output.

Expected: Pulumi should not need to update any resources as no changes have been made.
Actual: Pulumi wants to delete the existing resource and replace it due to naming changes.

### Hyphen Names Changed to Snake Case
![image](https://user-images.githubusercontent.com/25461821/138917628-a497bf5d-e8b5-4da9-b3e7-fb83fed94c15.png)

### Preview of Delete/Replace
![image](https://user-images.githubusercontent.com/25461821/138917530-58a37f5a-e4ae-4f8e-86b6-0d29587833ac.png)

## Sample files
resources.json
```
{
	"resources": [{
			"type": "{type of your resource}",
			"name": "{name of your resource}",
			"id": "{id of your resource}"
		}
	]
}
```

Sample used for test
```
{
	"resources": [{
			"type": "aws:ec2/vpc:Vpc",
			"name": "my-test-vpc",
			"id": "vpc-022f8da0496290b02"
		}
	]
}
```

**Comment by justinvp** [comment]
This regressed with #4915 back in June 2020.
