### ISSUE TITLE
Allow dynamic querying of resources

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#83]
There may be circumstances in which we want to dynamically discover resources.

For example, when reverse engineering the LumiGL from an existing environment, we may have an object moniker and/or set of properties in hand, and want to discover a resource's ID, if any.  There is no reason we couldn't support an API like the following on `ResourceProvider`, for examples:

    rpc Find(moniker, properties) returns (id) {}

Going even further beyond that, we may eventually want a way in Lumi programs themselves to look up resources dynamically.  For example, imagine our organization has set up an ECS cluster, and we simply want to plug into that.  It would be reasonable to write code like this:

    let cluster = aws.ecs.Cluster.find("id");
    let container = new aws.ecs.Container({ cluster: cluster, ... });

It's not clear what `"id"` we would use for this, but presumably the object moniker would be a great place to start.  In that case, the hypothetical `ResourceProvider.Find` API above would do the trick. 

It's possible we would want to support more sophisticated queries (eventually), however we need to be careful not to lead people down a bad path.  For instance, hard-coding an ARN into a Lumi program would tie that program to a specific deployment, whereas the moniker is sufficiently "logical" that it wouldn't interfere with multi-instancing, etc.

**Comment by lukehoban** [comment]
@hausdorff did some prototyping of `list` operations for the `@pulumi/kubernetes` provider in particular in M21, but focused initially on the stack context, not the target cloud provider context.  We'll be looking at building upon that in future milestones.

**Comment by ellismg** [comment]
We'll land the first part of this (querying against an existing stack's state, not live resources) in https://github.com/pulumi/pulumi/pull/2630.

**Comment by lukehoban** [comment]
Opened #83 as a more up-to-date tracking item for the remaining piece of this.
