### ISSUE TITLE
Import is incomplete and inconsistent

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi#8300]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When importing a `vault.okta.AuthBackendUser` via `pulumi import`, the generated code and imported state is incorrect as the `Groups` property has a `nil` value when it should have a real value. This is also inconsistent. Sometimes the code and state are correct, and sometimes it is incorrect.

I've not tried reproduce this with other resource types.

### Actual resource details

```
% vault read auth/user_okta/users/foo
Key         Value
---         -----
groups      [one two]
policies    []
```

### Correct code (snippet)

```
Groups: pulumi.StringArray{
        pulumi.String("one"),
        pulumi.String("two"),
},
``` 

### Incorrect code (snippet)

```
Groups: pulumi.StringArray{
        nil,
        pulumi.String("two"),
},
``` 

### Correct state (snippet)

```json
"inputs": {
    "__defaults": [],
    "groups": [
        "one",
        "two"
    ],
    "path": "user_okta",
    "username": "foo"
},
``` 

### Incorrect state (snippet)

```json
"inputs": {
    "__defaults": [],
    "groups": [
        null,
        "two"
    ],
    "path": "user_okta",
    "username": "foo"
},
``` 

### Steps to reproduce

1. `vault server -dev` in one terminal
2. `pulumi up` the code at https://gist.github.com/clstokes/e41eb035cc08812c9442cec1ba552dde
3. pulumi stack init imported
4. `pulumi import vault:okta/authBackendUser:AuthBackendUser main user_okta/foo -y`
5. observe incomplete code and state
6.  repeat with `pulumi state delete urn:pulumi:imported::pulumi-vault::vault:okta/authBackendUser:AuthBackendUser::main --force -y && pulumi import vault:okta/authBackendUser:AuthBackendUser main user_okta/foo -y` if doesn't reproduce the first time
7. run with `TF_LOG=trace ...` to see the API request and response details from Vault. It is always correct in my testing.

Expected: code and state should be correct every time
Actual: sometimes is correct, most times is incorrect

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in #8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
