### ISSUE TITLE
[go sdk] Can anyone introduce the built-in types of pulumi?

### ISSUE THREAD

**Issue by mritd** [pulumi/pulumi#8317]
I am a newbie to pulumi and described in the document that pulumi uses Input/output to determine dependencies. But when actually writing the code, I found that pulumi has similar built-in types:

```go
Int
intInput
IntOutput
IntPtrInput
IntPtrOutput
```

Can someone help me explain which type should be used under what circumstances?

**Comment by emiliza** [comment]
Hi! These types are also defined in the code https://github.com/pulumi/pulumi/blob/master/sdk/go/pulumi/types_builtins.go - hope this helps!

- Int is an input type for int values.
- IntInput is an input type that accepts Int and IntOutput values.
- IntOutput is an Output that returns int values.
- IntPtrInput is an input type that accepts IntPtr and IntPtrOutput values.
- IntPtrOutput is an Output that returns *int values.
