### ISSUE TITLE
Provider docs not showing env vars for nested types

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi#8323]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The API Reference for complex types in the Provider resources aren't showing the env var usage:
https://www.pulumi.com/registry/packages/kubernetes/api-docs/provider/#burst_nodejs

Compare this to:
https://www.pulumi.com/registry/packages/kubernetes/api-docs/provider/#suppresshelmhookwarnings_nodejs

**Comment by leezen** [comment]
11/30 Triage: We have a number of issues w/ the generator and not a ton of context on it on the team at the moment. Let's schedule time in an upcoming iteration to tackle them together.
