### ISSUE TITLE
Unable to import AWS EfsLocation

### ISSUE THREAD

**Issue by lyenliang** [pulumi/pulumi#8326]
## Unable to import AWS EfsLocation

I followed [this document](https://www.pulumi.com/registry/packages/aws/api-docs/datasync/efslocation/#import) to import one of my AWS DataSync location to pulumi. But something went wrong.

### Steps to reproduce

1. Run `pulumi import aws:datasync/efsLocation:EfsLocation dest_efs_location arn:aws:datasync:ap-southeast-1:012345678901:location/loc-01bf52940d19157a7`.
2. The above command would create the following error message
```
    error: aws:datasync/efsLocation:EfsLocation resource 'dest_efs_location' has a problem: Missing required argument: The argument "efs_file_system_arn" is required, but no definition was found.. Examine values at 'EfsLocation.EfsFileSystemArn'.
    error: Preview failed: one or more inputs failed to validate
```

Expected: I expect that the location can be imported correctly.
Actual: I encountered the following error message.
```
    error: aws:datasync/efsLocation:EfsLocation resource 'dest_efs_location' has a problem: Missing required argument: The argument "efs_file_system_arn" is required, but no definition was found.. Examine values at 'EfsLocation.EfsFileSystemArn'.
    error: Preview failed: one or more inputs failed to validate
```

My pulumi version is `v3.16.0`.

**Comment by emiliza** [comment]
Hi @lyenliang - sorry about this inconvenience, this is an issue with how we're performing imports. I'll close this out as a dupe, as the greater issue is being tracked in https://github.com/pulumi/pulumi/issues/7160
