### ISSUE TITLE
How do I use Get* methods from within a constructor?

### ISSUE THREAD

**Issue by atrauzzi** [pulumi/pulumi#8334]
- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

It's very unclear how I should use the values from `Get*` methods in my `Stack`.

_I'm using C#/.NET._

### Steps to reproduce

```csharp
    public MyStack()
    {
        // ...
        var defaultNetwork = await GetNetwork.InvokeAsync(new()
        {
            Network = "default",
        });
        // ...
    }
```

**Expected:** I think I was expecting this to return something that implements `Resource` that represents something preexisting in my infrastructure which is *not* being managed by Pulumi, but that can still participate in the dependency graph.

**Actual:** I can't resolve the promise because Pulumi conventions dictate that I do all my work in my stacks constructor.

---

There's probably a documentation problem somewhere in here because I've tried my best to look for some prior art before coming to open this ticket.  Is there no conventional guidance on how to use `Get*` methods?

**Comment by emiliza** [comment]
Great questions @atrauzzi! We have an [examples repo](https://github.com/pulumi/examples) that could be helpful.

I think for the first half of your question:
> represents something preexisting in my infrastructure which is not being managed by Pulumi

You could attempt to try to [import](https://www.pulumi.com/docs/guides/adopting/import/) this resource.

As for resolving promises, you'll want to look at using [outputs](https://www.pulumi.com/docs/intro/concepts/inputs-outputs/), and try something like:
`var defaultNetwork = Output.Create(GetNetwork.InvokeAsync()).Apply(...)`

Depending which version of Pulumi and cloud provider you're using, you might be able to simplify this with `GetNetwork.Invoke(new ... ).Apply()`

Hope this helps!

**Comment by atrauzzi** [comment]
Thanks @emiliza --

What if the GetNetwork call depends on a service being enabled?  Is there any way to defer the call so that it only happens after the service it depends on has been created?

**Comment by emiliza** [comment]
@atrauzzi Yep! Take a look at `dependsOn` https://www.pulumi.com/docs/intro/concepts/resources/#dependson

**Comment by atrauzzi** [comment]
It doesn't look like InvokeAsync doesn't accept that parameter.

**Comment by justinvp** [comment]
Hi @atrauzzi, you should be able to do something like this:

```c#
        var defaultNetwork = computeService.Id.Apply(_ => GetNetwork.InvokeAsync(new()
        {
            Network = "default",
        }));
```
