### ISSUE TITLE
replaceOnChanges, but for changes to a separate resource.

### ISSUE THREAD

**Issue by inhumantsar** [pulumi/pulumi#8340]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

For certain resources, it would be useful if replacement could be triggered on resources whenever a specified resource is replaced. 

In my specific use-case, if an ECS Service is replaced while it has an Autoscaling Policy and Target attached, the attachments are lost and both autoscaling resources must be recreated manually. 

While `--target-replace` works, but it's kind kludgy to do `pulumi up` and then `pulumi up --target-replace <some really long urn>`. It would be really useful to have a resource option for this.

### Affected area/feature

Pulumi Resources, potentially just the AWS module.

**Comment by emiliza** [comment]
Hi @inhumantsar thanks for filing! 

Sounds like you may be asking for https://github.com/pulumi/pulumi/issues/838? If so, please take a moment to upvote and we'll close this out as a dupe

**Comment by inhumantsar** [comment]
Hey @emiliza that is exactly what I'm after. 

Surprised it's not requested that often. Guess it won't be happening any time soon 😔
