### ISSUE TITLE
Changing parenting of a resource changes it's name, forcing recreation

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#837]
We recently made a change to include the parent type in the URN for a resource (as well as the type of the resource itself).

This had the unfortunate side effect of making it a breaking change to introduce a parent-child relationship where there was not one (or vice versa).  Because the name changes, we actually observe this as a creation of an entirely unrelated resource, then a deletion of the previous resource.

For example, we would love to take our `awsinfra.Network` abstraction and make it a `pulumi.ComponentResource` that took ownership of all the resource it creates.  Unfortunately though, doing so would result in tearing down and recreating all resources in all stacks that use it.  Even though it doesn't require any changes to physical resources - just a reorganization of the Pulumi view of nesting.

**Comment by lukehoban** [comment]
From another place this was hit in #1877: 

> Situation: I created a DNS record via Route 53. For organization purposes, I then decided I wanted to make it a child of another resource for the sake of clarity. So I added { parent: p } to my child record.

> A fully logical (no change in inputs) re-parenting should probably just work.

**Comment by protometa** [comment]
On the other hand, I'm really surprised to be finding out that the the URNs of children don't include the name of the parent... I thought components provided similar namespacing as stacks. Now none of my components can be instantiated more than once 😫

**Comment by protometa** [comment]
As for ideas, the unique id of a resource can be (and probably should be) an immutable random token. Then every resource would also have a unique but mutable address in the hierarchy of stack/component/resource names, kind of like a filesystem.

**Comment by lukehoban** [comment]
Closing as a dupe of #458 which is tracking the proposed fix for renaming resources generally, including re-parenting them.

**Comment by GaboFDC** [comment]
#458 final implementation doesn't solve this issue. Is still an ongoing issue.

**Comment by lukehoban** [comment]
> 458 final implementation doesn't solve this issue. Is still an ongoing issue.

#458 provides a way to change the parent without a replacement by specifying what the previous parent was so that it is known that this is the "same resource".  Are you saying that you would like to be able to change the parent without adding an `alias` and have this "just work"?

**Comment by GaboFDC** [comment]
> #458 provides a way to change the parent without a replacement by specifying what the previous parent was so that it is known that this is the "same resource". Are you saying that you would like to be able to change the parent without adding an `alias` and have this "just work"?

Sorry, I didn't read completely and missed that it was possible to do it, make it "just work" would be ideal, but also I get that may be difficult to implement. Maybe what is needed is to have better documentation about this possibility of using alias, and how to do it, maybe with some examples. Because from what I saw, the only way to know how to do it right now is checking the GitHub issues and PRs
