### ISSUE TITLE
Unable to download plugin random for darwin-arm64 pre v3.1

### ISSUE THREAD

**Issue by robertvanhoesel** [pulumi/pulumi#8378]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
It seems some plugins versions are not provided in Apple Silicon (dawrin-arm64) format, and I have not found a way to work around it (i.e. force a higher version).

When running a v2 project for the first time on a new Apple Silicon machine, the CLI it gave the below error message, with a suggested command to install the plugin. 

However, running the command gives a 403 on the [plugin download location](https://get.pulumi.com/releases/plugins/pulumi-resource-random-v2.2.0-darwin-arm64.tar.gz). It's clear it has [not been released](https://github.com/pulumi/pulumi-random/releases/tag/v2.2.0) for Arm64. 

```
> pulumi up
Previewing update (******)

View Live: https://app.pulumi.com/****/****/previews/******-******-*****-******

[resource plugin postgresql-2.10.0] installing
Downloading plugin: 15.50 MiB / 15.50 MiB [=========================] 100.00% 2s
 
error: could not load plugin for random provider 'urn:pulumi:****::****::pulumi:providers:random::default_2_2_0': 
no resource plugin 'random-v2.2.0' found in the workspace or on your $PATH, 
install the plugin using `pulumi plugin install resource random v2.2.0`

> pulumi plugin install resource random v2.2.0
error: [resource plugin random-2.2.0] downloading from : 403 HTTP error fetching plugin
from https://get.pulumi.com/releases/plugins/pulumi-resource-random-v2.2.0-darwin-arm64.tar.gz
```

I assume this is an issue that needs fixing, especially as I have found no way to work around it by forcing a higher version. I attempted several things:
- Downgrading the CLI all the way to v2
- Upgrading all project dependencies to v3 (I can't seem to force the plugin system to resolve to random provide a v3)
- Removing all node modules, uninstalling Pulumi
- Installing the latest random package manually, and running pulumi up

What I will still attempt:
- Upgrade the project dependencies on a amd machine to versions that also have an arm version.

<details>
<summary><code>pulumi about</code></summary>
<pre>
CLI          
Version      3.17.0
Go Version   go1.17.2
Go Compiler  gc

Host     
OS       darwin
Version  12.0.1
Arch     arm64

Backend  
Name     pulumi.com
</pre>

</details>

### Steps to reproduce

Expected: 
- Arm64 plugins are available
- Or getting unsupported message `error: [resource plugin radnom] downloading from : unsupported plugin architecture: arm64`

Actual: 
- Pulumi cli thinks package is available but it's not. 

Related https://github.com/pulumi/pulumi/issues/4868

**Comment by stack72** [comment]
Hi @robertvanhoesel 

So we wrote a small troubleshooting guide regarding this - https://www.pulumi.com/docs/troubleshooting/#403-http-error-fetching-plugin

Unfortunately, we won't be back porting ARM to earlier versions of plugins - I am hopeful that the guide made help

Please do let me know if it doesn't and we can work through this with you

Paul

**Comment by robertvanhoesel** [comment]
Hi Paul,

Thanks for the link – seems my assumption is correct then! Would it be possible at all for the cli to prevent these package gets for unsupported versions and instead link to the troubleshoot?
