### ISSUE TITLE
Pulumi CLI not prompting for passphrase for the commands after "pulumi up" - AWS Python getting started

### ISSUE THREAD

**Issue by vigneshnin** [pulumi/pulumi#8386]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I was following the getting started instrcution for AWS and I created the S3 bucket with "pulumi up", but after that, when I moved on to the next step to see the output bucket_name, the following error comes.

```
error: constructing secrets manager of type "passphrase": unable to find either `PULUMI_CONFIG_PASSPHRASE` or `PULUMI_CONFIG_PASSPHRASE_FILE` when trying to access the Passphrase Secrets Provider; please ensure one of these environment variables is set to allow the operation to continue
```

I am able to fix this after running the following command
`export PULUMI_CONFIG_PASSPHRASE=12345678`

Even thought there is an option to set the environment variable for easily working with pulumi while using the passphrase, the CLI must prompt for the passphrase if the environment variable is not already set. This must also be mentioned in the Getting startted documentation if this is an intended behaviour.

### Steps to reproduce

1. Follow the instruction for python in [AWS python instructions](https://www.pulumi.com/docs/get-started/aws/deploy-stack/)
2. Run `pulumi up` and wait for the execution to complete
3. Run `pulumi stack output bucket_name`  

Expected:  See the output bucket name after prompting for the passphrase
Actual: The error mentioned above is shown

**Comment by leezen** [comment]
@vigneshnin Had you run `pulumi login` at any point prior to this and if so, could you please describe how you ran that command (with what arguments)?

**Comment by vigneshnin** [comment]
@leezen Yes! I did login to Pulumi but only as local `pulumi login --local`

**Comment by leezen** [comment]
@vigneshnin Thanks -- that explains the behavior then. If you log into the local backend, then the expectation is that you'd need to also configure a secrets provider for the stack.
