### ISSUE TITLE
error: gcp:serviceAccount/account:Account resource  doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$"

### ISSUE THREAD

**Issue by raphaelauv** [pulumi/pulumi#8388]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

```log
Diagnostics:
  gcp:serviceAccount:Account (service_account_Compute_Engine_default_service_account):
    error: gcp:serviceAccount/account:Account resource 'service_account_Compute_Engine_default_service_account' has a problem: "account_id" ("5822921XXXX-compute") doesn't match regexp "^[a-z](?:[-a-z0-9]{4,28}[a-z0-9])$". Examine values at 'Account.AccountId'.
    error: Preview failed: one or more inputs failed to validate
 
  pulumi:pulumi:Stack (XXXX-prod):
    error: preview failed
```

impossible to import an existing service_account in my gcp project

```json
    {
      "id": "projects/XXXX/serviceAccounts/58229215XXX-compute@developer.gserviceaccount.com",
      "name": "Compute_Engine_default_service_account",
      "type": "gcp:serviceAccount/account:Account",
      "parent": "parent-main",
      "provider": "provider-main"
    },
```

Expected: I should be able to import an existing resource
Actual: I can't import it

**Comment by raphaelauv** [comment]
it's a bug on the gcp teraform provider -> https://github.com/hashicorp/terraform-provider-google/issues/7443

**Comment by aryehb** [comment]
According to [this](https://github.com/hashicorp/terraform-provider-google/issues/7443#issuecomment-4409805181) comment on that issue, this has been fixed in the Terraform provider.

However, I'm still experiencing this error with `@pulumi/gcp` `v9.23.0`.
