### ISSUE TITLE
tsconfig "module" conflict: project needs "esnext", pulumi needs "commonjs"

### ISSUE THREAD

**Issue by chrishoward** [pulumi/pulumi#8415]
## Hello!
- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
We are using pulumi (typescript) in a repository which also has a create-react-app application. Our tsconfig file has `"module": "esnext"` as required by create-react-app. We had no issues using pulumi v2.x.x as it ignored our tsconfig and used its own internal config [**here**](https://github.com/pulumi/pulumi/blob/272c4643b20d40113689475fd2f9fe3134e6d431/sdk/nodejs/cmd/run/run.ts#L171).

In pulumi v3.x.x it was changed to use the tsconfig found in the project root and override the internal pulumi options with `...compilerOptions`. Now our pulumi throws the error:

```pulumi:pulumi:Stack (roads-vicroads-ui-dev):
    error: Running program '/home/coder/my-repository' failed with an unhandled exception:
    /home/coder/my-repository/pulumi.ts:52
    import * as mime from "mime";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
        at wrapSafe (internal/modules/cjs/loader.js:988:16)
        at Module._compile (internal/modules/cjs/loader.js:1036:27)
        at Module.m._compile (/home/coder/my-repository/node_modules/ts-node/src/index.ts:439:23)
        at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
        at Object.require.extensions.<computed> [as .ts] (/home/coder/my-repository/node_modules/ts-node/src/index.ts:442:12)
        at Module.load (internal/modules/cjs/loader.js:937:32)
        at Function.Module._load (internal/modules/cjs/loader.js:778:12)
        at Module.require (internal/modules/cjs/loader.js:961:19)
        at require (internal/modules/cjs/helpers.js:92:18)
        at Object.<anonymous> (/home/coder/my-repository/node_modules/@pulumi/pulumi/cmd/run/run.js:219:31)
```

Attempts to change our tsconfig "module" value to "commonjs" see it forced back to "esnext" by create-react-app. 

Does pulumi support other module options? Is it possible to keep the module as commonjs for pulumi?
I'll create a PR for this approach for discussion.

### Steps to reproduce
1. Set up pulumi typescript
2. Set "module" to "esnext" in tsconfig.json
3. Run a pulumi preview command for example

Expected: In v2.x.x pulumi command works fine
Actual: In v3.x.x pulumi command fails with above error

**Comment by iwahbe** [comment]
Hi @chrishoward, 
This doesn't seem like a bug to me. You informed the Pulumi CLI that you wanted to use `"module": "esnext"` and that request was respected. You can write pulumi code with `"module": "esnext"` syntax:
```typescript
const aws = require("./node_modules/@pulumi/aws");

// Create an AWS resource (S3 Bucket)
const bucket = new aws.s3.Bucket("my-bucket");

// Export the name of the bucket
exports.bucketName = bucket.id;
```

Is it possible to have a different config for pulumi that is set to `"module": "commonjs"`? Alternatively you could refactor your Pulumi code to comply with `esnext`.  I don't think we can stop respecting the `"module"` setting at this point. It would be a breaking change for users who rely on `"module"`.

**Comment by chrishoward** [comment]
Hi @iwahbe 
Thanks for the explanation, I agree.

At the moment pulumi looks for `tsconfig.json`, and other libraries in the same repository (create react app in our case) are also looking for this file, and the settings of the file required for each consumer are now conflicting. What do you think about a change whereby pulumi looks for `tsconfig.json` and `tsconfig.pulumi.json` and if the latter exists it takes precendence and uses that?

This feels like a clean, non-breaking solution, and saves us having to do any trickery with our builds and renaming/restoring `tsconfig.something.json` files when we run certain pulumi/react commands etc.

**Comment by iwahbe** [comment]
I think that would be a viable solution to your problem. I don't love it for 2 reasons:
1. It adds another special value (`tsconfig.pulumi.json`) to remember.
2. Because we can't tell if the user intends to use `tsconfig.pulumi.json` if the file isn't present, we get silent fail over. For example, if you added `tsconfig.Pulumi.json`, the error message would be `syntax error` instead of missing config. 

What would you think of adding a runtime option in `Pulumi.yaml` that specifies where to find the tsconfig file. Then you could write:
```yaml
name: pulumi-project
runtime:
  name: nodejs
  options:
    tsconfig: mytsconfig.json
```
I think this solution is more in line with how we normally find project files. For example, we default to `index.ts` for launching your TS project, but if you set `main: start.ts` we will take `start.ts` as the program main file. 

@chrishoward What do you think? Would this solve your use case?

**Comment by chrishoward** [comment]
@iwahbe Being able to just specify the name of the tsconfig to use in Pulumi.yaml is a much nicer solution. The draft PR looks good. Is there anything further I can help with on this?

Thanks for your help!

**Comment by iwahbe** [comment]
@chrishoward If this works for you, I think we're all good. I'll clean up the PR. Unless the team has a better idea, we will get that merged soon. Thanks for bringing this to our attention.

**Comment by chrishoward** [comment]
@iwahbe Fantastic, thanks!
