### ISSUE TITLE
GCP Logging Project Sink not actually creating svc account via Python SDK

### ISSUE THREAD

**Issue by trevormarburger** [pulumi/pulumi#8426]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce

1. Create a gcp Logging Project Sink resource like the following:

```py
logging_sink = logging.ProjectSink(
    project                = os.environ.get('PULUMI_PROJ'),
    resource_name          = SINK_NAME,
    name                   = SINK_NAME,
    unique_writer_identity = True,
    destination            = Output.concat("pubsub.googleapis.com/", pubsub_topic.id),
    filter                 = render_storage_filters(path="./templates", file="log_filters.jinja2", bucket="<redacted>", filters=SINK_FILTERS)
)
```
2. Attempt to access the logging_sink.writer identity attribute afterward, in order to attach permissions via an IAM binding:
```py
iam_binding = serviceaccount.IAMBinding(
    resource_name      = "iam-binding",
    service_account_id = logging_sink.writer_identity,
    role               = "roles/pubsub.publisher",

    members = [
        logging_sink.writer_identity
    ]
)
```

**Expected**: IAM Binding would be attached, without `service_account_id` param needed (it's not in Terraform).  Also, the writer_identity service account "created" would be visible in the IAM dashboard in GCP following the creation by the `unique_writer_identity=True` param

**Actual**: The Service account created via the `unique_writer_identity=True` param is non-existent in the GCP Console nor via a `gcloud` query to list svc accts.  Additionally, the service account must be getting creating _somewhere_, because the error returned upon attempt to create the IAM Binding Resource includes the svc acct name `serviceAccount:p<redacted>-<redacted>@gcp-sa-logging.iam.gserviceaccount.com` and how it's not in the expected regex format of `projects/<project>/serviceAccounts/fooBar@googleserviceblah.com`, advised to "`Examine values at 'IAMBinding.ServiceAccountId'.`"

**Comment by emiliza** [comment]
Oh this is unfortunate - can you try using `projects.IAMBinding()` instead of `serviceaccount.IAMBinding()` and see if this helps? Also which version of the of pulumi-gcp are you using?

**Comment by trevormarburger** [comment]
@emiliza - I actually figured out this workaround earlier today!  However, seeing this would totally have saved me, so thank you.  I am on `Pulumi Version 3.17.0` and `pulumi-gcp 5.26.0`
