### ISSUE TITLE
Running `pulumi new` against a github repo without a master branch fails

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#8428]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When running `pulumi new` against a GitHub repo that has `main` as the default branch, Pulumi fails with the following error message:

```zsh
error: couldn't find remote ref "refs/heads/master"
```

### Steps to reproduce

Run the following: `pulumi new https://github.com/pierskarsenbarg/new-pulumi`

(that's a GitHub repo without a `master` branch)

If you create a master branch (even if it's not the default branch) it works.

Expected:  To clone and create a new project using the code in the repo
Actual:  Error message occurs

**Comment by justinvp** [comment]
In the meantime, you can workaround this by specifying the branch explicitly, e.g.:

```
pulumi new https://github.com/pierskarsenbarg/new-pulumi/tree/main
```
