### ISSUE TITLE
Dotnet 6 issues on m1 & m1max cpus - running pulumi up fails

### ISSUE THREAD

**Issue by stejsj** [pulumi/pulumi#8447]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We are unable to run pulumi up on our infrastructure projects on our new macbook pro m1max machines with dotnet 6 installed via homebrew. 

We get the following error:

Type                 Name                                  Plan     Info
     pulumi:pulumi:Stack  services-orchestration-dev-stejsj-t2           1 error; 5 messages

Diagnostics:
  pulumi:pulumi:Stack (services-orchestration-dev-stejsj-t2):
    A fatal error occurred. The required library libhostfxr.dylib could not be found.
    If this is a self-contained application, that library should exist in [/Users/sejensen/dev/chipper-orchestration/infra/bin/Debug/netcoreapp3.1/].
    If this is a framework-dependent application, install the runtime in the global location [/usr/local/share/dotnet/x64] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
    The .NET Core runtime can be found at:
      - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=osx.10.17-x64

    error: an unhandled error occurred: Program exited with non-zero exit code: 131
--------

Setting DOTNET_ROOT results in this error instead
  pulumi:pulumi:Stack (services-orchestration-dev-stejsj-t2):
    Failed to load A, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0/libhostfxr.dylib, 0x0001): tried: '/usr/local/share/dotnet/host/fxr/6.0.0/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libhostfxr.dylib' (no such file), '/usr/lib/libhostfxr.dylib' (no such file)
    The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0/libhostfxr.dylib failed
      - Installing .NET Core prerequisites might help resolve this problem.
         https://go.microsoft.com/fwlink/?linkid=2063366

    error: an unhandled error occurred: Program exited with non-zero exit code: 130

Expected: being able to run pulumi up with dothet 6 and m1 or m1 max cpus
Actual: fails to run

**Comment by stejsj** [comment]
Any ideas for progress on this issue? We are really strugling with not being able to run dotnet 6 on our m1 macs with pulumi.

**Comment by joeduffy** [comment]
@stejsj I don't have an m1 personally, so trying to do a bit of psychic debugging here. Did you install .NET 6 Arm64? If I am [reading this issue correctly](https://github.com/dotnet/sdk/issues/22380), .NET 6 x64 won't work on M1s yet due to [lack of x64 emulation support](https://github.com/dotnet/designs/blob/main/accepted/2021/x64-emulation-on-arm64/x64-emulation.md). My read of part of the error above ("have 'arm64', need 'x86_64'") indicates perhaps you've got the x64 installation which is leading to this error.

**Comment by rawkode** [comment]
@stejsj I've ran into this problem too and it appears to be related to the current release of the dotnet installer.

Ref: https://github.com/dotnet/installer/issues/12187

**Comment by ESipalis** [comment]
Quick workaround for M1 Macs - add the following to your csproj:
```
<PropertyGroup Condition="'$(NETCoreSdkRuntimeIdentifier)'=='osx-arm64'">
    <RuntimeIdentifier>osx-x64</RuntimeIdentifier>
</PropertyGroup>
```

This builds the program for x64 architecture, and then running `pulumi up` runs the build in x64 emulated mode.

No need for additional SDKs or anything, just have the latest .NET 6 Arm64 SDK.

**Comment by Zaid-Ajaj** [comment]
@ESipalis Tomorrow we will be releasing v3.7.0 of the Pulumi nuget packages. It should fix these issues and you won't need this type of workaround. Please consider taking it for a spin and let us know if you encounter any issues

**Comment by ESipalis** [comment]
@Zaid-Ajaj 

- Removed the workaround on `3.26.1`.
- Running `pulumi up` fails with GRPC error.
- Upgrade to `3.27.0` Pulumi nuget package.
- Running `pulumi up` succeeds!

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @ESipalis for confirming that is works 🎉
