### ISSUE TITLE
Allow for resources to be made "immutable"

### ISSUE THREAD

**Issue by atrauzzi** [pulumi/pulumi#8450]
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When replacing managed SSL certificate(s) for a Google Cloud load balancer, the new certificate creation returns prior to the certificate being viable.  This is totally normal and outside of Pulumis control as it's a slightly delayed process as the domain(s) go through a validation process.

Unfortunately, this also means that when Pulumi creates the new certificate(s), it's deleting the existing certificate which technically should be left in place while the new one provisions.

```csharp
            var names = string.Join("", myProject.InferredRecordSets
                .Where((recordSet) => recordSet.Domain == domain)
                .Select((recordSet) => recordSet.Name)
                .OrderBy((name) => name));

            var hashedNames = BitConverter
                .ToString(MD5.Create().ComputeHash(Encoding.UTF8.GetBytes(names)))
                .Replace("-", "")
                .Substring(0, 8)
                .ToLower();

            var name = $"{domain.Replace(".", "-")}-{hashedNames}";

            return new ManagedSslCertificate(
                name,
                options: new()
                {
                    Parent = managedZone,
                },
                args: new()
                {
                    Name = name,
                    Managed = new ManagedSslCertificateManagedArgs
                    {
                        Domains = myProject.InferredRecordSets
                            .Where((recordSet) => recordSet.Domain.Equals(domain))
                            .Select((recordSet) => recordSet.Name)
                            .ToList(),
                    },
                }
            );
```

I would like to requiest that Pulumi add the ability to have a resource "orphaned" from state when a change is detected.

This would have the effect of making the resource immutable.  Building on the example above, it'd be as simple as:

```csharp
                // ...
                options: new()
                {
                    Parent = managedZone,
                    Immutable = true,
                },
                // ...
```

With this flag set to `true`, the corresponding state would be deleted and the resource would effectively be created anew.

---

@jaxxstorm [suggested on slack](https://pulumi-community.slack.com/archives/C84L4E3N1/p1637264661329800) I create this issue here. :slightly_smiling_face:

**Comment by fitzoh** [comment]
+1 for this being a useful feature.
I'd suggest something other than `immutable` though, I would assume a resource being immutable means that no changes are allowed (like `ignoreChanges` for all fields, or perhaps an error if any fields are changed).

I feel like `orphanOnReplace` is specific enough but maybe not appropriate language.

`retainOnReplace` or `noDeleteOnReplace`?

**Comment by atrauzzi** [comment]
For sure!  Open to any more appropriate names.

**Comment by Sytten** [comment]
I came here to say the same thing, this is such a PITA right now

**Comment by atrauzzi** [comment]
Here again to just say that I recently tried to do a `pulumi state delete` on an SSL certificate and Pulumi is blocking me from even manipulating the state to obtain the behaviour I need: "This resource can't be safely deleted because the following resources depend on it..."

While I realize the resource I want to remove from state is depended on by another, I'm not actually deleting it from my infrastructure.  I'm simply trying to tell Pulumi to forget about it so that I can have it create another.

**Comment by Frassle** [comment]
You can make it so any change cause a replacement by using the [`replaceOnChanges`](https://www.pulumi.com/docs/intro/concepts/resources/#replaceonchanges) resource option set to `["*"]`, i.e. match any property path as needing a replacement not an update.

Would still need a way to not do the delete. A `orphanOnReplace` sounds possible although a little scary in terms of losing tracking of resource. Wouldn't it be better for pulumi to understand waiting for the new cert to actually be valid?

**Comment by atrauzzi** [comment]
Certainly, but then it's up to each resource to express that lifecycle and I guess I'd just rather always have a trap-door option to apply that behaviour outside of whatever the resources are built to support.  Either as a safety and also as just a bit of flexibility built into Pulumi itself.

**Comment by Frassle** [comment]
Also just linking https://github.com/pulumi/pulumi/issues/7747 as I think retainOnDelete as described there would do the same as orphanOnReplace but also keeping the resource around even when removed from the program. Is that the right behavior for this scenario?

**Comment by atrauzzi** [comment]
This might be more inclusive than just retain on delete. It might also include "delete on any change" behaviour as well.

**Comment by Frassle** [comment]
Isn't that just `ResourceOptions { replaceOnChanges = ["*"], retainOnDelete = true }`?
I'm not sure we want to add an option which would clash with these other two options.

**Comment by atrauzzi** [comment]
If that facilitates what I describe, then I totally agree! :slightly_smiling_face:

**Comment by Frassle** [comment]
I think this is now covered by replaceOnChanges and retainOnDelete which will be in the next release.

**Comment by Sytten** [comment]
Now we just need to figure out a solution so the GCP load balancer keeps the old certificate while the new one provision, otherwise it is still too easy to shot yourself in the foot :)

**Comment by atrauzzi** [comment]
Wouldn't `RetainOnDelete` do this?

**Comment by Sytten** [comment]
No, retain on delete will just remove the resource from the state. So this means it will trigger an update of the LB with the new certificate GCP ID, but this cert is not provisioned yet so the clients will start to error out. You basically have to manually add the old certificate ID to the list of certs given to the LB so it keeps it while the new cert gets provisioned.

**Comment by atrauzzi** [comment]
Well, that's what we want though...

We want it removed from state, but no "delete" to be issued to GCP.  The LB will just get a new cert added while the old one lingers.
