### ISSUE TITLE
Pulumi CLI / `stack select` - the `--create` flag doesn't work anymore

### ISSUE THREAD

**Issue by doitadrian** [pulumi/pulumi#8457]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

It seems that the `--create` flag on the `stack select` command is not working correctly in the latest release.

![image](https://user-images.githubusercontent.com/5121148/142588457-26049844-4aad-4ff3-9f47-223f4749e2e6.png)

Here I'm running two commands. The first one is selecting an existing stack. All works.

The second one is selecting a new one - a stack that doesn't exist. Here we get:
```
failed to load checkpoint: blob (key ".pulumi/stacks/dev3.json") (code=NotFound): stat /Users/adrian/dev/webiny-js-2/.pulumi/apps/admin/.pulumi/stacks/dev3.json: no such file or directory
``` 

Notice that in both cases I pass `-c` (which is the same as `--create`).

Actually I first noticed an error here with the S3 backend and thought it's something related to my setup. A couple of hours later, I noticed the same thing is happening with local backend. I also noticed this issue is introduced with the latest version - with `v3.17.0` this works, but with `v3.18.0` it doesn't.

### Steps to reproduce

1. Run the `stack select xyz --create` command (`xyz` stack must not exist)
2.
3.
4.

Expected: The stack to be created and automatically selected.
Actual: An error is being thrown, saying the folder cannot be found.

**Comment by Gerrit-K** [comment]
Same here with an Azure Blob Storage backend. As a workaround, we now use `pulumi stack select -c <STACK> || pulumi stack init <STACK>`.  A bit noisy and may catch other errors unwantedly, but it works for now without downgrading.

**Comment by emiliza** [comment]
Didn't catch this till now, but we also filed this as a duplicate in https://github.com/pulumi/pulumi/issues/8461 We have a fix merged, and it'll be included in the next release. Apologies for the inconvenience 😞

**Comment by doitadrian** [comment]
Thanks @emiliza !
