### ISSUE TITLE
`--target-dependents` in `pulumi state delete`

### ISSUE THREAD

**Issue by oktocat** [pulumi/pulumi#8458]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently `pulumi state delete` is far too cautious when it comes to deleting the children of any given resource.
A good example would be having something like a k8s cluster -> lots of deployments -> lots of CRs/CRDs.
If the root resource in this DAG is removed for some reason (e.g. out of band for Pulumi), a manual state intervention is required to clean up the orphaned resources. At the same time `pulumi state delete` doesn't allow for deleting the resource if it still has other resources dependent on it, effectively forcing the user to walk the dependency tree bottom up, which could be insanely tedious. An anecdote: I eventually gave up and manually edited a 500k line JSON to delete all resources parented under a no longer valid `provider`.

In such cases, it would be really nice to have a flag that forces the cascading resource deletion.
Given how `pulumi up` has the `--target-dependents` flag that allows the targeted deletion of a resource and anything that depends on it, it would make sense for `pulumi state delete` to have consistent behaviour.

cc @pgavlin

**Comment by pnathan** [comment]
this would be fantastic. I'm going to have to write a treewalker here to return a properly ordered list to then feed into a 1 by 1 delete...

**Comment by RobbieMcKinstry** [comment]
I've definitely hit this issue a few times myself.
