### ISSUE TITLE
Clean up types in `pkg/tokens`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#846]
Many of the strongly-typed string wrappers in the `tokens` package are no longer used with the same semantics as the initial design (which was based around these being tokens in a language runtime execution engine).  We should bring these in line with how these types are now used in our codebase.

A couple things:
1. Where strict internal structure is required, we should make sure only actually supported formats are constructible (including removing support for documented but not supported formats).
1. Where these are truly just opaque strings with no fixed internal structure, we may want to remove the strongly typed wrappers.

**Comment by ellismg** [comment]
@swgillespie was the most recent person to do a pass and we are pretty happy with where we are at now.
