### ISSUE TITLE
Pulumi 3.18.0 python version

### ISSUE THREAD

**Issue by Arturx47** [pulumi/pulumi#8460]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

After running pulumi up, the diagnosis from pulumi says:

ERROR: Failed to resolve python version command: fork/exec bin/python: no such fie or directory

### Steps to reproduce

1.Install pulumi 3.18.0 (python lib) or upgrade from 3.17.1 to 3.18.1 into an existing stack and run a build

Expected: 
just to work as before
Actual: 
pulumi up works but the error is spitted out

**Comment by aviflax** [comment]
I’m seeing the same problem using the Docker image `pulumi/pulumi-python:3.18.0` without a virtualenv.

**Comment by hiradp** [comment]
@iwahbe - I am actually seeing this on 3.19.0:

```
Failed to resolve python version command: fork/exec /home/runner/****************/venv/bin/python: no such file or directory
```

Does this warrant a separate issue?

**Comment by iwahbe** [comment]
@hiradp that would be great.
