### ISSUE TITLE
Readme links to invalid Travis CI link

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#8478]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

`README.md` uses the link:
```
[![Linux x64 Build Status](https://travis-ci.com/pulumi/pulumi.svg?token=cTUUEgrxaTEGyecqJpDn&branch=master)](https://travis-ci.com/pulumi/pulumi)  
```
This link points to a 404 error. We should point this to a different source, correctly showing if the build is green. 

### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:

**Comment by emiliza** [comment]
Ah, yeah, this should probably point to https://github.com/pulumi/pulumi/actions/workflows/master.yml/badge.svg
