### ISSUE TITLE
Expose Stack Name Property in .Net

### ISSUE THREAD

**Issue by dniasoff** [pulumi/pulumi#8496]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Would like a way of seeing the Stack name and environment in .net

**Comment by dniasoff** [comment]
Found out how to do it

var resourceName = this.GetResourceName();

**Comment by pierskarsenbarg** [comment]
@dniasoff you can also use `DeploymentInstance.StackName` (https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi/Pulumi.DeploymentInstance.html)
