### ISSUE TITLE
Allow arguments in plan/apply

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#85]
At the moment, programs cannot be parameterized.  For complex scripts, we will want this.

The thinking here is that `os.args` (for Node.js programs) will be populated with anything passed at the command line, just like if you used `node`.  So, for example:

    let vpc = new aws.ec2.VPC({ cidr: os.args["cidr"] });

**Comment by lukehoban** [comment]
We have config which we use for this purpose. And it's not clear we want to directly formalize OS args as an input mechanism.  Closing this out for now.
