### ISSUE TITLE
k8s.apiextensions.CustomResource deleting error - "<resource>" timed out waiting to be Ready

### ISSUE THREAD

**Issue by SidetrekAI** [pulumi/pulumi#8502]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

`k8s.apiextensions.CustomResource` hangs when attempting to `pulumi destroy` and then errors out with: `k8s.apiextensions.CustomResource deleting error - "<resource>" timed out waiting to be Ready`

### Steps to reproduce
Create a k8s CustomResource:

```
const knativeEventing = new k8s.apiextensions.CustomResource(knativeEventingName, {
      apiVersion: 'operator.knative.dev/v1alpha1',
      kind: 'KnativeEventing',
      metadata: {
        name: knativeEventingName,
        namespace: knativeEventingNamespace.metadata.name,
      },
    }, { parent: this })
```

Destroy the stack using `pulumi destroy`.

Errors out during destroy:

```
kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition knativeeventings.operator.knative.dev **deleting failed** error: 'knativeeventings.operator.knative.dev' timed out waiting to be Ready
```
  
Expected: Should delete the stack without error.
Actual: Errors out during destroy.

**Comment by emiliza** [comment]
Hi @SidetrekAI - sorry you're running into this 😞 

This looks like a known issue in our pulumi-kubernetes provider https://github.com/pulumi/pulumi-kubernetes/issues/1418. Can you take a look and see if this workaround works for you? https://github.com/pulumi/pulumi-kubernetes/issues/1418#issuecomment-767878038
