### ISSUE TITLE
TTL is a number not a string

### ISSUE THREAD

**Issue by orcutt989** [pulumi/pulumi#8536]
File: [themes/default/content/registry/packages/aws/api-docs/route53/record/_index.md](https://www.pulumi.com/registry/packages/aws/api-docs/route53/record/)

![image](https://user-images.githubusercontent.com/5608027/144124861-49a46763-e4e3-43c0-9abc-96d6c4e91f98.png)

![image](https://user-images.githubusercontent.com/5608027/144124937-04088c36-3811-4ed7-be20-cb9b97282920.png)

**Comment by justinvp** [comment]
This is fixed.
