### ISSUE TITLE
Metaschema validation adds significant latency to import and programgen tools

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi#8541]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
With https://github.com/pulumi/pulumi/pull/7952/ we added metaschema validation as part of the codepath related to binding to the spec. With large schemas (azure-native), the schema validation can take upwards of 20 seconds. While this amortizes well for example generation and other batch operations, it imposes a large penalty for important workloads like one-off resource imports and conversion tools (arm2pulumi).

<img width="444" alt="Screen Shot 2021-11-30 at 6 40 39 PM" src="https://user-images.githubusercontent.com/1094518/144664969-a5e4035f-17cf-43e8-97bc-e18518baab01.png">

One option is to allow disabling schema validation in some cases. There is a draft PR for that [here](https://github.com/pulumi/pulumi/pull/8542). This feels clunky and I am not sure when we would actually like to enforce metaschema validation. Should this be part of schema generation instead so we can trust that the schema has been validated against the metaschema (or at least a certain version etc.) and allow that to be trusted?

### Steps to reproduce

1. `pulumi import azure-native:storage/v20150501preview:StorageAccount <name> /subscriptions/.../resourceGroups/.../providers/Microsoft.Storage/storageAccounts/<storage-account>`
2. Wait 30 seconds for import to succeed

Expected: 
Import should be near instantaneous

Actual: 
~30+ seconds wait for the codegen for the import.

**Comment by viveklak** [comment]
CC @pgavlin @mikhailshilkov

**Comment by pgavlin** [comment]
Today we validate every time a package schema is bound, including when binding the schema for purposes of program codegen or when loading the schema for a package referenced by another package. I can imagine that in these situations--essentially any situation in which the schema being bound is being referenced, rather than when it is the root package under consideration--we could disable the validation and trust that the schema is well-formed. With that approach, we would only pay the validation penalty when loading a package for SDK generation. How does that sound?

cc @pulumi/platform

**Comment by pgavlin** [comment]
https://github.com/pulumi/pulumi/pull/8543 implements the behavior described above. The various SDK codegen drivers in the native providers + tfbridge will need to be updated to call `BindSpec` rather than `ImportSpec` if we take the PR.

**Comment by viveklak** [comment]
> 

Ack. The following instances will need to change in native providers:
https://github.com/pulumi/pulumi-kubernetes/blob/237c8f6300624f80c5e7b70f8ddea1dee7e07d73/provider/cmd/pulumi-gen-kubernetes/main.go#L123
https://github.com/pulumi/pulumi-aws-native/blob/7fd9e0d8f36090a636db45c22a53a5bbde9b64b4/provider/cmd/pulumi-gen-aws-native/main.go#L260
https://github.com/pulumi/pulumi-azure-native/blob/833a218187ca7afb214906a90af0191aa295cddd/provider/cmd/pulumi-gen-azure-native/main.go#L260
https://github.com/pulumi/pulumi-google-native/blob/2da011f7ce69fcf7e2c05f2f2ce0777617b31f2a/provider/cmd/pulumi-gen-google-native/main.go#L241
