### ISSUE TITLE
State is not properly updated when for wafv2.WebAcl with custom rules

### ISSUE THREAD

**Issue by manospasj** [pulumi/pulumi#8552]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm using the NodeJS version of Pulumi and I am trying to create a wafv2.WebAcl with a few custom rules like this
```typescript
new wafv2.WebAcl(
  "MyWebAcl",
  {
    scope: "REGIONAL",
    defaultAction: {
      allow: {},
    },
    visibilityConfig: {
      metricName: "MyMetric",
      cloudwatchMetricsEnabled: true,
      sampledRequestsEnabled: true,
    },
    rules: [
      // I have defined 3 custom rules here
    ],
  },
);
```
Creating the ACL works fine, but then if I execute the `pulumi preview --diff` command it says that the rules have changed and it needs to update them, even though nothing has changed in my code. I checked the Web ACL in AWS Console and it was created with the expected configuration, but Pulumi state doesn't match AWS.

### Steps to reproduce

1. Add a wafv2.WebAcl with a few custom rules in an empty project.
2. Execute the `pulumi up` command to create the Web ACL.
4. Execute the `pulumi preview --diff` command.

Expected: Executing the `pulumi preview --diff` command should say that there are no changes.
Actual: The `pulumi preview --diff` command thinks that the rules have changed and the Web ACL needs to be updated.

**Comment by emiliza** [comment]
Apologies you're running into this 😞  

I believe this is a duplicate, issue is covered in https://github.com/pulumi/pulumi-aws/issues/1423 - please use this for tracking
