### ISSUE TITLE
Targeted Runs will complete out-of-scope Deletion Actions from previous runs

### ISSUE THREAD

**Issue by con5cience** [pulumi/pulumi#8568]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

```
▶ pulumi up --target 'urn:pulumi:prod::cluster::eks:index:ManagedNodeGroup$aws:eks/nodeGroup:NodeGroup::newnodes-1c' --target 'urn:pulumi:prod::cluster::eks:index:ManagedNodeGroup$aws:eks/nodeGroup:NodeGroup::newnodes-1b' --target 'urn:pulumi:prod::cluster::eks:index:ManagedNodeGroup$aws:eks/nodeGroup:NodeGroup::newnodes-1a'
Previewing update (org/prod)

View Live: <redacted>

     Type                                                                       Name                       
     pulumi:pulumi:Stack                                                        cluster-prod           
     pulumi:pulumi:Stack                                                        cluster-prod           
     │  └─ aws:eks:NodeGroup                                                    cluster-1
     ├─ eks:index:ManagedNodeGroup                                              cluster-1a 
     │  └─ aws:eks:NodeGroup                                                    cluster-1
     ├─ eks:index:ManagedNodeGroup                                              cluster-1b
     │  └─ aws:eks:NodeGroup                                                    cluster-1
     ├─ eks:index:ManagedNodeGroup                                              cluster-1c 
     │  └─ aws:eks:NodeGroup                                                    cluster-1
     ├─ eks:index:ManagedNodeGroup                                              newnodes-1c   
 +   │  └─ aws:eks:NodeGroup                                                    newnodes-1c 
     ├─ eks:index:ManagedNodeGroup                                              newnodes-1b   
 +   │  └─ aws:eks:NodeGroup                                                    newnodes-1b 
     ├─ eks:index:ManagedNodeGroup                                              newnodes-1a   
 +   │  └─ aws:eks:NodeGroup                                                    newnodes-1a 
     └─ eks:index:Cluster                                                       cluster            
  
Outputs: <redacted>

Do you want to perform this update? yes
Updating (org/prod)

View Live: <redacted>

     Type                  Name                    Status         Info
     pulumi:pulumi:Stack   cluster-prod        **failed**     1 error
 -   ├─ aws:eks:NodeGroup  oldnodes-1a  deleted        
 -   ├─ aws:eks:NodeGroup  oldnodes-1b  deleted        
 -   └─ aws:eks:NodeGroup  oldnodes-1c  deleted        
 ```

This caused a Production outage as all the nodes were pulled out from under the cluster before the new MNGs were created.

### Steps to reproduce

1) Provision a Managed Node Group.
2) Make code changes to the MNG that will cause them to be delete-replaced (instance types, in this case). Apply the changes.
3) Paste code to create new MNGs alongside the old ones currently flagged for deletion from the previous run.
4) Run Pulumi targeting the new MNG URNs.

Expected: It was expected that actions would only be performed on the targeted resources. Additionally, I expected to see the planned completed deletion of the old MNGs in the preview.

Actual: Delete-flagged MNGs were deleted before the new MNGs were created. No mention of this course of action was shown in the Preview.

**Comment by leezen** [comment]
@con5cience I'm not sure I totally follow your repro steps. From the outputs above, it looks like at some point the logical name of the resources have changed, e.g. from `newnodes-1a` to `oldnodes-1a`? I tried a couple ways to reproduce, but couldn't trigger the deletion. Did you have the resources in a pending delete state in the first place within your state perhaps?

It'd be great to understand what you're trying to accomplish as well. If the goal was to swap in a new managed node group without downtime, then shouldn't autonaming along w/ the default create-before-delete replacement semantics do what you need?

**Comment by con5cience** [comment]
We've observed very inconsistent behavior with Pulumi when trying to change instance types on a managed node group.

In this case, I had changed the instance type on the MNG and it was pending deletion. I wanted to add another MNG alongside before deleting the old group as a contingency, and targeted the URNs of the new MNGs. It deleted the MNGs that were pending deletion anyway.  

From my perspective, the problem is that:

The delete actions were not part of the preview.

The delete actions were undertaken even though the URNs of the items deleted were not part of the indicated targets.

**Comment by leezen** [comment]
> In this case, I had changed the instance type on the MNG and it was pending deletion. I wanted to add another MNG alongside before deleting the old group as a contingency, and targeted the URNs of the new MNGs.

Could you please describe this in more detail as to what steps you took? Did you change the instance type on the MNG, run `pulumi up`, then cancel the operation part-way through (leading to pending deletions) or where did the pending deletions come from? Essentially, I'm wondering if this is a case of https://github.com/pulumi/pulumi/issues/2948?

**Comment by con5cience** [comment]
1) Have a MNG.
2) Change the instance types on the MNG in code.
3) `pulumi up`. Existing MNG is changed and flagged for delete-replacement.
4) Add new MNG in code alongside the existing.
5) `pulumi up` targeting the new MNG URN. Pre-existing MNGs flagged for deletion are deleted even though they are not part of target scope nor reported in the preview.

I did not cancel the run at any point.

**Comment by leezen** [comment]
I'm really having trouble repro'ing this. When I get to step 3 in your above, the node group is replaced in the same run (a new one is created and the old one is deleted). Plowing through to the additional steps simply causes the new node group to be created.

I'm using `@pulumi/eks@0.36.0`

**Comment by leezen** [comment]
Any chance you could please provide a repo with the contents to reproduce?
