### ISSUE TITLE
Issue getting result out of random.RandomPassword

### ISSUE THREAD

**Issue by tiagocborg** [pulumi/pulumi#8620]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce
I am trying to create a random secret and storing it on secret manager. But no matter how I try to get the output, the result is always `Calling [toJSON] on an [Output<T>] is not supported. To get the value of an Output as a JSON value or JSON string consider either: 1: o.apply(v => v.toJSON()) 2: o.apply(v => JSON.stringify(v)) See https://pulumi.io/help/outputs for more details. This function may throw in a future version of @pulumi/pulumi.`

I tried with `pulumi.output`, `apply`, the result is always the same. Although, if I do not use it on an object, just assign it directly to `secretString`, it works fine.

![Captura de ecrã 2021-12-21, às 14 32 25](https://user-images.githubusercontent.com/6026596/146946840-d32764ea-9ae0-438f-b04c-87abe5bad138.png)

**Comment by Frassle** [comment]
You want something like the below explicitly joining the outputs:
```
const creds = pulumi.all([rdsUsername, rdsPassword]).apply(([username, password]) => {
   return JSON.stringify({AURORA_USERNAME: username, AURORA_PASSWORD: password})
});
```
or the `output` function should also work:
```
const creds = pulumi.output({
   AURORA_USERNAME: rdsUsername.result,
   AURORA_PASSWORD: rdsPassword.result,
}).apply(creds => JSON.stringify(creds));
```

Also a note that `output.apply(value => value)` does nothing, it's the same as just `output`.

**Comment by tiagocborg** [comment]
It worked, thanks
