### ISSUE TITLE
ComponentResource python types are incomplete

### ISSUE THREAD

**Issue by antifuchs** [pulumi/pulumi#8623]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We are creating more `ComponentResource`s now, and overall they're great - however, we're getting type-checking failures from pyright with pulumi 3.19.0:

* The `__init__` method takes an `props: Optional[dict]` that should probably be typed as `Optional['Inputs']`
* The `register_output` method has no type annotations on its `outputs` argument. That should probably also be `Optional['Inputs']`?

### Steps to reproduce
1. turn on typechecking with pyright
2. Make a class like the following:

```py
class Foo(pulumi.ComponentResource):
    def __init__(
        self,
        name: str,
        opts: Optional[pulumi.ResourceOptions] = None,
    ):
        super().__init__("pkg:index:Foo", name, None, opts)  # <- fails to typecheck
        self.register_outputs({})  #<- also fails to typecheck
```

Expected: No typechecking failures
Actual: two typechecking failures, on the call to `super().__init__` and `register_outputs`.
```
error: Type of "__init__" is partially unknown
    Type of "__init__" is "(t: str, name: str, props: dict[Unknown, Unknown] | None = None, opts: ResourceOptions | None = None, remote: bool = False) -> None" (reportUnknownMemberType)
error: Type of "register_outputs" is partially unknown
    Type of "register_outputs" is "(outputs: Unknown) -> Unknown" (reportUnknownMemberType)
```

**Comment by lukehoban** [comment]
I was just looking into this and having trouble reproing it initially.  Turns out it requires turning on strict type checking in pyright via `# pyright: strict`.

**Comment by t0yv0** [comment]
CC @t0yv0 @mikhailshilkov
