### ISSUE TITLE
Error initializing Docker client: protocol not available

### ISSUE THREAD

**Issue by madhank93** [pulumi/pulumi#8626]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Tech Stacks - Typescript/Node.js and GCP

I was following the blog article written for [docker using pulumi](https://www.pulumi.com/blog/pulumi-and-docker-development-to-production/). But when I execute the `pulumi up` command I am getting an `Error initializing Docker client: protocol not available` 

![image](https://user-images.githubusercontent.com/15702795/147131168-cf6c9b69-326f-4917-a3a4-9b59764051f7.png)

### Steps to reproduce

1. Install Pulumi and Pulumi-docker dependencies
2. Run `pulumi up` command

Expected: It should display pulumi preview with diagnostics
Actual: Getting `Error initializing Docker client: protocol not available`

**Comment by leezen** [comment]
I wonder if this is the same as https://discuss.hashicorp.com/t/error-error-initializing-docker-client-protocol-not-available/10886/2

I would suggest attempting to try that by running `pulumi config set docker:host "npipe:////.//pipe//docker_engine"` to see if that resolves your issue.

**Comment by madhank93** [comment]
@leezen Thank you so much. Running the above command solved the problem.
