### ISSUE TITLE
Ensure code coverage results are deterministic

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#8629]
Currently, code coverage frequently changes in files not touched by a PR.  That leads to misleading reports of coverage loss or gain, and also to an overall level of noise that's larger than the real change in most PRs.  We should audit tests to ensure we reduce coverage noise to a bare minimum, to ensure we can rely on the data we see from code coverage analysis.

**Comment by lukehoban** [comment]
Also - many code coverage results just seem to be "wrong" in meaningful ways.  Almost all PRs show as reducing coverage even though they don't, miss out on coverage introduced in the tests, include loss of coverage for files unmodified in the PR, etc.  

We should do a deep review of the correctness of the data collection, and ensure it is meaningful.

**Comment by lukehoban** [comment]
Marking as P1, as this leads to "build failures" on PRs, and has marked every PR as failing for the last several weeks.

**Comment by leezen** [comment]
This is only leading us to fail the coverage check, which isn't currently gating merge, correct? These failures aren't being classified as build failures nor blocking the build unless I'm missing something? Agree we want to make sure we tune this such that we can rely on the check itself, but wanted to make sure I'm not missing anything.

**Comment by lukehoban** [comment]
Yes - it doesn't block, but does mark every PR as failed.  And adds a lot of incorrect "noise" on every PR.  

![Uploading Screen Shot 2022-01-04 at 4.24.20 PM.png…]()

**Comment by joeduffy** [comment]
It also makes the repo just red overall. For instance, Anton tried to make things green, only to be foiled by the non-deterministic and incorrect code coverage report:

![image](https://user-images.githubusercontent.com/3953235/148151082-145ea544-0a90-490c-81ce-34958f0bfd99.png)

That's as much of a bummer as the PRs looking red too.

**Comment by leezen** [comment]
Removing `p1` as we've made these informational for now.

**Comment by EvanBoyle** [comment]
Go 1.20 now supports coverage profiles for integration tests that span multiple binary invocations: https://go.dev/testing/coverage/

**Comment by EvanBoyle** [comment]
An interesting idea if we wanted to start generating code coverage from an e2e suite such as examples we could:

- as a part of all publishing workflows, build and publish a binary that is built with coverage info (for language plugins, for all providers) and publish these to S3 under a consistent naming convention
- teach CLI plugin acquisition how to acquire plugins built with coverage info when a particular env var is set `$PULUMI_DEBUG_COVERAGE=1` and to fall back to normal binaries if covered binaries are not available

This would make the process of running e2e integration tests far easier. Anyone could reasonably spin up an E2E test without having to worry about acquiring source and compiling a bunch of extra binaries with coverage info.

**Comment by Frassle** [comment]
Not all providers are going to be Go binaries, and we might end up with not even all language plugins are Go binaries. We probably don't want to ship coverage enabled binaries in the default .tar.gz files we ship, but having a separate download (and a separate plugin cache) for "debug" binaries sounds possible.

**Comment by tgummerer** [comment]
I believe this issue has been fixed a while ago, by removing retries through `gotestsum`.  Our code coverage results have been deterministic since then.  Ideally we'd also track coverage on each PR, and we were planning on that, but the coverage numbers we do have are accurate.  I believe this issue can be closed out because of that, but feel free to reopen if I'm missing something here.
