### ISSUE TITLE
Automation API: Python in-line throws `Resource Monitor has terminated, shutting down` error for all stacks after a stack error.

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#8633]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

An automation api program with inline programs throws `Resource Monitor has terminated, shutting down` error for stacks after a stack failure and marks the stacks as failed even though the subsequent stacks successfully deploy all the resources.

### Steps to reproduce

1. Use attached program.
2. Set the azure credentials (lines 7 - 8)
3. python auto-api-program.py
4. You will see two runs of a randomly named stack.
5. The first stack will create 5 of 8 resources and fail - on purpose to cause the condition 
6. The second or more runs will create all 8 resources and indicate failure even though it's fine.
7. The stack is in a failed state.
8. To clean up, you can delete the resource group in Azure and then force delete the stack.

Expected: 
The subsequent stack.ups should not fail.
Actual: 
They fail.

[auto_api_program.py.txt](https://github.com/pulumi/pulumi/files/7770971/auto_api_program.py.txt)

**Comment by joeduffy** [comment]
The culprit appears to be this line:

https://github.com/pulumi/pulumi/blob/5ec0b2ffe6db08290a5c680f86e8e6b8ccf7d9b5/sdk/nodejs/automation/server.ts#L96

If I comment that out, everything seems to run as expected.

**Comment by t0yv0** [comment]
Thanks for the repro, I am able to reproduce, but is is taking me some time to understand how to best solve for Python. 

Notes on what's happening in Python. The two separate `up` runs are not sufficiently isolated. Exceptions thrown by async tasks created by register_resource against the first monitor e.g. `127.0.0.1:62464` end up landing on the asyncio loop after the program switches to the next monitor e.g. `127.0.0.1:62502` and contaminating the second run.

**Comment by t0yv0** [comment]
Follow up in https://github.com/pulumi/pulumi/issues/8658 for other languages than Python.

**Comment by t0yv0** [comment]
Had to revert the PR on Windows tests timing out on master. Need to re-invsetigate this on Windows.
