### ISSUE TITLE
Create GKE autopilot fails with default configs (golang)

### ISSUE THREAD

**Issue by sfrique** [pulumi/pulumi#8638]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When creating a cluster with default config it fails with this error:
```
Diagnostics:
  gcp:container:Cluster (xxx-some-cluster):
    error: 1 error occurred:
        * googleapi: Error 400: Max pods constraint on node pools for Autopilot clusters should be 32., badRequest
```
This is the relevant part:

```
func createCluster(name string, zone pulumi.String, ctx *pulumi.Context) (*container.Cluster, error) {

	uniqueName := name + "-" + string(zone)
	cluster, err := container.NewCluster(ctx, uniqueName, &container.ClusterArgs{
		EnableAutopilot: pulumi.Bool(true),
		Location:        zone,
	})
	if err != nil {
		return nil, err
	}
	return cluster, nil
}

```
Here is the documentation https://www.pulumi.com/registry/packages/gcp/api-docs/container/cluster/#autopilot

When trying to set `default_max_pods_per_node` i get this
```
Diagnostics:
  gcp:container:Cluster (boot-and-consensus-us-west1-a):
    error: gcp:container/cluster:Cluster resource 'boot-and-consensus-us-west1-a' has a problem: ConflictsWith: "default_max_pods_per_node": conflicts with enable_autopilot. Examine values at 'Cluster.DefaultMaxPodsPerNode'.
```

### Steps to reproduce

1. Create the file from the tutorial
2. run pulumi up

Expected: Cluster created
Actual: Error with max pod constraint

**Comment by viveklak** [comment]
Closing in favor of https://github.com/pulumi/pulumi-gcp/issues/714
