### ISSUE TITLE
master build is broken

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#8644]
The latest `master` build failed with:

https://github.com/pulumi/pulumi/runs/4651812501?check_suite_focus=true

We're also seeing this in several PRs:
- https://github.com/pulumi/pulumi/runs/4651812501?check_suite_focus=true
- https://github.com/pulumi/pulumi/runs/4654207276?check_suite_focus=true

```
if [ -e .coverage ]; then PATH=venv/bin:$PATH coverage xml -o /home/runner/work/pulumi/pulumi/coverage/python-auto.xml; fi
No source for code: '/home/runner/work/pulumi/pulumi/sdk/python/rep-10>'.
make[1]: *** [Makefile:65: test_auto] Error 1
make[1]: Leaving directory '/home/runner/work/pulumi/pulumi/sdk/python'
make: *** [build/common.mk:222: sdk/python_test_all] Error 2
```

**Comment by thetorpedodog** [comment]
This is probably a new bug (incompatibility? ???) that I introduced to `attrs`: https://github.com/python-attrs/attrs/issues/895

(I was googling `"no source for code" "rep"` to see if this kind of issue had ever come up before; instead I just saw a bunch of people’s autobuilds breaking 😰)

**Comment by t0yv0** [comment]
Thank you @thetorpedodog and @lukehoban it appears that the upstream fix makes our builds succeed again. We considered a workaround with `coverage -i` (ignore errors) but its' no longer necessary.
