### ISSUE TITLE
Pulumi leaves orphan provider processes running and consuming memory

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#8696]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

It is possible to end up in a state where `pulumi-language-nodejs` process is orphaned and keeps running.  I am reproducing it in the context of investigating OOM and failed builds on Windows. I had to repeatedly (~10 times) run these passing integration tests:

```
cd tests/examples
go test -test.v -run TestAccMinimal
```

Now I was able to find this process still running:

```powershell
$pp = gwmi win32_process -filter 'Name="pulumi-language-nodejs.exe"'
$pp
```

```

__GENUS                    : 2
__CLASS                    : Win32_Process
__SUPERCLASS               : CIM_Process
__DYNASTY                  : CIM_ManagedSystemElement
__RELPATH                  : Win32_Process.Handle="4364"
__PROPERTY_COUNT           : 45
__DERIVATION               : {CIM_Process, CIM_LogicalElement, CIM_ManagedSystemElement}
__SERVER                   : pulumiwintestvm
__NAMESPACE                : root\cimv2
__PATH                     : \\pulumiwintestvm\root\cimv2:Win32_Process.Handle="4364"
Caption                    : pulumi-language-nodejs.exe
CommandLine                : C:\Users\pulumiadmin\.pulumi-dev\bin\pulumi-language-nodejs.exe -typescript=false
                             -root=C:\Users\PULUMI~1\AppData\Local\Temp\2\p-it-pulumiwint-minimal-7a83a456-205592354
                             127.0.0.1:62862
CreationClassName          : Win32_Process
CreationDate               : 20220106205802.645271+000
CSCreationClassName        : Win32_ComputerSystem
CSName                     : pulumiwintestvm
Description                : pulumi-language-nodejs.exe
ExecutablePath             : C:\Users\pulumiadmin\.pulumi-dev\bin\pulumi-language-nodejs.exe
ExecutionState             :
Handle                     : 4364
HandleCount                : 122
InstallDate                :
KernelModeTime             : 8593750
MaximumWorkingSetSize      : 1380
MinimumWorkingSetSize      : 200
Name                       : pulumi-language-nodejs.exe
OSCreationClassName        : Win32_OperatingSystem
OSName                     : Microsoft Windows Server 2016 Datacenter|C:\Windows|\Device\Harddisk0\Partition2
OtherOperationCount        : 16895
OtherTransferCount         : 1514406
PageFaults                 : 5577
PageFileUsage              : 17420
ParentProcessId            : 3288
PeakPageFileUsage          : 20352
PeakVirtualSize            : 723537920
PeakWorkingSetSize         : 19244
Priority                   : 8
PrivatePageCount           : 17838080
ProcessId                  : 4364
QuotaNonPagedPoolUsage     : 13
QuotaPagedPoolUsage        : 134
QuotaPeakNonPagedPoolUsage : 16
QuotaPeakPagedPoolUsage    : 134
ReadOperationCount         : 314
ReadTransferCount          : 195239
SessionId                  : 2
Status                     :
TerminationDate            :
ThreadCount                : 7
UserModeTime               : 3437500
VirtualSize                : 717246464
WindowsVersion             : 10.0.14393
WorkingSetSize             : 17477632
WriteOperationCount        : 2
WriteTransferCount         : 166
PSComputerName             : pulumiwintestvm
ProcessName                : pulumi-language-nodejs.exe
Handles                    : 122
VM                         : 717246464
WS                         : 17477632
Path                       : C:\Users\pulumiadmin\.pulumi-dev\bin\pulumi-language-nodejs.exe
```

Its parent process is dead.

This leak may lead to a memory leak on a server that repeatedly runs `pulumi`. 

I have seen in the past the same issue happening with my Mac OS based dev environment but cannot reproduce at the moment.

### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:

**Comment by stack72** [comment]
@t0yv0 it does

```
▶ ps aux | grep pulumi
stack72          61389   0.0  0.1  5045448  10648 s004  S    30Dec21   0:13.03 /Users/stack72/.pulumi/plugins/resource-kubernetes-v3.12.0/pulumi-resource-kubernetes 127.0.0.1:60277
stack72          61387   0.0  0.0  5007020   8036 s004  S    30Dec21   0:06.54 /Users/stack72/.pulumi/plugins/resource-random-v4.0.0/pulumi-resource-random 127.0.0.1:60277
```

I am not running anything Pulumi right now

**Comment by t0yv0** [comment]
To confirm, your result is on Mac or Linux?

**Comment by lblackstone** [comment]
I've seen this as well. I think it usually has to do with the pulumi program panicking.

**Comment by t0yv0** [comment]
Checked the repro steps above, pulumi program does not seem to be panicking in the logs of these tests, so it sounds like the leak is possible on the happy path.

**Comment by pgavlin** [comment]
Yes, I've also seen this. I know I've seen it in the case of panics on *nix; not sure if I've seen in on the normal path on *nix. Very possible, though.

**Comment by t0yv0** [comment]
Logging some research on possible solutions.

# OS solutions

This would be the best, to instruct the OS to kill child process after parent one dies, automatically.

Linux: when spawning a child, can instruct which signal to send to the child when parent dies:

```
type SysProcAttr struct {
	Pdeathsig    Signal         // Signal that the process will get when its parent dies (Linux only)
}
```
This could be SIGKILL that would do the job.

MacOS: parent and child processes must be in the same process group, and then something has to kill the process group. In the case of pulumi process dying, there needs to be another hypervisor. Perhaps it can be Automation API script or in the case of tests the programtest framework. In this situations the solution works (also works on Linux);

```
	// Setpgid sets the process group ID of the child to Pgid,
	// or, if Pgid == 0, to the new child's process ID.
	cmd.SysProcAttr = &syscall.SysProcAttr{
		Setpgid: true,
	}

        ...
        cmd.Start()
        ...
        thePid := cmd.Process.Pid
        defer func() {
              syscall.Kill(-thePid, syscall.SIGKILL)
        }()
```

In general though if the parent is pulumi and it dies before doing the PGID based kill, the orphans will persist.

There is a setssid call I did not explore further that may make `pulumi` the root process of a process group, but I'm still doubtful if that will clean up sub-processes automatically if the parent terminates.

Windows: needs job groups.  Not in Go stdlib yet, https://github.com/golang/go/issues/17608 did not find a well-used library with bindings, bindings might be complicated without a good knowledge of the Windows APIs involved. There is https://github.com/kolesnikovae/go-winjob that may work but does not look battle-tested.

# Polling

Less efficient than being notified by the OS, but polling in the child for parent health can be more foolproof and reliable. We can get parent process ID using stdlib and that works cross-platform:

```go
var ppid int = os.Getppid()
```

In the case of MacOS, empirically it seems that an orphaned process will have its ppid change from the original one to 1. There is a change of ppid that the process can detect. On Windows however it is not the case, and ppid remains constant.

Go stdlib does not offer any API to infer the health of a different OS process. However with `github.com/mitchellh/go-ps` it is possible:

```
// FindProcess looks up a single process by pid.
//
// Process will be nil and error will be nil if a matching process is
// not found.
func FindProcess(pid int) (Process, error) {
	return findProcess(pid)
}
```

I've tested a quick program that has the child poll `FindProcess(ppid)` and self-destruct when that process is not found, and it does mostly what we would want on Mac and Windows (yet to test on Linux). The only caveat is that ppid needs to be collected at the beginning of the program in case the process is reparented to 1, and it better get the correct ppid (there is a subtle race). If we are worried about this race can pass the PPID as an argument or env var.

# Polling monitor

Instead of polling process health which uses syscalls and assumes a process structure, we could also poll at gRPC level. An endpoint can be added for heartbeat. Or we repurpose SupportsFeature for heartbeat purposes without making gRPC additions.

**Comment by AaronFriel** [comment]
@t0yv0 you can just put it on our backlog 😆

**Comment by t0yv0** [comment]
How do I do that? Looks like @Frassle is taking care of it now.

**Comment by AaronFriel** [comment]
Platform project, "Iteration backlog" I think, for anything we want to tackle next. Into "Triage" column if you want the team to review, and no status if it's true-backlog.

**Comment by Frassle** [comment]
Reading https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md I'm not sure grpc connectivity states are exactly what we need for this. Sounds like a channel could go *idle* and disconnect and then if nothing tried to send an RPC it would happily stay *idle* even though the engine has shutdown.

@t0yv0's idea of a simple `Heartbeat()` on the engine interface sounds quite workable though. I don't think we need to check very often (maybe every 5 minutes or so?) and if the engine has gone just cancel out.

**Comment by Frassle** [comment]
Maybe even better than writing our own Heartbeat, just using grpcs health check protocol: https://github.com/grpc/grpc/blob/master/doc/health-checking.md
