### ISSUE TITLE
[codegen/nodejs] Generate `install-pulumi-plugin.js` install script

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#8701]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Our provider packages include a script that runs `pulumi plugin install` for the associated plugin when the package is installed. The install script isn't currently generated as part of the Node.js SDK codegen. Instead, as part of publishing the package to NPM, we have a [script](https://github.com/pulumi/scripts/blob/master/ci/add-plugin-installer-script.js) that runs which modifies the `package.json` for the package and includes the [install script](https://github.com/pulumi/scripts/blob/master/ci/install-pulumi-plugin.js).

Rather than mangling the `package.json` and injecting the install script as part of the publish process, we should consider changing this to happen during SDK codegen. This aligns with [what we do for Python](https://github.com/pulumi/pulumi/blob/684d7aad3920042ce1982b5fedddea62a6e5bb61/pkg/codegen/python/gen.go#L1971-L1976), which emits a `setup.py` which also shells out to the `pulumi plugin install` command.

The code generator should emit the install script and appropriate entry in `package.json` to have the script run during installation of the package. The existing install script does not currently support specifying the `--server` flag to `pulumi plugin install`, so as part of this, the emitted install script should include the `--server` flag if the schema has `pluginDownloadURL` set.

**Comment by stack72** [comment]
@justinvp we need to collaborate really closely on this so that I remove the old script from our GHA as we roll this out

**Comment by justinvp** [comment]
@stack72, yep, sounds good.

From reading over [how the old script works](https://github.com/pulumi/scripts/blob/b6ee1692954d2b39e7a22b0db80b8cc4b735c101/ci/publish-tfgen-package#L33-L42), if the codegen emits and places `install-pulumi-plugin.js` with the same name in the same place as the old script, I think we can keep the old script as-is for now (the old script will overwrite what was codegen'd, which is fine for our packages), and then once the change has rolled out everywhere, we can delete the old script from GHA at our leisure. (Or we could tweak the old script to look for the install script file, and if it already exists, bail).
