### ISSUE TITLE
Pulumi generated lambda fails if dependency repository package.json defines "exports"

### ISSUE THREAD

**Issue by PupoSDC** [pulumi/pulumi#8710]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm trying to use [zod](https://github.com/colinhacks/zod) for lambda input validation. This packages defines [exports](https://github.com/colinhacks/zod/blob/master/package.json#L8-L13) in it's `package.json`.  This results in the generated lambda failing with this error:

```
{
  "errorType": "Error",
  "errorMessage": "Package subpath './lib/index.js' is not defined by \"exports\" in /var/task/node_modules/zod/package.json",
  "trace": [
    "Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/index.js' is not defined by \"exports\" in /var/task/node_modules/zod/package.json",
    "    at new NodeError (internal/errors.js:322:7)",
    "    at throwExportsNotFound (internal/modules/esm/resolve.js:322:9)",
    "    at packageExportsResolve (internal/modules/esm/resolve.js:545:3)",
    "    at resolveExports (internal/modules/cjs/loader.js:450:36)",
    "    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)",
    "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:746:27)",
    "    at Module.require (internal/modules/cjs/loader.js:974:19)",
    "    at require (internal/modules/cjs/helpers.js:93:18)",
    "    at /var/task/__index.js:23:19"
  ]
}
```

### Steps to reproduce

here is a [repro-repo](https://github.com/PupoSDC/issue-pulumi-lambdas-fail-with-zod/blob/master/index.ts).

when i execute the lambda pulumi creates I get the error mentioned above. This error can be fixed by changing the resulting code.

Code produced by Pulumi:

```js
function __f2() {
  return (function() {
    with({ zod_1: require("zod/lib/index.js") }) {
````

Code that works:

```js
function __f2() {
  return (function() {
    with({ zod_1: require("zod") }) {
````

### Other info

Because of this [issue](https://github.com/pulumi/pulumi/issues/4130) I went ahead and tried this with the alpha version, but I get the sam result for both. 

```
pulumi about
CLI          
Version      3.21.1
Go Version   go1.17.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     4.33.1
docker  3.1.0
nodejs  unknown

Host     
OS       darwin
Version  12.0.1
Arch     arm64

This project is written in nodejs (/Users/pedro/.nvm/versions/node/v16.10.0/bin/node v16.10.0)

NAME            VERSION
@pulumi/aws     4.33.1
@pulumi/awsx    0.30.0
@pulumi/pulumi  3.22.0-alpha.1641528849
zod             3.11.6
@types/node     14.18.5
```

**Comment by PupoSDC** [comment]
@thibaut-pro  have you found a way to automatize the workaround?
Or are you, like me, changing the file in aws console?

**Comment by thibaut-pro** [comment]
I am also changing the file in the AWS console after each deployment.

**Comment by PupoSDC** [comment]
I found a way to systematically circunvent this issue, but boy... is it hacky lol:

For `zod`:

```ts
    import * as Zod from "zod"; // not needed if you are into TS
    const zod = require("z" + "o" + "d") as typeof Zod;

    const inputSchema : Zod.ZodSchema<Input> = zod
      .object({
        potato: zod.string(),
      });
 ```
 
 Doing a require is not enough because the compiler is smarter than that and will replace it with `zod/lib/index.js`, but converting it into a dynamic value is enough to let the compiler skip transpiling the package name.

**Comment by lukehoban** [comment]
> Code produced by Pulumi:
> 
> ```ts
> function __f2() {
>   return (function() {
>     with({ zod_1: require("zod/lib/index.js") }) {
> ```
> Code that works:
> 
> ```ts
> function __f2() {
>   return (function() {
>     with({ zod_1: require("zod") }) {
> ```

This is the core of the issue, that we rewrite the `import`/`require` of the root module into a require of the file that ultimately provides this module object.  That is due to the code in https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/runtime/closure/createClosure.ts#L1340:L1372 and the way it uses the module cache.  I'm not entirely sure whether Node offers a way to identify the correct logical module name to use for a specific module object - which is what we'd need to do to ensure that logic continues to work while still supporting Node modules that use `exports` to hide their internals.

**Comment by dixler** [comment]
I have a naive workaround involving mangling paths. Just thought I'd leave it here.

I'll look more into determining logical module name in the meantime.

```node
Welcome to Node.js v12.22.9.
Type ".help" for more information.
> require('noexport')
{ publicFlag: 'this is imported from secret' }
> require('noexport/lib/secret')
Uncaught:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/secret' is not defined by "exports" in /home/kdixler/Documents/issues/8710.pulumi/node_modules/noexport/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:299:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:522:3)
    at resolveExports (internal/modules/cjs/loader.js:424:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at REPL2:1:1
    at Script.runInThisContext (vm.js:120:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
> require('./node_modules/noexport/lib/secret')
{ flag: 'this is imported from secret' }```

**Comment by PupoSDC** [comment]
Thanks a lot @dixler!! Excited to see this make it to a release!
