### ISSUE TITLE
Pulumi reports error of deploy, but no errors on any resource

### ISSUE THREAD

**Issue by mastoj** [pulumi/pulumi#8713]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We have some pulumi deploys that reports that it failed, but all the resources have been created. This causes confusion and also makes it a little bit more problematic to find if there is an issue or not. I'm unsure about the internals of how pulumi works, but one guess on my end is that this happens when we do a `pulumi up` (in our automation tool) then the process that initiated it is sort of cancelled, could be a web request that we stopped, which could mean that when `pulumi up` is finished it doesn't have anywhere to return the data and therefor fails. This would mean the resources have been created but the overall process failed. See screenshot of the result.

### Steps to reproduce

Haven't been able to create a small reproduction.

Expected: 

If all resources are green, then the job should be green, or a least the error message should include what went wrong and not just a generic message.

Actual: 

![image](https://user-images.githubusercontent.com/501424/148758006-de8bf776-c34d-4a26-997e-caec7ee5fb8c.png)

**Comment by justinvp** [comment]
Closing this old issue that doesn't have a repro. If you're still seeing this, please open a new issue.
