### ISSUE TITLE
Issues assigning cloudwatch group to callbackFunction lambda

### ISSUE THREAD

**Issue by ewucc** [pulumi/pulumi#8727]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Unable to assign a custom cloudwatch group to the lambda created from  `aws.lambda.CallbackFunction()`. 
Instead, the custom cloudwatch group is created and unused. A second cloudwatch group is created automatically and used by the lambda from the callback function and is not tracked in the pulumi stack.
### Steps to reproduce

I'm trying to assign a cloudwatch group to the lambda created by the callbackFunction() using code like this 
```
let cwGroup = new aws.cloudwatch.LogGroup("test-group", {})
let callback = new aws.lambda.CallbackFunction("function-12345", { callbackFunctionArgs}, { dependsOn: [cwGroup] }) 
```

Expected: 
I expected a lambda with {name} to be created and the created `cwGroup` to be where logs are sent. I expect to see the cloudwatch group set as a dependency for the lambda created by the callbackFunction().

Actual: 
the cloudWatch group for `cwGroup` is created correctly but a second cloudwatch group called `function-12345` is created and used as destination for the logs instead. 

Looking at the pulumi stack output, I see that the custom cloudwatch group I created is set as a dependency but that is not reflected in AWS.

**Comment by Dynasty9** [comment]
I'm also seeing this same bug

**Comment by cody2094** [comment]
I actually have this issue but slightly different :

The log group `function-12345` is not created, but its expected by the lambda job. When clicking on "view cloudwatch logs" I see an error claiming the log group `/aws/lambda/function-12345` does not exist.
