### ISSUE TITLE
config get is returning a different result to what's displayed in the portal

### ISSUE THREAD

**Issue by wsalahuddin** [pulumi/pulumi#8745]
We are setting a config value of the build number (default format) from azure pipeline e.g.
20220113.2
but on retrieving this config, the value is being read as 
2.02201132e+07

We only noticed this issue today, i.e. pulumi version 3.22.0 
Not sure if this is this version related or the value of the number.

Note: Pulumi portal displays the correct value, but when you copy the value using the copy icon next to the value it shows the incorrect value.

**Comment by krisdehaudt** [comment]
+1, has the same issue

**Comment by mikhailshilkov** [comment]
Probably related to #8752 and #8682? @iwahbe
