### ISSUE TITLE
Config Key:Value in State File

### ISSUE THREAD

**Issue by XavierGeerinck** [pulumi/pulumi#8748]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We are working on a infrastructure deployment and would need to access a config variable to check if a resource was deployed or not (e.g. when we create something through an API call). Is there a way in Pulumi to access a config variable? Is there a way to persist this to the state file?

**Comment by mikhailshilkov** [comment]
Hi @XavierGeerinck 

There's a Pulumi [config](https://www.pulumi.com/docs/intro/concepts/config/) to store per-stack configuration values but I understand you are asking about a different thing.

Is it that you want to do some action, and then record this fact in the state file? I think you could achieve this with a [dynamic provider](https://www.pulumi.com/blog/dynamic-providers/) if you are using TypeScript or Python. I don't think there is an API to write to state file directly - I'm not sure how that would square with the desired-state definition that the Pulumi model provides.

I'm curious to learn more about your scenario.

**Comment by XavierGeerinck** [comment]
Hi @mikhailshilkov Thanks a lot for coming back on this! We indeed checked and came to the conclusion that the dynamic provider was the solution :) using it now and works perfectly!
