### ISSUE TITLE
pulumi config set is changing the entire Pulumi yaml file, not only the specific key

### ISSUE THREAD

**Issue by felipegirotti** [pulumi/pulumi#8752]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

After the update to version `3.22.0` we are facing errors on our Pulumi yaml files, we perform the command `config set --path app.version {commit-hash}`. 
And now the pulumi command are changing other values we have as string to number.
We reverted to run on our pipelines the old version `3.21.0` that working fine.

### Steps to reproduce

1. Create a stack and add values number as string, e.g: `MY_CONFIG: "2020_1"`
2. Run `pulumi -s {stack} config set --path app.version latest`
3. Your file Pulumi.{stack}.yaml is changed the value `MY_CONFIG: 20201`

Expected: We expected that only change the value I set in the command
Actual: Pulumi command is changing other values

**Comment by Frassle** [comment]
I think this is due to https://github.com/pulumi/pulumi/pull/8682
