### ISSUE TITLE
Example generation panic

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#8775]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Upgrading to `pulumi/pulumi` version >= 3.18.0 panics generating examples while binding an invoke signature with a single expression.

This change was a part of https://github.com/pulumi/pulumi/issues/7949

Relevant line: https://github.com/pulumi/pulumi/blame/master/pkg/codegen/pcl/invoke.go#L83

When accessing args[1] we haven't checked that we've got at least 2 arguments so this fails when there is exactly 1 expression.

### Steps to reproduce

Attempt to bind a function call expression with exactly 1 arg e.g. `["aws-native::getPartition"]`

### Impact

Unable to upgrade `aws-native` to use latest version of `pulumi/pulumi`.

**Comment by mikhailshilkov** [comment]
Is `aws-native::getPartition` a valid resource token? Shouldn't it be something like `aws-native:index:getPartition`? Is AWS Native the only provider that faces this issue?

**Comment by stack72** [comment]
the token should indeed have 3 parts to it AFAICR

**Comment by danielrbradley** [comment]
This is a valid token only having two parts as it's a pseudo parameter - not related to a resource type. Reference: [Pseudo parameters reference - AWS::Partition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-partition)

**Comment by danielrbradley** [comment]
Fixed in #8805
