### ISSUE TITLE
Question: is there a way to proceed with destroying a stack if resource not found

### ISSUE THREAD

**Issue by mkabatek** [pulumi/pulumi#8817]
I keep running into the following issue when I want to destroy a stack after a failed update. Is there any way I can bypass the error and move on with destroying the stack. Is there some way to force pulumi to continue?

```
Diagnostics:
  aws:lb:Listener (strata-companion-lb-demo):
    error: deleting urn:xyz: Error deleting Listener: ListenerNotFound: Listener 'arn:aws:elasticloadbalancing:us-west-2:xxx' not found
    	status code: 400, request id: 863e3c28-385a-49a6-8918-5dcf61ab3396

  pulumi:pulumi:Stack (rms-strata-DEMO):
    error: update failed
```

**Comment by Frassle** [comment]
I think `pulumi refresh` should fix this as that should pick up the resource is missing.

**Comment by mkabatek** [comment]
@Frassle thank you I will attempt this.
