### ISSUE TITLE
Unstable test CI on Windows platform

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi#8820]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Test CI (test.yml, test-fast.yml) workflow is flaky and silently fails on Windows with either of the two messages:

* The hosted runner: GitHub Actions 9 lost...the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.

* Received request to deprovision: The request was cancelled by the remote provider.

We ran many experiments based on the hypothesis that the container is running out of memory, but the issue remains open. Some learnings:

* The issue is not specific to a test, it manifests in the following test subsets: integration, integration-and-codegen, etc; splitting integration test subset into further subsets made it manifest in integration-go and integration-nodejs

* Reducing test parallelism to P=1 did not fix the issue (but should have significantly reduced RAM usage)

* Locking Go toolchain so only one instance of RAM-hungry linker can run at a time did not fix the issue

* Detecting and killing orphan processes between tests did not fix the issue

* Instrumenting memory use on Windows shows 30MB per pulumi process, ~100 MB per node process and up to ~600 mb per linker process as part of example Go compilation toolchain; we have not yet reproduced a 4GB RAM utilization needed to run out of memory on the GHA VM

Mitigations:

- [x] Reduced test subsets run on PR verification to avoid failing more PRs on this
- [ ] However master branch is still affected; considering moving Windows testing out of master verification into a dedicated workflow
- [ ] #8824

Going forward:

Would need to reproduce the issue either locally or with significant instrumentation in the GHA container to understand exactly what's going on, perhaps the non-memory causes in the "workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error." list are to blame.

### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:

**Comment by AaronFriel** [comment]
Follow up actions, [per thread in Slack](https://pulumi.slack.com/archives/C9SGX9QA1/p1642804371156800?thread_ts=1642701705.089300&cid=C9SGX9QA1):

- [ ] Skip Windows CI tests on PR checks, add to scheduled job

**Comment by AaronFriel** [comment]
I think this is resolved by #10207, we'll monitor over the iteration. CC @mikhailshilkov

**Comment by AaronFriel** [comment]
This appears to be largely resolved - closing!
