### ISSUE TITLE
iam.GetPolicyDocument example is wrong - also how to create string pointer?

### ISSUE THREAD

**Issue by ghostsquad** [pulumi/pulumi#8821]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Example shows using a go string for the SID, however, the API only accepts a `*string`.

### Steps to reproduce

Copy/paste example into a main.go, go will complain.

Expected: 

The example at least compiles.

Actual: 

![image](https://user-images.githubusercontent.com/55453295/144683474-9c521875-a9b8-42d8-b827-ef2157d875e8.png)

First problem is that pointers to strings, ints, etc aren't a normal thing to do in go, and doing in a normal go-way results in harder to maintain code with extra variables hanging around that shouldn't really be needed.

If you are familiar with the AWS Go SDK (not the pulumi provider), it provides some utility functions to make this easier.

https://docs.aws.amazon.com/sdk-for-go/api/aws/

I didn't see any way to do this using the `pulumi` built-ins either. Even `pulumi.StringPtr("1")` returns a `StringPtrInput` type.

My work around is to import the AWS SDK or a package like: https://github.com/xorcare/pointer

**Comment by t0yv0** [comment]
@AaronFriel

**Comment by AaronFriel** [comment]
Hey @ghostsquad, as @leezen suggested, it is indeed frustrating to deal with pointers in Go. Since you referenced the AWS SDK, I wonder if we read the same StackOverflow post, I think I came across exactly that recommendation yesterday. 

I had to write these little helpers just the other day, and hopefully shows the pattern that's helpful:

```go
func StringRef(s string) *string { return &s }

func ProtocolRef(s v1.Protocol) *v1.Protocol { return &s }

func Int32Ref(s int32) *int32 { return &s }
```

@t0yv0 I wonder if Pulumi's Go SDK should also include conversion utilities like [AWS does](https://docs.aws.amazon.com/sdk-for-go/api/aws/)?

**Comment by ghostsquad** [comment]
Ya, I mean it's easy enough to write my own small functions, or (heavy weight) import the AWS SDK.

At minimum, I wanted to bring to light that it was surprising that the docs were wrong, and although I know the solution, I wanted to help anyone else who ran into this type of problem, and was confused and/or wondering if there was a canonical/idiomatic way of solving this.

I am also requesting that the documents be updated to reflect the canonical/idiomatic way to write the code.

Thank you for your time!

**Comment by AaronFriel** [comment]
Absolutely, the docs should be code you can copy and paste.

**Comment by t0yv0** [comment]
@AaronFriel for context a lot of the code examples are coming from automated source-to-source translators via PCL intermediate form and with ProgramGen.

  https://github.com/pulumi/pulumi/blob/master/pkg/codegen/go/gen_program.go

Not to add to the specific issue here, but thinking of similar problems in this space..

I'm thinking we need to at least have a page in dev docs that explains how this works and where to find the pieces. Non-compiling examples are a big problem.  Having worked with the code a bit we are not in a place where code guarantees producing valid (or even compiling) output, there's some work to  do. 

Open to new ideas also. We could and probably should check the generated corpus of examples for whether they compile or not in an automated fashion. That would be a lot easier and may be of benefit.

**Comment by mikhailshilkov** [comment]
> Open to new ideas also. We could and probably should check the generated corpus of examples for whether they compile or not in an automated fashion. That would be a lot easier and may be of benefit.

FWIW, I did a prototype that compiled all C# examples generated in a given provider. I found a few generation issues but, also, a lot of the source examples weren't "compiler-ready" in the first place: they would reference non-existing resources or have placeholders in places. Say, a TF example would define Resource B using A without defining A at all. This makes me doubt we can ever get it to perfection.

Sorry for going off-topic a bit.

**Comment by t0yv0** [comment]
That's good input, perhaps that's telling us that kind of check would not be practical yet.

**Comment by AaronFriel** [comment]
@ghostsquad hey, there! Thanks for reporting this and I'm pleased to say that in an upcoming release of the pulumi-aws package, these docs should be fixed and we'll show something like this:

```go
    policyDocument, err := iam.GetPolicyDocument(ctx, &iam.GetPolicyDocumentArgs{
      Statements: []iam.GetPolicyDocumentStatement{
        iam.GetPolicyDocumentStatement{
          Sid: pulumi.StringRef("1"),
          //...
```

That should happen soon™️, but release processes take time.

**Comment by guineveresaenger** [comment]
Hi @ghostsquad - as of [this release](https://github.com/pulumi/pulumi-aws/commit/88766e175cef7b562270038aadb3507cd7246ecf) you should see the correct [example in the docs](https://www.pulumi.com/registry/packages/aws/api-docs/iam/getpolicydocument/#basic-example).

Thank you so much for reporting and happy coding!

**Comment by AaronFriel** [comment]
@guineveresaenger it looks like the docs still show the string literal and not `pulumi.StringRef`, but the versions look right to me for this change to have made it in.
