### ISSUE TITLE
Can't disable default Kubernetes provider in 3.23.0 for yaml.ConfigFile

### ISSUE THREAD

**Issue by itay** [pulumi/pulumi#8853]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I am trying out the new Pulumi 3.23.0 capability of disabling the default providers, and have this in my stack:

```
  pulumi:disable-default-providers:
  - aws
  - kubernetes
```

This seems to work well for AWS, but I am having an odd issue with the Kubernetes one. Specifically, I have the following resource:

```
    _, err = yaml.NewConfigFile(ctx, "certmanager-deploy-file", &yaml.ConfigFileArgs{
        File: "./cert-manager.yaml",
        Transformations: []yaml.Transformation{
            // We need to make two modifications:
            // 1. Add the role ARN for IRSA
            // 2. Set the fsGroup for IRSA token mapping
            // Docs here: https://cert-manager.io/docs/configuration/acme/dns01/route53/#eks-iam-role-for-service-accounts-irsa
            func(state map[string]interface{}, opts ...pulumi.ResourceOption) {
                metadata := state["metadata"].(map[string]interface{})
                name := metadata["name"]
                if state["kind"] == "ServiceAccount" && name == "cert-manager" {
                    var annotations map[string]interface{}
                    if v, ok := metadata["annotations"]; !ok {
                        annotations = make(map[string]interface{})
                        metadata["annotations"] = annotations
                    } else {
                        annotations = v.(map[string]interface{})
                    }
                    annotations["eks.amazonaws.com/role-arn"] = irsaRole.Arn
                }
                if state["kind"] == "Deployment" && name == "cert-manager" {
                    deploymentSpec := state["spec"].(map[string]interface{})
                    template := deploymentSpec["template"].(map[string]interface{})
                    podSpec := template["spec"].(map[string]interface{})
                    podSpec["securityContext"] = map[string]interface{}{
                        "fsGroup": 1001,
                    }
                }

            },
        },
    }, pulumi.DependsOn([]pulumi.Resource{irsaRole}), pulumi.Provider(eksConfig.Provider))
    if err != nil {
        return nil, err
    }
```
    
Where eksConfig.Provider is constructed as the result of an eks.Cluster creation:

```
    k8sProvider, err := providers.NewProvider(ctx, "k8s-ssa-provider", &providers.ProviderArgs{
        Kubeconfig: kubeconfig,
    })
    if err != nil {
        return nil, err
    }
```
    
When I run this with the default Kubernetes one disabled, I get this error:

```
    error: program failed: 1 error occurred:
        * decoding YAML: rpc error: code = Unknown desc = unknown provider ''
    exit status 1
```
    
There is not any more info in the logs even if I set logging to 9. If I enable the Kubernetes default provider, it works just fine, even though I am passing an explicit provider here. I know it is this resource that's causing the issue as if I comment it out, things work.

Looking at the state file for this resource, I notice:

```
{
    "urn": "urn:pulumi:prod-us-west-1::okera-infra-regions::kubernetes:yaml:ConfigFile::certmanager-deploy-file",
    "custom": false,
    "type": "kubernetes:yaml:ConfigFile",
    "parent": "urn:pulumi:prod-us-west-1::okera-infra-regions::pulumi:pulumi:Stack::okera-infra-regions-prod-us-west-1",
    "dependencies": [
        "urn:pulumi:prod-us-west-1::okera-infra-regions::aws:iam/role:Role::cert-manager-iam-role"
    ]
},
```

So it seems like this resource does not have a provider set. Maybe because it's a `ComponentResource`? I am not sure.

Also note that I've always passed my custom provider here, even prior to disabling the default Kubernetes one, so there is no explicit provider change.

Is this a bug or am I doing something unexpected here?

### Steps to reproduce

See above.

Expected: I can disable the Kubernetes default provider and everything will work if I pass a default provider.
Actual: I can't disable the Kubernetes default provider.

**Comment by itay** [comment]
For reference, I also asked about it here: https://pulumi-community.slack.com/archives/C84L4E3N1/p1643311388318700

**Comment by iwahbe** [comment]
It looks like a bug to me. I'm going to see if I can put together a repro.

**Comment by itay** [comment]
If it’s helpful, happy to also show this happening live. You’re welcome to ping me on the Slack or via email.

**Comment by iwahbe** [comment]
Component resources don't have real providers, but that shouldn't be a problem
The error message passes through comes from here
https://github.com/pulumi/pulumi-kubernetes/blob/3b905eb3c2f478724bd5fd80de1d62cfec5ea56d/sdk/go/kubernetes/yaml/yaml.go#L140-L147
and is related to the invoke here:
https://github.com/pulumi/pulumi-kubernetes/blob/3b905eb3c2f478724bd5fd80de1d62cfec5ea56d/sdk/go/kubernetes/yaml/yaml.go#L173-L185

If you could build a repro that I could use, that would be amazing. I haven't been able to repro the bug on my own.

**Comment by AaronFriel** [comment]
@iwahbe I think I see the issue here, the child resources are created without passing in the options (in this case, the provider) from the call to `NewConfigFile`:

From the sdk, [sdk/go/kubernetes/yaml/configFile.go#L165-L169](https://github.com/pulumi/pulumi-kubernetes/blob/3f5a2475cf6cac794627ee9740dac5eb290705ef/sdk/go/kubernetes/yaml/configFile.go#L159-L163)
```go
func NewConfigFile(ctx *pulumi.Context,
  name string, args *ConfigFileArgs, opts ...pulumi.ResourceOption) (*ConfigFile, error) {

    // Parse and decode the YAML files.
    rs, err := parseDecodeYamlFiles(ctx, &ConfigGroupArgs{
      Files:           []string{args.File},
      Transformations: args.Transformations,
      ResourcePrefix:  args.ResourcePrefix,
    }, true, pulumi.Parent(configFile))
    if err != nil {
      return nil, err
    }
    configFile.Resources = rs
```

We should either: 

1. Change the codegen to pick options to pass down to child resources
2. Change how we search for providers to search the parent's providers if we don't have one

What makes the most sense to you?

**Comment by AaronFriel** [comment]
@itay it looks like I've gone down the wrong rabbit hole and there may be a solution today. Can you try this:

```
    }, pulumi.DependsOn([]pulumi.Resource{irsaRole}), pulumi.Providers(eksConfig.Provider))
```

There is some tech debt around how `Provider` and `Providers` differ. The former is valid for individual resources, the latter is intended for collections-of-resources where they may have children with different providers, for example if you created a component resource with children that included an S3 bucket and a Kubernetes cronjob at the same time.

**Comment by AaronFriel** [comment]
Note for digging in further: is there an issue with this cast and the fact that we're taking a list of ResourceOption? Nowhere else in pulumi/pulumi or pulumi/kubernetes does a cast like `opt.(pulumi.InvokeOption)` occur.

https://github.com/pulumi/pulumi-kubernetes/blob/3d0c3adcb6252f602ebbe02333d8a8cf67fd6106/sdk/go/kubernetes/yaml/yaml.go#L131-L137

```go
	// Find options which are also Invoke options, and prepare them to pass to Invoke functions
	var invokeOpts []pulumi.InvokeOption
	for _, opt := range opts {
		if invokeOpt, ok := opt.(pulumi.InvokeOption); ok {
			invokeOpts = append(invokeOpts, invokeOpt)
		}
	}
```


I'm too much of a Golang novice here to identify why this cast would fail, and I'll need to do a bit of reading to understand why. 

```
type ResourceOption interface {
	applyResourceOption(*resourceOptions)
}

type InvokeOption interface {
	applyInvokeOption(*invokeOptions)
}

type ResourceOrInvokeOption interface {
	ResourceOption
	InvokeOption
}
```

For posterity: My hunch is that golang implements dynamic dispatch like most languages with a vtables, that `pulumi.Parent` constructs a `ResourceOrInvokeOption` vtable, but when we call `NewConfigFile` and/or `parseDecodeYamlFiles`, passing it as a `pulumi.ResourceOption`, we're dropping the vtable for `pulumi.InvokeOption`. Therefore the cast fails, and we lose the Parent option.

**Comment by itay** [comment]
FYI I did try what @AaronFriel suggested (both with `pulumi.Providers` and `pulumi.ProviderMap`), but neither worked to resolve the issue.

**Comment by AaronFriel** [comment]
@itay updated Kubernetes provider to latest (3.15.0) and that solved it. Oops, should have asked to try that first.

**Comment by itay** [comment]
Yes, sorry about that. Turns out updated software works 👍 

@iwahbe thanks for this awesome new capability!

**Comment by itay** [comment]
@AaronFriel @iwahbe I can't reopen the issue, but I have encountered it again with the most up to date everything using `helmv3`. Specifically, here is my code:

```
func CreateNodeExporter(ctx *pulumi.Context, awsProvider *aws.Provider, eksConfig *EKSConfiguration) error {
	ns, err := corev1.NewNamespace(ctx, "node-exporter-namespace", &corev1.NamespaceArgs{
		Metadata: &metav1.ObjectMetaArgs{
			Name: pulumi.String("node-exporter"),
		},
	}, pulumi.Provider(eksConfig.Provider))
	if err != nil {
		return err
	}

	neValues := map[string]interface{}{
		"namespaceOverride": ns.Metadata.Name().Elem().ToStringOutput(),
	}

	_, err = helmv3.NewChart(ctx, "node-exporter", helmv3.ChartArgs{
		Repo:      pulumi.String("prometheus-community"),
		Chart:     pulumi.String("prometheus-node-exporter"),
		Version:   pulumi.String("3.0.0"),
		Namespace: ns.Metadata.Name().Elem().ToStringOutput(),
		FetchArgs: helmv3.FetchArgs{
			Repo: pulumi.String("https://prometheus-community.github.io/helm-charts"),
		},
		Values: pulumi.ToMap(neValues),
	}, pulumi.Provider(eksConfig.Provider))

	if err != nil {
		return err
	}

	return nil
}
```

With the default `kubernetes` provider disabled as described in the original issue. If I do a `pulumi up`, I get:

```
error: program failed: waiting for RPCs: failed to invoke helm template: rpc error: code = Unknown desc = unknown provider ''
```

If I re-enable the default provider - things work just fine (it uses my explicit provider).

Happens with Pulumi 3.23.0 and 3.24.1, and the following library versions:

```
	github.com/pulumi/pulumi-kubernetes/sdk/v3 v3.15.0
	github.com/pulumi/pulumi/sdk/v3 v3.23.0
```

**Comment by iwahbe** [comment]
@itay With the example you just gave me, I have a consistent repro of the bug! That is super helpful.

**Comment by iwahbe** [comment]
After some investigation, I see two problems: the error message is completely uninformative, and there is a bug in our Kubernetes provider. We call an invoke without giving a provider. The call chain looks like this:
1. https://github.com/pulumi/pulumi-kubernetes/blob/89cd0c24438806a3ff98ffb9ae3a0944e6600639/sdk/go/kubernetes/helm/v3/chart.go#L221
2. https://github.com/pulumi/pulumi-kubernetes/blob/89cd0c24438806a3ff98ffb9ae3a0944e6600639/sdk/go/kubernetes/helm/v3/chart.go#L267
3. https://github.com/pulumi/pulumi-kubernetes/blob/89cd0c24438806a3ff98ffb9ae3a0944e6600639/sdk/go/kubernetes/helm/v3/chart.go#L302
4. https://github.com/pulumi/pulumi-kubernetes/blob/89cd0c24438806a3ff98ffb9ae3a0944e6600639/sdk/go/kubernetes/helm/v3/chart.go#L310

**Comment by iwahbe** [comment]
The error message will be improved by https://github.com/pulumi/pulumi/pull/8978.

**Comment by itay** [comment]
Awesome - I’ll wait for the two PRs to be merged and released!

**Comment by iwahbe** [comment]
Clarified by https://github.com/pulumi/pulumi/pull/8978. Fixed by https://github.com/pulumi/pulumi-kubernetes/issues/1905.

**Comment by itay** [comment]
FYI - I don't know if it was the fix for this that caused this issue, but there's some regression in 3.25.0 related to this functionality in #9055
