### ISSUE TITLE
Stack preview/up failure lacks indication of error cause

### ISSUE THREAD

**Issue by tychedelia** [pulumi/pulumi#8854]
About a week ago, many of our stacks started to fail on version `3.17.0` with a cryptic `an unhandled error occurred: Program exited with non-zero exit code: 1`. Upgrading to `3.22.1` solved all of these, except for a single stack [that continues to error out](https://gist.github.com/tychedelia/829ed6967cdd9ee05c4c330da3be0563). There have been no modifications to this project, and the debug logs appear to confirm that the planner doesn't expect to make any updates.

Some facts that might be relevant:
- We are using the s3 backend.
- Identical stack in different account was failing, but working fine post version upgrade.
- Doing a refresh works fine and is able to interact with the statefile.
- I've tried upgrading provider/all npm dependencies without luck.

Happy to provide any additional information as needed, since this one is kind of cryptic. I've examined the statefile, but there doesn't appear to be anything weird about it.

**Comment by Frassle** [comment]
Can you run with verbose logging turned on "--logtostderr -v=9" and see if that reveals anything?

**Comment by tychedelia** [comment]
@Frassle If you look at the linked gist, verbose logging is on. I can't see anything obvious but maybe you can spot something!

**Comment by Frassle** [comment]
Ah sorry I missed that. We'll have a look!

**Comment by Frassle** [comment]
```EvalSourceIterator ended with an error: an unhandled error occurred: Program exited with non-zero exit code: 1```
It looks like your program is crashing out after starting up (there's a log to register the top level Stack resource from your program).

Could you attach a debugger or turn more logging on in your application?

**Comment by tychedelia** [comment]
Was able to track this down -- it's definitely an application level error. I had ruled out an early exit from our code, since we appropriately log all errors, but didn't realize that the pulumi logging infrastructure is asynchronous, and thus we were exiting before a log message could be printed identifying the error. It makes sense to me given pulumi's arch why logging is async, but I wish there was a way to generate a compile time error for an unused promise.

Thank you for your time.
