### ISSUE TITLE
NX/monorepo support

### ISSUE THREAD

**Issue by Badabum** [pulumi/pulumi#8865]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Hi team, and thanks for amazing product!

I've recently started to use node + NX for monorepo setup and found it quite difficult to setup pulumi support.
Would be nice to get some guidance or even an official plugin for NX. Thanks in advance!

**Comment by mattfysh** [comment]
Hi @Badabum - have you tried the `@wanews/nx-pulumi` plugin?

**Comment by dixler** [comment]
I think the following issues are related to monorepos and there seem to be a lot of pain points for adoption into existing projects. some of the issues may be old and may be solved.

## nodejs
- [ ] #2619
- [ ] #2661 (possibly solved? there's a repro repo)
- [ ] #3013
- [ ] #5541
- [ ] #7168
- [ ] #8787
- [ ] #10009
- [ ] #10022 

## python
- [ ] #7360

These 10 issues collectively have 82 :+1: which would put the aggregate issue into possibly the top 10 upvoted issues(disregarding duplicate upvotes)

It seems that the most commonly referenced monorepo tools are
- nx
- lerna
-  yarn workspaces

cc @mikhailshilkov @lukehoban for after the long weekend.

**Comment by eggsy84** [comment]
> Hi @Badabum - have you tried the `@wanews/nx-pulumi` plugin?

We've got Pulumi working nicely within a mono-repo using the `@wanews/nx-pulumi` plugin also.

https://www.npmjs.com/package/@wanews/nx-pulumi

You can also get it working ok by using NX and the standard `@nrwl/workspace:run-commands` plugin to execute pulumi commands (assuming pulumi on the path as well of course)

**Comment by Badabum** [comment]
@RobbieMcKinstry it would be awesome

**Comment by RobbieMcKinstry** [comment]
We're exploring possible solutions to this issue, along with related monorepo issues, starting next week.

**Comment by julienp** [comment]
We've done a series of changes to how pulumi looks for dependencies during installation and function serialisation, and created an example on how to use Pulumi in an Nx monorepo https://www.pulumi.com/blog/nx-monorepo/
