### ISSUE TITLE
Document pluginDownloadURL flow

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#8890]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This is mostly the process for `pluginDownloadURL`:
- schema
- sdks
- end experience

**Comment by iwahbe** [comment]
@AaronFriel did you have more in mind then https://github.com/pulumi/pulumi-hugo/pull/1029 for this issue?

**Comment by AaronFriel** [comment]
I think we can close this, I have another issue for writing a blog post about Pulumi wordle
