### ISSUE TITLE
CLI bugs after bumping survey to v2.3.2

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#8912]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
- new behavior broke stack selector @Frassle 
  - #8887
  - #8888
- import output is buggy @pgavlin has a recording in the [slack thread](https://pulumi.slack.com/archives/CBUP505U7/p1643713912052759)

### Steps to reproduce

1. [repro recording](https://pulumi.slack.com/archives/CBUP505U7/p1643835004243339?thread_ts=1643713912.052759&cid=CBUP505U7)

Expected: CLI output doesn't overwrite itself 
Actual: CLI output overwrites itself

**Comment by mikhailshilkov** [comment]
Small note: we should not rely on private links in issue decriptions - it's better to copy the text/repro to the issue itself instead of linking to slack.
