### ISSUE TITLE
502 Bad Gateway during stack updates

### ISSUE THREAD

**Issue by dipack95** [pulumi/pulumi#8913]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce

We're seeing a really large number of "502 Bad Gateway" errors when updating our Pulumi stacks today -- [example](https://app.pulumi.com/transcend-io/integration-amplitude/dev/updates/30).

For some context, we've recently moved to using Pulumi to manage our fleets of Lambda functions (and associated infra, like SQS queues, function event invoke configurations, etc.), in past week. We have 100+ stacks that we deploy in a parallel fashion, i.e. a separate deployment process using `pulumi up --refresh --stack <org-id>/<env>`.

These kinds of errors are especially annoying, as it means that we constantly need to manually export the stack's state, remove any pending ops, import the stack back into Pulumi, and re-run the deploy process.

The error message is:

```
integration-amplitude-dev (pulumi:pulumi:Stack)
error: resource complete event returned an error: failed to save snapshot: serializing deployment: serializing resources: failed to encrypt secret value: [502] <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
```

Expected: The deploy process to complete without any issues
Actual: 502 Bad Gateway errors, when it comes to saving snapshots

It would be especially helpful if we could add some support to Pulumi's CLI that could override such errors involving pending operations during a `pulumi up` -- something like a `--force` flag? Or better yet, including some more information on why this keeps happening as part of the error stack.

**Comment by lukehoban** [comment]
There was a transient operational issue earlier today that led to an increased error rate (specifically 502 errors) for a period of time. This has been resolved now. 

https://status.pulumi.com/incidents/9p5ycs357vpl

**Comment by dipack95** [comment]
Okay, thanks for clearing that up! @lukehoban 

The asks still stand though -- is it possible to add an option to force the deployment of a stack in such cases?

**Comment by leezen** [comment]
@dipack95 Having a better workflow around pending operations is tracked in https://github.com/pulumi/pulumi/issues/4265
