### ISSUE TITLE
[codegen/go] Inputty types elision removes necessary types from Azure-native go sdk

### ISSUE THREAD

**Issue by TechnicallyJoe** [pulumi/pulumi#8918]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm trying to run set up a Postgresserver on Azure using the example shown here: https://www.pulumi.com/registry/packages/azure-native/api-docs/dbforpostgresql/server/#create-a-new-server

Copy-pasting this doesn't work because of this error:
`cannot use (dbforpostgresql.ServerPropertiesForDefaultCreate literal) (value of type dbforpostgresql.ServerPropertiesForDefaultCreate) as pulumi.Input value in struct literal: missing method ElementTypecompilerInvalidIfaceAssign`

Code i'm attempting to run:
```
_, err := dbforpostgresql.NewServer(ctx, "server", &dbforpostgresql.ServerArgs{
		Location: pulumi.String("westus"),
		Properties: dbforpostgresql.ServerPropertiesForDefaultCreate{
			AdministratorLogin:         "cloudsa",
			AdministratorLoginPassword: "<administratorLoginPassword>",
			CreateMode:                 "Default",
			MinimalTlsVersion:          "TLS1_2",
			SslEnforcement:             "Enabled",
			StorageProfile: dbforpostgresql.StorageProfile{
				BackupRetentionDays: 7,
				GeoRedundantBackup:  "Disabled",
				StorageMB:           128000,
			},
		},
		
		ResourceGroupName: pulumi.String("TestGroup"),
		ServerName:        pulumi.String("pgtestsvc4"),
		Sku: &dbforpostgresql.SkuArgs{
			Capacity: pulumi.Int(2),
			Family:   pulumi.String("Gen5"),
			Name:     pulumi.String("B_Gen5_2"),
			Tier:     pulumi.String("Basic"),
		},
		Tags: pulumi.StringMap{
			"ElasticServer": pulumi.String("1"),
		},
	})
	if err != nil {
		return err
	}
```

### Steps to reproduce
The example shown here: https://www.pulumi.com/registry/packages/azure-native/api-docs/dbforpostgresql/server/#create-a-new-server

Expected: No error when using the struct shown in the example.
Actual: Got an error

`cannot use (dbforpostgresql.ServerPropertiesForDefaultCreate literal) (value of type dbforpostgresql.ServerPropertiesForDefaultCreate) as pulumi.Input value in struct literal: missing method ElementTypecompilerInvalidIfaceAssign`

**Comment by Zaid-Ajaj** [comment]
I believe this is fixed by https://github.com/pulumi/pulumi/pull/14679 but we need a new version of azure-native modules published in order to close it out

**Comment by Zaid-Ajaj** [comment]
I believe this is no longer an issue. In azure-native v2, missing `Args` variant of types were re-enabled and the example https://www.pulumi.com/registry/packages/azure-native/api-docs/dbforpostgresql/server/#create-a-new-server should now work.
