### ISSUE TITLE
git_test.go's tests fail if git has no global user.email and user.name config set

### ISSUE THREAD

**Issue by patriziobrunops** [pulumi/pulumi#8924]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
I'm building pulumi on my Fedora Silverblue laptop in a toolbox container and getting test failures in `sdk/go/common/util/gitutil/git_test.go`. It would probably make sense to set `user.name` and `user.email` locally in the test repo. Something else I've found fixing this, the tests make the assumption that git uses `master` as default init branch, which with recent git versions is no more the case, in fact the new default is `main`.
error log:
```
    environment.go:94: Created new test environment:  /tmp/test-env3127899202
    git_test.go:189: Running command git init
    git_test.go:192: Running command git add *
    git_test.go:193: Running command git commit -m 'Initial commit'
    git_test.go:193: Ran command git args [commit -m 'Initial commit'] and expected success. Instead got failure.
    git_test.go:193: Run Error: exit status 128
    git_test.go:193: STDOUT: 
    git_test.go:193: STDERR: Author identity unknown
        
        *** Please tell me who you are.
        
        Run
        
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
        
        to set your account's default identity.
        Omit --global to set the identity only in this repository.
```
### Steps to reproduce

1. Follow instructions at CONTRIBUTING.cmd
2. run `make` from the repo root

Expected: successful build
Actual: gitutil/git tests fail because they rely on local configuration that is not available

**Comment by patriziobruno** [comment]
I noticed another problem with this. The tests assume that `init.defaultBranch` is set to `master`, but newer git installations have it set to `main`.
