### ISSUE TITLE
Set Environment.ExitCode = -1 when exception thrown in stack results in resources marked for deletion

### ISSUE THREAD

**Issue by guitarrapc** [pulumi/pulumi#8942]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I would like to suggest setting `Environment.ExitCode = -1` when Pulumi caught exception during stack results.

Background:
Pulumi can write with C# Top-level statement but if user forget to `return` then generated code is not `Task<int>` but `Task`.
This easily reproduce #7050.

Yes, I met this issue and deleted my resources.

```cs
using Pulumi; // and so on...

// bad example. Exception in stack result but ExitCode is 0, resources will be deleted.
await Deployment.RunAsync<MyStack>();

// good. Exception in stack result and ExitCode is 1, stop execution right after.
return await Deployment.RunAsync<MyStack>();
```

Sharplab without return. 
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQGUCWBbADgGwgAUEB7AcwSm2QBoATEAagB8ABAJgEYBYAKDYAGAARsuAVgDc/fmwCcwgGKlSAOmWkAgsgCeAOwDGACgCU0vrIDMojkpX8A3v2EvR1sQDZRADlEeAPJh6MAB8dlq6hqbOrk58rgmiCmweqgAiEPhQOkYAKjgQ6LhQeupk2OgQBqR69MhGliZmMYmiAOzCXOYJAL78PUA=

Sharplab with return.
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQGUCWBbADgGwgAUEB7AcwSm2QBoATEAagB8ABAJgEYBYAKDYAGAARsuAVgDc/fmwDsogJzCAYqVIA6NaQCCyAJ4A7AMYAKAJTS+sgMyiOq9fwDe/Ye9F2xANlEAOUW8AHkxDGAA+R10DEws3D1c+D2SlQI0AEQh8KH1TABUcCHRcKEMtMmx0CGNSQ3pkUxtzS3iU0QUuK2SAX35uoA==

### Affected area/feature

* sdk/dotnet

**Comment by AaronFriel** [comment]
Hey @guitarrapc, apologies for the delay here. I'm looking at this and I think we'll have to close this as by-design, but I'm going to ask @mikhailshilkov here.

Mikhail, I think setting the exit code on this overload of the task runner makes sense, and the main function tends to be just returning the result of this overload of `RunAsync`. If we modified RunAsync here to set `Environment.ExitCode`, would that affect automation API?

https://github.com/pulumi/pulumi/blob/b0f51a6b2c298488f2dbb7e81c8efc469a7c868d/sdk/dotnet/Pulumi/Deployment/Deployment_Run.cs#L103-L104

**Comment by mikhailshilkov** [comment]
@AaronFriel I think the proposal is to keep the signature and behavior of `RunAsync` but _also_ set the exit code. I haven't tried if it  solves the problem, but assuming yes, I don't think it would break automation API or any other consumers. Or how will it?

**Comment by AaronFriel** [comment]
I wasn't sure if the automation API might _also_ call the Deployment.RunAsync static method.

**Comment by mikhailshilkov** [comment]
@AaronFriel Ah, thank you, now I see what you mean. That's a good point. I don't think that Automation API calls `RunAsync` (it may call `RunInlineAsync` for inline stacks) but I had actually to go and inspect the code to find that out, which gave me a pause.

Now I agree that assumption of being in control of the process may be dangerous here.
