### ISSUE TITLE
[codegen/go] pulumiTypes.go is too large to compile

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi#8950]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Originally filed on pulumi-aws with title: New WAFv2 rule (in go) causes CPU to spike and doesn't run
When trying to create a new wafv2.rulegroup in Go, the CPU shoots up to nearly max and won't even show a preview.

```zsh
❯ go version
go version go1.17.5 darwin/amd64
```

### Steps to reproduce

The following code causes this issue to happen:

```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/wafv2"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		_, err := wafv2.NewRuleGroup(ctx, "rule-group", &wafv2.RuleGroupArgs{
			Capacity: pulumi.Int(713),
			Scope:    pulumi.String("REGIONAL"),
			VisibilityConfig: &wafv2.RuleGroupVisibilityConfigArgs{
				CloudwatchMetricsEnabled: pulumi.Bool(true),
				MetricName:               pulumi.String("waf-rules"),
				SampledRequestsEnabled:   pulumi.Bool(true),
			},
		})

		if err != nil {
			return err
		}

		return nil
	})
}
```

a similar program in typescript doesn't have the same outcome (the preview shows and and the resource is created):

```typescript
import * as aws from "@pulumi/aws";

const rule = new aws.wafv2.RuleGroup("rule-group", {
    capacity: 70,
    scope: "REGIONAL",
    visibilityConfig: {
        cloudwatchMetricsEnabled: true,
        metricName: "test-metric",
        sampledRequestsEnabled: true
    }
})

```

Expected:  New rule group is created
Actual: new rule group fails to be created and the program just hangs. It doesn't even show a preview

**Comment by mikhailshilkov** [comment]
This will be fixed by https://github.com/pulumi/pulumi-aws/pull/2589 in 6.0 of the provider
