### ISSUE TITLE
[codegen/go] Secret outputs not generated correctly

### ISSUE THREAD

**Issue by rawkode** [pulumi/pulumi#8967]
@lblackstone if you have a few minutes, it would be great if you could verify if this is intended behaviour or not.

Thanks

### Discussed in https://github.com/pulumi/pulumi/discussions/8965

<div type='discussions-op-text'>

<sup>Originally posted by **frezbo** February 10, 2022</sup>
When generating a secret value as output using a sample schema like https://github.com/frezbo/pulumi-provider-talos/blob/8300bfa1ea9a42e2bd9748a4ccf8d36d7af7ec54/provider/cmd/pulumi-resource-talos/schema.json#L124-L157 if output property `secretsBundle` is not duplicated in `inputProperties` and the output property is marked as a `secret` by adding like below snippet

```json
"properties": {
                "secretsBundle": {
                    "type": "object",
                    "$ref": "#types/talos:bundle:SecretsBundle",
                    "secret": true
                }
            },
```

The generated code is like this:

```go
+       if args.SecretsBundle != nil {
+               args.SecretsBundle = pulumi.ToSecret(args.SecretsBundle).(SecretsBundleTypeOutput)
+       }
+       secrets := pulumi.AdditionalSecretOutputs([]string{
+               "secretsBundle",
+       })
+       opts = append(opts, secrets)
```

as seen from the generated code, it considers `SecretsBundle` as an input argument as `args.SecretsBundle`

I've also looked into the pulumi code and I believe https://github.com/pulumi/pulumi/pull/7128 this change might have broken it. The test for the provider codegen https://github.com/pulumi/pulumi/blob/a1e18dae4dc00142c086fcae0a90171f278db166/pkg/codegen/testing/test/testdata/simple-yaml-schema/schema.yaml#L77-L85 also defines an input property and an output property with the same name `bar`. Is that a requirement for the provider? I can't think of a use case where the input and output property always need to be the  same name.</div>

**Comment by lblackstone** [comment]
The intended behavior is that the input and output side can be marked secret independently. See [this comment](https://github.com/pulumi/pulumi/pull/7128/files#r638956831) for more detail.

I skimmed through the linked PR, and it looks like the Go codegen may have a bug: https://github.com/pulumi/pulumi/pull/7128/files#diff-077694b97192c663e9314d22e695e6040d200174f3a2ef437021384302b9fd99R1184-R1185

Somebody should dig into this further, but it looks like the input secret state may be incorrectly linked to the output state. The other SDKs looked right, but that should be confirmed as well.

**Comment by justinvp** [comment]
The issue is only with Go codegen. More details in #9050
