### ISSUE TITLE
Pulumi stack file doesn't unlock with running a single pipeline

### ISSUE THREAD

**Issue by maksatbek710** [pulumi/pulumi#8973]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We use CI/CD pipeline combined pulumi and s3 as backend. But sometimes pulumi locks the state which is expected when two jobs try to change state, but even there is only one job left it wouldn't unlock the state.

**Comment by mikhailshilkov** [comment]
In particular, there was one change related to locking in 3.23.0. Could you try 3.22.1 to see if it helps?

**Comment by maksatbek710** [comment]
Hello, I'm sorry, I was on vacation. We are using cloudlflare `4.0.0` and pulumi `3.21.0`

**Comment by maksatbek710** [comment]
> In particular, there was one change related to locking in 3.23.0. Could you try 3.22.1 to see if it helps?

We have project that deploy aws  resource which is held by CI/CD pipeline. And Other projects using it as template. We randomly see that error in any projects. I tested and made sure there is only single pipeline running but it still show pulumi state lock error.

**Comment by Marius-O** [comment]
I'm seeing this issue after upgrading from v2.25.2 to v3.30.0. Preview works, yet deployment fails with the error described in this thread. Any suggestions? Our backend is Azure.

**Comment by Frassle** [comment]
Preview doesn't try to take the state lock. Are you sure locks are getting left locked, rather than you just have multiple deployments trying to run at once and failing because they can't get the lock (which is expected, and has https://github.com/pulumi/pulumi/issues/4052 tracking a feature to wait instead of fail)

**Comment by Marius-O** [comment]
> Preview doesn't try to take the state lock. Are you sure locks are getting left locked, rather than you just have multiple deployments trying to run at once and failing because they can't get the lock (which is expected, and has #4052 tracking a feature to wait instead of fail)

Yes, quite convinced locks remained locked, we only run pulumi via CI/CD so I can track what's running at what point in time. Also after the run the lock stays in place indefinitely (the file is there even after 5hrs), so something is terminating ungraciously. Perhaps the upgrade cause it? Also noticed after the upgrade, there's a resource diff in the preview without any changes to the stack.

**Comment by Frassle** [comment]
> so something is terminating ungraciously.

Given these are just files the unlocking code will only run if pulumi shuts down gracefully. If your CI is killing the pulumi process I would expect locks to get stuck.

> Also noticed after the upgrade, there's a resource diff in the preview without any changes to the stack.

That happens sometimes, providers will sometimes say a value is a diff because of changes in how the value is normalised to their backend. If you think it's a bug raise an issue in the relevant provider repo.

**Comment by Marius-O** [comment]
Is there any way I can enable verbose logging on `pulumi/actions@v3`? Perhaps I can get a better understanding of what's going on?

**Comment by Frassle** [comment]
Not currently, it would be worth raising that as an issue at https://github.com/pulumi/actions/issues

**Comment by Marius-O** [comment]
Added https://github.com/pulumi/actions/issues/589

In the meanwhile I've sorted my issue as well. The SAS token that we were using to interact with the backend storage did not have delete permissions. The deployment was successful each time, but the lock was never being removed, causing subsequent deployments to fail. I'm going to guess that in v2 the locking mechanism was different.

Thanks for your involvement @Frassle

**Comment by paultreadel** [comment]
> The SAS token that we were using to interact with the backend storage did not have delete permissions.

Thanks for reporting your resolution.  I was having exactly the same issue and was completely stuck on what could be going wrong.  Everything was reporting as successful by the CI/CD pipeline so I had no indication of what was going wrong.
