### ISSUE TITLE
Failure communicating with management.azure.com on WSL2 - Cannot unmarshal DNS message 

### ISSUE THREAD

**Issue by adolfojulcamoro** [pulumi/pulumi#8974]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Please help me with the error. I unknow the origin. The SP's credentials are does correct and it have Contributor permission.

azure:core:ResourceGroup pangeacodemoprd  error: Unable to list provider registration status, <br/>it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure sending request: StatusCode=0 -- Original Error: Get "https://management.azure.com/subscriptions/[secret]/providers?api-version=2016-02-01": dial tcp: lookup management.azure.com on 172.17.96.1:53: cannot unmarshal DNS message

**Comment by Frassle** [comment]
Are you running in WSL by any chance? https://github.com/microsoft/WSL/issues/7642#issuecomment-1032751472

**Comment by AaronFriel** [comment]
Hey @AdolfoJulcamoro, this may be an issue we're tracking upstream issue with the Go language's DNS implementation here: https://github.com/golang/go/issues/51127

If you're using the Windows Subsystem for Linux 2 (WSL2) on Windows, there are some things you can try:

1. Edit `/etc/resolv.conf` in WSL to use a DNS server on your network, or a public DNS server such as `1.1.1.1`:

```
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
# nameserver 172.20.32.1
# ❌⬆️ comment out this line here
nameserver 1.1.1.1
# ✅⬆️ add this line here
```

2. Edit the hosts file on Windows.

To figure out the right IP address to use for your location, I recommend first running `host management.azure.com`:

```
$ host management.azure.com
# ignore all of the output except:
... has address aaa.bbb.ccc.ddd # ⬅️ copy this IP address
```

Another thing you can try is, on Windows, to edit your hosts file, you'll need to run Notepad as an admin, then open `C:\Windows\System32\Drivers\etc\hosts`, and you can then add a line like so:

```
# Copy the IP address your system resolved here:
aaa.bbb.ccc.ddd management.azure.com
```

**Comment by AdolfoJulcamoro** [comment]
Thank you very much to all. I see it was a very simple fix bug
