### ISSUE TITLE
Pulumi import not working for vault:gcp/secretBackend:SecretBackend

### ISSUE THREAD

**Issue by sfc-gh-tbacon** [pulumi/pulumi#8976]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Pulumi produces the following errors when attempting to import a [Vault GCP secrets backend](https://www.pulumi.com/registry/packages/vault/api-docs/gcp/secretbackend/):

> error: vault:gcp/secretBackend:SecretBackend resource 'example_vault_gcp_secret_backend_xxx0' has a problem: Attribute must be a whole number, got . Examine values at 'SecretBackend.DefaultLeaseTtlSeconds'.
> error: vault:gcp/secretBackend:SecretBackend resource 'example_vault_gcp_secret_backend_xxx0' has a problem: Attribute must be a whole number, got . Examine values at 'SecretBackend.MaxLeaseTtlSeconds'.

The default and max lease TTL values are currently set to the default of `0s`.

### Steps to reproduce

1. create a GCP secrets engine in vault
2. attempt to import it using pulumi import

Expected: 
The resource would be imported to the stack state
Actual: 
Pulumi throws the above errors

**Comment by mikhailshilkov** [comment]
Import functionality has been significantly refactored in #8922 to substantially reduce the number of failures during `pulumi import` and make the generated code more truthful and complete. We haven't tested this exact issue, but we believe it's addressed by the refactoring.

I'll go ahead and close the issue - feel free if you still get issues with it after upgrading to the Pulumi CLI version 3.26.1 or above.

Read more about the changes in [Easier IaC adoption with improved `pulumi import` experience](https://www.pulumi.com/blog/changes-to-import/).
