### ISSUE TITLE
TLS/SSL error at Python project creation

### ISSUE THREAD

**Issue by fingoldo** [pulumi/pulumi#8977]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce

On Windows Server 2019,  Python 3.8.8, trying in command line or Anaconda prompt:
`pulumi new aws-python`
2. ... typing in project name, description, stack name, aws region
```
Creating virtual environment...
Finished creating virtual environment
Updating pip, setuptools, and wheel in virtual environment...
```

Expected: 
_successful installation_

Actual: 
```
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```
However, project is created in the pulumi dashboard.
What should I do to fix the SSL errors?

**Comment by joeduffy** [comment]
I am not sure what's causing this, however, this StackOverflow thread seems to have some proposed Windows fixes that have worked for others: https://stackoverflow.com/questions/45954528/pip-is-configured-with-locations-that-require-tls-ssl-however-the-ssl-module-in. Not sure why it's talking about "Anaconda" to be honest, but that's probably just my naivety on standard Python/Windows configurations. I am just mentioning here in case it helps until someone can take a look.

**Comment by fingoldo** [comment]
I have copied libcrypto-1_1-x64.* and libssl-1_1-x64.* files, as was suggested (they were not present), and re-run pulumi new command, however, the same error appeared (
But thank you anyway guys for trying to help.

**Comment by fingoldo** [comment]
Hi all. Can you kindly provide a hint, where is the following attempted:

python.exe -m pip install --upgrade pip setuptools wheel

I have no problems installing any package in my Windows. But probably since you are doing it through venv, whatever actions I take in the main OS are useless to venv. There are suggestions to run pip with [additional flags ](https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi) and I'd like to try them, but I can't locate the source of the command itself. Or is it compiled somewhere?
