### ISSUE TITLE
Unexpected locking error when using the Automation API on NodeJS with S3 backend

### ISSUE THREAD

**Issue by barakcoh** [pulumi/pulumi#8984]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Hi Team,

We are trying to use the Automation API on our backend NodeJS server with the S3 backend but we keep getting the following error:
`error: the stack is currently locked by 1 lock(s). Either wait for the other process(es) to end or manually delete the lock file(s)`

Note the stack isn’t locked before running `stack.up` and setting `PULUMI_SELF_MANAGED_STATE_LOCKING=0` doesn't help.

We are experiencing this error only while using the Automation API with S3 as our Pulumi backend. Everything works fine when using Automation with the pulumi.com backend or with deploying using the CLI with S3 backend.

It looks like the S3 backend might be performing excessive locking.

### Steps to reproduce
```ts
const program = async () => {
   const rawDataBucket = await aws.s3.getBucket({ bucket: rawDataBucketId });
   ...
}

const stack = await LocalWorkspace.createOrSelectStack(
  {
   stackName,
   projectName,,
   program,
  },
  {
   envVars: {
    PULUMI_CONFIG_PASSPHRASE: '',
    PULUMI_SELF_MANAGED_STATE_LOCKING: 1
   },
  }
 );
await stack.up({
   onOutput: console.log,
   onEvent: console.log,
  });
```

Expected: `stack.up` completes successfully
Actual: `stack.up` fails with `error: the stack is currently locked by 1 lock(s). Either wait for the other process(es) to end or manually delete the lock file(s)`

**Comment by mikhailshilkov** [comment]
@barakcoh There was one change related to locking in 3.23.0. Could you install the CLI 3.22.1 to see if it helps?

**Comment by barakcoh** [comment]
hi @mikhailshilkov we were already on 3.47.1 so that's not the issue, but turns out we were simplify missing the `s3:DeleteObject` so the first lock couldn't be deleted. 

Would be nice if the error was more informative (seems now the exception that occurs whe trying to delete the lock is being swallowed)

**Comment by slikk66** [comment]
Just hit same issue.. was not clear by the error message anywhere that insufficient S3 permissions were to blame, thanks @barakcoh for posting the solution 🙌
