### ISSUE TITLE
Add documentation for disabling default providers

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#8987]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Describe https://github.com/pulumi/pulumi/issues/3383 in our docs. Probably in https://www.pulumi.com/docs/intro/concepts/resources/providers/.

**Comment by lukehoban** [comment]
I wonder if we might also want to add a section at the bottom of https://www.pulumi.com/docs/intro/concepts/config/ that contains a list of all `pulumi:` config options understood by the Pulumi engine.  For now, that would include just this option, but could be a single place to include all such global configuration.  That would then be a little like https://www.pulumi.com/docs/reference/cli/environment-variables/ as a single place to understand all CLI env vars.
