### ISSUE TITLE
HCL Language Host

### ISSUE THREAD

**Issue by damianh** [pulumi/pulumi#8989]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I, and I'm expect many others, would very much like to see support for an HCL language host. The core reasons I can offer from my various encounters advocating Pulumi:

1. There is a body of existing HCL that they don't want to rewrite _nor_ convert to another language.
2. Orgs/teams with varied capabilities where there are people with TF / HCL experience but would not consider themselves programmers mixed with people with programming language capability. In such case, one might have some projects/stacks in HCL e.g. networking, and others in C#/TS (e.g. app/service). A mix'n'match approach could be palatable.

I think it would **really** help with adoption and it would certainly help to reduce resistances that I encounter.

**Comment by damianh** [comment]
https://opentf.org/announcement

Perhaps it is politically safer now to do this.

**Comment by Frassle** [comment]
> There is a body of existing HCL that they don't want to rewrite nor convert to another language.

This is not going to happen. The pulumi engine and pulumi providers are a meaningfully different interface to terraform. Even if we supported HCL as a language it would have to be our own dialect of HCL and Terraform HCL would have to be converted.

Now in many cases the end results would look _very_ similar, but it would not be the same.

> Orgs/teams with varied capabilities where there are people with TF / HCL experience but would not consider themselves programmers mixed with people with programming language capability. In such case, one might have some projects/stacks in HCL e.g. networking, and others in C#/TS (e.g. app/service). A mix'n'match approach could be palatable.

Our current suggestion would be to use pulumi-yaml for these cases, but we're open to hearing more about how HCL would be meaningfully different from YAML, so it's not totally out of the question.

**Comment by damianh** [comment]
Thanks for the response.

The idea here about supporting HCL as a language provider would be to reduce the friction of porting existing bodies of existing HCL code to Pulumi and be maintained as HCL there after. I would absolutely not expect bi-directional compatibility, a dialect with some conversions during a port would be reasonably expected.

The suggestion of using YAML instead would imply a complete rewrite.
