### ISSUE TITLE
Large typings file (xxx.d.ts) problems when using WebStorm

### ISSUE THREAD

**Issue by chutch1122** [pulumi/pulumi#9000]
When using WebStorm with the TypeScript/Node module, it seems like having the `.d.ts` typings file as large as it is (in the case of `types/inputs.d.ts` with `@pulumi/azure-native@1.58.0` it is ~25 MB) is causing the type completion and auto-import features to not work. These features work with most other `.d.ts` typings files (eg: `documentdb/mongoDBResourceMongoDBCollection.d.ts` - which happens to be pretty small).

I suspect that if `types/inputs.d.ts` could be split apart into multiple `.d.ts` files then type completion and auto-import would work properly.

Large file "Read Only Mode"- `types/inputs.d.ts`
![image](https://user-images.githubusercontent.com/3986362/154115196-09c72351-1ebe-4725-ba7d-7d3c8c824978.png)

Small file -  `documentdb/mongoDBResourceMongoDBCollection.d.ts`
![image](https://user-images.githubusercontent.com/3986362/154114962-f9df93fb-32a2-45ef-afb3-c61358dba546.png)

**Comment by danielrbradley** [comment]
@pulumi/platform-core transfering this as it would appear this could only be solved by changing the way we generate the files for input and output types. Ideally, we'd split each namespace's types into separate files so they could be referenced individually to solve performances issues such as this one.

**Comment by mikhailshilkov** [comment]
Tracked in https://github.com/pulumi/pulumi/issues/6571
