### ISSUE TITLE
Add completion as an alias to gen-completion

### ISSUE THREAD

**Issue by christianh814** [pulumi/pulumi#9005]
## Add completion as an alias to gen-completion

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add `completion` as an alias to `gen-completion`, since I thought (initially) the `pulumi` cli didn't support this.

### Affected area/feature

Pulumi cli

**Comment by mikhailshilkov** [comment]
Hey @christianh814 thank you for the suggestion.

I'm not yet sure - `gen-completion` seems to be more specific. Do you have any references to other CLIs that do a similar thing and what their commands are called? cc @Frassle @justinvp for opinions

**Comment by Frassle** [comment]
I know github call this [command `completion`](https://cli.github.com/manual/gh_completion) but I'm not sure if there's any consistency across tools for this?

**Comment by christianh814** [comment]
> Hey @christianh814 thank you for the suggestion.
> 
> I'm not yet sure - `gen-completion` seems to be more specific. Do you have any references to other CLIs that do a similar thing and what their commands are called? cc @Frassle @justinvp for opinions

Actually, now that I think about it, this may just be a cloud-native tool thing. Here is a snippet from my `~/.bashrc` file

```shell
source <(argocd completion bash)
source <(argo completion bash)
source <(helm completion bash)
source <(kubectl completion bash)
source <(kind completion bash)
source <(oc completion bash)
source <(openshift-install completion bash)
source <(tkn completion bash)
source <(tkn pac completion bash)
source <(kustomize completion bash)
source <(yq shell-completion bash)
source <(operator-sdk completion bash)
source <(kam completion bash)
source <(clusterctl completion bash)
source <(clusterawsadm completion bash)
source <(flux completion bash)
source <(hugo completion bash)
source <(eksctl completion bash)
source <(hypershift completion bash)
source <(pulumi gen-completion bash)
```

This is mainly just convenience. Initially, I thought the Pulumi cli had no shell completion generation because I was used to the `completion` subcommand. Thought it would be nice to add to avoid having others make the same assumption I initially did.

**Comment by Frassle** [comment]
That seems enough examples for this change to be consider reasonable, I'll approve the PR
