### ISSUE TITLE
Wrong delete order of destroying EKS cluster and Node Group

### ISSUE THREAD

**Issue by Dysproz** [pulumi/pulumi#9009]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

In infrastructure that contains EKS cluster and Node Group attached to it `pulumi destroy` command fails on deleting EKS cluster with error: `ResourceInUseException: Cluster has nodegroups attached`.

However, node group is deleted after pulumi fails to destroy EKS cluster so running `pulumi destroy` second time success.
It seems that there's no mechanism in pulumi that'll make EKS cluster delete operation wait first to delete node group.

I'm using pulumi v3.24.1 with Typescript

### Steps to reproduce

1. Create infrastructure with EKS cluster and Node Group attached to the cluster.
2. Run `pulumi destroy`
3. Pulumi fails with `ResourceInUseException: Cluster has nodegroups attached`

Expected: pulumi destroys everything in the first run.
Actual: EKS cluster destroy fails and it's necessary to run destroy command the second time.

**Comment by danielrbradley** [comment]
Hi, thanks for reporting. 

Which Pulumi resource providers are you using? Are you using `@pulumi/aws` or `@pulumi/eks`?

This is likely to be caused by not having implicit dependencies between the components being created (e.g. using an output from the cluster when creating the nodegroups). This should be able to be worked around if using `@pulumi/aws` by using an explict [DependsOn](https://www.pulumi.com/docs/intro/concepts/resources/options/dependson/).

**Comment by danielrbradley** [comment]
I don't think this should be related to 772 as that usually results in a hard program crash.

That's suprising that `dependsOn` doesn't fix this. Might you be able to share a minimal example of your program to show how you're constructing the resource properties and the dependsOn options? Hopefully a minimal reproduction will help us narrow down the cause of the dependency not being honnored.

**Comment by Dysproz** [comment]
I wanted to prepare a minimal example of what we do with pulumi and reproduce the problem without sharing the whole code. However, when I put it in a single resource I couldn't reproduce the bug.
I've started looking and found out that the problem was probably with the code structure that we use - we have a couple of classes extending ComponentResource that make a stack. It seems that adding `parent: this` to resources created under class solves the problem for me.
Thanks for help @danielrbradley, I think that we may close this issue. :)

**Comment by danielrbradley** [comment]
Thanks for the update @Dysproz happy to help ☺️
