### ISSUE TITLE
Add information to the schema that indicates which resource properties cause replacement

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#9017]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add information to the schema that indicates which resource properties cause replacement. this is in support of adding an indicator of this to our docs, see https://github.com/pulumi/registry/issues/518 for a bit more context.

**Comment by mikhailshilkov** [comment]
We do have a `ReplaceOnChanges` property in the schema but I don't think it's being used consistently in the existing providers.

> // ReplaceOnChanges specifies if the property is to be replaced instead of updated (default false).
	ReplaceOnChanges bool

**Comment by mikhailshilkov** [comment]
Update on the above - we decided that we want to decouple `ReplaceOnChanges` from the flag that would be used in docs. We should create the latter - and this issue will be tracking this work.
