### ISSUE TITLE
Python providers not working

### ISSUE THREAD

**Issue by calumabarnett** [pulumi/pulumi#9024]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Since `pulumi==3.23.0` we've experienced issues when creating resources with custom providers. When running `pulumi preview` or `pulumi up` we typically get an error of the form:
```
ValueError: Attempted to register resource kubernetes:core/v1:Namespace with a provider for '<pulumi.output.Output object at 0x10dddc5b0>'
```

### Steps to reproduce

With `pulumi==3.24.1`, `pulumi-eks==0.37.1` and `pulumi-kubernetes==3.16.0`, running `pulumi preview` or `pulumi up` with the following programme raises the above error.

We expect that this would run successfully.

```python
from pulumi import ResourceOptions
from pulumi_eks import Cluster
from pulumi_kubernetes.core.v1 import Namespace

cluster = Cluster(resource_name="test")

namespace = Namespace(
    resource_name="test", opts=ResourceOptions(provider=cluster.provider)
)
```

This may be related to #8770.

**Comment by PriyaBasker23** [comment]
We have couple issues around provider s    
```
     provider = Provider(
            resource_name="test-provider",
            assume_role="arn:aws:iam::********:role/test-role",
        )
        test_pipeline = TestPipeline(
            name="test",
            provider=provider,
        )
    
>       assert provider == test_pipeline._curatedBucket._providers["aws"]

```
Error - KeyError: 'aws' . If i specify the package name  instead of 'aws' then the unit test passes. It would be good to know the change happened related to providers

**Comment by PriyaBasker23** [comment]
Another issue with Provider . 
In the middle of building stack the provider assumes a different role ( or provider is switched to different account, Eg: below code 
```
provider = Provider(
        resource_name="different_account",
        region="eu-west-1",
        assume_role=ProviderAssumeRoleArgs(role_arn=role_arn),
    )
```
```
 self._JobScript = BucketObject(
            resource_name=f"{name}-glue-job-script",
            opts=ResourceOptions(depends_on=[self._rolePolicy], provider=provider),
            bucket=destination_bucket.name,
            key=f"glue-job-scripts/{glue_script.split('/')[-1]}",
            server_side_encryption="AES256",
            source=FileAsset(glue_script),
            tags=tagger.create_tags(f"{name}-glue-script"),
```
Fails while doing above operation  and following error occurs - Access denied error 

aws:s3:BucketObject test-ab40dc-glue-job-script **creating failed** '
'Diagnostics:'
('    \t* Error uploading object to S3 bucket (test-ab40dc-curated): '
[459](https://github.com/ministryofjustice/data-engineering-pulumi-components/runs/5144508255?check_suite_focus=true#step:11:459)
 'AccessDenied: Access Denied')

**Comment by mikhailshilkov** [comment]
@iwahbe Could you please check?

**Comment by iwahbe** [comment]
Successfully reproduced. I'm working on a fix now.

**Comment by iwahbe** [comment]
@calumabarnett Thanks for the clear repro. It is appreciated. #8770 added additional verification on the providers being passed in. To do this verification, we need to examine the value of `provider`, which relies on the field type being eager: https://github.com/pulumi/pulumi/blob/e1d65a7a9a3b77b5c1c0c243f56d21ad1a856fe5/sdk/python/lib/pulumi/resource.py#L400

The [`provider`](https://github.com/pulumi/pulumi-eks/blob/a4ee6f7a206c4588e0cb06fd24f740789d15bc24/python/pulumi_eks/cluster.py#L1509-L1515) property for `pulumi_eks` is of type `pulumi.Output[pulumi_kuberntes.Provider]`.

To get the example you provided working, we add an `apply`:
```python
from pulumi import ResourceOptions
from pulumi_eks import Cluster
from pulumi_kubernetes.core.v1 import Namespace

cluster = Cluster(resource_name="test")

namespace = cluster.provider.apply(
    lambda p: Namespace(resource_name="test", opts=ResourceOptions(provider=p))
)
```


I understand that this is not ideal. I will see if I can come up with a way to accept `pulumi.Output[pulumi.ProviderResource]`.

**Comment by justinvp** [comment]
The main problem is that the `ResourceOptions`' `provider` arg doesn't yet accept `Output[ProviderResource]`, which is tracked by https://github.com/pulumi/pulumi/issues/7012.

The workaround of creating the `Namespace` resource inside an `apply` would technically work, but it's not ideal, and creating resources inside an `apply` is not something we'd generally recommend, if possible.

A better workaround is to create a new instance of the `pulumi_kubernetes.Provider` and pass it the `Cluster`'s `kubeconfig`:

```python
import json

from pulumi import ResourceOptions
from pulumi_eks import Cluster
from pulumi_kubernetes import Provider
from pulumi_kubernetes.core.v1 import Namespace

cluster = Cluster("test")

provider = Provider("eks-k8s", kubeconfig=cluster.kubeconfig.apply(lambda k: json.dumps(k)))

namespace = Namespace("test", opts=ResourceOptions(provider=provider))
```

**Comment by calumabarnett** [comment]
Thanks @iwahbe @justinvp – both of those workarounds are OK for the repro example. In practice, I've tried to use a new Kubernetes provider to create cluster resources and have come up against another issue. This seems to be because cluster resources like `Namespace` have `parent=cluster` and this is interacting with providers. When we run `pulumi preview` it just hangs.

To reproduce:
1. With `pulumi==3.22.1` (before #8770) run `pulumi up` with the following program:
     ```python
    import pulumi
    import pulumi_eks as eks
    import pulumi_kubernetes as k8s
    
    cluster = eks.Cluster(resource_name="test")
    
    namespace = k8s.core.v1.Namespace(
        resource_name="test", opts=pulumi.ResourceOptions(provider=cluster.provider, parent=cluster)
    )
    ```
2. Upgrade to `pulumi==3.25.0`.
3. Implement the workaround and run `pulumi preview`:
    ```python
    import json
    
    import pulumi_eks as eks
    import pulumi_kubernetes as k8s
    import pulumi
    
    cluster = eks.Cluster(resource_name="test")
    
    provider = k8s.Provider(
        resource_name="test", kubeconfig=cluster.kubeconfig.apply(lambda k: json.dumps(k))
    )
    
    namespace = k8s.core.v1.Namespace(
        resource_name="test",
        opts=pulumi.ResourceOptions(provider=provider, parent=cluster),
    )
    ```

**Comment by PriyaBasker23** [comment]
> We have couple issues around providers
> 
> **Below code failed on unit test**
> 
> ```
>      provider = Provider(
>             resource_name="test-provider",
>             assume_role="arn:aws:iam::********:role/test-role",
>         )
>         test_pipeline = TestPipeline(
>             name="test",
>             provider=provider,
>         )
>     
> >       assert provider == test_pipeline._curatedBucket._providers["aws"]
> ```
> 
> Error - KeyError: 'aws' . If i specify the package name instead of 'aws' then the unit test passes. It would be good to know the change happened related to providers

@iwahbe - any lucky with the suggestion ? . I have raised two issues above

**Comment by iwahbe** [comment]
@PriyaBasker23 I'm assuming that `Provider` is `aws.Provider`. Is `TestPipeline` a component resource? If you pass `TestPipeline(name="test", providers=[provider])` does that still fail the unit test?

We did change how the `provider` and `providers` field reacted in https://github.com/pulumi/pulumi/pull/8770. If you call `Foo("name", provider=pkgProvider)`, we assume that the package of `Foo` is the same package as `pkgProvider`.
