### ISSUE TITLE
Use Pulumi.yaml template as schema to validate Pulumi.$stack.yaml

### ISSUE THREAD

**Issue by awoimbee** [pulumi/pulumi#9031]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The `template` key in `Pulumi.yaml` ([reference](https://www.pulumi.com/docs/reference/pulumi-yaml/)) is very useful to keep track of every possible configuration key and to document them.
The issue I face with this feature is that it's under utilized and the template can quickly become outdated if one forgets to update it. That's why I would like to see validation by the pulumi cli.

### Affected area/feature

The pulumi SDK (`new pulumi.Config()` would check the schema and warn or error according to user preference).

**Comment by Frassle** [comment]
I think this is now covered by config schema support.
