### ISSUE TITLE
[sdk/nodejs] clean up mockpackage

### ISSUE THREAD

**Issue by dixler** [pulumi/pulumi#9042]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Filing since mockpackage should be cleaned up, but issue #9019 `make install` could be fixed by #9026 without it.

### Affected area/feature
sdk/nodejs

**Comment by julienp** [comment]
Fixed by https://github.com/pulumi/pulumi/pull/15757
