### ISSUE TITLE
Pulumi fails with 'no resource plugin 'github-v4.1.0' found in the workspace or on your $PATH' when dependency package upgrades

### ISSUE THREAD

**Issue by piotr-bzdyl-vertexinc** [pulumi/pulumi#9061]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I have an existing Pulumi program in Python with the following setup:
Pulumi 3.24.1
requirements.txt
```
pulumi>=3.0.0,<4.0.0
pulumi-github>=4.0.0,<5.0.0
```

I have some Github resources in the state created with pulumi-github in 4.1.0 version. Now my CI environment downloaded newer version of pulumi-github (4.10.0), the CI workflow for pulumi preview fails.

CI environment setup steps:
```
python3 -m venv venv
venv/bin/pip install -r requirements.txt
```

Error:
```
error: no resource plugin 'github-v4.1.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource github v4.1.0`
```

I have to manually add the following step to the CI environment setup steps:
```
pulumi plugin install resource github v4.1.0
```

It makes the version ranges risky to use as the CI process might fail anytime a new dependency version is released. Maybe the list of required resource plugin versions to download automatically should be determined now only from the dependency package version but also from the existing resources in the state?

**Comment by mikhailshilkov** [comment]
@piotr-bzdyl-vertexinc apologies for a slow response. Which operation gives you this error?

**Comment by piotr-bzdyl-vertexinc** [comment]
Hi @mikhailshilkov. It was during `pulumi preview`.

**Comment by Frassle** [comment]
I suspect this is probably fixed by the work we've done so far on https://github.com/pulumi/pulumi/issues/12177.
