### ISSUE TITLE
Stack size issues with parented resources and aliases

### ISSUE THREAD

**Issue by DSTAlan** [pulumi/pulumi#9089]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When trying to update the names of rules and subscriptions for an existing Azure Native stack I am experiencing issues where the pulumi up is taking hours and the stack is growing to a huge size.  I have a stack json file (stored in Azure storage) that currently is 1.3 MB.  When I run a pulumi up this grows in size while Pulumi up is running.  The latest attempt grew from 1.3 MB to over 400MB in size.  When I look in the stack file I see a lot of lines similar to the following...

"urn:pulumi:<stack>::<project>::azure-native:resources/v20190701:ResourceGroup$azure-native:servicebus/v20150801:Namespace$azure-native:servicebus:Topic$azure-native:servicebus:Subscription$azure-native:servicebus/v20210101preview:Rule::<rulename>",
"urn:pulumi:<stack>::<project>::azure-native:resources/v20190701:ResourceGroup$azure-native:servicebus/v20150801:Namespace$azure-native:servicebus:Topic$azure-native:servicebus:Subscription$azure-native:servicebus/v20210601preview:Rule::<rulename>",
"urn:pulumi:<stack>::<project>::azure-native:resources/v20190701:ResourceGroup$azure-native:servicebus/v20150801:Namespace$azure-native:servicebus:Topic$azure-native:servicebus:Subscription$azure-native:servicebus/v20211101:Rule::<rulename>",
"urn:pulumi:<stack>::<project>::azure-native:resources/v20190701:ResourceGroup$azure-native:servicebus/v20150801:Namespace$azure-native:servicebus:Topic$azure-native:servicebus/v20140901:Subscription$azure-native:servicebus:Rule::<rulename>",
"urn:pulumi:<stack>::<project>::azure-native:resources/v20190701:ResourceGroup$azure-native:servicebus/v20150801:Namespace$azure-native:servicebus:Topic$azure-native:servicebus/v20140901:Subscription$azure-native:servicebus/v20170401:Rule::<rulename>",
"urn:pulumi:<stack>::<project>::azure-native:resources/v20190701:ResourceGroup$azure-native:servicebus/v20150801:Namespace$azure-native:servicebus:Topic$azure-native:servicebus/v20140901:Subscription$azure-native:servicebus/v20180101preview:Rule::<rulename>",
"urn:pulumi:<stack>::<project>::azure-native:resources/v20190701:ResourceGroup$azure-native:servicebus/v20150801:Namespace$azure-native:servicebus:Topic$azure-native:servicebus/v20140901:Subscription$azure-native:servicebus/v20210101preview:Rule::<rulename>",
"urn:pulumi:<stack>::<project>::azure-native:resources/v20190701:ResourceGroup$azure-native:servicebus/v20150801:Namespace$azure-native:servicebus:Topic$azure-native:servicebus/v20140901:Subscription$azure-native:servicebus/v20210601preview:Rule::<rulename>",

### Steps to reproduce
"pulumi up" against an existing stack that has been working fine until recently.
I am using Pulumi 3.25.0 with AzureNative 1.60.0

Expected: Pulumi up to succeed
Actual: Pulumi up running for more than 1 hour and I eventually terminated it.

**Comment by DSTAlan** [comment]
I set this off again and let it run to completion.  The changes it needed to make were to delete 4 items (2 topic subscriptions each with a single rule) and create 4 new items (two different subscriptions, each with a single rule).  The pulumi up took 3 hours and 35 minutes to run and the stack file climbed from 1.3 MB to 471.7 MB.

**Comment by DSTAlan** [comment]
After a bit more digging, the issue seems to be with the aliases sections for each item in the stack.  As an example, a Service Bus Rule that had 44 aliases before the last pulumi up command now has 60 000 aliases!

**Comment by mikhailshilkov** [comment]
@DSTAlan thank you for reporting this. Do you have a small-ish program that I could run to reproduce this behavior?

**Comment by DSTAlan** [comment]
Hi @mikhailshilkov. We use a lot of wrapper files around Pulumi to simplify mapping YAML config files to Pulumi modules so I don't have anything simple to share.  I can share sections from log files though and am happy to have a screen sharing session with someone to show what I am seeing.

What seems to be happening is that a single alias in the stack like the following

"urn:pulumi:<stackname>::azure-native:resources:ResourceGroup$azure-native:servicebus:Namespace$azure-native:servicebus/v20140901:Topic$azure-native:servicebus:Subscription::<subscriptionname>",

is being joined by a load of versioned variants such as

"urn:pulumi:<stackname>::azure-native:resources:ResourceGroup$azure-native:servicebus:Namespace$azure-native:servicebus/v20140901:Topic$azure-native:servicebus/v20140901:Subscription::<subscriptionname>",
"urn:pulumi:<stackname>::azure-native:resources:ResourceGroup$azure-native:servicebus:Namespace$azure-native:servicebus/v20140901:Topic$azure-native:servicebus/v20150801:Subscription::<subscriptionname>",
"urn:pulumi:<stackname>::azure-native:resources:ResourceGroup$azure-native:servicebus:Namespace$azure-native:servicebus/v20140901:Topic$azure-native:servicebus/v20170401:Subscription::<subscriptionname>",
"urn:pulumi:<stackname>::azure-native:resources:ResourceGroup$azure-native:servicebus:Namespace$azure-native:servicebus/v20140901:Topic$azure-native:servicebus/v20180101preview:Subscription::<subscriptionname>",
"urn:pulumi:<stackname>::azure-native:resources:ResourceGroup$azure-native:servicebus:Namespace$azure-native:servicebus/v20140901:Topic$azure-native:servicebus/v20210101preview:Subscription::<subscriptionname>",
"urn:pulumi:<stackname>::azure-native:resources:ResourceGroup$azure-native:servicebus:Namespace$azure-native:servicebus/v20140901:Topic$azure-native:servicebus/v20210601preview:Subscription::<subscriptionname>",
"urn:pulumi:<stackname>::azure-native:resources:ResourceGroup$azure-native:servicebus:Namespace$azure-native:servicebus/v20140901:Topic$azure-native:servicebus/v20211101:Subscription::<subscriptionname>",

The above shows what is happening for a topic subscription, this is more pronounced for a topic subscription rule.  

I will also see if I can put a simple program together that doesn't use our wrappers that exhibits the same behaviour.

**Comment by DSTAlan** [comment]
@mikhailshilkov I have sent an email to your GitHub listed email address containing a simple program that demonstrates the issue.

**Comment by DSTAlan** [comment]
Hi @mikhailshilkov, did you get the example that I sent through OK?
Cheers
Alan

**Comment by mikhailshilkov** [comment]
@DSTAlan Yes I did, thank you. I've just returned from PTO - will take a look shortly.

**Comment by mikhailshilkov** [comment]
@DSTAlan Yes, I was able to repro it, now trying to figure out the culprit. 

> How can I get the Pulumi deployment to (temporarily) stop managing the Service Bus without it trying to delete the Service Bus when next I run "pulumi up"?

`pulumi stack delete` should help.

**Comment by mikhailshilkov** [comment]
@DSTAlan Another thing I noticed is that if I don't set the `Parent` option, my state is normal again. Could this be a workaround for you?

**Comment by mikhailshilkov** [comment]
The broad picture is the following. Let's say we have

- resource type A with aliases A1, A2, A3,
- resource type B with aliases B1, B2, B3
- resource type C with aliases C1, C2, C3

Now, the following Pulumi program (in pseudolanguage):

```
a = new A(...);
b = new B(..., {parent: a});
c = new C(....,{parent:b}); 
```

will cause an exponential growth of aliases in the state file, because

- a has aliases for types A1, A2, A3 (3)
- b has aliases for all types A1:a/B1, A2:a/B1, A3:a/B1, A1:a/B2, A2:a/B2, A3:a/B2, A1:a/B3, A2:a/B3, A3:a/B3 (9)
- c has aliases for all type Ax:a/Bx:b/Cx (27)

The repro has the following resource structure:

```
 +   └─ azure-native:resources:ResourceGroup           PulumiSBusTest-rg                 created     
 +      └─ azure-native:servicebus:Namespace           PulumiSBusTest-sbus               created     
 +         └─ azure-native:servicebus:Topic            PulumiSBusTest-Topic1             created     
 +            └─ azure-native:servicebus:Subscription  PulumiSBusTest-Topic1-Sub1        created     
 +               └─ azure-native:servicebus:Rule       PulumiSBusTest-Topic1-Sub1_Rule1  created
```

which give 58k aliases to the `Rule` resource.

**Comment by DSTAlan** [comment]
Thanks for the response @mikhailshilkov.  That matches exactly what I am seeing, 58K aliases for a rule which will presumably jump every time a new version is added by Microsoft.  Historically I never had this issue so I am wondering what has changed to balloon this out so much in the last couple of months?

I will give the parent option a shot and see if that fixes things for me.

**Comment by mikhailshilkov** [comment]
> Historically I never had this issue so I am wondering what has changed to balloon this out so much in the last couple of months?

Thank you for this. I tried it with multiple versions and figured that it works fine for versions 1.52.0 and before, but starts going crazy with 1.53.0 of azure-native. Which is very puzzling, as 1.53.0 doesn't seem to have any relevant changes...

**Comment by DSTAlan** [comment]
@mikhailshilkov.  I have tried the parent option and the file did shrink right down which is great.  The problem I have is that I couldn't work out how to change the parent without deleting the resources and recreating them which would be problematic with the live bus.  Is there a way to do this?

**Comment by mikhailshilkov** [comment]
> The problem I have is that I couldn't work out how to change the parent without deleting the resources and recreating them which would be problematic with the live bus. Is there a way to do this?

You could use aliases for this, see https://www.pulumi.com/blog/cumundi-guest-post/

**Comment by mikhailshilkov** [comment]
So, this is "by design" done in https://github.com/pulumi/pulumi/pull/8627. We'll have to see if we have ways to limit the impact though.

**Comment by DSTAlan** [comment]
I might try rolling back to 3.20.0 then as a temporary solution.

**Comment by mikhailshilkov** [comment]
That won't help - it's the provider that causes trouble. 1.52.0 is the last version without this issue.

**Comment by DSTAlan** [comment]
Just FYI, I've used aliasing to re-parent everything as you suggested.  I've re-parented on to the service bus rather than the stack or resource group so the file hasn't shrunk as much as possible but it is a lot better.  The file has shrunk from 470mb to 14mb and deployment for a rule add has dropped rom 3.5 hours to 45 seconds. So thanks for the tips.  Hopefully there will be a solution soon that doesn't require reparenting everything, pehaps a flag to disable alias cascading or similar.

Thanks again!
