### ISSUE TITLE
On engine panic, print out message suggesting to rerun command with `--debug` flag

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#909]
Since it will be hard to fix all engine panic error messages before first launch, suggest doing the following:
- When there is an engine panic, print out a message in a different color
- Message reads: `Sorry, you've run into a P bug! Please run the command again with --debug and post the command line and output to https://github.com/P/P/issues/new`
- P is a placeholder.

**Comment by mikhailshilkov** [comment]
I'm slowly going through older issues... This one has been open for 4 years without any action and I don't feel like we want to do exactly what it describes. Let's track with other items in #4603.
