### ISSUE TITLE
Exception: invoke of azure-native:authorization:getClientConfig failed

### ISSUE THREAD

**Issue by VNGSNZ** [pulumi/pulumi#9108]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When running pulumi up i receive the following error:

Exception: invoke of azure-native:authorization:getClientConfig failed: invocation of azure-native:authorization:getClientConfig returned an error: getting authenticated object ID: Error parsing json result from the Azure CLI: Error retrieving running Azure CLI: WARNING: The underlying Active Directory Graph API will be replaced by Microsoft Graph API in a future version of Azure CLI. Please carefully review all breaking changes introduced during this migration: https://docs.microsoft.com/cli/azure/microsoft-graph-migration

### Steps to reproduce

1. Run pulumi up command for a existing project.
2. AWS CLI version -> 2.34.1
3. Pulumi version -> 3.25.1

Expected: Deployment of a existing (known working) automation project.
Actual: Receive error above.

**Comment by DSTAlan** [comment]
Hi @VNGSNZ , I am seeing this issue, is there a fix/workaround?

**Comment by aureq** [comment]
@DSTAlan Have you tried to upgrade to the latest Pulumi version ?

**Comment by Mejato** [comment]
@DSTAlan see - (https://github.com/pulumi/pulumi-azure-native/discussions/1565)
