### ISSUE TITLE
Python dynamic provider with boto3: Other threads are currently calling into gRPC, skipping fork() handlers

### ISSUE THREAD

**Issue by austinbyers** [pulumi/pulumi#9110]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We use Python dynamic providers that rely on `boto3`, the AWS SDK, to perform various operations. `pulumi up` works as expected, but always with a diagnostic error message:

```
Diagnostics:
  pulumi:pulumi:Stack (austin-pulumi-bug-repro-repro):
    E0303 15:09:18.160991000 123145385041920 fork_posix.cc:76]             Other threads are currently calling into gRPC, skipping fork() handlers
```

### Steps to reproduce

```python
from typing import Any, Optional

import boto3
import pulumi_aws as aws
from pulumi import ResourceOptions
from pulumi.dynamic import CreateResult, Resource, ResourceProvider


class MyProvider(ResourceProvider):
    def create(self, props: Any) -> CreateResult:
        account_id = boto3.client('sts').get_caller_identity()['Account']
        return CreateResult(id_=account_id, outs=props)


class MyCustomResource(Resource):
    def __init__(self, name: str, opts: Optional[ResourceOptions] = None):
        super().__init__(MyProvider(), name, {}, opts)


if __name__ == '__main__':
    aws.s3.Bucket('empty', aws.s3.BucketArgs(force_destroy=True))
    MyCustomResource('custom')
```

<img width="237" alt="Screen Shot 2022-03-03 at 3 34 42 PM" src="https://user-images.githubusercontent.com/3608925/156671001-3e561ba8-5fd8-4e5c-9029-38feb509db71.png">

1. `pulumi init` a stack
2. `pulumi up` with the source code above

Expected: Success with no diagnostic error message
Actual: `fork_posix` error msg

#### Versions

* `pulumi` CLI: v3.25.1
* Pip Libraries
    * `boto3`: 1.18.55
    * `pulumi`: 3.25.0
    * `pulumi_aws`: 4.38.0 

----

I've seen similar behavior if I put `boto3` in the `delete()` method and then call `pulumi destroy`

**Comment by Frassle** [comment]
This is logging that was coming from grpc. It is [apparently fixed since 1.48.1](https://github.com/grpc/grpc/pull/29992#issuecomment-1236569221) and we're currently running 1.51.3. I'm going to assume this is fixed.
