### ISSUE TITLE
Typescript error for pulumi.interpolate within aws.iam.getPolicyDocument

### ISSUE THREAD

**Issue by elanw** [pulumi/pulumi#9114]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When using`pulumi.interpolate` in  `aws.iam.getPolicyDocument`, I get a typescript error that `Type output is not assignable to type string`. This prevents pulumi up from running successfully due to a TS compilation error. Marking the offending line with `// @ts-ignore` resolves the issue and allows for successful creation of the resource.

### Steps to reproduce
1. create an iam role: 
  `const codeBuildServiceRole = new aws.iam.Role(...)`

2. create an iam policy via `aws.iam.getPolicyDocument` that uses the arn output of the step 1 resource as an principal aws resource :
```
const s3BucketKmsKeyPolicy = aws.iam.getPolicyDocument({
  ...
  principals: [{
          type: "AWS",
          identifiers: [
            pulumi.interpolate`${codeBuildServiceRole.arn}`,
          ],
        }],

  ...
```

Expected: no typescript error
Actual: Get the following ts error: `Type output is not assignable to type string`

**Comment by mikhailshilkov** [comment]
@elanw This is expected. The original implementation of functions didn't allow passing outputs into input values. Please try using `getPolicyDocumentOutput` instead of `getPolicyDocument` which should accept output values.
