### ISSUE TITLE
Support self-signed certs for `pulumi login`

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi#9120]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When deploying a self-hosted Pulumi Service for testing, I may want to just use a self-signed cert.
But, `pulumi login https://MY_API_ENDPOINT` does not work.
It throws: 
```
error: problem logging in: getting user info from https://api.mitch.pulumi-ce.team: performing HTTP request: Get "https://api.mitch.pulumi-ce.team/api/user": x509: certificate signed by unknown authority
```

**Comment by Frassle** [comment]
Figured this would be a good test case for https://github.com/pulumi/pulumi/issues/4665.

Considering adding something like the below to Pulumi.yaml.
```
name: ssl_test
runtime: nodejs
backend:
  url: https://localhost:8080
  config:
    service:disable-tls: true
```

Of course that would depend on you having a project file in your working directory. I wonder if we need some other way of passing config that lives above projects for setting backend settings?

**Comment by lukehoban** [comment]
I'm not sure we want to put this in the project file.  This is configuration about the backend itself - which we generally want to set machine-scoped.  To the extent we want to support backend configuration explicitly, I think we actually want to support it at the stack level, vs. the project level (since it's really stacks that live in backends, not projects).

I'd be inclined to support this as a flag to `pulumi login`, and to then serialize this into the `~/.pulumi/credentials.json` metadata associated with the backend for use in other backend operations.

**Comment by Frassle** [comment]
> This is configuration about the backend itself - which we generally want to set machine-scoped.

Project files already have a backend.URL configuration. Is the problems that's trying to solve also solved by making backends machine-wide? Or is this just that configuring a given backend URL is machine-wide but then it makes sense for individual projects to opt-in to which configured backend they use?

> I think we actually want to support it at the stack level

We'd have to load stack.json files before building a backend to parse the stack reference in that case. Which I think we could hack around today, but given issues like https://github.com/pulumi/pulumi/issues/2005#issuecomment-431913734 we'd have to be able to tell if "foo/bar" is intended to be owner "foo" or project "foo" and that varies based on if the backend supports organisations or not.

**Comment by lukehoban** [comment]
> Is the problems that's trying to solve also solved by making backends machine-wide?

The primary way that backend is configured today is via system wide value that is set via a `pulumi login` and stored in `~/.pulumi/credentials.json`.  I believe we should focus on addressing this first and foremost as part of this standard workflow.  The vast majority of usage of backends is not configured in the project or stack, but is just configured via `pulumi login` once on a machine, and then every other operation on that machine uses the logged in backend.

> Project files already have a backend.URL configuration. 

Yeah - I think this was sort of a mistake to introduce (or at least, we hadn't fully thought through how backends should be configured at the project and stack level - and doing this only at the project level is a bit of an impedance mismatch with how these things are actually managed - which is that a stack actually lives in a backend).  We should propose a holistic design around how backend is managed at the project and stack levels as part of overall backend improvement.

It's a fair point though that we already support `backend` in the project file, so in principle, any configuration we add to `pulumi login` we should also add to that and any other places you can configure the backend (for example, we also support an env var - `PULUMI_BACKEND_URL ` - that sets the backend, and likely need to support a way for that approach to also opt-in to disabling TLS).

**Comment by Frassle** [comment]
Had a quick look at what it takes to pass an extra option through `login` in https://github.com/pulumi/pulumi/pull/9159. Doesn't try to take config from the project file or envvars currently but would be possible to add.

**Comment by phillipedwards** [comment]
This issue just popped up again, when can we expect to have the reference PR pulled in? @Frassle
