### ISSUE TITLE
Databricks provider

### ISSUE THREAD

**Issue by marcindulak** [pulumi/pulumi#9123]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

https://github.com/databrickslabs/terraform-provider-databricks.

There were attempts to create a databricks provider before: https://github.com/XBeg9/pulumi-databricks or https://github.com/ingenii-solutions/pulumi-databricks

**Comment by 2fifty6** [comment]
This would be fantastic!

**Comment by stack72** [comment]
Hey all! Happy to say that we now have an official provider for Databricks :) I can close this out!

https://github.com/pulumi/pulumi-databricks
https://www.npmjs.com/package/@pulumi/databricks
https://www.nuget.org/packages/Pulumi.Databricks
https://pypi.org/project/pulumi-databricks/
