### ISSUE TITLE
message error when folks use --stack without fully qualified name

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#9131]
## overview
in https://github.com/pulumi/pulumi/pull/9051 i removed the `If you're using the --stack flag, make sure to pass the fully qualified name (org/project/stack)` error message as folks either rarely hit that or never hit that in that situation. we should detect when folks are using that flag and not using a fully qualified name and display this error message then.

there's a bit more convo on #9051 about this.

**Comment by Frassle** [comment]
I commented elsewhere but I think `httpstate.Backend.ParseStackReference` might be the right place to add this message.

**Comment by mikhailshilkov** [comment]
@Zaid-Ajaj sounds like a good issue to take a look at, adding to the upcoming iteration
