### ISSUE TITLE
Pulumi Python: Fork support is only compatible with the epoll1 and poll polling strategies

### ISSUE THREAD

**Issue by austinbyers** [pulumi/pulumi#9133]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We recently started seeing a bunch of errors in our automated Pulumi builds:

> pulumi:pulumi:Stack .... running E0302 17:31:21.432724807     195 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies

The builds are still ultimately successful, but the error message is noisy and concerning. #9110 is almost certainly related if not the same root cause.

We first detected the bug in **v3.25.0** of the pulumi pip library and **v1.44.0** of the `grpcio` library

### Steps to reproduce
Our Dockerfile, running in AWS CodeBuild:

```Dockerfile
FROM pulumi/pulumi-python:latest

LABEL description="The image used by CodeBuild to execute pulumi, republish of pulumi:pulumi-python."

VOLUME /var/lib/docker

RUN python3 -m venv venv && venv/bin/pip3 install boto3 pulumi pulumi-aws

ENTRYPOINT ["pulumi"]
```

Build a Python Pulumi program that deploys a Lambda function and IAM role.

With these pip versions, the build is successful with no error msg:

> Successfully installed arpeggio-1.10.2 attrs-21.4.0 dill-0.3.4 grpcio-1.43.0 parver-0.3.1 protobuf-3.19.4 pulumi-3.24.1 pulumi-aws-4.36.0 pyyaml-6.0 semver-2.13.0 six-1.16.0

With these pip versions, the build is successful with lots of `fork_posix` error messages:

> Successfully installed arpeggio-1.10.2 attrs-21.4.0 dill-0.3.4 grpcio-1.44.0 parver-0.3.1 protobuf-3.19.4 pulumi-3.25.0 pulumi-aws-4.36.0 pyyaml-6.0 semver-2.13.0 six-1.16.0

**Comment by jaxxstorm** [comment]
I've opened https://github.com/grpc/grpc/issues/29044 to see what the upstream maintainers have to say

**Comment by zivyatziv** [comment]
Hey there, there seems to be an issue with newer versions of grpcio.
You can run:
```
pip install grpcio<=1.43.0
```
Or simply add `grpcio<=1.43.0` to your `requirements.txt`.

**Comment by Frassle** [comment]
Looks like this is getting fixed in grpcio https://github.com/grpc/grpc/pull/29103

**Comment by rminev** [comment]
I am seeing this message if I don't gracefully close an opened grpc channel though `channel.close()`.
Also I see it even when I call `channel.close()` but the remote grpc server is not reachable or not running any longer.

So in normal cases, this should be the fix.
```
channel = grpc.insecure_channel(f'{ipaddr}:{self.port}')
<do your calls>
channel.close()
```

**Comment by RobbieMcKinstry** [comment]
The upstream PR was merged in March. We use a version of `grpc` (v1.50) in the Python SDK from October. As such, I think we can close this PR now as fixed. Let me know if I'm wrong, and we can reopen 👍🏻
