### ISSUE TITLE
[diffs] Pretty-print JSON diffs

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi#9135]
During a preview or an update, the Pulumi CLI should pretty-print diffs for properties that accept JSON data. This would aid in the readability of diffs between large JSON documents (e.g. IAM policies, network firewall rules, etc.).

**Comment by lukehoban** [comment]
I believe this is also tracked in https://github.com/pulumi/pulumi/issues/5831?

**Comment by pgavlin** [comment]
Hah, I think you're right. I had searched for "preview json" and that didn't come up.
