### ISSUE TITLE
Update console output for `pulumi stack rm`

### ISSUE THREAD

**Issue by caseyyh** [pulumi/pulumi#9166]
Stack deletion does not actually delete resources and requires the user to execute a `pulumi destroy` first.

However, attempting to delete a stack with resources still attached to it yields this message:

```
casey@caseys-mbp aws-go % pulumi stack rm tearmedown                  
This will permanently remove the 'tearmedown' stack!
Please confirm that this is what you'd like to do by typing ("tearmedown"): tearmedown
error: 'tearmedown' still has resources; removal rejected; pass --force to override
```

Which reads to me (as a person who tries first and regrets later), meant that I should force delete the stack... before I realized the sins of my ways. Suggestion to update wording to encourage user to run `destroy` before suggesting a `--force` flag, which would orphan those resources.

**Comment by Frassle** [comment]
```
error: 'tearmedown' still has resources; removal rejected; pass --force to override and ignore existing resources
```
?

**Comment by caseyyh** [comment]
It would also be great to maybe include verbage like `Use pulumi destroy to tear down resources first` or something!

**Comment by Frassle** [comment]
```
error: 'tearmedown' still has resources; removal rejected; pass --force to override and ignore existing resources. Use `pulumi destroy` to delete resources first.`
```

@susanev any thoughts? Probably want to keep in mind that this error message is going to have to cover https://github.com/pulumi/pulumi/issues/9172 at some point as well.

**Comment by susanev** [comment]
i can take a look on monday!
