### ISSUE TITLE
Error message is shown during the first command when main and virtualenv is set in Pulumi.yaml

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi#9175]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
When `main` and `virtualenv` is set in Pulumi.yaml then during the first command virtualenv is created and the following message is shown.

`Failed to resolve python version command: fork/exec <path to the project>/venv/bin/python: no such file or directory`

### Steps to reproduce

Given structure:

```
Pulumi.yaml
src/__main__.py
src/requirements.txt
```

Pulumi.yaml

```yaml
name: experiment
backend:
  url: file://.
main: src
runtime:
  name: python
  options:
    virtualenv: venv
```

requirements.txt
```
pulumi==3.26.1
```

When pulumi command is run for the first time (for example pulumi preview), the error message is shown.
```shell
pulumi preview
```

Consequent runs are ok.

Expected: No error message
Actual: 
```
Previewing update (test):
     Type                 Name             Plan     Info
     pulumi:pulumi:Stack  experiment-test           1 message

Diagnostics:
  pulumi:pulumi:Stack (experiment-test):
    Failed to resolve python version command: fork/exec <path to the project>/venv/bin/python: no such file or directory
```

**Comment by marcelloromani** [comment]
Thank you for reporting this issue.

I am experiencing the exact same issue when running Pulumi on GitHub actions.

The error message I get is:

```
  Diagnostics:
    pulumi:pulumi:Stack (hello-ec2-dev):
      Failed to resolve python version command: fork/exec /opt/actions-runner/_work/pulumi-demo/pulumi-demo/hello-ec2/venv/bin/python: no such file or directory
```

Since the GitHub runners are ephemeral (or should be), if it doesn't work on first run, it doesn't work at all.

**Comment by marcelloromani** [comment]
After removing these lines:
```
-  options:
-    virtualenv: venv
```
from Pulumi.yaml the job worked fine in GitHub actions.

**Comment by dixler** [comment]
When I run pulumi with `runtime.venv` specified, but no `venv` directory, it sends a diagnostic message saying:
> Failed to resolve python version command: fork/exec /home/kdixler/go/src/github.com/pulumi/pulumi/tests/integration/python/venv/venv/bin/python: no such file or directory

It appears to continue running, either way.

It seems that we have a check to determine if python in the venv is a valid version, but if the venv hasn't been created, the check prints that message(but continues).

Does this match everyone's experience? @jancespivo @marcelloromani
