### ISSUE TITLE
Allow whoami to show orgs available

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#9181]
Pulumi whoami will show how you've logged in as. It'd be great to show what orgs you actually have access to.

```
pulumi whoami --orgs

{"user": "jaxxstorm", "orgs": ["pulumi", "demo"]}
```

**Comment by Frassle** [comment]
I'm not sure the service returns us this information? `/api/user` just returns the username.
@pulumi/service is there an endpoint we can hit to get this data?

**Comment by EvanBoyle** [comment]
`/user` returns a full user including a list of org summaries:

https://github.com/pulumi/pulumi-service/blob/2a639a4444d3b6234cf704c307544813c849f42a/pkg/apitype/users.go#L20-L34

https://github.com/pulumi/pulumi-service/blob/b0608554fe29d14d95c96113c0f5243dffea6fd6/cmd/service/routing_api.go#L224

I believe that the `pulumi whoami` command does not call this endpoint, and instead reads this info based on some cached metadata: 

https://github.com/pulumi/pulumi/blob/6a8f7be1d548d7b3c02fadecc238933722fb0110/pkg/backend/httpstate/backend.go#L408

**Comment by Frassle** [comment]
Ah ok we do call that but looks like we only pull GithubUser off the response, I'll test if we can pull of the other entries and feed them back.
