### ISSUE TITLE
Pulumi not respecting engines property and npmrc file

### ISSUE THREAD

**Issue by antstanley** [pulumi/pulumi#9201]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Pulumi doesn't appear to respect the `engines` setting in `package.json` or the `engine-strict` config option in `.npmrc`

I've built a Custom Resource in Pulumi with a pre-deploy step that copies files from one location to another before creating a function. It uses the `fs.cpSync` method, which was only introduced to node in  version `16.7`. 

I need to ensure that Pulumi fails if the wrong version of Node is being used. I've set the correct `engines` property in `package.json` and set `engine-strict=true` in my `.npmrc` file.

### Steps to reproduce

Repo to reproduce - [](https://github.com/antstanley/pulumi-repro)

1. Specify minimum Node version on a Pulumi project

add below to `package.json`

```json
    "engines": {
        "node": ">=16.7.0"
    }
```

add below a `.npmrc` file

```sh
engine-strict=true
```

2. Change Node version to earlier version

If you have `nvm` configured run the command below to set your project to use node v14

```sh
nvm use 14
```

3. Run `pulumi up` or `pulumi preview` to run your project

Expected: Would hope to get an error like below, that I get when running `jest` or `ts-node` on the code base

```sh

Your Node version is incompatible with "/code/pulumi-repro".

Expected version: >=16.7.0
Got: v14.19.0

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.

```

Actual: Pulumi runs as per normal, even though wrong engine is specified

In my specific use case, because I'm using a newer feature of node (`fs.cpSync`) I get an error saying `fs.cpSync is not a function`, that is being generated by a Custom Component I've created used by other teams who might not be fully aware they need the latest LTS version of node.

**Comment by Zaid-Ajaj** [comment]
Hi @antstanley thanks a lot for filing the issue. Indeed, pulumi should take node project config into account. I will see what I can do about and will keep you posted 😄

**Comment by Zaid-Ajaj** [comment]
Hi @antstanley, the fix has been merged and will be available in the upcoming version of pulumi (tomorrow if everything goes to plan :rocket:)

**Comment by antstanley** [comment]
Thank you for picking this up! Will test it in the morning!
