### ISSUE TITLE
Ensure builds respect split-DNS configurations on MacOS

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#9224]
See:
- https://github.com/golang/go/issues/12524

And this helpful comment: https://github.com/golang/go/issues/12524#issuecomment-1006174901

We may want to build our MacOS binaries on Intel (x86-64) and then cross-compile with a flag (CGO_ENABLED=1) to ensure that DNS resolution uses the host/libc DNS. 

For our other platforms, building natively or cross-compiling from Linux with CGO_ENABLED=0 should provide full coverage of our supported platforms.

**Comment by guineveresaenger** [comment]
related user issue: https://github.com/pulumi/pulumi-aws/issues/2185

**Comment by AaronFriel** [comment]
I've since changed my mind on this. This issue should be closed because we _do_ do this for Pulumi/Pulumi CLI builds, but I am certain this is a mistake for us to apply everywhere and I would very much like to not require it here.

1. While GitHub makes macOS CI relatively easy, not every CI tool does. Even if we solve this for ourselves, we will leave our third party providers with **fundamentally broken macOS binaries**.
2. The [limited number of macOS runners](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits) can cause a small # of updates to providers to result in an organization-wide CI outage.
3. As a Go project team member wrote, **[cgo is not go](https://dave.cheney.net/2016/01/18/cgo-is-not-go)**, and can greatly complicate our support for providers.

If we want to greatly expand our third party ecosystem, I think we need to press the Go team to take up https://github.com/golang/go/issues/12524, and resolve to fix up https://github.com/golang/go/pull/30686.

**Comment by abhinav** [comment]
Update: per discussion with @AaronFriel, Go 1.20 helps this.

https://github.com/pulumi/pulumi/pull/12051 attempts to switch to ubuntu-latest build machines for macOS builds. That has a green "bors try".

**Comment by AaronFriel** [comment]
This should be closable now, I checked that the latest draft release is built on 1.20. I don't see any indication the upstream CL on Go was reverted.

**Comment by justinvp** [comment]
I believe this is now fixed.
