### ISSUE TITLE
detect when an _empty_ update is being run

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#9229]
## overview
can we detect when someone is running an update with nothing being deployed beyond the stack itself and warn the user about this?

folks may hit this when they forget to save the file.

more than likely, folks don't mean to do this, but a lot of new users may do this by accident; if we can message them ahead of time, it may help them better understand what is happening and adjust ahead of running the update

**Comment by Frassle** [comment]
I don't think we can do it ahead of time, we need to run the program to see what it does. But we could warn at the end of up that nothing but a stack was deployed and that's probably a mistake. Would we also want to warn if a user runs an up that causes all resources but the stack to be deleted?

**Comment by mikhailshilkov** [comment]
They would see an empty preview in this case, right? Or what is the scenario that we are talking about here?

**Comment by susanev** [comment]
@mikhailshilkov yes, but if this is there very first time seeing a preview they may not know how to read it, or skip over it. the idea is, can we message them that this was probably not attended in clear language, along with some suggestions for what they should do next, e.g., save. happy to work with someone to figure out the details of how we want to solve the issue.

**Comment by dixler** [comment]
After getting clarification from @susanev we want to ensure that updates with no changes trigger the no changes warning.

**Comment by cnunciato** [comment]
> After getting clarification from @susanev we want to ensure that updates with no changes trigger the no changes warning.

Would this only appear for empty stacks, or also for stacks containing resources that just aren't being updated? If the latter, I'd push back on this, as it's super common to run updates that don't actually change anything (and indeed this is often exactly what you want to see).

**Comment by susanev** [comment]
to be clear, this is an info message and not an error.

the original intent came out of a usability study in which the user had not saved their file and was totally confused that nothing got created. the idea was to give them a lil message so folks could double check that's what they intended.

if folks don't support this, im not going to push hard on it. if folks want the link to the usability study pls let me know.

**Comment by cnunciato** [comment]
@susanev Ok thanks. Yeah, maybe a link to the interview that led to this issue would help. Adding few more info-level words to the output of an update of a stack with no resources definitely couldn't hurt. (And indeed I've hit this myself.) It's the second case (stack with resources, none being updated) that I'd consider more "by design", so probably not something we want to call out as "unusual".
