### ISSUE TITLE
Error: Resource parent is not a valid Resource

### ISSUE THREAD

**Issue by sunilvijaychordia** [pulumi/pulumi#9233]
Using Pulumi:

I am trying to add secrets to my key vault (a clientId, client secret, and tenantId) to mount my Databricks app to my storage account. The app registration for Databricks is done in "Databricks.ts". I am passing this Databricks app object to the "Keyvault.ts" to add the secret to key vault. Here's the code that is adding the secret. The error I get is as below. How do I convert the string to "resource" type, which is what the "parent" property requires? 

```
 const clientid = new azureNative.keyvault.Secret(`${secretName}-clientid`, {
            resourceGroupName: this.rgName,
            secretName: `${secretName}-clientid`,
            vaultName: keyVault.name,
            properties: {
                value: this.databricksSP.application.applicationId
            },
            tags: ApplicationTags
        },{
            parent: this.databricksSP.application,
            dependsOn : [keyVault]
        });
````

 ## Error: Resource parent is not a valid Resource: Calling [toString] on an [Output<T>] is not supported.

**Comment by mikhailshilkov** [comment]
What are you trying to achieve by setting a parent here? The `parent` option allows you to build a hierachy of resources in terms of Pulumi state and console, e.g. you would see one resource under the other in the preview. For that to work, you need to pass an actual resource to the option value (e.g. `keyVault` to make the vault be the parent of the secret).

Or do you want something else?
