### ISSUE TITLE
update access token to user token in the cli

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#9242]
we will soon be renaming access token to user token so we will need to update uses of it in the cli. we will be doing the service changes in https://github.com/pulumi/pulumi-service/issues/8389 and the docs changes in https://github.com/pulumi/pulumi-hugo/issues/1224.

**Comment by lukehoban** [comment]
> we will soon be renaming access token to user token so

Hmm - I'm not sure that's a good change.  These are access tokens.  Let me take a look at the decisions we made leading to this before we make disruptive name changes here.
