### ISSUE TITLE
Export from Pulumi service and import to S3

### ISSUE THREAD

**Issue by jmcrthrs** [pulumi/pulumi#9252]
Is it possible to follow this guide and export from Pulumi Service to S3?

https://www.pulumi.com/docs/intro/concepts/state/#migrating-between-backends

I have exported my stack from Pulumi Service to a file:

```
pulumi stack export --show-secrets --file my-app-dev.checkpoint.json
````

and then logged in to S3 and attempted to import it:

```
pulumi stack import --file my-app-dev.checkpoint.json 
error: could not deserialize deployment: constructing secrets manager of type "service": could not find access token for https://api.pulumi.com, have you logged in?
```

I think it is referring to this section of my json:
```
"secrets_providers": {
            "type": "service",
            "state": {
                "url": "https://api.pulumi.com",
                "owner": "xxx",
                "project": "xx",
                "stack": "dev"
            }
        },
```

I don't have any secrets in my project. Is it safe to remove the `secrets_providers` property?

**Comment by Frassle** [comment]
Before you export you can change the secret provider to the passphrase based secret provider (or any of the other non-pulumi-service options) with `pulumi stack change-secrets-provider passphrase`.

**Comment by Frassle** [comment]
There isn't any supported way to do that. You can just remove "secrets_provider" but I think it will cause the engine to panic if you add something that is a secret.

**Comment by lukehoban** [comment]
>  Is is possible to remove the password requirement completely?

Not currently. You need some secrets provider.  But the scenario originally discussed here should work, so closing this out.
