### ISSUE TITLE
SDK can use more recent protobuffer properties than the engine understands

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi#9255]
## Issue details

We are creating AKS cluster with system agent pool, per your recommedation we added `ignoreChanges` to the AKS's `agentPoolProfiles` and added a new state for importing the system pool as a different resources.

Creation and updates are working well but if we want to destroy the stack we encounter this error:
```
-  azure-native:containerservice/v20210501:AgentPool control1 deleting
 -  azure-native:containerservice/v20210501:AgentPool control1 deleting error: Code="OperationNotAllowed" Message="There has to be at least one agent pool."
 -  azure-native:containerservice/v20210501:AgentPool control1 **deleting failed** error: Code="OperationNotAllowed" Message="There has to be at least one agent pool."
 ```

I tried adding `pulumi.RetainOnDelete` to the control1 agent pool but it doesn't seem to work and we still get the same error
I'm using these providers and SDK:
```
github.com/pulumi/pulumi-azure-native/sdk v1.59.0
github.com/pulumi/pulumi/sdk/v3 v3.26.1
```

CLI is in the same version as the SDK

@viveklak

**Comment by Frassle** [comment]
So given the two way compatibility we need to support (users can upgrade just the engine, or just the sdk, or both) we can't have strict checks here. There's already a system for the SDK to ask the engine what features it supports (`SupportsFeature` requests) which we should have used to gate the use of retainOnDelete.

I don't think there's any other checks we can add here, there's no simple versioning scheme that fits.
