### ISSUE TITLE
[dotnet] Custom data type in Output

### ISSUE THREAD

**Issue by jbrezina** [pulumi/pulumi#9259]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
I'm trying to output dictionary of custom data type but I'm getting an error.
The Output property and the custom data type are defined as follows
```csharp
[Output] public Output<ImmutableDictionary<string, MyData>> Outputs { get; set; }

[OutputType]
public sealed class MyData
{
	public readonly string Data1;
	public readonly string Data2;
	public readonly string Data3;

	[OutputConstructor]
	public MyData(
		string data1,
		string data2,
		string data3)
	{
		Data1 = data1;
		Data2 = data2;
		Data3 = data3;
	}
}

```
Expected: Custom data type is successfully serialized.
Actual: **```System.InvalidOperationException: 'MyData' is not a supported argument type.```**

**Comment by jbrezina** [comment]
[[dotnet] Support outputs of type object](https://github.com/pulumi/pulumi/issues/5446) may be somehow related?

**Comment by mikhailshilkov** [comment]
This is tracked in #3690
