### ISSUE TITLE
Pulumi import refuses to proceed indicated a pending_operation

### ISSUE THREAD

**Issue by praveenperera** [pulumi/pulumi#9267]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

After my issue with #9266 I manually deleted all my resources. And deleted everything from the `pending_operations` and `resources`. However when I do import I get an error: 

```
error: the current deployment has 1 resource(s) with pending operations:
  * urn:pulumi:dev::sequence-infra::gcp:sql/databaseInstance:DatabaseInstance::project-service-database-instance, interrupted while creating
```

We are using Pulumi cloud so I don't know any other way to get the stack reset. My only option is to delete the stack and start over.

**Comment by mikhailshilkov** [comment]
It sounds like pending operations are still in the state file? Could you show a sanitized extract from your state file?

Usually, you should be able to able to get rid of pending operations by exporting the state and then importing it again `pulumi stack export | pulumi stack import`.

**Comment by praveenperera** [comment]
I deleted my stack and started over. But then `pending_operations` and `resources` was an empty array `[]`

**Comment by mikhailshilkov** [comment]
Which backend are you using (Pulumi SaaS, S3, etc)? For the service, we should be able to see the history of you state.
