### ISSUE TITLE
Output stack url and outputs to a file

### ISSUE THREAD

**Issue by StevePotter** [pulumi/pulumi#9268]
Hi, I'm looking to run Pulumi in a CI job and call another service to store the stack URL and outputs.  I can parse the output of `pulumi up`, but that's difficult and brittle.  CDK has an `--outputs-file` parameter that will generate a local JSON file with the outputs.  I'm looking for the same thing.  Ideally, one file that has the outputs in a JSON format and another file that has the URL to the stack.

**Comment by Frassle** [comment]
https://www.pulumi.com/docs/reference/cli/pulumi_stack_output/ ?

**Comment by mikhailshilkov** [comment]
Is this flag what you are looking for @StevePotter ?

```
  -j, --json           Emit output as JSON
```

**Comment by StevePotter** [comment]
Heck yes, I can't believe I missed it!  It would be cool to have a full url in addition to the urn, but that's fine.  Thanks so much!
