### ISSUE TITLE
Automation API, SummaryEvent is not emitted randomly [python]

### ISSUE THREAD

**Issue by pawelros** [pulumi/pulumi#9269]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

SummaryEvent sometimes is not emitted for successful Pulumi stack executions. I believe it should be always generated. Otherwise we cannot rely fully on Pulumi Automation Engine events.

### Steps to reproduce

I created in Python 3.9.10 a CI/CD application (I will share some parts of it) that utilises Pulumi Automation API. Application runs multiple Pulumi stacks at once - each stack in a dedicated thread. Pulumi stack execution is submitted into `ThreadPoolExecutor`:

```python
    def execute_all_stacks(self):
        """Submits all stacks from internal collection to a thread pool executor"""

        for stack_execution in self._stack_executions:
            stack_execution.future = self._thread_pool.submit(
                stack_execution.future_to_submit, on_event=stack_execution.on_event
            )
            stack_execution.future.add_done_callback(
                functools.partial(StackExecution.done_callback, stack_execution)
            )
```
I use few abstractions here that allow me to encapsulate some logic. As you can see I subscribe to `on_event` event.

`future_to_submit` is:
```python
    @property
    def future_to_submit(self):
        """Returns a method signature that will be executed on pulumi Stack object by thread pool executor."""

        return getattr(self._pulumi_stack, self._pulumi_action)
```
where `pulumi_stack` is stack created via Pulumi automation sdk:
```python
import pulumi.automation as auto
auto.select_stack(
                stack_name=stack_name,
                project_name=project_name,
                work_dir=work_dir
            )
```

on_event method that I subscribed looks like this:

```python
    def on_event(self, event: EngineEvent):
        """This callback is invoked whenever Pulumi engine emits an event.

        Events that we want to handle and transform to dto's for further processing are filtered here.
        EngineEvent code can be found here: https://github.com/pulumi/pulumi/blob/master/sdk/python/lib/pulumi/automation/events.py
        """ 

        """Here we handle diagnostic_event(s) in order to find any exception tracebacks."""
        diagnostic_event = event.diagnostic_event
        if diagnostic_event:
            if diagnostic_event.message.startswith('Traceback (most recent call last)'):
                traceback = TracebackEventDto.fromEngineEvent(event)
                self._traceback_events.append(traceback)

            return

        """Here we handle resource_pre_event(s) which are emitted during pulumi preview, refresh, update and destroy.
        Each event represents a new state of a single pulumi resource."""
        resource_event = event.resource_pre_event
        if resource_event:
            if resource_event.metadata.op in (
                OpType.CREATE,
                OpType.CREATE_REPLACEMENT,
                OpType.UPDATE,
                OpType.DELETE,
                OpType.DELETE_REPLACED,
                OpType.IMPORT,
                OpType.IMPORT_REPLACEMENT,
                OpType.REPLACE,
                OpType.REFRESH,
            ):
                dto = ResourceChangeEventDto.fromEngineEvent(event)
                self._resource_change_events.append(dto)

                if (
                    resource_event.metadata.type == 'aws:s3/bucketObject:BucketObject'
                    and resource_event.metadata.op == OpType.UPDATE
                ):
                    dto = S3BucketChangeEventDto.fromEngineEvent(event)
                    if dto:
                        self._s3_bucket_change_events.append(dto)

            return

        """Here we handle summary_event which is always emitted at the end of pulumi stack execution."""
        if event.summary_event:
            self._summary_event = SummaryEventDto.fromEngineEvent(event)
```

Expected: During every successful Pulumi stack execution, Pulumi Engine should emit `SummaryEvent` which contains crucial information about the run
Actual: Sometimes event did not get emitted at all. The thread finishes successfully, without any errors. Yet the event does not get emitted. 

I use `SummaryEvent` to generate a flat DTO that contains information about how many resources Pulumi stack execution changed, etc. Because sometimes the event is not emitted I am forced to implement a hacky fallback mechanism that parses this information from stack execution stdout using RegEx expressions. Maybe some wait() is needed?

**Comment by pawelros** [comment]
Not sure if this is related, but when SummaryEvent is not emmitted I always see this error as well:
```
2022-03-23T11:34:31.9843042Z Exception in thread Thread-99 (_watch_logs):
2022-03-23T11:34:31.9843463Z Traceback (most recent call last):
2022-03-23T11:34:31.9933754Z   File "/home/actions/actions-runner/_work/_tool/Python/3.10.3/x64/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
2022-03-23T11:34:31.9934306Z     self.run()
2022-03-23T11:34:31.9935128Z   File "/home/actions/actions-runner/_work/_tool/Python/3.10.3/x64/lib/python3.10/threading.py", line 946, in run
2022-03-23T11:34:31.9935621Z     self._target(*self._args, **self._kwargs)
2022-03-23T11:34:31.9936460Z   File "/home/actions/.local/share/virtualenvs/c-abtXG9Cs/lib/python3.10/site-packages/pulumi/automation/_stack.py", line 727, in _watch_logs
2022-03-23T11:34:31.9937084Z     event = EngineEvent.from_json(json.loads(line))
2022-03-23T11:34:31.9937850Z   File "/home/actions/actions-runner/_work/_tool/Python/3.10.3/x64/lib/python3.10/json/__init__.py", line 346, in loads
2022-03-23T11:34:31.9938359Z     return _default_decoder.decode(s)
2022-03-23T11:34:31.9939085Z   File "/home/actions/actions-runner/_work/_tool/Python/3.10.3/x64/lib/python3.10/json/decoder.py", line 337, in decode
2022-03-23T11:34:31.9939794Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2022-03-23T11:34:31.9940567Z   File "/home/actions/actions-runner/_work/_tool/Python/3.10.3/x64/lib/python3.10/json/decoder.py", line 353, in raw_decode
2022-03-23T11:34:31.9941075Z     obj, end = self.scan_once(s, idx)
2022-03-23T11:34:31.9941577Z json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2636 (char 2635)
```

**Comment by mikhailshilkov** [comment]
@iwahbe Could you take a look if you can repro or diagnose this somehow?

**Comment by iwahbe** [comment]
> Sometimes event did not get emitted at all. The thread finishes successfully, without any errors. Yet the event does not get emitted.

> Not sure if this is related, but when SummaryEvent is not emmitted I always see this error as well:

What do you mean by it the thread finishes without errors and you also see this error? Can you clarify?

When you say sometimes, do you have any understanding what causes the problem. Do some stacks always fail, but others always succeed? Will the same stack succeed or fail at random? Does this fail 1/10 times, 1/10,000? The reason I'm asking is to get a sense if I should look for a concurrency bug or not.

Our Automation API events are transmitted over the wire as JSON. If we are seeing a missing event, and also a json parsing traceback, I my immediate suspicion is that we are emitting invalid json.

**Comment by pawelros** [comment]
Hey @iwahbe, sorry for the confusion - I double checked random failures on my site and I can tell that for every random failure on my side I get `json.decoder.JSONDecodeError` error. My initial assessment probably was wrong because this exception was handled silently in my script and then the script was breaking on SummaryEvent that was not emitted because of `JSONDecodeError`. Do you want me to update issue title and description?

**Comment by iwahbe** [comment]
You don't need to update the description as long as I know what's going on (and its recorded in the comments). Thanks for offering though.

**Comment by pawelros** [comment]
Hey @iwahbe did you manage to find the problem? I can help you with debugging if you can't reproduce it.

**Comment by iwahbe** [comment]
@pawelros Sorry for the delayed response. I would love some help reproducing the problem.
I have been trying to reproduce the problem with the following program, and have been unsuccessful. 
```python
from os import getcwd
from concurrent import futures
import pulumi.automation as auto

num_stacks = 50

project_name = "python"
work_dir = getcwd()


all_events = []
summary_events = []


def on_event(e: auto.EngineEvent):
    if e.summary_event is not None:
        summary_events.append(e.summary_event)
    all_events.append(e)


e = futures.ThreadPoolExecutor(max_workers=4)

stacks = [
    e.submit(
        auto.create_or_select_stack,
        stack_name=f"stack-{i}",
        project_name=project_name,
        work_dir=work_dir,
    )
    for i in range(num_stacks)
]

# We wait to ensure maximum contention on events
print("Waiting on stack creation")
(done, not_done) = futures.wait(stacks)
if len(done) != num_stacks:
    raise Exception(f"Not enough stacks: {not_done}")
print("All stacks created")

results = [e.submit(s.result().preview, on_event=on_event) for s in stacks]

print(f"Waiting on {len(results)} futures")
futures.wait(results)
print(f"Collected {len(all_events)} events")
print(f"Collected {len(summary_events)} summary events (expected {num_stacks})")
```

**Comment by mikhailshilkov** [comment]
@pawelros Could you help Ian with the example above and trying to repro the problem? Thank you!

**Comment by pawelros** [comment]
Yes, sorry I forgot about that. Let my try to isolate the problem and prepare a test repo.

**Comment by pawelros** [comment]
Guys, is there any way to print the json? Our stacks contain a lot of resources and I think it might be very difficult to reproduce it with `hello-world` repos.

**Comment by iwahbe** [comment]
@pawelros I think you can insert a `print` statement on line 741 here:
https://github.com/pulumi/pulumi/blob/633d586aeb14ad35191ec2713430e5e8137f2877/sdk/python/lib/pulumi/automation/_stack.py#L732-L748

Let me know if that isn't what you were asking for.
