### ISSUE TITLE
Run golangci-lint with latest image (once we're building with go 1.18)

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi#9280]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

golangci-lint updated to run with go 1.18 which caused our linting for 1.17 code to start failing. We locked to a specific image version in https://github.com/pulumi/pulumi/pull/9279, but once we're on 1.18 we should set this back to latest.

1.18 error:
```
Run cd pkg && golangci-lint run -c ../.golangci.yml
cmd/pulumi/main_test.go:59:53: not enough arguments in call to testing.MainStart
	have (noTestDeps, nil, nil, nil)
	want ("testing".testDeps, []"testing".InternalTest, []"testing".InternalBenchmark, []"testing".InternalFuzzTarget, []"testing".InternalExample) (typecheck)
	m := testing.MainStart(noTestDeps(0), nil, nil, nil)
```

**Comment by RobbieMcKinstry** [comment]
Now that we're on Go 1.18, we're not encountering the lint violation anymore. However, we're still blocked from using `golangci-lint@latest` due to https://github.com/pulumi/pulumi/issues/10327 . That issue is tracking the upgrade of `golangci-lint` to v1.49.
