### ISSUE TITLE
Go project architecture

### ISSUE THREAD

**Issue by thepabloaguilar** [pulumi/pulumi#9289]
## Hello!
This is not a real feature request, it's a question. Sorry if here is not the right place!

I was using Pulumi with Python and it's very easy to reference a resource in other files since I can just import it.

Python Project Tree:
```text
my_repo
  -> ec2
  -> vpc
```

So, if I want to reference a VPC attribute in an EC2 resource I can just import:
```python
from my_repo import my_vpc

ec2_resource = ec2.EC2(vpc_id=my_vpc.id)
```

But now I'm working with Pulumi Go, and it's being hard to me to think how to do the same thing in Go! I want to separate every resource in its own package.
As an example, I'm trying to configure a `Kinesis Firehose` which depends of a `S3` bucket, how can I reference that bucket that's in another package in my `kinesis_firehose` package?

I can't even import because to import I need a name and an ID, but I don't know that ID until my bucket is created!

Any thoughts??

**Comment by thepabloaguilar** [comment]
As a workaround I've created a struct to encapsulate the creation function, so, I wrap every resource in a package. But the resource is just "created" once and the next calls to `Create` it just return the value from the first call.

```go
package creator

import (
	"sync"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ResourceCreator[R pulumi.Resource] struct {
	createFunc func(ctx *pulumi.Context) (R, error)
	resource   *R
	mu         sync.Mutex
}

func (r *ResourceCreator[R]) Create(ctx *pulumi.Context) (R, error) {
	if r.resource == nil {
		r.mu.Lock()
		defer r.mu.Unlock()
	}

	if r.resource == nil {
		resource, err := r.createFunc(ctx)
		if err != nil {
			var zeroValue R
			return zeroValue, err
		}

		r.resource = &resource
	}

	return *r.resource, nil
}
```

S3 Bucket:
```go
package s3

import (
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/s3"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"my-package/creator"
)

var Bucket = creator.NewResourceCreator(newBucket)

func newBucket(ctx *pulumi.Context) (*s3.Bucket, error) {
	bucket, err := s3.NewBucket(ctx, "SomeBucket", &s3.BucketArgs{
		Bucket: pulumi.String("bucket-name"),
	})
	if err != nil {
		return nil, err
	}

	return bucket, nil
}
```

So I can import:
```go
package ec2

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"my-package/creator"
	"my-package/s3"
)

var Resource = creator.NewResourceCreator(newResource)

func newResource(ctx *pulumi.Context) (*ec2.SomeResource, error) {
	bucket, err := s3.Bucket.Create(ctx)
	if err != nil {
		return nil, err
	}

	resource, err := ec2.SomeResource(ctx, "SomeResource", &ec2.SomeResourceArgs{
		Bucket: bucket,
	})
	if err != nil {
		return nil, err
	}

	return resource, nil
}
```

And run on the main loop:
```go
package main

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"my-package/creator"
	"my-package/s3"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		// Create S3 Bucket
		_, err := s3.Bucket.Create(ctx)
		if err != nil {
			return err
		}

		return nil
	})
}
```

**Comment by guineveresaenger** [comment]
Hi @thepabloaguilar - we welcome questions, and I love the detail in yours!

A great place to get help is our [Pulumi Community Slack](https://slack.pulumi.com/). The GO SDK is definitely some of the more tricky packages to deal with resource dependencies in your Pulumi code so I encourage you to join the community slack! 

At first glance at your question, you should be able to pass on the Pulumi Apply promise of the bucket ID just like you would for Python, more info here: 

https://www.pulumi.com/docs/intro/concepts/inputs-outputs/#apply

And a deep dive (unfortunately not Go focused) on the concept:
https://www.leebriggs.co.uk/blog/2021/05/09/pulumi-apply.html

**Comment by RobbieMcKinstry** [comment]
Hi @thepabloaguilar ! I hope you were able to find the answer to your question. Since this issue hasn't seen any further activity in awhile, I'm going to close it. Please reach out if you think it should be reopened :)
