### ISSUE TITLE
AquaSec Provider

### ISSUE THREAD

**Issue by yuft** [pulumi/pulumi#9315]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We are interested in this AquaSec TF provider(https://github.com/aquasecurity/terraform-provider-aquasec), can we bridge it to Pulumi?

Thank you.

**Comment by mikhailshilkov** [comment]
cc @pulumi/platform-providers

**Comment by guineveresaenger** [comment]
Hi @yuft - we would love to collaborate with you on this! 

While our documentation on how to help you get your provider all the way into the Pulumi registry is currently a bit lacking, we are actively working on improving that and will help you out as you go!

1. Get started by forking our boilerplate repo:
https://github.com/pulumi/pulumi-tf-provider-boilerplate

You should be able to follow all the steps up until "Configuring CI", with the only difference being that you'd be using your own org namespace.

2. We have a publishing process as well, outlined here: https://www.pulumi.com/docs/guides/pulumi-packages/how-to-author/

Please do not hesitate to reach out to us, right here on this issue, or on the [Pulumi community slack](https://slack.pulumi.com/) - the #contribute or #pulumiverse channels are both great.

**Comment by guineveresaenger** [comment]
Hi @yuft  - checking in to see if you had any other questions! 💟

**Comment by yuft** [comment]
@guineveresaenger thanks for the info. 

I will have a give it a try in the next 1-2 weeks and get back here.

**Comment by yuft** [comment]
@guineveresaenger I've pushed my changes here https://github.com/yuft/pulumi-AquaSec

I have only minimal examples.

I wonder what I can do next. doc/apis and a PR to https://github.com/pulumi/registry?

**Comment by guineveresaenger** [comment]
Hi @yuft! Sorry for the delay, I was out of office.

Next steps for you are:

Add a `docs` folder with two files - https://www.pulumi.com/docs/guides/pulumi-packages/how-to-author/#overview-installation--configuration for the overview tabs for your package docs on the registry

And you want to have nice looking metadata in your schema.json: https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/content/docs/guides/pulumi-packages/how-to-author.md#package-metadata

We're doing some updates on this, so your PR to https://github.com/pulumi/registry no longer needs to include any manually run docsgen - all you need to do is add the provider schema file path and repository slug to the [community packages list](https://github.com/pulumi/registry/blob/master/community-packages/package-list.json).

Once you open that registry PR, the team will help you address any remaining questions on that PR.

Thank you for your patience, we are grateful to any opportunity to improve our publishing process.

Please feel free to reach out to me, on the [Pulumi community slack](https://slack.pulumi.com/) - it's a little easier for me to respond faster on Slack. :)
