### ISSUE TITLE
pulumi state delete leaves URNs behind

### ISSUE THREAD

**Issue by rbm-radius** [pulumi/pulumi#9317]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Even after `pulumi destroy`, `pulumi up` can fail with a Duplicate resource error. `pulumi state delete <URN>` doesn't find that resource and can't delete it. A subsequent `pulumi up` creating a resource named like that URN fails with "Duplicate resource" error.

### Steps to reproduce

1. Create a stack with a cloudwatch LogGroup resource named '/my/resource'
2. Destroy the stack with `pulumi destroy`
3. Rebuild the stack with `pulumi up`
4. Get error message that the LogGroup resource named `<URN prefix>/my/resource` already exists
5. Delete the resource with `pulumi state delete <URN prefix>/my/resource`
6. Get error message that the resource does not exist
7. Rerun `pulumi up`
8. Get the duplicate resource error message from item 4 again 
9. `GOTO 5`

Expected: 

* The resource should be deleted after the first pulumi destroy
* The resource shouldn't throw a duplicate resource message after `pulumi destroy` and `pulumi up`
* The resource shouldn't throw an error that it doesn't exist in `pulumi state delete` after pulumi has complained it already exists

Actual: 

* `pulumi up` throws an error that the resource exists, but `pulumi state delete` doesn't find it.

![image](https://user-images.githubusercontent.com/99690083/160701410-b592c000-da6b-4604-b518-dfe8ec4c0430.png)

**Comment by mikhailshilkov** [comment]
@rbm-radius Could you please share the code to reproduce this? Based on the error, it looks like you have two resources with the same name in your Pulumi program.

**Comment by Frassle** [comment]
That error has _nothing_ to do with the current state. It's driven by `new Resource` calls from the running pulumi program. As Mikhail said it looks like you have two resources in your program that have got the same name.
If you export your stack state with `pulumi stack export` you could confirm that the URN isn't currently there.

**Comment by rbm-radius** [comment]
I'm not at liberty to share the code I have :( That said, I'm sure I don't have two resources by the same name. I only have one log group.

**Comment by Frassle** [comment]
Can you get debug logs by adding `-v9 --logtostderr` and either post them here or email them to fraser@pulumi.com.

That error can only happen from duplicate URNs so something must be triggering two registrations of that log group.
