### ISSUE TITLE
Schema generation is non-deterministic?

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi#9332]
We have [a build for one of our providers](https://github.com/pulumi/pulumi-hcloud/runs/5788302282?check_suite_focus=true) which is failing with a dirty schema in a strange way:

* When running locally, no diff exists for any SDK.
* When running in GH Actions, there's a diff _only for the Node SDK_.
* This issue does has yet to present itself for any other providers - just pulumi-hcloud.

Pulumi version is 3.27.0. I'm unable to determine _what_ the actual diff is. It could be whitespace, but copy/pasting into a visual diff tool yielded no difference.

**Comment by lunaris** [comment]
This has been open a while and doesn't appear to have bitten us recently (having checked in with provider maintainers), so I'm going to close as not reproducible. If it does rear its head again we can reopen and address.
