### ISSUE TITLE
CLI Performance Issues when using stackReferences

### ISSUE THREAD

**Issue by Kamaradeivanov** [pulumi/pulumi#9350]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

For several months I have been experiencing poor performance when using the `pulumi up` command. I suppose that the number of resources in several of my stack was in cause.

I already check the following closed issue : 

- https://github.com/pulumi/pulumi/issues/3178
- https://github.com/pulumi/pulumi/issues/3257

### Steps to reproduce

Recently I start a new project with just 12 resources : 

- 1 kubernetes Provider
- 3 kubernetes Secret
- 6 pulumi StackReference

Here is the trace aggregated View :

![image](https://user-images.githubusercontent.com/1730415/161802520-f301cbe0-cb8f-4d8a-a587-f85f87561da2.png)

And the trace for the pulumi job :

![image](https://user-images.githubusercontent.com/1730415/161804794-3bc0ee3a-23cb-4c5e-a733-de0fc53501c2.png)

Traces show me almost only api/decryptValue (more than 1000) and some api/getStack (12)

A pulumi up on that stack need 5 minutes to apply ... and 5min for the preview, so 10min to create 3 poor secrets. 

Expected: The pulumi up command should take 1 or 2 minutes.
Actual: It take 10 minutes

**Comment by Kamaradeivanov** [comment]
Sorry forgot to mention that : 

pulumi version : v3.28.0

And typescript versions: 

```json
 "dependencies": {
    "@pulumi/kubernetes": "3.18.0",
    "@pulumi/pulumi": "3.28.0",
  }
```

**Comment by mikhailshilkov** [comment]
Is it possible to remove some/all StackReferences temporarily just to confirm they are the culprit? Does the time grow linearly with the number of references?

**Comment by Kamaradeivanov** [comment]
I have simplify stacks used as reference to have only one secret at the top of each output. Now performance are far better.

**Comment by Kamaradeivanov** [comment]
I've done modification to switch all stack to this principle : if there is more than one secret into an output, I apply the method pulumi.secret() on that output. 

After doing that. When I apply the job that took 14min the first time (the one with 6 StackReference resources) it now took a little more than 4min. 

![image](https://user-images.githubusercontent.com/1730415/162195096-c5b28564-b5cd-4e27-b7bd-aa6d32e5cb50.png)

**Comment by Frassle** [comment]
So we added bulk decryption for when loading the state file for the stack being updated, but we don't do the same bulk decrypt when reading in stack references.

Should be a fairly easy addition.

**Comment by Frassle** [comment]
Digging into this I think my comment above is wrong, it looks like StackReferences should be hitting the bulkDecrypt path.

**Comment by Frassle** [comment]
So I think the problem is that BulkDecrypt is only used if the `Decrypter` implements the `BulkDecrypt` interface, and only the `serviceCrypter` does that. Problem is when we ask for the `Decrypter` from the `DefaultSecretsProvider` inside httpstack where we load the stack references it wraps that `serviceCrypter` in a `cachingCrypter` which _does not_ implement `BulkDecrypt`.

I'm inclined to change this BulkDecrypt design back to the one me and @stack72 originally had which didn't require any type tests to get things right. Should fix this up.
