### ISSUE TITLE
Pulumi changes detected on the same file.  

### ISSUE THREAD

**Issue by uqgwil10** [pulumi/pulumi#9352]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Pulumi compare thinks there are changes when it is the same file.

We have a datadog cloud formation file that we are storing locally and everytime we "pulumi up" changes are detected.  
![pulumi bug report](https://user-images.githubusercontent.com/13570168/161867782-cf5529fc-23dc-428c-b0c9-b4759afd8e5c.png)

It seems that some characters are altered when pulumi stores them in state. So when state is compared to the local cloudformation template it always picks up differences. 

From my perspective I have just altered the cloudformation template to remove those characters, but this wouldn't be possible if someone was referencing an external cloudformation template. 

### Steps to reproduce
1. Have a cloudformation file with with a description of a resource such as this `or send logs using AWS PrivateLink should select no and install this independently`
2. Using that cloudformation template create the resource in pulumi using @pulumi/aws - new aws.cloudformation.Stack
3. Pulumi up and deploy the resource.
4. After it has been successfully deployed. Pulumi up again and see pulumi still detects that there are changes. 

Expected: No changes to be present
Actual: Pulumi records that there are changes.

**Comment by mikhailshilkov** [comment]
Thank you for reporting @uqgwil10 

> Have a cloudformation file with with a description of a resource such as this or send logs using AWS PrivateLink should select no and install this independently

I think you lost those special characters in this quote that are likely causing the problem. (quotes around `no`?) Could you share the exact source text please?

**Comment by mikhailshilkov** [comment]
It's a fairly old issue and has no clear repro. Since we haven't heard back on the last question, I'll close it as non-actionable.
