### ISSUE TITLE
Pulumi CLI doesn't respect PULUMI_CONSOLE_DOMAIN env var for stack updates

### ISSUE THREAD

**Issue by mchaynes** [pulumi/pulumi#9356]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When I have `PULUMI_CONSOLE_DOMAIN` environment variable set, the CLI still uses project setting's URL as the backend when running `pulumi up`

However, the "View Live:" link pretends like it is respecting the variable.

![image](https://user-images.githubusercontent.com/17183569/162103543-c0bbf705-1818-4a7c-b055-452c4edc03ee.png)

I think that either **1)** Pulumi should respect the environment variable end to end. Or **2)** It should display the real URL its hitting.
#### root cause (maybe)
From reading the code, I believe I've figured out the root cause. Essentially when we build our "client", we use the project settings:
https://github.com/pulumi/pulumi/blob/50ade97b095a18df7ec49460cee0ccc4832f43ab/sdk/go/common/workspace/creds.go#L152-L181

Here's where we build and print the `View Live: <url>` link:
https://github.com/pulumi/pulumi/blob/50ade97b095a18df7ec49460cee0ccc4832f43ab/pkg/backend/httpstate/backend.go#L986-L1001

And here's what `b.CloudConsoleURL()` eventually does (note line 52):
https://github.com/pulumi/pulumi/blob/50ade97b095a18df7ec49460cee0ccc4832f43ab/pkg/backend/httpstate/console.go#L41-L68

### Steps to reproduce

1. Create pulumi program, run an update like normal using `app.pulumi.com` as the backend
2. Run `export PULUMI_CONSOLE_DOMAIN=localhost:4200`
3. Run `pulumi up`

Expected: `View Live: https://app.pulumi.com/myles/geodatadownloader/prod/previews/<uuid>`
Actual: `View Live: https://localhost:4200/myles/geodatadownloader/prod/previews/<uuid>`

**Comment by Frassle** [comment]
Ah reading though this a bit more carefully I'm not sure if there's actually anything we can do here. `PULUMI_CONSOLE_DOMAIN` is an envvar just used just to override this logic that's kind of it's point, it doesn't set the backend in use that's done by either project settings or `PULUMI_BACKEND_URL`.

The problem `PULUMI_CONSOLE_DOMAIN` is trying to solve is that given a backend url we can't know where it's app console url is, there's a few assumptions in cloudConsoleURL but they might be wrong so we have to let the env var take precedence.

I think the best we could do here is ignore the envvar _iff_ the backend is set to api.pulumi.com.

**Comment by mchaynes** [comment]
I see. Because `PULUMI_BACKEND_URL` != `PULUMI_CONSOLE_DOMAIN` and has no strict relation to each other, we have to assume that if the env var is defined, its also correct.

**Comment by Frassle** [comment]
Yup. I'm going to close this off as by-design.
