### ISSUE TITLE
Issues with previews of array values from StackReferences

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi#9365]
Notes from feedback from a user:

> I have a stack which pulls a StackReference, which will eventually have an output that isn’t there yet. In a preview, I see this:
> ![image](https://user-images.githubusercontent.com/223467/162269510-c9e8ad5d-387e-4754-9dc7-adb3444b9d34.png)
>  the second is from a stack reference, the first was created in the program
> 1) the null is wrong (and that value is known)
> 2) the “” is definitely wrong, at best it should be unknown, it should 100% not be an empty string.

**Comment by phillipedwards** [comment]
Steps to reproduce:
1. Create 2 pulumi programs
2. program 1 creates a security group and exports the security group ID
3. program 2 imports the above SG ID using a stack reference, creates another SG, applies both to an EC2 instance
4. pulumi up on program 2 to stand up base resources
5. Uncomment all commented lines in program (importing SG id via stackref and applying SG id to EC2 instance.
6. pulumi pre --diff shows issue seen in screenshot.

See screenshot below. "null" value in SG input list is a known and physically present SG ID.

![diff-screenshot](https://user-images.githubusercontent.com/25461821/162272050-8af44a9c-a521-4650-84c4-1bb724c979c2.png)

Program 1:
```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ec2"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		fullAccessCidr := pulumi.StringArray{pulumi.String("0.0.0.0/0")}
		sg, err := ec2.NewSecurityGroup(ctx, "cluster-sg", &ec2.SecurityGroupArgs{

			Ingress: ec2.SecurityGroupIngressArray{
				ec2.SecurityGroupIngressArgs{
					Protocol:   pulumi.String("tcp"),
					FromPort:   pulumi.Int(443),
					ToPort:     pulumi.Int(443),
					CidrBlocks: fullAccessCidr,
				},
			},
		})
		if err != nil {
			return err
		}

		// Export the name of the bucket
		ctx.Export("sg-id", sg.ID())
		return nil
	})
}
```

Program 2:
```go
package main

import (
	"github.com/pulumi/pulumi-aws/sdk/v5/go/aws/ec2"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		// UNCOMMENT TO SHOW ISSUE

		// stackRef, err := pulumi.NewStackReference(ctx, "phillipedwards/aws-sg-parent/dev", &pulumi.StackReferenceArgs{})
		// if err != nil {
		// 	return nil
		// }

		//id := stackRef.GetStringOutput(pulumi.String("sg-id"))

		fullAccessCidr := pulumi.StringArray{pulumi.String("0.0.0.0/0")}
		group, err := ec2.NewSecurityGroup(ctx, "web-secgrp", &ec2.SecurityGroupArgs{
			Ingress: ec2.SecurityGroupIngressArray{
				ec2.SecurityGroupIngressArgs{
					Protocol:   pulumi.String("tcp"),
					FromPort:   pulumi.Int(22),
					ToPort:     pulumi.Int(22),
					CidrBlocks: fullAccessCidr,
				},
			},
		})
		if err != nil {
			return err
		}

		mostRecent := true
		ami, err := ec2.LookupAmi(ctx, &ec2.LookupAmiArgs{
			Filters: []ec2.GetAmiFilter{
				{
					Name:   "name",
					Values: []string{"amzn-ami-hvm-*-x86_64-ebs"},
				},
			},
			Owners:     []string{"137112412989"},
			MostRecent: &mostRecent,
		})
		if err != nil {
			return err
		}

		srv, err := ec2.NewInstance(ctx, "web-server-www", &ec2.InstanceArgs{
			Tags:         pulumi.StringMap{"Name": pulumi.String("web-server-www")},
			InstanceType: pulumi.String("t2.micro"),
			VpcSecurityGroupIds: pulumi.StringArray{
				group.ID(),
				//id, // UNCOMMENT TO SHOW ISSUE
			},
			Ami: pulumi.String(ami.Id),
			UserData: pulumi.String(`#!/bin/bash
			echo "Hello, World!" > index.html
			nohup python -m SimpleHTTPServer 80 &`),
		})
		if err != nil {
			return err
		}

		ctx.Export("publicIp", srv.PublicIp)
		ctx.Export("publicHostName", srv.PublicDns)

		return nil
	})
}

```

**Comment by mikhailshilkov** [comment]
@phillipedwards The screenshot doesn't show the second part - namely the emtpy string - reported by the user. Do you know if this is also reproduced?

**Comment by phillipedwards** [comment]
@mikhailshilkov I've not yet been able to repro that portion, nor been able to get one from the user in question.

**Comment by pgavlin** [comment]
Reopening to track the issue around unknowns.

**Comment by phillipedwards** [comment]
@pgavlin re-running the same programs I provided above does seem to produce the empty string behavior the user is alluding to. I'm not sure if something has changed or my tests were ran incorrectly, but I can repeatedly produce the issue. 

Reproducible by deploying program 2 when program 1 stack is created, but has not yet been deployed.

Pulumi version - 3.30.0

![image](https://user-images.githubusercontent.com/25461821/164536044-4347f9da-9138-4452-956a-7d2ca8de5b07.png)

**Comment by dixler** [comment]
wasn't able to repro and going on PTO unassigning this issue.
