### ISSUE TITLE
Upgrade version of TypeScript bundled with Pulumi or allow override

### ISSUE THREAD

**Issue by antstanley** [pulumi/pulumi#9378]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The version of TypeScript currently bundled by Pulumi is v3.7.3, is old and doesn't support the latest Javascript features.  I'm trying to use the *ES2021* `.replaceAll` method to remove illegal characters from a label. 

Due to the old version of TypeScript in use I can't specify `es2021` as a compiler target or lib in my `tsconfig.json`

Node.js 16, the current LTS version of Node, supports all ES2021 features, but due to Pulumi using an old version of TypeScript those new language features are not available.

It would be great if Pulumi either kept the version of TypeScript up to date, or potentially moved it to a peer dependency allowing higher versions to be installed.

### Affected area/feature

Unable to use *ES2021* Javascript features with Pulumi TypeScript scripts.

**Comment by Frassle** [comment]
There's a few issues open for this already* so I'm going to close this as a duplicate.

\* https://github.com/pulumi/pulumi/issues?q=is%3Aissue+is%3Aopen+peer+dependency
