### ISSUE TITLE
python dynamic resource providers suddenly stopped working

### ISSUE THREAD

**Issue by sammck** [pulumi/pulumi#9381]
### What happened?

it looks a little like a github repo pulumi/pulumi-pulumi-python disappeared?

(
```bash
.venv) sam@sammck-ubuntu:~/projects/xpulumi/xp/project/dev-box$ pulumi up
Previewing update (dev):
 
error: could not load plugin for pulumi-python provider 'urn:pulumi:dev::dev-box::pulumi:providers:pulumi-python::default': no resource plugin 'pulumi-resource-pulumi-python' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource pulumi-python`
(.venv) sam@sammck-ubuntu:~/projects/xpulumi/xp/project/dev-box$ pulumi plugin install resource pulumi-python
error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-pulumi-python/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```

### Steps to reproduce

From a clean machine:

```bash
sam@sammck-ubuntu:~$ pulumi plugin install resource pulumi-python
pulumi: command not found
sam@sammck-ubuntu:~$ nano ~/.bashrc
sam@sammck-ubuntu:~$ ~/.pulumi/bin/pulumi plugin install resource pulumi-python
error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-pulumi-python/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```

### Expected Behavior

successful installation of plugin

### Actual Behavior

HTTP error accessing the pulumi github repo

### Versions used

v.3.28.0

### Additional context

This was working just a few days ago. no changes to my code, now I can neither update nor destroy my stacks.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
The pulumi-python resource plugin isn't actually a real plugin. It's a file that's packaged with the pulumi binary.

Can you check where you are running `pulumi` from and make sure that `pulumi-resource-pulumi-python` is also in that folder and that folder is on $PATH (N.B. This is arguably a bug, but dynamic providers only work if they're on PATH as opposed to every other provider and plugin)

**Comment by sammck** [comment]
If it's any help, it is also reproducible with:

```bash
docker run -it --rm ghcr.io/pulumi/pulumi-python pulumi plugin install resource pulumi-python
```

**Comment by sammck** [comment]
> The pulumi-python resource plugin isn't actually a real plugin. It's a file that's packaged with the pulumi binary.
> 
> Can you check where you are running `pulumi` from and make sure that `pulumi-resource-pulumi-python` is also in that folder and that folder is on $PATH (N.B. This is arguably a bug, but dynamic providers only work if they're on PATH as opposed to every other provider and plugin)

Yes, this is the problem. I explicitly do not have pulumi bin dir in PATH because I have private installations per project and do not want to accidentally invoke the wrong one.  It stopped working because I finally deleted my global installation of pulumi, and unbeknownst to me, all this time it had been finding the dynamic resource providers in a different pulumi bin directory than I was using (as you said, arguably a bug).
I added it onto PATH in my wrapper and now it works... Thanks.

**Comment by alfredopalhares** [comment]
I still get this error i am running pulumi up I am running version `3.104.2`  
```
Diagnostics:
  pulumi:providers:pulumi-python (default):
    error: could not find latest version for provider pulumi-python: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-pulumi-python/releases/latest. If this is a private Git
Hub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens

```
I have it in PATH, but I guess this issue is long time fixed, but there not really any more resources on this.

**Comment by Frassle** [comment]
> I have it in PATH

I assume you mean pulumi is on PATH. That shouldn't actually matter anymore. What's needed is that "pulumi-resource-pulumi-python" binary needs to be next to the pulumi binary. 

How did you install pulumi?

**Comment by alfredopalhares** [comment]
I did install via the arch linux package manager, its been working OK until i started writing dynamic providers.

**Comment by Frassle** [comment]
The arch package manager is not officially maintained, I would highly suspect that it's not doing the installation correctly in this case.

**Comment by alfredopalhares** [comment]
> The arch package manager is not officially maintained, I would highly suspect that it's not doing the installation correctly in this case.

This was exactly it, weird, because I never had any issues so far, I will report this to the package mantainer afterwards.
