### ISSUE TITLE
Add update plan support to Automation API

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi#9385]
We should add support for update plans to Automation API. Ideally you should be able to:

1. use Automation API to run a preview and get a strongly typed update plan (make sure types are available in all SDKs) as the output
2. manipulate the plan programmatically
3. run an update using that plan

This request has come up from several users over the last year or so. Here's a note from the original plan issue: 
- https://github.com/pulumi/pulumi/issues/2318#issuecomment-1009486815
- https://github.com/pulumi/pulumi/issues/2318#issuecomment-1089882330

**Comment by Frassle** [comment]
> manipulate the plan programmatically

Not sure what's expected here? We don't currently define the format for an update plan so these are just opaque files to the user.

**Comment by EvanBoyle** [comment]
@Frassle as a user in an automated setting I may want to generate a plan, and then apply some business logic on the plan to either relax or expand the generated constraints. I may just want to read the generated plan and make some assertions on it. 

I don't think transparent string is the right choice here. Not nearly as useful unless we add the types to the Automation API SDKs.

**Comment by Frassle** [comment]
I'm not sure we're ready to expose that level of detail as something user could take a dependency on. There's also the pain point that these types are easy to define for the go sdk (just reuse what's in sdk/go/common/apitype/plan.go) but I didn't think automation api duplicated this many types into other languages for anything else.
