### ISSUE TITLE
grpcio pinned <1.44 causes issues on ARM64 platforms

### ISSUE THREAD

**Issue by sammck** [pulumi/pulumi#9421]
https://github.com/pulumi/pulumi/blob/b31c5b136c6e6626c6b5bac8b2b8a777135586bb/sdk/python/requirements.txt#L4

I'm having trouble getting different packages to work together with Pulumi due to the upper bound on grpcio version. Ubuntu 20.04 ARM64 really wants 1.44, and the wheel for 1.43 can't seem to build from source. Looking online, there might have been a reason for the pin in the past, but maybe it is resolved?

I'm running on Apple M1 silicon but in an Ubuntu VM.

**Comment by sammck** [comment]
Hmm, I am able to get 1.43 installed into virtualenv by first upgrading pip and then explicitly using pip to install it.  But poetry immediately breaks reinstalling the same version...

```
  • Installing grpcio (1.43.0): Failed

  EnvCommandError

  Command ['/home/sam/sams-dev-box/.venv/bin/pip', 'install', '--no-deps', 'file:///home/sam/.cache/pypoetry/artifacts/70/29/58/8f9ec0af4f3b8c2001879d97d9d082ca9ef00e3d9dedc0586a2a567157/grpcio-1.43.0-cp38-cp38-manylinux_2_17_aarch64.whl'] errored with the following return code 1, and output: 
  ERROR: grpcio-1.43.0-cp38-cp38-manylinux_2_17_aarch64.whl is not a supported wheel on this platform.
```

May be a poetry issue, but may affect other users...

**Comment by mikhailshilkov** [comment]
Pinned in https://github.com/pulumi/pulumi/pull/9139

@iwahbe The upstream issue seems to be closed. Can we unpin?

**Comment by iwahbe** [comment]
@mikhailshilkov It looks like we can unpin
