### ISSUE TITLE
[ci] Intermittent build failures with API rate limit exceeded

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#9424]
Our tests keep failing intermittently with 

> Run jaxxstorm/action-install-gh-release@v1.3.1
> Error: API rate limit exceeded for installation ID 807028.

[Example](https://github.com/pulumi/pulumi/runs/6077315980?check_suite_focus=true#step:19:1)

Let's figure out where the limit is and how to stop hitting it from our CI.

**Comment by Frassle** [comment]
Raised https://github.com/jaxxstorm/action-install-gh-release/pull/16 to add throttling to action-install-gh-release

**Comment by Frassle** [comment]
Updated our CI to use a new version of action-install-gh-release. It _should_ backoff and retry rate limit errors. Will watch for a few days before closing this off as fixed.

**Comment by Frassle** [comment]
Haven't seen any more instances of this 🎉
