### ISSUE TITLE
Composite ResourceOption

### ISSUE THREAD

**Issue by ghostsquad** [pulumi/pulumi#9455]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Would be nice to have something like a `Composite` ResourceOption, where it fits the bill as a _single_ `ResourceOption` even if behind the scenes it were multiple. There are some use cases where this would save a bit of typing and neaten the code.

### Affected area/feature

Pulumi core interfaces

**Comment by Frassle** [comment]
Is this a request for the Go SDK? The other languages already use `ResourceOptions` types (note the plurality). Have you got an example of some code you have that would benefit from this? Also how would you expect this to work if options clashed (e.g. combining `Protect(true)` and `Protect(false)`)?

**Comment by ghostsquad** [comment]
Yes, this is for Go.

This would be a simple wrapper around how resource options already work. They are applied in order presented.

So you can default with everything protected, and pass in another option to turn off protect. The last option wins.

A composite is just a slice, and internally iterates over each item in it.

**Comment by Frassle** [comment]
Sounds reasonable. No objection to this being added in. If you feel you can make a Pull Request for this, I'd be happy to review. Else I'll see about getting round to it between things, shouldn't take too long to write up.

**Comment by ghostsquad** [comment]
> Sounds reasonable. No objection to this being added in. If you feel you can make a Pull Request for this, I'd be happy to review. Else I'll see about getting round to it between things, shouldn't take too long to write up.

I'll submit a PR tonight
