### ISSUE TITLE
Multi-Language Component Cannot be a Parent of Another Resource - Causes Promise Leak

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#9457]
### What happened?

Using a multi-language component as the `parent` property to another resource causes a fatal error (promise leak).

### Steps to reproduce

1. Install a Pulumi component, in  your Pulumi program, which is generated from a MLC. Eg- https://www.pulumi.com/registry/packages/aws-s3-replicated-bucket/.
2. Create another resource, such as a bucket object.
3. Set the bucket object's `parent` resourceOption to the MLC.
4. See promise leak

### Expected Behavior

MLC should be able to be set as parent of another resource.

### Actual Behavior

MLC as a parent of another resource causes promise leak and fatal error.

### Versions used

CLI Version                        3.30.0
aws                                    5.2.0
aws-s3-replicated-bucket  0.0.6

### Additional context

Sample program to reproduce error:
```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as s3 from "@pulumi/aws-s3-replicated-bucket";
import { PathLike, promises as fs } from "fs";

const uploadObjectsToBucket = async (bucket: s3.ReplicatedBucket, dir: PathLike) => {
    const objects = await fs.readdir(dir, { withFileTypes: true });
    for (const object of objects) {
        const path = `${dir}/${object.name}`;
        new aws.s3.BucketObject(object.name, {
            bucket: bucket.sourceBucket.id,
            source: new pulumi.asset.FileAsset(path)
        }, {
            parent: bucket // commenting 'parent' will stop error
        });
    }
}

export = async () => {

    const mlcBucket = new s3.ReplicatedBucket("rep-bucket", {
        destinationRegion: "us-east-1"
    });

    await uploadObjectsToBucket(mlcBucket, "./content")
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I think this might just be a manifestation of the more general issues with setting parent to any component resource. It looks like the BucketObject is trying to register before the component is constructed and then a load of properties are just being filled in as the system also tries to shutdown.
