### ISSUE TITLE
pulumi up does not fail on error

### ISSUE THREAD

**Issue by mvgijssel** [pulumi/pulumi#9461]
### What happened?

Running `pulumi up` without being logged in / without having a `PULUMI_ACCESS_TOKEN` set resulted in an error being **printed** but not in a non-zero exit code.

### Steps to reproduce

```shell
❯ pulumi  up -y | tee
error: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions

❯ echo $?
0
```

### Expected Behavior

I would expect a non-zero exit code when there is an error.

### Actual Behavior

Zero (0) exit code returned.

### Versions used

```
CLI
Version      3.30.0
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME    VERSION
python  unknown

Host
OS       darwin
Version  12.3
Arch     x86_64

This project is written in python (/Users/maarten/.asdf/shims/python3 v3.9.7)

Current Stack: mg_74_deploy_vms_ignite_pulumi

TYPE                      URN
pulumi:pulumi:Stack       urn:pulumi:mg_74_deploy_vms_ignite_pulumi::infrastructure::pulumi:pulumi:Stack::infrastructure-mg_74_deploy_vms_ignite_pulumi
pulumi:providers:command  urn:pulumi:mg_74_deploy_vms_ignite_pulumi::infrastructure::pulumi:providers:command::default_0_1_0
command:remote:Command    urn:pulumi:mg_74_deploy_vms_ignite_pulumi::infrastructure::command:remote:Command::k3s_cluster


Found no pending operations associated with mg_74_deploy_vms_ignite_pulumi

Backend
Name           pulumi.com
URL            https://app.pulumi.com/mvgijssel
User           mvgijssel
Organizations

NAME        VERSION
pip         21.2.3
setuptools  57.4.0

Pulumi locates its logs in /var/folders/50/lc98t2hn7t18m9tlzx6v10yh0000gn/T/ by default
```

### Additional context

Might be related https://github.com/pulumi/pulumi/issues/5085

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
pulumi does exit with a non-zero exit code. But your checking the exit code of the whole pipe operation with "$?" and because `tee` was successful the exit code is 0.

Check out [PIPESTATUS](https://unix.stackexchange.com/questions/14270/get-exit-status-of-process-thats-piped-to-another):
```
fraser@IBASA-PC:~/projects/example$ PULUMI_ACCESS_TOKEN="" pulumi up --yes | tee
error: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions
fraser@IBASA-PC:~/projects/example$ echo "${PIPESTATUS[0]} ${PIPESTATUS[1]}"
255 0
```

**Comment by mvgijssel** [comment]
Thanks @Frassle for pointing that out! Sorry for the oversight 🤦 . Also noticed that I wasn't propagating the error code from a Python subprocess as well https://github.com/mvgijssel/setup/pull/85/commits/d732c213dec2e914038737f62b979234cd3927db 🙈
