### ISSUE TITLE
Default and Explicit Provider is Selecting Different Plugin Versions

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#9482]
### What happened?

In a go program, with multiple versions of the same Pulumi plugin installed, the default provider selects the appropriate version based on the SDK version, while the explicit provider selects the newest available version of the plugin. For example, if versions `4.38.1` and `5.1.3` of the `aws` plugin are installed and the SDK is pinned to `github.com/pulumi/pulumi-aws/sdk/v4/go/aws` in the go program, the default provider will correctly select the `4.38.1` version while the explicit provider will incorrectly select the `5.1.3` version.

Not only is this incorrect, but this is problematic as there are some breaking changes seen in `5.1.3`. Plugin versions should match the SDK's version unless the user defines otherwise. Note, a workaround is to specify the version of the `plugin` for the provider in the provider's resource options, however, this is cumbersome.

### Steps to reproduce

1. Clone https://github.com/phillipedwards/aws-plugin-issue
2. Ensure AWS plugin `4.38.1` and `5.1.2 | 5.1.3` are installed. `pulumi plugin install resource aws ....`
3. Execute `pulumi up`
4. Pay close attention to the `eks.LookupCluster` calls. (they have different outcomes with different providers).

### Expected Behavior

Explicit and default providers, in the same program, should select the correct plugins as dictated by the language SDK. In this case, that should be `pulumi aws 4.38.1` as aws is pinned to `github.com/pulumi/pulumi-aws/sdk/v4/go/aws` in the Pulumi program.

### Actual Behavior

Explicit provider disregards the pinned version in the program and selects the latest available version of the aws plugin, which is `5.1.3` in this case. The default provider correctly selects version `4.38.1`. 

NOTE: if only version `4.38.1` is installed, the explicit provider will select the correct plugin version.

### Versions used

CLI: 3.30.0
AWS: 4.38.1, 5.1.3
OS: Ubuntu - 20.04

### Additional context

Viewing log data, `GetPluginPath` is initially called with a semver included (`4.38.1`) which correctly selects the plugin version. Later in the execution, `GetPluginPath()` is called _without_ a semver included which defaults plugin selection to "the latest version". This data can be seen executing with `pulumi up|pre --logtostderr -v=9 2> logs.txt`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Looking at this there's code in the engine which seems to expect a "version" property on provider resources, but looking at providers in the sdks nothing seems to ever pass that information.

I think when we generate SDKs we need to codegen in the provider version as part of the inputs sent for the provider resource.

**Comment by phillipedwards** [comment]
@Frassle The "version" or lack of a "version" is what I also observed in the logs. Explicit providers always seem to be passing `nil` as version to `GetPluginPath()`.

**Comment by iwahbe** [comment]
We can't embed versions in our packages unless we change how our versioning works. We don't know the version of a package when we build it because we base the version on the commit hash of the checked in package (which depends on the code generate). I think we will need to change how version lookup happens (at the engine level) for providers where the version isn't specified (using the same process as for default providers if version is nil).

If we could fill the `"version"` tag in our schemas, then the change would be three lines in [these functions](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/go/gen.go#L3728-L3761).

**Comment by pgavlin** [comment]
> Looking at this there's code in the engine which seems to expect a "version" property on provider resources, but looking at providers in the sdks nothing seems to ever pass that information.
> 
> I think when we generate SDKs we need to codegen in the provider version as part of the inputs sent for the provider resource.

We do set these fields. See for example https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/s3/bucket.ts#L517 and https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/utilities.ts#L51-L54. I think that we just don't do this for Go.

**Comment by pgavlin** [comment]
I experimented with a cut-down version of the original program a bit. Here's a version that only uses the `v4` module:

```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws"
	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/iam"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		cfg := config.New(ctx, "aws")
		awsProvider, err := aws.NewProvider(ctx, "aws", &aws.ProviderArgs{
			Region: pulumi.String(cfg.Require("region")),
			//Profile: pulumi.String(cfg.Require("profile")),
		})

		if err != nil {
			return nil
		}

		eksRole, err := iam.NewRole(ctx, "eks-iam-eksRole", &iam.RoleArgs{
			AssumeRolePolicy: pulumi.String(`{
		    "Version": "2008-10-17",
		    "Statement": [{
		        "Sid": "",
		        "Effect": "Allow",
		        "Principal": {
		            "Service": "eks.amazonaws.com"
		        },
		        "Action": "sts:AssumeRole"
		    }]
		}`),
		}, pulumi.Provider(awsProvider))

		if err != nil {
			return err
		}

		eksPolicies := []string{
			"arn:aws:iam::aws:policy/AmazonEKSServicePolicy",
			"arn:aws:iam::aws:policy/AmazonEKSClusterPolicy",
		}

		for i, eksPolicy := range eksPolicies {
			_, err := iam.NewRolePolicyAttachment(ctx, fmt.Sprintf("rpa-%d", i), &iam.RolePolicyAttachmentArgs{
				PolicyArn: pulumi.String(eksPolicy),
				Role:      eksRole.Name,
			})
			if err != nil {
				return err
			}
		}

		return nil
	})
}
```

And here's a version that mixes `v4` and `v5` (it is more likely that in practice the dependency would be transitive):

```go
package main

import (
	"fmt"

	"github.com/pulumi/pulumi-aws/sdk/v4/go/aws/iam"
	awsv5 "github.com/pulumi/pulumi-aws/sdk/v5/go/aws"
	iamv5 "github.com/pulumi/pulumi-aws/sdk/v5/go/aws/iam"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		cfg := config.New(ctx, "aws")
		awsProvider, err := awsv5.NewProvider(ctx, "aws", &awsv5.ProviderArgs{
			Region: pulumi.String(cfg.Require("region")),
			//Profile: pulumi.String(cfg.Require("profile")),
		})

		if err != nil {
			return nil
		}

		eksRole, err := iam.NewRole(ctx, "eks-iam-eksRole", &iam.RoleArgs{
			AssumeRolePolicy: pulumi.String(`{
		    "Version": "2008-10-17",
		    "Statement": [{
		        "Sid": "",
		        "Effect": "Allow",
		        "Principal": {
		            "Service": "eks.amazonaws.com"
		        },
		        "Action": "sts:AssumeRole"
		    }]
		}`),
		}, pulumi.Provider(awsProvider))

		if err != nil {
			return err
		}

		eksPolicies := []string{
			"arn:aws:iam::aws:policy/AmazonEKSServicePolicy",
			"arn:aws:iam::aws:policy/AmazonEKSClusterPolicy",
		}

		for i, eksPolicy := range eksPolicies {
			_, err := iamv5.NewRolePolicyAttachment(ctx, fmt.Sprintf("rpa-%d", i), &iamv5.RolePolicyAttachmentArgs{
				PolicyArn: pulumi.String(eksPolicy),
				Role:      eksRole.Name,
			})
			if err != nil {
				return err
			}
		}

		return nil
	})
}
```

In the former case, both the `v4` and `v5` plugins are loaded. The `v4` plugin is chosen for the default provider because the `v5` SDK is not referenced by the program, but the `v5` plugin is loaded for the explicit provider because its resource options do not specify a version and the plugin loader decides to use the newest available version. In this case, the `v5` provider should not have been chosen because the explicit provider request is from the `v4` SDK.
```
I0531 16:26:11.417707   56823 plugins.go:258] computeDefaultProviderPlugins(): considering go
I0531 16:26:11.417720   56823 plugins.go:261] computeDefaultProviderPlugins(): skipping go, not a resource provider
I0531 16:26:11.417728   56823 plugins.go:258] computeDefaultProviderPlugins(): considering aws-4.38.1
I0531 16:26:11.417738   56823 plugins.go:289] computeDefaultProviderPlugins(): plugin aws-4.38.1 selected for package aws (first seen)
I0531 16:26:11.417746   56823 plugins.go:295] computeDefaultProviderPlugins(): summary of default plugins:
I0531 16:26:11.417771   56823 plugins.go:297]   aws             = 4.38.1

...
I0531 16:26:13.233549   56823 plugin.go:184] Launching plugin 'aws (resource)' from '/Users/pgavlin/.pulumi/plugins/resource-aws-v5.6.0/pulumi-resource-aws' with args: 127.0.0.1:56614
I0531 16:26:15.820866   56823 plugin.go:184] Launching plugin 'aws (resource)' from '/Users/pgavlin/.pulumi/plugins/resource-aws-v4.38.1/pulumi-resource-aws' with args: 127.0.0.1:56614
```

In the latter case, only the `v5` plugin is loaded. The `v5` plugin is chosen for the default provider because both the `v4` and `v5` SDKs are referenced by the program and the resource registration that caused the default provider creation does not specify an SDK version, in which case the loader decides to load the newest plugin. The same goes for the explicit provider. In this case, the default provider--which is created due to a resource registration from the `v4` SDK--uses the wrong version, but the explicit provider chooses the right version.
```
I0531 16:24:18.871011   56598 plugins.go:258] computeDefaultProviderPlugins(): considering go
I0531 16:24:18.871025   56598 plugins.go:261] computeDefaultProviderPlugins(): skipping go, not a resource provider
I0531 16:24:18.871033   56598 plugins.go:258] computeDefaultProviderPlugins(): considering aws-4.38.1
I0531 16:24:18.871044   56598 plugins.go:289] computeDefaultProviderPlugins(): plugin aws-4.38.1 selected for package aws (first seen)
I0531 16:24:18.871053   56598 plugins.go:258] computeDefaultProviderPlugins(): considering aws-5.6.0
I0531 16:24:18.871062   56598 plugins.go:277] computeDefaultProviderPlugins(): plugin aws-5.6.0 selected for package aws (override, newer than previous 4.38.1)
I0531 16:24:18.871075   56598 plugins.go:295] computeDefaultProviderPlugins(): summary of default plugins:
I0531 16:24:18.871082   56598 plugins.go:297]   aws             = 5.6.0
...
I0531 16:24:29.645228   56598 plugin.go:184] Launching plugin 'aws (resource)' from '/Users/pgavlin/.pulumi/plugins/resource-aws-v5.6.0/pulumi-resource-aws' with args: 127.0.0.1:56537
I0531 16:24:36.523774   56598 plugin.go:184] Launching plugin 'aws (resource)' from '/Users/pgavlin/.pulumi/plugins/resource-aws-v5.6.0/pulumi-resource-aws' with args: 127.0.0.1:56537
```

This is a pretty serious issue, but I'm not entirely sure how to solve it without changing the way we deal with versions in the Go SDK.

**Comment by Frassle** [comment]
> We do set these fields. See for example https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/s3/bucket.ts#L517 and https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/utilities.ts#L51-L54. I think that we just don't do this for Go.

That provider config is on resources not providers seems to be a point my brain just struggles to get ☹️
