### ISSUE TITLE
Consider a `copy` command

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#95]
It might be convenient to offer a `copy` command that copies and renames an existing target:

    $ pulumi stack copy stage-west stage-east

This would simply copy the whole resource state from `stage-west` to a new environment `stage-east`.  We could consider what it would mean to copy into an existing environment too.

By default, it would presumably carry forward all configuration.  But if we wanted to change some configuration, as in this particular example, we could enable deltas at `copy` time:

    $ pulumi stack copy stage-west stage-east --config.aws:region=us-east-1

This raises some interesting challenges, such as the fact that (for AWS), the AMI names between regions will differ.  This may entirely obviate the usefulness of this command, since we might need to actually execute the package anyway to generate the new AMI names.  But I still feel like this could be a useful capability, especially for scenarios where we are gradually rolling out changes.

**Comment by lukehoban** [comment]
https://github.com/pulumi/pulumi/issues/1583 tracks a more up to date version of this.  Closing this one out.
