### ISSUE TITLE
Allow changing project name in Pulumi.yaml

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi#950]
Consider providing a way to change project names, or just allowing the name to be changed in `Pulumi.yaml`. See the discussion in #541 for more details.

## Issue

The project name in `Pulumi.yaml` is assumed to be part of a stable identifier in identifying a stack (either a local or managed stack).  Currently, renaming the project will result in all stack resources being orphaned. 

## Workaround 

To work around this, run `pulumi destroy` before renaming the project.  (If you have already changed the project name, simply change back to the old name and run `pulumi destroy`.)

**Comment by nguyenxndaidev** [comment]
My workaround is to change also the `.pulumi/stacks/<stack>.json` to match the new project name.

**Comment by jbrezina** [comment]
There is a [duplicate issue](https://github.com/pulumi/pulumi/issues/3052) where is also mentioned [workaround](https://github.com/pulumi/pulumi/issues/3052#issuecomment-865645728) without destroying all the resources

**Comment by mikhailshilkov** [comment]
Thank you @jbrezina. Indeed, I tried the suggested workaround and it seems to work just fine for me. I'll go ahead and close both issues.
