### ISSUE TITLE
Integration tests fail for Java and YAML

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#9535]
With `unrecognized project runtime` error

> Error:     template_test.go:98: Starting test run for "aws-java"
  Error:     program.go:1648: sample: /tmp/test-env672361055
  Error:     program.go:1653: pulumi: /home/runner/.pulumi/bin/pulumi
      program.go:680: 
          	Error Trace:	program.go:680
          	            				template_test.go:140
          	Error:      	Received unexpected error:
          	            	copying test to temp dir : Failed to prepare /tmp/p-it-fv-az397-8-test-env67-d7405958-753017410: unrecognized project runtime: java
          	Test:       	TestTemplates/aws-java

https://github.com/pulumi/templates/runs/6290540103?check_suite_focus=true

**Comment by iwahbe** [comment]
I want to see a successful run before I close this issue
