### ISSUE TITLE
Changed PULUMI_CONFIG_PASSPHRASE behaviour can delete entire state file.

### ISSUE THREAD

**Issue by wannessels** [pulumi/pulumi#9541]
### What happened?

After upgrading to 3.31.1 the state file was emptied for every stack we ran.

We are using pulumi automation (python) and storing our state in an s3 bucket with kms key and appropriate policies. As such we don't need the pulumi passphrase and set it to empty.

Root cause is probably bad error handling in stack.create_or_select , in this case triggered by changed behaviour of empty PULUMI_CONFIG_PASSPHRASE env var, see https://github.com/pulumi/pulumi/pull/9490

### Steps to reproduce

[pulumi_sample.py](https://github.com/pulumi/pulumi/files/8622400/pulumi_sample.py.txt)

first run with 3.30.0
```
>pulumi version
v3.30.0
warning: A new version of Pulumi is available. To upgrade from version '3.30.0' to '3.31.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

>python pulumi_sample.py
Updating (stack):

+  pulumi:pulumi:Stack project-stack creating
+  random:index:RandomString random creating
+  random:index:RandomString random created
+  pulumi:pulumi:Stack project-stack created

Resources:
+ 2 created

Duration: 1s
```
then upgrade to 3.31.1
```
>pulumi version
v3.31.1

>python pulumi_sample.py  
Traceback (most recent call last):
  File "pulumi_sample.py", line 24, in <module>
    stack = Stack.create_or_select("stack", workspace)
  File "venv\lib\site-packages\pulumi\automation\_stack.py", line 160, in create_or_select
    return Stack(stack_name, workspace, StackInitMode.CREATE_OR_SELECT)
  File "venv\lib\site-packages\pulumi\automation\_stack.py", line 186, in __init__
    workspace.create_stack(name)
  File "venv\lib\site-packages\pulumi\automation\_local_workspace.py", line 214, in create_stack
    self._run_pulumi_cmd_sync(args)
  File "venv\lib\site-packages\pulumi\automation\_local_workspace.py", line 300, in _run_pulumi_cmd_sync
    return _run_pulumi_cmd(args, self.work_dir, envs, on_output)
  File "venv\lib\site-packages\pulumi\automation\_cmd.py", line 75, in _run_pulumi_cmd
    raise create_command_error(result)
pulumi.automation.errors.CommandError:
 code: 4294967295
 stdout: Created stack 'stack'
 stderr: error: passphrase must be set with PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE environment variables


>pulumi stack --show-urns
Current stack is stack:
    Managed by Thinkpad
    No updates yet; run 'pulumi up'
Current stack resources (0):
    No resources currently in this stack

Use `pulumi stack select` to change stack; `pulumi stack ls` lists known ones
```

### Expected Behavior

don't create empty state if select fails due to missing passphrase

### Actual Behavior

existing state file overwritten with empty state file

### Versions used

3.31.1

### Additional context

Please provide an alternative mechanism to set empty passphrase (without having to create an empty passphrase file)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> As such we don't need the pulumi passphrase and set it to empty.

Ah yes so "" is now treated the same as unset. Quick fix just set it to to a non-empty placeholder value.

**Comment by Frassle** [comment]
> Won't that make existing secrets unaccessible? We don't need the extra security of a passphrase, but we do use secrets to avoid generated credentials being logged.

Yes, it would, sorry didn't click that you've currently got secrets. I think given that short-term use a an empty file and set PULUMI_CONFIG_PASSPHRASE (although be aware that's currently broken and will be fixed in 3.32.1). I'm looking to see if there's a flag to just disable the encryption but still track that things are secrets for logging, if there isn't one we could see about adding that.

**Comment by Frassle** [comment]
So firstly 3.32.1 has been released and PULUMI_CONFIG_PASSPHRASE_FILE should be working again.

Looking to the next release I've got two ideas to help with this:
1. Add a new "SecretsProvider" option called "passthrough" (name up for change, maybe "disabled" or "none" would be better). Normally you'd set this via `stack init --secrets-provider passthrough`.
2. Add another PULUMI_CONFIG_SECRETS_PROVIDER envvar that will be used for --secrets-provider if none is given on the command line.

I think with both of those you should be able to just set PULUMI_CONFIG_SECRETS_PROVIDER=passthrough to get the behavior you want. Note that the CLI will track these things are still secrets and so filter them out as "[secret]" but in the state file they will just be plain text.

E.g. given a state file like:
```
"outputs": {
  "bucketName": {
    "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
    "ciphertext": "\"my-bucket-c728f05\""
  }
},
```
`pulumi stack output` will print:
```
Current stack outputs (1):
    OUTPUT      VALUE
    bucketName  [secret]
```
or with --show-secrets:
```
Current stack outputs (1):
    OUTPUT      VALUE
    bucketName  my-bucket-c728f05
```

Does that all sound fine?

**Comment by Frassle** [comment]
We've reverted the behaviour change here. We will allow PULUMI_CONFIG_PASSPHRASE to be set to "" and will treat that as a passphrase of "" rather than unset. 

N.B. PULUMI_CONFIG_PASSFILE continues to treat "" as unset, but then the empty string was never a valid file path anyway so this just brings it into consistency with most envvars where we treat "" and unset the same.
