### ISSUE TITLE
pulumi export statement in a loop works unexpectedly

### ISSUE THREAD

**Issue by flyisland** [pulumi/pulumi#9547]
### What happened?

I created multiple VMs with a loop, and I want to output the public IP of each VM after they were created.

### Steps to reproduce

Basically, I just put the example code from [azure-py-webserver](https://github.com/pulumi/examples/blob/3245f1f031/azure-py-webserver/__main__.py) into a loop, of course, each resource has its unique name with the index of the loop. I expected the export statement at the end of the loop would show me the public IPs of all VMs after they were created.

```python
for i in range(2):
    vm_name = f"sol{i}"
    ...
    ...
    ...
    public_ip_addr = vm.id.apply(lambda _: network.get_public_ip_address_output(
        public_ip_address_name=public_ip.name,
        resource_group_name=resource_group.name))

    export(f"{vm_name} IP", public_ip_addr.ip_address)
```

### Expected Behavior

I expect outputs with two different public IP

```
Outputs:
    sol0 IP:: "20.239.154.IP1"
    sol1 IP:: "20.239.154.IP2"
```

### Actual Behavior

I Got the same IP with two outputs

```txt
    Type                                      Name            Status
 +   pulumi:pulumi:Stack                       azure-vms-dev   created
 +   ├─ azure-native:resources:ResourceGroup   resource_group  created
 +   ├─ azure-native:network:VirtualNetwork    sol_VNET        created
 +   ├─ azure-native:network:PublicIPAddress   sol0_PublicIP   created
 +   ├─ azure-native:network:PublicIPAddress   sol1_PublicIP   created
 +   ├─ azure-native:network:NetworkInterface  sol0_Nic        created
 +   ├─ azure-native:network:NetworkInterface  sol1_Nic        created
 +   ├─ azure-native:compute:VirtualMachine    sol1            created
 +   └─ azure-native:compute:VirtualMachine    sol0            created

Outputs:
    sol0 IP:: "20.239.154.16"
    sol1 IP:: "20.239.154.16"

Resources:
    + 9 created

Duration: 1m55s
```

### Versions used

```
❯ pulumi about
CLI
Version      3.32.0
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.63.0
python        unknown

Host
OS       darwin
Version  12.3.1
Arch     x86_64

This project is written in python (/Users/ichen/.pyenv/shims/python3 v3.9.4)

Backend
Name           pulumi.com
URL            https://app.pulumi.com/ichen
User           ichen
Organizations  ichen

NAME                 VERSION
black                22.3.0
pip                  22.0.4
pulumi-azure-native  1.63.0
setuptools           62.1.0
wheel                0.37.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I think this is due to Python not Pulumi. Your code has probably captured the loop variable, which in python is a single mutable variable. For example the following program prints `3 3 3 3` not `0 1 2 3`:
```
    xs = []
    for i in range(4):
        ys = lambda: i
        xs.append(ys)

    for x in xs:
        print(x())
```

You need to assign `i` to a new local `j` within the loop body to capture correctly.

**Comment by Frassle** [comment]
Just assign the loop variable to a new name inside the loop body. e.g taking my example above:
```
    xs = []
    for i in range(4):
        j = i
        ys = lambda: j
        xs.append(ys)

    for x in xs:
        print(x())
```

**Comment by flyisland** [comment]
But it's not the loop variable I'd like to export, I need to export the output of the pulumi resources.

If you look at the outputs in the Actual Behavior, you could see the loop variable is correctly printed, `sol0` and `sol1`.

```
Outputs:
    sol0 IP:: "20.239.154.16"
    sol1 IP:: "20.239.154.16"
```

Anyway, I modified the code as below:
```
for i in range(2):
    vm_name = f"sol{i}"
    ...
    ...
    ...
    # Get IP address as an output.
    public_ip_address_name = public_ip.name
    resource_group_name = resource_group.name
    public_ip_addr = vm.id.apply(
        lambda _: network.get_public_ip_address_output(
            public_ip_address_name=public_ip_address_name,
            resource_group_name=resource_group_name,
        )
    )

    export(f"{vm_name} IP", public_ip_addr.ip_address)

```

But I still got the same result, two different VM name with the same Public IP

```
     Type                                          Name            Status
 +   pulumi:pulumi:Stack                           azure-vms-dev   created
 +   ├─ azure-native:resources:ResourceGroup       resource_group  created
 +   ├─ azure-native:network:VirtualNetwork        sol_VNET        created
 +   ├─ azure-native:network:NetworkSecurityGroup  sol_nsg         created
 +   ├─ azure-native:network:PublicIPAddress       sol0_PublicIP   created
 +   ├─ azure-native:network:PublicIPAddress       sol1_PublicIP   created
 +   ├─ azure-native:network:NetworkInterface      sol0_Nic        created
 +   ├─ azure-native:network:NetworkInterface      sol1_Nic        created
 +   ├─ azure-native:compute:VirtualMachine        sol1            created
 +   └─ azure-native:compute:VirtualMachine        sol0            created

Outputs:
    sol0 IP: "20.187.65.232"
    sol1 IP: "20.187.65.232"

Resources:
    + 10 created
```

**Comment by flyisland** [comment]
> xs = []
>     for i in range(4):
>         j = i
>         ys = lambda: j
>         xs.append(ys)
> 
>     for x in xs:
>         print(x())

I just found the above code also prints `3 3 3 3 ` : (

**Comment by flyisland** [comment]
I just fixed this issue.

As @Frassle pointed out, the root cause of this issue is that I used the loop's local variable in the lambda expression directly. 

After I studied [How to Use Python Lambda Functions](https://realpython.com/python-lambda/#appropriate-uses-of-lambda-expressions) and the [Inputs and Outputs](https://www.pulumi.com/docs/intro/concepts/inputs-outputs/) of Pulumi, I think I should get the required variable from the argument of the `apply` method.

Here is the modified code:

```python
for i in range(2):
    vm_name = f"sol{i}"
    ...
    ...
    ...
    # Get IP address as an output.
    combined_output = Output.all(
        vm_id=vm.id,
        public_ip_name=public_ip.name,
        resource_group_name=resource_group.name,
    )
    public_ip_addr = combined_output.apply(
        lambda args: network.get_public_ip_address_output(
            public_ip_address_name=args["public_ip_name"],
            resource_group_name=args["resource_group_name"],
        )
    )
    export(f"{vm_name} IP", public_ip_addr.ip_address)
```

Now I can get all the Public IPs I want:

```
Outputs:
  - sol0 IP: "20.239.193.78"
  - sol1 IP: "20.239.195.132"
```

**Comment by Frassle** [comment]
> I just found the above code also prints 3 3 3 3 : (

Urgh yeh of course should of tested that, was doing it from memory and forgot the oddness you have to do for python:
```
xs = []
for i in range(4):
    ys = lambda j=i: j
    xs.append(ys)

for x in xs:
    print(x())
```

You need to trigger a new scope for the new name, otherwise j is just part of the same scope as i (loops don't _actually_ have their own scope in python).
