### ISSUE TITLE
Python Codegen Breaks when using Reference Types which Themselves Contain an Enum

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi#9565]
### What happened?

When using reference types which contain an enum themselves, Python codgen attempts to get a relative path to the resource's module, which is not the path where the enum resides (it's a reference type). Thus, python can't resolve the import.

### Steps to reproduce

If you define a resource which references an external type, in our case google-native:iam/v1:AuditConfig, which has a nested enum property, this case will be hit:

```golang
func (mod *modContext) collectImportsForResource(properties []*schema.Property, imports imports, input bool,
	res *schema.Resource) {
	codegen.VisitTypeClosure(properties, func(t schema.Type) {
		switch t := t.(type) {
		case *schema.ObjectType:
			imports.addType(mod, t, input)
		case *schema.EnumType:
			imports.addEnum(mod, t.Token)
		case *schema.ResourceType:
			// Don't import itself.
			if t.Resource != res {
				imports.addResource(mod, t)
			}
		}
	})
}
```

which will end up calling this:
```golang
func (mod *modContext) importEnumFromToken(tok string) string {
	modName := mod.tokenToModule(tok)
	if modName == mod.mod {
		return "from ._enums import *"
	}

	importPath := mod.getRelImportFromRoot()

	if modName == "" {
		return fmt.Sprintf("from %s import _enums as _root_enums", importPath)
	}

	components := strings.Split(modName, "/")
	return fmt.Sprintf("from %s import %s", importPath, components[0])
}
```

### Expected Behavior

Generated Python is able to import module.

### Actual Behavior

Generated Python is not able to import module.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I don't think I fully understand this issue, but from what I think your talking about (running sdk generation for a schema that uses `google-native:iam/v1:AuditConfig` as a property) I can't see any issue.

I added a codegen test and pushed a branch here: https://github.com/pulumi/pulumi/compare/fraser/issue9565

Could you get back with what I'm missing to show the error your talking about?
