### ISSUE TITLE
Unpredictable behavior of `pulumi preview --json` (sometimes includes `.newState.outputs` and sometimes doesn't)

### ISSUE THREAD

**Issue by briansorahan** [pulumi/pulumi#9571]
### What happened?

I'm using the `--json` flag to `pulumi preview --diff` to detect differences in the preview between one branch and another of a pulumi project at work.
What I'm seeing is that for resources that have updates, there is sometimes an `outputs` field in the newState json object and sometimes not.
I was initially on 3.32.1 when I started seeing this behavior, and it was happening about 50% of the time.
Today I downgraded to 3.28.0 because I've been doing the test for a couple weeks and wasn't seeing it until just recently, which made me think it might have something to do with upgrading the CLI (I upgrade every time it says I should).
With 3.28.0 I would say I'm seeing this issue about 20% of the time.
The specific resources I'm seeing it on are kubernetes deployments and stateful sets.

### Steps to reproduce

I don't have a reliable way to reproduce this yet.

### Expected Behavior

`pulumi preview` will deterministically output JSON that shows me the updates to a stack.

### Actual Behavior

Sometimes there is an `outputs` field in the `newState` object, and sometimes not.

### Versions used

```
CLI
Version      3.28.0
Go Version   go1.17.8
Go Compiler  gc

Plugins
NAME        VERSION
aiven       4.1.1
docker      3.0.0
gcp         5.11.0
kafka       3.0.1
kubernetes  3.8.3
mysql       3.0.0
python      unknown

Host
OS       darwin
Version  12.1
Arch     x86_64

This project is written in python (/Users/brian.soraham/miniconda3/envs/muse_deploy/bin/python3 v3.8.5)

Backend
Name           E983171-MAR-22
URL            gs://REDACTED
User           brian.soraham
Organizations

NAME                    VERSION
alembic                 1.4.3
black                   19.10b0
gcsfs                   2022.3.0
invoke                  1.5.0
more-itertools          8.12.0
mypy                    0.910
mysql-connector-python  8.0.21
pip                     20.2.3
psutil                  5.8.0
pulumi-aiven            4.1.1
pulumi-docker           3.0.0
pulumi-gcp              5.11.0
pulumi-kafka            3.0.1
pulumi-kubernetes       3.8.3
pulumi-mysql            3.0.0
pycodestyle             2.7.0
pylint                  2.4.4
PyMySQL                 0.10.1
pytest                  6.2.4
pytz                    2020.4
setuptools              61.2.0
wheel                   0.37.1

Pulumi locates its logs in /var/folders/ld/v996jmzs70g4zhkg7mgq9gn00000gr/T/ by default
warning: Failed to get information about the current stack: No current snapshot
warning: A new version of Pulumi is available. To upgrade from version '3.28.0' to '3.32.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @briansorahan thank you for reporting this.

We want to understand how to reproduce this issue. Does it happen on any stack for you, or on some specific one? If would be great if you could share a repro with us.

**Comment by RobbieMcKinstry** [comment]
Hi @briansorahan . Just wanted to give you a friendly nudge to provide further information, if you have it! Thanks! :)

**Comment by mikhailshilkov** [comment]
This issue is fairly old and, since we haven't heard back, I'll go ahead and close it as non-actionable
