### ISSUE TITLE
Gitpod environment seems to be broken

### ISSUE THREAD

**Issue by Phil1972** [pulumi/pulumi#9577]
### What happened?

I read the contributing instructions and wanted to opt for the Gitpod ready environment, but it will not work.  There are build errors and we cannot go further.

### Steps to reproduce

Click on the gitpod link.  The make and dependencies nuget won't load properly.

https://gitpod.io/#https://github.com/pulumi/pulumi

### Expected Behavior

Working environment

### Actual Behavior

Error in the terminal window preventing proper build (make)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@jaxxstorm were you the one who setup gitpod? I think it was intended to run pulumi, not contribute to it, wasn't it?
