### ISSUE TITLE
Support TypeScript more natively in the engine

### ISSUE THREAD

**Issue by lindydonna** [pulumi/pulumi#958]
Per discussion in https://github.com/pulumi/pulumi/issues/898#issuecomment-364608190:

From @lukehoban 

> if we want to specifically solve the TypeScript part of the problem, it would be interesting to look into whether our Node execution wrapper should use [ts-node](https://github.com/TypeStrong/ts-node) or similar so that TypeScript can be loaded directly without the need for compilation at all.  That could significantly help with the TypeScript-specific experience.

See also: https://github.com/pulumi/pulumi/issues/98 and https://github.com/pulumi/pulumi/issues/722#issuecomment-351823013

**Comment by lukehoban** [comment]
We considered this in #981 and decided not to do it at the time - but I increasingly think we need to do this.  Even for statically typed languages like Go, we don't require an explicit build step.  It feels really odd that we don't just take case of this.  I'm inclined to take @ellismg's suggestion in  https://github.com/pulumi/pulumi/pull/981#issuecomment-370663668 and move ahead with this again.

**Comment by joeduffy** [comment]
I would like to at least make this possible, even if just an option, since I myself always forget to compile.  Might be worth taking inspiration from how [Deno](https://github.com/ry/deno) does this.

**Comment by lukehoban** [comment]
> even if just an option

Yeah, this was exactly the suggestion frmo @ellismg I liked above - to make this a separate `runtime` target you can use in `Pulumi.yaml` so that it's opt-in - and still allows using the existing javascript target it you just want to treat TS as a transpiler.
