### ISSUE TITLE
Resource options additional_secret_outputs not working

### ISSUE THREAD

**Issue by iakabi25** [pulumi/pulumi#9581]
### What happened?

I try to mask a secret using additional secret outputs : https://www.pulumi.com/docs/intro/concepts/resources/options/additionalsecretoutputs/

But when I do a pulumi preview, the secret is shown and it also appears in plaintext in the stack file.

### Steps to reproduce

In python : 
```
aws.secretsmanager.SecretVersion(
                f"aws_secretversion_{secret_name}",
                secret_id=secret.id,
                secret_string=json.dumps(secret_value),
                opts=ResourceOptions(additional_secret_outputs=["secret_string"])
)
```
I also tried with `ResourceOptions(additional_secret_outputs=["secretString"])`.

When I do a pulumi preview, I can see the secret in plaintext : 

```
aws:secretsmanager/secretVersion:SecretVersion: (create)
[urn=urn:pulumi:dev::snowflake::aws:secretsmanager/secretVersion:SecretVersion::aws_secretversion_snowflake/user/dev_usr_finops_api]
        [provider=urn:pulumi:dev::snowflake::pulumi:providers:aws::default_4_38_1::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        secretId    : output<string>
        secretString: (json) {
            password         : "3BY,&LwsG__\\=)0/MUch[Te=J)zh[5"
            username         : "TEST"
        }
```

### Expected Behavior

The secret should not be shown when I run pulumi preview. It should also be encrypted in the stack file.

### Actual Behavior

The secret is shown when I run pulumi preview. And the secret appears in plaintext in the stack file.

### Versions used

The secret is shown when I run pulumi preview. And the secret appears in plaintext in the stack file.

CLI
Version      3.32.1  
Go Version   go1.17.9
Go Compiler  gc      

Plugins
NAME       VERSION
aws        4.38.1
python     unknown
snowflake  0.7.0

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in python (/usr/bin/python3 v3.9.5)

Current Stack: dev

Backend
Name           FR-XXXXX
URL            s3://XXXXXX
User           iakabi
Organizations

NAME                        VERSION
pip                         22.0.4
pkg_resources               0.0.0
pulumi-aws                  4.38.1
pulumi-snowflake            0.7.0
pydantic                    1.9.0
snowflake-connector-python  2.7.6
wheel                       0.37.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @iakabi25 thank you for your question.

`additional_secret_outputs` is to mark _outputs_ of the resource as a secret, not its inputs. If you want to secret-fy an input, use `Output.secret` instead:

```python
import pulumi
from pulumi_aws import secretsmanager

secret_value = pulumi.Output.secret("{\"my\": \"secret\"}")

secretsmanager.SecretVersion(
    f"aws_secretversion",
    secret_id="test",
    secret_string=secret_value
)
```

**Comment by iakabi25** [comment]
Thanks it was it ! Sorry for the inconvenience
