### ISSUE TITLE
Add package schema metadata for Go module path

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi#9601]
When running `pulumi convert` on an awsx project, we lack a reliable way to obtain the module version in our schema for Go, see the [comment here for details](https://github.com/pulumi/pulumi/blob/a5645493929d8749b2c86d537e8ba5578c6cde79/pkg/codegen/go/gen_program.go#L160-L190).

Running `go mod tidy` tends to work and is at least deterministic on an individual's machine, but is not reproducible and can vary depending on what exists in a user's module cache. The awsx package specifies an import base path:

```json
      "importBasePath": "github.com/pulumi/pulumi-awsx/sdk/go/awsx",
```

But the module is located two directories up, and this can't be determined (see the link at the top) without pulling the repo.

```go.mod
module awsx

go 1.17

require github.com/pulumi/pulumi-awsx/sdk v1.0.0-beta.2
```

As go.mod is generated without a version for the awsx package and it's `go mod tidy` that finds the version, on my machine due to my module cache having test and prerelease versions, it finds `v1.0.0-testplsignore.0`.

```
 ~/.pulumi-dev/bin/pulumi convert --language go --out .wip.as-go
Installing dependencies...

go: finding module for package github.com/pulumi/pulumi-awsx/sdk/go/awsx/lb
go: finding module for package github.com/pulumi/pulumi-awsx/sdk/go/awsx/ecs
go: found github.com/pulumi/pulumi-awsx/sdk/go/awsx/ecs in github.com/pulumi/pulumi-awsx/sdk v1.0.0-testplsignore.0
go: found github.com/pulumi/pulumi-awsx/sdk/go/awsx/lb in github.com/pulumi/pulumi-awsx/sdk v1.0.0-testplsignore.0
Finished installing dependencies
```

**Comment by iwahbe** [comment]
@AaronFriel Is the goal to generate a partial `go.mod`? I don't understand when we would separate them without generating `go.mod`. I think we would still get unreliable imports when packages we specify depend on cached packages.

**Comment by AaronFriel** [comment]
Yeah, the goal is to generate a complete go.mod for direct dependencies with specific versions.
