### ISSUE TITLE
Master builds are failing with checksum errors

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#9602]
A few recent master builds have failed with

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/1454008/168580037-7dbae021-f236-4a85-a4b4-ab1fb67e4ba5.png">

https://github.com/pulumi/pulumi/runs/6431805010?check_suite_focus=true#step:15:29

**Comment by mikhailshilkov** [comment]
Potentially can be addressed by https://github.com/pulumi/pulumi/issues/6634

**Comment by t0yv0** [comment]
Worked around this but the root cause points to the need to switch to GoReleaser PRO https://github.com/pulumi/pulumi/issues/8885
