### ISSUE TITLE
Make it possible to create custom pulumi packages without manual workarounds

### ISSUE THREAD

**Issue by vavsab** [pulumi/pulumi#9606]
Hi team. I need to wrap **[DataStax Astra](https://www.datastax.com/products/datastax-astra)** [terraform provider](https://registry.terraform.io/providers/datastax/astra/latest).

I've forked pulumi tf boilerplate [here](https://github.com/mapped/pulumi-astra) and almost got it to work.

I have 2 problems stopping from fully utilizing it:

1. ~Nodejs generator creates `pluginDownloadURL` property but pulumi expects `server`. Pulumi fails to download my custom package until I manually change it to `server`.~ (Moved to https://github.com/pulumi/pulumi/issues/9661)
![image](https://user-images.githubusercontent.com/10233442/168849474-8defc971-6726-43a2-abb7-be25c9190c52.png)
**Possible solution**: change generator in [`gen.go`](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/nodejs/gen.go#L2112) to emit `server`.

2. My nodejs package name is **@mapped/pulumi-astra**. It does not follow pulumi conventions, thus it generates incorrect download URL for my plugin and pulumi fails unless I manually override it in `package.json`. The problem is that I cannot override it in my [`resources.go`](https://github.com/mapped/pulumi-astra/blob/main/provider/resources.go#L119)
![image](https://user-images.githubusercontent.com/10233442/168858338-4bf04027-2c89-4066-8be1-43c9e6ebae41.png)

I see that it takes `PluginName` from schema [here](https://github.com/pulumi/pulumi/blob/9d0b09c229fcc3eda185b90479ac706890241e7b/pkg/codegen/nodejs/gen.go#L2155) but there is no way to put it into schema in my [`resources.go`](https://github.com/mapped/pulumi-astra/blob/main/provider/resources.go#L119)

**Possible solution**: add `pluginName` property in [`tfgen`](https://github.com/pulumi/pulumi-terraform-bridge/blob/5945d59d8189b841964708a3d13dfb110925f2fc/pkg/tfgen/generate_schema.go#L300)

**Comment by iwahbe** [comment]
I can't speak to the tf-bridge issue, but you are definitely right about writing `pluginDownloadURL` and expecting `server`. I'm going to split that into a separate issue so we can track both separately.

**Comment by iwahbe** [comment]
CC @pulumi/platform-providers can you take a look at the TF-bridge problem. The solution seems reasonable but I don't know enough to be sure.

**Comment by guineveresaenger** [comment]
Hi @vavsab - you should be able to use the [latest version of the Terraform bridge](https://github.com/pulumi/pulumi-terraform-bridge/releases/tag/v3.24.1) and then `PackageName` should be available in your `resources.go` file like in [this example](https://github.com/jaxxstorm/pulumi-scaleway/blob/master/provider/resources.go#L202).

**Comment by vavsab** [comment]
H @guineveresaenger [Updated](https://github.com/mapped/pulumi-astra/commit/5100c583dde2e91062c8240dbd4cdd9458f9fa83). It did not help. My schema still misses `pluginName` prop.
Let's go through the problem one more time:
1. It won't work until I have `pulumi.name` prop generated in my package.json 
![image](https://user-images.githubusercontent.com/10233442/170231420-dab8c743-c363-41ef-a5d9-6d58e698fec7.png)
2. We may see [here](https://github.com/pulumi/pulumi/blob/9d0b09c229fcc3eda185b90479ac706890241e7b/pkg/codegen/nodejs/gen.go#L2155) that it can generate `pulumi.name`. For this our `schema.json` must contain 'language.nodejs.pluginName' prop (please do not confuse with `packageName`, they are different). As you may see from my `schema.json` [here](https://github.com/mapped/pulumi-astra/blob/5100c583dde2e91062c8240dbd4cdd9458f9fa83/provider/cmd/pulumi-resource-astra/schema.json#L1889) I have no `pluginName` generated.
3. To generate `pluginName` we need to add a property to tfgen and assign it [here](https://github.com/pulumi/pulumi-terraform-bridge/blob/5945d59d8189b841964708a3d13dfb110925f2fc/pkg/tfgen/generate_schema.go#L300)

**Comment by stack72** [comment]
Hi @vavsab 

We have package specific metadata in the bridge that handles the mapping here. For NodeJS, you can specify `PackageName` in the bridge as follows:

```
		JavaScript: &tfbridge.JavaScriptInfo{
			PackageName: "@pulumiverse/unifi",
			// List any npm dependencies and their versions
			Dependencies: map[string]string{
				"@pulumi/pulumi": "^3.0.0",
			},
			DevDependencies: map[string]string{
				"@types/node": "^10.0.0", // so we can access strongly typed node definitions.
				"@types/mime": "^2.0.0",
			},
			// See the documentation for tfbridge.OverlayInfo for how to lay out this
			// section, or refer to the AWS provider. Delete this section if there are
			// no overlay files.
			//Overlay: &tfbridge.OverlayInfo{},
		},
```
That will ensure that the package name generated is as suggested. We also have a way of doing the same for Python and setting DotNet RootNamespace. 

With regards to the pluginName specifically, we determine that based on the schema itself. So for example if your provider is called `pulumi-astra` then we will determine the provider name to be `astra`. We then use the `pluginDownloadURL` to be able to determine what we believe is the correct format of the binary to download based on OS and Architecture. By setting the PackageName and the plugiDownloadURL correctly, you will be able to get the correct provider name as part of your download string

You can follow the following best practice examples of providers that were created by the community [pulumi-unify](https://github.com/pulumiverse/pulumi-unifi/blob/main/provider/resources.go) or [pulumi-scaleway](https://github.com/jaxxstorm/pulumi-scaleway/blob/master/provider/resources.go).

If you need me to get on a call and help you then I am glad to do so. 

Paul

**Comment by vavsab** [comment]
@stack72 I found it! Pulumi does not care about `pluginDownloadUrl` at all. It's important only for [this ci script](https://github.com/jaxxstorm/scripts/blob/third_party/ci/add-plugin-installer-script.js#L47).

I see 3 possible fixes here:
1. Update [tf boilerplate](https://github.com/pulumi/pulumi-tf-provider-boilerplate/blob/main/deployment-templates/release.yml#L110) to use this CI action to make `pluginDownloadUrl` work.
2. Fix tfgen to generate URL [here](https://github.com/jaxxstorm/pulumi-scaleway/blob/master/sdk/nodejs/scripts/install-pulumi-plugin.js#L10) correctly (you may notice that URL there misses `v` prefix in the version)
3. Fix tfgen to emit `server` in addition to `pluginDownloadURL`. I like this the most cause even if I remove pulumi binary cash it will reload it on `pulumi preview` or `pulumi up`

**Comment by vavsab** [comment]
@stack72 Please [find me in Teams](https://teams.microsoft.com/l/chat/0/0?users=ivan@mapped.com) to discuss this issue.

**Comment by guineveresaenger** [comment]
Hi @vavsab - I'm assuming that you were able to figure out the correct naming for your wrapped provider, so I'm going to close out this issue and track your suggestions in https://github.com/pulumi/pulumi-tf-provider-boilerplate/issues/74.

**Comment by vavsab** [comment]
@guineveresaenger nope. It's still unresolved. Need to continue the conversation here and fix the bugs.

**Comment by vavsab** [comment]
I just discovered that problem is deeper than it seems to be. `pulumi plugin install` will always fail for community packages if you clear pulumi packages binary cache. This must be resolved. I can make a PR. Just let's decide how you want it to be fixed.

**Comment by stack72** [comment]
@vavsab please can you provide the logs of the Pulumi plugin install command and we can see - this feels like your provider may be incorrectly configured from the boilerplate as we have helped a few people out these together

**Comment by stack72** [comment]
After looking you are missing a 'v' on this line as part of your pluginDownloadURL https://github.com/mapped/pulumi-astra/blob/7a991f13b51ced45428f53dc0a53dbf79e450bdd/provider/resources.go#L73

The path just match that of the release name (v1.0.15)

**Comment by vavsab** [comment]
> After looking you are missing a 'v' on this line as part of your pluginDownloadURL https://github.com/mapped/pulumi-astra/blob/7a991f13b51ced45428f53dc0a53dbf79e450bdd/provider/resources.go#L73
> 
> The path just match that of the release name (v1.0.15)

If I add 'v' I will get 'vv' in pluginDownloadUrl. Already tried. Furthermore, scaleway provider has no 'v' https://github.com/jaxxstorm/pulumi-scaleway/blob/c5f054b607e9f5ff86539c2fcbb2bf605cfe251d/provider/resources.go#L86

**Comment by vavsab** [comment]
> @vavsab please can you provide the logs of the Pulumi plugin install command and we can see - this feels like your provider may be incorrectly configured from the boilerplate as we have helped a few people out these together

Let me show how this bug works for already existing community package.
Steps to reproduce:
1. init nodejs pulumi project
2. `npm install @jaxxstorm/pulumi-scaleway`
3. Add some scaleway resources
```js
import * as scaleway from "@jaxxstorm/pulumi-scaleway";

export const res = (async () => {
    // No matter what. Just to make pulumi download scaleway binaries.
    new scaleway.IotHub("test-db", {
        productPlan: "test"
    })
})()
```
4. Run `pulumi plugin install`
It crashes here. 
`[resource plugin jaxxstorm/pulumi-scaleway-0.2.1] installing
error: [resource plugin jaxxstorm/pulumi-scaleway-0.2.1] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-jaxxstorm%2Fpulumi-scaleway-v0.2.1-windows-amd64.tar.gz`

My pulumi version is `v3.33.2`. Updated now.


<details><summary>Detailed logs `pulumi plugin install --logtostderr -v 10`:</summary>
<p>
I0528 22:20:09.504571   28284 plugins.go:1057] GetPluginPath(language, nodejs, <nil>): found on $PATH C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin\pulumi-language-nodejs.exe
I0528 22:20:09.505077   28284 plugin.go:184] Launching plugin 'nodejs' from 'C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin\pulumi-language-nodejs.exe' with args: -root=C:\Projects\Mapped\pulumi-playground,127.0.0.1:63496
I0528 22:20:10.240523   28284 langruntime_plugin.go:207] langhost[nodejs].GetPluginInfo() executing
I0528 22:20:10.241600   28284 langruntime_plugin.go:115] langhost[nodejs].GetRequiredPlugins(proj=ivan-pulumi-playground,pwd=C:\Projects\Mapped\pulumi-playground,program=.) executing
I0528 22:20:10.426898   28284 langruntime_plugin.go:157] langhost[nodejs].GetRequiredPlugins(proj=ivan-pulumi-playground,pwd=C:\Projects\Mapped\pulumi-playground,program=.) success: #versions=4
I0528 22:20:10.430288   28284 plugins.go:1057] GetPluginPath(language, nodejs, <nil>): found on $PATH C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin\pulumi-language-nodejs.exe
I0528 22:20:10.430849   28284 plugins.go:1098] GetPluginPath(resource, jaxxstorm/pulumi-scaleway, 0.2.1): enabling new plugin behavior
I0528 22:20:10.430849   28284 plugins.go:1184] SelectCompatiblePlugin(..., jaxxstorm/pulumi-scaleway): beginning
I0528 22:20:10.431411   28284 plugins.go:1223] SelectCompatiblePlugin(..., jaxxstorm/pulumi-scaleway): failed to find match
I0528 22:20:10.436316   28284 plugins.go:1098] GetPluginPath(resource, astra, 1.0.15): enabling new plugin behavior
I0528 22:20:10.436316   28284 plugins.go:1184] SelectCompatiblePlugin(..., astra): beginning
I0528 22:20:10.436316   28284 plugins.go:1217] SelectCompatiblePlugin(..., astra): skipping plugin astra-1.0.14: semver mismatch
I0528 22:20:10.436874   28284 plugins.go:1213] SelectCompatiblePlugin(..., astra): best plugin astra-1.0.15: semver match
I0528 22:20:10.436874   28284 plugins.go:1226] SelectCompatiblePlugin(..., astra): selecting plugin 'astra-1.0.15': best match
I0528 22:20:10.436874   28284 plugins.go:1145] GetPluginPath(resource, astra, 1.0.15): found in cache at C:\Users\IvanSabelnikov\.pulumi\plugins\resource-astra-v1.0.15\pulumi-resource-astra.exe
I0528 22:20:10.442893   28284 plugins.go:1098] GetPluginPath(resource, cloudflare, 4.7.0): enabling new plugin behavior
I0528 22:20:10.442893   28284 plugins.go:1184] SelectCompatiblePlugin(..., cloudflare): beginning
I0528 22:20:10.442893   28284 plugins.go:1213] SelectCompatiblePlugin(..., cloudflare): best plugin cloudflare-4.7.0: semver match
I0528 22:20:10.443409   28284 plugins.go:1226] SelectCompatiblePlugin(..., cloudflare): selecting plugin 'cloudflare-4.7.0': best match
I0528 22:20:10.443409   28284 plugins.go:1145] GetPluginPath(resource, cloudflare, 4.7.0): found in cache at C:\Users\IvanSabelnikov\.pulumi\plugins\resource-cloudflare-v4.7.0\pulumi-resource-cloudflare.exe
I0528 22:20:10.448642   28284 plugins.go:1098] GetPluginPath(resource, random, 4.7.0): enabling new plugin behavior
I0528 22:20:10.448642   28284 plugins.go:1184] SelectCompatiblePlugin(..., random): beginning
I0528 22:20:10.449160   28284 plugins.go:1213] SelectCompatiblePlugin(..., random): best plugin random-4.7.0: semver match
I0528 22:20:10.449160   28284 plugins.go:1226] SelectCompatiblePlugin(..., random): selecting plugin 'random-4.7.0': best match
I0528 22:20:10.449160   28284 plugins.go:1145] GetPluginPath(resource, random, 4.7.0): found in cache at C:\Users\IvanSabelnikov\.pulumi\plugins\resource-random-v4.7.0\pulumi-resource-random.exe
I0528 22:20:10.458176   28284 plugins.go:1184] SelectCompatiblePlugin(..., jaxxstorm/pulumi-scaleway): beginning
I0528 22:20:10.458176   28284 plugins.go:1223] SelectCompatiblePlugin(..., jaxxstorm/pulumi-scaleway): failed to find match
I0528 22:20:10.458176   28284 sink.go:147] defaultSink::Infoerr([resource plugin jaxxstorm/pulumi-scaleway-0.2.1] installing)
[resource plugin jaxxstorm/pulumi-scaleway-0.2.1] installing
I0528 22:20:10.458176   28284 plugins.go:274] jaxxstorm/pulumi-scaleway downloading from github.com/pulumi/pulumi-jaxxstorm/pulumi-scaleway/releases
I0528 22:20:10.458699   28284 plugins.go:676] full plugin download url: https://github.com/pulumi/pulumi-jaxxstorm/pulumi-scaleway/releases/download/v0.2.1/pulumi-resource-jaxxstorm%2Fpulumi-scaleway-v0.2.1-windows-amd64.tar.gz
I0528 22:20:10.458699   28284 plugins.go:677] plugin install request headers: map[User-Agent:[pulumi-cli/1 (; windows)]]
I0528 22:20:10.604635   28284 plugins.go:684] plugin install response headers: map[Cache-Control:[no-cache] Content-Security-Policy:[default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'] Content-Type:[text/plain; charset=utf-8] Date:[Sat, 28 May 2022 19:19:58 GMT] Expect-Ct:[max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"] Permissions-Policy:[interest-cohort=()] Referrer-Policy:[origin-when-cross-origin, strict-origin-when-cross-origin] Server:[GitHub.com] Set-Cookie:[_gh_sess=******; Path=/; HttpOnly; Secure; SameSite=Lax _octo=GH1.1.1154635981.1653765610; Path=/; Domain=github.com; Expires=Sun, 28 May 2023 19:20:10 GMT; Secure; SameSite=Lax logged_in=no; Path=/; Domain=github.com; Expires=Sun, 28 May 2023 19:20:10 GMT; HttpOnly; Secure; SameSite=Lax] Strict-Transport-Security:[max-age=31536000; includeSubdomains; preload] Vary:[X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With] X-Content-Type-Options:[nosniff] X-Frame-Options:[deny] X-Github-Request-Id:[F80B:93AD:1AFA021:1CA7856:629275EA] X-Xss-Protection:[0]]
I0528 22:20:10.608513   28284 plugins.go:185] jaxxstorm/pulumi-scaleway downloading from https://get.pulumi.com/releases/plugins
I0528 22:20:10.608605   28284 plugins.go:190] jaxxstorm/pulumi-scaleway downloading from https://get.pulumi.com/releases/plugins
I0528 22:20:10.609221   28284 plugins.go:676] full plugin download url: https://get.pulumi.com/releases/plugins/pulumi-resource-jaxxstorm%2Fpulumi-scaleway-v0.2.1-windows-amd64.tar.gz
I0528 22:20:10.609802   28284 plugins.go:677] plugin install request headers: map[User-Agent:[pulumi-cli/1 (; windows)]]
I0528 22:20:11.364494   28284 plugins.go:684] plugin install response headers: map[Content-Type:[application/xml] Date:[Sat, 28 May 2022 19:20:10 GMT] Server:[AmazonS3] Via:[1.1 5d40d4ac7c3a1e18748166636540091e.cloudfront.net (CloudFront)] X-Amz-Cf-Id:[-*****==] X-Amz-Cf-Pop:[WAW50-C1] X-Cache:[Error from cloudfront]]
I0528 22:20:11.368321   28284 sink.go:155] defaultSink::Error(error: [resource plugin jaxxstorm/pulumi-scaleway-0.2.1] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-jaxxstorm%2Fpulumi-scaleway-v0.2.1-windows-amd64.tar.gz)
error: [resource plugin jaxxstorm/pulumi-scaleway-0.2.1] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-jaxxstorm%2Fpulumi-scaleway-v0.2.1-windows-amd64.tar.gz
</p>
</details>

**Comment by vavsab** [comment]
@stack72 
These 2 fixes completely solve my problem:
1. [This fix](https://github.com/mapped/pulumi-astra/commit/6d5e0e2b34320eb7bd26116d4958f7dd06febbe4) makes `pulumi plugin install` work after you clear pulumi packages binary cache (I have Windows, so the cache is stored in `C:\Users\<USER>\.pulumi\plugins` on my PC).
2. [This fix](https://github.com/mapped/pulumi-astra/commit/7e9e45b6915d57977974e9c1a117c8b726e99df4) makes it to download the binary during `npm install @mapped/pulumi-astra`

**Comment by vavsab** [comment]
Is it possible to reopen this issue? It still blocks new members from creating custom packages.

**Comment by stack72** [comment]
@iwahbe looks like we need some codegen changes here?

**Comment by iwahbe** [comment]
Addressing (1): You can set the `package.json#pulumi.server` via `schema.json#pluginDownloadURL`. This should work as of https://github.com/pulumi/pulumi/issues/9661. You can set `package.json#pulumi.name` via `package.json#languages.nodejs.pluginName`. You shouldn't need a workaround.

**Comment by vavsab** [comment]
@iwahbe how do I set `schema.json#languages.nodejs.pluginName`? I cannot find the corresponding param for this in my resource.go.

**Comment by stack72** [comment]
You may need to upgrade your bridge dependency as it's relatively new - maybe last month or so

**Comment by vavsab** [comment]
@stack72 I have the latest bridge [`v3.24.1`](https://github.com/mapped/pulumi-astra/blob/b79d27498fb6c6bb698d82ca18044fe360f45fb4/provider/go.mod#L7) that was upgraded 8 days ago. I cannot find how I can generate `schema.json#languages.nodejs.pluginName` there.
![image](https://user-images.githubusercontent.com/10233442/171454922-9e0e77db-47fe-430c-bdaf-aa131c45995e.png)

**Comment by vavsab** [comment]
> Addressing (1): You can set the package.json#pulumi.server via schema.json#pluginDownloadURL. This should work as of https://github.com/pulumi/pulumi/issues/9661, @stack72 can comment how long it will take for this to filter into tfgen. I'm not sure.

@stack72 Should I create a PR to bump pulumi package [here](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/go.mod#L38)?

**Comment by stack72** [comment]
PluginDownloadURL happens outside of JavaScript - it's at the top level of SchemaInfo

**Comment by stack72** [comment]
I am saying you don't need to bump the package - pluginDownloadUrl is already supported - it's not as part of JavaScript options https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfbridge/info.go#L69

**Comment by vavsab** [comment]
> I am saying you don't need to bump the package - pluginDownloadUrl is already supported - it's not as part of JavaScript options https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfbridge/info.go#L69

It won't work until I get this fix https://github.com/pulumi/pulumi/pull/9662 
To get it we need to bump pulumi

**Comment by iwahbe** [comment]
@vavsab Am I correct that you are targeting the url `https://github.com/mapped/pulumi-astra/releases/download/v1.0.19/pulumi-resource-astra-v1.0.19-windows-amd64.tar.gz`. If so then you should have `schema.pluginDownloadURL: https://github.com/mapped/pulumi-astra/releases/download/v${VERSION}`. It looks like [the `sed` operation from `pulumi-scaleway`](https://github.com/jaxxstorm/pulumi-scaleway/blob/c5f054b607e9f5ff86539c2fcbb2bf605cfe251d/Makefile#L42) is adding the second `v`. You could remove the extra `v` at the sed call: `VERSION := $(shell pulumictl get version --language javascript | sed 's/^v//')`, but that doesn't seem like an ideal solution. @stack72 do we have a better solution?

**Comment by vavsab** [comment]
> @vavsab Am I correct that you are targeting the url https://github.com/mapped/pulumi-astra/releases/download/v1.0.19/pulumi-resource-astra-v1.0.19-windows-amd64.tar.gz

@iwahbe  Yes, correct. I can do a workaround here. The question is that then we need to include this workaround into https://github.com/pulumi/pulumi-tf-provider-boilerplate

**Comment by ringods** [comment]
Related to #9007

**Comment by vavsab** [comment]
Today it's fixed. [Use astra provider as a reference](https://github.com/pulumiverse/pulumi-astra/blob/main/provider/resources.go)
Thanks everyone for the hard work.
