### ISSUE TITLE
Empty PULUMI_CONFIG_PASSPHRASE environment variable is not taking effect

### ISSUE THREAD

**Issue by hanlins** [pulumi/pulumi#9612]
### What happened?

Set `PULUMI_CONFIG_PASSPHRASE` environment variable to an empty string, and it's not working, CLI is still asking for `PULUMI_CONFIG_PASSPHRASE`.

### Steps to reproduce

```
$ PULUMI_CONFIG_PASSPHRASE="" pulumi config set foo bar --stack foostack
Enter your passphrase to unlock config/secrets
    (set PULUMI_CONFIG_PASSPHRASE or PULUMI_CONFIG_PASSPHRASE_FILE to remember):
```

### Expected Behavior

Pulumi should proceed, and take the empty string as pulumi passphrase.

### Actual Behavior

It still asks for `PULUMI_CONFIG_PASSPHRASE` environment in prompt output.

### Versions used

```
$ pulumi version
v3.32.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by barryrobison** [comment]
Additionally this behaviour circumvents the `PULUMI_SKIP_CONFIRMATIONS` / `--non-interactive` flags by requiring interactive input.

**Comment by barryrobison** [comment]
dupe of https://github.com/pulumi/pulumi/issues/9489 ?

**Comment by hanlins** [comment]
> dupe of #9489 ?

Hi @barryrobison, thanks for the replies! Seems the conclusion[^1] is made that the change causing this issue is reverted and the issue will be fixed by next release, good to hear that! Closing this issue and subscribing the issue you mentioned :)
[^1]: https://github.com/pulumi/pulumi/issues/9489#issuecomment-1124063850
