### ISSUE TITLE
TestDynamicPython and TestEnumOutputsPython are failing in master

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi#9652]
`TestDynamicPython` and `TestEnumOutputsPython` have started to fail consistently in master - the first time I see it in https://github.com/pulumi/pulumi/runs/6526626852?check_suite_focus=true

**Comment by AaronFriel** [comment]
I think we can revise the P1/uncategorized, unless P0 means "CI is red" in which case, 👍 

The unit tests here do something which we should say is unsupported: A dynamic provider that captures global variables and determines its "id" based on how many times it's been constructed. 

Resource state for dynamic providers should be a pure function of inputs, I believe, and if a user wants a dynamic provider with multiple instances, they can supply the desired ID(s) as input props.

**Comment by mikhailshilkov** [comment]
Reopening as the master build still failed: https://github.com/pulumi/pulumi/runs/6544743093?check_suite_focus=true#step:37:156

**Comment by mikhailshilkov** [comment]
> P0 means "CI is red"

Yes, P0 is for the failing master build, not the misbehaving feature.

**Comment by AaronFriel** [comment]
Dill maintainer suggested this change:

https://github.com/uqfoundation/dill/issues/481#issuecomment-1133789848

Trying that out in a PR now.
