### ISSUE TITLE
Pulumi up takes forever and fails with an error

### ISSUE THREAD

**Issue by AMKamel** [pulumi/pulumi#9659]
### What happened?

running `pulumi --logtostderr --verbose=3 up --yes`
started to take very long time and I eventually hit control+c, this is the first time I encounter this today, also during one of those retries I say the following error, I am not sure if this is a bug or it's that pulumi service is having issues!
```
error: reading response from API: stream error: stream ID 3; INTERNAL_ERROR; received from peer
```

### Steps to reproduce

`pulumi --logtostderr --verbose=3 up --yes`

### Expected Behavior

Normal preview and update run

### Actual Behavior

lags forever most of times and sometimes fails with the error
```
error: reading response from API: stream error: stream ID 3; INTERNAL_ERROR; received from peer
```

### Versions used

CLI          
Version      3.33.1
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME           VERSION
cloudinit      1.3.0
command        0.1.0
nodejs         unknown
pulumiservice  0.0.6
random         4.7.0
vault          5.4.1

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by EvanBoyle** [comment]
@AMKamel we had a brief slowdown processing engine events yesterday about five minutes before you filed this issue. It should be resolved. 

Are you still seeing this issue?

**Comment by AMKamel** [comment]
Yes that's right, it got resolved yesterday around that time
