### ISSUE TITLE
pulumi stack rm prompt is confusing

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#9663]
when deleting a stack we ask the person to type the stack name, for example if the stack name is dev we ask them to type "dev", but if you type "dev" with the quotes it does not work.

suggest dropping both the quotes and the parens from that prompt

```
This will permanently remove the 'dev' stack!
Please confirm that this is what you'd like to do by typing ("dev"): 
```

this came up in a usability study today

**Comment by dixler** [comment]
we could tie in the thinking from #9640 and deliberately make it hard to copy paste it via double clicking. :smiling_imp:

**Comment by t0yv0** [comment]
@dixler @susanev this seems super easy to modify so why don't we include it in M77 and just get it done (without depending on #9640).

I just want to confirm if the desired prompt should look like this:

```
This will permanently remove the dev stack!
Please confirm that this is what you'd like to do by typing dev: 
```

Or like this:

```
This will permanently remove the "dev" stack!
Please confirm that this is what you'd like to do by typing "dev": 
```

I have a slight preference for seeing it with the quotes so I know it's not a normal part of the sentence, but it's lovely to use the same kind of quotes (either `"` or `'`) in both prompts, and dropping the parens.

We could also accept `"dev"` as confirmation! If the user types that we could just proceed.

**Comment by dixler** [comment]
> We could also accept both dev and "dev" as confirmation! If the user types either of those we could just proceed taking it as confirmed.

I prefer this.

**Comment by dixler** [comment]
Can I just colorize the thing the user is supposed to type to orange and remove the quotes? Seems safer than making the parsing more lax.

**Comment by t0yv0** [comment]
I'd say go ahead Kyle and make some decisions here that make sense and let's ship. I'm trying to avoid the temptation to bikeshed further.
