### ISSUE TITLE
Pulumi commands super slow when ran from inside Docker container

### ISSUE THREAD

**Issue by nemwiz** [pulumi/pulumi#9668]
### What happened?

I'm preparing a workshop and to ensure that all participants have the same environment I'm using Docker.
The workflow is the following:
- We create a Docker container with all the tools installed inside (Pulumi included)
- We `sh` into the container with `docker exec -it <container-name> /bin/bash`
- We run the commands from inside the container to provision infra and do other things

I've noticed that all pulumi commands like `pulumi up` or `pulumi preview` take significantly longer, around 4-5 mins when running inside the container. When I run the same commands outside of the container, it's blazing fast. 

Here is the Dockerfile that we are using:
```
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y --no-install-recommends curl vim unzip openssl jq ca-certificates && update-ca-certificates \
    && curl -fsSL https://deb.nodesource.com/setup_14.x | bash - && apt-get install -y nodejs \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"  \
    && unzip awscliv2.zip \
    && ./aws/install \
    && curl -fsSL https://get.pulumi.com | bash
CMD ["sleep", "infinity"]
```

### Steps to reproduce

This can be done in any Pulumi project.

- Create a Dockerfile (see above for contents)
- `cd` into the directory
- Run `docker build -t workshop-dev-environment .`
- Adjust your paths and run `docker run -d --name dev-env --mount type=bind,source="$PWD",target=/app --mount type=bind,source=<YOUR-HOME-FOLDER>/.aws,target=/root/.aws workshop-dev-environment`
- Sh into the container with `docker exec -it dev-env /bin/bash`
- Run `cd app && pulumi up`

### Expected Behavior

I expected for Pulumi to complete much faster within a few seconds.

### Actual Behavior

Pulumi up and other commands take 4-5 minutes.

### Versions used

CLI
Version      3.33.1
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.4.0
docker  3.2.0
nodejs  unknown

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in nodejs (C:\Program Files\Volta\node.exe v14.17.6)

Backend
Name           pulumi.com
URL            https://app.pulumi.com/neni-fe-workshop
User           neni-fe-workshop
Organizations  neni-fe-workshop

NAME            VERSION
@pulumi/aws     5.4.0
@pulumi/awsx    0.40.0
@pulumi/pulumi  3.33.1
@types/node     14.18.18

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
Hey @nemwiz, thanks for reporting are you able to use Windows Subsystem for Linux 2 based backend for Docker? And are you mounting files from the Windows side or a WSL Linux distribution?

Docker filesystem performance with volume mounts can sometimes be not very good especially with the large number of files Node.js places in `node_modules`. If possible, try to use WSL2.

**Comment by nemwiz** [comment]
Hey @AaronFriel . Thanks for clarifying that, this was really helpful. I am using WSL2 but the problem was that I was mounting my directory from the Windows side. As soon as I moved my project to the WSL filesystem and mounted it from there, it works like a charm. :)

For posterity, here are 2 helpful links on how to use the WSL filesystem.
https://docs.microsoft.com/en-us/windows/wsl/setup/environment (File storage section)
https://docs.docker.com/desktop/windows/wsl/#best-practices

I'm closing this issue. Thanks!

**Comment by AaronFriel** [comment]
@nemwiz glad that I was able to help!

**Comment by alfred-stokespace** [comment]
Can also confirm, we tried same setup Windows -> Docker -> Pulumi and it was awful. 
Switched from that to WSL -> Docker -> Pulumi and much... much faster!
