### ISSUE TITLE
help for pulumi stack isnt super informative

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#9677]
this came up in a usability study today

the person deployed their first stack and then wanted to review the state of the stack in the cli. they looked at both pulumi and pulumi stack help and the docs but could not figure out what command would list out their resources.

could we provide more details than just `manage stacks` to make it clear to folks that using `pulumi stack` will list out their resources and outputs?

i can share a lil video clip and an email from the user with more deets about their experience if it would be useful to you

**Comment by dixler** [comment]
help for `pulumi import` doesn't explain how to use it as well. we might want to repurpose this issue to look over all of the help text.

**Comment by t0yv0** [comment]
@cnunciato could your team help here perhaps? This is what we have:

```
Manage stacks

A stack is a named update target, and a single project may have many of them.
Each stack has a configuration and update history associated with it, stored in
the workspace, in addition to a full checkpoint of the last known good update.

Usage:
  pulumi stack [flags]
  pulumi stack [command]

Available Commands:
  change-secrets-provider Change the secrets provider for a stack
  export                  Export a stack's deployment to standard out
  graph                   Export a stack's dependency graph to a file
  history                 Display history for a stack
  import                  Import a deployment from standard in into an existing stack
  init                    Create an empty stack with the given name, ready for updates
  ls                      List stacks
  output                  Show a stack's output properties
  rename                  Rename an existing stack
  rm                      Remove a stack and its configuration
  select                  Switch the current workspace to the given stack
  tag                     Manage stack tags
  unselect                Resets stack selection from the current workspace

Flags:
  -h, --help           help for stack
  -i, --show-ids       Display each resource's provider-assigned unique ID
      --show-name      Display only the stack name
      --show-secrets   Display stack outputs which are marked as secret in plaintext
  -u, --show-urns      Display each resource's Pulumi-assigned globally unique URN
  -s, --stack string   The name of the stack to operate on. Defaults to the current stack

Global Flags:
      --color string                 Colorize output. Choices are: always, never, raw, auto (default "auto")
  -C, --cwd string                   Run pulumi as if it had been started in another directory
      --disable-integrity-checking   Disable integrity checking of checkpoint files
  -e, --emoji                        Enable emojis in the output (default true)
      --logflow                      Flow log settings to child processes (like plugins)
      --logtostderr                  Log to stderr instead of to files
      --non-interactive              Disable interactive mode for all commands
      --profiling string             Emit CPU and memory profiles and an execution trace to '[filename].[pid].{cpu,mem,trace}', respectively
      --tracing file:                Emit tracing to the specified endpoint. Use the file: scheme to write tracing data to a local file
  -v, --verbose int                  Enable verbose logging (e.g., v=3); anything >3 is very verbose

Use "pulumi stack [command] --help" for more information about a command.

```

And we have this:

https://www.pulumi.com/docs/intro/concepts/stack/

Happy to patch the `pulumi stack help` message displayed, but I think we need help writing good copy, or deciding what goes in the displayed help message.

**Comment by susanev** [comment]
@t0yv0 im happy to help here as well.

i want to clarify, that the participant didn't get to this info, they use `pulumi help` which only lists the description `Manage stacks` for the stack command. this gave them zero hint that they could use `stacks` to list their resources and outputs.

suggest a more specific description there, as manage implies that's what you  use to make changes not what you can use to see the state of things.

**Comment by t0yv0** [comment]
Ah, good. So the `pulumi stack output` is not discoverable from this? 

> . this gave them zero hint that they could use stack to list their resources and outputs.

How do I use `pulumi stack` to list the resources? I'm not sure even I discovered this functionality. Should they be using `pulumi console` to see them in the UI as the best discoverable option?

We could probably scope down this change to something really quick, but I'd like some help figuring out what we want it to look like. Is it possible to simply amend this (doesn't quite feel right, but to get the conv started):

# Current

Currently (from pulumi --help)

```
Stack Management Commands:
  new                   Create a new Pulumi project
  config                Manage configuration
  stack                 Manage stacks
  console               Opens the current stack in the Pulumi Console
  import                Import resources into an existing stack
  refresh               Refresh the resources in a stack
  state                 Edit the current stack's state
```

# Proposed

```
Stack Management Commands:
  new                   Create a new Pulumi project
  config                Manage configuration
  stack                 Manage stacks and inspect outputs
  console               Opens the current stack in the Pulumi Console
  import                Import resources into an existing stack
  refresh               Refresh the resources in a stack
  state                 Edit the current stack's state
```

**Comment by susanev** [comment]
@t0yv0 if you use the command `pulumi stack` it lists out the resources and outputs. the particular participant did their very first up and then was like, okay great now i want to see my state. its totally possible for them to go to the service to see this information. but they wanted to access it from the cli.

a few additional options to consider (also cool with ur proposal)...
`Manage and view state`
`Manage and view stack state`
`Stack state commands`
`Manage stack state
`Stack and state commands`

I'm really trying to get state into the description if possible.

some other nits it would be rad to clean up..
change to `Create Pulumi project`
change to `Open stack in Pulumi console`
change to `Import resources into stack`
change to `Refresh the stack resources`
change to `Edit stack state`

idk if you have thoughts on the need to say `current stack` in some of these. but it smells of a usability issue coverup. happy for you to explain why its important to keep the word `current` in there.

hope this is helpful!!

`
