### ISSUE TITLE
Confusing help message when incorrectly using logging flags

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#968]
When you put a logging flag between `pulumi` and the verb you're intending to log, you get a funny help message that doesn't line up with reality:

```
$ pulumi --logflow update
flag provided but not defined: -logflow
Usage of pulumi:
  -C string
    	Run pulumi as if it had been started in another directory
  -alsologtostderr
    	log to standard error as well as files
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
```

`pulumi update --logflow` works since Cobra parses it correctly.

This is confusing and it seems to me like `google/glog` is hijacking flag parsing somewhere and Cobra doesn't know about it.

**Comment by Frassle** [comment]
I hit this yesterday trying to get logs from the openstack-provider. In fact I'm still not sure what the right way to get logs out is!

**Comment by joeduffy** [comment]
I've run into this myself. I believe it's a bad combination of the way glog hijacks the flag package and how cobra uses pflag. They both rely on global statics and I think depending on the order of evaluation one or the other wins.
