### ISSUE TITLE
Do not expose IgnoreChanges on ComponentResourceOptions

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi#9704]
### What happened?

A community member was[ attempting to use `IgnoreChanges` on a Component Resource](https://github.com/pulumi/pulumi-eks/issues/709), in this case `eks.ManagedNodeGroup` and found it to be not working as they expected.

The difference between Resources and Components is subtle from a user perspective, and it seems reasonable to want to turn that knob. However, due to the specific implementation of schematized component resources, it currently is not possible to use the `IgnoreChanges` option, and currently, as per @pgavlin, this is intentional.

In the future, we may implement this option, but to expose it currently is confusing, since it doesn't actually work on Component resources. 

### Steps to reproduce

Use a component and watch your program compile with `opts=pulumi.ResourceOptions(ignore_changes=["root.nested"]),` but fail to ignore changes on `pulumi up`.

### Expected Behavior

This is really more of a UX bug, but due to this option being available, I expect changes to be ignored on all resources, including component resources.

### Actual Behavior

Setting the option does nothing to a component resource.

### Versions used

```
CLI          
Version      3.33.1
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.4.0
eks         0.40.0
kubernetes  3.19.2
python      unknown

Host     
OS       darwin
Version  11.6
Arch     x86_64
```

### Additional context

While we may in the future be able to have this option on component resources, we do not now and this is intentional.

[Internal Slack thread](https://pulumi.slack.com/archives/C02VCJEBT2N/p1653524516656529)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by AaronFriel** [comment]
@guineveresaenger I think what we want to do here, rather than change our types (which could be a breaking change & require a 4.0 release) is to improve our docs and consider warning in the engine on setting "ignore_changes" to a component.

**Comment by Frassle** [comment]
Docs update + warning + keeping a TODO comment to remind us to clean this up as part of 4.0. 

I think the warning should be pretty easy to add. Just add some diagnostic calls just before the `if remote` block at https://github.com/pulumi/pulumi/blob/master/pkg/resource/deploy/source_eval.go#L1079 if the RegisterResourceRequest had any settings that we ignore for ComponentResources. 

Oddly I think the step_generator will probably try and handle ignore_changes for non-remote components, not that it will actually do anything but change what's recorded in the state file.

**Comment by RobbieMcKinstry** [comment]
Hello! I want to make sure I'm understanding the problem. I believe I was able to reproduce the problem with this program:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const tags = {
    "issue": "9704",
    "creator": "robbiemckinstry",
};

// **Control Group:**
// Create a bucket, but set "ignoreChanges", preventing
// changes to the tags from taking effect on Update operations.
const ignoredName = "mckinstry-bug-repro-ignored";
const ignoredOpts = {
  ignoreChanges: ["tags"],
};

const ignoredBucket = new aws.s3.Bucket("ignored-bucket", {
  bucket: ignoredName,
  tags: tags
}, ignoredOpts);

// **Experimental Group:**
// Build a Component with the same structure, but
// note that the "ignoredTags" option is not acknowledged
// by the engine. Changes to the tags are applied on Update.

class OurBucketComponent extends pulumi.ComponentResource {
  public bucket: aws.s3.Bucket;

  constructor(name: string, args: any, opts?: pulumi.ComponentResourceOptions) {
    super("pkg:index:OurBucketComponent", name, args, opts);
    this.bucket = new aws.s3.Bucket(name, {
      tags: args.tags,
      bucket: args.bucketName,
    }, { parent: this });
    
    this.registerOutputs({
      bucketName: this.bucket.id,
    });
  }
}

const args = {
  bucketName: "mckinstry-bug-repro",
  tags: tags,
};

const opts = {
  ignoreChanges: ["root.nested"],
};

const bucket = new OurBucketComponent("mckinstry-bucket", args, opts);

// Export the bucket names and tags.
export const bucketName = bucket.bucket.id;
export const bucketTags = bucket.bucket.tags;

export const ignoredBucketName = ignoredBucket.id;
export const ignoredBucketTags = ignoredBucket.tags;
```

<img width="840" alt="Screen Shot 2022-06-13 at 3 50 45 PM" src="https://user-images.githubusercontent.com/4955075/173433564-0e626acb-2b1b-4652-a8ae-4671c3b30713.png">

When I change the value of `tags`, I see the changes are made on the Component resource, but not on the `ignored` bucket, despite both using the `ignoreChanges` option.
