### ISSUE TITLE
GO: Export type resourceOrInvokeOption (function)

### ISSUE THREAD

**Issue by ghostsquad** [pulumi/pulumi#9710]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'd like to write my own abstractions in Go, and utilize a common interface where I can accept `opts ...pulumi.ResourceOrInvokeOption`. Unfortunately, there's only a few options that satisfy this interface. A `ResourceOrInvokeOption` satisfies both `ResourceOption` and `InvokeOption`, but not the other way around.

This type is incredibly simple, and powerful, but I can't use it. Even if I try to implement my own, which I have tried, and that's shown below:

https://github.com/pulumi/pulumi/blob/567a5152969a5d33022b0c3aaa1b4be63c7f21a3/sdk/go/pulumi/resource.go#L149-L176

Here's what I've tried:

```go
type ResourceOrInvokeOption struct {
	pulumi.ResourceOption
	pulumi.InvokeOption
}

func ToResourceOrInvokeOption(ro pulumi.ResourceOption, io pulumi.InvokeOption) pulumi.ResourceOrInvokeOption {
	return &ResourceOrInvokeOption{
		ResourceOption: ro,
		InvokeOption:   io,
	}
}
```

```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16f8be1]
    goroutine 1 [running]:
    github.com/me/my-project/pkg/patterns.(*ResourceOrInvokeOption).github.com/pulumi/pulumi/sdk/v3/go/pulumi.applyInvokeOption(0x1962b00?, 0xc0005ef4c0?)
    	<autogenerated>:1 +0x21
    github.com/pulumi/pulumi/sdk/v3/go/pulumi.(*Context).Invoke(0xc000548140, {0x1c38590, 0x2d}, {0x0, 0x0}, {0x1962b00?, 0xc0005ef4c0?}, {0xc0005f2510, 0x3, 0x3})
    	/Users/wmcnamee/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.32.1/go/pulumi/context.go:235 +0xf82
    github.com/pulumi/pulumi-aws/sdk/v4/go/aws.GetCallerIdentity(0xc000697778?, {0xc0005f2510, 0x3, 0x3})
```

```go
	options := &invokeOptions{}
	for _, o := range opts {
		if o != nil {
			o.applyInvokeOption(options)
		}
	}
```

The issue here isn't that `o` is `nil`, it's that `applyInvokeOption` is `nil`. 

### Affected area/feature

Golang

**Comment by ghostsquad** [comment]
I think I actually solved this problem with this monstrosity. However... there are still rough sees, and I am not satisfied yet with workaround (explained below).

```Go
type resourceOrInvokeOption struct {
	pulumi.ResourceOption
	pulumi.InvokeOption
}

func ToResourceOrInvokeOption(ro pulumi.ResourceOption, io pulumi.InvokeOption) pulumi.ResourceOrInvokeOption {
	if ro != nil {
		if ro, ok := ro.(pulumi.ResourceOrInvokeOption); ok {
			return ro
		}

		return resourceOrInvokeOption{
			ResourceOption: ro,
		}
	}

	if io != nil {
		if io, ok := io.(pulumi.ResourceOrInvokeOption); ok {
			return io
		}

		return resourceOrInvokeOption{
			InvokeOption: io,
		}
	}

	return nil
}

func ToResourceAndInvokeOptions(rio ...pulumi.ResourceOrInvokeOption) ([]pulumi.ResourceOption, []pulumi.InvokeOption) {
	ro := lo.Map(rio, func(t pulumi.ResourceOrInvokeOption, _ int) pulumi.ResourceOption {
		if v, ok := t.(resourceOrInvokeOption); ok {
			return v.ResourceOption
		}

		return pulumi.ResourceOption(t)
	})

	io := lo.Map(rio, func(t pulumi.ResourceOrInvokeOption, _ int) pulumi.InvokeOption {
		if v, ok := t.(resourceOrInvokeOption); ok {
			return v.InvokeOption
		}

		return pulumi.InvokeOption(t)
	})

	return ro, io
}
```

The big issue here is that my private `resourceOrInvokeOption` is a struct not a function, like that in pulumi, and therefore when a type assertion is done, it will pass, and thus will return a value that as a _method_ that is nil, since I can't actually create something that has non-nil _private pulumi_ methods `applyResourceOption` and `applyInvokeOption`.

Example of something that _looks_ like it would work, but actually when `pulumi.Context` gets a hold of it, will fail with the `nil` exception due to the `applyInvokeOption` method being nil.

```Go
var v resourceOrInvokeOption
x, ok := v.(pulumi.ResourceOption); ok {
   ...
}
```

Which is why in my helper method `ToResourceAndInvokeOptions`, I have to explicitly check to see, if what I got was my private type implementation, and then return the _field_ (e.g. `return v.ResourceOption`) instead of itself. Pulumi will handle `nil` objects fun, but not `nil` methods.

**Comment by ghostsquad** [comment]
Context doesn't know about the fields themselves.

Note that a ResourceOrInvokeOption natively satisfies both ResourceOption and InvokeOption interfaces. Those interfaces only refer to the private `apply` methods. I cannot make anything myself that satisfies those interfaces AND has non-nil methods on them.

The upstream implementation _implements_ those `apply` methods, and within returns a nil `*resourceOption` (note the case here, again it's another private struct. I can't implement anything that returns this private struct, because it's not a valid method signature to begin with.

https://github.com/pulumi/pulumi/blob/master/sdk/go/pulumi/context.go#L235

This is where context calls the method. In the case for me, the object `o` is never nil, but the method is.

It doesn't get to the point of evaluating the return of the method based on what I'm seeing in the stack trace.

**Comment by Frassle** [comment]
> Context doesn't know about the fields themselves.
> ...
> I cannot make anything myself that satisfies those interfaces AND has non-nil methods on them.

Yes you can, and you did, because that's what struct embedding does.

```
type ResourceOrInvokeOption struct {
	pulumi.ResourceOption
	pulumi.InvokeOption
}
```
Is a struct that implements the interfaces of ResourceOption and InvokeOption by forwarding the method sets of those interfaces to fields of interface pointers in the struct.

But you do still need to set the ResourceOption or InvokeOption fields of this, and if you only set one and then pass it down a call chain that expects the other you'll get a nil pointer access.

**Comment by ghostsquad** [comment]
Ok, I did get my-side mixed up. Because I'm doing interface embedding inside a struct, internally I get some fields that would not otherwise be known by an outside caller (nor should they). Here's a playground example that I think simplifies things in order to further the conversation:

```go
package main

import (
	"github.com/kr/pretty"
)

type Foo interface {
	fooMethod()
}

type Bar interface {
	barMethod()
}

type ResourceOrInvokeOption struct {
	Foo
	Bar
}

func main() {
	pretty.Printf("%+v", ResourceOrInvokeOption{})

	r := ResourceOrInvokeOption{}
	r.fooMethod()
}
```

https://go.dev/play/p/ewLUuePl3XW

The field `Foo` inside `ResourceOrInvokeOption` is nil. Thus, when calling `r.fooMethod()` I get a nil pointer exception. So yes, I am mistaken, it's not that the method is nil, it's that my field is nil. The only thing left to do is fill in the blank with a brittle implementation like:

```go
ResourceOption: pulumi.DependsOn(nil)
```

knowing that `DependsOn` using `append`, and thus this would be a no-op.

For invoke, there is no such "hack" available.

Therefore, an alternate solution could be for Pulumi to expose a `NoopResourceOption` and `NoopInvokeOption` so that I can fill in the blanks of my own `ResourceOrInvokeOption`. But that still puts extra burden on the user. I believe a better interface would be exposing a function like this:

```go
func ToResourceOrInvokeOption(ro ResourceOption, io InvokeOption) ResourceOrInvokeOption {
   return resourceOrInvokeOption(func(ros *resourceOptions, ios *invokeOptions) {
		switch {
		case ro != nil:
			ro.applyResourceOption(ros)
		case io != nil:
			io.applyInvokeOptions(ios)
		}
	})
}
```

**Comment by Frassle** [comment]
I'm still not sure why you after this type? The only reason we have it in the SDK is as a questionable trick to work around golangs lack of method overloads.

If you have an abstraction that wants ResourceOptions or InvokeOptions I would make a tagged union to represent that (i.e. truly an "or" type) and then filter out the parts you want when calling into Pulumi.

**Comment by ghostsquad** [comment]
The interfaces here that matter are `pulumi.ResourceOption` and `pulumi.InvokeOption`. I believe what I'm describing is the fact that it's not possible for me to make a type that reasonably can do what you are suggesting.

**Comment by Frassle** [comment]
> There's no such thing as a union type in Golang.

They aren't built in, but you can write up your own type that behaves like a tagged union.
```
type TaggedUnion struct {
	ro ResourceOption
	io InvokeOption
}

func FromResourceOption(ro ResourceOption) TaggedUnion { return TaggedUnion{ro: ro} }
func FromInvokeOption(io InvokeOption) TaggedUnion     { return TaggedUnion{io: io} }
func FromResourceOrInvokeOption(rio ResourceOrInvokeOption) TaggedUnion {
	return TaggedUnion{ro: rio, io: rio}
}

func (tu TaggedUnion) GetResourceOption() ResourceOption { return tu.ro }
func (tu TaggedUnion) GetInvokeOption() InvokeOption     { return tu.io }
```

If your less bothered about compile time safety you can just have a struct with two fields. If your more bothered write a Match function rather than Get functions.

This doesn't seem like a Pulumi SDK concern?

**Comment by ghostsquad** [comment]
I interpreted as "This can act as a ResourceOrInvokeOption" (functional mindset), vs "this _is_ a ResourceAndInvokeOption".

You also mention "abusing the `Composite` function". It feels very strange to use the words "abuse" here. As a developer, I am making decisions in my program, and sometimes, I may _explicitly_ want to do nothing. What is wrong with that? I may want to even _remove_ or _unset_ an option that has been previously set. How do you expect me to be able to do these things without such tools as `nil`, or `del`, etc? There are plenty of examples of this even in the standard library:

Can you help me understand why a "no-op" is not desirable?

https://pkg.go.dev/io/ioutil#NopCloser

https://pkg.go.dev/io#Discard

https://pkg.go.dev/context#TODO

**Comment by ghostsquad** [comment]
Why would passing an empty array be an error?

**Comment by ghostsquad** [comment]
I still am trying to understand why an empty list is less valid than a list with 1 or more items in it. Or why a list of "do nothings" is less valid that a list of "do the same thing over and over".

Is this an invalid use case? It clearly doesn't do anything (no-op) since protect is false by default.

```go
[]pulumi.ResourceOption{ pulumi.Protect(false), pulumi.Protect(false) }
```

Should this panic?

```go
[]pulumi.ResourceOption{ pulumi.Protect(true), pulumi.Protect(false) }
```

What about this?

```go
[]pulumi.ResourceOption{ pulumi.Protect(true), pulumi.Protect(true) }
```

What about this?

```go
[]pulumi.ResourceOption{}
```
