### ISSUE TITLE
additionalSecretOutputs not triggering secrets provider encryption

### ISSUE THREAD

**Issue by analytical-jim** [pulumi/pulumi#9738]
### What happened?

My stack has been configured to use Google's KMS service via:
`pulumi stack change-secrets-provider "gcpkms://projects/*****/locations/*****/keyRings/*****/cryptoKeys/****"`

My current understanding is the pulumi:

Encrypts a symmetrical key using KMS but then all the values are AES256 encrypted with that key - they don't go through KMS.

I have tested encrypted values for configuration keys via `pulumi config set --secret ...` and can confirm that the values generated are NOT base64 encoded. This does work.

However; for stack outputs where the target resource attribute has been encrypted via e.g.:
    options:
      additionalSecretOutputs:
        - privateKeyData

the value returned by: 

`pulumi stack output deploy_sa_key --show-secrets ...` is a base64 encoded value. (Not the original value)
So potentially two issues:
1. The original value is not returned and
2. It is base64 encoded (confirmed by piping output from stack output to a base64 --decode --ignore-garbage command

Thanks

### Steps to reproduce

Please see above

### Expected Behavior

1. output from stack output is original value
2. should use encryption as per the secrets provider configured. Not base64 _encoding_.

### Actual Behavior

Please see description

### Versions used

v3.33.2

### Additional context

Discussed on Community Slack channel with Fraser Waters.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by analytical-jim** [comment]
Just in case relevant - I used originally `pulumi stack change-secrets-provider` to change stack secrets provider as opposed to initialising a new stack and specifying the secrets provider just in case output encryption works for an initialisation scenario...

**Comment by Frassle** [comment]
> I have tested encrypted values for configuration keys via pulumi config set --secret ... and can confirm that the values generated are NOT base64 encoded. This does work.

Was this confirmed by looking at the Pulumi.*.yaml file that has the config? 
Does `pulumi config` show the config property as "[secret]"?

> pulumi stack output deploy_sa_key --show-secrets ... is a base64 encoded value. (Not the original value)
Without --show-secrets does this then show as "[secret]"?

What does the data in the state file look like? Is it an object with a ciphertext property? Is that property just a base64 encoding of your plain value?

**Comment by Frassle** [comment]
I've also raised https://github.com/pulumi/pulumi/pull/9750 to help with making sure that the key property given in "additionalSecretOutputs" is of the right casing to match the internal property keys.

**Comment by mikhailshilkov** [comment]
@analytical-jim Could you please add a snippet of code that you use for testing, so that I could reproduce this exactly? Thank you!
