### ISSUE TITLE
Consider a `run` command

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#975]
It occurred to me that we could enable a pretty cool workflow by implementing a `run` command.  This is inspired by the way Metaparticle works.  The idea is that it would be sugar for:

* Provisioning a new stack
* Performing a `update` to populate the stack
* Block tailing all logs in the stack
* Upon ^C, performing a `destroy` and stack `rm`

The experience here is effectively that of running a distributed application directly from your terminal.  This is probably more demo material, and thought provoking, than being immensely useful in practice (although, who knows, it could turn out to be a great way for inner loop testing of stack changes).

This hypothetical flow shows off many things all at once, and might actually help describe how our system works: we could begin with a `run` demo and then say "but of course you don't want to need a terminal connected, so let's show you `update`" ... although, the name `update` isn't terribly suggestive, and something like `activate` might do a better job of driving the point home.

**Comment by lukehoban** [comment]
`pulumi watch` is part of this - and we could in principle expand that command with a flag to automatically do the `pulumi stack init`, `pulumi destroy` and `pulumi stack rm` parts of this as well.  But I'm not sure in practice we're likely to add any deeper product feature here in the forseeable future - will close this out for now.
