### ISSUE TITLE
rpc error - FailedPrecondition - cryptokey not enabled current state is: DESTROY_SCHEDULED

### ISSUE THREAD

**Issue by analytical-jim** [pulumi/pulumi#9788]
### What happened?

Google-Native: Attempted to update existing KMS KeyRing, Key to global as I want to use KMS encryption via secret manager.
All operations, including pulumi cancel result in this error. "could not desrialise deployment: constructing secrets manager of type "cloud": secrets (GCP KMS)
I resorted to removing the secret provider object definition from the state file and re-importing which resulted in this:

Pulumi Version:   v3.33.2
Go Version:       go1.17.10
Go Compiler:      gc
Architecture:     amd64
Operating System: linux
Panic:            attempt to decrypt value

goroutine 1 [running]:
runtime/debug.Stack()
        /Users/runner/hostedtoolcache/go/1.17.10/x64/src/runtime/debug/stack.go:24 +0x65
main.panicHandler()
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:29 +0x3d
panic({0x1a036c0, 0x2192b60})
        /Users/runner/hostedtoolcache/go/1.17.10/x64/src/runtime/panic.go:1038 +0x215
github.com/pulumi/pulumi/sdk/v3/go/common/resource/config.panicCrypter.DecryptValue(...)
        /Users/runner/work/pulumi/pulumi/sdk/go/common/resource/config/crypt.go:138
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializePropertyValue({0x1ac0880, 0xc00074ea50}, {0x7fc446ef0450, 0x31b3818}, {0x7fc446ef0478, 0x31b3818})
        /Users/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:597 +0x3b5
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeProperties(0xc00074ef30, {0x7fc446ef0450, 0x31b3818}, {0x7fc446ef0478, 0x31b3818})
        /Users/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:524 +0xeb
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeResource({{0xc00044d380, 0x5b}, 0x1, 0x0, {0xc0003ec140, 0x50}, {0xc000617b80, 0x31}, 0xc00074e9f0, 0xc00074ea20, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:486 +0xa5
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeDeploymentV3({{{0x2149aae0, 0xeda313d01, 0x3182fe0}, {0xc000617840, 0x40}, {0xc00054f138, 0x7}, {0x0, 0x0, 0x0}}, ...}, ...)
        /Users/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:263 +0x713
github.com/pulumi/pulumi/pkg/v3/resource/stack.DeserializeUntypedDeployment(0xc00009aba0, {0x21c29c0, 0x31b3180})
        /Users/runner/work/pulumi/pulumi/pkg/resource/stack/deployment.go:201 +0x40f
main.newStackImportCmd.func1(0x3, {0x8020103, 0x3, 0xc000bcfd78})
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/stack_import.go:79 +0x1eb
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunFunc.func1(0xe, {0xc0005d0e40, 0xc000bcfd90, 0x5ecfa5})
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:96 +0x26
github.com/pulumi/pulumi/sdk/v3/go/common/util/cmdutil.RunResultFunc.func1(0xc0001f8500, {0xc0005d0e40, 0x0, 0x2})
        /Users/runner/work/pulumi/pulumi/sdk/go/common/util/cmdutil/exit.go:112 +0x4f
github.com/spf13/cobra.(*Command).execute(0xc0001f8500, {0xc0005d0e20, 0x2, 0x2})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001ebb80)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        /Users/runner/work/pulumi/pulumi/pkg/cmd/pulumi/main.go:48 +0x45

### Steps to reproduce

Updated YAML KMS key ring resource definition from us-central1 to global for both keyring and key definition blocks.
edited state file directly and attempted to import.

### Expected Behavior

Forced reset to default secrets provider since I cannot find any way to 'reset' the provider back to the pulumi default.

### Actual Behavior

^^^

### Versions used

3.33.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@analytical-jim Thank you for filing this issue.

As I understand, you have two problems:
1. An issue updating your KeyRing resource with Google Native.
2. Your question about how to update the secrets provider.

I feel like (1) is better to be raised in the [google-native repo](https://github.com/pulumi/pulumi-google-native/issues). @Frassle commented on (2) above - you shouldn't be editing your state file directly.

Do I understand correctly that your secret provider relies on the key ring that is managed from the same stack? If so, that sounds problematic to me - you should probably split these into two stacks: one to manage the key, the other one to use it for secrets.

I'd love to learn more about your scenario if the above doesn't help.
