### ISSUE TITLE
failed to compute archive hash for "code": archive/tar: missed writing 2026611 bytes

### ISSUE THREAD

**Issue by bajtos** [pulumi/pulumi#9789]
### What happened?

I am managing my AWS Lambda function using Pulumi, using `pulumi.asset.AssetArchive` to provide list of files to upload.

Two to three weeks ago, I started to observe problems when running `pulumi up` locally on my macOS M1 machine. The archive is uploaded to AWS, but some of the larger JavaScript files are truncated in the middle. (The file sizes are between 500KB to 5MB). Fortunately, this problem was not happening when running `pulumi up` from GitHub Actions.

Occasionally, I was receiving the following error on my machine, but again not in GitHub Actions:

Formatted for clarity:
```
Diagnostics:
  pulumi:pulumi:Stack (my-stack-name):
    error: Running program '/home/runner/work/my-project/my-project/infra'
      failed with an unhandled exception:
    Error: failed to register new resource 
      my-api-handler [aws:lambda/function:Function]: 2 
      UNKNOWN: failed to compute archive hash for "code": 
      archive/tar: missed writing 2026611 bytes
```

Full error:

```

Diagnostics:
  pulumi:pulumi:Stack (my-stack-name):
    error: Running program '/home/runner/work/my-project/my-project/infra' failed with an unhandled exception:
    Error: failed to register new resource my-api-handler [aws:lambda/function:Function]: 2 UNKNOWN: failed to compute archive hash for "code": archive/tar: missed writing 2026611 bytes
        at Object.registerResource (/home/runner/work/my-project/my-project/node_modules/.pnpm/@pulumi+pulumi@3.33.2/node_modules/@pulumi/runtime/resource.ts:295:27)
        at new Resource (/home/runner/work/my-project/my-project/node_modules/.pnpm/@pulumi+pulumi@3.33.2/node_modules/@pulumi/resource.ts:393:13)
        at new CustomResource (/home/runner/work/my-project/my-project/node_modules/.pnpm/@pulumi+pulumi@3.33.2/node_modules/@pulumi/resource.ts:772:9)
        at new Function (/home/runner/work/my-project/my-project/node_modules/.pnpm/@pulumi+aws@5.6.0/node_modules/@pulumi/lambda/function.ts:505:9)
        at new ZebraDashboardApiLambda (file:///home/runner/work/my-project/my-project/infra/dashboard-lambda.js:88:20)
        at new ZebraTenant (file:///home/runner/work/my-project/my-project/infra/tenant.js:129:31)
        at file:///home/runner/work/my-project/my-project/infra/infra.js:119:19
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Today, I started to get the error "missed writing N bytes" in GitHub Actions too.

### Steps to reproduce

Am I the only person encountering this issue? If the log message does not offer any hints on what can be wrong, then I'll trim down our project into an example that can be posted in public.

High-level steps to reproduce:
1. Create a new Pulumi project in JavaScript
2. Write a JavaScript lambda handler depending on `pg` and `undici`, run `esbuild` to create the source code file for AWS, configure Pulumi's Lambda function `code` property using `pulumi.asset.AssetArchive` (see https://bajtos.net/posts/2022-05-bundling-nodejs-for-aws-lambda/)
3. Run `pulumi up`

### Expected Behavior

Pulumi packs all provided assets into an archive and uploads the archive to AWS. The archive contains the full file content, nothing is truncated.

### Actual Behavior

Sometimes, during the preview phase, I get the error `failed to compute archive hash for "code": archive/tar: missed writing 2026611 bytes`.

In other times, the Lambda code is updated and Lambda invocations fails at runtime.

```
ERROR Uncaught Exception 
```

```json
{
  "errorType":"Runtime.UserCodeSyntaxError",
  "errorMessage": "SyntaxError: Unexpected end of input",
  "stack":[
    "Runtime.UserCodeSyntaxError: SyntaxError: Unexpected end of input",
    " at _loadUserApp (file:///var/runtime/index.mjs:724:17)",
    " at async Object.module.exports.load (file:///var/runtime/index.mjs:741:21)",
    " at async file:///var/runtime/index.mjs:781:15",
    " at async file:///var/runtime/index.mjs:4:1"
  ]
}
```

### Versions used

```
CLI
Version      3.33.2
Go Version   go1.18.2
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  12.4
Arch     arm64

This project is written in nodejs (/usr/local/bin/node v16.15.0)
```

I am using `pnpm` which seems to be unsupported by `pulumi about`:
```
warning: Failed to get information about the Pulumi program's plugins: Could not find either (...)/yarn.lock or (...)/package-lock.json
```

Here is the output of `pnpm ls "@pulumi/*"`:

```
dependencies:
@pulumi/aws 5.6.0
@pulumi/awsx 0.40.0
@pulumi/postgresql 3.4.0
@pulumi/pulumi 3.33.2
@pulumi/random 4.7.0
```

### Additional context

Everything used to work fine for many months. The problems started 2-3 weeks ago. I am not aware of any change that would trigger the new behavior. When I observed the problem for the first time, I upgraded all Pulumi dependencies to the latest versions, but the problem persisted.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
> using pulumi.asset.AssetArchive to provide list of files to upload.

Is this just using AssetArchive made up of FileAssets?

**Comment by Frassle** [comment]
Ah I've found a place where we are missing an error check! Will raise a PR for that, hopefully get it in the release tomorrow and then if you give that a try we might get a better error message for what's actually gone wrong.

**Comment by Frassle** [comment]
Found another error condition we really were missing a check for!

**Comment by bajtos** [comment]
I am trying to create a small standalone project reproducing the issue. I was not able to hit the problem so far. I have two guesses:
1. Is there any per-project local state maintained by pulumi CLI? Maybe this local state is corrupted in my main project, but fine in the new project and also in GitHub Actions?
2. Perhaps there is a race condition somewhere inside Pulumi runtime and this race condition is triggered only when there are enough resources? My new project has significantly less resources that the main one, so maybe there is not enough activity to trigger the race condition.

Any other hints on what can be wrong?

**Comment by Frassle** [comment]
>Is there any per-project local state maintained by pulumi CLI? Maybe this local state is corrupted in my main project, but fine in the new project and also in GitHub Actions?

Not really. Hashing the ArchiveAssets will use temp files but they shouldn't be clashing with each other. 

> Perhaps there is a race condition somewhere inside Pulumi runtime and this race condition is triggered only when there are enough resources? My new project has significantly less resources that the main one, so maybe there is not enough activity to trigger the race condition.

Always a possibility, I've been looking through the code to see if I can see anything suspect but it all looks sensible so far.

Just to point out that release 3.34 (https://github.com/pulumi/pulumi/releases/tag/v3.34.0) is going out now, and this has some extra error checks to make sure that files have been copied as expected into the tar stream. It would be good for you to update to that and see what error messages that gives.

**Comment by bajtos** [comment]
> Just to point out that release 3.34 (https://github.com/pulumi/pulumi/releases/tag/v3.34.0) is going out now, and this has some extra error checks to make sure that files have been copied as expected into the tar stream. It would be good for you to update to that and see what error messages that gives.

Awesome! Here is the new error message I am getting from GitHub Actions:

```
Error: failed to register new resource my-api-handler [aws:lambda/function:Function]: 2 
  UNKNOWN: failed to compute archive hash for "code": 
  incorrect blob size for lambdas/dashboard.lambda.bundled.js.map: 
  expected 7236723, got 819200
```

**Comment by bajtos** [comment]
The problem happens for (relatively) smaller files too:

```
failed to compute archive hash for "code": 
incorrect blob size for lambdas/zebra-mobile-upload.lambda.bundled.js.map: 
expected 1606719, got 98304
```

**Comment by Frassle** [comment]
Well I'm glad that error message caught what I suspected was wrong. It seems that `file.Stat().Size()` is giving one number, but when we then call `io.Copy` on the file it copies far less than what stat reported.

If these files are being re-written during the update that could obviously cause this (if we stat the file get 200, but then while reading it something else truncates the file to 100). Hopefully you can confirm that nothing is touching these files during the update.

I'll keep doing some reading if there's other scenarios where State and Copy disagree on size.

Another point it would be good for you to confirm, given error messages like `incorrect blob size for lambdas/dashboard.lambda.bundled.js.map: expected 7236723, got 819200` which of those is the size reported if you check the the file size?

**Comment by Frassle** [comment]
> From what I can see in the logs for a successful run, ls -l is saying that lambdas/dashboard.lambda.bundled.js.map has file size 1610957.

Interesting that doesn't match either number in the error message!

**Comment by bajtos** [comment]
> Interesting that doesn't match either number in the error message!

IIRC, I have recently updated some of the project dependencies, thus the current CI builds are producing slightly different files.

I guess the point is that the "expected" size printed in the Pulumi error message seems to be the real file size.

I'll post another comment when I encounter the error "incorrect blob size" again. My CI builds were running fine yesterday.

Yesterday, I was also running `pulumi up` from my local machine. It finished with no errors, but some of the Lambda code archives contained files truncated in the middle. I think there is another bug lurking somewhere.

**Comment by Frassle** [comment]
> It finished with no errors, but some of the Lambda code archives contained files truncated in the middle. I think there is another bug lurking somewhere.

OK, I'll keep an eye out for anywhere else we might be truncating and not warning.

**Comment by bajtos** [comment]
After re-running the workflow, I encountered a different error:

```
failed to compute archive hash for "code": 
incorrect blob size for lambdas/dashboard.lambda.bundled.js: 
expected 6619136, got 6619136: 
archive/tar: write too long
```


Size observed by my code:

```
binary size: 7548756
file size:   7548756
```

I noticed that the file size log is printed two times. Now I am realising that I am deploying the same source code to two Lambda instances. Because each `aws.lambda.Function` is created independently and there is no way to `await` esbuild from `pulumi.ComponentResource` constructor, I think I end up running two instances of `esbuild` in parallel, writing to the same output file. 🤦🏻‍♂️

Having said that, I am not sure if this could cause `incorrect blob size` error - shouldn't Pulumi wait until all promises are resolved before it starts to build asset archives?

Conceptually, my code works like this - note that `buildLambdaArchive` calls `esbuild` and returns a promise.

```js
class DashboardApiLambda extends pulumi.ComponentResource {
  constructor(name, args, opts) {
     super('my-backend:DashboardApiLambda', name, {}, opts);
     // create role, etc.

     this.lambdaFunction = new aws.lambda.Function(name, {
      code: buildLambdaArchive(projectRoot, 'lambdas/dashboard.lambda.js', {
        [graphileCacheFile]: new pulumi.asset.FileAsset(
          path.resolve(projectRoot, graphileCacheFile),
        ),
      }),
      handler: 'index.uploadHandler',
      // (etc)
    });
  }
}

new DashboardApiLambda('tenant1', {/*...*/});
new DashboardApiLambda('tenant2', {/*...*/});
```

I am going to rework my code to ensure I am running esbuild only once for each output file.

**Comment by Frassle** [comment]
> I think I end up running two instances of esbuild in parallel, writing to the same output file. 🤦🏻‍♂️

That is probably it! I'm glad we could add enough error checking to help you find that.

> Having said that, I am not sure if this could cause incorrect blob size error - shouldn't Pulumi wait until all promises are resolved before it starts to build asset archives?

No. We'll start reading files as soon as one function gets sent to the engine.

I'd recommend either changing the esbuild so it works in a fresh folder for each lambda function, or make one function depend on the other one (Use the dependsOn resource option) so that Pulumi will wait for one to finish before starting on the next.

**Comment by bajtos** [comment]
@Frassle, thank you so much for your help! I feel a bit embarrassed about wasting your time troubleshooting the foot gun I made on my own 🙈

I decided to leverage the Node.js module caching mechanism and define the code archive as a module-global variable. 

This solved the problem with corrupted archives uploaded by `pulumi up` executed locally on my machine and the error "failed to compute archive hash" reported by GitHub Actions.

Do you envision any problems with such an approach?

Essentially:

```js
// cached at module level:
const DASHBOARD_CODE_ARCHIVE = buildLambdaArchive(
  projectRoot, 
  'lambdas/dashboard.lambda.js', 
  {
    [graphileCacheFile]: new pulumi.asset.FileAsset(
      path.resolve(projectRoot, graphileCacheFile),
    ),
  },
);

// multiple instance of this class can be safely created,
// they all share the same (Promise of) code archive
export class DashboardApiLambda extends pulumi.ComponentResource {
  constructor(name, args, opts) {
     super('my-backend:DashboardApiLambda', name, {}, opts);
     // create role, etc.

     this.lambdaFunction = new aws.lambda.Function(name, {
      code: DASHBOARD_CODE_ARCHIVE,
      handler: 'index.uploadHandler',
      // (etc)
    });
  }
}
```

**Comment by bajtos** [comment]
I am proposing to close this GitHub issue as resolved, WDYT?
