### ISSUE TITLE
Enum-only types fail NodeJS SDK build

### ISSUE THREAD

**Issue by harribo11** [pulumi/pulumi#9813]
### What happened?

When creating a simple component provider whose schema only contains resources with a flat set of properties (i.e. just strings and enums) the nodejs SDK is not compilable. The generated line:

```typescript
import { enums } from "../types
```

is not valid because `types/index.ts` has not been created.

The `types/enums/index.ts` does exist correctly, but the references to enums expects enums to be re-exported from the `types/index.ts`.

### Steps to reproduce

- [Example schema](https://github.com/pulumi/pulumi-azure-justrun/blob/v0.1.13/schema.json)
- [Generated nodejs SDK](https://github.com/pulumi/pulumi-azure-justrun/tree/v0.1.13/sdk/nodejs)
- [Failed build](https://github.com/pulumi/pulumi-azure-justrun/runs/6797942620)

### Expected Behavior

Either `types/index.ts` should be generated to re-export the enums subfolder, or the imports for enums should be written as

```typescript
import * as enums from "../types/enums";
```

### Actual Behavior

```
webapp.ts(5,59): error TS2307: Cannot find module './types' or its corresponding type declarations
```

### Additional context

A quick workaround is to add a single non-enum type definition which doesn't have to be referenced by any resources. This then generates the `types/index.ts` file correct to re-export the enums.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by harribo11** [comment]
In this case I am only creating a fairly simple component: I did not create any of my own types at first and only referenced external types. I defined enum types because referencing external enum types caused the build to fail, as the SDK would attempt to reference an enum which did not exist.

Link to SDK which references nonexistent enums file (see line 70, 90)
https://github.com/pulumi/pulumi-azure-justrun/blob/f360d03626a5e31836e96b6d2f10862297b1b424/sdk/nodejs/staticWebsite.ts

**Comment by danielrbradley** [comment]
@mikhailshilkov I walked through the issue with Harry and have reworded to include a little more detail on the scenario. Does that help answer the scenario question?

**Comment by mchaynes** [comment]
@danielrbradley I just ran into this as well. I am attempting to reference an enum for an `inputProperty` in the pulumi service provider for https://github.com/pulumi/pulumi-pulumiservice/issues/51 . 

We have some "magic" numbers defined in our [REST API documentation](https://www.pulumi.com/docs/reference/service-rest-api/#parameters-18) that define different permission levels (`read=101`, `edit=102`, `admin=103`). I'd like the generated SDK to provide these values as an enum.

**Comment by iwahbe** [comment]
This should have been fixed in https://github.com/pulumi/pulumi/pull/10286.

**Comment by mikhailshilkov** [comment]
@iwahbe 🎉  Do you want to close the issue as done?
