### ISSUE TITLE
error: could not get cloud url: could not load current project: project is missing a 'name' attribute

### ISSUE THREAD

**Issue by Frassle** [pulumi/pulumi#9836]
### Discussed in https://github.com/pulumi/pulumi/discussions/9825

<div type='discussions-op-text'>

<sup>Originally posted by **ibrahim-shaaban-hussein** June  9, 2022</sup>
$ pulumi new 
warning: A new version of Pulumi is available. To upgrade from version '3.33.2' to '3.34.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
error: could not get cloud url: could not load current project: project is missing a 'name' attribute

Ibrahims-MacBook-Pro:quickstart ibrahims.hussein$ pulumi new aws-python
warning: A new version of Pulumi is available. To upgrade from version '3.33.2' to '3.34.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
error: could not get cloud url: could not load current project: project is missing a 'name' attribute
Ibrahims-MacBook-Pro:quickstart ibrahims.hussein$ 

MacOs Catalina version 10.15.5</div>

**Comment by Frassle** [comment]
`pulumi new` seems to work fine for me on 3.34.0. Can you confirm that this is still an issue on 3.34 or later. If it is please attach the log output from `pulumi new -v11 --logtostderr` to this issue.

**Comment by mikhailshilkov** [comment]
cc @ibrahim-shaaban-hussein - I believe the question above is for you

**Comment by ibrahim-shaaban-hussein** [comment]
Yes, I solved the issue, I create Pulumi.yaml file manually in new created directory and defined the Language, and bin and work fine now

**Comment by gregmartyn** [comment]
reproducible with:

```
docker run -it \
    --workdir /app \
    --volume "$(pwd):/app" \
    --user "$(id --user)" \
    pulumi/pulumi \
    new
error: could not get cloud url: failed to get the home path: getting current user: user: Current requires cgo or $USER set in environment
```
It works if you take out the `--user "$(id --user)"` part, but then you're running as root inside the container.

**Comment by gregmartyn** [comment]
(replace `"$(id --user)"` with `"$(id -u)"` on mac)
