### ISSUE TITLE
Adding new parent to already running stack component breaks stack creation

### ISSUE THREAD

**Issue by victor-mariano-leite** [pulumi/pulumi#9844]
### What happened?

Since some resources are already created and sometimes can't be overrided, like AWS Route 53 records, if we place it under CustomComponentX ( `{ parent: parentThis }`, being `parentThis` the CustomComponentX instance ) after is already created with no parent, it might break the stack creation, even when using deleteBeforeReplace.

My hypothesis is that, when we place Route 53 under a CustomComponentX, seems like in runtime Pulumi understands it as a new component, and not a old component being recreated/replaced or moved (possible state).

Which implies that for some resources, deletion in this scenario enforces manual deletion, which is kind of a pain.

### Steps to reproduce

Our scenario was the following (considering the same amout of abstraction layers):

1. In index.ts (or whatever other language), create a MainComponent class that builds a CustomComponent class, both heirs of ComponentResource;

2. This CustomComponent implements a AWS Route 53 Record in it's constructor;

3. Run `pulumi up`, without adding the CustomComponent class instance as parent of Route 53 Record;

4. Later, add the CustomComponent class instance as parent of the same Route 53 Record with the same parameters, then run `pulumi up` again.

### Expected Behavior

Delete the parentless old Route 53 Record, and create a new with CustomComponentX as it's parent later.

### Actual Behavior

Can't create the resource, because it already exists, meaning that it's not recognizing replace behavior.

### Versions used

```CLI          
Version      3.33.2
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME     VERSION
aws      5.7.2
command  0.1.0
docker   3.2.0
github   4.12.0
nodejs   unknown
random   4.8.0

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs (/home/XXXXX/.nvm/versions/node/v17.2.0/bin/node v17.2.0)

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/XXXXX
User           XXXXX
Organizations  XXXXX

NAME                              VERSION
@pulumi/aws                       5.7.2
@pulumi/awsx                      0.40.0
@pulumi/command                   0.1.0
@pulumi/docker                    3.2.0
@pulumi/github                    4.12.0
@pulumi/pulumi                    3.34.1
@pulumi/random                    4.8.0
@soufantech/pulumi-naming         0.2.0
@commitlint/cli                   17.0.2
@commitlint/config-conventional   17.0.2
@types/node                       17.0.41
@typescript-eslint/eslint-plugin  5.27.1
@typescript-eslint/parser         5.27.1
commitizen                        4.2.4
cz-conventional-changelog         3.3.0
eslint                            8.17.0
eslint-config-airbnb-base         15.0.0
eslint-config-prettier            8.5.0
eslint-plugin-import              2.26.0
eslint-plugin-import-helpers      1.2.1
eslint-plugin-prettier            4.0.0
eslint-plugin-security            1.5.0
eslint-plugin-sonarjs             0.13.0
eslint-plugin-unused-imports      2.0.0
husky                             8.0.1
prettier                          2.6.2

**Comment by Frassle** [comment]
> My hypothesis is that, when we place Route 53 under a CustomComponentX, seems like in runtime Pulumi understands it as a new component, and not a old component being recreated/replaced or moved (possible state).

Yes it does! We identify resources by a logical name which is given by the name the user gives us in the `new Resource` constructor arguments _and_ the type of the parent. 

If your moving a resource from one parent to another you can use aliases to tell the engine to treat it as the same resource and not do a delete/create. See https://www.pulumi.com/docs/intro/concepts/resources/options/aliases/

**Comment by victor-mariano-leite** [comment]
Nice! Didn't knew that, thanks for clarifying :)
