### ISSUE TITLE
Specifying ?profile in AWS KMS provider does not work as documented

### ISSUE THREAD

**Issue by benesch** [pulumi/pulumi#9846]
### What happened?

AWS KMS providers do not support the `?profile` query parameter, even though they were recently documented to do so!

![image](https://user-images.githubusercontent.com/882976/173211906-f4e02c9b-4b0e-4199-8641-84ee0d65883c.png)

Am I holding it wrong?

### Steps to reproduce

Initialize a new stack with an `awskms` secrets provider that specifies `?profile` in the URL:

```
pulumi stack init newstack --secrets-provider "awskms:///arn:aws:kms:REDACTED?region=us-east-1&profile=my-company-profile"
```

I got this error message:

### Expected Behavior

Stack is correctly created using the credentials provided by the specified profile.

### Actual Behavior

The `?profile` parameter is rejected:

```
error: open keeper awskms:///arn:aws:kms:REDACTED?region=us-east-1&profile=my-company-profile: unknown query parameter "profile"
```

### Versions used

```
$ pulumi about
CLI
Version      3.34.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME              VERSION
aws               5.4.0
cloudinit         1.3.0
command           0.2.0
docker-buildkit   0.1.17
eks               0.39.0
fivetran          0.1.6
frontegg          0.2.22
honeycomb         0.0.8
kubernetes        3.19.1
kubernetes-proxy  0.1.3
linkerd-link      0.0.7
postgresql        3.4.0
postgresql-exec   0.1.1
python            unknown
random            4.7.0
tls               4.4.0

Host
OS       ubuntu
Version  20.04
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I think you also need to add `awssdk=v2` to the query parameters:
```
pulumi stack init newstack --secrets-provider "awskms:///arn:aws:kms:REDACTED?awssdk=v2&region=us-east-1&profile=my-company-profile"
```

If you let us know if that works, we'll get the docs updated accordingly.

**Comment by benesch** [comment]
Ooh, yes, that worked perfectly! Thanks very much!
