### ISSUE TITLE
Make previewDigest into exported type PreviewDigest

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi#9851]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

To enable the parsing of the preview digest in other programs it would be nice to be able to reference the previewDigest type directly from other programs instead of having to copy/paste it. Can we export that in future versions. 

### Affected area/feature

pulumi/pkg

**Comment by Frassle** [comment]
We have a long running plan to change the interface to the engine such that the cli and automation api both talk to the engine via a gRPC interface. This is primarily to ensure the two interfaces stay in sync as it would mean even if we fail to write a language specific wrapper function around a given message for the automation api, the raw grpc interface would still be available as a decent fallback.

As part of that work it would probably make sense to make sure that cli commands taking "--json" options end up pretty much just json printing a grpc message. Other programs could then just use the codegenerated grpc structs from the automation api sdks.

I don't think we really want people taking a dependency on /pkg itself.

**Comment by AaronFriel** [comment]
@rshade could you describe the scenario you'd need to use the Preview Digest, or if you might have a workaround available?

**Comment by AaronFriel** [comment]
@Frassle given that this digest is the output of `--json`, I think it's OK to make this type public. It just strictly helps any third party tools that run `pulumi preview` and also helps keep us honest about the contract for structured CLI output. What do you think?

**Comment by Frassle** [comment]
And as I said above, I think long term I'd like this to be declared as part of the codegen'd engine api that both the CLI and automation sdks use.
