### ISSUE TITLE
Allow BACKEND_URL to be statically defined, such as in Pulumi.yaml

### ISSUE THREAD

**Issue by ghostsquad** [pulumi/pulumi#9865]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

There are a slow of related issues with the CLI, and not being able to configure certain things explicitly within a project. One such thing is the `PULUMI_BACKEND_URL`. I've resorted to _never_ running `pulumi` naked. I have to wrap pulumi, to ensure that I'm using the proper backend, otherwise it will be whatever arbitrary backend was last "activated" in my home directory.

I possible solution is to include it in the `Pulumi.yaml` file (associated with the project, but not specific to a stack).

Example of a snippet from a `Taskfile.yml`:

```yaml
      AWS_PROFILE={{.AWS_PROFILE}} \
      PULUMI_BACKEND_URL={{.PULUMI_BACKEND_URL}} \
      pulumi \
        {{.GLOBAL_ARGS}} \
        {{.SUBCMD}} \
        {{if (list "preview" "up" "destroy" "stack" "refresh" "state" "import" | has .SUBCMD)}}--stack {{.REQUESTED_STACK}}{{end}} \
        {{.ARGS}} \
        {{.CLI_ARGS}}
```

### Affected area/feature

CLI/Stack Configuration

**Comment by Frassle** [comment]
> I possible solution is to include it in the Pulumi.yaml file (associated with the project, but not specific to a stack).

Pulumi.yaml already supports this. See the `backend` option at https://www.pulumi.com/docs/reference/pulumi-yaml/.
