### ISSUE TITLE
kms.Alias still tries run when applying changes even when it's not targetted with -t

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi#9869]
### What happened?

When doing a Pulumi run against a single, specific target, `pulumi pre` and `pulumi up` showed that only that resource would be created/updated, but when applying the change, Pulumi complained about another resource (`kms.Alias`) not being able to be created/updated.

I'm not sure this is a problem with the `kms.Alias` resource alone, but I never had issues with other resources.

### Steps to reproduce

This code is enough to reproduce the error. You can substitute `RandomPet` with any other resource, it doesn't matter, since the issue seems to be with `kms.Alias`.

```
import pulumi_random
import pulumi_aws

pulumi_random.RandomPet("pet")
key = pulumi_aws.kms.Key("key")
pulumi_aws.kms.Alias("alias", target_key_id=key.key_id)
```

Then run the code to create the single `RandomPet` resource:

```
pulumi up -t urn:pulumi:example::example::random:index/randomPet:RandomPet::pet
```

### Expected Behavior

I would expect Pulumi to create a single `RandomPet` resource.

### Actual Behavior

Pulumi creates the `RandomPet` resource and breaks after that since it doesn't have enough information to create the `kms.Alias`.

```
$ pulumi up -t urn:pulumi:example::example::random:index/randomPet:RandomPet::pet
Previewing update (example/example)

View Live: <redacted>

     Type                       Name             Plan       Info
     pulumi:pulumi:Stack        example-example             1 message
 +   └─ random:index:RandomPet  pet              create     
 
Do you want to perform this update? yes
Updating (example/example)

View Live: <redacted>

     Type                       Name             Status         Info
     pulumi:pulumi:Stack        example-example                 1 message
 +   ├─ random:index:RandomPet  pet              created        
     └─ aws:kms:Alias           alias            **failed**     1 error
 
Diagnostics:
  aws:kms:Alias (alias):
    error: aws:kms/alias:Alias resource 'alias' has a problem: Missing required argument: The argument "target_key_id" is required, but no definition was found.. Examine values at 'Alias.TargetKeyId'.
 

### Versions used

With redactions:

```
CLI          
Version      3.34.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME          VERSION
aws           5.8.0
python        unknown
random        4.8.0

Host     
OS       ubuntu
Version  21.10
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.9.7'

Current Stack: example/example

Dependencies:
NAME                 VERSION
boto3                1.24.7
pip                  22.1.2
pkg_resources        0.0.0
pulumi-aws           5.8.0
pulumi-random        4.8.0
setuptools           62.3.4
wheel                0.37.1

Pulumi locates its logs in /tmp by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This looks like we don't handle targets till after calling provider Check. I think we need to see about filtering out non-targeted resources much higher up in the step generator.

**Comment by Frassle** [comment]
Reopening as we're going to have to revert this fix.

**Comment by Sodki** [comment]
Hi @Frassle, has there been another attempt at fixing this issue? It's a big problem for us not being able to target the application of changes to certain resources. Thank you.

**Comment by Frassle** [comment]
Afraid not. The semantics of targetting are pretty complex and we haven't yet worked out why exactly the last change triggered https://github.com/pulumi/pulumi/issues/10020

**Comment by dixler** [comment]
I ran the repro and it ran successfully as it was fixed by https://github.com/pulumi/pulumi/pull/12628

Which ran into the same issues of
- https://github.com/pulumi/pulumi/issues/10020

in
- https://github.com/pulumi/pulumi/issues/12964

Which was fixed in
- https://github.com/pulumi/pulumi/pull/12973
