### ISSUE TITLE
`pulumi convert` help text is wrong

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#9892]
The help text for `pulumi convert` mentions PCL:

```
Convert resource declarations into a pulumi program.

The PCL program to convert should be supplied on stdin.
```

I think it should say YAML and probably describe the command in a bit more depth.

It also says the program is supplied on `stdin`, which I don't think is true. Instead, it uses the current directory's project. Maybe it's possible to pass it in `stdin` too? I didn't try it, but if so, this deserves a bit more articulation too.

Two other things don't look quite right:

```
Flags:
  -d, --description string   The project description; if not specified, a prompt will request it
  -n, --name string          The project name; if not specified, a prompt will request it
```

The is no prompting for these, they are just taken from the current project.

**Comment by Zaid-Ajaj** [comment]
Fixed in #10036
