### ISSUE TITLE
Ability to detect a changes in a resource name and build proper update plan

### ISSUE THREAD

**Issue by kirillmakhonin** [pulumi/pulumi#9894]
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
As a developer of Pulumi stacks I want to have an ability to automatically handle cases when I change a resource name of the same remote object. WIth current approach new resource will be created first and then old will be removed, but if these resources are pointing on the same remote object it makes a problem when I change a name of resource in Pulumi stack.

### Example use case 1 (with a resource type that can silently overwrite remote resource)
1. I have a resource aws.s3.BucketObject that creates an object in the bucket A with key B
2. I change a name for resource in Pulumi stack.
3. After `pulumi up` I see 2 changes: creation of new resource, removal of old resource
4. After I approve these changes: new file is created first (it overwrites original file), then same file is deleted by the delete operation. As a result - new aws.s3.BucketObject is pointing to not existing file in S3 bucket
5. After I run `pulumi up` next time without `-r` flag - Pulumi will not see that file does not exist in a Bucket.

### Example use case 2 (with a resource type that has a check that same resource is not created)
1. I have a resource aws.ec2.Instace that creates an instance with name C
2. I change a name for resource in Pulumi stack.
3. After `pulumi up` I see 2 changes: creation of new resource, removal of old resource
4. After I approve these changes: I get a conflict that same resource already exists

## Technical proposal
As a provider developer I want to provide an option to build internal URI of a resource (instance name for EC2, bucket+object name for S3 Object) and Pulumi engine detects that it is a resource name change and handles such changes properly

### Affected area/feature

- Providers
- Engine

**Comment by danielrbradley** [comment]
Hi @kirillmakhonin thanks for the detailed writup!

I think the solution for both of your use cases is to use [aliases resource options](https://www.pulumi.com/docs/intro/concepts/resources/options/aliases/). These allow identifiers to be changed between deployments and for the engine to see them as exactly the same resource.

Please let us know if this resolves the issue you've seen or otherwise how aliases don't cover the specific case.
