### ISSUE TITLE
Model script and command provisioning

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi#99]
As part of creating or updating infrastructure, it is often necessary to run scripts and/or commands.  We will need a first class way of modeling this in the system.

For example, we may want to provision an EC2 instance and then immediately afterwards issue an SSH command to install or configure something (a shell, Chef, Puppet script, etc).

In fact, we will be forced to do this for the self-host scenario, since we have to install and configure etcd and a volume driver on nodes after they come up.

There are a few possible approaches we could take, however here is one:

* All such scripts/commands are modeled as resources in the source and its graph.  Therefore in the program we simply say something like `let cmd = new Command({ instance: someEC2Instance, command: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf" };`, and it happens in the correct order.

* A script/command by default is treated as "mutable" and taints all resources that it refers to.  This means that a change to the script/command actually has the effect of deleting and recreating the target resource.  This ensures the scripts don't need to handle anything beyond the "initial state" per its sequence in the overall graph, which would be the case for many provisioning scripts.

* A script/command may be explicitly marked as "resilient" to indicate that the script/command understands how to handle any possible state, beyond just the initial one, and so changes to the script/command do not imply deletion and recreation of the target resource.

* All actions are sequenced just like other resource creation.  In other words, the `pulumi up` command waits for them to complete, checkpoints deployment state like it usually does, and so on.

Obviously, in all cases, there is a certain amount of "trust me" involved, however, at least the points of extensibility are well-defined and handled in a structured way by the Pulumi system.

In the future, there is another kind of script/command we may wish to consider.  I'll call this a "migration script".  This is a one-time thing that is not a persistent part of the overall resource graph, but becomes part of it for a single particular deployment.  This could be run manually (e.g., "run mu update up to step #7, pause, let me run my script, and then I'll manually resume"); or we could provide a first class way to slot that script into the graph manually as part of a deployment.

**Comment by lukehoban** [comment]
This and #127 and #1691 are all related.   Would be great to have a design proposal for first step to address some of the scenarios here in M20.

**Comment by casey-robertson** [comment]
Only chiming in because I wanted to learn a bit about Linkerd 2.x and I've already got Pulumi building K8s for me on GKE.  Would be great to deploy Linkerd as well but they only have a bash installer .. the only helm chart I saw was for legacy Linkerd 1.x

**Comment by wmorgan** [comment]
FYI we're tracking a Linkerd 2.x Helm chart here: https://github.com/linkerd/linkerd2/issues/452

PRs welcome :)

**Comment by brandonkal** [comment]
I would like to see something like this:

```ts
const vm = new pulumi.vm()

vm.onCreate([new Action(name, {
  diff: `command-to-check-script-version`,
  exec: `run-local-script`,
})])
```

Pulumi resources would expose a set of hooks for each object's CREATE, UPDATE, DELETE.
Pulumi Actions are executed for the events they are registered for. The same action can be registered for multiple objects. All actions are local commands. A diff command can be registered so that Pulumi can determine and properly record whether an action is required. Several actions can be registered with each hook, which is why I've used an array in the example above.

A hook model would provide a lot of flexibility. For instance, you could just as easily create an action that notifies a slack channel.

I would love to be able to run an Ansible playbook against newly provisioned machines.

**Comment by Place1** [comment]
I've been toying around with this idea a bit. I'm interested in using pulumi to manage the life cycle of bare metal hosts; specifically to provision and manage k8s clusters on them. Currently i'm using ansible for this task.

> A script/command by default is treated as "mutable" and taints all resources that it refers to. This means that a change to the script/command actually has the effect of deleting and recreating the target resource. This ensures the scripts don't need to handle anything beyond the "initial state" per its sequence in the overall graph, which would be the case for many provisioning scripts.

I think in my use-case things like the above wouldn't be possible.

**Comment by brandonkal** [comment]
@Place1 you could probably get this working now with my [pulumi-command](https://github.com/brandonkal/pulumi-command) provider and keeping provisioning scripts in ansible.

You give it an object with create, update, delete, diff, and you can also specify an object/string to compare. It will run an update if (1) compare input is changed, (2) update input has changed, (3) or specified diff command returns zero. [Logic here](https://github.com/brandonkal/pulumi-command/blob/master/pkg/provider/provider.go#L237-L257)

I believe this is a more reasonable approach than assuming the VM must be deleted and recreated.

I would still love to be able to run actions on Pulumi resource hooks.

**Comment by lukehoban** [comment]
For folks looking for solutions here - please do take a look at https://github.com/pulumi/examples/tree/master/aws-ts-ec2-provisioners.  There is a small helper library built with "dynamic providers" that solves for the most common cases of this.  We are still looking at adding more first-class support here in the near future - but this should help for folks who need a solution today.

**Comment by maratsh** [comment]
Does pulumi has any plans to add first class support for this any time soon ?

**Comment by greglearns** [comment]
@maratsh I just saw this today (3 hours ago I was looking for the same answer as you!) :-)
https://www.pulumi.com/docs/intro/concepts/programming-model/#providers
https://github.com/pulumi/examples/blob/master/aws-ts-ec2-provisioners/provisioners/provisioner.ts

**Comment by OneWorkAccounts** [comment]
@greglearns thanks for the comment, just started writing this myself and you saved me a lot of time!

and of course thanks to @joeduffy and the team for building this awesome platform

**Comment by shinebayar-g** [comment]
Native support for something similar to Terraform's local-exec or remote-exec would be really handy!

**Comment by napalm684** [comment]
Dynamic providers don't work for languages like CSharp, so I would say this isn't a valid workaround. I will likely have to resort to userdata.

**Comment by yellowhat** [comment]
For GCP a wrapper like this would be ideal:

```python
def run_ssh(args):
    vm_name = args[0]
    cmd = f"gcloud compute ssh {vm_name} -- touch /tmp/ssh"
    out = run(cmd, shell=True, check=True, capture_output=True)

_ = pulumi.Output.all(vm.name).apply(run_ssh)
```

**Comment by lukehoban** [comment]
Earlier this week we released a new Pulumi [Command](https://www.pulumi.com/registry/packages/command/) package in the Pulumi registry which addresses the core use cases tracked here, running scripts locally or remotely on a target VM as part of the Pulumi resource lifecycle.  

This new package is supported in all Pulumi languages.

Notably, it is focused only on running shell scripts and copying files.  It does not (yet) support running code inside the Pulumi language your deployment is authored in from within the resource lifecycle.  https://github.com/pulumi/pulumi/issues/1691 will continue to track adding deeper support in Pulumi for language-level events that can run within the resource lifecycle.

The Command package supports quite a few common patterns involving local and remote scrips execution.  There are a few notable examples in the package overview that address a number of the cases noted in replies above in this issue:
* [A simple local resource (random)](https://www.pulumi.com/registry/packages/command/#a-simple-local-resource-random))
* [Remote provisioning of an EC2 instance ](https://www.pulumi.com/registry/packages/command/#remote-provisioning-of-an-ec2-instance)
* [Invoking a Lambda during a Pulumi deployment](https://www.pulumi.com/registry/packages/command/#invoking-a-lambda-during-pulumi-deployment)
* [Using `local.Command` with `curl` to manage an external REST API](https://www.pulumi.com/registry/packages/command/#using-localcommand-with-curl-to-manage-external-rest-api)
* [Graceful cleanup of workloads in a Kubernetes cluster](https://www.pulumi.com/registry/packages/command/#graceful-cleanup-of-workloads-in-a-kubernetes-cluster)

In addition - [these 4 examples](https://github.com/pulumi/examples/pull/1141) in the examples repo which previously used a dynamic provider-based workaround are now updated to use `remote.Command` and `remote.CopyFile` from the Command package.

This new package covers the vast majority of core use cases here, so we'll close this out, and continue to track some of the additional future opportunities in https://github.com/pulumi/pulumi/issues/1691, https://github.com/pulumi/pulumi/issues/127 and https://github.com/pulumi/pulumi-command/issues.

**Comment by aslanpour** [comment]
My solution was to create a dummy ComponentResource that does the post-resource creation actions. 
Procedure:
- my actual resource is created
- a component resource sits next to the resource creation block and dependsOn the actual resource.
