### ISSUE TITLE
pulumi cli description for destroy is wrong

### ISSUE THREAD

**Issue by susanev** [pulumi/pulumi#9901]
pulumi cli description for destroy is wrong
[internal slack convo](https://pulumi.slack.com/archives/C85BS3LJZ/p1655230372394299)

file to fix up: https://github.com/pulumi/pulumi/blob/master/pkg/cmd/pulumi/destroy.go#L63-L70

**Comment by mikhailshilkov** [comment]
@kimberleyamackenzie sorry for stealing this - I opened https://github.com/pulumi/pulumi/pull/9968 to fix this, please take a look

**Comment by susanev** [comment]
no worries, thank you!!
