### ISSUE TITLE
Warn on possible missing aliases during preview

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi#9902]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

A common user issue is renaming resources which leads to a create plus delete operation which can either result in:
- Service errors – the cloud provider says the resource already exists
- Missing resources – if the create overwrites the existing resource then the delete happens after, resulting in out-of sync state (e.g. S3 Objects).

Could we therefore build a simple heuristic when there is a delete plus a create in an update plan, and the provider identifiers are the same? This could be raised as a warning to the user with the suggestion that they might be missing an alias.

**Comment by lukehoban** [comment]
This sounds similar to https://github.com/pulumi/pulumi/issues/6078.
