### ISSUE TITLE
Unable to join the Pulumi Community on Slack due to expired link

### ISSUE THREAD

**Issue by maxsxu** [pulumi/pulumi#9908]
### What happened?

The [Join the Pulumi Community on Slack](https://slack.pulumi.com/?utm_campaign=pulumi-pulumi-github-repo&utm_source=github.com&utm_medium=welcome-slack) is expired as is shown below

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/15963141/174820201-da24945a-3326-4862-838e-e079fe5d1610.png">

### Steps to reproduce

Open https://slack.pulumi.com/?utm_campaign=pulumi-pulumi-github-repo&utm_source=github.com&utm_medium=welcome-slack)

### Expected Behavior

Able to join the slack

### Actual Behavior

Unable to join the slack

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by susanev** [comment]
@maxsxu sry about the trouble! this should now be fixed, would you mind trying again?

**Comment by lukehoban** [comment]
Closing as fixed for now.

**Comment by maxsxu** [comment]
It's resolved, I'm in now. Thanks

**Comment by Maddin-M** [comment]
@susanev I currently have the same issue. I am trying to join via this link: https://join.slack.com/t/pulumi-community/shared_invite/zt-3673xlhrl-UOSZqzVeNXaskFe1jLPS2A

I get redirected to: https://pulumi-community.slack.com/join/shared_invite/zt-3673xlhrl-UOSZqzVeNXaskFe1jLPS2A#/shared-invite/error

<img width="617" height="228" alt="Image" src="https://github.com/user-attachments/assets/23881525-6d90-408c-9b3b-35a28bef672a" />
