### ISSUE TITLE
ResourceOptions.dependsOn only accepts Resources and not Output<Resource>

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi#991]
Working through the issues in https://github.com/pulumi/pulumi-cloud/pull/404 discovered that it's not possible to use `Output<Resource>` with `dependsOn`, since there is no way to get an `Output`'s list of resource dependencies. We may want to consider allowing `Output<Resource>` for `dependsOn` so that this works correctly.

**Comment by brandonbloom** [comment]
I just ran in to this. Assumed it would work, but got scolded by tsc. I ran in to this because I was using another Output's apply method to get a parameter for a resource.

**Comment by brandonbloom** [comment]
Also just figured out a workaround: Use another `apply` call.

**Comment by brandonbloom** [comment]
Now that I have a bit more experience, a warning for onlookers: Additional apply calls makes `preview` less useful. It's advisable to avoid creating resources in `apply` for that reason.

**Comment by brandonbloom** [comment]
Here's another workaround that depends on internals:

```typescript
let outputDeps = <T>(output: pulumi.Output<T>) => {
  return (<any>output).resources() as Iterable<pulumi.Resource>;
};
```

You can use it like:

```typescript
{dependsOn: [...outputDeps(someOutput)]}
```
