### ISSUE TITLE
Merge Conflicts for `CHANGELOG_PENDING`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi#9945]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We get many merge conflicts when updating changelog pending. We should fix this.

## Proposed Solutions

1. We could create a changelog folder and concatenate changes together when updating `CHANGELOG.md`.
2. Structured YAML to provide easier merge resolution.

**Comment by dixler** [comment]
Another suggestion.

I saw that [kubernetes](https://github.com/kubernetes/kubernetes) has a CHANGELOG directory. Maybe we could just copy it to the directory with the version number and git add it? I think there might be a way to preserve the file history for blames.

**Comment by RobbieMcKinstry** [comment]
@dixler is that suggestion different from (1)?

**Comment by RobbieMcKinstry** [comment]
I've got a design doc almost complete. Probably will finish it on Monday, with enough time to circulate it before iteration planning.

**Comment by dixler** [comment]
> @dixler is that suggestion different from (1)?

(1) suggests we concatenation changes and the linked approach just leaves them as is.

**Comment by dixler** [comment]
can we also factor in a way to create a failing test if we're in the middle of a release?

**Comment by RobbieMcKinstry** [comment]
> can we also factor in a way to create a failing test if we're in the middle of a release?

Hm, that's a good question. How would we determine if we're in the middle of a release?

**Comment by Frassle** [comment]
> How would we determine if we're in the middle of a release?

My last workplace had a manual toggle setup and a github action that checked the state of it. Meant that anyone could go hit the red button to block all merges unless the PR had a special trust-me comment on it.

If that's easy to setup might be good enough to just hit a "go red" button when starting the release, and "go green" when it's done.

**Comment by RobbieMcKinstry** [comment]
Yeah, I'm just wondering where the state is kept.
Something like https://github.com/marketplace/actions/stateful-action or maybe in a Workflow artifact?

**Comment by RobbieMcKinstry** [comment]
After a little reading, Actions `cache` is preferred for global state while artifacts are for swapping state between jobs in the same workflow (and storing files after execution).

**Comment by RobbieMcKinstry** [comment]
I can imagine a workflow that checks the cache for a global "Are We Releasing?" toggle, and fails the check if "Releasing=True".
Is there an easy way to trigger all PRs to rerun a status check from a workflow?

Or prior art in the form of an existing GH Action for this purpose?

**Comment by RobbieMcKinstry** [comment]
If we get merge queues, this becomes a different beast entirely, because we won't be manually merging PRs anymore.
