### ISSUE TITLE
resource name requirements have changed

### ISSUE THREAD

**Issue by that70schris** [pulumi/pulumi#9947]
### What happened?

upgrading from 3.34.1 to 3.35.0 produces an error where a resource name like `web:web` used to be acceptable, now we get an error like: "An assertion has failed: Expected string 'web:web' to be a name"

### Steps to reproduce

- start with pulumi version 3.34.1
- create a resource with a colon in the name
- upgrade to pulumi version 3.35.0
- try running a `pulumi update`

### Expected Behavior

update to proceed as normal

### Actual Behavior

update errors out complaining about the colon in the name.

### Versions used

3.34.1
3.35.0

### Additional context

I'm not sure if this was an intentional update, but this causes real issues since removing the colon from the URN will cause pulumi to try creating new resources rather than updating existing ones which isn't really an option for us.  would really appreciate reverting this behavior, or worst case a way to update our URN's without disturbing anything

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
This is because of an `AsQName` call as part of the new engine side alias logic.

**Comment by pgpx** [comment]
I got this error when upgrading to 3.35.0 and installing a cert-manager Helm chart, where some of the k8s resources generated by the Helm chart contain a `:`, for example: https://github.com/cert-manager/cert-manager/blob/b7700289f0fd20fb28b3b001df783b23ef77e6e7/deploy/charts/cert-manager/templates/webhook-rbac.yaml#L51

**Comment by Oyelowo** [comment]
I also ran into the same issue with cert-manager after I upgraded. I was initially considering a workaround of search and replace(`:` --> `__`)  but that might lead to more issues down the line
name `cert-manager-webhook:subjectaccessreviews`



```sh
panic: fatal: An assertion has failed: Expected string 'cert-manager-controller-approve:cert-manager-io' to be a name (([A-Za-z0-9_.-][A-Za-z0-9_.-]*\/)*[A-Za-z0-9_.-][A-Za-z0-9_.-]*)

goroutine 101 [running]:
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /private/tmp/pulumi-20220622-73678-r2l3nm/sdk/go/common/util/contract/failfast.go:23
github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x80?, {0x103917525?, 0x2f?}, {0x14002ca2e08?, 0x14002ca2e28?, 0x14002ca2e08?})
        /private/tmp/pulumi-20220622-73678-r2l3nm/sdk/go/common/util/contract/assert.go:33 +0xe4
github.com/pulumi/pulumi/sdk/v3/go/common/tokens.AsQName({0x14000cb3440, 0x2f})
        /private/tmp/pulumi-20220622-73678-r2l3nm/sdk/go/common/tokens/names.go:97 +0xe0
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).inheritedChildAlias(0x1400028f320, {0x14001454180, 0x3a}, {0x14000f84600, 0x2f}, {0x140014541f2, 0xc}, {0x14000bd7600, 0x3e})
        /private/tmp/pulumi-20220622-73678-r2l3nm/pkg/resource/deploy/step_generator.go:401 +0x128
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).generateSteps(0x1400028f320, {0x12c7e8818, 0x14001a8aef0})
        /private/tmp/pulumi-20220622-73678-r2l3nm/pkg/resource/deploy/step_generator.go:440 +0x20f0
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*stepGenerator).GenerateSteps(0x1400028f320, {0x12c7e8818?, 0x14001a8aef0?})
        /private/tmp/pulumi-20220622-73678-r2l3nm/pkg/resource/deploy/step_generator.go:255 +0x34
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).handleSingleEvent(0x14000780198, {0x10420b668?, 0x14001a8aef0})
        /private/tmp/pulumi-20220622-73678-r2l3nm/pkg/resource/deploy/deployment_executor.go:447 +0xd8
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute.func3(0x14000c401e0, 0x14000780198, 0x140003e5550, {0x1042200b0, 0x14000545cc0}, 0x0?, 0x0?, {0x104220158, 0x14000c25530})
        /private/tmp/pulumi-20220622-73678-r2l3nm/pkg/resource/deploy/deployment_executor.go:284 +0x1b4
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*deploymentExecutor).Execute(0x14000780198, {0x104220158?, 0x14000c25530}, {{0x12c65f298, 0x140008d7980}, 0x7fffffff, 0x0, 0x0, {0x105032b80, 0x0, ...}, ...}, ...)
        /private/tmp/pulumi-20220622-73678-r2l3nm/pkg/resource/deploy/deployment_executor.go:300 +0x850
github.com/pulumi/pulumi/pkg/v3/resource/deploy.(*Deployment).Execute(0x14000579ef0, {0x104220158, 0x14000c25530}, {{0x12c65f298, 0x140008d7980}, 0x7fffffff, 0x0, 0x0, {0x105032b80, 0x0, ...}, ...}, ...)
        /private/tmp/pulumi-20220622-73678-r2l3nm/pkg/resource/deploy/deployment.go:432 +0x8c
github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run.func1()
        /private/tmp/pulumi-20220622-73678-r2l3nm/pkg/engine/deployment.go:270 +0x174
created by github.com/pulumi/pulumi/pkg/v3/engine.(*deployment).run
        /private/tmp/pulumi-20220622-73678-r2l3nm/pkg/engine/deployment.go:253 +0x2b4

```
