### ISSUE TITLE
Support 'invoke' for dynamic providers

### ISSUE THREAD

**Issue by opichals** [pulumi/pulumi#9958]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I am looking to cross-reference already existing API resources from a pulumi dynamic provider resource instances. It would be nice to get the [invoke](https://github.com/pulumi/pulumi/pull/369) functionality available for dynamic providers.

**Comment by mikhailshilkov** [comment]
Hi @opichals thank you for filing this issue.

Could you please share more details about your target scenario? One particular aspect I'm curious about is how a dynamic provider's invoke would differ from a plain function implemented in the same program? Any code sample that you could share to illustrate?

**Comment by opichals** [comment]
@mikhailshilkov As a Pulumi rookie I was confused about the asymmetry of the dynamic providers and regular ones. As you say I could probably use a plain function.
