### ISSUE TITLE
Add stack tags to automation API

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi#9975]
We currently don't support tagging stacks using automation API

**Comment by mikhailshilkov** [comment]
Sounds like a dupe of https://github.com/pulumi/pulumi/issues/5681

**Comment by joeduffy** [comment]
What does “as not planned” mean?

**Comment by susanev** [comment]
@joeduffy it seems to be a class of issues including won't fix, duplicate, can't repro, and stale at least according to the tool tip. I think that language is pretty confusing. @mikhailshilkov can we make that language more clear?

**Comment by mikhailshilkov** [comment]
It's a github feature - I don't think the message is customizable... https://github.blog/changelog/2022-03-10-the-new-github-issues-march-10th-update/#%F0%9F%95%B5%F0%9F%8F%BD%E2%99%80%EF%B8%8F-issue-closed-reasons
