### ISSUE TITLE
"completing deletion from previous update" should be run last

### ISSUE THREAD

**Issue by wvanderdeijl** [pulumi/pulumi#9979]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I love the feature that pulumi first creates all new resources and schedules the deletion of resources at the very end. But it seems that it does not do this if the `pulumi up` failed for whatever reason. On the next `pulumi up` the scheduled deleted resources are process first before creating any new resources. This can lead to errors where the resources cannot be deleted yet.

Take the next example:
1. a stack has resource A which is used by resource B
2. we do a pulumi up that needs to replace resource A and create resource Z. Pulumi could start by creating the replacement for resource A, schedules the old resource A for deletion and then tries to create resource Z and update resource B to use the new resource A. But if the creation of resource Z fails, pulumi aborts.
3. We do another `pulumi up` and it starts with the scheduled deletion of the old resource A before doing any of the new work. But this new work would include updating resource B to use the replacement resource A. Since that hasn't run yet the deletion of the old resource A will fail as the cloud provider throws an error that this resource is still in use.

Is there a way to postpone the deletions from previous updates until *after* all the "rolling forward" has been done and queue those for the same time as all the deletions that get discovered in the current run?

### Affected area/feature

Scheduling of the deletion from previous updates

**Comment by lukehoban** [comment]
I believe this is the same issue tracked in https://github.com/pulumi/pulumi/issues/2948?

**Comment by mikhailshilkov** [comment]
Yes, looks like like a duplicate to me. I'll close this issue - let me know if that's wrong.
