### ISSUE TITLE
pulumi preview with CLI v3.35.1 runs into out-of-memory error

### ISSUE THREAD

**Issue by m42jbz** [pulumi/pulumi#9985]
### What happened?

When running pulumi preview with the pulumi CLI version 3.35.1, the preview partially succeeds and then starts to consume all of the host memory until an out-of-memory error kills the process.
[pulumi-oom-3.35.1.log](https://github.com/pulumi/pulumi/files/9000078/pulumi-oom-3.35.1.log)
.

### Steps to reproduce

use pulumi CLI 3.35.1, run preview, process runs into out-of-memory error.
use pulumi CLI 3.34.1, run preview, process displays diff and exits without error.

### Expected Behavior

preview succeeds

### Actual Behavior

preview fails with out-of-memory error

### Versions used

- Pulumi CLI v.3.15.1
- a compiled C# pulumi project
  - Pulumi 3.30.0
  - Pulumi.AzureNative 1.63.0

### Additional context

The preview gets stuck after a the diff for a virtual machine and before a virtual machine extension.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by XBeg9** [comment]
facing the same issues on the stacks that was working fine till an update

**Comment by lukehoban** [comment]
The stack trace appears to be related to the changes in https://github.com/pulumi/pulumi/pull/9731/files. 

@XBeg9 are you also using C#?

**Comment by Frassle** [comment]
So the engine now multiplies out alias combinations, so that eventually that logic can be removed from the SDKs. What I suspect is happening is that the SDK is multiplying out all the alias combinations, passing that to the engine which then multiplies everything out again. I'm looking at just replacing the simple "add each calculated urn to a slice" logic with adding it to a set instead. This should result in smaller alias lists as duplicates get stripped.

**Comment by XBeg9** [comment]
> 

no, I am using typescript (nodejs)

**Comment by m42jbz** [comment]
seeing the aliases being the prime suspect at the moment, i wanted to provide some additional context. maybe it helps to verify/narrow down the issue. the code for the resources over which the preview seems to stumble looks roughly like this:

```csharp
public class CustomVm : ComponentResource
{
    public CustomVm(
        string name,
        CustomVmArgs args,
        ComponentResourceOptions? options = null)
        : base("custom-vm", name, args, options)
    {
        var nic = new NetworkInterface($"{name}-nic",
            new NetworkInterfaceArgs {
              [REDACTED]
            },
            new CustomResourceOptions {
                Parent = this,
                Aliases = {
                    new Alias {
                        NoParent = true,
                    }
                }
            }
        );

        var vm = new VirtualMachine($"{name}-vm",
            new VirtualMachineArgs {
                [REDACTED]
            },
            new CustomResourceOptions {
                Parent = nic,
                Aliases = {
                    new Alias {
                        NoParent = true,
                    }
                },
                DeleteBeforeReplace = true
            }
        );

        var vmExt = new VirtualMachineExtension($"{name}-ext",
            new VirtualMachineExtensionArgs  {
                [REDACTED]
            },
            new CustomResourceOptions {
                Parent = vm,
                Aliases = {
                    new Alias {
                        NoParent = true,
                    }
                },
                DeleteBeforeReplace = true,
            }
        );
    }
}
```

**Comment by Frassle** [comment]
> maybe it helps to verify/narrow down the issue

Yes. You've got chained parents (ResourceA parented to ResourceB parented to ResourceC) and the alias code in the engine wasn't handling that correctly.

**Comment by Frassle** [comment]
We have decided to revert all changes related to moving alias logic to the engine for now. This will bring the engine back to how it behaved in 3.34.1. In the future we will look at massively increasing the test coverage in this area before looking to add this feature again. Release 3.35.2 should be out soon with this revert included.

**Comment by Frassle** [comment]
3.35.2 is now available which should fix this.

**Comment by Eric-Swiftly** [comment]
I can confirm that I was experiencing the same problem and 3.35.2 has resolved the issue.
