### ISSUE TITLE
Do not supply `providers` option to a custom resource when passed down from component resource

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi#9996]
When I ran the following with `providers` component resource option the preview failed with 
```
kubernetes:yaml:ConfigFile (guestbook):
    error: Error: Do not supply 'providers' option to a CustomResource. Did you mean 'provider' instead?
        at new CustomResource (/Users/vivek/code/examples/gcp-ts-gke-hello-world/node_modules/@pulumi/resource.ts:769:19)
        at new Service (/Users/vivek/code/examples/gcp-ts-gke-hello-world/node_modules/@pulumi/core/v1/service.ts:152:9)
```
Here is the code:
```ts
const guestbook = new k8s.yaml.ConfigFile("guestbook",
    {
        file: "https://raw.githubusercontent.com/pulumi/pulumi-kubernetes/master/tests/sdk/nodejs/examples/yaml-guestbook/yaml/guestbook.yaml",
        transformations: [
            (obj: any) => {
                // Do transformations on the YAML to use the same namespace and
                // labels as the NGINX stack above
                if (obj.metadata.labels) {
                    obj.metadata.labels['appClass'] = namespaceName
                } else {
                    obj.metadata.labels = appLabels
                }

                // Make the 'frontend' Service public by setting it to be of type
                // LoadBalancer
                if (obj.kind == "Service" && obj.metadata.name == "frontend") {
                    if (obj.spec) {
                        obj.spec.type = "LoadBalancer"
                    }
                }
            }
        ],
    },
    {
        providers: {kubernetes: clusterProvider},
    },
);
```

_A similar error was originally posted by @EvanBoyle in https://github.com/pulumi/pulumi/issues/5573#issuecomment-725691576_

Is it the expectation that component authors must resolve the providers resource option for the component resource down to appropriate `provider` references in the underlying custom resources?

**Comment by ringods** [comment]
@viveklak my understanding is you only pass `providers` (plural) to a component resource, and `provider` (singular) when passing the provider to a single resource. 

When passing `providers` is passed to a component resource, and the single resources have their `parent` configured correctly, the provider lookup for the child resources will happen correctly to the ones passed to the component resource.

Here you can see the provider lookup implementation, going from the `provider` on the current resource, to a lookup in `providers` map, to checking with the `parent`:

https://github.com/pulumi/pulumi/blob/350274c99637f5ad1c2f442f3b8e4ce2a23599ae/sdk/nodejs/resource.ts#L343-L361

Although this general mechanism is implemented on the abstract `Resource` class, the `CustomResource` subclass, representing single resources, prevents passing the `providers` option explicitely here:

https://github.com/pulumi/pulumi/blob/350274c99637f5ad1c2f442f3b8e4ce2a23599ae/sdk/nodejs/resource.ts#L769

So your answer is: no, once the `providers` are passed to the component resource, the lookup mechanism will map the first part of the resource type and use that as the lookup key in the parent `providers` map.

**Comment by iwahbe** [comment]
@ringods is right. You should get correct `provider` behavior by just parenting the child resource to the component.

**Comment by viveklak** [comment]
It is still pretty annoying that component authors have to prune this. Do we understand why we can't simply ignore the `providers` field for custom resources instead of erroring as we currently do?

**Comment by mikhailshilkov** [comment]
@iwahbe it's a component

https://github.com/pulumi/pulumi-kubernetes/blob/4f2602184e0032e29485479fee3c850e347ce53d/sdk/nodejs/yaml/yaml.ts#L2773

**Comment by EronWright** [comment]
Closing this as a pulumi-kubernetes issue, see follow-up: https://github.com/pulumi/pulumi-kubernetes/issues/2049
